### PR TITLE
Add postsubmit for building fast/stable image and push it

### PR DESCRIPTION
**Pull request by Jooho**
Add postsubmit configuration:
- Build fast image when master branch is changed
- Build stable image when release-v0.11.0-alpha branch is changed.

### CODE REVIEW

**Comment by Jooho** [comment]
/pj-rehearse branch-ci-opendatahub-io-modelmesh-serving-main-modelmesh-serving-stable-image-mirror

**Comment by Xaenalt** [comment]
Ok, I'm told the failing tests are ok on this, hopefully nothing breaks:

/lgtm

**Pull request merged**
