### PR TITLE
WIP Test increase azure instance size

### PR DESCRIPTION
**Pull request by xueqzhan**

### CODE REVIEW

**Comment by xueqzhan** [comment]
/pj-rehearse pull-ci-openshift-cloud-credential-operator-release-4.14-e2e-azure-upgrade

**Comment by suhanime** [comment]
@abutcher FYI

**Comment by xueqzhan** [comment]
/pj-rehearse pull-ci-openshift-cloud-credential-operator-release-4.14-e2e-azure-upgrade

**Comment by xueqzhan** [comment]
/pj-rehearse pull-ci-openshift-cloud-credential-operator-release-4.14-e2e-azure-upgrade

**Comment by xueqzhan** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.13-upgrade-from-stable-4.12-e2e-azure-sdn-upgrade

**Pull request closed without merging**
