### PR TITLE
Remove template AWS UPI job

### PR DESCRIPTION
**Pull request by patrickdillon**
This job has been replaced by a workflow/steps job.

### CODE REVIEW

**Comment by bradmwilliams** [comment]
@patrickdillon In order to clear the `release-controller-config` failure, you'll need to either:
1. Update the following lines to point to the new periodic job that calls the respective workflow
2. Remove the following lines all together

https://github.com/openshift/release/blob/ccb8b19c8181988525d801e7a39e4b3d514f5153/core-services/release-controller/_releases/release-ocp-4.12.json#L161-L166
and then run a `make release-controllers` from the root of the repo and include the changes.

**Comment by patrickdillon** [comment]
@DennisPeriquet your PR https://github.com/openshift/release/pull/34926 fixed this on master. I believe we "backported" the step registry periodics back to 4.9 so I'm updating accordingly in this PR but not sure if it's correct. Would you PTAL?

**Comment by DennisPeriquet** [comment]
@patrickdillon sure thing.   I believe the PR looks good.

But, I wonder if it's possible to remove [these](https://github.com/DennisPeriquet/release/blob/fe9dc9488046a968e43f70cb11d93c9447f7dc51/core-services/template-deprecation/_allowlist.yaml#L483-L491) lines because from what I understand, that file tracks the tests that still need conversion from templates to steps.

**Review by bradmwilliams — APPROVED** [review]

**Pull request merged**
