### PR TITLE
CNO master: add OVN AWS upgrade test

### PR DESCRIPTION
**Pull request by vrutkovs**
Adds OVN upgrade test to CNO master PRs

### CODE REVIEW

**Comment by danwinship** [comment]
This isn't inherently AWS-ish is it? Wasn't there a push to not indicate irrelevant platform requirements in test names, to make it clear they can be switched between aws and gcp if needed?

**Comment by vrutkovs** [comment]
>Wasn't there a push to not indicate irrelevant platform requirements in test names

It was, but CNO has `e2e-gcp-ovn-upgrade` already (also platform seems to be important for CNO)

**Comment by danwinship** [comment]
Wait, if we already have e2e-gcp-ovn-upgrade then do we really need e2e-aws-ovn-upgrade too?

CNO itself does not care about platform. To the extent that ovn-kubernetes cares, AWS is "easy" and GCP is "hard" (because there's extra GCP-only trickiness around load balancers) so if e2e-gcp-ovn-upgrade is passing then I can't imagine why e2e-aws-ovn-upgrade wouldn't, other than flakes...

**Comment by vrutkovs** [comment]
Oh, okay, I'm fine with dropping it then. I've seen azure/gcp/vsphere installs, so I assumed we're interested in upgrades for these (its being prepared) and also AWS install. If we're certain GCP results would work no worse then on AWS then its not worth adding more tests.

**Pull request closed without merging**
