### PR TITLE
Fixing openshift-machine-api-operator-master.yaml to use dockerfile from ocp-build-data

### PR DESCRIPTION
**Pull request by alvaroaleman**

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@elmiko if you cant review this, can you delegate the review to someone who can?

**Comment by elmiko** [comment]
@alvaroaleman we are just discussing this in chat, a question has come up about the images we use for release. is there an expectation that these images should be publicly available?

**Comment by elmiko** [comment]
just wanted to share what we've learned. the build images are available publicly by replacing "ocp" with "origin" in the container image spec. for example, http://registry.svc.ci.openshift.org/origin/builder:golang-1.13 to grab the build image. i think we will probably update our dockerfile with the origin images, at which point we might need to revisit this file.

/lgtm

**Pull request merged**
