### PR TITLE
fix image pull in ptp e2e

### PR DESCRIPTION
**Pull request by jzding**

### CODE REVIEW

**Comment by jzding** [comment]
/pj-rehearse pull-ci-openshift-ptp-operator-master-operator-e2e

**Review by nishant-parekh — COMMENTED** [review]
Why use the regex this change should be part of the change to use new release images correct?

**Comment by jzding** [comment]
> Why use the regex this change should be part of the change to use new release images correct?

regex would match `4.18` and replace the matched image with pipeline image.

**Pull request merged**
