### PR TITLE
Update Installer FCOS configuration according to latest changes in master

### PR DESCRIPTION
**Pull request by vrutkovs**
Unblocks image build in https://github.com/openshift/installer/pull/4200

### CODE REVIEW

**Comment by smarterclayton** [comment]
why is rehearse failing?

**Comment by vrutkovs** [comment]
`images` requires https://github.com/openshift/installer/pull/4200/commits/e6f19d635cf18d359eeba816bf9d9d6e299601f6 :/

**Comment by jstuever** [comment]
/cc @mandre @iamemilio 
as this is touching openstack-installer

**Pull request merged**
