### PR TITLE
Cleanup TrustyAI config

### PR DESCRIPTION
**Pull request by RobGeada**

### CODE REVIEW

**Comment by bear-redhat** [comment]
/pj-rehearse ci/rehearse/trustyai-explainability/trustyai-explainability/main/trustyai-explainability-e2e

**Comment by bear-redhat** [comment]
/pj-rehearse pull-ci-trustyai-explainability-trustyai-explainability-main-trustyai-explainability-e2e

**Review by tteofili — APPROVED** [review]
LGTM

**Review by danielezonca — APPROVED** [review]

**Pull request merged**
