### PR TITLE
Adjust unit test request to 2vcpu, 4Gi memory

### PR DESCRIPTION
**Pull request by csrwng**
Brings it back up to the original 2vcpu, and bumps up to 4Gi memory

### CODE REVIEW

**Comment by csrwng** [comment]
@stevekuznetsov @kargakis

**Comment by kargakis** [comment]
So it's enough to push changes in Github for them to be picked up by Jenkins, is that correct?

**Comment by csrwng** [comment]
@kargakis yes that's enough. The pipeline checks out the template from github every time it runs.

**Comment by kargakis** [comment]
Awesome!

**Pull request merged**
