### PR TITLE
Adding 416 gcp support

### PR DESCRIPTION
**Pull request by paigerube14**
Need to have the same cloud configuration that we ran in 4.15 on 4.16

### CODE REVIEW

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-gcp periodic-ci-redhat-chaos-prow-scripts-main-rosa-4.16-nightly-krkn-rosa-hcp-hog periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-azure periodic-ci-redhat-chaos-prow-scripts-main-rosa-4.16-nightly-krkn-tests-rosa-hcp

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-azure periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-gcp

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-azure

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-azure periodic-ci-redhat-chaos-prow-scripts-main-rosa-4.16-nightly-krkn-tests-rosa periodic-ci-redhat-chaos-prow-scripts-main-rosa-4.16-nightly-krkn-tests-rosa-hog pull-ci-redhat-chaos-prow-scripts-main-rosa-4.16-nightly-krkn-tests-rosa-infra

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-rosa-4.16-nightly-krkn-tests-rosa periodic-ci-redhat-chaos-prow-scripts-main-rosa-4.15-nightly-krkn-tests-rosa

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-rosa-4.16-nightly-krkn-tests-rosa

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-rosa-4.16-nightly-krkn-tests-rosa-hcp periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-gcp periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-azure periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-hcp-loaded-upgrade

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-hcp-loaded-upgrade periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416 periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-gcp periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-azure

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-gcp

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-azure periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416 periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-gcp

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-azure periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-gcp

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-gcp

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-gcp periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-azure

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-gcp

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-gcp

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-gcp

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-gcp

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-azure-node-tests periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-gcp-node-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-azure-node-tests periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-gcp-node-tests periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-gcp periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-azure

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-azure-node-tests periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-gcp-node-tests periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-gcp periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-azure

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-gcp periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-azure

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-hcp-loaded-upgrade

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-rosa-4.16-nightly-krkn-tests-rosa-node periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-gcp

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-gcp periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-azure

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-gcp-node-tests periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-gcp

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-cloud-gcp-api-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-gcp

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-gcp-node-tests periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-gcp

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-cloud-gcp-node-tests periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-azure periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-azure-node

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-cloud-gcp-node-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-gcp-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-gcp-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-azure

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416-azure-node

**Review by chaitanyaenr — APPROVED** [review]
/lgtm

**Review by shahsahil264 — APPROVED** [review]
LGTM

**Pull request merged**
