### PR TITLE
OCPQE-14876: Add baremetal dualstack ABI

### PR DESCRIPTION
**Pull request by mhanss**
This PR aims to add jobs for dual-stack ABI OpenShift deployment.

### CODE REVIEW

**Comment by mhanss** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-baremetal-ha-agent-dualstack-dynamic-fips-f14

**Comment by mhanss** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-baremetal-compact-agent-ipv6-dynamic-f14

**Comment by mhanss** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-baremetal-compact-agent-ipv6-dynamic-f14

**Comment by mhanss** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-baremetal-compact-agent-ipv6-dynamic-f14

**Comment by mhanss** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-baremetal-compact-agent-ipv6-dynamic-f14

**Comment by aleskandro** [comment]
Can we fix https://github.com/openshift/release/pull/53916 before testing this one so that we work with them sync?

**Comment by mhanss** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-baremetal-sno-agent-dualstack-dynamic-f14

**Comment by mhanss** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-baremetal-sno-agent-dualstack-dynamic-f14

**Comment by mhanss** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-baremetal-sno-agent-dualstack-dynamic-f14

**Comment by mhanss** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-baremetal-ha-agent-dualstack-dynamic-fips-f14

**Comment by mhanss** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-baremetal-ha-agent-ipv4-static-disc-fips-f7

**Comment by mhanss** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-baremetal-ha-agent-ipv4-static-disc-fips-f7

**Comment by mhanss** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-baremetal-ha-agent-ipv4-static-disc-fips-f7

**Pull request merged**
