### PR TITLE
Update odh-manifests to use OpenShift 4.10

### PR DESCRIPTION
**Pull request by VaishnaviHire**

### CODE REVIEW

**Comment by anishasthana** [comment]
Is there any reason we aren't bumping up to OpenShift 4.11 instead of 4.10?

**Comment by LaVLaS** [comment]
> Is there any reason we aren't bumping up to OpenShift 4.11 instead of 4.10?
Yes. @VaishnaviHire Is using this PR as a refresher on updating openshift-ci configs

**Review by anishasthana — APPROVED** [review]
/lgtm

**Review by LaVLaS — APPROVED** [review]
/lgtm

**Pull request merged**
