### PR TITLE
OCPEDGE-1374: feat: onboarding the ksan-operator repo

### PR DESCRIPTION
**Pull request by jeff-roche**

### CODE REVIEW

**Comment by suleymanakbas91** [comment]
Shall we also set up the prow config for this repo so that tools like Tide is enabled? https://github.com/openshift/release/tree/55dd2b5535f9871dfd9a6b2fc7932405493216e6/core-services/prow/02_config/openshift/lvm-operator

**Comment by jeff-roche** [comment]
> Shall we also set up the prow config for this repo so that tools like Tide is enabled? https://github.com/openshift/release/tree/55dd2b5535f9871dfd9a6b2fc7932405493216e6/core-services/prow/02_config/openshift/lvm-operator

I'll add this 👍

**Pull request merged**
