### PR TITLE
LOG-3864: Remove vector build configuration for release branch

### PR DESCRIPTION
**Pull request by xperimental**
Removes the configuration for the vector `v0.21-rh-release-5.6` branch introduced in #37714 but keeps the change to RHCOS9 for the `v0.21-rh` build.

cc @cahartma

### CODE REVIEW

**Comment by xperimental** [comment]
/pj-rehearse pull-ci-openshift-cluster-logging-operator-release-5.6-e2e pull-ci-openshift-cluster-logging-operator-release-5.6-e2e-claim-aws pull-ci-openshift-cluster-logging-operator-release-5.6-e2e-ocp-next

**Comment by xperimental** [comment]
/pj-rehearse pull-ci-openshift-cluster-logging-operator-release-5.6-e2e-ocp-previous

**Review by alanconway — APPROVED** [review]
/lgtm

**Comment by cahartma** [comment]
/pj-rehearse pull-ci-openshift-cluster-logging-operator-release-5.6-e2e-ocp-previous /pj-rehearse pull-ci-openshift-cluster-logging-operator-release-5.6-e2e /pj-rehearse pull-ci-openshift-cluster-logging-operator-release-5.6-e2e-claim-aws /pj-rehearse pull-ci-openshift-cluster-logging-operator-release-5.6-e2e-ocp-next

**Comment by Red-GV** [comment]
/pj-rehearse pull-ci-openshift-cluster-logging-operator-release-5.6-e2e-ocp-previous
/pj-rehearse pull-ci-openshift-cluster-logging-operator-release-5.6-e2e
/pj-rehearse pull-ci-openshift-cluster-logging-operator-release-5.6-e2e-ocp-next
/pj-rehearse pull-ci-openshift-cluster-logging-operator-release-5.6-e2e-claim-aws

**Comment by Red-GV** [comment]
/pj-rehearse pull-ci-openshift-cluster-logging-operator-release-5.6-e2e pull-ci-openshift-cluster-logging-operator-release-5.6-e2e-ocp-next pull-ci-openshift-cluster-logging-operator-release-5.6-e2e-claim-aws

**Comment by Red-GV** [comment]
/pj-rehearse pull-ci-openshift-cluster-logging-operator-release-5.6-e2e-claim-aws

**Comment by Red-GV** [comment]
/pj-rehearse pull-ci-openshift-cluster-logging-operator-release-5.6-e2e pull-ci-openshift-cluster-logging-operator-release-5.6-e2e-ocp-next

**Comment by Red-GV** [comment]
/pj-rehearse pull-ci-openshift-cluster-logging-operator-release-5.6-e2e-ocp-previous

**Comment by Red-GV** [comment]
/pj-rehearse pull-ci-openshift-cluster-logging-operator-release-5.6-e2e-ocp-previous

**Pull request merged**
