### PR TITLE
Cleanup old configurations

### PR DESCRIPTION
**Pull request by dhaiducek**
- Remove periodic CI check (in favor of in-repo GitHub Actions)
- Remove configurations for `2.3` and `2.4` (I've double checked for `release-*` branch protections in the repos)

### CODE REVIEW

**Review by JustinKuli — APPROVED** [review]
😟 `-8,657` 😅

**Comment by dhaiducek** [comment]
> 😟 -8,657 😅

Oh, yeah. I think this is my favorite part:

> +0 😂

**Pull request merged**
