### PR TITLE
Remove manual creation of NutanixCsiStorage CRD

### PR DESCRIPTION
**Pull request by thunderboltsid**
- The operator should install the CRD. Added a step to wait until the CRD is available before creating a NutanixCsiStorage object.
- Use a custom catalog source to unblock tests until the new operator version is available and certified for the certified-operators catalog

### CODE REVIEW

**Comment by adiantum** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-main-e2e-nutanix

**Comment by thunderboltsid** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-main-e2e-nutanix

**Comment by thunderboltsid** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-main-e2e-nutanix

**Comment by thunderboltsid** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-main-e2e-nutanix

**Comment by thunderboltsid** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-main-e2e-nutanix

**Comment by thunderboltsid** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-main-e2e-nutanix

**Comment by thunderboltsid** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-main-e2e-nutanix

**Comment by thunderboltsid** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-main-e2e-nutanix

**Comment by thunderboltsid** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-main-e2e-nutanix

**Comment by thunderboltsid** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-main-e2e-nutanix

**Comment by thunderboltsid** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-main-e2e-nutanix

**Comment by thunderboltsid** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-main-e2e-nutanix

**Pull request merged**
