### PR TITLE
hypershift: remove from base and out of date version skew tests

### PR DESCRIPTION
**Pull request by sjenning**
Remove `from: base` for image builds.

Can result in skew issues like this https://github.com/openshift/release/pull/52311

Also second commit to remove skew tests that I missed in https://github.com/openshift/release/pull/52240

### CODE REVIEW

**Comment by sjenning** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-conformance

**Review by stevekuznetsov — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
