### PR TITLE
Validate Operator Bundles

### PR DESCRIPTION
**Pull request by rajatcing**
This PR based on [9205](https://github.com/openshift/release/pull/9205).

### CODE REVIEW

**Comment by rajatsing** [comment]
cc @umangachapagain can you please review it?.

**Comment by umangachapagain** [comment]
Like the CI error says,
+ you need to generate configs
+ add config for release-4.6 branch
+ ensure you promote the correct images (master -> 4.7 release-4.6 -> 4.6 release-4.5 -> 4.5)

**Comment by rajatsing** [comment]
> Like the CI error says,
> 
> * you need to generate config
> * add config for release-4.6 branch
> * ensure you promote the correct images (master -> 4.7 release-4.6 -> 4.6 release-4.5 -> 4.5)

How can I generate all these configs and correct images?. what is the command to do that?.

**Comment by jarrpa** [comment]
@rajatsing Run `make update` from the project root.

**Comment by rajatsing** [comment]
I tried running `make update` from the root directory.
It made changes into [openshift-ocs-operator-master-presubmits.yaml](https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-master-presubmits.yaml).

But I'm not sure if these changes are valid. I'm still not sure what changes are we expecting.
@umangachapagain  can you please brief me over how can I do the following.

- Generate configs
- add config for release-4.6 branch
- promote the correct images (master -> 4.7 release-4.6 -> 4.6 release-4.5 -> 4.5)

I could not find any resources on how can I do that?. I wanted to finish this PR asap.
Thanks

**Comment by umangachapagain** [comment]
> I tried running `make update` from the root directory.
> It made changes into [openshift-ocs-operator-master-presubmits.yaml](https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-master-presubmits.yaml).
> 
> But I'm not sure if these changes are valid. I'm still not sure what changes are we expecting.
> @umangachapagain can you please brief me over how can I do the following.
> 
>     * Generate configs
> 
`make update` should do or even `make jobs`
>     * add config for release-4.6 branch
> 
Copy release-4.5 files and update it
>     * promote the correct images (master -> 4.7 release-4.6 -> 4.6 release-4.5 -> 4.5)
> 
 `core-services/image-mirroring/ocs-operator/mapping_ocs-operator_quay` is where image publishing happens and rest is within the config files that we write.
> 
> I could not find any resources on how can I do that?. I wanted to finish this PR asap.
> Thanks

**Comment by rajatsing** [comment]
@umangachapagain  I have added the config for release 4.6 and I think that you have already added 4.6 and master [mapping file](https://github.com/openshift/release/blob/master/core-services/image-mirroring/ocs-operator/mapping_ocs-operator_quay#L21-L23) already. Do you want me to add images for 4.7 in here too?.

**Comment by rajatsing** [comment]
@umangachapagain  can you review this again?. I have generated the config files. Can you please check?.

**Comment by umangachapagain** [comment]
> @umangachapagain can you review this again?. I have generated the config files. Can you please check?.

I still don't see config for `release-4.6`. Can you add that too?

**Review by umangachapagain — CHANGES_REQUESTED** [review]
How did you generate ` ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-release-4.6-presubmits.yaml ` without ` ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-release-4.6.yaml`?

Also the tests are not passing.

**Comment by rajatsing** [comment]
> How did you generate ` ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-release-4.6-presubmits.yaml ` without ` ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-release-4.6.yaml`?
> 
> 
> 
> Also the tests are not passing.

What commands to I need to pass these?.
Make update doesn't starts above ci.

**Comment by rajatsing** [comment]
> How did you generate `ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-release-4.6-presubmits.yaml` without ` ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-release-4.6.yaml`?
> 
> Also the tests are not passing.

I have to copy the changes from 4.5 and replace them appropriately.

**Comment by rajatsing** [comment]
@umangachapagain any updates or should we close it?.

**Comment by jarrpa** [comment]
With the use of the CI Steps feature, we are building and using the operator bundle, effectively validating it in practice. Thus I believe we no longer have need for this PR.

/close

**Pull request closed without merging**
