### PR TITLE
openshift-pipelines/{setup-tektoncd,setup-tektoncd-cli}

### PR DESCRIPTION
**Pull request by otaviof**
Only enabling `openshift-ci-bot` for these projects, no CI infrastructure needed.
- https://github.com/openshift-pipelines/setup-tektoncd
- https://github.com/openshift-pipelines/setup-tektoncd-cli

### CODE REVIEW

**Comment by vdemeester** [comment]
```
{"component":"checkconfig","file":"k8s.io/test-infra/prow/cmd/checkconfig/main.go:91","func":"main.reportWarning","level":"warning","msg":"the following orgs or repos enable at least one plugin that uses OWNERS files (approve, blunderbuss, owners-label) but do not enable the verify-owners plugin to ensure validity of OWNERS files: [repo: openshift-pipelines/setup-tektoncd repo: openshift-pipelines/setup-tektoncd-cli]","severity":"warning","time":"2023-03-17T11:59:56Z"}
```
We need to add `OWNERS` file on those 2 repositories

**Comment by otaviof** [comment]
> ```
> {"component":"checkconfig","file":"k8s.io/test-infra/prow/cmd/checkconfig/main.go:91","func":"main.reportWarning","level":"warning","msg":"the following orgs or repos enable at least one plugin that uses OWNERS files (approve, blunderbuss, owners-label) but do not enable the verify-owners plugin to ensure validity of OWNERS files: [repo: openshift-pipelines/setup-tektoncd repo: openshift-pipelines/setup-tektoncd-cli]","severity":"warning","time":"2023-03-17T11:59:56Z"}
> ```
> 
> We need to add `OWNERS` file on those 2 repositories

Indeed! 🏃‍♀️ The PRs to add the required file:
- https://github.com/openshift-pipelines/setup-tektoncd/pull/3
- https://github.com/openshift-pipelines/setup-tektoncd/pull/3

Thanks!

**Comment by vdemeester** [comment]
```
{"component":"checkconfig","file":"k8s.io/test-infra/prow/cmd/checkconfig/main.go:91","func":"main.reportWarning","level":"warning","msg":"[the following orgs or repos enable the bugzilla plugin but do not forbid the bugzilla/invalid-bug label for merging: [repo: openshift-pipelines/setup-tektoncd repo: openshift-pipelines/setup-tektoncd-cli], the following orgs or repos forbid the do-not-merge/release-note-label-needed label for merging but do not enable the release-note plugin: [repo: openshift-pipelines/setup-tektoncd repo: openshift-pipelines/setup-tektoncd-cli]]","severity":"warning","time":"2023-03-17T12:07:36Z"}
{"component":"checkconfig","file":"k8s.io/test-infra/prow/cmd/checkconfig/main.go:91","func":"main.reportWarning","level":"warning","msg":"[config core-services/prow/02_config/openshift-pipelines/openshift-pipelines/setup-tektoncd/_prowconfig.yaml is at an invalid location. All configs must be below core-services/prow/02_config. If they are org-specific, they must be in a folder named like the org. If they are repo-specific, they must be in a folder named like the repo below a folder named like the org., config core-services/prow/02_config/openshift-pipelines/openshift-pipelines/setup-tektoncd-cli/_prowconfig.yaml is at an invalid location. All configs must be below core-services/prow/02_config. If they are org-specific, they must be in a folder named like the org. If they are repo-specific, they must be in a folder named like the repo below a folder named like the org.]","severity":"warning","time":"2023-03-17T12:07:36Z"}
```

**Comment by otaviof** [comment]
> ```
> {"component":"checkconfig","file":"k8s.io/test-infra/prow/cmd/checkconfig/main.go:91","func":"main.reportWarning","level":"warning","msg":"[the following orgs or repos enable the bugzilla plugin but do not forbid the bugzilla/invalid-bug label for merging: [repo: openshift-pipelines/setup-tektoncd repo: openshift-pipelines/setup-tektoncd-cli], the following orgs or repos forbid the do-not-merge/release-note-label-needed label for merging but do not enable the release-note plugin: [repo: openshift-pipelines/setup-tektoncd repo: openshift-pipelines/setup-tektoncd-cli]]","severity":"warning","time":"2023-03-17T12:07:36Z"}
> {"component":"checkconfig","file":"k8s.io/test-infra/prow/cmd/checkconfig/main.go:91","func":"main.reportWarning","level":"warning","msg":"[config core-services/prow/02_config/openshift-pipelines/openshift-pipelines/setup-tektoncd/_prowconfig.yaml is at an invalid location. All configs must be below core-services/prow/02_config. If they are org-specific, they must be in a folder named like the org. If they are repo-specific, they must be in a folder named like the repo below a folder named like the org., config core-services/prow/02_config/openshift-pipelines/openshift-pipelines/setup-tektoncd-cli/_prowconfig.yaml is at an invalid location. All configs must be below core-services/prow/02_config. If they are org-specific, they must be in a folder named like the org. If they are repo-specific, they must be in a folder named like the repo below a folder named like the org.]","severity":"warning","time":"2023-03-17T12:07:36Z"}
> ```

Thanks for the heads up, the plugins and labels are consistent now.

**Review by vdemeester — APPROVED** [review]
/lgtm

**Pull request merged**
