### PR TITLE
MGMT-10256: remove redundant release-controller jobs

### PR DESCRIPTION
**Pull request by osherdp**
Since we already test stable releases of 4.y.z releases that are getting bumped in our [bump-ocp jobs](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-assisted-assisted-installer-deployment-master-bump-ocp/1523196145474473984) (and actually any changes to the ``data/`` directory in assisted-service repo), it's redundant doing those tests sometimes 4 times a day for the nightly payloads.

We can certainly postpone testing for afterwards if such thing will ever occur.

### CODE REVIEW

**Comment by osherdp** [comment]
/hold
waiting for rehearse jobs, just in case it somehow affects them

**Comment by osherdp** [comment]
/unhold
failures do not seem relevant to actual changes

**Comment by osherdp** [comment]
/hold
Might want to add something to this change

**Comment by osherdp** [comment]
> /hold Might want to add something to this change

Seems like it's not possible to do those tests for specific 4-stable versions, so I'm canceling hold
/unhold

**Review by eliorerz — APPROVED** [review]

**Pull request merged**
