### PR TITLE
ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e: Incorporate metal

### PR DESCRIPTION
**Pull request by wking**
Fold the previous metal-specific template into our multi-platform UPI template to DRY things up.  Also adds boskos/quota coverage for metal, although I'm not sure what our current capacity is.  With this commit, there will be a single knob to adjust when we discover our capacity.

/assign @abhinavdahiya

### CODE REVIEW

**Comment by wking** [comment]
[Most][1] [recent][2] [round][3] failed on a boskos hiccup.

/retest

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/5106/rehearse-5106-canary-openshift-ocp-installer-e2e-metal-4.2/2
[2]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/5106/rehearse-5106-canary-openshift-ocp-installer-e2e-metal-serial-4.2/2
[3]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/5106/rehearse-5106-pull-ci-openshift-installer-master-e2e-aws-upi/3

**Comment by wking** [comment]
[metal-4.2][1]:

```
level=fatal msg="failed to initialize the cluster: Cluster operator image-registry is still updating" 
```

But [no gathered logs][2].  Until I figure out why:

/hold

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/5106/rehearse-5106-canary-openshift-ocp-installer-e2e-metal-4.2/4
[2]: https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_release/5106/rehearse-5106-canary-openshift-ocp-installer-e2e-metal-4.2/4/artifacts/e2e-metal/installer/

**Comment by petr-muller** [comment]
Stale PR, please adapt and reopen if still needed.

/close

**Pull request closed without merging**
