### PR TITLE
Add MDR 0.2.0

### PR DESCRIPTION
**Pull request by clobrano**
Add config and presubmit configuration files for
- MDR version 0.2.0
- branch release-0.2
- OCP 4.11 to 4.14

Signed-off-by: Carlo Lobrano <c.lobrano@gmail.com>

### CODE REVIEW

**Comment by clobrano** [comment]
/pj-rehearse pull-ci-medik8s-machine-deletion-remediation-release-0.2-4.11-openshift-e2e

**Comment by clobrano** [comment]
/pj-rehearse pull-ci-medik8s-machine-deletion-remediation-release-0.2-4.13-openshift-e2e

**Comment by clobrano** [comment]
/pj-rehearse pull-ci-medik8s-machine-deletion-remediation-release-0.2-4.13-openshift-e2e

**Review by slintes — APPROVED** [review]

**Pull request merged**
