### PR TITLE
WIP: Interop - Expands jobs on ROSA 4.17

### PR DESCRIPTION
**Pull request by oharan2**

### CODE REVIEW

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.17-lp-rosa-classic-mtc-interop-aws-rosa

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.17-lp-rosa-classic-openshift-pipelines-interop-rosa-aws periodic-ci-skupperproject-skupper-openshift-smoke-test-image-main-service-interconnect-ocp4.17-lp-rosa-classic-rhsi-interop-rosa-aws periodic-ci-rhbk-sso-test-main-rhsso-product-ocp4.17-lp-rosa-classic-rhsso-interop-aws periodic-ci-rh-messaging-qe-claire-amq-broker-lpt-amq-broker-ocp4.17-lp-rosa-classic-amq-broker-rosa-aws periodic-ci-openshift-logging-extended-logging-tests-interop-main-cluster-logging-ocp4.17-lp-rosa-classic-cluster-logging-operator-rosa-aws

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.17-lp-rosa-classic-openshift-pipelines-interop-rosa-aws

**Comment by srivickynesh** [comment]
Openshift-pipelines 1.16 is GAed. Please update the branches to latest version.

**Pull request closed without merging**
