### PR TITLE
Fixing html for metrics to work in lens plugin for ci results.

### PR DESCRIPTION
**Pull request by vr4manta**
Made changes to the script logic to read in the metric JSON from the files and embed into the HTML output.

### CODE REVIEW

**Comment by vr4manta** [comment]
/pj-rehearse pull-ci-openshift-machine-api-operator-master-e2e-vsphere-ovn

**Comment by vr4manta** [comment]
/pj-rehearse pull-ci-openshift-machine-api-operator-master-e2e-vsphere-ovn

**Comment by vr4manta** [comment]
/pj-rehearse pull-ci-openshift-machine-api-operator-master-e2e-vsphere-ovn

**Comment by vr4manta** [comment]
/pj-rehearse pull-ci-openshift-machine-api-operator-master-e2e-vsphere-ovn

**Comment by vr4manta** [comment]
/pj-rehearse pull-ci-openshift-machine-api-operator-master-e2e-vsphere-ovn

**Comment by vr4manta** [comment]
/pj-rehearse pull-ci-openshift-machine-api-operator-master-e2e-vsphere-ovn

**Comment by vr4manta** [comment]
/pj-rehearse pull-ci-openshift-machine-api-operator-master-e2e-vsphere-ovn

**Comment by jcpowermac** [comment]
/hold 

just making sure all tests pass

**Pull request merged**
