### PR TITLE
Update after AMQ Streams 2.8.0 release

### PR DESCRIPTION
**Pull request by henryZrncik**

### CODE REVIEW

**Comment by im-konge** [comment]
Blocked until #58851 is merged

**Comment by im-konge** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.18-lp-interop-amq-streams-2-8-fips periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.18-lp-interop-amq-streams-2-8

**Comment by im-konge** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.18-lp-interop-amq-streams-2-8-fips periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.18-lp-interop-amq-streams-2-8

**Comment by im-konge** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.18-lp-interop-amq-streams-2-8-fips

**Comment by im-konge** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.18-lp-interop-amq-streams-2-8-fips

**Comment by im-konge** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.18-lp-interop-amq-streams-2-8-fips

**Comment by im-konge** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.18-lp-interop-amq-streams-2-7-fips periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.18-lp-interop-amq-streams-2-8

**Review by Simranpal — APPROVED** [review]
/lgtm

**Pull request merged**
