### PR TITLE
Setup E2E tests for the opendatahub-io/data-science-pipeline-operator

### PR DESCRIPTION
**Pull request by HumairAK**
In exchange for: https://github.com/openshift/release/pull/36619

### CODE REVIEW

**Comment by HumairAK** [comment]
/pj-rehearse pull-ci-opendatahub-io-data-science-pipelines-operator-main-dsp-operator-e2e

**Comment by HumairAK** [comment]
/pj-rehearse pull-ci-opendatahub-io-data-science-pipelines-operator-main-dsp-operator-e2e

**Comment by rimolive** [comment]
/pj-rehearse pull-ci-opendatahub-io-data-science-pipelines-operator-main-dsp-operator-e2e

**Comment by HumairAK** [comment]
/pj-rehearse pull-ci-opendatahub-io-data-science-pipelines-operator-main-dsp-operator-e2e

**Comment by HumairAK** [comment]
/pj-rehearse pull-ci-opendatahub-io-data-science-pipelines-operator-main-dsp-operator-e2e

**Comment by HumairAK** [comment]
/pj-rehearse pull-ci-opendatahub-io-data-science-pipelines-operator-main-dsp-operator-e2e

**Comment by HumairAK** [comment]
/pj-rehearse pull-ci-opendatahub-io-data-science-pipelines-operator-main-dsp-operator-e2e

**Comment by HumairAK** [comment]
/pj-rehearse pull-ci-opendatahub-io-data-science-pipelines-operator-main-dsp-operator-e2e

**Comment by HumairAK** [comment]
/pj-rehearse pull-ci-opendatahub-io-data-science-pipelines-operator-main-dsp-operator-e2e

**Comment by HumairAK** [comment]
/pj-rehearse pull-ci-opendatahub-io-data-science-pipelines-operator-main-dsp-operator-e2e

**Comment by HumairAK** [comment]
/pj-rehearse pull-ci-opendatahub-io-data-science-pipelines-operator-main-dsp-operator-e2e

**Pull request closed without merging**
