### PR TITLE
quay: add ovn-kubernetes image to mirroring

### PR DESCRIPTION
**Pull request by dcbw**
Add the image to the mirrors so we can reference it from places we care about, like https://github.com/openshift/cluster-network-operator/pull/44

@pecameron @stevekuznetsov @petr-muller

### CODE REVIEW

**Comment by dcbw** [comment]
@petr-muller @stevekuznetsov does this one look OK to you? Thanks!

**Comment by petr-muller** [comment]
@dcbw this is usually a @smarterclayton thing, I'd prefer him to ack this

**Comment by dcbw** [comment]
Ok I'll bug him then. Thanks!

**Comment by dcbw** [comment]
Per conversation with @smarterclayton he will do a PR that adds ovn-kubernetes and a couple others, that will supercede this PR. Keeping it open until that one shows up.

**Comment by dcbw** [comment]
Closing in favor of https://github.com/openshift/release/pull/3257

**Pull request closed without merging**
