### PR TITLE
coreos/coreos-assembler: Add a job that tests RHCOS

### PR DESCRIPTION
**Pull request by jlebon**
This builds on https://github.com/openshift/os/pull/606 and
https://github.com/openshift/release/pull/23744.

### CODE REVIEW

**Comment by jlebon** [comment]
(This is a rebase of https://github.com/openshift/release/pull/20929.)

**Comment by jlebon** [comment]
OK cool, that took almost 2 hours to run for some reason, but it worked!

**Review by ravanelli — APPROVED** [review]
LGTM.

**Pull request merged**
