### PR TITLE
MCO-998: enable synk scans for MCO

### PR DESCRIPTION
**Pull request by cheesesashimi**
Proactively runs the Snyk security scans on the MCO codebase to better detect and alert us to potential issues.

### CODE REVIEW

**Comment by cheesesashimi** [comment]
/pj-rehearse pull-ci-openshift-machine-config-operator-master-security

**Comment by cheesesashimi** [comment]
/pj-rehearse pull-ci-openshift-machine-config-operator-master-security

**Comment by sinnykumari** [comment]
ci log isn't much useful to tell why it failed. I am wondering if this is due to the fact that it found various security related issue
10 [High]   25 [Medium]   42 [Low]
And failing test is indicating that fix them to make it secure?

**Comment by cheesesashimi** [comment]
/pj-rehearse pull-ci-openshift-machine-config-operator-master-security

**Comment by cheesesashimi** [comment]
/pj-rehearse pull-ci-openshift-machine-config-operator-master-security

**Comment by cheesesashimi** [comment]
/pj-rehearse pull-ci-openshift-machine-config-operator-master-security

**Comment by cheesesashimi** [comment]
/pj-rehearse pull-ci-openshift-machine-config-operator-master-security

**Pull request merged**
