### PR TITLE
OADP-1.2: Add e2e tests on ocp-4.12

### PR DESCRIPTION
**Pull request by hhpatel14**

### CODE REVIEW

**Comment by hhpatel14** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-oadp-1.2-4.12-operator-e2e-azure

**Review by sseago — APPROVED** [review]

**Comment by hhpatel14** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-oadp-1.2-4.12-operator-e2e-aws

**Comment by hhpatel14** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-oadp-1.2-4.12-operator-e2e-gcp

**Comment by hhpatel14** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-oadp-1.2-4.12-operator-e2e-aws

**Comment by hhpatel14** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-oadp-1.2-4.12-operator-e2e-azure

**Pull request merged**
