### PR TITLE
Change golang image for file-integrity-operator and complianceascode

### PR DESCRIPTION
**Pull request by JAORMX**

### CODE REVIEW

**Review by jhrozek — APPROVED** [review]
As long as we follow up on this PR and bump the deps to 1.15 to be consistent with the rest, I'm fine.
/lgtm
/approve

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 001b63a5c8cb8bb1af544e64fa4083c1a54ee243

**Review by jhrozek — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
