### PR TITLE
Mounte push secret to the ci-tools' e2e test

### PR DESCRIPTION
**Pull request by hongkailiu**
To fix https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/1309/pull-ci-openshift-ci-tools-master-e2e/1319427712250548224

/cc @stevekuznetsov @alvaroaleman

### CODE REVIEW

**Comment by hongkailiu** [comment]
/hold

require https://github.com/openshift/release/pull/13063

**Review by alvaroaleman — APPROVED** [review]

**Comment by hongkailiu** [comment]
Yes. rehearse passed.

**Pull request merged**
