### PR TITLE
RHODS-8272: Create TrustyAI jobs within OpenDataHub.io Config

### PR DESCRIPTION
**Pull request by RobGeada**
Adds a TrustyAI section to the OpenDataHub.io CI configuration, to test the TrustyAI upstream repository.

### CODE REVIEW

**Comment by RobGeada** [comment]
pj-rehearse

**Review by Xaenalt — APPROVED** [review]

**Comment by RobGeada** [comment]
/pj-rehearse pull-ci-trustyai-explainability-trustyai-explainability-8272b-images pull-ci-trustyai-explainability-trustyai-explainability-8272b-trustyai-explainability-e2e

**Comment by RobGeada** [comment]
/pj-rehearse pull-ci-trustyai-explainability-trustyai-explainability-RHODS-8272b-images pull-ci-trustyai-explainability-trustyai-explainability-RHODS-8272b-trustyai-explainability-e2e

**Comment by RobGeada** [comment]
/pj-rehearse pull-ci-trustyai-explainability-trustyai-explainability-mainTest-trustyai-explainability-e2e

**Comment by RobGeada** [comment]
/pj-rehearse pull-ci-trustyai-explainability-trustyai-explainability-mainTest-trustyai-explainability-e2e

**Review by anishasthana — APPROVED** [review]
/lgtm

**Pull request merged**
