### PR TITLE
AWS Load Balancer Controller: Update build root from repository

### PR DESCRIPTION
**Pull request by thejasn**

### CODE REVIEW

**Comment by Miciah** [comment]
I think this should be fine now that https://github.com/openshift/aws-load-balancer-controller/pull/11 has merged.
/retest-required
/lgtm

**Comment by alebedev87** [comment]
This change has been merged as part of https://github.com/openshift/release/pull/34323.

**Comment by Miciah** [comment]
> This change has been merged as part of #34323.

So it looks like this PR can be closed.
/close

**Pull request closed without merging**
