### PR TITLE
[Test] Prepare RHCS 1.6.6 provider jobs

### PR DESCRIPTION
**Pull request by jerichokeyne**

### CODE REVIEW

**Comment by jerichokeyne** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-release-1.6.6-rosa-classic-full-resource-f7

**Comment by yuwang-RH** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-release-1.6.6-rosa-sts-advanced-critical-high-f3 periodic-ci-terraform-redhat-terraform-provider-rhcs-release-1.6.6-rosa-sts-private-medium-low-f7 periodic-ci-terraform-redhat-terraform-provider-rhcs-release-1.6.6-rosa-sts-advanced-day1-negative-f7 periodic-ci-terraform-redhat-terraform-provider-rhcs-release-1.6.6-rosa-sts-upgrade-y-f7 periodic-ci-terraform-redhat-terraform-provider-rhcs-release-1.6.6-rosa-classic-full-resource-f7 periodic-ci-terraform-redhat-terraform-provider-rhcs-release-1.6.6-rosa-hcp-full-resource-f7 periodic-ci-terraform-redhat-terraform-provider-rhcs-release-1.6.6-rosa-hcp-advanced-critical-high-f3 periodic-ci-terraform-redhat-terraform-provider-rhcs-release-1.6.6-rosa-hcp-advanced-medium-low-f7 periodic-ci-terraform-redhat-terraform-provider-rhcs-release-1.6.6-rosa-hcp-private-medium-low-f7 periodic-ci-terraform-redhat-terraform-provider-rhcs-release-1.6.6-rosa-hcp-arm-f7 periodic-ci-terraform-redhat-terraform-provider-rhcs-release-1.6.6-rosa-hcp-network-f7 periodic-ci-terraform-redhat-terraform-provider-rhcs-release-1.6.6-rosa-hcp-encryption-f7

**Comment by jerichokeyne** [comment]
/pj-rehease rosa-hcp-advanced-critical-high-f3 rosa-hcp-private-medium-low-f7 rosa-hcp-network-f7 rosa-hcp-encryption-f7

**Comment by jerichokeyne** [comment]
/pj-rehearse rosa-hcp-advanced-critical-high-f3 rosa-hcp-private-medium-low-f7 rosa-hcp-network-f7 rosa-hcp-encryption-f7

**Comment by jerichokeyne** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-release-1.6.6-rosa-hcp-advanced-critical-high-f3 periodic-ci-terraform-redhat-terraform-provider-rhcs-release-1.6.6-rosa-hcp-private-medium-low-f7 periodic-ci-terraform-redhat-terraform-provider-rhcs-release-1.6.6-rosa-hcp-network-f7 periodic-ci-terraform-redhat-terraform-provider-rhcs-release-1.6.6-rosa-hcp-encryption-f7

**Pull request closed without merging**
