### PR TITLE
Include openstack dualstack presubmit job to MAPO

### PR DESCRIPTION
**Pull request by MaysaMacedo**

### CODE REVIEW

**Comment by MaysaMacedo** [comment]
Result of periodic jobs https://prow.ci.openshift.org/job-history/origin-ci-test/logs/periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.14-e2e-openstack-dualstack-techpreview
The failures are related to when our cloud was down

**Review by gryf — APPROVED** [review]
/lgtm

**Pull request merged**
