### PR TITLE
MSI: add support to install operator from iib

### PR DESCRIPTION
**Pull request by rnetser**
https://raw.githubusercontent.com/RedHatQE/openshift-ci-trigger/main/operators-latest-iib.json is used to monitor new index images for operators and to trigger related openshift ci jobs.

### CODE REVIEW

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-gpu-servicemesh-operators-v4.13-IIB-sanity-rosa-rhods-gpu-servicemesh

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-gpu-servicemesh-operators-v4.13-IIB-sanity-rosa-rhods-gpu-servicemesh

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-gpu-servicemesh-operators-v4.13-IIB-sanity-rosa-rhods-gpu-servicemesh

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-gpu-servicemesh-operators-v4.13-IIB-sanity-rosa-rhods-gpu-servicemesh

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-gpu-servicemesh-operators-v4.13-IIB-sanity-rosa-rhods-gpu-servicemesh

**Review by myakove — APPROVED** [review]

**Pull request merged**
