### PR TITLE
rename secrets in ci-operator templates

### LINKED ISSUE #1370: Ensure the same secret name is reused locally and in CI
https://github.com/openshift/release/tree/master/projects/azure#test-ci-operator-jobs

We should figure out how to use the same name in both runs, it's annoying to have to rename the secret in the template to test locally.

@openshift/sig-azure 
/kind cleanup

### PR DESCRIPTION
**Pull request by charlesakalugwu**
closes #1370 

@mjudeikis

### CODE REVIEW

**Comment by kargakis** [comment]
You should also update the README [here](https://github.com/openshift/release/tree/master/projects/azure#test-ci-operator-jobs) to remove the section about renaming the template secret.

**Comment by charlesakalugwu** [comment]
@kargakis theres a PR open for that #1809

**Pull request merged**
