### PR TITLE
openstack: Use the new resource pruner for cleanup

### PR DESCRIPTION
**Pull request by pierreprinetti**
The old script ran `openshift-install destroy cluster`; this one doesn't. The advantage here is that each stale resource is properly tracked, and this enables us to better diagnose potential issues in the OpenStack resource lifecycle management within OpenShift.

### CODE REVIEW

**Comment by pierreprinetti** [comment]
/pj-rehearse periodic-ci-shiftstack-prune-main-cleanup-vexxhost

**Comment by pierreprinetti** [comment]
/pj-rehearse periodic-ci-shiftstack-prune-main-cleanup-vexxhost

**Comment by pierreprinetti** [comment]
I do not understand this error. Why does it want an openstack-installer image?
>could not run steps: step cleanup-vexxhost failed: "cleanup-vexxhost" pre steps failed: "cleanup-vexxhost" pod "cleanup-vexxhost-openstack-conf-clouds" failed: pod pending for more than 30m0s: containers have not started in 30m0.000234104s: test: 
>Container test is not ready with reason ImagePullBackOff and message Back-off pulling image "image-registry.openshift-image-registry.svc:5000/ci-op-t4d9z1nc/stable:openstack-installer" 

/pj-rehearse periodic-ci-shiftstack-prune-main-cleanup-vexxhost

**Comment by pierreprinetti** [comment]
/pj-rehearse periodic-ci-shiftstack-prune-main-cleanup-vexxhost

**Comment by pierreprinetti** [comment]
/pj-rehearse periodic-ci-shiftstack-prune-main-cleanup-vexxhost

**Comment by pierreprinetti** [comment]
/pj-rehearse periodic-ci-shiftstack-prune-main-cleanup-vexxhost

**Comment by pierreprinetti** [comment]
/pj-rehearse periodic-ci-shiftstack-prune-main-cleanup-vexxhost

**Comment by mandre** [comment]
I assume that `prune` knows to ignore the resources we manually created in the CI environments and that should not be removed, right?

**Comment by pierreprinetti** [comment]
> I assume that `prune` knows to ignore the resources we manually created in the CI environments and that should not be removed, right?

You should not assume.
* [servers](https://github.com/shiftstack/prune/blob/b6b0778e0c2baadb328cf954539f6c4aaea9717b/main.go#L125): `NameIsNot("metrics")`
* [routers](https://github.com/shiftstack/prune/blob/b6b0778e0c2baadb328cf954539f6c4aaea9717b/main.go#L129): `NameIsNot("dualstack")`
* [networks](https://github.com/shiftstack/prune/blob/b6b0778e0c2baadb328cf954539f6c4aaea9717b/main.go#L141): `NameDoesNotContain("hostonly", "external", "sahara-access", "mellanox", "intel", "public")`
* [security groups](https://github.com/shiftstack/prune/blob/b6b0778e0c2baadb328cf954539f6c4aaea9717b/main.go#L153): `NameIsNot("default", "ssh", "allow_ssh", "allow_ping")`
* [containers](https://github.com/shiftstack/prune/blob/b6b0778e0c2baadb328cf954539f6c4aaea9717b/main.go#L168): `NameIsNot("shiftstack-metrics", "shiftstack-bot")`
* [images](https://github.com/shiftstack/prune/blob/b6b0778e0c2baadb328cf954539f6c4aaea9717b/main.go#L173C53-L173C197): `NameMatchesOneOfThesePatterns(".{8}-.{5}-.{5}-ignition", ".{8}-.{5}-.{5}-rhcos", "bootstrap-ign-.{8}-.{5}-.{5}", "rhcos-.{7,8}-.{5}")`

These are the filters I have extracted from both the [cleanup script](https://github.com/shiftstack/shiftstack-ci/blob/main/clean-ci-resources.sh) and from the [stale resource lister](https://github.com/shiftstack/shiftstack-ci/blob/main/stale.sh). If I missed any, then please report that!

**Comment by mandre** [comment]
> > I assume that `prune` knows to ignore the resources we manually created in the CI environments and that should not be removed, right?
> 
> You should not assume.

I assumed, because I know you, but was still checking :)

**Comment by pierreprinetti** [comment]
/pj-rehearse periodic-ci-shiftstack-prune-main-cleanup-vexxhost

**Comment by pierreprinetti** [comment]
/pj-rehearse periodic-ci-shiftstack-prune-main-cleanup-vexxhost

**Comment by pierreprinetti** [comment]
/pj-rehearse periodic-ci-shiftstack-prune-main-cleanup-vh-mecha-central

**Comment by pierreprinetti** [comment]
/pj-rehearse ack
@mandre PTAL

**Comment by pierreprinetti** [comment]
/pj-rehearse periodic-ci-shiftstack-prune-main-cleanup-openstack-hwoffload

**Comment by mandre** [comment]
We need to resolve the conflict on `ci-operator/jobs/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main-periodics.yaml`, then let's go!

**Comment by pierreprinetti** [comment]
/pj-rehearse periodic-ci-shiftstack-prune-main-cleanup-vh-mecha-central

**Comment by pierreprinetti** [comment]
/pj-rehearse periodic-ci-shiftstack-prune-main-cleanup-vh-mecha-central

**Review by mandre — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
