### PR TITLE
Move some operator to use 4.12 Compact Cluster

### PR DESCRIPTION
**Pull request by Sandeepyadav93**
Moving some cluster to use 4.12 Compact cluster
from SNO 4.10

On a 3 node OCP cluster we discovered that the `make ceph`
toy can only be accessed from pods running on the same node,
if glance/cinder lands on different worker they can't communicate with ceph.

Also, updating glance/cinder/manila to spawn pod on same node as ceph
node.

Once PR[1] lands we can move nodeSelector under template.

[1] https://github.com/openstack-k8s-operators/glance-operator/pull/272

### CODE REVIEW

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-octavia-operator-main-octavia-operator-build-deploy-kuttl

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-ansibleee-operator-main-ansibleee-operator-build-deploy-kuttl

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-ansibleee-operator-main-ansibleee-operator-build-deploy-kuttl

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-ovn-operator-main-ovn-operator-build-deploy-kuttl

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-ovn-operator-main-ovn-operator-build-deploy-kuttl

**Comment by Sandeepyadav93** [comment]
/hold

Some legit failures

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-placement-operator-main-placement-operator-build-deploy

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-placement-operator-main-placement-operator-build-deploy

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-placement-operator-main-placement-operator-build-deploy

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-placement-operator-main-placement-operator-build-deploy

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-ansibleee-operator-main-ansibleee-operator-build-deploy-kuttl

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-ansibleee-operator-main-ansibleee-operator-build-deploy-kuttl

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-manila-operator-build-deploy

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-baremetal-operator-main-openstack-baremetal-operator-build-deploy

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-manila-operator-main-manila-operator-build-deploy

**Comment by viroel** [comment]
Depends-on https://github.com/openstack-k8s-operators/ovn-operator/pull/87 to have ovn job passing

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-mariadb-operator-main-mariadb-operator-build-deploy-kuttl

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-mariadb-operator-main-mariadb-operator-build-deploy-kuttl

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-swift-operator-main-swift-operator-build-deploy

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-cinder-operator-main-cinder-operator-build-deploy-kuttl

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-manila-operator-build-deploy

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-manila-operator-main-manila-operator-build-deploy-tempest

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-manila-operator-main-manila-operator-build-deploy-tempest

**Comment by viroel** [comment]
Lets try manila again. Failures doesn't seems related to this change.
Cinder, Manila and Glance nodeSelector are working[1][2][3][4]

[1] https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/41107/rehearse-41107-pull-ci-openstack-k8s-operators-manila-operator-main-manila-operator-build-deploy-tempest/1680421192474824704/artifacts/manila-operator-build-deploy-tempest/openstack-k8s-operators-gather/artifacts/pods/cinder-volume-volume1-0-describe.log
[2] https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/41107/rehearse-41107-pull-ci-openstack-k8s-operators-manila-operator-main-manila-operator-build-deploy-tempest/1680421192474824704/artifacts/manila-operator-build-deploy-tempest/openstack-k8s-operators-gather/artifacts/pods/manila-share-share1-0-describe.log
[3] https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/41107/rehearse-41107-pull-ci-openstack-k8s-operators-manila-operator-main-manila-operator-build-deploy-tempest/1680421192474824704/artifacts/manila-operator-build-deploy-tempest/openstack-k8s-operators-gather/artifacts/pods/glance-internal-api-6cc97bd57d-gt8wr-describe.log
[4] https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/41107/rehearse-41107-pull-ci-openstack-k8s-operators-manila-operator-main-manila-operator-build-deploy-tempest/1680421192474824704/artifacts/manila-operator-build-deploy-tempest/openstack-k8s-operators-gather/artifacts/pods/glance-external-api-5c78d889b4-jmztx-describe.log

**Comment by Sandeepyadav93** [comment]
Abandoning in favor of https://github.com/openshift/release/pull/41385

**Pull request closed without merging**
