### PR TITLE
telco5g: nto: features to run tests on in BM job

### PR DESCRIPTION
**Pull request by danimjaffe**
As a follow-up step to #48773 ,
we now select only the relevant features to run tests on when the BM job is triggered in the cluster-node-tuning-operator repository.

### CODE REVIEW

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-cluster-node-tuning-operator-master-e2e-telco5g-cnftests pull-ci-openshift-cluster-node-tuning-operator-release-4.15-e2e-telco5g-cnftests

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-cluster-node-tuning-operator-master-e2e-telco5g-cnftests

**Comment by yanirq** [comment]
/lgtm
We will have to establish a base line and sort out the errors

**Pull request merged**
