### PR TITLE
[azure] set single node instance type on arm64

### PR DESCRIPTION
**Pull request by jinyunma**
Fixed issue introduced in https://github.com/openshift/release/pull/39185

### CODE REVIEW

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.14-installer-rehearse-azure

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-azure-ipi-sno-p2-f28

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-azure-ipi-sno-p2-f28

**Comment by jinyunma** [comment]
cc @jianlinliu @gpei to review

**Comment by jinyunma** [comment]
@eranco74 could you help to review this PR? thanks.

**Comment by jianlinliu** [comment]
cc @liangxia to review.

**Pull request merged**
