### PR TITLE
OCPBUGS-29471: CI for e2e on metal

### PR DESCRIPTION
**Pull request by candita**
Add configuration to exercise e2e tests on a bare metal cluster.

See https://github.com/openshift/images/pull/161

### CODE REVIEW

**Comment by candita** [comment]
Did it timeout or run out of memory?

> ...
> dev-scripts setup completed, fetching logs
> ...
> {"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:264","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process gracefully exited before 10m0s grace period","severity":"error","time":"2024-03-05T22:25:14Z"}
> {"component":"entrypoint","error":"process timed out","file":"k8s.io/test-infra/prow/entrypoint/run.go:84","func":"k8s.io/test-infra/prow/entrypoint.Options.internalRun","level":"error","msg":"Error executing test 
process","severity":"error","time":"2024-03-05T22:25:14Z"}
> error: failed to execute wrapped command: exit status 127 


/pj-rehearse pull-ci-openshift-images-master-e2e-metal-ipi-ovn

**Comment by candita** [comment]
/pj-rehearse pull-ci-openshift-images-master-e2e-metal-ipi-ovn

**Comment by candita** [comment]
/pj-rehearse pull-ci-openshift-images-master-e2e-metal-ipi-ovn

**Comment by candita** [comment]
A couple of these in the log:
>   E0306 02:48:37.812913       1 limiter.go:165] error reloading router: exit status 126
>   /var/lib/haproxy/reload-haproxy: line 81: /usr/sbin/haproxy: Operation not permitted
>

**Comment by candita** [comment]
I'll try a retest while investigating MonitorTests.  At least one team ignores them: https://github.com/openshift/release/pull/45663

>  I0307 00:43:56.713344     951 monitortest.go:182] Deleting route: test-disruption-6jv4l took 0.04 seconds
> found errors fetching in-cluster data: [failed to list files in disruption event folder on node master-0.ostest.test.metalkube.org: the server could not find the requested resource failed to list files in disruption event folder on node master-1.ostest.test.metalkube.org: the server could not find the requested resource failed to list files in disruption event folder on node master-2.ostest.test.metalkube.org: the server could not find the requested resource failed to list files in disruption event folder on node worker-0.ostest.test.metalkube.org: the server could not find the requested resource failed to list files in disruption event folder on node worker-1.ostest.test.metalkube.org: the server could not find the requested resource failed to list files in disruption event folder on node worker-2.ostest.test.metalkube.org: the server could not find the requested resource]
> ...
> Suite run returned error: failed due to a MonitorTest failure
> No manifest filename passed
> error running options: failed due to a MonitorTest failureerror: failed due to a MonitorTest failure

/pj-rehearse pull-ci-openshift-images-master-e2e-metal-ipi-ovn-ipv6

**Comment by candita** [comment]
Reported in core network forum.

> /root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/cache/cache.go:25:2: missing go.sum entry for module providing package golang.org/x/exp/maps (imported by sigs.k8s.io/controller-runtime/pkg/cache); to add:
> 	go get sigs.k8s.io/controller-runtime/pkg/cache@v0.16.3
> acl_logging.go:18:2: missing go.sum entry for module providing package k8s.io/kubernetes/test/e2e/framework (imported by github.com/ovn-org/ovn-kubernetes/test/e2e); to add:
> 	go get github.com/ovn-org/ovn-kubernetes/test/e2e
> util.go:28:2: missing go.sum entry for module providing package k8s.io/kubernetes/test/e2e/framework/debug (imported by github.com/ovn-org/ovn-kubernetes/test/e2e); to add:
> 	go get github.com/ovn-org/ovn-kubernetes/test/e2e
> e2e.go:33:2: missing go.sum entry for module providing package k8s.io/kubernetes/test/e2e/framework/deployment (imported by github.com/ovn-org/ovn-kubernetes/test/e2e); to add:
> 	go get github.com/ovn-org/ovn-kubernetes/test/e2e
> acl_logging.go:12:2: missing go.sum entry for module providing package k8s.io/kubernetes/test/e2e/framework/kubectl (imported by github.com/ovn-org/ovn-kubernetes/test/e2e); to add:
> 	go get github.com/ovn-org/ovn-kubernetes/test/e2e
> e2e.go:35:2: missing go.sum entry for module providing package k8s.io/kubernetes/test/e2e/framework/node (imported by github.com/ovn-org/ovn-kubernetes/test/e2e); to add:
> 	go get github.com/ovn-org/ovn-kubernetes/test/e2e
> acl_logging.go:13:2: missing go.sum entry for module providing package k8s.io/kubernetes/test/e2e/framework/pod (imported by github.com/ovn-org/ovn-kubernetes/test/e2e); to add:
> 	go get github.com/ovn-org/ovn-kubernetes/test/e2e
> egress_services.go:21:2: missing go.sum entry for module providing package k8s.io/kubernetes/test/e2e/framework/pod/output (imported by github.com/ovn-org/ovn-kubernetes/test/e2e); to add:
> 	go get github.com/ovn-org/ovn-kubernetes/test/e2e
> service.go:32:2: missing go.sum entry for module providing package k8s.io/kubernetes/test/e2e/framework/rc (imported by github.com/ovn-org/ovn-kubernetes/test/e2e); to add:
> 	go get github.com/ovn-org/ovn-kubernetes/test/e2e
> node_ip_mac_migration.go:11:2: missing go.sum entry for module providing package k8s.io/kubernetes/test/e2e/framework/service (imported by github.com/ovn-org/ovn-kubernetes/test/e2e); to add:
> 	go get github.com/ovn-org/ovn-kubernetes/test/e2e
> e2e.go:37:2: missing go.sum entry for module providing package k8s.io/kubernetes/test/e2e/framework/skipper (imported by github.com/ovn-org/ovn-kubernetes/test/e2e); to add:
> 	go get github.com/ovn-org/ovn-kubernetes/test/e2e
> e2e.go:38:2: missing go.sum entry for module providing package k8s.io/kubernetes/test/utils (imported by github.com/ovn-org/ovn-kubernetes/test/e2e); to add:
> 	go get github.com/ovn-org/ovn-kubernetes/test/e2

**Comment by candita** [comment]
/pj-rehearse pull-ci-openshift-images-master-e2e-metal-ipi-ovn-ipv4

**Comment by candita** [comment]
Cluster initialization failed for ipv6 test. kube-apiserver had problems that caused other operators to fail.  kube-apiserver log shows alot of these: 

> W0307 20:28:16.021243       1 cmd.go:467] Error getting installer pods on current node master-0.ostest.test.metalkube.org: Get "https://[fd02::1]:443/api/v1/namespaces/openshift-kube-apiserver/pods?labelSelector=app%3Dinstaller": dial tcp [fd02::1]:443: connect: connection refused

/pj-rehearse pull-ci-openshift-images-master-e2e-metal-ipi-ovn-ipv6

**Comment by candita** [comment]
/pj-rehearse pull-ci-openshift-images-master-e2e-metal-ipi-ovn-ipv4

**Comment by candita** [comment]
https://github.com/openshift/release/pull/48537 fixes the issue mentioned in https://github.com/openshift/release/pull/49518#issuecomment-1984555088

**Comment by candita** [comment]
Issue with e2e-metail-ipi-ovn-ipv4:

> Trying to pull quay.io/libpod/registry:2.8...
> Error: initializing source docker://quay.io/libpod/registry:2.8: can't talk to a V1 container registry

**Comment by candita** [comment]
Build failure for e2e-metal-ipi-ovn-ipv6  

> Errors during downloading metadata for repository 'rhel-9-nfv-ppc64le':
>   - Status code: 404 for http://base-4-16-rhel9.ocp.svc/rhel-9-nfv-ppc64le/repodata/repomd.xml (IP: 172.30.12.254)
> Error: Failed to download metadata for repo 'rhel-9-nfv-ppc64le': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
>

**Comment by candita** [comment]
e2e-aws jobs were aborted, and e2e-metal job had several storage errors resembling:

> [0;31m        "error: failed to get pool 'oooq_pool'",[0m
> [0;31m        "error: Storage pool not found: no storage pool with matching name 'oooq_pool'"[0m
> 

/pj-rehearse pull-ci-openshift-images-master-e2e-metal-ipi-ovn-ipv4

**Comment by candita** [comment]
/pj-rehearse pull-ci-openshift-images-master-e2e-metal-ipi-ovn-ipv6

**Comment by candita** [comment]
disruption failures, and also the error below in e2e-aws and e2e-metal-ipi-ovn-ipv6.  However, this does not preclude a rehearsal ack.

/pj-rehearse ack 

>    [FAILED] error getting crio container data from node worker-1.ostest.test.metalkube.org
>     Unexpected error:
>         <*errors.StatusError | 0xc000815220>: 
>         Internal error occurred: admission plugin "security.openshift.io/SCCExecRestrictions" failed to complete validation in 13s
>         {
>             ErrStatus: 
>                 code: 500
>                 details:
>                   causes:
>                   - message: admission plugin "security.openshift.io/SCCExecRestrictions" failed to
>                       complete validation in 13s
>                 message: 'Internal error occurred: admission plugin "security.openshift.io/SCCExecRestrictions"
>                   failed to complete validation in 13s'
>                 metadata: {}
>                 reason: InternalError
>                 status: Failure,
>         }
>     occurred
>     In [It] at: github.com/openshift/origin/test/extended/cpu_partitioning/crio.go:143 @ 03/14/24 19:49:23.642

**Comment by candita** [comment]
/pj-rehearse

> error: failed to push image registry.build05.ci.openshift.org/ci-op-0nfn8c57/release:latest: unable to upload new layer (0): Patch "https://registry.build05.ci.openshift.org/v2/ci-op-0nfn8c57/release/blobs/uploads/5d9e78c5-b117-4949-b862-9cac6e5dbf8d?_state=...: unknown version reference "machine-os"

**Comment by candita** [comment]
Again the same failure on e2e-metal-ipi-ovn-ipv6:

> error: failed to push image registry.build05.ci.openshift.org/ci-op-0y0chmyv/release:latest: unable to upload new layer (0): Patch "https://registry.build05.ci.openshift.org/v2/ci-op-0y0chmyv/release/blobs/uploads/fb9c7de6-1037-48ad-8ca0-8a958cbee424?_state=...": unknown version reference "machine-os"

**Comment by candita** [comment]
Some node segfaults like:

>  nodes/ip-10-0-111-139.us-east-2.compute.internal/journal-previous.gz:Mar 19 16:01:42.942974 ip-10-0-111-139 kernel: NetworkManager[1082]: segfault at 1 ip 00005633116ff719 sp 00007ffd286dc7f0 error 4 in NetworkManager[563311602000+273000] likely on CPU 2 (core 0, socket 0)

/pj-rehearse

**Comment by candita** [comment]
/pj-rehearse abort
>   Timed out waiting for node count (5) to equal or exceed machine count (6).

**Comment by candita** [comment]
@bparees @jupierce can I get an approval on this please?

**Comment by bparees** [comment]
@jupierce looks like we need some more approvers for https://github.com/openshift/release/blob/master/ci-operator/config/openshift/images/OWNERS and https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/images/OWNERS

**Comment by candita** [comment]
> @jupierce looks like we need some more approvers for https://github.com/openshift/release/blob/master/ci-operator/config/openshift/images/OWNERS and https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/images/OWNERS

Hi @bparees @jupierce can you help with this one or are you no longer working on it?  Should I add someone from our team to the images/OWNERS?

**Comment by bparees** [comment]
> Hi @bparees @jupierce can you help with this one or are you no longer working on it? Should I add someone from our team to the images/OWNERS?

Justin still works on it, but i do not

**Pull request merged**
