### PR TITLE
Indicate MCO tests are longduration test

### PR DESCRIPTION
**Pull request by liangxia**
The MCO tests are running long duration tests, add keyword longduration to indicate that.

### CODE REVIEW

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-f9-longduration-mco-critical

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-gcp-ipi-f9-longduration-mco-critical

**Comment by rioliu-rh** [comment]
LGTM

**Pull request merged**
