### PR TITLE
Run FIPS scan using check_payload for Distributed Tracing operators

### PR DESCRIPTION
**Pull request by IshwarKanse**
The PR adds OCP CI step distributed-tracing-tests-fips-scan to scan the Distributed Tracing Tempo, OpenTelemetry operators and related images for FIPS using [check_paylod](https://github.com/openshift/check-payload) tool and adds OCP CI jobs to run the step and tests on FIPS enabled clusters.

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.16-stage-opentelemetry-stage-tests-fips periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.16-stage-tempo-stage-tests-fips

**Comment by IshwarKanse** [comment]
Currently these jobs will fail as we do not have the RHOSDT 3.3 build in the stage registry which has FIPS support.

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.16-stage-opentelemetry-stage-tests-fips periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.16-stage-tempo-stage-tests-fips

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.16-stage-opentelemetry-stage-tests-fips-scan periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.16-stage-tempo-stage-tests-fips-scan

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.16-stage-opentelemetry-stage-tests-fips-scan periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.16-stage-tempo-stage-tests-fips-scan

**Review by vprashar2929 — APPROVED** [review]
/lgtm

**Pull request merged**
