### PR TITLE
Request token for Codeready Workspaces QE

### PR DESCRIPTION
**Pull request by rhopp**
This PR was created according to instructions in https://docs.ci.openshift.org/docs/how-tos/use-registries-in-build-farm/#how-do-i-get-a-token-for-programmatic-access-to-the-central-ci-registry

Signed-off-by: Radim Hopp <rhopp@redhat.com>

### CODE REVIEW

**Comment by rhopp** [comment]
Pinging @hongkailiu for approval. Thanks

**Review by hongkailiu — APPROVED** [review]

**Pull request merged**
