### PR TITLE
Add a CI lane that builds and deploys sriov-network-operator

### PR DESCRIPTION
**Pull request by oribon**

### CODE REVIEW

**Comment by oribon** [comment]
@zshi-redhat @fedepaol 
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/19267/rehearse-19267-pull-ci-openshift-sriov-network-operator-master-operator-e2e/1405473543642157056/artifacts/operator-e2e/e2e/build-log.txt
looks like it works, can we merge?

**Comment by fedepaol** [comment]
This is awesome!
/lgtm
@zshi-redhat I think this needs your approval

**Pull request merged**
