### PR TITLE
Add ci-operator config and job for cri-o 1.14

### PR DESCRIPTION
**Pull request by umohnani8**
Add yaml files to config and jobs for cri-o release-1.14
branch so that we run e2e-aws tests on cri-o PRs.

Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
@petr-muller the e2e-aws and launch-aws tests are failing to start up a cluster. This has been happening since yesterday. Am I messing something up or is this just test flakes?
The config and job match what we have for cri-o 1.13 in https://github.com/openshift/release/pull/3962 and those tests are passing.

**Comment by petr-muller** [comment]
/test pj-rehearse

@umohnani8 I don't know. The rehearsals execute the added/changed jobs as if they were run against the target branch HEAD, so in the case of e2e tests their results depend on how healthy openshift currently is. It's certainly known to flake a bit (current build cop usually knows if there's currently something going on). The rehearsals do not block the merge, so if it looks like the jobs work fine and the tests inside flake them, you can merge them.

**Comment by umohnani8** [comment]
@petr-muller got it, thanks! Trying to debug the problem here, seems something is off with the cri-o being built for the ci.

**Comment by cgwalters** [comment]
Look at [the log bundle(https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_release/4030/rehearse-4030-pull-ci-cri-o-cri-o-release-1.14-e2e-aws/6/artifacts/e2e-aws/installer/) and drill down into one of the master's journals:

```
Jun 19 13:13:46 ip-10-0-129-84 hyperkube[944]: F0619 13:13:46.174808     944 server.go:264] failed to run Kubelet: failed to create kubelet: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial unix /var/run/crio/crio.sock: connect: no such file or directory"
```

And that's because:

```
-- Logs begin at Wed 2019-06-19 13:09:22 UTC, end at Wed 2019-06-19 13:41:43 UTC. --
Jun 19 13:13:43 ip-10-0-129-84 systemd[1]: Starting Open Container Initiative Daemon...
Jun 19 13:13:44 ip-10-0-129-84 crio[928]: time="2019-06-19 13:13:44.541376996Z" level=fatal msg="config validation: invalid plugin_dirs entry: stat /var/lib/cni/bin: no such file or directory"
Jun 19 13:13:44 ip-10-0-129-84 systemd[1]: crio.service: Main process exited, code=exited, status=1/FAILURE
Jun 19 13:13:44 ip-10-0-129-84 systemd[1]: crio.service: Failed with result 'exit-code'.
```

**Comment by mrunalp** [comment]
@smarterclayton @stevekuznetsov ptal. This is ready.

**Pull request merged**
