### PR TITLE
STOR-1823: Remove shared-resource CSI driver and operator

### PR DESCRIPTION
**Pull request by dobsonj**
https://issues.redhat.com/browse/STOR-1823

/hold for https://github.com/openshift/cluster-storage-operator/pull/509

/cc @openshift/storage

### CODE REVIEW

**Comment by adambkaplan** [comment]
Do we need to remove the tests to remove the CSI driver from the payload? We didn't do this with Jenkins way back when...

**Comment by dobsonj** [comment]
> Do we need to remove the tests to remove the CSI driver from the payload? We didn't do this with Jenkins way back when...

I updated it, we can just remove the promotion stanza for the driver and leave the presubmit jobs in place for the repo.

**Comment by dobsonj** [comment]
/pj-rehearse ack
the security job (snyk) has always been red

**Pull request merged**
