### PR TITLE
fix openshift-managed-upgrade-operator ns doesn't exist for HCP cluster

### PR DESCRIPTION
**Pull request by aaraj7**
[OCM-7956](https://issues.redhat.com//browse/OCM-7956) The command "oc get pod -n openshift-managed-upgrade-operator | grep 'managed-upgrade-operator' | grep -v 'catalog' | cut -d ' ' -f1" is not supported for hcp cluster.

### CODE REVIEW

**Comment by aaraj7** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-master-rosacli-aws-rosa-upgrade-e2e-f7 periodic-ci-openshift-openshift-tests-private-master-rosacli-aws-rosa-shared-vpc-upgrade-e2e-f7 periodic-ci-openshift-openshift-tests-private-master-rosacli-aws-rosa-hcp-upgrade-e2e-f7

**Comment by aaraj7** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-master-rosacli-aws-rosa-shared-vpc-upgrade-e2e-f7 periodic-ci-openshift-openshift-tests-private-master-rosacli-aws-rosa-hcp-upgrade-e2e-f7

**Comment by aaraj7** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-master-rosacli-aws-rosa-shared-vpc-upgrade-e2e-f7

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-master-rosacli-aws-rosa-shared-vpc-upgrade-e2e-f7

**Comment by yasun1** [comment]
The failure is related to the cluster itself but not this change. 
/pj-rehearse ack

**Pull request merged**
