### PR TITLE
OCPQE-13371: add brew and redhat auths

### PR DESCRIPTION
**Pull request by jianzhangbjz**
Config `brew.registry.redhat.io` and `registry.redhat.io` registries auth instead of the `${CLUSTER_PROFILE_DIR}/pull-secret`.

### CODE REVIEW

**Comment by jianzhangbjz** [comment]
Hold until @Xia-Zhao-rh 's checking
/hold

**Comment by Xia-Zhao-rh** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-c2s-ipi-disconnected-private-p2-f7

**Comment by Xia-Zhao-rh** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-sc2s-ipi-disconnected-private-p3-f28-destructive

**Pull request merged**
