### PR TITLE
promote QE tests-private image to ocp

### PR DESCRIPTION
**Pull request by jianzhangbjz**
Promote a new image `tests-private` for QE testing.

### CODE REVIEW

**Comment by jianzhangbjz** [comment]
@smarterclayton Hi, we want to promote a new image called `tests-private` for `OCP` so that other components can leverage it. Could you help give approval? Thanks!

**Comment by smarterclayton** [comment]
Can you describe in more detail what is in `tests-private`?  The use of `private` is new for us, so I might ask for a different name to clarify.

Who will be allowed to see these tests?  Will we ever ship them to customers?  Can they be publicly exposed to the internet?  What impact would there be if they were accidentally exposed?  Can they contain information that should be embargoed (like tests that verify embargoed CVEs, before a CVE is released)?

**Comment by jianzhangbjz** [comment]
> Can you describe in more detail what is in tests-private? The use of private is new for us, so I might ask for a different name to clarify.

This `test-private` image contains three binaries mainly:

1. the `extended-platform-tests` binary which compiled from the https://github.com/openshift/openshift-tests-private. It contains the OpenShift QE test cases.
2. the `opm` binary for QE testing
3. the `operator-sdk` binary for QE testing

Details: https://github.com/openshift/openshift-tests-private/blob/master/images/Dockerfile

> Who will be allowed to see these tests?

I think all OpenShift org members are allowed to see them.

> Will we ever ship them to customers? 

No.

> Can they be publicly exposed to the internet?

I guess no. Because they contain some unreleased binaries.

> What impact would there be if they were accidentally exposed?

The unreleased `opm` and `operator-sdk` binaries are leaked.

> Can they contain information that should be embargoed (like tests that verify embargoed CVEs, before a CVE is released)?

No for now. But they can.

**Comment by jianzhangbjz** [comment]
Close it since an image that was built from a private repo would generally not publish it to the quay.

**Pull request closed without merging**
