### PR TITLE
cincinnati: run rustfmt tests for Rust 1.46 only

### PR DESCRIPTION
**Pull request by steveej**
* [x] Depends on https://github.com/openshift/cincinnati/pull/300

See #11170 and #11437.

### CODE REVIEW

**Comment by steveeJ** [comment]
/hold 

Still waiting for CI to merge the dependency.

**Comment by steveeJ** [comment]
I can't reproduce the rustfmt failures for rust 1.44 and 1.45. Let's make sure this is reproducible on CI.

/retest

**Comment by steveeJ** [comment]
I was able to verify the rustfmt failures locally now. This is an interesting situation as the formatting is off on auto-generated code, which seems to be a corner case for me with regards to strictness of tests. Additionally I verified that rustfmt 1.46.0 does not reformat the code in question, so I suggest leaving it as is and overriding these tests for now, and bump to rust 1.46.0 immediately after this.

/override ci/rehearse/openshift/cincinnati/master/rustfmt-1.44.0
/override ci/rehearse/openshift/cincinnati/master/rustfmt-1.45.0

**Review by vrutkovs — APPROVED** [review]
/lgtm

**Pull request merged**
