### PR TITLE
cluster-etcd-operator: use multistep job for e2e-upgrade

### PR DESCRIPTION
**Pull request by vrutkovs**
Run GCP upgrade using multistep and persist container logs using Loki

### CODE REVIEW

**Comment by hexfusion** [comment]
thanks @vrutkovs 
/lgtm

**Comment by wking** [comment]
/hold

need to get 4.6+ too?

**Comment by vrutkovs** [comment]
4.6 is using AWS, which requires https://github.com/openshift/release/pull/11629.
Do we want to make it uniform and move all to GCP?

**Comment by vrutkovs** [comment]
/hold cancel

Updated 4.6 jobs to use platform-agnostic upgrade tests

**Comment by hexfusion** [comment]
failure with 4.7 rehearse feels nonblocking, will monitor in the future.

/lgtm

**Pull request merged**
