### PR TITLE
Add ref: sdn-conf for aws-ipi-sdn2ovn

### PR DESCRIPTION
**Pull request by weliang1**
The default network plugin is OVN not SDN in v4.12. Update workflow to install SDN and then execute sdn2ovn migration test.

@zhaozhanqi @anuragthehatter @lihongan PTAL!

### CODE REVIEW

**Comment by jianlinliu** [comment]
looks good to me. To avoid conflicts with another WIP big PR - https://github.com/openshift/release/pull/31256 (pending on dev's review), can you help remove the change in `ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.12.yaml`, after that, we can safely merge this PR.

**Comment by weliang1** [comment]
> Update rehearse-4.12 YAML file

@jianlinliu Change it back now.

**Pull request merged**
