### PR TITLE
OCPBUGS-30238 Moving the fips-check step into the workflow for multiarch jobs

### PR DESCRIPTION
**Pull request by tvardema**

### CODE REVIEW

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-fips-ovn-remote-libvirt-ppc64le

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-fips-ovn-remote-libvirt-ppc64le

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-fips-ovn-remote-libvirt-ppc64le

**Comment by tvardema** [comment]
Waiting for https://github.com/openshift/ci-tools/pull/4015 to merge.

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-fips-ovn-remote-libvirt-ppc64le

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-fips-ovn-remote-libvirt-ppc64le

**Comment by danilo-gemoli** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-fips-ovn-remote-libvirt-ppc64le

**Pull request merged**
