### PR TITLE
openstack/sriov: use images from quay-proxy.ci.openshift.org

### PR DESCRIPTION
**Pull request by EmilienM**
- **Revert "openstack/SRIOV: don't install from source anymore (#53294)"**
- **openstack/sriov: use images from quay-proxy.ci.openshift.org**

### CODE REVIEW

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.17-e2e-openstack-nfv-intel

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.17-e2e-openstack-nfv-intel

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.17-e2e-openstack-nfv-intel

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.17-e2e-openstack-nfv-intel

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.17-e2e-openstack-nfv-intel

**Comment by EmilienM** [comment]
@MaysaMacedo @mandre for review please
cc @MiguelCarpio FYI

**Comment by MaysaMacedo** [comment]
/lgtm

Great work!

**Pull request merged**
