### PR TITLE
OCPQE-13107: use the correct auth for image mirroring for C2S/SC2S clusters

### PR DESCRIPTION
**Pull request by jianzhangbjz**
As the title, fix a mirror auth issue.

### CODE REVIEW

**Comment by jianzhangbjz** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-c2s-ipi-disconnected-private-p2-f7

**Review by bandrade — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
