### PR TITLE
add osde2e testing job for upgrade reschedule

### PR DESCRIPTION
**Pull request by bmeng**
add the test job for upgrade rescheduled scenarios based on the existing e2e testing in osde2e.

### CODE REVIEW

**Comment by bmeng** [comment]
@jeefy Could you help take a look?

And I have a question, I see some of the tests did not cover all the platforms and environments. I just picked random of them. Do we have the guideline about which platform and environment should be covered?

**Comment by jeefy** [comment]
There aren't any set guidelines, but this coverage would probably suffice short-term.

Do we need to run this every 8 hours? Or does it make sense to change this to a daily test?

**Comment by bmeng** [comment]
Yes, that should be fine to run once everyday. Changed the cron schedule for that.

**Comment by bmeng** [comment]
@jeefy the test cannot pass if I use the cluster api.ci... I am not sure what is the difference between `api.ci` and `build01`. But looks like the test accepts the build01 only....

**Pull request merged**
