### PR TITLE
Adding 'e2e-aws-ocp' job to special-resource-operator.

### PR DESCRIPTION
**Pull request by ybettan**
Signed-off-by: Yoni Bettan <ybettan@redhat.com>

### CODE REVIEW

**Comment by ybettan** [comment]
/cc @pacevedom 
/cc @quarterpin 

We are ready to merge 💯

**Comment by ybettan** [comment]
/hold
Just want to try to remove some ENVs that may be redundant.

**Review by pacevedom — APPROVED** [review]

**Pull request merged**
