### PR TITLE
add CI for hive ocm-2.0 branch

### PR DESCRIPTION
**Pull request by gregsheremeta**
/cc @dgoodwin @staebler

### CODE REVIEW

**Comment by gregsheremeta** [comment]
it's a copy/paste of ocm-1.0. Let me know if there's a cleaner way to do this.

**Comment by gregsheremeta** [comment]
/hold

wait for the branch to exist

**Comment by staebler** [comment]
The ocm-2.0 branch exists now.

/hold cancel

/test pj-rehearse

**Comment by gregsheremeta** [comment]
@staebler looks like the tests are failing because it doesn't see the branch. Any ideas?

**Comment by staebler** [comment]
Need to run `make ci-operator-config`.

/lgtm cancel

**Pull request merged**
