### PR TITLE
[ISV-3498] Create an end-to-end test for the community operator pipeline - prow configuration for testing branch

### PR DESCRIPTION
**Pull request by ezopezo**
Openshift prow configuration for e2e community operator testing.

### CODE REVIEW

**Comment by ezopezo** [comment]
/pj-rehearse pull-ci-redhat-openshift-ecosystem-community-operators-pipeline-preprod-integration-tests-community-operators-4.13-deploy-and-test-operator

**Comment by ezopezo** [comment]
/pj-rehearse pull-ci-redhat-openshift-ecosystem-community-operators-pipeline-preprod-integration-tests-community-operators-4.13-deploy-and-test-operator

**Comment by ezopezo** [comment]
/pj-rehearse pull-ci-redhat-openshift-ecosystem-community-operators-pipeline-preprod-integration-tests-community-operators-4.13-deploy-and-test-operator

**Comment by danilo-gemoli** [comment]
/pj-rehearse pull-ci-redhat-openshift-ecosystem-community-operators-pipeline-preprod-integration-tests-community-operators-4.13-deploy-and-test-operator

**Comment by mrhillsman** [comment]
/pj-rehearse pull-ci-redhat-openshift-ecosystem-community-operators-pipeline-preprod-integration-tests-community-operators-4.13-deploy-and-test-operator

**Comment by danilo-gemoli** [comment]
/pj-rehearse pull-ci-redhat-openshift-ecosystem-community-operators-pipeline-preprod-integration-tests-community-operators-4.13-deploy-and-test-operator

**Comment by ezopezo** [comment]
This pull request is deprecated due to change of the underlying design in Community operator pipeline.

**Pull request closed without merging**
