### PR TITLE
Remove unsupported OCP versions for shifstack/periodics

### PR DESCRIPTION
**Pull request by MaysaMacedo**
The 4.11 is not supported[1] anymore. Let's remove the periodics that run on that version to free resources.

[1] https://access.redhat.com/support/policy/updates/openshift/

### CODE REVIEW

**Comment by pierreprinetti** [comment]
Have you considered using [our periodivs-bump script](https://github.com/shiftstack/shiftstack-ci/blob/main/bump-periodics.sh)?

**Comment by MaysaMacedo** [comment]
@pierreprinetti No as I wasn't aware about that script. Am I suppose to use it?
I just followed the same pattern done in the [last removal.](https://github.com/openshift/release/commit/22ef2b76836aece6a20367af7592ca4303f58cf3)

**Pull request merged**
