### PR TITLE
Add lease for openstack-nerc-dev cluster type

### PR DESCRIPTION
**Pull request by MaysaMacedo**
This commits adds the lease for the openstack-nerc-dev cloud and sets the openstack values that will be necessary for OCP cluster install.

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
/lgtm

**Review by mandre — COMMENTED** [review]
/approve

**Review by deepsm007 — APPROVED** [review]

**Comment by EmilienM** [comment]
We missed three files, I think:
* `ci-secret-bootstrap/_config.yaml`
* `clusters/app.ci/openshift-user-workload-monitoring/mixins/grafana_dashboards_out/boskos_grafanadashboard.yaml`
* `clusters/app.ci/openshift-user-workload-monitoring/mixins/_grafana_dashboards/boskos.jsonnet`

**Comment by EmilienM** [comment]
Also I'm confused why do we need that lease, how will it be used?

**Pull request merged**
