### PR TITLE
[alibabacloud] explicitly set EIP bandwidth as 200Mbps

### PR DESCRIPTION
**Pull request by jianli-wei**
Explicitly set EIP bandwidth to 200Mbps (see [OCPBUGS-10673](https://issues.redhat.com/browse/OCPBUGS-10673)).

### CODE REVIEW

**Comment by jianli-wei** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.13-installer-rehearse-alibabacloud

**Comment by jianlinliu** [comment]
cc @liangxia to approve.

**Pull request merged**
