### PR TITLE
chore(RHIDP-893): add RHDH catalog size scalability testing jobs

### PR DESCRIPTION
**Pull request by pmacik**

### CODE REVIEW

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-catalog-db-1g-scalability

**Review by yogananth-subramanian — APPROVED** [review]
/lgtm

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-catalog-db-1g-scalability pull-ci-redhat-performance-backstage-performance-main-catalog-db-2g-scalability

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-catalog-db-1g-scalability pull-ci-redhat-performance-backstage-performance-main-catalog-db-2g-scalability

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-catalog-db-1g-scalability

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-catalog-db-20g-scalability

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-catalog-db-20g-scalability

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-catalog-db-20g-scalability

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-catalog-db-20g-scalability

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-catalog-db-20g-scalability

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-catalog-db-20g-scalability

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-catalog-db-20g-scalability

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-catalog-db-20g-scalability

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp-catalog-api-size-scalability pull-ci-redhat-performance-backstage-performance-main-mvp-catalog-component-size-scalability

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp-catalog-api-size-scalability pull-ci-redhat-performance-backstage-performance-main-mvp-catalog-component-size-scalability

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp-catalog-api-size-scalability pull-ci-redhat-performance-backstage-performance-main-mvp-catalog-component-size-scalability

**Comment by pmacik** [comment]
/pr-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp-catalog-size-api-scalability pull-ci-redhat-performance-backstage-performance-main-mvp-catalog-size-component-scalability

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp-catalog-size-api-scalability pull-ci-redhat-performance-backstage-performance-main-mvp-catalog-size-api-scalability-20g pull-ci-redhat-performance-backstage-performance-main-mvp-catalog-size-component-scalability pull-ci-redhat-performance-backstage-performance-main-mvp-catalog-size-component-scalability-20g

**Review by yogananth-subramanian — APPROVED** [review]

**Pull request merged**
