### PR TITLE
ROX-24631: add an ocp nongroovy-e2e job

### PR DESCRIPTION
**Pull request by porridge**
See https://github.com/stackrox/stackrox/pull/11416

Making this opt-in on PRs is the first baby step. Depending on the level of success I will later make this run by default, and on merges, nightlies and releases.

/cc @gavin-stackrox @janisz

### CODE REVIEW

**Comment by gavin-stackrox** [comment]
/lgtm
though I think you will need to undo the `_config.yml` changes.

**Comment by porridge** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-4-15-nongroovy-e2e-tests

**Comment by porridge** [comment]
```
INFO: Mon Jun 10 07:49:34 UTC 2024: Waiting for stackrox deploy/central to appear
/go/src/github.com/stackrox/stackrox/tests/e2e/lib.sh: line 425: DEPLOY_DIR: unbound variable
****
**** 07:49:54: ERROR: test failed [Test failed: exit 1]
```
But this is somewhat expected, I'll iterate on this in the stackrox repo.

/pj-reharse skip

**Review by ebensh — APPROVED** [review]
Re-approving post-rebase

**Review by msugakov — COMMENTED** [review]
Even if it's opt-in, I don't see a reason not to add it to `release-x.y` (literally `x.y`) so that we don't introduce only-few-folks-can-explain-why fragmentation.

I mean to remind about this https://spaces.redhat.com/display/StackRox/Making+changes+to+OpenShift+CI#MakingchangestoOpenShiftCI-PullRequestchecklist

**Comment by porridge** [comment]
> Even if it's opt-in, I don't see a reason not to add it to `release-x.y` (literally `x.y`) so that we don't introduce only-few-folks-can-explain-why fragmentation.

I didn't add it on purpose, because this is a very experimental phase - at this point I'm far from certain that this will ever work. This change as is is the bare minimum necessary to be able iterate on this job. But if you feel strongly I can add it to the template.

**Comment by msugakov** [comment]
> This change as is is the bare minimum necessary to be able iterate on this job.

Ok, I don't mind, but the experience shows it should normally go in one of two directions: get reverted if changes did not work or get "mainlined" if changes proved themselves ok.
A third option is when it's stuck half-done not reverted and not completed. This one is undesirable and the one which concerns me. For me this happens when I started something but got interrupted and then forgot.

As a way to not end up like this, I typically create a JIRA, assign to myself and pull into a sprint. Theoretically, the existing ROX-22594 could fit except that it gets comments traffic from junit2jira and any reminder comment of a kind "Don't forget to sync nongroovy changes to release-x.y branch setup" will get buried in bot comments. Therefore, I'd recommend creating such JIRA.

On the other hand, we argue about an equally small change to `release-x.y` that can be mechanically done in under 5 minutes. Shouldn't be a big deal unless you know something that I don't know, e.g. that `release-x.y` is out of sync with `master` so much that it's reconciling will be a big deal.

Not to contradict myself but rather to not slow down your decision-making:

/lgtm

**Review by msugakov — APPROVED** [review]
/lgtm

**Comment by porridge** [comment]
FTR, https://issues.redhat.com/browse/ROX-24631 created.

**Pull request merged**
