### PR TITLE
Fixing openshift-cluster-api-provider-libvirt-master.yaml to use dockerfile from ocp-build-data

### PR DESCRIPTION
**Pull request by alvaroaleman**

### CODE REVIEW

**Comment by cfergeau** [comment]
The commit log is not giving any details why we want to do that, which problem this is fixing, ... Can you add this?

**Comment by alvaroaleman** [comment]
@cfergeau this pr is syncs the dockerfile configured in ocp-build-data, in the future these will get automerged, see http://post-office.corp.redhat.com/archives/aos-devel/2020-August/msg00110.html for a more detailed explanation. I unfortunately only sent that mail after creating the PRs, so thats why its not included in the body :upside_down_face:

**Pull request merged**
