### PR TITLE
WMCO branching day changes

### PR DESCRIPTION
**Pull request by sebsoto**
Adjusts versioning to line up with golang 1.22 and OCP 4.17.
Changes community fast-forward setting to have community-4.17 track
release-4.17.
Changes upgrade test to upgrade from 4.16 to 4.17.

### CODE REVIEW

**Comment by sebsoto** [comment]
Skipped the rehearse as it will fail due to the WMCO branching PR not being in yet

**Review by jrvaldes — APPROVED** [review]
/lgtm

**Pull request merged**
