### PR TITLE
Update base image for csi-driver-shared-resource

### PR DESCRIPTION
**Pull request by sayan-biswas**
Changes:
- Update base image to 4.17
- Update golang version to 1.22

### CODE REVIEW

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Comment by sayan-biswas** [comment]
/pj-rehearse pull-ci-openshift-csi-driver-shared-resource-release-4.17-e2e-aws-csi-driver-slow

**Pull request merged**
