### PR TITLE
Run E2E AWS single node variant on cluster-etcd-operator presubmit

### PR DESCRIPTION
**Pull request by omertuc**
Based on #15187

EDIT: Added single-node Live CD flow as well

### CODE REVIEW

**Comment by romfreiman** [comment]
e2e-aws-single-node is expected to fail until all the relevant code is merged. Hence the job is neither blocking nor enabled be default.
We just want to have all the building blocks in place and getting ready for 4.8.
@ironcladlou @hexfusion

**Comment by romfreiman** [comment]
@hexfusion @ironcladlou please review

**Comment by hexfusion** [comment]
this is breaking all ci for the repo. need to revert until we can figure out why


```
2021/02/05 16:16:18 ci-operator version v20210204-f833fac
2021/02/05 16:16:18 Loading configuration from https://config.ci.openshift.org for openshift/cluster-etcd-operator@master
error: failed to load configuration: got unexpected http 400 status code from configresolver: failed to resolve config: Failed resolve MultiStageTestConfiguration: no workflow named e2e-aws-single-nodefailed to resolve config with registry: Failed resolve MultiStageTestConfiguration: no workflow named e2e-aws-single-node
time="2021-02-05T16:16:19Z" level=info msg="Reporting job state 'failed' with reason 'loading_args:loading_config:config_resolver'"

```

**Pull request merged**
