### PR TITLE
Add a presubmit to validate the multi-arch image mirroring generation

### PR DESCRIPTION
**Pull request by droslean**
- Added a reference in `Makefile` for both validation and regeneration.
- Added a presubmit to run every time the folder `core-services/image-mirroring` changes.
- Regerate the configs.

/cc @openshift/test-platform 
Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

### CODE REVIEW

**Comment by droslean** [comment]
/hold

It seems that our build_root image has python 2.7.....

**Comment by bear-redhat** [comment]
Is the content changes in `hack/image-mirroring/supplemental_ci_images_mirror_gen.py` are clean ups?

**Comment by droslean** [comment]
@bear-redhat Nope that are the original files that are being maintained by our stakeholders. Based on what images exist in that folder we generate a corresponding mirroring for arm64 architecture.

**Review by jmguzik — APPROVED** [review]

**Pull request merged**
