### PR TITLE
Add new aws-ovn-serial job

### PR DESCRIPTION
**Pull request by jluhrsen**
- creates new periodic job for 4.11 that will run every 48h
- adds job as a nightly payload blocker for 4.11

This is part of the work in https://issues.redhat.com/browse/SDN-2893
towards moving OCP to use ovn-kubernetes as the default CNI in some
future release.

Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>

### CODE REVIEW

**Comment by dgoodwin** [comment]
Suggest just adding the periodic first, then get a week or two's worth of data before beginning discussion around blocking payloads. 

TRT's view is that the bar for blocking payloads needs to be very high, given the difficulties involved with keeping our current blocking jobs passing and payloads flowing. Our request for any new blocking job would be (a) justification for why an informing job or just a periodic is insufficient, (b) proven pass rate, (c) a team channel to direct notifications to when the job falls below expected pass rate, a (d) a manager backstop to be notified when the job flatlines for an extended period, and (e) someone to attend trt scrum once or twice a week to stay in the loop on what's going on. All of this is naturally attempting to deal with the fact that we absolutely must keep payloads flowing, we often can't even with the set of blocking jobs now, and we have a sea of periodics that nobody pays attention to.

We could go halfway and just do (b) (c) and (d) as an informing job.

**Comment by jluhrsen** [comment]
> Suggest just adding the periodic first, then get a week or two's worth of data before beginning
> discussion around blocking payloads.
> 
> TRT's view is that the bar for blocking payloads needs to be very high, given the difficulties involved with keeping our current blocking jobs passing and payloads flowing. Our request for any new blocking job would be
> (a) justification for why an informing job or just a periodic is insufficient,

A big change is coming for OCP where ovn-kubernetes will be the default CNI. The OVN team is searching
for ways to make sure CI is up to par with openshift-sdn to ensure at least the same quality for the platform
for when this happens. Making sure payload jobs are equivalent to openshift-sdn jobs is one idea. There is
an Epic [here](https://issues.redhat.com/browse/SDN-2880) about this effort. An email was sent to aos-devel recently discussing these plans as well.

FYI, I have other PRs to catch up the blocking jobs on both CI and nightly payloads to match openshift-sdn with
ovn-kubernetes versions.


> (b) proven pass rate

understood. Was thinking some number of rehearsals from this PR would suffice, but sounds like we might
want to get the periodic version up and running for a while to have enough data to give confidence. I'll break this
PR up in to two. 1) to create a periodic job and 2) to make it a payload blocker.

> (c) a team channel to direct notifications to when the job falls below expected pass rate, a

#forum-sdn is the channel and @sdn-team or @jamo is what to use

> (d) a manager backstop to be notified when the job flatlines for an extended period, and

I can be the "manager backstop" as well, but my actual manager @vpickard would be my backstop

> (e) someone to attend trt scrum once or twice a week to stay in the loop on what's going on.

The TRT standup is before my working hours (I'm PST), Is there any crossover with the
"Testing/CI + Release Architecture" meeting that would make attendance there acceptable instead?

> All of this is naturally attempting to deal with the fact that we absolutely must keep payloads flowing, we often can't even with the set of blocking jobs now, and we have a sea of periodics that nobody pays attention to.

totally understand the concerns here.

> 
> We could go halfway and just do (b) (c) and (d) as an informing job.

I think with my above reply we are good with this for now, but we can keep the discussion going here or
on slack if needed. whatever works.

**Comment by jluhrsen** [comment]
> understood. Was thinking some number of rehearsals from this PR would suffice, but sounds like we might want to get the periodic version up and running for a while to have enough data to give confidence. I'll break this PR up in to two. 1) to create a periodic job and 2) to make it a payload blocker.

1) is still this PR
2) is [here](https://github.com/openshift/release/pull/28010)

**Pull request merged**
