### PR TITLE
MULTIARCH-4611 - Converting all 4.16 periodics jobs to the UPI workflow

### PR DESCRIPTION
**Pull request by tvardema**
As part of the initiative to remove libvirt from the openshift installer, we need all the 4.16+ periodic jobs to be using the UPI workflow.

### CODE REVIEW

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-fips-ovn-remote-libvirt-ppc64le periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-fips-ovn-remote-libvirt-s390x

**Comment by tvardema** [comment]
/pj-rehearse ocp-image-ecosystem-ovn-remote-libvirt-ppc64le ocp-image-ecosystem-ovn-remote-libvirt-s390x

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-image-ecosystem-ovn-remote-libvirt-ppc64le periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-image-ecosystem-ovn-remote-libvirt-s390x

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-fips-ovn-remote-libvirt-ppc64le

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-image-ecosystem-ovn-remote-libvirt-ppc64le

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-image-ecosystem-ovn-remote-libvirt-s390x

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-image-ecosystem-ovn-remote-libvirt-s390x periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-image-ecosystem-ovn-remote-libvirt-ppc64le

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-image-ecosystem-ovn-remote-libvirt-s390x periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-image-ecosystem-ovn-remote-libvirt-ppc64le periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-e2e-compact-ovn-remote-libvirt-ppc64le periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-e2e-compact-ovn-remote-libvirt-s390x

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-fips-ovn-remote-libvirt-ppc64le

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-fips-ovn-remote-libvirt-ppc64le

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-fips-ovn-remote-libvirt-ppc64le

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-e2e-serial-ovn-remote-libvirt-s390x periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-heavy-build-ovn-remote-libvirt-ppc64le

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-heavy-build-ovn-remote-libvirt-ppc64le periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-e2e-serial-ovn-remote-libvirt-s390x

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-heavy-build-ovn-remote-libvirt-ppc64le periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-e2e-serial-ovn-remote-libvirt-s390x

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-e2e-serial-ovn-remote-libvirt-s390x

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-e2e-serial-ovn-remote-libvirt-ppc64le periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-image-ecosystem-ovn-remote-libvirt-s390x

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-heavy-build-ovn-remote-libvirt-ppc64le periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-heavy-build-ovn-remote-libvirt-s390x

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-e2e-serial-ovn-remote-libvirt-ppc64le periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-e2e-serial-ovn-remote-libvirt-s390x

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-fips-ovn-remote-libvirt-ppc64le periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-fips-ovn-remote-libvirt-s390x

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-e2e-compact-ovn-remote-libvirt-ppc64le periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-e2e-compact-ovn-remote-libvirt-s390x

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-e2e-compact-ovn-remote-libvirt-s390x periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-e2e-compact-ovn-remote-libvirt-ppc64le

**Comment by tvardema** [comment]
/pj-rehearse ocp-image-ecosystem-ovn-remote-libvirt-ppc64le ocp-image-ecosystem-ovn-remote-libvirt-s390x ocp-image-ecosystem-ovn-remote-libvirt-ppc64le ocp-image-ecosystem-ovn-remote-libvirt-ppc64le

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-image-ecosystem-ovn-remote-libvirt-ppc64le periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-image-ecosystem-ovn-remote-libvirt-s390x

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-jenkins-e2e-ovn-remote-libvirt-s390x periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-jenkins-e2e-ovn-remote-libvirt-ppc64le

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.16-upgrade-from-nightly-4.15-ocp-ovn-remote-libvirt-ppc64le periodic-ci-openshift-multiarch-master-nightly-4.16-upgrade-from-nightly-4.15-ocp-ovn-remote-libvirt-s390x

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.16-upgrade-from-nightly-4.15-ocp-ovn-remote-libvirt-ppc64le periodic-ci-openshift-multiarch-master-nightly-4.16-upgrade-from-nightly-4.15-ocp-ovn-remote-libvirt-s390x

**Review by jaypoulz — APPROVED** [review]
/lgtm

**Pull request merged**
