### PR TITLE
onboard member-operator to use openshift-ci

### PR DESCRIPTION
**Pull request by dipak-pawar**
My team is working on SaaS project called codeready toolchain. While thinking of design, we decided to go with two operators i.e. host and member operators to implement required functionality for it. we'd like to use openshift-ci for our operators.
 
This PR onboards  member-operator  to use openshift CI.

### CODE REVIEW

**Comment by dipak-pawar** [comment]
/hold 
as blocked by https://github.com/codeready-toolchain/member-operator/pull/3

**Comment by knobunc** [comment]
This is failing because of a bad import: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/797/pull-ci-openshift-machine-config-operator-master-images/2698

```
could not wait for build: the build machine-config-daemon failed after 45s with reason DockerBuildFailed: Docker build strategy has failed.

Using version from git...
Building github.com/openshift/machine-config-operator/cmd/...-gcfa394e4-dirty, cfa394e44bc9f4f52330fdedc599eaacdab0102f)
# github.com/openshift/machine-config-operator/pkg/daemon
pkg/daemon/update.go:8:2: imported and not used: "io"
error: build error: running 'WHAT=machine-config-daemon ./hack/build-go.sh' failed with exit code 2
```

**Comment by dipak-pawar** [comment]
> This is failing because of a bad import: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/797/pull-ci-openshift-machine-config-operator-master-images/2698

This is not related to this repository

**Pull request merged**
