### PR TITLE
Update root image for cnv-ci-src

### PR DESCRIPTION
**Pull request by rabin-io**

### CODE REVIEW

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-openshift-release-master-cnv-nightly-4.18-e2e-azure-deploy-cnv

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-openshift-release-master-cnv-nightly-4.18-e2e-azure-deploy-cnv

**Comment by tiraboschi** [comment]
/pj-rehearse periodic-ci-openshift-release-master-cnv-nightly-4.18-e2e-azure-deploy-cnv

**Comment by rabin-io** [comment]
/pj-rehearse ack

@tiraboschi can you please review and LGTM the PR?

**Pull request merged**
