### PR TITLE
generate multiple testing users and skip the OCP idp-htpasswd for rosa/osd

### PR DESCRIPTION
**Pull request by yasun1**
close [OCPQE-13421](https://issues.redhat.com//browse/OCPQE-13421)

### CODE REVIEW

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-ocm-osd-ccs-p2-f7

**Comment by yasun1** [comment]
@liangxia The OSD/ROSA cluster always recovers the internal changes in the cluster, etc. add HTPasswd via oc(step: idp-htpasswd). Now in this PR, we will generate the test users for the OCP e2e test from the ocm side. Please help review the code.

**Comment by xingxingxia** [comment]
/hold
Should https://github.com/openshift/release/blob/master/ci-operator/step-registry/idp/htpasswd/idp-htpasswd-commands.sh have some changes?

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-ocm-osd-ccs-p2-f7

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-ocm-osd-ccs-p2-f7

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-ocm-osd-ccs-p2-f7

**Pull request merged**
