### PR TITLE
cnf-features-deploy updates for release-4.15 branch cut

### PR DESCRIPTION
**Pull request by Sandeepyadav93**
configuration changes
jobs update
image mapping update

### CODE REVIEW

**Comment by SchSeba** [comment]
/override ci/rehearse/openshift-kni/cnf-features-deploy/master/e2e-gcp-ovn 
/pj-rehearse

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.15-e2e-aws-ran-profile pull-ci-openshift-kni-cnf-features-deploy-master-e2e-gcp-ovn

**Comment by Sandeepyadav93** [comment]
/pj-rehearse ack

ovn job failure in master branch is known.

**Pull request merged**
