### PR TITLE
OCPQE-14727: update hypershift-guest test chain

### PR DESCRIPTION
**Pull request by LiangquanLi930**

### CODE REVIEW

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-ovn-hypershift-guest-p1-f21-destructive

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-ovn-hypershift-guest-p1-f7

**Comment by LiangquanLi930** [comment]
@kuiwang02 @liangxia, Could you help to review this PR? Thanks

**Comment by kuiwang02** [comment]
iamok from golang's view

**Comment by YuLi517** [comment]
@liangxia This PR will be needed for hosted cluster installation. Currently, our hosted cluster installation keep on failing in prow. Could you help to review it on priority? Thanks in advance.

**Pull request merged**
