### PR TITLE
Sync Serverless CI config/eventing-kafka-broker.yaml

### PR DESCRIPTION
**Pull request by creydr**
Remove partitions-replication-verifier image (was removed from EKB in https://github.com/knative-sandbox/eventing-kafka-broker/pull/2931/files#diff-d6b50804e8307543633a8febd1be9a12254aa50a68d48107e1158d91c35904e4)

https://github.com/openshift-knative/eventing-kafka-broker/pull/599 is having these issues

### CODE REVIEW

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-kafka-broker-release-next-412-images

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-kafka-broker-release-next-412-images

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
