### PR TITLE
Migrate openshift/knative-eventing to openshift-knative/eventing

### PR DESCRIPTION
**Pull request by mgencur**
https://issues.redhat.com/browse/SRVKE-1314

/hold

### CODE REVIEW

**Review by pierDipi — COMMENTED** [review]
To be safe, can we just add new jobs and only remove periodics from the old repo but without removing pre and post submits for the old repository?

**Comment by mgencur** [comment]
This is getting complicated:
``` {"component":"checkconfig","error":"error loading prow config: [duplicated basename is not allowed: openshift-knative-eventing-release-next-postsubmits.yaml, duplicated basename is not allowed: openshift-knative-eventing-release-next-presubmits.yaml, duplicated basename is not allowed: openshift-knative-eventing-release-v1.3-postsubmits.yaml, duplicated basename is not allowed: openshift-knative-eventing-release-v1.3-presubmits.yaml, duplicated basename is not allowed: openshift-knative-eventing-release-v1.4-postsubmits.yaml, duplicated basename is not allowed: openshift-knative-eventing-release-v1.4-presubmits.yaml, duplicated basename is not allowed: openshift-knative-eventing-release-v1.5-postsubmits.yaml, duplicated basename is not allowed: openshift-knative-eventing-release-v1.5-presubmits.yaml, duplicated basename is not allowed: openshift-knative-eventing-release-v1.6-postsubmits.yaml, duplicated basename is not allowed: openshift-knative-eventing-release-v1.6-presubmits.yaml]","file":"k8s.io/test-infra/prow/cmd/checkconfig/main.go:248","func":"main.main","level":"fatal","msg":"Validation failed","severity":"fatal","time":"2022-11-15T15:12:16Z"} 
```

**Comment by mgencur** [comment]
Since the migration for Serving went well in terms of CI setup I'd probably return back to the original solution - add the new CI config and remove the old CI config in one PR.
I'm not sure how to fix the error above.

**Comment by mgencur** [comment]
@smg247 Could you please review once again? The registry-replacer job caused a conflict so I had to rebase and re-push. Thanks!

**Review by pierDipi — APPROVED** [review]
/lgtm

**Pull request merged**
