### PR TITLE
OCPBUGS-42318: openstack-tests: force IPv6 endpoint

### PR DESCRIPTION
**Pull request by EmilienM**
force IPv6 endpoint in openstack-tests when needed

### CODE REVIEW

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-e2e-openstack-singlestackv6

**Comment by MaysaMacedo** [comment]
Can you create a JIRA card so we don't forget to investigate it?

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-e2e-openstack-singlestackv6

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-e2e-openstack-singlestackv6

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-e2e-openstack-singlestackv6

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-e2e-openstack-singlestackv6

**Comment by EmilienM** [comment]
I need to trigger the job so I can check if the CCM cloud.conf secret has the right URL because the test says it doesn't.

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-e2e-openstack-singlestackv6

**Comment by MaysaMacedo** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-e2e-openstack-singlestackv6

**Comment by mandre** [comment]
For the record, I'm partially reverting https://github.com/openshift/release/pull/56932/ in https://github.com/openshift/release/pull/57131, so that's likely something you want to pull back in here.

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-e2e-openstack-singlestackv6

**Pull request merged**
