### PR TITLE
cluster-launch-installer-e2e: remove etcd nodes

### PR DESCRIPTION
**Pull request by crawford**
etcd nodes have been removed from the installer.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
Etcd nodes are being removed from installer here https://github.com/openshift/installer/pull/168

**Comment by wking** [comment]
Can we also remove [`autoScalingGroupExtraTags`][1] here to catch up with the merged-yesterday openshift/installer#88?  Or should I file a separate PR for that?

[1]: https://github.com/openshift/release/blob/d06179d4daa49e7ea81d938b9d6f6240ff6dcbf2/cluster/test-deploy/aws/openshift.yaml#L11-L15

**Comment by wking** [comment]
Looks like we also want to remove `tlsValidityPeriod` to catch up with coreos/tectonic-installer#3262.

**Comment by crawford** [comment]
@wking I'll tackle it here.

**Comment by stevekuznetsov** [comment]
@wking @crawford hey guys -- if there is config in this repo that is `openshift/installer`-specific, please add yourselves to the OWNERS for those files. See the `ci-operator/templates/OWNERS` file for an example. Tag me and I can merge that, I want you guys to be able to self-service your own config in here

**Comment by eparis** [comment]
I'm wondering if we shouldn't revert...
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/176/pull-ci-origin-installer-e2e-aws/682/

@crawford @wking

**Comment by eparis** [comment]
I'm going to revert, because it broke CI.  We'll try again when https://github.com/openshift/installer/pull/168 is ready to try again.

**Pull request merged**
