### PR TITLE
Use repo as build root for CPMSO image

### PR DESCRIPTION
**Pull request by Fedosin**
To include required manifests we need to set "from_repository" to true.

Generated by `make jobs`

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
the `from_repository` makes sense, but what does `skip_cloning` do?

**Comment by Fedosin** [comment]
Currently CI [documentation](https://docs.ci.openshift.org/docs/architecture/timeouts/) doesn't mention what `skip_cloning` does. As I understand `skip_cloning: true` prevents copying of .ci-operator.yaml file from the repository during ci job run.

**Pull request merged**
