### PR TITLE
Azure OVNKubernetes ipi workflow

### PR DESCRIPTION
**Pull request by davidvossel**
I'm working on hypershift's KubeVirt platform and I need an ipi workflow for setting up Azure with OVN.

### CODE REVIEW

**Comment by aravindhp** [comment]
/cc @JacobTanenbaum 

Jacob please take over ownership of this step registry configuration and assign someone from the SDN team in addition.

**Comment by nunnatsa** [comment]
@aravindhp, @ravisantoshgudimetla - could you please approve this PR?

**Comment by stbenjam** [comment]
Missing an OWNERS file. Why not do this all in one PR along with the gcp one? I’m not clear how these steps will be used.

**Comment by davidvossel** [comment]
I've combined this logic with the gcp OVN workflow in a new pr, #28670

**Comment by stbenjam** [comment]
> > Missing an OWNERS file.
> 
> @stbenjam This directory already has an OWNERS file.

Ok, but that appears to be for the hybrid job? Who's maintaining this new workflow?

> > Why not do this all in one PR along with the gcp one?
> 
> I split this into two PRs because I wasn't sure if we'd need separate people to approve since two cloud providers are involved.
> 
> > I’m not clear how these steps will be used.
> 
> This step is used during the IPI install of OCP on Azure. It transforms a default install (OpenshiftSDN) to one that will use OVNKubernetes for the pod network.

Sorry, what I was asking for is I think this PR should contain the jobs you're going to add that make use of it so we can see a rehearse to know the workflow does what you want.  This workflow is pretty lightweight, there are other `e2e` workflows that include tests, is that not what you want?  That's why I want to see a job so I have a good idea of what the workflow is for.

**Pull request closed without merging**
