### PR TITLE
Move machine config operator packet jobs to new equinix profile

### PR DESCRIPTION
**Pull request by ardaguclu**
The current packet account will soon be closed. This PR moves to new packet account, namely equinix-ocp-metal.

### CODE REVIEW

**Comment by ardaguclu** [comment]
cc: @andfasano @derekhiggins

**Comment by ardaguclu** [comment]
@kikisdeliveryservice could you please take a look at this change?. Old cluster_profile will be removed and we are moving to new cluster_profile. Thanks.

**Comment by derekhiggins** [comment]
@rfredette would you be able to take a look please, the old account it due to close tomorrow

**Comment by kikisdeliveryservice** [comment]
This is just an infra change and doesn't fundamentally change the jobs right? Seems fine to me.. should I wait for @rfredette to view?

**Comment by ardaguclu** [comment]
> This is just an infra change and doesn't fundamentally change the jobs right? Seems fine to me.. should I wait for @rfredette to view?

Thanks @kikisdeliveryservice. Yes, this is just an infra change and does not change anything beyond that.

**Comment by cybertron** [comment]
Packet setup seems to be failing on all of the jobs I've looked at so far:

 2022-01-28 17:30:38 TASK [create Packet host ipi-ci-op-k4ls5vi3-42607-1487112217504518144] *********
2022-01-28 17:30:42 fatal: [localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false} 

/test pj-rehearse
to see if we just got unlucky and hit an outage.

**Comment by ardaguclu** [comment]
> Packet setup seems to be failing on all of the jobs I've looked at so far:
> 
>  2022-01-28 17:30:38 TASK [create Packet host ipi-ci-op-k4ls5vi3-42607-1487112217504518144] *********
> 2022-01-28 17:30:42 fatal: [localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false} 
> 
> /test pj-rehearse
> to see if we just got unlucky and hit an outage.

Thanks @cybertron. Yesterday, there was an incident due to Centos EOL. Problem should be solved in current running jobs.

**Comment by kikisdeliveryservice** [comment]
(just waiting for jobs to run/pass to add approval)

**Comment by kikisdeliveryservice** [comment]
Should pj_reherse (and the other running jobs) be taking almost 4 hours??? :grimacing:

**Comment by kikisdeliveryservice** [comment]
@cybertron wdyt on these tests?

i'll retry in the meantime

/retest

**Comment by ardaguclu** [comment]
> @cybertron wdyt on these tests?
> 
> i'll retry in the meantime
> 
> /retest

7 tests passed and 3 failed. I looked at the failing ones and they are not related to this change(new cluster_profile worked and they were able to run a cluster to test).

**Comment by cybertron** [comment]
Yeah, I looked at some of the failures yesterday (and apparently forgot to send my comment, sigh) and they all got through dev-scripts setup which means the equinix infra was working correctly. I think we're good to go.

/lgtm

**Review by kikisdeliveryservice — APPROVED** [review]
This seems good to go, thanks @ardaguclu @cybertron

**Pull request merged**
