### PR TITLE
Set network type ovn

### PR DESCRIPTION
**Pull request by rccrdpccl**
workaround to fix e2e-agent-compact-ipv4

### CODE REVIEW

**Comment by rccrdpccl** [comment]
/hold
testing if this change would fix agent-compact-ipv4 job

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-e2e-agent-compact-ipv4

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-e2e-agent-compact-ipv4

**Comment by rccrdpccl** [comment]
/hold
this is a workaround that we could use if we can't wait for https://github.com/openshift-metal3/dev-scripts/pull/1622

If needed feel free to lgtm and unhold

**Review by gamli75 — APPROVED** [review]

**Comment by eifrach** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-e2e-agent-compact-ipv4

**Pull request merged**
