### PR TITLE
vSphere: openshift kubernetes run ipi vs upi

### PR DESCRIPTION
**Pull request by jcpowermac**
For vSphere the default install type running for CI jobs
should be IPI. Modifying to reflect that.

### CODE REVIEW

**Comment by gnufied** [comment]
Do we know how did we end up with this? I am just curious, it should have been breaking before too - isn't it?

**Comment by jsafrane** [comment]
I don't like all rehearsals failed with
```
http://base-4-3-rhel8.ocp.svc/rhel-8-server-ose/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
```
/retest

**Review by soltysh — APPROVED** [review]
More information is in https://bugzilla.redhat.com/show_bug.cgi?id=2038389 also the support matrix for vSphere is laid out in https://github.com/openshift/enhancements/blob/master/enhancements/storage/csi-vsphere-operator.md and https://docs.openshift.com/container-platform/4.9/installing/installing_vsphere/preparing-to-install-on-vsphere.html#installation-vsphere-infrastructure_preparing-to-install-on-vsphere

/lgtm
/approve

**Pull request merged**
