### PR TITLE
Revert "Run E2E AWS single node variant on cluster-etcd-operator presubmit"

### PR DESCRIPTION
**Pull request by hexfusion**
this is breaking all ci for the repo. need to revert until we can figure out why

```
2021/02/05 16:16:18 ci-operator version v20210204-f833fac
2021/02/05 16:16:18 Loading configuration from https://config.ci.openshift.org for openshift/cluster-etcd-operator@master
error: failed to load configuration: got unexpected http 400 status code from configresolver: failed to resolve config: Failed resolve MultiStageTestConfiguration: no workflow named e2e-aws-single-nodefailed to resolve config with registry: Failed resolve MultiStageTestConfiguration: no workflow named e2e-aws-single-node
time="2021-02-05T16:16:19Z" level=info msg="Reporting job state 'failed' with reason 'loading_args:loading_config:config_resolver'"

```

Reverts openshift/release#14757

### CODE REVIEW

**Comment by retroflexer** [comment]
Since this is breaking ci, we need to revert while we figure out why.

/lgtm

**Comment by bbguimaraes** [comment]
@hexfusion, @retroflexer: https://github.com/openshift/release/pull/15589.

**Pull request merged**
