### PR TITLE
Add 4.5 to 4.12 upgrade test on Azure

### PR DESCRIPTION
**Pull request by shellyyang1989**
Closes [OCPQE-12662](https://issues.redhat.com/browse/OCPQE-12662)

### CODE REVIEW

**Comment by xingxingxia** [comment]
```
export OC_DIR="/tmp/client"
...
export PATH=${OC_DIR}:${JQ_DIR}:$PATH
...
    echo -e "Extracting oc\n"
    ...
    while ! (oc adm release extract -a "${CLUSTER_PROFILE_DIR}/pull-secret" --command=oc --to=${OC_DIR} ${TARGET});
```
The code executes oc program located in OC_DIR to replace oc binary in OC_DIR meantime, this causes above `/test pj-rehearse` failure:
```
Extracting oc
Failed to extract oc binary, retry...
...
Failed to extract oc binary, retry...
```
Need to use a middle dir e.g. /tmp/client-2, extract to it, then mv it to OC_DIR.

**Comment by xingxingxia** [comment]
Another issue, Azure cluster will be pruned after 12h age, unless extended with https://url.corp.redhat.com/Temporarily-preserving-a-Resource-Group-Azure . In Jenkins e2e this is often seen and causes failures after cluster pruned which adds useless efforts of CI watchers reporting and assignees analyzing. Can it be extended in this PR or somewhere?

**Comment by shellyyang1989** [comment]
> Need to use a middle dir e.g. /tmp/client-2, extract to it, then mv it to OC_DIR.

Thanks @xingxingxia!

**Comment by shellyyang1989** [comment]
> Another issue, Azure cluster will be pruned after 12h age, unless extended with https://url.corp.redhat.com/Temporarily-preserving-a-Resource-Group-Azure . In Jenkins e2e this is often seen and causes failures after cluster pruned which adds useless efforts of CI watchers reporting and assignees analyzing. Can it be extended in this PR or somewhere?

Yeah, I've thought of it and talked to WeiSun. I have no idea if we are able to get around of the prunner/cannon in Prow. Let's ask @liangxia @jhou1 for their expertise.

**Comment by shellyyang1989** [comment]
oc extract failed again.

```
Extracting oc
error: image did not contain usr/bin/oc
Failed to extract oc binary, retry...
error: image did not contain usr/bin/oc
```

But we have injected oc by `cli: latest` in the toimage ref.

```
ref:
  as: cucushift-upgrade-toimage
  from: ansible
  timeout: 24h
  grace_period: 10m
  commands: cucushift-upgrade-toimage-commands.sh
  cli: latest
```

**Comment by liangxia** [comment]
> oc extract failed again.
> 
> ```
> Extracting oc
> error: image did not contain usr/bin/oc
> Failed to extract oc binary, retry...
> error: image did not contain usr/bin/oc
> ```
> 
> But we have injected oc by `cli: latest` in the toimage ref.
> 
> ```
> ref:
>   as: cucushift-upgrade-toimage
>   from: ansible
>   timeout: 24h
>   grace_period: 10m
>   commands: cucushift-upgrade-toimage-commands.sh
>   cli: latest
> ```

Because oc is inject to `/cli/oc`

**Comment by shellyyang1989** [comment]
Hi @jinyunma do you have any idea about the error?
```
INFO[2022-11-11T02:43:53Z] Running step vsphere-ipi-ipi-conf-vsphere-dns. 
INFO[2022-11-11T02:44:04Z] Logs for container test in pod vsphere-ipi-ipi-conf-vsphere-dns: 
INFO[2022-11-11T02:44:04Z] 2022-11-11 02:43:59+00:00 - Install AWS cli...
Searching for pip<21
Reading https://pypi.python.org/simple/pip/
Couldn't find index page for 'pip' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for pip<21
```

**Comment by jinyunma** [comment]
> do you have any idea about the error?

as we discussed offline, try to use high version of tools image to see issue get resolved or not?

**Comment by shellyyang1989** [comment]
Upgrade test failed on 4.10 to 4.11 because the hw version doesn't meet requirement. Seems like we need to upgrade the hw version.

 ```
- lastTransitionTime: "2022-11-11T18:02:50Z"
    message: 'Cluster operator storage should not be upgraded between minor versions:
      VSphereCSIDriverOperatorCRUpgradeable: VMwareVSphereControllerUpgradeable: node
      ci-op-zpvj44ig-3d8b9-7nzh2-worker-4tlpv has hardware version vmx-13, which is
      below the minimum required version 15'
    reason: VSphereCSIDriverOperatorCR_VMwareVSphereController_check_deprecated_hw_version
    status: "False"
    type: Upgradeable
```

**Comment by shellyyang1989** [comment]
As @chengzhang1016 suggested, we change the platform of 4.5 to 4.12 upgrade from vSphere to Azure to make it proceed. Will cover vSphere in any of 4.6, 4.7, 4.8... to latest upgrade later.

**Comment by chengzhang1016** [comment]
Yes, there is a test gap of Upgrade Path 4.5 --> 4.12 in the testing of 4.12.0 (we didn't cover it whether on Prow or on Jenkins). I hope we can fill up the gap asap. I'm assuming the automation block issue on vSphere cannot be resolved quickly, so suggest moving to other cloud providers.
We can cover the vSphere on other Upgrade Paths (such as 4.6 -->4.12 or 4.7 --> 4.12) on Prow,  we also have more time for solving the problem since the implement of these Upgrade Paths are not urgent on Prow (we have triggered these Upgrade Paths on Jenkins).
cc: @shellyyang1989 @jiajliu @Xia-Zhao-rh @xiuwang @liangxia @jhou1

**Pull request merged**
