### PR TITLE
core-services/prow/02_config/openshift/cincinnati-graph-data/_prowconfig: Trust openshift-ota-bot

### PR DESCRIPTION
**Pull request by wking**
Don't require ok-to-test, lgtm, or approval for this bot.  We want its pull requests to land automatically, and if we need to touch something to land PRs it files, that defeats the purpose.  Some notes on the mechanics in the commit messages.

### CODE REVIEW

**Review by vrutkovs — APPROVED** [review]
/lgtm

**Comment by vrutkovs** [comment]
>{"component":"checkconfig","file":"k8s.io/test-infra/prow/cmd/checkconfig/main.go:90","func":"main.reportWarning","level":"warning","msg":"the following orgs or repos enable the bugzilla plugin but do not forbid the bugzilla/invalid-bug label for merging: [repo: openshift/cincinnati-graph-data]","severity":"warning","time":"2022-04-13T18:08:18Z"}

Not sure how important that is, but may be worth fixing

**Comment by wking** [comment]
/hold cancel

I fixed the earlier Bugzilla complaint by restoring the invalid-bug label.

**Pull request merged**
