### PR TITLE
Add cloud API tests for Azure chaos

### PR DESCRIPTION
**Pull request by chaitanyaenr**

### CODE REVIEW

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.15-nightly-krkn-hub-tests-415-azure

**Comment by chaitanyaenr** [comment]
/pj-rehearse  periodic-ci-redhat-chaos-prow-scripts-main-4.15-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.15-nightly-krkn-hub-tests-415-azure

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.15-nightly-krkn-hub-tests-415-azure

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.15-nightly-krkn-hub-tests-415-azure

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.15-nightly-krkn-hub-tests-415-azure

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.15-nightly-krkn-hub-tests-415-azure

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.15-nightly-krkn-hub-tests-415-azure

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.15-nightly-krkn-hub-tests-415-azure

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.15-nightly-krkn-hub-tests-415-azure

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.15-nightly-krkn-hub-tests-415-azure

**Comment by paigerube14** [comment]
think the changes in [my pr](https://github.com/openshift/release/pull/52581) cover what is added here

**Pull request closed without merging**
