### PR TITLE
openstack: test root volumes in specific AZ

### PR DESCRIPTION
**Pull request by EmilienM**
Adding coverage to test boot from volume when using availability zones.

### CODE REVIEW

**Comment by EmilienM** [comment]
I patched the 4.11 job to trigger it in rehearse. I'll remove it when I know it works.

**Comment by EmilienM** [comment]
it worked: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/27462/rehearse-27462-periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.12-e2e-openstack-az/1543985687370403840/artifacts/e2e-openstack-az/openstack-gather/artifacts/openstack_nodes.log

**Review by mandre — COMMENTED** [review]
Thanks. This fixes OSASINFRA-2545.
/lgtm
/approve

**Pull request merged**
