### PR TITLE
extdns: update ocp version to latest on main branches

### PR DESCRIPTION
**Pull request by alebedev87**
Update the versions of the OpenShift clusters on which the tests are run.

### CODE REVIEW

**Comment by alebedev87** [comment]
/pj-rehearse pull-ci-openshift-external-dns-operator-main-verify

**Comment by alebedev87** [comment]
Rebased from `master` to fix `ordered-prow-config`.

**Comment by gcs278** [comment]
One nit on the description - you don't mention external dns operator, might be good to mention that.

**Comment by gcs278** [comment]
Ehh you mention it in the title, not a big deal.

**Comment by alebedev87** [comment]
@gcs278 : I don't know if there is any convention in this repository but I try to mention the components impacted. Since both the operator and operand were touched I didn't want the commit and the title to be too long and shortened it to `extdns` similar to https://github.com/openshift/release/pull/46634 and https://github.com/openshift/release/pull/35668.

**Pull request merged**
