### PR TITLE
SPLAT-1250: Removed tech preview for vSphere IPI Static IP.

### PR DESCRIPTION
**Pull request by vr4manta**
[SPLAT-1250](https://issues.redhat.com/browse/SPLAT-1250)

### Changes
- Removed TechPreviewNoUpgrade from vSphere IPI Static IP jobs

### CODE REVIEW

**Comment by vr4manta** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-vsphere-static-ovn

**Review by r4f4 — COMMENTED** [review]
/approve

**Review by vrutkovs — APPROVED** [review]
/approve

**Pull request merged**
