### PR TITLE
Move update trust policy for shared-vpc to a step and mask the AWS billing account

### PR DESCRIPTION
**Pull request by yasun1**
To keep the provision step clean, move the extra update steps to the individual step. -- [OCPQE-19582](https://issues.redhat.com//browse/OCPQE-19582)
Also mask the AWS billing account in the logs.

### CODE REVIEW

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-stable-aws-rosa-sts-shared-vpc-f14

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-stable-aws-rosa-sts-shared-vpc-f14 periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-stable-aws-rosa-sts-hcp-advanced-stage-critical-f14

**Comment by yasun1** [comment]
@xueli181114 @yunjiang29 Please help review the PR. Thanks.

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-stable-aws-rosa-sts-shared-vpc-f14

**Pull request merged**
