### PR TITLE
include the local image-pusher credentials in all registry-push-credentials-ci-central secrets

### PR DESCRIPTION
**Pull request by droslean**
/cc @openshift/test-platform @hongkailiu

### CODE REVIEW

**Review by hongkailiu — COMMENTED** [review]
/hold

We have the key already in the map.
Let us do a meeting again to clarify your request.

**Comment by hongkailiu** [comment]
> I am guessing that we can remove the pull credentials and use the push only. My request is the same. I need to push to the local registry instead of just pulling.

If the push is from a build farm to the local registry the credentials in `registry-push-credentials-ci-central` should work.
For example, push on build01, then please try with `registry-push-credentials-ci-central` in the `ci` namespace on build01. It has the permissions already and is used by our promotion pod.

As we discussed, the only concern that I have about it is that you probably should use a new service account dedicated to the new component so that we can tell from audit log who-did-what if needed in the future.
But i am fine too if you want to unblock your story with the existing SA image-pusher.

**Comment by droslean** [comment]
> > I am guessing that we can remove the pull credentials and use the push only. My request is the same. I need to push to the local registry instead of just pulling.
> 
> If the push is from a build farm to the local registry the credentials in `registry-push-credentials-ci-central` should work. For example, push on build01, then please try with `registry-push-credentials-ci-central` in the `ci` namespace on build01. It has the permissions already and is used by our promotion pod.
> 
> As we discussed, the only concern that I have about it is that you probably should use a new service account dedicated to the new component so that we can tell from audit log who-did-what if needed in the future. But i am fine too if you want to unblock your story with the existing SA image-pusher.

@hongkailiu I don't understand why we need a different service account. `ci-operator` is already pulling and pushing images on the local imagestream. I am just trying to understand how manifest-tool can use the same creds

**Comment by hongkailiu** [comment]
> @hongkailiu I don't understand why we need a different service account. `ci-operator` is already pulling and pushing images on the local imagestream. I am just trying to understand how manifest-tool can use the same creds

One tool/component has its own pod, SA, etc. Like deck, sink, hook from Prow. Each one has its own SA. If the component `ci-operator` pushes image, we should use `sa/ci-operator`. If it is another component X, then `sa/X` should be used.

**Comment by droslean** [comment]
> > @hongkailiu In addition, using push credentials we already mount in ci-operator don't have permission to push in the local registry. You can see: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-vega-project-ccb-operator-master-images/1699046922691547136
> 
> Which secret did it use?

The registry-push-credentials-ci-central.


> > @hongkailiu I don't understand why we need a different service account. `ci-operator` is already pulling and pushing images on the local imagestream. I am just trying to understand how manifest-tool can use the same creds
> 
> One tool/component has its own pod, SA, etc. Like deck, sink, hook from Prow. Each one has its own SA. If the component `ci-operator` pushes image, we should use `sa/ci-operator`. If it is another component X, then `sa/X` should be used.

The operation is happening inside ci-operator. It would make sense to use the `sa/ci-operator`, but I am ok creating a new serviceAccount as well. This will require mounting the sa dockercfg into the pod, therefore change in prowgen will be required.

**Comment by hongkailiu** [comment]
> The registry-push-credentials-ci-central.

Could you show me the yaml of the pod?
Because the secret should be able to push to any build farm: I am fairly sure of it. ^_^ We have used it for all the image jobs for very long time.
As we discussed in the meeting, you can extract the secret and play with it on in an isolated pod. Much easier to debug.

**Comment by droslean** [comment]
@hongkailiu You can see the job: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-vega-project-ccb-operator-master-images/1699046922691547136

I also tested it manually in build01. Those credentials don't have permission to push anything to the registry.

I am guessing that's because the creds are for pulling only since we are generating the config from the `image-puller` serviceAccount. That is why in my https://github.com/openshift/ci-tools/pull/3603 I tried to add the pusher credentials instead.

Otherwise, I could create new RBACs for a new serviceAccount and then change `prowgen` to mount the secret to all jobs, which I tried to avoid.

**Comment by hongkailiu** [comment]
> I also tested it manually in build01.

Could you show me the steps of your manual test?
I would expect the pod yaml with oc-image-mirror as the cmd using the credentials coming from the secret `registry-push-credentials-ci-central`.

**Comment by droslean** [comment]
> > I also tested it manually in build01.
> 
> Could you show me the steps of your manual test? I would expect the pod yaml with oc-image-mirror as the cmd using the credentials coming from the secret `registry-push-credentials-ci-central`.

You can spawn a pod from the `ci-tools-build-root:1.19` which contains the `manifest-tool` binary. You can mount the `registry-push-credentials-ci-central` secret and use them to run the manifest-tool to create a new image with the manifest and push it. The credentials don't have permissions. This is exactly what https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-vega-project-ccb-operator-master-images/1699046922691547136 did. You can see errors like:
```console
time="2023-09-05T13:10:13Z" level=debug msg="fetch response received" digest="sha256:7a518c2b2063814dad7ec22ebe1e64698e90195c0f3c217787c19ba19bb9e0de" mediatype=application/vnd.docker.distribution.manifest.list.v2+json response.header.content-length=248 response.header.content-type="application/json; charset=utf-8" response.header.date="Tue, 05 Sep 2023 13:10:13 GMT" response.header.docker-distribution-api-version=registry/2.0 response.header.www-authenticate="Basic realm=openshift,error=\"access denied\"" response.header.x-registry-supports-signatures=1 response.status="401 Unauthorized" size=402 url="https://image-registry.openshift-image-registry.svc:5000/v2/ci-op-6t77ih93/pipeline/manifests/src"
```

https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-vega-project-ccb-operator-master-images/1699046922691547136#1:build-log.txt%3A36

**Pull request closed without merging**
