### PR TITLE
update cloud team test profiles

### PR DESCRIPTION
**Pull request by sunzhaohua2**
I don't think we need to cover same workflow in nightly, stable, arm for cloud team, I want to keep it only in nightly job, for stable and arm we have included other workflow for aws platform

@huali9 @jhou1 @miyadav PTAL, thanks!

### CODE REVIEW

**Comment by jianlinliu** [comment]
@sunzhaohua2 seem like there are some remaining long-duration test jobs, can you help have a double check:
```
[jianlinliu@jialiu-laptop openshift-tests-private]$ grep -r "as: .*long-duration"|egrep "stable|arm64"
openshift-openshift-tests-private-release-4.10__arm64-nightly.yaml:- as: aws-ipi-p3-f28-long-duration-part1-3
openshift-openshift-tests-private-release-4.10__arm64-nightly.yaml:- as: aws-ipi-p3-f28-long-duration-part2-3
openshift-openshift-tests-private-release-4.10__arm64-nightly.yaml:- as: aws-ipi-p3-f28-long-duration-part3-3
openshift-openshift-tests-private-release-4.12__amd64-stable.yaml:- as: aws-ipi-disconnected-private-tp-p3-f28-long-duration-cloud
openshift-openshift-tests-private-release-4.12__amd64-stable.yaml:- as: aws-ipi-p3-f28-long-duration-part1-3
openshift-openshift-tests-private-release-4.12__amd64-stable.yaml:- as: aws-ipi-p3-f28-long-duration-part2-3
openshift-openshift-tests-private-release-4.12__amd64-stable.yaml:- as: aws-ipi-p3-f28-long-duration-part3-3
openshift-openshift-tests-private-release-4.12__amd64-stable.yaml:- as: aws-usgov-ipi-private-sts-p3-f28-long-duration-cloud
openshift-openshift-tests-private-release-4.12__amd64-stable.yaml:- as: azure-ipi-p3-f28-long-duration-part3-3
openshift-openshift-tests-private-release-4.12__amd64-stable.yaml:- as: azure-ipi-workers-marketimage-p3-f28-long-duration-cloud
openshift-openshift-tests-private-release-4.12__amd64-stable.yaml:- as: gcp-ipi-p3-f28-long-duration-part3-3
openshift-openshift-tests-private-release-4.12__amd64-stable.yaml:- as: gcp-ipi-proxy-techpreview-p3-f28-long-duration-cloud
openshift-openshift-tests-private-release-4.12__arm64-stable.yaml:- as: aws-ipi-disconnected-private-tp-p3-f28-long-duration-cloud
openshift-openshift-tests-private-release-4.12__arm64-stable.yaml:- as: aws-ipi-p3-f28-long-duration-part1-3
openshift-openshift-tests-private-release-4.12__arm64-stable.yaml:- as: aws-ipi-p3-f28-long-duration-part2-3
openshift-openshift-tests-private-release-4.12__arm64-stable.yaml:- as: aws-ipi-p3-f28-long-duration-part3-3
openshift-openshift-tests-private-release-4.12__arm64-stable.yaml:- as: azure-ipi-p3-f28-long-duration-part3-3
openshift-openshift-tests-private-release-4.9__amd64-stable.yaml:- as: aws-ipi-p3-f28-long-duration-part1-3
openshift-openshift-tests-private-release-4.9__amd64-stable.yaml:- as: aws-ipi-p3-f28-long-duration-part2-3
openshift-openshift-tests-private-release-4.9__amd64-stable.yaml:- as: aws-ipi-p3-f28-long-duration-part3-3
openshift-openshift-tests-private-release-4.9__amd64-stable.yaml:- as: azure-ipi-p3-f28-long-duration-part3-3
openshift-openshift-tests-private-release-4.9__amd64-stable.yaml:- as: gcp-ipi-p3-f28-long-duration-part3-3
openshift-openshift-tests-private-release-4.8__amd64-stable.yaml:- as: aws-ipi-p3-f28-long-duration-part1-3
openshift-openshift-tests-private-release-4.8__amd64-stable.yaml:- as: aws-ipi-p3-f28-long-duration-part2-3
openshift-openshift-tests-private-release-4.8__amd64-stable.yaml:- as: aws-ipi-p3-f28-long-duration-part3-3
openshift-openshift-tests-private-release-4.8__amd64-stable.yaml:- as: azure-ipi-p3-f28-long-duration-part3-3
openshift-openshift-tests-private-release-4.8__amd64-stable.yaml:- as: gcp-ipi-p3-f28-long-duration-part3-3
openshift-openshift-tests-private-release-4.13__arm64-nightly.yaml:- as: aws-ipi-p3-f28-long-duration-part1-3
openshift-openshift-tests-private-release-4.13__arm64-nightly.yaml:- as: aws-ipi-p3-f28-long-duration-part2-3
openshift-openshift-tests-private-release-4.13__arm64-nightly.yaml:- as: aws-ipi-p3-f28-long-duration-part3-3
openshift-openshift-tests-private-release-4.12__arm64-nightly.yaml:- as: aws-ipi-disconnected-private-tp-p3-f28-long-duration-cloud
openshift-openshift-tests-private-release-4.12__arm64-nightly.yaml:- as: aws-ipi-p3-f28-long-duration-part1-3
openshift-openshift-tests-private-release-4.12__arm64-nightly.yaml:- as: aws-ipi-p3-f28-long-duration-part2-3
openshift-openshift-tests-private-release-4.12__arm64-nightly.yaml:- as: aws-ipi-p3-f28-long-duration-part3-3
openshift-openshift-tests-private-release-4.12__arm64-nightly.yaml:- as: azure-ipi-p3-f28-long-duration-part3-3
openshift-openshift-tests-private-release-4.11__arm64-nightly.yaml:- as: aws-ipi-p3-f28-long-duration-part1-3
openshift-openshift-tests-private-release-4.11__arm64-nightly.yaml:- as: aws-ipi-p3-f28-long-duration-part2-3
openshift-openshift-tests-private-release-4.11__arm64-nightly.yaml:- as: aws-ipi-p3-f28-long-duration-part3-3
openshift-openshift-tests-private-release-4.11__arm64-stable.yaml:- as: aws-ipi-p3-f28-long-duration-part1-3
openshift-openshift-tests-private-release-4.11__arm64-stable.yaml:- as: aws-ipi-p3-f28-long-duration-part2-3
openshift-openshift-tests-private-release-4.11__arm64-stable.yaml:- as: aws-ipi-p3-f28-long-duration-part3-3
openshift-openshift-tests-private-release-4.10__arm64-stable.yaml:- as: aws-ipi-p3-f28-long-duration-part1-3
openshift-openshift-tests-private-release-4.10__arm64-stable.yaml:- as: aws-ipi-p3-f28-long-duration-part2-3
openshift-openshift-tests-private-release-4.10__arm64-stable.yaml:- as: aws-ipi-p3-f28-long-duration-part3-3
```

**Comment by sunzhaohua2** [comment]
> @sunzhaohua2 seem like there are some remaining long-duration test jobs, can you help have a double check:

@jianlinliu The jobs without the suffix `-cloud` are not cloud team's, do we need to confirm with other teams?

**Comment by jianlinliu** [comment]
> long-duratio

@liangxia can you still remember which team submited the long-duration test jobs?

**Comment by liangxia** [comment]
> @liangxia can you still remember which team submited the long-duration test jobs?

`*-long-duration-cloud` are added by cloud team, the others `*-long-duration-partx-y` are added by ginkgo tests.

**Comment by jianlinliu** [comment]
> the others *-long-duration-partx-y are added by ginkgo tests.

Who should we confirm with? @kuiwang02 ?

**Comment by kuiwang02** [comment]
> > the others *-long-duration-partx-y are added by ginkgo tests.
> 
> Who should we confirm with? @kuiwang02 ?

here is the history:
when release-4.12 start, there is no longduration test in prow ci (or we can see longduration test is not ran on prow ci).
so, @chengzhang1016 create https://issues.redhat.com/browse/OCPQE-11828 for me and let me research it so that team can create longduration test in prow ci.
And then I created the first three tests
aws-ipi-p3-f28-long-duration-part1-3
aws-ipi-p3-f28-long-duration-part2-3
aws-ipi-p3-f28-long-duration-part3-3
as starting point on amd64-nightly on release-4.12 only.

For other longduration test, should be other team to make them (some are new added, and some are copy& pasted when add new build or arch yaml file). and I do not add longduration anymore after those three tests.
It means such longduration on arm64 or other build, or other releases are not added by me, and frankly I do not know how to decided which arch, build and release need them.

I also do not know who decide it. what I did is to enable such test as pilot.

@jianlinliu @chengzhang1016

**Comment by jianlinliu** [comment]
@jianping-shu seem like you added `azure-ipi-p3-f28-long-duration-part3-3` and `gcp-ipi-p3-f28-long-duration-part3-3` can you help confirm if it always needed to run in stable/arm testing?

**Comment by jianlinliu** [comment]
> @jianlinliu The following 3 are for Hive test cases. azure-ipi-p3-f28-long-duration-part3-3 gcp-ipi-p3-f28-long-duration-part3-3 aws-ipi-p3-f28-long-duration-part3-3 They are NOT needed for arm because Hive operator only supports to be installed on amd cluster, so the Hive case are skipped actually in these arm runs. They could be optional for stable testing in my mind. Personally I think nightly and at least 1 run in 1 month is ok for Hive.

Good to know, do you mind to file anther PR to remove those unnecessary test jobs.

**Comment by jianping-shu** [comment]
> 
> Good to know, do you mind to file anther PR to remove those unnecessary test jobs.

Sure. I'll do it.

**Comment by jianlinliu** [comment]
@liangxia I think we can approve this PR now, for other long duration test jobs, we can update them in other PRs.

**Comment by liangxia** [comment]
Automatic merge failed; fix conflicts and then commit the result.

**Pull request merged**
