### PR TITLE
feat: rhtap: add 'report' post-step

### PR DESCRIPTION
**Pull request by psturc**
https://issues.redhat.com/browse/RHTAP-1852

### CODE REVIEW

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e

**Review by jkopriva — APPROVED** [review]

**Pull request merged**
