### PR TITLE
Use downstream compatible test cases using Tempo operator repo commit

### PR DESCRIPTION
**Pull request by IshwarKanse**
Resolves https://issues.redhat.com/browse/TRACING-3433

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.14-lp-interop-tempo-interop-aws periodic-ci-openshift-grafana-tempo-operator-main-ocp4.13-amd64-upgrade-tempo-operator-upgrade

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-ocp4.13-amd64-upgrade-tempo-operator-upgrade

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-ocp4.13-amd64-upgrade-tempo-operator-upgrade

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-ocp4.13-amd64-upgrade-tempo-operator-upgrade

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-ocp4.13-amd64-upgrade-tempo-operator-upgrade

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-ocp4.13-amd64-upgrade-tempo-operator-upgrade periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.14-lp-interop-tempo-interop-aws

**Comment by IshwarKanse** [comment]
The job failed on a step managed by interop team.We can ignore it. I'll reach out to the interop team to look into it.

**Review by frzifus — APPROVED** [review]

**Pull request merged**
