### PR TITLE
run e2e-aws-jenkins if openshift/origin files specific to it alone are changed

### PR DESCRIPTION
**Pull request by gabemontero**
See https://github.com/openshift/origin/pull/26268 and the PRs it references for all the tl;dr

### CODE REVIEW

**Comment by gabemontero** [comment]
@akram @waveywaves @jkhelil @adambkaplan FYI

**Comment by gabemontero** [comment]
@adambkaplan you may want to lobby to be added as an approver to https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/origin/OWNERS for changes like this

**Comment by yselkowitz** [comment]
Would the same be needed/wanted for the stable branches?

**Comment by gabemontero** [comment]
> Would the same be needed/wanted for the stable branches?

yep https://github.com/openshift/release/pull/19747

**Pull request merged**
