### PR TITLE
Add CI for published SDN repo

### PR DESCRIPTION
**Pull request by tnozicka**
/cc @deads2k @sttts

### CODE REVIEW

**Comment by tnozicka** [comment]
reherse jobs are expected to fail as published repose don't have vendor folder

**Comment by stevekuznetsov** [comment]
> reherse jobs are expected to fail as published repose don't have vendor folder

So is there a PR to the SDN repo to add one? Or are we enabling blocking jobs on the repo that are not going to succeed?

**Comment by tnozicka** [comment]
The repo is only published by a bot from origin/staging, no PRs are merged there. There is an PR (https://github.com/openshift/sdn/pull/1) that restores vendor folder and that needs to pass the whole suite before we can transfer from staging to its own repo. We want to be sure the CI is setup correctly before we do the move.

**Pull request merged**
