### PR TITLE
[PERFSCALE-2804] Bump PODS_PER_NODE

### PR DESCRIPTION
**Pull request by krishvoor**
This PR bumps the PODS_PER_NODE for:

1) PODS_PER_NODE=200 per [node-density-cni](https://docs.google.com/document/d/1CTJJQoutSSd039WrVTx0qzmHwRcBWHZFeWbHz0bhIPw/edit#heading=h.pehkwj2ue8zk) value
2) PODS_PER_NODE=200 per [node-density-heavy](https://docs.google.com/document/d/1CTJJQoutSSd039WrVTx0qzmHwRcBWHZFeWbHz0bhIPw/edit#heading=h.h7phuxmpdqh) value

### CODE REVIEW

**Review by venkataanil — APPROVED** [review]

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-node-density-heavy-24nodes periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-node-density-heavy-24nodes periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-node-density-cni-24nodes pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-node-density-cni-3nodes

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-node-density-heavy-24nodes periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-node-density-cni-24nodes

**Review by chentex — APPROVED** [review]
/lgtm

**Pull request merged**
