### PR TITLE
Add EXTRACT_MANIFEST_INCLUDED to nutanix jobs

### PR DESCRIPTION
**Pull request by sgaoshang**
Add missed EXTRACT_MANIFEST_INCLUDED, back to openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml where it is imported.

### CODE REVIEW

**Comment by sgaoshang** [comment]
@jianlinliu pls help to review it, thanks.

**Comment by jianlinliu** [comment]
cc @liangxia to review

**Comment by jianlinliu** [comment]
cc @liangxia to review.

**Pull request merged**
