### PR TITLE
HCO: bump version to 1.11.0

### PR DESCRIPTION
**Pull request by nunnatsa**

### CODE REVIEW

**Comment by nunnatsa** [comment]
Waiting for https://github.com/kubevirt/hyperconverged-cluster-operator/pull/2453

**Comment by nunnatsa** [comment]
kubevirt/hyperconverged-cluster-operator#2453 merged

/pj-rehearse max

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-gcp pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-operator-sdk-aws pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-operator-sdk-gcp pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-operator-sdk-gcp

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-operator-sdk-aws

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-prev-operator-sdk-azure pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-azure pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-sno-aws pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-prev-operator-sdk-sno-azure pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-operator-sdk-aws pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-sno-azure pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-upgrade-operator-sdk-gcp pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-operator-sdk-gcp pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-upgrade-operator-sdk-aws

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-operator-sdk-aws pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-prev-operator-sdk-azure

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
