### PR TITLE
Add kernel packer PR tests

### PR DESCRIPTION
**Pull request by Molter73**
This PR refactors how the kernel crawling for stackrox works. By moving all required steps into `ref`s and creating a single `workflow`, we now have periodic and presubmit crawling in just a few lines of configuration.

### CODE REVIEW

**Review by porridge — APPROVED** [review]
/lgtm

**Comment by erthalion** [comment]
> ci/rehearse/periodic-ci-stackrox-kernel-packer-master-kernel-crawling-periodic — Job failed

To fix this one we could change back the instance type we spin up to e2 (it was introduced as part of trying to make crawling/repackaging faster, but in the view of caching is not needed anymore).

**Comment by Molter73** [comment]
Thanks @erthalion, I'll do that now!

**Pull request merged**
