### PR TITLE
update boot image for ash

### PR DESCRIPTION
**Pull request by jinyunma**
In installation doc of [ipi on ash](https://docs.openshift.com/container-platform/4.12/installing/installing_azure_stack_hub/installing-azure-stack-hub-default.html#installation-azure-user-infra-uploading-rhcos_installing-azure-stack-hub-default) and [upi on ash](https://docs.openshift.com/container-platform/4.12/installing/installing_azure_stack_hub/installing-azure-stack-hub-user-infra.html#installation-azure-user-infra-uploading-rhcos_installing-azure-stack-hub-user-infra), boot image is always obtained from `openshift-install coreos print-stream-json` and upload to ash environment for later usage.

To align with the official doc, 
1. In IPI, change the step `ipi-conf-osimage-azure` to step `ipi-conf-azurestack-rhcos`, always use the matched boot image.
2.  In UPI, add step `ipi-conf-azurestack-rhcos`  in relevant installation chains.

### CODE REVIEW

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.13-installer-rehearse-azure-stack

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.12-installer-rehearse-azure-stack

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.12-installer-rehearse-azure-stack

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.12-installer-rehearse-azure-stack

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-azurestack-ovn-upi

**Comment by jinyunma** [comment]
cc @gpei @jianlinliu @MayXuQQ for review

IPI passed job: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/39083/rehearse-39083-periodic-ci-openshift-verification-tests-master-installer-rehearse-4.13-installer-rehearse-azure-stack/1654661052773699584

**Comment by jianlinliu** [comment]
@rna-afk do you mind help review this?

**Comment by jianlinliu** [comment]
cc @liangxia to review

**Pull request merged**
