### PR TITLE
[rosacli][ocp] add security group jobs for ROSA HCP

### PR DESCRIPTION
**Pull request by yasun1**
[OCPQE-20727](https://issues.redhat.com/browse/OCPQE-20727)

### CODE REVIEW

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-master-rosacli-aws-rosa-hcp-security-group-e2e-f7 periodic-ci-openshift-openshift-tests-private-master-rosacli-aws-rosa-hcp-security-group-private-e2e-f7

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-master-rosacli-aws-rosa-hcp-security-group-e2e-f7 periodic-ci-openshift-openshift-tests-private-master-rosacli-aws-rosa-hcp-security-group-private-e2e-f7

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-master-rosacli-aws-rosa-hcp-security-group-e2e-f7 periodic-ci-openshift-openshift-tests-private-master-rosacli-aws-rosa-hcp-security-group-private-e2e-f7

**Review by radtriste — APPROVED** [review]

**Comment by yasun1** [comment]
@liangxia Could you help review the PR? Thanks.

**Pull request merged**
