### PR TITLE
test(SRVKP-4182): Regression Testing OpenShift Pipelines v1.13 and v1.14

### PR DESCRIPTION
**Pull request by rh-rahulshetty**
Run performance regression tests on v1.13 and v1.14 OpenShift Pipelines. 

- [x] [SRVKP-4189](https://issues.redhat.com/browse/SRVKP-4189): Testing increasing concurreny for math scenario (60/70/80/90/100) for 1000 runs on OpenShift Pipelines v1.13
- [x] [SRVKP-4190](https://issues.redhat.com/browse/SRVKP-4190): Testing increasing concurreny for math scenario (60/70/80/90/100) for 1000 runs on OpenShift Pipelines v1.14
- [x] [SRVKP-4191](https://issues.redhat.com/browse/SRVKP-4191): Testing increasing concurreny for math scenario (50/100/150/200) for 1000 runs on OpenShift Pipelines v1.13 with HA=10 setup
- [x] [SRVKP-4192](https://issues.redhat.com/browse/SRVKP-4192): Testing increasing concurreny for math scenario (50/100/150/200) for 1000 runs on OpenShift Pipelines v1.14 with HA=10 setup
- [x] [SRVKP-4194](https://issues.redhat.com/browse/SRVKP-4194): Test OpenShift Pipeline v1.13 Chains with bigbang scenario concurrency=100 and total runs=2500/5000/7500/10000
- [x] [SRVKP-4195](https://issues.redhat.com/browse/SRVKP-4195): Test OpenShift Pipeline v1.14 Chains with bigbang scenario concurrency=100 and total runs=2500/5000/7500/10000
- [x] [SRVKP-4196](https://issues.redhat.com/browse/SRVKP-4196): Test OpenShift Pipeline v1.13 Chains with bigbang scenario concurrency=100 and total runs=2500/5000/7500/10000 with HA=10 setup
- [x] [SRVKP-4197](https://issues.redhat.com/browse/SRVKP-4197): Test OpenShift Pipeline v1.14 Chains with bigbang scenario concurrency=100 and total runs=2500/5000/7500/10000 with HA=10 setup

### CODE REVIEW

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-1000-x-math

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-1000-x-math

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-sign-tekton-bigbang

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-1000-x-math

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-1000-x-math-ha-10

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-1000-x-math-ha-10

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-sign-tekton-bigbang

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-sign-tekton-bigbang

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-1000-x-math

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-1000-x-math-ha-10

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-1000-x-math-ha-10

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-sign-tekton-bigbang
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-sign-tekton-bigbang

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-sign-tekton-bigbang

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-sign-tekton-bigbang

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-5000-sign-tekton-bigbang pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-7500-sign-tekton-bigbang pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-10000-sign-tekton-bigbang

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-sign-tekton-bigbang

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-sign-tekton-bigbang pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-7500-sign-tekton-bigbang pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-10000-sign-tekton-bigbang

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-7500-sign-tekton-bigbang pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-10000-sign-tekton-bigbang

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-2500-sign-tekton-bigbang-ha pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-5000-sign-tekton-bigbang-ha pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-7500-sign-tekton-bigbang-ha pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-10000-sign-tekton-bigbang-ha

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-10000-sign-tekton-bigbang pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-2500-sign-tekton-bigbang-ha pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-sign-tekton-bigbang-ha pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-7500-sign-tekton-bigbang-ha pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-10000-sign-tekton-bigbang-ha

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-2500-sign-tekton-bigbang-ha

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-2500-sign-tekton-bigbang-ha

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-10000-sign-tekton-bigbang  pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-sign-tekton-bigbang-ha

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-10000-sign-tekton-bigbang pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-2500-sign-tekton-bigbang-ha pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-sign-tekton-bigbang-ha pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-7500-sign-tekton-bigbang-ha pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-10000-sign-tekton-bigbang-ha

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-10000-sign-tekton-bigbang

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-2500-sign-tekton-bigbang pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-2500-sign-tekton-bigbang

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-5000-sign-tekton-bigbang

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-2500-sign-tekton-bigbang pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-5000-sign-tekton-bigbang pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-2500-sign-tekton-bigbang pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-sign-tekton-bigbang

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-2500-sign-tekton-bigbang pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-5000-sign-tekton-bigbang pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-2500-sign-tekton-bigbang pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-sign-tekton-bigbang

**Review by jhutar — APPROVED** [review]
/lgtm

**Review by khrm — COMMENTED** [review]
Are we not benchmarking performance tuning parameter scenario? @jhutar

**Comment by jhutar** [comment]
Hello @khrm :wave: Yes, Pipelines perf tuning is SRVKP-4366. This PR was for 1.13 vs. 1.14 testing in SRVKP-4182. Hope that answers the question :)

**Comment by khrm** [comment]
Yes. Thanks.

**Pull request merged**
