### PR TITLE
CMO: add jsonnet-fmt and rules jobs

### PR DESCRIPTION
**Pull request by jan--f**
These new jobs check formatting of jsonnet and test prometheus rules for
PRs.

Signed-off-by: Jan Fajerski <jfajersk@redhat.com>

### CODE REVIEW

**Comment by jan--f** [comment]
The failing test will be fixed by https://github.com/openshift/cluster-monitoring-operator/pull/1129

**Review by paulfantom — APPROVED** [review]
/lgtm

**Pull request merged**
