### PR TITLE
add platform none and vsphere multi-zone to clusterbot allowed workflows

### PR DESCRIPTION
**Pull request by rvanderp3**
add vsphere platform none support for winc and vsphere multi-zone to clusterbot allowed workflows

### CODE REVIEW

**Comment by rvanderp3** [comment]
cc @bostrt

**Review by bradmwilliams — APPROVED** [review]

**Comment by bostrt** [comment]
I'm not sure how to test clusterbot changes but this /lgtm based on other similar PR's that have merged successfully.

**Pull request merged**
