### PR TITLE
WINC-634: wmco: add community-4.8 jobs

### PR DESCRIPTION
**Pull request by aravindhp**
Add community-4.8 jobs so that we can test WMCO on OKD 4.8

### CODE REVIEW

**Comment by sebsoto** [comment]
/approve
Assuming the required `.ci-operator.yaml` change in the WMCO is next

**Comment by aravindhp** [comment]
> /approve
> Assuming the required `.ci-operator.yaml` change in the WMCO is next

As discussed over Slack no `.ci-operator.yaml` changes are needed.

The rehearsals will fail as https://github.com/openshift/windows-machine-config-operator/pull/509 needs to get merged. Given that the rehearsals are failing as expected, I prefer getting this merged first and have the e2es run on https://github.com/openshift/windows-machine-config-operator/pull/509 before it merges.

**Review by stevekuznetsov — APPROVED** [review]

**Pull request merged**
