### PR TITLE
openshift/oadp-operator:oadp-1.0: Use golang 1.19 for test/e2e

### PR DESCRIPTION
**Pull request by kaovilai**
unblocks https://github.com/openshift/oadp-operator/pull/954

Signed-off-by: Tiger Kaovilai <tkaovila@redhat.com>

### CODE REVIEW

**Review by shubham-pampattiwar — APPROVED** [review]

**Comment by kaovilai** [comment]
rip 
```
INFO[2023-04-12T22:27:50Z] /bin/bash: line 2: make: command not found
```

**Comment by kaovilai** [comment]
going back to https://github.com/openshift/release/commit/ca6f60e9b132a863b71c9ce7d2f6b46256217de9

**Review by weshayutin — APPROVED** [review]

**Review by rayfordj — APPROVED** [review]
/lgtm

**Comment by kaovilai** [comment]
Blocked by https://github.com/openshift/oadp-operator/pull/963

**Review by sseago — APPROVED** [review]

**Comment by kaovilai** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-oadp-1.0-4.8-operator-e2e

**Comment by kaovilai** [comment]
E2e is running now. Errors are to be fixed in the operator repo later.

**Review by rayfordj — APPROVED** [review]
/lgtm

**Pull request merged**
