### PR TITLE
OCPBUGS-36363: Install yq manually if not found in installer image

### PR DESCRIPTION
**Pull request by Shilpa-Gokul**
Added code to install yq manually until yq-v4 package is backported to the 4.14 installer code.

### CODE REVIEW

**Comment by Shilpa-Gokul** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-ovn-ppc64le-powervs

**Comment by Shilpa-Gokul** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.15-ocp-e2e-ovn-ppc64le-powervs-original

**Comment by Shilpa-Gokul** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-ovn-ppc64le-powervs

**Comment by Shilpa-Gokul** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-ovn-ppc64le-powervs

**Comment by Shilpa-Gokul** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-ovn-ppc64le-powervs

**Comment by Shilpa-Gokul** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-ovn-ppc64le-powervs

**Comment by Shilpa-Gokul** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-ovn-ppc64le-powervs

**Comment by Shilpa-Gokul** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-ovn-ppc64le-powervs

**Comment by Shilpa-Gokul** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-ovn-ppc64le-powervs

**Comment by Shilpa-Gokul** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-ovn-ppc64le-powervs

**Comment by Shilpa-Gokul** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-ovn-ppc64le-powervs

**Comment by Shilpa-Gokul** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-ovn-ppc64le-powervs

**Comment by Shilpa-Gokul** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-ovn-ppc64le-powervs

**Review by r4f4 — COMMENTED** [review]
/approve

**Pull request merged**
