### PR TITLE
Adding updated list of openshift-docs branches to run against the portal build step

### PR DESCRIPTION
**Pull request by aireilly**
Adding updated list of openshift-docs branches to run against the portal build step

### CODE REVIEW

**Review by gabriel-rh — APPROVED** [review]
LGTM

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-enterprise-4.11-validate-asciidoc

**Review by gabriel-rh — APPROVED** [review]
LGTM

**Review by gabriel-rh — APPROVED** [review]
LGTM

**Pull request merged**
