### PR TITLE
Update 4.2 repo file to use 4.2 mirrors

### PR DESCRIPTION
**Pull request by timlnx**
In response to https://jira.coreos.com/browse/ART-795 "4.2 repos not synced to mirror.openshift.com"

### CODE REVIEW

**Comment by tbielawa** [comment]
/hold
still need to actually mirror the content. will break stuff if merged too soon :)

**Comment by stevekuznetsov** [comment]
/lgtm
/approve

@tbielawa you could add yourself to the OWNERS on those directories as well so you can self-approve since you're the expert on this one

**Pull request merged**
