### PR TITLE
Add storage QE in cherry-pick-approved list

### PR DESCRIPTION
**Pull request by duanwei33**
Hello, could you add storage QE in cherry-pick-approved list as there are some storage bug need to be fixed in this repo, thanks.
cc @jsafrane

### CODE REVIEW

**Comment by duanwei33** [comment]
@sttts Hi, I'm not sure if you're the right person to allow me(storage QE) into cherry-pick-approved list, we have some PR need to be added cherry-pick-approved, thanks in advance.

**Comment by jsafrane** [comment]
lgtm from storage team. @duanwei33 is the right storage QA person.

**Pull request merged**
