### PR TITLE
test 4.15 120 node upgrade

### PR DESCRIPTION
**Pull request by venkataanil**
Please don't review or merge this PR. This PR is to debug failures during migration.
PR https://github.com/openshift/release/pull/48101 has the relevant changes to suport 120 node migration

### CODE REVIEW

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-loaded-upgrade-from-4.14-perfscale-aws-120nodes-loaded-upgrade-414to415

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-loaded-upgrade-from-4.14-perfscale-aws-120nodes-loaded-upgrade-414to415

**Comment by venkataanil** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-loaded-upgrade-from-4.14-perfscale-aws-120nodes-loaded-upgrade-414to415

**Pull request closed without merging**
