### PR TITLE
unprotect jenkins plugin repos

### PR DESCRIPTION
**Pull request by bparees**
we have a need to directly push commits into the master branch to maintain sync w/ upstream jenkins plugin processes.

### CODE REVIEW

**Comment by bparees** [comment]
@gabemontero fyi

**Comment by gabemontero** [comment]
Ultimately, the plugins do not show up in our image until we update https://github.com/openshift/jenkins

**Comment by bparees** [comment]
/assign @stevekuznetsov 

no idea if this format is correct.  where's the doc for this file?

**Comment by bparees** [comment]
@coverprice can you pick someone from your team to review this?  in particular i'm not sure about the syntax for adding specific teams that should be allowed to push direct to master.

**Comment by petr-muller** [comment]
Reading https://github.com/kubernetes/test-infra/tree/master/prow/cmd/branchprotector, this PR looks correct to me.

/lgtm
/approve

**Pull request merged**
