### PR TITLE
Loki: update to 2.2.1

### PR DESCRIPTION
**Pull request by vrutkovs**
Latest stable version should have all pack/unpack fixes

### CODE REVIEW

**Comment by vrutkovs** [comment]
/hold

to check rehearsals

**Comment by vrutkovs** [comment]
/hold cancel

Works as expected in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/17740/rehearse-17740-pull-ci-operator-framework-operator-lifecycle-manager-release-4.7-e2e-upgrade/1382332539712049152

**Review by periklis — APPROVED** [review]
/lgtm

**Pull request merged**
