### PR TITLE
azure: Fix UPI for older release tests

### PR DESCRIPTION
**Pull request by rna-afk**
The older release tests seem to not have yaml installed and is
failing. Installing pyyaml should do the trick.

### CODE REVIEW

**Comment by staebler** [comment]
@rna-afk Can you temporarily add the commit from https://github.com/openshift/release/pull/20840 to convince the rehearsal job to run against the earlier OpenShift versions?

**Comment by rna-afk** [comment]
The tests are producing the usual errors now after two fixes. Removing the temporary commit.

**Comment by LorbusChris** [comment]
@rna-afk thanks for taking this on. Mind adding a note in the commit message about the second fix (`.azure.url`)?

**Review by LorbusChris — APPROVED** [review]

**Pull request merged**
