### PR TITLE
Serverless: migrate nightly jobs from OCP 4.12 to 4.13

### PR DESCRIPTION
**Pull request by mgencur**
Also add slack notification to single-node openshift periodic job

### CODE REVIEW

**Comment by mgencur** [comment]
/pj-rehearse pull-ci-openshift-knative-serverless-operator-main-4.13-operator-e2e-aws-ocp-413

**Comment by cardil** [comment]
/hold

for my PR, that fixes the SO UI tests on 4.12

**Comment by mgencur** [comment]
/pj-rehearse pull-ci-openshift-knative-serverless-operator-main-4.13-operator-e2e-aws-ocp-413

**Comment by cardil** [comment]
/unhold

the change for UI tests for 4.12 is now merged

**Comment by mgencur** [comment]
/pj-rehearse pull-ci-openshift-knative-serverless-operator-main-4.13-operator-e2e-aws-ocp-413

**Review by cardil — APPROVED** [review]
/lgtm

**Pull request merged**
