### PR TITLE
OCPEDGE-924: feat: added dynamic seed versioning

### PR DESCRIPTION
**Pull request by jeff-roche**

### CODE REVIEW

**Comment by jeff-roche** [comment]
/pj-rehearse pull-ci-openshift-kni-lifecycle-agent-main-ibu-e2e-flow

**Comment by jeff-roche** [comment]
/pj-rehearse pull-ci-openshift-kni-lifecycle-agent-main-ibu-e2e-flow

**Comment by jeff-roche** [comment]
/pj-rehearse pull-ci-openshift-kni-lifecycle-agent-main-ibu-e2e-flow

**Comment by jeff-roche** [comment]
/pj-rehearse ci/rehearse/periodic-ci-openshift-kni-lifecycle-agent-main-periodics-seedgen-aws-ocp-4-15

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-kni-lifecycle-agent-main-periodics-seedgen-aws-ocp-4-15

**Comment by jeff-roche** [comment]
/pj-rehearse pull-ci-openshift-kni-lifecycle-agent-main-ibu-e2e-flow periodic-ci-openshift-kni-lifecycle-agent-main-periodics-seedgen-aws-ocp-4-15 periodic-ci-openshift-kni-lifecycle-agent-main-periodics-seedgen-aws-ocp-4-16

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-kni-lifecycle-agent-main-periodics-seedgen-aws-ocp-4-15

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-kni-lifecycle-agent-main-periodics-seedgen-aws-ocp-4-15

**Comment by jeff-roche** [comment]
/pj-rehearse ci/rehearse/openshift-kni/lifecycle-agent/main/ibu-e2e-flow

**Comment by jeff-roche** [comment]
/pj-rehearse pull-ci-openshift-kni-lifecycle-agent-main-ibu-e2e-flow

**Comment by jeff-roche** [comment]
/pj-rehearse pull-ci-openshift-kni-lifecycle-agent-release-4.15-ibu-e2e-flow

**Comment by jeff-roche** [comment]
/pj-rehearse pull-ci-openshift-kni-lifecycle-agent-main-ibu-e2e-flow

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-kni-lifecycle-agent-main-periodics-seedgen-aws-ocp-4-16

**Comment by jeff-roche** [comment]
/pj-rehearse pull-ci-openshift-kni-lifecycle-agent-main-ibu-e2e-flow

**Comment by jeff-roche** [comment]
/pj-rehearse pull-ci-openshift-kni-lifecycle-agent-main-ibu-e2e-flow

**Review by javipolo — APPROVED** [review]

**Review by javipolo — APPROVED** [review]

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-kni-lifecycle-agent-main-periodics-seedgen-aws-ocp-4-16

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-kni-lifecycle-agent-main-periodics-seedgen-aws-ocp-4-16

**Review by donpenney — APPROVED** [review]

**Pull request merged**
