### PR TITLE
Add release-0.0.2 jobs for nvidia gpu plugin

### PR DESCRIPTION
**Pull request by rawagner**

### CODE REVIEW

**Comment by mkowalski** [comment]
/uncc

Not sure why I'm here

**Comment by rawagner** [comment]
> /uncc
> 
> Not sure why I'm here

openshift-ci bot suggests you https://github.com/openshift/release/pull/32082#issuecomment-1240291744

**Review by fabiendupont — APPROVED** [review]
/lgtm

**Review by droslean — APPROVED** [review]

**Pull request merged**
