### PR TITLE
support hw_version 21 on vsphere 8

### PR DESCRIPTION
**Pull request by WenXinWei**

### CODE REVIEW

**Comment by jcpowermac** [comment]
/hold

not all vsphere 8 environments are on update 2

**Comment by WenXinWei** [comment]
@jcpowermac  how about add a line to judge the minor version? 8.0.2 and later version, the hw_versions contains 21.

**Comment by WenXinWei** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.14-e2e-vsphere-upi

**Comment by WenXinWei** [comment]
installation was pass. please help review this pr. @jcpowermac

**Pull request merged**
