### PR TITLE
Set up peribolos on opendatahub-io

### PR DESCRIPTION
**Pull request by harshad16**

### CODE REVIEW

**Comment by harshad16** [comment]
/pj-rehearse pull-ci-opendatahub-io-org-management-main-unit-tests

**Comment by bbguimaraes** [comment]
Can you describe what the motive is for this job?  `peribolos` (and repository configuration in general) is managed by DPP — see the existing job in [`infra-periodics`](https://github.com/openshift/release/blob/780902667b38ab762fe19a46076d744f057f9feb/ci-operator/jobs/infra-periodics.yaml#L1370).

/hold

**Comment by harshad16** [comment]
> Can you describe what the motive is for this job? `peribolos` (and repository configuration in general) is managed by DPP — see the existing job in [`infra-periodics`](https://github.com/openshift/release/blob/780902667b38ab762fe19a46076d744f057f9feb/ci-operator/jobs/infra-periodics.yaml#L1370).

ack, i was just trying to understand , if other project could utilize peribolos from openshift-ci
this was just testing pr.
thanks closing this.

**Pull request closed without merging**
