### PR TITLE
ci: update the profile for rosa-day1-negative-f7

### PR DESCRIPTION
**Pull request by yuwang-RH**
Some case in rosa-day1-negative-f7 failed as the account has no billing account.
It will be fixed by updating using the aws-sd-qe cluster profile.

### CODE REVIEW

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-day1-negative-f7

**Comment by yuwang-RH** [comment]
@xueli181114 Could you help review this PR?

**Comment by yuwang-RH** [comment]
@ciaranRoche Could you help review and approve it?Thanks.

**Review by ciaranRoche — APPROVED** [review]
/lgtm

**Pull request merged**
