### PR TITLE
[IBMCloud] fix fail to create bastion with 10.1.0 is plugin

### PR DESCRIPTION
**Pull request by MayXuQQ**
fix using plugin vpc-infrastructure[infrastructure-service/is] to 10.1.0 , fail to create the bastion host floating IP.

### CODE REVIEW

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.16-installer-rehearse-ibmcloud

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.16-installer-rehearse-ibmcloud

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.16-installer-rehearse-ibmcloud

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.16-installer-rehearse-ibmcloud

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.16-installer-rehearse-ibmcloud

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.16-installer-rehearse-ibmcloud

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.15-installer-rehearse-ibmcloud

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.15-installer-rehearse-ibmcloud

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.15-installer-rehearse-ibmcloud

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.16-installer-rehearse-ibmcloud

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.16-installer-rehearse-ibmcloud

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.16-installer-rehearse-ibmcloud

**Comment by jianlinliu** [comment]
> on the flexy template, floating-ip-reserve failed, no such issue on Prow CI

We only need to describe the prow issue, not mentioned any flexy template things.

Also pls squash multiple commits into one.

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-stable-ibmcloud-ipi-private-fips-f14

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.15-installer-rehearse-ibmcloud

**Comment by MayXuQQ** [comment]
@jianlinliu How about merging this PR first, I will check the workers-rhel-scaleup step in another PR? thanks

**Pull request merged**
