### PR TITLE
[WIP] jaeger operator tests on ROSA hypershift

### PR DESCRIPTION
**Pull request by shakyav**

### CODE REVIEW

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by iblancasa** [comment]
cc @IshwarKanse

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj -rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.15-lp-interop-jaeger-interop-aws

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.15-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.15-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.15-lp-interop-jaeger-interop-aws

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.15-lp-interop-jaeger-interop-aws

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.15-lp-interop-jaeger-interop-aws

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.15-lp-interop-jaeger-interop-aws

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.15-lp-interop-jaeger-interop-aws

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.15-lp-interop-jaeger-interop-aws

**Comment by IshwarKanse** [comment]
@shakyav, has the pipeline image issue on the test cluster been resolved? I don’t see any PR changes. If unresolved, let’s close this PR and open a new one post-resolution to avoid unnecessary rehearsal costs.

**Comment by IshwarKanse** [comment]
@shakyav The rbac step did the trick. 1 test case flaked, all the others passed.

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj- rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.13-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.15-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
closing this , having some issue with rebase, creating a new PR - https://github.com/openshift/release/pull/49988

**Pull request closed without merging**
