### PR TITLE
WIP: Add a generator for creating testgrid config from ci-operator

### PR DESCRIPTION
**Pull request by smarterclayton**
This is just a sample and has not been extensively tested.

@stevekuznetsov

### CODE REVIEW

**Comment by petr-muller** [comment]
Would it make sense to teach prowgen to do this, so that the config would be kept up to date?

**Comment by stevekuznetsov** [comment]
The Python stuff in this repo was supposed to be ephemeral and a hold-over until we got the Go generator/validator in. If we want this generation to be long-lived and maintained I'd rather see it in Go.

**Comment by smarterclayton** [comment]
I'd say this generation is just enough to get us going until I see test grid running.  At that point, we are probably ready to move it into ci-operator-prowgen.

**Comment by stevekuznetsov** [comment]
Let's write Golang :)

**Comment by stevekuznetsov** [comment]
Data point -- the branching scripts are stale and if they had been in Go and used common methods to prowgen they would have been kept up to date.

**Comment by petr-muller** [comment]
/close 

Looks like we already have what we need.

**Pull request closed without merging**
