### PR TITLE
MON-3413: fix observability version in the bundle file

### PR DESCRIPTION
**Pull request by lihongyan1**
[MON-3413](https://issues.redhat.com/browse/MON-3413)
premerge prow job begin to failed after release 0.0.26

### CODE REVIEW

**Comment by lihongyan1** [comment]
/pj-rehearse pull-ci-rhobs-observability-operator-main-observability-operator-e2e

**Comment by lihongyan1** [comment]
/pj-rehearse pull-ci-rhobs-observability-operator-main-observability-operator-e2e

**Review by jan--f — APPROVED** [review]
/lgtm

**Pull request merged**
