### PR TITLE
WIP: OCPQE-18080: Install OCP to a shared VPC on GCP, with credentialsMode "Manual" and static credentials, along with nested virtualization and OS disk type & size testing

### PR DESCRIPTION
**Pull request by jianli-wei**
WIP

### CODE REVIEW

**Comment by jianli-wei** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.15-installer-rehearse-debug

**Comment by jianlinliu** [comment]
> Install OCP to a shared VPC on GCP, with credentialsMode "Manual" and static credentials, along with nested virtualization and OS disk type & size testing

If I remember right, we already have several jobs to cover "a shared VPC on GCP, with credentialsMode "Manual" and static credentials", "nested virtualization" and "OS disk type & size" separately, do we need to combine them together to cover them again?

**Comment by jianli-wei** [comment]
> > Install OCP to a shared VPC on GCP, with credentialsMode "Manual" and static credentials, along with nested virtualization and OS disk type & size testing
> 
> If I remember right, we already have several jobs to cover "a shared VPC on GCP, with credentialsMode "Manual" and static credentials", "nested virtualization" and "OS disk type & size" separately, do we need to combine them together to cover them again?

Yes, I'm thinking to combine the 3 into 1, because nested virtualization testing only needs N2 machine series and a bastion host, and OS disk type & size adds just a little bit to the install-config. Your suggestion? Thanks!

**Comment by jianlinliu** [comment]
> > If I remember right, we already have several jobs to cover "a shared VPC on GCP, with credentialsMode "Manual" and static credentials", "nested virtualization" and "OS disk type & size" separately, do we need to combine them together to cover them again?
> 
> Yes, I'm thinking to combine the 3 into 1, because nested virtualization testing only needs N2 machine series and a bastion host, and OS disk type & size adds just a little bit to the install-config. Your suggestion? Thanks!

I think `a shared VPC on GCP, with credentialsMode "Manual" and static credentials` is a bit far aways with the other two test points, if you want to do some combination, I suggest to only combine the latter two cases.

**Comment by jianli-wei** [comment]
> I think `a shared VPC on GCP, with credentialsMode "Manual" and static credentials` is a bit far aways with the other two test points, if you want to do some combination, I suggest to only combine the latter two cases.

Got it, let me do. Thanks!

**Pull request closed without merging**
