### PR TITLE
Move coredns IPI packet jobs to new equinix profile

### PR DESCRIPTION
**Pull request by derekhiggins**
The current packet account will soon be closed.

### CODE REVIEW

**Comment by derekhiggins** [comment]
@rfredette would you be able to take a look please, the old account it due to close tomorrow

**Comment by cybertron** [comment]
/test pj-rehearse

Although I guess all the jobs are going to start failing soon anyway if the old account goes away.

**Comment by cybertron** [comment]
/lgtm

Enough of the jobs passed to convince me the new infra is working.

**Pull request closed without merging**
