### PR TITLE
KMM: install from bundles in e2e-hub

### PR DESCRIPTION
**Pull request by qbarrand**
/cc @mresvanis @yevgeny-shnaidman @ybettan

### CODE REVIEW

**Comment by ybettan** [comment]
I am happy when CI is. Looks like you need to run `make jobs` and re-push.

We probably have changes in `ci/prow/e2e-hub-spoke-incluster-build` in KMM's repo?! If we do, could you please link the KMM's PR in this one?

**Comment by qbarrand** [comment]
/pj-rehearse pull-ci-rh-ecosystem-edge-kernel-module-management-main-e2e-hub

**Pull request merged**
