### PR TITLE
Creating data-path workflow

### PR DESCRIPTION
**Pull request by jtaleric**
Creating a test which will run data-path tests like k8s-netperf and ingress-perf

### CODE REVIEW

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-ocp-qe-perfscale-aws-ingress-perf-9nodes-periodic

**Review by krishvoor — APPROVED** [review]
/lgtm

**Pull request merged**
