### PR TITLE
Add configuration for Python 3.11 based notebooks

### PR DESCRIPTION
**Pull request by caponetto**
Depends on https://github.com/opendatahub-io/notebooks/pull/659

### CODE REVIEW

**Comment by jiridanek** [comment]
just a reminder that two PRs will be needed, one for opendatahub-io and another for red-hat-data-services, same as in 2024a

* https://github.com/openshift/release/pull/49709
* https://github.com/openshift/release/pull/49706

**Comment by jiridanek** [comment]
What's `pull-ci-openshift-release-master-build11-dry`? I dont remember seeing this before.

**Comment by jiridanek** [comment]
@caponetto looks good to me, tests failed because rocm image was not built, which is known issue; wdyt?

**Comment by caponetto** [comment]
> @caponetto looks good to me, tests failed because rocm image was not built, which is known issue; wdyt?

I agree. I thought the `*-e2e-tests` (anaconda, codeserver, habana) were supposed to pass since they don't have to do with rocm.

**Comment by jiridanek** [comment]
The images test always tries to build all images and if that fails, the dependent tests automatically fail. Harshad once mentioned it would be nice if we could improve this but tbh I don't understand openshift či enough to jump in and just do it.

**Pull request merged**
