### PR TITLE
OCPCLOUD-2484,OCPCLOUD-2481: Adds cloud-provider-{azure,gcp} rpms to artifacts

### PR DESCRIPTION
**Pull request by theobarberbany**
Pulls azure and gcp credential providers into o/k artifacts to prevent breaking OKD & scos composes.

### CODE REVIEW

**Comment by theobarberbany** [comment]
/pj-rehearse pull-ci-openshift-kubernetes-release-4.16-images

**Comment by theobarberbany** [comment]
/pj-rehearse pull-ci-openshift-kubernetes-release-4.16-images

**Comment by theobarberbany** [comment]
pull-ci-openshift-kubernetes-release-4.17-images

**Comment by theobarberbany** [comment]
/pj-rehearse pull-ci-openshift-kubernetes-release-4.17-images

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
