### PR TITLE
installer test coverage

### PR DESCRIPTION
**Pull request by jcpowermac**

### CODE REVIEW

**Comment by jcpowermac** [comment]
@patrickdillon coverage output:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/35986/rehearse-35986-pull-ci-openshift-installer-master-unit/1621237422840877056/artifacts/test/artifacts/

**Review by r4f4 — COMMENTED** [review]
/lgtm
Nice addition

**Pull request merged**
