### PR TITLE
Update the commands that are run for test and verify to reference the…

### PR DESCRIPTION
**Pull request by coreydaley**
… makefile

### CODE REVIEW

**Comment by coreydaley** [comment]
/assign @adambkaplan @gabemontero 
Could one of you please check this out and lgtm if it's ok?

**Comment by gabemontero** [comment]
the output from`make verify` at https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/26008/rehearse-26008-pull-ci-openshift-builder-master-verify/1489704509151121408/artifacts/test/build-log.txt looks odd to me @coreydaley 

WDYT?

**Comment by gabemontero** [comment]
unit test at https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/26008/rehearse-26008-pull-ci-openshift-builder-master-unit/1489704509084012544/artifacts/test/build-log.txt looks good however

**Comment by gabemontero** [comment]
> the output from`make verify` at https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/26008/rehearse-26008-pull-ci-openshift-builder-master-verify/1489704509151121408/artifacts/test/build-log.txt looks odd to me @coreydaley
> 
> WDYT?

I was expecting some sort of output besides an echo of the script called, but maybe that just means it ran clean?  What happens when you do it locally?

**Comment by coreydaley** [comment]
@gabemontero 
I modeled these changes after the way that openshift/csi-driver-shared-resource does it. Locally it just outputs the command that was run (the same as the shared-resource repo does).

**Comment by gabemontero** [comment]
> @gabemontero I modeled these changes after the way that openshift/csi-driver-shared-resource does it. Locally it just outputs the command that was run (the same as the shared-resource repo does).

gotcha ... so this is "expected"

/lgtm

**Pull request merged**
