### PR TITLE
Remove stackrox/collector PR and master checks

### PR DESCRIPTION
**Pull request by Molter73**
We are moving most of stackrox/collector checks to GHA, since we are nearing completion of the migration, this PR will be responsible for removing existing configuration.

### CODE REVIEW

**Comment by Stringy** [comment]
Does this currently contain just deletions of the features that we have so far ported to GHA? I was expecting a full deletion of the configuration

**Comment by Stringy** [comment]
Hang on, I'm an idiot and somehow missed the PR title, ignore me.

**Review by Stringy — APPROVED** [review]

**Comment by Molter73** [comment]
The push-drivers and support-packages job seems to be failing due to the CPaaS variant not being ready for running on PRs, I think we can ignore it and I'll take a closer look if it keeps failing after merge.

**Pull request merged**
