### PR TITLE
ovirt use secure connection

### PR DESCRIPTION
**Pull request by Gal-Zaidman**
This PR fixes a TODO that got lost on the port to workflows

### CODE REVIEW

**Review by janoszen — APPROVED** [review]

**Comment by Gal-Zaidman** [comment]
For this PR to really work we will need to backport:
https://github.com/openshift/cloud-credential-operator/pull/317
and
https://github.com/openshift/installer/pull/4809
to at least 4.6 :/

**Comment by Gal-Zaidman** [comment]
This is already implemented

**Pull request closed without merging**
