### PR TITLE
4.8 Feature Freeze

### PR DESCRIPTION
**Pull request by petr-muller**
- Require `bugzilla/valid-bug` for merges to master/main
- Exempt openshift/console and openshift-console-operator from the tightened criteria
- Exempt logging team repos from the tightened criteria
- Exempt operator-framework/operator-{registry,lifecycle-manager} and also exempt them from 4.8+ OCP world entirely (https://github.com/openshift/release/pull/17580 and [convo](https://coreos.slack.com/archives/CBN38N3MW/p1617978353379500))

### CODE REVIEW

**Comment by petr-muller** [comment]
Goddamit I always do `make ci-operator-config` instead.

**Review by jupierce — APPROVED** [review]

**Comment by petr-muller** [comment]
Added changes for taking out operator-framework repos (https://github.com/openshift/release/pull/17580)

**Review by jupierce — APPROVED** [review]

**Pull request merged**
