### PR TITLE
telco5g: Replace domain for a new AWS account

### PR DESCRIPTION
**Pull request by sshnaidm**
We set up a new AWS telco account with a new domain name, replace it in jobs.

### CODE REVIEW

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-master-e2e-aws-ci-tests

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-numaresources-operator-release-4.13-ci-install-e2e pull-ci-openshift-kni-mixed-cpu-node-plugin-main-ci-e2e pull-ci-openshift-kni-cluster-group-upgrades-operator-release-4.15-integration pull-ci-openshift-kni-lifecycle-agent-main-integration pull-ci-openshift-kni-cnf-features-deploy-release-4.15-e2e-aws-ci-tests pull-ci-redhat-cne-cloud-event-proxy-release-4.16-e2e-aws pull-ci-redhat-cne-hw-event-proxy-operator-main-e2e-aws

**Review by ffromani — APPROVED** [review]
NROP changes LGTM

**Comment by zeeke** [comment]
cnf-features-deploy LGTM

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.14-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-release-4.14-e2e-aws-ran-profile pull-ci-openshift-kni-mixed-cpu-node-plugin-main-ci-e2e pull-ci-redhat-cne-hw-event-proxy-operator-main-e2e-operator pull-ci-redhat-cne-hw-event-proxy-operator-main-e2e-aws

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-redhat-cne-cloud-event-proxy-release-4.16-e2e-aws periodic-ci-openshift-kni-numaresources-operator-main-ci-must-gather-e2e

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-cluster-group-upgrades-operator-main-integration pull-ci-openshift-kni-cluster-group-upgrades-operator-release-4.14-integration

**Review by jzding — APPROVED** [review]
/lgtm

**Pull request merged**
