### PR TITLE
PerfScale Self-Managed 4.15 AWS job

### PR DESCRIPTION
**Pull request by jtaleric**
Adding 4.15 4.15 self-managed control-plane jobs

JIRA [PERFSCALE-2545](https://issues.redhat.com//browse/PERFSCALE-2545)

### CODE REVIEW

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-perfscale-aws-control-plane-24nodes-periodic

**Comment by jtaleric** [comment]
I will add slack notifications after the rehearse job.

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-perfscale-aws-control-plane-24nodes-periodic

**Comment by krishvoor** [comment]
> I will add slack notifications after the rehearse job.

Overall lgtm, once the Slack notifications are in will approve this.

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-perfscale-aws-control-plane-24nodes-periodic

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-perfscale-aws-control-plane-24nodes-periodic

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-perfscale-aws-control-plane-24nodes-periodic

**Review by krishvoor — APPROVED** [review]
/lgtm

**Pull request merged**
