### PR TITLE
[CVP-3113] Add prow job configs for OCP v4.11 for OSD

### PR DESCRIPTION
**Pull request by sonam1412**

### CODE REVIEW

**Comment by smg247** [comment]
@sonam1412 you should add `reviewers` (they can match the `approvers`) to the OWNERS files for this repo (ex: https://github.com/openshift/release/blob/46daac332480953e0569c36de7a49c64645c1674/ci-operator/jobs/redhat-openshift-ecosystem/msp/OWNERS) so that blunderbuss can choose the correct people to request reviews from. Jakub and I are not the proper people to review this one.

/uncc smg247 jmguzik

**Comment by sonam1412** [comment]
OCP v4.11 GA release date has been postponed to Wed Aug 10th. Hence, putting the PR on hold

**Comment by sonam1412** [comment]
> @sonam1412 you should add `reviewers` (they can match the `approvers`) to the OWNERS files for this repo (ex: https://github.com/openshift/release/blob/46daac332480953e0569c36de7a49c64645c1674/ci-operator/jobs/redhat-openshift-ecosystem/msp/OWNERS) so that blunderbuss can choose the correct people to request reviews from. Jakub and I are not the proper people to review this one.
> 
> /uncc smg247 jmguzik

Thanks for the suggestion. I will add it a list of reviewers in it

**Comment by sonam1412** [comment]
cc: @samvarankashyap @nmars @asergienk PTAL

**Comment by asergienk** [comment]
lgtm

**Comment by samvarankashyap** [comment]
lgtm

**Pull request merged**
