### PR TITLE
[OCPCLOUD-1110] Add ccm step registry with FG apply job

### PR DESCRIPTION
**Pull request by Danil-Grigorev**
The step registry is used to host CI jobs relevant to CCCMO functionality. This will be the main location where all CI additions will be done, such as tests for migration or custom cluster installations which will run CCM pods during startup.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
I've given this a once over and while I don't fully understand how the CI registry steps work, this looks ok from what I can tell

**Review by JoelSpeed — COMMENTED** [review]
Looks fine to me, would definitely be a plus to get these tests in place so we can continune developing with our operator

/lgtm

**Review by elmiko — APPROVED** [review]
this makes sense to me, thanks Danil
/lgtm

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
