### PR TITLE
[HCO] test main branch as v1.10.0

### PR DESCRIPTION
**Pull request by tiraboschi**

### CODE REVIEW

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-images pull-ci-kubevirt-hyperconverged-cluster-operator-main-images

**Comment by tiraboschi** [comment]
/hold
we need https://github.com/openshift/release/pull/37183 first

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-image-index-aws pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-image-index-gcp pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-image-index-sno-azure pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-index-sno-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-gcp pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-image-index-aws pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-upgrade-index-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-image-index-gcp pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-image-index-sno-azure pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-image-index-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-image-index-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-image-index-gcp pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-azure pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-image-index-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-image-index-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-image-index-gcp pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-image-index-aws pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-azure

**Review by nunnatsa — APPROVED** [review]
/approve

**Comment by tiraboschi** [comment]
Green enough
/pj-rehearse ack

**Pull request merged**
