### PR TITLE
NO-ISSUE: Make agent compact job optional

### PR DESCRIPTION
**Pull request by adriengentil**
make agent compact jobs optional as they are currently flaky

### CODE REVIEW

**Review by CrystalChun — APPROVED** [review]
/lgtm

**Review by osherdp — APPROVED** [review]

**Comment by zaneb** [comment]
/hold
The agent installer is designed to always be in lockstep, with all images coming from the same release. Please just make the job (temporarily) optional if it is flaky.

**Comment by gamli75** [comment]
LGTM

**Review by gamli75 — APPROVED** [review]

**Pull request merged**
