### PR TITLE
CONSOLE-3303: nodejs-16 and nginx image mirroring for console plugin template

### PR DESCRIPTION
**Pull request by cajieh**

### CODE REVIEW

**Review by jhadvig — COMMENTED** [review]
@cyril-ui-developer have you test to build the image with the plugin-template?

**Comment by jhadvig** [comment]
/title nodejs-16 image mirroring for console plugin template

**Comment by jhadvig** [comment]
/retitle nodejs-16 and nginx image mirroring for console plugin template

**Comment by jhadvig** [comment]
@jupierce could you please review this one. Thanks!

**Comment by jhadvig** [comment]
/retitle CONSOLE-3303: nodejs-16 and nginx image mirroring for console plugin template

**Review by droslean — APPROVED** [review]

**Pull request merged**
