### PR TITLE
Make components use supplemental prow configs

### PR DESCRIPTION
**Pull request by alvaroaleman**
This PR changes all components to load supplemental prow config. It
doesn't make a difference yet, as there is none. I verified in crier
that this does not result in an error.

Needs https://github.com/openshift/ci-tools/pull/1890 to not break the configresolver

/hold

### CODE REVIEW

**Comment by bradmwilliams** [comment]
@alvaroaleman Is it safe to assume that all the various tools, except for the ci-chat-bot and release-controller, all had corresponding PR's that have been accepted and are ready for these changes, once https://github.com/openshift/ci-tools/pull/1890 merges?

**Comment by alvaroaleman** [comment]
@bradmwilliams yes it is. It is also already in ci-chat-bot and release-controller:
* https://github.com/openshift/ci-chat-bot/pull/146/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R26
* https://github.com/openshift/release-controller/pull/261/files#diff-4cf9522e878095c3485341074435715315289c126515459380ef42abee637f73R67

Which provides https://github.com/kubernetes/test-infra/blob/11321d21de7fce9dc525da683ded9648221fc583/prow/flagutil/config/config.go#L54

**Comment by bradmwilliams** [comment]
@alvaroaleman Thanks!  I saw the ci-chat-bot and release-controller PRs come though.  Just wanted to verify for all the other tools included in this PR.

**Review by bradmwilliams — APPROVED** [review]
/lgtm

**Comment by alvaroaleman** [comment]
Ref https://issues.redhat.com/browse/DPTP-2072

**Pull request merged**
