### PR TITLE
Update openshift-multiarch-release-4.8-periodics.yaml

### PR DESCRIPTION
**Pull request by LakshmiRavichandran1**
enable build/s2i tests on s390x with the availability of MA test-build-simples2i

### CODE REVIEW

**Comment by yselkowitz** [comment]
can we get the tests enabled on ppc64le too?

**Comment by deepsm007** [comment]
> can we get the tests enabled on ppc64le too?

Yes, @LakshmiRavichandran1 will enable them

**Review by deepsm007 — APPROVED** [review]
The failed tests are not related to the PR changes.

**Pull request merged**
