### PR TITLE
Downgrade bazel to 0.18.0

### PR DESCRIPTION
**Pull request by ingvagabund**
Sync with the same version used by the upstream cluster-api.

### CODE REVIEW

**Comment by enxebre** [comment]
why do we need to downgrade? this has been working so far

**Comment by ingvagabund** [comment]
> why do we need to downgrade? this has been working so far

for debugging purposes

**Comment by ingvagabund** [comment]
Unit test is failing with:
```
(which bazel && ./hack/update-bazel.sh) || true
/go/src/github.com/openshift/cluster-api/bazel
$TEST_TMPDIR defined: output root default is '/go/src/github.com/openshift/cluster-api/_output/.cache' and max_idle_secs default is '15'.
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 156d2d03-f85a-447d-b4b7-e3c46ead71ec
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
    currently loading: 
ERROR: Skipping '//:gazelle': error loading package '': in /go/src/github.com/openshift/cluster-api/_output/.cache/_bazel_root/329e6b0155c0ea7976c3e2bc09b71040/external/bazel_gazelle/def.bzl: Encountered error while reading extension file 'lib/shell.bzl': no such package '@bazel_skylib//lib': Traceback (most recent call last):
	File "/go/src/github.com/openshift/cluster-api/_output/.cache/_bazel_root/329e6b0155c0ea7976c3e2bc09b71040/external/bazel_tools/tools/build_defs/repo/git.bzl", line 163
		_clone_or_update(ctx)
	File "/go/src/github.com/openshift/cluster-api/_output/.cache/_bazel_root/329e6b0155c0ea7976c3e2bc09b71040/external/bazel_tools/tools/build_defs/repo/git.bzl", line 73, in _clone_or_update
		fail(("error cloning %s:\n%s" % (ctx....)))
error cloning bazel_skylib:
+ cd /go/src/github.com/openshift/cluster-api/_output/.cache/_bazel_root/329e6b0155c0ea7976c3e2bc09b71040/external
+ rm -rf /go/src/github.com/openshift/cluster-api/_output/.cache/_bazel_root/329e6b0155c0ea7976c3e2bc09b71040/external/bazel_skylib /go/src/github.com/openshift/cluster-api/_output/.cache/_bazel_root/329e6b0155c0ea7976c3e2bc09b71040/external/bazel_skylib
+ git clone --shallow-since=1549647446 +0100 https://github.com/bazelbuild/bazel-skylib /go/src/github.com/openshift/cluster-api/_output/.cache/_bazel_root/329e6b0155c0ea7976c3e2bc09b71040/external/bazel_skylib
error: unknown option `shallow-since=1549647446'
usage: git clone [options] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --progress            force progress reporting
    -n, --no-checkout     don't create a checkout
    --bare                create a bare repository
    --mirror              create a mirror repository (implies bare)
    -l, --local           to clone from a local repository
    --no-hardlinks        don't use local hardlinks, always copy
    -s, --shared          setup as shared repository
    --recursive           initialize submodules in the clone
    --recurse-submodules  initialize submodules in the clone
    --template <template-directory>
                          directory from which templates will be used
    --reference <repo>    reference repository
    -o, --origin <name>   use <name> instead of 'origin' to track upstream
    -b, --branch <branch>
                          checkout <branch> instead of the remote's HEAD
    -u, --upload-pack <path>
                          path to git-upload-pack on the remote
    --depth <depth>       create a shallow clone of that depth
    --single-branch       clone only one branch, HEAD or --branch
    --separate-git-dir <gitdir>
                          separate git dir from working tree
    -c, --config <key=value>
                          set config inside the new repository
```

**Pull request merged**
