### PR TITLE
merge-bot: Add periodics

### PR DESCRIPTION
**Pull request by mdbooth**

### CODE REVIEW

**Comment by mdbooth** [comment]
The failure of periodic-ci-shiftstack-merge-bot-main-cloud-provider-openstack is expected. It is correctly executing and determining that it can't currently perform an automatic merge due to an unresolved merge conflict in the target repo. That is: it is correctly failing.

**Comment by mdbooth** [comment]
AFAICT the failure in app-ci-config-dry is a bug in the test? Is this related to the decommissioning of app.ci?

**Comment by pierreprinetti** [comment]
You'll probably want to polish the API and treat failures and errors with separate signaling... but that is up to you. Good job!

/lgtm

**Pull request merged**
