### PR TITLE
ocm: add console repo

### PR DESCRIPTION
**Pull request by chrisahl**

### CODE REVIEW

**Review by jamestalton — APPROVED** [review]
lgtm

**Review by alvaroaleman — APPROVED** [review]
/label tide/merge-method-squash

**Comment by alvaroaleman** [comment]
@chrisahl please remove all changes in ci-operator/jobs/coreos/rpm-ostree and ci-operator/jobs/openshift/os from this PR

**Comment by chrisahl** [comment]
@alvaroaleman Thanks for spotting that.  Not sure why `make update` is doing that.  I have removed those changes from this PR.

**Comment by chrisahl** [comment]
@alvaroaleman Any idea why this is not merging?  Is it the hold?

**Pull request merged**
