### PR TITLE
OKD 4.9: create necessary periodics and release-controller config

### PR DESCRIPTION
**Pull request by vrutkovs**
Create release-controller configuration and periodics for OKD 4.9 nightlies

### CODE REVIEW

**Comment by bradmwilliams** [comment]
@vrutkovs  Just want to make sure that the name change from `origin` to `okd` is intentional? i.e. all the OKD files have been named: release-origin-4.X.json.

**Comment by vrutkovs** [comment]
>Just want to make sure that the name change from origin to okd is intentional

Yup, it is, we're trying to make sure clear up confusion between origin as in https://github.com/openshift/origin and origin as old name for OKD

**Review by bradmwilliams — APPROVED** [review]
/lgtm

**Pull request merged**
