### PR TITLE
cluster-launch-installer-meta-e2e: Retry bootstrap-complete once

### PR DESCRIPTION
**Pull request by sdodson**
Watching some CI jobs I'm seeing bootstrap-complete achieved shortly after we give up at 30 minutes. This is likely due to the longer than normal pivot from RHEL 8.0 to 8.1. I've also seen it happen once for install-complete but that was only after I had made manual attempts to unblock things.

### CODE REVIEW

**Comment by patrickdillon** [comment]
this LGTM... are you working on rehearsal or is this ready to merge?

**Comment by sdodson** [comment]
@patrickdillon Sorry, I should've WIP'd this. While I think this code is ready to go I'm waiting on some metal image changes to land before I'll be able to be sure that this has improved things. Those should land today or tomorrow and i'll slack you once it's ready.

**Comment by patrickdillon** [comment]
> @patrickdillon Sorry, I should've WIP'd this. While I think this code is ready to go I'm waiting on some metal image changes to land before I'll be able to be sure that this has improved things. Those should land today or tomorrow and i'll slack you once it's ready.

Sounds good. As there is a hold, I'll just lgtm and you can remove the hold. Or slack me if you need anything else. 
/lgtm

**Pull request merged**
