### PR TITLE
updating openshift-preflight jobs to go 1.22

### PR DESCRIPTION
**Pull request by acornett21**

### CODE REVIEW

**Comment by acornett21** [comment]
/pj-rehearse pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.12-e2e pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.12-images pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.15-e2e 
pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.15-images

**Comment by acornett21** [comment]
/pj-rehearse pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.12-e2e pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.12-images pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.15-e2e
pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.15-images

**Comment by acornett21** [comment]
/pj-rehearse pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.15-images

**Review by skattoju — APPROVED** [review]
/lgtm

**Pull request merged**
