### PR TITLE
openshift-ansible 3.11: run aws/gcp tests nightly

### PR DESCRIPTION
**Pull request by vrutkovs**
These periodics would help us asses the state of CI for 3.11 branches

### CODE REVIEW

**Comment by vrutkovs** [comment]
/hold

for rehearsals

**Review by mtnbikenc — APPROVED** [review]
/lgtm

**Comment by mtnbikenc** [comment]
The rehearsals ran fairly quickly, which seems suspicious.  I'm seeing some `exit status 1` messages but tests are passing.

**Comment by vrutkovs** [comment]
34m to install and run conformance/parallel on AWS :speedboat: :racehorse: Twice as much on GCP though.

Test results look correct to me though. lets see if serial/minimal (used in `origin`) works better

**Comment by mtnbikenc** [comment]
@vrutkovs, e2e-aws-nightly has passed once out of four attempts.  Do you feel that is enough or should we retest until it passes again?

**Comment by vrutkovs** [comment]
@mtnbikenc even if the pass rate is low its still worth having a periodic.
We can look into failures later once we get enough runs to analyze it

**Review by mtnbikenc — APPROVED** [review]
/lgtm

**Pull request merged**
