### PR TITLE
Add assisted-install workflow

### PR DESCRIPTION
**Pull request by YuviGold**
Like `baremetalds-assisted-workflow` but without test steps for PRs

### CODE REVIEW

**Comment by YuviGold** [comment]
/cc @osherdp 

Wait for everything to pass.
/hold

**Review by osherdp — APPROVED** [review]
/lgtm

**Comment by YuviGold** [comment]
Onpremise jobs are failing due to another issue that will be solved on https://github.com/openshift/assisted-test-infra/pull/507 .
/unhold

**Pull request merged**
