### PR TITLE
Make aws-ovn-windows presubmits optional for ovnk

### PR DESCRIPTION
**Pull request by jluhrsen**
Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>

### CODE REVIEW

**Comment by flavio-fernandes** [comment]
/assign @dcbw 
:)

**Comment by dcbw** [comment]
/lgtm
/approve
Until WinC team is able to figure out what's wrong with latest AWS Windows AMIs...
https://coreos.slack.com/archives/CM4ERHBJS/p1654696760639069

**Pull request merged**
