### PR TITLE
Update go version of odh/modelmesh-serving pipeline

### PR DESCRIPTION
**Pull request by israel-hdez**
Upgrade to go1.20, from go1.19.
This is required for Model Mesh v0.12

### CODE REVIEW

**Review by spolti — APPROVED** [review]
/lgtm

**Comment by israel-hdez** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-serving-main-images pull-ci-opendatahub-io-modelmesh-serving-main-unit

**Comment by israel-hdez** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-serving-main-images pull-ci-opendatahub-io-modelmesh-serving-main-unit

**Pull request merged**
