### PR TITLE
PLNSRVCE-452: turn off tr pruning for in repo jvm-build-svc e2e

### PR DESCRIPTION
**Pull request by gabemontero**

### CODE REVIEW

**Comment by gabemontero** [comment]
/assign @psturc 

I may see about getting someone in the US timezone with sufficent creds to lgtm this, but otherwise, when you are back in on Tuesday, PTAL

I expect the e2e to still fail given the current state of jvm-build-service and what I'm seeing in local testing and https://github.com/redhat-appstudio/jvm-build-service/pull/129 but assuming the cluster setup goes as expected, this change will help with debug in https://github.com/redhat-appstudio/jvm-build-service/pull/129

I'll put a hold if the rehearsal falls short of ^^

**Comment by gabemontero** [comment]
OK turning off of TaskRun pruning worked, as the pod dump on failure seen at https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/30790/rehearse-30790-pull-ci-redhat-appstudio-jvm-build-service-main-jvm-build-service-in-repo-e2e/1551633639530303488/build-log.txt dumped useful info, including the `--context` issue and bad cache service host issue addressed in https://github.com/redhat-appstudio/jvm-build-service/pull/129

@psturc please go ahead and lgtm here and it will facilitate fixing the test in jvm-build-service PRs 

thanks

**Comment by gabemontero** [comment]
https://github.com/redhat-appstudio/jvm-build-service/pull/129 we are now green

let's see how the rehearsal is

**Comment by gabemontero** [comment]
may need to put in a wait in the test to make sure the `pipeline` SA is created after project creation before we start creating Tekton objs:

`* failed to create task run pod "sample-component-build-5c72z-fetch-repository": translating TaskSpec to Pod: serviceaccounts "pipeline" not found. Maybe missing or invalid Task jvm-build-service-test-namespace-nshxh/git-clone`

let's see how intermittent or consistent this is ... have not see in previously

/retest

**Comment by gabemontero** [comment]
> may need to put in a wait in the test to make sure the `pipeline` SA is created after project creation before we start creating Tekton objs:
> 
> `* failed to create task run pod "sample-component-build-5c72z-fetch-repository": translating TaskSpec to Pod: serviceaccounts "pipeline" not found. Maybe missing or invalid Task jvm-build-service-test-namespace-nshxh/git-clone`
> 
> let's see how intermittent or consistent this is ... have not see in previously
> 
> /retest

@stuartwdouglas ^^

**Comment by gabemontero** [comment]
> > may need to put in a wait in the test to make sure the `pipeline` SA is created after project creation before we start creating Tekton objs:
> > `* failed to create task run pod "sample-component-build-5c72z-fetch-repository": translating TaskSpec to Pod: serviceaccounts "pipeline" not found. Maybe missing or invalid Task jvm-build-service-test-namespace-nshxh/git-clone`
> > let's see how intermittent or consistent this is ... have not see in previously
> > /retest
> 
> @stuartwdouglas ^^

https://github.com/redhat-appstudio/jvm-build-service/pull/130

though did not merge in time for current test run

**Comment by psturc** [comment]
> > > may need to put in a wait in the test to make sure the `pipeline` SA is created after project creation before we start creating Tekton objs:
> > > `* failed to create task run pod "sample-component-build-5c72z-fetch-repository": translating TaskSpec to Pod: serviceaccounts "pipeline" not found. Maybe missing or invalid Task jvm-build-service-test-namespace-nshxh/git-clone`
> > > let's see how intermittent or consistent this is ... have not see in previously
> > > /retest
> > 
> > 
> > @stuartwdouglas ^^
> 
> [redhat-appstudio/jvm-build-service#130](https://github.com/redhat-appstudio/jvm-build-service/pull/130)
> 
> though did not merge in time for current test run

I think that's reasonable thing to do. We do that in [e2e-tests as well](https://github.com/redhat-appstudio/e2e-tests/blob/30c8b4b4db23e23bc099c62f123edabf456d1238/pkg/utils/common/controller.go#L324-L327) after we noticed some failures related to missing pipeline SA

**Review by psturc — APPROVED** [review]

**Pull request merged**
