### PR TITLE
Add 4.15 nightly configs

### PR DESCRIPTION
**Pull request by ashwindasr**
For https://issues.redhat.com/browse/ART-7065

### CODE REVIEW

**Comment by ashwindasr** [comment]
4.14 tests brought forward

**Comment by ashwindasr** [comment]
Haven't add the CI file though, not sure if it was within the scope of this change. Please let me know if I should add that in as well.

**Comment by bradmwilliams** [comment]
> Haven't add the CI file though, not sure if it was within the scope of this change. Please let me know if I should add that in as well.

I'm not aware of any reason why you shouldn't bring the `ci` changes along as well. If nothing is producing images into those imagestreams, then the release-controller will simply ignore them.

**Comment by ashwindasr** [comment]
Added CI config in https://github.com/openshift/release/pull/41062/commits/845b6e467bc2b2810c1047b19dc271a970bd3d8c

**Comment by bradmwilliams** [comment]
/approve
I'll approve the changes to give someone else the opportunity to comment (specifically @openshift/openshift-release-oversight) to make sure that they have a chance to chime in with any concerns here.

**Comment by neisw** [comment]
Are the 4.15 configs like [release-ocp-4.15.json](https://github.com/openshift/release/blob/845b6e467bc2b2810c1047b19dc271a970bd3d8c/core-services/release-controller/_releases/release-ocp-4.15.json) supposed to reference 4.14 jobs?  Not sure if it is an intentional transitory thing or not.

    "gcp-ovn-upgrade-4.14-minor": {
      "optional": true,
      "prowJob": {
        "name": "periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-upgrade"
      },
      "upgrade": true,
      "upgradeFromRelease": {
        "candidate": {
          "stream": "nightly",
          "version": "4.13"
        }
      }
    },
    etc.

**Comment by bradmwilliams** [comment]
Previously, when branching occurred, there was a copy-paste-update step that took the jobs and job definitions and performed an N+1 operation on them to move them forward.  Obviously, that won't work in this case since there are no new job definitions.  This might be worth bringing to the ARCH call on Thursday to try an flesh out with all the parties involved.

**Comment by ashwindasr** [comment]
Closing this in favor of https://github.com/openshift/release/pull/41475 and https://github.com/openshift/release/pull/41475.

**Pull request closed without merging**
