### PR TITLE
OCM-9597 | ci: rosa-master-e2e-rosa-sts-shared-vpc-critical-high-f3 failed at creation

### PR DESCRIPTION
**Pull request by xueli181114**

### CODE REVIEW

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-sts-shared-vpc-critical-high-f3

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-sts-shared-vpc-critical-high-f3

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-sts-shared-vpc-critical-high-f3

**Comment by robpblake** [comment]
Confirmed with @xueli181114  that the `pj-rehearse` is failing due to unstable test cases, not the CI configuration itself.

**Review by robpblake — APPROVED** [review]
/lgtm

**Pull request merged**
