### PR TITLE
RHOSDT 3.4 security and FIPS scan

### PR DESCRIPTION
**Pull request by IshwarKanse**

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-grafana-tempo-operator-main-upstream-ocp-4.15-amd64-aws-security-sast pull-ci-openshift-jaegertracing-jaeger-operator-main-security-sast pull-ci-openshift-distributed-tracing-qe-main-ocp-4.14-dast-distributed-tracing-tests-dast pull-ci-openshift-distributed-tracing-qe-main-ocp-4.16-fips-scan-distributed-tracing-operators pull-ci-openshift-open-telemetry-opentelemetry-operator-main-upstream-ocp-4.15-amd64-aws-security-sast

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-upstream-ocp-4.15-amd64-aws-security-sast

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-distributed-tracing-qe-main-ocp-4.14-dast-distributed-tracing-tests-dast pull-ci-openshift-distributed-tracing-qe-main-ocp-4.16-fips-scan-distributed-tracing-operators

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-distributed-tracing-qe-main-ocp-4.16-fips-scan-distributed-tracing-operators

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-distributed-tracing-qe-main-ocp-4.16-fips-scan-distributed-tracing-operators

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-distributed-tracing-qe-main-ocp-4.16-fips-scan-distributed-tracing-operators

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-distributed-tracing-qe-main-ocp-4.16-fips-scan-distributed-tracing-operators

**Review by vprashar2929 — APPROVED** [review]
/lgtm

**Pull request merged**
