### PR TITLE
OCPEDGE-1252: upkeep: add presubmits for 4.17

### PR DESCRIPTION
**Pull request by eggfoobar**

### CODE REVIEW

**Review by jakobmoellerdev — APPROVED** [review]
/lgtm

**Comment by eggfoobar** [comment]
/pj-rehearse pull-ci-openshift-lvm-operator-release-4.17-e2e-aws

**Comment by eggfoobar** [comment]
/pj-rehearse pull-ci-openshift-lvm-operator-release-4.17-precommit-check

**Comment by eggfoobar** [comment]
/pj-rehearse pull-ci-openshift-lvm-operator-release-4.17-precommit-check

**Pull request merged**
