### PR TITLE
Remove stale generated postsubmits

### PR DESCRIPTION
**Pull request by petr-muller**
Removes a bunch of image-building & promoting postsubmits for older releases. Prowgen no longer generates these jobs after many changes in its logic, so we may consider removing them. I am not sure if that is a appropriate action to do, but if we need these jobs, we should fix prowgen so it starts generating them again.

/cc @smarterclayton @stevekuznetsov

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@smarterclayton do we care to promote things prior to 4.0? My first thought would be no

**Comment by stevekuznetsov** [comment]
@petr-muller we fixed prowgen to remove these, right?

**Comment by petr-muller** [comment]
> @petr-muller we fixed prowgen to remove these, right?

Not exactly, prowgen removes jobs with a `generated-by-prowgen` label, but the jobs created before prowgen started labeling its jobs are not recognized as generated. We just no longer create new stale jobs as we go.

**Comment by stevekuznetsov** [comment]
Oh right and my thought was that we could cherry-pick the `generated-by-prowgen` label to an old `prowgen` and use it to label these before we made promotion optional, then we could use the new one to remove them?

**Comment by petr-muller** [comment]
> Oh right and my thought was that we could cherry-pick the `generated-by-prowgen` label to an old `prowgen` and use it to label these before we made promotion optional, then we could use the new one to remove them?

I don't think that happened - I though this PR would be simply merged. I think I can regenerate the PR without much effort.

**Comment by petr-muller** [comment]
Rebased. Noticed further suspicious manual jobs while doing so, filed https://github.com/openshift/release/pull/3697 for it.

**Pull request merged**
