### PR TITLE
fix(KFLUXBUGS-1486): Use correct Exodus secret names

### PR DESCRIPTION
**Pull request by dheerajodha**
The E2E job's Bootstrap script fails while fetching the secret called "exodus_non_prod_key" from the OpenShift Vault. This is because the Vault contains a secret named "exodus_prod_key" instead.

### CODE REVIEW

**Comment by dheerajodha** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests-periodic

**Review by jinqi7 — APPROVED** [review]

**Pull request merged**
