### PR TITLE
adding FDP qe trigger to 4.16 presubmits and add NonPreRelease tag

### PR DESCRIPTION
**Pull request by anuragthehatter**
backporting #51675  to 4.16 as well
@jluhrsen @kuiwang02 @liangxia @asood-rh PTAL

### CODE REVIEW

**Comment by jluhrsen** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-release-4.16-e2e-aws-ovn-fdp-qe

**Comment by asood-rh** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-release-4.16-e2e-aws-ovn-fdp-qe

**Comment by anuragthehatter** [comment]
@jluhrsen @vrutkovs Can you help merging it if no comments? Thanks

**Comment by anuragthehatter** [comment]
/hold
Waiting for https://github.com/openshift/openshift-tests-private/pull/17426 to merge to see how that rehearses.

**Comment by anuragthehatter** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-release-4.16-e2e-aws-ovn-fdp-qe

**Comment by anuragthehatter** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-release-4.16-e2e-aws-ovn-fdp-qe

**Comment by anuragthehatter** [comment]
@jluhrsen @vrutkovs Can you help merging it? Thanks

**Comment by jluhrsen** [comment]
the commit message seems weird:

```
adding trigger to 4.16 presubmits as well
adding trigger to 4.16 presubmits as well 1

adding trigger to 4.16 presubmits as well 2
```

**Comment by anuragthehatter** [comment]
> the commit message seems weird:
> 
> ```
> adding trigger to 4.16 presubmits as well
> adding trigger to 4.16 presubmits as well 1
> 
> adding trigger to 4.16 presubmits as well 2
> ```

@jluhrsen Sorry for confusion. SInce it was all squashed I did't mention clearly..heh. Whatever went in #51675 its all same except tag is `4.16` now in 2nd commit and QE tests tagged with `NonPreRelease` will also be included.

**Comment by anuragthehatter** [comment]
@jluhrsen Done. PTAL. Also removed `always_run: false`, `sudo make jobs` and then manually added that back

**Comment by jluhrsen** [comment]
/pj-rehearse


if the rehearsals come back looking right, we can get this in.

**Comment by jluhrsen** [comment]
one of the jobs failed, but don't think it has anything to do with this PR that is just creating the job. maybe a bug in the product or test.

/pj-rehearse ack
/lgtm

**Comment by anuragthehatter** [comment]
@vrutkovs @deads2k @stbenjam Looking for trt approval. Thanks

**Comment by anuragthehatter** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-release-4.16-e2e-aws-ovn-fdp-qe

**Pull request merged**
