### PR TITLE
Update VPA and Cluster Resource Override for 4.17

### PR DESCRIPTION
**Pull request by joelsmith**

### CODE REVIEW

**Comment by joelsmith** [comment]
Needed for the following PRs:
https://github.com/openshift/kubernetes-autoscaler/pull/304
https://github.com/openshift/vertical-pod-autoscaler-operator/pull/163
https://github.com/openshift/cluster-resource-override-admission/pull/73
https://github.com/openshift/cluster-resource-override-admission-operator/pull/145

**Comment by jkyros** [comment]
hmmm, /pj-rehearse ack maybe ?

**Comment by joelsmith** [comment]
> hmmm, /pj-rehearse ack maybe ?

Yep, I couldn't remember the syntax without the bot's clues and had to go look it up. I should have just waited a sec for your hint ;-)

**Pull request merged**
