### PR TITLE
Fixing openshift-origin-aggregated-logging-master.yaml to use dockerfile from ocp-build-data

### PR DESCRIPTION
**Pull request by alvaroaleman**

### CODE REVIEW

**Comment by jupierce** [comment]
This PR depends on https://github.com/openshift/origin-aggregated-logging/pull/1965

**Comment by periklis** [comment]
@alvaroaleman @jupierce What are we missing here to fix the builds? I don't see any PR on origin-aggregated-logging to tell.

**Comment by jupierce** [comment]
@periklis The images cannot be built: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/10886/rehearse-10886-pull-ci-openshift-origin-aggregated-logging-master-images/1301199792864497664/build-log.txt  . 
```
LoadError: cannot load such file -- rdoc/task
/fluentd/lib/syslog_protocol/Rakefile:63:in `require'
/fluentd/lib/syslog_protocol/Rakefile:63:in `<top (required)>'
/fluentd/lib/syslog_protocol/vendor/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
/usr/share/gems/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/usr/share/gems/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/opt/app-root/src/bin/bundle:23:in `load'
/opt/app-root/src/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
/fluentd/lib
subprocess exited wi
```
https://coreos.slack.com/archives/C016WEXB3U6/p1597760376174700 discusses it.

**Review by periklis — APPROVED** [review]

**Pull request merged**
