### PR TITLE
mco: Update base images for the e2e-metal-assisted flow

### PR DESCRIPTION
**Pull request by YuviGold**

### CODE REVIEW

**Comment by YuviGold** [comment]
> @YuviGold should these metal jobs be failing?

These images are used only by e2e-metal-assisted workflow. All the other jobs shouldn't be affected.

**Comment by kikisdeliveryservice** [comment]
> > @YuviGold should these metal jobs be failing?
> 
> These images are used only by e2e-metal-assisted workflow. All the other jobs shouldn't be affected.

gotcha, that job does indeed pass :+1: 

/approve

**Pull request merged**
