### PR TITLE
vsphere upi: updates for terraform changes

### PR DESCRIPTION
**Pull request by jcpowermac**
- Added new terraform variables required in the recent
changes in vsphere upi terraform

- Added an additional run of the registry patch
in some instances the config is not update properly.

- vim - `autocmd BufWritePre * %s/\s\+$//e` removed white space

### CODE REVIEW

**Comment by jcpowermac** [comment]
This PR can be merged without the changes to the installer:
https://github.com/openshift/installer/pull/3429

**Comment by abhinavdahiya** [comment]
can you separate the remove extra space commit from code changes please.

**Comment by abhinavdahiya** [comment]
> Added an additional run of the registry patch
in some instances the config is not update properly.

can you link to the BZ that explains why this change is required, or provide the details in the commit message. Currently it's unclear.

**Comment by bparees** [comment]
/approve

will wait for @abhinavdahiya to lgtm

**Comment by abhinavdahiya** [comment]
> Added new terraform variables required in the recent
changes in vsphere upi terraform

this template is used by all releases 4.{1,2,3,4} and master.. so please make sure adding these new variables do not break previous releases.

**Comment by jcpowermac** [comment]
> > Added new terraform variables required in the recent
> > changes in vsphere upi terraform
> 
> this template is used by all releases 4.{1,2,3,4} and master.. so please make sure adding these new variables do not break previous releases.

I have extra variables in my `terraform.tfvars` it just seems to warn that they are there.
updated as asked

**Comment by patrickdillon** [comment]
LGTM.

**Pull request merged**
