### PR TITLE
add workflow for vsphere upi with https proxy conf

### PR DESCRIPTION
**Pull request by jinyunma**
add workflow for vsphere upi with https proxy conf

### CODE REVIEW

**Comment by jinyunma** [comment]
cc @jianlinliu and @gpei help to review

**Comment by jinyunma** [comment]
@liangxia could you help to approve this PR? thanks.

**Comment by liangxia** [comment]
@jinyunma  I'll wait for https://github.com/openshift/verification-tests/pull/2510, and the bot will sync the changes to openshift/release, which will happen at about 15:33 (Beijing time) today. Then @jianlinliu and @gpei can try to approve.

**Comment by liangxia** [comment]
The bot synced the owners in https://github.com/openshift/release/pull/23990

@jianlinliu Could you help verify you have got the merge permission by add `/approve` on a separate line ?

**Comment by jianlinliu** [comment]
@liangxia great, it woks. Thanks.

**Pull request merged**
