### PR TITLE
Enable additional OpenTelemetry tests.

### PR DESCRIPTION
**Pull request by IshwarKanse**
* Enable additional OpenTelemetry tests.
* Skip monolithic-multitenancy-openshift test until https://github.com/grafana/tempo-operator/pull/866 is merged.

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-grafana-tempo-operator-main-tempo-e2e-tests pull-ci-openshift-grafana-tempo-operator-main-tempo-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests

**Review by iblancasa — APPROVED** [review]

**Pull request merged**
