### PR TITLE
Adding Eventhubs to the broker test image build procedure

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

Based on https://github.com/openshift-knative/eventing-kafka-broker/pull/251

### CODE REVIEW

**Comment by matzew** [comment]
/hold

for the midstream PR

**Comment by matzew** [comment]
@pierDipi please take a look

**Review by pierDipi — APPROVED** [review]
/lgtm

**Pull request merged**
