### PR TITLE
cert-rotation: fix prepare for shutdown for HA

### PR DESCRIPTION
**Pull request by vrutkovs**
Wait for one or 3 replicas to show up

### CODE REVIEW

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-30d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-30d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-suspend-30d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-suspend-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-30d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-30d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-suspend-30d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-suspend-30d

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Pull request merged**
