### PR TITLE
[wip]Add the mirror file all missing images on app.ci

### PR DESCRIPTION
**Pull request by hongkailiu**
https://issues.redhat.com/browse/DPTP-1981

The mapping file is generated by https://github.com/openshift/ci-tools/pull/1714

### CODE REVIEW

**Comment by hongkailiu** [comment]
Some stats:

```txt
# 9971 images to mirror in total
$ cat core-services/image-mirroring/dptp-internal/mapping_dptp_internal | wc -l
    9971
# sum by namespace
$ cat core-services/image-mirroring/dptp-internal/mapping_dptp_internal | cut -d '=' -f 2 | cut -d '/' -f 2 | sort | uniq -c | sort -r -k 1 -n
2023 ipv6
 815 ocp-private
 772 rhcos-devel
 583 sno-dev
 571 kni
 455 oo-index-images
 396 cincinnati-ci-public
 333 honzaci
 315 muller-bundle-testing
 311 msimka
 297 sno-vz-alpha
 230 flaper87-moc
 227 dprince-moc
 225 bbguimaraes
 189 adahiya-testing
 170 save-42
 160 metal-testing
 144 trown-moc
 144 nmoraitis-test
 143 mrunalptest
 122 assisted-installer
 113 ci-byoh
 111 hypershift-toolkit
 104 crawford-test
  92 rteague-1
  91 ocp
  79 rhcos
  76 openstack
  56 clayton-test-1
  56 ci
  53 jc-crud
  50 newkargakistest
  48 bnemec
  45 vrutkovs
  44 ci-pr-images
  32 integr8ly
  30 markmc
  29 mrunalp-mirrors
  20 hongkliu-test
  18 open-cluster-management
  14 ovirt
  14 cgwalters
  14 cewong-dev
  12 squeed
  12 cincinnati-ci
   8 kiegroup
   8 jlebon-test-1
   8 jlebon
   8 coreos
   7 psap
   7 ibm-gate-secrets
   6 art
   5 ocp-kni
   5 nmoraitis-prow
   4 metering-prerelease
   4 chancez-e2e-35
   3 wjiang
   3 cincinnati
   3 ci-test-ewolinet
   2 serenatest
   2 promecieus
   2 ppc64le-openstack-installer-46
   2 ppc64le-openstack-installer-45
   2 ppc64le-openstack-installer-44
   2 ppc64le-openstack-installer-43
   2 ocp-future
   2 mkumatag-test
   2 jeremy-ssl-junk
   2 images-openshift-acme
   2 http-test2
   2 heckinchonker
   2 fcos
   2 danwinship
   2 cvp-images
   2 code-ready
   1 tunedover
   1 travier
   1 test
   1 pratik
   1 osd-operators
   1 origin
   1 miabbott
   1 local-operators
   1 jwforres-test
   1 jbieren
   1 jaypoulz
   1 fabric8-services
   1 eb96a609
   1 derekh
   1 deads2k-01
   1 darkmuggle
   1 codeready-toolchain
   1 clayton-test
   1 bz1784163
   1 bugzilla-operator
   1 bastion
   1 anothertest
```

**Comment by stevekuznetsov** [comment]
What happens when the namespace does not exist on app.ci?

**Comment by stevekuznetsov** [comment]
We can probably filter those out.

**Comment by stevekuznetsov** [comment]
WTF are 2k images in ipv6 NS?

**Comment by petr-muller** [comment]
I'd probably be quite selective, it's (again a nice opportunity to get rid of cruft). Maybe select the namespaces which are obviously important (`ci`, `art`...) and share the list with aos-devel with "we're leaving these ones behind, shout loudly if there's anything important. Then wait a week, then unexpose the reigstry and see what breaks.

**Comment by hongkailiu** [comment]
> What happens when the namespace does not exist on app.ci?

In theory the oc-image-mirror call will fail. In reality, we do not have such case
```
# nothing is printed.
$ cat core-services/image-mirroring/dptp-internal/mapping_dptp_internal | cut -d '=' -f 2 | cut -d '/' -f 2 | sort | uniq  | while read ns; do if ! oc --context app.ci get ns $ns ; then echo "$ns =============" ; fi ; done
```

**Pull request closed without merging**
