### PR TITLE
Adding the func-util image

### PR DESCRIPTION
**Pull request by creydr**
Adding the func-util image (added in https://github.com/openshift-knative/kn-plugin-func/pull/860)

### CODE REVIEW

**Comment by matejvasek** [comment]
@jrangelramos PTAL

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-kn-plugin-func-release-next-images

**Comment by creydr** [comment]
rebased

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-kn-plugin-func-release-next-images

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-kn-plugin-func-release-next-unit

**Comment by creydr** [comment]
```
could not run steps: step e2e-oncluster-test failed: failed to wait for the created cluster claim to become ready: timed out waiting for the condition 
```
/pj-rehearse pull-ci-openshift-knative-kn-plugin-func-release-next-e2e-oncluster-test

**Comment by matejvasek** [comment]
/pj-rehearse pull-ci-openshift-knative-kn-plugin-func-release-next-e2e-oncluster-test

**Comment by matejvasek** [comment]
/pj-rehearse pull-ci-openshift-knative-kn-plugin-func-release-next-unit

**Comment by matejvasek** [comment]
/pj-rehearse pull-ci-openshift-knative-kn-plugin-func-release-next-unit

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-kn-plugin-func-release-next-unit

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-kn-plugin-func-release-next-unit

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-kn-plugin-func-release-next-unit

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-kn-plugin-func-release-next-unit

**Comment by creydr** [comment]
Needs #881 for func-utils image in serverless-1.34 branch

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-kn-plugin-func-release-next-unit

**Pull request merged**
