### PR TITLE
OSASINFRA-3522: Redistribute ShifStack CI Jobs between mecha-central and mecha-az0 clouds

### PR DESCRIPTION
**Pull request by MiguelCarpio**
The ShifStack CI Jobs redistribution between mecha-central and mecha-az0 is needed because mecha-central lacks the resources to run all the designated jobs. On the other hand, mecha-az0 has few designated jobs and shows many resources available.

The following jobs will be moved from mecha-central to mecha-az0.  All jobs that are less than version 4.15.

shiftstack-ci-release-4.12.yaml
- e2e-openstack-proxy
- e2e-openstack-csi-manila
- e2e-openstack-csi-cinder

shiftstack-ci-release-4.13.yaml
- e2e-openstack-proxy
- e2e-openstack-externallb-techpreview
- e2e-openstack-csi-manila
- e2e-openstack-csi-cinder

shiftstack-ci-release-4.14.yaml
- e2e-openstack-externallb
- e2e-openstack-proxy
- e2e-openstack-csi-manila  
- e2e-openstack-csi-cinder

### CODE REVIEW

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.13-e2e-openstack-externallb-techpreview periodic-ci-shiftstack-ci-release-4.14-e2e-openstack-csi-manila

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.13-e2e-openstack-externallb-techpreview periodic-ci-shiftstack-ci-release-4.14-e2e-openstack-csi-manila

**Review by mandre — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
