### PR TITLE
Update the latest and target image env name

### PR DESCRIPTION
**Pull request by shellyyang1989**
Closes [OCPQE-13410](https://issues.redhat.com/browse/OCPQE-13410)

### CODE REVIEW

**Comment by shellyyang1989** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-nightly-4.12-upgrade-from-stable-4.11-aws-ipi-disconnected-private-p2-f14

**Comment by shellyyang1989** [comment]
Upgrade step passed. 
INFO[2023-01-03T09:10:51Z] Step aws-ipi-disconnected-private-p2-f14-cucushift-upgrade-toimage succeeded after 1h13m30s. 

cc @aleskandro @liangxia for review and merge. Thanks!

**Comment by aleskandro** [comment]
Hi @shellyyang1989, thanks!

/lgtm

I just wonder whether replacing the occurrences of `RELEASE_IMAGE_TARGET` and `RELEASE_IMAGE_INITIAL` with `OPENSHIFT_UPGRADE_RELEASE_IMAGE_OVERRIDE` and `OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE` can be a (low-pri) follow-up to this PR to get a more coherent code base for the upgrade-steps defined in the cucushift org's steps with respect to other code in this repo.

**Comment by shellyyang1989** [comment]
> I just wonder whether replacing the occurrences of `RELEASE_IMAGE_TARGET` and `RELEASE_IMAGE_INITIAL` with `OPENSHIFT_UPGRADE_RELEASE_IMAGE_OVERRIDE` and `OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE` can be a (low-pri) follow-up to this PR to get a more coherent code base for the upgrade-steps defined in the cucushift org's steps with respect to other code in this repo.

Yeah, I agree. Having unified env name makes sense to me. The EUS upgrade are using `RELEASE_IMAGE_INITIAL`  and `RELEASE_IMAGE_TARGET`.

```
$ grep -r "RELEASE_IMAGE_TARGET\|RELEASE_IMAGE_INITIAL"
upgrade/paused/intermediate/cucushift-upgrade-paused-intermediate-commands.sh:echo "RELEASE_IMAGE_INITIAL: ${RELEASE_IMAGE_INITIAL}"
upgrade/paused/intermediate/cucushift-upgrade-paused-intermediate-commands.sh:oc adm release info "${RELEASE_IMAGE_INITIAL}"
upgrade/paused/intermediate/cucushift-upgrade-paused-intermediate-ref.yaml:    env: "RELEASE_IMAGE_INITIAL"
upgrade/paused/intermediate/cucushift-upgrade-paused-intermediate-ref.yaml:    env: "RELEASE_IMAGE_TARGET"
upgrade/paused/intermediate/to-latest/cucushift-upgrade-paused-intermediate-to-latest-commands.sh:TARGET_VERSION="$(oc adm release info "${RELEASE_IMAGE_TARGET}" --output=json | jq -r '.metadata.version')"
upgrade/paused/intermediate/to-latest/cucushift-upgrade-paused-intermediate-to-latest-ref.yaml:    env: "RELEASE_IMAGE_TARGET"
upgrade/paused/latest/cucushift-upgrade-paused-latest-commands.sh:echo "RELEASE_IMAGE_TARGET: ${RELEASE_IMAGE_TARGET}"
upgrade/paused/latest/cucushift-upgrade-paused-latest-commands.sh:oc adm release info "${RELEASE_IMAGE_TARGET}"
upgrade/paused/latest/cucushift-upgrade-paused-latest-commands.sh:export TARGET_RELEASE="${RELEASE_IMAGE_TARGET}"
upgrade/paused/latest/cucushift-upgrade-paused-latest-ref.yaml:    env: "RELEASE_IMAGE_INITIAL"
upgrade/paused/latest/cucushift-upgrade-paused-latest-ref.yaml:    env: "RELEASE_IMAGE_TARGET"
upgrade/paused/latest/to-latest/cucushift-upgrade-paused-latest-to-latest-commands.sh:TARGET_VERSION="$(oc adm release info "${RELEASE_IMAGE_TARGET}" --output=json | jq -r '.metadata.version')"
upgrade/paused/latest/to-latest/cucushift-upgrade-paused-latest-to-latest-ref.yaml:    env: "RELEASE_IMAGE_TARGET"
upgrade/paused/unpause/cucushift-upgrade-paused-unpause-commands.sh:echo "RELEASE_IMAGE_TARGET ${RELEASE_IMAGE_TARGET}"
upgrade/paused/unpause/cucushift-upgrade-paused-unpause-commands.sh:oc adm release info "${RELEASE_IMAGE_TARGET}"
upgrade/paused/unpause/cucushift-upgrade-paused-unpause-commands.sh:export TARGET_RELEASE="${RELEASE_IMAGE_TARGET}"
upgrade/paused/unpause/cucushift-upgrade-paused-unpause-ref.yaml:    env: "RELEASE_IMAGE_INITIAL"
upgrade/paused/unpause/cucushift-upgrade-paused-unpause-ref.yaml:    env: "RELEASE_IMAGE_TARGET"
```

And multi-hop upgrade are using `RELEASE_IMAGE_INITIAL`  and `RELEASE_IMAGE_TARGET`.

```
$ grep -r "RELEASE_IMAGE_TARGET\|RELEASE_IMAGE_INITIAL"
openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.2.yaml:      commands: echo "${RELEASE_IMAGE_INTERMEDIATE43},${RELEASE_IMAGE_INTERMEDIATE44},${RELEASE_IMAGE_INTERMEDIATE45},${RELEASE_IMAGE_INTERMEDIATE46},${RELEASE_IMAGE_INTERMEDIATE47},${RELEASE_IMAGE_INTERMEDIATE48},${RELEASE_IMAGE_INTERMEDIATE49},${RELEASE_IMAGE_INTERMEDIATE410},${RELEASE_IMAGE_INTERMEDIATE411},${RELEASE_IMAGE_TARGET}"
openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.2.yaml:      - env: RELEASE_IMAGE_TARGET
openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.3.yaml:      commands: echo "${RELEASE_IMAGE_INTERMEDIATE44},${RELEASE_IMAGE_INTERMEDIATE45},${RELEASE_IMAGE_INTERMEDIATE46},${RELEASE_IMAGE_INTERMEDIATE47},${RELEASE_IMAGE_INTERMEDIATE48},${RELEASE_IMAGE_INTERMEDIATE49},${RELEASE_IMAGE_INTERMEDIATE410},${RELEASE_IMAGE_INTERMEDIATE411},${RELEASE_IMAGE_TARGET}"
openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.3.yaml:      - env: RELEASE_IMAGE_TARGET
openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.4.yaml:      commands: echo "${RELEASE_IMAGE_INTERMEDIATE45},${RELEASE_IMAGE_INTERMEDIATE46},${RELEASE_IMAGE_INTERMEDIATE47},${RELEASE_IMAGE_INTERMEDIATE48},${RELEASE_IMAGE_INTERMEDIATE49},${RELEASE_IMAGE_INTERMEDIATE410},${RELEASE_IMAGE_INTERMEDIATE411},${RELEASE_IMAGE_TARGET}"
openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.4.yaml:      - env: RELEASE_IMAGE_TARGET
openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.5.yaml:      commands: echo "${RELEASE_IMAGE_INTERMEDIATE46},${RELEASE_IMAGE_INTERMEDIATE47},${RELEASE_IMAGE_INTERMEDIATE48},${RELEASE_IMAGE_INTERMEDIATE49},${RELEASE_IMAGE_INTERMEDIATE410},${RELEASE_IMAGE_INTERMEDIATE411},${RELEASE_IMAGE_TARGET}"
openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.5.yaml:      - env: RELEASE_IMAGE_TARGET
openshift-openshift-tests-private-release-4.11__amd64-nightly-4.11-upgrade-from-stable-4.10-from-stable-4.9.yaml:      commands: echo "${RELEASE_IMAGE_INTERMEDIATE},${RELEASE_IMAGE_TARGET}" > ${SHARED_DIR}/upgrade-edge
openshift-openshift-tests-private-release-4.11__amd64-nightly-4.11-upgrade-from-stable-4.10-from-stable-4.9.yaml:      - env: RELEASE_IMAGE_TARGET
openshift-openshift-tests-private-release-4.11__amd64-nightly-4.11-upgrade-from-stable-4.10-from-stable-4.9.yaml:      commands: echo "${RELEASE_IMAGE_INTERMEDIATE},${RELEASE_IMAGE_TARGET}" > ${SHARED_DIR}/upgrade-edge
openshift-openshift-tests-private-release-4.11__amd64-nightly-4.11-upgrade-from-stable-4.10-from-stable-4.9.yaml:      - env: RELEASE_IMAGE_TARGET
openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.7.yaml:      commands: echo "${RELEASE_IMAGE_INTERMEDIATE48},${RELEASE_IMAGE_INTERMEDIATE49},${RELEASE_IMAGE_INTERMEDIATE410},${RELEASE_IMAGE_INTERMEDIATE411},${RELEASE_IMAGE_TARGET}"
openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.7.yaml:      - env: RELEASE_IMAGE_TARGET
openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.6.yaml:      commands: echo "${RELEASE_IMAGE_INTERMEDIATE47},${RELEASE_IMAGE_INTERMEDIATE48},${RELEASE_IMAGE_INTERMEDIATE49},${RELEASE_IMAGE_INTERMEDIATE410},${RELEASE_IMAGE_INTERMEDIATE411},${RELEASE_IMAGE_TARGET}"
openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.6.yaml:      - env: RELEASE_IMAGE_TARGET
openshift-openshift-tests-private-release-4.12__amd64-stable-4.12-upgrade-from-stable-4.6.yaml:      commands: echo "${RELEASE_IMAGE_INTERMEDIATE47},${RELEASE_IMAGE_INTERMEDIATE48},${RELEASE_IMAGE_INTERMEDIATE49},${RELEASE_IMAGE_INTERMEDIATE410},${RELEASE_IMAGE_INTERMEDIATE411},${RELEASE_IMAGE_TARGET}"
openshift-openshift-tests-private-release-4.12__amd64-stable-4.12-upgrade-from-stable-4.6.yaml:      - env: RELEASE_IMAGE_TARGET
openshift-openshift-tests-private-release-4.12__amd64-stable-4.12-upgrade-from-stable-4.7.yaml:      commands: echo "${RELEASE_IMAGE_INTERMEDIATE48},${RELEASE_IMAGE_INTERMEDIATE49},${RELEASE_IMAGE_INTERMEDIATE410},${RELEASE_IMAGE_INTERMEDIATE411},${RELEASE_IMAGE_TARGET}"
openshift-openshift-tests-private-release-4.12__amd64-stable-4.12-upgrade-from-stable-4.7.yaml:      - env: RELEASE_IMAGE_TARGET
openshift-openshift-tests-private-release-4.12__arm64-nightly-4.12-upgrade-from-eus-4.10.yaml:      RELEASE_IMAGE_INITIAL: release:initial-arm64
openshift-openshift-tests-private-release-4.12__arm64-nightly-4.12-upgrade-from-eus-4.10.yaml:      RELEASE_IMAGE_TARGET: release:target-arm64
```

**Pull request merged**
