### PR TITLE
Remove the release-2.7 and main branches from the deprecated sync controllers

### PR DESCRIPTION
**Pull request by mprahl**

### CODE REVIEW

**Review by dhaiducek — APPROVED** [review]
LGTM!

Good call! Should we also archive the repos upstream and uninstall magic-mirror from them?

**Comment by mprahl** [comment]
> LGTM!
> 
> Good call! Should we also archive the repos upstream and uninstall magic-mirror from them?

Good point! I archived the upstream repos now. I'll go ahead and request that Magic Mirror be disabled on those repos.

**Pull request merged**
