### PR TITLE
ComplianceAsCode: Add PCI-DSS v4 profiles to e2e

### PR DESCRIPTION
**Pull request by yuumasato**
Let's enable testing for PCI-DSS v4 profiles.

### CODE REVIEW

**Comment by yuumasato** [comment]
@rhmdnd @Vincent056

**Comment by rhmdnd** [comment]
Looks like some of the failures are due to legitimate issues:

```
E2E-FAILURE: The expected result for the e2e-pci-dss-4-0-security-profiles-operator-exists rule didn't match. Expected 'PASS', Got 'FAIL'
```

I think we can fix those in a subsequent PR to the content repository.

**Pull request merged**
