### PR TITLE
shiftstack monitor: Add Vexxhost

### PR DESCRIPTION
**Pull request by pierreprinetti**

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
/lgtm

**Comment by pierreprinetti** [comment]
Explanation: this Vexxhost-managed cloud is currently our main target for CI, and our user account finally got the necessary permissions to query quota information.

**Review by EmilienM — APPROVED** [review]
/lgtm
/approve

**Review by droslean — APPROVED** [review]

**Review by mandre — COMMENTED** [review]
/lgtm

**Pull request merged**
