### PR TITLE
SDCICD-149. Introduce 4.4 nightly integration jobs.

### PR DESCRIPTION
**Pull request by mdwn**
4.4 nightly integration jobs have been introduced.

### CODE REVIEW

**Comment by meowfaceman** [comment]
/hold
Until the 4.4 rehearsals can be inspected.

**Comment by meowfaceman** [comment]
/hold cancel
I removed the 4.4 -> 4.4 upgrade jobs because they're questionably useful when 4.4 isn't stable.

**Comment by jeremyeder** [comment]
> /hold cancel
> I removed the 4.4 -> 4.4 upgrade jobs because they're questionably useful when 4.4 isn't stable.

Is this because of the SDN issues causing etcd to fail?

**Comment by meowfaceman** [comment]
> > /hold cancel
> > I removed the 4.4 -> 4.4 upgrade jobs because they're questionably useful when 4.4 isn't stable.
> 
> Is this because of the SDN issues causing etcd to fail?

Right now this is only because the 4.4 nightly -> 4.4 nightly signal isn't particularly useful -- it's not a realistic upgrade path and doesn't produce any real useful signal.

**Pull request merged**
