### PR TITLE
USHIFT-1054 - MicroShift reboot test should not ignore wait error

### PR DESCRIPTION
**Pull request by copejon**
[USHIFT-1054](https://issues.redhat.com//browse/USHIFT-1054)

### CODE REVIEW

**Review by pacevedom — APPROVED** [review]
/lgtm

**Comment by copejon** [comment]
Right now it's failing due to some issue with pushing the job's built images into the registry.

**Comment by copejon** [comment]
New failures are to do with pulling in dependent registry images:
`
operator "cluster-network-operator" contained an invalid image-references file: no input image tag named "ovn-kubernetes"
`

**Comment by bbguimaraes** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.15-e2e-reboot

**Comment by copejon** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.12-e2e-reboot

**Comment by copejon** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.12-e2e-reboot

**Comment by copejon** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-reboot-arm

**Comment by copejon** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.15-e2e-reboot-arm
/pj-rehearse pull-ci-openshift-microshift-release-4.12-e2e-reboot

**Comment by copejon** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.12-e2e-reboot

**Comment by copejon** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.12-e2e-reboot

**Comment by copejon** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.12-e2e-reboot

**Comment by copejon** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.12-e2e-reboot

**Comment by copejon** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.12-e2e-reboot

**Comment by copejon** [comment]
pull-ci-openshift-microshift-release-4.12-e2e-reboot is complaining that there isn't sufficient room to schedule the test pod.  It's the only non-infra pod being created and the node has 10Gb available for LVs so something is confusing the scheduler.

**Comment by copejon** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.12-e2e-reboot

**Pull request merged**
