### PR TITLE
Add periodic for ocp-build-data-enforcer

### PR DESCRIPTION
**Pull request by alvaroaleman**
Requires
* https://github.com/openshift/release/pull/11050
* https://github.com/openshift/ci-tools/pull/1121

and a testrun via rehearsal.

Capped to one pr for now in case it causes issues.

### CODE REVIEW

**Comment by alvaroaleman** [comment]
Needs:
* https://github.com/openshift/ci-tools/pull/1127 so it can self-approve
* https://github.com/openshift/ci-tools/pull/1128 otherwise the diff is completely unreadable

**Comment by jupierce** [comment]
/hold
Sorry I missed that the dependencies finally merged. Unhold at will.

**Pull request merged**
