### PR TITLE
Serverless: Remove building stop-bundle

### PR DESCRIPTION
**Pull request by mgencur**
The stop bundle is not required anymore. We're using the regular serverless-bundle instead. This is a follow-up to https://github.com/openshift-knative/serverless-operator/pull/2034

### CODE REVIEW

**Comment by mgencur** [comment]
/pj-rehearse pull-ci-openshift-knative-serverless-operator-main-4.12-upgrade-tests-aws-ocp-412 pull-ci-openshift-knative-serverless-operator-main-4.12-upgrade-kitchensink-ocp-412

**Comment by mgencur** [comment]
Requires https://github.com/openshift-knative/serverless-operator/pull/2044

**Comment by mgencur** [comment]
/pj-rehearse pull-ci-openshift-knative-serverless-operator-main-4.12-upgrade-tests-aws-ocp-412 pull-ci-openshift-knative-serverless-operator-main-4.12-upgrade-kitchensink-ocp-412

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
