### PR TITLE
OCPQE-16458: Adding FIPS in agent CI: enable fips in amd platform jobs

### PR DESCRIPTION
**Pull request by zniu1011**

### CODE REVIEW

**Comment by zniu1011** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-sno-agent-ipv4-static-connected-f7

**Comment by jhou1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-sno-agent-ipv4-static-connected-f7

**Comment by jhou1** [comment]
/lgtm

I have not seen a successful install(resource issue), @zniu1011 please continue to test this until you have a succesful install.

**Comment by zniu1011** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-sno-agent-ipv4-static-connected-f7

**Pull request merged**
