### PR TITLE
Expand plugins for openshift-acme

### PR DESCRIPTION
**Pull request by tnozicka**

### CODE REVIEW

**Comment by tnozicka** [comment]
```
{"component":"checkconfig","error":"invalid plugin configuration:\n\tunknown plugin: branchcleaner\n\tunknown plugin: needs-rebase","level":"fatal","msg":"Error loading Prow plugin config.","time":"2019-01-16T10:04:56Z"}
```
are we disabling the plugins on purpose or just missing an update from upstream?

**Comment by petr-muller** [comment]
> ```
> {"component":"checkconfig","error":"invalid plugin configuration:\n\tunknown plugin: branchcleaner\n\tunknown plugin: needs-rebase","level":"fatal","msg":"Error loading Prow plugin config.","time":"2019-01-16T10:04:56Z"}
> ```
> 
> are we disabling the plugins on purpose or just missing an update from upstream?

I think it's the latter.

**Comment by stevekuznetsov** [comment]
Fixed the image behind that test but I can't reproduce the error seen in the test, locally. Hrm.

**Pull request merged**
