### PR TITLE
CONSOLE-3303: Move plugin template to the openshift GitHub org - Remove unused docker file, nodejs:16 and ngnix images mirroring for console plugin template 

### PR DESCRIPTION
**Pull request by cajieh**

### CODE REVIEW

**Comment by hongkailiu** [comment]
/hold

Is the dockerfile used somewhere?

Trying to figure out
https://redhat-internal.slack.com/archives/CBN38N3MW/p1677009004937119?thread_ts=1676576122.666999&cid=CBN38N3MW

**Comment by cyril-ui-developer** [comment]
@smg247 @hongkailiu I have removed the unused Dockerfile. Also, removed the nodejs:16 and nginx images mirroring changes since we'll not be using them again. 
PTAL.

**Pull request merged**
