### PR TITLE
Change facility to metro

### PR DESCRIPTION
**Pull request by sgoveas**
facility will be deprecated from Dec 1, 2023

### CODE REVIEW

**Comment by derekhiggins** [comment]
/test periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

Is metro supported by the ansible playbook?

**Comment by derekhiggins** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by derekhiggins** [comment]
It failed, I ran part of it locally and got the following error (with no_log: set to false)

> fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (packet_device) module: metro. Supported parameters include: always_pxe, auth_token, count, count_offset, device_ids, facility, features, hostnames, ipxe_script_url, locked, operating_system, plan, project_id, state, tags, user_data, wait_for_public_IPv, wait_timeout (lock, name)."}

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-baremetalds-ipi-ovn-ipv4-f4

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-hostname-change

**Comment by pamoedom** [comment]
Hi @derekhiggins, my 2 cents:
I can see the "metro" parameter present within the [equinix.cloud](https://github.com/equinix-labs/ansible-collection-equinix/) ansible collection but not within the legacy [equinix.metal](https://github.com/equinix/ansible-collection-metal), I think is time to transition to the new collection and start using the "metro" parameter ASAP, in TF they have disabled it since past Dec, I suppose they'll do the same in Ansible in short time. Also note that the use of "facility" could cause unexpected issues at API level, they are deprecating it everywhere.

**Comment by sgoveas** [comment]
Started a new PR #48680

**Pull request closed without merging**
