### PR TITLE
Make it so that we can build based on branch dynamically from prow

### PR DESCRIPTION
**Pull request by smarterclayton**
The presence of an "artifacts" label on the job in postsubmits is enough metadata for
us to decide to build it. Look at all the repos, then find the ones with jobs with
artifacts for that branch.

@stevekuznetsov prow config as source of truth for automation has appeal to me (you must have a prow build job in order to get images pushed, etc).

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
What is this? Run a subset of postsubmits when a new branch is pushed? Is this trying to work around the lack of "publishing postsubmit" jobs in Prow? Can we just add those? This is like six levels of indirection away from the code I've ever read...

**Comment by smarterclayton** [comment]
It's not working around anything.  It's rerunning all jobs tagged a certain way.  Either way, it's treating prow config as authoritative.  We'll have other reasons to do that.

**Comment by smarterclayton** [comment]
Independent of this, yes, we still need to solve "how do I run the jobs on the latest, not on the newest".

**Comment by smarterclayton** [comment]
For right now, when we branch for 4.0 `hack/branch` and `hack/branch-build` will be what I use to automate that.

**Pull request merged**
