### PR TITLE
add periodic-ci-stackrox-stackrox-master-ocp-4-17-lp-interop-acs-tests-aws

### PR DESCRIPTION
**Pull request by amp-rh**
[INTEROP-7438](https://issues.redhat.com/browse/INTEROP-7438)

### CODE REVIEW

**Comment by amp-rh** [comment]
/pj-rehearse periodic-ci-stackrox-stackrox-master-ocp-4-17-lp-interop-acs-tests-aws

**Comment by amp-rh** [comment]
/pj-rehearse periodic-ci-stackrox-stackrox-master-ocp-4-17-lp-interop-acs-tests-aws

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
