### PR TITLE
BYOR 4.0: test RHEL nodes scaleup in AWS

### PR DESCRIPTION
**Pull request by vrutkovs**
This adds a new template and job definition to test RHEL nodes scaleup in 4.0 cluster.

### CODE REVIEW

**Comment by mtnbikenc** [comment]
@vrutkovs Can we use the 'rehearsal' process demoed last week to test this new job?

**Comment by vrutkovs** [comment]
That requires existing template - and code committed in `devel-40`.

It tested this manually - and the playbook starts correctly. The nodes didn't join though, might be crio issue

**Pull request merged**
