### PR TITLE
[INTEROP-7408] Remove RE_TRIGGER from ocp  4.16 config env.

### PR DESCRIPTION
**Pull request by dfrazzette**
Remove `RE_TRIGGER_ON_FAILURE: "true"` from config env.

### CODE REVIEW

**Comment by dfrazzette** [comment]
/pj-rehearse periodic-ci-quay-quay-tests-master-ocp-416-quay-quay-e2e-tests-quay311-ocp416-lp-interop

**Comment by dfrazzette** [comment]
/pj-rehearse periodic-ci-quay-quay-tests-master-ocp-416-quay-quay-e2e-tests-quay311-ocp416-lp-interop

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
