### PR TITLE
Checkout test branch test driver for kubevirt csi

### PR DESCRIPTION
**Pull request by awels**
Instead of always checking out the test driver from the master branch, see if the git commit hash exists and attempt to check it out. If that doesn't exist, fall back to the master branch.

### CODE REVIEW

**Comment by awels** [comment]
/pj-rehearse pull-ci-openshift-kubevirt-csi-driver-master-e2e-kubevirt-aws-csi

**Comment by awels** [comment]
/pj-rehearse pull-ci-openshift-kubevirt-csi-driver-master-e2e-kubevirt-aws-csi

**Comment by awels** [comment]
/pj-rehearse pull-ci-openshift-kubevirt-csi-driver-master-e2e-kubevirt-aws-csi

**Comment by awels** [comment]
/pj-rehearse pull-ci-openshift-kubevirt-csi-driver-master-e2e-kubevirt-aws-csi

**Review by davidvossel — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
