### PR TITLE
add aggregated job for gcp ovn rt

### PR DESCRIPTION
**Pull request by eggfoobar**
Replacing gcp ovn, with gcp ovn rt aggregated job

### CODE REVIEW

**Comment by dgoodwin** [comment]
/hold

Need to make sure everyone's on board before this goes in.

The job it's replacing has a pass rate of 60%, the new job is about 40% (and possibly climbing). Not sure how much this matters given we're focusing on individual test pass rate when we go aggregated, but it's worth noting.

[rt job](https://sippy.dptools.openshift.org/sippy-ng/jobs/4.11/analysis?filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22periodic-ci-openshift-release-master-ci-4.11-upgrade-from-stable-4.10-e2e-gcp-ovn-rt-upgrade%22%7D%5D%7D)

[orig job](https://sippy.dptools.openshift.org/sippy-ng/jobs/4.11/analysis?filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22periodic-ci-openshift-release-master-ci-4.11-upgrade-from-stable-4.10-e2e-gcp-ovn-upgrade%22%7D%5D%7D)

Top failing tests look somewhat similar.

**Comment by dgoodwin** [comment]
Via scrum Egli is going to investigate if we can get funding to run both aggregated.

**Comment by eggfoobar** [comment]
Reached out to @sudhaponnaganti , we are okay to turn this on for a month with out replacing a pre-existing job, reaching out for long term confirmation on funding

**Comment by dgoodwin** [comment]
ok this is a LGTM from TRT then, but we need someone who can confirm the config is accurate and will work.

**Review by bradmwilliams — APPROVED** [review]

**Pull request merged**
