### PR TITLE
Correcting built_root for e2e

### PR DESCRIPTION
**Pull request by vishnuchalla**
### Description
Changing built_root to python as we plan to have some python packages to be installed. Also we plan to clone our source code inside the container.

### CODE REVIEW

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-cloud-bulldozer-e2e-benchmarking-master-images

**Comment by vishnuchalla** [comment]
/ph-rehearse pull-ci-cloud-bulldozer-e2e-benchmarking-master-unit

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-cloud-bulldozer-e2e-benchmarking-master-images

**Review by jtaleric — APPROVED** [review]
/lgtm

**Pull request merged**
