### PR TITLE
[WIP] Test Jaeger on ARM cluster.

### PR DESCRIPTION
**Pull request by IshwarKanse**

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-ocp-4.14-arm64-jaeger-e2e-tests

**Review by frzifus — APPROVED** [review]

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-ocp-4.14-arm64-jaeger-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-ocp-4.14-arm64-jaeger-e2e-tests

**Review by iblancasa — APPROVED** [review]

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-ocp-4.14-arm64-jaeger-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-ocp-4.14-arm64-jaeger-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-ocp-4.14-arm64-jaeger-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-ocp-4.14-arm64-jaeger-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-ocp-4.14-arm64-jaeger-e2e-tests

**Comment by IshwarKanse** [comment]
Closing this one out in favor of https://github.com/openshift/release/pull/44106 which is already merged.

**Pull request closed without merging**
