### PR TITLE
Create SA for Integration QE

### PR DESCRIPTION
**Pull request by apodhrad**
Signed-off-by: Andrej Podhradsky <apodhrad@redhat.com>

### CODE REVIEW

**Comment by apodhrad** [comment]
Hello,

first of all, I'm sorry if I missed something.
My goal is to create a service account (without token expiration) for Integration QE (QE for RH Integration products).

Please help me to proceed with this process as I did not find any official guide how to do it.

**Comment by droslean** [comment]
Hello @apodhrad, Here it is unclear where you want to use this serviceAccount. Also, what do you mean 'without token expiration'? Either way, there is no automation to create the service account after this will be merged. We will have to do this manually. In addition, you should be aware that we are planning to deprecate that cluster.

**Comment by petr-muller** [comment]
> Here it is unclear where you want to use this serviceAccount. Also, what do you mean 'without token expiration'?

I assume they want to pull images, not relying on expiring personal tokens. SAs

> Either way, there is no automation to create the service account after this will be merged. We will have to do this manually..

That's incorrect. This will be normally created by `applyconfig` why wouldn't it?

> In addition, you should be aware that we are planning to deprecate that cluster.

That's a good point - for now this should not block anything but I'll ask @hongkailiu if there's something that needs to be done w.r.t. the migration.

**Review by petr-muller — APPROVED** [review]

**Comment by apodhrad** [comment]
Hi @droslean @petr-muller I'm sorry for the delay (I had sick days plus there was a public holiday).
Yes, I want such a service account for pulling images in Jenkins jobs.

Thanks for merging this. If I understand it correctly, now we have a service account definition. Next step should to obtain the token. Could you help me how I can to that, please?

**Comment by petr-muller** [comment]
https://cookbook.openshift.org/accessing-an-openshift-cluster/how-can-i-create-a-service-account-for-scripted-access.html

**Comment by petr-muller** [comment]
If there's further assistance needed, please ping `@dptp-helpdesk` on #forum-testplatform Slack channel

**Comment by apodhrad** [comment]
Hi @petr-muller thank you very much! That's exactly what I was looking for.

**Pull request merged**
