### PR TITLE
SRVCLI-314 knative-client - use pooled clusters

### PR DESCRIPTION
**Pull request by mgencur**
https://issues.redhat.com/browse/SRVCLI-314

### CODE REVIEW

**Comment by dsimansk** [comment]
/approve
/lgtm

Adding hold to let the rehearsal job finish first.
/hold

**Comment by mgencur** [comment]
@dsimansk the release-next/48-e2e-aws-ocp check is supposed to fail. The change are not yet on the release-next branch (only on main)

**Comment by dsimansk** [comment]
Roger, roger!
/hold cancel

**Pull request merged**
