### PR TITLE
Migrate origin-installer-e2e-aws-upgrade-4* jobs away from api.ci

### PR DESCRIPTION
**Pull request by hongkailiu**
https://issues.redhat.com/browse/DPTP-2034

/cc @petr-muller @smarterclayton

### CODE REVIEW

**Comment by hongkailiu** [comment]
/hold

rehearsing ...

**Comment by hongkailiu** [comment]
Need to figure out

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/16437/rehearse-16437-release-openshift-origin-installer-e2e-aws-upgrade-4.1-to-4.2-to-4.3-to-4.4-nightly/1367116132976168960#1:build-log.txt%3A122

**Review by petr-muller — APPROVED** [review]
Looks safe

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
