### PR TITLE
make ref use installer created namespaces.

### PR DESCRIPTION
**Pull request by ascerra**
- Change application_root_namespace to rhtap-app
- Remove call to create-creds.sh script that is being removed in this PR https://github.com/redhat-appstudio/rhtap-e2e/pull/11

### CODE REVIEW

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-rhtap-installer-main-rhtap-installer-e2e-nightly

**Review by xinredhat — APPROVED** [review]

**Pull request merged**
