### PR TITLE
add a nutanix e2e test to the cluster-autoscaler-operator

### PR DESCRIPTION
**Pull request by elmiko**
this test is optional and not run by default, it is being added to help us with platform specific testing options for the cao.

### CODE REVIEW

**Comment by elmiko** [comment]
this is being added to help confirm https://github.com/openshift/cluster-autoscaler-operator/pull/275

@JoelSpeed ptal

**Comment by elmiko** [comment]
i'm trying to run the make commands specified in the output (`make jobs` and `make ci-operator-config`, but i just get permission denied errors.

**Comment by JoelSpeed** [comment]
/pj-rehearse ack

I can't type

**Pull request merged**
