### PR TITLE
update knative func owners file

### PR DESCRIPTION
**Pull request by jrangelramos**

### CODE REVIEW

**Review by lkingland — APPROVED** [review]

**Review by dsimansk — APPROVED** [review]
/approve
/lgtm
/approve
/lgtm

**Comment by dsimansk** [comment]
I'd just add @matzew for now, and follow-up with another PR. WDYT? Even though it's pretty old PR. It's good idea to update OWNERS.

**Review by lkingland — APPROVED** [review]

**Comment by lkingland** [comment]
> @jrangelramos if we want to proceed @lkingland needs to be member of the org.

I am not seeing an invite to the "openshift" org; only was added to "openshift-knative".  Let me know if you want to proceed that way and I'll keep an eye on my inbox

**Pull request closed without merging**
