### PR TITLE
MSI: Random cluster names

### PR DESCRIPTION
**Pull request by rnetser**

### CODE REVIEW

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-cluster-install-uninstall-cluster-install-uninstall-hypershift-4-13-candidate-rand-name

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-cluster-install-uninstall-cluster-install-uninstall-hypershift-4-13-candidate-rand-name

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-cluster-install-uninstall-cluster-install-uninstall-hypershift-4-13-candidate

**Review by myakove — APPROVED** [review]

**Pull request merged**
