### PR TITLE
hook: supply an explicit tracker ID

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @alvaroaleman 
requires https://github.com/kubernetes/test-infra/pull/19711 to merge
/hold

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
From the API today, we see this external bug link:

```json
        {
          "ext_description": "Bug 1891555: Create Windows version information",
          "ext_bz_id": 131,
          "ext_priority": "None",
          "bug_id": 1693865,
          "ext_bz_bug_id": "openshift/oc/pull/623",
          "id": 1639940,
          "ext_status": "closed",
          "type": {
            "must_send": false,
            "can_send": false,
            "description": "Github",
            "can_get": true,
            "url": "https://github.com/",
            "id": 131,
            "send_once": false,
            "type": "GitHub",
            "full_url": "https://github.com/%id%"
          }
        },
```

**Review by alvaroaleman — APPROVED** [review]
/hold
until the t-i change is deployed

**Comment by stevekuznetsov** [comment]
/hold cancel
deployed in https://github.com/openshift/release/pull/13142

**Pull request merged**
