### PR TITLE
Update NVIDIA GPU operator tests with 23.9

### PR DESCRIPTION
**Pull request by empovit**
* Add v23.9.x to the test matrix
* Remove v1.11.x and v22.9.x due to EOL

### CODE REVIEW

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.13-nvidia-gpu-operator-e2e-23-9-x

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.11-nvidia-gpu-operator-e2e-23-9-x
/pj-rehearse periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.12-nvidia-gpu-operator-e2e-23-9-x

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.12-nvidia-gpu-operator-e2e-23-9-x

**Comment by sagidayan** [comment]
@empovit do we know if this can be merged or not?

**Pull request merged**
