### PR TITLE
OCPQE-20152 disable baremetalds-ipi-ovn-dualstack-primaryv6 and barem…

### PR DESCRIPTION
**Pull request by ming1013**
Disable upgrade job with baremetalds-ipi-ovn-dualstack-primaryv6 and baremetalds-ipi-ovn-ipv6-fips profile
 cc @jiajliu @jianlinliu @shellyyang1989 @JianLi-RH PTAL, thank you!

### CODE REVIEW

**Comment by shellyyang1989** [comment]
Hi Ming, we need to drop it from config (ci-operator/config/openshift/openshift-tests-private/) and then run make update.

**Comment by ming1013** [comment]
> Hi Ming, we need to drop it from config (ci-operator/config/openshift/openshift-tests-private/) and then run make update.

Thanks. @shellyyang1989 I added config files update, but met error when make update, will check more

**Comment by jianlinliu** [comment]
cc @liangxia to review.

**Pull request merged**
