### PR TITLE
templates: migrate openshift_installer_upi: gcp

### PR DESCRIPTION
**Pull request by petr-muller**

### CODE REVIEW

**Review by stevekuznetsov — APPROVED** [review]

**Comment by petr-muller** [comment]
/hold
Rehearsals look fishy

**Comment by petr-muller** [comment]
ci/rehearse/openshift/installer/release-4.3/e2e-gcp-upi 
```
2020/12/08 12:42:33 Executing pod "e2e-gcp-upi-upi-conf-gcp"
2020/12/08 12:42:38 Container cp-secret-wrapper in pod e2e-gcp-upi-upi-conf-gcp completed successfully
~/installer /output
Emptying the compute pool...
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: No module named yaml 
```

Looks incompatible with the workflow

**Comment by petr-muller** [comment]
ci/rehearse/openshift/installer/release-4.4/e2e-gcp-upi

Failure 1:
```
level=fatal msg="failed to fetch Master Machines: failed to generate asset \"Master Machines\": failed to fetch availability zones: failed to list zones: googleapi: Error 403: Required 'compute.zones.list' permission for 'projects/openshift-gce-devel-ci', forbidden"
```

Failure 2
```
ERROR: (gcloud.projects.add-iam-policy-binding) Resource in projects [openshift-gce-devel-ci:setIamPolicy] is the subject of a conflict: There were concurrent policy changes. Please retry the whole read-modify-write with exponential backoff.
```

**Comment by petr-muller** [comment]
Meh, the 4.3 job works when template-based (https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/14160/rehearse-14160-pull-ci-openshift-installer-release-4.3-e2e-gcp-upi/1336297272748544000)

So we'd break it if we migrated, but it's a little annoying to investigate and fix something for a 4.3 job

**Comment by stevekuznetsov** [comment]
How is the base image different so as to require `pip install` ?

**Comment by petr-muller** [comment]
@stevekuznetsov the image that runs the step is `upi-installer`, which has three inputs, versions of which evolved over time (and very likely the `Dockerfile.upi.ci` did too.

```
- dockerfile_path: images/installer/Dockerfile.upi.ci
  from: base
  inputs:
    ocp_4.1_cli:
      as:
      - registry.svc.ci.openshift.org/ocp/4.1:cli
    ocp_builder_golang-1.12:
      as:
      - registry.svc.ci.openshift.org/ocp/builder:golang-1.12
  to: upi-installer
```

**Pull request merged**
