### PR TITLE
Use correct tags for go 1.22 image

### PR DESCRIPTION
**Pull request by vbnrh**

### CODE REVIEW

**Comment by vbnrh** [comment]
/pj-rehearse pull-ci-red-hat-storage-odf-multicluster-orchestrator-main-integration-test
/pj-rehearse pull-ci-red-hat-storage-odf-multicluster-orchestrator-main-unit-test

**Comment by vbnrh** [comment]
/pj-rehearse pull-ci-red-hat-storage-odf-multicluster-orchestrator-main-unit-test

**Review by umangachapagain — APPROVED** [review]
/lgtm

**Pull request merged**
