### PR TITLE
Move jobs back to build01

### PR DESCRIPTION
**Pull request by hongkailiu**
/hold

Wait for upgrade of b01.

/cc @openshift/openshift-team-developer-productivity-test-platform

### CODE REVIEW

**Comment by petr-muller** [comment]
/lgtm

Let's make sure we run rehearsals *after* b01 upgrades and before merge.

**Comment by hongkailiu** [comment]
No failures of the rehearsals look like

```
the following tags from the release could not be imported
```

/hold cancel

**Pull request merged**
