### PR TITLE
github-ldap-user-group-creator manages group/openshift-priv-admins

### PR DESCRIPTION
**Pull request by hongkailiu**
https://github.com/openshift/ci-tools/pull/2699

/cc @openshift/test-platform 

Delete those after merging

```console
oc --context app.ci get group openshift-priv-admins-workaround
oc --context app.ci get sa group-auto-updater -n ci 
oc --context app.ci get ClusterRole groups-getter-updater
oc --context app.ci get ClusterRoleBinding groups-getter-updater-bind
```

### CODE REVIEW

**Comment by hongkailiu** [comment]
/hold

wait for https://github.com/openshift/ci-tools/pull/2699

**Review by droslean — APPROVED** [review]

**Comment by hongkailiu** [comment]
The group is managed now.

```console
oc get group openshift-priv-admins --show-labels
NAME                    USERS                                                                                                                                                                                                            LABELS
openshift-priv-admins   <kerberos-ids>  dptp.openshift.io/requester=github-ldap-user-group-creator
```

Clean up:

```console
oc --context app.ci delete group openshift-priv-admins-workaround --as system:admin
group.user.openshift.io "openshift-priv-admins-workaround" deleted

oc --context app.ci delete sa group-auto-updater -n ci  --as system:admin
serviceaccount "group-auto-updater" deleted

oc --context app.ci delete ClusterRole groups-getter-updater --as system:admin
clusterrole.rbac.authorization.k8s.io "groups-getter-updater" deleted

oc --context app.ci delete ClusterRoleBinding groups-getter-updater-bind --as system:admin
clusterrolebinding.rbac.authorization.k8s.io "groups-getter-updater-bind" deleted
```

**Pull request merged**
