### PR TITLE
CNO: bump go 1.23 / lint

### PR DESCRIPTION
**Pull request by fedepaol**
Bumping the golangci-lint version so it won't explode with go 1.23

### CODE REVIEW

**Comment by fedepaol** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-e2e-aws-hypershift-ovn-kubevirt

**Comment by jcaamano** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-e2e-gcp-ovn

**Comment by jcaamano** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-e2e-gcp-ovn

**Comment by jcaamano** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-verify

**Comment by jcaamano** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-lint

**Comment by jcaamano** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-images

**Comment by jcaamano** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-unit

**Comment by jcaamano** [comment]
@fedepaol 

```
dockerimage.image.openshift.io "quay.io/openshift/ci:ci_golangci-lint_v1.62.0" not found, dockerimage.image.openshift.io "quay-proxy.ci.openshift.org/openshift/ci:ci_golangci-lint_v1.62.0" not found
```

I guess we will need to mirror it:
https://github.com/openshift/release/blob/857cf23e2e7dd1a47b6825dc50f9038519bd4eba/core-services/image-mirroring/_config.yaml#L704-L707

**Comment by fedepaol** [comment]
> @fedepaol
> 
> ```
> dockerimage.image.openshift.io "quay.io/openshift/ci:ci_golangci-lint_v1.62.0" not found, dockerimage.image.openshift.io "quay-proxy.ci.openshift.org/openshift/ci:ci_golangci-lint_v1.62.0" not found
> ```
> 
> I guess we will need to mirror it:
> 
> https://github.com/openshift/release/blob/857cf23e2e7dd1a47b6825dc50f9038519bd4eba/core-services/image-mirroring/_config.yaml#L704-L707

Not sure about that because we are consuming the one from ci registry:
```
  golangci-lint:
    name: golangci-lint
    namespace: ci
    tag: v1.62.0
```


Like, that statement should be for mirroring what we have on ci from quay, not the other way around. Let me try to ask around first.

**Comment by fedepaol** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-lint

**Comment by fedepaol** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-lint

**Comment by fedepaol** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-lint

**Comment by fedepaol** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-lint

**Comment by fedepaol** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-lint

**Pull request merged**
