### PR TITLE
Periodics: add upgrade jobs for AWS compact clusters

### PR DESCRIPTION
**Pull request by vrutkovs**
Add periodic jobs to verify compact clusters can be safely upgraded

### CODE REVIEW

**Comment by vrutkovs** [comment]
/hold

for rehearsals

**Comment by vrutkovs** [comment]
4.6 -> 4.7 passed

/retest

**Comment by vrutkovs** [comment]
/hold cancel

Ready for review

**Review by wking — APPROVED** [review]
```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/17879/rehearse-17879-periodic-ci-openshift-release-master-ci-4.8-upgrade-from-stable-4.7-e2e-aws-compact-upgrade/1384499948774494208/artifacts/e2e-aws-compact-upgrade/gather-extra/artifacts/clusterversion.json | jq -r '.items[].status.history[] | .startedTime + " " + (.completionTime // "-") + " " + .state + " " + .version'
2021-04-20T14:16:54Z 2021-04-20T15:18:55Z Completed 4.8.0-0.ci-2021-04-20-092252
2021-04-20T13:40:53Z 2021-04-20T14:13:13Z Completed 4.7.7
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/17879/rehearse-17879-periodic-ci-openshift-release-master-ci-4.8-upgrade-from-stable-4.7-e2e-aws-compact-upgrade/1384499948774494208/artifacts/e2e-aws-compact-upgrade/gather-extra/artifacts/nodes.json | jq -r '.items[].metadata.name'
ip-10-0-137-239.ec2.internal
ip-10-0-186-182.ec2.internal
ip-10-0-237-134.ec2.internal
```

/lgtm

**Pull request merged**
