### PR TITLE
Add OWNERS to acs-fleet-manager and remove unused ones

### PR DESCRIPTION
**Pull request by SimonBaeumer**
@dhaus67 
@mtodor 
@ivan-degtiarenko

### CODE REVIEW

**Comment by mtesseract** [comment]
This file is auto-generated (see header). You can change this in the target repo now.
(Only for initial integration we had to provide OWNERS file into the openshift/release repo.

**Comment by matzew** [comment]
I think it's also helpful to have the some on the actual generated `jobs`

https://github.com/openshift/release/blob/88761bac73992b0216a4822b0278cf919971a803/ci-operator/jobs/stackrox/acs-fleet-manager/OWNERS

**Comment by SimonBaeumer** [comment]
Closing, is replaced with: https://github.com/stackrox/acs-fleet-manager/pull/192

**Pull request closed without merging**
