### PR TITLE
4.18 expansion of camelk

### PR DESCRIPTION
**Pull request by vi-patel**
add FIREWATCH_DEFAULT_JIRA_ASSIGNEE
update cron
create .config.prowgen file for slack reporting of results being auto-created with make updates

### CODE REVIEW

**Comment by vi-patel** [comment]
replaces PR#57605, which had issues after succusseful rebasing on passing the prow config checks.

**Comment by vi-patel** [comment]
both fips and non-fips scenarios were run successfully on PR#57605, reusing the same files.

**Comment by dfrazzette** [comment]
Passing rehearsal jobs:
- [1843701674024112128](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/57605/rehearse-57605-periodic-ci-jboss-fuse-camel-k-test-container-main-camel-k-ocp4.18-lp-interop-camel-k-interop-aws-fips/1843701674024112128) - FIPS
- [1843674556980531200](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/57605/rehearse-57605-periodic-ci-jboss-fuse-camel-k-test-container-main-camel-k-ocp4.18-lp-interop-camel-k-interop-aws/1843674556980531200) - non-FIPS

**Pull request merged**
