### PR TITLE
add cucushift-installer-check into azure-stack and azure-mag install chain

### PR DESCRIPTION
**Pull request by jinyunma**
as title

### CODE REVIEW

**Comment by jinyunma** [comment]
cc @gpei @jianlinliu to review

**Comment by jianlinliu** [comment]
@danwinship @JacobTanenbaum the PR did not change anything on ovn-kubernates part, but robot told us pre-check failed, have to run `make jobs`, after that, there is some change on ovn-kubernates jobs, can you help review it?

**Pull request merged**
