### PR TITLE
[CVP-3781]: Added timestamp in all CVP scripts echoing output into logs

### PR DESCRIPTION
**Pull request by maneeshmehra**

### CODE REVIEW

**Comment by asergienk** [comment]
/pj-rehearse periodic-ci-redhat-openshift-ecosystem-cvp-ocp-4.16-cvp-common-claim

**Comment by maneeshmehra** [comment]
/pj-rehearse periodic-ci-redhat-openshift-ecosystem-cvp-ocp-4.16-cvp-common-claim

**Comment by maneeshmehra** [comment]
/pj-rehearse periodic-ci-redhat-openshift-ecosystem-cvp-ocp-4.16-cvp-common-claim

**Comment by maneeshmehra** [comment]
/pj-rehearse periodic-ci-redhat-openshift-ecosystem-cvp-ocp-4.16-cvp-common-claim

**Comment by maneeshmehra** [comment]
/pj-rehearse periodic-ci-redhat-openshift-ecosystem-cvp-ocp-4.16-cvp-common-claim

**Comment by asergienk** [comment]
/pj-rehearse periodic-ci-redhat-openshift-ecosystem-cvp-ocp-4.16-cvp-common-claim

**Comment by maneeshmehra** [comment]
/pj-rehearse periodic-ci-redhat-openshift-ecosystem-cvp-ocp-4.16-cvp-common-claim

**Comment by asergienk** [comment]
lgtm, @nmars @samvarankashyap ptal

**Comment by maneeshmehra** [comment]
/pj-rehearse periodic-ci-redhat-openshift-ecosystem-cvp-ocp-4.16-cvp-common-claim

**Review by samvarankashyap — APPROVED** [review]
lgtm

**Pull request merged**
