### PR TITLE
Add Prow CI support for ABI dual-stack configs using DHCP

### PR DESCRIPTION
**Pull request by bmanzari**
Add Prow CI support for ABI dual-stack configs using DHCP

### CODE REVIEW

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-agent-baremetal-sno-dualstack-dynamic-connected

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-agent-baremetal-sno-dualstack-dynamic-connected

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-agent-baremetal-sno-dualstack-dynamic-connected

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-agent-baremetal-sno-dualstack-dynamic-connected

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-agent-baremetal-sno-dualstack-dynamic-connected

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-agent-baremetal-sno-dualstack-dynamic-connected

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-agent-baremetal-sno-dualstack-dynamic-connected

**Comment by jhou1** [comment]
Thank you, Biagio

Are the following lines telling the program to create a dual stack clusters?
```
      INTERNAL_NET_CIDR: 192.168.90.0/24
      INTERNAL_NET_CIDR_V6: 2620:52:0:1eb::0/64
      ipv4_enabled: "true"
      ipv6_enabled: "true"
```

**Comment by jhou1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-agent-baremetal-sno-dualstack-dynamic-connected

**Comment by jhou1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-agent-baremetal-sno-dualstack-dynamic-connected

**Comment by jhou1** [comment]
Needs rebase

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-agent-baremetal-sno-dualstack-dynamic-connected

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-agent-baremetal-sno-dualstack-dynamic-disconnected

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-agent-baremetal-sno-dualstack-dynamic-connected

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-agent-baremetal-sno-dualstack-dynamic-connected

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-sno-dualstack-dynamic-connected

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-sno-dualstack-dynamic-connected

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-sno-dualstack-dynamic-connected

**Comment by jhou1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-sno-dualstack-dynamic-connected

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-agent-baremetal-sno-dualstack-dynamic-connected

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-agent-baremetal-sno-dualstack-dynamic-connected

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-agent-baremetal-sno-dualstack-dynamic-connected

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-agent-baremetal-sno-dualstack-dynamic-connected

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-agent-baremetal-sno-dualstack-dynamic-connected

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-agent-baremetal-sno-dualstack-dynamic-connected

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-agent-baremetal-sno-dualstack-dynamic-connected

**Pull request closed without merging**
