### PR TITLE
openstack: fix logic on performanceprofile for 4.9 & 4.10

### PR DESCRIPTION
**Pull request by EmilienM**
The logic was recently changed and I forgot to update the operator, to
OR instead of AND.

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
Looks sane to me.
/lgtm
/hold for CI

**Comment by EmilienM** [comment]
It's doing what we want:
* On 4.9: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/28239/rehearse-28239-periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.9-e2e-openstack-nfv-intel/1520131498626256896/artifacts/e2e-openstack-nfv-intel/openstack-provision-performanceprofile/build-log.txt
* On 4.11: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/28239/rehearse-28239-periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.11-e2e-openstack-nfv-hwoffload/1520131498450096128/artifacts/e2e-openstack-nfv-hwoffload/openstack-provision-performanceprofile/build-log.txt

/hold cancel

**Pull request merged**
