### PR TITLE
add descheduer-operator to CI

### PR DESCRIPTION
**Pull request by sjenning**
@ravisantoshgudimetla @derekwaynecarr

### CODE REVIEW

**Comment by ravisantoshgudimetla** [comment]
> the following orgs or repos enable the approve plugin but do not require the approved label for merging

The above is the error I am seeing. Do we need to enable branch protection with labels or something like that?

**Comment by petr-muller** [comment]
> The above is the error I am seeing. Do we need to enable branch protection with labels or something like that?

No, it's not related to branch protection. It warns because you configured Tide (=automated merges) to merge PRs with just the `lgtm` label, ignoring the `approved` label, which does not make sense when you have approve plugin enabled. So either:

1. Do not enable approve plugin (=remove [this](https://github.com/openshift/release/pull/1988/files#diff-5da33c7edc88b9ba312e0e1eda240a8f))
2. Include your repo into the list of repos for which Tide cares about `approved` label. Simply put, put your repo [here](https://github.com/openshift/release/blob/master/cluster/ci/config/prow/config.yaml#L65) instead of [here](https://github.com/openshift/release/blob/master/cluster/ci/config/prow/config.yaml#L147) (see the `labels/missingLabels` fields to see the conditions for Tide to merge the PR)

**Comment by sjenning** [comment]
thanks @petr-muller.  updated.  all green now.

**Pull request merged**
