### PR TITLE
OCPQE-16532: fix jsonpath issue by using oc

### PR DESCRIPTION
**Pull request by jinyunma**
Get below error by using oc 4.4 and previous versions when query release version with jsonpath
https://github.com/openshift/release/blob/master/ci-operator/step-registry/ipi/install/install/ipi-install-install-commands.sh#L9
```
$ ./oc adm release info quay.io/openshift-release-dev/ocp-release@sha256:9ff90174a170379e90a9ead6e0d8cf6f439004191f80762764a5ca3dbaab01dc -o "jsonpath={.metadata.version}"
error: --output only supports 'name', 'json', 'pullspec', or 'digest'
```

Failed job: https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-4.14-upgrade-from-stable-4.3-azure-ipi-f30/1694503533480513536#1:build-log.txt%3A138

### CODE REVIEW

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-4.14-upgrade-from-stable-4.3-azure-ipi-f30

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-4.14-upgrade-from-stable-4.3-azure-ipi-f30

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-4.14-upgrade-from-stable-4.3-azure-ipi-f30

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-4.14-upgrade-from-stable-4.3-azure-ipi-f30

**Comment by jinyunma** [comment]
cc @jianlinliu @jhou1 @jiajliu @shellyyang1989 to review if my change is acceptable, then I will launch more job to check the update.

installation is passed for failed place from [job](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/42630/rehearse-42630-periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-4.14-upgrade-from-stable-4.3-azure-ipi-f30/1696450631339872256)
```
Release payload version: 4.3.40
error: --output only supports 'name', 'json', 'pullspec', or 'digest'
skip get architecture in .metadata.metadata["release.openshift.io/architecture"]
Payload architecture not found in .metadata.metadata["release.openshift.io/architecture"], using .config.architecture
error: --output only supports 'name', 'json', 'pullspec', or 'digest'
skip getting architecture in .config.architecture
Release payload architecture: amd64
Original channel from CVO manifest: stable-4.3
Matching candidate channel: candidate-4.3
Querying https://api.integration.openshift.com/api/upgrades_info/graph?channel=candidate-4.3&arch=amd64 for version 4.3.40
Version 4.3.40 is available in candidate-4.3, cluster can query OpenShift Update Service (OSUS/Cincinnati)
Setting channel to candidate-4.3 and upstream to https://api.integration.openshift.com/api/upgrades_info/graph
```

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-4.14-upgrade-from-stable-4.3-azure-ipi-f30

**Comment by jianlinliu** [comment]
The job failed because api url become unavailable after ~12 hours.
```
[36mINFO[0m[2023-08-30T02:00:16Z] Step azure-ipi-f30-cucushift-chainupgrade-toimage failed after 12h52m52s. 
```
Seem like DPP pruner cleaned up the cluster after 12 hours.

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.13-installer-rehearse-gcp

**Pull request merged**
