### PR TITLE
ComplianceAsCode: Add run_if_changed statements

### PR DESCRIPTION
**Pull request by JAORMX**
This ensures that the e2e jobs only run if relevant files are touched.

Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>

### CODE REVIEW

**Comment by jhrozek** [comment]
I think the regexes are good. What do you think about adding `Dockerfiles/ocp4_content` and `Dockerfiles/quay_publish`?

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 012d8009227c610757a71d8df2bc6d7d1d31d2e0

**Comment by JAORMX** [comment]
> I think the regexes are good. What do you think about adding `Dockerfiles/ocp4_content` and `Dockerfiles/quay_publish`?

@jhrozek done

**Review by jhrozek — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
