### PR TITLE
Outpost support for AWS

### PR DESCRIPTION
**Pull request by AsherShoshan**

### CODE REVIEW

**Comment by bear-redhat** [comment]
/ok-to-test
Direct calls to AWS CLI is restricted on DPTP's AWS account, which is not the case here.
Approvals from DPTP is not required.

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.11-installer-rehearse-aws

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.11-installer-rehearse-aws

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.11-installer-rehearse-aws

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.11-installer-rehearse-aws-outpost

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.13-installer-rehearse-aws

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.13-installer-rehearse-aws

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-e2e-conformance-kubevirt

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-e2e-conformance-kubevirt

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.13-installer-rehearse-aws

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-e2e-conformance-kubevirt

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.13-installer-rehearse-aws

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.11-installer-rehearse-aws

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.11-installer-rehearse-aws-outpost

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by cmyster** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-e2e

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-terraform-rehearse-debug

**Pull request closed without merging**
