### PR TITLE
Fixing openshift-cluster-network-operator-master.yaml to use dockerfile from ocp-build-data

### PR DESCRIPTION
**Pull request by alvaroaleman**

### CODE REVIEW

**Comment by danwinship** [comment]
/cc @squeed 

I think probably `Dockerfile.rhel7` should be fixed to be golang 1.13 too (or 14?)

**Comment by squeed** [comment]
Yeah, let's bump to 1.14.

**Comment by danwinship** [comment]
/hold
we're updating the golang requirements in https://github.com/openshift/cluster-network-operator/pull/753
@alvaroaleman it seems like ocp-build-data doesn't explicitly specify the golang versions. Do we need to update anything there? Or are the changes here generated from a combination of the ocp-build-data and the current state of cluster-network-operator?

**Comment by jupierce** [comment]
@danwinship This PR is just an attempt to make sure the Dockerfile you use upstream is the same Dockerfile ART uses to build your component downstream. You can certainly set new go versions (feel free to replace this PR with your own variation so long as Dockerfile.rhel7 is used).
The *next* wave of PRs (not yet opened) will force CI builds to start using the version of Go that ART is using. After that work lands, you won't need to worry about keeping things in sync manually.

**Comment by danwinship** [comment]
/hold cancel
/lgtm
we can just do another update when the golang version changes...

**Pull request merged**
