### PR TITLE
Update vsphere winc cluster profile

### PR DESCRIPTION
**Pull request by weinliu**
Update to us vsphere-2

Or the machine may be created on Datastore below, without the template file
...snip...

```
      Metadata:
        Creation Timestamp:
      Network:
        Devices:
          Network Name:      ci-vlan-946
      Num CP Us:             4
      Num Cores Per Socket:  4
      Snapshot:
      Template:              windows-golden-images/windows-server-2022-template-qe
      User Data Secret:
        Name:  windows-user-data
      Workspace:
        Datacenter:     cidatacenter
        Datastore:      /cidatacenter/datastore/vsanDatastore
        Folder:         /cidatacenter/vm/ci-ln-zss120t-c1627-7bsrt
        Resource Pool:  /cidatacenter/host/cicluster/Resources/ipi-ci-clusters
        Server:         vcenter.ci.ibmc.devcluster.openshift.com
Status:
```
...snip...

### CODE REVIEW

**Comment by miyadav** [comment]
Thanks @weinliu 
LGTM

**Comment by weinliu** [comment]
@jianlinliu @jhou1 could you help take a look? Thanks!

**Comment by jianlinliu** [comment]
`vsphere-2` is going to be dismissed soon, refer to https://redhat-internal.slack.com/archives/C015H2WDJRY/p1721839557324909

**Comment by weinliu** [comment]
> `vsphere-2` is going to be dismissed soon, refer to https://redhat-internal.slack.com/archives/C015H2WDJRY/p1721839557324909

My bad, I meant to use `cluster_profile: vsphere-connected-2`

@jianlinliu could you take another look? Thanks

**Comment by jianlinliu** [comment]
>  I meant to use cluster_profile: vsphere-connected-2

I am afraid, vsphere-connected-2 is going to be dismissed soon, the proposed cluster profile is `vsphere-elastic`. If winc have some specific requirement, it is better to discuss with SPLAT team in `forum-ocp-splat` slack channel.

**Comment by jianlinliu** [comment]
Confirmed with splat team in https://redhat-internal.slack.com/archives/C011MLLLY4W/p1722488478100679, vsphere-connected-2 is still can be used for now. Later we need dedicated effort to migrate it.

/lgtm

**Pull request merged**
