### PR TITLE
Add support to run chaos tests on x86_64 arch

### PR DESCRIPTION
**Pull request by chaitanyaenr**
This is enabled for OCP 4.14 builds.

### CODE REVIEW

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-x86-64-krkn-hub-tests-x86-64

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-x86-64-krkn-hub-tests-x86-64

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-x86-64-krkn-hub-tests-x86-64

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-x86-64-krkn-hub-tests-x86-64

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-x86-64-krkn-hub-tests-x86-64

**Comment by chaitanyaenr** [comment]
@paigerube14 PTAL

**Comment by paigerube14** [comment]
@chaitanyaenr what is the difference between this and https://github.com/openshift/release/blob/master/ci-operator/config/redhat-chaos/krkn-hub/redhat-chaos-krkn-hub-main__4.14-nightly.yaml ?

**Comment by chaitanyaenr** [comment]
> @chaitanyaenr what is the difference between this and https://github.com/openshift/release/blob/master/ci-operator/config/redhat-chaos/krkn-hub/redhat-chaos-krkn-hub-main__4.14-nightly.yaml ?

So basically this jobs runs on x86_64 arch instances and https://github.com/openshift/release/blob/master/ci-operator/config/redhat-chaos/krkn-hub/redhat-chaos-krkn-hub-main__4.14-nightly.yaml  runs the tests on amd64 instances.

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-krkn-hub-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-krkn-hub-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-x86-64-krkn-hub-tests-x86-64

**Pull request merged**
