### PR TITLE
add label for new OLM repos

### PR DESCRIPTION
**Pull request by jianzhangbjz**
To address the issue in https://github.com/openshift/platform-operators/pull/84
```yaml
@openshift-cherrypick-robot: The following test failed, say /retest to rerun all failed tests or /retest-required to rerun all mandatory failed tests:
```

### CODE REVIEW

**Comment by jianzhangbjz** [comment]
Hi @awgreene  @kuiwang02 , could you help approve it? Thanks!

**Review by danilo-gemoli — APPROVED** [review]

**Pull request merged**
