### PR TITLE
Update master tag to 4.8 OCP Create image promotion postsubmit job for ci-artifacts

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
This Patch adds the promote stanza to ci-artifacts, enabling the postsubmit job to build and store the image into the openshift-psap/ci-artifacts image-stream  
This patch also updates master tag to use 4.8 OCP

Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
OutOfMemoryKilled
/test pj-rehearse

**Comment by kpouget** [comment]
I don't understand where is the `config` part of this postsubmit job ... did I missed something, or you forgot to include it in the commit? but the tests would have failed if that was the case o^O

**Comment by ArangoGutierrez** [comment]
> I don't understand where is the `config` part of this postsubmit job ... did I missed something, or you forgot to include it in the commit? but the tests would have failed if that was the case o^O

The core component of this PR is 
```yaml
promotion:
  name: master
  namespace: openshift-psap
```

**Comment by kpouget** [comment]
thanks @ArangoGutierrez :)

/lgtm

**Pull request merged**
