### PR TITLE
Utilize gcs browser prefixes by bucket config

### PR DESCRIPTION
**Pull request by smg247**
Now that https://github.com/kubernetes/test-infra/pull/26079 exists, we can use it in our config and set the `gcs browser` prefixes by `bucket`. This will make it so the `postsubmits` and `periodics` in the 2 private deck instances link to the correct place as well as the `presubmits`.

Fixes: [DPTP-2813](https://issues.redhat.com/browse/DPTP-2813)

### CODE REVIEW

**Comment by droslean** [comment]
We will need to update the vendors in ci-tools as well.

**Comment by smg247** [comment]
> We will need to update the vendors in ci-tools as well.

yeah, unfortunately you are right...I'll take care of it

**Pull request merged**
