### PR TITLE
Transition HCP KubeVirt 4.15 periodic to use mce 2.5 pre-release and LVM etcd storage

### PR DESCRIPTION
**Pull request by davidvossel**
Previously the 4.15 job was using the hypershift operator's registry.ci builds. We need to transition to testing with the mce 2.5 pre-release now that we are approaching the release of 4.15

### CODE REVIEW

**Comment by davidvossel** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-kubevirt-mce-baremetalds-conformance

**Comment by davidvossel** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-kubevirt-mce-baremetalds-conformance

**Comment by davidvossel** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-kubevirt-mce-baremetalds-conformance

**Review by qinqon — CHANGES_REQUESTED** [review]
We are missing
```
LVM_OPERATOR_SUB_CHANNEL=stable-4.15
```

By default is installing 4.13

**Comment by davidvossel** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-kubevirt-mce-baremetalds-conformance

**Comment by davidvossel** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-kubevirt-mce-baremetalds-conformance

**Review by qinqon — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
