### PR TITLE
OpenShift CI job for Upgrade tests

### PR DESCRIPTION
**Pull request by jkopriva**

### CODE REVIEW

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by rhopp** [comment]
The PR looks fine to me. I'm just not sure we should be adding this one as we've already been approached to lower our usage of "common" AWS resources (I think we are now draining hypershift's team budget) and this job is adding another (third!) full-blown (hypershift hosted) cluster to each of the PR checks.
@psrna if you think this *needs* to be merged ASAP - it would be nice to have approval from the team holding the budget IMO.
/hold

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests

**Pull request merged**
