### PR TITLE
Migrate (2.3): presubmits part 2

### PR DESCRIPTION
**Pull request by hongkailiu**
- [ ] 1. migrate existing jobs that had duplicates to the build farm
- [x] 2. migration of jobs that had not yet been duplicated but are generated from config
    - [ ] 2.1. openshift-priv repos
    - [ ] 2.2. jobs with volume 0
    - [x] 2.3. 1/5 jobs each day
- [ ] 3. migration of hand-written jobs; if the migration causes them to fail we may reach out to affected teams for help here
- [ ] 4. migration of presubmits, including image publication image mirroring, and all remained presubmits that are left or added during the migration
- [ ] 5. migration of periodics, including release gates and infrastructure jobs

### CODE REVIEW

**Comment by hongkailiu** [comment]
/hold

for tomorrow (Mar. 31).

/assign @stevekuznetsov

**Comment by stevekuznetsov** [comment]
/lgtm

Cancel whenever.

**Pull request merged**
