### PR TITLE
Update Placement, Swift and Telemetry jobs to OCP 4.16

### PR DESCRIPTION
**Pull request by lewisdenny**
Jira: https://issues.redhat.com/browse/OSPRH-8549

### CODE REVIEW

**Comment by lewisdenny** [comment]
pj-rehearse pull-ci-openstack-k8s-operators-telemetry-operator-main-telemetry-operator-build-deploy-kuttl pull-ci-openstack-k8s-operators-placement-operator-main-placement-operator-build-deploy-kuttl pull-ci-openstack-k8s-operators-swift-operator-main-swift-operator-build-deploy-kuttl

**Comment by lewisdenny** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-telemetry-operator-main-telemetry-operator-build-deploy-kuttl pull-ci-openstack-k8s-operators-placement-operator-main-placement-operator-build-deploy-kuttl pull-ci-openstack-k8s-operators-swift-operator-main-swift-operator-build-deploy-kuttl

**Comment by lewisdenny** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-swift-operator-main-swift-operator-build-deploy-kuttl

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-telemetry-operator-main-telemetry-operator-build-deploy-kuttl

**Pull request merged**
