### PR TITLE
ipi-install-hosted-loki: remove readiness probe

### PR DESCRIPTION
**Pull request by vrutkovs**
There is no service requesting promtail and we'd like to avoid TargetDown alerts

### CODE REVIEW

**Comment by vrutkovs** [comment]
No loki/promtail alerts in rehearsals
/cc @wking

**Comment by stbenjam** [comment]
/remove lifecycle-stale

@vrutkovs Is this still something we want?

**Comment by vrutkovs** [comment]
I haven't seen TargetDown alerts for a while, so probably this change is too dangerous - also it may prevent us from fetching all logs. Lets close it and come back to it if necessary

**Pull request closed without merging**
