### PR TITLE
installer: drop techpreview from heterogeneous jobs

### PR DESCRIPTION
**Pull request by r4f4**
This fixes the following e2e failure:
```
  [sig-ci] [Early] prow job name [It] should match feature set [Suite:openshift/conformance/parallel]
  github.com/openshift/origin/test/extended/ci/job_names.go:36

    [FAILED] job name "aws-ovn-heterogeneous" has mismatched feature set in name (expected techpreview in job name)
```

### CODE REVIEW

**Comment by r4f4** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-aws-ovn-heterogeneous

**Comment by r4f4** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-gcp-ovn-heterogeneous

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Pull request merged**
