### PR TITLE
Set the Prow jobs for stolostron/governance-policy-framework-addon

### PR DESCRIPTION
**Pull request by mprahl**
Related:
https://github.com/stolostron/backlog/issues/25999

### CODE REVIEW

**Comment by dhaiducek** [comment]
The `OWNERS` file is missing in the `jobs/` folder.

**Comment by dhaiducek** [comment]
We need to commit a `.ci-operator.yaml` file to the repo for this to work, for example:
https://github.com/stolostron/config-policy-controller/blob/main/.ci-operator.yaml

**Comment by dhaiducek** [comment]
The `release-2.7` branch needs to be fast-forwarded so it has the `.ci-operator.yaml` file also.

**Review by dhaiducek — APPROVED** [review]

**Review by Kyl-Bempah — APPROVED** [review]
LGTM

**Pull request merged**
