### PR TITLE
Changing config to see test on sippy dashboard

### PR DESCRIPTION
**Pull request by shahsahil264**
@paigerube14 @chaitanyaenr

### CODE REVIEW

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-x86-64-krkn-hub-tests-x86-64

**Comment by shahsahil264** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-krkn-hub-tests-414

**Comment by shahsahil264** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-x86-64-krkn-hub-tests-x86-64

**Comment by shahsahil264** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-krkn-hub-tests-414

**Comment by shahsahil264** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-x86-64-krkn-hub-tests-x86-64

**Comment by shahsahil264** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-x86-64-krkn-hub-tests-x86-64

**Pull request merged**
