### PR TITLE
kubevirt: Move common-templates to gcp-virtualization

### PR DESCRIPTION
**Pull request by fossedihelm**
Changed the cluster_profile to `gcp-virtualization`.
Changed the name from `azure` to `gcp`

jira ticket: https://issues.redhat.com/browse/PCO-423

Signed-off-by: fossedihelm <ffossemo@redhat.com>

### CODE REVIEW

**Comment by fossedihelm** [comment]
Hey @ksimon1 the failing tests suggest me to run `make jobs` and push the changes:
the result is that in the `ci-operators/jobs/kubevirt/common-templates/kubevirt-common-templates-release-*-presubmits.yaml` files, the `cluster` value goes from "build03" to "build02".
Is it a safe change? Thanks

**Comment by ksimon1** [comment]
If the change was done by `make jobs` script, then it should be fine

**Comment by ksimon1** [comment]
I would merge this PR even with failing tests, because most of the failures comes from versions, which are no longer supported. @akrejcir WDYT? If there will be some tests failing after this merge, I will fix them in different PR.

**Comment by akrejcir** [comment]
ok, that's reasonable.

/lgtm

**Pull request merged**
