### PR TITLE
ci-operator/mco: rename mco dockerfile

### PR DESCRIPTION
**Pull request by kikisdeliveryservice**
Rename mco dockerfile from Dockerfile.machine-config-operator
to Dockerfile

Related-to: openshift/machine-config-operator#739
Required-by: openshift/machine-config-operator#895

cc:@runcom

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
This PR opened based on @runcom 's request here: 
https://github.com/openshift/machine-config-operator/pull/895#issuecomment-508505929

/assign @runcom

**Comment by kikisdeliveryservice** [comment]
Realizing I need to change this first in our repo before I change it here, will have to time this correctly tomorrow.

So: 
/hold

**Comment by kikisdeliveryservice** [comment]
I think I need to _add_ a dockerfile named Dockerfile to the MCO repo (the new master dockerfile containing all the component images), then merge this, then delete the old Dockerfile.machine-config-operator (the old master dockerfile containing all the component images)

**Comment by runcom** [comment]
last minute thought, this might be the time we sync with ART about the rhel image as well (if we drop Dockerfile.machine-config-operator.rhel7 will ART start failing?)

**Comment by kikisdeliveryservice** [comment]
> last minute thought, this might be the time we sync with ART about the rhel image as well (if we drop Dockerfile.machine-config-operator.rhel7 will ART start failing?)

@runcom Sounds like a good idea!! Will do!

**Comment by kikisdeliveryservice** [comment]
lifting hold since openshift/machine-config-operator has merged.

/hold cancel

**Pull request merged**
