### PR TITLE
[kubevirt] update ocp to 4.12 for kubevirt ssp

### PR DESCRIPTION
**Pull request by ksimon1**
update ocp to 4.12 for kubevirt ssp 

Signed-off-by: Karel Šimon <ksimon@redhat.com>

### CODE REVIEW

**Comment by akrejcir** [comment]
Looks good. I will give `/lgtm` once tests pass.

**Comment by ksimon1** [comment]
/pj-rehearse pull-ci-kubevirt-ssp-operator-master-e2e-functests

**Pull request merged**
