### PR TITLE
[WIP] OCPQE-13529: Jobs that pre-test cucushift framework changes

### PR DESCRIPTION
**Pull request by liangxia**
To identify root cause for https://issues.redhat.com/browse/OCPQE-13529, we need code changes in verification-tests, which might break auto execution in Jenkins CI and Prow CI. To avoid the break in CI, we will test the framework changes in devel branch for verification-tests.

Related PRs, https://github.com/openshift/release/pull/36058, https://github.com/openshift/release/pull/36156

First test with master branch in verification-tests, to make sure we are in the correct starting point, which is that UI tests fail on build farm [build02](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/36116/rehearse-36116-periodic-ci-openshift-verification-tests-devel-4.12-amd64-stable-aws-ipi-build02/1622899794097737728), while works on build farm [build01](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/36116/rehearse-36116-periodic-ci-openshift-verification-tests-devel-4.12-amd64-stable-aws-ipi-build01/1622899794223566848) / [build03](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/36116/rehearse-36116-periodic-ci-openshift-verification-tests-devel-4.12-amd64-stable-aws-ipi-build03/1622899794160652288) / [build04](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/36116/rehearse-36116-periodic-ci-openshift-verification-tests-devel-4.12-amd64-stable-aws-ipi-build04/1622899794374561792) / [build05](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/36116/rehearse-36116-periodic-ci-openshift-verification-tests-devel-4.12-amd64-stable-aws-ipi-build05/1622899794307452928)

### CODE REVIEW

**Comment by liangxia** [comment]
Created a new branch `devel`, which is the same to master branch at the moment.
Then test with devel branch, to make sure we are in the correct starting point, which is that UI tests fail on build farm [build02](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/36116/rehearse-36116-periodic-ci-openshift-verification-tests-devel-4.12-amd64-stable-aws-ipi-build02/1623526601545224192), while works on build farm [build01](https://prow.ci.openshift.org/placeholder) / [build03](https://prow.ci.openshift.org/placeholder) / [build04](https://prow.ci.openshift.org/placeholder) / [build05](https://prow.ci.openshift.org/placeholder)

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-devel-4.12-amd64-stable-aws-ipi-build04

**Comment by liangxia** [comment]
Test changes in https://github.com/openshift/verification-tests/pull/3210

/pj-rehearse

**Comment by liangxia** [comment]
Test changes in https://github.com/openshift/verification-tests/pull/3216

/pj-rehearse

**Comment by liangxia** [comment]
/pj-rehearse abort

We need to wait for the new images.

**Comment by yanpzhan** [comment]
Generally, how long we need wait before new images are built?

**Comment by liangxia** [comment]
The image has been refresh at `"Created": "2023-03-22T18:04:01"`

/pj-rehearse

**Pull request closed without merging**
