### PR TITLE
ci: add ocs, odf-operator config for 4.18

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
added config for 4.18 release for ocs and odf-operator

### CODE REVIEW

**Review by iamniting — CHANGES_REQUESTED** [review]
Can you also update main branches to consume OCP 4.18?

**Comment by Nikhil-Ladha** [comment]
> Can you also update main branches to consume OCP 4.18?

Done

**Review by iamniting — APPROVED** [review]

**Comment by Nikhil-Ladha** [comment]
/pj-rehearse pull-ci-red-hat-storage-ocs-operator-main-ocs-operator-bundle-e2e-aws

**Pull request merged**
