### PR TITLE
[CVP-3518] Update the scorecard container to v8

### PR DESCRIPTION
**Pull request by asergienk**

### CODE REVIEW

**Comment by danilo-gemoli** [comment]
`core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ci` looks fine
/lgtm
but
/hold
because I'm not the owner of the other two files.

**Comment by asergienk** [comment]
/pj-rehearse periodic-ci-redhat-openshift-ecosystem-cvp-ocp-4.12-cvp-common-claim

**Pull request merged**
