### PR TITLE
[PERFSCALE-3401] BM CPT: LSO operator deploy 2/2

### PR DESCRIPTION
**Pull request by josecastillolema**
Continuation of https://github.com/openshift/release/pull/57346

### CODE REVIEW

**Comment by josecastillolema** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-x86-day2-lso

**Comment by josecastillolema** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-x86-day2-lso

**Comment by josecastillolema** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-x86-day2-lso

**Comment by josecastillolema** [comment]
```
# oc get pv -A
NAME                CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM   STORAGECLASS   VOLUMEATTRIBUTESCLASS   REASON   AGE
local-pv-2131a083   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-213bc4e1   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-2860c17    1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-28fc81cc   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-2b95110f   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-3ad566e1   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-3c8281c5   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-4e18b235   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-5dcd75c9   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-634325a3   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-75e6f29b   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-793ff6f4   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-7f6f8db6   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-806b6ab2   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-87b8324e   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-8b3f6c02   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-984ee3c3   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-9b509553   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-bf49e06    1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-ca3416fc   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-cb1e39dc   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-cbb3e7c2   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-d2200536   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-d3411d11   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-e1588080   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-e5c759bc   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-f13d9bdf   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-f14e3264   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-f4ffc077   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-f675b918   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-fb752736   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
local-pv-ffc5bffc   1490Gi     RWO            Delete           Available           localblock     <unset>                          44s
```

**Comment by josecastillolema** [comment]
@jtaleric ptal, results here: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/57386/rehearse-57386-pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-x86-day2-lso/1842843980602019840

**Review by rsevilla87 — APPROVED** [review]
/lgtm

**Pull request merged**
