### PR TITLE
Add prow job for the cluster status geneva action

### PR DESCRIPTION
**Pull request by charlesakalugwu**
/cc @kargakis @mjudeikis

### CODE REVIEW

**Comment by kargakis** [comment]
Do we need to have this separate? Can't it run as part of e2e if the admin api is present?

**Comment by charlesakalugwu** [comment]
> Do we need to have this separate? Can't it run as part of e2e if the admin api is present?

I guess it can be run as part of e2e. yes

**Comment by petr-muller** [comment]
/test pj-rehearse

sorry about this, an escaped test specimen :)

**Comment by charlesakalugwu** [comment]
closing this in favor of running this test as part of the e2e prow job

**Pull request closed without merging**
