### PR TITLE
Adding delete option for kube burner ocp version

### PR DESCRIPTION
**Pull request by paigerube14**
The kube-burner ocp way of running the workload has a different parameter name for cleanup. Its called garbage collect. Changing the name of the variable for cluster-density-v2

It was cleaning up the resources before it ran the upgrade. Notice no non default namespace at top of this output: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-nightly-4.13-loaded-upgrade-from-stable-4.12-ocp-qe-perfscale-loaded-upgrade-aws/1673300211016929280/artifacts/ocp-qe-perfscale-loaded-upgrade-aws/openshift-qe-loaded-upgrade/build-log.txt

### CODE REVIEW

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-nightly-4.13-loaded-upgrade-from-stable-4.12-ocp-qe-perfscale-loaded-upgrade-aws periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-nightly-4.14-loaded-upgrade-from-stable-4.12-ocp-qe-perfscale-loaded-upgrade-aws

**Comment by liqcui** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-nightly-4.13-loaded-upgrade-from-stable-4.12-ocp-qe-perfscale-loaded-upgrade-aws

**Pull request merged**
