### PR TITLE
Update NVIDIA GPU operator periodics on 4.15

### PR DESCRIPTION
**Pull request by empovit**
Following 4.15 GA on Feb 27

### CODE REVIEW

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.15-nvidia-gpu-operator-e2e-master

**Comment by mresvanis** [comment]
/lgtm

@empovit feel free to unhold when the operator is in OCP 4.15

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.15-nvidia-gpu-operator-e2e-23-9-x periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.15-nvidia-gpu-operator-e2e-23-6-x

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.15-nvidia-gpu-operator-e2e-23-9-x periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.15-nvidia-gpu-operator-e2e-23-6-x

**Pull request merged**
