### PR TITLE
MGMT-18072: Adjust periodicity of nighly jobs

### PR DESCRIPTION
**Pull request by danmanor**
Adjust running frequency of periodic jobs in ocm branches:

OCM N daily
OCM N-1 every 2 days
OCM N-2 once a week
OCM N-3 once a week (will be deprecated soon anyway)

### CODE REVIEW

**Review by adriengentil — APPROVED** [review]

**Comment by danmanor** [comment]
/‏pj-rehearse

**Comment by danmanor** [comment]
/‏pj-rehearse ack

**Pull request merged**
