### PR TITLE
Run kuttl tests in e2e job for ovn-operator

### PR DESCRIPTION
**Pull request by cescgina**
Run the build-deploy-kuttl workflow instead of the build-deploy one.

### CODE REVIEW

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-ovn-operator-main-ovn-operator-build-deploy-kuttl

**Comment by cescgina** [comment]
Tests are passing: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/37382/rehearse-37382-pull-ci-openstack-k8s-operators-ovn-operator-main-ovn-operator-build-deploy-kuttl/1636306843598852096/artifacts/ovn-operator-build-deploy-kuttl/openstack-k8s-operators-kuttl/build-log.txt
```
=== CONT  kuttl
    harness.go:405: run tests finished
    harness.go:513: cleaning up
    harness.go:570: removing temp folder: ""
--- PASS: kuttl (140.44s)
    --- PASS: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/ovn_scale (130.90s)
PASS
```

**Comment by Sandeepyadav93** [comment]
/pj-rehearse ack


result looks good
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/37382/rehearse-37382-pull-ci-openstack-k8s-operators-ovn-operator-main-ovn-operator-build-deploy-kuttl/1636306843598852096/artifacts/ovn-operator-build-deploy-kuttl/openstack-k8s-operators-kuttl/build-log.txt

**Pull request merged**
