### PR TITLE
hypershift: refactor and unify hypershift install step

### PR DESCRIPTION
**Pull request by sjenning**
- Unifies all `hypershift install` calls to a single step `ref: hypershift-install`
- Makes `hypershift-install` and `hypershift-install-metrics` a `ref` instead of `chain` since there is only a single operation
- Put step commands in a separate script file.  This is required for a `ref` and the filename is opinionated as well.

This fixes an issue where `/test e2e-conformance` does not install the hypershift-operator under test.

The image for `hypershift-install` no longer needs to be an image with source since we aren't calling the `hypershift-install-private` Make target anymore.

After this, we can remove the Make target in the o/h repo here
https://github.com/openshift/hypershift/blob/main/Makefile#L218-L231

### CODE REVIEW

**Comment by sjenning** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-aws
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-conformance
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-e2e-aws-periodic

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-e2e-aws-periodic

**Comment by sjenning** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-conformance

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-aws-ovn

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-aws-ovn

**Pull request merged**
