### PR TITLE
CI setup for Serverless 1.25

### PR DESCRIPTION
**Pull request by skonto**
As in https://github.com/openshift/release/pull/30476. Uses 4.11.

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by skonto** [comment]
@pierDipi we need to build `knative-v1.4:knative-eventing-kafka-broker-src`, the rest are available.

**Comment by pierDipi** [comment]
@skonto it's called `knative-v1.4:eventing-kafka-broker-src`

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by skonto** [comment]
```
11:07:53.092 DEBUG:   [[ $(oc -n openshift-marketplace get pods -l olm.catalogSource=serverless-operator --no-headers | wc -l) != 1 ]] : Waiting until non-zero (max 120 sec.)
done
error: the server doesn't have a resource type ""
11:07:53.723 DEBUG:   [[ $(oc -n openshift-marketplace get sa serverless-operator -ojsonpath='{.imagePullSecrets}' | grep -c dockercfg) == 0 ]] : Waiting until non-zero (max 120 sec.)
.........................................................................................................................
11:10:13.720 ERROR:   Time out of 120 exceeded
```

**Comment by skonto** [comment]
Now two are failing one due to:

```
[31mERRO[0m[2022-09-14T13:47:21Z] 
  * could not run steps: step upstream-e2e-mesh-aws-ocp-46 failed: failed to wait for the created cluster claim to become ready: timed out waiting for the condition 
  * ```
The other:
```
TestServerlessUpgrade/VerifyContinualTests/ChannelContinualTest
```

**Comment by pierDipi** [comment]
+1

/unhold

**Pull request merged**
