### PR TITLE
MULTIARCH-3987: Add security scan for openshift-ibm-powervs-block-csi-driver

### PR DESCRIPTION
**Pull request by yussufsh**

### CODE REVIEW

**Comment by dharaneeshvrd** [comment]
@yussufsh Actual test need to be added in https://github.com/openshift/release/blob/master/ci-operator/config/openshift/ibm-powervs-block-csi-driver/openshift-ibm-powervs-block-csi-driver-release-4.12.yaml and then if you run `make jobs` which will auto generate your job config.

**Comment by yussufsh** [comment]
We have some good rehearse o/p.
Can @mkumatag or @jaypoulz do a `/pj-rehearse ack`?

**Comment by mkumatag** [comment]
But I see lots of errors in the scan result(most of them are in vendoring packages), lets have a solid plan how to fix them if we merge this PR?

**Comment by jaypoulz** [comment]
I filed https://issues.redhat.com/browse/MULTIARCH-3986 as an umbrella to track the addition of each of the jobs.
That said, we probably want to start adding specific repo+version resolution tickets, and then focus our efforts from newest to oldest. The 4.16/4.15/main scans are probably all the same at this point pre-merge.

One question is, is there a way we can avoid scanning the "main" branch since it will always have a numbered analog?

**Comment by jaypoulz** [comment]
@yussufsh Besides adding general enablement tickets, I also added tickets we can use to start a daisy-chain for updating each release. E.g. https://issues.redhat.com/browse/MULTIARCH-3994

In the acceptance criteria for that ticket, I provided instructions for how to clone that ticket so you can make a copy for 4.14. (We can continue this until we get all the way back to 4.12).

CC @Karthik-K-N since I did the same for your repos

**Comment by yussufsh** [comment]
> But I see lots of errors in the scan result(most of them are in vendoring packages), lets have a solid plan how to fix them if we merge this PR?

@mkumatag @jaypoulz Looking at the synk code scan result there are no `critical` issues found. Does that not qualify for merging this PR? Also, note there are no vulnerable dependencies.
```
✔ Tested 1193 dependencies for known issues, no vulnerable paths found.
```

I have another concern. Of course, we will look at the other sev issues, but I see most of them are located in the vendor project which IMO not P1 for us to fix but we could try—saying that because some issues are tough to be accepted in the community. For example, the below issue with controller-runtime (which is an important dependency for us) means logger not printing the error stack is really difficult to convince and is going to take longer.
```
✗ [High] Generation of Error Message Containing Sensitive Information
   ID: 99cb59a9-c6a7-4a12-8bc2-36e21ee9a08e 
   Path: vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go, line 64 
   Info: Information exposure through error stack trace in fmt.Fprintf.
```

Should we stick to fixing all or high/medium issues? Critical issues will be P1 for sure going forward.

**Comment by mkumatag** [comment]
/pj-rehearse pull-ci-openshift-ibm-powervs-block-csi-driver-main-security

**Comment by mkumatag** [comment]
- I'm not comfortable running the scan against the vendoring code, because this may break your CI anytime, lets learn from already enabled repos how they are handling this.
- We need to ensure all the rehearse jobs passed before we merge this PR

**Comment by yussufsh** [comment]
/pj-rehearse pull-ci-openshift-ibm-powervs-block-csi-driver-main-security

**Comment by yussufsh** [comment]
/pj-rehearse pull-ci-openshift-ibm-powervs-block-csi-driver-main-security

**Comment by yussufsh** [comment]
`ci/rehearse/openshift/ibm-powervs-block-csi-driver/main/security` looks good without vendor inclusion.

**Comment by yussufsh** [comment]
@jaypoulz do you know why the release branches are throwing these errors:
```
Starting snyk code scan
There was a problem running Code analysis. One or more of Snyk's services may be temporarily unavailable.
Contact support if the problem persists.
Full vulnerabilities report is available at /logs/artifacts/snyk.sarif.json
snyk code scan failed
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:84","func":"k8s.io/test-infra/prow/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2023-12-11T05:52:59Z"}
error: failed to execute wrapped command: exit status 1
---
```

**Comment by jaypoulz** [comment]
My guess is that we've overrun the snyk scan limit?

**Review by mkumatag — APPROVED** [review]
/lgtm

**Comment by yussufsh** [comment]
@mkumatag could you please also add /pj-rehearse ack

**Pull request merged**
