### PR TITLE
OSASINFRA-3645: new job to test HCP on OSP with pre-defined FIP

### PR DESCRIPTION
**Pull request by EmilienM**
## Summary

This PR introduces a new job in Hypershift Control Plane (HCP) on OpenStack which will be removed once the feature becomes the default method for deployments in our CI for HCP on OpenStack Platform (OSP) conformance jobs.

## Key Changes

* Job Addition: Adds a new job to test HCP on OSP with a pre-defined Floating IP (FIP).
* Reuse of Provision Step: Utilizes the existing floating IP provision step to provision an Ingress Floating IP that will be reused by the HCP conformance workflow.

## Context

This change is part of the ongoing efforts to enhance our CI workflows for HCP on OSP by ensuring proper IP management and reducing manual intervention.

### CODE REVIEW

**Comment by EmilienM** [comment]
I'm happy with the outcome:
* `e2e-openstack-conformance` didn't regress.
* `e2e-openstack-conformance-ingress-fip` didn't pass but as expected since the feature hasn't merged yet.

We can merge it as is I think and I'll rework it once the feature has landed as mentioned in the commit message.
/pj-rehearse ack

**Comment by MaysaMacedo** [comment]
/lgtm

Nice job!

**Pull request merged**
