### PR TITLE
Add alpine as a base image

### PR DESCRIPTION
**Pull request by 0xmichalis**
@openshift/sig-azure adds a minimal image built from alpine:3.8 to be used by azure-misc tools. Brings the size of azure-purge from >300MB down to 12MB.

### CODE REVIEW

**Comment by jim-minter** [comment]
in Docker terms scratch is an empty image - it's not possible to use that?

**Comment by kargakis** [comment]
It's not possible to tag it into an imagestream, it's not a pullable image.

**Comment by jim-minter** [comment]
s/scratch/alpine/ would be clearer but feel free to hit merge

**Comment by kargakis** [comment]
> s/scratch/alpine/ would be clearer but feel free to hit merge

updated to alpine, merging

**Pull request merged**
