### PR TITLE
Add ocs-client operator install command in ocs-operator

### PR DESCRIPTION
**Pull request by leelavg**
Add make install-ocs-client command to ocs-operator e2e test

### CODE REVIEW

**Comment by leelavg** [comment]
cc @iamniting @malayparida2000

**Comment by malayparida2000** [comment]
@iamniting better we override https://github.com/red-hat-storage/ocs-operator/pull/2520 and merge first, and merge this only when it passes. This way we won't be blocking CI for other PRs.

**Comment by leelavg** [comment]
no, let's not override, I believe there's some issue in cleanup, will work on it.

**Review by iamniting — APPROVED** [review]
/approve

**Pull request merged**
