### PR TITLE
add a postsubmit job to use codecov for certman-operator

### PR DESCRIPTION
**Pull request by yithian**

### CODE REVIEW

**Comment by cblecker** [comment]
/hold
@yithian You're missing the postsubmit file, otherwise lgtm

**Comment by yithian** [comment]
@cblecker is that postsubmit file supposed to be autogenerated by `make jobs`? if so, it's not

**Comment by cblecker** [comment]
No, it's not. The presubmit (the job that runs on each PR) is autogenerated, but the postsubmit is not unfortunately

**Comment by cblecker** [comment]
/lgtm
/approve
/hold cancel

/assign @stevekuznetsov 
rehearse isn't passing because the secret needs to be mirrored first

**Pull request merged**
