### PR TITLE
Add node related metrics to gather extra

### PR DESCRIPTION
**Pull request by harche**
Add node related metrics to gather extra

### CODE REVIEW

**Comment by harche** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-aws-sdn

**Review by dgrisonnet — APPROVED** [review]
/lgtm
/approve

**Comment by dgrisonnet** [comment]
@vrutkovs could you have a look when you have the chance? It looks like this needs your approval.

**Pull request merged**
