### PR TITLE
Add storage objects to gather-extra

### PR DESCRIPTION
**Pull request by jsafrane**
* Storage.operator.openshift.io is CRD for cluster-storage-operator.
* CSIDriver.storage.k8s.io has information about installed CSI drivers.
* CSINode.storage.k8s.io has information about topology of CSI drivers.
* VolumeAttachment.storage.k8s.io has information about attached volumes. In theory, this should be empty at the end of every test, but one never knows.

### CODE REVIEW

**Comment by jsafrane** [comment]
/assign @wking  
You seem to be the main author of the changed file.
I checked failed rehearsals and they don't seem to be related to this PR.

**Comment by wking** [comment]
Is there a storage-specific must-gather you can run, like networking does [here][1]?  Ideally this extra step is just an emergency safety valve for clusters too dead to must-gather.

[1]: https://github.com/openshift/release/blob/89b5042adf87e6a67fb387efb347962b4bb0b3d9/ci-operator/step-registry/gather/network/gather-network-commands.sh

**Comment by jsafrane** [comment]
I'd prefer to have the storage objects in the same location as the rest of the cluster must-gather. Having Nodes, PVs, CSINodes and CSIDrivers dumped in separate directories is odd - all of them are cluster-scoped Kubernetes resources.

Similarly, both `storage` and e.g. `kube-controller-manager` are operator.openshift.io/v1 objects, no need to clutter them among separate directories.

**Pull request closed without merging**
