### PR TITLE
STOR-1871: add presubmit e2e jobs for secrets-store-csi-driver repo

### PR DESCRIPTION
**Pull request by dobsonj**
https://issues.redhat.com/browse/STOR-1871

We already run this test from https://github.com/openshift/secrets-store-csi-driver-operator but we need to run it from https://github.com/openshift/secrets-store-csi-driver too. This is for two reasons:

1) Regression testing, so we can see if a driver rebase breaks our tests before merging a PR.
2) We need to improve the reliability of this test, and to do that we need a presubmit job on the driver repo to see the effect of changes to the test.

I couldn't find a way to install secrets-store-csi-driver-operator with a custom driver image from a secrets-store-csi-driver presubmit job, so this workflow installs the driver from manifests without the operator involved at all. This is similar to how upstream would run tests against the driver.

/cc @openshift/storage

### CODE REVIEW

**Comment by dobsonj** [comment]
/pj-rehearse pull-ci-openshift-secrets-store-csi-driver-main-e2e-vault

**Comment by dobsonj** [comment]
/pj-rehearse pull-ci-openshift-secrets-store-csi-driver-main-e2e-vault

**Comment by dobsonj** [comment]
The test was successful, except for one known flake:
```
# daemonset.apps/vault-csi-provider patched
# pod/vault-0 condition met
# Error from server (NotFound): pods "vault-csi-provider-kql92" not found
# Error from server (NotFound): pods "vault-csi-provider-zgcqn" not found
# Error from server (NotFound): pods "vault-csi-provider-zkntk" not found
```
That should be fixed by https://github.com/openshift/secrets-store-csi-driver/pull/24 but I want this presubmit job merged first, so I can make sure it really fixes it.
/pj-rehearse ack

**Comment by gnufied** [comment]
It looks to be failing on:
```

# pod/vault-0 condition met
# Error from server (NotFound): pods "vault-csi-provider-kql92" not found
# Error from server (NotFound): pods "vault-csi-provider-zgcqn" not found
# Error from server (NotFound): pods "vault-csi-provider-zkntk" not found
ok 2 setup vault
```

**Comment by dobsonj** [comment]
Hey @gnufied I mentioned this in a [previous comment](https://github.com/openshift/release/pull/53638#issuecomment-2191882263), but that is a known test flake (it almost always happens) and I have a proposed fix in https://github.com/openshift/secrets-store-csi-driver/pull/24, but I need the presubmit job first to ensure it really fixes the problem with the test.

**Pull request merged**
