### PR TITLE
releases: migrate release jobs for 4.7+

### PR DESCRIPTION
**Pull request by AlexNPavel**
As 4.7 is now GA, this PR migrates release jobs for 4.7+ to generated
for jobs that had been migrated for pre-4.7 releases. This excludes
`e2e-aws` jobs and jobs with `UNRESOLVED_CONFIG` due too the release job
for `e2e-aws` having `UNRESOLVED_CONFIG` and a ci-operator config also
having `e2e-aws` already defined. That conflict will be handled in a
separate PR.

This is the `release-job-migrator` config used for this PR:
```
config:
  e2e-gcp:
    steps:
      cluster_profile: gcp
      workflow: openshift-e2e-gcp
  console-aws:
    base_images:
      console-tests:
        tag: console-tests
    steps:
      cluster_profile: aws
      workflow: ipi-aws
      test:
      - as: e2e-test
        commands: ./test-prow-e2e.sh release
        from: console-tests
        cli: latest
        resources:
          limits:
            memory: 6Gi
          requests:
            cpu: 100m
            memory: 200Mi
  e2e-aws-fips:
    steps:
      cluster_profile: aws
      workflow: openshift-e2e-aws
      env:
        FIPS_ENABLED: true
      pre:
      - chain: ipi-aws-pre
      - ref: fips-check
  e2e-azure-fips:
    steps:
      cluster_profile: azure4
      workflow: openshift-e2e-azure
      env:
        FIPS_ENABLED: true
      pre:
      - chain: ipi-azure-pre
      - ref: fips-check
  e2e-gcp-fips:
    steps:
      cluster_profile: gcp
      workflow: openshift-e2e-gcp
      env:
        FIPS_ENABLED: true
      pre:
      - chain: ipi-gcp-pre
      - ref: fips-check
  e2e-aws-fips-serial:
    steps:
      cluster_profile: aws
      workflow: openshift-e2e-aws
      env:
        FIPS_ENABLED: true
        TEST_SUITE: openshift/conformance/serial
      pre:
      - chain: ipi-aws-pre
      - ref: fips-check
  e2e-azure-fips-serial:
    steps:
      cluster_profile: azure4
      workflow: openshift-e2e-azure
      env:
        FIPS_ENABLED: true
        TEST_SUITE: openshift/conformance/serial
      pre:
      - chain: ipi-azure-pre
      - ref: fips-check
  e2e-gcp-fips-serial:
    steps:
      cluster_profile: gcp
      workflow: openshift-e2e-gcp
      env:
        FIPS_ENABLED: true
        TEST_SUITE: openshift/conformance/serial
      pre:
      - chain: ipi-gcp-pre
      - ref: fips-check
  e2e-aws-sdn-multitenant:
    steps:
      cluster_profile: aws
      workflow: openshift-e2e-aws-sdn-multi
```

Jobs migrated according to `release-job-migrator`:
```
release-openshift-ocp-installer-console-aws-4.7 -> periodic-ci-openshift-release-master-nightly-4.7-console-aws
release-openshift-ocp-installer-console-aws-4.8 -> periodic-ci-openshift-release-master-nightly-4.8-console-aws
release-openshift-ocp-installer-console-aws-4.9 -> periodic-ci-openshift-release-master-nightly-4.9-console-aws
release-openshift-ocp-installer-e2e-aws-fips-4.7 -> periodic-ci-openshift-release-master-nightly-4.7-e2e-aws-fips
release-openshift-ocp-installer-e2e-aws-fips-4.8 -> periodic-ci-openshift-release-master-nightly-4.8-e2e-aws-fips
release-openshift-ocp-installer-e2e-aws-fips-4.9 -> periodic-ci-openshift-release-master-nightly-4.9-e2e-aws-fips
release-openshift-ocp-installer-e2e-aws-fips-serial-4.7 -> periodic-ci-openshift-release-master-nightly-4.7-e2e-aws-fips-serial
release-openshift-ocp-installer-e2e-aws-fips-serial-4.8 -> periodic-ci-openshift-release-master-nightly-4.8-e2e-aws-fips-serial
release-openshift-ocp-installer-e2e-aws-fips-serial-4.9 -> periodic-ci-openshift-release-master-nightly-4.9-e2e-aws-fips-serial
release-openshift-ocp-installer-e2e-azure-fips-4.7 -> periodic-ci-openshift-release-master-nightly-4.7-e2e-azure-fips
release-openshift-ocp-installer-e2e-azure-fips-4.8 -> periodic-ci-openshift-release-master-nightly-4.8-e2e-azure-fips
release-openshift-ocp-installer-e2e-azure-fips-4.9 -> periodic-ci-openshift-release-master-nightly-4.9-e2e-azure-fips
release-openshift-ocp-installer-e2e-azure-fips-serial-4.7 -> periodic-ci-openshift-release-master-nightly-4.7-e2e-azure-fips-serial
release-openshift-ocp-installer-e2e-azure-fips-serial-4.8 -> periodic-ci-openshift-release-master-nightly-4.8-e2e-azure-fips-serial
release-openshift-ocp-installer-e2e-azure-fips-serial-4.9 -> periodic-ci-openshift-release-master-nightly-4.9-e2e-azure-fips-serial
release-openshift-ocp-installer-e2e-gcp-4.2 -> periodic-ci-openshift-release-master-nightly-4.2-e2e-gcp
release-openshift-ocp-installer-e2e-gcp-4.3 -> periodic-ci-openshift-release-master-nightly-4.3-e2e-gcp
release-openshift-ocp-installer-e2e-gcp-4.7 -> periodic-ci-openshift-release-master-nightly-4.7-e2e-gcp
release-openshift-ocp-installer-e2e-gcp-4.8 -> periodic-ci-openshift-release-master-nightly-4.8-e2e-gcp
release-openshift-ocp-installer-e2e-gcp-4.9 -> periodic-ci-openshift-release-master-nightly-4.9-e2e-gcp
release-openshift-ocp-installer-e2e-gcp-fips-4.7 -> periodic-ci-openshift-release-master-nightly-4.7-e2e-gcp-fips
release-openshift-ocp-installer-e2e-gcp-fips-4.8 -> periodic-ci-openshift-release-master-nightly-4.8-e2e-gcp-fips
release-openshift-ocp-installer-e2e-gcp-fips-4.9 -> periodic-ci-openshift-release-master-nightly-4.9-e2e-gcp-fips
release-openshift-ocp-installer-e2e-gcp-fips-serial-4.7 -> periodic-ci-openshift-release-master-nightly-4.7-e2e-gcp-fips-serial
release-openshift-ocp-installer-e2e-gcp-fips-serial-4.8 -> periodic-ci-openshift-release-master-nightly-4.8-e2e-gcp-fips-serial
release-openshift-ocp-installer-e2e-gcp-fips-serial-4.9 -> periodic-ci-openshift-release-master-nightly-4.9-e2e-gcp-fips-serial
release-openshift-origin-installer-e2e-aws-sdn-multitenant-4.7 -> periodic-ci-openshift-release-master-ci-4.7-e2e-aws-sdn-multitenant
release-openshift-origin-installer-e2e-aws-sdn-multitenant-4.8 -> periodic-ci-openshift-release-master-ci-4.8-e2e-aws-sdn-multitenant
release-openshift-origin-installer-e2e-aws-sdn-multitenant-4.9 -> periodic-ci-openshift-release-master-ci-4.9-e2e-aws-sdn-multitenant
release-openshift-origin-installer-e2e-gcp-4.2 -> periodic-ci-openshift-release-master-ci-4.2-e2e-gcp
release-openshift-origin-installer-e2e-gcp-4.3 -> periodic-ci-openshift-release-master-ci-4.3-e2e-gcp
release-openshift-origin-installer-e2e-gcp-4.7 -> periodic-ci-openshift-release-master-ci-4.7-e2e-gcp
release-openshift-origin-installer-e2e-gcp-4.8 -> periodic-ci-openshift-release-master-ci-4.8-e2e-gcp
release-openshift-origin-installer-e2e-gcp-4.9 -> periodic-ci-openshift-release-master-ci-4.9-e2e-gcp
```

### CODE REVIEW

**Comment by AlexNPavel** [comment]
4.9 won't pass because the `initial` image it is trying to pull is 4.8 stable, which doesn't exist. That being said, the base release configs should be using the same stream rel 1 (i.e. second latest accepted image in the same stream) as initial. I'll have to see why the initial image is using prerelease

**Comment by AlexNPavel** [comment]
/hold
https://github.com/openshift/release/pull/16267 changed the previous naming scheme, making this PR invalid. `release-job-migrator` will have to be updated to support the new naming conventions.

**Review by petr-muller — APPROVED** [review]

**Review by petr-muller — APPROVED** [review]

**Comment by petr-muller** [comment]
:tada:

**Pull request merged**
