### PR TITLE
[WIP] Fix baremetal-operator config job

### PR DESCRIPTION
**Pull request by andfasano**

### CODE REVIEW

**Comment by stbenjam** [comment]
What is this trying to fix? Repos that are forks of upstream need this information so they get checked out to the right place. 

openshift/baremetal-operator's canonical name is metal3-io/baremetal-operator.

**Comment by andfasano** [comment]
> What is this trying to fix? Repos that are forks of upstream need this information so they get checked out to the right place.
> 
> github.com/openshift/baremetal-operator's canonical name is github.com/metal3-io/baremetal-operator.

The CI jobs for baremetal-operator are failing since many days, and the initial error showed a missing Dockerfile, so it was a tentative to fix it (still a WIP as per title).

**Comment by andfasano** [comment]
Analysis update: the jobs are failing while building the `src` image, due a failure raised by the `clonerefs` tool. In particular, it seems that for some some reason two "components" get executed against the same repo (the one specified in the original `canonical_go_repository`)  thus generating the issue (see `git init` in https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/9615/rehearse-9615-pull-ci-openshift-baremetal-operator-master-e2e-metal-ipi/11/build-log.txt)

**Comment by andfasano** [comment]
Fixed by https://github.com/openshift/ci-tools/pull/912

**Pull request closed without merging**
