### PR TITLE
CVP Common: collect image pull events from test cluster

### PR DESCRIPTION
**Pull request by dirgim**
Collect all image pull events from the testing cluster.
The output will contain the timestamp and the event message in a comma-separated value format.

### CODE REVIEW

**Comment by petr-muller** [comment]
@dirgim is there a reason why this needs DPTP review? You are an approver, anyone from your team can LGTM your changes, and we expect teams to self-manage their step registry content.

I can review some sensitive or tricky content when needed, but we really should not need to review standard content changes.

**Review by samvarankashyap — APPROVED** [review]
lgtm

**Comment by dirgim** [comment]
> @dirgim is there a reason why this needs DPTP review? You are an approver, anyone from your team can LGTM your changes, and we expect teams to self-manage their step registry content.
> 
> I can review some sensitive or tricky content when needed, but we really should not need to review standard content changes.

@petr-muller I'm fully aware that the DPTP team isn't the owner of these steps. 

Because there are currently no rehearsal jobs for any of the cvp-common workflow, we have been adding you to have at least a sanity check on the PRs that make changes to the workflow steps to prevent introduction of breaking changes. 
If you believe that some other SMEs would be better suited to this task, please recommend them.

**Comment by petr-muller** [comment]
> Because there are currently no rehearsal jobs for any of the cvp-common workflow, we have been adding you to have at least
> If you believe that some other SMEs would be better suited to this task, please recommend them.

Sure, I'll gladly help with reviewing stuff related e.g. to step-registry entities, new steps, or anything that uses sme advanced features such as dependencies or parameters, but when the only change is the payload (the executed command), I don't think there's any SME suitable other than your team. I'm as useful as a living `shellcheck` for that :)

**Pull request merged**
