### PR TITLE
openshift/install: Update path and binary name for openshift-install.

### PR DESCRIPTION
**Pull request by yifan-gu**
"tectonic" is renamed to "openshift-install", some paths are also
changed.

Ref https://github.com/openshift/installer/pull/69

### CODE REVIEW

**Comment by wking** [comment]
Ah, you may want to get [this][1] too.

[1]: https://github.com/openshift/release/blob/7791a576b132a7aaf55c76af56790158bb5efee6/cluster/test-deploy/aws/openshift.yaml#L6

**Comment by yifan-gu** [comment]
@wking updated, thank you!

**Comment by smarterclayton** [comment]
I can  lgtm this as needed tomorrow.  Looks like the other PR needs a rebase.

**Comment by yifan-gu** [comment]
@smarterclayton Thanks, but I'm going to close this, we just think create a new binary and migrate the old package to the new binary would be easier.

**Pull request closed without merging**
