### PR TITLE
Fix: ODH Add missing content of 2023b release branch

### PR DESCRIPTION
**Pull request by harshad16**
Fix: ODH Add missing content of 2023b release branch
Related-to: https://github.com/opendatahub-io/notebooks/issues/135

### CODE REVIEW

**Comment by atheo89** [comment]
Hmmm I guess we have to update with the missing content also the release-2023b configuration then...
Overall, looks good to me :) thanks!

**Comment by harshad16** [comment]
> Hmmm I guess we have to update with the missing content also the release-2023b configuration then...
Overall, looks good to me :) thanks!

i checked them, they seem to have the right information in them.

**Pull request merged**
