### PR TITLE
Add CSI migration to o/k and o/o

### PR DESCRIPTION
**Pull request by jsafrane**
Add the job as optional and don't run it as a default. It may be useful when testing PRs related to migration and rebases.

### CODE REVIEW

**Comment by marun** [comment]
No risk of adding an optional on-demand job.

**Comment by jsafrane** [comment]
Note: rehearsal failures are expected. One of the reason to get the job to o/k is to debug it with PRs in o/k.
I can't reproduce the failure manually :-(.

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
