### PR TITLE
OCPQE-23943 - adding reporter config to 4.17 periodics

### PR DESCRIPTION
**Pull request by miyadav**
@sunzhaohua2 @huali9 @shellyyang1989 PTAL when time permits.

### CODE REVIEW

**Comment by sunzhaohua2** [comment]
Thank you so much, I've always wanted to add this, but I forgot ^_^

**Comment by kuiwang02** [comment]
@miyadav it is not me to approve regression prow job. please contact with qe-productivity to approve it.
cc @liangxia

**Pull request merged**
