### PR TITLE
Remove broken compact jobs

### PR DESCRIPTION
**Pull request by derekhiggins**
All of these have been failing for at least 3 months, some for a lot longer. Remove them as they are waisting resources and they don't appear to be required.

-
I havn't remove the 4.{7,8,9) jobs as these are passing.

### CODE REVIEW

**Comment by derekhiggins** [comment]
cc @jerpeter1 removing the broken compact jobs

**Review by iurygregory — APPROVED** [review]

**Comment by derekhiggins** [comment]
Done here https://github.com/openshift/release/pull/38417

**Pull request closed without merging**
