### PR TITLE
cluster dns operator: rename jobs to add cni

### PR DESCRIPTION
**Pull request by alebedev87**

### CODE REVIEW

**Comment by alebedev87** [comment]
/pj-rehearse pull-ci-openshift-cluster-dns-operator-master-e2e-aws-ovn-single-node

**Comment by alebedev87** [comment]
/pj-rehearse pull-ci-openshift-cluster-dns-operator-master-e2e-aws-ovn-serial

**Comment by alebedev87** [comment]
/pj-rehearse pull-ci-openshift-cluster-dns-operator-master-e2e-aws-ovn-upgrade

**Comment by alebedev87** [comment]
/pj-rehearse pull-ci-openshift-cluster-dns-operator-master-e2e-aws-ovn-single-node

**Comment by alebedev87** [comment]
/pj-rehearse pull-ci-openshift-cluster-dns-operator-master-e2e-aws-ovn-serial

**Comment by alebedev87** [comment]
/pj-rehearse pull-ci-openshift-cluster-dns-operator-master-e2e-aws-ovn-single-node

**Comment by alebedev87** [comment]
/pj-rehearse pull-ci-openshift-cluster-dns-operator-master-e2e-aws-ovn-upgrade

**Comment by alebedev87** [comment]
/pj-rehearse pull-ci-openshift-cluster-dns-operator-master-e2e-aws-ovn-upgrade

**Comment by alebedev87** [comment]
/pj-rehearse pull-ci-openshift-cluster-dns-operator-master-e2e-aws-ovn-single-node

**Comment by alebedev87** [comment]
/pj-rehearse pull-ci-openshift-cluster-dns-operator-master-e2e-aws-ovn-upgrade

**Comment by alebedev87** [comment]
/pj-rehearse pull-ci-openshift-cluster-dns-operator-master-e2e-aws-ovn-single-node

**Review by candita — APPROVED** [review]

**Pull request merged**
