### PR TITLE
Run kubernetes-nmstate operator e2e tests

### PR DESCRIPTION
**Pull request by creydr**
Currently we run only the e2e tests of the handler. This PR adds jobs (including periodics) to run the operators e2e tests as well.

**Additional information for reviewers:**
* I renamed the handlers existing workflow `kubernetes-nmstate-e2e` into `kubernetes-nmstate-e2e-handler` to distinguish between the test workflow for the handler and the operator (eae253fb2ba8bff2518f098fa03e2c0f61362d85)

### CODE REVIEW

**Comment by creydr** [comment]
/hold
need to rebase after #26087 got merged.

**Comment by creydr** [comment]
/hold cancel
as #26087 got merged.

**Comment by creydr** [comment]
`ehearse/periodic-ci-openshift-kubernetes-nmstate-master-e2e-handler-sdn-ipv4-nightly-periodic` failed due to a flake (passed in the past in this PR).

`ci-operator-config` failed, because the openshift-priv "mirror" is not yet updated with the new configs (renamed the handler workflow). I have never changed something in this folder and most of the commits are from the bot which syncs something.

--> ready for review

/assign @cybertron

**Review by cybertron — APPROVED** [review]
/lgtm
/retest-required

**Comment by cybertron** [comment]
It sounds like there may be an infra issue with equinix that is being looked into. Hopefully these jobs will start working once that is resolved.

**Comment by cybertron** [comment]
Only three of the operator tests failed, and of those two were infra issues. It looks to me like the new jobs are working.

/lgtm

**Pull request merged**
