### PR TITLE
Enable chaos tests for OCP 4.17

### PR DESCRIPTION
**Pull request by chaitanyaenr**

### CODE REVIEW

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-tests-417

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-tests-417

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-tests-417

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-tests-417

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-tests-417

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-tests-417

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-tests-417

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-tests-417

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-tests-417

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-tests-417

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-tests-417

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-tests-417

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-tests-417

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-tests-417

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-tests-417

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-tests-417

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-tests-417

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-tests-417

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-tests-417

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-tests-417

**Review by shahsahil264 — APPROVED** [review]
LGTM

**Pull request merged**
