### PR TITLE
Add initial devfile tests with ODO

### PR DESCRIPTION
**Pull request by josephca**

### CODE REVIEW

**Comment by josephca** [comment]
/retitle WIP-Add initial devfile tests with ODO

**Comment by josephca** [comment]
Hi, @amitkrout, can you provide the code review? thanks,

**Review by elsony — COMMENTED** [review]
Is the file meant to be `devfile-integration-tests-master_v4.5.yaml` (single underscore) instead of `devfile-integration-tests-master__v4.5.yaml`?

**Comment by josephca** [comment]
> Is the file meant to be `devfile-integration-tests-master_v4.5.yaml` (single underscore) instead of `devfile-integration-tests-master__v4.5.yaml`?

No, according to the doc, double underscores should be used for the variant.

**Review by elsony — APPROVED** [review]
lgtm

**Pull request merged**
