### PR TITLE
MGMT-10946: fix memory and disk usage of ZTP jobs

### PR DESCRIPTION
**Pull request by osherdp**
Going through our jobs and match the provisioned machines with the actual requirements for their specs:
* Memory is set to 16GiB (worker nodes requirement is actually 8GiB, but we don't have a way separate it in dev-scripts' extra workers).
* Installation disk size is set to 100GB.

I also removed values that match the declared defaults of the ztp/capi workflows, so it now contains less duplication and should be easier to read. As part of it the default networking also changed to IPv4 as it's the most frequently used one.

### CODE REVIEW

**Comment by omertuc** [comment]
> but we don't have a way separate it in dev-scripts' extra workers)

Let's open a ticket to fix this in dev-scripts?

**Comment by omertuc** [comment]
image

/lgtm

**Comment by osherdp** [comment]
> /hold rehearse?

you want to rehearse a bigger sample?

**Comment by osherdp** [comment]
> > but we don't have a way separate it in dev-scripts' extra workers)
> 
> Let's open a ticket to fix this in dev-scripts?

sure, I'll open one to see what we can do there
dev-scripts just classifies all those spoke cluster nodes as extra-nodes without distinction but we can create some API to create extra-workers post hub deployment and be more flexible in defining those extra nodes

**Comment by osherdp** [comment]
@omertuc can you re-lgtm? I had to rebase

**Review by eliorerz — APPROVED** [review]
LGTM

**Comment by osherdp** [comment]
/unhold
mostly looks okay. something is odd with the waiting logic for infra-envs, but I'm seeing it [outside of my PR](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-ipv4v6-3masters-ocp-410-periodic/1548488805265182720). taking discussion about it to slack

**Pull request merged**
