### PR TITLE
Remove hard coded bundle version

### PR DESCRIPTION
**Pull request by praveenkumar**

### CODE REVIEW

**Comment by praveenkumar** [comment]
> We actually have a crc binary in /bin/crc and source code in /opt/crc, not clear to me if we need the bundle version expected by this binary, or the bundle version used in the source code. They probably are supposed to match, but I'd still pick the 'more correct' one in case one day a change causes them not to match. 

@cfergeau Process is something like following which will make sure the binary and the source code is not the different one.

- As soon as code push to crc repo the initial crc container image is created using the Dockerfile in https://github.com/code-ready/crc/blob/master/images/openshift-ci/Dockerfile and if you look at this docker file then the crc binary built by same source which is copied to `/opt/crc` ( https://github.com/code-ready/crc/blob/master/images/openshift-ci/Dockerfile#L10-L11 ) we need to do it because our tests are not able to create static binary https://github.com/code-ready/crc/commit/1d0236ea01d487859ba37e2b607a9d332004e4b5#diff-dd460cb66b5baf1b034c6d60a7ddd4f6 

> A short explanation about the rationale for using the version from the source in the commit log may be useful.

@cfergeau  since the binary and source is same we can use the version which will eliminate updating the bundle version for every single bundle update.

**Comment by cfergeau** [comment]
> > We actually have a crc binary in /bin/crc and source code in /opt/crc, not clear to me if we need the bundle version expected by this binary, or the bundle version used in the source code. They probably are supposed to match, but I'd still pick the 'more correct' one in case one day a change causes them not to match.
> 
> @cfergeau Process is something like following which will make sure the binary and the source code is not the different one.
> 

**at the moment** the process is this way, I cannot predict which changes we will make to it in the future, so it feels better to get the bundle version from the "correct" location. Which binary is being used by the tests? If it's the prebuilt binary, I'd prefer that we extract the bundle version from it. If `make integration` is going to build a new binary, then we should indeed get the bundle version from the source.

**Pull request merged**
