### PR TITLE
WIP: Add cucushift e2e test for azure-upi

### PR DESCRIPTION
**Pull request by dis016**
[OCPQE-5687](https://issues.redhat.com/browse/OCPQE-5687) Add cucushift e2e test for azure-upi 
/cc @jhou1 @liangxia @pruan-rht @JianLi-RH

### CODE REVIEW

**Comment by dis016** [comment]
tests added with PR https://github.com/openshift/verification-tests/pull/2430 https://github.com/openshift/cucushift/pull/8858

**Comment by liangxia** [comment]
@dis016 The 4.9 installation failed. Is it a know issue or just a flake and we are good to retest ?

**Comment by dis016** [comment]
> @dis016 The 4.9 installation failed. Is it a know issue or just a flake and we are good to retest ?

@liangxia not very sure that its a known issue or flake,  i am just exploring egress-ingress related networking scenarios.

**Comment by dis016** [comment]
> > @dis016 The 4.9 installation failed. Is it a know issue or just a flake and we are good to retest ?
> 
> @liangxia not very sure that its a known issue or flake, i am just exploring egress-ingress related networking scenarios.

@lxia looks the 4.9 tests are failing due to known issue https://issues.redhat.com/browse/CORS-1776. and not a flake, retest also failed.

**Comment by liangxia** [comment]
@dis016  The steps have been refactored.  We are reusing a step cucushift-e2e for different iaas and define several envs in the job to distinguish them from each other.

**Comment by dis016** [comment]
closing this MR, will reopen new MR  with new reused workflows

**Pull request closed without merging**
