### PR TITLE
Remove csi-operator image job

### PR DESCRIPTION
**Pull request by jsafrane**
csi-operator is not shipped as part of OKD, so don't build its image.

### CODE REVIEW

**Comment by tsmetana** [comment]
Don't you need to also update cluster/ci/config/prow/config.yaml and cluster/ci/config/prow/plugins.yaml?

**Comment by jsafrane** [comment]
> Don't you need to also update cluster/ci/config/prow/config.yaml and cluster/ci/config/prow/plugins.yaml?

No, I still want /lgtm and merge bot working in the repo.

**Comment by tsmetana** [comment]
OK then.
/lgtm

**Comment by jsafrane** [comment]
@petr-muller @bbguimaraes @droslean, did we break anything with ^?

The goal is to remove `images` and `e2e-aws` jobs and leave the other jobs there.

**Comment by petr-muller** [comment]
> did we break anything with ^?
> The goal is to remove `images` and `e2e-aws` jobs and leave the other jobs there.

Nope, but you haven't really removed the `e2e-aws` job - the generator is not (yet) smart enough to delete jobs that it previously generated.

**Pull request merged**
