### PR TITLE
Onboard wildfly quickstart

### PR DESCRIPTION
**Pull request by kabir**

### CODE REVIEW

**Comment by kabir** [comment]
Screenshot 2023-09-13 at 14 00 56

@bear-redhat @hongkailiu I am getting the above error. I don't think it looks like the problem is on my side, but could be wrong. Any suggestions for how to proceed?

**Comment by kabir** [comment]
pj-rehearse

**Review by fabiobrz — APPROVED** [review]

**Comment by fabiobrz** [comment]
> /pj-rehearse ack

Hi @kabir - it seems that validation jobs have had something to say regarding the latest version, out of the blue.
Here is what [the check is suggesting](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/43257/pull-ci-openshift-release-master-ordered-prow-config/1706730073085710336):

```
 -    cluster: build01
+    cluster: build03 
```

 i.e. just move to the `build03` cluster.

**Pull request merged**
