### PR TITLE
[azure] Fix cpms check on 4.15

### PR DESCRIPTION
**Pull request by jinyunma**
Failed job: https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.15-arm64-nightly-azure-ipi-fullyprivate-proxy-f14/1728467881705869312

The behavior is changed on 4.15, no failureDomains section in cpms spec. 
```
                    "machines_v1beta1_machine_openshift_io": {
                        "metadata": {
                            "labels": {
                                "machine.openshift.io/cluster-api-cluster": "ci-op-pzvvl1qs-5897f-sjl6d",
                                "machine.openshift.io/cluster-api-machine-role": "master",
                                "machine.openshift.io/cluster-api-machine-type": "master"
                            }
                        },
```
It's empty string for failureDomain.platform on 4.14.
```
                    "machines_v1beta1_machine_openshift_io": {
                        "failureDomains": {
                            "platform": ""
                        },
                        "metadata": {
                            "labels": {
                                "machine.openshift.io/cluster-api-cluster": "ci-op-3ycfnsxw-1c91a-qqv9g",
                                "machine.openshift.io/cluster-api-machine-role": "master",
                                "machine.openshift.io/cluster-api-machine-type": "master"
                            }
                        },
```

### CODE REVIEW

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-azure-stack-ipi-f28

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.14-installer-rehearse-azure

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-arm64-nightly-azure-ipi-ultrassd-disks-f28

**Comment by jinyunma** [comment]
cc @gpei @jianlinliu to review
The change on 4.15 is confirmed with Cloud dev, it is expected.

**Comment by jianlinliu** [comment]
Had we hit some problem or bugs because `failureDomain.platform` setting issue before? I am thinking if the field is not important, and never introduce some issues, maybe we can remove the check point to make the step simpler.

**Comment by jinyunma** [comment]
> Had we hit some problem or bugs because `failureDomain.platform` setting issue before? I am thinking if the field is not important, and never introduce some issues, maybe we can remove the check point to make the step simpler.

yes, we added cases based on bug https://issues.redhat.com/browse/OCPBUGS-18883. The behaviors of setting `failureDomain.platform`  are different for installation on zonal region or single zone region.

**Comment by jinyunma** [comment]
/pj-rehearse ack

merge it to unblock those failed jobs on 4.15

**Pull request merged**
