### PR TITLE
RHDH: Configure and Enable PR check and Nightly e2e job for Branch 1.3.x

### PR DESCRIPTION
**Pull request by subhashkhileri**
RHDH: Configure and Enable PR check and Nightly e2e job for Branch 1.3.x

https://issues.redhat.com/browse/RHIDP-3791

### CODE REVIEW

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-1.3.x-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-1.3.x-images

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-1.3.x-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-1.3.x-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-1.3.x-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-1.3.x-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-1.3.x-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-1.3.x-e2e-tests

**Review by josephca — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
