### PR TITLE
feat: update ocp to 4.13 in kubevirt ssp operator

### PR DESCRIPTION
**Pull request by ksimon1**
this commit updates ocp to 4.13 in ssp operator test lanes

Signed-off-by: Karel Šimon <ksimon@redhat.com>

### CODE REVIEW

**Comment by ksimon1** [comment]
@lyarwood we have to wait for new kubevirt version v0.59

**Comment by akrejcir** [comment]
PR: https://github.com/kubevirt/ssp-operator/pull/516 should fix CI on 4.13.

/pj-rehearse

**Comment by akrejcir** [comment]
/pj-rehearse pull-ci-kubevirt-ssp-operator-master-e2e-upgrade-functests

**Comment by akrejcir** [comment]
/pj-rehearse pull-ci-kubevirt-ssp-operator-master-e2e-upgrade-functests

**Comment by akrejcir** [comment]
/pj-rehearse pull-ci-kubevirt-ssp-operator-master-e2e-upgrade-functests

**Comment by lyarwood** [comment]
> @lyarwood: changing LGTM is restricted to collaborators

Awesome, @akrejcir mind adding me?

**Comment by akrejcir** [comment]
> Awesome, @akrejcir mind adding me?

I've created a PR to add you: https://github.com/openshift/release/pull/37213
The `OWNERS` file should be updated by a bot, I'm not sure why it was not.

**Pull request merged**
