### PR TITLE
ovirt-e2e: add ovirt e2e-test to cluster-storage-operator presubmits

### PR DESCRIPTION
**Pull request by eslutsky**
add ovirt-e2e tests on the cluster-storage-operator repo.

Signed-off-by: Evgeny Slutsky <eslutsky@redhat.com>

### CODE REVIEW

**Comment by jsafrane** [comment]
Is there a way how to add the test to https://github.com/openshift/release/blob/master/ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master.yaml ? That one is smaller and easier to review.

**Comment by Gal-Zaidman** [comment]
FYI ovirt is broken on master currently, this is a PR to add a ovirt-e2e job to cluster-storage-operator so we can test a fix on CI.
So it's ok that ovirt failed as long as we see it started a cluster install

**Comment by jsafrane** [comment]
@eslutsky @Gal-Zaidman, I am sorry I broke over and appreciate an ovirt test job, hover, can you please answer the question in https://github.com/openshift/release/pull/10343#issuecomment-661046464 ?

**Comment by eslutsky** [comment]
> @eslutsky @Gal-Zaidman, I am sorry I broke over and appreciate an ovirt test job, hover, can you please answer the question in [#10343 (comment)](https://github.com/openshift/release/pull/10343#issuecomment-661046464) ?

@jsafrane, we are still using the template  method like most platforms, as far as we know there is no way to add our test to 
https://github.com/openshift/release/blob/master/ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master.yaml with out-migrating to workflows.

**Comment by jsafrane** [comment]
Thanks!

/approve

**Pull request merged**
