### PR TITLE
stackrox: fix EKS destroy

### PR DESCRIPTION
**Pull request by gavin-stackrox**
Incorporates https://github.com/stackrox/automation-flavors/pull/168 to fix EKS cluster destruction.
/cc @davdhacs @tommartensen

### CODE REVIEW

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-eks-qa-e2e-tests

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-eks-qa-e2e-tests

**Review by tommartensen — APPROVED** [review]
/lgtm

**Pull request merged**
