### PR TITLE
remove pj-rehearse job args

### PR DESCRIPTION
**Pull request by droslean**
Related to [ci-operator-prowgen#56](https://github.com/openshift/ci-operator-prowgen/pull/56)

Fixes https://github.com/openshift/release/issues/2740

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Why? I like explicit arguments. This doesn't change the mounts at all

**Comment by petr-muller** [comment]
> Why? I like explicit arguments. This doesn't change the mounts at all

After https://github.com/openshift/ci-operator-prowgen/pull/56, `pj-rehearse` will obtain master config itself by manipulating the git repo passed to it by `--candidate-path`, so it no longer needs to get master config locations from the outside.

**Comment by stevekuznetsov** [comment]
Shouldn't we also remove the mounts, then?

**Comment by droslean** [comment]
oops. I forgot them. Updated in the latest push

**Pull request merged**
