### PR TITLE
Enable azure e2e tests for cloud-provider-azure, enable azure-ccm-install for cccmo 

### PR DESCRIPTION
**Pull request by lobziik**
- enable azure-e2e-ccm tests for azure-cloud-provider
 - enable azure-e2e-ccm-install for cccmo and azure-cloud-provider (as optional)

### CODE REVIEW

**Review by Fedosin — APPROVED** [review]
/lgtm
/hold

**Review by elmiko — COMMENTED** [review]
/lgtm

**Review by Fedosin — APPROVED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
Config generation is invalid, this can't merge until that is fixed
/lgtm cancel

**Review by JoelSpeed — COMMENTED** [review]
/lgtm

**Review by Fedosin — APPROVED** [review]
/lgtm

**Pull request merged**
