### PR TITLE
update ibm-roks-toolkit testing  to account for new image streams

### PR DESCRIPTION
**Pull request by relyt0925**
follow up to this PR:
https://github.com/openshift/release/pull/16701

Adjusts tags to get tests to continue to function after movement to new app.ci

Depends on this PR first:
https://github.com/openshift/release/pull/17043

### CODE REVIEW

**Comment by petr-muller** [comment]
Can we split this into the part that sets things up and another part that starts using the new IS? That way we get rehearsals.

**Comment by petr-muller** [comment]
oh I see :D

**Comment by relyt0925** [comment]
@petr-muller I believe the failures above are test flakes in the pipeline. I believe this is ready to go in if you are ok with the changes.

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
