### PR TITLE
Adding 4.18 ppc64le jobs

### PR DESCRIPTION
**Pull request by aishwaryabk**
cc: @juliemathew @sajauddin

### CODE REVIEW

**Comment by aishwaryabk** [comment]
@kuiwang02 @Xia-Zhao-rh  @aleskandro Request you to review the PR. Thanks!

**Comment by aishwaryabk** [comment]
@kuiwang02 @Xia-Zhao-rh A gentle reminder on this. Thanks

**Comment by Xia-Zhao-rh** [comment]
@liangxia PTAL, thanks~

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-ppc64le-nightly-powervs-ipi-f7

**Pull request merged**
