### PR TITLE
Reverts changes to fix Intel Images builds in ODH Notebooks

### PR DESCRIPTION
**Pull request by sharvil10**
This PR reverts the changes made in PR #51853 since the PR # in [ODH Notebooks #521](https://github.com/opendatahub-io/notebooks/pull/521) is closed.

### CODE REVIEW

**Comment by sharvil10** [comment]
@atheo89 @harshad16 could you please add the `ok-to-test` label on this one so I can test the [PR #544](https://github.com/opendatahub-io/notebooks/pull/544) on ODH notebooks?

**Comment by harshad16** [comment]
> could you please add the `ok-to-test` label on this one so I can test the [PR #544](https://github.com/opendatahub-io/notebooks/pull/544) on ODH notebooks?

To test this, we would need to have this in place.
As everything looks good. we should be able to merge it.

/lgtm
/approve

**Pull request merged**
