### PR TITLE
Change metal-ipi workflows to new metal-ipi steps

### PR DESCRIPTION
**Pull request by ardaguclu**

### CODE REVIEW

**Comment by ardaguclu** [comment]
> /test pj-rehearse
> 
> This seems to be working since some of the jobs passed, but it would be nice to not have quite so many failures.

@cybertron I think, we can move forward after one last retest. Because there is already some flakiness as general.

/retest

**Comment by cybertron** [comment]
/lgtm

Sounds good.

**Comment by ardaguclu** [comment]
> /lgtm
> 
> Sounds good.

Thanks. I checked full test history and it seems that all tests passed once and no permanent failing.

**Pull request merged**
