### PR TITLE
add shared configuration for eclipse-che repo

### PR DESCRIPTION
**Pull request by mkuznyetsov**
add configuration for eclipse-che repo, so that other projects will automatically share it's configuration

### CODE REVIEW

**Review by nickboldt — APPROVED** [review]
LGTM, but haven't tested it.

Ref:  [CRW-3581](https://issues.redhat.com/browse/CRW-3581)

**Comment by mkuznyetsov** [comment]
@smg247 Can you please tell, if this PR is good to merge?

**Pull request merged**
