### PR TITLE
deprecate the aws and azure upi template jobs for openshift/installer repository

### PR DESCRIPTION
**Pull request by droslean**
/cc @rna-afk 
/cc @openshift/test-platform 

Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

### CODE REVIEW

**Comment by droslean** [comment]
@rna-afk Can you please check the rehearsals? [CORS-1588](https://issues.redhat.com/browse/CORS-1588) is closed but it seems that the workflow is broken for those releases. In addition, this PR is a follow-up of that card since it didn't happen in https://github.com/openshift/release/pull/22320/

Shall we merge this or do you want to reopen [CORS-1588](https://issues.redhat.com/browse/CORS-1588)?

**Comment by rna-afk** [comment]
>[CORS-1588](https://issues.redhat.com/browse/CORS-1588) is closed but it seems that the workflow is broken for those releases.

Could you elaborate? Not sure what you mean by `those releases`. IIUC the workflow works but these tests are failing since the images corresponding to the versions have not been fixed with a few changes we made to the latest releases.

**Comment by droslean** [comment]
@rna-afk Coming back to this... I took the liberty to update those jobs for you since they are deprecated. We are planning to completely remove all templates. [CORS-1588](https://issues.redhat.com/browse/CORS-1588) was the only reason for keeping those jobs and since this card is closed we should remove them. If you want to keep them, please open another card to make sure to address this.

**Comment by droslean** [comment]
@rna-afk I am closing this PR. We will do a massive removal of all jobs in the near future instead.

**Pull request closed without merging**
