### PR TITLE
Switch metallb jobs to equinix-ocp-metal profile

### PR DESCRIPTION
**Pull request by fedepaol**
The old profile is getting dismissed, switching to the new one.

### CODE REVIEW

**Comment by sabinaaledort** [comment]
the 4.9 lanes are failing as dev-scripts are running later version of MetalLB tests that wasn't backported. we should remove these lanes for now and work on setting another 4.9 CI.

**Comment by sabinaaledort** [comment]
frr/master/ovn lane failed due to the following error which might be related to timing. the tests are running in operator mode. we clean the configmap but we are not waiting for the addresspool object to be deleted before starting the next test.
```
BGP
[90m/root/dev-scripts/metallb/metallb/e2etest/bgptests/bgp.go:58[0m
  BFD
  [90m/root/dev-scripts/metallb/metallb/e2etest/bgptests/bgp.go:443[0m
    should work with the given bfd profile
    [90m/root/dev-scripts/metallb/metallb/e2etest/bgptests/bgp.go:444[0m
      [91m[1mIPV4 - full params [It][0m
      [90m/root/dev-scripts/metallb/metallb/e2etest/bgptests/bgp.go:506[0m

      [91mFeb  8 10:46:50.641: Unexpected error:
          <*errors.StatusError | 0xc000963680>: {
              ErrStatus: {
                  TypeMeta: {Kind: "", APIVersion: ""},
                  ListMeta: {
                      SelfLink: "",
                      ResourceVersion: "",
                      Continue: "",
                      RemainingItemCount: nil,
                  },
                  Status: "Failure",
                  Message: "admission webhook \"addresspoolvalidationwebhook.metallb.io\" denied the request: CIDR \"192.168.10.0/24\" in pool bfd-test overlaps with already defined CIDR \"192.168.10.0/24\" in pool l2-test",
                  Reason: "CIDR \"192.168.10.0/24\" in pool bfd-test overlaps with already defined CIDR \"192.168.10.0/24\" in pool l2-test",
                  Details: nil,
                  Code: 403,
              },
          }
          admission webhook "addresspoolvalidationwebhook.metallb.io" denied the request: CIDR "192.168.10.0/24" in pool bfd-test overlaps with already defined CIDR "192.168.10.0/24" in pool l2-test
      occurred[0m
```

**Comment by msherif1234** [comment]
we need this merged 1st so we can fix the CI issues

**Pull request merged**
