### PR TITLE
OCPBUGS-28689: Switch sdn jobs to ovn(mao)

### PR DESCRIPTION
**Pull request by derekhiggins**
openshift-sdn is no longer supported for new installs

### CODE REVIEW

**Review by damdo — COMMENTED** [review]
/approve

**Comment by damdo** [comment]
@derekhiggins @elfosardo this is now ready for rehearsals

**Comment by derekhiggins** [comment]
/pj-rehearse pull-ci-openshift-machine-api-operator-release-4.16-e2e-metal-ipi

**Comment by derekhiggins** [comment]
/pj-rehearse pull-ci-openshift-machine-api-operator-release-4.16-e2e-metal-ipi

**Pull request merged**
