### PR TITLE
Only run E2E on the API repo when payload inputs change

### PR DESCRIPTION
**Pull request by JoelSpeed**
This is based on the content of the [Dockerfile.rhel8](https://github.com/openshift/api/blob/693f5c58db0c639e91d70bf4a6998a15846ef25b/Dockerfile.rhel8#L13-L32) within the repository. I have tried to make it so that the E2E only run when the inputs to the dockerfile, or the dockerfile itself changes.

### CODE REVIEW

**Comment by deads2k** [comment]
/lgtm
/hold

Once you think it works, we can go with it.  Or wait until we have a single folder.

**Comment by JoelSpeed** [comment]
/hold cancel

We have a single folder now

**Comment by JoelSpeed** [comment]
/pj-rehearse ack

This isn't a rehearsable change

**Pull request merged**
