### PR TITLE
WINC-1191: add azure upgrade test to release 4.12

### PR DESCRIPTION
**Pull request by jrvaldes**
This commit introduces the azure-e2e-upgrade test
in the release 4.12 branch.

### CODE REVIEW

**Comment by jrvaldes** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-azure-e2e-upgrade

**Review by saifshaikh48 — COMMENTED** [review]
/lgtm

thanks for adding this

**Comment by alinaryan** [comment]
LGTM

**Comment by jrvaldes** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-azure-e2e-upgrade

to gather another data point

**Comment by jrvaldes** [comment]
ci/rehearse/openshift/windows-machine-config-operator/release-4.12/azure-e2e-upgrade

as per [wmco logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/47918/rehearse-47918-pull-ci-openshift-windows-machine-config-operator-release-4.12-azure-e2e-upgrade/1749524289960284160/artifacts/azure-e2e-upgrade/gather-extra/artifacts/pods/openshift-windows-machine-config-operator_windows-machine-config-operator-55dd769466-6k65w_manager.log) intermitent network blips prevented instance configuration in the expected time.

**Comment by jrvaldes** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-azure-e2e-upgrade

instance configuration succeded, test timed out.

**Comment by jrvaldes** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-azure-e2e-upgrade

**Comment by jrvaldes** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-azure-e2e-upgrade

**Comment by jrvaldes** [comment]
> /hold
> 
> interesting error in the rehearsal
> 
> > time="2024-01-22T16:49:56Z" level=fatal msg="Failed to run bundle upgrade: update catalog error: error in upgrading FBC: error creating the upgraded FBC: error creating new image registry: mkdir registry.build05.ci.openshift.org-ci-op-wp5i7fjp-pipeline@sha256:9df120e970b96716bb2d2c68969b45403ae5a77f140e38e150beb8a6a24acf01_registry.build05.ci.openshift.org-ci-op-wp5i7fjp-pipeline@sha256:8a631857c164d3eb97c53d44f6ac7bfdda8e44ba30c72ba947619c1debdbe287: file name too long\n"

pushed https://github.com/openshift/release/pull/47918/commits/b7ab3e61e166c72e8b231dd68ca51db5eaaba83f to address this.

**Comment by jrvaldes** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-azure-e2e-upgrade

**Comment by jrvaldes** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-azure-e2e-upgrade

deployment timed out

**Comment by jrvaldes** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-azure-e2e-upgrade

ipi install failed

**Comment by jrvaldes** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-azure-e2e-upgrade

**Comment by jrvaldes** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-azure-e2e-upgrade

[failed](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/47918/rehearse-47918-pull-ci-openshift-windows-machine-config-operator-release-4.12-azure-e2e-upgrade/1751698656194465792), no nodes are available to run the test

**Comment by jrvaldes** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-azure-e2e-upgrade

**Comment by jrvaldes** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-azure-e2e-upgrade

**Comment by jrvaldes** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-azure-e2e-upgrade

**Comment by jrvaldes** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-azure-e2e-upgrade

**Comment by jrvaldes** [comment]
/hold

depends on:
- https://github.com/openshift/windows-machine-config-operator/pull/2050

**Comment by jrvaldes** [comment]
/hold cancel

blocking PR merged.

- https://github.com/openshift/windows-machine-config-operator/pull/2050

**Comment by jrvaldes** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-azure-e2e-upgrade

**Comment by jrvaldes** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-azure-e2e-upgrade

win node configuration succeded, validation test timed out.

**Comment by jrvaldes** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-azure-e2e-upgrade

**Comment by jrvaldes** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-azure-e2e-upgrade

**Comment by jrvaldes** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-azure-e2e-upgrade

**Comment by jrvaldes** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-azure-e2e-upgrade

**Comment by jrvaldes** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-azure-e2e-upgrade

**Comment by jrvaldes** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-azure-e2e-upgrade

**Comment by jrvaldes** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-azure-e2e-upgrade

**Comment by jrvaldes** [comment]
/pj-rehearse ack 

cc @sebsoto   job [passed](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/47918/rehearse-47918-pull-ci-openshift-windows-machine-config-operator-release-4.12-azure-e2e-upgrade/1758347487417995264)

**Comment by sebsoto** [comment]
/approve
Nice solution with the `operator-sdk cleanup` command

**Pull request merged**
