### PR TITLE
Cli latest

### PR DESCRIPTION
**Pull request by paigerube14**
Adding cli latest that when we cut a new dockerfile without oc installed we will properly get the latest CLI 

lots of comments and tests in https://github.com/openshift/release/pull/54209

This is splitting out functionality that hopefully will be harmless for now

### CODE REVIEW

**Comment by nathan-weinberg** [comment]
I uh don't know why I was added to this :sweat_smile:

**Comment by paigerube14** [comment]
Will want to merge the pr [here](https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/630) after this is merged

**Comment by paigerube14** [comment]
> I uh don't know why I was added to this 😅

@nathan-weinberg honestly no idea how it found your user. You can try to unassign yourself. Sorry about the noise

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-nightly-x86-sno-control-plane

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-nightly-x86-sno-control-plane

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.17-nightly-x86-control-plane-3nodes

**Comment by nathan-weinberg** [comment]
> > I uh don't know why I was added to this 😅
> 
> @nathan-weinberg honestly no idea how it found your user. You can try to unassign yourself. Sorry about the noise

No worries!

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.17-nightly-x86-control-plane-3nodes

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.17-nightly-x86-control-plane-3nodes

**Comment by vishnuchalla** [comment]
> @vishnuchalla @afcollins @qiliRedHat @jtaleric PTAL, this PR I split out adding the latest cli from [this PR](https://github.com/openshift/release/pull/54209) so that when we update the [dockerfile to not have oc installed](https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/630) we shouldn't see any failures in the images
> 
> This shouldn't change any of the current functionality

So can we discard [this PR](https://github.com/openshift/release/pull/54209) now?

**Comment by qiliRedHat** [comment]
@paigerube14  Reading the below comment in https://github.com/openshift/release/pull/54209, my understanding is though no cli is defined in the config file, job will 'get the latest version of the cli that was the same version as the ocp installed version'
> Another test I did, when there was no cli defined in the config file it was still able to get the latest version of the cli that was the same version as the ocp installed version: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/54209/rehearse-54209-pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-gcp-4.15-nightly-arm-test/1816839020982833152/artifacts/test/openshift-qe-test/build-log.txt

My concern is, for those test step like 'openshift-qe-move-pods-infra' which does not have ocp installed, where will it get the oc cli without it defined in the config file?

Another question is, from the pj-rehearse job you run in this pr, the version oc cli version is 4.16.2 instead of 4.17 that is the ocp installed version. How could we know the 4.16.2 is NOT from the docker image from https://github.com/openshift-qe/ocp-qe-perfscale-ci/blob/main/prow/Dockerfile? 
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/54886/rehearse-54886-pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.17-nightly-x86-control-plane-3nodes/1817916092631224320/artifacts/control-plane-3nodes/openshift-qe-cluster-density-v2/build-log.txt 
> + oc version
Client Version: 4.16.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: 4.17.0-0.nightly-2024-07-29-061317

**Comment by paigerube14** [comment]
@qiliRedHat 

1. For the 'openshift-qe-move-pods-infra' it will take which ever cli is defined in the test itself its. So if the test is 4.15 the cli set would be 4.15 so the infra step would get 4.15. Same thing as how any of the kube-burner tests I have done 
2. See [comment here](https://github.com/openshift/release/pull/54209#issuecomment-2248626424) about past runs. If the oc is properly set up per test version it should show a version the same as the ocp version installed. 
4.16.2 is the latest stable right now that any reference to the latest ci from_image of  ocp-qe-perfscale-ci will have that set unless we use the docker test file that has no cli set and then cli: latest will take effect 

[4.17 test](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/54209/rehearse-54209-pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.17-nightly-x86-test/1815433043255496704/artifacts/test/openshift-qe-test/build-log.txt)

```
Python 3.9.9
/tmp /
created virtual environment CPython3.9.9.final.0-64 in 354ms
  creator CPython3Posix(dest=/tmp/venv_qe, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/alabama/.local/share/virtualenv)
    added seed packages: pip==24.1, setuptools==70.1.0, wheel==0.43.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
Client Version: 4.17.0-202407190341.p0.g4cd37ca.assembly.stream.el9-4cd37ca
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: 4.17.0-0.nightly-2024-07-20-191204
Kubernetes Version: v1.30.2
```

**Comment by paigerube14** [comment]
> this PR

@vishnuchalla I'm going to update that pr with some other changes once this pr and [this one](https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/630#issuecomment-2253236243) are merged since I had a lot of comments/details in there

**Pull request merged**
