### PR TITLE
DEVEXP-533: bump OCM ocp golang image to 1.13

### PR DESCRIPTION
**Pull request by gabemontero**

### CODE REVIEW

**Comment by gabemontero** [comment]
Well the config file change, bumping the 2nd golang ref to 1.13, had no bearing on the core image problem I was seeing:

```
could not wait for build: the build openshift-controller-manager failed after 57s with reason DockerBuildFailed: Docker build strategy has failed.

--> ENV "foo"="bar"
--> WORKDIR /go/src/github.com/openshift/openshift-controller-manager
--> RUN yum install -y gpgme-devel libassuan-devel
/bin/sh: line 0: cd: /go/src/github.com/openshift/openshift-controller-manager: No such file or directory
error: build error: running 'yum install -y gpgme-devel libassuan-devel' failed with exit code 1
```

Might have to start adding some debug / experiment with removing that yum install (I've had conversations in the past which indicated those were nice to haves vs. necessities)

**Comment by gabemontero** [comment]
/hold

this needs the dockerfile change in https://github.com/openshift/openshift-controller-manager/pull/85 to merge before the rehearsal jobs will pass

**Comment by gabemontero** [comment]
/hold cancel

@adambkaplan IMO enough of the rehearsal jobs have passed that this OCM bump to golang 1.13 is vetted and we can lgm (where with this repo, not all of the rehearsals have to pass to merge)

I see a double digit amount of various e2e-* jobs passing across the various branches

Among things, jobs like https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/8104/rehearse-8104-pull-ci-openshift-openshift-controller-manager-master-e2e-gcp-builds/3 

were hitting the `Timed out waiting for internal registry hostname to be published` OCM rollout pain we were just discussing, and are not related to golang 1.13

WDYT ?

**Comment by adambkaplan** [comment]
/lgtm

The golang delta between 1.12 and 1.13 is small - a lot of changes happened on the tooling end. We shouldn't wait on CI for this.

**Pull request merged**
