### PR TITLE
Fix golang version

### PR DESCRIPTION
**Pull request by liangxia**
/cc @kuiwang02 @Xia-Zhao-rh @jianzhangbjz

### CODE REVIEW

**Comment by kuiwang02** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.6-images-images

**Comment by kuiwang02** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.7-images-images

**Comment by liangxia** [comment]
> /pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.7-images-images

Those tests are already executed and passed

**Comment by kuiwang02** [comment]
> > /pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.7-images-images
> 
> Those tests are already executed and passed

yes. I am sorry I do not notice it at the beginning.
and then I find it, and add lgtm.

thanks

**Pull request merged**
