### PR TITLE
OSASINFRA-3618: Reflect changes to Cinder CSI driver operator

### PR DESCRIPTION
**Pull request by stephenfin**
The location of files have changed [1]. Reflect this.

~[1] must merge before we can merge this.~ This PR is merged now.

[1] https://github.com/openshift/csi-operator/pull/275

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
/lgtm

**Comment by stephenfin** [comment]
/pj-rehearse pull-ci-openshift-csi-operator-release-4.19-e2e-openstack-cinder-csi

**Comment by mandre** [comment]
I'm pretty sure the failure is caused by the load of jobs hitting the same infra node at the same time, let's try again with just the failing job:
/pj-rehearse pull-ci-openshift-csi-operator-release-4.19-e2e-openstack-cinder-csi

**Review by mandre — COMMENTED** [review]
/lgtm

**Pull request merged**
