### PR TITLE
ovn-kubernetes: re-add un-suffixed image names

### PR DESCRIPTION
**Pull request by dcbw**
Now that https://github.com/openshift/ovn-kubernetes/pull/1553 landed which copies the RHEL9-suffixed Dockerfiles back over the regular Dockerfiles, we can re-enable building images using the non-suffixed names.

After this works, we can retarget the CNO to use the non-suffixed images.

Then we can remove the openshift/release bits that build them.

Then we can finally remove the the -rhel-9 Dockerfiles.

### CODE REVIEW

**Comment by dcbw** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-master-okd-images

**Comment by dcbw** [comment]
/pj-rehearse ack

The only things this PR affects are image builds for OCP and OKD, and those both passed. The images aren't actually used yet, so can't possibly affect any of the rehearse jobs.

**Comment by bparees** [comment]
carries forward existing image names
/approve

**Pull request merged**
