### PR TITLE
add more resources to get collected

### PR DESCRIPTION
**Pull request by deads2k**
Adding endpoints, apiservices, and the detailed status of controlplane operators.

@tnozicka look correct?

### CODE REVIEW

**Comment by smarterclayton** [comment]
You need to change installer-src as well

**Comment by deads2k** [comment]
> You need to change installer-src as well

which one?  I thought I got both of them.

**Comment by tnozicka** [comment]
looks good, maybe sync it to byor template as well https://github.com/openshift/release/blob/8f2193b570325524a1f244a727941621a7624682/ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-40.yaml#L434

**Comment by stevekuznetsov** [comment]
/hold 

for the changes @tnozicka asked for

**Pull request merged**
