### PR TITLE
stackrox: build the operator using a local image

### PR DESCRIPTION
**Pull request by gavin-stackrox**
Builds the operator with a mirrored golang 1.17.2.
/hold
/uncc

### CODE REVIEW

**Comment by gavin-stackrox** [comment]
@porridge FYI, I tried using a local image for golang-1.17 to avoid the rate limiting problem but it is not [working](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/31090/rehearse-31090-pull-ci-stackrox-stackrox-master-images/1555366896797224960). 
Another idea is that we could mirror the docker.io image via OpenShift CIs supplemental_images.

**Comment by porridge** [comment]
Looks like the cause could be some antiquated `git` version, and lack of error checking in our scripts?
```
[1/2] STEP 16/17: RUN GOOS=$(go env GOOS) scripts/go-build.sh operator
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
```

**Comment by porridge** [comment]
Indeed, the `registry.ci.openshift.org/openshift/release:golang-1.17` image seems to have git `1.8.3.1`, apparently [released **over 9 years ago**](https://github.com/git/git/releases/tag/v1.8.3.1). 🤯 
Perhaps the base image does receive security fixes somehow, but I think using software that old will just cause never ending compatibility issues.

**Comment by porridge** [comment]
Google is finding no relevant hits for `["supplemental_images"]`. Do you have more information about this @gavin-stackrox ?

**Comment by gavin-stackrox** [comment]
I'll close this. Another way to do this is with a mirror and use.

**Comment by gavin-stackrox** [comment]
@porridge the build looks good: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/31090/rehearse-31090-pull-ci-stackrox-stackrox-master-images/1559457830782636032/artifacts/build-logs/operator-controller.log

I'll wait for the e2e tests to pass before releasing the hold on this PR.

Can you `/lgtm`?

**Comment by porridge** [comment]
Aaand of course its's impossible to add comments to this file :-(
@gavin-stackrox please instead add the following piece of text to the PR description:
```
See [this PR](https://github.com/openshift/release/pull/31357) for an example of how to set up the mirroring.
```

We probably want the same change in `ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies.yaml`, right?

However if you prefer this can be done in a separate PR, so in principle this is good to go
/lgtm

OTOH I'm wondering how we will be updating this going forward?
AFAICT this line in `operator/Dockerfile` now needs to match the entry under `as:` on line 89, right?
Now let's say we want to go switch to `1.17.13`, we will have the following four PRs to make:
1. new line in [`core-services/image-mirroring/stackrox/mapping_supplemental_ci_images_stackrox_base_images:`](https://github.com/openshift/release/pull/31357/files#diff-7c5d7540651c34d2f76e45fd13ae4023fb2d79e6a0e410a98e69a5d78ae81e0c)
2. new stanza in `base_images`, as well as a new setting in `inputs` of `operator-controller` in this file (and the nightly one) - I **hope** these can be added without problems even if they happen not to be used or match anything?
3. `EXPECTED_GO_VERSION` and `operator/Dockerfile:FROM golang:1.17.2 as builder` in the `stackrox/stackrox` repo
4. remove the old entries for (2)

If the above makes sense, can we document it somewhere?

**Comment by gavin-stackrox** [comment]
> Aaand of course its's impossible to add comments to this file :-( @gavin-stackrox please instead add the following piece of text to the PR description:
> 
> ```
> See [this PR](https://github.com/openshift/release/pull/31357) for an example of how to set up the mirroring.
> ```
> 
> We probably want the same change in `ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies.yaml`, right?

Yes.

> However if you prefer this can be done in a separate PR, so in principle this is good to go /lgtm
> 
> OTOH I'm wondering how we will be updating this going forward? AFAICT this line in `operator/Dockerfile` now needs to match the entry under `as:` on line 89, right? Now let's say we want to go switch to `1.17.13`, we will have the following four PRs to make:
> 
> 1. new line in [`core-services/image-mirroring/stackrox/mapping_supplemental_ci_images_stackrox_base_images:`](https://github.com/openshift/release/pull/31357/files#diff-7c5d7540651c34d2f76e45fd13ae4023fb2d79e6a0e410a98e69a5d78ae81e0c)
> 2. new stanza in `base_images`, as well as a new setting in `inputs` of `operator-controller` in this file (and the nightly one) - I **hope** these can be added without problems even if they happen not to be used or match anything?
> 3. `EXPECTED_GO_VERSION` and `operator/Dockerfile:FROM golang:1.17.2 as builder` in the `stackrox/stackrox` repo
> 4. remove the old entries for (2)
> 
> If the above makes sense, can we document it somewhere?

It makes sense though I think there is more to do like update the `rox-ci-image` `stackrox-build`

**Pull request merged**
