### PR TITLE
Add configs for openshift/ovn-kubernetes

### PR DESCRIPTION
**Pull request by dcbw**
Add CI configs for openshift/ovn-kubernetes. Need to merge https://github.com/openshift/ovn-kubernetes/pull/2 so we have the dockerfile, but other than that I think this is all we need?  If not please let me know and I'll fix it up. Thanks!

@pecameron @stevekuznetsov @petr-muller

### CODE REVIEW

**Comment by dcbw** [comment]
Note that builds/CI will likely fail until https://github.com/openshift/ovn-kubernetes/pull/2 merges.

**Comment by droslean** [comment]
/hold

Hold until [openshift/ovn-kubernetes#2](https://github.com/openshift/ovn-kubernetes/pull/2)

**Comment by petr-muller** [comment]
> other than that I think this is all we need? If not please let me know and I'll fix it up. Thanks!

/lgtm
/approve

The config is fine. @droslean I don't think this needs to really wait for https://github.com/openshift/ovn-kubernetes/pull/2. Many people merge CI setup first and finish the bits their repo needs afterwards. There's no problem with that.

**Pull request merged**
