### PR TITLE
Add execution time to junit xml report

### PR DESCRIPTION
**Pull request by liangxia**
Previously, the time field is hard code to "1", and got removed in https://github.com/openshift/release/pull/45356

Instead of simply remove it (which cause some issue for the classifier job from prow to reportportal), fix the field with meaningful test execution time.

### CODE REVIEW

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-azure-ipi-sdn-f14  periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-gcp-ipi-sdn-arm-f14

**Comment by liangxia** [comment]
Verified the change [works](https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/45992/rehearse-45992-periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-azure-ipi-sdn-f14/1727616826541608960/artifacts/azure-ipi-sdn-f14/fips-check-node-scan/artifacts/fips-check-node-scan.xml),
```
<testsuite name="fips-check-node-scan" failures="0" errors="0" skipped="0" tests="1" time="51">
<testcase name="Security_and_Compliance:Node scan of fips check should succeedded or skipped"/>
</testsuite>
```

**Comment by JianLi-RH** [comment]
Is SECONDS a buildin variable? just curious about it.

/lgtm

**Comment by liangxia** [comment]
> Is SECONDS a buildin variable? just curious about it.

@JianLi-RH Yes. You can verify that by `man sh` ( or `man bash`), then search with `SECONDS`

**Review by r4f4 — COMMENTED** [review]
/approve

**Pull request merged**
