### PR TITLE
OSSM maistra fix istio e2e workflow env

### PR DESCRIPTION
**Pull request by yxun**

### CODE REVIEW

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-integ-servicemesh-multicluster-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-maistra-istio-push-image-2-4

**Comment by jwendell** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.3-integ-servicemesh-2-3

**Comment by jwendell** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.3-integ-servicemesh-multicluster-2-3

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.3-integ-servicemesh-2-3

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.3-integ-servicemesh-multicluster-2-3

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-integ-pilot-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-integ-pilot-2-4

**Comment by yxun** [comment]
this PR fix will be large. Here are reasons I want to explain here:

1. The existing istio integ test runs are not using BUILD_WITH_CONTAINER env
and they take little amount of cpu resources.
The existing workflow follows cluster_claim  approach by running on a standby cluster.
However, there are fewer than 2 cpus resource in those standby clusters.

 2. The required istio integ test runs will set BUILD_WITH_CONTAINER='0' env
Those jobs will include building steps in each run. They need around 4-8 CPUs.
With 1-2 CPU each run takes more than 2 hours. (timeout and not stable)

3. So I have to replace the cluster_claim approach with a cluster_profile one.
Then a test job will start provisioning a new cluster and run tests with enough CPU resources.

4. However, we also have some smaller jobs like maistra istio-images-centos, istio-operator jobs which work with 2 cpus resource.
I renamed the existing workflow and keep smaller jobs with cluster_claim
I created a new workflow for istio integ test jobs.

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.3-integ-servicemesh-2-3

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.3-integ-servicemesh-multicluster-2-3

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.3-integ-pilot-2-3

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.3-integ-pilot-2-3

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.3-integ-pilot-2-3

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.3-integ-servicemesh-2-3

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.3-integ-servicemesh-multicluster-2-3

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-integ-servicemesh-multicluster-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-3.0-integ-pilot-3-0

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-maistra-istio-push-image-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.3-integ-servicemesh-2-3

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.3-integ-servicemesh-2-3

**Pull request merged**
