### PR TITLE
OCPQE-20012: Baremetal IPI on other arches than the AUX_HOST's one

### PR DESCRIPTION
**Pull request by aleskandro**
To support deployments of IPI on BM clusters having a control plane with architecture different than the one of the auxiliary host we use for the provisioning, we require another auxiliary host to run the bootstrap VM. This additional host is now deployed in the internal network and reachable through forwarding from the main (arm64) auxiliary host. This PR patches the baremetal/lab steps by:
- Removing the need for the PROVISIONING_HOST variable: it is now considered the same as the AUX_HOST one
- Using a file for each architecture in the cluster profile dir to set the port to reach the provisioning host via ssh
- Using a file for each architecture in the cluster profile dir to set the interface to bind the provisioning network (and removes the PROVISIONING_NET_DEV variable)

Finally, this PR adds a job to test IPI on x86_64 BM w/ provisioning network.

Successful installation: https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/50236/rehearse-50236-periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-amd-f7/1773343115231367168

### CODE REVIEW

**Comment by aleskandro** [comment]
periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-amd-f7

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-amd-f7

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-amd-f7

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-amd-f7

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-amd-f7

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-amd-f7

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-amd-f7

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-amd-f7

**Pull request merged**
