### PR TITLE
Added multi-arch cluster-samples-operator jobs to 4.6 periodics file

### PR DESCRIPTION
**Pull request by jaypoulz**

### CODE REVIEW

**Comment by jaypoulz** [comment]
I don't want to keep spinning on build failures for 4.6 on s390x. There's clearly something intermittently broken with deploys of 4.6 on s390x, but not with the actual image streams being tested. So this PR is good to added to our running jobs as we work towards resolving those.

**Review by stevekuznetsov — APPROVED** [review]

**Pull request merged**
