### PR TITLE
fix(SRVKP-5785): Package setup issue from deprecated Mirrorlist

### PR DESCRIPTION
**Pull request by rh-rahulshetty**
Resolve issue with failing package setup due to broken mirrorlist in **openshift-pipelines-performance-runner**

### CODE REVIEW

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-2500-sign-tekton-bigbang-ha

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-2500-sign-tekton-bigbang-ha

**Comment by rh-rahulshetty** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-2500-sign-tekton-bigbang-ha

**Review by khrm — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
