### PR TITLE
MGMT-15863 - fix resources for assisted-cnv e2e

### PR DESCRIPTION
**Pull request by eifrach**

### CODE REVIEW

**Comment by eifrach** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-cnv-periodic

**Comment by eifrach** [comment]
/pj-rehearse  pull-ci-openshift-assisted-service-cloud_hotfix_releases-e2e-metal-assisted-cnv pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted-cnv

**Comment by eifrach** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted-cnv

**Comment by eifrach** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-cnv-periodic

**Comment by eifrach** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-cnv-periodic

**Comment by eifrach** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted-cnv

**Review by adriengentil — APPROVED** [review]

**Review by gamli75 — APPROVED** [review]

**Pull request merged**
