### PR TITLE
Use latest images for HO and e2e tests

### PR DESCRIPTION
**Pull request by simonpasquier**

### CODE REVIEW

**Comment by simonpasquier** [comment]
/pj-rehearse pull-ci-openshift-monitoring-plugin-main-e2e-hypershift-conformance, pull-ci-openshift-cluster-monitoring-operator-release-master-e2e-hypershift-conformance

**Comment by simonpasquier** [comment]
/pj-rehearse pull-ci-openshift-monitoring-plugin-main-e2e-hypershift-conformance pull-ci-openshift-cluster-monitoring-operator-release-master-e2e-hypershift-conformance

**Comment by simonpasquier** [comment]
/pj-rehearse pull-ci-openshift-cluster-monitoring-operator-master-e2e-hypershift-conformance

**Review by slashpai — APPROVED** [review]
/lgtm

**Pull request merged**
