### PR TITLE
MGMT-11419: fix makefile target vsphere-kube-api

### PR DESCRIPTION
**Pull request by danielerez**
Use 'setup' target instead of 'create_full_environment'.

### CODE REVIEW

**Comment by omertuc** [comment]
Why

**Comment by danielerez** [comment]
> Why

Used the old 'create_full_environment' target by mistake in https://github.com/openshift/release/pull/31171

**Comment by omertuc** [comment]
Oh, `create_full_environment` doesn't even exist. ok

**Comment by danielerez** [comment]
> Details

Thanks:) Rehearse won't work yet. Still depends on test-infra change: https://github.com/openshift/assisted-test-infra/pull/1786

**Comment by omertuc** [comment]
ack
/unhold

**Review by eliorerz — APPROVED** [review]

**Pull request merged**
