### PR TITLE
vsphere: netmgr debug

### PR DESCRIPTION
**Pull request by jcpowermac**

### CODE REVIEW

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn periodic-ci-openshift-release-master-nightly-4.15-e2e-vsphere-ovn periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn periodic-ci-openshift-release-master-nightly-4.15-e2e-vsphere-ovn periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn

**Comment by cybertron** [comment]
/lgtm

I'm not seeing any worker sosreports and we don't capture worker service logs in must-gather so I can't confirm that this is working, but it looks correct so I think it's good to go.

**Comment by jcpowermac** [comment]
fyi @rvanderp3 @vr4manta @sgaoshang

**Pull request merged**
