### PR TITLE
Adding new es variables

### PR DESCRIPTION
**Pull request by paigerube14**
Need to set new variables, still work in progress

### CODE REVIEW

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-lib-test

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-lib-test

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-component-readiness-krkn-hub-component-readiness-417

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-lib-test

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-component-readiness-krkn-hub-component-readiness-417

**Comment by paigerube14** [comment]
@shahsahil264 @chaitanyaenr PTAL passing job here: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/56144/rehearse-56144-periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-component-readiness-krkn-hub-component-readiness-417/1831319810613448704

**Review by shahsahil264 — APPROVED** [review]
LGTM

**Pull request merged**
