### PR TITLE
[ignore me] Add must-gather-inspector to must-gather

### PR DESCRIPTION
**Pull request by pierreprinetti**

### CODE REVIEW

**Comment by elmiko** [comment]
this looks like a cool way to integrate the camgi, many thanks for showing the way ;)

**Comment by pierreprinetti** [comment]
Looks like we can’t use $SHARED_DIR to pass the must-gather to the next step, because there is a limit on the blobs we can push to $SHARED_DIR:

Running must-gather... error: failed to create/update secret: failed to update secret: Request entity too large: limit is 3145728

**Comment by elmiko** [comment]
> We will probably need to force okd-camgi into gather/must-gather afterall

that seems to increase the difficulty, but at least we have a patch for it ;)

**Pull request closed without merging**
