### PR TITLE
HCO: move the okd upgrade tests to use operator-sdk

### PR DESCRIPTION
**Pull request by nunnatsa**

### CODE REVIEW

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-upgrade-operator-sdk-aws pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-upgrade-operator-sdk-gcp

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-upgrade-operator-sdk-aws pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-upgrade-operator-sdk-gcp

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-upgrade-operator-sdk-aws pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-upgrade-operator-sdk-gcp

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-upgrade-operator-sdk-gcp

**Review by tiraboschi — APPROVED** [review]

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
