### PR TITLE
SPLAT-1620: WIP: testing vsphere capacity manager

### PR DESCRIPTION
**Pull request by rvanderp3**
WIP PR for testing the vsphere capacity manager

### CODE REVIEW

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn

**Comment by rvanderp3** [comment]
/pj-rehearse ci/rehearse/periodic-ci-openshift-release-master-nightly-4.15-e2e-vsphere-ovn ci/rehearse/periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn

**Comment by rvanderp3** [comment]
/pj-rehearse ci/rehearse/periodic-ci-openshift-release-master-nightly-4.15-e2e-vsphere-ovn

**Comment by rvanderp3** [comment]
/pj-rehearse ci/rehearse/periodic-ci-openshift-release-master-nightly-4.15-e2e-vsphere-ovn

**Comment by rvanderpol3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-vsphere-ovn

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-vsphere-ovn

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-vsphere-ovn

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-vsphere-ovn

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-vsphere-ovn

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-release-4.15-e2e-vsphere

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-release-4.15-e2e-vsphere

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-release-4.15-e2e-vsphere

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-release-4.15-e2e-vsphere

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-release-4.15-e2e-vsphere

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-release-4.15-e2e-vsphere

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-release-4.15-e2e-vsphere

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-release-4.15-e2e-vsphere

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-release-4.15-e2e-vsphere

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-release-4.15-e2e-vsphere

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-release-4.15-e2e-vsphere

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-release-4.16-e2e-vsphere

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-release-4.14-e2e-vsphere

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-release-4.16-e2e-vsphere pull-ci-openshift-cluster-image-registry-operator-release-4.15-e2e-vsphere pull-ci-openshift-cluster-image-registry-operator-release-4.14-e2e-vsphere

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-release-4.16-e2e-vsphere periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-zones

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-release-4.16-e2e-vsphere periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-zones

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-release-4.16-e2e-vsphere periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-zones pull-ci-openshift-installer-master-altinfra-e2e-vsphere-capi-multi-vcenter-ovn

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-release-4.16-e2e-vsphere periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-zones pull-ci-openshift-installer-master-altinfra-e2e-vsphere-capi-multi-vcenter-ovn

**Comment by rvanderpol3** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-release-4.16-e2e-vsphere periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-zones pull-ci-openshift-installer-master-altinfra-e2e-vsphere-capi-multi-vcenter-ovn

**Comment by rvanderpol3** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-release-4.16-e2e-vsphere periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-zones pull-ci-openshift-installer-master-altinfra-e2e-vsphere-capi-multi-vcenter-ovn

**Comment by rvanderpol3** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-release-4.16-e2e-vsphere periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-zones pull-ci-openshift-installer-master-altinfra-e2e-vsphere-capi-multi-vcenter-ovn

**Comment by rvanderpol3** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-release-4.16-e2e-vsphere periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-zones pull-ci-openshift-installer-master-altinfra-e2e-vsphere-capi-multi-vcenter-ovn periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-externallb-ovn periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-stable-vsphere-ipi-proxy-fips-f14

**Comment by rvanderpol3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-externallb-ovn

**Comment by rvanderpol3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-externallb-ovn periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-zones

**Comment by rvanderpol3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-externallb-ovn periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-zones

**Comment by rvanderpol3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-zones

**Comment by rvanderpol3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-externallb-ovn periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-zones

**Comment by rvanderpol3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-externallb-ovn periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-zones

**Comment by rvanderpol3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-externallb-ovn periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-zones

**Comment by rvanderpol3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-externallb-ovn

**Comment by rvanderpol3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-externallb-ovn

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-upi-zones

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-upi

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.7-e2e-vsphere-upi

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-upi-zones

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-upi-zones

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-upi-zones

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-upi-zones

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-upi-zones

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-upi-zones

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-upi-zones

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-upi-zones

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-upi-zones

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-upi-zones

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-upi-zones

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-upi-zones

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-upi-zones

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-upi-zones

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-upi-zones

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-upi-zones

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-upi-zones

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-upi-zones

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-upi-zones

**Pull request closed without merging**
