### PR TITLE
Add nutanix qe secret

### PR DESCRIPTION
**Pull request by sgaoshang**

### CODE REVIEW

**Review by droslean — APPROVED** [review]

**Comment by smg247** [comment]
@sgaoshang the `ci-secret-bootstrap` job is failing with the following error:
```
key ssh-privatekey in secret XX/cluster-secrets-nutanix-qe in cluster arm01 is targeted by XX-secret-bootstrap config and by vault item in path kv/selfservice/openshift-qe/nutanix-qe, ...
```
It appears that a secret with this same name already exists on Vault selfservice. Can you either revert this PR or remove/rename the offending secret?

**Pull request merged**
