### PR TITLE
vsphere: move older jobs to new cluster

### PR DESCRIPTION
**Pull request by jcpowermac**

### CODE REVIEW

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.12-e2e-vsphere-ovn

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.12-e2e-vsphere-upi

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-platform-none-vsphere-e2e-operator pull-ci-openshift-windows-machine-config-operator-release-4.12-vsphere-e2e-operator pull-ci-openshift-ovn-kubernetes-release-4.12-e2e-vsphere-ovn

**Comment by jcpowermac** [comment]
Missing static dns entry for `v8c-2-vcenter.ocp2.dev.cluster.com`, added on the vyatta


/pj-rehearse pull-ci-openshift-installer-release-4.12-e2e-vsphere-ovn pull-ci-openshift-installer-release-4.12-e2e-vsphere-upi pull-ci-openshift-windows-machine-config-operator-release-4.12-platform-none-vsphere-e2e-operator pull-ci-openshift-windows-machine-config-operator-release-4.12-vsphere-e2e-operator pull-ci-openshift-ovn-kubernetes-release-4.12-e2e-vsphere-ovn

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-platform-none-vsphere-e2e-operator pull-ci-openshift-windows-machine-config-operator-release-4.12-vsphere-e2e-operator pull-ci-openshift-installer-release-4.12-e2e-vsphere-upi

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-vsphere-e2e-operator

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-platform-none-vsphere-e2e-operator pull-ci-openshift-windows-machine-config-operator-release-4.12-vsphere-e2e-operator pull-ci-openshift-installer-release-4.12-e2e-vsphere-upi

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-vsphere-e2e-operator

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-vsphere-e2e-operator

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-platform-none-vsphere-e2e-operator pull-ci-openshift-windows-machine-config-operator-release-4.12-vsphere-e2e-operator pull-ci-openshift-installer-release-4.12-e2e-vsphere-upi

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-platform-none-vsphere-e2e-operator pull-ci-openshift-windows-machine-config-operator-release-4.12-vsphere-e2e-operator pull-ci-openshift-installer-release-4.12-e2e-vsphere-upi

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-vsphere-e2e-operator

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-vsphere-e2e-operator

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-vsphere-e2e-operator

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-vsphere-e2e-operator

**Comment by jsafrane** [comment]
/approve
CSI driver + operator jobs

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.13-platform-none-vsphere-e2e-operator

**Comment by jcpowermac** [comment]
wrong version...
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.12-platform-none-vsphere-e2e-operator

**Comment by jrvaldes** [comment]
/lgtm

https://github.com/openshift/release/pull/43683/commits/0d232002c447b6a8e9fc8dc1a57928694e38aabb should be reverted after the following PR merges:

- https://github.com/openshift/windows-machine-config-operator/pull/1856
- https://github.com/openshift/windows-machine-config-operator/pull/1857

**Review by aravindhp — APPROVED** [review]

**Review by vrutkovs — APPROVED** [review]
/approve

**Comment by deads2k** [comment]
All the upper packages are approved.  Since this infra is maintained by the splat team, I think they logically own where it runs.  approving.

**Comment by jrvaldes** [comment]
> /lgtm
> 
> [0d23200](https://github.com/openshift/release/commit/0d232002c447b6a8e9fc8dc1a57928694e38aabb) should be reverted after the following PR merges:
> 
> * [[release-4.12] Remove hard-coded default network for vSphere e2e test windows-machine-config-operator#1856](https://github.com/openshift/windows-machine-config-operator/pull/1856)
> * [[release-4.11] Remove hard-coded default network for vSphere e2e test windows-machine-config-operator#1857](https://github.com/openshift/windows-machine-config-operator/pull/1857)



@jcpowermac  PRs merged, and `LEASED_RESOURCE` is no longer required for Windows jobs in vSphere. It should be safe to revert [0d23200](https://github.com/openshift/release/commit/0d232002c447b6a8e9fc8dc1a57928694e38aabb)

**Pull request merged**
