### PR TITLE
Power VS: Add premerge job for powervs

### PR DESCRIPTION
**Pull request by mjturek**

### CODE REVIEW

**Comment by r4f4** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-powervs-capi-ovn

**Comment by r4f4** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-powervs-capi-ovn

**Comment by hamzy** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-powervs-capi-ovn

**Comment by hamzy** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-powervs-capi-ovn

**Comment by hamzy** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-powervs-capi-ovn

**Pull request merged**
