### PR TITLE
virt, periodics, 4.19: enable TP feature set

### PR DESCRIPTION
**Pull request by maiqueb**
The feature is still TP, and we need data from the periodics to support this move.

### CODE REVIEW

**Comment by maiqueb** [comment]
/rehearsals-ack

The tests are passing (look for `OCPFeatureGate:PersistentIPsForVirtualization` in the list of passed tests in https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/59472/rehearse-59472-periodic-ci-openshift-ovn-kubernetes-release-4.19-periodics-e2e-aws-ovn-virt-techpreview-periodic/1864002712811606016) but the monitor tests fail on missing required SCCs. 

@qinqon  @kyrtapz would you lgtm ? We need to gather 4.19 results to graduate the feature.

**Comment by maiqueb** [comment]
@tssurya could you approve ?

**Review by tssurya — APPROVED** [review]

**Pull request merged**
