### PR TITLE
Update Security Profile Operator CI config tag

### PR DESCRIPTION
**Pull request by Vincent056**
We need to update golang version in CI to 1.21 so it can run successfully.

### CODE REVIEW

**Comment by Vincent056** [comment]
Close in favor using hard reset approach

**Comment by rhmdnd** [comment]
/pj-rehearse pull-ci-openshift-security-profiles-operator-main-e2e-operator
/pj-rehearse pull-ci-openshift-security-profiles-operator-main-e2e-flaky

**Comment by Vincent056** [comment]
close in favor of https://github.com/openshift/release/pull/46280

**Pull request closed without merging**
