### PR TITLE
[wip] debugging: add manifest to log to serial console

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade

**Review by cgwalters — APPROVED** [review]

**Comment by stbenjam** [comment]
/pj-rehearse abort

Install succeeded, trying to catch it failing

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-upgrade

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-aws-ovn-heterogeneous-upgrade

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-sdn-cgroupsv2

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-ovn-upgrade

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-fips

**Comment by cgwalters** [comment]
> Install succeeded, trying to catch it failing

I think though what we may find useful information even in passing job logs.

**Comment by stbenjam** [comment]
There are also already journal logs from hosts that were successful if you want to look at those:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade/1642808731659931648/artifacts/e2e-aws-ovn-upgrade/ipi-install-install-stableinitial/artifacts/

In the log-bundle, `control-plane/*/journals` has journals for the successful nodes

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-fips

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-ovn-upgrade

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-sdn-cgroupsv2

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-upgrade

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-fips

**Comment by stbenjam** [comment]
/pj-rehearse  ci/rehearse/periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-sdn-cgroupsv2

**Comment by stbenjam** [comment]
/pj-rehearse pull-ci-openshift-jenkins-client-plugin-master-e2e-aws-jenkins-client-plugin

**Comment by stbenjam** [comment]
/pj-rehearse pull-ci-openshift-cluster-storage-operator-master-e2e-aws-ovn

**Comment by stbenjam** [comment]
/pj-rehearse pull-ci-openshift-origin-master-e2e-aws-ovn-fips

**Comment by stbenjam** [comment]
/pj-rehearse pull-ci-openshift-origin-master-e2e-aws-ovn-serial

**Comment by stbenjam** [comment]
/pj-rehearse pull-ci-openshift-machine-config-operator-master-e2e-aws-ovn-upgrade

**Comment by stbenjam** [comment]
/pj-rehearse pull-ci-openshift-cluster-etcd-operator-master-e2e-aws-ovn-serial

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-sdn-cgroupsv2

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-upgrade

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade

**Comment by stbenjam** [comment]
/pj-rehearse pull-ci-openshift-cluster-etcd-operator-master-e2e-aws-ovn-serial

**Comment by stbenjam** [comment]
/pj-rehearse pull-ci-openshift-k8s-prometheus-adapter-release-4.12-e2e-agnostic-cmo

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-aws-ovn-heterogeneous-upgrade

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-fips

**Comment by stbenjam** [comment]
/pj-rehearse pull-ci-openshift-origin-master-e2e-aws-ovn-serial

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-aws-ovn-heterogeneous-upgrade

**Pull request closed without merging**
