### PR TITLE
Add openstack-upgrade-4.6-stable-to-4.7-ci periodic

### PR DESCRIPTION
**Pull request by vrutkovs**
Use `openshift-upgrade-openstack-loki` to add a 4.6 -> 4.7 ci upgrade job on openstack

TODO:
* [x] Steps use `openstack-installer`, which is not present in released payloads

### CODE REVIEW

**Comment by vrutkovs** [comment]
/retest

No output in rehearsal

**Comment by alvaroaleman** [comment]
/uncc

I do not know anything about those periodics.

**Comment by vrutkovs** [comment]
/hold

Invalid secrets are passed

**Comment by petr-muller** [comment]
Can we add one for 4.7->4.8 too so that we don't forget carrying this for the future?

**Comment by vrutkovs** [comment]
>Can we add one for 4.7->4.8 too so that we don't forget carrying this for the future?

Good idea, done

**Comment by vrutkovs** [comment]
Initial setup failed

/retest

**Comment by vrutkovs** [comment]
kube-apiserver failed to rollout in stableinstall

/retest

**Comment by petr-muller** [comment]
/approve 
Feel free to merge when ready

**Comment by vrutkovs** [comment]
/hold cancel
/retest

Ready for review, rehearsals fail on quota issues

**Comment by pierreprinetti** [comment]
/lgtm

As for the failing tests, we can also fix later if they don't turn green.

Thank you!

**Comment by vrutkovs** [comment]
/hold

metadata needs to be regenerated

**Comment by pierreprinetti** [comment]
Looks like this needs a `make update`

**Comment by vrutkovs** [comment]
/hold cancel

Done

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
