### PR TITLE
telco5g: Add Baremetal SNO jobs against cnf-features-repo

### PR DESCRIPTION
**Pull request by Sandeepyadav93**
[CNF-11094](https://issues.redhat.com//browse/CNF-11094)

### CODE REVIEW

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-master-e2e-telco5g-sno-cnftests

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.15-e2e-telco5g-sno-cnftests

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.14-e2e-telco5g-sno-cnftests

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-master-e2e-telco5g-sno-cnftests

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.15-e2e-telco5g-sno-cnftests

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.15-e2e-telco5g-sno-cnftests

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.15-e2e-telco5g-sno-cnftests

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.16-e2e-telco5g-sno-cnftests

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-master-e2e-telco5g-sno-cnftests

**Comment by Sandeepyadav93** [comment]
/assign @ffromani @yuvalk

Could you please take a look at this PR? It adds the capability to run SNO against cnf-features-deploy. This job will not trigger by default and is non-voting.

The job is randomly failing(we have the same failures in periodic runs). However, we would like to merge this and investigate the failures in parallel.

**Comment by yuvalk** [comment]
/approve
sorry, didnt see this earlier

**Pull request merged**
