### PR TITLE
Onboard openstack-k8s-operators/install_yamls repo

### PR DESCRIPTION
**Pull request by amolkahat**
Onboard openstack-k8s-operators/install_yamls repo in prow.

This patch also adds pre-commit job which is optional.

### CODE REVIEW

**Comment by viroel** [comment]
missing OWNERS file in other repos: 
- ci-operator/jobs/openstack-k8s-operators/install_yamls/
- core-services/prow/02_config/openstack-k8s-operators/install_yamls/

**Comment by amolkahat** [comment]
> missing OWNERS file in other folders:
> 
>     * ci-operator/jobs/openstack-k8s-operators/install_yamls/
> 
>     * core-services/prow/02_config/openstack-k8s-operators/install_yamls/

Thanks @viroel, Added OWNERS file in above mentioned dir.

**Comment by amolkahat** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-install_yamls-master-precommit-check

**Comment by amolkahat** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-install_yamls-master-precommit-check

**Comment by amolkahat** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-install_yamls-master-precommit-check

**Comment by amolkahat** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-install_yamls-master-precommit-check

**Comment by amolkahat** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-install_yamls-master-precommit-check

**Comment by amolkahat** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-install_yamls-master-precommit-check

**Comment by amolkahat** [comment]
| /pj-rehearse pull-ci-openstack-k8s-operators-install_yamls-master-precommit-check
-- | --

**Comment by amolkahat** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-install_yamls-master-precommit-check

**Comment by amolkahat** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-install_yamls-master-precommit-check

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-install_yamls-master-images pull-ci-openstack-k8s-operators-install_yamls-master-precommit-check

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-install_yamls-master-precommit-check

**Comment by raukadah** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-install_yamls-master-precommit-check

**Comment by bshewale** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-install_yamls-master-precommit-check

**Comment by viroel** [comment]
we need https://github.com/openstack-k8s-operators/install_yamls/pull/204 to have pre-commit passing

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-install_yamls-master-precommit-check

**Pull request merged**
