### PR TITLE
Configure for release-2.4 branch on kubevirt/hyperconverged-cluster-operator

### PR DESCRIPTION
**Pull request by tiraboschi**
Configure for release-2.4 branch on kubevirt/hyperconverged-cluster-operator

### CODE REVIEW

**Comment by orenc1** [comment]
Hello @droslean ,
In #10500, we added the following block in prow config, to allow running prow jobs on release-2.[4-9] branch on kubevirt/hyperconverged-cluster-operator repo:
```
    ci-operator/config/kubevirt/**/*release-2.[4-9].yaml:
      clusters:
        app.ci:
        - ci
      name: ci-operator-misc-configs
```

However, the sharded-config test does not recognize this entry.
` time="2020-08-03T11:34:38Z" level=error msg="Validation failed" error="ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-2.4.yaml.config_updater.maps: Invalid value: \"ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-2.4.yaml\": Config file does not belong to any auto-updating config." `

Adding an entry for `release-2.*` collides with `open-cluster-management/registration` project.

Could you please suggest how can we enable openshift-ci prow jobs in PRs against release-2.* branches in kubevirt project?

Thanks

**Comment by tiraboschi** [comment]
Finally handled with https://github.com/openshift/release/pull/10670 (correctly) renaming the release branch as release-1.1 on kubevirt/hyperconverged-cluster-operator

**Pull request closed without merging**
