### PR TITLE
[WIP]: Refactor HyperShift Prow-CI Jobs

### PR DESCRIPTION
**Pull request by krishvoor**
This PR refactors a HyperShift Prow-CI 4.13 Jobs

### CODE REVIEW

**Comment by svetsa-rh** [comment]
Per discussion in our call today, let's take time to analyze Hypershift test results for individual workloads and make sure they are all looking good, before we combine workloads into chains.
https://issues.redhat.com/browse/OCPQE-16525

/hold

**Comment by krishvoor** [comment]
> Per discussion in our call today, let's take time to analyze Hypershift test results for individual workloads and make sure they are all looking good, before we combine workloads into chains. https://issues.redhat.com/browse/OCPQE-16525
> 

Hi @svetsa-rh do we an update on this?

**Comment by krishvoor** [comment]
> > > Per discussion in our call today, let's take time to analyze Hypershift test results for individual workloads and make sure they are all looking good, before we combine workloads into chains. https://issues.redhat.com/browse/OCPQE-16525
> > 
> > 
> > Hi @svetsa-rh do we an update on this?
> 
> @krishvoor I am working on filling gaps for HCP https://issues.redhat.com/browse/PERFSCALE-2518 Can we do this as soon as that is complete, so we can combine all.
> 
> Also, naming has changed quite a bit now. Let's make sure to be consistent.

@svetsa-rh Kindly assign me the new PRs, so I am well aware of those changes and rework this one accordingly.
Thank you!

**Comment by krishvoor** [comment]
@svetsa-rh For HCP Large/Medium scale PR, we have this PR in place as well
https://github.com/openshift/release/pull/43004

**Comment by krishvoor** [comment]
Closing this in favor of https://issues.redhat.com/browse/PERFSCALE-2518

**Pull request closed without merging**
