### PR TITLE
MetalLB / MetalLB operator: build on rhel9

### PR DESCRIPTION
**Pull request by fedepaol**

### CODE REVIEW

**Review by cgoncalves — CHANGES_REQUESTED** [review]
Need to update also in files `openshift-metallb-release-4.16.yaml` and `openshift-metallb-operator-release-4.16.yaml`.

**Comment by fedepaol** [comment]
> Need to update also in files `openshift-metallb-release-4.16.yaml` and `openshift-metallb-operator-release-4.16.yaml`.

done (and thanks)

**Pull request merged**
