### PR TITLE
MON-3173: manually disable ci/prow/versions test on release branches …

### PR DESCRIPTION
**Pull request by machine424**
…from 4.10 to 4.15

### CODE REVIEW

**Comment by machine424** [comment]
Thanks to you both.

@jan--f  Yes, as I mentioned in the ticket, this is not ideal, but will buy us some time to think about a better/automated solution.

I'll add the step to the template, I hope we'll not get used to doing this :)

**Comment by machine424** [comment]
Some of this was reverted by a lovely bot https://github.com/openshift/release/pull/39366/files

I'll see

**Comment by jan--f** [comment]
hm its possible that the brancher bot ensures that the release branches are tested just like the master branch is tested. Maybe we should fix this is our `make versions` target?

**Comment by machine424** [comment]
Yep, I'm trying to apply solution #2 in here https://github.com/openshift/cluster-monitoring-operator/pull/1969

**Pull request merged**
