### PR TITLE
Remove obsolete Stolostron volsync-addon-controller jobs

### PR DESCRIPTION
**Pull request by skitt**
ACM 2.6 has reached EOL, pre-2.7 jobs are no longer needed.

### CODE REVIEW

**Comment by tesshuflower** [comment]
I think we may have to put this on hold for a bit - ACM 2.6 still has extended support for some customers at the moment.

**Comment by skitt** [comment]
> I think we may have to put this on hold for a bit - ACM 2.6 still has extended support for some customers at the moment.

Right, I mentioned that in https://redhat-internal.slack.com/archives/CTDEY6EEA/p1704372800169959 but a few PRs have been merged; I can revert them if necessary of course (at least, restore the 2.6 jobs).

**Comment by skitt** [comment]
@tesshuflower I’ve restored the 2.6 jobs in this PR.

/hold cancel

**Comment by tesshuflower** [comment]
Thank you @skitt !

/lgtm

**Review by sahare — APPROVED** [review]
lgtm

**Pull request merged**
