### PR TITLE
only run features unit tests if features dir changes

### PR DESCRIPTION
**Pull request by davidvossel**
The baremetal deploy repo's unit tests only apply to the features directory.

### CODE REVIEW

**Comment by davidvossel** [comment]
/cc @rlopez133 

This will prevent CI from triggering on your baremetal prep changes. If you want a new CI job for baremetal prep validation, that will need to be a new entry in the baremetal-deploy Openshift CI presubmit config.

**Comment by slintes** [comment]
`Not mergeable. Needs bugzilla/valid-bug label.`

really?

**Pull request merged**
