### PR TITLE
Add collaborators

### PR DESCRIPTION
**Pull request by ruromero**
Signed-off-by: Ruben Romero Montes <rromerom@redhat.com>

Mirror builds to quay.io
Grant access also to other owners @tchughesiv @bmozaffa

### CODE REVIEW

**Comment by smarterclayton** [comment]
/hold

This is not how we do mirroring.

**Comment by ruromero** [comment]
Add only collaborators

**Comment by ruromero** [comment]
@petr-muller can you remove the hold label?

**Comment by petr-muller** [comment]
I think anyone can

/hold cancel

**Pull request merged**
