### PR TITLE
Move machineconfig objects into its own folder

### PR DESCRIPTION
**Pull request by hongkailiu**
More objects are coming, e.g., https://github.com/openshift/release/pull/12775
Objects stays in a project related folder.

/cc @openshift/openshift-team-developer-productivity-test-platform

### CODE REVIEW

**Comment by alvaroaleman** [comment]
Didn't we discuss this and come to the conclusion that we want less and not more folders?

**Comment by hongkailiu** [comment]
> Didn't we discuss this and come to the conclusion that we want less and not more folders?

I do not know if we reached a conclusion, or that is an option in grooming.
Maybe we can handle the folder structure all together at the same time?

Personally, the subfolders telling me where it is about make sense, easy to locate the files without `grep` the content.
But I am OK if we switch to a new rule on folders.

**Comment by alvaroaleman** [comment]
> Personally, the subfolders telling me where it is about make sense, easy to locate the files without grep the content.
But I am OK if we switch to a new rule on folders.

I find them super confusing, because we have too many and many objects could be argued belong in multiple folders. I think just having one folder with all objects would be best. If you want further grouping, you could prefix the objects.

**Comment by hongkailiu** [comment]
/close

I will follow this new rule from now on.

**Pull request closed without merging**
