### PR TITLE
cert-rotation: tweak CSR approval

### PR DESCRIPTION
**Pull request by vrutkovs**
Approve CSRs until each node has 2 csrs, increase timeouts and amount of attempts

### CODE REVIEW

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-ha-cert-rotation-suspend-90d pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-sno-cert-rotation-suspend-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-ha-cert-rotation-suspend-90d pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-sno-cert-rotation-suspend-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-ha-cert-rotation-suspend-90d pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-sno-cert-rotation-suspend-90d pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-sno-cert-rotation-suspend-360d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-ha-cert-rotation-suspend-90d pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-sno-cert-rotation-suspend-90d pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-sno-cert-rotation-suspend-360d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-ha-cert-rotation-suspend-90d pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-sno-cert-rotation-suspend-90d pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-sno-cert-rotation-suspend-180d pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-ha-cert-rotation-suspend-90d pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-sno-cert-rotation-suspend-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-ha-cert-rotation-suspend-90d pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-sno-cert-rotation-suspend-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-ha-cert-rotation-suspend-90d pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-sno-cert-rotation-suspend-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-ha-cert-rotation-suspend-90d pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-sno-cert-rotation-suspend-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-ha-cert-rotation-suspend-90d pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-sno-cert-rotation-suspend-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-ha-cert-rotation-suspend-90d pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-sno-cert-rotation-suspend-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-ha-cert-rotation-suspend-90d pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-sno-cert-rotation-suspend-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-ha-cert-rotation-suspend-90d pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-sno-cert-rotation-suspend-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-ha-cert-rotation-suspend-90d pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-sno-cert-rotation-suspend-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-ha-cert-rotation-suspend-90d pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-sno-cert-rotation-suspend-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-ha-cert-rotation-suspend-90d pull-ci-openshift-cluster-kube-apiserver-operator-release-4.15-e2e-metal-ovn-sno-cert-rotation-suspend-90d

**Comment by vrutkovs** [comment]
/pj-rehearse ack

/cc @wangke19 
PTAL

**Comment by tkashem** [comment]
/lgtm

/hold
(feel free to cancel it when you think it's good to merge)

**Pull request merged**
