### PR TITLE
Prepare openshift-knative-v1.29.1 release.

### PR DESCRIPTION
**Pull request by Kaustubh-pande**
Signed-off-by: Kautsubh pande [kpande@redhat.com](mailto:kpande@redhat.com)

cc @matzew @dsimansk @mgencur

### CODE REVIEW

**Comment by Kaustubh-pande** [comment]
/pj-rehearse pull-ci-openshift-knative-serverless-operator-release-1.29-4.12-upgrade-tests-aws-ocp-412

**Comment by Kaustubh-pande** [comment]
/pj-rehearse pull-ci-openshift-knative-serverless-operator-release-1.29-4.12-upstream-e2e-mesh-aws-ocp-412

**Comment by pierDipi** [comment]
/pj-rehearse pull-ci-openshift-knative-serverless-operator-release-1.29-4.12-upstream-e2e-mesh-aws-ocp-412

**Comment by pierDipi** [comment]
mesh test was fixed in https://github.com/openshift-knative/serverless-operator/pull/2127 yesterday

**Comment by dsimansk** [comment]
@pierDipi ahh I'm not approver around here. Do you mind stamping it? Thanks!

**Pull request merged**
