### PR TITLE
OCPEDGE-996: Refactor ibu periodics and seed generation 

### PR DESCRIPTION
**Pull request by jeff-roche**
This PR does a few things:
- Remove 4.14 seed gen job (4.14 is not officially supported)
- Refactor the periodics into a more typical file structure (per ocp y-stream)
- Refactors seed gen such that having a presubmit specific and a periodic specific seed gen step is no longer needed. This is done utilizing the promoted LCA operator images from the main branch and release-4.15 branch. Pulling those in allows us to reference them with `pipeline:lca-operator`

### CODE REVIEW

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-kni-lifecycle-agent-main-nightly-4.16-seedgen-aws-ocp-4-16

**Review by javipolo — APPROVED** [review]

**Pull request merged**
