### PR TITLE
Adding azure-sop to prow.

### PR DESCRIPTION
**Pull request by kwoodson**
Adding azure-sop to allow for bot interactions.

### CODE REVIEW

**Comment by y-cote** [comment]
More of a learning opp. to see how to add a new repo to prow than a lgtm. Seems fine is there isn't any other files to hook the new repo into.

**Comment by kwoodson** [comment]
@y-cote, this was my best guess.  I'm not sure if we need anything else. Was hoping @mjudeikis would know.

**Comment by kwoodson** [comment]
@smarterclayton @petr-muller 

We'd like to add azure-sop to prow in order to get the ability to give commands and automate merging of PRs.  Does this PR look sufficient to achieve this?

**Comment by droslean** [comment]
@kwoodson I just realize that this repo doesn't exist.  Can you explain?

**Comment by kwoodson** [comment]
@droslean, it does and it is private. I only granted access to the openshift azure team.

**Comment by droslean** [comment]
Great. Just make sure that the bot has access in that repo.

**Pull request merged**
