### PR TITLE
Sync Serverless CI

### PR DESCRIPTION
**Pull request by serverless-qe**
Sync Serverless CI using openshift-knative/hack.

### CODE REVIEW

**Comment by creydr** [comment]
main jobs passed:
* eventing-kafka-broker-release-v1.12-414-test-reconciler-encryption-auth-aws-414
* eventing/release-v1.12/412-test-reconciler-aws-412
* eventing/release-v1.12/414-test-reconciler-aws-414
* periodic-ci-openshift-knative-eventing-kafka-broker-release-v1.12-414-test-reconciler-encryption-auth-aws-414-c

/pj-rehearse ack
/lgtm

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
