### PR TITLE
Update tag spec to 4.4 for all RHMI components

### PR DESCRIPTION
**Pull request by mikenairn**

### CODE REVIEW

**Comment by mikenairn** [comment]
@david-martin @pb82 Would one of you approve this please

**Comment by davidkirwan** [comment]
@david-martin do you want to keep me as an owner on this repo? (happy to stay, but I'm completely out of the loop).

**Comment by david-martin** [comment]
> @david-martin do you want to keep me as an owner on this repo? (happy to stay, but I'm completely out of the loop).

Thanks @davidkirwan 
I'll update the various OWNERS files to let you off the hook :)

**Comment by david-martin** [comment]
#10284

**Pull request merged**
