### PR TITLE
Pin NTO's PAO lanes to build03

### PR DESCRIPTION
**Pull request by yanirq**
Signed-off-by: Yanir Quinn <yquinn@redhat.com>

### CODE REVIEW

**Comment by ffromani** [comment]
> Signed-off-by: Yanir Quinn [yquinn@redhat.com](mailto:yquinn@redhat.com)

context: `build04`'s image registry was frequently returning 500 errors at the time of change. We don't have any preference for build hosts, so we just pin to a different one.

**Comment by ffromani** [comment]
/lgtm
/hold
/cc @jmencak 
not too fond of explicit pinning, but we need to stop the bleeding
let's wait for other reviewers

**Comment by jmencak** [comment]
Thank you for the PR.
/lgtm
/unhold

**Pull request merged**
