### PR TITLE
Move workflows to new packet cluster profiles

### PR DESCRIPTION
**Pull request by lranjbar**
Moving jobs that use the following workflows to their respective cluster profiles:
- baremetalds-assisted -> packet-assisted
- baremetalds-sno  -> packet-sno

### CODE REVIEW

**Comment by lranjbar** [comment]
This PR blocks: https://github.com/openshift/release/pull/21739

**Comment by lranjbar** [comment]
/assign @eliorerz @hexfusion @sinnykumari @stbenjam @wking

Lots of teams involved in this one. For those interested in the errors from the packet-setup steps, check out the channel `#forum-metal-alerts` on Slack.

**Comment by hexfusion** [comment]
LGTM

**Comment by lranjbar** [comment]
/hold

Lets table this while I work on ocm-2.4 release

**Comment by andfasano** [comment]
@lranjbar looks like there are some conflicts to be resolved. Can you please fix them, so that we could ping the other missing owners? Thanks

**Comment by lranjbar** [comment]
Looks like there are unwanted changes coming in after rebase.

**Comment by andfasano** [comment]
> Looks like there are unwanted changes coming in after rebase.

@lranjbar can you please re-check the rebase, I wasn't expecting updates on the `always_run` fields (at least for our repos).

**Comment by lranjbar** [comment]
Will be splitting this PR into multiple PRs for better chance of merging.

**Pull request closed without merging**
