### PR TITLE
Enable the following OSSM Pilot tests:

### PR DESCRIPTION
**Pull request by MaxBab**
Enable:
* TestCustomGateway/minimal
* TestCustomGateway/minimal-delay-create-gateway-svc
* TestProxyHeaders
* TestTcpProbe/rewrite-success
* TestGRPCProbe
* TestTunnelingOutboundTraffic
* TestIngress
* TestLabelChanges
* TestLocality
* TestMirroringExternalService
* TestMirroring/mirror-percent-absent
* TestMirroring/mirror-10
* TestMirroring/mirror-50

### CODE REVIEW

**Comment by MaxBab** [comment]
Hi @bmangoen @dgn 

Could you allow the testing for this patch, please?

Thanks.

**Comment by dgn** [comment]
Hey @MaxBab, this looks good- what needed to be changed to make them pass?

**Comment by bmangoen** [comment]
LGTM. Waiting for the `istio-integration-pilot` test result but `TestTraffic` seems to be flaky

**Comment by MaxBab** [comment]
> Hey @MaxBab, this looks good- what needed to be changed to make them pass?

Hi,

Nothing.
Just enable them.

They are actually working.
I'm testing and verifying all the tests.
The one that are working, I'm enabling.
On the failing, I'll work to fix them.

**Comment by MaxBab** [comment]
@bmangoen @dgn 

Hi guys,

I would appreciate an approval, please.

**Review by dgn — APPROVED** [review]

**Comment by MaxBab** [comment]
@bmangoen @dgn 

Hi guys,

Any idea what else needed to be merged?

**Pull request merged**
