### PR TITLE
Add e2e-aws-sdn-kubeproxy job

### PR DESCRIPTION
**Pull request by danwinship**
Adds a new job to sdn and CNO to run openshift-sdn with a standalone kube-proxy, so we can test standalone kube-proxy behavior.

/hold
not sure how close to passing this is going to be and we don't want to merge it yet if it's really broken

### CODE REVIEW

**Comment by danwinship** [comment]
OK, failing tests:

> [sig-instrumentation] Prometheus when installed on the cluster should start and expose a secured proxy and unsecured metrics 

Yup, we don't do the kube-rbac-proxy thing for standalone kube-proxy metrics

> [sig-network] Services should be rejected when no endpoints exist

Not sure what's up with that...

> [sig-instrumentation] Prometheus when installed on the cluster when using openshift-sdn should be able to get the sdn ovs flows

or that

**Comment by danwinship** [comment]
filed https://github.com/openshift/cluster-network-operator/pull/839 and https://github.com/openshift/sdn/pull/202

**Comment by juanluisvaladas** [comment]
/retest
Both PRs are merged, let's see if it passes now. The test definition looks fine.

**Comment by danwinship** [comment]
> `[sig-network] Services should be rejected when no endpoints exist`

seems to be failing reliably

> `[sig-instrumentation] Prometheus when installed on the cluster shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured`

failed in some:

> `"promQL query: ALERTS{alertname!~\"Watchdog|AlertmanagerReceiversNotConfigured|PrometheusRemoteWriteDesiredShards\",alertstate=\"firing\",severity!=\"info\"} >= 1 had reported incorrect results:\n[{\"metric\":{\"__name__\":\"ALERTS\",\"alertname\":\"TargetDown\",\"alertstate\":\"firing\",\"job\":\"kube-proxy\",\"namespace\":\"openshift-kube-proxy\",\"service\":\"openshift-kube-proxy\",\"severity\":\"warning\"},\"value\":[1603368118.071,\"1\"]}]"`

Other stuff looks like flakes

**Comment by danwinship** [comment]
I've forgotten what the current state of this is...
/retest

**Comment by danwinship** [comment]
Reliably failing:
`[sig-instrumentation] Prometheus when installed on the cluster shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured [Early] [Suite:openshift/conformance/parallel]`
(probably something wrong with the kube-rbac-proxy definition?)

Sporadically failing:
`[sig-network] Services should be rejected when no endpoints exist [Skipped:ibmcloud] [Suite:openshift/conformance/parallel] [Suite:k8s]`
(not sure why, but I can reproduce this...)

**Pull request closed without merging**
