### PR TITLE
Test using the same GO used to build the image

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Comment by derekhiggins** [comment]
Looking at some of the failures on some of the earlier revisions, I can see where the 4.11 jobs were fixed but do you know if this has been fixed in the current version?
> ./hack/generate.sh: line 12: cd: /go/src/github.com/openshift/cluster-baremetal-operator: No such file or directory

from [here](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/32406/rehearse-32406-pull-ci-openshift-cluster-baremetal-operator-release-4.10-generate-check/1571873585016868864#1:build-log.txt%3A12)

**Comment by elfosardo** [comment]
> Looking at some of the failures on some of the earlier revisions, I can see where the 4.11 jobs were fixed but do you know if this has been fixed in the current version?
> 
> > ./hack/generate.sh: line 12: cd: /go/src/github.com/openshift/cluster-baremetal-operator: No such file or directory
> 
> from [here](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/32406/rehearse-32406-pull-ci-openshift-cluster-baremetal-operator-release-4.10-generate-check/1571873585016868864#1:build-log.txt%3A12)

@derekhiggins thanks, I noticed this too, this was fixed in 4.12 but not older versions, we need https://github.com/openshift/cluster-baremetal-operator/pull/290 plus more backports

**Comment by elfosardo** [comment]
this should fix 4.10 https://github.com/openshift/cluster-baremetal-operator/pull/291

**Comment by elfosardo** [comment]
also backports for 4.9 and 4.8 for the same problem https://github.com/openshift/cluster-baremetal-operator/pull/292 https://github.com/openshift/cluster-baremetal-operator/pull/293

**Comment by elfosardo** [comment]
forgot still missing https://github.com/openshift/cluster-baremetal-operator/pull/292 and https://github.com/openshift/cluster-baremetal-operator/pull/293

**Pull request merged**
