### PR TITLE
Setup CI job for Tektoncd Pipeline release v0.7.0

### PR DESCRIPTION
**Pull request by nikhil-thomas**
/cc @chmouel @vdemeester @sthaha 
Signed-off-by: Nikhil Thomas <nikthoma@redhat.com>

### CODE REVIEW

**Comment by chmouel** [comment]
There is the quay mirroring to setup too

**Comment by nikhil-thomas** [comment]
> There is the quay mirroring to setup too

i was going to push it in a separate pr.
I can add it with this patch, if that will work too.

**Pull request merged**
