### PR TITLE
Add job/pull-ci-openshift-release-clusterimageset-validate

### PR DESCRIPTION
**Pull request by hongkailiu**
https://issues.redhat.com/browse/DPTP-3115

### CODE REVIEW

**Comment by hongkailiu** [comment]
/pj-rehearse pull-ci-openshift-release-clusterimageset-validate

**Comment by hongkailiu** [comment]
/pj-rehearse pull-ci-openshift-release-clusterimageset-validate

**Comment by hongkailiu** [comment]
/pj-rehearse pull-ci-openshift-release-clusterimageset-validate

**Comment by hongkailiu** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/35352/rehearse-35352-pull-ci-openshift-release-clusterimageset-validate/1613897420700127232

failed as expected.

**Comment by bbguimaraes** [comment]
/lgtm
/hold

Do we want to correct the existing definitions before activating the job, even if it is `always_run: false`?

**Comment by hongkailiu** [comment]
> Do we want to correct the existing definitions before activating the job, even if it is `always_run: false`?

The current ones are correct. The failing rehearsal is the result of a new file within this PR that was to show the job works and has been now removed.


Let me rehearse it again before merging.

/pj-rehearse pull-ci-openshift-release-clusterimageset-validate

**Comment by hongkailiu** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/35352/rehearse-35352-pull-ci-openshift-release-clusterimageset-validate/1616062824075759616
Still green.

/hold cancel

**Pull request merged**
