### PR TITLE
Remove the presubmit telco jobs by adding cron

### PR DESCRIPTION
**Pull request by jhou1**
This fixes #50528 

@liangxia @kuiwang02 @aleskandro Please review.

### CODE REVIEW

**Comment by liangxia** [comment]
@jhou1 https://github.com/openshift/release/pull/50528 adds two presubmit jobs, while this PR change one of them to periodic job. Is it expected ?

**Comment by jhou1** [comment]
@liangxia I should remove that 4.16 as well, hold on

**Comment by kuiwang02** [comment]
@jhou1 Thanks

**Comment by aleskandro** [comment]
Thanks @jhou1

**Pull request merged**
