### PR TITLE
ci-operator/*: caching cri-o CI

### PR DESCRIPTION
**Pull request by sohankunkerkar**

### CODE REVIEW

**Comment by sohankunkerkar** [comment]
/pj-rehearse pull-ci-sohankunkerkar-cri-o-ci-refactor-ci-rhel-e2e

**Comment by sohankunkerkar** [comment]
/pj-rehearse pull-ci-sohankunkerkar-cri-o-ci-refactor-ci-rhel-e2e

**Comment by sohankunkerkar** [comment]
/pj-rehearse pull-ci-sohankunkerkar-cri-o-ci-refactor-periodics-setup-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse pull-ci-sohankunkerkar-cri-o-ci-refactor-periodics-setup-fedora-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-sohankunkerkar-cri-o-ci-refactor-periodics-setup-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse pull-ci-sohankunkerkar-cri-o-ci-refactor-ci-cgroupv2-e2e-crun

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-sohankunkerkar-cri-o-ci-refactor-periodics-setup-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-sohankunkerkar-cri-o-ci-refactor-periodics-setup-fedora-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-sohankunkerkar-cri-o-ci-refactor-periodics-setup-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-sohankunkerkar-cri-o-ci-refactor-periodics-setup-fedora-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-sohankunkerkar-cri-o-ci-refactor-periodics-setup-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-sohankunkerkar-cri-o-ci-refactor-periodics-setup-fedora-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-sohankunkerkar-cri-o-ci-refactor-periodics-setup-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-sohankunkerkar-cri-o-ci-refactor-periodics-setup-fedora-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-sohankunkerkar-cri-o-ci-refactor-periodics-setup-fedora-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-sohankunkerkar-cri-o-ci-refactor-periodics-setup-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse pull-ci-sohankunkerkar-cri-o-ci-refactor-ci-fedora-integration

**Comment by sohankunkerkar** [comment]
/pj-rehearse pull-ci-sohankunkerkar-cri-o-ci-refactor-ci-fedora-integration

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-sohankunkerkar-cri-o-ci-refactor-periodics-setup-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-sohankunkerkar-cri-o-ci-refactor-periodics-setup-fedora-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse pull-ci-sohankunkerkar-cri-o-ci-refactor-ci-cgroupv2-e2e

**Comment by sohankunkerkar** [comment]
/pj-rehearse pull-ci-sohankunkerkar-cri-o-ci-refactor-ci-cgroupv2-integration

**Comment by sohankunkerkar** [comment]
/pj-rehearse pull-ci-sohankunkerkar-cri-o-ci-refactor-ci-cgroupv2-integration

**Comment by sohankunkerkar** [comment]
@jianlinliu  could you take a look at it?

**Comment by jianlinliu** [comment]
Looks good to me for creating new folders under gcp folder.

/lgtm

**Pull request merged**
