### PR TITLE
Adding bccutil build to the openshift-docs CI

### PR DESCRIPTION
**Pull request by aireilly**
~Adding a bccutil scratch build that will allow us to appoximately test changes to openshift-docs source.~

It is not acceptable or productive to run ancient software in production. The bccutil container is running on Fedora 29! It's too buggy and serves no purpose to run doc builds with bccutil.

### CODE REVIEW

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-preview-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-preview-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-preview-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-asciidoc pull-ci-openshift-openshift-docs-prow-test-2-validate-portal pull-ci-openshift-openshift-docs-prow-test-2-openshift-docs-bccutil-build pull-ci-openshift-openshift-docs-prow-test-2-openshift-docs-portal-preview

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-asciidoc pull-ci-openshift-openshift-docs-prow-test-2-validate-portal pull-ci-openshift-openshift-docs-prow-test-2-openshift-docs-bccutil-build pull-ci-openshift-openshift-docs-prow-test-2-openshift-docs-portal-preview

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-asciidoc pull-ci-openshift-openshift-docs-prow-test-2-validate-portal pull-ci-openshift-openshift-docs-prow-test-2-openshift-docs-bccutil-build pull-ci-openshift-openshift-docs-prow-test-2-openshift-docs-portal-preview

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-asciidoc pull-ci-openshift-openshift-docs-prow-test-2-validate-portal pull-ci-openshift-openshift-docs-prow-test-2-openshift-docs-bccutil-build pull-ci-openshift-openshift-docs-prow-test-2-openshift-docs-portal-preview

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-asciidoc pull-ci-openshift-openshift-docs-prow-test-2-validate-portal pull-ci-openshift-openshift-docs-prow-test-2-openshift-docs-bccutil-build pull-ci-openshift-openshift-docs-prow-test-2-openshift-docs-portal-preview

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-asciidoc pull-ci-openshift-openshift-docs-prow-test-2-validate-portal pull-ci-openshift-openshift-docs-prow-test-2-openshift-docs-bccutil-build pull-ci-openshift-openshift-docs-prow-test-2-openshift-docs-portal-preview

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by deepsm007** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Comment by aireilly** [comment]
It is not acceptable or productive to run ancient software in production. The bccutil container is running on Fedora 29! It's too buggy and serves no purpose to run doc builds with bccutil.

**Pull request closed without merging**
