### PR TITLE
ARMOCP-511: Enable builds on arm01 for the hypershift org

### PR DESCRIPTION
**Pull request by aleskandro**
This PR enables arm64 builds for the hypershift prow org so that QE can use the produced images in the tests pipelines.
The images are mirrored in quay in the same repository as for amd64. The amd64 images are kept without any suffix, while the arm64 images will have the `-arm64` suffix. In future, when the clusters are upgraded to 4.13 and a path for Prow multi-arch builds is available, we will need to change this for producing ManifestList images.

Note: Avoiding <4.13 builds seems not possible yet (cc @droslean).

This is an initial work related to [ARMOCP-511](https://issues.redhat.com//browse/ARMOCP-511).

### CODE REVIEW

**Comment by deepsm007** [comment]
@droslean any thoughts if we want to only create postsubmits for release >=4.13 ?

**Comment by aleskandro** [comment]
cc @LiangquanLi930

**Comment by aleskandro** [comment]
Hello @enxebre  @sjenning, can you PTAL?

**Comment by bryan-cox** [comment]
/retitle ARMOCP-511: Enable builds on arm01 for the hypershift org

**Pull request merged**
