### PR TITLE
draft of openshit-tests-private container image

### PR DESCRIPTION
**Pull request by kuiwang02**
/cc @jianzhangbjz 

it is wip. and now I want to check the image health.

### CODE REVIEW

**Comment by jcpowermac** [comment]
fyi...

```
# jcallen @ magnesium in ~ [12:30:32]
$ oc get is stable -o yaml  | grep upi
```

```
134m        Normal    Pulling                           pod/extended-vsphere-ipi-parallel-ipi-conf-vsphere-check          Pulling image "image-registry.openshift-image-registry.svc:5000/ci-op-0ggqsrd8/stable:upi-installer"
4m32s       Normal    BackOff                           pod/extended-vsphere-ipi-parallel-ipi-conf-vsphere-check          Back-off pulling image "image-registry.openshift-image-registry.svc:5000/ci-op-0ggqsrd8/stable:upi-installer"
4m5s        Normal    BackOff                           pod/extended-vsphere-ipi-parallel-ipi-deprovision-vsphere-diags   Back-off pulling image "image-registry.openshift-image-registry.svc:5000/ci-op-0ggqsrd8/stable:upi-installer"
```

**Comment by kuiwang02** [comment]
> 

Thank you.

**Comment by kuiwang02** [comment]
> fyi...
> 
> ```
> # jcallen @ magnesium in ~ [12:30:32]
> $ oc get is stable -o yaml  | grep upi
> ```
> 
> ```
> 134m        Normal    Pulling                           pod/extended-vsphere-ipi-parallel-ipi-conf-vsphere-check          Pulling image "image-registry.openshift-image-registry.svc:5000/ci-op-0ggqsrd8/stable:upi-installer"
> 4m32s       Normal    BackOff                           pod/extended-vsphere-ipi-parallel-ipi-conf-vsphere-check          Back-off pulling image "image-registry.openshift-image-registry.svc:5000/ci-op-0ggqsrd8/stable:upi-installer"
> 4m5s        Normal    BackOff                           pod/extended-vsphere-ipi-parallel-ipi-deprovision-vsphere-diags   Back-off pulling image "image-registry.openshift-image-registry.svc:5000/ci-op-0ggqsrd8/stable:upi-installer"
> ```

Thank you. @jcpowermac

**Pull request closed without merging**
