### PR TITLE
Run optional kubevirt IPI tests for openshift-installer

### PR DESCRIPTION
**Pull request by bardielle**

### CODE REVIEW

**Comment by bardielle** [comment]
@vrutkovs I changed the e2e-kubevirt workflow to run on openshift-installer-master.yaml instead of  openshift-installer-fcos.yaml
Can you re-review it please?

**Review by vrutkovs — APPROVED** [review]
/lgtm

**Comment by staebler** [comment]
> @vrutkovs I changed the e2e-kubevirt workflow to run on openshift-installer-master.yaml instead of openshift-installer-fcos.yaml
> Can you re-review it please?

Please change the PR title and commit message since the changes are no longer for the OKD installer.

**Comment by bardielle** [comment]
@staebler thanks, I changed the commit msg and the PR title

**Review by staebler — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
