### PR TITLE
Add ability to run cucushift tests in serial

### PR DESCRIPTION
**Pull request by liangxia**
To support test in https://github.com/openshift/release/pull/51675

### CODE REVIEW

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn-fdp-qe

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn-fdp-qe

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn-fdp-qe

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn-fdp-qe

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn-fdp-qe

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-azure-ipi-basecap-vset-arm-f2

**Comment by anuragthehatter** [comment]
Looks good to me. Thanks
/assign @pruan-rht @dis016 @JianLi-RH

**Pull request merged**
