### PR TITLE
SPLAT-728: add AWS Local Zones lease pool

### PR DESCRIPTION
**Pull request by mtulio**
https://issues.redhat.com/browse/SPLAT-728

ci-tools PR creating the profile: https://github.com/openshift/ci-tools/pull/3336

### CODE REVIEW

**Comment by mtulio** [comment]
Richard, ptal?
/assign @rvanderp3

**Comment by rvanderp3** [comment]
Hi @mtulio is there a corresponding PR in ci-tools yet?

**Comment by mtulio** [comment]
> Hi @mtulio is there a corresponding PR in ci-tools yet?

There is https://github.com/openshift/ci-tools/pull/3336 , it was just merged.

**Comment by mtulio** [comment]
Hey @rvanderp3 I think the `/lgtm` was added before converting from Draft. Would you mind to tag it again?

**Review by droslean — APPROVED** [review]

**Pull request merged**
