### PR TITLE
Add image build job for Node Problem Detector

### PR DESCRIPTION
**Pull request by joelsmith**

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@smarterclayton did we change LGTM to not approve anymore?

**Comment by smarterclayton** [comment]
Upstream did but I thought it was an optional flag.

I think it was dumb personally

On Nov 2, 2018, at 4:20 PM, Steve Kuznetsov <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> did we change LGTM to
not approve anymore?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/release/pull/2058#issuecomment-435486813>,
or mute
the thread

**Pull request merged**
