### PR TITLE
implement Jira in the OPP OCP 4.15 job

### PR DESCRIPTION
**Pull request by vboulos**
- Implement Jira in the OPP OCP 4.15 job

### CODE REVIEW

**Comment by vboulos** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.15-interop-openshift-plus-interop-aws

**Comment by vboulos** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.15-interop-openshift-plus-interop-aws

**Review by gparvin — APPROVED** [review]
Thanks

**Pull request merged**
