### PR TITLE
[HyperShift]: enable HyperShift agent-connected-metal3 conformance test

### PR DESCRIPTION
**Pull request by LiangquanLi930**

### CODE REVIEW

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-agent-connected-ipv4-metal3-conformance

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-agent-connected-dualstack-metal3-conformance

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-agent-connected-dualstack-metal3-conformance

**Comment by jparrill** [comment]
discussion in this thread: https://redhat-internal.slack.com/archives/G01QS0P2F6W/p1708081692852879

**Pull request merged**
