### PR TITLE
remove files for azure-misc

### PR DESCRIPTION
**Pull request by mjudeikis**
Removed azure-misc from testing as its private now. WIll need to rollaback when fix privacy issue

@kwoodson @Makdaam

### CODE REVIEW

**Comment by kwoodson** [comment]
@mjudeikis its either this or come up with authentication to see private repos. Should we investigate how much effort it is to upload/maintain a secret for this repository?

**Comment by mjudeikis** [comment]
@kwoodson I think we dont have anything now to build from this repo :/ 
raised follow up the issue for this https://github.com/openshift/azure-misc/issues/134

**Comment by jim-minter** [comment]
@mjudeikis any chance you could see if a secret can be set up rather than taking this approach?

**Comment by mjudeikis** [comment]
@jim-minter ci-operator does not support private repositories. This was why we "went open" first time :/

**Comment by Makdaam** [comment]
/lgtm
We don't build any images anymore in this repo.
Since the builds block other PRs I'm for removing this for now.

**Pull request merged**
