### PR TITLE
o/cvo: bump golangci-lint version

### PR DESCRIPTION
**Pull request by petr-muller**

### CODE REVIEW

**Comment by petr-muller** [comment]
/pj-rehearse pull-ci-openshift-cluster-version-operator-master-lint pull-ci-openshift-cluster-version-operator-master-unit

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Comment by petr-muller** [comment]
/pj-rehearse pull-ci-openshift-cluster-version-operator-master-lint pull-ci-openshift-cluster-version-operator-master-unit

**Pull request merged**
