### PR TITLE
Fix Azure CCM OVN Hybrid Install

### PR DESCRIPTION
**Pull request by aravindhp**

### CODE REVIEW

**Comment by aravindhp** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-azure-e2e-ccm-install

**Comment by aravindhp** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-azure-e2e-ccm-install

**Comment by aravindhp** [comment]
/retitle Fix Azure CCM OVN Hybrid Install

**Comment by elmiko** [comment]
just curious, are we enabling the tech preview feature gate to install the CCM or something else?

**Comment by JoelSpeed** [comment]
/approve

Is there an equivalent flow that doesn't have the CCM part to it? Could eliminate the workflow completely if that can be used and the job level can be set to techpreview

**Comment by sebsoto** [comment]
> Is there an equivalent flow that doesn't have the CCM part to it? Could eliminate the workflow completely if that can be used and the job level can be set to techpreview

@JoelSpeed 
Just created https://github.com/openshift/release/pull/38968 to explore that

**Pull request merged**
