### PR TITLE
OCPQE-23207 ROSA HCP should use extended health check

### PR DESCRIPTION
**Pull request by radtriste**

### CODE REVIEW

**Comment by radtriste** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-stable-aws-rosa-hcp-security-group-f14 periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-stable-aws-rosa-hcp-security-group-private-f14

**Comment by radtriste** [comment]
cc @xueli181114 for approval

**Comment by radtriste** [comment]
@kuiwang02 @bandrade @jhou1 Could you approve that one ?

**Comment by kuiwang02** [comment]
@radtriste it is not me to approve regression prow job.

add @liangxia help it.

**Pull request merged**
