### PR TITLE
Prow job to test COO on arm64 cluster

### PR DESCRIPTION
**Pull request by lihongyan1**
https://issues.redhat.com/browse/COO-172

### CODE REVIEW

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.15-coo-arm-stage

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.15-coo-arm-stage

**Comment by lihongyan1** [comment]
periodic-ci-rhobs-observability-operator-main-ocp-4.15-coo-arm-stage

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.15-coo-arm-stage

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.13-coo-qeindex

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.14-coo-qeindex

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.13-coo-stage

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.14-coo-stage

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.16-coo-arm-qeindex

**Comment by lihongyan1** [comment]
periodic-ci-rhobs-observability-operator-main-ocp-4.16-coo-arm-stage

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.16-coo-arm-stage

**Comment by lihongyan1** [comment]
/pj-rehearse  periodic-ci-rhobs-observability-operator-main-ocp-4.13-coo-qeindex

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.14-coo-qeindex

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.13-coo-qeindex

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.14-coo-qeindex

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.16-coo-arm-qeindex

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.16-coo-arm-qeindex

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.16-coo-arm-qeindex

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.16-coo-arm-stage

**Comment by lihongyan1** [comment]
/pj-rehearse  periodic-ci-rhobs-observability-operator-main-ocp-4.13-coo-stage

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.13-coo-qeindex

**Comment by lihongyan1** [comment]
/pj-rehearse  periodic-ci-rhobs-observability-operator-main-ocp-4.14-coo-qeindex

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.14-coo-stage

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.17-coo-stage

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.17-coo-qeindex

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.17-coo-qeindex

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.17-coo-stage

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.17-coo-qeindex

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.16-coo-arm-qeindex

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.16-coo-arm-stage

**Comment by lihongyan1** [comment]
/pj-rehearse  periodic-ci-rhobs-observability-operator-main-ocp-4.14-coo-qeindex

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.14-coo-stage

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.13-coo-qeindex

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.13-coo-stage

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.16-coo-arm-stage

**Comment by lihongyan1** [comment]
/pj-rehearse ack
The failure of job ci/rehearse/periodic-ci-rhobs-observability-operator-main-ocp-4.17-coo-qeindex is expected for bug [COO-225](https://issues.redhat.com/browse/COO-225) observability-operator pod failed to to list *v1alpha1.ConsolePlugin on OCP4.17

**Comment by jan--f** [comment]
Thanks, this
/lgtm

**Pull request merged**
