### PR TITLE
Enable systemd journal logging to serial consoles

### PR DESCRIPTION
**Pull request by stbenjam**
This adds a machine config to forward systemd logs to the console for masters and workers. This will help debug early boot problems.

### CODE REVIEW

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-fips

**Comment by stbenjam** [comment]
/hold

Not sure how far bar ignition 3.x goes, might need to be smarter about when the manifest gets applied since this affects all jobs.

**Comment by stbenjam** [comment]
/hold cancel

Going to just run it on 4.14 for now to try to catch the bootstrapping problem

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-fips

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-fips

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-fips

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-fips

**Comment by travier** [comment]
https://github.com/coreos/fedora-coreos-config/blob/5134c04ddf542701c2434e136a4ff16cfc57cd47/platforms.yaml

**Comment by stbenjam** [comment]
Colin is the one who suggested this approach when we were debugging some early boot problems in another bug 🤷🏻

**Comment by stbenjam** [comment]
@travier https://github.com/coreos/fedora-coreos-config/pull/2399

**Pull request merged**
