### PR TITLE
Run cross build on specific changes

### PR DESCRIPTION
**Pull request by 0xmichalis**
@smarterclayton

### CODE REVIEW

**Comment by smarterclayton** [comment]
Filename for mac is `_darwin`.  Otherwise looks fine.

**Comment by stevekuznetsov** [comment]
Nice stuff. @bparees if you'd like we can add similar regex to trigger your suites of extended jobs

**Comment by bparees** [comment]
@stevekuznetsov we don't really have any platform specific stuff that i can think of in those suites.

**Comment by stevekuznetsov** [comment]
@bparees no, I meant if you see that the template service broker files changed, run the templates suite or whatever

**Comment by bparees** [comment]
@stevekuznetsov ah, yes that would be interesting.

**Pull request merged**
