### PR TITLE
[Prow CI workflow Enablement] Use MCE create HostedCluster on BM + KubeVirt platform

### PR DESCRIPTION
**Pull request by LiangquanLi930**
hypershift: enbale MCE-KubeVirt CI on BM

### CODE REVIEW

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.13-periodics-e2e-kubevirt-mce-baremetalds-conformance

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.13-periodics-e2e-kubevirt-mce-baremetalds-conformance

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.13-periodics-e2e-kubevirt-mce-baremetalds-conformance

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.13-periodics-e2e-kubevirt-mce-baremetalds-conformance

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.13-periodics-e2e-kubevirt-mce-baremetalds-conformance

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.13-periodics-e2e-kubevirt-mce-baremetalds-conformance

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.13-periodics-e2e-kubevirt-mce-baremetalds-conformance

**Review by davidvossel — COMMENTED** [review]
it looks like all the setup steps and conformance test steps passed in the rehearse job, but the tear down steps failed

```
+ curl -k --output /tmp/hypershift.tar.gz https://hypershift-cli-download-multicluster-engine.apps.ostest.test.metalkube.org/linux/amd64/hypershift.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: hypershift-cli-download-multicluster-engine.apps.ostest.test.metalkube.org; Unknown error
```

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.13-periodics-e2e-kubevirt-mce-baremetalds-conformance

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.13-periodics-e2e-kubevirt-mce-baremetalds-conformance

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-mce-baremetalds-conformance

**Review by davidvossel — COMMENTED** [review]
/approve
/lgtm

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.13-periodics-e2e-kubevirt-mce-baremetalds-conformance

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-mce-baremetalds-conformance

**Comment by LiangquanLi930** [comment]
https://issues.redhat.com/browse/OCPQE-15526

**Pull request merged**
