### PR TITLE
removing unneeded gather from assisted nutanix

### PR DESCRIPTION
**Pull request by eifrach**

### CODE REVIEW

**Comment by eifrach** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-nutanix-assisted

**Comment by eliorerz** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-nutanix-assisted-4-15-periodic

**Comment by eifrach** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-nutanix-assisted-4-15-periodic

**Review by danmanor — APPROVED** [review]

**Pull request merged**
