### PR TITLE
Adding workflow-config in chat-bot for various providers

### PR DESCRIPTION
**Pull request by miyadav**
For debugging prow failures adding one more workflow-config .
@sunzhaohua2 @jhou1 @huali9 @liangxia @yunjiang29 , PTAL if not repeated and it is good to add to help debug with exact cluster config .

### CODE REVIEW

**Comment by liangxia** [comment]
The change itself looks good.

Since the change also need approval from dptp. And to avoid bothering dptp too much, we should add this kind of changes in batch (rather than one by one).

**Comment by miyadav** [comment]
/hold 
Will make bulk changes for merging later.

**Comment by miyadav** [comment]
> The change itself looks good.
> 
> Since the change also need approval from dptp. And to avoid bothering dptp too much, we should add this kind of changes in batch (rather than one by one).

@liangxia PTAL once you are back and let me know if we can add more or this is ok to get merged for now .
The added worflow list contains profiles whose jenkins jobs are removed as per our [CI-Unifying-doc](https://docs.google.com/spreadsheets/d/1okJGAWsIj6RV91ChgsWQNwXzmHjvd-MkPntHr-UNNI8/edit?usp=sharing)
cc @sunzhaohua2 @jhou1

**Review by bradmwilliams — APPROVED** [review]

**Pull request merged**
