### PR TITLE
Increasing port ranges

### PR DESCRIPTION
**Pull request by jtaleric**
Bumping the port ranges

### CODE REVIEW

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-nightly-x86-data-path-9nodes

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-nightly-x86-data-path-9nodes

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-nightly-x86-data-path-9nodes

**Review by mukrishn — APPROVED** [review]
LGTM

**Pull request merged**
