### PR TITLE
debug 415_monitoring

### PR DESCRIPTION
**Pull request by Tai-RedHat**

### CODE REVIEW

**Comment by Tai-RedHat** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-vsphere-agent-dualstack-sno-f14

**Comment by Tai-RedHat** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-vsphere-agent-dualstack-sno-f14

**Comment by Tai-RedHat** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-vsphere-agent-dualstack-sno-f14

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-vsphere-agent-dualstack-sno-f14

**Pull request closed without merging**
