### PR TITLE
OPRUN-3542: Use openshift/ folder Makefile for running OLM v1 tests

### PR DESCRIPTION
**Pull request by dtfranz**
/hold until our downstream repo PRs have merged

### CODE REVIEW

**Comment by tmshort** [comment]
Use OPRUN-3542 for this. You will need to do `make config` locally.

**Comment by dtfranz** [comment]
> Use [OPRUN-3542](https://issues.redhat.com//browse/OPRUN-3542) for this. You will need to do `make config` locally, and add the changes to your PR.

Thanks for the reminder, been a long time since I worked in this space. BTW the command was `make jobs`

**Comment by tmshort** [comment]
Can you get rid of those things we identified as being covered by `make verify`?
i.e.
* make vet
* make fmt 

??

**Comment by tmshort** [comment]
/pj-rehearse pull-ci-openshift-operator-framework-operator-controller-main-verify

**Comment by dtfranz** [comment]
Looks like the docs generation part of `verify` is failing

**Comment by tmshort** [comment]
Check the downstream verify status? Do we need to do any downstream commits re: docs?

**Comment by tmshort** [comment]
I noticed that too

**Comment by dtfranz** [comment]
/hold
for:
https://github.com/openshift/operator-framework-operator-controller/pull/155
https://github.com/openshift/operator-framework-catalogd/pull/73

**Pull request merged**
