### PR TITLE
Add pre and post submit jobs for eventing-kafka-broker 1.3

### PR DESCRIPTION
**Pull request by pierDipi**
Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

### CODE REVIEW

**Comment by pierDipi** [comment]
/hold

let's see how it goes.

**Comment by pierDipi** [comment]
blocked by https://github.com/openshift-knative/eventing-kafka-broker/pull/177

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
