### PR TITLE
Added new scenarios for chains HA testing

### PR DESCRIPTION
**Pull request by siddardh-ra**
Initialized new var `DEPLOYMENT_CHAINS_CONTROLLER_HA_REPLICAS` and added new scenarios for chains HA testing

### CODE REVIEW

**Comment by siddardh-ra** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-5000-100-signing-test

**Comment by siddardh-ra** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-5000-100-signing-test-ha2

**Comment by siddardh-ra** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-5000-100-signing-test

**Comment by siddardh-ra** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test

**Comment by siddardh-ra** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test  pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha2

**Comment by siddardh-ra** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha2

**Comment by siddardh-ra** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha2

**Comment by siddardh-ra** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha4 pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha6

**Comment by siddardh-ra** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha10 pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha6

**Comment by siddardh-ra** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha10

**Comment by siddardh-ra** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha10 pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha6

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha10

**Comment by siddardh-ra** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha10

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha10

**Comment by jhutar** [comment]
OK, let's see now. With https://github.com/openshift-pipelines/performance/commit/43792b97b901f24ea3e082ee252f0c88d7741ba8, https://github.com/openshift-pipelines/performance/commit/855ea8e20f64a6924147866a88c450f61e27f33d and https://github.com/openshift-pipelines/performance/commit/6e03a5568d7127a2a2f634dee8f31eac2471742e, I hope it will work now.

**Comment by siddardh-ra** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha10

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha10

**Comment by jhutar** [comment]
Oooh, the issue is on totally different place. Trying now with https://github.com/openshift-pipelines/performance/commit/add6b0e8f8d162947af75eec07b1cd150ca9335a

**Comment by siddardh-ra** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha10  pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha6

**Comment by siddardh-ra** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha10 pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test

**Comment by siddardh-ra** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha10 pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test

**Comment by siddardh-ra** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha10 pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test

**Comment by siddardh-ra** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha10 pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test

**Comment by siddardh-ra** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha10 pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test

**Comment by siddardh-ra** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha10 pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test

**Comment by siddardh-ra** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha10 pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha4	pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha6

**Comment by siddardh-ra** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha6

**Comment by siddardh-ra** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test-ha4

**Comment by siddardh-ra** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test

**Comment by siddardh-ra** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test

**Comment by siddardh-ra** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-14-5000-100-signing-test

**Pull request closed without merging**
