### PR TITLE
Adding upgrade wait num

### PR DESCRIPTION
**Pull request by paigerube14**
Wait time variable was not getting properly exported resulting in 2 different wait times during the upgrade 

https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.17-nightly-x86-loaded-upgrade-from-4.16-loaded-upgrade-416to417-252nodes/1866332300459905024

Set in release upgrade script 
```
+ echo TARGET_RELEASES is 4.17.0-0.nightly-2024-12-06-012705
TARGET_RELEASES is 4.17.0-0.nightly-2024-12-06-012705
+ UPGRADE_WAIT_NUM=450
```

Set in sub upgrade script 
[export UPGRADE_WAIT_NUM=${UPGRADE_WAIT_NUM:-300}](https://github.com/openshift-qe/ocp-qe-perfscale-ci/blob/93f5e57ff150fa017c88e7d8d8a7832746a69968/upgrade_scripts/upgrade.sh#L159)
`Specify UPGRADE_WAIT_NUM is 300`

### CODE REVIEW

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.17-nightly-x86-loaded-upgrade-from-4.16-loaded-upgrade-416to417-24nodes

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.17-nightly-x86-loaded-upgrade-from-4.16-loaded-upgrade-416to417-24nodes

**Comment by qiliRedHat** [comment]
@paigerube14 good catch!

**Comment by paigerube14** [comment]
> @paigerube14 good catch! Is there any job you have seen that needs to extend the UPGRADE_WAIT_NUM?

Yes, the 252 loaded upgrade. I had put a failure job in the original description

**Pull request merged**
