### PR TITLE
NO-ISSUE: test cnv and odf jobs on OCP 4.12

### PR DESCRIPTION
**Pull request by adriengentil**

### CODE REVIEW

**Review by osherdp — APPROVED** [review]

**Comment by adriengentil** [comment]
ci/rehearse/openshift/assisted-service/cloud_hotfix_releases/e2e-metal-assisted-odf failed on a flake
/pj-rehearse ack

**Comment by adriengentil** [comment]
/override ci/rehearse/openshift/assisted-service/cloud_hotfix_releases/e2e-metal-assisted-odf

**Pull request merged**
