### PR TITLE
Update periodics of NVIDIA GPU operator

### PR DESCRIPTION
**Pull request by empovit**
* Spread out CI jobs to reduce load on AWS account
* Remove some 4.15 periodics until the operator is available in the catalog

### CODE REVIEW

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.12-nvidia-gpu-operator-e2e-23-9-x

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.12-nvidia-gpu-operator-e2e-23-9-x

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.12-nvidia-gpu-operator-e2e-23-9-x

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.12-nvidia-gpu-operator-e2e-23-9-x

**Review by wabouhamad — COMMENTED** [review]
/lgtm

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.12-nvidia-gpu-operator-e2e-23-9-x

**Pull request merged**
