### PR TITLE
Bump coreos-assembler to Fedora 38

### PR DESCRIPTION
**Pull request by jlebon**
Matches https://github.com/coreos/coreos-assembler/pull/3451.

### CODE REVIEW

**Comment by jlebon** [comment]
/hold
Until we've looked into https://github.com/coreos/coreos-assembler/pull/3451#issuecomment-1533401732.

**Comment by jlebon** [comment]
/hold cancel

I think this is ready to get in now.

**Comment by dustymabe** [comment]
ok I see we need this in order to make this change in COSA itself: https://github.com/coreos/coreos-assembler/pull/3451#issuecomment-1535388040

/lgtm

**Comment by jlebon** [comment]
/pj-rehearse ack

We'll test this in https://github.com/coreos/coreos-assembler/pull/3451.

**Pull request merged**
