### PR TITLE
ocm-terraform-provider e2e with openshift-tests/conformance

### PR DESCRIPTION
**Pull request by AsherShoshan**

### CODE REVIEW

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Review by sagidayan — CHANGES_REQUESTED** [review]
I think we should add a check to validate `$ART_NAME` (in all scripts). Someone might be missing it, and it won't be clear on why things are not working as expected.

This variable is super important in our case, without it the TF state is lost/invalid.

I would error out if the variable is empty or unset with an informative message.

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-periodic2

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-e2e-periodic2

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-e2e-periodic2

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-e2e-periodic2

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-e2e-periodic2

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-e2e-periodic2

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-e2e-periodic2

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-e2e-periodic2

**Comment by bardielle** [comment]
@AsherShoshan please squash the commits
@osherdp Please review it

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-e2e-periodic2

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-e2e-periodic2

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-e2e-periodic2

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-e2e-periodic2

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-e2e-periodic2

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-e2e-periodic2

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-e2e-periodic2

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-e2e-periodic2

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-e2e-periodic2

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-e2e-periodic2

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-e2e-periodic2

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-e2e-periodic2

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-e2e-periodic2

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-e2e-periodic2

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-e2e-periodic2

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-e2e-periodic2

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-rehearse-debug

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-e2e-periodic2

**Pull request closed without merging**
