### PR TITLE
modelmesh runtime adapter to openshift ci

### PR DESCRIPTION
**Pull request by Jooho**
This is the first openshift ci  for modelmesh-runtime-adapter repository

### CODE REVIEW

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-main-images

**Comment by Jooho** [comment]
/pj-rehearse ci/rehearse/opendatahub-io/modelmesh-runtime-adapter/develop/modelmesh-runtime-adapter-pr-image-mirror

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-images

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-images

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-images

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-images

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-images

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-images

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-fvt

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-fvt

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-fvt

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-test

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-test

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-test

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-test

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-test

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-test

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-test

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-test

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-test

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-test

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-test

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-test  pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-fvt

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-fvt

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-fvt

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-fvt

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-fvt

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-fvt

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-test  pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-fvt

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-fvt  pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-test

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-fvt pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-test

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-fvt pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-test

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-fvt pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-test

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-fvt

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-fvt

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-fvt

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-fvt

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-modelmesh-runtime-adapter-fvt

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-fvt

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-fvt

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-develop-fvt

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-main-fvt

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-runtime-adapter-main-fvt

**Comment by Jooho** [comment]
@droslean @bear-redhat Could you please review this?

**Review by Xaenalt — APPROVED** [review]

**Pull request merged**
