### PR TITLE
SPLAT-991: create pre-submit jobs for vSphere static IP

### PR DESCRIPTION
**Pull request by rvanderp3**
creating a an optional pre-submit job in support of https://issues.redhat.com/browse/SPLAT-827

### CODE REVIEW

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.14-e2e-vsphere-static-ovn

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.14-e2e-vsphere-static-ovn

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.14-e2e-vsphere-static-ovn

**Comment by rvanderp3** [comment]
The static IP configured install-config.yaml is making it to the install step.  I'd like to go ahead and see if we can get this workflow enabled and we can update it as the feature development progresses.  At this point, we can use it to perform presubmit testing on the bootstrap/control plane nodes.  @vr4manta is working on a controller to assign IP addresses to the compute nodes.

**Comment by jcpowermac** [comment]
/lgtm
/approve
/pj-rehearse ack

remove when you are ready
/hold

**Pull request merged**
