### PR TITLE
SPLAT-41: release: Add azure-e2e-upi periodic test runs

### PR DESCRIPTION
**Pull request by LorbusChris**

### CODE REVIEW

**Comment by LorbusChris** [comment]
It looks like the e2e only ran properly on 4.10.

@staebler @rna-afk does the conversion from templates to steps for Azure UPI e2e from https://github.com/openshift/release/pull/22320 only apply to master/4.10?

**Comment by staebler** [comment]
> It looks like the e2e only ran properly on 4.10.
> 
> @staebler @rna-afk does the conversion from templates to steps for Azure UPI e2e from #22320 only apply to master/4.10?

No, it was intended to be for all versions. It seems like the upi image that we are using does not have everything that we need for earlier versions.
https://github.com/openshift/release/blob/d4024c14be26c22af32871181383b4b415bd0799/ci-operator/step-registry/upi/install/azure/upi-install-azure-commands.sh#L65-L68

**Comment by rna-afk** [comment]
I created https://github.com/openshift/release/pull/24862 in the hopes of fixing the yaml error

**Comment by staebler** [comment]
@LorbusChris I am not seeing good results from the jobs. I am hesitant to add the jobs to the periodics if they are just going to add noise, although I would like to see trends over time.

The two infrastructure failures that I see are (1) the bootstrap VM failed to start and (2) Total Regional Cores quota limits.

/test pj-rehearse

**Comment by LorbusChris** [comment]
@staebler @fabianofranz the test run, but don't (or seldomly) succeed. How do we proceed with this?

**Comment by LorbusChris** [comment]
/reopen
This might still be relevant, cc @fabianofranz

**Pull request closed without merging**
