### PR TITLE
SDCICD-63. Add in osde2e scale tests.

### PR DESCRIPTION
**Pull request by mdwn**
osde2e scale tests have been added.

### CODE REVIEW

**Comment by jeefy** [comment]
@meowfaceman Do the scale tests need to be run every four hours? I feel like a nightly run would suffice (or even twice/day)

**Comment by meowfaceman** [comment]
> @meowfaceman Do the scale tests need to be run every four hours? I feel like a nightly run would suffice (or even twice/day)

Good catch, you're absolutely right. I'll reduce this to once a day.

**Comment by jeremyeder** [comment]
> > @meowfaceman Do the scale tests need to be run every four hours? I feel like a nightly run would suffice (or even twice/day)
> 
> Good catch, you're absolutely right. I'll reduce this to once a day.

But that won't let us run things that take more than 4 hours right?  We still have that prow limit?

**Comment by meowfaceman** [comment]
That's correct. This job only takes 30 minutes though -- we worked through the initial issues of it taking longer than expected.

**Pull request merged**
