### PR TITLE
improve sdn migration ovn steps to add connection coverage

### PR DESCRIPTION
**Pull request by zhaozhanqi**
Add the following coverage during sdn live migration to ovn
1. pod2pod with networkpolicy with different CNI and different worker
2. hostnetwork pod to container pod with networkpolicy with different CNI ( sdn and ovn-k) 
3. from ingress pod with networkpolicy with different CNI and different worker
4. pod with different cni  keep access dns 
5. pod with different cni keep access kapi

### CODE REVIEW

**Comment by zhaozhanqi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-gcp-ipi-sdn-live-migration-ovn-f28

**Comment by zhaozhanqi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-sdn-live-migration-ovn-f28

**Comment by zhaozhanqi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-sdn-live-migration-ovn-f28

**Comment by zhaozhanqi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-sdn-live-migration-ovn-f28

**Comment by zhaozhanqi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-sdn-live-migration-ovn-f28

**Comment by zhaozhanqi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-sdn-live-migration-ovn-f28

**Comment by zhaozhanqi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-sdn-live-migration-ovn-f28

**Comment by zhaozhanqi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-sdn-live-migration-ovn-f28

**Comment by zhaozhanqi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-sdn-live-migration-ovn-f28

**Comment by zhaozhanqi** [comment]
@liangxia Here is the logs https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/59226/rehearse-59226-periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-sdn-live-migration-ovn-f28/1864559823597604864/artifacts/aws-ipi-sdn-live-migration-ovn-f28/cucushift-sdn-live-migration-ovn/build-log.txt

Could you help approve this?

**Comment by liangxia** [comment]
I think someone in the `ci-operator/step-registry/cucushift/sdn-live-migration-ovn/OWNERS` would be the better reviewer/approver for the PR.

**Comment by zhaozhanqi** [comment]
@weliang1 ^^ could you take a look?

**Comment by weliang1** [comment]
> @weliang1 ^^ could you take a look?

@zhaozhanqi Testing looks good to me, some suggestions for improvements:
1. Better to delete names space z3 and z4 at the end for clean up. 
2. Create the third namespace to test your configured networkplicy will only allow pods from z4 to pods in the z3, and block the traffic from pods in new space to pods in the z3. (It's optional, and it's up to you to update it or not)
3. It’s better to add a testing step to check egress traffic from pods to any external site outside the cluster during migration

**Comment by zhaozhanqi** [comment]
> 3. It’s better to add a testing step to check egress traffic from pods to any external site outside the cluster during migration

Yes, that's my next plan to improve ( including egress traffic and egressfirewall), since some cluster is proxy, we need to consider it. .

**Comment by zhaozhanqi** [comment]
@liangxia Could you help approve this?

**Pull request merged**
