### PR TITLE
Stop setting redundant flags

### PR DESCRIPTION
**Pull request by stevekuznetsov**
We should be able to get all of the information we need by using the
GitHub client from the PAT we're loading into these tools.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @hongkailiu 
/hold

### CODE REVIEW

**Comment by hongkailiu** [comment]
I need to change the code before merging those, right?
I will work on this today.

**Comment by hongkailiu** [comment]
dep. on https://github.com/openshift/ci-tools/pull/186

**Comment by stevekuznetsov** [comment]
This needs upstream Git client automation, etc... will re-do later

/close

**Pull request closed without merging**
