### PR TITLE
Add 5 repos to the ignore-repo list for owners autosync

### PR DESCRIPTION
**Pull request by ascerra**
This PR will prevent the autosync mechanism from overriding changes to the release repo OWNERS files for these specific repos.

### CODE REVIEW

**Review by sadlerap — COMMENTED** [review]
SBO change looks good to me, though I'd like some acknowledgement for the other repos.  I wasn't aware of their changes.

**Review by Kartikey-star — APPROVED** [review]
Approving with respect to Helm project.

**Review by rm3l — APPROVED** [review]
Sounds good for odo as well.

**Review by rm3l — APPROVED** [review]

**Review by sadlerap — APPROVED** [review]

**Pull request merged**
