### PR TITLE
Added config openshift/incluster-anomaly-detection

### PR DESCRIPTION
**Pull request by rajusem**
Added configuration (including Prow CI tests) for the recently-created repo openshift/incluster-anomaly-detection.

### CODE REVIEW

**Comment by rajusem** [comment]
/pj-rehearse pull-ci-openshift-incluster-anomaly-detection-main-code-style

**Comment by danilo-gemoli** [comment]
/pj-rehearse pull-ci-openshift-incluster-anomaly-detection-main-code-style

**Comment by rajusem** [comment]
/pj-rehearse pull-ci-openshift-incluster-anomaly-detection-main-unittest

**Comment by rajusem** [comment]
/pj-rehearse pull-ci-openshift-incluster-anomaly-detection-main-lint

**Comment by rajusem** [comment]
/pj-rehearse pull-ci-openshift-incluster-anomaly-detection-main-code-style

**Comment by rajusem** [comment]
/pj-rehearse pull-ci-openshift-incluster-anomaly-detection-main-unittest

**Comment by rajusem** [comment]
/pj-rehearse pull-ci-openshift-incluster-anomaly-detection-main-unittest

**Comment by rajusem** [comment]
/pj-rehearse pull-ci-openshift-incluster-anomaly-detection-main-lint

**Comment by rajusem** [comment]
/pj-rehearse pull-ci-openshift-incluster-anomaly-detection-main-code-style

**Comment by rajusem** [comment]
/pj-rehearse pull-ci-openshift-incluster-anomaly-detection-main-unittest

**Pull request merged**
