### PR TITLE
Update devfile registry to use go 1.21 and OpenShift 4.15

### PR DESCRIPTION
**Pull request by michael-valdron**
# Description

Devfile registry will be using golang 1.21 after pending changes: https://github.com/devfile/registry/pull/420

blocking devfile/api#1558

### CODE REVIEW

**Comment by michael-valdron** [comment]
/pj-rehearse reject

Need to bump OpenShift to ensure best compatibility with Kubernetes 1.29

**Comment by michael-valdron** [comment]
Should really update to OpenShift 4.16 when stable is released.

**Review by maysunfaisal — APPROVED** [review]
/lgtm

**Pull request merged**
