### PR TITLE
Add build pipeline for OVMS 2.15

### PR DESCRIPTION
**Pull request by vaibhavjainwiz**
Add build pipeline for OVMS 2.15

### CODE REVIEW

**Comment by vaibhavjainwiz** [comment]
/pj-rehearse pull-ci-red-hat-data-services-openvino_model_server-rhoai-2.15-images

**Comment by vaibhavjainwiz** [comment]
/pj-rehearse pull-ci-red-hat-data-services-openvino_model_server-rhoai-2.15-images

**Comment by Xaenalt** [comment]
Looks like a dockerfile issue:

```
[4/4] STEP 27/36: COPY --from=build /usr/local/lib64/python3.*/site-packages/MarkupSafe-2.1.5.dist-info /ovms/python_deps/MarkupSafe-2.1.5.dist-info
error: build error: building at STEP "COPY --from=build /usr/local/lib64/python3.*/site-packages/MarkupSafe-2.1.5.dist-info /ovms/python_deps/MarkupSafe-2.1.5.dist-info": checking on sources under "/var/lib/containers/storage/overlay/58d614296ea6025e7deaf801be76f7ee77c68270a4e2fa5e1fa103f3ded8a989/merged": Rel: can't make  relative to /var/lib/containers/storage/overlay/58d614296ea6025e7deaf801be76f7ee77c68270a4e2fa5e1fa103f3ded8a989/merged; copier: stat: ["/usr/local/lib64/python3.*/site-packages/MarkupSafe-2.1.5.dist-info"]: no such file or directory
```

**Comment by rpancham** [comment]
/pj-rehearse pull-ci-red-hat-data-services-openvino_model_server-rhoai-2.15-images

**Review by rpancham — APPROVED** [review]

**Comment by Xaenalt** [comment]
I'm at a bit of a loss as to why this is erroring here, code in the repo is identical to 2.14...

**Pull request merged**
