### PR TITLE
add periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.17-lp-interop-jboss-fuse-interop-aws

### PR DESCRIPTION
**Pull request by amp-rh**
[INTEROP-7438](https://issues.redhat.com/browse/INTEROP-7438)

### CODE REVIEW

**Comment by amp-rh** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.17-lp-interop-jboss-fuse-interop-aws

**Comment by amp-rh** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.17-lp-interop-jboss-fuse-interop-aws

**Comment by amp-rh** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.17-lp-interop-jboss-fuse-interop-aws

**Comment by amp-rh** [comment]
/assign 
chetna14manku
jvrubel

**Comment by smongiar** [comment]
@amp-rh the PR looks good to me, but the rehearsal jobs are failing for some reason we cannot investigate through log. Looking at the periodic run history, the last successful one was on the 29th of June:

Screenshot from 2024-07-08 09-17-10

What changed exactly?

**Comment by amp-rh** [comment]
> @amp-rh the PR looks good to me, but the rehearsal jobs are failing for some reason we cannot investigate through log. Looking at the periodic run history, the last successful one was on the 29th of June:
> 
> What changed exactly?

[The changes made to ci-operator/step-registry/jboss-fuse/run-tests/jboss-fuse-run-tests-ref.yaml ](https://github.com/openshift/release/blame/561f8abc5e77803566ab40e1930dbea8e60a683c/ci-operator/step-registry/jboss-fuse/run-tests/jboss-fuse-run-tests-ref.yaml)marked the failing tests as changed. The changes only included an increase to the ref step timeout and a typo fix.

**Comment by smongiar** [comment]
> > @amp-rh the PR looks good to me, but the rehearsal jobs are failing for some reason we cannot investigate through log. Looking at the periodic run history, the last successful one was on the 29th of June:
> > What changed exactly?
> 
> @smongiar [The changes made to ci-operator/step-registry/jboss-fuse/run-tests/jboss-fuse-run-tests-ref.yaml ](https://github.com/openshift/release/blame/561f8abc5e77803566ab40e1930dbea8e60a683c/ci-operator/step-registry/jboss-fuse/run-tests/jboss-fuse-run-tests-ref.yaml)marked the failing tests as changed. The changes only included an increase to the ref step timeout and a typo fix.

Ok, I was just wondering, why previously working pipelines are failing now, I agree with you that your changes have no impact on that. Anyway, I agree to merge the PR but we need to investigate on the infra side about failures. Thank you @amp-rh

**Review by smongiar — APPROVED** [review]

**Pull request merged**
