### PR TITLE
test openshift os in openshift

### PR DESCRIPTION
**Pull request by cheesesashimi**
This PR makes use of the new scripts found in openshift/os to build and test an RHCOS image. The new tests include an OS derivation test wherein the candidate RHCOS image is mutated in a test cluster, applied to a cluster node, and the cluster node rebooted to verify that it successfully boots into the new OS.

### CODE REVIEW

**Comment by cgwalters** [comment]
Neat!  So I think ultimately we can probably extend this to support a full flow where the OS build is actually used for the *initial* update target, i.e. we override `machine-os-content` or equivalent too.

But testing one worker node is a very useful pattern.

**Comment by cgwalters** [comment]
Hmm though, a lot of PRs today have near-zero chance to break cluster provisioning or layering.
I think right now our current "build-test-qemu" flow is a decent gate - this is making that CI check *much* more expensive and likely to flake (e.g. capacity issues).

WDYT about introducing e.g. `/test e2e-node-layering` as an optional opt-in context (and continue to execute it in a periodic).

Ultimately if we start using lockfiles for RHCOS - that's where pull request based gating would become much more useful, because that's where we'd be able to gate new kernel/systemd and really all the other packages.

(And if we had that, then we could drop the promotion job)

**Comment by travier** [comment]
> Hmm though, a lot of PRs today have near-zero chance to break cluster provisioning or layering. I think right now our current "build-test-qemu" flow is a decent gate - this is making that CI check _much_ more expensive and likely to flake (e.g. capacity issues).
> 
> WDYT about introducing e.g. `/test e2e-node-layering` as an optional opt-in context (and continue to execute it in a periodic).

That's my concern too. It would be preferable two different tests to decouple the failures. Can we have tests launch only if some other tests succeed in Prow?

**Comment by travier** [comment]
I'm not up to speed about how Prow works and what we can do so this might not make sense.

Could we do the image build in the build stage and store the result directly in the container image? We could then pull it for testing with distinct tests:
- kola (full)
- kola (basic) + e2e
- kola (basic) + layering test

Similarly, I'm working on https://github.com/openshift/release/pull/27686 to make SCOS builds from the same branch.

**Comment by cheesesashimi** [comment]
@travier Funny you ask that question! When I was doing early exploratory work, [I didn't think that was possible](https://github.com/openshift/os/issues/600#issuecomment-1034264117). The issue that I was running into was somehow converting the OCI image archive that COSA produces into an image without doing something like `$ skopeo copy`. I was getting stuck on what I thought was an issue with the OpenShift image builder (it was appending a `/` onto the path for the OCI archive). On a hunch yesterday afternoon, I revisited my assumptions, and it turns out that [it is possible](https://github.com/openshift/release/pull/27779/files#diff-2b767984d563832440148da073ee36879bb8dd6c6af38d3ee6f3dc29de237e9fR38-R59) to convert that OCI archive into your final image; you have configure your image build to accept an input and then you have to provide an absolute path to where that input is.

In the example highlighted above, I'm using `skopeo` to pull an image into an OCI archive and placing that into the build context so that I can then do `FROM oci-archive:/absolute/path/to/oci/archive` to create the final image from the on-disk OCI archive. I was able to get COSA build to run in an image build yesterday although I'll need to move the testing steps to test phases as you've described. I plan on opening a PR to `openshift/os` today to decouple the `cosa build` and `kola test` portions of the build and test script.

**Comment by cheesesashimi** [comment]
This has been superceded by https://github.com/openshift/release/pull/27779

**Pull request closed without merging**
