### PR TITLE
Add auto trigger

### PR DESCRIPTION
**Pull request by rnetser**

### CODE REVIEW

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-multi-cluster-smoke-v4.14-test-fail-setup-skip-test

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-multi-cluster-smoke-v4.14-test-fail-setup-skip-test

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-multi-cluster-smoke-v4.14-test-fail-setup-skip-test

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-multi-cluster-smoke-v4.14-test-fail-setup-skip-test

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-multi-cluster-smoke-v4.14-test-fail-setup-skip-test

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-multi-cluster-smoke-v4.14-test-fail-setup-skip-test

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-multi-cluster-smoke-v4.14-test-fail-setup-skip-test

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-multi-cluster-smoke-v4.14-test-fail-setup-skip-test

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-multi-cluster-smoke-v4.14-test-fail-setup-skip-test

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-multi-cluster-smoke-v4.14-test-fail-setup-skip-test

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-multi-cluster-smoke-v4.14-test-fail-setup-skip-test

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-multi-cluster-smoke-v4.14-test-fail-setup-skip-test

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-multi-cluster-smoke-v4.14-test-fail-setup-skip-test

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-multi-cluster-smoke-v4.14-test-fail-setup-skip-test

**Review by myakove — APPROVED** [review]

**Pull request merged**
