### PR TITLE
Bug 1909849 migrate broken aws-fips upgrade periodics to multi-stage

### PR DESCRIPTION
**Pull request by petr-muller**
A version of https://github.com/openshift/release/pull/16322 that passes tests and also moves the matching 4.3 job

/cc @sallyom

### CODE REVIEW

**Comment by petr-muller** [comment]
Looks fine, 4.3 fails everywhere on that Prometheus glitch and 4.4 passed.

**Comment by sallyom** [comment]
@petr-muller right, I could not figure out why the `ci/prow/release-controller-config` was failing in https://github.com/openshift/release/pull/16322  If this PR is good, please merge it! I'll close the #16322 then.  Thank you!  
I've also updated the linked bug to be valid

**Review by sallyom — APPROVED** [review]
/lgtm

**Comment by petr-muller** [comment]
/retitle Bug 1909849 migrate broken aws-fips upgrade periodics to multi-stage

**Comment by petr-muller** [comment]
@sallyom looks like I cannot link the bug to the PR post-merge

**Pull request merged**
