### PR TITLE
Fixing openshift-builder-master.yaml to use dockerfile from ocp-build-data

### PR DESCRIPTION
**Pull request by alvaroaleman**

### CODE REVIEW

**Comment by gabemontero** [comment]
> /lgtm cancel
> 
> @alvaroaleman @gabemontero can we review why we were using the rhel8 Dockerfile in ocp-build-data?

it stems from @yselkowitz 's ubi8 migration efforts .... aside from his PR https://github.com/openshift/builder/pull/165
he has this note in https://docs.google.com/document/d/13QoTt78qyGm08D_f6K8pj9xlH7cG721yj-G5BwBzgZY/edit?ts=5f0dbcb1#

builder: sysvinit-tools -> procps-ng/util-linux

**Comment by alvaroaleman** [comment]
Yeah there is currently an ongoing effort to make everything UBI 8 based. @jupierce can provide more details on that.

**Comment by adambkaplan** [comment]
/close

Replacing with #10917

**Pull request closed without merging**
