### PR TITLE
Update ci job for che-plugin-registry repo

### PR DESCRIPTION
**Pull request by svor**
- Update job for che-plugin registry to use OS 12
- Remove che-plugin-registry nightly job (outdated)

### CODE REVIEW

**Comment by svor** [comment]
@tolusha @artaleks9 Are you able to review this PR?
Do you know whom should I ask to add me (svor) as a [member](https://github.com/orgs/openshift/people) of the openshift org to be an owner of the contributed files?

**Comment by artaleks9** [comment]
@svor 
| _Are you able to review this PR?_
I don't have an access to this PR as reviewer. Perhaps, until the 'OWNERS' file won't be changed.

**Comment by svor** [comment]
> @tolusha @artaleks9 Are you able to review this PR? Do you know whom should I ask to add me (svor) as a [member](https://github.com/orgs/openshift/people) of the openshift org to be an owner of the contributed files?

/cc @smg247

**Review by artaleks9 — APPROVED** [review]

**Review by artaleks9 — APPROVED** [review]

**Pull request merged**
