### PR TITLE
Disable devfile tests on OCP 4.9

### PR DESCRIPTION
**Pull request by josephca**
Signed-off-by: Joseph Kim <joskim@redhat.com>

Disable devfile tests on OCP 4.9 and adjust the periodic test intervals accordingly.

### CODE REVIEW

**Comment by josephca** [comment]
/pj-rehearse periodic-ci-devfile-integration-tests-main-v4.12.console-e2e-gcp-console-periodic

**Review by elsony — APPROVED** [review]
/lgtm

**Pull request merged**
