### PR TITLE
logging CI tests for journald, json-file, and crio

### PR DESCRIPTION
**Pull request by richm**
This adds tests for logging CI for docker with --log-driver=journald,
for docker with --log-driver=json-file, and for crio

### CODE REVIEW

**Comment by richm** [comment]
ci/prow/generated-config requires a new version of `ci-operator` built with https://github.com/openshift/ci-operator/pull/212

**Comment by petr-muller** [comment]
`ci-operator` is fine but Prowgen needs to be updated too

**Comment by petr-muller** [comment]
https://github.com/openshift/ci-operator-prowgen/pull/46 needs to merge, then Prow job configs will need to be regenerated in this PR to pick up correct profile references.

**Pull request closed without merging**
