### PR TITLE
OADP-master: Add e2e for ocp version 4.12

### PR DESCRIPTION
**Pull request by hhpatel14**

### CODE REVIEW

**Comment by hhpatel14** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-master-4.12-operator-e2e-azure

**Comment by hhpatel14** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-master-4.12-operator-e2e-azure

**Comment by hhpatel14** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-master-4.12-operator-e2e-aws

**Review by sseago — APPROVED** [review]

**Comment by kaovilai** [comment]
replaces https://github.com/openshift/release/pull/39107

**Pull request merged**
