### PR TITLE
Migrate from master-sidecar-4 to master-sidecar-4.2

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by adambkaplan** [comment]
don't we need `master-4` to run 4.1-related PRs?

**Comment by dmage** [comment]
Yes, we might want to have the 4.1 API for the release-4.1 branch. But this .yaml file doesn't specify which version of OpenShift should be started. The only difference is

```diff
--- master-sidecar-4.yaml	2019-07-20 12:01:28.000000000 +0200
+++ master-sidecar-4.2.yaml	2019-07-20 12:01:28.000000000 +0200
@@ -1299,8 +1299,8 @@
       {\n    if [ ! -d \"${LOCALUP_CONFIG}/kube-apiserver\" ]; then\n        mkdir -p
       ${LOCALUP_CONFIG}/kube-apiserver\n        cp ${base}/kube-apiserver.yaml ${LOCALUP_CONFIG}/kube-apiserver\n
       \       local::master::generate_kubeapiserver_certs\n    fi\n\n    KUBE_APISERVER_LOG=${LOG_DIR}/kube-apiserver.log\n
-      \   hypershift openshift-kube-apiserver \\\n      --v=${LOG_LEVEL} \\\n      --vmodule=\"${LOG_SPEC}\"
-      \\\n      --config=${LOCALUP_CONFIG}/kube-apiserver/kube-apiserver.yaml >\"${KUBE_APISERVER_LOG}\"
+      \   hyperkube kube-apiserver \\\n      --v=${LOG_LEVEL} \\\n      --vmodule=\"${LOG_SPEC}\"
+      \\\n      --openshift-config=${LOCALUP_CONFIG}/kube-apiserver/kube-apiserver.yaml >\"${KUBE_APISERVER_LOG}\"
       2>&1 &\n    KUBE_APISERVER_PID=$!\n\n    # Wait for kube-apiserver to come up
       before launching the rest of the components.\n    local::master::log::info \"Waiting
       for kube-apiserver to come up\"\n    local::master::util::wait_for_url \"https://${API_HOST_IP}:${API_SECURE_PORT}/healthz\"
```

Also if we needed it, we could restore it from the git history.

**Comment by runcom** [comment]
can we get this in to unblock https://github.com/openshift/image-registry/pull/183 which is blocking a kube-drain library update in MCO?

**Comment by adambkaplan** [comment]
/lgtm

ping @stevekuznetsov

**Pull request merged**
