### PR TITLE
Move OpenStack CCCMO jobs to vh-managed

### PR DESCRIPTION
**Pull request by mandre**
vh-mecha-central was recently re-deployed and we added a proxy to reach the provider network where the FIPs are. This caused the LB UDP tests to fail as it's not compatible with the environment.

Move the jobs to vexxhost managed cloud, where we have public IP addresses for the FIPs.

### CODE REVIEW

**Comment by mandre** [comment]
@JoelSpeed if you were wondering why the OpenStack LB tests started failing in your PRs.

/assign @JoelSpeed

**Comment by mandre** [comment]
/pj-rehearse pull-ci-openshift-cluster-cloud-controller-manager-operator-release-4.14-e2e-openstack-ovn

**Comment by EmilienM** [comment]
@mandre the thing that I worry is that managed VEXXHOST doesn't have multiple AZ therefore we won't use that cloud to test failure domains in CCPMSO... I wonder why we need that job then?
I think we should work on making that job running on mecha in multiple AZ.

**Review by damdo — COMMENTED** [review]
/approve
/lgtm

**Review by elmiko — COMMENTED** [review]
/approve

**Pull request merged**
