### PR TITLE
[vsphere] adds multi-zone variant to vsphere

### PR DESCRIPTION
**Pull request by rvanderp3**
adds a multi-zone variant such that multi-zone vSphere installs can be performed via clusterbot

depends on https://github.com/openshift/ci-chat-bot/pull/297

### CODE REVIEW

**Comment by bradmwilliams** [comment]
@rvanderp3 Typically, the `openshift/release` PR should merge *before* the `openshift/ci-chat-bot` PR.  This PR puts the pieces in place (first), and the other PR enables it to be executed (second).

**Comment by rvanderp3** [comment]
> @rvanderp3 Typically, the `openshift/release` PR should merge _before_ the `openshift/ci-chat-bot` PR. This PR puts the pieces in place (first), and the other PR enables it to be executed (second).

oh man, sorry about that.  I'll go ahead and lift the hold on this one.  Sorry for all the noise today :)
/hold cancel

**Review by bradmwilliams — APPROVED** [review]

**Comment by rvanderp3** [comment]
updated to force the cluster profile to vsphere-multizone

**Review by bradmwilliams — APPROVED** [review]

**Pull request merged**
