### PR TITLE
BYOR 4.0: run RHEL scaleup as an additional test in machine-api-operator

### PR DESCRIPTION
**Pull request by vrutkovs**
Add an optional `e2e-rhel-scaleup` job to test RHEL scaleup in Machine API Operator PRs. It won't be executed on all PRs.

### CODE REVIEW

**Comment by enxebre** [comment]
What's the expectation here?
How does this interact with the machine api operator?
Can you point to the scaleup test source code?

**Comment by vrutkovs** [comment]
Scaleup test playbook - https://github.com/openshift/openshift-ansible/blob/devel-40/test/aws/scaleup.yml
It does the following:
* sets up ssh bastion for ansible to reach workers via ssh
* clones existing machinesets, replacing the RHCOS AMI with Centos AMI
* waits for new machines to be created and adds them to ansible inventory
* runs RHEL scaleup playbook - this would install crio, kubelet and runs 'mco --once-from' to copy necessary configs on the nodes . Mco would reboot the node on success
* the playbook would wait for nodes to join the cluster
* test playbook would drain existing CoreOS nodes and remove them from the cluster
* Once playbook has passed standard e2e tests start with only RHEL workers in the cluster

The expectation is that e2e tests pass on RHEL nodes successfully. Changes in machine API might require us to change the playbooks, so we would like to be notified on that early

**Comment by enxebre** [comment]
"* test playbook would drain existing CoreOS nodes and remove them from the cluster"
By just deleting the machineSets, the nodes should get drained automatically

**Comment by vrutkovs** [comment]
>By just deleting the machineSets, the nodes should get drained automatically

Right, we prefer to do that manually so that tests would start when cluster is already stable - although its not strictly necessary

**Comment by enxebre** [comment]
Yeah, you could integrate these into just one step i.e `remove existing machinesets` https://github.com/openshift/openshift-ansible/blob/devel-40/test/aws/scaleup.yml#L127-L144
Then just wait for the cluster to achieve your expected state before running the tests

How long does it take this tests? can we not make this block the mao repo initially?
This needs to be run any of the components involved, e.g https://github.com/openshift/openshift-ansible otherwise any change in those could potentially silently break the mao CI

**Comment by vrutkovs** [comment]
>How long does it take this tests? 

About 10 mins to scaleup RHEL nodes - and usual installer + test time

> can we not make this block the mao repo initially?

This test won't be started automatically on every PR and marked as 'optional'. If you're in doubt that some Machine API change will break RHEL scaleup (e.g. creating a machine with custom AMI), please start the test with `/test e2e-rhel-scaleup`. If it fails due to other reason use `/skip` to remove the status - it won't block the merge (please notify us that it fails if possible)

>This needs to be run also against any of the components involved with the e2e expectation

This is a blocking test for openshift-ansible, yes

**Comment by petr-muller** [comment]
Why did Tide not retest the jobs for this PR before merge? It let a mistake in :/

**Pull request merged**
