### PR TITLE
Remove the reset_host function

### PR DESCRIPTION
**Pull request by aleskandro**

### CODE REVIEW

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-arm64-nightly-baremetal-pxe-compact-agent-ipv4-static-connected-f14

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-upi-ovn-ipv4-f14

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-multi-nightly-baremetal-upi-ovn-ipv4-f14

**Comment by aleskandro** [comment]
/pj-rehease periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-upi-ovn-ipv4-f14

/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-arm64-nightly-baremetal-pxe-compact-agent-ipv4-static-connected-f14

/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-multi-nightly-baremetal-upi-ovn-ipv4-f14

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-arm64-nightly-baremetal-pxe-compact-agent-ipv4-static-connected-f14

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-multi-nightly-baremetal-upi-ovn-ipv4-f14

**Comment by aleskandro** [comment]
/pj-rehearse ack

failures are beyond the scope of this pr.

**Review by sgoveas — COMMENTED** [review]
/lgtm

**Pull request merged**
