### PR TITLE
Remove bushslicer job

### PR DESCRIPTION
**Pull request by thekad**
Unsure about bac6efb78, can revert if needed

cc @openshift/sig-azure

### CODE REVIEW

**Comment by ehashman** [comment]
Might need to rerun prowgen to get the generated-config test passing (see https://github.com/openshift/release/pull/3580#issuecomment-486389448).

**Comment by thekad** [comment]
> Might need to rerun prowgen to get the generated-config test passing (see [#3580 (comment)](https://github.com/openshift/release/pull/3580#issuecomment-486389448)).

turns out prowgen wants the images jobs back, let's go step by step

**Comment by kwoodson** [comment]
@ehashman @thekad,  this was one that I worked on with the previous QE representative on our team.  @mgahagan73 is now the QE representative on our team.  The bushslicer test suite is our internal OpenShift test suite that we wanted to run on our cluster to ensure compatibility.

I think we still want to use bushslicer.  @mgahagan73, Thoughts?

**Comment by ehashman** [comment]
@kwoodson Bushslicer hasn't been passing for months (has it ever passed?): https://openshift-gce-devel.appspot.com/builds/origin-ci-test/logs/periodic-ci-openshift-openshift-azure-master-bushslicer/

I don't think we have the resources to get it to pass any time soon so the plan is to cut our losses and remove it.

**Comment by kwoodson** [comment]
@ehashman 
I agree that it will take some engineering effort but here are the results:
```
33 scenarios (5 failed, 28 passed)
551 steps (5 failed, 71 skipped, 475 passed)
30m10.030s
[08:23:48] INFO> === At Exit ===
---
```

The reason for the failures are a matter of us running the incorrect set of tests(OCP) against our enterprise version.  

https://github.com/openshift/openshift-azure/issues/909
https://github.com/openshift/openshift-azure/issues/963

This fails for a wide number of reasons:
- 401 `Login failed (401 Unauthorized)` Investigation needed
- `error pulling image registry.svc.ci.openshift.org/ci/clonerefs@sha256:835268c14fbcad843bc9752ba579ec3be2e7d19c94f6dfc627a3dacfeaf1afce: received unexpected HTTP status: 500 Internal Server Error`
- flake `time="2019-02-14T07:49:01Z" level=fatal msg="containerservice.OpenShiftManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: error response cannot be parsed: \"400 Bad Request: Failed to apply request: WaitForNodes: Get https://e2e-yuqqyyes.eastus.cloudapp.azure.com/api/v1/nodes/master-000000: read tcp 172.16.157.75:54230->20.42.25.74:443: read: connection timed out\\n\" error: json: cannot unmarshal number into Go value of type azure.RequestError"`


If the team decides that this test suite is not valuable then please remove.  I think that it does provide value when it does actually run.  I think @e-tienne or @mgahagan73 could help us out here.

**Comment by ehashman** [comment]
We haven't had a successful run of the test suite in a few months but didn't really notice, so I'm not sure how much value we're getting out of this test or if we have the resources to get this working. At this point I think this is a sunk cost and we consider adding it back for ARO 4.x. I'm gonna approve this PR but hold off on the LGTM until we hear back from QE. We can always revert if we change our minds :)

/approve

**Comment by ehashman** [comment]
/hold

Waiting on sync with QE.

**Comment by ehashman** [comment]
QE is going to fix the bushslicer job. I'm wondering if we should still proceed with the removal here and add it back later? Thoughts?

**Comment by thekad** [comment]
@ehashman I think we can proceed in removing it, since if we want to add back the bushslicer job it will not be using ci-operator image anyway and the config *will* change, wdyt @kwoodson @mgahagan73 ?

**Comment by mgahagan73** [comment]
If we want to remove it for now and add it back later then that's fine, Here is where we are currently:

All the tests that need ssh access to the nodes are currently working using az to grab the IP's of each node. 

Logs are working now but logging format is junit which I think we can handle ok. There is a results summary as well. 

Web-based logins are not working because the verification tests aren't working with the MS login prompts. 

I still need to figure out how to get a login token to pass to the tests given what we were using before is no longer available. 

Test  output summary:
Failing Scenarios:
cucumber -p junit -p dir_embedder /home/test/verification-tests/features/images/jenkins.feature:157 # Scenario Outline: Trigger build of application from jenkins job with persistent volume, Examples (#2)
cucumber -p junit -p dir_embedder /home/test/verification-tests/features/images/jenkins.feature:208 # Scenario Outline: Make jenkins slave configurable when do jenkinspipeline strategy with maven slave, Examples (#2)
cucumber -p junit -p dir_embedder /home/test/verification-tests/features/online/metrics.feature:5 # Scenario: Ordinary user could view CPU,memory, network metrics statistics on pod page of openshift web console
cucumber -p junit -p dir_embedder /home/test/verification-tests/features/web/service-catalog/project.feature:5 # Scenario: Manage project in popup panel on home page

28 scenarios (4 failed, 24 passed)
494 steps (4 failed, 35 skipped, 455 passed)
38m5.030s
[20:30:57] INFO> === At Exit ===

**Comment by ehashman** [comment]
Okay, let's merge this and figure out how to add back bushslicer later.

/lgtm

**Pull request merged**
