### PR TITLE
Remove releases from hypershift addon CI configuration

### PR DESCRIPTION
**Pull request by rokej**
Removed `releases` from hypershift addon CI configuration

### CODE REVIEW

**Comment by rokej** [comment]
/pj-rehearse pull-ci-stolostron-hypershift-addon-operator-backplane-2.5-sonar

**Comment by rokej** [comment]
/pj-rehearse pull-ci-stolostron-hypershift-addon-operator-main-sonar

**Review by mikeshng — APPROVED** [review]
/lgtm

**Pull request merged**
