### PR TITLE
Sdn 2893 aws ovn serial payload blockers

### PR DESCRIPTION
**Pull request by jluhrsen**

### CODE REVIEW

**Comment by jluhrsen** [comment]
/hold

this can't be done until https://github.com/openshift/release/pull/27959 is merged

**Comment by dgoodwin** [comment]
I will discuss with team but I am PTO until Monday.

/hold

CC @neisw regarding something possibly wrong with the alert.

**Comment by jluhrsen** [comment]
@dgoodwin , the job still is just as stable as the openshift-sdn version. can we get this in?

**Comment by dgoodwin** [comment]
I need to talk to my manager and staff engineer first chance we're all on a call. We are extremely hesitant to take on more blocking jobs given what it means for payload success, it would be very easy to start jamming up code shipping to the whole org if this goes wrong.

I don't know if we can say this is as successful as sdn: https://sippy.dptools.openshift.org/sippy-ng/jobs/4.11?filters=%257B%2522items%2522%253A%255B%257B%2522columnField%2522%253A%2522name%2522%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522aws-serial%2522%257D%252C%257B%2522columnField%2522%253A%2522name%2522%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522aws-ovn-serial%2522%257D%255D%252C%2522linkOperator%2522%253A%2522or%2522%257D&sort=asc&sortField=net_improvement

You're below but close for nightly, but it's not running nearly as often, hard to have confidence in 3-4 runs per week. Can you bump this up to a few times a day and see if we can get a clearer signal.

I will broach with team as soon as possible.

**Comment by jluhrsen** [comment]
> I need to talk to my manager and staff engineer first chance we're all on a call. We are extremely hesitant to take on more blocking jobs given what it means for payload success, it would be very easy to start jamming up code shipping to the whole org if this goes wrong.
> 

what about removing the openshift-sdn version of these jobs in 4.11 and higher. The push here is to get OVN more
attention in our CI pipelines since it will be our default CNI soon.

> I don't know if we can say this is as successful as sdn: https://sippy.dptools.openshift.org/sippy-ng/jobs/4.11?filters=%257B%2522items%2522%253A%255B%257B%2522columnField%2522%253A%2522name%2522%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522aws-serial%2522%257D%252C%257B%2522columnField%2522%253A%2522name%2522%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522aws-ovn-serial%2522%257D%255D%252C%2522linkOperator%2522%253A%2522or%2522%257D&sort=asc&sortField=net_improvement
> 
> You're below but close for nightly, but it's not running nearly as often, hard to have confidence in 3-4 runs per week. Can you bump this up to a few times a day and see if we can get a clearer signal.

yeah, it's close but not quite there yet I guess.

[here](https://github.com/openshift/release/pull/28685) is a PR to run these things 3 times a day

> 
> I will broach with team as soon as possible.

Thank you! :)

**Comment by dgoodwin** [comment]
Demoting SDN would definitely help us not overwhelm TRT in keeping payloads flowing.

**Comment by dgoodwin** [comment]
5% pass rate last 7 days :(

**Comment by jluhrsen** [comment]
> 5% pass rate last 7 days :(

yeah, I know @dgoodwin, we have [this issue](https://issues.redhat.com/browse/SDN-3087) to figure out which definitely looks like trouble in OVN somewhere.

**Pull request closed without merging**
