### PR TITLE
Onboarding KubeFed to CI

### PR DESCRIPTION
**Pull request by sohankunkerkar**

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
```
 error: failed to determine job spec: failed to resolve --git-ref: ref 'release-v0.1.0' does not point to any commit in 'openshift/kubefed' 
```

Does the branch exist?

**Comment by sohankunkerkar** [comment]
> ```
>  error: failed to determine job spec: failed to resolve --git-ref: ref 'release-v0.1.0' does not point to any commit in 'openshift/kubefed' 
> ```
> 
> Does the branch exist?

@stevekuznetsov  No, it doesn't exist. I have already changed the name to make it work. Do you still see that issue?

**Pull request merged**
