### PR TITLE
Update golang version to 1.18 for power vs cloud provider

### PR DESCRIPTION
**Pull request by Karthik-K-N**
This PR contains the changes to update golang to version 1.18

Reference PR: https://github.com/openshift/release/pull/27913

### CODE REVIEW

**Review by mkumatag — COMMENTED** [review]
/lgtm

**Review by mkumatag — APPROVED** [review]
/approve

/hold for others to review

**Review by elmiko — COMMENTED** [review]
looks very similar to what we did for the aws and ibm cloud providers
/lgtm

**Pull request merged**
