### PR TITLE
MCE Agent Power - Address changes required in ibmcloud cli command due to latest power-iaas plugin

### PR DESCRIPTION
**Pull request by dharaneeshvrd**

### CODE REVIEW

**Comment by dharaneeshvrd** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-mce-power-conformance

**Comment by dharaneeshvrd** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-mce-power-conformance

**Comment by dharaneeshvrd** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-mce-power-conformance

**Review by mkumatag — APPROVED** [review]
/lgtm

**Comment by mkumatag** [comment]
for long run, lets plan to use the newer version and use those latest subcommands.

**Review by Shilpa-Gokul — APPROVED** [review]

**Pull request merged**
