### PR TITLE
golang version update to 1.18

### PR DESCRIPTION
**Pull request by kim-tsao**
Update to v1.18 to fix failing CI tests for https://github.com/devfile/api/issues/1013

Signed-off-by: Kim Tsao <ktsao@redhat.com>

### CODE REVIEW

**Review by elsony — APPROVED** [review]
/lgtm

**Comment by kim-tsao** [comment]
/pj-rehearse  pull-ci-devfile-registry-operator-main-v4.12-images,  pull-ci-devfile-registry-operator-main-v4.12-registry-operator-integration-test

**Comment by kim-tsao** [comment]
/pj-rehearse pull-ci-devfile-registry-operator-main-v4.12-images

**Comment by kim-tsao** [comment]
opting out of running `pull-ci-devfile-registry-operator-main-v4.12-registry-operator-integration-test` since that depends on changes from https://github.com/devfile/registry-operator/pull/33 and will be run as part of that PR check

**Pull request merged**
