### PR TITLE
RHODS: Update OWNERS file

### PR DESCRIPTION
**Pull request by samuelvl**
Update OWNERS file to match the current working members and remove CI jobs for https://github.com/red-hat-data-services/cuda-minimal-notebook

### CODE REVIEW

**Review by LaVLaS — APPROVED** [review]
/lgtm

**Comment by samuelvl** [comment]
Hey @hongkailiu @bear-redhat @bbguimaraes  I think I need your approval since I'm removing `red-hat-data-services-cuda-minimal-notebook-main` job in `core-services/sanitize-prow-jobs/_config.yaml` file

**Review by anishasthana — APPROVED** [review]
/lgtm 😿

**Comment by danilo-gemoli** [comment]
@samuelvl we're a little bit late, I'm sorry.
I'm going to lgtm (yet another reason to do that: branch-protector job is failing) this and put it on hold for a while just o double check it with one of my more experienced colleague.
/lgtm
/hold

**Comment by danilo-gemoli** [comment]
@samuelvl can you please rebase it?

**Pull request closed without merging**
