### PR TITLE
feat: add security scanning for powermon

### PR DESCRIPTION
**Pull request by vprashar2929**
This PR adds snyk security scanning for PowerMonitoring Operator(`v1alpha1` and `tech-preview` branches) and Kepler(`main` branch). The scans will be triggered on every PR creation.

Report URL: https://app.snyk.io/org/openshift-ci-internal/project/393b2488-0987-4719-9036-69af3ced9988

### CODE REVIEW

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-power-monitoring-operator-v1alpha1-security

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-power-monitoring-operator-v1alpha1-security

**Review by sthaha — COMMENTED** [review]
/lgtm

**Pull request merged**
