### PR TITLE
Enable arm64 image builds for the Openshift organization

### PR DESCRIPTION
**Pull request by droslean**
/cc @openshift/test-platform @deepsm007 @danilo-gemoli 
Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

### CODE REVIEW

**Comment by droslean** [comment]
Needs https://github.com/openshift/ci-tools/pull/3137

**Comment by hongkailiu** [comment]
Nice work on ci-tools post-submit!
Maybe try with one or 2 ocp core components before enabling the whole org?
Do we need to build every image in the org for arm64? Can arm01 handle the workload?

**Comment by droslean** [comment]
@hongkailiu We won't gain anything by enabling one or two core components that is why I want to enable all of them to see the missing pieces and if the arm01 cluster can handle the workload as well. So, your concerns are right, that is why I opened this PR.

**Comment by danilo-gemoli** [comment]
We are going to merge this PR in order to assess the entire promotion lifecycle.
We know some pieces are missing and one of the best way to understand what those pieces are is to merge this PR and see what works and what doesn't.
Analyze every `ci-operator` configuration could not be enough to spot every issue as there are some images being built outside any configuration (check `machine-os-content` image on [openshift-release-release-4.13-periodics.yaml](https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/release/openshift-release-release-4.13-periodics.yaml#L32-L67))

/lgtm
/hold

@droslean @hongkailiu

**Comment by osherdp** [comment]
> @osherdp Can you ignore the alerts? or you can open a PR to disable the multi-architecture builds for your repo.

Sure thing. I'll disable the multi-arch builds for now to make the signal a little better

**Pull request merged**
