### PR TITLE
Submariner addon: set up the 2.7 branch

### PR DESCRIPTION
**Pull request by skitt**
This adds the 2.7 configuration and jobs, and configures the main
branch so it is automatically promoted to the release-2.7 branch, and
artifacts published to 2.7.

### CODE REVIEW

**Comment by skitt** [comment]
This needs the `release-2.7` branch to be created first.

**Comment by skitt** [comment]
@gurnben this is ready to go, the Sonar failures are expected.

**Comment by skitt** [comment]
@gurnben this still needs a “lgtm” if it’s OK to merge (the Sonar failures are expected).

**Comment by gurnben** [comment]
Ah, sorry I missed this!  
/lgtm

**Pull request merged**
