### PR TITLE
Add release-openshift-origin-installer-launch-openstack task

### PR DESCRIPTION
**Pull request by vrutkovs**
Used by cluster-bot to start Openstack cluster

### CODE REVIEW

**Comment by vrutkovs** [comment]
Worked as expected in [this job](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-openstack/1437455427620048896)

**Review by EmilienM — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
