### PR TITLE
[SPLAT-986][vsphere]enable 4.13 --> 4.14 multi-zone upgrade job

### PR DESCRIPTION
**Pull request by WenXinWei**
to add multi-zone upgrade job for vsphere.

### CODE REVIEW

**Comment by WenXinWei** [comment]
pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-4.14-upgrade-from-stable-4.13-vsphere-ipi-zones-f28

**Comment by WenXinWei** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-4.14-upgrade-from-stable-4.13-vsphere-ipi-zones-f28

**Comment by WenXinWei** [comment]
@jianlinliu @jinyunma @gpei  please help review the pr when you have time.

**Comment by jianlinliu** [comment]
cc @jhou1 and @liangxia to review

**Pull request merged**
