### PR TITLE
OSSM-3270: Migrate proxy postsubmit jobs

### PR DESCRIPTION
**Pull request by yxun**

### CODE REVIEW

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-proxy-maistra-2.2-copy-artifacts-gcs-2-2

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-proxy-maistra-2.2-copy-artifacts-gcs-2-2

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-proxy-maistra-2.2-copy-artifacts-gcs-2-2

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-proxy-maistra-2.2-copy-artifacts-gcs-2-2

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-proxy-maistra-2.2-copy-artifacts-gcs-2-2

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-proxy-maistra-2.2-copy-artifacts-gcs-2-2

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-proxy-maistra-2.2-copy-artifacts-gcs-2-2

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-proxy-maistra-2.2-copy-artifacts-gcs-2-2

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-proxy-maistra-2.2-copy-artifacts-gcs-2-2

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-proxy-maistra-2.2-copy-artifacts-gcs-2-2

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-proxy-maistra-2.2-copy-artifacts-gcs-2-2

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-proxy-maistra-2.2-copy-artifacts-gcs-2-2

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-proxy-maistra-2.2-copy-artifacts-gcs-2-2

**Comment by yxun** [comment]
one of the proxy postsubmit job run before adding postsubmit: true back:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/38726/rehearse-38726-pull-ci-maistra-proxy-maistra-2.2-copy-artifacts-gcs-2-2/1653176023962882048

**Review by jwendell — APPROVED** [review]

**Pull request merged**
