### PR TITLE
loki: rework collector configuration

### PR DESCRIPTION
**Pull request by vrutkovs**
* Move some labels in json fields
* Remove duplicate collector sections

### CODE REVIEW

**Review by periklis — COMMENTED** [review]
LGTM

**Comment by vrutkovs** [comment]
Works fine now - https://grafana-loki.ci.openshift.org/explore?orgId=1&left=%5B%22now-6h%22,%22now%22,%22Grafana%20Cloud%22,%7B%22expr%22:%22%7Binvoker%3D%5C%22openshift-internal-ci%2Frehearse-17305-pull-ci-openshift-machine-api-operator-master-e2e-vsphere-upgrade%2F1377203323362349056%5C%22%7D%20%7C%20unpack%20%7C%20namespace%3D%5C%22openshift-machine-config-operator%5C%22%22%7D%5D

**Pull request merged**
