### PR TITLE
add gather-azure-cli in cucushift-installer-rehearse-azure-ipi-deprovision

### PR DESCRIPTION
**Pull request by MayXuQQ**
add  gather-azure-cli  to gather azure info with az cli when deprovision

### CODE REVIEW

**Comment by gpei** [comment]
Is there any useful logs that we have to get through this step?

**Comment by MayXuQQ** [comment]
> Is there any useful logs that we have to get through this step?

this step provide some info of the cluster with azure cli, has been used in developer's workflow, 
such as :
- az monitor metrics list 
- az vm boot-diagnostics get-boot-log

**Comment by gpei** [comment]
> * az monitor metrics list

To be honest, I have no idea how could this help us debugging installation failures, I checked one example log
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.13-e2e-azure-csi/1598422533990780928/artifacts/e2e-azure-csi/gather-azure-cli/artifacts/azure-monitor-metrics/lb-ci-op-1hkz6xqi-19730-m2s4v-SnatConnectionCount.json
it's all "null" result. 

> * az vm boot-diagnostics get-boot-log

If the installation failure is caused by VM boot error, we could get the instance system log from bootstrap gather, it's automatically gathered by installer during the installation.

**Comment by gpei** [comment]
In step `gather-azure-cli`, it's still downloading `jq` and `oc` inside the container which we're trying to get rid of, such action has been proved to be very unstable in our CI.

**Comment by MayXuQQ** [comment]
https://github.com/openshift/release/pull/34487#issuecomment-1334750784

**Pull request closed without merging**
