### PR TITLE
Add openshift-e2e-azure-ccm-ovn-hybrid workflows

### PR DESCRIPTION
**Pull request by Fedosin**
This PR adds two workflows:
* openshift-e2e-azure-ccm-ovn-hybrid
* openshift-e2e-azure-ccm-ovn-hybrid-install

They are required for testing of Windows containers with CCM support.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Is this based on some existing workflows for another platform?

**Comment by Fedosin** [comment]
@JoelSpeed Basically this is a combination of ovn-hybrid and ccm(-install) workflows. When they are combined we can test Windows Containers on Azure with CCM support.

**Comment by lobziik** [comment]
Can we add optional run of this workflow to CCCMO repo? At least we will see rehearse results there.

**Comment by Fedosin** [comment]
I don't think we need these jobs in CCCMO, as they are primarily for WMCO. But if it's really necessary, we can add them there as well.

**Comment by JoelSpeed** [comment]
This seems reasonable to me, we can follow up with future PRs to add tests that actually use this

/lgtm

**Pull request merged**
