### PR TITLE
Upgrade TrustyAI ocp to 4.13 from 4.12

### PR DESCRIPTION
**Pull request by RobGeada**
As an attempt to temporarily workaround the OCP issues seen recently

### CODE REVIEW

**Review by tteofili — APPROVED** [review]

**Review by ruivieira — APPROVED** [review]

**Comment by RobGeada** [comment]
/pj-rehearse pull-ci-trustyai-explainability-trustyai-explainability-main-trustyai-explainability-e2e auto-ack

**Comment by RobGeada** [comment]
/pj-rehearse pull-ci-trustyai-explainability-trustyai-explainability-main-trustyai-explainability-e2e

**Review by danielezonca — APPROVED** [review]
/lgtm

**Pull request merged**
