### PR TITLE
Add amd64 to multi-arch migration tests on nightly payloads

### PR DESCRIPTION
**Pull request by shellyyang1989**
Refers [MIXEDARCH-134](https://issues.redhat.com/browse/MIXEDARCH-134) [MIXEDARCH-167](https://issues.redhat.com/browse/MIXEDARCH-167)

### CODE REVIEW

**Comment by shellyyang1989** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-azure-ipi-baselinecaps-v413-to-multiarch-p2-f14

**Comment by shellyyang1989** [comment]
@aleskandro @liangxia @jianlinliu for review. Thanks!

**Comment by shellyyang1989** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-azure-ipi-baselinecaps-v413-to-multiarch-p2-f14

**Review by aleskandro — APPROVED** [review]
/lgtm

**Comment by shellyyang1989** [comment]
The migration gets stuck on console. Is it a bug?

```
oc get clusterversion
NAME      VERSION                              AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.13.0-0.nightly-2023-02-27-101545   True        True          114m    Unable to apply 4.13.0-ec.3: wait has exceeded 40 minutes for these operators: console
```

```
#####oc describe co console#####
Status:
  Conditions:
    Last Transition Time:  2023-03-01T04:07:41Z
    Message:               ThanosQuerierProxyServiceResolverSyncDegraded: customresourcedefinitions.apiextensions.k8s.io "managedproxyserviceresolvers.proxy.open-cluster-management.io" is forbidden: User "system:serviceaccount:openshift-console-operator:console-operator" cannot get resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
    Reason:                ThanosQuerierProxyServiceResolverSync_GetManagedProxyServiceResolverCRDFailed
    Status:                True
    Type:                  Degraded
```

**Pull request merged**
