### PR TITLE
Add missing fields for arm profiles

### PR DESCRIPTION
**Pull request by lwan-wanglin**
fix issue for ci failure https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-aws-ipi-disconnected-sts-efs-p3-f28-destructive/1670493555430264832

### CODE REVIEW

**Comment by lwan-wanglin** [comment]
periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-aws-ipi-disconnected-sts-efs-p3-f28-destructive

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-aws-ipi-disconnected-sts-efs-p3-f28-destructive

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-aws-ipi-disconnected-sts-ep-p3-f28-destructive

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-aws-ipi-ovn-hypershift-guest-p1-f14-destructive

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-aws-ipi-disconnected-sts-ep-p3-f28-destructive

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-aws-ipi-disconnected-sts-efs-p3-f28-destructive

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-aws-ipi-disconnected-sts-ep-p3-f28-destructive

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-aws-ipi-disconnected-sts-ep-p3-f28-destructive

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-aws-ipi-disconnected-sts-ep-p3-f28-destructive

**Comment by lwan-wanglin** [comment]
@aleskandro @LiangquanLi930 @yunjiang29 Could you help to review? thanks

- rehearse-40462-periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-aws-ipi-disconnected-sts-efs-p3-f28-destructive 
pass https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/40462/rehearse-40462-periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-aws-ipi-disconnected-sts-efs-p3-f28-destructive/1670998107980042240

- periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-aws-ipi-disconnected-sts-ep-p3-f28-destructive
failed becasue of this mco bug: https://issues.redhat.com/browse/OCPBUGS-12707

**Comment by LiangquanLi930** [comment]
Imok for HyperShift

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-aws-ipi-private-p3-f28-long-duration-cloud

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-aws-ipi-private-p2-f28-long-duration-apiserver

**Comment by lwan-wanglin** [comment]
@liangxia could you help review and merge it?thanks

**Comment by lwan-wanglin** [comment]
thanks @pruan-rht , only persons in [OWNERS list]([ci-operator/config/openshift/openshift-tests-private/OWNERS](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/openshift-tests-private/OWNERS)) can merge the PR.

**Pull request merged**
