### PR TITLE
MGMT-15343: bump golang 1.19 assisted service

### PR DESCRIPTION
**Pull request by eifrach**

### CODE REVIEW

**Comment by adriengentil** [comment]
`metal-assisted-day2-arm-workers` and `e2e-oci-assisted` are failing for unrelated reasons, I'll fix them with another PR.

**Review by adriengentil — APPROVED** [review]
should be ok if `e2e-ai-operator-ztp` passes

**Comment by eifrach** [comment]
rebase branch after fix #41631

**Review by adriengentil — APPROVED** [review]

**Review by osherdp — APPROVED** [review]

**Pull request merged**
