### PR TITLE
[CVP-3094] Create prow jobs & configs for OCP v4.12

### PR DESCRIPTION
**Pull request by asergienk**

### CODE REVIEW

**Comment by hongkailiu** [comment]
/override ci/prow/check-gh-automation

It is true that the github app is not installed.
The repo is special because it has no Prow configs
https://github.com/openshift/release/tree/master/core-services/prow/02_config/redhat-openshift-ecosystem
Otherwise, it would have been caught by periodic-check-gh-automation

We believe this is the edge case where github app is not needed.
If we do not want to override in the future, we could ignore the repo in the check
https://github.com/openshift/release/blob/6d33a9313da5d6e76ad5afbdcc06a30b382435ce/ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml#L26-L29

**Comment by samvarankashyap** [comment]
> /override ci/prow/check-gh-automation
> 
> It is true that the github app is not installed. The repo is special because it has no Prow configs https://github.com/openshift/release/tree/master/core-services/prow/02_config/redhat-openshift-ecosystem Otherwise, it would have been caught by periodic-check-gh-automation
> 
> We believe this is the edge case where github app is not needed. If we do not want to override in the future, we could ignore the repo in the check
> 
> https://github.com/openshift/release/blob/6d33a9313da5d6e76ad5afbdcc06a30b382435ce/ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml#L26-L29

I am sorry, I am could not understand the context of the comment.

**Pull request merged**
