### PR TITLE
move longduration-part3 gcp job back to amd ci

### PR DESCRIPTION
**Pull request by jianlinliu**
Since https://github.com/openshift/release/pull/44207, longduration-part3 gcp arm and amd jobs are merged, and migrated to multi-arch ci, per Hive team's feedback, hive never support arm arch, so move back the job to only amd ci.

### CODE REVIEW

**Comment by jianlinliu** [comment]
cc @jianping-shu to review.

**Comment by jianlinliu** [comment]
cc @liangxia to review.

**Comment by liangxia** [comment]
@jianlinliu There are conflicts. Could you rebase ?
```
Auto-merging ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml\nCONFLICT (content): Merge conflict in ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
```

**Comment by jianlinliu** [comment]
> @jianlinliu There are conflicts. Could you rebase ?
> 
> ```
> Auto-merging ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml\nCONFLICT (content): Merge conflict in ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
> ```

Thanks for checking, done.

**Pull request merged**
