### PR TITLE
Expand ocp 4.16 for z-stream on ibmcloud

### PR DESCRIPTION
**Pull request by smatula**

### CODE REVIEW

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.16-lp-interop-jaeger-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.15-lp-interop-jaeger-interop-ibmcloud

**Review by Simranpal — APPROVED** [review]
/lgtm

**Review by iblancasa — APPROVED** [review]

**Pull request merged**
