### PR TITLE
change image source name

### PR DESCRIPTION
**Pull request by rpancham**
Changed the SOURCE_IMAGE_REF path as the image build was failing

### CODE REVIEW

**Review by Xaenalt — APPROVED** [review]

**Comment by Xaenalt** [comment]
/pj-rehearse pull-ci-opendatahub-io-openvino_model_server-2023.1-release-pr-image-mirror

**Comment by Xaenalt** [comment]
/pj-rehearse branch-ci-opendatahub-io-openvino_model_server-2023.1-release-fast-image-mirror

**Comment by Xaenalt** [comment]
/pj-rehearse pull-ci-opendatahub-io-openvino_model_server-2023.1-release-pr-image-mirror
/pj-rehearse branch-ci-opendatahub-io-openvino_model_server-2023.1-release-fast-image-mirror

**Comment by Xaenalt** [comment]
/pj-rehearse pull-ci-opendatahub-io-openvino_model_server-v2023.1-release-fast-image-mirror

**Comment by rpancham** [comment]
/pj-rehearse pull-ci-opendatahub-io-openvino_model_server-v2023.1-release-fast-image-mirror

**Comment by Xaenalt** [comment]
/pj-rehearse pull-ci-opendatahub-io-openvino_model_server-2023.1-release-pr-image-mirror

**Pull request merged**
