### PR TITLE
Move ovn and placement prow jobs over from 4.14 to 4.15 Hive cluster

### PR DESCRIPTION
**Pull request by bshewale**

### CODE REVIEW

**Comment by lewisdenny** [comment]
#/pj-rehearse pull-ci-openstack-k8s-operators-placement-operator-main-placement-operator-build-deploy-kuttl pull-ci-openstack-k8s-operators-ovn-operator-main-ovn-operator-build-deploy-kuttl

**Comment by bshewale** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-placement-operator-main-placement-operator-build-deploy-kuttl pull-ci-openstack-k8s-operators-ovn-operator-main-ovn-operator-build-deploy-kuttl

**Comment by bshewale** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-placement-operator-main-placement-operator-build-deploy-kuttl pull-ci-openstack-k8s-operators-ovn-operator-main-ovn-operator-build-deploy-kuttl

**Comment by lewisdenny** [comment]
#/pj-rehearse pull-ci-openstack-k8s-operators-ovn-operator-main-ovn-operator-build-deploy-kuttl

**Comment by lewisdenny** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-ovn-operator-main-ovn-operator-build-deploy-kuttl

**Comment by lewisdenny** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-ovn-operator-main-ovn-operator-build-deploy-kuttl

**Comment by lewisdenny** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-ovn-operator-main-ovn-operator-build-deploy-kuttl

**Comment by lewisdenny** [comment]
Should pass now that [1] has merged

[1] https://github.com/openstack-k8s-operators/ovn-operator/pull/299

**Pull request merged**
