### PR TITLE
STOR-1856: build AWS EFS operator from csi-operator

### PR DESCRIPTION
**Pull request by RomanBednar**
Needs to be merged along with: https://github.com/openshift-eng/ocp-build-data/pull/4913

cc @openshift/storage

### CODE REVIEW

**Comment by RomanBednar** [comment]
/pj-rehearse pull-ci-openshift-csi-operator-master-aws-efs-operator-e2e

**Comment by RomanBednar** [comment]
/pj-rehearse pull-ci-openshift-csi-operator-master-aws-efs-operator-e2e

**Comment by gnufied** [comment]
/pj-rehearse pull-ci-openshift-csi-operator-release-4.16-aws-efs-operator-e2e

**Pull request merged**
