### PR TITLE
kubevirt: Move ssp-operator to gcp-virtualization

### PR DESCRIPTION
**Pull request by akrejcir**
Changed the `cluster_profile` to `gcp-virtualization`.

### CODE REVIEW

**Comment by akrejcir** [comment]
/pj-rehearse ci/rehearse/kubevirt/ssp-operator/master/e2e-single-node-functests

**Comment by akrejcir** [comment]
/pj-rehearse kubevirt/ssp-operator/master/e2e-single-node-functests

**Comment by akrejcir** [comment]
/pj-rehearse pull-ci-kubevirt-ssp-operator-master-e2e-single-node-functests

**Comment by akrejcir** [comment]
/pj-rehearse pull-ci-kubevirt-ssp-operator-release-v0.15-e2e-upgrade-functests

**Comment by 0xFelix** [comment]
@akrejcir Moving to `gcp-virtualization` in this case means moving ssp-operator to a different GCP account but not to a profile that uses nested virt capable nodes by default, right?

**Comment by akrejcir** [comment]
I'm not sure. @ksimon1 how can I find out if a gcp node is capable of nested virt?

**Comment by ksimon1** [comment]
Support for virtualization should be defined by ENV variable `COMPUTE_NODE_TYPE: n2-standard-4`. It is already part of the manifests, so the change of account, should not affect the virtualization support.

**Comment by 0xFelix** [comment]
As we now use a different profile, would it make sense to set this node type as the default for this profile? Is that possible?

**Comment by ksimon1** [comment]
I dont think we can do that, because this infrastructurre is shared across multiple project and we would affect them as well.
/lgtm

**Pull request merged**
