### PR TITLE
Revert "Merge pull request #6226 from tnozicka/force-vendoring"

### PR DESCRIPTION
**Pull request by stevekuznetsov**
This reverts commit 918d523283b8aaac04cb946894d084d4a1567a2d, reversing
changes made to d4ce9753a0892f96877451d1d1ee287ecf3998db.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@tnozicka @deads2k @mfojtik this broke downstream users _exactly_ as I warned in the original PR.

Please:

1. create an image that's a derivative of these bases and sets your flag
2. enforce that the repos you care about us it

**Comment by tnozicka** [comment]
@stevekuznetsov mind mentioning which ones?

**Comment by tnozicka** [comment]
if it was the supposed case of not using vendor folder, the expectation mentioned on the actual PR was for them to a) vendor as they should have b) use -mod=mod explicitly - not to revert the PR

**Comment by smarterclayton** [comment]
Note that all product code must use the vendor dir.  Tools and other things can avoid the cache, unless that code is required to ship stuff.

**Pull request merged**
