### PR TITLE
OCPQE-25063 drop sdn profile for cpou test

### PR DESCRIPTION
**Pull request by jiajliu**
Update sdn to ovn in 4.17 cpou test, more details in https://redhat-internal.slack.com/archives/CJ1J9C3V4/p1724731484054999

### CODE REVIEW

**Comment by jiajliu** [comment]
cc @zhaozhanqi @jianlinliu @shellyyang1989 PTAL, thanks

**Comment by shellyyang1989** [comment]
lgtm

**Comment by jiajliu** [comment]
cc @liangxia ptal, thanks

**Pull request merged**
