### PR TITLE
add periodic logging job

### PR DESCRIPTION
**Pull request by jcantrill**
Add periodic job to ensure claims remain viable

cc @cahartma @xperimental

### CODE REVIEW

**Comment by jcantrill** [comment]
/pj-rehearse periodic-ci-openshift-cluster-logging-operator-master-functional-periodic

**Comment by xperimental** [comment]
I think the issue with the stale clusters should be a non-issue once development restarts again. It might also make sense to reduce the number of "ready clusters" in the pool to the number needed by a single PR (maybe +1), so that they get cycled faster.

**Pull request closed without merging**
