### PR TITLE
cloud-team: do not take github reviews into consideration

### PR DESCRIPTION
**Pull request by paulfantom**
SSIA

/assign @petr-muller @stevekuznetsov 
/CC: @enxebre @frobware

### CODE REVIEW

**Comment by enxebre** [comment]
lgtm

**Comment by stevekuznetsov** [comment]
Are you guys explicitly doing this for all of the repos in that list? Sorry, I am not off-the-cuff knowledgeable of which repos you guys manage

**Comment by paulfantom** [comment]
That list is all repos we are managing

**Pull request merged**
