### PR TITLE
non-generated jobs: add flag --lease-server-username-file

### PR DESCRIPTION
**Pull request by hongkailiu**
https://issues.redhat.com/browse/DPTP-1913

/hold

require openshift/ci-tools#1676

```bash
$ find ./ci-operator/jobs  -type f -name "*.yaml"  -exec python3 migrate_non_prowgen_jobs.py {} \;
```

```python
#!/usr/bin/env python3

import logging
import yaml
import sys

filename = sys.argv[1]

def migrate(job):
    if job.get("agent", "") != "kubernetes" and job.get("agent", "") != "":
        logging.warning("the agent '%s' of job '%s' is not 'kubernetes'", job.get("agent", ""), job["name"])
        return job
    containers = []
    boskos = False
    for container in job['spec']['containers']:
        if container['image'].endswith("ci-operator:latest"):
            if 'args' not in container:
                logging.warning("no args for job %s", job["name"])
                containers.append(container)
                continue
            if container.get('command', []) != ["ci-operator"]:
                logging.warning("command not ci-operator in job %s", job["name"])
                containers.append(container)
                continue
            if "--lease-server-password-file=/etc/boskos/password" in container.get('args', []):
                boskos = True
                if "--lease-server-username=ci" in container.get('args', []):
                   container['args'].remove("--lease-server-username=ci")
                container['args'].append("--lease-server-username-file=/etc/boskos/username")
            if not "volumeMounts" in container:
                 container['volumeMounts'] = []
            if boskos:
                container['args'] = sorted(container['args'])
                container['volumeMounts'] = sorted(container['volumeMounts'], key=lambda vm: vm['name'])
        containers.append(container)
    job['spec']['containers'] = containers
    if boskos:
        if not "volumes" in job['spec']:
            job['spec']['volumes'] = []
        if {'name': 'boskos', 'secret': {'items': [{'key': 'password', 'path': 'password'}], 'secretName': 'boskos-credentials'}} in job['spec']['volumes']:
            job['spec']['volumes'].remove({'name': 'boskos', 'secret': {'items': [{'key': 'password', 'path': 'password'}], 'secretName': 'boskos-credentials'}})
        job['spec']['volumes'].append({'name': 'boskos', 'secret': {'items': [{'key': 'password', 'path': 'password'},{'key': 'username', 'path': 'username'}], 'secretName': 'boskos-credentials'}})
        job['spec']['volumes'] = sorted(job['spec']['volumes'], key=lambda v: v['name'])
    return job

with open(filename) as f:
    all = yaml.load(f, Loader=yaml.FullLoader)
    for t in ("presubmits", "postsubmits"):
        if t not in filename:
            continue
        for repo in all[t]:
            jobs = []
            for job in all[t][repo]:
                if not "labels" in job or not "ci-operator.openshift.io/prowgen-controlled" in job["labels"] or job["labels"]["ci-operator.openshift.io/prowgen-controlled"] != "true":
                    logging.info('job is not controlled by prowgen: %s', job["name"])
                    jobs.append(migrate(job))
                else:
                    jobs.append(job)
            all[t][repo] = jobs
    if "periodics" in filename:
        jobs = []
        for job in all["periodics"]:
            if not "labels" in job or not "ci-operator.openshift.io/prowgen-controlled" in job["labels"] or job["labels"]["ci-operator.openshift.io/prowgen-controlled"] != "true":
                logging.info('job is not controlled by prowgen: %s', job["name"])
                jobs.append(migrate(job))
            else:
                jobs.append(job)
        all["periodics"] = jobs

with open(sys.argv[1], 'w') as f:
    yaml.dump(all, f)
```

### CODE REVIEW

**Comment by petr-muller** [comment]
`container['args'] = sorted(container['args'])`

is is generally not safe to sort args, some args can be positional, think:

```
- --arg1
- value
- --arg2
```

**Comment by petr-muller** [comment]
^^^
/hold

**Comment by hongkailiu** [comment]
close by my mistake.

I will address https://github.com/openshift/release/pull/15679#issuecomment-776109902 in the new PR.

**Pull request closed without merging**
