### PR TITLE
Update Distributed Tracing jobs.

### PR DESCRIPTION
**Pull request by IshwarKanse**
This PR updates the Distributed Tracing jobs to sync with the upstream changes.

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-grafana-tempo-operator-main-tempo-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests

**Review by vprashar2929 — APPROVED** [review]
/lgtm

**Pull request merged**
