### PR TITLE
oadp:velero-datamover use repo dockerfile for unit-test

### PR DESCRIPTION
**Pull request by kaovilai**
Signed-off-by: Tiger Kaovilai <tkaovila@redhat.com>

blocked by https://github.com/openshift/oadp-operator/pull/1095

### CODE REVIEW

**Review by sseago — APPROVED** [review]

**Comment by kaovilai** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-velero-datamover-4.11-operator-unit-test
/pj-rehearse pull-ci-openshift-oadp-operator-velero-datamover-4.10-operator-unit-test

**Comment by kaovilai** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-velero-datamover-4.11-operator-unit-test pull-ci-openshift-oadp-operator-velero-datamover-4.10-operator-unit-test

**Comment by kaovilai** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-velero-datamover-4.11-operator-unit-test pull-ci-openshift-oadp-operator-velero-datamover-4.10-operator-unit-test

**Comment by kaovilai** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-velero-datamover-4.11-operator-unit-test pull-ci-openshift-oadp-operator-velero-datamover-4.10-operator-unit-test

**Pull request merged**
