### PR TITLE
Move router packet jobs to new equinix profile

### PR DESCRIPTION
**Pull request by ardaguclu**
The current packet account will soon be closed. This PR moves to new packet account, namely equinix-ocp-metal.

### CODE REVIEW

**Comment by ardaguclu** [comment]
@Miciah could you please take a look at this change?. Old cluster_profile will be removed soon and we are moving to new cluster_profile. Thanks.

**Comment by derekhiggins** [comment]
@rfredette would you be able to take a look please, the old account it due to close tomorrow

**Comment by Miciah** [comment]
@ardaguclu, there are still references to Packet in definitions under `ci-operator/jobs/openshift-priv/router/`; should this PR update these as well?

**Comment by ardaguclu** [comment]
> @ardaguclu, there are still references to Packet in definitions under `ci-operator/jobs/openshift-priv/router/`; should this PR update these as well?  

Thanks @Miciah As far as I know, priv ones are automatically updated after we merged this one. @andfasano could you please verify me?

**Comment by andfasano** [comment]
> > @ardaguclu, there are still references to Packet in definitions under `ci-operator/jobs/openshift-priv/router/`; should this PR update these as well?
> 
> Thanks @Miciah As far as I know, priv ones are automatically updated after we merge this one. @andfasano could you please verify me?

Yes, AFAIK (for more details, see https://docs.ci.openshift.org/docs/architecture/private-repositories/#openshift-priv-organization)

**Pull request merged**
