### PR TITLE
Adding gcp chaos prfoile

### PR DESCRIPTION
**Pull request by paigerube14**
Trying to update to use the new gcp-chaos profile

### CODE REVIEW

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-cloud-gcp-node-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-cloud-gcp-node-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-cloud-gcp-node-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-cloud-gcp-node-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-cloud-gcp-node-tests

**Comment by paigerube14** [comment]
@shahsahil264 @chaitanyaenr PTAL, this is only updating to use the new chaos gcp account/profile 

Passing run here: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/58183/rehearse-58183-periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-cloud-gcp-node-tests/1850881780446400512

**Review by chaitanyaenr — APPROVED** [review]
/lgtm

**Review by shahsahil264 — APPROVED** [review]
LGTM

**Pull request merged**
