### PR TITLE
opendatahub-io: Initial configuration for kubeflow repository

### PR DESCRIPTION
**Pull request by samuelvl**
Add https://github.com/opendatahub-io/kubeflow repository to Openshift CI

### CODE REVIEW

**Comment by samuelvl** [comment]
@droslean @hongkailiu The bot assigned you automatically, may you review this PR? I tried but I got `cannot trigger testing until a trusted user reviews the PR`.

**Comment by samuelvl** [comment]
Hey @jmguzik could you review this PR please? Thanks!

**Comment by samuelvl** [comment]
Hey @droslean @hongkailiu I assigned the PR to @jmguzik but I'm not sure if this is correct, thanks!

**Comment by droslean** [comment]
@samuelvl This is correct. @jmguzik is in DPTP team.

**Pull request merged**
