### PR TITLE
Move distributed-tracing-install-catalogsource as a common step to enable-stage-catalogsource.

### PR DESCRIPTION
**Pull request by IshwarKanse**
* Move distributed-tracing-install-catalogsource as a common step to enable-stage-catalogsource so that rest of the QE teams can use it for stage testing jobs.

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-distributed-tracing-qe-main-distributed-tracing-tests-dast

**Review by vprashar2929 — APPROVED** [review]
/lgtm

**Pull request merged**
