### PR TITLE
OpenStack: Add e2e-openstack to installer stable branches

### PR DESCRIPTION
**Pull request by mandre**
Copy e2e-openstack job definitions to installer stable branches.

### CODE REVIEW

**Comment by mandre** [comment]
All `e2e-openstack` jobs for the pj-rehearse job succeeded, but not all at the same time. We're experiencing capacity issue in the OpenStack CI cloud, and it would require more luck than I have today to have all 3 jobs green at the same time.

release-4.3/e2e-openstack was green previously in https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/6224/rehearse-6224-pull-ci-openshift-installer-release-4.3-e2e-openstack/5

**Comment by tomassedovic** [comment]
/lgtm
/test pj-rehearse

@mandre's explanation makes sense, the OpenStack our CI uses has been under capacity in the last couple of months causing frequent test failures due to VMs not coming up.

**Comment by jstuever** [comment]
/uncc @jstuever 
/cc @Fedosin 
Removing myself as already lgtm and I'm not an approver.

**Pull request merged**
