### PR TITLE
Removing TechPreview from day-0 multiarch compute jobs in 4.18

### PR DESCRIPTION
**Pull request by tvardema**

### CODE REVIEW

**Comment by jeffdyoung** [comment]
@tvardema should these test be named:
periodic-ci-openshift-multiarch-master-nightly-4.18-ocp-e2e-gcp-ovn-multi-day-0-x-ax
periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-gcp-ovn-multi-day-0-x-ax

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-gcp-ovn-multi-day-0-x-ax periodic-ci-openshift-multiarch-master-nightly-4.18-ocp-e2e-aws-ovn-multi-day-0-x-a periodic-ci-openshift-multiarch-master-nightly-4.18-ocp-e2e-gcp-ovn-multi-day-0-x-ax

**Comment by jeffdyoung** [comment]
> @tvardema should these test be named: periodic-ci-openshift-multiarch-master-nightly-4.18-ocp-e2e-gcp-ovn-multi-day-0-x-a periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-gcp-ovn-multi-day-0-x-a
> 
> instead of? periodic-ci-openshift-multiarch-master-nightly-4.18-ocp-e2e-gcp-ovn-multi-day-0-x-ax periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-gcp-ovn-multi-day-0-x-ax

@tvardema Lets have a follow up PR to rename the jobs and add them to the multi release controller?

**Pull request merged**
