### PR TITLE
assisted-installer: Use built assisted images on ocm-2.3 branch

### PR DESCRIPTION
**Pull request by lranjbar**
[MGMT-7140](https://issues.redhat.com/browse/MGMT-7140)

Signed-off-by: Lisa Rashidi-Ranjbar <lranjbar@redhat.com>

### CODE REVIEW

**Comment by omertuc** [comment]
```
could not resolve base image from openshift/ocm-2.3:assisted-installer: imagestreamtags.image.openshift.io \"ocm-2.3\" not found","time":"2021-07-02T20:21:22Z"}
```

I guess this is a catch 22 for this PR, it won't work until the PR gets merged and it starts promoting those images

**Review by YuviGold — APPROVED** [review]
LGTM

**Pull request merged**
