### PR TITLE
SPLAT-1715: migrate jobs to AWS account and edge-zones quota-slice

### PR DESCRIPTION
**Pull request by mtulio**
The `local-zones` profile was initially used in the development phase to support AWS Local Zones on installer on supported regions filtered in the quota-slice.

Currently the jobs have been moved to default AWS CI Account, we need to rename the quota slice to `edge-zones` (#55635 ) as for now it isn't testing only Local Zones, but also Wavelength Zone.

This change is moving the `manifest-validation` job, which only consumes API calls from AWS, to the default AWS account used by CI and other edge-zone jobs. The unused quota slice `aws-local-zones` is also removed, the `edge-zones` quota-slice is enforced to edge zone jobs.

This PR must be merged after https://github.com/openshift/release/pull/55635 to allow running rehearsal jobs here in new boskos config.

The unused profile will be removed at https://github.com/openshift/ci-tools/pull/4234

https://issues.redhat.com/browse/SPLAT-1715

### CODE REVIEW

**Comment by mtulio** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-aws-ovn-edge-zones

**Comment by mtulio** [comment]
blocking by https://github.com/openshift/release/pull/55635
/hold

**Comment by mtulio** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-ovn-edge-zones-manifest-validation

**Comment by mtulio** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.17-e2e-aws-ovn-edge-zones-manifest-validation

**Comment by mtulio** [comment]
converting to draft to troubleshoot the failure below as `RELEASE_IMAGE_LATEST` is not allowed to be override in workflow manifest.

~~~
INFO[2024-08-15T22:23:26Z] /bin/bash: line 12: RELEASE_IMAGE_LATEST: unbound variable
~~~

**Comment by mtulio** [comment]
retrying with fixes in `generated-config` job:

/pj-rehearse pull-ci-openshift-installer-release-4.17-e2e-aws-ovn-edge-zones-manifest-validation

**Comment by mtulio** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.17-e2e-aws-ovn-edge-zones-manifest-validation

**Comment by mtulio** [comment]
Changes:
- Making the manifest validation to skip when the Region is not opted-in in new AWS CI Account
- Disable BYO IP in the config generation to prevent failures when the region isn't supported as the jobs manifest-validation runs multi-region.


/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-ovn-edge-zones-manifest-validation

**Comment by mtulio** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-ovn-edge-zones-manifest-validation

**Comment by mtulio** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-ovn-edge-zones-manifest-validation

**Comment by mtulio** [comment]
> /pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-ovn-edge-zones-manifest-validation

The job [1824484395726147584][1824484395726147584] timed out while it is running the first time in the CI account, requiring to enable a few opted-out zones in regions non-tested currently by installs.

I am increasing the timeout to `20m`, but in the follow up executions which the zones is already enabled, it should take lower than 10m (check history][history] for more information)

/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-ovn-edge-zones-manifest-validation

[1824484395726147584]: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/54784/rehearse-54784-periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-ovn-edge-zones-manifest-validation/1824484395726147584
[history]: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-edge-zones-manifest-validation/1824212093541289984

**Comment by mtulio** [comment]
> > /pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-ovn-edge-zones-manifest-validation
> 
> The job [1824484395726147584](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/54784/rehearse-54784-periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-ovn-edge-zones-manifest-validation/1824484395726147584) timed out while it is running the first time in the CI account, requiring to enable a few opted-out zones in regions non-tested currently by installs.
> 
> I am increasing the timeout to `20m`, but in the follow up executions which the zones is already enabled, it should take lower than 10m [check history](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-edge-zones-manifest-validation/1824212093541289984) for more information)
> 
> /pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-ovn-edge-zones-manifest-validation

[Timed out again][1824495208629276672] close to the end of execution after enabling a lot of zone groups.

[1824495208629276672]: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/54784/rehearse-54784-periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-ovn-edge-zones-manifest-validation/1824495208629276672

Trying again:
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-ovn-edge-zones-manifest-validation

**Comment by mtulio** [comment]
manual rehearsal jobs are acceptable. Running auto-ack
/pj-rehearse auto-ack

**Comment by mtulio** [comment]
Retrying failed jobs caused by `Timed out waiting for image pull secrets in the test namespace. `
/pj-rehearse pull-ci-openshift-installer-master-e2e-aws-ovn-edge-zones

**Comment by mtulio** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-ovn-edge-zones

**Comment by mtulio** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-shared-vpc-localzones

**Comment by mtulio** [comment]
[periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-shared-vpc-localzones #1824519911565692928][1824519911565692928] failed caused bys a known issue documented in [OCPBUGS-31407][OCPBUGS-31407] as a limitation on schedule in taint nodes.

/pj-rehearse ack

[1824519911565692928]:https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/54784/rehearse-54784-periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-shared-vpc-localzones/1824519911565692928
[OCPBUGS-31407]: https://issues.redhat.com/browse/OCPBUGS-31407

**Review by r4f4 — COMMENTED** [review]
/approve

**Pull request merged**
