### PR TITLE
Always run single node live CD on cluster-bootstrap presubmit

### PR DESCRIPTION
**Pull request by omertuc**

### CODE REVIEW

**Comment by omertuc** [comment]
/hold 
Due to recent concerns about Packet resource waste

**Comment by romfreiman** [comment]
Was about to hold it myself

**Comment by romfreiman** [comment]
/hold
@omertuc do we really need it? How often does this repo change?

**Comment by omertuc** [comment]
> /hold
> @omertuc do we really need it? How often does this repo change?

IDK, you suggested it a month ago. What other repo do we want this in? etcd operator?

**Comment by romfreiman** [comment]
@omertuc I agree. At that point I didnt understand we have a limit on packet servers :)

**Comment by eranco74** [comment]
Didn't we just doubled the number of packet servers?
If this is such a concern we need to figure out a way to test this flow in cloud env.
We can't keep it without coverage.

**Pull request closed without merging**
