### PR TITLE
Add OCP 4.15 for NMO and FAR

### PR DESCRIPTION
**Pull request by razo7**
Testing NMO and FAR on OCP 4.15

### CODE REVIEW

**Review by clobrano — APPROVED** [review]
/lgtm

**Comment by razo7** [comment]
/pj-rehearse pull-ci-medik8s-fence-agents-remediation-main-4.15-openshift-e2e

**Comment by razo7** [comment]
/pj-rehearse pull-ci-medik8s-node-maintenance-operator-main-4.15-openshift-e2e

**Comment by razo7** [comment]
/pj-rehearse pull-ci-medik8s-node-maintenance-operator-main-4.15-openshift-e2e

**Pull request merged**
