### PR TITLE
bump apiVersion of PodSecurityPolicy to v1

### PR DESCRIPTION
**Pull request by hongkailiu**
https://issues.redhat.com/browse/DPTP-2989

### CODE REVIEW

**Comment by smg247** [comment]
/lgtm-cancel
lgtmed hastily:
```
error: unable to recognize \"clusters/build-clusters/01_cluster/loki/loki.yaml\": no matches for kind \"PodSecurityPolicy\" in version \"policy/v1\"\n"
```

**Comment by hongkailiu** [comment]
`PodSecurityPolicy` is removed.
https://kubernetes.io/docs/tasks/configure-pod-container/migrate-from-psp/

**Pull request closed without merging**
