### PR TITLE
Add 4.4 to 4.12 upgrade on AWS

### PR DESCRIPTION
**Pull request by shellyyang1989**
Refers [OCPQE-11543](https://issues.redhat.com/browse/OCPQE-11543)

### CODE REVIEW

**Comment by shellyyang1989** [comment]
@jhou1 @xingxingxia The 4.4 to 4.12 upgrade step got passed. But the job failed at gathering must-gather due to the security issue. Any suggestion is appreciated. Thanks! cc @jianlinliu 

```
Running must-gather...
Error from server (Forbidden): pods "must-gather-2972g" is forbidden: violates PodSecurity "restricted:latest": allowPrivilegeEscalation != false (containers "gather", "copy" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (containers "gather", "copy" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or containers "gather", "copy" must set securityContext.runAsNonRoot=true), seccompProfile (pod or containers "gather", "copy" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

**Comment by xingxingxia** [comment]
@shellyyang1989, OK I see the error messages in ci/rehearse/periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-4.12-upgrade-from-stable-4.4-aws-ipi's failure link. For the must-gather commands, need to ensure the oc used there includes the https://github.com/openshift/oc/pull/1099 code.

**Comment by shellyyang1989** [comment]
> @shellyyang1989, OK I see the error messages in ci/rehearse/periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-4.12-upgrade-from-stable-4.4-aws-ipi's failure link. For the must-gather commands, need to ensure the oc used there includes the [openshift/oc#1099](https://github.com/openshift/oc/pull/1099) code.

Thanks Xingxing. It seems like I'm using the 4.4 cli image. Let me update it.

**Comment by xingxingxia** [comment]
@shellyyang1989 , saw your error shown in last "ci/rehearse/periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-4.12-upgrade-from-stable-4.4-aws-ipi" failure link's build-log.txt:
```
[2022-10-26T10:18:17Z] Running step aws-ipi-cucushift-upgrade-toimage.
[2022-10-26T21:33:57Z] Logs for container test in pod aws-ipi-cucushift-upgrade-toimage:
[2022-10-26T21:33:57Z] Upgrade targets are registry.build03.ci.openshift.org/ci-op-5bcw3hcs/release@sha256:c67fe644d1c06e6d7694e648a40199cb06e25e1c3cfd5cd4fdac87fd696d2297 registry.build03.ci.openshift.org/ci-op-5bcw3hcs/release@sha256:ebe1db9c641da831e5efdaaddb895477d80e028f338c4724e03df89a5d0ca4cc ...snipped...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
...snipped...
Tools have not yet extracted at the server, please wait .
...snipped...
Tools have not yet extracted at the server, please wait .......................................................................................................................................
```
Then checked https://github.com/openshift/release/blob/master/ci-operator/step-registry/cucushift/upgrade/toimage/cucushift-upgrade-toimage-commands.sh , the related code sequence:
```
...
echo "Upgrade targets are ${TARGET_RELEASES[*]}"
...
for target in "${TARGET_RELEASES[@]}"
...
    TARGET_VERSION="$(oc adm release info "${TARGET}" --output=json | jq -r '.metadata.version')"
...
    local route="openshift-release-artifacts"
...
    url="${route}.apps.ci.l2s4.p1.openshiftapps.com"
...
    while curl -kLs https://${url}/${TARGET_VERSION} | grep -q "Extracting tools"
    do
        echo -ne "Tools have not yet extracted at the server, please wait ${progress}\r"
```
Then I tried:
```
$ curl -kLs https://openshift-release-artifacts.apps.ci.l2s4.p1.openshiftapps.com/4.5.41 | grep -q "Extracting tools"
$ echo $?
1

$ curl -kLs https://openshift-release-artifacts.apps.ci.l2s4.p1.openshiftapps.com/4.5.non-existent | grep -q "Extracting tools"
$ echo $?
0  <-- "true"
$ curl -kLs https://openshift-release-artifacts.apps.ci.l2s4.p1.openshiftapps.com/4.5.non-existent
<!DOCTYPE html> 
        <html>
            <head>
                <meta http-equiv="refresh" content="5">
            </head>
            <body>
                <p>Extracting tools for 4.5.non-existent, may take up to a minute ...</p>
            </body>
        </html>
```
The words "Extracting tools" occur when the ${TARGET_VERSION} is not existing, which is assigned via `TARGET_VERSION="$(oc adm release info "${TARGET}" --output=json | jq -r '.metadata.version')"`. From the log's output, the TARGET is registry.build03.ci.openshift.org/ci-op-5bcw3hcs/release@sha256:c67fe644d1c06e6d7694e648a40199cb06e25e1c3cfd5cd4fdac87fd696d2297, then I tried:
```
$ oc adm release info registry.build03.ci.openshift.org/ci-op-5bcw3hcs/release@sha256:c67fe644d1c06e6d7694e648a40199cb06e25e1c3cfd5cd4fdac87fd696d2297 registry.build03.ci.openshift.org/ci-op-5bcw3hcs/release@sha256:ebe1db9c641da831e5efdaaddb895477d80e028f338c4724e03df89a5d0ca4cc --output=json | jq -r '.metadata.version'
error: unable to read image registry.build03.ci.openshift.org/ci-op-5bcw3hcs/release@sha256:ebe1db9c641da831e5efdaaddb895477d80e028f338c4724e03df89a5d0ca4cc: Get "https://registry.build03.ci.openshift.org/v2/ci-op-5bcw3hcs/release/manifests/sha256:ebe1db9c641da831e5efdaaddb895477d80e028f338c4724e03df89a5d0ca4cc": unauthorized: authentication required
```
But the build-log.txt doesn't show this `authentication required` error. I want to know whether its output's version exists in https://openshift-release-artifacts.apps.ci.l2s4.p1.openshiftapps.com.

**Comment by shellyyang1989** [comment]
@xingxingxia I think it's caused by the temporary unavailability of https://openshift-release-artifacts.apps.ci.l2s4.p1.openshiftapps.com/4.5.41. Even I got the error this morning. But it works for now. I didn't see the error in the last run. I opened a [PR](https://github.com/openshift/release/pull/33510) to fail fast when the issue occurs.

**Comment by shellyyang1989** [comment]
The [test](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/33160/rehearse-33160-periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-4.12-upgrade-from-stable-4.4-aws-ipi/1585536694063468544) gets passed. It's ready for your review. Thanks! @jhou1 @liangxia @xingxingxia

**Pull request merged**
