### PR TITLE
sbo: add disable-openshift-4.14+ tag for 4.14 tests

### PR DESCRIPTION
**Pull request by sadlerap**

### CODE REVIEW

**Comment by sadlerap** [comment]
Retest this once https://github.com/redhat-developer/service-binding-operator/pull/1470 merges into `release-1.3.x`

**Comment by baijum** [comment]
/pj-rehearse periodic-ci-redhat-developer-service-binding-operator-release-v1.3.x-4.14-acceptance-lp-interop

**Pull request merged**
