### PR TITLE
[TRT-1160] Migrate the periodic vsphere upgrade job from 4.14 to 4.16

### PR DESCRIPTION
**Pull request by droslean**
/cc @DennisPeriquet 

follow-up of https://github.com/openshift/release/pull/50535 

Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

### CODE REVIEW

**Comment by droslean** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.16-e2e-vsphere-ovn-upgrade

**Comment by DennisPeriquet** [comment]
/lgtm
/hold

feel free to /hold cancel when ready

**Pull request merged**
