### PR TITLE
WIP test

### PR DESCRIPTION
**Pull request by bear-redhat**

### CODE REVIEW

**Comment by bear-redhat** [comment]
/pj-rehearse periodic-ci-opendatahub-io-ai-edge-main-test-ai-edge-periodic

**Comment by bear-redhat** [comment]
/pj-rehearse periodic-ci-opendatahub-io-ai-edge-main-test-ai-edge-periodic

**Comment by bear-redhat** [comment]
/pj-rehearse periodic-ci-opendatahub-io-ai-edge-main-test-ai-edge-periodic

**Comment by bear-redhat** [comment]
/pj-rehearse periodic-ci-opendatahub-io-ai-edge-main-test-ai-edge-periodic

**Comment by MarianMacik** [comment]
/pj-rehearse periodic-ci-opendatahub-io-ai-edge-main-test-ai-edge-periodic

**Comment by MarianMacik** [comment]
/pj-rehearse periodic-ci-opendatahub-io-ai-edge-main-test-ai-edge-periodic

**Comment by bear-redhat** [comment]
/pj-rehearse periodic-ci-opendatahub-io-ai-edge-main-test-ai-edge-periodic

**Comment by bear-redhat** [comment]
/pj-rehearse periodic-ci-opendatahub-io-ai-edge-main-test-ai-edge-periodic

**Comment by bear-redhat** [comment]
/pj-rehearse periodic-ci-opendatahub-io-ai-edge-main-test-ai-edge-periodic

**Comment by bear-redhat** [comment]
/pj-rehearse periodic-ci-opendatahub-io-ai-edge-main-test-ai-edge-periodic

**Comment by bear-redhat** [comment]
/pj-rehearse periodic-ci-opendatahub-io-ai-edge-main-test-ai-edge-periodic

**Comment by bear-redhat** [comment]
/pj-rehearse periodic-ci-opendatahub-io-ai-edge-main-test-ai-edge-periodic

**Comment by bear-redhat** [comment]
/pj-rehearse periodic-ci-opendatahub-io-ai-edge-main-test-ai-edge-periodic

**Pull request closed without merging**
