### PR TITLE
add oscp 4.18 osci configs for helm

### PR DESCRIPTION
**Pull request by amp-rh**

### CODE REVIEW

**Comment by amp-rh** [comment]
/pj-rehearse pull-ci-redhat-developer-helm-release-3.11-helm-ocp4.18-lp-interop-images

**Comment by vi-patel** [comment]
Can you update the cron value to `0 0 11 6 *`, and add a `FIREWATCH_DEFAULT_JIRA_ASSIGNEE` for the scenarios.

**Pull request merged**
