### PR TITLE
OLMv1: use shared commitchecker

### PR DESCRIPTION
**Pull request by ncdc**

### CODE REVIEW

**Comment by ncdc** [comment]
/pj-rehearse pull-ci-openshift-operator-framework-catalogd-main-verify-commits-shared
/pj-rehearse pull-ci-openshift-operator-framework-catalogd-main-verify-commits

**Comment by ncdc** [comment]
/pj-rehearse pull-ci-openshift-operator-framework-operator-controller-main-verify-commits-shared
/pj-rehearse pull-ci-openshift-operator-framework-catalogd-main-verify-commits-shared
/pj-rehearse pull-ci-openshift-operator-framework-rukpak-main-verify-commits-shared

**Review by stevekuznetsov — APPROVED** [review]

**Pull request merged**
