### PR TITLE
opendatahub-io: Update CI jobs to use Centos stream8 base images

### PR DESCRIPTION
**Pull request by LaVLaS**
Fixes CI tests failures related to the EOL of Centos

CI test error related to Centos EOL -- `Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist`

Signed-off-by: Landon LaSmith <LLaSmith@redhat.com>

### CODE REVIEW

**Review by crobby — APPROVED** [review]
/lgtm

**Review by anishasthana — APPROVED** [review]
/lgtm

**Review by anishasthana — COMMENTED** [review]
/lgtm

**Pull request merged**
