### PR TITLE
remove ovn-ex-gw-e2e step from metal-ipi-ovn-ipv4

### PR DESCRIPTION
**Pull request by jluhrsen**
Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>

### CODE REVIEW

**Comment by jluhrsen** [comment]
/hold
just using this to test for now

**Comment by jluhrsen** [comment]
https://issues.redhat.com/browse/SDN-3612

**Comment by derekhiggins** [comment]
/lgtm
thanks @jluhrsen

**Pull request merged**
