### PR TITLE
machine-os-images: add dev-scripts base image for e2e tests

### PR DESCRIPTION
**Pull request by andfasano**
Add image required to run baremetal workflows

### CODE REVIEW

**Comment by zaneb** [comment]
4.11 jobs failing with "could not lazily evaluate deferred parameter "RELEASE_IMAGE_LATEST": image stream "release" has no tag "latest" in spec or status".
I suspect this isn't actually a problem yet.

**Review by elfosardo — APPROVED** [review]

**Comment by andfasano** [comment]
> 4.11 jobs failing with "could not lazily evaluate deferred parameter "RELEASE_IMAGE_LATEST": image stream "release" has no tag "latest" in spec or status". I suspect this isn't actually a problem yet.

Yes thanks

**Pull request merged**
