### PR TITLE
vSphere: Remove ocp 4.5

### PR DESCRIPTION
**Pull request by jcpowermac**
Close to EOL and 4.5 is in permafailing since docker rate
limit was implemented. This won't be fixed for the 4.5
release no sense wasting our limited resources continuing
to test a release that will always fail.

### CODE REVIEW

**Comment by hasbro17** [comment]
@jcpowermac SGTM but needs a rebase.

**Comment by jcpowermac** [comment]
> @jcpowermac SGTM but needs a rebase.

@hasbro17 all set, thanks!

**Comment by jcpowermac** [comment]
@bradmwilliams can you take a look?

**Pull request merged**
