### PR TITLE
[INTEROP-7439] Expand GitOps to 1.13 for OCP CI 4.17.

### PR DESCRIPTION
**Pull request by dfrazzette**
Create ci/config for GitOps v1.13 release on OCP 4.17.

### CODE REVIEW

**Comment by dfrazzette** [comment]
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-v1.13-gitops-ocp4.17-lp-interop-redhat-openshift-gitops-interop-aws

**Comment by dfrazzette** [comment]
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-v1.13-gitops-ocp4.17-lp-interop-redhat-openshift-gitops-interop-aws

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
