### PR TITLE
Add 4.14 OCP SNR CI

### PR DESCRIPTION
**Pull request by mshitrit**
dependent on https://github.com/medik8s/self-node-remediation/pull/127

### CODE REVIEW

**Comment by slintes** [comment]
this PR doesn't look right, many unrelated modified or even new files 🤔

**Comment by mshitrit** [comment]
> this PR doesn't look right, many unrelated modified or even new files thinking

Good point, I think they snack in due to `make jobs`, I'll remove anything that's not related.

**Comment by slintes** [comment]
errors on the base prow jobs can mostly be fixed by rebasing and running make update again

**Pull request merged**
