### PR TITLE
Fix openshift-ansible scaleup keypair

### PR DESCRIPTION
**Pull request by mtnbikenc**

### CODE REVIEW

**Comment by mtnbikenc** [comment]
Added debug commit to force rehearsal of openshift-ansible.

/retitle [WIP] Fix openshift-ansible scaleup keypair

**Comment by petr-muller** [comment]
Hrm. More bugs.

**Comment by abhinavdahiya** [comment]
/lgtm

will allow @mtnbikenc to drop WIP and cancel hold
/hold

**Pull request merged**
