### PR TITLE
Adds egress-router-cni images to ci-operator

### PR DESCRIPTION
**Pull request by danielmellado**
This PR adds egress-router-cni images to ci-operator pipeline.

### CODE REVIEW

**Comment by danielmellado** [comment]
Pull-request updated, HEAD is now cdee8115d9939a5a7b1c7616e9139d54ee5776b7

**Comment by danielmellado** [comment]
Pull-request updated, HEAD is now 7c358418685c297aa4cb27a489ceefdd31769e6f

**Comment by danielmellado** [comment]
Pull-request updated, HEAD is now 546e8e75331fb4e84436a5d3bff3eeac1b467003

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
