### PR TITLE
Sync Serverless CI

### PR DESCRIPTION
**Pull request by creydr**
run 
```
make generate-eventing-ci
```

### CODE REVIEW

**Comment by creydr** [comment]
/pj-rehearse periodic-ci-openshift-knative-eventing-kafka-broker-release-v1.12-414-test-conformance-aws-ocp-414-continuous

**Comment by creydr** [comment]
/pj-rehearse periodic-ci-openshift-knative-eventing-release-v1.12-414-test-conformance-aws-ocp-414-continuous

**Comment by creydr** [comment]
/pj-rehearse periodic-ci-openshift-knative-eventing-istio-release-v1.12-414-e2e-tests-aws-ocp-414-continuous

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-istio-release-v1.10-411-e2e-tests-aws-ocp-411

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-istio-release-v1.12-411-e2e-tests-aws-ocp-411

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-istio-release-v1.9-410-e2e-tests-aws-ocp-410

**Comment by creydr** [comment]
/pj-rehearse periodic-ci-openshift-knative-eventing-hyperfoil-benchmark-main-414-test-kafka-8045b51-aws-ocp-414-continuous

**Comment by creydr** [comment]
/pj-rehearse periodic-ci-openshift-knative-eventing-istio-release-v1.12-414-e2e-tests-aws-ocp-414-continuous

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-release-v1.12-414-test-reconciler-aws-ocp-414

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-release-v1.12-414-images

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-release-v1.12-414-test-conformance-aws-ocp-414

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-release-v1.12-414-test-e2e-aws-ocp-414

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-release-v1.12-414-test-e2e-aws-ocp-414

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-release-v1.12-414-images

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-release-v1.12-414-test-conformance-aws-ocp-414

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-release-v1.12-414-test-e2e-aws-ocp-414

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-release-v1.12-414-test-reconciler-aws-ocp-414

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-kafka-broker-release-v1.12-414-images

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-kafka-broker-release-v1.12-414-test-conformance-aws-ocp-414

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-kafka-broker-release-v1.12-414-test-e2e-aws-ocp-414

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-kafka-broker-release-v1.12-414-test-reconciler-aws-ocp-414

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-release-v1.12-414-images

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-release-v1.12-414-test-conformance-aws-ocp-414

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-release-v1.12-414-test-e2e-aws-ocp-414

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-release-v1.12-414-test-reconciler-aws-ocp-414

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-kafka-broker-release-v1.12-414-images

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-kafka-broker-release-v1.12-414-test-conformance-aws-ocp-414

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-kafka-broker-release-v1.12-414-test-e2e-aws-ocp-414

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-kafka-broker-release-v1.12-414-test-reconciler-aws-ocp-414

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by matzew** [comment]
Let's make sure the mirroring job really works, after this is merged

**Comment by creydr** [comment]
> Let's make sure the mirroring job really works, after this is merged

@matzew how can I test/verify it? 
According to https://github.com/openshift/release/pull/46937#issuecomment-1864082393, the mirror job is not affected

> A full list of affected jobs can be found [here](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pj-rehearse/openshift/release/46937/92b5264b04e1e69d49d0c3c0fe8c5dc4ad79b87c)

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-kafka-broker-release-v1.12-414-test-e2e-aws-ocp-41

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-kafka-broker-release-v1.12-414-test-e2e-aws-ocp-411

**Pull request merged**
