### PR TITLE
HCO: image cleanup

### PR DESCRIPTION
**Pull request by nunnatsa**
After the test refactoring, remove unused images.

### CODE REVIEW

**Comment by nunnatsa** [comment]
pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-images pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-images pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-operator-sdk-aws

**Comment by nunnatsa** [comment]
pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-images pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-images pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-operator-sdk-aws

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-images pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-images pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-operator-sdk-aws

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
