### PR TITLE
add auto-assign config to apiserver repos for QE

### PR DESCRIPTION
**Pull request by wangke19**
Add auto-assign config to apiserver related repos, QE(allowed_users) will be assigned in PR after backport-risk-assessed labelled.
CC @xingxingxia , @gangwgr .

@sttts , please help to review/merge when you are free, thanks!

### CODE REVIEW

**Comment by xingxingxia** [comment]
/hold
I'd like to hold on before we finish discussion of new questions about `assign_on`'s elements in private qe lead channel.

**Comment by xingxingxia** [comment]
/unhold
Unholding per latest update from [DPTP-2612](https://issues.redhat.com/browse/DPTP-2612)

**Comment by wangke19** [comment]
@sttts @bparees Please help to review/merge when you are free. Thanks!

**Comment by wangke19** [comment]
@sttts @deads2k need approved label from you.

**Pull request merged**
