### PR TITLE
fix: wrong workflow for rhoai operator image mirror

### PR DESCRIPTION
**Pull request by zdtsw**
fix error : "could not run steps: step rhoai-operator-pr-image-mirror failed: "rhoai-operator-pr-image-mirror" pre steps failed: could not determine image pull spec for image rhods-operator on step opendatahub-io-ci-image-mirror 
[36mINFO[0m[2024-07-12T15:02:23Z] Reporting job state 'failed' with reason 'executing_graph:step_failed:executing_multi_stage_test'"

ref: https://issues.redhat.com/browse/RHOAIENG-8550

### CODE REVIEW

**Comment by zdtsw** [comment]
@VaishnaviHire  ^

**Comment by zdtsw** [comment]
/pj-rehearse pull-ci-red-hat-data-services-rhods-operator-main-rhoai-operator-pr-image-mirror

**Comment by VaishnaviHire** [comment]
I think we still have the issue

**Comment by zdtsw** [comment]
> I think we still have the issue

my very last try, or i gave up!

**Comment by zdtsw** [comment]
/pj-rehearse pull-ci-red-hat-data-services-rhods-operator-main-rhods-operator-pr-image-mirror

**Comment by zdtsw** [comment]
`pull-ci-red-hat-data-services-rhods-operator-main-rhoai-operator-pr-image-mirror` has been renamed to `pull-ci-red-hat-data-services-rhods-operator-main-rhods-operator-pr-image-mirror`
so we do not need to pj on it again

**Pull request merged**
