### PR TITLE
bumps golang version to 1.12 for master team's components

### PR DESCRIPTION
**Pull request by p0lyn0mial**

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
`ci-operator/config/openshift/cluster-kube-scheduler-operator/OWNERS` is missing

/assign @mfojtik for additional approval

**Comment by sttts** [comment]
We will change the Dockerfiles in independent follow-ups.

/hold cancel
/cancel hold

**Comment by p0lyn0mial** [comment]
> @p0lyn0mial - Should we switch all the components to go1.12 before this get merged?

yes, as a follow-up.

**Comment by p0lyn0mial** [comment]
`pull-ci-openshift-release-master-correctly-sharded-config` fails on:
```
[ERROR] This check enforces that configuration YAML files will be uploaded automatically
[ERROR] as they change. You are adding a file that is not covered by the automatic upload.
[ERROR] Contact an administrator to resolve this issue.
```

@stevekuznetsov could you help merge this pull :) ?

**Comment by gabemontero** [comment]
Not sure why rehearsal jobs were not run with this but now PRs against the cluster manager operator are failing with 

```
GOCACHE=off go test -v ./test/e2e/...
build cache is disabled by GOCACHE=off, but required as of Go 1.12
```

I'm seeing it with both a PR I have as well as running against the master branch of the operator against one of today's 4.2 ci cluster levels.

I'll submit a PR in the operator to try and address.

**Pull request merged**
