### PR TITLE
stolostron: search dco

### PR DESCRIPTION
**Pull request by mqhackett**
Related Issue: https://github.com/stolostron/backlog/issues/18042

Description:
 - Adds DCO check for search-indexer and search-v2-api

### CODE REVIEW

**Comment by jlpadilla** [comment]
/lgtm
@mqhackett We need to add the DCO file to the repos.

**Comment by mqhackett** [comment]
Looks like we need a CICD member for this one, because we are creating a new directory for DCO check config

**Review by schmidtd — APPROVED** [review]
/lgtm

**Pull request merged**
