### PR TITLE
AGENT-662: agent-installer-utils add e2e tests

### PR DESCRIPTION
**Pull request by andfasano**
This patch adds the sno/compact/ha agent jobs for the agent-installer-utils repo

### CODE REVIEW

**Comment by zaneb** [comment]
Would be good to use skip_if_only_changed to ignore docs/OWNERS file changes.
Is there a bot that syncs this to the release-4.14 and release-4.15 configs? If not we need to copy these same configs over so we don't lose them on release-4.14 once it branches off master.

**Comment by andfasano** [comment]
> Would be good to use skip_if_only_changed to ignore docs/OWNERS file changes. Is there a bot that syncs this to the release-4.14 and release-4.15 configs? If not we need to copy these same configs over so we don't lose them on release-4.14 once it branches off master.

Good point for skip, added it. I've checked about the config sync,  and from the [docs](https://docs.ci.openshift.org/docs/architecture/branching/#do-i-need-to-make-sure-branched-ci-operator-configs-are-up-to-date-for-release-branches) it seems it will happen for 4.15 but not for 4.14, so added also it

**Comment by andfasano** [comment]
> > Would be good to use skip_if_only_changed to ignore docs/OWNERS file changes. Is there a bot that syncs this to the release-4.14 and release-4.15 configs? If not we need to copy these same configs over so we don't lose them on release-4.14 once it branches off master.
> 
> Good point for skip, added it. I've checked about the config sync, and from the [docs](https://docs.ci.openshift.org/docs/architecture/branching/#do-i-need-to-make-sure-branched-ci-operator-configs-are-up-to-date-for-release-branches) it seems it will happen for 4.15 but not for 4.14, so added also it

From a double check with DPTP it seems that the promotion target of `main` (so `4.14`) and the release branches based on that (so `4.15`) will be kept in sync by the CI

**Review by rwsu — APPROVED** [review]

**Pull request merged**
