### PR TITLE
commatrix: update CI lanes

### PR DESCRIPTION
**Pull request by sabinaaledort**
1. Configure 4.16 and 4.17 CI lanes
2. Update main OCP version

### CODE REVIEW

**Comment by sabinaaledort** [comment]
/pj-rehearse pull-ci-openshift-kni-commatrix-4.16-commatrix-e2e-tests pull-ci-openshift-kni-commatrix-4.17-commatrix-e2e-tests pull-ci-openshift-kni-commatrix-main-commatrix-e2e-tests

**Comment by sabinaaledort** [comment]
/pj-rehearse pull-ci-openshift-kni-commatrix-4.16-commatrix-e2e-tests pull-ci-openshift-kni-commatrix-4.17-commatrix-e2e-tests pull-ci-openshift-kni-commatrix-main-commatrix-e2e-tests

**Comment by sabinaaledort** [comment]
/pj-rehearse pull-ci-openshift-kni-commatrix-release-4.16-commatrix-e2e-tests pull-ci-openshift-kni-commatrix-release-4.17-commatrix-e2e-tests pull-ci-openshift-kni-commatrix-main-commatrix-e2e-tests

**Comment by sabinaaledort** [comment]
/pj-rehearse pull-ci-openshift-kni-commatrix-release-4.16-commatrix-e2e-tests

**Comment by sabinaaledort** [comment]
/pj-rehearse pull-ci-openshift-kni-commatrix-main-commatrix-e2e-tests

**Comment by sabinaaledort** [comment]
/pj-rehearse pull-ci-openshift-kni-commatrix-release-4.16-commatrix-e2e-tests

**Review by aabughosh — COMMENTED** [review]
/approve

**Comment by sabinaaledort** [comment]
/pj-rehearse pull-ci-openshift-kni-commatrix-release-4.16-commatrix-e2e-tests

**Comment by sabinaaledort** [comment]
/pj-rehearse pull-ci-openshift-kni-commatrix-release-4.16-commatrix-e2e-tests

**Comment by sabinaaledort** [comment]
/pj-rehearse pull-ci-openshift-kni-commatrix-release-4.16-commatrix-e2e-tests pull-ci-openshift-kni-commatrix-release-4.17-commatrix-e2e-tests pull-ci-openshift-kni-commatrix-main-commatrix-e2e-tests pull-ci-openshift-kni-commatrix-release-4.18-commatrix-e2e-tests pull-ci-openshift-kni-commatrix-main-commatrix-e2e-tests

**Comment by sabinaaledort** [comment]
/pj-rehearse pull-ci-openshift-kni-commatrix-release-4.16-commatrix-e2e-tests

**Comment by sabinaaledort** [comment]
/pj-rehearse pull-ci-openshift-kni-commatrix-release-4.16-commatrix-e2e-tests

**Comment by sabinaaledort** [comment]
/pj-rehearse pull-ci-openshift-kni-commatrix-release-4.16-commatrix-e2e-tests

**Comment by sabinaaledort** [comment]
/pj-rehearse pull-ci-openshift-kni-commatrix-release-4.16-commatrix-e2e-tests

**Comment by sabinaaledort** [comment]
/pj-rehearse pull-ci-openshift-kni-commatrix-release-4.16-commatrix-e2e-tests

**Comment by sabinaaledort** [comment]
/pj-rehearse pull-ci-openshift-kni-commatrix-release-4.16-commatrix-e2e-tests

**Comment by sabinaaledort** [comment]
/pj-rehearse pull-ci-openshift-kni-commatrix-release-4.16-commatrix-e2e-tests

**Review by shirmoran — APPROVED** [review]

**Pull request merged**
