### PR TITLE
OCPBUGS-44199: Add test cases for aws tags

### PR DESCRIPTION
**Pull request by barbacbd**
** Add space to installer tests for tags (both the key and value)

### CODE REVIEW

**Comment by barbacbd** [comment]
Need to add numbers and special characters

**Comment by r4f4** [comment]
I see the tags in the capa output:
```
  additionaltags:
    clusterName: ci-op-ngiktnm6-c9d05
    expirationDate: 2024-11-19T01:55+00:00
    key2: value2
    keyA: valueA
    keyD: valueD spaces
    keySpecial: v@lu3-Special_.:/=+
    kubernetes.io/cluster/ci-op-ngiktnm6-c9d05-qlrcm: owned
```

/lgtm

**Pull request merged**
