### PR TITLE
Update kserve jobs

### PR DESCRIPTION
**Pull request by riprasad**
Add kserve 0.12.0 ci
Rename kserve 0.11 to 0.11.1
Update test platform openshift version to 4.15
switch to ipi-gcp workflow due to outage in hypershift clusters

### CODE REVIEW

**Comment by spolti** [comment]
This PR might need a rebase, or are the commits from @Jooho needed?

**Comment by riprasad** [comment]
This is not required anymore. This was a workaround to unblock CI for kserve due to openshift-ci hypershift outage

**Pull request closed without merging**
