### PR TITLE
Adds test for consecutive bundle upgrades

### PR DESCRIPTION
**Pull request by dharmit**
Should be merged after https://github.com/kubevirt/hyperconverged-cluster-operator/pull/2443.

### CODE REVIEW

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-azure

**Comment by dharmit** [comment]
Looks like infra error to me:
```
level=error msg=failed to fetch Cluster: failed to generate asset "Cluster": failure applying terraform for "cluster" stage: failed to create cluster: failed to apply Terraform: exit status 1 
```

/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-azure

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-azure

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-azure

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
Earlier failures were due to incorrect `BASE_DOMAIN`. After switching from Azure to AWS, I forgot to change the `BASE_DOMAIN` value.

/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

```
* could not run steps: step hco-e2e-upgrade-twice-operator-sdk-aws failed: ["hco-e2e-upgrade-twice-operator-sdk-aws" pre steps failed: "hco-e2e-upgrade-twice-operator-sdk-aws" pod "hco-e2e-upgrade-twice-operator-sdk-aws-ipi-conf-aws" failed: pod pending for more than 30m0s: containers have not started in 30m0.000479686s: sidecar, test: 
```

**Comment by dharmit** [comment]
Hard-coded `MAX_STEPS` to 30 since seeing below in the logs:

```
+ set +u
+ tar -C /tmp/secret -xzvf /tmp/secret/scc.tar.gz
scc/
scc/anyuid.yaml.before
scc/hostaccess.yaml.before
scc/hostmount-anyuid.yaml.before
scc/hostnetwork.yaml.before
scc/hostnetwork-v2.yaml.before
scc/machine-api-termination-handler.yaml.before
scc/node-exporter.yaml.before
scc/nonroot.yaml.before
scc/nonroot-v2.yaml.before
scc/privileged.yaml.before
scc/restricted.yaml.before
scc/restricted-v2.yaml.before
+ export OUTPUT_DIR=/tmp/secret
+ OUTPUT_DIR=/tmp/secret
++ grep -c 'Msg ' /bin/bash
+ MAX_STEPS=-2
```

/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
```
* could not run steps: step hco-e2e-upgrade-twice-operator-sdk-aws failed: ["hco-e2e-upgrade-twice-operator-sdk-aws" pre steps failed: "hco-e2e-upgrade-twice-operator-sdk-aws" pod "hco-e2e-upgrade-twice-operator-sdk-aws-openshift-cluster-bot-rbac" failed: pod pending for more than 30m0s: containers have not started in 30m0.000341382s: sidecar, test: 
```

/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
This moved further. But fails in the step to bring up the VM. Below excerpt from the [must-gather](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/41423/rehearse-41423-pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws/1694623494362370048/artifacts/hco-e2e-upgrade-twice-operator-sdk-aws/consecutive-upgrade-bundle/artifacts/kubevirt-must-gather/quay-io-kubevirt-must-gather-sha256-501e30ac7d5b9840a918bb9e5aa830686288ccfeee37d70aaf99cd2e302a2bb0/namespaces/vmsns/kubevirt.io/virtualmachines/custom/testvm.yaml):

```
status:
  conditions:
  - lastProbeTime: "2023-08-24T08:57:49Z"
    lastTransitionTime: "2023-08-24T08:57:49Z"
    message: Guest VM is not reported as running
    reason: GuestNotRunning
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-08-24T08:57:49Z"
    message: '0/6 nodes are available: 3 Insufficient devices.kubevirt.io/kvm, 3 node(s)
      had untolerated taint {node-role.kubernetes.io/master: }. preemption: 0/6 nodes
      are available: 3 No preemption victims found for incoming pod, 3 Preemption
      is not helpful for scheduling..'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  created: true
```

Triggering again to ensure it wasn't a flake.

/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
Failed again for the same reason as earlier:

```
status:
  conditions:
  - lastProbeTime: "2023-08-24T10:42:41Z"
    lastTransitionTime: "2023-08-24T10:42:41Z"
    message: Guest VM is not reported as running
    reason: GuestNotRunning
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-08-24T10:42:41Z"
    message: '0/6 nodes are available: 3 Insufficient devices.kubevirt.io/kvm, 3 node(s)
      had untolerated taint {node-role.kubernetes.io/master: }. preemption: 0/6 nodes
      are available: 3 No preemption victims found for incoming pod, 3 Preemption
      is not helpful for scheduling..'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  created: true
  desiredGeneration: 2
  observedGeneration: 2
  printableStatus: ErrorUnschedulable
  volumeSnapshotStatuses:
  - enabled: false
    name: containerdisk
    reason: Snapshot is not supported for this volumeSource type [containerdisk]
  - enabled: false
    name: cloudinitdisk
    reason: Snapshot is not supported for this volumeSource type [cloudinitdisk]
```

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
```
* 2023-09-21T07:49:07Z 1x kubelet: Pulling image "image-registry.openshift-image-registry.svc:5000/ci-op-0nt06fig/stable@sha256:65414ff5fac8b2680d327e4842dc054744a1e62c543a9b1f547c24b36b22070f" 
INFO[2023-09-21T08:19:04Z] Ran for 38m3s                                
ERRO[2023-09-21T08:19:04Z] Some steps failed:                           
ERRO[2023-09-21T08:19:04Z] 
  * could not run steps: step [release:latest] failed: release "release-latest" failed: pod pending for more than 30m0s: containers have not started in 30m0.000924483s: release, sidecar: 
* Container release is not ready with reason PodInitializing
* Container sidecar is not ready with reason PodInitializing 
```
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
Keep seeing this error so added a debug commit:
```
 + ./hack/retry.sh 30 10 'oc get vmi -n vmsns testvm -o jsonpath='\''{ .status.phase }'\'' | grep '\''Running'\'''
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
oc get vmi -n vmsns testvm -o jsonpath='{ .status.phase }' | grep 'Running'
> failed with exit code 1, waiting 10 seconds to retry...
+ cleanup
+ rv=1
+ '[' x1 '!=' x0 ']'
+ echo 'Error during upgrade: exit status: 1'
Error during upgrade: exit status: 1
+ make dump-state 
```

/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
```
 INFO[2023-09-25T07:47:35Z] Ran for 1h28m22s                             
ERRO[2023-09-25T07:47:35Z] Some steps failed:                           
ERRO[2023-09-25T07:47:35Z] 
  * could not run steps: step hco-e2e-upgrade-twice-operator-sdk-aws failed: "hco-e2e-upgrade-twice-operator-sdk-aws" test steps failed: "hco-e2e-upgrade-twice-operator-sdk-aws" pod "hco-e2e-upgrade-twice-operator-sdk-aws-deploy-cr" failed: pod pending for more than 30m0s: containers have not started in 30m0.000491046s: ci-scheduling-dns-wait, cp-entrypoint-wrapper, place-entrypoint, sidecar, test: 
* Container sidecar is not ready with reason PodInitializing
* Container test is not ready with reason PodInitializing 
```

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
```
STEP 1/15: FROM registry.access.redhat.com/ubi9/nginx-120
Trying to pull registry.access.redhat.com/ubi9/nginx-120:latest...
error: build error: creating build container: copying system image from manifest list: parsing image configuration: fetching blob: received unexpected HTTP status: 500 Internal Server Error
INFO[2023-09-25T10:34:15Z] Build bin succeeded after 3m7s
```

/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
```
 level=error msg=Error: creating EC2 VPC: VpcLimitExceeded: The maximum number of VPCs has been reached. 
```

/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-twice-operator-sdk-aws

**Comment by dharmit** [comment]
Closing in favour of #47114

/close

**Pull request closed without merging**
