### PR TITLE
cloud-provider-{azure,gcp} enables promotion for 4.15

### PR DESCRIPTION
**Pull request by theobarberbany**
Accidentally adding `disabled: true` in the promotion stanza has caused a bunch of downstream things that rely on the images from these jobs being in release to break. This should fix that, hopefully.

### CODE REVIEW

**Comment by theobarberbany** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-azure-release-4.15-images

**Comment by theobarberbany** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-gcp-release-4.15-images

**Review by hongkailiu — APPROVED** [review]

**Pull request merged**
