### PR TITLE
Enable e2e tests with CCM functionality for Azure platform

### PR DESCRIPTION
**Pull request by lobziik**
- e2e tests workflow
- install with enabled featuregate (optional)

Depends on https://github.com/openshift/machine-config-operator/pull/2669
Installation with feature gate also needed: https://github.com/openshift/machine-config-operator/pull/2668

### CODE REVIEW

**Review by Fedosin — COMMENTED** [review]
Looks good, but could we exclude mandre and mdbooth from owners. They are from OpenStack team and don't need access to Azure worflows.

**Review by elmiko — COMMENTED** [review]
agreed with @Fedosin , otherwise lgtm

**Review by elmiko — COMMENTED** [review]
/lgtm

**Review by Fedosin — COMMENTED** [review]
/lgtm

**Pull request merged**
