### PR TITLE
kata-containers: Re-enable tests fixed by updated webhook

### PR DESCRIPTION
**Pull request by ldoktor**
recently the kata-webhook got updated which fixed several e2e issues, re-enable the tests that are passing now.

### CODE REVIEW

**Comment by wainersm** [comment]
@ldoktor glad to hear that a simple update to the webhook made some tests magically work. Overall, do you know what was the problem with the webhook?

/lgtm

**Comment by ldoktor** [comment]
No changes, just rebased to re-trigger the infra-broken failures

**Comment by ldoktor** [comment]
@wainersm let's wait for https://github.com/kata-containers/tests/pull/5806 to be merged and verified (after the periodic job passes) then we can merge this.

**Pull request merged**
