### PR TITLE
Configure openstack-ironic repo

### PR DESCRIPTION
**Pull request by elfosardo**
Add ci jobs
Add repo to OCP lifecycle and automated branching

### CODE REVIEW

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-release-4.14-unit
/pj-rehearse pull-ci-openshift-openstack-ironic-release-4.14-pep8
/pj-rehearse pull-ci-openshift-openstack-ironic-release-4.15-pep8
/pj-rehearse pull-ci-openshift-openstack-ironic-release-4.15-unit

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-release-4.14-unit

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-release-4.14-pep8

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-release-4.15-unit

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-release-4.13-pep8

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-release-4.10-pep8

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-release-4.10-pep8

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-release-4.10-unit

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-release-4.9-unit
/pj-rehearse pull-ci-openshift-openstack-ironic-release-4.7-pep8
/pj-rehearse pull-ci-openshift-openstack-ironic-release-4.8-unit
/pj-rehearse pull-ci-openshift-openstack-ironic-release-4.9-pep8

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-release-4.9-unit

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-release-4.15-images

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-release-4.15-images

**Comment by elfosardo** [comment]
/pj-rehearse ack
good enough

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-release-4.7-pep8

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-release-4.15-images

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-release-4.15-images

**Comment by danilo-gemoli** [comment]
@elfosardo why do you claim `releases:` in every configurations if no tests use them?

**Comment by elfosardo** [comment]
> @elfosardo why do you claim `releases:` in every configurations if no tests use them?

@danilo-gemoli please explain why this is an issue. I'm a bit confused, I'm following guidelines from ci-operator documentation and various discussions, this is not the first configuration that we put in place, but it's the first time I get this comment. Thank you!

**Pull request merged**
