### PR TITLE
[image-registry] Rename dockerfile

### PR DESCRIPTION
**Pull request by ashwindasr**
For https://github.com/openshift/image-registry/pull/407

### CODE REVIEW

**Review by adambkaplan — APPROVED** [review]
/lgtm

Rehearsal jobs are expected to fail until the referenced image-registry PR merges.

**Comment by ashwindasr** [comment]
@adambkaplan I think the command is `/pj-rehearse ack`

**Comment by ashwindasr** [comment]
@adambkaplan looks like we need a space between `/pj-rehearse` and `ack`

**Comment by ashwindasr** [comment]
Also if you can take a look at https://github.com/openshift/image-registry/pull/407 and lgtm that as well, we can merge it in along with this one, if that works

**Pull request merged**
