### PR TITLE
Sync Serverless CI

### PR DESCRIPTION
**Pull request by serverless-qe**
Sync Serverless CI using openshift-knative/hack.

### CODE REVIEW

**Review by creydr — APPROVED** [review]
Just in time with the 1.14 branch creation :)

/lgtm

**Comment by pierDipi** [comment]
@creydr for EKB, I think https://github.com/openshift-knative/eventing-kafka-broker/commit/8d7915a6f8407d596749a3181b614076efad3c1c has been merged too late and the branch was created with the old modules included

**Comment by creydr** [comment]
We also don't have https://github.com/knative-extensions/eventing-kafka-broker/commit/b7b888054ae3aefcc47bd13676a05548a63de071 in upstream 1.14

**Comment by pierDipi** [comment]
@creydr I guess we can fix issues on the EKB and eventing-istio branch itself ? and merge this one?

**Comment by creydr** [comment]
> @creydr I guess we can fix issues on the EKB and eventing-istio branch itself ? and merge this one?

Agree :+1:

**Pull request merged**
