### PR TITLE
SPLAT-919: introduce additional jobs and expand lease pool

### PR DESCRIPTION
**Pull request by rvanderp3**
Introduces additional leases to the vSphere 8 lease pool as well as a CSI periodic.

### CODE REVIEW

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-vsphere-8-ovn-csi
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-vsphere-8-ovn-techpreview-serial

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-vsphere-8-ovn-csi

**Review by droslean — APPROVED** [review]

**Pull request merged**
