### PR TITLE
Adds stackrox 4.13-ppc64le job and change daily job to latest

### PR DESCRIPTION
**Pull request by mdafsanhossain**
Introduces changes to,

1. Adds a job target for ocp 4.13 stackrox ppc64le job
2. Changes default version to `LATEST` which targets the current latest `OCP` version.

### CODE REVIEW

**Comment by mdafsanhossain** [comment]
@gavin-stackrox Can you take a look?

**Comment by mdafsanhossain** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-powervs-4-13-qa-e2e-tests

**Comment by mdafsanhossain** [comment]
/pj-rehearse periodic-ci-stackrox-stackrox-master-daily-powervs-latest-ebpf-qa-e2e-tests

**Comment by mdafsanhossain** [comment]
/pj-rehearse periodic-ci-stackrox-stackrox-master-daily-powervs-latest-ebpf-qa-e2e-tests

**Comment by mdafsanhossain** [comment]
/pj-rehearse periodic-ci-stackrox-stackrox-master-daily-powervs-latest-ebpf-qa-e2e-tests

**Comment by mdafsanhossain** [comment]
/pj-rehearse periodic-ci-stackrox-stackrox-master-daily-powervs-latest-ebpf-qa-e2e-tests

**Comment by mdafsanhossain** [comment]
/pj-rehearse periodic-ci-stackrox-stackrox-master-daily-powervs-latest-ebpf-qa-e2e-tests

**Comment by mdafsanhossain** [comment]
/pj-rehearse periodic-ci-stackrox-stackrox-master-daily-powervs-latest-ebpf-qa-e2e-tests pull-ci-stackrox-stackrox-master-powervs-4-13-qa-e2e-tests

**Comment by mdafsanhossain** [comment]
@gavin-stackrox Jobs are running as expected. Can you `ack` it?

**Comment by gavin-stackrox** [comment]
@mdafsanhossain I guess it didn't like my /lgtm earlier: https://github.com/openshift/release/pull/46509#issuecomment-1845681558
Remember to `/uncc` when you open a PR here so that it does not add random reviewers.

**Comment by gavin-stackrox** [comment]
@mdafsanhossain you will need to ack the pj-rehearse (documented above)

**Comment by mdafsanhossain** [comment]
`lgtm` got removed because I rebased.

**Pull request merged**
