### PR TITLE
Update approvers and reviewers for verification-tests jobs

### PR DESCRIPTION
**Pull request by jhou1**
@liangxia @jianlinliu PTAL

### CODE REVIEW

**Comment by jianlinliu** [comment]
Also need to update ci-operator/jobs/openshift/verification-tests/OWNERS ?

**Comment by liangxia** [comment]
The owner file used here (and the file in folder jobs) is synced from verification-tests by the bot.
So you need to update in the verification-tests.

**Comment by liangxia** [comment]
If you update the `OWNERS` file in the original (e.g, `verification-tests`) repository, the openshift-bot will sync that to the `release` repo automatically every work day.
See how the bot works, https://github.com/openshift/release/pulls?q=is%3Apr+is%3Aclosed+author%3Aopenshift-bot+%22Sync+OWNERS%22

**Pull request closed without merging**
