### PR TITLE
noop

### PR DESCRIPTION
**Pull request by jim-minter**
@stevekuznetsov am I right in thinking prow didn't update itself after https://github.com/openshift/release/pull/2622 ?  What's the right way to kick it?

### CODE REVIEW

**Comment by jim-minter** [comment]
@mjudeikis @thekad fyi

**Comment by jim-minter** [comment]
also @kargakis

**Comment by jim-minter** [comment]
manually labelling lgtm

**Comment by thekad** [comment]
So, #2622 didn't go through, but this one did? did you do anything else @jim-minter ?

**Comment by stevekuznetsov** [comment]
This also looks like it never got updated. @jim-minter in the future please escalate config not auto-updating as an outage to DPTP team. If you don't see the bot comment on your PR, it did not update config.

**Comment by stevekuznetsov** [comment]
The root cause of this seems to be a GItHub failure to deliver webhooks

**Comment by kargakis** [comment]
> please escalate config not auto-updating as an outage to DPTP team

Trying to complete documenting CI for my team and I need to include this info - is it #forum-testplatform on slack or are there other channels as well we need to be aware of?

**Comment by stevekuznetsov** [comment]
That's the one

**Comment by thekad** [comment]
@stevekuznetsov this one seems to have gone through, we can see the previous changes reflected in the CI jobs now.

**Pull request merged**
