### PR TITLE
Add 1.6, 1.7 and 1.8 for net-kourier and net-istio

### PR DESCRIPTION
**Pull request by nak3**
As per title.

/cc @skonto @mgencur

### CODE REVIEW

**Comment by mgencur** [comment]
LGTM. My understanding is that you're not running any tests in pre-submit checks. This is only for building images in pre-submit and post-submit phase.

**Comment by nak3** [comment]
> LGTM. My understanding is that you're not running any tests in pre-submit checks. This is only for building images in pre-submit and post-submit phase.

Yes, that's correct. net-kourier and net-istio do not have the e2e test in their repo.

**Pull request merged**
