### PR TITLE
adds ci job for origin-4.4-kubernetes-1.17.0-rc.2

### PR DESCRIPTION
**Pull request by p0lyn0mial**

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
it wants a newer version of golang
```
Detected go version: go version go1.13.1 linux/amd64.
Kubernetes requires go1.13.4 or greater.
Please install go1.13.4 or later.
```

**Comment by tnozicka** [comment]
/approve
/lgtm

Rehearsals are expected to fail, since this is new repo/branch the failures will get fixed in the PR there.

Also we need to update Golang to 1.13.4

**Comment by p0lyn0mial** [comment]
requires https://github.com/openshift/release/pull/6297

**Pull request merged**
