### PR TITLE
WIP: ci-operator/templates/openshift/installer/cluster-launch-installer-e2e: Don't update OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE for mirrors

### PR DESCRIPTION
**Pull request by wking**
This is from 246118f38e (#4585), because there was some confusion about how the bootstrap machine would decide to pull from the mirror instead of the original.  But Clayton points out that that the `imageContentSources` must apply to the bootstrap machine as well, so we can use the original release pullspec and the bootstrap machine will still pull it from the mirror.

### CODE REVIEW

**Comment by umohnani8** [comment]
Any way to trigger the mirror job on this?

**Comment by wking** [comment]
> Any way to trigger the mirror job on this?

I've added faae65d75 to make it obvious to the rehearsal logic that the mirror tests are impacted, and now we're running [this][1].  We'll obviously want to drop that commit once we see the override-drop working as expected.

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/5567/rehearse-5567-release-openshift-ocp-installer-e2e-aws-mirrors-4.3/1

**Comment by wking** [comment]
Summarizing mirror failures so far:

* [1][]: `error: failed to commit blob sha256:2b80ca7f6f9a5637221a2a9bc17b71cb1a2fe51fe101614f55c034fbae39d25b from manifest sha256:3f57990bcca667bc26f6a37bdaca84d94f108834fd21da7aa28c707100245a7f to registry.svc.ci.openshift.org/ci-op-97rntt0y/release-scratch: blob upload unknown`, CI-registry flake, we [retry now](https://bugzilla.redhat.com/show_bug.cgi?id=1754042), but when CI is sufficiently sad that's still not enough.
* [2][]: `error: unable to push quay.io/openshift-release-dev/ocp-v4.0-art-dev: failed to upload blob sha256:...: received unexpected HTTP status: 500 Internal Server Error`, same boat as 1.
* [3][]: `error: unable to read image registry.svc.ci.openshift.org/ocp/release@sha256:...: unauthorized: authentication required`.  Dunno about this.
* [4][]: `error: unable to push quay.io/openshift-release-dev/ocp-v4.0-art-dev: failed to upload blob sha256:...: blob upload unknown`, same boat as 1.

/test pj-rehearse

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/5567/rehearse-5567-release-openshift-ocp-installer-e2e-aws-mirrors-4.3/1
[2]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/5567/rehearse-5567-release-openshift-ocp-installer-e2e-aws-mirrors-4.3/2
[3]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/5567/rehearse-5567-release-openshift-ocp-installer-e2e-aws-mirrors-4.3/3
[4]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/5567/rehearse-5567-release-openshift-ocp-installer-e2e-aws-mirrors-4.3/4

**Comment by wking** [comment]
`error: unable to push quay.io/openshift-release-dev/ocp-v4.0-art-dev: failed to upload blob sha256:...: unknown blob` [again][1].

/test pj-rehearse

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/5567/rehearse-5567-release-openshift-ocp-installer-e2e-aws-mirrors-4.3/5

**Comment by wking** [comment]
`error: unable to read image registry.svc.ci.openshift.org/ocp/release@sha256:97f4bd5b72c6d58df11583b1d685680e30809a1c6f7a3d0cc6f4cc1a72c8bbc8: unauthorized: authentication required` [again][1].  Maybe that's a real issue with the revised template...

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/5567/rehearse-5567-release-openshift-ocp-installer-e2e-aws-mirrors-4.3/6

**Comment by wking** [comment]
ok, `unable to read image` errors are coming out of the `test` container, so probably [here][1].  I'll drop some debugging in around there and see if we can get more details.

[1]: https://github.com/openshift/release/blob/805e5d6988d8776da810904c07f7e06dbbcf7774/ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml#L253

**Comment by wking** [comment]
Pushed 76564ada8 -> 19b12c46c adding `-a "${PULL_SECRET_PATH}"` to hopefully [avoid][1]:

```
FIXME: getting image pullspecs
error: unable to read image registry.svc.ci.openshift.org/ocp/release@sha256:77dbb7cb39bc69e5de65bf50a87942de6a98bc4dc2a2d0a9d539db004a36d964: unauthorized: authentication required
```

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/5567/rehearse-5567-release-openshift-ocp-installer-e2e-aws-mirrors-4.3/11

**Comment by umohnani8** [comment]
this can be closed. Don't need to change anything in the ci.

**Pull request closed without merging**
