### PR TITLE
Adding knative-eventing_0.18.4_ci

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

as per title

### CODE REVIEW

**Comment by mgencur** [comment]
/lgtm
/hold

Holding just for the rehearse to finish. Please unhold if you're satisfied with that.

**Comment by matzew** [comment]
/unhold

```
level=fatal msg="failed to initialize the cluster: Cluster operator openshift-controller-manager is still updating"
2020/11/04 14:17:04 Container setup in pod e2e-aws-ocp-46 failed, exit code 1, reason Error
2020/11/04 14:31:30 Copied 153.54MB of artifacts from e2e-aws-ocp-46 to /logs/artifacts/e2e-aws-ocp-46
2020/11/04 14:31:31 Releasing leases for "e2e-aws-ocp-46"
2020/11/04 14:31:31 Releasing lease "cc65a053-4fa0-451e-9969-164180476bbf" for "aws-quota-slice"
2020/11/04 14:31:31 No custom metadata found and prow metadata already exists. Not updating the metadata.
2020/11/04 14:31:31 Ran for 1h44m5s
error: some steps failed:
  * could not run steps: step e2e-aws-ocp-46 failed: template pod "e2e-aws-ocp-46" failed: the pod ci-op-5mb381cx/e2e-aws-ocp-46 failed after 1h14m38s (failed containers: setup): ContainerFailed one or more containers exited
Container setup exited with code 1, reason Error
---
msg="Waiting up to 20m0s for the Kubernetes API at https://api.ci-op-5mb381cx-97a79.origin-ci-int-aws.dev.rhcloud.com:6443..."
skipped 5 lines unfold_more
Trace[1623147797]: [15.20726854s] [15.20726854s] Objects listed
E1104 13:44:23.773614      38 reflector.go:307] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ClusterVersion: Get "https://api.ci-op-5mb381cx-97a79.origin-ci-int-aws.dev.rhcloud.com:6443/apis/config.openshift.io/v1/clusterversions?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dversion&resourceVersion=22849&timeoutSeconds=487&watch=true": dial tcp 52.40.165.212:6443: connect: connection refused
E1104 13:46:21.403873      38 reflector.go:307] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ClusterVersion: Get "https://api.ci-op-5mb381cx-97a79.origin-ci-int-aws.dev.rhcloud.com:6443/apis/config.openshift.io/v1/clusterversions?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dversion&resourceVersion=23790&timeoutSeconds=364&watch=true": dial tcp 52.40.165.212:6443: connect: connection refused
level=info msg="Cluster operator insights Disabled is False with AsExpected: "
level=info msg="Cluster operator openshift-controller-manager Progressing is True with _DesiredStateNotYetAchieved: Progressing: daemonset/controller-manager: updated number scheduled is 2, desired number scheduled is 3"
level=fatal msg="failed to initialize the cluster: Cluster operator openshift-controller-manager is still updating"
---
```

**Pull request merged**
