### PR TITLE
Split Dex manifests up

### PR DESCRIPTION
**Pull request by danilo-gemoli**
I have to unmarshal a `Deployment` but a multi-objects yaml file like the following:
```yaml
kind: Namespace
---
kind: ServiceAccount
---
kind: Deployment
---
```
makes the code unnecessarily complex.
I will rather change the yaml rather than writing mumbo jumbo Go code.

### CODE REVIEW

**Review by droslean — APPROVED** [review]
you could put them in a List as well....

**Comment by danilo-gemoli** [comment]
There may be no need anymore to merge this

**Comment by danilo-gemoli** [comment]
/close
not needed anymore

**Pull request closed without merging**
