### PR TITLE
Add QE's e2e to testgrid

### PR DESCRIPTION
**Pull request by liangxia**
Add QE's e2e to testgrid for informing

### CODE REVIEW

**Comment by petr-muller** [comment]
This does not simply add a job to testgrid (the `core-services/testgrid-config-generator/_allow-list.yaml` change alone does that), but it also adds the job as informing to release controller, which AFAIK allows only `openshift/release` jobs to be added.

If you only need the job in testgrid, leave out the release-controller config change.

At this point in time, I would also expect the 4.10 job to exist.

**Comment by liangxia** [comment]
> This does not simply add a job to testgrid (the `core-services/testgrid-config-generator/_allow-list.yaml` change alone does that), but it also adds the job as informing to release controller, which AFAIK allows only `openshift/release` jobs to be added.
> 
> If you only need the job in testgrid, leave out the release-controller config change.
> 
> At this point in time, I would also expect the 4.10 job to exist.

@petr-muller Thank you for the info.
Our goal is get those jobs add into testgrid and release controller as informing.
But for now, let's just get it into testgrid.

We are still working on the 4.10 jobs. We will add them in a separate PR when it's ready.

**Pull request merged**
