### PR TITLE
NO-ISSUE: backup terraform folder

### PR DESCRIPTION
**Pull request by eifrach**

### CODE REVIEW

**Comment by eifrach** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-master-edge-e2e-metal-assisted-single-node

**Comment by eifrach** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-master-edge-e2e-metal-assisted-single-node

**Comment by eifrach** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-master-edge-e2e-metal-assisted-single-node

**Comment by deepsm007** [comment]
/pj-rehearse pull-ci-openshift-assisted-image-service-release-ocm-2.6-e2e-metal-assisted-deploy-nodes

**Comment by eifrach** [comment]
/pj-rehearse pull-ci-openshift-assisted-image-service-main-edge-e2e-metal-assisted

**Comment by eifrach** [comment]
/pj-rehearse pull-ci-openshift-assisted-image-service-release-ocm-2.6-e2e-metal-assisted
/pj-rehearse pull-ci-openshift-assisted-image-service-main-edge-e2e-metal-assisted-deploy-nodes
/pj-rehearse pull-ci-openshift-assisted-image-service-main-edge-e2e-metal-assisted-external

**Comment by eifrach** [comment]
/pj-rehearse pull-ci-openshift-assisted-image-service-main-edge-e2e-metal-assisted-deploy-nodes

**Pull request merged**
