### PR TITLE
ocs-operator: Use index image

### PR DESCRIPTION
**Pull request by nbalacha**
Signed-off-by: N Balachandran <nibalach@redhat.com>

### CODE REVIEW

**Comment by BlaineEXE** [comment]
From @nbalacha 's email:

> I looked at the OCP ci failures for OCS last week and I think I have made some progress. 
> 
> Current state:
> ci/prow/red-hat-storage-ocs-ci-e2e-aws fails consistently because it is trying to deploy OCS using the registry instead of the index image.
> 
> 2021-11-29 04:57:40.961902 I | Deploying ocs image quay.io/ocs-dev/ocs-registry:latest
panic: timed out waiting for the condition: waiting on deployment ocs-operator to be created
>
>This PR updates the catalog source to use the index image. It is able to deploy OCS but fails when trying to update /etc/passwd for the ocs ci user.
>This is because OCS no longer uses openshift-ci/Dockerfile.tools as the image build root. The Dockerfile provides permissions to change the /etc/passwd file.
>
> I didn't look further as I did not know why the build root was changed. I've set up a short meeting today to discuss this.

Good job catching the need for the dependency to be added. :+1:

It's very possible that some of my changes were what caused us to no longer use `openshift-ci/Dockerfile.tools`. I was working with Jose to bring our use of OpenShift CI into a better state where we have fewer individual files to maintain (more reuse) and to follow the latest examples and guidelines from OpenShift CI maintainers. 

Given our efforts to "modernize" our use of openshift CI, I am wondering why we need the ability to update `/etc/passwd` in CI. What is changing that, and why? Is that really needed in CI and not in production? If so, how hard is it to remove the need for access to `/etc/passwd`?

**Comment by nbalacha** [comment]
> Given our efforts to "modernize" our use of openshift CI, I am wondering why we need the ability to update `/etc/passwd` in CI. What is changing that, and why? Is that really needed in CI and not in production? If so, how hard is it to remove the need for access to `/etc/passwd`?

I am waiting to hear back from the OCS CI QE team. The comment in hack/red-hat-storage-ocs-ci-tests.sh states that:

# Openshift CI runs this test within a pod with a randomized uid
# ocs-ci expects this randomized user to exist in the /etc/passwd file
# so we need to dynamically create an entry for the user

**Comment by nbalacha** [comment]
The OCS CI team is unaware of this requirement. Maybe this is no longer required.

I propose that we merge this PR and I will then send a PR to remove the /etc/passwd changes done in the ocs-operator script. Lets see if the ocs-ci run succeeds without the passwd changes.

**Review by jarrpa — APPROVED** [review]
/lgtm

**Review by BlaineEXE — APPROVED** [review]

**Pull request merged**
