### PR TITLE
Interop - Add RHSSO scenario on ROSA classic

### PR DESCRIPTION
**Pull request by oharan2**

### CODE REVIEW

**Comment by oharan2** [comment]
/pj-rehearse pull-ci-rhbk-sso-test-main-rhsso-product-ocp4.16-lp-rosa-classic-images

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-rhbk-sso-test-main-rhsso-product-ocp4.16-lp-rosa-classic-rhsso-interop-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-rhbk-sso-test-main-rhsso-product-ocp4.16-lp-rosa-classic-rhsso-interop-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-rhbk-sso-test-main-rhsso-product-ocp4.16-lp-rosa-classic-rhsso-interop-aws

**Comment by oharan2** [comment]
/pj-rehearse pull-ci-rhbk-sso-test-fix_KCCR-rhsso-product-ocp4.16-lp-rosa-classic-images

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-rhbk-sso-test-fix_KCCR-rhsso-product-ocp4.16-lp-rosa-classic-rhsso-interop-aws

**Review by ikhomyn — APPROVED** [review]
Hi @oharan2, /lgtm

**Pull request merged**
