### PR TITLE
[insights-runtime-extractor] unit test

### PR DESCRIPTION
**Pull request by jmesnil**
add tests to run unit tests from the source repository

### CODE REVIEW

**Comment by tremes** [comment]
/pj-rehearse pull-ci-openshift-insights-runtime-extractor-main-unit-tests

**Comment by jmesnil** [comment]
/pj-rehearse pull-ci-openshift-insights-runtime-extractor-main-unit-tests

**Comment by jmesnil** [comment]
/pj-rehearse pull-ci-openshift-insights-runtime-extractor-main-rust-unit-tests

**Comment by jmesnil** [comment]
/pj-rehearse pull-ci-openshift-insights-runtime-extractor-main-rust-unit-tests

**Comment by jmesnil** [comment]
/pj-rehearse pull-ci-openshift-insights-runtime-extractor-main-rust-unit-tests

**Comment by jmesnil** [comment]
/pj-rehearse pull-ci-openshift-insights-runtime-extractor-main-rust-unit-tests

**Comment by jmesnil** [comment]
/pj-rehearse pull-ci-openshift-insights-runtime-extractor-main-rust-unit-tests

**Comment by jmesnil** [comment]
/pj-rehearse pull-ci-openshift-insights-runtime-extractor-main-unit-tests

**Comment by jmesnil** [comment]
/pj-rehearse pull-ci-openshift-insights-runtime-extractor-main-rust-unit-tests

**Comment by jmesnil** [comment]
/pj-rehearse pull-ci-openshift-insights-runtime-extractor-main-rust-unit-tests

**Comment by jmesnil** [comment]
/pj-rehearse pull-ci-openshift-insights-runtime-extractor-main-rust-unit-tests

**Comment by jmesnil** [comment]
/pj-rehearse pull-ci-openshift-insights-runtime-extractor-main-rust-unit-tests

**Comment by jmesnil** [comment]
/pj-rehearse pull-ci-openshift-insights-runtime-extractor-main-rust-unit-tests

**Comment by jmesnil** [comment]
/pj-rehearse pull-ci-openshift-insights-runtime-extractor-main-rust-unit-tests

**Comment by jmesnil** [comment]
/pj-rehearse pull-ci-openshift-insights-runtime-extractor-main-rust-unit-tests

**Comment by jmesnil** [comment]
/pj-rehearse pull-ci-openshift-insights-runtime-extractor-main-rust-unit-tests

**Comment by jmesnil** [comment]
pull-ci-openshift-insights-runtime-extractor-main-rust-unit-tests

**Comment by jmesnil** [comment]
/pj-rehearse pull-ci-openshift-insights-runtime-extractor-main-rust-unit-tests

**Comment by jmesnil** [comment]
/pj-rehearse pull-ci-openshift-insights-runtime-extractor-main-rust-unit-tests

**Comment by jmesnil** [comment]
/pj-rehearse pull-ci-openshift-insights-runtime-extractor-main-rust-unit-tests

**Comment by jmesnil** [comment]
/pj-rehearse pull-ci-openshift-insights-runtime-extractor-main-rust-unit-tests

**Comment by jmesnil** [comment]
/pj-rehearse pull-ci-openshift-insights-runtime-extractor-release-4.18-images

**Comment by jmesnil** [comment]
@tremes Could you please review and add a /lgtm? The jobs will now run unit tests for Go and Rust against the `main`, `release-4.18` &`release-4.19` branches of https://github.com/openshift/insights-runtime-extractor

**Pull request merged**
