### PR TITLE
[WIP] no-op to run hypershift upgrade

### PR DESCRIPTION
**Pull request by ricky-rav**

### CODE REVIEW

**Comment by ricky-rav** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-4.14-upgrade-from-stable-4.13-aws-ipi-ovn-hypershift-replace-f7

**Comment by ricky-rav** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-release-4.14-4.14-upgrade-from-stable-4.13-aws-ipi-ovn-hypershift-replace-f7

**Comment by ricky-rav** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-4.14-upgrade-from-stable-4.13-aws-ipi-ovn-hypershift-replace-f7

**Comment by ricky-rav** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-4.14-upgrade-from-stable-4.13-aws-ipi-ovn-hypershift-replace-f7

**Comment by flavio-fernandes** [comment]
Nice! TY for doing this, Ricky.

**Pull request closed without merging**
