### PR TITLE
openshift/os: Explicitly promote into ocp/4.12 imagestream

### PR DESCRIPTION
**Pull request by cgwalters**
Followup to https://github.com/openshift/os/issues/940

We changed the image name, but to succeed in landing the MCO changes
to use `rhel-coreos-8` we need an image named `rhel-coreos-8` in
the integration imagestream.

Closes: https://github.com/openshift/os/issues/943

### CODE REVIEW

**Review by jmarrero — APPROVED** [review]
lgtm

**Comment by yuqi-zhang** [comment]
/assign @jupierce

Since this does touch image-mirroring, it appears we need an owner from there to also take a look.

For context, this is changing how we ship base OS images in alignment with the CoreOS Layering enhancement. The original (machine-os-content) will still be shipped for compatibility, but we need 2 additional images (rhel coreos 8 and extensions) for the new layered container image os format.

**Comment by yuqi-zhang** [comment]
/assign @bparees 

is this something you can help us with? Sorry for the multi-pings. This is blocking the MCO team and the layering initiative. For more context please see the above message (and https://github.com/openshift/machine-config-operator/pull/3258#issuecomment-1205328567 )

**Pull request merged**
