### PR TITLE
vSphere:move misc jobs to vsphere-2 cluster profile

### PR DESCRIPTION
**Pull request by jcpowermac**

### CODE REVIEW

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-redhat-openshift-ecosystem-provider-certification-tool-main-4.13-platform-none-vsphere periodic-ci-redhat-openshift-ecosystem-provider-certification-tool-main-4.13-platform-external-vsphere

**Comment by jcpowermac** [comment]
/assign pierdipi jcrossley3

Can you please approve this PR. All vSphere jobs are being moved to a new build cluster in IBM. These are the last jobs to move.

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-redhat-openshift-ecosystem-provider-certification-tool-main-4.13-platform-external-vsphere

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
