### PR TITLE
Added e2e-metal-assisted-capi

### PR DESCRIPTION
**Pull request by eranco74**

### CODE REVIEW

**Comment by osherdp** [comment]
@eranco74 do ``make update`` for it to generate the new job

**Comment by eranco74** [comment]
Trying with hypershift image built with this:
https://github.com/openshift/hypershift/pull/771
/test pj-rehearse

**Comment by eranco74** [comment]
Waiting for inventory api to be ready 
/test pj-rehearse

**Comment by eranco74** [comment]
assisted-test-infra [issue](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/24329/rehearse-24329-pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-capi/1471067028461719552/artifacts/e2e-metal-assisted-capi/baremetalds-assisted-setup/build-log.txt)
/test pj-rehearse

**Comment by eranco74** [comment]
/test pj-rehearse

! StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: IP not available after waiting: machine minikube didn't return IP after 1 minute

**Comment by eranco74** [comment]
`�[31mERROR: file or directory not found: ./discovery-infra/tests/test_kube_api.py`
The tests moved to a different directory...

**Comment by osherdp** [comment]
@eranco74 you can use the new makefile target that @eliorerz created

**Comment by eranco74** [comment]
> @eranco74 you can use the new makefile target that @eliorerz created

@eliorerz what makefile target is that?

**Comment by eranco74** [comment]
minikube issue
/test pj-rehearse

**Comment by eranco74** [comment]
/test pj-rehearse
:crossed_fingers:

**Comment by eranco74** [comment]
minikube issue...
/test pj-rehearse

**Comment by osherdp** [comment]
@eranco74 @avishayt did the rehearse job eventually passed?

**Pull request merged**
