### PR TITLE
modify step name in firewatch config

### PR DESCRIPTION
**Pull request by rujutashinde**

### CODE REVIEW

**Comment by rujutashinde** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhoai-addon-interop-v4.14-GA-production-smoke-rosa-rhoai-addon-baseline-fips

**Comment by rujutashinde** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhoai-addon-interop-v4.14-GA-production-smoke-osd-aws-rhoai-addon-baseline-fips

**Review by rnetser — APPROVED** [review]

**Pull request merged**
