### PR TITLE
Add kn-cli-artifacts image

### PR DESCRIPTION
**Pull request by navidshaikh**
- Genereate cross platform binaries in binary_builds_commands
 - ADD the required files for packaging cli artifacts tar gzs and zip
 - Update image mirroring config to sync the image to quay

### CODE REVIEW

**Comment by petr-muller** [comment]
@navidshaikh I can confirm this change is not expected to cause differently-generated jobs (slack followup)

**Comment by navidshaikh** [comment]
@rhuss: This is ready to go in. 
(We might have to change this in future based on how signing shapes up, but we can do that in subsequent PR, lets get this in for testing ;-)).

**Pull request merged**
