### PR TITLE
MGMT-15555: ignore monitoring for conformance tests

### PR DESCRIPTION
**Pull request by osherdp**
As a temporary workaround, this ignores only the case of monitoring failures during conformance tests (regular test failures from the test suite should still fail the job).

For example, [this job](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-ipxe-periodic/1690589089230753792) fails for:
```
[2023-08-13 03:19:23] error running options: failed due to a MonitorTest failureerror: failed due to a MonitorTest failure 
```

and the logs before that indicate that we have some kind of problem accessing routes defined in the ingress mechanism:
```
[2023-08-13 06:16:20] time="2023-08-13T06:16:20Z" level=error msg="disruption sample failed: Get \"https://test-disruption-t64j2-openshift-image-registry.apps.test-infra-cluster-1e9f685a.redhat.com/healthz\": EOF" auditID=a5777263-d102-4015-a8f2-a6c4e2a8b03d backend=image-registry type=new 
```

### CODE REVIEW

**Comment by osherdp** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted

**Comment by osherdp** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted

**Comment by osherdp** [comment]
/pj-rehearse periodic-ci-openshift-assisted-service-master-edge-e2e-metal-assisted-periodic

**Comment by osherdp** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-periodic

**Review by eliorerz — APPROVED** [review]
LGTM

**Pull request merged**
