### PR TITLE
ACM-10217 Update branch forwarding for stolostron/console

### PR DESCRIPTION
**Pull request by KevinFCormier**
https://issues.redhat.com/browse/ACM-10217
- Fix up node version and forwarding in `release-2.11` and `backplane-2.6` branches
- Switch forwarding in `main` from `release-2.10` to `release-2.11`

### CODE REVIEW

**Comment by Randy424** [comment]
@KevinFCormier are these tests expected to fail?

**Comment by KevinFCormier** [comment]
@Randy424 I don't think it's a new issue, because our Sonar post-submits have been failing for awhile:
https://prow.ci.openshift.org/?repo=stolostron%2Fconsole

**Pull request merged**
