### PR TITLE
Add 4.12 hetero to 4.13 hetero upgrade job

### PR DESCRIPTION
**Pull request by shellyyang1989**
Refers to [MIXEDARCH-133](https://issues.redhat.com/browse/MIXEDARCH-133)

### CODE REVIEW

**Comment by shellyyang1989** [comment]
The upgrade step passed.
INFO[2022-12-23T06:57:58Z] Step aws-ipi-p2-f14-cucushift-upgrade-toimage succeeded after 1h18m30s. 

cc @aleskandro @jianlinliu @liangxia @jhou1 for review. 
cc @LiangquanLi930 @YuLi517 @evakhoni for comments.

**Review by aleskandro — APPROVED** [review]
/lgtm

**Comment by aleskandro** [comment]
Refers MIXEDARCH-133

**Pull request merged**
