### PR TITLE
Configure ironic-image jobs for OCP 4.15

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Comment by elfosardo** [comment]
repositories need to be populated

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-release-4.15-prevalidation-images

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-release-4.15-prevalidation-images

**Comment by iurygregory** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-release-4.15-prevalidation-images

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-master-e2e-metal-ipi-virtualmedia

**Pull request merged**
