### PR TITLE
MCE-disconnected: avoid hardcoding oc-mirror image

### PR DESCRIPTION
**Pull request by tiraboschi**
Get oc-mirror from stable clients instead of hardcoding an image digest in the test scripts.

### CODE REVIEW

**Comment by tiraboschi** [comment]
@LiangquanLi930 FYI

**Comment by tiraboschi** [comment]
@LiangquanLi930 FYI

**Comment by LiangquanLi930** [comment]
> @LiangquanLi930 FYI

@tiraboschi Hi, I do not recommend making this adjustment because there are certain differences between different versions for oc-mirror. There are some distinctions in flags, which would increase the maintenance cost for us.

**Comment by tiraboschi** [comment]
> > @LiangquanLi930 FYI
> 
> @tiraboschi Hi, I do not recommend making this adjustment because there are certain differences between different versions for oc-mirror. There are some distinctions in flags, which would increase the maintenance cost for us.

Do you mean per ocp minor releases?
What about using https://mirror2.openshift.com/pub/openshift-v4/clients/ocp/candidate-4.14/oc-mirror.tar.gz , https://mirror2.openshift.com/pub/openshift-v4/clients/ocp/candidate-4.15/oc-mirror.tar.gz ... instead of https://mirror2.openshift.com/pub/openshift-v4/clients/ocp/candidate/oc-mirror.tar.gz ?

**Comment by LiangquanLi930** [comment]
> Do you mean per ocp minor releases?
> What about using https://mirror2.openshift.com/pub/openshift-v4/clients/ocp/candidate-4.14/oc-mirror.tar.gz , https://mirror2.openshift.com/pub/openshift-v4/clients/ocp/candidate-4.15/oc-mirror.tar.gz ... instead of https://mirror2.openshift.com/pub/openshift-v4/clients/ocp/candidate/oc-mirror.tar.gz ?

yep, There are certain differences between y versions

**Comment by tiraboschi** [comment]
> > Do you mean per ocp minor releases?
> > What about using https://mirror2.openshift.com/pub/openshift-v4/clients/ocp/candidate-4.14/oc-mirror.tar.gz , https://mirror2.openshift.com/pub/openshift-v4/clients/ocp/candidate-4.15/oc-mirror.tar.gz ... instead of https://mirror2.openshift.com/pub/openshift-v4/clients/ocp/candidate/oc-mirror.tar.gz ?
> 
> yep, There are certain differences between y versions

OK, so on the other side pointing to https://mirror2.openshift.com/pub/openshift-v4/clients/ocp/candidate/oc-mirror.tar.gz skipping the `-4.Y` suffix will implicitly ensure that we will take the same version of all the branches without the need to hardcode a specific digest in the script.

**Comment by tiraboschi** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-agent-ovn-mce-disconnected-dualstack-conformance

**Comment by tiraboschi** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-agent-ovn-mce-disconnected-ipv6-conformance

**Pull request merged**
