### PR TITLE
Config IPv4=no for e2e-metal-assisted-ipv6 to avoid running dual-stack

### PR DESCRIPTION
**Pull request by YuviGold**
Matches https://github.com/openshift/assisted-test-infra/pull/1112

/cc @eliorerz 
/cc @osherdp 
/cc @mkowalski

### CODE REVIEW

**Comment by YuviGold** [comment]
Most of ipv6 jobs passed. No need to verify why specific jobs failed since it's not related to the change.

**Review by osherdp — APPROVED** [review]

**Comment by YuviGold** [comment]
/cc @stbenjam 
some changes on the nighltlies jobs

**Review by osherdp — APPROVED** [review]

**Pull request merged**
