### PR TITLE
Use new tagging format for Serving source image

### PR DESCRIPTION
**Pull request by ReToCode**
Fixes JIRA [SRVKS-1011](https://issues.redhat.com/browse/SRVKS-1011)

## Proposed Changes
- Use new tagging format for Serving source image

/cc @nak3 , @skonto , @mgencur

### CODE REVIEW

**Comment by ReToCode** [comment]
Now we have a dead-lock as this PR also depends on https://github.com/openshift-knative/serverless-operator/pull/2046.

```
Pulling image registry.ci.openshift.org/openshift/knative-v1.8.0:knative-serving-src ...
```

@nak3 , @skonto , @mgencur mind reviewing this with failed builds?

**Comment by nak3** [comment]
/lgtm
/approve

CI needs to fix https://github.com/openshift-knative/serverless-operator/pull/2046#discussion_r1166502298 but 2046 needs this PR :face_with_spiral_eyes:

**Pull request merged**
