### PR TITLE
[oVirt] Port presubmit jobs to workflows - csi workflow only

### PR DESCRIPTION
**Pull request by Gal-Zaidman**

### CODE REVIEW

**Comment by jsafrane** [comment]
@Gal-Zaidman do you want to include csi-snapshot-controller-operator repo too? Just in case we break snapshot-controller deployment. https://github.com/openshift/release/tree/master/ci-operator/jobs/openshift/cluster-csi-snapshot-controller-operator

**Comment by Gal-Zaidman** [comment]
> @Gal-Zaidman do you want to include csi-snapshot-controller-operator repo too? Just in case we break snapshot-controller deployment. https://github.com/openshift/release/tree/master/ci-operator/jobs/openshift/cluster-csi-snapshot-controller-operator

Well I only changed what we had, I didn't remove any jobs or added any....
I also thought to my self why do we have jobs on the snapshot because I thought that we don't support it on ovirt... but assumed that you, roy and benny wanted a job on that repo for a reason, and we can always remove it later if required :)

This PR focuses on the port

**Comment by rgolangh** [comment]
@jsafrane @Gal-Zaidman ovirt doesn't have resize and snapshot support yet, so this would be a waste and and a burden on those repo's. Unless ovirt e2e are defined not mandatory and doesn't run automatically.

**Comment by Gal-Zaidman** [comment]
> @jsafrane @Gal-Zaidman ovirt doesn't have resize and snapshot support yet, so this would be a waste and and a burden on those repo's. Unless ovirt e2e are defined not mandatory and doesn't run automatically.

@rgolangh updated to run_always false, that means that the job will run only if triggered manually.

Also added a release 4.6 workflow as a preparation, currently it is identical to the regular workflow, I'll update the content on a separate PR.
Just thought its best to update the job here then ping you and jan again

**Comment by jsafrane** [comment]
/assign @bennyz @rgolangh 
for approval

**Pull request merged**
