### PR TITLE
add config for application-ui and console-api

### PR DESCRIPTION
**Pull request by chenz4027**
https://github.com/open-cluster-management/backlog/issues/9525

Signed-off-by: Maggie Chen @chenz4027

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/label tide/merge-method-squash

Ping me once this is not WIP anymore for approval.
/uncc

**Comment by chenz4027** [comment]
@alvaroaleman This PR is no longer WIP and is ready for approval

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
