### PR TITLE
Test MCO on OCP 4.16

### PR DESCRIPTION
**Pull request by douglascamata**
This applies to ACM 2.10, 2.11, and 2.12.

### CODE REVIEW

**Review by saswatamcode — APPROVED** [review]

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-main-test-e2e pull-ci-stolostron-multicluster-observability-operator-release-2.12-test-e2e pull-ci-stolostron-multicluster-observability-operator-release-2.11-test-e2e

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-main-test-e2e pull-ci-stolostron-multicluster-observability-operator-release-2.11-test-e2e

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-main-test-e2e

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-main-test-e2e

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-main-test-e2e

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-main-test-e2e

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-release-2.11-test-e2e

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-main-test-e2e

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-main-test-e2e

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-main-test-e2e

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-release-2.11-test-e2e

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-release-2.11-test-e2e

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-main-test-e2

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-release-2.12-test-e2e

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-release-2.12-test-e2e

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-release-2.11-test-e2e

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-release-2.11-test-e2e

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-release-2.10-test-e2e

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-release-2.11-test-e2e

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-release-2.12-test-e2e

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-release-2.11-test-e2

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-release-2.11-test-e2e

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-release-2.10-test-e2e

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-release-2.10-test-e2e

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-release-2.10-test-e2e

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-release-2.10-test-e2e

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-release-2.10-test-e2e

**Comment by douglascamata** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-release-2.10-test-e2e

**Review by saswatamcode — APPROVED** [review]
/lgtm

**Pull request merged**
