### PR TITLE
OCPCLOUD-2627 - adding 10 e2e cases for pre-submit tests(capi-aws)

### PR DESCRIPTION
**Pull request by miyadav**
Adding tests to pre-submit capi-aws-provider repo , for testing rebases.

### CODE REVIEW

**Comment by miyadav** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-aws-master-regression-clusterinfra-aws-ipi-proxy-techpreview

**Comment by miyadav** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-aws-master-regression-clusterinfra-aws-ipi-proxy-techpreview

**Comment by JoelSpeed** [comment]
@miyadav Can you please link the source to these test cases? As per the other comment I left, JUnit would be nice to have if possible with the tooling you have

**Comment by miyadav** [comment]
@JoelSpeed here is the [source](https://github.com/openshift/openshift-tests-private/tree/master/test/extended/clusterinfrastructure)

**Comment by miyadav** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-aws-master-regression-clusterinfra-aws-ipi-proxy-techpreview

**Comment by miyadav** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-aws-master-regression-clusterinfra-aws-ipi-proxy-techpreview

**Comment by miyadav** [comment]
had to rebase due to conflict @JoelSpeed @damdo can you help to merge it , we could use it to test rebase on 4.17 ..

**Pull request merged**
