### PR TITLE
Update CI test command for cluster ingress and dns operators

### PR DESCRIPTION
**Pull request by pravisankar**
- Now it will also verifies gofmt and generated bindata mismatches

### CODE REVIEW

**Comment by pravisankar** [comment]
@ironcladlou PTAL

**Comment by pravisankar** [comment]
@ironcladlou Followed the steps in the https://docs.google.com/document/d/1SQ_qlkcplqhe8h6ONXdgBr7YUVbs4oRSj4ISl3gpLW4 doc and it did not generate any new changes to prow jobs. 
If I delete existing openshift-cluster-{dns,ingress}-operator-{presubmits,postsubmits}.yaml files, it is generating these files again but it has only subset of the existing changes. I think the current custom presubmit and postsubmit yaml files are good for dns/ingress operator and I don't think we need any more changes.

**Comment by ironcladlou** [comment]
Thanks
/lgtm

**Pull request merged**
