### PR TITLE
Use diff cluster pools for checking out hub and managed clusters during e2e tests

### PR DESCRIPTION
**Pull request by coleenquadros**
Testing out changed from this PR - https://github.com/openshift/release/pull/51057

### CODE REVIEW

**Comment by coleenquadros** [comment]
pj-rehearse pull-ci-stolostron-multicluster-observability-operator-release-2.11-test-e2e

**Comment by coleenquadros** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-main-test-e2e

**Comment by coleenquadros** [comment]
Verified on the test cluster
```
cluster-claims  clusterpool-list  hub-1.json  hub-1.kc  managed-1.json  managed-1.kc
sh-4.4$ cat managed-1.json 
{
  "username": "kubeadmin",
  "password": "4MYzS-kpkzc-9DmBw-PPmyE",
  "basedomain": "dev07.red-chesterfield.comsno-415-wbdz5.dev07.red-chesterfield.com",
  "api_url": "https://api.sno-415-wbdz5.dev07.red-chesterfield.com:6443",
  "console_url": "https://console-openshift-console.apps.sno-415-wbdz5.dev07.red-chesterfield.com"
}
sh-4.4$ cat hub-1.json 
{
  "username": "kubeadmin",
  "password": "xxmnv-cddjN-zj5Er-zzitg",
  "basedomain": "dev07.red-chesterfield.comsno-4xlarge-415-7j5s4.dev07.red-chesterfield.com",
  "api_url": "https://api.sno-4xlarge-415-7j5s4.dev07.red-chesterfield.com:6443",
  "console_url": "https://console-openshift-console.apps.sno-4xlarge-415-7j5s4.dev07.red-chesterfield.com"
}
sh-4.4$ 

```

**Review by thibaultmg — APPROVED** [review]
/lgtm

**Pull request merged**
