### PR TITLE
[MTO] Move tests on build10, Skip tests when non needed, add post-submit

### PR DESCRIPTION
**Pull request by aleskandro**
We are moving tests on build10 to support the testing of multiarch-compute nodes clusters in the buildfarm.
 
Other MTO minor issues are being resolved here, like adding a post-submit and [MULTIARCH-4286](https://issues.redhat.com/browse/MULTIARCH-4286).

### CODE REVIEW

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-tuning-operator-main-e2e-gcp-multi-operator

**Review by droslean — APPROVED** [review]

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-tuning-operator-main-e2e-gcp-multi-operator-olm

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-tuning-operator-main-lint

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-tuning-operator-main-sast

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-tuning-operator-main-lint

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-tuning-operator-main-security

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-tuning-operator-main-lint

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-tuning-operator-main-sast

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-tuning-operator-main-sast

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-tuning-operator-main-lint

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-tuning-operator-main-sast

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-tuning-operator-main-lint

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-tuning-operator-main-security

**Comment by aleskandro** [comment]
/pj-rehearse ci/rehearse/openshift/multiarch-tuning-operator/main/lint ci/rehearse/openshift/multiarch-tuning-operator/main/sast ci/rehearse/openshift/multiarch-tuning-operator/main/security

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-tuning-operator-main-lint pull-ci-openshift-multiarch-tuning-operator-main-sast pull-ci-openshift-multiarch-tuning-operator-main-security

**Pull request merged**
