### PR TITLE
MCO Add MCO dedicated Vsphere agent SNO job

### PR DESCRIPTION
**Pull request by sergiordlr**
Add a dedicated jor for MCO running critical test cases in a Vsphere agent SNO cluster.

### CODE REVIEW

**Comment by sergiordlr** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-vsphere-agent-dualstack-sno-longduration-mco-critical-f9

**Comment by sergiordlr** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-vsphere-agent-dualstack-sno-longduration-mco-critical-f9

**Comment by sergiordlr** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-vsphere-agent-dualstack-sno-longduration-mco-critical-f9

**Comment by sergiordlr** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-vsphere-agent-dualstack-sno-longduration-mco-critical-f9

**Comment by sergiordlr** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-vsphere-agent-dualstack-sno-longduration-mco-critical-f9

**Comment by sergiordlr** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-vsphere-agent-dualstack-sno-longduration-mco-critical-f9

**Comment by sergiordlr** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-vsphere-agent-dualstack-sno-longduration-mco-critical-f9

**Comment by ptalgulk01** [comment]
/lgtm 
Thankyou !

**Pull request merged**
