### PR TITLE
RHEL scaleup: criotested repos should be versioned

### PR DESCRIPTION
**Pull request by vrutkovs**
Use OPENSHIFT_VERSION template var to construct origin-pr and criotested 
repos.

Keeping "4.0" in the names to avoid an ugly diff, this can be done later

cc @runcom

### CODE REVIEW

**Comment by vrutkovs** [comment]
/hold

There is no crio-tested 4.1 repo yet

**Comment by runcom** [comment]
> There is no crio-tested 4.1 repo yet

do we still have crio-tested also? I remember it going away at some point but I may be mistaken

**Comment by mtnbikenc** [comment]
Why are we using https://rpms.svc.ci.openshift.org/openshift-origin-v4.1/?  They are old 4.0 RPMs.
https://rpms.svc.ci.openshift.org/openshift-origin-v4.0/ and
https://rpms.svc.ci.openshift.org/openshift-origin-v4.1/
have the same content as well.

Why not https://mirror.openshift.com/enterprise/all/4.1/latest/x86_64/os/? cri-o is there too.  Also in https://mirror.openshift.com/enterprise/rhel/cri-o-tested/

**Comment by vrutkovs** [comment]
Superceded by #3761

**Pull request closed without merging**
