### PR TITLE
OCPQE-14534: Overwrite api_port for rosa-hypershift

### PR DESCRIPTION
**Pull request by liangxia**

### CODE REVIEW

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-stable-aws-rosa-sts-hypershift-guest-p1-f2

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-gcp-ipi-ovn-ipsec-p1-f4

**Comment by liangxia** [comment]
Verified the change still works on normal cluster with api port 6443
```
sh-4.4$ hostname
gcp-ipi-ovn-ipsec-p1-f4-cucushift-e2e

sh-4.4$ ls -lh ${SHARED_DIR}/runtime_env
lrwxrwxrwx. 1 root 1004200000 18 Mar 27 08:51 /var/run/secrets/ci.openshift.io/multi-stage/runtime_env -> ..data/runtime_env

sh-4.4$ head ${SHARED_DIR}/runtime_env
export USERS=testuser-1:******
export CUCUMBER_PUBLISH_QUIET=true
export DISABLE_WAIT_PRINT=true
export BUSHSLICER_LOG_LEVEL=INFO
export BUSHSLICER_DEFAULT_ENVIRONMENT=ocp4
export OPENSHIFT_ENV_OCP4_HOSTS="api.ci-op-7yip98n0-da4d6.qe.gcp.devcluster.openshift.com:lb"
export OPENSHIFT_ENV_OCP4_ADMIN_CREDS_SPEC=file:///tmp/kubeconfig
export BUSHSLICER_CONFIG="{'global': {'browser': 'chrome'}, 'environments': {'ocp4': {'api_port': '6443', 'version': '4.14'}}}"
```

/cc @jhou1 @JianLi-RH @dis016 @pruan-rht

**Comment by LiangquanLi930** [comment]
iam ok for HyperShift, thanks

**Pull request merged**
