### PR TITLE
switch cluster logging operator to use olm deployment for tests

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@ewolinetz @jcantrill please review the rehearsal output in https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/7933/rehearse-7933-pull-ci-openshift-cluster-logging-operator-master-e2e-operator/10/artifacts/e2e-operator/container-logs/test.log and confirm it ran all the tests you'd expect for cluster logging operator e2e.

**Comment by ewolinetz** [comment]
I see all the tests in `hack/testing`
@jcantrill i can't remember, do we expect any of the `test/e2e` tests still?

**Comment by bparees** [comment]
> @jcantrill i can't remember, do we expect any of the test/e2e tests still?

interesting, i don't see anything that would be running them, but it seems surprising to me that the golang tests would have been replaced by shell script tests.  I'd have expected things to go the other way.

it also looks to me like those tests expect/require the cluster logging operator is already installed on the cluster (in my quick survey I see nothing in them that deploys the operator, just stuff that creates logging instances)

**Comment by jcantrill** [comment]
> > @jcantrill i can't remember, do we expect any of the test/e2e tests still?

Yes.

> 
> interesting, i don't see anything that would be running them, but it seems surprising to me that the golang tests would have been replaced by shell script tests. I'd have expected things to go the other way.

These tests have bash scripts in `hack/testing` that are kicked off from `test-e2e.sh`

> 
> it also looks to me like those tests expect/require the cluster logging operator is already installed on the cluster (in my quick survey I see nothing in them that deploys the operator, just stuff that creates logging instances)

Most (if not all) the golang tests assume the operator was already deployed, presumably by the bash script.  This allows us to run them over and over without needing to redeploy.  The biggest limitation we've had is there was never really any good golang code to do easy deployment and easily gather artifacts

**Comment by bparees** [comment]
slack discussion confirmed we are running the goalng e2es, as seen in the output via things like:

```
 [INFO] Starting test of logforwarding ./test/e2e/logforwarding/fluent/
```

merging

**Pull request merged**
