### PR TITLE
Integrate e2e (golang+cucushift) for aws-usgov-ipi-private-cco-manual…

### PR DESCRIPTION
**Pull request by liangxia**
…-security-token-service

### CODE REVIEW

**Comment by jhou1** [comment]
What about every two weeks?

**Comment by liangxia** [comment]
There is another profile for aws-usgov which is already merged.
I think we can let this PR go, and update the test frequency in batch in a follow up PR. 
@jhou1 HDYT

**Comment by jhou1** [comment]
OK

/unhold
/lgtm

**Pull request merged**
