### PR TITLE
Add more descriptive message for hypershift-ibmcloud-cluster-claim-check failure

### PR DESCRIPTION
**Pull request by pamelachristie**
Improve logging when IBMCloud test fails due to another PR test already in progress.

### CODE REVIEW

**Comment by pamelachristie** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-ibmcloud-iks
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-ibmcloud-roks

**Comment by pamelachristie** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-ibmcloud-iks pull-ci-openshift-hypershift-main-e2e-ibmcloud-roks

**Comment by pamelachristie** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-ibmcloud-iks pull-ci-openshift-hypershift-main-e2e-ibmcloud-roks

**Comment by pamelachristie** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-ibmcloud-iks pull-ci-openshift-hypershift-main-e2e-ibmcloud-roks

**Comment by hasueki** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-ibmcloud-iks
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-ibmcloud-roks

**Comment by hasueki** [comment]
Results look good to me!
```
HyperShift operator deployment found on the PR test cluster. There may be another PR test in progress.
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/45877/rehearse-45877-pull-ci-openshift-hypershift-main-e2e-ibmcloud-roks/1727038203162005504
```
HyperShift operator deployment found on the PR test cluster. There may be another PR test in progress.
Build 1729257990277566464 installed the current HO deployment. 
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/45877/rehearse-45877-pull-ci-openshift-hypershift-main-e2e-ibmcloud-iks/1729266965911965696

**Review by hasueki — APPROVED** [review]
/lgtm

**Review by hasueki — APPROVED** [review]
/approve

**Pull request merged**
