### PR TITLE
Update the quayio-pull-through-cache

### PR DESCRIPTION
**Pull request by deepsm007**
Follow-up https://github.com/openshift/release/commit/6add24d85de83425975f1587df5447c6bc99a19e
Deploy the quayio cache on the new appci cluster

/cc @openshift/test-platform

### CODE REVIEW

**Comment by deepsm007** [comment]
/pj-rehearse pull-ci-openshift-cluster-capi-operator-release-4.14-e2e-aws-ovn-techpreview

**Comment by deepsm007** [comment]
/pj-rehearse pull-ci-openshift-lvm-operator-release-4.15-e2e-aws

**Review by jmguzik — APPROVED** [review]

**Pull request closed without merging**
