### PR TITLE
Add configmap-scale workload to downstream kubernetes repo

### PR DESCRIPTION
**Pull request by rsevilla87**
Includes configmap-scale workload to run manually in the kube-apiserver-operator component. This workload generates a configmap churning, that will allow us to detect bottlenecks and performance regressions related with etcd and kube-apiserver components.

It uses [kube-burner](https://github.com/cloud-bulldozer/kube-burner) to generate the workload, this tool is able to to fetch it's own configuration files from a remote http source (using a github project in this scenario)

cc: @tkashem @hexfusion @jtaleric

Signed-off-by: Raul Sevilla <rsevilla@redhat.com>

### CODE REVIEW

**Comment by sttts** [comment]
IMO the operator is the wrong repo, or at least we should also have that also in openshift/kubernetes. Rebases will be done in the latter and there we need this signal most.

**Comment by sttts** [comment]
Other than that, big :+1: for these kind of changes. Such a scale CI job can produce real value to notice regressions early.

**Comment by rsevilla87** [comment]
> IMO the operator is the wrong repo, or at least we should also have that also in openshift/kubernetes. Rebases will be done in the latter and there we need this signal most.

Makes sense, as discussed with @tkashem and @hexfusion we also have plans add this test to downstream openshift/etcd CI as well

**Comment by jtaleric** [comment]
@sttts @hexfusion @tkashem any other feedback for this work? Thanks!

**Comment by sttts** [comment]
If the new job is optional for PRs, I would just go ahead and merge. We can iterate to make it better.

LGTM

**Comment by rsevilla87** [comment]
> If the new job is optional for PRs, I would just go ahead and merge. We can iterate to make it better.
> 
> LGTM

I set always_run to false. Im not an expert in prow at all, so I guess this is the required parameter to make this job optional

**Comment by jtaleric** [comment]
> If the new job is optional for PRs, I would just go ahead and merge. We can iterate to make it better.
> 
> LGTM

ack! From the PR it looks like it won't run with every PR, someone would need to add a comment with : 

`/test configmap-scale` 

However, my CI understanding is lacking...

**Pull request merged**
