### PR TITLE
Add dry-runnable prow manifests for testing

### PR DESCRIPTION
**Pull request by 0xmichalis**
@bbguimaraes @stevekuznetsov this sets up a dry prow cluster so we avoid mutating any PRs or Jenkins jobs. Up to you whether you want this approach of copying the manifests or prepatch the original configs before creating them in the test cluster. I just went with this approach since it's faster.

One thing that needs to be tested in the new cluster is actual mutation of prowjobs because we have added [CRD validation](https://github.com/openshift/release/pull/542) (we don't use it today in the live cluster). For that we need a fix upstream to allow PJ mutation when --dry-run is true and no --deck-url is provided (TBD).

### CODE REVIEW

**Comment by kargakis** [comment]
> For that we need a fix upstream to allow PJ mutation when --dry-run is true and no --deck-url is provided (TBD).

Opened https://github.com/kubernetes/test-infra/pull/7329

**Comment by stevekuznetsov** [comment]
Why not just scale down the original cluster, export all the PJ and recreate in the new cluster? Downtime is fine.

**Comment by kargakis** [comment]
> Why not just scale down the original cluster, export all the PJ and recreate in the new cluster? Downtime is fine.

This is not for migrating the existing cluster but for testing in the new cluster.

**Comment by kargakis** [comment]
> One thing that needs to be tested in the new cluster is actual mutation of prowjobs because we have added CRD validation (we don't use it today in the live cluster). For that we need a fix upstream to allow PJ mutation when --dry-run is true and no --deck-url is provided (TBD).

I can confirm validation works fine (at least the most worrisome bit which was enabled in https://github.com/kubernetes/test-infra/pull/6215 and added in https://github.com/openshift/release/pull/542). What did I do?
* Build a docker image from https://github.com/kubernetes/test-infra/pull/7329
* Use that in the dry-run version of the jenkins operator introduced here; dropped deck-url from the flags
* Copied a pending prowjob from the prod cluster
* As is, the jenkins operator uses for BUILD_IDs the snowflake library so once it saw the prowjob in the cluster it successfully turned it to Error
* Confirmed it didn't mutate Github and Jenkins

**Comment by stevekuznetsov** [comment]
Ah, I see what you mean. OK.

**Comment by kargakis** [comment]
@juanvallejo what's the status of Manifests upstream? It would be nice to have a tool that works with patch overlays.

**Pull request closed without merging**
