### PR TITLE
Add a fake cluster pool for e2e tests

### PR DESCRIPTION
**Pull request by hongkailiu**
https://issues.redhat.com/browse/DPTP-2143

Required by https://github.com/openshift/ci-tools/pull/1884/files

/hold

waiting for Hive version with https://issues.redhat.com/browse/HIVE-1493

### CODE REVIEW

**Review by petr-muller — COMMENTED** [review]
let's call it `pools/ci-tools`? I still think we will want to have multiple pools in a directory so calling a directory "_pool" begs to be imprecise in the future.

**Comment by stevekuznetsov** [comment]
What is this waiting on? New Hive control plane rollout?

**Comment by hongkailiu** [comment]
Hive is now with v1.1.2.

/hold cancel

**Pull request merged**
