### PR TITLE
DEVEXP-557: bump samples operator to golang 1.13

### PR DESCRIPTION
**Pull request by gabemontero**
@openshift/openshift-team-developer-experience FYI

### CODE REVIEW

**Comment by gabemontero** [comment]
@dmage or @ricardomaraschini - got cycles for an lgtm ?

**Comment by dmage** [comment]
Unit tests have a strange problem:
```
--- FAIL: TestBinaryMetrics (0.04s)
    --- FAIL: TestBinaryMetrics/single_set_to_true (0.00s)
        server_test.go:148: error requesting metrics server: Get https://localhost:6789/metrics: unexpected EOF
```

@gabemontero feel free to unhold if that's expected

**Comment by gabemontero** [comment]
> Unit tests have a strange problem:
> 
> ```
> --- FAIL: TestBinaryMetrics (0.04s)
>     --- FAIL: TestBinaryMetrics/single_set_to_true (0.00s)
>         server_test.go:148: error requesting metrics server: Get https://localhost:6789/metrics: unexpected EOF
> ```
> 
> @gabemontero feel free to unhold if that's expected

Thanks for checking @dmage 
Yeah the current unit tests for metrics have a race condition around the local port they open which have not arisen enough yet for me to get rid of them ... though I get closer each time

Especially if say master and 4.6 unit tests run on the same host

I'll wait to see how the rest of them do, and then see about re-rehearsing

**Pull request merged**
