### PR TITLE
SPLAT-1382: add vSphere CAPI presubmit tests

### PR DESCRIPTION
**Pull request by rvanderp3**

### CODE REVIEW

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-vsphere-capi-ovn,pull-ci-openshift-installer-master-e2e-vsphere-capi-zones

**Comment by rvanderp3** [comment]
cc @jcpowermac @vr4manta

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-vsphere-capi-ovn pull-ci-openshift-installer-master-e2e-vsphere-capi-zones

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-vsphere-capi-ovn pull-ci-openshift-installer-master-e2e-vsphere-capi-zones

**Comment by r4f4** [comment]
@patrickdillon What's the plan for CAPI CI? Should the jobs live in the altinfra variant or in the main installer?

**Comment by r4f4** [comment]
@rvanderp3 does https://github.com/openshift/release/pull/48135 cover vsphere capi for the time being?

**Comment by rvanderp3** [comment]
> @rvanderp3 does #48135 cover vsphere capi for the time being?

yes, i believe it does.  closing this PR.

**Pull request closed without merging**
