### PR TITLE
MIXEDARCH-367: Add GCP e2e job for multi-arch compute

### PR DESCRIPTION
**Pull request by Prashanth684**
For 4.14 and 4.15

### CODE REVIEW

**Comment by Prashanth684** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-gcp-ovn-heterogeneous

**Comment by Prashanth684** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-gcp-ovn-heterogeneous

**Comment by Prashanth684** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.15-ocp-e2e-gcp-ovn-heterogeneous

**Comment by Prashanth684** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-gcp-ovn-heterogeneous

**Review by bradmwilliams — APPROVED** [review]

**Pull request merged**
