### PR TITLE
OCPQE-20548 set worker num to 2 for mco all suite on gcp

### PR DESCRIPTION
**Pull request by rioliu-rh**
configure worker num to 2 on GCP, this change will save much more time to execute all MCO cases

### CODE REVIEW

**Comment by rioliu-rh** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-gcp-ipi-f9-longduration-mco-all

**Comment by liangxia** [comment]
One line code change with 6 commits is not ideal. Would you mind to squash the commits to make a cleaner commit history ?

**Comment by rioliu-rh** [comment]
> One line code change with 6 commits is not ideal. Would you mind to squash the commits to make a cleaner commit history ?

I think github setting will squash all the commits when merge PR. https://github.com/$github-account/release/settings

**Comment by sergiordlr** [comment]
The change LGTM

**Comment by rioliu-rh** [comment]
@sergiordlr all cases still cannot be executed within 22 hours with 2 workers setting.
```
INFO[2024-04-12T10:34:00Z] Running step gcp-ipi-f9-longduration-mco-all-openshift-extended-test-longduration. 
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:169","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 22h0m0s timeout","severity":"error","time":"2024-04-13T07:28:17Z"}
```
https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/50850/rehearse-50850-periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-gcp-ipi-f9-longduration-mco-all/1778716728193191936

Do you think we still need this change?

**Comment by rioliu-rh** [comment]
I'm thinking whether we need to check status for every node in `preChecks`, maybe mcp level sanity check is good enough

**Comment by liangxia** [comment]
> > One line code change with 6 commits is not ideal. Would you mind to squash the commits to make a cleaner commit history ?
> 
> I think github setting will squash all the commits when merge PR. https://github.com/$(github-account)/release/settings
> 
> most of the commits in this PR history are auto generated by ort strategy

True and also not true.
release repo will squash the commits into one commit, but still keep all those commit messages.
e.g,
```
commit 5a7479fb5b3a151b83461dc9254c8b519efa2618
Author: Subhash Khileri <skhileri@redhat.com>
Date:   Wed Apr 10 02:34:23 2024 +0530

    Job to enable pr-check retest on backstage-showcase (#50139)
    
    * Job to enable pr-check retest on backstage-showcase
    
    * Job to enable pr-check retest on backstage-showcase
    
    * Job to enable pr-check retest on backstage-showcase
    
    * Job to enable pr-check retest on backstage-showcase
```

**Comment by rioliu-rh** [comment]
> > > One line code change with 6 commits is not ideal. Would you mind to squash the commits to make a cleaner commit history ?
> > 
> > 
> > I think github setting will squash all the commits when merge PR. [$(github-account)/release/settings](https://github.com/$(github-account)/release/settings)
> > most of the commits in this PR history are auto generated by ort strategy
> 
> True and also not true. release repo will squash the commits into one commit, but still keep all those commit messages. e.g,
> 
> ```
> commit ce1b5d7a9ecc26a61827a9956aa66253b6d72ff0
> Author: Xiaozheng Liu (Rio) <rioliu@redhat.com>
> Date:   Thu Feb 22 14:25:04 2024 +0800
> 
>     OCPQE-19032 add release-qe-test step and job (#48939)
>     
>     * add release-qe-test step and job
>     
>     * add few debug codes
>     
>     * make update
>     
>     * output jobctl content
>     
>     * try to fix from image of job-python3
>     
>     * change from image of job-python3 to oar-python3
>     
>     * remove from image and few debug codes
>     
>     * add cli base image
>     
>     * add cli image in step ref
>     
>     * correct cli image tag in step ref
>     
>     * add release for cli ref, add new image for jobctl
>     
>     * add ci-pull-credentials
>     
>     * update latest cli version to 4.16
>     
>     * remove cluster setting
>     
>     * add cluster config back to new test
>     
>     * remove cluster attribute for new test
>     
>     * add releasepayload modifier token in step
>     
>     * correct shell variable reference
>     
>     * add test code to list token
>     
>     * correct token file under mounted cred
>     
>     * correct cluster endpint
>     
>     * output token for debugging
>     
>     * refine oc cmds
>     
>     * update new nightly buld for testing
>     
>     * remove test code
>     
>     * add -e option for echo cmd
>     
>     * change cron job setting to every year
> ```

the commit message is configurable.
above message is Default. we can use PR title instead

**Comment by sergiordlr** [comment]
@rioliu-rh If this change is not a solution for the 22 hours timeout problem, then we don't need it. We need another approach.

**Comment by rioliu-rh** [comment]
> @rioliu-rh If this change is not a solution for the 22 hours timeout problem, then we don't need it. We need another approach.

ok, close this PR

**Pull request closed without merging**
