### PR TITLE
Fix issue DPTP-3312 Add periodic for clean up HyperShift leaked resources

### PR DESCRIPTION
**Pull request by bear-redhat**
Add a temporary periodic to clean up leaked resources by HyperShift

### CODE REVIEW

**Review by hongkailiu — APPROVED** [review]
NIT: Jira card as part of the component name: looking odd.

**Comment by hongkailiu** [comment]
/hold

/lgtm cancel

Need to fix failed checks.

**Comment by bear-redhat** [comment]
> NIT: Jira card as part of the component name: looking odd.

It's temporary

**Comment by hongkailiu** [comment]
/hold

free to cancel when you are ready to watch the rolling ...

**Pull request merged**
