### PR TITLE
[WIP] integreatly-operator: go-next-version branch

### PR DESCRIPTION
**Pull request by psturc**

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
👀

**Comment by laurafitzgerald** [comment]
@psturc was intly-operator-base-image also updated? It's using an older version of go https://github.com/integr8ly/integreatly-operator/blob/master/openshift-ci/Dockerfile.tools#L1

**Comment by psturc** [comment]
@laurafitzgerald thanks, that's a good point.

I've tried it now, but `IMAGE_NAME=registry.svc.ci.openshift.org/integr8ly/intly-operator-base-image:go-v1-16 test/run` is failing on `go mod vendor`, so I can't push the new tag until I figure out what's wrong.

WIP branch: https://github.com/integr8ly/integreatly-operator/pull/1633

cc @philbrookes

**Comment by laurafitzgerald** [comment]
@psturc can it be closed?

**Comment by psturc** [comment]
yes

**Pull request closed without merging**
