### PR TITLE
OCPQE-14317: 4.1 -> 4.13 upgrade

### PR DESCRIPTION
**Pull request by liangxia**

### CODE REVIEW

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-stable-4.1-aws-ipi-p1-f30

**Comment by jhou1** [comment]
I'm a bit curious about the result of this long run :)

Let me know if I should add the label now or later.

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-stable-4.1-aws-ipi-p1-f30

**Pull request merged**
