### PR TITLE
prow/bugzilla: release-4.4 now requires 4.4.z

### PR DESCRIPTION
**Pull request by sdodson**
/cc @eparis

### CODE REVIEW

**Comment by eparis** [comment]
Don't you also need to get https://github.com/openshift/release/pull/8710/files#diff-7c676c0b5340c412827ca4494082c350L243

**Comment by sdodson** [comment]
> Don't you also need to get https://github.com/openshift/release/pull/8710/files#diff-7c676c0b5340c412827ca4494082c350L243

Yeah, got those too. CI was failing on `make ci-operator-config` presumably because ci-operator had been updated since the last time it was run?

**Comment by sdodson** [comment]
@alvaroaleman Seems to be cleaning up the second commit here https://github.com/openshift/release/pull/8711

**Pull request merged**
