### PR TITLE
Update Tempo jobs.

### PR DESCRIPTION
**Pull request by IshwarKanse**

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-ocp-4.13-amd64-upgrade-opentelemetry-operator-upgrade periodic-ci-openshift-grafana-tempo-operator-main-ocp4.13-amd64-upgrade-tempo-operator-upgrade pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests pull-ci-openshift-grafana-tempo-operator-main-tempo-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-ocp-4.13-amd64-upgrade-opentelemetry-operator-upgrade

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-ocp-4.13-amd64-upgrade-opentelemetry-operator-upgrade

**Comment by IshwarKanse** [comment]
Autoscale test flaked, rest looks good.

**Review by vprashar2929 — APPROVED** [review]
/lgtm

**Pull request merged**
