### PR TITLE
chore: update powermon jobs to use cluster-pool

### PR DESCRIPTION
**Pull request by vprashar2929**
This PR updates the config/jobs for Power Monitoring Operator and Kepler to make use of cluster pool when running jobs for AWS clusters

It updates the below jobs:
* Post-submit
* Pre-submit
* Periodic

### CODE REVIEW

**Comment by vprashar2929** [comment]
//pj-rehearse pull-ci-openshift-power-monitoring-power-monitoring-operator-v1alpha1-power-monitoring-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-main-kepler-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-power-monitoring-operator-v1alpha1-power-monitoring-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-power-monitoring-operator-v1alpha1-power-monitoring-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-main-kepler-e2e

**Review by IshwarKanse — APPROVED** [review]
/lgtm

**Pull request merged**
