### PR TITLE
Sync Serverless CI

### PR DESCRIPTION
**Pull request by serverless-qe**
Sync Serverless CI using openshift-knative/hack.

### CODE REVIEW

**Comment by creydr** [comment]
as per https://github.com/openshift-knative/hack/pull/71#pullrequestreview-1609652060 hold until https://github.com/openshift-knative/eventing-kafka-broker/pull/808 merged

/hold
/cc @pierDipi

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

/unhold

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by skonto** [comment]
/lgtm 

just the slowstart image was added.

**Pull request merged**
