### PR TITLE
Add olm 4.16 to testgrid

### PR DESCRIPTION
**Pull request by tmshort**

### CODE REVIEW

**Review by perdasilva — APPROVED** [review]
lgtm

**Review by perdasilva — APPROVED** [review]
lgtm

**Comment by joelanford** [comment]
/approve
/label rehearsals-ack

Adding `rehearsals-ack` label despite failing rehearsals because this PR is simply updating testgrid to show 4.16 results. The fact that the tests ran is sufficient signal that this PR does what is intended.

**Review by perdasilva — APPROVED** [review]
lgtm

**Comment by tmshort** [comment]
ping @dptp

**Comment by tmshort** [comment]
ping @bear-redhat

**Review by droslean — APPROVED** [review]

**Comment by perdasilva** [comment]
@droslean thank you!!!

**Pull request merged**
