### PR TITLE
Test OpenTelemetry jobs.

### PR DESCRIPTION
**Pull request by IshwarKanse**
Run OTEL jobs, unblock tests and fix minor issues.

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-ocp-4.13-amd64-upgrade-opentelemetry-operator-upgrade periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-ocp-4.14-amd64-opentelemetry-e2e-tests periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-ocp-4.13-hypershift-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-ocp-4.13-amd64-upgrade-opentelemetry-operator-upgrade periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-ocp-4.14-amd64-opentelemetry-e2e-tests periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-ocp-4.13-hypershift-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-ocp-4.13-amd64-upgrade-opentelemetry-operator-upgrade periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-ocp-4.14-amd64-opentelemetry-e2e-tests periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-ocp-4.13-hypershift-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-ocp-4.13-hypershift-opentelemetry-e2e-tests

**Review by vprashar2929 — APPROVED** [review]
/lgtm

**Pull request merged**
