### PR TITLE
cluster-launch-installer-e2e: collect journals from all known nodes

### PR DESCRIPTION
**Pull request by vrutkovs**
This would split node journals in separate folders

### CODE REVIEW

**Comment by wking** [comment]
Do we really need this at all anymore?  I'd rather teach must-gather to handle this ([existing code][1]) and then lean on must-gather.  We might need to adjust the CI invocation to say "and also gather compute logs, although you'd usually just collect control-plane logs".  But unless we know we need node logs even in cases where must-gather fails (because the cluster got past bootstrap-complete but then croaked), I'd rather not have to maintain this redundant gather code.

[1]: https://github.com/openshift/must-gather/blob/f5a9121b9c7471700d061f8fe6dad3b320933501/collection-scripts/gather_service_logs

**Comment by vrutkovs** [comment]
>I'd rather teach must-gather to handle this (existing code) and then lean on must-gather

must-gather changes would also apply on customer clusters, which may be undesirable.

**Comment by wking** [comment]
> must-gather changes would also apply on customer clusters, which may be undesirable.

But sometimes it *would* be desirable.  So have it off by default, but with a simple knob to turn it on?  And set that knob for CI?

**Pull request merged**
