### PR TITLE
Removing 4.15 ppc64le jobs

### PR DESCRIPTION
**Pull request by aishwaryabk**
cc: @juliemathew @sajauddin

### CODE REVIEW

**Comment by aishwaryabk** [comment]
@kuiwang02 @rioliu-rh @aleskandro Request you to review this PR. Thanks!

**Comment by aishwaryabk** [comment]
@kuiwang02 @rioliu-rh  A gentle reminder on this. Thanks

**Comment by kuiwang02** [comment]
@aishwaryabk for regression prow job, it is not me to approve it. for me, I only review it from golang's view.
so, please contact with qe-productivity team to approve it.

cc @liangxia

**Pull request merged**
