### PR TITLE
remove test job on codeready-toolchain/toolchain-common

### PR DESCRIPTION
**Pull request by xcoulon**
Signed-off-by: Xavier Coulon <xcoulon@redhat.com>

### CODE REVIEW

**Comment by MatousJobanek** [comment]
I believe that we can remove the toolchain-common from the openshift-ci completely - we don't need any post-submit operations for that repo

**Review by MatousJobanek — APPROVED** [review]

**Comment by xcoulon** [comment]
closing in favor of https://github.com/openshift/release/pull/19593

**Pull request closed without merging**
