### PR TITLE
releases: migrate RT jobs to multi-stage

### PR DESCRIPTION
**Pull request by petr-muller**
Needs https://github.com/openshift/release/pull/16430

Resolves [DPTP-1686](https://issues.redhat.com/browse/DPTP-1686)

### CODE REVIEW

**Comment by petr-muller** [comment]
/cc @MarSik @jsafrane 

For now I have *not* bumped the compute node size to isolate the changes

**Comment by MarSik** [comment]
Btw, does it make sense to wait for fully green run? Looking at the past test results the jobs were failing most of the time anyway...

**Comment by petr-muller** [comment]
> Btw, does it make sense to wait for fully green run? 

Not green runs, but I wanted to see if they happen to be green and if we need https://github.com/openshift/release/pull/16435

**Comment by jsafrane** [comment]
/retest

4.9 went OK (as broken as usual -rt- test), but the others did not even install because of GCE API quota.

**Comment by petr-muller** [comment]
Hm, it does not seem that https://github.com/openshift/release/pull/16435 (which includes the compute node type increase to `n1-standard-8`) change has significantly better rehearsals than this one...

**Comment by petr-muller** [comment]
I guess we can merge this one and iterate?

**Pull request merged**
