### PR TITLE
HCO: Remove jobs for unused release branches

### PR DESCRIPTION
**Pull request by nunnatsa**
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

### CODE REVIEW

**Comment by danilo-gemoli** [comment]
What about mappings coming from `core-services/image-mirroring/openshift/mapping_origin_4_9`, `core-services/image-mirroring/openshift/mapping_origin_4_10` and `core-services/image-mirroring/openshift/mapping_origin_4_11`?

**Comment by danilo-gemoli** [comment]
@smg247 why is Tide playing hide-and-seek?

**Comment by smg247** [comment]
> @smg247 why is Tide playing hide-and-seek?

Rate limiting. It's just the status that doesn't show up. its been an off and on issue for a long time now.

**Comment by nunnatsa** [comment]
> What about mappings coming from `core-services/image-mirroring/openshift/mapping_origin_4_9`, `core-services/image-mirroring/openshift/mapping_origin_4_10` and `core-services/image-mirroring/openshift/mapping_origin_4_11`?

@danilo-gemoli - this is the result of running `make openshift-image-mirror-mappings`. I prefer no to change auto generated files.

**Comment by nunnatsa** [comment]
> > HCO: Remove jobs for unused release branches
> 
> 
> 
> am i to understand release-1.x is now your active set of release branches?
> 
> 
> 
> 

We never used openshift/release tobtelease cnv. We're using it for testing.

**Pull request merged**
