### PR TITLE
Sync Serverless CI

### PR DESCRIPTION
**Pull request by serverless-qe**
Sync Serverless CI using openshift-knative/hack.

### CODE REVIEW

**Comment by pierDipi** [comment]
/pj-rehearse pull-ci-openshift-knative-backstage-plugins-release-v1.12-415-images

**Comment by pierDipi** [comment]
/pj-rehearse pull-ci-openshift-knative-backstage-plugins-release-v1.12-415-images

**Comment by aliok** [comment]
/pj-rehearse pull-ci-openshift-knative-backstage-plugins-release-v1.12-415-images

"rate limiter"

**Comment by pierDipi** [comment]
@aliok 

we need to bump the Go version:
```
ERRO[2024-04-02T13:58:39Z] 
  * could not resolve inputs: could not determine inputs for step [input:openshift_release_rhel-8-release-golang-1.18-openshift-4.16]: could not resolve base image from openshift/release:rhel-8-release-golang-1.18-openshift-4.16: imagestreamtags.image.openshift.io "release:rhel-8-release-golang-1.18-openshift-4.16" not found 
INFO[2024-04-02T13:5[8](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/50459/rehearse-50459-pull-ci-openshift-knative-backstage-plugins-release-v1.12-415-images/1775160897304530944#1:build-log.txt%3A8):39Z] Reporting job state 'failed' with reason 'resolving_inputs'
```

**Comment by pierDipi** [comment]
This will fix the owners issue https://github.com/openshift-knative/hack/pull/143

**Comment by aliok** [comment]
> This will fix the owners issue https://github.com/openshift-knative/hack/pull/143

I merged it.

> we need to bump the Go version:

Done.

Now I triggered another generate-ci action.

**Comment by pierDipi** [comment]
/pj-rehearse pull-ci-openshift-knative-backstage-plugins-release-v1.12-415-images

**Comment by aliok** [comment]
The `config` dir for `backstage-plugins` has the OWNERS file but not the `jobs` dir.

@pierDipi

**Comment by pierDipi** [comment]
@aliok https://github.com/openshift-knative/hack/pull/145

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Comment by skonto** [comment]
Not sure if we need to be approvers in everything, unless we are that unlucky that one team has noone available.

**Pull request merged**
