### PR TITLE
ACM Obs: Use OCP4.17 for ACM2.12 tests

### PR DESCRIPTION
**Pull request by jacobbaungard**
Bump the OCP version to 4.17 for the ACM 2.12 release branch.

### CODE REVIEW

**Review by philipgough — APPROVED** [review]
/lgtm

**Comment by jacobbaungard** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-release-2.12-test-e2e

**Comment by jacobbaungard** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-release-2.12-test-e2e

**Pull request merged**
