### PR TITLE
fix(hypershift): update IBM Cloud tests for HyperShift

### PR DESCRIPTION
**Pull request by a-dsouza**
Updating IBM Cloud CI tests for HyperShift main branch:
https://v3.travis.ibm.com/github/alchemy-containers/armada-hypershift-operator/builds/5747939

### CODE REVIEW

**Comment by a-dsouza** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-ibmcloud-iks

**Comment by a-dsouza** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-ibmcloud-iks

**Comment by a-dsouza** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-ibmcloud-iks

**Comment by a-dsouza** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-ibmcloud-iks

**Comment by a-dsouza** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-ibmcloud-iks

**Review by hasueki — APPROVED** [review]
/lgtm

**Pull request merged**
