### PR TITLE
openshift/machine-config-operator: Drop e2e-aws-workers-rhel7

### PR DESCRIPTION
**Pull request by cgwalters**
AFAIK, we only support RHEL8 now:
https://github.com/openshift/openshift-docs/commit/ac891979aa26af8e284a4e924de796f9063fa07a

### CODE REVIEW

**Comment by cgwalters** [comment]
cc @mtnbikenc

**Comment by kikisdeliveryservice** [comment]
Fine with me. Will let Russell do the honors. :+1:

**Comment by mtnbikenc** [comment]
Hi all, I've not been on the Installer team for a while.  Need to have them engaged on this.
/uncc
/cc @staebler

**Pull request merged**
