### PR TITLE
Creating automation for DVO tests

### PR DESCRIPTION
**Pull request by JoaoFula**
This PR is for the creation of the automation for DVO e2e tests in OCP clusters. 
https://github.com/app-sre/deployment-validation-operator/

### CODE REVIEW

**Comment by JoaoFula** [comment]
PR is not ready to be merged. As of right now this is only a trial to understand the installation of OCP cluster with installation of DVO. The e2e tests are yet to be added to the config file.

**Comment by hongkailiu** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-e2e-in-cluster-build-4.14

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-e2e-in-cluster-build-4.13

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-e2e-in-cluster-build-4.13

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-e2e-in-cluster-build-4.13

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-e2e-in-cluster-build-4.13

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-e2e-in-cluster-build-4.13

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-e2e-in-cluster-build-4.13

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-e2e-in-cluster-build-4.13

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-deployment-validation-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-deployment-validation-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-deployment-validation-operator-e2e-tests

**Pull request closed without merging**
