### PR TITLE
WIP: donot merge: Example for running custom cnfqe1

### PR DESCRIPTION
**Pull request by rshemtov13**

### CODE REVIEW

**Comment by rshemtov13** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-telco5g-cnftests

**Comment by mrniranjan** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-telco5g-cnftests

**Comment by rshemtov13** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-telco5g-cnftests

**Comment by rshemtov13** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-telco5g-cnftests

**Comment by mrniranjan** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-telco5g-cnftests

**Comment by mrniranjan** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-telco5g-cnftests

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-telco5g-cnftests

**Pull request closed without merging**
