### PR TITLE
Add e2e job for csi-external-resizer sidecar

### PR DESCRIPTION
**Pull request by bertinatto**
CC @openshift/storage

### CODE REVIEW

**Comment by bertinatto** [comment]
/hold
Wait for rehearse jobs.

**Comment by bertinatto** [comment]
retest

**Comment by bertinatto** [comment]
/test pj-rehearse

`External Storage [Driver: ebs.csi.aws.com] [Testpattern: Dynamic PV (filesystem volmode)] volumeLimits should support volume limits [Slow][Serial] [Suite:k8s] [Suite:openshift/csi] ex`

This test failed, but it was supposed to be skipped. The other rehearse jobs skipped it correctly.

**Comment by bertinatto** [comment]
`level=error msg="Cluster operator monitoring Degraded is True with UpdatingAlertmanagerFailed: Failed to rollout the stack. Error: running task Updating Alertmanager failed: waiting for Alertmanager object changes failed: waiting for Alertmanager: expected 3 replicas, updated 2 and available 2"`

/hold cancel

**Comment by bertinatto** [comment]
Some failing jobs have the annotation` [Suite:openshift/csi]` in their names. This is weird because after the commit below these annotations are no longer added to CSI tests, so they shouldn't be there:
https://github.com/openshift/origin/commit/df6f5bd8c663ce1a89bd27ea289d695a66ff9199

**Comment by bertinatto** [comment]
`{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","time":"2020-02-17T16:36:40Z"}`

/retest

**Comment by bertinatto** [comment]
/test pj-rehearse

` level=fatal msg="Bootstrap failed to complete: failed to wait for bootstrapping to complete: timed out waiting for the condition" `

**Comment by jsafrane** [comment]
/lgtm
I can see every new job succeeded at least once and it failed mostly in bootstrap. Few times it failed due to AWS API throttling.

**Pull request merged**
