### PR TITLE
Azure UPI proxy

### PR DESCRIPTION
**Pull request by Amoghrd**

### CODE REVIEW

**Comment by Amoghrd** [comment]
I have retested this thrice but all the times the master nodes are not getting ready. @jianlinliu could you PTAL and let me know if there is something wrong

**Comment by jianlinliu** [comment]
> I have retested this thrice but all the times the master nodes are not getting ready. @jianlinliu could you PTAL and let me know if there is something wrong

Firstly we need to understand the detailed manual install process to set up the wanted install configuration, if you want to reference upi_on_azure-install.sh in QE's flexy template, need to go through every step, and merge necessary steps into the existing `upi-install-azure`, it is not simply place different existing reference in order.

In this PR, I saw you reference `azure-provision-resourcegroup`, `azure-provision-vnet` and `azure-provision-bastionhost`, but the question is, does `upi-install-azure` will use those created resources? E.g: `azure-provision-resourcegroup` will create a resource group, `upi-install-azure` will create another resource group, there is no relationship between them.

**Comment by Amoghrd** [comment]
@jianlinliu So regarding if the template is using the created resources, I printed out the install-config to check and can see that it is using the resources created in the vnet step here
`platform:`
  `azure:`
   ` baseDomainResourceGroupName: os4-common`
   ` region: northcentralus`
    `networkResourceGroupName: ci-op-fi8c0tv7-e02-rg`
`    virtualNetwork: ci-op-fi8c0tv7-56e02-vnet`
`    controlPlaneSubnet: ci-op-fi8c0tv7-56e02-master-subnet`
`    computeSubnet: ci-op-fi8c0tv7-56e02-worker-subnet`

**Comment by jianlinliu** [comment]
> I printed out the install-config to check and can see that it is using the resources created in the vnet step here

The detailed install process between UPI and IPI is different. IPI means installer will help provision all the resources per the setting in install-config.yaml, while UPI users need to provision all the resources on their own.

In this case, you provisioned resource group/vnet resources, and modified setting in install-config.yaml, while `upi-install-azure` created another separate resource group/vnet resources again, and also provision bootstrap/mastesr/workers there, obviously the being consumed vnet by the machines are not matched with the setting in the install-config.yaml.

I think here is two directions to move forwards:
1. modify `upi-install-azure` to make it respect the provisioned resource group/vnet, but not re-create some new ones.
2. not calling `azure-provision-resourcegroup`, `azure-provision-vnet`, `azure-provision-bastionhost`, but modify `upi-install-azure` and re-use it to make it also having the same functionality.

**Comment by Amoghrd** [comment]
@jianlinliu Can you PTAL at the shell. I have triggered the checks again but its failing at the for [loop](https://github.com/openshift/release/pull/27087/files#diff-5483a633ffe74be033f28def4e9b0c9adbfb0ec96b53e43ef314e22672b64ae9R1116) Its timing out with this log
`router-default LoadBalancer 172.30.214.172 <pending> 80:32316/TCP,443:31308/TCP 11m 
<pending>`

**Comment by jianlinliu** [comment]
You can download must-gather log from artifacts for trouble shooting.

From the failed job's must-gather log, I can see this:
```
$ router-default-9db48fcb5-v2tth.yaml
<--snip-->
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-04-01T03:23:23Z"
    message: '0/3 nodes are available: 3 node(s) had taint {node-role.kubernetes.io/master:
      }, that the pod didn''t tolerate.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: Burstable
```

That sounds like no any ready worker nodes.

Go back to the upi script, "Approving pending CSRs" is going to happen behind "Adding ingress DNS records", sounds it is not in a right order. Per our upi doc and reference to `ci-operator/step-registry/upi/install/azurestack/upi-install-azurestack-commands.sh`,  "Approving pending CSRs" should happen prior to "Adding ingress DNS records". I even doubt the common upi install works for not.

**Pull request closed without merging**
