### PR TITLE
Route tide ghv4 traffic to ghproxy

### PR DESCRIPTION
**Pull request by hongkailiu**

### CODE REVIEW

**Comment by hongkailiu** [comment]
/hold

will do after lunch.

**Comment by hongkailiu** [comment]
I did it only for `./cluster/ci/config/prow/`. What about others?
```
$ grep -irn github-endpoint .
./core-services/ci-chat-bot/deploy.yaml:51:          - --github-endpoint=http://ghproxy
./ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml:13:        - --github-endpoint=http://ghproxy
./ci-operator/jobs/infra-periodics.yaml:288:      - --github-endpoint=http://ghproxy
./ci-operator/jobs/infra-periodics.yaml:373:      - --github-endpoint=http://ghproxy
./ci-operator/jobs/infra-periodics.yaml:449:          - --github-endpoint=http://ghproxy
./cluster/ci/config/prow/openshift/plank.yaml:54:          - --github-endpoint=http://ghproxy
./cluster/ci/config/prow/openshift/tide.yaml:56:          - --github-endpoint=http://ghproxy
./cluster/ci/config/prow/openshift/needs_rebase.yaml:44:          - --github-endpoint=http://ghproxy
./cluster/ci/config/prow/openshift/hook.yaml:71:          - --github-endpoint=http://ghproxy
```

**Comment by stevekuznetsov** [comment]
We should change all of them.

**Pull request merged**
