### PR TITLE
Expansion of MTC scenario to run for 4.18

### PR DESCRIPTION
**Pull request by vi-patel**
Other updates:
  update cron
  add FIREWATCH_DEFAULT_JIRA_ASSIGNEE
  update .config.prowgen file for slack reporting of results being auto-created with make updates

### CODE REVIEW

**Comment by vi-patel** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.18-lp-interop-mtc-interop-aws

**Comment by vi-patel** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.18-lp-interop-mtc-interop-aws

**Comment by vi-patel** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.18-lp-interop-mtc-interop-aws

**Comment by vi-patel** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.18-lp-interop-mtc-interop-aws

**Comment by vi-patel** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.18-lp-interop-mtc-interop-aws

**Comment by vi-patel** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.18-lp-interop-mtc-interop-aws-fips

**Review by dfrazzette — APPROVED** [review]

**Pull request merged**
