### PR TITLE
Add e2e GCP ovn job for arm64

### PR DESCRIPTION
**Pull request by SaravanaStorageNetwork**
Fixes [ARMOCP-563](https://issues.redhat.com/browse/ARMOCP-563)

### CODE REVIEW

**Comment by SaravanaStorageNetwork** [comment]
/hold  

https://github.com/openshift/ci-tools/pull/3618 needs to be merged first.

**Comment by SaravanaStorageNetwork** [comment]
PR https://github.com/openshift/ci-tools/pull/3618 merged.  
/unhold

**Comment by SaravanaStorageNetwork** [comment]
I'm breaking down the patch into two parts https://github.com/openshift/release/pull/43372 to avoid errors in e2e test.

**Comment by SaravanaStorageNetwork** [comment]
@aleskandro  PTAL

**Comment by SaravanaStorageNetwork** [comment]
PR https://github.com/openshift/release/pull/43372 merged.

/unhold

**Comment by SaravanaStorageNetwork** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-gcp-ovn-arm64

**Comment by Prashanth684** [comment]
```
/bin/bash: line 19: /var/run/secrets/ci.openshift.io/cluster-profile/ssh-publickey: No such file or directory
```
are we missing some setting?

**Comment by SaravanaStorageNetwork** [comment]
> ```
> /bin/bash: line 19: /var/run/secrets/ci.openshift.io/cluster-profile/ssh-publickey: No such file or directory
> ```
> 
> are we missing some setting?

As such there are two related PRs (merged)
https://github.com/openshift/ci-tools/pull/3618 
https://github.com/openshift/release/pull/43372

I've added the secret following this doc. https://docs.ci.openshift.org/docs/how-tos/adding-a-new-secret-to-ci/ 
As I understand, there is no ssh key involvement here.  

@deepsm007 @aleskandro  Any insights here?

**Comment by Prashanth684** [comment]
> > ```
> > /bin/bash: line 19: /var/run/secrets/ci.openshift.io/cluster-profile/ssh-publickey: No such file or directory
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > are we missing some setting?
> 
> As such there are two related PRs (merged) [openshift/ci-tools#3618](https://github.com/openshift/ci-tools/pull/3618) #43372
> 
> I've added the secret following this doc. https://docs.ci.openshift.org/docs/how-tos/adding-a-new-secret-to-ci/ As I understand, there is no ssh key involvement here.
> 
> @deepsm007 @aleskandro Any insights here?

I think these need to be added to DPTP's vault as documented here: https://docs.ci.openshift.org/docs/how-tos/adding-a-cluster-profile/#providing-credentials

**Comment by Prashanth684** [comment]
> > > ```
> > > /bin/bash: line 19: /var/run/secrets/ci.openshift.io/cluster-profile/ssh-publickey: No such file or directory
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > are we missing some setting?
> > 
> > 
> > As such there are two related PRs (merged) [openshift/ci-tools#3618](https://github.com/openshift/ci-tools/pull/3618) #43372
> > I've added the secret following this doc. https://docs.ci.openshift.org/docs/how-tos/adding-a-new-secret-to-ci/ As I understand, there is no ssh key involvement here.
> > @deepsm007 @aleskandro Any insights here?
> 
> I think these need to be added to DPTP's vault as documented here: https://docs.ci.openshift.org/docs/how-tos/adding-a-cluster-profile/#providing-credentials
> 
> If you look at this PR: https://github.com/openshift/release/pull/40927/files#diff-63b36b70b93292356def13b06fae6212529d6669acfac0cb8fc3a6ecaa514e8aR68360, the QE team has a `cluster-secrets-gcp-qe`. we need one like this I guess

I see that you have added the secret here: https://github.com/openshift/release/blob/master/core-services/ci-secret-bootstrap/_config.yaml#L1120 although I'm not sure if  this is correct or it needs a separate block

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-gcp-ovn-arm64

**Comment by SaravanaStorageNetwork** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-gcp-ovn-arm64

**Comment by SaravanaStorageNetwork** [comment]
@Prashanth684  
<<I think these need to be added to DPTP's vault as documented here: https://docs.ci.openshift.org/docs/how-tos/adding-a-cluster-profile/#providing-credentials

Yes, I've done this. 

I tried adding the cluster-profile as part of separate block - but it isn't helping.
(like - https://github.com/openshift/release/pull/43372/files#diff-6f809450f5216bc90d0c08b723c9fe080da1358283bbf47c42f05bfc589c49fdL1066-R1114) 

It fails with this error:
 `INFO[2023-09-20T17:13:02Z] /bin/bash: line 10: /var/run/secrets/ci.openshift.io/cluster-profile/public_hosted_zone: No such file or directory `
(Complete logs [here](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/43535/rehearse-43535-periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-gcp-ovn-arm64/1704543504014774272))

Test platform team could help us.  
@danilo-gemoli  If you have any insight let us know.

**Comment by SaravanaStorageNetwork** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-gcp-ovn-arm64

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-gcp-ovn-arm64

**Comment by SaravanaStorageNetwork** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-gcp-ovn-arm64

**Comment by Prashanth684** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-gcp-ovn-arm64

**Comment by Prashanth684** [comment]
installs are successful - some tests are failing
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-gcp-ovn-arm64

**Comment by SaravanaStorageNetwork** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-gcp-ovn-arm64

**Comment by SaravanaStorageNetwork** [comment]
@Prashanth684  @dgoodwin rebase done. PTAL

**Pull request merged**
