### PR TITLE
Add pullrequest init to 0.5 tekton release

### PR DESCRIPTION
**Pull request by chmouel**

### CODE REVIEW

**Comment by hrishin** [comment]
@chmouel we need to add `pullrequest` in mirroring as well https://github.com/openshift/release/blob/master/core-services/image-mirroring/tekton/mapping_tekton_v0_5_quay

Right?

**Comment by chmouel** [comment]
@hrishin yes i was wondering where was it again,

**Comment by chmouel** [comment]
@hrishin yes i was wondering where was it again,

**Comment by hrishin** [comment]
Yes @chmouel repo got restructured a bit. Thank you :+1:  for adding it.

**Comment by chmouel** [comment]
There is something wrong going on with this job on tags, full investigation [here](https://coreos.slack.com/archives/CG5GV6CJD/p1568132723375000) (protected), let's try to merge this patch and rekick it on `openshift/tektoncd-pipeline`

**Pull request merged**
