### PR TITLE
Added a periodic job for smoke tests of Insights Operator

### PR DESCRIPTION
**Pull request by quarckster**
Insights Operator developers team would like to run the tests nightly.

### CODE REVIEW

**Comment by tremes** [comment]
@quarckster Thanks. What about 4.5 and 4.4?

**Comment by quarckster** [comment]
@tremes `TestUploadNotDelayedAfterStart` hasn't been backported to that versions.

**Comment by quarckster** [comment]
@tremes after discussion with @psimovec I added all tests to nightly job.

**Pull request merged**
