### PR TITLE
telco5g: Improve SNO job for telco5g

### PR DESCRIPTION
**Pull request by sshnaidm**
Add logging for SNO actions.
Add auth for pulling containers like it's done in MNO job.

### CODE REVIEW

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-telco5g-sno-cnftests

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-telco5g-sno-cnftests periodic-ci-openshift-release-master-nightly-4.13-e2e-telco5g-sno-cnftests periodic-ci-openshift-release-master-nightly-4.15-e2e-telco5g-sno-cnftests

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-telco5g-sno-cnftests

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-telco5g-sno-cnftests periodic-ci-openshift-release-master-nightly-4.13-e2e-telco5g-sno-cnftests periodic-ci-openshift-release-master-nightly-4.15-e2e-telco5g-sno-cnftests

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-telco5g-sno-cnftests periodic-ci-openshift-release-master-nightly-4.13-e2e-telco5g-sno-cnftests periodic-ci-openshift-release-master-nightly-4.15-e2e-telco5g-sno-cnftests

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-telco5g-sno-cnftests

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-telco5g-sno-cnftests

**Comment by Sandeepyadav93** [comment]
Thank you @sshnaidm for adding me on this review:-

As per the last failure, looks like Job is not able to find ~/pull-secret.txt .

~~~
TASK [Add docker auth to enable pulling containers from CI registry] ***********
task path: /output/fetch-kubeconfig.yml:26
fatal: [XXXXXXXXXXXX]: FAILED! => {"changed": true, "cmd": "oc --kubeconfig=/home/kni/ag-sno/cnfdu14-4.13-nightly/auth/kubeconfig set data secret/pull-secret -n openshift-config --from-file=.dockerconfigjson=~/pull-secret.txt", "delta": "0:00:00.059253", "end": "2023-11-06 11:54:51.232027", "msg": "non-zero return code", "rc": 1, "start": "2023-11-06 11:54:51.172774", "stderr": "error: error reading ~/pull-secret.txt: no such file or directory", "stderr_lines": ["error: error reading ~/pull-secret.txt: no such file or directory"], "stdout": "", "stdout_lines": []}
~~~

Just curious, Which containers are we not able to pull now in SNO and we want to address by adding this login?

**Comment by sshnaidm** [comment]
> Thank you @sshnaidm for adding me on this review:-
> 
> As per the last failure, looks like Job is not able to find ~/pull-secret.txt .
> 
> ```
> TASK [Add docker auth to enable pulling containers from CI registry] ***********
> task path: /output/fetch-kubeconfig.yml:26
> fatal: [XXXXXXXXXXXX]: FAILED! => {"changed": true, "cmd": "oc --kubeconfig=/home/kni/ag-sno/cnfdu14-4.13-nightly/auth/kubeconfig set data secret/pull-secret -n openshift-config --from-file=.dockerconfigjson=~/pull-secret.txt", "delta": "0:00:00.059253", "end": "2023-11-06 11:54:51.232027", "msg": "non-zero return code", "rc": 1, "start": "2023-11-06 11:54:51.172774", "stderr": "error: error reading ~/pull-secret.txt: no such file or directory", "stderr_lines": ["error: error reading ~/pull-secret.txt: no such file or directory"], "stdout": "", "stdout_lines": []}
> ```
> 
> Just curious, Which containers are we not able to pull now in SNO and we want to address by adding this login?

Containers from CI registry, because it requires authorization.

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-telco5g-sno-cnftests

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-telco5g-sno-cnftests

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-telco5g-sno-cnftests periodic-ci-openshift-release-master-nightly-4.14-e2e-telco5g-sno-cnftests periodic-ci-openshift-release-master-nightly-4.15-e2e-telco5g-sno-cnftests

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-telco5g-sno-cnftests periodic-ci-openshift-release-master-nightly-4.14-e2e-telco5g-sno-cnftests periodic-ci-openshift-release-master-nightly-4.15-e2e-telco5g-sno-cnftests

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-telco5g-sno-cnftests

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-telco5g-sno-cnftests periodic-ci-openshift-release-master-nightly-4.15-e2e-telco5g-sno-cnftests

**Pull request merged**
