### PR TITLE
Add the presubmit jobs for rosa Classic and HCP

### PR DESCRIPTION
**Pull request by yasun1**
As the first demo presubmit job works as expected, we'd like to add more jobs to satisfy the testing strategy.
[OCM-7988](https://issues.redhat.com//browse/OCM-7988)

### CODE REVIEW

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-rosa-master-e2e-presubmits-pr-rosa-hcp pull-ci-openshift-rosa-master-e2e-presubmits-pr-rosa-sts

**Review by radtriste — APPROVED** [review]
/lgtm

**Comment by yasun1** [comment]
@ciaranRoche Please help review the PR. Thanks.

**Pull request merged**
