### PR TITLE
STOR-1312: Add openshift/secrets-store-csi-driver-operator repo

### PR DESCRIPTION
**Pull request by dobsonj**
https://issues.redhat.com/browse/STOR-1312
Pre-submit, post-submit, and prow config for https://github.com/openshift/secrets-store-csi-driver-operator
cc @openshift/storage

### CODE REVIEW

**Comment by dobsonj** [comment]
/pj-rehearse ack
/cc @openshift/storage
for review

/assign @bparees
for image-mirroring approval

**Comment by bparees** [comment]
image name meets conventions.
/approve

**Pull request merged**
