### PR TITLE
OCPBUGS-42626: [CI] no tests were found matching the OPENSTACK_TEST_SKIPS regex

### PR DESCRIPTION
**Pull request by MiguelCarpio**
Remove skip of OPENSTACK_TEST_SKIPS manila share to the 4.13 and 4.12 shiftstack ci periodic proxy jobs

### CODE REVIEW

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.13-e2e-openstack-proxy periodic-ci-shiftstack-ci-release-4.12-e2e-openstack-proxy

**Review by mandre — COMMENTED** [review]
That's because the test doesn't exist in 4.12 and 4.13. Not sure if this works but we could try setting the `OPENSTACK_TEST_SKIPS` environment variable to the empty string in 4.12 and 4.13, to see if this takes precedence over what is defined in the workflow.

**Comment by MiguelCarpio** [comment]
/pj-rehearse pull-ci-openshift-machine-api-provider-openstack-release-4.18-e2e-openstack-proxy pull-ci-openshift-cluster-api-provider-openstack-release-4.13-e2e-openstack-proxy

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.12-e2e-openstack-proxy

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.13-e2e-openstack-proxy

**Comment by MiguelCarpio** [comment]
> > That's because the test doesn't exist in 4.12 and 4.13. Not sure if this works but we could try setting the `OPENSTACK_TEST_SKIPS` environment variable to the empty string in 4.12 and 4.13, to see if this takes precedence over what is defined in the workflow.
> 
> It's probably that the workflow env variable `OPENSTACK_TEST_SKIPS` overwrites what is defined in the `OPENSTACK_TEST_SKIPS` job config. However, I can test it in another PR.

Yeah, leaving the  `OPENSTACK_TEST_SKIPS` blank works. 

/pj-rehearse-ack

**Pull request merged**
