### PR TITLE
upgrade clusterlifecycle-state-metrics golang to 1.21

### PR DESCRIPTION
**Pull request by haoqing0110**

### CODE REVIEW

**Comment by haoqing0110** [comment]
/pj-rehearse pull-ci-stolostron-clusterlifecycle-state-metrics-main-sonar-pre-submit

**Comment by xuezhaojun** [comment]
@haoqing0110 

We need to click accept for the security issues found by sonar.( I did
image

**Comment by xuezhaojun** [comment]
/pj-rehearse pull-ci-stolostron-clusterlifecycle-state-metrics-main-sonar-pre-submit

**Pull request merged**
