### PR TITLE
Generate 4.5 jobs

### PR DESCRIPTION
**Pull request by hongkailiu**
Follow up https://github.com/openshift/release/pull/6041

https://coreos.slack.com/archives/GB7NB0CUC/p1574440388487400

Refer https://github.com/openshift/release/pull/5169

```bash
config-brancher --config-dir ./ci-operator/config --current-release 4.4 --future-release 4.5 --confirm
for i in $(find ci-operator/jobs/ -name '*-release-4.4-*submits.yaml' ); do cp  "${i//-release-4.4-/-master-}" "${i//-release-4.4-/-release-4.5-}"; done

find ci-operator/jobs/ -name '*release-4.5-*submits.yaml' -exec sed -i 's/-master-/-release-4.5-/g' {} \;

ci-operator-prowgen --from-dir ./ci-operator/config/ --to-dir ./ci-operator/jobs/
```

### CODE REVIEW

**Comment by hongkailiu** [comment]
@petr-muller 
I got stuck here.
I cannot make those checks happy.

**Comment by petr-muller** [comment]
I'll look into it.

**Comment by petr-muller** [comment]
/close
Done in https://github.com/openshift/release/pull/6072

**Pull request closed without merging**
