### PR TITLE
Sync Serverless CI

### PR DESCRIPTION
**Pull request by serverless-qe**
Sync Serverless CI using openshift-knative/hack.

### CODE REVIEW

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

/pj-rehearse max

**Comment by ReToCode** [comment]
@pierDipi not sure about the older eventing-kafka-broker CI. Do you want to re-run or merge and (maybe) fix later?

**Comment by mgencur** [comment]
@ReToCode I think we should remove all CI configs for unsupported versions from all repositories. They're not required anymore. They only slow down CI updates like this one and they can be found in GIT history is required (but I doubt they will be required again).

**Pull request merged**
