### PR TITLE
OpenStack: Skip Networking IPerf2

### PR DESCRIPTION
**Pull request by mdbooth**
This is pending resolution of https://bugzilla.redhat.com/show_bug.cgi?id=2000754

/cc @iamemilio

### CODE REVIEW

**Comment by iamemilio** [comment]
can you also skip this for 4.9

**Comment by MaysaMacedo** [comment]
In case this needs to be skipped only when openstack is used, maybe a rule can be added here https://github.com/openshift/origin/blob/master/test/extended/util/annotate/rules.go

**Pull request closed without merging**
