### PR TITLE
DPTP-3353: Add heterogeneous (multi) cluster to build farm readme

### PR DESCRIPTION
**Pull request by deepsm007**
/cc @droslean @danilo-gemoli

### CODE REVIEW

**Review by droslean — APPROVED** [review]

**Comment by droslean** [comment]
@hongkailiu In which point we should include a kubeconfig in our list?

**Comment by hongkailiu** [comment]
> @hongkailiu At which point should we include a kubeconfig in our list?

This would be the first step for joining the cluster. We need to upload it manually to Vault.
https://vault.ci.openshift.org/ui/vault/secrets/kv/show/dptp/config-updater

The requirement of the kubeconfig is
https://github.com/openshift/release/blob/master/clusters/JoinBuildFarm.md#set-up-applyconfig-against-the-cluster


Do we treat multi01 differently from other clusters, like b1…b05? If it is the same, we have automation for joining the cluster.

Try this in the ci-tools foler:
```
$ go run ./cmd/cluster-init --create-pr=false --release-repo <path_to_release_repo>  --cluster-name multi01
```
You can check the result and keep the things you like.

**Comment by droslean** [comment]
@deepsm007 I am closing this PR since the process is more complicated. I will take care of it in another PR.

**Pull request closed without merging**
