### PR TITLE
OCPQE-18638: Add slack notification for automated release jobs

### PR DESCRIPTION
**Pull request by liangxia**

### CODE REVIEW

**Comment by rioliu-rh** [comment]
@liangxia  only one concern. Do we need to send notification for successful job?

**Comment by liangxia** [comment]
> @liangxia only one concern. Do we need to send notification for successful job?

To make sure we can get notification for those jobs. E.g, if we do not send the notification for the success jobs, and the job success in the coming 10 days. It's hard to know whether the notification works as expected or not (the notification not working or due to no failure jobs).
We can remove the notification for those success jobs later after we confirm the notification work as expected.

**Pull request merged**
