### PR TITLE
kubevirt: vm-console-proxy: Add CI for branch "release-v0.6"

### PR DESCRIPTION
**Pull request by akrejcir**

### CODE REVIEW

**Review by 0xFelix — APPROVED** [review]
/lgtm

**Comment by akrejcir** [comment]
/pj-rehearse pull-ci-kubevirt-vm-console-proxy-release-v0.6-e2e-functests

**Comment by akrejcir** [comment]
/pj-rehearse pull-ci-kubevirt-vm-console-proxy-release-v0.6-e2e-functests

**Pull request merged**
