### PR TITLE
Increase ceph pod resources for tempest

### PR DESCRIPTION
**Pull request by fmount**

### CODE REVIEW

**Comment by fmount** [comment]
/pj-reharse pull-ci-openstack-k8s-operators-manila-operator-main-manila-operator-build-deploy-tempest

**Comment by fmount** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-glance-operator-main-glance-operator-build-deploy-tempest

**Comment by fmount** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-glance-operator-main-glance-operator-build-deploy-tempest

**Comment by fmount** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-manila-operator-main-manila-operator-build-deploy-tempest

**Comment by fmount** [comment]
@viroel "2Gi" for Ceph are not enough when manila-tempest is executed: we see failures in https://github.com/openstack-k8s-operators/manila-operator/pull/242 because the Ceph Pod is evicted and Glance start crashloopbacking because the backend is gone.

**Comment by fmount** [comment]
@viroel why the current `manila-tempest` does not get the new `CEPH_DATASIZE` [1] ?

[1] https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/49290/rehearse-49290-pull-ci-openstack-k8s-operators-manila-operator-main-manila-operator-build-deploy-tempest/1762750317633474560/artifacts/manila-operator-build-deploy-tempest/openstack-k8s-operators-deploy/build-log.txt

**Comment by fmount** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-manila-operator-main-manila-operator-build-deploy-tempest

**Comment by fmount** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-glance-operator-main-glance-operator-build-deploy-tempest

**Comment by fmount** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-cinder-operator-main-cinder-operator-build-deploy-tempest

**Comment by fmount** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-manila-operator-main-manila-operator-build-deploy-tempest

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-manila-operator-main-manila-operator-build-deploy-tempest

**Comment by viroel** [comment]
now running without the hold-the-node

**Comment by viroel** [comment]
/pj-rehearse abort
 
 previous run only failed due to hold-the-node flag enabled:
 https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/49290/rehearse-49290-pull-ci-openstack-k8s-operators-manila-operator-main-manila-operator-build-deploy-tempest/1762844486725013504/build-log.txt
 
Tempest tests passing:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/49290/rehearse-49290-pull-ci-openstack-k8s-operators-manila-operator-main-manila-operator-build-deploy-tempest/1762844486725013504/artifacts/manila-operator-build-deploy-tempest/openstack-k8s-operators-tempest/artifacts/stestr_results.html

**Comment by viroel** [comment]
/pj-rehearse ack

previous run of manila is passing on tempest. Change looks good.

**Pull request merged**
