### PR TITLE
Use OCP 4.9 in ACM 2.4 GRC framework tests

### PR DESCRIPTION
**Pull request by JustinKuli**

### CODE REVIEW

**Review by dhaiducek — CHANGES_REQUESTED** [review]

**Comment by dhaiducek** [comment]
There's a new rehearsal command to trigger the rehearsal since I think they no longer trigger automatically. I'll dig it up so we can test the updated config.

**Review by dhaiducek — APPROVED** [review]
Shoot. We (AKA RHACM) would need to make updates to the step registry script to detect the `release` repo and handle it properly. We'll ignore the rehearsals for now and get this merged.

**Review by gurnben — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
