### PR TITLE
telco5g: Add additional wait timeout for SNO jobs for 30 min

### PR DESCRIPTION
**Pull request by sshnaidm**
[CNF-11218](https://issues.redhat.com//browse/CNF-11218)

### CODE REVIEW

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-telco5g-sno-cnftests

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-telco5g-sno-cnftests periodic-ci-openshift-release-master-nightly-4.14-e2e-telco5g-sno-cnftests periodic-ci-openshift-release-master-nightly-4.12-e2e-telco5g-sno-cnftests

**Comment by Sandeepyadav93** [comment]
/lgtm

Adding another 30 mins doesn't seems to help but patch is doing what it is expected to do:-

~~~
FAILED - RETRYING: [XXXXXXXXXXXX]: Run oc command to check if cluster is ready (30 retries left).
.
.

FAILED - RETRYING: [XXXXXXXXXXXX]: Run oc command to check if cluster is ready (1 retries left).
fatal: [XXXXXXXXXXXX]: FAILED! => {
    "attempts": 30,
    "changed": true,
    "cmd": "oc --kubeconfig=/home/kni/ag-sno/cnfdu13-4.12-nightly/auth/kubeconfig get clusterversion -o=jsonpath='{.items[0].status.conditions[?(@.type=='\\''Available'\\'')].status}'",
    "delta": "0:00:00.082451",
    "end": "2024-02-08 14:10:33.552681",
    "rc": 0,
    "start": "2024-02-08 14:10:33.470230"
}

STDOUT:

False
...ignoring
~~~

**Pull request merged**
