### PR TITLE
NO-ISSUE: fix multiline echo

### PR DESCRIPTION
**Pull request by eifrach**

### CODE REVIEW

**Comment by eifrach** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-nutanix-assisted

**Comment by eifrach** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-nutanix-assisted

**Comment by eifrach** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-nutanix-assisted

**Review by danmanor — APPROVED** [review]

**Pull request merged**
