### PR TITLE
e2e-aws master: remove extra space in TEST_SKIP

### PR DESCRIPTION
**Pull request by vrutkovs**
This fixed a list of skipped tests for e2e-aws job. This fixes https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/9990/pull-ci-openshift-openshift-ansible-master-e2e-aws/28/build-log.txt - some tests were not skipped

### CODE REVIEW

**Comment by vrutkovs** [comment]
@stevekuznetsov the tests fail and suggest to split this line - which is incorrect. Should I use env vars instead or Prow tests should be fixed?

**Comment by stevekuznetsov** [comment]
Why is it incorrect?

```
$ cat /tmp/test.yaml 
key: value that is on
  multiple lines
$ python
Python 2.7.13 (default, May 10 2017, 20:04:28) 
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>> with open("/tmp/test.yaml") as f:
...     data = yaml.load(f)
... 
>>> data["key"]
'value that is on multiple lines'
```

**Comment by stevekuznetsov** [comment]
Perhaps it's `'(\\['` being wrong and you need `"(\\["` or `'(\['`? For what it's worth, you are the only test with `\\[`

**Comment by stevekuznetsov** [comment]
I would suggest changing to `'(\['` to match the rest

**Comment by vrutkovs** [comment]
`value: |` was the trick

**Pull request merged**
