### PR TITLE
Always run single node live CD on installer presubmit

### PR DESCRIPTION
**Pull request by omertuc**

### CODE REVIEW

**Comment by staebler** [comment]
Do we have the metal resources to make this an always run? Before we enable this, I want to make sure that we are confident that this will not be another always-run test that rarely passes.

**Comment by omertuc** [comment]
> Do we have the metal resources to make this an always run? Before we enable this, I want to make sure that we are confident that this will not be another always-run test that rarely passes.

@wking raised similar concerns. I'll reevaluate.

/hold

**Comment by romfreiman** [comment]
@staebler @omertuc  we got higher quota for Packet. And the test grid looks good:
https://testgrid.k8s.io/redhat-openshift-ocp-release-4.8-informing#periodic-ci-openshift-release-master-nightly-4.8-e2e-metal-single-node-live-iso
Lets enable this job?

**Pull request merged**
