### PR TITLE
templates: Add large and xlarge variants

### PR DESCRIPTION
**Pull request by smarterclayton**
These variants increase the size of master nodes so we can launch
larger clusters.

### CODE REVIEW

**Comment by wking** [comment]
Did you want to bump the UPI template too?  Metal template?  Or are we going to take this in a few baby steps?

**Comment by smarterclayton** [comment]
Right now I just want to test with AWS (the primary reason to do large is so we can launch a cluster from the bot that is capable of scaling to 1k nodes)

**Comment by abhinavdahiya** [comment]
> Right now I just want to test with AWS (the primary reason to do large is so we can launch a cluster from the bot that is capable of scaling to 1k nodes)

@smarterclayton do we have enough IPs in the default case to support 1000 nodes... ?

the default are https://github.com/openshift/installer/blob/a9c3395b1b51d418d5e9ff1490148647f36c2cd3/pkg/types/defaults/installconfig.go#L19-L20
that allow 512 pods and 512 nodes??

**Comment by smarterclayton** [comment]
The documentation on these API objects is atrocious.

**Pull request merged**
