### PR TITLE
Bump TALM golang version to 1.19

### PR DESCRIPTION
**Pull request by sudomakeinstall2**
Signed-off-by: Saeid Askari <saskari@redhat.com>

### CODE REVIEW

**Comment by jc-rh** [comment]
/pj-rehearse pull-ci-openshift-kni-cluster-group-upgrades-operator-main-ci-job

**Comment by sudomakeinstall2** [comment]
/pj-rehearse pull-ci-openshift-kni-cluster-group-upgrades-operator-main-ci-job

**Review by nishant-parekh — APPROVED** [review]

**Comment by jc-rh** [comment]
/pj-rehearse pull-ci-openshift-kni-cluster-group-upgrades-operator-main-integration

**Pull request merged**
