### PR TITLE
remove: SKIP_HYPERSHIFT_PULL_SECRET_UPDATE

### PR DESCRIPTION
**Pull request by LiangquanLi930**
this is to enable qe catalog source in hypershift upgrade pipelines

### CODE REVIEW

**Comment by liangxia** [comment]
A quick search show there are six occurrence of the var, while we see five of them changed in this PR. Could you double confirm ?
```
$ grep -r SKIP_HYPERSHIFT_PULL_SECRET_UPDATE ci-operator/config/
ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.12.yaml:      SKIP_HYPERSHIFT_PULL_SECRET_UPDATE: "true"
ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.12.yaml:      SKIP_HYPERSHIFT_PULL_SECRET_UPDATE: "true"
ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-4.14-upgrade-from-stable-4.13.yaml:      SKIP_HYPERSHIFT_PULL_SECRET_UPDATE: "true"
ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.13.yaml:      SKIP_HYPERSHIFT_PULL_SECRET_UPDATE: "true"
ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.13.yaml:      SKIP_HYPERSHIFT_PULL_SECRET_UPDATE: "true"
ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.13.yaml:      SKIP_HYPERSHIFT_PULL_SECRET_UPDATE: "true"

```

**Comment by LiangquanLi930** [comment]
> A quick search show there are six occurrence of the var, while we see five of them changed in this PR. Could you double confirm ?
> 
> ```
> $ grep -r SKIP_HYPERSHIFT_PULL_SECRET_UPDATE ci-operator/config/
> ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.12.yaml:      SKIP_HYPERSHIFT_PULL_SECRET_UPDATE: "true"
> ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.12.yaml:      SKIP_HYPERSHIFT_PULL_SECRET_UPDATE: "true"
> ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-4.14-upgrade-from-stable-4.13.yaml:      SKIP_HYPERSHIFT_PULL_SECRET_UPDATE: "true"
> ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.13.yaml:      SKIP_HYPERSHIFT_PULL_SECRET_UPDATE: "true"
> ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.13.yaml:      SKIP_HYPERSHIFT_PULL_SECRET_UPDATE: "true"
> ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.13.yaml:      SKIP_HYPERSHIFT_PULL_SECRET_UPDATE: "true"
> ```

Thanks a lot! done

**Pull request merged**
