### PR TITLE
Assisted installer: 4.6 periodic should run weekly and without conformance tests

### PR DESCRIPTION
**Pull request by tsorya**
Assisted installer: 4.6 periodic should run weekly and without conformance tests

### CODE REVIEW

**Review by osherdp — CHANGES_REQUESTED** [review]
/hold
let's see how rehearsal goes

**Review by osherdp — CHANGES_REQUESTED** [review]
seems like it still doesn't work, because you need to declare ``TEST_SUITE`` as a parameter in: https://github.com/openshift/release/blob/master/ci-operator/step-registry/assisted/baremetal/test/assisted-baremetal-test-ref.yaml#L12

**Comment by tsorya** [comment]
> seems like it still doesn't work, because you need to declare `TEST_SUITE` as a parameter in: https://github.com/openshift/release/blob/master/ci-operator/step-registry/assisted/baremetal/test/assisted-baremetal-test-ref.yaml#L12

why it is so difficult to make such a small change

**Comment by osherdp** [comment]
> > seems like it still doesn't work, because you need to declare `TEST_SUITE` as a parameter in: https://github.com/openshift/release/blob/master/ci-operator/step-registry/assisted/baremetal/test/assisted-baremetal-test-ref.yaml#L12
> 
> why it is so difficult to make such a small change

/shrug

**Review by osherdp — APPROVED** [review]

**Comment by osherdp** [comment]
/test pj-rehearse
4.6 installation failure is a bit interesting. worth adding to the sheet

**Review by osherdp — APPROVED** [review]

**Comment by osherdp** [comment]
Seems like it worked
Well done!

**Pull request merged**
