### PR TITLE
Add template-validator image to the CI jobs

### PR DESCRIPTION
**Pull request by vatsalparekh**
Build template-validator image from the Dockerfile and make it usable for the test jobs

Signed-off-by: Vatsal Parekh <vparekh@redhat.com>

### CODE REVIEW

**Comment by akrejcir** [comment]
Have you run `make update` to update the jobs?

**Comment by ksimon1** [comment]
Can you please remove https://github.com/openshift/release/tree/master/ci-operator/config/kubevirt/kubevirt-template-validator folder?

**Comment by vatsalparekh** [comment]
> Have you run `make update` to update the jobs?

@akrejcir  I did, no changes done by it

**Comment by akrejcir** [comment]
@ksimon1, Please, don't approve PRs in this repo before the CI passes. `/approve` skips CI.

**Pull request merged**
