### PR TITLE
build02: use 600Gb disks on workers

### PR DESCRIPTION
**Pull request by hongkailiu**
Follow up https://coreos.slack.com/archives/GB7NB0CUC/p1607039371232600

The 2nd commit shows what I modified on the existing ones.

I have done the following to all 3 machinesets to generate `kubectl.kubernetes.io/last-applied-configuration` annotation. Then we can remove `machineset.spec.replicas` field safely.

```
oc --context build02 get machineset -n openshift-machine-api ${machineset} -o yaml | oc --context build02 apply  --as system:admin -f -
```

Currently we have those workers:

```
oc --context build02 get machine -n openshift-machine-api  | grep w-
build0-gstfj-w-b-4kk57   Running   n1-standard-16   us-east1   us-east1-b   3d19h
build0-gstfj-w-b-fz88z   Running   n1-standard-16   us-east1   us-east1-b   3d18h
build0-gstfj-w-b-hvf4d   Running   n1-standard-16   us-east1   us-east1-b   21d
build0-gstfj-w-b-nxf7x   Running   n1-standard-16   us-east1   us-east1-b   3d19h
build0-gstfj-w-b-r4gkk   Running   n1-standard-16   us-east1   us-east1-b   3d19h
build0-gstfj-w-b-tgpxk   Running   n1-standard-16   us-east1   us-east1-b   3d19h
build0-gstfj-w-b-tq465   Running   n1-standard-16   us-east1   us-east1-b   3d18h
build0-gstfj-w-b-vdrss   Running   n1-standard-16   us-east1   us-east1-b   3d16h
build0-gstfj-w-b-wlt5m   Running   n1-standard-16   us-east1   us-east1-b   3d18h
build0-gstfj-w-b-xjjgg   Running   n1-standard-16   us-east1   us-east1-b   3d19h
build0-gstfj-w-c-4gdwm   Running   n1-standard-16   us-east1   us-east1-c   3d18h
build0-gstfj-w-c-7tq97   Running   n1-standard-16   us-east1   us-east1-c   11d
build0-gstfj-w-c-c5n6z   Running   n1-standard-16   us-east1   us-east1-c   9d
build0-gstfj-w-c-dgn5s   Running   n1-standard-16   us-east1   us-east1-c   23h
build0-gstfj-w-c-fxj4s   Running   n1-standard-16   us-east1   us-east1-c   11d
build0-gstfj-w-c-p9wl8   Running   n1-standard-16   us-east1   us-east1-c   9d
build0-gstfj-w-c-qtvg2   Running   n1-standard-16   us-east1   us-east1-c   3d22h
build0-gstfj-w-c-zzc4g   Running   n1-standard-16   us-east1   us-east1-c   3d18h
build0-gstfj-w-d-4lw59   Running   n1-standard-16   us-east1   us-east1-d   10d
build0-gstfj-w-d-bmfqn   Running   n1-standard-16   us-east1   us-east1-d   44d
build0-gstfj-w-d-h9drp   Running   n1-standard-16   us-east1   us-east1-d   20h
build0-gstfj-w-d-hjsjc   Running   n1-standard-16   us-east1   us-east1-d   16d
build0-gstfj-w-d-j7d29   Running   n1-standard-16   us-east1   us-east1-d   20h
build0-gstfj-w-d-k2t98   Running   n1-standard-16   us-east1   us-east1-d   11d
build0-gstfj-w-d-m786c   Running   n1-standard-16   us-east1   us-east1-d   16d
build0-gstfj-w-d-rsglh   Running   n1-standard-16   us-east1   us-east1-d   14d
build0-gstfj-w-d-t9hn7   Running   n1-standard-16   us-east1   us-east1-d   14d
```

I will delete them one by one to see if the new ones created by autoscaler have the bigger disk.

/cc @stevekuznetsov @alvaroaleman

### CODE REVIEW

**Review by alvaroaleman — APPROVED** [review]

**Comment by hongkailiu** [comment]
/hold

Will do cluster upgrade now.

**Comment by hongkailiu** [comment]
upgrade is complete.

/hold cancel

```
oc --context build02 get node
NAME                                                        STATUS   ROLES    AGE     VERSION
build0-gstfj-m-0.c.openshift-ci-build-farm.internal         Ready    master   199d    v1.19.0+1348ff8
build0-gstfj-m-1.c.openshift-ci-build-farm.internal         Ready    master   199d    v1.19.0+1348ff8
build0-gstfj-m-2.c.openshift-ci-build-farm.internal         Ready    master   199d    v1.19.0+1348ff8
build0-gstfj-w-b-hvf4d.c.openshift-ci-build-farm.internal   Ready    worker   24d     v1.19.0+1348ff8
build0-gstfj-w-b-k88vm.c.openshift-ci-build-farm.internal   Ready    worker   174m    v1.19.0+1348ff8
build0-gstfj-w-b-wvswj.c.openshift-ci-build-farm.internal   Ready    worker   174m    v1.19.0+1348ff8
build0-gstfj-w-c-4gdwm.c.openshift-ci-build-farm.internal   Ready    worker   6d16h   v1.19.0+1348ff8
build0-gstfj-w-c-7t6n6.c.openshift-ci-build-farm.internal   Ready    worker   170m    v1.19.0+1348ff8
build0-gstfj-w-c-7tq97.c.openshift-ci-build-farm.internal   Ready    worker   13d     v1.19.0+1348ff8
build0-gstfj-w-c-fxj4s.c.openshift-ci-build-farm.internal   Ready    worker   13d     v1.19.0+1348ff8
build0-gstfj-w-c-k884p.c.openshift-ci-build-farm.internal   Ready    worker   2d16h   v1.19.0+1348ff8
build0-gstfj-w-c-n4dm5.c.openshift-ci-build-farm.internal   Ready    worker   17h     v1.19.0+1348ff8
build0-gstfj-w-c-p9wl8.c.openshift-ci-build-farm.internal   Ready    worker   12d     v1.19.0+1348ff8
build0-gstfj-w-c-q7jkg.c.openshift-ci-build-farm.internal   Ready    worker   170m    v1.19.0+1348ff8
build0-gstfj-w-c-qtvg2.c.openshift-ci-build-farm.internal   Ready    worker   6d21h   v1.19.0+1348ff8
build0-gstfj-w-c-zsbvd.c.openshift-ci-build-farm.internal   Ready    worker   174m    v1.19.0+1348ff8
build0-gstfj-w-d-5wb76.c.openshift-ci-build-farm.internal   Ready    worker   5h18m   v1.19.0+1348ff8
build0-gstfj-w-d-h9drp.c.openshift-ci-build-farm.internal   Ready    worker   3d18h   v1.19.0+1348ff8
build0-gstfj-w-d-m54xt.c.openshift-ci-build-farm.internal   Ready    worker   12m     v1.19.0+1348ff8
build0-gstfj-w-d-p2md7.c.openshift-ci-build-farm.internal   Ready    worker   12m     v1.19.0+1348ff8
build0-gstfj-w-d-pms49.c.openshift-ci-build-farm.internal   Ready    worker   4h22m   v1.19.0+1348ff8
build0-gstfj-w-d-wclmw.c.openshift-ci-build-farm.internal   Ready    worker   4h22m   v1.19.0+1348ff8
```

**Comment by hongkailiu** [comment]
Checked several new VMs: 600G is used (after the manual fix below).
Screen Shot 2020-12-07 at 11 58 21 AM

Applied to many fields:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-openshift-release-master-build02-apply/1335972935520751616

Fixed by removing the last-modified annotation and apply the file with the replica value (to generate the annotation), and apply the file without it (it then becomes 1: might be related to [a bug fix](https://bugzilla.redhat.com/show_bug.cgi?id=1820654)), afterwards, autoscaler takes control of the value.

`build0-gstfj-w-c-zsbvd.c.openshift-ci-build-farm.internal` became `NotReady` and fixed by resetting it on the GCP console.

**Pull request merged**
