### PR TITLE
add periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.17

### PR DESCRIPTION
**Pull request by amp-rh**
See [INTEROP-7452](https://issues.redhat.com/browse/INTEROP-7452)

### CODE REVIEW

**Comment by amp-rh** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.17-stage-jaeger-stage-tests

**Comment by amp-rh** [comment]
rehearsals-ack

**Review by calebevans — APPROVED** [review]
/lgtm

**Review by iblancasa — APPROVED** [review]

**Comment by IshwarKanse** [comment]
@amp-rh Hi, you need to add an interop job which tests the released Jaeger operator version with OCP 4.17. The job config that you are adding is for stage testing, which is used for testing a pre-release operator version. You can refer the existing interop job configs for adding the 4.17 job. Refer the jobs which has interop in their name.

**Comment by IshwarKanse** [comment]
For Jaeger https://github.com/openshift/release/blob/master/ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.16-lp-interop.yaml

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.17-lp-interop-jaeger-interop-aws

**Pull request merged**
