### PR TITLE
WIP: [HCO] modify FBC index image

### PR DESCRIPTION
**Pull request by tiraboschi**

### CODE REVIEW

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-images

**Comment by nunnatsa** [comment]
Continuing here: #37371

**Comment by tiraboschi** [comment]
closing

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-images

**Pull request closed without merging**
