### PR TITLE
vSphere: temporarily remove gather bootstrap ip addressing

### PR DESCRIPTION
**Pull request by jcpowermac**
With the terraform change the state names also changed.
Will follow up with an alternative method of gathering
ip addressing.

### CODE REVIEW

**Comment by jcpowermac** [comment]
cc: @sdodson

**Comment by sdodson** [comment]
Won't the followup need to be compatible with both old and new given that this template is used across many versions/branches?

**Comment by jcpowermac** [comment]
Yep.  The idea I was just thinking about is to use `govc` and grab the ip from vmtools.

**Pull request merged**
