### PR TITLE
Add tide to tektoncd-cli

### PR DESCRIPTION
**Pull request by chmouel**

### CODE REVIEW

**Comment by chmouel** [comment]
@stevekuznetsov thanks for the review, we have the plugin already : 

https://github.com/openshift/release/blob/master/cluster/ci/config/prow/plugins.yaml#L323-L324

and I am not sure what do you mean by enable it on master and release-xx any chances you can point it out to wherver it's need to be updated? thanks

**Comment by alanfx** [comment]
Hey @chmouel Looks great!
/lgtm

**Pull request merged**
