### PR TITLE
ComplianceAsCode: Switch jobs to OCP 4.9

### PR DESCRIPTION
**Pull request by JAORMX**
Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>

### CODE REVIEW

**Comment by jhrozek** [comment]
Looks like we need to upgrade deps?
```
go: warning: k8s.io/client-go@v12.0.0+incompatible: retracted by module author: pre-module versions are obsolete
go: to switch to the latest unretracted version, run:
	go get k8s.io/client-go@latest{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-06-15T06:46:02Z"}
error: failed to execute wrapped command: exit status 1
```

**Comment by JAORMX** [comment]
@jhrozek yep... looks like it.

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 3edfe4e0215e38ba2b57827bf8d5cb2c547eed21

**Review by jhrozek — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
