### PR TITLE
[CIGolang]rebuild baseui

### PR DESCRIPTION
**Pull request by kuiwang02**
/cc @Xia-Zhao-rh 

cc @memodi @yapei

### CODE REVIEW

**Comment by memodi** [comment]
Thanks @kuiwang02, could you also change other release files changed in this PR: https://github.com/openshift/release/pull/50148

**Comment by kuiwang02** [comment]
> Thanks @kuiwang02, could you also change other release files changed in this PR: #50148

OK. thanks to reminder it.

**Comment by kuiwang02** [comment]
@memodi 
suppose https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm is updated repeatedly to point to the current stable version, so maybe it will be updated few months(1~2, I am not sure).

if we put it into baseui, it means we will check if it is updated and rebuild baseui image with PR. 
if we put it into ui, it could be rebuilt every time when we submit PR in tests-private repo. although it has few overlap, I think it is better than the above. so, I prefer it.

is it ok for you? thanks

**Comment by memodi** [comment]
Yeah, no worries. I had thought about including in test-private-ui but I thought it would be too much to download chrome every time this image is built, so I included in baseui but I didn't know the limitation of baseui at the time that it would not built/promoted routinely.

**Comment by kuiwang02** [comment]
> Yeah, no worries. I had thought about including in test-private-ui but I thought it would be too much to download chrome every time this image is built, so I included in baseui but I didn't know the limitation of baseui at the time that it would not built/promoted routinely.

Thanks. lets go in this way currently.

**Comment by kuiwang02** [comment]
@memodi the tests pass. could you please add lgtm? thanks

**Review by memodi — APPROVED** [review]
/lgtm

**Pull request merged**
