### PR TITLE
enable-qe-catalogsource for e2e-console and e2e-aws

### PR DESCRIPTION
**Pull request by memodi**
Intention here to enable QE catalogSource, basically add [this "ref" ](https://github.com/openshift/release/tree/master/ci-operator/step-registry/enable-qe-catalogsource)for e2e-console test. Please let me know if this is not correct way as I am still learning about ci-operator.

My previous PR #35623 was probably for incorrect file which got overwritten by bot.

### CODE REVIEW

**Comment by kuiwang02** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-e2e-console

**Comment by yapei** [comment]
looks good to me ~

**Pull request merged**
