### PR TITLE
Remove CustomResourcePublishOpenAPI tests from the minimal list

### PR DESCRIPTION
**Pull request by andfasano**
CustomResourcePublishOpenAPI tests appear to be flaky in 4.7 builds only

### CODE REVIEW

**Comment by andfasano** [comment]
cc @derekhiggins @bfournie

**Comment by derekhiggins** [comment]
@andfasano does removing them from these jobs from list mean they wont be run?

**Comment by andfasano** [comment]
> @andfasano does removing them from these jobs from list mean they wont be run?

Only for versions <= 4.7, where the minimal list of tests was used (we started addressing to run the whole parallel/serial suites only for versions >= 4.8)

**Review by bfournie — APPROVED** [review]

**Pull request merged**
