### PR TITLE
Disable no-feature-freeze labels for cluster monitoring operator

### PR DESCRIPTION
**Pull request by fpetkovski**
This commit disables the no-FF labels required to merge PRs for the
OpenShift cluster monitoring operator.

### CODE REVIEW

**Comment by simonpasquier** [comment]
/lgtm
/hold
@petr-muller if you remember we enabled the docs/qe/px approved labels for the cluster-monitoring-operator in #20653 because our team is part of the no-ff process. If we understand correctly, we need to undo the changes since 4.10 development is open now. Does the change look correct to you?

**Comment by petr-muller** [comment]
@simonpasquier I don't think this change is correct - noFF teams (as far as I'm informed) are supposed to have the same criteria even in this period: either bugs (for bugfixes) or approvals (for features).

**Comment by simonpasquier** [comment]
To my understanding, the approved labels are only required during the feature freeze period. Asking @bugenerali for clarification :)

**Comment by petr-muller** [comment]
I have these quotes by @bparees:

> Ben Parees  18:01
> @Petr Muller no-FF teams always need docs/px/qe acks to merge non-bug PRs
> Ben Parees  18:12
> @Petr Muller yeah, so for no-FF teams, FF doesn't exist, so nothing should change in their merge criteria when we hit FF.

**Comment by simonpasquier** [comment]
/close
oh right, re-reading the docs my assumption seems to be wrong. I'll check with Ben and Dan.

**Comment by bugenerali** [comment]
Hi @simonpasquier and @fpetkovski, for feature PRs, the no-FF teams would should adhere to the (px/docs/qe approval) rules throughout the release (not only after Feature Freeze), meaning that before 4.10 FF, your monitoring team will need px/docs/qe approval labels (in addition to "approved" and "lgtm" labels) for features. Thanks for tagging me!

**Pull request closed without merging**
