### PR TITLE
Update networking QE cherry pick approvers

### PR DESCRIPTION
**Pull request by mffiedler**
Add @gsr-shanks to the networking QE cherry pick approvers for all repos the team is responsible for.

### CODE REVIEW

**Comment by mffiedler** [comment]
@fedepaol @mandre @dcbw @pliurh Please approve QE cherry picker updates.

**Comment by fedepaol** [comment]
> @fedepaol @mandre @dcbw @pliurh Please approve QE cherry picker updates.

mind adding also metallb, metallb-operator and frr ?

**Pull request closed without merging**
