### PR TITLE
[maistra] Remove elasticsearch operator from test jobs

### PR DESCRIPTION
**Pull request by mkralik3**

### CODE REVIEW

**Comment by Sau1506mya** [comment]
@mkralik3 , the latest job for servicemesh operator on ROSA Classic is on OCP4.16, which is not updated yet.
`https://github.com/openshift/release/blob/master/ci-operator/config/maistra/maistra-test-tool/maistra-maistra-test-tool-main__servicemesh-ocp4.16-lp-rosa-classic.yaml`

**Review by FilipB — APPROVED** [review]

**Comment by mkralik3** [comment]
/pj-rehearse periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.16-lp-rosa-classic-servicemesh-rosa-aws periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.16-lp-interop-servicemesh-interop-aws periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.17-lp-interop-servicemesh-interop-aws

**Comment by mkralik3** [comment]
/pj-rehearse periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.16-lp-interop-servicemesh-interop-aws

**Comment by Sau1506mya** [comment]
@mkralik3 , we can ignore `ocp4.16-lp-interop` test as the latest job in each platform passed.
 We are good to merge this PR.

**Comment by mkralik3** [comment]
after our GA ( next week ) I need to upgrade the product version and some tests so if that cypress test is still failing, I will fix it as a part of that PR.

**Comment by Sau1506mya** [comment]
> /rehearsal-ack

@mkralik3 for adding `rehearsal-ack` we need to comment `/pj-rehearse ack`. I will do it for you now.

**Pull request merged**
