### PR TITLE
Configure the Submariner addon branch for ACM 2.13

### PR DESCRIPTION
**Pull request by tpantelis**

### CODE REVIEW

**Comment by tpantelis** [comment]
> I created the release-2.13 branch in the addon repository, let’s see if that fixes the rehearsals.

yeah I was wondering about that: "_fatal: couldn't find remote ref release-2.13_".

**Comment by skitt** [comment]
/lgtm
/approve

@tpantelis I’ll leave you to ack the pj rehearsals if the jobs succeed

**Pull request merged**
