### PR TITLE
AGENT-996: Create periodic jobs for 4&5 control plane nodes

### PR DESCRIPTION
**Pull request by rwsu**
The 4 control plane job also exercises the none platform.

The 5 control plane job also exercises PXE boot mode.

### CODE REVIEW

**Comment by rwsu** [comment]
/pj-rehearse
````
could not run steps: step [release:latest] failed: failed to get CLI image: unable to wait for the 'cli' image in the stable stream to populate (waited for 5m5.016549834s): timed out waiting for the condition 
````

**Review by pawanpinjarkar — COMMENTED** [review]
The prow job config looks good but the 5 control plane job never finished successfully. This is not related to the changes from this PR but needs to be looked into. @rwsu

**Comment by rwsu** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-agent-5control-ipv6-pxe-conformance

**Comment by bfournie** [comment]
As the 5 node control plane job was failing regularly it has been removed in https://github.com/openshift/release/pull/59972.
We may need to change the timeout for when the operators are available.

**Pull request merged**
