### PR TITLE
Revert "Alibaba: removal of master and 4.16 jobs"

### PR DESCRIPTION
**Pull request by jcpowermac**
This reverts commit 8037af56e3378ccfa0aa3d9c6b6761160cc60c76.

### CODE REVIEW

**Review by jmguzik — APPROVED** [review]

**Comment by stbenjam** [comment]
/hold

I don't think the error you're reporting from the release controller is actually fatal.  You just need a corresponding PR to ocp-build-data to remove the ART side of things.

**Comment by stbenjam** [comment]
CI payloads are broken

https://amd64.ocp.releases.ci.openshift.org/releasestream/4.16.0-0.ci/release/4.16.0-0.ci-2023-12-14-105222

I guess we can revert this until we get all the neccessary PR's staged to merge in one go

/hold cancel

**Pull request merged**
