### PR TITLE
Add e2e-nutanix job to the CCCMO repo.

### PR DESCRIPTION
**Pull request by lobziik**
Due to the plans to add nutanix integration there:

xref: https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/201

### CODE REVIEW

**Comment by lobziik** [comment]
cc @JoelSpeed

**Comment by JoelSpeed** [comment]
Do we want to have this so that it only runs when Nutanix files are changed? Looks like it will pretty much always run as it is configured now

**Comment by lobziik** [comment]
Will this: https://github.com/openshift/release/pull/34375/files#diff-fc5310b98024d08c8061371a7603559e1d4fbc6f95d1c8e700f624c3a9e6ee06R745 prevent job from the automatic triggering?

Looking into doc, I would expect this job not be triggered for every pr: https://docs.ci.openshift.org/docs/how-tos/contributing-openshift-release/#tolerated-changes-to-generated-jobs

**Comment by JoelSpeed** [comment]
Check against the CPMS jobs, but I think you need `run_if_only_changed` instead. My understanding is that you can't have `always_run` and `skip_if_only_chaged` together, so yes, `always_run` is false, but that's because it will skip based on the regex

**Comment by JoelSpeed** [comment]
I would suggest at the very minimum `run_if_changed: .*nutanix.*` so that when we know it's definitely nutanix related it will run automatically

**Review by elmiko — COMMENTED** [review]
/lgtm

**Comment by lobziik** [comment]
/pj-rehearse ack

This job is flaky because monitoring-related prometheus is not able to spin up for some reason. But cluster bootstrap is finishing, which we are basically interesting in.

**Pull request merged**
