### PR TITLE
merge automation for janus-idp/{backstage-showcase, backstage-plugins, software-templates, operator, helm} repos

### PR DESCRIPTION
**Pull request by kadel**
- add janus-idp/{backstage-showcase, backstage-plugins, software-templates, operator, helm} repos 
- creates org level `_pluginconfig.yaml` and removes repo specific config for showcase-e2e repo

### CODE REVIEW

**Comment by kadel** [comment]
@deepsm007 @hongkailiu can you please look into this

**Review by droslean — APPROVED** [review]

**Pull request merged**
