### PR TITLE
ROX-21124: Move non-e2e testing OSCI scanner release branch jobs to GitHub Actions

### PR DESCRIPTION
**Pull request by BradLugo**
Related to https://github.com/stackrox/scanner/pull/1376.

### CODE REVIEW

**Comment by BradLugo** [comment]
This PR removes the release branch jobs from all config files. Let me know if you'd like these changes to be split up into different PRs.

**Comment by BradLugo** [comment]
Looks like all these jobs are going to continue to fail during rehearsal due to the name limitation in gke and how we extract a name from the OSCI job name. Not sure a great way to test this

**Comment by RTann** [comment]
hopefully https://github.com/openshift/release/pull/47942 helps simplify this a bit

**Review by RTann — COMMENTED** [review]
Going to ignore everything that isn't 2.28, 2.31, and 2.32 (see https://github.com/openshift/release/pull/47942). Also ignoring the `jobs/` since those are generated

**Pull request closed without merging**
