### PR TITLE
Fixing openshift-kuryr-kubernetes-master.yaml to use dockerfile from ocp-build-data

### PR DESCRIPTION
**Pull request by alvaroaleman**

### CODE REVIEW

**Comment by dulek** [comment]
@alvaroaleman: That won't work because Kuryr builds an RPM first and repo that's supposed to serve that RPM is disabled by default when injected by ci-operator. I was to fix it in ci-tools#221, but got hard pushback there. The workaround to use `--enablerepo` won't work either because for OCP builds the `built` repository is not injected, so command will fail.

**Comment by dulek** [comment]
And why aren't rehearsal jobs running on this PR?

**Comment by alvaroaleman** [comment]
@dulek this pr is autogenerated and syncs the dockerfile configured in ocp-build-data, in the future these will get automerged, see http://post-office.corp.redhat.com/archives/aos-devel/2020-August/msg00110.html

If that Dockerfile is wrong, you need to update your components configuration in the ocp-build-data repo

**Comment by dulek** [comment]
> @dulek this pr is autogenerated and syncs the dockerfile configured in ocp-build-data, in the future these will get automerged, see http://post-office.corp.redhat.com/archives/aos-devel/2020-August/msg00110.html
> 
> If that Dockerfile is wrong, you need to update your components configuration in the ocp-build-data repo

The other file won't work on OCP as it works differently (the Kuryr RPMs built there is simply in the OCP repos already, here they're in a separate repository called `built`, which is running in pods on the build cluster itself). What merging this will break is that with a build we'll get Kuryr RPM from latest puddle, not the one that's being built from the PR.

Can we resolve this somehow before Friday, but not merge it today? I'm open for any solution to the issue, I even proposed one myself in openshift/ci-tools#221.

And if you wonder why only here this is a problem - we're probably the only ones building RPM and then an image from it.

**Comment by alvaroaleman** [comment]
@dulek why are they in a separate repo on the cluster? According to https://github.com/openshift/ci-tools/pull/221#issuecomment-543810985 this should be fixable by checking if the `build` repo exists and only enabling it if it does

**Comment by dulek** [comment]
openshift/kuryr-kubernetes#316 should help with this, but I'm not happy in putting a workaround where it's not needed.

**Comment by dulek** [comment]
> @dulek why are they in a separate repo on the cluster? According to [openshift/ci-tools#221 (comment)](https://github.com/openshift/ci-tools/pull/221#issuecomment-543810985) this should be fixable by checking if the `build` repo exists and only enabling it if it does

Ah, I forgot to answer your first question. Basically how OKD or ci-operator-based builds with RPMs work is that they spawn pods that do various tasks. One of them is to build the RPM using specified script and the code. That RPM (actually full RPM repo) is then taken and put into pods that host it and are exposed as a Service. Then an image is built that will have `built.repo` file pointing to that Service in `/etc/yum.repos.d`. Then, using that container as a base, the regular containers that should have access to freshly built RPMs are created. The only issue is that for some unknown reason `built.repo` had `enabled=0` line, meaning that you explicitly need to enable it in order for it to be used, and that's what differentiates openshift-kuryr-*-ci-rhel8 from openshift-kuryr-*-rhel8 Dockerfiles.

Right now I discovered that due to some unrelated changes this approach doesn't work either and wrong RPM is used in builds anyway, so I guess I'll just give this a push and deal with both problems next on.

**Pull request merged**
