### PR TITLE
Add e2e-ovirt presubmits to cluster-api-provider-ovirt

### PR DESCRIPTION
**Pull request by rgolangh**

### CODE REVIEW

**Comment by rgolangh** [comment]
@petr-muller will the master job I created be copied automatically to 4.5 and 4.6 or should I created those too?

**Comment by petr-muller** [comment]
> will the master job I created be copied automatically to 4.5 and 4.6 or should I created those too?

@rgolangh It will be copied to 4.5, no need to do anything.

**Comment by petr-muller** [comment]
/uncc 

This needs a review by someone in cluster-api-provider-ovirt

**Comment by rgolangh** [comment]
@petr-muller I am the cluster-api-provider-ovirt owner

**Comment by petr-muller** [comment]
What I meant by that is that someone related to the project needs to give a `/ltgm`, not us (DPTP). And not you, because you are the author :). Unfortunately the bot asked us because https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/cluster-api-provider-ovirt/OWNERS only contains you, so it went up and asked as as higher-level OWNERS in repo.

**Comment by rgolangh** [comment]
@petr-muller so how do we proceed? who needs to lgtm this then?

**Comment by petr-muller** [comment]
@rgolangh Anyone can `/lgtm`, ideally someone from your team. Who would review your PRs to the target repo?

**Pull request merged**
