### PR TITLE
OSSM maistra profile workflow update worker node type

### PR DESCRIPTION
**Pull request by yxun**

### CODE REVIEW

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-3.0-integ-pilot-3-0

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-operator-maistra-3.0-integration-kind

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-integ-pilot-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.5-integ-pilot-2-5

**Comment by jwendell** [comment]
/pj-rehearse pull-ci-maistra-istio-operator-maistra-3.0-integration-kind

**Comment by jwendell** [comment]
/pj-rehearse pull-ci-maistra-istio-operator-maistra-3.0-integration-ocp

**Review by jwendell — APPROVED** [review]

**Pull request merged**
