### PR TITLE
Add slack message for single-node 4.11 jobs

### PR DESCRIPTION
**Pull request by omertuc**

### CODE REVIEW

**Review by osherdp — APPROVED** [review]

**Comment by DennisPeriquet** [comment]
Just curious, ... is merge and watch the "single-node-ci channel" the only way to know if this works?

**Comment by omertuc** [comment]
I believe so, yes.
I think if the configuration was way off than some of the validation jobs running on this PR would've complained, but who knows

**Comment by DennisPeriquet** [comment]
ah, ok.  So we can just do a spot check in the channel, after merge, to confirm the messages are there. The fact that it's copy paste makes the approval easier. Thanks.

/lgtm

**Review by vrutkovs — APPROVED** [review]
/lgtm

**Pull request merged**
