### PR TITLE
Add tag by commit to rosa promoted image

### PR DESCRIPTION
**Pull request by enriquebelarte**
Adds commit tag to promoted image in rosa.

### CODE REVIEW

**Comment by ciaranRoche** [comment]
@enriquebelarte is there a JIRA for this change?

**Comment by enriquebelarte** [comment]
> @enriquebelarte is there a JIRA for this change?

Added comment to [existing](https://issues.redhat.com/browse/OCM-785) related task.

**Review by osherdp — APPROVED** [review]

**Comment by ciaranRoche** [comment]
@enriquebelarte you need to add `rehearsals-ack label` if you want this merged 

```
/pj-rehearse ack
```

**Comment by ciaranRoche** [comment]
i guess i could also add the ack :smile:

**Pull request merged**
