### PR TITLE
MGMT-18378 - adding LVM resources, default storage for CNV

### PR DESCRIPTION
**Pull request by eifrach**
-  above 4.12 for SNO, 4.15 for multi node - CNV should use LVM by default. ( fixed in [PR#6645](https://github.com/openshift/assisted-service/pull/6645) )
- Adding resources for LVM

### CODE REVIEW

**Comment by eifrach** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-cnv-4-16

**Review by adriengentil — APPROVED** [review]
/hold

**Pull request merged**
