### PR TITLE
CMA: Perform pre/post test setup/tear-down in E2E

### PR DESCRIPTION
**Pull request by joelsmith**

### CODE REVIEW

**Comment by joelsmith** [comment]
Waiting for https://github.com/openshift/kedacore-keda/pull/23 to merge prior to running the `pj-rehearse` job.

**Comment by joelsmith** [comment]
/pj-rehearse pull-ci-openshift-custom-metrics-autoscaler-operator-main-cma-e2e-aws-ovn

**Comment by joelsmith** [comment]
Though the test failed, it showed that it correctly ran the setup phase. Unfortunately the test can't pass here running against the main branch since the operand E2E tests are expecting KEDA 2.12+ and the operator only has 2.11+. However, I think it made it far enough to give us confidence that this commit is right (or at least, heading in the right direction).

/pj-rehearse ack

**Comment by jkyros** [comment]
Yep, sounds good :smile: 
/lgtm

**Pull request merged**
