### PR TITLE
switch to gcp-opendatahub cluster profile

### PR DESCRIPTION
**Pull request by riprasad**

### CODE REVIEW

**Comment by riprasad** [comment]
/pj-rehearse pull-ci-opendatahub-io-kubeflow-master-odh-notebook-controller-e2e

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve

thank you for this work :100:

**Comment by riprasad** [comment]
@harshad16
You've given approval to the pull request, but there are failed end-to-end (e2e) tests. Is this expected?

**Comment by harshad16** [comment]
> You've given approval to the pull request, but there are failed end-to-end (e2e) tests. Is this expected?
no it was not expected, however we can take a look , if this doesn't work on our repos.

**Pull request merged**
