### PR TITLE
update ocs-metrics-exporter build context

### PR DESCRIPTION
**Pull request by umangachapagain**

### CODE REVIEW

**Comment by umangachapagain** [comment]
/pj-rehearse pull-ci-red-hat-storage-ocs-operator-release-4.15-images	pull-ci-red-hat-storage-ocs-operator-main-images pull-ci-red-hat-storage-ocs-operator-main-ocs-operator-bundle-e2e-aws

**Comment by umangachapagain** [comment]
/pj-rehearse pull-ci-red-hat-storage-ocs-operator-release-4.15-images pull-ci-red-hat-storage-ocs-operator-main-images

**Comment by umangachapagain** [comment]
/pj-rehearse pull-ci-red-hat-storage-ocs-operator-main-images

**Review by iamniting — APPROVED** [review]

**Pull request merged**
