### PR TITLE
add e2e-cmd jobs to oc, openshift-apiserver repositories

### PR DESCRIPTION
**Pull request by sallyom**
Adding test-cmd to openshift/oc and openshift/openshift-apiserver

### CODE REVIEW

**Comment by sallyom** [comment]
test-cmd error: 
```
FAILURE after 0.000s: test/cmd/policy-storage-admin.sh:24: executing 'oc policy can-i --as=storage-adm get pods --all-namespaces' expecting success and text 'no': the output content test failed
Standard output from the command:
yes
``` 
hopefully this will fix: https://github.com/openshift/origin/pull/23622

**Comment by deads2k** [comment]
/lgtm
/hold

hold for green or at least closer

**Comment by soltysh** [comment]
This is blocked by https://github.com/openshift/origin/pull/23649 currently

**Comment by soltysh** [comment]
@sallyom the only failures are coming from 4.3 branches, I don't think we need to care about those atm, do we? I'd say we should merge this as soon as 4.3 master opens and work out whatever blocks as then. I don't want to mess with people trying to merge 4.2 fixes atm.

**Comment by sallyom** [comment]
> @sallyom the only failures are coming from 4.3 branches, I don't think we need to care about those atm, do we? I'd say we should merge this as soon as 4.3 master opens and work out whatever blocks as then. I don't want to mess with people trying to merge 4.2 fixes atm.

I had already started a `/ retest` before I saw this comment.  Yes, all rehearse jobs were green except 4.3 oc/oas e2e-cmd  and master/oc e2e-cmd was red.  I'll see where we're at with this next retest.

**Comment by sallyom** [comment]
4.3 branch e2e-cmd jobs created in separate PR, [here](https://github.com/openshift/release/pull/4920).  Will merge this first, then clear issues with 4.3 after.

**Comment by tnozicka** [comment]
I think you need to manually delete namespace `ci-op-d2fikw43` on api.ci to unstuck cached failed builds

**Pull request merged**
