### PR TITLE
ci-operator/jobs: Remove scaleup-rhel7 from 4.1 and 4.2 jobs

### PR DESCRIPTION
**Pull request by mtnbikenc**
4.1 and 4.2 are EOL and do not require test jobs for scaleup-rhel7

### CODE REVIEW

**Review by ashcrow — APPROVED** [review]
Changes look good to me.

**Comment by mtnbikenc** [comment]
@stevekuznetsov ping

**Comment by mtnbikenc** [comment]
Not pursuing this anymore.

**Pull request closed without merging**
