### PR TITLE
Fix a mistaken context_dir path in opendatahub-io notebook image definitions

### PR DESCRIPTION
**Pull request by jiridanek**

### CODE REVIEW

**Comment by jiridanek** [comment]
The observed ci fail is from another inconsistency, trustyai has only ubi9 directory in the main branch of the notebooks repo, there is not ubi8

```
error: error copying source path /go/src/github.com/opendatahub-io/notebooks/jupyter/trustyai/ubi8-python-3.8/. to .: exit status 1
```

**Review by harshad16 — COMMENTED** [review]
Super great find
i totally missed this review.
now i wonder , how are the rest of the image even getting build, the rocm-tensorflow and rocm-pytorch.

anyhow `make jobs` comment needs to be ran to complete this pr.

**Comment by jiridanek** [comment]
I did the last trustyai change on train from my phone, so I couldn't run make jobs then. Sorry about that.

**Comment by jiridanek** [comment]
The rehearsals show that the situation regarding ocp-ci builds has been improved and we no longer get build failures on missing image definitions, only on out-of-resource conditions. Let's merge this, shall we?

/pj-rehearse ack

**Comment by jiridanek** [comment]
> Super great find i totally missed this review. now i wonder , how are the rest of the image even getting build, the rocm-tensorflow and rocm-pytorch.

It's cheating

```
- context_dir: jupyter/datascience/ubi9-python-3.9
  dockerfile_path: Dockerfile
  from: jupyter-minimal-ubi9-python-3.9
  to: jupyter-datascience-ubi9-python-3.9
```

```
- context_dir: jupyter/rocm/tensorflow/ubi9-python-3.9
  dockerfile_path: Dockerfile
  from: jupyter-datascience-ubi9-python-3.9
  to: rocm-jupyter-tensorflow-ubi9-python-3.9
```

It makes a rocm- image without actually `dnf install rocm`. The GitHub actions built images are built properly in this respect. We should probably generate this section of the yaml from the makefile, same as is done for github actions, to avoid mistakes like this.

**Pull request merged**
