### PR TITLE
ci-operator/config/openshift: Decouple Cincinnati ecosystem from OpenShift branching

### PR DESCRIPTION
**Pull request by wking**
graph-data only has a development branch.  Cincinnati and its operator recently pivoted to a similar model, [releasing an OpenShift Update Service 5.0 on 2022-08-03][0] based on the master branches.  This commit rips out all the old release-* stuff, and also:

* Drops `releases` in favor of cluster claims [1], because we are decoupled from the OpenShift core and do not need to install a fresh cluster for our testing.

* Drops `promotion`.  We'd already had most of our images in `exclude_images`, so not much change in terms of actually-promoted images.  But dropping the promotion property [opts us out of OpenShift branching][2].

[0]: https://access.redhat.com/errata/RHEA-2022:5871
[1]: https://docs.ci.openshift.org/docs/architecture/ci-operator/#testing-with-a-cluster-from-a-cluster-pool
[2]: https://docs.ci.openshift.org/docs/architecture/branching/#how-do-i-opt-my-repository-into-automated-branching

### CODE REVIEW

**Comment by PratikMahajan** [comment]
looks like we need to fix cincinnati tests before merging this PR

**Comment by wking** [comment]
Hmm, yeah, [both][1] [have][2] `no matches for kind "Template" in version "v1"`.  But we've had v1 Templates [for years][3].  Ah, but our `apiVersion` declarations like [this one][4] are missing the `template.openshift.io` group information.  Unclear to me why this pivot to cluster pools changes anything, but :shrug: I can try adding the group information...

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/31237/rehearse-31237-pull-ci-openshift-cincinnati-master-customrust-e2e/1557741650195779584
[2]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/31237/rehearse-31237-pull-ci-openshift-cincinnati-master-e2e/1557741650380328960
[3]: https://github.com/openshift/api/blame/72d2ca90c49733567a5530e42aece2e68bd709ea/template/install.go#L7-L11
[4]: https://github.com/openshift/cincinnati/blob/867409df7b05fa0ceeee45055a93d48a3e5adc08/dist/openshift/observability.yaml#L2-L3

**Comment by wking** [comment]
I've filed openshift/cincinnati#727, adding the group information to the Template `apiVersion`.

**Comment by wking** [comment]
openshift/cincinnati#727 merged.

/test pj-rehearse

**Comment by wking** [comment]
Looks like the next tweak we need is dropping all namespaces, to avoid:

```
AllNamespaces InstallModeType not supported, cannot configure to watch all namespaces
```

**Comment by wking** [comment]
openshift/cincinnati#728 will hopefully address the `AllNamespaces` issue.

**Comment by wking** [comment]
openshift/cincinnati#719 merged.

/retest

**Comment by wking** [comment]
[Two][1] [rehearsals][2] had:

    could not determine image pull spec for image stable:cincinnati-operator on step e2e-test

/hold

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/31237/rehearse-31237-pull-ci-openshift-cincinnati-operator-master-operator-e2e/1560752268779720704#1:build-log.txt%3A33
[2]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/31237/rehearse-31237-pull-ci-openshift-cincinnati-operator-master-operator-e2e-latest-osus/1560752269027184640#1:build-log.txt%3A35

**Comment by wking** [comment]
[graph-data e2e][1] hit a Quay 500.

/retest

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/31237/rehearse-31237-pull-ci-openshift-cincinnati-graph-data-master-e2e/1560796229279944704

**Review by PratikMahajan — APPROVED** [review]
/lgtm

**Comment by wking** [comment]
Oops, CI is green, so [this][1] is stale.

/hold cancel

[1]: https://github.com/openshift/release/pull/31237#issuecomment-1221189503

**Pull request merged**
