### PR TITLE
stolostron installer repos: add branch protection

### PR DESCRIPTION
**Pull request by ray-harris**
Signed-off-by: Ray Harris <raharris@redhat.com>

### CODE REVIEW

**Comment by JakobGray** [comment]
If this is merged how difficult will it be to push to a release branch if needed? I just used an action this morning that pushed to release 2.6 in mch-operator. Would that no longer work? 

We also have some junk branches that might end up becoming protected under these rules that we should delete first. For example: 
- https://github.com/stolostron/backplane-operator/tree/backplane-2.0-go1.18  
- https://github.com/stolostron/multiclusterhub-repo/tree/release-2.5-go1.18

**Comment by ray-harris** [comment]
I cleaned up all the `-go1.18` branches.

There's an option to allow specific actors (such as a github actions bot account) to bypass the PR requirement and push directly to a protected branch. Let me know what the username is and I'll add it.

**Comment by JakobGray** [comment]
There's https://github.com/stolostron/multiclusterhub-operator/commit/5568d40e429d14fa7c832da6245509c060bbb59e, https://github.com/stolostron/multiclusterhub-repo/commit/a3e3c39e439b9d9c4bb71e472398995052d00254, and https://github.com/stolostron/backplane-operator/commit/9042ac7546eb685522dc5ca633c76cf985224770

**Comment by ray-harris** [comment]
Pushed commit to let `web-flow` push to main, release-*, backplane-* branches in backplane-operator and multiclusterhub-operator.

**Pull request merged**
