### PR TITLE
Revert "Cincinnati: run rustfmt tests for Rust 1.45/1.44/1.43"

### PR DESCRIPTION
**Pull request by vrutkovs**
Reverts openshift/release#11170. Rust 1.45 is not yet merged

### CODE REVIEW

**Comment by steveeJ** [comment]
/lgtm cancel

Actually reverting to build01 cluster will break CI

**Comment by vrutkovs** [comment]
`ci/prow/ordered-prow-config` is still not happy with the cluster, although I generated it with `make update` :man_shrugging:

**Comment by vrutkovs** [comment]
/retest

https://github.com/openshift/release/pull/11438 should have fixed that

**Pull request merged**
