### PR TITLE
rename junit files

### PR DESCRIPTION
**Pull request by shakyav**

### CODE REVIEW

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-logging-interop-ocp-ci-main-hypershift-4.14-lp-rosa-hypershift-cluster-logging-operator-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-logging-interop-ocp-ci-main-hypershift-4.14-lp-rosa-hypershift-cluster-logging-operator-rosa-hypershift

**Review by anpingli — COMMENTED** [review]
/lgtm

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-logging-interop-ocp-ci-main-hypershift-4.14-lp-rosa-hypershift-cluster-logging-operator-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-logging-interop-ocp-ci-main-hypershift-4.15-lp-rosa-hypershift-cluster-logging-operator-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-logging-interop-ocp-ci-main-hypershift-4.14-lp-rosa-hypershift-cluster-logging-operator-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-logging-interop-ocp-ci-main-hypershift-4.14-lp-rosa-hypershift-cluster-logging-operator-rosa-hypershift

**Pull request merged**
