### PR TITLE
terraform-rhcs-rosa-classic(OCM-5973): rename from terraform-rhcs-rosa

### PR DESCRIPTION
**Pull request by nirarg**
Fixes: [OCM-5973](https://issues.redhat.com//browse/OCM-5973)

### CODE REVIEW

**Comment by nirarg** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-classic-main-images
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-classic-main-verify-format
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-classic-main-rosa-classic-public

**Comment by nirarg** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-classic-main-images pull-ci-terraform-redhat-terraform-rhcs-rosa-classic-main-verify-format pull-ci-terraform-redhat-terraform-rhcs-rosa-classic-main-rosa-classic-public

**Comment by nirarg** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-classic-main-images pull-ci-terraform-redhat-terraform-rhcs-rosa-classic-main-verify-format pull-ci-terraform-redhat-terraform-rhcs-rosa-classic-main-rosa-classic-public

**Review by enriquebelarte — APPROVED** [review]

**Review by bardielle — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
