### PR TITLE
SPLAT-657: ipi/aws-local-zones: increase zone coverage in opted-out zones

### PR DESCRIPTION
**Pull request by mtulio**
AWS is constantly adding new locations in Local Zones, we need to test it to prevent unwanted scenarios in features we are declaring supported. It will also not increase the cost of the test as it is selecting randomly one single zone.

https://github.com/openshift/enhancements/pull/1232

Increasing the zone coverage by setting the flag `--all-availability-zones` to show zones which are not yet opted-in - the installer must opt-in when creating the cluster and that zone name is set in install-config.yaml:

- `us-east-1` in CI account without the flag `--all-availability-zones`
```bash
$ AWS_PROFILE=aws-local-zones aws ec2 describe-availability-zones  --region us-east-1  --filters Name=state,Values=available Name=zone-type,Values=local-zone --query 'AvailabilityZones[].ZoneName' | jq -r .[]
us-east-1-lim-1a
us-east-1-msp-1a
us-east-1-qro-1a
```

- `us-east-1` in CI account with the flag `--all-availability-zones`
```bash
$ AWS_PROFILE=aws-local-zones aws --region us-east-1 ec2 describe-availability-zones --all-availability-zones --filter Name=state,Values=available Name=zone-type,Values=local-zone | jq -r '.AvailabilityZones[].ZoneName' 
us-east-1-atl-1a
us-east-1-bos-1a
us-east-1-bue-1a
us-east-1-chi-1a
us-east-1-dfw-1a
us-east-1-iah-1a
us-east-1-lim-1a
us-east-1-mci-1a
us-east-1-mia-1a
us-east-1-msp-1a
us-east-1-nyc-1a
us-east-1-phl-1a
us-east-1-qro-1a
us-east-1-scl-1a

```

- `us-west-2` in CI account without the flag `--all-availability-zones`
```bash
$ AWS_PROFILE=aws-local-zones aws --region us-west-2 ec2 describe-availability-zones  --filter Name=state,Values=available Name=zone-type,Values=local-zone | jq -r '.AvailabilityZones[].ZoneName' 
us-west-2-las-1a
us-west-2-sea-1a

```

- `us-west-2` in CI account with the flag `--all-availability-zones`
```bash
$ AWS_PROFILE=aws-local-zones aws --region us-west-2 ec2 describe-availability-zones --all-availability-zones --filter Name=state,Values=available Name=zone-type,Values=local-zone | jq -r '.AvailabilityZones[].ZoneName' 
us-west-2-den-1a
us-west-2-las-1a
us-west-2-lax-1a
us-west-2-lax-1b
us-west-2-pdx-1a
us-west-2-phx-1a
us-west-2-sea-1a

```

### CODE REVIEW

**Comment by mtulio** [comment]
More improvements to increase the coverage in installer picking random zones even if it's not yet opted-in. Ref PR https://github.com/openshift/installer/pull/7137

For IPI owners, ptal?
@vrutkovs @patrickdillon @yunjiang29

**Comment by mtulio** [comment]
@vrutkovs would you mind taking a look? it's an small improvement in the zone query

**Comment by vrutkovs** [comment]
Why do we want to increase the coverage? This should be in commit message / PR description

**Comment by mtulio** [comment]
> Why do we want to increase the coverage? This should be in commit message / PR description

Updated.

That update is also also covered in the RFE for Local Zones.

**Comment by vrutkovs** [comment]
Oh, I see. I don't know the implications of using not-yet-supported zones, I'll leave it for Devan to approve. I don't think picking random zone is a good idea cost-wise tbh

**Comment by mtulio** [comment]
@vrutkovs - Thanks for sharing your thoughts.

> I don't know the implications of using not-yet-supported zones, I'll leave it for Devan to approve.

Which zone is not supported? We are declaring support for Local Zones in 4.12. If we'll not test in CI, we are not testing what we are declaring as supported to our customers.

> I don't think picking random zone is a good idea cost-wise tbh

What is the cost increase of getting static zone and random zone?[1][2] This suggestion was to prevent high costs from getting all zones in all tests (alongside increasing the total execution time, and risk for failures). The cost will increase almost 14x (in us-east-1) for each execution if we'll **not** pick one zone for each execution. Another cons of getting one static zone is we'll also not cover the customer scenario.

[1] https://github.com/openshift/enhancements/blob/master/enhancements/installer/aws-custom-edge-machineset-local-zones.md#infrastructure-costs
[2] https://aws.amazon.com/about-aws/global-infrastructure/localzones/pricing/

**Comment by mtulio** [comment]
Hi Yunfei, as you are familiar with Local Zones, could you please take a look too?
/assign @yunjiang29

**Comment by patrickdillon** [comment]
This LGTM but why skip the rehearsals? I would feel more confident with rehearsals. I think marco is out for the moment, so I'm going to go ahead and run them

/pj-rehearse

**Comment by mtulio** [comment]
> This LGTM but why skip the rehearsals? I would feel more confident with rehearsals. I think marco is out for the moment, so I'm going to go ahead and run them
> 
> /pj-rehearse

Thanks. Reason for skip:
The piece of the code that was changed is reachable only by the job `pull-ci-openshift-installer-master-e2e-aws-ovn-localzones` (or 4.14), which I think is expected to fail as the PR (https://github.com/openshift/installer/pull/7137) in the installer is still open. So I wouldn't allocate the infra cost for that small change.

PRs exercised the rehearsals when introducing this job:

- https://github.com/openshift/release/pull/40031
- https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/rehearse-40031-pull-ci-openshift-installer-master-e2e-aws-ovn
- https://prow.ci.openshift.org/pr-history/?org=openshift&repo=release&pr=40031

Here you can see the merged version of this change (job [`pull-ci-openshift-installer-master-e2e-aws-ovn-localzones`](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-installer-master-e2e-aws-ovn-localzones)) running in the installer's PR mentioned above:
https://prow.ci.openshift.org/pr-history/?org=openshift&repo=installer&pr=7137

**Comment by mtulio** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-aws-ovn-localzones

**Comment by mtulio** [comment]
> /pj-rehearse pull-ci-openshift-installer-master-e2e-aws-ovn-localzones

failed as expected (due the open PR): https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/40606/rehearse-40606-pull-ci-openshift-installer-master-e2e-aws-ovn-localzones/1674173677668667392#1:build-log.txt%3A129

zone selected:
```
- architecture: amd64
  name: edge
  platform:
    aws:
      zones: [us-east-1-lim-1a]
```

Triggering other tests which are more related to this change:
/pj-rehearse pull-ci-openshift-installer-master-e2e-aws-ovn
/pj-rehearse pull-ci-openshift-installer-master-e2e-aws-ovn-imdsv2
/pj-rehearse pull-ci-openshift-installer-master-e2e-aws-ovn-fips

**Comment by mtulio** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-aws-ovn-imdsv2

**Comment by mtulio** [comment]
Unrelated failure in the test ` [sig-api-machinery][Feature:ClusterResourceQuota] Cluster resource quota should control resource limits across namespaces [apigroup:quota.openshift.io][apigroup:image.openshift.io][apigroup:monitoring.coreos.com][apigroup:template.openshift.io] [Suite:openshift/conformance/parallel]`
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/40606/rehearse-40606-pull-ci-openshift-installer-master-e2e-aws-ovn/1674287909835902976

/pj-rehearse pull-ci-openshift-installer-master-e2e-aws-ovn

**Comment by mtulio** [comment]
> This LGTM but why skip the rehearsals? I would feel more confident with rehearsals. I think marco is out for the moment, so I'm going to go ahead and run them
> 
> /pj-rehearse

@patrickdillon what is the pass ratio of those jobs to get confidence in your PoV?

**Comment by patrickdillon** [comment]
> > This LGTM but why skip the rehearsals? I would feel more confident with rehearsals. I think marco is out for the moment, so I'm going to go ahead and run them
> > /pj-rehearse
> 
> @patrickdillon what is the pass ratio of those jobs to get confidence in your PoV?

Just a sanity check to make sure nothing is obviously broken. Is this an expected failure https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/40606/rehearse-40606-pull-ci-openshift-installer-master-e2e-aws-ovn-localzones/1674173677668667392

**Comment by mtulio** [comment]
> > > This LGTM but why skip the rehearsals? I would feel more confident with rehearsals. I think marco is out for the moment, so I'm going to go ahead and run them
> > > /pj-rehearse
> > 
> > 
> > @patrickdillon what is the pass ratio of those jobs to get confidence in your PoV?
> 
> Just a sanity check to make sure nothing is obviously broken. Is this an expected failure https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/40606/rehearse-40606-pull-ci-openshift-installer-master-e2e-aws-ovn-localzones/1674173677668667392

@patrickdillon - Yes, expected fail preventing to install in non-existing VPC: `edge machine pool is valid when installing in existing VPC` (installer PR isn't in master, master supports only Phase I). [My comment](https://github.com/openshift/release/pull/40606#issuecomment-1612093842) has more details.

**Comment by mtulio** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-aws-ovn-fips

**Comment by mtulio** [comment]
- `e2e-aws-ovn` seems to be very flaky recently.
- `e2e-aws-ovn-fips` passing.

@patrickdillon can you see any blocker in this PR?

**Pull request merged**
