### PR TITLE
Change validate-portal and validate-asciidoc builds to be manual

### PR DESCRIPTION
**Pull request by aireilly**

### CODE REVIEW

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-deploy-preview

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-asciidoc

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-validate-portal

**Review by gabriel-rh — APPROVED** [review]
LGTM

**Pull request merged**
