### PR TITLE
NO-JIRA: fix: change workflow install for optional operators on SNO to match HA

### PR DESCRIPTION
**Pull request by eggfoobar**
We recently noticed an error in our CI tests on the SNO optional operator flow vs the regular flow. This was due to a mismatch between what the operator was being built with and what the payload was running. It turned out there is a difference in how the regular optional flow is being installed and how SNO is being installed, this makes sure that the install for SNO is similar to the HA version and no longer uses the stable payload which can be out of step with a presubmit build in terms of the underlying libraries

### CODE REVIEW

**Comment by eggfoobar** [comment]
/pj-rehearse pull-ci-openshift-lvm-operator-main-images pull-ci-openshift-lvm-operator-main-lvm-operator-e2e-aws pull-ci-openshift-lvm-operator-main-lvm-operator-e2e-aws-sno

**Comment by eggfoobar** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-release-1.11-hco-e2e-upgrade-prev-operator-sdk-sno-aws pull-ci-kubevirt-hyperconverged-cluster-operator-release-1.11-hco-e2e-operator-sdk-sno-aws pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-prev-operator-sdk-sno-aws pull-ci-kubevirt-hyperconverged-cluster-operator-release-1.11-hco-e2e-upgrade-operator-sdk-sno-aws pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-operator-sdk-sno-aws

**Comment by eggfoobar** [comment]
/pj-rehearse pull-ci-openshift-lvm-operator-main-images pull-ci-openshift-lvm-operator-main-lvm-operator-e2e-aws pull-ci-openshift-lvm-operator-main-lvm-operator-e2e-aws-sno

**Comment by eggfoobar** [comment]
/pj-rehearse pull-ci-openshift-lvm-operator-main-lvm-operator-e2e-aws-sno

**Comment by eggfoobar** [comment]
/pj-rehearse periodic-ci-openshift-lvm-operator-main-lvm-operator-e2e-aws-sno

**Review by tiraboschi — APPROVED** [review]

**Comment by eggfoobar** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-release-1.10-hco-e2e-operator-sdk-azure pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-azure

**Pull request merged**
