### PR TITLE
azure: remove resources stanzas

### PR DESCRIPTION
**Pull request by jim-minter**
@mjudeikis fyi

### CODE REVIEW

**Comment by jim-minter** [comment]
@ehashman fyi

**Comment by ehashman** [comment]
```
error loading configuration files: invalid configuration from openshift/openshift-azure/openshift-openshift-azure-master.yaml: invalid configuration: 'resources.*' should have at least one request or limit
```

Is there really no way to get best effort without doing something silly? (e.g. specifying a request but no limit like with our `cpu: 10m` solution)

**Comment by stevekuznetsov** [comment]
You don't want best effort. You do that and a) you don't get scheduled well then b) you get evicted

**Comment by mjudeikis** [comment]
> You don't want best effort. You do that and a) you don't get scheduled well then b) you get evicted

We started to get a lot of memory allocation errors with Burstable config. Somehow this eliminates this. But agreed, need to test and see how much more flakes we will see.

**Pull request merged**
