### PR TITLE
OCPBUGS-3206: Ensure node reboot in SDN migration script

### PR DESCRIPTION
**Pull request by pliurh**
Add retry logic to node reboot. Make sure all the nodes can be rebooted.

### CODE REVIEW

**Comment by pliurh** [comment]
@weliang1 Could you give this patch a try? See if it can fix the issue you found.

**Comment by weliang1** [comment]
> @weliang1 Could you give this patch a try? See if it can fix the issue you found.

@pliurh Both scripts works for vsphere cluster using latest 4.12 build.
/lgtmp

**Pull request merged**
