### PR TITLE
Adapt glance-operator test job to envtest

### PR DESCRIPTION
**Pull request by gibizer**

### CODE REVIEW

**Comment by gibizer** [comment]
We need a small fix to the makefile first https://github.com/openstack-k8s-operators/glance-operator/pull/240

**Comment by fmount** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-glance-operator-main-functional

**Review by fmount — APPROVED** [review]
+1 from me, however I suspect we need someone like @Sandeepyadav93 or @viroel to merge.

**Pull request merged**
