### PR TITLE
Symlink goimports in origin-release docker images

### PR DESCRIPTION
**Pull request by ingvagabund**
Fixes: https://github.com/openshift/ci-config/pull/43

### CODE REVIEW

**Comment by ingvagabund** [comment]
When building `origin-release/golang-1.8` I get:
```sh
Step 6 : RUN INSTALL_PKGS="golang-${VERSION}" &&     yum install -y $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum clean all &&     go get golang.org/x/tools/cmd/cover         golang.org/x/tools/cmd/goimports         github.com/tools/godep         github.com/golang/lint/golint         github.com/openshift/imagebuilder/cmd/imagebuilder &&     mv $GOPATH/bin/* /usr/bin/ &&     rm -rf $GOPATH/* &&     mkdir $GOPATH/bin &&     ln -s /usr/bin/imagebuilder $GOPATH/bin/imagebuilder
 ---> Running in 3d72db223ed4
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
 * base: mirror.karneval.cz
 * epel: mirror.karneval.cz
 * extras: mirror.karneval.cz
 * updates: mirror.karneval.cz
No package golang-1.8.3 available.
Error: Nothing to do
```

Since [1] has:
```
toplink/packages/golang/1.9.2/4.el7/x86_64/golang-bin-1.9.2-4.el7.x86_64.rpm
toplink/packages/golang/1.9.2/4.el7/x86_64/golang-1.9.2-4.el7.x86_64.rpm
toplink/packages/golang/1.9.2/4.el7/noarch/golang-src-1.9.2-4.el7.noarch.rpm
toplink/packages/golang/1.9.2/4.el7/noarch/golang-tests-1.9.2-4.el7.noarch.rpm
toplink/packages/golang/1.9.2/4.el7/noarch/golang-misc-1.9.2-4.el7.noarch.rpm
toplink/packages/golang/1.9.2/4.el7/noarch/golang-docs-1.9.2-4.el7.noarch.rpm
```

Well, is there any repo that provides golang-1.8.*?

[1] http://cbs.centos.org/kojifiles/repos/paas7-openshift-multiarch-el7-build/latest/x86_64/pkglist

**Comment by ingvagabund** [comment]
@stevekuznetsov @jcajka

**Comment by stevekuznetsov** [comment]
There should be one in https://cbs.centos.org/repos/paas7-openshift-origin37-candidate/x86_64/os/Packages/ but right now the version is wrong in there. We should be fixing that. /cc @sdodson

**Comment by smarterclayton** [comment]
The 1.8 release image needs to be updated to be like 1.10 (use the download and fake RPM setup).

**Comment by ingvagabund** [comment]
> The 1.8 release image needs to be updated to be like 1.10 (use the download and fake RPM setup).

Done.

Was able to build `docker.io/openshift/origin-release:golang-1.8` locally.

```sh
$ docker run -it docker.io/openshift/origin-release:golang-1.8 /bin/ls /go/bin
goimports  imagebuilder
```

**Comment by ingvagabund** [comment]
@stevekuznetsov PTAL

**Comment by ingvagabund** [comment]
After rebuilding all images:
```sh
$ docker run -it docker.io/openshift/origin-release:golang-1.8 /bin/ls /go/bin
goimports  imagebuilder
$ docker run -it docker.io/openshift/origin-release:golang-1.9 /bin/ls /go/bin
goimports  imagebuilder
$ docker run -it docker.io/openshift/origin-release:golang-1.10 /bin/ls /go/bin
goimports  imagebuilder
```

**Pull request merged**
