### PR TITLE
aws-load-balancer: pre-install-rosa - create unique WAF ACLs

### PR DESCRIPTION
**Pull request by alebedev87**
This PR tries to avoid sharing WAF ACLs between different PRs.

### CODE REVIEW

**Comment by DennisPeriquet** [comment]
/hold
/lgtm

The change makes sense. Unhold when ready to merge.

**Comment by alebedev87** [comment]
/pj-rehearse pull-ci-openshift-aws-load-balancer-operator-main-e2e-aws-rosa-operator

**Comment by alebedev87** [comment]
The classic WAF does not allow non alphanumeric characters in the name.

**Comment by alebedev87** [comment]
/pj-rehearse pull-ci-openshift-aws-load-balancer-operator-main-e2e-aws-rosa-operator

**Comment by alebedev87** [comment]
/pj-rehearse pull-ci-openshift-aws-load-balancer-operator-main-e2e-aws-rosa-operator

**Comment by alebedev87** [comment]
/pj-rehearse pull-ci-openshift-aws-load-balancer-operator-main-e2e-aws-rosa-operator

**Comment by alebedev87** [comment]
/pj-rehearse pull-ci-openshift-aws-load-balancer-operator-main-e2e-aws-rosa-operator

**Comment by alebedev87** [comment]
/pj-rehearse pull-ci-openshift-aws-load-balancer-operator-main-e2e-aws-rosa-operator

**Pull request merged**
