### PR TITLE
Add vsphere zonal for capi installer

### PR DESCRIPTION
**Pull request by jcpowermac**

### CODE REVIEW

**Comment by jcpowermac** [comment]
zonal for capv was broken and we didn't know.

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.16-altinfra-e2e-vsphere-capi-zones

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.16-altinfra-e2e-vsphere-capi-zones

**Comment by jcpowermac** [comment]
failing where expected requires 
https://github.com/openshift/installer/pull/8059
to at least install correctly

**Review by r4f4 — COMMENTED** [review]
/approve

**Pull request merged**
