### PR TITLE
openshift/okd-machine-os: drop machine-os-content reference

### PR DESCRIPTION
**Pull request by jlebon**
It's long been deprecated now and nothing should be relying on it anymore.

See also https://issues.redhat.com/browse/MCO-392.

### CODE REVIEW

**Comment by vrutkovs** [comment]
Needs `make openshift-image-mirror-mappings`, otherwise
/approve

/pj-rehearse pull-ci-openshift-okd-machine-os-release-4.16-e2e-aws-ovn

**Comment by LorbusChris** [comment]
okd-machine-os doesn't yet have a release-4.16 branch, so let's rehearse on master
/pj-rehearse pull-ci-openshift-okd-machine-os-master-e2e-aws-ovn

**Comment by jlebon** [comment]
Rebased!

**Comment by jlebon** [comment]
/pj-rehearse pull-ci-openshift-okd-machine-os-master-e2e-aws-ovn

**Review by vrutkovs — APPROVED** [review]
/lgtm
/rehearsals ack

Thanks!

**Pull request merged**
