### PR TITLE
Update openshift/kubernetes images to RHEL 9

### PR DESCRIPTION
**Pull request by bertinatto**

### CODE REVIEW

**Comment by bertinatto** [comment]
/pj-rehearse pull-ci-openshift-kubernetes-release-4.15-artifacts
/pj-rehearse pull-ci-openshift-kubernetes-release-4.15-integration
/pj-rehearse pull-ci-openshift-kubernetes-release-4.15-images

**Comment by bertinatto** [comment]
/pj-rehearse pull-ci-openshift-kubernetes-release-4.15-integration

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
