### PR TITLE
Add Calico e2e tests to 4.3 and 4.4 periodics

### PR DESCRIPTION
**Pull request by csrwng**
Per calico team request, adding periodic tests for 4.3 and 4.4 branches

### CODE REVIEW

**Comment by csrwng** [comment]
@smarterclayton ptal

**Comment by smarterclayton** [comment]
once the rehearse's return i'll tag it (poke me if i go radio silent)

**Comment by csrwng** [comment]
the rehearse test for 4.3 looks good, 4.4 never took off... retrying
/test pj-rehearse

**Comment by smarterclayton** [comment]
/lgtm

thanks

**Pull request merged**
