### PR TITLE
fix: update powermon operator e2e

### PR DESCRIPTION
**Pull request by vprashar2929**
This PR improves the way Kepler deployment name is retrieved

### CODE REVIEW

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-power-monitoring-operator-tech-preview-power-monitoring-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-power-monitoring-operator-tech-preview-power-monitoring-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-power-monitoring-operator-tech-preview-power-monitoring-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-power-monitoring-operator-tech-preview-power-monitoring-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-power-monitoring-operator-v1alpha1-power-monitoring-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-power-monitoring-operator-v1alpha1-power-monitoring-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-power-monitoring-operator-v1alpha1-power-monitoring-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-power-monitoring-operator-v1alpha1-power-monitoring-operator-e2e

**Review by IshwarKanse — APPROVED** [review]
/lgtm

**Review by IshwarKanse — APPROVED** [review]
/lgtm

**Pull request merged**
