### PR TITLE
fixing approve csrs shell script, previously it was exiting early

### PR DESCRIPTION
**Pull request by acornett21**

### CODE REVIEW

**Comment by acornett21** [comment]
/pj-rehearse pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.15-e2e pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.16-e2e pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.12-e2e

**Comment by acornett21** [comment]
/pj-rehearse periodic-ci-redhat-openshift-ecosystem-certified-operators-prod-ocp-4.13-preflight-prod-claim

**Comment by acornett21** [comment]
/pj-rehearse periodic-ci-redhat-openshift-ecosystem-certified-operators-prod-ocp-4.12-preflight-prod-claim periodic-ci-redhat-openshift-ecosystem-certified-operators-prod-ocp-4.14-preflight-prod-claim periodic-ci-redhat-openshift-ecosystem-certified-operators-prod-ocp-4.15-preflight-prod-claim periodic-ci-redhat-openshift-ecosystem-certified-operators-prod-ocp-4.16-preflight-prod-claim

**Comment by acornett21** [comment]
/pj-rehearse periodic-ci-redhat-openshift-ecosystem-certified-operators-prod-ocp-4.13-preflight-prod-claim

**Comment by acornett21** [comment]
/pj-rehearse periodic-ci-redhat-openshift-ecosystem-certified-operators-prod-ocp-4.12-preflight-prod-claim periodic-ci-redhat-openshift-ecosystem-certified-operators-prod-ocp-4.14-preflight-prod-claim periodic-ci-redhat-openshift-ecosystem-certified-operators-prod-ocp-4.15-preflight-prod-claim periodic-ci-redhat-openshift-ecosystem-certified-operators-prod-ocp-4.16-preflight-prod-claim

**Review by komish — APPROVED** [review]
/lgtm

**Pull request merged**
