### PR TITLE
Remove OCP 4.5 from serving next release

### PR DESCRIPTION
**Pull request by nak3**
As per title, this patch removes OCP 4.5 from serving next release since serverless-operator will target 4.6 (starting w/ 1.11).

/cc @markusthoemmes @mgencur

### CODE REVIEW

**Comment by nak3** [comment]
Umm... as per `generated-config` test, I should remove openshift-knative-serving-release-next-postsubmits.yaml ? :thinking:

**Review by markusthoemmes — APPROVED** [review]
/lgtm
/approve

**Comment by mgencur** [comment]
Please run `make jobs` and `make ci-operator-config` in the root dir of that repo. It should clean the jobs automatically.

**Comment by nak3** [comment]
@mgencur  Sure, I updated now. `openshift-knative-serving-release-next-postsubmits.yaml` was removed by the make commands. I hope it would be fine.

**Comment by markusthoemmes** [comment]
We need to enable image promotion in rhe 4.6 YAML. The postsubmit job should then stick around I think.

**Comment by nak3** [comment]
Thank you @markusthoemmes @mgencur . I found what I missed. I needed to add https://github.com/openshift/release/pull/13306/commits/f1f1b2cd12d06b9cc1e190bdce3f5d177684fe34 which had 4.5 yaml.

**Review by markusthoemmes — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
