### PR TITLE
[DPTP-1737] Migrate openshift-console release-* e2e tests to multi-stage

### PR DESCRIPTION
**Pull request by droslean**
/cc @openshift/openshift-team-developer-productivity-test-platform 

Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Were these automatically moved?

**Comment by droslean** [comment]
> Were these automatically moved?

I changed them manually.

**Comment by petr-muller** [comment]
```
determinize-ci-operator --config-dir ci-operator/config --enabled-template-migration=openshift_installer_src --template-migration-ceiling 100000 --confirm
```
gives the same resuls minus openshift-priv which will be synced automatically so this is fine

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
