### PR TITLE
Enabling lifecycle for openshift/odo

### PR DESCRIPTION
**Pull request by mohammedzee1000**
/cc @kadel
Signed-off-by: Mohammed Zeeshan Ahmed <mohammed.zee1000@gmail.com>

### CODE REVIEW

**Comment by petr-muller** [comment]
@mohammedzee1000 you need to add the repo to all three these jobs - you only added it to the one that closes rotten issues but nothing makes them rotten.

See https://github.com/openshift/release/pull/6436/files

**Comment by mohammedzee1000** [comment]
Thanks will take a look and raise another PR :)

**Comment by mohammedzee1000** [comment]
@petr-muller https://github.com/openshift/release/pull/6566

**Pull request merged**
