### PR TITLE
stolostron: Add 2.5 branch configuration for submariner-addon

### PR DESCRIPTION
**Pull request by skitt**
Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Comment by skitt** [comment]
The Sonar jobs are failing with variants of

    stat pkg/apis/submarinerconfig/v1alpha1: no such file or directory

which suggests that they are running somewhere other than the artifact’s base directory.

**Comment by skitt** [comment]
/cc @tpantelis 

As per https://github.com/stolostron/cicd-docs/blob/main/prow/new_release.md it’s OK for the rehearsal tests to fail.

**Review by tpantelis — APPROVED** [review]

**Pull request merged**
