### PR TITLE
Removed and Refactor the OSDe2e Pipelines to only contain the currently accepted

### PR DESCRIPTION
**Pull request by MrSantamaria**

### CODE REVIEW

**Comment by MrSantamaria** [comment]
/assign aweiteka
This is what I have in mind for our discussion today based on the pipeline focus.

**Comment by aweiteka** [comment]
+1 to intent of this PR. I can't sign-off on technical details.

Could you add description with which tests are being enabled/disabled?

**Comment by MrSantamaria** [comment]
This includes AWS, GCP, ROSA/STS, and ARO jobs for the default e2e-suite. 
Addon jobs have been left alone.

I'm also making some changes to our naming convention.
We were doing:
$env-$flavor
I'm changing it to:
$flavor-env

Mainly for readability, it was hard to read what was actually being covered.

Capturing the overall test here:
https://docs.google.com/spreadsheets/d/1V4NP6adpNd-1sZ-whG35op4l2eisV8eU5bgYJ3wUmcI/edit#gid=1498729427
After this PR goes through I'll update the Testgrid variables as well.

**Comment by cblecker** [comment]
@MrSantamaria Any of the jobs that can't/shouldn't be rehearsed, can we flip their `pj-rehearse.openshift.io/can-be-rehearsed` to false? (docs: https://docs.ci.openshift.org/docs/how-tos/contributing-openshift-release/#rehearsals)

**Comment by MrSantamaria** [comment]
@cblecker I chased this down as well with the dptp team:
https://coreos.slack.com/archives/CBN38N3MW/p1661269329857069

It seems we are not able to force a pj-rehearse false when using the prowgen.

**Pull request merged**
