### PR TITLE
Added pre-commit job for ironic operator

### PR DESCRIPTION
**Pull request by amolkahat**
Added ironic operator pre commit job

### CODE REVIEW

**Comment by Sandeepyadav93** [comment]
@amolkahat please run `make update` from root directory of openshift/release and it will create job definitions for you.

**Comment by amolkahat** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-ironic-operator-master-precommit-check

**Comment by amolkahat** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-ironic-operator-master-precommit-check

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-ironic-operator-master-precommit-check

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-ironic-operator-master-precommit-check

**Comment by amolkahat** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-ironic-operator-master-precommit-check

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-ironic-operator-master-precommit-check

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-ironic-operator-master-precommit-check

**Comment by bshewale** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-ironic-operator-master-precommit-check

**Pull request merged**
