### PR TITLE
Change  region for release-service-catalog repo

### PR DESCRIPTION
**Pull request by jinqi7**

### CODE REVIEW

**Comment by jinqi7** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests-periodic

**Review by happybhati — APPROVED** [review]
/lgtm
/approve

**Comment by mmalina** [comment]
@jinqi7 why this change? Do you expect that this will improve performance? Or any other reason?

**Comment by jinqi7** [comment]
> @jinqi7 why this change? Do you expect that this will improve performance? Or any other reason?

I tried to workaround the schedule issue. The server types are the same in the two pools.

**Comment by mmalina** [comment]
> > @jinqi7 why this change? Do you expect that this will improve performance? Or any other reason?
> 
> I tried to workaround the schedule issue. The server types are the same in the two pools.

Ok. But it didn't really help, right...

**Pull request merged**
