### PR TITLE
stackrox: bump openshift versions

### PR DESCRIPTION
**Pull request by gavin-stackrox**
/cc @msugakov @porridge @janisz 
/hold

### CODE REVIEW

**Comment by porridge** [comment]
- https://github.com/stackrox/stackrox/pull/4774 addresses the PSP-related failures in operator e2e tests

**Comment by porridge** [comment]
re-running tests now that PSP fix is merged.

/pj-rehearse max

**Comment by porridge** [comment]
```
NAME                          READY   STATUS             RESTARTS       AGE     IP            NODE                           NOMINATED NODE   READINESS GATES
central-6958cc7f6b-hn5k5      0/1     CrashLoopBackOff   5 (101s ago)   5m14s   10.128.2.24   ip-10-0-169-171.ec2.internal   <none>           <none>
```

```
Migrator: 2023/02/08 10:40:33.642316 log.go:18: Info: Migrator failed: unable to get Postgres DB config: pgsql: could not load password file "/run/secrets/stackrox.io/db-password/password": open /run/secrets/stackrox.io/db-password/password: no such file or directory
```

- I believe this is being addressed in https://github.com/stackrox/stackrox/pull/4767 so I'd wait for that one to be merged and retry, as otherwise we have no idea whether the openshift bump broke something..

**Review by janisz — APPROVED** [review]

**Pull request merged**
