### PR TITLE
CVP common: add AWS Load Balancer Operator's custom objects

### PR DESCRIPTION
**Pull request by alebedev87**
This PR adds the custom Kubernetes objects for AWS Load Balancer Operator.

### CODE REVIEW

**Comment by alebedev87** [comment]
/pj-rehearse periodic-ci-redhat-openshift-ecosystem-cvp-ocp-4.12-cvp-common-claim

**Comment by alebedev87** [comment]
/pj-rehearse periodic-ci-redhat-openshift-ecosystem-cvp-ocp-4.12-cvp-common-claim

**Comment by alebedev87** [comment]
/pj-rehearse

It may take more for the vault sync to take place but let's give it a try.

**Comment by alebedev87** [comment]
/pj-rehearse periodic-ci-redhat-openshift-ecosystem-msp-osd-4.11-aws-msp-osd-4-11

**Comment by alebedev87** [comment]
/pj-rehearse periodic-ci-redhat-openshift-ecosystem-cvp-ocp-4.7-cvp-common-aws

**Comment by dirgim** [comment]
/pj-rehearse periodic-ci-redhat-openshift-ecosystem-msp-osd-4.11-aws-msp-osd-4-11

**Comment by asergienk** [comment]
the changes look good to me, it seems like they cannot be tested with the rehearsals jobs because those jobs test the "e2e-test-operator" package, therefore "optional-operators-cvp-common-apply-secrets" artifacts output is not helpful to us:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/40377/rehearse-40377-periodic-ci-redhat-openshift-ecosystem-msp-ocp-4.10-medium-single-az-amd64-aws/1670766789711106048/artifacts/medium-single-az-amd64-aws/optional-operators-cvp-common-apply-secrets/build-log.txt

@nmars ptal

**Comment by nmars** [comment]
/pj-rehearse periodic-ci-redhat-openshift-ecosystem-msp-osd-4.11-aws-msp-osd-4-11

**Pull request closed without merging**
