### PR TITLE
Inject cli from release:target for cert rotation test

### PR DESCRIPTION
**Pull request by wangke19**
Associated Jira issue: https://issues.redhat.com/browse/OCPQE-22645

### CODE REVIEW

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-gcp-ipi-oidc-rt-fips-regen-cert-f14

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-gcp-ipi-oidc-rt-fips-regen-cert-f14

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-gcp-ipi-oidc-rt-fips-regen-cert-f14

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-gcp-ipi-oidc-rt-fips-regen-cert-f14

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-gcp-ipi-oidc-rt-fips-regen-cert-f14

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-gcp-ipi-oidc-rt-fips-regen-cert-f14

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-gcp-ipi-oidc-rt-fips-regen-cert-f14

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-gcp-ipi-oidc-rt-fips-regen-cert-f14

**Comment by wangke19** [comment]
/pj-rehearse  periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-azure-ipi-des-fips-regen-cert-f14

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-aws-ipi-byo-iam-role-regen-cert-f14

**Comment by wangke19** [comment]
Checked the step  openshift-e2e-test-qe-regenerate-cluster-cert of test jobs all were passed as expected.
```
INFO[2024-06-14T06:49:33Z] Step gcp-ipi-oidc-rt-fips-regen-cert-f14-openshift-e2e-test-qe-regenerate-cluster-cert succeeded after 2h0m47s. 
INFO[2024-06-14T11:19:08Z] Step aws-ipi-byo-iam-role-regen-cert-f14-openshift-e2e-test-qe-regenerate-cluster-cert succeeded after 2h14m48s.
INFO[2024-06-14T10:18:23Z] Step azure-ipi-des-fips-regen-cert-f14-openshift-e2e-test-qe-regenerate-cluster-cert succeeded after 2h4m3s. 
```

**Comment by jianlinliu** [comment]
I have no objection on the change. 

/lgtm

**Comment by wangke19** [comment]
> I have no objection on the change, but looks like you are injecting cli:latest but not cli:target
> 
> /lgtm

Yes, but it works fine from job test results.

**Comment by liangxia** [comment]
> I have no objection on the change, but looks like you are injecting cli:latest but not cli:target

+1

**Pull request merged**
