### PR TITLE
Add AWS SNO recert weekly periodics for 4.{14,15}

### PR DESCRIPTION
**Pull request by mresvanis**
This PR adds [recert](https://github.com/rh-ecosystem-edge/recert) on AWS Single Node OpenShift periodics for OpenShift 4.14 and 4.15. It also adds failure reporting to `#recert-ci` Slack channel.

### CODE REVIEW

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-single-node-recert-parallel pull-ci-rh-ecosystem-edge-recert-main-e2e-aws-ovn-single-node-recert-serial

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ovn-single-node-recert-serial periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-aws-ovn-single-node-recert-parallel

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ovn-single-node-recert-serial periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-aws-ovn-single-node-recert-serial

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ovn-single-node-recert-serial periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-aws-ovn-single-node-recert-serial

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-aws-ovn-single-node-recert-serial

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ovn-single-node-recert-serial

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-aws-ovn-single-node-recert-parallel

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-aws-ovn-single-node-recert-parallel

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-aws-ovn-single-node-recert-parallel

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-aws-ovn-single-node-recert-serial

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-aws-ovn-single-node-recert-parallel

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-aws-ovn-single-node-recert-serial

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ovn-single-node-recert-parallel

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ovn-single-node-recert-parallel

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-aws-ovn-single-node-recert-serial periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ovn-single-node-recert-parallel

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-aws-ovn-single-node-recert-serial

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-aws-ovn-single-node-recert-serial

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-aws-ovn-single-node-recert-serial

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ovn-single-node-recert-serial

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ovn-single-node-recert-serial

**Comment by omertuc** [comment]
No rename?

**Comment by mresvanis** [comment]
> No rename?

It wasn't yet merged when I opened this PR, I'll try to add it now.

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-baremetalds-sno-recert-cluster-rename

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ovn-single-node-recert-parallel

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-baremetalds-sno-recert-cluster-rename

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-baremetalds-sno-recert-cluster-rename

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-baremetalds-sno-recert-cluster-rename

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ovn-single-node-recert-serial periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ovn-single-node-recert-parallel

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ovn-single-node-recert-parallel

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ovn-single-node-recert-parallel

**Comment by mresvanis** [comment]
@omertuc baremetal SNO recert rename job has been added, PTAL.

**Comment by mresvanis** [comment]
> Slack?

Right, we need to manually add those configs in the respective Job manifest... We should now have slack integration for all jobs (also for the FIPS periodic test).

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ovn-single-node-recert-parallel periodic-ci-rh-ecosystem-edge-recert-main-4.14-baremetalds-sno-recert-cluster-rename periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ovn-single-node-recert-serial pull-ci-rh-ecosystem-edge-recert-main-4.14-images pull-ci-rh-ecosystem-edge-recert-main-4.15-images periodic-ci-rh-ecosystem-edge-recert-main-4.14-aws-sno-fips-recert

**Pull request merged**
