### PR TITLE
Add Vsphere platform for e2e test 

### PR DESCRIPTION
**Pull request by hhpatel14**

### CODE REVIEW

**Comment by hhpatel14** [comment]
@petr-muller can you please confirm the workflow/cluster profile I am using is correct?

**Comment by petr-muller** [comment]
@hhpatel14 I am not involved in anything related to vsphere, so I'm unlikely the correct person to ping.

Correct in what sense?

**Comment by hhpatel14** [comment]
@petr-muller  It looks like all vsphere prow-jobs are failing for the same reasons. I guess vsphere workflow is the reason, but I can be wrong.  https://prow.ci.openshift.org/?type=periodic&cluster=vsphere

**Pull request closed without merging**
