### PR TITLE
main image and turning images off

### PR DESCRIPTION
**Pull request by paigerube14**
Creating main image for ocp-qe-perfscale-ci

### CODE REVIEW

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-node-density-heavy-3nodes

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-node-density-heavy-3nodes

**Comment by paigerube14** [comment]
/assign @qiliRedHat @shahsahil264 

Taking out the non required failing test

**Comment by shahsahil264** [comment]
LGTM

**Review by shahsahil264 — APPROVED** [review]

**Pull request merged**
