### PR TITLE
logging - add rsyslog image

### PR DESCRIPTION
**Pull request by richm**
logging - add rsyslog image

### CODE REVIEW

**Comment by richm** [comment]
@jcantrill

**Comment by richm** [comment]
Also - not sure how to get the fedora image tagged into the api.ci image streams

**Comment by petr-muller** [comment]
I believe for dealing with base images you need @smarterclayton

**Comment by jcantrill** [comment]
@petr-muller  I dont understand approvals for this repo.  Some times it seems like our team can get PRs through without your team's assistance and other times, like this one, we can not

**Comment by petr-muller** [comment]
> @petr-muller I dont understand approvals for this repo. Some times it seems like our team can get PRs through without your team's assistance and other times, like this one, we can not

It's driven by the `OWNERS` files, depending on which files you touch. This one also touches `Makefile` in the root, you you need an approver from root `OWNERS`, most PRs touch files in `ci-operator/{config,jobs}` subtree, where we force teams to put their `OWNERS` so that modifications there can be handled by the teams themselves.

With this one, I'm not sure if it's okay to tag `fedora` into `openshift:release`. That's why I suggested to chase @smarterclayton about it.

**Comment by smarterclayton** [comment]
We are actively trying to move all our CI images to rhel/UBI.  Why do we need fedora in this case?  What are you using it for / is what we are shipping going to be the rhel version?

**Comment by smarterclayton** [comment]
Put another way, what RPM are you looking for and is already in an rpm repo that ocp-build-data references for OsBs builds

**Comment by richm** [comment]
rsyslog is a special case
for upstream usage, we can use the rsyslog from fedora, so if we just use the fedora base image, we get all of the rsyslog packages we want for free - if this is not acceptable, there are a couple of not so good alternatives:
- use the upstream centos base image (or a derivative used as the base image for openshift origin images), and create some sort of copr repo for the rsyslog packages - ugly, lots of manual sync'ing, or lots of work to automate
- build the entire rsyslog from source in the upstream image - also ugly, requiring lots of manual sync'ing or automation

for downstream, the process is a little more complicated.  The rsyslog packages included with RHEL do not have all of the logging/kubernetes/crio functionality we require.  So we are taking as a start the rsyslog packages from rhel8, adding patches to them, building them in rhlog-1.0-rhel-7 (yes, rhel-7, at least for now - will there be an rhaos-4.0-rhcos-4 target?), then tagging them into rhaos-4.0-rhel-7-container-build, and we will use those rsyslog packages to build the downstream rsyslog image.

**Comment by smarterclayton** [comment]
Our plan is to sync container-build rpm repo to CI and simply build that way for everything.  If we do that, will you still need this?

**Comment by richm** [comment]
> Our plan is to sync container-build rpm repo to CI and simply build that way for everything. If we do that, will you still need this?

So that means the upstream image build will have access to the rsyslog packages from rhaos-4.0-rhel-7-container-build?  If so, then no, we can drop the fedora base image and go with the usual origin base image used by all of the other upstream images.  When will this be available?

**Comment by smarterclayton** [comment]
Hopefully by tomorrow, but running into other things.  No later than middle
of next week.

**Comment by richm** [comment]
With all of the changes for rsyslog and UBI support, I think we will be solving this in a different way, or not at all.

**Pull request closed without merging**
