### PR TITLE
MAO: Always run RHEL7 Scaleup tests

### PR DESCRIPTION
**Pull request by mtnbikenc**
RHEL7 scaleup tests will always run but are not required

https://jira.coreos.com/browse/CORS-1059

Resubmit of #3473

### CODE REVIEW

**Comment by michaelgugino** [comment]
I'm not really clear what the interface between MAO and RHEL is?  Could you provide more details on how this would be helpful?

**Comment by frobware** [comment]
Should this also be optional?

**Comment by sdodson** [comment]
> I'm not really clear what the interface between MAO and RHEL is? Could you provide more details on how this would be helpful?

@vrutkovs we wanted this because machine api was used to provision the RHEL instances or were there other dependencies on MAO specific to scaleup?


> Should this also be optional?

Long term yes, only optional until success rate is sufficiently high that you'd be comfortable making it required.

**Comment by vrutkovs** [comment]
>@vrutkovs we wanted this because machine api was used to provision the RHEL instances or were there other dependencies on MAO specific to scaleup?

Correct, our tests are creating machine via MAO so in order to keep tests stable we should ensure MAO changes won't break them

**Pull request merged**
