### PR TITLE
[CVP-4046] Add hybrid overlay feature on a running cluster

### PR DESCRIPTION
**Pull request by asergienk**

### CODE REVIEW

**Comment by asergienk** [comment]
/pj-rehearse periodic-ci-redhat-openshift-ecosystem-cvp-ocp-4.16-cvp-fips-common-claim

**Comment by asergienk** [comment]
/pj-rehearse periodic-ci-redhat-openshift-ecosystem-cvp-ocp-4.15-cvp-common-claim

**Review by samvarankashyap — COMMENTED** [review]
lgtm
but I have couple of  questions, 
Why are we updating all versions of Openshift ? 
do we really support hybrid overlay for all versions ? 
Are there any customers who use hybrid overlay for older versions of openshift ?

**Pull request merged**
