### PR TITLE
add periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.17-lp-interop-csb-interop-aws-latest

### PR DESCRIPTION
**Pull request by amp-rh**
[INTEROP-7438](https://issues.redhat.com/browse/INTEROP-7438)

### CODE REVIEW

**Comment by amp-rh** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.17-lp-interop-csb-interop-aws-latest

**Review by madunn — APPROVED** [review]

**Pull request merged**
