### PR TITLE
Adding support for the DPCR Cluster to Dex

### PR DESCRIPTION
**Pull request by bradmwilliams**

### CODE REVIEW

**Comment by bradmwilliams** [comment]
@alvaroaleman I think I have everything in place except the ability to add the client ID and Secret to BitWarden.  Not sure if you want to generate them and hand them to me, or I should generate them and hand them over to you.  Please advise.
Thanks!

**Review by alvaroaleman — APPROVED** [review]

**Review by alvaroaleman — COMMENTED** [review]
/hold

**Review by alvaroaleman — COMMENTED** [review]
Forgot I need to run the bootrapper on the changes of this PR, one moment

**Pull request merged**
