### PR TITLE
monitoring-operator: use multistep job for e2e-upgrade

### PR DESCRIPTION
**Pull request by vrutkovs**
Run AWS/GCP upgrade using multistep, persistent metrics and store container logs using Loki.

### CODE REVIEW

**Comment by vrutkovs** [comment]
/retest

master/4.6 failing

**Comment by vrutkovs** [comment]
master/4.6 flaking
/retest

**Comment by vrutkovs** [comment]
Discussed this with monitoring team - in order to prevent breaking 4.6/4.7/master we'll hold this until the code freeze.

/hold

**Comment by vrutkovs** [comment]
Workers didn't join the cluster

/retest

**Comment by vrutkovs** [comment]
/hold cancel

Ready for review

**Review by lilic — COMMENTED** [review]
/lgtm

Thanks!

**Pull request merged**
