### PR TITLE
stackrox: fix ocp next to 4.13+

### PR DESCRIPTION
**Pull request by gavin-stackrox**
The range we had caused a 4.12.7 to be deployed which is not what we want for this job. Note: we may want to consider how to cover that in the __ocp-4.12 variant.
/cc @BradLugo

### CODE REVIEW

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-next-qa-e2e-tests

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-next-qa-e2e-tests

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-next-qa-e2e-tests

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-next-qa-e2e-tests

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-4-next-qa-e2e-tests

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-next-qa-e2e-tests

**Review by BradLugo — APPROVED** [review]
re: https://docs.engineering.redhat.com/pages/viewpage.action?spaceKey=StackRox&title=ACS+-+OpenShift+version+support, we could add the `run if changed` support in this PR. Otherwise, /lgtm

**Pull request merged**
