### PR TITLE
OCM-4939 hypershift-e2e-f7 Disable ARN path

### PR DESCRIPTION
**Pull request by radtriste**
Follow-up once [OCM-4939](https://issues.redhat.com/browse/OCM-4939) is solved: [OCPQE-18412](https://issues.redhat.com/browse/OCPQE-18412)

### CODE REVIEW

**Comment by radtriste** [comment]
@xueli181114 @yingzhanredhat

**Comment by yasun1** [comment]
@liangxia Please help review. Thanks.

**Pull request merged**
