### PR TITLE
chore: update stackrox Go version to 1.21.9

### PR DESCRIPTION
**Pull request by tommartensen**
https://github.com/stackrox/rox-ci-image/pull/203

### CODE REVIEW

**Comment by tommartensen** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-gke-qa-e2e-tests

**Comment by tommartensen** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-gke-qa-e2e-tests

**Comment by tommartensen** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-gke-qa-e2e-tests

**Comment by tommartensen** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-gke-qa-e2e-tests

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-gke-upgrade-tests

**Pull request merged**
