### PR TITLE
enable non-blocking gcp-ovn-upgrade jobs for ovnkube and CNO

### PR DESCRIPTION
**Pull request by dcbw**

### CODE REVIEW

**Comment by dcbw** [comment]
@davetucker @abhat re https://issues.redhat.com/browse/SDN-937

**Comment by abhat** [comment]
do we need this for 4.5 as well?

**Comment by dcbw** [comment]
@abhat probably, but thought I'd try it here first.

**Comment by dcbw** [comment]
Note that we don't necessarily expect gcp-ovn-upgrade to pass yet...

**Comment by dcbw** [comment]
However, current test is "rate limit exceeded" flake:

`level=error msg="Error: Error when reading or editing ComputeHttpHealthCheck \"projects/openshift-gce-devel-ci/global/httpHealthChecks/ci-op-w7vg3lq7-3e621-xr66g-api\": googleapi: Error 403: Quota exceeded for quota group 'ReadGroup' and limit 'Read requests per 100 seconds' of service 'compute.googleapis.com' for consumer 'project_number:1053217076791'., rateLimitExceeded"`

**Pull request merged**
