### PR TITLE
Add periodic compliance jobs for OpenShift 4.13

### PR DESCRIPTION
**Pull request by rhmdnd**
Let's start running all compliance jobs on OpenShift 4.13 so we have a
better understanding of what the compliance posture is on that version.

### CODE REVIEW

**Comment by rhmdnd** [comment]
I'm good with the testing here since it adds coverage for all supported profiles on 4.13. We can chase down the handful of failures in separate bugs targeted to those profiles.

**Comment by Vincent056** [comment]
```
helpers.go:808: Result - Name: e2e-high-master-service-autofs-disabled - Status: NOT-APPLICABLE - Severity: medium
    helpers.go:815: E2E-FAILURE: The expected result for the service_autofs_disabled rule didn't match. Expected 'PASS', Got 'NOT-APPLICABLE'
```
this seems to be unexpected

**Pull request merged**
