### PR TITLE
refine ci coverage

### PR DESCRIPTION
**Pull request by jianlinliu**
Now almost every platform report quota alert every day, we have to refine the ci coverage to move forward the testing, so try to refine the ci coverage as following:

1. removing {aws|gcp|azure|vsphere}-ipi ci coverage, because they are very basic, others existing workflow can cover them
2. removing {aws|gcp|azure}-ipi -ovn ci coverage from 4.12+, because ovn is the default network type since 4.12
3. removing azure-ipi-sharednetwork ci coverage, because they are already covered by azure-ipi rhel workers, behind proxy, disconnected, private cluster, fully private cluster cases
4. removing azure-ipi-vmgenv1 ci coverage from 4.11-, because it get supported from 4.11+

### CODE REVIEW

**Comment by jianlinliu** [comment]
cc @liangxia @yunjiang29 @gpei @jinyunma @jianli-wei @lwan-wanglin @MayXuQQ @aleskandro @shellyyang1989 to be informed and help review.

**Comment by gpei** [comment]
@jianlinliu similar to the `1. removing {aws|gcp|azure|vsphere}-ipi ci coverage`, do we want to drop those basic upi workflow from the job definitions? such as `e2e-{gcp|azure|vsphere}-upi-p3`.

**Comment by jianlinliu** [comment]
>  do we want to drop those basic upi workflow from the job definitions? such as e2e-{gcp|azure|vsphere}-upi-p3

In prow ci, most of configuration coverage is happening on IPI, we only have a few UPI coverage there, at least, we need to cover UPI a few times, of course, maybe we continue to refine the coverage in another PR after we identify some UPI duplicates.

**Comment by jianlinliu** [comment]
> maybe we continue to refine the coverage in another PR after we identify some UPI duplicates.

Next step, we are going to lower test frequency of UPI + disconnected/proxy workflow to p3, only keep some basic UPI install on p2. Once PMs agree our proposal to drop UPI + disconnected/proxy ci coverage, we will directly remove them.

**Comment by gpei** [comment]
> > maybe we continue to refine the coverage in another PR after we identify some UPI duplicates.
> 
> Next step, we are going to lower test frequency of UPI + disconnected/proxy workflow to p3, only keep some basic UPI install on p2. Once PMs agree our proposal to drop UPI + disconnected/proxy ci coverage, we will directly remove them.

ok, there's also some workflows like `azure-ipi-resourcegroup-p2 `, I think we can downgrade it to p3, I guess we can have another PR for such priority downgrading.

**Comment by MayXuQQ** [comment]
azure-ipi-vmgenv1 just check use Standard_NP10s to create cluster (from 4.12) , how about removed form the period test ?

**Comment by jianlinliu** [comment]
> there's also some workflows like azure-ipi-resourcegroup-p2 , I think we can downgrade it to p3, I guess we can have another PR for such priority downgrading.

Yeah, in the todo list. Some more we can refine:
```
[jianlinliu@jialiu-laptop openshift-tests-private]$ grep -r "as: .*gcp-ipi-disconnected"
openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml:- as: e2e-gcp-ipi-disconnected-p2
openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml:- as: e2e-gcp-ipi-disconnected-p2-destructive
openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml:- as: e2e-gcp-ipi-disconnected-private-p3
openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml:- as: e2e-gcp-ipi-disconnected-private-p3-destructive
openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml:- as: e2e-gcp-ipi-disconnected-workers-rhel8-p2
openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml:- as: e2e-gcp-ipi-disconnected-workers-rhel8-p2-destructive
```

I guess `e2e-gcp-ipi-disconnected-p2` can be covered by `e2e-gcp-ipi-disconnected-workers-rhel8-p2`. No need it any more.

**Comment by jianlinliu** [comment]
> azure-ipi-vmgenv1 just check use Standard_NP10s to create cluster (from 4.12)

From 4.12? I remember it was added since 4.11, and the document in the workflow also indicate it is from 4.11

**Comment by jianlinliu** [comment]
also cc @zhaozhanqi to be informed.

**Comment by MayXuQQ** [comment]
> > azure-ipi-vmgenv1 just check use Standard_NP10s to create cluster (from 4.12)
> 
> From 4.12? I remember it was added since 4.11, and the document in the workflow also indicate it is from 4.11

you are right, from 4.11 https://github.com/openshift/release/blob/master/ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/vmgenv1/provision/cucushift-installer-rehearse-azure-ipi-vmgenv1-provision-chain.yaml

**Comment by zhaozhanqi** [comment]
> also cc @zhaozhanqi to be informed.

ok for me, thanks.  cc @anuragthehatter

**Comment by aleskandro** [comment]
lgtm from arm64 qe side

**Comment by gpei** [comment]
@jianlinliu while checking the Azure CI failing jobs, I just noticed we also have many `sdn` related workflows added, such as for azure:
```
[root@preserve-gpei-worker openshift-tests-private]# grep sdn openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml |grep e2e-azure
- as: e2e-azure-ipi-ovn-sdn2ovn-p2
- as: e2e-azure-ipi-private-sdn-p2
- as: e2e-azure-ipi-private-sdn-p3-destructive
- as: e2e-azure-ipi-sdn-migration-ovn-p2
- as: e2e-azure-ipi-sdn-p2
- as: e2e-azure-ipi-sdn-p3-destructive
```
So at least `azure-ipi-sdn` is being covered by `azure-ipi-sdn-migration-ovn`, and I guess we don't need dedicated `azure-ipi-private-sdn` profile since "private" has no relationship with the NetworkType inside OCP cluster. Could you help to remove them in this PR?

And seems this series of "ipi-sdn" "sdn-migration-ovn" "ovn-sdn2ovn" is covered on every platform, not sure if this is necessary cc @zhaozhanqi

**Comment by jianlinliu** [comment]
> Could you help to remove them in this PR?

Today I will file another PR to prune them after this PR get merged.

**Comment by gpei** [comment]
ok

**Pull request merged**
