### PR TITLE
add cluster and apiserver 95 quantile metrics

### PR DESCRIPTION
**Pull request by qJkee**
gather extra metrics

### CODE REVIEW

**Review by eggfoobar — APPROVED** [review]

**Review by wking — COMMENTED** [review]
/lgtm

**Comment by dgrisonnet** [comment]
@qJkee the `cluster:usage:cpu:apiserver:..` queries you added are incorrect. There is an extra `{` which result in a promQL evaluation error.

If we look deep into the log of this step, we can see that an error is reported: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/openshift-kubernetes-1252-nightly-4.11-e2e-metal-ipi-upgrade/1527095335401295872/artifacts/e2e-metal-ipi-upgrade/gather-extra/build-log.txt, and it prevents your metrics from being collected. You can search for `error: Query cluster:usage:cpu:apiserver:total:seconds:quantile` to see what I am talking about. That's not the only error and we should look into making them easier to detect.

**Comment by qJkee** [comment]
@dgrisonnet nice catch!
Looks like I've made a final typo during the final check
here's a PR with my queries fix, I'll try to fix other queries later
https://github.com/openshift/release/pull/28837

**Pull request merged**
