### PR TITLE
Expand openshift-pipelines to version 1.17, ipi-aws and rosa classic

### PR DESCRIPTION
**Pull request by shakyav**
Paasing jobs 
ROSA classic - https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/57820/rehearse-57820-periodic-ci-openshift-pipelines-release-tests-release-v1.17-openshift-pipelines-ocp4.17-lp-rosa-classic-openshift-pipelines-interop-rosa-aws/1869586305956974592
FIPS - https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/57820/rehearse-57820-periodic-ci-openshift-pipelines-release-tests-release-v1.17-openshift-pipelines-ocp4.18-lp-interop-openshift-pipelines-interop-aws-fips/1869629298554441728

Non-FIPS - https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/57820/rehearse-57820-periodic-ci-openshift-pipelines-release-tests-release-v1.17-openshift-pipelines-ocp4.18-lp-interop-openshift-pipelines-interop-aws/1869586181109321728

### CODE REVIEW

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-rhbk-sso-test-main-rhsso-product-ocp4.17-lp-rosa-hypershift-rhsso-interop-aws

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.17-lp-rosa-hypershift-devspaces-aws-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.17-lp-rosa-hypershift-mtc-interop-aws-rosa

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.17-lp-rosa-hypershift-openshift-pipelines-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.17-lp-rosa-hypershift-openshift-pipelines-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.17-lp-rosa-hypershift-mtc-interop-aws-rosa

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.17-lp-rosa-hypershift-devspaces-aws-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-rhbk-sso-test-main-rhsso-product-ocp4.17-lp-rosa-hypershift-rhsso-interop-aws

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.17-lp-rosa-hypershift-openshift-pipelines-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.17-lp-rosa-hypershift-openshift-pipelines-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.17-lp-rosa-hypershift-openshift-pipelines-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.17-lp-rosa-hypershift-devspaces-aws-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-rhbk-sso-test-main-rhsso-product-ocp4.17-lp-rosa-hypershift-rhsso-interop-aws

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.17-lp-rosa-hypershift-devspaces-aws-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.17-lp-rosa-hypershift-openshift-pipelines-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.17-lp-rosa-hypershift-mtc-interop-aws-rosa

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.17-lp-rosa-hypershift-mtc-interop-aws-rosa

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.17-lp-rosa-hypershift-openshift-pipelines-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.17-lp-rosa-hypershift-openshift-pipelines-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.17-lp-rosa-hypershift-mtc-interop-aws-rosa

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.16-lp-rosa-hypershift-openshift-pipelines-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.17-lp-rosa-hypershift-openshift-pipelines-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.17-lp-rosa-hypershift-openshift-pipelines-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.17-lp-rosa-hypershift-openshift-pipelines-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.16-openshift-pipelines-ocp4.18-lp-interop-openshift-pipelines-interop-aws

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.16-openshift-pipelines-ocp4.17-lp-rosa-hypershift-openshift-pipelines-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.16-openshift-pipelines-ocp4.18-lp-interop-openshift-pipelines-interop-aws

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.16-openshift-pipelines-ocp4.18-lp-interop-openshift-pipelines-interop-aws

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.16-openshift-pipelines-ocp4.18-lp-interop-openshift-pipelines-interop-aws

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.16-openshift-pipelines-ocp4.18-lp-interop-openshift-pipelines-interop-aws

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.16-openshift-pipelines-ocp4.18-lp-interop-openshift-pipelines-interop-aws

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.16-openshift-pipelines-ocp4.18-lp-interop-openshift-pipelines-interop-aws-fips

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.16-openshift-pipelines-ocp4.17-lp-rosa-hypershift-openshift-pipelines-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.16-openshift-pipelines-ocp4.18-lp-interop-openshift-pipelines-interop-aws-fips

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.16-openshift-pipelines-ocp4.18-lp-interop-openshift-pipelines-interop-aws-fips

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.16-openshift-pipelines-ocp4.18-lp-interop-openshift-pipelines-interop-aws-fips

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.16-openshift-pipelines-ocp4.17-lp-rosa-hypershift-openshift-pipelines-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.16-openshift-pipelines-ocp4.18-lp-interop-openshift-pipelines-interop-aws

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.16-openshift-pipelines-ocp4.18-lp-interop-openshift-pipelines-interop-aws

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.16-openshift-pipelines-ocp4.18-lp-interop-openshift-pipelines-interop-aws

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.16-openshift-pipelines-ocp4.18-lp-interop-openshift-pipelines-interop-aws

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.16-openshift-pipelines-ocp4.18-lp-interop-openshift-pipelines-interop-aws

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.16-openshift-pipelines-ocp4.18-lp-interop-openshift-pipelines-interop-aws-fips

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.16-openshift-pipelines-ocp4.18-lp-interop-openshift-pipelines-interop-aws-fips

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.16-openshift-pipelines-ocp4.18-lp-interop-openshift-pipelines-interop-aws

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.17-openshift-pipelines-ocp4.18-lp-interop-openshift-pipelines-interop-aws

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.17-openshift-pipelines-ocp4.17-lp-rosa-classic-openshift-pipelines-interop-rosa-aws

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.17-openshift-pipelines-ocp4.17-lp-rosa-hypershift-openshift-pipelines-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.17-openshift-pipelines-ocp4.18-lp-interop-openshift-pipelines-interop-aws-fips

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.17-openshift-pipelines-ocp4.17-lp-rosa-hypershift-openshift-pipelines-rosa-hypershift

**Review by dfrazzette — APPROVED** [review]

**Review by srivickynesh — APPROVED** [review]
/lgtm

**Pull request merged**
