### PR TITLE
Use el9 PACKET_OS in ztp workflow

### PR DESCRIPTION
**Pull request by carbonin**
This was missed in https://github.com/openshift/release/pull/52459 and now our ZTP jobs are failing because the new `oc` cli requires el9 GLIBC libraries.

Failures look like:

```
+(./01_install_requirements.sh:166): main(): retry_with_timeout 5 60 'curl https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz | sudo tar -U -C /usr/local/bin -xzf -'
+(utils.sh:16): retry_with_timeout(): retries=5
+(utils.sh:17): retry_with_timeout(): timeout_duration=60
+(utils.sh:18): retry_with_timeout(): command='curl https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz | sudo tar -U -C /usr/local/bin -xzf -'
++(utils.sh:20): retry_with_timeout(): seq 5
+(utils.sh:20): retry_with_timeout(): for _ in $(seq "$retries")
+(utils.sh:21): retry_with_timeout(): exit_code=0
+(utils.sh:22): retry_with_timeout(): timeout 60 bash -c 'curl https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz | sudo tar -U -C /usr/local/bin -xzf -'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 21 63.7M   21 13.8M    0     0  44.3M      0  0:00:01 --:--:--  0:00:01 44.2M
100 63.7M  100 63.7M    0     0  60.8M      0  0:00:01  0:00:01 --:--:-- 60.8M
+(utils.sh:23): retry_with_timeout(): ((  exit_code == 0  ))
+(utils.sh:24): retry_with_timeout(): return 0
+(./01_install_requirements.sh:167): main(): sudo chmod +x /usr/local/bin/oc
+(./01_install_requirements.sh:168): main(): oc version --client -o json
oc: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by oc)
oc: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by oc)
oc: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by oc)
```

Example failing jobs:
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_assisted-service/6446/pull-ci-openshift-assisted-service-master-edge-e2e-ai-operator-disconnected-capi/1806669261419057152
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_assisted-service/6446/pull-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp/1806669261494554624
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_assisted-service/6446/pull-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-capi/1806669261502943232

### CODE REVIEW

**Comment by carbonin** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp pull-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-capi

**Comment by carbonin** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp pull-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-capi

**Review by CrystalChun — APPROVED** [review]
/lgtm

**Pull request merged**
