### PR TITLE
ocm - Enable Bluderbuss for GRC repos

### PR DESCRIPTION
**Pull request by dhaiducek**

### CODE REVIEW

**Review by ChunxiAlexLuo — APPROVED** [review]
/LGTM

Do we still take grc-ui/api?

**Comment by dhaiducek** [comment]
That's a good point, @ChunxiAlexLuo -- I'll check with the console squad to see whether they want this change.

**Comment by dhaiducek** [comment]
/unhold

UI and API have been removed.

**Review by ChunxiAlexLuo — APPROVED** [review]
/lgtm

**Pull request merged**
