### PR TITLE
remove TP feature usermanaged

### PR DESCRIPTION
**Pull request by zhaozhanqi**
from 4.16, this feature is GA base on https://github.com/openshift/installer/pull/8101 and https://github.com/openshift/api/pull/1757

### CODE REVIEW

**Comment by zhaozhanqi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-external-lb-f7

**Comment by zhaozhanqi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-external-lb-f7

**Comment by zhaozhanqi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-external-lb-f7

**Comment by zhaozhanqi** [comment]
@aleskandro do you have time to take a look this failed [job](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/50212/rehearse-50212-periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-external-lb-f7/1772842030204981248) ?

**Comment by aleskandro** [comment]
> @aleskandro do you have time to help take a look this failed [job](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/50212/rehearse-50212-periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-external-lb-f7/1772842030204981248) ?

Hi @zhaozhanqi , it seems the installation was going fine from an infra perspective. Have you checked if all the nodes (including workers) joined the cluster?

**Comment by zhaozhanqi** [comment]
> > @aleskandro do you have time to help take a look this failed [job](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/50212/rehearse-50212-periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-external-lb-f7/1772842030204981248) ?
> 
> Hi @zhaozhanqi , it seems the installation was going fine from an infra perspective. Have you checked if all the nodes (including workers) joined the cluster?

The cluster cannot be accessed when I checked it by export KUBECONFIG=/tmp/secret/kubeconfig in pod of my project. Let me add one debug step to re-trigger another cluster to check more.

**Comment by zhaozhanqi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-external-lb-f7

**Comment by zhaozhanqi** [comment]
@aleskandro From above failed job, no worker joined the cluster 
```
$ oc get node
No resources found
```

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-external-lb-f7

**Comment by zhaozhanqi** [comment]
@sgoveas Hi, any clues you found until now?

**Comment by zhaozhanqi** [comment]
found strange things, the port `xx623` is expected? from [https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/50212/rehearse-50212-periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-external-lb-f7/1773378025086259200/artifacts/baremetal-ipi-ovn-ipv4-external-lb-f7/baremetal-lab-ipi-conf-external-lb-load-balancer/build-log.txt](url)
```
listen machine-config-server-XX623
    bind *:XX623
    mode tcp

      server master-00 192.168.83.89:XX623 check inter 1s
      server master-01 192.168.83.90:XX623 check inter 1s
      server master-02 192.168.83.99:XX623 check inter 1s
      server bootstrap 192.168.80.89:XX623 check inter 1s
```

**Comment by aleskandro** [comment]
uhm it isn't. Is this a replacement done in the logs or the actual configuration?

**Comment by zhaozhanqi** [comment]
> uhm it isn't. Is this a replacement done in the logs or the actual configuration?

I saw it from logs https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/50212/rehearse-50212-periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-external-lb-f7/1773378025086259200/artifacts/baremetal-ipi-ovn-ipv4-external-lb-f7/baremetal-lab-ipi-conf-external-lb-load-balancer/build-log.txt

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-external-lb-f7

**Comment by zhaozhanqi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-external-lb-f7

**Comment by zhaozhanqi** [comment]
I re-trigger the new job, this time found masters are ready, but workers did not boot up

```
$ oc get node
NAME                                                     STATUS   ROLES                  AGE    VERSION
master-00.ci-op-gd75pkkl.ocpqe.arm.eng.rdu2.redhat.com   Ready    control-plane,master   165m   v1.29.3+8628c3c
master-01.ci-op-gd75pkkl.ocpqe.arm.eng.rdu2.redhat.com   Ready    control-plane,master   136m   v1.29.3+8628c3c
master-02.ci-op-gd75pkkl.ocpqe.arm.eng.rdu2.redhat.com   Ready    control-plane,master   155m   v1.29.3+8628c3c
$ oc get bmh -A
NAMESPACE               NAME        STATE         CONSUMER                        ONLINE   ERROR   AGE
openshift-machine-api   master-00   provisioned   ci-op-gd75pkkl-ghmjt-master-0   true             3h8m
openshift-machine-api   master-01   provisioned   ci-op-gd75pkkl-ghmjt-master-1   true             3h8m
openshift-machine-api   master-02   provisioned   ci-op-gd75pkkl-ghmjt-master-2   true             3h8m
openshift-machine-api   worker-00                                                 true             3h8m
openshift-machine-api   worker-01                                                 true             3h8m

```

**Comment by zhaozhanqi** [comment]
@sgoveas @aleskandro BTW, how can I login the worker console to see why it's not booting well?

**Comment by zhaozhanqi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-external-lb-f7

**Comment by zhaozhanqi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-external-lb-f7

**Comment by zhaozhanqi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-external-lb-f7

**Comment by zhaozhanqi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-external-lb-f7

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-external-lb-f7

**Comment by zhaozhanqi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-external-lb-f7

**Comment by zhaozhanqi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-external-lb-f7

**Comment by zhaozhanqi** [comment]
@aleskandro @sgoveas the cluster can be setup now, even though there is bug https://issues.redhat.com/browse/OCPBUGS-33921 reported the network operator error. 

I think we can merge this PR now, Thanks for your help

**Pull request merged**
