### PR TITLE
add periodic-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.17-lp-interop-devspaces-interop-aws

### PR DESCRIPTION
**Pull request by amp-rh**
[INTEROP-7438](https://issues.redhat.com/browse/INTEROP-7438)

### CODE REVIEW

**Comment by amp-rh** [comment]
/pj-rehearse pull-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.17-lp-interop-images

**Comment by amp-rh** [comment]
/pj-rehearse pull-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.17-lp-interop-images

**Review by calebevans — APPROVED** [review]
/lgtm

**Comment by artaleks9** [comment]
There is present the error in the build-root.log:
```
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
```
The problem related to build  Dockerfile which uses `registry.ci.openshift.org/openshift/release:golang-1.18/19` (http://registry.ci.openshift.org/openshift/release:golang-1.18/19)`,  apparently is based on Centos 7 which came EOL, and gets this error.

It seems, we need to find a replacing of the `registry.ci.openshift.org/openshift/release:golang-1.18/19` to resolve this bug. 
I think, until resolving it,  don't merge PR.

**Comment by amp-rh** [comment]
/pj-rehearse pull-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.17-lp-interop-images

**Comment by amp-rh** [comment]
/pj-rehearse pull-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.17-lp-interop-images

**Comment by amp-rh** [comment]
/pj-rehearse pull-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.17-lp-interop-images

**Comment by amp-rh** [comment]
/pj-rehearse pull-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.17-lp-interop-images

**Comment by amp-rh** [comment]
/pj-rehearse pull-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.17-lp-interop-images

**Comment by amp-rh** [comment]
/pj-rehearse pull-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.17-lp-interop-images

**Comment by amp-rh** [comment]
/pj-rehearse pull-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.17-lp-interop-images

**Comment by amp-rh** [comment]
/pj-rehearse periodic-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.17-lp-interop-devspaces-interop-aws

**Comment by artaleks9** [comment]
* My comment about replacement/fixing `registry.ci.openshift.org/openshift/release:golang-1.18/1.19` due to this error:
```
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
```
was related to Dockerfile in the _[devspaces-interop-tests](https://github.com/redhat-developer/devspaces-interop-tests/blob/main/interop/Dockerfile)_ repository..sorry for confusing.

I prepared the [PR](https://github.com/redhat-developer/devspaces-interop-tests/pull/11) with fix this problem.
* So, I think, you can return back your changes as were, and it should work. 
Thanks.

**Comment by artaleks9** [comment]
* My comment about replacement/fixing `registry.ci.openshift.org/openshift/release:golang-1.18/1.19` due to this error:
```
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
```
was related to Dockerfile in the _[devspaces-interop-tests](https://github.com/redhat-developer/devspaces-interop-tests/blob/main/interop/Dockerfile)_ repository..sorry for confusing.

I prepared the [PR](https://github.com/redhat-developer/devspaces-interop-tests/pull/11) with fix this problem.
* So, I think, you can return back your changes as were, and it should work. 
Thanks.

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
