### PR TITLE
Add COMPUTE_NODE_TYPE to RHTAP jobs

### PR DESCRIPTION
**Pull request by flacatus**

### CODE REVIEW

**Review by johnmcollier — APPROVED** [review]
/lgtm
/approve

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-application-service-main-application-service-e2e

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-hac-e2e-tests

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e

**Comment by flacatus** [comment]
/pj-rehearse ci/rehearse/redhat-appstudio/application-service/main/application-service-e2e

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-application-service-main-application-service-e2e

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-hac-e2e-tests

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-application-service-main-application-service-e2e

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-hac-e2e-tests

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-hac-e2e-tests

**Pull request merged**
