### PR TITLE
chore: build-service: use pre-kcp version

### PR DESCRIPTION
**Pull request by psturc**
https://issues.redhat.com/browse/PLNSRVCE-836

depends on https://github.com/openshift/release/pull/34064

### CODE REVIEW

**Comment by psturc** [comment]
probably a test flake:
```
  Unexpected error:
      <*errors.errorString | 0xc00167eb00>: {
          s: "timed out when waiting for component build-suite-test-secret-overriding to be ready in build-e2e-dummy-quay-creds-auwi namespace: timed out waiting for the condition",
      }
      timed out when waiting for component build-suite-test-secret-overriding to be ready in build-e2e-dummy-quay-creds-auwi namespace: timed out waiting for the condition
  occurred
  In [BeforeAll] at: /tmp/tmp.1NVbUubs9s/tests/build/build.go:778
```
/retest

**Comment by psturc** [comment]
all tests passed. @mmorhun are you happy with enabling e2e for build-service repo? if so could you add `/lgtm/`? thanks

**Review by Michkov — APPROVED** [review]

**Review by mmorhun — APPROVED** [review]

**Pull request merged**
