### PR TITLE
Make ARM AWS Ovn upgrade as a blocking job

### PR DESCRIPTION
**Pull request by SaravanaStorageNetwork**
Fixes [ARMOCP-565](https://issues.redhat.com/browse/ARMOCP-565)

### CODE REVIEW

**Comment by SaravanaStorageNetwork** [comment]
@deepsm007  @Prashanth684  PTAL

**Comment by Prashanth684** [comment]
@deepsm007 can you get some eyes from TRT to look at this? the upgrade jobs have been pretty stable for now, so we feel confident about making them blocking

**Comment by neisw** [comment]
/lgtm

Reviewed with TRT, ok on our end

**Review by bradmwilliams — APPROVED** [review]

**Pull request merged**
