### PR TITLE
Modify the existing ocp release tests to run topology nightly tests in 4.13

### PR DESCRIPTION
**Pull request by sanketpathak**
https://issues.redhat.com/browse/ODC-7103

### CODE REVIEW

**Comment by sanketpathak** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-console-aws

**Comment by sanketpathak** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-console-aws

**Comment by sanketpathak** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-console-aws

**Comment by sanketpathak** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-console-aws

**Comment by sanketpathak** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-console-aws

**Comment by jerolimov** [comment]
/remove-lifecycle rotten
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-console

**Comment by jerolimov** [comment]
@sanketpathak The problem is that this job doesn't have the right (extended) timeout configured and always fails after 2h30m. One of us should update all (4.9-4.15+master) nightly builds so that their timeout matches the console pre-merge timeouts.

**Comment by sanketpathak** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-console-aws

**Comment by sanketpathak** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-console-aws

**Comment by sanketpathak** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-console-aws

/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-console-aws

**Comment by sanketpathak** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-console-aws

/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-console-aws

**Comment by sanketpathak** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-console-aws

/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-console-aws

**Comment by sanketpathak** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-console-aws

/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-console-aws

**Comment by sanketpathak** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-console-aws

**Comment by sanketpathak** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-console-aws

**Comment by sanketpathak** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-console-aws

**Comment by sanketpathak** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-console-aws

**Pull request closed without merging**
