### PR TITLE
Add boskos ImageStream

### PR DESCRIPTION
**Pull request by bbguimaraes**
To be used by E2E test in ci-tools.

### CODE REVIEW

**Comment by bbguimaraes** [comment]
@petr-muller

https://github.com/openshift/release/pull/11878#discussion_r489392760

> Can this suffer from the skew against the production boskos which is version pinned?

The goal of the E2E test is to verify the client in `ci-operator`, and I considered the lease server an irrelevant implementation detail.  For one, the test uses the in-memory version of `boskos`, so it already does not reproduce the production configuration.

For these reasons, I considered a scheduled import sufficient.

**Comment by bbguimaraes** [comment]
See

- https://github.com/openshift/ci-tools/pull/1229
- https://github.com/openshift/release/pull/11878
- https://github.com/openshift/ci-tools/pull/1232

for usage.

**Review by petr-muller — APPROVED** [review]

**Comment by bbguimaraes** [comment]
https://issues.redhat.com/browse/DPTP-1365

**Pull request merged**
