### PR TITLE
add secret bootstrap for was-virtualization

### PR DESCRIPTION
**Pull request by nunnatsa**
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

### CODE REVIEW

**Comment by smg247** [comment]
@nunnatsa this is causing the secret-bootstrap job to fail with the following error:
```
key .awscred in secret ci/cluster-secrets-aws-virtualization in cluster arm01 is targeted by ci-secret-bootstrap config and by vault item in path kv/selfservice/virtualization-secrets/aws, key .awscred in secret ci/cluster-secrets-aws-virtualization in cluster build01 is targeted by ci-secret-bootstrap config and by vault item in path kv/selfservice/virtualization-secrets/aws, key .awscred in secret ci/cluster-secrets-aws-virtualization in cluster build02 is targeted by ci-secret-bootstrap config and by vault item in path kv/selfservice/virtualization-secrets/aws, key .awscred in secret ci/cluster-secrets-aws-virtualization in cluster build03 is targeted by ci-secret-bootstrap config and by vault item in path kv/selfservice/virtualization-secrets/aws, key .awscred in secret ci/cluster-secrets-aws-virtualization in cluster build04 is targeted by ci-secret-bootstrap config and by vault item in path kv/selfservice/virtualization-secrets/aws, key .awscred in secret ci/cluster-secrets-aws-virtualization in cluster build05 is targeted by ci-secret-bootstrap config and by vault item in path kv/selfservice/virtualization-secrets/aws, key .awscred in secret ci/cluster-secrets-aws-virtualization in cluster vsphere is targeted by ci-secret-bootstrap config and by vault item in path kv/selfservice/virtualization-secrets/aws
```
Please correct this ASAP.

**Comment by nunnatsa** [comment]
@smg247 could you please explain what dose this error mean? From the text I can't even understand that this is an error.

**Comment by smg247** [comment]
> @smg247 could you please explain what dose this error mean? From the text I can't even understand that this is an error.

It appears that certain keys in the secret `cluster-secrets-aws-virtualization` are already being populated by `selfservice`, and you cannot use `ci-secret-bootstrap` as well. See: https://vault.ci.openshift.org/ui/vault/secrets/kv/show/selfservice/virtualization-secrets/aws for selfservice secret.

**Comment by nunnatsa** [comment]
Done here: 
https://github.com/openshift/release/pull/35308

**Pull request merged**
