### PR TITLE
Remove older allow_list entries now that generator is more precise

### PR DESCRIPTION
**Pull request by smarterclayton**
Only keep the broken jobs so they show up in their own dashboard.

### CODE REVIEW

**Comment by smarterclayton** [comment]
Remembered while working on https://github.com/openshift/ci-tools/pull/1798 that I promised to purge the lists.  Now our conventions and rules dictate generation, only broken tests need show up here.

**Comment by petr-muller** [comment]
Aren't in the allowlist also jobs that are not actually informing (=they are not triggered by release-controller) but want to be visible in testgrid?

**Comment by smarterclayton** [comment]
All periodic release jobs are now informing after https://github.com/openshift/ci-tools/pull/1798

**Comment by smarterclayton** [comment]
Oops, after https://github.com/smarterclayton/ci-tools/commit/f92726d15c580cc3eba2544a3f21f7ab87c2251c#diff-1df22c9e9193b5469d2e934503334b44acea5a5484b61e232b9e8f5fcde8e6bd (20 days ago).

**Comment by petr-muller** [comment]
@smarterclayton right, but not all jobs in the allowlist are release jobs. For example, `periodic-ci-openshift-psap-ci-artifacts-release-next-gpu-operator-e2e`

**Comment by smarterclayton** [comment]
That doesn't match the prefix - to be release informing you have to be periodic-openshift-release-master-...

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
