### PR TITLE
Include Kuryr upgrade jobs

### PR DESCRIPTION
**Pull request by MaysaMacedo**
This commit includes upgrade jobs from 4.9 to 4.10
and from 4.10 to 4.11. As an initial attempt we will
run no tests after the upgrade.

### CODE REVIEW

**Comment by MaysaMacedo** [comment]
From the latest run only one job failed and the [fix](https://bugzilla.redhat.com/show_bug.cgi?id=2070047) is already being worked on, the cluster was successfully upgraded.

```
started: (0/1/5) "[sig-arch][Early] Managed cluster should start all core operators [Skipped:Disconnected] [Suite:openshift/conformance/parallel]"

started: (0/2/5) "[sig-instrumentation] Prometheus when installed on the cluster shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured [Early] [Skipped:Disconnected] [Suite:openshift/conformance/parallel]"

started: (0/3/5) "[sig-auth][Feature:SCC][Early] should not have pod creation failures during install [Suite:openshift/conformance/parallel]"

started: (0/4/5) "[sig-cluster-lifecycle][Feature:Machines][Early] Managed cluster should have same number of Machines and Nodes [Suite:openshift/conformance/parallel]"

failed: (58.9s) 2022-03-30T09:02:29 "[sig-instrumentation] Prometheus when installed on the cluster shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured [Early] [Skipped:Disconnected] 

[Suite:openshift/conformance/parallel]"
started: (1/5/5) "[sig-arch][Feature:ClusterUpgrade] Cluster should remain functional during upgrade [Disruptive] [Serial]"

passed: (800ms) 2022-03-30T09:01:31 "[sig-arch][Early] Managed cluster should start all core operators [Skipped:Disconnected] [Suite:openshift/conformance/parallel]"

passed: (800ms) 2022-03-30T09:01:31 "[sig-cluster-lifecycle][Feature:Machines][Early] Managed cluster should have same number of Machines and Nodes [Suite:openshift/conformance/parallel]"

passed: (1.1s) 2022-03-30T09:01:31 "[sig-auth][Feature:SCC][Early] should not have pod creation failures during install [Suite:openshift/conformance/parallel]"

passed: (1h4m31s) 2022-03-30T10:07:00 "[sig-arch][Feature:ClusterUpgrade] Cluster should remain functional during upgrade [Disruptive] [Serial]"
```

**Comment by EmilienM** [comment]
/lgtm
/hold
feel free to merge at wish

**Pull request merged**
