### PR TITLE
Interop - Add web-terminal scenario on ROSA classic

### PR DESCRIPTION
**Pull request by oharan2**

### CODE REVIEW

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-master-web-terminal-ocp4.14-lp-rosa-classic-web-terminal-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-master-web-terminal-ocp4.14-lp-rosa-classic-web-terminal-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.14-lp-rosa-classic-web-terminal-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-master-web-terminal-ocp4.14-lp-rosa-classic-web-terminal-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.14-lp-rosa-classic-web-terminal-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.14-lp-rosa-classic-web-terminal-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.14-lp-rosa-classic-web-terminal-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.14-lp-rosa-classic-web-terminal-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse pull-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.14-lp-rosa-classic-images

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.14-lp-rosa-classic-web-terminal-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.14-lp-rosa-classic-web-terminal-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.14-lp-rosa-classic-web-terminal-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.14-lp-rosa-classic-web-terminal-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.14-lp-rosa-classic-web-terminal-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.14-lp-rosa-classic-web-terminal-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.14-lp-rosa-classic-web-terminal-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.16-lp-rosa-classic-web-terminal-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.16-lp-rosa-classic-web-terminal-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.16-lp-rosa-classic-web-terminal-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.16-lp-rosa-classic-web-terminal-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.16-lp-rosa-classic-web-terminal-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.16-lp-rosa-classic-web-terminal-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.16-lp-rosa-classic-web-terminal-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.16-lp-rosa-classic-web-terminal-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.16-lp-rosa-classic-web-terminal-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.16-lp-rosa-classic-web-terminal-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.16-lp-rosa-classic-web-terminal-rosa-aws

**Comment by musienko-maxim** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.16-lp-rosa-classic-web-terminal-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.16-lp-rosa-classic-web-terminal-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse pull-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.16-lp-rosa-classic-images

**Comment by musienko-maxim** [comment]
LGTM! Thx for your efforts!

**Comment by jkhelil** [comment]
@oharan2 I think it would be better if you reached out to others from platform teesting team

**Pull request merged**
