### PR TITLE
BUILD-264: Testing Disabled Refresh Resources Mode

### PR DESCRIPTION
**Pull request by otaviof**
Adding a extra step to run `make test-e2e-no-refreshresources` target.

### CODE REVIEW

**Comment by gabemontero** [comment]
after this PR merges @otaviof we should confirm with @adambkaplan but pretty sure we'll want to add to the operator's use of the drivers's e2e's to call this new "normal" run in addition to the existing one

I could see adding an additional call to the new make target in https://github.com/openshift/release/blob/master/ci-operator/step-registry/csi-driver-shared-resource/e2e/csi-driver-shared-resource-e2e-commands.sh

**Comment by gabemontero** [comment]
fyi https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/21591/rehearse-21591-pull-ci-openshift-csi-driver-shared-resource-master-e2e-aws-csi-driver-no-refreshresource/1433853242537676800/artifacts/e2e-aws-csi-driver-no-refreshresource/test/build-log.txt looks good !!

**Comment by adambkaplan** [comment]
> I could see adding an additional call to the new make target in https://github.com/openshift/release/blob/master/ci-operator/step-registry/csi-driver-shared-resource/e2e/csi-driver-shared-resource-e2e-commands.sh

I don't even think that is necessary. The e2e command intentionally doesn't deploy the driver so that other repos (csi-driver-shared-resource-operator, cluster-storage-operator) handle those details.

**Comment by gabemontero** [comment]
> > I could see adding an additional call to the new make target in https://github.com/openshift/release/blob/master/ci-operator/step-registry/csi-driver-shared-resource/e2e/csi-driver-shared-resource-e2e-commands.sh
> 
> I don't even think that is necessary. The e2e command intentionally doesn't deploy the driver so that other repos (csi-driver-shared-resource-operator, cluster-storage-operator) handle those details.

cool thanks for follow up @adambkaplan

**Pull request merged**
