### PR TITLE
Rely on GitHub workflows for Policy Framework PR CI

### PR DESCRIPTION
**Pull request by mprahl**

### CODE REVIEW

**Comment by dhaiducek** [comment]
Except you'll need to update the jobs also. (Running `make update` will cover it.)

**Comment by mprahl** [comment]
Thanks @dhaiducek! I knew I was missing something.  :)

**Review by dhaiducek — APPROVED** [review]

**Review by dhaiducek — APPROVED** [review]

**Comment by dhaiducek** [comment]
Blocked by:
- https://github.com/openshift/ci-tools/pull/3005

**Comment by mprahl** [comment]
@dhaiducek I removed the last commit. I'll rebase after that PR is merged.

**Comment by dhaiducek** [comment]
We should be able to just retest--the PR is in the `ci-tools` repo.

**Pull request merged**
