### PR TITLE
Fixing kube-reporting-presto-master.yaml to use dockerfile from ocp-build-data

### PR DESCRIPTION
**Pull request by alvaroaleman**

### CODE REVIEW

**Comment by bentito** [comment]
We have a limitation with the Dockerfile that ART is configured to use builds a version of this java-based forks by curling brew packages that we manually build in PNC with Maven (and then mirror to brew).
^^ @jupierce  @timflannagan1

**Comment by jupierce** [comment]
@bentito is working on merging the CI and ART dockerfiles using the CI_OPERATOR=true environment variable.

**Pull request merged**
