### PR TITLE
add test for jaeger hypershift 4.14 and 4.15

### PR DESCRIPTION
**Pull request by shakyav**
https://issues.redhat.com/browse/LPTOCPCI-1083

[LPTOCPCI-1207](https://issues.redhat.com/browse/LPTOCPCI-1207)

### CODE REVIEW

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.15-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.15-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.15-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.15-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.15-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.15-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.15-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.15-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.15-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rhearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rhearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.15-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
