### PR TITLE
Sync Serverless CI

### PR DESCRIPTION
**Pull request by serverless-qe**
Sync Serverless CI using openshift-knative/hack.

### CODE REVIEW

**Comment by pierDipi** [comment]
cert-manager operator installation needs to be changed for 4.13:
```
11:43:00.848 DEBUG:   [[ $(oc get deploy -n openshift-cert-manager cert-manager --no-headers | wc -l) != 1 ]] : Waiting until non-zero (max 600 sec.)
.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
11:53:52.345 ERROR:   Time out of 600 exceeded
make[1]: *** [install-kafka] Error 2
```

**Comment by creydr** [comment]
> pull-ci-openshift-knative-eventing-release-v1.11-413-test-e2e-aws-ocp-413

Checking on a way to install the correct CM operator version, depending on the OCP version in https://github.com/openshift-knative/serverless-operator/pull/2206 (still WIP/testing)

**Comment by creydr** [comment]
@pierDipi some of the marked failed jobs, are the old ones (ran before the SO cert-manager PR merged. e.g. [1686321006982991872](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/41856/rehearse-41856-pull-ci-openshift-knative-eventing-kafka-broker-release-v1.11-413-test-e2e-aws-ocp-413/1686321006982991872)).

One of the newer jobs (e.g. [1686989166912475136](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/41856/rehearse-41856-pull-ci-openshift-knative-eventing-release-v1.11-413-test-e2e-aws-ocp-413/1686989166912475136)) run with the latest SO version and installed cert-manager correctly: 
```
UNINSTALL_CERTMANAGER="false" ./hack/certmanager.sh
07:14:15.917 INFO:    Installing cert manager operator
Running on OpenShift 4.13.7 which supports GA'ed cert-manager-operator
namespace/cert-manager-operator created
operatorgroup.operators.coreos.com/cert-manager-operator created
subscription.operators.coreos.com/openshift-cert-manager-operator created
07:14:16.270 INFO:    Waiting until cert manager operator is available
07:14:16.271 DEBUG:   [[ $(oc get deploy -n cert-manager cert-manager --no-headers | wc -l) != 1 ]] : Waiting until non-zero (max 600 sec.)
........................................... done
INSTALL_SERVING="false" ./hack/install.sh
07:15:03.546 DEBUG:   Debug log (set -x) is written to: /logs/artifacts/build-wfl9rDgX/debuglog-install.sh.log
07:15:03.546 DEBUG:   Registering error handler: stacktrace
07:15:03.547 DEBUG:   Registering error handler: dump_state
07:15:03.548 INFO:    Skipping scaling up, because SCALE_UP is negative.
07:15:03.549 INFO:    Create namespaces
07:15:03.800 SUCCESS: Namespaces have been created: istio-system openshift-serverless
```

**Comment by pierDipi** [comment]
@creydr does that mean we're good to merge?

**Comment by creydr** [comment]
> @creydr does that mean we're good to merge?

I would say so

**Comment by ReToCode** [comment]
As this is only Serving cron changes, I don't think we need a build re-run? 

/pj-rehearse ack

/lgtm (from Serving side)

/hold feel free to start builds again or unhold.

**Pull request merged**
