### PR TITLE
remove unneeded promotion step for 3.11 jenkins image

### PR DESCRIPTION
**Pull request by gabemontero**
/assign @droslean

### CODE REVIEW

**Comment by droslean** [comment]
@gabemontero since you removed the `promotion`, can you regenerate the jobs with `ci-operator-prowgen`? It should also remove the corresponding postsubmit.

**Comment by gabemontero** [comment]
@droslean sure I'll see if I  can find the instructions for that

**Comment by droslean** [comment]
Use [ci-operator-prowgen](https://github.com/openshift/ci-tools/tree/master/cmd/ci-operator-prowgen). and just regenerate all the jobs. `ci-operator-prowgen --from-dir ci-operator/config/ --to-dir ci-operator/jobs/`. You will understand what happened after you will check your `git diff`

**Comment by gabemontero** [comment]
fyi @droslean had to remove it manually as @stevekuznetsov informed us that command would not work for jobs generated by older versions of prowgen

**Comment by gabemontero** [comment]
@droslean @stevekuznetsov post submit file manually updated ... PTAL

**Pull request merged**
