### PR TITLE
o/origin: move multitenant jobs from templates to matching multi-stage workflow

### PR DESCRIPTION
**Pull request by petr-muller**

### CODE REVIEW

**Comment by petr-muller** [comment]
This actually looks correct, `: [sig-instrumentation] Prometheus when installed on the cluster shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured [Early] [Suite:openshift/conformance/parallel] expand_more` is the flake-du-jour (https://triage.dptools.openshift.org/#de7697f07c156f1a6ec7)

**Review by AlexNPavel — APPROVED** [review]

**Pull request merged**
