### PR TITLE
Replace NVIDIA GPU Operator 24.3 with 24.9

### PR DESCRIPTION
**Pull request by empovit**
* 24.3 has reached EOL
* 24.9 is GA

### CODE REVIEW

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-nvidia-ci-main-4.15-nvidia-gpu-operator-e2e-24-9-x periodic-ci-rh-ecosystem-edge-nvidia-ci-main-4.17-nvidia-gpu-operator-e2e-24-9-x	periodic-ci-rh-ecosystem-edge-nvidia-ci-main-4.12-nvidia-gpu-operator-e2e-24-9-x periodic-ci-rh-ecosystem-edge-nvidia-ci-main-4.16-nvidia-gpu-operator-e2e-24-9-x 
periodic-ci-rh-ecosystem-edge-nvidia-ci-main-4.14-nvidia-gpu-operator-e2e-24-9-x 
periodic-ci-rh-ecosystem-edge-nvidia-ci-main-4.13-nvidia-gpu-operator-e2e-24-9-x

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-nvidia-ci-main-4.12-nvidia-gpu-operator-e2e-24-9-x periodic-ci-rh-ecosystem-edge-nvidia-ci-main-4.13-nvidia-gpu-operator-e2e-24-9-x periodic-ci-rh-ecosystem-edge-nvidia-ci-main-4.14-nvidia-gpu-operator-e2e-24-9-x periodic-ci-rh-ecosystem-edge-nvidia-ci-main-4.17-nvidia-gpu-operator-e2e-24-9-x

**Review by fabiendupont — APPROVED** [review]
/lgtm

**Pull request merged**
