### PR TITLE
migrate release-4* openshift/origin fips jobs to multi-stage steps

### PR DESCRIPTION
**Pull request by droslean**
/cc @openshift/openshift-team-developer-productivity-test-platform 

Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

### CODE REVIEW

**Comment by petr-muller** [comment]
/hold

Hm... one thing I am interested in here is not that the job pass but whether they test the right thing. It's not related to this actual migration, but can we *first* improve the fips-related logging so the steps log what they are doing, and the check logs what it is expecting and what is the result?

1. The `conf` step logs nothing about configuring the installation to be fips-enabled: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/15974/rehearse-15974-pull-ci-openshift-origin-release-4.4-e2e-aws-fips/1362120439853223936/artifacts/e2e-aws-fips/ipi-conf/build-log.txt
2. The `fips-check` logs that it is doing _something_ but does not say what it expects so you cannot judge if it actually works: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/15974/rehearse-15974-pull-ci-openshift-origin-release-4.4-e2e-aws-fips/1362120439853223936/artifacts/e2e-aws-fips/fips-check/build-log.txt

**Comment by droslean** [comment]
@petr-muller Yea those are nice concerns. I will add some logging in those scripts.

**Comment by droslean** [comment]
https://github.com/openshift/release/pull/16003

**Comment by droslean** [comment]
@petr-muller This should be ready to merge.

**Comment by petr-muller** [comment]
Perfect, thanks!

/lgtm

**Pull request merged**
