### PR TITLE
Pivot to new gen3 'm3.large.x86' instances to get rid of legacy non-I…

### PR DESCRIPTION
**Pull request by pamoedom**
Hi all, our current Packet entitlement is bound to legacy non-IBX locations which blocks some new features testing like vlan/metal_gw, in order to move to the new entitlement we need to ensure that [legacy facilities](https://metal.equinix.com/developers/docs/locations/facilities/#legacy-facility-sites) are no longer demanded, in order to do that from your side is as simple as requesting new gen3 `m3.large.x86` instances instead of legacy `m2.xlarge.x86`, those new instances cost the same but they are faster in comparison and have better network bandwith, specs [here](https://metal.equinix.com/product/servers/m3-large/).

NOTE: this is related with [DPP-10256](https://issues.redhat.com/browse/DPP-10256)

### CODE REVIEW

**Comment by osherdp** [comment]
@pamoedom please next time reach the assisted-installer team to review those kind of changes, and not dptp admins
We are of course okay with this change, but it lead to increased payment from our account and we would appreciate to know that in time (we just had to investigate lots of other directions before we noticed that)

**Comment by pamoedom** [comment]
My apologies @osherdp, I'll take that into account for future changes.

Please also note that when we pushed the change, there was no extra cost for the instance modification (I made that clear in the initial description), Equinix modified those prices some weeks after the change.

Best Regards.

**Comment by osherdp** [comment]
yeah, I noticed the costs comment. But still it's always good to communicate those changes in case somethings might break/change

**Comment by pamoedom** [comment]
Sure @osherdp, FWIW, I also recall adding @romfreiman within DPP-10256 for visibility on the assisted-installer changes, my apologies if I didn't reach all stakeholders properly for this change, I'll do it better next time.

**Pull request merged**
