### PR TITLE
[4.12] config-brancher, infra-periodics and bug related plugins changes

### PR DESCRIPTION
**Pull request by jmguzik**
/hold
/cc @danilo-gemoli 
@AlexNPavel  please check if my jira lifecycle plugin config change is correct.
@aleskandro I am reverting your change from 24.10.2022, before adding something different than okd, ocp, nightly we need to change ci-tools to add a category, otherwise, some of the automation tools are failing... yes that should be detected in presubmit

### CODE REVIEW

**Comment by aleskandro** [comment]
Hello @jmguzik I already added the stream in ci-tools. What's failing/wrong as of now and how can I help avoiding deleting the periodics for okd/scos?


See https://github.com/openshift/ci-tools/pull/3105

/cc @vrutkovs @LorbusChris

**Comment by jmguzik** [comment]
@aleskandro config-brancher tool does not recognize it. I, unfortunately, have no time space to edit the tool right now so I would proceed with deleting it to have a clean branch cut, and early next week we can follow this up and recreate the periodic.

**Comment by jmguzik** [comment]
> Have you tried with the last commit of ci-tools?

yes: `Thu Oct 27 20:05:15 2022 -0400`

**Comment by aleskandro** [comment]
Can you give the parameters that make it fail?

**Comment by jmguzik** [comment]
`config-brancher --config-dir ./ci-operator/config/ --current-release 4.12 --future-release 4.13 --bump-release 4.13 --confirm`

**Comment by aleskandro** [comment]
I'm trying the same, after building `config-brancher` from the master branch of ci-tools. 

It's working fine tho :/


1. pull the latest commit in the master branch of ci-tools
2. `go build -o config-brancher ./cmd/config-brancher`
3. `path/to/config-brancher --config-dir ./ci-operator/config/ --current-release 4.12 --future-release 4.13 --bump-release 4.13 -confirm` on the latest commit, branch master, of the openshift/release repository


```
various output......
INFO[0001] Branching configuration.                      branch=main org=red-hat-storage repo=odf-multicluster-orchestrator source-file=red-hat-storage-odf-multicluster-orchestrator-main.yaml variant=
INFO[0001] Branching configuration.                      branch=main org=redhat-cne repo=cloud-event-proxy source-file=redhat-cne-cloud-event-proxy-main.yaml variant=
INFO[0001] Branching configuration.                      branch=main org=redhat-cne repo=hw-event-proxy source-file=redhat-cne-hw-event-proxy-main.yaml variant=
INFO[0001] Branching configuration.                      branch=main org=redhat-cne repo=hw-event-proxy-operator source-file=redhat-cne-hw-event-proxy-operator-main.yaml variant=
aleskandro@dujour openshift-release (master*) % echo $?
0
```

**Pull request merged**
