### PR TITLE
Migrate insights operator jobs to multi stage

### PR DESCRIPTION
**Pull request by droslean**
/hold

Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

### CODE REVIEW

**Comment by tremes** [comment]
@droslean Is there more information wrt this change pls? I am not very experienced in this CI settings but I know there was already one change to using this "workflow" and we needed to revert it, because there was missing "support" secret in the cluster (which caused failures in our tests).

**Comment by droslean** [comment]
@tremes I created a new step that will create the insights secret in the generated cluster. I opened this PR to test it. When all rehearsals will pass, we will be ready to migrate to multi-stage jobs.

**Comment by droslean** [comment]
@tremes This PR is ready to be merged. From now on your jobs will use the multi-stage steps.

Some rehearsals failed because of a known aws issue but from the rest we prove here that this configuration works.

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
