### PR TITLE
Adjust optional operators CatalogSource for 4.12+

### PR DESCRIPTION
**Pull request by sebsoto**
With 4.13 clusters
catsrc.spec.grpcPodConfig.securityContextConfig: restricted must be set in order for the CatalogSource to become ready.

### CODE REVIEW

**Comment by aravindhp** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-e2e-upgrade

**Comment by aravindhp** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.9-aws-e2e-upgrade

**Comment by sebsoto** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-e2e-upgrade

**Comment by sebsoto** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-e2e-upgrade

**Comment by sebsoto** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.9-aws-e2e-upgrade

**Comment by aravindhp** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-e2e-upgrade

Cluster installation error:
```
level=error
level=error msg=Error: listing tags for (arn:aws:elasticloadbalancing:us-east-1:460538899914:listener/net/ci-op-2n71g9n1-0709c-tmbhl-int/5adcceab0ebc3f2e/98055ae8f171500e): ListenerNotFound: Listener 'arn:aws:elasticloadbalancing:us-east-1:460538899914:listener/net/ci-op-2n71g9n1-0709c-tmbhl-int/5adcceab0ebc3f2e/98055ae8f171500e' not found
level=error msg=	status code: 400, request id: ab836502-bb5c-4edc-a7c1-7ffd7d71cb52
level=error
level=error msg=  with module.vpc.aws_lb_listener.api_internal_services,
level=error msg=  on vpc/master-elb.tf line 135, in resource "aws_lb_listener" "api_internal_services":
level=error msg= 135: resource "aws_lb_listener" "api_internal_services" {
level=error
level=error msg=failed to fetch Cluster: failed to generate asset "Cluster": failure applying terraform for "cluster" stage: failed to create cluster: failed to apply Terraform: exit status 1
level=error
level=error msg=Error: listing tags for (arn:aws:elasticloadbalancing:us-east-1:460538899914:listener/net/ci-op-2n71g9n1-0709c-tmbhl-int/5adcceab0ebc3f2e/98055ae8f171500e): ListenerNotFound: Listener 'arn:aws:elasticloadbalancing:us-east-1:460538899914:listener/net/ci-op-2n71g9n1-0709c-tmbhl-int/5adcceab0ebc3f2e/98055ae8f171500e' not found
level=error msg=	status code: 400, request id: ab836502-bb5c-4edc-a7c1-7ffd7d71cb52
level=error
level=error msg=  with module.vpc.aws_lb_listener.api_internal_services,
level=error msg=  on vpc/master-elb.tf line 135, in resource "aws_lb_listener" "api_internal_services":
level=error msg= 135: resource "aws_lb_listener" "api_internal_services" {
level=error
level=error
```

**Comment by aravindhp** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-e2e-upgrade

**Comment by sebsoto** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-e2e-upgrade

**Comment by sebsoto** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.9-aws-e2e-upgrade

**Comment by sebsoto** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-e2e-upgrade

**Comment by sebsoto** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.9-aws-e2e-upgrade

**Comment by sebsoto** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-e2e-upgrade

**Comment by sebsoto** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.9-aws-e2e-upgrade

**Comment by sebsoto** [comment]
The `aws-e2e-upgrade-optional-operators-subscribe` step has succeeded on both master (4.13) and 4.9. Can this be approved?

**Pull request merged**
