### PR TITLE
ci-operator/step-registry/openshift/e2e/gcp/crc: Include "gcp" in workflow name

### PR DESCRIPTION
**Pull request by wking**
It's a GCP workflow, and we might grow additional workflows for other platforms in the future.  Including the platform in the workflow name makes space for that, and avoids:

```console
$ hack/step-jobs-by-platform.py
unable to determine platform-agnostic workflows for:
  openshift-e2e-crc
    gcp (pull-ci-openshift-installer-master-e2e-crc, pull-ci-openshift-installer-release-4.6-e2e-crc, pull-ci-openshift-installer-release-4.7-e2e-crc)
...
```

For precedent, see #10165.

### CODE REVIEW

**Comment by wking** [comment]
/assign @stevekuznetsov

CC @praveenkumar, @cfergeau, @guillaumerose

**Comment by wking** [comment]
Dropped the openshift-priv changes with 28c215a7b8 -> 6bd823da9e; @alvaroaleman points out that they're auto-generated.  Now I'm a full approver, and we just need a `/lgtm`.

/assign @praveenkumar

**Comment by abhinavdahiya** [comment]
> It's a GCP workflow

can you explain what you mean by it's GCP workflow? GCP workflow for openshift? Or that CRC is building their CI on GCP platform.
Have we talked to them about if they would ever run CRC on non GCP cloud?

**Comment by wking** [comment]
> can you explain what you mean by it's GCP workflow?

Just that it uses [a GCP-based workflow][1] and [cluster profile][2] and so consumes GCP [Boskos leases][3].  Although if it's just running a single, fat GCP machine and then using libvirt locally, it means our GCP Boskos lease pool is assigning the same lease for real GCP clusters as it is for these fat-instance libvirt clusters that lack much of the rest of the real GCP cluster resources.  Also potentially in this space is openshift/installer#3812.

[1]: https://github.com/openshift/release/blob/259ec00a9c1816765385026ca57b0d2bf3e9b313/ci-operator/step-registry/openshift/e2e/crc/openshift-e2e-crc-workflow.yaml#L5
[2]: https://github.com/openshift/release/blob/259ec00a9c1816765385026ca57b0d2bf3e9b313/ci-operator/config/openshift/installer/openshift-installer-master.yaml#L245
[3]: https://steps.svc.ci.openshift.org/help/leases

**Comment by wking** [comment]
> There is high likely hood that we will bundle the CRC with openshift testing on that platform and mis represent the usage etc.

I'm not changing the job name, which is sometimes used for aggregating CI statistics.  I'm just adjusting the workflow name.

**Comment by wking** [comment]
Rebased onto master with 6bd823da9e -> 92ac81133a

**Comment by mtnbikenc** [comment]
Needs rebase, but otherwise
/lgtm

**Review by mtnbikenc — APPROVED** [review]

**Comment by wking** [comment]
Rebased around #11821 with 92ac81133a -> b60c2eb35e.

**Comment by wking** [comment]
Oops, b60c2eb35e -> e2e4000309 removes the old `*.metadata.json` created in #11821.

**Pull request merged**
