### PR TITLE
MSI -  Install RHODS operator

### PR DESCRIPTION
**Pull request by rnetser**

### CODE REVIEW

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-operator-v4.13-rhods-tests

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-operator-v4.13-rhods-tests

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-operator-v4.13-rhods-tests

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-operator-v4.13-rhods-tests

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-operator-v4.13-rhods-tests

**Review by myakove — APPROVED** [review]

**Pull request merged**
