### PR TITLE
Bug OCPBUGS-10480: Skip storage test on master for e2e-openstack-csi-cinder

### PR DESCRIPTION
**Pull request by MaysaMacedo**

### CODE REVIEW

**Comment by pierreprinetti** [comment]
Can you please add a comment saying why you are skipping the tests, and what's the condition for re-enabling them?

**Review by mandre — COMMENTED** [review]
/lgtm
/approve

**Comment by MaysaMacedo** [comment]
@pierreprinetti there is a comment on the bug https://issues.redhat.com//browse/OCPBUGS-10480 explaining.
Basically we're waiting for the 1.27 bump in order to re-enable it.
Would you prefer if I comment somewhere in the code or here is fine?

**Comment by pierreprinetti** [comment]
>somewhere in the code or here is fine?

I guess here is fine! You got a LGTM already :)

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-openstack-cinder-csi-driver-operator-master-e2e-openstack-csi

**Comment by pierreprinetti** [comment]
/pj-rehearse pull-ci-openshift-openstack-cinder-csi-driver-operator-master-e2e-openstack-csi

**Pull request merged**
