### PR TITLE
Assisted-Installer: Remove conformance test from vsphere periodic workflow

### PR DESCRIPTION
**Pull request by eliorerz**
/cc @eliorerz

### CODE REVIEW

**Comment by eliorerz** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-periodic

**Comment by eliorerz** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-4-12-periodic

**Comment by eliorerz** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-4-12-periodic

**Comment by eliorerz** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted-4-12

**Review by gamli75 — APPROVED** [review]

**Review by adriengentil — APPROVED** [review]

**Comment by eliorerz** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-4-12

**Comment by eliorerz** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-4-12

**Pull request merged**
