### PR TITLE
removal of periodic RHODA job

### PR DESCRIPTION
**Pull request by redhatHameed**
Red Hat OpenShift Database Access (RHODA) has been decided to move as a community operator to the [Operator Hub](https://operatorhub.io/), and decided to remove the installation using the add-on flow. This job was created to test the RHODA operator using addon installation, but will be no longer required, so we are removing it.

### CODE REVIEW

**Comment by redhatHameed** [comment]
@jeremyary on PTO, so open new PR same as   - >  https://github.com/openshift/release/pull/36607

**Comment by redhatHameed** [comment]
@jbpratt @ryankwilliams can you review the PR and add okay test label, let me know something required to change thanks

**Comment by ryankwilliams** [comment]
Hey @redhatHameed, @jbpratt and I will have @dustman9000 and @apahim review/sign off on this request to remove the job.

Just for my knowledge, what is the reason for removing the job?

**Comment by redhatHameed** [comment]
> Hey @redhatHameed, @jbpratt and I will have @dustman9000 and @apahim review/sign off on this request to remove the job.
> 
> Just for my knowledge, what is the reason for removing the job?

@ryankwilliams Red Hat OpenShift Database Access (RHODA) has been decided to move as a community operator to the [Operator Hub](https://operatorhub.io/), and decided to remove the installation using the add-on flow. This job was created to test the RHODA operator using addon installation, but will be no longer required, so we are removing it.

@dustman9000 @apahim can you please this PR and let's us know if there is any concern thanks. 
cc : @tchughesiv @bmozaffa

**Pull request merged**
