### PR TITLE
e2e metal ipi with dual stack

### PR DESCRIPTION
**Pull request by andfasano**
Adds a new e2e-metal-ipi test with dual stack enabled (IPv4+IPv6) to the openshift/ovn-kubernetes project

### CODE REVIEW

**Comment by andfasano** [comment]
> Why is there so much duplication? There has to be a better way, isn't there support for some kind of cluster variants in the step registry?
> 
> In the worst case you could look at $JOB_NAME_SAFE and do conditional things for dual stack jobs in the existing dev-scripts steps.

AFAIK there's no yet any support to variants for multi-stage, I will recheck to see if there's anything better.
Using an env var will make the code more complex and harder to read, at least not it's clear from the config file which test is going to be executed. In general, I would prefer to have a clean way to inject a variant in the standard step.

**Comment by stbenjam** [comment]
There was a conflict in openshift-ovn-kubernetes-master.yaml, just rebased and resolved it.  This should be good to go.

**Pull request merged**
