### PR TITLE
chore(RHIDP-857): Add RHDH scalability test job

### PR DESCRIPTION
**Pull request by pmacik**

### CODE REVIEW

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-search-catalog-scalability

**Comment by pmacik** [comment]
Depends on: https://github.com/redhat-performance/backstage-performance/pull/22

**Comment by pmacik** [comment]
/pj-rehease pull-ci-redhat-performance-backstage-performance-main-search-catalog-scalability

**Comment by pmacik** [comment]
/pj-rehease pull-ci-redhat-performance-backstage-performance-main-search-catalog-scalability

**Comment by pmacik** [comment]
/pj-rehease pull-ci-redhat-performance-backstage-performance-main-search-catalog-scalability

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-search-catalog-scalability

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-search-catalog-scalability

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-list-catalog-scalability pull-ci-redhat-performance-backstage-performance-main-list-catalog pull-ci-redhat-performance-backstage-performance-main-list-catalog-empty

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-list-catalog-scalability pull-ci-redhat-performance-backstage-performance-main-list-catalog pull-ci-redhat-performance-backstage-performance-main-list-catalog-empty

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-list-catalog-scalability pull-ci-redhat-performance-backstage-performance-main-list-catalog pull-ci-redhat-performance-backstage-performance-main-list-catalog-empty

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-search-catalog

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-list-catalog-scalability pull-ci-redhat-performance-backstage-performance-main-list-catalog pull-ci-redhat-performance-backstage-performance-main-list-catalog-empty pull-ci-redhat-performance-backstage-performance-main-search-catalog

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-search-catalog-scalability

**Review by jhutar — APPROVED** [review]
/lgtm

**Review by yogananth-subramanian — APPROVED** [review]

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-list-catalog-scalability pull-ci-redhat-performance-backstage-performance-main-list-catalog pull-ci-redhat-performance-backstage-performance-main-list-catalog-empty pull-ci-redhat-performance-backstage-performance-main-search-catalog-scalability

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-list-catalog-scalability pull-ci-redhat-performance-backstage-performance-main-list-catalog pull-ci-redhat-performance-backstage-performance-main-list-catalog-empty pull-ci-redhat-performance-backstage-performance-main-search-catalog-scalability

**Review by yogananth-subramanian — APPROVED** [review]

**Pull request merged**
