### PR TITLE
Create a sample application that uses all of OPP

### PR DESCRIPTION
**Pull request by gparvin**
We need a sample application that uses all of OPP so some tests can run that isn't against an individual component but that is across all the opp products

### CODE REVIEW

**Comment by gparvin** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.15-interop-openshift-plus-interop-aws

**Comment by gparvin** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.15-interop-openshift-plus-interop-aws

**Comment by gparvin** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.15-interop-openshift-plus-interop-aws

**Comment by gparvin** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.15-interop-openshift-plus-interop-aws

**Comment by gparvin** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.15-interop-openshift-plus-interop-aws

**Comment by gparvin** [comment]
The policy-collection PR did not sync properly.  That should be resolved now so a new test is needed.

/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.15-interop-openshift-plus-interop-aws

**Comment by gparvin** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.15-interop-openshift-plus-interop-aws

**Comment by gparvin** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.15-interop-openshift-plus-interop-aws

**Review by vboulos — APPROVED** [review]

**Pull request merged**
