### PR TITLE
Tolerate 10m for singletons before firing ci-absent alerts

### PR DESCRIPTION
**Pull request by hongkailiu**
Those alerts have been fired mostly from a dead node.
Then the dead node is reaped by OpenShift.

I have looked several services that are impacted by the situation and triggered the corresponding alerts.
The service outage usually is 7-8 mins.
So let us tolerate this case and see how it goes.

### CODE REVIEW

**Comment by bbguimaraes** [comment]
Hmm, some of these have deployments with more than one replica and rolling updates, is the situation in our clusters so terrible that we _still_ end up with >10m disruptions?

**Comment by hongkailiu** [comment]
> Hmm, some of these have deployments with more than one replica and rolling updates, 

I actually checked this yesterday: Most of them are with 1 replica.

```console
oc get deploy -n ci -l app=prow
NAME                          READY   UP-TO-DATE   AVAILABLE   AGE
backport-verifier             1/1     1            1           2y8d
boskos                        3/3     3            3           2y296d
boskos-cleaner                1/1     1            1           2y296d
boskos-reaper                 1/1     1            1           2y296d
cherrypick                    1/1     1            1           2y296d
crier                         0/0     0            0           2y296d
crier-apps-auth               1/1     1            1           2y53d
deck                          2/2     2            2           2y296d
deck-internal                 2/2     2            2           2y296d
exporter                      1/1     1            1           2y296d
ghproxy                       1/1     1            1           2y296d
hook                          0/0     0            0           2y296d
hook-apps                     2/2     2            2           644d
horologium                    1/1     1            1           2y296d
jenkins-operator              1/1     1            1           2y296d
kata-jenkins-operator         1/1     1            1           2y296d
needs-rebase                  1/1     1            1           2y296d
payload-testing-prow-plugin   1/1     1            1           469d
pj-rehearse-plugin            2/2     2            2           145d
pj-rehearse-plugin-alpha      1/1     1            1           88d
plank                         0/0     0            0           2y296d
pod-scaler-producer           1/1     1            1           313d
prow-controller-manager       1/1     1            1           2y246d
publicize                     1/1     1            1           2y188d
qe-private-deck               2/2     2            2           376d
refresh                       1/1     1            1           2y296d
repo-init-apiserver           2/2     2            2           355d
retester                      1/1     1            1           293d
sinker                        1/1     1            1           2y296d
statusreconciler              1/1     1            1           524d
tide                          1/1     1            1           2y296d
tot                           1/1     1            1           2y296d
```

> is the situation in our clusters so terrible that we _still_ end up with >10m disruptions?

The ones I checked are about 7-8 mins. So I hope extend the `for` to 10m helps.
I do not know the SLA from openshift for the use case.
If we DO care HA of the component, we should support more replicas.

Tuning the alert is just a compromise/tradeoff.

**Comment by bbguimaraes** [comment]
Then I'd move just the singletons to the 10m group.

Have we seen alerts for the others?  I think I've seen `deck` sometimes unexplainably unavailable.  IMO that's something we should look into when it happens.  The others being down due to the platform are just a fact of life.

**Pull request merged**
