### PR TITLE
Assisted repos - add late binding SNO ipv4 jobs

### PR DESCRIPTION
**Pull request by omertuc**
- Periodic on both assisted-service master and ocm-2.4
- Presubmit on both assisted service master and ocm-2.4, optional on both, always_run only on the latter
- Presubmit on assisted-test-infra, optional, always_run

### CODE REVIEW

**Comment by YuviGold** [comment]
Please follow the [Adding a new CI job](https://github.com/openshift/assisted-service/blob/master/docs/dev/testing.md#adding-a-new-ci-job) guide.

* Add the job to test-infra
* Make the jobs `always_run: false`
* Add a periodic job with a Slack `config_reporter`

**Comment by omertuc** [comment]
> Please follow the [Adding a new CI job](https://github.com/openshift/assisted-service/blob/master/docs/dev/testing.md?rgh-link-date=2021-09-30T16%3A18%3A51Z#adding-a-new-ci-job) guide.
> 
> * Add the job to test-infra
> * Make the jobs `always_run: false`
> * Add a periodic job with a Slack `config_reporter`

PR updated

**Review by YuviGold — APPROVED** [review]
LGTM

**Pull request merged**
