### PR TITLE
Migrate more presubmits to build01 (1/5)

### PR DESCRIPTION
**Pull request by hongkailiu**
https://issues.redhat.com/browse/DPTP-1510

1/5 is calculated by number of names of jobs.

Eventually when we reach https://github.com/openshift/release/pull/11906 the volumes of job1 and job2 will be almost even because it is generated by the dispatch tool.

/cc @alvaroaleman @stevekuznetsov

### CODE REVIEW

**Comment by hongkailiu** [comment]
Will cancel the hold tomorrow morning.

**Comment by hongkailiu** [comment]
Oh. No. Conflicting.

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
