### PR TITLE
vsphere,remove unused segment branch

### PR DESCRIPTION
**Pull request by jcpowermac**

### CODE REVIEW

**Review by jrvaldes — COMMENTED** [review]
@jcpowermac  thanks for taking care of this. 

Mostly LGTM, just minor formatting suggestions.

**Comment by jrvaldes** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.15-vsphere-e2e-operator

**Review by saifshaikh48 — COMMENTED** [review]
/lgtm

nits: spacing/formatting as commented above

**Comment by jcpowermac** [comment]
@jrvaldes resolved comments

**Comment by sebsoto** [comment]
/approve

Thanks, good to see the wmco tests passing

**Pull request merged**
