### PR TITLE
Refreshed openstack-approvers

### PR DESCRIPTION
**Pull request by mandre**
Added myself as an approver and removed flaper87 and trown.

### CODE REVIEW

**Comment by tomassedovic** [comment]
/lgtm
/approve

Martin is a member of the OpenStack team, while `flaper87` and `trown` left.

I wonder how changes here got merged in the past given some of the owners were never members of the OpenShift org. Is this a more recent check?

**Comment by mandre** [comment]
Hey @petr-muller, do you mind taking a look at this when you have time? Thanks.

**Comment by petr-muller** [comment]
I can approve this but it won't merge until the check is happy.

**Comment by mandre** [comment]
Is it really errors or simple warnings? It seems like the job succeeded.

**Comment by mandre** [comment]
And if it's really errors, then I'd need help figure out how to refresh the `openstack-approvers` group while keeping CI happy.

**Comment by petr-muller** [comment]
@mandre it's errors, see the `do-not-merge/invalid-owners-file` label, Tide won't merge the PR with this label.

See https://github.com/openshift/release/pull/4637#issuecomment-518614027 - the IDs there can be either redhatters with badly set up accounts (not tied to openshift org), or not redhatters (it looks like all three are the latter). I think all can be safely removed from `OWNERS_ALIASES`.

**Comment by mandre** [comment]
> @mandre it's errors, see the `do-not-merge/invalid-owners-file` label, Tide won't merge the PR with this label.

Gotcha! I pushed a new commit to update the `cluster-api-openstack-maintainers` group as well, hopefully that's enough to make CI happy.

**Comment by mandre** [comment]
could we perhaps do a first pass on OWNERS_ALIASES to remove all the nicks of persons not belonging to the openshift org ? Otherwise I have the feeling I'm going to spend my afternoon on this.

**Comment by mandre** [comment]
Hopefully https://github.com/kubernetes/test-infra/pull/13889 should help me get past the verify-owners check.

**Comment by mandre** [comment]
Hmm, looks like the prow `verify-owners` plugin used in CI doesn't yet include https://github.com/kubernetes/test-infra/pull/13889

How can we update it?

**Comment by mandre** [comment]
Finally :tada:

**Pull request merged**
