### PR TITLE
Enable CAPI CI jobs

### PR DESCRIPTION
**Pull request by yunjiang29**
Enable CAPI install for the following 4.16 jobs:

## _amd64-nightly.yaml
```
aws-ipi-disc-priv-workers-rhcos-rhel8-f14
aws-ipi-disc-priv-workers-rhcos-rhel8-f14-destructive
aws-ipi-localzone-byo-subnet-ovn-day2-f2
aws-ipi-localzone-byo-subnet-ovn-f2
aws-ipi-localzone-fips-f2
aws-ipi-outpost-day2-f2
aws-ipi-private-shared-vpc-phz-sts-f2
aws-ipi-private-shared-vpc-phz-sts-f9-destructive
aws-ipi-shared-vpc-phz-freeipa-f14
aws-ipi-shared-vpc-phz-sts-openldap-fips-f2
aws-ipi-wavelength-byo-subnet-ovn-day2-f5
aws-ipi-wavelength-byo-subnet-ovn-f2
aws-ipi-wavelength-fips-f2
aws-usgov-ipi-private-f5
aws-usgov-ipi-private-sts-f5
aws-usgov-ipi-private-workers-marketplace-f5
```
## _multi-nightly.yaml
```
aws-ipi-byo-iam-role-arm-f2
aws-ipi-byo-kms-etcd-encryption-arm-f2
aws-ipi-byo-route53-compact-arm-f2
aws-ipi-sno-etcd-encryption-arm-f2
aws-ipi-disc-priv-sts-basecap-none-arm-f5
aws-ipi-disc-priv-sts-efs-arm-f2
aws-ipi-disc-priv-sts-ep-arm-f2
aws-ipi-ingress-lbtype-classic-arm-f2
aws-ipi-ingress-lbtype-nlb-arm-f2
aws-ipi-ovn-efs-arm-f2
aws-ipi-proxy-sts-arm-f2
aws-ipi-usertags-custom-sg-arm-f5
```

### CODE REVIEW

**Comment by yunjiang29** [comment]
@gpei @jianlinliu PTAL, thanks

**Comment by jianlinliu** [comment]
cc @liangxia to review.

**Pull request merged**
