### PR TITLE
LOG-4183: Update logging-view-plugin to go 1.20 and ubi9

### PR DESCRIPTION
**Pull request by jcantrill**
Ref: https://issues.redhat.com/browse/LOG-4183

cc @jgbernalp @alanconway

### CODE REVIEW

**Comment by jcantrill** [comment]
@jgbernalp Please review the e2e test and advise if this is a flake or something that will require further changes in the code base of the plugin

**Comment by jgbernalp** [comment]
/pj-rehearse pull-ci-openshift-logging-view-plugin-main-test-e2e

**Pull request merged**
