### PR TITLE
fix microshift rpm install e2e

### PR DESCRIPTION
**Pull request by sallyom**
/cc @husky-parul @cooktheryan 

I believe this will fix things
Only cp podman volume when _not_ installing via rpm

### CODE REVIEW

**Comment by sallyom** [comment]
:shrug: I'm missing something

**Comment by cooktheryan** [comment]
@sallyom i thought we deprecated that script in favor of kuttl?

**Comment by sallyom** [comment]
> @sallyom i thought we deprecated that script in favor of kuttl?

we haven't yet but i'd love to, what a pita : ) I guess we don't need it, pushed a commit to rm it

**Pull request merged**
