### PR TITLE
include the manifest-tool-local-pusher secret in all handcrafted jobs

### PR DESCRIPTION
**Pull request by droslean**
```python
import os
import ruamel.yaml

# Path to the directory containing the YAML files
directory_path = "ci-operator/jobs"

# Create YAML object
yaml = ruamel.yaml.YAML()
yaml.preserve_quotes = True
yaml.width = 200

# Function to check labels and commands, and update the job if conditions are met
def check_and_update_job(job):
    modified = False
    if isinstance(job, dict):
        job_name = job.get('name', 'Unnamed job')

        # Check the labels
        labels = job.get('labels', {})
        has_prowgen_label = 'ci.openshift.io/generator' in labels and labels['ci.openshift.io/generator'] == 'prowgen'
        
        if has_prowgen_label:
            print(f"Skipping {job_name} - has prowgen label")
            return modified

        # Check if 'ci-operator' is in the command or args of the first container
        containers = job.get('spec', {}).get('containers', [])
        has_ci_operator = False
        if containers:
            has_ci_operator = 'ci-operator' in containers[0].get('command', []) or 'ci-operator' in containers[0].get('args', [])
        
        if not has_ci_operator:
            print(f"Skipping {job_name} - does not have ci-operator command in the first container")
            return modified

        print(f"Processing {job_name}")

        # Adding volume mount if it does not exist
        volumeMounts = containers[0].get('volumeMounts', [])
        if not any(vm.get('name') == 'manifest-tool-local-pusher' for vm in volumeMounts):
            volumeMounts.append({
                'mountPath': '/secrets/manifest-tool',
                'name': 'manifest-tool-local-pusher',
                'readOnly': True
            })
            modified = True
            print(f"Added volume mount to job {job_name}")

        # Adding volume if it does not exist
        volumes = job.get('spec', {}).get('volumes', [])
        if not any(v.get('name') == 'manifest-tool-local-pusher' for v in volumes):
            volumes.append({
                'name': 'manifest-tool-local-pusher',
                'secret': {
                    'secretName': 'manifest-tool-local-pusher'
                }
            })
            modified = True
            print(f"Added volume to job {job_name}")

    return modified

# Iterate over all files in the directory and its subdirectories
for root, dirs, files in os.walk(directory_path):
    for filename in files:
        if filename.endswith(".yaml"):
            file_path = os.path.join(root, filename)
            with open(file_path, 'r') as file:
                try:
                    content = yaml.load(file)
                    modified = False
                    
                    if filename.endswith("-periodics.yaml"):
                        jobs = content.get('periodics', [])
                        for job in jobs:
                            modified |= check_and_update_job(job)

                    elif filename.endswith("-postsubmits.yaml") or filename.endswith("-presubmits.yaml"):
                        job_type = 'postsubmits' if filename.endswith("-postsubmits.yaml") else 'presubmits'
                        job_map = content.get(job_type, {})
                        for _, jobs in job_map.items():
                            for job in jobs:
                                modified |= check_and_update_job(job)

                    if modified:
                        with open(file_path, 'w') as file:
                            yaml.dump(content, file)
                            print(f"File {filename} modified")
                except Exception as e:
                    print(f"Error reading or writing file {filename}: {e}")

```

/cc @smg247 @openshift/test-platform 

Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

### CODE REVIEW

**Comment by smg247** [comment]
you've got quite a few non `ci-operator` jobs where this secret is unnecessary in here

**Comment by droslean** [comment]
> you've got quite a few non `ci-operator` jobs where this secret is unnecessary in here

Yea, I am working on the script.

**Pull request merged**
