### PR TITLE
[ovn-operator] Update functional job

### PR DESCRIPTION
**Pull request by karelyatin**
[1] is Adding functional test and it requires
GOFLAGS to be overridden.

Also update job name to be functional.

[1] https://github.com/openstack-k8s-operators/ovn-operator/pull/41

### CODE REVIEW

**Comment by karelyatin** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-ovn-operator-main-functional

**Comment by karelyatin** [comment]
@Sandeepyadav93 @abays can you please review this

**Comment by Sandeepyadav93** [comment]
/lgtm

@karelyatin this looks good.

fyi.. Nova team have disabled "ginkgo color output" in their functional job[1]  incase you want to add something similar.
 
[1] https://github.com/openshift/release/commit/80a74aae86790c88e90d80cfa1b4f0fb4c39d7e9

**Comment by karelyatin** [comment]
> /lgtm
> 
> @karelyatin this looks good.
> 
> fyi.. Nova team have disabled "ginkgo color output" in their functional job[1] incase you want to add something similar.
> 
> [1] [80a74aa](https://github.com/openshift/release/commit/80a74aae86790c88e90d80cfa1b4f0fb4c39d7e9)

/rehearsals-ack @Sandeepyadav93 ok, i will check that if needed i will push a follow up PR.

**Comment by karelyatin** [comment]
@Sandeepyadav93 any idea how to get rehearsals-ack label?

**Pull request merged**
