### PR TITLE
Increasing 4.14 nodes and moving to m6a type

### PR DESCRIPTION
**Pull request by paigerube14**
Want to increase node size for control plane tests, masters are losing connection 

CC: @afcollins

### CODE REVIEW

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-ocp-qe-perfscale-aws-node-density-heavy-small-scale

**Review by jtaleric — COMMENTED** [review]
lgtm

**Comment by paigerube14** [comment]
Andrew pinged me that the m5.xlarge might not be enough still, going to increase worker to m5.2xlarge 

```
The masters kept >1c idle !
however, I still see the issue in the api logs and see many workers hitting 0% idle, so maybe larger masters is not enough.
```

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-ocp-qe-perfscale-aws-node-density-heavy-small-scale

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-ocp-qe-perfscale-aws-node-density-heavy-small-scale

**Comment by paigerube14** [comment]
@afcollins do things with this current configuration seem good? should we merge these node sizes

**Comment by afcollins** [comment]
Looking at the results.. Latencies are better, to have max at 41s instead of 49s from the m5.2xlarge masters.

```
time="2023-08-24 18:06:27" level=info msg="node-density-heavy: ContainersReady 50th: 18324 99th: 40228 max: 40641 avg: 18574" file="pod_latency.go:176"
```

Master CPU util is ~8c as well, so having 16c machines are appropriate.
However, we really don't need 64GB. We are only using 10GiB max on the masters.

If we want to optimize further, we could go to c5.4xlarge which will give use the same 16c compute and save a few dollars.

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-ocp-qe-perfscale-aws-node-density-heavy-small-scale

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-ocp-qe-perfscale-aws-ci-tests-small-scale-kube-burner

**Comment by paigerube14** [comment]
@jtaleric @afcollins final thoughts on this? Do we still want these changes?

**Comment by afcollins** [comment]
These changes aren't necessary any longer.

We are good to close without merging.

**Pull request closed without merging**
