### PR TITLE
kubevirt: ssp: Change ssp master to main

### PR DESCRIPTION
**Pull request by opokornyy**
This PR updates SSP master to main.

### CODE REVIEW

**Comment by opokornyy** [comment]
/hold

We should wait for this PR  - https://github.com/kubevirt/ssp-operator/pull/569#issuecomment-1580809024

**Comment by akrejcir** [comment]
We cannot disable CI on `master` before all open PRs against the branch are merged.

Can you instead copy the configuration files for the `main` branch?

**Comment by akrejcir** [comment]
Please prefix the commit and PR with `kubevirt: ssp: ` so it's clear which project it changes.

**Comment by opokornyy** [comment]
> We cannot disable CI on `master` before all open PRs against the branch are merged.
> 
> Can you instead copy the configuration files for the `main` branch?

Done

**Comment by ksimon1** [comment]
The upgrade test is probably failing due to https://github.com/kubevirt/ssp-operator/blob/master/automation/e2e-upgrade-functests/run.sh#L21

**Comment by lyarwood** [comment]
/pj-rehearse pull-ci-kubevirt-ssp-operator-main-e2e-upgrade-functests

**Comment by opokornyy** [comment]
This PR - https://github.com/kubevirt/ssp-operator/pull/569, needs to be merged first then the tests should pass

**Comment by opokornyy** [comment]
/pj-rehearse pull-ci-kubevirt-ssp-operator-main-e2e-upgrade-functests

**Comment by opokornyy** [comment]
/pj-rehearse pull-ci-kubevirt-ssp-operator-main-e2e-upgrade-functests

**Comment by lyarwood** [comment]
> /pj-rehearse pull-ci-kubevirt-ssp-operator-main-e2e-upgrade-functests

This isn't going to pass until `main` has been sync'd with `master` and includes https://github.com/kubevirt/ssp-operator/pull/569

**Comment by lyarwood** [comment]
/pj-rehearse pull-ci-kubevirt-ssp-operator-main-e2e-upgrade-functests

**Pull request merged**
