### PR TITLE
updating openshift-preflight to use 4.9 and 4.13

### PR DESCRIPTION
**Pull request by acornett21**
- Switching to new versions of OCP

### CODE REVIEW

**Comment by acornett21** [comment]
/pj-rehearse pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.13-e2e, pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.13-images, pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.9-e2e, pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.9-images

**Comment by acornett21** [comment]
/pj-rehearse pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.13-e2e pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.13-images pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.9-e2e pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.9-images

**Comment by acornett21** [comment]
/pj-rehearse pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.13-e2e pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.13-images pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.9-e2e pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.9-images

**Review by bcrochet — COMMENTED** [review]
/lgtm

**Review by komish — APPROVED** [review]
/lgtm

**Pull request merged**
