### PR TITLE
MGMT-9358 update assisted-installer-agent golang version to 1.17

### PR DESCRIPTION
**Pull request by filanov**

### CODE REVIEW

**Comment by osherdp** [comment]
/hold
(to inspect rehearse jobs)
/lgtm
/approve

**Comment by osherdp** [comment]
/retest
(it might still be affected by build02 unbalanced load incident)

**Comment by filanov** [comment]
@osherdp the two failing tests are failing on 
```
2022-03-10 10:57:50 fatal: [localhost]: FAILED! => {"changed": false, "msg": "ERROR: Packet setup failed."}
```

**Comment by osherdp** [comment]
> @osherdp the two failing tests are failing on
> 
> ```
> 2022-03-10 10:57:50 fatal: [localhost]: FAILED! => {"changed": false, "msg": "ERROR: Packet setup failed."}
> ```

yes, we get that from time to time
as long as we get one e2e test passing for this PR, we should be good

**Pull request merged**
