### PR TITLE
 OSASINFRA-3367: OpenStack: Restore mergebot periodics to stable branches

### PR DESCRIPTION
**Pull request by mandre**
These jobs were failing because we don't have `release-x` branches in
merge-bot repository.

This effectively reverts commit
https://github.com/shiftstack/release/commit/7b09edc5bd2d5fcb5036634da9dff38d24532785, and moves the periodics for
syncing the stable branches to the main job definition.

### CODE REVIEW

**Comment by mandre** [comment]
I'm still testing a few things
/hold

**Comment by mandre** [comment]
/pj-rehearse periodic-ci-shiftstack-merge-bot-main-cloud-provider-openstack-4.13

**Comment by mandre** [comment]
/pj-rehearse periodic-ci-shiftstack-merge-bot-main-cloud-provider-openstack-4-13

**Comment by pierreprinetti** [comment]
/lgtm
Thank you for looking into this.

**Pull request merged**
