### PR TITLE
Migrate metrics and alerts to UWM

### PR DESCRIPTION
**Pull request by hongkailiu**
The following different is to show the diff. between the migrated ones and the current ones in the prow-monitoring: We removed some 

- Removed [prow_monitoring_absent_alerts.libsonnet](https://github.com/openshift/release/blob/master/clusters/app.ci/prow-monitoring/mixins/_prometheus/prow_monitoring_absent_alerts.libsonnet): We do not need them any more since they are managed
- Removed [kube-state-metrics.yaml](https://github.com/openshift/release/blob/master/clusters/app.ci/prow-monitoring/kube-state-metrics.yaml). We will look into the solution in [DPTP-3253](https://issues.redhat.com/browse/DPTP-3253).  cc @bradmwilliams 
- Removed [scrape configs for OpenStack](https://github.com/openshift/release/blob/c2b203f75b4dca57dbcebbcc7b596abac866c009/clusters/app.ci/prow-monitoring/additional-scrape-configs_secret.yaml#L61-L78): The endpoints [DPTP-2473](https://issues.redhat.com/browse/DPTP-2473) seem not working any more. /cc @pierreprinetti 

```console
diff -Naupr clusters/app.ci/openshift-user-workload-monitoring/mixins/prometheus_out/ci-alerts_prometheusrule.yaml clusters/app.ci/prow-monitoring/mixins/prometheus_out/prometheus-prow-rules_prometheusrule.yaml
--- clusters/app.ci/openshift-user-workload-monitoring/mixins/prometheus_out/ci-alerts_prometheusrule.yaml      2022-12-11 18:12:39
+++ clusters/app.ci/prow-monitoring/mixins/prometheus_out/prometheus-prow-rules_prometheusrule.yaml     2022-12-08 13:17:57
@@ -1,8 +1,11 @@ metadata:
 apiVersion: monitoring.coreos.com/v1
 kind: PrometheusRule
 metadata:
-  name: ci-alerts
-  namespace: ci
+  labels:
+    prometheus: prow
+    role: alert-rules
+  name: prometheus-prow-rules
+  namespace: prow-monitoring
 spec:
   groups:
   - name: ci-absent
@@ -129,6 +132,56 @@ spec:
       for: 10m
       labels:
         severity: critical
+  - name: prow-monitoring-absent
+    rules:
+    - alert: ServiceLostHA
+      annotations:
+        message: The service {{ $labels.job }} has at most 1 instance for 5 minutes.
+      expr: |
+        sum(up{job=~"grafana|prometheus|alertmanager"}) by (job) <= 1
+      for: 5m
+      labels:
+        severity: critical
+    - alert: AlertManagerPodDown
+      annotations:
+        message: Not all of 3 alert manager pods have been running in the last 5 minutes.
+      expr: |
+        sum(up{job="alertmanager"}) < 3
+      for: 5m
+      labels:
+        severity: critical
+    - alert: grafanaDown
+      annotations:
+        message: The service grafana has been down for 5 minutes.
+      expr: |
+        absent(up{job="grafana"} == 1)
+      for: 5m
+      labels:
+        severity: critical
+    - alert: alertmanagerDown
+      annotations:
+        message: The service alertmanager has been down for 5 minutes.
+      expr: |
+        absent(up{job="alertmanager"} == 1)
+      for: 5m
+      labels:
+        severity: critical
+    - alert: prometheusDown
+      annotations:
+        message: The service prometheus has been down for 5 minutes.
+      expr: |
+        absent(up{job="prometheus"} == 1)
+      for: 5m
+      labels:
+        severity: critical
+    - alert: blackboxDown
+      annotations:
+        message: The service blackbox has been down for 5 minutes.
+      expr: |
+        absent(up{job="blackbox"} == 1)
+      for: 5m
+      labels:
+        severity: critical
   - name: abnormal webhook behaviors
     rules:
     - alert: no-webhook-calls
@@ -426,6 +479,13 @@ spec:
         team: cnf-cop
   - name: prow
     rules:
+    - alert: prow-pod-crashlooping
+      annotations:
+        message: Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container}}) is restarting {{ printf "%.2f" $value }} times / 5 minutes.
+      expr: rate(kube_pod_container_status_restarts_total{namespace=~"ci|prow-monitoring",job="kube-state-metrics"}[15m]) * 60 * 5 > 0
+      for: 1m
+      labels:
+        severity: critical
     - alert: prow-job-backlog-growing
       annotations:
         message: The number of the triggered Prow jobs that have not yet been running has been increasing for the past hour.
@@ -442,6 +502,15 @@ spec:
         severity: critical
     - expr: count(label_replace(count(github_token_usage{token_hash =~ "openshift.*"}) by (token_hash), "login", "$1", "token_hash", "(.*)") or github_user_info{login=~"openshift-.*"}) by (login)
       record: github:identity_names
+  - name: release-controller-down
+    rules:
+    - alert: releaseControllerDown
+      annotations:
+        message: '{{ $labels.deployment }} has been down for 5 minutes.'
+      expr: kube_deployment_status_replicas_unavailable{namespace="ci", deployment=~"release-controller.*"} >= 1
+      for: 5m
+      labels:
+        severity: critical
   - name: release-controller-bugzilla-errors
     rules:
     - alert: releaseControllerBugzillaError
(p3env) ➜  release git:(migrate_metrics) diff -Naupr clusters/app.ci/openshift-user-workload-monitoring/mixins/prometheus_out/alertmanager-user-workload-secret_template.yaml clusters/app.ci/prow-monitoring/mixins/prometheus_out/alertmanager-prow-secret_template.yaml
--- clusters/app.ci/openshift-user-workload-monitoring/mixins/prometheus_out/alertmanager-user-workload-secret_template.yaml    2022-12-11 18:12:40
+++ clusters/app.ci/prow-monitoring/mixins/prometheus_out/alertmanager-prow-secret_template.yaml        2022-11-17 11:32:54
@@ -1,13 +1,13 @@ metadata:
 apiVersion: template.openshift.io/v1
 kind: Template
 metadata:
-  name: alertmanager-user-workload-secret
+  name: alertmanager-prow-secret
 objects:
 - apiVersion: v1
   kind: Secret
   metadata:
-    name: alertmanager-user-workload
-    namespace: ${MONITORING_NAMESPACE}
+    name: alertmanager-prow
+    namespace: ${PROW_MONITORING_NAMESPACE}
   stringData:
     alertmanager.yaml: |+
       global:
@@ -23,70 +23,70 @@ - apiVersion: v1
         slack_configs:
         - api_url: ${SLACK_API_URL}
           channel: '#ops-testplatform'
-          icon_url: https://user-images.githubusercontent.com/4013349/205364674-3fea6300-88ed-4a90-bc53-4ae5f65b16b0.png
-          text: '{{ .CommonAnnotations.message }}'
+          icon_url: https://avatars3.githubusercontent.com/u/3380462
+          text: '{{ template "custom_slack_text" . }}'
       - name: slack-warnings
         slack_configs:
         - api_url: ${SLACK_API_URL}
           channel: '#alerts-testplatform'
-          icon_url: https://user-images.githubusercontent.com/4013349/205364674-3fea6300-88ed-4a90-bc53-4ae5f65b16b0.png
-          text: '{{ .CommonAnnotations.message }}'
+          icon_url: https://avatars3.githubusercontent.com/u/3380462
+          text: '{{ template "custom_slack_text" . }}'
       - name: slack-OLM-rh-operators
         slack_configs:
         - api_url: ${SLACK_API_URL}
           channel: '#operator-test'
-          icon_url: https://user-images.githubusercontent.com/4013349/205364674-3fea6300-88ed-4a90-bc53-4ae5f65b16b0.png
+          icon_url: https://avatars3.githubusercontent.com/u/3380462
           link_names: true
-          text: '{{ .CommonAnnotations.message }}'
+          text: '{{ template "custom_slack_text" . }}'
       - name: slack-build-cop
         slack_configs:
         - api_url: ${SLACK_API_URL}
           channel: '#build-cop-alerts'
-          icon_url: https://user-images.githubusercontent.com/4013349/205364674-3fea6300-88ed-4a90-bc53-4ae5f65b16b0.png
+          icon_url: https://avatars3.githubusercontent.com/u/3380462
           link_names: true
-          text: '{{ .CommonAnnotations.message }}'
+          text: '{{ template "custom_slack_text" . }}'
       - name: slack-endurance-cluster
         slack_configs:
         - api_url: ${SLACK_API_URL}
           channel: '#build-cop-alerts'
-          icon_url: https://user-images.githubusercontent.com/4013349/205364674-3fea6300-88ed-4a90-bc53-4ae5f65b16b0.png
+          icon_url: https://avatars3.githubusercontent.com/u/3380462
           link_names: true
-          text: '{{ .CommonAnnotations.message }}'
+          text: '{{ template "custom_slack_text" . }}'
       - name: slack-kni-cnf
         slack_configs:
         - api_url: ${SLACK_API_URL}
           channel: '#cnf-alerts'
-          icon_url: https://user-images.githubusercontent.com/4013349/205364674-3fea6300-88ed-4a90-bc53-4ae5f65b16b0.png
+          icon_url: https://avatars3.githubusercontent.com/u/3380462
           link_names: true
-          text: '{{ .CommonAnnotations.message }}'
+          text: '{{ template "custom_slack_text" . }}'
       - name: slack-openshift-logging
         slack_configs:
         - api_url: ${SLACK_API_URL}
           channel: '#forum-logging'
-          icon_url: https://user-images.githubusercontent.com/4013349/205364674-3fea6300-88ed-4a90-bc53-4ae5f65b16b0.png
+          icon_url: https://avatars3.githubusercontent.com/u/3380462
           link_names: true
-          text: '{{ .CommonAnnotations.message }}'
+          text: '{{ template "custom_slack_text" . }}'
       - name: slack-openshift-virtualization
         slack_configs:
         - api_url: ${SLACK_API_URL}
           channel: '#kubevirt-ci-monitoring'
-          icon_url: https://user-images.githubusercontent.com/4013349/205364674-3fea6300-88ed-4a90-bc53-4ae5f65b16b0.png
+          icon_url: https://avatars3.githubusercontent.com/u/3380462
           link_names: true
-          text: '{{ .CommonAnnotations.message }}'
+          text: '{{ template "custom_slack_text" . }}'
       - name: slack-patch-manager
         slack_configs:
         - api_url: ${SLACK_API_URL}
           channel: '#notifications-ci'
-          icon_url: https://user-images.githubusercontent.com/4013349/205364674-3fea6300-88ed-4a90-bc53-4ae5f65b16b0.png
+          icon_url: https://avatars3.githubusercontent.com/u/3380462
           link_names: true
-          text: '{{ .CommonAnnotations.message }}'
+          text: '{{ template "custom_slack_text" . }}'
       - name: slack-release-controller
         slack_configs:
         - api_url: ${SLACK_API_URL}
           channel: '#ops-crt'
-          icon_url: https://user-images.githubusercontent.com/4013349/205364674-3fea6300-88ed-4a90-bc53-4ae5f65b16b0.png
+          icon_url: https://avatars3.githubusercontent.com/u/3380462
           link_names: true
-          text: '{{ .CommonAnnotations.message }}'
+          text: '{{ template "custom_slack_text" . }}'
       route:
         group_by:
         - alertname
@@ -131,8 +131,11 @@ - apiVersion: v1
         - match:
             severity: critical
           receiver: slack-criticals
-      templates: []
+      templates:
+      - '*.tmpl'
 
+    msg.tmpl: |
+      {{ define "custom_slack_text" }}{{ .CommonAnnotations.message }}{{ end }}
 parameters:
 - description: The SLACK API URL
   name: SLACK_API_URL
@@ -140,6 +143,6 @@ - description: The PagerDuty integration key
 - description: The PagerDuty integration key
   name: PAGERDUTY_INTEGRATION_KEY
   required: true
-- description: monitoring namespace
-  name: MONITORING_NAMESPACE
-  value: openshift-user-workload-monitoring
+- description: prow monitoring namespace
+  name: PROW_MONITORING_NAMESPACE
+  value: prow-monitoring
```

https://issues.redhat.com/browse/DPTP-3249

### CODE REVIEW

**Comment by hongkailiu** [comment]
/hold

Need to watch the rolling.

**Comment by pierreprinetti** [comment]
Indeed, we had to migrate our monitoring system and we set up our own Prometheus instance for now. Thank you!

LGTM for OpenStack

**Comment by bradmwilliams** [comment]
@hongkailiu Thanks for the heads up! 
The release-controller changes LGTM.

**Comment by hongkailiu** [comment]
We will compare the targets with prow-monitoring after merge:

```console
oc get servicemonitor -n prow-monitoring
NAME                                      AGE
alertmanager                              2y239d
boskos                                    2y239d
ci-operator-configresolver                2y214d
crier                                     2y105d
deck                                      2y239d
deck-internal                             2y239d
exporter                                  2y239d
ghproxy                                   2y239d
grafana                                   2y239d
hook                                      2y239d
hook-apps                                 587d
jenkins-operator                          2y239d
kata-jenkins-operator                     2y239d
kube-state-metrics                        2y199d
plank                                     2y239d
pod-scaler-consumer-admission             111d
pod-scaler-producer                       257d
pod-scaler-ui                             488d
prometheus                                2y239d
prow-controller-manager                   2y190d
qe-private-deck                           315d
release-controller-api-ocp                340d
release-controller-api-ocp-arm64          340d
release-controller-api-ocp-arm64-priv     340d
release-controller-api-ocp-multi          340d
release-controller-api-ocp-multi-priv     340d
release-controller-api-ocp-ppc64le        340d
release-controller-api-ocp-ppc64le-priv   340d
release-controller-api-ocp-priv           340d
release-controller-api-ocp-s390x          340d
release-controller-api-ocp-s390x-priv     340d
release-controller-ocp                    487d
release-controller-ocp-arm64              487d
release-controller-ocp-arm64-priv         487d
release-controller-ocp-multi              390d
release-controller-ocp-multi-priv         390d
release-controller-ocp-ppc64le            487d
release-controller-ocp-ppc64le-priv       487d
release-controller-ocp-priv               487d
release-controller-ocp-s390x              487d
release-controller-ocp-s390x-priv         487d
repo-init-apiserver                       299d
repo-init-ui                              293d
result-aggregator                         2y213d
sinker                                    2y239d
tide                                      2y239d
vault-secret-collection-manager           599d

oc get podmonitor -n prow-monitoring
NAME                      AGE
dptp-controller-manager   2y220d
retester                  67d
```

**Pull request merged**
