### PR TITLE
Test internal registry Dumy job DO NOT MERGE

### PR DESCRIPTION
**Pull request by fjglira**

### CODE REVIEW

**Comment by fjglira** [comment]
/pj-rehearse pull-ci-maistra-istio-operator-maistra-3.0-registry-dummy-test

**Comment by fjglira** [comment]
/pj-rehearse pull-ci-maistra-istio-operator-maistra-3.0-registry-dummy-test

**Comment by fjglira** [comment]
/pj-rehearse pull-ci-maistra-istio-operator-maistra-3.0-registry-dummy-test

**Comment by jwendell** [comment]
did you run `make update`?

**Comment by fjglira** [comment]
> did you run `make update`?

I'm working to make update work on my macOS, the problem it's with the image that is downloading. Checking the best way to do it

**Comment by fjglira** [comment]
/pj-rehearse pull-ci-maistra-istio-operator-maistra-3.0-registry-dummy-test

**Pull request closed without merging**
