### PR TITLE
Less-critical updates to cluster secrets

### PR DESCRIPTION
**Pull request by bbguimaraes**
Cannot be applied before we fix: https://github.com/openshift/release/pull/2958#issuecomment-467833496.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
/lgtm
/hold
@bbguimaraes cancel hold when we can get the other changes automated

**Comment by bbguimaraes** [comment]
@smarterclayton, @stevekuznetsov: I tried to rebase but the structure of the pull secrets has changed. We now have `quay.io` in Bitwarden with fields

```yaml
"Push Credentials":
    auths:
        quay.io: …
"Pull Credentials":
    auths:
        cloud.openshift.com: …
        quay.io: …
```
and one `pull-secret` attachment:

```yaml
auths:
    cloud.openshift.com: …
    quay.io: …
    registry.connect.redhat.com: …
    registry.redhat.io: …
    registry.svc.ci.openshift.org: …
```

How does the `registry.redhat.io` secret fit in this?

**Comment by stevekuznetsov** [comment]
I think it's subsumed by one of the others? @smarterclayton promised to document this

**Comment by smarterclayton** [comment]
Should be documented in secrets.md


On Apr 24, 2019, at 6:15 PM, Steve Kuznetsov <notifications@github.com>
wrote:

I think it's subsumed by one of the others? @smarterclayton
<https://github.com/smarterclayton> promised to document this

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/release/pull/2965#issuecomment-486448177>,
or mute
the thread

**Comment by stevekuznetsov** [comment]
@bbguimaraes do we need this?

**Pull request closed without merging**
