### PR TITLE
Add StackRox Scanner release 2.27

### PR DESCRIPTION
**Pull request by RTann**
/hold
/uncc

Created this by copy/pasting the 2.26 release YAML and removing `ubi` since only `ubi-minimal` is needed

### CODE REVIEW

**Review by gavin-stackrox — APPROVED** [review]

**Comment by RTann** [comment]
nooo give back my LGTMs i didn't change anything you monster

**Comment by gavin-stackrox** [comment]
I think the missing piece is:
/pj-rehearse ack
as mentioned in the hidden piece of the comment https://github.com/openshift/release/pull/34015#issuecomment-1314524241

**Pull request merged**
