### PR TITLE
WIP debug CI issue

### PR DESCRIPTION
**Pull request by yapei**

### CODE REVIEW

**Comment by yapei** [comment]
/pj-rehearse cucushift-installer-rehearse-aws-usgov-ipi-disconnected-private

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-usgov-ipi-disconnected-private-p2-f7

**Comment by yapei** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-stable-azure-mag-ipi-p2-f7

**Comment by yapei** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-stable-azure-mag-ipi-p2-f7

**Pull request closed without merging**
