### PR TITLE
Fully enable rehearsals

### PR DESCRIPTION
**Pull request by petr-muller**
- Disable --dry-run and --no-fail on pj-rehearse job
- Remove pj-rehearse-testing job

/cc @stevekuznetsov @droslean @bbguimaraes 

/hold

Holding to prepare an announcement for aos-devel

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
/approve
Cancel hold whenever

**Comment by petr-muller** [comment]
:crossed_fingers: 

/hold cancel

/meow sunglasses

**Pull request merged**
