### PR TITLE
Improve app.ci monitoring

### PR DESCRIPTION
**Pull request by alvaroaleman**
* Use  a PodMonitor for the dptp-controller-manager: Using a pod monitor allows us to not need the service whose only ever purpose was to be targeted by Prometheus ServiceMonitor
* Remove ServiceMonitorSelector: The prom operator defaults to only using things from its own namespace: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec
* Automatically update the promethheus to make sure we always have the latest and greatest

### CODE REVIEW

**Comment by alvaroaleman** [comment]
This is the reason: https://github.com/coreos/prometheus-operator/issues/3119#issuecomment-610445145

The only reason we needed the service was the ServiceMonitor, it is an useless object otherwise and makes things needlessly complicated.

**Comment by alvaroaleman** [comment]
If you care about consistency we can use PodMonitors everywhere, all deployments need to have pods but not all deployments need to have ServiceMonitors

**Comment by hongkailiu** [comment]
Now i see the point:
Service + ServiceMonitor = PodMonitoring
We save 1 object.

Yes. I did add several services because i want to scrape it.
But I cannot tell now which they are.

/lgtm

**Pull request merged**
