### PR TITLE
Remove configs for master branches for OCP repos, turn off tide

### PR DESCRIPTION
**Pull request by stevekuznetsov**
/assign @eparis

### CODE REVIEW

**Comment by eparis** [comment]
/lgtm
break the world my friend!

**Comment by wking** [comment]
This PR was "we need CI capacity for 4.1.z and all the master-branch stuff is consuming too much of our AWS quota.  Put all non-essential CI on hold until we get the 4.1.z jobs through".  Once they went through, #3936 turned all the non-essential stuff back on.

**Pull request merged**
