### PR TITLE
Update to use the tektoncd-pipeline name

### PR DESCRIPTION
**Pull request by arilivigni**
- update config and jobs

### CODE REVIEW

**Comment by pmorie** [comment]
Error seems legit @arilivigni https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_release/3284/rehearse-3284-pull-ci-openshift-tektoncd-pipeline-master-e2e/3

**Comment by vdemeester** [comment]
@pmorie ah right, because https://github.com/openshift/tektoncd-pipeline/pull/5 is not in (and thus we don't have that file yet) :chicken: :egg:

**Comment by arilivigni** [comment]
@pmorie This is just to get the config in the pre-rehearse shouldn't prevent us from merging.  That is what we will fix on the test side @mgencur please correct me if this is incorrect

**Pull request merged**
