### PR TITLE
Revert "Merge pull request #6508 from hongkailiu/revertMigration"

### PR DESCRIPTION
**Pull request by hongkailiu**
This reverts commit 187ac9d14a5c71802542ca44a5155ae101b5190a, reversing
changes made to 993d3c1caa73f1fa08ca5d6116505748a176d82d.

https://coreos.slack.com/archives/CBN38N3MW/p1576858687152100?thread_ts=1576857112.149000&cid=CBN38N3MW

/cc @openshift/openshift-team-developer-productivity-test-platform

### CODE REVIEW

**Comment by hongkailiu** [comment]
/hold

blocked by https://github.com/openshift/ci-tools/pull/341

**Comment by stevekuznetsov** [comment]
/close

Better to regen when we're ready

**Pull request closed without merging**
