### PR TITLE
Synchronize tasks between PR, merge and nightlies for `master`

### PR DESCRIPTION
**Pull request by msugakov**
While looking at https://github.com/openshift/release/pull/36260 I realized I get annoyed by tasks being different between master PR, merge and nightlies. This change is to synchronize those where I thought it makes sense.

1. Made sure that for each PR-test, there is a corresponding merge-test. Except of:
   a) EKS, OSD-AWS, OSD-GCP, ARO-QA, ROSA-QA - I assume they are more experimental.
   b) 4.12 `newest` tests - we don't want master merge noise yet.
2. Copied things that differ PR-test and nightlies to nightlies (nothing needed to go the opposite way).

I had to shorten `merge-openshift-penultimate-operator-e2e-tests` to `merge-openshift-penult-operator-e2e-tests` because otherwise OSCI validation complains about the name being too long.

I included results of `make update` but haven't verified them at the time of the PR publishing.

### CODE REVIEW

**Comment by msugakov** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-openshift-penultimate-operator-e2e-tests

**Comment by gavin-stackrox** [comment]
Re: the master merge jobs: gke-{kernel,race,scale} were excluded on the basis of cost -v- value (and historically from the Circle CI config). These run on nightlies to surface regressions that way with the loss of fidelity to match PR to breakage. If we want to have 4 more GKE clusters run per merge we will need to ensure GCP/stackrox-ci quota to handle busy times.

**Comment by gavin-stackrox** [comment]
Re: openshift-penultimate-operator-e2e-tests, merge-openshift-oldest-qa-e2e-tests 👍 
And merge-openshift-newest-operator-e2e-tests -> merge-openshift-penult-operator-e2e-tests 👍 (though it'll need a change on the stackrox side to support the name)

**Comment by gavin-stackrox** [comment]
Re: ROSA and OSD-AWS on nightlies. I think we disabled these due to persistent flakes (#33998), I see some recent green on pulls but not so much that I'd re-enable for nightlies.

Re: ocp-ui-e2e-tests nightlies. This is not ready for prime time yet i.e. will fail.

**Comment by msugakov** [comment]
> Re: the master merge jobs: gke-{kernel,race,scale} were excluded on the basis of cost -v- value (and historically from the Circle CI config). These run on nightlies to surface regressions that way with the loss of fidelity to match PR to breakage. If we want to have 4 more GKE clusters run per merge we will need to ensure GCP/stackrox-ci quota to handle busy times.

I saw these were present in PR pre-submits. Are they disabled by default with some labels?

**Comment by msugakov** [comment]
I see. It's the magic of `always_run: false`

**Review by gavin-stackrox — APPROVED** [review]
/lgtm

**Comment by msugakov** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-openshift-penultimate-operator-e2e-tests

**Pull request merged**
