### PR TITLE
SPLAT-1423: Created CI jobs for CAPI vSphere static IP.

### PR DESCRIPTION
**Pull request by vr4manta**
[SPLAT-1423](https://issues.redhat.com/browse/SPLAT-1423)

## Changes
- Created CI jobs to test vSphere static IP on altinfra for CAPI installer changes

## Prerequisites
- https://github.com/openshift/installer/pull/8081
- https://github.com/openshift/installer/pull/7501

### CODE REVIEW

**Comment by vr4manta** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.16-altinfra-e2e-vsphere-capi-static-ovn

**Comment by vr4manta** [comment]
/assign @r4f4 @sdodson 
Ready for review

**Comment by r4f4** [comment]
Do we really need the `openshift-priv` changes?

**Comment by vr4manta** [comment]
> Do we really need the `openshift-priv` changes?

Good question.  I only did it to match the other capi config.  I can remove it if you think its not needed.

**Comment by r4f4** [comment]
> > Do we really need the `openshift-priv` changes?
> 
> Good question. I only did it to match the other capi config. I can remove it if you think its not needed.

I don't think it's needed. See https://docs.ci.openshift.org/docs/architecture/private-repositories/#openshift-priv-organization

**Comment by vr4manta** [comment]
> > > Do we really need the `openshift-priv` changes?
> > 
> > 
> > Good question. I only did it to match the other capi config. I can remove it if you think its not needed.
> 
> I don't think it's needed. See https://docs.ci.openshift.org/docs/architecture/private-repositories/#openshift-priv-organization

@r4f4 , I've removed the `openshift-priv` changes.  Thanks!

**Comment by r4f4** [comment]
/pj-rehearse pull-ci-openshift-installer-master-altinfra-e2e-vsphere-capi-static-ovn pull-ci-openshift-installer-release-4.15-altinfra-e2e-vsphere-static-ovn

**Comment by r4f4** [comment]
No provider is defined for the vsphere altinfra in 4.15: 
```
level=info msg=Creating infrastructure resources...
panic: not implemented
goroutine 1 [running]:
github.com/openshift/installer/pkg/infrastructure/platform.ProviderForPlatform({0x8e392a5?, 0x4?}, {0x8ef7819?, 0x24?}) 
```
So maybe we can drop the 4.15 change?

**Comment by vr4manta** [comment]
> No provider is defined for the vsphere altinfra in 4.15:
> 
> ```
> level=info msg=Creating infrastructure resources...
> panic: not implemented
> goroutine 1 [running]:
> github.com/openshift/installer/pkg/infrastructure/platform.ProviderForPlatform({0x8e392a5?, 0x4?}, {0x8ef7819?, 0x24?}) 
> ```
> 
> So maybe we can drop the 4.15 change?

yeah, i noticed bot added it from main file.  I can remove this.  static ip was in 4.15, but not for altinfra.  Let me make that change real quick.

**Pull request merged**
