### PR TITLE
add cluster-secrets-devsandboxci-aws for devsandboxci-aws cluster profile

### PR DESCRIPTION
**Pull request by MatousJobanek**
related PRs:
* cluster profile definition: https://github.com/openshift/ci-tools/pull/3893
* lease: https://github.com/openshift/release/pull/47765

secret created in Vault:
**selfservice/cluster-secrets-devsandboxci-aws/devsandboxci-aws**
```json
{
  ".awscred": "[default]\naws_access_key_id=<Access_Key_ID>\naws_secret_access_key=<Access_Key_Secret>",
  "secretsync/target-name": "cluster-secrets-devsandboxci-aws",
  "secretsync/target-namespace": "ci"
}
```

### CODE REVIEW

**Comment by jmguzik** [comment]
Do you have any other PRs you want to merge in this context? Eg you need boskos leases as well.

**Comment by MatousJobanek** [comment]
@jmguzik a new lease in boskos file is already merged: https://github.com/openshift/release/pull/47765

**Review by jmguzik — APPROVED** [review]

**Pull request merged**
