### PR TITLE
Increase memory limits for running openshift-tests

### PR DESCRIPTION
**Pull request by jcpowermac**

### CODE REVIEW

**Comment by jcpowermac** [comment]
https://search.ci.openshift.org/?search=Container+test+exited+with+code+137%2C+reason+OOMKilled&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

**Comment by stbenjam** [comment]
Thanks @jcpowermac 

- We can remove vsphere from the title, it appears to affect others

- Can we add the reasoning to the commit message? Something like:

> Increase memory limits for steps running openshift-tests to account for increased memory consumption. This change is necessary due to the removal of a workaround for a Linux kernel bug in golang versions 1.21+. See https://github.com/golang/go/issues/64332.

- Would you be willing to update some other steps? These reference openshift-tests:

```
./baremetalds/e2e/test/baremetalds-e2e-test-commands.sh
./baremetalds/sno/test/baremetalds-sno-test-commands.sh
./openshift/e2e/gcp/libvirt/test/openshift-e2e-gcp-libvirt-test-commands.sh
./openshift/e2e/libvirt/test/openshift-e2e-libvirt-test-commands.sh
./openshift/e2e/ovirt/minimal/test/openshift-e2e-ovirt-minimal-test-commands.sh
./openshift/e2e/test/openshift-e2e-test-commands.sh
./single-node/e2e/test/single-node-e2e-test-commands.sh
```

**Pull request merged**
