### PR TITLE
Update all ocp-release-operator-sdk builds to use the api.ci cluster

### PR DESCRIPTION
**Pull request by fabianvf**

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@fabianvf rationale?

**Comment by fabianvf** [comment]
@alvaroaleman Our image builds don't seem to be working in the 4.x cluster, still working on figuring out what the root issue there is but until we fix it CI in the openshift/ocp-release-operator-sdk repo can't pass. This at least gets us working again until we figure it out.

**Comment by alvaroaleman** [comment]
@fabianvf okay, please contact #devex for help on that.

We can merge this but we are in the process of migrating everything off of that cluster which includes jobs, so in the near future the job will end up on a 4.X cluster again without option to go back to a 3.11 one.

/lgtm
/approve

**Comment by fabianvf** [comment]
@alvaroaleman :+1: I am in contact with them and am aware that this is not a long-term solution, thanks a ton for getting to this so quickly

**Pull request merged**
