### PR TITLE
Update libvirt job for 4.4 release branch

### PR DESCRIPTION
**Pull request by andymcc**
Update test names for 4.4 and add additional tests in line with https://github.com/openshift/release/pull/8592/files

This resolves openshift-tests failures for libvirt tests:

error: suite "files" does not contain any tests

https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/origin-ci-test/pr-logs/pull/openshift_release/9030/rehearse-9030-pull-ci-openshift-cluster-api-provider-libvirt-release-4.4-e2e-libvirt/2

### CODE REVIEW

**Comment by andymcc** [comment]
@praveenkumar the tests are running now - would you be able to comment on the 4 tests that failed, if they aren't required/should be passing? We could disable those ones specifically.

**Comment by wking** [comment]
/assign @praveenkumar

As [suggested][1] by Prow/blunderbuss.

[1]: https://github.com/openshift/release/pull/9030#issuecomment-628676028

**Pull request merged**
