### PR TITLE
Add RHEL7 scaleup canary release informer

### PR DESCRIPTION
**Pull request by mtnbikenc**
https://jira.coreos.com/browse/CORS-1194

### CODE REVIEW

**Comment by droslean** [comment]
@mtnbikenc Can you add a `pj-rehearse.openshift.io/can-be-rehearsed: true` label? This will allow rehearse tool to rehearse the job in the PR.

**Comment by mtnbikenc** [comment]
@droslean Updated with `can-be rehearsed` label.

**Pull request merged**
