### PR TITLE
Adds securesign/rekor as a new repo

### PR DESCRIPTION
**Pull request by lance**
The Trusted Secure Sign project is spinning up and will be using openshift CI in midstream. This is an attempt to bootstrap an initial repo for that project. More will follow as we get more familiar with onboarding. Supercedes https://github.com/openshift/release/pull/41936

### CODE REVIEW

**Comment by lance** [comment]
@bbguimaraes how do I re-run the rehearsal jobs?

**Comment by danilo-gemoli** [comment]
> @bbguimaraes how do I re-run the rehearsal jobs?

https://github.com/openshift/release/pull/41939#issuecomment-1664374338

**Comment by lance** [comment]
@danilo-gemoli I did that and it didn't work?
image

**Comment by lance** [comment]
/pj-rehearse pull-ci-securesign-rekor-release-next-unit pull-ci-securesign-rekor-release-next-e2e
/pj-rehearse auto-ack

**Comment by lance** [comment]
/pj-rehearse pull-ci-securesign-rekor-release-next-unit pull-ci-securesign-rekor-release-next-e2e

**Comment by lance** [comment]
/pj-rehearse pull-ci-securesign-rekor-release-next-unit pull-ci-securesign-rekor-release-next-e2e

**Comment by lance** [comment]
/pj-rehearse pull-ci-securesign-rekor-release-next-unit pull-ci-securesign-rekor-release-next-e2e

**Comment by lance** [comment]
/pj-rehearse pull-ci-securesign-rekor-release-next-unit pull-ci-securesign-rekor-release-next-e2e

**Comment by lance** [comment]
@danilo-gemoli @bbguimaraes I'm a bit stumped getting unit and e2e tests working. Could one of you point me in the right direction here, as I'm not sure what is causing these jobs to fail?

Based on what I have in this file: https://github.com/openshift/release/pull/41939/files#diff-935e4885e965aff83bfb2b85956a7860f99eddfe0f85dc5cb8061f1486017fa9 it is my understanding that the unit test job will do the following in some fashion.

1. Clone the `securesign/rekor` repository from github
2. Check out the `release-next` branch
3. Run `git log -n 2 --pretty=format:"%H %s" && make test` which is configured as the `command` value for the unit tests

I see that this is happening, and the output from the `git log` command appears to be what I expect.

```
b37035f0c640d1aa374d267d2e5401cdb4705ad5 :open_file_folder: update Red Hat specific files
0d88d2204b62d6e4039104703b9047038e37d5bf build(deps): bump gocloud.dev from 0.32.0 to 0.33.0 (#1609)cd hack/tools; go build -trimpath -tags=tools -o /go/src/github.com/securesign/rekor/hack/tools/bin/swagger github.com/go-swagger/go-swagger/cmd/swagger
```

Which corresponds to the two most recent commits on the `release-next` branch in the repo: https://github.com/securesign/rekor/commits/release-next.

However the `make test` command is failing.

When I do the same thing locally, I get no errors, and see the expected output from the `git log` command noted earlier. The following commands all succeed.

```
cd /tmp
git clone git@github.com:securesign/rekor.git
cd rekor
git checkout release-next
make test
```
It's not clear to me what to do next in order to get these tests to pass in the OpenShift CI job. Any guidance would be appreciated.

**Comment by danilo-gemoli** [comment]
```
	To ignore the vendor directory, use -mod=readonly or -mod=mod.
	To sync the vendor directory, run:
		go mod vendor
```
Try to follow what the log says

**Comment by lance** [comment]
> ```
> 	To ignore the vendor directory, use -mod=readonly or -mod=mod.
> 	To sync the vendor directory, run:
> 		go mod vendor
> ```
> 
> Try to follow what the log says

I see what the log says, but I don't understand why this is necessary in CI when it's not necessary otherwise.

**Comment by lance** [comment]
/pj-rehearse pull-ci-securesign-rekor-release-next-unit pull-ci-securesign-rekor-release-next-e2e

**Comment by lance** [comment]
/pj-rehearse pull-ci-securesign-rekor-release-next-unit pull-ci-securesign-rekor-release-next-e2e

**Comment by lance** [comment]
OK - I've made some progress by updating the image used to run the tests here https://github.com/openshift/release/pull/41939/files#diff-935e4885e965aff83bfb2b85956a7860f99eddfe0f85dc5cb8061f1486017fa9R2-R5 and setting `GOFLAGS=""` on the commands. That fixed the e2e tests, however the unit tests are still failing. It seems as though the imagestream I am now using contains an older version of openssh. I would like to bump to a RHEL9 based image stream, but don't know what the name is for that and can't seem to find it. Any guidance here?

**Comment by lance** [comment]
/pj-rehearse pull-ci-securesign-rekor-release-next-unit pull-ci-securesign-rekor-release-next-e2e

**Review by sallyom — APPROVED** [review]
/lgtm

**Pull request merged**
