### PR TITLE
feat(RHTAP-979): Add jobs to run tekton-tuning scenarios for RHTAP load test

### PR DESCRIPTION
**Pull request by pmacik**
Ref: https://issues.redhat.com/browse/RHTAP-979

### CODE REVIEW

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-tekton-tuning-base

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-tekton-tuning-base pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-tekton-tuning

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-tekton-tuning-base pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-tekton-tuning

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-tekton-tuning-base pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-tekton-tuning

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-tekton-tuning-base pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-tekton-tuning-tuned pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-10u-10t-nodejs periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-basic periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-advanced

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-tekton-tuning-base pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-tekton-tuning-tuned pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-10u-10t-nodejs periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-basic periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-advanced

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-tekton-tuning-base pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-tekton-tuning-tuned periodic-ci-redhat-appstudio-e2e-tests-main-load-test-ci-daily-10u-10t periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-basic periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-advanced

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-tekton-tuning-base pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-tekton-tuning-tuned periodic-ci-redhat-appstudio-e2e-tests-main-load-test-ci-daily-10u-10t periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-basic periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-advanced

**Comment by pmacik** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-basic periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-advanced

**Comment by pmacik** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-basic periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-advanced

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-tekton-tuning-base pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-tekton-tuning-tuned periodic-ci-redhat-appstudio-e2e-tests-main-load-test-ci-daily-10u-10t periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-basic periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-advanced

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-tekton-tuning-base pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-tekton-tuning-tuned periodic-ci-redhat-appstudio-e2e-tests-main-load-test-ci-daily-10u-10t periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-basic periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-advanced

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-max-concurrency-basic-tekton-tuned pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-tekton-tuning-base pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-tekton-tuning-tuned

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-max-concurrency-basic-tekton-tuned

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-max-concurrency-basic-tekton-tuned

**Review by jhutar — APPROVED** [review]
LGTM

**Pull request merged**
