### PR TITLE
addon operator CI to conditionally run PKO tests

### PR DESCRIPTION
**Pull request by ashishmax31**
Fixes: https://issues.redhat.com/browse/MTSRE-1713

### CODE REVIEW

**Comment by supreeth7** [comment]
/pj-rehearse pull-ci-openshift-addon-operator-main-pko-e2e-tests

**Comment by supreeth7** [comment]
/pj-rehearse pull-ci-openshift-addon-operator-main-pko-e2e-tests

**Comment by supreeth7** [comment]
/pj-rehearse pull-ci-openshift-addon-operator-main-pko-e2e-tests

**Comment by supreeth7** [comment]
/pj-rehearse pull-ci-openshift-addon-operator-main-pko-e2e-tests

**Comment by supreeth7** [comment]
/pj-rehearse pull-ci-openshift-addon-operator-main-pko-e2e-tests

/bark

**Comment by supreeth7** [comment]
/pj-rehearse pull-ci-openshift-addon-operator-main-pko-e2e-tests

**Comment by supreeth7** [comment]
/pj-rehearse pull-ci-openshift-addon-operator-main-pko-e2e-tests

**Comment by supreeth7** [comment]
/pj-rehearse pull-ci-openshift-addon-operator-main-pko-e2e-tests

**Comment by ashishmax31** [comment]
/pj-rehearse pull-ci-openshift-addon-operator-main-pko-e2e-tests

**Comment by supreeth7** [comment]
/pj-rehearse pull-ci-openshift-addon-operator-main-pko-e2e-tests

**Comment by supreeth7** [comment]
Daily re-run for one last time.


/pj-rehearse pull-ci-openshift-addon-operator-main-pko-e2e-tests

**Pull request closed without merging**
