### PR TITLE
Chaos image

### PR DESCRIPTION
**Pull request by paigerube14**
Need to add in redhat-chaos supplemental quay images to use in tests for PR: https://github.com/openshift/release/pull/34844/

CC: @chaitanyaenr 
Should we go ahead and update the org name on quay before this gets merged?

### CODE REVIEW

**Comment by chaitanyaenr** [comment]
@paigerube14 Yes, let's update the org name to redhat-chaos.

**Comment by smg247** [comment]
@paigerube14, we are seeing errors with the mirroring here.
```
error: unable to push manifest to registry.ci.openshift.org/chaos/cerberus:kraken-hub: denied
error: unable to push manifest to registry.ci.openshift.org/chaos/krkn:latest: denied
```
Can you correct this?

**Comment by paigerube14** [comment]
@smg247 how/where would I correct that? I think the quay images are public

**Comment by smg247** [comment]
I'm not really sure. Is something different about those 2 that errored? All the others seem to have worked...

**Comment by paigerube14** [comment]
@smg247 looking at the settings of those repos they all look the same... 

I was able to pull both the images locally with no issues: `docker pull quay.io/redhat-chaos/cerberus:kraken-hub`

Can you send me the job information you are seeing that on

**Comment by smg247** [comment]
I think the error is coming on the push. So maybe the manifest isn't supported for some reason?
Here is the latest execution: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-image-mirroring-supplemental-ci-images/1620874674248355840

**Comment by paigerube14** [comment]
@smg247 Ah, I found I hadn't invited the openshift robots on those 2 github repos. Doing that now and hopefully will be resolved once they are approved?

**Comment by smg247** [comment]
Hmm, the error message doesn't really point to that being the issue, but you never know...

**Comment by paigerube14** [comment]
@smg247 is there anywhere that has a list of errors like this and possible solutions? Even if its a few solutions. Like you said it doesnt seem like it points to that issue but could fix...

**Comment by smg247** [comment]
Not that I know of, unfortunately. This is just standard openshift image-registry stuff. I am not an expert in it. Essentially, this job is just going through your file and running `oc image mirror` for each line: https://github.com/openshift/release/blob/c07f9620eef5bef2b64191e38c8fe1c1b6a4334d/ci-operator/jobs/infra-image-mirroring.yaml#L908-L921

**Comment by hongkailiu** [comment]
```bash
oc get ns chaos
Error from server (NotFound): namespaces "chaos" not found
```

Probably this is the reason.
I will update our doc about it.

**Comment by hongkailiu** [comment]
It is green now after

```console
oc create namespace chaos --as system:admin
namespace/chaos created
```

**Pull request merged**
