### PR TITLE
Promote submariner-addon to stolostron 2.6

### PR DESCRIPTION
**Pull request by dfarrell07**
Hopefully this will fix CI.

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

**Comment by dfarrell07** [comment]
I really hate self-merging, but I'm 80% sure this is breaking CI and 95% sure it will not make the situation worse. I don't know of anyone else online who knows this system. Discussion here: https://app.slack.com/client/T027F3GAJ/C01KV8QDATA/thread/C01KV8QDATA-1655409571.765029

/approve /lgmt

**Comment by dfarrell07** [comment]
I guess we can't self-approve. Yay for a good review system, boo for still-breaking CI.

**Review by gurnben — APPROVED** [review]
LGTM!

**Comment by dfarrell07** [comment]
Those jobs always fail here. :sweat_smile: 

IMHO we just need a /lgtm label now.

**Pull request merged**
