### PR TITLE
hosted loki: collect promtail metrics

### PR DESCRIPTION
**Pull request by vrutkovs**
* Secure promtail metrics using oauth-proxy
* Add ServiceMonitor to collect promtail metrics (we create a Service for oauth-proxy access anyway)

Re-introduces #17500

### CODE REVIEW

**Comment by vrutkovs** [comment]
/hold

e2e-aws passes, e2e-gcp is probably flaking

/retest

**Review by periklis — COMMENTED** [review]
Looks good to me. @vrutkovs Did you succeed running some successful rehearsals on that?

**Comment by vrutkovs** [comment]
/hold

Yup, its good to go, no alerts caused by promtail

**Review by periklis — APPROVED** [review]
/lgtm

**Pull request merged**
