### PR TITLE
Add runtime-utils to prow

### PR DESCRIPTION
**Pull request by adambkaplan**
/assign @stevekuznetsov 

/cc @bparees @gabemontero

### CODE REVIEW

**Comment by gabemontero** [comment]
assuming additions under the `ci-operator` dir don't make sense until *after* this PR merges @adambkaplan ?

**Comment by adambkaplan** [comment]
@gabemontero correct - need to land https://github.com/openshift/runtime-utils/pull/2 first

**Comment by hongkailiu** [comment]
@adambkaplan 
LMK when the dep. gets merged.

**Comment by adambkaplan** [comment]
@hongkailiu I should have clarified - this is a blocker to set up tests. Otherwise we need to green-button merge https://github.com/openshift/runtime-utils/pull/2

**Comment by adambkaplan** [comment]
Order as I under stand it:
1. Enable prow and tide
2. Merge PR to set up our makefile and build machinery
3. Add another PR here to enable blocking tests

**Comment by hongkailiu** [comment]
@adambkaplan 
Do you want (with the current PR) to use Tide as a merge-bot for `openshift/runtime-utils`?

@petr-muller 
If we merge this PR, Tide will work for `openshift/runtime-utils`, right?
Then @adambkaplan can add tests via ci-operator config.

**Comment by adambkaplan** [comment]
> Do you want (with the current PR) to use Tide as a merge-bot for openshift/runtime-utils?

@hongkailiu correct - use the same tooling for `openshift/runtime-utils` as the rest of the org.

**Comment by hongkailiu** [comment]
Thanks for confirmation, @adambkaplan 
Let us wait for confirmation from @petr-muller because I know that the set up is kind of tricky and undoing causes more work.

**Comment by hongkailiu** [comment]
got the green light from Petr.
Let us try

/lgtm
/approve

**Comment by hongkailiu** [comment]
@adambkaplan 

You can lgtm and aprr on https://github.com/openshift/runtime-utils/pull/2 when you ready to merge it.
Tide should respond.

**Pull request merged**
