### PR TITLE
openshift/os: Use coreos-assembler:4.11 for 4.11

### PR DESCRIPTION
**Pull request by HuijingHei**
To make the openshift branching 4.11

### CODE REVIEW

**Comment by HuijingHei** [comment]
The error seems need to remove `fedora` and `ocp_builder_rhel-8-golang-1.17-openshift-4.11` in `base_images`, do we need them?
```
time="2022-06-28T08:40:24Z" level=error msg="Failed to load CI Operator configuration" error="failed to load ci-operator config (error unmarshaling JSON: json: cannot unmarshal number into Go struct field ImageStreamTagReference.base_images.tag of type string)" source-file=ci-operator/config/openshift/os/openshift-os-release-4.11.yaml
```

**Comment by travier** [comment]
/hold
While we figure out the issue

**Comment by HuijingHei** [comment]
> It could be that `fedora:36` and `ocp:rhel-8-golang-1.17-openshift-4.11` don't exist as ImageStreamTags?

No idea where to check, any suggestions?

**Pull request closed without merging**
