### PR TITLE
WIP rehearsals for netobserv 

### PR DESCRIPTION
**Pull request by memodi**
WIP rehearsals for netobserv

### CODE REVIEW

**Comment by memodi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-arm-f28-netobserv

**Comment by memodi** [comment]
@Amoghrd - feel free to use this PR to run rehearsals for regression

**Comment by Amoghrd** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-multi-nightly-aws-ipi-arm-f28-netobserv

**Comment by memodi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-amd-f28-netobserv

**Comment by memodi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-multi-nightly-aws-ipi-arm-f28-netobserv

**Comment by Amoghrd** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-multi-nightly-aws-ipi-arm-f28-netobserv

**Comment by Amoghrd** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-aws-ipi-amd-f14-netobserv

**Comment by Amoghrd** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-aws-ipi-arm-f28-netobserv

**Comment by memodi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-multi-nightly-aws-ipi-amd-f28-netobserv

**Comment by memodi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-multi-nightly-aws-ipi-amd-f60-netobserv

**Comment by memodi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-multi-nightly-aws-ipi-arm-f28-netobserv

**Comment by Amoghrd** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-multi-nightly-aws-ipi-amd-f28-netobserv

**Pull request closed without merging**
