### PR TITLE
bump sample operator to golang 1.11 for v4.2 and later

### PR DESCRIPTION
**Pull request by gabemontero**
@openshift/sig-developer-experience fyi /ptal

Jira https://jira.coreos.com/browse/DEVEXP-345

### CODE REVIEW

**Comment by gabemontero** [comment]
also posted commit to add @adambkaplan to the OWNERS file

**Comment by coreydaley** [comment]
@gabemontero 
Interesting, your above comment did not assign it to me, maybe because of the words after the command, i think all you can have after the command is github ids

**Comment by coreydaley** [comment]
@stevekuznetsov looks like slash commands aren't working for this pull request.  Any thoughts?

**Comment by petr-muller** [comment]
/assign @coreydaley 

I think we had some webhook delivery issues yesterday.

**Comment by gabemontero** [comment]
@coreydaley removed Alex as well thanks

**Pull request merged**
