### PR TITLE
debug winc script - 4.17 31276

### PR DESCRIPTION
**Pull request by weinliu**
/hold

### CODE REVIEW

**Comment by weinliu** [comment]
/pj-rehearse abort
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.17-debug-winc-aws-ipi

**Comment by weinliu** [comment]
Check if the patch works https://github.com/openshift/openshift-tests-private/pull/21732

**Comment by rrasouli** [comment]
@weinliu can you fix required test, I believe `make update` will sort it out

**Comment by weinliu** [comment]
> @weinliu can you fix required test, I believe `make update` will sort it out

The changes were used for trigging the test, this patch will not be requsted to get merged, I think we can leave it as-is.

**Comment by weinliu** [comment]
/pj-rehearse abort
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.17-debug-winc-nutanix-ipi

**Comment by weinliu** [comment]
/pj-rehearse abort
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.17-debug-winc-nutanix-ipi

**Comment by weinliu** [comment]
/pj-rehearse abort
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-nutanix-ipi

**Comment by weinliu** [comment]
/pj-rehearse abort
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-nutanix-ipi
wait added to check the proxy

**Comment by weinliu** [comment]
/pj-rehearse abort
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-nutanix-ipi
wait added to check the proxy

**Comment by weinliu** [comment]
/pj-rehearse abort
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-nutanix-ipi
wait added for debug

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.17-debug-winc-aws-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-nutanix-ipi

**Pull request closed without merging**
