### PR TITLE
Delete RC resources on api.ci

### PR DESCRIPTION
**Pull request by hongkailiu**
Blocking https://github.com/openshift/release/pull/17254

/cc @bradmwilliams @jupierce

### CODE REVIEW

**Comment by bradmwilliams** [comment]
We need to modify the release-controller generation script to not recreate these scripts or it will never pass CI

**Comment by bradmwilliams** [comment]
@hongkailiu You can test by commenting out this call in your repo:
https://github.com/openshift/release/blob/2e14729d7abb7c32851f969d5b79712d4fc38f79/hack/generators/release-controllers/generate-release-controllers.py#L223
If everything works, nothing should be put back into place.

**Comment by bradmwilliams** [comment]
@hongkailiu Do you have another PR that relocates the `images-origin-4.*.yaml` files over to `app.ci`?

**Comment by hongkailiu** [comment]
> @hongkailiu Do you have another PR that relocates the `images-origin-4.*.yaml` files over to `app.ci`?

They are basically defines only names of imagesgreams.
I believe they exist on app.ci already.

I am reluctant to move them over, because applying an incomplete yaml to an existing object (to another cluster) is tricky, e.g., would it be removing the fields that are not in the yaml?
I do not want to mess up with RC's streams if I do not have to. :)

**Comment by bradmwilliams** [comment]
Oh, I totally agree and understand.
I only ask because they are part of the "branching" instructions... i.e. they are used to create the "new" release imagestream at the time we branch.  So, come next release (4.10), we'll need to address the fact that they are now missing from the repo.

**Comment by hongkailiu** [comment]
> Oh, I totally agree and understand.
> I only ask because they are part of the "branching" instructions... i.e. they are used to create the "new" release imagestream at the time we branch. So, come next release (4.10), we'll need to address the fact that they are now missing from the repo.

Creating new ones are fine with me.
Could we leave comments about this in the branching doc?

**Comment by bradmwilliams** [comment]
Of course we can update the doc.
/lgtm

**Pull request merged**
