### PR TITLE
Move extended_templates into a block-merging job

### PR DESCRIPTION
**Pull request by 0xmichalis**
@bparees @stevekuznetsov

### CODE REVIEW

**Comment by bparees** [comment]
thanks @kargakis 
@jim-minter fyi  (@openshift/devex fyi)

**Comment by stevekuznetsov** [comment]
@bparees if this is taking 2 minutes to run tests I would like us to fold it into the conformance bucket (can we consider this feature conformance?)

**Comment by bparees** [comment]
@stevekuznetsov @jim-minter tried to do that and you denied him. For now this is the expedient path but i'd love to work with you to get it in there.  The problem is the TSB requires additional master-configuration and the current extended test framework approach does not allow for that configuration to be performed.

**Comment by stevekuznetsov** [comment]
Man, now I sound like a jerk, huh.

Yes, conformance will continue to run on a cluster installed with Ansible and if we do not have a means by which to install the TSB with Ansible we will not be able to run those tests as part of Conformance. This change LGTM

**Comment by kargakis** [comment]
@stevekuznetsov @bparees I am planning on updating the SQ tomorrow morning when I'll be at the top of my game and it will be empty. @stevekuznetsov I will also rebase test-infra and drop our SQ patches.

**Comment by stevekuznetsov** [comment]
ACK

**Comment by kargakis** [comment]
Deployed.

**Pull request merged**
