### PR TITLE
Add `acm-cli` and `policy-cli` to `stolostron`

### PR DESCRIPTION
**Pull request by dhaiducek**

### CODE REVIEW

**Review by gurnben — APPROVED** [review]
/lgtm
/approve

**Review by JustinKuli — APPROVED** [review]
LGTM

**Comment by dhaiducek** [comment]
/pj-rehearse ack

Sorry for the churn here. I got the fix rebased and pulled into this PR, so this is ready for re-review.

**Review by JustinKuli — APPROVED** [review]
/lgtm

**Pull request merged**
