### PR TITLE
Add nutanix, openstack powervs to techpreview

### PR DESCRIPTION
**Pull request by patrickdillon**
TechPreview Jobs:

- Add nutanix e2e
- Add openstack e2e
- Remove aws shared vpc (went GA in 4.15)

I attempted to add PowerVS to the techpreview jobs, but using the configuration from our periodics in the installer repo did not work:

https://github.com/openshift/release/blob/df52e063313688ceafe7fab18275aeb180cbca06/ci-operator/config/openshift/installer/openshift-installer-master__altinfra-periodics.yaml#L127-L143

This fails with:

```
time="2024-05-06T19:07:54Z" level=error error="[failed to validate configuration openshift/release/openshift-release-master__ci-4.16.yaml: invalid configuration: tests[33].literal_steps.pre[7].dependencies[0]: cannot determine source for dependency \"release:ppc64le-latest\" - this dependency requires a \"ppc64le-latest\" release, which is not configured, failed to validate configuration openshift/release/openshift-release-master__nightly-4.16.yaml: invalid configuration: tests[77].literal_steps.pre[7].dependencies[0]: cannot determine source for dependency \"release:ppc64le-latest\" - this dependency requires a \"ppc64le-latest\" release, which is not configured]"
time="2024-05-06T19:07:54Z" level=fatal msg="error validating configuration files"
make[1]: *** [Makefile:78: ci-operator-checkconfig] Error 1
```

### CODE REVIEW

**Review by vrutkovs — APPROVED** [review]

**Comment by patrickdillon** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.16-e2e-openstack-ovn-techpreview periodic-ci-openshift-release-master-ci-4.16-e2e-powervs-ovn-techpreview periodic-ci-openshift-release-master-ci-4.16-e2e-nutanix-ovn-techpreview

**Pull request merged**
