### PR TITLE
feat: nigthly job for konflux-ci on ocp v4.15

### PR DESCRIPTION
**Pull request by psturc**
https://issues.redhat.com/browse/KONFLUX-3169

* the job rehearsal job [has passed](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/52415/rehearse-52415-periodic-ci-redhat-appstudio-infra-deployments-main-ocp415-konflux-e2e-v415/1793661473264766976) ✅

### CODE REVIEW

**Comment by psturc** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-infra-deployments-main-ocp415-konflux-e2e-v415

**Comment by psturc** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-infra-deployments-main-ocp415-konflux-e2e-v415

**Comment by psturc** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-infra-deployments-main-ocp415-konflux-e2e-v415

**Comment by psturc** [comment]
/test all
/pj-rehearse periodic-ci-redhat-appstudio-infra-deployments-main-ocp415-konflux-e2e-v415

**Comment by psturc** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-infra-deployments-main-ocp415-konflux-e2e-v415

**Comment by psturc** [comment]
[CI failed on flakey test](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/52415/rehearse-52415-periodic-ci-redhat-appstudio-infra-deployments-main-ocp415-konflux-e2e-v415/1797976194486898688), not addressable in this PR

**Review by dheerajodha — APPROVED** [review]
/lgtm

**Review by kasemAlem — APPROVED** [review]

**Pull request merged**
