### PR TITLE
Switch from index image to bundle image

### PR DESCRIPTION
**Pull request by clobrano**
Switch to bundle image and operator-sdk instead of operator workflow and index image (deprecated)

see: https://docs.ci.openshift.org/docs/how-tos/testing-operator-sdk-operators/#building-an-index-deprecated

### CODE REVIEW

**Comment by slintes** [comment]
oh, that triggered also the green ones 🙈 

/pj-rehearse reject

**Comment by slintes** [comment]
this should not trigger the limited set again... ?!

/pj-rehearse auto-ack

**Comment by slintes** [comment]
seems to work

/lgtm

**Comment by slintes** [comment]
/pj-rehearse pull-ci-medik8s-machine-deletion-remediation-main-4.13-openshift-e2

**Comment by clobrano** [comment]
> @slintes: job(s): pull-ci-medik8s-machine-deletion-remediation-main-4.13-openshift-e2 either don't exist or were not found to be affected, and cannot be rehearsed
:thinking: 
             
/pj-rehearse pull-ci-medik8s-machine-deletion-remediation-main-4.13-openshift-e2e

**Comment by slintes** [comment]
Oh missed a trailing "e" when triggering the failed test 😄 
And you just triggered tests again 😉 

Shortcut:
/pj-rehearse ack

**Comment by clobrano** [comment]
> Shortcut:
/pj-rehearse ack

doh!

**Pull request merged**
