### PR TITLE
OPP with ACM 2.11 and OCP 4.16 and OCP 4.17

### PR DESCRIPTION
**Pull request by vboulos**
This PR updates the existing OPP jobs to run with ACM 2.11 on OCP 4.16 and OCP 4.17

### CODE REVIEW

**Comment by vboulos** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.16-interop-openshift-plus-interop-aws periodic-ci-stolostron-policy-collection-main-opp-ocp4.17-interop-openshift-plus-interop-aws

**Comment by vboulos** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.16-interop-openshift-plus-interop-aws

**Comment by vboulos** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.16-interop-openshift-plus-interop-aws

**Review by gparvin — APPROVED** [review]

**Pull request merged**
