### PR TITLE
Fix vSphere and AWS CCM OVN Hybrid install

### PR DESCRIPTION
**Pull request by saifshaikh48**
Stop using deprecated step `ipi-conf-techpreview-do-not-use` and i
nstead use `FEATURE_SET` env var to keep this job testing tech preview.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
By changing this, you will break any cluster/CI that is for earlier releases than 4.12. Since the rehearsal suggests that only 4.13 is affected, this is probably OK to proceed with.

Do you have other TechPreview jobs on WINC? It may be worth dropping this in favour of a generic TechPreviewNoUpgrade test

**Comment by saifshaikh48** [comment]
@JoelSpeed Yep we do for our other CCM jobs ([Azure](https://github.com/openshift/release/pull/38947), AWS)

**Comment by saifshaikh48** [comment]
@JoelSpeed We'll also be removing all non-master CCM jobs anyway so there should be no problem, thanks for the heads up

**Comment by saifshaikh48** [comment]
Will wait for https://github.com/openshift/release/pull/39855 to merge before putting this PR through

**Comment by saifshaikh48** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-vsphere-e2e-ccm-install

**Comment by saifshaikh48** [comment]
/pj-rehearse periodic-ci-openshift-windows-machine-config-operator-master-vsphere-e2e-ccm-install

**Comment by saifshaikh48** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-vsphere-e2e-ccm-install

**Comment by saifshaikh48** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-vsphere-e2e-ccm-install

**Comment by saifshaikh48** [comment]
/pj-rehearse periodic-ci-openshift-windows-machine-config-operator-master-vsphere-e2e-ccm-install

**Comment by saifshaikh48** [comment]
/pj-rehearse periodic-ci-openshift-windows-machine-config-operator-master-vsphere-e2e-ccm-install

**Review by aravindhp — APPROVED** [review]

**Pull request merged**
