### PR TITLE
Add 4.6->4.7 ovn upgrade job to PR test jobs

### PR DESCRIPTION
**Pull request by jluhrsen**
Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>

### CODE REVIEW

**Comment by jluhrsen** [comment]
@maintainers, this is my first time trying to add a presubmit CI job. I took most of the job config from
examples in ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml which
run the upgrade jobs we want to see against ovn-kubernetes PRs.

**Comment by danwinship** [comment]
@jluhrsen for the most part, jobs are defined in `ci-operator/config/$ORG/$REPO` and then you run `make jobs` and it "compiles" them to `ci-operator/jobs/$ORG/$REPO`. In some cases some stuff has to be done directly in `/jobs/` but usually not

**Comment by jluhrsen** [comment]
> @jluhrsen for the most part, jobs are defined in `ci-operator/config/$ORG/$REPO` and then you run `make jobs` and it "compiles" them to `ci-operator/jobs/$ORG/$REPO`. In some cases some stuff has to be done directly in `/jobs/` but usually not

ok, thanks for the help. let me update this doing it the right way.

/hold

**Pull request closed without merging**
