### PR TITLE
Fix golang version for openshift/api

### PR DESCRIPTION
**Pull request by tnozicka**
/cc @marun @sttts

### CODE REVIEW

**Comment by tnozicka** [comment]
/hold
for rehearsals

**Comment by tnozicka** [comment]
need https://github.com/openshift/api/pull/746 first

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by tnozicka** [comment]
(https://github.com/openshift/api/pull/746 merged)

**Comment by tnozicka** [comment]
green
/hold cancel

**Pull request merged**
