### PR TITLE
SPLAT-1231: Removed old ip assignment logic from CI scripts.

### PR DESCRIPTION
**Pull request by vr4manta**
[SPLAT-1231](https://issues.redhat.com/browse/SPLAT-1231)

## Changes
- Removed old unused IP logic from scripts for vSphere

### CODE REVIEW

**Comment by vr4manta** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted pull-ci-openshift-assisted-installer-master-edge-e2e-vsphere-assisted pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-externallb-ovn

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-externallb-ovn
/retest-required

**Comment by vr4manta** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-master-edge-e2e-vsphere-assisted pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted pull-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted

**Review by adriengentil — APPROVED** [review]

**Comment by mhanss** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-vsphere-agent-disc-compact-f14

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-vsphere-agent-disc-compact-f14

**Comment by mhanss** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-vsphere-agent-disc-compact-f14

**Comment by mhanss** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-vsphere-agent-ha-f14

**Comment by mhanss** [comment]
It seems the job failures are not related to the changes, therefore, the changes are good to go.
/lgtm

**Comment by mhanss** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-vsphere-agent-compact-fips-f14

**Comment by mhanss** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-vsphere-agent-compact-fips-f14

**Pull request merged**
