### PR TITLE
Fixing openshift-cluster-autoscaler-operator-master.yaml to use dockerfile from ocp-build-data

### PR DESCRIPTION
**Pull request by alvaroaleman**

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Could you please update the PR description to explain the problem that is being fixed by this PR, it's not immediately obvious from the code changes.

Since this will now not match the 4.6 and 4.7 build configurations, should they also be updated to match?

**Comment by alvaroaleman** [comment]
@JoelSpeed this PR is autogenerated by a tool that syncs the config from whats configured in the ocp-build-data repo, see http://post-office.corp.redhat.com/archives/aos-devel/2020-August/msg00110.html

Release 4.6 and 4.7 will get fast-forwarded based on the master configuration

**Comment by JoelSpeed** [comment]
/lgtm

Got it, the differences between the files are very minor, looks like we should be ok with the switch

**Pull request merged**
