### PR TITLE
add cluster logging operator e2e to elastic + aggregated logging repos

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@openshift/openshift-team-logging fyi, this will add the CLO e2e to the EO and OAL repository PRs.

/hold
(want to see rehearsals pass)

**Comment by bparees** [comment]
@vimalk78 @ewolinetz i see this has passed rehearsal now.  Are we confident enough to merge it, or is it still flaky and merging it will result in blocked PRs?

**Comment by vimalk78** [comment]
> @vimalk78 @ewolinetz i see this has passed rehearsal now. Are we confident enough to merge it, or is it still flaky and merging it will result in blocked PRs?

I am more inclined to merging `ARTIFACT_DIR=/tmp/artifacts/logging-artifacts` change so that we get correct artifacts to check failures. My PR for fixing LF tests is merged. i can open an temp PR to check further.

**Comment by bparees** [comment]
@vimalk78 ok i've created this PR to fix the path on the existing jobs:
https://github.com/openshift/release/pull/8169

and i'll leave this PR open until you're satisfied the new jobs it introduces are reliable enough to merge.  but we should merge it asap since until we do, someone can break the CLO by merging bad changes to the EO or OAL repos.

**Comment by vimalk78** [comment]
```
error: error when creating "olm_deploy/operatorregistry/service.yaml": Post https://api.ci-op-1m8vdx98-4b908.origin-ci-int-aws.dev.rhcloud.com:6443/api/v1/namespaces/openshift-operators-redhat/services: read tcp 172.16.50.198:49296->35.168.224.253:6443: read: connection reset by peer
[ERROR] PID 242: hack/test-e2e-olm.sh:9: `ELASTICSEARCH_OPERATOR_NAMESPACE=openshift-operators-redhat olm_deploy/scripts/catalog-deploy.sh` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/test-e2e-olm.sh:9: `ELASTICSEARCH_OPERATOR_NAMESPACE=openshift-operators-redhat olm_deploy/scripts/catalog-deploy.sh`
[INFO]   Exiting with code 1.
```
/retest

**Comment by vimalk78** [comment]
/retest

mirros issues
```

http://base-4-5.ocp.svc/rhel-server-ose/repodata/cf5bf30f7fe04d3fc40e6441fbce8edcbafc883bd7da36defa9a969a0be6828d-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://base-4-5.ocp.svc/rhel-server-ose/repodata/cf5bf30f7fe04d3fc40e6441fbce8edcbafc883bd7da36defa9a969a0be6828d-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
```

**Comment by vimalk78** [comment]
/retest

```
2020/04/07 14:03:30 Build cluster-logging-operator failed, printing logs:

http://base-4-5.ocp.svc/rhel-server-ose/repodata/cf5bf30f7fe04d3fc40e6441fbce8edcbafc883bd7da36defa9a969a0be6828d-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://base-4-5.ocp.svc/rhel-server-ose/repodata/cf5bf30f7fe04d3fc40e6441fbce8edcbafc883bd7da36defa9a969a0be6828d-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.

```

**Pull request merged**
