### PR TITLE
PLNSRVCE-517 add builder images to CI

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by gabemontero** [comment]
So its been a while since we did a rehearsal here.  The one here is failing with 

` .ci/override-tekton-bundle.sh: line 5: JVM_BUILD_SERVICE_PR_SHA: unbound variable `

Now, when we create PR in the jvm-build-service repo, $JVM_BUILD_SERVICE_PR_SHA is always set, so there is no problem.

So, in theory I could merge this as is and we can continue testing with jvm-build-service PRs, but our CI has been on fire enough the last 36 hours, so I would like to get some validation with the rehearsal here before we merge this, and that is one reason why I don't want to do just merge this with the failing rehearsal. 

Plus, when I start creating periodics / cron jobs to start testing bigger source code repos with bigger openshift clusters, I'll have to fix this anyway.

I'll post back here with a retest when I have this handled.

**Comment by gabemontero** [comment]
` .ci/override-tekton-bundle.sh: line 6: JVM_BUILD_SERVICE_PR_SHA: unbound variable `

so it grabbed the right level of jvm-build-service:

`2022-07-29T19:55:21.571017504Z {"command":"PWD=/go/src/github.com/redhat-appstudio/jvm-build-service  git checkout FETCH_HEAD","component":"clonerefs","file":"k8s.io/test-infra/prow/pod-utils/clone/clone.go:83","func":"k8s.io/test-infra/prow/pod-utils/clone.Run.func2","level":"info","msg":"Ran command","output":"Note: checking out 'FETCH_HEAD'.\n\nYou are in 'detached HEAD' state. You can look around, make experimental\nchanges and commit them, and you can discard any commits you make in this\nstate without impacting any branches by performing another checkout.\n\nIf you want to create a new branch to retain commits you create, you may\ndo so (now or later) by using -b with the checkout command again. Example:\n\n  git checkout -b new_branch_name\n\nHEAD is now at c1811af... Merge pull request #147 from gabemontero/override-bundle-prs-only\n","severity":"info","time":"2022-07-29T19:55:21Z"}`

so my local bash testing produced different results than what occurs in CI (entirely possible that my internet search for how to check for unbound vars produced a bad recipe for openshift ci) around checking for unbound bash variables.

I even found https://github.com/redhat-appstudio/infra-deployments/blob/main/hack/preview.sh#L9-L12 
does it matter if the `then` is on the same line? but then again I don't think preview.sh is called from openshift ci

ran `shellcheck` against it, and it did not complain

I guess I can try param expansion and check for the default

sigh I hate bash

**Comment by gabemontero** [comment]
so I opened https://github.com/redhat-appstudio/jvm-build-service/pull/148 but I'll wait on review of my bash this time

if it is merged, we can retest here

**Comment by stuartwdouglas** [comment]
@gabemontero all good now

**Review by Michkov — APPROVED** [review]

**Pull request merged**
