### PR TITLE
NETOBSERV-1594: Remove SKIPPED profiles for NetObserv

### PR DESCRIPTION
**Pull request by Amoghrd**
Based on previous regression runs on ReportPortal have removed the profiles where the tests were skipped

### CODE REVIEW

**Review by memodi — APPROVED** [review]
/lgtm

**Comment by Amoghrd** [comment]
These new checks are failing due to timeout and `error="lstat ./clusters/hosted-mgmt/pools: no such file or directory"` think can be ignored

**Comment by Amoghrd** [comment]
PTAL @kuiwang02 Removing profiles where Network_Observability tests should not run

**Comment by kuiwang02** [comment]
I am ok.

cc @liangxia to approve it if there is no more comment.
Thanks

**Pull request merged**
