### PR TITLE
Update image mirroring for 3scale-interop-tests

### PR DESCRIPTION
**Pull request by mdujava**
Update image to latest GA

### CODE REVIEW

**Comment by Sau1506mya** [comment]
@mdujava , just confirming v2.13 will not be used in future for any testing in any of the platforms related to OCP?

**Comment by mdujava** [comment]
> @mdujava , just confirming v2.13 will not be used in future for any testing in any of the platforms related to OCP?

Correct

**Comment by Sau1506mya** [comment]
> > @mdujava , just confirming v2.13 will not be used in future for any testing in any of the platforms related to OCP?
> 
> Correct

Cool then, we are good to merge this PR :)

**Pull request merged**
