### PR TITLE
WINC-755: [upi-vsphere] Support Windows Server 2022

### PR DESCRIPTION
**Pull request by saifshaikh48**
This PR updates the scripts used in the WMCO `platform=none` tests to use
the Windows Server 2022 golden image template *with Docker* to create VMs.
This is done in favor of using the image without Docker runtime installed to
maintain compatibility with older releases where containerd is not supported.

### CODE REVIEW

**Comment by saifshaikh48** [comment]
/hold

until https://github.com/openshift/windows-machine-config-operator/pull/1035 merges

**Comment by selansen** [comment]
So same image will be used even for master repo CI jobs, Am I right? (even though we completely moved to containerd in master, this image will continue to have docker)

**Comment by saifshaikh48** [comment]
/unhold

functionality PR https://github.com/openshift/windows-machine-config-operator/pull/1035 has merged

**Pull request merged**
