### PR TITLE
OTA-1016: CVO: Add hypershift conformance presubmit

### PR DESCRIPTION
**Pull request by petr-muller**
Hypershift is becoming increasingly important and with CVO being one of the major OCP components we may want to be sure we do not break it.

### CODE REVIEW

**Comment by petr-muller** [comment]
e2e-hypershift failed `EnsureLimitedEgressTrafficToManagementKAS` which seems unrelated:
```
TestCreateClusterPrivate/EnsureHostedCluster/EnsureNetworkPolicies/EnsureLimitedEgressTrafficToManagementKAS
{Failed
=== RUN   TestCreateClusterPrivate/EnsureHostedCluster/EnsureNetworkPolicies/EnsureLimitedEgressTrafficToManagementKAS
     util.go:824: Connecting to kubernetes endpoint on: https://172.20.0.1:6443
=== CONT  TestCreateClusterPrivate/EnsureHostedCluster/EnsureNetworkPolicies/EnsureLimitedEgressTrafficToManagementKAS
     util.go:851: private router pod was unexpectedly allowed to reach the management KAS. stdOut: . stdErr: Internal error occurred: error executing command in container: container is not created or running
--- FAIL: TestCreateClusterPrivate/EnsureHostedCluster/EnsureNetworkPolicies/EnsureLimitedEgressTrafficToManagementKAS (22.66s) }
```

**Comment by petr-muller** [comment]
Let's get more data:
/pj-rehearse

**Comment by petr-muller** [comment]
4.14 e2e-hypershift failed with a single failure that seems unrelated:

```
: TestCreateClusterPrivate/ValidateHostedCluster
{Failed  === RUN   TestCreateClusterPrivate/ValidateHostedCluster
   ...
    util.go:1515: condition AWSEndpointAvailable status [False] doesn't match the expected status [True]
    util.go:1526: Failed to validate HostedCluster conditions in 10m0s: timed out waiting for the condition
    --- FAIL: TestCreateClusterPrivate/ValidateHostedCluster (1716.29s)
```

**Comment by petr-muller** [comment]
Let's do one more run
/pj-rehearse

**Comment by petr-muller** [comment]
This time there's an issue in the conformance run, but seems unrelated to CVO:

```
[sig-cli] oc builds complex build start-build
{  fail [github.com/openshift/origin/test/extended/cli/builds.go:290]: Unexpected error:
    <*fmt.wrapError | 0xc0056fcf40>: 
    Error running /usr/bin/oc --namespace=e2e-test-oc-builds-vdrf6 --kubeconfig=/tmp/secret/nested_kubeconfig start-build --from-webhook https://af163312cd4c443/apis/build.openshift.io/v1/namespaces/e2e-test-oc-builds-vdrf6/buildconfigs/ruby-sample-build/webhooks/secret101/generic:
    StdOut>
    Unable to connect to the server: dial tcp: lookup af163312cd4c443 on 172.30.0.10:53: no such host
    StdErr>
    Unable to connect to the server: dial tcp: lookup af163312cd4c443 on 172.30.0.10:53: no such host
    exit status 1
...
[sig-cli] oc builds complex build webhooks CRUD
{  fail [github.com/openshift/origin/test/extended/cli/builds.go:233]: Expected
    <string>: Name:		ruby-sample-build
....
    to contain substring
    <string>: https://af163312cd4c443/apis/build.openshift.io/v1/namespaces/e2e-test-oc-builds-5r8z5/buildconfigs/ruby-sample-build/webhooks/<secret>/github
```

Overall the pass rate and general noisiness of the jobs is very good, I don't see why we should not run both on CVO repo.
/pj-rehearse ack

**Review by wking — APPROVED** [review]
/lgtm

**Comment by petr-muller** [comment]
/hold cancel
/test ordered-prow-config

Looks like failovers back and forth...

**Pull request merged**
