### PR TITLE
minor diff fixes between jenkins and default template; fix passing of focus/skip into ginkgo

### PR DESCRIPTION
**Pull request by gabemontero**
Fixes https://github.com/openshift/release/issues/3647

@stevekuznetsov fyi

### CODE REVIEW

**Comment by gabemontero** [comment]
changing just the template did not trigger rehearsals

looking to make a dummy change to the config or presubmit

**Comment by gabemontero** [comment]
e2e-gcp failure was a known 3.11 vs. 4.0 client plugin test thing which https://github.com/openshift/jenkins-client-plugin/pull/264 will sort out

**Comment by gabemontero** [comment]
/assign @stevekuznetsov 
/assign @bparees 
/assign @smarterclayton 

PTAL ... this gets jenkins back to actually having ginkgo process the focus so it executes the jenkins pipeline tests in openshift/origin 's 3.11 pipeline.go

@bparees I assigned you for historical reasons given you work that resulted in https://github.com/openshift/origin/blob/release-3.11/test/extended/setup.sh#L7-L9 where you noted --ginkgo.focus no longer worked.

When I found that, I moved to using `-focus` instead, and saw the tests get picked up in the rehearsal job (after I temporarily changed the presubmit to get the rehearsal job to run)

@stevekuznetsov @smarterclayton I refrained for now of updating the other templates in openshift-ansible, not know if you all really wanted `e2e-gcp` to run tests.  

But I can update those along these lines if you want.

See my findings at https://github.com/openshift/release/issues/3647#issuecomment-489776657 about seeing no ginkgo suites getting picked up in openshift/origin PRs as well.

**Comment by gabemontero** [comment]
I keep forgetting @petr-muller and @droslean in the fun ... fyi/ptal

**Comment by gabemontero** [comment]
@droslean when you get the chance see about deleting https://github.com/openshift/release/pull/3691#issuecomment-490475451, https://github.com/openshift/release/pull/3691#issuecomment-490475501, and https://github.com/openshift/release/pull/3691#issuecomment-490482347

github future comment snafu

**Comment by bparees** [comment]
they're all in the past now so it should be fine.

**Pull request merged**
