### PR TITLE
capo: Run verify and test in main and openshift modules

### PR DESCRIPTION
**Pull request by mdbooth**
* [X] Merge https://github.com/openshift/cluster-api-provider-openstack/pull/281

### CODE REVIEW

**Comment by mdbooth** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-openstack-main-test-openshift
/pj-rehearse pull-ci-openshift-cluster-api-provider-openstack-main-test

**Comment by mdbooth** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-openstack-main-test-openshift
/pj-rehearse pull-ci-openshift-cluster-api-provider-openstack-main-test

**Comment by mdbooth** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-openstack-main-test

**Review by mandre — COMMENTED** [review]
/lgtm
/approve

**Comment by mdbooth** [comment]
Note that this PR no longer modified `test`, which is presumably why pj-rehearse didn't run it. However, it seems that running it manually still fails. This presumably means this test failure is a separate issue unrelated to this PR.

/pj-rehearse pull-ci-openshift-cluster-api-provider-openstack-main-test

**Review by mandre — COMMENTED** [review]
/lgtm

**Pull request merged**
