### PR TITLE
Adding prow checks for a branch of integreatly operator

### PR DESCRIPTION
**Pull request by maksymvavilov**
Adding porw cheks for [this](https://github.com/integr8ly/integreatly-operator/tree/MGDAPI-3256-working) branch

### CODE REVIEW

**Comment by makslion** [comment]
I'm fine with rehearses failing with `missing dependencies: "openshift_release_golang-1.16"` This branch is to upgrade the go version of the operator

**Comment by makslion** [comment]
The format fails because of the go version - it changes autogenerated files and makes the `format` test sad about this. This is fine to me

**Comment by laurafitzgerald** [comment]
/approve
pr to fix the rehearsals -> https://github.com/integr8ly/integreatly-operator/pull/2432

**Pull request merged**
