### PR TITLE
[WIP] [TEST ONLY] Serverless: Generate CI configs for serverless-operator repo automatically

### PR DESCRIPTION
**Pull request by mgencur**
The pj-rehearse tests depend on https://github.com/openshift-knative/serverless-operator/pull/2380 which needs to be merged first.

### CODE REVIEW

**Comment by mgencur** [comment]
/pj-rehearse pull-ci-openshift-knative-serverless-operator-main-413-operator-e2e-aws-ocp-413

**Comment by skonto** [comment]
@mgencur the perf tests are being removed from the release-next branch see https://github.com/openshift-knative/serving/pull/525. Once that is merged I am going to re-run the action (https://github.com/openshift-knative/hack/actions/runs/6786620981) at the hack repo to get the right targets in.

**Comment by mgencur** [comment]
> @mgencur the perf tests are being removed from the release-next branch see https://github.com/openshift-knative/serving/pull/525. Once that is merged I am going to re-run the action (https://github.com/openshift-knative/hack/actions/runs/6786620981)

Good to know, thanks. This is just an example PR that will be generated by openshift-knative/hack. The point is mostly to check the serverless-operator CI config which is new.

**Pull request closed without merging**
