### PR TITLE
oVirt: add ovirt upgrade perodics

### PR DESCRIPTION
**Pull request by Gal-Zaidman**
Signed-off-by: Gal-Zaidman <gzaidman@redhat.com>

### CODE REVIEW

**Comment by sdodson** [comment]
/lgtm
/hold
What was in the rebase/force push? I was just looking over the previous test results which looked like a test failure but the upgrade seems to have run so acceptable to start providing signal.

**Comment by Gal-Zaidman** [comment]
> /lgtm
> /hold
> What was in the rebase/force push?

Running make jobs caused a lot of updates (5000 files), thought I might need to rebase, but it didn't help...
Don't know what is the reason but I don't think my patch should update 5000 files so I kept generated-config failing.

>I was just looking over the previous test results which looked like a test failure but the upgrade seems to have run so acceptable to start providing signal.

Well I ran it twice and upgrade was successful on the first [1] but failed on
"[sig-arch][Feature:ClusterUpgrade] Cluster should remain functional during upgrade [Disruptive] [Serial] [Suite:openshift]"
which is across the board as you can see on [2][3].

We moved the whole CI to a new engine today so I'm interested to see what the next runs will do.

[1] https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/origin-ci-test/pr-logs/pull/openshift_release/9659/rehearse-9659-release-openshift-ocp-installer-e2e-ovirt-upgrade-4.4-stable-to-4.5-ci/1272898656864833536
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1843183
[3] https://search.apps.build01.ci.devcluster.openshift.com/?search=Cluster+should+remain+functional+during+upgrade&maxAge=168h&context=1&type=junit&name=upgrade.*4.5&maxMatches=5&maxBytes=20971520&groupBy=job

**Comment by sdodson** [comment]
Looks like we need to run `make jobs` as that ci job is failing.

**Comment by Gal-Zaidman** [comment]
@sdodson 
ran `make jobs` like you asked and committed the output.
I really don't know what is special about this PR that causes 5000+ changed files. 
I thought that such a change is probably unrelated and should be pushed on a separate PR, but I will leave if for the reviews to decide

**Comment by sdodson** [comment]
Hmm, I was able to get that to go away by rebasing upon master.

**Comment by sdodson** [comment]
/lgtm
It's concerning that both of those failed during initial version installation but lets hope that's a fluke.

**Comment by Gal-Zaidman** [comment]
> /lgtm
> It's concerning that both of those failed during initial version installation but lets hope that's a fluke.

We are upgrading our CI env to run on ovirt-4.4.
It wasn't a 100% smooth transition :)

**Pull request merged**
