### PR TITLE
ci-operator/openshift/os: Re-enable promotion for 4.12/master

### PR DESCRIPTION
**Pull request by travier**
Hopefully this should fix forwarding master to non frozen releases.

### CODE REVIEW

**Review by jmguzik — COMMENTED** [review]
Please run `make openshift-image-mirror-mappings` and push as a separate commit here.

**Comment by travier** [comment]
I don't understand what this list of image mappings is for. We don't want to publish this image as it's just the source.

**Comment by travier** [comment]
/hold
We don't want that image to be part of an OCP release

**Comment by travier** [comment]
Updated to hopefully do the right thing now.

**Comment by miabbott** [comment]
Seems to make sense to me; but I'm going to defer to @jmguzik 

/approve

**Comment by jmguzik** [comment]
Let's give it a try.
/lgtm

**Pull request merged**
