### PR TITLE
LPTOCPCI-586:  Fix  jaegertracing-jaeger results do not contain junit_ prefix

### PR DESCRIPTION
**Pull request by amp-rh**
[Fix opensift-ci Interop scenario jaegertracing-jaeger results do not contain junit_ prefix when fails](https://issues.redhat.com/browse/LPTOCPCI-586)

### CODE REVIEW

**Comment by amp-rh** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.14-lp-interop-jaeger-interop-aws

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
