### PR TITLE
switch to aws-opendatahub cluster profile

### PR DESCRIPTION
**Pull request by riprasad**

### CODE REVIEW

**Comment by riprasad** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-model-controller-release-v0.11.0-alpha-fvt

**Comment by riprasad** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-model-controller-release-v0.11.0-alpha-fvt

**Comment by israel-hdez** [comment]
@riprasad  There are other two jobs for odh-model-controller. Don't those need to change too?

**Comment by riprasad** [comment]
@israel-hdez Other jobs doesn't make use of cluster profiles

**Review by israel-hdez — APPROVED** [review]

**Pull request merged**
