### PR TITLE
Removed e2e-ai-operator-ztp-capi job from openshift-cluster-api-provider-agent-master

### PR DESCRIPTION
**Pull request by eranco74**
There is no way to run the operator flow from any repo other than assisted-service

### CODE REVIEW

**Comment by eranco74** [comment]
cc: @osherdp @adriengentil

**Comment by adriengentil** [comment]
Maybe you can you try with this index instead: https://github.com/openshift/release/pull/32685/files#diff-348f7d1f1bb9b5e00e50537ad128fc243b1770a28792603ca443d0e2380e7c08R14-R17

Is is made to reference container images in quay instead of the internal registry of Prow.

**Comment by eranco74** [comment]
Last attempt to fix this job
https://github.com/openshift/release/pull/33240

**Comment by eranco74** [comment]
Job is passing now

**Pull request closed without merging**
