### PR TITLE
Remove compact conf step

### PR DESCRIPTION
**Pull request by andfasano**
Removed compact conf step to use directly `DEVSCRIPTS_CONFIG` in order to simplify the job definition. Hopefully this should help also with the sippy warning

### CODE REVIEW

**Comment by vrutkovs** [comment]
/approve

Not sure why rehearsals don't run

**Comment by petr-muller** [comment]
/hold
I'd like to have rehearsals, and I'd also like to see why we don't have rehearsals.

**Comment by petr-muller** [comment]
Turns out missing rehearsals are a missing feature of pj-rehearse: https://github.com/openshift/ci-tools/pull/2016

/approve
/lgtm

@andfasano feel free to unhold if needed: the ci-tools PR will hopefully merge in a day or two so we'll get rehearsals after that, but feel free to merge if this needs to go in faster.

**Comment by vrutkovs** [comment]
/refresh

Not sure how to trigger rehearsals. @andfasano could you force-push the commit or simply open/close the PR?

**Comment by andfasano** [comment]
@vrutkovs seems to be working now!

**Pull request merged**
