### PR TITLE
Added setup for mirroring osa image to Quay registry

### PR DESCRIPTION
**Pull request by rajusem**
PR contains setup related to mirroring ci image to Quay registry based on https://docs.ci.openshift.org/docs/how-tos/mirroring-to-quay/#configuring-mirroring-for-new-organization

### CODE REVIEW

**Comment by rajusem** [comment]
/pj-rehearse pull-ci-openshift-incluster-anomaly-detection-main-lint

**Comment by rajusem** [comment]
/pj-rehearse pull-ci-openshift-incluster-anomaly-detection-main-lint

**Comment by rajusem** [comment]
/pj-rehearse pull-ci-openshift-incluster-anomaly-detection-main-images

**Comment by rajusem** [comment]
/pj-rehearse pull-ci-openshift-incluster-anomaly-detection-main-lint

**Comment by rajusem** [comment]
/pj-rehearse pull-ci-openshift-incluster-anomaly-detection-main-images

**Review by jmguzik — APPROVED** [review]

**Pull request merged**
