### PR TITLE
enable the multi-arch building for the ovn-kubernetes repo

### PR DESCRIPTION
**Pull request by droslean**
Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

### CODE REVIEW

**Comment by droslean** [comment]
@smg247 I am not sure if this is a bug, but I was expecting to rehearse those jobs. Is this expected?

**Comment by smg247** [comment]
> @smg247 I am not sure if this is a bug, but I was expecting to rehearse those jobs. Is this expected?

They are all `postsubmits`, we don't rehearse those.

**Pull request closed without merging**
