### PR TITLE
Remove job/cpaas-cvp-optional-operator-common-tests

### PR DESCRIPTION
**Pull request by hongkailiu**
This is the only one in this file.

/hold
wait for rehearsal

/cc @petr-muller 

---

[cpv-trigger](https://github.com/openshift/ci-tools/tree/master/cmd/cvp-trigger) uses `periodic-ci-redhat-operator-ecosystem-playground-cvp-ocp-4.6-cvp-common-aws`.
This job is no longer needed.

### CODE REVIEW

**Comment by hongkailiu** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/16312/pull-ci-openshift-release-master-pj-rehearse/1365113758132736000#1:build-log.txt%3A12

a rehearse tool bug?

**Comment by petr-muller** [comment]
/hold

I'll need to look into this one, CVP is tricky.

**Comment by hongkailiu** [comment]
@petr-muller One more thing to consider:
This one needs `cm/step-registry`. It stays now only on `app.ci` and `api.ci`.
So the job moves to `app.ci`?

**Comment by petr-muller** [comment]
> This one needs cm/step-registry 

Looks like it does not really need it, just mounts it and does not use it.

**Comment by hongkailiu** [comment]
@petr-muller 

Just finished reading https://github.com/openshift/ci-tools/tree/master/cmd/cvp-trigger

So we need to use `cvp-trigger` to trigger `cpaas-cvp-optional-operator-common-tests` job?
I will ask the details tomorrow.

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
