### PR TITLE
ACM-9040: Upgrade go builder version to 1.21

### PR DESCRIPTION
**Pull request by chenz4027**
https://issues.redhat.com/browse/ACM-9040

### CODE REVIEW

**Review by mikeshng — APPROVED** [review]
/approve

/lgtm

**Comment by mikeshng** [comment]
@chenz4027 could you please double check if `main` files need the changes as well? Thanks.

**Comment by chenz4027** [comment]
@mikeshng You are right, I think main would need them too

**Review by mikeshng — APPROVED** [review]
/approve

/lgtm

**Pull request merged**
