### PR TITLE
Add zonal CI jobs to vSphere CSI driver + operator

### PR DESCRIPTION
**Pull request by jsafrane**
To prevent regressions in topology enabled environments, like [this one](https://issues.redhat.com/browse/OCPBUGS-23970).

cc @openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
/pj-rehearse

Rehearsals should fail because of https://issues.redhat.com/browse/OCPBUGS-23970, I just want to see if it reaches that state.

**Comment by gnufied** [comment]
cc @jcpowermac @rvanderp3

**Comment by jsafrane** [comment]
/pj-rehearse ack
All faled as expected. And actually 6 jobs were running in parallel, it's more than I expected.

**Pull request merged**
