### PR TITLE
machine-config-operator: add gcp-op test for single-node

### PR DESCRIPTION
**Pull request by sinnykumari**

### CODE REVIEW

**Comment by sinnykumari** [comment]
Needs https://github.com/openshift/release/pull/17139
/hold

**Review by kikisdeliveryservice — COMMENTED** [review]
i think we need to explicitly also update the 4.8/4.9.yamls as well

**Comment by sinnykumari** [comment]
yeah, was thinking of doing it in another PR once we know it works for master

**Comment by kikisdeliveryservice** [comment]
hmm something is wrong with the yaml:

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/17357/pull-ci-openshift-release-yamllint/1377293986229653504

**Review by kikisdeliveryservice — APPROVED** [review]
remove hold whenever you are ready.

/lgtm

**Comment by sinnykumari** [comment]
Dependent PR https://github.com/openshift/release/pull/17139 has been merged.
/hold cancel
Rebased PR to fix merge conflict

**Comment by sinnykumari** [comment]
When a new job gets added it usually fails(don't why) but this is the pattern I have observed in already merged PRs in this repo like https://github.com/openshift/release/pull/13435 , https://github.com/openshift/release/pull/9607

**Review by kikisdeliveryservice — APPROVED** [review]
looks good @sinnykumari

**Pull request merged**
