### PR TITLE
fix logging-eventrouter base image

### PR DESCRIPTION
**Pull request by jcantrill**
This PR bumps the golang base image for the logging-eventrouter

cc @eparis

### CODE REVIEW

**Review by alanconway — APPROVED** [review]
/lgtm

**Comment by crawford** [comment]
"Pod got deleted unexpectedly"

/retest

**Comment by jcantrill** [comment]
@crawford are these rehearsals merge blockers?  I know our periodic 4.5 routinely fails and we have not investigated it fully to determine why

**Comment by crawford** [comment]
@jcantrill These rehearsals aren't, but `app-ci-config-dry` is and it's currently failing with the following:

```
route.openshift.io/v1, Kind=Route doesn't support dry-run
```

Do you know what that's about?

**Pull request merged**
