### PR TITLE
Don't build openshift-docs previews for openshift-cherrypick-robot

### PR DESCRIPTION
**Pull request by aireilly**
Building docs is expensive, we don't need to do it for cherrypicks.

### CODE REVIEW

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-gitops-docs-main-deploy-preview

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-gitops-docs-main-deploy-preview

**Comment by aireilly** [comment]
@kalexand-rh this is ready to merge

**Comment by kalexand-rh** [comment]
LGTM

**Comment by kalexand-rh** [comment]
lgtm

**Pull request merged**
