### PR TITLE
adding aws-ipi-sdn test for 4.12

### PR DESCRIPTION
**Pull request by lihongan**
follow https://github.com/openshift/release/pull/31173

@liangxia please help take a look. Thanks

### CODE REVIEW

**Comment by lihongan** [comment]
Retest but this time SDN cluster failed at step `sdn-conf`
```
INFO[2022-08-11T01:10:14Z] Running step e2e-aws-ipi-sdn-p1-sdn-conf.    
INFO[2022-08-11T01:10:54Z] Logs for container test in pod e2e-aws-ipi-sdn-p1-sdn-conf: 
INFO[2022-08-11T01:10:54Z] ## Install yq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1474  100  1474    0     0  58960      0 --:--:-- --:--:-- --:--:-- 58960
   yq installed
/tmp/yq: line 1: syntax error near unexpected token `newline'
/tmp/yq: line 1: `<html>' 
```
looks the yq was not downloaded correctly. Normally the file size is 11.6M 
```
$ curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /tmp/yq && chmod +x /tmp/yq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 11.6M  100 11.6M    0     0  1882k      0  0:00:06  0:00:06 --:--:-- 2418k

```

**Comment by zhaozhanqi** [comment]
@lihongan 
How about update this one to sdn.  since the default already be OVN, this one should be duplicated. 

```
- as: e2e-aws-ipi-ovn-p1
  cron: 0 6 * * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      E2E_RUN_TAGS: '@aws-ipi and @network-ovnkubernetes and not @fips'
      TAG_VERSION: '@4.12'
    test:
    - chain: openshift-e2e-test-qe
    workflow: cucushift-installer-rehearse-aws-ipi-ovn
```

**Comment by zhaozhanqi** [comment]
FYI,  once this PR https://github.com/openshift/verification-tests/pull/2992 is merged

we don't need to care the tag `and @network-ovnkubernetes` or `@network-openshiftsdn`,  we can remove this in `E2E_RUN_TAGS`

**Comment by lihongan** [comment]
> @lihongan How about update this one to sdn. since the default already be OVN, this one should be duplicated.
> 
> ```
> - as: e2e-aws-ipi-ovn-p1
>   cron: 0 6 * * *
>   steps:
>     cluster_profile: aws-qe
>     env:
>       BASE_DOMAIN: qe.devcluster.openshift.com
>       E2E_RUN_TAGS: '@aws-ipi and @network-ovnkubernetes and not @fips'
>       TAG_VERSION: '@4.12'
>     test:
>     - chain: openshift-e2e-test-qe
>     workflow: cucushift-installer-rehearse-aws-ipi-ovn
> ```

Yes, that's also acceptable.
Because the original default one is p3 and only executed each 28 days, do you think that is reasonable for 4.12? If yes, then I can updated as your suggestion.
Or you want to update the priority of the default "e2e-aws-ipi" ?

**Comment by lihongan** [comment]
> FYI, once this PR [openshift/verification-tests#2992](https://github.com/openshift/verification-tests/pull/2992) is merged
> 
> we don't need to care the tag `and @network-ovnkubernetes` or `@network-openshiftsdn`, we can remove this in `E2E_RUN_TAGS`

Great to know that, then please create a new PR to remove all tags after that PR merged. Thanks

**Comment by lihongan** [comment]
@liangxia could you help take a look? Both failed at step `cucushift-e2e-report` but installation and e2e-test were completed.

**Pull request merged**
