### PR TITLE
ROX-17165: update all remaining builder/tester images to include Go 1.20.4

### PR DESCRIPTION
**Pull request by tommartensen**

### CODE REVIEW

**Comment by tommartensen** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-4-10-operator-e2e-tests

**Comment by tommartensen** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-4-10-qa-e2e-tests pull-ci-stackrox-stackrox-master-ocp-4-10-ui-e2e-tests pull-ci-stackrox-stackrox-master-aks-qa-e2e-tests pull-ci-stackrox-stackrox-master-aro-qa-e2e-tests pull-ci-stackrox-stackrox-master-eks-qa-e2e-tests pull-ci-stackrox-stackrox-master-gke-nongroovy-e2e-tests pull-ci-stackrox-stackrox-master-gke-operator-e2e-tests pull-ci-stackrox-stackrox-master-gke-qa-e2e-tests pull-ci-stackrox-stackrox-master-gke-race-condition-qa-e2e-tests pull-ci-stackrox-stackrox-master-gke-scale-tests pull-ci-stackrox-stackrox-master-gke-ui-e2e-tests

**Comment by tommartensen** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-aro-qa-e2e-tests

Couldn't create ARO cluster, not sure why. Retry!

**Comment by tommartensen** [comment]
Ignore `ci/rehearse/stackrox/stackrox/master/gke-operator-e2e-tests` - future prep work, known to fail: https://redhat-internal.slack.com/archives/C0321S70YK1/p1684856503755839

**Comment by gavin-stackrox** [comment]
/lgtm
The rehearsal failures do not look related to the test image change AFAICT.

**Comment by tommartensen** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-gke-race-condition-qa-e2e-tests pull-ci-stackrox-stackrox-master-ocp-4-10-ui-e2e-tests pull-ci-stackrox-stackrox-master-aro-qa-e2e-tests pull-ci-stackrox-stackrox-master-aks-qa-e2e-tests pull-ci-stackrox-stackrox-master-gke-ui-e2e-tests pull-ci-stackrox-stackrox-master-ocp-4-10-qa-e2e-tests pull-ci-stackrox-stackrox-master-ocp-4-10-operator-e2e-tests

**Comment by tommartensen** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-4-10-qa-e2e-tests

**Comment by tommartensen** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-aro-qa-e2e-tests pull-ci-stackrox-stackrox-master-aks-qa-e2e-tests

**Comment by gavin-stackrox** [comment]
/lgtm
The rehearsal failures do not look related to the test image change.
The 5s mutex panic under ARO should be filed in jira.

**Comment by tommartensen** [comment]
Flakes:
ARO: https://issues.redhat.com/browse/ROX-17506
AKS: https://issues.redhat.com/browse/ROX-17412

**Pull request merged**
