### PR TITLE
OCM-9650 | ci: Make rosa pre-submit jobs enforced for tests changes

### PR DESCRIPTION
**Pull request by xueli181114**

### CODE REVIEW

**Review by radtriste — APPROVED** [review]
/lgtm

**Comment by xueli181114** [comment]
/pj-rehearse pull-ci-openshift-rosa-master-e2e-presubmits-pr-rosa-hcp-advanced

**Comment by xueli181114** [comment]
/pj-rehearse pull-ci-openshift-rosa-master-e2e-presubmits-pr-rosa-hcp-advanced

**Comment by xueli181114** [comment]
/pj-rehearse pull-ci-openshift-rosa-master-e2e-presubmits-pr-rosa-hcp-advanced

**Pull request merged**
