### PR TITLE
Add presubmits for common-templates v0.26 and v0.27

### PR DESCRIPTION
**Pull request by 0xFelix**
Add presubmits for common-templates v0.26 and v0.27

### CODE REVIEW

**Comment by akrejcir** [comment]
The lane `e2e-gcp-common-templates-windows2012` was removed from `master`. Should it be included in these new configurations?

**Comment by 0xFelix** [comment]
@akrejcir Updated

**Comment by 0xFelix** [comment]
/pj-rehearse pull-ci-kubevirt-common-templates-release-v0.27-e2e-gcp-common-templates-centos-stream9
/pj-rehearse pull-ci-kubevirt-common-templates-release-v0.26-e2e-gcp-common-templates-windows10

**Comment by 0xFelix** [comment]
/pj-rehearse ci/rehearse/kubevirt/common-templates/release-v0.27/e2e-gcp-common-templates-centos-stream9

**Pull request merged**
