### PR TITLE
Add verify ci job to image-registry repo

### PR DESCRIPTION
**Pull request by coreydaley**

### CODE REVIEW

**Comment by bparees** [comment]
/approve
/lgtm
/hold

you can remove the hold when you get rehearsal passing... if you do it before then you're going to block all your PRs against image-registry.

**Comment by coreydaley** [comment]
Looks like gofmt is failing on the ones that have merged due to using an old golang version of 1.10.
@dmage Can we update to 1.12?

**Comment by coreydaley** [comment]
@bparees can a get an lgtm? I had to push an update to use golang 1.12 instead of 1.10 to get the verify to pass

**Pull request merged**
