### PR TITLE
libvirt: override docker.io registries for test images

### PR DESCRIPTION
**Pull request by r4f4**
Adding the same workaround in #13460 for the remote libvirt CI jobs to
solve the docker.io rate limitting in the meantime.

Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>

### CODE REVIEW

**Comment by Gal-Zaidman** [comment]
I did a little test on my [PR](https://github.com/openshift/release/pull/13818) and triggered a conformance test on 4.6 and 4.7.
[4.6 job](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/13818/rehearse-13818-release-openshift-ocp-installer-e2e-ovirt-4.6/1330902969461248000) finished the installation and started the tests but still hit the rate limit problem on some tests, so I guess that patch is not enough to avoid the problem

**Comment by r4f4** [comment]
On Tue, Nov 24, 2020 at 9:05 AM Gal Zaidman <notifications@github.com> wrote:
>
> I did a little test on my PR and triggered a conformance test on 4.6 and 4.7.
> 4.6 job finished the installation and started the tests but still hit the rate limit problem on some tests, so I guess that patch is not enough to avoid the problem

So it seems the centos:7 image is not going through the registry
override process. All the other images (busybox, httpd, ...) are being
overridden. This is where the overriding occurs:
https://github.com/kubernetes/kubernetes/blob/master/test/utils/image/manifest.go#L273


-- 
Rafael Fonseca

**Comment by crawford** [comment]
cc @sjenning 

/lgtm

**Pull request merged**
