### PR TITLE
oko: Require kuttl job for neutron/octavia/ovn-operator

### PR DESCRIPTION
**Pull request by kajinamit**
... to ensure basic functionality is kept when we merge PRs.

### CODE REVIEW

**Comment by kajinamit** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-ovn-operator-main-ovn-operator-build-deploy-kuttl pull-ci-openstack-k8s-operators-neutron-operator-main-neutron-operator-build-deploy-kuttl pull-ci-openstack-k8s-operators-octavia-operator-main-octavia-operator-build-deploy-kuttl

**Comment by karelyatin** [comment]
It's good idea but considering many intermittent failures(failed even in this patch) in these jobs i am little hesitating to make it require now until these jobs are more stable. But if others think it's good to merge it now this fine by me too.

We(personally i do) do not ignore the failures in these jobs while reviewing but consider merge when they fail due to infra issue or unrelated to patches.

**Comment by kajinamit** [comment]
> It's good idea but considering many intermittent failures(failed even in this patch) in these jobs i am little hesitating to make it require now until these jobs are more stable. But if others think it's good to merge it now this fine by me too.
> 
> We(personally i do) do not ignore the failures in these jobs while reviewing but consider merge when they fail due to infra issue or unrelated to patches.

In case we have to skip some jobs, we can override the result using the `/override` command. This would require additional steps but reasonable as you should check the failing job and understand why it's failing even if you keep the job optional. https://docs.ci.openshift.org/docs/how-tos/overriding-failing-ci-jobs/

**Review by karelyatin — COMMENTED** [review]
/lgtm

**Review by booxter — APPROVED** [review]

**Comment by kajinamit** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-ovn-operator-main-ovn-operator-build-deploy-kuttl

**Review by karelyatin — APPROVED** [review]
/lgtm

**Pull request merged**
