### PR TITLE
Add EXTRA_FLAGS back

### PR DESCRIPTION
**Pull request by rsevilla87**
Adding back line removed by mistake in https://github.com/openshift/release/pull/49976/files

### CODE REVIEW

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-control-plane-120nodes

**Comment by jtaleric** [comment]
Not clear why the failure - https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/51031/rehearse-51031-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-control-plane-120nodes/1780563137146130432/artifacts/control-plane-120nodes/openshift-qe-node-density/build-log.txt

**Comment by rsevilla87** [comment]
> Not clear why the failure - https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/51031/rehearse-51031-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-control-plane-120nodes/1780563137146130432/artifacts/control-plane-120nodes/openshift-qe-node-density/build-log.txt

doesn't seems clear to me either, rerunning

**Pull request merged**
