### PR TITLE
Calculate global timers for rosa install (command) and cluster ready (wait for operators)

### PR DESCRIPTION
**Pull request by morenod**
- Move cluster final status out of .timers.install object to allow sum all values inside it
- Calculate install_ready timer as sum of all .timers.install timers
- Calculate cluster_ready timer as sum of install_ready and co_wait_time

### CODE REVIEW

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.13-nightly-x86-control-plane-3nodes

**Comment by morenod** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-control-plane-3nodes

**Comment by morenod** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-control-plane-24nodes

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-control-plane-24nodes

**Pull request merged**
