### PR TITLE
Rename csi-driver-shared-resource image

### PR DESCRIPTION
**Pull request by adambkaplan**
- Update the mirrored image name to csi-driver-shared-resource.
- Updated the image name in the promotion pipeline.

Note that the current CI hard-codes the image name for testing, and will
therefore break.

### CODE REVIEW

**Comment by adambkaplan** [comment]
/cc @smarterclayton 

This will update the image name we mirror to quay. I believe you will need to make the repo public once images are pushed.

**Comment by adambkaplan** [comment]
@dmage this appears new - ImageStreams don't support server-side apply:

```
{"component":"applyconfig","file":"/go/src/github.com/openshift/ci-tools/cmd/applyconfig/applyconfig.go:280","func":"main.(*configApplier).doWithRetry","level":"error","msg":"Apply command failed (not recoverable)","output":"W0802 14:18:30.812362    3424 shim_kubectl.go:55] Using non-groupfied API resources is deprecated and will be removed in a future release, update apiVersion to \"image.openshift.io/v1\" for your resource\nW0802 14:18:31.069796    3424 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition\nerror: image.openshift.io/v1, Kind=ImageStream doesn't support dry-run\n","severity":"error","time":"2021-08-02T14:18:31Z"}
{"component":"applyconfig","file":"/go/src/github.com/openshift/ci-tools/cmd/applyconfig/applyconfig.go:145","func":"main.commandExecutor.runAndCheck","level":"info","msg":"oc apply -f clusters/app.ci/supplemental-ci-images/openshift-priv/4.2-priv-is.yaml -o name --dry-run=server --validate=true: failed to apply\nW0802 14:18:31.719268    3436 shim_kubectl.go:55] Using non-groupfied API resources is deprecated and will be removed in a future release, update apiVersion to \"image.openshift.io/v1\" for your resource\nW0802 14:18:32.049455    3436 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition\nerror: image.openshift.io/v1, Kind=ImageStream doesn't support dry-run\n","severity":"info","time":"2021-08-02T14:18:32Z"}
```

**Comment by adambkaplan** [comment]
/assign @coreydaley 

As expected, this will temporarily break our CI

**Comment by smarterclayton** [comment]
Is there a paired PR you can link here which includes the rename of the operator dependency on the image name?

**Comment by adambkaplan** [comment]
@smarterclayton here's the pair PR that fixes the image name: https://github.com/openshift/csi-driver-shared-resource/pull/40

**Comment by adambkaplan** [comment]
Note that once we wire everything up and install via the cluster storage operator, we won't need to hardcode the image name for CI testing.

**Pull request merged**
