### PR TITLE
Only capture must gathers in the gather step

### PR DESCRIPTION
**Pull request by Sandeepyadav93**
OSP must gather have the parity of logs with what we were collecting here using shell script, with this commit we are removing the duplicate log collection.

### CODE REVIEW

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-keystone-operator-main-keystone-operator-build-deploy-kuttl

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-keystone-operator-main-keystone-operator-build-deploy-kuttl

**Comment by Sandeepyadav93** [comment]
Must gather are correctly getting reports: 

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/43342/rehearse-43342-pull-ci-openstack-k8s-operators-keystone-operator-main-keystone-operator-build-deploy-kuttl/1702300261520773120/artifacts/keystone-operator-build-deploy-kuttl/openstack-k8s-operators-gather/artifacts/must-gather/

**Review by cescgina — COMMENTED** [review]
lgtm

**Comment by viroel** [comment]
/lgtm

must-gather outputs looks good and seems to have everything else removed from the script[1]

[1] https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/43342/rehearse-43342-pull-ci-openstack-k8s-operators-keystone-operator-main-keystone-operator-build-deploy-kuttl/1702300261520773120/artifacts/keystone-operator-build-deploy-kuttl/openstack-k8s-operators-gather/artifacts/must-gather/

**Comment by viroel** [comment]
/pj-rehearse ack

thanks Sandeep

**Pull request merged**
