### PR TITLE
Add vLLM CI for 2.14

### PR DESCRIPTION
**Pull request by rpancham**
Addresses : https://issues.redhat.com/browse/RHOAIENG-13659

### CODE REVIEW

**Comment by dtrifiro** [comment]
Waiting for #57235 rehearsals to see if updated requirements fix the build issues

**Comment by dtrifiro** [comment]
/pj-rehearse pull-ci-red-hat-data-services-vllm-rhoai-2.14-images

**Review by NickLucche — APPROVED** [review]

**Comment by dtrifiro** [comment]
/pj-rehearse pull-ci-red-hat-data-services-vllm-rhoai-2.14-smoke-test

**Review by tarukumar — APPROVED** [review]

**Comment by dtrifiro** [comment]
<markdown-accessiblity-table data-catalyst="" style="box-sizing: border-box; display: block; color: rgb(240, 246, 252); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
/pj-rehearse pull-ci-red-hat-data-services-vllm-rhoai-2.14-smoke-test
--


</markdown-accessiblity-table><br class="Apple-interchange-newline">

**Pull request merged**
