### PR TITLE
Drop rollback jobs on 4.13 and earlier

### PR DESCRIPTION
**Pull request by shellyyang1989**
Per slack thread https://redhat-internal.slack.com/archives/CJ1J9C3V4/p1697428516778689, we decided to focus on 4.14 and main branch. So dropping the rollback jobs on 4.13 and earlier.

### CODE REVIEW

**Comment by shellyyang1989** [comment]
cc @jiajliu @jianlinliu @JianLi-RH

**Comment by jianlinliu** [comment]
> So dropping the rollback jobs on 4.13 and earlier.

We also need to drop the one in 4.12?
```
$ grep -r "as: e2e-aws-ovn-upgrade-rollback" |grep 4.12
ci-operator/config/openshift/release/openshift-release-master__nightly-4.12.yaml:- as: e2e-aws-ovn-upgrade-rollback-oldest-supported
ci-operator/config/openshift/origin/openshift-origin-master__4.12-upgrade-from-stable-4.11.yaml:- as: e2e-aws-ovn-upgrade-rollbac
```

**Review by wking — APPROVED** [review]
/lgtm

**Review by bradmwilliams — APPROVED** [review]

**Review by wking — APPROVED** [review]
/lgtm

**Comment by wking** [comment]
Nothing to rehearse for this pure-removal:

/pj-rehearse ack

**Pull request merged**
