### PR TITLE
SPLAT-1448: installer/aws/edge-zones: increase pool and timeout for presubmit

### PR DESCRIPTION
**Pull request by mtulio**
- Ref [SPLAT-1448](https://issues.redhat.com/browse/SPLAT-1448)
- Updates https://github.com/openshift/release/pull/47996
- Increase lease pool for AWS Local Zones preventing concurrency issues in required jobs on installer - the jobs using this profile is making AWS API calls, not launching resources, which will not result in cost increasing

### CODE REVIEW

**Comment by mtulio** [comment]
PTAL?
/assign @rvanderp3 @r4f4

**Comment by mtulio** [comment]
Trevor, PTAL for boskos change?
/assign @wking

**Review by r4f4 — COMMENTED** [review]
/approve

**Comment by mtulio** [comment]
I needed to rebase, will ask review to stamp LGTM again.

**Review by wking — APPROVED** [review]
Bumping the quota a bit because we are not yet seeing AWS-API-throttling issues makes sense to me :+1:

/lgtm

**Pull request merged**
