### PR TITLE
NVIDIA GPU operator: replace 4.11 with 4.16

### PR DESCRIPTION
**Pull request by empovit**
* OCP 4.11 has reached EOL
* Nightly builds of 4.16 have become available

### CODE REVIEW

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.16-nvidia-gpu-operator-e2e-master

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.16-nvidia-gpu-operator-e2e-master

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.16-nvidia-gpu-operator-e2e-master

**Review by fabiendupont — APPROVED** [review]
/lgtm

**Pull request merged**
