### PR TITLE
build 02: add ctrcfg to use crun

### PR DESCRIPTION
**Pull request by haircommander**
starting with the workers

Signed-off-by: Peter Hunt~ <pehunt@redhat.com>

### CODE REVIEW

**Comment by wking** [comment]
Bringing back some of #32448, which we'd reverted in #32552, although I don't remember why.

**Comment by haircommander** [comment]
> Bringing back some of #32448, which we'd reverted in #32552, although I don't remember why.

https://docs.google.com/document/d/1cmyS-m9bnjBRNcu-01qDMVxXxeryU4YUWofc3K8HDr0/edit?usp=sharing

**Comment by haircommander** [comment]
difference is now we have https://github.com/cri-o/cri-o/pull/6264 which should prevent the issues on the workers, and we also fixed the issues we saw on the control plane

**Comment by hongkailiu** [comment]
LGTM

/hold

Need to watch the rolling.

**Pull request merged**
