### PR TITLE
Netobserv inputs update

### PR DESCRIPTION
**Pull request by memodi**
Followup to #48810 
* Netobserv inputs update for ebpf and plugin.
* use cluster pool to reduce time for e2e-operator
* use ubi9 image for all components and operator

### CODE REVIEW

**Comment by memodi** [comment]
/pj-rehearse pull-ci-netobserv-network-observability-operator-main-e2e-operator

**Comment by memodi** [comment]
/pj-rehearse pull-ci-netobserv-network-observability-operator-main-e2e-operator

**Comment by memodi** [comment]
/pj-rehearse pull-ci-netobserv-network-observability-operator-main-e2e-operator

**Comment by memodi** [comment]
/pj-rehearse pull-ci-netobserv-network-observability-operator-main-e2e-operator

**Comment by memodi** [comment]
/pj-rehearse pull-ci-netobserv-network-observability-operator-main-e2e-operator

**Comment by memodi** [comment]
/pj-rehearse pull-ci-netobserv-network-observability-operator-main-e2e-operator

**Comment by memodi** [comment]
/pj-rehearse pull-ci-netobserv-network-observability-operator-main-e2e-operator

**Review by jpinsonneau — APPROVED** [review]

**Comment by memodi** [comment]
/pj-rehearse pull-ci-netobserv-network-observability-operator-main-e2e-operator

**Comment by memodi** [comment]
/pj-rehearse pull-ci-netobserv-network-observability-operator-main-e2e-operator

**Comment by memodi** [comment]
/pj-rehearse pull-ci-netobserv-network-observability-operator-main-e2e-operator

**Comment by memodi** [comment]
/pj-rehearse pull-ci-netobserv-network-observability-operator-main-e2e-operator

**Comment by memodi** [comment]
/pj-rehearse pull-ci-netobserv-network-observability-operator-main-e2e-operator

**Comment by memodi** [comment]
/pj-rehearse pull-ci-netobserv-network-observability-operator-main-images

**Comment by memodi** [comment]
/pj-rehearse  pull-ci-netobserv-network-observability-operator-main-ci-index-noo-bundle

**Comment by memodi** [comment]
/pj-rehearse pull-ci-netobserv-netobserv-ebpf-agent-main-images

**Comment by memodi** [comment]
/pj-rehearse pull-ci-netobserv-network-observability-operator-main-e2e-operator

**Review by jpinsonneau — APPROVED** [review]
/lgtm

**Pull request merged**
