### PR TITLE
[WIP] pod service route test

### PR DESCRIPTION
**Pull request by skordas**
https://issues.redhat.com/browse/OCPQE-15810

### CODE REVIEW

**Comment by skordas** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-gcp-4.13-ocp-qe-perfscale-pod-service-route-gcp periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-ocp-qe-perfscale-pod-service-route-aws

**Comment by skordas** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-ocp-qe-perfscale-pod-service-route-aws periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-gcp-4.13-ocp-qe-perfscale-pod-service-route-gcp

**Comment by skordas** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-ocp-qe-perfscale-pod-service-route-aws periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-gcp-4.13-ocp-qe-perfscale-pod-service-route-gcp

**Comment by skordas** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-ocp-qe-perfscale-pod-service-route-aws periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-gcp-4.13-ocp-qe-perfscale-pod-service-route-gcp

**Comment by skordas** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-gcp-4.13-ocp-qe-perfscale-pod-service-route-gcp periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-ocp-qe-perfscale-pod-service-route-aws

**Comment by paigerube14** [comment]
Looks like this isn't a viable option for kube-burner-ocp 


```
+ tee /tmp/secret/kube-burner-ocp.out
/tmp/kube-burner ocp pods-service-route --log-level=info --qps=20 --burst=20 --gc=true --uuid 6c99b80c-de54-4e7f-937a-342cb1734582 --es-server=https://XXXXXX:XXXXXXXXXXXX@search-XXXXXX-perf-scale-test-elk-hcm7wtsqpxy7xogbu72bor4uve.us-east-1.es.amazonaws.com --es-index=ripsaw-kube-burner
This subcommand is meant to be used against OpenShift clusters and serve as a shortcut to trigger well-known workloads

Usage:
  kube-burner ocp [command]

Available Commands:
  cluster-density    Runs cluster-density workload
  cluster-density-ms Runs cluster-density-ms workload
  cluster-density-v2 Runs cluster-density-v2 workload
  node-density       Runs node-density workload
  node-density-cni   Runs node-density-cni workload
  node-density-heavy Runs node-density-heavy workload

Flags:
      --alerting                  Enable alerting (default true)
      --burst int                 Burst (default 20)
      --es-index string           Elastic Search index
      --es-server string          Elastic Search endpoint
      --extract                   Extract workload in the current directory
      --gc                        Garbage collect created namespaces (default true)
  -h, --help                      help for ocp
      --local-indexing            Enable local indexing
      --metrics-endpoint string   YAML file with a list of metric endpoints
      --qps int                   QPS (default 20)
      --reporting                 Enable benchmark report indexing
      --timeout duration          Benchmark timeout (default 4h0m0s)
      --user-metadata string      User provided metadata file, in YAML format
      --uuid string               Benchmark UUID (default "77cf3afa-892f-4f8f-afa9-942d24019ade")

Global Flags:
      --log-level string   Allowed values: debug, info, warn, error, fatal (default "info")
```

**Pull request closed without merging**
