### PR TITLE
Run CI for 1.1.2 serving, net-istio and net-kourier release

### PR DESCRIPTION
**Pull request by nak3**

### CODE REVIEW

**Comment by nak3** [comment]
/retest

infra issue.

**Comment by skonto** [comment]
@nak3 are you planning to add the images in `core-services/image-mirroring/knative/mapping_knative_v1_1_quay` in a separate PR?

**Comment by nak3** [comment]
> b) Are we going to support 4.10 for 1.21? In the release matrix 4.10 is listed as well.

Yes, we need it. The status of 4.10 CI is messed up :sweat_smile: (e.g. https://github.com/openshift/release/pull/24365) So I will add it in the separated PR.

Added mirror image for a).

**Comment by mgencur** [comment]
/lgtm
/hold

Holding until the checks pass.

**Comment by nak3** [comment]
/hold cancel

All test passed.

**Review by rhuss — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
