### PR TITLE
Don't run unit tests for prom-label-proxy

### PR DESCRIPTION
**Pull request by simonpasquier**
Unit tests are already executed upstream. Also the OpenShift Go 1.13
image automatically sets GOFLAGS='-mod=vendor' which conflicts with the
way 'make test' runs the Go tests.

cc @openshift/openshift-team-monitoring

### CODE REVIEW

**Comment by s-urbaniak** [comment]
Hmm, do we really want to disable unit tests? my intuition tells me that it is still valuable to execute them downstream as we may carry patches and other modifications, or even potentially add specific downstream unit tests.

**Comment by s-urbaniak** [comment]
Oh i see we do the same already for other artifacts as outlined in https://github.com/openshift/prom-label-proxy/pull/154#issuecomment-647567127.

**Comment by s-urbaniak** [comment]
Let's discuss nevertheless out of band (architecture call?) our strategy for executing unit tests downstream.

**Comment by simonpasquier** [comment]
Agreed that we need a discussion and personally I'd be in favor of running unit tests...

**Pull request merged**
