### PR TITLE
revert api.url workaround

### PR DESCRIPTION
**Pull request by yasun1**
[OCPQE-17764](https://issues.redhat.com//browse/OCPQE-17764)

### CODE REVIEW

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-master-rosacli-rosa-aws-sts-rosacli-e2e-f3 periodic-ci-rhpit-interop-tests-main-openshift-pipelines-hypershift-4.13-lp-rosa-hypershift-openshift-pipelines-rosa-hypershift

**Comment by yasun1** [comment]
We have tried many times in https://github.com/openshift/release/pull/42122 in days, and could not reproduce the issue `api.url is null`. We'd like to comment out the workaround in [42067](https://github.com/openshift/release/pull/42067) so that we can catch the potential bugs in the future. 

cc @jtaleric @xueli181114

**Comment by jtaleric** [comment]
Is there a trigger we can set to catch if the api url isn't set? The issue is holding up PRs for flaky steps. 

I understand the want to identify the bug, but i am curious if we could track the failure and still keep the workaround?

**Comment by yasun1** [comment]
Adding the temporary notification and sleep 24 hours if the api.url=null. @jtaleric @xueli181114

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-aws-load-balancer-operator-main-e2e-aws-rosa-operator

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-aws-load-balancer-operator-main-e2e-aws-rosa-operator

**Comment by jtaleric** [comment]
Trying to understand this more, are you just leaving the 24hr sleep in for a WIP pr -- or are you planning to merge it with this?

**Comment by jtaleric** [comment]
FYI we are seeing the missing api url again. https://search.ci.openshift.org/?search=warning%3A+API+URL+was+null&maxAge=336h&context=0&type=build-log&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-aws-load-balancer-operator-main-e2e-aws-rosa-operator

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-aws-load-balancer-operator-main-e2e-aws-rosa-operator

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-aws-load-balancer-operator-main-e2e-aws-rosa-operator

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-aws-load-balancer-operator-main-e2e-aws-rosa-operator

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-master-rosacli-rosa-aws-sts-rosacli-e2e-f3

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-master-rosacli-rosa-aws-sts-rosacli-e2e-f3

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-master-rosacli-rosa-aws-sts-rosacli-e2e-f3

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-rosa-sts-f14

**Pull request merged**
