### PR TITLE
cluster-logging: Update golang builder to go1.22 in 5.9

### PR DESCRIPTION
**Pull request by periklis**
/cc @xperimental @JoaoBraveCoding @jcantrill

### CODE REVIEW

**Comment by periklis** [comment]
Expected to fail because of circular dependency to:
- openshift/cluster-logging-operator/pull/2842

the following tests:
- pull-ci-openshift-cluster-logging-operator-release-5.9-lint
- pull-ci-openshift-cluster-logging-operator-release-5.9-unit

**Review by JoaoBraveCoding — APPROVED** [review]
/lgtm

**Pull request merged**
