### PR TITLE
Add azure-upi-etcd-encryption-workflow

### PR DESCRIPTION
**Pull request by wangke19**
Add azure-upi-etcd-encryption-workflow for Jira issue [OCPQE-12216](https://issues.redhat.com//browse/OCPQE-12216)

### CODE REVIEW

**Comment by jianlinliu** [comment]
@wangke19 I saw ipi azure + etcd-encryption is just merged, now this PR is for upi azure + etcd-encryption, I wonder is there any difference between UPI and IPI for etcd-encryption? Per my understanding, it sounds not unnecessary.

**Comment by wangke19** [comment]
> @wangke19 I saw ipi azure + etcd-encryption is just merged, now this PR is for upi azure + etcd-encryption, I wonder is there any difference between UPI and IPI for etcd-encryption? Per my understanding, it sounds not unnecessary.

Actually, no difference, just implement the part of Jenkins profile `94_UPI on AZURE & ccm & OVN IPSEC & FIPS On & Etcd Encryption on`, have a full test workflow for Prow CI.

**Comment by jianlinliu** [comment]
> > @wangke19 I saw ipi azure + etcd-encryption is just merged, now this PR is for upi azure + etcd-encryption, I wonder is there any difference between UPI and IPI for etcd-encryption? Per my understanding, it sounds not unnecessary.
> 
> Actually, no difference, just implement the part of Jenkins profile `94_UPI on AZURE & ccm & OVN IPSEC & FIPS On & Etcd Encryption on`, have a full test workflow for Prow CI.

The prow ci migration actually is not 100% matched with the original jenkins profiles, during the migration, we can refine the original jenkins profiles. After feature owner estimate, if the feature testing itself make no difference on upi and ipi, I recommend  only covering one of UPI and IPI should be enough.

**Comment by wangke19** [comment]
Okay, for the same function, we prefer to IPI implementation.

**Pull request closed without merging**
