### PR TITLE
chore: rhtap - use custom cluster profile

### PR DESCRIPTION
**Pull request by psturc**
https://issues.redhat.com/browse/RHTAP-1749

follow-up on 
* https://github.com/openshift/release/pull/44202
* https://github.com/openshift/ci-tools/pull/3677/files

### CODE REVIEW

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-service-provider-integration-operator-main-spi-service-e2e

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-service-provider-integration-operator-main-spi-service-e2e

**Comment by psturc** [comment]
```
• [FAILED] [301.856 seconds]
[spi-suite] SVPI-395 - Github OAuth flow to upload token [It] SPITokenBinding should be in Injected phase [spi-suite, gh-oauth-flow]
/tmp/tmp.qpc7nyOKrx/tests/spi/oauth.go:183
  [FAILED] Timed out after 300.001s.
  SPIAccessTokenBinding is not in Injected phase
  Expected
      <bool>: false
  to be true
  In [It] at: /tmp/tmp.qpc7nyOKrx/tests/spi/oauth.go:189 @ 10/16/23 10:20:10.548
```
/pj-rehearse pull-ci-redhat-appstudio-service-provider-integration-operator-main-spi-service-e2e

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-application-service-main-application-service-e2e pull-ci-redhat-appstudio-infra-deployments-main-appstudio-hac-e2e-tests pull-ci-redhat-appstudio-remote-secret-main-remote-secret-service-e2e

**Comment by psturc** [comment]
/pj-rehearse ci/rehearse/redhat-appstudio/infra-deployments/main/appstudio-hac-e2e-tests

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-hac-e2e-tests

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-service-provider-integration-operator-main-spi-service-e2e

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-hac-e2e-tests

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests

**Comment by albarbaro** [comment]
Looks good to me.

**Review by rsoaresd — APPROVED** [review]

**Review by johnmcollier — APPROVED** [review]

**Pull request merged**
