### PR TITLE
OCPBUGS-46016: rename 'master' to 'main' for installer

### PR DESCRIPTION
**Pull request by DennisPeriquet**
This PR is in support of renaming the default branch for https://github.com/openshift/installer from 'master' to 'main'.

Unhold this PR only when:

* the default branch for https://github.com/openshift/installer has been renamed to 'main'
* You have verified that the CI jobs are working as expected either by running '/pj-rehearse' or by inspection.

/hold

### CODE REVIEW

**Comment by patrickdillon** [comment]
@DennisPeriquet it looks like there may be conflicts on this pr that need to be resolved

**Comment by patrickdillon** [comment]
/pj-rehearse pull-ci-openshift-installer-main-altinfra-e2e-aws-ovn

**Comment by patrickdillon** [comment]
/pj-rehearse pull-ci-openshift-installer-main-e2e-powervs-capi-ovn

**Comment by DennisPeriquet** [comment]
@patrickdillon i see you've LGTM'ed. Once we rename the default branch to 'main', I I will run a pj-rehearse on pull-ci-openshift-installer-main-images and this one will exercise the new default branch name.

If that goes well, I'll do the unhold.

Please assign this PR when ready to do this.

**Comment by DennisPeriquet** [comment]
Those 3 rehearse jobs are failing as expected with `fatal: couldn't find remote ref main`.
I think it's time for me to take over.

I will work on getting with JustinP to get the branch renamed.

/assign @DennisPeriquet

**Comment by DennisPeriquet** [comment]
The [rehearse job](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/59742/rehearse-59742-pull-ci-openshift-installer-main-images/1869098713956225024) failure didn't appear to be related to a default branch rename:

```
: Build image upi-installer from the repository expand_less | 2h4m17s
-- | --
{  error occurred handling build upi-installer-amd64: could not get build upi-installer-amd64: client rate limiter Wait returned an error: context canceled}
```

/pj-rehearse ack
/hold cancel

**Pull request merged**
