### PR TITLE
openstack-k8s: drop support for storage bundle

### PR DESCRIPTION
**Pull request by dprince**
We are no longer using this storage bundle

### CODE REVIEW

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-keystone-operator-main-keystone-operator-build-deploy-kuttl

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy

**Pull request merged**
