### PR TITLE
[azure] remove marketplace image upgrade CI jobs and suspend fresh install CI jobs

### PR DESCRIPTION
**Pull request by jinyunma**
As title, 
1.  Remove marketplace image upgrade CI jobs
2.  Suspend fresh install CI jobs temporarily until overdue bill issue get fixed under relevant azure subscriptions.

### CODE REVIEW

**Comment by jinyunma** [comment]
cc: @jianlinliu @gpei @MayXuQQ to review

**Comment by jianlinliu** [comment]
cc @liangxia to review.

**Pull request merged**
