### PR TITLE
Add ci config and job to run e2e-aws on crio-1.19

### PR DESCRIPTION
**Pull request by umohnani8**
Add the config and job needed to run the e2e-aws ci on
all PRs in the cri-o release-1.19 branch.

Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

### CODE REVIEW

**Comment by jcpowermac** [comment]
Getting failures related to this pull request.

```
time="2020-06-09T16:10:57Z" level=fatal msg="Failed to get config agent: Failed to load configs: loading config failed: failed to load ci-operator config (invalid configuration in file ci-operator/config/cri-o/cri-o/cri-o-cri-o-release-1.19.yaml: error unmarshaling JSON: while decoding JSON: json: unknown field \"cluster\"\nvalue:\nbase_images:\n  base:\n    cluster: https://api.ci.openshift.org\n    name: \"4.6\"\n    namespace: ocp\n    tag: base\n  base-machine:\n    cluster: https://api.ci.openshift.org\n    name: fedora\n    namespace: openshift\n    tag: \"29\"\n  machine-os-content-base:\n    cluster: https://api.ci.openshift.org\n    name: \"4.6\"\n    namespace: ocp\n    tag: machine-os-content\nbuild_root:\n  image_stream_tag:\n    cluster: https://api.ci.openshift.org\n    name: release\n    namespace: openshift\n    tag: golang-1.13\nimages:\n- context_dir: images/os/\n  from: base\n  inputs:\n    base-machine-with-rpms:\n      as:\n      - fedora:29\n      paths: null\n    machine-os-content-base:\n      as:\n      - registry.svc.ci.openshift.org/rhcos/machine-os-content:4.6\n      paths: null\n  to: machine-os-content\nraw_steps:\n- rpm_image_injection_step:\n    from: base-machine\n    to: base-machine-with-rpms\nresources:\n  '*':\n    requests:\n      cpu: 100m\n      memory: 4Gi\nrpm_build_commands: hack/build-rpms.sh\ntag_specification:\n  cluster: https://api.ci.openshift.org\n  name: \"4.6\"\n  namespace: ocp\ntests:\n- as: e2e-aws\n  steps:\n    cluster_profile: aws\n    workflow: openshift-e2e-aws\n- as: launch-aws\n  commands: sleep 7200 & wait\n  openshift_installer:\n    cluster_profile: aws\nzz_generated_metadata:\n  branch: release-1.19\n  org: cri-o\n  repo: cri-o\n)"
```

See:
https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/9204/pull-ci-openshift-release-master-ci-operator-registry/11834

**Comment by jcpowermac** [comment]
Should be resolved with
https://github.com/openshift/release/pull/9572

**Comment by umohnani8** [comment]
Thanks!

**Pull request merged**
