### PR TITLE
Fix/Debug baremetalds-ipi-ovn-ipv4-f28-destructive profile

### PR DESCRIPTION
**Pull request by jadhaj**
baremetalds-ipi-ovn-ipv4-f28-destructive profile complains about missing gcc:

https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-baremetalds-ipi-ovn-ipv4-f28-destructive/1710882667085434880

excerpt from log:

 Compile failed: command 'gcc' failed: No such file or directory
    creating tmp
    cc -I/usr/include/libxml2 -I/usr/include/libxml2 -c /tmp/xmlXPathInit50yxi7b_.c -o tmp/xmlXPathInit50yxi7b_.o
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    *********************************************************************************
    error: command 'gcc' failed: No such file or directory

cc @derekhiggins

### CODE REVIEW

**Comment by jadhaj** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-baremetalds-ipi-ovn-ipv4-f28-destructive

**Comment by jadhaj** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-baremetalds-ipi-ovn-ipv4-f28-destructive

**Comment by jadhaj** [comment]
cc @liangxia

**Comment by jadhaj** [comment]
Is there anything needed to proceed with PR ?

**Comment by jadhaj** [comment]
@derekhiggins Please review

**Comment by derekhiggins** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-ovn-ipv4

**Comment by jadhaj** [comment]
@derekhiggins I added context on description above

**Comment by derekhiggins** [comment]
> @derekhiggins I added context on description above

thanks, lgtm

**Pull request merged**
