### PR TITLE
Add CI testing on a ppc64le OpenStack cluster at OSU's Open Source Lab.

### PR DESCRIPTION
**Pull request by hamzy**
This is a cluster of ppc64le machines.

The major difference is that the floating ips are predefined.

### CODE REVIEW

**Comment by EmilienM** [comment]
I'm a little bit sad to see that we are not re-using the OpenStack steps. With a bit of tuning, I'm sure we could do it, and it'll reduce maintenance cost and code duplication.

**Comment by EmilienM** [comment]
@hamzy what is the plan with this PR, is there any way our team could help you?

**Comment by hamzy** [comment]
Hello @EmilienM!

I still want to work on it, but I have been asked to help the Power 10 cloud team get support support in the openshift installer.

Is it possible to postpone work on this for a little while?

**Comment by EmilienM** [comment]
> Hello @EmilienM!
> 
> I still want to work on it, but I have been asked to help the Power 10 cloud team get support support in the openshift installer.
> 
> Is it possible to postpone work on this for a little while?

Of course, just let us know when you need our help.

**Pull request closed without merging**
