### PR TITLE
Port 4.6 GCP upgrades to multistep

### PR DESCRIPTION
**Pull request by vrutkovs**
This would use multistep workflow which preserves metrics and logs in 4.5 stable -> 4.6 ci job

### CODE REVIEW

**Comment by vrutkovs** [comment]
/retest

Failed to install 4.5 build

**Comment by vrutkovs** [comment]
Install fails with `Error: unknown flag: --etcd-ca-key` in bootkube

**Comment by vrutkovs** [comment]
https://github.com/openshift/ci-tools/pull/1230 should enable `stable-initial:installer`

**Comment by vrutkovs** [comment]
```
2020/09/16 14:54:46 ci-operator version v20200916-2f1db3d
error: failed to load configuration: response from configresolver == 502 (Bad Gateway) 
```
/retest

**Comment by vrutkovs** [comment]
/retest

Test timed out

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
