### PR TITLE
Add 4.13 heterogeneous on amd64 cluster upgrade to 4.13

### PR DESCRIPTION
**Pull request by shellyyang1989**
Refers [MIXEDARCH-135](https://issues.redhat.com/browse/MIXEDARCH-135) [MIXEDARCH-168](https://issues.redhat.com/browse/MIXEDARCH-168)

### CODE REVIEW

**Comment by shellyyang1989** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-multi-nightly-4.13-upgrade-from-ec-4.13-azure-ipi-baselinecaps-v413-amd64-p2-f14

**Comment by shellyyang1989** [comment]
@aleskandro @liangxia @jianlinliu for review. Thanks!

**Comment by shellyyang1989** [comment]
Upgrade and scaleup passed.

```
INFO[2023-02-28T12:36:35Z] Running step azure-ipi-baselinecaps-v413-amd64-p2-f14-cucushift-upgrade-toimage. 
INFO[2023-02-28T14:01:25Z] Step azure-ipi-baselinecaps-v413-amd[64](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/36794/rehearse-36794-periodic-ci-openshift-openshift-tests-private-release-4.13-multi-nightly-4.13-upgrade-from-ec-4.13-azure-ipi-baselinecaps-v413-amd64-p2-f14/1630510703825653760#1:build-log.txt%3A64)-p2-f14-cucushift-upgrade-toimage succeeded after 1h24m50s. 
INFO[2023-02-28T14:01:25Z] Running step azure-ipi-baselinecaps-v413-amd64-p2-f14-ipi-install-heterogeneous. 
INFO[2023-02-28T14:27:55Z] Step azure-ipi-baselinecaps-v413-amd64-p2-f14-ipi-install-heterogeneous succeeded after 26m30s.
```

**Review by aleskandro — APPROVED** [review]

**Pull request merged**
