### PR TITLE
stackrox: PR & OCP 4.12 CI for 3.73 release branch

### PR DESCRIPTION
**Pull request by gavin-stackrox**
This add CI jobs for PR on the release-3.73 branch that are similar to what was running on merges to that branch. All but the openshift jobs are `always_run: true` similar to what we are used to with CI on the main branch.

This also completes coverage for OCP merge CI with 4.8, 4.11, 4.12 runs of operator and qa e2e tests.

/cc @msugakov 
/hold

### CODE REVIEW

**Comment by robbycochran** [comment]
@gavin-stackrox What do we expect to fail here before you can merge? 

Since we expect to fail due to PSP compat issue, `openshift-newest-operator-e2e-tests` and `openshift-newest-qa-e2e-tests` failures look ok.

The penultimate OCP tests seem to be stuck waiting for cluster.

Can we ignore UI and static check failures?

**Comment by gavin-stackrox** [comment]
@robbycochran I think this can merge as is. The grouped-static-checks failure was mentioned by Mladden elsewhere.
/pj-rehearse ack 
/unhold

**Review by robbycochran — APPROVED** [review]

**Pull request merged**
