### PR TITLE
Bump OCP and go for OSC

### PR DESCRIPTION
**Pull request by gkurz**
OSC 1.8.1 is bumping its OCP and go versions. Prepare CI for that.

### CODE REVIEW

**Review by beraldoleal — APPROVED** [review]
LGTM, thanks.

**Comment by gkurz** [comment]
/pj-rehearse pull-ci-openshift-sandboxed-containers-operator-devel-ci-index-openshift-sandboxed-containers-operator-bundle

**Comment by gkurz** [comment]
/pj-rehearse pull-ci-openshift-sandboxed-containers-operator-devel-sandboxed-containers-operator-e2e

**Review by littlejawa — APPROVED** [review]
LGTM
Thanks !

**Comment by gkurz** [comment]
The CI failure is :

```
ClusterServiceVersion sandboxed-containers-operator.v1.8.0 status message: install failed: deployment operator-metrics-server not ready before timeout: deployment "operator-metrics-server" exceeded its progress deadline
```

This is expected since the monitor image of OSC 1.8.0 doesn't have the metrics-server container definition (to be fixed by https://gitlab.cee.redhat.com/cpaas-midstream/osc-operator/-/merge_requests/630).

It is safe to proceed.

/pj-rehearse ack

**Pull request merged**
