### PR TITLE
Add golang 1.21 image

### PR DESCRIPTION
**Pull request by hongkailiu**
To unblock https://github.com/openshift/ci-tools/pull/3600#issuecomment-1711210316

/cc @openshift/test-platform

### CODE REVIEW

**Review by droslean — APPROVED** [review]

**Comment by hongkailiu** [comment]
Seems working.
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-build-origin-release-image-origin-release-golang-1.21/1708648120201515008

```console
$ oc get istag -n openshift release:golang-1.21
NAME                  IMAGE REFERENCE                                                                                                                              UPDATED
release:golang-1.21   image-registry.openshift-image-registry.svc:5000/openshift/release@sha256:62898d6f93588e517e07749e323063b7432d550fb2e311f57c4a64d6d3012108   3 days ago
```

**Pull request merged**
