### PR TITLE
CI implementation: Enable Agent Disconnected 2.4 e2e CI jobs

### PR DESCRIPTION
**Pull request by LiangquanLi930**
https://issues.redhat.com/browse/OCPQE-22190

### CODE REVIEW

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetalds-hypershift-agent-mce-disconnected-guest-f14

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetalds-hypershift-agent-mce-disconnected-mgmt-f14

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetalds-hypershift-agent-mce-disconnected-guest-f14

**Comment by LiangquanLi930** [comment]
@kuiwang02 Could you help to review the ginkgo part for this PR? this cluster is disconnected and dualstack

**Comment by kuiwang02** [comment]
@LiangquanLi930 it is not me to approve regression prow job. please contact with qe-productivity. cc @liangxia 

I am ok for golang part of this PR.

**Comment by LiangquanLi930** [comment]
@liangxia Could you help to review this PR? Thanks

**Pull request merged**
