### PR TITLE
add periodic-ci-RedHatQE-interop-testing-cnv-4.17-cnv-odf

### PR DESCRIPTION
**Pull request by amp-rh**
See [INTEROP-7451](https://issues.redhat.com/browse/INTEROP-7451)

### CODE REVIEW

**Comment by amp-rh** [comment]
/pj-rehearse pull-ci-RedHatQE-interop-testing-cnv-4.17-cnv-odf-ocp4.17-lp-interop-images

**Comment by amp-rh** [comment]
/pj-rehearse pull-ci-RedHatQE-interop-testing-cnv-4.17-cnv-odf-ocp4.17-lp-interop-images

**Comment by amp-rh** [comment]
/pj-rehearse pull-ci-RedHatQE-interop-testing-cnv-4.17-ocp-cnv-odf-4.17-images

**Comment by amp-rh** [comment]
/pj-rehearse pull-ci-RedHatQE-interop-testing-cnv-4.17-ocp-cnv-odf-4.17-images pull-ci-RedHatQE-interop-testing-cnv-4.17-cnv-odf-ocp4.17-lp-interop-images

**Review by calebevans — APPROVED** [review]
/lgtm

**Comment by rabin-io** [comment]
/pj-rehearse pull-ci-RedHatQE-interop-testing-cnv-4.17-cnv-odf-ocp4.17-lp-interop-images

**Comment by amp-rh** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.17-cnv-odf-ocp4.17-lp-interop-cnv-odf-tests-aws-upi-ocp417

**Comment by amp-rh** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.17-ocp-cnv-odf-4.17-cnv-odf-tests-aws-upi-ocp417

**Comment by amp-rh** [comment]
/pj-rehearse pull-ci-RedHatQE-interop-testing-cnv-4.17-cnv-odf-ocp4.17-lp-interop-images

**Comment by amp-rh** [comment]
/pj-rehearse pull-ci-RedHatQE-interop-testing-cnv-4.17-cnv-odf-ocp4.17-lp-interop-images

**Comment by amp-rh** [comment]
/pj-rehearse pull-ci-RedHatQE-interop-testing-cnv-4.17-cnv-odf-ocp4.17-lp-interop-images

**Comment by amp-rh** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.17-cnv-odf-ocp4.17-lp-interop-cnv-odf-tests-aws-upi-ocp417 periodic-ci-RedHatQE-interop-testing-cnv-4.17-ocp-cnv-odf-4.17-cnv-odf-tests-aws-upi-ocp417

**Comment by amp-rh** [comment]
Needs approval from one of @dbasunag @lukas-bednar @rabin-io
Thanks!

**Comment by danalanerh** [comment]
@lukas-bednar @rabin-io @dbasunag We're currently blocked from being able to run this scenario until we get approval for the MR. Can someone please update this?

**Pull request closed without merging**
