### PR TITLE
Add e2e tests for azure-ipi-proxy 4.11

### PR DESCRIPTION
**Pull request by liangxia**

### CODE REVIEW

**Comment by dis016** [comment]
LGTM

**Comment by liangxia** [comment]
/test all
to pick changes in https://github.com/openshift/release/pull/27625

**Comment by liangxia** [comment]
The PR is ready at job level., with 17/247 tests failed. Checked the failed scenarios one by one, they are scenario failures which need inspect from feature team.
I think we can let the job go and execute, then we will create jira issue for those consistently failing ones.

**Pull request merged**
