### PR TITLE
[rhoso] disable nmstate + nncp

### PR DESCRIPTION
**Pull request by stuggi**

### CODE REVIEW

**Comment by stuggi** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl

**Comment by stuggi** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-keystone-operator-main-keystone-operator-build-deploy-kuttl

**Comment by lewisdenny** [comment]
Hi @stuggi , What is the context for this change mate?

**Comment by stuggi** [comment]
error: build error: Failed to push image: trying to reuse blob sha256:8afba38a614e150d5cec9d32c41bedfe2fe3cc1a11fbd33c712e10abb9e65de9 at destination: pinging container registry quay.rdoproject.org: Get "https://quay.rdoproject.org/v2/": dial tcp 38.129.56.158:443: i/o timeout

**Comment by stuggi** [comment]
> Hi @stuggi , What is the context for this change mate?

https://github.com/openstack-k8s-operators/install_yamls/pull/969 changed the way when to apply NNCPs.

**Comment by stuggi** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-keystone-operator-main-keystone-operator-build-deploy-kuttl

**Review by olliewalsh — APPROVED** [review]
/lgtm

**Comment by lewisdenny** [comment]
> > Hi @stuggi , What is the context for this change mate?
> 
> [openstack-k8s-operators/install_yamls#969](https://github.com/openstack-k8s-operators/install_yamls/pull/969) changed the way when to apply NNCPs. With this the kuttl test ran again successful on the openstack-operator.

Thank you @stuggi , can you please add that context to the commit message? After that, as I see you have verified the fix by running the two Kuttl jobs, I can merge the patch.

**Comment by stuggi** [comment]
> [openstack-k8s-operators/install_yamls#969](https://github.com/openstack-k8s-operators/install_yamls/pull/969) changed the way when to apply NNCPs. With this the kuttl test ran again successful on the openstack-operator.

done

**Comment by stuggi** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl

**Review by lewisdenny — APPROVED** [review]
/lgtm
/approved

Adding back existing lgtm

**Pull request merged**
