### PR TITLE
MSI: Add RHOAM sanity to co-exist tests

### PR DESCRIPTION
**Pull request by rnetser**

### CODE REVIEW

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-rhoam-v4.13-stage-co-exist-rosa-rhods-rhoam

**Review by oharan2 — APPROVED** [review]

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-rhoam-v4.13-stage-co-exist-rosa-rhods-rhoam

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-rhoam-v4.13-stage-co-exist-rosa-rhods-rhoam

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-rhoam-v4.13-stage-co-exist-rosa-rhods-rhoam

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-rhoam-v4.13-stage-co-exist-rosa-rhods-rhoam

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-rhoam-v4.13-stage-co-exist-rosa-rhods-rhoam

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-rhoam-v4.13-stage-co-exist-rosa-rhods-rhoam

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-rhoam-v4.13-stage-co-exist-rosa-rhods-rhoam

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-rhoam-v4.13-stage-co-exist-rosa-rhods-rhoam

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-rhoam-v4.13-stage-co-exist-rosa-rhods-rhoam

**Review by myakove — APPROVED** [review]

**Pull request merged**
