### PR TITLE
Tempo zstream onboarding on ibmcloud

### PR DESCRIPTION
**Pull request by smatula**

### CODE REVIEW

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.14-lp-interop-tempo-interop-ibmcloud periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.15-lp-interop-tempo-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.14-lp-interop-tempo-interop-ibmcloud periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.15-lp-interop-tempo-interop-ibmcloud

**Review by Simranpal — APPROVED** [review]
/lgtm

**Review by IshwarKanse — APPROVED** [review]
/lgtm

**Pull request merged**
