### PR TITLE
Add configuration for openshift/ci-tools

### PR DESCRIPTION
**Pull request by bbguimaraes**
/hold

### CODE REVIEW

**Comment by bbguimaraes** [comment]
> [ERROR] This check enforces that component configuration files are accompanied by OWNERS
> [ERROR] files so that the appropriate team is able to self-service further configuration
> [ERROR] change pull requests.

**Comment by droslean** [comment]
I think its better to do the first commit in `ci-tools` repo with the `OWNERS` file.

**Comment by bbguimaraes** [comment]
The repository is ready, all tests pass. The `lgtm` was lost because I had to add `OWNER` files (even though the top-level file was appropriate).

/hold cancel

**Comment by bbguimaraes** [comment]
… haha

/remove-sig azure

**Pull request merged**
