### PR TITLE
[4.14-4.16 multi nightly] add release 'target'

### PR DESCRIPTION
**Pull request by jianli-wei**
Debug the failures:
- https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-gcp-ipi-sdn-migration-ovn-amd-f28/1839194299359563776
- https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-gcp-ipi-sdn-migration-ovn-arm-f28/1820208685889097728
- https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-gcp-ipi-sdn-live-migration-ovn-f28/1833134178812563456
- https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.15-multi-nightly-gcp-ipi-sdn-migration-ovn-arm-f28/1830718925197807616

### CODE REVIEW

**Comment by jianli-wei** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-gcp-ipi-sdn-migration-ovn-amd-f28

**Comment by jianli-wei** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-gcp-ipi-sdn-migration-ovn-arm-f28

**Comment by jianli-wei** [comment]
@jianlinliu please help review, thanks!

**Comment by jianli-wei** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-gcp-ipi-sdn-live-migration-ovn-f28

**Comment by jianli-wei** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-multi-nightly-gcp-ipi-sdn-migration-ovn-arm-f28

**Comment by jianli-wei** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-gcp-ipi-sdn-live-migration-ovn-f28

**Comment by jianlinliu** [comment]
@jianli-wei good catch !

Per migration test chain:
```
$ cat ci-operator/step-registry/cucushift/sdn-migration-ovn/cucushift-sdn-migration-ovn-chain.yaml
chain:
  as: cucushift-sdn-migration-ovn
  steps:
  - ref: idp-htpasswd
  - ref: cucushift-pre
  - ref: openshift-extended-upgrade-pre    
  - ref: cucushift-upgrade-prepare
  - ref: cucushift-upgrade-prehealthcheck  
  - ref: ovn-sdn-migration
  - ref: openshift-extended-upgrade-post
  - ref: cucushift-upgrade-check
  - ref: openshift-upgrade-qe-test-report
```
`openshift-extended-upgrade-post` is referencing `target` release image on the [line](https://github.com/openshift/release/blob/master/ci-operator/step-registry/openshift-extended/upgrade/post/openshift-extended-upgrade-post-ref.yaml#L6). 

While I think we should fix the issue in the migration chain to remove the those step designed for upgrade ci which referenced `target` release image.

@zhaozhanqi Do you think running e2e is a MUST for the migration chain ? If no, I think `ovn-sdn-migration` + `cucushift-installer-check-cluster-health` is enough. If yes, can we pick up some e2e test from `openshift-e2e-test-qe` to run, instead of those upgrade e2e test steps including `openshift-extended-upgrade-pre`, `openshift-extended-upgrade-post`

**Comment by zhaozhanqi** [comment]
> @zhaozhanqi Do you think running e2e is a MUST for the migration chain ? If no, I think `ovn-sdn-migration` + `cucushift-installer-check-cluster-health` is enough. If yes, can we pick up some e2e test from `openshift-e2e-test-qe` to run, instead of those upgrade e2e test steps including `openshift-extended-upgrade-pre`, `openshift-extended-upgrade-post`

The flow for migration almost same with upgrade, So here is using upgrade test data to check the features are working well after migration.  So I prefer to keep it.

**Comment by jianlinliu** [comment]
sdn is removed from 4.17+, it will only affect 3 ci yaml files, I can let it go.

/lgtm

cc @liangxia to review.

**Comment by zhaozhanqi** [comment]
LGTM

**Pull request merged**
