### PR TITLE
MGMT-15397: wait for nutanixcsioperator package manifest

### PR DESCRIPTION
**Pull request by eliorerz**
/cc @eliorerz

### CODE REVIEW

**Comment by eliorerz** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-nutanix-assisted-periodic

**Comment by eliorerz** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-nutanix-assisted

**Comment by eliorerz** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-nutanix-assisted

**Comment by eliorerz** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-nutanix-assisted-periodic

**Comment by eliorerz** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-nutanix-assisted-periodic

**Comment by eliorerz** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-nutanix-assisted

**Comment by eliorerz** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-nutanix-assisted

**Comment by eliorerz** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-nutanix-assisted-periodic

**Comment by eliorerz** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-nutanix-assisted-periodic

**Comment by eliorerz** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-nutanix-assisted

**Comment by eliorerz** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-nutanix-assisted

**Comment by eliorerz** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-nutanix-assisted

**Comment by eliorerz** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-nutanix-assisted

**Comment by eliorerz** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-nutanix-assisted-periodic

**Comment by eliorerz** [comment]
/cc @osherdp @adriengentil 
The flakiness is due to other reasons and not the post installation steps

**Review by osherdp — APPROVED** [review]

**Pull request merged**
