### PR TITLE
Add tempest job for keystone operator

### PR DESCRIPTION
**Pull request by arxcruz**
This patch adds the keystone operator job with tempest

### CODE REVIEW

**Comment by arxcruz** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-keystone-operator-master-keystone-operator-build-deploy-tempest

**Comment by arxcruz** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-keystone-operator-master-keystone-operator-build-deploy-tempest

**Comment by arxcruz** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-keystone-operator-master-keystone-operator-build-deploy-tempest

**Comment by arxcruz** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-keystone-operator-master-keystone-operator-build-deploy-tempest

**Comment by arxcruz** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-keystone-operator-master-keystone-operator-build-deploy-tempest

**Comment by arxcruz** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-keystone-operator-master-keystone-operator-build-deploy-tempest

**Review by viroel — APPROVED** [review]
Thanks Arx

**Comment by viroel** [comment]
/pj-rehearsal ack

tempest job is passing[1]
[1] https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/rehearse-36539-pull-ci-openstack-k8s-operators-keystone-operator-master-keystone-operator-build-deploy-tempest

**Comment by viroel** [comment]
/pj-rehearse ack

tempest job is passing[1]
[1] https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/rehearse-36539-pull-ci-openstack-k8s-operators-keystone-operator-master-keystone-operator-build-deploy-tempest

**Pull request merged**
