### PR TITLE
Use RHEL9 for CO Content CI

### PR DESCRIPTION
**Pull request by Vincent056**
This commit updates CO content CI to use RHEL 9.2 base OCP.

### CODE REVIEW

**Comment by Vincent056** [comment]
/pj-rehearse pull-ci-ComplianceAsCode-content-master-e2e-aws-rhcos4-high

**Comment by Vincent056** [comment]
/pj-rehearse pull-ci-ComplianceAsCode-content-master-e2e-aws-ocp4-high-node

**Comment by Vincent056** [comment]
/pj-rehearse pull-ci-ComplianceAsCode-content-master-e2e-aws-ocp4-high

**Comment by Vincent056** [comment]
/pj-rehearse pull-ci-ComplianceAsCode-content-master-e2e-aws-rhcos4-moderate

**Comment by Vincent056** [comment]
/pj-rehearse pull-ci-ComplianceAsCode-content-master-e2e-aws-ocp4-moderate

**Comment by Vincent056** [comment]
/pj-rehearse pull-ci-ComplianceAsCode-content-master-e2e-aws-ocp4-stig

**Comment by Vincent056** [comment]
/pj-rehearse pull-ci-ComplianceAsCode-content-master-e2e-aws-rhcos4-high

**Comment by Vincent056** [comment]
/pj-rehearse pull-ci-ComplianceAsCode-content-master-e2e-aws-rhcos4-e8

**Comment by Vincent056** [comment]
/pj-rehearse pull-ci-ComplianceAsCode-content-master-e2e-aws-ocp4-stig-node

**Comment by Vincent056** [comment]
/pj-rehearse pull-ci-ComplianceAsCode-content-master-e2e-aws-ocp4-cis-node

**Comment by Vincent056** [comment]
/pj-rehearse pull-ci-ComplianceAsCode-content-master-e2e-aws-rhcos4-high

**Comment by Vincent056** [comment]
/pj-rehearse pull-ci-ComplianceAsCode-content-master-e2e-aws-ocp4-high-node

**Comment by Vincent056** [comment]
/pj-rehearse pull-ci-ComplianceAsCode-content-master-e2e-aws-rhcos4-high

**Comment by Vincent056** [comment]
/pj-rehearse pull-ci-ComplianceAsCode-content-master-e2e-aws-rhcos4-high

**Comment by Vincent056** [comment]
/pj-rehearse pull-ci-ComplianceAsCode-content-master-e2e-aws-rhcos4-high

**Comment by Vincent056** [comment]
/pj-rehearse pull-ci-ComplianceAsCode-content-master-e2e-aws-rhcos4-high

**Comment by jhrozek** [comment]
@Vincent056 did you remember to run `make update` before submitting the new version?

**Comment by Vincent056** [comment]
> make update

oops, forgot to run that, let me fix it

**Comment by Vincent056** [comment]
/pj-rehearse pull-ci-ComplianceAsCode-content-master-e2e-aws-rhcos4-high

**Comment by Vincent056** [comment]
The latest 4.13 image is already using rhel9, let's close this one

**Pull request closed without merging**
