### PR TITLE
renaming multicloudhub-repo to multiclusterhub-repo

### PR DESCRIPTION
**Pull request by nathanweatherly**
We're renaming multicloudhub-repo to multiclusterhub-repo

### CODE REVIEW

**Comment by nathanweatherly** [comment]
`read-only image store assigns the same name to multiple images` is new to me

**Comment by hongkailiu** [comment]
/lgtm
/hold
feel free to cancel if you want to fix the rehearsals later.

**Comment by nathanweatherly** [comment]
Thanks!

**Pull request merged**
