### PR TITLE
OCPQE-13626 yaml module is not available in ocp/4.8:upi-installer image

### PR DESCRIPTION
**Pull request by yunjiang29**
Resolve issue https://issues.redhat.com/browse/OCPQE-13626, replace python `pyyaml` module with `yq-go`

`yq-go` has been installed in:
* 4.8: https://github.com/openshift/installer/pull/6322
* 4.9: https://github.com/openshift/installer/pull/6316
* 4.10: https://github.com/openshift/installer/pull/6285
* 4.11: https://github.com/openshift/installer/pull/6225
* 4.12: https://github.com/openshift/installer/pull/6008

Current `python3 yaml` solution is applicable for 4.10+, after apply this fix it will be applicable for 4.8+

Tests:

- [x] `rehearse-36002-periodic-ci-openshift-openshift-tests-private-release-4.10-amd64-nightly-4.10-upgrade-from-eus-4.8-aws-upi-p3-f28`: [link](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/36002/rehearse-36002-periodic-ci-openshift-openshift-tests-private-release-4.10-amd64-nightly-4.10-upgrade-from-eus-4.8-aws-upi-p3-f28/1622509935382237184)
- [x] `rehearse-36002-periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-upi-p3-f28`: [link](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/36002/rehearse-36002-periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-upi-p3-f28/1622544289487654912)
- [x] `rehearse-36002-periodic-ci-openshift-openshift-tests-private-release-4.8-amd64-nightly-azure-upi-p3-f28` [link](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/36002/rehearse-36002-periodic-ci-openshift-openshift-tests-private-release-4.8-amd64-nightly-azure-upi-p3-f28/1622522648250552320)

### CODE REVIEW

**Comment by yunjiang29** [comment]
@jinyunma @jianlinliu @gpei please take a look, let me know if any potential issues, thanks.

<= 4.7 is not supported, I listed tool's availability [here](https://issues.redhat.com/browse/OCPQE-13626?focusedCommentId=21662047&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-21662047)

**Comment by yunjiang29** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.11-e2e-aws-upi-proxy

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.10-amd64-nightly-4.10-upgrade-from-eus-4.8-aws-upi-p3-f28

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.8-amd64-nightly-azure-upi-p3-f28

**Comment by jianlinliu** [comment]
From https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/36002/rehearse-36002-periodic-ci-openshift-openshift-tests-private-release-4.10-amd64-nightly-4.10-upgrade-from-eus-4.8-aws-upi-p3-f28/1621406355195695104, seem like we hit another script bug.

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.10-amd64-nightly-4.10-upgrade-from-eus-4.8-aws-upi-p3-f28

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.10-amd64-nightly-4.10-upgrade-from-eus-4.8-aws-upi-p3-f28

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.8-amd64-nightly-azure-upi-p3-f28

**Comment by yunjiang29** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.11-e2e-aws-upi-proxy

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.10-amd64-nightly-4.10-upgrade-from-eus-4.8-aws-upi-p3-f28

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.10-amd64-nightly-4.10-upgrade-from-eus-4.8-aws-upi-p3-f28

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.10-amd64-nightly-4.10-upgrade-from-eus-4.8-aws-upi-p3-f28

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.8-amd64-nightly-azure-upi-p3-f28

**Comment by yunjiang29** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.11-e2e-aws-upi-proxy

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.10-amd64-nightly-4.10-upgrade-from-eus-4.8-aws-upi-p3-f28

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.10-amd64-nightly-4.10-upgrade-from-eus-4.8-aws-upi-p3-f28

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.8-amd64-nightly-azure-upi-p3-f28

**Comment by yunjiang29** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.11-e2e-aws-upi-proxy

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-upi-p3-f28

**Comment by yunjiang29** [comment]
@jianlinliu PTAL, it's ready for merge now, see test result in https://github.com/openshift/release/pull/36002#issue-1569250056

**Pull request merged**
