### PR TITLE
Update OTEL jobs.

### PR DESCRIPTION
**Pull request by IshwarKanse**

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-upstream-ocp-4.15-amd64-aws-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-upstream-ocp-4.15-amd64-aws-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-upstream-ocp-4.15-amd64-aws-opentelemetry-e2e-tests

**Review by vprashar2929 — APPROVED** [review]

**Pull request merged**
