### PR TITLE
Add ci for 4.7 for knative-eventing{,-kafka} v0.21.0

### PR DESCRIPTION
**Pull request by lberk**

### CODE REVIEW

**Comment by lberk** [comment]
cc/ @matzew

**Comment by mgencur** [comment]
OCP 4.6 is maybe not required here? According to https://docs.google.com/spreadsheets/d/1HTxR37_MM03_JQImW-KmAFk1oEQ83fXzfGxdfWQSX6o/edit#gid=0 the next Serverless version will run on OCP 4.7 only.

**Comment by matzew** [comment]
@lberk is it possible to remove the 4.6 bits from this PR?

and than we update our script and remove the 4.6 generator?

**Comment by lberk** [comment]
thanks for the feedback! will do so (drop the 4.6 bits) shortly

**Comment by matzew** [comment]
are the failures expected ?

**Comment by lberk** [comment]
@matzew No, why would they be? :) they all passed yesterday and the error logs seem to indicate that the failures are infra related

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
