### PR TITLE
Drop Knative eventing periodics for 0.24

### PR DESCRIPTION
**Pull request by pierDipi**
0.24 is not supported anymore.

I'm not removing pre-submits and post-submits since serving keeps them.

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

/hold
to make sure all checkers do pass

**Comment by pierDipi** [comment]
@matzew running `make jobs` recreates these 2 files again [1], I guess that error is fine or how do I remove these jobs?

[1] _untracked files_
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.24-periodics.yaml
        ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.24-periodics.yaml
```

**Comment by matzew** [comment]
you need to remove the config from the job - sorry, did not catch that yesterday :see_no_evil: 

I've created a new PR, with two commits to show the process:
https://github.com/openshift/release/pull/27545

/close

**Pull request closed without merging**
