### PR TITLE
ComplianceAsCode: Add e2e tests to ocp4e2e repo

### PR DESCRIPTION
**Pull request by JAORMX**
Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>

### CODE REVIEW

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 725b2034549cfee1a8147f4e45162b1e5aa0181f

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 9915b845190f3b9ac4d83ac057354a2d68a791f4

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now a5b479f7f482ff841469c53f85d64809217f348e

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 6f0f842e20c4e95d505de860136ec9bf7463d2b4

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 6f72e945c389dac9bbeaac8815d4d8b5f99ec73e

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now c6c37da1d01176475f98213d34a9ce047b1183ed

**Review by jhrozek — APPROVED** [review]
/lgtm

**Review by jhrozek — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
