### PR TITLE
OCM-9705/OCM-9706 Setup `rosa-hcp-arm` jobs

### PR DESCRIPTION
**Pull request by radtriste**
- https://issues.redhat.com/browse/OCM-9705
- https://issues.redhat.com/browse/OCM-9706

depends on:
- https://github.com/openshift/rosa/pull/2268
- https://github.com/terraform-redhat/terraform-provider-rhcs/pull/724

### CODE REVIEW

**Comment by radtriste** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-hcp-arm-f7

**Comment by radtriste** [comment]
Failing due to https://issues.redhat.com/browse/OCM-9617

**Comment by radtriste** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-arm-optional-presubmit periodic-ci-openshift-rosa-master-e2e-rosa-hcp-arm-f7 periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-arm-f7

**Comment by radtriste** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-arm-optional-presubmit periodic-ci-openshift-rosa-master-e2e-rosa-hcp-arm-f7 periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-arm-f7

**Comment by radtriste** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-arm-optional-presubmit periodic-ci-openshift-rosa-master-e2e-rosa-hcp-arm-f7 periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-arm-f7

**Comment by radtriste** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-arm-critical-high-presubmit pull-ci-openshift-rosa-master-e2e-presubmits-pr-rosa-hcp-arm

**Review by ciaranRoche — APPROVED** [review]
/lgtm

**Pull request merged**
