### PR TITLE
API-1617: Add test which ensures the SNO cluster can recover after being suspended/shutdown

### PR DESCRIPTION
**Pull request by vrutkovs**
Ensures that the SNO cluster can be restored after:
* VM was suspended and resumed or
* machine was shut down and powered on again

when the following period has passed:

* 30 days
* 90 days
* 180 days
* 360 days

Current status:
* 119 days seems to be the max period, as otherwise openshift-apiserver(?) can't connect to kube-apiserver:
`
2024-01-23T12:48:28.078309356+00:00 stderr F E0123 12:48:28.078211      15 authentication.go:70] "Unable to authenticate the request" err="[x509: certificate has expired or is not yet valid: current time 2024-01-23T12:48:28Z is after 2023-11-24T12:20:41Z, verifying certificate SN=4550266744792405343, SKID=, AKID=BB:36:AC:22:3C:D3:10:A0:BA:08:9C:B4:DA:45:F3:F4:3D:45:B6:01 failed: x509: certificate has expired or is not yet valid: current time 2024-01-23T12:48:28Z is after 2023-11-24T12:20:41Z]"
`
* cert-rotation controller generates a new signer cert:
`
cabundle.go:64] Updated ca-bundle.crt configmap [#0]: "openshift-kube-apiserver-operator_aggregator-client-signer@1706381630" [] issuer="<self-signed>" (Jan 27 18:53:49 2024 to Jan 28 06:53:50 2024 (now=Jul 31 18:42:00 2023))/openshift-config-managed with:
`
but apparently installer pod is not created to place it on the node

### CODE REVIEW

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-shutdown-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-shutdown-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-shutdown-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Review by dinhxuanvu — COMMENTED** [review]
/lgtm

**Pull request merged**
