### PR TITLE
Upgrade ckcp to 0.9.0 & Openshift version 4.11

### PR DESCRIPTION
**Pull request by samyak-jn**
- Upgrade testing ckcp/openshift version for testing

Signed-off-by: Samyak Jain [samyak.jn11@gmail.com](mailto:samyak.jn11@gmail.com)

### CODE REVIEW

**Review by chetan-rns — APPROVED** [review]
/lgtm

**Review by jgwest — APPROVED** [review]
LGTM too, thank @samyak-jn!

**Pull request merged**
