### PR TITLE
Update OLM operator version of AMQ Streams to 2.4.0-3

### PR DESCRIPTION
**Pull request by im-konge**
This PR updates OLM_OPERATOR_VERSION for AMQ Streams operator after latest release.

### CODE REVIEW

**Comment by im-konge** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.14-lp-interop-amq-streams-2-4

**Comment by im-konge** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.14-lp-interop-amq-streams-2-4

**Review by Frawless — APPROVED** [review]

**Pull request merged**
