### PR TITLE
STOR-1819: Add manifest with OCP specific CSI certification tests

### PR DESCRIPTION
**Pull request by jsafrane**
Add configuration of OCP specific tests to Azure Disk and vSphere CSI testing workflows.

This is Azure + vSphere variant of https://github.com/openshift/release/pull/55204.

In both cases, pass `test/e2e/ocp-manifest.yaml` from `openshift/vmware-vsphere-csi-driver-operator` repo (or csi-operator) into `$SHARED_DIR` and use it as `$TEST_OCP_CSI_DRIVER_MANIFEST` when running openshift-tests with CSI certification suite for the vSphere or Azure CSI driver
    
This enables quite noisy test, run it only in a CSI driver periodic- jobs.

### CODE REVIEW

**Comment by jsafrane** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-csi pull-ci-openshift-vmware-vsphere-csi-driver-operator-release-4.18-e2e-vsphere-csi periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-csi

Expectation: periodic- runs the new test, pull- doesn't and AWS still works (I added is a small debug print there)

**Comment by jsafrane** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-csi pull-ci-openshift-vmware-vsphere-csi-driver-operator-release-4.18-e2e-vsphere-csi periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-csi

**Comment by jsafrane** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-csi pull-ci-openshift-vmware-vsphere-csi-driver-operator-release-4.18-e2e-vsphere-csi periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-csi periodic-ci-openshift-release-master-nightly-4.18-e2e-azure-csi pull-ci-openshift-csi-operator-release-4.18-e2e-azure-csi

**Comment by jsafrane** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-csi periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-csi

**Comment by jsafrane** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-azure-csi

**Comment by jsafrane** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-azure-csi periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-csi

they seem to pick old openshift-tests image

**Comment by jsafrane** [comment]
Finally, the rehearsal picked the newest openshift-tests and ran "OpenShift CSI extended - SCSI LUN Overflow should use many PVs on a single node" successfully on both Azure and vSphere.

This one failed even before installation on pull secrets
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-csi

**Comment by deepsm007** [comment]
/override ci/build-farm/build11-dry

We are syncing the cluster

**Comment by jsafrane** [comment]
cc @openshift/storage, I think it's ready for review

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Pull request merged**
