### PR TITLE
Remove superceded operation condition testing code

### PR DESCRIPTION
**Pull request by bparees**
this logic is superceded by
https://github.com/openshift/origin/blob/4fb407c2e22faa27276287f411829fb84a22545a/pkg/monitor/intervalcreation/operator.go#L85

### CODE REVIEW

**Comment by bparees** [comment]
@wking @deads2k ptal

**Comment by bparees** [comment]
/hold

need to add the mkdir back in

**Comment by wking** [comment]
Reverts are cheap if we change out mind :)

/lgtm

**Pull request merged**
