### PR TITLE
Bumps E2E_VERSION to 2.1.3

### PR DESCRIPTION
**Pull request by krishvoor**
This PR bumps `E2E_VERSION` to 2.1.3

### CODE REVIEW

**Comment by krishvoor** [comment]
@jtaleric @svetsa-rh @rsevilla87

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-data-path-9nodes

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-payload-control-plane-6nodes

**Review by rsevilla87 — APPROVED** [review]
lgtm

**Comment by rsevilla87** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-data-path-9nodes

**Review by jtaleric — APPROVED** [review]
lgtm

**Pull request merged**
