### PR TITLE
openshift-ansible: remove devel-40 tests

### PR DESCRIPTION
**Pull request by vrutkovs**
`devel-40` branch is no longer used

/cc @mtnbikenc

### CODE REVIEW

**Comment by mtnbikenc** [comment]
@vrutkovs I found two instances of devel-40 in cluster/ci/config/prow/plugins.yaml.  Is that file automatically updated?

**Comment by vrutkovs** [comment]
@mtnbikenc right, removed those

**Comment by vrutkovs** [comment]
@droslean @bbguimaraes @stevekuznetsov need your approval

**Pull request merged**
