### PR TITLE
ADO CI to conditionally run PKO tests

### PR DESCRIPTION
**Pull request by supreeth7**
Supersedes: https://github.com/openshift/release/pull/49055

### CODE REVIEW

**Comment by ashishmax31** [comment]
/pj-rehearse pull-ci-openshift-addon-operator-main-pko-e2e-tests

**Comment by supreeth7** [comment]
/pj-rehearse pull-ci-openshift-addon-operator-main-pko-e2e-tests

**Comment by ashishmax31** [comment]
/pj-rehearse pull-ci-openshift-addon-operator-main-operator-e2e

**Comment by ashishmax31** [comment]
@supreeth7 PKO e2e tests are not fixed by https://github.com/openshift/addon-operator/pull/578. Atleast when running locally they still fail.

**Comment by supreeth7** [comment]
@ashishmax31  Let's wait for the rehearsals to run to confirm the same

**Comment by ashishmax31** [comment]
@supreeth7  I say we merge this and fix the PKO tests later. In doing so we will unblock all PRs unrelated to PKO.

**Comment by supreeth7** [comment]
I was thinking along the same lines. Feel free to `/lgtm` it.

**Pull request merged**
