### PR TITLE
Set e2e test not to be auto run

### PR DESCRIPTION
**Pull request by Boomatang**
Documentation used: https://docs.ci.openshift.org/docs/how-tos/contributing-openshift-release/#tolerated-changes-to-generated-jobs

Jira: https://issues.redhat.com/browse/MGDAPI-1238

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
@Boomatang This looks like it should work. I'm not sure if it will allow tide to merge a pr without any e2e tests running. Is that what we expect? Also should we reflect this change on other branches? We are the owners here so we can approve it and merge and test it and make any changes later that we need.

**Comment by Boomatang** [comment]
@laurafitzgerald It was my assumption that we did want to force the e2e test to be ran before allowing PR's to merge. I felt the aim of the ticket was to allow PR authors to make changes to the PR with out have to worry about the e2e running each time.
I did not think of how this would apply to the other branches. I will follow up with this.

**Comment by laurafitzgerald** [comment]
@Boomatang ok, that makes sense. wdyt about getting this change merged to a feature branch and testing it, if you are not sure that it will work as expected. I didn't have time to delve into the docs myself.

**Comment by philbrookes** [comment]
The goal here is to leave the e2e optional, a PR can merge without them having run against that PR. It's upto the approver of the PR to decide if they want to run the e2e tests before approving or not.

**Comment by Boomatang** [comment]
Last push makes the both `e2e` and `rhoam-e2e` optional. They would need to be manually called by `/test <test name>`.

The current state means the test do not auto run on creation or changes to a PR and the test will not block the PR from been merged.

**Comment by laurafitzgerald** [comment]
@Boomatang can we put those onto all the branches? Without digging too much this looks like it will do what we want.

**Comment by Boomatang** [comment]
@laurafitzgerald I am not sure what you mean by branches.

**Comment by philbrookes** [comment]
@laurafitzgerald do you know how to do that? If it's not trivial, I'm happy for this change to only be applied to PRs against master for now.

**Comment by laurafitzgerald** [comment]
It's trivial. I just means adding the same config to each file in this directory https://github.com/openshift/release/tree/8ae2fc7000ee33a4382e280bbdda52709a626a6d/ci-operator/config/integr8ly/integreatly-operator

**Comment by Boomatang** [comment]
I had asked Phil about this on the jira. This change should only affect the master branch.

**Comment by laurafitzgerald** [comment]
@Boomatang to fix the failing test you need to run `make ci-operator-config` and commit the generated changes.
Also it doesn't seem to be recognising `always_run` in the json. Is this definitely a valid value in the docs?

**Comment by laurafitzgerald** [comment]
@Boomatang the change needs to go in https://github.com/openshift/release/blob/master/ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-master-presubmits.yaml#L4

**Comment by Boomatang** [comment]
@laurafitzgerald From my reading of the doc it seemed like that was the correct place to add them values and should have been accepted. But that raise a new question. It the file you linked the test we wish to not always have ran are marked as `always_run: false`. So why do they still run on PR changes.

The docs I was reading: https://docs.ci.openshift.org/docs/how-tos/contributing-openshift-release/#tolerated-changes-to-generated-jobs

**Comment by laurafitzgerald** [comment]
@Boomatang you can fix both failing jobs with `make jobs`

**Comment by Boomatang** [comment]
@laurafitzgerald PR is up to date and all test are passing

**Pull request merged**
