### PR TITLE
Add sync job for istio upstream to our istio fork

### PR DESCRIPTION
**Pull request by fjglira**
As part of the jira: https://issues.redhat.com/browse/OSSM-4505

We need to sync first the current fork with the master istio/istio repository

### CODE REVIEW

**Comment by fjglira** [comment]
/pj-rehearse periodic-ci-openshift-service-mesh-istio-master-sync-upstream-istio-master

**Comment by fjglira** [comment]
/pj-rehearse periodic-ci-openshift-service-mesh-istio-master-sync-upstream-istio-master

**Comment by fjglira** [comment]
/pj-rehearse periodic-ci-openshift-service-mesh-istio-master-sync-upstream-istio-master

**Comment by fjglira** [comment]
/pj-rehearse periodic-ci-openshift-service-mesh-istio-master-sync-upstream-istio-master

**Comment by fjglira** [comment]
/pj-rehearse periodic-ci-openshift-service-mesh-istio-master-sync-upstream-istio-master

**Comment by fjglira** [comment]
/pj-rehearse periodic-ci-openshift-service-mesh-istio-master-sync-upstream-istio-master

**Review by dgn — APPROVED** [review]

**Review by dgn — APPROVED** [review]

**Pull request merged**
