### PR TITLE
openstack-test: Kuryr job optional

### PR DESCRIPTION
**Pull request by pierreprinetti**
Kuryr testing signal is currently not reliable.

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
If the job is broken and it prevents merging code then it's fair game to make it optional until it stabilizes.
Do we have an issue where we track kuryr CI problems?

**Comment by dulek** [comment]
> If the job is broken and it prevents merging code then it's fair game to make it optional until it stabilizes. Do we have an issue where we track kuryr CI problems?

https://issues.redhat.com/browse/OCPBUGS-17066 is where I'm tracking it at the moment.

**Comment by dulek** [comment]
/lgtm

We intend to remove Kuryr in 4.15 anyway.

**Pull request merged**
