### PR TITLE
remove the yum-config-manager binary entirely to ensure no openshift dockerfiles rely on it

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton pj-rehearse of the images job succeeded, does that give us sufficient confidence that we can still build all the openshift images w/ this change?  I would think so......

**Comment by smarterclayton** [comment]
Wait, why move it?  Just leave it enabled (remove those two lines)

**Comment by bparees** [comment]
> Wait, why move it? Just leave it enabled (remove those two lines)

@smarterclayton i was under the impression you wanted it blocked to ensure no one introduced dockerfiles that use yum-config-manager?

i've updated the PR to leave yum-config-manager in place, so if that is indeed what you wanted, you can lgtm it now.

**Pull request merged**
