### PR TITLE
Move verification-tests agnostic packet jobs to new equinix profile

### PR DESCRIPTION
**Pull request by derekhiggins**
The current packet account will soon be closed.

### CODE REVIEW

**Comment by derekhiggins** [comment]
@jianlinliu would you be able to take a look

**Comment by jianlinliu** [comment]
The PR looks good to me, but I am thinking if we should remove the the baremetal test grid from QE's verification tests. 

@liangxia Maybe we can re-add them back after QE validated these jobs works on QE's equinix account, wdyt?

**Comment by liangxia** [comment]
> The PR looks good to me, but I am thinking if we should remove the the baremetal test grid from QE's verification tests, once that, maybe we can close this PR.
> 
> @liangxia Maybe we can re-add them back after QE validated these jobs works on QE's equinix account, wdyt?

All the jobs from QE with version 4.9/4.10 ( which are not based on installer team's profiles ) are removed.
We are focusing on 4.11 with install team's profiles.

**Comment by jianlinliu** [comment]
Thanks @liangxia 

@derekhiggins I guess all the jobs which referenced `cluster_profile: packet` are removed now, so I guess you can close this PR now.

**Pull request closed without merging**
