### PR TITLE
openstack: re-enable periodics for NFV on 4.12

### PR DESCRIPTION
**Pull request by EmilienM**

### CODE REVIEW

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.13-e2e-openstack-nfv-intel

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.13-e2e-openstack-nfv-intel

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.13-e2e-openstack-nfv-mellanox

**Comment by EmilienM** [comment]
So yeah, 4.12 jobs work fine. It's only an issue for non-GA versions (here 4.13)...

**Review by mandre — COMMENTED** [review]
Thanks!
/lgtm
/approve

**Pull request merged**
