### PR TITLE
ci-chat-bot/release-controller: use tokenFile in the kubeconfigs

### PR DESCRIPTION
**Pull request by hongkailiu**
https://issues.redhat.com/browse/DPTP-3142

For the easy maintenance, we split the kubeconfig to two files:
1. the static part: the content except token
2. the dynamic part: the token which will be refreshed periodically

We have tested this with sprint-automation and pod-scaler and they are working.

/hold

We need to know how those kuebconfigs are used.

Once merged, we need to rerun the generator job to get the items in Vault and the bootstrap job to sync them to secret on the cluster.

/cc @bradmwilliams

### CODE REVIEW

**Comment by bradmwilliams** [comment]
> 
> We need to know how those kuebconfigs are used.
> 
@hongkailiu We use the kubeconfig's to talk with the underlying build clusters to create prowjobs and gather the connection information, for the cluster that we launched, on the respective build cluster where it ran:
https://github.com/openshift/release/blob/1dfe4386e91bab7087f310e2b5f144ae6e9f82ba/clusters/app.ci/ci-chat-bot/ci-chat-bot.yaml#L166-L181

The current logic reads the kubeconfigs from the local filesystem and then stores them in memory:
https://github.com/openshift/ci-chat-bot/blob/f6c13ed57208c9d05c81d51d5f4165bbf47da3f3/main.go#L181-L227
and we watch for changes here:
https://github.com/openshift/ci-chat-bot/blob/f6c13ed57208c9d05c81d51d5f4165bbf47da3f3/main.go#L229-L255

**Comment by hongkailiu** [comment]
The simplest way of adopting this (I do not want this change either but upstream has moved away):
1. modify the code to ignore certain files (as a flag) while loading kubeconfigs. See [how Prow deals with it](https://github.com/kubernetes/test-infra/pull/27436/files#diff-f1358dea208000900b4c086f35daa0a81630f82b095ad1395fe33d859bf80927R109-R112).
2. mount the `sa.ci-chat-bot.{cluster}.token.txt` files into the same folder: They are the token part of `sa.ci-chat-bot.{cluster}.config`.

**Comment by bradmwilliams** [comment]
@hongkailiu For the `release-controller` it's very similar as well.  We just have different service accounts for all the different flavors of the release-controller, so we have hold the `app.ci` kubeconfig in the respective secret...
https://github.com/openshift/release/blob/1dfe4386e91bab7087f310e2b5f144ae6e9f82ba/clusters/app.ci/release-controller/deploy-ocp-controller.yaml#L169
https://github.com/openshift/release/blob/1dfe4386e91bab7087f310e2b5f144ae6e9f82ba/clusters/app.ci/release-controller/deploy-ocp-controller.yaml#L292-L298

**Review by bradmwilliams — APPROVED** [review]

**Pull request merged**
