### PR TITLE
4.16 lp interop configs add firewatch success rule

### PR DESCRIPTION
**Pull request by smatula**

### CODE REVIEW

**Comment by smatula** [comment]
/pj-rhearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.16-lp-interop-csb-interop-aws-latest periodic-ci-openshift-knative-serverless-operator-main-ocp4.16-lp-interop-operator-e2e-interop-aws-ocp416

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.16-lp-interop-csb-interop-aws-latest periodic-ci-openshift-knative-serverless-operator-main-ocp4.16-lp-interop-operator-e2e-interop-aws-ocp416

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
