### PR TITLE
HOSTEDCP-1666: openshift-controller-manager: add hypershift conformance presubmit test

### PR DESCRIPTION
**Pull request by sjenning**
We encountered a regression originating from this repo on release blocking hypershift conformance.

Add as a presubmit to guard against regression in the future.

### CODE REVIEW

**Comment by sjenning** [comment]
/pj-rehearse pull-ci-openshift-openshift-controller-manager-master-e2e-hypershift-conformance

**Comment by sjenning** [comment]
/pj-rehearse pull-ci-openshift-openshift-controller-manager-master-e2e-hypershift-conformance

**Comment by sjenning** [comment]
/pj-rehearse pull-ci-openshift-openshift-controller-manager-master-e2e-hypershift-conformance

**Comment by sjenning** [comment]
/pj-rehearse pull-ci-openshift-openshift-controller-manager-master-e2e-hypershift-conformance

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Pull request merged**
