### PR TITLE
Add two missing baremetal workflows

### PR DESCRIPTION
**Pull request by danwinship**
There are currently baremetal workflows to run the serial and upgrade tests with sdn+ipv4 and ovn+ipv6, but not with ovn+ipv4. This fixes that.

### CODE REVIEW

**Comment by derekhiggins** [comment]
@danwinship these look fine to me, just wondering if there is a plan to use them, we usually just add them if needed

**Comment by danwinship** [comment]
@derekhiggins oh, sorry; this is part of the "getting rid of openshift-sdn in CI" thing.

A bunch of repos are using `baremetalds-e2e-sdn-serial-ipv4` / `baremetalds-e2e-upgrade-sdn`, but don't actually care about SDN specifically. I was going to suggest that they switch to `baremetalds-e2e-serial-ovn-ipv6` / `baremetalds-e2e-upgrade-ovn-ipv6`, but it seemed slightly weird to say "you have to switch from ipv4 to ipv6", and maybe some people would rather avoid additional ipv6 jobs since that's another set of potential flakes for them to deal with that are really somebody else's problem...

There are also cases like cluster-baremetal-operator, which currently tests sdn+ipv4 upgrade and ovn+ipv6 upgrade, and it's not clear if the right way forward is "just test ovn+ipv6" or "test ovn+ipv4 and ovn+ipv6"... (That ambiguity also exists in multiple repos with `e2e-metal-ipi-sdn` vs `e2e-metal-ipi-ovn-ipv6`, but in that case the ovn+ipv4 job already exists, so the repo owners can already choose whichever resolution they want.)

I guess I could just tell people "switch to the ovn+ipv6 workflows, or if you really don't want that, then go comment on this PR and say you want the ovn+ipv4 ones"?

**Comment by derekhiggins** [comment]
/approve

thanks for the explanation, makes sense.

**Comment by stbenjam** [comment]
/lgtm

Do you plan to create jobs that use this? It should probably be an informer on payloads

**Comment by danwinship** [comment]
@stbenjam the bot didn't seem to catch your lgtm?
re jobs, see https://github.com/openshift/release/pull/47558#issuecomment-1910350985

**Pull request merged**
