### PR TITLE
This commit will intall kustomize 

### PR DESCRIPTION
**Pull request by tonyxrmdavidson**
his commit will intall kustomize as the first step of the update to use istio configuration

### CODE REVIEW

**Comment by tonyxrmdavidson** [comment]
`% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 23.4M  100 23.4M    0     0  88.9M      0 --:--:-- --:--:-- --:--:-- 88.9M
Version: {Version:kustomize/v3.2.3 GitCommit:f8412aa3d39f32151525aff97a351288f5a7470b BuildDate:2019-10-08T23:30:25Z GoOs:linux GoArch:amd64}
Deploying opendatahub-subscription from openshift-ci/resources/opendatahub-subscription.yaml...
subscription.operators.coreos.com/model-registry-test-source-subscription created
[0;32m✔ Success:[0m Deployment of opendatahub-subscription succeeded.
Monitoring the installation of CRDs: datascienceclusters.datasciencecluster.opendatahub.io dscinitializations.dscinitialization.opendatahub.io featuretrackers.features.opendatahub.io
Timeout set to 120s
CRD 'datascienceclusters.datasciencecluster.opendatahub.io' is not installed.
CRD 'dscinitializations.dscinitialization.opendatahub.io' is not installed.
CRD 'featuretrackers.features.opendatahub.io' is not installed.
CRD 'datascienceclusters.datasciencecluster.opendatahub.io' is not installed.
CRD 'dscinitializations.dscinitialization.opendatahub.io' is not installed.
CRD 'featuretrackers.features.opendatahub.io' is not installed.
CRD 'datascienceclusters.datasciencecluster.opendatahub.io' is not installed.
CRD 'dscinitializations.dscinitialization.opendatahub.io' is not installed.
CRD 'featuretrackers.features.opendatahub.io' is not installed.
CRD 'datascienceclusters.datasciencecluster.opendatahub.io' is not installed.
CRD 'dscinitializations.dscinitialization.opendatahub.io' is not installed.
CRD 'featuretrackers.features.opendatahub.io' is not installed.
CRD 'datascienceclusters.datasciencecluster.opendatahub.io' is not installed.
CRD 'dscinitializations.dscinitialization.opendatahub.io' is not installed.
CRD 'featuretrackers.features.opendatahub.io' is not installed.
CRD 'datascienceclusters.datasciencecluster.opendatahub.io' is not installed.
CRD 'dscinitializations.dscinitialization.opendatahub.io' is not installed.
CRD 'featuretrackers.features.opendatahub.io' is not installed.
CRD 'datascienceclusters.datasciencecluster.opendatahub.io' is not installed.
CRD 'dscinitializations.dscinitialization.opendatahub.io' is not installed.
CRD 'featuretrackers.features.opendatahub.io' is not installed.
CRD 'datascienceclusters.datasciencecluster.opendatahub.io' is not installed.
CRD 'dscinitializations.dscinitialization.opendatahub.io' is not installed.
CRD 'featuretrackers.features.opendatahub.io' is not installed.
CRD 'datascienceclusters.datasciencecluster.opendatahub.io' is not installed.
CRD 'dscinitializations.dscinitialization.opendatahub.io' is not installed.
CRD 'featuretrackers.features.opendatahub.io' is not installed.
CRD 'datascienceclusters.datasciencecluster.opendatahub.io' is not installed.
CRD 'dscinitializations.dscinitialization.opendatahub.io' is not installed.
CRD 'featuretrackers.features.opendatahub.io' is not installed.
CRD 'datascienceclusters.datasciencecluster.opendatahub.io' is not installed.
CRD 'dscinitializations.dscinitialization.opendatahub.io' is not installed.
CRD 'featuretrackers.features.opendatahub.io' is not installed.
CRD 'datascienceclusters.datasciencecluster.opendatahub.io' is not installed.
CRD 'dscinitializations.dscinitialization.opendatahub.io' is not installed.
CRD 'featuretrackers.features.opendatahub.io' is not installed.
CRD 'datascienceclusters.datasciencecluster.opendatahub.io' is not installed.
CRD 'dscinitializations.dscinitialization.opendatahub.io' is not installed.
CRD 'featuretrackers.features.opendatahub.io' is not installed.
CRD 'datascienceclusters.datasciencecluster.opendatahub.io' is not installed.
CRD 'dscinitializations.dscinitialization.opendatahub.io' is not installed.
CRD 'featuretrackers.features.opendatahub.io' is not installed.
[0;32m✔ Success:[0m All specified CRDs are installed.
Deploying model-registry-DSCInitialization from openshift-ci/resources/model-registry-DSCInitialization.yaml...
dscinitialization.dscinitialization.opendatahub.io/default-dsci created
[0;32m✔ Success:[0m Deployment of model-registry-DSCInitialization succeeded.
Deploying opendatahub-data-science-cluster from openshift-ci/resources/opendatahub-data-science-cluster.yaml...
datasciencecluster.datasciencecluster.opendatahub.io/default-dsc created
[0;32m✔ Success:[0m Deployment of opendatahub-data-science-cluster succeeded.
Monitoring the installation of CRDs: acceleratorprofiles.dashboard.opendatahub.io datasciencepipelinesapplications.datasciencepipelinesapplications.opendatahub.io odhapplications.dashboard.opendatahub.io odhdashboardconfigs.opendatahub.io odhdocuments.dashboard.opendatahub.io
Timeout set to 120s
CRD 'acceleratorprofiles.dashboard.opendatahub.io' is not installed.
CRD 'datasciencepipelinesapplications.datasciencepipelinesapplications.opendatahub.io' is not installed.
CRD 'odhapplications.dashboard.opendatahub.io' is not installed.
CRD 'odhdashboardconfigs.opendatahub.io' is not installed.
CRD 'odhdocuments.dashboard.opendatahub.io' is not installed.
CRD 'acceleratorprofiles.dashboard.opendatahub.io' is installed.
CRD 'datasciencepipelinesapplications.datasciencepipelinesapplications.opendatahub.io' is not installed.
CRD 'odhapplications.dashboard.opendatahub.io' is installed.
CRD 'odhdashboardconfigs.opendatahub.io' is installed.
CRD 'odhdocuments.dashboard.opendatahub.io' is installed.
CRD 'acceleratorprofiles.dashboard.opendatahub.io' is installed.
CRD 'datasciencepipelinesapplications.datasciencepipelinesapplications.opendatahub.io' is not installed.
CRD 'odhapplications.dashboard.opendatahub.io' is installed.
CRD 'odhdashboardconfigs.opendatahub.io' is installed.
CRD 'odhdocuments.dashboard.opendatahub.io' is installed.
CRD 'acceleratorprofiles.dashboard.opendatahub.io' is installed.
CRD 'datasciencepipelinesapplications.datasciencepipelinesapplications.opendatahub.io' is not installed.
CRD 'odhapplications.dashboard.opendatahub.io' is installed.
CRD 'odhdashboardconfigs.opendatahub.io' is installed.
CRD 'odhdocuments.dashboard.opendatahub.io' is installed.
CRD 'acceleratorprofiles.dashboard.opendatahub.io' is installed.
CRD 'datasciencepipelinesapplications.datasciencepipelinesapplications.opendatahub.io' is not installed.
CRD 'odhapplications.dashboard.opendatahub.io' is installed.
CRD 'odhdashboardconfigs.opendatahub.io' is installed.
CRD 'odhdocuments.dashboard.opendatahub.io' is installed.
[0;32m✔ Success:[0m All specified CRDs are installed.
error: resource name may not be empty
[0;33m! INFO:[0m  Pod  is not running or does not have 2 containers ready
error: resource name may not be empty
[0;33m! INFO:[0m  Pod  is not running or does not have 2 containers ready
error: resource name may not be empty
[0;33m! INFO:[0m  Pod  is not running or does not have 2 containers ready
error: resource name may not be empty
[0;33m! INFO:[0m  Pod  is not running or does not have 2 containers ready
error: resource name may not be empty
[0;33m! INFO:[0m  Pod  is not running or does not have 2 containers ready
[0;33m! INFO:[0m  Pod model-registry-operator-controller-manager-6c5bb7845b-csjvs is not running or does not have 2 containers ready
[0;33m! INFO:[0m  Pod model-registry-operator-controller-manager-6c5bb7845b-csjvs is not running or does not have 2 containers ready
[0;33m! INFO:[0m  Pod model-registry-operator-controller-manager-6c5bb7845b-csjvs is not running or does not have 2 containers ready
[0;33m! INFO:[0m  Pod model-registry-operator-controller-manager-6c5bb7845b-csjvs is not running or does not have 2 containers ready
[0;32m✔ Success:[0m Pod model-registry-operator-controller-manager-6c5bb7845b-csjvs is running and 2 out of 2 containers are ready
Deploying modelregistry_v1alpha1_modelregistry from openshift-ci/resources/model-registry-operator/modelregistry_v1alpha1_modelregistry.yaml...
modelregistry.modelregistry.opendatahub.io/modelregistry-sample created
[0;32m✔ Success:[0m Deployment of modelregistry_v1alpha1_modelregistry succeeded.
Monitoring the installation of CRDs: modelregistries.modelregistry.opendatahub.io
Timeout set to 120s
[0;32m✔ Success:[0m All specified CRDs are installed.
Deploying mysql-db from openshift-ci/resources/model-registry-operator/mysql-db.yaml...
service/model-registry-db created
persistentvolumeclaim/model-registry-db created
deployment.apps/model-registry-db created
secret/model-registry-db created
[0;32m✔ Success:[0m Deployment of mysql-db succeeded.
[0;32m✔ Success:[0m Deployment model-registry-db is available
[0;32m✔ Success:[0m Deployment modelregistry-sample is available
[0;33m! INFO:[0m  Pod model-registry-db-6d648f9f59-p54m2 is not running or does not have 1 containers ready
[0;33m! INFO:[0m  Pod model-registry-db-6d648f9f59-p54m2 is not running or does not have 1 containers ready
[0;33m! INFO:[0m  Pod model-registry-db-6d648f9f59-p54m2 is not running or does not have 1 containers ready
[0;33m! INFO:[0m  Pod model-registry-db-6d648f9f59-p54m2 is not running or does not have 1 containers ready
[0;33m! INFO:[0m  Pod model-registry-db-6d648f9f59-p54m2 is not running or does not have 1 containers ready
[0;33m! INFO:[0m  Pod model-registry-db-6d648f9f59-p54m2 is not running or does not have 1 containers ready
[0;33m! INFO:[0m  Pod model-registry-db-6d648f9f59-p54m2 is not running or does not have 1 containers ready
[0;33m! INFO:[0m  Pod model-registry-db-6d648f9f59-p54m2 is not running or does not have 1 containers ready
[0;32m✔ Success:[0m Pod model-registry-db-6d648f9f59-p54m2 is running and 1 out of 1 containers are ready
[0;33m! INFO:[0m  Pod modelregistry-sample-7f8b66d8bf-rff84 is not running or does not have 2 containers ready
[0;33m! INFO:[0m  Pod modelregistry-sample-7f8b66d8bf-rff84 is not running or does not have 2 containers ready
[0;33m! INFO:[0m  Pod modelregistry-sample-7f8b66d8bf-rff84 is not running or does not have 2 containers ready
[0;33m! INFO:[0m  Pod modelregistry-sample-7f8b66d8bf-rff84 is not running or does not have 2 containers ready
[0;32m✔ Success:[0m Pod modelregistry-sample-7f8b66d8bf-rff84 is running and 2 out of 2 containers are ready
[0;32m✔ Success:[0m Route 'modelregistry-sample-http' exists in namespace 'opendatahub'
[0;32m✔ Success:[0m Route server is reachable. Status code: 200 OK
Success: Registered Model ID: 1
Success: Model Version ID: 2
Success: Model Artifact ID: 1`

**Comment by dhirajsb** [comment]
@tonyxrmdavidson Is there a need for using kustomize directly? The `oc` command has a `-k` option to process kustomize yaml and apply it.

**Pull request closed without merging**
