### PR TITLE
Add floating image tags for opendatahub image builds

### PR DESCRIPTION
**Pull request by z103cb**
* Added `DO_PERIODIC_JOB_FLOATING_TAG` environment variable to the  image-mirror script.  The default value is set to `false`
* Overrode the DO_PERIODIC_JOB_FLOATING_TAG environment variable

### CODE REVIEW

**Comment by Xaenalt** [comment]
Oh, I see why I can't ACK it, can you modify the OWNERS file for this new step-registry part

**Comment by heyselbi** [comment]
@z103cb looks like it needs @VaishnaviHire's approval

**Review by VaishnaviHire — APPROVED** [review]

**Review by vaibhavjainwiz — APPROVED** [review]
/lgtm

**Pull request merged**
