### PR TITLE
Promote dev-scripts image to openshift-kni namespace

### PR DESCRIPTION
**Pull request by andfasano**
This change is required to stop promoting the `dev-scripts` test image in the `ocp/4.x` image stream, since this forces the `dev-scripts` repo to fall within the OpenShift CI centralized release branch management, and we'd like to avoid that.
The fix then promotes the `dev-scripts` image into the `openshift-kni/test` image stream.

### CODE REVIEW

**Comment by stbenjam** [comment]
Looks like there's a conflict now in openshift-metal3-dev-scripts-release-4.6-presubmits.yaml

Will this affect the 4.5 periodic at all?

**Comment by andfasano** [comment]
> Looks like there's a conflict now in openshift-metal3-dev-scripts-release-4.6-presubmits.yaml
> 
> Will this affect the 4.5 periodic at all?

No (of course we will have to add the proper `base_images` stanza to let them fetch the `dev-scripts` image from the `openshift-kni/tests" stream)

**Pull request merged**
