### PR TITLE
Adding agent proxy job

### PR DESCRIPTION
**Pull request by jhou1**
Adding E2E integration to disconnected proxy installation with agent-based installer.

/hold until test is finished.

### CODE REVIEW

**Comment by jhou1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-baremetal-compact-agent-ipv4-static-disconnected-proxy-p1-f7

**Comment by jhou1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-baremetal-compact-agent-ipv4-static-disconnected-proxy-p1-f7

**Comment by jhou1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-baremetal-compact-agent-ipv4-static-disconnected-proxy-p1-f7

**Comment by jhou1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-baremetal-compact-agent-ipv4-static-disconnected-proxy-p1-f7

**Comment by jhou1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-baremetal-compact-agent-ipv4-static-disconnected-proxy-p1-f7

**Comment by jhou1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-baremetal-compact-agent-ipv4-static-disconnected-proxy-p1-f7

**Comment by jhou1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-baremetal-compact-agent-ipv4-static-disconnected-proxy-p1-f7

**Comment by jhou1** [comment]
Tested and reedy for merge

/assign @mhanss @bmanzari @liangxia

**Comment by liangxia** [comment]
@jhou1 The PR has WIP in the title, it's blocking the PR from auto merging.

**Comment by jhou1** [comment]
Thanks, I did remove `WIP` this morning, but due to browser connection issue the submit didn't happen..

**Comment by liangxia** [comment]
Looks like we need fetch latest codes and rebase

**Pull request merged**
