### PR TITLE
chore: remove hacbs periodic job, update flavours

### PR DESCRIPTION
**Pull request by psturc**
* remove hacbs periodic job, that is not relevant anymore
* update node flavour for RHTAP CI jobs

### CODE REVIEW

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests

**Review by johnmcollier — APPROVED** [review]
approving for the HAS job changes

/lgtm

**Pull request merged**
