### PR TITLE
always kill the backgroup process of copy_kubeconfig_pid when exit

### PR DESCRIPTION
**Pull request by jianlinliu**
1. Per the [log](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/39084/rehearse-39084-periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-stable-4.1-aws-ipi-p1-f30/1654683405553504256), even ipi-install-install failed, it did not exit until time out (2 hours); 
```
error: failed to execute wrapped command: exit status 127 
INFO[2023-05-06T05:17:33Z] Step aws-ipi-p1-f30-ipi-install-install failed after 2h10m17s.
```
After this fix, save a lot of time, here is the [log](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/39084/rehearse-39084-periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-stable-4.1-aws-ipi-p1-f30/1654740120315629568) .
```
error: failed to execute wrapped command: exit status 1 
INFO[2023-05-06T07:32:38Z] Step aws-ipi-p1-f30-ipi-install-install failed after 40m10s. 
```
2. During the debugging, found another issue about `configure-registry-storage-destroy-s3-cloudfront` in the [log](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/39084/rehearse-39084-periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-stable-4.1-aws-ipi-p1-f30/1654683405553504256), it will hang the job for a long time:
```
* 127x kubelet: Back-off pulling image "image-registry.openshift-image-registry.svc:5000/ci-op-xgfv2jf6/stable:upi-installer"
* 2x kubelet: Error: ImagePullBackOff 
INFO[2023-05-06T05:55:26Z] Step aws-ipi-p1-f30-configure-registry-storage-destroy-s3-cloudfront failed after 30m11s. 
```
Not each job define upi-installer imageStream, So use a fixed version of upi-installer image to run the step.
and strongly recommend to use a separate workflow to cover the registry s3 cloudfront install, so I peel off the deploy/destroy ref from aws-ipi-sdn-provision/aws-ipi-deprovision chains and create a dedicated install workflow for it.

### CODE REVIEW

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-stable-4.1-aws-ipi-p1-f30

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-stable-4.1-aws-ipi-p1-f30

**Comment by jianlinliu** [comment]
cc @liangxia to review the timeout issue fix.
cc @xiuwang and @wewang58 to review registry s3 cloudfront issue, once this PR get merged, you need to add a dedicated ci job to cover it. cc @yunjiang29.

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.11-installer-rehearse-aws

**Comment by xiuwang** [comment]
/lgtm
@jianlinliu thanks

**Comment by yunjiang29** [comment]
looks good to me.

**Pull request merged**
