### PR TITLE
OKD: ironic-image okd-scos specific builds for master, >4.12

### PR DESCRIPTION
**Pull request by sherine-k**
This PR is a partial replacement for https://github.com/openshift/release/pull/34166 for ironic-image

### CODE REVIEW

**Comment by sherine-k** [comment]
> @sherine-k could you update the Dockerfile path to Dockerfile.scos?
Done

**Review by elfosardo — CHANGES_REQUESTED** [review]
I strongly suggest to use stream9, all the packages used come from cs9/rhel9 and this could break without notice
ironic upstream has removed support for python3.6 and CS8 since the beginning of the year, we removed support in the ironic openshift containers right after

**Review by elfosardo — APPROVED** [review]

**Comment by sherine-k** [comment]
/unhold
https://github.com/openshift/ironic-image/pull/320 merged

**Comment by elfosardo** [comment]
@sherine-k the images build jobs are failing because of some missing config:
4.12 is failing because of missing dockerfile in the ironic-image repo in release 4.12 -> need to backport https://github.com/openshift/ironic-image/pull/320 (or similar) to 4.12
4.14 is failing because of missing scos image origin/scos-4.14 -> need to check with ART ?

**Comment by sherine-k** [comment]
/hold
Needs https://github.com/openshift/ironic-image/pull/329 to merge

**Comment by LorbusChris** [comment]
https://github.com/openshift/ironic-image/pull/329 has merged

/pj-rehearse
/hold cancel

**Comment by LorbusChris** [comment]
Will look fixing at scos-4.14 later.
/rehearsals-ack

**Comment by LorbusChris** [comment]
/hold
this is using stream8 base images, is that intended?

**Pull request merged**
