### PR TITLE
Add e2e-cmd

### PR DESCRIPTION
**Pull request by tnozicka**
optional but always run

/cc @deads2k

### CODE REVIEW

**Comment by tnozicka** [comment]
/hold
requires https://github.com/openshift/origin/pull/23432

**Comment by deads2k** [comment]
https://github.com/openshift/origin/pull/23453 merged so we can try this rehearse again.

**Comment by deads2k** [comment]
throttling

/retest

**Comment by sttts** [comment]
https://github.com/openshift/origin/pull/23432 merged.

/hold cancel

**Comment by enj** [comment]
/hold cancel
/lgtm

I see it went green.  David will need to approve when he gets back.

**Pull request merged**
