### PR TITLE
updating operator sdk version in preflight presubmits

### PR DESCRIPTION
**Pull request by acornett21**

### CODE REVIEW

**Comment by acornett21** [comment]
/pj-rehearse pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.12-e2e pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.12-images pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.16-e2e pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.16-images

**Comment by acornett21** [comment]
/pj-rehearse pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.16-e2e

**Comment by acornett21** [comment]
/pj-rehearse pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.16-e2e

**Review by komish — APPROVED** [review]
/lgtm

**Review by skattoju — APPROVED** [review]

**Pull request merged**
