### PR TITLE
OCPVE-329: Revert "Revert "feat: added the test steps for rt-tests to the rt upgrade jobs""

### PR DESCRIPTION
**Pull request by jeff-roche**
Reverts openshift/release#38252

### CODE REVIEW

**Comment by jeff-roche** [comment]
@dgoodwin we are bringing this one back so that we can begin looking into why the aggregated job was failing

**Comment by stbenjam** [comment]
We generally don't run two test suites in the same job, the job you're adding it to is for upgrade conformance. Can we create a separate job that runs the RT suite? 

You will not run the RT suite anyway if the main conformance fails because it will get skipped: https://docs.ci.openshift.org/docs/architecture/step-registry/#workflow

It would also mean you don't need to duplicate the test step, and could just set TEST_TYPE instead and call the typical test step.

**Comment by jeff-roche** [comment]
Replaced by #40074 with new approach suggested by @stbenjam

**Pull request closed without merging**
