### PR TITLE
Add e2e tests for aws-ipi-proxy 4.11

### PR DESCRIPTION
**Pull request by liangxia**

### CODE REVIEW

**Comment by liangxia** [comment]
/cc @jhou1 @JianLi-RH @dis016 @pruan-rht 

PR ready for review, and all tests passed.

**Comment by jhou1** [comment]
Thanks, Liang,

I think this PR is ready to merge, but looking at the results, the three failures are pretty consistent from `Egress-ingress related networking scenarios`, do they require some additional configuration?

**Comment by jhou1** [comment]
@lihongan Could you please help us know if we were missing something here? https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/27199/rehearse-27199-periodic-ci-openshift-verification-tests-master-nightly-4.11-e2e-aws-ipi-proxy/1506536163203092480

**Comment by lihongan** [comment]
> @lihongan Could you please help us know if we were missing something here? https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/27199/rehearse-27199-periodic-ci-openshift-verification-tests-master-nightly-4.11-e2e-aws-ipi-proxy/1506536163203092480

@huiran0826 Could you please help take a look? It seems all failed cases are EgressNetworPolicy related, maybe they are not runnable in proxy cluster.
cc @zhaozhanqi

**Comment by zhaozhanqi** [comment]
@weliang1 @huiran0826 seems these cases cannot be tested on proxy cluster, please double confirm, if yes, Please help add `@noproxy` tag for these cases, thanks.

**Comment by weliang1** [comment]
> @weliang1 @huiran0826 seems these cases cannot be tested on proxy cluster, please double confirm, if yes, Please help add `@noproxy` tag for these cases, thanks.

@huiran0826 They are all egressnetworkpolicy cases:

- Egress-ingress related networking scenarios: Apply same egress network policy in different projects expand_more	
- Egress-ingress related networking scenarios: Service with a DNS name can not by pass Egressnetworkpolicy with IP corresponding that DNS name expand_more	
- Egress-ingress related networking scenarios: The endpoints in EgressNetworkPolicy denying cidrSelector will be ignored expand_more

**Comment by huiran0826** [comment]
They cases missed the noproxy tag, I will update cases.

**Comment by liangxia** [comment]
> These cases missed the noproxy tag, I will update cases.

Thanks.  Also don't forgot the update the related field in Polarion.

**Comment by huiran0826** [comment]
https://github.com/openshift/cucushift/pull/9079

**Comment by liangxia** [comment]
Related feature team have fixed the failures.

PR ready for review.

**Review by dis016 — COMMENTED** [review]
LGTM

**Pull request merged**
