### PR TITLE
SPLAT-986: vSphere multi-zone upgrade workflow

### PR DESCRIPTION
**Pull request by rvanderp3**
Enabling vSphere mutli-zone workload and periodic per [SPLAT-730](https://issues.redhat.com/browse/SPLAT-730)

### CODE REVIEW

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-upgrade-from-stable-4.13-e2e-vsphere-ovn-zones-upgrade

**Comment by rvanderp3** [comment]
/hold
found an issue in the rehearsal about the job name

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-upgrade-from-stable-4.13-e2e-vsphere-ovn-zones-upgrade

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-upgrade-from-stable-4.13-e2e-vsphere-zones-upgrade

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-upgrade-from-stable-4.13-e2e-vsphere-zones-upgrade

**Review by wking — APPROVED** [review]
/lgtm

Poking at [the rehearsal][1], I see multiple data centers in a single vCenter:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/37187/rehearse-37187-periodic-ci-openshift-release-master-nightly-4.14-upgrade-from-stable-4.13-e2e-vsphere-zones-upgrade/1635080362419818496/artifacts/e2e-vsphere-zones-upgrade/gather-must-gather/artifacts/must-gather.tar | tar xOz quay-io-openshift-release-dev-ocp-v4-0-art-dev-sha256-6d68129c33361a4dbc1831ae87d25a338cc55fb8fd9c045bab498300735f7b95/cluster-scoped-resources/config.openshift.io/infrastructures/cluster.yaml | yaml2json | jq .spec.platformSpec.vsphere.vcenters
[
  {
    "datacenters": [
      "IBMCloud",
      "datacenter-2"
    ],
    "port": 443,
    "server": "ibmvcenter.vmc-ci.devcluster.openshift.com"
  }
]
```

And a successful update from 4.13 to 4.14:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/37187/rehearse-37187-periodic-ci-openshift-release-master-nightly-4.14-upgrade-from-stable-4.13-e2e-vsphere-zones-upgrade/1635080362419818496/artifacts/e2e-vsphere-zones-upgrade/gather-extra/artifacts/clusterversion.json | jq -r '.items[].status.history[] | .startedTime + " " + .completionTime + " " + .state + " " + .version'
2023-03-13T01:33:54Z 2023-03-13T02:36:49Z Completed 4.14.0-0.nightly-2023-03-08-194110
2023-03-13T01:00:25Z 2023-03-13T01:21:09Z Completed 4.13.0-ec.4
```

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/37187/rehearse-37187-periodic-ci-openshift-release-master-nightly-4.14-upgrade-from-stable-4.13-e2e-vsphere-zones-upgrade/1635080362419818496

**Pull request merged**
