### PR TITLE
Include 4.11 periodic job for Kuryr with NFV

### PR DESCRIPTION
**Pull request by MaysaMacedo**

### CODE REVIEW

**Comment by MaysaMacedo** [comment]
Successful run with Kuryr https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/28523/rehearse-28523-periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.11-e2e-openstack-nfv-intel-kuryr/1524711430979325952

**Comment by EmilienM** [comment]
/lgtm
/hold

Maysa, please feel free to hold cancel when you want.

**Pull request merged**
