### PR TITLE
Update TF provider AWS credential file to meet QE's convention

### PR DESCRIPTION
**Pull request by yunjiang29**

### CODE REVIEW

**Comment by yunjiang29** [comment]
@xueli181114 PTAL

**Review by radtriste — APPROVED** [review]

**Comment by radtriste** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-classic-main-rosa-classic-public-with-shared-vpc

**Comment by yunjiang29** [comment]
test get passed https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/49412/rehearse-49412-pull-ci-terraform-redhat-terraform-rhcs-rosa-classic-main-rosa-classic-public-with-shared-vpc/1773261905956179968

**Comment by yunjiang29** [comment]
test get passed https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/49412/rehearse-49412-pull-ci-terraform-redhat-terraform-rhcs-rosa-classic-main-rosa-classic-public-with-shared-vpc/1773261905956179968

**Pull request merged**
