### PR TITLE
Fix Azure Disk CSI Driver (TP) jobs

### PR DESCRIPTION
**Pull request by bertinatto**
The driver/operator has graduated to GA recently, so we removed the TP feature set from the workflow. To test the 4.9 driver we
inline the workflow in the jobs. For 4.8 we completely disable the job because the TP feature set is causing other components to fail.

CC @openshift/storage

### CODE REVIEW

**Comment by bertinatto** [comment]
/test pj-rehearse
I'd like to see at least one 4.8 job passing

**Comment by DennisPeriquet** [comment]
The changes look reasonable (same workflow but inlined with added steps).
If you can point me to a relevant rehearse job that passed, I can give it a lgtm.

**Comment by bertinatto** [comment]
> The changes look reasonable (same workflow but inlined with added steps). If you can point me to a relevant rehearse job that passed, I can give it a lgtm.

@DennisPeriquet can you take another look? Rehease jobs passed:
1. https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/27772/rehearse-27772-pull-ci-openshift-azure-disk-csi-driver-operator-release-4.9-e2e-azure-csi/1518638427069747200
2. https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/27772/rehearse-27772-pull-ci-openshift-azure-disk-csi-driver-release-4.9-e2e-azure-csi/1518638427170410496
3. https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/27772/rehearse-27772-periodic-ci-openshift-release-master-nightly-4.9-e2e-azure-csi-migration/1518638427241713664

**Comment by DennisPeriquet** [comment]
thanks for the rehearse jobs @bertinatto.

/lgtm

**Comment by bertinatto** [comment]
/assign @dgoodwin 
for approval

**Comment by bertinatto** [comment]
> Could you clarify why there's no changes for 4.10 and 4.11?

@dgoodwin I should have clarified that this PR is a follow up to https://github.com/openshift/release/pull/22107.

In #22107 we removed the `TechPreviewNoUpgrade` feature set from the workflow, which fixed 4.10 onward. However, that broke 4.8 and 4.9 jobs because the CSI driver is TP in those versions, and in need the FS enabled there. So instead of creating a new workflow (with the FS) just for 4.9, we inlined the steps in the job.

**Comment by dgoodwin** [comment]
Thanks!
/approve

**Pull request merged**
