### PR TITLE
telco5g: SRIOV  Add CNF Baremetal tests job for 4.15 release branch

### PR DESCRIPTION
**Pull request by sshnaidm**
[CNF-11277](https://issues.redhat.com//browse/CNF-11277)

### CODE REVIEW

**Review by SchSeba — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by sshnaidm** [comment]
/pj-rehears pull-ci-openshift-sriov-network-operator-release-4.15-e2e-telco5g-cnftests

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-release-4.15-e2e-telco5g-cnftests

**Pull request merged**
