### PR TITLE
Add waiting for operators/roles ready before running tests (terraform-provider TR)

### PR DESCRIPTION
**Pull request by amalykhi**

### CODE REVIEW

**Comment by amalykhi** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-ocm-main-managed-oidc-config-e2e-presubmit

**Comment by amalykhi** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-managed-oidc-config-e2e-periodic

**Comment by amalykhi** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-managed-oidc-config-e2e-periodic

**Comment by amalykhi** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-managed-oidc-config-e2e-periodic

**Comment by amalykhi** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-managed-oidc-config-e2e-periodic

**Comment by amalykhi** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-managedx-oidc-config-e2e-periodic

**Comment by amalykhi** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-managed-oidc-config-e2e-periodic

**Comment by amalykhi** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-managed-oidc-config-e2e-periodic

**Comment by amalykhi** [comment]
/pj-rehearse  pull-ci-terraform-redhat-terraform-provider-rhcs-main-managed-oidc-config-e2e-presubmit

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-managed-oidc-config-e2e-periodic

**Comment by amalykhi** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-managed-oidc-config-e2e-periodic

**Comment by amalykhi** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-managed-oidc-config-e2e-periodic

**Comment by amalykhi** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-managed-oidc-config-e2e-periodic

**Comment by amalykhi** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-managed-oidc-config-e2e-periodic

**Comment by amalykhi** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-ocm-main-managed-oidc-config-e2e-presubmit

**Comment by amalykhi** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-managed-oidc-config-e2e-periodic

**Comment by amalykhi** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-managed-oidc-config-e2e-periodic

**Comment by amalykhi** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-managed-oidc-config-e2e-periodic

**Pull request closed without merging**
