### PR TITLE
Live migration: remove requirement for feature gate for 4.16 or above.

### PR DESCRIPTION
**Pull request by martinkennelly**
Live migration is GA for 4.16.
ref: https://github.com/openshift/api/pull/1747

/hold

### CODE REVIEW

**Comment by martinkennelly** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-release-4.16-e2e-aws-live-migration-sdn-ovn

Expecting it to fail until API is updated to define `conditions` in network status.

**Comment by martinkennelly** [comment]
cc @kyrtapz

**Comment by kyrtapz** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-e2e-aws-live-migration-sdn-ovn

**Comment by martinkennelly** [comment]
Forced pushed because i didnt include ovn-k jobs.

**Comment by martinkennelly** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-e2e-aws-live-migration-sdn-ovn

**Comment by kyrtapz** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-master-e2e-aws-live-migration-sdn-ovn

**Comment by martinkennelly** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-release-4.16-e2e-aws-live-migration-sdn-ovn

**Comment by kyrtapz** [comment]
CNO rehearsal passed.
/lgtm

**Comment by martinkennelly** [comment]
@dgoodwin Removing the need for a feature gate on 4.16 as Live Migration is now GA on 4.16. PTAL. I wasnt sure who has rights to approve the `openshift-priv` sub dirs. Same as `openshift`?

**Pull request merged**
