### PR TITLE
opendatahub-io/caikit-nlp: remove run_if_changed for image mirrors

### PR DESCRIPTION
**Pull request by dtrifiro**
remove run_if_changed

### CODE REVIEW

**Comment by Xaenalt** [comment]
/pj-rehearse pull-ci-opendatahub-io-caikit-nlp-main-fast-image-mirror

**Comment by Xaenalt** [comment]
Something's up here

/hold

**Comment by dtrifiro** [comment]
@Xaenalt

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/46327/rehearse-46327-pull-ci-opendatahub-io-caikit-nlp-main-pr-image-mirror/1731600487557369856

**Comment by Xaenalt** [comment]
Yeah, what on earth is going on, why doesn't pj-rehearse see our job

**Comment by Xaenalt** [comment]
/pj-rehearse branch-ci-opendatahub-io-caikit-nlp-main-fast-image-mirror

**Comment by dtrifiro** [comment]
/pj-rehearse branch-ci-opendatahub-io-caikit-nlp-main-fast-image-mirror

**Comment by dtrifiro** [comment]
/pj-rehearse  branch-ci-opendatahub-io-caikit-nlp-main-fast-image-mirror

**Comment by dtrifiro** [comment]
Decided to scrap this PR, not really required anymore

**Pull request closed without merging**
