### PR TITLE
[DNM] Use QE's install step

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Review by bradmwilliams — COMMENTED** [review]
/lgtm

**Review by bradmwilliams — COMMENTED** [review]
/lgtm

**Comment by stbenjam** [comment]
@bradmwilliams No need to lgtm, this is just some experiment

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-ovn-sts

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-ovn-sts

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-ovn-sts

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-ovn

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-ovn

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-ovn

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-ovn

**Comment by smg247** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-ovn

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-ovn

**Comment by stbenjam** [comment]
@smg247 Looks like ORIGINAL_RELEASE_IMAGE_LATEST is working https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/57711/rehearse-57711-periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-ovn/1847047305555873792

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-ovn

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-ovn

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-ovn

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-ovn
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-hypershift-ovn
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-ovn-no-external
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-hypershift-ovn-no-external

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-hypershift-ovn

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-ovn-no-external

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-hypershift-ovn-no-external

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-ovn-no-external

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-hypershift-ovn-no-external

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-ovn

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-hypershift-ovn

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-ovn-no-external

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-ovn

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-hypershift-ovn

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-hypershift-ovn

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-ovn

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-ovn

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-hypershift-ovn

**Pull request closed without merging**
