### PR TITLE
USHIFT-2912: Build MicroShift's multus & CNI plugins

### PR DESCRIPTION
**Pull request by pmtk**

### CODE REVIEW

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-containernetworking-plugins-master-images pull-ci-openshift-containernetworking-plugins-release-4.16-images	 pull-ci-openshift-multus-cni-master-images	pull-ci-openshift-multus-cni-release-4.16-images

**Review by s1061123 — APPROVED** [review]
/lgtm

**Pull request merged**
