### PR TITLE
Serverless: Remove old CI config for 1.4 - 1.29

### PR DESCRIPTION
**Pull request by mgencur**
Keep only supported versions 1.30, 1.31, main

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by mgencur** [comment]
Sorry, apparently CI automation merged [this commit](https://github.com/openshift/release/commit/c3e1fd6d5cbc12b5c4986b3ff250abb134a47344) and I've had to rebase this PR.

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
