### PR TITLE
Add ARO 4.15.27 upgrade to 4.15 nightly and e2e testing

### PR DESCRIPTION
**Pull request by mgahagan73**
Ths PR adds 4.15 post-upgrade e2e testing for ARO

### CODE REVIEW

**Comment by mgahagan73** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-4.15-upgrade-from-aro-4.15-aro-f7

**Comment by mgahagan73** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-4.15-upgrade-from-aro-4.15-aro-f7

**Comment by mgahagan73** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-4.15-upgrade-from-aro-4.15-aro-f7

**Comment by mgahagan73** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-4.15-upgrade-from-aro-4.15-aro-f7

**Comment by mgahagan73** [comment]
Added  --insecure-skip-tls-verify=true  which should  stop the intermittent failures I've seen during rehersal jobs due to self-signed tls certs., otherwise this is just like the previous 4.12-4.14 upgrade/e2e jobs.

**Comment by kuiwang02** [comment]
@mgahagan73 it is regression job, please contact with qe-productivity team to approve it.
cc @liangxia

**Pull request merged**
