### PR TITLE
mco: add config to run ci test against MCO's mcbs branch

### PR DESCRIPTION
**Pull request by sinnykumari**
mcbs branch https://github.com/openshift/machine-config-operator/tree/mcbs
will be used for initial development and testing of features around
mcbs.

Creating a separate ci config should allow us to control tests that
we would want to run into this branch.

### CODE REVIEW

**Comment by sinnykumari** [comment]
Need approval for changes made in core-services/prow/02_config
/assign @wking

**Review by cgwalters — APPROVED** [review]
/lgtm

**Review by stevekuznetsov — APPROVED** [review]

**Comment by sinnykumari** [comment]
Need lgtm again. 
Had to push changes to get  generated-config green, started failing before final merge which could be due to some recent change in ci configs.

**Review by cgwalters — APPROVED** [review]
/lgtm

**Pull request merged**
