### PR TITLE
config-updater: maintain all templates on vsphere cluster

### PR DESCRIPTION
**Pull request by petr-muller**
If it's a template and it's on build02, it should be on vsphere too.

### CODE REVIEW

**Comment by petr-muller** [comment]
`fatal: unable to access 'https://github.com/openshift/release.git/': Could not resolve host: github.com` 

Not bad

**Comment by petr-muller** [comment]
ping @droslean @hongkailiu

**Review by stevekuznetsov — APPROVED** [review]

**Pull request merged**
