### PR TITLE
Build the sctp tester image as part of the CI job

### PR DESCRIPTION
**Pull request by fedepaol**
Also, force tests to use it.

### CODE REVIEW

**Comment by fedepaol** [comment]
/retest ci/rehearse/openshift-kni/cnf-features-deploy/master/e2e-gcp-ovn

Strange thing e2e-gcp worked

**Comment by fedepaol** [comment]
> /retest ci/rehearse/openshift-kni/cnf-features-deploy/master/e2e-gcp-ovn
> 
> Strange thing e2e-gcp worked

Just realized e2e-gcp is the only one working because it's the only one I fixed :-)

**Comment by slintes** [comment]
nice :)
failed tests are about origin test only (which is expected to fail yet)

/lgtm

**Pull request merged**
