### PR TITLE
always use --keep-manifest-list option when mirroring images

### PR DESCRIPTION
**Pull request by jianlinliu**
manifest list are being used widely, e.g: pre-merged builds, so always enabled  --keep-manifest-list option when mirroring images

### CODE REVIEW

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.11-amd64-stable-vsphere-ipi-disconnected-f28

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-stable-4.13-upgrade-from-stable-4.12-azure-ipi-disconnected-fullyprivate-f28

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-quay-quay-tests-master-omr-ocp413-quay-omr-tests-omr-ocp413-disconnected

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.11-amd64-stable-vsphere-ipi-disconnected-f28

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.11-amd64-stable-vsphere-ipi-disconnected-f28

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.11-amd64-stable-vsphere-ipi-disconnected-f28

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.11-amd64-stable-vsphere-ipi-disconnected-f28

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.11-amd64-stable-vsphere-ipi-disconnected-f28

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.11-amd64-stable-vsphere-ipi-disconnected-f28

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.11-amd64-stable-vsphere-ipi-disconnected-f28

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.11-amd64-stable-vsphere-ipi-disconnected-f28

**Comment by jianlinliu** [comment]
ci job logs:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/46701/rehearse-46701-periodic-ci-quay-quay-tests-master-omr-ocp413-quay-omr-tests-omr-ocp413-disconnected/1734794052395601920

https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/46701/rehearse-46701-periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-stable-4.13-upgrade-from-stable-4.12-azure-ipi-disconnected-fullyprivate-f28/1734786073738874880

cc @yunjiang29 @shellyyang1989 @sgaoshang @jinyunma to review.

**Comment by shellyyang1989** [comment]
The upgrade change looks good to me.

**Pull request merged**
