### PR TITLE
Update make e2e target

### PR DESCRIPTION
**Pull request by fjglira**

### CODE REVIEW

**Review by jwendell — APPROVED** [review]

**Review by jwendell — CHANGES_REQUESTED** [review]
actually I think you need to change the job names too?

**Comment by fjglira** [comment]
I just added: `/pj-rehearse ack` because this need to be merged first to be able to run the job properly again after this change: https://github.com/maistra/istio-operator/pull/1709

**Comment by fjglira** [comment]
> actually I think you need to change the job names too?

Job names updated

**Review by jwendell — APPROVED** [review]

**Pull request merged**
