### PR TITLE
Add pre-commit job for placement-operator

### PR DESCRIPTION
**Pull request by gibizer**
The pre-commit config is introduced in
https://github.com/openstack-k8s-operators/placement-operator/pull/102

### CODE REVIEW

**Comment by gibizer** [comment]
/retest 
https://github.com/openstack-k8s-operators/placement-operator/pull/102 has been merged now.

**Comment by gibizer** [comment]
pre-commit job worked as expected https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/35600/rehearse-35600-pull-ci-openstack-k8s-operators-placement-operator-master-precommit-check/1617479616560107520/artifacts/test/build-log.txt

**Review by SeanMooney — APPROVED** [review]
ci results look good to me

**Pull request merged**
