### PR TITLE
SPLAT-1628: disable AWS platform external skips

### PR DESCRIPTION
**Pull request by rvanderp3**

### CODE REVIEW

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-external-aws-ccm

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-external-aws-ccm

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-external-aws-ccm

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-external-aws-ccm

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-external-aws-ccm

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-external-aws-ccm

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-external-aws-ccm

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-external-aws-ccm

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-external-aws-ccm

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-external-aws-ccm

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-external-aws-ccm periodic-ci-openshift-release-master-nightly-4.17-e2e-external-aws-ccm periodic-ci-openshift-release-master-nightly-4.16-e2e-external-aws-ccm periodic-ci-openshift-release-master-nightly-4.15-e2e-external-aws-ccm

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-external-aws-ccm periodic-ci-openshift-release-master-nightly-4.17-e2e-external-aws-ccm periodic-ci-openshift-release-master-nightly-4.16-e2e-external-aws-ccm

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-external-aws-ccm periodic-ci-openshift-release-master-nightly-4.17-e2e-external-aws-ccm

**Review by mtulio — APPROVED** [review]
/lgtm
/approve

We are seeing[1] 4.18 failing in HA Proxy too, but it seems to be unrelated. Let's monitor the 4.18 periodic while it is still an working branch.


[1] https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/56468/rehearse-56468-periodic-ci-openshift-release-master-nightly-4.18-e2e-external-aws-ccm/1841475366812651520

**Review by mtulio — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
