### PR TITLE
library-go: remove cpu requests and limits

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by petr-muller** [comment]
/test pj-reherse-testing

(we are planning to enable this job to run everywhere, so I'm dropping few manual triggers on stuff)

**Comment by smarterclayton** [comment]
You need to add CPU requests back.

**Comment by smarterclayton** [comment]
Every CI job should have a CPU request and memory request.  Almost all jobs should set a memory limit.  No job should set a CPU limit without talking to me or Seth (services on cluster not included, this is CI jobs only).

**Pull request merged**
