### PR TITLE
Use library-go make targets

### PR DESCRIPTION
**Pull request by jsafrane**
* "make test" runs unit tests.
* "make verify" checks go fmt, go vet and bindata correctness.

There is no "make sanity".

### CODE REVIEW

**Comment by rgolangh** [comment]
That's our upstream, ovirt project. Its okay, but I think we must have that for ci-operator/config/openshift/ovirt-csi-driver-operator`

**Comment by jsafrane** [comment]
Good catch, I updated `openshift/ovirt-csi-driver-operator` too.

**Pull request merged**
