### PR TITLE
GCP IPI XPN (non-techpreview in 4.13)

### PR DESCRIPTION
**Pull request by jianli-wei**
1. Copy from `cucushift-installer-rehearse-gcp-ipi-xpn-techpreview-provision` to `cucushift-installer-rehearse-gcp-ipi-xpn-provision`, by removing the references to steps `ipi-conf-feature-set`, `ipi-conf-gcp-create-firewall-rules`, and `ipi-conf-gcp-public-dns-zone` (along with the env variables), as they are not required/supported in 4.13.
2. Add workflow `cucushift-installer-rehearse-gcp-ipi-xpn`.

FYI 4.13 doesn't support `platform.gcp.{createFirewallRules,privateDNSZone,publicDNSZone}`
```
$ ./openshift-install version
./openshift-install 4.13.0-0.nightly-2023-01-27-165107
built from commit fca41376abe654a9124f0450727579bb85591438
release image registry.ci.openshift.org/ocp/release@sha256:29b1bc2026e843d7a2d50844f6f31aa0d7eeb0df540c7d9339589ad889eee529
release architecture amd64
$ ./openshift-install explain installconfig.platform.gcp
KIND:     InstallConfig
VERSION:  v1

RESOURCE: <object>
  GCP is the configuration used when installing on Google Cloud Platform.

FIELDS:
    computeSubnet <string>
      ComputeSubnet is an existing subnet where the compute nodes will be deployed. The value should be the name of the subnet.

    controlPlaneSubnet <string>
      ControlPlaneSubnet is an existing subnet where the control plane will be deployed. The value should be the name of the subnet.

    defaultMachinePlatform <object>
      DefaultMachinePlatform is the default configuration used when installing on GCP for machine pools which do not define their own platform configuration.

    licenses <[]string>
      Licenses is a list of licenses to apply to the compute images The value should a list of strings (https URLs only) representing the license keys. When set, this will cause the installer to copy the image into user's project. This option is incompatible with any mechanism that makes use of pre-built images such as the current env OPENSHIFT_INSTALL_OS_IMAGE_OVERRIDE

    network <string>
      Network specifies an existing VPC where the cluster should be created rather than provisioning a new one.

    networkProjectID <string>   
      NetworkProjectID specifies which project the network and subnets exist in when they are not in the main ProjectID.

    projectID <string> -required-
      ProjectID is the the project that will be used for the cluster.

    region <string> -required-  
      Region specifies the GCP region where the cluster will be created.

$ 
```
- [GCP: Remove the BYOH code](https://github.com/openshift/installer/pull/6771)
- [CORS-2382 Skip Firewall Creation based on Permissions](https://issues.redhat.com/browse/CORS-2382)

### CODE REVIEW

**Comment by jianli-wei** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.13-installer-rehearse-gcp

**Comment by jianlinliu** [comment]
>  by removing the references to steps ipi-conf-feature-set, ipi-conf-gcp-create-firewall-rules, and ipi-conf-gcp-public-dns-zone

Will installer create their own firewall rules and public dns zones in XPN VPC?

**Comment by jianli-wei** [comment]
> > by removing the references to steps ipi-conf-feature-set, ipi-conf-gcp-create-firewall-rules, and ipi-conf-gcp-public-dns-zone
> 
> Will installer create their own firewall rules and public dns zones in XPN VPC?

1. Whether creating firewall-rules or not would depend on whether the given GCP credential has the required permissions to create firewall-rules.
2. As for public DNS zone, the installer would choose the public DNS zone based on the given baseDomain (which should belong to the service project).
3. Installer would always create private DNS zone in the service project.

**Comment by jianlinliu** [comment]
@jianli-wei once this get merged, shall we replace `gcp-ipi-xpn-techpreview` with this one in ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml, right? If yes, can you help prepare a followup PR to replace it.

**Comment by jianli-wei** [comment]
> @jianli-wei once this get merged, shall we replace `gcp-ipi-xpn-techpreview` with this one in ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml, right? If yes, can you help prepare a followup PR to replace it.

Yes, let me do then. Thanks!

**Pull request merged**
