### PR TITLE
enable mce 2.4 conformance test

### PR DESCRIPTION
**Pull request by LiangquanLi930**

### CODE REVIEW

**Comment by sjenning** [comment]
/approve
/lgtm
holding rehearse ack until we see 4.14 conformance pass

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn-mce-conformance

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn-mce-conformance

**Pull request closed without merging**
