### PR TITLE
MGMT-14094: Cleanup dangling resources in OCI

### PR DESCRIPTION
**Pull request by adriengentil**
Create a new step and a new job to schedule cleanup in OCI.

### CODE REVIEW

**Comment by adriengentil** [comment]
/hold
wait for https://github.com/openshift/assisted-test-infra/pull/2253 to be merged first

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-oci-cleanup-cluster-profile-oci-assisted

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-oci-cleanup-cluster-profile-oci-assisted

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-oci-cleanup-cluster-profile-oci-assisted

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-oci-cleanup-cluster-profile-oci-assisted

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-oci-cleanup-cluster-profile-oci-assisted

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-oci-cleanup-cluster-profile-oci-assisted

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-oci-cleanup-cluster-profile-oci-assisted

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-oci-cleanup-cluster-profile-oci-assisted

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-oci-cleanup-cluster-profile-oci-assisted

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-oci-cleanup-cluster-profile-oci-assisted

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-oci-cleanup-cluster-profile-oci-assisted
/retest

**Review by osherdp — APPROVED** [review]

**Review by osherdp — APPROVED** [review]

**Pull request merged**
