### PR TITLE
crio: add perfscale job for testing

### PR DESCRIPTION
**Pull request by sohankunkerkar**

### CODE REVIEW

**Comment by sohankunkerkar** [comment]
/pj-rehearse pull-ci-cri-o-cri-o-main-ci-perfscale-control-plane-6nodes

**Comment by sohankunkerkar** [comment]
/pj-rehearse pull-ci-cri-o-cri-o-main-ci-perfscale-control-plane-6nodes

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-cri-o-cri-o-main-ci-perfscale-control-plane-6nodes

**Pull request merged**
