### PR TITLE
Adding Dynamic Storage class and Exit for PVC Scenario

### PR DESCRIPTION
**Pull request by shahsahil264**
@paigerube14 @chaitanyaenr

### CODE REVIEW

**Comment by shahsahil264** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416

**Comment by shahsahil264** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416

**Comment by shahsahil264** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416

**Comment by shahsahil264** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-416

**Review by chaitanyaenr — APPROVED** [review]
/lgtm

**Pull request merged**
