### PR TITLE
Allow MSFT to lgtm/approve PRs in openshift-azure

### PR DESCRIPTION
**Pull request by 0xmichalis**
@openshift/sig-azure still need the OWNERS files. 

/hold

### CODE REVIEW

**Comment by kargakis** [comment]
OWNERS added in https://github.com/openshift/openshift-azure/pull/178

**Comment by kargakis** [comment]
@stevekuznetsov broken config update?

**Comment by stevekuznetsov** [comment]
Cluster might have been down?

**Comment by stevekuznetsov** [comment]
Also why not add as collaborator?

**Comment by kargakis** [comment]
> Also why not add as collaborator?

Need to discuss with @jim-minter when he is back and @pweil-

**Comment by pweil-** [comment]
I think we can make a team if they're added as outside collaborators?  That would be good

**Comment by stevekuznetsov** [comment]
They just need to be repo collaborator, not needing to join the Org

**Pull request merged**
