### PR TITLE
kubevirt: ssp: Add config for branch "release-v0.20"

### PR DESCRIPTION
**Pull request by akrejcir**

### CODE REVIEW

**Comment by lyarwood** [comment]
/hold
@akrejcir when you're back online later in the week, looks like something is off with the branch permissions?

```
{"component":"check-gh-automation","file":"/go/src/github.com/openshift/ci-tools/cmd/check-gh-automation/main.go:218","func":"main.checkRepos","level":"error","msg":"Bot openshift-merge-robot does not have admin access in kubevirt/ssp-operator with branch protection enabled","severity":"error","time":"2024-05-01T08:58:11Z"}
```

**Comment by akrejcir** [comment]
Overriding, because we are using `kubevirt-bot` not `openshift-merge-robot` to merge our PRs.

/override ci/prow/check-gh-automation

**Pull request merged**
