### PR TITLE
Move baremetal 4.12 nightly jobs to build05

### PR DESCRIPTION
**Pull request by tdomnesc**
build05 can connect to the new internal hardware

https://issues.redhat.com/browse/METAL-331

### CODE REVIEW

**Comment by derekhiggins** [comment]
/lgtm
Looks good to me, pass rates look similar to the equinix version

**Review by mandre — COMMENTED** [review]
You may consider adding the BM team lead to https://github.com/openshift/release/blob/master/ci-operator/config/openshift/release/OWNERS.

/approve

**Comment by dtantsur** [comment]
hi @mandre, is this a standard practice? I don't think other team leads are there, the list is quite light.

**Comment by mandre** [comment]
> hi @mandre, is this a standard practice? I don't think other team leads are there, the list is quite light.

Good question. I believe that if your team manages a CI infra and you need to make frequent adjustment where jobs run, you should have someone from your team able to approve the changes. That's definitely the case for the OpenStack team.

**Pull request merged**
