### PR TITLE
Openjdk zstream 4.16 and firewatch updates

### PR DESCRIPTION
**Pull request by smatula**

### CODE REVIEW

**Comment by smatula** [comment]
pj-rehearse periodic-ci-rh-openjdk-jdkContainerOcpTests-main-openjdk-ocp4.16-lp-interop-openjdk-interop-ibmcloud periodic-ci-rh-openjdk-jdkContainerOcpTests-main-openjdk-ocp4.15-lp-interop-openjdk-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-rh-openjdk-jdkContainerOcpTests-main-openjdk-ocp4.16-lp-interop-openjdk-interop-ibmcloud periodic-ci-rh-openjdk-jdkContainerOcpTests-main-openjdk-ocp4.15-lp-interop-openjdk-interop-ibmcloud

**Review by Simranpal — APPROVED** [review]
/lgtm

**Pull request merged**
