### PR TITLE
ocm: Cut release-2.4 branch for console

### PR DESCRIPTION
**Pull request by KevinFCormier**
open-cluster-management/backlog#14309

### CODE REVIEW

**Comment by Randy424** [comment]
Looks good, I am assuming these test failures are related to the work itself (a few appeared in https://github.com/openshift/release/pull/20392 as well). I'm added a hold to prevent auto-merge, so @chrisahl can also take a look, just to be thorough. He has a deeper knowledge of automation testing than I.

**Review by Randy424 — APPROVED** [review]

**Review by chrisahl — APPROVED** [review]

**Comment by KevinFCormier** [comment]
@Randy424 Yes, the "rehearse" jobs are expected to fail.

**Pull request merged**
