### PR TITLE
HOSTEDCP-1569: hypershift: 4.17 periodics use HO and e2e from main

### PR DESCRIPTION
**Pull request by sjenning**

### CODE REVIEW

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-aws-ovn

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-aws-ovn

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.17-periodics-e2e-aws-ovn

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-aws-ovn

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-aws-ovn

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-aws-ovn

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.17-periodics-e2e-aws-ovn

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-aws-ovn

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-aws-ovn

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.17-periodics-e2e-aws-ovn

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-aws-ovn

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-aws-ovn

**Comment by sjenning** [comment]
need to wait for https://amd64.ocp.releases.ci.openshift.org/releasestream/4.16.0-0.ci/release/4.16.0-0.ci-2024-07-30-194438 to be promoted

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-aws-ovn

**Comment by fxierh** [comment]
I'm wondering if now is the right time to do the same for the 4.16 and 4.17 QE jobs :thinking:

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-aws-ovn

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-aws-ovn

**Pull request closed without merging**
