### PR TITLE
azure: use ARTIFACTS in o-a jobs

### PR DESCRIPTION
**Pull request by 0xmichalis**
https://github.com/openshift/release/pull/1369 was not enough

@bbguimaraes @openshift/sig-azure

### CODE REVIEW

**Comment by mjudeikis** [comment]
/lgtm 
What does this do? How it hooks up?

**Comment by kargakis** [comment]
I still don't understand how the ci-operator figures out which path to gather artifacts from inside the template but I am going to guess `ci-operator.openshift.io/wait-for-container-artifacts: teardown` and the emptyDir named `artifacts` matter.

**Comment by kargakis** [comment]
@mjudeikis there is an `ARTIFACTS` env variable that is set by Prow to `/logs/artifacts`. Not sure how the ci-operator gets the artifacts from the template though. cc @stevekuznetsov

**Comment by bbguimaraes** [comment]
https://github.com/openshift/ci-operator/blob/master/TEMPLATES.md#template-artifact-output

**Pull request merged**
