### PR TITLE
Reverting reverted "OCPQE-19493: Change facility to metro""

### PR DESCRIPTION
**Pull request by sgoveas**
Reverts openshift/release#50097

### CODE REVIEW

**Comment by derekhiggins** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-agent-master-edge-e2e-ai-operator-ztp

**Comment by derekhiggins** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-agent-master-edge-e2e-ai-operator-ztp

**Comment by sgoveas** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-agent-master-edge-e2e-ai-operator-ztp

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-baremetalds-ipi-ovn-ipv4-fips-f14

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-baremetalds-ipi-ovn-ipv4-fips-f14

**Comment by sgoveas** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-agent-master-edge-e2e-ai-operator-ztp

**Comment by sgoveas** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-agent-master-edge-e2e-ai-operator-ztp

**Comment by sgoveas** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-agent-master-edge-e2e-ai-operator-ztp

**Comment by eifrach** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-agent-master-edge-e2e-ai-operator-ztp

**Comment by eranco74** [comment]
The packet setup workes
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/50490/rehearse-50490-pull-ci-openshift-assisted-installer-agent-master-edge-e2e-ai-operator-ztp/1775437946082562048/artifacts/e2e-ai-operator-ztp/baremetalds-packet-setup/finished.json

**Pull request merged**
