### PR TITLE
openshift-psap: cleanups

### PR DESCRIPTION
**Pull request by kpouget**
Cleanup up unused/outdated CI configurations

### CODE REVIEW

**Comment by kpouget** [comment]
@bthurber I guess your team doesn't use `openshift-psap/special-resource-operator`, can you approve this PR
@sjug, you're the owner of openshift-psap/wireguard-worker, can you approve?
@dhellmann the image mirroring was updated with `make openshift-image-mirror-mappings`, can you approve?

thanskf for your help :)

**Comment by kpouget** [comment]
@dhellmann yes, `ci-artfacts*` and `wireguard-worker` aren't part of the OCP payload,

`openshift-psap/special-resource-operator` has been part of it, once (IIRC, but not sure it was from `openshift-psap`), so I'll let @bthurber confirm that it's gone from all the releases

**Comment by kpouget** [comment]
ping @bthurber @sjug

**Review by bthurber — APPROVED** [review]
ack...no longer used

**Comment by kpouget** [comment]
closing, I will open PRs for each of the repos to cleanup.

**Pull request closed without merging**
