### PR TITLE
Backport explicit lease to left jobs

### PR DESCRIPTION
**Pull request by sgaoshang**
backport the explicit lease for 4.12 and 4.15

### CODE REVIEW

**Comment by sgaoshang** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-stable-vsphere-ipi-proxy-fips-f14

**Comment by sgaoshang** [comment]
@jianlinliu pls help to review it, thanks. cc: @jinyunma @WenXinWei

**Comment by jianlinliu** [comment]
cc @liangxia to review.

**Pull request merged**
