### PR TITLE
[AMQ Streams] Update AMQ Streams version to 2.6.0 after release

### PR DESCRIPTION
**Pull request by see-quick**
When this PR will be merged [1], we can proceed with this one.

[1] - https://github.com/openshift/release/pull/46520

### CODE REVIEW

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.14-lp-interop-amq-streams-2-6 periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.14-lp-rosa-classic-amq-streams-2-6-rosa-aws periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.15-lp-interop-amq-streams-2-6

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.14-lp-interop-amq-streams-2-6 periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.14-lp-rosa-classic-amq-streams-2-6-rosa-aws periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.15-lp-interop-amq-streams-2-6

**Comment by dfrazzette** [comment]
LGTM.

**Comment by see-quick** [comment]
Hey guys, could anyone from you merge this? :) @davidvossel, @fabiand @vladikr

**Comment by see-quick** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.14-lp-interop-amq-streams-2-6 periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.14-lp-rosa-classic-amq-streams-2-6-rosa-aws periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.15-lp-interop-amq-streams-2-6

**Comment by see-quick** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.14-lp-interop-amq-streams-2-6 periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.14-lp-rosa-classic-amq-streams-2-6-rosa-aws periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.15-lp-interop-amq-streams-2-6

**Comment by see-quick** [comment]
@davidvossel I don't know if it was created most likely but it is one of the make commands which are needed for the update of files... :) the question is why is Kubevirt an empty file...? Anyway, it is not related to this PR and I have resolved the issue above... :)

**Pull request merged**
