### PR TITLE
Decommission 4.6 and 4.7 openshift-ci ClusterPools

### PR DESCRIPTION
**Pull request by 2uasimojo**
These releases are
[EOL](https://access.redhat.com/support/policy/updates/openshift#dates) and we removed all use of these pools via #35893.

**NOTE:** These pools will need to be [manually deleted](https://docs.ci.openshift.org/docs/how-tos/cluster-claim/#renaming-a-cluster-pool) from the CI cluster once this merges!

### CODE REVIEW

**Comment by smg247** [comment]
@2uasimojo I will remove the resources post-merge.

**Comment by smg247** [comment]
```
oc delete clusterpools/ci-ocp-4-6-amd64-aws-us-east-1 -n ci-cluster-pool --as system:admin
clusterpool.hive.openshift.io "ci-ocp-4-6-amd64-aws-us-east-1" deleted

oc delete clusterpools/ci-ocp-4-7-amd64-aws-us-east-1 -n ci-cluster-pool --as system:admin
clusterpool.hive.openshift.io "ci-ocp-4-7-amd64-aws-us-east-1" deleted
```

**Comment by jmguzik** [comment]
@2uasimojo have this been checked with @vikaslaad? I am asking as when I tried to decrease the execution frequency of jobs for 4.7 I received info we still need it, so I am wondering if that is not the same here. It was some time though, but still.

**Comment by 2uasimojo** [comment]
> @2uasimojo have this been checked with @vikaslaad? I am asking as when I tried to decrease the execution frequency of jobs for 4.7 I received info we still need it, so I am wondering if that is not the same here. It was some time though, but still.

@jmguzik what team would that be for? It was in the preceding PR (#35893) that we (re)moved existing 4.7 jobs. I sent an [email](https://groups.google.com/a/redhat.com/g/aos-devel/c/KeXDo4gAyv4) about it and the PR received approvals from OWNERS on each affected team.

**Pull request merged**
