### PR TITLE
kvm-device-plugin: Tolerate CI worker taint

### PR DESCRIPTION
**Pull request by cgwalters**
We want to schedule this pod onto CI workers.

xref https://github.com/openshift/os/issues/1028

### CODE REVIEW

**Review by travier — APPROVED** [review]

**Comment by cgwalters** [comment]
Hmm actually, we may also need `ci-prowjobs-worker`...

@bear-redhat do you know where these node taints are defined?

**Comment by cgwalters** [comment]
/hold
while I test some stuff

**Comment by cgwalters** [comment]
/hold cancel
OK I added all the tolerations I think we need

**Comment by travier** [comment]
Do we still need this one?

**Pull request closed without merging**
