### PR TITLE
Bug 2030776: e2e-operator always uses quay master images during presubmit tests

### PR DESCRIPTION
**Pull request by dobsonj**
https://bugzilla.redhat.com/show_bug.cgi?id=2030776
/cc @openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
> error: build error: error building at STEP "COPY manifests...stat: ["/manifests/4.10/*.yaml"]: no such file or directory

I wonder where that comes from.

**Comment by dobsonj** [comment]
> > error: build error: error building at STEP "COPY manifests...stat: ["/manifests/4.10/*.yaml"]: no such file or directory
> 
> I wonder where that comes from.

The error is from this line in bundle.Dockerfile:
https://github.com/openshift/local-storage-operator/blob/master/config/bundle.Dockerfile#L10
```
STEP 9/12: COPY manifests/4.10/*.yaml /manifests/
error: build error: error building at STEP "COPY manifests/4.10/*.yaml /manifests/": checking on sources under "/tmp/build/inputs": Rel: can't make  relative to /tmp/build/inputs; copier: stat: ["/manifests/4.10/*.yaml"]: no such file or directory
```
That line should work if run from within the `config` directory as defined here:
https://github.com/openshift/release/blob/785a3a720ed7744ab121db77dee5f42d03e30512/ci-operator/config/openshift/local-storage-operator/openshift-local-storage-operator-master.yaml#L44-L46
But for some reason it's treated as an absolute path here.

**Comment by dobsonj** [comment]
Oh! of course, these manifests were moved to 4.11 recently. But the bundle.Dockerfile was not updated.
https://github.com/openshift/local-storage-operator/tree/master/config/manifests/4.11

**Comment by dobsonj** [comment]
Filed https://github.com/openshift/local-storage-operator/pull/325

**Comment by dobsonj** [comment]
The latest e2e-operator run failed because:
```
Creating Subscription
Subscription name is "oo-vnfwj"
Waiting for installPlan to be created
Failed to find installPlan for subscription
```
From the subscription logs:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/26479/rehearse-26479-pull-ci-openshift-local-storage-operator-master-e2e-operator/1496864960184061952/artifacts/e2e-operator/optional-operators-subscribe/artifacts/sub-oo-vnfwj.yaml
```
  conditions:
  - lastTransitionTime: "2022-02-24T15:56:20Z"
    message: all available catalogsources are healthy
    reason: AllCatalogSourcesHealthy
    status: "False"
    type: CatalogSourcesUnhealthy
  - message: 'constraints not satisfiable: no operators found in channel 4.11 of package
      local-storage-operator in the catalog referenced by subscription oo-vnfwj, subscription
      oo-vnfwj exists'
    reason: ConstraintsNotSatisfiable
    status: "True"
    type: ResolutionFailed
```
Ah, the channel name "4.11" is wrong, should be "preview" instead based on the bundle.Dockerfile we're using for LSO:
```
$ grep channel config/bundle.Dockerfile 
LABEL operators.operatorframework.io.bundle.channels.v1=preview
LABEL operators.operatorframework.io.bundle.channel.default.v1=preview
```

**Comment by dobsonj** [comment]
This looks like it will work for release-4.10 too (pushed another commit), but not for older release branches.

**Comment by dobsonj** [comment]
> @dobsonj: all tests **passed!**

Yay, @openshift/storage this is ready for review

**Pull request merged**
