### PR TITLE
WIP Create prow cluster for release-4.14-amd64-nightly-aws-ipi-sdn

### PR DESCRIPTION
**Pull request by BhargaviGudi**

### CODE REVIEW

**Comment by BhargaviGudi** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.14-installer-rehearse-debug

**Comment by xiaojiey** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.14-installer-rehearse-debug

**Comment by BhargaviGudi** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.14-installer-rehearse-debug

**Pull request closed without merging**
