### PR TITLE
[release-1.29] Add Serverless operator CI config

### PR DESCRIPTION
**Pull request by dsimansk**
Per title adding the CI config & jobs for the "to be created" `release-1.29`.

The idea is to have it sitting in the queue with initial checks and run `/pj-rehearse` once the branch is created. Please let me know if it doesn't work like that. :)

/cc @ReToCode @skonto @matzew @pierDipi @mgencur

### CODE REVIEW

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve
/hold

**Comment by ReToCode** [comment]
/pj-rehearse pull-ci-openshift-knative-serverless-operator-release-1.29-4.8-operator-e2e-aws-ocp-48

/pj-rehearse pull-ci-openshift-knative-serverless-operator-release-1.29-4.12-upstream-e2e-mesh-aws-ocp-412

/pj-rehearse pull-ci-openshift-knative-serverless-operator-release-1.29-4.12-operator-e2e-aws-ocp-412

/pj-rehearse pull-ci-openshift-knative-serverless-operator-release-1.29-4.8-upgrade-tests-aws-ocp-48

/pj-rehearse pull-ci-openshift-knative-serverless-operator-release-1.29-4.8-upstream-e2e-aws-ocp-48

**Comment by dsimansk** [comment]
/pj-rehearse pull-ci-openshift-knative-serverless-operator-release-1.29-4.12-operator-e2e-aws-ocp-412
/pj-rehearse pull-ci-openshift-knative-serverless-operator-release-1.29-4.12-upstream-e2e-mesh-aws-ocp-412

**Review by ReToCode — APPROVED** [review]
/lgtm

**Pull request merged**
