### PR TITLE
Clean up few omitempty fields from jobs

### PR DESCRIPTION
**Pull request by petr-muller**
Needs to merge after https://github.com/openshift/ci-tools/pull/1010 merges

/cc @alvaroaleman

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/lgtm
(I would have abused the autoconfigbrancher for this)
/hold

**Comment by petr-muller** [comment]
> (I would have abused the autoconfigbrancher for this)

That's a really nice idea. Next time.

**Pull request closed without merging**
