### PR TITLE
link up ovn-kubernetes jobs

### PR DESCRIPTION
**Pull request by rajatchopra**
Signed-off-by: Rajat Chopra <rchopra@redhat.com>

@stevekuznetsov PTAL

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
We will need the robots to be invited into the `openvswitch` organization and given write access to that repository before we merge this.

**Comment by kargakis** [comment]
Also you probably need at least the trigger plugin enabled [here](https://github.com/openshift/release/blob/97d8497a6ca183f80ca52be0b70bc9ba7ff22cf2/cluster/ci/config/prow/plugins.yaml#L4).

**Comment by kargakis** [comment]
> Also you probably need at least the trigger plugin enabled here.

And similar to this stanza [here](https://github.com/openshift/release/blob/97d8497a6ca183f80ca52be0b70bc9ba7ff22cf2/cluster/ci/config/prow/plugins.yaml#L119-L120)

**Comment by kargakis** [comment]
> We will need the robots to be invited into the openvswitch organization and given write access to that repository before we merge this.

You will also need to setup the webhook so prow can receive events.

**Comment by kargakis** [comment]
The webhook requires a secret. Send me your PGP key at mkargaki@redhat.com and I can share the secret that you need to use.

**Comment by rajatchopra** [comment]
@kargakis This PR is ready to merge

**Comment by kargakis** [comment]
@rajatchopra I am not seeing any logs in prow related to this repo. Did you setup the webhook? Also, you will need to invite the bot as a collaborator in the repo so it can update commit statuses and add labels.

**Comment by stevekuznetsov** [comment]
Whoa no

**Comment by stevekuznetsov** [comment]
This PR is NOT ready to merge

**Comment by stevekuznetsov** [comment]
This commit specifically is bad -- use `git rebase`. https://github.com/openshift/release/pull/609/commits/207f4ade80154002b5188e3d8e1bc16156575cfd

**Comment by kargakis** [comment]
It doesn't seem that commit was applied.

**Pull request merged**
