### PR TITLE
hypershift: add openstack periodics

### PR DESCRIPTION
**Pull request by EmilienM**
Add periodics for OpenStack.

### CODE REVIEW

**Comment by EmilienM** [comment]
something's not working, I'll have to investigate.

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.17-periodics-e2e-openstack periodic-ci-openshift-hypershift-release-4.18-periodics-e2e-openstack

**Comment by sjenning** [comment]
/approve
/lgtm
feel free to rehearse ack when you are confident it is solid

**Review by sjenning — APPROVED** [review]

**Pull request merged**
