### PR TITLE
cri-o: update golang to 1.22

### PR DESCRIPTION
**Pull request by saschagrunert**
cc @haircommander @sohankunkerkar @kwilczynski @sairameshv 

Required for k8s 1.30 and PR's like https://github.com/cri-o/cri-o/pull/7815

### CODE REVIEW

**Review by sairameshv — APPROVED** [review]
/lgtm

**Comment by haircommander** [comment]
```
   * could not resolve inputs: could not determine inputs for step [input:root]: could not resolve base image from openshift/release:golang-1.22: imagestreamtags.image.openshift.io "release:golang-1.22" not found 
```

**Comment by kwilczynski** [comment]
> @haircommander @kwilczynski do we know who to reach out to for this kind of image? Kubernetes v1.30 (as well as our vendored dependencies) will depend on it as well.

@saschagrunert, I spoke with Joep about this recently. Things are in progress to build the dedicated image to use for builds.

Not sure how long it will take. I will chase this again.

**Comment by saschagrunert** [comment]
PTAL  @haircommander @sohankunkerkar @kwilczynski @sairameshv

**Comment by haircommander** [comment]
done in https://github.com/openshift/release/pull/51529

/close

**Pull request closed without merging**
