### PR TITLE
openshift-cincinnati-graph-data-master: run e2e test in a verbose mode

### PR DESCRIPTION
**Pull request by vrutkovs**
This should give us some more info and show if there are errors

### CODE REVIEW

**Comment by vrutkovs** [comment]
seems CI won't keep test log from successful runs :/

**Comment by steveeJ** [comment]
You could add an `&& exit 1` to the command of the job you're interested in debugging

**Comment by vrutkovs** [comment]
Tested this in https://github.com/openshift/cincinnati-graph-data/pull/489 instead to get real failures

**Pull request closed without merging**
