### PR TITLE
openshift-ansible inventories: update VPC

### PR DESCRIPTION
**Pull request by vrutkovs**
Ref: https://jira.coreos.com/browse/DPP-2495

Update VPC ID after the existing one was pruned

### CODE REVIEW

**Comment by mtnbikenc** [comment]
Failure
`The subnet ID 'subnet-f93770d6' does not exist`

**Comment by vrutkovs** [comment]
@dobbymoodge seems we need an updated Subnet ID here too

**Comment by vrutkovs** [comment]
atomic job failed as AMI for Fedora Atomic AMI has been removed - I'll fix that later

**Comment by vrutkovs** [comment]
some AWS hiccup? Public IP got assigned, but public DNS was empty

/test pj-rehearse

**Pull request merged**
