### PR TITLE
Add notification for 4.11 canary job

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@openshift/openshift-team-developer-productivity-platform ptal

**Comment by thrasher-redhat** [comment]
> @openshift/openshift-team-developer-productivity-platform ptal

Guessing this should be @openshift/openshift-team-developer-productivity-test-platform

**Comment by bparees** [comment]
> Guessing this should be https://github.com/orgs/openshift/teams/openshift-team-developer-productivity-test-platform

whoops, yes, thanks.

**Pull request merged**
