### PR TITLE
Changing iterations count for cluster-density v2

### PR DESCRIPTION
**Pull request by vishnuchalla**
As per our data cluster density v2 supports upto 250 iteration per node. Since we have 11 pods in each iteration of cluster density v2. Deciding 22 as iterations count. (i.e 250/11 ~= 22)

### CODE REVIEW

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aro-4.13-nightly-ocp-qe-perfscale-ci-tests-6nodes-aro

**Review by paigerube14 — APPROVED** [review]
/lgtm

**Pull request merged**
