### PR TITLE
HOSTEDCP-1685:  add dependencies to jobs for multiarch image use

### PR DESCRIPTION
**Pull request by Patryk-Stefanski**

### CODE REVIEW

**Comment by Patryk-Stefanski** [comment]
/pj-rehearse pull-ci-openshift-hypershift-release-4.16-e2e-aws

**Comment by sjenning** [comment]
failure is genuine

**Comment by Patryk-Stefanski** [comment]
/pj-rehearse pull-ci-openshift-hypershift-release-4.16-e2e-aws

**Pull request merged**
