### PR TITLE
service-ca-operator: run make verify

### PR DESCRIPTION
**Pull request by sallyom**
this can't merge until hack/verify-generated-bindata is fixed in release-4.1,2,3 branches (https://github.com/openshift/service-ca-operator/blob/release-4.2/hack/verify-generated-bindata.sh#L17) 

EDIT: I'm only adding `make verify` for `4.2, 4.3, master` _not_ `4.1` since that will require a PR to service-ca-operator:4.1 branch.  Will add in a follow-up.

### CODE REVIEW

**Comment by enj** [comment]
/approve

Looks reasonable once service-ca is fixed up.

**Comment by sallyom** [comment]
> /approve
> 
> Looks reasonable once service-ca is fixed up.

yes, we might want to pause and plug into library-go's make scripts

**Comment by sallyom** [comment]
@enj this will need another lgtm, since I had to remove the verify check in the release-4.1 job.  We'll need to fix the [hack script here](https://github.com/openshift/service-ca-operator/blob/release-4.1/hack/verify-generated-bindata.sh#L17) to get verify working for 4.1.  Can be a follow-up.

**Pull request merged**
