### PR TITLE
[OCPQE-22233]add azure debug for winc

### PR DESCRIPTION
**Pull request by weinliu**

### CODE REVIEW

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-azure-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-azure-ipi

**Comment by weinliu** [comment]
@liangxia @rrasouli could you help take a look? Then I can have 4.12-4.16 included

@rrasouli https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/53156/rehearse-53156-pull-ci-openshift-openshift-tests-private-master-debug-winc-azure-ipi/1801170552249913344
some cases failed, but they works on jenkins. Do we need to do other updates for prow?

**Comment by liangxia** [comment]
LGTM

**Comment by weinliu** [comment]
/test generated-config
--


<br class="Apple-interchange-newline">

**Comment by weinliu** [comment]
@sebsoto could you help take a look? Thanks

**Comment by weinliu** [comment]
@liangxia could you help take another look? Thanks

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-azure-ipi

**Pull request merged**
