### PR TITLE
Alert on failed mirroring jobs for build-cop

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @hongkailiu

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@hongkailiu how do we set up similar alerts (but to a unique channel for each one) for the other mirroring jobs?

**Comment by hongkailiu** [comment]
> @hongkailiu how do we set up similar alerts (but to a unique channel for each one) for the other mirroring jobs?

https://coreos.slack.com/archives/GB7NB0CUC/p1565982120436800

**Comment by hongkailiu** [comment]
Checked ... The alert is live.
https://prometheus-prow-monitoring.svc.ci.openshift.org/alerts

**Pull request merged**
