### PR TITLE
Enable FIPS on agent-e2e-compact-ipv4 workflow

### PR DESCRIPTION
**Pull request by zaneb**

### CODE REVIEW

**Comment by zaneb** [comment]
/pj-rehearse  ci/rehearse/openshift-metal3/dev-scripts/master/e2e-agent-compact-ipv4
/pj-rehearse ci/rehearse/openshift/assisted-installer-agent/release-4.12/e2e-agent-compact-ipv4
/pj-rehearse ci/rehearse/openshift/assisted-installer-agent/release-4.13/e2e-agent-compact-ipv4
/pj-rehearse ci/rehearse/openshift/assisted-installer-agent/release-4.14/e2e-agent-compact-ipv4

**Comment by zaneb** [comment]
/pj-rehearse pull-ci-openshift-metal3-dev-scripts-master-e2e-agent-compact-ipv4 /pj-rehearse pull-ci-openshift-assisted-installer-agent-release-4.12-e2e-agent-compact-ipv4 /pj-rehearse pull-ci-openshift-assisted-installer-agent-release-4.13-e2e-agent-compact-ipv4 /pj-rehearse pull-ci-openshift-assisted-installer-agent-release-4.14-e2e-agent-compact-ipv4

**Comment by zaneb** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-agent-compact-ipv4 pull-ci-openshift-installer-release-4.14-e2e-agent-compact-ipv4 pull-ci-openshift-installer-release-4.13-e2e-agent-compact-ipv4 pull-ci-openshift-installer-release-4.12-e2e-agent-compact-ipv4

**Comment by zaneb** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.12-e2e-agent-compact

**Comment by zaneb** [comment]
Previous failure on 4.13 was error building the image, so not related.
/pj-rehearse pull-ci-openshift-installer-release-4.13-e2e-agent-compact-ipv4

**Comment by zaneb** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.14-e2e-agent-compact-ipv4 pull-ci-openshift-installer-release-4.13-e2e-agent-compact-ipv4 pull-ci-openshift-installer-release-4.12-e2e-agent-compact

**Comment by zaneb** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.14-e2e-agent-compact-ipv4 pull-ci-openshift-installer-release-4.13-e2e-agent-compact-ipv4 pull-ci-openshift-installer-release-4.12-e2e-agent-compact

**Comment by zaneb** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.14-e2e-agent-compact-ipv4 pull-ci-openshift-installer-release-4.13-e2e-agent-compact-ipv4 pull-ci-openshift-installer-release-4.12-e2e-agent-compact

**Comment by zaneb** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.14-e2e-agent-compact-ipv4 pull-ci-openshift-installer-release-4.13-e2e-agent-compact-ipv4

**Comment by zaneb** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.14-e2e-agent-compact-ipv4

**Comment by zaneb** [comment]
4.14 seems to genuinely be broken - if the hosts are booting, we are not able to contact them over the network. However, I cannot reproduce this locally. And https://github.com/openshift/installer/pull/7565 shows that the job wasn't already broken, so it must be related to enabling FIPS.

**Comment by zaneb** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.14-e2e-agent-compact-ipv4

**Comment by zaneb** [comment]
4.14 should be fixed by openshift/machine-os-images#31 triggering a rebuild of the CI image.
/pj-rehearse pull-ci-openshift-installer-release-4.14-e2e-agent-compact-ipv4

**Comment by andfasano** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-agent-release-4.15-e2e-agent-compact-ipv4

**Pull request merged**
