### PR TITLE
Migrate release controller to core-services

### PR DESCRIPTION
**Pull request by stevekuznetsov**
/assign @openshift/openshift-team-developer-productivity-test-platform @smarterclayton @jupierce 
/hold

### CODE REVIEW

**Comment by smarterclayton** [comment]
Where did the other objects go?

**Comment by smarterclayton** [comment]
Ah, I see they were already moved

**Comment by smarterclayton** [comment]
Hrm, this is missing code changes made to the release json today.  4.3-CI changed

**Comment by stevekuznetsov** [comment]
Yeah, should not have allowed it to get stale

**Pull request merged**
