### PR TITLE
Add resource watch observer to all 412 and 413 nightly jobs

### PR DESCRIPTION
**Pull request by xueqzhan**
This PR adds resource watch observers to all 4.12 and 4.13 nightly jobs.

### CODE REVIEW

**Comment by xueqzhan** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-upgrade-ovn-ipv6

**Comment by deads2k** [comment]
/hold

in case ken wants to wait for more rehearsals.

**Comment by xueqzhan** [comment]
> /hold
> 
> in case ken wants to wait for more rehearsals.

Resource watch is enabled for the rehearsed job above. I don't intend to run another rehearse job. I am going to cancel hold

**Review by wking — COMMENTED** [review]
Enabling [this watcher][1] makes sense to me.

[1]: https://github.com/openshift/release/blob/7ab2f96909921cac4b66d01019badea167590ace/ci-operator/step-registry/observers/resource-watch/observers-resource-watch-observer.yaml

**Review by wking — APPROVED** [review]
/lgtm

**Pull request merged**
