### PR TITLE
Move kvm jobs away from b02

### PR DESCRIPTION
**Pull request by hongkailiu**
It seems the failover did not handle this case.

https://github.com/openshift/release/pull/31027

/cc @openshift/test-platform

### CODE REVIEW

**Comment by bear-redhat** [comment]
Fyi, I don't think these tests will run on b04 unless we also have Nested Virtualisation licence enabled on b04...

**Comment by hongkailiu** [comment]
/hold

We are moving back jobs to b02.
So we do not need this any more.

**Comment by bear-redhat** [comment]
@hongkailiu shall we close this one since b02 is back online?

**Pull request closed without merging**
