### PR TITLE
Add code ready workspaces test harness addon

### PR DESCRIPTION
**Pull request by flacatus**
In order to promote CodeReady Workspaces Add-on from staging OSD to production OSD we create Addon Test Harness for OSD E2E.We add our token to Origin CI Ref PR: https://github.com/openshift/release/pull/7904/files

Signed-off-by: flacatus <flacatus@redhat.com>

### CODE REVIEW

**Comment by flacatus** [comment]
cc @rhopp

**Comment by jeefy** [comment]
/test pj-rehearse

If this doesn't pass there may be something wrong with the env.

**Comment by meowfaceman** [comment]
/test pj-rehearse
Just would like to see this run as intended. The job looks fine.

**Comment by meowfaceman** [comment]
So, looks like there's a quota issue in the source account. I don't mind merging this as is -- the job seems fine, but we'll have to adjust as we see the job results come in.

**Pull request merged**
