### PR TITLE
openshift-cnv: custom src image for upgrade lanes

### PR DESCRIPTION
**Pull request by tiraboschi**
openshift-cnv: custom src image for upgrade lanes 

Run upgrade lanes with a custom src image
to be able to consume the expect tool there.

### CODE REVIEW

**Comment by tiraboschi** [comment]
4.9-e2e-upgrade is not working because 2.6.5 is not working on OCP 4.9 due to deprecated APIs.
4.7-e2e-deploy and 4.8-e2e-deploy are instead not interested by this change which is specific to the upgrade lanes.

**Comment by tiraboschi** [comment]
src-upgrade-ci got built as expected, see:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/20466/rehearse-20466-pull-ci-openshift-cnv-cnv-ci-master-4.8-images/1418505970866196480/artifacts/build-logs/src-upgrade-ci.log

**Review by orenc1 — APPROVED** [review]
/approve

**Pull request merged**
