### PR TITLE
OCPQE-18638: Get date to prepared for fully automated EC/z-stream release

### PR DESCRIPTION
**Pull request by liangxia**

### CODE REVIEW

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-release-tests-master-4.15-amd64-nightly-aws-ipi-fips-f1

**Comment by kuiwang02** [comment]
I have one comment:
the releast-test is public, so the log generated by golang step is in https://prow.ci.openshift.org/, not https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/.
I am not sure it is allowed because it means the log is also public.


if we define such test in openshit-tests-private component, it has no such problem. and I think it could be put in openshit-tests-private component technically.

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-automated-release-4.15-nightly-aws-ipi-fips-f1

**Pull request merged**
