### PR TITLE
enable release-note prow plugin for shipwright

### PR DESCRIPTION
**Pull request by gabemontero**
@adambkaplan @sbose78 

this is the first step in setting up a PR template with release note automation like there is in Tekton

there are a handful of repos under the auspices of openshift/release that are already using this prow plugin

### CODE REVIEW

**Comment by gabemontero** [comment]
ok gotta figure out 

`{"component":"unset","file":"prow/cmd/checkconfig/main.go:79","func":"main.reportWarning","level":"warning","msg":"the following orgs or repos enable the release-note plugin but do not forbid the do-not-merge/release-note-label-needed label for merging: [repo: shipwright-io/build]","severity":"warning","time":"2021-02-10T22:56:38Z"}`

**Comment by gabemontero** [comment]
> ok gotta figure out
> 
> `{"component":"unset","file":"prow/cmd/checkconfig/main.go:79","func":"main.reportWarning","level":"warning","msg":"the following orgs or repos enable the release-note plugin but do not forbid the do-not-merge/release-note-label-needed label for merging: [repo: shipwright-io/build]","severity":"warning","time":"2021-02-10T22:56:38Z"}`

think it has something to do with https://github.com/kubernetes/test-infra/blob/master/prow/cmd/checkconfig/main.go#L578

```
	if includeForbidden {
		configs = append(configs,
			plugin{name: hold.PluginName, label: labels.Hold, matcher: forbids},
			plugin{name: wip.PluginName, label: labels.WorkInProgress, matcher: forbids},
			plugin{name: bugzilla.PluginName, label: labels.InvalidBug, matcher: forbids},
			plugin{name: verifyowners.PluginName, label: labels.InvalidOwners, matcher: forbids},
			plugin{name: releasenote.PluginName, label: releasenote.ReleaseNoteLabelNeeded, matcher: forbids},
			plugin{name: cherrypickunapproved.PluginName, label: labels.CpUnapproved, matcher: forbids},
			plugin{name: blockade.PluginName, label: labels.BlockedPaths, matcher: forbids},
			plugin{name: needsrebase.PluginName, label: labels.NeedsRebase, external: true, matcher: forbids},
		)
	}
```

and something in the _lables.yaml or _config.yaml

**Comment by gabemontero** [comment]
ok we are all green now

/assign @adambkaplan 
/assign @sbose78 
/assign @droslean

**Review by droslean — APPROVED** [review]

**Comment by sbose78** [comment]
Thanks Gabe!

**Pull request merged**
