### PR TITLE
Add Interop Job  For OCP-4.15

### PR DESCRIPTION
**Pull request by rabin-io**

### CODE REVIEW

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.15-ocp-cnv-odf-4.15-cnv-odf-tests-aws-upi-ocp415

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.15-ocp-cnv-odf-4.15-cnv-odf-tests-aws-upi-ocp415

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.15-ocp-cnv-odf-4.15-cnv-odf-tests-aws-upi-ocp415

**Review by myakove — APPROVED** [review]

**Pull request merged**
