### PR TITLE
Use cluster profile for GPU operator pre-/post-submit

### PR DESCRIPTION
**Pull request by empovit**

### CODE REVIEW

**Comment by empovit** [comment]
/pj-rehearse pull-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.14-nvidia-gpu-operator-e2e
/pj-rehearse pull-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-images
/pj-rehearse pull-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-lint

**Comment by empovit** [comment]
/pj-rehearse pull-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-lint

**Review by fabiendupont — APPROVED** [review]
/lgtm

**Pull request merged**
