### PR TITLE
MGMT-18911: gather logs from ibi-host in ibio e2e test

### PR DESCRIPTION
**Pull request by giladravid16**

### CODE REVIEW

**Comment by giladravid16** [comment]
/pj-rehearse pull-ci-openshift-image-based-install-operator-main-e2e-ibio

**Comment by giladravid16** [comment]
/pj-rehearse pull-ci-openshift-image-based-install-operator-backplane-2.7-e2e-ibio

**Comment by giladravid16** [comment]
/pj-rehearse pull-ci-openshift-image-based-install-operator-main-e2e-ibio pull-ci-openshift-image-based-install-operator-backplane-2.7-e2e-ibio

**Comment by giladravid16** [comment]
/pj-rehearse pull-ci-openshift-image-based-install-operator-main-e2e-ibio pull-ci-openshift-image-based-install-operator-backplane-2.7-e2e-ibio

**Comment by giladravid16** [comment]
/pj-rehearse pull-ci-openshift-image-based-install-operator-main-e2e-ibio

**Comment by giladravid16** [comment]
/pj-rehearse pull-ci-openshift-image-based-install-operator-main-e2e-ibio

**Comment by giladravid16** [comment]
/pj-rehearse pull-ci-openshift-image-based-install-operator-main-e2e-ibio

**Comment by giladravid16** [comment]
/pj-rehearse pull-ci-openshift-image-based-install-operator-main-e2e-ibio pull-ci-openshift-image-based-install-operator-backplane-2.7-e2e-ibio

**Comment by giladravid16** [comment]
/pj-rehearse pull-ci-openshift-image-based-install-operator-main-e2e-ibio

**Comment by eranco74** [comment]
Looks good!
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/56747/rehearse-56747-pull-ci-openshift-image-based-install-operator-main-e2e-ibio/1836074986935160832/artifacts/e2e-ibio/image-based-install-operator-gather/artifacts/root/ibio-gather/manifests/dataimage.yaml


https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/56747/rehearse-56747-pull-ci-openshift-image-based-install-operator-main-e2e-ibio/1836074986935160832/artifacts/e2e-ibio/image-based-install-operator-gather/artifacts/root/ibio-gather/ibi-host/

/lgtm
/approve

**Pull request merged**
