### PR TITLE
Add aws-rhel profile from QE to cluster-bot workflow-launch

### PR DESCRIPTION
**Pull request by Phaow**
## Add aws-rhel profile from QE to cluster-bot workflow-launch

- Add aws-rhel profile from QE to cluster-bot workflow-launch.
- Make debug the CI failure on RHEL nodes profiles easier.

```
# Lack of `aws-rhel profile` in cluster-bot's workflow-launch

Penghao Wang 17:53
workflow-launch cucushift-installer-rehearse-aws-ipi-proxy-sdn-workers-rhel8 4.12

Cluster Bot APP  17:53
Workflow cucushift-installer-rehearse-aws-ipi-proxy-sdn-workers-rhel8 not in workflow list. Please add cucushift-installer-rehearse-aws-ipi-proxy-sdn-workers-rhel8 to the workflows list before retrying this command
```

### CODE REVIEW

**Comment by Phaow** [comment]
@liangxia @jhou1 @jianlinliu Could you please help to take a look when you get a chance? Many thanks!

**Review by bradmwilliams — APPROVED** [review]

**Comment by bradmwilliams** [comment]
@Phaow You probably just need to rebase your changes against the latest/greatest code.

**Comment by Phaow** [comment]
> workflow-launch cucushift-installer-rehearse-aws-ipi-proxy-sdn-workers-rhel8 4.12

Hi @bradmwilliams , thanks for reminding! Seems it has no conflict and gets merged.

**Pull request merged**
