### PR TITLE
jobs: propagate gcs secret

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/cc @alvaroaleman @petr-muller

### CODE REVIEW

**Comment by petr-muller** [comment]
/lgtm
/hold

Should merge fine after ci-tools builds new image

**Comment by stevekuznetsov** [comment]
/hold cancel 
rebased

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
