### PR TITLE
Update operator installation from iib

### PR DESCRIPTION
**Pull request by rnetser**

### CODE REVIEW

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-rhoai-operator-interop-v4.14-IIB-smoke-rosa-rhoai-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-rhoai-operator-interop-v4.14-IIB-smoke-rosa-rhoai-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-rhoai-operator-interop-v4.14-IIB-smoke-rosa-rhoai-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-rhoai-operator-interop-v4.14-IIB-smoke-rosa-rhoai-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-rhoai-operator-interop-v4.14-IIB-smoke-rosa-rhoai-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-rhoai-operator-interop-v4.14-IIB-smoke-rosa-rhoai-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-rhoai-operator-interop-v4.14-IIB-smoke-rosa-rhoai-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-rhoai-operator-interop-v4.14-IIB-smoke-rosa-rhoai-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-rhoai-operator-interop-v4.14-IIB-smoke-rosa-rhoai-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-rhoai-operator-interop-v4.14-IIB-smoke-rosa-rhoai-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-rhoai-operator-interop-v4.14-IIB-smoke-rosa-rhoai-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-rhoai-operator-interop-v4.14-IIB-smoke-rosa-rhoai-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-rhoai-operator-interop-v4.14-IIB-smoke-rosa-rhoai-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-rhoai-operator-interop-v4.14-IIB-smoke-rosa-rhoai-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-rhoai-operator-interop-v4.14-IIB-smoke-rosa-rhoai-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-rhoai-operator-interop-v4.14-IIB-smoke-rosa-rhoai-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-rhoai-operator-interop-v4.14-IIB-smoke-rosa-rhoai-baseline-fips

**Comment by rnetser** [comment]
@myakove

**Review by myakove — APPROVED** [review]

**Pull request merged**
