### PR TITLE
NO-ISSUE: Fix assisted vsphere workflow

### PR DESCRIPTION
**Pull request by adriengentil**
- Use common step to get vsphere credentials
- Update centos 8 stream ISO

### CODE REVIEW

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-periodic

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-periodic

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-periodic

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-periodic

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-periodic

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-periodic

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-periodic

**Review by eifrach — APPROVED** [review]

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-periodic

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-periodic

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-periodic

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-periodic

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-periodic

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-periodic

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-periodic

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-periodic

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-periodic

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-periodic

**Comment by adriengentil** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-periodic

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted-4-12 pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted-4-13 pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted-umn pull-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted pull-ci-openshift-assisted-test-infra-release-ocm-2.9-e2e-vsphere-assisted-kube-api pull-ci-openshift-assisted-test-infra-release-ocm-2.7-e2e-vsphere-assisted-kube-api pull-ci-openshift-assisted-test-infra-release-ocm-2.8-e2e-vsphere-assisted-kube-api

**Comment by adriengentil** [comment]
/cc @eifrach @gamli75 @rccrdpccl 
jobs are still flaky due to an issue with user permissions in vsphere, I'm following up this issue. In the meantime, it would be great to merge this PR.

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-periodic periodic-ci-openshift-assisted-service-edge-master-e2e-vsphere-assisted-periodic

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted-4-12 pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted-4-13 pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted-umn pull-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted pull-ci-openshift-assisted-test-infra-release-ocm-2.9-e2e-vsphere-assisted-kube-api pull-ci-openshift-assisted-test-infra-release-ocm-2.7-e2e-vsphere-assisted-kube-api pull-ci-openshift-assisted-test-infra-release-ocm-2.8-e2e-vsphere-assisted-kube-api

**Review by gamli75 — APPROVED** [review]

**Pull request merged**
