### PR TITLE
LOG-4716: Add CI for logging-fluentd 5.8, remove main CI

### PR DESCRIPTION
**Pull request by jcantrill**
https://issues.redhat.com/browse/LOG-4716

cc @cahartma @xperimental

### CODE REVIEW

**Comment by xperimental** [comment]
/pj-rehearse pull-ci-ViaQ-logging-fluentd-v1.16.x-clo-functional

**Comment by jcantrill** [comment]
/pj-rehearse pull-ci-ViaQ-logging-fluentd-v1.16.x-clo-functional

**Pull request merged**
