### PR TITLE
Install unzip on SNC test instances

### PR DESCRIPTION
**Pull request by guillaumerose**
In order to uncompress Windows oc zip file in SNC test script, I need unzip in the test instance.

Related to https://github.com/code-ready/snc/pull/242

### CODE REVIEW

**Comment by cfergeau** [comment]
> In order to uncompress Windows oc zip file in SNC test script, I need unzip in the test instance.
> 
> Related to [code-ready/snc#242](https://github.com/code-ready/snc/pull/242)

This belongs in the commit log.

**Comment by guillaumerose** [comment]
added!

**Pull request merged**
