### PR TITLE
Add namespace argument to script for JJB apply

### PR DESCRIPTION
**Pull request by csrwng**
if NAMESPACE variable is set, it will use that instead of the current namespace

### CODE REVIEW

**Comment by csrwng** [comment]
@paradigm @stevekuznetsov

**Comment by stevekuznetsov** [comment]
Why did we decide this over the `kubeconfig` change inside of the pod? We'll need to add this sort of thing for every `make` target as well, right?

**Comment by csrwng** [comment]
@stevekuznetsov yes, so the issue is that inside the pod we're using magic and not a real kubeconfig. The oc client assembles a kubeconfig internally from the namespace and token secrets. So it's not as easy as copying an existing kubeconfig and pointing to it.

**Comment by stevekuznetsov** [comment]
Ah right the in-cluster config is crazy. ok. we need an explicit and hopefully minimally invasive way to inject a namespace not only into this script but into everything in the Makefile.

@kargakis i apologize for asking you to remove the namespace flag from the Makefile targets we had before :(

**Comment by stevekuznetsov** [comment]
@kargakis suggested we just deploy the pod in the correct namespace 

/close

**Pull request closed without merging**
