### PR TITLE
Switch fips e2e jobs to use day 1 support

### PR DESCRIPTION
**Pull request by mrunalp**
@AlexNPavel ptal

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
We want to verify manually that day-1 works with all the fixes before switching to day 1 in the CI.

**Comment by ashcrow** [comment]
pj-rehearse issue is this (which I'm not sure what it means tbh):
```
time="2019-11-08T00:49:56Z" level=error msg="Job failed" job=rehearse-5824-pull-ci-openshift-installer-master-e2e-metal name=13541e2b-01c0-11ea-a644-0a58ac10194f org=openshift pr=5824 repo=release state=failure type=presubmit
```

and the e2e-metal looks like an infra issue:
```
The facility sjc1 has no provisionable c1.small.x86 servers matching your criteria
```

**Comment by ashcrow** [comment]
e2e-metal:
```
error: blob upload unknown
```

**Comment by mrunalp** [comment]
I am not sure if we should be blocking on the metal issue. @stevekuznetsov do you know?

**Pull request merged**
