### PR TITLE
OCPQE-12048: add workflow:CPx86,NP arm

### PR DESCRIPTION
**Pull request by LiangquanLi930**
[OCPQE-12048](https://issues.redhat.com//browse/OCPQE-12048): CI Integration: control plane on X86, hosted cluster worker on Arm

### CODE REVIEW

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-ovn-hypershift-arm-nodepool-mgmt-p1-f7

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-aws-ipi-ovn-hypershift-arm-nodepool-mgmt-p1-f7

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-aws-ipi-ovn-hypershift-arm-nodepool-mgmt-p1-f7

**Comment by LiangquanLi930** [comment]
@liangxia Could you help to review this PR? thanks

**Comment by YuLi517** [comment]
@liangxia Could you help to review this PR? This will be used in OCP 4.14 release. After this PR, we will have continue work to do. Thanks

**Comment by liangxia** [comment]
Installation failed, the tests haven't started.
```
INFO[2023-05-23T15:20:51Z] Running step aws-ipi-ovn-hypershift-arm-nodepool-mgmt-p1-f7-create-hostedcluster. 
INFO[2023-05-23T15:21:00Z] Logs for container test in pod aws-ipi-ovn-hypershift-arm-nodepool-mgmt-p1-f7-create-hostedcluster: 
INFO[2023-05-23T15:21:00Z] + AWS_GUEST_INFRA_CREDENTIALS_FILE=/etc/hypershift-ci-jobs-awscreds/credentials
...
Error: unknown flag: --arch
unknown flag: --arch
INFO[2023-05-23T15:21:00Z] Step aws-ipi-ovn-hypershift-arm-nodepool-mgmt-p1-f7-create-hostedcluster failed after 8s. 
INFO[2023-05-23T15:21:00Z] Step phase pre failed after 36m7s.

**Comment by LiangquanLi930** [comment]
> Installation failed, the tests haven't started.
> 
> ```
> INFO[2023-05-23T15:20:51Z] Running step aws-ipi-ovn-hypershift-arm-nodepool-mgmt-p1-f7-create-hostedcluster. 
> INFO[2023-05-23T15:21:00Z] Logs for container test in pod aws-ipi-ovn-hypershift-arm-nodepool-mgmt-p1-f7-create-hostedcluster: 
> INFO[2023-05-23T15:21:00Z] + AWS_GUEST_INFRA_CREDENTIALS_FILE=/etc/hypershift-ci-jobs-awscreds/credentials
> ...
> Error: unknown flag: --arch
> unknown flag: --arch
> INFO[2023-05-23T15:21:00Z] Step aws-ipi-ovn-hypershift-arm-nodepool-mgmt-p1-f7-create-hostedcluster failed after 8s. 
> INFO[2023-05-23T15:21:00Z] Step phase pre failed after 36m7s.  
> ```
this job this 4.13, arm noodpool support version is 4.14, So then I made the change, here is new jobs
https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/39633/rehearse-39633-periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-aws-ipi-ovn-hypershift-arm-nodepool-mgmt-p1-f7/1661285247003660288

**Comment by LiangquanLi930** [comment]
> Installation failed, the tests haven't started.
> 
> ```
> INFO[2023-05-23T15:20:51Z] Running step aws-ipi-ovn-hypershift-arm-nodepool-mgmt-p1-f7-create-hostedcluster. 
> INFO[2023-05-23T15:21:00Z] Logs for container test in pod aws-ipi-ovn-hypershift-arm-nodepool-mgmt-p1-f7-create-hostedcluster: 
> INFO[2023-05-23T15:21:00Z] + AWS_GUEST_INFRA_CREDENTIALS_FILE=/etc/hypershift-ci-jobs-awscreds/credentials
> ...
> Error: unknown flag: --arch
> unknown flag: --arch
> INFO[2023-05-23T15:21:00Z] Step aws-ipi-ovn-hypershift-arm-nodepool-mgmt-p1-f7-create-hostedcluster failed after 8s. 
> INFO[2023-05-23T15:21:00Z] Step phase pre failed after 36m7s.  
> ```

@liangxia  this job this 4.13, arm noodpool support version is 4.14, So then I made the change, here is new jobs
https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/39633/rehearse-39633-periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-aws-ipi-ovn-hypershift-arm-nodepool-mgmt-p1-f7/1661285247003660288

**Comment by LiangquanLi930** [comment]
here is [job](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/39633/rehearse-39633-periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-aws-ipi-ovn-hypershift-arm-nodepool-mgmt-p1-f7/1661285247003660288) this job is 4.14, is successful^^
@liangxia Could you help to review this PR?

**Pull request merged**
