### PR TITLE
Enable NetworkManager trace logging for cucushift-installer-rehearse-azure-ipi-provision for OCPBUGS-5569

### PR DESCRIPTION
**Pull request by rbbratta**
DHCP timeout failures on Azure, enable NM trace logging to debug.

### CODE REVIEW

**Comment by rbbratta** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-nightly-azure-ipi-baselinecaps-v412-p2-f14

**Comment by rbbratta** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-nightly-azure-ipi-baselinecaps-v412-p2-f14

**Comment by rbbratta** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-nightly-azure-ipi-baselinecaps-v412-p2-f14

**Comment by smg247** [comment]
/uncc
You don't need my review for this one

**Comment by rbbratta** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-nightly-azure-ipi-baselinecaps-v412-p2-f14

**Comment by rbbratta** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-nightly-azure-ipi-baselinecaps-v412-p2-f14

**Comment by MayXuQQ** [comment]
/assign @yunjiang29  
thanks

**Comment by rbbratta** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-nightly-azure-ipi-baselinecaps-v412-p2-f14

**Comment by rbbratta** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-nightly-azure-ipi-baselinecaps-v412-p2-f14

**Comment by rbbratta** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-nightly-azure-ipi-baselinecaps-v412-p2-f14

**Comment by rbbratta** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-nightly-azure-ipi-baselinecaps-v412-p2-f14

**Comment by rbbratta** [comment]
/pj-rehearse periodicperiodic-ci-openshift-openshift-tests-private-release-4.12-arm64-nightly-azure-ipi-baselinecaps-v412-p3-f28-destructive

**Comment by rbbratta** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-nightly-azure-ipi-baselinecaps-v412-p3-f28-destructive

**Comment by MayXuQQ** [comment]
@rbbratta pj-rehearse max will cause the test quota exhausted

**Comment by rbbratta** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-nightly-azure-ipi-baselinecaps-v412-p2-f14

**Pull request merged**
