### PR TITLE
Bug 2007692: Remove old-rhcos CI jobs from periodics

### PR DESCRIPTION
**Pull request by stbenjam**
This removes the "old-rhcos" template job from periodics. Initial
investigation shows no one from the CoreOS team knows about this job,
it's using an old template style, and it's permafailing across many releases
for a long period of time.

### CODE REVIEW

**Comment by stbenjam** [comment]
/assign @petr-muller 

Would you mind having a look at this one? Thanks!

**Review by petr-muller — APPROVED** [review]

**Comment by petr-muller** [comment]
/lgtm cancel

Needs `make jobs` to fixup cluster assignment

**Comment by stbenjam** [comment]
> /lgtm cancel
> 
> Needs `make jobs` to fixup cluster assignment

Ah sorry, fixed.

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
