### PR TITLE
Samples: add OKD test configs for 4.6/4.7 branches

### PR DESCRIPTION
**Pull request by vrutkovs**
This ensures fixes to release-4.6 are promoted to OKD as well.

/cc @gabemontero

### CODE REVIEW

**Comment by gabemontero** [comment]
/approve

one more attempt at getting at least some rehearsal jobs passing

/retest

**Comment by gabemontero** [comment]
@vrutkovs do we expect any of these rehearsal jobs to succeed?

**Comment by vrutkovs** [comment]
master and 4.7 are failing with 
`error: unable to create a release: operator "cluster-samples-operator" contained an invalid image-references file: no input image tag named "baremetal-installer"` - seem we need to promote installer first.

/hold

4.6 should be fine

**Comment by gabemontero** [comment]
Hmm ... one of the 4.6 items failed waiting for OCP content to install:  

`error waiting for example imagestream jboss-fuse70-java-openshift to appear`

from https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/12686/rehearse-12686-pull-ci-openshift-cluster-samples-operator-release-4.6-okd-e2e-aws-operator/1318245509952966656

That would imply to me @vrutkovs that the `OKD` env change you put in at https://github.com/openshift/cluster-samples-operator/blob/release-4.6/test/e2e/cluster_samples_operator_test.go#L321-L324 is not firing 

WDYT?

**Comment by gabemontero** [comment]
See https://github.com/openshift/cluster-samples-operator/blob/release-4.6/assets/operator/ocp-x86_64/fis/imagestreams/jboss-fuse70-java-openshift-rhel7.json

**Comment by vrutkovs** [comment]
Updated `__okd*` files to run `make test-e2e-okd`

**Comment by gabemontero** [comment]
OK @vrutkovs the 4.6 okd's are coming up green again

/lgtm

feel free to unhold when the promotion you noted in https://github.com/openshift/release/pull/12686#issuecomment-712386773 occurs and you start seeing green rehearsals for 4.7 as well

**Comment by gabemontero** [comment]
ah ... some green 4.7's as well :-)

**Comment by vrutkovs** [comment]
Right, lets unhold this - 4.7 is now at least buildable, OKD specific tests are running.

/hold cancel

**Pull request merged**
