### PR TITLE
pf-status-relay images

### PR DESCRIPTION
**Pull request by mlguerrero12**
Add images sections
Configure image mirroring to quay.io

### CODE REVIEW

**Comment by mlguerrero12** [comment]
/pj-rehearse pull-ci-openshift-pf-status-relay-main-images pull-ci-openshift-pf-status-relay-main-unit

**Comment by mlguerrero12** [comment]
/pj-rehearse pull-ci-openshift-pf-status-relay-main-images pull-ci-openshift-pf-status-relay-main-unit

**Comment by mlguerrero12** [comment]
/pj-rehearse pull-ci-openshift-pf-status-relay-main-images pull-ci-openshift-pf-status-relay-main-unit

**Review by SchSeba — APPROVED** [review]
/lgtm
/approve

**Comment by mlguerrero12** [comment]
@bparees, could you please review this PR? Thanks!

**Comment by mlguerrero12** [comment]
hi @jupierce, could you please take a look at this?

**Pull request merged**
