### PR TITLE
qci-pruner: use logging to include timestamp in the output

### PR DESCRIPTION
**Pull request by hongkailiu**
Some test:

```
$ hack/qci_registry_pruner.py 
2024-06-14T16:23:10 - ERROR - OAuth token is required

$ QUAY_OAUTH_TOKEN=abc hack/qci_registry_pruner.py
2024-06-14T16:23:50 - ERROR - Error retrieving tags
Traceback (most recent call last):
  File "/Users/hongkliu/repo/openshift/release/hack/qci_registry_pruner.py", line 114, in run
    tags, has_more = fetch_tags('openshift/ci', token, page, like='_prune_')
...
2024-06-14T16:23:50 - INFO - Retrying in 1 minute..
...
```

/cc @openshift/test-platform @jupierce

### CODE REVIEW

**Review by droslean — APPROVED** [review]

**Comment by deepsm007** [comment]
Remove hold while watching out the rolling

**Comment by hongkailiu** [comment]
Seems working. 
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-openshift-release-qci-pruner/1802680716291477504

**Pull request merged**
