### PR TITLE
Promote check-payload image to registry.ci.openshift.org

### PR DESCRIPTION
**Pull request by liangxia**
To support running check-payload tests in Prow CI.

### CODE REVIEW

**Comment by jhou1** [comment]
Is there any context or pointer for a reviewer what check-payload is?

**Comment by liangxia** [comment]
> Is there any context or pointer for a reviewer what check-payload is?

@jhou1  https://github.com/openshift/check-payload/blob/main/README.md

**Comment by xiaojiey** [comment]
@kolyshkin @mrunalp @rphillips Could you please help to review? Thanks.

**Pull request merged**
