### PR TITLE
stackrox: switch some OCP clusters to GCP

### PR DESCRIPTION
**Pull request by gavin-stackrox**
Similar to #38351, switch to GCP clusters to avoid https://access.redhat.com/solutions/7007136.

/hold
/cc @msugakov @BradLugo 
/pj-rehearse

### CODE REVIEW

**Review by msugakov — APPROVED** [review]
/lgtm

**Comment by msugakov** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-4-12-fips-qa-e2e-tests pull-ci-stackrox-stackrox-master-ocp-4-10-operator-e2e-tests

**Comment by msugakov** [comment]
Well, fips succeeded on the previous run. I did not have to rerun it.

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/38352/rehearse-38352-pull-ci-stackrox-stackrox-master-ocp-4-10-operator-e2e-tests/1647140267473506304 failed strangely though.

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-4-12-qa-e2e-tests pull-ci-stackrox-stackrox-master-ocp-4-12-operator-e2e-tests pull-ci-stackrox-stackrox-master-ocp-4-10-qa-e2e-tests pull-ci-stackrox-stackrox-master-ocp-4-10-operator-e2e-tests

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-4-12-qa-e2e-tests pull-ci-stackrox-stackrox-master-ocp-4-12-operator-e2e-tests pull-ci-stackrox-stackrox-master-ocp-4-10-qa-e2e-tests pull-ci-stackrox-stackrox-master-ocp-4-10-operator-e2e-tests

**Comment by gavin-stackrox** [comment]
@BradLugo @msugakov I retooled this PR to _only_ change OCP 4.12 to GCP (for master, nightlies and 4.0) due to the current relative stability of ipi-aws. Can I get a new `/lgtm`?
/unhold

**Review by BradLugo — APPROVED** [review]
/lgtm

**Pull request merged**
