### PR TITLE
Create config for ACM scenario.

### PR DESCRIPTION
**Pull request by ascerra**

### CODE REVIEW

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by vboulos** [comment]
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by vboulos** [comment]
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by vboulos** [comment]
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.13-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.13-lp-interop-acm-interop-aws

**Pull request closed without merging**
