### PR TITLE
Add grafana dashboard for build-cop

### PR DESCRIPTION
**Pull request by hongkailiu**

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@hongkailiu can you link to the dashboard in the staging Grafana instance please, and let @smarterclayton @wking give feedback?

**Comment by hongkailiu** [comment]
> @hongkailiu can you link to the dashboard in the staging Grafana instance please, and let @smarterclayton @wking give feedback?

https://grafana-prow-monitoring-stage.svc.ci.openshift.org/d/prNtYgWWz/prow-dashboard?orgId=1&from=now-5m&to=now

**Comment by hongkailiu** [comment]
@smarterclayton 
Can you give me [more details](https://jira.coreos.com/browse/DPTP-404)? Maybe starting with `release qualification vs pull request`?

**Comment by wking** [comment]
> Maybe starting with `release qualification vs pull request`?

This is probably preflights, run against PRs, vs the promotion gates like [these][1].

[1]: https://testgrid.k8s.io/redhat-openshift-release-blocking#redhat-release-openshift-origin-installer-e2e-aws-4.1&sort-by-flakiness=

**Comment by smarterclayton** [comment]
release-* is release qualification
pull-ci-* is PRs

**Comment by hongkailiu** [comment]
> release-* is release qualification
> pull-ci-* is PRs

@smarterclayton Please check if that is what is in your mind.
https://grafana-prow-monitoring-stage.svc.ci.openshift.org/d/smRhLMWZk/build-cop-dashboard?orgId=1&from=now-2d&to=now

@wking 
I am goggling how to use testgrid. :)

**Comment by hongkailiu** [comment]
[DPTP-404](https://jira.coreos.com/browse/DPTP-404)

* Do we still need the first panel (basically what we are using now for build-cop report) with the rest of them present?

* release qualification vs pull request:
release-* vs pull-ci-*

    Q: no include e2e in the keyword?

* infrastructure failures vs other types

    Remark: Not failured information saved (by prow) for the noment.

* `job_name1` and `job_name2` are used only in the last panel for the case that none of the predefined panel satisfies your request, try the last one.

    Q: Do we need this?

Review [the current board](https://grafana-prow-monitoring-stage.svc.ci.openshift.org/d/6829209d59479d48073d09725ce807fa/build-cop-dashboard?orgId=1):

```
$ oc get deployment -n prow-monitoring-stage grafana -o yaml | grep ": GF_SECURITY_ADMIN_PASSWORD" -A1 -B2
```

@smarterclayton and @wking 
Please take a look.

**Comment by wking** [comment]
```console
$ oc get deployment -n prow-monitoring-stage grafana -o yaml | grep ": GF_SECURITY_ADMIN_PASSWORD" -A1 -B2
Error from server (Forbidden): deployments.extensions "grafana" is forbidden: User "wking" cannot get deployments.extensions in the namespace "prow-monitoring-stage": no RBAC policy matched
```

How do I go about requesting access?

**Comment by wking** [comment]
"Job States by Repo" seems unnecessary.  There's already a "select a repo" drop down at the top, and the build-cop is only interested in cross-team impact anyway (presumably individual teams are aware when they break CI in their own repo, because Prow will drop comments in their PRs).

**Pull request merged**
