### PR TITLE
telcov10n: add hcp cnf 4.18 config

### PR DESCRIPTION
**Pull request by rshemtov13**

### CODE REVIEW

**Comment by rshemtov13** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-hcp-cnf-4.18-e2e-telcov10n-functional-hcp-cnf-nightly

**Comment by rshemtov13** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-hcp-cnf-4.18-e2e-telcov10n-functional-hcp-cnf-nightly

**Comment by rshemtov13** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-hcp-cnf-4.18-e2e-telcov10n-functional-hcp-cnf-nightly

**Comment by rshemtov13** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-hcp-cnf-4.18-e2e-telcov10n-functional-hcp-cnf-nightly

**Comment by rshemtov13** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-hcp-cnf-4.18-e2e-telcov10n-functional-hcp-cnf-nightly

**Comment by rshemtov13** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-hcp-cnf-4.18-e2e-telcov10n-functional-hcp-cnf-nightly

**Comment by rshemtov13** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-hcp-cnf-4.18-e2e-telcov10n-functional-hcp-cnf-nightly

**Review by shaior — APPROVED** [review]
/lgtm

**Pull request merged**
