### PR TITLE
Remove GitHub IDPs on build0{1|2}

### PR DESCRIPTION
**Pull request by hongkailiu**
https://issues.redhat.com/browse/DPTP-2659

/cc @openshift/test-platform 

/hold

Wait for the timing.

### CODE REVIEW

**Comment by smg247** [comment]
There is also a section about github OAuth in `clusters/build-clusters/01_cluster/README.md

**Review by smg247 — APPROVED** [review]

**Comment by hongkailiu** [comment]
/hold cancel

waiting for the build ...

**Pull request merged**
