### PR TITLE
chore(stackrox): update build root for 4.4 to 0.3.67.1

### PR DESCRIPTION
**Pull request by gavin-stackrox**
go 1.21.9
/uncc

### CODE REVIEW

**Review by vikin91 — APPROVED** [review]

**Review by tommartensen — APPROVED** [review]
/lgtm

supersedes https://github.com/openshift/release/pull/51583

**Comment by tommartensen** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-release-4.4-eks-qa-e2e-tests

**Comment by tommartensen** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-release-4.4-eks-qa-e2e-tests

**Comment by tommartensen** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-release-4.4-ocp-4-15-fips-qa-e2e-tests

**Pull request merged**
