### PR TITLE
[PERFSCALE-2578] Perfscale Jobs on spot instances

### PR DESCRIPTION
**Pull request by krishvoor**
This PR will allow us to run Perfscale jobs on SPOT instances currently
the PR is scoped to run on Self-Managed AWS

And some quick formatting

### CODE REVIEW

**Comment by krishvoor** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-perfscale-aws-data-path-9nodes-periodic periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-nightly-x86-perfscale-aws-data-path-9nodes-periodic periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.13-nightly-x86-perfscale-aws-data-path-9nodes-periodic

**Comment by jtaleric** [comment]
@krishvoor do we have a sense of what sort of cost savings this will provide us? Given these clusters are short lived does really using spot help us?

**Comment by krishvoor** [comment]
> @krishvoor do we have a sense of what sort of cost savings this will provide us?
@jtaleric Yes we do ~63% savings for m5.xlarge per hour/per instance when compared with on-demand instances.

> Given these clusters are short lived does really using spot help us?
Yes, SPOT instances work very well for short-lived purposes like <24 node testing.

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.13-nightly-x86-perfscale-aws-control-plane-24nodes-periodic

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-nightly-x86-perfscale-aws-control-plane-24nodes-periodic periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-perfscale-aws-control-plane-24nodes-periodic

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.13-nightly-x86-control-plane-24nodes
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.13-nightly-x86-data-path-9nodes

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.13-nightly-x86-control-plane-24nodes
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.13-nightly-x86-data-path-9nodes

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.13-nightly-x86-data-path-9nodes

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.13-nightly-x86-control-plane-24nodes
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.13-nightly-x86-data-path-9nodes

**Comment by krishvoor** [comment]
In this test: the nodes went [down](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/45216/rehearse-45216-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.13-nightly-x86-data-path-9nodes/1721846355808227328) expected behaviour w/ SPOT

In this test the cluster was reliable - however, the timeout was observed during the waiting on the Infra pods:
```
Final check - Check if all pods to be settle
.Some pods fail to startup in limit times, please check ...
```

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.13-nightly-x86-control-plane-24nodes
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.13-nightly-x86-data-path-9nodes

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.13-nightly-x86-data-path-9nodes

**Comment by krishvoor** [comment]
This Occurrence of SPOT Instances on the Data Path [passed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/45216/rehearse-45216-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.13-nightly-x86-data-path-9nodes/1722576020323700736) 

This Occurrence of SPOT Instances on the Control Plane [passed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/45216/rehearse-45216-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.13-nightly-x86-control-plane-24nodes/1722555922720493568)

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.13-nightly-x86-control-plane-24nodes periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.13-nightly-x86-data-path-9nodes

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.13-nightly-x86-data-path-9nodes

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.13-nightly-x86-control-plane-24nodes periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.13-nightly-x86-data-path-9nodes

**Pull request closed without merging**
