### PR TITLE
4.9 gate releases on all jobs that gated 4.8

### PR DESCRIPTION
**Pull request by petr-muller**
Needs these PRs first:

- https://github.com/openshift/release/pull/19053
- https://github.com/openshift/release/pull/19054
- https://github.com/openshift/release/pull/19055

### CODE REVIEW

**Comment by stbenjam** [comment]
Should the 3rd PR in your list there be https://github.com/openshift/release/pull/19055? 19054 is there twice

**Comment by petr-muller** [comment]
Indeed. Thanks, fixed!

**Comment by petr-muller** [comment]
All good now. @bradmwilliams PTAL

**Review by bradmwilliams — APPROVED** [review]
/lgtm

**Comment by stbenjam** [comment]
/retitle 4.9 gate releases on all jobs that gated 4.8

**Pull request merged**
