### PR TITLE
Strip CPU limits from prowjob pods

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by smarterclayton** [comment]
@droslean

**Comment by droslean** [comment]
It seems that [validate-prow-job-semantics.py](https://github.com/openshift/release/blob/master/hack/validate-prow-job-semantics.py#L266) has to change also.

**Comment by smarterclayton** [comment]
We really need to move validation into ci-operator-prowgen.

**Comment by smarterclayton** [comment]
Fifth time's the charm

**Pull request merged**
