### PR TITLE
Authorize Openshift members to run tests in the descheduler

### PR DESCRIPTION
**Pull request by 0xmichalis**
@ingvagabund @stevekuznetsov

### CODE REVIEW

**Comment by ingvagabund** [comment]
Right, thanks for that. I don't have any /lgtm power so @stevekuznetsov if you please

**Comment by stevekuznetsov** [comment]
This means non-openshift memebers (those of the incubator) can't trigger, right? Why do we want that?

**Comment by kargakis** [comment]
Right, I was syncing the behavior with what's happening today in `kubernetes-incubator/crio`.

**Comment by kargakis** [comment]
So we may want to remove authorizing only Openshift members to start jobs in `cri-o`? Agreed we should authenticate `kubernetes-incubator` members.

**Pull request closed without merging**
