### PR TITLE
Replace ci/api-build01-ci-devcluster-openshift-com:6443 with build01

### PR DESCRIPTION
**Pull request by hongkailiu**
Require https://github.com/openshift/release/pull/8526/files
and BW uploading and secret resync.

Update:
BW uploading and re-syncing are done: it contains both contexts as suggested by https://github.com/openshift/release/pull/8539#issuecomment-618758164
(will remove the old one afterwards)

/cc @alvaroaleman @stevekuznetsov 

/hold

### CODE REVIEW

**Comment by hongkailiu** [comment]
```
grep -irn ci/api-build01-ci-devcluster-openshift-com:6443 .
./hack/ensure_job_cluster.py:14:BUILD01_CLUSTER = "ci/api-build01-ci-devcluster-openshift-com:6443"
```

The above will be gone after https://github.com/openshift/release/pull/8530 merges

**Comment by stevekuznetsov** [comment]
@hongkailiu to make this seamless, I suggest adding both contexts to the kubeconfig so we do not break anything in production now, then moving the config to use `build01`, then removing the old one

**Comment by hongkailiu** [comment]
> @hongkailiu to make this seamless, I suggest adding both contexts to the kubeconfig so we do not break anything in production now, then moving the config to use `build01`, then removing the old one

I remember you mentioned something like this in the grooming.
Only now realize what it is exactly.
On it.

**Comment by hongkailiu** [comment]
@alvaroaleman @stevekuznetsov

This one is ready.

**Comment by alvaroaleman** [comment]
/hold
has mergeconflicts

**Comment by hongkailiu** [comment]
Will regenerate

**Comment by hongkailiu** [comment]
@alvaroaleman 

Regenerated.

**Comment by hongkailiu** [comment]
/hold

need rebase again ...

**Comment by hongkailiu** [comment]
@alvaroaleman 

Let us do this before the next rebase is required.
It is hard to compete with 200 developers.

**Pull request merged**
