### PR TITLE
Add the first presubmit job on pull request checking for rosacli

### PR DESCRIPTION
**Pull request by yasun1**
[OCM-7692](https://issues.redhat.com//browse/OCM-7692)

### CODE REVIEW

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-rosa-master-e2e-presubmits-pr-rosa-hcp

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-rosa-master-e2e-presubmits-pr-rosa-hcp

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-rosa-master-e2e-presubmits-pr-rosa-hcp

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-rosa-master-e2e-presubmits-pr-rosa-hcp

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-rosa-master-e2e-presubmits-pr-rosa-hcp

**Comment by ciaranRoche** [comment]
@xueli181114 @yasun1 can we run into the same issue with these pre-submit jobs as we got on TF?

**Comment by yasun1** [comment]
@ciaranRoche Currently, this presubmits job is an on-demand job by setting `always_run: false`, besides, this job is not considered as a merging blocker by setting `optional: true`. The PR owner needs to trigger the job manually via `/pj-rehearse pull-ci-openshift-rosa-master-e2e-presubmits-pr-rosa-hcp`. The job will build the latest rosacli from the PR, create the ROSA HCP cluster, then run the Critical cases(if no test cases are updated). 

For your question, it is Yes to find out whether the changes in the pull request work.

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-rosa-master-e2e-presubmits-pr-rosa-hcp

**Comment by radtriste** [comment]
/pj-rehearse pull-ci-openshift-rosa-master-e2e-presubmits-pr-rosa-hcp

**Comment by radtriste** [comment]
@yasun1 
```
Summarizing 3 Failures:
  [FAIL] Edit IDP [It] can create/delete the HTPasswd IDPs - [id:49137] [day2, feature-idp, Critical]
  /go/src/github.com/openshift/rosa/tests/e2e/test_rosacli_idp.go:286
  [FAIL] Validate user [It] try to create cluster with invalid usernames, passwords or unsupported configurations - [id:66362] [day2, feature-user, Critical]
  /go/src/github.com/openshift/rosa/tests/e2e/test_rosacli_user.go:178
  [FAIL] Edit User [It] can grant/list/revoke users - [id:36128] [day2, feature-user, Critical]
  /go/src/github.com/openshift/rosa/tests/e2e/test_rosacli_user.go:54
```
All 3 also failing in nightly: https://redhat-internal.slack.com/archives/C0519LZH1RA/p1714690555853569

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-rosa-master-e2e-presubmits-pr-rosa-hcp

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-rosa-master-e2e-presubmits-pr-rosa-hcp

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-rosa-master-e2e-presubmits-pr-rosa-hcp

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-rosa-master-e2e-presubmits-pr-rosa-hcp

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-rosa-master-e2e-presubmits-pr-rosa-hcp

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-rosa-master-e2e-presubmits-pr-rosa-hcp

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-rosa-master-e2e-presubmits-pr-rosa-hcp

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-rosa-master-e2e-presubmits-pr-rosa-hcp

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-rosa-master-e2e-presubmits-pr-rosa-hcp

**Review by ciaranRoche — COMMENTED** [review]
/lgtm

**Pull request merged**
