### PR TITLE
OCPBUGS-30620: csi-operator: clean up legacy test manifests

### PR DESCRIPTION
**Pull request by dobsonj**
This updates the step-registry to use test manifests from the top-level directory of csi-operator, and builds the test images from a common Dockerfile.test. The intent is to eventually remove the legacy directory in this repo.

/hold
for https://github.com/openshift/csi-operator/pull/194

/cc @openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
/retitle OCPBUGS-30620: csi-operator: clean up legacy test manifests

**Comment by dobsonj** [comment]
/pj-rehearse pull-ci-openshift-origin-release-4.15-e2e-aws-csi pull-ci-openshift-origin-release-4.14-e2e-aws-csi

**Comment by dobsonj** [comment]
/pj-rehearse pull-ci-openshift-origin-release-4.15-e2e-aws-csi pull-ci-openshift-origin-release-4.14-e2e-aws-csi

**Pull request merged**
