### PR TITLE
switch to using new hcp tool for hypershift/kubevirt create/destroy

### PR DESCRIPTION
**Pull request by davidvossel**

### CODE REVIEW

**Comment by davidvossel** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-conformance periodic-ci-openshift-hypershift-release-4.13-periodics-e2e-kubevirt-conformance

**Comment by davidvossel** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-conformance periodic-ci-openshift-hypershift-release-4.13-periodics-e2e-kubevirt-conformance

**Comment by davidvossel** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-conformance periodic-ci-openshift-hypershift-release-4.13-periodics-e2e-kubevirt-conformance

**Comment by davidvossel** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-conformance periodic-ci-openshift-hypershift-release-4.13-periodics-e2e-kubevirt-conformance

**Comment by davidvossel** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-conformance periodic-ci-openshift-hypershift-release-4.13-periodics-e2e-kubevirt-conformance

**Comment by davidvossel** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-conformance periodic-ci-openshift-hypershift-release-4.13-periodics-e2e-kubevirt-conformance

**Comment by davidvossel** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-conformance

**Comment by davidvossel** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-conformance

**Review by nunnatsa — COMMENTED** [review]
/lgtm

**Pull request merged**
