### PR TITLE
Expand Periodic Test Coverage

### PR DESCRIPTION
**Pull request by awgreene**
OLM V0 has a fairly flakey e2e test suite. This commit will cause prow to upload the result of an e2e run for all OLM supported releases on a daily basis. Our team will be able to use this data to identify common failures per release and assign the fixes to members of our team. Once we've improved test stability, we'll be able to decrease the cadence at which these tests are ran.

### CODE REVIEW

**Comment by awgreene** [comment]
/hold
I'm going to hold this until @stevekuznetsov takes a look to verify the changes.

**Comment by awgreene** [comment]
Tests ran successfully.
/pj-rehearse ack

**Comment by stevekuznetsov** [comment]
/lgtm
/approve

You might need TP approvals

**Pull request merged**
