### PR TITLE
Add chained upgrades periodics

### PR DESCRIPTION
**Pull request by vrutkovs**
This PR updated openshift-e2e-test to support multiple update tests and adds periodic job to test 4.5 -> 4.6 -> 4.7 upgrade

### CODE REVIEW

**Comment by vrutkovs** [comment]
`error: Failed to acquire resource, current capacity: 0 free, 155 leased`

/retest

**Review by wking — APPROVED** [review]
```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/17732/rehearse-17732-periodic-ci-openshift-release-master-ci-4.8-upgrade-from-stable-4.6-e2e-aws-upgrade/1384416861386444800/artifacts/e2e-aws-upgrade/gather-extra/artifacts/clusterversion.json | jq -r '.items[].status.history[] | .startedTime + " " + (.completionTime // "-") + " " + .state + " " + .version'
2021-04-20T09:54:10Z 2021-04-20T11:11:59Z Completed 4.8.0-0.ci-2021-04-19-194640
2021-04-20T08:47:27Z 2021-04-20T09:53:55Z Completed 4.7.6
2021-04-20T08:13:36Z 2021-04-20T08:42:27Z Completed 4.6.23
```

/lgtm

**Comment by vrutkovs** [comment]
Adding TRT team for review

/cc @technical-release-team

**Comment by vrutkovs** [comment]
Adding TRT for review

/cc @wking @ravisantoshgudimetla @dmage @petr-muller

**Comment by dmage** [comment]
`periodic-ci-openshift-release-master-stable-4.7-upgrade-from-stable-4.5-e2e-aws-upgrade`

It is implied that it goes through stable-4.6, but don't we want to have the intermediate version explicitly in the job name? Once we are able to upgrade from N to N+2, will we have both paths (4.6->4.7->4.8 and 4.6->4.8) tested?

**Comment by vrutkovs** [comment]
Right, good idea, renaming those

**Pull request merged**
