### PR TITLE
OCPBUGS-25119: Add security scan for machine-api-provider-powervs repository

### PR DESCRIPTION
**Pull request by Karthik-K-N**

### CODE REVIEW

**Comment by Karthik-K-N** [comment]
/pj-rehearse pull-ci-openshift-machine-api-provider-powervs-main-security

**Review by djslavens — APPROVED** [review]
/lgtm

**Review by djslavens — APPROVED** [review]
/lgtm

**Comment by Karthik-K-N** [comment]
@mkumatag @djslavens could you please take a look, I just rebased the PR so lost the lgtm label.

**Review by djslavens — APPROVED** [review]
/lgtm

**Pull request merged**
