### PR TITLE
Bumping SRO CI to use OCP-4.10.

### PR DESCRIPTION
**Pull request by ybettan**
Also added a periodic job for OCP-4.9.

Signed-off-by: Yoni Bettan <yonibettan@gmail.com>

### CODE REVIEW

**Comment by qbarrand** [comment]
Could you please remove updates to the CI jobs for the PSAP repo from this PR? [This other PR](https://github.com/openshift/release/pull/26986) is removing the jobs entirely.

**Comment by ybettan** [comment]
/hold
Need to be rebased on top of https://github.com/openshift/release/pull/26986 once merged.

**Pull request merged**
