### PR TITLE
 mtc hypershift 4.16 expansion

### PR DESCRIPTION
**Pull request by shakyav**

### CODE REVIEW

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.16-lp-rosa-hypershift-mtc-interop-aws-rosa

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.16-lp-rosa-hypershift-mtc-interop-aws-rosa

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
