### PR TITLE
WIP: DNM Testing build06

### PR DESCRIPTION
**Pull request by deepsm007**
/cc @nobody

### CODE REVIEW

**Comment by deepsm007** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-x86-ping-bastion

**Comment by deepsm007** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-x86-ping-bastion-build06

**Comment by deepsm007** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-x86-ping-bastion-build06

**Comment by josecastillolema** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-x86-ping-bastion-build06

**Comment by josecastillolema** [comment]
@deepsm007 I think we can close the PR now, thanks!

**Pull request closed without merging**
