### PR TITLE
[kubevirt-tekton-tasks] feat: add tekton-tasks-pusher secret to kubevirt-tekton-tasks

### PR DESCRIPTION
**Pull request by ksimon1**
this new secret will be used by kubevirt tekton tasks e2e tests

### CODE REVIEW

**Review by codingben — APPROVED** [review]
/lgtm

**Comment by ksimon1** [comment]
pj-rehearse pull-ci-kubevirt-kubevirt-tekton-tasks-main-e2e-tests

**Comment by ksimon1** [comment]
/pj-rehearse pull-ci-kubevirt-kubevirt-tekton-tasks-main-e2e-tests

**Review by 0xFelix — APPROVED** [review]
/lgtm

**Comment by codingben** [comment]
I see that `rehearsals-ack` label is missing?

**Pull request merged**
