### PR TITLE
HCO: continue to move lane to CNV account

### PR DESCRIPTION
**Pull request by nunnatsa**
Fix te base domain in the failed lane

Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

### CODE REVIEW

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-image-index-aws

**Comment by orenc1** [comment]
aws dns issue in our account appears to be fixed now. let's check again:
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-image-index-aws

**Comment by nunnatsa** [comment]
/close

Done in #35328

**Pull request closed without merging**
