### PR TITLE
Build Opamp bridge-server from OTEL CI jobs and enable e2e-openshift-serverless test suite in Tempo jobs. 

### PR DESCRIPTION
**Pull request by IshwarKanse**

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-upstream-ocp-4.14-amd64-gcp-ipi-ovn-ipsec-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-upstream-ocp-4.14-amd64-gcp-ipi-ovn-ipsec-opentelemetry-e2e-tests periodic-ci-openshift-grafana-tempo-operator-main-upstream-ocp-4.16-amd64-aws-ipi-shared-vpc-phz-sts-tempo-e2e-tests

**Review by vprashar2929 — APPROVED** [review]
/lgtm

**Pull request merged**
