### PR TITLE
openshift/ovn-kubernetes: fetch dev-scripts image from openshfit-kni/test image stream

### PR DESCRIPTION
**Pull request by akiselev1**
This PR is required to reflect the changes introduced in #8934

### CODE REVIEW

**Comment by akiselev1** [comment]
@pecameron Usually changes in master config are copied to future branches by repo bots within a day after master change. Changes to older branch configs (4.4) are not copied and have to be done manually. I ran `make ci-operator-config` and `make jobs`, but they did not create any updates to job files.

**Comment by pecameron** [comment]
@akiselev1 I think master becomes the latest and we need bz to "back port" earlier releases. In any event the pile of fails gives us things to look at.

**Pull request merged**
