### PR TITLE
OCPEDGE-1033: fix: running the realtime origin suite against the aws metal cluster

### PR DESCRIPTION
**Pull request by jeff-roche**
Running the realtime test suite that is currently run on GCP with the realtime kernel against AWS metal running the realtime kernel

### CODE REVIEW

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.17-upgrade-from-stable-4.16-e2e-metal-ovn-single-node-rt-upgrade-test

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.17-upgrade-from-stable-4.16-e2e-metal-ovn-single-node-rt-upgrade-test

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.17-upgrade-from-stable-4.16-e2e-metal-ovn-single-node-rt-upgrade-test

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.17-upgrade-from-stable-4.16-e2e-metal-ovn-single-node-rt-upgrade-test

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.17-upgrade-from-stable-4.16-e2e-metal-ovn-single-node-rt-upgrade-test

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.17-upgrade-from-stable-4.16-e2e-metal-ovn-single-node-rt-upgrade-test

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.17-upgrade-from-stable-4.16-e2e-metal-ovn-single-node-rt-upgrade-test

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.17-upgrade-from-stable-4.16-e2e-metal-ovn-single-node-rt-upgrade-test

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.17-upgrade-from-stable-4.16-e2e-metal-ovn-single-node-rt-upgrade-test

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.17-upgrade-from-stable-4.16-e2e-metal-ovn-single-node-rt-upgrade-test

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.17-upgrade-from-stable-4.16-e2e-metal-ovn-single-node-rt-upgrade-test

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.17-upgrade-from-stable-4.16-e2e-metal-ovn-single-node-rt-upgrade-test

**Comment by jeff-roche** [comment]
/hold

This needs to wait for https://github.com/openshift/origin/pull/28980 which fixes oslat taking the cluster down

**Comment by eggfoobar** [comment]
/unhold 

Origin change is merged in, we should be good to test this soon

**Comment by eggfoobar** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.17-upgrade-from-stable-4.16-e2e-metal-ovn-single-node-rt-upgrade-test

**Comment by eggfoobar** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.17-upgrade-from-stable-4.16-e2e-metal-ovn-single-node-rt-upgrade-test

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.17-upgrade-from-stable-4.16-e2e-metal-ovn-single-node-rt-upgrade-test

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.17-upgrade-from-stable-4.16-e2e-metal-ovn-single-node-rt-upgrade-test

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.18-upgrade-from-stable-4.17-e2e-metal-ovn-single-node-rt-upgrade-test

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.17-upgrade-from-stable-4.16-e2e-metal-ovn-single-node-rt-upgrade-test

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.17-upgrade-from-stable-4.16-e2e-metal-ovn-single-node-rt-upgrade-test

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-upgrade-from-stable-4.16-e2e-metal-ovn-single-node-rt-upgrade

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.17-upgrade-from-stable-4.16-e2e-metal-ovn-single-node-rt-upgrade-test periodic-ci-openshift-release-master-nightly-4.17-upgrade-from-stable-4.16-e2e-metal-ovn-single-node-rt-upgrade

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-upgrade-from-stable-4.16-e2e-metal-ovn-single-node-rt-upgrade

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-upgrade-from-stable-4.16-e2e-metal-ovn-single-node-rt-upgrade

**Review by vrutkovs — APPROVED** [review]
/approve

**Pull request merged**
