### PR TITLE
Add step to enable crio debug logging and turn it on for azure

### PR DESCRIPTION
**Pull request by stbenjam**
[TRT-309](https://issues.redhat.com//browse/TRT-309)

Needed to troubleshoot https://bugzilla.redhat.com/show_bug.cgi?id=2082271

### CODE REVIEW

**Comment by stbenjam** [comment]
/hold

Pending confirmation this works.

**Comment by deads2k** [comment]
/approve
/hold

holding so @stbenjam can confirm he sees what he wants in the output.  Feel free to release the hold when you're ready.

**Pull request closed without merging**
