### PR TITLE
ocm: app image mirroring for latest and 2.4.0 tags

### PR DESCRIPTION
**Pull request by mikeshng**
Signed-off-by: Mike Ng <ming@redhat.com>

### CODE REVIEW

**Comment by mikeshng** [comment]
Removed the legacy image mirror service.

/assign ray-harris

**Comment by mikeshng** [comment]
@ray-harris please review the changes under `core-services/image-mirroring/open-cluster-management`. Thanks.

**Review by xiangjingli — APPROVED** [review]

**Pull request merged**
