### PR TITLE
Switch Kuryr job to hwoffload cloud

### PR DESCRIPTION
**Pull request by dulek**
This cloud still runs 16.2, let's see how it rolls.

### CODE REVIEW

**Comment by dulek** [comment]
/pj-rehearse ci/rehearse/openshift/kuryr-kubernetes/release-4.13/e2e-openstack-kuryr

**Comment by dulek** [comment]
/pj-rehearse pull-ci-openshift-kuryr-kubernetes-release-4.13-e2e-openstack-kuryr

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-kuryr-kubernetes-release-4.12-e2e-openstack-kuryr

**Comment by dulek** [comment]
/pj-rehearse pull-ci-openshift-kuryr-kubernetes-release-4.13-e2e-openstack-kuryr

**Comment by dulek** [comment]
/pj-rehearse pull-ci-openshift-kuryr-kubernetes-release-4.13-e2e-openstack-kuryr

**Comment by dulek** [comment]
/pj-rehearse pull-ci-openshift-kuryr-kubernetes-release-4.13-e2e-openstack-kuryr

**Pull request closed without merging**
