### PR TITLE
Config nmstate-console-plugin prow

### PR DESCRIPTION
**Pull request by upalatucci**

### CODE REVIEW

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-nmstate-console-plugin-main-e2e-tests

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-nmstate-console-plugin-main-e2e-tests

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-nmstate-console-plugin-main-e2e-tests

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-nmstate-console-plugin-main-e2e-tests

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-nmstate-console-plugin-main-e2e-tests

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-nmstate-console-plugin-main-e2e-tests

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-nmstate-console-plugin-main-e2e-tests

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-nmstate-console-plugin-main-e2e-tests

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-nmstate-console-plugin-main-e2e-tests

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-nmstate-console-plugin-main-e2e-tests

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-nmstate-console-plugin-main-e2e-tests

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-nmstate-console-plugin-main-e2e-tests

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-nmstate-console-plugin-main-e2e-tests

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-nmstate-console-plugin-main-e2e-tests

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-nmstate-console-plugin-main-e2e-tests

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-nmstate-console-plugin-main-e2e-tests

**Comment by orenc1** [comment]
```
 + echo 'Deploy nmstate console plugin'
Deploy nmstate console plugin
+ oc process -f oc-manifest.yaml -p IMAGE=registry.build05.ci.openshift.org/ci-op-dj4wjkhf/pipeline@sha256:ccec6b5a36097a8fb4641105f71d09bb885febfb14ae8ea8ea1ed503cab9f49a
+ oc create -f -
error: unable to process template
  namespaces "ci-op-dj4wjkhf" not found
error: no objects passed to create 
```
Since a namespace is not configured at:
https://github.com/openshift/nmstate-console-plugin/blob/main/oc-manifest.yaml
the namespace used is the one of the current-context.

You might want to add `namespace: nmstate` after:
https://github.com/openshift/nmstate-console-plugin/blob/main/oc-manifest.yaml#L4

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-nmstate-console-plugin-main-e2e-tests

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-nmstate-console-plugin-main-e2e-tests

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-nmstate-console-plugin-main-e2e-tests

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-nmstate-console-plugin-main-e2e-tests

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-nmstate-console-plugin-main-e2e-tests

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-nmstate-console-plugin-main-e2e-tests

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-nmstate-console-plugin-main-e2e-tests

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-nmstate-console-plugin-main-e2e-tests

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-nmstate-console-plugin-main-e2e-tests

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-nmstate-console-plugin-main-e2e-tests

**Comment by upalatucci** [comment]
Hi @hongkailiu thanks for the review. What should i do to have the `rehearsals-ack` label?

**Pull request merged**
