### PR TITLE
Switch to golang 1.14 for NTO 4.6+.

### PR DESCRIPTION
**Pull request by jmencak**
Switch to golang 1.14 for NTO 4.6+.

### CODE REVIEW

**Comment by jmencak** [comment]
/hold
linking a bot-created PR: https://github.com/openshift/release/pull/10245

**Comment by ArangoGutierrez** [comment]
You are always leading the change @jmencak !!

**Comment by jmencak** [comment]
Bot-created PRs are fun.  Had to rebase, /lgtm lost.

**Pull request merged**
