### PR TITLE
CAPO: Only test and build main branch

### PR DESCRIPTION
**Pull request by mdbooth**

### CODE REVIEW

**Comment by mdbooth** [comment]
@mandre Can we try to determine if this PR is correct and, if so, merge it? I believe this will be a prerequisite to getting this built correctly by ART and clusterbot.

**Comment by mdbooth** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-openstack-main-test

**Comment by mdbooth** [comment]
Job failed successfully:
```
go: sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.0.0-20211110210527-619e6b92dab9: cannot query module due to -mod=vendor
make: *** [Makefile:189: /go/src/sigs.k8s.io/cluster-api-provider-openstack/hack/tools/bin/setup-envtest-v0.0.0-20211110210527-619e6b92dab9] Error 1
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"k8s.io/test-infra/prow/entrypoint/run.go:84","func":"k8s.io/test-infra/prow/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2023-10-02T14:12:21Z"} 
```

We would need to fix that in the CAPO repo. I think we should merge this.

**Review by mandre — COMMENTED** [review]
Currently, downstream CAPO has `master` and `main` branches which is really confusing:
- `master` is no longer used (it contained the code of downstream CAPO at `release-4.11` + ART automated changes)
- `main` is a copy of upstream CAPO and serves as our dev branch.

We want to start developing in the `main` branch, and use it to branch off releases branches.

/lgtm
/approve

**Comment by mdbooth** [comment]
Merge conflict. Must have rebased against an old version. Rebase coming in very shortly.

**Pull request merged**
