### PR TITLE
GITOPS: enabling tests for v1.15 version

### PR DESCRIPTION
**Pull request by varshab1210**
gitops-operator jobs added for branch v1.15.

### CODE REVIEW

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-v1.15-v4.17-kuttl-parallel

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-v1.15-v4.17-kuttl-parallel

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-v1.15-v4.17-kuttl-parallel

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-v1.15-v4.17-kuttl-parallel

**Review by Mangaal — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
