### PR TITLE
Add CI prevalidation config for ironic-image 4.17

### PR DESCRIPTION
**Pull request by MahnoorAsghar**

### CODE REVIEW

**Comment by MahnoorAsghar** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-release-4.17-prevalidation-images

**Comment by elfosardo** [comment]
/hold
until 4.17 branching

**Comment by MahnoorAsghar** [comment]
/retest
/hold cancel
4.17 branches created today

**Comment by MahnoorAsghar** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-release-4.17-prevalidation-images

**Comment by MahnoorAsghar** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-master-okd-images
/pj-rehearse pull-ci-openshift-ironic-image-master-okd-scos-images
/pj-rehearse pull-ci-openshift-ironic-image-release-4.17-okd-images

**Comment by MahnoorAsghar** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-master-okd-scos-images

**Comment by MahnoorAsghar** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-release-4.17-okd-images

**Comment by MahnoorAsghar** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-release-4.17-okd-images

**Comment by MahnoorAsghar** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-release-4.17-prevalidation-e2e-metal-ipi-ovn-ipv6-prevalidation

**Comment by MahnoorAsghar** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-master-e2e-metal-ipi-virtualmedia

**Comment by MahnoorAsghar** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-master-okd-images

**Comment by MahnoorAsghar** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-master-okd-scos-images

**Comment by MahnoorAsghar** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-master-prevalidation-e2e-metal-ipi-bm-prevalidation

**Comment by MahnoorAsghar** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-master-prevalidation-e2e-metal-ipi-ovn-ipv6-prevalidation

**Comment by MahnoorAsghar** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-release-4.17-okd-images

**Comment by MahnoorAsghar** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-master-prevalidation-e2e-metal-ipi-ovn-ipv6-prevalidation

**Comment by MahnoorAsghar** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-master-okd-images

**Comment by MahnoorAsghar** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-master-okd-images

**Comment by MahnoorAsghar** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-master-okd-scos-images

**Comment by MahnoorAsghar** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-release-4.17-okd-images

**Comment by MahnoorAsghar** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-master-okd-images

**Comment by MahnoorAsghar** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-release-4.17-okd-images

**Comment by MahnoorAsghar** [comment]
The master/okd-images and jobs are failing consistently (7 times in a row) with a timeout (45 minutes), failing to import imagestreamtags.
The master/okd-scos-images job is failing to copy a grub EFI file from the image.

**Comment by MahnoorAsghar** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-master-okd-images

**Comment by MahnoorAsghar** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-release-4.17-okd-images

**Comment by MahnoorAsghar** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-master-okd-scos-images

**Comment by elfosardo** [comment]
/hold
need https://github.com/openshift/release/pull/52468 first

**Comment by MahnoorAsghar** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-master-okd-scos-images

**Comment by MahnoorAsghar** [comment]
/pj-rehearse pull-ci-openshift-ironic-image-master-okd-images

**Pull request merged**
