### PR TITLE
rename route-controller-manager image to be consistent with ART

### PR DESCRIPTION
**Pull request by atiratree**
inconsistency broke the nightly: https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/265

### CODE REVIEW

**Comment by atiratree** [comment]
@dhellmann can you please take a look?

**Comment by dhellmann** [comment]
Discussion in https://coreos.slack.com/archives/CB95J6R4N/p1664552031166729

/approve

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
