### PR TITLE
Add pre-upgrade prepare and post-upgrade check for chain upgrade

### PR DESCRIPTION
**Pull request by liangxia**
The workflow work as below, e.g, for 4.10 -> 4.13 upgrade,
1. Install 4.10
2. Upgrade to 4.11, then 4.12
3. Pre-upgrade data preparation (ginkgo and cucushift)
4. Upgrade to 4.13
5. Post-upgrade data check (ginkgo and cucushift)

### CODE REVIEW

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-stable-4.11-aws-ipi-p1-f14

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-stable-4.11-aws-ipi-p1-f14

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-stable-4.11-aws-ipi-p1-f14

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-stable-4.1-aws-ipi-p1-f30

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-stable-4.2-aws-ipi-p1-f30

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-stable-4.1-aws-ipi-p1-f30

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-stable-4.2-aws-ipi-p1-f30

**Pull request merged**
