### PR TITLE
prow/bugzilla: release-4.6 requires target release 4.6.z

### PR DESCRIPTION
**Pull request by sdodson**
OCS release-4.6 requires OCS 4.6.0 too.

/cc @eparis @bparees

### CODE REVIEW

**Comment by sdodson** [comment]
I guess @wking and have made themselves OWNERS but I believe @eparis still owns policy decision and can flip the labels directly.

**Comment by bparees** [comment]
OCS still needs 4.6.0 as the target because they haven't shipped 4.6.0 yet?

**Comment by sdodson** [comment]
> OCS still needs 4.6.0 as the target because they haven't shipped 4.6.0 yet?

Their bugs don't seem to have a 4.6.z target release option so I just went with it. I got there from https://github.com/openshift/ocs-operator/pull/855 and the linked bug https://bugzilla.redhat.com/show_bug.cgi?id=1886873 This also aligns with how their release-4.5 branch is configured.

**Comment by bparees** [comment]
/lgtm

don't think i'm an approver though

**Pull request merged**
