### PR TITLE
[o/cert-manager-operator] CI job config updates for 1.12, 1.11

### PR DESCRIPTION
**Pull request by swghosh**
Signed-off-by: Swarup Ghosh <swghosh@redhat.com>

### CODE REVIEW

**Comment by swghosh** [comment]
/pj-rehearse ack
(cannot rehearse without actual bump PRs getting in: openshift/cert-manager-operator#141, openshift/cert-manager-operator#142, openshift/cert-manager-operator#143)

**Comment by thejasn** [comment]
Hmm, needs a re-run on `make jobs`.

**Pull request merged**
