### PR TITLE
Stolostron: configure backplane-2.2 & release-2.7 jobs

### PR DESCRIPTION
**Pull request by skitt**
Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Review by mark-nc — APPROVED** [review]
/lgtm

**Review by gurnben — APPROVED** [review]
/approve /lgtm

**Review by wking — APPROVED** [review]
My Prow-config approval is [just for Boskos][1], but this one looks straightforward enough for me to bend policy to save the test-platform folks some time.

/lgtm

[1]: https://github.com/openshift/release/blob/1d8c9cb48b7318991d15acc17beeba11000474f9/core-services/prow/02_config/OWNERS#L3

**Pull request merged**
