### PR TITLE
Bug 1957031: Move e2e-*-ovn to generated jobs

### PR DESCRIPTION
**Pull request by jluhrsen**
- moves aws, gcp and azure jobs to generated jobs for 4.3-4.9
- previously all branches were set with 48h intervals except
  4.3 and 4.4 which were running at 24h intervals. Intervals
  are now adjusted to:
  * 72h for 4.3, 4.4 and 4.5
  * 48h for 4.6 and 4.7
  * 24h for 4.8 and 4.9

Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>

### CODE REVIEW

**Comment by vrutkovs** [comment]
/approve

Needs rebase

**Review by vrutkovs — COMMENTED** [review]
Looks good, needs `make jobs` to update build cluster assignment

**Comment by jluhrsen** [comment]
> Looks good, needs `make jobs` to update build cluster assignment

that was from me accidentally updating a presubmit yaml for the ovnk repo config. I removed that. I think we are good to go now.

**Review by vrutkovs — APPROVED** [review]
/approve
/lgtm

**Review by droslean — APPROVED** [review]

**Pull request merged**
