### PR TITLE
OCPQE-18692: adding sshkey for core user during install

### PR DESCRIPTION
**Pull request by jinyunma**
auto test case:
OCP-42342 [IPI-on-Azure] Install using ed25519 / ecdsa key

### CODE REVIEW

**Comment by jianlinliu** [comment]
> OCP-24431 [ipi-on-azure] Adding sshkey for core user after cluster is created and login cluster

For now, I prefer to treat the case like some machineconfig related cases, but not a installer case, so maybe we can deactivate such cases. @gpei wdty?

**Comment by jinyunma** [comment]
> > OCP-24431 [ipi-on-azure] Adding sshkey for core user after cluster is created and login cluster
> 
> For now, I prefer to treat the case like some machineconfig related cases, but not a installer case, so maybe we can deactivate such cases. @gpei wdty?

One checkpoint in this case is to check etcd running as static pod, but not as a systemd unit (merged from [OCP-21546](https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-21546)). This seems etcd case, do we still need to cover on installer side?

**Comment by jianlinliu** [comment]
> do we still need to cover on installer side?

I think no, I think that case is old and common enough, I think etcd team should already cover it.

**Comment by gpei** [comment]
> OCP-24431 [ipi-on-azure] Adding sshkey for core user after cluster is created and login cluster
> 
> For now, I prefer to treat the case like some machineconfig related cases, but not a installer case, so maybe we can deactivate such cases. @gpei wdty?

Yes, for such day-2 operations on managing nodes, there only would be MachineConfig involved. I'm ok to drop such testing from installer side.

**Comment by gpei** [comment]
I just had a quick search in MCO test cases and found this one https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-46897, it has the same testing steps as OCP-24431

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-ipi-private-sshkey-f14

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-ipi-private-sshkey-f14

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-ipi-private-sshkey-f14

**Pull request merged**
