### PR TITLE
Updating e2e version to remove dev ES instance

### PR DESCRIPTION
**Pull request by vishnuchalla**
### Description
Updated e2e version so we have dev ES removal updates into CI.

### Testing
Will verify through CI tests here. Also verified in e2e PR: https://github.com/cloud-bulldozer/e2e-benchmarking/pull/721

### CODE REVIEW

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-loaded-upgrade-from-4.17-loaded-upgrade-417to418-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-payload-control-plane-6nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-release-4.18-qe-perfscale-aws-ovn-small-cluster-density

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-conc-builds-3nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-node-density-heavy-3nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-router-perf-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-node-density-cni-3nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-router-perf-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-conc-builds-3nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-control-plane-3nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-router-perf-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-node-density-heavy-3nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-node-density-cni-3nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-control-plane-3nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-conc-builds-3nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-release-4.18-qe-perfscale-aws-ovn-small-cluster-density

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-loaded-upgrade-from-4.17-loaded-upgrade-417to418-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/override periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-payload-control-plane-6nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-payload-control-plane-6nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-payload-control-plane-6nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-payload-control-plane-6nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.17-nightly-x86-loaded-upgrade-from-4.16-loaded-upgrade-416to417-24nodes

**Comment by vishnuchalla** [comment]
Bug fix for index subcommand is here: https://github.com/kube-burner/kube-burner-ocp/pull/120, which will fix the failures in upgrade jobs.

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.17-nightly-x86-loaded-upgrade-from-4.16-loaded-upgrade-416to417-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-payload-control-plane-6nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-loaded-upgrade-from-4.17-loaded-upgrade-417to418-24nodes

**Comment by vishnuchalla** [comment]
Please ignore the above failures that were triggered by mistake and aborted later. Below are the list of key tests that are verified.
```
* rehearse-57560-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-data-path-9nodes
* rehearse-57560-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-loaded-upgrade-from-4.17-loaded-upgrade-417to418-24nodes
* rehearse-57560-pull-ci-openshift-ovn-kubernetes-release-4.18-qe-perfscale-aws-ovn-small-cluster-density
* rehearse-57560-pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-conc-builds-3nodes
* rehearse-57560-pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-control-plane-3nodes
* rehearse-57560-pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-node-density-cni-3nodes
* rehearse-57560-pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-node-density-heavy-3nodes
* rehearse-57560-pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-router-perf-24nodes
```

**Review by mukrishn — APPROVED** [review]
lgtm

**Pull request merged**
