### PR TITLE
MSI - add hypershift tests

### PR DESCRIPTION
**Pull request by rnetser**

### CODE REVIEW

**Comment by rnetser** [comment]
/pj-rehearse  periodic-ci-CSPI-QE-MSI-hypershift-v4.12-hypershift-cluster-tests

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-hypershift-v4.12-hypershift-cluster-tests

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-hypershift-v4.12-hypershift-cluster-tests

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-hypershift-v4.12-hypershift-cluster-tests

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-hypershift-v4.12-hypershift-cluster-tests

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-hypershift-v4.12-hypershift-cluster-tests

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-hypershift-v4.12-hypershift-cluster-tests

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-hypershift-v4.12-hypershift-cluster-tests

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-hypershift-v4.12-hypershift-cluster-tests

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-hypershift-v4.12-hypershift-cluster-tests

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-hypershift-v4.13-hypershift-cluster-tests

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-hypershift-v4.13-hypershift-cluster-tests

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-hypershift-v4.13-hypershift-cluster-tests

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-hypershift-v4.13-hypershift-cluster-tests

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-hypershift-v4.12-hypershift-cluster-tests

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-hypershift-v4.13-hypershift-cluster-tests

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-hypershift-v4.13-hypershift-cluster-tests

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-hypershift-v4.13-hypershift-cluster-tests

**Review by myakove — APPROVED** [review]

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-hypershift-v4.13-hypershift-cluster-tests

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-hypershift-v4.13-hypershift-cluster-tests

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-hypershift-v4.13-hypershift-cluster-tests

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-hypershift-v4.13-hypershift-cluster-tests

**Review by myakove — APPROVED** [review]

**Pull request merged**
