### PR TITLE
[PERFSCALE-3634] Move to new QUADSv2 URLs

### PR DESCRIPTION
**Pull request by josecastillolema**

### CODE REVIEW

**Comment by josecastillolema** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.17-latest-x86-deploy-sno

**Comment by josecastillolema** [comment]
The test failed from an unrelated issue being dealt in https://github.com/openshift/release/pull/60119,
otherwise succeded

**Review by rsevilla87 — APPROVED** [review]
/lgtm

**Pull request merged**
