### PR TITLE
CRI-O: require e2e jobs

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by haircommander** [comment]
/hold

waiting until https://github.com/cri-o/cri-o/pull/4640 merges (to actually fix the jobs)

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by umohnani8** [comment]
/hold

Realised rehearse jobs are not blooking, oops.

**Pull request merged**
