### PR TITLE
Add the new backplane release to the plugins.yaml for ACM

### PR DESCRIPTION
**Pull request by jnpacker**
Signed-off-by: Joshua Packer <jpacker@redhat.com>

### CODE REVIEW

**Review by schmidtd — APPROVED** [review]
/LGTM

**Review by hongkailiu — COMMENTED** [review]
I do not find any config file satisfying the path:

```console
$ find . -name "*-backplane-2.1*.yaml"
```

Usually the change like this comes together with the config files.
And we have checks to ensure any config file will be included in one (and only one) sharded configMap.

**Comment by jnpacker** [comment]
@hongkailiu I did this pull separate from my change as I was told I should do it first. i can put this change together with my original pull request.

https://github.com/openshift/release/pull/28137

**Comment by jnpacker** [comment]
I did try to add this change to the pull request with the new config's but I still see the shardding error.

**Comment by schmidtd** [comment]
No, this one has to go in first.

**Comment by jnpacker** [comment]
@hongkailiu is this change required prior to my merge of the new prow jobs?

**Comment by schmidtd** [comment]
I forgot this hadn't merged... I started a new one, now we need ACM as well:
https://github.com/openshift/release/pull/28496

**Comment by schmidtd** [comment]
@hongkailiu Please LGTM this PR first: https://github.com/openshift/release/pull/28496
This PR can be closed in lieu of that one.

**Comment by jnpacker** [comment]
Since #28496 duplicates this work, closing this pull request.

**Pull request closed without merging**
