### PR TITLE
Updating e2e version to the latest

### PR DESCRIPTION
**Pull request by vishnuchalla**
### Description
Updating e2e version to the latest.

### Testing
Testing and verifying through the PRs.

### CODE REVIEW

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-release-4.16-qe-perfscale-aws-ovn-small-cluster-density

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-data-path-9nodes

**Comment by rsevilla87** [comment]
IMO this kind of PRs are not necessary unless we need any specific feature/fix, only available in a most recent e2e tag

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-release-4.16-qe-perfscale-aws-ovn-small-cluster-density

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-release-4.16-qe-perfscale-aws-ovn-small-cluster-density

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-payload-control-plane-6nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-node-density-heavy-3nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-loaded-upgrade-from-4.15-loaded-upgrade-415to416-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-conc-builds-3nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.17-nightly-x86-node-density-cni-3nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.13-nightly-x86-router-perf-3nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-conc-builds-3nodes

**Pull request merged**
