### PR TITLE
MicroShift E2E: Custom link to log.html

### PR DESCRIPTION
**Pull request by pmtk**

### CODE REVIEW

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-e2e

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-e2e

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-e2e

**Comment by dhellmann** [comment]
/lgtm

Excellent addition!

**Pull request merged**
