### PR TITLE
Fix HyperShift QE multi CI job

### PR DESCRIPTION
**Pull request by LiangquanLi930**

### CODE REVIEW

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-aws-ipi-ovn-hypershift-guest-f14-destructive

**Comment by lwan-wanglin** [comment]
cc @liangxia to review, thanks

**Comment by LiangquanLi930** [comment]
@liangxia Could you help to review this PR? Thanks

**Pull request merged**
