### PR TITLE
[MMO] Build10 post-submits enablement (multiarch) and increase limits and requests for SAST

### PR DESCRIPTION
**Pull request by aleskandro**
/cc @Prashanth684

### CODE REVIEW

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-manager-operator-main-images-multi

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-manager-operator-main-images-multi

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-manager-operator-main-images-multi

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-manager-operator-main-images-multi

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-manager-operator-main-images-multi

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-manager-operator-main-images-multi

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-manager-operator-main-images-multi

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-manager-operator-main-images-multi

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-manager-operator-main-images-multi

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-manager-operator-main-images-multi

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-manager-operator-main-fmt

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-manager-operator-main-images-multi

**Comment by droslean** [comment]
/pj-rehearse pull-ci-openshift-multiarch-manager-operator-main-images-multi

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-manager-operator-main-fmt

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-multiarch-manager-operator-main-images-multi

**Pull request merged**
