### PR TITLE
initial commit of calico cni

### PR DESCRIPTION
**Pull request by mrbojangles3**
Add the installation of the Calico CNI to our testing 
[JIRA - [PERFSCALE-2874](https://issues.redhat.com//browse/PERFSCALE-2874)](https://issues.redhat.com/browse/PERFSCALE-2874)

### CODE REVIEW

**Review by jtaleric — COMMENTED** [review]
Lets get add a job in config here -  https://github.com/openshift/release/blob/master/ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.16-nightly-x86.yaml#L268 

Similar to this job.

**Comment by jtaleric** [comment]
@mrbojangles3 you need to regenerate all the files after updating the `owners` file

**Comment by mrbojangles3** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-calico-control-plane-24nodes

**Comment by mrbojangles3** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-calico-control-plane-24nodes

**Comment by mrbojangles3** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-calico-control-plane-24nodes

**Comment by jtaleric** [comment]
Unrelated failure.

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-calico-control-plane-24nodes

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-calico-control-plane-24nodes

**Comment by mrbojangles3** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-calico-control-plane-24nodes

**Comment by mrbojangles3** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-calico-control-plane-24nodes

**Comment by jtaleric** [comment]
```INFO[2024-03-29T18:37:11Z] Logs for container test in pod calico-control-plane-24nodes-openshift-qe-move-pods-infra: 
```

We should deploy manually and run these tasks to determine where/why these failures keep hitting us in CI

**Comment by mrbojangles3** [comment]
I have followed the docs, created two infra nodes, tried to reproduce this by hand. was not able to. I will investigate further.

**Pull request closed without merging**
