### PR TITLE
openstack: Test OCP v4.12

### PR DESCRIPTION
**Pull request by pierreprinetti**
This patch is the result of:
1. running the [ShiftStack version-rolling script][1];
2. changing the target release of periodics from "nightly" to "ci";
3. adding Slack reporting for the new 4.12 jobs.

[1]: https://github.com/shiftstack/shiftstack-ci/blob/main/bump-periodics.sh

cf https://github.com/shiftstack/shiftstack-ci/pull/181

Implements [OSASINFRA-2904](https://issues.redhat.com//browse/OSASINFRA-2904)

### CODE REVIEW

**Comment by pierreprinetti** [comment]
The 4.12 image seems not to be available yet.

**Comment by pierreprinetti** [comment]
Looks like we have a 4.12 image.
PTAL @mandre @EmilienM

**Comment by pierreprinetti** [comment]
Let me rebase, so that the PR job history is a bit easier to read

**Review by mandre — COMMENTED** [review]
We now have some 4.12 images after we changed to the ci stream. The jobs all seem to run, which is the point of this PR.
/lgtm
/approve

**Pull request merged**
