### PR TITLE
Add josecastillolema/rsevilla87 as openshift-qe approvers

### PR DESCRIPTION
**Pull request by josecastillolema**

### CODE REVIEW

**Comment by josecastillolema** [comment]
cc @rsevilla87

**Comment by josecastillolema** [comment]
PTAL @jtaleric

**Comment by afcollins** [comment]
lgtm but I am not an approver in two of the files, so you still need someone who is @paigerube14 @svetsa-rh

**Comment by josecastillolema** [comment]
Thanks @paigerube14 !

**Pull request merged**
