### PR TITLE
RHOSDT 3.4 test on IBM P

### PR DESCRIPTION
**Pull request by IshwarKanse**

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.15-ibm-p-stage-jaeger-stage-tests-ibm-p

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.15-ibm-p-stage-jaeger-stage-tests-ibm-p

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.15-ibm-p-stage-jaeger-stage-tests-ibm-p

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.16-ibm-p-stage-jaeger-stage-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.16-ibm-p-stage-jaeger-stage-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.16-ibm-p-stage-tempo-stage-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.16-ibm-p-stage-opentelemetry-stage-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.16-ibm-p-stage-opentelemetry-stage-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.16-ibm-p-stage-opentelemetry-stage-tests

**Comment by IshwarKanse** [comment]
Few tests failed as the cluster is SNO and lacks enough resources.

**Review by vprashar2929 — APPROVED** [review]
/lgtm

**Pull request merged**
