### PR TITLE
Allow tcpdump collection from master nodes as well

### PR DESCRIPTION
**Pull request by trozet**
Also enables tcpdump for azure where we are seeing nodes go unready after kapiserver restarts.

### CODE REVIEW

**Comment by jluhrsen** [comment]
/lgtm

just FYI that this tcpdump-service is not enabled on any jobs right now

**Comment by deads2k** [comment]
/pj-rehearse
/approve

/hold

you may self-release the hold after confirming the rehearsal results.

**Comment by trozet** [comment]
looks like my syntax is wrong and we need to pass a label: 

INFO: gathering quay tcpdump packet headers if present
error: at least one node name or a selector (-l) must be specified

**Comment by trozet** [comment]
/pj-rehearse pull-ci-openshift-machine-config-operator-release-4.15-e2e-azure-ovn-upgrade

**Comment by trozet** [comment]
looks like its working: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/41541/rehearse-41541-pull-ci-openshift-machine-config-operator-release-4.15-e2e-azure-ovn-upgrade/1683148386158514176/artifacts/e2e-azure-ovn-upgrade/gather-extra/artifacts/tcpdump/

**Pull request merged**
