### PR TITLE
Telco5g-cnf-tests Run with new params

### PR DESCRIPTION
**Pull request by liornoy**
Depends-On: https://github.com/openshift-kni/cnf-features-deploy/pull/1501

### CODE REVIEW

**Comment by liornoy** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-telco5g-cnftests

**Comment by liornoy** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-telco5g-cnftests

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-telco5g-cnftests

**Comment by liornoy** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-telco5g-cnftests

**Comment by liornoy** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-telco5g-cnftests

**Comment by liornoy** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-telco5g-cnftests pull-ci-openshift-kni-cnf-features-deploy-master-e2e-gcp-ovn

**Comment by liornoy** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-telco5g-cnftests

**Comment by liornoy** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-master-e2e-gcp-ovn

**Comment by liornoy** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-telco5g-cnftests

**Comment by liornoy** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-telco5g-cnftests

**Comment by liornoy** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-telco5g-cnftests

**Comment by liornoy** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-telco5g-cnftests

**Comment by liornoy** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-telco5g-cnftests

**Comment by liornoy** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-telco5g-cnftests

**Comment by liornoy** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-telco5g-cnftests

**Pull request closed without merging**
