### PR TITLE
Remove labels from vsphere cloud config file

### PR DESCRIPTION
**Pull request by gnufied**
Fixes https://issues.redhat.com/browse/OCPBUGS-1264

### CODE REVIEW

**Comment by jsafrane** [comment]
/retest
hoping that a vmware job is rehearsed

**Comment by gnufied** [comment]
@jsafrane the vsphere migration tests were passing btw.

**Comment by jsafrane** [comment]
I can see all vSphere rehearsals installed and tests passed. There are some flaky invariants, not caused by this PR.

**Pull request closed without merging**
