### PR TITLE
Update qe azure proxy techpreview workflow

### PR DESCRIPTION
**Pull request by sunzhaohua2**
Update `azure-ipi-proxy-ccm` to `azure-ipi-proxy-techpreview`, use step i`pi-conf-techpreview` instead of `ccm-conf-apply-feature-gate`. @jhou1 @miyadav @huali9 Please help to take a look.

Change because we want to use one workflow to cover both capi and ccm. We will add two workflows for each provider such as `aws-ipi-disconnected-private-techpreview` and` aws-ipi-proxy-techpreview` with step` ipi-conf-techpreview`,  no longer cover post installation. Merge together because both ccm and capi are enabled by featuregate. No longer cover post installation because dev have already covered  the two installation methods ,we don't need repetitive work. No matter ccm/capi is installed by which method, after it’s installed, it will be same for us to run e2e testing.  Sorry for bringing it up so late as we have almost done all the workflows.
For 4.10 it will only cover ccm, for 4.11 it will cover capi+ccm, if ccm GA in 4.12 then it will only cover capi in 4.12.

### CODE REVIEW

**Comment by jhou1** [comment]
@sunzhaohua2 Can you please provide context about this change? Thanks

**Comment by sunzhaohua2** [comment]
> @sunzhaohua2 Can you please provide context about this change? Thanks

I updated https://github.com/openshift/release/pull/29809#issue-1283195753, please take a look.

**Comment by jianlinliu** [comment]
@jhou1 @liangxia anyone can help review this?

**Comment by liangxia** [comment]
The bot stated that there are conflicts.

**Pull request merged**
