### PR TITLE
Adding Origin CI GPU Job

### PR DESCRIPTION
**Pull request by zvonkok**
I want to make sure that GPUs are always functional in Origin.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Can you link the `aos-cd-jobs` PR that this is paired with?

**Comment by zvonkok** [comment]
Here is the corresponding sjb config for this prow job: [https://github.com/openshift/aos-cd-jobs/pull/1546](https://github.com/openshift/aos-cd-jobs/pull/1546)

**Comment by stevekuznetsov** [comment]
When the other merges, we can merge this

**Comment by jeremyeder** [comment]
I LGTM'd the sjb PR

**Comment by kargakis** [comment]
/hold

seems to need a rebase

**Comment by zvonkok** [comment]
@kargakis  This branch has no conflicts with the base branch

**Comment by stevekuznetsov** [comment]
It doesn't have conflicts but your `git` history is all out of whack -- you have hundreds of commits in this branch.

**Pull request closed without merging**
