### PR TITLE
update OWNERS in openshift/upgrade folder

### PR DESCRIPTION
**Pull request by jluhrsen**
- removes associates no longer at red hat
- adds jluhrsen

Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>

### CODE REVIEW

**Review by wking — APPROVED** [review]
/lgtm

**Comment by jluhrsen** [comment]
@wking, I had to update this with `make registry-metadata` after you /lgtm so it got removed. mind adding it back please?

**Review by wking — APPROVED** [review]
/lgtm

**Comment by jluhrsen** [comment]
> /lgtm

@bear-redhat , can you /lgtm again please? I had to re-do the 'make metadata' stuff. all tests pass now

**Pull request merged**
