### PR TITLE
Soft-deprecate MERGE_BLOCKING_STATUS_MIGRATION.md

### PR DESCRIPTION
**Pull request by petr-muller**
These instructions are no longer needed now when status-reconciler is in place. An alternative is to keep this file and add some bold note to the top about status-reconciler.

/cc @stevekuznetsov @droslean @bbguimaraes

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Let's keep it in case we need manual intervention

**Comment by petr-muller** [comment]
I've added a warning explaining the current status to the header of the doc.

**Pull request merged**
