### PR TITLE
[LPTOCPCI-306] Remove Unneeded Operator from OADP Scenario

### PR DESCRIPTION
**Pull request by calebevans**

### CODE REVIEW

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-oadp-qe-oadp-qe-automation-main-oadp1.1-ocp4.14-lp-interop-oadp-interop-aws

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-oadp-qe-oadp-qe-automation-main-oadp1.1-ocp4.14-lp-interop-oadp-interop-aws

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-oadp-qe-oadp-qe-automation-main-oadp1.1-ocp4.14-lp-interop-oadp-interop-aws

**Review by ascerra — APPROVED** [review]

**Pull request merged**
