### PR TITLE
Create a set of base images in CI that can build like OSBS

### PR DESCRIPTION
**Pull request by smarterclayton**
This creates jobs to maintain base images that have repos that point to
the internal mirrors (so that the images don't have credentials in them).

The base images are available to authenticated users.

The standard-golang.yaml job demonstrates running a build on api.ci that
consumes rhel content. We could make it easy for someone to run a binary
build against the server. The advantage of this approach is that creds
never leave the cluster and CI and user testing is the same.

### CODE REVIEW

**Comment by smarterclayton** [comment]
https://github.com/openshift/release/pull/2102/files#diff-17fc2d30b3b0b5c53b6dc6ad6f4618daR19 would be the standard Dockerfile that every repo would have modulo some tweaks.  Someone could test arbitrary docker files by tweaking the build yaml and running it on api.ci.  We'd want to make it cleaner.

@stevekuznetsov @adammhaile @smunilla this demonstrates CI that runs against a rhel mirror we control outside the firewall, but is reasonably testable locally, that requires no Dockerfile enablement (the base image you chose for CI controls the content).  The mirror controls the set of enabled packages (base-4-0 would be the standard mirror, but we could have logging-4-0 or nodejs-4-0, one for each repo set):

```
$ curl http://base-4-0.ocp.svc

[docker]
id = docker
name = docker
baseurl = http://base-4-0.ocp.svc/docker
enabled = 1
gpgcheck = 0

[openshift]
id = openshift
name = openshift
baseurl = http://base-4-0.ocp.svc/openshift
enabled = 1
gpgcheck = 0

[rhel-7.5-server]
id = rhel-7.5-server
name = rhel-7.5-server
baseurl = http://base-4-0.ocp.svc/rhel-7.5-server
enabled = 1
gpgcheck = 0

[rhel-7.5-server-optional]
id = rhel-7.5-server-optional
name = rhel-7.5-server-optional
baseurl = http://base-4-0.ocp.svc/rhel-7.5-server-optional
enabled = 1
gpgcheck = 0

[rhel-7.5-server-extras]
id = rhel-7.5-server-extras
name = rhel-7.5-server-extras
baseurl = http://base-4-0.ocp.svc/rhel-7.5-server-extras
enabled = 1
gpgcheck = 0

[rhel-7.5-atomic]
id = rhel-7.5-atomic
name = rhel-7.5-atomic
baseurl = http://base-4-0.ocp.svc/rhel-7.5-atomic
enabled = 1
gpgcheck = 0
```

**Comment by smarterclayton** [comment]
```
oc logs build.build.openshift.io/example-rhel-golang -f -n ocp
Cloning "https://github.com/openshift/cluster-version-operator.git" ...
	Commit:	ffcd66a9b1e8ba7364f7ed46d0cac577e5b49e82 (Merge pull request #49 from smarterclayton/add_service)
	Author:	OpenShift Merge Robot <openshift-merge-robot@users.noreply.github.com>
	Date:	Wed Nov 7 12:14:41 2018 -0800
Replaced Dockerfile FROM image registry.svc.ci.openshift.org/ocp/base-4.0:rhel

Pulling image docker-registry.default.svc:5000/ocp/base-4.0@sha256:c8f073ef5ebd0e09ff035606f7c7e95f21b9be73a3a4121cea78b9515eddb991 ...
Pulled 2/3 layers, 68% complete
Pulled 3/3 layers, 100% complete
Extracting

Pulling image registry.svc.ci.openshift.org/ocp/builder:golang-1.10 ...
--> FROM registry.svc.ci.openshift.org/ocp/builder:golang-1.10 as 0
--> WORKDIR /go/src/github.com/openshift/cluster-version-operator
--> COPY . .
--> RUN go build -o cluster-version-operator ./cmd
--> FROM docker-registry.default.svc:5000/ocp/base-4.0@sha256:c8f073ef5ebd0e09ff035606f7c7e95f21b9be73a3a4121cea78b9515eddb991 as 1
--> RUN INSTALL_PKGS="       wget       " &&     yum install -y $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum clean all
Loaded plugins: ovl, product-id, search-disabled-repos, subscription-manager
This system is not receiving updates. You can use subscription-manager on the host to register and assign subscriptions.
Resolving Dependencies
--> Running transaction check
---> Package wget.x86_64 0:1.14-18.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package      Arch           Version              Repository               Size
================================================================================
Installing:
 wget         x86_64         1.14-18.el7          rhel-7.5-server         547 k

Transaction Summary
================================================================================
Install  1 Package

Total download size: 547 k
Installed size: 2.0 M
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : wget-1.14-18.el7.x86_64                                      1/1
install-info: No such file or directory for /usr/share/info/wget.info.gz
  Verifying  : wget-1.14-18.el7.x86_64                                      1/1

Installed:
  wget.x86_64 0:1.14-18.el7

Complete!
Loaded plugins: ovl, product-id, search-disabled-repos, subscription-manager
This system is not receiving updates. You can use subscription-manager on the host to register and assign subscriptions.
Cleaning repos: docker openshift rhel-7.5-atomic rhel-7.5-server
              : rhel-7.5-server-extras rhel-7.5-server-optional
Other repos take up 1.6 k of disk space (use --verbose for details)
--> COPY --from=0 ./cluster-version-operator /usr/bin/cluster-version-operator
--> ENV "OPENSHIFT_BUILD_NAME"="example-rhel-golang" "OPENSHIFT_BUILD_NAMESPACE"="ocp" "OPENSHIFT_BUILD_SOURCE"="https://github.com/openshift/cluster-version-operator.git" "OPENSHIFT_BUILD_REFERENCE"="master" "OPENSHIFT_BUILD_COMMIT"="ffcd66a9b1e8ba7364f7ed46d0cac577e5b49e82"
--> LABEL "io.openshift.build.commit.author"="OpenShift Merge Robot \u003copenshift-merge-robot@users.noreply.github.com\u003e" "io.openshift.build.commit.date"="Wed Nov 7 12:14:41 2018 -0800" "io.openshift.build.commit.id"="ffcd66a9b1e8ba7364f7ed46d0cac577e5b49e82" "io.openshift.build.commit.message"="Merge pull request #49 from smarterclayton/add_service" "io.openshift.build.commit.ref"="master" "io.openshift.build.name"="example-rhel-golang" "io.openshift.build.namespace"="ocp" "io.openshift.build.source-location"="https://github.com/openshift/cluster-version-operator.git"
--> Committing changes to temp.builder.openshift.io/ocp/example-rhel-golang:bcf15c48 ...
--> Done
Build complete, no image push requested
```

**Comment by smarterclayton** [comment]
Will include examples of ci-operator config, prow config, ocp-build-data
config, and a local dev flow tomorrow

**Comment by adammhaile** [comment]
@smarterclayton I think I understand but let's discuss this morning if time permits.

**Comment by smarterclayton** [comment]
Starting to explore generating both ci-operator config definitions and prow jobs for RHEL tasks.  I am using a python script for now to transform existing job definitions in bulk (including many who don't have an equivalent yet in OSBS).

https://github.com/openshift/builder/pull/22 shows a passing RHEL run for a straight transformation of that job.  

Created https://github.com/openshift/ci-operator-prowgen/pull/43 to look at how to have prowgen have separate definitions for a rep and carry that through (used `_rhel` in the filename to create an alternate generation path).

**Comment by smarterclayton** [comment]
In order to do validation, we need to unambiguously know what a jobs variant is https://github.com/openshift/ci-operator-prowgen/pull/47

**Pull request merged**
