### PR TITLE
disable branch protection on openshift/library

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@stevekuznetsov we use a jenkins job to update openshift/library nightly.  It seems like branch protection broke it, so i'm disabling it, but if there's a different approach we should use please let me know (e.g. giving the job a different set of credentials that allow it to merge?).

The job we run is here:
https://ci.openshift.redhat.com/jenkins/job/update_openshift_library

**Comment by bparees** [comment]
@coreydaley thanks for catching this.  i'm going to manually update openshift/library for now.

**Comment by stevekuznetsov** [comment]
Just add the credentials you are using to push to the list of users that can push to the library repo

**Comment by bparees** [comment]
@stevekuznetsov my pushes are still failing.  When do these changes get applied to the repo?

**Comment by bparees** [comment]
And do the ci-bots need admin to be able to apply the changes to the repo?  they did not have it, though i have added it now.

**Pull request merged**
