### PR TITLE
[WIP] OCPQE-13529: unknown error: Chrome failed to start: crashed

### PR DESCRIPTION
**Pull request by liangxia**
Update on Feb 7, 2023
Replaced by https://github.com/openshift/release/pull/36116

### CODE REVIEW

**Comment by bear-redhat** [comment]
@liangxia  can you also create a rehearsal for build01?

**Comment by liangxia** [comment]
The changes in openshift-tests-private are very likely to conflict.
Replaced by https://github.com/openshift/release/pull/36116

/close

**Pull request closed without merging**
