### PR TITLE
use ipi-conf chain on aws/gcp/azure cloudproviders

### PR DESCRIPTION
**Pull request by jianlinliu**
1. help QE's workflow get synced together when new steps are added into the chains
2. homogenize install config generate step on aws/gcp/azure cloudproviders to compare for easy narrow down

### CODE REVIEW

**Comment by jianlinliu** [comment]
@yunjiang29 @jianli-wei @MayXuQQ Ready to review now.

**Comment by jianli-wei** [comment]
The updates on GCP parts look good to me, thanks! 
/lgtm

**Pull request merged**
