### PR TITLE
updated clair component to be managed

### PR DESCRIPTION
**Pull request by deshpandevlab**
Creating Clair managed component in quay tests

Quay-operator tests are failing for a timeout using

```
"containerStatuses": [
                    {
                        "image": "quay.io/sclorg/postgresql-15-c9s:latest",
                        "imageID": "",
                        "lastState": {},
                        "name": "clair-postgres-15",
                        "ready": false,
                        "restartCount": 0,
                        "started": false,
                        "state": {
                            "waiting": {
                                "message": "secret \"clair-config-secret\" not found",
                                "reason": "CreateContainerConfigError"
                            }
                        }
                    }
                ],
```

### CODE REVIEW

**Comment by deshpandevlab** [comment]
Manually tested deploying a quay registry with Clair component as managed without any custom config. Clair should create the supporting config on it's own.

**Comment by syed** [comment]
LGTM

**Review by syed — APPROVED** [review]

**Comment by deshpandevlab** [comment]
/pj-rehearse pull-ci-quay-quay-operator-master-ocp-latest-e2e

**Comment by deshpandevlab** [comment]
/pj-rehearse pull-ci-quay-quay-operator-master-ocp-latest-e2e

**Comment by deshpandevlab** [comment]
tests failed for objectbucketclaim not found. The fix is merged, restarting the tests

/pj-rehearse pull-ci-quay-quay-operator-master-ocp-latest-e2e

**Pull request merged**
