### PR TITLE
[OLS] operator - moving to use hypershift cluster for e2e

### PR DESCRIPTION
**Pull request by xrajesh**
Moving back to use hypershift cluster for e2e

### CODE REVIEW

**Comment by xrajesh** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-operator-main-bundle-e2e

**Comment by bear-redhat** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-operator-main-images

**Comment by bear-redhat** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-operator-main-bundle-e2e

**Comment by bparees** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-operator-main-bundle-e2e

**Comment by xrajesh** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-operator-main-bundle-e2e

**Comment by xrajesh** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-operator-main-bundle-e2e

**Comment by xrajesh** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-operator-main-bundle-e2e

**Comment by bear-redhat** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-operator-main-bundle-e2e

**Comment by xrajesh** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-operator-main-bundle-e2e

**Comment by xrajesh** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-operator-main-bundle-e2e

**Comment by xrajesh** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-operator-main-bundle-e2e

**Pull request merged**
