### PR TITLE
STOR-1750: Build azure file from csi operator

### PR DESCRIPTION
**Pull request by gnufied**
Fixes [STOR-1750](https://issues.redhat.com//browse/STOR-1750)

### CODE REVIEW

**Comment by gnufied** [comment]
/pj-rehearse pull-ci-openshift-cluster-storage-operator-master-e2e-azure-file-csi

**Comment by dobsonj** [comment]
/lgtm
but I think you'll need to rebase now that https://github.com/openshift/release/pull/48802 has merged.
After rebasing, the approval under ci-operator/jobs/openshift/release shouldn't be required anymore.

**Comment by gnufied** [comment]
/pj-rehearse pull-ci-openshift-cluster-storage-operator-master-e2e-azure-file-csi

**Comment by gnufied** [comment]
/pj-rehearse pull-ci-openshift-cluster-storage-operator-4.15-e2e-azure-file-csi

**Comment by gnufied** [comment]
Some of the older ones succeeded. So I will cancel the hold.

/hold cancel

**Pull request merged**
