### PR TITLE
Run kuttl tests in e2e job for neutron-operator

### PR DESCRIPTION
**Pull request by cescgina**
Run the build-deploy-kuttl workflow instead of the build-deploy one.

### CODE REVIEW

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-neutron-operator-master-neutron-operator-build-deploy-kuttl

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-neutron-operator-master-neutron-operator-build-deploy-kuttl

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-neutron-operator-master-neutron-operator-build-deploy-kuttl

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-neutron-operator-master-neutron-operator-build-deploy-kuttl

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-neutron-operator-master-neutron-operator-build-deploy-kuttl

**Comment by cescgina** [comment]
Tests passed, ready for review

**Comment by rlandy** [comment]
Logs show kuttl tests passing:

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/37124/rehearse-37124-pull-ci-openstack-k8s-operators-neutron-operator-master-neutron-operator-build-deploy-kuttl/1634199743208886272/artifacts/neutron-operator-build-deploy-kuttl/openstack-k8s-operators-kuttl/build-log.txt

--- PASS: kuttl (150.60s)
    --- PASS: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/neutron_scale (140.90s)
PASS

Agreed that build-deploy should not always run - the build-deploy-kuttl should

**Pull request merged**
