### PR TITLE
Add & fix test execution for maistra in ROSA 

### PR DESCRIPTION
**Pull request by smpsgill**
Testing running the maistra tests on ROSA

### CODE REVIEW

**Comment by Simranpal** [comment]
/pj-rehearse  pull-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-images periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-servicemesh-rosa-aws

**Comment by Simranpal** [comment]
/pj-rehearse pull-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-images periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-servicemesh-rosa-aws

**Comment by Simranpal** [comment]
/pj-rehearse pull-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-images periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-servicemesh-rosa-aws

**Comment by Simranpal** [comment]
/pj-rehearse pull-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-images periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-servicemesh-rosa-aws

**Comment by FilipB** [comment]
@Simranpal there are some test failures but the oc login works fine. I will create new ROSA cluster to debug.

**Comment by FilipB** [comment]
/pj-rehearse pull-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-images periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-servicemesh-rosa-aws

**Comment by FilipB** [comment]
I added env variables to run just the interop group and maistra test tool are green now.

**Comment by FilipB** [comment]
/pj-rehearse pull-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-images periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-servicemesh-rosa-aws

**Comment by Simranpal** [comment]
/pj-rehearse pull-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-images periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-servicemesh-rosa-aws

**Comment by FilipB** [comment]
/pj-rehearse pull-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-images periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-servicemesh-rosa-aws

**Comment by FilipB** [comment]
/pj-rehearse pull-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-images periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-servicemesh-rosa-aws

**Comment by FilipB** [comment]
/pj-rehearse pull-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-images periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-servicemesh-rosa-aws

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-servicemesh-rosa-aws

**Comment by Simranpal** [comment]
/pj-rehearse pull-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-images periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-servicemesh-rosa-aws

**Comment by Simranpal** [comment]
/pj-rehearse pull-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-images periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-servicemesh-rosa-aws

**Comment by FilipB** [comment]
/pj-rehearse pull-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-images periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-servicemesh-rosa-aws

**Comment by Simranpal** [comment]
/pj-rehearse  pull-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-image periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-interop-servicemesh-interop-aws periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.15-lp-interop-servicemesh-interop-aws

**Pull request merged**
