### PR TITLE
chore: move remaining RHTAP repos to RHTAP CP

### PR DESCRIPTION
**Pull request by psturc**
https://issues.redhat.com/browse/RHTAP-1885

### CODE REVIEW

**Review by thepetk — APPROVED** [review]
/lgtm

**Review by mmorhun — APPROVED** [review]

**Review by dirgim — APPROVED** [review]
/lgtm

**Comment by psturc** [comment]
Hi @stuartwdouglas we're migrating JBS e2e jobs to rhtap cluster pools. The jvm-in-repo e2e job hit [this failure](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/45374/rehearse-45374-pull-ci-redhat-appstudio-jvm-build-service-main-jvm-build-service-in-repo-jbs-e2e/1721860244453199872#1:build-log.txt%3A3063) and other JBS jobs failed too - do you have any concerns? do you think it could be related to this PR or is it safe to merge it?

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-image-controller-main-image-controller-e2e pull-ci-redhat-appstudio-integration-service-main-integration-service-e2e

**Comment by flacatus** [comment]
seems like most of the jobs are not related with this pr. We can merge after  @stuartwdouglas confirmation

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-jvm-build-service-main-jvm-build-service-e2e

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-managed-gitops-main-managed-gitops-e2e-tests

**Comment by stuartwdouglas** [comment]
LGTM, the failures are not related

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-managed-gitops-main-managed-gitops-e2e-tests

**Comment by psturc** [comment]
@jgwest I increased the timeout for gitops e2e job to 3h. do you think [this test failure](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/45374/rehearse-45374-pull-ci-redhat-appstudio-managed-gitops-main-managed-gitops-e2e-tests/1722255254180859904#1:build-log.txt%3A961) could be related to the PR?

**Pull request merged**
