### PR TITLE
Setup CI for serverless release 1.28

### PR DESCRIPTION
**Pull request by ReToCode**
- As in https://github.com/openshift/release/pull/34864

/cc @matzew, @skonto

### CODE REVIEW

**Comment by ReToCode** [comment]
/pj-rehearse pull-ci-openshift-knative-serverless-operator-release-1.28-4.8-upstream-e2e-aws-ocp-48
/pj-rehearse pull-ci-openshift-knative-serverless-operator-release-1.28-4.8-upstream-e2e-mesh-aws-ocp-48

**Comment by skonto** [comment]
```
    spoof.go:180: Retrying https://helloworld-go-serverless-tests2.apps.ci-ocp-4-8-amd64-aws-us-east-1-tgk8b.hive.aws.ci.openshift.org: retrying for certificate signed by unknown authority: Get "https://helloworld-go-serverless-tests2.apps.ci-ocp-4-8-amd64-aws-us-east-1-tgk8b.hive.aws.ci.openshift.org": x509: certificate signed by unknown authority
```

**Comment by ReToCode** [comment]
/pj-rehearse pull-ci-openshift-knative-serverless-operator-release-1.28-4.8-upstream-e2e-mesh-aws-ocp-48

**Comment by ReToCode** [comment]
4.8 builds are failing because of https://redhat-internal.slack.com/archives/CD87JDUB0/p1678366812460729?thread_ts=1678364834.982649&cid=CD87JDUB0. Going to merge this without them.

/pj-rehearse ack

**Pull request merged**
