### PR TITLE
MULTIARCH-4785 Multiarch Compute Day 0 arm x86 GCP

### PR DESCRIPTION
**Pull request by tvardema**
The multiarch team is working on an installer PR to enable day-0 multiarch compute deployments. This PR enables this on GCP.

### CODE REVIEW

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-gcp-ovn-heterogeneous periodic-ci-openshift-release-master-nightly-4.16-e2e-gcp-ovn-fips pull-ci-openshift-cluster-config-operator-release-4.14-e2e-gcp pull-ci-openshift-cluster-kube-apiserver-operator-release-4.17-e2e-gcp-operator periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-e2e-gcp-ovn-arm64

**Comment by tvardema** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-gcp-ovn-heterogeneous

**Comment by r4f4** [comment]
`e2e-gcp-ovn-heterogeneous`: expected to fail until https://github.com/openshift/installer/pull/8701 merges.

/pj-rehearse ack

**Review by r4f4 — COMMENTED** [review]
/lgtm

**Pull request merged**
