### PR TITLE
telco: Run jobs on a specific Telco AWS cluster

### PR DESCRIPTION
**Pull request by sshnaidm**

### CODE REVIEW

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-numaresources-operator-main-ci-e2e

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-numaresources-operator-main-ci-install-e2e

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-numaresources-operator-main-ci-install-e2e

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-numaresources-operator-main-ci-install-e2e

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-numaresources-operator-main-ci-install-e2e

**Comment by jmguzik** [comment]
/pj-rehearse pull-ci-openshift-kni-numaresources-operator-main-ci-e2e

**Comment by jmguzik** [comment]
/pj-rehearse pull-ci-openshift-kni-numaresources-operator-main-ci-install-e2e

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-numaresources-operator-main-ci-install-e2e

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-numaresources-operator-main-ci-install-e2e

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-numaresources-operator-main-ci-e2e

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-node-label-operator-main-ci-e2e pull-ci-openshift-kni-numaresources-operator-main-ci-e2e pull-ci-openshift-kni-numaresources-operator-main-ci-install-e2e pull-ci-openshift-kni-numaresources-operator-release-4.10-ci-e2e

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-node-label-operator-main-ci-e2e pull-ci-openshift-kni-numaresources-operator-main-ci-e2e pull-ci-openshift-kni-numaresources-operator-main-ci-install-e2e pull-ci-openshift-kni-numaresources-operator-release-4.10-ci-e2e

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-numaresources-operator-release-4.10-ci-install-e2e pull-ci-openshift-kni-cnf-features-deploy-release-4.12-e2e-aws-ran-profile pull-ci-openshift-kni-cnf-features-deploy-master-e2e-aws-ran-profile

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-lifecycle-agent-main-integration pull-ci-openshift-kni-mixed-cpu-node-plugin-main-ci-e2e pull-ci-openshift-kni-cluster-group-upgrades-operator-main-integration pull-ci-openshift-kni-cluster-group-upgrades-operator-release-4.14-integration

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-node-label-operator-main-ci-e2e pull-ci-openshift-kni-numaresources-operator-main-ci-e2e pull-ci-openshift-kni-numaresources-operator-main-ci-install-e2e pull-ci-openshift-kni-cluster-group-upgrades-operator-main-integration pull-ci-openshift-kni-mixed-cpu-node-plugin-main-ci-e2e

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-mixed-cpu-node-plugin-main-ci-e2e

**Comment by ffromani** [comment]
/lgtm

numaresources and cnf-features-deploy bits

**Comment by Tal-or** [comment]
/lgtm
/approve 
mixed-cpus-node-plugin bits

**Review by nishant-parekh — APPROVED** [review]
/lgtm

**Review by donpenney — APPROVED** [review]

**Pull request merged**
