### PR TITLE
Remove: deprecate opendatahub-io/odh-manifests and odh-deployer in rhoai

### PR DESCRIPTION
**Pull request by zdtsw**
- [odh-manifests](https://github.com/opendatahub-io/odh-manifests) is not being used, achieved
- [odh-deploy](https://github.com/red-hat-data-services/odh-deployer) is also not in use

### CODE REVIEW

**Comment by zdtsw** [comment]
@VaishnaviHire / @LaVLaS FYI

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

**Comment by VaishnaviHire** [comment]
@zdtsw Lint job is failing for this pr

**Comment by zdtsw** [comment]
> @zdtsw Lint job is failing for this pr

should be fixed

**Comment by zdtsw** [comment]
@LaVLaS / @VaishnaviHire need one more "/lgtm" on this

**Pull request merged**
