### PR TITLE
installer: save AWS instance output as text in teardown

### PR DESCRIPTION
**Pull request by vrutkovs**
Instead of saving a full json artifacts should contain plain text.

See 
https://docs.aws.amazon.com/cli/latest/reference/ec2/get-console-output.html#examples

However atm this would save an empty file for some weird reason

/cc @wking

### CODE REVIEW

**Comment by wking** [comment]
Try touching something meaningless in a 4.2->4.3 update job definition to trigger a rehearsal that shows a broken machine reboot.

**Comment by vrutkovs** [comment]
Implemented in https://github.com/openshift/release/commit/6ec5bf39a6009472fdc1807f6dff8e8341fb90ff

**Pull request closed without merging**
