### PR TITLE
openstack: Skip more jobs

### PR DESCRIPTION
**Pull request by pierreprinetti**
With this change, the Installer presubmits `e2e-openstack-parallel` and
`e2e-openstack-proxy` are run on the same triggers as `e2e-openstack`.

Notably, documentation and UPI changes do not trigger these IPI jobs any
more.

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
/lgtm

**Comment by pierreprinetti** [comment]
@sadasu perhaps?

**Review by mandre — COMMENTED** [review]
/lgtm

**Comment by zaneb** [comment]
The commit message is a bit misleading here, because this will result in far _fewer_ jobs being skipped. Previously these jobs only ran on a change to the openstack platform. after this they'll run on any change except changes to other platforms. I'm not sure that is intended.

**Comment by pierreprinetti** [comment]
> The commit message is a bit misleading here, because this will result in far _fewer_ jobs being skipped. Previously these jobs only ran on a change to the openstack platform. after this they'll run on any change except changes to other platforms. I'm not sure that is intended.

Thank you for your comment. We'll review the workload raise this change is expected to provoke, and see if it's acceptable.

**Comment by sadasu** [comment]
/approve cancel
Until further investigation into what openstack jobs need to run when non-platform installer changes are made.

**Pull request closed without merging**
