### PR TITLE
remove onprem jobs from OCP 4.8

### PR DESCRIPTION
**Pull request by osherdp**
/hold
/cc @YuviGold

### CODE REVIEW

**Review by YuviGold — APPROVED** [review]

**Comment by petr-muller** [comment]
/approve

Approving to allow merge, but ideally someone who knows the following is correct and implies that these jobs can be removed should `/lgtm` this
>tl;dr: we no longer support the behavior of assisted-onprem for 4.8, and 4.6 version is being dropped from the assisted system

**Pull request merged**
