### PR TITLE
Updated search-v2-operator prow configs

### PR DESCRIPTION
**Pull request by dislbenn**
Signed-off-by: dislbenn <dbennett@redhat.com>

### CODE REVIEW

**Comment by SherinV** [comment]
Do we need to remove prow jobs from _prowconfig.yaml file as discussed here? https://redhat-internal.slack.com/archives/CSZLMKPS5/p1674573181028719?thread_ts=1674571903.749829&cid=CSZLMKPS5
@dislbenn @jlpadilla

**Comment by dislbenn** [comment]
> Do we need to remove prow jobs from _prowconfig.yaml file as discussed here? https://redhat-internal.slack.com/archives/CSZLMKPS5/p1674573181028719?thread_ts=1674571903.749829&cid=CSZLMKPS5 @dislbenn @jlpadilla

@SherinV I'm okay with removing it if the branch protection will still be intact. @jlpadilla any opinions? If we remove it from the `_prowconfig.yaml` file, we should update and remove it from the other project's `_prowconfig.yaml` file to remain consistent.

**Review by jlpadilla — APPROVED** [review]
/lgtm

**Review by SherinV — APPROVED** [review]

**Pull request merged**
