### PR TITLE
[StackRox CI:ppc64le] Replace domain name with IP address

### PR DESCRIPTION
**Pull request by mdafsanhossain**
Replaces `cluster.pool.synergyonpower.com` with the IP address of the intermediate host since the DNS record will be deleted.

### CODE REVIEW

**Review by gavin-stackrox — APPROVED** [review]

**Comment by mdafsanhossain** [comment]
/pj-rehearse periodic-ci-stackrox-stackrox-master-daily-powervs-latest-ebpf-qa-e2e-tests

**Pull request merged**
