### PR TITLE
Migrate fips scan job

### PR DESCRIPTION
**Pull request by ashwindasr**
Migrate fips-scan job to where all the other FIPS jobs are, under `fips-check` dir

Thread [here](https://redhat-internal.slack.com/archives/C05U13J3LLS/p1718739657136919?thread_ts=1715954957.336589&cid=C05U13J3LLS)

### CODE REVIEW

**Comment by ashwindasr** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-fips-payload-scan

**Comment by ashwindasr** [comment]
`
---- Successful run with warnings
`
/pj-rehearse ack

**Review by bradmwilliams — APPROVED** [review]

**Pull request merged**
