### PR TITLE
repos: Remove now unused RHEL 8.3 repo

### PR DESCRIPTION
**Pull request by travier**
RHCOS 4.7 was the last consumer of RHEL 8.3 and it has now moved to 8.4.

Deployments updated with:
```
$ ./hack/generators/release-controllers/generate-release-controllers.py .
```

### CODE REVIEW

**Comment by travier** [comment]
Waiting on https://github.com/openshift/os/pull/558

**Comment by travier** [comment]
Ready for review

**Comment by alvaroaleman** [comment]
I don't know anything about this, sorry.
/assign @jupierce

**Comment by travier** [comment]
Ping here. Could we get an approval for this one?

**Comment by sosiouxme** [comment]
only approver in clusters/build-clusters/common/OWNERS is `dptp` which I don't think is legit. @jupierce maybe slap a label on this?

4.7 no longer pinned to 8.3

**Pull request merged**
