### PR TITLE
Bug 1892472: Add unit-tests and linter jobs to master branch

### PR DESCRIPTION
**Pull request by abhat**
This commit adds unit-test, linter, and gofmt jobs to the CI.

### CODE REVIEW

**Comment by abhat** [comment]
/hold
wait for the unit-tests to be able to run without sudo access.

**Comment by alexanderConstantinescu** [comment]
@abhat : ovn-kubernetes 4.6 is broken again for `make check`. PR: https://github.com/openshift/ovn-kubernetes/pull/389 broke us. Could you please try to get this in ASAP? I will take care of fixing the broken build again.

**Comment by abhat** [comment]
After openshift/ovn-kubernetes#428 lands, the lint and unit targets should start passing.

**Pull request closed without merging**
