### PR TITLE
[4.11] Bump ci-operator configs and some infra jobs

### PR DESCRIPTION
**Pull request by petr-muller**
- [4.11] Stop propagating ci-operator config changes to 4.10
- [4.11] Stop fast-forwarding code to 4.10
- [4.11] Bugs on PRs to main branch must target 4.11
- [4.11] Bump ci-operator configs
- [4.11] `make update`

The commit bumping ci-operator config should be refreshed at the time of the
code freeze:

```console
$ config-brancher --config-dir ../release/ci-operator/config \
  --current-release=4.10 \
  --future-release=4.11  \
  --bump-release=4.11 \
  --confirm
```

### CODE REVIEW

**Comment by petr-muller** [comment]
/hold

Needs to wait for 4.11 development open

**Review by hongkailiu — APPROVED** [review]

**Comment by petr-muller** [comment]
Merged this with a bot

**Pull request merged**
