### PR TITLE
cluster-autoscaler-operator: add periodic job

### PR DESCRIPTION
**Pull request by paulfantom**
Periodically run e2e tests on cluster-autoscaler-operator.

### CODE REVIEW

**Comment by enxebre** [comment]
how does this affect the repo workflow? does it block? where can this be visualised? does it notify when it fails?

**Comment by paulfantom** [comment]
> how does this affect the repo workflow?

it doesn't

> does it block?

no

> where can this be visualised?

here: https://deck-ci.svc.ci.openshift.org/?repo=openshift%2Fcluster-autoscaler-operator&type=periodic

> does it notify when it fails?

no

**Comment by frobware** [comment]
> does it notify when it fails?

I think aos-cloud should be notified when this fails. Or into the slack channel. Either way, we want the presence of failures "in our face" - not something we have to remember to poll for.

**Comment by paulfantom** [comment]
> I think aos-cloud should be notified when this fails. Or into the slack channel. Either way, we want the presence of failures "in our face" - not something we have to remember to poll for.

There is no such feature available.

**Pull request merged**
