### PR TITLE
OCPQE-21261 - adding snyk tests on presubmits

### PR DESCRIPTION
**Pull request by miyadav**
Adding security scans for presubmits on following repos  mentioned in Jira and other details - `OCPQE-21261`

@elmiko  @damdo @JoelSpeed @shellyyang1989 @sunzhaohua2 @huali9 PTAL.

### CODE REVIEW

**Comment by miyadav** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-gcp-master-security

**Comment by JoelSpeed** [comment]
How much work do we think will be needed to make these tests go green? I thought we had fairly good snyk configs ignoring most false positives already?

**Comment by miyadav** [comment]
> How much work do we think will be needed to make these tests go green? I thought we had fairly good snyk configs ignoring most false positives already?

Not much , if it works , I can mark them as false and then , from this point on, only new commits will give us the issues if any .
I can go ahead and do that , then we can start comparing .

**Comment by miyadav** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-vsphere-master-security

**Pull request merged**
