### PR TITLE
cert-rotation: collect sos report and other data after time skew

### PR DESCRIPTION
**Pull request by vrutkovs**
After time skew in cert rotation tests gather-* steps are useless, as kubeconfig in shared dir is no longer valid. Node data should be collected using a separate step.

TODO:
* [x] collect SOS report to get network / container logs
* [x] dump /etc/kubeconfig from each node
* [x] compose a valid kubeconfig using control-plane certs from kube-apiserver container on first master and get a list of nodes / csrs / CO status

### CODE REVIEW

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-180d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-180d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-180d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-180d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-180d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-180d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-180d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-180d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-180d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-180d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-180d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-180d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-180d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-180d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-180d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-180d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-180d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-180d

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Pull request merged**
