### PR TITLE
Hypershift: Re-Add junit to e2e presubmit and make output more legible

### PR DESCRIPTION
**Pull request by alvaroaleman**
Produces and output that looks like this:
```
$ gotestsum  --format=standard-verbose --raw-command  --junitfile=/tmp/junit.xml -- go tool test2json -t  ./install.test -test.v
=== RUN   TestMultiDocYamlRendering
--- PASS: TestMultiDocYamlRendering (0.27s)
=== RUN   TestTemplateYamlRendering
--- PASS: TestTemplateYamlRendering (0.31s)
=== RUN   TestJsonListRendering
--- PASS: TestJsonListRendering (0.14s)
=== RUN   TestJsonTemplateRendering
--- PASS: TestJsonTemplateRendering (0.17s)
=== RUN   TestOptions_Validate
=== RUN   TestOptions_Validate/when_empty_private_platform_is_specified_it_errors
=== RUN   TestOptions_Validate/when_partially_specified_oauth_creds_used_(OIDCStorageProviderS3Credentials)_it_errors
=== RUN   TestOptions_Validate/when_partially_specified_oauth_creds_used_(OIDCStorageProviderS3CredentialsSecret)_it_errors
=== RUN   TestOptions_Validate/when_all_data_specified_there_is_no_error
=== RUN   TestOptions_Validate/when_aws_private_platform_without_private_creds_and_region_it_errors
--- PASS: TestOptions_Validate (0.00s)
    --- PASS: TestOptions_Validate/when_empty_private_platform_is_specified_it_errors (0.00s)
    --- PASS: TestOptions_Validate/when_partially_specified_oauth_creds_used_(OIDCStorageProviderS3Credentials)_it_errors (0.00s)
    --- PASS: TestOptions_Validate/when_partially_specified_oauth_creds_used_(OIDCStorageProviderS3CredentialsSecret)_it_errors (0.00s)
    --- PASS: TestOptions_Validate/when_all_data_specified_there_is_no_error (0.00s)
    --- PASS: TestOptions_Validate/when_aws_private_platform_without_private_creds_and_region_it_errors (0.00s)
PASS

DONE 10 tests in 0.916s
```

All other format options seem to only print `ok` and a duration if there
were no failures.

### CODE REVIEW

**Comment by sjenning** [comment]
waiting for artifacts this time :smile: 
/hold

**Comment by alvaroaleman** [comment]
There is now junit and the test output is present again: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/26372/rehearse-26372-pull-ci-openshift-hypershift-main-e2e-aws/1494365227506995200/artifacts/e2e-aws/test-e2e/build-log.txt
/hold cancel
@sjenning mind stamping?

**Comment by sjenning** [comment]
nice
/hold cancel

**Pull request merged**
