### PR TITLE
Add openshift/cloud-provider-azure repository

### PR DESCRIPTION
**Pull request by lobziik**
CI integration for https://github.com/openshift/cloud-provider-azure
  
- Add Azure CCM and node manager images build tasks in CI
- Enable unit-tests for cloud-provider-azure

### CODE REVIEW

**Review by petr-muller — APPROVED** [review]
LGTM but needs rebase

**Review by elmiko — APPROVED** [review]
/lgtm

**Comment by lobziik** [comment]
rebased

**Pull request merged**
