### PR TITLE
[knative-client] Add CI setup for release v0.25.1

### PR DESCRIPTION
**Pull request by dsimansk**
Per title.

/cc @rhuss @vyasgun

### CODE REVIEW

**Review by vyasgun — COMMENTED** [review]
/lgtm

**Comment by dsimansk** [comment]
Since the PR is touching image mirroring, could you please take a look? To have client updated sooner then few days before cut. :)

@markusthoemmes @matzew

**Review by rhuss — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
