### PR TITLE
ovn-kubernetes: add CI to release-4.5, bump to go-1.13

### PR DESCRIPTION
**Pull request by squeed**
Somehow it was missing.

### CODE REVIEW

**Comment by danwinship** [comment]
why are those not generated from `config/openshift/ovn-kubernetes/` ?
also, golang version fixes should be a separate commit

**Comment by squeed** [comment]
> why are those not generated from `config/openshift/ovn-kubernetes/` ?

Because we've never had autogenerated gcp-ovn and aws-ovn jobs, and I just want 4.5 to look like 4.6 and master. I've filed a separate jira card to make that the case.

**Comment by dcbw** [comment]
`  * could not run steps: step e2e-aws-ovn failed: failed to acquire lease: status 503 Service Unavailable, status code 503`

/retest

**Comment by dcbw** [comment]
@squeed I thought that, up until May 31, master was force-synced to 4.5 across all of openshift. Then June 1 master got moved to 4.6 but I assume that the 4.5 branch would still be whatever was in master as of May 31. Or is openshift/release just different?

**Comment by danwinship** [comment]
> I thought that, up until May 31, master was force-synced to 4.5 across all of openshift. Then June 1 master got moved to 4.6 but I assume that the 4.5 branch would still be whatever was in master as of May 31. Or is openshift/release just different?

openshift/release doesn't use branches, it just has separate explicit config files for each release in the master branch, and AIUI there's no automatic syncing between them.

**Pull request merged**
