### PR TITLE
USHIFT-958: Add conformance reduced presubmits

### PR DESCRIPTION
**Pull request by pacevedom**

### CODE REVIEW

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-ocp-conformance-reduced

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-ocp-conformance-reduced

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-ocp-conformance-reduced

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-ocp-conformance-reduced

**Comment by copejon** [comment]
Looks like the failed tests are expecting some of the APIs MicroShift doesn't support

```
  Sep  8 14:36:14.663: INFO: Error building cluster data: the server could not find the requested resource (get infrastructures.config.openshift.io cluster)
  Sep  8 14:36:14.663: INFO: Error building cluster data: the server could not find the requested resource (get networks.config.openshift.io cluster)
  Sep  8 14:36:14.663: INFO: Error building cluster data: the server could not find the requested resource (get clusterversions.config.openshift.io)
````

**Comment by pacevedom** [comment]
> Looks like the failed tests are expecting some of the APIs MicroShift doesn't support
> 
> ```
>   Sep  8 14:36:14.663: INFO: Error building cluster data: the server could not find the requested resource (get infrastructures.config.openshift.io cluster)
>   Sep  8 14:36:14.663: INFO: Error building cluster data: the server could not find the requested resource (get networks.config.openshift.io cluster)
>   Sep  8 14:36:14.663: INFO: Error building cluster data: the server could not find the requested resource (get clusterversions.config.openshift.io)
> ```

Which ones? I am seeing this which is not related to the tests, at first:
```
"ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (Protocol error)\n"
```

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-ocp-conformance-reduced

**Comment by copejon** [comment]
Weird. Going to run this again to see if the problem recurs.  If it passes, I'll lgtm it.


/pj-rehearse pull-ci-openshift-microshift-main-ocp-conformance-reduced

**Pull request closed without merging**
