### PR TITLE
Updated observability projects to build on 2.6

### PR DESCRIPTION
**Pull request by dislbenn**
Related issue: https://github.com/stolostron/backlog/issues/22894
Signed-off-by: dislbenn <dbennett@redhat.com>

### CODE REVIEW

**Comment by dislbenn** [comment]
@haoqing0110 @songleo can you help to approve? It seems that your approvals are needed also.

**Review by haoqing0110 — APPROVED** [review]
/lgtm
/approve

**Review by songleo — APPROVED** [review]

**Pull request merged**
