### PR TITLE
[INTEROP-7527] OCP 4.18 expansion for GitOps 1.14 lp-interop.

### PR DESCRIPTION
**Pull request by dfrazzette**
Include OCP 4.18 FIPS-enabled testing (although not currently supported for GitOps). Also add default Jira assignee.

### CODE REVIEW

**Comment by dfrazzette** [comment]
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-v1.14-gitops-ocp4.18-lp-interop-redhat-openshift-gitops-interop-aws

**Comment by dfrazzette** [comment]
Rehearsal job [1843135109335617536](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/57507/rehearse-57507-periodic-ci-redhat-developer-gitops-operator-v1.14-gitops-ocp4.18-lp-interop-redhat-openshift-gitops-interop-aws/1843135109335617536) passed. GitOps does not currently support FIPS, so no FIPS-enabled rehearsal run.

**Review by Simranpal — APPROVED** [review]
/lgtm

**Pull request merged**
