### PR TITLE
[CRC] update crc integration test

### PR DESCRIPTION
**Pull request by lilyLuLiu**
As CRC integration test have been modified that execute with parameters.  The script for CRC integration test. also need to be update.

### CODE REVIEW

**Comment by praveenkumar** [comment]
@lilyLuLiu Does that mean those variable now not used as part of test? Can you mention in the commit logs?

**Comment by praveenkumar** [comment]
@lilyLuLiu better to rebase with master and again push it to have CI green

**Comment by praveenkumar** [comment]
This test is failing because we are providing the bundle which is openshift one and fails for microshift.

**Comment by praveenkumar** [comment]
@lilyLuLiu let's try with `/tmp/integration.test --pull-secret-path="${HOME}"/pull-secret` without the `bundle` so it pull from release.

**Comment by lilyLuLiu** [comment]
@praveenkumar , yeah, we can leave the `bundle-path` empty to solve the issue. One question: Do we have to test a specific bundle version for this test?

**Comment by praveenkumar** [comment]
> @praveenkumar , yeah, we can leave the `bundle-path` empty to solve the issue. One question: Do we have to test a specific bundle version for this test? If not, I think we can remove all the `bundle-path` related code.

Not for our CI, but it is used for internal pipeline so better to have it there in the code but remove the `bundle-path` in here.

**Comment by lilyLuLiu** [comment]
@praveenkumar , Hi, All the checks of this PR have passed. Could you help review and merge this PR?

**Comment by praveenkumar** [comment]
@lilyLuLiu Added all required labels, hopefully it will be soon merged.

**Pull request merged**
