### PR TITLE
Remove csi-driver-registrar jobs

### PR DESCRIPTION
**Pull request by jsafrane**
csi-driver-registrar is replaced by csi-node-driver-registrar and
csi-cluster-driver-registrar in 4.2.

I hope it's the right way to remove the image from OKD 4.2 and keep it in 4.1.

Slightly related to https://github.com/openshift/release/pull/4080

/assign @smarterclayton

### CODE REVIEW

**Comment by jsafrane** [comment]
Rebased
@smarterclayton, PTAL

**Comment by smarterclayton** [comment]
Before we merge make sure no other operator is referencing these in "image-references".  You can run `oc adm release extract --to=/tmp/dir <42_recent_release>` to disk and look for them.  Once you've done that we can merge and remove.

Is there a corresponding ocp-build-data change for this?

**Comment by jsafrane** [comment]
> You can run oc adm release extract --to=/tmp/dir <42_recent_release> to disk

Tested with today's 4.2.0-0.okd-2019-07-24-124505, no release manifest references csi-driver-registrar image.

**Comment by jsafrane** [comment]
> Is there a corresponding ocp-build-data change for this?

https://gitlab.cee.redhat.com/openshift-art/ocp-build-data/commit/947e995f77cc7142780eff987f5b65ee9b126d38

**Comment by smarterclayton** [comment]
You intended to remove the registrar from 4.1?  Only remove that ci-operator file if registrar should never have been in 4.1 (otherwise, if it's still supposed to be there leave the release-4.1 file)

**Comment by jsafrane** [comment]
I restored 4.1, but I think we did not ship the registrar in OCP. OKD shipped it, but IMO it was an accident. Nothing in CI nor CVO / OLM uses it.

**Comment by smarterclayton** [comment]
If it's not shipped in OCP, and no need to have it in OKD, you *can* remove the branch and then I'll delete the image.  Generally once we ship, pruning OKD is beneficial so we don't have accidents.

**Pull request merged**
