### PR TITLE
Fix OCP OBO compatiblity job

### PR DESCRIPTION
**Pull request by lihongyan1**
Updating go version and upgrade OCP to 4.16 at the same time
fix issue [COO-146](https://issues.redhat.com/browse/COO-146) obo compat job keep failing

### CODE REVIEW

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-416-compat

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-e2e-test-harness

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-416-compat

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-e2e-test-harness

**Comment by jan--f** [comment]
The test harness fails with
```
Failed to set up or retrieve cluster: could not launch cluster: create cluster failed: region check failed: region list failed: error: failed to wait for command to finish: exit status 1, stderr: ERR: Failed to fetch regions: Error creating AWS client: Invalid AWS Credentials: operation error STS: GetCallerIdentity, exceeded maximum number of attempts, 12, https response error StatusCode: 403, RequestID: 8128d005-bd61-4f07-b848-dac413a9af97, api error InvalidClientTokenId: The security token included in the request is invalid..
```

**Pull request merged**
