### PR TITLE
Setup CI job for Tektoncd Pipeline release v0.5.2

### PR DESCRIPTION
**Pull request by khrm**
/cc @chmouel  @sthaha @vdemeester

Signed-off-by: Khurram Baig kbaig@redhat.com

### CODE REVIEW

**Comment by hrishin** [comment]
@khrm wondering, we may need to add image mirror job as well? like this [mapping](https://github.com/openshift/release/tree/master/core-services/image-mirroring/tekton)

**Comment by khrm** [comment]
@petr-muller Do we have to setup mapping for mirror image [here](https://github.com/openshift/release/tree/master/core-services/image-mirroring/tekton)?

**Comment by vdemeester** [comment]
@khrm @hrishin we just have to open a PR adding a new file for 0.5.x (`mapping_tekton_v0_5_quay`) :wink:

**Pull request merged**
