### PR TITLE
Fix validator, add some new checks

### PR DESCRIPTION
**Pull request by stevekuznetsov**
/assign @petr-muller

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
needs migration:

```
bazel run //maintenance/migratestatus -- --org tnozicka --repo openshift-acme --move ci/prow/e2e --dest ci/prow/tnozicka-openshift-acme-e2e --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo image-registry --move ci/prow/e2e --dest ci/prow/e2e-gcp --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo image-registry --move ci/prow/e2e --dest ci/prow/e2e-gcp --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo origin --move ci/prow/gcp-serial --dest ci/prow/e2e-gcp-serial --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo origin --move ci/prow/gcp-crio --dest ci/prow/e2e-gcp-crio --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo origin --move ci/prow/conformance-k8s --dest ci/prow/e2e-conformance-k8s --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo origin --move ci/prow/conformance-k8s --dest ci/prow/e2e-conformance-k8s --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo origin --move ci/prow/gcp-crio --dest ci/prow/e2e-gcp-crio --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo origin --move ci/prow/launch-gcp --dest ci/prow/e2e-gcp-launch --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo origin --move ci/prow/cross --dest ci/prow/artifacts --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo origin --move ci/prow/gcp --dest ci/prow/e2e-gcp --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo origin --move ci/prow/conformance-k8s --dest ci/prow/e2e-conformance-k8s --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo origin --move ci/prow/cross --dest ci/prow/artifacts --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo origin --move ci/prow/launch-gcp --dest ci/prow/e2e-gcp-launch --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo origin --move ci/prow/gcp --dest ci/prow/e2e-gcp --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo openshift-ansible --move ci/prow/gcp-crio --dest ci/prow/e2e-gcp-crio --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo openshift-ansible --move ci/prow/launch-gcp --dest ci/prow/e2e-gcp-launch --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo openshift-ansible --move ci/prow/gcp --dest ci/prow/e2e-gcp --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo openshift-ansible --move ci/prow/launch-gcp --dest ci/prow/e2e-gcp-launch --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo openshift-ansible --move ci/prow/gcp-ha --dest ci/prow/e2e-gcp-ha --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo openshift-ansible --move ci/prow/gcp-ha --dest ci/prow/e2e-gcp-ha --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo openshift-ansible --move ci/prow/gcp --dest ci/prow/e2e-gcp --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo openshift-ansible --move ci/prow/gcp-crio --dest ci/prow/e2e-gcp-crio --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo openshift-ansible --move ci/prow/gcp-major-upgrade --dest ci/prow/e2e-gcp-major-upgrade-master --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo origin-web-console-server --move ci/prow/e2e --dest ci/prow/e2e-gcp --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo origin-web-console-server --move ci/prow/e2e --dest ci/prow/e2e-gcp --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo builder --move ci/prow/gcp-crio --dest ci/prow/e2e-gcp-crio --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo builder --move ci/prow/gcp --dest ci/prow/e2e-gcp --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo jenkins --move ci/prow/e2e --dest ci/prow/e2e-gcp --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo jenkins --move ci/prow/e2e --dest ci/prow/e2e-gcp --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
bazel run //maintenance/migratestatus -- --org openshift --repo jenkins --move ci/prow/e2e --dest ci/prow/e2e-gcp --dry-run=false --continue-on-error --logtostderr --token /tmp/token.txt --continue-on-error
```

**Comment by petr-muller** [comment]
/lgtm
/hold

(hold because the migration need)

**Comment by stevekuznetsov** [comment]
I had some `bazel` issues and could not run migration earlier today

**Comment by stevekuznetsov** [comment]
Ran the migrations, will merge now

**Pull request merged**
