### PR TITLE
Include OKD config in branching automation

### PR DESCRIPTION
**Pull request by petr-muller**
- Execute: `config-brancher`
- Execute: `make jobs`
- Carry over manual modifications to OKD jobs
- `prowgen`
- `make openshift-image-mirror-mappings`

This is a followup to https://github.com/openshift/ci-tools/pull/2641 which modifies the tooling to include OKD config files in branching automation. Some checks are expected to fail until https://github.com/openshift/ci-tools/pull/2641 merges and we get new images that implement the necessary functionality.

/hold

### CODE REVIEW

**Comment by petr-muller** [comment]
/cc @vrutkovs @LorbusChris 

Could you eyeball this PR for sanity? Hopefully the https://github.com/openshift/ci-tools/pull/2641 change in the tooling should result in better automation for OKD CI config.

**Comment by vrutkovs** [comment]
Looks good at a glance, brilliant work
`generated-config` wants to remove `- --target=[release:latest]` though

**Comment by petr-muller** [comment]
That's fine, that's because the check runs with pre-https://github.com/openshift/ci-tools/pull/2641 code. After the ci-tools change merges, this check will pass and allow this PR to merrge.

**Comment by LorbusChris** [comment]
Thanks for working on this, @petr-muller! Looks sane to me.

**Pull request merged**
