### PR TITLE
Fixing data path test bugs

### PR DESCRIPTION
**Pull request by vishnuchalla**
### Description
Bug fixes for data path tests here: https://github.com/cloud-bulldozer/e2e-benchmarking/pull/681
Mostly due to configuration errors.

### Testing
Tested and verified in an hacky way with these two jobs
* https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/48920/rehearse-48920-pull-ci-cloud-bulldozer-e2e-benchmarking-master-e2e-ingress-perf-single-node/1759071812420898816
* https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/48920/rehearse-48920-pull-ci-cloud-bulldozer-e2e-benchmarking-master-e2e-network-smoke-single-node/1759031210517991424

### CODE REVIEW

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-cloud-bulldozer-e2e-benchmarking-master-e2e-network-smoke-single-node	
/pj-rehearse pull-ci-cloud-bulldozer-e2e-benchmarking-master-e2e-ingress-perf-single-node

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-cloud-bulldozer-e2e-benchmarking-master-e2e-ingress-perf-single-node

**Review by krishvoor — APPROVED** [review]
/lgtm

**Pull request merged**
