### PR TITLE
MAO: Skip e2e jobs on a change only for docs

### PR DESCRIPTION
**Pull request by Fedosin**
Added skip_if_only_changed: ^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$ for appropriate e2e jobs.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Do we have a link to the docs that suggest this is the standard pattern for doing this? Would be nice to add to the PR description if we have one handy

**Comment by Fedosin** [comment]
I don't think there is an official recommendation for this pattern. But it's used by MCO, CCO, CCCMO, Image Registry Operator, Installer, Hive and many other OpenShift projects. So I think it's safe to use it for MAO as well.

**Review by alexander-demichev — APPROVED** [review]
/lgtm

**Pull request merged**
