### PR TITLE
Add Go 1.22 builder

### PR DESCRIPTION
**Pull request by tpantelis**

### CODE REVIEW

**Comment by skitt** [comment]
@tpantelis could you split out the `image-builder` part into a separate PR? It needs to go in first, then https://github.com/stolostron/image-builder/pull/138, and only after that will we be able to update the addon configuration.

**Comment by tpantelis** [comment]
> @tpantelis could you split out the `image-builder` part into a separate PR? It needs to go in first, then [stolostron/image-builder#138](https://github.com/stolostron/image-builder/pull/138), and only after that will we be able to update the addon configuration.

yeah I was wondering about that. I thought I'd first try to combine them 😄

**Review by gurnben — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
