### PR TITLE
Fix e2e crc checks

### PR DESCRIPTION
**Pull request by praveenkumar**

### CODE REVIEW

**Comment by staebler** [comment]
@praveenkumar Can you provide a link to a job history that shows that this test is passing consistently? The [history](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/rehearse-15522-pull-ci-openshift-installer-master-e2e-crc) for this PR shows only a single recent success and not a consistency of success.

**Comment by praveenkumar** [comment]
@staebler I can add retest on this PR multiple time to create successful history for the job if that works for you and then you can approve it tomorrow?

**Comment by praveenkumar** [comment]
@staebler Now we have some stats, can we take this in now?

**Review by staebler — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
