### PR TITLE
Add long duration Azure Mag job for Hive

### PR DESCRIPTION
**Pull request by fxierh**
Hive supports MAG (Microsoft Azure Government) in addition to MAC (Microsoft Azure Commercial). 
This PR adds a long-duration MAG job for Hive.

### CODE REVIEW

**Comment by fxierh** [comment]
@jianping-shu All existing MAG test cases passed :)

**Comment by fxierh** [comment]
@liangxia Would you please take a look ? Thanks !

**Comment by liangxia** [comment]
Waiting for feature team's review.

**Pull request merged**
