### PR TITLE
hypershift: KubeVirt-HyperShift-guest

### PR DESCRIPTION
**Pull request by LiangquanLi930**
https://issues.redhat.com/browse/OCPQE-13743

### CODE REVIEW

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-ipi-ovn-kubevirt-hypershift-guest-p3-f21

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-ipi-ovn-kubevirt-hypershift-guest-p3-f21

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-ipi-ovn-kubevirt-hypershift-guest-p3-f21

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-ipi-ovn-kubevirt-hypershift-guest-p3-f21

**Comment by LiangquanLi930** [comment]
@kuiwang02 @liangxia Could you help to review this PR? thanks

**Comment by kuiwang02** [comment]
iamok from golang's view

**Pull request merged**
