### PR TITLE
OCM-9126 | TestOnly: Trigger rosacli regression testing for v1.2.42-rc1

### PR DESCRIPTION
**Pull request by radtriste**

### CODE REVIEW

**Comment by radtriste** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-non-sts-advanced-critical-high-f3 periodic-ci-openshift-rosa-master-e2e-rosa-sts-advanced-critical-high-f3 periodic-ci-openshift-rosa-master-e2e-rosa-hcp-advanced-critical-high-f3

**Comment by radtriste** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-hcp-advanced-critical-high-f3

**Comment by radtriste** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-sts-private-link-critical-high-f3 periodic-ci-openshift-rosa-master-e2e-rosa-hcp-external-auth-critical-high-f3 periodic-ci-openshift-rosa-master-e2e-rosa-hcp-private-link-critical-high-f3

**Comment by radtriste** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-hcp-external-auth-medium-low-f7 periodic-ci-openshift-rosa-master-e2e-rosa-sts-advanced-medium-low-f7 periodic-ci-openshift-rosa-master-e2e-rosa-sts-private-link-medium-low-f7 periodic-ci-openshift-rosa-master-e2e-rosa-hcp-advanced-medium-low-f7

**Comment by radtriste** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-ocm-resources-f3 periodic-ci-openshift-rosa-master-e2e-rosa-day1-negative-f7 periodic-ci-openshift-rosa-master-e2e-rosa-day1-supplemental-f3

**Comment by radtriste** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-sts-upgrade-z-stream-f3  periodic-ci-openshift-rosa-master-e2e-rosa-sts-upgrade-y-stream-f3  periodic-ci-openshift-rosa-master-e2e-rosa-hcp-upgrade-z-stream-f3  periodic-ci-openshift-rosa-master-e2e-rosa-hcp-upgrade-y-stream-f3

**Comment by radtriste** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-hcp-external-auth-medium-low-f7

**Comment by radtriste** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-hcp-private-link-critical-high-f3

**Comment by radtriste** [comment]
## Results investigation

- [periodic-ci-openshift-rosa-master-e2e-rosa-hcp-external-auth-medium-low-f7](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/54100/rehearse-54100-periodic-ci-openshift-rosa-master-e2e-rosa-hcp-external-auth-medium-low-f7/1810320462886998016)
	- cilium issue ?
	- **restarted**
- [periodic-ci-openshift-rosa-master-e2e-rosa-hcp-external-auth-critical-high-f3](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/54100/rehearse-54100-periodic-ci-openshift-rosa-master-e2e-rosa-hcp-external-auth-critical-high-f3/1810315631111704576)
	- cilium issue ?
	- **restarted**
- [periodic-ci-openshift-rosa-master-e2e-rosa-sts-private-link-critical-high-f3](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/54100/rehearse-54100-periodic-ci-openshift-rosa-master-e2e-rosa-sts-private-link-critical-high-f3/1810315628515430400)
	- id:55979
		- `ERR: Expected a valid instance type: Machine type 'm5.xlarge' not found in availability zones 'us-east-1-atl-1a' for region: 'us-east-1'`
- [periodic-ci-openshift-rosa-master-e2e-rosa-day1-supplemental-f3](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/54100/rehearse-54100-periodic-ci-openshift-rosa-master-e2e-rosa-day1-supplemental-f3/1810576986737741824)
	- id:71329
		- Missing the `enable-autoscaling` into the `GenerateClusterCreateFlags` method when using `profile.AutoscalerEnabled`
- [periodic-ci-openshift-rosa-master-e2e-rosa-hcp-upgrade-y-stream-f3](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/54100/rehearse-54100-periodic-ci-openshift-rosa-master-e2e-rosa-hcp-upgrade-y-stream-f3/1810576969721450496)
	- Issue with getting the y-1 version (known issue)
- [periodic-ci-openshift-rosa-master-e2e-rosa-hcp-upgrade-z-stream-f3](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/54100/rehearse-54100-periodic-ci-openshift-rosa-master-e2e-rosa-hcp-upgrade-z-stream-f3/1810576969666924544)
	- Issue with getting the z-1 version (known issue)
- [periodic-ci-openshift-rosa-master-e2e-rosa-hcp-advanced-medium-low-f7](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/54100/rehearse-54100-periodic-ci-openshift-rosa-master-e2e-rosa-hcp-advanced-medium-low-f7/1810320463096713216)
	- id:65160 Issue in cli output ?
- [periodic-ci-openshift-rosa-master-e2e-rosa-hcp-private-link-critical-high-f3](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/54100/rehearse-54100-periodic-ci-openshift-rosa-master-e2e-rosa-hcp-private-link-critical-high-f3/1810315634391650304)
	- Timeout creating cluster
	- **Restarted**
- [periodic-ci-openshift-rosa-master-e2e-rosa-sts-upgrade-y-stream-f3](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/54100/rehearse-54100-periodic-ci-openshift-rosa-master-e2e-rosa-sts-upgrade-y-stream-f3/1810576969616592896)
	- id:73731
- [periodic-ci-openshift-rosa-master-e2e-rosa-ocm-resources-f3](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/54100/rehearse-54100-periodic-ci-openshift-rosa-master-e2e-rosa-ocm-resources-f3/1810576986662244352)
	- id:73743
		- Expected as we run from master ... Version displayed is ok. Failure can be ignored
	- id:59551
		- Fixed and tested ok
	- id:74661
		- Destructive action only, not OCMResources Runtime as it needs Cluster
	- id:60971
		- flaky issue ?
		- To investigate further
	- id:64620
		- CI issue
		- `ERR: There was a problem saving private key to a file: open rosa-private-key-ocp64620oc-oidc-j3t8.key: permission denied`
	- id:72162
		- CI issue. Passed locally.
		- `waiting for [base64 -D]: exit status 1`
		- `base64` is not present IMO
- [periodic-ci-openshift-rosa-master-e2e-rosa-hcp-advanced-critical-high-f3](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/54100/rehearse-54100-periodic-ci-openshift-rosa-master-e2e-rosa-hcp-advanced-critical-high-f3/1810315192572055552)
	- id:64917
	- id:49137
		- CLI output issue. Console may not be available yet during testing
	- id:53031
		- CLI output issue. Console may not be available yet during testing
	- id:61138
		- Looks like a flaky issue. I was able to create one
- [periodic-ci-openshift-rosa-master-e2e-rosa-day1-negative-f7](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/54100/rehearse-54100-periodic-ci-openshift-rosa-master-e2e-rosa-day1-negative-f7/1810576986683215872)
	- id:38770
		- Missing the `enable-autoscheduling` into the `GenerateClusterCreateFlags` method when using `profile.AutoscalerEnabled
	- id:73725
		- Random profile chose the rosa-hcp-up profile, thus failing
	- id:72657
		- Random profile chose the rosa-hcp-up profile, thus failing
	- id:70970
		- `ERR: No valid billing account associated.`
		- Not sure what is wrong there ...
	- id:73755
		- Random profile chose the rosa-hcp-up profile, thus failing

**Comment by radtriste** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-hcp-external-auth-medium-low-f7 periodic-ci-openshift-rosa-master-e2e-rosa-hcp-external-auth-critical-high-f3 periodic-ci-openshift-rosa-master-e2e-rosa-sts-private-link-critical-high-f3 periodic-ci-openshift-rosa-master-e2e-rosa-day1-supplemental-f3 periodic-ci-openshift-rosa-master-e2e-rosa-hcp-upgrade-y-stream-f3 periodic-ci-openshift-rosa-master-e2e-rosa-hcp-upgrade-z-stream-f3 periodic-ci-openshift-rosa-master-e2e-rosa-hcp-advanced-medium-low-f7 periodic-ci-openshift-rosa-master-e2e-rosa-hcp-private-link-critical-high-f3 periodic-ci-openshift-rosa-master-e2e-rosa-sts-upgrade-y-stream-f3 periodic-ci-openshift-rosa-master-e2e-rosa-ocm-resources-f3 periodic-ci-openshift-rosa-master-e2e-rosa-hcp-advanced-critical-high-f3 periodic-ci-openshift-rosa-master-e2e-rosa-day1-negative-f7

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-hcp-advanced-critical-high-f3

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-hcp-advanced-critical-high-f3

**Comment by radtriste** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-hcp-external-auth-critical-high-f3

**Comment by radtriste** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-hcp-upgrade-y-stream-f3

**Comment by radtriste** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-day1-negative-f7

**Comment by radtriste** [comment]
Restarted
ci/rehearse/periodic-ci-openshift-rosa-master-e2e-rosa-hcp-advanced-medium-low-f7 (proxy issue)
ci/rehearse/periodic-ci-openshift-rosa-master-e2e-rosa-hcp-external-auth-medium-low-f7 (proxy issue)
ci/rehearse/periodic-ci-openshift-rosa-master-e2e-rosa-hcp-external-auth-critical-high-f3 (proxy issue)
ci/rehearse/periodic-ci-openshift-rosa-master-e2e-rosa-hcp-upgrade-y-stream-f3 (roles issue)
ci/rehearse/periodic-ci-openshift-rosa-master-e2e-rosa-day1-negative-f7 (billing account issue)


Investigated
ci/rehearse/periodic-ci-openshift-rosa-master-e2e-rosa-hcp-advanced-critical-high-f3 -> ok
	Network verifier issue -> Occurs also on master. Does not seem related to the CLI

ci/rehearse/periodic-ci-openshift-rosa-master-e2e-rosa-sts-private-link-critical-high-f3 -> ok
	57102 -> Related to https://github.com/openshift/rosa/pull/2228 (merged post cut-off), can be ignored
	55979 -> Related to https://github.com/openshift/rosa/pull/2232 (merged post cut-off), can be ignored
	
ci/rehearse/periodic-ci-openshift-rosa-master-e2e-rosa-ocm-resources-f3
	72162
		CI issue. Passed locally.
	64620
		OCM roles issue. Need parallel investigaiton. Not blocking
	59551
		Quota issue. Working locally
	73743
		Expected as we run from master ... Version displayed is ok. Failure can be ignored
	44511
		OCM roles issue. Need parallel investigaiton. Not blocking

ci/rehearse/periodic-ci-openshift-rosa-master-e2e-rosa-day1-supplemental-f3
	OCM account roles issue. Need parallel investigaiton. Not blocking

**Comment by radtriste** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-hcp-advanced-medium-low-f7

**Comment by radtriste** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-hcp-external-auth-medium-low-f7 periodic-ci-openshift-rosa-master-e2e-rosa-hcp-external-auth-critical-high-f3

**Comment by radtriste** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-hcp-external-auth-critical-high-f3

**Comment by radtriste** [comment]
See results investigation [here](https://github.com/openshift/release/pull/54100#issuecomment-2225647553)

**Pull request closed without merging**
