### PR TITLE
stackrox: Enable ARO nightly

### PR DESCRIPTION
**Pull request by davdhacs**
Reverts openshift/release#32438 "Disable nightly aro"
/cc @porridge @gavin-stackrox 
/hold

### CODE REVIEW

**Comment by porridge** [comment]
/hold
How do we make sure this actually works beforehand?
I wasn't able to trigger the ARO flavor job in https://github.com/stackrox/stackrox/pull/3590 :thinking:

**Comment by gavin-stackrox** [comment]
Looks like they ran @porridge https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_stackrox/3590/pull-ci-stackrox-stackrox-master-aro-qa-e2e-tests/1585533104280309760

**Pull request merged**
