### PR TITLE
Create sa/build01 on vsphere

### PR DESCRIPTION
**Pull request by hongkailiu**
This SA will be used to generate pull secret which is then used in the build pod.

/cc @jcpowermac @alvaroaleman

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/hold
lets please not name it like a different build cluster, I thought the build01 SA on the build01 cluster as named after the cluster

**Comment by hongkailiu** [comment]
This name `build01` is kind of special.
Our script to generate the file also expects this name.
Also the file name containing value to be uploaded to BW: `build01_vsphere_reg_auth_value.txt` (build01 is the sa name and vsphere is the cluster name).
`sa/build01` is there in ci namespace on each build cluster.
Renaming this one only will be more confusing IMHO.

Can I keep the name pattern even though it looks a bit odd?

**Pull request merged**
