### PR TITLE
Remove extra workers from baremetal serial workflows

### PR DESCRIPTION
**Pull request by andfasano**
Since https://github.com/openshift/origin/pull/26681, every baremetal e2e is responsible to create/destroy its own extra workers as needed

### CODE REVIEW

**Comment by ardaguclu** [comment]
/lgtm

To allow the jobs run;
/hold

**Comment by ardaguclu** [comment]
/lgtm cancel

After thinking on it, still we need APPLY_EXTRA_WORKERS for releases <4.10. Probably 4.9 metal-ipi-serial-ipv4 will fail with machine scale test.

**Comment by andfasano** [comment]
> /lgtm cancel
> 
> After thinking on it, still we need APPLY_EXTRA_WORKERS for releases <4.10. Probably 4.9 metal-ipi-serial-ipv4 will fail with machine scale test.

Yep, good point, I guess we'll have to keep it until the new extraworker approach will be backported.

**Pull request closed without merging**
