### PR TITLE
OCPBUGS-33091: Only place the VM storage pools on small second disks

### PR DESCRIPTION
**Pull request by derekhiggins**
If the disk on a virt hosts are less then 200G then it
can't store both the VM storage pools and the image
registry.

Also
Test access to API during devscripts-gather
    
devscripts gather has access to the API without going
through the proxy.

### CODE REVIEW

**Comment by derekhiggins** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-upgrade-from-stable-4.14-e2e-metal-ipi-upgrade-ovn-ipv6 periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-ovn-bm periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-ovn-ipv6 periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-upgrade-ovn-ipv6 periodic-ci-openshift-release-master-nightly-4.16-upgrade-from-stable-4.15-e2e-metal-ipi-upgrade-ovn-ipv6

**Comment by derekhiggins** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-upgrade-from-stable-4.14-e2e-metal-ipi-upgrade-ovn-ipv6 periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-ovn-bm periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-ovn-ipv6 periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-upgrade-ovn-ipv6 periodic-ci-openshift-release-master-nightly-4.16-upgrade-from-stable-4.15-e2e-metal-ipi-upgrade-ovn-ipv6

**Comment by stbenjam** [comment]
/retitle OCPBUGS-33091: Only place the VM storage pools on small second disks

**Comment by derekhiggins** [comment]
The upgrade jobs didn't run on ESI, but the PR had the desired effect of only putting the VM pools on the second disk(taken from the ipv6 job)
```
$ df -h / /opt/dev-scripts/pool
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2       175G   35G  133G  21% /
/dev/sdb        187G  103G   84G  55% /opt/dev-scripts/pool

```

**Comment by derekhiggins** [comment]
/pj-rehearse ack 
the upgrade job still running is currently broken 
I'm not sure even with this the disk will be large enough but if we merge it we should find out fairly quickly

**Pull request merged**
