### PR TITLE
[PERFSCALE-3428] Verify cluster-health before running data-path jobs

### PR DESCRIPTION
**Pull request by rsevilla87**
/cc @josecastillolema @jtaleric 

Cluster health check is only actually necessary before running data-path jobs, kube-burner based jobs already incorporate health check

### CODE REVIEW

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-dev-latest-x86-weekly-6nodes

**Comment by rsevilla87** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-x86-data-path-6nodes

**Comment by rsevilla87** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-dev-latest-x86-data-path-6nodes

**Comment by jtaleric** [comment]
Should we add this to our other data-path jobs (not just BM)?

**Comment by rsevilla87** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-x86-data-path-6nodes

**Comment by rsevilla87** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-x86-data-path-6nodes

**Comment by rsevilla87** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-x86-data-path-6nodes

**Pull request merged**
