### PR TITLE
feat: add jobs for power-mon operator for tech-preview branch

### PR DESCRIPTION
**Pull request by vprashar2929**
This PR adds jobs for PowerMon Operator for `tech-preview` branch
* Periodic -> OCP4.13/4.14 on AWS and GCP
* PostSubmit Jobs -> OCP 4.14 on AWS and GCP
* PreSubmit -> OCP 4.14 on AWS

### CODE REVIEW

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-tech-preview-kepler-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-power-monitoring-operator-tech-preview-power-monitoring-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-tech-preview-kepler-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-tech-preview-kepler-e2e

**Review by sthaha — COMMENTED** [review]
/lgtm

**Pull request merged**
