### PR TITLE
[Prow CI Step Enhancement] update step mce-install to support downstream

### PR DESCRIPTION
**Pull request by LiangquanLi930**
use downstream image to install MCE

### CODE REVIEW

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.12-periodics-4.12-conformance-mce-aws-ovn

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.12-periodics-4.12-conformance-mce-aws-ovn

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.12-periodics-4.12-conformance-mce-aws-ovn

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.12-periodics-4.12-conformance-mce-aws-ovn

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.12-periodics-4.12-conformance-mce-aws-ovn

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.12-periodics-4.12-conformance-mce-aws-ovn

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-mce-aws-ovn

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-mce-aws-ovn

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-mce-aws-ovn

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-mce-aws-ovn

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-mce-aws-ovn

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-mce-aws-ovn

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-mce-aws-ovn

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-mce-aws-ovn

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-mce-aws-ovn

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-mce-aws-ovn

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-mce-aws-ovn

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-mce-aws-ovn

**Review by rokej — APPROVED** [review]

**Pull request merged**
