### PR TITLE
MGMT-18657: fix resources for CNV 4.16

### PR DESCRIPTION
**Pull request by eifrach**

### CODE REVIEW

**Comment by eifrach** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-cnv-4-16-periodic

**Comment by danmanor** [comment]
@eifrach you mean "CNV" not "LVM right ?

**Comment by danmanor** [comment]
@eifrach If this works, we have more CNV jobs which probably need the same patch

**Comment by eifrach** [comment]
/retitle MGMT-18657: fix resources for CNV 4.16

**Comment by eifrach** [comment]
> @eifrach you mean "CNV" not "LVM right ?
yes, thanks

**Comment by eifrach** [comment]
> @eifrach If this works, we have more CNV jobs which probably need the same patch

I did in #43905 - I may missed this one

**Pull request merged**
