### PR TITLE
4.11: Populate handcrafted release jobs

### PR DESCRIPTION
**Pull request by petr-muller**
- 4.11: Seed handcrafted release jobs from 4.10
- 4.11: Bump versions in handcrafted release jobs
- 4.11: Add legacy release jobs to allowlist
- `make release-controllers`

### CODE REVIEW

**Comment by petr-muller** [comment]
Probably a good time to assess whether we still need some of the legacy handcrafted jobs:
- `release-openshift-ocp-installer-e2e-aws-csi-4.11`: Its 4.10 version is *not* referenced from any release-controller config. We seem to have equivalent-looking jobs in ci-op configs, like `e2e-aws-csi`
- `release-openshift-origin-installer-e2e-aws-disruptive-4.11`: Its 4.10 version is *not* referenced from any release-controller config. We do not seem to have equivalents in ci-op configs, but there seems to be a [workflow](https://steps.ci.openshift.org/workflow/openshift-e2e-aws-disruption).
- `release-openshift-origin-installer-e2e-aws-shared-vpc-4.11`: Its 4.10 version is *not* referenced from any release-controller config. We do not seem to have equivalents in ci-op configs.
- `release-openshift-ocp-installer-e2e-azure-serial-4.11`: Its 4.10 version is referenced from `release-ocp-4.10.json`. We seem to have equivalents in ci-op configs.
- `release-openshift-origin-installer-e2e-azure-shared-vpc-4.11`: Its 4.10 version is *not* referenced from any release-controller config. We do not seem to have equivalents in ci-op configs.
- `release-openshift-ocp-installer-e2e-gcp-serial-4.11`: Its 4.10 version is referenced from `release-ocp-4.10.json`. We seem to have equivalents in ci-op configs.
- `release-openshift-origin-installer-e2e-gcp-shared-vpc-4.11`: Its 4.10 version is *not* referenced from any release-controller config. We do not seem to have equivalents in ci-op configs.
- `release-openshift-ocp-installer-e2e-aws-mirrors-4.11`: Its 4.10 version is *not* referenced from any release-controller config. We do not seem to have equivalents in ci-op configs.
- `release-openshift-ocp-installer-e2e-metal-compact-4.11`: Its 4.10 version is *not* referenced from any release-controller config. We seem to have `e2e-metal-ipi-compact` in ci-op config
- `release-openshift-ocp-installer-e2e-metal-serial-4.11`: Its 4.10 version is referenced from `release-ocp-4.10.json`. We do not seem to have an equivalent in ci-op configs, but there is `e2e-metal-ipi-serial-ipv4` which could be it?
- `release-openshift-ocp-installer-e2e-aws-upi-4.11`: Its 4.10 is referenced from `release-ocp-4.10.json`. We do not seem to have equivalents in ci-op configs.

So it seems we could do the following:

Drop:
- `release-openshift-ocp-installer-e2e-aws-csi-4.11`

Replace:
- `release-openshift-ocp-installer-e2e-azure-serial-4.11` with `periodic-ci-openshift-release-master-ci-4.11-e2e-azure-serial`
- `release-openshift-ocp-installer-e2e-gcp-serial-4.11` with `periodic-ci-openshift-release-master-ci-4.11-e2e-gcp-serial`
- `release-openshift-ocp-installer-e2e-metal-compact-4.11` with `periodic-ci-openshift-release-master-nightly-4.11-e2e-metal-ipi-compact`
- 

Followup with:
- Replace `release-openshift-origin-installer-e2e-aws-disruptive-4.11` with [workflow](https://steps.ci.openshift.org/workflow/openshift-e2e-aws-disruption)-based generated job
- Replace `release-openshift-ocp-installer-e2e-metal-serial-4.11` with one of the existing `e2e-metal-ipi-serial-*` jobs

Probably keep:
- `release-openshift-origin-installer-e2e-aws-shared-vpc-4.11` (no matching workflow yet)
- `release-openshift-origin-installer-e2e-azure-shared-vpc-4.11` (no matching workflow yet)
- `release-openshift-origin-installer-e2e-gcp-shared-vpc-4.11` (no matching workflow yet)
- `release-openshift-ocp-installer-e2e-aws-mirrors-4.11` (no matching workflow yet)
- `release-openshift-ocp-installer-e2e-aws-upi-4.11`

**Comment by wking** [comment]
We [have some 4.11 nightlies now][1].

/retest

Nothing stood out for me on visual inspection, so:

/lgtm

And in case anyone wants to wait for the retest rehearsals to go through:

/hold

[1]: https://amd64.ocp.releases.ci.openshift.org/#4.11.0-0.nightly

**Pull request merged**
