### PR TITLE
Move to Golang  1.21

### PR DESCRIPTION
**Pull request by skonto**
- Needed by the next run of https://github.com/openshift-knative/serving/pull/544 which will have the new files from
https://github.com/openshift-knative/serving/pull/546.
- openshift-knative/hack can't consume the new image unless it exists on the release-next branch.

/assign @ReToCode

### CODE REVIEW

**Review by ReToCode — COMMENTED** [review]
Isn't this created by openshift-knative/hack?

**Comment by ReToCode** [comment]
Ah sorry, missed

> openshift-knative/hack can't consume the new image unless it exists on the release-next branch.


/lgtm
/approve

**Comment by skonto** [comment]
No because you need the dockerfiles and the images defined in the "FROM" directive to exist on the release-next branch so it can pick it up.

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-release-next-411-images

**Pull request merged**
