### PR TITLE
Looking to add a simple SNO job

### PR DESCRIPTION
**Pull request by jtaleric**
SNO Job to identify regressions performance w/ OVN and OVNIC

### CODE REVIEW

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-sno-4.13-ocp-qe-perfscale-aws-control-plane-sno-periodic

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-sno-4.14-ocp-qe-perfscale-aws-control-plane-sno-periodic

**Comment by paigerube14** [comment]
/assign @paigerube14 @svetsa-rh 
Just for visibility

**Pull request merged**
