### PR TITLE
Improve ansible message formatting

### PR DESCRIPTION
**Pull request by osherdp**
Currently output is displayed raw (with whitespace characters that displayed like ``\n``, ``\t`` for example), which makes it hard to read the output in case of failures.

This should use the YAML callback plugin to make it much more readable. Read more at
https://www.jeffgeerling.com/blog/2018/use-ansibles-yaml-callback-plugin-better-cli-experience

### CODE REVIEW

**Comment by osherdp** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted

**Comment by osherdp** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted

**Comment by osherdp** [comment]
/cc @adriengentil @eliorerz 
Looks much better, at least in https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/37473/rehearse-37473-pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted/1637760644562292736/artifacts/e2e-metal-assisted/assisted-common-gather/build-log.txt

**Comment by DennisPeriquet** [comment]
It does look better :-) .  Here's a [log without it](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-assisted-test-infra-release-ocm-2.7-e2e-metal-assisted-kube-api-net-suite-periodic/1636860826751078400/artifacts/e2e-metal-assisted-kube-api-net-suite-periodic/assisted-common-gather/build-log.txt)

**Review by adriengentil — APPROVED** [review]
awesome!

**Comment by osherdp** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-single-node-live-iso pull-ci-openshift-assisted-service-release-ocm-2.7-e2e-ai-operator-ztp

**Pull request merged**
