### PR TITLE
Expansion of scenario to run for 4.18

### PR DESCRIPTION
**Pull request by vi-patel**
Other updates:
 * update chron
 * add FIREWATCH_DEFAULT_JIRA_ASSIGNEE
 * create .config.prowgen file for slack reporting of results being auto-created with make updates

### CODE REVIEW

**Comment by vi-patel** [comment]
/pj-rehearse periodic-ci-redhat-developer-odo-main-odo-ocp4.18-lp-interop-odo-scenario-aws

**Comment by vi-patel** [comment]
/pj-rehearse periodic-ci-redhat-developer-odo-main-odo-ocp4.18-lp-interop-odo-scenario-aws-fips

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
