### PR TITLE
WIP: GitOps | Onboard Interop testing

### PR DESCRIPTION
**Pull request by varshab1210**

### CODE REVIEW

**Comment by varshab1210** [comment]
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-master-gitops-ocp4.13-lp-interop-redhat-openshift-gitops-interop-aws

**Comment by varshab1210** [comment]
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-master-gitops-ocp4.13-lp-interop-redhat-openshift-gitops-interop-aws

**Comment by varshab1210** [comment]
/test all
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-master-gitops-ocp4.13-lp-interop-redhat-openshift-gitops-interop-aws

**Comment by varshab1210** [comment]
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-master-gitops-ocp4.13-lp-interop-redhat-openshift-gitops-interop-aws

**Comment by varshab1210** [comment]
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-v1.8-gitops-ocp4.13-lp-interop-redhat-openshift-gitops-interop-aws

**Comment by varshab1210** [comment]
/test all
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-v1.8-gitops-ocp4.13-lp-interop-redhat-openshift-gitops-interop-aws

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-v1.8-gitops-ocp4.13-lp-interop-redhat-openshift-gitops-interop-aws

**Comment by varshab1210** [comment]
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-v1.8-gitops-ocp4.13-lp-interop-redhat-openshift-gitops-interop-aws

**Comment by varshab1210** [comment]
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-v1.8-gitops-ocp4.13-lp-interop-redhat-openshift-gitops-interop-aws

**Comment by varshab1210** [comment]
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-v1.8-gitops-ocp4.13-lp-interop-redhat-openshift-gitops-interop-aws

**Comment by varshab1210** [comment]
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-Openshift-CI-testing-gitops-ocp4.13-lp-interop-redhat-openshift-gitops-interop-aws

**Comment by varshab1210** [comment]
periodic-ci-redhat-developer-gitops-operator-Openshift-CI-testing-gitops-ocp4.13-lp-interop-redhat-openshift-gitops-interop-aws

**Comment by varshab1210** [comment]
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-Openshift-CI-testing-gitops-ocp4.13-lp-interop-redhat-openshift-gitops-interop-aws

**Comment by varshab1210** [comment]
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-Openshift-CI-testing-gitops-ocp4.13-lp-interop-redhat-openshift-gitops-interop-aws

**Comment by varshab1210** [comment]
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-Openshift-CI-testing-gitops-ocp4.13-lp-interop-redhat-openshift-gitops-interop-aws

**Comment by varshab1210** [comment]
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-Openshift-CI-testing-gitops-ocp4.13-lp-interop-redhat-openshift-gitops-interop-aws

**Comment by varshab1210** [comment]
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-Openshift-CI-testing-gitops-ocp4.13-lp-interop-redhat-openshift-gitops-interop-aws

**Comment by varshab1210** [comment]
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-Openshift-CI-testing-gitops-ocp4.13-lp-interop-redhat-openshift-gitops-interop-aws

**Comment by varshab1210** [comment]
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-Openshift-CI-testing-gitops-ocp4.13-lp-interop-redhat-openshift-gitops-interop-aws

**Comment by varshab1210** [comment]
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-Openshift-CI-testing-gitops-ocp4.13-lp-interop-redhat-openshift-gitops-interop-aws

**Comment by varshab1210** [comment]
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-Openshift-CI-testing-gitops-ocp4.13-lp-interop-redhat-openshift-gitops-interop-aws

**Comment by varshab1210** [comment]
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-Openshift-CI-testing-gitops-ocp4.13-lp-interop-redhat-openshift-gitops-interop-aws

**Comment by varshab1210** [comment]
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-Openshift-CI-testing-gitops-ocp4.13-lp-interop-redhat-openshift-gitops-interop-aws

**Comment by varshab1210** [comment]
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-Openshift-CI-testing-gitops-ocp4.13-lp-interop-redhat-openshift-gitops-interop-aws

**Pull request closed without merging**
