### PR TITLE
[ovs-operator] Update functional job

### PR DESCRIPTION
**Pull request by karelyatin**
[1] is Adding functional test and it requires
GOFLAGS to be overridden.
Also update job name to be functional and
add GINKGO_ARGS.

[1] https://github.com/openstack-k8s-operators/ovs-operator/pull/114

### CODE REVIEW

**Comment by karelyatin** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-ovs-operator-main-functional

**Comment by karelyatin** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-ovs-operator-main-functional

**Comment by Sandeepyadav93** [comment]
/pj-rehearse ack

No tests available but job looks okay configwise.

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/39105/rehearse-39105-pull-ci-openstack-k8s-operators-ovs-operator-main-functional/1655594243122532352/artifacts/test/build-log.txt

**Pull request merged**
