### PR TITLE
remove assisted-test-infra related jobs for ocm-2.3

### PR DESCRIPTION
**Pull request by osherdp**
We decided this job to not be cost-effective for getting fixed, also not simulating good enough the required environment.

/cc @mkowalski @eliorerz

### CODE REVIEW

**Comment by osherdp** [comment]
/hold
(for a complete review)

**Comment by osherdp** [comment]
/cc @lranjbar 
do you think we should get out also the reminders of assisted-test-infra-ocm-2.3 configuration?

**Review by eliorerz — APPROVED** [review]
LGTM

**Review by mkowalski — APPROVED** [review]
🥐

**Pull request merged**
