### PR TITLE
Different stab of operator on prow.

### PR DESCRIPTION
**Pull request by porridge**
This is work in progress, a slightly different approach to #29718 - in a different branch to not ruin links in [this thread](https://coreos.slack.com/archives/CBN38N3MW/p1657524554082019).

/hold
/test pj-rehearse-max

Just cc-ing Gavin to prevent auto-assignment.

/cc @gavin-stackrox

### CODE REVIEW

**Comment by gavin-stackrox** [comment]
I learnt from @house-d that you can also skip auto-assignment with an empty `/uncc`.

**Comment by gavin-stackrox** [comment]
/uncc @gavin-stackrox 
:)
/shrug

**Comment by porridge** [comment]
Superseded by https://github.com/openshift/release/pull/30630

**Pull request closed without merging**
