### PR TITLE
ROX-21034: bump stackrox automation ocp tag to 0.9.19

### PR DESCRIPTION
**Pull request by stehessel**
Bump OCP automation flavor tag to `0.9.19` to get https://github.com/stackrox/automation-flavors/pull/191.

### CODE REVIEW

**Comment by stehessel** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-4.14-ocp-4-14-qa-e2e-tests

**Review by tommartensen — APPROVED** [review]
/assign @stehessel 

/lgtm

**Pull request merged**
