### PR TITLE
Create openshift-ci project for model-registry

### PR DESCRIPTION
**Pull request by tonyxrmdavidson**
Removing un-needed security step from configuration

revert janus-ipd/_prowconfig.yaml file back to original. This was a change brought in the configuration tool which shouldn't have added to the file.

### CODE REVIEW

**Comment by psalajova** [comment]
> /remove-do-no-merge

Hi, if you wish to remove the `do-not-merge/work-in-progress` label you need to remove the "Draft" from the title of this PR (see [WIP prow plugin](https://prow.k8s.io/plugins) for more info)

**Review by dtrifiro — APPROVED** [review]

**Pull request merged**
