### PR TITLE
Modify golangci-lint job to run in a container

### PR DESCRIPTION
**Pull request by Sandeepyadav93**
Existing `golangci` job `pull-ci-openstack-k8s-operators-mariadb-operator-master-golangci`
install `golanci-lint` binary which is failing after receiving 429 (ratelimit) from github.[1]

If we run `golangci-lint` in a container we don't need to install the
binary from GitHub and can avoid the rate limit issue altogether.

In this PR, we have three commits.
(1) Adding new job that will run `golangci-lint` in `golangci-lint` container
(2) Removing the older job `pull-ci-openstack-k8s-operators-mariadb-operator-master-golangci`
(3)  Rename golangci-lint job as golangci(tooriginal job name)

[1] https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/30638/rehearse-30638-pull-ci-openstack-k8s-operators-mariadb-operator-master-golangci/1551583824574418944/build-log.txt

### CODE REVIEW

**Comment by Sandeepyadav93** [comment]
Running golangci-lint in golangci-lint container worked[1]. 

Should we remove the old job `pull-ci-openstack-k8s-operators-mariadb-operator-master-golangci` which is failing due to rate limit[2] in the same patch?


[1] https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/30807/rehearse-30807-pull-ci-openstack-k8s-operators-osp-director-operator-master-golangci-lint/1551858412633985024/artifacts/test/build-log.txt

[2] https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/30807/rehearse-30807-pull-ci-openstack-k8s-operators-osp-director-operator-master-golangci/1551858412873060352/build-log.txt

**Comment by Sandeepyadav93** [comment]
/retest

github rate limiting in last failures.

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/30807/rehearse-30807-pull-ci-openstack-k8s-operators-osp-director-operator-master-golint/1551873855948066816

~~~
Cloning into '/go/src/github.com/openstack-k8s-operators/osp-director-operator/CI_TOOLS_REPO'...
fatal: unable to access 'https://github.com/openstack-k8s-operators/openstack-k8s-operators-ci/': The requested URL returned error: 429
make: *** [get-ci-tools] Error 128
~~~

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
