### PR TITLE
[o/cert-manager-operator] Enable promotion

### PR DESCRIPTION
**Pull request by swghosh**
Use promotion in cert-manager-operator and it's bundle
* [WIP] facilitate upgrade tests between y-streams of cert-manager-operator
* this change will 
    * 1.10 promotes to ocp-4.12 
    * 1.11 promotes to ocp-4.13 
    * master (i.e. future 1.12) promotes to ocp-4.14

Signed-off-by: Swarup Ghosh <swghosh@redhat.com>

### CODE REVIEW

**Comment by swghosh** [comment]
e2e failing due to same glibc issue as previous
```
/usr/bin/cert-manager-operator: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /usr/bin/cert-manager-operator)
/usr/bin/cert-manager-operator: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/cert-manager-operator)
```
/hold

**Comment by swghosh** [comment]
/pj-rehearse pull-ci-openshift-cert-manager-operator-cert-manager-v1.10.x-e2e-operator-upgrade
/pj-rehearse pull-ci-openshift-cert-manager-operator-cert-manager-v1.10.x-e2e-operator

**Comment by swghosh** [comment]
/pj-rehearse pull-ci-openshift-cert-manager-operator-cert-manager-v1.10.x-e2e-operator

**Comment by swghosh** [comment]
> @swghosh: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name | Commit | Details | Required | Rerun command
> --- | --- | --- | --- | ---
> ci/rehearse/openshift/cert-manager-operator/cert-manager-v1.10.x/e2e-operator-upgrade | 76d5446eeabb76ef91e8e11f790463c377f16bef | [link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/41088/rehearse-41088-pull-ci-openshift-cert-manager-operator-cert-manager-v1.10.x-e2e-operator-upgrade/1678737898364473344) | unknown | `/pj-rehearse pull-ci-openshift-cert-manager-operator-cert-manager-v1.10.x-e2e-operator-upgrade`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openshift&repo=release&pr=41088). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:swghosh).
> 
> <details>
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
> </details>
> 

Expected to fail, since 1.10 branch e2e-upgrade expect latest CSV version as 1.10.3 (which is impending merge openshift/cert-manager-operator#133).

/remove-hold
glibc problem is resolved using `from: ubi` in operator image.

**Comment by bparees** [comment]
/hold

i've got concerns about the naming convention being used here, with the operator version being included in the image repo name.  And in particular w/ the case of putting the branch name (`master`) in the image repo name also.

let's talk with the test platform team about the best way to approach this that meets your goals.

**Pull request closed without merging**
