### PR TITLE
Add: aws-efs-csi-driver-operator extended presubmit test jobs

### PR DESCRIPTION
**Pull request by Phaow**
### Add aws-efs extended presubmit test jobs to extend the presubmit test coverage
https://issues.redhat.com/browse/OCPQE-15381

### CODE REVIEW

**Comment by Phaow** [comment]
/pj-rehearse pull-ci-openshift-aws-efs-csi-driver-release-4.14-e2e-csi-extended

**Comment by Phaow** [comment]
/pj-rehearse pull-ci-openshift-aws-efs-csi-driver-operator-release-4.14-operator-e2e-extended

**Comment by Phaow** [comment]
/pj-rehearse pull-ci-openshift-aws-efs-csi-driver-operator-master-operator-e2e-extended

**Comment by Phaow** [comment]
/pj-rehearse pull-ci-openshift-aws-efs-csi-driver-operator-master-operator-e2e-extended

**Comment by Phaow** [comment]
/pj-rehearse pull-ci-openshift-aws-efs-csi-driver-operator-master-operator-e2e-extended

**Comment by Phaow** [comment]
/pj-rehearse pull-ci-openshift-aws-efs-csi-driver-operator-master-operator-e2e-extended

**Comment by Phaow** [comment]
/pj-rehearse pull-ci-openshift-aws-efs-csi-driver-operator-master-operator-e2e-extended

**Comment by Phaow** [comment]
/pj-rehearse pull-ci-openshift-aws-efs-csi-driver-operator-release-4.14-operator-e2e-extended

**Comment by Phaow** [comment]
/pj-rehearse pull-ci-openshift-aws-efs-csi-driver-operator-release-4.14-operator-e2e-extended

**Comment by Phaow** [comment]
/pj-rehearse pull-ci-openshift-aws-efs-csi-driver-operator-release-4.14-operator-e2e-extended

**Comment by Phaow** [comment]
/pj-rehearse pull-ci-openshift-aws-efs-csi-driver-operator-master-operator-e2e-extended

**Comment by Phaow** [comment]
/pj-rehearse pull-ci-openshift-aws-efs-csi-driver-operator-master-operator-e2e-extended
/pj-rehearse pull-ci-openshift-aws-efs-csi-driver-operator-release-4.14-operator-e2e-extended

**Comment by Phaow** [comment]
/pj-rehearse pull-ci-openshift-aws-efs-csi-driver-operator-master-operator-e2e-extended
/pj-rehearse pull-ci-openshift-aws-efs-csi-driver-operator-release-4.14-operator-e2e-extended

**Comment by Phaow** [comment]
/pj-rehearse pull-ci-openshift-aws-efs-csi-driver-operator-release-4.14-operator-e2e-extended

**Comment by Phaow** [comment]
Hello @jsafrane , the efs csi dirver operator presubmit test job is ready for review, could you please help take a look when you get a chance? Thanks in advance!
The last commit just fix typo in workflow docummentation(as the release repo default merge type is `squash`, so I don't squash the commits to make the review more clearly). 
[Rehearse passed record](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/38481/rehearse-38481-pull-ci-openshift-aws-efs-csi-driver-operator-master-operator-e2e-extended/1651890170263244800/artifacts/operator-e2e-extended/openshift-extended-test/build-log.txt)

**Comment by Phaow** [comment]
/pj-rehearse pull-ci-openshift-aws-efs-csi-driver-operator-release-4.14-operator-e2e-extended

**Comment by Phaow** [comment]
/pj-rehearse pull-ci-openshift-aws-efs-csi-driver-operator-master-operator-e2e-extended

**Comment by jsafrane** [comment]
/pj-rehearse pull-ci-openshift-aws-efs-csi-driver-operator-master-operator-e2e-extended

**Pull request merged**
