### PR TITLE
Bug 1874618: cluster-api-provider-baremetal: add unit test job

### PR DESCRIPTION
**Pull request by dhellmann**
We were running an end-to-end test job, but not the unit tests.

/assign @zaneb

### CODE REVIEW

**Comment by zaneb** [comment]
```
go run vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go crd paths=./pkg/apis/... output:crd:dir=./config/crds/
/bin/sh: kustomize: command not found
```

sigh

**Comment by dhellmann** [comment]
See https://github.com/openshift/cluster-api-provider-baremetal/pull/107

**Comment by dhellmann** [comment]
Waiting for https://github.com/openshift/cluster-api-provider-baremetal/pull/108

**Comment by dhellmann** [comment]
Now we need https://github.com/openshift/cluster-api-provider-baremetal/pull/111

**Comment by hardys** [comment]
> Now we need [openshift/cluster-api-provider-baremetal#111](https://github.com/openshift/cluster-api-provider-baremetal/pull/111)

Now merged

/retest

**Pull request merged**
