### PR TITLE
Console/ODC team update

### PR DESCRIPTION
**Pull request by christoph-jerolimov**
1. Remove Debsmita from the PR slack reminder since she's working on another project now.
2. Remove Hemant and Sparsh from the cherry-pick-approved list since they have left RH. Thanks for all your work.

### CODE REVIEW

**Comment by danilo-gemoli** [comment]
Clearly my fault, I forgot to update [the flag](https://github.com/openshift/release/blob/5ef2346ab13d964c294ee35f7f8d10f89bf228ba/ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml#L1444) back then.
@jerolimov your commit is correct but the failing test has to be updated in another PR.
I'm going to fix it.

**Comment by jerolimov** [comment]
Thanks @smg247 @danilo-gemoli, I rebased and dropped the config change.

`pr-reminder-config` passes already :+1:

**Pull request merged**
