### PR TITLE
Update ocs, odf config and add 4.17 jobs for ocs, odf operators

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Add 4.17 jobs for ocs, odf operators
And, update CSV version in ocs,odf main jobs

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
@iamniting please review

**Review by iamniting — APPROVED** [review]

**Comment by iamniting** [comment]
/pj-rehearse pull-ci-red-hat-storage-ocs-operator-main-ocs-operator-bundle-e2e-aws

**Comment by iamniting** [comment]
/pj-rehearse pull-ci-red-hat-storage-ocs-operator-main-ocs-operator-bundle-e2e-aws

**Pull request merged**
