### PR TITLE
Use the OpenShift bundle Dockerfile in OTEL jobs

### PR DESCRIPTION
**Pull request by IshwarKanse**
Use the new OpenShift bundle added to upstream. https://github.com/open-telemetry/opentelemetry-operator/pull/3056

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-ocp-4.14-amd64-opentelemetry-e2e-tests periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.16-lp-interop-tempo-interop-aws

**Review by frzifus — APPROVED** [review]

**Comment by IshwarKanse** [comment]
/override ci/rehearse-54612-periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-ocp-4.14-amd64-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/override ci/rehearse/periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-ocp-4.14-amd64-opentelemetry-e2e-tests

**Pull request merged**
