### PR TITLE
Use Openshift console latest image

### PR DESCRIPTION
**Pull request by upalatucci**
Right now our tests are failing as we are using an openshift console image with a known issue.

### CODE REVIEW

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-kubevirt-ui-kubevirt-plugin-main-kubevirt-e2e-aws

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-kubevirt-ui-kubevirt-plugin-main-kubevirt-e2e-aws

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-kubevirt-ui-kubevirt-plugin-main-kubevirt-e2e-aws

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-kubevirt-ui-kubevirt-plugin-main-kubevirt-e2e-aws

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-kubevirt-ui-kubevirt-plugin-main-kubevirt-e2e-aws

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-kubevirt-ui-kubevirt-plugin-main-kubevirt-e2e-aws

**Comment by yaacov** [comment]
/pj-rehearse pull-ci-kubevirt-ui-kubevirt-plugin-main-kubevirt-e2e-aws

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-kubevirt-ui-kubevirt-plugin-main-kubevirt-e2e-aws

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-kubevirt-ui-kubevirt-plugin-main-kubevirt-e2e-aws

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-kubevirt-ui-kubevirt-plugin-main-kubevirt-e2e-aws

**Pull request closed without merging**
