### PR TITLE
Add app-sre/deployment-validation-operator repository

### PR DESCRIPTION
**Pull request by rporres**
Created using `make new-repo` from this repository and `make prow-config` from https://github.com/app-sre/deployment-validation-operator (via https://github.com/openshift/boilerplate)

cc @2uasimojo 

Apologies in advance if there's something completely wrong here, I'm a complete n00b in prow 😅

### CODE REVIEW

**Review by 2uasimojo — APPROVED** [review]
The ci-operator parts are correct.

The core-services parts _look_ legit to me. If they came from `make new-repo` I'm sure they're at least workable, and we can always tweak them later.

/lgtm

**Comment by 2uasimojo** [comment]
Oh, wait, you need OWNERS files for your ci-operator configs.

/lgtm cancel

**Review by 2uasimojo — APPROVED** [review]
/lgtm

**Comment by rporres** [comment]
Re-running OOM killed test 
```
error: some steps failed:
  * could not run steps: step src failed: could not wait for build: the build src failed after 1m5s with reason OutOfMemoryKilled: The build pod was killed due to an out of memory condition.
```
/test pj-rehearse

**Review by 2uasimojo — COMMENTED** [review]
Still

/lgtm

Let's get this merged before it drifts again.

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
