### PR TITLE
[Test]build up rhcs 1.6.3 release testing.

### PR DESCRIPTION
**Pull request by jameszwang**

### CODE REVIEW

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-advanced-medium-low-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-advanced-critical-high-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-network-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-upgrade-y-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-private-critical-high-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-arm-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-private-critical-high-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-private-day1-negative-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-classic-full-resource-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-upgrade-z-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-day1-negative-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-encryption-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-upgrade-z-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-full-resource-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-private-critical-high-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-private-medium-low-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-day1-supplemental-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-advanced-critical-high-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-advanced-medium-low-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-upgrade-z-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-full-resource-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-day1-supplemental-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-critical-high-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-classic-full-resource-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-medium-low-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-full-resource-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-private-medium-low-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-upgrade-y-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-shared-vpc-critical-high-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-private-day1-negative-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-private-critical-high-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-full-resource-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-full-resource-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-day1-negative-163

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-private-day1-negative-163

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-critical-high-163

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-critical-high-163

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-critical-high-163

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-full-resource-163

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-day1-negative-163

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-day1-supplemental-163

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-upgrade-z-163

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-shared-vpc-critical-high-163

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-private-day1-negative-163

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-private-critical-high-163

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-classic-full-resource-163

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-private-medium-low-163

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-classic-full-resource-163

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-upgrade-y-163

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-medium-low-163

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-full-resource-163

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-full-resource-163

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-medium-low-163

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-upgrade-y-163

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-full-resource-163

**Comment by xueli181114** [comment]
rosa-sts-ad-medium+Low
```
 Summarizing 4 Failures:
  [FAIL] Classic Ingress [It] validate ingress components - [id:75067] [feature-ingress, day2, Medium]
  /alabama/terraform-provider-rhcs/tests/utils/helper/assert.go:52
  [FAIL] Create MachinePool [It] can reconciliate with basic flow - [id:65645] [day2, feature-machinepool, Medium]
  /alabama/terraform-provider-rhcs/tests/e2e/classic_machine_pool_test.go:697
  [FAIL] Edit Account roles [It] can create account roles with default prefix - [id:65380] [day2, Medium]
  /alabama/terraform-provider-rhcs/tests/e2e/account_roles_test.go:46
  [FAIL] Edit MachinePool [BeforeEach] check the validations and some negative scenarios of creating/editing/deleting default machinepool - [id:69073] [day2, feature-machinepool, Medium]
  /alabama/terraform-provider-rhcs/tests/e2e/classic_machine_pool_test.go:850 
```

**Comment by xueli181114** [comment]
rosa-sts-pl
```
   [FAIL] Classic Ingress [It] validate ingress components - [id:75067] [feature-ingress, day2, Medium]
  /alabama/terraform-provider-rhcs/tests/utils/helper/assert.go:52
  [FAIL] Edit Account roles [It] can create account roles with default prefix - [id:65380] [day2, Medium]
  /alabama/terraform-provider-rhcs/tests/e2e/account_roles_test.go:46 
```

**Pull request closed without merging**
