### PR TITLE
OCPBUGS-39307: update build_root to use go1.22 for 4.17+

### PR DESCRIPTION
**Pull request by jluhrsen**

### CODE REVIEW

**Comment by jluhrsen** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-release-4.17-unit

**Comment by jluhrsen** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-release-4.18-unit

**Comment by jluhrsen** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-release-4.17-unit

**Comment by jluhrsen** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-release-4.18-unit

**Comment by jluhrsen** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-release-4.19-unit

**Review by trozet — APPROVED** [review]
/lgtm

**Pull request merged**
