### PR TITLE
adding testing for hybrid networking custom vxlan port to networking repos

### PR DESCRIPTION
**Pull request by JacobTanenbaum**
adding testing for custom vxlan ports for hybrid networking to
openshift/ovn-kubernetes and openshift/cluster-network-operator when using
ovn-kubernetes network plugin

### CODE REVIEW

**Comment by aravindhp** [comment]
Thanks for adding this @JacobTanenbaum. I suggest holding this until #11225 merges.

**Comment by JacobTanenbaum** [comment]
/hold 

holding until https://github.com/openshift/release/pull/11225 merges

**Comment by JacobTanenbaum** [comment]
@abhat @dcbw @knobunc PTAL this needs an approver

**Pull request merged**
