### PR TITLE
cincinnati: run rustfmt on Rust 1.40

### PR DESCRIPTION
**Pull request by vrutkovs**
Add a test to verify cincinnati formatting using latest stable Rust

* [x] Requires https://github.com/openshift/cincinnati/pull/201 to pass rehearsals

### CODE REVIEW

**Comment by wking** [comment]
[Rehearsal][1] failed:

```
error: toolchain '1.40.0-x86_64-unknown-linux-gnu' is not installed
```

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/6901/rehearse-6901-pull-ci-openshift-cincinnati-master-rustfmt-1.40.0/1

**Comment by steveeJ** [comment]
> [Rehearsal](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/6901/rehearse-6901-pull-ci-openshift-cincinnati-master-rustfmt-1.40.0/1) failed:
> 
> ```
> error: toolchain '1.40.0-x86_64-unknown-linux-gnu' is not installed
> ```

That's because

> Requires [openshift/cincinnati#201](https://github.com/openshift/cincinnati/pull/201) to pass rehearsals

as mentioned by @vrutkovs in the OP.

**Pull request merged**
