### PR TITLE
Skip OutOfServiceTaint remediation verification if out-of-service taint is not supported

### PR DESCRIPTION
**Pull request by k-keiichi-rh**
This RP is to set a env variable to skip OutOfServiceTaint remediation verification if out-of-service taint is not supported.

### CODE REVIEW

**Comment by slintes** [comment]
you need to run `make ci-operator-config` and amend changes

**Comment by k-keiichi-rh** [comment]
> you need to run make ci-operator-config and amend changes

Thanks for the suggestion. I fixed it.

**Pull request merged**
