### PR TITLE
MTA zstream 4.16 and firewatch updates

### PR DESCRIPTION
**Pull request by smatula**

### CODE REVIEW

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-konveyor-tackle-ui-tests-mta_7.0.3-mta-ocp4.15-lp-interop-mta-interop-ibmcloud periodic-ci-konveyor-tackle-ui-tests-mta_7.0.3-mta-ocp4.16-lp-interop-mta-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-konveyor-tackle-ui-tests-mta_7.0.3-mta-ocp4.15-lp-interop-mta-interop-ibmcloud

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
