### PR TITLE
 4.16 hypershift cluster-nfd-operator expansion

### PR DESCRIPTION
**Pull request by shakyav**
PR is to expand Cluster-nfd layered product testing to ROSA hypershift 4.16

### CODE REVIEW

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-cluster-nfd-operator-release-4.16-ocp4.16-lp-rosa-hypershift-nfd-e2e-master-aws-rosa-hypershift

**Review by calebevans — APPROVED** [review]
/lgtm

**Comment by shakyav** [comment]
cc: [yevgeny-shnaidman](https://github.com/yevgeny-shnaidman)

**Comment by shakyav** [comment]
@ybettan can you please approve this PR, it need s to be merged for ROSA hypershift 4.16 weekly testing for layered products

**Pull request merged**
