### PR TITLE
[INTEROP-7440] Expand OpenShift Pipelines to 1.15 for OCP CI 4.17.

### PR DESCRIPTION
**Pull request by dfrazzette**
Create ci/config for OpenShift Pipelines v1.15 release on OCP 4.17.

### CODE REVIEW

**Comment by dfrazzette** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.17-lp-interop-openshift-pipelines-interop-aws

**Review by calebevans — APPROVED** [review]
/lgtm

**Review by VeereshAradhya — APPROVED** [review]

**Pull request merged**
