### PR TITLE
MSI: enable smoke periodic job

### PR DESCRIPTION
**Pull request by rnetser**

### CODE REVIEW

**Review by myakove — APPROVED** [review]

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-single-cluster-smoke-v4.14-single-cluster-hypershift-4-14-candidate-smoke

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-single-cluster-smoke-v4.14-single-cluster-hypershift-4-14-candidate-smoke

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-single-cluster-smoke-v4.14-single-cluster-hypershift-4-14-candidate-smoke

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-single-cluster-smoke-v4.14-single-cluster-hypershift-4-14-candidate-smoke

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-single-cluster-smoke-v4.14-single-cluster-hypershift-4-14-candidate-smoke

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-single-cluster-smoke-v4.14-single-cluster-hypershift-4-14-candidate-smoke

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-single-cluster-smoke-v4.14-single-cluster-hypershift-4-14-candidate-smoke

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-single-cluster-smoke-v4.14-single-cluster-hypershift-4-14-candidate-smoke

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-single-cluster-smoke-v4.14-single-cluster-hypershift-4-14-candidate-smoke

**Pull request merged**
