### PR TITLE
Update lp-configs firewatch to have success set 2

### PR DESCRIPTION
**Pull request by smatula**

### CODE REVIEW

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-jboss-fuse-camel-quarkus-openshift-interop-main-camel-quarkus-ocp4.15-lp-interop-camel-quarkus-interop-aws periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.15-lp-interop-csb-interop-aws-latest periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.15-lp-interop-servicemesh-interop-aws

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
