### PR TITLE
baremetalds-packet-setup: Add PACKET_PLAN parameter

### PR DESCRIPTION
**Pull request by lranjbar**
Add PACKET_PLAN parameter to the step so we can choose different plans.

### CODE REVIEW

**Comment by andfasano** [comment]
It seems fine, let's wait for some green runs

**Comment by lranjbar** [comment]
Both upgrade jobs hit this error:

- ci/rehearse/periodic-ci-openshift-release-master-nightly-4.9-e2e-metal-ipi-upgrade
- ci/rehearse/periodic-ci-openshift-assisted-service-release-ocm-2.4-e2e-metal-assisted-operator-ztp-periodic-upgrade

```
+(./04_setup_ironic.sh:139): main(): for name in ironic ironic-api ironic-conductor ironic-inspector dnsmasq httpd-${PROVISIONING_NETWORK_NAME} mariadb ipa-downloader
+(./04_setup_ironic.sh:140): main(): sudo podman ps
+(./04_setup_ironic.sh:140): main(): grep -w 'ipa-downloader$'
+(./04_setup_ironic.sh:141): main(): sudo podman ps --all
+(./04_setup_ironic.sh:141): main(): grep -w 'ipa-downloader$'
+(./04_setup_ironic.sh:145): main(): sudo podman pod exists ironic-pod
+(./04_setup_ironic.sh:150): main(): sudo podman pod create -n ironic-pod
time="2021-11-15T17:01:51Z" level=error msg="Error freeing pod lock after failed creation: no such file or directory"
Error: error adding Infra Container: error pulling infra-container image: Error initializing source docker://registry.access.redhat.com/ubi8/pause:latest: error pinging docker registry registry.access.redhat.com: invalid status code from registry 503 (Service Unavailable)
```

**Comment by lranjbar** [comment]
The cucushift job hit this error:

- ci/rehearse/periodic-ci-openshift-verification-tests-master-ocp-4.9-e2e-baremetal-cucushift-ipi

```
+(./04_setup_ironic.sh:140): main(): grep -w 'ipa-downloader$'
+(./04_setup_ironic.sh:141): main(): sudo podman ps --all
+(./04_setup_ironic.sh:141): main(): grep -w 'ipa-downloader$'
+(./04_setup_ironic.sh:145): main(): sudo podman pod exists ironic-pod
+(./04_setup_ironic.sh:150): main(): sudo podman pod create -n ironic-pod
time="2021-11-15T17:02:18Z" level=error msg="Error freeing pod lock after failed creation: no such file or directory"
Error: error adding Infra Container: error pulling infra-container image: Error initializing source docker://registry.access.redhat.com/ubi8/pause:latest: can't talk to a V1 docker registry
```
Same code lines.. different error. Will wait and see if more come

**Comment by lranjbar** [comment]
Expected to fail:
- ci/rehearse/openshift/assisted-service/release-ocm-2.4/e2e-metal-assisted-operator-disconnected

**Comment by andfasano** [comment]
None of the failures seem related to the current PR changes

/approve

**Pull request merged**
