### PR TITLE
Replace pre-commit literal Dockerfile by CI image

### PR DESCRIPTION
**Pull request by Sandeepyadav93**
This patch replaces pre-commit literal dockerfile by the CI images maintained on openstack-k8s-opertors-ci repo[1], avoiding building pre-commit image build on every PR.

[1] https://github.com/openstack-k8s-operators/openstack-k8s-operators-ci/blob/8991de5dc145964c1c8fb8c1e6fa7a31cee41e6b/images/pre-commit/Dockerfile

### CODE REVIEW

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-placement-operator-master-precommit-check

**Comment by bogdando** [comment]
why do we need both this one and https://github.com/openshift/release/pull/35761 ?

**Comment by Sandeepyadav93** [comment]
@bogdando This is for placement operator the other patch is for nova-operator.

**Review by bogdando — APPROVED** [review]

**Pull request merged**
