### PR TITLE
add user grantomation to OWNERS and azure cluster wide

### PR DESCRIPTION
**Pull request by grantomation**
/assign @mjudeikis

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@enj @deads2k is it possible for this team to write an RBAC rule that would allow them to update their own group (but no other group) at cluster scope?

**Comment by enj** [comment]
> @enj @deads2k is it possible for this team to write an RBAC rule that would allow them to update their own group (but no other group) at cluster scope?

You could grant update on that group (by name) to members of that group...  Sounds a bit recursive and if you removed yourself on accident it would lock you out, but it should work as long as cluster admin creates the group and adds the initial users.

I think a better approach would be to have two groups - one with the static, cluster admin controlled list of "group admins" and the other group as it is today (and have it managed by the users in group admins).

**Comment by stevekuznetsov** [comment]
Locking yourself out sounds fine to me -- that would be something Azure team could escalate to me. @grantomation can you add such an RBAC rule please so changing this cluster-wide file does not result in DPTP actions?

**Comment by grantomation** [comment]
I could probably look at that. What does DPTP stand for?

**Comment by petr-muller** [comment]
> I could probably look at that. What does DPTP stand for?

Developer Productivity - Test Platform. @stevekuznetsov 's team.

**Comment by grantomation** [comment]
closing in favour of https://github.com/openshift/release/pull/3465

**Pull request closed without merging**
