### PR TITLE
Change repo names to match the RHCOS repo names

### PR DESCRIPTION
**Pull request by ravanelli**
- Update repo names to match the internal RHCOS repository

Signed-off-by: Renata Ravanelli <rravanel@redhat.com>

### CODE REVIEW

**Comment by travier** [comment]
You *likely* have ti run `make update` after making those changes here.

**Review by travier — COMMENTED** [review]
/lgtm

**Comment by jlebon** [comment]
Hmm, according to CI this is missing a `make release-controllers`.

**Pull request merged**
