### PR TITLE
Allow konflux bot to run CI tests

### PR DESCRIPTION
**Pull request by coleenquadros**
Adding Konflux bot as a trusted app  to allow CI test runs on the repos

### CODE REVIEW

**Review by philipgough — APPROVED** [review]
/lgtm

**Review by Kyl-Bempah — APPROVED** [review]
/approve

**Comment by subbarao-meduri** [comment]
@coleenquadros May I suggest including only pluginconfig changes as part of this PR, and not updating the user?

**Comment by coleenquadros** [comment]
@subbarao-meduri CI was complaining there is an unverified user in the OWNERS file so removed the user to get unblocked

**Pull request merged**
