### PR TITLE
Migrate initial repos to golang-1.13 for 1.17 rebase

### PR DESCRIPTION
**Pull request by tnozicka**
/cc @deads2k 

@openshift/sig-master

### CODE REVIEW

**Comment by deads2k** [comment]
lgtm
/approve

**Comment by tnozicka** [comment]
/cc @adambkaplan 
for your repos

**Comment by tnozicka** [comment]
we are running blind here because it doesn't run rehearsal (https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/6235/pull-ci-openshift-release-master-pj-rehearse/10942#1:build-log.txt%3A111) but we need to move anyways

**Comment by tnozicka** [comment]
/hold
the fix to always use vendor folder was reverted without an explanation in https://github.com/openshift/release/pull/6279

we can't merge this or we start ignoring vendor dirs

**Comment by tnozicka** [comment]
dropped must-gather as we didn't get an approval for that path and origin went first in https://github.com/openshift/release/pull/6364 to have CI rehearsals

**Comment by tnozicka** [comment]
/hold cancel
https://github.com/openshift/release/pull/6337 is in

**Pull request merged**
