### PR TITLE
remove unused openshift-upgrade-qe-test-paused-to-latest chain and steps

### PR DESCRIPTION
**Pull request by jianlinliu**
1. `openshift-upgrade-qe-test-paused-to-latest` is not used in any ci job.
2. most of `to-latest` steps in `openshift-upgrade-qe-test-paused-to-latest` is similar to the ones in `openshift-upgrade-qe-test-paused`, later will submit more enhancement to reuse the existing steps as much as possible if need the ci coverage in the future, so that reduce some code maintenance work.
3. With https://github.com/openshift/release/pull/49743 commit, later we can reuse the step (upgrade with --to-latest option)  if need the ci coverage in the future.

### CODE REVIEW

**Comment by jianlinliu** [comment]
cc @jiajliu and @shellyyang1989 to review.

**Comment by jiajliu** [comment]
@jianlinliu There is still one candidate case https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-48683 which might use `openshift-upgrade-qe-test-paused-to-latest`. But there is also a 4.16 epic might re-position EUS-to-EUS in https://issues.redhat.com/browse/OTA-1184, which means there may be not eus-to-eus. I haven't got exact plan on the epic yet. So shall we postpone this pr until the epic is explicit to us?

**Comment by jianlinliu** [comment]
> @jianlinliu There is still one candidate case https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-48683 which might use `openshift-upgrade-qe-test-paused-to-latest`. But there is also a 4.16 epic might re-position EUS-to-EUS in https://issues.redhat.com/browse/OTA-1184, which means there may be not eus-to-eus. I haven't got exact plan on the epic yet. So shall we postpone this pr until the epic is explicit to us?

Just like I explained in the description comment, actually I have some more plan to polish the eus upgrade chain, e.g: introduce set-channel step, separate pause/unpause step in other following, and reuse cucushift-upgrade-to step in eus chain, once all the following PR get completed, it would be very easy to assumable a needed eus upgrade chain as our demands. But I need to tidy up the existing ones step by step to avoid the noise from the temporary unused steps.

**Comment by jiajliu** [comment]
> I have some more plan to polish the eus upgrade chain
ack, generally sgtm, leave it to the author yang

**Pull request merged**
