### PR TITLE
add fedora variant to cri-o CI

### PR DESCRIPTION
**Pull request by sohankunkerkar**
We will skip the e2e tests until we figure out the actual issue.

### CODE REVIEW

**Comment by sohankunkerkar** [comment]
@skyler is planning to handle the deduplication of the test and gather scripts.

**Comment by haircommander** [comment]
/approve

LGTM

**Comment by skyler** [comment]
@sohankunkerkar though an exciting challenge to be sure, I will not be doing that 😛 (I think you've tagged the wrong person).

**Pull request merged**
