### PR TITLE
MSI: add RHODS operator tests on hypershift

### PR DESCRIPTION
**Pull request by rnetser**

### CODE REVIEW

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-operator-v4.13-sanity-rosa-rhods-hypershift

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-operator-v4.13-sanity-rosa-rhods-hypershift

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-operator-v4.13-sanity-rosa-rhods-hypershift

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-operator-v4.13-sanity-rosa-rhods-hypershift

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-operator-v4.13-sanity-rosa-rhods-hypershift

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-operator-v4.13-sanity-rosa-rhods-hypershift

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-operator-v4.13-sanity-rosa-rhods-hypershift

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-operator-v4.13-sanity-rosa-rhods-hypershift

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-operator-v4.13-sanity-rosa-rhods-hypershift

**Review by omrirh — APPROVED** [review]

**Pull request merged**
