### PR TITLE
e2e and upgrade schedule update

### PR DESCRIPTION
**Pull request by rahulsharma36**
Updating schedule for e2e and upgrade jobs

### CODE REVIEW

**Comment by vrutkovs** [comment]
Why is this schedule being updated?

**Comment by rahulsharma36** [comment]
These jobs are running twice a day so we have modified it to once a day to have less load on infra to see if there is any improvement on CI test jobs
________________________________
From: Vadim Rutkovsky ***@***.***>
Sent: 28 April 2022 20:35
To: openshift/release ***@***.***>
Cc: Rahul Sharma49 ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [openshift/release] e2e and upgrade schedule update (PR #28202)

Why is this schedule being updated? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***> ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

Why is this schedule being updated?

**Comment by vrutkovs** [comment]
Lets add this to commit message

/ok-to-test

**Review by deepsm007 — APPROVED** [review]
Discussed and agreed upon during CI interlock

**Pull request merged**
