### PR TITLE
chore(SRVKP-3752): Switch Pipelines perf tests to dedicated AWS account

### PR DESCRIPTION
**Pull request by jhutar**

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/approve

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-100-x-build

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-100-x-build

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-100-x-build

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-100-x-build

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-100-x-build

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-100-x-build

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-100-x-build

**Pull request merged**
