### PR TITLE
Vboulos promote acm212 images

### PR DESCRIPTION
**Pull request by vboulos**
Promote ACM 2.12 test images for the following components

- CLC (UI)
- CLC (Non-ui)
- ALC
- GRC
- Observability

### CODE REVIEW

**Comment by vboulos** [comment]
/pj-rehearse pull-ci-stolostron-application-ui-test-release-2.12-images

**Review by gurnben — APPROVED** [review]
/lgtm
/approve

**Comment by vboulos** [comment]
rehearsals-ack

**Pull request merged**
