### PR TITLE
ocm: Enable DCO for GRC

### PR DESCRIPTION
**Pull request by dhaiducek**

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@dhaiducek can you just activate it org wide instead?

**Comment by dhaiducek** [comment]
@alvaroaleman I asked _exactly_ the same question. Apparently we have automation in some repos that is not able to provide sign-offs, so we have to do it on a per-repo basis. 🙁

**Comment by dhaiducek** [comment]
Unless you have other methods to accomplish this--I'd love to only have this enabled in one place org-wide.

**Comment by alvaroaleman** [comment]
@dhaiducek it should be possible to activate it org wide and then exclude the repos that do not need it: https://github.com/kubernetes/test-infra/blob/09560258592cf91fe8478bcf80b3d6b369b1ac65/prow/plugins/plugin-config-documented.yaml#L467 (excluded repo is just the repo name, not org/repo)

**Comment by dhaiducek** [comment]
YES! You are my hero--I didn't come across that YAML reference file in my digging. Thanks! Let me take this back to our team, and hopefully we can get this updated.

**Comment by dhaiducek** [comment]
Although, that may not be quite as acceptable since then the other plugins would be disabled for those repos also, correct? I guess in that case we'd need to re-add plugins for each of the excluded repos? (I'm just trying to think through objections people might have...)

**Comment by alvaroaleman** [comment]
> Although, that may not be quite as acceptable since then the other plugins would be disabled for those repos also, correct? I guess in that case we'd need to re-add plugins for each of the excluded repos? (I'm just trying to think through objections people might have...)

Yeah, that is true

**Comment by dhaiducek** [comment]
@alvaroaleman Thanks for your help and suggestions, but I wasn't able to convince our org to enable the DCO plugin org-wide. 😢 I'll keep pressing for it, but could we please merge this PR in the meantime?

**Review by alvaroaleman — APPROVED** [review]
/label tide/merge-method-squash

**Pull request merged**
