### PR TITLE
SPLAT-1250: Added vSphere static IP periodical.

### PR DESCRIPTION
**Pull request by vr4manta**
[SPLAT-1250](https://issues.redhat.com/browse/SPLAT-1250)

## Changes
- Added new Periodical for vSphere Static IP (4.15 & 4.16)

### CODE REVIEW

**Review by vrutkovs — APPROVED** [review]

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-static-ovn

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-static-ovn

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-static-ovn

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-static-ovn

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-static-ovn

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-static-ovn

**Pull request merged**
