### PR TITLE
NO-ISSUE: assisted vsphere test CSI driver

### PR DESCRIPTION
**Pull request by adriengentil**

### CODE REVIEW

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Pull request closed without merging**
