### PR TITLE
Multiplier for cluster-density-v2

### PR DESCRIPTION
**Pull request by paigerube14**
Want to be able to load the cluster less than 9*  for chaos tests but still want to be able to reuse cluster-density-v2 code 

CC: @chaitanyaenr

### CODE REVIEW

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-gcp-4.13-ocp-qe-perfscale-ci-tests-kube-burner

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-gcp-4.13-ocp-qe-perfscale-ci-tests-kube-burner

**Review by chaitanyaenr — APPROVED** [review]
/lgtm

**Pull request merged**
