### PR TITLE
chore(RHIDP-1001): Add job for RHDH scalability with respect to CPU and memory resources

### PR DESCRIPTION
**Pull request by pmacik**

### CODE REVIEW

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-list-catalog-resources-scalability

**Review by yogananth-subramanian — APPROVED** [review]

**Review by yogananth-subramanian — APPROVED** [review]

**Review by yogananth-subramanian — APPROVED** [review]
/lgtm

**Pull request merged**
