### PR TITLE
NTO: Add one lane to all no cluster e2e tests

### PR DESCRIPTION
**Pull request by yanirq**
Combine all e2e tests that do not require a cluster under
one lane: e2e-no-cluster and one target: test-e2e-local

Signed-off-by: Yanir Quinn <yquinn@redhat.com>

### CODE REVIEW

**Comment by jmencak** [comment]
Tests failing with `Error: failed to compute the reserved and isolated CPUs: can't allocate odd number of CPUs from a NUMA Node`

**Comment by yanirq** [comment]
> Tests failing with `Error: failed to compute the reserved and isolated CPUs: can't allocate odd number of CPUs from a NUMA Node`

yes. this test does not result in an error but should be fixed.
Also the render test should be aligned.  
These are probably side effects of https://github.com/openshift/cluster-node-tuning-operator/pull/344 - tests not aligned properly to these changes.  
I will work on a fix.

**Review by fromanirh — COMMENTED** [review]
/lgtm

**Pull request merged**
