### PR TITLE
openstack: Add optional e2e-openstack job to CIRO

### PR DESCRIPTION
**Pull request by trown**

### CODE REVIEW

**Comment by trown** [comment]
https://github.com/openshift/cluster-image-registry-operator/pull/292 broke the openstack e2e job, this patch will allow running `/test e2e-openstack` on patches to that repo

**Comment by mandre** [comment]
/lgtm

CIRO broke the deployment against openstack before, we need to run the e2e-openstack job there.

**Comment by adambkaplan** [comment]
fyi @dmage

**Pull request merged**
