### PR TITLE
rebasebot: Always rebase from latest release branch for IBM

### PR DESCRIPTION
**Pull request by RadekManak**
This PR add script that fetches all branches from GitHub API for cloud-provider-ibm and determines the latest release branch to that will be used when running the rebasebot command.

### CODE REVIEW

**Comment by elmiko** [comment]
lgtm, let's see how the rehearse goes. thanks again!

**Comment by JoelSpeed** [comment]
/lgtm
/pj-rehearse ack

Picked up the right branch

**Comment by RadekManak** [comment]
/pj-rehearse ack
Added the same change for powervs repository.

**Pull request merged**
