### PR TITLE
cert-rotation: workaround ovn not creating CSRs on aws 

### PR DESCRIPTION
**Pull request by vrutkovs**
Use a workaround for https://issues.redhat.com/browse/OCPBUGS-42001 in AWS cert rotation tests

### CODE REVIEW

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-ha-cert-rotation-suspend-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-ha-cert-rotation-suspend-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-ha-cert-rotation-suspend-30d periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-ovn-ha-cert-rotation-suspend-30d periodic-ci-openshift-release-master-nightly-4.16-e2e-aws-ovn-ha-cert-rotation-suspend-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-ha-cert-rotation-suspend-30d periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-ovn-ha-cert-rotation-suspend-30d periodic-ci-openshift-release-master-nightly-4.16-e2e-aws-ovn-ha-cert-rotation-suspend-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-ha-cert-rotation-suspend-30d periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-ovn-ha-cert-rotation-suspend-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-ha-cert-rotation-suspend-30d periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-ovn-ha-cert-rotation-suspend-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-aws-ovn-ha-cert-rotation-suspend-30d

**Review by dinhxuanvu — COMMENTED** [review]
/lgtm

**Pull request merged**
