### PR TITLE
HOSTEDCP-1078: hypershift: add cluster_profile

### PR DESCRIPTION
**Pull request by sjenning**

### CODE REVIEW

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn

**Comment by sjenning** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-release-4.14-e2e-hypershift-ovn

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn-conformance

**Review by bryan-cox — APPROVED** [review]
/lgtm

**Pull request merged**
