### PR TITLE
increase the azure-qe-quota-slice to 30

### PR DESCRIPTION
**Pull request by MayXuQQ**
in order to avoid the {  failed to acquire lease for "azure-qe-quota-slice": resources not found}

### CODE REVIEW

**Comment by MayXuQQ** [comment]
/assign @wking
thanks

**Review by wking — APPROVED** [review]
I know nothing about this cloud account, but here's a blind:

/lgtm

Ideally, this sort of thing should be paired with some cloud-account quota increases, because you don't help anything by replacing:

> failed to acquire lease for "azure-qe-quota-slice": resources not found

with:

> ...failed to install because resource X is out of quota...

See 1b664ccf6d7416b70097e1388b39c3f0bae82de3 (#12840) for me doing some Azure quota calculations for `azure4-quota-slice` back in 2020 (expected Azure cluster resource consumption may have evolved since then).  I'm dropping a hold in case you want to do that sort of calculation here, but pull the hold if you don't want to, because it's not my account ;)

/hold

**Comment by MayXuQQ** [comment]
azure-qe-quota-slice used in QE test.  and I will ask DDP team to increase the quotas.  
this is current quota. 
=======centralus=======
Standard DSv3 Family vCPUs                     3000
Public IP Addresses                                      50
Public IP Addresses - Standard                    40
=======northcentralus=======
Standard DSv3 Family vCPUs                1000
Public IP Addresses                                    40
Public IP Addresses - Standard               1000
=======westus3=======
Standard DSv3 Family vCPUs                   350
Public IP Addresses                               1000
Public IP Addresses - Standard            1000

**Comment by jianlinliu** [comment]
Let us assume 1 clusters have 6 nodes, 4 vcpu per node, sounds like westus3's vcpu need some increase later.

**Comment by MayXuQQ** [comment]
> Let us assume 1 clusters have 6 nodes, 4 vcpu per node, sounds like westus3's vcpu need some increase later.

I've open ticket to increase the quota.

**Comment by jianlinliu** [comment]
> Ideally, this sort of thing should be paired with some cloud-account quota increases

Yeah, this is already taken into our consideration.

**Pull request merged**
