### PR TITLE
Add caikit-tgis and vllm CI for 2.13

### PR DESCRIPTION
**Pull request by rpancham**
Addresses : https://issues.redhat.com/browse/RHOAIENG-11133

### CODE REVIEW

**Comment by vaibhavjainwiz** [comment]
/pj-rehearse pull-ci-red-hat-data-services-vllm-rhoai-2.13-images

**Comment by rpancham** [comment]
/pj-rehearse pull-ci-red-hat-data-services-vllm-rhoai-2.13-images

**Comment by Xaenalt** [comment]
/pj-rehearse pull-ci-red-hat-data-services-vllm-rhoai-2.13-images

**Pull request merged**
