### PR TITLE
Remove jobs that do not have jobs data for test analysis

### PR DESCRIPTION
**Pull request by DennisPeriquet**
Re: [TRT-407](https://issues.redhat.com//browse/TRT-407)

When `job-run-aggregator analyze-test-case ...` gets "found no related jobRuns", it's fatal.  We want to suppress this so we can analyze the rest of the jobs.

In this PR, I remove those jobs to avoid getting errors.

### CODE REVIEW

**Comment by dgoodwin** [comment]
Is it more correct to ignore errors in the script, or to not return 1 from the command itself? I'm legit not sure...

**Comment by xueqzhan** [comment]
> Is it more correct to ignore errors in the script, or to not return 1 from the command itself? I'm legit not sure...

We are running this script to go through all variants. When one variant fails, it does make sense for job-run-aggregator to return an error. But the overall script should continue with the following variants.

@DennisPeriquet Can you confirm that we are producing a junit even if there is no job run found? If not, we need to produce one somewhere.

**Comment by DennisPeriquet** [comment]
@xueqzhan there is nothing written when there is no related jobs.  @xueqzhan @dgoodwin See what you think about https://github.com/openshift/ci-tools/pull/3002/files.

This will allow us to keep `set -o errexit` to catch all the other errors that might happen.
I feel a little "unprotected" when I take that out.

**Comment by DennisPeriquet** [comment]
```
test-output/
└── artifacts
    ├── aws-ovn-ipi
    │   └── 4.12.0-0.nightly-2022-09-12-152748
    │       ├── job-run-summary.html
    │       └── junit-test-case-analysis.xml
    ├── aws-ovn-upi
    │   └── 4.12.0-0.nightly-2022-09-12-152748 <-- empty
    ├── aws-sdn-ipi
    │   └── 4.12.0-0.nightly-2022-09-12-152748
    │       ├── job-run-summary.html
    │       └── junit-test-case-analysis.xml
```

**Comment by xueqzhan** [comment]
If we know for sure that we do not have certain variants with the nightly payload, we should just remove those variants from the script. 

If the aggregator is asked to aggregate on certain variants and couldn't find any job runs to aggregate, should we create a junit in the aggregator for that?

**Comment by DennisPeriquet** [comment]
I removed the jobs without job data since they will just create unnecessary noise.

**Comment by DennisPeriquet** [comment]
Removing the combinations that have no jobs data gives us a clean set of junit tests:

```
$ tree test-output/
test-output/
└── artifacts
    ├── aws-ovn-ipi
    │   └── 4.12.0-0.nightly-2022-09-12-152748
    │       ├── job-run-summary.html
    │       └── junit-test-case-analysis.xml
    ├── aws-sdn-ipi
    │   └── 4.12.0-0.nightly-2022-09-12-152748
    │       ├── job-run-summary.html
    │       └── junit-test-case-analysis.xml
    ├── aws-sdn-upi
    │   └── 4.12.0-0.nightly-2022-09-12-152748
    │       ├── job-run-summary.html
    │       └── junit-test-case-analysis.xml
    ├── azure-ovn-ipi
    │   └── 4.12.0-0.nightly-2022-09-12-152748
    │       ├── job-run-summary.html
    │       └── junit-test-case-analysis.xml
    ├── gcp-sdn-ipi
    │   └── 4.12.0-0.nightly-2022-09-12-152748
    │       ├── job-run-summary.html
    │       └── junit-test-case-analysis.xml
    ├── metal-ovn-ipi
    │   └── 4.12.0-0.nightly-2022-09-12-152748
    │       ├── job-run-summary.html
    │       └── junit-test-case-analysis.xml
    ├── metal-sdn-ipi
    │   └── 4.12.0-0.nightly-2022-09-12-152748
    │       ├── job-run-summary.html
    │       └── junit-test-case-analysis.xml
    ├── vsphere-ovn-ipi
    │   └── 4.12.0-0.nightly-2022-09-12-152748
    │       ├── job-run-summary.html
    │       └── junit-test-case-analysis.xml
    ├── vsphere-ovn-upi
    │   └── 4.12.0-0.nightly-2022-09-12-152748
    │       ├── job-run-summary.html
    │       └── junit-test-case-analysis.xml
    └── vsphere-sdn-ipi
        └── 4.12.0-0.nightly-2022-09-12-152748
            ├── job-run-summary.html
            └── junit-test-case-analysis.xml

21 directories, 20 files
```

**Pull request merged**
