### PR TITLE
logging - add rsyslog image

### PR DESCRIPTION
**Pull request by richm**
logging - add rsyslog image

### CODE REVIEW

**Comment by richm** [comment]
@jcantrill

**Comment by jcantrill** [comment]
@richm Did we get approval from @smarterclayton to merge this?  Why does the eventrouter need a fedora base?

**Comment by smarterclayton** [comment]
We’re trying to not include more fedora images in CI.  Everything should be buildable from a rhel base, except for the few special cases.  Anything based on Go should definitely not be based on fedora

**Pull request merged**
