### PR TITLE
OSASINFRA-3555: hypershift/openstack: handle Ingress

### PR DESCRIPTION
**Pull request by EmilienM**
This PR adds the necessary steps and CLI options to HCP e2e so we can get a working cluster deploy with Ingress.

### CODE REVIEW

**Comment by mdbooth** [comment]
I see we merged the dns stuff :( My preference would be to remove it. This makes testing difficult.

**Comment by EmilienM** [comment]
Thanks for the approvals. I'm going to make sure DNS works and I'll ack pj rehearse.
Note that the DNS step here is just until I find out whether we can leverage the external-dns-operator with AWS provider to take care of the ingress endpoint. cc @mdbooth

**Comment by EmilienM** [comment]
DNS worked:
* https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/55115/rehearse-55115-pull-ci-openshift-hypershift-main-e2e-openstack/1819445353250820096/artifacts/e2e-openstack/openstack-provision-dnsrecords/artifacts/dns_up.json
* https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/55115/rehearse-55115-pull-ci-openshift-hypershift-main-e2e-openstack/1819445353250820096/artifacts/e2e-openstack/openstack-provision-dnsrecords/build-log.txt
/hold cancel

**Pull request merged**
