### PR TITLE
HCO: move OKD tests to install by operator-sdk

### PR DESCRIPTION
**Pull request by nunnatsa**

### CODE REVIEW

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-operator-sdk-aws

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-operator-sdk-gcp

**Review by orenc1 — APPROVED** [review]

**Pull request merged**
