### PR TITLE
Add 4.7 remote libvirt upgrade tests

### PR DESCRIPTION
**Pull request by r4f4**
I'm taking over the work started at https://github.com/openshift/release/pull/10728

### CODE REVIEW

**Comment by r4f4** [comment]
This depends on https://github.com/openshift/origin/pull/25491.

**Comment by r4f4** [comment]
Depends on https://github.com/openshift/origin/pull/25586

**Comment by r4f4** [comment]
Depends on https://github.com/openshift/release/pull/16485

**Review by alvaroaleman — APPROVED** [review]
/label tide/merge-method-squash

**Pull request merged**
