### PR TITLE
Sync Serverless CI config/

### PR DESCRIPTION
**Pull request by serverless-qe**

### CODE REVIEW

**Comment by skonto** [comment]
cc @dsimansk @pierDipi

**Comment by skonto** [comment]
>  Uploading finished
The ImageStreamTag "ubi-minimal:latest" is invalid: from: Error resolving ImageStreamTag ubi-minimal:latest in namespace openshift-marketplace: unable to find latest tagged image

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-net-kourier-release-v1.16-413-images
/pj-rehearse pull-ci-openshift-knative-net-istio-release-v1.16-417-images
/pj-rehearse pull-ci-openshift-knative-serving-release-v1.16-417-images

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by cardil** [comment]
/pj-rehearse pull-ci-openshift-knative-kn-plugin-event-release-1.16-416-e2e-aws-416

**Comment by cardil** [comment]
/pj-rehearse auto-ack

The changes https://github.com/openshift/release/compare/f4e33062d7b943ec17e16a6009fec76582876c2d..9498f91fb2ad97231f057bfc6f004d47b7e4ff36 looks to be expected from https://github.com/openshift-knative/hack/pull/388

The changes look okay to me, but I will not slap lgtm just before the long weekend.

**Comment by cardil** [comment]
This will fix the kn-event test failure: https://github.com/openshift-knative/kn-plugin-event/pull/546

**Comment by cardil** [comment]
/pj-rehearse pull-ci-openshift-knative-kn-plugin-event-release-1.16-416-e2e-aws-416

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Review by matejvasek — APPROVED** [review]

**Pull request merged**
