### PR TITLE
coreos/coreos-assembler: run RHCOS tests on rhcos-4.9 and rhcos-4.8

### PR DESCRIPTION
**Pull request by jlebon**
This effectively backports openshift#23972 to the RHCOS branches.

### CODE REVIEW

**Comment by jlebon** [comment]
Requires: https://github.com/openshift/release/pull/23972
And requires https://github.com/coreos/coreos-assembler/pull/2578 backported to all those branches.

**Comment by jlebon** [comment]
OK, so `rhcos-4.8` and `rhcos-4.9` will fail because of https://github.com/coreos/coreos-assembler/pull/2598#issuecomment-985729167. I'd suggest just overriding those and if any adjustments are needed, it'd be on the cosa side anyway so we'll fix it there.

**Comment by jlebon** [comment]
/override ci/rehearse/coreos/coreos-assembler/rhcos-4.8/rhcos
/override ci/rehearse/coreos/coreos-assembler/rhcos-4.9/rhcos

**Review by cgwalters — APPROVED** [review]

**Pull request merged**
