### PR TITLE
periodic cert-rotation: add comments and update OWNERS

### PR DESCRIPTION
**Pull request by sallyom**
add comments and update OWNERS, update cron

### CODE REVIEW

**Comment by sallyom** [comment]
I was hoping this would kick a rehearse of the 4.6,4.7 cert-rotation jobs but it did not :shrug:

**Comment by sallyom** [comment]
/assign @soltysh 

* added you to the OWNERS :) i'll ask @damemi if he wouldn't mind, though, instead :) 
* added the last suggestions from review and fixed the curl cmd
* updated cron to run M,W,F

**Comment by sallyom** [comment]
/hold

I'm using this PR to run rehearse to optimize the script & remove flakes

**Comment by sallyom** [comment]
* i'm expecting 4.5 rehearse to fail, as it does not have the fix: https://github.com/openshift/cluster-kube-scheduler-operator/pull/288 
* rerunning to discover/fix flakes

/retest

**Comment by sallyom** [comment]
2 greens in a row... going for 3

/test pj-rehearse

**Comment by sallyom** [comment]
@soltysh i made some minor changes such as increasing timeout with oc commands, bumping retries. I've seen a much higher percentage of green tests - had 4 in a row so I think this should merge now, thanks

/hold cancel

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Review by droslean — APPROVED** [review]

**Pull request merged**
