### PR TITLE
OCPQE-24492 - removing optional , so that from this point onwards , we could review…

### PR DESCRIPTION
**Pull request by miyadav**
… all sast issues

/pj-rehearse pull-ci-openshift-cluster-api-provider-gcp-master-security

### CODE REVIEW

**Comment by miyadav** [comment]
@JoelSpeed @elmiko , removed `optional: true` , as this was having '0' vulnerabilities , going forward we can keep its sanity ( depending on reviews of the issues reported by test ) .
We can do similar for other repos , where dev have put effort to have '0' vulnerabilities.
@shellyyang1989 @sunzhaohua2 @huali9

**Comment by JoelSpeed** [comment]
I'd like to discuss this with the engineering team before we merge
/hold

**Comment by JoelSpeed** [comment]
@miyadav We discussed and concluded that we think this would be ok to trial, but, we need to understand how we would update the configuration if we found an issue that we could not easily resolve. Do you have a way to declaratively add an exception to a configuration file in the repository?

**Comment by JoelSpeed** [comment]
/approve
/lgtm
/pj-rehearse ack
/hold cancel

Discussed during our team QE sync today, going to move this forward

**Pull request merged**
