### PR TITLE
Pointing io tests image to the 4.14 branch

### PR DESCRIPTION
**Pull request by JoaoFula**

### CODE REVIEW

**Review by droslean — APPROVED** [review]

**Comment by JoaoFula** [comment]
Hello @jupierce could I get an approval on this PR? You're being requested because I'm removing the mirroring jobs for IO test suite for versions prior to 4.11

**Comment by JoaoFula** [comment]
Hello @jupierce @bparees @dhellmann, could we get an approval on this PR please?

**Pull request merged**
