### PR TITLE
RHOC: Add credentials secret mount

### PR DESCRIPTION
**Pull request by asmigala**

### CODE REVIEW

**Comment by MrSantamaria** [comment]
Hmmm from the logs I think the harness you are using is the cause of the Ginkgo Leak. 
@ritmun have you seen this error with the addon harnesses?

**Comment by asmigala** [comment]
@MrSantamaria there's definitely a bug in our harness, I'll get to fixing that next week.

**Comment by MrSantamaria** [comment]
If you get too stuck you can reach us at #sd-cicd

**Pull request merged**
