### PR TITLE
Stop promoting to openshift-psap managed namespaces

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
/cc @kpouget @hongkailiu 
https://issues.redhat.com/browse/DPTP-2613

**Comment by ArangoGutierrez** [comment]
Thanks @kpouget , but why the hold?

**Comment by ArangoGutierrez** [comment]
I see, yeah let's wait for PT comments  thanks K

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
