### PR TITLE
OCPQE-26319 add 4.14 auto release jobs

### PR DESCRIPTION
**Pull request by rioliu-rh**
add e2e/upgrade auto release jobs for 4.14 release

### CODE REVIEW

**Comment by rioliu-rh** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-automated-release-stable-4.14-upgrade-from-stable-4.13-aws-ipi-f360

**Comment by rioliu-rh** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-automated-release-aws-ipi-f360

**Comment by rioliu-rh** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-automated-release-stable-4.14-upgrade-from-stable-4.14-gcp-ipi-f360

**Review by tomasdavidorg — APPROVED** [review]
/lgtm

**Pull request merged**
