### PR TITLE
kubevirt: ssp: add tests for release-v0.16 branch in common-templates

### PR DESCRIPTION
**Pull request by ksimon1**
add tests for release-v0.16 branch in common-templates
Signed-off-by: Karel Šimon <ksimon@redhat.com>
/approve cancel

### CODE REVIEW

**Comment by akrejcir** [comment]
Can you prefix the commit message and this PR's name with `kubevirt: ssp: `?  So it is clear to which project this PR and commit belongs, without looking at the code.

**Comment by ksimon1** [comment]
I can, but in the future PR. I need to get this PR merged ASAP

**Comment by akrejcir** [comment]
ok

/lgtm

**Pull request merged**
