### PR TITLE
Various cleanups for CoreOS-related things

### PR DESCRIPTION
**Pull request by jlebon**
See individual commits.

### CODE REVIEW

**Comment by jlebon** [comment]
/pj-rehearse pull-ci-openshift-os-master-images
/pj-rehearse pull-ci-openshift-os-master-scos-9-build-test-qemu
/pj-rehearse pull-ci-openshift-os-master-rhcos-9-build-test-qemu

**Comment by jlebon** [comment]
/pj-rehearse pull-ci-openshift-os-master-images
/pj-rehearse pull-ci-openshift-os-master-scos-9-build-test-qemu
/pj-rehearse pull-ci-openshift-os-master-rhcos-9-build-test-qemu

**Comment by jlebon** [comment]
/pj-rehearse pull-ci-openshift-os-master-images pull-ci-openshift-os-master-scos-9-build-test-qemu pull-ci-openshift-os-master-rhcos-9-build-test-qemu

**Comment by jlebon** [comment]
/pj-rehearse pull-ci-openshift-os-master-images pull-ci-openshift-os-master-scos-9-build-test-qemu pull-ci-openshift-os-master-rhcos-9-build-test-qemu

**Comment by travier** [comment]
/pj-rehearse pull-ci-openshift-os-master-rhcos-9-build-test-qemu

**Comment by jlebon** [comment]
Folded https://github.com/openshift/release/pull/59083 into this one.

/cc @bear-redhat

**Comment by jlebon** [comment]
/pj-rehearse pull-ci-openshift-os-master-rhcos-9-build-test-qemu pull-ci-openshift-os-master-rhcos-9-build-test-metal

**Comment by deepsm007** [comment]
/override ci/prow/ordered-prow-config

not related to the PR

**Pull request merged**
