### PR TITLE
openshift/os: Use coreos-assembler:4.9 for 4.9

### PR DESCRIPTION
**Pull request by cgwalters**
This is now SOP and we should try to ensure it happens as part of
the openshift branching.

### CODE REVIEW

**Review by saqibali-2k — APPROVED** [review]

**Comment by cgwalters** [comment]
OK, some sort of repo sync problems.  Whee.

**Comment by cgwalters** [comment]
Hmm OK actually it seems like the failure is somehow specific to this PR, which is confusing.   The build in https://github.com/openshift/os/pull/625 at least got past this point.

**Review by travier — APPROVED** [review]

**Pull request merged**
