### PR TITLE
move assisted-tools related steps to workflows

### PR DESCRIPTION
**Pull request by osherdp**
In preparation for [MGMT-9583](https://issues.redhat.com/browse/MGMT-9583) (allowing to trigger some periodic jobs on-demand using cluster-bot) this change creates the relevant workflows so that we can take leverage of the ``workflow-launch`` command.

Another thing it does is move the ``tools`` related steps/workflows to be under ``assisted`` instead of ``assisted-baremetal``, as it has no use of an actual baremetal machine.

### CODE REVIEW

**Comment by michaellevy101** [comment]
I understand that this just a technical refactor and it's a step forward. 
can you please explain what's the purpose of those tools?

**Comment by osherdp** [comment]
> I understand that this just a technical refactor and it's a step forward. can you please explain what's the purpose of those tools?

Sure
* bump-ocp: uses some API to understand if there are new stable releases for the various ``major.minor`` release (z-streams). So if it detects there's a new version ``4.10.11`` and we currently have ``4.10.10`` in our ``default_release_images.json`` file, it creates a PR to update that value.
* ci-status-report: goes over presubmit jobs for assisted-installer related repositories, and outputs a graph with the results: how many have failed, how many have succeeded, how many aborted etc. Output is visible in slack, and the status is daily.
* triage-status-report: goes over triage jira tickets and outputs their details in slack.
* snapshot-repos: updates [assisted-installer.yaml](https://github.com/openshift-assisted/assisted-installer-deployment/blob/master/assisted-installer.yaml) with recent revisions of master branches of the different components. QE team are daily taking this kind of output, and installing an environment with those exact revisions. It is being done because ``integration`` system can be updated in-mid testing and it's not that easy to understand which exact "version" it tested. So this is a good alternative for testing a specific snapshot that we can correlate with the actual code.

**Pull request merged**
