### PR TITLE
Adding Kuttl tests to master branch

### PR DESCRIPTION
**Pull request by varshab1210**
Signed-off-by: varshab1210 <vab@redhat.com>

### CODE REVIEW

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.8-e2e

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.8-kuttl-sequential

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.9-kuttl-parallel

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.9-kuttl-sequential

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.10-kuttl-sequential

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.10-kuttl-sequential

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.8-e2e

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.8-kuttl-sequential

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.10-kuttl-sequential

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.9-kuttl-parallel

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.9-kuttl-sequential

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.10-kuttl-sequential

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.8-kuttl-parallel

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.10-kuttl-sequential

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.9-kuttl-sequential

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.10-kuttl-sequential

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.10-kuttl-sequential

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.10-kuttl-sequential

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.10-kuttl-sequential

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.10-kuttl-sequential

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.10-kuttl-sequential

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.10-kuttl-sequential

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.10-kuttl-sequential

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.10-kuttl-sequential

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.10-kuttl-sequential

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.10-kuttl-sequential

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.9-kuttl-parallel

**Comment by danilo-gemoli** [comment]
/lgtm
as I'm not sure what Tide is actually doing

**Pull request merged**
