### PR TITLE
[maistra] Add OPERATOR_VERSION variable for test suite to skip unsupported tests

### PR DESCRIPTION
**Pull request by mkralik3**

### CODE REVIEW

**Comment by mkralik3** [comment]
/pj-rehearse periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.16-lp-interop-servicemesh-interop-aws

**Comment by mkralik3** [comment]
/pj-rehearse periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.16-lp-interop-servicemesh-interop-aws

**Comment by mkralik3** [comment]
/pj-rehearse periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.16-lp-interop-servicemesh-interop-aws

**Comment by mkralik3** [comment]
/pj-rehearse periodic-ci-maistra-maistra-test-tool-main-servicemesh-hypershift-4.15-lp-rosa-hypershift-servicemesh-aws-rosa-hypershift periodic-ci-maistra-maistra-test-tool-main-servicemesh-hypershift-4.14-lp-rosa-hypershift-servicemesh-aws-rosa-hypershift

**Comment by mkralik3** [comment]
/pj-rehearse periodic-ci-maistra-maistra-test-tool-main-servicemesh-hypershift-4.15-lp-rosa-hypershift-servicemesh-aws-rosa-hypershift

**Review by FilipB — APPROVED** [review]

**Pull request merged**
