### PR TITLE
add pre-merge test for OAR

### PR DESCRIPTION
**Pull request by jianzhangbjz**
As title,

### CODE REVIEW

**Comment by jianzhangbjz** [comment]
/pj-rehearse pull-ci-openshift-release-tests-master-oar-check

**Comment by jianzhangbjz** [comment]
/pj-rehearse pull-ci-openshift-release-tests-master-oar-check

**Comment by jianzhangbjz** [comment]
/pj-rehearse pull-ci-openshift-release-tests-master-oar-check

**Comment by jianzhangbjz** [comment]
/pj-rehearse pull-ci-openshift-release-tests-master-oar-check

**Comment by jianzhangbjz** [comment]
/pj-rehearse pull-ci-openshift-release-tests-master-oar-check

**Comment by jianzhangbjz** [comment]
/pj-rehearse pull-ci-openshift-release-tests-master-oar-check

**Comment by jianzhangbjz** [comment]
/pj-rehearse pull-ci-openshift-release-tests-master-oar-check

**Comment by jianzhangbjz** [comment]
/pj-hearse periodic-ci-openshift-release-tests-master-stable-build-test

**Comment by jianzhangbjz** [comment]
/pj-hearse periodic-ci-openshift-release-tests-master-stable-build-test

**Comment by jianzhangbjz** [comment]
Hi @kuiwang02 @Xia-Zhao-rh could you help approve it when you get a chance? Thanks!

**Comment by wewang58** [comment]
/lgtm 
thanks

**Pull request merged**
