### PR TITLE
Set all available versions for assisted-test-infra system-test job

### PR DESCRIPTION
**Pull request by YuviGold**

### CODE REVIEW

**Comment by omertuc** [comment]
Doesn't an empty OPENSHIFT_VERSION mean default to `4.7`? Doesn't seem to fit your commit message.
Did you mean `OPENSHIFT_VERSIONS`?

**Comment by omertuc** [comment]
Please don't LGTM without author addressing review comments...

**Comment by YuviGold** [comment]
> Doesn't an empty OPENSHIFT_VERSION mean "default to `4.7`"? Doesn't seem to fit your commit message.
> Did you mean `OPENSHIFT_VERSIONS`?

It depends on the workflow. On the pytest workflow there is no default as presented on https://github.com/openshift/assisted-test-infra/pull/688/files#diff-fd319f80628e389daf226c94bb6aa50ae1fce37b80a4b7221f6da81fbe0094f8R118-R126
But on second thought.. Maybe it should remain to test only the default. Let's see if it works, if not I'll revert.

@eliorerz next time please see if the tests finished. In case not (and I forgot to) please set an <hold> label

**Comment by YuviGold** [comment]
Verified. system-test job now runs against all the available versions. (4.6, 4.7, 4.8)

**Pull request merged**
