### PR TITLE
CNF-11459: update ptp test jobs to use new telco-runner image

### PR DESCRIPTION
**Pull request by nishant-parekh**

### CODE REVIEW

**Review by jzding — APPROVED** [review]
/lgtm

**Comment by nishant-parekh** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-telco5g-ptp

**Comment by nishant-parekh** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-telco5g-ptp

**Comment by nishant-parekh** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-telco5g-ptp

**Comment by nishant-parekh** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-telco5g-ptp

**Comment by nishant-parekh** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-telco5g-ptp

**Comment by nishant-parekh** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-telco5g-ptp

**Comment by nishant-parekh** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-telco5g-ptp

**Comment by nishant-parekh** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-telco5g-ptp

**Pull request merged**
