### PR TITLE
Remove all ovn-upgrade jobs for 4.5->4.6

### PR DESCRIPTION
**Pull request by jluhrsen**
4.5 and 4.6 are deprecated and with OVN not deployed
as default these jobs are mostly noise at this point.
This is a result of a conversation in:
  https://bugzilla.redhat.com/show_bug.cgi?id=1977969

Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>

### CODE REVIEW

**Comment by petr-muller** [comment]
@abhat my opinion is not important, we run the platform and do not own the actual jobs that validate the product. 

Historically, we were always told that as platform owners, we should not remove any jobs even for EOLed OCP versions - see https://issues.redhat.com/browse/DPTP-1877 for some more context, but the conversation there was mostly about jobs on PRs which does not necessarily apply here. You may want to consult the job removal with staff engineers to be sure. There are also lighter alternatives to job removal, such as reducing trigger intervals and/or removing such jobs from release-controller configs.

**Comment by abhat** [comment]
@petr-muller agreed. I was deferring to your opinion mostly because the folks who run the platform know what other teams are doing and what are the recommendations for EOL'd OCP release. Having said that, we will work with staff-engineers to understand whether these jobs can be removed completely or reduced in frequency. 4.6 is EUS so we may not be able to get rid of all the jobs. However, whether we will support an upgrade from 4.5 to 4.6 (which is the release OVN became GA) is debatable. cc @jluhrsen @candita

**Review by wking — APPROVED** [review]
/lgtm

**Comment by wking** [comment]
/hold

I forgot I'm an approver for these dirs now.  Holding in case anyone else wants to weigh in.

**Comment by jluhrsen** [comment]
@abhat , approve this?

**Pull request merged**
