### PR TITLE
Add periodic-ci-operator-yaml-creator

### PR DESCRIPTION
**Pull request by alvaroaleman**
Adds a periodic for creating PRs on the ocp payload repos with the
.ci-operator.yaml file.

Ref https://issues.redhat.com/browse/DPTP-2245

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/hold
This should only start running after branchcut

**Comment by alvaroaleman** [comment]
@jupierce should we cancel the hold now that branch cut is done?

**Comment by jupierce** [comment]
@alvaroaleman let's do it!

**Pull request merged**
