### PR TITLE
KAM | Add CI versions OCP 4.11-4.13

### PR DESCRIPTION
**Pull request by varshab1210**
Updatig OCP versions in Openshift CI to 4.9-4.13

### CODE REVIEW

**Comment by wtam2018** [comment]
@varshab1210 I know it it in draft. When you get it ready, please add some description to the PR. Thanks.

**Comment by varshab1210** [comment]
@wtam2018 Updated the description
As I mentioned earlier, we need to skip CI tests. Shall I proceed?

**Review by wtam2018 — COMMENTED** [review]
/lgtm

**Pull request merged**
