### PR TITLE
Moving vSphere CI to a larger public subnet

### PR DESCRIPTION
**Pull request by jcpowermac**

### CODE REVIEW

**Comment by dav1x** [comment]
LGTM

**Comment by wking** [comment]
vSphere rehearsal [failed][1], and was unable to SSH into the bootstrap machine to gather logs?

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/5544/rehearse-5544-pull-ci-openshift-installer-master-e2e-vsphere/4

**Comment by dav1x** [comment]
> vSphere rehearsal [failed](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/5544/rehearse-5544-pull-ci-openshift-installer-master-e2e-vsphere/4), and was unable to SSH into the bootstrap machine to gather logs?

At the moment the CI job is using the older subnet from a different VLAN. Once this change is applied the VMs should be using the correct larger VLAN.

**Comment by jcpowermac** [comment]
> vSphere rehearsal [failed](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/5544/rehearse-5544-pull-ci-openshift-installer-master-e2e-vsphere/4), and was unable to SSH into the bootstrap machine to gather logs?

@wking we use terraform state to determine the ip addresses of the virtual machines.  Unfortunately with the current issue with RHCOS the machines will reboot back into DHCP and the addresses are wrong.

**Comment by jcpowermac** [comment]
The rehearse test will continue to fail until we have a resolution for: https://bugzilla.redhat.com/show_bug.cgi?id=1762509
Which I hope will soon be available (last night RHCOS was still pivoting to an older release)

**All** vSphere pre-4.3 jobs will now **fail** because the ESXi host that was attached to the previous subnet via the port group no longer exists.  The only network subnet the new ESXi has access to is `139.178.87.128/25`.  Hence the need for this PR to be merged.

**Pull request merged**
