### PR TITLE
oVirt: increase minimal jobs memory

### PR DESCRIPTION
**Pull request by Gal-Zaidman**
This PR increases the mem for workers and masters on minimal jobs

Signed-off-by: Gal-Zaidman <gzaidman@redhat.com>

### CODE REVIEW

**Comment by Gal-Zaidman** [comment]
Ovirt jobs will not pass due to:
- resources
- https://github.com/openshift/machine-config-operator/pull/2209
Since this PR works (checked the machines created on the env) I'm comfortable with it

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
