### PR TITLE
Fix building of binaries in OpenTelemetry jobs

### PR DESCRIPTION
**Pull request by IshwarKanse**

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-ocp-4.14-amd64-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-ocp-4.14-amd64-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-ocp-4.14-amd64-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-ocp-4.14-amd64-opentelemetry-e2e-tests

**Review by vprashar2929 — APPROVED** [review]
/lgtm

**Pull request merged**
