### PR TITLE
kni: scheduler: enable security scanning

### PR DESCRIPTION
**Pull request by ffromani**
per https://docs.ci.openshift.org/docs/how-tos/add-security-scanning/

### CODE REVIEW

**Comment by ffromani** [comment]
cc @shajmakh @swatisehgal

**Comment by creydr** [comment]
#44912 should contain the fix for the failing rehearse job

**Comment by ffromani** [comment]
> #44912 should contain the fix for the failing rehearse job

thanks!

**Comment by ffromani** [comment]
/pj-rehearse pull-ci-openshift-kni-scheduler-plugins-master-security

**Comment by ffromani** [comment]
/pj-rehearse pull-ci-openshift-kni-scheduler-plugins-master-security

**Review by swatisehgal — COMMENTED** [review]
The PR looks good to me but the newly added job seems to be failing and the failures seems legit. Do we plan to fix this?

**Comment by ffromani** [comment]
> The PR looks good to me but the newly added job seems to be failing and the failures seems legit. Do we plan to fix this?

yes, fixes will be coming with PRs against the repo (scheduler-plugins in this case), e.g https://github.com/openshift-kni/scheduler-plugins/pull/153

**Review by swatisehgal — APPROVED** [review]
/lgtm

Some tests are failing which is not ideal but it is a clear sign that the job introduced in this PR is working. The work to resolve the failures is already ongoing in the relevant repo so no reason to block this PR.

**Pull request merged**
