### PR TITLE
use devsandboxci-aws cluster profile for all toolchain repos

### PR DESCRIPTION
**Pull request by MatousJobanek**
it looks like that it worked https://github.com/openshift/release/pull/48430

toolchain-e2e job that used the profile: https://storage.googleapis.com/test-platform-results/pr-logs/pull/codeready-toolchain_toolchain-e2e/895/pull-ci-codeready-toolchain-toolchain-e2e-master-e2e/1763303482275663872/build-log.txt

### CODE REVIEW

**Review by mfrancisc — APPROVED** [review]
/lgtm

**Review by sbryzak — APPROVED** [review]

**Pull request merged**
