### PR TITLE
console-operator: build with golang 1.13

### PR DESCRIPTION
**Pull request by stlaz**
/assign @jhadvig

### CODE REVIEW

**Comment by jhadvig** [comment]
```
level=error msg="Failed to rehearse jobs" error="failed to create watch for ProwJobs: Get https://172.30.0.1:443/apis/prow.k8s.io/v1/namespaces/ci/prowjobs?labelSelector=ci.openshift.org%2Frehearse%3D8087&watch=true: unexpected EOF" pr=8087
ERROR: pj-rehearse: rehearsal tool failure
```

**Comment by benjaminapetersen** [comment]
Nice, thx!

**Comment by benjaminapetersen** [comment]
/lgtm 
as well

**Pull request merged**
