### PR TITLE
MGMT-13708: ensure ztp jobs use internal builds

### PR DESCRIPTION
**Pull request by adriengentil**
Export the required variables for the script that deploys the index to
overwrite the assisted images with the ones build internaly by the job.

### CODE REVIEW

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-release-ocm-2.7-e2e-ai-operator-ztp

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-disconnected

**Comment by adriengentil** [comment]
ci/rehearse/openshift/assisted-installer/release-ocm-2.7/e2e-ai-operator-ztp was expected to fail :partying_face: because of a bug introduced in the controller

**Comment by adriengentil** [comment]
ci/rehearse/openshift/assisted-installer/master/edge-e2e-ai-operator-ztp and ci/rehearse/openshift/assisted-installer/release-ocm-2.7/e2e-ai-operator-ztp are both flakes

**Review by osherdp — APPROVED** [review]

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-master-edge-e2e-ai-operator-ztp

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-master-edge-e2e-ai-operator-ztp

**Pull request merged**
