### PR TITLE
Update Tempo jobs

### PR DESCRIPTION
**Pull request by IshwarKanse**
Update and test the jobs to include the new test suites.

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-grafana-tempo-operator-main-upstream-ocp-4.14-amd64-gcp-ipi-ovn-ipsec-tempo-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-grafana-tempo-operator-main-upstream-ocp-4.14-amd64-gcp-ipi-ovn-ipsec-tempo-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-grafana-tempo-operator-main-upstream-ocp-4.14-amd64-gcp-ipi-ovn-ipsec-tempo-e2e-tests pull-ci-openshift-grafana-tempo-operator-main-upstream-ocp-4.16-amd64-aws-ipi-shared-vpc-phz-sts-tempo-e2e-tests pull-ci-openshift-grafana-tempo-operator-main-upstream-upgrade-ocp-4.17-amd64-azure-tempo-operator-upgrade

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-grafana-tempo-operator-main-upstream-ocp-4.14-amd64-gcp-ipi-ovn-ipsec-tempo-e2e-tests pull-ci-openshift-grafana-tempo-operator-main-upstream-upgrade-ocp-4.17-amd64-azure-tempo-operator-upgrade

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-grafana-tempo-operator-main-upstream-ocp-4.16-amd64-aws-ipi-shared-vpc-phz-sts-tempo-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-grafana-tempo-operator-main-upstream-ocp-4.16-amd64-aws-ipi-shared-vpc-phz-sts-tempo-e2e-tests

**Review by vprashar2929 — APPROVED** [review]
/lgtm

**Pull request merged**
