### PR TITLE
chore: jvm-build-service: rename e2e jobs

### PR DESCRIPTION
**Pull request by psturc**
Since we're no longer leveraging appstudio for running in-repo-e2e, it'd make sense to give e2e `make` targets a more accurate name

[related changes in jvm-build-service](https://github.com/redhat-appstudio/jvm-build-service/pull/397/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R30-R33)

### CODE REVIEW

**Comment by psturc** [comment]
@gabemontero I'm sorry to bother you with this, but since you're the only one from the owners list who has a deep knowledge of jvm-build-service, would you have couple of minutes to this and related PR a look? Thanks.

follow-up action item: help Stuart to request the membership in openshift org :)

**Comment by gabemontero** [comment]
> @gabemontero I'm sorry to bother you with this, but since you're the only one from the owners list who has a deep knowledge of jvm-build-service, would you have couple of minutes to this and related PR a look? Thanks.
> 
> follow-up action item: help Stuart to request the membership in openshift org :)

no worries ... that said, I've learned from the OCP pr's I got pulled into that they've changed how things work a bit.  You have to explicitly ask for rehearsals now.

**Comment by psturc** [comment]
@gabemontero cool, but I guess they won't pass until [these changes](https://github.com/redhat-appstudio/jvm-build-service/pull/397/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R30-R33) are merged. And vice versa, so I guess we're kinda in a deadlock here :)

**Comment by gabemontero** [comment]
> @gabemontero cool, but I guess they won't pass until [these changes](https://github.com/redhat-appstudio/jvm-build-service/pull/397/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R30-R33) are merged. And vice versa, tests in that PR won't pass as well, so I guess we're kinda in a deadlock here :)

@psturc I would update your jvm-build-service PR to include both the old and new makefile directive name.  Once that merges, you can do this PR.  Then after this PR merges, you can remove the old one in jvm-build-service.

That is the only way I know to resolve the deadlock.

**Review by gabemontero — CHANGES_REQUESTED** [review]
@psturc you should also remove the `jvm-build-service-e2e` job for this repo since you other PR removes the scripts in the .ci folder

**Pull request merged**
