### PR TITLE
Remove failing NetworkGranular tests for POWER

### PR DESCRIPTION
**Pull request by ravanelli**
There is an open issue to fix it. However,
we need blacklist the tests until we have a fix for it.

Signed-off-by: Renata Ravanelli <rravanel@redhat.com>

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/uncc
I can not review testchanges

**Comment by clnperez** [comment]
lgtm
and will try tests one more time. good to see the network ones all pass :D 

/retest
/cc @jaypoulz

**Comment by clnperez** [comment]
/retest

this time trouble bringing up the cluster:
```
Could not update prometheusrule \"openshift-cloud-credential-operator/cloud-credential-operator-alerts\" (163 of 573): the server does not recognize this resource, check extension API servers\n* Could not update prometheusrule \"openshift-cluster-samples-operator/samples-operator-alerts\" (282 of 573): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-apiserver-operator/openshift-apiserver-operator\" (561 of 573): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-authentication-operator/authentication-operator\" (482 of 573): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-cluster-machine-approver/cluster-machine-approver\" (492 of 573): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-cluster-version/cluster-version-operator\" (8 of 573): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-console-operator/console-operator\" (517 of 573): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-controller-manager-operator/openshift-controller-manager-operator\" (567 of 573): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-dns-operator/dns-operator\" (520 of 573): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-etcd-operator/etcd-operator\" (523 of 573): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-image-registry/image-registry\" (488 of 573): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-ingress-operator/ingress-operator\" (526 of 573): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-kube-apiserver-operator/kube-apiserver-operator\" (529 of 573): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-kube-controller-manager-operator/kube-controller-manager-operator\" (537 of 573): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-kube-scheduler-operator/kube-scheduler-operator\" (545 of 573): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-machine-api/cluster-autoscaler-operator\" (199 of 573): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-machine-api/machine-api-operator\" (550 of 573): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-machine-config-operator/machine-config-daemon\" (552 of 573): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-operator-lifecycle-manager/olm-operator\" (556 of 573): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-service-ca-operator/service-ca-operator\" (573 of 573): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-service-catalog-apiserver-operator/openshift-service-catalog-apiserver-operator\" (496 of 573): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-service-catalog-controller-manager-operator/openshift-service-catalog-controller-manager-operator\" (500 of 573): the server does not recognize this resource, check extension API servers"
```

the 4.4 ci tests failed with a lot of in-tree volume test failures today, so we'll see if this hits that as well.

**Comment by clnperez** [comment]
> the 4.4 ci tests failed with a lot of in-tree volume test failures today, so we'll see if this hits that as well.

Turns out that was a disk-pressure issue in the prow infra. No idea why this keeps failing to create a cluster. The 4.4 ci is fine now. @ravanelli will have to debug as it is her PR (so only she has permission to the job contents).

**Comment by ravanelli** [comment]
Cloud you please approve this PR @bbguimaraes or @jaypoulz ?
All test are good now.

**Comment by jaypoulz** [comment]
Only the people in the file linked above can give the "Approved" label. :)

See:
https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/release/OWNERS

I will give you my approval blessing nonetheless, meaningless as it may be 😸

**Review by jaypoulz — APPROVED** [review]

**Comment by ravanelli** [comment]
Thanks @jaypoulz  :joy: I will wait for @bbguimaraes so

**Comment by ravanelli** [comment]
Hi @crawford and @petr-muller cloud you please approve this PR?

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
