### PR TITLE
[WiP] assisted installer: copy source from src

### PR DESCRIPTION
**Pull request by rccrdpccl**
Trying to have CI to handle copying source files, so we can drop `COPY . .` instruction from dockerfile

### CODE REVIEW

**Comment by rccrdpccl** [comment]
My intention is to remove `COPY . .` from `Dockerfile.assisted-service-build`, and this PR seems to prove that it will work. @osherdp could you please make sure I am not overlooking anything? :pray:

**Comment by osherdp** [comment]
> 

No, it looks good
Keep in mind that there's only one job that relies on assisted-service-build right now (``publish-python-client``) so with a little modification we can also remove the need of this ``src`` copying

**Comment by rccrdpccl** [comment]
Thanks @osherdp . Do you mean by creating a specific dockerfile for that job? Would you suggest going down that route or just merge "this" (I will open a clean PR) and its related change in the target repo?

**Comment by rccrdpccl** [comment]
I've added back the job but it seems that is not executing in the reharse.... Am I doing it wrong?

**Comment by osherdp** [comment]
ahh... it doesn't rehearse postsubmit jobs
you can transform it to presubmit for this check, it shouldn't do anything wrong

**Comment by rccrdpccl** [comment]
@osherdp I am not too familiar with this job, but it looks like it broke when uploading, after it has been generated from source:

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/30780/pull-ci-openshift-release-master-pj-rehearse/1555587045403922432

Do you think this is enough to test this PR?

**Comment by osherdp** [comment]
I think this problem got fixed a few days ago
Let's see how it retest

**Comment by rccrdpccl** [comment]
It looks like the test passed, https://github.com/openshift/release/pull/31076 is ready to be merged if you agree @osherdp

**Pull request closed without merging**
