### PR TITLE
Add job for testing KubeVirt against OCP 4.6

### PR DESCRIPTION
**Pull request by dhiller**
Adds a configuration to test KubeVirt release-0.33 against OCP 4.6

### CODE REVIEW

**Comment by dhiller** [comment]
Latest run show one failure: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/12070/rehearse-12070-periodic-ci-kubevirt-kubevirt-release-0.33-e2e-periodic-azure-nested-virt/1308367290793725952

`Storage Starting a VirtualMachineInstance [rfe_id:2288][crit:high][vendor:cnv-qe@redhat.com][level:component]With Alpine ISCSI PVC [test_id:3139]should be successfully started `

**Comment by dhiller** [comment]
[Test failure is due to flaky test.](https://github.com/kubevirt/kubevirt/issues/4204)

**Comment by dhiller** [comment]
/override periodic-ci-kubevirt-kubevirt-release-0.33-e2e-periodic-azure-nested-virt
/override pj-rehearse

**Comment by stu-gott** [comment]
/override periodic-ci-kubevirt-kubevirt-release-0.33-e2e-periodic-azure-nested-virt
/override pj-rehearse
/lgtm

**Comment by dhiller** [comment]
> /override periodic-ci-kubevirt-kubevirt-release-0.33-e2e-periodic-azure-nested-virt
> /override pj-rehearse
> /lgtm

@stu-gott thanks for the review!

**Pull request merged**
