### PR TITLE
USHIFT-2074: Add periodics to capture problems with microshift clusterbot workflow

### PR DESCRIPTION
**Pull request by pmtk**

### CODE REVIEW

**Comment by pmtk** [comment]
/pj-rehearse periodic-ci-openshift-microshift-main-clusterbot

**Comment by pmtk** [comment]
/pj-rehearse periodic-ci-openshift-microshift-release-4.15-clusterbot periodic-ci-openshift-microshift-release-4.14-clusterbot

**Comment by pmtk** [comment]
/pj-rehearse periodic-ci-openshift-microshift-main-clusterbot

**Review by pacevedom — COMMENTED** [review]
/lgtm

**Pull request merged**
