### PR TITLE
Fix upgrade job

### PR DESCRIPTION
**Pull request by sgaoshang**

### CODE REVIEW

**Comment by sgaoshang** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-4.14-upgrade-from-stable-4.13-vsphere-ipi-proxy-workers-rhel8-f28

**Comment by sgaoshang** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-4.14-upgrade-from-stable-4.13-vsphere-ipi-proxy-workers-rhel8-f28

**Comment by sgaoshang** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-4.14-upgrade-from-stable-4.13-vsphere-ipi-proxy-workers-rhel8-f28

**Comment by sgaoshang** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-4.14-upgrade-from-stable-4.13-vsphere-ipi-proxy-workers-rhel8-f28

**Comment by sgaoshang** [comment]
@jianlinliu @jinyunma pls help review it, thanks.

**Comment by jianlinliu** [comment]
cc @liangxia to review.

**Pull request merged**
