### PR TITLE
Add kuttl test in e2e job for ansiblee-opertor

### PR DESCRIPTION
**Pull request by cescgina**
Run the build-deploy-kuttl workflow instead of the build-deploy one.

### CODE REVIEW

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-ansibleee-operator-main-ansibleee-operator-build-deploy-kuttl

**Comment by cescgina** [comment]
Needs https://github.com/openstack-k8s-operators/install_yamls/pull/171 to fix failing kuttl tests

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-ansibleee-operator-main-ansibleee-operator-build-deploy-kuttl

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-ansibleee-operator-main-ansibleee-operator-build-deploy-kuttl

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-ansibleee-operator-main-ansibleee-operator-build-deploy-kuttl

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-ansibleee-operator-main-ansibleee-operator-build-deploy-kuttl

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-ansibleee-operator-main-ansibleee-operator-build-deploy-kuttl

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-ansibleee-operator-main-ansibleee-operator-build-deploy-kuttl

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-ansibleee-operator-main-ansibleee-operator-build-deploy-kuttl

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-ansibleee-operator-main-ansibleee-operator-build-deploy-kuttl

**Comment by cescgina** [comment]
/pj-rehearse ack 
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/37626/rehearse-37626-pull-ci-openstack-k8s-operators-openstack-ansibleee-operator-main-ansibleee-operator-build-deploy-kuttl/1640652655460093952/artifacts/ansibleee-operator-build-deploy-kuttl/openstack-k8s-operators-kuttl/build-log.txt

**Comment by Sandeepyadav93** [comment]
/lgtm

Based on current target in install_yamls for ansibleee[1]

[1] https://github.com/openstack-k8s-operators/install_yamls/blob/master/Makefile#L165-L171

**Pull request merged**
