### PR TITLE
Getting rosa 4.16 pieces ready for the tests

### PR DESCRIPTION
**Pull request by vishnuchalla**
### Description
Getting a PR ready for ROSA 4.16. Will get it merged when we have our CI back to the normal state.

### Testing
Will verify through rehearsal jobs.

### CODE REVIEW

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-ec-x86-cluster-density-v2-249nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-ec-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-data-path-9nodes
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-control-plane-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-control-plane-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-heavy-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-cni-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-heavy-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-node-density-heavy-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-node-density-cni-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-control-plane-120nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-control-plane-120nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-cni-120nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-node-density-cni-120nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-control-plane-249nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-control-plane-249nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-cni-249nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-node-density-cni-249nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-conc-builds-3nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-conc-builds-3nodes

**Comment by vishnuchalla** [comment]
> /lgtm

@skordas Thanks for the review. Please kindly wait until I tag the reviewers please. I am still running some of the experiments and this PR is likely  going to be open for a while.

**Comment by vishnuchalla** [comment]
> > /lgtm
> 
> @skordas Thanks for the review. Please kindly wait until I tag the reviewers. I am still running some of the experiments and this PR is likely going to be open for a while.

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-heavy-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-heavy-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-heavy-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-heavy-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-heavy-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-heavy-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-heavy-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-heavy-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-control-plane-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-cni-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-heavy-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-heavy-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-control-plane-120nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-heavy-24nodes

**Comment by krishvoor** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-control-plane-120nodes pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-heavy-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-control-plane-120nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-heavy-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-heavy-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-heavy-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-heavy-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-heavy-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-heavy-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-node-density-heavy-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-heavy-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-control-plane-120nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-heavy-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-control-plane-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-control-plane-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-control-plane-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-cni-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-heavy-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-control-plane-120nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-cni-120nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-control-plane-249nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-control-plane-24nodes
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-node-density-heavy-24nodes
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-node-density-cni-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-node-density-heavy-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-node-density-cni-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-control-plane-120nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-node-density-cni-120nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-control-plane-249nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-heavy-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-control-plane-249nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-control-plane-249nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-control-plane-249nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse ci/rehearse/openshift-qe/ocp-qe-perfscale-ci/main/rosa-4.15-nightly-x86-control-plane-249nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-control-plane-249nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-node-density-cni-249nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-control-plane-249nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-node-density-cni-249nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-control-plane-249nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse ci/rehearse/periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.16-nightly-x86-data-path-9nodes

**Pull request closed without merging**
