### PR TITLE
STOR-1731: Add e2e workflow for SMB csi driver

### PR DESCRIPTION
**Pull request by dobsonj**
https://issues.redhat.com/browse/STOR-1731

This adds an e2e test workflow for smb-csi-driver-operator to run the `openshift/csi` test suite.

/hold for https://github.com/openshift/csi-operator/pull/210 to merge first
/cc @openshift/storage @jsafrane @mpatlasov

### CODE REVIEW

**Comment by dobsonj** [comment]
/pj-rehearse pull-ci-openshift-csi-operator-master-ci-index-smb-csi-driver-operator-bundle pull-ci-openshift-csi-operator-master-smb-operator-e2e

**Comment by dobsonj** [comment]
/pj-rehearse pull-ci-openshift-csi-operator-master-ci-index-smb-csi-driver-operator-bundle pull-ci-openshift-csi-operator-master-smb-operator-e2e pull-ci-openshift-csi-operator-master-e2e-aws-csi pull-ci-openshift-csi-operator-master-e2e-azure-csi pull-ci-openshift-csi-operator-master-e2e-azure-file-csi pull-ci-openshift-csi-operator-master-images

**Comment by dobsonj** [comment]
/pj-rehearse pull-ci-openshift-csi-operator-master-ci-index-smb-csi-driver-operator-bundle pull-ci-openshift-csi-operator-master-smb-operator-e2e pull-ci-openshift-csi-operator-master-e2e-aws-csi pull-ci-openshift-csi-operator-master-e2e-azure-csi pull-ci-openshift-csi-operator-master-e2e-azure-file-csi pull-ci-openshift-csi-operator-master-images

**Comment by dobsonj** [comment]
/pj-rehearse pull-ci-openshift-csi-operator-master-smb-operator-e2e

**Comment by dobsonj** [comment]
/pj-rehearse pull-ci-openshift-csi-operator-master-smb-operator-e2e pull-ci-openshift-csi-operator-master-e2e-azure-file-csi

**Comment by dobsonj** [comment]
[it works!](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/50871/rehearse-50871-pull-ci-openshift-csi-operator-master-smb-operator-e2e/1779136701386461184)
/unhold
/pj-rehearse ack

**Review by mpatlasov — APPROVED** [review]

**Pull request merged**
