### PR TITLE
Move 4.3-4.7 calico jobs to step-registry

### PR DESCRIPTION
**Pull request by jluhrsen**
The real work for this was done for 4.8 by @vruktovs here:
https://github.com/openshift/release/pull/18367

Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>

### CODE REVIEW

**Review by vrutkovs — APPROVED** [review]
/lgtm

Thanks!

**Review by vrutkovs — APPROVED** [review]
4.7 passed
4.6 fails on insecure metrics for kube-proxy (afaik there's a bug for that)
/approve
/lgtm

**Comment by jluhrsen** [comment]
the 4.6 job is failing due to [kube-proxy does not provide secure metrics endpoint](https://bugzilla.redhat.com/show_bug.cgi?id=1971809)

4.5 job also fails for the kube-proxy metrics problem, but there is another test case (Monitor cluster while tests execute" that
is perma-failing and looks like some invalid resources are trying to be accesses. non existent git repos
(e.g., https://github.com/openshift/non-working-example.git, or http://my.docker/build)

4.4 is failing the e2e-aws-calico-openshift-e2e-test pod right away, but I can't find a reason why.

4.3 is failing to install every time.

I will update this PR to only do this work for 4.6+ We will still have the old version of these jobs for 4.3-5 running, but
they are permafailing so I'm guessing they are not that important:

https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-calico-4.3
https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-calico-4.4
https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-calico-4.5

**Comment by jluhrsen** [comment]
@vrutkovs , can we get an override on the failing 4.6 job. this is the bz for it:
https://bugzilla.redhat.com/show_bug.cgi?id=1971809

**Review by vrutkovs — APPROVED** [review]
/lgtm

**Comment by vrutkovs** [comment]
Rehearsals are not necessary to pass. You need `/approve` from TRT to have this merged

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
