### PR TITLE
Move oc packet jobs to new equinix profile

### PR DESCRIPTION
**Pull request by ardaguclu**
The current packet account will soon be closed. This PR moves to new packet account, namely equinix-ocp-metal.

### CODE REVIEW

**Comment by ardaguclu** [comment]
cc: @andfasano @derekhiggins

**Comment by ardaguclu** [comment]
@soltysh could you please take a look at this change?. Old cluster_profile will be removed and we are moving to new cluster_profile. Thanks.

**Comment by derekhiggins** [comment]
@mfojtik  would you be able to take a look please, the old account it due to close tomorrow

**Pull request merged**
