### PR TITLE
add four rosacli upgrade jobs

### PR DESCRIPTION
**Pull request by yuwang-RH**
Add jobs for rosacli upgrade,
rosa-sts-upgrade-z-stream-f3
rosa-hcp-upgrade-z-stream-f3
rosa-sts-upgrade-y-stream-f3
rosa-hcp-upgrade-y-stream-f3

### CODE REVIEW

**Comment by yuwang-RH** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-sts-upgrade-z-stream-f3

**Comment by yuwang-RH** [comment]
@ciaranRoche Could you review and approve this?Thanks.

**Review by robpblake — APPROVED** [review]
/lgtm

**Pull request merged**
