### PR TITLE
openstack: Run the upi tests against Dockerfile

### PR DESCRIPTION
**Pull request by pierreprinetti**
Run the e2e-openstack-upi test suite when the CI Dockerfile is changed.

### CODE REVIEW

**Comment by pierreprinetti** [comment]
Is the regex syntax right? I guess we'll only find out once it's merged!

/cc EmilienM mandre

**Comment by EmilienM** [comment]
> Is the regex syntax right? I guess we'll only find out once it's merged!

yes, I tested it

/lgtm
/approve

**Comment by pierreprinetti** [comment]
/assign @sdodson

Following the bot's suggestion.

**Pull request merged**
