### PR TITLE
SBO - expand rosa-hypershift testing to OCP 4.12

### PR DESCRIPTION
**Pull request by ascerra**
We started testing the install of the operator a few weeks ago for rosa-hypershift 4.13 this just extends the testing to also test on 4.12.

### CODE REVIEW

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-redhat-developer-service-binding-operator-release-v1.3.x-4.12-acceptance-lp-rosa-hypershift-412

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-redhat-developer-service-binding-operator-release-v1.3.x-4.12-acceptance-lp-rosa-hypershift-412

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-redhat-developer-service-binding-operator-release-v1.3.x-4.12-acceptance-lp-rosa-hypershift-412

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-redhat-developer-service-binding-operator-release-v1.3.x-4.12-acceptance-lp-rosa-hypershift-412

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-redhat-developer-service-binding-operator-release-v1.3.x-4.12-acceptance-lp-rosa-hypershift-412

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-redhat-developer-service-binding-operator-release-v1.3.x-4.12-acceptance-lp-rosa-hypershift-412

**Review by sadlerap — APPROVED** [review]

**Pull request merged**
