### PR TITLE
WIP Generate e2e test from ci-operator config

### PR DESCRIPTION
**Pull request by bbguimaraes**
Generate an E2E test from the ci-operator configuration.

It's an afternoon hack (I think "MVP" is the correct euphemism here), but
already generates a job equivalent to the one created manually.  Some of the
open questions:

1. The implementation is highly specialized for the "deploy cluster, run this
   command" type of template, which is the only type we have.  If we plan to
   add templates with different inputs, we need to consider how to pass different
   sets of parameters to the template.
2. Do we want the test definitions in the ci-operator configuration file?
   The code in the PR hijacks the `tests` list, do we want a dedicated
   top-level key, a specific format in `tests`, …?

### CODE REVIEW

**Comment by bbguimaraes** [comment]
@droslean @petr-muller @stevekuznetsov

**Comment by stevekuznetsov** [comment]
I think we'll need optional subtypes for each type of job, using pointers to structs in the test struct like we did in the step struct to allow users to pass in more data. This looks like a great step on the path to migrate from template to ci-op native!!

**Comment by petr-muller** [comment]
The generator got it's own repo: https://github.com/openshift/ci-operator-prowgen

**Pull request closed without merging**
