### PR TITLE
correct the zone names for the second AWS account

### PR DESCRIPTION
**Pull request by droslean**
/cc @openshift/openshift-team-developer-productivity-test-platform 
Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

### CODE REVIEW

**Comment by alvaroaleman** [comment]
Why were the old zones wrong and why are the new ones correct?

**Comment by droslean** [comment]
> Why were the old zones wrong and why are the new ones correct?

My mistake. I looked in the wrong place in AWS console and I add the wrong zones in the configuration.

**Comment by alvaroaleman** [comment]
> My mistake. I looked in the wrong place in AWS console and I add the wrong zones in the configuration.

I don't understand, us-east-1 _is_ a valid zone

**Comment by droslean** [comment]
> I don't understand, us-east-1 is a valid zone

Where did you see that?

**Comment by droslean** [comment]
/hold

Perhaps I am a little bit confused about how the Zone thing works.. I will dig this.

**Comment by droslean** [comment]
@coverprice Can you help me understand what are the available zones for the 2nd AWS account?

**Comment by alvaroaleman** [comment]
/hold

This needs references on what failed how and why we expect this to improve the situation

**Comment by coverprice** [comment]
I don't know much about Boskos, but from the PR, it seems you removed valid region names. What was the specific problem? The new account is just a regular account, it doesn't have any restrictions about zones (apart from the exotic rarely-used ones that need to be enabled).

**Pull request closed without merging**
