### PR TITLE
[preflight] Install dependencies to support podman CLI

### PR DESCRIPTION
**Pull request by samira-barouti**
For the container certification, preflight needs to leverage podman CLI
to pull/inspect/run/delete containers. This PR installs
the required packages for podman CLI.

### CODE REVIEW

**Review by jomkz — APPROVED** [review]
/lgtm

**Review by bcrochet — APPROVED** [review]
/lgtm

**Comment by samira-barouti** [comment]
Since we are using podman cli, this PR is no longer needed.

**Pull request closed without merging**
