### PR TITLE
USHIFT-1878: MicroShift workflow for clusterbot

### PR DESCRIPTION
**Pull request by pmtk**
/hold
/cc

### CODE REVIEW

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-clusterbot-test

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-clusterbot-test

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-clusterbot-test

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-clusterbot-test

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-clusterbot-test

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-clusterbot-test

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-clusterbot-test

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-clusterbot-test

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-clusterbot-test

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-clusterbot-test

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-clusterbot-test

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-clusterbot-test-source

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-clusterbot-test

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.14-clusterbot-test-414

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-clusterbot-test pull-ci-openshift-microshift-main-clusterbot-test-source pull-ci-openshift-microshift-release-4.14-clusterbot-test-414

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-clusterbot-test pull-ci-openshift-microshift-main-clusterbot-test-source pull-ci-openshift-microshift-release-4.14-clusterbot-test-414

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-clusterbot-test pull-ci-openshift-microshift-main-clusterbot-test-source pull-ci-openshift-microshift-release-4.14-clusterbot-test-414

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-clusterbot-test pull-ci-openshift-microshift-main-clusterbot-test-source pull-ci-openshift-microshift-release-4.14-clusterbot-test-414

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-clusterbot-test pull-ci-openshift-microshift-main-clusterbot-test-source pull-ci-openshift-microshift-release-4.14-clusterbot-test-414

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-clusterbot-test pull-ci-openshift-microshift-main-clusterbot-test-source pull-ci-openshift-microshift-release-4.14-clusterbot-test-414

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-metal-tests

**Review by pacevedom — APPROVED** [review]
/lgtm

**Pull request merged**
