### PR TITLE
ci-tools: build job-run-aggregator

### PR DESCRIPTION
**Pull request by petr-muller**
/cc @deads2k @stbenjam

### CODE REVIEW

**Comment by petr-muller** [comment]
yeah I'd like to see `ci/rehearse/openshift/ci-tools/master/images` to pass and then I'll unhold

**Comment by petr-muller** [comment]
known problems in ci-tools tests

**Comment by dgoodwin** [comment]
What would be the resulting pullspec for this image? We're having a little trouble locating it.

**Comment by petr-muller** [comment]
`registry.ci.openshift.org/ci/job-run-aggregator:latest` but the imagestreams in `ci` namespace are mirrored to all build farms so you should be able to just do `image: job-run-aggregator:latest` in pods anywhere.

**Pull request merged**
