### PR TITLE
switch monitoring projects to golang 1.16

### PR DESCRIPTION
**Pull request by raptorsun**

### CODE REVIEW

**Comment by simonpasquier** [comment]
I would only touch `*-master.yaml`, `*-4.8.yaml` and `*-4.9.yaml` files because OpenShift <= 4.7 use older versions of Go. ping @paulfantom

**Comment by raptorsun** [comment]
> I would only touch `*-master.yaml`, `*-4.8.yaml` and `*-4.9.yaml` files because OpenShift <= 4.7 use older versions of Go. ping @paulfantom

acknowledged. 4.8 and 4.9 will upgrade to golang 1.16 while the rest are left intact. 👍

**Comment by dgrisonnet** [comment]
I would agree with Simon that we don't need to touch older versions of OCP since we already know that tooling is working.

That said, it made me notice that we still haven't updated our release images to `rhel-8-golang-1.16-openshift-4.8`, but since we are close to code freeze, I would be quite reluctant to do the upgrade. Although, I don't think we would encounter any particular issue with that. wdyt @simonpasquier @paulfantom?

**Comment by paulfantom** [comment]
It looks like not all projects can be updated to `1.16` immediately due to issues with code vendoring. I would suggest excluding them for now and update in a follow-up PR. Otherwise lgtm.

**Comment by raptorsun** [comment]
removed openshift-kube-rbac-proxy, prom-label-proxy and grafana from the upgrade to golang 1.16, another PR will be created for them.

**Comment by paulfantom** [comment]
Seems like `prometheus` is also failing :shrug:

**Comment by raptorsun** [comment]
The error from prometheus is expected, this pull request is used to pave the road for the [PR of upgrading prometheus to v2.26.1](https://github.com/openshift/prometheus/pull/86).

For the other failed tests, i need more checking.

**Comment by simonpasquier** [comment]
@raptorsun the failures on the various `vendor` jobs are expected and they will be fixed the next time someone wants to merge a PR.

**Pull request merged**
