### PR TITLE
OCPBUGS-32016: Wait for sriov-operator Pods to be running

### PR DESCRIPTION
**Pull request by MaysaMacedo**
This commits ensures that the sriov related Pods
are all running before creating a node policy.

### CODE REVIEW

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-release-4.16-e2e-openstack-hwoffload

**Comment by MaysaMacedo** [comment]
/pj-rehearse  pull-ci-openshift-sriov-network-operator-release-4.16-e2e-openstack-nfv-hwoffload

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-release-4.16-e2e-openstack-nfv-hwoffload

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-machine-api-provider-openstack-release-4.16-e2e-openstack-nfv-intel

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-machine-api-provider-openstack-release-4.16-e2e-openstack-nfv-intel

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-machine-api-provider-openstack-release-4.16-e2e-openstack-nfv-intel

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-machine-api-provider-openstack-release-4.16-e2e-openstack-nfv-intel

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-machine-api-provider-openstack-release-4.16-e2e-openstack-nfv-intel

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-machine-api-provider-openstack-release-4.16-e2e-openstack-nfv-intel

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-release-4.16-e2e-openstack-hwoffload

**Comment by MaysaMacedo** [comment]
Example of failure that we've hit:

https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/51417/rehearse-51417-pull-ci-openshift-machine-api-provider-openstack-release-4.16-e2e-openstack-nfv-intel/1793349164441014272

**Comment by EmilienM** [comment]
Thanks a lot Maysa for taking care of this one.
/lgtm
/pj-rehearse ack

**Pull request merged**
