### PR TITLE
Update jenkins for 4.13 branch

### PR DESCRIPTION
**Pull request by akram**
Update jenkins for 4.13 branch

### CODE REVIEW

**Review by jmguzik — APPROVED** [review]

**Comment by jmguzik** [comment]
@jupierce probably you have rights to approve this. Related slack: https://coreos.slack.com/archives/CBN38N3MW/p1664371278800219

**Comment by akram** [comment]
/override ci/rehearse/openshift/jenkins/release-4.12/e2e-aws-jenkins-client-plugin

**Pull request merged**
