### PR TITLE
[INTEROP-7456] [INTEROP-7458] Create FIPS test for skupper/Service InterConnect; create .config.prowgen for slack_reporter config.

### PR DESCRIPTION
**Pull request by dfrazzette**
Created FIPS periodic job to test FIPS compliance for Service InterConnect on OCP 4.17 FIPS cluster. Also updated `.config.prowgen` file to include `slack_reporter` config for interop tests.

### CODE REVIEW

**Comment by dfrazzette** [comment]
pj-rehearse periodic-ci-skupperproject-skupper-openshift-smoke-test-image-main-service-interconnect-ocp4.17-lp-interop-rhsi-interop-aws-fips

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
