### PR TITLE
Update che-operator and chectl tests config

### PR DESCRIPTION
**Pull request by tolusha**
### What does this PR do
Use OpenShift 4.11 and 4.12 to run tests on

### CODE REVIEW

**Comment by tolusha** [comment]
/pj-rehearse pull-ci-eclipse-che-che-operator-main-v12-operator-test

**Comment by tolusha** [comment]
/pj-rehearse pull-ci-che-incubator-chectl-main-v12-chectl pull-ci-che-incubator-chectl-main-v11-chectl

**Comment by tolusha** [comment]
/pj-rehearse pull-ci-che-incubator-chectl-main-v12-chectl-devworkspace-happy-path

**Comment by tolusha** [comment]
/pj-rehearse pull-ci-eclipse-che-che-operator-main-v12-che-behind-proxy pull-ci-eclipse-che-che-operator-main-v12-devworkspace-happy-path

**Comment by tolusha** [comment]
/pj-rehearse pull-ci-che-incubator-chectl-main-v12-chectl pull-ci-che-incubator-chectl-main-v11-chectl

**Comment by tolusha** [comment]
@smg247
Could you have a look please?

**Review by smg247 — APPROVED** [review]

**Pull request merged**
