### PR TITLE
Bug 1975966: Disable Arc conformance tests

### PR DESCRIPTION
**Pull request by fabianofranz**
[Azure Arc Conformance Tests](https://github.com/Azure/azure-arc-validation/) have changed recently so we're temporarily disabling the entire suite in order to save resources while we work to adjust it to the new format.

### CODE REVIEW

**Comment by fabianofranz** [comment]
@bradmwilliams @hasbro17 can you take a look?

**Comment by bradmwilliams** [comment]
@fabianofranz If your intention is to eventually enable these jobs again, at least for the release-controller changes, you can simply add the `"disabled": true,` flag to each of the definitions.

**Comment by bradmwilliams** [comment]
@fabianofranz Just noticed... if the definitions are removed from `ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml`, then they will also have to be removed from the release-controller definitions, or its going to fail validation.
Sorry for the churn!

**Review by bradmwilliams — APPROVED** [review]

**Comment by fabianofranz** [comment]
@hasbro17 @joelddiaz @petr-muller or @frobware I'm looking for an approver, mind taking a look? tks!

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
