### PR TITLE
WIP: Refactoring & Templating test

### PR DESCRIPTION
**Pull request by bmanzari**
Explore the ability to 

- leverage jinja templates for agent YAML files

### CODE REVIEW

**Comment by aleskandro** [comment]
Is there any other step in this repo doing it? I do not like the `curl` approach so much, and I'm even not sure a refactoring of these scripts is worth it with the state of the art (infra to be concluded yet).

I'm also strongly opposed to the agent on BM scripts to diverge from the BM ones. If anything will be done that impacts BM the infra, it has to be for both.

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-arm64-nightly-baremetal-sno-agent-ipv4-static-connected-f7

**Comment by pamoedom** [comment]
Hi @bmanzari, I also have some concerns about this refactoring and using external scripts, can you please elaborate on the purpose? is there any blockade you are suffering with the current location?

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-arm64-nightly-baremetal-sno-agent-ipv4-static-connected-f7

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-arm64-nightly-baremetal-sno-agent-ipv4-static-connected-f7

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-arm64-nightly-baremetal-sno-agent-ipv4-static-connected-f7

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-arm64-nightly-baremetal-sno-agent-ipv4-static-connected-f7

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-arm64-nightly-baremetal-sno-agent-ipv4-static-connected-f7

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-arm64-nightly-baremetal-sno-agent-ipv4-static-connected-f7

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-arm64-nightly-baremetal-sno-agent-ipv4-static-connected-f7

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-arm64-nightly-baremetal-sno-agent-ipv4-static-connected-f7

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-arm64-nightly-baremetal-sno-agent-ipv4-static-connected-f7

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-arm64-nightly-baremetal-sno-agent-ipv4-static-connected-f7

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-arm64-nightly-baremetal-sno-agent-ipv4-static-connected-f7

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-arm64-nightly-baremetal-sno-agent-ipv4-static-connected-f7

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-arm64-nightly-baremetal-sno-agent-ipv4-static-connected-f7

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-arm64-nightly-baremetal-sno-agent-ipv4-static-connected-f7

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-arm64-nightly-baremetal-sno-agent-ipv4-static-connected-f7

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-arm64-nightly-baremetal-sno-agent-ipv4-static-connected-f7

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-arm64-nightly-baremetal-sno-agent-ipv4-static-connected-f7

**Pull request closed without merging**
