### PR TITLE
Update Distributed Tracing interop jobs and use golang 1.21 for build.

### PR DESCRIPTION
**Pull request by IshwarKanse**
* Update the interop and stage jobs for RHOSDT 3.0.
* Use golang-1.21 for build root. 
* Build the OpenTelemetry Operator OpampBridge image.

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-grafana-tempo-operator-main-tempo-e2e-tests periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.15-lp-interop-tempo-interop-aws

**Comment by IshwarKanse** [comment]
Tempo tests passed:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/46507/rehearse-46507-pull-ci-openshift-grafana-tempo-operator-main-tempo-e2e-tests/1732639979915448320
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/46507/rehearse-46507-periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.15-lp-interop-tempo-interop-aws/1732639979969974272

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.15-lp-interop-opentelemetry-interop-aws

**Comment by IshwarKanse** [comment]
periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.15-lp-interop-opentelemetry-interop-aws

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.15-lp-interop-opentelemetry-interop-aws

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.15-lp-interop-opentelemetry-interop-aws

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.15-lp-interop-opentelemetry-interop-aws

**Comment by IshwarKanse** [comment]
OpenTelemetry interop tests passed.
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/46507/rehearse-46507-periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.15-lp-interop-opentelemetry-interop-aws/1732787651766915072

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.15-lp-interop-jaeger-interop-aws pull-ci-jaegertracing-jaeger-operator-main-jaeger-e2e-tests

**Review by pavolloffay — APPROVED** [review]

**Pull request merged**
