### PR TITLE
e2e: use lease client

### PR DESCRIPTION
**Pull request by bbguimaraes**

### CODE REVIEW

**Comment by bbguimaraes** [comment]
The tests used an old version of `ci-operator` because the post-submit build job failed:

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/branch-ci-openshift-ci-tools-master-images/231

**Comment by bbguimaraes** [comment]
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/5802/rehearse-5802-pull-ci-openshift-origin-master-e2e-azure/2 fixed in https://github.com/openshift/ci-tools/pull/255.

**Comment by stevekuznetsov** [comment]
@bbguimaraes what's left here?

**Comment by bbguimaraes** [comment]
All rehearsals behaved as expected (even those that had flakes =).

@openshift/openshift-team-developer-productivity-test-platform: anyone feeling courageous?

**Pull request merged**
