### PR TITLE
Run kuttl tests in e2e job for mariadb-operator

### PR DESCRIPTION
**Pull request by cescgina**
Run the build-deploy-kuttl workflow instead of the build-deploy one

### CODE REVIEW

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-mariadb-operator-master-mariadb-operator-build-deploy-kuttl

**Comment by rlandy** [comment]
Checked kuttl tests are now running and passing per report: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/37275/rehearse-37275-pull-ci-openstack-k8s-operators-mariadb-operator-master-mariadb-operator-build-deploy-kuttl/1635644101393125376/artifacts/mariadb-operator-build-deploy-kuttl/openstack-k8s-operators-kuttl/artifacts/kuttl-test-mariadb.json

build-deploy is now not running by default (correct).

Full log is here: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/37275/rehearse-37275-pull-ci-openstack-k8s-operators-mariadb-operator-master-mariadb-operator-build-deploy-kuttl/1635644101393125376/artifacts/mariadb-operator-build-deploy-kuttl/openstack-k8s-operators-kuttl/build-log.txt

=== CONT  kuttl
    harness.go:405: run tests finished
    harness.go:513: cleaning up
    harness.go:570: removing temp folder: ""
--- PASS: kuttl (104.24s)
    --- PASS: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/mariadb_deploy (94.70s)

**Pull request merged**
