### PR TITLE
HyperShift-MCE: Update the decompress method

### PR DESCRIPTION
**Pull request by LiangquanLi930**

### CODE REVIEW

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-mce-aws-ovn

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.12-periodics-4.12-conformance-mce-aws-ovn

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.14-conformance-mce-aws-ovn

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-mce-kubevirt

**Comment by davidvossel** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-mce-kubevirt

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-mce-kubevirt

**Comment by davidvossel** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-mce-kubevirt

**Review by dtthuynh — APPROVED** [review]

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.12-periodics-4.12-conformance-mce-kubevirt

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-mce-kubevirt

**Pull request merged**
