### PR TITLE
OCPQE-24816 update e2e tags in cpou jobs

### PR DESCRIPTION
**Pull request by jiajliu**
1. add missing tags to drop TELCO cases to resolve the issue in https://issues.redhat.com/browse/OCPQE-24816
2. drop useless e2e tags to keep consistent based on https://github.com/openshift/release/pull/55502#discussion_r1717811321

### CODE REVIEW

**Comment by jiajliu** [comment]
cc @jianlinliu @liangxia PTAL, thanks.

**Comment by jianlinliu** [comment]
cc @liangxia to review.

**Pull request merged**
