### PR TITLE
Remove verify-deps test from ocm-o

### PR DESCRIPTION
**Pull request by adambkaplan**
This test suite doesn't exist for cluster-openshift-controller-manager-operator

/assign @tnozicka

### CODE REVIEW

**Comment by adambkaplan** [comment]
Added in https://github.com/openshift/release/pull/4121, but how did this merge? Rehearsal for ocm-o should have failed.

**Comment by tnozicka** [comment]
Sorry, this is my bad, I really though all the operator we started were using build machinery from library-go, looking at the Makefile there it isn't true for ocm operator. Rehearse job was green so we merged. Looks like it may ignore optional jobs...
Maybe we should just update the Makefile there, let me send a PR there and see how it looks to you.

**Comment by tnozicka** [comment]
/hold
if we go with https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/106 this code should stay

**Comment by adambkaplan** [comment]
/close

Approved https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/106

**Pull request closed without merging**
