### PR TITLE
ipi/deprovision/deprovision: Remove stuttering subdirectory

### PR DESCRIPTION
**Pull request by wking**
The directory was from 23ca2ce536 (#5962).  But chains and refs are distinct types; we don't need to use separate subdirectories to further distinguish their names.

### CODE REVIEW

**Comment by wking** [comment]
Pushed a6db4077a to do the same for `ipi/install/install`.

**Comment by stevekuznetsov** [comment]
```
 .//ci-operator/step-registry/ipi/install/vsphere/ipi-install-vsphere-commands.sh: .//ci-operator/step-registry/ipi/install/vsphere/ipi-install-vsphere-commands.sh: openBinaryFile: does not exist (No such file or directory) 
```

We may need to update that ShellCheck job

**Comment by wking** [comment]
/hold

While I work through [rehearsal][1]:

```
time="2020-03-25T21:45:15Z" level=error msg="could not load step registry" error="Failed to load registry file ci-operator/step-registry/ipi/install/ipi-install-install-ref.yaml: open ci-operator/step-registry/ipi/install/ipi-install-commands.sh: no such file or directory" pr=7931
ERROR: pj-rehearse: misconfiguration
```

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/7931/pull-ci-openshift-release-master-pj-rehearse/17095

**Comment by wking** [comment]
Should be fixed with a6db4077a -> 12e2732bc.

/hold cancel

**Comment by stevekuznetsov** [comment]
shellcheck still no likey

**Comment by wking** [comment]
Ah, fixed the symlink (and rebased on master, no conflicts) with 12e2732bc -> 04658519e.

**Comment by wking** [comment]
[pj-rehearse][1] says:

```
time="2020-03-25T22:25:28Z" level=error msg="could not get step registry differences" error="could not find registry component in registry graph: ipi-install-install" pr=7931
ERROR: pj-rehearse: misconfiguration
```

But:

```console
$ git --no-pager log -1 --oneline
04658519e (HEAD -> drop-deprovision-stutter, wking/drop-deprovision-stutter) ipi/install/install: Remove stuttering subdirectory
$ git --no-pager grep install-install 04658519e --
...no hits...
```

Maybe stale branch?

/retest

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/7931/pull-ci-openshift-release-master-pj-rehearse/17099

**Comment by wking** [comment]
Fixed the `ipi-install-install-ref.yaml` filename with 04658519e -> 2c8bb980b

**Comment by wking** [comment]
@AlexNPavel on using the same name for both a `ref` and `chain`:

> Essentially, the issue with this is that if a ref is updated and a chain has the same name, the rehearse tool will think that the chain changed, not the ref. The rehearse tool will then rehearse any jobs that have that chain anywhere in their dependency graph. The only time this could cause an issue is if a job uses the ref but not the chain, and the ref changes break that job but not jobs that use the chain.

Checking:

```console
$ git --no-pager grep 'ref: ipi-install$' origin/pr/7931   
origin/pr/7931:ipi/install/ipi-install-chain.yaml:  - ref: ipi-install
```

So at least in this particular instance, we're not impacted by that limitation.  Might still want to reject this PR (and unwind existing master locations where a chain and ref share a name?) to avoid setting a potentially confusing precedent?

**Comment by wking** [comment]
Rebased around #9739 with 1c6a933cc7 -> 0f7172a70f.

**Comment by wking** [comment]
@stevekuznetsov, tons of rehearsals, but lots are green, so my guess is the failures are unreliable in master.  Should be a quick review 😇

**Pull request closed without merging**
