### PR TITLE
Update pre-commit contianer image

### PR DESCRIPTION
**Pull request by Sandeepyadav93**
Build pre-commit image from SRC, we are using same pattern in all operators.

### CODE REVIEW

**Review by gibizer — APPROVED** [review]
looks good

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-placement-operator-master-precommit-check

**Comment by Sandeepyadav93** [comment]
/pj-rehearse ack

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/37872/rehearse-37872-pull-ci-openstack-k8s-operators-placement-operator-master-precommit-check/1641385525828915200/build-log.txt

**Pull request merged**
