### PR TITLE
MULTIARCH-4597: Add dnsConfig to heterogeneous UPI workflow for s390x.

### PR DESCRIPTION
**Pull request by jaypoulz**

### CODE REVIEW

**Comment by jaypoulz** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-e2e-ovn-remote-libvirt-s390x-heterogeneous

**Comment by jaypoulz** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-e2e-ovn-remote-libvirt-s390x-heterogeneous

**Review by werled — APPROVED** [review]
lgtm

**Comment by werled** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.15-ocp-e2e-ovn-remote-libvirt-s390x-heterogeneous

**Pull request merged**
