### PR TITLE
Remove NFD and SRO from cherry-pick-approved

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Currently NFD and SRO (non Core operators) are in lists that force this
operators source code to enforce `cherry-pick-approved` and
`group-lead-approved` labels. as discussed with the team we only want
Bugzilla related labels for our development workflow

Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by petr-muller** [comment]
1. Who approves the exemption from OCP development process? Usually we require pillar lead approvals for exemptions.
2. The PR is probably incorrect. You removed your repos from queries that cover current (4.8) and past (<4.7) release branhces, but that only means Tide will not merge PRs on the braches, not that it will relax criteria on them.

**Comment by ArangoGutierrez** [comment]
>     1. Who approves the exemption from OCP development process? Usually we require pillar lead approvals for exemptions.
> 
>     2. The PR is probably incorrect. You removed your repos from queries that cover current (4.8) and past (<4.7) release branhces, but that only means Tide will not merge PRs on the braches, not that it will relax criteria on them.

Hi @petr-muller , the pillar lead for NFD and SRO is @mrunalp 
both NFD and SRO are not CORE operators, they are addons, we want to remove the cherry-pick-approved and
group-lead-approved labels from our workflow, leaving only `bugzilla-valid-bug` as a blocker for backports and master during code freeze 

would you point me to which lines I should "not" remove on this patch.

thanks!

**Comment by petr-muller** [comment]
> would you point me to which lines I should "not" remove on this patch.

It's not about removing or leaving lines, you'll need to understand the configuration and describe your merge criteria that need to hold for your repos/braches. Every item in the `queries` list is a GH PR query that means "PRs satisfying the query are allowed to merge". You removed your repos from several queries, you'll need to write new queries.

**Comment by petr-muller** [comment]
For assistance please ping `@dptp-helpdesk`

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
