### PR TITLE
OCM-6386 RHCS rosa sts jobs use NonClassicCluster label

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/OCM-6386

### CODE REVIEW

**Comment by radtriste** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-critical-high-f3

**Comment by radtriste** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-private-critical-high-f3

**Comment by radtriste** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-critical-high-f3 periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-private-critical-high-f3

**Review by gdbranco — APPROVED** [review]

**Comment by radtriste** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-optional-presubmit

**Comment by radtriste** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-private-optional-presubmit

**Comment by radtriste** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-private-optional-presubmit

**Comment by radtriste** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-optional-presubmit pull-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-day1-negative-optional-presubmit

**Comment by radtriste** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-optional-presubmit pull-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-day1-negative-optional-presubmit pull-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-critical-high-presubmit

**Comment by radtriste** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-day1-negative-optional-presubmit

**Comment by radtriste** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-day1-negative-optional-presubmit

**Comment by radtriste** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-optional-presubmit

**Pull request merged**
