### PR TITLE
Validate Bugzilla bug states before linking

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @eparis 
depends on #4193

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
(config test will pass once the prereq PR merges)

**Comment by stevekuznetsov** [comment]
very interesting
/retest

**Comment by stevekuznetsov** [comment]
Needs https://github.com/kubernetes/test-infra/pull/13156

**Comment by eparis** [comment]
/lgtm
obviously after 13156 merges.

**Comment by stevekuznetsov** [comment]
Will retest after https://github.com/openshift/release/pull/4199 lands

**Pull request merged**
