### PR TITLE
fix: OADP must-gather mirror job and multi-arch

### PR DESCRIPTION
**Pull request by mateusoliveira43**
Create images job for OADP must-gather and mirror it to quay

Related to https://github.com/openshift/oadp-operator/issues/1487

### CODE REVIEW

**Comment by mateusoliveira43** [comment]
/hold
this will break OADP CI

**Comment by kaovilai** [comment]
/retitle fix: OADP must-gather mirror job and multi-arch

:D

**Comment by mateusoliveira43** [comment]
must-gather Dockerfile needs update to work with ARM

**Pull request closed without merging**
