### PR TITLE
Added a periodic job to test secure boot on gcp to 4.13 ci

### PR DESCRIPTION
**Pull request by eranco74**

### CODE REVIEW

**Comment by eranco74** [comment]
Looks good
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/35706/rehearse-35706-periodic-ci-openshift-release-master-ci-4.13-e2e-gcp-secureboot/1618327128200187904/artifacts/e2e-gcp-secureboot/ipi-install-install/artifacts/install-config.yaml

**Review by vrutkovs — APPROVED** [review]
/approve
/rehearsals ack

**Pull request merged**
