### PR TITLE
HAC 83: Initialize configuration for hac-dev repo

### PR DESCRIPTION
**Pull request by florkbr**
Repo https://github.com/openshift/hac-dev

See https://issues.redhat.com/browse/HAC-83

### CODE REVIEW

**Comment by andrewballantyne** [comment]
@florkbr seems `jest` is not available... Although it is in their dependency list. Thoughts?

```
> hac-dev@0.0.1 test /go/src/github.com/openshift/hac-dev
> jest
sh: 1: jest: not found
```

**Comment by andrewballantyne** [comment]
Discussed with Bryan off-line and it appears [OpenShift Console does it](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/console/openshift-console-master.yaml#L48) via the '[build-frontend.sh](https://github.com/openshift/console/blob/master/build-frontend.sh)', we'll likely need something here too.

**Comment by florkbr** [comment]
I have updated this PR to run `build.sh` and `test.sh` in the root of the hac-dev repo. Those will need to be added and we should be able to retrigger this PR to get it passing.

**Review by jerolimov — APPROVED** [review]
For me, from hac-dev team, this looks fine.

/lgtm

**Pull request merged**
