### PR TITLE
Remove docs-no-retest plugin

### PR DESCRIPTION
**Pull request by 0xmichalis**
/assign stevekuznetsov

### CODE REVIEW

**Comment by wking** [comment]
Should this have removed [the associated label][1] too?

[1]: https://github.com/openshift/release/blob/ea04d2dbc876ba6afd03da7ff25790646332fda6/cluster/ci/config/prow/labels.yaml#L168-L173

**Comment by kargakis** [comment]
Yes, we should remove it.

**Comment by wking** [comment]
> Yes, we should remove it.

I'll file a PR.

**Comment by kargakis** [comment]
Thanks

**Pull request merged**
