### PR TITLE
add periodic test for backstage

### PR DESCRIPTION
**Pull request by josephca**
Move PR test to periodic test

### CODE REVIEW

**Comment by josephca** [comment]
@subhashkhileri please review. The rehearse test failure will be fixed by https://github.com/janus-idp/showcase-e2e/pull/39.

**Review by subhashkhileri — APPROVED** [review]

**Comment by josephca** [comment]
/pj-rehearse periodic-ci-janus-idp-showcase-e2e-main-v4.13-showcase-e2e-periodic

**Pull request merged**
