### PR TITLE
cert rotation suspend: test workaround for stuck CNI

### PR DESCRIPTION
**Pull request by vrutkovs**

### CODE REVIEW

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-sno-cert-rotation-suspend-30d periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-ha-cert-rotation-suspend-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-ha-cert-rotation-suspend-60d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-sno-cert-rotation-suspend-30d periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-ha-cert-rotation-suspend-30d periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-sno-cert-rotation-suspend-90d periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-ha-cert-rotation-suspend-90d periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-sno-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-sno-cert-rotation-shutdown-90d

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Pull request merged**
