### PR TITLE
Fix build_root for openstack sushy in older releases

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Comment by elfosardo** [comment]
/hold
pending openstack-sushy changes
https://github.com/openshift/openstack-sushy/pull/48
https://github.com/openshift/openstack-sushy/pull/49
https://github.com/openshift/openstack-sushy/pull/50
https://github.com/openshift/openstack-sushy/pull/51

**Comment by elfosardo** [comment]
/pj-rehearse ack
failures are expected, unfortunately
we'll fix in the sushy repo

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-sushy-release-4.12-pep

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-sushy-release-4.12-pep8

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-sushy-release-4.12-pep8

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-sushy-release-4.12-pep8

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-sushy-release-4.13-pep8

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-sushy-release-4.12-pep8

**Review by iurygregory — APPROVED** [review]
/lgtm

**Pull request merged**
