### PR TITLE
switch from check to verify,cmd,unit

### PR DESCRIPTION
**Pull request by deads2k**
Adds verify to the list of automatically run jobs

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@deads2k do you want this PR to be a catch-all for all three new jobs you are going to add, keep it open while you test them?

**Comment by deads2k** [comment]
> @deads2k do you want this PR to be a catch-all for all three new jobs you are going to add, keep it open while you test them?

No.  I'd like to see the "small" one work end to end first, then I'll get the other two.

**Comment by stevekuznetsov** [comment]
@deads2k why do we need to add this to the default trigger set for all PRs to see it work? Can just run the job manually -- I promise updating the Prow config will enable it :)

**Comment by deads2k** [comment]
> @deads2k why do we need to add this to the default trigger set for all PRs to see it work? Can just run the job manually -- I promise updating the Prow config will enable it :)

I meant I wanted to see one flow work all the way through for creating a new job before I go to the effort of making two more.  No objection to kicking jenkins or whatever (I don't know what to do ), to see the backing job work before turning this on.

**Comment by deads2k** [comment]
@stevekuznetsov updated ptal.

**Comment by stevekuznetsov** [comment]
LGTM

**Comment by deads2k** [comment]
check - 25 minutes
cmd - 54 minutes
unit - 48 minutes

**Comment by stevekuznetsov** [comment]
Previous job was ~1h45m

I would worry that test-cmd would run over the hour limit and we would be doubling the cost here. That's worst-case. As is, we only increase the cost by 50%

**Comment by deads2k** [comment]
> I would worry that test-cmd would run over the hour limit and we would be doubling the cost here. That's worst-case. As is, we only increase the cost by 50%

Halving the latency for a developer could do as much as double their productivity for particular pulls.  Also, test-cmd flakes more often than unit, so we could be reducing the /retest cost.

**Pull request merged**
