### PR TITLE
openstack-tests: Add an e2e presubmit to master

### PR DESCRIPTION
**Pull request by pierreprinetti**

### CODE REVIEW

**Comment by pierreprinetti** [comment]
This depends on https://github.com/openshift/release/pull/23623

**Review by mandre — COMMENTED** [review]
/approve
/lgtm

/hold for the tests to pass

**Comment by pierreprinetti** [comment]
/hold cancel

PASS! https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/23838/rehearse-23838-pull-ci-openshift-openstack-test-main-test/1466322401133334528/artifacts/test/openstack-test-openstack/build-log.txt

:partying_face:

**Pull request merged**
