### PR TITLE
Add test frequency to job names

### PR DESCRIPTION
**Pull request by liangxia**
Based on latest name rules in [1], add test frequency to job names

Test frequency update will be in follow up PRs

[1] https://github.com/openshift/release/blob/master/ci-operator/config/openshift/openshift-tests-private/README.md

### CODE REVIEW

**Comment by jianlinliu** [comment]
I have a WIP PR to remove duplicates ci coverage to lower our workload on all cloudproviders, so that we can survive during the weekend. But my PR has many conflicts with this ones. Do you mind to wait for a while to wait for my PR get merged, then update the job names?

**Comment by liangxia** [comment]
/hold
waiting for https://github.com/openshift/release/pull/34096 to merge, then reapply the changes.

**Pull request merged**
