### PR TITLE
Hive

### PR DESCRIPTION
**Pull request by huangmingxia**
Delete the long-duration-part3-3 job of 4.8 and 4.9, including aws, azure, gcp.
[OCPQE-13755](https://issues.redhat.com/browse/OCPQE-13755)

### CODE REVIEW

**Comment by huangmingxia** [comment]
@jianping-shu @jianlinliu @liangxia  please help review, thanks.

**Comment by jianping-shu** [comment]
These jobs for Hive were removed because there's no Hive test case in 4.8/4.9 branch of openshift-tests-private repo

**Pull request merged**
