### PR TITLE
Update(ci-operator): Red Hat Integration - Service Registry version 2.4

### PR DESCRIPTION
**Pull request by rkubis**

### CODE REVIEW

**Comment by rkubis** [comment]
/pj-rehearse periodic-ci-Apicurio-apicurio-registry-system-tests-main-service-registry-ocp4.14-lp-interop-service-registry-2-4

**Comment by Sau1506mya** [comment]
@rkubis we need an approval from someone in this OWNERS file to allow this to merge
https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/release/OWNERS 
This looks good to me and I've added the /lgtm label

**Review by vrutkovs — APPROVED** [review]
/approve

**Pull request merged**
