### PR TITLE
MSI: add RHOAM to observability flow

### PR DESCRIPTION
**Pull request by rnetser**

### CODE REVIEW

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Review by myakove — APPROVED** [review]

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.14-stage-multi-cluster-observability-4-14-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.14-stage-multi-cluster-observability-4-14-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.14-stage-multi-cluster-observability-4-14-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.14-stage-multi-cluster-observability-4-14-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.14-stage-multi-cluster-observability-4-14-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.14-stage-multi-cluster-observability-4-14-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.14-stage-multi-cluster-observability-4-14-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.14-stage-multi-cluster-observability-4-14-rosa-acm-gcp-mngd-rosa-mngd

**Review by myakove — APPROVED** [review]

**Review by calebevans — APPROVED** [review]
/approve

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.14-lp-interop-mtc-interop-aws

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.14-stage-multi-cluster-observability-4-14-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.14-lp-interop-mtc-interop-aws

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.14-stage-multi-cluster-observability-4-14-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.14-lp-interop-mtc-interop-aws

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.14-lp-interop-mtc-interop-aws

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.14-lp-interop-mtc-interop-aws

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.14-lp-interop-mtc-interop-aws

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.15-lp-interop-mtc-interop-aws

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.15-lp-interop-mtc-interop-aws

**Review by calebevans — APPROVED** [review]
/lgtm

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-rhoai-addon-interop-v4.15-GA-smoke-rosa-rhods-addon-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-rhoam-v4.14-production-co-exist-rosa-rhoai-rhoam

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-cluster-install-uninstall-cluster-install-uninstall-gcp-osd-4-14-stable

**Pull request merged**
