### PR TITLE
Perfscale email

### PR DESCRIPTION
**Pull request by paigerube14**
Want to send results to wider perfscale qe email alias

### CODE REVIEW

**Comment by svetsa-rh** [comment]
@paigerube14 Change looks good. 
Is there a sanity test either in prow or jenkins to confirm email address is working and everyone got notification? I didn't find any emails.

**Comment by paigerube14** [comment]
> @paigerube14 Change looks good. Is there a sanity test either in prow or jenkins to confirm email address is working and everyone got notification? I didn't find any emails.

No, the only way this works in jenkins is when there's no user (the timer/cron job deploys it)

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-gcp-4.13-ocp-qe-perfscale-router-perf-gcp

**Comment by paigerube14** [comment]
@svetsa-rh I received an email from the test. Lmk if you did as well

**Comment by qiliRedHat** [comment]
Thanks! I got the email and can open the google spread sheet.

**Pull request merged**
