### PR TITLE
hypershift-azure

### PR DESCRIPTION
**Pull request by jechen0648**

### CODE REVIEW

**Comment by fxierh** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-azure-aks-hypershift-byo-vnet-fips-mgmt-f14

**Comment by zhouying7780** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-azure-aks-hypershift-byo-vnet-fips-mgmt-f14

**Comment by jechen0648** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-azure-aks-hypershift-byo-vnet-fips-mgmt-f14

**Comment by jechen0648** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-azure-aks-hypershift-byo-vnet-fips-mgmt-f14

**Comment by sunzhaohua2** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-azure-aks-hypershift-byo-vnet-fips-mgmt-f14

**Comment by jechen0648** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-azure-aks-hypershift-byo-vnet-fips-mgmt-f14

**Comment by sunzhaohua2** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-azure-aks-hypershift-byo-vnet-fips-mgmt-f14

**Pull request closed without merging**
