### PR TITLE
OADP (ocp 4.12): add e2e tests in master and 1.2 branch

### PR DESCRIPTION
**Pull request by hhpatel14**

### CODE REVIEW

**Review by kaovilai — APPROVED** [review]

**Comment by hhpatel14** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-master-4.12-operator-e2e-azure

**Comment by hhpatel14** [comment]
/pj-rehearse periodic-ci-openshift-oadp-operator-master-4.12-operator-e2e-gcp-periodic-slack

**Comment by kaovilai** [comment]
@hhpatel14 run `make jobs`

**Comment by hhpatel14** [comment]
/pj-rehearse periodic-ci-openshift-oadp-operator-master-4.12-operator-e2e-gcp-periodic-slack

**Comment by kaovilai** [comment]
@hhpatel14 stop retesting aws.

> InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/39107/rehearse-39107-periodic-ci-openshift-oadp-operator-master-4.12-operator-e2e-aws-periodic-slack/1686558831213023232#1:build-log.txt%3A237

**Comment by hhpatel14** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-oadp-1.2-4.12-operator-e2e-gcp
/pj-rehearse pull-ci-openshift-oadp-operator-oadp-1.2-4.12-images

**Pull request closed without merging**
