### PR TITLE
Adding aro to chaos tests

### PR DESCRIPTION
**Pull request by paigerube14**
Want to add aro for both 4.13 and 4.14 to chaos testing pipeline

### CODE REVIEW

**Review by chaitanyaenr — COMMENTED** [review]
@paigerube14 LGTM. We need to run $ make ci-operator-config to fix the CI.

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-aro-4.14-nightly-krkn-hub-tests-aro-414 periodic-ci-redhat-chaos-krkn-hub-main-aro-4.13-nightly-krkn-hub-tests-aro-413

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-aro-4.14-nightly-krkn-hub-tests-aro-414 periodic-ci-redhat-chaos-krkn-hub-main-aro-4.13-nightly-krkn-hub-tests-aro-413

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-aro-4.14-nightly-krkn-hub-tests-aro-414 periodic-ci-redhat-chaos-krkn-hub-main-aro-4.13-nightly-krkn-hub-tests-aro-413

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-aro-4.13-nightly-krkn-hub-tests-aro-413

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-aro-4.13-nightly-krkn-hub-tests-aro-413

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-aro-4.13-nightly-krkn-hub-tests-aro-413

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-aro-4.13-nightly-krkn-hub-tests-aro-413

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-aro-4.13-nightly-krkn-hub-tests-aro-413

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-aro-4.13-nightly-krkn-hub-tests-aro-413 periodic-ci-redhat-chaos-krkn-hub-main-aro-4.14-nightly-krkn-hub-tests-aro-414

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-aro-4.13-nightly-krkn-hub-tests-aro-413 periodic-ci-redhat-chaos-krkn-hub-main-aro-4.14-nightly-krkn-hub-tests-aro-414

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-aro-4.13-nightly-krkn-hub-tests-aro-413 periodic-ci-redhat-chaos-krkn-hub-main-aro-4.14-nightly-krkn-hub-tests-aro-414

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-aro-4.13-nightly-krkn-hub-tests-aro-413

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-aro-4.13-nightly-krkn-hub-tests-aro-413 periodic-ci-redhat-chaos-krkn-hub-main-aro-4.14-nightly-krkn-hub-tests-aro-414

**Comment by paigerube14** [comment]
Issue found because of this testing fixed with this pr: https://github.com/redhat-chaos/krkn-lib-kubernetes/pull/6

Also opened up issue upstream:https://github.com/arcalot/arcaflow-lib-kubernetes-python/issues/6

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-aro-4.13-nightly-krkn-hub-tests-aro-413

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-aro-4.13-nightly-krkn-hub-tests-aro-413

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-aro-4.14-nightly-krkn-hub-tests-aro-414

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-aro-4.14-nightly-krkn-hub-tests-aro-414

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-aro-4.14-nightly-krkn-hub-tests-aro-414

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-aro-4.14-nightly-krkn-hub-tests-aro-414

**Pull request merged**
