### PR TITLE
Add NW and MG collection to hypershift workflow

### PR DESCRIPTION
**Pull request by jluhrsen**
Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>

### CODE REVIEW

**Review by alvaroaleman — COMMENTED** [review]
I don't think these will work, as they use must-gather under the hood which doesn't work in Hypershift.

/hold

**Comment by jluhrsen** [comment]
> I don't think these will work, as they use must-gather under the hood which doesn't work in Hypershift.
> 
> /hold

ok. was just testing this for now. I was digging through a job's artifacts and could not find a must-gather tar file. do you know where that would be?

**Comment by alvaroaleman** [comment]
@jluhrsen since must-gather doesn't work, its not being used :) What is used is the `hypershift dump` command, which closely resembles what must-gather does, see e.G. the `hypershift-dump.tar` file here: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/30931/rehearse-30931-pull-ci-openshift-hypershift-main-e2e-conformance/1553056843230613504/artifacts/e2e-conformance/dump/artifacts/

**Comment by jluhrsen** [comment]
> @jluhrsen since must-gather doesn't work, its not being used :) What is used is the `hypershift dump` command, which closely resembles what must-gather does, see e.G. the `hypershift-dump.tar` file here: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/30931/rehearse-30931-pull-ci-openshift-hypershift-main-e2e-conformance/1553056843230613504/artifacts/e2e-conformance/dump/artifacts/

got it. I thought by "under the hood" you meant that it would be there in some secret fun location to find. oh well. really I was just trying to get a MG so I could use that [static-kas](https://github.com/alvaroaleman/static-kas) tool to interact with the cluster after the fact. oh well. I'll close this one.

**Comment by alvaroaleman** [comment]
> oh well. really I was just trying to get a MG so I could use that static-kas tool to interact with the cluster after the fact. oh well. I'll close this one.

You can, just download and extract the `hypershift-dump.tar` and point static-kas at it, that is how I debug these tests :)

**Comment by jluhrsen** [comment]
> > oh well. really I was just trying to get a MG so I could use that static-kas tool to interact with the cluster after the fact. oh well. I'll close this one.
> 
> You can, just download and extract the `hypershift-dump.tar` and point static-kas at it, that is how I debug these tests :)

thanks for the help here. I got it to work (mostly). I was trying to do an 'oc describe network -A' but that was empty. could
be a hypershift thing though.

**Comment by alvaroaleman** [comment]
@jhutar that is because we don't dump the mgmt cluster network, but we do dump the hostedcluster network. If you extract the archive, there is a folder named `hostedcluster-$something`, if you then do `static-kas --base-dir ./hostedcluster-$something` you will see the hostedclusters network

**Pull request closed without merging**
