### PR TITLE
Serverless reuse knative eventing src image

### PR DESCRIPTION
**Pull request by mgencur**
Replaces https://github.com/openshift/release/pull/9525

### CODE REVIEW

**Comment by matzew** [comment]
/lgtm

@mgencur nit: on master, soon we are on 0.14.2   - should we add _this_ to the 1.7.x branch(es) as well ?

**Comment by mgencur** [comment]
@matzew I had to rebase.

Re: 0.13.0 vs. 0.14.2 - yes, we'll have to update this to 0.14.2 when the master branch is updated in serverless-operator repo, in order to pull the right version of tests again. But not now.
Re: 1.7.x branches, I'd rather do that only for master branch and use this approach for future releases 1.8 and newer. This work is still not finished even for master branch (need to source knative-eventing-operator and serving-operator repos) and there are too many PRs in flight.

**Comment by mgencur** [comment]
This PR is ready again.

**Pull request merged**
