### PR TITLE
chore: remove unused secret-related env vars

### PR DESCRIPTION
**Pull request by psturc**
https://issues.redhat.com/browse/KONFLUX-2678

### CODE REVIEW

**Comment by psturc** [comment]
/assign @flacatus @Dannyb48 @jkopriva 
please add `/lgtm` if it looks ok

/hold
I will test this once hive is ready

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests

**Comment by psturc** [comment]
Hi @elsony @johnmcollier @maysunfaisal @yangcao77 we had to change the konflux CI secret name that devfile jobs are using. Could you please approve this PR? Thanks

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests

**Review by johnmcollier — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
