### PR TITLE
Test skipping must-gather for Serverless

### PR DESCRIPTION
**Pull request by mgencur**
This enables the feature that skips gathering artifacts on succcessful test runs.

https://issues.redhat.com/browse/SRVCOM-945

### CODE REVIEW

**Comment by skonto** [comment]
The only case I have found this useful in the past was where I had to compare a successful run's log output with a failed one.

**Comment by mgencur** [comment]
@skonto If there's a need to compare successful and unsuccesful runs you can make your build fail by hand, just place `exit 1` in the right place in the script. Then of course you'll need to remove it and run once again to get CI green.
This should be a rare case, right? Otherwise some important tests are missing.

**Comment by mgencur** [comment]
Just to be clear. The test logs will always be there. This is about removing gathering additional information about the OpenShift cluster (not Knative components)

**Comment by skonto** [comment]
@mgencur yeah I agree you can do it manually depends on how often things fail and how useful is that info anyway ;)

**Comment by mgencur** [comment]
Upstream E2E failed with a usual flake: `TestRevisionTimeout`

**Pull request merged**
