### PR TITLE
Debug Only[Nutanix]

### PR DESCRIPTION
**Pull request by liqcui**
/hold

### CODE REVIEW

**Comment by liqcui** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-nutanix-4.17-nightly-x86-data-path-9nodes

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-nutanix-4.17-nightly-x86-node-density-heavy-24nodes

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-nutanix-4.16-nightly-x86-node-density-heavy-24nodes

**Comment by liqcui** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-nutanix-4.17-nightly-x86-data-path-9nodes

**Comment by SachinNinganure** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-nutanix-4.16-nightly-x86-data-path-9nodes

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-nutanix-4.16-nightly-x86-node-density-heavy-24nodes

**Pull request closed without merging**
