### PR TITLE
[ART-9247] Create release-fips config

### PR DESCRIPTION
**Pull request by ashwindasr**
Follows https://github.com/openshift/release/pull/50497

### CODE REVIEW

**Comment by ashwindasr** [comment]
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-openshift-release-fips

**Comment by ashwindasr** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-openshift-release-fips

**Comment by ashwindasr** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-openshift-release-fips

**Comment by ashwindasr** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-openshift-release-fips

**Comment by ashwindasr** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-openshift-release-fips

**Comment by ashwindasr** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-openshift-release-fips

**Comment by ashwindasr** [comment]
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

**Comment by ashwindasr** [comment]
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

**Comment by ashwindasr** [comment]
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

**Comment by ashwindasr** [comment]
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

**Comment by ashwindasr** [comment]
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

**Comment by bradmwilliams** [comment]
Just a heads up... you'll need to re-add the `cron` bit to your `4.16` job to make it a `periodic` and not a `presubmit`.

**Comment by ashwindasr** [comment]
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

**Comment by ashwindasr** [comment]
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

**Comment by ashwindasr** [comment]
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

**Comment by ashwindasr** [comment]
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

**Comment by ashwindasr** [comment]
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

**Comment by ashwindasr** [comment]
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

**Comment by ashwindasr** [comment]
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

**Comment by ashwindasr** [comment]
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

**Comment by ashwindasr** [comment]
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

**Comment by ashwindasr** [comment]
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

**Comment by ashwindasr** [comment]
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

**Comment by ashwindasr** [comment]
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

**Comment by ashwindasr** [comment]
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

**Comment by ashwindasr** [comment]
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

**Comment by ashwindasr** [comment]
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

**Comment by ashwindasr** [comment]
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

**Comment by ashwindasr** [comment]
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

**Comment by ashwindasr** [comment]
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

**Comment by ashwindasr** [comment]
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

**Comment by ashwindasr** [comment]
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

**Comment by ashwindasr** [comment]
/close

This PR is getting too polluted, will test a new one, as draft, and then open for review

**Pull request closed without merging**
