### PR TITLE
knative-serving and knative-build configs and job definitions

### PR DESCRIPTION
**Pull request by mgencur**
This PR replaces https://github.com/openshift/release/pull/2086 and adds all the remaining configs and job definitions for knative-build and knative-serving

### CODE REVIEW

**Comment by petr-muller** [comment]
LGTM overall, but `ci-operator --config ci-operator/config/openshift/knative-build/openshift-knative-build-master.yaml  --git-ref openshift/knative-build@master --target=[images]` does not succeed for me.

Also, you should add OWNERS files so that your team can lgtm/approve.

**Comment by mgencur** [comment]
@petr-muller thanks, there's now this PR which adds the missing images and should make the tests pass (https://github.com/openshift/knative-build/pull/1) It passed for me when testing against this branch (`--git-ref=mgencur/serving-1@openshift_ci`)

**Comment by petr-muller** [comment]
Prow should work with OWNERS_ALIASES. `openshift/release` [has the file](https://github.com/openshift/release/blob/master/OWNERS_ALIASES) and e.g. installer [uses it](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/installer/OWNERS)

**Comment by mgencur** [comment]
> Prow should work with OWNERS_ALIASES. `openshift/release` [has the file](https://github.com/openshift/release/blob/master/OWNERS_ALIASES) and e.g. installer [uses it](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/installer/OWNERS)

Thanks, I'll look into it.

**Pull request merged**
