### PR TITLE
Tempo zstream 4.16 and firewatch updates

### PR DESCRIPTION
**Pull request by smatula**

### CODE REVIEW

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.15-lp-interop-tempo-interop-ibmcloud periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.16-lp-interop-tempo-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.15-lp-interop-tempo-interop-ibmcloud periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.16-lp-interop-tempo-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.15-lp-interop-tempo-interop-aws periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.16-lp-interop-tempo-interop-aws

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.15-lp-interop-tempo-interop-ibmcloud periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.16-lp-interop-tempo-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.16-lp-interop-tempo-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.16-lp-interop-tempo-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.15-lp-interop-tempo-interop-ibmcloud periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.16-lp-interop-tempo-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.16-lp-interop-tempo-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.16-lp-interop-tempo-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse /pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.16-lp-interop-tempo-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.15-lp-interop-tempo-interop-ibmcloud

**Review by Simranpal — APPROVED** [review]
/lgtm

**Pull request merged**
