### PR TITLE
chore(RHTAP-1805): add aws-rhtap-performance cluster profile

### PR DESCRIPTION
**Pull request by pmacik**

### CODE REVIEW

**Comment by pmacik** [comment]
depends on https://github.com/openshift/ci-tools/pull/3699

**Comment by danilo-gemoli** [comment]
Can you polish a bit `core-services/ci-secret-bootstrap/_config.yaml` as there are a lot of spaces that clutter the diff?

**Comment by pmacik** [comment]
> Can you polish a bit `core-services/ci-secret-bootstrap/_config.yaml` as there are a lot of spaces that clutter the diff?

@danilo-gemoli Fixed

**Comment by pmacik** [comment]
Resolved conflicts, rebased...

**Pull request merged**
