### PR TITLE
Add metal-ipi serial ipv6/virtualmedia/dualstack release informing jobs

### PR DESCRIPTION
**Pull request by andfasano**
This PR adds missing serial (optional) jobs for the relevant metal-ipi configurations

### CODE REVIEW

**Comment by andfasano** [comment]
Hi @dgoodwin  could you please have a look at this patch? It adds some serial jobs as informer jobs

**Comment by stbenjam** [comment]
This would need `make release-controllers` to pass, and you probably want to add this to 4.11 not just 4.10?

**Comment by dgoodwin** [comment]
We're experimenting with (for every new informing job) getting (1) slack channel to notify when this job drops below some failure threshold (what would that threshold be for this job? what pass rate would you be alarmed if it went below?) and (2) a manager backstop to notify if the job is flatlined for roughly two weeks. Could we get that info for these new jobs? Goal is to avoid informing jobs nobody ever looks at.

**Comment by andfasano** [comment]
This task will be addressed in https://github.com/openshift/release/pull/27200

**Pull request closed without merging**
