### PR TITLE
Migrate encrypt job to devqe vSphere

### PR DESCRIPTION
**Pull request by sgaoshang**
Migrate encrypt job

Since encryption is disable on vsphere 2, we enable it on devqe and migrate related jobs to it.

### CODE REVIEW

**Comment by sgaoshang** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-vsphere-upi-encrypt-f28

**Comment by sgaoshang** [comment]
@jianlinliu pls help to review it, thanks. cc: @jinyunma @WenXinWei

**Comment by jianlinliu** [comment]
cc @liangxia to review

**Pull request merged**
