### PR TITLE
OCPQE-20704: [HyperShift QE] Azure CI e2e

### PR DESCRIPTION
**Pull request by LiangquanLi930**
Enable e2e tests(mgmt and guest) on azure
job link: https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/50169/rehearse-50169-periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-azure-ipi-ovn-hypershift-mgmt-f28/1775054341384704000

### CODE REVIEW

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-azure-ipi-ovn-hypershift-mgmt-f28

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-azure-ipi-ovn-hypershift-mgmt-f28

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-azure-ipi-ovn-hypershift-mgmt-f28

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-azure-ipi-ovn-hypershift-mgmt-f28

**Comment by LiangquanLi930** [comment]
@kuiwang02 @liangxia Could you help to review this PR? Thanks

**Comment by kuiwang02** [comment]
I am ok.

**Pull request merged**
