### PR TITLE
OCPQE-14018: regression test on hypershift-mce-kubevirt

### PR DESCRIPTION
**Pull request by LiangquanLi930**
[OCPQE-14018](https://issues.redhat.com/browse/OCPQE-14018)

### CODE REVIEW

**Comment by LiangquanLi930** [comment]
@kuiwang02 Could you help to review this PR? Thanks

**Comment by kuiwang02** [comment]
iamok from golang's view

**Comment by LiangquanLi930** [comment]
@liangxia, Could you help to review this PR? Thanks!

**Pull request merged**
