### PR TITLE
ci-operator/config/openshift/release: Drop cross-minor rollback jobs

### PR DESCRIPTION
**Pull request by wking**
The job flavor was originally added in 083763496f (#16260).  The jobs have subsequently been cloned forward to new minors as part of the branching process.  And as older jobs started failing, I'd been dropping them gradually like 856aab20df (#33005).  But rounding with @jluhrsen, the jobs no longer serve a useful role, and as 856aab20df points out, rollbacks between minor releases are not supported.  Drop the likely-to-fail and not-useful-even-when-it-passes jobs in their entirety, so they stop getting cloned forward during branching.

### CODE REVIEW

**Comment by stbenjam** [comment]
Some wires are getting crossed because someone just made these informers

https://github.com/openshift/release/pull/39488

**Comment by wking** [comment]
Ah, thanks for the pointer.  I think folks are conflating the various jobs with `rollback` in their name.  The ones #39488 should have focused on are the `upgrade-rollback-oldest-supported` jobs.

**Review by vrutkovs — APPROVED** [review]
/approve
/lgtm

**Comment by vrutkovs** [comment]
Seems it needs another `make update` though

**Review by vrutkovs — APPROVED** [review]
/lgtm

**Pull request merged**
