### PR TITLE
Upgrade from f28 -> f29

### PR DESCRIPTION
**Pull request by baude**
Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by baude** [comment]
@stevekuznetsov is there any way we can disable the validate test on the centos image until a 1.11 image is available?

**Comment by stevekuznetsov** [comment]
> disable the validate test on the centos image 

What does this mean?

**Comment by baude** [comment]
golang made a change between 1.10 and 1.11 where the results of gofmt are not the same.  so we need to move to only running the validate test on something that is 1.11.

so in `./ci-operator/config/containers/libpod/containers-libpod-master.yaml` , I dont want the 1.10 centos image to run:

```
- artifact_dir: /tmp/artifacts
  as: validate
  commands: ARTIFACT_DIR=/tmp/artifacts make validate
  container:
    from: test-bin
```

**Comment by stevekuznetsov** [comment]
Oh. The only way to do it is to update the validate job to run 1.11, then the only PR that can merge will be the one fixing the formatting, then once that merges the rest are unblocked

**Pull request merged**
