### PR TITLE
change e2e-gcp-op-layering to e2e-gcp-op-techpreview

### PR DESCRIPTION
**Pull request by cheesesashimi**
As we place more features behind FeatureGates, there will be a need to ensure that these features are actually activated and have e2e test coverage. This job is being renamed to indicate that it can be used to test features that are behind FeatureGates.

### CODE REVIEW

**Comment by cheesesashimi** [comment]
/pj-rehearse pull-ci-openshift-machine-config-operator-master-e2e-gcp-op-techpreview

**Comment by djoshy** [comment]
/pj-rehearse pull-ci-openshift-machine-config-operator-master-e2e-gcp-op-techpreview

**Comment by djoshy** [comment]
/pj-rehearse pull-ci-openshift-machine-config-operator-master-e2e-gcp-op-techpreview

**Comment by cheesesashimi** [comment]
/pj-rehearse pull-ci-openshift-machine-config-operator-master-e2e-gcp-op-techpreview

**Pull request merged**
