### PR TITLE
add kubevirt to label sync job

### PR DESCRIPTION
**Pull request by droslean**
/cc @petr-muller

### CODE REVIEW

**Comment by petr-muller** [comment]
/hold

I'm not convinced we're supposed to sync our (openshift) Prow labels to kubevirt org. It looks like that org (or at least it's namesake repo, https://github.com/kubevirt/kubevirt, is using its own Prow: https://prow.apps.ovirt.org.

We'll need to talk with @rmohr @rthallisey about this: Why is OpenShift Prow handling an upstream (kubevirt) repository? We discovered this by our tooling not being able to create a merge-blocking issue, which is what we do for all repos that build images that end up being promoted into `ocp` imagestreams. kubevirt/hyperconverged-cluster-operator [does](https://github.com/openshift/release/blob/master/ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-master.yaml#L25) this, which does not seem right - it looks like all other components have a fork in `openshift` org from where the images are built. @smarterclayton, does this sound right?

**Comment by rmohr** [comment]
> For now let's just add the repo. That seems appropriate.

That may or may not work. In general the hco-operator is part of another project. We want to detect openshift incompatibilities early, however these labels which we were missing on the repo was about letting us stop merging things, which can be problemtic, since the kubevirt related projects in general have other freeze cycles ...

Long story short, it is not clear to me how to handle the processes of the two orgs, without blocking anyone.

**Comment by petr-muller** [comment]
@rmohr @stevekuznetsov Adding the tide blocker label to the repo at least made out job to fully pass again: https://prow.svc.ci.openshift.org/?job=periodic-openshift-release-merge-blockers. So there's no immediate need to do anything. Long-term we'll probably need to reconsider how to handle corner cases like this. Personally I would white-list orgs in our "Promotes Official Images" check.

**Comment by petr-muller** [comment]
/close

We fixed this differently.

**Pull request closed without merging**
