### PR TITLE
NO-JIRA: HCO: use label to skip tests, in upgrade lanes

### PR DESCRIPTION
**Pull request by nunnatsa**

### CODE REVIEW

**Review by tiraboschi — APPROVED** [review]

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-prev-operator-sdk-aws pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-aws pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-azure pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-consecutive-operator-sdk-upgrades-azure

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-aws pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-azure pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-consecutive-operator-sdk-upgrades-azure

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-aws

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-azure pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-aws

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-azure pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-aws

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-azure

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-azure

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-aws

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-azure

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-azure

**Review by tiraboschi — APPROVED** [review]

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-azure pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-aws

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-azure pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-aws

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-azure pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-aws

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-aws

**Pull request merged**
