### PR TITLE
Rename ipi-conf-techpreview to ipi-conf-techpreview-do-not-use

### PR DESCRIPTION
**Pull request by JoelSpeed**
Follow up from #38872, I want to deter people from using this step in future jobs. I have renamed it and added some documentation to explain that it should no longer be used and that the env var should be used instead.

At some point we should prune 4.11 and older jobs for techpreview and then we can remove this completely.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
I don't think we need to rehearse this, it's purely a rename operation

**Review by wking — APPROVED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
/pj-rehearse ack

No need to rehearse when this is just a rename operation

**Pull request merged**
