### PR TITLE
CI updates for managed-velero-operator

### PR DESCRIPTION
**Pull request by cblecker**
The managed-velero-operator is not a part of the OCP release bundle, and was tagged/branched in error. This cleans up those configurations, as well as reverts the changes to unset GOFLAGS.

### CODE REVIEW

**Comment by cblecker** [comment]
This is pending https://github.com/openshift/managed-velero-operator/pull/27

**Comment by cblecker** [comment]
/hold cancel
/assign @tnozicka 

This should be good to go

**Comment by tnozicka** [comment]
the GOFLAGS change lgtm

I think the rest would deserve a comment. You are also removing branches and promotion to 4.4 ocp so if that's intentional it looks like it shouldn't have been there before. Someone with privs should probably delete the old images promoted to that namespace.

/unassign tnozicka
/assign @stevekuznetsov

**Pull request merged**
