### PR TITLE
ci-operator: Avoid marking the any of the images[*] as optional

### PR DESCRIPTION
**Pull request by timflannagan**
Update the openshift/operator-framework-olm prow configuration and avoid
marking any of the images listed in the images stanza as optional. This
was previously added as a way to get some CI feedback on whether the
images were able to be built successfully, but not blocking PRs from
merging due to failures.

That assumption is not true, and when specifying `optional: true` for
any images defined in that list of images, that image won't be built or
promoted externally.

Update the operator-framework[operator-lifecycle-manager,operator-registry]
master/4.8+ branch prow configurations and disable promotion to `ocp/4.8:...`
as it's problematic attempting to promote an image from multiple repositories.

See the following error that's returned when attempting to promote from both
repositories:

```
non-unique image publication found: 
ERROR: output tag ocp/4.9:operator-registry is promoted from more than one place: openshift/operator-framework-olm@release-4.9, operator-framework/operator-registry@release-4.9
ERROR: output tag ocp/4.8:operator-lifecycle-manager is promoted from more than one place: openshift/operator-framework-olm@master, operator-framework/operator-lifecycle-manager@master
ERROR: output tag ocp/4.8:operator-registry is promoted from more than one place: openshift/operator-framework-olm@master, operator-framework/operator-registry@master
ERROR: output tag ocp/4.9:operator-lifecycle-manager is promoted from more than one place: openshift/operator-framework-olm@release-4.9, operator-framework/operator-lifecycle-manager@release-4.9
```

We'll now promote from the downstream, openshift/operator-framework-olm
location.

### CODE REVIEW

**Comment by timflannagan** [comment]
Not sure why it keeps assigning people outside of this repository's OWNER file.

/uncc petr-muller

**Review by ankitathomas — APPROVED** [review]
/lgtm

**Comment by timflannagan** [comment]
I'm going to hold for now and let the e2e rehearsal tests play out, but this is fine to merge.

/hold

**Pull request merged**
