### PR TITLE
Delete yamls applied to api.ci

### PR DESCRIPTION
**Pull request by hongkailiu**
Follow up https://github.com/openshift/release/pull/17254#issuecomment-809512908

/cc @stevekuznetsov @petr-muller

### CODE REVIEW

**Comment by hongkailiu** [comment]
```console
$ git --no-pager show --name-only  
commit f74b52708afb2db70a9823d13a4e68cc33de52d0 (HEAD -> del_serv_apici, downstream/del_serv_apici)
Author: Hongkai Liu <hongkailiu@users.noreply.github.com>
Date:   Mon Mar 29 14:54:58 2021 -0400

    Delete yamls applied to api.ci

core-services/build-farm/OWNERS
core-services/build-farm/README.md
core-services/build-farm/admin_image-pusher_rbac.yaml
core-services/ci-chat-bot/OWNERS
core-services/ci-chat-bot/README.md
core-services/ci-chat-bot/ci-chat-bot.yaml
core-services/ci-operator-configresolver/OWNERS
core-services/ci-operator-configresolver/README.md
core-services/ci-operator-configresolver/ci-operator-configresolver.yaml
core-services/ci-operator-configresolver/redirect.yaml
core-services/ci-rpms/OWNERS
core-services/ci-rpms/README.md
core-services/ci-rpms/admin_01_ns.yaml
core-services/ci-rpms/artifacts-rpms.yaml
core-services/ci-search/OWNERS
core-services/ci-search/README.md
core-services/ci-search/deploy.yaml
core-services/cluster/OWNERS
core-services/cluster/README.md
core-services/cluster/admin_autoscaler.yaml
core-services/cluster/ca-cert_README.md
core-services/cluster/logging/admin_fluentd-configmap.yaml
core-services/cluster/logging/admin_fluentd-daemonset.yaml
core-services/iaas-e2e-config/OWNERS
core-services/iaas-e2e-config/README.md
core-services/iaas-e2e-config/e2e-targets.yaml
core-services/openshift-monitoring/OWNERS
core-services/openshift-monitoring/README.md
core-services/openshift-monitoring/alertmanager-main_secret_template.yaml
core-services/openshift-monitoring/cfg_prometheus-prow-rules_prometheusrule.yaml
core-services/openshift-monitoring/k8s_prometheus.yaml
core-services/openshift-monitoring/main_alertmanager.yaml
core-services/prevent-image-gc/OWNERS
core-services/prevent-image-gc/README.md
core-services/prevent-image-gc/daemonset.yaml
core-services/prow/03_deployment/PROW_RESOURCES.md
core-services/prow/03_deployment/adapter_imagestreams.yaml
core-services/prow/03_deployment/admin_config_updater_rbac.yaml
core-services/prow/03_deployment/admin_test-credentials.yaml
core-services/prow/03_deployment/ci-ns-ttl-controller.yaml
core-services/prow/03_deployment/deck-redirect.yaml
core-services/prow/03_deployment/deck.yaml
core-services/prow/03_deployment/gcsweb-redirect.yaml
core-services/prow/03_deployment/gcsweb.yaml
core-services/prow/03_deployment/hook.yaml
core-services/prow/03_deployment/pdb.yaml
core-services/prow/03_deployment/prow-priority-class.yaml
core-services/supplemental-ci-images/OWNERS
core-services/supplemental-ci-images/README.md
core-services/various_rbac/OWNERS
core-services/various_rbac/README.md
core-services/various_rbac/admin_ci-operator_roles.yaml
core-services/various_rbac/admin_user_roles.yaml
services/brew-registry-pullsecret/OWNERS
services/brew-registry-pullsecret/README.md
services/brew-registry-pullsecret/admin_rbac.yaml
services/cnv-qe/OWNERS
services/cnv-qe/README.md
services/cnv-qe/admin_rbac.yaml
services/edge/OWNERS
services/edge/README.md
services/edge/admin_rbac.yaml
services/grafunnah/OWNERS
services/grafunnah/README.md
services/grafunnah/admin_dev-cluster-role-binding.yaml
services/interop-qe/OWNERS
services/interop-qe/README.md
services/interop-qe/admin_rbac.yaml
services/ocs/OWNERS
services/ocs/README.md
services/ocs/admin_rbac.yaml
services/osd-images/OWNERS
services/osd-images/README.md
services/osd-images/admin_rbac.yaml
services/ppc64le-osuosl-ci/OWNERS
services/ppc64le-osuosl-ci/README.md
services/ppc64le-osuosl-ci/admin_rbac.yaml
services/redhat-integration/OWNERS
services/redhat-integration/README.md
services/redhat-integration/admin_group.yaml
services/redhat-integration/admin_project.yaml
services/redhat-integration/admin_rbac.yaml
services/squid-egress-proxy/Dockerfile
services/squid-egress-proxy/OWNERS
services/squid-egress-proxy/README.md
services/squid-egress-proxy/build.yaml
services/squid-egress-proxy/entrypoint.sh
services/squid-egress-proxy/squid.repo
```

**Review by petr-muller — APPROVED** [review]
I love a smell of burning YAML in the morning

**Comment by sdodson** [comment]
Where did these go?

**Pull request merged**
