### PR TITLE
OCPQE-13989: Invoke e2e test on hypershift-mce-kubevirt

### PR DESCRIPTION
**Pull request by LiangquanLi930**
[OCPQE-13989](https://issues.redhat.com/browse/OCPQE-13989)

### CODE REVIEW

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-ipi-ovn-kubevirt-hypershift-mce-guest-p3-f21

**Comment by LiangquanLi930** [comment]
@liangxia @kuiwang02  Could you help to review this PR? Thanks!

**Comment by kuiwang02** [comment]
iamok from golang's view

**Pull request merged**
