### PR TITLE
SPLAT-687: Skip "multiple PV pointing to the same storage" tests on vSphere

### PR DESCRIPTION
**Pull request by jsafrane**
vSphere CSI driver is broken:
- https://bugzilla.redhat.com/show_bug.cgi?id=2106736
- https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/1913

The test was added in 4.11, skip it in 4.11 and newer.

cc @openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
> error: suite "files" does not contain any tests

This needs https://github.com/openshift/origin/pull/27300 merged into 4.11.

**Comment by jsafrane** [comment]
I can see only volume expansion tests failed

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Pull request merged**
