### PR TITLE
Setup CI for serverless release 1.27

### PR DESCRIPTION
**Pull request by ReToCode**
* As in https://github.com/openshift/release/pull/33856
* Uses golang 1.18

### CODE REVIEW

**Comment by nak3** [comment]
/lgtm

Thank you!

**Comment by nak3** [comment]
/hold

for test and other reviewers if there is any comments.

**Comment by pierDipi** [comment]
@ReToCode how did you create them?

**Comment by pierDipi** [comment]
I would like to make sure that we're including https://github.com/openshift/release/pull/33891

**Comment by ReToCode** [comment]
I just copied the 1.26 files and updated them.

**Review by pierDipi — APPROVED** [review]
/unhold

**Comment by nak3** [comment]
/pj-rehearse pull-ci-openshift-knative-serverless-operator-release-1.27-4.8-operator-e2e-aws-ocp-48

**Pull request merged**
