### PR TITLE
Generate configurations for 4.2

### PR DESCRIPTION
**Pull request by stevekuznetsov**
/assign @smarterclayton

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Generated with:

```
config-brancher --config-dir ./ci-operator/config --current-release 4.1 --future-release 4.2 --confirm
ci-operator-prowgen --from-dir ./ci-operator/config --to-dir ./ci-operator/jobs
```

**Comment by wking** [comment]
/hold

No sense at banging away on this until we fix [owners][1]:

```
[ERROR] Run the following script to fetch OWNERS files from the component repositories:

[ERROR] $ ci-operator/populate-owners.sh

[ERROR] Please note that the script populates *all* ci-operator subdirectories, and it
[ERROR] takes a long time to execute (tens of minutes). If the target repository does not
[ERROR] contain an OWNERS file, it will need to be created manually.

[ERROR] The following component config directories do not have OWNERS files:

ci-operator/config/openshift/etcd-quorum-guard
ci-operator/jobs/openshift/etcd-quorum-guard
```

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_release/3567/pull-ci-openshift-release-master-owners/3038

**Comment by wking** [comment]
And possibly obsolete since openshift/machine-config-operator#677 ?

**Comment by stevekuznetsov** [comment]
Yeah let me regenerate this

**Pull request merged**
