### PR TITLE
Update AMQ Broker to support 4.18

### PR DESCRIPTION
**Pull request by madunn**
Expand the AMQ Broker scenario to support OCP 4.18 with and without FIPS.

### CODE REVIEW

**Review by tlbueno — APPROVED** [review]
The changes looks good to me.

**Comment by tlbueno** [comment]
looks like something is still missing to be reviewed here. @madunn could you verify that is pending here?

**Comment by dfrazzette** [comment]
Changes will be ported to [PR#56251](https://github.com/openshift/release/pull/56251). Closing.

**Pull request closed without merging**
