### PR TITLE
insert chain 'cucushift-installer-check' for gcp provision chains

### PR DESCRIPTION
**Pull request by jianli-wei**
- insert the cluster health chain `cucushift-installer-check` into gcp provision chains

### CODE REVIEW

**Comment by gpei** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-gcp-ipi-xpn-private-f28

**Comment by jianli-wei** [comment]
> /pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-gcp-ipi-xpn-private-f28

FYI _INFO[2023-09-11T04:54:20Z] Step phase pre succeeded after 47m14s._

**Pull request merged**
