### PR TITLE
OCPBUGS-42375: OpenStack: export new SR-IOV related images

### PR DESCRIPTION
**Pull request by mandre**
Export new images needed in 4.18.

Here is an [example of a failed job](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_installer/9067/pull-ci-openshift-installer-master-e2e-openstack-nfv-intel/1841539383837069312).

### CODE REVIEW

**Comment by mandre** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.18-e2e-openstack-nfv-intel

**Comment by MaysaMacedo** [comment]
/lgtm

let's wait for CI result before merging

**Comment by mandre** [comment]
It's not enough. The `hack/env.sh` file is broken in the source repo. I have [a fix here](https://github.com/openshift/sriov-network-operator/commit/f94fa644ddee573d246f656e49e8f232273f3bc0) but for some reason github doesn't allow me to submit a PR to https://github.com/k8snetworkplumbingwg/sriov-network-operator :confused:

**Comment by MiguelCarpio** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.18-e2e-openstack-nfv-intel

**Comment by mandre** [comment]
This needs downstream sriov-network-operator to include https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/780 first.
/hold

**Comment by mandre** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.18-e2e-openstack-nfv-intel

**Comment by mandre** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.18-e2e-openstack-nfv-intel

**Comment by mandre** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.18-e2e-openstack-nfv-intel

**Pull request merged**
