### PR TITLE
cnf-features-deploy: ran profile CI updates

### PR DESCRIPTION
**Pull request by Missxiaoguo**
Updates:
- Switch ran profile CI job from gcp to aws cluster
- Skip sro test as sro, nfd and multinetworkpolicy are not part of ran profile.
Jira: [CNF-2983](https://issues.redhat.com//browse/CNF-2983)

### CODE REVIEW

**Review by lack — APPROVED** [review]

**Comment by Missxiaoguo** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-master-e2e-gcp-ran-profile

**Comment by SchSeba** [comment]
/lgtm
/approve

@Missxiaoguo please be aware that the ran lane is still broken.

**Comment by SchSeba** [comment]
adding @vitus133

**Comment by Missxiaoguo** [comment]
> @Missxiaoguo please be aware that the ran lane is still broken.
Yes, worker-cnf MCP is degraded. It's likely because of the RAN profile itself which needs to be updated in the cnf-features-deploy repo. I am still doing more tests and look for the config CR that caused the issue.

**Comment by Missxiaoguo** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-master-e2e-aws-ran-profile

**Comment by Missxiaoguo** [comment]
The ran profile CI has broken for a long time. The issue is the worker node/s couldn't come up online after the ran profile is applied. Did a lot testings with the clusters built by cluster-bot which are the same environment created by prow CI. The conclusion is ran profile CI cannot consistently work on the GCP environment somehow. If the operators were applied before MCs, the nodes couldn't come up from reboot.  It's not related to the configuration CRs applied as part of ran profile. Switching to aws cluster solves the issue. 
/unhold

**Comment by yuvalk** [comment]
> The ran profile CI has broken for a long time. The issue is the worker node/s couldn't come up online after the ran profile is applied. Did a lot testings with the clusters built by cluster-bot which are the same environment created by prow CI. The conclusion is ran profile CI cannot consistently work on the GCP environment somehow. If the operators were applied before MCs, the nodes couldn't come up from reboot. It's not related to the configuration CRs applied as part of ran profile. Switching to aws cluster solves the issue. /unhold

do you know what are the differences between the machine types (gcp vs aws)?

**Comment by Missxiaoguo** [comment]
> do you know what are the differences between the machine types (gcp vs aws)?

@yuvalk I am not aware of the differences. As far as I know, same memory(16G) and vcpus(4), also OVN kubernetes. I have no idea why gcp didn't work :(. Any other things I can check?

**Comment by Missxiaoguo** [comment]
> I think it's interesting that GCP fails while AWS succeeds, but maybe it's better for us to just move to AWS for now and write up a bug for the GCP people with a demonstration of what breaks?

Agree, I will file a bug for this

**Comment by yuvalk** [comment]
> > do you know what are the differences between the machine types (gcp vs aws)?
> 
> @yuvalk I am not aware of the differences. As far as I know, same memory(16G) and vcpus(4), also OVN kubernetes. I have no idea why gcp didn't work :(. Any other things I can check?

`lscpu` on both would be interesting (can try and dig that info from the bring-up code, to see what machine types are they using in each)

**Comment by yuvalk** [comment]
> > > do you know what are the differences between the machine types (gcp vs aws)?
> > 
> > 
> > @yuvalk I am not aware of the differences. As far as I know, same memory(16G) and vcpus(4), also OVN kubernetes. I have no idea why gcp didn't work :(. Any other things I can check?
> 
> `lscpu` on both would be interesting (can try and dig that info from the bring-up code, to see what machine types are they using in each)

in aws these seems to be m4.xlarge
which are
"Up to 2.4 GHz Intel Xeon Scalable Processor (Broadwell E5-2686 v4 or Haswell E5-2676 v3)"

**Comment by yuvalk** [comment]
in gcp, this is a n2-standard-4 machine
which is either
Intel® Xeon® Platinum 8373C Processor
or
Intel® Xeon® Gold 6268CL Processor (which is also the default and most likely to get)

so the aws using gen 4 cpus whereas in gcp it's most likely gen 2

I dont know if that is an explanation
maybe worth a shot trying to run in gcp on newer cpus  (if u know how to reproduce the issue)

**Comment by Missxiaoguo** [comment]
> > > > do you know what are the differences between the machine types (gcp vs aws)?
> > > 
> > > 
> > > @yuvalk I am not aware of the differences. As far as I know, same memory(16G) and vcpus(4), also OVN kubernetes. I have no idea why gcp didn't work :(. Any other things I can check?
> > 
> > 
> > `lscpu` on both would be interesting (can try and dig that info from the bring-up code, to see what machine types are they using in each)
> 
> in aws these seems to be m4.xlarge which are "Up to 2.4 GHz Intel Xeon Scalable Processor (Broadwell E5-2686 v4 or Haswell E5-2676 v3)"

The machine type for gcp is e2-standard-4
```
sh-4.4# lscpu
Architecture:       x86_64
CPU op-mode(s):     32-bit, 64-bit
Byte Order:         Little Endian
CPU(s):             4
On-line CPU(s) list: 0-3
Thread(s) per core: 2
Core(s) per socket: 2
Socket(s):          1
NUMA node(s):       1
Vendor ID:          GenuineIntel
BIOS Vendor ID:     Google
CPU family:         6
Model:              79
Model name:         Intel(R) Xeon(R) CPU @ 2.20GHz
Stepping:           0
CPU MHz:            2200.216
BogoMIPS:           4400.43
Hypervisor vendor:  KVM
Virtualization type: full
L1d cache:          32K
L1i cache:          32K
L2 cache:           256K
L3 cache:           56320K
NUMA node0 CPU(s):  0-3
Flags:              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
```
The machine type for aws is m6a.xlarge.
```

**Comment by Missxiaoguo** [comment]
> in gcp, this is a n2-standard-4 machine which is either Intel® Xeon® Platinum 8373C Processor or Intel® Xeon® Gold 6268CL Processor (which is also the default and most likely to get)
> 
> so the aws using gen 4 cpus whereas in gcp it's most likely gen 2
Ah, I see..

> I dont know if that is an explanation maybe worth a shot trying to run in gcp on newer cpus (if u know how to reproduce the issue)

Yeah, I was also wondering it was due to limited resources, so I issued a rehearsal with type n2-standard-8 which didn't work either :(
https://github.com/openshift/release/commit/6eda2583e157cc45ac60e80200b68e01e51d475b

**Pull request merged**
