### PR TITLE
[PERFSCALE-3249] Ingress configuration for scalelab job

### PR DESCRIPTION
**Pull request by rsevilla87**
Updating ingress configuration for baremetal job.

cc @jtaleric @josecastillolema

### CODE REVIEW

**Comment by rsevilla87** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by rsevilla87** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by rsevilla87** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by rsevilla87** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by rsevilla87** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Review by jtaleric — APPROVED** [review]
/lgtm

**Pull request merged**
