### PR TITLE
Introduce openshift-e2e-aws-csi-install workflow

### PR DESCRIPTION
**Pull request by jsafrane**
Create `openshift-e2e-aws-csi-install` workflow that still uses `TEST_INSTALL_CSI_DRIVERS` and thus install AWS EBS CSI driver as part of the CI job. This one should be used in 4.5 and older jobs.

For now, `openshift-e2e-aws-csi-install` is the same as `openshift-e2e-aws-csi`, but the end goal is to rework the later one to use CSI driver installed by cluster setup. I'll do it as a separate PR to keep rehearsals working (see https://github.com/openshift/release/pull/11093 for the full changeset).

### CODE REVIEW

**Comment by jsafrane** [comment]
Most of rehearse jobs either succeeded at least once or flaked during test due to known issues.

**Review by droslean — APPROVED** [review]

**Pull request merged**
