### PR TITLE
HyperShift-MCE: add step:hypershift-mce-dump

### PR DESCRIPTION
**Pull request by LiangquanLi930**

### CODE REVIEW

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.13-periodics-e2e-kubevirt-mce-conformance

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.13-periodics-e2e-aws-ovn-mce-conformance

**Review by davidvossel — COMMENTED** [review]
/lgtm
/approve

**Review by rokej — APPROVED** [review]

**Pull request merged**
