### PR TITLE
ovirt: Add machine-config-operator presubmit

### PR DESCRIPTION
**Pull request by rgolangh**
Depends-on: #4340

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
waiting for #4340 to merge. looks fine otherwise.

/hold

**Comment by rgolangh** [comment]
On Mon, 6 Jan 2020 at 20:32, Kirsten <notifications@github.com> wrote:

> waiting for #4340 <https://github.com/openshift/release/pull/4340> to
> merge. looks fine otherwise.
>

It is other way round, this PR is necessary for #4340 to be green to merge.

/hold

**Comment by kikisdeliveryservice** [comment]
wait.. now im confused... is it post holiday haze? :)

This PR is adding ovirt tests to MCO right?  But AFAICT https://github.com/openshift/installer/pull/1948 which is what adds ovirt to installer isn't merged yet no?

So wouldn't this PR depend on #1948?  We can't run any tests until installer can install ovirt... no?

Looking closely, not sure why installer e2e would depend on mco e2e (via #4340 )

Can you clarify so I understand?

**Comment by rgolangh** [comment]
You are 100% right, I was confusing this with other mao PR. This is my
evening haze :)

**Comment by rgolangh** [comment]
@kikisdeliveryservice https://github.com/openshift/release/pull/4340 is merged

**Pull request merged**
