### PR TITLE
Enable e2e-metal-ipi on oc

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by wking** [comment]
If you do 4.4 and master, shouldn't you do 4.5 too?

**Comment by stbenjam** [comment]
> If you do 4.4 and master, shouldn't you do 4.5 too?

The last time I tried to add it to 4.5/4.6, DPTP told me a bot automatically does it. I don't know how often it runs but it does seem to happen sometimes: https://github.com/openshift/release/commit/3b5dca59829c20cdb880f61648c6493a98f168c6

**Comment by soltysh** [comment]
> The last time I tried to add it to 4.5/4.6, DPTP told me a bot automatically does it. I don't know how often it runs but it does seem to happen sometimes: [3b5dca5](https://github.com/openshift/release/commit/3b5dca59829c20cdb880f61648c6493a98f168c6)

Sometimes doesn't sound convincing, why not just make it there, it definitely doesn't hurt :wink:

**Comment by stbenjam** [comment]
It also doesn’t not hurt. I can add it later if the script doesn’t do it. I won’t be around for a few more hours to add it. It’d be nice if we could test the oc PR and unbreak us m....

**Comment by stbenjam** [comment]
I guess it doesn't matter since https://github.com/openshift/oc/pull/392 is approved and going to merge.

It seems odd to me that `oc` PR's that affect disconnected installation gets lots of code merged without a single CI test that tests disconnected installs.

**Comment by soltysh** [comment]
> It seems odd to me that `oc` PR's that affect disconnected installation get merged without a single CI test that does a disconnected install, or does e2e-cmd do that?

Nobody added it since there was no clear requirement, yet. e2e-cmd is different, in the long run it will turn to be part of regular e2e.

**Pull request closed without merging**
