### PR TITLE
Cleanup list of jobs we have

### PR DESCRIPTION
**Pull request by jhutar**

### CODE REVIEW

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-konflux-ci-e2e-tests-main-load-test-ci-100u

**Review by pmacik — CHANGES_REQUESTED** [review]
@jhutar good idea, I'd also remove the following jobs:
* tekton-tuning-base
* tekton-tuning-tuned
* max-concurrency-basic-tekton-tuned

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-konflux-ci-e2e-tests-main-load-test-ci-100u

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-konflux-ci-e2e-tests-main-load-test-ci-100u

**Comment by jhutar** [comment]
/pj-rehearse periodic-ci-konflux-ci-e2e-tests-main-load-test-ci-daily-100u

**Comment by jhutar** [comment]
/pj-rehearse periodic-ci-konflux-ci-e2e-tests-main-load-test-ci-daily-100u

**Pull request merged**
