### PR TITLE
cert-rotation: don't copy registry CA manually

### PR DESCRIPTION
**Pull request by vrutkovs**
Rely on REGISTRY_CA_PATH env var in config.sh.

Required after https://github.com/openshift/assisted-service/pull/6485

### CODE REVIEW

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.18-e2e-metal-ovn-sno-cert-rotation-suspend-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.18-e2e-metal-ovn-sno-cert-rotation-suspend-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.18-e2e-metal-ovn-sno-cert-rotation-suspend-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.18-e2e-metal-ovn-sno-cert-rotation-suspend-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.18-e2e-metal-ovn-sno-cert-rotation-suspend-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.18-e2e-metal-ovn-sno-cert-rotation-suspend-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.18-e2e-metal-ovn-sno-cert-rotation-suspend-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.18-e2e-metal-ovn-sno-cert-rotation-suspend-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.18-e2e-metal-ovn-sno-cert-rotation-suspend-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.18-e2e-metal-ovn-sno-cert-rotation-suspend-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.18-e2e-metal-ovn-sno-cert-rotation-suspend-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.18-e2e-metal-ovn-sno-cert-rotation-suspend-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.18-e2e-metal-ovn-sno-cert-rotation-suspend-90d

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Pull request merged**
