### PR TITLE
WIP: Unconfigured ephemeral installer

### PR DESCRIPTION
**Pull request by bmanzari**
Add CI integrations for [AGENT-559](https://issues.redhat.com//browse/AGENT-559) and [AGENT-574](https://issues.redhat.com//browse/AGENT-574) epics

### CODE REVIEW

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-ephe-compact-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-ephe-compact-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-ephe-compact-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-ephe-compact-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-ephe-ha-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-ephe-sno-agent-ipv4-dynamic-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-ephe-compact-agent-ipv4-dynamic-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-ephe-compact-agent-ipv4-dynamic-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-ephe-compact-agent-ipv4-dynamic-connected-p1-f14

**Comment by zniu1011** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-agent-baremetal-ephe-sno-agent-ipv4-dynamic-connected-p1-f14

**Pull request closed without merging**
