### PR TITLE
Apply the needs-upstream label for PRs with vendor changes

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/cc @deads2k @kargakis @smarterclayton

### CODE REVIEW

**Comment by deads2k** [comment]
@soltysh can you explain how you would use this for blocking upstream pulls during  a kube rebase?

**Comment by stevekuznetsov** [comment]
We can expand the submit-queue's negative label list to include it (think the opposite of the `kind/bug` flow)

**Comment by kargakis** [comment]
We will get it for free with `tide` but yeah, in the meantime we can add it in the submit queue.

/lgtm

**Comment by kargakis** [comment]
It still sucks that the queue will need to restart for the label change.

**Comment by stevekuznetsov** [comment]
What I wanted to do, which would not be webhook based, was use a graphql query and commenter bot to just add /hold on to the prs...

**Comment by kargakis** [comment]
SGTM. We should run something similar when we add new blocking presubmits.

**Pull request merged**
