### PR TITLE
Add jobs of installations with Kuryr to the Installer

### PR DESCRIPTION
**Pull request by MaysaMacedo**
Adds optional pre-submit jobs of ocp installation
with Kuryr to the installer.

### CODE REVIEW

**Comment by pierreprinetti** [comment]
You set `always_run: true`. If you really want it to run on every PR, you can mimic `e2e-openstack` and do:
```
always_run: false
run_if_changed: ^([^d]|d(d|o(d|cd))*([^do]|o([^cd]|c[^ds])))*(d(d|o(d|cd))*(oc?)?)?$
```

or you can [go even fancier](https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#triggering-jobs-based-on-changes) with something like:

```
always_run: false
skip_if_only_changed: ^docs/
```

(feel free to improve; you may want to also exclude `^upi/` and other paths)

**Comment by MaysaMacedo** [comment]
> You set `always_run: true`. If you really want it to run on every PR, you can mimic `e2e-openstack` and do:
> 
> ```
> always_run: false
> run_if_changed: ^([^d]|d(d|o(d|cd))*([^do]|o([^cd]|c[^ds])))*(d(d|o(d|cd))*(oc?)?)?$
> ```
> 
> or you can [go even fancier](https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#triggering-jobs-based-on-changes) with something like:
> 
> ```
> always_run: false
> skip_if_only_changed: ^docs/
> ```
> 
> (feel free to improve; you may want to also exclude `^upi/` and other paths)

good point, thanks

**Review by pierreprinetti — APPROVED** [review]

**Comment by sdodson** [comment]
@MaysaMacedo is it expected that those jobs are currently failing?

**Comment by MaysaMacedo** [comment]
@sdodson It's expected some flakiness with master/4.9.
The master job failed while deprovision due to a [bug](https://storyboard.openstack.org/#!/story/2008254) on Octavia that probably is just missing a backport.
All the jobs have passed at least once with [the current commit.](https://prow.ci.openshift.org/pr-history/?org=openshift&repo=release&pr=19879)

**Comment by sdodson** [comment]
Since these are optional and not always run accepting them with failing rehearsals.
/lgtm
/approve

**Pull request merged**
