### PR TITLE
Fix OCS/ODF tests step for Interop

### PR DESCRIPTION
**Pull request by rabin-io**

### CODE REVIEW

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.12-ocp-cnv-odf-4.12-cnv-odf-tests-aws-upi-ocp412

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.12-ocp-cnv-odf-4.12-cnv-odf-tests-aws-upi-ocp412

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.12-ocp-cnv-odf-4.12-cnv-odf-tests-aws-upi-ocp412

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.12-ocp-cnv-odf-4.12-cnv-odf-tests-aws-upi-ocp412

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.12-ocp-cnv-odf-4.12-cnv-odf-tests-aws-upi-ocp412

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.12-ocp-cnv-odf-4.12-cnv-odf-tests-aws-upi-ocp412

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.16-ocp-cnv-odf-4.16-cnv-odf-tests-aws-upi-ocp416

**Review by lukas-bednar — APPROVED** [review]
/lgtm

**Comment by Sau1506mya** [comment]
Hi @rabin-io , @lukas-bednar , Can we test the rehearsal job for `-lp-interop` tests also before merging of this PR?

**Comment by Sau1506mya** [comment]
> Hi @rabin-io , @lukas-bednar , Can we test the rehearsal job for `-lp-interop` tests also before merging of this PR?

I have re-triggered the job manually for CNV and it passed - [https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-RedHatQE-i[…]p-interop-cnv-odf-tests-aws-upi-ocp416/1790648485536600064](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-RedHatQE-interop-testing-cnv-4.16-cnv-odf-ocp4.16-lp-interop-cnv-odf-tests-aws-upi-ocp416/1790648485536600064 )

**Pull request merged**
