### PR TITLE
Update ocm-agent builder to golang-1.17

### PR DESCRIPTION
**Pull request by weherdh**
As title.
This is related to the [OA](https://github.com/openshift/ocm-agent/pull/47) update using go 1.17.

### CODE REVIEW

**Comment by mrbarge** [comment]
There's a few other spots in that file that might need changing too, can you change those as well?

https://github.com/openshift/release/blob/0f0b42f40b1b7b08563e9aaa3c92179be27a3f86/ci-operator/config/openshift/ocm-agent/openshift-ocm-agent-master.yaml#L6

https://github.com/openshift/release/blob/0f0b42f40b1b7b08563e9aaa3c92179be27a3f86/ci-operator/config/openshift/ocm-agent/openshift-ocm-agent-master.yaml#L19

https://github.com/openshift/release/blob/0f0b42f40b1b7b08563e9aaa3c92179be27a3f86/ci-operator/config/openshift/ocm-agent/openshift-ocm-agent-master.yaml#L21

**Comment by weherdh** [comment]
> Member

Updated. Thanks

**Pull request merged**
