### PR TITLE
UPI GCP sdn migration to ovn and rollback

### PR DESCRIPTION
**Pull request by weliang1**
For https://issues.redhat.com/browse/OCPQE-11142: UPI GCP sdn migration to ovn and rollback

@anuragthehatter @zhaozhanqi @lihongan PTAL!

### CODE REVIEW

**Comment by weliang1** [comment]
@jianlinliu Could you help to figure out why validation jobs keep failing? 
```
level=info msg=Waiting up to 20m0s (until 6:49PM) for the Kubernetes API at https://api.ci-op-xjg3kc7g-8e913.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:6443/...
level=error msg=Attempted to gather ClusterOperator status after wait failure: listing ClusterOperator objects: Get "https://api.ci-op-xjg3kc7g-8e913.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:6443/apis/config.openshift.io/v1/clusteroperators": dial tcp 35.223.19.241:6443: i/o timeout
level=info msg=Use the following commands to gather logs from the cluster
level=info msg=openshift-install gather bootstrap --help
level=error msg=Bootstrap failed to complete: Get "https://api.ci-op-xjg3kc7g-8e913.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:6443/version": dial tcp 35.223.19.241:6443: i/o timeout
level=error msg=Failed waiting for Kubernetes API. This error usually happens when there is a problem on the bootstrap host that prevents creating a temporary control plane.
```

**Comment by jianlinliu** [comment]
> Could you help to figure out why validation jobs keep failing?

From must-gather log, I can see the following:
```
$ cat bootstrap/journals/release-image.log | head -4
-- Logs begin at Fri 2022-09-23 00:59:19 UTC, end at Fri 2022-09-23 01:24:38 UTC. --
Sep 23 00:59:52 ci-op-klxqiqhy-8e913-qlpdj-bootstrap.c.XXXXXXXXXXXX.internal systemd[1]: Starting Download the OpenShift Release Image...
Sep 23 00:59:52 ci-op-klxqiqhy-8e913-qlpdj-bootstrap.c.XXXXXXXXXXXX.internal release-image-download.sh[1883]: Pulling registry.build02.ci.openshift.org/ci-op-klxqiqhy/release@sha256:0245eeeefc20093827ee6fcbd3e05cbd515c02745324393b44a478fd75f4c94e...
Sep 23 00:59:54 ci-op-klxqiqhy-8e913-qlpdj-bootstrap.c.XXXXXXXXXXXX.internal release-image-download.sh[1956]: Error: initializing source docker://registry.build02.ci.openshift.org/ci-op-klxqiqhy/release@sha256:0245eeeefc20093827ee6fcbd3e05cbd515c02745324393b44a478fd75f4c94e: reading manifest sha256:0245eeeefc20093827ee6fcbd3e05cbd515c02745324393b44a478fd75f4c94e in registry.build02.ci.openshift.org/ci-op-klxqiqhy/release: unauthorized: authentication required
```
That is because your steps did not include `- ref: ipi-install-rbac`.

I compared with the existing upi workflow, seem like you are writing a new workflow from the very beginning, but not modify based on the existing workflow.  Personally I suggest you to copy some existing workflow, then modify them to integrate your feature based on them, because the existing workflows are tested well,  we can avoid such issues to save some time.

 After go a simple review on the PR, I have some more questions:
1. `ref: sdn-conf` is after `chain: upi-conf-gcp`, I do not think the sdn-conf setting will be respected. @lihongan has ever hit such similar issue in https://github.com/openshift/release/pull/32057#issuecomment-1241521464
2. More importantly, I saw `gcp/ipi/sdn/sdn2ovn-rollback` is already existing, is it necessary to do it again on UPI? Personally I think the networking rollback testing in IPI and UPI make no much difference, sounds like a bit duplicated.

**Comment by lihongan** [comment]
> 2\. More importantly, I saw `gcp/ipi/sdn/sdn2ovn-rollback` is already existing, is it necessary to do it again on UPI? Personally I think the networking rollback testing in IPI and UPI make no much difference, sounds like a bit duplicated.

@zhaozhanqi any idea regarding this? 
From my opinion, I think we just need to keep one e2e test on UPI or IPI in each platform, also agree with Jianlin that no difference between them. And on the other hand, I think this PR is just to create workflow but we can apply one of them to e2e test. for example:
in 4.12 we are testing rollback in:
```
AWS IPI
Azure UPI
GCP IPI
vSphere UPI
```
in 4.13 we are testing rollback in:
```
AWS UPI
Azure IPI
GCP UPI
vSphere IPI
```

**Comment by jianlinliu** [comment]
>  I think this PR is just to create workflow but we can apply one of them to e2e test.

Once workflows are merged, we need to notify productivity team to run what kinds of e2e testing on which workflows. So if we can confirm rollback make no much difference between IPI and UPI, I even suggest not add any UPI rollback workflow. This is similar case like installer private cluster case,  in prow ci, if we can use IPI to install a private cluster, we would never add UPI private cluster workflow.

**Comment by lihongan** [comment]
Yes, having one workflow on IPI or UPI is also acceptable.
@zhaozhanqi WDYT?, if that's OK then we can review https://issues.redhat.com/browse/OCPQE-10826 and remove/close some sub-tasks that created for IPI and UPI.

**Comment by zhaozhanqi** [comment]
> Yes, having one workflow on IPI or UPI is also acceptable. @zhaozhanqi WDYT?, if that's OK then we can review https://issues.redhat.com/browse/OCPQE-10826 and remove/close some sub-tasks that created for IPI and UPI.

IMO, they are also no difference,  However according to the dev's jira issue mentioned IPI and UPI. so like we better cover both. 
eg. https://issues.redhat.com/browse/NP-575(Support the SDN migration on IBM cloud platform for both UPI and IPI clusters)

However I think we do not need to create so many sdn2ovn workflow as I talked with weibin in https://coreos.slack.com/archives/GLDDW02SJ/p1663849118895879
means we just use existing basic sdn(IPI and UPI) workflow,  then invoke the 
```
    test:
    - chain: cucushift-sdn-migration-ovn
```
example PR https://github.com/openshift/release/pull/32392/files

**Comment by jianlinliu** [comment]
> However according to the dev's jira issue mentioned IPI and UPI.

Maybe we can have a confirm with dev, if dev have no preference to test it in one of them or both, then we can drop the UPI one, that will save us a lot of effort. (Compare UPI and IPI, IPI is definitely our high-priority choice, IPI is tidy and easy install and destroy than UPI)

**Comment by weliang1** [comment]
> > 2. More importantly, I saw `gcp/ipi/sdn/sdn2ovn-rollback` is already existing, is it necessary to do it again on UPI? Personally I think the networking rollback testing in IPI and UPI make no much difference, sounds like a bit duplicated.
> 
> @zhaozhanqi any idea regarding this? From my opinion, I think we just need to keep one e2e test on UPI or IPI in each platform, also agree with Jianlin that no difference between them. And on the other hand, I think this PR is just to create workflow but we can apply one of them to e2e test. for example: in 4.12 we are testing rollback in:
> 
> ```
> AWS IPI
> Azure UPI
> GCP IPI
> vSphere UPI
> ```
> 
> in 4.13 we are testing rollback in:
> 
> ```
> AWS UPI
> Azure IPI
> GCP UPI
> vSphere IPI
> ```

@zhaozhanqi @jianlinliu @lihongan Dev agree us to do the way as @lihongan  mentioned here.
I close this PR now, thanks everyone for reviewing.

**Pull request closed without merging**
