### PR TITLE
ROX-17163: bump rox-ci-image to go version 1.19.9 for release-3.74

### PR DESCRIPTION
**Pull request by tommartensen**
Bumping test images to a version with Go 1.19.9.

@gavin-stackrox has already green-lit the changes in https://github.com/openshift/release/pull/39423, but I split the PRs for 3.73 and 3.74 for simplified testing, so need a `lgtm` from a reviewer here.

Reviewers may ignore the specific test failures, they're due to Go version incompability (newer Go version in runner than on `release-3.74` branch). 
The updates for the `release-3.74` branch are being implemented in https://github.com/stackrox/stackrox/pull/6066. 

After merging this PR, I can run the tests properly in `stackrox/stackrox` and fix any issues / cherry-pick existing fixes.

### CODE REVIEW

**Comment by tommartensen** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-release-3.74-grouped-static-checks pull-ci-stackrox-stackrox-release-3.74-integration-unit-tests pull-ci-stackrox-stackrox-release-3.74-ocp-4-11-qa-e2e-tests pull-ci-stackrox-stackrox-release-3.74-local-roxctl-tests

**Review by gavin-stackrox — APPROVED** [review]
/lgtm

**Comment by tommartensen** [comment]
/pj-rehearse ack

We ignore CI failures for now and fix them after code on release-3.74 is changed to Go 1.19 in https://github.com/stackrox/stackrox/pull/6066

**Pull request merged**
