### PR TITLE
peel off apply-release-image-signature option when mirror images

### PR DESCRIPTION
**Pull request by jianlinliu**

### CODE REVIEW

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.11-arm64-nightly-4.11-upgrade-from-stable-4.10-aws-ipi-disconnected-private-p2-f14

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-stable-4.13-upgrade-from-stable-4.12-vsphere-ipi-disconnected-registry-pvc-p2-f7

**Comment by shellyyang1989** [comment]
Refers to [OCPQE-14239](https://issues.redhat.com/browse/OCPQE-14239)

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-stable-4.13-upgrade-from-stable-4.12-vsphere-ipi-disconnected-registry-pvc-p2-f7

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-stable-4.13-upgrade-from-stable-4.12-vsphere-ipi-disconnected-registry-pvc-p2-f7

**Comment by jianlinliu** [comment]
The PR also works when mirroring an signed image in https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/38236/rehearse-38236-periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-stable-4.13-upgrade-from-stable-4.12-vsphere-ipi-disconnected-registry-pvc-p2-f7/1646084176614526976/artifacts/vsphere-ipi-disconnected-registry-pvc-p2-f7/cucushift-upgrade-mirror-images-by-oc-adm/build-log.txt

**Comment by jianlinliu** [comment]
@shellyyang1989 @JianLi-RH the PR is ready to review.

**Comment by shellyyang1989** [comment]
The change looks good to me! Thank you Jianlin. As the change is specifically done for c2s, could we please run a test on aws c2s?

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-4.14-upgrade-from-stable-4.13-aws-c2s-ipi-disconnected-private-p2-f14

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-4.14-upgrade-from-stable-4.13-aws-c2s-ipi-disconnected-private-p2-f14

**Pull request merged**
