### PR TITLE
adjust jenkins e2e template prepare image for recent ci-operator/rele…

### PR DESCRIPTION
**Pull request by gabemontero**
…ase evolution

### CODE REVIEW

**Comment by gabemontero** [comment]
@bparees fyi

@petr-muller or @bbguimaraes  or @droslean  or @stevekuznetsov or @smarterclayton ptal

**Comment by gabemontero** [comment]
FWIW the last jenkins e2e job to pass with the prior env var name for the prepare container was https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_jenkins/740/pull-ci-openshift-jenkins-master-e2e-gcp/84 from 21 days ago for PR https://github.com/openshift/jenkins/pull/740

**Comment by bparees** [comment]
/lgtm
it can't make it worse

**Comment by gabemontero** [comment]
The relevant ci-operator config is https://github.com/openshift/release/blob/master/ci-operator/config/openshift/jenkins/openshift-jenkins-master.yaml#L12-L20 and https://github.com/openshift/release/blob/master/ci-operator/config/openshift/jenkins/openshift-jenkins-master.yaml#L79-L85

That second link in particular gives me pause

**Comment by bparees** [comment]
> That second link in particular gives me pause to some degree 

yeah that second link would make me think that IMAGE_TESTS would map to the same thing as IMAGE_JENKINS_E2E_TESTS in which case this PR wouldn't change anything.  I guess we'll find out in a minute.

**Pull request merged**
