### PR TITLE
Back to current rhcos 8.5

### PR DESCRIPTION
**Pull request by deads2k**
reverts https://github.com/openshift/release/pull/27563/commits

### CODE REVIEW

**Comment by hongkailiu** [comment]
/approve

/hold

in case you want to wait for the rehearsal ...

**Comment by deads2k** [comment]
oh, how much worse can it get :)

/hold cancel

**Comment by deads2k** [comment]
/hold

holding to give a standard for ovn if they can fix themselves in time.

**Comment by deads2k** [comment]
heh, fun.  Well, here we go.

**Pull request merged**
