### PR TITLE
sync run_if_changed/skip_if_only_changed from jobs to ci-op config

### PR DESCRIPTION
**Pull request by droslean**
/cc @openshift/test-platform 

The script that was used is:
```python
import os
from ruamel.yaml import YAML
from pathlib import Path


from yaml.loader import SafeLoader


job_path = 'ci-operator/jobs'
config_path = 'ci-operator/config'

yaml = YAML(typ='rt')
yaml.preserve_quotes = True
yaml.default_flow_style = True

def parse_org_repo(path):
    return os.path.basename(os.path.dirname(os.path.dirname(path))), os.path.basename(os.path.dirname(path))

for (dirpath, dirnames, filenames) in os.walk(job_path):
    for filename in filenames:
        if filename.endswith('presubmits.yaml'):
            org_repo = parse_org_repo(os.path.join(dirpath, filename))
            with open(os.path.join(dirpath, filename), 'r') as f:
                data = yaml.load(f)
                    
                jobs = data['presubmits'][org_repo[0] + "/" + org_repo[1]]
                for job in jobs:
                    if 'skip_if_only_changed' in job and 'spec' in job and job['spec']['containers'][0]['command'][0] == 'ci-operator':
                        
                        test_name = job['context'].removeprefix("ci/prow/")
                        trimmed = filename.removesuffix('-presubmits.yaml')
                        ci_op_config = '{}.yaml'.format(trimmed)
                        
                        if 'labels' in job and 'ci-operator.openshift.io/variant' in job['labels']:
                            ci_op_config = '{}__{}.yaml'.format(trimmed, job['labels']['ci-operator.openshift.io/variant'])                        
                        ci_op_config_path = os.path.join(config_path, org_repo[0], org_repo[1], ci_op_config)

                        ci_op_data = yaml.load(Path(ci_op_config_path))
                        if 'tests' in ci_op_data: 
                            for test in ci_op_data['tests']:
                                if test['as'] == test_name:
                                    test['skip_if_only_changed'] = job['skip_if_only_changed']


                        yaml.dump(ci_op_data, Path(ci_op_config_path))
```

Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

### CODE REVIEW

**Comment by droslean** [comment]
https://issues.redhat.com/browse/DPTP-2505

**Comment by petr-muller** [comment]
Can you share the script/code you used? It may be useful for other occasions.

**Comment by droslean** [comment]
> Can you share the script/code you used? It may be useful for other occasions.

@petr-muller added in the description

**Review by petr-muller — APPROVED** [review]
Sweet

**Pull request merged**
