### PR TITLE
trivial commit to rerun tests - no need to approve nor to merge!

### PR DESCRIPTION
**Pull request by naftalysh**

### CODE REVIEW

**Comment by naftalysh** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-10u-10t-nodejs

**Comment by naftalysh** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-10u-10t-nodejs

**Comment by naftalysh** [comment]
This PR is just to run the pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-10u-10t-nodejs test again 
It will be closed once tests are finished
No need to approve it

**Comment by naftalysh** [comment]
The problem with running the nodejs load test was due to misconfiguration of load-test-scenario.ci-10u-10t-nodejs in vault - https://vault.ci.openshift.org/ui/vault/secrets/kv/show/selfservice/rhtap-load-test/rhtap-load-test

load-test-scenario.ci-10u-10t-nodejs - 
"export USER_PREFIX=ci-nodejs USERS_PER_THREAD=10 THREADS=10 COMPONENT_REPO=ttps://github.com/nodeshift-starters/devfile-sample.git"

I fixed it in vault in rhtap-load-test secret (with new secret version) to be - 
"export USER_PREFIX=ci-nodejs USERS_PER_THREAD=10 THREADS=10 COMPONENT_REPO=https://github.com/nodeshift-starters/devfile-sample.git"

And re running the test again

**Comment by naftalysh** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-10u-10t-nodejs

**Comment by naftalysh** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-10u-10t-nodejs

**Comment by naftalysh** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-10u-10t-nodejs

**Comment by naftalysh** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-10u-10t-nodejs

**Comment by naftalysh** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-10u-10t-nodejs

**Comment by naftalysh** [comment]
pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-10u-10t-quarkus

**Comment by naftalysh** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-10u-10t-nodejs

**Comment by naftalysh** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-10u-10t-nodejs

**Comment by smg247** [comment]
@naftalysh in order to not `cc` a bunch of people when you do this. Comment `/cc noone` in the PR body

**Comment by naftalysh** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-10u-10t-nodejs

**Comment by naftalysh** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-10u-10t-nodejs

**Comment by naftalysh** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-10u-10t-nodejs

**Comment by naftalysh** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-10u-10t-nodejs

**Comment by naftalysh** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-10u-10t-nodejs

**Comment by naftalysh** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-10u-10t-nodejs

**Comment by naftalysh** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-10u-10t-nodejs

**Comment by naftalysh** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-10u-10t-nodejs

**Comment by naftalysh** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-10u-10t-nodejs

**Pull request closed without merging**
