### PR TITLE
Change registry reference for image customization controller image

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Comment by dtantsur** [comment]
LGTM. Is it ready to go?

**Comment by elfosardo** [comment]
@dtantsur this should be ready, I don't see other places where we need to change the name in the release repo,
keep in mind that the final test will be https://github.com/openshift/cluster-baremetal-operator/pull/260, after this has merged

**Comment by zaneb** [comment]
/assign @bparees
Ben, this change was requested by @smarterclayton in #23976.

**Pull request merged**
