### PR TITLE
RHDH Openshift-ci cluster pool setup for ephemeral cluster claim

### PR DESCRIPTION
**Pull request by subhashkhileri**
https://issues.redhat.com/browse/RHIDP-4762

### CODE REVIEW

**Comment by subhashkhileri** [comment]
/pj-rehearse periodic-ci-janus-idp-backstage-showcase-main-e2e-tests-nightly-ocp-v14

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-main-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-main-e2e-tests

**Review by Prucek — APPROVED** [review]

**Pull request merged**
