### PR TITLE
Adding nightly SRO e2e test runs in ci-artifacts

### PR DESCRIPTION
**Pull request by dagrayvid**
This PR will enable running the SRO (upstream master) e2e tests against 4.7 and 4.8 nightly builds of OCP using the openshift-psap/ci-artifacts repository.

### CODE REVIEW

**Comment by dagrayvid** [comment]
The 4.8 error looks like a simple 403 error in a yum install in the entitlement test...
/retest

**Comment by kpouget** [comment]
@dagrayvid, entitlement on 4.8 cannot work at the moment, forget about it!

**Comment by kpouget** [comment]
thanks @dagrayvid 

/lgtm

/test ci-secret-bootstrap-config-validation

**Comment by kpouget** [comment]
great @dagrayvid :D (comment was on the wrong PR yesterday :#)

feel free to create a PR for https://github.com/openshift-psap/ci-dashboard/,
hopefully you should just have to duplicate&adapt https://github.com/openshift-psap/ci-dashboard/blob/master/examples/gpu-operator.yml (+ GitHub actions)

**Pull request merged**
