### PR TITLE
hypershift: mce-kubevirt 4.13

### PR DESCRIPTION
**Pull request by LiangquanLi930**
add: `conformance-mce-kubevirt`
update: `conformance-mce-aws-ovn`'s `MCE_VERSION` to 2.3

### CODE REVIEW

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-mce-aws-ovn

**Review by rokej — APPROVED** [review]

**Comment by davidvossel** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-mce-aws-ovn

rehearsal failed due to aws capacity issues. let's try again

```We currently do not have sufficient m6a.xlarge capacity in the Availability Zone you requested (us-east-1d).```

**Review by davidvossel — COMMENTED** [review]
the code looks fine. some of the file names are still strange though.

for example, the create/destroy step registries being used have the `2.2` version in them, but are being used for mce 2.3. Can we rename those files now?

```ci-operator/step-registry/hypershift/mce/kubevirt/create/2.2/hypershift-mce-kubevirt-create-2.2-chain.yaml```

^ maybe that should be something like

```ci-operator/step-registry/hypershift/mce/kubevirt/create/hypershift-mce-kubevirt-create-chain.yaml```

?

**Pull request merged**
