### PR TITLE
ci-operator/templates/openshift/installer/cluster-launch-installer-e2e: tail installer log in setup container

### PR DESCRIPTION
**Pull request by dcbw**
Instead of having to jump to a terminal and tail it yourself.

### CODE REVIEW

**Comment by dcbw** [comment]
@stevekuznetsov this look OK? Saves me a couple clicks and a bunch of typing at least once or twice a day...

**Comment by wking** [comment]
Instead of hopping on the CI cluster and watching logs, you can get a kubeconfig for an in-flight PR job by getting the namespace from the build log.  For example, [this job][1] has:

```
2020/01/28 21:23:29 Using namespace ci-op-ywnz700y
```

Then run:

```console
$ while ! oc -n ci-op-ywnz700y rsync -c setup e2e-aws:/tmp/artifacts/installer/auth/kubeconfig .; do sleep 30; done
$ while ! oc --request-timeout 5s --config kubeconfig get clusterversion version; do sleep 30; done
```

which polls the CI cluster until it can copy down the `kubeconfig` and then polls the cluster-under-test until it reports a ClusterVersion.  Example output looks like:

```
Error from server (NotFound): pods "e2e-aws" not found  <- waiting for the pod to launch
...
error: invalid path kubeconfig: stat kubeconfig: no such file or directory  <- waiting for the installer to run
...
receiving incremental file list
kubeconfigsent 43 bytes  received 9,109 bytes  3,660.80 bytes/sec
total size is 9,016  speedup is 0.99
...
error: the server doesn't have a resource type "clusterversion"  <- etcd-signer pretends to be the Kube API, but doesn't actually serve any resources
...
The connection to the server api.ci-op-ywnz700y-1d3f3.origin-ci-int-aws.dev.rhcloud.com:6443 was refused - did you specify the right host or port?  <- etcd-signer stopped (etcd probably up), but no bootstrap API server up yet
...
Error from server (NotFound): clusterversions.config.openshift.io "version" not found  <- bootstrap API server up, ClusterVersion CRD up, CVO not up yet
...
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version             False       True          29s     Working towards 0.0.1-2020-01-28-213341: 46% complete
```

/close

**Pull request closed without merging**
