### PR TITLE
vSphere vcm fix wicd

### PR DESCRIPTION
**Pull request by jcpowermac**

### CODE REVIEW

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.16-wicd-unit-vsphere pull-ci-openshift-windows-machine-config-operator-release-4.12-wicd-unit-vsphere pull-ci-openshift-windows-machine-config-operator-master-wicd-unit-vsphere

**Comment by mansikulkarni96** [comment]
Thanks for fixing this for us @jcpowermac 
/approve

**Review by mansikulkarni96 — APPROVED** [review]

**Pull request merged**
