### PR TITLE
CNV-40288: add kubevirt must-gather to hcp

### PR DESCRIPTION
**Pull request by nunnatsa**

### CODE REVIEW

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn-kubevirt pull-ci-openshift-origin-master-e2e-aws-ovn-kubevirt

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn-kubevirt pull-ci-openshift-origin-master-e2e-aws-ovn-kubevirt

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn-kubevirt pull-ci-openshift-origin-master-e2e-aws-ovn-kubevirt

**Review by davidvossel — COMMENTED** [review]
/lgtm
/approve

nice!

**Pull request merged**
