### PR TITLE
[FoO-CSB] Making use of secrets in place of configmaps where required

### PR DESCRIPTION
**Pull request by smongiar**
@oharan2 @calebevans @Sau1506mya

### CODE REVIEW

**Comment by smongiar** [comment]
jvrubel is on PTO @madunn can we merge it anyway? or can we assign it to @Croway in place of him?

**Comment by smongiar** [comment]
> @smongiar Yes we can merged without them. I am verifying whether or not we want to run a rehearsal on this in the group chat. If we want to run one, I can execute it and we can commence with the review process.

@calebevans thank you, for me it's ok. We can run a rehearsal job. Take in account that I will be in PTO tomorrow since January, 5th

**Comment by calebevans** [comment]
@smongiar sure, we can probably get this resolved today. Can you just respond to Adam here: https://redhat.enterprise.slack.com/archives/C069LEFS92P/p1703081252602069

This is just to ensure that even if a leak were to occur, before the files are made public, the secrets found in vault are redacted.

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.15-lp-interop-csb-interop-aws-latest

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.15-lp-interop-jboss-fuse-interop-aws

**Comment by smongiar** [comment]
Any update on this? :) Are we ready to merge? @calebevans @oharan2

**Pull request merged**
