### PR TITLE
Move RBACs for api.ci to core-services/various_rbac

### PR DESCRIPTION
**Pull request by hongkailiu**
Follow up https://coreos.slack.com/archives/CBN38N3MW/p1593460791327300

We could either move the files to core-service (where the applyconfig is enabled already) or enable it on the targeting folder.
I chose the latter in this PR.
I did not choose the former because it would be applied to `app.ci` as well and `app.ci` might not want it.

I believe the files were not moved to the core-service folder because it is RBAC yaml.
We enable `applyconfig` on RBAC only recently.

/assign @petr-muller 

Need Petr's input on this PR.

I believe there are other yamls that we need to apply manually, e.g., https://github.com/openshift/release/blob/master/cluster/ci/config/roles.yaml
But I do not want to apply other files in that folder.

/hold

/cc @openshift/openshift-team-developer-productivity-test-platform @bparees

### CODE REVIEW

**Comment by petr-muller** [comment]
> We could either move the files to core-service (where the applyconfig is enabled already) or enable it on the targeting folder. 
> I chose the latter in this PR.
> I did not choose the former because it would be applied to app.ci as well and app.ci might not want it.
> I believe the files were not moved to the core-service folder because it is RBAC yaml.
> We enable applyconfig on RBAC only recently.

We should 100% move the files from `cluster/...` - that was always the goal. The reason why we never moved these was not the fact that they are RBAC (`applyconfig` always handled RBAC fine), but because they are a heap of various RBAC that do not belong to any specific single "thing" and that heap would need to be broken down and triaged, and nobody ever invested the effort.

So I think we should do one of the following:
1) Either bite the bullet, break that file down and put the individual pieces into the applyconfig-covered directories to which they belong (might be even new ones)
2) Or just move it to somewhere in `core-services`, call it "Various RBAC" or something.

**Comment by hongkailiu** [comment]
> I did not choose the former because it would be applied to app.ci as well and app.ci might not want it.

This claim is not true.

Chose the 2nd option that Petr gave me.

**Comment by hongkailiu** [comment]
> I think the old locations are still refered to in the Makefile. They should be removed.

Removed.

**Pull request merged**
