### PR TITLE
ACS Scanner release 2.28

### PR DESCRIPTION
**Pull request by RTann**
/uncc
/hold

### CODE REVIEW

**Comment by RTann** [comment]
@jvdm @dcaravel @daynewlee just note to approve PRs in this repo, you have to comment `/lgtm`. You need both a approval and an lgtm, and typically you get an approval for free if you are an OWNER of the file(s) in question

**Comment by RTann** [comment]
```
rtannenb:~/go/src/github.com/RTann/release$ diff ci-operator/config/stackrox/scanner/stackrox-scanner-release-2.27.yaml ci-operator/config/stackrox/scanner/stackrox-scanner-release-2.28.yaml
--- ci-operator/config/stackrox/scanner/stackrox-scanner-release-2.27.yaml	2023-02-01 16:08:43
+++ ci-operator/config/stackrox/scanner/stackrox-scanner-release-2.28.yaml	2023-02-01 17:33:41
@@ -185,6 +185,6 @@
           cpu: 2000m
           memory: 4000Mi
 zz_generated_metadata:
-  branch: release-2.27
+  branch: release-2.28
   org: stackrox
   repo: scanner
```

**Comment by dcaravel** [comment]
> Also note the stuff in jobs/ is generated

Were the new files in `jobs/` generated by running `make jobs` locally and then committing?

**Comment by RTann** [comment]
> > Also note the stuff in jobs/ is generated
> 
> @RTann Were the new files in `jobs/` generated by running `make jobs` locally and then committing?

yep! In case you forget to do that when editing this yourself, CI will remind you and tell you the command to run.

**Review by dcaravel — APPROVED** [review]
/lgtm

**Pull request merged**
