### PR TITLE
cinder-operator master branch renamed to main

### PR DESCRIPTION
**Pull request by ASBishop**

### CODE REVIEW

**Comment by viroel** [comment]
prow-config is failing due to different build clusters [1]
Can you try to run `make jobs` and check if it changes the build cluster?

[1] https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/39337/pull-ci-openshift-release-master-ordered-prow-config/1658194965274038272/build-log.txt

**Comment by fmount** [comment]
@ASBishop you might need to run `sudo make jobs` as suggested by the failure [1]

[1] https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/39337/pull-ci-openshift-release-master-ordered-prow-config/1658194965274038272

**Comment by ASBishop** [comment]
@fmount thanks, running that now. Without the sudo I just got hundreds of "permission denied"

**Comment by dprince** [comment]
@ASBishop I included the cinder updates in the PR here: https://github.com/openshift/release/pull/39341 Perhaps we just abandon this and do them all at once?

**Comment by ASBishop** [comment]
https://github.com/openshift/release/pull/39341 merged, superseding this patch.

**Pull request closed without merging**
