### PR TITLE
Update python for openshift ansible

### PR DESCRIPTION
**Pull request by barbacbd**
Updated ansible python version to python3. /usr/bin/python fails during 4.12 and earlier versions.

### CODE REVIEW

**Comment by barbacbd** [comment]
/pj-rehearse pull-ci-openshift-openshift-ansible-release-4.11-e2e-aws-workers-rhel8
/pj-rehearse pull-ci-openshift-openshift-ansible-release-4.12-e2e-aws-workers-rhel8
/pj-rehearse pull-ci-openshift-openshift-ansible-release-4.13-e2e-aws-workers-rhel8
/pj-rehearse pull-ci-openshift-openshift-ansible-release-4.14-e2e-aws-workers-rhel8

**Comment by barbacbd** [comment]
/pj-rehearse pull-ci-openshift-openshift-ansible-release-4.13-e2e-aws-workers-rhel8

**Comment by barbacbd** [comment]
/pj-rehearse pull-ci-openshift-openshift-ansible-release-4.11-e2e-aws-workers-rhel8

**Comment by barbacbd** [comment]
/pj-rehearse pull-ci-openshift-openshift-ansible-release-4.11-e2e-aws-workers-rhel8

**Review by vrutkovs — APPROVED** [review]
/approve
/lgtm

**Comment by barbacbd** [comment]
/pj-rehearse pull-ci-openshift-openshift-ansible-release-4.11-e2e-aws-workers-rhel8

**Comment by barbacbd** [comment]
/pj-rehearse pull-ci-openshift-openshift-ansible-release-4.11-e2e-aws-workers-rhel8

**Comment by barbacbd** [comment]
/pj-rehearse pull-ci-openshift-openshift-ansible-release-4.11-e2e-aws-workers-rhel8

**Comment by barbacbd** [comment]
/pj-rehearse pull-ci-openshift-openshift-ansible-release-4.11-e2e-aws-workers-rhel8

**Comment by barbacbd** [comment]
/pj-rehearse pull-ci-openshift-openshift-ansible-release-4.11-e2e-aws-workers-rhel8

**Pull request closed without merging**
