### PR TITLE
Add NVIDIA GPU test on OCP 4.17 nightly builds

### PR DESCRIPTION
**Pull request by empovit**
* Run the CI jobs on 4.17 once a week
* Deploy the operator from a master bundle
* Update othe jobs to avoid running on weekends

### CODE REVIEW

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-nvidia-ci-main-4.17-nvidia-gpu-operator-e2e-master

**Review by wabouhamad — COMMENTED** [review]
/lgtm

**Pull request merged**
