### PR TITLE
introduce parameterized test image template

### PR DESCRIPTION
**Pull request by bparees**
also switch auth console test job to use parameterized image template

### CODE REVIEW

**Comment by bparees** [comment]
blocked on https://github.com/openshift/release/pull/4425

**Comment by bparees** [comment]
@spadgett @enj ptal, you're first into the breech on being converted to use a generic parameterized test image instead of a hardcoded one.

**Comment by abhinavdahiya** [comment]
Why are we adding yet another template to create the cluster?

**Comment by bparees** [comment]
> Why are we adding yet another template to create the cluster?

@abhinavdahiya we are adding a new template to control how tests are run against the cluster (via a parameterized image) so that teams can easily have jobs that are run against arbitrary repos, that will run their tests against PRs for those repos.  

Once all the existing users of the console-specific template are updated to this, we can remove that template, so there will not be a net add of templates.

**Comment by bparees** [comment]
spoke w/ @enj on slack.  applying lgtm label.

@stevekuznetsov @bbguimaraes can one of you approve?

**Pull request merged**
