### PR TITLE
METAL-752: Remove 4.10 ipv6 jobs

### PR DESCRIPTION
**Pull request by derekhiggins**
The 4.10 IPv6 jobs are broken (we can't mirror the images as the "oc adm release mirror" command doesn't support
"--keep-manifest-list=true"

4.10 is also EOL so delete these jobs.

### CODE REVIEW

**Review by iurygregory — APPROVED** [review]

**Review by JoelSpeed — COMMENTED** [review]
/approve

**Comment by dcbw** [comment]
@derekhiggins I was pretty sure this all worked on 4.10 at some point... do we know what broke?

**Comment by derekhiggins** [comment]
closing in favour of fixing

**Pull request closed without merging**
