### PR TITLE
OCPBUGS-28548: add cloud-provider-aws RPM to artifacts image

### PR DESCRIPTION
**Pull request by LorbusChris**
Alternative approach to https://github.com/openshift/release/pull/48171/files
/cc @theobarberbany

### CODE REVIEW

**Comment by LorbusChris** [comment]
this'll need a couple of approvals
/assign @deads2k @elmiko @jmguzik

**Comment by sdodson** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-aws-release-4.15-e2e-aws-ovn

**Comment by sdodson** [comment]
```
[2/2] STEP 4/6: RUN rpm -Uvh --oldpackage /*.rpm && rm -vf /*.rpm /usr/share/rpm/__db.* /usr/share/rpm/.*.lock
Verifying...                          ########################################
Preparing...                          ########################################
	package ecr-credential-provider-4.15.0-999999999999.el9.x86_64 is already installed
error: build error: building at STEP "RUN rpm -Uvh --oldpackage /*.rpm && rm -vf /*.rpm /usr/share/rpm/__db.* /usr/share/rpm/.*.lock": while running runtime: exit status 2
```

**Comment by vrutkovs** [comment]
/retitle OCPBUGS-28548: add cloud-provider-aws RPM to artifacts image

**Comment by theobarberbany** [comment]
@sdodson @LorbusChris 

I'm not too sure what's going on here. I think that because we are promoting the rpms image, and the rpm we build has a fixed version/release (4.X.X-99999?) when we come to upgrade we already are at the latest version? This doesn't qutie make sense to me though, as I thought we were using centos stream9 (and promoting rpms as `cloud-provider-aws-rpms`)

I guess we could add the date and build time to the release, but then we would keep a large number of previous builds in the image. 

Is there a nicer approach or something I'm missing?

**Comment by theobarberbany** [comment]
Let's try and see what happens when this merged: https://github.com/openshift/release/pull/48266

The ci built images (release 9999...) don't exist in the rhel-coreos images.

**Comment by theobarberbany** [comment]
https://github.com/openshift/release/pull/48266 merged.

/unhold

**Comment by theobarberbany** [comment]
Using https://github.com/openshift/release/pull/48496 in favour of this PR.  

/hold

@LorbusChris can we close this PR? :)

**Pull request closed without merging**
