### PR TITLE
ROX-14352: Mirror new image.

### PR DESCRIPTION
**Pull request by porridge**
Pick up https://github.com/stackrox/rox-ci-image/pull/176

### CODE REVIEW

**Review by gavin-stackrox — APPROVED** [review]

**Comment by porridge** [comment]
The change to `clusters/` is a result of `make multi-arch-gen` that was complained about by CI.
@janisz can you please /lgtm this again (I bumped the version to the one built from the tag).

**Review by jmguzik — APPROVED** [review]

**Pull request merged**
