### PR TITLE
fix: add run_if_changed field for rhoam-e2e job

### PR DESCRIPTION
**Pull request by psturc**
### Description

Don't run rhoam-e2e test if a PR doesn't contain changes to the integreatly-operator codebase

Based on [test/e2e job](https://github.com/openshift/release/blob/1b760bf9b54dca5867168f90fed7631683cd0848/ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-master-presubmits.yaml#L17)

### CODE REVIEW

**Comment by psturc** [comment]
hey @philbrookes, would you mind giving this PR a quick look?

**Comment by philbrookes** [comment]
Maybe we could also expressly not match `*.sh|*.md`?

**Review by philbrookes — APPROVED** [review]

**Comment by psturc** [comment]
@philbrookes the regex I've previously added [seems to be working fine](regexr.com/5fd2b), but the Prow `config` job was failing, because Golang doesn't support [regex negative lookaheads](https://github.com/kubernetes/test-infra/issues/9095). It's not the easiest thing to workaround this and I've come up with a solution for filtering out `*.md` files only.
You can test it [here](regexr.com/5feik)

Let me know what you think

**Review by philbrookes — APPROVED** [review]

**Pull request merged**
