### PR TITLE
trt-1451: add e2e-azure-ovn-serial

### PR DESCRIPTION
**Pull request by neisw**

### CODE REVIEW

**Comment by neisw** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.16-e2e-azure-ovn-serial

**Comment by neisw** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.16-e2e-azure-ovn-serial

**Comment by neisw** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.16-e2e-azure-ovn-serial

**Comment by neisw** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.16-e2e-azure-ovn-serial

**Review by stbenjam — COMMENTED** [review]
Looks correct to me

- Can we remove release-openshift-ocp-installer-e2e-azure-serial-* jobs?
- And add this one going back to a couple of releases? (Maybe 4.15 and 4.14?)

**Comment by neisw** [comment]
/pj-rehearse ack

Jobs run.  4.16 passes but times out due to resource watch,  4.15 has  a pathological event failure but the job runs and these are added as informing so we can monitor.

**Review by deepsm007 — APPROVED** [review]

**Pull request merged**
