### PR TITLE
ARMOCP-431: hypershift: mgmt e2e with CP on ARM64

### PR DESCRIPTION
**Pull request by LiangquanLi930**
https://issues.redhat.com/browse/ARMOCP-516

### CODE REVIEW

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-aws-ipi-ovn-hypershift-mgmt-p2-f21

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-aws-ipi-ovn-hypershift-mgmt-p2-f21

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-aws-ipi-ovn-hypershift-mgmt-p2-f21

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-ipi-ovn-hypershift-mgmt-p2-f21

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-aws-ipi-ovn-hypershift-mgmt-p2-f21

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-nightly-aws-ipi-ovn-hypershift-mgmt-p2-f7

**Comment by LiangquanLi930** [comment]
/pj-rehearse  periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-aws-ipi-ovn-hypershift-mgmt-p2-f7

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-aws-ipi-ovn-hypershift-mgmt-p2-f7

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-aws-ipi-ovn-hypershift-mgmt-p2-f7

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-aws-ipi-ovn-hypershift-mgmt-p2-f7

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-aws-ipi-ovn-hypershift-mgmt-p2-f7

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-aws-ipi-ovn-hypershift-mgmt-p2-f7

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-aws-ipi-ovn-hypershift-mgmt-p1-f7

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-aws-ipi-ovn-hypershift-mgmt-p1-f7

**Comment by LiangquanLi930** [comment]
@kuiwang02 @liangxia Could you help to review this PR? thanks

**Comment by heliubj18** [comment]
1. this pr is to create a new pipeline for hypershift  clusters with arm control plane and amd64 worker nodes.  
2. run test cases with the `HyperShiftMGMT` filter

**Review by aleskandro — APPROVED** [review]

**Comment by kuiwang02** [comment]
iamok from golang's view.

**Comment by LiangquanLi930** [comment]
https://issues.redhat.com/browse/ARMOCP-517

**Comment by bryan-cox** [comment]
/retitle ARMOCP-431: hypershift: mgmt e2e with CP on ARM64

**Pull request merged**
