### PR TITLE
Serverless: Use dockerfile_path for index and bundle image builds

### PR DESCRIPTION
**Pull request by mgencur**
Related to https://issues.redhat.com/browse/SRVCOM-2846

Needs https://github.com/openshift-knative/serverless-operator/pull/2378 in the target repo to work properly.

### CODE REVIEW

**Comment by mgencur** [comment]
/pj-rehearse pull-ci-mgencur-serverless-operator-index_build_context_path-4.13-operator-e2e-aws-ocp-413

**Comment by mgencur** [comment]
/pj-rehearse pull-ci-mgencur-serverless-operator-index_build_context_path-4.13-images

**Comment by mgencur** [comment]
/pj-rehearse pull-ci-mgencur-serverless-operator-index_build_context_path-4.13-operator-e2e-aws-ocp-413

**Comment by mgencur** [comment]
/pj-rehearse pull-ci-mgencur-serverless-operator-index_build_context_path-4.13-operator-e2e-aws-ocp-413

**Comment by mgencur** [comment]
/pj-rehearse pull-ci-mgencur-serverless-operator-index_build_context_path-4.13-images

**Comment by mgencur** [comment]
This is a chicken-egg problem with [pull/2378](https://github.com/openshift-knative/serverless-operator/pull/2378). The CI checks in this PR won't work until the other PR is merged and same applies for that PR.
So, I added a commit that tests the changes against my own repo (github.com/mgencur/serverless-operator) and branch that is used in [pull/2378](https://github.com/openshift-knative/serverless-operator/pull/2378)
The CI checks against my repo passed as can be seen in these runs:
* [4.13-images](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/45387/rehearse-45387-pull-ci-mgencur-serverless-operator-index_build_context_path-4.13-images/1721916471992389632)
* [4.13-operator-e2e-aws-ocp-413](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/45387/rehearse-45387-pull-ci-mgencur-serverless-operator-index_build_context_path-4.13-operator-e2e-aws-ocp-413/1721914158506577920)
I will remove the temporary commit and PR is ready for merging.

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
