### PR TITLE
openshift-machine-config-operator: remove autopromotion to origin

### PR DESCRIPTION
**Pull request by vrutkovs**
MCO needs time to accommodate for FCOS changes, so we'll disable the autopromotion to 4.6/4.7 for now.

OKD team will manually promote MCO images after verification, no further actions required from MCO team.

### CODE REVIEW

**Comment by darkmuggle** [comment]
/hold

Won't the effect of this require the MCO to manually promote OKD? What's the desired outcome of this PR? I fear that removing the MCO from automatic promotions will result in nothing being promoted.

**Comment by ashcrow** [comment]
@vrutkovs What FCOS changes are being referenced here?

**Comment by vrutkovs** [comment]
>Won't the effect of this require the MCO to manually promote OKD?

Yes.

>What's the desired outcome of this PR? I fear that removing the MCO from automatic promotions will result in nothing being promoted.

That gives us time to verify that MCO changes haven't impacted OKD. That certainly would be slower, but should provide a better quality for OKD releases.

>What FCOS changes are being referenced here?

In FCOS Ignition [places ssh keys](https://github.com/coreos/ignition/pull/751) in `~/.ssh/authorized_keys.d/ignition`, but MCO controls `~/.ssh/authorized_keys`. This makes it [fail on FCOS](https://github.com/openshift/machine-config-operator/issues/2385) - and RHCOS is configured to run Ignition with (legacy?) ssh key merging

**Comment by darkmuggle** [comment]
> That gives us time to verify that MCO changes haven't impacted OKD. That certainly would be slower, but should provide a better quality for OKD releases.

Who would promote the MCO, then? I want to be really clear about the expectations and have them clear set. The MCO team is not staffed to take on manual promotion and validation for OKD. Without an explicit understanding of who will do this work, I am unwilling to consent.

**Comment by vrutkovs** [comment]
>Who would promote the MCO, then?

OKD team would

> The MCO team is not staffed to take on manual promotion and validation for OKD.

MCO team has approved promotion for release-4.6/release-4.7/master commits to OKD in https://github.com/openshift/release/pull/12683, it also adds (optional) OKD tests. If [MCO is unwilling to include these results](https://github.com/openshift/machine-config-operator/pull/2404#issuecomment-777633114) when [making a decision to merge a PR](https://github.com/openshift/machine-config-operator/pull/2404#issuecomment-779461882) OKD team will take care of verifying MCO changes. No action from MCO needed

**Comment by darkmuggle** [comment]
This sounds reasonable to me then.
/lgtm

**Comment by vrutkovs** [comment]
Included in https://github.com/openshift/release/pull/15802

**Pull request closed without merging**
