### PR TITLE
OADP-1.2: add e2e periodic jobs for 4.12 and 4.13

### PR DESCRIPTION
**Pull request by hhpatel14**

### CODE REVIEW

**Review by sseago — APPROVED** [review]

**Comment by hhpatel14** [comment]
/pj-rehearse periodic-ci-openshift-oadp-operator-oadp-1.2-4.13-operator-e2e-aws-periodic

**Comment by hhpatel14** [comment]
/pj-rehearse periodic-ci-openshift-oadp-operator-oadp-1.2-4.12-operator-e2e-gcp-periodic

**Comment by hhpatel14** [comment]
/pj-rehearse periodic-ci-openshift-oadp-operator-oadp-1.2-4.12-operator-e2e-gcp-periodic

**Review by kaovilai — APPROVED** [review]

**Pull request merged**
