### PR TITLE
Build Jenkins on top of the UBI image instead of centos

### PR DESCRIPTION
**Pull request by smarterclayton**
Leverage the rhscl repo and the new CLI. Needs openshift/jenkins#801 to merge.

### CODE REVIEW

**Comment by gabemontero** [comment]
@bparees as we discussed on slack, when this merges, we won't be able to test plugin version changes with openshift/jenkins PRs anymore

@adambkaplan fyi / welcome to the fun (at least until @pweil- 's devtools deal closes :-) )

**Comment by bparees** [comment]
> @bparees as we discussed on slack, when this merges, we won't be able to test plugin version changes with openshift/jenkins PRs anymore

can the plugin PR jobs define their own image-build step for the jenkins image that supercedes what is being defined here?  So it could continue to build a centos-based image and install the plugin?

Alternatively, is there a reason the plugin PR jobs can't continue to extend this image by adding the fresh-built plugin on top? (that's what they do today, right?)

**Comment by adambkaplan** [comment]
/hold

until https://github.com/openshift/jenkins/pull/801 merges

**Comment by gabemontero** [comment]
On Tue, Feb 19, 2019 at 1:11 PM Ben Parees <notifications@github.com> wrote:

> @bparees <https://github.com/bparees> as we discussed on slack, when this
> merges, we won't be able to test plugin version changes with
> openshift/jenkins PRs anymore
>
> can the plugin PR jobs define their own image-build step for the jenkins
> image that supercedes what is being defined here? So it could continue to
> build a centos-based image and install the plugin?
>
Yeah my assumption was we could continue to test our plugin changes via the
plugin PR jobs.  There have been no changes to those jobs since they do not
produce images to be published.

It is testing say a change to the k8s plugin or one of the other jenkins
plugins (typically to fix a security advisory) pulled in our jenkins image
that would have to be done manually.

**Comment by bparees** [comment]
> It is testing say a change to the k8s plugin or one of the other jenkins plugins (typically to fix a security advisory) pulled in our jenkins image that would have to be done manually.

ah, got it.  yeah that is ugly.

**Comment by gabemontero** [comment]
@bparees @smarterclayton @adambkaplan 

So I have question out to the ART folks on clarifying how I can specify refs to specific commit levels for the jenkins core and plugin RPMs

With that piece of information, we can then flip our current openshift/jenkins repo PR test scenario from
1) test changes on centos for either plugin or core version bumps ... alter the versions accordingly if tests fail, etc.
2) when validated, run the update jobs for the RPMs with the vetted versions

to
1) build new levels of those RPMs at the versions we want to test
2) update the dockerfile during a openshift/jenkins PR to point to those new RPMs specifically,
3) when the tests pass, the image is produced
4) if the test fails, iterate over new RPMs with different combinations of  plugins and jenkins core until we get one that works

We just need to decide which step we take first
1) unholding this PR
2) updating the the Dockefile to point to the specific RPM levels

**Comment by gabemontero** [comment]
OK, after talking with @adammhaile the idea in https://github.com/openshift/release/pull/2901#issuecomment-467160025 is a non starter.

- they only keep the latest version of the RPMs we build
- keeping older versions is not possible
- specifying specific versions goes against their best practice

@adammhaile suggested storing the plugin files in our github repo, but @bparees says that approach is untenable.

My next endeavor will be  if I can 
- take the current aos-cd-jobs that ART has provided at https://github.com/openshift/aos-cd-jobs/tree/master/jobs/devex for updating the two jenkins RPMS
- understand the current ci-operator rpm capabilities (see rpm_build* steps at https://github.com/openshift/ci-operator/blob/master/CONFIGURATION.md along with any example usages I can find at https://github.com/openshift/release
- and augment the jenkins rhel docker strategy build so that it installs rpms built as part of an openshift/jenkins PR for testing 

I see some sort of meeting amongst the particulars here in our future, but I'll see how far I can get by digging first.

**Comment by bparees** [comment]
Can we make the dockerfile + scripts inside it smart enough to do the right thing?

ie smart enough to in one scenario pull the plugins from upstream, and in another attempt to install them from rpms?

**Comment by gabemontero** [comment]
Yeah something along those lines is the goal ... the bullets I mentioned previously are *potential* means to that end .... perhaps
- when running in api.ci, we download from upstream and test, and then generate the rpm in brew *if testing is successful*
- when running in osbs, it uses the rpm we generated during api.ci testing 

I just have no idea yet if that is possible, or how much change to existing CI is needed to make it possible

**Comment by gabemontero** [comment]
so using the `rpm_build*` stuff appears a no-go as well

as I mentioned in scrum, my making `the dockerfile + scripts inside it smart enough to do the right thing` to quote @bparees will entail examining envs which will only exist in the api.ci / PR form to do our download plugin hpi form, and when they are not there, do the rpm install

essentially a merge in some form of 2/Dockerfile into 2/Dockerfile.rhel7 from openshift/jenkins and factoring in whether it impacts opneshift-jenkins-2.ym in openshift/ocp-build-data (though I don't think it should)

then we can merge this puppy

**Comment by gabemontero** [comment]
After https://github.com/openshift/jenkins/pull/810 merges, we should be able to remove the hold on this and merge unless we still need review from a non @smarterclayton person from DPTP

I'll ping them on testplatform slack if need be

**Comment by smarterclayton** [comment]
No additional review needed.  But let me know so I can look at 810

**Comment by gabemontero** [comment]
On Tue, Mar 5, 2019 at 5:27 PM Clayton Coleman <notifications@github.com>
wrote:

> No additional review needed. But let me know so I can look at 810


Both 810 and the associated ocp-build-data PRs have merged

Ptal @smarterclayton at your convenience

/hold cancel

**Comment by gabemontero** [comment]
The ocp-build-data secret sauce at https://github.com/openshift/library/blob/master/official.yaml is what goes with https://github.com/openshift/jenkins/pull/810

**Comment by gabemontero** [comment]
bump @smarterclayton

**Comment by gabemontero** [comment]
reminder, the motivation for https://github.com/openshift/library/blob/master/official.yaml (negotiation in openshift/ocp-build-data#48) and openshift/jenkins#810 are
1) be able to test new versions of jenkins core and non-openshift plugins in or openshift/jenkins PRs (where we download those new items from jenkins proper)
2) cut new RPMs in brew once those combinations have been vetted
3) build the osbs/brew images via those RPMs in brew

**Comment by smarterclayton** [comment]
Currently failing
https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/branch-ci-openshift-jenkins-master-images/52
- I may need to bump the base image again.

**Comment by gabemontero** [comment]
@smarterclayton actually I think I need to make some more changes to https://github.com/openshift/jenkins/blob/master/2/Dockerfile.rhel7 as part of the move to a "hybrid" where we download plugins in api.ci and yum install them in osbs

See 
```
chgrp: cannot dereference ‘/opt/openshift/plugins/*hpi.jpi’: No such file or directory
chmod: cannot operate on dangling symlink ‘/opt/openshift/plugins/*hpi.jpi’
chown: cannot access ‘/usr/lib/jenkins/*hpi’: No such file or directory
```

from https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/branch-ci-openshift-jenkins-master-images/52

**Comment by gabemontero** [comment]
working it via https://github.com/openshift/jenkins/pull/814

**Comment by gabemontero** [comment]
the image build completed with https://github.com/openshift/jenkins/pull/814 so progress ... now tracking e2e's while awaiting any review comments

**Pull request merged**
