### PR TITLE
Add bastion-telco workflow to step-registry

### PR DESCRIPTION
**Pull request by johnbieren**
This lets you set up an openshift cluster using the bastion-telco ssh service.

I will add a way to run tests with this workflow in a followup PR soon

Signed-off-by: Johnny Bieren <jbieren@redhat.com>

### CODE REVIEW

**Comment by johnbieren** [comment]
The tests complain about mountPath in the yaml, but I pulled that directly from https://steps.ci.openshift.org/help#credentials

**Comment by johnbieren** [comment]
@yuvalk can you review this PR?

**Review by hongkailiu — APPROVED** [review]

**Pull request merged**
