### PR TITLE
API-1783: Revert payload timeout increase

### PR DESCRIPTION
**Pull request by dinhxuanvu**
Revert https://github.com/openshift/release/pull/51865

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
Hold until [origin is rebased](https://github.com/openshift/origin/pull/28828).
/hold

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by dinhxuanvu** [comment]
@jupierce Hey Justin, would you mind approving this PR? Thanks.

**Comment by dinhxuanvu** [comment]
@jmguzik Would you please approve this PR? Thanks :)

**Review by jmguzik — APPROVED** [review]

**Pull request merged**
