### PR TITLE
Adding other IAAS

### PR DESCRIPTION
**Pull request by kasturinarra**
Adding other IAAS in the yaml file

### CODE REVIEW

**Comment by kasturinarra** [comment]
@liangxia @wsun1 could you please help review ? Thanks !!

**Comment by liangxia** [comment]
@kasturinarra  Run `make update` to generate the jobs.

**Comment by kasturinarra** [comment]
@liangxia i have run 'make update' and updated the PR, could you please help check again ? Thanks !!

**Comment by liangxia** [comment]
Perhaps take the baremetal one out, as it fails at installation stage which needs more check.

**Comment by kasturinarra** [comment]
> Perhaps take the baremetal one out, as it fails at installation stage which needs more check.

@liangxia removed baremetal and updated again, thanks !!

**Pull request merged**
