### PR TITLE
update reliability job

### PR DESCRIPTION
**Pull request by qiliRedHat**
https://issues.redhat.com/browse/OCPQE-24497

### CODE REVIEW

**Comment by qiliRedHat** [comment]
/pj-rehearse pull-ci-openshift-svt-master-reliability-v2-master-images

**Comment by qiliRedHat** [comment]
/pj-rehearse pull-ci-openshift-svt-master-reliability-v2-aws-4.17-nightly-x86-reliability-v2-1h

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-svt-master-reliability-v2-aws-4.17-nightly-x86-reliability-v2-1h

**Comment by qiliRedHat** [comment]
/pj-rehearse pull-ci-openshift-svt-master-reliability-v2-aws-4.17-nightly-x86-reliability-v2-1h

**Comment by qiliRedHat** [comment]
/pj-rehearse pull-ci-openshift-svt-master-reliability-v2-aws-4.17-nightly-x86-reliability-v2-1h

**Comment by qiliRedHat** [comment]
/pj-rehearse pull-ci-openshift-svt-master-reliability-v2-aws-4.17-nightly-x86-reliability-v2-1h

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-svt-master-reliability-v2-aws-4.17-nightly-x86-reliability-v2-1h

**Comment by qiliRedHat** [comment]
/pj-rehearse pull-ci-openshift-svt-master-reliability-v2-azure-4.15-nightly-x86-reliability-v2-1h

**Comment by qiliRedHat** [comment]
/pj-rehearse pull-ci-openshift-svt-master-reliability-v2-aws-4.17-nightly-x86-reliability-v2-1h

**Comment by qiliRedHat** [comment]
/pj-rehearse pull-ci-openshift-svt-master-reliability-v2-aws-4.17-nightly-x86-reliability-v2-1h

**Comment by qiliRedHat** [comment]
@paigerube14 The new image for reliability works now after merging this pr https://github.com/openshift/release/pull/55407 to add the image promote yaml file. The test passed on the image pulling stage, reliability test it self failed which is expected because of an issue with an openshift template. So this pr can be merged. Please help to review, thanks!

**Pull request merged**
