### PR TITLE
openstack: Fix unbound variables

### PR DESCRIPTION
**Pull request by pierreprinetti**
* Fix unbound variables
* `[[` is undefined in POSIX sh

### CODE REVIEW

**Comment by pierreprinetti** [comment]
/uncc  jcpowermac mtnbikenc
/cc mandre tomassedovic

This might supersede https://github.com/openshift/release/pull/6727 , if it passes reharse.

**Comment by tomassedovic** [comment]
/lgtm
/hold

Holding to make sure it's not merged before demonstrating the OpenStack job is fixed. I like it, thanks!

Hope this works :-)

**Comment by tomassedovic** [comment]
Okay, the OpenStack job has failed, but it got past the unbound variables issues. And the bootstrapping failure is something we still need to resolve (unrelated to this).

I'm in favour of merging this now, but I'd like to hear @mandre's opinion as well.

**Comment by pierreprinetti** [comment]
@mandre @tomassedovic 

We have a chicken-and-egg problem here with https://github.com/openshift/cluster-image-registry-operator/pull/438 ; however, setup seems to complete. I suggest to merge this patch so that we can start fixing the next bug in the stack

**Comment by tomassedovic** [comment]
@pierreprinetti I thought the CIRO issue (https://github.com/openshift/cluster-image-registry-operator/pull/438) happened much later -- after bootstrapping had completed.

So I think the bootstrap issue we're seeing in the job here is not going to be fixed by that PR. But it isn't related to this change either. I.e. I'm in favour of merging this too.

**Comment by pierreprinetti** [comment]
:+1: 
/hold cancel

**Comment by mandre** [comment]
A little late to the party :+1:

**Pull request merged**
