### PR TITLE
openstack/BYON: enable openshift-e2e-test minimal

### PR DESCRIPTION
**Pull request by EmilienM**
Add more coverage to BYON CI job, by running the openshift-e2e-test
workflow, with experimental/reliability/minimal test suite.

### CODE REVIEW

**Comment by pierreprinetti** [comment]
The test results do not look like flakes, but just in case:
/retest

**Comment by pierreprinetti** [comment]
/lgtm
/hold

Please remove the /hold once the tests pass.

**Comment by EmilienM** [comment]
/test pj-rehearse
500 error on registry.build01.ci.openshift.org

**Review by mandre — COMMENTED** [review]
/lgtm

**Pull request merged**
