### PR TITLE
Onboard devfile organization and devworkspace-operator repo

### PR DESCRIPTION
**Pull request by flacatus**
Run e2e tests in OCP 4.4. and 4.5.
Signed-off-by: flacatus <flacatus@redhat.com>

### CODE REVIEW

**Comment by flacatus** [comment]
@petr-muller I didn't found docs about auto-merge... Is there an example to do it?

**Comment by flacatus** [comment]
I'm asking for future projects. For this project we don't need automated merge...

**Comment by petr-muller** [comment]
It's in the "new component onboarding" doc... https://docs.google.com/document/d/1SQ_qlkcplqhe8h6ONXdgBr7YUVbs4oRSj4ISl3gpLW4/edit#heading=h.cq05syqgopx

Without automated merges, plugins like `approve` and `lgtm` do not make much sense (unless you use them in your manual process), that's why I ask. For just tests you could basically just have `trigger`.

**Comment by flacatus** [comment]
@petr-muller  For now I want them for manual process. Maybe in the future We add automated merges but not now.

**Comment by flacatus** [comment]
@petr-muller Can we merge?

**Pull request merged**
