### PR TITLE
[INTEROP-7539][INTEROP-7513] Distributed Tracing:OpenTelemetry: Expand to OCP 4.18; create FIPS config.

### PR DESCRIPTION
**Pull request by dfrazzette**
Include OCP 4.18 FIPS-enabled testing. Also add `.config.prowgen`/`slack_reporter` config and default Jira assignee.

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.18-lp-interop-opentelemetry-interop-aws periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.18-lp-interop-opentelemetry-interop-aws-fips

**Review by iblancasa — APPROVED** [review]
/lgtm

**Pull request merged**
