### PR TITLE
USHIFT-1106: switch verify target to verify-ci

### PR DESCRIPTION
**Pull request by dhellmann**
Use the more comprehensive verify-ci target to include all of the checks.

Depends on: https://github.com/openshift/microshift/pull/1678

### CODE REVIEW

**Comment by dhellmann** [comment]
The rehearse logs for the job on main are https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/38420/rehearse-38420-pull-ci-openshift-microshift-main-verify/1648482296413556736/artifacts/verify/verify/build-log.txt

/pj-rehearse pull-ci-openshift-microshift-release-4.15-verify
/pj-rehearse pull-ci-openshift-microshift-release-4.14-verify

**Comment by dhellmann** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.15-verify pull-ci-openshift-microshift-release-4.14-verify

**Comment by ggiguash** [comment]
I think we can merge this change now.
/lgtm

**Comment by dhellmann** [comment]
@ggiguash I want to make sure nothing breaks on the 4.14 or 4.15 branches, then I'll leave the rehearsal ack and let this merge.

**Pull request merged**
