### PR TITLE
OCPQE-21589: reassign the domain ocp-dev-ppc64le.com to multi-arch-cicd.cis.ibm.net or ipi-ppc64le.cis.ibm.net

### PR DESCRIPTION
**Pull request by prb112**
[OCPQE-21589](https://issues.redhat.com//browse/OCPQE-21589): reassign the domain ocp-dev-ppc64le.com to multi-arch-cicd.cis.ibm.net or ipi-ppc64le.cis.ibm.net

### CODE REVIEW

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-ibmcloud-ovn-multi-ppc64le-f7

**Comment by MayXuQQ** [comment]
based on comments in [OCPQE-21589](https://issues.redhat.com/browse/OCPQE-21589) 
/lgtm

**Comment by prb112** [comment]
Hi @jhou1 @liangxia  Could you approve this configuration changes? We are going to fix workflow changes in a subsequent PR so we can continue fixing the Cucushift / CI as a PowerDev team (in parallel).Thank you, Paul

Thanks @MayXuQQ

**Comment by prb112** [comment]
Thank you very much @liangxia

**Pull request merged**
