### PR TITLE
TRT-1875: lightspeed-service periodic variants

### PR DESCRIPTION
**Pull request by neisw**
Separate ocp releases to individual variant configs

### CODE REVIEW

**Comment by neisw** [comment]
/pj-rehearse periodic-ci-openshift-lightspeed-service-main-4.15-e2e-ols-cluster

**Comment by neisw** [comment]
/pj-rehearse periodic-ci-openshift-lightspeed-service-main-4.15-e2e-ols-cluster

**Comment by JoaoFula** [comment]
@neisw seems like this issue in the rehearsals is also happening in our existing periodic tests so it should be unrelated to the PR. I would like to still run the rehearsals before we merge though as the changes are pretty extensive.

**Comment by neisw** [comment]
/pj-rehearse periodic-ci-openshift-lightspeed-service-main-4.15-e2e-ols-cluster

**Comment by neisw** [comment]
/pj-rehearse periodic-ci-openshift-lightspeed-service-main-4.16-e2e-ols-cluster
/pj-rehearse periodic-ci-openshift-lightspeed-service-main-4.17-e2e-ols-cluster

**Comment by neisw** [comment]
/pj-rehearse periodic-ci-openshift-lightspeed-service-main-4.17-e2e-ols-cluster

**Comment by neisw** [comment]
@JoaoFula looks like each job has run now.  4.15 and 4.17 had failing tests, I wouldn't think that was related to these changes but have a look.

FWIW it was really just a lift and shift over to separate release specific configs but please do look it over and raise concerns if you have any.

**Comment by JoaoFula** [comment]
Hi @neisw! yeah, the test failures don't seem at all related to the changes.
I just needed to see the rehearsal tests actually run (any potential breaking changes would stop it from running rather than causing test failures) so I think we can approve this PR.
Thank you so much!

**Review by tisnik — COMMENTED** [review]
it looks sane :)

**Pull request merged**
