### PR TITLE
add 1.7 prow tests

### PR DESCRIPTION
**Pull request by anandrkskd**

### CODE REVIEW

**Comment by anandrkskd** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-v1.7-unit pull-ci-redhat-developer-gitops-operator-v1.7-v4.10-ci-index-gitops-operator-bundle pull-ci-redhat-developer-gitops-operator-v1.7-v4.10-e2e pull-ci-redhat-developer-gitops-operator-v1.7-v4.10-images pull-ci-redhat-developer-gitops-operator-v1.7-v4.10-kuttl-parallel pull-ci-redhat-developer-gitops-operator-v1.7-v4.10-kuttl-sequential pull-ci-redhat-developer-gitops-operator-v1.7-v4.11-ci-index-gitops-operator-bundle pull-ci-redhat-developer-gitops-operator-v1.7-v4.11-e2e pull-ci-redhat-developer-gitops-operator-v1.7-v4.11-images pull-ci-redhat-developer-gitops-operator-v1.7-v4.11-kuttl-parallel pull-ci-redhat-developer-gitops-operator-v1.7-v4.11-kuttl-sequential pull-ci-redhat-developer-gitops-operator-v1.7-v4.12-ci-index-gitops-operator-bundle pull-ci-redhat-developer-gitops-operator-v1.7-v4.12-e2e pull-ci-redhat-developer-gitops-operator-v1.7-v4.12-images pull-ci-redhat-developer-gitops-operator-v1.7-v4.12-kuttl-parallel pull-ci-redhat-developer-gitops-operator-v1.7-v4.12-kuttl-sequential

**Comment by anandrkskd** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-v1.7-unit pull-ci-redhat-developer-gitops-operator-v1.7-v4.10-ci-index-gitops-operator-bundle pull-ci-redhat-developer-gitops-operator-v1.7-v4.10-e2e pull-ci-redhat-developer-gitops-operator-v1.7-v4.10-images pull-ci-redhat-developer-gitops-operator-v1.7-v4.10-kuttl-parallel pull-ci-redhat-developer-gitops-operator-v1.7-v4.10-kuttl-sequential pull-ci-redhat-developer-gitops-operator-v1.7-v4.11-ci-index-gitops-operator-bundle pull-ci-redhat-developer-gitops-operator-v1.7-v4.11-e2e pull-ci-redhat-developer-gitops-operator-v1.7-v4.11-images pull-ci-redhat-developer-gitops-operator-v1.7-v4.11-kuttl-parallel pull-ci-redhat-developer-gitops-operator-v1.7-v4.11-kuttl-sequential pull-ci-redhat-developer-gitops-operator-v1.7-v4.12-ci-index-gitops-operator-bundle pull-ci-redhat-developer-gitops-operator-v1.7-v4.12-e2e pull-ci-redhat-developer-gitops-operator-v1.7-v4.12-images pull-ci-redhat-developer-gitops-operator-v1.7-v4.12-kuttl-parallel pull-ci-redhat-developer-gitops-operator-v1.7-v4.12-kuttl-sequential

**Comment by anandrkskd** [comment]
/pj-rehearse ci/rehearse/redhat-developer/gitops-operator/v1.7/v4.10-kuttl-parallel

**Comment by anandrkskd** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-v1.7-v4.11-kuttl-parallel

**Comment by anandrkskd** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-v1.7-unit pull-ci-redhat-developer-gitops-operator-v1.7-v4.10-ci-index-gitops-operator-bundle pull-ci-redhat-developer-gitops-operator-v1.7-v4.10-e2e pull-ci-redhat-developer-gitops-operator-v1.7-v4.10-images pull-ci-redhat-developer-gitops-operator-v1.7-v4.10-kuttl-parallel pull-ci-redhat-developer-gitops-operator-v1.7-v4.10-kuttl-sequential pull-ci-redhat-developer-gitops-operator-v1.7-v4.11-ci-index-gitops-operator-bundle pull-ci-redhat-developer-gitops-operator-v1.7-v4.11-e2e pull-ci-redhat-developer-gitops-operator-v1.7-v4.11-images pull-ci-redhat-developer-gitops-operator-v1.7-v4.11-kuttl-parallel pull-ci-redhat-developer-gitops-operator-v1.7-v4.11-kuttl-sequential pull-ci-redhat-developer-gitops-operator-v1.7-v4.12-ci-index-gitops-operator-bundle pull-ci-redhat-developer-gitops-operator-v1.7-v4.12-e2e pull-ci-redhat-developer-gitops-operator-v1.7-v4.12-images pull-ci-redhat-developer-gitops-operator-v1.7-v4.12-kuttl-parallel pull-ci-redhat-developer-gitops-operator-v1.7-v4.12-kuttl-sequential

**Comment by anandrkskd** [comment]
@varshab1210 can we merge this in

**Comment by varshab1210** [comment]
CI is failing because of https://issues.redhat.com/browse/GITOPS-2985

LGTM! Thanks @anandrkskd 

/pj-rehearse ack

@wtam2018 Can we merge this?

**Comment by wtam2018** [comment]
@varshab1210 Do you mean once https://github.com/redhat-developer/gitops-operator/pull/530/files is merged, tthe two failing tests in v1.7 will pass?

**Comment by anandrkskd** [comment]
@wtam2018 can you approve with `/approve` as well, the PR need approved label to merge.

**Pull request merged**
