### PR TITLE
Adding logs for SSHD

### PR DESCRIPTION
**Pull request by jaypoulz**

### CODE REVIEW

**Comment by clnperez** [comment]
Thanks @jaypoulz! Will these messages log to stdout (so we will be able to see them if we dump the container/pod logs)?

**Comment by jaypoulz** [comment]
@clnperez Yes - the idea is that when this container is started, the output of sshd is printing to stderr. I believe this is the purpose of the -e flag in https://github.com/openshift/release/blob/master/core-services/sshd-bastion/ppc64le-libvirt/deployment.yaml#L223

**Comment by clnperez** [comment]
Ah, didn't see that `-e` flag. Thanks! We had a tunnel issue this morning and couldn't reconnect after many retries, so, would be good to have this in!

**Comment by deepsm007** [comment]
lgtm

**Comment by jaypoulz** [comment]
@deepsm007 I think you need the `/lgtm`

**Comment by jaypoulz** [comment]
🙇‍♂️ 🙏

**Pull request merged**
