### PR TITLE
coreos/rpm-ostree: Add clang-analyzer job

### PR DESCRIPTION
**Pull request by cgwalters**
This is off by default for now (it's expensive) and
it won't actually fail right now, just outputs data until
we've fixed the warnings.

### CODE REVIEW

**Comment by cgwalters** [comment]
This depends on https://github.com/coreos/coreos-assembler/pull/2034

**Comment by jlebon** [comment]
/approve
Did you want to add one for ostree too?

**Comment by cgwalters** [comment]
> Did you want to add one for ostree too?

Yeah...that aspect is a mess.  Keeping things in sync there is painful.  I added https://github.com/coreos/fedora-coreos-tracker/issues/263#issuecomment-772903759
related to this.  For now...I'm concentrating on rpm-ostree since the recent switch to C++ and our combined inexperience there requires as much hand-holding/CI as possible.

/retest

**Comment by cgwalters** [comment]
OK this works now: Direct link to example analyzer logs: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/15593/rehearse-15593-pull-ci-coreos-rpm-ostree-master-clang-analyzer/1358869314257555456/artifacts/test/artifacts/2021-02-08-201335-5914-1/index.html

**Pull request merged**
