### PR TITLE
Move 4.8 release jobs from api.ci to a build farm

### PR DESCRIPTION
**Pull request by petr-muller**
/cc @hongkailiu 

:metal: 

Only TRT cares about 4.8 right now, and I am TRT :P

### CODE REVIEW

**Comment by petr-muller** [comment]
/hold 
/meow

I can haz rehearsals

**Comment by petr-muller** [comment]
```
INFO: Requesting a release from  https://openshift-release.svc.ci.openshift.org/api/v1/releasestream/4.8.0-0.nightly/latest
```

Ah goddamit we dont' have a passing nightly yet :/

**Comment by petr-muller** [comment]
/hold cancel

Looks good to me

**Review by hongkailiu — APPROVED** [review]
Do you need to change the ci back to nightly when available?

**Comment by petr-muller** [comment]
> Do you need to change the ci back to nightly when available?

Yes

**Pull request merged**
