### PR TITLE
Insert post upgrade check on cap to disconnected upgrade chain

### PR DESCRIPTION
**Pull request by shellyyang1989**
@jianlinliu @jiajliu @JianLi-RH for review. Thank you.

### CODE REVIEW

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-stable-4.12-aws-ipi-disc-sno-baselinecaps-none-f28

**Comment by jianlinliu** [comment]
@shellyyang1989 pr-rehearse job failed, because when running https://github.com/openshift/release/blob/master/ci-operator/step-registry/cucushift/upgrade/check/capability/cucushift-upgrade-check-capability-commands.sh#L34, proxy is not exported yet on https://github.com/openshift/release/blob/master/ci-operator/step-registry/cucushift/upgrade/check/capability/cucushift-upgrade-check-capability-commands.sh#L246

**Comment by shellyyang1989** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-stable-4.12-aws-ipi-disc-sno-baselinecaps-none-f28

**Comment by shellyyang1989** [comment]
Refers [OCPQE-17567](https://issues.redhat.com/browse/OCPQE-17567)

**Pull request merged**
