### PR TITLE
Remove unsupported release jobs configuration

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Comment by dtantsur** [comment]
/lgtm

ironic-hardware-inventory-recorder-image should be removed completely

**Comment by elfosardo** [comment]
/hold
addressing some concerns emerged from a discussion on slack first

**Comment by elfosardo** [comment]
/unhold
I think we've clarified the concerns and we can move forward, with the rebase first :/

**Comment by elfosardo** [comment]
@dtantsur @derekhiggins this looks good, can you please have another look ?

**Comment by bparees** [comment]
what's the motivation to remove this?

while i appreciate the idea of cleaning up dead config, this removes our ability to rebuild/test those images in the future if we found ourselves needing to do so, right?  And i'm not sure what we gain by removing it(these jobs are never being run anyway, afaik)

**Comment by elfosardo** [comment]
> what's the motivation to remove this?
> 
> while i appreciate the idea of cleaning up dead config, this removes our ability to rebuild/test those images in the future if we found ourselves needing to do so, right? And i'm not sure what we gain by removing it(these jobs are never being run anyway, afaik)

@bparees the motivation is to reduce the number of configuration files that clutter the images configuration directories and focus on what we actually support. It's true that the jobs do not run, so why keep their configuration? OCP up to version 4.5 is EOL, we don't have any customer on those versions, so we don't really have any real use in rebuild the images.
I believe this type of cleaning should be done regularly to keep the repository uncluttered and essential.
In any case, if we ever need those files back, history is preserved and we could easily recover them.

**Comment by bparees** [comment]
Given the configs are isolated to well-named files that make it clear which release they apply to, it doesn't seem like that much clutter.

Anyway i'm not completely averse to this (as you say, we can recover the config from the git history), but i'm not a fan of doing it on ad-hoc basis for a specific component(it will make reverting it that much harder if we do need to, and harder to even realize that some pieces are missing, when some pieces are still there).  This seems like a decision we should make as a product, if we're satisfied that we can effectively archive these configs for older EOL releases, then let's do it for all them.


@petr-muller @jupierce wdyt?

also @sdodson as you may be one of the people involved in a sudden "oh we need a patch for an extended support customer still running 4.3" escalation.

**Comment by sdodson** [comment]
@bparees I've had assurances that we will never ship new bits up through at least 4.4.

I agree however that we should either remove all 4.0-4.4 config or leave these be assuming the only resources they consume are a few bytes in a git repo (ie: no jobs running, no significant impact on maintaining jobs which are tied to currently supported releases)

**Comment by bparees** [comment]
incidentally, we *are* still running CI for as far back as 4.1:
https://amd64.ocp.releases.ci.openshift.org/#4.1.0-0.ci

(new payload as of 6 weeks ago).

Maybe we shouldn't be, i don't know why we are, but we are.

**Comment by bparees** [comment]
/hold

i'd like to see us make a holistic decision here about CI for EOL releases, not removal individual job configs.

might be a good topic for the weekly CI/Testing/Release arch call.

**Comment by bparees** [comment]
i've queued this up for discussion in the next ci/testing/release arch sync call (which will NOT be the week of feb 14th, due to shift week).

**Comment by bparees** [comment]
we discussed this on the CI/Testing arch call and concluded we do not want to remove EOL release CI config

**Pull request closed without merging**
