### PR TITLE
Add gpu-operator PSAP 4.7 -> 4.8 periodic upgrade tests

### PR DESCRIPTION
**Pull request by omertuc**
/cc @kpouget

### CODE REVIEW

**Comment by kpouget** [comment]
thanks @omertuc, you've been faster than me!

can you add slack reporting in the `jobs` file?

I guess you just duplicated the 4.6->4.7 file, changed the cluster versions and marked it as `always_run: false`, right?

**Comment by omertuc** [comment]
> can you add slack reporting in the `jobs` file?

Will do

> I guess you just duplicated the 4.6->4.7 file, changed the cluster versions and marked it as `always_run: false`, right?

That's right

**Comment by omertuc** [comment]
> @omertuc: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Rerun command
> ci/rehearse/periodic-ci-openshift-psap-ci-artifacts-release-4.8-upgrade-gpu-operator-e2e-upgrade-170	[13ef6f1](https://github.com/openshift/release/commit/13ef6f13c6c86d5773b1d3ee0b960a94f5323170)	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/20629/rehearse-20629-periodic-ci-openshift-psap-ci-artifacts-release-4.8-upgrade-gpu-operator-e2e-upgrade-170/1420058562553450496)	`/test pj-rehearse`
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openshift&repo=release&pr=20629). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:omertuc).

@kpouget do you think it failed because 170 is not certified yet?

**Comment by kpouget** [comment]
@omertuc, no, it's the installation of the operator on 4.7 that failed, this is independent of the upgrade and 4.8

```
2021-07-27 17:33:08,393 p=4121 u=psap-ci-runner n=ansible | roles/gpu_operator_deploy_from_operatorhub/tasks/deploy_from_catalog.yml:111
2021-07-27 17:33:08,393 p=4121 u=psap-ci-runner n=ansible | TASK: gpu_operator_deploy_from_operatorhub : Find the GPU Operator OperatorHub InstallPlan
2021-07-27 17:33:08,393 p=4121 u=psap-ci-runner n=ansible | ----- FAILED ----
2021-07-27 17:33:08,393 p=4121 u=psap-ci-runner n=ansible | 
2021-07-27 17:33:08,393 p=4121 u=psap-ci-runner n=ansible | <command> oc get subscriptions.operators.coreos.com/gpu-operator-certified -n openshift-operators -ojsonpath={@.status.installPlanRef.name}
2021-07-27 17:33:08,393 p=4121 u=psap-ci-runner n=ansible | 
2021-07-27 17:33:08,393 p=4121 u=psap-ci-runner n=ansible | ----- FAILED ----
2021-07-27 17:33:08,402 p=4121 u=psap-ci-runner n=ansible | 
```

I've seen this error multiple times today with the Cluster Pool,
and there are many errors in the [catalog operator logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/20629/rehearse-20629-periodic-ci-openshift-psap-ci-artifacts-release-4.8-upgrade-gpu-operator-e2e-upgrade-170/1420058562553450496/artifacts/gpu-operator-e2e-upgrade-170/0-preupgrade-gpu-operator-test-operatorhub-170/artifacts/009__gpu_operator__deploy_from_operatorhub/catalog_operator.log), 
I'm not sure what is relevant inside these logs ...

**Comment by kpouget** [comment]
@omertuc something wrong wrong with the labels with `upgrade-gpu-operator-e2e-upgrade`:
```
NAME                                 DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                                      AGE
gpu-feature-discovery                0         0         0       0            0           nvidia.com/gpu.deploy.gpu-feature-discovery=true   109m
nvidia-container-toolkit-daemonset   0         0         0       0            0           nvidia.com/gpu.deploy.container-toolkit=true       109m
nvidia-dcgm                          0         0         0       0            0           nvidia.com/gpu.deploy.dcgm=true                    109m
nvidia-dcgm-exporter                 0         0         0       0            0           nvidia.com/gpu.deploy.dcgm-exporter=true           109m
nvidia-device-plugin-daemonset       0         0         0       0            0           nvidia.com/gpu.deploy.device-plugin=true           109m
nvidia-driver-daemonset              1         1         1       1            1           nvidia.com/gpu.deploy.driver=true                  109m
nvidia-mig-manager                   0         0         0       0            0           nvidia.com/gpu.deploy.mig-manager=true             109m
nvidia-node-status-exporter          1         1         1       1            1           nvidia.com/gpu.deploy.node-status-exporter=true    109m
nvidia-operator-validator            0         0         0       0            0           nvidia.com/gpu.deploy.operator-validator=true      109m
```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/20629/rehearse-20629-periodic-ci-openshift-psap-ci-artifacts-release-4.8-upgrade-gpu-operator-e2e-upgrade/1420123700790824960/artifacts/gpu-operator-e2e-upgrade/2-postupgrade-gpu-operator-validate-deployment/artifacts/001__gpu-operator__must-gather/004__gpu_operator__capture_deployment_state/all_gpu_ds.list
only two operator labels are enabled at the end of the test:
```
NAME                                READY   STATUS    RESTARTS   AGE    IP           NODE                                        NOMINATED NODE   READINESS GATES
nvidia-driver-daemonset-ln9ts       1/1     Running   0          21m    10.130.2.6   ip-10-0-138-82.us-west-2.compute.internal   <none>           <none>
nvidia-node-status-exporter-p5qhl   1/1     Running   1          109m   10.130.2.7   ip-10-0-138-82.us-west-2.compute.internal   <none>           <none>
```

**Comment by kpouget** [comment]
and `upgrade-gpu-operator-e2e-upgrade-170` failed because https://github.com/openshift-psap/ci-artifacts/pull/227 wasn't merged yet

**Comment by omertuc** [comment]
> @omertuc something wrong wrong with the labels with `upgrade-gpu-operator-e2e-upgrade`:
> 
> ```
> NAME                                 DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                                      AGE
> gpu-feature-discovery                0         0         0       0            0           nvidia.com/gpu.deploy.gpu-feature-discovery=true   109m
> nvidia-container-toolkit-daemonset   0         0         0       0            0           nvidia.com/gpu.deploy.container-toolkit=true       109m
> nvidia-dcgm                          0         0         0       0            0           nvidia.com/gpu.deploy.dcgm=true                    109m
> nvidia-dcgm-exporter                 0         0         0       0            0           nvidia.com/gpu.deploy.dcgm-exporter=true           109m
> nvidia-device-plugin-daemonset       0         0         0       0            0           nvidia.com/gpu.deploy.device-plugin=true           109m
> nvidia-driver-daemonset              1         1         1       1            1           nvidia.com/gpu.deploy.driver=true                  109m
> nvidia-mig-manager                   0         0         0       0            0           nvidia.com/gpu.deploy.mig-manager=true             109m
> nvidia-node-status-exporter          1         1         1       1            1           nvidia.com/gpu.deploy.node-status-exporter=true    109m
> nvidia-operator-validator            0         0         0       0            0           nvidia.com/gpu.deploy.operator-validator=true      109m
> ```
> 
> [gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/20629/rehearse-20629-periodic-ci-openshift-psap-ci-artifacts-release-4.8-upgrade-gpu-operator-e2e-upgrade/1420123700790824960/artifacts/gpu-operator-e2e-upgrade/2-postupgrade-gpu-operator-validate-deployment/artifacts/001__gpu-operator__must-gather/004__gpu_operator__capture_deployment_state/all_gpu_ds.list](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/20629/rehearse-20629-periodic-ci-openshift-psap-ci-artifacts-release-4.8-upgrade-gpu-operator-e2e-upgrade/1420123700790824960/artifacts/gpu-operator-e2e-upgrade/2-postupgrade-gpu-operator-validate-deployment/artifacts/001__gpu-operator__must-gather/004__gpu_operator__capture_deployment_state/all_gpu_ds.list)
> only two operator labels are enabled at the end of the test:
> 
> ```
> NAME                                READY   STATUS    RESTARTS   AGE    IP           NODE                                        NOMINATED NODE   READINESS GATES
> nvidia-driver-daemonset-ln9ts       1/1     Running   0          21m    10.130.2.6   ip-10-0-138-82.us-west-2.compute.internal   <none>           <none>
> nvidia-node-status-exporter-p5qhl   1/1     Running   1          109m   10.130.2.7   ip-10-0-138-82.us-west-2.compute.internal   <none>           <none>
> ```

yep, noticed that. Couldn't figure out why. It has to do with the operator state machine? no? Since "desired" is 0

**Comment by kpouget** [comment]
no, `desired` must be correct (most likely at least), so no node must match `nvidia.com/gpu.deploy.gpu-feature-discovery=true`.
I guess the label is `nvidia.com/gpu.deploy.gpu-feature-discovery=false` because the label has been disabled by the GPU Operator upgrade manager, and not re-enabled

**Comment by kpouget** [comment]
```
                    "nvidia.com/gpu.deploy.container-toolkit": "false",
                    "nvidia.com/gpu.deploy.dcgm": "false",
                    "nvidia.com/gpu.deploy.dcgm-exporter": "false",
                    "nvidia.com/gpu.deploy.device-plugin": "false",
                    "nvidia.com/gpu.deploy.driver": "true",
                    "nvidia.com/gpu.deploy.gpu-feature-discovery": "false",
                    "nvidia.com/gpu.deploy.node-status-exporter": "true",
                    "nvidia.com/gpu.deploy.operator-validator": "false",
                    "nvidia.com/gpu.present": "true",
```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/20629/rehearse-20629-periodic-ci-openshift-psap-ci-artifacts-release-4.8-upgrade-gpu-operator-e2e-upgrade/1420123700790824960/artifacts/gpu-operator-e2e-upgrade/gather-extra/artifacts/nodes.json

**Comment by kpouget** [comment]
> INFO[2021-07-29T13:43:49Z] Step
gpu-operator-e2e-upgrade-170-ipi-install-install failed after 37m40s.

:(

/test pj-rehearse

**Comment by omertuc** [comment]
@kpouget let's merge this?

**Comment by kpouget** [comment]
@omertuc I think the PR entered a test-retry loop :# :# :#

**Pull request closed without merging**
