### PR TITLE
Add 4.11 QE job for testing

### PR DESCRIPTION
**Pull request by sunzhaohua2**
@jhou1 @miyadav @huali9 add this 4.11 job so that we can add our CAPI and aws IMDSv2 workflow. PTAL.

### CODE REVIEW

**Comment by jianlinliu** [comment]
@zhaozhanqi  do you mind to change the exiting ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse.yaml file to ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.10.yaml

**Comment by sunzhaohua2** [comment]
> 

sure, will update

**Comment by jianlinliu** [comment]
periodic-ci-openshift-verification-tests-master-installer-rehearse-4.10-installer-rehearse-azuremag failure is a known issue, because QE's mag subscription is disabled.

periodic-ci-openshift-verification-tests-master-installer-rehearse-4.10-installer-rehearse-gcp-ipi-proxy sounds like a flake.

periodic-ci-openshift-verification-tests-master-installer-rehearse-4.10-installer-rehearse-vsphere-discon sounds like a flake too.

periodic-ci-openshift-verification-tests-master-installer-rehearse-4.10-installer-rehearse-aws-usgov-qe @yunjiang29  do you think it is a flake or some other issue?

**Comment by yunjiang29** [comment]
> periodic-ci-openshift-verification-tests-master-installer-rehearse-4.10-installer-rehearse-azuremag failure is a known issue, because QE's mag subscription is disabled.
> 
> periodic-ci-openshift-verification-tests-master-installer-rehearse-4.10-installer-rehearse-gcp-ipi-proxy sounds like a flake.
> 
> periodic-ci-openshift-verification-tests-master-installer-rehearse-4.10-installer-rehearse-vsphere-discon sounds like a flake, cc @jinyunma to be noticed.
> 
> periodic-ci-openshift-verification-tests-master-installer-rehearse-4.10-installer-rehearse-aws-usgov-qe @yunjiang29 do you think it is a flake or some other issue?

@jianlinliu I think it's a flake, the latest test this morning in my PR get passed:

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/29050/rehearse-29050-periodic-ci-openshift-verification-tests-master-installer-rehearse-installer-rehearse-aws-usgov-qe/1536162658032553984

**Comment by jianlinliu** [comment]
based on that, I will approve this PR.

**Pull request merged**
