### PR TITLE
NOJIRA: fix: adding in the pipeline lca

### PR DESCRIPTION
**Pull request by jeff-roche**

### CODE REVIEW

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-kni-lifecycle-agent-main-nightly-4.16-image-based-upgrade-e2e-parallel-conformance

**Comment by jeff-roche** [comment]
/pj-rehearse periodic-ci-openshift-kni-lifecycle-agent-main-nightly-4.16-image-based-upgrade-e2e-parallel-conformance

**Review by javipolo — APPROVED** [review]

**Pull request merged**
