### PR TITLE
4.16 lp interop configs add firewatch success rule

### PR DESCRIPTION
**Pull request by smatula**

### CODE REVIEW

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-pit-7.4.x-eap-ocp4.16-lp-interop-eap-74-interop-aws periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.16-lp-interop-jaeger-interop-aws

**Review by calebevans — APPROVED** [review]
/lgtm

**Review by Simranpal — APPROVED** [review]
/lgtm

**Pull request merged**
