### PR TITLE
Add new 4.13 workloads

### PR DESCRIPTION
**Pull request by svetsa-rh**
Add new 4.13 nightly tests.
4.12 test is being moved to separate file as part of https://github.com/openshift/release/pull/39968

### CODE REVIEW

**Comment by svetsa-rh** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.13-nightly-cluster-density-v2-images pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.13-nightly-cluster-density-v2-ocp-qe-perfscale-ci-tests-rosa-cluster-density-v2 pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.13-nightly-images periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.13-nightly-ocp-qe-perfscale-ci-tests-rosa-cluster-density periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.13-nightly-ocp-qe-perfscale-ci-tests-rosa-node-density periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.13-nightly-ocp-qe-perfscale-ci-tests-rosa-cluster-density-v2

**Comment by svetsa-rh** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.13-nightly-ocp-qe-perfscale-ci-tests-rosa-cluster-density-v2 periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.13-nightly-ocp-qe-perfscale-ci-tests-rosa-cluster-density periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.13-nightly-ocp-qe-perfscale-ci-tests-rosa-node-density

**Comment by svetsa-rh** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.13-nightly-ocp-qe-perfscale-ci-tests-rosa-cluster-density

**Comment by svetsa-rh** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.13-nightly-ocp-qe-perfscale-ci-tests-rosa-cluster-density-v2

**Comment by svetsa-rh** [comment]
@paigerube14 Can you ptal?

**Review by paigerube14 — APPROVED** [review]
/lgtm

**Comment by paigerube14** [comment]
It would be good if we got a second reviewer on these. @qiliRedHat @jtaleric PTAL thanks

**Pull request merged**
