### PR TITLE
create logging jobs for logging 5.0 release

### PR DESCRIPTION
**Pull request by jcantrill**
This PR establishes CI jobs for OpenShift Logging 5.0 release aka. OCP 4.7

https://issues.redhat.com/browse/LOG-1087

### CODE REVIEW

**Comment by jcantrill** [comment]
@ewolinetz  @alanconway 5.0 jobs which i removed the tag_specification in favor of releases which will
 * run PRs an the latest stable payload
 * remove? payload building from logging PRs (faster?)

**Comment by jcantrill** [comment]
> @jcantrill do we still want to be using the "4.7" branch and "ocp" namespace for these? or can we move these away from that older process

I'm not sure I understand your question; can you point to a specific portion of the config?  The jobs need to point to 4.7 ocp as the base upon which we test. I've updated the promotion section to promote images to a logging specific ns

**Comment by jcantrill** [comment]
@stevekuznetsov can you review `core-services/prow/02_config` for approval?

**Review by stevekuznetsov — APPROVED** [review]

**Pull request merged**
