### PR TITLE
Fixing kube-reporting-metering-operator-master.yaml to use dockerfile from ocp-build-data

### PR DESCRIPTION
**Pull request by alvaroaleman**

### CODE REVIEW

**Comment by jupierce** [comment]
Blocked by https://github.com/openshift/release/pull/10885

**Comment by timflannagan1** [comment]
It looks like images are failing for both the metering and reporting operators.

The reporting-operator looks to be the lower hanging fruit and fails when pulling the golang base image:
```
Replaced Dockerfile FROM image openshift/ose-base:latest
Pulling image docker-registry.default.svc:5000/ci-op-m50v7rbz/pipeline@sha256:8bfb14d668dc23547ec4ed1a8e06732e23512aa6c44a3b315068b29138d1e201 ...
Pulling image openshift/golang-builder:1.13 ...
error: build error: failed to pull image: repository docker.io/openshift/golang-builder not found: does not exist or no pull access
2020/08/25 01:08:51 Build metering-ansible-operator failed, printing logs:
Pulling image "docker-registry.default.svc:5000/ci-op-m50v7rbz/pipeline@sha256:166f0d3b03736c52fe2445adfe71c5fc4edaa16eb346c93ba12e7aad2c5a8dea" ...
Replaced Dockerfile FROM image openshift/ose-ansible-operator:4.6
```

I can update the Dockerfile.reporting-operator.rhel to use the registry.svc.ci.openshift.org registry instead of the `openshift/golang-builder:1.13` it's currently configured to use (and likewise for the `openshift/ose-base` base image) and I imagine that error will go away. @jupierce have you seen this error yet?

**Comment by jupierce** [comment]
@timflannagan1 It looks like the issue you reported is behind us. Now: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/10852/rehearse-10852-pull-ci-kube-reporting-metering-operator-master-images/1301281877981663232/build-log.txt
```
--> ENV HOME=/opt/ansible
--> ENV HELM_CHART_PATH=${HOME}/charts/openshift-metering
--> COPY images/metering-ansible-operator/roles/ ${HOME}/roles/
--> COPY images/metering-ansible-operator/watches.yaml ${HOME}/watches.yaml
--> COPY images/metering-ansible-operator/scripts ${HOME}/scripts
2020/09/02 22:17:48 Build metering-ansible-operator-registry succeeded after 1m45s
2020/09/02 22:17:48 Tagging metering-ansible-operator-registry into stable
2020/09/02 22:17:49 No custom metadata found and prow metadata already exists. Not updating the metadata.
2020/09/02 22:17:49 Ran for 5m10s
error: some steps failed:
  * could not run steps: step metering-ansible-operator failed: could not wait for build: the build metering-ansible-operator failed after 1m40s with reason DockerBuildFailed: Docker build strategy has failed.

--> ENV HELM_CHART_PATH=${HOME}/charts/openshift-metering
--> COPY images/metering-ansible-operator/roles/ ${HOME}/roles/
--> COPY images/metering-ansible-operator/watches.yaml ${HOME}/watches.yaml
--> COPY images/metering-ansible-operator/scripts ${HOME}/scripts
error: build error: stat /tmp/build/inputs/images/metering-ansible-operator/scripts: no such file or directory
```

**Comment by jupierce** [comment]
@timflannagan1 It does look in the `scripts` directory is missing upstream: https://github.com/kube-reporting/metering-operator/tree/master/images/metering-ansible-operator

**Comment by timflannagan1** [comment]
@jupierce I'm not entirely sure how I missed that during the PR review. Anyways opened a PR for fixing that upstream: https://github.com/kube-reporting/metering-operator/pull/1393

**Pull request merged**
