### PR TITLE
IBU upgrade disable rollback

### PR DESCRIPTION
**Pull request by omertuc**
Waiting on https://github.com/rh-ecosystem-edge/ib-orchestrate-vm/pull/61 first

See linked PR for motivation

### CODE REVIEW

**Review by javipolo — APPROVED** [review]

**Comment by omertuc** [comment]
/pj-rehearse pull-ci-openshift-kni-lifecycle-agent-main-ibu-e2e-flow

**Comment by omertuc** [comment]
/pj-rehearse pull-ci-openshift-kni-lifecycle-agent-main-ibu-e2e-flow

**Comment by omertuc** [comment]
@jeff-roche

**Pull request merged**
