### PR TITLE
Include optional presubmits Kuryr jobs to origin

### PR DESCRIPTION
**Pull request by MaysaMacedo**

### CODE REVIEW

**Comment by pierreprinetti** [comment]
You probably want to add the presubmit to `master` to be able to run the test on the development branch

**Comment by MaysaMacedo** [comment]
> You probably want to add the presubmit to `master` (ci-operator/config/openshift/origin/openshift-origin-master.yaml) to be able to run the test on the development branch

Done. Thanks, @pierreprinetti

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
