### PR TITLE
SPLAT-1639: vSphere - Reorganize vault secrets and start migrating to new CI vsphere env

### PR DESCRIPTION
**Pull request by jcpowermac**
They are a mess, this is the start to fixing them...
This is a transition to consolidating the vault collection to one - currently there two top level and nine lower level.
The previous mounts will be removed as we migrate from those vSphere environments and are no longer needed.
Existing key/values have been added, with one modification which is to add vcenter.ci and remove v8c-2-vcenter.ocp2.dev.cluster.com

### CODE REVIEW

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.16-altinfra-e2e-vsphere-capi-ovn

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.16-altinfra-e2e-vsphere-capi-static-ovn

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.16-altinfra-e2e-vsphere-capi-ovn

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.16-altinfra-e2e-vsphere-capi-ovn

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-stable-vsphere-ipi-zones-f14

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-stable-vsphere-ipi-proxy-fips-f14

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-stable-vsphere-ipi-disc-f14

**Comment by WenXinWei** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-vsphere-ipi-zones-multisubnets-external-lb-f28

**Comment by mhanss** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-vsphere-agent-dualstack-compact-f14

**Comment by eliorerz** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted

**Comment by eliorerz** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-kube-api

**Review by eliorerz — APPROVED** [review]

**Pull request merged**
