### PR TITLE
Regenerate presubmits to pick up ci-tools#2136

### PR DESCRIPTION
**Pull request by petr-muller**

### CODE REVIEW

**Comment by 2uasimojo** [comment]
ok for hive. I'm not sure why we need the second form, e.g.

```diff
@@ -122,7 +124,8 @@ presubmits:
   - agent: kubernetes
     always_run: false
     branches:
-    - master
+    - ^master$
+    - ^master-
     cluster: build01
     context: ci/prow/e2e-aws-manual-oidc
     decorate: true
```
IIUC `^master-` will also match branches like `master-foo`, which it didn't before. But at least in our case, since we don't have branches like that, it's not a thing.

**Comment by petr-muller** [comment]
> IIUC `^master-` will also match branches like `master-foo`, which it didn't before. But at least in our case, since we don't have branches like that, it's not a thing.

It actually *did* match such branches before, see https://docs.ci.openshift.org/docs/how-tos/contributing-openshift-release/#feature-branches. The problem with that is that without a separator, you get false matches by e.g. `release-4.10` being a "feature 
branch" of `relase-4.1`. Requiring the separator will help with that.

**Pull request merged**
