### PR TITLE
Remove periodic nmstate jobs

### PR DESCRIPTION
**Pull request by derekhiggins**
These are running with a equinix-ocp-metal cluster_profile, which
is intended to be used to provided baremetal specifically for ipi
testing. We are currently over capacity and under pressure to reduce
usage.

These periodic jobs alone represent about 14% of our usage so we need
to remove them. I've left the presubmit jobs for now to allow time for
an alternative to be found but eventualy we'll also need to remove these.

### CODE REVIEW

**Comment by derekhiggins** [comment]
pinging OWNERS @creydr @cybertron @phoracek @qinqon @rhrazdil @yboaron

Can we remove these jobs (and eventually the presubmit jobs) the equinix profile is intended for ipi development and is way over subscribed, can you use  a aws cluster instead to test your artifacts?

**Review by cybertron — CHANGES_REQUESTED** [review]
These need to be on baremetal because that's the only supported platform for kubernetes-nmstate right now. It's possible we could move them somewhere else if/when we have ci running on another platform, but right now we don't.

As a compromise, could we just remove the e2e-operator tests from periodic? The handler tests break because of external changes on a semi-regular basis so periodic jobs are kind of important for them, but the operator tests shouldn't be as exposed to that sort of thing.

I would also like to get @creydr 's thoughts, but he's out on PTO for the next two weeks. :-/

**Comment by cybertron** [comment]
> I'll update the PR to remove the operator tests from periodic while we figure out what to do about the other, I'm told they'll need to go soon as we aiming to drastically reduce the usage on this account.

Okay, I guess if we're told they absolutely have to go then as long as whoever is making that decision is aware of the problems it will likely cause then we'll have to live with it.

I do wonder how 4 jobs running once a day could possibly be that big a resource user though. I'm pretty sure I trigger more metal jobs on patches than that by myself on an average day. :-/

/lgtm

**Comment by cybertron** [comment]
Oh, I have approver rights for this too.

/approve

**Comment by derekhiggins** [comment]
> I do wonder how 4 jobs running once a day could possibly be that big a resource user though. I'm pretty sure I trigger more metal jobs on patches than that by myself on an average day. :-/

Just to provide some details here, its more then just 4 jobs, there was 36 different periodic jobs on this repository (now 18), some daily and some weekly. Over all of August the periodic jobs (excluding the jobs on PRs) represented 14% (1157/8257) of the overall host requested on our equinix account.

**Pull request merged**
