### PR TITLE
Fix mto operator deploy issue and add more debug info

### PR DESCRIPTION
**Pull request by lwan-wanglin**
the pr fix below issue:
-  fix kustomization yaml file patches issue, the previous one will casue pathes overide
- Add more debug info for operator deploy

### CODE REVIEW

**Comment by lwan-wanglin** [comment]
/pj-rehearse pull-ci-openshift-multiarch-tuning-operator-main-ocp416-e2e-aws-ovn-mto-origin-post periodic-ci-openshift-multiarch-tuning-operator-main-ocp418-e2e-aws-ovn-proxy-mto-origin pull-ci-openshift-multiarch-tuning-operator-main-ocp417-e2e-aws-ovn-mto-origin-post pull-ci-openshift-multiarch-tuning-operator-main-ocp418-e2e-aws-ovn-mto-origin-post

**Comment by lwan-wanglin** [comment]
/pj-rehearse pull-ci-openshift-multiarch-tuning-operator-main-ocp416-e2e-aws-ovn-mto-origin-post periodic-ci-openshift-multiarch-tuning-operator-main-ocp418-e2e-aws-ovn-proxy-mto-origin pull-ci-openshift-multiarch-tuning-operator-main-ocp417-e2e-aws-ovn-mto-origin-post pull-ci-openshift-multiarch-tuning-operator-main-ocp418-e2e-aws-ovn-mto-origin-post

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-tuning-operator-main-ocp418-e2e-aws-ovn-proxy-mto-origin

**Comment by aleskandro** [comment]
Hi Lin, can we print the same info as we do for in the repo's deploy-and-e2e script?

**Review by aleskandro — COMMENTED** [review]
/lgtm

**Pull request merged**
