### PR TITLE
Setup oc repo

### PR DESCRIPTION
**Pull request by tnozicka**
/cc @sttts @deads2k

### CODE REVIEW

**Comment by droslean** [comment]
/lgtm
/hold

Hold, if you might want to wait for the rehearsals.

**Comment by deads2k** [comment]
terraform error.  It will only block merges to oc if it is broken.  I move to merge over red.

**Comment by tnozicka** [comment]
@droslean thanks

important ones passed, e2e ar acceptible flakes
/hold cancel

**Pull request merged**
