### PR TITLE
Update Hypershift KubeVirt 4.16 periodics

### PR DESCRIPTION
**Pull request by davidvossel**
This PR transitions the 4.16 periodic to use the baremetalds infra as well as reporting 4.16 periodic failures to slack.

### CODE REVIEW

**Comment by davidvossel** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-kubevirt-baremetalds-conformance

**Review by qinqon — APPROVED** [review]
/lgtm
/approve

**Comment by qinqon** [comment]
Ingress issue 
```
NAME                                       VERSION                         AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
console                                                                                                                 
csi-snapshot-controller                    4.16.0-0.ci-2024-02-01-031542   True        False         False      54m     
dns                                        4.16.0-0.ci-2024-02-01-031542   False       Unknown       False      54m     DNS "default" is unavailable.
image-registry                                                             False       True          True       52m     Available: The deployment does not have available replicas...
ingress                                                                    False       True          True       54m     The "default" ingress controller reports Available=False: IngressControllerUnavailable: One or more status conditions indicate unavailable: DeploymentAvailable=False (DeploymentUnavailable: The deployment has Available status condition set to False (reason: MinimumReplicasUnavailable) with message: Deployment does not have minimum availability.)
insights                                                                                                                
kube-apiserver                             4.16.0-0.ci-2024-02-01-031542   True        False         False      54m     
kube-controller-manager                    4.16.0-0.ci-2024-02-01-031542   True        False         False      54m     
kube-scheduler                             4.16.0-0.ci-2024-02-01-031542   True        False         False      54m     
kube-storage-version-migrator                                                                                           
monitoring                                                                                                              
network                                                                                              True               Failed to probe MTU: timed out getting result from MTU prober context deadline exceeded
node-tuning                                4.16.0-0.ci-2024-02-01-031542   True        True          False      50m     Waiting for 2/2 Profiles to be applied
openshift-apiserver                        4.16.0-0.ci-2024-02-01-031542   True        False         False      54m     
openshift-controller-manager               4.16.0-0.ci-2024-02-01-031542   True        False         False      54m     
openshift-samples                                                                                                       
operator-lifecycle-manager                 4.16.0-0.ci-2024-02-01-031542   True        False         False      54m     
operator-lifecycle-manager-catalog         4.16.0-0.ci-2024-02-01-031542   True        False         False      54m     
operator-lifecycle-manager-packageserver   4.16.0-0.ci-2024-02-01-031542   True        False         False      54m     
service-ca                                                                                                              
storage                                    4.16.0-0.ci-2024-02-01-031542   True        False         False      54m     
```

**Comment by qinqon** [comment]
Fix is in place

/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-kubevirt-baremetalds-conformance

**Comment by davidvossel** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-kubevirt-baremetalds-conformance

**Comment by qinqon** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-kubevirt-baremetalds-conformance

**Comment by davidvossel** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-kubevirt-baremetalds-conformance

**Comment by davidvossel** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-kubevirt-baremetalds-conformance

**Pull request merged**
