### PR TITLE
OCPQE-6636: Refactor cucushift e2e tests (continue-4)

### PR DESCRIPTION
**Pull request by liangxia**
Previously we add new step definitions for each cucushift e2e tests, e.g, aws-ipi, aws-upi, gcp-ipi, ...
We'd like to refactor those step definitions so those cucushift e2e tests share the same step definition, to easier future maintenance. And we refactored the steps in #23185, this is the follow up to update existing jobs.

/cc @JianLi-RH @dis016 @pruan-rht @jhou1

### CODE REVIEW

**Comment by liangxia** [comment]
The failures are on specific test cases, not related to the changes (job level refactor) in this PR.

/assign @ingvagabund

**Review by droslean — APPROVED** [review]

**Pull request merged**
