### PR TITLE
MGMT-16332: [assisted-installer] set lvms test to compact cluster

### PR DESCRIPTION
**Pull request by eifrach**
[assisted-installer] - replacing LVM SNO test with LVMS on compact cluster

### CODE REVIEW

**Comment by eifrach** [comment]
/pj-rehearse  pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted-lvm

**Comment by eifrach** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted-lvm

**Comment by eifrach** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted-lvm

**Comment by eifrach** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-lvm-periodic
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted-lvm

**Review by gamli75 — APPROVED** [review]

**Pull request merged**
