### PR TITLE
Add azure-manual-oidc tests to CAPI-azure

### PR DESCRIPTION
**Pull request by dlom**
/assign @jstuever 
/cc @2uasimojo

### CODE REVIEW

**Comment by jstuever** [comment]
Does this need `FEATURE_SET: TechPreviewNoUpgrade` ?

**Comment by jstuever** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-azure-release-4.16-e2e-azure-manual-oidc
/pj-rehearse pull-ci-openshift-cluster-api-provider-azure-release-4.14-e2e-azure-manual-oidc

**Comment by dlom** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-azure-release-4.16-e2e-azure-manual-oidc

**Comment by dlom** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-azure-release-4.16-e2e-azure-manual-oidc
/pj-rehearse pull-ci-openshift-cluster-api-provider-azure-release-4.15-e2e-azure-manual-oidc
/pj-rehearse pull-ci-openshift-cluster-api-provider-azure-release-4.14-e2e-azure-manual-oidc

**Comment by dlom** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-azure-release-4.16-e2e-azure-manual-oidc
/pj-rehearse pull-ci-openshift-cluster-api-provider-azure-release-4.15-e2e-azure-manual-oidc
/pj-rehearse pull-ci-openshift-cluster-api-provider-azure-release-4.14-e2e-azure-manual-oidc

**Comment by dlom** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-azure-release-4.16-e2e-azure-manual-oidc
/pj-rehearse pull-ci-openshift-cluster-api-provider-azure-release-4.15-e2e-azure-manual-oidc
/pj-rehearse pull-ci-openshift-cluster-api-provider-azure-release-4.14-e2e-azure-manual-oidc

**Comment by dlom** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-azure-release-4.15-e2e-azure-manual-oidc

**Comment by dlom** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-azure-release-4.14-e2e-azure-manual-oidc

**Comment by dlom** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-azure-release-4.14-e2e-azure-manual-oidc

**Comment by dlom** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-azure-release-4.14-e2e-azure-manual-oidc

**Review by jstuever — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
