### PR TITLE
Add aws to all Knative job names that launch clusters

### PR DESCRIPTION
**Pull request by bbrowning**
This allows better reporting on the number of concurrent jobs
consuming AWS resources.

### CODE REVIEW

**Comment by bbrowning** [comment]
/assign @alanfx @mgencur @markusthoemmes @matzew @navidshaikh 

Adding QE and Knative team leads to verify I didn't botch any of their bits and to raise awareness that as we create jobs for future release branches they need the same "e2e-aws" instead of "e2e" naming pattern for proper reporting.

**Comment by alanfx** [comment]
Oy, I am in the midst of changing these names as well to account for using `4.1` vs `4.2` in this PR https://github.com/openshift/release/pull/4217

**Comment by bbrowning** [comment]
Fun! I have no strong preference if this should wait until after your PR lands or whether you want to incorporate adding the aws names into our jobs as part of your other PR. I only created this PR at the request of @smarterclayton to ensure that all jobs that launch clusters on AWS have 'aws' in their name.

**Comment by alanfx** [comment]
Well, I think you win, since your PR has passed all the checks already! Mine is still not working, so I'll adjust to your PR.

**Pull request merged**
