### PR TITLE
skip sig-storage tests on ppc64le until overrides return

### PR DESCRIPTION
**Pull request by clnperez**
Since https://github.com/openshift/origin/pull/24887 was merged, we've
lost some image overrides. Working on this, but in the meantime trying
to get some green 4.7 CI runs.

Signed-off-by: Christy Norman <christy@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by clnperez** [comment]
unable to get the lease on that last one. bad gateway error.
/retest

**Comment by clnperez** [comment]
there was a short outage with boskos so not worried about that bad gateway failure.

**Comment by clnperez** [comment]
After having gone through the tests that failed, there were a couple of docker rate limiting failures, several that hit registry timeouts, and a couple that are known to be flaky. And one that is being fixed by https://github.com/openshift/release/pull/14307. Is it possible to get this merged so we see less noise with our CI? With so many variables I don't foresee getting a green on this particular PR.

**Comment by clnperez** [comment]
I think the sshd tunnel went down on that one. :/

/retest

**Comment by petr-muller** [comment]
/approve

Someone who is able to eyeball the list of tests to be skipped (=not me) should `/lgtm` this.

**Comment by r4f4** [comment]
The skip list is fine and it'll be revised in https://github.com/openshift/release/pull/14346 which contains a fix for the multi-arch image overrides.

/lgtm

**Pull request merged**
