### PR TITLE
Determinize openshift-release-master-postsubmits so new cluster-init automation can generate relevant diffs

### PR DESCRIPTION
**Pull request by smg247**
This file represents the changes that jobconfig.WriteToDir makes when updating the postsubmits.
/cc @openshift/test-platform

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
How did you generate this?

**Comment by smg247** [comment]
> How did you generate this?

@stevekuznetsov I ran my cluster-init code (so running through `jobconfig.WriteToDir`) with a new `build03` cluster, and then I manually deleted the actual new job for `build03` to be left with the resulting diff.

**Pull request merged**
