### PR TITLE
Remove disabled cluster and move jobs

### PR DESCRIPTION
**Pull request by deepsm007**
/cc @openshift/test-platform 
https://redhat-internal.slack.com/archives/CBN38N3MW/p1724840877923609

### CODE REVIEW

**Comment by deepsm007** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-4.17-upgrade-from-stable-4.1-aws-ipi-f28

**Comment by shellyyang1989** [comment]
cc @JianLi-RH @jiajliu @jianlinliu @evakhoni @dis016 for awareness

**Comment by deepsm007** [comment]
https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-4.17-upgrade-from-stable-4.1-aws-ipi-f28/1828790146770669568 run looks good on build03

**Comment by deepsm007** [comment]
/pj-rehearse abort 

The job is stuck ` exec /tools/entrypoint: argument list too long`, I triggered a manual run on build03 which looks good

**Pull request merged**
