### PR TITLE
Use registry.k8s.io instead of k8s.gcr.io

### PR DESCRIPTION
**Pull request by soltysh**
Ref https://groups.google.com/a/kubernetes.io/g/dev/c/kgWu5q6h8fs/m/ANmnNAatAQAJ

/assign @davidvossel

### CODE REVIEW

**Comment by nunnatsa** [comment]
Could you please also change `cluster_profile: gcp` to `cluster_profile: gcp-virtualization` and then run `make jobs`?

**Comment by soltysh** [comment]
@nunnatsa done, ptal

**Comment by soltysh** [comment]
@nunnatsa ptal, let's try to land this bit

**Pull request closed without merging**
