### PR TITLE
PLNSRVCE-658: pivot off of pre-kcp infra-deps to repo 'dev' flow until kcp transition complete

### PR DESCRIPTION
**Pull request by gabemontero**
Also
- remove now unneeded pruning job (with throttling form of pruning) 
- make jvm-build-service-e2e from e2e-tests optional, require explicit launch, until kcp transition complete
- remove periodic (may re-add after kcp transition is complete)

A separate PR will deal with the builder images and the fact they were moved from the jvm-build-service repo.

### CODE REVIEW

**Comment by gabemontero** [comment]
/assign @psturc 
/assign @stuartwdouglas 

@dwalluck FYI

**Comment by gabemontero** [comment]
@stuartwdouglas - if you want to join the openshift github org and be able to approve/lgtm these openshift/ci PRs, I believe the current process is documented at https://source.redhat.com/groups/public/atomicopenshift/atomicopenshift_wiki/openshift_onboarding_checklist_for_github

**Comment by gabemontero** [comment]
Need some more massaging back on the jvm-build-service side ... some of the overlay objs did not have the namespace set, and so it defaulted to the current namespace in the CI cluster vs. the namespace we want on the test cluster:

```
 Executing patch-yaml.sh
jvm build service golang operator image:
registry.build01.ci.openshift.org/ci-op-fc8sd30z/pipeline@sha256:393d52f2813d3e1ecd3026e1f41a8f9b11963b34c95e655d0b81d430a24cf5ba
jvm build service jvm cache image:
registry.build01.ci.openshift.org/ci-op-fc8sd30z/pipeline@sha256:307af3d52230677c7b1757b19517f4dd82c022476dafb2e95b06335029ef6718
jvm build service jvm sidecar image:
registry.build01.ci.openshift.org/ci-op-fc8sd30z/pipeline@sha256:0dca5d2519b8be7096eb8303c88ae26c1746024f587d1f565a133739dee5bdac
jvm build service jvm analyzer image:
registry.build01.ci.openshift.org/ci-op-fc8sd30z/pipeline@sha256:ad34458ed95f04a0e237f679feb66835617eb6b83be42a20cb53cdf869606137
jvm build service jvm reqprocessor image:
registry.build01.ci.openshift.org/ci-op-fc8sd30z/pipeline@sha256:0fce22da3fe7acb183d508469a290b129261389745d64a6b3052fa0b879ac4fd
jvm build service JDK8 builder image:
registry.build01.ci.openshift.org/ci-op-fc8sd30z/pipeline@sha256:e87d78c835fc2c64c4bd6ddd7441f9c8339892ae1e815e5927fd797269badbbf
jvm build service JDK11 builder image:
registry.build01.ci.openshift.org/ci-op-fc8sd30z/pipeline@sha256:49c6a2fd1d81eacbef4f6f090bf0430bf1cf45c2d7cc47e713a41a5289ec3cc8
jvm build service JDK17 builder image:
registry.build01.ci.openshift.org/ci-op-fc8sd30z/pipeline@sha256:58af3f4dab6cb4fb9304da3c22f365d2bbfd0c488db96e6a364d7f690cf28434
customresourcedefinition.apiextensions.k8s.io/artifactbuilds.jvmbuildservice.io created
customresourcedefinition.apiextensions.k8s.io/dependencybuilds.jvmbuildservice.io created
customresourcedefinition.apiextensions.k8s.io/tektonwrappers.jvmbuildservice.io created
serviceaccount/hacbs-jvm-operator created
Warning: resource serviceaccounts/pipeline is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
serviceaccount/pipeline configured
Warning: resource serviceaccounts/pipeline is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
serviceaccount/pipeline configured
clusterrole.rbac.authorization.k8s.io/hacbs-jvm-cache created
clusterrole.rbac.authorization.k8s.io/hacbs-jvm-operator created
clusterrole.rbac.authorization.k8s.io/hacbs-jvm-operator-view created
clusterrole.rbac.authorization.k8s.io/pipeline created
clusterrolebinding.rbac.authorization.k8s.io/hacbs-jvm-operator created
clusterrolebinding.rbac.authorization.k8s.io/pipeline created
configmap/jvm-build-system-config created
deployment.apps/hacbs-jvm-operator created
Error from server (NotFound): error when creating "deploy/overlays/development": namespaces "ci-op-fc8sd30z" not found
Error from server (NotFound): error when creating "deploy/overlays/development": namespaces "ci-op-fc8sd30z" not found
Error from server (NotFound): error when creating "deploy/overlays/development": namespaces "ci-op-fc8sd30z" not found
Error from server (NotFound): error when creating "deploy/overlays/development": namespaces "ci-op-fc8sd30z" not found
Error from server (NotFound): error when creating "deploy/overlays/development": namespaces "ci-op-fc8sd30z" not found
```

**Comment by gabemontero** [comment]
also got to handle the correct settings in CI for the `QUAY_USERNAME` and `QUAY_TOKEN` for the `jvm-build-config` configmap and the `jvm-build-secret` secret that we manually set in our dev flow

**Comment by gabemontero** [comment]
> also got to handle the correct settings in CI for the `QUAY_USERNAME` and `QUAY_TOKEN` for the `jvm-build-config` configmap and the `jvm-build-secret` secret that we manually set in our dev flow

actually i don't see the e2e's using container storage yet, so I can maybe punt on that ^^ for now ... we'll see

**Comment by stuartwdouglas** [comment]
yea, I am still working on the container image storage, as you saw there is an auth failure pushing to the registry.

**Comment by gabemontero** [comment]
still hitting namespace issues with the maven and gradle tasks in the last run

going back to the repo and work on some form of the change I proposed in https://github.com/redhat-appstudio/jvm-build-service/pull/245#discussion_r966514294 based on @stuartwdouglas 's comment

i.e. a 'subset" of the current dev flow

**Comment by stuartwdouglas** [comment]
So https://github.com/redhat-appstudio/jvm-build-service/pull/230 might actually pass this time, which means that the container based config should work. 

I'm not sure how much that affects the issues you are seeing, but if it is related it might be worth waiting for that PR to go in.

**Comment by gabemontero** [comment]
> So [redhat-appstudio/jvm-build-service#230](https://github.com/redhat-appstudio/jvm-build-service/pull/230) might actually pass this time, which means that the container based config should work.
> 
> I'm not sure how much that affects the issues you are seeing, but if it is related it might be worth waiting for that PR to go in.

pretty sure they are unrelated to what I see changed in that ^^ PR but thanks

at most, I think I'll just need to make sure that CI properly seeds things so that the https://github.com/redhat-appstudio/jvm-build-service/pull/230/files#diff-323f42935c5af98a0b4152788343529680bef21786b46d6d23f8c23c6d785755R192 path is properly exercised

**Comment by gabemontero** [comment]
ok the standard in repo looks good at https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/32127/rehearse-32127-pull-ci-redhat-appstudio-jvm-build-service-main-jvm-build-service-in-repo-e2e/1568406723809513472

we'll see how the other 2 do for interest, but this is ready for lgtm @psturc @stuartwdouglas

**Comment by gabemontero** [comment]
CI log retrieval error in apicurio:
```
 INFO[2022-09-10T01:54:35Z] Running step jvm-build-service-in-repo-apicurio-e2e-jvm-build-service-in-repo-apicurio-e2e. 
WARN[2022-09-10T03:19:35Z] error: Unable to retrieve logs from failed pod container sidecar.  error=container "sidecar" in pod "jvm-build-service-in-repo-apicurio-e2e-jvm-build-service-in-repo-apicurio-e2e" is terminated
WARN[2022-09-10T03:19:35Z] error: Unable to retrieve logs from failed pod container test.  error=container "test" in pod "jvm-build-service-in-repo-apicurio-e2e-jvm-build-service-in-repo-apicurio-e2e" is terminated
INFO[2022-09-10T03:19:35Z] Step jvm-build-service-in-repo-apicurio-e2e-jvm-build-service-in-repo-apicurio-e2e failed after 1h25m0s. 
INFO[2022-09-10T03:19:35Z] Step phase test failed after 1h25m0s.        
```

but once this merges, we can track the logs live in our individual PRs if need be (can't do that with these rehearsals

the e2e-tests run failed on appstudio bootstrap:

```
Waiting for default project (and namespace) to exist: ......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:165","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 2h0m0s timeout","severity":"error","time":"2022-09-10T03:30:14Z"}
.........{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:255","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process did not exit before 15s grace period","severity":"error","time":"2022-09-10T03:30:29Z"}
{"component":"entrypoint","error":"process timed out","file":"k8s.io/test-infra/prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-09-10T03:30:29Z"}
error: failed to execute wrapped command: exit status 127 
```

but with this test we are making this optional / requiring invocation with pre-kcp frozen

so yeah still please lgtm @psturc .... @stuartwdouglas FYI

**Comment by gabemontero** [comment]
also my guess is the apicurio build problem I just highlighted in https://github.com/redhat-appstudio/jvm-build-service/pull/230#issuecomment-1242734979 is pervasive across all runs

**Comment by gabemontero** [comment]
Had a change of heart and have put the periodic back in, at least until we get told to remove it, or we start getting clean service registry builds and the hacbs stakeholders move on from checking our periodic's status page.

**Comment by gabemontero** [comment]
take that back ;-) 

without the full PR override, we pick up too much pre-kep intra-deployment settings which are no longer reasonably updated

`    util.go:129: cache and/or localstack not present in timely fashion`

re-deleting

**Comment by gabemontero** [comment]
the failure at https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/32127/rehearse-32127-pull-ci-redhat-appstudio-jvm-build-service-main-jvm-build-service-e2e/1569386771504959488 is not surprising, and per the change here, while we I do not delete it, this job will only run if a developer explicitly asks for it in their PR

**Comment by gabemontero** [comment]
we are hitting the need for https://github.com/openshift/ci-tools/pull/3005 announced in announce-testplatform earlier today in build-clusters

I am monitoring that PR

**Pull request merged**
