### PR TITLE
OCPNODE-1286: Add a new periodic cri-o CI job

### PR DESCRIPTION
**Pull request by sairameshv**
Add a job to periodically run cri-o e2e tests by enabling the evented pleg feature

/cc @harche @mrunalp @sohankunkerkar @saschagrunert 

Linked cri-o PR: https://github.com/cri-o/cri-o/pull/6955

### CODE REVIEW

**Comment by haircommander** [comment]
/approve

LGTM thanks!

**Comment by sohankunkerkar** [comment]
@sairameshv I think you might want to add config in https://github.com/openshift/release/blob/master/ci-operator/config/cri-o/cri-o/cri-o-cri-o-main__ci.yaml#L41 with `e2e-evented-pleg` and do `make jobs` to update the corresponding job.

**Review by saschagrunert — APPROVED** [review]

**Comment by sohankunkerkar** [comment]
Not a blocker but if you want to track the status of your periodic job, then try adding [these](https://github.com/openshift/release/blob/master/ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-main-periodics.yaml#LL19C1-L29C33) lines:

**Comment by sairameshv** [comment]
> Not a blocker but if you want to track the status of your periodic job, then try adding [these](https://github.com/openshift/release/blob/master/ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-main-periodics.yaml#LL19C1-L29C33) lines:

Agree, Updated !!

**Pull request merged**
