### PR TITLE
Add a ContainerRuntimeConfig to enable debug logging.

### PR DESCRIPTION
**Pull request by dgoodwin**
For azure 4.9 to 4.10 upgrade job debugging.

### CODE REVIEW

**Comment by wking** [comment]
Looks good to me, for something we expect to use for testing and then remove once that testing completes.  I'm adding a hold in case you want to wait and see how the rehearsal goes.

/lgtm
/hold

**Review by wking — APPROVED** [review]
/lgtm

**Comment by dgoodwin** [comment]
Failure doesn't look related to my change and I can now see level=debug messages from crio service in system journals. Going to run it again but this job fails all the time so may release hold if another result lands that doesn't look related to this change.

**Pull request merged**
