### PR TITLE
cucushift-installer-rehearse-aws-ipi-ovn-kubevirt-hypershift-mce

### PR DESCRIPTION
**Pull request by LiangquanLi930**
[OCPQE-12426](https://issues.redhat.com/browse/OCPQE-12426)
[OCPQE-14019](https://issues.redhat.com/browse/OCPQE-14019)

### CODE REVIEW

**Comment by LiangquanLi930** [comment]
@liangxia @kuiwang02 Could you help to review this PR? thanks

**Comment by LiangquanLi930** [comment]
[OCPQE-12426](https://issues.redhat.com/browse/OCPQE-12426)

**Comment by LiangquanLi930** [comment]
[OCPQE-14019](https://issues.redhat.com/browse/OCPQE-14019)

**Comment by kuiwang02** [comment]
iamok from golang's view.

**Pull request merged**
