### PR TITLE
Move all monitoring components to go 1.12

### PR DESCRIPTION
**Pull request by paulfantom**
Switch to go 1.12 for all remaining components managed by @openshift/openshift-team-monitoring 

Also `s/mxinden/paulfantom/g` in OWNERS files :)

/hold

### CODE REVIEW

**Comment by paulfantom** [comment]
Blocked by:
- https://github.com/openshift/prom-label-proxy/pull/9
- https://github.com/openshift/grafana/pull/18
- https://github.com/openshift/kube-state-metrics/pull/11

**Comment by paulfantom** [comment]
We have everything merged now so this should be fine.

/hold cancel

**Comment by brancz** [comment]
Awesome! That was a big chunk of hard work. Nice job! :tada: 

/lgtm

**Comment by brancz** [comment]
cc @krasi-georgiev @pgier for approving the rest

**Comment by squat** [comment]
wowi!

**Pull request merged**
