### PR TITLE
Sync Serverless CI

### PR DESCRIPTION
**Pull request by serverless-qe**
Sync Serverless CI using openshift-knative/hack.

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by creydr** [comment]
@mgencur could you PTAL at this PR? Need you as an approver :) 

/cc @mgencur

**Comment by creydr** [comment]
/pj-rehearse periodic-ci-openshift-knative-eventing-release-v1.12-414-test-conformance-aws-ocp-414-continuous

**Comment by mgencur** [comment]
Hey @creydr @matzew , this PR now includes new changes which were brought with new commits in openshift-knative/hack. This PR looks good to me. Just running some re-hearse jobs.

/pj-rehearse more

**Pull request merged**
