### PR TITLE
Adding openshift-eng/openshift-goimports repository

### PR DESCRIPTION
**Pull request by coreydaley**

### CODE REVIEW

**Comment by coreydaley** [comment]
@smg247 This pull request should be all cleaned up now and all tests are passing. Please take a look when you get a moment.

**Comment by smg247** [comment]
@coreydaley you don't need an approval from me (or anyone on the test-platform team). The PR is already approved. Just needs an lgtm from _anyone_. That should be from someone on your team as these are your configs that you will own.

**Comment by coreydaley** [comment]
> @coreydaley you don't need an approval from me (or anyone on the test-platform team). The PR is already approved. Just needs an lgtm from _anyone_. That should be from someone on your team as these are your configs that you will own.

Ok, thanks.

**Comment by coreydaley** [comment]
/assign @adambkaplan @gabemontero 
Could one of you take a look at this and lgtm if it looks good?

**Pull request merged**
