### PR TITLE
assisted publish jobs: create docker config directory

### PR DESCRIPTION
**Pull request by adriengentil**

### CODE REVIEW

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-release-4.14-push-pr-image periodic-ci-openshift-assisted-installer-agent-release-ocm-2.6-mirror-nightly-image periodic-ci-openshift-assisted-installer-master-edge-mirror-nightly-image-controller

**Review by osherdp — APPROVED** [review]

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-release-4.14-push-pr-image periodic-ci-openshift-assisted-installer-agent-release-ocm-2.6-mirror-nightly-image periodic-ci-openshift-assisted-installer-master-edge-mirror-nightly-image-controller

**Review by osherdp — APPROVED** [review]

**Pull request merged**
