### PR TITLE
ci-operator/templates/openshift/installer/cluster-launch-installer-upi-src: Drop unused template

### PR DESCRIPTION
**Pull request by wking**
The template was added in 78d8c17337 (#5388), but had no consumers.  There were potential consumers in flight [here][1] and [here][2], but both of those pull requests closed without landing.  We can always dig this back out of the Git history if it turns out folks actually do need a non-e2e UPI template, but until then remove it to save the maintenance cost of keeping unused code up to date.

[1]: https://github.com/openshift/release/pull/4325/files#diff-264b567e579413709feec76ef0604cf3R336
[2]: https://github.com/openshift/release/pull/5367/files#diff-131c135812b5130dcd1252473291b4a5R188

### CODE REVIEW

**Comment by wking** [comment]
We probably want to drop [this ci-tools code][1] too.  Or is there a UPI-src consumer I'm missing?  Cluster-bot?  Something magic in the ci-tools code?

[1]: https://github.com/openshift/ci-tools/blob/7aee696cc87a21b1c379f83089019466c928eeab/cmd/ci-operator-prowgen/main.go#L325-L328

**Comment by wking** [comment]
CC @markusthoemmes

**Comment by stevekuznetsov** [comment]
Looks like a lot of work, to what end?

**Comment by wking** [comment]
Dropping unused code looks like work?  I'm trying to save us work we're currently spending on apparently dead code:

```console
$ git --no-pager log --date=short --format='%h %ad%d %s' origin/master -- ci-operator/templates/openshift/installer/cluster-launch-installer-upi-src.yaml 
9cd158adf 2019-12-03 (origin/pr/6223) template: Use a more correct kill command
dc2607523 2019-12-02 (origin/pr/6192) ci-operator/templates/openshift/installer: Bump AWS UPI to RHCOS 43.81.201911221453.0
3893cb541 2019-11-17 (origin/pr/5959) template: Increase teardown timeout
43de8a538 2019-11-16 (origin/pr/5955) template: Bump all activeDeadlineSeconds to 4 hours
866f4db0d 2019-11-03 (origin/pr/5749) ci-operator/templates: Pull AWS region and zone from the cluster for TEST_PROVIDER
8b01d7cb7 2019-10-29 (origin/pr/5649) Enable image registry for UPI & metal tests
9463bff2b 2019-10-17 (origin/pr/5495) teardown: Gather machines and machinesets on teardown of clusters
7f980d050 2019-10-16 (origin/pr/5459) Add CLI init container to UPI src template.
78d8c1733 2019-10-11 (origin/pr/5388) Add a UPI based src template.
```

**Comment by wking** [comment]
Rebased around #6223 with 2bbd0c60c -> 25d8ecfd8.

**Comment by markusthoemmes** [comment]
The work on that template was done to make it possible to test the Serverless product on VMSphere based environments. We kinda dropped it cause we hit issue after issue and it was said that these envs are moving to a cloud provider so we'd need a different template anyway. @mgencur can tell more.

**Comment by mgencur** [comment]
We dropped the work for Serverless on vSphere because the environment was not able to provision load balancers for Kubernetes services. I believe the work to migrate vSphere setup to AWS is still ongoing, tracked in https://github.com/openshift/installer/pull/2603. I'm not sure if the code that is being removed from this openshift/release repo will work with the new installer.
From Serverless point of view, we still want to run tests on vSphere but we're waiting for the PR above. Our work is tracked in https://jira.coreos.com/browse/SRVKS-278

**Comment by wking** [comment]
> From Serverless point of view, we still want to run tests on vSphere...

Ok, so the issue is that installer-provisioned vSphere is not a thing?  And you're looking to run a custom test suite, so you can't use the upi-e2e template?

**Comment by markusthoemmes** [comment]
@wking exactly so!

**Pull request closed without merging**
