### PR TITLE
stackrox: Add a presubmit check for stackrox repo config

### PR DESCRIPTION
**Pull request by gavin-stackrox**
Run the stackrox/stackrox config check when config/ or jobs/ files are modified for that repo. I've added this as a variant to keep it out of the main config/ file.

/fyi @msugakov @BradLugo @davdhacs @tommartensen (note: you guys cannot review as you are not owners in the changed dirs)

### CODE REVIEW

**Comment by gavin-stackrox** [comment]
/uncc
this PR is still a WIP

**Comment by gavin-stackrox** [comment]
Finally! Passes test.
/pj-rehearse ack
/cc

**Comment by calebevans** [comment]
@gavin-stackrox I'm not sure why I am a reviewer on this. I can review it, does this have to do with interop testing at all?

**Comment by gavin-stackrox** [comment]
> @gavin-stackrox I'm not sure why I am a reviewer on this. I can review it, does this have to do with interop testing at all?

@calebevans this has nothing to do with interop. I'd guess the openshift-ci bot initially added you because you are in the OWNERS chain somewhere. I can ask for new reviewers in #test-platform if you don't feel this is your area.

**Comment by calebevans** [comment]
@gavin-stackrox i dont mind reviewing, but it probably wouldn't mean much as I'm not exactly sure what this PR is doing because I'm not familiar. It'd probably be more useful to have someone else more familiar review this one.

**Comment by gavin-stackrox** [comment]
Agreed and Thanks!
/uncc @calebevans

**Comment by DennisPeriquet** [comment]
hi @gavin-stackrox, I'm not familiar with what your test does, ... but, it passed the unit tests and your rehearse job and the scope looks limited to the stackrox area.  If you looked at the logs and they look to be doing what you expect, I can ltgm.

**Pull request merged**
