### PR TITLE
MCO-1416: Make `e2e-gcp-op-techpreview` Required

### PR DESCRIPTION
**Pull request by isabella-janssen**
Makes `e2e-gcp-op-techpreview` a blocking job.

### CODE REVIEW

**Comment by RishabhSaini** [comment]
great job!
 /lgtm

**Comment by cheesesashimi** [comment]
Nice job with the changes @isabella-janssen!

@RishabhSaini I don't think you have LGTM / approval permissions for this repo yet. Might not be a bad idea for you and @isabella-janssen to open separate PRs to the OWNERS file to get those permissions :smile:.

Other than that, I want to let this sit for a day or two before we merge it just to get a sense of how well the `e2e-gcp-op-techpreview` job is performing.

**Comment by dkhater-redhat** [comment]
I dont think the lgtm got picked up so re-added it :)

**Pull request closed without merging**
