### PR TITLE
[WIP] WinC Disconnected

### PR DESCRIPTION
**Pull request by saifshaikh48**

### CODE REVIEW

**Comment by saifshaikh48** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-disconnected-e2e-operator

**Comment by saifshaikh48** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-nutanix-disconnected-e2e-operator

**Comment by saifshaikh48** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-nutanix-disconnected-e2e-operator

**Comment by 2uasimojo** [comment]
> @[openshift-ci](https://github.com/apps/openshift-ci) openshift-ci bot requested review from [0xFelix](https://github.com/0xFelix) and [2uasimojo](https://github.com/2uasimojo) [1 hour ago](https://github.com/openshift/release/pull/51266#event-12580851595)

Why?

/unassign
/uncc

**Comment by saifshaikh48** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-nutanix-disconnected-e2e-operator

**Comment by saifshaikh48** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-nutanix-disconnected-e2e-operator

**Comment by saifshaikh48** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-vsphere-disconnected-e2e-operator

**Comment by saifshaikh48** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-vsphere-disconnected-e2e-operator

**Comment by saifshaikh48** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-vsphere-disconnected-e2e-operator

**Comment by saifshaikh48** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-vsphere-disconnected-e2e-operator

**Comment by saifshaikh48** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-vsphere-disconnected-e2e-operator

**Comment by saifshaikh48** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-vsphere-disconnected-e2e-operator

**Comment by saifshaikh48** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-vsphere-disconnected-e2e-operator

**Comment by saifshaikh48** [comment]
/close

https://github.com/openshift/release/pull/50547 went in for this work

**Pull request closed without merging**
