### PR TITLE
vsphere upi: upgrade rhcos template hardware

### PR DESCRIPTION
**Pull request by jcpowermac**
- Removes previous upload debugging
- Removes check for template. Always uploads new template
- Randomly selects a hardware version, updates hardware to either:
  15, 17, 18 or 19.

### CODE REVIEW

**Comment by jcpowermac** [comment]
changes are working as expected the issue is with reusing the namespace
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/21153/rehearse-21153-periodic-ci-openshift-release-master-nightly-4.9-e2e-vsphere-upi-serial/1431354111990697984/artifacts/e2e-vsphere-upi-serial/upi-conf-vsphere-ova/build-log.txt

**Comment by rvanderp3** [comment]
The import of the ova via cluster_name appears to be precreating the VM directory and terraform fails on installation due to this.

**Pull request closed without merging**
