### PR TITLE
Always send users to gubernator for origin

### PR DESCRIPTION
**Pull request by smarterclayton**
We want to depend less and less on Jenkins, and Jenkins is slow and
most users who view logs won't be able to do anything useful there
anyway. Would rather have gubernator be the only location.

@skuznets even after opening the fix to test-infra, I still think we should send users to gubernator always because it allows users to get PR history and other behavior that is more valuable than seeing the (slow) jenkins page that they can't do anything useful on.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Can you add the `FINISHED STAGE: FAILURE:` to the list of things that Gubernator highlights so users can get some of the UX that we had with Jenkins FCM?

**Comment by stevekuznetsov** [comment]
@smarterclayton probably good to add them to this: https://github.com/openshift/test-infra/blob/master/gubernator/regex.py#L28

**Comment by smarterclayton** [comment]
Just in our fork, upstream, or add a config?

**Comment by stevekuznetsov** [comment]
Just in our fork -- I haven't tried to break out Gubernator in config at all.

**Comment by smarterclayton** [comment]
In https://github.com/openshift/test-infra/pull/20

**Pull request merged**
