### PR TITLE
Add ci-ppc test to NTO as part of PAO migration

### PR DESCRIPTION
**Pull request by jlojosnegros**
As part of Performance Addon Operation (PAO) migration to Node Tuning Operator (NTO) (openshift/cluster-node-tuning-operator#322) Performance Profile Creator (PPC) CLI tool is being migrated ( openshift/cluster-node-tuning-operator#325).

This PR add the automatic execution of the PPC unit tests.

### CODE REVIEW

**Comment by yanirq** [comment]
@jlojosnegros  make sure to add this also to 4.11 and 4.12 manifests. 
After that you need to run `make update` to get the auto generated files for jobs.

**Comment by jmencak** [comment]
Needs https://github.com/openshift/cluster-node-tuning-operator/pull/325 merged first and as Yanir says, I'm missing mods in 4.11 and 4.12 files.

**Comment by jlojosnegros** [comment]
> @jlojosnegros make sure to add this also to 4.11 and 4.12 manifests.
> After that you need to run `make update` to get the auto generated files for jobs.

Ok, I will take care of it 

> Also - make sure the makefile target will exist on Node tuning operator.
it will be available when https://github.com/openshift/cluster-node-tuning-operator/pull/325 will be merged.

**Comment by jlojosnegros** [comment]
> @jlojosnegros make sure to add this also to 4.11 and 4.12 manifests.
> After that you need to run `make update` to get the auto generated files for jobs.

Added

**Comment by yanirq** [comment]
/hold cancel

@jmencak ill leave the final review here for you before approval.

**Comment by jlojosnegros** [comment]
rebase to solve conflicts

**Comment by jmencak** [comment]
Thank you for the PR, Jose.
/lgtm
/approve

**Review by jmencak — APPROVED** [review]

**Pull request merged**
