### PR TITLE
Updating openshift-qe to use e2e v2.1.8

### PR DESCRIPTION
**Pull request by vishnuchalla**
### Description
Updating `openshift-qe` to use latest e2e version (.i.e v1.2.8)

### Testing
Will be verifying through the rehearsal jobs.

### CODE REVIEW

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-release-4.15-qe-perfscale-aws-ovn-small-cluster-density

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-data-path-9nodes

**Comment by jtaleric** [comment]
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/53245/rehearse-53245-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-data-path-9nodes/1802150023492800512#1:build-log.txt%3A253 

appears to be a weird timing issue here. We delete the ns in the smoke test, so we attempt to reuse it since it still exists when we kick off the real test :(

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-data-path-9nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-data-path-9nodes

**Comment by krishvoor** [comment]
@vishnuchalla - Very Minor nit - can you update the PR title from `v1.2.8` to `v2.1.8` :)

**Comment by jtaleric** [comment]
It is very weird. 

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/53245/rehearse-53245-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-data-path-9nodes/1805266370724630528/artifacts/data-path-9nodes/openshift-qe-network-smoke/build-log.txt 

We don't even see 4096 be attempted w/o hostNetwork.

**Pull request merged**
