### PR TITLE
OCPEDGE-592: Automate rebasing for openshift/topolvm repo

### PR DESCRIPTION
**Pull request by suleymanakbas91**

### CODE REVIEW

**Comment by suleymanakbas91** [comment]
/pj-rehearse periodic-ci-openshift-eng-rebasebot-main-topolvm

**Comment by suleymanakbas91** [comment]
/pj-rehearse periodic-ci-openshift-eng-rebasebot-main-topolvm

**Comment by suleymanakbas91** [comment]
/pj-rehearse periodic-ci-openshift-eng-rebasebot-main-topolvm

**Comment by suleymanakbas91** [comment]
/pj-rehearse periodic-ci-openshift-eng-rebasebot-main-topolvm

**Comment by RadekManak** [comment]
/pj-rehearse periodic-ci-openshift-eng-rebasebot-main-topolvm

**Comment by RadekManak** [comment]
/pj-rehearse periodic-ci-openshift-eng-rebasebot-main-topolvm

**Comment by suleymanakbas91** [comment]
/pj-rehearse periodic-ci-openshift-eng-rebasebot-main-topolvm

**Comment by suleymanakbas91** [comment]
/pj-rehearse periodic-ci-openshift-eng-rebasebot-main-topolvm

**Comment by RadekManak** [comment]
/pj-rehearse periodic-ci-openshift-eng-rebasebot-main-topolvm

**Pull request merged**
