### PR TITLE
Removing DTK nightly job for 4.8.

### PR DESCRIPTION
**Pull request by ybettan**
We will support max 2 versions backward, for example during 4.12 development we will support 4.9 and 4.10 in addition to the current version released which is 4.11.

Signed-off-by: Yoni Bettan <yonibettan@gmail.com>

### CODE REVIEW

**Comment by ybettan** [comment]
@dgoodwin I tried to follow the CI instruction but seems like `make release-controllers` isn't working. Not even on `master`.
```
ybettan release (nightly-4.8) $ make release-controllers
curl -o clusters/app.ci/release-controller/admin_01_releasepayload_crd.yaml https://raw.githubusercontent.com/openshift/release-controller/master/artifacts/release.openshift.io_releasepayloads.yaml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 26590  100 26590    0     0  47022      0 --:--:-- --:--:-- --:--:-- 46978
sed -i '/./,$!d' 'clusters/build-clusters/common/testimagestreamtagimport.yaml'
sed -i '/./,$!d' 'clusters/app.ci/prow/01_crd/pullrequestpayloadqualificationruns.yaml'
sed -i '/./,$!d' 'clusters/app.ci/release-controller/admin_01_releasepayload_crd.yaml'
./hack/generators/release-controllers/generate-release-controllers.py .
Traceback (most recent call last):
  File "/home/ybettan/go/src/github.com/release/./hack/generators/release-controllers/generate-release-controllers.py", line 25, in <module>
    import genlib
  File "/home/ybettan/go/src/github.com/release/hack/generators/lib/genlib/__init__.py", line 3, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
make: *** [Makefile:61: release-controllers] Error 1
```

Any idea how can I solve it?

**Comment by dgoodwin** [comment]
This is more a question for testplatform, but maybe try installing python3-pyyaml or equivalent.

**Comment by ybettan** [comment]
`pip install pyyaml` did the trick.
Thanks @dgoodwin 
PTAL

**Comment by ybettan** [comment]
@stbenjam Do you have any idea why this PR isn't merging? I have no idea what `Not mergeable. Must be by author openshift-bot OR Needs rehearsals-ack label.` means.

**Pull request merged**
