### PR TITLE
OCPQE-22783 set catalogsource name for 4.16 auto release jobs

### PR DESCRIPTION
**Pull request by rioliu-rh**
configure catalogsource name as `auto-release-app-registry` for 4.16 auto release jobs. 
catalogsource rename is supported by code change in https://github.com/openshift/release/pull/53089

### CODE REVIEW

**Comment by rioliu-rh** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-automated-release-aws-ipi-private-shared-vpc-phz-sts-f360

**Comment by rioliu-rh** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-automated-release-azure-ipi-marketplace-mini-perm-f360

**Comment by liangxia** [comment]
We also have automated release jobs for 4.12

**Comment by rioliu-rh** [comment]
> We also have automated release jobs for 4.12

yes, I wanna do the same change for 4.12 in another PR.

**Comment by rioliu-rh** [comment]
latest catalogsource list is like below
```console
$ omc get catalogsource -n openshift-marketplace
NAME                        DISPLAY                TYPE   PUBLISHER      AGE
auto-release-app-registry   Production Operators   grpc   OpenShift QE   1h
certified-operators         Certified Operators    grpc   Red Hat        2h
community-operators         Community Operators    grpc   Red Hat        2h
redhat-marketplace          Red Hat Marketplace    grpc   Red Hat        2h
redhat-operators            Red Hat Operators      grpc   Red Hat        2h
```

**Comment by rioliu-rh** [comment]
@liangxia can you help to add lgtm, thx

**Pull request merged**
