### PR TITLE
[kubevirt] update go to 1.19 in ssp and tekton tasks manifests

### PR DESCRIPTION
**Pull request by ksimon1**
update go to 1.19 in ssp and tekton tasks manifests
Signed-off-by: Karel Šimon <ksimon@redhat.com>

### CODE REVIEW

**Comment by akrejcir** [comment]
Can you do the same change for SSP `v0.16`, because that will be in `4.12`.

**Comment by ksimon1** [comment]
> Can you do the same change for SSP `v0.16`, because that will be in `4.12`.

done

**Comment by akrejcir** [comment]
Looks good, I will give `/lgtm` when tests pass.

**Review by 0xFelix — APPROVED** [review]
/lgtm

**Pull request merged**
