### PR TITLE
Kubevirt-BM-0212-416

### PR DESCRIPTION
**Pull request by jechen0648**

### CODE REVIEW

**Comment by jechen0648** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-kubevirt-baremetalds-conformance

**Comment by jechen0648** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-kubevirt-baremetalds-conformance

**Comment by jechen0648** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-kubevirt-baremetalds-conformance

**Comment by jechen0648** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-kubevirt-baremetalds-conformance

**Comment by jechen0648** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-kubevirt-csi-conformance

**Comment by jechen0648** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-kubevirt-baremetalds-conformance

**Comment by qinqon** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-kubevirt-baremetalds-conformance

**Comment by jechen0648** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-kubevirt-baremetalds-conformance

**Comment by jechen0648** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-kubevirt-baremetalds-conformance

**Pull request closed without merging**
