### PR TITLE
Setup E2E tests for the opendatahub-io/data-science-pipeline-operator

### PR DESCRIPTION
**Pull request by harshad16**
Setup E2E tests for the opendatahub-io/data-science-pipeline-operator
 
 This would run an install and test script.
 The script would install the data-science-pipeline-operator and run a series of checks.
 
 Depends-on: https://github.com/openshift/release/pull/36619

### CODE REVIEW

**Comment by harshad16** [comment]
/pj-rehearse pull-ci-opendatahub-io-data-science-pipelines-operator-main-dsp-operator-e2e

**Comment by harshad16** [comment]
/pj-rehearse pull-ci-opendatahub-io-data-science-pipelines-operator-main-dsp-operator-e2e

**Comment by harshad16** [comment]
/pj-rehearse pull-ci-opendatahub-io-data-science-pipelines-operator-main-dsp-operator-e2e

**Comment by harshad16** [comment]
/pj-rehearse pull-ci-opendatahub-io-data-science-pipelines-operator-main-dsp-operator-e2e

**Comment by harshad16** [comment]
/pj-rehearse pull-ci-opendatahub-io-data-science-pipelines-operator-main-dsp-operator-e2e

**Comment by harshad16** [comment]
/pj-rehearse pull-ci-opendatahub-io-data-science-pipelines-operator-main-dsp-operator-e2e

**Comment by harshad16** [comment]
/pj-rehearse pull-ci-opendatahub-io-data-science-pipelines-operator-main-dsp-operator-e2e

**Review by rimolive — APPROVED** [review]

**Pull request merged**
