### PR TITLE
add the manifest-tool binary to the ci-tools-build-root image

### PR DESCRIPTION
**Pull request by droslean**
/cc @openshift/test-platform

### CODE REVIEW

**Comment by danilo-gemoli** [comment]
`manifest-tool` was already copied in [images/multi-arch-builder-controller/Dockerfile](https://github.com/openshift/ci-tools/blob/80e760661c2b495f7804426a625745e4c5bdf004/images/multi-arch-builder-controller/Dockerfile), why do we need it inside the build root?

**Comment by droslean** [comment]
@danilo-gemoli For the e2e job in ci-tools.

**Comment by droslean** [comment]
https://github.com/openshift/ci-tools/pull/3587

**Pull request merged**
