### PR TITLE
feat: Automate max concurency test

### PR DESCRIPTION
**Pull request by jhutar**

### CODE REVIEW

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12

**Review by khrm — COMMENTED** [review]
/lgtm
/approve

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-100 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-600-60 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-700-70 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-800-80 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-900-90

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-100 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-600-60 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-700-70 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-800-80 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-900-90

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-100 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-600-60 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-700-70 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-800-80 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-900-90

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-100 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-800-80 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-900-90

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-100 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-800-80 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-900-90

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-800-80

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-800-80

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-100 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-90 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-80 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-70 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-60 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-100-ha-2 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-90-ha-2 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-80-ha-2 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-70-ha-2 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-60-ha-2 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-100-ha-4 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-90-ha-4 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-80-ha-4 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-70-ha-4 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-60-ha-4 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-100-ha-8 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-90-ha-8 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-80-ha-8 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-70-ha-8 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-60-ha-8

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-60-ha-2

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-60-ha-2

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-100 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-90 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-80 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-70 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-60 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-100-ha-2 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-90-ha-2 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-80-ha-2 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-70-ha-2 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-60-ha-2 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-100-ha-4 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-90-ha-4 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-80-ha-4 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-70-ha-4 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-60-ha-4 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-100-ha-8 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-90-ha-8 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-80-ha-8 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-70-ha-8 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-60-ha-8

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-100 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-90 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-80 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-70 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-60 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-100-ha-2 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-90-ha-2 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-80-ha-2 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-70-ha-2 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-60-ha-2 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-100-ha-4 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-90-ha-4 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-80-ha-4 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-70-ha-4 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-60-ha-4 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-100-ha-8 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-90-ha-8 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-80-ha-8 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-70-ha-8 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-60-ha-8

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-100 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-90 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-80 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-70 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-60 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-100-ha-2 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-90-ha-2 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-80-ha-2 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-70-ha-2 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-60-ha-2 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-100-ha-4 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-90-ha-4 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-80-ha-4 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-70-ha-4 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-60-ha-4 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-100-ha-8 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-90-ha-8 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-80-ha-8 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-70-ha-8 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-60-ha-8

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-100 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-90 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-80 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-70 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-60 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-100-ha-4 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-90-ha-4 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-80-ha-4 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-70-ha-4 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-60-ha-4

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-60 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-70 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-80 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-90 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-100

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-60 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-70 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-80 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-90 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-100

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-60 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-70 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-80 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-90 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-100

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-100-ha-10 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-60-ha-10 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-70-ha-10 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-80-ha-10 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-12-1000-90-ha-10

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-100-ha-10 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-60-ha-10 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-70-ha-10 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-80-ha-10 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-90-ha-10

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-60 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-70 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-80 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-90 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-100

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-100-ha-10 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-60-ha-10 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-70-ha-10 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-80-ha-10 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-90-ha-10

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-100-ha-10 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-60-ha-10 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-70-ha-10 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-80-ha-10 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-90-ha-10

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-100-ha-10 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-60-ha-10 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-70-ha-10 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-80-ha-10 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-90-ha-10

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-100-x-build

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-100-x-build

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-60 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-70 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-80 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-90 pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-1000-100

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-100-x-build

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-100-x-build

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-100-x-build

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-100-x-build

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-max-concurrency-downstream-1-13-100-x-build

**Review by koustavsaha — COMMENTED** [review]
/lgtm

**Review by khrm — COMMENTED** [review]
/approve

**Pull request merged**
