### PR TITLE
rhods: Add red-hat-data-services-ci-image-mirror workflow

### PR DESCRIPTION
**Pull request by samuelvl**
Fix this error in https://github.com/red-hat-data-services/notebooks repository:

``` 
ERROR Registry secret file not found: /secrets/red-hat-data-services-push-secret/config.json
```

### CODE REVIEW

**Comment by samuelvl** [comment]
@LaVLaS Could you lgtm this PR? Looks like @atheo89 lgtm is not enough :/

**Review by LaVLaS — APPROVED** [review]
/lgtm

**Comment by LaVLaS** [comment]
> @LaVLaS Could you lgtm this PR? Looks like @atheo89 lgtm is not enough :/

Do you want to add @atheo89 the RHODS step-registry [OWNERS](https://github.com/openshift/release/blob/master/ci-operator/step-registry/red-hat-data-services/OWNERS)

**Pull request merged**
