### PR TITLE
Add Jaeger OCP 4.16 stage testing job

### PR DESCRIPTION
**Pull request by IshwarKanse**

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.16-stage-jaeger-stage-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.16-stage-jaeger-stage-tests

**Review by vprashar2929 — APPROVED** [review]
/lgtm

**Pull request merged**
