### PR TITLE
Update aosqe-index image to 4.16 for 4.16 z stream upgrade

### PR DESCRIPTION
**Pull request by JianLi-RH**

### CODE REVIEW

**Comment by JianLi-RH** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-4.16-upgrade-from-stable-4.16-gcp-ipi-xpn-private-filestore-csi-arm-f28

**Comment by JianLi-RH** [comment]
hi @jianlinliu @shellyyang1989 @jiajliu @evakhoni @dis016  since run this job hit  `argument list too long`, can we merge it without test? cc @chao007

**Comment by jianlinliu** [comment]
> can we merge it without test

okay for me

**Comment by jianlinliu** [comment]
cc @liangxia to review.

**Pull request merged**
