### PR TITLE
Add infra-role label to job branch-ci-openshift-release-master-core-apply

### PR DESCRIPTION
**Pull request by hongkailiu**
/cc @openshift/openshift-team-developer-productivity-test-platform

### CODE REVIEW

**Comment by hongkailiu** [comment]
The reason why I did not use the method in https://github.com/openshift/release/pull/5341

TBU: working on Ben's comments right now.

**Comment by stevekuznetsov** [comment]
Wouldn't it be better just to add the infra label to these jobs? I want us to be able to opt more jobs into the alerting without doing all this work.

**Comment by hongkailiu** [comment]
> Wouldn't it be better just to add the infra label to these jobs? I want us to be able to opt more jobs into the alerting without doing all this work.

On it.
I thought the infra label was only for the periodics.

**Comment by stevekuznetsov** [comment]
Owners can't run:

```
  Warning  Failed     23m (x2 over 23m)    kubelet, origin-ci-ig-n-gnqm  Failed to pull image "centos:7": rpc error: code = Unknown desc = received unexpected HTTP status: 503 Service Unavailable
  Warning  Failed     23m (x2 over 23m)    kubelet, origin-ci-ig-n-gnqm  Error: ErrImagePull
  Normal   Pulling    23m (x3 over 23m)    kubelet, origin-ci-ig-n-gnqm  pulling image "centos:7"
  Normal   BackOff    14m (x39 over 23m)   kubelet, origin-ci-ig-n-gnqm  Back-off pulling image "centos:7"
  Warning  Failed     4m3s (x78 over 23m)  kubelet, origin-ci-ig-n-gnqm  Error: ImagePullBackOff
```
:(

**Pull request merged**
