### PR TITLE
WIP - ipi-aws-proxy: Use tls endpoint for squid

### PR DESCRIPTION
**Pull request by adambkaplan**
Use the TLS endpoint for the HTTPS_PROXY endpoint. HTTPS connections
from containers to the proxy will be TLS encrypted with squid's
self-signed certificate. Tests which require a connection to the
internet will fail unless the proxy's CA is added to the container's TLS
trust bundle.

### CODE REVIEW

**Comment by adambkaplan** [comment]
@wking based on our conversation yesterday. I expect most build tests to fail running the build in the rehearsal.

**Comment by adambkaplan** [comment]
/retest

@wking looks like we aren't even getting the bootstrap cluster up with this change - any idea what is going on here?

**Comment by wking** [comment]
Sorry for the delay.  [Job][1] has [an installer log bundle][2] in assets.  Pulling that down:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/16293/rehearse-16293-pull-ci-openshift-installer-master-e2e-aws-proxy/1366942569312817152/artifacts/e2e-aws-proxy/ipi-install-install/artifacts/log-bundle-20210303033144.tar | tar xz
$ ls -l log-bundle-20210303033144/bootstrap/journals/
total 13872
-rw-r--r-- 1 wking wking      102 Mar  2 19:31 approve-csr.log
-rw-r--r-- 1 wking wking      102 Mar  2 19:31 bootkube.log
-rw-r--r-- 1 wking wking      102 Mar  2 19:31 crio-configure.log
-rw-r--r-- 1 wking wking      102 Mar  2 19:31 crio.log
-rw-r--r-- 1 wking wking      102 Mar  2 19:31 ironic.log
-rw-r--r-- 1 wking wking      102 Mar  2 19:31 kubelet.log
-rw-r--r-- 1 wking wking      102 Mar  2 19:31 master-bmh-update.log
-rw-r--r-- 1 wking wking 14173531 Mar  2 19:31 release-image.log
$ tail -n3 log-bundle-20210303033144/bootstrap/journals/release-image.log 
Mar 03 03:31:45 ip-10-0-12-53 release-image-download.sh[1620]: Pull failed. Retrying registry.build01.ci.openshift.org/ci-op-jfftk271/release@sha256:773e8a38f1cb915867f47452afe85998228d00c6991e62795046705c0e1cc2e7...
Mar 03 03:31:45 ip-10-0-12-53 release-image-download.sh[1620]: Error: unable to pull registry.build01.ci.openshift.org/ci-op-jfftk271/release@sha256:773e8a38f1cb915867f47452afe85998228d00c6991e62795046705c0e1cc2e7: Error initializing source docker://registry.build01.ci.openshift.org/ci-op-jfftk271/release@sha256:773e8a38f1cb915867f47452afe85998228d00c6991e62795046705c0e1cc2e7: error pinging docker registry registry.build01.ci.openshift.org: Get "https://registry.build01.ci.openshift.org/v2/": proxyconnect tcp: tls: first record does not look like a TLS handshake
Mar 03 03:31:45 ip-10-0-12-53 release-image-download.sh[1620]: Pull failed. Retrying registry.build01.ci.openshift.org/ci-op-jfftk271/release@sha256:773e8a38f1cb915867f47452afe85998228d00c6991e62795046705c0e1cc2e7...
```

Ah, [3128 is HTTP][3].  If we want to use HTTPS, we should use something like [this][4].  Which will also pull in all of the cert-generating business from that template.  And we'd also need to poke a new hole in the security group around [here][5].

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/16293/rehearse-16293-pull-ci-openshift-installer-master-e2e-aws-proxy/1366942569312817152
[2]: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/16293/rehearse-16293-pull-ci-openshift-installer-master-e2e-aws-proxy/1366942569312817152/artifacts/e2e-aws-proxy/ipi-install-install/artifacts/
[3]: https://github.com/openshift/release/blob/97ef576657e0467569d5f08b9ce8ffc87e39ab78/ci-operator/step-registry/ipi/conf/aws/proxy/ipi-conf-aws-proxy-commands.sh#L294
[4]: https://github.com/openshift/release/blob/97ef576657e0467569d5f08b9ce8ffc87e39ab78/ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml#L1411
[5]: https://github.com/openshift/release/blob/97ef576657e0467569d5f08b9ce8ffc87e39ab78/ci-operator/step-registry/ipi/conf/aws/proxy/ipi-conf-aws-proxy-commands.sh#L194

**Comment by ewolinetz** [comment]
sorry for the delay on this review... as @wking stated the https port is `3130` not `3128`. Squid has the config separated like that so it was more obvious which protocol was being used on the proxy side.

do we want to still keep the `http_port` as `3128` here? or do we want to force all communication via https?

**Comment by adambkaplan** [comment]
> do we want to still keep the http_port as 3128 here? or do we want to force all communication via https?

@ewolinetz my responses to your question would be:

1. How do our customers typically configure proxies?
2. Which configuration would be more likely to expose a problem in our code?

My gut is HTTPS only would be the right answer for question 2.

**Comment by ewolinetz** [comment]
> @ewolinetz my responses to your question would be:
> 
>     1. How do our customers typically configure proxies?
> 
>     2. Which configuration would be more likely to expose a problem in our code?
> 
> 
> My gut is HTTPS only would be the right answer for question 2.

I guess it depends -- do we need to ensure our components are using `https` when its available? if so, I feel like we wouldn't expose the `http` endpoint on the proxy at all then to make sure they can and will use `https` instead.

I may be off base on that though... I'm not sure what most customers would use. IMO those that are going through the trouble to ensure all communication goes through the proxy will want everything to be encrypted as well.

**Pull request closed without merging**
