### PR TITLE
Move openstack-baremetal and openstack prow jobs over from 4.14 to 4.15 Hive cluster

### PR DESCRIPTION
**Pull request by bshewale**

### CODE REVIEW

**Comment by lewisdenny** [comment]
#/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-tempest pull-ci-openstack-k8s-operators-openstack-baremetal-operator-main-openstack-baremetal-operator-build-deploy

**Comment by bshewale** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-tempest pull-ci-openstack-k8s-operators-openstack-baremetal-operator-main-openstack-baremetal-operator-build-deploy

**Comment by bshewale** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl

**Comment by viroel** [comment]
lgtm

**Pull request merged**
