### PR TITLE
ROX-14352: Bump CI images to latest version

### PR DESCRIPTION
**Pull request by porridge**
- Counterpart PR for https://github.com/stackrox/stackrox/pull/4485
/cc @janisz

### CODE REVIEW

**Comment by janisz** [comment]
Why so many failures?

**Comment by porridge** [comment]
As @gavin-stackrox mentioned [elsewhere](https://github.com/stackrox/stackrox/pull/4485#issuecomment-1400616353), vast majority of these are caused by the following and similar failures in `store-artifacts.sh`:

```
AccessDeniedException: 403 circleci-rox@stackrox-ci.iam.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket. Permission 'storage.buckets.get' denied on resource (or it may not exist).
Exception raised in ['scripts/ci/store-artifacts.sh', 'store_artifacts', '/tmp/collector-metrics', 'part-1/collector-metrics'], Command '['scripts/ci/store-artifacts.sh', 'store_artifacts', '/tmp/collector-metrics', 'part-1/collector-metrics']' returned non-zero exit status 1.
```

The only other failures are:
- [cert validation error in ROSA](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/35572/rehearse-35572-pull-ci-stackrox-stackrox-master-rosa-qa-e2e-tests/1616396129727942656): `E0120 12:51:26.848353     731 memcache.go:238] couldn't get current server API group list: Get "https://api.rox-ci-27942656.ezhu.p1.openshiftapps.com:6443/api?timeout=32s": x509: certificate signed by unknown authority`
- [couple of](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/35572/rehearse-35572-pull-ci-stackrox-stackrox-master-osd-aws-qa-e2e-tests/1616396126368305152) [PSP issues in OSD](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/35572/rehearse-35572-pull-ci-stackrox-stackrox-master-osd-gcp-qa-e2e-tests/1616396127202971648): `error: resource mapping not found for name: "stackrox-central" namespace: "" from "/go/src/github.com/stackrox/stackrox/deploy/openshift/central-deploy/central/01-central-02-psps.yaml": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"`
- [`IntegrationsSplunkViolationsTest` flake](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/35572/rehearse-35572-pull-ci-stackrox-stackrox-master-openshift-penultimate-qa-e2e-tests/1616396125638496256)
- [something that looks like `ImageScanningTest` flake on ARO](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/35572/rehearse-35572-pull-ci-stackrox-stackrox-master-aro-qa-e2e-tests/1616396108072751104)

I'll take a stab at retrying these first. Not sure what to do about the `circleci-rox` 403s? :shrug:
Could this indeed be caused by the image bump somehow?

**Comment by porridge** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-rosa-qa-e2e-tests pull-ci-stackrox-stackrox-master-osd-gcp-qa-e2e-tests pull-ci-stackrox-stackrox-master-osd-aws-qa-e2e-tests pull-ci-stackrox-stackrox-master-openshift-penultimate-qa-e2e-tests pull-ci-stackrox-stackrox-master-aro-qa-e2e-tests

**Comment by porridge** [comment]
After the retry, we're down to just two failure modes:
- the unrelated `no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"` ({rosa,osd-{gcp,aws}}-qa-e2e)
- `AccessDeniedException: 403 circleci-rox@stackrox-ci.iam.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket` on all other jobs

I think we can safely ignore the former.
About the latter, I really need help from @gavin-stackrox - I have no idea how that's supposed to work.

/cc @gavin-stackrox

**Comment by gavin-stackrox** [comment]
The PodSecurityPolicy related failure is fixed by https://github.com/stackrox/stackrox/pull/4488 so should disappear on the next round.

The error storing artifacts is concerning. The service account credentials used are valid (can create a cluster for example). I'm suspicious that something changed in the Google Cloud SDK from 50 -> 55. (gsutil 5.14 -> 5.18). The roles granted to this account do not seem to be sufficient for writing to a GCS bucket so how it ever worked is 🙃 (cc @porridge)

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-rosa-qa-e2e-tests pull-ci-stackrox-stackrox-master-osd-gcp-qa-e2e-tests pull-ci-stackrox-stackrox-master-osd-aws-qa-e2e-tests pull-ci-stackrox-stackrox-master-openshift-penultimate-qa-e2e-tests pull-ci-stackrox-stackrox-master-aro-qa-e2e-tests

**Comment by gavin-stackrox** [comment]
looks better. lets try the big guns!
/pj-rehearse max

**Comment by porridge** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-gke-nongroovy-e2e-tests pull-ci-stackrox-stackrox-master-gke-ui-e2e-tests pull-ci-stackrox-stackrox-master-gke-postgres-scale-tests pull-ci-stackrox-stackrox-master-gke-postgres-ui-e2e-tests pull-ci-stackrox-stackrox-master-gke-version-compatibility-tests pull-ci-stackrox-stackrox-master-rosa-qa-e2e-tests pull-ci-stackrox-stackrox-master-gke-postgres-qa-e2e-tests pull-ci-stackrox-stackrox-master-gke-upgrade-tests pull-ci-stackrox-stackrox-master-gke-race-condition-qa-e2e-tests pull-ci-stackrox-stackrox-master-gke-postgres-nongroovy-e2e-tests pull-ci-stackrox-stackrox-master-gke-qa-e2e-tests pull-ci-stackrox-stackrox-master-gke-kernel-qa-e2e-tests pull-ci-stackrox-stackrox-master-gke-scale-tests

**Comment by porridge** [comment]
I think we can declare victory :tada:
/pj-rehearse ack
@gavin-stackrox @janisz can I get an LGTM please?

**Review by janisz — APPROVED** [review]

**Pull request merged**
