### PR TITLE
quay: add jobs for quay-operator 3.9 and 3.8

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by dmage** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/44786/rehearse-44786-pull-ci-quay-quay-operator-redhat-3.9-ocp-latest-e2e/1716822369974095872

ACKing as the 3.9 job rehearsal was successful

/pj-rehearse ack

**Review by jonathankingfc — APPROVED** [review]
LGTM

**Pull request merged**
