### PR TITLE
MGMT-14240: Set ConnectionAttempts in assisted workflows

### PR DESCRIPTION
**Pull request by adriengentil**
Set `ConnectionAttempts` in ansible/ssh_config in order to retry SSH
connections when they fail (mostly with OCI).

### CODE REVIEW

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-egde-e2e-metal-assisted

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted

**Review by osherdp — APPROVED** [review]

**Pull request merged**
