### PR TITLE
Add HCO registry image builds and upgrade test

### PR DESCRIPTION
**Pull request by rwsu**
Add builds for the container registry image to deploy the operator
through OLM using the latest operator image on quay.io.

Builds a second container registry image to test upgrades using
the operator image built as part of the current job.

Adds a new e2e test for upgrades.

Requires this patch to merge: https://github.com/kubevirt/hyperconverged-cluster-operator/pull/313

### CODE REVIEW

**Comment by rthallisey** [comment]
@rwsu 
```"Failed to determine info for prow job config" error="file name was not prefixed with \"ci-operator-jobs-\": \"infra-periodics\"" source-file=/tmp/tmp.wOoua0sUar/ci-operator/jobs/infra-periodics.yaml```

**Comment by rwsu** [comment]
Latest tests show

````
2019/10/31 16:58:54 Build hco-registry-upgrade failed, printing logs:
Pulling image "docker-registry.default.svc:5000/ci-op-6mfg76ql/pipeline@sha256:a459e5bc236f2beb36591116ec79b3940f25661e2fefba85a37045f94fea50b2" ...
Replaced Dockerfile FROM image quay.io/openshift/origin-operator-registry:latest

Pulling image docker-registry.default.svc:5000/ci-op-6mfg76ql/pipeline@sha256:2c265d79f28cff9224ed81007874d1952c95190ce2d98dc0989c35c616b17bb7 ...

Pulling image fedora:30 ...
error: build error: no FROM statement found
````

and

````
2019/10/31 16:58:37 Build operator-registry-base failed, printing logs:
Pulling image "docker-registry.default.svc:5000/ci-op-7nrs0xpr/pipeline@sha256:c282cdccd9d2606250ed627b2a1a95ac5136ec2d5f3396f8b9d913b05a1403c8" ...
error: open /tmp/build/inputs/deploy/Dockerfile.registry.intermediate: no such file or directory
````

The first issue could be due to formatting in kubevirt/hyperconverged-cluster-operator/deploy/Dockerfile.registry.upgrade. It may not like ARG before FROM. Or the FROM clause to pull in fedora30 needs to be a more qualified URI. Not sure which version of docker OpenShift CI is using, but the issue could be because it is on an older version. I'll post an update to the HCO repo to workaround it. 

The second issue looks like a problem in the config file.

**Comment by rwsu** [comment]
Image builds are now working. The test itself needs a few more modifications in this PR: https://github.com/kubevirt/hyperconverged-cluster-operator/pull/344

**Comment by rwsu** [comment]
The hco-e2e-upgrade-aws jobs failed because the kubevirt-node-labeller pods couldn't be scheduled: 

````
            "status": {
                "conditions": [
                    {
                        "lastProbeTime": null,
                        "lastTransitionTime": "2019-11-07T16:24:33Z",
                        "message": "0/6 nodes are available: 5 node(s) didn't match node selector, 6 Insufficient devices.kubevirt.io/kvm.",
                        "reason": "Unschedulable",
                        "status": "False",
                        "type": "PodScheduled"
                    }
                ],
                "phase": "Pending",
                "qosClass": "BestEffort"
            }
````

We need to turn on KVM_EMULATION flag in the CSVs. See https://github.com/kubevirt/hyperconverged-cluster-operator/pull/321/files

The hco-e2e-aws job testing "make deploy" sets this flag. See line 77 in hack/deploy.sh.

We also need to update the latest tagged image in quay for hyperconverged-cluster-operator. The latest is a month old and doesn't contain support for the KVM_EMULATION flag in hyperconverged_controller.go.

**Comment by rwsu** [comment]
/test pj-rehearse

The upgrade test was successful on master and release-4.3. On release-4.4, there was an issue with cluster provisioning. Rerunning jobs.

**Pull request merged**
