### PR TITLE
Add RHEL-9 CI repo to the workers-rhel-repos step

### PR DESCRIPTION
**Pull request by gpei**
As requested in https://issues.redhat.com/browse/ART-10445, updated the RHEL-9 repos in the step accordingly.

### CODE REVIEW

**Comment by gpei** [comment]
cc @jianlinliu @yunjiang29 for the review

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-azure-ipi-proxy-workers-rhcos-rhel8-f7

**Comment by gpei** [comment]
@jianlinliu the 4.14-4.16 RHEL scaleup prow jobs are still pending on the backport of https://github.com/openshift/openshift-ansible/pull/12503/, it's failed for the incompatible of ansible-core 2.17, we can test with 4.17 jobs

**Comment by gpei** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-azure-ipi-proxy-workers-rhcos-rhel8-f14

**Comment by barbacbd** [comment]
@gpei can/should we change the name of the job to rhel-9 for aws jobs in another PR?

**Comment by gpei** [comment]
> can/should we change the name of the job to rhel-9 for aws jobs in another PR?

@barbacbd  Sure, let me try to update it after https://github.com/openshift/openshift-ansible/pull/12506 merged.

**Pull request merged**
