### PR TITLE
WIP: CORS-3578: Stop building libvirt-installer container image

### PR DESCRIPTION
**Pull request by sadasu**
As part of the removal of libvirt as a supported platform on OpenShift (https://issues.redhat.com/browse/OCPBUGS-35523), do not build the libvirt-installer image starting with the 4.16 release.

### CODE REVIEW

**Comment by sadasu** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.16-okd-e2e-agent-compact-ipv4

**Comment by r4f4** [comment]
/hold
We cannot do this just yet. The multi-arch team still depends on this image for their CI steps.

/cc @jaypoulz @tvardema

**Comment by r4f4** [comment]
@sadasu instead of removing the `libvirt-installer` image, we should just remove the libvirt terraform provider from the Installer.

**Comment by r4f4** [comment]
@sadasu and when the time comes to remove `libvirt-installer` make sure its contents are properly migrated to the `upi-installer` image, update the multi-arch steps to use the `upi-installer` and *then* remove `libvirt-installer`.

**Comment by sadasu** [comment]
> @sadasu instead of removing the `libvirt-installer` image, we should just remove the libvirt terraform provider from the Installer.

We are not ready to do that yet because Multi-arch has not completed their transition away from the libvirt terraform based install in their CI. So, this work specifically targets the release image because we know that is not in use.

**Comment by r4f4** [comment]
> > @sadasu instead of removing the `libvirt-installer` image, we should just remove the libvirt terraform provider from the Installer.
> 
> We are not ready to do that yet because Multi-arch has not completed their transition away from the libvirt terraform based install in their CI. So, this work specifically targets the release image because we know that is not in use.

NO, the image IS in use. Have you checked the release/ repo for usage?

**Comment by r4f4** [comment]
```
ci-operator/step-registry/ipi/conf/libvirt/ipi-conf-libvirt-ref.yaml
3:  from: libvirt-installer

ci-operator/step-registry/openshift/e2e/libvirt/conf/openshift-e2e-libvirt-conf-ref.yaml
3:  from: libvirt-installer

ci-operator/step-registry/openshift/e2e/gcp/libvirt/test/openshift-e2e-gcp-libvirt-test-ref.yaml
3:  from: libvirt-installer

ci-operator/step-registry/openshift/e2e/gcp/libvirt/setup/openshift-e2e-gcp-libvirt-setup-ref.yaml
3:  from: libvirt-installer

ci-operator/step-registry/openshift/e2e/gcp/libvirt/conf/openshift-e2e-gcp-libvirt-conf-ref.yaml
3:  from: libvirt-installer

ci-operator/step-registry/openshift/e2e/gcp/libvirt/cert-rotation/test/openshift-e2e-gcp-libvirt-cert-rotation-test-ref.yaml
3:  from: libvirt-installer

ci-operator/step-registry/openshift/e2e/gcp/libvirt/cert-rotation/setup/openshift-e2e-gcp-libvirt-cert-rotation-setup-ref.yaml
3:  from: libvirt-installer

ci-operator/step-registry/openshift/e2e/gcp/libvirt/cert-rotation/conf/openshift-e2e-gcp-libvirt-cert-rotation-conf-ref.yaml
3:  from: libvirt-installer

ci-operator/step-registry/openshift/e2e/gcp/crc/test/openshift-e2e-gcp-crc-test-ref.yaml
3:  from: libvirt-installer
```

**Comment by patrickdillon** [comment]
> and when the time comes to remove `libvirt-installer` make sure its contents are properly migrated to the `upi-installer` image, update the multi-arch steps to use the `upi-installer` and _then_ remove `libvirt-installer`.

This makes sense. We need to resolve the existing dependencies on `libvirt-installer` image. It would be good if we knew particular tests that we could rehearse to test these changes?

**Comment by sadasu** [comment]
> > and when the time comes to remove `libvirt-installer` make sure its contents are properly migrated to the `upi-installer` image, update the multi-arch steps to use the `upi-installer` and _then_ remove `libvirt-installer`.
> 
> This makes sense. We need to resolve the existing dependencies on `libvirt-installer` image. It would be good if we knew particular tests that we could rehearse to test these changes?

@r4f4 , @patrickdillon , this PR is not trying to remove all references to `libvirt-installer` image. I am aware of the multi-arch effort that is underway. I am trying to not include the libvirt-installer image into the CI release payload. I am moving this to WIP until I finish my experimentation.

**Comment by patrickdillon** [comment]
> @r4f4 , @patrickdillon , this PR is not trying to remove all references to `libvirt-installer` image. I am aware of the multi-arch effort that is underway. I am trying to not include the libvirt-installer image into the CI release payload. I am moving this to WIP until I finish my experimentation.

Ok. I think we're good in that regard, the libvirt installer image is not in the ci payload:

```
$ oc adm release info registry.ci.openshift.org/ocp/release:4.16.0-0.ci-2024-05-07-174928 | rg libvirt
  libvirt-machine-controllers                    sha256:f92e84acd409f5fc6a253f3141bca2fc11ec448eab535336fb691bbb3b5e3342
```

**Comment by zaneb** [comment]
As far as I know the libvirt-installer container image has never been included in the release payload.
This would stop building the image altogether, so it should be linked to [CORS-3222](https://issues.redhat.com/browse/CORS-3222) (or some new ticket that depends on it), not [CORS-3453](https://issues.redhat.com/browse/CORS-3453).

**Comment by sadasu** [comment]
/hold cancel

Already WIP

**Comment by sadasu** [comment]
Keeping it as WIP because I don't know how to take care of these references to the `libvirt-installer` image:
```
./gather/crc/gather-crc-ref.yaml:  from: libvirt-installer
./gather/snc/gather-snc-ref.yaml:  from: libvirt-installer
./ipi/conf/libvirt/ipi-conf-libvirt-ref.yaml:  from: libvirt-installer
./ipi/deprovision/deprovision/libvirt/ipi-deprovision-deprovision-libvirt-ref.yaml:  from: libvirt-installer
./ipi/deprovision/deprovision/libvirt/ipi-deprovision-deprovision-libvirt-ref.yaml:    that needs the libvirt-installer of the cluster, in order to destroy a tenant cluster.
./ipi/install/libvirt/install/ipi-install-libvirt-install-ref.yaml:  from: libvirt-installer
./ipi/libvirt/cleanup/ipi-libvirt-cleanup-ref.yaml:  from: libvirt-installer
./ipi/libvirt/cleanup/post/ipi-libvirt-cleanup-post-ref.yaml:  from: libvirt-installer
./ipi/libvirt/cleanup/pre/ipi-libvirt-cleanup-pre-ref.yaml:  from: libvirt-installer
./openshift/e2e/gcp/crc/test/openshift-e2e-gcp-crc-test-ref.yaml:  from: libvirt-installer
./openshift/e2e/gcp/libvirt/cert-rotation/conf/openshift-e2e-gcp-libvirt-cert-rotation-conf-ref.yaml:  from: libvirt-installer
./openshift/e2e/gcp/libvirt/cert-rotation/setup/openshift-e2e-gcp-libvirt-cert-rotation-setup-ref.yaml:  from: libvirt-installer
./openshift/e2e/gcp/libvirt/cert-rotation/test/openshift-e2e-gcp-libvirt-cert-rotation-test-ref.yaml:  from: libvirt-installer
./openshift/e2e/gcp/libvirt/conf/openshift-e2e-gcp-libvirt-conf-ref.yaml:  from: libvirt-installer
./openshift/e2e/gcp/libvirt/setup/openshift-e2e-gcp-libvirt-setup-ref.yaml:  from: libvirt-installer
./openshift/e2e/gcp/libvirt/test/openshift-e2e-gcp-libvirt-test-ref.yaml:  from: libvirt-installer
./openshift/e2e/libvirt/conf/openshift-e2e-libvirt-conf-ref.yaml:  from: libvirt-installer
./upi/conf/libvirt/agent/upi-conf-libvirt-agent-ref.yaml:  from: libvirt-installer
./upi/conf/libvirt/network/upi-conf-libvirt-network-ref.yaml:  from: libvirt-installer
./upi/conf/libvirt/upi-conf-libvirt-ref.yaml:  from: libvirt-installer
./upi/deprovision/libvirt/upi-deprovision-libvirt-ref.yaml:  from: libvirt-installer
./upi/gcp/nested/post/upi-gcp-nested-post-ref.yaml:  from: libvirt-installer
./upi/gcp/nested/pre/upi-gcp-nested-pre-ref.yaml:  from: libvirt-installer
./upi/install/libvirt/network/upi-install-libvirt-network-ref.yaml:  from: libvirt-installer
./upi/install/libvirt/upi-install-libvirt-ref.yaml:  from: libvirt-installer
./upi/libvirt/conf/upi-libvirt-conf-ref.yaml:  from: libvirt-installer
./upi/libvirt/deprovision/upi-libvirt-deprovision-ref.yaml:  from: libvirt-installer
./upi/libvirt/install/heterogeneous/upi-libvirt-install-heterogeneous-ref.yaml:  from: libvirt-installer
./upi/libvirt/install/install/upi-libvirt-install-install-ref.yaml:  from: libvirt-installer
./upi/libvirt/cleanup/post/upi-libvirt-cleanup-post-ref.yaml:  from: libvirt-installer
./upi/libvirt/cleanup/pre/upi-libvirt-cleanup-pre-ref.yaml:  from: libvirt-installer

```

**Comment by r4f4** [comment]
@sadasu We *cannot* remove `libvirt-installer`. CC @jaypoulz @tvardema

**Comment by tvardema** [comment]
@sadasu As noted in the ticket linked to this PR, the multiarch team heavily depends on the `libvirt-installer` image for Power and Z CI jobs in all releases.
The goal of this ticket ([MULTIARCH-4038](https://issues.redhat.com/browse/MULTIARCH-4038)) was to remove our dependency on `terraform` in the installer by doing a UPI deployment.  Again, we still heavily depend on the `libvirt-installer` image.

**Comment by zaneb** [comment]
@tvardema could whatever you're using the [libvirt image](https://github.com/openshift/installer/blob/main/images/libvirt/Dockerfile.ci) for be rolled into the [UPI image](https://github.com/openshift/installer/blob/main/images/installer/Dockerfile.upi.ci)?
It's expensive to build two.

**Pull request closed without merging**
