### PR TITLE
logging - remove rsyslog build and push jobs

### PR DESCRIPTION
**Pull request by richm**
get rid of references to rsyslog

### CODE REVIEW

**Comment by richm** [comment]
@jcantrill

**Comment by richm** [comment]
flake?
```
error: unable to read image registry.svc.ci.openshift.org/ci-op-1l31fv2c/stable@sha256:8a8ab2ea2dc1854ce99df2e8023fa5cf2a693715a71e188fa9ee0240324db87c: received unexpected HTTP status: 500 Internal Server Error
```

**Comment by richm** [comment]
why did this fail?
```
time="2019-10-29T15:37:04Z" level=error msg="Job failed" job=rehearse-5643-pull-ci-openshift-origin-aggregated-logging-release-4.4-images name=04f9a560-fa61-11e9-b28c-0a58ac10cd11 org=openshift pr=5643 repo=release state=failure type=presubmit
```
?

**Comment by richm** [comment]
flake
/retest

**Comment by richm** [comment]
flake
/retest

**Comment by richm** [comment]
flake
/retest

**Comment by richm** [comment]
flake
/retest

**Comment by richm** [comment]
flake
/retest

**Comment by richm** [comment]
flake
/retest

**Comment by richm** [comment]
flake
/retest

**Comment by richm** [comment]
flake
/retest

**Comment by richm** [comment]
@stevekuznetsov  Can we just force merge this change?

**Comment by richm** [comment]
flake
/retest

**Comment by richm** [comment]
flake
/retest

**Comment by richm** [comment]
` could not start the process: fork/exec hack/validate-prow-config.sh: no such file or directory ` ???

**Comment by richm** [comment]
```
error: could not resolve inputs: could not determine inputs for step [input:base]: could not resolve base image: imagestreamtags.image.openshift.io "4.5:base" not found
```
I did not add that . . .

please help

It is imperative that rsyslog is removed because its builds are breaking which is causing logging CI breakage which is preventing PRs from merging: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_origin-aggregated-logging/1785/pull-ci-openshift-origin-aggregated-logging-master-upgrade-full-integ-aws/204/build-log.txt

**Comment by richm** [comment]
> 4.5 issue is known and not from this PR

In order to get this merged as quickly as possible, should I edit the configs to use an image that actually exists now, so that the tests will pass?

**Comment by stevekuznetsov** [comment]
The rehearsal is not blocking and you can ignore it. Looks like since you are changing image mirroring config you need @smarterclayton to approve this

**Comment by richm** [comment]
> Looks like since you are changing image mirroring config you need @smarterclayton to approve this

/assign @smarterclayton

The change is to remove the rsyslog image from being pushed/mirrored (since we are no longer building it)

**Comment by richm** [comment]
please merge - can we please get rid of rsyslog????

**Comment by richm** [comment]
please merge - can we please get rid of rsyslog????

**Comment by richm** [comment]
`ci/prow/step-registry-shellcheck` fails due to
```
hack/validate-registry-commands.sh: line 6: find: command not found
hack/validate-registry-commands.sh: line 6: xargs: command not found
```
/retest

**Comment by richm** [comment]
please merge - can we please get rid of rsyslog????

**Comment by richm** [comment]
please merge

**Comment by richm** [comment]
please merge

**Comment by richm** [comment]
all tests pass - please review and merge

**Comment by petr-muller** [comment]
This needs @smarterclayton for the mirroring change.

**Comment by richm** [comment]
all tests pass - please review and merge

**Comment by richm** [comment]
Can we please get rid of rsyslog??????????
please review and merge
please review and merge
please review and merge
please review and merge
please review and merge
All work and no play makes Jack a dull boy.

**Comment by smarterclayton** [comment]
/hold

Did we never ship this?  And it’s just been in CI output since 4.1?  Has it been removed / never been in OSBS?

**Comment by richm** [comment]
> /hold
> 
> Did we never ship this?

We never shipped this.

> And it’s just been in CI output since 4.1?

Yes.

> Has it been removed / never been in OSBS?

@sosiouxme can you confirm ^^^?

**Comment by smarterclayton** [comment]
/hold cancel

You can check in ocp-build-data - if they have builds, delete them, then let’s make sure no one references it, and then we can purge the current built tags

/lgtm

**Pull request merged**
