### PR TITLE
USHIFT-3247: Add 4.16 jobs to testgrid

### PR DESCRIPTION
**Pull request by pacevedom**

### CODE REVIEW

**Comment by stbenjam** [comment]
Any reason not to include 4.17? If you're not part of the development release it won't get automatically carried forward durin branches (and to move to blocking it'll have be on 4.17, older releases typically don't take new blockers)

**Comment by pacevedom** [comment]
> Any reason not to include 4.17? If you're not part of the development release it won't get automatically carried forward during branching (and to move to blocking it'll have be on 4.17, older releases typically don't take new blockers)

Ah,this is because of using the config-brancher I think. We rely on it for periodics but we might need to use variants instead to get blocking going. Let me work it out and see if this PR should be extended/changed.

**Pull request closed without merging**
