### PR TITLE
updating operator-sdk to v1.37.0

### PR DESCRIPTION
**Pull request by acornett21**

### CODE REVIEW

**Comment by acornett21** [comment]
/pj-rehearse pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.13-e2e pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.13-images pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.17-e2e pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.17-images

**Comment by acornett21** [comment]
/pj-rehearse pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.17-e2e

**Review by bcrochet — APPROVED** [review]
/lgtm

**Pull request merged**
