### PR TITLE
Make hypershift e2e required in autoscaler

### PR DESCRIPTION
**Pull request by enxebre**
/hold

### CODE REVIEW

**Comment by csrwng** [comment]
/pj-rehearse pull-ci-openshift-kubernetes-autoscaler-master-e2e-hypershift

**Comment by elmiko** [comment]
given the low frequency of changes to the repo i think this is a good pre-submit test to run. i think we should consider adding a `skip_if_only_changed` clause to ensure that this test runs only when we change the cluster-autoscaler parts of the repository as i'm not sure we need to test if only a vertial-pod-autoscaler or docs change is added.

**Comment by enxebre** [comment]
rebased!
>given the low frequency of changes to the repo i think this is a good pre-submit test to run. i think we should consider adding a skip_if_only_changed clause to ensure that this test runs only when we change the cluster-autoscaler parts of the repository as i'm not sure we need to test if only a vertial-pod-autoscaler or docs change is added.

@elmiko is there a precedent I can use as example in this repo? otherwise I'll follow up in a different PR to do it all together for all mapi/capi jobs.

**Comment by elmiko** [comment]
> @elmiko is there a precedent I can use as example in this repo? otherwise I'll follow up in a different PR to do it all together for all mapi/capi jobs.

sadly, i think not, maybe it was wishful thinking on my part. happy to have it in a followup, but i think the current restriction on skipping if there is a docs change is good enough.

/lgtm

**Pull request merged**
