### PR TITLE
[INTEROP-7517] Update repo branch to `amq-broker-lpt`.

### PR DESCRIPTION
**Pull request by dfrazzette**
Changing test repo branch to fix _default broker version mismatch_ error.

Also expand the scenario to run on OCP 4.18, add FIPS test support, create `.config.prowgen` file to persist `slack_reporter` config list in periodics yaml.

### CODE REVIEW

**Comment by dfrazzette** [comment]
/pj-rehearse periodic-ci-rh-messaging-qe-claire-lpt-amq-broker-ocp4.17-lp-interop-amq-broker-interop-aws

**Comment by dfrazzette** [comment]
/pj-rehearse periodic-ci-rh-messaging-qe-claire-lpt-amq-broker-ocp4.17-lp-interop-amq-broker-interop-aws

**Comment by dfrazzette** [comment]
/pj-rehearse periodic-ci-rh-messaging-qe-claire-lpt-amq-broker-ocp4.17-lp-interop-amq-broker-interop-aws

**Comment by tlbueno** [comment]
LGTM, the fix for claire branch is correct.

**Comment by dfrazzette** [comment]
/pj-rehearse periodic-ci-rh-messaging-qe-claire-amq-broker-lpt-amq-broker-ocp4.18-lp-interop-amq-broker-interop-aws periodic-ci-rh-messaging-qe-claire-amq-broker-lpt-amq-broker-ocp4.18-lp-interop-amq-broker-interop-aws-fips

**Pull request merged**
