### PR TITLE
add resource-request-override.hypershift.openshift.io to hypershift jobs

### PR DESCRIPTION
**Pull request by flacatus**

### CODE REVIEW

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.2-integ-security-2-2 pull-ci-maistra-istio-maistra-2.3-integ-helm-2-3 pull-ci-maistra-istio-maistra-2.3-integ-telemetry-2-3 pull-ci-redhat-appstudio-application-service-main-application-service-e2e

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.2-integ-security-2-2

**Comment by jkopriva** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.2-integ-security-2-2

**Pull request closed without merging**
