### PR TITLE
[WIP]MGMT-14709: Force hostname format in dualstack job

### PR DESCRIPTION
**Pull request by carbonin**
Currently all our dualstack jobs on 4.13 and above are failing because the worker node CSRs are not getting auto-approved during the metal IPI install using devscripts.

This is happening because of a hostname mismatch between the CSR and the machine. The machine hostname originally came from the BMH which detected the hostname (something like `worker-0`) from before it had been set for the last time to the fqdn.

This patch explicitly tells dev-scripts to use the fqdn as the hostname so that the short name can never be set early an cause this confusion.

cc @paul-maidment @nmagnezi @omertuc

### CODE REVIEW

**Comment by carbonin** [comment]
/pj-rehearse periodic-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-ipv4v6-3masters-periodic

**Comment by carbonin** [comment]
/retest

Got further than before. Retesting to see if this one is a flake

**Comment by carbonin** [comment]
/pj-rehearse periodic-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-ipv4v6-3masters-periodic

**Comment by carbonin** [comment]
I was able to catch this job live and the issue was that we couldn't access quay.io from the spoke hosts. Seemingly this happened because they only had ipv6 addresses even though the network was also configured for ipv4.

I managed to pull the journal off of one of those hosts and will take a look at it next week.

**Comment by carbonin** [comment]
/pj-rehearse periodic-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-ipv4v6-3masters-periodic

**Comment by carbonin** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp

**Comment by carbonin** [comment]
I don't think we'll want to change this for all jobs, but I made the change this way for now so we could test the other jobs with this to see if it's truly necessary.

**Comment by carbonin** [comment]
/pj-rehearse periodic-ci-openshift-assisted-service-release-ocm-2.7-e2e-ai-operator-ztp-ipv4v6-3masters-periodic

**Comment by carbonin** [comment]
/pj-rehearse periodic-ci-openshift-assisted-service-release-ocm-2.6-e2e-ai-operator-ztp-periodic periodic-ci-openshift-assisted-service-release-ocm-2.7-e2e-ai-operator-ztp-periodic periodic-ci-openshift-assisted-service-release-ocm-2.8-e2e-ai-operator-ztp-periodic

**Comment by carbonin** [comment]
/pj-rehearse periodic-ci-openshift-assisted-service-release-ocm-2.8-e2e-ai-operator-ztp-periodic

**Comment by carbonin** [comment]
/pj-rehearse periodic-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-disconnected-periodic

**Comment by carbonin** [comment]
/pj-rehearse periodic-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-ipv4v6-3masters-periodic

**Comment by carbonin** [comment]
This doesn't seem to break anything and it moves the dual stack jobs a bit further along (failing at discovering agents rather than dev-scripts setup)

@osherdp @nmagnezi do you think we should merge this first and I'll continue to debug the agents issue after or just work on it here since all the dual-stack jobs will continue to fail?

**Comment by carbonin** [comment]
Also @osherdp @nmagnezi if there are any other rehearsals you think we should run feel free to trigger some

**Comment by carbonin** [comment]
/pj-rehearse periodic-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-ipv4v6-3masters-periodic

**Comment by carbonin** [comment]
/pj-rehearse periodic-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-ipv4v6-3masters-periodic

**Comment by carbonin** [comment]
/pj-rehearse periodic-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-ipv4v6-3masters-periodic

**Comment by osherdp** [comment]
> This doesn't seem to break anything and it moves the dual stack jobs a bit further along (failing at discovering agents rather than dev-scripts setup)
> 
> @osherdp @nmagnezi do you think we should merge this first and I'll continue to debug the agents issue after or just work on it here since all the dual-stack jobs will continue to fail?

I don't see a difference between merging & waiting for periodic results to rehearsing it here, except the later allows you access to the environment and also allows triggering the jobs
So I think it's better to get to the root-cause in this scope to make the loop shorter and leave the git history cleaner (in case we'll need to revert or change the configuration)

**Comment by carbonin** [comment]
I agree @osherdp especially since the original solution doesn't seem to be the way to go at this point.

I'd like to fully understand a fix before merging anything.

**Comment by carbonin** [comment]
/pj-rehearse periodic-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-ipv4v6-3masters-periodic

**Comment by carbonin** [comment]
/pj-rehearse periodic-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-ipv4v6-3masters-periodic

**Comment by carbonin** [comment]
/pj-rehearse periodic-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-ipv4v6-3masters-periodic

**Comment by carbonin** [comment]
Failed to pull the operator catalog image. I suppose that's because it isn't mirrored.

```
Failed to pull image "registry.redhat.io/redhat/redhat-operator-index:v4.12": rpc error: code = Unknown desc = unable to retrieve auth token: invalid username/password: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication
```

I think the only way we'd deal with this correctly is if we ran this as a disconnected job.

But then we'd be mirroring all the images for the hub, forcing virtual media boot, and also fully running disconnected just so we can set the provisioning network to `Managed` so that the hosts get a consistent hostname when running in dual-stack.

Seems like a bit much even if it works. I'm wondering if we go back to trying to figure out a more "proper" fix?

**Comment by carbonin** [comment]
/pj-rehearse periodic-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-ipv4v6-3masters-periodic

**Comment by carbonin** [comment]
/pj-rehearse periodic-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-ipv4v6-3masters-periodic

**Comment by carbonin** [comment]
/pj-rehearse periodic-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-ipv4v6-3masters-periodic

**Comment by carbonin** [comment]
/pj-rehearse periodic-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-ipv4v6-3masters-periodic

**Comment by carbonin** [comment]
/pj-rehearse periodic-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-ipv4v6-3masters-periodic

**Comment by carbonin** [comment]
/pj-rehearse periodic-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-ipv4v6-3masters-periodic

**Comment by carbonin** [comment]
Closing this for now as there doesn't seem to be a simple way around the failure.

We'll need to wait for https://issues.redhat.com/browse/OCPBUGS-14933 to be resolved.

**Pull request closed without merging**
