### PR TITLE
MGMT-16961: add IP change

### PR DESCRIPTION
**Pull request by eranco74**

### CODE REVIEW

**Comment by eranco74** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-baremetalds-sno-recert-cluster-rename
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-baremetalds-sno-recert-cluster-rename

**Comment by eranco74** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-baremetalds-sno-recert-cluster-rename

**Comment by eranco74** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-baremetalds-sno-recert-cluster-rename

**Comment by eranco74** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-baremetalds-sno-recert-cluster-rename

**Comment by eranco74** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-baremetalds-sno-recert-cluster-rename

**Comment by eranco74** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-baremetalds-sno-recert-cluster-rename

**Comment by eranco74** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-baremetalds-sno-recert-cluster-rename

**Comment by eranco74** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-baremetalds-sno-recert-cluster-rename

**Comment by eranco74** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-baremetalds-sno-recert-cluster-rename

**Comment by eranco74** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-baremetalds-sno-recert-cluster-rename

**Comment by eranco74** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-baremetalds-sno-recert-cluster-rename

**Comment by eranco74** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-baremetalds-sno-recert-cluster-rename

**Comment by eranco74** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-baremetalds-sno-recert-cluster-rename

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-baremetalds-sno-recert-cluster-rename

**Comment by eranco74** [comment]
/pj-rehearse pull-ci-rh-ecosystem-edge-recert-main-baremetalds-sno-recert-cluster-rename

**Pull request merged**
