### PR TITLE
sriov: add e2e-openstack-nfv-config-drive jobs

### PR DESCRIPTION
**Pull request by EmilienM**
Add `e2e-openstack-nfv-config-drive` jobs so we can test when workers
have config-drive enabled.

### CODE REVIEW

**Comment by EmilienM** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-master-e2e-openstack-nfv-config-drive
this should fail because of https://issues.redhat.com/browse/OCPBUGS-41829 but that's OK I have a fix upstream and I need this PR to test its backport to OCP.

**Comment by EmilienM** [comment]
````
2024-09-11T21:59:23.13496437Z	INFO	openstack/openstack.go:113	reading OpenStack meta_data from config-drive
2024-09-11T21:59:23.134987691Z	INFO	openstack/openstack.go:115	getting OpenStack meta_data from metadata server
2024/09/11 21:59:23 [DEBUG] GET http://169.254.169.254/openstack/2018-08-27/meta_data.json
2024-09-11T21:59:24.102079138Z	INFO	openstack/openstack.go:115	getting OpenStack network_data from metadata server
2024/09/11 21:59:24 [DEBUG] GET http://169.254.169.254/openstack/2018-08-27/network_data.json
````

so config drive didn't work, this confirm the bug.
config drive enabled: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/56589/rehearse-56589-pull-ci-openshift-sriov-network-operator-master-e2e-openstack-nfv-config-drive/1833960574656974848/artifacts/e2e-openstack-nfv-config-drive/openstack-gather/artifacts/openstack_nodes.log

**Review by SchSeba — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
