### PR TITLE
SPLAT-1232: aws/upi-installer: fetch cloudformation template from github PR

### PR DESCRIPTION
**Pull request by mtulio**
Introduce fetch CloudFormation templates fetch from custom URLs in presubmit
and periodic jobs.

The URL is built based on the JOB_SPEC, and it tries to fetch from PR
URL, instead of directly from the master branch, allowing testing of the workflows
`*-aws-ovn-shared-vpc-*`.

References:

- alternative of https://github.com/openshift/release/pull/45680
- option 2 discussed in https://redhat-internal.slack.com/archives/C68TNFWA2/p1699617322801979
- used in: https://github.com/openshift/release/pull/45158

### CODE REVIEW

**Comment by mtulio** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-aws-ovn-shared-vpc-localzones

**Comment by mtulio** [comment]
/pj-rehease pull-ci-openshift-installer-release-4.14-e2e-aws-ovn-shared-vpc

**Comment by mtulio** [comment]
/pj-rehease pull-ci-openshift-installer-release-4.14-e2e-aws-ovn-shared-vpc

**Comment by mtulio** [comment]
/pj-rehease pull-ci-openshift-installer-release-4.14-e2e-aws-ovn-shared-vpc

**Comment by mtulio** [comment]
/pj-rehease periodic-ci-openshift-release-master-nightly-4.15-e2e-aws-ovn-shared-vpc-localzones

**Comment by mtulio** [comment]
/pj-rehease pull-ci-openshift-installer-master-e2e-aws-ovn-shared-vpc-localzones

**Comment by mtulio** [comment]
/pj-rehease pull-ci-openshift-installer-master-e2e-aws-ovn-shared-vpc

**Comment by mtulio** [comment]
It is not ready for review yet, converted to regular PR because bot isn’t responding to rehearse commands, trying to figure out why

**Comment by mtulio** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-aws-ovn-shared-vpc

**Comment by mtulio** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-aws-ovn-shared-vpc

**Comment by mtulio** [comment]
Running the last failed rehearsals with more debug:
/pj-rehearse pull-ci-openshift-installer-release-4.16-e2e-aws-ovn-shared-vpc-localzones

**Comment by mtulio** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.16-e2e-aws-ovn-shared-vpc-localzones

**Comment by mtulio** [comment]
/pj-rehease pull-ci-openshift-installer-release-4.14-e2e-aws-ovn-shared-vpc

**Comment by mtulio** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.16-altinfra-e2e-aws-ovn-shared-vpc-localzones

**Comment by mtulio** [comment]
Based in the last `/pj-rehearse`:
/pj-rehearse ack

Keep `/hold` until https://github.com/openshift/release/pull/45158 is merged.

**Comment by mtulio** [comment]
Based on the Slack discussion, this is the initial proposal to improve the CloudFormation template fetching from installer repo from different jobs/builds:
/assgin @r4f4 @rvanderp3

**Comment by mtulio** [comment]
/pj-rehease periodic-ci-openshift-release-master-nightly-4.15-e2e-aws-ovn-shared-vpc-localzones

**Comment by r4f4** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-aws-ovn-shared-vpc-localzones pull-ci-openshift-installer-release-4.11-e2e-aws-shared-vpc pull-ci-openshift-installer-release-4.15-e2e-aws-ovn-shared-vpc

**Comment by mtulio** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.15-e2e-aws-ovn-shared-vpc

**Comment by mtulio** [comment]
/pj-rehearse pull-ci-openshift-installer-master-altinfra-e2e-aws-ovn-shared-vpc-wavelengthzones

**Pull request closed without merging**
