### PR TITLE
OCPQE-11259: Add build info for RELEASE_IMAGE_LATEST which is used in upgrade

### PR DESCRIPTION
**Pull request by liangxia**

### CODE REVIEW

**Comment by liangxia** [comment]
/unhold

@dis016  Let's get the `RELEASE_IMAGE_LATEST` added to upgrade first. We can use a follow up to deal with `RELEASE_IMAGE_TARGET`.

**Comment by dis016** [comment]
@liangxia sure, Thank you.

**Comment by dis016** [comment]
LGTM

**Pull request merged**
