### PR TITLE
Update OCM/SubM fast-forward to release-2.5 branch

### PR DESCRIPTION
**Pull request by dfarrell07**
Change the branch kept in sync with main from release-2.4 to
release-2.5, to allow development to continue on the main branch while
the release-2.4 branch is code-frozen.

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

**Comment by dfarrell07** [comment]
We need to create the submariner-addon `release-2.5` branch.

**Comment by skitt** [comment]
> We need to create the submariner-addon `release-2.5` branch.

Done!

**Pull request merged**
