### PR TITLE
promtail-hosted: use promtail 2.7.4

### PR DESCRIPTION
**Pull request by vrutkovs**
Bump promtail to latest stable

### CODE REVIEW

**Comment by dgoodwin** [comment]
Is the use of your repo intentional? If so feel free to cancel hold.

/approve
/lgtm
/hold

**Comment by vrutkovs** [comment]
Yeah, we have to use my repo for now, until https://quay.io/repository/openshift-cr/promtail is updated

/hold cancel
/pj-rehearse ack

**Comment by vrutkovs** [comment]
/hold cancel

Updated to use openshift-logging org

**Comment by atiratree** [comment]
hi @dgoodwin @vrutkovs,  this broke the CI due to an invalid tag: can you please take a look at and tag https://github.com/openshift/release/pull/37909?

**Comment by jeffdyoung** [comment]
@dgoodwin @vrutkovs Can we revert this change? quay.io/openshift-logging/promtail is not build for arm64.
cc: @deepsm007 @SaravanaStorageNetwork

**Comment by dgoodwin** [comment]
I think so yes, the fix didn't even work.

**Comment by vrutkovs** [comment]
Sure, feel free to revert it (and https://github.com/openshift/release/pull/37909 too)

**Pull request merged**
