### PR TITLE
OCPQE-25316 enable 4.13 for qe-release-gate-test

### PR DESCRIPTION
**Pull request by rioliu-rh**
add 4.13 to supported list

### CODE REVIEW

**Review by jhuttana — COMMENTED** [review]
/lgtm

**Comment by rioliu-rh** [comment]
/pj-rehearse periodic-ci-openshift-release-tests-master-qe-release-gate-test

**Comment by rioliu-rh** [comment]
/pj-rehearse periodic-ci-openshift-release-tests-master-qe-release-gate-test

**Comment by rioliu-rh** [comment]
found an issue in previous rehearse job, it's fixed in https://github.com/openshift/release-tests/pull/287

**Pull request merged**
