### PR TITLE
[HCP|KV|Disconnected] Use oc-mirror v2 to mirror the RHCOS container …

### PR DESCRIPTION
**Pull request by tiraboschi**
…disk image

### CODE REVIEW

**Comment by tiraboschi** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.17-periodics-e2e-kubevirt-metal-ovn-disconnected

**Comment by tiraboschi** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-mce-e2e-kubevirt-metal-ovn-disconnected

**Comment by tiraboschi** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-mce-e2e-kubevirt-metal-ovn-disconnected

**Comment by tiraboschi** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.17-periodics-e2e-kubevirt-metal-ovn-disconnected

**Comment by tiraboschi** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.17-periodics-e2e-kubevirt-metal-ovn-disconnected

**Comment by tiraboschi** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-mce-e2e-kubevirt-metal-ovn-disconnected

**Comment by tiraboschi** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-mce-e2e-kubevirt-metal-ovn-disconnected

**Comment by tiraboschi** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.17-periodics-e2e-kubevirt-metal-ovn-disconnected

**Comment by tiraboschi** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-mce-e2e-kubevirt-metal-ovn-disconnected

**Comment by tiraboschi** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-mce-e2e-kubevirt-metal-ovn-disconnected

**Comment by tiraboschi** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.17-periodics-e2e-kubevirt-metal-ovn-disconnected

**Comment by tiraboschi** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.16-periodics-mce-e2e-kubevirt-metal-ovn-disconnected

**Review by davidvossel — COMMENTED** [review]
/lgtm
/approve

**Comment by tiraboschi** [comment]
the conflict was just in the job file
/pj-rehearse ack

**Pull request merged**
