### PR TITLE
fix: package name

### PR DESCRIPTION
**Pull request by zdtsw**
- also use rhoai namespace , channel
ref: https://issues.redhat.com/browse/RHOAIENG-14768

### CODE REVIEW

**Comment by zdtsw** [comment]
/pj-rehearse pull-ci-opendatahub-io-opendatahub-operator-rhoai-opendatahub-operator-e2e

**Comment by zdtsw** [comment]
/pj-rehearse pull-ci-opendatahub-io-opendatahub-operator-rhoai-opendatahub-operator-e2e

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

**Comment by VaishnaviHire** [comment]
/pj-rehearse pull-ci-opendatahub-io-opendatahub-operator-rhoai-opendatahub-operator-e2e

**Pull request merged**
