### PR TITLE
Switch dev06 to dev02

### PR DESCRIPTION
**Pull request by chenz4027**
Signed-off-by: Maggie Chen <magchen@redhat.com>

### CODE REVIEW

**Comment by KevinFCormier** [comment]
@ray-harris Will we need a review from you or someone else as well since we are adding a new secret for ClusterPool access to the step-registry?

**Comment by ray-harris** [comment]
@KevinFCormier Anyone from the CICD squad can approve the PR, but the secret must be in Vault before the PR is merged. If it's not there, the workflow won't work for anyone.

**Comment by KevinFCormier** [comment]
The secret is there:
image

**Comment by chenz4027** [comment]
@ray-harris Yep it's defined in the Vault
image

**Pull request merged**
