### PR TITLE
Deprecating pvc-new-pod scenario

### PR DESCRIPTION
**Pull request by shahsahil264**
As per our discussion on slack, I am deprecating the pvc-new-pod scenario

@paigerube14 @chaitanyaenr

### CODE REVIEW

**Review by chaitanyaenr — APPROVED** [review]
/lgtm

**Comment by paigerube14** [comment]
should we take out the actual code/folder as well?

**Comment by shahsahil264** [comment]
> should we take out the actual code/folder as well?

I feel we should keep it for future use ? 
What are your thoughts @chaitanyaenr

**Pull request merged**
