### PR TITLE
mco: Update to use rhel-coreos in master+4.14

### PR DESCRIPTION
**Pull request by cgwalters**
Since https://github.com/openshift/machine-config-operator/pull/3596 merged.

### CODE REVIEW

**Comment by sdodson** [comment]
etcd member unhealthy seems unlikely to be associated with this change
/pj-rehearse pull-ci-openshift-machine-config-operator-release-4.14-e2e-gcp-op

**Comment by sinnykumari** [comment]
MCO logs looks fine, so giving another try
/pj-rehearse pull-ci-openshift-machine-config-operator-release-4.14-e2e-gcp-op

**Comment by sdodson** [comment]
Probably depends on https://github.com/openshift/release/pull/37117
once more for good measure
/pj-rehearse pull-ci-openshift-machine-config-operator-release-4.14-e2e-gcp-op

**Pull request merged**
