### PR TITLE
[WIP] Adding support for dualstack clusters in Azure

### PR DESCRIPTION
**Pull request by bradmwilliams**

### CODE REVIEW

**Comment by aojea** [comment]
is this triggering some dual stack job so we can verify it?

**Comment by bradmwilliams** [comment]
I had triggered the following job with these changes, plus the cluster-bot change to enable it:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-azure-modern/1466125280308367360

Unfortunately, the job failed because the cluster never became available.

**Comment by bradmwilliams** [comment]
/close
This can be re-opened if necessary

**Pull request closed without merging**
