### PR TITLE
Configure openshift and kubernetes jobs running using PSI

### PR DESCRIPTION
**Pull request by prietyc123**
Configuration is related to https://github.com/openshift/odo/pull/4063 and https://github.com/openshift/odo/pull/4401

### CODE REVIEW

**Comment by prietyc123** [comment]
Once both pr gets merged we need to merge this one. Meanwhile holding this pr.

/hold

**Comment by mohammedzee1000** [comment]
Rebase required @prietyc123

**Review by mohammedzee1000 — APPROVED** [review]
Codewise looks good, but needs a rebase. Will lgtm after rebase is done

**Comment by mohammedzee1000** [comment]
oops forgot approval was taken as lgtm
/lgtm cancel

**Comment by prietyc123** [comment]
Holding this pr until https://github.com/openshift/odo/pull/4401 gets merged.

/hold

**Review by mohammedzee1000 — APPROVED** [review]
/lgtm

**Pull request merged**
