### PR TITLE
Run knative-serving on 4.1

### PR DESCRIPTION
**Pull request by mgencur**

### CODE REVIEW

**Comment by mgencur** [comment]
/hold 
Need to investigate the failures.

**Comment by mgencur** [comment]
Closing due to https://issues.jboss.org/browse/MAISTRA-410
Will re-open when this issue is fixed. Knative fails to install right now.

**Comment by mgencur** [comment]
Re-opening for testing purposes. I want to test a workaround with loading kernel modules on demand.

**Comment by markusthoemmes** [comment]
@mgencur I think this is outdated?

**Comment by mgencur** [comment]
Yeah.

**Pull request closed without merging**
