### PR TITLE
add-vsphere-ipi-ovn-migration-sdn-workflow

### PR DESCRIPTION
**Pull request by weliang1**
Same PR https://github.com/openshift/release/pull/37442 keep failing.

This PR is for https://issues.redhat.com/browse/NP-639: Support for ovn-kubernetes to openshift-sdn CNI Migration

Comparing sdn2ovn migration, we do not think many customers will do the ovn2sdn migration, so one workflow testing should be enough.

The reason to pick vsphere cluster is because most customer OCP clusters are running in vsphere.

This PR fixed all the issues mentioned in PR #37295
@liangxia @zhaozhanqi PTAL

### CODE REVIEW

**Comment by weliang1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-vsphere-ipi-ovn-migration-sdn-p2-f7

**Comment by weliang1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-vsphere-ipi-ovn-migration-sdn-p2-f7

**Comment by weliang1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-vsphere-ipi-ovn-migration-sdn-p2-f7

**Comment by weliang1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-vsphere-ipi-ovn-migration-sdn-p2-f7

**Comment by weliang1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-vsphere-ipi-ovn-migration-sdn-p2-f7

**Comment by weliang1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-vsphere-ipi-ovn-migration-sdn-p2-f7

**Comment by weliang1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-vsphere-ipi-ovn-migration-sdn-p2-f7

**Comment by weliang1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-vsphere-ipi-ovn-migration-sdn-p2-f7

**Comment by weliang1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-vsphere-ipi-ovn-migration-sdn-p2-f7

**Comment by weliang1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-vsphere-ipi-ovn-migration-sdn-p2-f7

**Comment by weliang1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-vsphere-ipi-ovn-migration-sdn-p2-f7

**Comment by weliang1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-vsphere-ipi-ovn-migration-sdn-p2-f7

**Comment by weliang1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-vsphere-ipi-ovn-migration-sdn-p2-f7

**Comment by zhaozhanqi** [comment]
above job failed due to one case
```
      [36m[33m[02:31:40] INFO> Shell Commands: oc debug  --kubeconfig=/alabama/workdir/vsphere-ipi-ovn-migration-sdn-p2-f7-cucushift-upgrax/ocp4_admin.kubeconfig -n prj-vsphere-ipi-ovn-migration-sdn-p2-f7-cucushift-upgrax-gns9 --image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:02841b726f9f5f33323f1f7947fdb6fff751458c958e6db49949279105bbc45b node/ci-op-0ify7zn7-96e53-88dm6-master-0 -- chroot /host/ bash -c cd\ \'/tmp/workdir/vsphere-ipi-ovn-migration-sdn-p2-f7-cucushift-upgrax\''[0m
      [36m'cat\ /etc/kubernetes/kubelet.conf[0m[0m
      [36m[0m
      [36mSTDERR:[0m
      [36mStarting pod/ci-op-0ify7zn7-96e53-88dm6-master-0-debug ...[0m
      [36mTo use host binaries, run `chroot /host`[0m
      [36m[0m
      [36mRemoving debug pod ...[0m
      [36mError from server (BadRequest): container "container-00" in pod "ci-op-0ify7zn7-96e53-88dm6-master-0-debug" is waiting to start: ContainerCreating[0m[0m
      [36m[33m[02:31:41] INFO> Exit Status: 1[0m[0m
    [31mThen the step should [31m[1msucceed[0m[0m[31m[90m                                        # features/step_definitions/common.rb:4[0m[0m
[31m      the step failed (RuntimeError)[0m
```

**Comment by zhaozhanqi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-vsphere-ipi-ovn-migration-sdn-p2-f7

**Comment by zhaozhanqi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-vsphere-ipi-ovn-migration-sdn-p2-f7

**Pull request closed without merging**
