### PR TITLE
Renaming ml-pipelines repo to data-science-pipelines

### PR DESCRIPTION
**Pull request by DharmitD**

### CODE REVIEW

**Comment by LaVLaS** [comment]
@DharmitD Did you intend to commit the new files for the `modelmesh-serviing` prowConfig?

**Comment by LaVLaS** [comment]
@DharmitD The operator is failing because you are referencing a [default-configs](https://github.com/opendatahub-io/data-science-pipelines/tree/master/manifests/opendatahub/overlays/default-configs) overlay in data-science-pipelines that is not a valid kustomize manifests (there is no kustomization.yaml file). I assume that you are replicating the functionality that was updated in `default-configs` overlay in [odh-manifests](https://github.com/opendatahub-io/odh-manifests/blob/master/data-science-pipelines/overlays/default-configs/kustomization.yaml)

**Comment by LaVLaS** [comment]
/lgtm

@DharmitD You'll probably need @anishasthana @rimolive @gmfrasca to `/lgtm` for this to merge

**Review by anishasthana — APPROVED** [review]
/lgtm

**Review by gmfrasca — COMMENTED** [review]
/lgtm

**Pull request merged**
