### PR TITLE
ocm: add new repo bailer

### PR DESCRIPTION
**Pull request by cameronmwall**

### CODE REVIEW

**Comment by ray-harris** [comment]
@cameronmwall Let me see about getting the `tar` command added to the builder image. I thought it would have been there.

**Comment by ray-harris** [comment]
@cameronmwall The image you're building is based on `ubi-minimal:8`, which doesn't have tar (or yum) installed.

ubi-minimal:8 uses `microdnf` to install packages instead of `yum`. So you'll need to use that to install tar and the other packages you need. You can also switch to `ubi:8` as that uses `yum` and already has `tar` installed.

**Comment by cameronmwall** [comment]
@ray-harris ah. That explains it. Thanks for catching

**Pull request merged**
