### PR TITLE
Remove duplicated pipeline images

### PR DESCRIPTION
**Pull request by bbguimaraes**
As identified with the new validation added in:

https://github.com/openshift/ci-tools/pull/2062

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/2062/pull-ci-openshift-ci-tools-master-breaking-changes/1405213857000984576

and documented in:

https://github.com/openshift/ci-docs/pull/161

/hold

I won't have time to deploy and verify today.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
What about these is duplicated?

**Comment by bbguimaraes** [comment]
@stevekuznetsov: this is the validation message we (will) [generate](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/2062/pull-ci-openshift-ci-tools-master-breaking-changes/1405213857000984576):

```
images[0]: duplicate image name 'elasticsearch-proxy' (previously defined by field 'base_images[elasticsearch-proxy]')
```

And for `sriov-network-operator`:

```
images[2]: duplicate image name 'sriov-network-webhook' (previously defined by field 'base_images[sriov-network-webhook]')
```

**Comment by stevekuznetsov** [comment]
..ah


/lgtm
/approve

**Pull request merged**
