### PR TITLE
Add MDR relese-0.3 configs

### PR DESCRIPTION
**Pull request by clobrano**

### CODE REVIEW

**Comment by clobrano** [comment]
/pj-rehearse pull-ci-medik8s-machine-deletion-remediation-release-0.3-4.14-test

**Comment by clobrano** [comment]
/pj-rehearse pull-ci-medik8s-machine-deletion-remediation-release-0.3-4.14-test /pj-rehearse pull-ci-medik8s-machine-deletion-remediation-release-0.3-4.14-images /pj-rehearse pull-ci-medik8s-machine-deletion-remediation-release-0.3-4.14-ci-bundle-my-bundle /pj-rehearse pull-ci-medik8s-machine-deletion-remediation-release-0.3-4.14-openshift-e2e

**Comment by slintes** [comment]
/pj-rehearse pull-ci-medik8s-machine-deletion-remediation-release-0.3-4.14-unit

**Pull request merged**
