### PR TITLE
Jenkins - expand rosa-hypershift testing to OCP 4.12

### PR DESCRIPTION
**Pull request by ascerra**

### CODE REVIEW

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-openshift-jenkins-release-4.12-jenkins-hypershift4.12-aws-jenkins-lp-rosa-hypershift-412

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-openshift-jenkins-release-4.12-jenkins-hypershift4.12-aws-jenkins-lp-rosa-hypershift-412

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
