### PR TITLE
add techpreview gate to etcd recovery job

### PR DESCRIPTION
**Pull request by tjungblu**

### CODE REVIEW

**Comment by tjungblu** [comment]
/pj-rehearse pull-ci-openshift-origin-master-e2e-aws-etcd-recovery

**Comment by hasbro17** [comment]
@bparees Would appreciate if you could take a look and approve.
We're enabling the techpreview features so that our etcd recovery jobs can test out the new etcd backup APIs
https://github.com/openshift/api/blob/master/config/v1/feature_gates.go#L295
https://github.com/openshift/api/pull/1482

**Comment by tjungblu** [comment]
Thank you, both! 

/pj-rehearse ack

**Pull request merged**
