### PR TITLE
MCO-562: mco: make e2e-gcp-op-single-node test required and skip running resource heavy tests on doc related changes

### PR DESCRIPTION
**Pull request by sinnykumari**
we had enough run of gcp-op-single-node run on master branch and looking at test run https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-machine-config-operator-master-e2e-gcp-op-single-node?buildId=1673685709745033216 , looks ok to make it required as pattern matches with gcp-op test.

Also,  skip running bootstrap-unit, e2e-hypershift and e2e-okd-scos-e2e-aws-ovn test for doc related changes.

### CODE REVIEW

**Comment by sinnykumari** [comment]
Also, using same PR to make skip running bootstrap-unit, e2e-hypershift and e2e-okd-scos-e2e-aws-ovn test for doc related changes.

**Comment by djoshy** [comment]
Thanks for making these changes, @sinnykumari ! Looks goods to me, I was just a little confused with the difference between always_run and optional. Does always_run just cause the test to run, no matter what files are changed?

**Comment by sinnykumari** [comment]
`always_run` means it will run on all PRs and `optional` tells whether this tests is Required or not. If we set option to false, that means it will be a blocking test on MCO PR whenever it runs

**Comment by djoshy** [comment]
Gotcha makes sense!
/lgtm

**Pull request merged**
