### PR TITLE
Sort the configs/jobs and fix cron entries

### PR DESCRIPTION
**Pull request by liangxia**
Changes in the PR,
1. Sort the configs/jobs
2. Fix several cron entries

### CODE REVIEW

**Comment by jianli-wei** [comment]
@liangxia May I ask why we need them sorted? Thanks!

**Comment by liangxia** [comment]
> May I ask why we need them sorted? Thanks!

When comparing between different versions/architectures, sorted configs are more easier to diff.

**Review by jianli-wei — APPROVED** [review]

**Comment by liangxia** [comment]
@jianli-wei E.g, it helps us find issue like this, https://github.com/openshift/release/pull/36208

**Pull request merged**
