### PR TITLE
OSASINFRA-3464 - Loading proxy env for disconnected or otherwise unreachable environments

### PR DESCRIPTION
**Pull request by MiguelCarpio**
For disconnected or otherwise unreachable environments, we want to have steps use an HTTP(S) proxy to reach the API server. This proxy configuration file should export HTTP_PROXY, HTTPS_PROXY, and NO_PROXY environment variables, as well as their lowercase equivalents (note that libcurl doesn't recognize the uppercase variables).

### CODE REVIEW

**Comment by MiguelCarpio** [comment]
Hey folks, I want to use the ipi-conf-inframachineset step here [OSASINFRA-3426 - Adding ShiftStack ingress-perf Periodic CI Job](https://github.com/openshift/release/pull/52342), but I realized that I have a routing issue because the step pod can't reach the API server. Loading the proxy environment is needed.

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.16-upgrade-from-stable-4.15-e2e-aws-sdn-upgrade-infra

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.15-upgrade-from-stable-4.14-e2e-aws-sdn-upgrade-infra, periodic-ci-openshift-release-master-ci-4.9-upgrade-from-stable-4.8-e2e-aws-upgrade-infra

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.15-upgrade-from-stable-4.14-e2e-aws-sdn-upgrade-infra

**Comment by MiguelCarpio** [comment]
Hey folks, @DennisPeriquet @xueqzhan, I believe the failed test was caused by another error, regardless of this PR. 

` job name "aws-sdn-upgrade-infra" has mismatched network type in name (expected 'ovn', found 'sdn')`

What do you think? Could we approve it?

**Comment by DennisPeriquet** [comment]
> Hey folks, @DennisPeriquet @xueqzhan, I believe the failed test was caused by another error, regardless of this PR.
> 
> ` job name "aws-sdn-upgrade-infra" has mismatched network type in name (expected 'ovn', found 'sdn')`
> 
> What do you think? Could we approve it?

If your rehearsal jobs went as expected besides the renaming problem, you should be good to go.  I don't believe failed rehearsal jobs gate a merge.

**Comment by elmiko** [comment]
change looks good to me, and based on the comments it seems like this is not causing the name issue.

/lgtm
/approve

**Pull request merged**
