### PR TITLE
Sync fedora:29 to build farm

### PR DESCRIPTION
**Pull request by hongkailiu**
Follow up https://coreos.slack.com/archives/CBN38N3MW/p1598369434209500

/cc @jcaianirh @alvaroaleman

### CODE REVIEW

**Comment by alvaroaleman** [comment]
This is wrong, this doesn't belong into the static config: https://coreos.slack.com/archives/CBN38N3MW/p1598371829214800?thread_ts=1598369434.209500&cid=CBN38N3MW

The rehearsal is correctly trying to import it, that times out. That is the bug. This doesn't belong into the static config at all.
/close

**Comment by hongkailiu** [comment]
See https://github.com/openshift/ci-tools/pull/1165

**Pull request closed without merging**
