### PR TITLE
Rename machine-api-provider-openstack

### PR DESCRIPTION
**Pull request by mdbooth**
Promote the MAPO image under the same name as the downstream payload tag.

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
I believe the `openstack-machine-api-provider` name is correct, at least this is what we were requested to change to in https://github.com/openshift/release/pull/24933#issuecomment-1014653123

**Comment by mdbooth** [comment]
> I believe the `openstack-machine-api-provider` name is correct, at least this is what we were requested to change to in [#24933 (comment)](https://github.com/openshift/release/pull/24933#issuecomment-1014653123)

@thiagoalessio Does 👆 make sense to you? Am I ok to drop this PR?

**Comment by pierreprinetti** [comment]
/remove-lifecycle stale

Ping @jupierce: you may have a clearer vision than we do of what ramifications this PR can have across ART<->CI<->Release Controller. Do you mind having a look?

**Comment by pierreprinetti** [comment]
/reopen

@jupierce can you please confirm this has to be merged?

**Pull request closed without merging**
