### PR TITLE
remove the optional from HoH e2e test

### PR DESCRIPTION
**Pull request by yanmxa**
Signed-off-by: myan <myan@redhat.com>

### CODE REVIEW

**Comment by yanmxa** [comment]
Refs: https://github.com/stolostron/backlog/issues/24257

**Comment by clyang82** [comment]
Please have a try with `m5ad.large`. if it works, then use it. otherwise, I will merge this PR.

**Comment by clyang82** [comment]
node is not ready with `m5ad.large`.
```
Events:
  Type     Reason            Age                   From                   Message
  ----     ------            ----                  ----                   -------
  Warning  FailedScheduling  <unknown>                                    no nodes available to schedule pods
  Warning  FailedScheduling  <unknown>                                    no nodes available to schedule pods
  Warning  FailedScheduling  <unknown>                                    0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
  Normal   Scheduled         <unknown>                                    Successfully assigned openshift-ingress/router-default-6c96f6bc66-cpbwq to d8c15e953b9b
  Warning  FailedMount       75s (x10 over 5m25s)  kubelet, d8c15e953b9b  MountVolume.SetUp failed for volume "service-ca-bundle" : configmap references non-existent config key: service-ca.crt
  Warning  FailedMount       75s (x10 over 5m25s)  kubelet, d8c15e953b9b  MountVolume.SetUp failed for volume "default-certificate" : secret "router-certs-default" not found
  Warning  FailedMount       64s (x2 over 3m22s)   kubelet, d8c15e953b9b  Unable to attach or mount volumes: unmounted volumes=[default-certificate service-ca-bundle], unattached volumes=[default-certificate service-ca-bundle kube-api-access-kkds5]: timed out waiting for the condition
```

**Pull request merged**
