### PR TITLE
Prevent rebasebot from overwriting rebase branches

### PR DESCRIPTION
**Pull request by odvarkadaniel**
Adding a label that is going to be used by cloud infra's rebase-bot. 
Ref to PR in rebase-bot: [PR Rebase-bot](https://github.com/openshift-eng/rebasebot/pull/16)

### CODE REVIEW

**Comment by odvarkadaniel** [comment]
Added the label within the main org as well, so we can see it when rebasing, @JoelSpeed.

**Comment by odvarkadaniel** [comment]
We want to prevent the [rebasebot](https://github.com/openshift-eng/rebasebot) from overwriting the rebase branch so we can fix up/squash fixes manually. We need a label for our org named `openshift-cloud-team` so we can distinguish these PR's, but we also need that label within the main-org.

**Comment by odvarkadaniel** [comment]
> @odvarkadaniel can you explain a little bit more in detail why you need that label also within `openshift` main org? Is PR Rebase-bot operating also within `openshift` org?

The pull requests are being created from the cloud team org into the main org. The PRs then appear within the main org.
We then need the label to be able to be set on the PRs in the main org as well. Once the label is set on the PR, the `rebasebot` knows, that it is not something that should be rebased.

**Comment by danilo-gemoli** [comment]
I'm quite perplexed of adding the label on the entire org without being aware of at least one team other than you that needs this feature.
That said, the idea is good, I trust on you guys to spread the word across the other teams such that we can justify this PR.
/lgtm

**Review by danilo-gemoli — APPROVED** [review]

**Comment by JoelSpeed** [comment]
> That said, the idea is good, I trust on you guys to spread the word across the other teams such that we can justify this PR.

Thanks, if we don't get adoption I'm happy to come back later and clean this up and move it back to just our own repositories 🙏

**Pull request merged**
