### PR TITLE
[DPTP-1892] Migrate cluster-scaleup template jobs to multi-stage

### PR DESCRIPTION
**Pull request by droslean**
Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

### CODE REVIEW

**Comment by droslean** [comment]
This change will need https://github.com/openshift/openshift-ansible/pull/12293 for all release branches.

**Comment by droslean** [comment]
@mtnbikenc Can you take care of [rehearse-15336-pull-ci-openshift-openshift-ansible-release-4.5-e2e-aws-workers-rhel7](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/15336/rehearse-15336-pull-ci-openshift-openshift-ansible-release-4.5-e2e-aws-workers-rhel7/1356210433484132352#1:build-log.txt%3A139)

It seems that the entry in this [.repo](https://github.com/openshift/openshift-ansible/blob/master/images/installer/origin-extra-root/etc/yum.repos.d/openshift-origin-4.0-ci.repo) file is wrong.

**Comment by mtnbikenc** [comment]
Getting all the way to the [test pod](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/15336/rehearse-15336-pull-ci-openshift-openshift-ansible-release-4.5-e2e-aws-workers-rhel7/1356620538625134592#1:build-log.txt%3A99) on the 4.5 job is encouraging.  Maybe not much more to do, other than getting the [CI repo URL updated](https://github.com/openshift/openshift-ansible/pull/12295).

**Comment by mtnbikenc** [comment]
rehearse-15336-pull-ci-openshift-machine-config-operator-release-4.5-e2e-aws-workers-rhel7 passed once. :+1:

All the other boto backports are merged.

**Comment by mtnbikenc** [comment]
@droslean All of the workers-rhel7 jobs are at least getting to the cluster build stage.  release-4.1, -4.2, -4.3 are failing because of cluster monitoring operator.  release-4.4 is getting past rhel worker scaleup but is failing some prometheus jobs.  release-4.5 is passing sometimes but is also failing prometheus jobs occasionally.  These are all indicative of issues we've seen in the past and the fixes probably were not backported to older branches.

**Comment by droslean** [comment]
@mtnbikenc Does this mean that all those jobs are failing even with using the template? Can you confirm that changing them to multi-stage doesn't change anything?

**Comment by mtnbikenc** [comment]
For the previous scaleup jobs, 4.1 and 4.2 are failing for other reasons, but do get past the cluster build stage.  4.3 and 4.4 show that have passed, but the test details actually indicate they have failed on other tests.

[pull-ci-openshift-openshift-ansible-release-4.1-e2e-aws-scaleup-rhel7](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-openshift-ansible-release-4.1-e2e-aws-scaleup-rhel7)
[pull-ci-openshift-openshift-ansible-release-4.2-e2e-aws-scaleup-rhel7](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-openshift-ansible-release-4.2-e2e-aws-scaleup-rhel7)
[pull-ci-openshift-openshift-ansible-release-4.3-e2e-aws-scaleup-rhel7](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-openshift-ansible-release-4.3-e2e-aws-scaleup-rhel7)
[pull-ci-openshift-openshift-ansible-release-4.4-e2e-aws-scaleup-rhel7](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-openshift-ansible-release-4.4-e2e-aws-scaleup-rhel7)

If the intent is to get all these jobs stable, it make more sense to me to move them all to multi-stage and resolve any issues.

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
