### PR TITLE
clean up release upgrade job names

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
/assign @smarterclayton 

note that i'd also like to rename `release-openshift-origin-installer-e2e-aws-upgrade-4.2-nightly-to-4.3` to `release-openshift-origin-installer-e2e-aws-upgrade-4.2-nightly-to-4.3-nightly` but my understanding is that rename is more problematic.

**Comment by bparees** [comment]
(no one except @smarterclayton should merge this as he may be the only one who understands the implications of renaming jobs)

**Comment by bparees** [comment]
@smarterclayton i think this one is probably less controversial than https://github.com/openshift/release/pull/6649 so maybe we start here?

**Comment by smarterclayton** [comment]
Or now that we have a stable 4.3.0-rc.1 we should make this job not use 4.3 nightly?  Or do we have that job?

**Comment by bparees** [comment]
> Or now that we have a stable 4.3.0-rc.1 we should make this job not use 4.3 nightly? Or do we have that job?

we have this:
```
  name: release-openshift-origin-installer-e2e-aws-upgrade-4.3-to-4.4
  spec:
    containers:
    - command:
      - /bin/bash
      - -c
      - "#!/bin/bash\nset -euo pipefail\n\ninitial=$(ARTIFACTS)/release-initial.json\nlatest=$(ARTIFACTS)/release-latest.json\nif
        ! curl --fail -X GET -G https://openshift-release.svc.ci.openshift.org/api/v1/releasestream/4-stable/latest
        --data-urlencode 'in=>4.3.0-0 <4.4.0-0' > ${initial}; then\n  echo \"error:
        Could not find a stable version\"\n  exit 1\nfi\nif ! curl --fail -X GET -G
        https://openshift-release.svc.ci.openshift.org/api/v1/releasestream/4.4.0-0.ci/latest
        > ${latest}; then\n  echo \"error: Could not find newest version\"\n  exit
        1\nfi\n\nfrom=$( python -c 'import json,sys; print json.load(open(sys.argv[1],
        \"r\"))[\"name\"]' \"${initial}\" )\nto=$( python -c 'import json,sys; print
        json.load(open(sys.argv[1], \"r\"))[\"name\"]' \"${latest}\" )\nexport RELEASE_IMAGE_INITIAL=$(
        python -c 'import json,sys; print json.load(open(sys.argv[1], \"r\"))[\"pullSpec\"]'
        \"${initial}\" )\nexport RELEASE_IMAGE_LATEST=$( python -c 'import json,sys;
        print json.load(open(sys.argv[1], \"r\"))[\"pullSpec\"]' \"${latest}\" )\n\n#
        prow doesn't allow init containers or a second container\nexport PATH=$PATH:/tmp/bin\nmkdir
        /tmp/bin\ncurl https://mirror.openshift.com/pub/openshift-v4/clients/ocp-dev-preview/4.3.0-0.nightly-2019-11-13-233341/openshift-client-linux-4.3.0-0.nightly-2019-11-13-233341.tar.gz
        | tar xvzf - -C /tmp/bin/        \nchmod ug+x /tmp/bin/oc\n\n# annotate the
        information about this job so that the release controller adds it to the upgrade
        graph\noc annotate pj/${PROW_JOB_ID} \"release.openshift.io/from-tag=${from}\"
        \"release.openshift.io/tag=${to}\" \"release.openshift.io/source=ocp/$(BRANCH)\"\n\nci-operator
        --artifact-dir=$(ARTIFACTS) --lease-server=http://boskos\\\n  --secret-dir=/usr/local/pull-secret
        --secret-dir=/usr/local/e2e-$(CLUSTER_TYPE)-upgrade-cluster-profile \\\n  --target=e2e-$(CLUSTER_TYPE)-upgrade
        --input-hash=$(BUILD_ID) --input-hash=$(JOB_NAME)\n"
```

which i guess is using the generic upgrade job?  

it's attempting to go from 
```
        https://openshift-release.svc.ci.openshift.org/api/v1/releasestream/4-stable/latest
        --data-urlencode 'in=>4.3.0-0 <4.4.0-0'
```

to

```
        https://openshift-release.svc.ci.openshift.org/api/v1/releasestream/4.4.0-0.ci/latest
```

but i guess that's not the same thing since it's going to a 4.4-ci,  not 4.4-nightly.

do the RCs show up in 4-stable?

**Comment by bparees** [comment]
in any case `release-openshift-origin-installer-e2e-aws-upgrade-4.3-nightly-to-4.4` should not be changed to use 4.3-rc.  `release-openshift-origin-installer-e2e-aws-upgrade-4.3-to-4.4-nightly` would be the appropriate name/job for that.

let's just cover this in our whiteboard discussion tomorrow

**Comment by smarterclayton** [comment]
/lgtm

The 4.4 to 4.5 is a good example of the "what should we do when none exist"

**Pull request merged**
