### PR TITLE
Sync Serverless CI config/

### PR DESCRIPTION
**Pull request by serverless-qe**

### CODE REVIEW

**Comment by mgencur** [comment]
/pj-rehearse pull-ci-openshift-knative-serverless-operator-main-417-operator-e2e-aws-417

**Comment by mgencur** [comment]
/hold
Just to see if 417-operator-e2e-aws-417 can provision 4.17 cluster.

**Comment by mgencur** [comment]
We need this: https://github.com/openshift-knative/hack/pull/406/files , otherwise all builds fail sooner than the cluster is requested.

**Comment by mgencur** [comment]
/pj-rehearse pull-ci-openshift-knative-serverless-operator-main-417-operator-e2e-aws-417

**Comment by mgencur** [comment]
/unhold

The CLusterPool for 4.17 already spins up nodes in AWS:
image

**Review by dsimansk — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
