### PR TITLE
change the name of e2e-azure test to e2e-azure-ovn 

### PR DESCRIPTION
**Pull request by JacobTanenbaum**
to make the testing a little more clear change the name of the e2e-azure
testing to e2e-azure-ovn so that it is clear what network plugin is being used

renaming the test name on master, release-4.7, and release-4.6 for consistency

### CODE REVIEW

**Comment by dcbw** [comment]
@JacobTanenbaum needs a rebase?

**Comment by abhat** [comment]
Same comment as on #11816. Do we need to rename the release-4.6 and release-4.7 jobs. Also, how does this affect our search capability in sippy and search.svc.ci?

**Pull request merged**
