### PR TITLE
logging - disable travis for now

### PR DESCRIPTION
**Pull request by richm**
disable travis for origin-aggregated-logging for now

### CODE REVIEW

**Comment by ewolinetz** [comment]
lgtm

**Comment by richm** [comment]
please correct me if I'm wrong, but I think this is what is blocking origin-aggregated-logging PRs e.g. https://github.com/openshift/origin-aggregated-logging/pull/1643 the `continuous-integration/travis-ci/pr` job is Required but never reports any status

**Comment by stevekuznetsov** [comment]
Yes, that is correct

/lgtm

**Pull request merged**
