### PR TITLE
MGMT-17219: Add single-node-recert artifact collection

### PR DESCRIPTION
**Pull request by mresvanis**
This PR adds SSH bastion host configuration for the Single Node OpenShift recert step and through that artifact collection for that same step. Specifically, the artifacts collected are:

- recert summary (clean) YAML
- recert systemd service logs

### CODE REVIEW

**Comment by mresvanis** [comment]
/pj-rehearse pull-ci-rh-ecosystem-edge-recert-main-e2e-aws-ovn-single-node-recert-parallel

**Comment by mresvanis** [comment]
/pj-rehearse pull-ci-rh-ecosystem-edge-recert-main-e2e-aws-ovn-single-node-recert-parallel

**Comment by mresvanis** [comment]
/pj-rehearse pull-ci-rh-ecosystem-edge-recert-main-e2e-aws-ovn-single-node-recert-parallel

**Comment by mresvanis** [comment]
/pj-rehearse pull-ci-rh-ecosystem-edge-recert-main-e2e-aws-ovn-single-node-recert-parallel

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ovn-single-node-recert-parallel

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ovn-single-node-recert-parallel

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ovn-single-node-recert-parallel

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ovn-single-node-recert-parallel

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ovn-single-node-recert-parallel

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ovn-single-node-recert-parallel

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ovn-single-node-recert-parallel

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ovn-single-node-recert-parallel

**Comment by mresvanis** [comment]
/pj-rehearse pull-ci-rh-ecosystem-edge-recert-main-e2e-aws-ovn-single-node-recert-parallel

**Comment by mresvanis** [comment]
/pj-rehearse pull-ci-rh-ecosystem-edge-recert-main-4.14-images pull-ci-rh-ecosystem-edge-recert-main-4.15-images pull-ci-rh-ecosystem-edge-recert-main-4.16-images pull-ci-rh-ecosystem-edge-recert-main-baremetalds-sno-recert-cluster-rename pull-ci-rh-ecosystem-edge-recert-main-cargo-check pull-ci-rh-ecosystem-edge-recert-main-cargo-clippy pull-ci-rh-ecosystem-edge-recert-main-e2e-aws-ovn-single-node-recert-parallel pull-ci-rh-ecosystem-edge-recert-main-e2e-aws-ovn-single-node-recert-serial pull-ci-rh-ecosystem-edge-recert-main-images pull-ci-rh-ecosystem-edge-recert-release-4.15-baremetalds-sno-recert-cluster-rename pull-ci-rh-ecosystem-edge-recert-release-4.15-e2e-aws-ovn-single-node-recert-parallel pull-ci-rh-ecosystem-edge-recert-release-4.15-e2e-aws-ovn-single-node-recert-serial periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ovn-single-node-recert-parallel periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ovn-single-node-recert-serial

**Comment by omertuc** [comment]
Amazing, thank you!

**Comment by mresvanis** [comment]
/pj-rehearse pull-ci-rh-ecosystem-edge-recert-main-e2e-aws-ovn-single-node-recert-parallel

**Comment by mresvanis** [comment]
/pj-rehearse pull-ci-rh-ecosystem-edge-recert-main-e2e-aws-ovn-single-node-recert-serial

**Pull request merged**
