### PR TITLE
o/jenkins: delete doomed 3.11 job + template

### PR DESCRIPTION
**Pull request by petr-muller**
Follow-up to: https://coreos.slack.com/archives/CNU6JC8GJ/p1621257116056400

The job is also a sole user of the `prow-job-cluster-launch-e2e-openshift-jenkins` template so we can remove that as well.

/cc @waveywaves @akram @jkhelil

### CODE REVIEW

**Comment by akram** [comment]
/lgtm

@petr-muller you may need a rebase

**Comment by petr-muller** [comment]
@akram thanks, rebased

**Pull request merged**
