### PR TITLE
Update the master sidecar

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
hmm.. usually we see the cvo integration test show up here as pj-rehearse.. but that doens't seem to be happening here..

**Comment by dmage** [comment]
@abhinavdahiya because we usually update the sidecar's version and change the job for the master branch to use the new version. This job change is detected by pj-rehearse. The image-registry jobs are also affected by this sidecar.

@smarterclayton did you hold it because of pj-rehearse?

**Comment by coreydaley** [comment]
Is there any word on this fix getting merged? There are several openshift/image-registry pull requests waiting on it.

**Comment by smarterclayton** [comment]
This is getting closed in favor of oleg's change #8224

**Pull request closed without merging**
