### PR TITLE
OCPQE-14239: Fix proxy issue on c2s

### PR DESCRIPTION
**Pull request by liangxia**

### CODE REVIEW

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.11-amd64-nightly-4.11-upgrade-from-stable-4.10-aws-c2s-ipi-disconnected-private-fips-p2-f14

**Comment by shellyyang1989** [comment]
Hi Liang,
Looks like it's dupe with https://github.com/openshift/release/pull/40167

**Comment by liangxia** [comment]
The failure is not related to the changes in this PR, retest,
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.11-amd64-nightly-4.11-upgrade-from-stable-4.10-aws-c2s-ipi-disconnected-private-fips-p2-f14

**Comment by evakhoni** [comment]
hmm..
1. duplicate with my earlier #40167
2. failed rehearse the same way as mine

**Pull request closed without merging**
