### PR TITLE
CVP-3096: Extend cluster lifespan in case of unsuccessful installation

### PR DESCRIPTION
**Pull request by apodhrad**
Signed-off-by: Andrej Podhradsky <apodhrad@redhat.com>

### CODE REVIEW

**Comment by apodhrad** [comment]
Hi @jupierce @bradmwilliams could you review this PR please?

Btw, what do you think about extending the list of approvers for the step `osd-crecte-create`?

**Comment by bradmwilliams** [comment]
Hey @apodhrad,
Since this PR's has been `/approved`, anyone in the Openshift organization should be able to `/lgtm` it.  I would recommend having someone on your team take a look and if everything is in order, then they can tag it for you.

**Comment by apodhrad** [comment]
Hi @samvarankashyap , could you check this PR and add your lgtm, please?

**Comment by asergienk** [comment]
lgtm, I let @samvarankashyap review and add lgtm label

**Pull request merged**
