### PR TITLE
Initial configuration files for the cinder-operator.

### PR DESCRIPTION
**Pull request by rlandy**
Initial configuration files for the cinder-operator.

### CODE REVIEW

**Review by Sandeepyadav93 — CHANGES_REQUESTED** [review]
ci-operator/jobs/openstack-k8s-operators/cinder-operator/OWNERS

viroeli - typo extra i

**Comment by Sandeepyadav93** [comment]
ok-to-test

**Comment by viroel** [comment]
/lgtm

all new 5 tests are passing.
configuration files looks correct too.

**Pull request merged**
