### PR TITLE
Fix OLM periodics

### PR DESCRIPTION
**Pull request by danilo-gemoli**
Periodics:
- `periodic-auto-olm-downstreaming`
- `periodic-auto-olm-v1-downstreaming`  

are failing miserably due to missing the permissions to pull images from the `operator-lifecycle-manager` namespace:
```sh
The test container could not start because it could not pull "registry.ci.openshift.org/operator-lifecycle-manager/olm-v1-bumper:latest". Check your images. Full message: "Back-off pulling image \"registry.ci.openshift.org/operator-lifecycle-manager/olm-v1-bumper:latest\""
```

@tmshort

### CODE REVIEW

**Comment by tmshort** [comment]
@danilo-gemoli Not sure this did what we expected, can't create the pod - I would guess due to the container not being pullable? Unless this is expected?

**Comment by danilo-gemoli** [comment]
@tmshort rehearsals don't handle such a scenario: the test has been run but no SA or RoleBindings have been created. Failure is expected I guess:
```sh
$ oc --context=app.ci -n ci get sa/olm-image-puller
Error from server (NotFound): serviceaccounts "olm-image-puller" not found
```

**Comment by tmshort** [comment]
Thanks @danilo-gemoli !!!

**Pull request merged**
