### PR TITLE
SPLAT-776: enable e2e-vsphere-zones for vsphere problem detector

### PR DESCRIPTION
**Pull request by bostrt**

### CODE REVIEW

**Comment by bostrt** [comment]
The jobs failed but installation went okay!

**Comment by gnufied** [comment]
How close are we from making these jobs mandatory? Will they be perma-failing for now?

**Comment by jcpowermac** [comment]
> How close are we from making these jobs mandatory? Will they be perma-failing for now?

Not any time soon, we don't have the capacity to do that.

**Comment by gnufied** [comment]
Does it make sense to have periodic job then? I am trying to understand - why have a job which will always fail as pre-submit hook. I know we have had jobs like these before (*cough* *cough* - migration jobs), but it will likely get ignored right?

**Comment by jcpowermac** [comment]
> Does it make sense to have periodic job then? I am trying to understand - why have a job which will always fail as pre-submit hook. I know we have had jobs like these before (_cough_ _cough_ - migration jobs), but it will likely get ignored right?

Its set `optional`, should only run when you request.

**Comment by rvanderp3** [comment]
> Does it make sense to have periodic job then? I am trying to understand - why have a job which will always fail as pre-submit hook. I know we have had jobs like these before (_cough_ _cough_ - migration jobs), but it will likely get ignored right?

we would like a way to test changes to the vsphere-problem-detector from within the PR.  we are working on improving the signal of the test, but this gives us some assurance that our change is behaving as we expect.

**Comment by gnufied** [comment]
okay lets see how it goes. We can always revert if this turns out to be a problem.

/lgtm
/approve

**Pull request merged**
