### PR TITLE
ocs: update Bugzilla target release

### PR DESCRIPTION
**Pull request by agarwal-mudit**
/cc @nixpanic

### CODE REVIEW

**Review by nixpanic — CHANGES_REQUESTED** [review]
I do not think this is correct, OCS 4.8.1 is not released yet? When is is merged, we can not add any bug fixes to OCS 4.8.1 in case QE reports issues. Is that OK?

**Comment by agarwal-mudit** [comment]
> I do not think this is correct, OCS 4.8.1 is not released yet? When is is merged, we can not add any bug fixes to OCS 4.8.1 in case QE reports issues. Is that OK?

Worst case we can manually merge but given the policy we have for current z-streams plan is to push any new bugs to the next z-stream

**Comment by agarwal-mudit** [comment]
BZ list is finalized, RC build is created so we don't expect any change unless something very critical comes

**Review by nixpanic — APPROVED** [review]
/approve

**Pull request merged**
