### PR TITLE
Update Intellij-openshift-connector

### PR DESCRIPTION
**Pull request by sbouchet**

### CODE REVIEW

**Comment by sbouchet** [comment]
@hongkailiu @psalajova : sorry for the noise, but what are the next steps ?

**Review by adietish — APPROVED** [review]
Looks good for the little I know about it 😉

**Comment by sbouchet** [comment]
> @adietish: changing LGTM is restricted to collaborators

@psalajova : how do i add @adietish as collaborators ? he is coreclty listed in OWNERS file..

**Comment by psalajova** [comment]
@sbouchet afaik this is a github setting, unrelated to the OWNERS file. see https://docs.ci.openshift.org/docs/how-tos/onboarding-a-new-component/#who-can-lgtm

**Comment by sbouchet** [comment]
> @sbouchet afaik this is a github setting, unrelated to the OWNERS file. see https://docs.ci.openshift.org/docs/how-tos/onboarding-a-new-component/#who-can-lgtm

andre is already a team member on the openshift org : https://github.com/orgs/openshift/teams?query=%40adietish

**Comment by psalajova** [comment]
> > @sbouchet afaik this is a github setting, unrelated to the OWNERS file. see https://docs.ci.openshift.org/docs/how-tos/onboarding-a-new-component/#who-can-lgtm
> 
> andre is already a team member on the openshift org : https://github.com/orgs/openshift/teams?query=%40adietish
> 
> i assume he is on the wrong team, should it be https://github.com/orgs/openshift/teams/team-red-hat ?

Being a member of the openshift org should be enough... It looks like I may have been wrong before, could you try adding adietish under reviewers in the OWNERS file? https://github.com/openshift/release/blob/b031cb1cca6a70601a6d3117f98085a43fdc840c/ci-operator/config/redhat-developer/intellij-openshift-connector/OWNERS#L11 Sorry for the confusion

**Comment by psalajova** [comment]
> > @sbouchet afaik this is a github setting, unrelated to the OWNERS file. see https://docs.ci.openshift.org/docs/how-tos/onboarding-a-new-component/#who-can-lgtm
> 
> andre is already a team member on the openshift org : https://github.com/orgs/openshift/teams?query=%40adietish
> 
> i assume he is on the wrong team, should it be https://github.com/orgs/openshift/teams/team-red-hat ?

Yes please try to add adietish to https://github.com/orgs/openshift/teams/team-red-hat , the usual way I'm aware of is to request it through https://devservices.dpp.openshift.com/support/

**Pull request merged**
