### PR TITLE
MGMT-2325: ci-operator/step-registry/baremetalds/assisted/gather: recursively scp logs

### PR DESCRIPTION
**Pull request by hexfusion**
recursive scp requires `-r` flag

> scp: /tmp/artifacts/*: No such file or directory

ref: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/12985/rehearse-12985-pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted/1318954864033665024/build-log.txt

### CODE REVIEW

**Comment by hexfusion** [comment]
cc @YuviGold @romfreiman

**Comment by romfreiman** [comment]
@YuviGold do we even downloading the logs?

**Comment by hexfusion** [comment]
> @YuviGold do we even downloading the logs?

good point looks like you might be missing $HOME?

```
X Error creating minikube directory: mkdir /.minikube: permission denied
* 
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
Could not create directory '/.ssh'.
```

**Comment by YuviGold** [comment]
> > @YuviGold do we even downloading the logs?
> 
> good point looks like you might be missing $HOME?
> 
> ```
> X Error creating minikube directory: mkdir /.minikube: permission denied
> * 
> * minikube is exiting due to an error. If the above message is not useful, open an issue:
>   - https://github.com/kubernetes/minikube/issues/new/choose
> Could not create directory '/.ssh'.
> ```

I'm trying to investigate it also on #12985.
It seems strange that we would have permissions error while both `assisted-setup` and `assisted-gather` steps doing an SSH to the same packet server, with the same user (root).

**Comment by hexfusion** [comment]
resolve via https://github.com/openshift/release/pull/12985

**Pull request closed without merging**
