### PR TITLE
openshift-psap/ci-artifacts-priv: new repo for running tests with internal results

### PR DESCRIPTION
**Pull request by kpouget**
This PR adds a private repository 'openshift-psap/ci-artifacts-priv' whose tests will run under 'qe-private-deck'.

The execution under `qe-private-deck` has been discussed on [slack](https://coreos.slack.com/archives/CBN38N3MW/p1666016444306089?thread_ts=1665757154.083399&cid=CBN38N3MW) with Stephen Goeddel.

### CODE REVIEW

**Comment by kpouget** [comment]
@hongkailiu, I hit a bug with my main branch being named `main`, the `shared-config` failed with [this error](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/33174/pull-ci-openshift-release-master-correctly-sharded-config/1582099951310082048), while it passed after renaming the branch from `main` to `perf` (https://github.com/openshift/release/pull/33174/commits/c0530133ee5982c4afadfd861e9b4b477ef27455).
Is this an issue you already faced?

**Comment by kpouget** [comment]
@hongkailiu, apart from the comment above, this PR is good for review

thanks,

Kevin

**Review by fcami — APPROVED** [review]
/lgtm

**Pull request merged**
