### PR TITLE
Fix assisted service setup quoting again

### PR DESCRIPTION
**Pull request by carbonin**

### CODE REVIEW

**Comment by carbonin** [comment]
/hold

until this passes the assisted tests

**Review by YuviGold — APPROVED** [review]
/lgtm
/approve

**Comment by carbonin** [comment]
/hold

to see outcome of assisted test

**Comment by carbonin** [comment]
So this should really pass e2e-metal-assisted now that https://github.com/openshift/assisted-test-infra/pull/212 is merged, but we're still getting the 400 error saying we don't have auth for the test registry.

I'm trying to figure out if we have an out-of-date assisted-test-infra checkout, but that line looks like this :neutral_face: 
`2020/11/02 23:27:55 Resolved source https://github.com/openshift/assisted-test-infra to master@`

**Comment by carbonin** [comment]
I'll retest one more time and maybe we'll get a sha :pray: 

/retest

**Pull request merged**
