### PR TITLE
Specify build cluster for Nutanix e2e jobs

### PR DESCRIPTION
**Pull request by adiantum**
Currently only one build cluster supports VPN.
 The cluster is explicitly defined in Nutanix e2e
 jobs for cluster-provider-nutanix.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Are there other jobs across other repositories that also need to be updated with this?

**Comment by adiantum** [comment]
> Are there other jobs across other repositories that also need to be updated with this?

Yeah, there're also openshift-priv jobs. I've updated PR.

**Comment by JoelSpeed** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-release-4.13-e2e-nutanix

**Comment by adiantum** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-release-4.13-e2e-nutanix

**Comment by adiantum** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-release-4.12-e2e-nutanix

**Comment by adiantum** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-release-4.12-e2e-nutanix

**Comment by adiantum** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-release-4.13-e2e-nutanix

**Comment by adiantum** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-release-4.12-e2e-nutanix

**Comment by adiantum** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-release-4.13-e2e-nutanix

**Comment by adiantum** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-release-4.13-e2e-nutanix

**Comment by adiantum** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-release-4.13-e2e-nutanix

**Comment by adiantum** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-release-4.13-e2e-nutanix

**Comment by JoelSpeed** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-release-4.13-e2e-nutanix

**Comment by adiantum** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-release-4.13-e2e-nutanix

**Comment by JoelSpeed** [comment]
I think this is just a flake failure right?
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-release-4.13-e2e-nutanix

**Comment by adiantum** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-release-4.13-e2e-nutanix

**Comment by adiantum** [comment]
> I think this is just a flake failure right?
Yeah, at least the part of test that was fixed ( connection to test env ) works fine.

**Review by elmiko — COMMENTED** [review]
/lgtm

**Comment by adiantum** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-release-4.13-e2e-nutanix

**Comment by adiantum** [comment]
> @adiantum Are you aware of this certificate signing issue we are seeing in the logs? Looks like the api-int address isn't being included in the SANs?

I'm aware but also it looks like flaky thing.
@thunderboltsid any idea why api-int could be not included in SANs?

**Comment by thunderboltsid** [comment]
This seems to be due to IP contention on the prism cluster. Seems like the masters from a cluster didn't get deleted. 
Screenshot 2023-02-16 at 19 17 52
Looking at https://search.ci.openshift.org/?search=+ci-op-ftmrtww7&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job seems like the lingering masters are from a failed assisted installer job that didn't clean up.

**Comment by vrutkovs** [comment]
Yeah, sorry, turns out assisted installer masters were never properly torn down (https://github.com/openshift/release/pull/35967 would fix that).

Can we clean up the masters on CI clusters manually to unblock us?

**Comment by thunderboltsid** [comment]
> 

Thanks for the update. That explains the issue. For the time being, let's manually delete until the above PR gets merged.

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-release-4.13-e2e-nutanix

**Comment by thunderboltsid** [comment]
So, there seem to be a few issues impacting Nutanix CI tests which have tangled up together:
- Wrong build cluster (which this PR fixes)
- Improper cleanup by AI jobs causing IP contention (fixed by https://github.com/openshift/release/pull/35967)
- Sporadic CSI operator installation issues (known bug https://bugzilla.redhat.com/show_bug.cgi?id=2118245)

Given this devil’s knot, IMO, it’s prudent to move ahead by merging this PR to help untangle this knot rather than wasting cycles waiting for the stars to align.

**Comment by JoelSpeed** [comment]
Based on the above, we believe this resolved the first in a line of issues with the CI, lets merge this and tackle the other issues separately 
/pj-rehearse ack

**Pull request merged**
