### PR TITLE
turn on ocb feature gate for layering e2e

### PR DESCRIPTION
**Pull request by dkhater-redhat**
layering e2e test doesn't set the feature gate, so now setting it.

### CODE REVIEW

**Comment by jkyros** [comment]
/pj-rehearse pull-ci-openshift-machine-config-operator-master-e2e-gcp-op-layering

**Comment by jkyros** [comment]
Alright, so the rehearsal here doesn't work because it didn't see any prow job changes because all we changed was an environment variable.

 I tested it [over here ](https://github.com/openshift/release/pull/46823)  and it looks like: 
1. The CI gate config works 
2. The test works 
3. The test failed during cleanup while deleting the node
4. The node actually did get deleted even though `oc` had a bad return code

**Review by yuqi-zhang — APPROVED** [review]
/lgtm

Should be a safe change to attempt

**Comment by yuqi-zhang** [comment]
going to try

/label rehearsals-ack

**Comment by jkyros** [comment]
I know the bot won't answer rehearsals, but maybe, just maybe...
/pj-rehearse ack

**Pull request merged**
