### PR TITLE
grafana: add useful panels for debugging token usage

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

https://grafana-prow-monitoring-stage.svc.ci.openshift.org/d/d72fe8d0400b2912e319b1e95d0ab1b3/github-cache?orgId=1&refresh=1m&var-token=235e57835f76bcfcd23a883081b0ac4c025950d2c8ce0353ee3b1d01455b4067&var-path=%2Frepos%2F:owner%2F:repo%2Fpulls%2F:pullId&var-status=200&var-user_agent=peribolos&var-range=30m
Screenshot from 2020-04-03 08-02-59

/assign @alvaroaleman

### CODE REVIEW

**Comment by alvaroaleman** [comment]
Can we also get an `all` option for the various parameters?

**Comment by stevekuznetsov** [comment]
Why? If you want token use by path for all user agents, I have a dedicated plot for it (that loads quickly, because it does not use regex). Same thing for the opposite -- use by agent for all paths. There is no usefulness to "all" for the dedicated plots, they present data specificaly for a drill-down view, the "All" is handled by the overviews. What question would you answer with "all" for a parameter?

**Comment by alvaroaleman** [comment]
> Why? If you want token use by path for all user agents, I have a dedicated plot for it (that loads quickly, because it does not use regex). Same thing for the opposite -- use by agent for all paths. There is no usefulness to "all" for the dedicated plots, they present data specificaly for a drill-down view, the "All" is handled by the overviews. What question would you answer with "all" for a parameter?

Because I find it super confusing if there are distinct panels for `all` and for `drill down`

**Comment by stevekuznetsov** [comment]
Weird. You look at the overall, then decide how to drill down. I would like to keep it this way, that's the workflow I've been using the entire time. Furthermore, using "all" requires that we use regex matching on the things, which will cause paths that prefix each other (for instance) not to work as expected. And, regex matching is slow as hell.

**Pull request merged**
