### PR TITLE
Run kuttl tests in e2e job for ovs-operator

### PR DESCRIPTION
**Pull request by cescgina**
Run the build-deploy-kuttl workflow instead of the build-deploy one.

### CODE REVIEW

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-ovs-operator-main-ovs-operator-build-deploy-kuttl

**Comment by cescgina** [comment]
Tests passed, ready for review

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-ovs-operator-main-ovs-operator-build-deploy-kuttl

**Comment by frenzyfriday** [comment]
Looks good to me. The build-deploy-kuttl tests are passing as well.

**Comment by Sandeepyadav93** [comment]
/pj-rehearse ack

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/37444/rehearse-37444-pull-ci-openstack-k8s-operators-ovs-operator-main-ovs-operator-build-deploy-kuttl/1638456419097251840/artifacts/ovs-operator-build-deploy-kuttl/openstack-k8s-operators-kuttl/build-log.txt

**Pull request merged**
