### PR TITLE
Configure shipwrigh-io/operator

### PR DESCRIPTION
**Pull request by adambkaplan**
- Configure prow plugins for release note, matching label.
- Configure labels needed to merge/block merge.

### CODE REVIEW

**Comment by adambkaplan** [comment]
/cc @gabemontero 

Followed your lead on setting up the release note plugin.

**Review by alvaroaleman — APPROVED** [review]
/hold
for prow config changes

**Comment by adambkaplan** [comment]
@alvaroaleman added the missing OWNERS files.

**Review by alvaroaleman — APPROVED** [review]
(The hold was in case you want gabe to verify, feel free to remove it if that is not needed)

**Comment by adambkaplan** [comment]
Moving forward with just the prow plugins, we've been using github actions for CI

**Comment by adambkaplan** [comment]
/hold cancel

Gabe gave lgtm

**Pull request merged**
