### PR TITLE
Bug 1833372: Remove installation of golang dep, because CNO is moving to Go Modules and dep is not required.

### PR DESCRIPTION
**Pull request by vishnoianil**
…s and dep is not required.

Signed-off-by: Anil Vishnoi <avishnoi@redhat.com>

### CODE REVIEW

**Comment by vishnoianil** [comment]
@danwinship @dcbw @rcarrillocruz @alexanderConstantinescu @dave-tucker PTAL. 

This is required for the following pull request that migrate CNO to GO Modules
https://github.com/openshift/cluster-network-operator/pull/616

@dave-tucker PTAL at above PR as well. I will be updating verify-style.sh to make it work with this change.

**Comment by danwinship** [comment]
You can't merge this until you change CNO to not call `dep check` from `./hack/verify-style.sh`. Otherwise you'll break the CI job.

**Comment by danwinship** [comment]
ok, I don't understand exactly why it's failing, but I filed https://github.com/openshift/cluster-network-operator/pull/630 to remove the `dep check` from `verify-style.sh` so we can commit this so we can commit https://github.com/openshift/cluster-network-operator/pull/616

**Comment by vishnoianil** [comment]
> You can't merge this until you change CNO to not call `dep check` from `./hack/verify-style.sh`. Otherwise you'll break the CI job.

@danwinship My CNO PR always takes care of it.

**Comment by vishnoianil** [comment]
> ok, I don't understand exactly why it's failing, but I filed [openshift/cluster-network-operator#630](https://github.com/openshift/cluster-network-operator/pull/630) to remove the `dep check` from `verify-style.sh` so we can commit this so we can commit [openshift/cluster-network-operator#616](https://github.com/openshift/cluster-network-operator/pull/616)

@danwinship I think it's failing because we use -mod=vendor flag with GO111MODULE="auto" and trying to get dep using `go get -u github.com/golang/dep/cmd/dep`, so removing this will help it to reach to execution of verify-style.sh, but it will fail there because we are internally check for presence of `dep`, so in my CNO patch i removed that as well.

**Comment by vishnoianil** [comment]
> > You can't merge this until you change CNO to not call `dep check` from `./hack/verify-style.sh`. Otherwise you'll break the CI job.
> 
> @danwinship My CNO PR always takes care of it.

Did i say always :D ..i meant anyways :P

**Comment by vishnoianil** [comment]
@danwinship Looks like all the tests are passing on this PR, without CNO PR, except tide is looking for lgtm for this PR i believe ?

**Pull request merged**
