### PR TITLE
jobs: extend 4.6 -> 4.7 -> 4.8 upgrade timeout to 8hrs

### PR DESCRIPTION
**Pull request by vrutkovs**
TODO:
* [x] Verify that step/job crosses 4hr period
* [x] Add a step to delete Insights operator pod
      This would make it send a new report, so that we could see the result in the Superset.
      UPD: CI runs are preconfigured to run snapshots every 10 mins, which is enough for post section to trigger this

Requires https://github.com/openshift/ci-tools/pull/2294 to pass generated job checker

### CODE REVIEW

**Comment by wking** [comment]
/lgtm
/hold

Looks good to me.  Would be nice to have a rehearsal confirming it works before pulling the hold, but if it's to hard to get the ancient versions to install, I'm fine landing this first and adjusting later if necessary.

**Comment by vrutkovs** [comment]
/hold cancel

Lets run them live for a few weeks, we might want to move them to never-stable if these never pass

**Pull request merged**
