### PR TITLE
upi-gcp-nested: do not hardcode GCP project/region/zone

### PR DESCRIPTION
**Pull request by petr-muller**
To ensure reusability, GCP project needs to be supplied via cluster
profile (parameter is technically fine but the cluster profile contains
the project ID together with necessary credentials). Region needs to be
inferred from Boskos lease. Zone needs to be read from GCP based on
region.

Blocks: https://github.com/openshift/release/pull/18253

### CODE REVIEW

**Comment by petr-muller** [comment]
/hold

Apparently, not *that* easy :/

**Comment by petr-muller** [comment]
```diff
- GOOGLE_COMPUTE_ZONE="$(gcloud ... | head -n 1)}"
+ GOOGLE_COMPUTE_ZONE="$(gcloud ... | head -n 1)"
```

:facepalm:

**Review by stevekuznetsov — APPROVED** [review]

**Pull request merged**
