### PR TITLE
DPTP-3932: Migrate periodic-image-mirroring-kubefed

### PR DESCRIPTION
**Pull request by deepsm007**
/cc @openshift/test-platform
/assign @hongkailiu 

/hold

Checking the rehearsal ...

### CODE REVIEW

**Comment by deepsm007** [comment]
Dry-run result:
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/50979/rehearse-50979-periodic-image-mirroring-kubefed/1780253814188675072  
Looks good.

**Comment by deepsm007** [comment]
Dry run:
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/50979/rehearse-50979-periodic-image-mirroring-kubefed/1780279872631869440 
looks good now

**Review by hongkailiu — APPROVED** [review]

**Pull request merged**
