### PR TITLE
remove 4.6 vsphere ovn jobs

### PR DESCRIPTION
**Pull request by jluhrsen**
These jobs run in to pull limits from docker and the changes
in 4.7+ that resolved it were too complicated to back port
to 4.6. We removed a pre-submit job here [0], but I neglected
to remove all the other 4.6 ovn-vsphere jobs that are just
wasting resources and perma-failing

[0] https://github.com/openshift/release/pull/18398/commits/8ba1ced352b73519c421f26db51ebd203f605fb1

Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>

### CODE REVIEW

**Review by wking — COMMENTED** [review]
From [TestGrid][1]:

image

So not quite perma-failing, but since the 7th it's been pretty close to dead.

/lgtm

[1]: https://testgrid.k8s.io/redhat-openshift-ocp-release-4.6-informing#periodic-ci-openshift-release-master-nightly-4.6-e2e-vsphere-ovn

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
