### PR TITLE
enable service catalog and tsb in CI for conformance runs

### PR DESCRIPTION
**Pull request by jim-minter**
other half of https://github.com/openshift/aos-cd-jobs/pull/718

### CODE REVIEW

**Comment by jim-minter** [comment]
@stevekuznetsov ptal

**Comment by stevekuznetsov** [comment]
@smarterclayton any comments? LGTM

**Comment by jim-minter** [comment]
@smarterclayton bump

**Comment by deads2k** [comment]
@stevekuznetsov You prepared to do this?  I've got work backing up on it.

**Comment by stevekuznetsov** [comment]
@smarterclayton feel free to revert, but to unblock work let's get this in. @jim-minter you'll want to make sure the new image gets created to pick this up

**Comment by pmorie** [comment]
Cc @staebler

**Pull request merged**
