### PR TITLE
Bug 1870369: Fix gather bootstrap command

### PR DESCRIPTION
**Pull request by rna-afk**
Fixes current setup by setting the GATHER_BOOTSTRAP_ARGS variable
which was missing before and now it will gather the bootstrap logs
successfully when the test is run.

### CODE REVIEW

**Comment by jcpowermac** [comment]
@rna-afk since the images were moved to rhel8 and there is an issue with CSRs and the older cli I think you will need these:
https://github.com/openshift/installer/pull/4098
https://github.com/openshift/release/pull/11397

**Comment by rna-afk** [comment]
Ah got it thanks! was wondering why the tests failed.

**Comment by rna-afk** [comment]
Alternate jq solution would be 
val=$(echo $TERRAFORM_SHOW_DATA | jq -r '{IPs: [.values.root_module.child_modules[] | select(.address | startswith("module.ipam")) | .resources[] | select(.address | startswith("data.http.getip")) | .values.body']})
bootstrap_ip=$(echo $val | jq '.IPs[] | select(. | contains("bootstrap"))' | grep -Eo '([0-9]*\.){3}[0-9]*') 
echo $bootstrap_ip 

I thought the val part extraction looks long and unreadable compared to the grep answer. Let me know if this is a better solution.

**Comment by jcpowermac** [comment]
> Alternate jq solution would be
> 
> ```
> val=$(echo $TERRAFORM_SHOW_DATA | jq -r '{IPs: [.values.root_module.child_modules[] | select(.address | startswith("module.ipam")) | .resources[] | select(.address | startswith("data.http.getip")) | .values.body']})
> bootstrap_ip=$(echo $val | jq '.IPs[] | select(. | contains("bootstrap"))' | grep -Eo '([0-9]*\.){3}[0-9]*') 
> echo $bootstrap_ip 
> ```
> 
> I thought the val part extraction looks long and unreadable compared to the grep answer. Let me know if this is a better solution.

Terraform won't know the ip address of the virtual machine. It needs to be grabbed via `govc`

**Comment by jcpowermac** [comment]
@rna-afk 
This is a significantly easier way of getting the ip address for the virtual machine.  If vmware tools is not running the host is not online far enough to grab data from it anyway

```
      declare "${hostname//-/_}_ip"="$(govc vm.ip -wait=1m -vm.ipath="$ipath" | awk -F',' '{print $1}')"
```

**Pull request closed without merging**
