### PR TITLE
install google-chrome in UI images

### PR DESCRIPTION
**Pull request by memodi**
install google-chrome for cypress tests

### CODE REVIEW

**Comment by memodi** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-images
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-e2e-console

**Comment by memodi** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-images
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-e2e-console

**Comment by memodi** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-e2e-console

**Comment by memodi** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-e2e-console

**Comment by memodi** [comment]
rehearsal on master e2e-console passed: https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/50148/rehearse-50148-pull-ci-openshift-openshift-tests-private-master-e2e-console/1771265181087698944

**Comment by liangxia** [comment]
/lgtm

/hold
just in case @yapei has concerts.

**Comment by yapei** [comment]
looks good to me, let's see how it works in CI
/unhold

**Pull request merged**
