### PR TITLE
PowerVS: Switch installer altinfra to CI periodics

### PR DESCRIPTION
**Pull request by hamzy**
Move the PowerVS CAPI testing out of the installer periodics and into the CI nightlies.

### CODE REVIEW

**Comment by hamzy** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-ovn-ppc64le-powervs-capi

**Review by r4f4 — COMMENTED** [review]
/approve

Thanks for doing this.

**Pull request merged**
