### PR TITLE
Updating a few of the "odd" P/Z jobs to use the multi-payload as a default

### PR DESCRIPTION
**Pull request by tvardema**
JIRA: [MIXEDARCH-374](https://issues.redhat.com//browse/MIXEDARCH-374)

### CODE REVIEW

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.12-ocp-image-ecosystem-ovn-remote-libvirt-s390x

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.12-ocp-image-ecosystem-ovn-remote-libvirt-s390x

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.12-ocp-image-ecosystem-ovn-remote-libvirt-ppc64le

**Comment by jeffdyoung** [comment]
Just so I know I'm following correctly.. you are changing these jobs to use the multi-payload:

```
ocp-image-ecosystem-ovn-remote-libvirt-s390x
ocp-image-ecosystem-ovn-remote-libvirt-ppc64le
ocp-jenkins-e2e-ovn-remote-libvirt-s390x
ocp-jenkins-e2e-ovn-remote-libvirt-ppc64le
```

If so, can we be more specific in the Jira Ticket on what is changing? Otherwise LGTM.

**Comment by tvardema** [comment]
> If so, can we be more specific in the Jira Ticket on what is changing? Otherwise LGTM.

Updated the JIRA with more specific job descriptions.

**Pull request merged**
