### PR TITLE
Hive: Add CI jobs for mce-2.2 branch

### PR DESCRIPTION
**Pull request by 2uasimojo**

### CODE REVIEW

**Review by gurnben — APPROVED** [review]
/lgtm
/approve

**Comment by 2uasimojo** [comment]
@abutcher can you tell at a glance whether the azure failure is one of those things we fixed with a recent revendor?

**Comment by 2uasimojo** [comment]
ight.

/pj-rehearse pull-ci-openshift-hive-mce-2.2-e2e-azure

**Comment by abutcher** [comment]
Looks like a problem fixed in the revendor https://github.com/openshift/hive/pull/1928

```
    - errorMessage: 'failed to reconcile machine "hive-06ec5181-05d8-43-ssvml-infra-centralus3-8279f":
        failed to create vm hive-06ec5181-05d8-43-ssvml-infra-centralus3-8279f: failure
        sending request for machine hive-06ec5181-05d8-43-ssvml-infra-centralus3-8279f:
        cannot create vm: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending
        request: StatusCode=404 -- Original Error: Code="NotFound" Message="The Image
        ''/subscriptions/d38f1e38-4bed-438e-b227-833f997adf6a/resourceGroups/hive-06ec5181-05d8-43-ssvml-rg/providers/Microsoft.Compute/images/hive-06ec5181-05d8-43-ssvml''
        cannot be found in ''centralus'' region."'
      errorReason: InvalidConfiguration
```

**Comment by 2uasimojo** [comment]
Okay, let's land this and fix the branch in the repo.

/pj-rehearse ack

**Pull request merged**
