### PR TITLE
telco5g: Use spot instances 2

### PR DESCRIPTION
**Pull request by sshnaidm**

### CODE REVIEW

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.12-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-release-4.14-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-release-4.15-e2e-aws-ci-tests

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.12-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-release-4.14-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-release-4.15-e2e-aws-ci-tests

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.12-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-release-4.14-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-release-4.15-e2e-aws-ci-tests

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.12-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-release-4.14-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-release-4.15-e2e-aws-ci-tests

**Review by SchSeba — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
