### PR TITLE
Add SPLAT team to prowjob readers

### PR DESCRIPTION
**Pull request by bostrt**
SPLAT team develops a tool that reads Prow Jobs directly from app.ci and needs reader role.

### CODE REVIEW

**Comment by hongkailiu** [comment]
> SPLAT team develops a tool that reads Prow Jobs directly from app.ci and needs reader role.

Should it be a service account if it is a tool?

**Comment by bostrt** [comment]
> Should it be a service account if it is a tool?

Yes, a service account would be great. Can you link me to a doc on how to get one?

**Comment by bostrt** [comment]
@hongkailiu just updated with the Service Account. Thanks for the guidance! Hopefully, this configuration is acceptable now.

**Review by hongkailiu — APPROVED** [review]

**Pull request merged**
