### PR TITLE
OWNERS: Prune ewolinetz

### PR DESCRIPTION
**Pull request by wking**
Eric has left Red Hat :(

Generated using #21876 with:

```console
$ hack/owners-prune.py -r ~/src/openshift/release -m 'Eric has left Red Hat :(' ewolinetz
```

to help folks avoid errors [like][1]:

> ewolinetz
> User is not a member of the org. User is not a collaborator. Satisfy at least one of these conditions to make the user trusted.

when copy/pasting around existing `OWNERS` content.

[1]: https://github.com/openshift/release/pull/21175#issuecomment-975780722

### CODE REVIEW

**Comment by wking** [comment]
I've pushed ba3250b -> a94e50f to add:

```console
$ make registry-metadata
$ sed -i '/ewolinetz/d' clusters/app.ci/registry-access/openshift-logging/admin_manifest.yaml
```

**Review by alanconway — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
