### PR TITLE
Add maistra-builder 3.0 image tag

### PR DESCRIPTION
**Pull request by dgn**
Requirement for https://github.com/openshift/release/pull/37391

### CODE REVIEW

**Review by yxun — APPROVED** [review]

**Comment by dgn** [comment]
> @dgn you need to mirror this in the `arm64` [file](https://github.com/openshift/release/blob/e01097f53ee9f27fad7fde799f4c591393220ba9/core-services/image-mirroring-arm64/mapping_supplemental_ci_images_ci#L53) too.

That file does not exist on master...?

**Comment by smg247** [comment]
/approve
The temporary step must be finished now. Sorry for the delay.

**Comment by dgn** [comment]
No worries. Thank you

**Pull request merged**
