### PR TITLE
HOSTEDCP-1569: capk: update hypershift-tests image ref

### PR DESCRIPTION
**Pull request by sjenning**
follow-on fix to https://github.com/openshift/release/pull/57167

### CODE REVIEW

**Comment by sjenning** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-kubevirt-main-e2e-hypershift-kubevirt

**Review by devguyio — APPROVED** [review]

**Comment by sjenning** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-kubevirt-main-e2e-hypershift-kubevirt

**Review by devguyio — APPROVED** [review]
/lgtm

**Comment by stbenjam** [comment]
Is this why payloads fail?

https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-hypershift-release-4.18-periodics-e2e-aws-ovn-conformance/1838989796240789504

The rehearsal that's running looks good.  We haven't had a green payload in a while so tagging this to hopefully get one overnight...

/label approved
/pj-rehearse

**Comment by stbenjam** [comment]
/pj-rehearse ack

meant ack not run more rehearsals

**Comment by nunnatsa** [comment]
@sjenning - this is not working. Now trying to rebuild 4.15 and 4.16 to fix CVEs, and the test fails for capk behavior that was changed later, and hypershift test in main, check it. It can't work.

**Pull request merged**
