### PR TITLE
Sync Serverless CI

### PR DESCRIPTION
**Pull request by serverless-qe**
Sync Serverless CI using openshift-knative/hack.

### CODE REVIEW

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve
/ok-to-test

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-release-v1.14-412-test-e2e-aws-412

**Comment by ReToCode** [comment]
/pj-rehearse periodic-ci-openshift-knative-serving-release-v1.14-412-test-e2e-aws-412-c

**Comment by ReToCode** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-release-v1.14-412-test-e2e-aws-412

**Comment by ReToCode** [comment]
/pj-rehearse periodic-ci-openshift-knative-serving-release-v1.14-415-perf-tests-aws-415-c

**Comment by ReToCode** [comment]
/pj-rehearse periodic-ci-openshift-knative-serving-release-v1.14-415-test-e2e-aws-415-c

**Comment by ReToCode** [comment]
/pj-rehearse periodic-ci-openshift-knative-serving-release-v1.14-412-test-e2e-tls-aws-412-c

**Comment by ReToCode** [comment]
> creating EC2 EIP: AddressLimitExceeded: The maximum number of addresses has been reached.

**Comment by ReToCode** [comment]
/pj-rehearse periodic-ci-openshift-knative-serving-release-v1.14-415-test-e2e-aws-415-c

**Comment by ReToCode** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-release-v1.14-412-test-e2e-aws-412

**Comment by ReToCode** [comment]
/pj-rehearse periodic-ci-openshift-knative-serving-release-v1.14-415-test-e2e-aws-415-c

**Comment by ReToCode** [comment]
/pj-rehearse periodic-ci-openshift-knative-serving-release-v1.14-415-perf-tests-aws-415-c

**Comment by ReToCode** [comment]
/pj-rehearse periodic-ci-openshift-knative-serving-release-v1.14-412-test-e2e-tls-aws-412-c

**Comment by ReToCode** [comment]
e2e tests cannot pass atm, as this needs changes in S-O.

/pj-rehearse ack

**Comment by deepsm007** [comment]
@ReToCode https://github.com/openshift/release/blob/master/core-services/image-mirroring/knative/mapping_knative_knative-nightly_eventing_quay mirroring has started to fail after this PR merge. Is there anything that changed ? 
Failing [job](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-image-mirroring-knative/1785851952827994112)

**Pull request merged**
