### PR TITLE
New NFD owners

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
- https://github.com/openshift/cluster-nfd-operator/pull/273
- https://github.com/openshift/node-feature-discovery/pull/88

**Comment by ArangoGutierrez** [comment]
@yevgeny-shnaidman

**Review by yevgeny-shnaidman — APPROVED** [review]

**Pull request merged**
