### PR TITLE
add extended-platform-tests binary to  e2e template, run e2e-extended-platform in kcmo

### PR DESCRIPTION
**Pull request by sallyom**
This adds a test job to a single openshift repo, kcmo, to verify the new test binaries include all test suites and that suites pass. 

Add `e2e-new` target in kube-controller-manager-operator repo.  This will be a temporary target to verify new test binaries can replace old openshift-tests binary. 
`e2e-new` runs the ci template that uses extended-platform-tests, openshfit-tests-kubernetes binaries built from openshift/openshift-tests repository. 
Depends on https://github.com/openshift/openshift-tests/pull/12

This will be the last PR that needs to pass b4 renaming extended-platform-tests image to release:tests and then modifying ci templates to run new binaries. 
 
/assign @soltysh 
/cc @tnozicka @deads2k

### CODE REVIEW

**Comment by deads2k** [comment]
I hate teraform

/retest

**Comment by deads2k** [comment]
terraform is going to become a four letter work

/retest

**Comment by deads2k** [comment]
terraform

/retest

**Comment by deads2k** [comment]
w00t.  it worked.

/hold

**Comment by sallyom** [comment]
/hold

need this first: https://github.com/openshift/openshift-tests/pull/12

**Comment by sallyom** [comment]
openshift-tests-kubernetes is going in a different direction, closing this

**Pull request closed without merging**
