### PR TITLE
Add nutanix failure domain job

### PR DESCRIPTION
**Pull request by sgaoshang**

### CODE REVIEW

**Comment by sgaoshang** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-nutanix-ipi-boot-categories-project-rt-f28

**Comment by sgaoshang** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-nutanix-ipi-boot-categories-project-rt-f28

**Comment by sgaoshang** [comment]
/pj-rehearse pull-ci-openshift-machine-api-provider-nutanix-main-e2e-nutanix

**Comment by sgaoshang** [comment]
/pj-rehearse pull-ci-openshift-machine-api-provider-nutanix-main-e2e-nutanix

**Comment by sgaoshang** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-nutanix-ipi-zones-f14

**Comment by sgaoshang** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-nutanix-ipi-zones-f14

**Comment by sgaoshang** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-nutanix-ipi-zones-f14

**Comment by sgaoshang** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-nutanix-ipi-zones-f14

**Comment by sgaoshang** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-nutanix-ipi-zones-f14

**Comment by sgaoshang** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-nutanix-ipi-zones-f14

**Comment by sgaoshang** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-nutanix-ipi-zones-f14

**Comment by sgaoshang** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-nutanix-ipi-zones-f14

**Comment by sgaoshang** [comment]
@jianlinliu We make some change to Nutanix zonal env, added 3 PEs and also changed network name, pls help to review, thanks.

**Comment by jianlinliu** [comment]
@sgaoshang Now we do not need the change on `ipi-conf-nutanix-context` mentioned in https://github.com/openshift/release/pull/47854 ? How was it resolved?

**Comment by sgaoshang** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-nutanix-ipi-zones-f14

**Comment by sgaoshang** [comment]
> @sgaoshang Compared with #47854 , seem like we we only removed the change on `ipi-conf-nutanix-context` now? How was it resolved?

We need to change `ipi-conf-nutanix-context` because there are 3 subnets with same name exist on zonal env, like Zonal24/Zonal24/Zonal24, when getting VIP it will return 3 IPs and cause error, I asked DPP to change the name to Zonal24_STS/Zonal24/Zonal24 and will use Zonal24_STS to get VIP.

**Comment by sgaoshang** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-nutanix-ipi-zones-f14

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-nutanix-ipi-zones-f14

**Comment by jianlinliu** [comment]
cc @liangxia to review.

**Pull request merged**
