### PR TITLE
Reapply "OTA-1069: adding new test point to OCP-23799 (#52187)"

### PR DESCRIPTION
**Pull request by evakhoni**
This reverts commit fa544869f9942ca128edd66947e6c1a018766601.

follow up [OCPBUGS-37345](https://issues.redhat.com/browse/OCPBUGS-37345) and the decision to reenable rollback, reintroducing OCP-23799 test points disabled via #53845
/cc @jiajliu @JianLi-RH @jianlinliu @dis016 @shellyyang1989

### CODE REVIEW

**Comment by jianlinliu** [comment]
@evakhoni shall we also apply it to 4.16 -> 4.17 upgrade job ?

**Comment by evakhoni** [comment]
> @evakhoni shall we also apply it to 4.16 -> 4.17 upgrade job ?

oh :man_facepalming: :) just reversed the last revert, but we definitely need to-4.17 as well :+1:

**Comment by evakhoni** [comment]
> step-registry-shellcheck job failed.

artifact of the revert.. stole a bracket from the function above it :man_shrugging:

**Comment by evakhoni** [comment]
just reintroducing back previously reverted code, so i guess
/pj-rehearse ack

**Pull request merged**
