### PR TITLE
Initial Configuration backplane 2.4

### PR DESCRIPTION
**Pull request by Kyl-Bempah**
/hold

### CODE REVIEW

**Comment by Kyl-Bempah** [comment]
@qiujian16 @subbarao-meduri @JakobGray @KevinFCormier @rokej

**Comment by dhaiducek** [comment]
- Should we remove the `release-2.4` configurations entirely rather than just removing the promotion stanzas?
- Also, in the past the latest version was promoted from `main`, though I don't know the background nor the consequences on that--I've just been blindly doing it up until now.

**Comment by dhaiducek** [comment]
@gurnben 
1. A separate PR works for me! Since the `2.4` promotions no longer conflict, I don't think there's harm in leaving the configurations in place, either. I've been thinking about cleaning up GRC repos in the back of my mind lately just to keep things streamlined as our configurations grow.
2. Gotcha. Yeah, then if it's not relevant any more, that sounds good to me! I was wondering if there might be cases where a squad might use the promoted images from `main` in tests or something before fast-forwarding, but that's probably a squad-by-squad thing (and might not even be a thing).

**Pull request merged**
