### PR TITLE
Enable FIPS mode

### PR DESCRIPTION
**Pull request by pawanpinjarkar**

### CODE REVIEW

**Comment by andfasano** [comment]
cc @zaneb for additional feedback

**Comment by pawanpinjarkar** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-agent-master-e2e-agent-compact-ipv4

**Comment by pawanpinjarkar** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-agent-master-e2e-agent-ha-dualstack
/pj-rehearse pull-ci-openshift-assisted-installer-agent-master-e2e-agent-sno-ipv6

**Comment by pawanpinjarkar** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-agent-master-e2e-agent-sno-ipv6

**Comment by pawanpinjarkar** [comment]
/pj-rehearse  periodic-ci-openshift-release-master-nightly-4.14-e2e-agent-ha-dualstack

**Comment by pawanpinjarkar** [comment]
> What's the purpose of this change? It was my intention to enable FIPS on only one job, the same as we do for other features (like e.g. IPv6).

This PR is not necessary now as I have changed the job definitions for the conformance tests. https://github.com/openshift/release/pull/43917/files

**Pull request closed without merging**
