### PR TITLE
feat: add kepler e2e to prow

### PR DESCRIPTION
**Pull request by vprashar2929**
This PR adds Kepler e2e to Prow

### CODE REVIEW

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-main-kepler-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-main-kepler-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-main-kepler-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-main-kepler-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse  pull-ci-openshift-power-monitoring-kepler-main-images

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-main-kepler-e2e

**Review by sthaha — COMMENTED** [review]
/lgtm

**Pull request merged**
