### PR TITLE
Apply the new group policy on pool's RBACs

### PR DESCRIPTION
**Pull request by hongkailiu**

### CODE REVIEW

**Review by petr-muller — APPROVED** [review]
LGTM but it seems to me we need to communicate this first and have docs to tell people how to maintain groups instead, so holding

/hold

**Comment by hongkailiu** [comment]
```console
$ oc --context hive delete group cvp-pool-admins hypershift-pool-admins msp-pool-admins --as system:admin
group.user.openshift.io "cvp-pool-admins" deleted
group.user.openshift.io "hypershift-pool-admins" deleted
group.user.openshift.io "msp-pool-admins" deleted
```

**Comment by petr-muller** [comment]
:steam_locomotive:

**Pull request merged**
