### PR TITLE
Add disaster recovery test to the automated release

### PR DESCRIPTION
**Pull request by wangke19**
We think the DR test is the important part of the automated release tests, so add it. 
Associated Jira issue: https://issues.redhat.com/browse/OCPQE-24145, https://issues.redhat.com/browse/OCPQE-22058

### CODE REVIEW

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-vsphere-ipi-zones-f28

**Comment by wangke19** [comment]
/assign @liangxia 
cc: @geliu2016 @wsun1

**Comment by liangxia** [comment]
For automated release, it requires high pass ratio of the job and the test cases.
```
ginkgo:
  type: openshift-extended-test-disasterrecovery
  total: 9
  failures: 2
  errors: 0
  skipped: 5
```
You'll need a higher pass ratio of your test cases.   
/cc @rioliu-rh @jianlinliu

**Comment by jianlinliu** [comment]
> You'll need a higher pass ratio of your test cases.

Right, the automated release testing 0 failure tolerance, any failure will be treated as the whole test failed.

**Comment by rioliu-rh** [comment]
1. at least we need to ensure LEVEL0 case has high pass ratio
2. do we need to run DR test for all the auto release jobs?

**Comment by wangke19** [comment]
> * at least we need to ensure LEVEL0 case has high pass ratio
> * do we need to run DR test for all the auto release jobs?



> For automated release, it requires high pass ratio of the job and the test cases.
> 
> ```
> ginkgo:
>   type: openshift-extended-test-disasterrecovery
>   total: 9
>   failures: 2
>   errors: 0
>   skipped: 5
> ```
> 
> You'll need a higher pass ratio of your test cases. /cc @rioliu-rh @jianlinliu

@liangxia One question is, are these tests all running in parallel? For our DR test, only can be ran in serial.

**Comment by wangke19** [comment]
> 1. at least we need to ensure LEVEL0 case has high pass ratio
> 2. do we need to run DR test for all the auto release jobs?

We have LEVEL0 cases, but all DR cases were executed.
```
"[sig-disasterrecovery] DR_Testing LEVEL0-ROSA-ARO-OSD_CCS-NonPreRelease-Longduration-Author:rgangwar-High-19941-[Apiserver] [failure inject] when 1 master is down the cluster should continue serving well without unavailable more than 30s [Disruptive] [Serial]"
```

**Comment by liangxia** [comment]
> > * at least we need to ensure LEVEL0 case has high pass ratio
> > * do we need to run DR test for all the auto release jobs?
> 
> > For automated release, it requires high pass ratio of the job and the test cases.
> > ```
> > ginkgo:
> >   type: openshift-extended-test-disasterrecovery
> >   total: 9
> >   failures: 2
> >   errors: 0
> >   skipped: 5
> > ```
> > You'll need a higher pass ratio of your test cases. /cc @rioliu-rh @jianlinliu
> 
> @liangxia One question is, are these tests all running in parallel? For our DR test, only can be ran in serial.

Your step `openshift-extended-test-disasterrecovery` controls how your test cases are executed, in serial or in parallel.

**Comment by rioliu-rh** [comment]
if DR step is added to auto release test chain, it will be executed in every auto release job run for every accepted nightly. I'm curious about DR testing requirement

Q: DR test case is disruptive, currently disruptive tests are excluded by default value of param `TEST_FILTERS` in step openshift-extended-test. so it could be the 1st disruptive case involved in auto release pipeline
Q: is it required for release gate testing? can we run this kind of test in dedicated job and mark it as optional? when the job/test is stable enough, we can promote it as required job then

**Comment by wangke19** [comment]
> if DR step is added to auto release test chain, it will be executed in every auto release job run for every accepted nightly. I'm curious about DR testing requirement
> 
> Q: DR test case is disruptive, currently disruptive tests are excluded by default value of param `TEST_FILTERS` in step openshift-extended-test. so it could be the 1st disruptive case involved in auto release pipeline Q: is it required for release gate testing? can we run this kind of test in dedicated job and mark it as optional? when the job/test is stable enough, we can promote it as required job then

A1: DR cases won't be exueted in openshift-extended-test chain, we did that in openshift-extended-test-disasterrecovery step.
A2:  To add DR step to auto release test chain, this decision comes from our previous discussion @wsun1 and @geliu2016 we think level0 DR cases are key features.

**Comment by wsun1** [comment]
> Q: is it required for release gate testing? can we run this kind of test in dedicated job and mark it as optional? when the job/test is stable enough, we can promote it as required job then
Yes, Level 0 DR test cases are reqired for the release gate testing. No matter where it runs, we would like DR Level 0 has the same criterion with other Level 0 test cases. 

> failures: 2
@wangke19 For these 2 failures, we need to fix them firstly if they are not product issue.

**Comment by rioliu-rh** [comment]
> > Q: is it required for release gate testing? can we run this kind of test in dedicated job and mark it as optional? when the job/test is stable enough, we can promote it as required job then
> 
> Yes, Level 0 DR test cases are reqired for the release gate testing. No matter where it runs, we would like DR Level 0 has the same criterion with other Level 0 test cases.

Thanks for the confirmation about the DR testing priority. my biggest concern is DR case stability not only depends on openshift product quality i.e. functionality of control plane components, it also depends on cloud vendors stability. because the case does stop/start vm instance. and this op might have different results on different platforms. if we put it in all the auto release jobs, it's a bit risky. I think we need some testing results to prove its stability. otherwise if any incident occurred from cloud vendor side, it will kill all the auto release jobs running on issued platform.

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-automated-release-aws-ipi-private-shared-vpc-phz-sts-f360

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-automated-release-aws-ipi-private-shared-vpc-phz-sts-f360

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-automated-release-aws-usgov-ipi-private-ep-fips-f360

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-automated-release-aws-ipi-private-shared-vpc-phz-sts-f360

**Comment by wangke19** [comment]
/pj-rehearse  periodic-ci-openshift-openshift-tests-private-release-4.16-automated-release-azure-stack-upi-f360

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-automated-release-nutanix-ipi-proxy-fips-mini-perm-f360

**Comment by wangke19** [comment]
/pj-rehearse  periodic-ci-openshift-openshift-tests-private-release-4.16-automated-release-azure-ipi-marketplace-mini-perm-f360

**Comment by wangke19** [comment]
Currently, we have only one DR case OCP-19941, it meets the entry requirements for the automated release Prow Ci jobs. In the past 10 days, it was executed a total of 20 times, with 1 failures and 19 successes, pass raito:95%. We can get the detail from our `OCPQE Webapps`

**Comment by rioliu-rh** [comment]
I think we can add your DR test job as informing job, i.e. it will be triggered by auto release controller, but the test result will not be used for aggregation. we can monitor the test result continuously, if the test has high pass ratio on different platforms, we can add it to the auto release test chain, then it will take effective on all the test jobs.

**Comment by wangke19** [comment]
W created one Jira issue https://issues.redhat.com/browse/OCPQE-24145 to calculate pass ratio of aws platform, this task lasted almost 2 months, we got a good results, 100% pass ratio of LEVEL0 DR test cases on aws platform, detail see https://issues.redhat.com/browse/OCPQE-24145?focusedId=25399125&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-25399125, and we discussed in Slack: https://redhat-internal.slack.com/archives/CH76YSYSC/p1724312845274979?thread_ts=1724219560.343439&cid=CH76YSYSC, decided to a new auto release job instead of adding the step to auto release test chain. This behavior is under control.

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-automated-release-aws-ipi-private-fips-disasterrecovery-f360

**Comment by rioliu-rh** [comment]
do you want to run DR test only in this job? currently chain `openshift-e2e-test-qe-disasterrecovery-sanity` has step `openshift-extended-test`

**Comment by wangke19** [comment]
> do you want to run DR test only in this job? currently chain `openshift-e2e-test-qe-disasterrecovery-sanity` has step `openshift-extended-test`

These Level0 DR tests are run separately on a single platform, with no other tests running together, and after the DR tests are completed, it is necessary to run some basic sanity tests to ensure the success after the DR is done.

**Pull request closed without merging**
