### PR TITLE
MGMT-13264:assisted-common-post-install: fix UID

### PR DESCRIPTION
**Pull request by vrutkovs**
Make sure we run "fix UID" script before ssh'ing on the node to fetch kubeconfig and run teardown

### CODE REVIEW

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-metal-assisted
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-periodic

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted

Failed to fetch equinix terraform bundle

**Review by eliorerz — APPROVED** [review]
LGTM

**Pull request merged**
