### PR TITLE
Add basic CI for apiserver-library-go

### PR DESCRIPTION
**Pull request by sallyom**
Adding basic CI for openshift/apiserver-library-go
* verify
* verify-deps
* test-unit

### CODE REVIEW

**Comment by sallyom** [comment]
@deads2k running this PR against [this update to apiserver-library-go](https://github.com/openshift/apiserver-library-go/pull/2) is green for me, locally.

**Comment by sallyom** [comment]
lol not sure what's going on w/ those rehearse jobs, something isn't set up quite right though.. i'll figure it out tonight-outta time today

**Comment by petr-muller** [comment]
/retest
rehearsals were broken yesterday

**Comment by deads2k** [comment]
/lgtm

it's red and we'll fix it.

**Pull request merged**
