### PR TITLE
Updates prowconfig for managed gitops for branch off protection

### PR DESCRIPTION
**Pull request by samyak-jn**
This is a quick fix, to solve the CI failure because of branch protection: [logs](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-branch-protector/1528976944278802432)!

For more reference, check the slack thread, [here](https://coreos.slack.com/archives/CBN38N3MW/p1653391342347139).

CC: @smg247 

Signed-off-by: Samyak Jain <samyak.jn11@gmail.com>

### CODE REVIEW

**Comment by smg247** [comment]
I think you want your config to look more like: https://github.com/openshift/release/blob/master/core-services/prow/02_config/redhat-appstudio/infra-deployments/_prowconfig.yaml (just replace `infra-deployments` with `managed-gitops`).

**Comment by samyak-jn** [comment]
Hi @smg247, may I know more about why? I tried doing, exactly as mentioned in the document written [here](https://docs.ci.openshift.org/docs/architecture/branch-protection/#notes-on-protect-false)
For now, I checked how the product side of the team was doing it in [gitops-operator ](https://github.com/openshift/release/blob/master/core-services/prow/02_config/redhat-developer/gitops-operator/_prowconfig.yaml)and used the same here.
The CI fails due to linting issues, which I'm fixing atm as we speak

**Comment by smg247** [comment]
> Hi @smg247, may I know more about why? I tried doing, exactly as mentioned in the document written [here](https://docs.ci.openshift.org/docs/architecture/branch-protection/#notes-on-protect-false) For now, I checked how the product side of the team was doing it in [gitops-operator ](https://github.com/openshift/release/blob/master/core-services/prow/02_config/redhat-developer/gitops-operator/_prowconfig.yaml)and used the same here. The CI fails due to linting issues, which I'm fixing atm as we speak

Well you originally had it malformed, but what you have now looks okay to me. Of course, this is **your** config so you can set it up however you want, but if you have branch protection on (the default) you need to add the bot as an admin. Anyways, the way you have it now looks fine to me.

**Comment by samyak-jn** [comment]
Thanks for the update, can you point me in the right direction as to why the CI config is failing?

**Comment by smg247** [comment]
```
"msg":"the following orgs or repos enable the bugzilla plugin but do not forbid the bugzilla/invalid-bug label for merging: [repo: redhat-appstudio/managed-gitops]"
```

**Comment by smg247** [comment]
> Thanks for the update, can you point me in the right direction as to why the CI config is failing? Also, to add on, the branch protection is off on the managed-gitops repository (there are no rules as per see)
> 
> image (1)
> 
> Also, both the bots are already invited to the redhat-appstudio org!

yeah the issue there is that the `openshift-merge-robot` only has read access. again, not a problem with your current config, just update the bugzilla thing and you are good to go.

**Comment by samyak-jn** [comment]
Thank you for your quick responses on this, I highly appreciate it! :taco: :rocket:

**Pull request merged**
