### PR TITLE
bz and jira validation criteria after branching day

### PR DESCRIPTION
**Pull request by jmguzik**
Signed-off-by: Jakub Guzik <jguzik@redhat.com>

/cc @danilo-gemoli 
/cc @AlexNPavel 
@AlexNPavel please let us know if you spot any problem in the Jira plugin conf in this PR

### CODE REVIEW

**Comment by jmguzik** [comment]
/hold
I release at my convenience.

**Comment by danilo-gemoli** [comment]
/lgtm
/hold
looks good to me but let's wait for @AlexNPavel

**Pull request merged**
