### PR TITLE
Add virtualmedia and ipv6 jobs to image controller customization

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-image-customization-controller-main-e2e-metal-ipi-virtualmedia

**Comment by elfosardo** [comment]
unknown | /pj-rehearse pull-ci-openshift-image-customization-controller-release-4.15-e2e-metal-ipi-virtualmedia
-- | --

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-image-customization-controller-release-4.15-e2e-metal-ipi-virtualmedia

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-image-customization-controller-main-e2e-metal-ipi-virtualmedia

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-image-customization-controller-main-e2e-metal-ipi-virtualmedia

**Comment by elfosardo** [comment]
/pj-rehearse ack
this can go in

**Review by iurygregory — APPROVED** [review]

**Pull request merged**
