### PR TITLE
Update OLM operator version of AMQ Streams

### PR DESCRIPTION
**Pull request by im-konge**
This PR updates `OLM_OPERATOR_VERSION` for AMQ Streams operator after latest release.

### CODE REVIEW

**Comment by im-konge** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.14-lp-interop-amq-streams-2-4

**Comment by see-quick** [comment]
Hmmm, I am seeing a failure in build-clusters. I think you need to execute `make update-ci-build-clusters` to get it to work.

**Comment by im-konge** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.14-lp-interop-amq-streams-2-4

**Pull request merged**
