### PR TITLE
PowerVS: Add CAPI installer CI

### PR DESCRIPTION
**Pull request by hamzy**
Add a nightly CI run for the CAPI built installer on PowerVS

### CODE REVIEW

**Comment by hamzy** [comment]
/pj-rehearse periodic-ci-openshift-installer-master-altinfra-periodics-e2e-powervs-capi-ovn

**Comment by hamzy** [comment]
/pj-rehearse periodic-ci-openshift-installer-master-altinfra-periodics-e2e-powervs-capi-ovn

**Comment by hamzy** [comment]
I watched a successful create cluster.  The e2e tests probably won't all pass.

**Review by r4f4 — COMMENTED** [review]
/approve

**Pull request merged**
