### PR TITLE
Serverless: pre-submit and nightly job on OCP 4.11

### PR DESCRIPTION
**Pull request by mgencur**
https://issues.redhat.com/browse/SRVCOM-2052

The weekly jobs (azure, gcp, ovn, etc.) will be migrated in the next round.

### CODE REVIEW

**Comment by mgencur** [comment]
The failures are being resolved in https://github.com/openshift-knative/serverless-operator/pull/1679 and that PR should be merged first.

**Comment by skonto** [comment]
@mgencur rebase gentle ping and let's try again.

**Comment by mgencur** [comment]
@skonto this is ready.

**Review by pierDipi — APPROVED** [review]
/lgtm

**Pull request merged**
