### PR TITLE
OSSM-3811 Update maistra workflows with prow job env variables

### PR DESCRIPTION
**Pull request by yxun**

### CODE REVIEW

**Comment by jwendell** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-integ-helm-2-4

**Review by jwendell — CHANGES_REQUESTED** [review]
I don't think this worked. There's no junit file here: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/38814/rehearse-38814-pull-ci-maistra-istio-maistra-2.4-integ-helm-2-4/1651643404875993088/artifacts/integ-helm-2-4/integ-helm-2-4/

In fact, in build.log you see that the artifacts dir is created because the ARTIFACT variable is not defined. Here's the source: https://github.com/maistra/istio/blob/maistra-2.4/prow/integ-suite-kind.sh#L140

**Comment by yxun** [comment]
> I don't think this worked. There's no junit file here: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/38814/rehearse-38814-pull-ci-maistra-istio-maistra-2.4-integ-helm-2-4/1651643404875993088/artifacts/integ-helm-2-4/integ-helm-2-4/
> 
> In fact, in build.log you see that the artifacts dir is created because the ARTIFACT variable is not defined. Here's the source: https://github.com/maistra/istio/blob/maistra-2.4/prow/integ-suite-kind.sh#L140

I think the ARTIFACT was renamed in Openshift CI as ARTIFACT_DIR
Let me create another commit

**Comment by jwendell** [comment]
It should be `ARTIFACTS`, in plural.

**Comment by yxun** [comment]
> It should be `ARTIFACTS`, in plural.

well, they overwrite that. Check my log here:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/38814/rehearse-38814-pull-ci-maistra-istio-maistra-3.0-test-prow-env/1651611180378099712/artifacts/test-prow-env/build/build-log.txt
ARTIFACTS=
ARTIFACT_DIR=/logs/artifacts

More ref: https://github.com/openshift/release/blob/master/ci-operator/config/kube-reporting/metering-operator/kube-reporting-metering-operator-master.yaml#L86
 I think when they set up Prow , they overwrite that default variable name to ARTIFACT_DIR
 but anyway, I can have a workaround

**Comment by yxun** [comment]
I searched the usage of  "ARTIFACTS" in maistra org repos. 
https://github.com/search?q=org%3Amaistra+ARTIFACTS&type=code&p=1
And Add a commit about this env variable name mapping. 
It looks like maistra/istio mentions "ARTIFACTS"
And maistra/proxy mentions both "ARTIFACTS" and "ARTIFACT_DIR"

**Comment by yxun** [comment]
correct my last comment:
> And maistra/proxy mentions both "ARTIFACTS" and "ARTIFACTS_DIR"
The "ARTIFACTS_DIR" in proxy repo is not relevant to this PR

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-integ-helm-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-maistra-istio-lint-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-integ-helm-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-maistra-istio-lint-2-4

**Comment by jwendell** [comment]
It seems better now, as I can see *some* artifacts. Do you know where `junit.xml` is? It was supposed to be in the root artifacts dir: https://github.com/maistra/istio/blob/maistra-2.4/Makefile.core.mk#L99 but I cannot find it anywhere.

**Comment by yxun** [comment]
> It seems better now, as I can see _some_ artifacts. Do you know where `junit.xml` is? It was supposed to be in the root artifacts dir: https://github.com/maistra/istio/blob/maistra-2.4/Makefile.core.mk#L99 but I cannot find it anywhere.

the directory should be :
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/38814/rehearse-38814-pull-ci-maistra-istio-maistra-2.4-integ-helm-2-4/1651699204357099520/artifacts/integ-helm-2-4/copy-artifacts/artifacts/

I will check why the integ test run does not generate junit.xml file there

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-integ-helm-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-integ-helm-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-integ-helm-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-integ-helm-2-4

**Comment by yxun** [comment]
> It seems better now, as I can see _some_ artifacts. Do you know where `junit.xml` is? It was supposed to be in the root artifacts dir: https://github.com/maistra/istio/blob/maistra-2.4/Makefile.core.mk#L99 but I cannot find it anywhere.

The go-junit-report was not installed in the /usr/bin/
[> sh: /usr/bin/go-junit-report: No such file or directory
command terminated with exit code 127](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/38814/rehearse-38814-pull-ci-maistra-istio-maistra-2.4-integ-helm-2-4/1652037422512345088/artifacts/integ-helm-2-4/integ-helm-2-4/build-log.txt)

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-integ-helm-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-integ-helm-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-integ-helm-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-integ-helm-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-integ-helm-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-integ-helm-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-integ-helm-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-integ-helm-2-4

**Review by jwendell — COMMENTED** [review]
Where's the build.log now? It looks like it's gone.

**Comment by yxun** [comment]
> Where's the build.log now? It looks like it's gone.

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/38814/rehearse-38814-pull-ci-maistra-istio-maistra-2.4-integ-helm-2-4/1655979522639532032/artifacts/integ-helm-2-4/integ-helm-2-4/build-log.txt

We defined an istio integ test as a CI steps test. That's an annoying feature from openshift CI . They embedded job logs in directories

**Review by jwendell — APPROVED** [review]

**Pull request merged**
