### PR TITLE
Fix typo of COO clust poos

### PR DESCRIPTION
**Pull request by lihongyan1**

### CODE REVIEW

**Review by IshwarKanse — APPROVED** [review]
/lgtm

**Review by vprashar2929 — APPROVED** [review]
/lgtm

**Comment by lihongyan1** [comment]
@cahartma Please help review and approve the PR, though @vprashar2929 has approved, not sure why the PR failed to be auto merged

**Comment by lihongyan1** [comment]
@Clee2691 Please help review the PR

**Pull request merged**
