### PR TITLE
Adapt: aws-local-zone

### PR DESCRIPTION
**Pull request by Phaow**
Fix: [OCPQE-13496](https://issues.redhat.com/browse/OCPQE-13496)

As currently `gp3` type volumes not available on aws local zones, change the default storageClass from `gp3-csi` to `gp2-csi` for enhancement.

### CODE REVIEW

**Comment by Phaow** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-network-mtu-localzone-pewang-debug

**Comment by Phaow** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-network-mtu-localzone-pewang-debug

**Comment by Phaow** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-network-mtu-localzone-pewang-debug

**Comment by Phaow** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-network-mtu-localzone-pewang-debug

**Comment by Phaow** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-network-mtu-localzone-pewang-debug

**Comment by Phaow** [comment]
/assign @duanwei33 @yunjiang29 @jianlinliu 
Could you please help take a look when you get a chance? Thanks!

**Comment by Phaow** [comment]
[Default storageclass set successfully log](https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/37249/rehearse-37249-periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-network-mtu-localzone-pewang-debug/1635680479527047168/artifacts/aws-ipi-network-mtu-localzone-pewang-debug/storage-conf-storageclass-set-default-storageclass/build-log.txt)
[The case OCP-28018 passed log](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/37249/rehearse-37249-periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-network-mtu-localzone-pewang-debug/1635680479527047168)

**FYI**
For storage cases failures part, we'll handdle them in the case logic to adapt aws local zone clusters.

**Comment by yunjiang29** [comment]
@Phaow following chains for LZ feature are also required to update:

* 4.12 only
```
cucushift-installer-rehearse-aws-ipi-network-mtu-localzone-provision
cucushift-installer-rehearse-aws-ipi-network-mtu-localzone-sdn-provision
```

* 4.13+
```
cucushift-installer-rehearse-aws-ipi-localzone-provision
cucushift-installer-rehearse-aws-ipi-localzone-sdn-provision
```

* 4.12+
```
cucushift-installer-rehearse-aws-ipi-disconnected-private-network-mtu-localzone-provision
```

**Comment by Phaow** [comment]
@yunjiang29 Thanks for the details! Updated, could you please help take a look when you get a chance? Thanks!

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-localzone-p2-f14

**Comment by yunjiang29** [comment]
```
no proxy setting.
Current default storageclass is: gp3-csi
Running Command: oc annotate sc storageclass.kubernetes.io/is-default-class=false --all --overwrite
storageclass.storage.k8s.io/gp2-csi annotated
storageclass.storage.k8s.io/gp3-csi annotated
Running Command: oc annotate sc gp2-csi storageclass.kubernetes.io/is-default-class=true --overwrite
storageclass.storage.k8s.io/gp2-csi annotated
Running Command: oc get sc
NAME                PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2-csi (default)   ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   25m
gp3-csi             ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   25m
```

**Pull request merged**
