### PR TITLE
ci-operator/templates/openshift: Get e2e-aws out of us-east-1b

### PR DESCRIPTION
**Pull request by wking**
We're currently getting a lot of 500s there [like][1]:

```
time="2019-03-22T18:02:51Z" level=debug msg="2019-03-22T18:02:51.255Z [DEBUG] plugin.terraform-provider-aws: 2019/03/22 18:02:51 [DEBUG] [aws-sdk-go] DEBUG: Response ec2/RunInstances Details:"
time="2019-03-22T18:02:51Z" level=debug msg="2019-03-22T18:02:51.255Z [DEBUG] plugin.terraform-provider-aws: ---[ RESPONSE ]--------------------------------------"
time="2019-03-22T18:02:51Z" level=debug msg="2019-03-22T18:02:51.255Z [DEBUG] plugin.terraform-provider-aws: HTTP/1.1 500 Internal Server Error"
```

Looking at the results of this Athena query:

```sql
SELECT *
FROM "default"."cloudtrail_logs_cloud_trail_test_clayton"
WHERE from_iso8601_timestamp(eventtime) > date_add('hour', -4, now())
  AND eventname = 'RunInstances'
  AND errorcode = 'Server.InternalError'
ORDER BY eventtime;
```

They're all in 1b:

```console
$ for ZONE in a b c d e f g; do echo "${ZONE} $(grep -c "us-east-1${ZONE}" c128e363-4791-4049-8936-aafc6e2e36dd.csv)"; done
a 0
b 181
c 0
d 0
e 0
f 0
g 0
```

This commit moves us to 1d instead.

@staebler, when I try this locally I get:

```
ERROR  * module.masters.aws_network_interface.master[1]: key "us-east-1c" does not exist in map var.az_to_subnet_id in:
ERROR
ERROR ${var.az_to_subnet_id[var.availability_zones[count.index]]}
ERROR  * module.masters.aws_network_interface.master[2]: key "us-east-1d" does not exist in map var.az_to_subnet_id in:
ERROR
ERROR ${var.az_to_subnet_id[var.availability_zones[count.index]]}
ERROR  * module.masters.aws_network_interface.master[0]: key "us-east-1a" does not exist in map var.az_to_subnet_id in:
ERROR
ERROR ${var.az_to_subnet_id[var.availability_zones[count.index]]}
ERROR  * module.bootstrap.var.subnet_id: key "us-east-1a" does not exist in map module.vpc.az_to_public_subnet_id in:
ERROR
ERROR ${module.vpc.az_to_public_subnet_id[var.aws_master_availability_zones[0]]}
```

Guesses?

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/operator-framework_operator-lifecycle-manager/777/pull-ci-operator-framework-operator-lifecycle-manager-master-e2e-aws-olm/1365/artifacts/e2e-aws-olm/installer/.openshift_install.log

### CODE REVIEW

**Comment by wking** [comment]
CC @vrutkovs, @sdodson too, since I'm touching the Ansible stuff.

**Comment by wking** [comment]
/hold cancel

Working for @abhinavdahiya.  My error was forgetting to change my usual `platform.aws.region` from `us-west-2` to `us-east-1` :man_facepalming: .  After this PR lands I'll file a new validation check ;).

**Comment by sdodson** [comment]
Over what time period has this been an issue?

**Comment by smarterclayton** [comment]
/lgtm

Also, we need to start moving these out of the template and into a profile - as it is right now you'd have to also change ci-operator in order to fix upgrade jobs but we can let those fail for a bit.

**Comment by wking** [comment]
> Over what time period has this been an issue?

Sorry, missed this in the excitement.

run-instances

**Pull request merged**
