### PR TITLE
kubevirt: vm-console-proxy: Update Golang to 1.21

### PR DESCRIPTION
**Pull request by akrejcir**
Updated build root image to: `rhel-9-golang-1.21-openshift-4.16`

### CODE REVIEW

**Review by 0xFelix — APPROVED** [review]
/approve

**Comment by akrejcir** [comment]
Yes, I'm working on it. I will post an update soon.

**Comment by 0xFelix** [comment]
`envsubst` is also missing.

**Comment by akrejcir** [comment]
Updated.

**Review by 0xFelix — APPROVED** [review]
/lgtm

**Pull request merged**
