### PR TITLE
R.I.P tracer

### PR DESCRIPTION
**Pull request by droslean**
We don't need `tracer`. We have `stackdriver`. Also, tracer is not able to get any logs if any of prow's pod has been redeployed.

### CODE REVIEW

**Comment by petr-muller** [comment]
I still use this for quick diagnostics, can we keep it?

**Comment by droslean** [comment]
Well, we can use stackdriver.  I like the idea of getting rid of it. Less stuff to maintain, less stuff running to the cluster etc... But its fine from my side to keep it.

**Comment by droslean** [comment]
/close 
let's keep it.

**Pull request closed without merging**
