### PR TITLE
MSI: upate operator workflow

### PR DESCRIPTION
**Pull request by rnetser**

### CODE REVIEW

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-rhods-operator-v4.13-hypershift-GA-production-smoke-rosa-rhods-hypershift-fips

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-rhods-operator-v4.13-hypershift-GA-production-smoke-rosa-rhods-hypershift-fips

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-rhods-operator-v4.13-hypershift-GA-production-smoke-rosa-rhods-hypershift

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-rhods-operator-v4.13-hypershift-IIB-smoke-rosa-rhods-hypershift

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-rhods-operator-v4.13-hypershift-IIB-smoke-rosa-rhods-hypershift

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-rhods-operator-v4.13-hypershift-IIB-smoke-rosa-rhods-hypershift

**Review by myakove — APPROVED** [review]

**Review by myakove — APPROVED** [review]

**Pull request merged**
