### PR TITLE
Kam secret path update

### PR DESCRIPTION
**Pull request by amitkrout**
Mounting kam bootstrap secrets into specific mount directory

### CODE REVIEW

**Comment by amitkrout** [comment]
```
$ oc login --token=**** --server=https://api.ci.l2s4.p1.openshiftapps.com:6443
$ oc create secret --namespace kam generic kam-quay-docker-conf-secret --from-file kam-bot-kambot-auth.json
$ oc create secret --namespace kam generic kam-github-secret --from-file secret.txt
$ oc get secret -n kam
NAME                          TYPE                                  DATA   AGE
[...]
kam-github-secret             Opaque                                1      48s
kam-quay-docker-conf-secret   Opaque                                1      2m14s
```
/retest

**Review by droslean — APPROVED** [review]

**Pull request merged**
