### PR TITLE
Fix secret error on the CI because of large file part of secret directory

### PR DESCRIPTION
**Pull request by praveenkumar**
Currently secret wrapper is trying to create a secret with all contents that are in /tmp/secret folder.

- failed to create/update secret: failed to update secret: Request entity too large: limit is 3145728

### CODE REVIEW

**Review by cfergeau — COMMENTED** [review]
`$HOME` is `/tmp/secret`?

**Comment by praveenkumar** [comment]
> $HOME is /tmp/secret?

@cfergeau  yes.

**Pull request merged**
