### PR TITLE
ipi-deprovision: add a job that does GCE and AWS

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

depends on https://github.com/openshift/ci-tools/pull/380

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
All working now, we can merge https://github.com/openshift/ci-tools/pull/385 when we're ready and rehearse it here.

**Comment by wking** [comment]
/lgtm
/hold

Not clear on why [the future run][1] got marked failed, or whether you want to wait on openshift/ci-tools#387, but this looks pretty good to me.

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/6756/rehearse-6756-periodic-ipi-deprovision-future/9

**Comment by stevekuznetsov** [comment]
```
$ oc logs -f 4eb82c6f-3985-11ea-baf6-0a58ac10375e -c test
Searching for clusters with a TTL of 30 minutes ago
cluster_age_cutoff: 2020-01-17T23:29+0000
deprovisioning in AWS ...
deprovisioning in AWS region eu-north-1 ...
deprovisioning in AWS region ap-south-1 ...
deprovisioning in AWS region eu-west-3 ...
deprovisioning in AWS region eu-west-2 ...
deprovisioning in AWS region eu-west-1 ...
deprovisioning in AWS region ap-northeast-2 ...
deprovisioning in AWS region ap-northeast-1 ...
deprovisioning in AWS region sa-east-1 ...
deprovisioning in AWS region ca-central-1 ...
deprovisioning in AWS region ap-southeast-1 ...
deprovisioning in AWS region ap-southeast-2 ...
deprovisioning in AWS region eu-central-1 ...
deprovisioning in AWS region us-east-1 ...
deprovisioning in AWS region us-east-2 ...
deprovisioning in AWS region us-west-1 ...
deprovisioning in AWS region us-west-2 ...
deprovisioning in GCE ...
Activated service account credentials for: [ci-provisioner@openshift-gce-devel-ci.iam.gserviceaccount.com]
will deprovision GCE cluster ci-op--jphfv in region us-east1:
{
  "infraID":"ci-op--jphfv",
  "gcp":{
    "region":"us-east1",
    "projectID":"openshift-gce-devel-ci"
  }
}
will deprovision GCE cluster ci-op--xkb7r in region us-east1:
{
  "infraID":"ci-op--xkb7r",
  "gcp":{
    "region":"us-east1",
    "projectID":"openshift-gce-devel-ci"
  }
}
will deprovision GCE cluster ci-op-2wzz4 in region us-east1:
{
  "infraID":"ci-op-2wzz4",
  "gcp":{
    "region":"us-east1",
    "projectID":"openshift-gce-devel-ci"
  }
}
will deprovision GCE cluster ci-op-4gqdt in region us-east1:
{
  "infraID":"ci-op-4gqdt",
  "gcp":{
    "region":"us-east1",
    "projectID":"openshift-gce-devel-ci"
  }
}
openshift-install --dir /tmp/deprovision/ci-op-4gqdt --log-level debug destroy cluster
openshift-install --dir /tmp/deprovision/ci-op--xkb7r --log-level debug destroy cluster
openshift-install --dir /tmp/deprovision/ci-op--jphfv --log-level debug destroy cluster
openshift-install --dir /tmp/deprovision/ci-op-2wzz4 --log-level debug destroy cluster
Deprovision finished successfully
```

**Comment by stevekuznetsov** [comment]
OK, so it works. The most conservative path forward:

 - turn off current ipi-deprovision and force stale clusters somewhow
 - run a rehearsal to show that this handles AWS correctly
 - merge https://github.com/openshift/ci-tools/pull/385 to make it not dry-run
 - rehearse to show that the prod code works
 - merge this PR


The less conservative but way more quick path:

 - merge this PR
 - merge https://github.com/openshift/ci-tools/pull/385
 - turn off `ipi-deprovision`
 - leave for the weekend
 - fix bugs on Monday

**Pull request merged**
