### PR TITLE
gather-cert-rotation: update sosreport collect procedure

### PR DESCRIPTION
**Pull request by vrutkovs**
No need to run SOS in interactive podman - and there is no reason to ignore its results

### CODE REVIEW

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-180d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-180d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-180d pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-360d pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-suspend-180d pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-suspend-360d

**Comment by vrutkovs** [comment]
/pj-rehearse ack

All four jobs have collected artifacts:
* https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/43112/rehearse-43112-pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-180d/1699803630963527680/artifacts/e2e-metal-ovn-ha-cert-rotation-shutdown-180d/gather-cert-rotation/artifacts/
* https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/43112/rehearse-43112-pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-360d/1699803631034830848/artifacts/e2e-metal-ovn-ha-cert-rotation-shutdown-360d/gather-cert-rotation/artifacts/
* https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/43112/rehearse-43112-pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-suspend-180d/1699803631089356800/artifacts/e2e-metal-ovn-ha-cert-rotation-suspend-180d/gather-cert-rotation/artifacts/
* https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/43112/rehearse-43112-pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-suspend-360d/1699803631148077056/artifacts/e2e-metal-ovn-ha-cert-rotation-suspend-360d/gather-cert-rotation/artifacts/

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Pull request merged**
