### PR TITLE
add end-to-end job

### PR DESCRIPTION
**Pull request by deads2k**

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
You'll also need to update the submitqueue configmap -- `cluster/ci/config/submit-queue/submit_queue.yaml`

**Comment by kargakis** [comment]
It would be nice to have a solution for running new jobs in existing PRs. Right now we have to manually /test end-to-end?

**Comment by stevekuznetsov** [comment]
I don't think so, prow will trigger it automatically when it refreshes

**Comment by stevekuznetsov** [comment]
> prow will trigger it automatically when it refreshes

well, if it has any reason to refresh the PR, that is. hmm - we should probably suggest this upstream?

**Comment by kargakis** [comment]
Yeah, we should discuss. A retester postsubmit triggered when the prow config gets updated is probably enough (in the future, prow config will live inside origin, for now we can use the release repo). I will test tomorrow.

**Pull request merged**
