### PR TITLE
Sync back BM IPI virtual media jobs

### PR DESCRIPTION
**Pull request by jadhaj**

### CODE REVIEW

**Comment by jadhaj** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-multi-nightly-baremetal-ipi-ovn-dualstack-amd-vmedia-f7

**Comment by jadhaj** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-multi-nightly-baremetal-ipi-ovn-dualstack-amd-vmedia-f7 cancel

**Comment by jadhaj** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-multi-nightly-baremetal-ipi-ovn-dualstack-amd-vmedia-f7

**Comment by jadhaj** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-multi-nightly-baremetal-ipi-ovn-ipv4-fips-vmedia-amd-f28

**Comment by kuiwang02** [comment]
@jadhaj FYI https://github.com/openshift/release/pull/56335#issuecomment-2357278605

**Pull request merged**
