### PR TITLE
Metallb: update image tags in main yaml to 4.17

### PR DESCRIPTION
**Pull request by karampok**

### CODE REVIEW

**Comment by karampok** [comment]
```
operatorhub.config.openshift.io/cluster patched
++(./deploy_metallb.sh:45): oc -n openshift-marketplace get sa builder -oyaml
++(./deploy_metallb.sh:45): grep imagePullSecrets -A 1
++(./deploy_metallb.sh:45): grep -o 'builder-.*'
+(./deploy_metallb.sh:45): secret=
+(./deploy_metallb.sh:75): buildindexpod='apiVersion: v1
kind: Pod
metadata:
  name: buildindex
  namespace: openshift-marketplace
spec:
  restartPolicy: Never
  serviceAccountName: builder
  containers:
    - name: priv
      image: quay.io/podman/stable
      command:
        - /bin/bash
        - -c
        - |
          set -xe
          sleep INF
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/run/secrets/openshift.io/push
          name: dockercfg
          readOnly: true
  volumes:
    - name: dockercfg
      defaultMode: 384
      secret:
        secretName: 
'
+(./deploy_metallb.sh:77): echo 'apiVersion: v1
kind: Pod
metadata:
  name: buildindex
  namespace: openshift-marketplace
spec:
  restartPolicy: Never
  serviceAccountName: builder
  containers:
    - name: priv
      image: quay.io/podman/stable
      command:
        - /bin/bash
        - -c
        - |
          set -xe
          sleep INF
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/run/secrets/openshift.io/push
          name: dockercfg
          readOnly: true
  volumes:
    - name: dockercfg
      defaultMode: 384
      secret:
        secretName: 
'
+(./deploy_metallb.sh:77): oc apply -f -
The Pod "buildindex" is invalid: 
* spec.volumes[0].secret.secretName: Required value
* spec.containers[0].volumeMounts[0].name: Not found: "dockercfg"
+(./deploy_metallb.sh:79): success=0
````
this why the ipi fails

**Comment by fedepaol** [comment]
> this why the ipi fails

Let's give it another shot. The frr-k8s lane is doing the same but passed.

**Pull request merged**
