### PR TITLE
[OCPQE-22232][wip]add prow debug vsphere2

### PR DESCRIPTION
**Pull request by weinliu**

### CODE REVIEW

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by kuiwang02** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
close due to some docker failure, new one created: https://github.com/openshift/release/pull/54568

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by miyadav** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Pull request closed without merging**
