### PR TITLE
Remove RBAC of getting ns to access grafana

### PR DESCRIPTION
**Pull request by hongkailiu**
See https://jira.coreos.com/browse/DPTP-423

### CODE REVIEW

**Comment by hongkailiu** [comment]
/hold
Manual testing is ongoing.

**Comment by hongkailiu** [comment]
/hold cancel
Test passed with @e-tienne  . Many thanks.

**Comment by hongkailiu** [comment]
> Doesn't this open it up to the whole world?

It is open to all authenticated users.
But yes, if every github user can do the authentication (does it require a redhat email or anything similar?), then it is open to all github users.

**Comment by hongkailiu** [comment]
Tried with my gh test account. This is the error message.
```
This cluster is configured to use GitHub OAuth authentication. You need to be a member of the OpenShift GitHub organization to be able to log in.
```

**Comment by hongkailiu** [comment]
Also checked this
```
$ oc exec --as system:admin  -n kube-system master-api-<top-secret> -- grep oauthConfig /etc/origin/master/master-config.yaml -A 16
```

I think that my theory is correct. GH users with redhat org have access, NOT any github user.

Since it is kind of important feature, it is better you double-check with a testing account which is not in red-hat. :)

**Comment by stevekuznetsov** [comment]
OK, I tested it with my bot, this is working.

/lgt,

**Pull request merged**
