### PR TITLE
Add e2e-openstack-ipi job to mdns-publisher

### PR DESCRIPTION
**Pull request by mandre**
Always runs, non-voting.

### CODE REVIEW

**Comment by cybertron** [comment]
Great, thanks! Just waiting for the job to pass.

**Comment by cybertron** [comment]
Since this is a non-blocking job, if the flakiness is just in the job itself and not the ci configuration we do have the option of just merging it. As long as it accurately represents the state of openstack ci it's doing the job.

**Comment by iamemilio** [comment]
true, I think we can just merge this. 

/approve

**Pull request merged**
