### PR TITLE
disruptive-workflows: port release 4.x disruptive tests to workflows

### PR DESCRIPTION
**Pull request by vrutkovs**
Affected components:
* cluster-etcd-operator
* installer
* machine-api-operator
* machine-config-operator
* kubernetes
* origin

This makes use of workflows (introduced in https://github.com/openshift/release/pull/17556) and adds Loki logging for these tests

### CODE REVIEW

**Comment by marun** [comment]
/lgtm

Also, all of these jobs are currently optional, so merging doesn't risk blocking merge for any of the affected repos.

**Comment by smarterclayton** [comment]
lgtm as well

**Comment by yuqi-zhang** [comment]
If I understand correctly this doesn't affect how the MCO tests are ran (optional, etc.), just makes use of the workflow right?
If so lgtm

**Comment by vrutkovs** [comment]
>this doesn't affect how the MCO tests are ran (optional, etc.), just makes use of the workflow right

correct, no changes to optional or new tests added

**Pull request merged**
