### PR TITLE
Move promotion to redhatdeveloper because redhat-. is forbidden by oc…

### PR DESCRIPTION
**Pull request by akram**
…p4 on osd

### CODE REVIEW

**Comment by hongkailiu** [comment]
Thanks for the renaming.

2 more places:
https://github.com/openshift/release/blob/master/clusters/app.ci/assets/dptp-controller-manager.yaml#L142

and

https://github.com/openshift/release/tree/master/clusters/app.ci/redhat-developer
The folder name, the file name, and the object name in the file.

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
