### PR TITLE
OCPQE-25552: Use 4.17.0-rc.1 as the initial image for rollback tests

### PR DESCRIPTION
**Pull request by fxierh**
There is a bug preventing the creation of 4.17.0-rc.0 hosted clusters on Azure.

https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/56556/rehearse-56556-periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-rollback-nightly-azure-aks-hypershift-byo-vnet-replace-guest-f7/1833837406273409024

### CODE REVIEW

**Comment by fxierh** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-rollback-nightly-azure-aks-hypershift-byo-vnet-replace-guest-f7

**Comment by fxierh** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-rollback-nightly-azure-aks-hypershift-byo-vnet-replace-guest-f7

**Comment by fxierh** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-rollback-nightly-azure-aks-hypershift-byo-vnet-replace-guest-f7

**Comment by fxierh** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-rollback-nightly-azure-aks-hypershift-byo-vnet-replace-guest-f7

**Comment by liangxia** [comment]
> There is a bug preventing the creation of 4.17.0-rc.0 hosted clusters on Azure.
> 
> https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/56556/rehearse-56556-periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-rollback-nightly-azure-aks-hypershift-byo-vnet-replace-guest-f7/1833837406273409024

The linked job passed.  Wrong link ?
BTW,  Is there a link for the bug  ?

**Comment by fxierh** [comment]
@liangxia 

The linked job is the result of rehearsal with RC1. 

Failure with RC0: https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-rollback-nightly-azure-aks-hypershift-byo-vnet-replace-guest-f7/1833771707576356864

Link to the bug: https://issues.redhat.com/browse/HOSTEDCP-1764 (opened as a story but could actually be considered as a bug because annotations on the HC resource was only needed when the MC is AKS but not OpenShift)

**Pull request merged**
