### PR TITLE
run build extended tests if code impacting them changes

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton @stevekuznetsov ptal
@openshift/devex fyi

**Comment by stevekuznetsov** [comment]
No heart emoji from @gabemontero ... make of that what you will

**Comment by stevekuznetsov** [comment]
Updated the config -- this should be live now

**Comment by gabemontero** [comment]
heart emoji added (along with @coreydaley 's :-) )

**Pull request merged**
