### PR TITLE
MSI: Use openshift-cli-installer in RHODS tests

### PR DESCRIPTION
**Pull request by rnetser**

### CODE REVIEW

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-aws-ipi-rhods-addon-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-aws-ipi-rhods-addon-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-aws-ipi-rhods-addon-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-aws-ipi-rhods-addon-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-osd-rhods-addon-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-osd-rhods-addon-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-osd-rhods-addon-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-osd-rhods-addon-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-osd-rhods-addon-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-osd-rhods-addon-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-osd-rhods-addon-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-rhods-addon-interop-v4.14-GA-smoke-rosa-rhods-addon-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-osd-rhods-addon-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-rhods-addon-interop-v4.14-GA-smoke-rosa-rhods-addon-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-osd-rhods-addon-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-osd-rhods-addon-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-osd-rhods-addon-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-osd-rhods-addon-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-osd-rhods-addon-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-osd-rhods-addon-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-osd-rhods-addon-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-osd-rhods-addon-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-osd-rhods-addon-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-aws-ipi-rhods-addon-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-IIB-smoke-rosa-rhods-addon-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Review by myakove — APPROVED** [review]

**Pull request merged**
