### PR TITLE
Add support for Podman in Makefile

### PR DESCRIPTION
**Pull request by eisraeli**
Check whether Podman or Docker container-engine is installed and enable
the use of Podman as well, instead of failing in case only Docker is
installed. Also reports an error in case no container-engine is installed.

### CODE REVIEW

**Comment by eisraeli** [comment]
@bbguimaraes 
Those 2 tests fail on an error message I've added in case no container-engine (neither Docker or Podman) can be found. 
Any insight on that ?

**Comment by bbguimaraes** [comment]
This Makefile is used in our tests, which are executed in containers that don't have `docker` (or `podman`) installed.

Every distribution I use has a [`podman-docker`](https://apps.fedoraproject.org/packages/podman-docker) package that translates `docker` commands to `podman`, I don't have `docker` installed and never had any problem using our tools.

**Comment by eisraeli** [comment]
I'm running Fedora 31. When I tried to use the Makefile like this:
`$ make new-repo`

This was the output I was getting:
```
docker pull registry.svc.ci.openshift.org/ci/repo-init:latest
bash: docker: command not found
make: *** [Makefile:63: new-repo] Error 127
```

**Comment by giuseppe** [comment]
could you please rebase it?  I think it is still useful, I've encountered the same issue

**Comment by eisraeli** [comment]
@giuseppe Since this wasn't merged, I suggest you install the 'podman-docker' package.
It should solve this issue. I thought that this PR should be merged or at least let Podman users know that the 'podman-docker' package is mandatory for using the makefile.

**Comment by eisraeli** [comment]
I see my changes were already incorporated into on another PR.
Closing this one.

**Pull request closed without merging**
