### PR TITLE
[WIP] Add new 4.14 Rosa tests along with cron.

### PR DESCRIPTION
**Pull request by svetsa-rh**
Adding 4.14 nightly tests for cluster-density, cluster-density-v2 and node-density for sanity testing and to kick off 4.14 testing on rosa.

### CODE REVIEW

**Comment by svetsa-rh** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-nightly-ocp-qe-perfscale-ci-tests-rosa-node-density periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-nightly-ocp-qe-perfscale-ci-tests-rosa-cluster-density-v2 periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-nightly-ocp-qe-perfscale-ci-tests-rosa-cluster-density

**Comment by paigerube14** [comment]
@svetsa-rh should we close this? I think this is already incorporated into prow

**Comment by svetsa-rh** [comment]
@paigerube14 No, this is not done yet.

The runs are currently failing with:
ERR: Error getting version: A valid policy version number must be specified
Valid versions: [4.7, 4.8, 4.10, 4.11, 4.12, 4.13]

I found some info related to this but haven't spent enough time to try the suggestions or find more info. Will look into it.

**Comment by paigerube14** [comment]
@svetsa-rh ah sorry didn't see it was rosa specific. Can you add to the title maybe?

**Comment by svetsa-rh** [comment]
Done

**Comment by svetsa-rh** [comment]
We have new tests being added for 4.14 in other PRs. Closing this old one.

**Pull request closed without merging**
