### PR TITLE
GitOps operator- Enable test runs on v1.6 branch

### PR DESCRIPTION
**Pull request by varshab1210**

### CODE REVIEW

**Review by wtam2018 — COMMENTED** [review]
/lgtm

**Comment by varshab1210** [comment]
@hongkailiu Please review the PR and merge if it looks good
Thanks!

**Comment by wtam2018** [comment]
/hold
@varshab1210 please add v4.9 e2e tests execution.

**Comment by varshab1210** [comment]
Hi @wtam2018 
Could you please merge this?
Thanks!

**Pull request closed without merging**
