### PR TITLE
Add bpfman and bpfman-operator to openshift-ci

### PR DESCRIPTION
**Pull request by msherif1234**

### CODE REVIEW

**Comment by msherif1234** [comment]
/pj-rehearse pull-ci-openshift-bpfman-operator-main-ci-bundle-operatorbundle

**Comment by msherif1234** [comment]
/pj-rehearse pull-ci-openshift-bpfman-main-images pull-ci-openshift-bpfman-main-security

**Review by Billy99 — APPROVED** [review]
/lgtm

**Pull request merged**
