### PR TITLE
Create presubmit configuration for kubevirt/kubevirt, fix nightly

### PR DESCRIPTION
**Pull request by dhiller**
Remove script from config, point to kubevirt/kubevirt test script
instead. Point to new script for pr testing.
Increase test pod memory limit to avoid OOMKilled.

Counterpart to kubevirt/kubevirt#3514

/cc @rmohr @danielBelenky

### CODE REVIEW

**Comment by dhiller** [comment]
Of course tests will fail currently as the counterpart has not been merged yet.

**Comment by dhiller** [comment]
/assign @crawford

had to increase the memory for the test pod to avoid getting OOMKilled.

**Comment by dhiller** [comment]
@sdodson sorry for pinging you, you were the approver for the template changes last time. I just increased the pod memory limit to avoid it getting OOMKillled. Can you take a look please? Thanks!

**Comment by sdodson** [comment]
/test pj-rehearse
This should pass now, correct?

**Comment by dhiller** [comment]
@sdodson no, not all will pass. as we still have to fix a problem on the other side (i.e. kubevirt/kubevirt). But we require these changes to be able to fix it.

**Comment by dhiller** [comment]
BTW the checks regarding awws and azure I don't have any clue about.

**Pull request merged**
