### PR TITLE
switch to aws-opendatahub cluster profile

### PR DESCRIPTION
**Pull request by riprasad**

### CODE REVIEW

**Comment by riprasad** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-release-v0.11.0-alpha-fvt

**Comment by riprasad** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-release-v0.11.0-alpha-fvt

**Comment by riprasad** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-release-v0.11.0-alpha-fvt

**Review by israel-hdez — APPROVED** [review]
Thanks @riprasad

**Pull request merged**
