### PR TITLE
OCM-12202 | ci: enable rosa-hcp-ad for OCP E2E 4.17 stable

### PR DESCRIPTION
**Pull request by xueli181114**

### CODE REVIEW

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-stable-aws-rosa-hcp-advanced-stage-critical-f7

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-stable-aws-rosa-hcp-advanced-stage-critical-f7

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-stable-aws-rosa-hcp-advanced-stage-critical-f7

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-stable-aws-rosa-hcp-advanced-stage-critical-f7

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-stable-aws-rosa-hcp-advanced-stage-critical-f7

**Comment by xueli181114** [comment]
The failed cases are debugged [here](https://redhat-internal.slack.com/archives/CCTBZUATE/p1730689939922149).

**Comment by xueli181114** [comment]
@kuiwang02 @liangxia Can you help to review?

**Comment by kuiwang02** [comment]
it is related to regression job, and I have no comments on it.

**Pull request merged**
