### PR TITLE
Add windows 2022 test lane to common-templates

### PR DESCRIPTION
**Pull request by Barakmor1**
Currently `always_run: false` to make sure it works first

Signed-off-by: bmordeha <bmodeha@redhat.com>

### CODE REVIEW

**Comment by Barakmor1** [comment]
@ksimon1 
Can you have a look please?

**Comment by ksimon1** [comment]
it looks like there are errors in config. Can you please run make jobs?

**Comment by Barakmor1** [comment]
> it looks like there are errors in config. Can you please run make jobs?

Done.
Thanks

**Comment by ksimon1** [comment]
And can you please run `make ci-operator-config`?

**Comment by Barakmor1** [comment]
> make ci-operator-config

Yes Done :)

**Pull request merged**
