### PR TITLE
volsync -use golang v1.22, ocp 4.16

### PR DESCRIPTION
**Pull request by tesshuflower**

### CODE REVIEW

**Review by JohnStrunk — APPROVED** [review]
/lgtm

**Comment by tesshuflower** [comment]
Sorry @JohnStrunk , I had to rebase, as after our upstream change merged, the replace image stuff for golang-1.22 was automatically removed from backube-volsync-main.yaml - do you mind reviewing again?

**Review by JohnStrunk — APPROVED** [review]
/lgtm

**Pull request merged**
