### PR TITLE
[4.9] - Add repo names to match the RHCOS repo names

### PR DESCRIPTION
**Pull request by ravanelli**
- We are changing the repo names in order to improve our internal redhat-coreos repo, to use a single branch for the RHCOS versions. We need to add the names to macth our repos names now.

Signed-off-by: Renata Ravanelli <rravanel@redhat.com>

### CODE REVIEW

**Comment by joepvd** [comment]
Similar to https://github.com/openshift/release/pull/34545, hence
/lgtm

**Comment by travier** [comment]
Was worried about the name change but https://github.com/openshift/release/pull/34545#issuecomment-1341322958 seems to clear it up.
/lgtm

**Pull request merged**
