### PR TITLE
propagate ACM 2.10 images

### PR DESCRIPTION
**Pull request by vboulos**
Propagate the ACM 2.10 QE images into Prow

### CODE REVIEW

**Comment by vboulos** [comment]
pj-rehearse pull-ci-stolostron-acmqe-grc-test-release-2.10-images

**Comment by vboulos** [comment]
/pj-rehearse pull-ci-stolostron-application-ui-test-release-2.10-images

**Comment by vboulos** [comment]
/pj-rehearse pull-ci-stolostron-observability_core_automation-release-2.10-images

**Comment by vboulos** [comment]
/pj-rehearse pull-ci-stolostron-acmqe-grc-test-release-2.10-images

**Review by gurnben — APPROVED** [review]
/lgtm
/approve

**Review by dfrazzette — APPROVED** [review]
@amp-rh - Can you approve this PR for merge?

**Review by amp-rh — APPROVED** [review]

**Comment by vboulos** [comment]
lgtm

**Pull request merged**
