### PR TITLE
MULTIARCH-4769 Day 0 multiarch compute arm x86

### PR DESCRIPTION
**Pull request by tvardema**
The multiarch team is working on an installer PR to enable day-0 multiarch compute deployments. This PR enables this on AWS.

### CODE REVIEW

**Comment by r4f4** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-aws-ovn-heterogeneous
Expected to fail until https://github.com/openshift/installer/pull/8698 merges. Failing is a good sign in this PR.

**Comment by r4f4** [comment]
> Expected to fail until https://github.com/openshift/installer/pull/8698 merges. Failing is a good sign in this PR.

Failed as expected:
```
level=error msg=failed to fetch Master Machines: failed to load asset "Install Config": failed to create install config: invalid "install-config.yaml" file: compute[0].architecture: Invalid value: "amd64": heteregeneous multi-arch is not supported; compute pool architecture must match control plane
Create manifests exit code: 3
```
The [install-config.yaml](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/54129/rehearse-54129-pull-ci-openshift-installer-master-e2e-aws-ovn-heterogeneous/1810714011927318528/artifacts/e2e-aws-ovn-heterogeneous/ipi-install-install/artifacts/install-config.yaml) has the right instance types and arches for each node type.

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-aws-ovn-heterogeneous periodic-ci-openshift-release-master-nightly-4.16-e2e-aws-ovn-fips pull-ci-openshift-cluster-config-operator-release-4.14-e2e-aws-ovn pull-ci-openshift-cluster-kube-descheduler-operator-release-4.17-e2e-aws-operator

**Review by r4f4 — COMMENTED** [review]
/lgtm

**Comment by r4f4** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-e2e-aws-ovn-arm64

**Pull request merged**
