### PR TITLE
disable vSphere UPI zonal installs in 4.12

### PR DESCRIPTION
**Pull request by rvanderp3**
UPI zonal installs are broken and not supported in 4.12.  There is a change required in the installer image that requires a backport to work with 4.12.  Thus, we'll disable this periodic.

### CODE REVIEW

**Comment by rvanderp3** [comment]
cc: @jcpowermac

**Review by bradmwilliams — APPROVED** [review]

**Comment by rvanderp3** [comment]
> /assign @stbenjam

Hi @stbenjam would you mind taking a look at this one when you get a chance?

**Pull request merged**
