### PR TITLE
trim approvers list for openshift/enhancements repo

### PR DESCRIPTION
**Pull request by dhellmann**

### CODE REVIEW

**Comment by russellb** [comment]
@dhellmann in conflict now

**Comment by dhellmann** [comment]
Hmm, now the file says not to edit it because it's generated. Let's see what the validation jobs have to say about the change.

**Comment by russellb** [comment]
> Hmm, now the file says not to edit it because it's generated. Let's see what the validation jobs have to say about the change.

that does sound familiar ... i think i remember running a tool in the past to generate some of the setup in this repo, and that included auto copying the OWNERS files

**Comment by hongkailiu** [comment]
If the `OWNERS` file is changed at upstream repo, it will be synced here, unless you want to disable the sync.
If you do not disable the sync and change the file here anyway, it will be changed back by our job.
https://github.com/openshift/release/blob/05571376c9fad4a1e16b7bf962c90023345cb474/ci-operator/jobs/infra-periodics.yaml#L497

**Comment by dhellmann** [comment]
@hongkailiu aha, thank you for explaining how that works!

@russellb @wking I don't feel particularly strongly about making this list short. I'm going to leave well-enough alone and close this PR. If you disagree, let me know and I'll reopen it and disable syncing.

**Pull request closed without merging**
