### PR TITLE
opendatahub-io/caikit-nlp: add build definition

### PR DESCRIPTION
**Pull request by dtrifiro**
add build definition for Dockerfile in `opendatahub/caikit-nlp`

### CODE REVIEW

**Comment by dtrifiro** [comment]
@Xaenalt can you take a look to see if this makes sense?

**Comment by Xaenalt** [comment]
Yeah, looks good to me
/ok-to-test
/pj-rehearse

**Comment by dtrifiro** [comment]
Yeah well, we also need to sync opendatahub/caikit-nlp to upstream, since the dockerfile is still missing

**Comment by dtrifiro** [comment]
/pj-rehearse pull-ci-opendatahub-io-caikit-nlp-release-pr-image-mirror

**Comment by dtrifiro** [comment]
/pj-rehearse pull-ci-opendatahub-io-caikit-nlp-release-pr-image-mirror
/pj-rehearse pull-ci-opendatahub-io-caikit-nlp-main-pr-image-mirror
/pj-rehearse pull-ci-opendatahub-io-caikit-nlp-release-images
/pj-rehearse pull-ci-opendatahub-io-caikit-nlp-main-images

**Pull request merged**
