### PR TITLE
ensure velero-plugin-for-legacy-aws is multiarch

### PR DESCRIPTION
**Pull request by weshayutin**
we only have amd64 built atm

### CODE REVIEW

**Review by sseago — APPROVED** [review]

**Review by kaovilai — APPROVED** [review]
/lgtm
/pj-rehearse ack

**Comment by kaovilai** [comment]
might require rebase

**Comment by kaovilai** [comment]
to fix error

**Comment by kaovilai** [comment]
```
ERROR: Run the following command to re-format the Prow jobs:
ERROR: $ make jobs
```

**Review by kaovilai — APPROVED** [review]
/lgtm

**Comment by weshayutin** [comment]
@kaovilai ++

**Pull request merged**
