### PR TITLE
Use ENABLE_WEBHOOKS ARG in Dockerfile

### PR DESCRIPTION
**Pull request by bshephar**
In an effort to reduce the computational load of our operators. We are disabling webhooks in the service operators by default. However, they are still required in CI for Kuttl tests to succeed. This change leverages the ENABLE_WEBHOOKS ARG added to the Dockerfile. For an example of this Dockerfile change, reference the heat-operator: https://github.com/openstack-k8s-operators/heat-operator/pull/466/files

Jira: https://issues.redhat.com/browse/OSPRH-11199

### CODE REVIEW

**Comment by bshephar** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-heat-operator-main-heat-operator-build-deploy-kuttl

**Comment by bshephar** [comment]
This should ideally pass without any of the changes to the Dockerfiles at this stage. Let's wait for the rehearse of the job to make sure we're not breaking anything here. Then we can re-check the Heat Operator PR to make sure it works are designed with the Dockerfile changes.

**Comment by bshephar** [comment]
Rehearse results show that this change doesn't break existing jobs.

**Comment by lewisdenny** [comment]
/lgtm

```
+ oc patch bc/heat-operator-bundle --type=json '-p=[{"op": "add", "path": "/spec/strategy/dockerStrategy/env", "value": [{"name": "ENABLE_WEBHOOKS", "value": "true"}]}]'
buildconfig.build.openshift.io/heat-operator-bundle patched

build.build.openshift.io/heat-operator-bundle-1 started

STEP 1/17: FROM scratch
STEP 2/17: ENV "ENABLE_WEBHOOKS"="true"
```

**Review by lewisdenny — APPROVED** [review]
/approve

**Pull request merged**
