### PR TITLE
Bug 1909849: fix broken aws-fips upgrade 4.4 periodic

### PR DESCRIPTION
**Pull request by sallyom**
I believe this fixes the issue with perma-failing [e2e-aws-fips-upgrade periodic](https://testgrid.k8s.io/redhat-openshift-ocp-release-4.4-informing#release-openshift-origin-installer-e2e-aws-upgrade-fips-4.4)

Or, I will remove this job if it's no longer required.

### CODE REVIEW

**Comment by petr-muller** [comment]
@sallyom can you rebase this please? Unfortunately we touch these a lot recently so we get conflicts...

**Comment by petr-muller** [comment]
Took a shot at it in https://github.com/openshift/release/pull/16443 to also move the matching 4.3 job

**Comment by sallyom** [comment]
https://github.com/openshift/release/pull/16443 fixes the fips-4.3 & 4.4 upgrade tests, closing this, thank you @petr-muller !

**Pull request closed without merging**
