### PR TITLE
infra-operator: Enable kuttl job

### PR DESCRIPTION
**Pull request by kajinamit**
so that we can replace build deploy job by it.

### CODE REVIEW

**Comment by kajinamit** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-infra-operator-main-infra-operator-build-deploy-kuttl pull-ci-openstack-k8s-operators-infra-operator-main-functional pull-ci-openstack-k8s-operators-infra-operator-main-images pull-ci-openstack-k8s-operators-infra-operator-main-infra-operator-build-deploy pull-ci-openstack-k8s-operators-infra-operator-main-precommit-check

**Comment by kajinamit** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-infra-operator-main-infra-operator-build-deploy-kuttl pull-ci-openstack-k8s-operators-infra-operator-main-functional pull-ci-openstack-k8s-operators-infra-operator-main-images pull-ci-openstack-k8s-operators-infra-operator-main-infra-operator-build-deploy pull-ci-openstack-k8s-operators-infra-operator-main-precommit-check

**Comment by kajinamit** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-infra-operator-main-infra-operator-build-deploy-kuttl

**Comment by kajinamit** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-infra-operator-main-infra-operator-build-deploy-kuttl pull-ci-openstack-k8s-operators-infra-operator-main-functional pull-ci-openstack-k8s-operators-infra-operator-main-images pull-ci-openstack-k8s-operators-infra-operator-main-infra-operator-build-deploy pull-ci-openstack-k8s-operators-infra-operator-main-precommit-check

**Comment by kajinamit** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-infra-operator-main-infra-operator-build-deploy-kuttl

**Comment by viroel** [comment]
/lgtm too
thanks @kajinamit

**Pull request merged**
