### PR TITLE
ci-operator: Introduce a dedicated prowjob for running OLM's psm unit tests

### PR DESCRIPTION
**Pull request by timflannagan**
The PSM is a sub-component of OLM that was introduced in 4.9. These unit tests are currently run by through the unit/olm prowjob as an original hack to get CI coverage without having to introduce a new prowjob, but we never fixed that hack after the PSM work was merged.

Signed-off-by: timflannagan <timflannagan@gmail.com>

### CODE REVIEW

**Comment by timflannagan** [comment]
Looks like the rehearsals worked:

```
go test /go/src/github.com/openshift/operator-framework-olm/pkg/package-server-manager/...
ok github.com/openshift/operator-framework-olm/pkg/package-server-manager 0.050s
```

**Review by exdx — COMMENTED** [review]
Do these changes also incorporate changes to OLM to not run the PSM unit tests as part of it's own unit suite run? Just making sure we aren't duplicating running the same tests twice in CI

**Comment by timflannagan** [comment]
@exdx Nope - that's needs to be done as a follow-up (I'm tracking this locally) once the upstream sync lands and CI is a bit more stable.

**Comment by exdx** [comment]
Ok cool -- let's do it as a followup
/lgtm

**Pull request merged**
