### PR TITLE
ci-operator: create an image from the latest running VM instance

### PR DESCRIPTION
**Pull request by sohankunkerkar**

### CODE REVIEW

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-cri-o-cri-o-main-periodics-setup-fedora-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-cri-o-cri-o-main-periodics-setup-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-cri-o-cri-o-main-periodics-setup-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-cri-o-cri-o-main-periodics-setup-fedora-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-cri-o-cri-o-main-periodics-setup-fedora-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-cri-o-cri-o-main-periodics-setup-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-cri-o-cri-o-main-periodics-setup-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-cri-o-cri-o-main-periodics-setup-fedora-periodic

**Comment by haircommander** [comment]
/lgtm
/approve
/hold

Lift hold when it's ready

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-cri-o-cri-o-main-periodics-setup-fedora-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-cri-o-cri-o-main-periodics-setup-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-cri-o-cri-o-main-periodics-setup-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-cri-o-cri-o-main-periodics-setup-fedora-periodic

**Comment by sohankunkerkar** [comment]
I wonder why GCP doesn't allow access to the disk of an instance that we stopped in the previous step. I haven't changed the project ID at all; I'm still in the same project namespace.

**Comment by bear-redhat** [comment]
/pj-rehearse periodic-ci-cri-o-cri-o-main-periodics-setup-fedora-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-cri-o-cri-o-main-periodics-setup-fedora-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-cri-o-cri-o-main-periodics-setup-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-cri-o-cri-o-main-periodics-setup-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-cri-o-cri-o-main-periodics-setup-fedora-periodic

**Review by mrunalp — APPROVED** [review]
/lgtm

**Pull request merged**
