### PR TITLE
Aro node

### PR DESCRIPTION
**Pull request by paigerube14**
Seeing if node scenarios are possible for aro

### CODE REVIEW

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-tests-aro-node

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-tests-aro-node

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-tests-aro-node

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-tests-aro-node

**Review by shahsahil264 — APPROVED** [review]
LGTM

**Pull request merged**
