### PR TITLE
Servicemesh zstream expansion

### PR DESCRIPTION
**Pull request by smpsgill**

### CODE REVIEW

**Comment by Simranpal** [comment]
Quarkus QE TS: Config

**Comment by mkralik3** [comment]
/pj-rehearse periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.16-lp-interop-servicemesh-interop-ibmcloud

**Comment by Simranpal** [comment]
/pj-rehearse periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.16-lp-interop-servicemesh-interop-ibmcloud

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request closed without merging**
