### PR TITLE
MSI - Add ACM Observability scneario

### PR DESCRIPTION
**Pull request by rnetser**

### CODE REVIEW

**Comment by rnetser** [comment]
@myakove

**Review by myakove — APPROVED** [review]

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4.13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4.13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4-13-stage-multi-cluster-observability-4.13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-acm-observability-v4.13-stage-multi-cluster-observability-4-13-rosa-acm-gcp-mngd-rosa-mngd

**Review by myakove — APPROVED** [review]

**Pull request merged**
