### PR TITLE
Add kdump gather step in powervs workflows

### PR DESCRIPTION
**Pull request by Shilpa-Gokul**

### CODE REVIEW

**Comment by Shilpa-Gokul** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-ovn-ppc64le-powervs

**Comment by Shilpa-Gokul** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-ovn-ppc64le-powervs

**Comment by jaypoulz** [comment]
Before we ack this rehearsal, we should verify that we successfully get a log if we intentionally crash a node.
Here is how I accomplished this:
1. Kick off the rehearsal job
2. Login to https://console.build01.ci.openshift.org/ (I believe this is where that rehearsal job is scheduled. If it's scheduled to a different build cluster, we can find the link in openshift/release -> clusters
3. There should be rehearsal project created called ci-op-{hash} or something like that
4. Switch the ci-op-{hash} project and list out the pods
5. wait for the job pods to create the "test" step pod. This pod will have oc configured and will be running the tests.
6. switch to the terminal tab of that pod and run $ oc get  nodes
7. Now run $ oc debug node/{name-of-one-of-the-compute-nodes} --to-namespace=default
8. Once it get's you into that node, run $ chroot /host
9. Now check that dump is running with  $ service kdump status
10. Now we crash the node with $ echo c > /proc/sysrq-trigger
11. Wait for a little bit for the terminal to end that debug process and kick you back to the test pod. From here, you can ensure that the node captured the log by rerunning step 7 and then $ ls /host/var/crash
12. Once your satisfied that kdump worked, exit back to the test pod. From here I like to short-circuit the test run by killing the test process. List out the active processes with $ ps -aux
13. Look for the process that is running openshift-tests with the test file. It's usually in the 150s to 160s
14. $ kill {pid-of-test-process}
15. Now just wait. A new pod will be created for the gather step, so you can watch the logs there if you're impatient and don't want to wait for them to show up in the rehearsal job output in prow.

**Comment by jaypoulz** [comment]
Actually, I think you may have missed something. You'll need to look at the default values set for kdump in the libvirt code to ensure it runs properly.
https://github.com/openshift/release/blob/master/ci-operator/step-registry/ipi/libvirt/pre/ipi-libvirt-pre-chain.yaml#L10-L21

**Comment by Shilpa-Gokul** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-ovn-ppc64le-powervs

**Comment by Shilpa-Gokul** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-ovn-ppc64le-powervs

**Comment by Shilpa-Gokul** [comment]
@jaypoulz Have added the default values for kdump and also tested as you mentioned. The crash is collected properly- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/43047/rehearse-43047-periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-ovn-ppc64le-powervs/1704366443014918144

**Comment by droslean** [comment]
/hold

Temporary holding to unblock the queue

**Pull request merged**
