### PR TITLE
[FUSEQE-19330] - Fix permissions on nginx server and update CSB examples

### PR DESCRIPTION
**Pull request by smongiar**

### CODE REVIEW

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.18-lp-interop-csb-interop-aws-latest-fips

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.17-lp-interop-jboss-fuse-interop-aws

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.17-lp-interop-csb-interop-aws-latest

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.18-lp-interop-csb-interop-aws-latest-fips

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.17-lp-interop-jboss-fuse-interop-aws

**Review by mcarlett — APPROVED** [review]

**Review by Croway — APPROVED** [review]

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.18-lp-interop-csb-interop-aws-latest-fips

**Pull request merged**
