### PR TITLE
stackrox: another way to run nightly tests

### PR DESCRIPTION
**Pull request by gavin-stackrox**
In this way, the nightly tests are a simple copy-n-paste of the master merge tests.

Nightly CI will exec: https://github.com/stackrox/stackrox/blob/nightlies/.openshift-ci/nightlies.sh which will kick off all the `postsubmit: true` CI.

Testing: Tags properly on rehearse.

/hold
/uncc

### CODE REVIEW

**Review by sbostick — APPROVED** [review]
LGTM

**Review by sbostick — APPROVED** [review]
LGTM

**Review by jmguzik — APPROVED** [review]

**Comment by jmguzik** [comment]
@gavin-stackrox I have failed to notice this before approving which is my mistake, but I would like to ask you in the future to either squash commits next time or use the command: `/label tide/merge-method-squash`
That works nicely, especially if you have multiple comments with non-descriptive names. Thanks!

**Pull request merged**
