### PR TITLE
Move barbican and designate prow jobs over from 4.14 to 4.15 Hive cluster

### PR DESCRIPTION
**Pull request by bshewale**

### CODE REVIEW

**Comment by lewisdenny** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-barbican-operator-main-barbican-operator-build-deploy-kuttl pull-ci-openstack-k8s-operators-barbican-operator-main-functional pull-ci-openstack-k8s-operators-barbican-operator-main-precommit-check

**Comment by lewisdenny** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-designate-operator-main-designate-operator-build-deploy-kuttl

**Comment by viroel** [comment]
/approve

This one looks good. we can remove the hold when needed.

**Review by lewisdenny — APPROVED** [review]
/unhold

**Pull request merged**
