### PR TITLE
add periodic-ci-insights-qe-iqe-cost-management-plugin-master-ocp4.17-lp-interop-cost-management-interop-aws

### PR DESCRIPTION
**Pull request by amp-rh**
[INTEROP-7438](https://issues.redhat.com/browse/INTEROP-7438)

### CODE REVIEW

**Comment by amp-rh** [comment]
/pj-rehearse periodic-ci-insights-qe-iqe-cost-management-plugin-master-ocp4.17-lp-interop-cost-management-interop-aws

**Review by madunn — APPROVED** [review]

**Pull request merged**
