### PR TITLE
Re-enable passing tests for 4.5 s390x

### PR DESCRIPTION
**Pull request by r4f4**
Image streams and some other fixes are now in place, so we can re-enable
some of the tests.

Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>

### CODE REVIEW

**Comment by bparees** [comment]
/approve

let's see the rehearsal pass before this merges though

**Comment by r4f4** [comment]
I see we are missing an override path `gcr.io/k8s-staging-csi/*` and there are some network issues I didn't see when I ran theses tests:
```
Get https://github.com/sclorg/nodejs-ex: dial tcp: i/o timeout
    error: git ls-remote failed with: fatal: unable to access 'https://github.com/sclorg/nodejs-ex/': Could not resolve host: github.com; Unknown error;  local file access failed with: stat https://github.com/sclorg/nodejs-ex: no such file or directory
```

**Comment by r4f4** [comment]
The override issue depends on https://github.com/openshift/release/pull/10229 being merged

**Comment by r4f4** [comment]
pinging @petr-muller for review

**Comment by bparees** [comment]
passed rehearsal
/lgtm

**Pull request merged**
