### PR TITLE
Fix SSO not displayed on HyperShift Test Grid

### PR DESCRIPTION
**Pull request by liswang89**

### CODE REVIEW

**Comment by liswang89** [comment]
/pj-rehease periodic-ci-rhbk-sso-test-main-rhsso-product-ocp4.15-lp-rosa-hypershift-rhsso-interop-aws

**Comment by liswang89** [comment]
/pj-rehease periodic-ci-rhbk-sso-test-main-rhsso-product-ocp4.15-lp-rosa-hypershift-rhsso-interop-aws

**Comment by liswang89** [comment]
/pj-rehease periodic-ci-rhbk-sso-test-main-rhsso-product-ocp4.14-lp-rosa-hypershift-rhsso-interop-aws

**Comment by liswang89** [comment]
/pj-rehearse periodic-ci-rhbk-sso-test-main-rhsso-product-ocp4.15-lp-rosa-hypershift-rhsso-interop-aws

**Review by Simranpal — APPROVED** [review]
/lgtm

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
