### PR TITLE
OCPQE-20784: Upgrade implementation Compact Hosted Control Plane

### PR DESCRIPTION
**Pull request by LiangquanLi930**

### CODE REVIEW

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-4.15-upgrade-from-stable-4.14-baremetalds-agent-hypershift-mce-compact-full-inplace-f7

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-4.15-upgrade-from-stable-4.14-baremetalds-agent-hypershift-mce-compact-full-inplace-f7

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-4.15-upgrade-from-stable-4.14-baremetalds-agent-hypershift-mce-compact-full-inplace-f7

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-4.15-upgrade-from-stable-4.14-baremetalds-agent-hypershift-mce-compact-full-inplace-f7

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-4.15-upgrade-from-stable-4.14-baremetalds-agent-hypershift-mce-compact-full-inplace-f7

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-4.15-upgrade-from-stable-4.14-baremetalds-agent-hypershift-mce-compact-full-inplace-f7

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-4.15-upgrade-from-stable-4.14-baremetalds-agent-hypershift-mce-compact-full-inplace-f7

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-4.15-upgrade-from-stable-4.14-baremetalds-agent-hypershift-mce-compact-full-inplace-f7

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-4.15-upgrade-from-stable-4.14-baremetalds-agent-hypershift-mce-compact-full-inplace-f7

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-4.15-upgrade-from-stable-4.14-baremetalds-agent-hypershift-mce-compact-full-inplace-f7

**Comment by LiangquanLi930** [comment]
@jianlinliu @shellyyang1989 Could you help review this PR? Thanks

**Comment by shellyyang1989** [comment]
The to-image step change looks good to me

/lgtm

**Comment by LiangquanLi930** [comment]
@liangxia Could you help to review this PR? Thanks

**Comment by liangxia** [comment]
Issues with concerns,

1. Step baremetalds-agent-hypershift-mce-compact-full-inplace-f7-destroy failed
2. Most of the upgrade prepare/check failed

**Comment by LiangquanLi930** [comment]
> Issues with concern,

> Step baremetalds-agent-hypershift-mce-compact-full-inplace-f7-destroy failed
Most of the upgrade prepare/check failed
@liangxia Thanks
For the first one, this is a known issue related to the BM installed with the dev-script, but it doesn't cause any resource leaks.

For the second one, as the Hypershift team, our main concern is whether the upgrade is successful. In the case of failure, I'll coordinate with various teams for debugging.

**Comment by liangxia** [comment]
> > Issues with concern,
> 
> > Step baremetalds-agent-hypershift-mce-compact-full-inplace-f7-destroy failed
> > Most of the upgrade prepare/check failed
> 
> @liangxia Thanks For the first one, this is a known issue related to the BM installed with the dev-script, but it doesn't cause any resource leaks.
> 
> For the second one, as the Hypershift team, our main concern is whether the upgrade is successful. In the case of failure, I'll coordinate with various teams for debugging.

```
cucushift:
  type: cucushift-upgrade-prepare
  total: 12
  failures: 11
  errors: 0
  skipped: 0
...
cucushift:
  type: cucushift-upgrade-check
  total: 12
  failures: 11
  errors: 0
  skipped: 1
```
Actually, all the upgrade prepare/check are failed.  I think the profile owner should responsible for this.

**Comment by YuLi517** [comment]
@liangxia Fully understand your concern here, we also want to debug and find the root cause of these failures. But based on cucushift report [log](https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/51015/rehearse-51015-periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-4.15-upgrade-from-stable-4.14-baremetalds-agent-hypershift-mce-compact-full-inplace-f7/1782192181109329920/artifacts/baremetalds-agent-hypershift-mce-compact-full-inplace-f7/openshift-upgrade-qe-test-report/build-log.txt). It's hard for us to find related team to handle debugging. I need report portal help to filter it and I will send the summary to whole team to debug. Could you help to let it merged? We will trigger it once and let it go inside report portal?

**Comment by liangxia** [comment]
> @liangxia Fully understand your concern here, we also want to debug and find the root cause of these failures. But based on cucushift report [log](https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/51015/rehearse-51015-periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-4.15-upgrade-from-stable-4.14-baremetalds-agent-hypershift-mce-compact-full-inplace-f7/1782192181109329920/artifacts/baremetalds-agent-hypershift-mce-compact-full-inplace-f7/openshift-upgrade-qe-test-report/build-log.txt). It's hard for us to find related team to handle debugging. I need report portal help to filter it and I will send the summary to whole team to debug. Could you help to let it merged? We will trigger it once and let it go inside report portal?

The log indicates, either we are passing wrong kubeconfig, or wrong API for the upgrade prepare/check. I don't think that's something related to features that need each sub-team to dig into.

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-4.15-upgrade-from-stable-4.15-baremetalds-agent-hypershift-mce-inplace-f7

**Pull request merged**
