### PR TITLE
[WINC-963]: Add CI jobs for community 4.12

### PR DESCRIPTION
**Pull request by alinaryan**
wmco: Add configs and conditionally skip CI jobs for community-4.12
core-services: onboard community-4.12 branch

### CODE REVIEW

**Review by saifshaikh48 — COMMENTED** [review]
/lgtm

**Comment by alinaryan** [comment]
Error with cluster install. 
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/35427/rehearse-35427-pull-ci-openshift-windows-machine-config-operator-community-4.12-okd-aws-e2e-operator/1615110546330226688
Multiple tests failed but 
`{ openshift cluster install failed overall}`

Possibly a quota policy issue again? 

/pj-rehearse pull-ci-openshift-windows-machine-config-operator-community-4.12-okd-aws-e2e-operator

**Review by aravindhp — APPROVED** [review]

**Pull request merged**
