### PR TITLE
Use app.ci as registry cluster in dptp-cm

### PR DESCRIPTION
**Pull request by hongkailiu**
/hold

will merge together with https://github.com/openshift/ci-tools/pull/1503

https://issues.redhat.com/browse/DPTP-1658

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@hongkailiu why does this need to get merged together with https://github.com/openshift/ci-tools/pull/1503/files? I would expect merging this to just work, promoting directly to the right cluster is an orthogonal change

**Comment by hongkailiu** [comment]
> @hongkailiu why does this need to get merged together with https://github.com/openshift/ci-tools/pull/1503/files? I would expect merging this to just work, promoting directly to the right cluster is an orthogonal change

I thought `test_images_distributor` and `promotionreconciler` needs the right source registry.
With `registry_syncer`, the above might be not necessary for the namespaces that are synced.
But we have not synced every namespace right?

**Comment by alvaroaleman** [comment]
> With registry_syncer, the above might be not necessary for the namespaces that are synced.
But we have not synced every namespace right?

To my understanding the whole point of the registry syncer is to not have these two changes coupled

**Comment by hongkailiu** [comment]
> To my understanding the whole point of the registry syncer is to not have these two changes coupled

True. I will handle this later.
Either add all other namespaces or start to use denial list only.

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
