### PR TITLE
Rocky is now supported in dev-scripts

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Comment by elfosardo** [comment]
ok, we need https://github.com/openshift-metal3/dev-scripts/pull/1441 first to fix the missing distros

**Comment by cybertron** [comment]
/lgtm
once ci is passing.

**Comment by cybertron** [comment]
/hold

I just realized that the rehearse jobs are not blocking and we don't want this to go in yet.

**Comment by elfosardo** [comment]
mmm looks like it does not get the latest dev-scripts changes

**Comment by cybertron** [comment]
Could also be https://github.com/openshift-metal3/dev-scripts/pull/1443 . That's making my local runs fail.

**Comment by derekhiggins** [comment]
Note: in CI we currently have both Rocky and Centos stream nodes, this PR has some passing tests on each type

@cybertron want to remove your /hold? looks like this should be ok now.

**Comment by cybertron** [comment]
/hold cancel

FWIW, I'm always okay with someone else removing my hold if the reason it was added has been resolved.

**Pull request merged**
