### PR TITLE
Require leases for scaleup tests

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @wking

### CODE REVIEW

**Comment by wking** [comment]
Don't you need to [add `lease` to `container-sub-tests`][1] too?

[1]: https://github.com/openshift/release/commit/aab6463a166e255b8adacd95974f58acd7e3b865#diff-1dbbb3c9b7788155db302b2a277ab26aR64

**Comment by wking** [comment]
CC @vrutkovs, so you know we're touching your template ;).  This PR is bringing over the same changes that #4649 brought to the other templates.

**Comment by stevekuznetsov** [comment]
@wking good call -- done

**Pull request merged**
