### PR TITLE
Test adjusting the limit

### PR DESCRIPTION
**Pull request by asood-rh**

### CODE REVIEW

**Comment by asood-rh** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-e2e-aws

**Comment by asood-rh** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-e2e-aws

**Comment by kuiwang02** [comment]
currently aws installation profile has problem, so you will meet aws installation fails.
so, we do not need to wait here, and then

/lgtm

**Comment by kuiwang02** [comment]
as you see, the aws installation fails at https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/55791/rehearse-55791-pull-ci-openshift-openshift-tests-private-master-e2e-aws/1826057229581684736#1:build-log.txt%3A60.
you could wait for time to see if it is fixed. and after that, could raise ticket in slack if it is still failing here.

but, for this PR, I suggest to merge it because 8Gi is ok for memory requested.

how about it?

**Comment by asood-rh** [comment]
> as you see, the aws installation fails at https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/55791/rehearse-55791-pull-ci-openshift-openshift-tests-private-master-e2e-aws/1826057229581684736#1:build-log.txt%3A60. you could wait for time to see if it is fixed. and after that, could raise ticket in slack if it is still failing here.
> 
> but, for this PR, I suggest to merge it because 8Gi is ok for memory requested.
> 
> how about it?

Sure, it makes sense. The PR merge may continue to be blocked if the aws cluster install fails.

**Comment by asood-rh** [comment]
> > as you see, the aws installation fails at https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/55791/rehearse-55791-pull-ci-openshift-openshift-tests-private-master-e2e-aws/1826057229581684736#1:build-log.txt%3A60. you could wait for time to see if it is fixed. and after that, could raise ticket in slack if it is still failing here.
> > but, for this PR, I suggest to merge it because 8Gi is ok for memory requested.
> > how about it?
> 
> Sure, it makes sense. The PR merge may continue to be blocked if the aws cluster install fails.

Removed WIP from title, merge should happen.

**Pull request merged**
