### PR TITLE
Fix issue DPTP-3961 Wait for OLM

### PR DESCRIPTION
**Pull request by bear-redhat**

### CODE REVIEW

**Comment by bear-redhat** [comment]
/pj-rehearse pull-ci-opendatahub-io-ai-edge-main-test-ai-edge

**Comment by bear-redhat** [comment]
/pj-rehearse pull-ci-opendatahub-io-ai-edge-main-test-ai-edge

**Comment by bear-redhat** [comment]
/pj-rehearse pull-ci-opendatahub-io-ai-edge-main-test-ai-edge

**Comment by rkubis** [comment]
/pj-rehearse pull-ci-opendatahub-io-ai-edge-main-test-ai-edge

**Comment by rkubis** [comment]
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-e2e-odh-cfo

**Pull request merged**
