### PR TITLE
add E2E test to openshift/lightspeed-operator

### PR DESCRIPTION
**Pull request by raptorsun**
do not merge. testing...

### CODE REVIEW

**Comment by raptorsun** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-operator-main-bundle-e2e

**Comment by raptorsun** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-operator-main-bundle-e2e

**Comment by raptorsun** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-operator-main-bundle-e2ea

**Comment by raptorsun** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-operator-main-bundle-e2e

**Comment by raptorsun** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-operator-main-bundle-e2e

**Comment by xrajesh** [comment]
/lgtm
@raptorsun We are ready to merge this. I can remove WIP ?

**Comment by raptorsun** [comment]
> /lgtm @raptorsun We are ready to merge this. I can remove WIP ?

I removed the WIP in title.
Has the rehearsal passed? =)

**Comment by raptorsun** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-operator-main-bundle-e2e

**Comment by xrajesh** [comment]
@raptorsun once the test passes one of us can add rehearsals-ack  .

**Comment by raptorsun** [comment]
@xrajesh all tests and the rehearsal passed, let's merge. 😁

**Pull request merged**
