### PR TITLE
Multi-arch disconnected on Azure QE testconfigs

### PR DESCRIPTION
**Pull request by lwan-wanglin**
refer https://issues.redhat.com/browse/MIXEDARCH-261

### CODE REVIEW

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-azure-ipi-disconnected-fullyprivate-p3-f28-destructive

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-azure-ipi-disconnected-fullyprivate-tp-p3-f28

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-azure-ipi-ingress-custom-ingresscontroller-p3-f28

**Comment by lwan-wanglin** [comment]
@aleskandro could you help to review the PR? thanks!

**Comment by aleskandro** [comment]
HI @lwan-wanglin it looks good to me, also, cc @MayXuQQ to review relative to the azure test matrix.

My opinion in this effort is to trigger just a few profiles for now and prioritize the ones that could take some branches involving specific binaries and images that we might miss as multi-arch artifacts. Therefore, the higher the coverage increase of multi-arch images/binaries execution for a given profile, the better. At the same time, avoid super-redundancy with others, frequently tested, profiles, so that (1) watchers can hold the workload and (2) costs increase are minimized.

**Review by aleskandro — APPROVED** [review]

**Comment by MayXuQQ** [comment]
How about azure-ipi-disconnected-fullyprivate-p2-f14
changed to p3-f28

**Review by MayXuQQ — APPROVED** [review]

**Review by MayXuQQ — APPROVED** [review]

**Comment by lwan-wanglin** [comment]
@MayXuQQ PTAL! thanks
cc @liangxia to review and merge, thanks

the installation jobs:
https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/39981/rehearse-39981-periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-azure-ipi-disconnected-fullyprivate-p3-f28-destructive/1665566699891462144
https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/39981/rehearse-39981-periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-azure-ipi-disconnected-fullyprivate-tp-p3-f28/1665566923015852032
https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/39981/rehearse-39981-periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-azure-ipi-ingress-custom-ingresscontroller-p3-f28/1665566969727815680

**Review by liangxia — APPROVED** [review]

**Pull request merged**
