### PR TITLE
Change Azure COMPUTE_NODE_TYPE for CNV e2e tests

### PR DESCRIPTION
**Pull request by rabin-io**
Better spec, same price

https://azureprice.net/compare?vms=Standard_D4s_v3,Standard_D4s_v5

Also, worth checking other regions then `centralus`, like India, which can be 50% cheaper 

https://azureprice.net/?region=centralus&_numberOfCores_min=4&_numberOfCores_max=4&_memoryInMB_min=16&tier=spot&_memoryInMB_max=16&sortField=bestPriceRegion&sortOrder=true

### CODE REVIEW

**Review by orenc1 — APPROVED** [review]
/approve

**Comment by rabin-io** [comment]
/pj-rehearse pull-ci-openshift-cnv-cnv-ci-release-4.12-e2e-deploy
/pj-rehearse pull-ci-openshift-cnv-cnv-ci-release-4.14-e2e-deploy

**Comment by rabin-io** [comment]
/pj-rehearse pull-ci-openshift-cnv-cnv-ci-master-4.12-e2e-deploy

**Comment by rabin-io** [comment]
/pj-rehearse pull-ci-openshift-cnv-cnv-ci-release-4.15-e2e-deploy

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-cnv-cnv-ci-master-4.13-e2e-deploy

**Pull request merged**
