### PR TITLE
stolostron: add publish hypershift-addon-operator canary test

### PR DESCRIPTION
**Pull request by mikeshng**
Signed-off-by: Mike Ng <ming@redhat.com>

### CODE REVIEW

**Comment by mikeshng** [comment]
I will unhold when the quay repo is created.

**Comment by mikeshng** [comment]
/unhold

quay repo is now created.

**Comment by mikeshng** [comment]
Thanks for the review.

/unhold

**Comment by rokej** [comment]
@mikeshng Are you planning to enable this for MCE 2.2 as well?

**Comment by mikeshng** [comment]
> @mikeshng Are you planning to enable this for MCE 2.2 as well?

@rokej created a new PR for 2.2 https://github.com/openshift/release/pull/35882

**Pull request merged**
