### PR TITLE
OCPQE-18827: Optimize cucushift-e2e steps

### PR DESCRIPTION
**Pull request by liangxia**
For the same job, `periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-azure-ipi-marketplace-noplan-f28-destructive`
log without changes in this PR, https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-azure-ipi-marketplace-noplan-f28-destructive/1759013140223234048
and log with changes in this PR, https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/49233/rehearse-49233-periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-azure-ipi-marketplace-noplan-f28-destructive/1762381902548832256

### CODE REVIEW

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-multi-nightly-aws-ipi-usertags-custom-sg-fips-amd-f28-destructive periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-azure-ipi-marketplace-noplan-f28-destructive  periodic-ci-openshift-openshift-tests-private-release-4.15-multi-nightly-gcp-ipi-compact-filestore-csi-amd-f28-destructive

**Comment by LiangquanLi930** [comment]
Thanks

**Pull request merged**
