### PR TITLE
Live migration: remove requirement for feature gate for 4.15

### PR DESCRIPTION
**Pull request by martinkennelly**
Live migration is GA for 4.15.
ref: openshift/api#1749

/cc @kyrtapz

### CODE REVIEW

**Comment by martinkennelly** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-release-4.15-e2e-aws-live-migration-sdn-ovn

**Comment by kyrtapz** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-release-4.15-e2e-aws-live-migration-sdn-ovn

**Comment by martinkennelly** [comment]
@trozet PTAL

**Pull request merged**
