### PR TITLE
Add 4.6 to 4.8 eus yaml file

### PR DESCRIPTION
**Pull request by kasturinarra**
Adding 4.8-upgrade-from-eus-4.6.yaml file

### CODE REVIEW

**Comment by kasturinarra** [comment]
@liangxia @wsun1 could you please help review ? thanks !!

**Comment by shellyyang1989** [comment]
The test config looks good to me. But seems like some test cases in the sanity test are not suitable to the test.

**Comment by jiajliu** [comment]
@kasturinarra We don't support paused-worker pool way for 4.6-4.8 eus upgrade.

**Comment by kasturinarra** [comment]
@wsun1 could you please help me understand if something is incorrect from my end ? thanks !!

**Comment by kasturinarra** [comment]
@jiajliu thanks, will close the PR here.

**Pull request closed without merging**
