### PR TITLE
chore(RHIDP-885): Use new AWS account to run Backstage perf&scale tests

### PR DESCRIPTION
**Pull request by jhutar**

### CODE REVIEW

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-search-catalog-scalability

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-search-catalog-scalability

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-search-catalog

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-list-catalog

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-baseline

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-baseline

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-search-catalog

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-search-catalog

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-search-catalog

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-search-catalog

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-search-catalog

**Review by pmacik — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
