### PR TITLE
NHC: Add release-0.2 branch, update main to OCP 4.11 and Go 1.18

### PR DESCRIPTION
**Pull request by slintes**

### CODE REVIEW

**Comment by slintes** [comment]
`node-healthcheck-operator/main/test` is expected to fail because of `go get` vs `go install` issue with 1.18, which is fixed in https://github.com/medik8s/node-healthcheck-operator/pull/94

**Comment by slintes** [comment]
/hold
wait for other rehearsal jobs

**Comment by beekhof** [comment]
/lgtm

why are the jobs failing though?

**Comment by slintes** [comment]
> why are the jobs failing though?

the e2e job failed because of resource issues on the node, should be temporarely only
the other is expected to fail because go get does not install binaries anymore. That is fixed in a NHC PR. We always have a hen - egg issue with such changes: do we first update NHC (test will will fail because of outdated CI), or do we update CI (will fail fail because of outdated NHC on main). I want to merge CI first and rerun CI on the NHC PR afterwards.

**Comment by slintes** [comment]
e2e is green

/hold cancel

**Pull request merged**
