### PR TITLE
Update and test upstream OTEL jobs

### PR DESCRIPTION
**Pull request by IshwarKanse**

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-upstream-ocp-4.15-amd64-aws-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-upstream-ocp-4.15-amd64-aws-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
Add fix PR for monitoring test case https://github.com/open-telemetry/opentelemetry-operator/pull/3458

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-upstream-ocp-4.15-amd64-aws-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
Fix failing tests https://github.com/openshift/distributed-tracing-qe/pull/64

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-upstream-ocp-4.15-amd64-aws-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-upstream-ocp-4.16-amd64-aws-ipi-shared-vpc-phz-sts-opentelemetry-e2e-tests pull-ci-openshift-open-telemetry-opentelemetry-operator-main-upstream-ocp-4.14-amd64-gcp-ipi-ovn-ipsec-opentelemetry-e2e-tests pull-ci-openshift-open-telemetry-opentelemetry-operator-main-upstream-upgrade-ocp-4.17-amd64-azure-opentelemetry-operator-upgrade pull-ci-openshift-open-telemetry-opentelemetry-operator-main-upstream-ocp-4.13-amd64-aws-ipi-ovn-hypershift-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-upstream-upgrade-ocp-4.17-amd64-azure-opentelemetry-operator-upgrade pull-ci-openshift-open-telemetry-opentelemetry-operator-main-upstream-ocp-4.14-amd64-gcp-ipi-ovn-ipsec-opentelemetry-e2e-tests

**Review by vprashar2929 — APPROVED** [review]
/lgtm

**Pull request merged**
