### PR TITLE
release-4.9: use 4.9 cluster instead of 4.8 -,-

### PR DESCRIPTION
**Pull request by kpouget**

### CODE REVIEW

**Comment by kpouget** [comment]
@omertuc, it you can `/lgtm` this one, would be nice :)

**Comment by omertuc** [comment]
We have [this](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/20986/rehearse-20986-periodic-ci-openshift-psap-ci-artifacts-release-4.9-gpu-operator-e2e-master/1424423353367662592) failed run before the merge, timed out waiting for the machine controller to make the GPU machine join the cluster.

But according to [this](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/20986/rehearse-20986-periodic-ci-openshift-psap-ci-artifacts-release-4.9-gpu-operator-e2e-master/1424423353367662592/artifacts/gpu-operator-e2e-master/gather-extra/artifacts/machines.json) (ctrl+f `g4dn.x`) it looks like the machine eventually did join the cluster, it probably just took it too much time.

**Comment by kpouget** [comment]
yes, that's what I notived as well, the machine remained as `Provisioned`
```
openshift-machine-api   ci-op-7k3qdh3t-f28a9-v6mxn-worker-us-east-1c--g4dn-xlarge-mwxdz   Provisioned   g4dn.xlarge   us-east-1   us-east-1c   21m
openshift-machine-api   ci-op-7k3qdh3t-f28a9-v6mxn-worker-us-east-1c-25cvx                Running       m5.xlarge     us-east-1   us-east-1c   48m
```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/20986/rehearse-20986-periodic-ci-openshift-psap-ci-artifacts-release-4.9-gpu-operator-e2e-master/1424423353367662592/artifacts/gpu-operator-e2e-master/nightly/artifacts/008__gpu-operator__must-gather/003__gpu_operator__capture_deployment_state/all_machines.list
but I can't find out anything explaining why it took longer than usual 🤷🏻 

thanks for merging it yesterday @omertuc,  the change was taken into account for the [nightly](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-psap-ci-artifacts-release-4.9-gpu-operator-e2e-master/1424505781717307392/artifacts/gpu-operator-e2e-master/nightly/artifacts/000__cluster__capture_environment/ocp.version) :)

**Pull request merged**
