### PR TITLE
Add openstack cluster type for workflows

### PR DESCRIPTION
**Pull request by pierreprinetti**
Extracting this change from #12497 and #8839 to be able to rehearse them without triggering 30+ jobs

/cc @vrutkovs @mandre

### CODE REVIEW

**Comment by vrutkovs** [comment]
Looks good, I don't think it needs to be WIP

**Comment by pierreprinetti** [comment]
@vrutkovs 
I turned it into WIP because of this: https://github.com/openshift/release/pull/11000/files#diff-65cce809dc5ddaa91711f6709acd41e5c24b735c073708e60f10aae28faf8712R25

Can it be that this is a dupe of that modification? I am not sure how they relate. Would you know perhaps?

**Comment by vrutkovs** [comment]
>Can it be that this is a dupe of that modification? I am not sure how they relate. Would you know perhaps?

These are related, but CLUSTER_TYPE support has to be added to both steps. You also would need to add `openstack-vexxhost` option here so that this type could run tests as well

**Review by mandre — COMMENTED** [review]
/lgtm

**Review by vrutkovs — APPROVED** [review]
/approve

**Pull request merged**
