### PR TITLE
Update go builder to 1.21 for stolostron/alertmanager

### PR DESCRIPTION
**Pull request by coleenquadros**
stolotstron/ALertmanager go builder is running 1.18. Updating it to 1.21

https://storage.googleapis.com/test-platform-results/pr-logs/pull/stolostron_prometheus-alertmanager/61/pull-ci-stolostron-prometheus-alertmanager-release-2.11-test/1795761369673371648/build-log.txt

https://github.com/stolostron/prometheus-alertmanager/pull/61

### CODE REVIEW

**Review by philipgough — APPROVED** [review]
/lgtm

**Comment by subbarao-meduri** [comment]
/pj-rehearse pull-ci-stolostron-prometheus-alertmanager-release-2.11-test

**Pull request merged**
