### PR TITLE
USHIFT-1247: Configure e2e test to be mandatory

### PR DESCRIPTION
**Pull request by pacevedom**

### CODE REVIEW

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-e2e

**Comment by dhellmann** [comment]
/lgtm
/hold

This looks good. I'm not sure if we're ready to merge, but if we are go ahead and remove the hold.

**Comment by dhellmann** [comment]
/lgtm

Let's wait for #40406 to merge before removing the hold on this one.

**Comment by dhellmann** [comment]
The tests passed on https://github.com/openshift/microshift/pull/1935j

/hold cancel

**Pull request merged**
