### PR TITLE
chore: update test images for stackrox/stackrox 4.4

### PR DESCRIPTION
**Pull request by tommartensen**
needs https://github.com/openshift/release/pull/51515.

### CODE REVIEW

**Review by vikin91 — APPROVED** [review]

**Review by fredrb — APPROVED** [review]

**Comment by tommartensen** [comment]
/hold

Because of #51515

**Comment by tommartensen** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-release-4.4-gke-qa-e2e-tests

**Comment by tommartensen** [comment]
/pj-rehearse ack

The test is failing, because release-4.4 branch is still on 1.20, while the image is 1.21.

**Comment by tommartensen** [comment]
Closing in favour of https://github.com/openshift/release/pull/51730.

I had temporarily updated this PR with an image with Go 1.21.8 to get some movement on this.

**Pull request closed without merging**
