### PR TITLE
Use one configmap for all grafana dashboards

### PR DESCRIPTION
**Pull request by hongkailiu**
Although there has been [no answers](https://coreos.slack.com/archives/C0VMT03S5/p1565906246461200) on the monitoring channel, I would like to give it a try here.

This would simplify the steps when we add new boards to grafana which has happened quite often recently.

/cc @stevekuznetsov @droslean 

After this merges and grafana-UI looks good, we need manual step:

```
oc delete configmap -n prow-monitoring grafana-dashboard-sinker --ignore-not-found=true --as=system:admin
oc delete configmap -n prow-monitoring grafana-dashboard-boskos --ignore-not-found=true --as=system:admin
oc delete configmap -n prow-monitoring grafana-dashboard-ghproxy --ignore-not-found=true --as=system:admin
oc delete configmap -n prow-monitoring grafana-dashboard-tide --ignore-not-found=true --as=system:admin
oc delete configmap -n prow-monitoring grafana-dashboard-hook --ignore-not-found=true --as=system:admin
oc delete configmap -n prow-monitoring grafana-dashboard-plank --ignore-not-found=true --as=system:admin
oc delete configmap -n prow-monitoring grafana-dashboard-jenkins-operator --ignore-not-found=true --as=system:admin
oc delete configmap -n prow-monitoring grafana-dashboard-deck --ignore-not-found=true --as=system:admin
oc delete configmap -n prow-monitoring grafana-dashboard-build-cop --ignore-not-found=true --as=system:admin
oc delete configmap -n prow-monitoring grafana-dashboard-prow --ignore-not-found=true --as=system:admin
oc delete configmap -n prow-monitoring grafana-dashboard-dptp --ignore-not-found=true --as=system:admin
oc delete configmap -n prow-monitoring grafana-dashboard-canary --ignore-not-found=true --as=system:admin
```

### CODE REVIEW

**Comment by droslean** [comment]
We need to add the make target to the main `postsubmit-update`

**Comment by hongkailiu** [comment]
> postsubmit-update

Yes, it is there already.

https://github.com/openshift/release/blob/579e59df7aff08ac7469e42bfc6f8821964b6fbc/Makefile#L44

**Comment by hongkailiu** [comment]
UI checks: Passed.

```
$ oc exec -n prow-monitoring grafana-7d75fc75d-b79hm -- ls /grafana-dashboard-definitions/0
Defaulting container name to grafana.
Use 'oc describe pod/grafana-7d75fc75d-b79hm -n prow-monitoring' to see all of the containers in this pod.
boskos.json
build_cop.json
canary.json
deck.json
dptp.json
e2e_template_jobs.json
ghproxy.json
hook.json
jenkins_operator.json
plank.json
prow.json
sinker.json
tide.json

```

**Comment by hongkailiu** [comment]
Much cleaner now:

```
$ oc delete configmap -n prow-monitoring grafana-dashboard-sinker --ignore-not-found=true --as=system:admin
configmap "grafana-dashboard-sinker" deleted
(p2env) [hongkliu@MiWiFi-R1CM-srv p2env]$ oc delete configmap -n prow-monitoring grafana-dashboard-boskos --ignore-not-found=true --as=system:admin
configmap "grafana-dashboard-boskos" deleted
(p2env) [hongkliu@MiWiFi-R1CM-srv p2env]$ oc delete configmap -n prow-monitoring grafana-dashboard-ghproxy --ignore-not-found=true --as=system:admin
configmap "grafana-dashboard-ghproxy" deleted
(p2env) [hongkliu@MiWiFi-R1CM-srv p2env]$ oc delete configmap -n prow-monitoring grafana-dashboard-tide --ignore-not-found=true --as=system:admin
configmap "grafana-dashboard-tide" deleted
(p2env) [hongkliu@MiWiFi-R1CM-srv p2env]$ oc delete configmap -n prow-monitoring grafana-dashboard-hook --ignore-not-found=true --as=system:admin
configmap "grafana-dashboard-hook" deleted
(p2env) [hongkliu@MiWiFi-R1CM-srv p2env]$ oc delete configmap -n prow-monitoring grafana-dashboard-plank --ignore-not-found=true --as=system:admin
configmap "grafana-dashboard-plank" deleted
(p2env) [hongkliu@MiWiFi-R1CM-srv p2env]$ oc delete configmap -n prow-monitoring grafana-dashboard-jenkins-operator --ignore-not-found=true --as=system:admin
configmap "grafana-dashboard-jenkins-operator" deleted
(p2env) [hongkliu@MiWiFi-R1CM-srv p2env]$ oc delete configmap -n prow-monitoring grafana-dashboard-deck --ignore-not-found=true --as=system:admin
configmap "grafana-dashboard-deck" deleted
(p2env) [hongkliu@MiWiFi-R1CM-srv p2env]$ oc delete configmap -n prow-monitoring grafana-dashboard-build-cop --ignore-not-found=true --as=system:admin
configmap "grafana-dashboard-build-cop" deleted
(p2env) [hongkliu@MiWiFi-R1CM-srv p2env]$ oc delete configmap -n prow-monitoring grafana-dashboard-prow --ignore-not-found=true --as=system:admin
configmap "grafana-dashboard-prow" deleted
(p2env) [hongkliu@MiWiFi-R1CM-srv p2env]$ oc delete configmap -n prow-monitoring grafana-dashboard-dptp --ignore-not-found=true --as=system:admin
configmap "grafana-dashboard-dptp" deleted
(p2env) [hongkliu@MiWiFi-R1CM-srv p2env]$ oc delete configmap -n prow-monitoring grafana-dashboard-canary --ignore-not-found=true --as=system:admin
configmap "grafana-dashboard-canary" deleted
(p2env) [hongkliu@MiWiFi-R1CM-srv p2env]$ oc get configmap -n prow-monitoring
NAME                                  DATA      AGE
grafana-dashboard-definitions-0       13        2h
grafana-dashboard-e2e-template-jobs   1         3d
grafana-dashboards                    1         120d
grafana-datasources                   1         120d
prometheus-prow-rulefiles-0           1         41m
(p2env) [hongkliu@MiWiFi-R1CM-srv p2env]$ oc delete configmap -n prow-monitoring grafana-dashboard-e2e-template-jobs --ignore-not-found=true --as=system:admin
configmap "grafana-dashboard-e2e-template-jobs" deleted

```

**Pull request merged**
