### PR TITLE
Update to have opendatahub-io tests use ocp 4.7 and 4.6

### PR DESCRIPTION
**Pull request by crobby**

### CODE REVIEW

**Comment by crobby** [comment]
/test pj-rehearse
flake on gather

**Comment by crobby** [comment]
/test pj-rehearse
gcp cluster flake this time

**Comment by crobby** [comment]
/retest
dashboard flake (I put up a PR to hopefully fix this)

**Comment by crobby** [comment]
/test pj-rehearse
multiple flakes

**Comment by crobby** [comment]
/test all
Hoping to pick up the fix to the dashboard test

**Review by anishasthana — APPROVED** [review]
/lgtm

**Pull request merged**
