### PR TITLE
Kuryr: Set master to 4.11

### PR DESCRIPTION
**Pull request by dulek**
This updates the RPM version of the build and points to 4.11 versions of
the repositories.

### CODE REVIEW

**Comment by dulek** [comment]
@MaysaMacedo  @gryf

**Comment by MaysaMacedo** [comment]
@dulek  there are some registries and tags using 4.10 in that file, do they need to be updated as well?

**Comment by dulek** [comment]
> @dulek there are some registries and tags using 4.10 in that file, do they need to be updated as well?

You mean `rhel-8-golang-1.17-openshift-4.10`? I don't think I ever touched them, it's probably supposed to be updated automatically. See commit d5a43c0d for example.

**Pull request merged**
