### PR TITLE
PowerVS: fix unsupported cluster type

### PR DESCRIPTION
**Pull request by hamzy**
The cluster type has changed from powervs to
powervs-1 and powervs-2

### CODE REVIEW

**Comment by hamzy** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-ovn-ppc64le-powervs

**Comment by jaypoulz** [comment]
This is fine, but I'm wondering if it would be better to future-proof this with a "starts with" or something

**Comment by hamzy** [comment]
So something like
powervs*)
?

**Comment by jaypoulz** [comment]
That's what I was thinking, but I'm not sure what the matching syntax is for bash. I would have to look it up. If that's correct, that might be cleaner.

**Comment by hamzy** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-ovn-ppc64le-powervs

**Comment by hamzy** [comment]
pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-ovn-ppc64le-powervs

**Comment by hamzy** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-ovn-ppc64le-powervs

**Comment by hamzy** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-ovn-ppc64le-powervs

**Comment by hamzy** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-serial-ovn-ppc64le-powervs

**Comment by hamzy** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-serial-ovn-ppc64le-powervs
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-ovn-ppc64le-powervs

**Comment by hamzy** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-ovn-ppc64le-powervs

**Pull request merged**
