### PR TITLE
feat: Add support for post-submit job on BM

### PR DESCRIPTION
**Pull request by vprashar2929**
This PR adds support for having a post-deploy job run on OCP running on BM.

### CODE REVIEW

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-operator-v1alpha1-kepler-operator-e2e

**Comment by aleskandro** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-operator-v1alpha1-kepler-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-operator-v1alpha1-kepler-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-operator-v1alpha1-kepler-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-operator-v1alpha1-kepler-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-operator-v1alpha1-kepler-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-operator-v1alpha1-kepler-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-operator-v1alpha1-kepler-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-operator-v1alpha1-kepler-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-operator-v1alpha1-kepler-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-operator-v1alpha1-kepler-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-operator-v1alpha1-kepler-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-operator-v1alpha1-kepler-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-operator-v1alpha1-kepler-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-operator-v1alpha1-kepler-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-operator-v1alpha1-kepler-operator-e2e

**Comment by vprashar2929** [comment]
Closing as creating a fresh one

**Pull request closed without merging**
