### PR TITLE
enable qe-catalogsource for gcp-ipi-workers-rhel8

### PR DESCRIPTION
**Pull request by Xia-Zhao-rh**
@xiaojiey @jianzhangbjz @kuiwang02 Please help to review it, thanks
Add step enable-qe-catalogsource 
Many cases are failed due to qe-app-registry is not installed
https://reportportal-openshift.apps.ocp-c1.prod.psi.redhat.com/ui/#prow/launches/722/320719?item0Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.type%3DSTEP%26launchesLimit%3D50%26isLatest%3Dfalse%26filter.in.status%3DFAILED%252CINTERRUPTED%26page.page%3D1

### CODE REVIEW

**Comment by Xia-Zhao-rh** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-gcp-ipi-workers-rhel8-fips-p2-f7

**Comment by xiaojiey** [comment]
@Xia-Zhao-rh Thanks a lot for the PR.
/lgtm

**Comment by Xia-Zhao-rh** [comment]
@jianlinliu would you please help to approve it?

Test result:
https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/36449/rehearse-36449-periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-gcp-ipi-workers-rhel8-fips-p2-f7/1626115579821690880/artifacts/gcp-ipi-workers-rhel8-fips-p2-f7/enable-qe-catalogsource/build-log.txt

https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/36449/rehearse-36449-periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-gcp-ipi-workers-rhel8-fips-p2-f7/1626115579821690880/artifacts/gcp-ipi-workers-rhel8-fips-p2-f7/openshift-extended-test/build-log.txt

The qe-app-registry is installed successfully

**Pull request merged**
