### PR TITLE
BM CPT Add restrict_network_access flag

### PR DESCRIPTION
**Pull request by josecastillolema**
Preparing the BM CPT lab for the network connectivity changes coming in:
 - https://github.com/openshift/ci-tools/pull/4247
 - https://github.com/openshift/ci-docs/pull/490

### CODE REVIEW

**Comment by josecastillolema** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-x86-ping-bastion

**Comment by josecastillolema** [comment]
cc @jtaleric @bear-redhat

**Comment by jtaleric** [comment]
I was under the impression with this change we can remove the pinning to `build05`, is that true @bear-redhat ?

**Comment by josecastillolema** [comment]
@bear-redhat could you please address comment https://github.com/openshift/release/pull/56624#issuecomment-2346538029 ?
Thanks!

**Comment by bear-redhat** [comment]
> I was under the impression with this change we can remove the pinning to `build05`, is that true @bear-redhat ?

still, not all clusters have access to RH intranet... you can try b10 atm.

**Comment by jtaleric** [comment]
> > I was under the impression with this change we can remove the pinning to `build05`, is that true @bear-redhat ?
> 
> still, not all clusters have access to RH intranet... you can try b10 atm. I will take a while to bring existing clusters to be RH intranet-enabled (potentially need to rebuild those clusters)

ack - so it is preferred we keep build05 as our default

**Review by jtaleric — APPROVED** [review]
/lgtm

**Pull request merged**
