### PR TITLE
IBMCloud: Add upgrade workflow for IBM Cloud

### PR DESCRIPTION
**Pull request by cjschaef**
Add workflow for IBM Cloud for upgrade testing. This includes adding a stableinitial workflow and integrating the gather-ibmcloud-resource step into the default ipi-ibmcloud-post workflow (removing duplications).

### CODE REVIEW

**Comment by cjschaef** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-upgrade-from-stable-4.15-e2e-ibmcloud-upgrade-ovn periodic-ci-openshift-ovn-kubernetes-master-e2e-ibmcloud-ipi-ovn-periodic

**Comment by cjschaef** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-upgrade-from-stable-4.15-e2e-ibmcloud-upgrade-ovn periodic-ci-openshift-ovn-kubernetes-master-e2e-ibmcloud-ipi-ovn-periodic

**Comment by cjschaef** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-upgrade-from-stable-4.15-e2e-ibmcloud-upgrade-ovn periodic-ci-openshift-ovn-kubernetes-master-e2e-ibmcloud-ipi-ovn-periodic

**Comment by cjschaef** [comment]
MonitorTest failures are being investigated separately, as they fail consistently ATM, which appears to be the case for both rehearsals.
https://issues.redhat.com/browse/OCPBUGS-30267

/pj-rehearse ack

**Comment by jeffnowicki** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-upgrade-from-stable-4.15-e2e-ibmcloud-upgrade-ovn periodic-ci-openshift-ovn-kubernetes-master-e2e-ibmcloud-ipi-ovn-periodic

**Pull request closed without merging**
