### PR TITLE
Use src image in upstream SRO lint test

### PR DESCRIPTION
**Pull request by pacevedom**

### CODE REVIEW

**Comment by pacevedom** [comment]
cc @ybettan

**Comment by ybettan** [comment]
If I am not mistaken, `src` image is directly build from the Dockerfile in the tested repo.
The Dockerfile in the repo assumes that the `helm` package was patched because this is what the image-build process in the makefile does BUT, building directly from the Dockerfile is failing as we get compilation errors (due to skipping on the patching stage)

**Comment by ybettan** [comment]
/hold 
Wait for https://github.com/openshift-psap/special-resource-operator/pull/183 to be merged first

**Comment by pacevedom** [comment]
Closing in favor of https://github.com/openshift/release/pull/24385

**Pull request closed without merging**
