### PR TITLE
Jboss Fuse Camel-k zstream onboarding on ibmcloud

### PR DESCRIPTION
**Pull request by smatula**

### CODE REVIEW

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-jboss-fuse-camel-k-test-container-main-camel-k-ocp4.15-lp-interop-camel-k-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-jboss-fuse-camel-k-test-container-main-camel-k-ocp4.14-lp-interop-camel-k-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-jboss-fuse-camel-k-test-container-main-camel-k-ocp4.15-lp-interop-camel-k-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-jboss-fuse-camel-k-test-container-main-camel-k-ocp4.14-lp-interop-camel-k-interop-aws

**Review by Simranpal — APPROVED** [review]
/lgtm

**Pull request merged**
