### PR TITLE
[WIP] Adding baremetal-lab-ipi workflow to prow CI

### PR DESCRIPTION
**Pull request by jadhaj**

### CODE REVIEW

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-baremetal-ipi-ovn-ipv4-p1-f14

**Comment by jadhaj** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-baremetal-ipi-ovn-ipv4-p1-f14

**Comment by jadhaj** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-baremetal-ipi-ovn-ipv4-p1-f14

**Comment by jadhaj** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-baremetal-ipi-ovn-ipv4-p1-f14

**Comment by jadhaj** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-baremetal-ipi-ovn-ipv4-p1-f14

**Comment by jadhaj** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-baremetal-ipi-ovn-ipv4-p1-f14

**Comment by jadhaj** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-baremetal-ipi-ovn-ipv4-p1-f14

**Comment by jadhaj** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-baremetal-ipi-ovn-ipv4-p1-f14

**Comment by jadhaj** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-baremetal-ipi-ovn-ipv4-p1-f14

**Comment by jadhaj** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-baremetal-ipi-ovn-ipv4-p1-f14

**Comment by jadhaj** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-baremetal-ipi-ovn-ipv4-p1-f14

**Comment by jadhaj** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-baremetal-ipi-ovn-ipv4-p1-f14

**Comment by jadhaj** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-baremetal-ipi-ovn-ipv4-p1-f14

**Pull request closed without merging**
