### PR TITLE
Krkn upgrade

### PR DESCRIPTION
**Pull request by paigerube14**
Using openshift random pod scenario as observer during upgrade

### CODE REVIEW

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-aws-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-gcp-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-gcp-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-gcp-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-test-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-gcp-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-gcp-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-aws-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-gcp-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-gcp-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-gcp-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-gcp-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.15-nightly-krkn-hub-tests-415-gcp

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-gcp-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-gcp-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-gcp-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-gcp-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-gcp-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-test-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-test-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-test-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-test-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-test-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-test-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-test-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-test-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-gcp-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-upgrade-chaos-gcp-loaded-upgrade-415to416

**Comment by paigerube14** [comment]
@shahsahil264 @chaitanyaenr PTAL

**Review by shahsahil264 — APPROVED** [review]
LGTM

**Review by chaitanyaenr — APPROVED** [review]
/lgtm

**Pull request merged**
