### PR TITLE
:broom: Reconfigure branches 1.5 - 1.8 for kn-event

### PR DESCRIPTION
**Pull request by cardil**
## Changes

- :broom: Reconfigure branches 1.5 - 1.8 for kn-event

### CODE REVIEW

**Comment by cardil** [comment]
Closes #32838

**Comment by dsimansk** [comment]
@cardil are those tests DDoSing Github? :)

**Comment by dsimansk** [comment]
`release-next` is a genuine error due to the overrides dir. Otherwise it should look much better than then http timeout error.

**Comment by dsimansk** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/34573/rehearse-34573-pull-ci-openshift-knative-kn-plugin-event-release-next-e2e-aws-ocp-411/1600454642456596480

I seem for `release-next` E22E tests we need to unset GOFLAGS in config or e2e-test.sh script. I think in client's config we reuse already build binary in the E2E tests, IIRC. I'll check it.

**Comment by dsimansk** [comment]
@cardil I'd ack those 2 tests. Given release-next can be fixed in e2e script. And we can check if 1.8 needs further debug.

**Comment by cardil** [comment]
@dsimansk Let me take a look at those a bit...

**Comment by dsimansk** [comment]
For the e2e script reference, mage is called here. https://github.com/openshift-knative/kn-plugin-event/blob/release-next/test/e2e-tests.sh#L27-L29.

Maybe it would be easier to maintain a modified mage wrapper script with `GOFLAGS` env var. To really have it only in a single place. Deviate would replace file called `mage` 1:1 right?

**Comment by cardil** [comment]
> @dsimansk: _Deviate would replace file called mage 1:1 right?_

We can have a wrapper. It will be over layered on top of upstream file, by Deviate tool.

But, I would rather not want it.

**Comment by cardil** [comment]
Let's merge https://github.com/openshift-knative/kn-plugin-event/pull/273 (and cherrypicks). After that, I'll update this config to remove `GOFLAGS` lines.

Hopefully, we will get passes then.

**Comment by cardil** [comment]
The error `execution.go:64: Panic happened: 'runtime error: index out of range [0] with length 0'` is already fixed on master: https://github.com/knative-sandbox/kn-plugin-event/blame/main/test/e2e/ics_send.go#L111-L113

The reasons for 1.8 failures are unknown for me. The above error, unfortunately covers up the real reasons...

/pj-rehearse pull-ci-openshift-knative-kn-plugin-event-release-1.8-e2e-aws-ocp-411

**Comment by dsimansk** [comment]
If the majority of rehearsal jobs passes, I'd merge this PR and specifically debug the suspicious release branch.

**Comment by cardil** [comment]
Right, make sense.

So, I think we can safely merge this PR, and then the sync PR https://github.com/openshift-knative/kn-plugin-event/pull/267 should pass nicely.

/pj-rehearse ack

**Pull request merged**
