### PR TITLE
Fix perms error in CI by using nss_wrapper

### PR DESCRIPTION
**Pull request by jmrodri**
The template-service-broker-operator is failing because of permissions error because we can no longer write to `/etc/passwd`. The way to fix this is use the NSS_WRAPPER. This PR is unfortunately on a PR https://github.com/openshift/template-service-broker-operator/pull/95 in the template-service-broker-operator repo.

### CODE REVIEW

**Comment by shawn-hurley** [comment]
@jmrodri don't we need to ignore the tests or remove them because the service catalog is removed in master now?

**Comment by jmrodri** [comment]
> @jmrodri don't we need to ignore the tests or remove them because the service catalog is removed in master now?
@shawn-hurley yes, I just posted a fix to remove them.

**Pull request merged**
