### PR TITLE
vSphere: move zonal jobs to vsphere02

### PR DESCRIPTION
**Pull request by jcpowermac**

### CODE REVIEW

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-vsphere-zones periodic-ci-openshift-release-master-nightly-4.13-e2e-vsphere-upi-zones

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-vsphere-zones periodic-ci-openshift-release-master-nightly-4.13-e2e-vsphere-upi-zones

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-vsphere-zones periodic-ci-openshift-release-master-nightly-4.13-e2e-vsphere-upi-zones

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-vsphere-zones

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-vsphere-zones

**Comment by jcpowermac** [comment]
/pj-rehearse  periodic-ci-openshift-release-master-nightly-4.13-e2e-vsphere-upi-zones

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-vsphere-zones periodic-ci-openshift-release-master-nightly-4.13-e2e-vsphere-upi-zones

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-vsphere-upi-zones

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-vsphere-upi-zones

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-vsphere-upi-zones

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-vsphere-upi-zones

**Comment by jcpowermac** [comment]
We have no network redundancy until this pr is merged and we can reconfigure all the vswitches

**Comment by cgwalters** [comment]
Technically MCO approvals should go via @sinnykumari e.g. but
/approve

**Review by damdo — COMMENTED** [review]
/lgtm

**Comment by WenXinWei** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-vsphere-ipi-zones-f14

**Comment by jcpowermac** [comment]
In job failures caused by
```
CONFLICT (content): Merge conflict in ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
```
had to rebase

**Pull request merged**
