### PR TITLE
Replace CNV smoke tests with e2e tests

### PR DESCRIPTION
**Pull request by rabin-io**

### CODE REVIEW

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-cnv-tests-main-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-cnv-tests-main-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-cnv-tests-main-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-cnv-tests-main-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-cnv-tests-main-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
retest 
/pj-rehearse periodic-ci-RedHatQE-cnv-tests-main-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
with timeout of 3h
/pj-rehearse periodic-ci-RedHatQE-cnv-tests-main-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
With timeout of 3h and must-gather after 30m

/pj-rehearse periodic-ci-RedHatQE-cnv-tests-main-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
OCP_MAJOR_MINOR var

/pj-rehearse periodic-ci-RedHatQE-cnv-tests-main-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
Bigger nodes, 

/pj-rehearse periodic-ci-RedHatQE-cnv-tests-main-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
Add exit condition to background function

/pj-rehearse periodic-ci-RedHatQE-cnv-tests-main-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-cnv-tests-main-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-cnv-tests-main-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-cnv-tests-main-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-cnv-tests-main-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-cnv-tests-main-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-cnv-tests-main-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-cnv-tests-main-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-cnv-tests-main-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-cnv-tests-main-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-cnv-tests-main-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-cnv-tests-main-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-cnv-tests-main-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-cnv-tests-cnv-4.13-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
/pj-rehearse pull-ci-RedHatQE-cnv-tests-cnv-4.13-ocp-cnv-odf-4.13-images

**Comment by rabin-io** [comment]
/pj-rehearse pull-ci-RedHatQE-cnv-tests-cnv-4.13-ocp-cnv-odf-4.13-images

**Comment by rabin-io** [comment]
/pj-rehearse pull-ci-RedHatQE-interop-testing-cnv-4.13-ocp-cnv-odf-4.13-images

**Comment by rabin-io** [comment]
/pj-rehearse pull-ci-RedHatQE-interop-testing-cnv-4.13-ocp-cnv-odf-4.13-images

**Comment by rabin-io** [comment]
/pj-rehearse pull-ci-RedHatQE-interop-testing-cnv-4.13-ocp-cnv-odf-4.13-images

**Comment by rabin-io** [comment]
/pj-rehearse pull-ci-RedHatQE-interop-testing-cnv-4.13-ocp-cnv-odf-4.13-images

**Comment by rabin-io** [comment]
/pj-rehearse pull-ci-RedHatQE-interop-testing-cnv-4.13-ocp-cnv-odf-4.13-images

**Comment by rabin-io** [comment]
/pj-rehearse pull-ci-RedHatQE-interop-testing-cnv-4.13-ocp-cnv-odf-4.13-images

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.13-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
/pj-rehearse pull-ci-RedHatQE-interop-testing-cnv-4.13-ocp-cnv-odf-4.13-images

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.13-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.13-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.13-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.13-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.13-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
/pj-reharse periodic-ci-RedHatQE-interop-testing-cnv-4.12-ocp-cnv-odf-4.12-cnv-odf-tests-aws-upi-ocp412

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.12-ocp-cnv-odf-4.12-cnv-odf-tests-aws-upi-ocp412

**Comment by rabin-io** [comment]
Create the branches at RedhatQE/interop-testing repo 

/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.12-ocp-cnv-odf-4.12-cnv-odf-tests-aws-upi-ocp412

**Comment by rabin-io** [comment]
Created the temp branches on rabin-io/cnv-ci

/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.12-ocp-cnv-odf-4.12-cnv-odf-tests-aws-upi-ocp412

**Comment by rabin-io** [comment]
Created the temp branches on rabin-io/cnv-ci

/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.12-ocp-cnv-odf-4.12-cnv-odf-tests-aws-upi-ocp412

**Comment by rabin-io** [comment]
@dshchedr Can you please review this pr?
Until this [PR](https://github.com/openshift-cnv/cnv-ci/pull/67) is merged, we are using my clone.

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.13-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.13-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Review by dbasunag — APPROVED** [review]

**Pull request merged**
