### PR TITLE
WIP - Run all SNO live cd tests

### PR DESCRIPTION
**Pull request by omertuc**

### CODE REVIEW

**Comment by romfreiman** [comment]
this will run all tests? Do u give enough resources to the VM?

**Comment by omertuc** [comment]
> this will run all tests? Do u give enough resources to the VM?

It should, yeah. 

Regarding resources - test infra deploy_ibip is responsible for choosing how much resources are allocated. Will check if it's currently enough

**Comment by osherdp** [comment]
```
        master_memory=32 * 1024,  # 32GB of RAM
        master_vcpu=12,
```

**Comment by omertuc** [comment]
/test pj-rehearse

Infra was updated to have more resources https://github.com/openshift/assisted-test-infra/pull/609

**Comment by omertuc** [comment]
Blocked by https://github.com/openshift/assisted-test-infra/pull/715

**Comment by omertuc** [comment]
> Blocked by [openshift/assisted-test-infra#715](https://github.com/openshift/assisted-test-infra/pull/715)

Merged

/retest

**Pull request closed without merging**
