### PR TITLE
ci-operator: Rename "operator install ..." to "operator conditions ..."

### PR DESCRIPTION
**Pull request by wking**
These test-cases from b6ab356b (#10957) occur in all gathers where an operator is sad, not just in gathers that run after failed installs.  Convert to a genric name to reduce confusion.

Generated with:

```console
$ sed -i 's/operator install /operator conditions /g' $(git grep -l 'operator install ')
```

### CODE REVIEW

**Review by vrutkovs — APPROVED** [review]
/lgtm
/cc bparees

**Comment by bparees** [comment]
this is going to cause a disruption in the ability to compare current/previous pass rates in sippy for these tests (since the names changed).

@mfojtik @deads2k would you prefer to wait until post 4.6GA (or at least code freeze) to land this?  Or are you ok losing that comparison?

**Comment by bparees** [comment]
/approve
/hold

(holding pending feedback from @mfojtik and @deads2k )

**Comment by deads2k** [comment]
lgtm to me as well.  Sippy is now updated to handle it.  I don't see a rehearse though.

**Comment by bparees** [comment]
/rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-aws-serial

**Comment by bparees** [comment]
@openshift/openshift-team-developer-productivity-test-platform this didn't rehearse because it would rehearse too many jobs:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/12298/pull-ci-openshift-release-master-pj-rehearse/1310983682479099904

 time="2020-09-29T16:45:41Z" level=info msg="Would rehearse too many jobs, will not proceed" org=openshift rehearsal-jobs=67 rehearsal-threshold=45 repo=release


is there a way to make it rehearse one at least?

**Comment by petr-muller** [comment]
@bparees Unfortunately the only way to do so is to have a PR that only touches one of the changed templates/steps

**Pull request merged**
