### PR TITLE
[WIP] add support for ocp 4.18 for sbo

### PR DESCRIPTION
**Pull request by vi-patel**
add support for ocp 4.18 for sbo

### CODE REVIEW

**Comment by vi-patel** [comment]
/pj-rehearse periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.18-acceptance-lp-interop-fips

**Comment by vi-patel** [comment]
/pj-rehearse periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.18-acceptance-lp-interop

**Comment by sadlerap** [comment]
This configuration isn't needed anymore, since [SBO has been archived](https://github.com/redhat-developer/service-binding-operator?tab=readme-ov-file#deprecation-notice).  Removing the entire config for SBO has been on my backlog for a while, might as well get around to cleaning it up.

I've filed #57112 to remove the config, since at this point there's nothing that can be done if these tests indicate an issue.

**Comment by vi-patel** [comment]
> This configuration isn't needed anymore, since [SBO has been archived](https://github.com/redhat-developer/service-binding-operator?tab=readme-ov-file#deprecation-notice). Removing the entire config for SBO has been on my backlog for a while, might as well get around to cleaning it up.
> 
> I've filed #57112 to remove the config, since at this point there's nothing that can be done if these tests indicate an issue.



> This configuration isn't needed anymore, since [SBO has been archived](https://github.com/redhat-developer/service-binding-operator?tab=readme-ov-file#deprecation-notice). Removing the entire config for SBO has been on my backlog for a while, might as well get around to cleaning it up.
> 
> I've filed #57112 to remove the config, since at this point there's nothing that can be done if these tests indicate an issue.

Thanks for letting me know @sadlerap I will let my team know this is no longer needed for osp 4.18 testing.

**Pull request closed without merging**
