### PR TITLE
Adds ROSA EC Build

### PR DESCRIPTION
**Pull request by krishvoor**
This PR adds EC build for ROSA 4.14

### CODE REVIEW

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-multiaz-ec-ci-tests-2nodes-periodic

**Comment by svetsa-rh** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-multiaz-ec-ci-tests-2nodes-periodic

**Comment by svetsa-rh** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-multiaz-ec-ingress-defaultnodes-periodic periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-singleaz-ec-network-perf-2nodes-periodic

**Comment by svetsa-rh** [comment]
@krishvoor looks good to me. Let's get at least one passing test run to make sure EC_BUILD env is recognized by these tests.

**Comment by krishvoor** [comment]
/pj-rehearse  periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-singleaz-ec-network-perf-2nodes-periodic

**Comment by krishvoor** [comment]
> @krishvoor looks good to me. Let's get at least one passing test run to make sure EC_BUILD env is recognized by these tests.

@svetsa-rh: The `EC_BUILD` is taking effect, but we are seeing this issues in the [logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/41919/rehearse-41919-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-singleaz-ec-network-perf-2nodes-periodic/1688409904794046464/artifacts/perfscale-rosa-singleaz-ec-network-perf-2nodes-periodic/rosa-conf-idp-htpasswd/build-log.txt)  which is not related to the PR:

```
Logging into staging with offline token using rosa cli 1.2.25
INFO: Logged in as 'ocm-prowci' on 'https://api.stage.openshift.com'
API URL is not registered back. Wait for 60 seconds...
API URL is not registered back. Wait for 60 seconds...
API URL is not registered back. Wait for 60 seconds...
API URL is not registered back. Wait for 60 seconds...
API URL is not registered back. Wait for 60 seconds...
API URL is not registered back. Wait for 60 seconds...
API URL is not registered back. Wait for 60 seconds...
API URL is not registered back. Wait for 60 seconds...
API URL is not registered back. Wait for 60 seconds...
API URL is not registered back. Wait for 60 seconds...
API URL is not registered back. Wait for 60 seconds...
API URL is not registered back. Wait for 60 seconds...
API URL is not registered back. Wait for 60 seconds...
API URL is not registered back. Wait for 60 seconds...
API URL is not registered back. Wait for 60 seconds...
error: Timed out while waiting for the API URL to be ready
```

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-singleaz-ec-network-perf-2nodes-periodic

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-singleaz-ec-network-perf-2nodes-periodic

**Comment by krishvoor** [comment]
[Logs](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/41919/rehearse-41919-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-singleaz-ec-network-perf-2nodes-periodic/1689682447718944768) indicate an error during de-provisioning step, and is likely a "timeout" issue.

1) Will rebase the branch 
2) And bump the timeout

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-singleaz-ec-network-perf-2nodes-periodic

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-singleaz-ec-network-perf-2nodes-periodic

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-multiaz-ec-ingress-defaultnodes-periodic

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-multiaz-ec-ci-tests-2nodes-periodic

**Comment by svetsa-rh** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-multiaz-ec-ingress-defaultnodes-periodic periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-singleaz-ec-network-perf-2nodes-periodic

**Comment by svetsa-rh** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-multiaz-ec-ingress-defaultnodes-periodic periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-singleaz-ec-network-perf-2nodes-periodic

**Comment by svetsa-rh** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-multiaz-ec-datapath-defaultnodes-periodic

**Comment by svetsa-rh** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-singleaz-ec-datapath-perf-2nodes-periodic

**Comment by krishvoor** [comment]
This job is failing [here](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/41919/rehearse-41919-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-multiaz-ec-datapath-defaultnodes-periodic/1691528009208565760) which are not exactly related to the PR in itself

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-singleaz-ec-datapath-perf-2nodes-periodic

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-multiaz-ec-datapath-defaultnodes-periodic

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-singleaz-ec-data-path-perf-2nodes-periodic

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-multiaz-ec-ci-tests-2nodes-periodic

**Comment by svetsa-rh** [comment]
@krishvoor Try rebase and then run `make update` and push your changes here and then try the tests.

**Comment by krishvoor** [comment]
> @krishvoor Try rebase and then run `make update` and push your changes here and then try the tests.

@svetsa-rh  just did, and nothing changed in the `make update`

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-multiaz-ec-ci-tests-2nodes-periodic

**Comment by krishvoor** [comment]
> @krishvoor Try rebase and then run `make update` and push your changes here and then try the tests.

@svetsa-rh I did that, current failure on this [job](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/41919/rehearse-41919-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-multiaz-ec-ci-tests-2nodes-periodic/1692012871178784768) is due to this

```
Logging into staging with offline token using rosa cli 1.2.25
INFO: Logged in as 'ocm-prowci' on 'https://api.stage.openshift.com'
/bin/bash: line 42: HOSTED_CP: unbound variable
```

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-multiaz-ec-ci-tests-2nodes-periodic

**Comment by svetsa-rh** [comment]
@krishvoor PR https://github.com/openshift/release/pull/42468 is now merged just few min ago.
Can you rebase again and re-test?

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-multiaz-ec-ci-tests-2nodes-periodic

**Pull request merged**
