### PR TITLE
Update pr checks and all ocp nightly jobs to use ephemeral cluster

### PR DESCRIPTION
**Pull request by subhashkhileri**
https://issues.redhat.com/browse/RHIDP-4991

### CODE REVIEW

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-main-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-main-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-main-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-main-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-main-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-main-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-main-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-main-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-main-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-main-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-main-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-main-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-main-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-main-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-main-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-main-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-main-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse periodic-ci-janus-idp-backstage-showcase-main-e2e-tests-nightly

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-main-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-main-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse periodic-ci-janus-idp-backstage-showcase-main-e2e-tests-nightly

**Review by josephca — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
