### PR TITLE
Add KUTTL job execution for openstack-k8s-operators/telemetry-operator

### PR DESCRIPTION
**Pull request by paramite**
Depends-On: https://github.com/openstack-k8s-operators/install_yamls/pull/606

### CODE REVIEW

**Comment by paramite** [comment]
Hi @frenzyfriday  @lewisdenny @viroel, anything else I need to do with this PR or are we good to go?

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-telemetry-operator-main-telemetry-operator-build-deploy-kuttl

**Comment by viroel** [comment]
> Hi @frenzyfriday @lewisdenny @viroel, anything else I need to do with this PR or are we good to go?

Let's make sure that test is passing, then we are good to merge. Thanks!

**Comment by viroel** [comment]
/pj-rehearse ack

tests running and passing: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/45552/rehearse-45552-pull-ci-openstack-k8s-operators-telemetry-operator-main-telemetry-operator-build-deploy-kuttl/1724396947193729024/artifacts/telemetry-operator-build-deploy-kuttl/openstack-k8s-operators-kuttl/artifacts/kuttl-test-telemetry.json

**Comment by viroel** [comment]
/pj-rehearse ack

minor update on build cluster since last job run

**Pull request merged**
