### PR TITLE
415 loaded upgrade

### PR DESCRIPTION
**Pull request by paigerube14**
Want to be able to run 415 loaded upgrade from 4.14

### CODE REVIEW

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-loaded-upgrade-from-4.14-perfscale-aws-24nodes-loaded-upgrade-414to415

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-loaded-upgrade-from-4.14-perfscale-aws-24nodes-loaded-upgrade-414to415

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-loaded-upgrade-from-4.14-perfscale-aws-24nodes-loaded-upgrade-414to415

**Comment by qiliRedHat** [comment]
LGTM, will see if @svetsa-rh  has any comment about the cron.

**Comment by qiliRedHat** [comment]
@paigerube14 I approved the pr, if there is any cadence conflict we can change it later.

**Pull request merged**
