### PR TITLE
LOG-2205: Setup CI for logging-fluentd

### PR DESCRIPTION
**Pull request by jcantrill**
This PR:
* Establishes CI for viaq/logging-fluentd

Ref: https://issues.redhat.com/browse/LOG-2205

### CODE REVIEW

**Comment by jcantrill** [comment]
cc @vimalk78 @syedriko @cahartma @vparfonov @alanconway

**Comment by jcantrill** [comment]
@syedriko once we have this in place we can add config to support 1.7.4 and a newer version and adjust cpaas accordingly

**Review by hongkailiu — APPROVED** [review]

**Review by alanconway — APPROVED** [review]
/lgtm

**Pull request merged**
