### PR TITLE
NO-ISSUE: build image-service image in CI with centos stream 9

### PR DESCRIPTION
**Pull request by danmanor**
This PR is a leftover from https://github.com/openshift/assisted-image-service/pull/266

### CODE REVIEW

**Comment by adriengentil** [comment]
can you remove other references to centos 8 ? We still have it here for example: https://github.com/openshift/release/blob/master/ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-main.yaml#L10

**Comment by danmanor** [comment]
@adriengentil Yes, done

**Review by adriengentil — APPROVED** [review]

**Pull request merged**
