### PR TITLE
Interop - Update Openshift-Pipelines scenario on Rosa Classic on OCP 4.16

### PR DESCRIPTION
**Pull request by oharan2**

### CODE REVIEW

**Comment by oharan2** [comment]
/pj-rehearse pull-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.16-lp-rosa-classic-images

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.16-lp-rosa-classic-openshift-pipelines-interop-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.16-lp-rosa-classic-openshift-pipelines-interop-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse pull-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.16-lp-rosa-classic-images

**Review by VeereshAradhya — APPROVED** [review]

**Pull request merged**
