### PR TITLE
Add master bots

### PR DESCRIPTION
**Pull request by mfojtik**
This PR add manifests for master team publisher bots.

### CODE REVIEW

**Comment by tnozicka** [comment]
@smarterclayton I was hoping this is the location where you would just apply all the yaml files when recreating the cluster but this
https://github.com/openshift/release/blob/master/cluster/ci/config/publishingbots/image-registry/config.yaml#L1-L4 
can't possibly pass

**Comment by stevekuznetsov** [comment]
Add it to `make postsubmit-update` to get it updated on pushes

**Comment by stevekuznetsov** [comment]
What's left here @mfojtik @sttts ? If you want to merge it now and iterate like I mentioned you should add it to the `make` target

**Comment by mfojtik** [comment]
@stevekuznetsov merge now, iterate as needed

**Comment by stevekuznetsov** [comment]
@mfojtik is this still active?

**Pull request closed without merging**
