### PR TITLE
OKD: add assisted periodics for 4.13

### PR DESCRIPTION
**Pull request by vrutkovs**
Checks that OKD can be installed using assisted installer

### CODE REVIEW

**Comment by vrutkovs** [comment]
Wrong OS (RHCOS) is selected for bootstrap node, needs https://github.com/openshift/assisted-test-infra/pull/1940

**Comment by vrutkovs** [comment]
Disk speed failure?

/pj-rehearse

**Comment by vrutkovs** [comment]
```
time="2022-12-07T20:05:52Z" level=error msg="Received step reply <installation-disk-speed-check-7aaa3d59> from infra-env <c32da5de-78c3-4020-8248-d653db4d6ac2> host <dbc9de4c-0835-42b2-be02-68ba1ef06614> exit-code <255> stderr <Could not get I/O performance for path /dev/disk/by-path/pci-0000:00:06.0 (fio exit code: 1, stderr: fio: io_u error on file /dev/disk/by-path/pci-0000: No space left on device: write offset=4194304, buflen=896\n)> stdout <{\"path\":\"/dev/disk/by-path/pci-0000:00:06.0\"}>" ...
```
https://github.com/openshift/assisted-installer-agent/pull/464 would fix that

**Comment by vrutkovs** [comment]
podman issue: error while loading shared libraries: librt.so.1: cannot change memory protections

/pj-rehearse

**Comment by vrutkovs** [comment]
SNO: doesn't come back from the reboot
HA: console can't resolve itself

/pj-rehearse

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-okd-4.13-e2e-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-okd-4.12-e2e-assisted
/pj-rehearse periodic-ci-openshift-release-master-okd-4.13-e2e-assisted
/pj-rehearse periodic-ci-openshift-release-master-okd-4.12-e2e-vsphere-ovn
/pj-rehearse periodic-ci-openshift-release-master-okd-4.13-e2e-vsphere-ovn

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-okd-4.12-e2e-assisted
/pj-rehearse periodic-ci-openshift-release-master-okd-4.13-e2e-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-okd-4.12-e2e-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-okd-4.12-e2e-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-okd-4.12-e2e-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-okd-4.12-e2e-assisted
/pj-rehearse periodic-ci-openshift-release-master-okd-4.13-e2e-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-okd-4.12-e2e-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-okd-4.12-e2e-assisted

**Comment by LorbusChris** [comment]
needs another run of `make jobs`

**Pull request merged**
