### PR TITLE
Decrease 4.11 test frequency

### PR DESCRIPTION
**Pull request by liangxia**
/cc @jianlinliu @gpei @yunjiang29 @jhou1

### CODE REVIEW

**Comment by gpei** [comment]
@liangxia do we have a plan to coordinate the weekly jobs with the 4.11.z release cycle? I mean such as 4.11.z is planned to be shipped every Monday, then we can execute our e2e jobs before Thu/Fri?, the timeline(if there is one) we want to finish 4.11.z regression testing.

**Comment by gpei** [comment]
@liangxia do we have a plan to coordinate the weekly jobs with the 4.11.z release cycle? I mean such as 4.11.z is planned to be shipped every Monday, then we can execute our e2e jobs before Thu/Fri?, the timeline(if there is one) we want to finish 4.11.z regression testing.

**Comment by liangxia** [comment]
> @liangxia do we have a plan to coordinate the weekly jobs with the 4.11.z release cycle? I mean such as 4.11.z is planned to be shipped every Monday, then we can execute our e2e jobs before Thu/Fri?, the timeline(if there is one) we want to finish 4.11.z regression testing.

We haven't started the migration from Jenkins to Prow for 4.11 yet. 
Mainly on 4.12 currently (add tests in Prow, and remove tests in Jenkins, in parallel), due to limited resource to support us running tests on both Prow CI and Jenkins CI.

**Pull request merged**
