### PR TITLE
NO-ISSUE: upgrading linter assisted-image-service

### PR DESCRIPTION
**Pull request by eifrach**
upgrading go linter  
* support for go package upgrades 
* newer vulnerability scan's 
* fix  test failing on [PR#133 ](https://github.com/openshift/assisted-image-service/pull/133)

### CODE REVIEW

**Review by adriengentil — APPROVED** [review]

**Review by osherdp — APPROVED** [review]

**Comment by eifrach** [comment]
/pj-rehearse pull-ci-openshift-assisted-image-service-release-ocm-2.6-lint

**Comment by osherdp** [comment]
@eifrach I don't think we need to run all the tests, you can just do
```
/pj-rehearse pull-ci-openshift-assisted-image-service-main-edge-lint
```

**Pull request merged**
