### PR TITLE
Add odf-console: release-4.13/comp branches

### PR DESCRIPTION
**Pull request by SanjalKatiyar**
Enable CI for release-4.13 and release-4.13-compatibility branches (odf-console).

### CODE REVIEW

**Review by bipuladh — COMMENTED** [review]
/hold
Lets wait for @alfonsomthd to create a docker image for our CI

**Comment by alfonsomthd** [comment]
> /hold Lets wait for @alfonsomthd to create a docker image for our CI

Our image is already pushed, so we can update these yaml's and merge this.

**Review by bipuladh — CHANGES_REQUESTED** [review]
/hold cancel
Lets remove the dockerfile_literal and use the pushed image.

**Comment by SanjalKatiyar** [comment]
/pj-rehearse pull-ci-red-hat-storage-odf-console-release-4.13-odf-console-e2e-aws

**Review by bipuladh — APPROVED** [review]
/lgtm

**Review by umangachapagain — APPROVED** [review]

**Pull request merged**
