### PR TITLE
add azure-misc repo to prow

### PR DESCRIPTION
**Pull request by jim-minter**

### CODE REVIEW

**Comment by jim-minter** [comment]
I've never done this before so can someone review? @stevekuznetsov @kargakis @pweil- ?

**Comment by kargakis** [comment]
You can remove the plugins.yaml changes, they already apply to all
openshift repos.

Make sure openshift-ci-robot and openshift-merge-robot are added as
collaborators in the repo.

**Comment by pweil-** [comment]
> Make sure openshift-ci-robot and openshift-merge-robot are added as
> collaborators in the repo.

the robot team has been added

**Comment by jim-minter** [comment]
@kargakis updated here thanks

**Pull request merged**
