### PR TITLE
add release-v1.2.x branch for kie-cloud-operator

### PR DESCRIPTION
**Pull request by tchughesiv**
Signed-off-by: tchughesiv <tchughesiv@gmail.com>

### CODE REVIEW

**Comment by droslean** [comment]
Can you try to recreate the jobs with the latest `ci-operator-prowgen` ?

**Comment by tchughesiv** [comment]
@droslean done, thanks

**Comment by tchughesiv** [comment]
@droslean is this cleared to be merged now?

**Pull request merged**
