### PR TITLE
Revert "Revert "ci-operator/step-registry/manifests: Factor day-2 manifests into own step""

### PR DESCRIPTION
**Pull request by wking**
Reverts openshift/release#10039

Hopefully the rehearsals will still show whatever the issue was that motivated #10039...

### CODE REVIEW

**Comment by petr-muller** [comment]
They do:
```
time="2020-07-03T03:47:23Z" level=error msg="Failed to get resolved config for test" error="failed resolve ReleaseBuildConfiguration: Failed resolve MultiStageTestConfiguration: e2e-aws: duplicate name: manifests" org=openshift repo=release 
```

https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/10053/pull-ci-openshift-release-master-pj-rehearse/1278897784635789312#1:build-log.txt%3A61

Not exactly sure what is the problem though :)

**Comment by bbguimaraes** [comment]
It was my mistake to approve your previous PR.  I blindly trusted the `ci-operator-registry` test, but for some reason we don't perform certain validations there.  `pj-rehearse` hits that code path, so it finds the problem: we are including `manifests` more than once in the `e2e-aws` test.

/hold

**Comment by wking** [comment]
An, possibly a workflow that includes the step twice (e.g. via two chains or something).

**Comment by wking** [comment]
Ok, `duplicate name: manifests` seems to be resolved now.

**Pull request closed without merging**
