### PR TITLE
agent: add AWS e2e test

### PR DESCRIPTION
**Pull request by andfasano**
Add AWS e2e test just to verify we're not introducing any regression during the development of the agent installer in the standard openshift installer

### CODE REVIEW

**Comment by zaneb** [comment]
Instead of just adding the one test we want to run by default, let's copy the _whole_ config but replace `skip_if_only_changed`/`run_if_changed` with `always_run: false` on everything except the e2e-aws test. That way we'll have to option to trigger any/all of the other tests to verify we haven't broken anything (but they won't run automatically on every PR).

**Comment by lranjbar** [comment]
> Instead of just adding the one test we want to run by default, let's copy the _whole_ config but replace `skip_if_only_changed`/`run_if_changed` with `always_run: false` on everything except the e2e-aws test. That way we'll have to option to trigger any/all of the other tests to verify we haven't broken anything (but they won't run automatically on every PR).

I don't agree with this approach. This will make more work in managing the CI configuration for a use case that would fall under the payload command probably.

**Comment by lranjbar** [comment]
JIRA tracking: AGENT-74

**Pull request merged**
