### PR TITLE
NO-ISSUE: Fix MicroShift's clusterbot image (root -> cli)

### PR DESCRIPTION
**Pull request by pmtk**

### CODE REVIEW

**Review by pacevedom — APPROVED** [review]
/lgtm

**Comment by pmtk** [comment]
/pj-rehearse periodic-ci-openshift-microshift-release-4.18-periodics-clusterbot-nightly pull-ci-openshift-microshift-main-e2e-aws-footprint-and-performance periodic-ci-openshift-microshift-release-4.14-ocp-conformance-nightly

**Review by pacevedom — COMMENTED** [review]
/lgtm

**Comment by pmtk** [comment]
/pj-rehearse periodic-ci-openshift-microshift-release-4.18-periodics-clusterbot-nightly pull-ci-openshift-microshift-main-e2e-aws-footprint-and-performance periodic-ci-openshift-microshift-release-4.14-ocp-conformance-nightly

**Comment by pmtk** [comment]
/pj-rehearse periodic-ci-openshift-microshift-release-4.18-periodics-clusterbot-nightly pull-ci-openshift-microshift-main-e2e-aws-footprint-and-performance periodic-ci-openshift-microshift-release-4.14-ocp-conformance-nightly

**Comment by pmtk** [comment]
/pj-rehearse periodic-ci-openshift-microshift-release-4.18-periodics-clusterbot-nightly pull-ci-openshift-microshift-main-e2e-aws-footprint-and-performance periodic-ci-openshift-microshift-release-4.14-ocp-conformance-nightly pull-ci-openshift-microshift-main-e2e-aws-tests-bootc

**Comment by pmtk** [comment]
/pj-rehearse periodic-ci-openshift-microshift-release-4.18-periodics-clusterbot-nightly pull-ci-openshift-microshift-main-e2e-aws-footprint-and-performance periodic-ci-openshift-microshift-release-4.14-ocp-conformance-nightly pull-ci-openshift-microshift-main-e2e-aws-tests-bootc

**Review by pacevedom — COMMENTED** [review]
/lgtm

**Pull request merged**
