### PR TITLE
METAL-991: metal3: add capi techpreview

### PR DESCRIPTION
**Pull request by honza**
Depends on

* https://github.com/openshift-metal3/dev-scripts/pull/1715
* https://github.com/openshift-metal3/dev-scripts/pull/1720

### CODE REVIEW

**Comment by hroyrh** [comment]
/testwith openshift/release/master/e2e-metal3-capi-techpreview openshift-metal3/dev-scripts#1720 openshift-metal3/dev-scripts#1715

**Comment by JoelSpeed** [comment]
/pj-rehearse pull-ci-openshift-cluster-capi-operator-main-e2e-metal3-capi-techpreview

Lets check things work before we merge them

**Comment by damdo** [comment]
@honza it looks like we are failing here: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/58839/rehearse-58839-pull-ci-openshift-cluster-capi-operator-main-e2e-metal3-capi-techpreview/1858631159420817408#1:build-log.txt%3A1040

**Comment by hroyrh** [comment]
/pj-rehearse pull-ci-openshift-cluster-capi-operator-main-e2e-metal3-capi-techpreview

**Review by damdo — COMMENTED** [review]
/approve

Thanks for adding this @honza

**Comment by damdo** [comment]
@honza  Make sure to add the rehearsals ack when you are happy

**Comment by honza** [comment]
Dependent PRs merged, let's try again

/pj-rehearse pull-ci-openshift-cluster-capi-operator-main-e2e-metal3-capi-techpreview

**Pull request merged**
