### PR TITLE
MGMT-15398: Pull multi-arch images from brew in AI arm job

### PR DESCRIPTION
**Pull request by adriengentil**
Pull assisted-installer, controller and agent multi-arch images from
brew.

### CODE REVIEW

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-day2-arm-workers
/cc @osherdp 

let's see :eyes:

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-day2-arm-workers

**Comment by osherdp** [comment]
I think ``target-namespace`` needs to be ``"test-credentials"``

**Comment by adriengentil** [comment]
> I think `target-namespace` needs to be `"test-credentials"`

I never know which namespace should be used :sweat_smile: 

/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-day2-arm-workers

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-day2-arm-workers

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-day2-arm-workers

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-day2-arm-workers

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-day2-arm-workers

**Comment by adriengentil** [comment]
@osherdp \o/

**Review by osherdp — APPROVED** [review]

**Pull request merged**
