### PR TITLE
Don't skip the sig-network tests

### PR DESCRIPTION
**Pull request by vpickard**
Enable the test for debugging.

Signed-off-by: vpickard <vpickard@redhat.com>

### CODE REVIEW

**Comment by wking** [comment]
I repaired the proxy infra again last night.

/retest

**Comment by vpickard** [comment]
The test is still failing. My tests on local cluster are not the same as in the CI job (passed in local cluster). Hold off merging until a fix is ready for CI.

**Comment by vpickard** [comment]
The failing test is from k8s E2E test suite. It is my understanding that this test suite is not expected to consume AWS proxy settings, so we will leave this test in the skip list.

For reference, the BZ associated with this is:
https://bugzilla.redhat.com/show_bug.cgi?id=1882845

**Pull request closed without merging**
