### PR TITLE
 4.16 expansion servicemesh

### PR DESCRIPTION
**Pull request by shakyav**

### CODE REVIEW

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-maistra-maistra-test-tool-main-servicemesh-hypershift-4.16-lp-rosa-hypershift-servicemesh-aws-rosa-hypershift

**Comment by mkralik3** [comment]
@shakyav please, wait with this PR till this https://github.com/openshift/release/pull/55340  is merged

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-maistra-maistra-test-tool-main-servicemesh-hypershift-4.16-lp-rosa-hypershift-servicemesh-aws-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-maistra-maistra-test-tool-main-servicemesh-hypershift-4.16-lp-rosa-hypershift-servicemesh-aws-rosa-hypershift

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
