### PR TITLE
MGMT-19366: Add periodic jobs to test 4 control plane nodes installation for ZTP / RESTful API

### PR DESCRIPTION
**Pull request by danmanor**

### CODE REVIEW

**Comment by danmanor** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-4-control-planes-periodic periodic-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-4masters-periodic

**Review by gamli75 — APPROVED** [review]

**Pull request merged**
