### PR TITLE
Move baremetal 4.11 nightly jobs to build05

### PR DESCRIPTION
**Pull request by tdomnesc**
so they run on internal lab hardware

https://issues.redhat.com/browse/METAL-331

### CODE REVIEW

**Comment by dgoodwin** [comment]
What is your take on all the failed metal job rehersals? There's a variety of failures in there, no consistent pattern but it does look like these may not pass on the new hardware.

**Comment by tdomnesc** [comment]
> What is your take on all the failed metal job rehersals? There's a variety of failures in there, no consistent pattern but it does look like these may not pass on the new hardware.

I have retested this over and over to compare to the current success rate, and it is identical. The failures are not because of the new hardware.

**Pull request merged**
