### PR TITLE
USHIFT-966 USHIFT-973: microshift e2e test suite

### PR DESCRIPTION
**Pull request by pmtk**

### CODE REVIEW

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift-tests pull-ci-openshift-microshift-main-e2e-microshift-tests-arm

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift-tests

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift-tests

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift-tests

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift-tests

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift-tests

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift-tests

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift-tests

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift-tests

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift-tests

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift-tests

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift-tests

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift-tests

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift-tests

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift-tests-arm

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift-tests pull-ci-openshift-microshift-main-e2e-microshift-tests-arm

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift-tests pull-ci-openshift-microshift-main-e2e-microshift-tests-arm

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift-tests pull-ci-openshift-microshift-main-e2e-microshift-tests-arm

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift-tests pull-ci-openshift-microshift-main-e2e-microshift-tests-arm

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift-tests pull-ci-openshift-microshift-main-e2e-microshift-tests-arm

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift-tests pull-ci-openshift-microshift-main-e2e-microshift-tests-arm

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift-tests pull-ci-openshift-microshift-main-e2e-microshift-tests-arm

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift-tests pull-ci-openshift-microshift-main-e2e-microshift-tests-arm

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift-tests pull-ci-openshift-microshift-main-e2e-microshift-tests-arm

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift-tests pull-ci-openshift-microshift-main-e2e-microshift-tests-arm

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift-tests pull-ci-openshift-microshift-main-e2e-microshift-tests-arm

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift-tests pull-ci-openshift-microshift-main-e2e-microshift-tests-arm pull-ci-openshift-microshift-release-4.14-e2e-openshift-conformance-reduced pull-ci-openshift-microshift-release-4.14-e2e-openshift-conformance-reduced-arm pull-ci-openshift-microshift-release-4.13-e2e-loadbalancer-smoke-test pull-ci-openshift-microshift-release-4.13-e2e-loadbalancer-smoke-test-arm pull-ci-openshift-microshift-release-4.13-e2e-greenboot pull-ci-openshift-microshift-release-4.13-e2e-greenboot-arm pull-ci-openshift-microshift-release-4.12-e2e-openshift-conformance-reduced pull-ci-openshift-microshift-release-4.12-e2e-router-smoke-test

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-microshift pull-ci-openshift-microshift-main-e2e-microshift-arm pull-ci-openshift-microshift-release-4.14-e2e-openshift-conformance-reduced pull-ci-openshift-microshift-release-4.14-e2e-openshift-conformance-reduced-arm pull-ci-openshift-microshift-release-4.13-e2e-loadbalancer-smoke-test pull-ci-openshift-microshift-release-4.13-e2e-loadbalancer-smoke-test-arm pull-ci-openshift-microshift-release-4.13-e2e-greenboot pull-ci-openshift-microshift-release-4.13-e2e-greenboot-arm pull-ci-openshift-microshift-release-4.12-e2e-openshift-conformance-reduced pull-ci-openshift-microshift-release-4.12-e2e-router-smoke-test

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-e2e pull-ci-openshift-microshift-main-microshift-e2e-arm

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-e2e pull-ci-openshift-microshift-release-4.12-e2e-router-smoke-test pull-ci-openshift-microshift-release-4.13-e2e-router-smoke-test

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-e2e pull-ci-openshift-microshift-release-4.12-e2e-router-smoke-test pull-ci-openshift-microshift-release-4.13-e2e-router-smoke-test

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-e2e pull-ci-openshift-microshift-release-4.12-e2e-router-smoke-test pull-ci-openshift-microshift-release-4.13-e2e-router-smoke-test

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-e2e

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-openshift-conformance-reduced

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-e2e-arm pull-ci-openshift-microshift-release-4.14-microshift-e2e pull-ci-openshift-microshift-release-4.14-microshift-e2e-arm pull-ci-openshift-microshift-release-4.14-e2e-openshift-conformance-reduced pull-ci-openshift-microshift-release-4.14-e2e-openshift-conformance-reduced-arm pull-ci-openshift-microshift-release-4.14-images pull-ci-openshift-microshift-release-4.14-test-srpm pull-ci-openshift-microshift-release-4.14-test-unit pull-ci-openshift-microshift-release-4.14-verify pull-ci-openshift-microshift-release-4.12-e2e-openshift-conformance-reduced pull-ci-openshift-microshift-release-4.12-e2e-reboot pull-ci-openshift-microshift-release-4.12-e2e-router-smoke-test pull-ci-openshift-microshift-release-4.12-images pull-ci-openshift-microshift-release-4.12-test-srpm pull-ci-openshift-microshift-release-4.12-test-unit pull-ci-openshift-microshift-release-4.12-verify pull-ci-openshift-microshift-release-4.13-e2e-greenboot pull-ci-openshift-microshift-release-4.13-e2e-greenboot-arm pull-ci-openshift-microshift-release-4.13-e2e-loadbalancer-smoke-test pull-ci-openshift-microshift-release-4.13-e2e-loadbalancer-smoke-test-arm pull-ci-openshift-microshift-release-4.13-e2e-openshift-conformance-reduced pull-ci-openshift-microshift-release-4.13-e2e-openshift-conformance-reduced-arm pull-ci-openshift-microshift-release-4.13-e2e-reboot pull-ci-openshift-microshift-release-4.13-e2e-reboot-arm pull-ci-openshift-microshift-release-4.13-e2e-router-smoke-test pull-ci-openshift-microshift-release-4.13-e2e-router-smoke-test-arm pull-ci-openshift-microshift-release-4.13-images pull-ci-openshift-microshift-release-4.13-test-srpm pull-ci-openshift-microshift-release-4.13-test-unit pull-ci-openshift-microshift-release-4.13-verify pull-ci-openshift-microshift-main-e2e-openshift-conformance-reduced pull-ci-openshift-microshift-main-e2e-openshift-conformance-reduced-arm periodic-ci-openshift-microshift-release-4.13-rebase-on-nightlies periodic-ci-openshift-microshift-main-rebase-on-nightlies periodic-ci-openshift-microshift-release-4.12-rebase-on-nightlies

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-e2e pull-ci-openshift-microshift-release-4.14-microshift-e2e pull-ci-openshift-microshift-release-4.14-e2e-openshift-conformance-reduced pull-ci-openshift-microshift-release-4.14-images pull-ci-openshift-microshift-release-4.14-test-srpm pull-ci-openshift-microshift-release-4.14-test-unit pull-ci-openshift-microshift-release-4.14-verify pull-ci-openshift-microshift-release-4.12-e2e-openshift-conformance-reduced pull-ci-openshift-microshift-release-4.12-e2e-reboot pull-ci-openshift-microshift-release-4.12-e2e-router-smoke-test pull-ci-openshift-microshift-release-4.12-images pull-ci-openshift-microshift-release-4.12-test-srpm pull-ci-openshift-microshift-release-4.12-test-unit pull-ci-openshift-microshift-release-4.12-verify pull-ci-openshift-microshift-release-4.13-e2e-loadbalancer-smoke-test-arm pull-ci-openshift-microshift-release-4.13-e2e-openshift-conformance-reduced pull-ci-openshift-microshift-release-4.13-e2e-reboot pull-ci-openshift-microshift-release-4.13-e2e-router-smoke-test-arm pull-ci-openshift-microshift-release-4.13-images pull-ci-openshift-microshift-release-4.13-test-srpm pull-ci-openshift-microshift-release-4.13-test-unit pull-ci-openshift-microshift-release-4.13-verify pull-ci-openshift-microshift-main-e2e-openshift-conformance-reduced pull-ci-openshift-microshift-main-e2e-openshift-conformance-reduced-arm

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.13-e2e-reboot pull-ci-openshift-microshift-release-4.12-e2e-reboot pull-ci-openshift-microshift-main-e2e-openshift-conformance-reduced

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.13-e2e-reboot pull-ci-openshift-microshift-release-4.12-e2e-reboot

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.13-e2e-reboot pull-ci-openshift-microshift-release-4.12-e2e-reboot pull-ci-openshift-microshift-main-microshift-e2e

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.13-e2e-reboot pull-ci-openshift-microshift-release-4.12-e2e-reboot pull-ci-openshift-microshift-main-microshift-e2e

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.13-e2e-reboot pull-ci-openshift-microshift-release-4.12-e2e-reboot pull-ci-openshift-microshift-main-microshift-e2e

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.12-e2e-reboot

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.12-e2e-reboot

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.13-e2e-reboot

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.13-e2e-reboot pull-ci-openshift-microshift-release-4.12-e2e-reboot

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.12-e2e-reboot

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-e2e pull-ci-openshift-microshift-release-4.14-microshift-e2e pull-ci-openshift-microshift-release-4.14-e2e-openshift-conformance-reduced pull-ci-openshift-microshift-release-4.14-images pull-ci-openshift-microshift-release-4.14-test-srpm pull-ci-openshift-microshift-release-4.14-test-unit pull-ci-openshift-microshift-release-4.14-verify pull-ci-openshift-microshift-release-4.12-e2e-openshift-conformance-reduced pull-ci-openshift-microshift-release-4.12-e2e-reboot pull-ci-openshift-microshift-release-4.12-e2e-router-smoke-test pull-ci-openshift-microshift-release-4.12-images pull-ci-openshift-microshift-release-4.12-test-srpm pull-ci-openshift-microshift-release-4.12-test-unit pull-ci-openshift-microshift-release-4.12-verify pull-ci-openshift-microshift-release-4.13-e2e-loadbalancer-smoke-test-arm pull-ci-openshift-microshift-release-4.13-e2e-openshift-conformance-reduced pull-ci-openshift-microshift-release-4.13-e2e-reboot pull-ci-openshift-microshift-release-4.13-e2e-router-smoke-test-arm pull-ci-openshift-microshift-release-4.13-images pull-ci-openshift-microshift-release-4.13-test-srpm pull-ci-openshift-microshift-release-4.13-test-unit pull-ci-openshift-microshift-release-4.13-verify pull-ci-openshift-microshift-main-e2e-openshift-conformance-reduced pull-ci-openshift-microshift-main-e2e-openshift-conformance-reduced-arm

**Review by pacevedom — APPROVED** [review]
/lgtm

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-e2e pull-ci-openshift-microshift-release-4.14-microshift-e2e pull-ci-openshift-microshift-release-4.14-e2e-openshift-conformance-reduced pull-ci-openshift-microshift-release-4.14-images pull-ci-openshift-microshift-release-4.14-test-srpm pull-ci-openshift-microshift-release-4.14-test-unit pull-ci-openshift-microshift-release-4.14-verify pull-ci-openshift-microshift-release-4.12-e2e-openshift-conformance-reduced pull-ci-openshift-microshift-release-4.12-e2e-reboot pull-ci-openshift-microshift-release-4.12-e2e-router-smoke-test pull-ci-openshift-microshift-release-4.12-images pull-ci-openshift-microshift-release-4.12-test-srpm pull-ci-openshift-microshift-release-4.12-test-unit pull-ci-openshift-microshift-release-4.12-verify pull-ci-openshift-microshift-release-4.13-e2e-loadbalancer-smoke-test-arm pull-ci-openshift-microshift-release-4.13-e2e-openshift-conformance-reduced pull-ci-openshift-microshift-release-4.13-e2e-reboot pull-ci-openshift-microshift-release-4.13-e2e-router-smoke-test-arm pull-ci-openshift-microshift-release-4.13-images pull-ci-openshift-microshift-release-4.13-test-srpm pull-ci-openshift-microshift-release-4.13-test-unit pull-ci-openshift-microshift-release-4.13-verify pull-ci-openshift-microshift-main-e2e-openshift-conformance-reduced pull-ci-openshift-microshift-main-e2e-openshift-conformance-reduced-arm

**Review by pacevedom — APPROVED** [review]
/lgtm

**Pull request merged**
