### PR TITLE
fix azure jobs for crun and cgroups v1

### PR DESCRIPTION
**Pull request by harche**
Fix azure installation issues for crun and cgroups v1 jobs.

### CODE REVIEW

**Comment by harche** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-azure-ovn-crun	
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-azure-ovn-cgroupsv1

**Comment by harche** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-azure-ovn-cgroupsv1

**Comment by harche** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-azure-ovn-cgroupsv1

**Comment by harche** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-azure-ovn-crun

**Comment by DennisPeriquet** [comment]
The last rehearse passed.  Add the `pj-rehearse ack` when you're ready to merge.

**Comment by harche** [comment]
All the jobs were configured correctly with their respective configuration of crun and cgroups v1. 

/pj-rehearse ack

**Pull request merged**
