### PR TITLE
Add e2e tests for 4.14

### PR DESCRIPTION
**Pull request by liangxia**

### CODE REVIEW

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-azure-upi-p3-f28

**Comment by liangxia** [comment]
Verified it pick up the correct payload,
```
INFO[2023-03-09T06:24:23Z] Resolved release arm64-latest to registry.ci.openshift.org/ocp-arm64/release-arm64:4.14.0-0.nightly-arm64-2023-02-27-084418
INFO[2023-03-09T06:24:23Z] Resolved release latest to registry.ci.openshift.org/ocp/release:4.14.0-0.nightly-2023-03-07-225351 
```

/cc @jhou1 @JianLi-RH @dis016 @pruan-rht

**Comment by jhou1** [comment]
Thank you Liang
/lgtm

**Pull request merged**
