### PR TITLE
OSSM revert maistra workflow hypershift chain

### PR DESCRIPTION
**Pull request by yxun**

### CODE REVIEW

**Comment by yxun** [comment]
/pj-rehearse periodic-ci-maistra-istio-operator-maistra-3.0-nightly-images-3-0

**Comment by yxun** [comment]
/pj-rehearse periodic-ci-maistra-istio-operator-maistra-3.0-nightly-images-3-0

**Comment by yxun** [comment]
/pj-rehearse periodic-ci-maistra-istio-operator-maistra-3.0-nightly-images-3-0

**Comment by yxun** [comment]
/pj-rehearse periodic-ci-maistra-istio-operator-maistra-3.0-nightly-images-3-0

**Comment by yxun** [comment]
/pj-rehearse periodic-ci-maistra-istio-operator-maistra-3.0-nightly-images-3-0

**Comment by yxun** [comment]
/pj-rehearse periodic-ci-maistra-istio-operator-maistra-3.0-nightly-images-3-0

**Comment by yxun** [comment]
/pj-rehearse periodic-ci-maistra-istio-operator-maistra-3.0-nightly-images-3-0

**Comment by yxun** [comment]
/pj-rehearse periodic-ci-maistra-istio-operator-maistra-3.0-nightly-images-3-0

**Comment by jwendell** [comment]
/pj-rehearse periodic-ci-maistra-istio-maistra-3.0-nightly-images-3-0

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-3.0-integ-pilot-3-0

**Comment by jwendell** [comment]
/pj-rehearse periodic-ci-maistra-istio-maistra-3.0-nightly-images-3-0

**Review by jwendell — APPROVED** [review]

**Pull request merged**
