### PR TITLE
calico: port 4.7 periodics to workflows

### PR DESCRIPTION
**Pull request by vrutkovs**
Follow-up for https://github.com/openshift/release/pull/18367

### CODE REVIEW

**Comment by vrutkovs** [comment]
```
{
            s: "query failed: ALERTS{alertname!~\"Watchdog|AlertmanagerReceiversNotConfigured|PrometheusRemoteWriteDesiredShards\",alertstate=\"firing\",severity!=\"info\"} >= 1: promQL query: ALERTS{alertname!~\"Watchdog|AlertmanagerReceiversNotConfigured|PrometheusRemoteWriteDesiredShards\",alertstate=\"firing\",severity!=\"info\"} >= 1 had reported incorrect results:\n[{\"metric\":{\"__name__\":\"ALERTS\",\"alertname\":\"TargetDown\",\"alertstate\":\"firing\",\"job\":\"kube-proxy\",\"namespace\":\"openshift-kube-proxy\",\"service\":\"openshift-kube-proxy\",\"severity\":\"warning\"},\"value\":[1621587779.952,\"1\"]}]",
        },
```
might be a flake

/retest

**Comment by jluhrsen** [comment]
comparing the [rehearsal](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/18745/rehearse-18745-periodic-ci-openshift-release-master-ci-4.7-e2e-aws-calico/1395683241075150848) with the current job in [testgrid](https://testgrid.k8s.io/redhat-openshift-ocp-release-4.7-informing#release-openshift-origin-installer-e2e-aws-calico-4.7) it seems a few more test cases failed than what seems normal. just double checking if they are consistent or not.

**Comment by vrutkovs** [comment]
Closed in favor of #18745

**Pull request closed without merging**
