### PR TITLE
ci-operator/platform-balance/step-jobs-by-platform: Cluster API providers are platform specific

### PR DESCRIPTION
**Pull request by wking**
Add all of `openshift/cluster-api-provider-*`.

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@wking can you put this script into a subdir and make yourself owner of that?

**Comment by wking** [comment]
sure.  I'd still have to flag someone down for a LGTM, though.  Will file a separate PR.

**Comment by wking** [comment]
Rebased around #11380 with 8ebdc1a320 -> 3b5bc23c7f.

**Pull request merged**
