### PR TITLE
telco5g: Add CNF Baremetal tests job for 4.15 release branch

### PR DESCRIPTION
**Pull request by sshnaidm**
[CNF-11277](https://issues.redhat.com//browse/CNF-11277)

### CODE REVIEW

**Comment by yanirq** [comment]
/pj-rehearse pull-ci-openshift-cluster-node-tuning-operator-release-4.15-e2e-telco5g-cnftests

**Comment by yanirq** [comment]
fix for currently failed test:  https://github.com/openshift/cluster-node-tuning-operator/pull/934

**Comment by sshnaidm** [comment]
@yanirq failing test shouldn't block this job, it's not mandatory and runs on demand

**Pull request merged**
