### PR TITLE
OCM-7094: remove gcp-ocm-osd-ccs tests from 4.13 nightly

### PR DESCRIPTION
**Pull request by jianli-wei**
Remove the tests from 4.13 nightly, according to below error and [the Slack discussion](https://redhat-internal.slack.com/archives/CHWDU0CP9/p1711686472942139).

```
$ ocm version
0.1.72
$ jq -r .client_email /home/fedora/.gcp/osd-ccs-gcp.json
osd-ccs-admin@openshift-qe-group-i-osd.iam.gserviceaccount.com
$ ocm create cluster ci-osd-gcp-10uk --ccs --provider=gcp --region us-central1 --service-account-file /home/fedora/.gcp/osd-ccs-gcp.json --version 4.13.0-0.nightly-2024-03-28-195129-nightly --channel-group nightly --compute-machine-type custom-4-16384 --subscription-type standard --etcd-encryption --secure-boot-for-shielded-vms
Error: Failed to create cluster: unable to create cluster: status is 400, identifier is '400', code is 'CLUSTERS-MGMT-400' and operation identifier is 'eef7fc27-6f40-46f5-beb0-d17619fcba32': SecureBoot for GCP clusters is only supported in version '4.13.0' or greater, current cluster version is '4.13.0-0.nightly-2024-03-28-195129'
$

### CODE REVIEW

**Comment by jianli-wei** [comment]
@yasun1 @xueli181114 please advise whether we need to remove the 4.13 nightly tests, thanks!

**Comment by yasun1** [comment]
@jianli-wei Please do it. We do not know whether it will be fixed or how long it could be fixed. It is meaningless to add a failure job on a less-attention version.

**Comment by jianli-wei** [comment]
FYI the current related tests in 4.13 stable: 
```
$ grep -E "as: gcp-ocm" ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-stable.yaml
- as: gcp-ocm-osd-ccs-marketplace-f14
- as: gcp-ocm-osd-ccs-xpn-f14
$

**Comment by jianli-wei** [comment]
@rioliu-rh please help review, thanks!

**Comment by jianlinliu** [comment]
cc @liangxia

**Pull request merged**
