### PR TITLE
Migrate custom test image template jobs to multi-stage

### PR DESCRIPTION
**Pull request by petr-muller**
Announced on aos-devel on Friday.

Please find more details here: https://docs.ci.openshift.org/docs/how-tos/migrating-template-jobs-to-multistage/#openshift_installer_custom_test_image

### CODE REVIEW

**Comment by petr-muller** [comment]
/hold

We'll want to announce this on aos-devel

**Comment by petr-muller** [comment]
Huh some of the rehearsal failures look really infra-y

- `could not run steps: step e2e-aws-operator failed: failed to create secret: secrets "e2e-aws-operator" already exists` ([link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/13848/rehearse-13848-pull-ci-openshift-cluster-api-provider-aws-release-4.1-e2e-aws-operator/1331253067768664064#1:build-log.txt%3A42))
- `Failed to get build src: etcdserver: request timed out` ([link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/13848/rehearse-13848-pull-ci-operator-framework-operator-marketplace-release-4.4-e2e-aws-console-olm/1331253081299488768#1:build-log.txt%3A26))

**Comment by petr-muller** [comment]
Also a build failure that looks very much like a bug

```
 error: build error: Failed to push image: error copying layers and metadata from "containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.imagestore=/var/lib/shared]image-registry.openshift-image-registry.svc:5000/ci-op-qtin03n1/pipeline:operator-marketplace" to "docker://image-registry.openshift-image-registry.svc:5000/ci-op-qtin03n1/pipeline:operator-marketplace": Error trying to reuse blob sha256:fc5b206e9329a1674dd9e8efbee45c9be28d0d0dcbabba3c6bb67a2f22cfcf2a at destination: failed to read from destination repository ci-op-qtin03n1/pipeline: 400 (Bad Request) 
```

**Comment by petr-muller** [comment]
Also: `cat: /tmp/artifacts/installer/auth/kubeadmin-password: No such file or directory` well hello, long time no see

**Comment by alvaroaleman** [comment]
> Also: cat: /tmp/artifacts/installer/auth/kubeadmin-password: No such file or directory well hello, long time no see

I believe the backports for this are still waiting for cherry-pick approval

**Comment by alanconway** [comment]
/uncc @alanconway 
Not familiar with this process.

**Comment by petr-muller** [comment]
@alvaroaleman these are different, seems like console tests for OLM:

- pull-ci-operator-framework-operator-marketplace-master-okd-e2e-aws-console-olm
- pull-ci-operator-framework-operator-marketplace-release-4.6-okd-e2e-aws-console-olm 

I will leave these out of the migration for now

**Comment by petr-muller** [comment]
`hack/e2e.sh: line 15: openshift-tests: command not found`  in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/13848/rehearse-13848-pull-ci-openshift-aws-ebs-csi-driver-operator-release-4.8-e2e-operator/1331589612614717440

Nice. I'll leave this one out for now too, but I guess I will monitor https://search.ci.openshift.org/?search=openshift-tests%3A+command+not+found&maxAge=48h&context=1&type=bug%2Bjunit&name=&maxMatches=5&maxBytes=20971520&groupBy=job after the merge

**Pull request merged**
