### PR TITLE
bump olmv1 components to go 1.20

### PR DESCRIPTION
**Pull request by joelanford**
Bump builder images to use go 1.20

### CODE REVIEW

**Review by ncdc — APPROVED** [review]

**Comment by joelanford** [comment]
/pj-rehearse pull-ci-openshift-operator-framework-rukpak-release-4.14-e2e pull-ci-openshift-operator-framework-operator-controller-main-images pull-ci-openshift-operator-framework-operator-controller-main-unit

**Comment by joelanford** [comment]
/hold
Looking into rukpak e2e rehearsal failure

**Comment by joelanford** [comment]
/hold cancel
reverted rukpak changes from this PR due to https://github.com/openshift/release/pull/40544#issuecomment-1601609250

**Comment by joelanford** [comment]
/pj-rehearse pull-ci-openshift-operator-framework-rukpak-release-4.14-e2e pull-ci-openshift-operator-framework-operator-controller-main-images pull-ci-openshift-operator-framework-operator-controller-main-unit pull-ci-openshift-operator-framework-catalogd-main-images pull-ci-openshift-operator-framework-catalogd-main-unit

**Pull request merged**
