### PR TITLE
enable release note and require label plugins for shipwright-io/cli

### PR DESCRIPTION
**Pull request by gabemontero**
/assign @adambkaplan 

@sbose78 @imjasonh fyi

### CODE REVIEW

**Comment by sbose78** [comment]
👍

**Comment by gabemontero** [comment]
ok e2e's all green

before I reach out to the test platform guys to approve, any reason you do *NOT* want to do this @adambkaplan ?

thanks

**Comment by gabemontero** [comment]
also, 

/hold

we should merge the PR template via https://github.com/shipwright-io/cli/pull/16 before merging this

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Comment by adambkaplan** [comment]
/hold cancel

Corresponding cli PR has merged

**Pull request merged**
