### PR TITLE
pin pip to less than 21, which dropped support for python2

### PR DESCRIPTION
**Pull request by fabianvf**
Changelog for pip 21: https://pip.pypa.io/en/stable/news/#id1
Example failing job: https://prow.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-ocp-installer-e2e-aws-upi-4.7/1353763437741608960

This is just a temporary solve, we should migrate from python2->3 in our scripts considering that it's been EOLed since last year.

### CODE REVIEW

**Comment by jcpowermac** [comment]
Uhh, how did that get in there...

```
100  887M  100  887M    0     0  16.5M      0  0:00:53  0:00:53 --:--:-- 18.1M
govc: Post https://vcsa-ci.vmware.devcluster.openshift.com/sdk: dial tcp 139.178.70.10:443: i/o timeout
```

**Review by petr-muller — APPROVED** [review]

**Comment by petr-muller** [comment]
/hold

If rehearsals are relevant

**Comment by fabianvf** [comment]
@petr-muller I don't believe the failures are related, the aws-upi job got to this point https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/15226/rehearse-15226-pull-ci-openshift-installer-master-e2e-aws-upi/1356988642098155520#1:build-log.txt%3A124, after that it's past these changes (it used to fail with invalid syntax as in this job: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-ocp-installer-e2e-aws-upi-4.7/1356853928188186624). The other jobs are harder to piece the logs together from, but since the pip installation is used to get the `awscli` tool and then do all the infra components, I think any job that was on aws and got past setup is unaffected.

The GCP jobs literally don't run this code so they're just broken for unrelated reasons.

Going through the failures 1 by 1:
- ci/rehearse/openshift/cluster-api-actuator-pkg/master/e2e-vsphere-operator: Cluster is up, fails on machine suite. Well past the changes here
- ci/rehearse/openshift/cluster-etcd-operator/master/e2e-disruptive: Cluster is up, fails a bunch of random tests. Also well past these changes
- ci/rehearse/openshift/cluster-image-registry-operator/release-4.5/e2e-vsphere-operator: This job is broken on setup, but completely unrelated (confirmed with vsphere-ci folks)
- ci/rehearse/openshift/installer/master/e2e-aws-upi: This one is failing after the changes from this PR, and in fact is getting further than it did prior to this PR.
- ci/rehearse/openshift/installer/release-4.3/e2e-gcp-upi: The code doesn't even run on this job (it's behind a conditional for aws platform), and it gets past the changes regardless.
- ci/rehearse/openshift/machine-api-operator/master/e2e-vsphere-serial: Cluster is up, fails on some etcd tests. Well past the changes here

**Comment by petr-muller** [comment]
@fabianvf sure, I only held so that they can be reviewed if needed. Rehearsals do not block so the PR would merge after my approval, and I wasn't sure if anyone wants to inspect the results or not. Sounds like this PR can be merged then.

/hold cancel

**Pull request merged**
