### PR TITLE
AWS auto case - byo IAM role

### PR DESCRIPTION
**Pull request by yunjiang29**
OCP-40931	[ipi-on-aws] Create cluster by using existing IAM roles (master only)
OCP-40932	[ipi-on-aws] Create cluster by using existing IAM roles (worker only)

New jobs:
*  `periodic-ci-openshift-verification-tests-master-installation-nightly-4.17-aws-ipi-byo-iam-role-master-arm-f28`
* `periodic-ci-openshift-verification-tests-master-installation-nightly-4.17-aws-ipi-byo-iam-role-worker-arm-f28`
* `periodic-ci-openshift-verification-tests-master-installation-nightly-4.18-aws-ipi-byo-iam-role-master-arm-f28`
* `periodic-ci-openshift-verification-tests-master-installation-nightly-4.18-aws-ipi-byo-iam-role-worker-arm-f28`

### CODE REVIEW

**Comment by yunjiang29** [comment]
jobs to be tested:

```
periodic-ci-openshift-verification-tests-master-installation-nightly-4.18-aws-ipi-byo-iam-role-master-arm-f28
periodic-ci-openshift-verification-tests-master-installation-nightly-4.18-aws-ipi-byo-iam-role-worker-arm-f28
periodic-ci-openshift-openshift-tests-private-release-4.18-multi-nightly-aws-ipi-byo-iam-role-efs-fips-amd-f28-destructive
periodic-ci-openshift-openshift-tests-private-release-4.15-multi-nightly-aws-ipi-byo-iam-role-efs-arm-f14
```

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.18-aws-ipi-byo-iam-role-master-arm-f28

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.18-aws-ipi-byo-iam-role-worker-arm-f28

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-multi-nightly-aws-ipi-byo-iam-role-efs-fips-amd-f28-destructive

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-multi-nightly-aws-ipi-byo-iam-role-efs-arm-f14

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.18-aws-ipi-byo-iam-role-master-arm-f28

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.18-aws-ipi-byo-iam-role-worker-arm-f28

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-multi-nightly-aws-ipi-byo-iam-role-efs-fips-amd-f28-destructive

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-multi-nightly-aws-ipi-byo-iam-role-efs-arm-f14

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.18-aws-ipi-byo-iam-role-master-arm-f28

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.18-aws-ipi-byo-iam-role-worker-arm-f28

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-multi-nightly-aws-ipi-byo-iam-role-efs-fips-amd-f28-destructive

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-multi-nightly-aws-ipi-byo-iam-role-efs-arm-f14

**Comment by yunjiang29** [comment]
@jianlinliu PTAL

**Comment by jianlinliu** [comment]
cc @liangxia for approval.

**Pull request merged**
