### PR TITLE
feat: add win2k22 test lane for tekton task operator

### PR DESCRIPTION
**Pull request by ksimon1**
feat: add win2k22 test lane for tekton task operator
this commit adds new test lane which checks win2k22 example pipeline in kubevirt tekton tasks operator

Signed-off-by: Karel Šimon <ksimon@redhat.com>

### CODE REVIEW

**Review by 0xFelix — APPROVED** [review]
/lgtm

**Comment by ksimon1** [comment]
/hold cancel
I will fix the failing test in tto repo

**Pull request merged**
