### PR TITLE
Changes for insights-operator-tests 4.13

### PR DESCRIPTION
**Pull request by JoaoFula**

### CODE REVIEW

**Comment by danilo-gemoli** [comment]
@JoaoFula `quay.io/redhatqe/insights-operator-tests:4.13` doesn't actually exist, therefore the mirroring job is failing right now. Are you guys planning to push it any time soon?

**Comment by JoaoFula** [comment]
@danilo-gemoli Hi, thanks for the info! It should've been created already so definitely something I need to look into. Hopefully will be resolved by the end of today. Will update here

**Comment by JoaoFula** [comment]
quay.io/redhatqe/insights-operator-tests:4.13 is now available. I apologize for any inconvenience and thank you once again.

**Pull request merged**
