### PR TITLE
RHTAPBUGS-983 Remove jira-lifecycle-plugin from appstudio jobs

### PR DESCRIPTION
**Pull request by jkopriva**

### CODE REVIEW

**Comment by jkopriva** [comment]
@johnmcollier @mmorhun @skabashnyuk Hi, can you please look at this? I want to remove the jira-lifecycle-plugin - this plugin is for OCPBUGS only, the integration between Jira and GitHub is handled by jira, which I leave as it is. Thank you!

**Review by mmorhun — APPROVED** [review]

**Review by lkolacek — APPROVED** [review]
LGTM +1 let's kill it :)

**Review by johnmcollier — APPROVED** [review]
/lgtm
/approve

**Comment by mmorhun** [comment]
@jannfis @jgwest @wtam2018 could someone review the PR?

**Pull request merged**
