### PR TITLE
NO-ISSUE: OCPBUGS-37716 testing ovn assisted

### PR DESCRIPTION
**Pull request by eifrach**
- Increasing Nutanix image size

### CODE REVIEW

**Comment by eifrach** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-ovn-single-node-csi

**Comment by eifrach** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-assisted

**Comment by eifrach** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-assisted

**Review by gamli75 — APPROVED** [review]

**Pull request merged**
