### PR TITLE
Add HyperShift jobs for testing Distributed Tracing and build Target Allocator image in jobs.

### PR DESCRIPTION
**Pull request by IshwarKanse**
Required by EPIC: https://issues.redhat.com/browse/TRACING-3172

This PR is to add HyperShift jobs for testing Distributed Tracing on a weekly periodic run. 

Also fix Target Allocator cases by building and setting the image in the Prow CI jobs.

EPIC https://issues.redhat.com/browse/TRACING-3357

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-ocp4.13-hypershift-tempo-e2e-tests

**Comment by frzifus** [comment]
@IshwarKanse that may no longer works:
https://github.com/open-telemetry/community/issues/1591

**Comment by IshwarKanse** [comment]
@frzifus Yes for OTEL, we will need to do the same thing we did for Tempo and fork the repo in OpenShift github org.

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-ocp4.13-hypershift-tempo-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-ocp4.13-hypershift-tempo-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-ocp4.13-hypershift-tempo-e2e-tests

**Comment by IshwarKanse** [comment]
The HyperShift jobs are working, here's one rehersal run https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/41212/rehearse-41212-periodic-ci-openshift-grafana-tempo-operator-main-ocp4.13-hypershift-tempo-e2e-tests/1679458246554816512 Will add the reporter config to report the job status to our Slack channel and we'll need to check how to get this merged as the github automation is now failing due to the bots access have been revoked from the OpenTelemetry operator repo.

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
OTEL rehersal run passed. https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/41212/rehearse-41212-pull-ci-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests/1680784112727625728

**Review by iblancasa — APPROVED** [review]

**Comment by IshwarKanse** [comment]
Closing this one out as I'll have to add this to our new location for opentelemetry-operator config.

**Pull request closed without merging**
