### PR TITLE
update images in 4.17+ for egress-router-cni jobs

### PR DESCRIPTION
**Pull request by jluhrsen**

### CODE REVIEW

**Comment by jluhrsen** [comment]
/pj-rehearse pull-ci-openshift-egress-router-cni-master-unit
/pj-rehearse pull-ci-openshift-egress-router-cni-master-verify
/pj-rehearse pull-ci-openshift-egress-router-cni-master-verify-deps
/pj-rehearse pull-ci-openshift-egress-router-cni-master-images

**Comment by jluhrsen** [comment]
/pj-rehearse pull-ci-openshift-egress-router-cni-master-verify

**Comment by jluhrsen** [comment]
/pj-rehearse pull-ci-openshift-egress-router-cni-master-verify-deps

**Comment by jluhrsen** [comment]
/pj-rehearse pull-ci-openshift-egress-router-cni-master-images

**Comment by jluhrsen** [comment]
/pj-rehearse pull-ci-openshift-egress-router-cni-master-verify pull-ci-openshift-egress-router-cni-master-verify-deps pull-ci-openshift-egress-router-cni-master-images

**Comment by jluhrsen** [comment]
/hold

something wrong [here](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/53255/rehearse-53255-pull-ci-openshift-egress-router-cni-master-images/1803118521719197696):
`step egress-router-cni is missing dependencies: "ocp_4.17_base-rhel9" is neither an imported nor a built image`

**Comment by jluhrsen** [comment]
/pj-rehearse pull-ci-openshift-egress-router-cni-master-verify pull-ci-openshift-egress-router-cni-master-verify-deps pull-ci-openshift-egress-router-cni-master-images

**Review by trozet — APPROVED** [review]
/lgtm

**Pull request merged**
