### PR TITLE
Updating the cron value for ocp4.16 config file

### PR DESCRIPTION
**Pull request by Sau1506mya**

### CODE REVIEW

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.16-cnv-odf-ocp4.16-lp-interop-cnv-odf-tests-aws-upi-ocp416

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.16-cnv-odf-ocp4.16-lp-interop-cnv-odf-tests-aws-upi-ocp416

**Review by ascerra — APPROVED** [review]

**Review by calebevans — APPROVED** [review]
/lgtm

**Review by dfrazzette — COMMENTED** [review]
/lgtm

**Review by rabin-io — COMMENTED** [review]
/lgtm

**Pull request merged**
