### PR TITLE
[rhd-sbo] Do not skip acceptance tests if the main Dockerfile is changed

### PR DESCRIPTION
**Pull request by pmacik**
Signed-off-by: Pavel Macík <pavel.macik@gmail.com>

Related to: https://github.com/redhat-developer/service-binding-operator/pull/1168

### CODE REVIEW

**Comment by baijum** [comment]
/lgtm
/hold

@pmacik Is there any order for merging PR and https://github.com/redhat-developer/service-binding-operator/pull/1168 ?

**Comment by pmacik** [comment]
> /lgtm /hold
> 
> @pmacik Is there any order for merging PR and [redhat-developer/service-binding-operator#1168](https://github.com/redhat-developer/service-binding-operator/pull/1168) ?

@baijum Not necessarily, thx

**Pull request merged**
