### PR TITLE
rhi operator

### PR DESCRIPTION
**Pull request by akoserwal**
Operator repo: https://github.com/redhat-integration/rhi-operator
The rhi-operator will be a downstream version of the operator integr8ly.

### CODE REVIEW

**Comment by akoserwal** [comment]
@cluster-bot

**Comment by akoserwal** [comment]
@bbguimaraes please can you take a look. This is ready to be merged

**Comment by bbguimaraes** [comment]
LGTM, but you need to remove the files under `cluster/`.

**Pull request merged**
