### PR TITLE
kubevirt: infra: Add CI for release-v0.1 branch of vm-console-proxy

### PR DESCRIPTION
**Pull request by akrejcir**

### CODE REVIEW

**Comment by akrejcir** [comment]
/pj-rehearse pull-ci-kubevirt-vm-console-proxy-release-v0.1-e2e-functests

**Comment by 0xFelix** [comment]
Can this run on plain Kubernetes too?

**Comment by akrejcir** [comment]
Currently it cannot. It uses an openshift annotation to create secrets with TLS certificates. On plain Kubernetes, it needs some work to create the secrets and not depend on the annotation.

**Comment by akrejcir** [comment]
/pj-rehearse pull-ci-kubevirt-vm-console-proxy-release-v0.1-e2e-functests

**Comment by akrejcir** [comment]
/pj-rehearse pull-ci-kubevirt-vm-console-proxy-release-v0.1-e2e-functests

**Pull request merged**
