### PR TITLE
OLS:  add separate bundle image

### PR DESCRIPTION
**Pull request by xrajesh**
- Test bundle image refers CI operator image 
- This change, makes a separate image for bundle , which will have the reference from CSV ( no substitution)

### CODE REVIEW

**Comment by xrajesh** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-operator-main-bundle-e2e

**Comment by xrajesh** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-operator-main-images

**Comment by xrajesh** [comment]
@bparees PTAL

**Comment by bparees** [comment]
@xrajesh make sure you rehearse + rehearse-ack as needed

**Pull request merged**
