### PR TITLE
Add all nightly single-node jobs as release informing for 4.9

### PR DESCRIPTION
**Pull request by omertuc**

### CODE REVIEW

**Comment by romfreiman** [comment]
maybe aws upgrade instead of azure upgrade?

**Comment by dhellmann** [comment]
> maybe aws upgrade instead of azure upgrade?

I don't see an AWS upgrade job in the list on [sippy](https://sippy.ci.openshift.org/sippy-ng/jobs/4.9?filters=%7B%22items%22%3A%5B%7B%22id%22%3A99%2C%22columnField%22%3A%22variants%22%2C%22operatorValue%22%3A%22contains%22%2C%22value%22%3A%22single-node%22%7D%5D%7D&sortField=net_improvement&sort=asc).

**Comment by omertuc** [comment]
> > maybe aws upgrade instead of azure upgrade?
> 
> I don't see an AWS upgrade job in the list on [sippy](https://sippy.ci.openshift.org/sippy-ng/jobs/4.9?filters=%7B%22items%22%3A%5B%7B%22id%22%3A99%2C%22columnField%22%3A%22variants%22%2C%22operatorValue%22%3A%22contains%22%2C%22value%22%3A%22single-node%22%7D%5D%7D&sortField=net_improvement&sort=asc).

Yeah not sure what "variants" means but if you search by name it shows up

https://sippy.ci.openshift.org/sippy-ng/jobs/4.9?filters=%7B%22items%22%3A%5B%7B%22id%22%3A99%2C%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22contains%22%2C%22value%22%3A%22single-node%22%7D%5D%7D&sort=asc&sortField=net_improvement

**Comment by dhellmann** [comment]
> > > maybe aws upgrade instead of azure upgrade?
> > 
> > 
> > I don't see an AWS upgrade job in the list on [sippy](https://sippy.ci.openshift.org/sippy-ng/jobs/4.9?filters=%7B%22items%22%3A%5B%7B%22id%22%3A99%2C%22columnField%22%3A%22variants%22%2C%22operatorValue%22%3A%22contains%22%2C%22value%22%3A%22single-node%22%7D%5D%7D&sortField=net_improvement&sort=asc).
> 
> Yeah not sure what "variants" means but if you search by name it shows up
> 
> https://sippy.ci.openshift.org/sippy-ng/jobs/4.9?filters=%7B%22items%22%3A%5B%7B%22id%22%3A99%2C%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22contains%22%2C%22value%22%3A%22single-node%22%7D%5D%7D&sort=asc&sortField=net_improvement

Weird. Maybe it's a UI bug.

**Comment by bparees** [comment]
not a UI bug, but some sort of analysis issue, the old sippy view also only shows the 4 jobs as part of the single-node variant:

image



https://github.com/openshift/sippy/blob/323f2fdb6f7db0881496daa5efe00b3e209dd088/pkg/testgridanalysis/testidentification/ocp_variants.go#L39 looks right, so i'm not sure why it's not getting picked up.

**Comment by stbenjam** [comment]
Looks like it's in never-stable: https://sippy.ci.openshift.org/sippy-ng/jobs/4.9?filters=%7B%22items%22%3A%5B%7B%22id%22%3A99%2C%22columnField%22%3A%22variants%22%2C%22operatorValue%22%3A%22contains%22%2C%22value%22%3A%22never-stable%22%7D%2C%7B%22id%22%3A99%2C%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22contains%22%2C%22value%22%3A%22single%22%7D%5D%7D&sort=asc&sortField=net_improvement

**Comment by omertuc** [comment]
> Looks like it's in never-stable: [sippy.ci.openshift.org/sippy-ng/jobs/4.9?filters=%7B%22items%22%3A%5B%7B%22id%22%3A99%2C%22columnField%22%3A%22variants%22%2C%22operatorValue%22%3A%22contains%22%2C%22value%22%3A%22never-stable%22%7D%2C%7B%22id%22%3A99%2C%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22contains%22%2C%22value%22%3A%22single%22%7D%5D%7D&sort=asc&sortField=net_improvement](https://sippy.ci.openshift.org/sippy-ng/jobs/4.9?filters=%7B%22items%22%3A%5B%7B%22id%22%3A99%2C%22columnField%22%3A%22variants%22%2C%22operatorValue%22%3A%22contains%22%2C%22value%22%3A%22never-stable%22%7D%2C%7B%22id%22%3A99%2C%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22contains%22%2C%22value%22%3A%22single%22%7D%5D%7D&sort=asc&sortField=net_improvement)

Yeah it's listed here:
https://github.com/openshift/sippy/blob/2239569bb27ac488d19bfa104be8d43cac37bdcf/pkg/testgridanalysis/testidentification/ocp_variants.go#L77

**Comment by dhellmann** [comment]
So, do we want to change to the AWS job or is the Azure job OK?

**Comment by omertuc** [comment]
[Azure](https://testgrid.k8s.io/redhat-openshift-ocp-release-4.9-informing#periodic-ci-openshift-release-master-ci-4.9-e2e-azure-upgrade-single-node) seems more stable than [aws](https://testgrid.k8s.io/redhat-openshift-ocp-release-4.9-informing#periodic-ci-openshift-release-master-ci-4.9-e2e-aws-upgrade-single-node) (less white columns)

@romfreiman is there any particular reason you prefer aws?

**Pull request merged**
