### PR TITLE
MGMT-14208: Adding presubmit lint job

### PR DESCRIPTION
**Pull request by danmanor**
Adding presubmit lint job

### CODE REVIEW

**Comment by danmanor** [comment]
@osherdp I think I added the config directly in the file instead of adding it in some other file and generate this config from there. If I am correct, can you point me to the file?

**Comment by osherdp** [comment]
> @osherdp I think I added the config directly in the file instead of adding it in some other file and generate this config from there. If I am correct, can you point me to the file?

you need to add the relevant code under https://github.com/openshift/release/blob/c973cbbfafc2d65338f128cbb66f88ab0f793a79/ci-operator/config/openshift-assisted/assisted-events-stream/openshift-assisted-assisted-events-stream-master.yaml#L17

**Comment by osherdp** [comment]
> /lgtm - @danmanor please make sure we merge the lint fixes in the target repo before this or it would be blocking

+1
you can also do ``/pj-rehearse`` to make sure the new job passes (after merging the lint re-formatting PR)

**Comment by adriengentil** [comment]
Is this PR still valid?

**Comment by danmanor** [comment]
@adriengentil no thanks

**Pull request closed without merging**
