### PR TITLE
Fix failing openshift-ansible unit test

### PR DESCRIPTION
**Pull request by mtnbikenc**
Unit test is reported as passing but the tests are actually failing.

- Added `pipefail`
- Added Ansible vars to point to `/tmp/ansible` instead of user home

### CODE REVIEW

**Comment by patrickdillon** [comment]
It looks this fixed the permissions issue and now the tests are running. I'm assuming the `set -o pipefail` fixes the false positive issue, but I don't think we can test that, right? 

Should we set unit to required for 3.11 & 3.10? https://github.com/openshift/release/blob/f8879e3e6a70ad29639a9992ffb5a5e4c0a8a5af/ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11-presubmits.yaml#L681

**Comment by mtnbikenc** [comment]
> It looks this fixed the permissions issue and now the tests are running. I'm assuming the `set -o pipefail` fixes the false positive issue, but I don't think we can test that, right?
> 
> Should we set unit to required for 3.11 & 3.10?
> 
> https://github.com/openshift/release/blob/f8879e3e6a70ad29639a9992ffb5a5e4c0a8a5af/ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11-presubmits.yaml#L681

When iterating on this PR I changed the pipefail option first and confirmed that it started reporting the failures.  I then add the required env vars so tox would run Ansible and write to /tmp.

It looks like the jobs are already required for 3.11 and 3.10.  No?

**Comment by patrickdillon** [comment]
> It looks like the jobs are already required for 3.11 and 3.10. No?

Woops I was looking for the wrong key, you are correct.

/lgtm

**Pull request merged**
