### PR TITLE
feat: add job for cleaning old rosa clusters

### PR DESCRIPTION
**Pull request by psturc**
https://issues.redhat.com/browse/KFLUXDP-7

Successful test run: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/57763/rehearse-57763-periodic-ci-konflux-ci-e2e-tests-main-rosa-old-clusters-cleanup/1846235122341253120

### CODE REVIEW

**Comment by psturc** [comment]
/pj-rehearse periodic-ci-konflux-ci-e2e-tests-main-rosa-old-clusters-cleanup

**Comment by psturc** [comment]
/pj-rehearse periodic-ci-konflux-ci-e2e-tests-main-rosa-old-clusters-cleanup

**Comment by psturc** [comment]
/pj-rehearse periodic-ci-konflux-ci-e2e-tests-main-rosa-old-clusters-cleanup

**Comment by psturc** [comment]
/pj-rehearse periodic-ci-konflux-ci-e2e-tests-main-rosa-old-clusters-cleanup

**Comment by psturc** [comment]
/pj-rehearse periodic-ci-konflux-ci-e2e-tests-main-rosa-old-clusters-cleanup

**Comment by psturc** [comment]
/pj-rehearse periodic-ci-konflux-ci-e2e-tests-main-rosa-old-clusters-cleanup

**Comment by psturc** [comment]
/pj-rehearse periodic-ci-konflux-ci-e2e-tests-main-rosa-old-clusters-cleanup

**Comment by psturc** [comment]
@flacatus @ascerra  could you guys take a look please

**Comment by psturc** [comment]
/pj-rehearse periodic-ci-konflux-ci-e2e-tests-main-rosa-old-clusters-cleanup

**Review by Dannyb48 — APPROVED** [review]
LGTM

**Pull request merged**
