### PR TITLE
template: Test a very simple form of automatic symptom generation

### PR DESCRIPTION
**Pull request by smarterclayton**
This will be wired into a triage tool and automatically take the most
recent symptoms from open bugs. It ensures that known flakes show up
prominently in the junit results instead of being buried.

Only introduced in one template for now.

### CODE REVIEW

**Comment by smarterclayton** [comment]
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/7669/rehearse-7669-pull-ci-openshift-cloud-credential-operator-master-e2e-gcp/1 should trigger the segfault detection.

**Comment by stevekuznetsov** [comment]
Good lord ... download a script from a Gist, to execute it inline? This is gold.

**Comment by smarterclayton** [comment]
Tagging while we assess how useful this is

**Pull request merged**
