### PR TITLE
OCPQE-20701 changing image to latest and filters

### PR DESCRIPTION
**Pull request by miyadav**
@sunzhaohua2 @huali9 @shellyyang1989 PTAL when time permits.

### CODE REVIEW

**Comment by miyadav** [comment]
/pj-rehearse pull-ci-openshift-cluster-capi-operator-main-regression-clusterinfra-cucushift-rehearse-capi-aws-ipi

**Comment by shellyyang1989** [comment]
Thanks for the fix. Seems like the tag used in *-release-4.x.yaml is also 4.16. Let's fix them together.

**Comment by miyadav** [comment]
/pj-rehearse pull-ci-openshift-cluster-capi-operator-main-regression-clusterinfra-cucushift-rehearse-capi-aws-ipi

**Comment by miyadav** [comment]
/pj-rehearse pull-ci-openshift-cluster-capi-operator-main-regression-clusterinfra-cucushift-rehearse-capi-aws-ipi

**Comment by miyadav** [comment]
@huali9 could you take  a look at the failed case when you get time, I think you fixed this in 64909(mapi) , might be same for 74803 (capi)

**Comment by huali9** [comment]
> 74803

Because the job is running in a different account not qe account and there is no pre-created placement group for testing. I previously updated our automation for CPMS part, but CAPI and MAPI part were missing. I've created https://issues.redhat.com/browse/OCPQE-26393 and will check all related cases and update the automation.

**Comment by miyadav** [comment]
/pj-rehearse pull-ci-openshift-cluster-capi-operator-main-regression-clusterinfra-cucushift-rehearse-capi-aws-ipi

**Comment by miyadav** [comment]
/pj-rehearse pull-ci-openshift-cluster-capi-operator-main-regression-clusterinfra-cucushift-rehearse-capi-aws-ipi

**Comment by miyadav** [comment]
@JoelSpeed , we can merge this now , PTAL when time permits.

**Pull request merged**
