### PR TITLE
Enable spot instances by default

### PR DESCRIPTION
**Pull request by liangxia**

### CODE REVIEW

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-automated-release-aws-ipi-mini-perm-f360

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-f9-longduration-mco-critical

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-multi-nightly-aws-ipi-amd-f7-netobserv

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-automated-release-aws-ipi-mini-perm-f360 periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-f9-longduration-mco-critical periodic-ci-openshift-openshift-tests-private-release-4.17-multi-nightly-aws-ipi-amd-f7-netobserv

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-automated-release-aws-ipi-mini-perm-f360 periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-f9-longduration-mco-critical periodic-ci-openshift-openshift-tests-private-release-4.17-multi-nightly-aws-ipi-amd-f7-netobserv

**Comment by jianlinliu** [comment]
@liangxia per our experience in jenkins system, we got some points to share:
1. spot instances quota is unstable. We often hit sopt instances quota limit issue even when we manually launch a cluster. If we enable it in ci, we have so many ci jobs, I guess the issues would bring trouble to us.
2. The assigned resource for spot instances might be withdraw by cloud provider during testing. Once that, that will break the whole ci testing, also bring a lot noise for our ci test result analysis.

Based on that, that is why we did not enable spot instances by default when we were running heavy testing in jenkins system. The same here, I guess we might not enable it in prow ci either. cc @yunjiang29 @jinyunma

**Pull request closed without merging**
