### PR TITLE
WIP Ostree build

### PR DESCRIPTION
**Pull request by vrutkovs**
Experiment with building ostree in api.ci

* `build_root` image (centos7 w/ golang installed) is used to clone the project as it has necessary user set
* `ostree-ci` is using F30 imagestream as a base for the dockerfile, which builds the code and runs minimal checks
* `sanity` test runs a simple command to verify the binary has been built

TODO:
* [ ] `owners` test fails as it doesn't have OWNERS filled in
* [ ] `config` test fails as the repos are not configured to have Prow triggers
* [ ] `rpm-ostree` build fails - wrong WORKDIR maybe?
* [ ] ostree's `sanity` test fails during `make install` as its not running as root
* [ ] Other tests fail as they can't run `make clean` to rebuild the package

Requires:
* [ ] https://github.com/ostreedev/ostree/pull/1916
* [ ] https://github.com/projectatomic/rpm-ostree/pull/1893

### CODE REVIEW

**Comment by cgwalters** [comment]
> ostree-ci is using F30 imagestream as a base for the dockerfile, which builds the code and runs minimal checks

I think we should use https://github.com/coreos/coreos-assembler/pull/730

The workaround for the fedora-release bug is here btw https://github.com/projectatomic/rpm-ostree/commit/0d841b2e2f11c360d2c96e2c5d1b10dc3bd03fb2#diff-4347e55ee672a63c1ae3a89e57fa78eeR14

**Comment by vrutkovs** [comment]
>I think we should use coreos/coreos-assembler#730

Good idea, added as TODO

**Comment by cgwalters** [comment]
It's built in the `coreos` namespace to imagestream `cosa-buildroot:latest`...a namespace I just created and need to ensure other people have access to it.

Anyways `registry.svc.ci.openshift.org/coreos/cosa-buildroot:latest` should be pullable.

**Comment by cgwalters** [comment]
@vrutkovs Are you still working on this?

**Comment by vrutkovs** [comment]
@cgwalters I am, I've got a few ideas to try tomorrow. Hopefully at least `ostree`'s sanity test would pass soon, so later we can move on to running tests in CentOS CI

**Comment by cgwalters** [comment]
I took the rpm-ostree part of this to https://github.com/openshift/release/pull/5263
Let's do ostree once that's done and working well.
/close

**Pull request closed without merging**
