### PR TITLE
Regular jobs shouldn't be using registry/serial

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by smarterclayton** [comment]
I prefer creepy pasta.

**Comment by stevekuznetsov** [comment]
3spooky5me

**Comment by smarterclayton** [comment]
Added a new serial job, switched some to use /minimal.  Still waiting on https://github.com/openshift/origin/pull/20989 before merging

**Comment by smarterclayton** [comment]
dependencies merged

**Pull request merged**
