### PR TITLE
Enable release-note plugin for CRI-O

### PR DESCRIPTION
**Pull request by saschagrunert**
We're now using the official Kubernetes pull request template so we can enable the release notes plugin as well.

/cc @mrunalp @haircommander

### CODE REVIEW

**Comment by saschagrunert** [comment]
PTAL @rhatdan @mrunalp @haircommander

**Comment by haircommander** [comment]
```
{"component":"unset","file":"prow/cmd/checkconfig/main.go:78","func":"main.reportWarning","level":"warning","msg":"[the following orgs or repos forbid the do-not-merge/release-note-label-needed label for merging but do not enable the release-note plugin: [org: cri-o], the following orgs or repos enable the release-note plugin but do not forbid the do-not-merge/release-note-label-needed label for merging: [repo: openshift-priv/sig-storage-local-static-provisioner]]","severity":"warning","time":"2020-07-06T13:34:50Z"}
```
odd, it sure looks like the release-note plugin is enabled

**Comment by saschagrunert** [comment]
> ```
> {"component":"unset","file":"prow/cmd/checkconfig/main.go:78","func":"main.reportWarning","level":"warning","msg":"[the following orgs or repos forbid the do-not-merge/release-note-label-needed label for merging but do not enable the release-note plugin: [org: cri-o], the following orgs or repos enable the release-note plugin but do not forbid the do-not-merge/release-note-label-needed label for merging: [repo: openshift-priv/sig-storage-local-static-provisioner]]","severity":"warning","time":"2020-07-06T13:34:50Z"}
> ```
> 
> odd, it sure looks like the release-note plugin is enabled

I don't get it too, we only enable the plugin for the `cri-o` org, right?

**Comment by haircommander** [comment]
hm

/retest

**Comment by haircommander** [comment]
lol there seems to be a cyclical dependency
```the following orgs or repos enable the release-note plugin but do not forbid the do-not-merge/release-note-label-needed label for merging```

**Comment by saschagrunert** [comment]
Green! PTAL @haircommander @mrunalp

**Comment by haircommander** [comment]
:tada:

**Comment by haircommander** [comment]
/lgtm

@petr-muller @stevekuznetsov PTAL

**Pull request merged**
