### PR TITLE
fix pod build broken after golang update

### PR DESCRIPTION
**Pull request by nishant-parekh**
update `sed` command to be agnostic of go version

### CODE REVIEW

**Review by edcdavid — APPROVED** [review]

**Comment by nishant-parekh** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.12-e2e-telco5g-ptp

**Comment by edcdavid** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.12-e2e-telco5g-ptp

**Comment by nishant-parekh** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.12-e2e-telco5g-ptp

**Comment by nishant-parekh** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.12-e2e-telco5g-ptp

**Pull request closed without merging**
