### PR TITLE
MGMT-11348: Build and publish multi-arch images for assisted agent

### PR DESCRIPTION
**Pull request by ori-amizur**
Resulting image is **quay.io/edge-infrastructure/assisted-installer-agent-multi:latest**

/cc @adriengentil 
/cc @mkowalski

### CODE REVIEW

**Comment by osherdp** [comment]
/hold
@ori-amizur can we make sure that it works?
For example, changing temporarily the job type to presubmit and seeing the rehearsal

I haven't seen a final rehearsal for the [assisted-installer PR](https://github.com/openshift/release/pull/31917) (only more outdated runs) which is a bit problematic in my opinion

**Comment by ori-amizur** [comment]
> /hold @ori-amizur can we make sure that it works? For example, changing temporarily the job type to presubmit and seeing the rehearsal
> 
> I haven't seen a final rehearsal for the [assisted-installer PR](https://github.com/openshift/release/pull/31917) (only more outdated runs) which is a bit problematic in my opinion

Already did it.  https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/32005/rehearse-32005-pull-ci-openshift-assisted-installer-agent-master-edge-publish-multi-arch-images/1567448335034355712

**Review by osherdp — APPROVED** [review]

**Comment by osherdp** [comment]
> > /hold @ori-amizur can we make sure that it works? For example, changing temporarily the job type to presubmit and seeing the rehearsal
> > I haven't seen a final rehearsal for the [assisted-installer PR](https://github.com/openshift/release/pull/31917) (only more outdated runs) which is a bit problematic in my opinion
> 
> Already did it. https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/32005/rehearse-32005-pull-ci-openshift-assisted-installer-agent-master-edge-publish-multi-arch-images/1567448335034355712
> 
> Also did final run for [assisted-installer PR](https://github.com/openshift/release/pull/31917), but it is not shown (don't know why ) in PR history.

ack. didn't notice that. thank you!

the reason it's not shown is because rehearse jobs are optional. so if you unhold before it finishes running it will not wait and merge the PR before (and it will abort the job as well)

**Pull request merged**
