### PR TITLE
[OCPQE-22232][wip]add prow debug vsphere4

### PR DESCRIPTION
**Pull request by weinliu**

### CODE REVIEW

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by kuiwang02** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/uncc @kuiwang02 

/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse cucushift-installer-rehearse-vsphere-ipi-template

**Comment by weinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-vsphere-ipi-template

**Comment by weinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-vsphere-ipi-template

**Pull request closed without merging**
