### PR TITLE
Update to use OCP 4.12 for devfile registry tests

### PR DESCRIPTION
**Pull request by josephca**
Signed-off-by: Joseph Kim <joskim@redhat.com>

### CODE REVIEW

**Review by elsony — APPROVED** [review]
/lgtm

**Comment by josephca** [comment]
/pj-rehearse pull-ci-devfile-registry-operator-main-v4.12-registry-operator-integration-test

**Comment by josephca** [comment]
/pj-rehearse pull-ci-devfile-registry-main-v4.12-registry-test

**Comment by josephca** [comment]
/pj-rehearse pull-ci-devfile-registry-operator-main-v4.12-registry-operator-integration-test
/pj-rehearse pull-ci-devfile-registry-main-v4.12-registry-test

**Comment by josephca** [comment]
/pj-rehearse pull-ci-devfile-registry-main-v4.12-registry-test

**Comment by josephca** [comment]
/pj-rehearse pull-ci-devfile-registry-operator-main-v4.12-registry-operator-integration-test

**Review by elsony — APPROVED** [review]
/lgtm

**Pull request merged**
