### PR TITLE
[WINDUP-4050] Add Branch v1.2 and Remove Old v1.0 Branch for MTR Interop Scenario

### PR DESCRIPTION
**Pull request by calebevans**

### CODE REVIEW

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-windup-windup-ui-tests-v1.2-mtr-ocp4.14-lp-interop-mtr-interop-aws

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-windup-windup-ui-tests-v1.2-mtr-ocp4.14-lp-interop-mtr-interop-aws

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-windup-windup-ui-tests-v1.2-mtr-ocp4.14-lp-interop-mtr-interop-aws

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-windup-windup-ui-tests-v1.2-mtr-ocp4.14-lp-interop-mtr-interop-aws

**Review by amp-rh — APPROVED** [review]

**Pull request merged**
