### PR TITLE
build up rhcs 1.6.3 release testing

### PR DESCRIPTION
**Pull request by radtriste**

### CODE REVIEW

**Comment by radtriste** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-advanced-critical-high-163 periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-private-critical-high-163  periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-critical-high-163 periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-private-critical-high-163

**Comment by radtriste** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-shared-vpc-critical-high-163

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-shared-vpc-critical-high-163

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-private-critical-high-163

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-advanced-critical-high-163

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-shared-vpc-critical-high-163

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-medium-low-163

**Pull request closed without merging**
