### PR TITLE
STOR-1744: Add smb csi presubmit jobs

### PR DESCRIPTION
**Pull request by Phaow**
### [STOR-1744](https://issues.redhat.com//browse/STOR-1744): Add smb csi driver source image

- Add smb csi presubmit jobs execute e2e extended test (upstream e2e mostly test the sc parameters)
  https://github.com/openshift/csi-driver-smb/pull/6#issuecomment-2100635623

### CODE REVIEW

**Comment by Phaow** [comment]
/pj-rehearse pull-ci-openshift-csi-operator-master-smb-operator-e2e-extended

**Comment by Phaow** [comment]
/pj-rehearse pull-ci-openshift-csi-operator-master-smb-operator-e2e-extended

**Comment by Phaow** [comment]
/pj-rehearse pull-ci-openshift-csi-operator-master-smb-operator-e2e-extended

**Comment by Phaow** [comment]
/pj-rehearse pull-ci-openshift-csi-operator-master-smb-operator-e2e-extended

**Comment by Phaow** [comment]
/pj-rehearse pull-ci-openshift-csi-operator-master-smb-operator-e2e-extended

**Comment by Phaow** [comment]
/pj-rehearse pull-ci-openshift-csi-operator-master-smb-operator-e2e-extended

**Comment by Phaow** [comment]
Hi @jsafrane @mpatlasov , could you please help take a look when you get a chance? Thanks!

**Comment by Phaow** [comment]
/pj-rehearse pull-ci-openshift-csi-operator-master-smb-operator-e2e-extended

**Comment by Phaow** [comment]
/pj-rehearse pull-ci-openshift-csi-operator-master-smb-operator-e2e-extended

**Comment by Phaow** [comment]
/pj-rehearse ack

FYI: The 1 flaky ` [sig-storage] Ensure that all storage objects are deleted during the tests`, I fixed in https://github.com/kubernetes-csi/csi-driver-smb/pull/779 .

**Comment by deepsm007** [comment]
/hold
batch failure while merging, i'll unhold after clearing the batch

**Pull request merged**
