### PR TITLE
fixed artifacts copy bug orion

### PR DESCRIPTION
**Pull request by shashank-boyapally**
exiting after copy to artifacts

### CODE REVIEW

**Comment by shashank-boyapally** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-write_jobs_to_gsheet-get-orion-results-cdv2

**Comment by shashank-boyapally** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-payload-control-plane-6nodes

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-payload-control-plane-6nodes

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-write_jobs_to_gsheet-get-orion-results-cdv2

**Comment by shashank-boyapally** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-write_jobs_to_gsheet-get-orion-results-cdv2

**Comment by shashank-boyapally** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-write_jobs_to_gsheet-get-orion-results-cdv2

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-write_jobs_to_gsheet-get-orion-results-cdv2

**Review by jtaleric — APPROVED** [review]
tested locally
/lgtm

**Pull request merged**
