### PR TITLE
Add test image for application-ui

### PR DESCRIPTION
**Pull request by chenz4027**
Signed-off-by: chenz4027 <magchen@redhat.com>
https://github.com/open-cluster-management/backlog/issues/12663
- remove duplicate unit-test stage as it has the same flow with sonarcloud test stanza
- add image build steps for application-ui-tests
- and image mirror with latest tag for release-2.3 for both application-ui and application-ui-tests
- and image pr mirror test for application-ui-tests

### CODE REVIEW

**Review by birsanv — APPROVED** [review]
lgtm

**Review by fxiang1 — APPROVED** [review]
Looks good. Thanks!

**Comment by chenz4027** [comment]
/cc @birsanv @fxiang1 

Could I get new lgtm approvals as there are additional commits? Thanks!

**Review by birsanv — APPROVED** [review]
lgtm

**Pull request merged**
