### PR TITLE
Add regional jobs

### PR DESCRIPTION
**Pull request by yasun1**
[OCM-9268](https://issues.redhat.com//browse/OCM-9268)

### CODE REVIEW

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-hcp-advanced-regional-f3

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-hcp-advanced-regional-f3

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-hcp-advanced-regional-f3

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-hcp-advanced-regional-f3

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-hcp-advanced-regional-f3

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-hcp-advanced-regional-f3 periodic-ci-openshift-rosa-master-e2e-rosa-sts-advanced-regional-f3

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-sts-advanced-regional-f3

**Comment by yasun1** [comment]
@robpblake @xueli181114 Please help review the PR. Thanks.

**Comment by robpblake** [comment]
Confirmed with @yasun1 that rehearsal failures relate to the tests executed by the jobs and not the job configuration themselves.

**Review by robpblake — APPROVED** [review]

**Pull request merged**
