### PR TITLE
Adding infra nodes to the kube-burner job

### PR DESCRIPTION
**Pull request by jtaleric**
Adding infra nodes to the 4.13 GCP kube-burner job to see if that helps with the failures

### CODE REVIEW

**Review by afcollins — APPROVED** [review]
LGTM

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-gcp-4.13-ocp-qe-perfscale-ci-tests-kube-burner

**Comment by vishnuchalla** [comment]
LGTM!

**Review by vishnuchalla — APPROVED** [review]

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-gcp-4.13-ocp-qe-perfscale-ci-tests-kube-burner

**Pull request merged**
