### PR TITLE
Lint job for the velero project (konveyor-dev branch)

### PR DESCRIPTION
**Pull request by mpryc**
- adds lint job for the velero project (konveyor-dev branch)
- adds run_if_changed for unit and lint jobs to trigger only for a relevant files.

### CODE REVIEW

**Comment by mpryc** [comment]
Current lint is br8ken in velero project. To fix it this needs to be merged and backported to other branches https://github.com/openshift/velero/pull/343

**Review by weshayutin — APPROVED** [review]
/LGTM

**Comment by mpryc** [comment]
@weshayutin could you please re-approve? The config job was failing due to the issue in the ci-operator-config job which has nothing to do with this change. Now it's passing.

**Review by weshayutin — APPROVED** [review]
/LGTM

**Pull request merged**
