### PR TITLE
Bug 2033711: IBM VPC operator needs e2e csi tests for ibmcloud

### PR DESCRIPTION
**Pull request by dobsonj**
Adding ibmcloud e2e tests for ibm-vpc-block-csi-driver-operator
https://bugzilla.redhat.com/show_bug.cgi?id=2033711
The `openshift-e2e-ibmcloud` workflow was defined in https://github.com/openshift/release/pull/20433
/cc @openshift/storage

### CODE REVIEW

**Comment by dobsonj** [comment]
/test ci/rehearse/openshift/ibm-vpc-block-csi-driver/release-4.10/e2e-ibmcloud
(failed due to status 500 from image registry)

**Review by bertinatto — COMMENTED** [review]
@dobsonj do you plan to test the CSI driver as well? Here's an example on how to create a workflow for that (search for `openshift-e2e-azure-csi-file`): https://github.com/openshift/release/pull/22988/files

**Comment by dobsonj** [comment]
> @dobsonj do you plan to test the CSI driver as well? Here's an example on how to create a workflow for that (search for `openshift-e2e-azure-csi-file`): https://github.com/openshift/release/pull/22988/files

@bertinatto Yeah, thanks for the pointer, I started looking into this too but still working on it. I was going to follow up with a separate PR for the CSI tests if this one passed all the checks in time to merge today.

**Comment by dobsonj** [comment]
/hold
until https://github.com/openshift/ibm-vpc-block-csi-driver-operator/pull/12 merges (for Dockerfile.test)

**Comment by dobsonj** [comment]
last push just sets `optional: true` for the `e2e-ibmcloud-csi` tests

**Comment by dobsonj** [comment]
from ci/prow/config:
```
could not start the process: fork/exec /checkconfig: no such file or directory
```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/24720/pull-ci-openshift-release-master-config/1496610055653429248/prowjob.json
```
					"image": "gcr.io/k8s-prow/checkconfig:v20220223-0d1254f509",
					"command": [
						"/checkconfig"
					],
```
This is slightly problematic because checkconfig moved:
```
$ docker run -it --entrypoint sh gcr.io/k8s-prow/checkconfig:v20220223-0d1254f509
/ # ls /checkconfig
ls: /checkconfig: No such file or directory
/ # which checkconfig 
/ko-app/checkconfig
```

**Comment by dobsonj** [comment]
> could not start the process: fork/exec /checkconfig: no such file or directory

This was already fixed today, and my branch includes this commit:
https://github.com/openshift/release/commit/322aaaf9473fe1c0d307887f38848c79700e50c7
so... :confused:

**Comment by dobsonj** [comment]
Looking better, but...
/retest
e2e-ibmcloud: A few failures due to timeouts / unexpected alerts and want to see if these are consistent.
e2e-ibmcloud-csi: 2 failures due to `clusterrolebindings.rbac.authorization.k8s.io "e2e-node-attacher" already exists` and 2 failures for the AllowedTopologies tests (that might need to be disabled?)

/retitle WIP: Bug 2033711: IBM VPC operator needs e2e csi tests for ibmcloud
The current changes only cover ibm-vpc-block-csi-driver-operator - I want to get a clean test run on one repo before expanding to cover the others.

**Comment by dobsonj** [comment]
The current install failures are due to https://bugzilla.redhat.com/show_bug.cgi?id=2066463

**Comment by dobsonj** [comment]
> The current install failures are due to https://bugzilla.redhat.com/show_bug.cgi?id=2066463

The fix for that bug merged
/retest

**Comment by dobsonj** [comment]
filed https://bugzilla.redhat.com/show_bug.cgi?id=2071758 for the current e2e-ibmcloud-csi failure:
External Storage [Driver: vpc.block.csi.ibm.io] [Testpattern: Dynamic PV (default fs)] subPath should support readOnly directory specified in the volumeMount

**Comment by dobsonj** [comment]
> External Storage [Driver: vpc.block.csi.ibm.io] [Testpattern: Dynamic PV (default fs)] subPath should support readOnly directory specified in the volumeMount

This test just passed successfully on my cluster... so... is it a flake?
/retest

**Comment by bparees** [comment]
image name follows our conventions
/approve

**Review by cjschaef — APPROVED** [review]
/lgtm

**Pull request merged**
