### PR TITLE
Add must-gather images for ODH

### PR DESCRIPTION
**Pull request by VaishnaviHire**
This PR makes following changes -
- Update image promotion for odh-manifests
- Add must-gather image build jobs for ODH  upstream and downstream

### CODE REVIEW

**Comment by VaishnaviHire** [comment]
/pj-rehearse pull-ci-opendatahub-io-opendatahub-operator-opendatahub-manifests-e2e

**Review by anishasthana — COMMENTED** [review]
/lgtm

**Review by DharmitD — COMMENTED** [review]
/lgtm

**Comment by VaishnaviHire** [comment]
/pj-rehearse ack

Some of the rehearsals failed due to infrastructure errors

**Pull request merged**
