### PR TITLE
Add kubernetes-sigs/security-profiles-operator e2e test

### PR DESCRIPTION
**Pull request by JAORMX**
This adds an e2e test definition for the security-profiles-operator so
it gets OpenShift coverage.

### CODE REVIEW

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now fc4da02ae082bda5cf25de892442141aa7424803

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now f153e8634f73e2fafb852ec7b30bcc75b73ee70f

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 6dde87fc3f07c664215c247d8cb502c2023eec6c

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 623819930de923bec23ec839b54be71ac6907796

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 602f2ab38a566989e1103d1b94d9feb25ceed794

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now c6c454d989da983582e0d2ac428be7528a5c997c

**Comment by petr-muller** [comment]
/uncc
Please ping when this passes tests

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by pjbgf — APPROVED** [review]
/lgtm

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
