### PR TITLE
Add the missing secrets on build01

### PR DESCRIPTION
**Pull request by hongkailiu**
https://issues.redhat.com/browse/DPTP-1012

/assign @stevekuznetsov @droslean

### CODE REVIEW

**Comment by hongkailiu** [comment]
> @hongkailiu did you already deploy them?

Not me. :)
https://issues.redhat.com/browse/DPTP-1012?focusedCommentId=14011683&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14011683

**Comment by alvaroaleman** [comment]
Okay, can you please run the secret bootstrapper once for build01 to make sure that what is deployed matches the config?

**Comment by hongkailiu** [comment]
> Okay, can you please run the secret bootstrapper once for build01 to make sure that what is deployed matches the config?

Will do after merge

**Comment by hongkailiu** [comment]
Run the tool `make cluster=build01` 

```
time="2020-03-27T21:05:17Z" level=info msg="handling secret: build01:ci/sentry-dsn"
time="2020-03-27T21:05:18Z" level=info msg="handling secret: build01:ocp/mirror.openshift.com"
time="2020-03-27T21:05:18Z" level=info msg="handling secret: build01:ci/github-credentials-openshift-ci-robot-private-git-cloner"
time="2020-03-27T21:05:18Z" level=info msg="handling secret: build01:ci/gce-sa-credentials-gcs-publisher"
time="2020-03-27T21:05:18Z" level=info msg="handling secret: build01:ci/gce-sa-credentials-gcs-private"
time="2020-03-27T21:05:18Z" level=info msg="handling secret: build01:ci/cluster-secrets-aws"
time="2020-03-27T21:05:18Z" level=info msg="handling secret: build01:ci/cluster-secrets-gcp"
time="2020-03-27T21:05:18Z" level=info msg="handling secret: build01:ci/cluster-secrets-vsphere"
time="2020-03-27T21:05:19Z" level=info msg="handling secret: build01:ci/cluster-secrets-azure4"
time="2020-03-27T21:05:19Z" level=info msg="handling secret: build01:ci/apici-ci-operator-credentials"
time="2020-03-27T21:05:19Z" level=info msg="handling secret: build01:ci/boskos-credentials"
time="2020-03-27T21:05:20Z" level=info msg="running bw command ..." args="[logout]"
```

**Pull request merged**
