### PR TITLE
OLM-2771: Add a presubmit that runs the openshift conformance tests in o/platform-operators

### PR DESCRIPTION
**Pull request by timflannagan**
See https://issues.redhat.com/browse/OLM-2771 for more information.

Signed-off-by: timflannagan <timflannagan@gmail.com>

### CODE REVIEW

**Comment by tylerslaton** [comment]
Applying the needed labels and holding for green CI.

/lgtm
/hold

**Comment by timflannagan** [comment]
```
clusteroperator.config.openshift.io/platform-operators-aggregated condition met
```

Nice.

**Comment by timflannagan** [comment]
Best guess is an issue with the build02 + runc changes from earlier. Seems harmless to let this retest overnight.

/retest

**Pull request merged**
