### PR TITLE
Add periodic ovn upgrade jobs (4.6->4.7)

### PR DESCRIPTION
**Pull request by jluhrsen**
Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>

### CODE REVIEW

**Comment by jluhrsen** [comment]
@alvaroaleman @stevekuznetsov , I'm not sure who to ping to take a look at PRs in this repo, but I saw the ci-robot requested from you originally. Can you point me in the right direction please?

**Review by alvaroaleman — APPROVED** [review]

**Comment by alvaroaleman** [comment]
/ok-to-test
@jluhrsen can you please follow the steps outlined in https://source.redhat.com/groups/public/atomicopenshift/atomicopenshift_wiki/openshift_onboarding_checklist_for_github to become a member of the openshift github organization and thus get testresults without someone else approving that first?

**Comment by jluhrsen** [comment]
> /ok-to-test
> @jluhrsen can you please follow the steps outlined in https://source.redhat.com/groups/public/atomicopenshift/atomicopenshift_wiki/openshift_onboarding_checklist_for_github to become a member of the openshift github organization and thus get testresults without someone else approving that first?

thanks... I remember doing all those steps when I first joined but I missed the final part about requesting access. I just did
that.

**Comment by jluhrsen** [comment]
@alvaroaleman I think this is good to go now. the one check that failed is a rehearse job created by this patch I guess, but looks to be related to some trouble with azure and ip allocation limits.

**Pull request merged**
