### PR TITLE
Update ci-operator config for cluster-kube-scheduler-operator.

### PR DESCRIPTION
**Pull request by aveshagarwal**
@smarterclayton @stevekuznetsov 

Could you check if it looks good now?

### CODE REVIEW

**Comment by smarterclayton** [comment]
You can test locally by cloning ci-operator and building it, then running `./ci-operator --config <path_to_this_file> --git-ref openshift/cluster-kube-scheduler-operator@master --dry-run`

If you get an error, your file still isn't correct

**Comment by aveshagarwal** [comment]
> You can test locally by cloning ci-operator and building it, then running ./ci-operator --config <path_to_this_file> --git-ref openshift/cluster-kube-scheduler-operator@master --dry-run

> If you get an error, your file still isn't correct

cool, trying it now.

**Comment by aveshagarwal** [comment]
@smarterclayton dry is failing with "error: could not run steps: could not resolve stable imagestream: Unauthorized"

**Comment by aveshagarwal** [comment]
```
2018/09/27 12:35:01 Tagging cluster-kube-scheduler-operator into stable
{
  "metadata": {
    "name": "stable:cluster-kube-scheduler-operator",
    "namespace": "ci-op-vm3dvn16",
    "creationTimestamp": null
  },
  "tag": {
    "name": "",
    "annotations": null,
    "from": {
      "kind": "ImageStreamImage",
      "namespace": "ci-op-vm3dvn16",
      "name": "pipeline@dry-fake"
    },
    "generation": null,
    "importPolicy": {},
    "referencePolicy": {
      "type": "Local"
    }
  },
  "generation": 0,
  "lookupPolicy": {
    "local": false
  },
  "image": {
    "metadata": {
      "creationTimestamp": null
    },
    "dockerImageMetadata": null,
    "dockerImageLayers": null
  }
}
2018/09/27 12:35:01 All images ready
```

However I also see the above, so may be its working for cluster-kube-scheduler-repo?

**Comment by smarterclayton** [comment]
You should see a list of tasks "Running ...." in the first few lines

**Comment by aveshagarwal** [comment]
```
un
2018/09/27 12:35:00 Resolved openshift/cluster-kube-scheduler-operator@master to commit 29f482cceaa5db71e43037775f822fa85345abc9
2018/09/27 12:35:00 Resolved source https://github.com/openshift/cluster-kube-scheduler-operator to master@29f482cc
2018/09/27 12:35:01 Resolved https://api.ci.openshift.org/openshift/release:golang-1.10 to sha256:43ad4740f25e4cbc6de8a964e2ce65ce50fbc24fc4e5e268e0a7370ca3b09bd1
2018/09/27 12:35:01 Resolved https://api.ci.openshift.org/openshift/centos:7 to sha256:fc2476ccae2a5186313f2d1dadb4a969d6d2d4c6b23fa98b6c7b0a1faad67685
2018/09/27 12:35:01 Using namespace ci-op-vm3dvn16
2018/09/27 12:35:01 Running [input:root], [input:os], [release-inputs], src, bin, test-bin, cluster-kube-scheduler-operator, [output:stable:cluster-kube-scheduler-operator], [images], [release:latest], unit
2018/09/27 12:35:01 Tagging release images from openshift/origin-v4.0:${component}
2018/09/27 12:35:01 Tagging https://api.ci.openshift.org/openshift/release:golang-1.10 into pipeline:root
2018/09/27 12:35:01 Tagging https://api.ci.openshift.org/openshift/centos:7 into pipeline:os
```

**Comment by smarterclayton** [comment]
The running line looks correct.

**Comment by aveshagarwal** [comment]
> The running line looks correct.

ok anything else or is this PR good to go?

**Pull request merged**
