### PR TITLE
cert-rotation: mirror release to local mirror

### PR DESCRIPTION
**Pull request by vrutkovs**

### CODE REVIEW

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-180d pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-360d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-suspend-90d pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-sno-cert-rotation-shutdown-90d pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-sno-cert-rotation-suspend-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-30d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-30d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-30d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-30d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ovn-ha-cert-rotation-shutdown-30d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ovn-ha-cert-rotation-shutdown-30d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by Altdarkzodiac** [comment]
Hey..I have a project who is ready

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ovn-ha-cert-rotation-shutdown-30d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-metal-ovn-ha-cert-rotation-suspend-90d periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ovn-ha-cert-rotation-suspend-30d

**Review by dinhxuanvu — APPROVED** [review]
/lgtm
/approve

**Review by Altdarkzodiac — COMMENTED** [review]
V

**Pull request merged**
