### PR TITLE
Hive: Add manifests for a Hypershift setup

### PR DESCRIPTION
**Pull request by alvaroaleman**
So that we can use hypershift to generate clusters in which we install hypershift.

Ref https://issues.redhat.com/browse/HOSTEDCP-281

/cc @csrwng

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/assign @petr-muller 
For approval (I can technically approve it myself but want it to be acked by tp)
This is from https://issues.redhat.com/browse/DPTP-2657 as discussed in slack

**Review by petr-muller — APPROVED** [review]

**Comment by hongkailiu** [comment]
https://issues.redhat.com/browse/DPTP-2657

**Pull request merged**
