### PR TITLE
Add configs for qe-private-deck repos

### PR DESCRIPTION
**Pull request by petr-muller**
- add configs for qe-private-deck repos (#26498)
- Private QE Deck config: add `repo:` stanzas to bucket configs

/cc @smg247 @jianzhangbjz 
/hold

I'd like Stephen to check whether what I added makes sense.

### CODE REVIEW

**Comment by petr-muller** [comment]
yaml indents...

/meow

**Comment by smg247** [comment]
/lgtm
yeah, the indents killed me...
`determinize-prow-config` completely removed the `repo` line and I didn't even notice it.
I wonder if we can add a warning if that tool entirely removes a line...

**Comment by jianzhangbjz** [comment]
Thank you both!

**Pull request merged**
