### PR TITLE
Add nightly jobs for Nutanix Winc

### PR DESCRIPTION
**Pull request by weinliu**
```
./generate-cron-entry.sh nutanix-ipi-ovn-winc-f14 openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml 

./generate-cron-entry.sh nutanix-ipi-ovn-winc-f14 openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml 

./generate-cron-entry.sh nutanix-ipi-ovn-winc-f7 openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml 

./generate-cron-entry.sh nutanix-ipi-ovn-winc-f7 openshift-openshift-tests-private-release-4.17__amd64-nightly.yaml
cron: 30 19 6,20 * *
cron: 35 19 8,24 * *
cron: 52 15 3,10,17,24 * *
cron: 3 2 4,11,18,27 * *

```

### CODE REVIEW

**Comment by weinliu** [comment]
@liangxia could you help take a look?
cc: @rrasouli

**Comment by weinliu** [comment]
@liangxia could you help take a look? Thanks!

**Comment by liangxia** [comment]
Waiting for feature team to ack.

**Comment by weinliu** [comment]
@rrasouli could you help take a look?

**Comment by rrasouli** [comment]
/lgtm
Thanks a lot, indeed Nutanix supported from 4.14

**Pull request merged**
