### PR TITLE
adding qe-report-ref statement missed earlier

### PR DESCRIPTION
**Pull request by miyadav**
@JoelSpeed @shellyyang1989 @sunzhaohua2 @huali9 , PTAL when time permits.

### CODE REVIEW

**Comment by shellyyang1989** [comment]
What does the ref do?

**Comment by JoelSpeed** [comment]
Did this perhaps reach some global timeout? Suggests it might have done with cancelled by user

**Comment by miyadav** [comment]
/pj-rehearse pull-ci-openshift-cluster-cloud-controller-manager-operator-master-level0-clusterinfra-azure-ipi-proxy-tests

**Pull request merged**
