### PR TITLE
CCO-401: Include azure-workload-identity images configuration.

### PR DESCRIPTION
**Pull request by abutcher**

### CODE REVIEW

**Comment by abutcher** [comment]
/assign @dhellmann

The target repo doesn't yet have a `.ci-operator.yaml` config but I think it gets automatically created by the CI robot based on other [history](https://github.com/openshift/aws-pod-identity-webhook/commits/master/.ci-operator.yaml).

**Comment by dhellmann** [comment]
/approve

The name `azure-workload-identity-webhook` looks good to me.

**Pull request merged**
