### PR TITLE
Stop applying MachineSet on build01

### PR DESCRIPTION
**Pull request by hongkailiu**
Because we do have replica defined in the yaml (they are dynamic values and modified by autoscaler), it leads to deleting the replica field of the objects.

https://coreos.slack.com/archives/CHY2E1BL4/p1585674017078900?thread_ts=1585659039.054000&cid=CHY2E1BL4

So we stop applying those in the post-submit jobs.

/cc @michaelgugino @elmiko

/cc @alvaroaleman

### CODE REVIEW

**Comment by hongkailiu** [comment]
I manually add replica back ... and the autoscaler is working

```
oc get machineset -n openshift-machine-api
NAME                              DESIRED   CURRENT   READY   AVAILABLE   AGE
build01-9hdwj-worker-us-east-1a   12        12        4       4           61d
build01-9hdwj-worker-us-east-1b   7         7         1       1           61d
build01-9hdwj-worker-us-east-1c   3         3         3       3           61d
```

**Comment by alvaroaleman** [comment]
The replicas key does not get removed when applying this:
```
$ oc apply -f clusters/build-clusters/01_cluster/openshift-machine-api/_admin_build01-9hdwj-worker-us-east-1a_machine_set.yaml --dry-run -o json|jq '.spec.replicas'
12
```

It probably got removed when this was applied the first time, as `oc` does a three way merge of value in annotation + currently deployed value + desired value. If the replicas field was once set, that would explicitly unset it. But this  is not happening anymore currently.

**Pull request closed without merging**
