### PR TITLE
OSSM federation add push image job

### PR DESCRIPTION
**Pull request by yxun**

### CODE REVIEW

**Comment by yxun** [comment]
/pj-rehearse pull-ci-openshift-service-mesh-federation-master-push-image

**Comment by yxun** [comment]
/pj-rehearse pull-ci-openshift-service-mesh-federation-master-push-image

**Comment by yxun** [comment]
/pj-rehearse pull-ci-openshift-service-mesh-federation-master-push-image

**Review by FilipB — APPROVED** [review]

**Pull request merged**
