### PR TITLE
cno, ci: align golangci-lint w/ go1.22 version

### PR DESCRIPTION
**Pull request by maiqueb**
golangci-lint requires version 1.56 for it to tolerate golang1.22, as per it's changelog [0].

This PR unblocks consuming the OpenShift API for 4.17, in [this CNO's PR](https://github.com/openshift/cluster-network-operator/pull/2357).

[0] - https://github.com/golangci/golangci-lint/releases/tag/v1.56.0

### CODE REVIEW

**Comment by jcaamano** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-images
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-verify

**Comment by jcaamano** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-images pull-ci-openshift-cluster-network-operator-master-verify

**Comment by jcaamano** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-lint

**Comment by jcaamano** [comment]
@maiqueb you would need to change `openshift-cluster-network-operator-release-4.17.yaml` as well

**Comment by jcaamano** [comment]
I would try with the v1.59.0 release, from
https://github.com/openshift/release/blob/c0aeb28186eb19e64112448eb90cdaaba0a41246/core-services/image-mirroring/_config.yaml#L630

**Comment by maiqueb** [comment]
> I would try with the v1.59.0 release, from
> 
> https://github.com/openshift/release/blob/c0aeb28186eb19e64112448eb90cdaaba0a41246/core-services/image-mirroring/_config.yaml#L630

Why ? That will require the golangci configuration to be updated because a bunch on linters are no longer maintained. 
... I imagine that when I replace the linters I'll have to go fix a bunch of code that doesn't meet the new linters expectations. 

We need to draw a line somewhere ...

**Comment by maiqueb** [comment]
but yeah

> > I would try with the v1.59.0 release, from
> > https://github.com/openshift/release/blob/c0aeb28186eb19e64112448eb90cdaaba0a41246/core-services/image-mirroring/_config.yaml#L630
> 
> Why ? That will require the golangci configuration to be updated because a bunch on linters are no longer maintained. ... I imagine that when I replace the linters I'll have to go fix a bunch of code that doesn't meet the new linters expectations.
> 
> We need to draw a line somewhere ...

Thanks for pointer though, I didn't know where to look for what lint images were available. 

... I'll go choose one that exists and works on this scenario,.

**Comment by jcaamano** [comment]
Just removing `deadcode` , `structcheck` and `varcheck` from the configuration does the trick. `unused` which is already enabled should provide the same coverage:
```
vagrant@devmaster ~/dev/openshift/cluster-network-operator master 1m 5s
❯ make golangci-lint
golangci-lint run --verbose --print-resources-usage --modules-download-mode=vendor --timeout=5m0s
INFO golangci-lint has version 1.59.1 built with go1.22.3 from 1a55854a on 2024-06-09T18:08:33Z 
INFO [config_reader] Config search paths: [./ /home/vagrant/dev/openshift/cluster-network-operator /home/vagrant/dev/openshift /home/vagrant/dev /home/vagrant /home /] 
INFO [config_reader] Used config file .golangci.yaml 
WARN [config_reader] The configuration option `run.skip-dirs` is deprecated, please use `issues.exclude-dirs`. 
INFO [lintersdb] Active 13 linters: [errcheck exportloopref gosimple govet ineffassign misspell nolintlint nosprintfhostport staticcheck tenv unconvert unused wastedassign] 
INFO [loader] Go packages loading at mode 575 (name|types_sizes|exports_file|deps|files|imports|compiled_files) took 1.395025592s 
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 13.493709ms 
INFO [linters_context/goanalysis] analyzers took 0s with no stages 
INFO [runner] Issues before processing: 27, after processing: 0 
INFO [runner] Processors filtering stat (out/in): filename_unadjuster: 27/27, path_prettifier: 27/27, skip_dirs: 27/27, exclude: 27/27, identifier_marker: 27/27, exclude-rules: 25/27, cgo: 27/27, invalid_issue: 27/27, skip_files: 27/27, autogenerated_exclude: 27/27, nolint: 0/25 
INFO [runner] processing took 5.988446ms with stages: nolint: 4.633687ms, exclude-rules: 528.746µs, autogenerated_exclude: 368.777µs, identifier_marker: 323.622µs, path_prettifier: 82.965µs, skip_dirs: 40.324µs, cgo: 2.703µs, invalid_issue: 2.566µs, filename_unadjuster: 790ns, max_same_issues: 581ns, exclude: 460ns, fixer: 410ns, sort_results: 401ns, skip_files: 391ns, uniq_by_line: 351ns, diff: 261ns, source_code: 251ns, max_from_linter: 249ns, path_prefixer: 231ns, max_per_file_from_linter: 230ns, path_shortener: 229ns, severity-rules: 221ns 
INFO [runner] linters took 293.684216ms with stages: goanalysis_metalinter: 287.630403ms 
INFO File cache stats: 0 entries of total size 0B 
INFO Memory: 19 samples, avg is 37.3MB, max is 91.1MB 
INFO Execution took 1.704557722s 
```

**Comment by maiqueb** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-images pull-ci-openshift-cluster-network-operator-master-verify pull-ci-openshift-cluster-network-operator-master-lint

**Comment by maiqueb** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-images pull-ci-openshift-cluster-network-operator-master-verify pull-ci-openshift-cluster-network-operator-master-lint

**Comment by maiqueb** [comment]
@jcaamano o/

This is looking good afaiu.

**Pull request merged**
