### PR TITLE
Creating Prow jobs for openshift-gitops branches

### PR DESCRIPTION
**Pull request by Srivaralakshmi**
Creating Prow jobs for openshift-gitops branches

### CODE REVIEW

**Comment by Srivaralakshmi** [comment]
@aireilly Kindly review and provide your LGTM/approval. Thanks!

**Comment by aireilly** [comment]
Https://github.com/openshift/openshift-docs/pull/79190 must be merged and CP'd to all gitops branches before this can be merged to pass the CI.

**Review by aireilly — APPROVED** [review]

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-gitops-docs-1.14-validate-asciidoc

**Pull request merged**
