### PR TITLE
baremetal: restore IPv6 as default configuration

### PR DESCRIPTION
**Pull request by stbenjam**
OVN fixes for shared gw mode on IPv6 have landed (BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1866464), so we can
put back IPv6 as the default in CI.

### CODE REVIEW

**Comment by stbenjam** [comment]
/hold

Let's make sure e2e-metal-ipi passes

**Comment by danwinship** [comment]
Setup is failing and not logging anything useful

```
2020/08/26 14:41:47 Executing "e2e-metal-ipi-baremetalds-packet-setup"
2020/08/26 15:12:17 error: unable to signal to artifacts container to terminate in pod e2e-metal-ipi-baremetalds-packet-setup, triggering deletion: could not run remote command: unable to upgrade connection: container not found ("artifacts")
```

(note time gap)

[Last run in openshift/baremetal-operator](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_baremetal-operator/93/pull-ci-openshift-baremetal-operator-master-e2e-metal-ipi/1298755343425212416) failed the same way.

**Comment by danwinship** [comment]
The ipv6 job logs are weird... All three CNO pods seem to think they are the leader, but I can't tell why because of CNO logging bugs (https://github.com/openshift/cluster-network-operator/pull/771). From what I can tell, at least one CNO thinks it is waiting for ovn-kubernetes to be deployed, but in fact, none of them even created the `openshift-ovn-kubernetes` namespace.

**Comment by stbenjam** [comment]
@cybertron is looking into the failures, it looks like the control plane aren't getting their hostnames early enough. It appears to be tied to br-ex and maybe some of the shared gateway fixes? But it's still not clear yet

**Comment by danwinship** [comment]
> @cybertron is looking into the failures, it looks like the control plane aren't getting their hostnames early enough. It appears to be tied to br-ex and maybe some of the shared gateway fixes? But it's still not clear yet

Does baremetal need a fix similar to https://github.com/openshift/machine-config-operator/pull/2031 ?

**Comment by cybertron** [comment]
Yes, I proposed https://github.com/openshift/machine-config-operator/pull/2058 which fixes the hostname issue I'm seeing. I  haven't gotten a full e2e run to work yet though. Not sure whether it's related to ipv6 or just general flakiness. The errors I'm seeing are similar to some other cross-platform issues that have been reported though.

**Comment by danwinship** [comment]
So in the last e2e-metal-ipi run, one of the masters has registered itself as a node with the name "localhost.localdomain", which I guess is the hostname problem you're talking about.

It got as far as creating 2 worker nodes. The nodes have not successfully come up though, and it's hard to tell why because `must-gather` failed, and the `log-bundle` file has logs from the masters but not the workers. From `nodes.json` we can see that both workers have `KubeletNotReady` with "Network plugin returns error: No CNI configuration file in /etc/kubernetes/cni/net.d/. Has your network provider started?". `pods.json` shows `multus` and `ovnkube-node` pods on `worker-0` but not `worker-1`. The multus pod seems to have stalled somehow: 4 of the 5 initContainers have run, but the 5th has not been started, for no obvious reason. It can't be an image-pulling problem because the 4th and 5th initContainers use the same image.

**Comment by cybertron** [comment]
Yeah, that's the hostname bug.

I'm also seeing issues with workers not coming up. In my local deployment I have one worker where I can't even access the virsh console. I have no idea how ipv6 would cause something like that, so my suspicion is that it's unrelated.

**Comment by danwinship** [comment]
/hold
we're probably going to end up partially reverting ovn-kube shared gateway mode...

**Comment by stbenjam** [comment]
The error on the CI job seems related to image mirroring.

/test pj-rehearse

**Comment by stbenjam** [comment]
https://github.com/openshift-metal3/dev-scripts/pull/1110 should hopefully fix this

**Comment by danwinship** [comment]
FTR I'm continuing to see mysterious problems in IPv6 with node -> service IP connections (including in particular, hostNetwork pod -> apiserver) that prevent installs from succeeding. We're trying to debug why.

**Comment by stbenjam** [comment]
/test pj-rehearse

The last few failures have been networking issues on the CI cluster, or on Packet.  Not sure what's going on there :-\

**Comment by danwinship** [comment]
/hold
https://github.com/ovn-org/ovn-kubernetes/pull/1714
https://github.com/ovn-org/ovn-kubernetes/pull/1715
and one more to come

**Comment by danwinship** [comment]
IPv6 cluster installs successfully with https://github.com/openshift/ovn-kubernetes/pull/278 (which includes 2 ovn-kube fixes that haven't yet merged upstream).

**Comment by stbenjam** [comment]
> IPv6 cluster installs successfully with [openshift/ovn-kubernetes#278](https://github.com/openshift/ovn-kubernetes/pull/278) (which includes 2 ovn-kube fixes that haven't yet merged upstream).

That PR was closed, what's the status of IPv6 in OVN?

**Comment by danwinship** [comment]
https://github.com/openshift/ovn-kubernetes/pull/279 should have fixed this (we can manually bring up clusters with that).
/retest

**Comment by stbenjam** [comment]
Install completed but tests have been stuck for ~40 minutes. Maybe some new test isn't working well with IPv6? Will retrigger once it fails, and have a look locally.

**Comment by stbenjam** [comment]
/test pj-rehearse

e2e-tests on that last run showed a very, very broken cluster.

**Comment by stbenjam** [comment]
/hold cancel

e2e-metal-ipi is passing with IPv6/disconnected and fewer tests.  Once https://github.com/openshift/origin/pull/24887 lands we can put them back.

**Pull request merged**
