### PR TITLE
Sync Serverless CI config/

### PR DESCRIPTION
**Pull request by serverless-qe**

### CODE REVIEW

**Comment by jcpowermac** [comment]
please do not move this job from vsphere-elastic to vsphere-2

vsphere-2 is being decommissioned

**Comment by jcpowermac** [comment]
https://github.com/openshift/release/pull/54677

**Comment by pierDipi** [comment]
Thanks @jcpowermac 

This is an automated PR as we have tooling that automates CI config, we will need to update it there so that the PR doesn't get created anymore

/close

**Pull request closed without merging**
