### PR TITLE
nmstate-console-plugin add branch forwarding

### PR DESCRIPTION
**Pull request by upalatucci**

### CODE REVIEW

**Comment by hstastna** [comment]
@upalatucci seems more tests are failing in this PR. Can you PTAL? Can we do something about those failings? Thanks.

**Comment by upalatucci** [comment]
hi @hstastna i'm just trying to understand with joep from the art team now. When will be ready i can PTAL

**Comment by upalatucci** [comment]
@hstastna @pcbailey i think i need an lgtm from you guys.

This pr is to synchronize release-4.14 branch with main. The art team supported me on creating this pr

**Comment by upalatucci** [comment]
@jupierce we need an approve from you i think

**Pull request merged**
