### PR TITLE
machine-api-provider-openstack: Verify go mod

### PR DESCRIPTION
**Pull request by pierreprinetti**
When dependencies change, go.mod, go.sum and the vendor directory must
be up-to-date.

Implements [OSASINFRA-2748](https://issues.redhat.com/browse/OSASINFRA-2748)

### CODE REVIEW

**Comment by pierreprinetti** [comment]
The rehearsal correctly fails, because the repository is in a dirty state.
The fix for the repo [is ready](https://github.com/openshift/machine-api-provider-openstack/pull/14) and ideally, we merge this first so that we can then verify that one.

**Review by mandre — COMMENTED** [review]
/lgtm
/retest
/hold for CI

**Pull request merged**
