### PR TITLE
ci-operator/step-registry/openshift/upgrade: Rename openshift-upgrade-*-loki -> openshift-upgrade-*

### PR DESCRIPTION
**Pull request by wking**
In 54678d5070 (#11333), we grew openshift-upgrade-gcp-loki workflow and ported cluster-version operator update CI to use it.  The workflow configures an in-cluster [Loki][2] which helps preserve logs from [previous][3] [pods][4]:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/476/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-upgrade/1319475296516182016/artifacts/e2e-agnostic-upgrade/gather-loki/loki-container-logs/loki-container-logs.tar | tar tvz
drwxr-xr-x 1002980000/root   0 2020-10-22 21:44 loki-container-logs/
drwxr-xr-x 1002980000/root   0 2020-10-22 21:44 loki-container-logs/e2e-k8s-sig-apps-daemonset-upgrade-7750/
drwxr-xr-x 1002980000/root   0 2020-10-22 21:44 loki-container-logs/e2e-k8s-sig-apps-daemonset-upgrade-7750/ds1-6f57p/
-rw-r--r-- 1002980000/root 113 2020-10-22 21:44 loki-container-logs/e2e-k8s-sig-apps-daemonset-upgrade-7750/ds1-6f57p/ds1_0.log
drwxr-xr-x 1002980000/root   0 2020-10-22 21:44 loki-container-logs/e2e-k8s-sig-apps-daemonset-upgrade-7750/ds1-j7l5p/
-rw-r--r-- 1002980000/root 113 2020-10-22 21:44 loki-container-logs/e2e-k8s-sig-apps-daemonset-upgrade-7750/ds1-j7l5p/ds1_0.log
...
```

That's useful for updates, whose late-in-the-update machine-config rollout will drain all the machines, leading to new replacement pods, and (pre-Loki) losing access to logs from the previous pods.  Since that change, all current multi-step update jobs have been gradually transitioned to use openshift-upgrade-*-loki workflows, except for:

```console
$ git --no-pager grep 'workflow: openshift-upgrade-[^-]*$' ci-operator/config
ci-operator/config/openshift/release/openshift-release-master__ocp-4.5-ci.yaml:    workflow: openshift-upgrade-aws
```

With this commit, I'm renaming the openshift-upgrade-*-loki workflows to openshift-upgrade-*, to show that they are the default, update workflows, reflecting the step maintainer's current best-practice recommendations.  This should help reduce questions like "I'm adding a new AWS update job, which of the openshift-upgrade-aws* flavors should I use?".

Generated with:

```console
$ sed -i 's/\(workflow: openshift-upgrade-[^-]*\)-loki/\1/' $(git grep -l 'workflow: openshift-upgrade-[^-]*-loki$' ci-operator/config)
$ for X in aws azure gcp; do for Y in "ci-operator/step-registry/openshift/upgrade/${X}/loki"/openshift-upgrade-*; do Z="$(echo "${Y}" | sed 's|/*loki-*||g')"; git rm -f "${Z}"; git mv "${Y}" "${Z}"; done; git rm -f "ci-operator/step-registry/openshift/upgrade/${X}/loki/OWNERS"; done
$ sed -i 's|/*loki-*||g' ci-operator/step-registry/openshift/upgrade/*/openshift-upgrade-*-workflow.metadata.json
$ emacs ci-operator/step-registry/openshift/upgrade/*/openshift-upgrade-*-workflow.yaml # 'as' and 'documentation' tweaks
```

[1]: https://github.com/openshift/release/pull/11333#event-3720634023
[2]: https://github.com/grafana/loki
[3]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/476/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-upgrade/1319475296516182016
[4]: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/476/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-upgrade/1319475296516182016/artifacts/e2e-agnostic-upgrade/gather-loki/loki-container-logs/

### CODE REVIEW

**Comment by wking** [comment]
/assign @petr-muller 

Rehearsals look pretty good.

**Review by petr-muller — APPROVED** [review]
LGTM from DPTP PoV
/hold

**Comment by petr-muller** [comment]
30/35 rehearsal pass is quite impressive

**Comment by petr-muller** [comment]
I missed the assign in https://github.com/openshift/release/pull/14217#issuecomment-742092972 which I interpret as "I can make this merge"

/hold cancel

**Pull request merged**
