### PR TITLE
openshift/assisted-service: Run jobs against relevant changes

### PR DESCRIPTION
**Pull request by lranjbar**

### CODE REVIEW

**Comment by osherdp** [comment]
Hmm, it's not that readable. I would prefer to do that if prow would implement a negative filter
@YuviGold

**Comment by lranjbar** [comment]
Yeah, there is no negative filter for prow. The only thing with allowlist is that it has to be updated when the top level directories change. Can be easy to forget. Does that happen often for our project? (I haven't seen it happen but don't know really.)

For allowlist on the subsystem/ would it be all the code directories + subsystem? I'll like to pair down the `always_run: true` as much as possible.

**Comment by YuviGold** [comment]
Please add `swagger.yaml` as well to all the lists

**Comment by lranjbar** [comment]
For MGMT-4716 and MGMT-4481

**Pull request merged**
