### PR TITLE
Added E2E upgrade job (4.4 -> 4.5) for the EO operator 

### PR DESCRIPTION
**Pull request by igor-karpukhin**
PR that fixes issues with EO upgrade job (prev PR: https://github.com/openshift/release/pull/10014)

### CODE REVIEW

**Comment by alanconway** [comment]
Not so familiar with this stuff, will leave to @ewolinetz 
/uncc @alanconway

**Comment by igor-karpukhin** [comment]
This PR has to be merged first: https://github.com/openshift/elasticsearch-operator/pull/514

**Pull request merged**
