### PR TITLE
updates to separate minishift

### PR DESCRIPTION
**Pull request by rnapoles-rh**

### CODE REVIEW

**Comment by prietyc123** [comment]
I think pr is meant for minishift only, no? Title of the pr is confusing 😕

**Comment by rnapoles-rh** [comment]
ci/rehearse/openshift/odo/master/psi-minishift-integration-e2e — Job failed because of dependency on https://github.com/openshift/odo/pull/4542

**Comment by rnapoles-rh** [comment]
@mohammedzee1000 need this merged to be able to test openshift/odo#4542

**Comment by rnapoles-rh** [comment]
@kadel @dharmit can you please add me to the openshift org ? see https://github.com/openshift/release/pull/17056#issuecomment-805016372

**Comment by prietyc123** [comment]
@rnapoles-rh The owner file which you modified are auto populated owner file. If you want to be in the list of reviewer, that should be done from odo repo itself.

**Comment by rnapoles-rh** [comment]
I will close this PR and reopen to new on

**Pull request closed without merging**
