### PR TITLE
updating to use library configs that run concurrently

### PR DESCRIPTION
**Pull request by coreydaley**

### CODE REVIEW

**Comment by gabemontero** [comment]
how about you update the verify job while you are messing with openshift/release to add make verify periodic as well @coreydaley

**Comment by coreydaley** [comment]
@gabemontero Since the script that runs right before it is actually doing the downloading already, running that verify script doesn't really make any sense.  On the other pull request check, it is verifying that the user committed their changes.

**Comment by gabemontero** [comment]
> @gabemontero Since the script that runs right before it is actually doing the downloading already, running that verify script doesn't really make any sense. On the other pull request check, it is verifying that the user committed their changes.

well it runs every 15 minutes now, right :-) ?

that said, it is just a question of having to remember the name of the periodic job and find the latest results to see if it is failing or not (I always have to force myself to check it from time to time), vs. seeing it in-line with a given PR ... it seems like a easy add for some quick convenience

**Comment by coreydaley** [comment]
The problem with adding it to the verify job for pull requests is that if anything has changed, the would have to run the make periodic import locally, commit the changes, and then push it back up.

I don't feel like that is something that we should put on the users shoulders.
Can't we update the periodic job to send an email if it fails?

**Comment by gabemontero** [comment]
> The problem with adding it to the verify job for pull requests is that if anything has changed, the would have to run the make periodic import locally, commit the changes, and then push it back up.
> 
> I don't feel like that is something that we should put on the users shoulders.
> Can't we update the periodic job to send an email if it fails?

Doesn't look like it.  It was even suggested by our test-infra guys upstream https://github.com/kubernetes/test-infra/issues/8668 which then seemed to transfer over to https://github.com/kubernetes/test-infra/issues/9905 but ultimately nothing seems to have landed.

I also grepped the repo on email but none of the hits are what we are talking about here.

I'll defer, at least for now based on your onus on the users point, and go ahead and 

/lgtm

And we can collectively keep an eyes on things manuall for now.

**Pull request merged**
