### PR TITLE
Add upgrade tests for stable 4.13 to EC 4.14 for ARM and multi

### PR DESCRIPTION
**Pull request by liangxia**

### CODE REVIEW

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-ec-4.14-upgrade-from-stable-4.13-aws-ipi-ovn-ipsec-f14

**Comment by liangxia** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-ec-4.14-upgrade-from-stable-4.13-azure-ipi-fullyprivate-proxy-f28

**Comment by liangxia** [comment]
Verified it's using the expected payloads,
```
INFO[2023-08-02T01:10:24Z] Resolved release latest to quay.io/openshift-release-dev/ocp-release:4.13.7-multi 
INFO[2023-08-02T01:10:24Z] Resolved release target to quay.io/openshift-release-dev/ocp-release:4.14.0-ec.4-multi 
```
```
INFO[2023-08-02T01:11:11Z] Resolved release arm64-latest to quay.io/openshift-release-dev/ocp-release:4.13.7-aarch64 
INFO[2023-08-02T01:11:11Z] Resolved release arm64-target to quay.io/openshift-release-dev/ocp-release:4.14.0-ec.4-aarch64 
```

/pj-rehearse abort

**Comment by jiajliu** [comment]
lgtm
/cc @aleskandro

**Pull request merged**
