### PR TITLE
Integrate e2e (golang+cucushift) for multiple vsphere profiles

### PR DESCRIPTION
**Pull request by liangxia**
Running QE's e2e (golang+cucushift) together.

### CODE REVIEW

**Comment by kuiwang02** [comment]
/lgtm

just one note: it seems you want to keep e2e-vsphere-upi on verification-tests.

**Comment by liangxia** [comment]
> /lgtm
> 
> just one note: it seems you want to keep e2e-vsphere-upi on verification-tests.

Not mean to keep a specific tests there.  It's that Prow does not allow empty `tests` for a config.
Also we'd like to keep the config file so that we can add other tests (e.g, destructive tests) in the coming days.

**Pull request merged**
