### PR TITLE
NO-JIRA: Testing OCPBUGS-34534 fix

### PR DESCRIPTION
**Pull request by pamoedom**
Removing `openshift-e2e-test-qe` test chain in order to verify OCPBUGS-34534 FIPS patch.

### CODE REVIEW

**Comment by pamoedom** [comment]
cc @rhjanders

**Comment by pamoedom** [comment]
cc @sgoveas

**Comment by rhjanders** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-ovn-fips
(trying something that worked for me in another PR in case it's useful)

**Comment by sgoveas** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-baremetalds-ipi-ovn-ipv4-fips-f14

**Pull request closed without merging**
