### PR TITLE
CORS-2659: installer: add azure nat-gateway presubmit job 

### PR DESCRIPTION
**Pull request by r4f4**
Now that NatGateway is a supported outbound type, let's add a test job to make sure we don't break this workflow.

### CODE REVIEW

**Comment by r4f4** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-azure-nat-gateway

**Comment by r4f4** [comment]
From the `azure-conf` step:
```bash
Writing 'outboundType: NatGateway' to install-config
```
From the `ipi-install-install` step, the install-config stanza contains:
```yaml
platform:
  azure:
    region: centralus
    outboundType: NatGateway
    baseDomainResourceGroupName: os4-common
```
The `openshift_install.log` contains:
```bash
time="2023-07-18T18:08:52Z" level=debug msg="azurerm_nat_gateway.nat_gw[0]: Creation complete after 15s [id=/subscriptions/d38f1e38-4bed-438e-b227-833f997adf6a/resourceGroups/ci-op-9j2zithf-b81f5-bkrkz-rg/providers/Microsoft.Network/natGateways/ci-op-9j2zithf-b81f5-bkrkz-natgw]"
[...]
time="2023-07-18T19:03:19Z" level=debug msg="Time elapsed per stage:"
time="2023-07-18T19:03:19Z" level=debug msg="              vnet: 13m48s"
time="2023-07-18T19:03:19Z" level=debug msg="         bootstrap: 2m28s"
time="2023-07-18T19:03:19Z" level=debug msg="           cluster: 7m11s"
time="2023-07-18T19:03:19Z" level=debug msg="Bootstrap Complete: 15m4s"
time="2023-07-18T19:03:19Z" level=debug msg="               API: 32s"
time="2023-07-18T19:03:19Z" level=debug msg=" Bootstrap Destroy: 2m12s"
time="2023-07-18T19:03:19Z" level=debug msg=" Cluster Operators: 14m17s"
time="2023-07-18T19:03:19Z" level=info msg="Time elapsed: 55m15s"
```

I will updated the job name once I see the e2e results.

**Comment by r4f4** [comment]
Update: added `ovn` to the job name and fixed indentation/tabs on the `-commands.sh` file.

**Comment by r4f4** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-azure-ovn-nat-gateway pull-ci-openshift-installer-master-e2e-azure-ovn pull-ci-openshift-installer-master-e2e-azure-ovn-upi pull-ci-openshift-installer-master-e2e-azure-ovn-shared-vpc

**Comment by r4f4** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-azure-ovn

**Comment by r4f4** [comment]
Update: rebased to fix merge conflicts.

**Comment by jhixson74** [comment]
LGTM, just need to rebase.

**Comment by r4f4** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-azure-nat-gateway

**Comment by r4f4** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-azure-ovn-nat-gateway

**Pull request closed without merging**
