### PR TITLE
Enable e2e-gcp on cri-o master branch

### PR DESCRIPTION
**Pull request by umohnani8**
Enable the e2e-gcp job as optional on the cri-o master
branch. This will help when e2e-aws in down or being flakey.

Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

### CODE REVIEW

**Comment by fidencio** [comment]
LGTM, thanks @umohnani8!

**Comment by umohnani8** [comment]
@vrutkovs @alvaroaleman @hongkailiu  PTAL

**Comment by alvaroaleman** [comment]
@umohnani8 you as an approver creating that PR approved it and anyone from your team can lgtm it, rehearsals tell you if the job work, I don't think you need dptp here

**Comment by umohnani8** [comment]
got it, thanks @alvaroaleman!

**Pull request merged**
