### PR TITLE
add health check in post install on azure platform

### PR DESCRIPTION
**Pull request by jinyunma**
1. Add step `cucushift-installer-check-capability` in chain `cucushift-installer-check`
2. Add chain `cucushift-installer-check` into all provision chains on azure platform
3. Fix issue in step `cucushift-installer-check-capability` when ADDITIONAL_ENABLED_CAPABILITIES is not set.

### CODE REVIEW

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-nightly-azure-ipi-baselinecaps-v412-p3-f28-destructive periodic-ci-openshift-verification-tests-master-installer-rehearse-4.13-installer-rehearse-azure

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-nightly-azure-ipi-baselinecaps-v412-p3-f28-destructive

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.14-installer-rehearse-azure

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-nightly-azure-ipi-baselinecaps-v412-p3-f28-destructive periodic-ci-openshift-verification-tests-master-installer-rehearse-4.14-installer-rehearse-azure

**Comment by jinyunma** [comment]
cc @yunjiang29 @gpei @jianlinliu to review

**Comment by gpei** [comment]
@yunjiang29 @jianli-wei the next step is let's add the chain `cucushift-installer-check` into all provision chains of AWS and GCP?

**Comment by jianli-wei** [comment]
> @yunjiang29 @jianli-wei the next step is let's add the chain `cucushift-installer-check` into all provision chains of AWS and GCP?

ok, let me add for GCP provision chains after it's merged, thanks!

**Comment by yunjiang29** [comment]
> @yunjiang29 @jianli-wei the next step is let's add the chain `cucushift-installer-check` into all provision chains of AWS and GCP?

Sure, I'll double-check AWS chains.

**Comment by gpei** [comment]
cc @jianlinliu for the conclusion we made last week. 

We plan to add Chain `cucushift-installer-check` into all the provision chains for all platforms gradually, so that we can 
add post checking steps like `cucushift-installer-check-capability` to the `cucushift-installer-check` chain which doesn't have the dedicated workflow to insert, or add some other kind of post checking which would be applied to all clusters in the future, we can also add it into `cucushift-installer-check` chain directly. 

Another benefit of doing so is, the `cucushift-installer-check` chain belongs to cluster provision chain, the Step phase pre,  so once the check point failed, the failure could be collected as Install failures in Report Portal, so it's straightforward for us to notice those failures.

**Pull request merged**
