### PR TITLE
openstack: add a job to test FIPS enabled

### PR DESCRIPTION
**Pull request by EmilienM**
Other platforms have it (GCP, AWS, etc), let's add one for OpenStack so
we increase our testing coverage with this important scenario.

Jira: [OSASINFRA-2600](https://issues.redhat.com/browse/OSASINFRA-2600)

### CODE REVIEW

**Comment by EmilienM** [comment]
/retest
```
* 3x kubelet: Failed to pull image "image-registry.openshift-image-registry.svc:5000/ci-op-p4t88b7b/stable:openstack-installer": rpc error: code = Unknown desc = Error reading manifest openstack-installer in image-registry.openshift-image-registry.svc:5000/ci-op-p4t88b7b/stable: manifest unknown: manifest unknown
```

**Review by vrutkovs — APPROVED** [review]

**Review by mandre — COMMENTED** [review]
/lgtm

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
