### PR TITLE
Expansion of Openshift Pipelines operator on ROSA to OCP4.17

### PR DESCRIPTION
**Pull request by Sau1506mya**

### CODE REVIEW

**Comment by Sau1506mya** [comment]
/pj-rehearse pull-ci-openshift-pipelines-release-tests-release-v1.16-openshift-pipelines-ocp4.17-lp-rosa-classic-images periodic-ci-openshift-pipelines-release-tests-release-v1.16-openshift-pipelines-ocp4.17-lp-rosa-classic-openshift-pipelines-interop-rosa-aws

**Review by srivickynesh — APPROVED** [review]
/lgtm

**Pull request merged**
