### PR TITLE
Enable retester for the openshift organization.

### PR DESCRIPTION
**Pull request by nesty156**
I would like to enable `retester` for the openshift organization.
[Retester's documentation](https://docs.ci.openshift.org/docs/architecture/retester/)
[DPTP-2827](https://issues.redhat.com/browse/DPTP-2827)

### CODE REVIEW

**Review by hongkailiu — COMMENTED** [review]
You need to remove it from the old one.

https://github.com/openshift/release/blob/c8520d987afc379f9b2eca5eb5f59186fa5c04a3/ci-operator/jobs/infra-periodics.yaml#L313

**Comment by petr-muller** [comment]
❤️

**Pull request merged**
