### PR TITLE
OCPQE-20701: add regression job for autoscaler

### PR DESCRIPTION
**Pull request by sunzhaohua2**
For regression autoscaler cases on autoscaler repos rebases/updates
@miyadav @huali9 @shellyyang1989 @JoelSpeed PTAL

### CODE REVIEW

**Comment by sunzhaohua2** [comment]
/pj-rehearse pull-ci-openshift-kubernetes-autoscaler-master-regression-clusterinfra-aws-ipi-proxy-autoscaler

**Comment by sunzhaohua2** [comment]
/pj-rehearse pull-ci-openshift-cluster-autoscaler-operator-master-regression-clusterinfra-gcp-ipi-autoscaler

**Comment by sunzhaohua2** [comment]
/pj-rehearse pull-ci-openshift-kubernetes-autoscaler-master-regression-clusterinfra-aws-ipi-proxy-autoscaler

**Comment by sunzhaohua2** [comment]
/pj-rehearse pull-ci-openshift-cluster-autoscaler-operator-master-regression-clusterinfra-gcp-ipi-autoscaler

**Comment by sunzhaohua2** [comment]
/pj-rehearse pull-ci-openshift-cluster-autoscaler-operator-master-regression-clusterinfra-gcp-ipi-autoscaler

**Comment by sunzhaohua2** [comment]
/pj-rehearse pull-ci-openshift-cluster-autoscaler-operator-master-regression-clusterinfra-gcp-ipi-autoscaler

**Comment by sunzhaohua2** [comment]
/pj-rehearse pull-ci-openshift-kubernetes-autoscaler-master-regression-clusterinfra-aws-ipi-proxy-autoscaler

**Comment by sunzhaohua2** [comment]
/pj-rehearse pull-ci-openshift-kubernetes-autoscaler-master-regression-clusterinfra-aws-ipi-proxy-autoscaler

**Comment by huali9** [comment]
LGTM

**Pull request merged**
