### PR TITLE
Stackrox release 4.5

### PR DESCRIPTION
**Pull request by porridge**
CI configuration files to support Stackrox release `4.5`.

### CODE REVIEW

**Review by msugakov — COMMENTED** [review]
It would help very much reviewing if you'd leave a note how you obtained these files. 

Did you just copy `release-x.y` to `release-4.5` or did you do something else?

**Comment by porridge** [comment]
> It would help very much reviewing if you'd leave a note how you obtained these files.
> 
> Did you just copy `release-x.y` to `release-4.5` or did you do something else?

@msugakov I manually invoked the relevant commands in the start release workflow (because that one failed to authenticate). Sorry I don't have the links handy, will post when back at the keyboard.

**Comment by porridge** [comment]
> @msugakov I manually invoked the relevant commands in the start release workflow (because that one failed to authenticate). Sorry I don't have the links handy, will post when back at the keyboard.

https://github.com/stackrox/stackrox/actions/runs/9851848580/job/27199425555

**Review by msugakov — APPROVED** [review]
/lgtm

Diffed `config/` files between `x.y` and `4.5` and found only the branch name adjusted.

**Comment by msugakov** [comment]
What else does it need?

**Comment by msugakov** [comment]
It needs `/pj-rehearse ack` from you @porridge

**Pull request merged**
