### PR TITLE
OCPBUGS-20097: Set default image as RHEL9 for oc

### PR DESCRIPTION
**Pull request by ardaguclu**
This PR defines base RHEL9 images whose will be used by oc.

### CODE REVIEW

**Comment by ardaguclu** [comment]
/pj-rehearse pull-ci-openshift-oc-master-e2e-agnostic-ovn-cmd

**Comment by ardaguclu** [comment]
/pj-rehearse pull-ci-openshift-oc-master-e2e-agnostic-ovn-cmd

**Comment by ardaguclu** [comment]
/pj-rehearse pull-ci-openshift-oc-master-e2e-agnostic-ovn-cmd

**Comment by ardaguclu** [comment]
/pj-rehearse pull-ci-openshift-oc-master-e2e-agnostic-ovn-cmd

**Comment by ardaguclu** [comment]
/pj-rehearse pull-ci-openshift-oc-master-e2e-agnostic-ovn-cmd

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
