### PR TITLE
Automation for DVO tests bundle building approach

### PR DESCRIPTION
**Pull request by JoaoFula**

### CODE REVIEW

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-deployment-validation-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-deployment-validation-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-deployment-validation-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-deployment-validation-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-deployment-validation-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-deployment-validation-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-deployment-validation-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-deployment-validation-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-deployment-validation-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-deployment-validation-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-deployment-validation-operator-e2e-tests

**Comment by JoaoFula** [comment]
Skipping pj-rehearse since the failure happened due to wrong option when running pytests and has been corrected

**Review by ncaak — APPROVED** [review]
/lgtm

**Pull request merged**
