### PR TITLE
Enhancement: unify efs csi install chain

### PR DESCRIPTION
**Pull request by Phaow**
## Enhancement: unify efs csi install chain
- Expands current config steps supoort proxy/disconnect test clusters
- Use the new efs install chain unify efs csi driver install

### CODE REVIEW

**Comment by Phaow** [comment]
/pj-rehearse periodic-ci-openshift-aws-efs-csi-driver-operator-release-4.10-nightly-operator-e2e

**Comment by Phaow** [comment]
/pj-rehearse periodic-ci-openshift-aws-efs-csi-driver-operator-release-4.10-nightly-operator-e2e

**Comment by Phaow** [comment]
/pj-rehearse periodic-ci-openshift-aws-efs-csi-driver-operator-release-4.10-nightly-operator-e2e

**Comment by Phaow** [comment]
/pj-rehearse periodic-ci-openshift-aws-efs-csi-driver-operator-release-4.13-nightly-operator-e2e

**Comment by Phaow** [comment]
Hi @jsafrane @dobsonj , could you please help take a look when you get a chance? Thanks in advance!

**FYI**
I rehearsed `periodic-ci-openshift-aws-efs-csi-driver-operator-release-4.10-nightly-operator-e2e` and `periodic-ci-openshift-aws-efs-csi-driver-operator-release-4.13-nightly-operator-e2e` test jobs, 4.13 passed, 4.10 has 1 failed case.
The 4.10 job 1 failed case looks like flaky not related the enhancement.
```console
Failing invariants:

[sig-node] static pods should start after being created
```

**Comment by Phaow** [comment]
/pj-rehearse periodic-ci-openshift-aws-efs-csi-driver-operator-release-4.13-nightly-operator-e2e

**Comment by jsafrane** [comment]
/pj-rehearse periodic-ci-openshift-aws-efs-csi-driver-operator-release-4.11-nightly-operator-e2e
/pj-rehearse periodic-ci-openshift-aws-efs-csi-driver-operator-release-4.12-nightly-operator-e2e
/pj-rehearse periodic-ci-openshift-aws-efs-csi-driver-operator-release-4.14-nightly-operator-e2e
/pj-rehearse periodic-ci-openshift-aws-efs-csi-driver-operator-release-master-nightly-operator-e2e

**Comment by jsafrane** [comment]
/pj-rehearse pull-ci-openshift-aws-efs-csi-driver-operator-release-4.10-operator-e2e
/pj-rehearse pull-ci-openshift-aws-efs-csi-driver-operator-release-4.11-operator-e2e	
/pj-rehearse pull-ci-openshift-aws-efs-csi-driver-operator-release-4.12-operator-e2e	
/pj-rehearse pull-ci-openshift-aws-efs-csi-driver-operator-release-4.13-operator-e2e	
/pj-rehearse pull-ci-openshift-aws-efs-csi-driver-operator-release-4.14-operator-e2e	
/pj-rehearse pull-ci-openshift-aws-efs-csi-driver-operator-release-master-operator-e2e

**Comment by jsafrane** [comment]
/pj-rehearse pull-ci-openshift-aws-efs-csi-driver-operator-release-4.10-operator-e2e pull-ci-openshift-aws-efs-csi-driver-operator-release-4.11-operator-e2e pull-ci-openshift-aws-efs-csi-driver-operator-release-4.12-operator-e2e pull-ci-openshift-aws-efs-csi-driver-operator-release-4.13-operator-e2e pull-ci-openshift-aws-efs-csi-driver-operator-release-4.14-operator-e2e pull-ci-openshift-aws-efs-csi-driver-operator-release-master-operator-e2e

**Comment by jsafrane** [comment]
looks good to me, rehaersing a bit more. Feel free to lgtm when they look OK-ish
/approve

**Pull request merged**
