### PR TITLE
Add step to collect IBM Cloud resources

### PR DESCRIPTION
**Pull request by cjschaef**
Added a new step which will collect the created resources on IBM
Cloud during IPI installation to assist with debugging purposes.

### CODE REVIEW

**Review by staebler — COMMENTED** [review]
/lgtm
/approve
/hold for gather from tests

**Comment by cjschaef** [comment]
It looks like the shell install script for IBM Cloud CLI requires `sudo` to perform operations
```
 Superuser privileges are required to run this script.
/tmp/Bluemix_CLI/install: line 9: sudo: command not found
Install failed.
environment: line 17: ibmcloud: command not found
{"component":"entrypoint","error":"wrapped process failed: exit status 127","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-01-18T20:11:16Z"}
error: failed to execute wrapped command: exit status 127 
```
I'll see if/how that can be addressed for use in the CI.

**Comment by cjschaef** [comment]
@staebler Okay, I'm sorry for the mess in this PR, has been challenging to get all the necessary components setup and tested in the CI environment for this resource gather functionality.

But, it looks like things are working now as expected, and for now, all the data to help our VPC is being collected
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/25391/rehearse-25391-pull-ci-openshift-installer-release-4.11-e2e-ibmcloud/1485695186926309376/artifacts/e2e-ibmcloud/ipi-ibmcloud-gather-resources/artifacts/ibmcloud-gather-resources/

This should finally be ready for an actual review now.

**Pull request merged**
