### PR TITLE
Fixing kube-reporting-hive-master.yaml to use dockerfile from ocp-build-data

### PR DESCRIPTION
**Pull request by alvaroaleman**

### CODE REVIEW

**Comment by bentito** [comment]
We have a limitation with the Dockerfile that ART is configured to use builds a version of this java-based fork by curling brew packages that we manually build in PNC with Maven (and then mirror to brew).
^^ @jupierce  @timflannagan1

**Comment by jupierce** [comment]
@bentito is working on leveraging the CI_OPERATOR=true environment variable to allow us to use the same file in CI and ART.
/hold

**Comment by jupierce** [comment]
There is a catch-22 here. Hive depends on hadoop. hadoop has migrated to rhel8. This breaks hive's CI because it is dependent on rhel7 repos. We can't merge rhel8 changed without hive CI passing.
Force merging to break cycle.

**Comment by jupierce** [comment]
PR should get things working again: https://github.com/kube-reporting/hive/pull/47

**Pull request merged**
