### PR TITLE
medik8s/nhc: remove index usage, add release v0.5

### PR DESCRIPTION
**Pull request by slintes**
- remove old releases
- switch to bundle image and operator-sdk instead of operator workflow and index image (https://docs.ci.openshift.org/docs/how-tos/testing-operator-sdk-operators/#building-an-index-deprecated)
- add release-0.5 configs

### CODE REVIEW

**Comment by slintes** [comment]
/pj-rehearse ci/rehearse/medik8s/node-healthcheck-operator/main/4.13-openshift-e2e

**Comment by slintes** [comment]
/pj-rehearse  pull-ci-medik8s-node-healthcheck-operator-main-4.13-openshift-e2e

**Review by clobrano — APPROVED** [review]

**Pull request merged**
