### PR TITLE
[azure] add api lb rule backendpool check in mixed publish case

### PR DESCRIPTION
**Pull request by jinyunma**
In case of publish: Mixed + apiserver: External + ingress: Internal, api lb rule is created in external load balancer, master nodes should be added into its backendpool.
During https://issues.redhat.com//browse/OCPBUGS-38070 verification, post-check script is passed, but found that master nodes are not added into api lb rule's backendpool, so add missing checkpoint in post check.

### CODE REVIEW

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-azure-ipi-mixed-ingress-internal-arm-f2

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-multi-nightly-azure-ipi-mixed-ingress-internal-arm-f2

**Comment by jinyunma** [comment]
post check step `cucushift-installer-check-azure-publish-mixed` passed this time in [job periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-azure-ipi-mixed-ingress-internal-arm-f2](https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/55807/rehearse-55807-periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-azure-ipi-mixed-ingress-internal-arm-f2/1826183767413231616/artifacts/azure-ipi-mixed-ingress-internal-arm-f2/cucushift-installer-check-azure-publish-mixed/) 

For 4.17 job, because PR in bug OCPBUGS-38070 has not been landed into accepted nightly build, API LB rule is not created in external LB on current nightly build, so the check could not be performed.

/pj-rehearse ack

@jianlinliu could you help to review again? thanks.

**Comment by jianlinliu** [comment]
> For 4.17 job, because PR in bug OCPBUGS-38070 has not been landed into accepted nightly build, API LB rule is not created in external LB on current nightly build, so the check could not be performed.

I glanced on the bug, OCPBUGS-38070 will lead the 4.17 installation failed, because api backend pool did not add master nodes into it, right?

**Comment by jinyunma** [comment]
> I glanced on the bug, OCPBUGS-38070 will lead the 4.17 installation failed, because api backend pool did not add master nodes into it, right?

Installation passed, because we always set up proxy server for publish: Mixed configuration, and API LB rule is also created in internal load balancer. But cluster could not be accessed from outside of cluster without proxy when publish: Mixed + apiserver: External + Ingress: Internal, because api backend pool did not add master nodes into it.

**Comment by jianlinliu** [comment]
> > I glanced on the bug, OCPBUGS-38070 will lead the 4.17 installation failed, because api backend pool did not add master nodes into it, right?
> 
> Installation passed, because we always set up proxy server for publish: Mixed configuration, and API LB rule is also created in internal load balancer. But cluster could not be accessed from outside of cluster without proxy when publish: Mixed + apiserver: External + Ingress: Internal, because api backend pool did not add master nodes into it.

Ah, got it. If that, we can not catch the OCPBUGS-38070 bug in our daily ci jobs, right?

**Comment by jinyunma** [comment]
> we can not catch the OCPBUGS-38070 bug in our daily ci jobs, right?

We can catch the original issue in OCPBUGS-38070, 
1. publish: Mixed + apiserver: External + ingress: Internal ->  api lb rule is not created in external lb.
2. publish: Mixed + apiserver: Internal + ingress: External -> api dns should not be created in public dns zone

Above two issues are caught by our post check script.

During pre-merge test with PR in OCPBUGS-38070 is merged, above two issues are fixed, but in scenario1, although api lb rule is created in external lb, master nodes are not added into its backendpool, so I changed bug back to ASSIGNED, this issue could not be caught by post check script, and add related checkpoint here.

**Comment by jianlinliu** [comment]
> During pre-merge test with PR in OCPBUGS-38070, above two issues are fixed, but in scenario1, although api lb rule is created in external lb, master nodes are not added into its backendpool, so I changed bug back to ASSIGNED, this issue could not be caught by post check script, and add related checkpoint here

Thanks for the details. So sounds once the fix of OCPBUGS-38070 landed into nightly build, the newly fixed check script can catch the issue of "master nodes are not added into its backendpool".

/lgtm

**Pull request merged**
