### PR TITLE
[vsphere] installation chain for ipi on vsphere in a disconnected network

### PR DESCRIPTION
**Pull request by jinyunma**
Add installation chain for ipi on vsphere in a disconnected network.

### CODE REVIEW

**Comment by petr-muller** [comment]
/uncc @petr-muller @smarterclayton 

You need someone from TRT to approve the new job being added as a release job. They will likely want to see a passing rehearsal. That said, it would be probably better approach to build these new jobs somewhere separate from release jobs, test and debug them there, merge the step registry content (workflows etc) separately, and only add new release jobs once the workflows exist.

**Comment by jinyunma** [comment]
@petr-muller thanks for the information, the purpose to add a new job is just to verify new installation chain, once the installation is passed, will remove related workflow and jobs before merging. This installation chain will be used later for QE cucushift test job. Maybe I could move to that job for verification.

I have another question in this PR, new installation chain will mirror image to local registry and deploy cluster in a disconnected network, I need to add pull secret of local image registry for cluster profile `vsphere-discon` so that pull-secrets can be directly used instead of updating manually in config step . Currently, cluster profile `vsphere-discon` use same pull-secrets as `vsphere`. As my understanding, I should update `ci-secret-bootstrap` config to add new section for `vsphere-discon` and append this pull secret.

Per doc [Providing Credentials](https://docs.ci.openshift.org/docs/how-tos/adding-a-cluster-profile/#providing-credentials), seems need to add this new secret in Vault under correct namespace and name, is it right? But how to map the key in Vault and pull-secret item in `ci-secret-bootstrap` config, do you have any suggestion or any example that I can refer to?

**Comment by petr-muller** [comment]
Sorry, I do not understand much from that description. What is local registry (local to what?). How is a pull secret related to a cluster profile (cluster profile is a collection of secrets belonging to a cloud platform account, so I would not say a pull secret is related to cluster profile).

Note that a custom secret does not necessarily need to be part of the cluster profile secrets, it can be passed in via a custom credential: https://docs.ci.openshift.org/docs/how-tos/adding-a-new-secret-to-ci/

Please ping `@dptp-helpde

**Comment by jinyunma** [comment]
/cc @jianlinliu @gpei for review
Job is failed at the step of post to destroy cluster and got 503 Service Unavailable known issue, should not be related with this PR. Disconnected IPI installation is successful.

**Pull request merged**
