### PR TITLE
Revert "[openshift-docs] - Adjusting validate-portal to ensure exit 1 on child process Asciidoctor failures"

### PR DESCRIPTION
**Pull request by aireilly**
Reverts openshift/release#52544

### CODE REVIEW

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-no-1.6-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-no-1.6-validate-portal

**Review by gabriel-rh — APPROVED** [review]
LGTM

**Pull request merged**
