### PR TITLE
periodics: add vsphere upgrade tests

### PR DESCRIPTION
**Pull request by vrutkovs**
Ref: https://issues.redhat.com/browse/OTA-308

### CODE REVIEW

**Review by droslean — APPROVED** [review]

**Comment by droslean** [comment]
/hold

Holding if you wanna wait for the rehearsals....

**Comment by vrutkovs** [comment]
Right, we need https://github.com/openshift/origin/pull/25913 and https://github.com/openshift/origin/pull/25914 to make service LB tests pass anyway

**Comment by vrutkovs** [comment]
/hold cancel

Ready for review. 4.7 -> 4.8 is fully ready, others need LB fix backport

**Review by droslean — APPROVED** [review]

**Pull request merged**
