### PR TITLE
kni: nrop: kickoff branch 4.18

### PR DESCRIPTION
**Pull request by shajmakh**
branch out 4.17 from main and redirect main to 4.18.

### CODE REVIEW

**Comment by shajmakh** [comment]
/hold 
for branching the relevant projects

**Comment by ffromani** [comment]
/hold

better to fix all the repos before

**Comment by shajmakh** [comment]
/pj-rehearse pull-ci-openshift-kni-numaresources-operator-release-4.17-images

**Comment by ffromani** [comment]
/pj-rehearse periodic-ci-openshift-kni-numaresources-operator-release-4.17-ci-must-gather-e2e

**Comment by ffromani** [comment]
interesting, the `images` failure is legit

**Comment by shajmakh** [comment]
build-topics was missing. Let's wait for the ci verification

**Comment by ffromani** [comment]
/pj-rehearse periodic-ci-openshift-kni-numaresources-operator-main-ci-must-gather-e2e

**Review by ffromani — APPROVED** [review]
/lgtm

**Comment by ffromani** [comment]
> /pj-rehearse periodic-ci-openshift-kni-numaresources-operator-main-ci-must-gather-e2e

before this, I fixed the tags on quay.io which prevented the test to start

**Comment by shajmakh** [comment]
the job passed before looks like an infra issue:
`Init container clonerefs not ready: (state: running) Init container initupload not ready: (state: waiting, reason: "PodInitializing", message: "") Init container place-entrypoint not ready: (state: waiting, reason: "PodInitializing", message: "")`

/retest config

**Pull request merged**
