### PR TITLE
Enable parallel tests for openstack upi

### PR DESCRIPTION
**Pull request by adduarte**

### CODE REVIEW

**Comment by mandre** [comment]
It seems like the full parallel test suite ran as expected however the failures were not reported correctly.

Run template e2e-openstack-upi - e2e-openstack-upi container test failed.

https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/9091/rehearse-9091-pull-ci-openshift-installer-master-e2e-openstack-upi/10

Likely the `test` container returned an unexpected error status.

Normally the test results should look more like:
https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/logs/release-openshift-ocp-installer-e2e-openstack-4.5/689

**Comment by adduarte** [comment]
running the TESTCOMMAND from within a bash function probably got in the way of the correct return code

**Comment by pierreprinetti** [comment]
Cool, now tests correctly fail! :grimacing: 

/lgtm
/retest
/hold

**Pull request merged**
