### PR TITLE
Test running jobs on build01

### PR DESCRIPTION
**Pull request by alvaroaleman**

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/hold
this should not get merged

**Comment by stevekuznetsov** [comment]
/test pj-rehearse
/retest

wtf those are old results

**Comment by stevekuznetsov** [comment]
```
  Normal   BackOff         4m44s (x110 over 29m)  kubelet, ip-10-0-171-147.ec2.internal  Back-off pulling image "registry.svc.ci.openshift.org/ocp/4.5@sha256:e93649a41b414eefabb44b628854663e079084675f8b1e74e07c4a634f496166"
```

:(

**Comment by stevekuznetsov** [comment]
The imported tag is `Local`:

```
$ oc --context build01 --namespace ocp get is 4.5 -o "jsonpath={.spec.tags[?(@.name==\"cli\")].referencePolicy.type}"
Local
```

However, the reference still isn't:

```
$ oc --context build01 --namespace ocp get is 4.5 -o "jsonpath={.spec.tags[?(@.name==\"cli\")].from.kind}"
DockerImage
$ oc --context build01 --namespace ocp get is 4.5 -o "jsonpath={.spec.tags[?(@.name==\"cli\")].from.name}"
registry.svc.ci.openshift.org/ocp/4.5@sha256:e93649a41b414eefabb44b628854663e079084675f8b1e74e07c4a634f496166
```

The namespace stream is source:

```
$ oc --context build01 --namespace ci-op-221pchh5 get is stable -o "jsonpath={.spec.tags[?(@.name==\"cli\")].referencePolicy.type}"
Source
```

However, it points to the ImageStreamImage:

```
$ oc --context build01 --namespace ci-op-221pchh5 get is stable -o "jsonpath={.spec.tags[?(@.name==\"cli\")].from.kind}"
ImageStreamImage
$ oc --context build01 --namespace ci-op-221pchh5 get is stable -o "jsonpath={.spec.tags[?(@.name==\"cli\")].from.name}"
4.5@sha256:e93649a41b414eefabb44b628854663e079084675f8b1e74e07c4a634f496166
```

However, the image for the container resolved to the api.ci field:

```
$ oc --context build01 --namespace ci-op-221pchh5 get pod release-latest -o jsonpath={.spec.containers[0].image}
registry.svc.ci.openshift.org/ocp/4.5@sha256:e93649a41b414eefabb44b628854663e079084675f8b1e74e07c4a634f496166
```

So, we should change `ci-operator` to pass a resolved digest for the local registry for the image, instead of `ImageStream:ImageStreamTag`

**Comment by stevekuznetsov** [comment]
Fix: https://github.com/openshift/ci-tools/pull/1158

**Comment by hongkailiu** [comment]
/retest

Verifying if the problem is still there.

**Pull request closed without merging**
