### PR TITLE
ComplianceAsCode/content CI: upgrade to 4.11

### PR DESCRIPTION
**Pull request by jhrozek**
Let's use the latest in-development release

### CODE REVIEW

**Comment by jhrozek** [comment]
CaC PRs:
 - https://github.com/ComplianceAsCode/content/pull/8996
 - https://github.com/ComplianceAsCode/content/pull/8995

**Comment by jhrozek** [comment]
The required PRs merged, let's retest
/test pj-rehearse

**Comment by jhrozek** [comment]
/test pj-rehearse
timeouts galore

**Comment by jhrozek** [comment]
/test pj-rehearse
none of the clusters installed

**Comment by jhrozek** [comment]
cluster install seems to be entirely foobar
/test pj-rehearse

**Comment by jhrozek** [comment]
I'm an idiot, we bumped the minimal go requirements for the e2e tests and I forgot to change the version here. Fixed.

**Comment by rhmdnd** [comment]
/cancel hold

Removing the hold label since we've merged the required fixes and CI is green.

**Pull request merged**
