### PR TITLE
SPLAT-960: enabling periodics for vSphere 8 on 4.12

### PR DESCRIPTION
**Pull request by rvanderp3**

### CODE REVIEW

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.12-e2e-vsphere-8-ovn-csi
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.12-e2e-vsphere-8-ovn
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.12-e2e-vsphere-8-ovn-upi

**Review by vrutkovs — APPROVED** [review]
/lgtm

**Pull request merged**
