### PR TITLE
stackrox: master: use automation-flavor for OCP 4

### PR DESCRIPTION
**Pull request by gavin-stackrox**
This PR is a retry of #44623 to switch OCP 4 CI clusters to use automation-flavors for install. The original PR failed due to a hard limit of 1500 IAM policy bindings per GCP project, With 20 bindings required per cluster this meant a limit of < 75 clusters which did not meet demand at branch time for release. This PR uses `credentialsMode: Passthrough` to limit the required bindings to 7 which should provide enough clusters (or we need to test less).

## Testing

- [x] rehearse with automation-flavors snapshot passed (apart from known flakes)

### CODE REVIEW

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-4-10-operator-e2e-tests pull-ci-stackrox-stackrox-master-ocp-4-13-qa-e2e-tests pull-ci-stackrox-stackrox-release-x.y-ocp-4-10-ui-e2e-tests pull-ci-stackrox-stackrox-release-4.3-ocp-4-13-compliance-e2e-tests

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-4-10-operator-e2e-tests pull-ci-stackrox-stackrox-master-ocp-4-13-qa-e2e-tests pull-ci-stackrox-stackrox-release-x.y-ocp-4-10-ui-e2e-tests pull-ci-stackrox-stackrox-release-4.3-ocp-4-13-compliance-e2e-tests

**Review by BradLugo — APPROVED** [review]
/lgtm

**Pull request merged**
