### PR TITLE
Testing quarkus on ocp 4.16 on aws

### PR DESCRIPTION
**Pull request by smpsgill**

### CODE REVIEW

**Comment by rsvoboda** [comment]
@Simranpal are the failures on your radar? cc @fedinskiy

**Comment by fedinskiy** [comment]
@rsvoboda these failures are from three weeks ago and were fixed here:
https://github.com/quarkus-qe/quarkus-openshift-interop/pull/12
(I suppose we after https://github.com/quarkus-qe/quarkus-openshift-interop/pull/13 we should not see them anymore even without a fix)

**Comment by Simranpal** [comment]
@fedinskiy @rsvoboda Closing this PR. This was just a test to compare against ibm cloud two weeks ago.

**Pull request closed without merging**
