### PR TITLE
remove verify-deps job for library-go repo

### PR DESCRIPTION
**Pull request by vareti**
This PR aims to remove verify-deps CI job for [library-go](https://github.com/openshift/library-go) repo.

[verify-deps](https://github.com/openshift/library-go/blob/b25329afa1ae9d7dfcd7c3d8d19940d7bb87afdd/alpha-build-machinery/make/targets/openshift/deps.mk#L20) does not support go modules. As library-go is in the process of migrating to go modules, disabling this CI job temporarily until `verify-deps` is supported by make targets.

ref https://github.com/openshift/library-go/pull/631#issuecomment-564014885

### CODE REVIEW

**Comment by sttts** [comment]
I miss the why? Why do we remove it? Please give context in the PR description.

**Comment by vareti** [comment]
> I miss the why. Why do we remove it? Please give context in the PR description.

I updated the PR description

**Pull request merged**
