### PR TITLE
[azure] add azure-ipi-usertags-techpreview workflow

### PR DESCRIPTION
**Pull request by jinyunma**
1. add azure-ipi-usertags-techpreview workflow
2.  add 4.13/4.13 amd64/arm64 ci jobs

### CODE REVIEW

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.13-installer-rehearse-azure

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.13-installer-rehearse-azure

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.13-installer-rehearse-azure

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.13-installer-rehearse-azure

**Comment by jinyunma** [comment]
**4.12 job periodic-ci-openshift-verification-tests-master-installer-rehearse-4.13-installer-rehearse-azure** 
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/37866/rehearse-37866-periodic-ci-openshift-verification-tests-master-installer-rehearse-4.13-installer-rehearse-azure/1641399961692147712

tags:
```
# az group show --name ci-op-183hzqdr-f609f-cc6fh-rg --query tags
{
  "KEYQE7": "value.7_test",
  "Key-5": "value_5",
  "Key3Test": "1TestValue1",
  "TestKey-1": "qe@Value+4",
  "a_key_6": "value=6+a",
  "key-length-128-abcs123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789": "false",
  "key-length-128-defs123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789": "val-length-256-as123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789",
  "key828": "val-length-256-as123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789s123456789",
  "kubernetes.io_cluster.ci-op-183hzqdr-f609f-cc6fh": "owned",
  "lastKey": "value?-last",
  "openshift_creationDate": "2023-03-30T11:34:01.633291+00:00",
  "qeKey10": "Value<test>10"
}
```
step cucushift-installer-check-control-plane-machine-name
```
control_plane_nodes_count: 3
excepted_count: 3
INFO: All control plane machine names are expected.
Machines:
ci-op-183hzqdr-f609f-cc6fh-master-0   Running   Standard_D8s_v3   southcentralus   1     34m   ci-op-183hzqdr-f609f-cc6fh-master-0   azure:///subscriptions/53b8f551-f0fc-4bea-8cba-6d1fefd54c8a/resourceGroups/ci-op-183hzqdr-f609f-cc6fh-rg/providers/Microsoft.Compute/virtualMachines/ci-op-183hzqdr-f609f-cc6fh-master-0   Running
ci-op-183hzqdr-f609f-cc6fh-master-1   Running   Standard_D8s_v3   southcentralus   2     34m   ci-op-183hzqdr-f609f-cc6fh-master-1   azure:///subscriptions/53b8f551-f0fc-4bea-8cba-6d1fefd54c8a/resourceGroups/ci-op-183hzqdr-f609f-cc6fh-rg/providers/Microsoft.Compute/virtualMachines/ci-op-183hzqdr-f609f-cc6fh-master-1   Running
ci-op-183hzqdr-f609f-cc6fh-master-2   Running   Standard_D8s_v3   southcentralus   3     34m   ci-op-183hzqdr-f609f-cc6fh-master-2   azure:///subscriptions/53b8f551-f0fc-4bea-8cba-6d1fefd54c8a/resourceGroups/ci-op-183hzqdr-f609f-cc6fh-rg/providers/Microsoft.Compute/virtualMachines/ci-op-183hzqdr-f609f-cc6fh-master-2   Running
```

**4.12 job: periodic-ci-openshift-verification-tests-master-installer-rehearse-4.12-installer-rehearse-azure**
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/37866/rehearse-37866-periodic-ci-openshift-verification-tests-master-installer-rehearse-4.12-installer-rehearse-azure/1641404638722789376

tags:
```
# az group show --name ci-op-5v7c016q-16d46-hczxp-rg --query tags
{
  "kubernetes.io_cluster.ci-op-5v7c016q-16d46-hczxp": "owned"
}
```

**Comment by jianlinliu** [comment]
cc @liangxia for review.

**Pull request merged**
