### PR TITLE
SDN-5457: Move kube-proxy image build from openshift/sdn to openshift/kubernetes

### PR DESCRIPTION
**Pull request by danwinship**
Stops building+promoting kube-proxy from openshift/sdn and starts building+promoting it from openshift/kubernetes. Since there's no longer any point to running CI in openshift/sdn in master (no images, and the remaining CI no longer passes), I removed the master/4.18/4.19 sdn configs entirely.

The last commit adds a step to the k8s-e2e-gcp-ovn and k8s-e2e-aws jobs to make them run `test-kube-proxy.sh` too

### CODE REVIEW

**Comment by danwinship** [comment]
/pj-rehearse pull-ci-openshift-kubernetes-master-images pull-ci-openshift-kubernetes-master-okd-scos-images pull-ci-openshift-kubernetes-master-e2e-gcp

**Comment by danwinship** [comment]
/pj-rehearse pull-ci-openshift-kubernetes-master-images pull-ci-openshift-kubernetes-master-okd-scos-images pull-ci-openshift-kubernetes-master-e2e-gcp

**Comment by danwinship** [comment]
/pj-rehearse pull-ci-openshift-kubernetes-master-images pull-ci-openshift-kubernetes-master-e2e-gcp

**Comment by danwinship** [comment]
/pj-rehearse pull-ci-openshift-kubernetes-master-images pull-ci-openshift-kubernetes-master-e2e-gcp

**Comment by danwinship** [comment]
/pj-rehearse pull-ci-openshift-kubernetes-master-k8s-e2e-gcp-ovn

**Comment by danwinship** [comment]
/pj-rehearse pull-ci-openshift-kubernetes-master-k8s-e2e-gcp-ovn

**Comment by danwinship** [comment]
OK, the new kube-proxy-test step shows up as a [separate step in the results](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/58505/rehearse-58505-pull-ci-openshift-kubernetes-master-k8s-e2e-gcp-ovn/1854190008248832000/artifacts/k8s-e2e-gcp-ovn/openshift-kubernetes-e2e-kube-proxy-test/) and will [cause the test to fail if it fails](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/58505/rehearse-58505-pull-ci-openshift-kubernetes-master-k8s-e2e-gcp-ovn/1854155184289091584).

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Pull request merged**
