### PR TITLE
gcp ccm

### PR DESCRIPTION
**Pull request by huali9**
add the workflow "cucushift-installer-rehearse-gcp-ipi-ccm" and provision & deprovision chains, similar as https://github.com/openshift/release/pull/29205

@jhou1 @sunzhaohua2 @miyadav Please help to take a look, thanks!

### CODE REVIEW

**Comment by huali9** [comment]
all tests passed!
@jhou1 @sunzhaohua2 @miyadav Please help to take a look, thanks!

**Comment by huali9** [comment]
just rebase the code. @jhou1 @sunzhaohua2 @miyadav @jianlinliu PTAL again, thanks!

**Comment by jianlinliu** [comment]
seem like no rehearse job to validate the new workflow

**Comment by huali9** [comment]
> seem like no rehearse job to validate the new workflow

Already validated the new workflow yesterday and all tests passed. So I don't think it's necessary to re-validate it and waste resources, when rebasing the code, I accept the changes of the master branch, and it won't cause conflicts again, WDYT?
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/29497/rehearse-29497-periodic-ci-openshift-verification-tests-master-installer-rehearse-4.10-installer-rehearse-gcp/1536961991074123776

**Pull request merged**
