### PR TITLE
[HCO] move to OCP/OKD 4.14 on main branch

### PR DESCRIPTION
**Pull request by tiraboschi**

### CODE REVIEW

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-hyperconverged-cluster-operator-main-hco-e2e-image-index-sno-aws
/pj-rehearse pull-ci-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-azure
/pj-rehearse pull-ci-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-gcp
/pj-rehearse pull-ci-hyperconverged-cluster-operator-main-hco-e2e-upgrade-index-aws 
/pj-rehearse pull-ci-hyperconverged-cluster-operator-main-hco-e2e-upgrade-index-azure
/pj-rehearse pull-ci-hyperconverged-cluster-operator-main-hco-e2e-upgrade-index-sno-azure
/pj-rehearse pull-ci-hyperconverged-cluster-operator-main-hco-e2e-upgrade-prev-index-aws
/pj-rehearse pull-ci-hyperconverged-cluster-operator-main-hco-e2e-upgrade-prev-index-sno-aws
/pj-rehearse pull-ci-hyperconverged-cluster-operator-main-okd-hco-e2e-image-index-aws
/pj-rehearse pull-ci-hyperconverged-cluster-operator-main-okd-hco-e2e-upgrade-index-aws
/pj-rehearse pull-ci-hyperconverged-cluster-operator-main-okd-hco-e2e-upgrade-index-gcp

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-image-index-sno-aws
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-azure
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-gcp
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-index-aws
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-index-azure
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-index-sno-azure
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-prev-index-aws
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-prev-index-sno-aws
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-image-index-aws
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-upgrade-index-aws
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-upgrade-index-gcp

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-azure

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-gcp

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-index-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-index-azure

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-index-sno-azure

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-prev-index-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-prev-index-sno-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-image-index-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-upgrade-index-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-upgrade-index-gcp

**Comment by tiraboschi** [comment]
/pj-rehearse periodic-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-deploy-nightly-main-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-azure

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-gcp

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-gcp

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-azure

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-gcp

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-azure

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-azure

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-gcp

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-azure

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-azure

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-gcp

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-image-index-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-image-index-gcp

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-image-index-sno-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-azure

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-index-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-index-azure

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-index-sno-azure

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-prev-index-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-image-index-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-upgrade-index-aws

**Review by nunnatsa — APPROVED** [review]
/lgtm

**Comment by tiraboschi** [comment]
/pj-rehearse periodic-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-deploy-nightly-main-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-azure

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-gcp

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-operator-sdk-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-operator-sdk-gcp

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-operator-sdk-sno-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-sno-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-prev-operator-sdk-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-prev-operator-sdk-sno-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-prev-operator-sdk-sno-azure

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-operator-sdk-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-operator-sdk-gcp

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-upgrade-operator-sdk-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-upgrade-operator-sdk-gcp

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-gcp

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-gcp

**Comment by tiraboschi** [comment]
/pj-rehearse periodic-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-deploy-nightly-main-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-azure

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-operator-sdk-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-operator-sdk-gcp

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-operator-sdk-sno-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-azure

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-sno-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-sno-azure

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-prev-operator-sdk-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-prev-operator-sdk-sno-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-operator-sdk-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-upgrade-operator-sdk-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-upgrade-operator-sdk-gcp

**Comment by tiraboschi** [comment]
/pj-rehearse periodic-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-deploy-nightly-main-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-azure

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-operator-sdk-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-operator-sdk-gcp

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-operator-sdk-sno-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-sno-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-prev-operator-sdk-sno-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-operator-sdk-aws

**Comment by tiraboschi** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-upgrade-operator-sdk-aws

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-image-index-gcp pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-image-index-aws pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-image-index-aws pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-image-index-azure

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-prev-index-aws pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-index-azure pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-prev-index-azure pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-index-aws pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-upgrade-operator-sdk-aws pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-aws pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-operator-sdk-sno-aws pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-azure periodic-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-deploy-nightly-main-aws pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-operator-sdk-gcp pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-operator-sdk-aws pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-prev-operator-sdk-aws pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-operator-sdk-sno-aws pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-prev-operator-sdk-sno-aws pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-operator-sdk-aws

**Comment by tiraboschi** [comment]
closing for https://github.com/openshift/release/pull/42143

**Pull request closed without merging**
