### PR TITLE
USHIFT-1396: Remove post sos report step from metal-tests

### PR DESCRIPTION
**Pull request by pacevedom**

### CODE REVIEW

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-metal-tests

**Comment by pacevedom** [comment]
/pj-rehearse ack
sos reports were not executed after the last step in test workflow.
/cc @pmtk @copejon @dhellmann

**Comment by pmtk** [comment]
/lgtm
/hold

I think we need https://github.com/openshift/microshift/pull/2025 first?

**Comment by dhellmann** [comment]
This looks OK. We can merge a few of the changes out of order.

/hold cancel

**Pull request merged**
