### PR TITLE
ocm - Use common Framework action (GRC)

### PR DESCRIPTION
**Pull request by dhaiducek**
Related updates:
- https://github.com/stolostron/cert-policy-controller/pull/174
- https://github.com/stolostron/config-policy-controller/pull/330
- https://github.com/stolostron/governance-policy-propagator/pull/242
- https://github.com/stolostron/governance-policy-spec-sync/pull/143
- https://github.com/stolostron/governance-policy-status-sync/pull/142
- https://github.com/stolostron/governance-policy-template-sync/pull/25
- https://github.com/stolostron/iam-policy-controller/pull/143

### CODE REVIEW

**Comment by dhaiducek** [comment]
Blocked by:
- https://github.com/openshift/ci-tools/pull/3005

**Review by mprahl — APPROVED** [review]

**Review by mprahl — APPROVED** [review]

**Review by mprahl — APPROVED** [review]

**Pull request merged**
