### PR TITLE
Add cert-manager to build05

### PR DESCRIPTION
**Pull request by bear-redhat**

### CODE REVIEW

**Review by hongkailiu — COMMENTED** [review]
1. Include https://github.com/openshift/release/commit/406d4336b0cc1729873cdd59a65017fbd5b8f69e for b05 in this PR.

2. We will talk about this: https://github.com/openshift/release/commit/5fbf0e9812d482048babfe745ff39f6fcded5429#diff-301b205d3c9a1080eca2683ec32ae3ecb0cde0bbaa8c806827dfdedabb30d3ce

---

Update:
2.1 Back up the current config.imageregistry.operator.openshift.io/cluster as json/yaml (the whole object)
2.2 Leave only the customized part of the object and apply it TWICE and check the one on the cluster if it still has the whole thing
2.3 Push the customized part to this PR as we did for b04

**Comment by bear-redhat** [comment]
The PR has been tested manually in build05
1. apply everything in `common_cert_manager`
2. apply `cert-manager/cert-manager_deployment.yaml`
3. apply `cert-manager/cert-issuer-staging_clusterissuer.yaml` and `cert-manager/cert-issuer_clusterissuer.yaml`
4. steal `-n cert-manager get secret cert-issuer` from `build03` and manually add to `build05`
5. apply `cert-manager/registry-build05_certificate.yaml`
6. follow https://github.com/openshift/release/blob/master/clusters/build-clusters/build03/openshift-image-registry/domain.md

**Pull request merged**
