### PR TITLE
SPLAT-1250: Set IPAM version to v1alpha1 for OCP 4.15 nightlies.

### PR DESCRIPTION
**Pull request by vr4manta**
[SPLAT-1250](https://issues.redhat.com/browse/SPLAT-1250)

## Changes
- Updated OCP 4.15 nightly to include IPAM version of v1alpha1

### CODE REVIEW

**Comment by vr4manta** [comment]
/assign @dgoodwin 
Ready for review.  Thanks!

**Review by vrutkovs — APPROVED** [review]
/approve

**Pull request merged**
