### PR TITLE
openshift-cincinnati-operator-master.yaml: remove OPERAND_IMAGE, bump Cincinnati

### PR DESCRIPTION
**Pull request by vrutkovs**
Remove `OPERAND_IMAGE` env var - its no longer being used.

Update deployed Cincinnati to include manifestref fixes for operator e2e

### CODE REVIEW

**Comment by vrutkovs** [comment]
/hold

waiting for rehearsals

**Review by wking — APPROVED** [review]
/lgtm

**Review by wking — APPROVED** [review]
/lgtm

**Comment by vrutkovs** [comment]
/retest

Not sure why this failed - probably error during initial scraping? Unfortunately we don't have pod logs during tests (I have a commit to improve that)

**Comment by vrutkovs** [comment]
Still not sure why it fails - https://github.com/openshift/cincinnati-operator/pull/140 would allow us to collect more info though
/hold cancel

**Pull request merged**
