### PR TITLE
Update var for dev portal

### PR DESCRIPTION
**Pull request by jinqi7**

### CODE REVIEW

**Comment by jinqi7** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests-periodic

**Comment by jinqi7** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests-periodic

**Comment by jinqi7** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests-periodic

**Review by kasemAlem — APPROVED** [review]

**Comment by kasemAlem** [comment]
LGTM

**Pull request merged**
