### PR TITLE
oadp: bump master golang to 1.19

### PR DESCRIPTION
**Pull request by kaovilai**

### CODE REVIEW

**Comment by weshayutin** [comment]
@kaovilai so we saw security issues for anything prior to 1.19.4 any chance we can try >= 1.19.4?

**Comment by rayfordj** [comment]
> @kaovilai so we saw security issues for anything prior to 1.19.4 any chance we can try >= 1.19.4?

+1 
FWIW, downstream is already using go 1.19 builders

**Review by rayfordj — APPROVED** [review]
/lgtm
Thanks, @kaovilai !

**Comment by kaovilai** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-master-4.9-operator-e2e-aws

**Comment by weshayutin** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-master-4.9-operator-e2e-gcp

**Comment by kaovilai** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-master-4.11-images

/pj-rehearse pull-ci-openshift-oadp-operator-master-4.9-operator-e2e-gcp

**Comment by kaovilai** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-master-4.11-images

/pj-rehearse pull-ci-openshift-oadp-operator-master-4.9-operator-e2e-gcp

**Review by weshayutin — APPROVED** [review]

**Pull request merged**
