### PR TITLE
Revert "Use operator-registry from ocp:4.5 to unlock CI"

### PR DESCRIPTION
**Pull request by yuvalturg**
This reverts the following commits:
ef1fefd7f1313830640920742c02ba9d789c20a3
d5c85a461291e9c0797a605f2b56a32a9e58b372

### CODE REVIEW

**Comment by yuvalturg** [comment]
/override ci/rehearse/kubevirt/hyperconverged-cluster-operator/master/hco-e2e-azure
/override ci/rehearse/kubevirt/hyperconverged-cluster-operator/master/hco-e2e-upgrade-azure
/override ci/rehearse/kubevirt/hyperconverged-cluster-operator/master/hco-e2e-upgrade-prev-azure

**Review by tiraboschi — CHANGES_REQUESTED** [review]
This is not enough by itself, we have also to revert https://github.com/openshift/release/pull/11383

Or simply change all the 4.5 ref to 4.6 ones.

**Comment by yuvalturg** [comment]
> This is not enough by itself, we have also to revert #11383
> 
> Or simply change all the 4.5 ref to 4.6 ones.



> This is not enough by itself, we have also to revert #11383
> 
> Or simply change all the 4.5 ref to 4.6 ones.

Done

**Review by tiraboschi — APPROVED** [review]

**Pull request closed without merging**
