### PR TITLE
Add zstream config for fuse

### PR DESCRIPTION
**Pull request by smpsgill**

### CODE REVIEW

**Comment by Simranpal** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.15-lp-interop-jboss-fuse-interop-ibmcloud

**Comment by Simranpal** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.15-lp-interop-jboss-fuse-interop-ibmcloud

**Comment by Simranpal** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.15-lp-interop-jboss-fuse-interop-ibmcloud

**Comment by Simranpal** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.15-lp-interop-jboss-fuse-interop-ibmcloud

**Comment by Simranpal** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.15-lp-interop-jboss-fuse-interop-ibmcloud periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.16-lp-interop-jboss-fuse-interop-ibmcloud

**Comment by Simranpal** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.15-lp-interop-jboss-fuse-interop-ibmcloud

**Comment by Simranpal** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.15-lp-interop-jboss-fuse-interop-ibmcloud

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
