### PR TITLE
ci-operator/*: refactor cri-o CI

### PR DESCRIPTION
**Pull request by sohankunkerkar**
co-authored by @wgahnagl

### CODE REVIEW

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-sohankunkerkar-cri-o-ci-refactor-periodics-setup-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-sohankunkerkar-cri-o-ci-refactor-periodics-setup-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-sohankunkerkar-cri-o-ci-refactor-periodics-setup-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-sohankunkerkar-cri-o-ci-refactor-periodics-setup-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse periodic-ci-sohankunkerkar-cri-o-ci-refactor-periodics-setup-fedora-periodic

**Comment by sohankunkerkar** [comment]
/pj-rehearse pull-ci-sohankunkerkar-cri-o-ci-refactor-ci-cgroupv2-e2e-crun

**Comment by sohankunkerkar** [comment]
/pj-rehearse pull-ci-sohankunkerkar-cri-o-ci-refactor-ci-rhel-e2e

**Comment by sohankunkerkar** [comment]
/pj-rehearse pull-ci-sohankunkerkar-cri-o-ci-refactor-ci-rhel-critest

**Comment by sohankunkerkar** [comment]
/pj-rehearse pull-ci-sohankunkerkar-cri-o-ci-refactor-ci-rhel-e2e

**Comment by sohankunkerkar** [comment]
/pj-rehearse pull-ci-sohankunkerkar-cri-o-ci-refactor-ci-rhel-e2e

**Comment by haircommander** [comment]
excellent clean up @wgahnagl @sohankunkerkar 

/lgtm

**Pull request merged**
