### PR TITLE
CFE-182: Add gcp to external-dns-operator ci pipeline

### PR DESCRIPTION
**Pull request by Elbehery**
This PR adds gcp step in the operator ci pipeline

### CODE REVIEW

**Comment by lmzuccarelli** [comment]
@Elbehery - Overall looks good. Any reasons why it's failing the tests generated-config and ci-operator-config-metadata ?

**Comment by lmzuccarelli** [comment]
Should there also be a openshift-external-dns-operator-release-4.10.yaml ?

**Comment by Elbehery** [comment]
> @Elbehery - Overall looks good. Any reasons why it's failing the tests generated-config and ci-operator-config-metadata ?

@lmzuccarelli yes I need to fix that, I am working on it now 👍🏽

**Comment by alebedev87** [comment]
GCP helper was not tested manually, that's why the rehearsal fails. This PR fixes GCP helper: https://github.com/openshift/external-dns-operator/pull/76

**Pull request merged**
