### PR TITLE
Add master node outage chaos scenario

### PR DESCRIPTION
**Pull request by chaitanyaenr**
This adds a new workflow to run master node outage to understand and improve the stability and performance at load.

### CODE REVIEW

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-cloud-tests-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-cloud-tests-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-cloud-tests-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-cloud-tests-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-cloud-tests-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-cloud-tests-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-cloud-tests-nightly-krkn-hub-cloud-api-tests

**Comment by paigerube14** [comment]
Opened pr for setting profile for aws cluster type: https://github.com/openshift/ci-tools/pull/3732

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-cloud-tests-nightly-krkn-hub-cloud-api-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-cloud-tests-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-cloud-tests-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-cloud-tests-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-cloud-tests-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-cloud-tests-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-cloud-tests-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-cloud-tests-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-cloud-tests-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-cloud-tests-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-cloud-tests-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-cloud-tests-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-cloud-tests-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-cloud-tests-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-cloud-tests-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-cloud-tests-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-cloud-tests-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-cloud-tests-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-cloud-tests-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-cloud-tests-nightly-krkn-hub-cloud-api-tests

**Pull request merged**
