### PR TITLE
Apply nothing but secrets on api.ci

### PR DESCRIPTION
**Pull request by hongkailiu**
https://issues.redhat.com/browse/DPTP-2048

- appyconfig only targets `core-services/secrets` to api.ci.
- move files in `common_except_api.ci` to `common`.

/cc @openshift/openshift-team-developer-productivity-test-platform

### CODE REVIEW

**Review by alvaroaleman — APPROVED** [review]

**Comment by petr-muller** [comment]
/hold

That's pretty aggressive. What do we do with the actual content of `services` / `core-services`. Just leave them behind?

**Comment by hongkailiu** [comment]
> That's pretty aggressive. What do we do with the actual content of `services` / `core-services`. Just leave them behind?

Two categories that I can think of for the things in those 2 folders:
- configs for our automation: like `_config.yaml` for sanitize tool. We do not apply them (_filename) to api.ci anyway.
- services: no services should be applied there. Either they have been deployed on OCP cluster in the farm, or they are redirects.

What else (except secrets) do you think we need them running on `api.ci`? In my opinion, we can just leave them behind like api.ci had been gone already.

**Comment by petr-muller** [comment]
> What else (except secrets) do you think we need them running on api.ci? In my opinion, we can just leave them behind like api.ci had been gone already.

I don't think we need *anything* running on api.ci, but I'm not sure whether carrying manifests but not applying them is the best approach. I'd expect us to first delete the manifests that we do not need, *then* stop the `apply` jobs?  Just stopping the apply jobs gets us into this weird state where our repo pretends to carry content but any changes to that content are not propagated to production (why to carry it then?). There are not just config files (`_-prefixed`) and redirects, there's also a ton of RBACs, the stuff in `release-controller` (do we need it? likely no - so we should remove it first?), https://github.com/openshift/release/tree/master/services/promecieus ...

**Comment by hongkailiu** [comment]
Do you prefer the order of removing the files and disabling the jobs?
I can do that too.

What I plan is to disable and delete (the reverse order of the above).
I feel disabling is a smaller PR, easier to revert (in case that I need to ... knock knock knock).
Eventually, we will reach the same status.

**Comment by stevekuznetsov** [comment]
Right, but the interim state is what's important there. If we delete manifests (or move them to app.ci-only), the `git` state of this repo is never wrong. If we just disable the job, we have a repo with manifests that do nothing.

**Comment by hongkailiu** [comment]
@petr-muller 

About promecieus:

https://issues.redhat.com/browse/DPTP-1874?focusedCommentId=15662178&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-15662178


And I sent the email to aos-devel about api.ci offlining like several months ago.
I can ask @vrutkovs  again.

@stevekuznetsov 
Ack. I will delele the files first.

**Comment by hongkailiu** [comment]
@petr-muller 

This one is ready. Only configs for our automation are left.

```console
$ tree core-services services -L 1
core-services
├── README.md
├── _TEMPLATE
├── _hack
├── ci-secret-bootstrap
├── ci-secret-generator
├── image-mirroring
├── ipi-deprovision
├── openshift-priv
├── prow
├── release-controller
├── sanitize-prow-jobs
├── secret-mirroring
├── secrets
├── template-deprecation
└── testgrid-config-generator
services
├── README.md
└── yamllint
```

**Review by petr-muller — APPROVED** [review]

**Comment by petr-muller** [comment]
:tada:

**Pull request merged**
