### PR TITLE
Move our rosa-hypershift testing to 4.14

### PR DESCRIPTION
**Pull request by ascerra**
In this PR we will be setting up 9 layered products that we tested against rosa-hypershift 4.12 & 4.13 to be tested against 4.14.

We will move these scenarios as is to get the simple health checks running on a weekly cadence, then follow up work will be done to extend the testing to run the layered product qe test suite as well.

### CODE REVIEW

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Review by IshwarKanse — APPROVED** [review]

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-openshift-jenkins-release-4.14-jenkins-hypershift4.14-aws-jenkins-lp-rosa-hypershift

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.14-acceptance-lp-rosa-hypershift

**Review by calebevans — APPROVED** [review]
/lgtm

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
