### PR TITLE
Refactor hypershift e2e jobs

### PR DESCRIPTION
**Pull request by ironcladlou**
This commit refactors the hypershift e2e jobs in a few ways:

- Remove all IPI jobs in favor of cluster pools.

- Remove the "pooled" qualifier from all the job names (e.g. "e2e-aws-pooled"
becomes "e2e-aws").

- Add an "e2e-aws-all" variant which is the same as the periodic (i.e. all tests
instead of just the presubmits).

### CODE REVIEW

**Comment by alvaroaleman** [comment]
> Remove all IPI jobs in favor of cluster pools.

Do we have the necessary quota in our AWS account to be able to do that?

**Comment by csrwng** [comment]
> Do we have the necessary quota in our AWS account to be able to do that?

I think we should. So far we haven't run into any quota issues. However, we should notice if we start seeing failures in tests because of quota, no? I think that's orthogonal to this change.

**Comment by ironcladlou** [comment]
@csrwng rebased, PTAL

**Pull request merged**
