### PR TITLE
OCM-11612 | ci: Fix rosa-hcp-regional job

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/OCM-11612

### CODE REVIEW

**Comment by radtriste** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-hcp-advanced-regional-f3

**Comment by radtriste** [comment]
depends on https://github.com/terraform-redhat/terraform-provider-rhcs/pull/808

**Comment by aaraj7** [comment]
/pj-rehearse periodic-ci-openshift-rosa-master-e2e-rosa-hcp-advanced-regional-f3

**Pull request merged**
