### PR TITLE
WINC-830: Revert "wmco: Mark platform-none job as optional"

### PR DESCRIPTION
**Pull request by aravindhp**
This reverts commit 735394052a39374ed72600747444932342137182.

### CODE REVIEW

**Comment by aravindhp** [comment]
/retitle WINC-830: Revert "wmco: Mark platform-none job as optional"

**Comment by aravindhp** [comment]
Wait for https://github.com/openshift/windows-machine-config-operator/pull/1261 to merge

**Review by sebsoto — APPROVED** [review]

**Pull request merged**
