### PR TITLE
Add NMO v0.16.0

### PR DESCRIPTION
**Pull request by razo7**
Add config and presubmit files for NMO v0.16.0 release branch, `release-0.16`, for OCP 4.11-4.14.

### CODE REVIEW

**Review by slintes — APPROVED** [review]
/retest

**Comment by razo7** [comment]
/pj-rehearse pull-ci-medik8s-node-maintenance-operator-release-0.16-4.14-openshift-e2e

**Comment by razo7** [comment]
/pj-rehearse pull-ci-medik8s-node-maintenance-operator-release-0.16-4.14-openshift-e2e

**Comment by razo7** [comment]
/pj-rehearse pull-ci-medik8s-node-maintenance-operator-release-0.16-4.11-openshift-e2e
/pj-rehearse auto-ack

**Pull request merged**
