### PR TITLE
[SNC] Add release-4.11 branch

### PR DESCRIPTION
**Pull request by praveenkumar**

### CODE REVIEW

**Comment by jmguzik** [comment]
@praveenkumar `ci/rehearse/code-ready/snc/release-4.11/e2e-snc ` failed. Is that expected?

**Comment by praveenkumar** [comment]
> @praveenkumar `ci/rehearse/code-ready/snc/release-4.11/e2e-snc ` failed. Is that expected?

@jmguzik Yes this is expected.

**Review by jmguzik — APPROVED** [review]

**Pull request merged**
