### PR TITLE
Update apiserver-library-go master to use golang 1.14

### PR DESCRIPTION
**Pull request by marun**

### CODE REVIEW

**Comment by marun** [comment]
Required by 1.19 bump: https://github.com/openshift/apiserver-library-go/pull/34

**Comment by marun** [comment]
Ignore rehearsal failure, openshift/apiserver-library-go#34 has to merge before it would pass, but it can't merge until this PR does.

**Comment by sttts** [comment]
Why not 4.6 and 4.7 ?

**Comment by soltysh** [comment]
> Why not 4.6 and 4.7 ?

IIRC, these are synced from master, since master is effectively 4.6.

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
