### PR TITLE
[OSD-19314] - Implementing a semi-automatic backplane-cli release

### PR DESCRIPTION
**Pull request by xiaoyu74**
The detailed implementation steps documented here: [Semi-Automatic Release process for backplane-cli](https://docs.google.com/document/d/1_EfS9FGuT-3a4i_1xC3jyhIh9qWrNfWMINLoe-8VhhU/edit)

### CODE REVIEW

**Comment by xiaoyu74** [comment]
/pj-rehearse branch-ci-openshift-backplane-cli-main-release branch-ci-openshift-backplane-cli-main-trigger-release

**Review by supreeth7 — APPROVED** [review]

**Pull request merged**
