### PR TITLE
[oko] Add build-deploy job for telemetry-operator

### PR DESCRIPTION
**Pull request by viroel**

### CODE REVIEW

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-telemetry-operator-main-telemetry-operator-build-deploy

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-telemetry-operator-main-telemetry-operator-build-deploy

**Comment by csibbitt** [comment]
I think I'm the wrong reviewer here; try @jlarriba or @paramite perhaps?

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-telemetry-operator-main-telemetry-operator-build-deploy

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-telemetry-operator-main-telemetry-operator-build-deploy

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-telemetry-operator-main-telemetry-operator-build-deploy

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-telemetry-operator-main-telemetry-operator-build-deploy

**Pull request merged**
