### PR TITLE
SDCICD-814 presubmit ci config and job for test harness repo

### PR DESCRIPTION
**Pull request by ritmun**
added prow config for "osde2e-example-test-harness" and generated prow job 

jira: https://issues.redhat.com/browse/SDCICD-815

### CODE REVIEW

**Comment by MrSantamaria** [comment]
This one needs build images for Linux and go like in the osde2e repo

**Comment by ritmun** [comment]
> This one needs build images for Linux and go like in the osde2e repo

Thanks for the input, @MrSantamaria . Could you elaborate where this should be added? Or is there an example I can follow?

**Comment by ritmun** [comment]
> > This one needs build images for Linux and go like in the osde2e repo
> 
> Thanks for the input, @MrSantamaria . Could you elaborate where this should be added? Or is there an example I can follow?

I realized where it was missing. Just added.

**Pull request merged**
