### PR TITLE
OCM-9023 | ci: Update rhcs shared vpc job only support classic cluster

### PR DESCRIPTION
**Pull request by jameszwang**

### CODE REVIEW

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-shared-vpc-critical-high-f3

**Review by radtriste — APPROVED** [review]
/lgtm

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-shared-vpc-critical-high-f3

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-shared-vpc-critical-high-f3

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-shared-vpc-critical-high-f3

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-shared-vpc-critical-high-f3

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-shared-vpc-critical-high-f3

**Comment by radtriste** [comment]
@jameszwang `NonClassicCluster` and `NonHCPCluster` labels do not exist anymore on TF provider testing
I am going to remove them from here

**Comment by jameszwang** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-shared-vpc-critical-high-f3

**Pull request closed without merging**
