### PR TITLE
Upgrade to go 1.19 in cloud-event-proxy config

### PR DESCRIPTION
**Pull request by jzding**

### CODE REVIEW

**Comment by jzding** [comment]
/pj-rehearse pull-ci-redhat-cne-cloud-event-proxy-main-e2e-aws

**Review by nishant-parekh — APPROVED** [review]

**Review by aneeshkp — APPROVED** [review]

**Comment by jzding** [comment]
/pj-rehearse pull-ci-redhat-cne-cloud-event-proxy-main-e2e-aws

**Pull request merged**
