### PR TITLE
openshift-eng/rebasebot: add missed go toolset to the rebasebot src image

### PR DESCRIPTION
**Pull request by lobziik**

### CODE REVIEW

**Comment by lobziik** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/35224/rehearse-35224-pull-ci-openshift-eng-rebasebot-main-unit/1612424580406710272 - previous rehearse

/pj-rehearse ack

**Review by Fedosin — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
