### PR TITLE
red-hat-data-services: get rid of useless cron jobs

### PR DESCRIPTION
**Pull request by dtrifiro**
remove useless cron jobs

### CODE REVIEW

**Comment by heyselbi** [comment]
@dtrifiro @Xaenalt I think [releases](https://github.com/openshift/release/blob/master/ci-operator/config/red-hat-data-services/caikit-tgis-serving/red-hat-data-services-caikit-tgis-serving-rhoai-2.6.yaml#L19) needs to be added and/or golang version updated. But I would say we just completely remove 1.31 CI, instead of debugging it, no?

**Comment by Xaenalt** [comment]
Yeah, agreed, 1.31 is dead

**Pull request merged**
