### PR TITLE
Add CI config for serving 1.8

### PR DESCRIPTION
**Pull request by nak3**
As per title.

### CODE REVIEW

**Comment by nak3** [comment]
/test generated-config

Hmm... `make jobs` is clean on my local.

**Comment by nak3** [comment]
```
{"severity":"ERROR","timestamp":"2022-11-10T14:30:38.384872241Z","logger":"knative-operator","caller":"controller/controller.go:566","message":"Reconcile error","knative.dev/pod":"knative-operator-webhook-5fcf64d97-8v8pv","knative.dev/controller":"knative.dev.operator.pkg.reconciler.knativeserving.Reconciler","knative.dev/kind":"operator.knative.dev.KnativeServing","knative.dev/traceid":"bea3f0e8-b7c6-41b4-9ebc-a7d19c64e9c9","knative.dev/key":"knative-serving/knative-serving","duration":"5.606007333s","error":"failed to apply non rbac manifest: no matches for kind \"HorizontalPodAutoscaler\" in version \"autoscaling/v2\"","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\t/go/src/github.com/openshift-knative/serverless-operator/vendor/knative.dev/pkg/controller/controller.go:566\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\t/go/src/github.com/openshift-knative/serverless-operator/vendor/knative.dev/pkg/controller/controller.go:543\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\t/go/src/github.com/openshift-knative/serverless-operator/vendor/knative.dev/pkg/controller/controller.go:491"}
```

**Comment by mgencur** [comment]
Replaced by https://github.com/openshift/release/pull/34010

**Comment by mgencur** [comment]
Please close this one.

**Pull request closed without merging**
