### PR TITLE
add periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.17

### PR DESCRIPTION
**Pull request by amp-rh**
[INTEROP-7438](https://issues.redhat.com/browse/INTEROP-7438)

### CODE REVIEW

**Comment by amp-rh** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.17-stage-tempo-stage-tests

**Review by calebevans — APPROVED** [review]
/lgtm

**Comment by IshwarKanse** [comment]
@amp-rh Hi, you need to add an interop job which tests the released Tempo operator version with OCP 4.17. The job config that you are adding is for stage testing, which is used for testing a pre-release operator version. You can refer the existing interop job configs for adding the 4.17 job. Refer the jobs which has interop in their name.

**Comment by IshwarKanse** [comment]
Refer this config file https://github.com/openshift/release/blob/master/ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.16-lp-interop.yaml

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.17-lp-interop-tempo-interop-aws

**Comment by IshwarKanse** [comment]
@amp-rh We had to move our Distributed Tracing operators jobs to private deck https://github.com/openshift/release/pull/54572 . This is required now as we have added tests that uses cloud credentials from OCP CI https://github.com/grafana/tempo-operator/pull/985 more will be added later. The jobs output was public before and we do not want to inadvertently leak any sensitive info since we are now using credentials from CI env. Your team might have access to private deck, I'm assuming there are other teams that are using the private deck as well and have interop jobs. If not you need to request access for your team.

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.17-lp-interop-tempo-interop-aws

**Pull request merged**
