### PR TITLE
Enable tide for service binding operator

### PR DESCRIPTION
**Pull request by baijum**

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
```
{
  "component": "checkconfig",
  "file": "prow/cmd/checkconfig/main.go:71",
  "func": "main.reportWarning",
  "level": "warning",
  "msg": "the following orgs or repos forbid the needs-rebase label for merging but do not enable the needs-rebase plugin: [repo: redhat-developer/service-binding-operator]",
  "time": "2019-06-25T12:28:22Z"
}
```

Looks like you want to add the `needs-rebase` plugin -- look to `plugins.yaml`.

Also, please prefer to add your repo to a previous config entry (in the list of repos) if the labels are identical.

**Comment by baijum** [comment]
@stevekuznetsov I have added the extra-plugins list.

**Pull request merged**
