### PR TITLE
Add 4.19-9.6 repos

### PR DESCRIPTION
**Pull request by sdodson**
Modeled after 394bf8b8541ddf099425b3af33157e0c3082d80d

### CODE REVIEW

**Comment by jlebon** [comment]
Thanks for helping to make progress on this!
This looks plausible to me.

/cc @mike-nguyen

For reference to reviewers, AIUI this connects with https://github.com/openshift-eng/ocp-build-data/pull/5822.

**Comment by mike-nguyen** [comment]
Does https://github.com/openshift-eng/ocp-build-data/pull/5822 mirror directly to the CDN? On [394bf8b](https://github.com/openshift/release/commit/394bf8b8541ddf099425b3af33157e0c3082d80d) I believe we got the URLs directly from RHEL.

**Comment by sdodson** [comment]
@mike-nguyen No I doubt it. I don't think these are the right URLs, they probably point at 9.5 content I assume. I'm going to go ahead and merge this to unblock the other PR and we can come back to update them later. I wasn't able to find any discussion about https://github.com/openshift-eng/ocp-build-data/pull/5822 on slack so I don't know its full intent.

**Comment by sdodson** [comment]
/label approved
/label lgtm
:-)

**Comment by jlebon** [comment]
Follow up to this in https://github.com/openshift/release/pull/60016.

**Pull request merged**
