### PR TITLE
WIP run job controller for 4.15

### PR DESCRIPTION
**Pull request by rioliu-rh**
Test whether new 4.15 accepted build can be detected
Test whether prow jobs defined for amd64 can be triggered
Test whether test result can be aggregated
Test whether releasepayload can be labeled if tests are all pass

### CODE REVIEW

**Comment by rioliu-rh** [comment]
/pj-rehearse periodic-ci-openshift-release-tests-master-qe-release-gate-test

**Comment by rioliu-rh** [comment]
/pj-rehearse periodic-ci-openshift-release-tests-master-qe-release-gate-test

**Comment by rioliu-rh** [comment]
/pj-rehearse periodic-ci-openshift-release-tests-master-qe-release-gate-test

**Comment by rioliu-rh** [comment]
/pj-rehearse periodic-ci-openshift-release-tests-master-qe-release-gate-test

**Comment by jianzhangbjz** [comment]
Great! Thanks! Seems like the workflow is Green now.

**Pull request closed without merging**
