### PR TITLE
run end_to_end against registry PRs

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
/assign @stevekuznetsov 

@openshift/sig-continuous-infrastructure ptal.  I need someone to confirm that when this job runs against PRs for openshift/image-registry, it will build+use the image-registry image produced by the PR/branch.  The job it ultimately is invoking is defined here:

https://github.com/openshift/aos-cd-jobs/blob/master/sjb/config/test_cases/test_pull_request_origin_end_to_end.yml

Thanks

**Comment by bparees** [comment]
@legionus @dmage fyi

**Comment by stevekuznetsov** [comment]
I don't think that will work

**Comment by bparees** [comment]
@stevekuznetsov more details please?

**Comment by stevekuznetsov** [comment]
It's an ancient job built to run against origin. I don't remember how it works but nothing about it immediately makes me thing that would do what you want. Why don't you write a new test?

**Comment by bparees** [comment]
> It's an ancient job built to run against origin. I don't remember how it works but nothing about it immediately makes me thing that would do what you want. Why don't you write a new test?

because this test works today, it's critical to us verifying we don't regress functionality, and we don't have time to stop and spend a week rewriting it.

**Comment by bparees** [comment]
and fyi this test when it runs against origin, builds the latest image-registry code and uses that image.

So i would expect it to be possible to do the inverse, if it does not do so already.

**Comment by stevekuznetsov** [comment]
I don't know the inner workings of the job, maybe you can have it as a parent and override the `sync` block. I'm not sure. You can always push it up and try

**Pull request closed without merging**
