### PR TITLE
[INTEROP-7281] Expand OpenShift Pipelines to v1.13 for OCP 4.15 and 4.16.

### PR DESCRIPTION
**Pull request by dfrazzette**
Per [SRVKP-3694](https://issues.redhat.com/browse/SRVKP-3694), Pipelines 1.11 is not supported on OCP 4.15. Expanding the scenario to test Pipelines 1.13 on OCP 4.15. (branch renamed)

### CODE REVIEW

**Comment by dfrazzette** [comment]
@calebevans - Branch rename closed original [PR#48976](https://github.com/openshift/release/pull/48976). Rehearsal job [1759684668195606528](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/48976/rehearse-48976-periodic-ci-openshift-pipelines-release-tests-release-v1.13-openshift-pipelines-ocp4.15-lp-interop-openshift-pipelines-interop-aws/1759684668195606528) completed. Comment if rehearsal job should be re-run for this PR?

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
