### PR TITLE
GCP2: Lower the quota to 18

### PR DESCRIPTION
**Pull request by petr-muller**
We're currently hitting limits on Service Accounts and Routers, each
holding 20 clusters, so setting to 18 to take short-term leaks into
account.

Request for limits bump: [DPP-7324](https://issues.redhat.com/browse/DPP-7324)
xref: https://github.com/openshift/release/pull/18253#issuecomment-833009915

### CODE REVIEW

**Comment by wking** [comment]
[Docs][1] say five service accounts and one router per cluster.  Does that match what we're measuring?  Holding in case you want to add these details or error messages or whatever to the commit message, so folks touching this limit later can find them.  Pull the hold whenever you want.

/lgtm
/hold

[1]: https://docs.openshift.com/container-platform/4.7/installing/installing_gcp/installing-gcp-account.html#installation-gcp-limits_installing-gcp-account

**Comment by petr-muller** [comment]
Bumping the quotas was really prompt so this PR may not be even necessary.

**Pull request closed without merging**
