### PR TITLE
OCPBUGS-29415: Synchronize the periodic build images to the release images

### PR DESCRIPTION
**Pull request by tmshort**

### CODE REVIEW

**Comment by joelanford** [comment]
/retitle "OCPBUGS-29415: Synchronize the periodic build images to the release images"

**Comment by tmshort** [comment]
The tert failure is a known flake:
```
Install Plan with deprecated version CRD Test [It] upgrade CRD with deprecated version
```

**Comment by tmshort** [comment]
/pj-rehearsals ack
The test failure is a known flake:
```
Install Plan with deprecated version CRD Test [It] upgrade CRD with deprecated version
```

**Comment by tmshort** [comment]
/pj-rehearse ack
The test failure is a known flake:
```
Install Plan with deprecated version CRD Test [It] upgrade CRD with deprecated version
```

**Pull request merged**
