### PR TITLE
MGMT-14372: MGMT-14371: Add 4.14 periodic and presubmit jobs

### PR DESCRIPTION
**Pull request by eliorerz**
/cc @eliorerz

### CODE REVIEW

**Comment by eliorerz** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted-4-14

**Comment by eliorerz** [comment]
@osherdp @gamli75 @adriengentil

**Review by gamli75 — APPROVED** [review]

**Pull request merged**
