### PR TITLE
Bug 1897737: Censor Terraform secrets

### PR DESCRIPTION
**Pull request by pierreprinetti**

### CODE REVIEW

**Comment by patrickdillon** [comment]
Personally I think it would be better to redact the secret, with an approach similar to this:
https://github.com/openshift/release/blob/master/ci-operator/step-registry/ipi/install/install/ipi-install-install-commands.sh#L59

rather than turning off tf debugging. TF debugging in CI has been useful for me for cloud platforms, but perhaps it is not as useful for openstack?

Also does this change need to be resolved in the step registry?

**Comment by pierreprinetti** [comment]
> Personally I think it would be better to redact the secret
I also think that a long-term solution is to be coded right within the Terraform-openstack provider. Currently we can't simply regex our way out because the Terraform provider funnily logs the sensitive ASCII content as a hex-dump sometimes.

I am proposing this as a CI-specific solution because users aren't expected to set the `TF_LOG` level.

> does this secret leak need to be resolved in the step registry

Very good point, thanks.

**Review by mandre — COMMENTED** [review]
/lgtm
/retest
/hold until the e2e-openstack job passes

**Review by mandre — COMMENTED** [review]
/lgtm
/hold cancel

**Comment by pierreprinetti** [comment]
/assign patrickdillon

I previously blindly copy-pasted what the bot recommended and assigned Clayton, which is probably not the best move.

**Comment by pierreprinetti** [comment]
@patrickdillon @smarterclayton 

We have a secret leak in the CI and this patch was meant as a quick band-aid to be applied as soon as possible. May I get some feedback on what I need to change in order to get an /approve, or the reasons why I won’t get it?

Also, I followed the bot’s advice on who to assign (Clayton). Is that what I was expected to do? If not, can you suggest a way I could patch Prow to give better suggestions?

Thank you.

/cc stevekuznetsov vrutkovs

**Comment by pierreprinetti** [comment]
Changed the PR to reflect @patrickdillon's suggestions, in the hopes that this can catch the eye of an approver.

**Review by mandre — COMMENTED** [review]
The patch looks good but IMO should fix the issue everywhere we're already filtering out sensitive log lines.

```
❯ ag "TF_LOG=debug .* password" -c
cluster-launch-installer-openstack-e2e.yaml:1
ci-operator/step-registry/ipi/install/install/ipi-install-install-commands.sh:1
ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml:1
ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml:1
ci-operator/templates/openshift/installer/cluster-launch-installer-custom-test-image.yaml:1
ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml:1
ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-upi-e2e.yaml:5
ci-operator/templates/openshift/installer/cluster-launch-installer-ovirt-e2e.yaml:1
ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml:1
ci-operator/templates/openshift/endurance/endurance-install.yaml:1
cluster-launch-installer-openstack-upi-e2e.yaml:5
```

**Comment by patrickdillon** [comment]
> @patrickdillon @smarterclayton
> 
> We have a secret leak in the CI and this patch was meant as a quick band-aid to be applied as soon as possible. May I get some feedback on what I need to change in order to get an /approve, or the reasons why I won’t get it?
> 
> Also, I followed the bot’s advice on who to assign (Clayton). Is that what I was expected to do? If not, can you suggest a way I could patch Prow to give better suggestions?
> 
> Thank you.
> 
> /cc stevekuznetsov vrutkovs

Sorry but I don't have approval rights at this level. Looks like you are covered for review but ping me if you need another look.

For approval you might reach out to @wking I know he handled secret redaction elsewhere so I am arbitrarily volunteering him. 😉

**Review by vrutkovs — APPROVED** [review]
/lgtm

**Comment by pierreprinetti** [comment]
@vrutkovs Thank you! However while you were approving, I have addressed @mandre's comment. I hope everything is still fine for you.

/cc @mandre

**Comment by vrutkovs** [comment]
Yup, that looks good.

/lgtm
/hold 

for rehearsals to run

**Comment by pierreprinetti** [comment]
@mandre 
I have removed the changes to the templates that require Clayton's or Ben's approval. OpenStack templates are covered. Can you please LGTM if fine for you?

@ Vadim: this is a subset of the changes you already LGTM'd, so I am not directly bothering you any more.

WRT the rehearsals, they're mostly failing so far and I'm not sure there's anything I can do.

**Review by mandre — COMMENTED** [review]
/lgtm

**Comment by mandre** [comment]
/hold
until the tests finish running

**Comment by jcpowermac** [comment]
@pierreprinetti FYI: this change is causing vSphere UPI to fail with the grep:
see https://coreos.slack.com/archives/C015H2WDJRY/p1612815477031800
Not sure if the other providers its causing an issue.

**Pull request merged**
