### PR TITLE
Split latest lane into variant lanes for sigs

### PR DESCRIPTION
**Pull request by dhiller**
We now create sig lanes for testing kubevirt on openshift-ci. This in turn enables us to test per sig. Also we increase the number of tests that are run.

| SIG | # tests | source |
|-------|----------|-----------|
| compute | 524 | [junit.functest.xml](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/22352/rehearse-22352-periodic-ci-kubevirt-kubevirt-main-nightly_4.10-e2e-compute/1465915080632700928/artifacts/e2e-compute/test/artifacts/junit.functest.xml) |
| network | 90 | [junit.functest.xml](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/22352/rehearse-22352-periodic-ci-kubevirt-kubevirt-main-nightly_4.10-e2e-network/1465915080683032576/artifacts/e2e-network/test/artifacts/junit.functest.xml) |
| storage | 28 | [junit.functest.xml](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/22352/rehearse-22352-periodic-ci-kubevirt-kubevirt-main-nightly_4.10-e2e-storage/1465915080553009152/artifacts/e2e-storage/test/artifacts/junit.functest.xml) |

**Reviewer note: the check for pj-rehearse is failing as one of the jobs has not finished after 4h, but this is by intent, as the compute tests take longer than that.**

### CODE REVIEW

**Comment by jean-edouard** [comment]
/uncc jean-edouard
Sorry, too noisy, but feel free to re-cc me when ready for review!

**Comment by dhiller** [comment]
@fabiand FYI

**Pull request closed without merging**
