### PR TITLE
Revert E2E version locking as we have CI test now

### PR DESCRIPTION
**Pull request by vishnuchalla**
### Description
Now that we have CI tests, reverting e2e version locking that went in as a part of one of the previous PRs: https://github.com/openshift/release/pull/46763

JIRA: https://issues.redhat.com/browse/PERFSCALE-2702
Verified through this test PR: https://github.com/cloud-bulldozer/e2e-benchmarking/pull/690

### Testing
Testing through one of rehearsal jobs.

### CODE REVIEW

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.12-nightly-x86-cluster-density-v2-3nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-release-4.15-qe-perfscale-aws-ovn-small-cluster-density

**Comment by jtaleric** [comment]
It appears the 4.12 test ran cdv2 but failed for other reasons..

This change has a big blast radius, i would like to see more testing done if possible, I only see 2 `pj-rehearase` attempts.

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-nightly-arm-data-path-9nodes
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-gcp-4.14-nightly-x86-network-policy-5nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-gcp-4.14-nightly-x86-network-policy-5nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.12-nightly-x86-cluster-density-v2-3nodes

**Comment by jtaleric** [comment]
These failures are unrelated to this change.

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.13-nightly-x86-router-perf-3nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.15-nightly-x86-node-density-heavy-24nodes

**Pull request closed without merging**
