### PR TITLE
sriov-dp-admission-controller base image rhel9

### PR DESCRIPTION
**Pull request by vrindle**

### CODE REVIEW

**Comment by zeeke** [comment]
/pj-rehearse pull-ci-openshift-sriov-dp-admission-controller-master-images
/ok-to-test

**Comment by zeeke** [comment]
/pj-rehearse pull-ci-openshift-sriov-dp-admission-controller-master-images

**Comment by vrindle** [comment]
@wizhaoredhat

**Comment by vrindle** [comment]
@wizhaoredhat @bn222

**Pull request merged**
