### PR TITLE
update redhat-cne repos to use the new aws-telco cluster profile

### PR DESCRIPTION
**Pull request by nishant-parekh**
Deprecate hw-event-proxy test jobs

### CODE REVIEW

**Comment by sshnaidm** [comment]
You should add 
```yaml
env:
    BASE_DOMAIN: sysdeseng.devcluster.openshift.com
```
like in https://github.com/openshift/release/pull/46607/files#diff-ce2b86cfe8835c248b4825cf30b74171499e912fcf1bc384f25becd040373593L71

And we need probably to increase quotas on the account if we add another jobs to it.

**Comment by nishant-parekh** [comment]
> You should add
> 
> ```yaml
> env:
>     BASE_DOMAIN: sysdeseng.devcluster.openshift.com
> ```
> 
> like in https://github.com/openshift/release/pull/46607/files#diff-ce2b86cfe8835c248b4825cf30b74171499e912fcf1bc384f25becd040373593L71
> 
> And we need probably to increase quotas on the account if we add another jobs to it.

updated for the base Domain environment variable. How can we increase the quota on the account?

**Comment by nishant-parekh** [comment]
/pj-rehearse pull-ci-redhat-cne-hw-event-proxy-operator-main-e2e-aws

**Comment by nishant-parekh** [comment]
/pj-rehearse pull-ci-redhat-cne-hw-event-proxy-operator-main-e2e-operator

**Comment by sshnaidm** [comment]
> > You should add
> > ```yaml
> > env:
> >     BASE_DOMAIN: sysdeseng.devcluster.openshift.com
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > like in https://github.com/openshift/release/pull/46607/files#diff-ce2b86cfe8835c248b4825cf30b74171499e912fcf1bc384f25becd040373593L71
> > And we need probably to increase quotas on the account if we add another jobs to it.
> 
> updated for the base Domain environment variable. How can we increase the quota on the account?

If jobs use IPI, we need to know how many jobs are running, what is amount of possible parallel jobs. It may require increasing [quotas in Prow ](https://github.com/openshift/release/pull/46120)and in AWS for VPCs and EIPs. I made quotas for openshift-kni org only, didn't plan for more.

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-redhat-cne-hw-event-proxy-operator-main-e2e-aws

**Comment by sshnaidm** [comment]
OK, it requires a rebase

**Review by sshnaidm — APPROVED** [review]
/lgtm

**Review by jzding — APPROVED** [review]
/lgtm

**Pull request merged**
