### PR TITLE
Update CI cluster roles

### PR DESCRIPTION
**Pull request by 0xmichalis**
/assign stevekuznetsov smarterclayton 

I think we **don't** want `view` access for authenticated users in the `ci` namespace.

### CODE REVIEW

**Comment by kargakis** [comment]
@bbguimaraes @paradigm fyi

**Comment by smarterclayton** [comment]
What’s the concern?

**Comment by stevekuznetsov** [comment]
We do want image-puller for unauth in there though

**Comment by kargakis** [comment]
> What’s the concern?

Access to pod logs. We run things that do stuff with ose.

**Comment by kargakis** [comment]
> Access to pod logs. We run things that do stuff with ose.

This would be fine if everyone that is a member of our cluster is a RedHatter, but it's not the case today.

**Comment by kargakis** [comment]
Is there anything that depends on having view access in ci today, like deployments that expect images for example? Why do we need it?

**Comment by stevekuznetsov** [comment]
Thought we merged this and fixed it but clearly not -- can we add `system:image-puller` to group `system:unauthenticated` for CI namespace?

**Comment by kargakis** [comment]
Will do tomorrow

**Comment by kargakis** [comment]
@stevekuznetsov done, ptal

**Comment by kargakis** [comment]
Seems we also have system:anonymous for doing image pulls from ci. Added that too. Also added an admin rolebinding linking ci-admins to the admin role in ci.

**Pull request merged**
