### PR TITLE
Keep JOB_NAME tag at 80 chars

### PR DESCRIPTION
**Pull request by derekhiggins**
Equinix seems to be enforcing a 80 char limit.

### CODE REVIEW

**Comment by derekhiggins** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-live-iso

**Comment by andfasano** [comment]
Something recently introduced?

**Comment by derekhiggins** [comment]
> Something recently introduced?

I guess so, I manually tried a ansible playbook that had failed and
`     "msg": "failed to set device state present, error: Error 422: Tags must be 1-80 characters"`

**Comment by derekhiggins** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ovn-single-node-live-iso

**Comment by derekhiggins** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-release-4.13-e2e-agent-compact-ipv4

**Pull request merged**
