### PR TITLE
adds monitoring resources to operator builds

### PR DESCRIPTION
**Pull request by umangachapagain**
Required for testing : https://github.com/openshift/ocs-operator/pull/739

Signed-off-by: Umanga Chapagain <chapagainumanga@gmail.com>

### CODE REVIEW

**Comment by anmolsachan** [comment]
@obnoxxx Can you please approve this PR so that all the tests can run. Thanks

**Comment by umangachapagain** [comment]
`Images` tests are passing which means that build is working fine.

`ocs-operator-e2e-aws` is failing with `ImagePullBackOff` which probably means it's unable to find image. This looks like CI config issue unrelated to this PR.

**Comment by anmolsachan** [comment]
@obnoxxx Looks like the failing tests are not because of this PR but CI . What should we do here ?

**Review by obnoxxx — CHANGES_REQUESTED** [review]
@umangachapagain - should we really do this for master and release-4.6 at once?
Can we not split it?

**Comment by jarrpa** [comment]
There's no real point in splitting it other than procedural overhead. The changes in the target repo are already done on both branches.

**Comment by jarrpa** [comment]
Also, this repo doesn't regularly divide PRs at the level of the individual branches. If a change affects multiple branches in the same way, it's typical to have them in a single PR.

**Review by obnoxxx — APPROVED** [review]
well then, i still find it weird not to split it, especially when it is not decided yet to which branches a change will be merged. 

/lgtm

**Pull request merged**
