### PR TITLE
OLS-691: create prow job for openshift lightspeed docs

### PR DESCRIPTION
**Pull request by rh-tokeefe**
Creating new prow job for the Openshift Lightspeed docs, as described here:
https://github.com/openshift/openshift-docs/tree/main/scripts/prow

### CODE REVIEW

**Comment by rh-tokeefe** [comment]
@kalexand-rh or @bergerhoffer I spoke with Kathryn, and I'm trying to work my way through setting up a new standalone doc branch for the OpenShift Lightspeed sproject. 

Following this set of [instructions](https://github.com/openshift/openshift-docs/tree/main/scripts/prow), I _think_ I'm at the point in the process where I have to obtain a LGTM on this PR.

**Comment by bergerhoffer** [comment]
> @kalexand-rh or @bergerhoffer I spoke with Kathryn, and I'm trying to work my way through setting up a new standalone doc branch for the OpenShift Lightspeed project.
> 
> Following this set of [instructions](https://github.com/openshift/openshift-docs/tree/main/scripts/prow), I _think_ I'm at the point in the process where I have to obtain a LGTM on this PR.
> 
> Please have a look and let me know what you think. Thanks!

Prow isn't one of my areas of expertise, so I'll defer to @kalexand-rh or someone else who has more knowledge in that area!

**Comment by kalexand-rh** [comment]
If we can get the pj-rehearse steps to pass, I'll approve it.

**Comment by kalexand-rh** [comment]
@aireilly, will you PTAL?

**Comment by aireilly** [comment]
Ok, so this also needs an update here with the new distro name (`openshift-lightspeed`?): https://github.com/openshift/release/blob/master/ci-operator/step-registry/openshift-docs/portal/openshift-docs-portal-commands.sh#L15

**Comment by rh-tokeefe** [comment]
@aireilly yes, I think openshift-lightspeed is the name we should use based on my discussion with Kathryn. Is that a change I can submit or do I need additional permissions to submit a change in that area?

**Comment by rh-tokeefe** [comment]
Slainte, @aireilly! The build has progressed past the spot where it failed. Thank you.

@kalexand-rh I'm keeping my fingers crossed...

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-lightspeed-docs-main-validate-asciidoc

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-lightspeed-docs-main-validate-portal

**Comment by rh-tokeefe** [comment]
@aireilly is there anything I can do to help get this PR merged?

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-lightspeed-docs-main-deploy-preview

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-lightspeed-docs-main-validate-asciidoc

**Comment by aireilly** [comment]
We need to verify those builds I just triggered, and then you need to comment `/pj-rehearse ack` in the PR to get it into the merge pool.

**Comment by aireilly** [comment]
@rh-tokeefe See https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/52953/rehearse-52953-pull-ci-openshift-openshift-docs-lightspeed-docs-main-deploy-preview/1800484649017806848#1:build-log.txt%3A38

You need to PR openshift-docs-lightspeed with the complete set of script/ folder files from main in openshift-docs, then rerun the failed tests here again once those changes are merged.

**Comment by aireilly** [comment]
@rh-tokeefe please force push again on the PR

**Comment by rh-tokeefe** [comment]
Created a different PR for the TP1 branch

**Pull request closed without merging**
