### PR TITLE
Setup Openshift-CI pipeline for OVMS 2024.3-release

### PR DESCRIPTION
**Pull request by vaibhavjainwiz**

### CODE REVIEW

**Comment by RH-steve-grubb** [comment]
This is part of the work for RHOAIENG-11705. I was going to finish off the Dockerfile before hooking it up to other things. We're not quite ready for this to go to RHDS. Anyways...
/lgtm

**Comment by vaibhavjainwiz** [comment]
/pj-rehearse pull-ci-opendatahub-io-openvino_model_server-2024.3-release-images
/pj-rehearse pull-ci-opendatahub-io-openvino_model_server-2024.3-release-pr-image-mirror

**Comment by vaibhavjainwiz** [comment]
/pj-rehearse pull-ci-opendatahub-io-openvino_model_server-2024.3-release-pr-image-mirror

**Pull request merged**
