### PR TITLE
Fixed wrong condition

### PR DESCRIPTION
**Pull request by ccardenosa**
The default catalog must be the one selected, if more than one is available and “!any” has been set as the value for the source” field.

### CODE REVIEW

**Comment by ccardenosa** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-sno-hub-ztp-4.17-latest-telcov10n-sno-hub-ztp-f360

**Comment by ccardenosa** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-sno-hub-ztp-4.17-latest-telcov10n-sno-hub-ztp-f360

**Comment by ccardenosa** [comment]
/assign @calebevans
/assign @vboulos

This PR is ready to be merged. Would you mind reviewing it?

**Review by dfrazzette — APPROVED** [review]

**Pull request merged**
