### PR TITLE
tide: require bugzilla/valid-bug for master branches

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
/hold

We should merge this at the start of the EU workday on Monday.

**Comment by wking** [comment]
Out of curiosity, this isn't just master, right?  Like if some crazy repo had a PR against a `feature-a` branch, this would keep Tide from merging that too?  Or does `from-branch-protection` somehow come into this?  And `ocs-operator` and the `lgtm`-only repositories are excluded from the `valid-bug` requirement?

**Comment by petr-muller** [comment]
@wking 

> Out of curiosity, this isn't just master, right? Like if some crazy repo had a PR against a feature-a branch, this would keep Tide from merging that too? Or does from-branch-protection somehow come into this?

Yeah this disables auto-merges for all branches that re 

> And ocs-operator and the lgtm-only repositories are excluded from the valid-bug requirement?

IIRC ocs-operator *is* excluded, but not the lgtm-only repos, good point.

**Pull request merged**
