### PR TITLE
[4.11] Generate ci-operator configs and jobs

### PR DESCRIPTION
**Pull request by petr-muller**
- [4.11] Generate ci-operator configuration
- [4.11] Generate ci-operator configuration for openshift-priv
- [4.11] Generate vanilla jobs for 4.11
- [4.11] Carry job customization over from master/main jobs
- [4.11] Update template allowlist

```bash
#!/bin/bash

set -o nounset
set -o errexit
set -o pipefail

git fetch upstream
git reset --hard upstream/master

CURRENT=4.10
NEXT=4.11

config-brancher --config-dir ci-operator/config --current-release=$CURRENT --future-release=$NEXT --confirm
git add ci-operator/config
git commit -m "[$NEXT] Generate ci-operator configuration"

ci-operator-config-mirror --config-dir ./ci-operator/config --to-org openshift-priv --only-org openshift --whitelist-file ./core-services/openshift-priv/_whitelist.yaml
git add ci-operator/config
git commit -m "[$NEXT] Generate ci-operator configuration for openshift-priv"

make jobs
git add ci-operator/jobs
git commit -m "[$NEXT] Generate vanilla jobs for $NEXT"

cat <<EOF >/tmp/filter.py
#!/usr/bin/env python3

import yaml
import sys
import copy

with open(sys.argv[1]) as f:
    all = yaml.full_load(f)
    for t in ("presubmits", "postsubmits"):
        for repo in all.get(t, {}):
            pruned = []
            for job in all.get(t, {}).get(repo, []):
                if job.get("agent", "") == "kubernetes":
                    pruned.append(job)
            all[t][repo] = pruned

with open(sys.argv[1], 'w') as f:
    yaml.dump(all, f, default_flow_style=False)
EOF

chmod +x /tmp/filter.py

find ci-operator/jobs/ -name '*-release-'$CURRENT'-*submits.yaml' -or -name '*-'$CURRENT'-periodics.yaml' | while read -r item; do
    echo -n "Processing: ${item}"
    for main in master main; do
      if [ -e "${item/release-$CURRENT/$main}" ]; then
        cp "${item/release-$CURRENT/$main}" "${item/$CURRENT/$NEXT}"
        sed -i "s/-$main-/-release-$NEXT-/g" "${item/$CURRENT/$NEXT}" # job names
        sed -i "s/- \^$main/- \^release-$NEXT/g" "${item/$CURRENT/$NEXT}" # branches
        /tmp/filter.py "${item/$CURRENT/$NEXT}"
        break
      fi
    done
    echo " [DONE]"
done

# openshift/release are special and are handled separately
rm -f ci-operator/jobs/openshift/release/openshift-release-release-$NEXT-periodics.yaml
make jobs
git add ci-operator/jobs
git commit -m "[$NEXT] Carry job customization over from master/main jobs"


make template-allowlist
git add core-services/template-deprecation/_allowlist.yaml
git commit -m "[$NEXT] Update template allowlist"
```

### CODE REVIEW

**Review by hongkailiu — APPROVED** [review]

**Comment by LorbusChris** [comment]
It seems this did not any variant configs for 4.11

**Comment by petr-muller** [comment]
No, variant configs are outside of OCP branching scope (variant configs do not contribute to OCP)

**Comment by LorbusChris** [comment]
I disagree strongly. OKD branches with OCD, and non-x84 OCP CI will be variant configs, too. Is there a way to automate variant config branching?

**Comment by petr-muller** [comment]
OK, to be more precise: it is outside the scope of what TP is currently committed to perform in OCP branching.

The branching is done by the https://github.com/openshift/ci-tools/tree/master/cmd/config-brancher tool, so the ability to branch variant configs would need to be implemented there (plus the annoying manual procedure to carry the manual modifications would need to be adjusted).

**Comment by fabianofranz** [comment]
OKD is a non-negotiable part of the OCP release for every engineering team. If we're currently not including it in the regular branching for the test platform, that's a gap that we need to fix asap. @ppawlows I'll reach out to you in private so we can sync about this. cc @craychee

**Pull request merged**
