### PR TITLE
increase networking-console-plugin memory e2e tests

### PR DESCRIPTION
**Pull request by upalatucci**

### CODE REVIEW

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-networking-console-plugin-release-4.17-e2e

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-networking-console-plugin-release-4.17-e2e

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-networking-console-plugin-release-4.17-e2e

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-networking-console-plugin-release-4.17-e2e

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-networking-console-plugin-release-4.17-e2e

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-networking-console-plugin-release-4.17-e2e

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-networking-console-plugin-release-4.17-e2e

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-networking-console-plugin-release-4.17-e2e

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-networking-console-plugin-release-4.17-e2e

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-networking-console-plugin-release-4.17-e2e

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-openshift-networking-console-plugin-release-4.17-e2e

**Pull request merged**
