### PR TITLE
Run odo test on stable server version

### PR DESCRIPTION
**Pull request by amitkrout**
Run odo test on stable server version

### CODE REVIEW

**Review by mohammedzee1000 — APPROVED** [review]
This pr definitely has my approval, but will not add lgtm until tests are green

**Comment by mohammedzee1000** [comment]
/lgtm cancel
ci needs to be green to apply this label

**Comment by amitkrout** [comment]
retest

**Comment by prietyc123** [comment]
@amitrout could you please rebase the PR once.

**Pull request closed without merging**
