### PR TITLE
Use bastionuser secret in sno-setup and cluster-setup scripts

### PR DESCRIPTION
**Pull request by danimjaffe**

### CODE REVIEW

**Comment by danimjaffe** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-telco5g-cnftests

**Comment by danimjaffe** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-telco5g-sno-cnftests

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-telco5g-cnftests

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-telco5g-sno-cnftests

**Pull request merged**
