### PR TITLE
ci-operator/step-registry/ipi/install/vsphere: Drop install step

### PR DESCRIPTION
**Pull request by wking**
The ref was born in fa871a1e13 (#7586) so it could use the upi-installer image to work with a self-signed certificate.  But vSphere installation hasn't required that since fe3ea6a8a5 (#12725).  Remove the vSphere-specific step and point consumers at the generic step instead.

/assign @jcpowermac

### CODE REVIEW

**Comment by wking** [comment]
I've pushed 4cde3e5bf5 -> 4f3f1f8557 to do the same for the deprovision step.

**Review by staebler — COMMENTED** [review]
Looks sane to me. I'll give @jcpowermac a chance to weigh in in case I am missing some wrinkle.

**Comment by wking** [comment]
Of the rehearsal failures, most [were][1] [test-case][2] [failures][3] (i.e. not "could not run that step, because the image being used isn't compatible".  The [update job][4], on the other hand, died on `step e2e-vsphere-upgrade failed: failed to acquire lease: resources not found`.  That seems orthogonal, but just in case:

/retest

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/16518/rehearse-16518-pull-ci-openshift-machine-api-operator-master-e2e-vsphere-serial/1367642331976568832
[2]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/16518/rehearse-16518-pull-ci-openshift-cluster-network-operator-master-e2e-vsphere-ovn/1367642331699744768
[3]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/16518/rehearse-16518-pull-ci-openshift-cluster-api-actuator-pkg-master-e2e-vsphere-operator/1367642331322257408
[4]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/16518/rehearse-16518-pull-ci-openshift-machine-api-operator-master-e2e-vsphere-upgrade/1367642332257587200

**Comment by wking** [comment]
ah, [`resources not found` is the terrible error for "Boskos quota exhausted"][1], so I should have retested just that job.  Or maybe I'll get lucky and it will be one of the ones to get a least this time around...

[1]: https://github.com/kubernetes/test-infra/issues/15382#issuecomment-614227137

**Comment by jcpowermac** [comment]
Other CI jobs passed.
/lgtm
Thanks!

**Pull request merged**
