### PR TITLE
[BM CPT] Add performance profile setup

### PR DESCRIPTION
**Pull request by josecastillolema**
Adds the core RDS performance profile as a day 2 step.

### CODE REVIEW

**Comment by josecastillolema** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-x86-day2-performanceprofile

**Comment by josecastillolema** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-x86-day2-performanceprofile

**Comment by josecastillolema** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-x86-day2-performanceprofile

**Review by rsevilla87 — APPROVED** [review]
lgtm

**Comment by jtaleric** [comment]
Nice work @josecastillolema couple of comments (shared on slack) 

- Can we change the name to `perf-profile` just to shorten it up. 
- Lets add a parameter/env var to specify the machine type -- the current perf-profile is for an R660 -- for net-new machines we add to CPT we can simply add a new env var w/ a new performance profile yaml

**Comment by josecastillolema** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-x86-day2-perf-profile-rds-core

**Comment by josecastillolema** [comment]
@rook PTAL

  - Changed the name to **perf-profile**
  - Created a folder inside **perf-profile** for the **rds-core** profile: **perf-profile/rds-core**
  - Parametrized ISOLATED_CORES, RESERVED_CORES and HUGEPAGES_COUNT and documented the defaults for R760

**Comment by josecastillolema** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-latest-x86-deploy-6nodes

**Pull request merged**
