### PR TITLE
Fix issue DPTP-3438 Add build08

### PR DESCRIPTION
**Pull request by bear-redhat**
Init the new build cluster

```
cluster-init --hosted --create-pr=false --release-repo ../release  --cluster-name build08
cluster-init --create-pr=false --release-repo ../release  --update
make update
make update-ci-build-clusters
```

### CODE REVIEW

**Comment by bear-redhat** [comment]
This PR is blocked due to missing CRD in HyperShift hosted clusters.
Ref: https://issues.redhat.com/browse/DPTP-3486

**Comment by hongkailiu** [comment]
/lgtm

/hold

Feel free to cancel while watching the rolling.

**Pull request merged**
