### PR TITLE
CORS-3698 - Add a test for Azure default install config

### PR DESCRIPTION
**Pull request by gpei**
To implement [CORS-3698](https://issues.redhat.com//browse/CORS-3698) for Azure, add the install test with a minimal default install-config.yaml ~~, and also with the minimal permission required~~

### CODE REVIEW

**Comment by gpei** [comment]
/pj-rehearse pull-ci-openshift-installer-master-azure-default-config-minimal-permission

**Comment by gpei** [comment]
@patrickdillon @r4f4 In the [test job](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/59559/rehearse-59559-pull-ci-openshift-installer-master-azure-default-config-minimal-permission/1864595342708707328) , I'm seeing an error that seems the SP of dev account for `azure4` cluster doesn't have the permission to create a new SP so the step `azure-provision-service-principal-minimal-permission` failed. 

Do we want to apply for the additional permission for it or let's move forward without using the minimal permission here?
cc @jianlinliu @jinyunma

**Comment by r4f4** [comment]
> @patrickdillon @r4f4 In the [test job](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/59559/rehearse-59559-pull-ci-openshift-installer-master-azure-default-config-minimal-permission/1864595342708707328) , I'm seeing an error that seems the SP of dev account for `azure4` cluster doesn't have the permission to create a new SP so the step `azure-provision-service-principal-minimal-permission` failed.
> 
> Do we want to apply for the additional permission for it or let's move forward without using the minimal permission here? cc @jianlinliu @jinyunma

How are we doing a minimal permissions install in Azure? Are we using a different cluster profile? Or are we creating a custom SP in the CI step and using that for the installation as with AWS?

**Comment by gpei** [comment]
> Or are we creating a custom SP in the CI step and using that for the installation as with AWS?

Yes, that's the way we're using for the step `azure-provision-service-principal-minimal-permission`, new SP and custom role created with the required minimal permissions.

**Comment by r4f4** [comment]
> > Or are we creating a custom SP in the CI step and using that for the installation as with AWS?
> 
> Yes, that's the way we're using for the step `azure-provision-service-principal-minimal-permission`, new SP and custom role created with the required minimal permissions.

So what about we rename the job and remove the `minimal-permissions` and either introduce that change later or as a separate job? Ideally we'd want to do like AWS and make all presubmits use minimal permissions so we test multiple cluster configurations + permissions combinations.

**Comment by gpei** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-azure-default-config

**Comment by gpei** [comment]
The generated install-config.yaml in the [`e2e-azure-default-config` job](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/59559/rehearse-59559-pull-ci-openshift-installer-master-e2e-azure-default-config/1866428200943357952/artifacts/e2e-azure-default-config/ipi-install-install/build-log.txt)

```
apiVersion: v1
metadata:
  name: ci-op-xvtpjik5-95346
sshKey: |...
baseDomain: ci.azure.devcluster.openshift.com
platform:
  azure:
    baseDomainResourceGroupName: os4-common
    region: eastus
controlPlane:
  architecture: amd64
  name: master
  platform: {}
compute:
- architecture: amd64
  name: worker
  replicas: 3
  platform: {}
```

**Comment by gpei** [comment]
@r4f4 would you mind approving this if no issue from your side?

**Review by r4f4 — COMMENTED** [review]
/approve

**Pull request merged**
