### PR TITLE
Vsphere 416

### PR DESCRIPTION
**Pull request by paigerube14**

### CODE REVIEW

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-vsphere-4.16-nightly-x86-node-density-heavy-24nodes pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-vsphere-4.16-nightly-x86-control-plane-10nodes pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-vsphere-4.15-nightly-x86-control-plane-10nodes

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-vsphere-4.16-nightly-x86-node-density-heavy-24nodes pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-vsphere-4.16-nightly-x86-control-plane-10nodes pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-vsphere-4.15-nightly-x86-control-plane-10nodes

**Comment by paigerube14** [comment]
@jcpowermac no, the configurations I'm testing here are part of our 4.16 regression performance and scale tests we are currently needing to run and validate
These configurations are more for "as-needed" tests that will not be ran consistently/on a cron schedule 

CC: @qiliRedHat @rpattath

**Comment by jcpowermac** [comment]
> @jcpowermac no, the configurations I'm testing here are part of our 4.16 regression performance and scale tests we are currently needing to run and validate These configurations are more for "as-needed" tests that will not be ran consistently/on a cron schedule
> 
> CC: @qiliRedHat @rpattath

Your configuration is over the amount of CPUs we have in that cluster

24 workers * 16 CPUs = 384

that cluster only has 192 cores
plus there will be other jobs running there

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-vsphere-4.16-nightly-x86-control-plane-24nodes

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-vsphere-4.15-nightly-x86-control-plane-24nodes

**Pull request closed without merging**
