### PR TITLE
Openshift pipelines zstream 4.16 and firewatch updates

### PR DESCRIPTION
**Pull request by smatula**

### CODE REVIEW

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.14-openshift-pipelines-ocp4.15-lp-interop-openshift-pipelines-interop-ibmcloud periodic-ci-openshift-pipelines-release-tests-release-v1.14-openshift-pipelines-ocp4.16-lp-interop-openshift-pipelines-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.14-openshift-pipelines-ocp4.16-lp-interop-openshift-pipelines-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.14-openshift-pipelines-ocp4.15-lp-interop-openshift-pipelines-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.14-openshift-pipelines-ocp4.15-lp-interop-openshift-pipelines-interop-ibmcloud periodic-ci-openshift-pipelines-release-tests-release-v1.14-openshift-pipelines-ocp4.16-lp-interop-openshift-pipelines-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.14-openshift-pipelines-ocp4.15-lp-interop-openshift-pipelines-interop-ibmcloud periodic-ci-openshift-pipelines-release-tests-release-v1.14-openshift-pipelines-ocp4.16-lp-interop-openshift-pipelines-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.14-openshift-pipelines-ocp4.15-lp-interop-openshift-pipelines-interop-ibmcloud periodic-ci-openshift-pipelines-release-tests-release-v1.14-openshift-pipelines-ocp4.16-lp-interop-openshift-pipelines-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.14-openshift-pipelines-ocp4.15-lp-interop-openshift-pipelines-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.14-openshift-pipelines-ocp4.15-lp-interop-openshift-pipelines-interop-ibmcloud periodic-ci-openshift-pipelines-release-tests-release-v1.14-openshift-pipelines-ocp4.16-lp-interop-openshift-pipelines-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.14-openshift-pipelines-ocp4.15-lp-interop-openshift-pipelines-interop-ibmcloud periodic-ci-openshift-pipelines-release-tests-release-v1.14-openshift-pipelines-ocp4.16-lp-interop-openshift-pipelines-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.14-openshift-pipelines-ocp4.15-lp-interop-openshift-pipelines-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.14-openshift-pipelines-ocp4.15-lp-interop-openshift-pipelines-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.14-openshift-pipelines-ocp4.15-lp-interop-openshift-pipelines-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.15-lp-interop-openshift-pipelines-interop-ibmcloud periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.16-lp-interop-openshift-pipelines-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.15-lp-interop-openshift-pipelines-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.15-lp-interop-openshift-pipelines-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.15-lp-interop-openshift-pipelines-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.16-lp-interop-openshift-pipelines-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.16-lp-interop-openshift-pipelines-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.15-lp-interop-openshift-pipelines-interop-ibmcloud periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.16-lp-interop-openshift-pipelines-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.16-lp-interop-openshift-pipelines-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.16-lp-interop-openshift-pipelines-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.16-lp-interop-openshift-pipelines-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.16-lp-interop-openshift-pipelines-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.16-lp-interop-openshift-pipelines-interop-ibmcloud

**Review by srivickynesh — APPROVED** [review]
/lgtm

**Review by VeereshAradhya — APPROVED** [review]

**Pull request merged**
