### PR TITLE
rhel9 building marketplace

### PR DESCRIPTION
**Pull request by grokspawn**

### CODE REVIEW

**Review by ankitathomas — APPROVED** [review]
/lgtm

**Comment by ankitathomas** [comment]
/pj-rehearse pull-ci-operator-framework-operator-marketplace-release-4.15-okd-images

**Comment by ankitathomas** [comment]
/pj-rehearse pull-ci-operator-framework-operator-marketplace-release-4.15-okd-scos-e2e-aws

**Comment by perdasilva** [comment]
/pj-rehearse pull-ci-operator-framework-operator-marketplace-release-4.15-okd-e2e-gcp

**Comment by perdasilva** [comment]
/pj-rehearse pull-ci-operator-framework-operator-marketplace-release-4.15-okd-e2e-gcp

**Pull request closed without merging**
