### PR TITLE
telco: Mark AWS telco jobs with specific tags

### PR DESCRIPTION
**Pull request by sshnaidm**
Mark resources in AWS telco jobs with specific tags - for jobs, repos, release etc.
[CNF-10868](https://issues.redhat.com//browse/CNF-10868)

### CODE REVIEW

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-master-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-master-e2e-aws-ran-profile pull-ci-openshift-kni-cnf-features-deploy-release-4.15-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-release-4.15-e2e-aws-ran-profile

**Comment by ffromani** [comment]
/approve

LGTM for numaresources-operator

**Review by donpenney — APPROVED** [review]

**Comment by Tal-or** [comment]
/approve

LGTM for mixed-cpu-node-plugin

**Review by jzding — APPROVED** [review]
/lgtm

**Pull request merged**
