### PR TITLE
Snapshot oldest prometheus data

### PR DESCRIPTION
**Pull request by dgrisonnet**
A recent change in the cluster-monitoring-operator will delete one of
the PVC of Prometheus if both instances aren't spread on multiple nodes.
To make sure that we always gather the most possible amount of data from
Prometheus in CI, we need to snapshot the data from the instance with
the oldest PVC instead of the previously hardcoded prometheus-k8s-0
instance.

/cc @simonpasquier

### CODE REVIEW

**Comment by dgrisonnet** [comment]
@simonpasquier I addressed your comment, PTAL.

/unhold

**Comment by dgrisonnet** [comment]
Failures still seem to be unrelated to the changes from this PR. PTAL @stbenjam @iamemilio

**Comment by wking** [comment]
looks reasonable to me.  But the current split into commits seems somewhat artificial.  For example, af098eb1e11 renames `monitoring_pod` to `prometheus`, but doesn't update all the consumers.  And 4e9c40b2408 updates the consumers to use `prometheus`, and also includes an orthogonal four-to-two indent adjustment.  Can we squash down to a single commit, or a single commit per file group, or some such?

**Pull request merged**
