### PR TITLE
feat: add cleanup private repos

### PR DESCRIPTION
**Pull request by tisutisu**
Add cleaning up of the quay private repos in the CronJob.

### CODE REVIEW

**Review by mmorhun — APPROVED** [review]

**Comment by tisutisu** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-e2e-tests-main-appstudio-dump-external-resources

**Comment by tisutisu** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-e2e-tests-main-appstudio-dump-external-resources

**Comment by tisutisu** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-e2e-tests-main-appstudio-dump-external-resources

**Pull request merged**
