### PR TITLE
Release controllers configurations for 4.12

### PR DESCRIPTION
**Pull request by danilo-gemoli**
The following configurations have been created and bumped:
- release-ocp-4.12-arm64.json
- release-ocp-4.12-multi.json
- release-ocp-4.12-ppc64le.json
- release-ocp-4.12-s390x.json
- release-ocp-4.12.json
- release-okd-4.12.json

Exceptions:
- `core-services/release-controller/_releases/release-ocp-4.12-ci.json` has already been created and bumped here: [#27829](https://github.com/openshift/release/pull/27829/commits/ab461f4da6b63bb16644136036194d52bd1c2120)
- `make openshift-image-mirror-mappings` has already been issued here: [#27829](https://github.com/openshift/release/pull/27829/commits/b41b5f2bc0a85180263f111e595280298fa41b09)

/cc @jmguzik

### CODE REVIEW

**Comment by smg247** [comment]
@danilo-gemoli you should be able to use the `override` command to override the failing `check-gh-automation` once this PR is `lgtm`'d. I am going to add an ignore to this job for the `openshift/multiarch` "repo" since it isn't an actual repo, but I am trying to batch all these cases up and do them at once so it isn't ready yet.

**Review by jmguzik — COMMENTED** [review]
@danilo-gemoli Seems to be Ok. Before bot merge, let's get lgtm also from @deepsm007

**Comment by jmguzik** [comment]
/cc @deepsm007 
Kindly please look at it. We discussed this yesterday here: https://github.com/openshift/release/pull/25517#issuecomment-1148323640

**Comment by deepsm007** [comment]
/lgtm 
Configs for 4.12 looking good

**Review by deepsm007 — APPROVED** [review]

**Pull request merged**
