### PR TITLE
[CIGolang]support golang test image

### PR DESCRIPTION
**Pull request by kuiwang02**
It supports UI test to unblock #24052

/cc @jianzhangbjz @yapei 

Please do not review it now. I am still trying it. 
After it is done, I will notice you to review it.

Thanks

### CODE REVIEW

**Comment by kuiwang02** [comment]
@jianzhangbjz @yapei 
the test pass. please review it and approve it.
Thanks

**Comment by yapei** [comment]
LGTM, thanks @kuiwang02

**Review by yapei — APPROVED** [review]
/lgtm

**Pull request merged**
