### PR TITLE
request token for ocp-perfscale

### PR DESCRIPTION
**Pull request by mohit-sheth**
following https://docs.ci.openshift.org/docs/how-tos/use-registries-in-build-farm/#how-do-i-get-a-token-for-programmatic-access-to-the-central-ci-registry to get a token for ocp-perfscale team

### CODE REVIEW

**Comment by mohit-sheth** [comment]
@chaitanyaenr @jtaleric PTAL

**Review by chaitanyaenr — APPROVED** [review]
/lgtm

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
