### PR TITLE
Add periodic jobs for kubernetes-nmstate

### PR DESCRIPTION
**Pull request by creydr**
Adds periodic jobs to run the e2e test of kubernetes-nmstate against the current release and nightly builds.

In addition this PR adds the k-nmstate e2e tests as a workflow, so it can be reused (ca47dbf492eb2f3a795036f3adf276894da0fe6f).

### CODE REVIEW

**Comment by cybertron** [comment]
It looks like the cluster is failing to stand up in the nightly job, and I see in forum-metal-platform that the 4.10 release is red. This may be failing on something unrelated.

Otherwise it lgtm.

**Comment by creydr** [comment]
> It looks like the cluster is failing to stand up in the nightly job, and I see in forum-metal-platform that the 4.10 release is red. This may be failing on something unrelated.
> 
> Otherwise it lgtm.

Yes seems so. I will retest tomorrow (passed already a couple of times https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/rehearse-25346-periodic-ci-openshift-kubernetes-nmstate-master-e2e-sdn-ipv4-nightly-periodic)

**Comment by creydr** [comment]
@cybertron: the nightly passed. Could you PTAL again?

**Comment by cybertron** [comment]
/lgtm

\o/

**Comment by creydr** [comment]
@jupierce could you PTAL at this PR?
Thanks in advance

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
