### PR TITLE
Run cluster-image-registry-operator tests on vsphere

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by dmage** [comment]
/assign @bparees 

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/7205/rehearse-7205-pull-ci-openshift-cluster-image-registry-operator-master-e2e-vsphere-operator/7

the tests are red, but we can run them!

**Comment by bparees** [comment]
/approve

@dmage let's see it rehearse green before merging

**Comment by dmage** [comment]
@bparees we can wait until e2e-vsphere is green, but e2e-vsphere-operator is expected to be red on baremetal/vsphere today. We have a pending PR openshift/cluster-image-registry-operator#458 that introduces some common setup functions and makes it easier to fix tests on vsphere, so I'd like to land it first. Also it'll be easier to fix tests if we have the e2e-vsphere-operator job.

**Comment by bparees** [comment]
> @bparees we can wait until e2e-vsphere is green, but e2e-vsphere-operator is expected to be red on baremetal/vsphere today. We have a pending PR openshift/cluster-image-registry-operator#458 that introduces some common setup functions and makes it easier to fix tests on vsphere, so I'd like to land it first. Also it'll be easier to fix tests if we have the e2e-vsphere-operator job.

ok that's reasonable.  i've marked the PR approved, so just find someone from devex to lgtm it once you're satisfied e2e-vsphere at least is passing.

**Comment by dmage** [comment]
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/7205/rehearse-7205-pull-ci-openshift-cluster-image-registry-operator-master-e2e-vsphere/8
```
dial tcp 139.178.87.140:10250: connect: connection refused
```

/test pj-rehearse

**Comment by dmage** [comment]
```
failed to acquire lease
```

/test pj-rehearse

**Comment by dmage** [comment]
```
failed to acquire lease
```

/test pj-rehearse

**Comment by ricardomaraschini** [comment]
Why are not these rehearse jobs not passing?

**Comment by dmage** [comment]
@ricardomaraschini because the registry bootstraps itself as Removed on this platform, and our tests aren't ready for that.

**Pull request merged**
