### PR TITLE
Add fcami to openshift-psap/ci-artifacts/OWNERS

### PR DESCRIPTION
**Pull request by kpouget**
cc @jmencak

### CODE REVIEW

**Comment by jmencak** [comment]
Thank you Kevin!
/lgtm

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Comment by ArangoGutierrez** [comment]
@fcami @kpouget @ashishkamra 
Looks like @fcami is on in the openshift org yet , see:
https://github.com/orgs/openshift/people?query=fc

**Comment by fcami** [comment]
> @fcami @kpouget @ashishkamra Looks like @fcami is on in the openshift org yet , see: https://github.com/orgs/openshift/people?query=fc

I sent an email to the OpenShift org owners a few days ago and got no answer yet.

**Comment by fcami** [comment]
@ArangoGutierrez @kpouget @ashishkamra This is done.

**Pull request merged**
