### PR TITLE
add linting to aws-provider presubmits

### PR DESCRIPTION
**Pull request by paulfantom**
CI for https://github.com/openshift/cluster-api-provider-aws/pull/36

/CC: @enxebre

### CODE REVIEW

**Comment by petr-muller** [comment]
You do not have `branches: ` specified in any of the new jobs, which makes such jobs run on all branches. Which is probably fine, but then it is not needed to add them to both files under different names.

**Comment by paulfantom** [comment]
@petr-muller thanks! :+1:

**Comment by enxebre** [comment]
@paulfantom based on @petr-muller comment wouldn't it make sense to remove branch: from unit?
/lgtm

**Comment by petr-muller** [comment]
> @paulfantom based on @petr-muller comment wouldn't it make sense to remove branch: from unit?

It's a little tricky for ci-operator jobs, because they need to have a reference to a ConfigMap with ci-operator config which is branch-based:

```
configMapKeyRef:
  key: master.json
```

**Pull request merged**
