### PR TITLE
[ospdo] bump golangci-lint and golang version for openstack-director-operator

### PR DESCRIPTION
**Pull request by stuggi**
bumps golangci-lint to v1.59.1 and golang to 1.21

### CODE REVIEW

**Comment by stuggi** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-osp-director-operator-master-gofmt

**Comment by stuggi** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-osp-director-operator-master-golangci

**Comment by stuggi** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-osp-director-operator-master-golint

**Comment by stuggi** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-osp-director-operator-master-golangci

**Comment by stuggi** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-osp-director-operator-master-golangci

**Comment by stuggi** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-osp-director-operator-master-golint

**Comment by stuggi** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-osp-director-operator-master-unit

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
