### PR TITLE
chore: update rhtap jobs to use ocp 4.13

### PR DESCRIPTION
**Pull request by psturc**
Depends on
* https://github.com/openshift/release/pull/47583

### CODE REVIEW

**Review by dirgim — APPROVED** [review]
/approve

**Review by johnmcollier — APPROVED** [review]
/approve
/lgtm

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests

**Comment by psturc** [comment]
[seems like a test flake](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/47581/rehearse-47581-pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1747179813493280768#1:build-log.txt%3A1011)

/pj-rehearse ack

**Pull request merged**
