### PR TITLE
OKD: build cluster-update-keys from Dockerfile

### PR DESCRIPTION
**Pull request by vrutkovs**
Build `cluster-update-keys` in payloads from Dockerfile
 (instead of Dockerfile.rhel) so that valid CI keys would be used
 to verify payloads.

Related: https://github.com/openshift/okd/issues/426

### CODE REVIEW

**Comment by smarterclayton** [comment]
lgtm when it's passing

**Comment by vrutkovs** [comment]
/retest

Flakes in `master-okd-e2e-aws`, odd oauth issues in `release-4.6/okd-e2e-aws` and `release-4.6/okd-e2e-aws-upgrade`

**Comment by vrutkovs** [comment]
/retest

boskos issues

**Comment by vrutkovs** [comment]
/hold

Somehow a bad FCOS has been promoted, fixing it in https://github.com/openshift/okd-machine-os/pull/49

**Comment by vrutkovs** [comment]
/retest

4.6 and 4.7 installs should now pass

**Comment by vrutkovs** [comment]
/hold cancel

most of the tests are now passing, ready for review. @smarterclayton PTAL

**Pull request merged**
