### PR TITLE
MGMT-14632: Remove 4.8 jobs

### PR DESCRIPTION
**Pull request by danmanor**
As part of the effort to remove support for openshift version <= 4.8, I remove the 4.8 CI jobs

### CODE REVIEW

**Comment by adriengentil** [comment]
There are also some references in assisted-installer and assisted-installer-agent repos.
https://github.com/search?q=repo%3Aopenshift%2Frelease+OPENSHIFT_VERSION%3D4.8&type=code

**Comment by danmanor** [comment]
@osherdp I think there is something wrong with `ci/prow/config`

**Review by osherdp — APPROVED** [review]

**Comment by adriengentil** [comment]
these is still the one in https://github.com/openshift/release/blob/master/ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master__edge.yaml#L226

**Pull request merged**
