### PR TITLE
MCO add dedicated job: upi azure fips

### PR DESCRIPTION
**Pull request by sergiordlr**
MCO add UPI Azure FIPS dedicated job

### CODE REVIEW

**Comment by sergiordlr** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-azure-stack-upi-fips-longduration-mco-g1-f9 periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-azure-stack-upi-fips-longduration-mco-g2-f9

**Comment by sergiordlr** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-azure-stack-upi-fips-longduration-mco-g1-f9 periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-azure-stack-upi-fips-longduration-mco-g2-f9

**Comment by ptalgulk01** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-azure-stack-upi-fips-longduration-mco-g1-f9 periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-azure-stack-upi-fips-longduration-mco-g2-f9

**Comment by ptalgulk01** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-azure-stack-upi-fips-longduration-mco-g1-f9 periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-azure-stack-upi-fips-longduration-mco-g2-f9

**Comment by sergiordlr** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-azure-stack-upi-fips-longduration-mco-g1-f9 periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-azure-stack-upi-fips-longduration-mco-g2-f9

**Comment by ptalgulk01** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-azure-stack-upi-fips-longduration-mco-g1-f9 periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-azure-stack-upi-fips-longduration-mco-g2-f9

**Comment by ptalgulk01** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-azure-stack-upi-fips-longduration-mco-g1-f9 periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-azure-stack-upi-fips-longduration-mco-g2-f9

**Pull request closed without merging**
