### PR TITLE
Bump e2e-benchmarking and enable service-latency measurement in 4.15 and 4.16 in cdv2

### PR DESCRIPTION
**Pull request by rsevilla87**
Release notes: https://github.com/cloud-bulldozer/e2e-benchmarking/pull/685

PS: The --service-latency flag needs at least kube-burner-ocp 1.2.0

### CODE REVIEW

**Comment by rsevilla87** [comment]
cc: @afcollins @jtaleric

**Comment by rsevilla87** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-control-plane-120nodes

**Review by afcollins — CHANGES_REQUESTED** [review]
Significant log spam from these changes we should fix in the tool before merging.
```
time="2024-03-06 11:59:48" level=error msg="timeout waiting for endpoint 172.30.45.192:80 to be ready" file="service_latency.go:162"
$ grep -c "service_latency.go:162" build-log.txt 
7620
$ wc -l build-log.txt 
    9847 build-log.txt
```

**Comment by rsevilla87** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-control-plane-120nodes

**Comment by jtaleric** [comment]
I looked at another 4.16 120 node run to make sure our timings were similar (https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-control-plane-120nodes/1767883430537728000) 🚢

**Comment by rsevilla87** [comment]
> Significant log spam from these changes we should fix in the tool before merging.
> 
> ```
> time="2024-03-06 11:59:48" level=error msg="timeout waiting for endpoint 172.30.45.192:80 to be ready" file="service_latency.go:162"
> $ grep -c "service_latency.go:162" build-log.txt 
> 7620
> $ wc -l build-log.txt 
>     9847 build-log.txt
> ```

there was an issue with the kube-burner payload, ignore these logs

**Pull request merged**
