### PR TITLE
azure - test adhoc workflow

### PR DESCRIPTION
**Pull request by mjudeikis**
@charlesakalugwu @kargakis I would like to merge this to test if we could use this way to execute part of the release workflow. 

This is development only and if this works, we might need to run our own prow or use only prow in some cases.

### CODE REVIEW

**Comment by kargakis** [comment]
```
    if job["spec"]["containers"][0]["command"][0] != "ci-operator":
KeyError: 'command'
```
@stevekuznetsov @petr-muller seems that prowjobs now require to use `ci-operator`? Can we relax this? We need to a new flow here.

**Comment by stevekuznetsov** [comment]
You're not reading that correctly. Decorated jobs must expose a command and you're getting a key error

**Comment by mjudeikis** [comment]
lets test this stuff :) thanks @charlesakalugwu @stevekuznetsov

**Comment by stevekuznetsov** [comment]
Can you guys at least give an attempt to test it without merging? We invested a lot of effort to give you the staging namespace to let you do that simply ...

**Comment by kargakis** [comment]
I hope we can take advantage of the staging namespace and not have to
deploy prow ourselves. MJ I hope you are unblocked now and can proceed with
upgrade testing anyway.

**Comment by stevekuznetsov** [comment]
It's linked in the READMEil I have personally linked to you numerous times in the last two weeks.

**Comment by stevekuznetsov** [comment]
https://github.com/openshift/release/blob/master/ci-operator/README.md#testing-with-mkpj-and-mkpod

**Comment by kargakis** [comment]
Where did you link it previously? It's the first time I come across it.
Likely missed it elsewhere, sorry.

I assume everyone has access to create jobs in the staging namespace. If
so, this should probably work for us, thanks

**Comment by bbguimaraes** [comment]
Yes, any authenticated user can create pods in that namespace.

You can also create `ConfigMap`s to test new templates.

**Comment by kargakis** [comment]
In order to test templates we need to add secrets to the namespace so it would be nice to remove access to secrets from everyone and use the secret mirroring controller for syncing.

**Comment by kargakis** [comment]
Though I guess if you can run any pod, you are able to mount any secret. Is it possible to run these test pods directly in our namespace?

**Comment by bbguimaraes** [comment]
Secrets are already mirrored to the staging namespace using the controller:

https://github.com/openshift/release/blob/master/cluster/ci/config/secret-mirroring/mapping.yaml

If the template requires a new secret, that secret can be added to the cluster separately, then mirrored and used in the staging namespace.

Testing jobs in your namespace would amount to reproducing the staging namespace, and that is exactly why we created it.

**Pull request merged**
