### PR TITLE
Add NVIDIA GPU Operator jobs on OCP 4.18

### PR DESCRIPTION
**Pull request by empovit**
Use 4.17 catalog sources until the NFD in NVIDIA GPU operators
are available in the 4.18 catalog.

### CODE REVIEW

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-nvidia-ci-main-4.18-nvidia-gpu-operator-e2e-master

**Review by wabouhamad — COMMENTED** [review]
/lgtm

**Review by wabouhamad — COMMENTED** [review]
/lgtm

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-nvidia-ci-main-4.18-nvidia-gpu-operator-e2e-24-6-x periodic-ci-rh-ecosystem-edge-nvidia-ci-main-4.18-nvidia-gpu-operator-e2e-24-9-x	periodic-ci-rh-ecosystem-edge-nvidia-ci-main-4.18-nvidia-gpu-operator-e2e-master

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-nvidia-ci-main-4.18-nvidia-gpu-operator-e2e-24-9-x periodic-ci-rh-ecosystem-edge-nvidia-ci-main-4.18-nvidia-gpu-operator-e2e-master

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-nvidia-ci-main-4.18-nvidia-gpu-operator-e2e-24-9-x periodic-ci-rh-ecosystem-edge-nvidia-ci-main-4.18-nvidia-gpu-operator-e2e-master

**Pull request merged**
