### PR TITLE
Add crun variant to e2e installer

### PR DESCRIPTION
**Pull request by harche**
This PR add `crun` variant to the e2e installer 

Signed-off-by: Harshal Patil <harpatil@redhat.com>

### CODE REVIEW

**Comment by harche** [comment]
Corresponding PR in cluster-bot repo - https://github.com/openshift/ci-chat-bot/pull/233

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by haircommander** [comment]
```
# echo $hash | base64 -d 
[crio.runtime]
default_runtime = "crun"
[crio.runtime.runtimes.runc]
runtime_path = ""
runtime_type = "oci"
runtime_root = "/run/runc"
runtime_config_path = ""
[crio.runtime.runtimes.crun]
runtime_path = ""
runtime_type = "oci"
runtime_root = "/run/crun"
runtime_config_path = ""
```

I think we should reduce this to 
```
[crio.runtime]
default_runtime = "crun"
[crio.runtime.runtimes.crun]
runtime_root = "/run/crun"
```
(or hash `W2NyaW8ucnVudGltZV0KZGVmYXVsdF9ydW50aW1lID0gImNydW4iCltjcmlvLnJ1bnRpbWUucnVudGltZXMuY3J1bl0KcnVudGltZV9yb290ID0gIi9ydW4vY3J1biIK`)
which follows our practice of specifying as few config fields as possible to allow cri-o to control the defaults

**Comment by staebler** [comment]
The installer team no longer provides support for that template. If you would like to add new features to that template, then please take ownership of the template by adding reviewers and approvers to the OWNERS file.

**Comment by harche** [comment]
> The installer team no longer provides support for that template. If you would like to add new features to that template, then please take ownership of the template by adding reviewers and approvers to the OWNERS file.

Thanks @staebler. We just wanted to add support for `crun` runtime in cluster-bot. I just followed what we did in case of [cgroups v2](https://github.com/openshift/release/pull/19956). I do not think from the node team we have the expertise to the take ownership and handle reviewes for that installer file. 

Is there any alternate way we could still make this work?

**Comment by harche** [comment]
Thanks @haircommander for https://github.com/openshift/release/pull/23610#issuecomment-983690244. 

/hold till we update PR with that suggestion.

**Comment by staebler** [comment]
> 

Maybe reach out to the owners of cluster-bot then. If cluster-bot wants to continue using this template, then they should take ownership of this template. If they have plans to switch over to using the workflows instead, then I recommend providing steps for adding crun rather than updating this template.

**Comment by harche** [comment]
> > 
> 
> Maybe reach out to the owners of cluster-bot then. If cluster-bot wants to continue using this template, then they should take ownership of this template. If they have plans to switch over to using the workflows instead, then I recommend providing steps for adding crun rather than updating this template.

Thanks @staebler. 

@bradmwilliams since cluster bot uses that installer file, can anyone from cluster bot take the ownership as suggested by @staebler ?

**Comment by bradmwilliams** [comment]
Simply to facilitate cluster-bot changes to the templates, I have created: https://github.com/openshift/release/pull/24198.
However, the truth of the matter is that these templates are largely unsupported now (by both the installer and CI teams) and every effort should be made to migrate your installation changes to the step-registry sooner than later.

**Comment by harche** [comment]
Thanks @bradmwilliams. I have updated this PR and it's ready to merge for now. 

But we will move to using step registry in future and to track that effort I have created a jira story - https://issues.redhat.com/browse/OCPNODE-802

**Review by bradmwilliams — APPROVED** [review]

**Pull request merged**
