### PR TITLE
Stackrox: remove postgres e2e from nightlies

### PR DESCRIPTION
**Pull request by gavin-stackrox**
Postgres e2e tests are not ready to run in release mode.

/cc @theencee @house-d

### CODE REVIEW

**Comment by theencee** [comment]
Still confused how it ever worked. I can't review the PR but lgtm

**Comment by gavin-stackrox** [comment]
@theencee we used to skip the test in `rox` code. 
if you onboard to OSCI you can `/lgtm` ;) https://docs.engineering.redhat.com/display/StackRox/Onboarding+to+OpenShift+GitHub+Organization

**Review by sbostick — APPROVED** [review]
LGTM

**Comment by gavin-stackrox** [comment]
Closing, handled by #32533

**Pull request closed without merging**
