### PR TITLE
jobs: opt out of pod utils with custom dirs

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Review by alvaroaleman — APPROVED** [review]
/hold

**Comment by stevekuznetsov** [comment]
part of DPTP-1819

**Review by alvaroaleman — APPROVED** [review]
/hold cancel

**Comment by stevekuznetsov** [comment]
Looks like our auto-update PR got this.

/close

**Pull request closed without merging**
