### PR TITLE
Enable Console e2e tests on Console Operator

### PR DESCRIPTION
**Pull request by jhadvig**
@ecordell PTAL

@benjaminapetersen fyi

### CODE REVIEW

**Comment by spadgett** [comment]
I'd suggest `e2e-aws-console-login` as the name so it's not confused with the full e2e suite

**Comment by spadgett** [comment]
Or we could run the full console e2e tests. They've been pretty reliable.

**Comment by spadgett** [comment]
cc @enj

**Comment by jhadvig** [comment]
@spadgett updated

**Comment by spadgett** [comment]
It looks like adding just the login tests fail because it tries to delete the test namespace that was never created:

```
Last browser URL:  https://console-openshift-console.apps.ci-op-03m60f7q-d180a.origin-ci-int-aws.dev.rhcloud.com/settings/cluster
Error from server (NotFound): namespaces "test-kffee" not found
[15:04:42] E/launcher - BUG: launcher exited with 1 tasks remaining
```

That has been fixed in 4.2 (master-next) by https://github.com/openshift/console/pull/1523

No longer an issue for this PR since we run the full e2e

**Pull request merged**
