### PR TITLE
Scorecard Testing for NMO & FAR Bundle Directories

### PR DESCRIPTION
**Pull request by razo7**
Add [Scorecard testing](https://sdk.operatorframework.io/docs/testing-operators/scorecard/) for FAR and NMO in OCP CI, after a failed try in [upstream NMO](https://github.com/medik8s/node-maintenance-operator/pull/67).

It is done also done downstream (as part of CVP) on multiple OCP versions whereas here it is done only once. I didn't see a real point in adding this test per OCP version.

### CODE REVIEW

**Comment by razo7** [comment]
/pj-rehearse pull-ci-medik8s-node-maintenance-operator-main-4.15-openshift-scorecard-bundle-2

**Comment by razo7** [comment]
/pj-rehearse pull-ci-medik8s-node-maintenance-operator-main-4.15-openshift-scorecard-bundle-2

**Comment by razo7** [comment]
/pj-rehearse pull-ci-medik8s-node-maintenance-operator-main-4.15-openshift-scorecard-bundle-2

**Comment by razo7** [comment]
/pj-rehearse pull-ci-medik8s-node-maintenance-operator-main-4.15-openshift-scorecard-bundle-2

**Comment by razo7** [comment]
/pj-rehearse pull-ci-medik8s-node-maintenance-operator-main-4.15-openshift-scorecard-bundle-2

**Comment by razo7** [comment]
/pj-rehearse pull-ci-medik8s-node-maintenance-operator-main-4.15-openshift-scorecard-bundle-2

**Comment by razo7** [comment]
/pj-rehearse pull-ci-medik8s-node-maintenance-operator-main-4.15-openshift-scorecard-bundle

**Comment by razo7** [comment]
/pj-rehearse pull-ci-medik8s-node-maintenance-operator-main-4.16-openshift-scorecard-bundle

**Comment by razo7** [comment]
/pj-rehearse pull-ci-medik8s-fence-agents-remediation-main-4.16-openshift-scorecard-bundle

**Comment by razo7** [comment]
/pj-rehearse pull-ci-medik8s-fence-agents-remediation-main-4.16-openshift-scorecard-bundle

**Comment by slintes** [comment]
/hold

I have some doubts, discussing offline

**Comment by slintes** [comment]
closing in favor of https://github.com/medik8s/node-maintenance-operator/pull/129

/close

**Pull request closed without merging**
