### PR TITLE
4.10: add periodic UPI jobs for AWS, GCP, Azure, and Azurestack

### PR DESCRIPTION
**Pull request by r4f4**
https://issues.redhat.com/browse/CORS-1786

### CODE REVIEW

**Comment by patrickdillon** [comment]
This LGTM (as evidenced by my tags), but I do not have experience adding release informing jobs so I added to hold, wondering if someone from TRT could take a look. I will ping them in slack because I don't see a gh group.

**Comment by dgoodwin** [comment]
This is just adding new 4.10 periodics, not informing jobs, is that correct? (informing being jobs attached to payloads that do not block promotion of the payload, periodics just being jobs run on a schedule) Based on the attached Jira I'm assuming periodic. I'm actually not great with this configuration so I'm not sure I can lgtm, but from what I can see, lgtm. :)

**Comment by deepsm007** [comment]
> This is just adding new 4.10 periodics, not informing jobs, is that correct? (informing being jobs attached to payloads that do not block promotion of the payload, periodics just being jobs run on a schedule) Based on the attached Jira I'm assuming periodic. I'm actually not great with this configuration so I'm not sure I can lgtm, but from what I can see, lgtm. :)

Yes, these are only periodics.

**Pull request merged**
