### PR TITLE
MON-1208: add test-unit job to kube-state-metrics

### PR DESCRIPTION
**Pull request by dgrisonnet**
/cc @paulfantom

### CODE REVIEW

**Comment by dgrisonnet** [comment]
Holding until we are sure we don't want to add this job to the release branches.

/hold

**Comment by paulfantom** [comment]
We are shipping ksm 1.9.x in OpenShift 4.7 so this job won't work there. Even with https://github.com/kubernetes/kube-state-metrics/pull/1327 merged this PR needs to wait for ksm 2.0 rebase.

**Comment by dgrisonnet** [comment]
I was also planning to add the upstream fix to this PR: https://github.com/openshift/kube-state-metrics/pull/41. With both fixes, it should be feasible even though we are not on 2.0, no?

**Comment by paulfantom** [comment]
Sorry I was not aware of that PR.
Yes, with both this will be possible :+1:

**Review by paulfantom — APPROVED** [review]
/lgtm

**Pull request merged**
