### PR TITLE
Remove priority class on SSH sastion deployments

### PR DESCRIPTION
**Pull request by hongkailiu**
Required by https://github.com/openshift/release/pull/18868

/cc @deepsm007

### CODE REVIEW

**Comment by alvaroaleman** [comment]
Can you just remove the priority class of the manifest? This is not more important than node-level things.
/hold

**Comment by hongkailiu** [comment]
> Also I don't think this will even work, the clients need to know the address of the sshd in advance and it will be different for build01 and build02

@deepsm007 

How does the test know which IP is going to be used, from build01 or build02?

**Comment by deepsm007** [comment]
> > Also I don't think this will even work, the clients need to know the address of the sshd in advance and it will be different for build01 and build02
> 
> @deepsm007
> 
> How does the test know which IP is going to be used, from build01 or build02?

The jobs will be updated with  the new bastion ip until we migrate to step-registry (Almost done few tweaks pending)

**Comment by hongkailiu** [comment]
> > > Also I don't think this will even work, the clients need to know the address of the sshd in advance and it will be different for build01 and build02
> > 
> > 
> > @deepsm007
> > How does the test know which IP is going to be used, from build01 or build02?
> 
> The jobs will be updated with the new bastion ip until we migrate to step-registry (Almost done few tweaks pending)

How does a step know which ip to use?
Or it is always hard-coded IP? We need to change the IP when changing the cluster?

**Comment by alvaroaleman** [comment]
> The jobs will be updated with the new bastion ip until we migrate to step-registry (Almost done few tweaks pending)

How exactly does this work, jobs connect in-cluster to the sshd and then what? FTR if this is just in cluster, the jobs can use the DNS name and it will work in both clusters

**Comment by deepsm007** [comment]
> > The jobs will be updated with the new bastion ip until we migrate to step-registry (Almost done few tweaks pending)
> 
> How exactly does this work, jobs connect in-cluster to the sshd and then what? FTR if this is just in cluster, the jobs can use the DNS name and it will work in both clusters

The steps will have dnsConfig pointing to the coredns pod inside bastion to resolve any requests

**Comment by alvaroaleman** [comment]
> The steps will have dnsConfig pointing to the coredns pod inside bastion to resolve any requests

Okay, so what is the purpose of the SSHD?

You can pre-allocate clusterIPs which would allow us to give the service the same IP in both clusters

**Comment by deepsm007** [comment]
> > > > Also I don't think this will even work, the clients need to know the address of the sshd in advance and it will be different for build01 and build02
> > > 
> > > 
> > > @deepsm007
> > > How does the test know which IP is going to be used, from build01 or build02?
> > 
> > 
> > The jobs will be updated with the new bastion ip until we migrate to step-registry (Almost done few tweaks pending)
> 
> How does a step know which ip to use?
> Or it is always hard-coded IP? We need to change the IP when changing the cluster?

Yes, the bastion Ip will be hardcoded in the config depending on the build cluster it will pick.

**Comment by deepsm007** [comment]
> You can pre-allocate clusterIPs which would allow us to give the service the same IP in both clusters

I was not aware of that but it will be helpful. Yes, I can provide ip or we can use the existing ip on build01

**Review by alvaroaleman — APPROVED** [review]
We'll have to manually delete the services on the clusters other than build01 first, as the field is immutable

**Review by alvaroaleman — COMMENTED** [review]
/hold cancel

**Comment by hongkailiu** [comment]
> We'll have to manually delete the services on the clusters other than build01 first, as the field is immutable

Done.

**Pull request merged**
