### PR TITLE
[wip] DNM - Add periodic

### PR DESCRIPTION
**Pull request by jwendell**

### CODE REVIEW

**Comment by yxun** [comment]
Do we need a plugin config folder in https://github.com/openshift/release/tree/master/core-services/prow/02_config/maistra ?

I haven't seen test-infra prow config before.

**Comment by jwendell** [comment]
> Do we need a plugin config folder in https://github.com/openshift/release/tree/master/core-services/prow/02_config/maistra ?
> 
> I haven't seen test-infra prow config before.

I don't think so, at least for now. This is a periodic job, not triggered by any github command.

**Pull request closed without merging**
