### PR TITLE
Move cluster pools' manifests to its own folder

### PR DESCRIPTION
**Pull request by hongkailiu**
Follow up https://github.com/openshift/ci-docs/pull/123#discussion_r616600328

/cc @petr-muller

### CODE REVIEW

**Review by petr-muller — COMMENTED** [review]
I apologize for bikeshedding, but don't we want to maintain multiple pools in a dir? Does not make sense to call a dir `ci-cluster-pool`. Don't we want something like:

```
pools/
pools/openshift-ci/ # our pools
pools/cvp/              # CVP pools
pools/whoever-else
...
```

**Comment by hongkailiu** [comment]
Can I keep the `pool` in the folder name (as well as in name of the project)?
I know it is clear to know it is about the pool if we check the repo and see the parent folder.
But when we do the oc get project on the cluster, we do not have a parent project.

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
