### PR TITLE
WIP: test cq image

### PR DESCRIPTION
**Pull request by avano**

### CODE REVIEW

**Comment by avano** [comment]
/pj-rehearse periodic-ci-jboss-fuse-camel-quarkus-openshift-interop-main-camel-quarkus-ocp4.15-lp-interop-camel-quarkus-interop-aws

**Comment by llowinge** [comment]
@ascerra @oharan2 Please, we only want to run `pj-rehearse` to verify image update works. Does this need any kind of approval ?

**Comment by llowinge** [comment]
+ Can it be in Draft/WIP state to have `pj-rehearse` working ?

**Comment by avano** [comment]
/pj-rehearse periodic-ci-jboss-fuse-camel-quarkus-openshift-interop-main-camel-quarkus-ocp4.15-lp-interop-camel-quarkus-interop-aws

**Pull request closed without merging**
