### PR TITLE
RHDH release 1.4 ci jobs setup

### PR DESCRIPTION
**Pull request by subhashkhileri**
https://issues.redhat.com/browse/RHIDP-5098

### CODE REVIEW

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-release-1.4-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-release-1.4-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-release-1.4-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-release-1.4-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-release-1.4-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse periodic-ci-janus-idp-backstage-showcase-release-1.4-e2e-tests-nightly

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-release-1.4-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-release-1.4-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse periodic-ci-janus-idp-backstage-showcase-release-1.4-e2e-tests-nightly

**Comment by subhashkhileri** [comment]
/pj-rehearse periodic-ci-janus-idp-backstage-showcase-release-1.4-e2e-tests-nightly

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-release-1.4-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-release-1.4-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-release-1.4-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-release-1.4-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse periodic-ci-janus-idp-backstage-showcase-release-1.4-e2e-tests-nightly

**Review by josephca — APPROVED** [review]
/lgtm
/approve

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-release-1.4-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse periodic-ci-janus-idp-backstage-showcase-release-1.4-e2e-tests-nightly

**Pull request merged**
