### PR TITLE
update tests-private with 4.16 tag for rosacli jobs

### PR DESCRIPTION
**Pull request by yuwang-RH**
To use the latest code in master branch, update the tag to 4.16

### CODE REVIEW

**Comment by yuwang-RH** [comment]
@yasun1 Could you help review this pr?Thanks.

**Comment by yuwang-RH** [comment]
@liangxia Could you help review and approve this PR?

**Comment by liangxia** [comment]
ci/prow/check-gh-automation — Pod got deleted unexpectedly

/retest-required

**Pull request merged**
