### PR TITLE
feat: upkeep aws infra

### PR DESCRIPTION
**Pull request by eggfoobar**
update rhel ami to use GA version
update instance type to use graviton 3 cpu

### CODE REVIEW

**Comment by eggfoobar** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-e2e-arm

**Review by pacevedom — COMMENTED** [review]
Just one run for 4.13 and another for 4.14/4.15/main is enough.
/lgtm

**Comment by pacevedom** [comment]
@eggfoobar I would go ahead and ack the rehearsals, failures are looking the same as with rhel 9.1. Rest of the jobs look good and images can be built again.

**Comment by eggfoobar** [comment]
Hmm, I would like to see one ARM success on e2e or conformance, just to make sure we didn't miss anything.

**Comment by eggfoobar** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-e2e-arm
/pj-rehearse pull-ci-openshift-microshift-main-e2e-openshift-conformance-reduced-arm

**Comment by eggfoobar** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-openshift-conformance-reduced-arm

**Pull request merged**
