### PR TITLE
devscripts-setup should look for additional manifests

### PR DESCRIPTION
**Pull request by stbenjam**
[TRT-676](https://issues.redhat.com//browse/TRT-676)

Some CI steps, like Loki configuraiton, inject manifest YAML's into the `$SHARED_DIR`. These should be copied and used by dev-scripts when installing baremetal clusters.

Note, Loki is a log collection tool, accessible under the "Debug tools" view in Prow.  At the moment all jobs have them except metal because metal doesn't currently do anything with the manifests from the CI step.

image

### CODE REVIEW

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-upgrade-ovn-ipv6
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-ovn-ipv4
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-sdn-bm

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-ovn-ipv4

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-sdn-bm

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-upgrade-ovn-ipv6

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-sdn-bm

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-sdn-bm

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-ovn-ipv4

**Comment by stbenjam** [comment]
This should be good to go
- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/35105/rehearse-35105-periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-ovn-ipv4/1610972722882416640 has loki results
- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/35105/rehearse-35105-periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-upgrade-ovn-ipv6/1610302183851429888 does not

**Comment by deepsm007** [comment]
These are just test failures unrelated to the changes of the PR
/lgtm

**Pull request merged**
