### PR TITLE
Use 4.3 cluster instead of 4.4

### PR DESCRIPTION
**Pull request by lmilbaum**
To address flaky CI tests

### CODE REVIEW

**Comment by petr-muller** [comment]
This looks very wrong: that repo is promoting to `ocp:4.4.` and that should not be changed because there is automation that relies on that.

**Comment by lioramilbaum** [comment]
@petr-muller Can you clarify what does that mean 'the repo promoting to ocp:4.4'?

**Comment by petr-muller** [comment]
@lioramilbaum this repository is configured (very likely intentionally) so that CI treats it in almost the exact same way like if it was a part of Openshift proper - same amount if integration testing, and also automated management of configs and jobs etc. by DPTP tools. IIRC the intention was to become coupled like this so that it is eventually easy for this operator become a part of OpenShift. If you change these configs like this, you will:

1) opt-out of all central management of configs (we won't create release branches, won't bump base versions once 4.4 is out to base its master on 4.5, anything)
2) stop publishing the artifacts to 4.4 imagestream and start publishing them to 4.3 imagestream. But the `release-4.3` branch is supposed to publish there, not master. Something in 4.4 probably consumes the artifacts published here, so you will break that something.

In OpenShift world there's no such thing as "use 4.3 cluster instead of 4.4" - master branches all contribute to (and are tested against) the same version of openshift. If you want special behavior you'll be on your own and you should really know what you are doing and be very sure you really want to do just that.

**Comment by lioramilbaum** [comment]
@petr-muller Thanks for the clarification. I am not 100% sure what am I doing. I wasn't aware of those automation around this config. The purpose of this PR is to address flaky tests.  No idea yet what is causing the tests to fail. Was hoping to solve it by a stable deployment.  I might need to move into a different direction.

**Pull request closed without merging**
