### PR TITLE
OSSM maistra Remove git workaround

### PR DESCRIPTION
**Pull request by yxun**
This PR is refactoring previous maistra-istio-e2e workflow and test jobs.
This PR removes unnecessary resource limits and a duplicate maistra-test-mc pod in the workflow.
It also removes the previous workaround of a git config issue.

### CODE REVIEW

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.1-istio-unit-2-1

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-images-centos-maistra-2.2-istio-images-centos-lint-2-2

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-images-centos-maistra-2.3-istio-images-centos-lint-2-3

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-images-centos-maistra-2.4-istio-images-centos-lint-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-api-maistra-2.1-api-gencheck-2-1

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-api-maistra-2.4-api-gencheck-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.3-maistra-istio-integ-aws-2-3

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.3-maistra-istio-integ-kube-multicluster-2-3

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-maistra-istio-integ-aws-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-maistra-istio-integ-kube-multicluster-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.3-maistra-istio-integ-aws-2-3

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.3-maistra-istio-integ-kube-multicluster-2-3

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.3-maistra-istio-integ-aws-2-3

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-maistra-istio-integ-aws-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.3-maistra-istio-integ-aws-2-3

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-maistra-istio-integ-aws-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.3-maistra-istio-integ-aws-2-3

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-maistra-istio-integ-aws-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.3-maistra-istio-integ-aws-2-3

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.1-istio-unit-2-1

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-maistra-istio-integ-aws-2-4

**Review by jwendell — APPROVED** [review]
Do you have a Jira for this? If not, you should create it as I think this was not a 5-min task.

**Pull request merged**
