### PR TITLE
ipi-install-install: Pin and checksum downloaded dependencies

### PR DESCRIPTION
**Pull request by pierreprinetti**
If we execute downloaded scripts without verifying their contents, then our CI infrastructure is only as secure as the most insecure of our dependencies. Which might be someone's Github account.

### CODE REVIEW

**Comment by pierreprinetti** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-aws-ovn pull-ci-openshift-installer-release-4.6-e2e-aws-fips

**Comment by pierreprinetti** [comment]
* pull-ci-openshift-installer-release-4.6-e2e-aws-fips: [install succeeded](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/37321/rehearse-37321-pull-ci-openshift-installer-release-4.6-e2e-aws-fips/1635941366875820032/artifacts/e2e-aws-fips/ipi-install-install/)
* pull-ci-openshift-installer-master-e2e-aws-ovn: [install succeeded](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/37321/rehearse-37321-pull-ci-openshift-installer-master-e2e-aws-ovn/1635941366796128256/artifacts/e2e-aws-ovn/ipi-install-install/)

/pj-rehearse ack

**Review by mandre — COMMENTED** [review]
/lgtm

**Comment by pierreprinetti** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-aws-ovn pull-ci-openshift-installer-release-4.6-e2e-aws-fips

**Review by mandre — COMMENTED** [review]
Simple rebase, still lgtm
/lgtm

**Pull request closed without merging**
