### PR TITLE
add e2e harness binary build job to operator pr-checks

### PR DESCRIPTION
**Pull request by ritmun**
`make e2e-harness-build` builds e2e test binary. This target currently runs on operator build jenkins job. If this target fails, operator builds will be blocked. So it should be ensured that this is successfully building in pr checks.

What the job does: 
- Runs only if osde2e/*, or gomod has changed
- builds ginkgo binary for e2e tests
- doesn't run tests

This PR adds the pr-check job to following operators:
- AVO
- CIO
- CDO
- MNMO
- Managed upgrade operator
- MGO
- OCM agent operator
- OSD metrics exporter
- RBAC Permissions operator
- Route monitor operator
- Splunk forwarder operator

https://issues.redhat.com//browse/SDCICD-1205 

boilerplate prow-config has already been updated to include this on new operator setups https://github.com/openshift/boilerplate/pull/398

### CODE REVIEW

**Review by mjlshen — APPROVED** [review]
/lgtm

**Review by dem4gus — APPROVED** [review]

**Review by sam-nguyen7 — COMMENTED** [review]
/lgtm

**Review by deepsm007 — APPROVED** [review]

**Pull request merged**
