### PR TITLE
[WIP] base origin-release golang builders on OCP images

### PR DESCRIPTION
**Pull request by sosiouxme**
Have origin-release golang builders use OCP golang-builder images as the base image so that the toolchain is as close as possible between OKD and OCP.

OCP images are based on UBI7 so I had to add the CentOS repo back in order to continue installing some of the extra dependencies in OKD.
Also, since the base image supplies golang and libs it was no longer necessary to install them or meddle with $GOROOT.

### CODE REVIEW

**Comment by sosiouxme** [comment]
I ran builds in https://api.ci.openshift.org/console/project/art/browse/builds and they looked good, but I'm not sure how/what I need to test building with them.

**Comment by smarterclayton** [comment]
You should be able to open a PR to openshift/release that changes one of
the ci-operator configs (say, openshift/origin master) to point to this
release image instead of the current one.  That'll trigger a rehearse run
that verifies at least that images passes.

**Comment by sosiouxme** [comment]
@smarterclayton I created https://github.com/openshift/release/pull/4492 but I don't know where to see the rehearse run you mentioned. (Tests all passed quickly)
@stevekuznetsov am i doing it wrong? How can I test building an image with my test builder?
I have to imagine you guys thought a great deal about how to make changes like this safely...

**Comment by bbguimaraes** [comment]
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/4492/pull-ci-openshift-release-master-pj-rehearse/4907#0:build-log.txt%3A37

>  time="2019-07-23T22:13:03Z" level=info msg="Would rehearse too many jobs, will not proceed" pr=4492 rehearsal-jobs=33 rehearsal-threshold=15

You can remove tests from the `ci-operator` configuration files in that PR to get below the maximum.

**Comment by sosiouxme** [comment]
When [trying with origin 4.1 builds with golang-1.11 a few days ago](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/4492/pull-ci-openshift-release-master-pj-rehearse/4958), I got many successes, some errors.
```
time="2019-07-25T02:54:01Z" level=error msg="Job failed" job=rehearse-4492-pull-ci-openshift-origin-release-4.1-e2e-vsphere name=3c80abc4-ae7e-11e9-bf6e-0a58ac101a09 org=openshift pr=4492 repo=release state=failure type=presubmit
time="2019-07-25T02:56:01Z" level=error msg="Job failed" job=rehearse-4492-pull-ci-openshift-origin-release-4.1-launch-vsphere name=3c8e4cb4-ae7e-11e9-bf6e-0a58ac101a09 org=openshift pr=4492 repo=release state=failure type=presubmit
time="2019-07-25T03:15:03Z" level=error msg="Job failed" job=rehearse-4492-pull-ci-openshift-origin-release-4.1-e2e-aws-image-ecosystem name=3c77f6b1-ae7e-11e9-bf6e-0a58ac101a09 org=openshift pr=4492 repo=release state=failure type=presubmit
time="2019-07-25T03:33:02Z" level=error msg="Job failed" job=rehearse-4492-pull-ci-openshift-origin-release-4.1-e2e-aws-builds name=3c75b3de-ae7e-11e9-bf6e-0a58ac101a09 org=openshift pr=4492 repo=release state=failure type=presubmit
```
Not sure how to tell if those were flakes.

No matter what I did, editing the origin master to use my golang-1.12 resulted in exceeding the rehearsal threshold (even removing tests didn't seem to make a difference, perhaps I don't understand what drives rehearsals). I shifted instead to [testing openshift-apiserver and sdn](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/4492/pull-ci-openshift-release-master-pj-rehearse/5053) and saw one failure:
```
time="2019-07-26T07:29:19Z" level=error msg="Job failed" job=rehearse-4492-pull-ci-openshift-sdn-master-e2e-aws name=c65b8137-af6d-11e9-bb6c-0a58ac101dbd org=openshift pr=4492 repo=release state=failure type=presubmit
```
Again not sure where to look for whether that's a flake or something more sinister.

**Comment by sosiouxme** [comment]
closed in favor of https://github.com/openshift/release/pull/5529

**Pull request closed without merging**
