### PR TITLE
Add CCM e2e Azure testing job for WMCO

### PR DESCRIPTION
**Pull request by Fedosin**
This PR adds an e2e job:

* azure-e2e-ccm-install tests fresh installations with CCM support.

### CODE REVIEW

**Comment by Fedosin** [comment]
/hold

This PR also contains https://github.com/openshift/release/pull/23423 that should be merged first.

**Comment by Fedosin** [comment]
```txt
E1109 17:45:17.150215       1 actuator.go:78] Machine error: failed to reconcile machine "e2e-nqvdn": failed to create vm e2e-nqvdn: failure sending request for machine e2e-nqvdn: cannot create vm: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="ResourcePurchaseValidationFailed" Message="User failed validation to purchase resources. Error message: 'You have not accepted the legal terms on this subscription: 'd38f1e38-4bed-438e-b227-833f997adf6a' for this plan. Before the subscription can be used, you need to accept the legal terms of the image. To read and accept legal terms, use the Azure CLI commands described at https://go.microsoft.com/fwlink/?linkid=2110637 or the PowerShell commands available at https://go.microsoft.com/fwlink/?linkid=862451. Alternatively, deploying via the Azure portal provides a UI experience for reading and accepting the legal terms. Offer details: publisher='MicrosoftWindowsServer' offer = 'WindowsServer', sku = 'datacenter-core-20h2-with-containers-smalldisk', Correlation Id: '5f3337dc-ae58-4efd-8532-fdc01076ff1d'.'"
```

**Review by elmiko — COMMENTED** [review]
+1, this generally looks good to me but i am not so familiar with the wcmo infra

**Comment by sebsoto** [comment]
@Fedosin Is the azure test failing in the expected way? The node objects were fully created

**Comment by Fedosin** [comment]
@sebsoto yes, unfortunately it is expected. This is because we have to install and configure Cloud Node Manager on each node on Azure. I created a PR to implement this feature: https://github.com/openshift/windows-machine-config-operator/pull/808

**Pull request merged**
