### PR TITLE
USHIFT-998: Use single firewall rule for easier cleanup

### PR DESCRIPTION
**Pull request by pacevedom**

### CODE REVIEW

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-reboot pull-ci-openshift-microshift-main-e2e-greenboot pull-ci-openshift-microshift-main-e2e-router-smoke-test

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-loadbalancer-smoke-test

**Pull request merged**
