### PR TITLE
Add cluster relocation service repo config and initial tests

### PR DESCRIPTION
**Pull request by carbonin**

### CODE REVIEW

**Comment by carbonin** [comment]
/pj-rehearse pull-ci-openshift-cluster-relocation-service-main-build

**Comment by carbonin** [comment]
/pj-rehearse pull-ci-openshift-cluster-relocation-service-main-unit-test

**Comment by carbonin** [comment]
/pj-rehearse pull-ci-openshift-cluster-relocation-service-main-unit-test

**Comment by gamli75** [comment]
LGTM

**Pull request merged**
