### PR TITLE
move marketplace openshift-serial test to aws

### PR DESCRIPTION
**Pull request by awgreene**
The openshift marketplace e2e-gcp-serial test suite has been failing at roughly a rate of 98% because of a series of disruption tests that expect 100% availability on core components. Most of the test failures feature intermitent disruption on the order of seconds. This issue seems to be isolated to running the test on gcp.

The goal of this PR is to move the e2e-serial tests to aws, identifying why the test failure seems to be isolated to gcp clusters should be followed up on.

### CODE REVIEW

**Comment by awgreene** [comment]
/pj-rehersal pull-ci-operator-framework-operator-marketplace-master-e2e-aws-serial

**Comment by awgreene** [comment]
/pj-rehearse pull-ci-operator-framework-operator-marketplace-master-e2e-aws-serial

**Comment by anik120** [comment]
Probably worth mentioning that running this test suite in gcp is failing ~98% of the time

**Review by anik120 — APPROVED** [review]
/lgtm

**Pull request merged**
