### PR TITLE
Move vsphere-8-vpn to elastic

### PR DESCRIPTION
**Pull request by jcpowermac**

### CODE REVIEW

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-vsphere-8-ipi-ovn-etcd-encryption-f28 periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn-etcd-scaling periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-externallb-ovn periodic-ci-openshift-release-master-nightly-4.15-upgrade-from-stable-4.14-e2e-vsphere-upgrade periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn-csi

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-static-ovn periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn-etcd-scaling periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-externallb-ovn

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-static-ovn periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn-etcd-scaling periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-externallb-ovn

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-static-ovn periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn-etcd-scaling periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-externallb-ovn

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-static-ovn periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn-etcd-scaling periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-externallb-ovn

**Review by r4f4 — COMMENTED** [review]
/approve

**Comment by jcpowermac** [comment]
/hold

Since we are only using a subset of the ip address list, it broke external lb configuration of haproxy. Will need to modify `e2e-vsphere-externallb-ovn-ipi-conf-vsphere-lb-external` step to continue this PR.

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-externallb-ovn

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-externallb-ovn

**Comment by jcpowermac** [comment]
/uncc @r4f4 @jhou1 @patrickdillon @bandrade @vrutkovs @sdodson @akostadinov

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-externallb-ovn

**Comment by jcpowermac** [comment]
external lb is looking better, on to static

/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-static-ovn

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-static-ovn

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-static-ovn

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-static-ovn

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-static-ovn periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn-etcd-scaling periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-externallb-ovn

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-static-ovn periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn-etcd-scaling periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-externallb-ovn

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-static-ovn

**Comment by jcpowermac** [comment]
This PR is now ready to go

/assign @r4f4 @jhou1 @patrickdillon @bandrade @vrutkovs @sdodson @akostadinov

**Review by r4f4 — COMMENTED** [review]
/approve

**Comment by jcpowermac** [comment]
fyi @neisw

**Pull request merged**
