### PR TITLE
Add Azure CSI driver test on Azure Stack

### PR DESCRIPTION
**Pull request by jsafrane**
Based on https://github.com/openshift/release/pull/18796, adding pre-submit test for the CSI driver on ASH.
I will turn it into a periodic job in a separate PR.

### CODE REVIEW

**Comment by jsafrane** [comment]
@bertinatto I don't think the test is going to pass

**Comment by bertinatto** [comment]
```
{"component":"entrypoint","file":"prow/entrypoint/run.go:255","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process did not exit before 10m0s grace period","severity":"error","time":"2021-09-21T16:51:24Z"}
{"component":"entrypoint","error":"os: process already finished","file":"prow/entrypoint/run.go:257","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Could not kill process after grace period","severity":"error","time":"2021-09-21T16:51:24Z"}
{"component":"entrypoint","error":"process timed out","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-09-21T16:51:24Z"}
error: failed to execute wrapped command: exit status 127
```
I'm not sure if this is a flake or not, so I'm re-scheduling the job:

/retest

**Comment by jsafrane** [comment]
The test was killed after 2 hours. Increasing parallelism...

**Comment by jsafrane** [comment]
With 4 tests in parallel, the tests succeeded after 1h28m0s. That's feels like too much (regular Azure with 20 tests in parallel finishes in 17m). Trying 8 tests in parallel, expecting 45 minutes.

**Comment by jsafrane** [comment]
"8" failed. Going back to 4 and removing WIP.

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Pull request merged**
