### PR TITLE
MGMT-16056: Change ODF and CNV to use OCP 4.14 in assisted

### PR DESCRIPTION
**Pull request by adriengentil**
`OPENSHIFT_INSTALL_RELEASE_IMAGE=""` is required to ensure we deploy OCP from the default images instead of the nightly release exposed by prow.

### CODE REVIEW

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-cloud_hotfix_releases-e2e-metal-assisted-cnv

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted-cnv

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-master-edge-e2e-metal-assisted-cnv

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-agent-master-edge-e2e-metal-assisted-odf

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-agent-master-edge-e2e-metal-assisted-cnv

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-agent-master-edge-e2e-metal-assisted-cnv

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-agent-master-edge-e2e-metal-assisted-odf

**Pull request merged**
