### PR TITLE
Update Retrigger to be set in the main workflow as default

### PR DESCRIPTION
**Pull request by vi-patel**
* Remove the var to retrigger from individual scenarios
* Update retrigger var to be set in the main workflows as default

### CODE REVIEW

**Review by calebevans — APPROVED** [review]
/lgtm

**Comment by vi-patel** [comment]
/pj-rehearse periodic-ci-rh-messaging-qe-claire-lpt-amq-broker-ocp4.16-lp-interop-amq-broker-interop-aws

**Comment by vi-patel** [comment]
@andreasgerstmayr @frzifus @iblancasa @IshwarKanse @pavolloffay @rubenvp8510 , can one of you please approve this PR, thanks in advance.

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Review by frzifus — APPROVED** [review]

**Comment by vi-patel** [comment]
@alanfx , @aliok , @creydr @lberk , @matzew , @mgencur , @pierDipi , @rhuss , @skonto , @ReToCode can one of you approve this PR, made a small update, thanks.

**Comment by vi-patel** [comment]
@andreasgerstmayr @frzifus @iblancasa @IshwarKanse @pavolloffay @rubenvp8510 , can one of you please approve this PR, thanks I made a small update

**Review by frzifus — APPROVED** [review]

**Pull request merged**
