### PR TITLE
NP-603: ushift change default MTU to 1500

### PR DESCRIPTION
**Pull request by pacevedom**

### CODE REVIEW

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-openshift-conformance-sig-api-machinery

**Comment by zshi-redhat** [comment]
LGTM

**Comment by zshi-redhat** [comment]
@pacevedom The file `upi-gcp-rhel8-pre-commands.sh` is exclusively used by microshift, right?
Just in case, I don't see microshift name in that script.

**Comment by pacevedom** [comment]
> @pacevedom The file `upi-gcp-rhel8-pre-commands.sh` is exclusively used by microshift, right? Just in case, I don't see microshift name in that script.

Yes, only MicroShift uses this workflow. Actually this workflow was created for it.

**Pull request merged**
