### PR TITLE
Update and run Tempo e2e tests for RHOSDT 3.3

### PR DESCRIPTION
**Pull request by IshwarKanse**

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.14-stage-tempo-stage-tests periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.15-stage-tempo-stage-tests periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.14-arm-stage-tempo-stage-tests periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.17-stage-tempo-stage-tests periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.13-stage-tempo-stage-tests periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.17-stage-tempo-stage-tests-fips periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.12-stage-tempo-stage-tests periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.16-stage-tempo-stage-tests periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.16-stage-tempo-stage-tests-fips

**Review by frzifus — APPROVED** [review]

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.14-stage-tempo-stage-tests periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.15-stage-tempo-stage-tests periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.14-arm-stage-tempo-stage-tests periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.17-stage-tempo-stage-tests periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.13-stage-tempo-stage-tests periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.17-stage-tempo-stage-tests-fips periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.12-stage-tempo-stage-tests periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.16-stage-tempo-stage-tests periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.16-stage-tempo-stage-tests-fips

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.16-stage-tempo-stage-tests periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.12-stage-tempo-stage-tests periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.17-stage-tempo-stage-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.14-arm-stage-tempo-stage-tests periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.16-stage-tempo-stage-tests

**Review by vprashar2929 — APPROVED** [review]
/lgtm

**Pull request merged**
