### PR TITLE
Installer: promote altinfra image

### PR DESCRIPTION
**Pull request by patrickdillon**
Point to specific altinfra dockerfile.

### CODE REVIEW

**Comment by patrickdillon** [comment]
Depends on https://github.com/openshift/installer/pull/7711

**Comment by patrickdillon** [comment]
/pj-rehearse pull-ci-openshift-installer-master-altinfra-images

**Comment by patrickdillon** [comment]
/pj-rehearse pull-ci-openshift-installer-master-altinfra-e2e-aws-ovn

**Comment by patrickdillon** [comment]
[e2e rehearsal ](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/45590/rehearse-45590-pull-ci-openshift-installer-master-altinfra-e2e-aws-ovn/1724068149927612416)fails with `not implemented` panic as expected:

```
 panic: not implemented 
```
/pj-rehearse ack

**Comment by patrickdillon** [comment]
/pj-rehearse pull-ci-openshift-installer-master-altinfra-images

**Review by r4f4 — COMMENTED** [review]
/lgtm

**Pull request merged**
