### PR TITLE
OpenStack: Set apiVersion for install-config to v1

### PR DESCRIPTION
**Pull request by mandre**
Also remove the `CONFIG_API_VERSION` environment variable as it
shouldn't be needed to configure the apiVersion per job.

### CODE REVIEW

**Review by Fedosin — APPROVED** [review]
/lgtm
/approve
/hold

**Comment by mandre** [comment]
@Fedosin, I believe the `/hold` has no reason to be. Could you please check and remove it?

**Review by pierreprinetti — APPROVED** [review]

**Pull request merged**
