### PR TITLE
Migrate Knative Serving from openshift to openshift-knative org

### PR DESCRIPTION
**Pull request by mgencur**
* Migrate only version 1.3 and newer
* Remove older CI setups as those releases are unsupported now

### CODE REVIEW

**Comment by skonto** [comment]
@mgencur This needs upgrades at the S-O side at least. We fetch the manifests from the midstream repos. 
Are you planning to migrate eventing too? Also could we delay this for 1.27? Is this urgent?

**Comment by mgencur** [comment]
> @mgencur This needs upgrades at the S-O side at least. We fetch the manifests from the midstream repos.
Are you planning to migrate eventing too? Also could we delay this for 1.27? Is this urgent?

I would migrate Eventing as well, but not before we migrate Serving. We want this to allow multiarch builds of test images. When we speak about "after" 1.26 it's at least end of November :-/ Do you have any pointers for serverless-operator side? What needs to be changed... Thanks

**Comment by mgencur** [comment]
Note to self: Check if there was any change in the original openshift/knative-serving directory before unholding this.

**Comment by nak3** [comment]
LGTM. I am fine to merge if Stavros is ready for S-O side https://github.com/openshift/release/pull/33058#issuecomment-1276197037

**Review by jmguzik — APPROVED** [review]

**Comment by jmguzik** [comment]
agh, wrong command
/pj-rehearse ack

**Pull request merged**
