### PR TITLE
Migrate azure jobs away from api.ci

### PR DESCRIPTION
**Pull request by hongkailiu**
https://issues.redhat.com/browse/DPTP-1566

/cc @openshift/openshift-team-developer-productivity-test-platform

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Title of this is wrong - they are not migrating to app.ci (and they should not be)

**Comment by hongkailiu** [comment]
Yes. Green.
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/14577/rehearse-14577-pull-ci-azure-master-e2e-create-20190430/1346906180030566400

I will remove the rehearsal labels and migrate all of them as planned.

**Comment by hongkailiu** [comment]
/assign @mjudeikis

Please take a look.

**Pull request merged**
