### PR TITLE
WINC-1322: [winc] WMCO 4.18 branching day changes

### PR DESCRIPTION
**Pull request by saifshaikh48**
- Adjusts versioning to line up with OCP 4.18.
- Changes fast-forward setting to have community-4.18 track release-4.18.
- Changes upgrade test to upgrade from 4.17 to 4.18.

### CODE REVIEW

**Comment by saifshaikh48** [comment]
/pj-reheasrse pull-ci-openshift-windows-machine-config-operator-master-build pull-ci-openshift-windows-machine-config-operator-master-aws-e2e-operator pull-ci-openshift-windows-machine-config-operator-master-azure-e2e-upgrade

sanity checks

**Review by mansikulkarni96 — APPROVED** [review]

**Comment by saifshaikh48** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-build pull-ci-openshift-windows-machine-config-operator-master-aws-e2e-operator pull-ci-openshift-windows-machine-config-operator-master-azure-e2e-upgrade

sanity checks

**Comment by saifshaikh48** [comment]
/pj-rehearse ack

sanity check jobs give green light, operator image builds and upgrade job successfully replaces old wmco version with new

**Pull request merged**
