### PR TITLE
Preparing for WildFly Charts

### PR DESCRIPTION
**Pull request by ehsavoie**

### CODE REVIEW

**Comment by ehsavoie** [comment]
@fabiobrz may you take a look ?

**Comment by fabiobrz** [comment]
> /verify-owners

It'll take some time until the ticket is processed and you'll be part of the org.

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-openshift_testing-wildfly-wildfly-charts-e2e

**Comment by ehsavoie** [comment]
/pj-rehearse pull-ci-wildfly-wildfly-charts-main-wildfly-wildfly-charts-e2e

**Pull request merged**
