### PR TITLE
MGMT-12439: Fix equinix steps for assisted

### PR DESCRIPTION
**Pull request by adriengentil**
- Fix line continuation
- `fix_uid.sh` script is not available, it will be performed as part of
  the ansible playbook

### CODE REVIEW

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-day2-arm-workers

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-day2-arm-workers

**Review by osherdp — APPROVED** [review]

**Pull request merged**
