### PR TITLE
Enable 4.3 cluster for odo

### PR DESCRIPTION
**Pull request by amitkrout**
Enabling OpenShift 4.3 cluster for odo testing

### CODE REVIEW

**Comment by amitkrout** [comment]
ping @kadel @mohammedzee1000 

So finally we have 4.1, 4.2 and 4.3 OpenShift cluster. Should we go with this combination or you guys want to remove 4.1 from this combination.

**Comment by mohammedzee1000** [comment]
Do we want to disable tests for any version as well in at this point in time, like 4.1?

**Comment by kadel** [comment]
> ping @kadel @mohammedzee1000
> 
> So finally we have 4.1, 4.2 and 4.3 OpenShift cluster. Should we go with this combination or you guys want to remove 4.1 from this combination.

 we need to test on all supported versions.

**Comment by amitkrout** [comment]
> > ping @kadel @mohammedzee1000
> > So finally we have 4.1, 4.2 and 4.3 OpenShift cluster. Should we go with this combination or you guys want to remove 4.1 from this combination.
> 
> we need to test on all supported versions.

AFAIK we support n-2 formula. so 4.1, 4.2 and 4.3 will be the part our test cluster.

**Comment by mohammedzee1000** [comment]
ok then
/test pj-rehearse

**Comment by mohammedzee1000** [comment]
looking good
/lgtm

**Pull request merged**
