### PR TITLE
add base_image for health check ref.

### PR DESCRIPTION
**Pull request by ascerra**
The hypershift-extended-health-check ref has been failing for the sbo rosa-hypershift scenario due to the missing base_image "upi-installer"

Failure we have been seeing is here: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.14-acceptance-lp-rosa-hypershift/1729078340456812544

This change includes the base image so that the hypershift-extended-health-check ref can run.

The scenario to test on 4.13 already had the base_image and when we moved to 4.14 we used a pre-existing file which is why we missed this.

### CODE REVIEW

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.14-acceptance-lp-rosa-hypershift

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
