### PR TITLE
Bug 2062152: Azure Stack Hub: skip parallel CSI tests

### PR DESCRIPTION
**Pull request by bertinatto**
CC @openshift/storage

### CODE REVIEW

**Comment by bertinatto** [comment]
/assign @dgoodwin 
for approval

**Comment by bertinatto** [comment]
/assign @stbenjam 
for approval as well

**Comment by dgoodwin** [comment]
Is this a permanent thing, Azure straight up doesn't support this and won't any time soon?

If not, how will you track bringing the test back in?

**Comment by bertinatto** [comment]
> Is this a permanent thing, Azure straight up doesn't support this and won't any time soon?
> 
> If not, how will you track bringing the test back in?

This is most likely permanent. 

When it comes to volume operations, Azure is significantly slower (and more unpredictable) than GCE and AWS. This seems to be even worse on Azure Stack Hub.

We already bumped the timeouts and basically there's nothing left we can do about it, so we opted to disable the offending tests on Azure Stack Hub only.

**Comment by dgoodwin** [comment]
Sounds good, thanks

/lgtm

**Pull request merged**
