### PR TITLE
OPCT-191: mirror opct image to be used on steps

### PR DESCRIPTION
**Pull request by mtulio**
[`opct`](https://github.com/redhat-openshift-ecosystem/provider-certification-tool) is the tool used to validate external cloud providers using VCSP Program.

We need to mirror this binary to avoid downloading from Github every step (run, retrieve, results, and more to come) defined on https://github.com/openshift/release/pull/36894 .

https://issues.redhat.com/browse/OPCT-178
https://issues.redhat.com/browse/OPCT-191

### CODE REVIEW

**Comment by mtulio** [comment]
Ptal @bbguimaraes @droslean?
/assign @bbguimaraes @droslean

**Review by droslean — APPROVED** [review]

**Comment by mtulio** [comment]
Ptal @bbguimaraes @droslean? The lgtm flag was gone after rebase

**Comment by mtulio** [comment]
Ptal @bbguimaraes @droslean? lgtm tag been removed after rebase.

**Pull request merged**
