### PR TITLE
kubevirt: ssp: Increase timeout for tests

### PR DESCRIPTION
**Pull request by akrejcir**
Increased timeout from the default 1 hour to 2 hours.

### CODE REVIEW

**Review by codingben — APPROVED** [review]
/lgtm

**Comment by ksimon1** [comment]
Would you please improve the commit message, why is this change necessary?

**Comment by ksimon1** [comment]
Btw. I think we should rather focus on making the tests faster, because I can see in the logs, that some of the prometheus tests takes about 6 minutes.

**Comment by akrejcir** [comment]
> Btw. I think we should rather focus on making the tests faster, because I can see in the logs, that some of the prometheus tests takes about 6 minutes per test.

I agree. Some of it will be solved by: https://bugzilla.redhat.com/show_bug.cgi?id=2151248
This is mainly needed to unblock PRs.

**Comment by 0xFelix** [comment]
@akrejcir Can you please create an issue in the ssp-operator repo to track the improvement/speed up of slow tests?

**Comment by akrejcir** [comment]
Done: https://github.com/kubevirt/ssp-operator/issues/500

**Comment by akrejcir** [comment]
/pj-rehearse pull-ci-kubevirt-ssp-operator-master-e2e-upgrade-functests

**Pull request merged**
