### PR TITLE
[WIP]E2e test for rhtap installer

### PR DESCRIPTION
**Pull request by xinredhat**

### CODE REVIEW

**Comment by xinredhat** [comment]
/pj-rehearse pull-ci-redhat-appstudio-rhtap-installer-main-rhtap-installer-e2e

**Comment by xinredhat** [comment]
/pj-rehearse pull-ci-redhat-appstudio-rhtap-installer-main-rhtap-installer-e2e

**Comment by xinredhat** [comment]
/pj-rehearse pull-ci-redhat-appstudio-rhtap-installer-main-rhtap-installer-e2e

**Comment by xinredhat** [comment]
/pj-rehearse pull-ci-redhat-appstudio-rhtap-installer-main-rhtap-installer-e2e

**Comment by xinredhat** [comment]
/pj-rehearse pull-ci-redhat-appstudio-rhtap-installer-main-rhtap-installer-e2e

**Comment by xinredhat** [comment]
/pj-rehearse pull-ci-redhat-appstudio-rhtap-installer-main-rhtap-installer-e2e

**Comment by xinredhat** [comment]
/pj-rehearse pull-ci-redhat-appstudio-rhtap-installer-main-rhtap-installer-e2e

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-rhtap-installer-main-rhtap-installer-e2e

**Comment by xinredhat** [comment]
/pj-rehearse pull-ci-redhat-appstudio-rhtap-installer-main-rhtap-installer-e2e

**Comment by xinredhat** [comment]
/pj-rehearse pull-ci-redhat-appstudio-rhtap-installer-main-rhtap-installer-e2e

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-rhtap-installer-main-rhtap-installer-e2e

**Comment by xinredhat** [comment]
/pj-rehearse pull-ci-redhat-appstudio-rhtap-installer-main-rhtap-installer-e2e

**Comment by xinredhat** [comment]
/pj-rehearse pull-ci-redhat-appstudio-rhtap-installer-main-rhtap-installer-e2e

**Comment by xinredhat** [comment]
/pj-rehearse pull-ci-redhat-appstudio-rhtap-installer-main-rhtap-installer-e2e

**Comment by xinredhat** [comment]
/pj-rehearse pull-ci-redhat-appstudio-rhtap-installer-main-rhtap-installer-e2e

**Comment by xinredhat** [comment]
/pj-rehearse pull-ci-redhat-appstudio-rhtap-installer-main-rhtap-installer-e2e

**Comment by xinredhat** [comment]
/pj-rehearse pull-ci-redhat-appstudio-rhtap-installer-main-rhtap-installer-e2e

**Pull request closed without merging**
