### PR TITLE
OCPQE-20701  OCPCLOUD-2622 capi gcp cases to run on rebase

### PR DESCRIPTION
**Pull request by miyadav**
/pj-rehearse pull-ci-openshift-cluster-api-provider-gcp-master-regression-clusterinfra-cucushift-rehearse-gcp-ipi-techprev

### CODE REVIEW

**Comment by JoelSpeed** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-gcp-master-regression-clusterinfra-cucushift-rehearse-gcp-ipi-techprev

**Comment by miyadav** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-gcp-master-regression-clusterinfra-cucushift-rehearse-gcp-ipi-techprev

**Comment by miyadav** [comment]
@JoelSpeed added reporting step , now working fine.

**Comment by damdo** [comment]
@JoelSpeed CAPG machines you mean?
The last CAPG E2E ran this friday on a presumbit to master, and was successful: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-api-provider-gcp/224/pull-ci-openshift-cluster-api-provider-gcp-master-e2e-gcp-capi-techpreview/1786384410791120896

Which one do you mean?

**Comment by JoelSpeed** [comment]
See the [rehearsal here](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/51609/rehearse-51609-pull-ci-openshift-cluster-api-provider-gcp-master-regression-clusterinfra-cucushift-rehearse-gcp-ipi-techprev/1787313049917460480), this is from QE test suites so it's possible that something changed maybe and we need to update the QE cases? Or it was a flake?

**Comment by damdo** [comment]
Hm, not really familiar with this QE suite.
But let's rerun the job a second time, not sure if it is a flake or not, let's rerun it and see if it fixes it first:

/pj-rehearse pull-ci-openshift-cluster-api-provider-gcp-master-regression-clusterinfra-cucushift-rehearse-gcp-ipi-techprev

**Comment by JoelSpeed** [comment]
Seems it's persistent, so perhaps something has regressed?

**Comment by miyadav** [comment]
Let me check it as well , will update.

**Comment by miyadav** [comment]
I ran on latest 4.16 looks [good](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/ginkgo-test/246241/console) , will re-run it here once more to confirm if it was flake only .

/pj-rehearse pull-ci-openshift-cluster-api-provider-gcp-master-regression-clusterinfra-cucushift-rehearse-gcp-ipi-techprev

**Comment by miyadav** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-gcp-master-regression-clusterinfra-cucushift-rehearse-gcp-ipi-techprev

**Comment by miyadav** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-gcp-master-regression-clusterinfra-cucushift-rehearse-gcp-ipi-techprev

**Comment by miyadav** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-gcp-master-regression-clusterinfra-cucushift-rehearse-gcp-ipi-techprev

**Comment by miyadav** [comment]
@JoelSpeed  this is fixed by using a cluster-profile specific to qe.

**Pull request merged**
