### PR TITLE
Update image-customization-controller base image for OCP 4.16

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Comment by elfosardo** [comment]
/retest
issues with CI

**Comment by elfosardo** [comment]
4.17 are expected to fail

**Comment by derekhiggins** [comment]
/lgtm

> / pj-rehearse max

 / pj-rehearse max can run upto 25 rehearse jobs, which is half of our capacity tied up for 3+ hours, /pj-rehearse might have been enough (or in this case selectively picking one job from each release)

**Comment by elfosardo** [comment]
this is needed for https://github.com/openshift/image-customization-controller/pull/112

**Pull request merged**
