### PR TITLE
Make the cloneref tool more idempotent and generic

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/cc @csrwng PTAL

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@csrwng rebased

**Comment by csrwng** [comment]
@stevekuznetsov my one comment is to rename the gopath var to something like prefixdir, given that we're not only building go. Otherwise lgtm

**Comment by stevekuznetsov** [comment]
@csrwng removed `$GOPATH` support entirely WDYT?

**Comment by csrwng** [comment]
@stevekuznetsov but you are still applying go semantics when you assume that you want to extract to src-root/src/github.com/owner/repo. Why not just let the caller tell you where they want the code?

**Comment by stevekuznetsov** [comment]
Without that structure we don't really have a good way for users to know where repositories will live relative to each other. Maybe we need some type of discovery mechanism? A well-known name for a symlink to the cloned repo seems reasonable, but if we need multiple repos cloned then we don't have a good way to message the locations.

**Comment by stevekuznetsov** [comment]
Fixed a permissions issue on `MkdirAll`.

**Pull request merged**
