### PR TITLE
Adding 4.10 and do nightly periodics there, as well as image promotion

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

as per title

This change was generated using this PR: https://github.com/openshift/knative-eventing/pull/1705

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

for optional jobs,
/hold

**Comment by matzew** [comment]
ok... this needs rebase ... :-(

**Pull request merged**
