### PR TITLE
Add multi-manager-operator (MOM) repository

### PR DESCRIPTION
**Pull request by bertinatto**

### CODE REVIEW

**Comment by bertinatto** [comment]
/pj-rehearse pull-ci-openshift-multi-operator-manager-master-unit
/pj-rehearse pull-ci-openshift-multi-operator-manager-master-verify

**Comment by bertinatto** [comment]
/pj-rehearse pull-ci-openshift-multi-operator-manager-master-verify

**Comment by p0lyn0mial** [comment]
LGTM

**Pull request merged**
