### PR TITLE
Jaeger - expand rosa-hypershift testing to OCP 4.12

### PR DESCRIPTION
**Pull request by ascerra**
We are extending our testing of the Jaeger operator to test on version 4.12 of rosa-hypershift.

### CODE REVIEW

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.12-lp-rosa-hypershift-jaeger-product-rosa-hypershift-412

**Comment by ascerra** [comment]
Could I please have one of the following review and approve this PR?
@pavolloffay
@andreasgerstmayr 
@iblancasa 
@rubenvp8510 
@frzifus 
@IshwarKanse

**Review by calebevans — APPROVED** [review]
/lgtm

**Review by frzifus — APPROVED** [review]

**Pull request merged**
