### PR TITLE
MCO: remove configuration for `fcos` branch

### PR DESCRIPTION
**Pull request by vrutkovs**
`fcos` branch is no longer used to build MCO for OKD

### CODE REVIEW

**Comment by jkyros** [comment]
This PR looks like it does what it says it does, but I don't know the history here and can't assess whether or not it's a good idea.  It looks like @vrutkovs  originally put the fcos branch stuff in here, so it makes sense he would know whether it was a good idea to take it out, but I'll defer to someone on the team with historical knowledge :)

**Comment by vrutkovs** [comment]
Right, in OKD 4.5 -> 4.7 we used `fcos` branch to host OKD-specific changes for MCO. In 4.10 all these changes were merged in `release-4.10` and we carry OKD 4.9 changes in a separate fork for now.

So this branch and CI configuration for it is no longer required.

**Review by jkyros — APPROVED** [review]
Thanks, I appreciate the context/background. And the cleanup. 
/lgtm

**Review by yuqi-zhang — APPROVED** [review]
lgtm, thanks for the cleanup!

**Comment by jkyros** [comment]
Nobody is going to want to do cleanup anymore if this is what happens :smile: 
/remove-lifecycle rotten

**Pull request closed without merging**
