### PR TITLE
Use counter for build-cop board

### PR DESCRIPTION
**Pull request by hongkailiu**

### CODE REVIEW

**Comment by hongkailiu** [comment]
/hold
I cannot see any data yet on the staging.
Maybe not 1h yet?
Let us wait.

**Comment by hongkailiu** [comment]
Feel better now on the graphs.
https://grafana-prow-monitoring-stage.svc.ci.openshift.org/d/6829209d59479d48073d09725ce807fa/build-cop-dashboard?orgId=1

/assign @stevekuznetsov

**Comment by stevekuznetsov** [comment]
Amazing!

/lgtm
/retest

**Pull request merged**
