### PR TITLE
stackrox: fix master branch ocp 4.12 testing

### PR DESCRIPTION
**Pull request by BradLugo**
/cc @gavin-stackrox

### CODE REVIEW

**Comment by BradLugo** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-4-12-operator-e2e-tests pull-ci-stackrox-stackrox-master-ocp-4-12-qa-e2e-tests pull-ci-stackrox-stackrox-master-ocp-4-12-ui-e2e-tests pull-ci-stackrox-stackrox-master-ocp-next-operator-e2e-tests pull-ci-stackrox-stackrox-master-ocp-next-qa-e2e-tests pull-ci-stackrox-stackrox-master-ocp-next-ui-e2e-tests

**Review by gavin-stackrox — APPROVED** [review]
/lgtm

**Pull request merged**
