### PR TITLE
enable Go units tests in openshift/images (release 4.15)

### PR DESCRIPTION
**Pull request by frobware**
Ran make update

Requires: https://github.com/openshift/images/pull/168.

### CODE REVIEW

**Comment by frobware** [comment]
`ci/rehearse/openshift/images/release-4.15/unit` [fails](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/51358/rehearse-51358-pull-ci-openshift-images-release-4.15-unit/1783484860623491072) but this is because this PR depends on https://github.com/openshift/images/pull/168.

**Comment by frobware** [comment]
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/51358/rehearse-51358-pull-ci-openshift-images-release-4.15-unit/1786073850144886784/artifacts/test/build-log.txt

/pj-rehearse ack

**Comment by frobware** [comment]
@bparees as you've just ack'd https://github.com/openshift/images/pull/168 please could you review/approve this PR.

**Comment by bparees** [comment]
> @bparees as you've just ack'd https://github.com/openshift/images/pull/168 please could you review/approve this PR.

i gave that PR a CPA label because it doesn't impact QE, but i'm no longer an approver on this repo, you need someone from:
https://github.com/openshift/release/blob/master/ci-operator/config/openshift/images/OWNERS
https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/images/OWNERS

(i'm no longer in the openshift org and slowly divesting my permissions)

**Comment by frobware** [comment]
> (i'm no longer in the openshift org and slowly divesting my permissions)

Noted.

**Comment by Miciah** [comment]
I'm unlinking the bug report.  It is still linked to the PR that fixed the unit tests in the openshift/images repository, but that PR and the bug report target openshift-4.15, which is preventing this PR from merging.  

/retitle enable Go units tests in openshift/images (release 4.15)

**Pull request merged**
