### PR TITLE
Update kubevirt-ui e2e node upgrade

### PR DESCRIPTION
**Pull request by upalatucci**
Make this change to upgrade node version

### CODE REVIEW

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-kubevirt-ui-kubevirt-plugin-main-kubevirt-e2e-aws

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-kubevirt-ui-kubevirt-plugin-main-kubevirt-e2e-aws

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-kubevirt-ui-kubevirt-plugin-main-kubevirt-e2e-aws
/pj-rehearse pull-ci-kubevirt-ui-kubevirt-plugin-main-images

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-kubevirt-ui-kubevirt-plugin-main-kubevirt-e2e-aws
/pj-rehearse pull-ci-kubevirt-ui-kubevirt-plugin-main-images

**Comment by upalatucci** [comment]
/pj-rehearse pull-ci-kubevirt-ui-kubevirt-plugin-main-kubevirt-e2e-aws

**Review by metalice — APPROVED** [review]

**Pull request merged**
