### PR TITLE
Revise name RHTAP to Konflux for devfile registry nightly testing

### PR DESCRIPTION
**Pull request by michael-valdron**
# Description

Changes the client name RHTAP to Konflux in nightly test setups.

Needed for devfile/registry#310 changes.

### CODE REVIEW

**Comment by thepetk** [comment]
@michael-valdron I think in order to make the failing test pass we need to merge the upgrade to 4.13 we were discussing with @flacatus [(PR here)](https://github.com/openshift/release/pull/49019)

**Comment by michael-valdron** [comment]
https://github.com/openshift/release/pull/49019 has been merged, unblocking this PR.

**Comment by michael-valdron** [comment]
/hold

devfile/registry#310 should be merged first.

**Review by thepetk — APPROVED** [review]
/lgtm

**Comment by michael-valdron** [comment]
Previous rehearsal before rebase passed: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/49400/rehearse-49400-periodic-ci-devfile-registry-main-v4.13-konflux-nightly-devfile-compatibility/1768307253212876800

**Review by maysunfaisal — APPROVED** [review]

**Pull request merged**
