### PR TITLE
[HyperShift KubeVirt] Bump to ODF 4.15

### PR DESCRIPTION
**Pull request by orenc1**

### CODE REVIEW

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn pull-ci-openshift-hypershift-main-e2e-kubevirt-azure-ovn periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-kubevirt-metal periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-kubevirt-metal-ovn-mce

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn pull-ci-openshift-hypershift-main-e2e-kubevirt-azure-ovn periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-kubevirt-metal periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-kubevirt-metal-ovn-mce

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn pull-ci-openshift-hypershift-main-e2e-kubevirt-azure-ovn periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-kubevirt-metal periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-kubevirt-metal-ovn-mce

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn pull-ci-openshift-hypershift-main-e2e-kubevirt-azure-ovn periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-kubevirt-metal periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-kubevirt-metal-ovn-mce

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn pull-ci-openshift-hypershift-main-e2e-kubevirt-azure-ovn periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-kubevirt-metal periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-kubevirt-metal-ovn-mce

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-kubevirt-csi-driver-master-e2e-kubevirt-aws-csi pull-ci-openshift-kubevirt-csi-driver-release-4.16-e2e-kubevirt-aws-csi pull-ci-openshift-kubevirt-csi-driver-release-4.15-e2e-kubevirt-aws-csi pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn-kubevirt

**Review by davidvossel — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
