### PR TITLE
assisted-service: Enable daily job deploying dual-stack clusters

### PR DESCRIPTION
**Pull request by mkowalski**
This PR enables the following jobs for master and ocm-2.4 branches in
the assisted-service scope

* e2e-metal-assisted-operator-ztp-dualstack-multinode-spoke-periodic
* e2e-metal-assisted-operator-ztp-dualstack-periodic

Contributes-to: [MGMT-6763](https://issues.redhat.com/browse/MGMT-6763)

### CODE REVIEW

**Comment by mkowalski** [comment]
/override ci/rehearse/periodic-ci-openshift-assisted-service-master-e2e-metal-assisted-operator-ztp-dualstack-multinode-spoke-periodic

This job is not supposed to pass before https://github.com/openshift/assisted-service/pull/2635 and https://github.com/openshift/assisted-installer/pull/359 are merged.

**Comment by YuviGold** [comment]
Please add a matching `reporter_config` to those jobs so we will be informed on Slack in case of a failure. Check how the other periodics on this job configuration are defined.

**Comment by mkowalski** [comment]
> Please add a matching `reporter_config` to those jobs so we will be informed on Slack in case of a failure. Check how the other periodics on this job configuration are defined.

Ok, added as part of https://github.com/openshift/release/pull/22315

**Pull request merged**
