### PR TITLE
OCPBUGS-10480: Skip failing storage snapshot test on master for e2e-openstack-csi-cinder

### PR DESCRIPTION
**Pull request by mandre**
We can remove the skips for 4.14 and master once origin is rebased on
kube 1.27.

### CODE REVIEW

**Comment by mandre** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-openstack-master-e2e-openstack-csi-cinder

**Comment by mandre** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-openstack-master-e2e-openstack-csi-cinder

**Comment by mandre** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-openstack-master-e2e-openstack-csi-cinder

**Comment by mdbooth** [comment]
@mandre Is there an issue open for this skip? Could we explicitly reference the issue as a comment next to the skip?

**Comment by mandre** [comment]
Meh, `make ci-operator-config` strips the comments I added. We will have to do with the commit message.

**Comment by MaysaMacedo** [comment]
/lgtm
thanks Martin

**Pull request merged**
