### PR TITLE
Removing redundant images for NFD and SRO.

### PR DESCRIPTION
**Pull request by ybettan**
Signed-off-by: Yoni Bettan <ybettan@redhat.com>

### CODE REVIEW

**Review by ArangoGutierrez — CHANGES_REQUESTED** [review]
Please remove NFD from the scope of this PR, thanks

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Comment by ybettan** [comment]
> Please remove NFD from the scope of this PR, thanks

Is there anyone using it? I have create this image myself yesterday.

**Review by droslean — APPROVED** [review]

**Comment by ybettan** [comment]
Needs @dagrayvid 's approval after https://github.com/openshift/release/pull/25672 is merged.

**Comment by ybettan** [comment]
@dagrayvid now that https://github.com/openshift/release/pull/25672 is merged, can you please approve?

**Pull request merged**
