### PR TITLE
Add prometheus metrics in proxy

### PR DESCRIPTION
**Pull request by 0xmichalis**
@stevekuznetsov @smarterclayton @csrwng wondering what's the best approach wrt vendoring stuff inside `release`. Today, it seems that we are rooting for a [vendor](https://github.com/openshift/release/tree/master/tools/release-ci) directory per project that can lead to duplicate deps in the repo. If we use a root vendor directory, we will end up with the `test-infra` mess but maybe that's the best approach. Or maybe move the code in separate repositories and store only config in `release`? Even better, have our own `openshift-ci` or something org? Thoughts?

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
How often do you expect to change the proxy code... and the Prow deployments in one PR? Or the proxy, and Jenkins in one PR? I feel like we have a number of disjoint things (and many in here that really do not belong in the spirit of `release` in the first place) and I wouldn't mind an org and separate repos, but that may be too much context switching? Seems like upstream, whether it's `contrib` or `test-infra`, like one monorepo

**Comment by kargakis** [comment]
> Seems like upstream, whether it's contrib or test-infra, like one monorepo

These are two different examples. Actually, upstream are moving away from `contrib` because it was a bad call and they have figured out that monorepos don't work when people coming from different parties put different things in the same repository.

https://github.com/kubernetes/contrib
> Do not add new projects to this repository. We eventually want to move all code in this repository to more appropriate repositories (see #762). Create a new repository in kubernetes-incubator instead (process).

Note that the monorepo approach is a standard thing for Googlers. Brian has mentioned this a gazillion times.

Regarding `test-infra`, until some time ago, it had been only Googlers who worked in it, so it's natural that they are comfortable with the monorepo approach. Eventually, more and more outside parties start contributing and then `test-infra` ends up like `contrib` is a possibility. Maybe not. I would certainly like to see `prow` moving into its own repository, because more and more tools are starting to use its libraries and at some point we are going to end up needing to propagate every change that happens in the prow libs to its dependants in the same PR. Which is a bad thing. Imagine if @deads2k had to change every tool that depends on `api-machinery` on every `api-machinery` change that he made **at the same time**.

Monorepos work when the group of people working on it is scoped so it could possibly work for us. We just need to make a call and go with it.

@smarterclayton thoughts?

**Comment by kargakis** [comment]
> Monorepos work when the group of people working on it is scoped so it could possibly work for us. We just need to make a call and go with it.

Tbh, I prefer separate repos but if we want everything inside `release` then I am fine with that too.

**Comment by stevekuznetsov** [comment]
Different org means permissions and teams and stuff will be harder. I can just make us new repos in openshift org unless there is a NACK

**Comment by kargakis** [comment]
I will probably move the code for the proxy in openshift/test-infra so I can also tackle https://github.com/openshift/release/issues/189.

**Pull request closed without merging**
