### PR TITLE
Adding zone outage run

### PR DESCRIPTION
**Pull request by paigerube14**
Want to add full zone outage to ci runs

### CODE REVIEW

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-zone-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-zone-tests

**Comment by paigerube14** [comment]
need update from https://github.com/redhat-chaos/prow-scripts/pull/25

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-zone-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-zone-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-zone-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-zone-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-zone-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-zone-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-zone-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-zone-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-zone-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-zone-tests

**Comment by paigerube14** [comment]
We do not have the aws cli installed in our images. Adding as part of the prow image here: https://github.com/redhat-chaos/prow-scripts/pull/43

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-zone-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-zone-tests

**Comment by paigerube14** [comment]
@chaitanyaenr @shahsahil264 PTAL:

passing job here: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/52576/rehearse-52576-periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-zone-tests/1813286269392785408/artifacts/krkn-hub-zone-tests/redhat-chaos-zone-outage/build-log.txt

**Review by shahsahil264 — APPROVED** [review]
LGTM

**Pull request merged**
