### PR TITLE
openshift-loki: Bump builder to go1.22

### PR DESCRIPTION
**Pull request by periklis**
Refs: [LOG-6169](https://issues.redhat.com//browse/LOG-6169)

/cc @xperimental @JoaoBraveCoding

### CODE REVIEW

**Comment by periklis** [comment]
/pj-rehearse pull-ci-openshift-loki-release-6.0-test-operator

**Comment by periklis** [comment]
/pj-rehearse pull-ci-openshift-loki-release-6.0-test-operator

**Comment by periklis** [comment]
/pj-rehearse pull-ci-openshift-loki-release-6.0-test-operator

**Review by JoaoBraveCoding — APPROVED** [review]
/lgtm

**Comment by periklis** [comment]
/pj-rehearse pull-ci-openshift-loki-release-6.0-test-operator

**Pull request merged**
