### PR TITLE
adding support for ocp 4.18 for ocs

### PR DESCRIPTION
**Pull request by vi-patel**
adding support for ocp 4.18 for ocs

### CODE REVIEW

**Comment by vi-patel** [comment]
/pj-rehearse periodic-ci-red-hat-storage-ocs-ci-master-odf-ocp4.18-lp-interop-odf-interop-aws-fips

**Comment by vi-patel** [comment]
ODF operator unavailable in 4.18, ODF 4.17 GA 10/30/24

**Comment by dfrazzette** [comment]
Non-FIPS ([1840867908167667712](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/57326/rehearse-57326-periodic-ci-red-hat-storage-ocs-ci-master-odf-ocp4.18-lp-interop-odf-interop-aws/1840867908167667712)) and FIPS ([1840869278014771200](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/57326/rehearse-57326-periodic-ci-red-hat-storage-ocs-ci-master-odf-ocp4.18-lp-interop-odf-interop-aws-fips/1840869278014771200)) rehearsal runs failed to install operator. Automation succeeded, so merging PR to include in OCP 4.18 test suite. Will disable weekly run until operator and changes are available.

**Pull request merged**
