### PR TITLE
OCPCLOUD-2024: Enable strict policy tag for rebasebot

### PR DESCRIPTION
**Pull request by odvarkadaniel**
This PR adds the strict policy tag feature to Nutanix, IBM and Alibaba.

### CODE REVIEW

**Comment by odvarkadaniel** [comment]
/pj-rehearse periodic-ci-openshift-eng-rebasebot-main-cloud-provider-powervs periodic-ci-openshift-eng-rebasebot-main-cloud-provider-nutanix periodic-ci-openshift-eng-rebasebot-main-cloud-provider-alibaba-cloud

**Review by damdo — COMMENTED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
Are the repos suitably set up for this? Do they all have the correct commit prefixes on the commits that need to be carried? Git history checks in place?

**Comment by odvarkadaniel** [comment]
> Are the repos suitably set up for this? Do they all have the correct commit prefixes on the commits that need to be carried? Git history checks in place?

Yes, checked that. Two of them (Nutanix, IBM) have the right prefixes on the commits and Alibaba has tag `rebase/manual` on the PR, so that will need to be done manually anyway.

**Comment by JoelSpeed** [comment]
Please leave a comment and a hold on the current Alibaba rebase asking whoevers owning that to make sure the commit prefixes are resolved before merge

**Pull request merged**
