### PR TITLE
switching "e2e" test in openshift-azure to "[Fake][EveryPR]" tags

### PR DESCRIPTION
**Pull request by Makdaam**

### CODE REVIEW

**Comment by Makdaam** [comment]
Added 60min Timeout on e2e test

**Comment by mjudeikis** [comment]
Is this intended to be only for test? If this is really needed can we add it to `timeout 60m to e2e-create.sh` in ou repo? And keep this repository to a minimum?

**Comment by Makdaam** [comment]
rebased, PR is ready to merge, all tests which run previously have the EveryPR tag
/hold cancel

**Pull request merged**
