### PR TITLE
Cluster Operator tools image config for ci-operator

### PR DESCRIPTION
**Pull request by csrwng**
Builds a tools image for use in cluster operator CI

### CODE REVIEW

**Comment by csrwng** [comment]
@stevekuznetsov ptal
This would allow me to reference my own root image for cloning/testing etc.

**Comment by stevekuznetsov** [comment]
You need to update the configmap updater plugin for this

**Comment by csrwng** [comment]
Done

**Comment by stevekuznetsov** [comment]
Needs rebase

**Comment by csrwng** [comment]
done. Removed the plugin config change since it got merged with the other cluster operator PR

**Pull request merged**
