### PR TITLE
ccpmso/periodics: fix cluster profile for openstack

### PR DESCRIPTION
**Pull request by EmilienM**
This was due to a typo when I added the job.

### CODE REVIEW

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.14-periodics-e2e-openstack
/cc JoelSpeed damdo

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.14-periodics-e2e-openstack

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.14-periodics-e2e-openstack

**Comment by EmilienM** [comment]
ha it finally works. I'll let the job finish but it's now looking good :-)

**Review by mandre — COMMENTED** [review]
/lgtm

**Pull request merged**
