### PR TITLE
Onboard tcib repo

### PR DESCRIPTION
**Pull request by son-vyas**

### CODE REVIEW

**Comment by son-vyas** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-tcib-main-images

**Comment by viroel** [comment]
/pj-rehearse ack
pre-commit job is passing: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/39690/rehearse-39690-pull-ci-openstack-k8s-operators-tcib-main-precommit-check/1661718376747110400/artifacts/test/build-log.txt

**Review by viroel — APPROVED** [review]

**Pull request merged**
