### PR TITLE
Move BASTION_FLAVOR to OpenStack resource names

### PR DESCRIPTION
**Pull request by EmilienM**
Move BASTION_FLAVOR to openstack resource names, so it'll be easier to move the BYON jobs around our cloud platforms.

### CODE REVIEW

**Comment by EmilienM** [comment]
/assign @stbenjam
please review when you have time. Thanks!

**Comment by stbenjam** [comment]
/approve
/lgtm
/hold

I assume the e2e-openstack-az failures aren't related? They don't look that way to me -- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/21095/rehearse-21095-periodic-ci-openshift-release-master-nightly-4.9-e2e-openstack-az/1425836545876692992

Feel free to remove the hold when you're ready to merge

**Comment by EmilienM** [comment]
> /approve
> /lgtm
> /hold
> 
> I assume the e2e-openstack-az failures aren't related? They don't look that way to me -- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/21095/rehearse-21095-periodic-ci-openshift-release-master-nightly-4.9-e2e-openstack-az/1425836545876692992
> 
> Feel free to remove the hold when you're ready to merge

they are not related, cluster deployed fine:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/21095/rehearse-21095-periodic-ci-openshift-release-master-nightly-4.9-e2e-openstack-az/1425836545876692992/artifacts/e2e-openstack-az/ipi-install-install/build-log.txt

The issue was on e2e tests, where some tests seem to be flacky:
```
Failing tests:

[sig-cli] Kubectl client Simple pod should return command exit codes [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should deny ingress access to updated pod [Feature:NetworkPolicy] [Skipped:Network/OpenShiftSDN/Multitenant] [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should enforce policy based on Ports [Feature:NetworkPolicy] [Skipped:Network/OpenShiftSDN/Multitenant] [Suite:openshift/conformance/parallel] [Suite:k8s]

Writing JUnit report to /logs/artifacts/junit/junit_e2e_20210812-165146.xml

error: 3 fail, 931 pass, 21 skip (1h5m57s)
````
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/21095/rehearse-21095-periodic-ci-openshift-release-master-nightly-4.9-e2e-openstack-az/1425836545876692992/artifacts/e2e-openstack-az/openshift-e2e-test/build-log.txt

Thanks for your review!

**Pull request merged**
