### PR TITLE
vsphere upi and ipi: new packet environment

### PR DESCRIPTION
**Pull request by jcpowermac**

### CODE REVIEW

**Comment by jcpowermac** [comment]
/hold
We might need to make additional modifications once the environment is up and running

**Comment by patrickdillon** [comment]
I think you might have missed one here: 
https://github.com/openshift/release/blob/master/ci-operator/step-registry/ipi/deprovision/vsphere/vips/ipi-deprovision-vsphere-vips-commands.sh#L17

**Comment by jcpowermac** [comment]
@patrickdillon thanks for checking

I _think_ I got everything. The IPAM server IP isn't changing since it runs in dev.

```
$ git --no-pager grep 139\.178      
step-registry/ipi/conf/vsphere/vips/ipi-conf-vsphere-vips-commands.sh:            '{network: "139.178.94.128", hostname: $hostn, ipam: "139.178.94.254", ipam_token: $token}')
step-registry/ipi/deprovision/vsphere/vips/ipi-deprovision-vsphere-vips-commands.sh:    curl "http://139.178.89.254/api/removeHost.php?apiapp=address&apitoken=${ipam_token}&host=${cluster_name}-$i"
templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml:          machineCIDR: 139.178.94.128/25
templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml:          machine_cidr = "139.178.94.128/25"
templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml:          ipam = "139.178.89.254"
templates/openshift/installer/cluster-launch-installer-upi-src.yaml:          machineCIDR: 139.178.94.128/25
templates/openshift/installer/cluster-launch-installer-upi-src.yaml:          machine_cidr = "139.178.94.128/25"
templates/openshift/installer/cluster-launch-installer-upi-src.yaml:          ipam = "139.178.89.254"
```

**Comment by jcpowermac** [comment]
Once the secrets are in sync I will run a test.  It _should_ kick off a job that I can monitor from vCenter.

**Comment by wking** [comment]
/lgtm
/hold

Pull the hold when you're happy with the rehearsals.

**Comment by jcpowermac** [comment]
Monitoring a IPI deployment.  The template, masters and the workers have came online.
/hold cancel

**Pull request merged**
