### PR TITLE
NO-JIRA: Add run_if_changed condition for csi-operator extended jobs

### PR DESCRIPTION
**Pull request by Phaow**
- Add run_if_changed condition for csi-operator extended jobs to avoid unnecessary ci resources waste.

### CODE REVIEW

**Comment by Phaow** [comment]
Hi @jsafrane , could you please help take a look when you get a chance? Thank you!

**Comment by jsafrane** [comment]
/lgtm
/approve
I can see it affects only -extended and Windows jobs

**Pull request merged**
