### PR TITLE
Data-path Jobs for BM

### PR DESCRIPTION
**Pull request by jtaleric**
Adding data-path jobs for BM. This is using the existing PerfScale tooling.

### CODE REVIEW

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.15-nightly-x86-data-path

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.15-nightly-x86-data-path

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.15-nightly-x86-data-path

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-nightly-x86-data-path

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.17-nightly-x86-data-path-9nodes

**Comment by josecastillolema** [comment]
Overall lgtm, but I couldn't find the results on the CPT Dashboard, is there any piece missing?

**Pull request merged**
