### PR TITLE
Remove 'day1-post,day2' from the default label filters of the presubmit jobs

### PR DESCRIPTION
**Pull request by yasun1**
[OCM-8223](https://issues.redhat.com//browse/OCM-8223)

### CODE REVIEW

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-rosa-master-e2e-presubmits-pr-rosa-hcp

**Comment by yasun1** [comment]
@ciaranRoche  Could you help review the pull request? Thanks.

**Comment by radtriste** [comment]
@yasun1 I am not sure about that change. Other labels will be tested in Nightlies. We don't need to test everything in PR check.
@xueli181114 wdyt ?

**Comment by yasun1** [comment]
@radtriste We do not test anything. After the change, the presubmit job will test:
1. if `/rosa/tests/ci/data/commit-focus`(generated when build PR image) is not empty, the cases list for each configuration is like `--ginkgo.focus ${FOCUS} --ginkgo.label-filter '!NonHCPCluster&&!Exclude'`.
2.  if `/rosa/tests/ci/data/commit-focus` is empty, which means there are no case IDs recorded, the cases list for each configuration is like `--ginkgo.label-filter 'Critical&&!NonHCPCluster&&!Exclude'`.

In the past, we defined the label filter for each job as `(day1-post,day2)&&!NonHCPCluster&&!Exclude`, which means that even if the case IDs list is not empty, if the case does not belong to `(day1-post,day2)`, it will not be executed. The `(day1-post,day2)&&!NonHCPCluster&&!Exclude` works at beginning. With the team members start automating other runtime features, we need to do this update

**Comment by yasun1** [comment]
@ciaranRoche Could you also help review the PR? Thanks.

**Review by radtriste — APPROVED** [review]
/lgtm

**Pull request merged**
