### PR TITLE
Add more testconfigs for arm on gcp

### PR DESCRIPTION
**Pull request by lwan-wanglin**
for https://issues.redhat.com/browse/ARMOCP-545

### CODE REVIEW

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-gcp-ipi-sno-f28

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-gcp-ipi-sdn-migration-ovn-f28

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-gcp-ipi-private-disasterrecovery-f14

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-gcp-ipi-compact-filestore-csi-f28

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-gcp-ipi-compact-filestore-csi-f28

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-gcp-ipi-baselinecaps-none-additionalcaps-f28

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-gcp-ipi-compact-filestore-csi-f28

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-gcp-ipi-sno-f28

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-gcp-ipi-disconnected-private-workload-identity-f28

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-gcp-ipi-baselinecaps-none-additionalcaps-f28

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-gcp-upi-baselinecaps-v413-f28

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-gcp-ipi-proxy-etcd-encryption-f28

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-gcp-ipi-private-f28-long-duration-cloud

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-gcp-upi-private-xpn-ingress-glb-f28

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-gcp-upi-private-xpn-sdn-f14

**Comment by lwan-wanglin** [comment]
run several new added jobs, all installation part succeeded

- rehearse-41797-periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-gcp-ipi-baselinecaps-none-additionalcaps-f28

https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/41797/rehearse-41797-periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-gcp-ipi-baselinecaps-none-additionalcaps-f28/1686001312002478080

- rehearse-41797-periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-gcp-ipi-compact-filestore-csi-f28

https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/41797/rehearse-41797-periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-gcp-ipi-compact-filestore-csi-f28/1686000140386570240

- rehearse-41797-periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-gcp-ipi-disconnected-private-workload-identity-f28

https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/41797/rehearse-41797-periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-gcp-ipi-disconnected-private-workload-identity-f28/1686000557434605568

- rehearse-41797-periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-gcp-upi-private-xpn-sdn-f14

https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/41797/rehearse-41797-periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-gcp-upi-private-xpn-sdn-f14/1686179533318787072

- rehearse-41797-periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-gcp-ipi-proxy-etcd-encryption-f28

https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/41797/rehearse-41797-periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-gcp-ipi-proxy-etcd-encryption-f28/1686178323052367872

- rehearse-41797-periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-gcp-upi-private-xpn-ingress-glb-f28

https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/41797/rehearse-41797-periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-gcp-upi-private-xpn-ingress-glb-f28/1686178843489996800

- rehearse-41797-periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-gcp-ipi-private-f28-long-duration-cloud/

https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/41797/rehearse-41797-periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-gcp-ipi-private-f28-long-duration-cloud/1686201189428891648

**Comment by jianlinliu** [comment]
cc @liangxia to review

**Pull request merged**
