### PR TITLE
rhods: Build minimal and cuda same pipeline

### PR DESCRIPTION
**Pull request by samuelvl**
1. Build [minimal notebook](https://github.com/red-hat-data-services/cuda-minimal-notebook/tree/develop/minimal) image
2. Use minimal as the base image for [cuda notebook](https://github.com/red-hat-data-services/cuda-minimal-notebook/tree/develop/cuda) image

### CODE REVIEW

**Comment by samuelvl** [comment]
@bbguimaraes @hongkailiu Hey guys, can I get a lgtm in this PR? 

Rehearse jobs are expected to fail until https://github.com/red-hat-data-services/cuda-minimal-notebook/pull/1 is merged but I cannot merge it until this one is merged (egg-chicken problem).

**Review by hongkailiu — APPROVED** [review]

**Pull request merged**
