### PR TITLE
MSI - Onboarding RHODS interop jobs on AWS OSD

### PR DESCRIPTION
**Pull request by omrirh**
Depends on:
- #41329

### CODE REVIEW

**Comment by omrirh** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.11-GA-stage-smoke-osd-rhods-addon-baseline-fips

**Comment by omrirh** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.11-GA-production-smoke-osd-rhods-addon-baseline-fips

**Comment by omrirh** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.11-GA-stage-smoke-osd-rhods-addon-baseline-fips

**Comment by omrirh** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.11-GA-production-smoke-osd-rhods-addon-baseline-fips

**Comment by omrirh** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.11-GA-production-smoke-osd-rhods-addon-baseline-fips

**Comment by omrirh** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.11-GA-stage-smoke-osd-rhods-addon-baseline-fips

**Comment by omrirh** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.12-GA-stage-smoke-osd-rhods-addon-baseline-fips

**Comment by omrirh** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.12-GA-production-smoke-osd-rhods-addon-baseline-fips

**Comment by omrirh** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-IIB-smoke-osd-rhods-addon-baseline-fips

**Comment by omrirh** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-production-smoke-osd-rhods-addon-baseline-fips

**Comment by omrirh** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.14-GA-smoke-osd-rhods-addon-baseline-fips

**Comment by omrirh** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.14-GA-smoke-osd-rhods-addon-baseline-fips

**Comment by omrirh** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-IIB-smoke-osd-rhods-addon-baseline-fips

**Comment by omrirh** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-production-smoke-osd-rhods-addon-baseline-fips

**Review by rnetser — CHANGES_REQUESTED** [review]
RHODS with OSD - only 4.13 tests are needed, please remove 4.11 and 4.12

**Pull request merged**
