### PR TITLE
PowerVS: update ibmcloud 2.22.1 (fix)

### PR DESCRIPTION
**Pull request by hamzy**
The ibmcloud CLI has updated to version 2.22.1

### CODE REVIEW

**Comment by hamzy** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.15-ocp-e2e-ovn-ppc64le-powervs-original-per

**Comment by mjturek** [comment]
the installer was reached so that seems to signal that the version of the CLI you're pointing to is correct.

**Pull request merged**
