### PR TITLE
Add jobs to build FCOS forks of MCD and installer

### PR DESCRIPTION
**Pull request by vrutkovs**
Build installer and MCD from `fcos` branch and promote these to fcos namespace

Supersedes https://github.com/openshift/release/pull/5557 and https://github.com/openshift/release/pull/5589

### CODE REVIEW

**Comment by LorbusChris** [comment]
In openshift-machine-config-operator-fcos.yaml we'll need an RPM build job analogous to #5572, stick that into an fcos-artifacts container and and get the bins from there to layer onto our FCOS ostree content to make an FCOS machine-os-content. Am I missing something?

**Comment by LorbusChris** [comment]
I was able to create an `fcos` branch on the MCO repo, but I don't have permissions to do that on the Installer's.

**Comment by vrutkovs** [comment]
>In openshift-machine-config-operator-fcos.yaml we'll need an RPM build job analogous to #5572, stick that into an fcos-artifacts container and and get the bins from there to layer onto our FCOS ostree content to make an FCOS machine-os-content. Am I missing something?

Eventually, yes, however this setup has been tested with el7 binaries so I'd rather stick to those for now so that rehearse tests would pass before we move further

**Comment by LorbusChris** [comment]
To clarify, what I meant with fcos-artifacts is they come from the `fcos` branches instead of master. That's why we will need a separate container for those artifacts (regardless of their buildroot).

**Pull request closed without merging**
