### PR TITLE
GCP: Change name of sharednetwork job to bring your own vpc

### PR DESCRIPTION
**Pull request by barbacbd**
** With the addition of the shared vpc job for GCP the sharednetwork job seemed a bit misnamed. Renamed the job and workflows to bring your own vpc (byo-vpc). There may be an addition of bring your own dns for some platforms, so it is best to keep this more explicit in what the byo portion includes.

### CODE REVIEW

**Comment by r4f4** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-gcp-ovn-byo-vpc

**Review by danilo-gemoli — APPROVED** [review]

**Pull request merged**
