### PR TITLE
fix: Update step-registry commands

### PR DESCRIPTION
**Pull request by vprashar2929**
This PR updates the step-registry `commands.sh` to include proper logging in case of failures.

### CODE REVIEW

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-operator-v1alpha1-kepler-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-operator-v1alpha1-kepler-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-operator-v1alpha1-kepler-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-operator-v1alpha1-kepler-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-operator-v1alpha1-kepler-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-operator-v1alpha1-kepler-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-operator-v1alpha1-kepler-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-operator-v1alpha1-kepler-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-operator-v1alpha1-kepler-operator-e2e

**Review by sthaha — COMMENTED** [review]
/lgtm
/approve

**Review by sthaha — APPROVED** [review]
/lgtm

**Pull request merged**
