### PR TITLE
jobs/openshift-release-periodics: Add a Slack notification for machine-os-content promotion

### PR DESCRIPTION
**Pull request by cgwalters**
Bring visibility for failures here into the team that should be looking at them.

### CODE REVIEW

**Comment by wking** [comment]
Thoughts about coverage for the other arches?

```console
$ git --no-pager grep 'promote-release-openshift-machine-os-content-e2e-.*4.9' ci-operator/jobs/openshift/release
ci-operator/jobs/openshift/release/openshift-release-release-4.9-periodics.yaml:  name: promote-release-openshift-machine-os-content-e2e-aws-4.9
ci-operator/jobs/openshift/release/openshift-release-release-4.9-periodics.yaml:  name: promote-release-openshift-machine-os-content-e2e-aws-4.9-s390x
ci-operator/jobs/openshift/release/openshift-release-release-4.9-periodics.yaml:  name: promote-release-openshift-machine-os-content-e2e-aws-4.9-ppc64le
```

**Comment by cgwalters** [comment]
> Thoughts about coverage for the other arches?

When this one works

**Review by wking — APPROVED** [review]
/lgtm

**Pull request merged**
