### PR TITLE
Revert "Mirror PAO index image"

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Reverts openshift/release#12822

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@fromanirh Need to revert it, see - https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-image-mirroring-openshift-kni/1316665273759043584

**Comment by fromanirh** [comment]
> @fromanirh Need to revert it, see - https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-image-mirroring-openshift-kni/1316665273759043584

OK, this is caused by the new index and not by the bundle I guess

**Comment by cynepco3hahue** [comment]
> OK, this is caused by the new index and not by the bundle I guess

Yep, because it should be explicitly builder under the images section, I hope it will work just as it :(

**Pull request merged**
