### PR TITLE
stackrox: extend GKE coverage in nightlies

### PR DESCRIPTION
**Pull request by gavin-stackrox**
[ROX-15785](https://issues.redhat.com//browse/ROX-15785)

Tested without `postsubmit: true`: https://prow.ci.openshift.org/pr-history/?org=openshift&repo=release&pr=37146

/uncc
/hold

### CODE REVIEW

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-nightlies-gke-latest-qa-e2e-tests pull-ci-stackrox-stackrox-nightlies-gke-oldest-qa-e2e-tests

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-nightlies-gke-latest-qa-e2e-tests pull-ci-stackrox-stackrox-nightlies-gke-oldest-qa-e2e-tests pull-ci-stackrox-stackrox-nightlies-gke-latest-ui-e2e-tests pull-ci-stackrox-stackrox-nightlies-gke-oldest-ui-e2e-tests pull-ci-stackrox-stackrox-nightlies-gke-latest-nongroovy-e2e-tests pull-ci-stackrox-stackrox-nightlies-gke-oldest-nongroovy-e2e-tests

**Review by BradLugo — APPROVED** [review]
/lgtm

**Pull request merged**
