### PR TITLE
Bump OCM/SubM golangci-lint to 1.43.0

### PR DESCRIPTION
**Pull request by dfarrell07**
Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

**Comment by dfarrell07** [comment]
> It seems the images we want need to be added to imagestreamtags.image.openshift.io first. (I have no idea how to do that.)

Yep, and I don't know either. I also don't know how to check which images are currently there other than guessing/checking.

**Comment by dfarrell07** [comment]
It seems like this is working now, catching real linting errors?

```
golangci-lint run --timeout 10m
test/util/util.go:40:18: ioutilDeprecated: ioutil.ReadFile is deprecated, use os.ReadFile instead (gocritic)
	nsBytes, err := ioutil.ReadFile("/var/run/secrets/kubernetes.io/serviceaccount/namespace")
	                ^
pkg/resource/namespace.go:8:18: ioutilDeprecated: ioutil.ReadFile is deprecated, use os.ReadFile instead (gocritic)
	nsBytes, err := ioutil.ReadFile("/var/run/secrets/kubernetes.io/serviceaccount/namespace")
	                ^
make: *** [Makefile:123: golangci-lint] Error 1
```

**Comment by skitt** [comment]
> It seems like this is working now, catching real linting errors?

Hurray! https://github.com/stolostron/submariner-addon/pull/257 will fix the linting errors.

**Comment by dfarrell07** [comment]
> ci/rehearse/stolostron/submariner-addon/main/golangci-lint — Job succeeded.

:partying_face: :heavy_check_mark:

**Review by tpantelis — APPROVED** [review]

**Pull request merged**
