### PR TITLE
Additional test suites for ARM - Cluster sample operator and serial e2e

### PR DESCRIPTION
**Pull request by deepsm007**
/cc @LorbusChris

### CODE REVIEW

**Comment by yselkowitz** [comment]
Image signature workflow was fixed by https://github.com/openshift/origin/pull/26459

Recently I've been seeing `[sig-network-edge][Feature:Idling] Unidling should handle many TCP connections by possibly dropping those over a certain bound [Serial] [Suite:openshift/conformance/serial]` fail in manual runs of the serial suite; have you not seen that?

When would this cause image-ecosystem to be run?

**Comment by deepsm007** [comment]
Image-ecosystem will run at 0:00 UTC everyday, I haven't tested the serial suite recently. I'll verify with this test run if the same test fails for the serial suite.

**Comment by yselkowitz** [comment]
Image signature workflow fix is being reverted because it is causing issues in fips-serial tests (which unfortunately were not triggered during the original PR to catch that), so serial still needs to wait unfortunately until we can get that fixed again.

**Comment by yselkowitz** [comment]
https://github.com/openshift/origin/pull/26510 has landed in latest nightly, so let's try again.
/retest

**Pull request merged**
