### PR TITLE
Run agent installer jobs on build05 cluster

### PR DESCRIPTION
**Pull request by zaneb**
This allows us to use internal hardware if it is available.

### CODE REVIEW

**Comment by derekhiggins** [comment]
thanks, there are a couple of other occurrences of "e2e-agent-compact" in the installer directory (for 4.12 and 4.13) can you add these. I have another PR covering the other jobs for installer, you might want to wait until it merges to avoid more conflicts. https://github.com/openshift/release/pull/32275

**Comment by zaneb** [comment]
Jobs failed in the expected way (i.e. due to [OCPBUGS-1482](https://issues.redhat.com/browse/OCPBUGS-1482), not failing to pull images or whatever).
/hold cancel

**Review by osherdp — APPROVED** [review]

**Pull request merged**
