### PR TITLE
oadp add support for 4.18

### PR DESCRIPTION
**Pull request by vi-patel**
Other updates
* update cron
* update FIREWATCH_DEFAULT_JIRA_ASSIGNEE
* update .config.prowgen for slack reporting

### CODE REVIEW

**Comment by vi-patel** [comment]
/pj-rehearse periodic-ci-oadp-qe-oadp-qe-automation-main-oadp1.4-ocp4.18-lp-interop-oadp-interop-aws

**Comment by vi-patel** [comment]
/pj-rehearse periodic-ci-oadp-qe-oadp-qe-automation-main-oadp1.4-ocp4.18-lp-interop-oadp-interop-aws-fips

**Comment by vi-patel** [comment]
ODF operator unavailable in 4.18, ODF 4.17 GA 10/30/24

**Comment by dfrazzette** [comment]
Non-FIPS ([1842190929532817408](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/57471/rehearse-57471-periodic-ci-oadp-qe-oadp-qe-automation-main-oadp1.4-ocp4.18-lp-interop-oadp-interop-aws/1842190929532817408)) and FIPS ([1842195059601051648](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/57471/rehearse-57471-periodic-ci-oadp-qe-oadp-qe-automation-main-oadp1.4-ocp4.18-lp-interop-oadp-interop-aws-fips/1842195059601051648)) rehearsal runs failed to install operator. Automation succeeded, so merging PR to include in OCP 4.18 test suite. Will disable weekly run until operator and changes are available.

**Pull request merged**
