### PR TITLE
add api call for 4.12 upgrade jobs

### PR DESCRIPTION
**Pull request by jianzhangbjz**
As the title shows, add `remote_api` for all 4.12 upgrade jobs.

### CODE REVIEW

**Comment by kuiwang02** [comment]
my understanding is that only test which is upgraded to stable build needs it.
and only test upgraded from stabe 4.11 needs it.

**Comment by kuiwang02** [comment]
actually test we trigger is only for install and upgrade, not run case.
it means
for install, the test has chain cucushift-installer-check-cluster-health only, like
```yaml
    test:
    - chain: cucushift-installer-check-cluster-health
```
for upgrade, the test has chain openshift-upgrade-qe-sanity, like
```yaml
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-sanity
```

only these test should be triggered by api, so we'd better to add remote api for these tests only.

**Comment by kuiwang02** [comment]
so, do we need to add remote api for all upgraded tests?

**Comment by jianzhangbjz** [comment]
> do we need to add remote api for all upgraded tests?

Yes, because this `API Call` way can be used by other teams too, not only for errata. Originally, I want to update all Prow jobs, but for now, I just update the 4.12 upgrade jobs for them.

**Pull request merged**
