### PR TITLE
update mco e2e to ocm-e2e-clusterpool

### PR DESCRIPTION
**Pull request by songleo**
ref: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/open-cluster-management_multicluster-observability-operator/818/pull-ci-open-cluster-management-multicluster-observability-operator-release-2.4-test-e2e/1460639922556768256#1:build-log.txt%3A238

### CODE REVIEW

**Review by haoqing0110 — APPROVED** [review]
/lgtm
/approve

**Review by morvencao — COMMENTED** [review]
/lgtm

**Comment by morvencao** [comment]
@songleo Can this be merged now? I still see `hold` label.

**Pull request merged**
