### PR TITLE
USHIFT-1436: capture the image build logs from the remote server

### PR DESCRIPTION
**Pull request by dhellmann**
We are not currently capturing the composer logs if any image fails to build. This PR is one part of correcting that problem.

### CODE REVIEW

**Comment by dhellmann** [comment]
/assign @pacevedom @copejon 

This PR depends on https://github.com/openshift/microshift/pull/2058

**Comment by copejon** [comment]
Same here, likely just needs to be rebased

**Comment by dhellmann** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-metal-tests

**Comment by dhellmann** [comment]
This will need to be re-rehearsed after https://github.com/openshift/microshift/pull/2058 merges. There's no point trying before then.

**Comment by dhellmann** [comment]
/retest-required
/pj-rehearse pull-ci-openshift-microshift-main-microshift-metal-tests

**Comment by ggiguash** [comment]
Got the logs in place. Merging.
/pj-rehearse ack

**Pull request merged**
