### PR TITLE
Update the gcp-kubernetes-e2e job for o/k to be optional

### PR DESCRIPTION
**Pull request by marun**

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
I don't think my lgtm works here but since this is blocking https://github.com/openshift/kubernetes/pull/300 which might fix CI a lot why not try! :joy_cat: 

/lgtm

**Comment by bparees** [comment]
Why don't we expect this job to pass on k8s prs?

**Comment by bparees** [comment]
Seems like a job we'd want to require so k8s updates don't break upgrades, whether it was optional before or not, why is optional the right setting?

**Comment by marun** [comment]
> Seems like a job we'd want to require so k8s updates don't break upgrades, whether it was optional before or not, why is optional the right setting?

@bparees This job has never passed, it's new as part of the hyperkube transition from origin to openshift/kubernetes. I renamed it recently when I switched it to run on gcp instead of aws and the rename made it required because I forgot that jobs need to be manually set optional post-generation (yay footgun).

Getting the job passing will require porting the annotation rules from origin to o/k, which is something I'm working on.

**Pull request merged**
