### PR TITLE
Dump iptables on every node during teardown.

### PR DESCRIPTION
**Pull request by squeed**
Might help with figuring out kube-proxy issues.

### CODE REVIEW

**Comment by squeed** [comment]
I'm not really sure how to best test this - any advice? Or is CI sufficient?

**Comment by squeed** [comment]
cc @danwinship, who has been doing a lot of flake triage these days.

**Comment by smarterclayton** [comment]
Just verify a fascimile runs for you locally

**Comment by squeed** [comment]
Works on my ~machine~ cluster ;-)

**Comment by danwinship** [comment]
lgtm

**Pull request merged**
