### PR TITLE
SPLAT-1276: network/mtu: add feature set

### PR DESCRIPTION
**Pull request by mtulio**
Fix of https://github.com/openshift/release/pull/46212

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_installer/7765/pull-ci-openshift-installer-master-e2e-aws-overlay-mtu-ovn-1200/1729907335251365888#1:build-log.txt%3A135-136

### CODE REVIEW

**Review by r4f4 — COMMENTED** [review]
/approve

**Comment by mtulio** [comment]
> [APPROVALNOTIFIER] This PR is **NOT APPROVED**
> 
> This pull-request has been approved by: _[jcpowermac](https://github.com/openshift/release/pull/46229#issuecomment-1832544126)_, _[mtulio](https://github.com/openshift/release/pull/46229#)_, _[r4f4](https://github.com/openshift/release/pull/46229#pullrequestreview-1756093817)_ **Once this PR has been reviewed and has the lgtm label**, please assign [vrutkovs](https://github.com/vrutkovs) for approval. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

/uncc @vladikr 
/assign @vrutkovs

**Pull request merged**
