### PR TITLE
add 4.17->4.18 upgrade jobs for ovnk and cno

### PR DESCRIPTION
**Pull request by jluhrsen**
this is a manual bump since our automation does not take care of these minor upgrade jobs

### CODE REVIEW

**Comment by jluhrsen** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-release-4.17-4.17-upgrade-from-stable-4.16-e2e-aws-ovn-upgrade

**Comment by jluhrsen** [comment]
not sure why the 4.16->4.17 ovnk rehearsal job didn't run, but just tried it again. all the other jobs seem fine. if that one comes back on we can ack the rehearsals and get approval

**Review by tssurya — APPROVED** [review]

**Pull request merged**
