### PR TITLE
NTO: set long timeout for pao e2e

### PR DESCRIPTION
**Pull request by yanirq**
Signed-off-by: Yanir Quinn <yquinn@redhat.com>

### CODE REVIEW

**Comment by yanirq** [comment]
/pj-rehearse pull-ci-openshift-cluster-node-tuning-operator-release-4.12-e2e-gcp-pao

**Comment by ffromani** [comment]
we set a long timeout because the tests we need to run need to reboot nodes, which is very expensive timewise.
Optimization/rearrangement of tests to cut off wall clock time is planned for the future, we need to un-break our lanes first.

**Review by MarSik — APPROVED** [review]
/lgtm

**Pull request merged**
