### PR TITLE
Libvirt 4.3 installer should use generic image

### PR DESCRIPTION
**Pull request by jaypoulz**
Relates to:
https://github.com/openshift/release/pull/6673
https://github.com/openshift/release/pull/6701

Blocked by:
https://github.com/openshift/installer/pull/3331
https://github.com/openshift/installer/pull/3339

### CODE REVIEW

**Comment by jaypoulz** [comment]
@alvaroaleman This won't pass testing until https://github.com/openshift/installer/pull/3331 lands. Maybe we can hold it in the meantime?

**Comment by alvaroaleman** [comment]
I retested the job because it was failing here because I broke it, it pretty much has nothing to do with your PR, just wanted ppl to avoid thinking it was their changes that introduces the failure of that job :)

**Comment by crawford** [comment]
I forgot that none of these tests are relevant to this PR (a job will come in the future).

/lgtm
/approve

**Pull request merged**
