### PR TITLE
OCPQE-13912: Pub-Private HyperShift guest test

### PR DESCRIPTION
**Pull request by LiangquanLi930**
https://issues.redhat.com/browse/OCPQE-13912

### CODE REVIEW

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-ovn-hypershift-public-private-guest-p1-f7

**Comment by LiangquanLi930** [comment]
@kuiwang02 @liangxia Could you help to review this PR? thanks

**Comment by kuiwang02** [comment]
iamok from golang's view.

**Comment by LiangquanLi930** [comment]
@liangxia Please help to review this OR, when you have time, thanks!

**Pull request merged**
