### PR TITLE
Serverless: weekly jobs on OCP 4.13

### PR DESCRIPTION
**Pull request by mgencur**

### CODE REVIEW

**Comment by mgencur** [comment]
/pj-rehearse periodic-ci-openshift-knative-serverless-operator-main-4.13-gcp-e2e-gcp-ocp-413-continuous
/pj-rehearse periodic-ci-openshift-knative-serverless-operator-main-4.13-hypershift-e2e-hypershift-413-continuous
/pj-rehearse periodic-ci-openshift-knative-serverless-operator-main-4.13-osd-e2e-osd-413-continuous
/pj-rehearse periodic-ci-openshift-knative-serverless-operator-main-4.13-vsphere-e2e-vsphere-ocp-413-continuous

**Comment by mgencur** [comment]
/pj-rehearse periodic-ci-openshift-knative-serverless-operator-main-4.13-hypershift-e2e-hypershift-413-continuous

**Comment by mgencur** [comment]
/pj-rehearse periodic-ci-openshift-knative-serverless-operator-main-4.13-osd-e2e-osd-413-continuous

**Comment by mgencur** [comment]
/pj-rehearse periodic-ci-openshift-knative-serverless-operator-main-4.13-vsphere-e2e-vsphere-ocp-413-continuous

**Comment by mgencur** [comment]
/pj-rehearse periodic-ci-openshift-knative-serverless-operator-main-4.13-osd-e2e-osd-413-continuous

**Comment by mgencur** [comment]
Results from the previous run:
PASSED: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/41174/rehearse-41174-periodic-ci-openshift-knative-serverless-operator-main-4.13-gcp-e2e-gcp-ocp-413-continuous/1679033954813874176
A couple of KafkaSource failures: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/41174/rehearse-41174-periodic-ci-openshift-knative-serverless-operator-main-4.13-hypershift-e2e-hypershift-413-continuous/1679034886201020416
A couple of KafkaSource failures: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/41174/rehearse-41174-periodic-ci-openshift-knative-serverless-operator-main-4.13-vsphere-e2e-vsphere-ocp-413-continuous/1679034941033156608
TestControllerHA failure: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/41174/rehearse-41174-periodic-ci-openshift-knative-serverless-operator-main-4.13-osd-e2e-osd-413-continuous/1679067418481135616

Summary: The specific platforms start correctly. The test failures are not specific to them but to general test suite instability which needs to be fixed elswhere.

**Review by cardil — APPROVED** [review]
/lgtm

**Pull request merged**
