### PR TITLE
OSSM-8069: Add jobs for 3.0 tp1 Istio branch

### PR DESCRIPTION
**Pull request by jwendell**

### CODE REVIEW

**Comment by jwendell** [comment]
/pj-rehearse pull-ci-openshift-service-mesh-istio-release-1.23.0-redhat-integ-pilot pull-ci-openshift-service-mesh-istio-release-1.23.0-redhat-unit

**Comment by jwendell** [comment]
pj-rehearse pull-ci-openshift-service-mesh-istio-release-1.23.0-redhat-integ-pilot pull-ci-openshift-service-mesh-istio-release-1.23.0-redhat-unit

**Comment by jwendell** [comment]
/pj-rehearse pull-ci-openshift-service-mesh-istio-release-1.23.0-redhat-integ-pilot pull-ci-openshift-service-mesh-istio-release-1.23.0-redhat-unit

**Review by yxun — APPROVED** [review]

**Review by sridhargaddam — APPROVED** [review]

**Pull request merged**
