### PR TITLE
OCPBUGS-22169: fix: update tuned script bootloader args

### PR DESCRIPTION
**Pull request by eggfoobar**
updating args to resolve extra reboot issue when tuned is applied

### CODE REVIEW

**Comment by eggfoobar** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade

**Comment by eggfoobar** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade

**Comment by jmencak** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade

**Comment by jmencak** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.15-upgrade-from-stable-4.14-e2e-gcp-ovn-rt-upgrade

**Comment by jmencak** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.13-upgrade-from-stable-4.12-e2e-gcp-ovn-rt-upgrade

**Comment by jmencak** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.11-upgrade-from-stable-4.10-e2e-gcp-ovn-rt-upgrade

**Comment by jmencak** [comment]
The tests are failing due to infra issues.  After manual testing (4.14->4.15 upgrade), I can say
/lgtm
I believe we probably do not need any extra checks for 4.9 (TuneD shipped with NTO)->4.10 (FDP TuneD with NTO).  4.9 is out of support and the 4.9->4.10 upgrade job is informing, not blocking.

**Comment by jmencak** [comment]
looks like I'm not an approval @ffromani , can we have an approval?

**Pull request merged**
