### PR TITLE
Initial commit for jira-lifecycle-plugin

### PR DESCRIPTION
**Pull request by bradmwilliams**

### CODE REVIEW

**Review by AlexNPavel — COMMENTED** [review]
We also need an owners file under `core-services/prow/02_config/openshift-eng/jira-lifecycle-plugin`

**Comment by bradmwilliams** [comment]
> We also need an owners file under `core-services/prow/02_config/openshift-eng/jira-lifecycle-plugin`

Done!

**Review by AlexNPavel — APPROVED** [review]

**Pull request merged**
