### PR TITLE
Add an openshift-kni periodic job that runs the whole suite every 8 hours.

### PR DESCRIPTION
**Pull request by fedepaol**
This will deploy and run all the features together.

### CODE REVIEW

**Comment by fedepaol** [comment]
The periodic failed the deploy phase.
Specifically because of 
```
error: error reading [/go/src/github.com/openshift-kni/baremetal-deploy/features/performance/manifests/generated]: recognized file extensions are [.json .yaml .yml]
```
which I think is happening [here](https://github.com/openshift-kni/baremetal-deploy/blob/02f5b7c70ff559cbb2620ae4a1a6cb140327df28/features/performance/deploy.sh#L14)

I think that's because the `oc` command shipped with the `src` image does not handle applying a whole folder. @davidvossel any ideas on how to handle this?

I can try using golang-1.13 as opposed to the 1.12 which we are currently using, or we can start thinking about building our own `build_root` image. Thoughts?

**Comment by davidvossel** [comment]
some of the performance manifests did apply correctly though. maybe one of the file names being generated isn't formatted correctly. 

```
[INFO]: deploying performance
machineconfigpool.machineconfiguration.openshift.io/master patched
machineconfigpool.machineconfiguration.openshift.io/worker patched
machineconfigpool.machineconfiguration.openshift.io/worker-rt patched
error: error reading [/go/src/github.com/openshift-kni/baremetal-deploy/features/performance/manifests/generated]: recognized file extensions are [.json .yaml .yml]
```

**Comment by davidvossel** [comment]
> we can start thinking about building our own build_root image. Thoughts?

I'm not opposed to the idea. It would allow us to include dependencies like ginkgo into into the build_root.

if you decide to take that route, here's an example of a build root container I built for ocs.

https://github.com/openshift/ocs-operator/blob/master/openshift-ci/Dockerfile.tools#L21

One thing that's nice about the build_root container is that we can start using that container for local builds as well so everyone converges on the same build environment (same golang version, ginkgo version, etc...)

**Comment by fedepaol** [comment]
> > we can start thinking about building our own build_root image. Thoughts?
> 
> I'm not opposed to the idea. It would allow us to include dependencies like ginkgo into into the build_root.
> 
> if you decide to take that route, here's an example of a build root container I built for ocs.
> 
> https://github.com/openshift/ocs-operator/blob/master/openshift-ci/Dockerfile.tools#L21
> 

Nice, I was just wondering how to include oc in that image.

> One thing that's nice about the build_root container is that we can start using that container for local builds as well so everyone converges on the same build environment (same golang version, ginkgo version, etc...)

Yes, although in my opinion we need to find the sweet spot in building around `go build` & friends, to avoid lack of clarity / readability.

**Comment by fedepaol** [comment]
/test pj-rehearse
hoping it was just a flake

**Comment by davidvossel** [comment]
/lgtm
/approve

these configs look fine, it's actually the periodic test that's broken

**Pull request merged**
