### PR TITLE
[odf-must-gather] Update CI configuration for release-4.15 branch

### PR DESCRIPTION
**Pull request by black-dragon74**
DO NOT MERGE until the linked issue is closed!

Blocked by: https://github.com/red-hat-storage/odf-must-gather/issues/72

Regards

### CODE REVIEW

**Comment by black-dragon74** [comment]
@yati1998 can you please add ok-to-test?

Regards

**Comment by black-dragon74** [comment]
Waiting on the linked issue before we merge this. Please do not merge until then.

**Review by yati1998 — APPROVED** [review]
LGTM

**Pull request merged**
