### PR TITLE
Adding job of upcoming knative v0.5.0 release

### PR DESCRIPTION
**Pull request by matzew**
as per title

### CODE REVIEW

**Comment by matzew** [comment]
```
[ERROR] This check enforces that configuration YAML files will be uploaded automatically
[ERROR] as they change. You are adding a file that is not covered by the automatic upload.
[ERROR] Contact an administrator to resolve this issue.

[ERROR] The following errors were found:

time="2019-04-01T18:33:49Z" level=warning msg="Failed to determine info for prow job config" error="file name was not prefixed with \"ci-operator-jobs-\": \"infra-periodics\"" source-file=ci-operator/jobs/infra-periodics.yaml
time="2019-04-01T18:33:49Z" level=error msg="File matches glob from unexpected ConfigMap." glob="ci-operator/config/openshift/external-dns/*openshift-4.0*.yaml" source-file=ci-operator/config/openshift/external-dns/openshift-external-dns-openshift-4.0.yaml
time="2019-04-01T18:33:50Z" level=error msg="File matches glob from unexpected ConfigMap." glob="ci-operator/jobs/openshift/external-dns/*openshift-4.0*.yaml" source-file=ci-operator/jobs/openshift/external-dns/openshift-external-dns-openshift-4.0-postsubmits.yaml
time="2019-04-01T18:33:50Z" level=error msg="File matches glob from unexpected ConfigMap." glob="ci-operator/jobs/openshift/external-dns/*openshift-4.0*.yaml" source-file=ci-operator/jobs/openshift/external-dns/openshift-external-dns-openshift-4.0-presubmits.yaml
time="2019-04-01T18:33:51Z" level=fatal msg="Found configurations that do not belong to the correct auto-updating config"
```

hrm - weird ...

**Comment by mgencur** [comment]
/lgtm 
The e2e tests will be tuned on `openshift/knative-eventing` side after this is integrated.

**Pull request merged**
