### PR TITLE
NTO: Old base images cleanup.

### PR DESCRIPTION
**Pull request by jmencak**

### CODE REVIEW

**Comment by jmencak** [comment]
/hold
This needs more work, putting on the back burner for the time being.

**Comment by jmencak** [comment]
/hold cancel
the upgrade failures match failures in other release PRs too.

**Comment by jmencak** [comment]
OK, a lot more failures than last time
/retest

**Comment by jmencak** [comment]
@kpouget , the tests are extremely flaky.  The best I got was only 4.8 and 4.9 e2e-upgrade tests failing with the same PR state. I'm very doubtful that I actually introduced the issue with this PR and I don't believe that hammering with /retest will help. WDYT?

**Comment by kpouget** [comment]
@jmencak 
sure, I see this PR has the same kind of issue as Eduardo's https://github.com/openshift/release/pull/17585,
and indeed I don't think that hammering is the best way to go :(

this page gives an overview of the retry history:
https://prow.ci.openshift.org/pr-history/?org=openshift&repo=release&pr=17590

and only those two never passed:
- rehearse-17590-pull-ci-openshift-cluster-node-tuning-operator-release-4.9-e2e-upgrade
- rehearse-17590-pull-ci-openshift-cluster-node-tuning-operator-release-4.8-e2e-upgrade

if you're confident that it's unrelated to the PR and it's safe to merge, I can approve the PR

**Comment by jmencak** [comment]
> @jmencak
> sure, I see this PR has the same kind of issue as Eduardo's #17585,
> and indeed I don't think that hammering is the best way to go :(
> 
> this page gives an overview of the retry history:
> https://prow.ci.openshift.org/pr-history/?org=openshift&repo=release&pr=17590
> 
> and only those two never passed:
> 
>     * rehearse-17590-pull-ci-openshift-cluster-node-tuning-operator-release-4.9-e2e-upgrade
> 
>     * rehearse-17590-pull-ci-openshift-cluster-node-tuning-operator-release-4.8-e2e-upgrade
> 
> 
> if you're confident that it's unrelated to the PR and it's safe to merge, I can approve the PR

Confident is a strong word, but I'm pretty sure it is unrelated. One thing I still need to understand where do `tag: rhel-8-release-openshift-4.6` and similar come from and how do I check they exist. Perhaps @ArangoGutierrez knows as he changed the tag in his PR.  For me, I know that blindly changing to `rhel-8-release-openshift-4.8` resulted in a completely broken PR as the tag did not exist.

**Comment by kpouget** [comment]
one thing I understood from Eduardo's comment is that these changes should only directly affect the `image` test: if the `image` can be correctly built, then the logic of the build process is consistent.

What comes after is ensuring that the newly built image (= the Go version update) doesn't break anything in the test suite. And that part is unfortunately flaky. 

So the way I see it is:
```
ci/rehearse/openshift/cluster-node-tuning-operator/master/images — Job succeeded. 
```
--> the logic is good
and for the rest, I can trust your best judgement!

**Comment by jmencak** [comment]
I think this can be merged now. All master "branch" tests passed. As for the rest I just cannot believe this PR intruduced the failures. Will test on a docs PR once this merges.

**Comment by kpouget** [comment]
/lgtm

> +12 -108
that's some good cleanup :)

**Pull request merged**
