### PR TITLE
prow: hook up coreos/coreos-assembler

### PR DESCRIPTION
**Pull request by jlebon**
This is mostly copy-pasted from the rpm-ostree one.

### CODE REVIEW

**Comment by jlebon** [comment]
Let's hold this one though until the rpm-ostree is all set up and tested working well.
/hold

**Comment by cgwalters** [comment]
> Let's hold this one though until the rpm-ostree is all set up and tested working well.

Yeah that was the idea.

**Comment by LorbusChris** [comment]
What does `/blunderbuss`do? :smile:

**Comment by petr-muller** [comment]
> What does `/blunderbuss`do? smile

_The blunderbuss plugin automatically requests reviews from reviewers when a new PR is created. The reviewers are selected based on the reviewers specified in the OWNERS files that apply to the files modified by the PR._

https://prow.svc.ci.openshift.org/plugins

**Comment by petr-muller** [comment]
Looks stale, please adapt and reopen if still needed.

/close

**Pull request closed without merging**
