### PR TITLE
[Baremetal/QE] IPI installation steps

### PR DESCRIPTION
**Pull request by aleskandro**
This PR introduces the steps to execute Baremetal IPI installation in the qe labs.

The following changes are included:
- `reserve-nodes` now takes into account the architecture of the required nodes so that we can use a single auxiliary server to provision both arm64 and amd64 clusters (this is a key enabler for testing Baremetal UPI clusters with multi-arch compute nodes)
- `provisioning-network`: the datamodel in the auxiliary host is updated to consider hosts connected to different switch stacks and the python code can now make multiple transactions, one per switch stack to configure. We do not implement a 'two-phase commit' strategy because a single failure would lead to the interruption of the workflow and the execution of the post steps. The post steps implement the rollback mechanism which works independently of a previous failure. We can safely ignore and wait for this reconciliation to be ran.
- introduced the `ipi-deprovision` step to handle the deletion of the bootstrap VM when early installation failures occur.
- introduced the `ipi-install` step that finalizes the install-config, creates manifests and ignitions, and finally installs the cluster. This step will execute the installation locally in the executor pod, setting the `libvirtURI` to reach the hypervisor of the provisioning host by the ssh transport (`qemu+ssh://`). During the bootstrap, the ironic endpoint is reachable via the APIVIP that is bound to the bootstrap VM. It is needed to be reached by the ironic-terraform provider running in the installer pod. As the labs APIVIPs are not routable, we use a proxy to run the `create cluster` command. This can be considered safe and doesn't affect the following steps for connected clusters.
- introduced chains and workflows similarly to the previously ones implemented for UPI installations.
- Finally, as we [don't ship](https://github.com/openshift/installer/blob/master/images/baremetal/Dockerfile.ci) the `baremetal-installer` for all the architectures in single-arch payloads (it needs CGO), we use the multi payload to allow extracting the baremetal-installer from the proper (in architecture) manifest.

Example test config:

```
tests:
- as: baremetal-ipi-ovn-ipv4-p1-f4
  cluster: build05
  cron: 0 0 * * *
  steps:
    cluster_profile: equinix-ocp-metal-qe
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:arm64-latest
    env:
      AUX_HOST: openshift-qe-bastion.arm.eng.rdu2.redhat.com
      DISCONNECTED: "false"
      IPI: "true"
      PROVISIONING_HOST: openshift-qe-bastion.arm.eng.rdu2.redhat.com
      PROVISIONING_NET_DEV: enP2p2s0f1
      architecture: arm64
      masters: "3"
      workers: "2"
    test:
    - ref: clusterbot-wait
    workflow: baremetal-lab-ipi
```
Installation succeeded before removing the above test config.

https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/36288/rehearse-36288-periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-nightly-baremetal-ipi-ovn-ipv4-p1-f4/1625135523913797632

### CODE REVIEW

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-4.13-upgrade-from-stable-4.12-azure-upi-p3-f28

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-nightly-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-nightly-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-nightly-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
Installation passing, at commit 6c666ab38580991c1e4a6c00bc56974092ea370e, before code finalization/rebasing/squashing

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-nightly-baremetal-ipi-ovn-ipv4-p1-f4

**Comment by aleskandro** [comment]
Refers ARMOCP-482

**Comment by aleskandro** [comment]
The installation succeeded: https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/36288/rehearse-36288-periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-nightly-baremetal-ipi-ovn-ipv4-p1-f4/1625135523913797632

Removing the test config commit and squashing

**Review by droslean — APPROVED** [review]

**Comment by aleskandro** [comment]
Refers OCPQE-11883

**Pull request merged**
