### PR TITLE
remove nested word from common-templates jobs name

### PR DESCRIPTION
**Pull request by ksimon1**
all common-templates jobs are failing due to long name
/cc @omeryahud @akrejcir 

Signed-off-by: Karel Šimon <ksimon@redhat.com>

### CODE REVIEW

**Comment by akrejcir** [comment]
@omeryahud @ksimon1, Please do not approve PRs in this repo before the CI passes, otherwise the PR will be merged ignoring CI.

**Comment by omeryahud** [comment]
@akrejcir I was not aware of that, thanks Andrej

**Pull request merged**
