### PR TITLE
Shorten the install job jenkins context and trigger

### PR DESCRIPTION
**Pull request by smarterclayton**
Also update install_update

### CODE REVIEW

**Comment by smarterclayton** [comment]
@stevekuznetsov

**Comment by kargakis** [comment]
Needs context migration

**Comment by stevekuznetsov** [comment]
@smarterclayton are you familiar with `test-infra/maintenance/migratestatus` ?

**Comment by kargakis** [comment]
https://github.com/kubernetes/test-infra/tree/master/maintenance/migratestatus

Grab the openshift-bot token with `oc get secret openshift-bot-token -o yaml -n ci`

**Comment by stevekuznetsov** [comment]
Err I usually use `openshift-bot` token or my own token -- try not to use `openshift-ci-robot` token so we have no chance of DOS on the queue/plugins

**Comment by smarterclayton** [comment]
will look tomorrow

**Pull request closed without merging**
