### PR TITLE
sriov: create `SriovOperatorConfig` while deploying

### PR DESCRIPTION
**Pull request by zeeke**
To align CI to PR
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/617

an `SriovOperatorConfig/default` needs to be created to make the SR-IOV network operator start working.

cc @EmilienM, @SchSeba, @bn222

### CODE REVIEW

**Comment by zeeke** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-master-operator-e2e pull-ci-openshift-sriov-network-operator-master-e2e-openstack-nfv pull-ci-openshift-sriov-network-operator-release-4.14-e2e-openstack-nfv

**Comment by EmilienM** [comment]
Thanks. I'll keep an eye on this PR. BTW, can it be applied on old versions, down to 4.12? If not, we'll need to add a conditional.

@MaysaMacedo to keep an eye on this one while I'm away.

**Comment by EmilienM** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-master-e2e-openstack-nfv

**Comment by EmilienM** [comment]
/cc MaysaMacedo
Please keep an eye on this one while I'm away, :pray:

**Comment by zeeke** [comment]
> Thanks. I'll keep an eye on this PR. BTW, can it be applied on old versions, down to 4.12? If not, we'll need to add a conditional.

@EmilienM @MaysaMacedo what do you want to apply to old versions? This PR changes step script `ci-operator/step-registry/openstack/provision/sriov-networknodepolicy/openstack-provision-sriov-networknodepolicy-commands.sh`, which  is shared among all the release branches. The need to create the SriovOperatorConfig resource is for 4.16+ only, but creating it on older branches is not a problem: the operator creates it's not present.

**Comment by zeeke** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-master-operator-e2e pull-ci-openshift-sriov-network-operator-master-e2e-openstack-nfv pull-ci-openshift-sriov-network-operator-release-4.14-e2e-openstack-nfv

**Comment by zeeke** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-master-operator-e2e pull-ci-openshift-sriov-network-operator-master-e2e-openstack-nfv pull-ci-openshift-sriov-network-operator-release-4.14-e2e-openstack-nfv

**Comment by zeeke** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-master-operator-e2e pull-ci-openshift-sriov-network-operator-master-e2e-openstack-nfv pull-ci-openshift-sriov-network-operator-release-4.14-e2e-openstack-nfv

**Comment by zeeke** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-master-e2e-openstack-nfv

**Comment by zeeke** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-master-e2e-openstack-nfv

**Comment by zeeke** [comment]
/pj-rehearse ack

@SchSeba @MaysaMacedo please, take a look

**Comment by SchSeba** [comment]
nice work!

/lgtm
/approve

**Comment by MaysaMacedo** [comment]
While I see the creation of `SriovOperatorConfig` in older releases didn't impact, it can give a wrong impression that this is a requirement in those releases. Do you mind adding a  comment that this is a requirement only for 4.16+ releases?

**Comment by MaysaMacedo** [comment]
/lgtm
/approve

comment additional can be added in a follow up PR

**Pull request merged**
