### PR TITLE
Adding write main branch

### PR DESCRIPTION
**Pull request by paigerube14**
Want to point to the main write branch, not my personal fork that my changes dont immediately effect tests 

@svetsa-rh @jtaleric

### CODE REVIEW

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-ocp-qe-perfscale-aws-node-density-heavy-small-scale

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-ocp-qe-perfscale-aws-node-density-heavy-small-scale

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-gcp-4.13-ocp-qe-perfscale-ci-tests-net-perf

**Comment by paigerube14** [comment]
@svetsa-rh can you ptal, one test passed and wrote to sheet as expected

**Comment by svetsa-rh** [comment]
@paigerube14 Can we change to the generic one 
`
+ export EMAIL_ID_FOR_RESULTS_SHEET=prubenda@redhat.com
+ EMAIL_ID_FOR_RESULTS_SHEET=prubenda@redhat.com
`

Also, I noticed several failures like this below:
`{
        "shard" : 0,
        "index" : "sysctl-metadata",
        "node" : "LOFR5gukQOmi3yoMoITUdA",
        "reason" : {
          "type" : "query_shard_exception",
          "reason" : "failed to create query: For input string: \"2023-09-19T14:30:56.000Z\"",
          "index_uuid" : "2MiyMIHBR82gDD6cX5bH_w",
          "index" : "sysctl-metadata",
          "caused_by" : {
            "type" : "number_format_exception",
            "reason" : "For input string: \"2023-09-19T14:30:56.000Z\""
          }
        }
      },
`


We may want to investigate it separately, but can we track it somewhere not to lose it.

**Comment by svetsa-rh** [comment]
Also, may be some debug output here but can we may be add more info on what to make of it? 
`
Status :  oc get cm cluster-config-v1 -n kube-system -o json | jq -r '.data' | grep 'fips' 
**return code1**
command oc get clusterversion --no-headers | awk '{print $2}'
command oc get nodes | grep worker | wc -l | xargs
**scale false**
`

**Comment by svetsa-rh** [comment]
Sorry, one more, I see 2 directories being written:
openshift-qe-write-perfscale-results/
openshift-qe-write-perfscale-results-ingress-perf/

From directory names it is not clear, what the difference between both are and also contents look somewhat identical, but I see some differences too.. anything we can do to it make it clearer so folks now what to expect in each directory?

**Comment by paigerube14** [comment]
@svetsa-rh can you send me the logs of where you are seeing that error? I don't see it in the write stuff that is effecting this pr. 
The directory name is based on the name of the ref used. I tried to limit the amount of sub folders I had to make so network perf uses the default commands and ingress perf uses a sub folder because you can't use the same ref in a test step

https://github.com/openshift/release/blob/01a4941fe1772a5da101db37ad8d2885a4dea33d/ci-operator/step-registry/openshift-qe/network-perf/openshift-qe-network-perf-chain.yaml#L6
https://github.com/openshift/release/blob/01a4941fe1772a5da101db37ad8d2885a4dea33d/ci-operator/step-registry/openshift-qe/ingress-perf/openshift-qe-ingress-perf-chain.yaml#L5

**Comment by paigerube14** [comment]
> Also, may be some debug output here but can we may be add more info on what to make of it? `Status : oc get cm cluster-config-v1 -n kube-system -o json | jq -r '.data' | grep 'fips' **return code1** command oc get clusterversion --no-headers | awk '{print $2}' command oc get nodes | grep worker | wc -l | xargs **scale false**`

This is in the prow script itself not in this pr

**Comment by paigerube14** [comment]
@svetsa-rh that's just the response from elastic search. Also in the prow script itself not in this pr. 
I would like to try to get the functionality we had back before we make any changes

**Comment by svetsa-rh** [comment]
> > Also, may be some debug output here but can we may be add more info on what to make of it? `Status : oc get cm cluster-config-v1 -n kube-system -o json | jq -r '.data' | grep 'fips' **return code1** command oc get clusterversion --no-headers | awk '{print $2}' command oc get nodes | grep worker | wc -l | xargs **scale false**`
> 
> This is in the prow script itself not in this pr

Like Prow system itself or another script of ours in Prow? 
Even here, I am not suggesting that we make this change but asking if we can track these somewhere (may be Jira?)

**Comment by svetsa-rh** [comment]
> @svetsa-rh that's just the response from elastic search. Also in the prow script itself not in this pr. I would like to try to get the functionality we had back before we make any changes

Agree! I am fine with another PR or jira tracking, since I saw them thought I'd bring it up for discussion.

**Comment by paigerube14** [comment]
@svetsa-rh all the logs are actually being written using this script: https://github.com/openshift-qe/ocp-qe-perfscale-ci/blob/write-scale-ci-results/write_to_sheet/prow_write.py

This issue is trying to fix the prow configuration to not point to my fork and branch so that we can formally review my changes (in the ocp-qe-perfscale-ci repo) in separate PR's so that when I make changes in my own branch and push the prow jobs aren't effected 

A jira is good but I dont think those changes need to stop this pr

**Comment by svetsa-rh** [comment]
> A jira is good but I dont think those changes need to stop this pr
except for email Id, none were to stop this PR Paige
Should have probably started a slack thread instead of here.

**Pull request merged**
