### PR TITLE
Add environment variable to CI config

### PR DESCRIPTION
**Pull request by brucejcong**

### CODE REVIEW

**Comment by sjenning** [comment]
/hold
Why do we want to disable PKI on the AWS flow?

**Comment by brucejcong** [comment]
Hey @sjenning from my understanding, this is to address this issue here: https://github.com/openshift/hypershift/issues/2455. According to Hide after convos with Cesar, this would help in extending the CI tests. 

From my understanding, this should catch if any PKI contracts has been broken on patch updates, but let me know if there's anything I'm missing! This PR goes with it: https://github.com/openshift/hypershift/pull/2989

**Comment by csrwng** [comment]
@brucejcong The thinking was to disable PKI reconciliation on upgrade for branches != main

**Comment by csrwng** [comment]
@brucejcong you'll need to add the env var to https://github.com/openshift/release/blob/5a157e42551ae816941865abaed833468a6021ca/ci-operator/step-registry/hypershift/aws/run-e2e/hypershift-aws-run-e2e-chain.yaml#L24
and default it to "false"

**Comment by csrwng** [comment]
/hold cancel
This is to test that no new PKI is introduced in previous minor releases.

**Pull request merged**
