### PR TITLE
Create install status and junit before must-gather

### PR DESCRIPTION
**Pull request by Shilpa-Gokul**

### CODE REVIEW

**Comment by Shilpa-Gokul** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.15-ocp-e2e-ovn-remote-libvirt-ppc64le

**Comment by Shilpa-Gokul** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.15-ocp-e2e-ovn-remote-libvirt-ppc64le

**Comment by Shilpa-Gokul** [comment]
> Why a separate step? Looks like there will be two copies of the installer junit code now which will make it harder to maintain.

Actually our requirement is, **we want the junit to be populated even if the the previous step has passed or failed**. Since gather-must-gather step has the flag "optional_on_success" set to true, the step is not invoked on success builds. Also I can't remove "optional_on_success" flag because it ends up collecting must-gather.tar for success builds too.

Since we didn't want to alter the gather-must-gather step, thought of adding a new step in the gather chain which will invoke the junit code based on the e2e result from our workflow. But we are still trying to figure out how to just invoke the createInstallJunit function without duplicating the entire code. Please advice if there is any other feasible solution for this.

Note: We are relying on this junit data to add a release informing job which will analyse and qualify a release payload based on the install status of the jobs

**Comment by stbenjam** [comment]
> Since gather-must-gather step has the flag "optional_on_success" set to true, the step is not invoked on success builds. Also I can't remove "optional_on_success" flag because it ends up collecting must-gather.tar for success builds too.

I think that's desirable - for all the CI jobs TRT manages, we collect must-gathers even on success.  It's useful because sometimes you may need to debug or investigate a job that was successful.  We also have plans for post-processing must-gathers to extract additional information from them for reporting into TRT's bigquery databases.

**Comment by jaypoulz** [comment]
My notes are - I'm fine with us setting the https://github.com/openshift/release/pull/53278/files#diff-1128a4a4d23c110aa38b6e9206841e774cd2b745ef6cee1d8d2dac4f15bd8277R5 flag to false to ensure that we always gather results for multi-arch jobs; however, we shouldn't touch the flags in the gather steps themselves (e.g. https://github.com/openshift/release/blob/master/ci-operator/step-registry/gather/must-gather/gather-must-gather-ref.yaml) since this would affect all CI jobs that reference them and we aren't paying the build for log storage. :)

**Comment by stbenjam** [comment]
> My notes are - I'm fine with us setting the https://github.com/openshift/release/pull/53278/files#diff-1128a4a4d23c110aa38b6e9206841e774cd2b745ef6cee1d8d2dac4f15bd8277R5 flag to false to ensure that we always gather results for multi-arch jobs; however, we shouldn't touch the flags in the gather steps themselves (e.g. https://github.com/openshift/release/blob/master/ci-operator/step-registry/gather/must-gather/gather-must-gather-ref.yaml) since this would affect all CI jobs that reference them and we aren't paying the bill for log storage. :)

Checked with the folks who are paying the bills and they're not concerned, it's already running in the vast majority of jobs.
  
If you make a change to gather-must-gather-ref.yaml I'm happy to approve it.

Thanks for noticing this - it's important to collect install results from everyone.

**Comment by Shilpa-Gokul** [comment]
@stbenjam I don't want to alter gather-must-gather step since its used by many other workflows. I have changed the flags for our workflows alone as Jeremy suggested. Could you please take a look?

**Comment by Shilpa-Gokul** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-heavy-build-ovn-remote-libvirt-ppc64le

**Pull request merged**
