### PR TITLE
readd prow jobs for origin release-3.9 azure testing

### PR DESCRIPTION
**Pull request by jim-minter**

### CODE REVIEW

**Comment by jim-minter** [comment]
@kargakis ptal

I think we should be good to do release branch testing, but not master branch yet.

I've removed the prow-submitted image builds because
a) there are ordering requirements (base image before node)
b) it's madness to have 4 different jenkins jobs, one per image, and I can't see a way to pass in parameters from prow to jenkins

As a stopgap I've created https://ci.openshift.redhat.com/jenkins/job/azure_build_images as a scheduled task to run the image builds, but request your input on how to do this "properly".

**Comment by kargakis** [comment]
> a) there are ordering requirements (base image before node)

You can order jobs by using `run_after_success`
```yaml
- name: azure_build_base_image_rhel
  agent: jenkins
  labels:
      master: ci.openshift.redhat.com
  interval: 168h
  run_after_success:
  - name: azure_build_node_image_rhel
    agent: jenkins
    labels:
        master: ci.openshift.redhat.com
```
>  b) it's madness to have 4 different jenkins jobs, one per image, and I can't see a way to pass in parameters from prow to jenkins

The main problem with a parameterized job is that the failure signal is going to be problematic. You don't know what is failing from a glance. Prow exposes job metrics and in the case of a parameterized job, they won't be helpful. That being said, passing env variables from prow down to Jenkins is a valid request but it requires a proposal+api changes and at that point I think going back to separate jobs is better (and more reliable).

**Comment by jim-minter** [comment]
> I think going back to separate jobs is better

Ok, I'll deal with it using `parent:` in aos-cd-jobs/sjb and that'll handle the worst of it for now.  But as we produce more images, the number of jenkins jobs will increase...

**Comment by jim-minter** [comment]
@kargakis ptal

**Pull request merged**
