### PR TITLE
MGMT-16079: Update master release configurations file to point to OCP 4.15

### PR DESCRIPTION
**Pull request by danmanor**
Update master release configurations file to point to `OCP 4.15`

### CODE REVIEW

**Review by adriengentil — APPROVED** [review]
Let's wait for the full rehearse

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-agent-master-edge-e2e-metal-assisted-upgrade-agent

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-4-10

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-day2-arm-workers

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-image-service-main-edge-e2e-metal-assisted-day2-arm-workers

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-day2-arm-workers

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-day2-arm-workers pull-ci-openshift-assisted-image-service-main-edge-e2e-metal-assisted-day2-arm-workers

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-image-service-main-edge-e2e-metal-assisted-day2-arm-workers

**Review by filanov — APPROVED** [review]

**Pull request merged**
