### PR TITLE
ocm: add new repo multicloudhub-operator

### PR DESCRIPTION
**Pull request by JakobGray**

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/uncc
You can ping me once this is ready and has seen approval from another owner of this repo

**Review by alvaroaleman — APPROVED** [review]
/label tide/merge-method-squash

**Comment by JakobGray** [comment]
@alvaroaleman The CI errors don't look related to the PR. Any advice on getting it passing?

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
