### PR TITLE
Toil reduction/stale bot

### PR DESCRIPTION
**Pull request by iamkirkbater**
Adds Openshift Repos to stale/rotten/close workflows with the CI bot, per OSD-4041 and SRE Toil Reduction Workflow.

I also sorted the list, since there are now so many repos there, instead of just appending the list for future maintainability.

### CODE REVIEW

**Comment by RiRa12621** [comment]
/hold
This should be obsolete if https://github.com/openshift/release/pull/9636#pullrequestreview-429061109 is agreed upon and implemented

**Comment by iamkirkbater** [comment]
@RiRa12621 should we just close this PR in lieu of #9396 in general?

**Comment by RiRa12621** [comment]
I think it depends: if we're going to add openshift/* to stale bot, then yes, but if it's decided otherwise, I prefer this one for OSD-SRE as it's including multiple state.

Essentially we need more information from @stevekuznetsov or @eparis on how we proceed with #9636

**Comment by iamkirkbater** [comment]
Closed because of #10573

**Pull request closed without merging**
