### PR TITLE
fix the eror when no_proxy var not exist

### PR DESCRIPTION
**Pull request by anpingli**

### CODE REVIEW

**Comment by anpingli** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-c2s-ipi-disc-priv-fips-f28-destructive

**Comment by anpingli** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-baremetal-ha-agent-ipv4-static-disc-fips-f7

**Comment by anpingli** [comment]
[enable-qe-catalogsource-disconnected ](https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/55597/rehearse-55597-periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-baremetal-ha-agent-ipv4-static-disc-fips-f7/1823915652730064896/artifacts/baremetal-ha-agent-ipv4-static-disc-fips-f7/enable-qe-catalogsource-disconnected/build-log.txt)pass in Job periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-baremetal-ha-agent-ipv4-static-disc-fips-f7

**Comment by anpingli** [comment]
@jianzhangbjz  Can you review it?

**Comment by anpingli** [comment]
[enable-qe-catalogsource-disconnected](https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/55597/rehearse-55597-periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-c2s-ipi-disc-priv-fips-f28-destructive/1823915511226830848/artifacts/aws-c2s-ipi-disc-priv-fips-f28-destructive/enable-qe-catalogsource-disconnected/build-log.txt) pass   in periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-c2s-ipi

**Comment by jianzhangbjz** [comment]
This PR addressed: [https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/logs/periodic-ci-o[…]atalogsource-disconnected/build-log.txt](https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-baremetal-ha-agent-ipv4-static-disc-fips-f7/1822264069554442240/artifacts/baremetal-ha-agent-ipv4-static-disc-fips-f7/enable-qe-catalogsource-disconnected/build-log.txt)
```console
environment: line 21: no_proxy: unbound variable
```

**Pull request merged**
