### PR TITLE
fix opendatahub io caikit tgis serving build

### PR DESCRIPTION
**Pull request by dtrifiro**
- opendatahub-io/caikit-tgis-serving: fix run_if_changed deps
- opendatahub-io/caikit-tgis-serving: get rid of text-generation-inference as base image

### CODE REVIEW

**Comment by dtrifiro** [comment]
@Xaenalt

**Review by Xaenalt — APPROVED** [review]

**Comment by Xaenalt** [comment]
/pj-rehearse pull-ci-opendatahub-io-caikit-tgis-serving-main-pr-image-mirror

**Pull request merged**
