### PR TITLE
Add FAR v0.2.0

### PR DESCRIPTION
**Pull request by razo7**
Add config and presubmit files for FAR v0.2.0 release branch, release-0.2, for OCP 4.11-4.14

### CODE REVIEW

**Review by slintes — APPROVED** [review]

**Comment by razo7** [comment]
/pj-rehearse pull-ci-medik8s-fence-agents-remediation-release-0.2-4.14-openshift-e2e

**Review by clobrano — APPROVED** [review]

**Comment by razo7** [comment]
It looks like rebase was needed
/pj-rehearse pull-ci-medik8s-fence-agents-remediation-release-0.2-4.14-openshift-e2e
/pj-rehearse auto-ack

**Comment by razo7** [comment]
/pj-rehearse pull-ci-medik8s-fence-agents-remediation-release-0.2-4.14-openshift-e2e
/pj-rehearse auto-ack

**Pull request merged**
