### PR TITLE
Rename e2e-aws-ovn-kubernetes to e2e-aws-ovn

### PR DESCRIPTION
**Pull request by danwinship**
followup to #5073

/cc @squeed 
/assign @smarterclayton

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
/hold

Does this update _all_ config?

```
$ git grep -l ovn-kubernetes
ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master.yaml
ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.1.yaml
ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.2.yaml
ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.3.yaml
ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.4.yaml
ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.5.yaml
ci-operator/jobs/infra-periodics.yaml
ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master-postsubmits.yaml
ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master-presubmits.yaml
ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.1-postsubmits.yaml
ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.1-presubmits.yaml
ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.2-postsubmits.yaml
ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.2-presubmits.yaml
ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.3-postsubmits.yaml
ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.3-presubmits.yaml
ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.4-postsubmits.yaml
ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.4-presubmits.yaml
ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.5-postsubmits.yaml
ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.5-presubmits.yaml
ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
ci-operator/jobs/openvswitch/ovn-kubernetes/openvswitch-ovn-kubernetes-master-postsubmits.yaml
ci-operator/jobs/openvswitch/ovn-kubernetes/openvswitch-ovn-kubernetes-master-presubmits.yaml
core-services/image-mirroring/openshift/mapping_origin_4_1
core-services/image-mirroring/openshift/mapping_origin_4_2
core-services/image-mirroring/openshift/mapping_origin_4_3
core-services/prow/02_config/_config.yaml
core-services/prow/02_config/_plugins.yaml
core-services/release-controller/_releases/release-ocp-4.3.json
core-services/release-controller/_releases/release-ocp-4.4.json
hack/validate-owners.sh
```

**Comment by danwinship** [comment]
> Does this update _all_ config?

The repo and image are still named `ovn-kubernetes`, so there will still be instances of the full name.

> ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master.yaml
> ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.1.yaml
> ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.2.yaml
> ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.3.yaml
> ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.4.yaml
> ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.5.yaml

These all contain

    images:
    - dockerfile_path: Dockerfile
      from: base
      to: ovn-kubernetes

which I believe gives the name of the image that will be built, which is not changing.

> ci-operator/jobs/infra-periodics.yaml
> hack/validate-owners.sh

These refer to `ci-operator/jobs/openvswitch/ovn-kubernetes`, which is named after the (upstream) repo and thus not changed

> ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master-postsubmits.yaml
> ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master-presubmits.yaml
> ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.1-postsubmits.yaml
> ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.1-presubmits.yaml
> ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.2-postsubmits.yaml
> ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.2-presubmits.yaml
> ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.3-postsubmits.yaml
> ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.3-presubmits.yaml
> ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.4-postsubmits.yaml
> ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.4-presubmits.yaml
> ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.5-postsubmits.yaml
> ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.5-presubmits.yaml

These only refer to `ovn-kubernetes` as part of the repo name: either as the string `openshift/ovn-kubernetes`; or as part of a string like `pull-ci-openshift-ovn-kubernetes-release-4.1-e2e-aws` or `openshift-ovn-kubernetes-release-4.1.yaml` that are derived from the repo name; or via `ci-operator`'s `--repo` arg.

> ci-operator/jobs/openvswitch/ovn-kubernetes/openvswitch-ovn-kubernetes-master-postsubmits.yaml
> ci-operator/jobs/openvswitch/ovn-kubernetes/openvswitch-ovn-kubernetes-master-presubmits.yaml

I don't think these are even used, but they just refer to the (upstream) repo name.

> core-services/image-mirroring/openshift/mapping_origin_4_1
> core-services/image-mirroring/openshift/mapping_origin_4_2
> core-services/image-mirroring/openshift/mapping_origin_4_3

These refer to the image name, which is not changed.

> core-services/prow/02_config/_config.yaml
> core-services/prow/02_config/_plugins.yaml

These refer to the repo name

> ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
> ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
> ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
> ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
> core-services/release-controller/_releases/release-ocp-4.3.json
> core-services/release-controller/_releases/release-ocp-4.4.json

These contain the string `ovn-kubernetes` in master, but not after this PR

/hold cancel

**Comment by stevekuznetsov** [comment]
Ah SGTM, thought the repo was changing names

/lgtm
/approve

**Pull request merged**
