### PR TITLE
stackrox: use latest EKS

### PR DESCRIPTION
**Pull request by gavin-stackrox**
/cc @robbycochran

### CODE REVIEW

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-eks-qa-e2e-tests

**Comment by gavin-stackrox** [comment]
FYI @robbycochran this passes with v1.24 EKS https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/37303/rehearse-37303-pull-ci-stackrox-stackrox-master-eks-qa-e2e-tests/1635797104049786880
I'd lean towards merging this change to update EKS tests from v1.22.

**Comment by robbycochran** [comment]
LGTM: From `eks-qa-e2e-tests ` logs -> `2023-03-15 00:34:28 [ℹ]  using Kubernetes version 1.24`

**Review by robbycochran — APPROVED** [review]

**Pull request merged**
