### PR TITLE
[OCPQE-18123][OCPQE-17973]Fix image pull issues

### PR DESCRIPTION
**Pull request by wewang58**

### CODE REVIEW

**Comment by wewang58** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-azure-ipi-workers-rhel8-f14

**Comment by wewang58** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-baremetal-sno-agent-ipv4-static-connected-f7

**Comment by wewang58** [comment]
/pj-rehearse  periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-vsphere-8-upi-f14

**Comment by wewang58** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-azure-ipi-workers-rhel8-f14

**Comment by wewang58** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-azure-ipi-disk-encryption-set-fips-regen-cert-f14

**Comment by wewang58** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-azure-ipi-minimal-permission-f28

**Comment by wewang58** [comment]
@jianzhangbjz  @jianlinliu  Could you help to review it too, thanks

**Comment by jianlinliu** [comment]
I will leave that to @jianzhangbjz to double confirm, from my opinion, if we always need `update_global_auth` and `create_icsp_connected`, I even think they deserve a dedicated step.

**Comment by wewang58** [comment]
@jianzhangbjz  Could you help to review it, thanks

**Pull request merged**
