### PR TITLE
Update Distributed Tracing interop jobs for RHOSDT 3.1 release

### PR DESCRIPTION
**Pull request by IshwarKanse**
RHOSDT 3.1 is released on Feb 26th, this PR updates the Distributed Tracing interop jobs to use the commit from the upstream repository which has compatible test cases for the release.

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.15-lp-interop-tempo-interop-aws

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.15-lp-interop-opentelemetry-interop-aws

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.15-lp-interop-opentelemetry-interop-aws

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.15-lp-interop-jaeger-interop-aws

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.15-lp-interop-jaeger-interop-aws

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.15-lp-interop-jaeger-interop-aws

**Comment by Sau1506mya** [comment]
Hey @IshwarKanse , Can we have ocp4.16 run as well in your PR before merging it?
Since we now moving forward with ocp4.16, thoughts?

**Comment by IshwarKanse** [comment]
@Sau1506mya I will add OCP 4.16 for all the operators in a different PR. We need to get this merged before the next interop periodic run.

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.16-lp-interop-opentelemetry-interop-aws periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.16-lp-interop-jaeger-interop-aws periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.16-lp-interop-tempo-interop-aws

**Pull request merged**
