### PR TITLE
fix account-roles issue

### PR DESCRIPTION
**Pull request by yasun1**
[OCPQE-17766](https://issues.redhat.com//browse/OCPQE-17766)

### CODE REVIEW

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-aws-rosa-sts-f7 periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-stable-aws-rosa-sts-hypershift-guest-integration-full-f7

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-aws-load-balancer-operator-main-e2e-aws-rosa-operator

**Comment by yuwang-RH** [comment]
@yasun1 `rosa create account-roles` without setting '--hosted-cp' or '--classic' will create set bundles of account-roles for hosted-cp and classic STS cluster. Just confirm with you if you want to use the classic account-roles for both hosted-cp and classic sts cluster creation? if no, it should get account-roles based on the cluster type.

**Pull request merged**
