### PR TITLE
ci-operator/jobs/openshift/machine-api-operator: add e2e-azure-operator

### PR DESCRIPTION
**Pull request by frobware**
machine-api-operator now with optional `e2e-azure-operator`
- Updated machine-api-operator jobs
- run generator
- make `e2e-azure-operator` optional

### CODE REVIEW

**Comment by ingvagabund** [comment]
/lgtm
/hold

Waiting until the rehersal job goes green (just a formality though still...). Feel free to unhold the PR anytime.

**Comment by frobware** [comment]
Hoping https://github.com/openshift/cluster-api-actuator-pkg/pull/108 will shed some light on the occasional flakiness. 

/retest

**Comment by frobware** [comment]
> Waiting until the rehersal job goes green (just a formality though still...). Feel free to unhold the PR anytime.

I made `e2e-azure-operator` optional until we fix the flaky "node drain" test.

**Pull request merged**
