### PR TITLE
CNF-10016: Mark ran latency performance as informing jobs

### PR DESCRIPTION
**Pull request by fontivan**
[CNF-10016](https://issues.redhat.com//browse/CNF-10016): Mark ran latency performance as informing jobs for 4.14, 4.15, and 4.16

- Cyclictest and Oslat latency is considered for a PASS/FAIL grade based on internal criteria
- Also updated test job names so that they did not contain duplicate information and were more helpful in general

### CODE REVIEW

**Comment by bradmwilliams** [comment]
@fontivan From the root of your `openshift/release` repo, you'll need to run a `make release-controllers`.  That should clear the failing test.

**Comment by fontivan** [comment]
@bradmwilliams I did that, but I think its upset with me because I renamed the jobs I had created to remove the redundant information. I think to make it happy I'll need to do this in 2 PRs then, one to rename and one to add informing?

**Comment by deepsm007** [comment]
@fontivan Execute `make update` which will update all the jobs and then run `make release-controllers`

**Comment by bradmwilliams** [comment]
You're adding jobs to a location that our automation knows nothing about.  You'll need to add your path here:
https://github.com/openshift/release/blob/79909095eb1b55c5ab62c9429ce18fa8f28509a4/hack/validate-release-jobs.py#L15-L23

**Comment by bradmwilliams** [comment]
You can reproduce/test the failure by running:
`$ ./hack/validate-release-jobs.py -r .`

**Comment by fontivan** [comment]
@bradmwilliams  @deepsm007  is there any way to configure rehearsals for performance metric based jobs? E.g. I'd like to be able to properly run rehearsals, but I know it will fail since its a performance based test and the results were already below threshold over the weekend

**Comment by bradmwilliams** [comment]
> @bradmwilliams @deepsm007 is there any way to configure rehearsals for performance metric based jobs? E.g. I'd like to be able to properly run rehearsals, but I know it will fail since its a performance based test and the results were already below threshold over the weekend

I'm pretty sure I cannot answer that question.  I'm not even sure what a `performance metric based job` would be.
AFAIK, a rehearsal is just a job that runs the specified workflow (`telco5g-kpi-results`).  If it returns a 0 then the job is successful.  If not, then it's a failure.  Any special handling of those failures would have to be written into the workflow.

**Pull request merged**
