### PR TITLE
Include Azure Disk CSI Certification tests

### PR DESCRIPTION
**Pull request by huffmanca**
Includes the CSI Certification tests for the Azure Disk CSI Driver Operator.

### CODE REVIEW

**Comment by jsafrane** [comment]
I can see some CSI certification tests passed, the workflow works as expected.
/lgtm

**Comment by huffmanca** [comment]
@abhinavdahiya,

Tagging you to approve this PR. It's been reviewed by the storage team and confirmed by them. I can also confirm that it installed the Azure Disk CSI Operator and necessary components.

**Pull request merged**
