### PR TITLE
Sync Serverless CI config/eventing.yaml: Support for 1.10

### PR DESCRIPTION
**Pull request by matzew**
Third PR for Eventing 1.10 CI support

Following up after:
* https://github.com/openshift-knative/hack/pull/50
* https://github.com/openshift-knative/eventing/pull/219

/hold

### CODE REVIEW

**Comment by matzew** [comment]
/assign @pierDipi 
/assign @creydr 

Added a hold to wait for the referenced eventing PR to be merged

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Review by creydr — APPROVED** [review]
/lgtm

**Pull request merged**
