### PR TITLE
Add openshift/assisted-test-infra system-test-olm periodic job

### PR DESCRIPTION
**Pull request by YuviGold**
/cc @osherdp

### CODE REVIEW

**Comment by osherdp** [comment]
The ipv6 will probably fail for now
Are you OK with this?

**Comment by YuviGold** [comment]
/hold
@osherdp why would it fail?

**Comment by osherdp** [comment]
We need to use OPENSHIFT_VERSION=4.8 and we need to update the 4.8 version we use to a newer fc version

**Comment by osherdp** [comment]
Let's push this instead:
https://github.com/openshift/release/pull/17970
And wait for the version upgrade

**Comment by YuviGold** [comment]
Fix rehearsals to run with nightly on #18291
/retest

**Comment by YuviGold** [comment]
@pkliczewski  @jakub-dzon 
Any idea why CNV fails? Were requirements changed? 
```
        "status_info": "Host cannot be installed due to following failing validation(s): Require at least 8 CPU cores for master role, found only 4",
```

could it be related to this bug? https://bugzilla.redhat.com/show_bug.cgi?id=1954477

**Comment by YuviGold** [comment]
The error happens because the dynamic resources feature depends on `env_variables`.
The test is providing the `olm_operator` as a parameter to `ClusterConfig` which doesn't affect the `nodes` configuration ATM.
I tried some workarounds but it can't be solved easily and generically.

This will work once @eliorerz will merge https://github.com/openshift/assisted-test-infra/pull/746 .
For now, I'd like to merge this PR so we will be able to follow OLM integration better.

/unhold

**Pull request merged**
