### PR TITLE
Create arm64 images for oadp-non-admin

### PR DESCRIPTION
**Pull request by shubham-pampattiwar**
Fixes: https://github.com/migtools/oadp-non-admin/issues/74

### CODE REVIEW

**Comment by kaovilai** [comment]
So it appears the images FROM are being replaced here hence no arm64 platform for the final stage.

**Comment by shubham-pampattiwar** [comment]
pj-rehearse

**Review by mateusoliveira43 — APPROVED** [review]
/lgtm

**Review by kaovilai — APPROVED** [review]

**Pull request merged**
