### PR TITLE
update upi-installer dockerfile and base image

### PR DESCRIPTION
**Pull request by jinyunma**
Change the upi-installer base image to rhel8.

### CODE REVIEW

**Comment by jinyunma** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-aws-ovn-upi

**Comment by jinyunma** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-gcp-ovn-upi

**Comment by jinyunma** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-vsphere-upi-zones

**Comment by jinyunma** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-azure-ovn-upi

**Comment by r4f4** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-azure-ovn-upi

**Comment by r4f4** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-gcp-ovn-upi pull-ci-openshift-installer-master-e2e-aws-ovn pull-ci-openshift-installer-master-e2e-aws-ovn-shared-vpc pull-ci-openshift-installer-master-e2e-azure-ovn pull-ci-openshift-installer-master-e2e-gcp-ovn pull-ci-openshift-installer-master-e2e-gcp-ovn-shared-vpc

**Comment by r4f4** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-ibmcloud-ovn

**Comment by jinyunma** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-ibmcloud-ovn

**Comment by jinyunma** [comment]
cc @jianlinliu @gpei for review and visibility

**Comment by jinyunma** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-vsphere-upi-zones

**Comment by jinyunma** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-vsphere-upi-zones

**Comment by r4f4** [comment]
It looks like the `xz` binary is missing somewhere: 
```
/bin/sh: xz: command not found
tar: /tmp/secret/terraform_state.tar.xz: Wrote only 4096 of 10240 bytes
tar: Child returned status 127
tar: Error is not recoverable: exiting now 
```

**Comment by r4f4** [comment]
> It looks like the `xz` binary is missing somewhere:
> 
> ```
> /bin/sh: xz: command not found
> tar: /tmp/secret/terraform_state.tar.xz: Wrote only 4096 of 10240 bytes
> tar: Child returned status 127
> tar: Error is not recoverable: exiting now 
> ```

Seems to be coming from https://github.com/openshift/release/blob/master/ci-operator/step-registry/upi/install/vsphere/upi-install-vsphere-commands.sh#L185 which uses the `upi-installer` as a base https://github.com/openshift/release/blob/master/ci-operator/step-registry/upi/install/vsphere/upi-install-vsphere-ref.yaml#L3

**Comment by r4f4** [comment]
> > Seems to be coming from https://github.com/openshift/release/blob/master/ci-operator/step-registry/upi/install/vsphere/upi-install-vsphere-commands.sh#L185 which uses the `upi-installer` as a base https://github.com/openshift/release/blob/master/ci-operator/step-registry/upi/install/vsphere/upi-install-vsphere-ref.yaml#L3
> 
> yes, I did an online debugging, and indeed `xz` binary is missing in container with rhel8-based upi-installer image, but exists using rhel7-based upi-installer image.

Nice work!

> maybe we need to install package `xz` in [Dockerfile.upi.ci.rhel8](https://github.com/openshift/installer/blob/master/images/installer/Dockerfile.upi.ci.rhel8#LL27C2)?

Yes, I think so. https://github.com/openshift/installer/pull/7238

**Comment by r4f4** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-vsphere-upi-zones

**Comment by r4f4** [comment]
e2e-azurestack: 
```
INFO[2023-06-10T14:23:26Z] Logs for container test in pod e2e-azurestack-ipi-conf-azurestack-creds: 
INFO[2023-06-10T14:23:26Z] /bin/bash: line 27: yq: command not found 
```
So we need to either https://github.com/openshift/installer/blob/master/images/installer/Dockerfile.upi.ci#L65 or we update the `ipi-conf-azurestack-creds` step to use `yq-go`.

**Comment by jinyunma** [comment]
> e2e-azurestack:
> 
> ```
> INFO[2023-06-10T14:23:26Z] Logs for container test in pod e2e-azurestack-ipi-conf-azurestack-creds: 
> INFO[2023-06-10T14:23:26Z] /bin/bash: line 27: yq: command not found 
> ```
> 
> So we need to either https://github.com/openshift/installer/blob/master/images/installer/Dockerfile.upi.ci#L65 or we update the `ipi-conf-azurestack-creds` step to use `yq-go`.

I searched the steps using upi-installer images, seems that only two azure-stack steps call `yq`, so change yq to yq-go in those steps in PR https://github.com/openshift/release/pull/40246

**Comment by jinyunma** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.14-e2e-azurestack

**Comment by jianlinliu** [comment]
@r4f4 one question, once this PR get merged, we need to backport to all supported old version, right?

**Comment by r4f4** [comment]
> @r4f4 one question, once this PR get merged, we need to backport to all supported old versions, right?

@jianlinliu Yes, starting with the Installer fixes to the container image.

**Review by r4f4 — COMMENTED** [review]
/approve

**Pull request merged**
