### PR TITLE
MSI: add GCP OSD installation

### PR DESCRIPTION
**Pull request by rnetser**

### CODE REVIEW

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-cluster-install-uninstall-cluster-install-uninstall-hypershift-4-13-candidate-rand-name

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-cluster-install-uninstall-cluster-install-uninstall-gcp-osd-4-13-stable

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-cluster-install-uninstall-cluster-install-uninstall-gcp-osd-4-13-stable

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-cluster-install-uninstall-cluster-install-uninstall-gcp-osd-4-13-stable

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-cluster-install-uninstall-cluster-install-uninstall-hypershift-4-13-candidate-rand-name

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-cluster-install-uninstall-cluster-install-uninstall-gcp-osd-4-13-stable

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-cluster-install-uninstall-cluster-install-uninstall-hypershift-4-13-candidate-rand-name

**Review by myakove — APPROVED** [review]

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Review by myakove — APPROVED** [review]

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Review by myakove — APPROVED** [review]

**Comment by myakove** [comment]
@JacobTanenbaum can you please review, we need approve from someone from [ci-operator/jobs/openshift/ovn-kubernetes/OWNERS](https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/ovn-kubernetes/OWNERS)

Thanks

**Pull request merged**
