### PR TITLE
Move octavia and openstack-ansibleee prow jobs over from 4.14 to 4.15 Hive cluster

### PR DESCRIPTION
**Pull request by bshewale**

### CODE REVIEW

**Comment by lewisdenny** [comment]
#/pj-rehearse pull-ci-openstack-k8s-operators-openstack-ansibleee-operator-main-ansibleee-operator-build-deploy-kuttl

**Comment by bshewale** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-ansibleee-operator-main-ansibleee-operator-build-deploy-kuttl

**Review by lewisdenny — APPROVED** [review]
/unhold

**Pull request merged**
