### PR TITLE
Hypershift ops: Apply all manifests

### PR DESCRIPTION
**Pull request by alvaroaleman**
Needed for https://github.com/openshift/hypershift-ops/pull/6
/cc @ironcladlou @sjenning @csrwng

### CODE REVIEW

**Comment by ironcladlou** [comment]
Hm, did you mean to use apply the hypershift-ops path? There is no manifests dir

**Comment by alvaroaleman** [comment]
@ironcladlou there is in openshift/hypershift-ops#6 which won't merge until this is merged

**Pull request merged**
