### PR TITLE
installer: remove altinfra periodics config

### PR DESCRIPTION
**Pull request by r4f4**
These configs were added so we could test CAPI because it required a different way to build the installer binary. Now that CAPI is part of the standard installer image, we don't need them anymore.

### CODE REVIEW

**Comment by r4f4** [comment]
/cc @hamzy 
To check the PowerVS config changes (I updated the versions to match the config).

**Comment by r4f4** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-gcp-capi-ovn pull-ci-openshift-installer-master-e2e-powervs-capi-ovn

**Comment by hamzy** [comment]
Initially looks good.  Hopefully we have enough leases for everything...

**Comment by r4f4** [comment]
> Initially looks good. Hopefully we have enough leases for everything...

@hamzy What do you mean? The job is still only triggered manually. The only difference is that triggering it will be `/test e2e-powervs-capi-ovn` instead of `/test altinfra-e2e-powervs-capi-ovn`.

**Comment by hamzy** [comment]
Ah, manual trigger is fine :)

**Comment by r4f4** [comment]
Update: fixed a c&p mistake when moving the jobs from the __altinfra config.

**Comment by r4f4** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-gcp-capi-ovn

**Review by barbacbd — COMMENTED** [review]
/lgtm

do we need to migrate over the jobs that are here or leave that to each point of contact for that work? I know that gcp has an open PR for this.

**Comment by r4f4** [comment]
> do we need to migrate over the jobs that are here or leave that to each point of contact for that work? I know that gcp has an open PR for this.

I migrated the jobs from the altinfra variant to the non-variant configs. The only job I have not migrated is the powervs periodic. The other periodics are now covered by existing periodics from platforms using capi by default.

**Comment by r4f4** [comment]
Update: dropped all changes except the removal of the altinfra periodics.

@hamzy the `powervs-capi-ovn` periodic will have to be moved to the standard periodics location. Can you do that?

**Comment by hamzy** [comment]
> Update: dropped all changes except the removal of the altinfra periodics.
> 
> @hamzy the `powervs-capi-ovn` periodic will have to be moved to the standard periodics location. Can you do that?

https://github.com/openshift/release/pull/53060

**Comment by r4f4** [comment]
Update: rebased to fix merge conflicts.

**Comment by r4f4** [comment]
Update: rebased to fix merge conflicts.

**Pull request merged**
