### PR TITLE
release-controller: Add RHEL 8.4 beta repos

### PR DESCRIPTION
**Pull request by travier**
Temporarily add RHEL 8.4 Beta repos for RHCOS 4.8. This will be removed once RHEL 8.4 is GA.

### CODE REVIEW

**Review by miabbott — APPROVED** [review]
Looks sane to me.

**Review by bradmwilliams — APPROVED** [review]
/lgtm

**Comment by travier** [comment]
I've just realized that I added a '.' in the repo name and we use that here: https://github.com/openshift/os/pull/527/files#diff-c3bb730c96a569528e0f02113620061bd9058085cf7578c2c373d5c0574dd220R20

So this probably won't work?

**Comment by miabbott** [comment]
> I've just realized that I added a '.' in the repo name and we use that here: https://github.com/openshift/os/pull/527/files#diff-c3bb730c96a569528e0f02113620061bd9058085cf7578c2c373d5c0574dd220R20
> 
> So this probably won't work?

Might be right...the format in the repo seems to be `ocp-X.Y-{name-split-by-dashes}.repo`

**Pull request merged**
