### PR TITLE
RHTAP-985: Upgrade RHTAP clusters to OCP 4.13

### PR DESCRIPTION
**Pull request by flacatus**

### CODE REVIEW

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-hac-e2e-tests
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-10u-10t
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-hac-e2e-tests

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-hac-e2e-tests

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests

**Comment by flacatus** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests-periodic

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests

**Comment by pmacik** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-basic periodic-ci-redhat-appstudio-e2e-tests-main-load-test-ci-daily-10u-10t

**Comment by flacatus** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-basic periodic-ci-redhat-appstudio-e2e-tests-main-load-test-ci-daily-10u-10t

**Comment by flacatus** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests-periodic pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests  pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-hac-e2e-tests

**Comment by pmacik** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-basic periodic-ci-redhat-appstudio-e2e-tests-main-load-test-ci-daily-10u-10t

**Pull request closed without merging**
