### PR TITLE
OSSM-3815 update maistra workflow with hypershift chain

### PR DESCRIPTION
**Pull request by yxun**
This PR updates 
1. workflow servicemesh-istio-e2e-profile  with hypershift provisioning
2. cluster version from 4.10 to 4.12 in maistra istio jobs
3. update istio-operator jobs and fix artifacts issue in building and pushing operator image jobs

### CODE REVIEW

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-integ-pilot-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.3-integ-pilot-2-3

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.3-integ-pilot-2-3

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.3-integ-servicemesh-multicluster-2-3

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.3-integ-servicemesh-2-3

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-3.0-maistra-istio-unit-3-0

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.3-integ-servicemesh-2-3

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.3-integ-servicemesh-multicluster-2-3

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-3.0-maistra-istio-unit-3-0

**Comment by jwendell** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-integ-servicemesh-2-4

**Review by jwendell — APPROVED** [review]

**Pull request merged**
