### PR TITLE
Add upgrade test for vsphere-ipi-proxy cluster

### PR DESCRIPTION
**Pull request by shellyyang1989**
I'm adding the test to see if upgrade on disconnected but proxy enabled clusters works.

### CODE REVIEW

**Comment by jhou1** [comment]
Thank you @shellyyang1989 .

@liangxia Do you think this should go to the openshift-tests-private dir to execute in private deck?

**Comment by liangxia** [comment]
> Thank you @shellyyang1989 .
> 
> @liangxia Do you think this should go to the openshift-tests-private dir to execute in private deck?

I'm OK to keep them either in verification-tests folder or openshift-tests-private folder, as all of the upgrade scenarios codes are in verification-tests, which is public, and it works in either folder.
But I have heard from several of the team members that testgrid is very helpful for finding/debugging failures. Perhaps that's the reason upgrade jobs are still added/adding into verification-tests.

**Comment by jhou1** [comment]
OK, thanks. I'm asking this because in upgrade-pipeline we are also executing Ginkgo scenarios, so these jobs will eventually be moved to openshift-tests-private if we are going to run Gingko upgrade tests.

@Xia-Zhao-rh what do you think?

**Comment by jhou1** [comment]
Merging this, we can follow up the discussion elsewhere.

/lgtm

**Comment by liangxia** [comment]
> OK, thanks. I'm asking this because in upgrade-pipeline we are also executing Ginkgo scenarios, so these jobs will eventually be moved to openshift-tests-private if we are going to run Gingko upgrade tests.
> 
> @Xia-Zhao-rh what do you think?

@jhou1  I didn't found the upgrade steps for ginkgo in Prow. So there is no integrated upgrade tests there.

@Xia-Zhao-rh @kuiwang02 @jianzhangbjz  Could you confirm whether the upgrade step for ginkgo exist in Prow or not, and add a link there if possible ?  Thanks.

**Comment by Xia-Zhao-rh** [comment]
@jhou1 @liangxia Now, the upgrade step for ginkgo doesn't exist in Prow now.

**Comment by jianzhangbjz** [comment]
Yes, there are no ginkgo upgrade steps in Prow. @jhou1 @liangxia Could you help migrate the `workflow: cucushift-upgrade` to the Ginkgo repo? After that, we can inject the ginkgo upgrade steps into it. Thanks very much!

**Comment by kuiwang02** [comment]
> Yes, there are no ginkgo upgrade steps in Prow. @jhou1 @liangxia Could you help migrate the `workflow: cucushift-upgrade` to the Ginkgo repo? After that, we can inject the ginkgo upgrade steps into it. Thanks very much!

actually move the test of the yaml to openshift-tests-private repo, like cucushift test moving to tests-private repo.

**Comment by liangxia** [comment]
I think the proper procedure is that,
1. Implement ginkgo upgrade in Prow.
2. Integrate upgrade for ginkgo and cucushift.
3. Migrate the upgrade jobs to openshift-tests-private folder one by one to use the integrated upgrade.

Definitely we can do item 3 ahead of item 1. But if we do like that, when we implement item 1, we may need several iterate/push to optimize the steps (this is quite common when writing new steps). Then each iterate will trigger all the upgrade jobs, which is really resources/time consuming.

Also currently we are able to use testgrid/sippy for those jobs in verification-tests which is really helpful for finding/debugging test failures. We'd like to keep the ability before item 1 is implemented.

**Comment by jianzhangbjz** [comment]
Yes, I understood. But, as you know, the upgrading test steps are the same, no matter ginko or cucushift. If we do item 3 first, we don't need to implement item 1 actually.
> But if we do like that, when we implement item 1, we may need several iterate/push to optimize the steps (this is quite common when writing new steps). 

We can migrate the upgrade wokflow and one test profile, and then inject the Ginkgo upgrade test cases, and then migrate other test profiles.

> Also currently we are able to use testgrid/sippy for those jobs in verification-tests which is really helpful for finding/debugging test failures. We'd like to keep the ability before item 1 is implemented.

Geting the private log is on going. Or we can preserve those upgrade workflow in  verification-tests repo first.

**Pull request merged**
