### PR TITLE
Kubevirt-on-BM-0827

### PR DESCRIPTION
**Pull request by jechen0648**

### CODE REVIEW

**Comment by jechen0648** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-baremetalds-conformance

**Comment by jechen0648** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-baremetalds-conformance

**Comment by jechen0648** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-baremetalds-conformance

**Comment by jechen0648** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-baremetalds-conformance

**Comment by qinqon** [comment]
@jechen0648 Do you know if we can have a dual stack extra job like this one ? also do you know if we can test https://github.com/openshift/origin/pull/27980 there ?

**Comment by jechen0648** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-baremetalds-conformance

**Comment by jechen0648** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-baremetalds-conformance

**Comment by qinqon** [comment]
@jechen0648  can we have another job for master branch ?

**Comment by LiangquanLi930** [comment]
> @jechen0648 Do you know if we can have a dual stack extra job like this one ? also do you know if we can test [openshift/origin#27980](https://github.com/openshift/origin/pull/27980) there ?

AFAIK, Currently we do not have a ci job for dual stack

**Comment by jechen0648** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-baremetalds-conformance

**Comment by jechen0648** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-baremetalds-conformance

**Pull request closed without merging**
