### PR TITLE
NO-ISSUE: Change the image used for conformance tests to openshift-tests-415

### PR DESCRIPTION
**Pull request by danmanor**
Change the image used for conformance tests to openshift-tests-415

### CODE REVIEW

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-image-service-master-edge-e2e-metal-assisted

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-master-edge-e2e-metal-assisted

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-agent-master-edge-e2e-metal-assisted

**Review by gamli75 — APPROVED** [review]

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-master-edge-e2e-metal-assisted pull-ci-openshift-assisted-installer-agent-master-edge-e2e-metal-assisted

**Comment by danmanor** [comment]
pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted pull-ci-openshift-assisted-image-service-master-edge-e2e-metal-assisted

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-image-service-master-edge-e2e-metal-assisted

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted pull-ci-openshift-assisted-image-service-main-edge-e2e-metal-assisted

**Review by gamli75 — APPROVED** [review]

**Pull request merged**
