### PR TITLE
TRT-1592: Update to promtail v2.9.4 to match server

### PR DESCRIPTION
**Pull request by dgoodwin**

### CODE REVIEW

**Comment by dgoodwin** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.16-upgrade-from-stable-4.15-e2e-gcp-ovn-rt-upgrade

**Comment by dgoodwin** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.16-e2e-aws-ovn

**Comment by dgoodwin** [comment]
This PR did not fix the log muddling but #49281 will. However we should still update promtail to match the server version and use the newer RPMs Periklis has been publishing for us and thought were in use.

**Comment by dgoodwin** [comment]
/pj-rehearse ci/rehearse/periodic-ci-openshift-release-master-ci-4.16-e2e-aws-ovn

**Comment by dgoodwin** [comment]
ci/rehearse/periodic-ci-openshift-release-master-ci-4.15-e2e-aws-ovn

**Comment by dgoodwin** [comment]
/pj-rehearse ci/rehearse/periodic-ci-openshift-release-master-ci-4.15-e2e-aws-ovn

**Comment by DennisPeriquet** [comment]
/retitle TRT-1592: Update to promtail v2.9.4 to match server

**Pull request merged**
