### PR TITLE
Migrate to app.ci: periodic-image-mirroring-knative

### PR DESCRIPTION
**Pull request by hongkailiu**
https://issues.redhat.com/browse/DPTP-1654

### CODE REVIEW

**Comment by hongkailiu** [comment]
/hold

Wait for https://github.com/openshift/ci-tools/pull/1418

**Review by alvaroaleman — APPROVED** [review]

**Comment by hongkailiu** [comment]
Some error:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-image-mirroring-knative/1328436150708211712

Seem RBAC diff on api.ci and app.ci.
Debugging...

**Comment by hongkailiu** [comment]
Fixed by https://github.com/openshift/release/pull/13659
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-image-mirroring-knative/1328442000952791040

**Pull request merged**
