### PR TITLE
test 64k-pagesize kernel type on arm bm

### PR DESCRIPTION
**Pull request by lwan-wanglin**
Adding a profile for basic arm 64k-pagesize kernel type on multiarch baremetal upi cluster to run e2e on it

### CODE REVIEW

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-arm64-nightly-baremetal-upi-ovn-ipv4-f28-day2-64k-pagesize

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-upi-ovn-ipv4-arm-mixarch-f28-day2-64k-pagesize

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-upi-ovn-ipv4-arm-mixarch-f28-day2-64k-pagesize

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-arm64-nightly-baremetal-upi-ovn-ipv4-f28-day2-64k-pagesize

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-upi-ovn-ipv4-arm-mixarch-f28-day2-64k-pagesize

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-upi-ovn-ipv4-arm-mixarch-f14-day2-64k-pagesize

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-upi-ovn-ipv4-arm-mixarch-f14-day2-64k-pagesize

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-upi-ovn-ipv4-arm-mixarch-f14-day2-64k-pagesize

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-upi-ovn-ipv4-arm-mixarch-f14-day2-64k-pagesize

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-upi-ovn-ipv4-arm-mixarch-f14-day2-64k-pagesize

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-upi-ovn-ipv4-arm-mixarch-f14-day2-64k-pagesize

**Comment by lwan-wanglin** [comment]
@aleskandro @rioliu-rh Both the installation part and kerneltype steps passed, could you help to review?thanks!

**Comment by rioliu-rh** [comment]
LGTM

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-upi-ovn-ipv4-arm-mixarch-f14-day2-64k-pagesize

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-upi-ovn-ipv4-arm-mixarch-f14-day2-64k-pagesize

**Comment by aleskandro** [comment]
the configuration now looks good to me. I'll leave it with no tag for further debugging the failure (that seems still related to keys missing from the vault)

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-upi-ovn-ipv4-arm-mixarch-f14-day2-64k-pagesize

**Comment by lwan-wanglin** [comment]
> the configuration now looks good to me. I'll leave it with no tag for further debugging the failure (that seems still related to keys missing from the vault)

I am not sure why it happened, I have readded openshift-qe publickey to bastion host, and the keys in vault is correct. I just rebuilt the job and the issue is gone.

**Comment by lwan-wanglin** [comment]
the e2e finished.
/pj-rehearse ack

**Comment by lwan-wanglin** [comment]
@aleskandro could you help add lgtm? thanks

**Comment by lwan-wanglin** [comment]
CC @liangxia to review, thanks!

**Pull request merged**
