### PR TITLE
openstack: Replace ccm-install with techpreview

### PR DESCRIPTION
**Pull request by pierreprinetti**
The workflow `openshift-e2e-openstack-ccm-install` is now a duplicate of
`openshift-e2e-openstack-techpreview`. This patch removes `ccm-install`
and replaces calls to it with `techpreview`.

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
/lgtm
/approve

**Comment by mandre** [comment]
Interesting that ci-operator-config job failed to validate configs in the openshift-priv directory, I thought we were instructed to leave them out of our patches.

**Comment by pierreprinetti** [comment]
The alternative would be to just replace the calls from `config`, then wait for automation to replace `priv`, then open a new PR for removing the workflow. Let's see how this one goes, and if it blocks, then I'll do that.

**Review by mandre — COMMENTED** [review]
/lgtm

**Pull request merged**
