### PR TITLE
Add job to run e2e tests of kubernetes-nmstate

### PR DESCRIPTION
**Pull request by creydr**
This PR adds jobs to run the e2e tests of [kubernetes-nmstate](https://github.com/openshift/kubernetes-nmstate) on bare metal with OpenshiftSDN.

**notes for reviewers**
didn't include tests on OVN, as the test setup failed here. Will try to figure out whats wrong for OVN and open another PR for it. So this one is "OpenshiftSDN-only".

### CODE REVIEW

**Comment by cybertron** [comment]
/lgtm

Looks like the job passed. I think we're probably waiting on an update to use https://github.com/openshift/kubernetes-nmstate/pull/246 but otherwise this looks ready to go.

**Comment by creydr** [comment]
@cybertron: You lgtm'd it once, but I removed the ssh-ci part, as openshift/kubernetes-nmstate#246 is now in place. Could you recheck on this please?

**Comment by cybertron** [comment]
/lgtm

\o/

**Pull request merged**
