### PR TITLE
capi-agent-provider: add linter

### PR DESCRIPTION
**Pull request by rccrdpccl**

### CODE REVIEW

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-lint

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-lint

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-lint

**Review by adriengentil — APPROVED** [review]

**Pull request merged**
