### PR TITLE
Integrate e2e (golang+cucushift) for azure-ipi-workers-rhel8

### PR DESCRIPTION
**Pull request by liangxia**

### CODE REVIEW

**Comment by liangxia** [comment]
Installation failure due to https://bugzilla.redhat.com/show_bug.cgi?id=2089153

**Comment by liangxia** [comment]
/cc @kuiwang02 @jianzhangbjz @jhou1 @JianLi-RH @dis016 @pruan-rht 

We've gone through the workflow, and it works fine.
The high failures are caused by disk pressure on the nodes, which is tracked in https://coreos.slack.com/archives/CPJQCSN49/p1653983113810879

**Comment by jianzhangbjz** [comment]
> The high failures are caused by disk pressure on the nodes, which is tracked in https://coreos.slack.com/archives/CPJQCSN49/p1653983113810879

@jinyunma Could you help link your fixed PR here? Thanks!

**Comment by liangxia** [comment]
> > The high failures are caused by disk pressure on the nodes, which is tracked in https://coreos.slack.com/archives/CPJQCSN49/p1653983113810879
> 
> @jinyunma Could you help link your fixed PR here? Thanks!

The PR is https://github.com/openshift/release/pull/29017 , which is merged earlier today.

**Pull request merged**
