### PR TITLE
Use ACM clusterpool instead of aws cluster profiles

### PR DESCRIPTION
**Pull request by zhujian7**

### CODE REVIEW

**Comment by zhujian7** [comment]
/pj-rehearse pull-ci-stolostron-multicloud-operators-foundation-backplane-2.4-e2e
/pj-rehearse pull-ci-stolostron-multicloud-operators-foundation-main-e2e

**Comment by zhujian7** [comment]
/pj-rehearse pull-ci-stolostron-multicloud-operators-foundation-main-e2e

**Comment by xuezhaojun** [comment]
/lgtm
The cluster-proxy-addon is GA in 2.6

**Pull request merged**
