### PR TITLE
Hypershift: Use latest stable 4.13 release image by default for mgmt clusters

### PR DESCRIPTION
**Pull request by muraee**

### CODE REVIEW

**Comment by enxebre** [comment]
lgtm

**Comment by muraee** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-aws pull-ci-openshift-hypershift-main-e2e-aws-4-13

**Comment by csrwng** [comment]
```
INFO[2023-06-01T15:30:28Z] Logs for container test in pod e2e-aws-create-management-cluster: 
INFO[2023-06-01T15:30:28Z] /bin/bash: line 11: jq: command not found
```

**Review by bryan-cox — APPROVED** [review]
/lgtm

**Comment by sjenning** [comment]
nice!
/lgtm

**Pull request merged**
