### PR TITLE
OCPQE-1289: add cluster health check step

### PR DESCRIPTION
**Pull request by jianlinliu**

### CODE REVIEW

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.13-installer-rehearse-azure

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.13-installer-rehearse-azure

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.13-installer-rehearse-azure

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.13-installer-rehearse-ibmcloud

**Comment by MayXuQQ** [comment]
why the step name add "cucushift-" prefix?

**Comment by jianlinliu** [comment]
> why the step name add "cucushift-" prefix?

The same reason why `cucushift-installer-rehearse-ibmcloud-ipi-private-provision` have "cucushift-" prefix.

**Comment by jianlinliu** [comment]
@shellyyang1989 @liangxia for review.

**Comment by MayXuQQ** [comment]
@jianlinliu when this step failed, will mark 'install:fail" in ReportPortal?

**Comment by jianlinliu** [comment]
> @jianlinliu when this step failed, will mark 'install:fail" in ReportPortal?

No. the step is added as `test`, the test item would be overridden by e2e testing in regular ci testing.

**Review by MayXuQQ — APPROVED** [review]

**Comment by shellyyang1989** [comment]
Refers to [OCPQE-14334](https://issues.redhat.com/browse/OCPQE-14334)

Thank you Jianlin. Per my understanding, if install finishes and exits 0, all the resources should be in the correct state. The question is: should we check if the instant state of the resources correct or not instead of waiting for them to be expected states?

**Comment by jianlinliu** [comment]
> should we check if the instant state of the resources correct or not instead of waiting for them to be expected states?

Can you explain it a bit? Or an example?

**Comment by jianlinliu** [comment]
If you are talking about the moment of `openshift-install` exits 0, ideally yes, but you know, we have many workflows which adding more post-actions after installer completed. We can use this step to guard the cluster is always in a good shape.

**Comment by shellyyang1989** [comment]
> If you are talking about the moment of openshift-install exits 0, ideally yes
Right, it's what I meant.

> we have many workflows which adding more post-actions
ah, that's fine. I didn't notice the post actions.

**Pull request merged**
