### PR TITLE
CCO-367: Deprovision AWS STS OIDC infrastructure after must-gather and IPI deprovision

### PR DESCRIPTION
**Pull request by abutcher**

### CODE REVIEW

**Comment by abutcher** [comment]
/pj-rehearse pull-ci-openshift-cloud-credential-operator-release-4.12-e2e-aws-manual-oidc

**Comment by 2uasimojo** [comment]
/title Deprovision AWS STS OIDC infrastructure after must-gather and IPI deprovision.

**Comment by 2uasimojo** [comment]
/retitle Deprovision AWS STS OIDC infrastructure after must-gather and IPI deprovision.

**Comment by 2uasimojo** [comment]
Part of stabilization in preparation for CCO-367

**Comment by sdodson** [comment]
/retitle CCO-367: Deprovision AWS STS OIDC infrastructure after must-gather and IPI deprovision

**Pull request merged**
