### PR TITLE
NO-ISSUE: Extend usage of assisted upgrade agent test

### PR DESCRIPTION
**Pull request by adriengentil**
* create periodic job for upgrade agent test
* define it as an optional job on assisted-service and
  assisted-installer-agent repos
* renamed `e2e-metal-upgrade-agent` -> `e2e-metal-assisted-upgrade-agent`

### CODE REVIEW

**Comment by adriengentil** [comment]
/cc @jhernand @osherdp 

@jhernand  I defined it on `assisted-service` and `assisted-installer-agent` as optional jobs, does it make sense? Should I define it on other repods (e.g.: `assisted-installer`)?

@osherdp I thought about the `always_run: false` :tada:

**Review by osherdp — APPROVED** [review]

**Pull request merged**
