### PR TITLE
added hadolint check for pipeline-service

### PR DESCRIPTION
**Pull request by xinredhat**
**Changes:**

Added linting tool `hadolint`  for pipeline-service

### CODE REVIEW

**Comment by fgiloux** [comment]
> Added security tool hadolint for pipeline-service

hadolint is a linting tool for Dockerfiles I would argue that it does more on stylistic errors than security

**Comment by xinredhat** [comment]
> > Added security tool hadolint for pipeline-service
> 
> hadolint is a linting tool for Dockerfiles I would argue that it does more on stylistic errors than security

updated the description `Added linting tool hadolint for pipeline-service`

**Review by bnallapeta — APPROVED** [review]
/lgtm

**Pull request merged**
