### PR TITLE
Migrate release periodics running ci-operator directly

### PR DESCRIPTION
**Pull request by hongkailiu**
https://issues.redhat.com/browse/DPTP-2034

```python
#!/usr/bin/env python3

import logging
import yaml
import sys

filename = sys.argv[1]

def migrate(job):
    if job.get("agent", "") != "kubernetes":
        return job
    if job.get("cluster", "") != "api.ci":
        return job
    if job.get('name','') == 'cpaas-cvp-optional-operator-common-tests':
        print("- " + job["name"])
        return job
    for container in job['spec']['containers']:
        if not(container['image'].endswith("ci-operator:latest") and container.get('command', []) == ["ci-operator"]):
            print(job["name"])
    return job

with open(filename) as f:
    all = yaml.load(f, Loader=yaml.FullLoader)
    for t in ("presubmits", "postsubmits"):
        if t not in filename:
            continue
        for repo in all[t]:
            jobs = []
            for job in all[t][repo]:
                jobs.append(migrate(job))
            all[t][repo] = jobs
    if "periodics" in filename:
        jobs = []
        for job in all["periodics"]:
            jobs.append(migrate(job))
        all["periodics"] = jobs
```

and then

```bash
$ find ./ci-operator/jobs/openshift/release  -type f -name "*cs.yaml"  -exec python3 migrate_non_prowgen_jobs.py {} \;
- release-openshift-origin-installer-old-rhcos-e2e-aws-4.7
- release-openshift-origin-installer-e2e-aws-upgrade-4.3-to-4.4-to-4.6-to-4.7-ci
- release-openshift-ocp-osd-gcp-nightly-4.7
- release-openshift-ocp-osd-aws-nightly-4.7
- release-openshift-origin-installer-old-rhcos-e2e-aws-4.8
- release-openshift-origin-installer-e2e-aws-upgrade-4.5-to-4.6-to-4.7-to-4.8-ci
- release-openshift-origin-installer-old-rhcos-e2e-aws-4.6
- release-openshift-origin-installer-e2e-aws-upgrade-4.3-to-4.4-to-4.5-to-4.6-ci
- endurance-cluster-maintenance-aws-4.6
- release-openshift-origin-installer-old-rhcos-e2e-aws-4.4
- release-openshift-origin-installer-e2e-aws-upgrade-4.1-to-4.2-to-4.3-to-4.4-nightly
- release-openshift-origin-installer-old-rhcos-e2e-aws-4.3
- release-openshift-origin-installer-e2e-aws-upgrade-4.1-to-4.2-to-4.3-nightly
- release-openshift-origin-installer-old-rhcos-e2e-aws-4.2
- release-openshift-origin-installer-old-rhcos-e2e-aws-4.5
- release-openshift-origin-installer-e2e-aws-upgrade-4.2-to-4.3-to-4.4-to-4.5-ci
- cpaas-cvp-optional-operator-common-tests
```

/hold

Let me check the secrets, and configMaps 

/cc @petr-muller

### CODE REVIEW

**Review by petr-muller — APPROVED** [review]
YOLO

**Comment by hongkailiu** [comment]
```
cat /tmp/v.txt | grep secret | cut -d' ' -f2 | sort | uniq
aws-openshift-llc-account-credentials
boskos-credentials
ci-pull-credentials
cluster-secrets-aws
cluster-secrets-azure4
cluster-secrets-gcp
cluster-secrets-metal
cluster-secrets-openstack
cluster-secrets-openstack-vexxhost
cluster-secrets-osd-ephemeral
endurance-cluster-credentials-4.6-aws
osde2e-common
osde2e-credentials
registry-pull-credentials
(p3env) ➜  release git:(master) ✗ cat /tmp/v.txt | grep configMap | cut -d' ' -f2 | sort | uniq
cluster-profile-aws-centos-40
cluster-profile-gcp
prow-job-cluster-launch-installer-custom-test-image
prow-job-cluster-launch-installer-e2e
prow-job-cluster-launch-installer-metal-e2e
prow-job-cluster-launch-installer-openstack-e2e
prow-job-cluster-launch-installer-upi-e2e
prow-job-cluster-scaleup-e2e-40
prow-job-endurance-install
prow-job-endurance-test
step-registry
```

```python
#!/usr/bin/env python3

import logging
import yaml
import sys

filename = sys.argv[1]

def migrate(job):
    if job.get("agent", "") != "kubernetes" and job.get("agent", "") != "":
        return job
    if job.get("cluster", "") != "api.ci":
        return job
    if not "volumes" in job['spec']:
        return job
    for volume in job['spec']["volumes"]:
        if 'configMap' in volume:
             logging.warning("configMap: %s", volume['configMap']["name"])
        if 'secret' in volume:   
             logging.warning("secret: %s", volume['secret']["secretName"])
        if 'projected' in volume:   
            for source in volume["projected"]['sources']:
                if 'configMap' in source:
                    logging.warning("configMap: %s", source['configMap']["name"])
                if 'secret' in source:   
                    logging.warning("secret: %s", source['secret']["name"])
    return job

with open(filename) as f:
    all = yaml.load(f, Loader=yaml.FullLoader)
    for t in ("presubmits", "postsubmits"):
        if t not in filename:
            continue
        for repo in all[t]:
            jobs = []
            for job in all[t][repo]:
                jobs.append(migrate(job))
            all[t][repo] = jobs
    if "periodics" in filename:
        jobs = []
        for job in all["periodics"]:
            jobs.append(migrate(job))
        all["periodics"] = jobs


```

**Comment by hongkailiu** [comment]
`endurance-cluster-credentials-4.6-aws`: this one is too special. Will do it with another PR.

**Comment by hongkailiu** [comment]
```bash
rg valueFrom ./ci-operator/jobs/openshift/release -l 
./ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
./ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
```

So no secret or configMap is used as `oc explain pod.spec.containers.env.valueFrom` in the release periodic jobs.

**Review by petr-muller — APPROVED** [review]

**Comment by hongkailiu** [comment]
/hold cancel

Will watch the prow-controller log.

**Pull request merged**
