### PR TITLE
fix issue of RHTAP installer CI deploying installer from main branch

### PR DESCRIPTION
**Pull request by xinredhat**
rh-pre-commit.version: 2.1.0
rh-pre-commit.check-secrets: ENABLED

### CODE REVIEW

**Comment by xinredhat** [comment]
/pj-rehearse pull-ci-redhat-appstudio-rhtap-installer-main-rhtap-installer-yamllint

**Comment by xinredhat** [comment]
/pj-rehearse pull-ci-redhat-appstudio-rhtap-installer-main-rhtap-installer-yamllint

**Comment by xinredhat** [comment]
/pj-rehearse pull-ci-redhat-appstudio-rhtap-installer-main-rhtap-installer-e2e

**Comment by prietyc123** [comment]
yes this should fix the rhtap installer issue but other components issue still won't be fixed. The directory issue which it sets by default for other user to rhtap-installer. Would you like to handle that in different PR?

**Comment by xinredhat** [comment]
> yes this should fix the rhtap installer issue but other components issue still won't be fixed. The directory issue which it sets by default for other user to rhtap-installer. Would you like to handle that in different PR?

I fixed, I didn't find a better way for it

**Pull request merged**
