### PR TITLE
[openstack-k8s-operators][fips-check] Use custom image

### PR DESCRIPTION
**Pull request by karelyatin**
The fips-check job broken currently, until the image with the fix[1] is available, let's use custom image.

Related-Issue: [OSPCIX-338](https://issues.redhat.com//browse/OSPCIX-338)

### CODE REVIEW

**Comment by karelyatin** [comment]
pj-rehearse pull-ci-openstack-k8s-operators-ovn-operator-main-ovn-operator-build-deploy

**Comment by karelyatin** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-ovn-operator-main-ovn-operator-build-deploy

**Comment by karelyatin** [comment]
It works fine with it https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/53414/rehearse-53414-pull-ci-openstack-k8s-operators-ovn-operator-main-ovn-operator-build-deploy/1803370891334127616/artifacts/ovn-operator-build-deploy/openstack-k8s-operators-fips-check/build-log.txt

**Review by bshephar — APPROVED** [review]

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
