### PR TITLE
[CNV] Bump OKD on main to 4.10

### PR DESCRIPTION
**Pull request by orenc1**
Signed-off-by: orenc1 <ocohen@redhat.com>

### CODE REVIEW

**Review by vrutkovs — APPROVED** [review]
/lgtm

**Comment by bparees** [comment]
approving because it sounds like we do not want to be mirroring these images in this way (see: https://coreos.slack.com/archives/C01CQA76KMX/p1652112606709819?thread_ts=1651774688.991529&cid=C01CQA76KMX) but ultimately there is a followup to be done here about whether we should be promoting these images at all, and mirroring them (for any ocp version).  It seems like the current thinking is that we should not.

/approve

**Review by bradmwilliams — APPROVED** [review]

**Pull request merged**
