### PR TITLE
Add labels in jobs

### PR DESCRIPTION
**Pull request by 0xmichalis**
@stevekuznetsov @csrwng ptal

Open to suggestions for a better label.

### CODE REVIEW

**Comment by kargakis** [comment]
We could also do it the other way around and label the old jobs. Assuming most people are going to add pipeline jobs, we wouldn't require from them to add the label in their PRs.

**Comment by stevekuznetsov** [comment]
I'd rather see the labels be explicit in both directions

**Comment by kargakis** [comment]
Updated to include labels for both masters, ptal

**Comment by stevekuznetsov** [comment]
LGTM

**Pull request merged**
