### PR TITLE
publish elastic operator src image for consumption from other test jobs

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton @stevekuznetsov is this a violation of any particular best practices/guidelines?

the elasticsearch operator repo has scripts in it that i need to use from other repo test jobs.

**Comment by smarterclayton** [comment]
Don't do this directly.  Have the repo declare a Dockerfile with a one liner FROM.  Then reference that here as a unique image.  src images don't have the right metadata and don't point to a real target repo.

**Pull request merged**
