### PR TITLE
remove multiple kcp-dev repositories from OpenShift CI

### PR DESCRIPTION
**Pull request by embik**
This is a follow up to #39766 and a discussion at #kcp-dev in Kubernetes Slack, we would like to remove a bigger bulk of repositories in one go. A few repositories are not ready yet for migration to the new KCP Prow instance, so we will revisit migrating it at a later (soon) date.

The repositories removed in this PR are:

- https://github.com/kcp-dev/apiextensions-apiserver
- https://github.com/kcp-dev/apimachinery
- https://github.com/kcp-dev/catalog
- https://github.com/kcp-dev/client-go
- https://github.com/kcp-dev/code-generator
- https://github.com/kcp-dev/controller-runtime-example
- https://github.com/kcp-dev/controller-runtime
- https://github.com/kcp-dev/enhancements
- https://github.com/kcp-dev/helm-charts
- https://github.com/kcp-dev/kubernetes
- https://github.com/kcp-dev/kcp
- https://github.com/kcp-dev/kcp-glbc
- https://github.com/kcp-dev/edge-mc

### CODE REVIEW

**Comment by embik** [comment]
rebased for latest changes, please take another look.

**Review by ncdc — APPROVED** [review]

**Comment by smg247** [comment]
Going to merge https://github.com/openshift/release/pull/40132 instead. This one leaves some remnants that 40132 handles.

**Pull request closed without merging**
