### PR TITLE
add monitoring approver for `cherry-pick-approved` label

### PR DESCRIPTION
**Pull request by Tai-RedHat**
@juzhao Please take a look in case I missed some files

### CODE REVIEW

**Comment by jan--f** [comment]
For monitoring work I don't think the console is needed. But you might work in their stuff separately :) That will need a lgtm from a console owner.
For the rest
/lgtm

**Comment by Tai-RedHat** [comment]
@yapei @jhadvig @spadgett please help to review the console part, thanks!

**Review by jhadvig — APPROVED** [review]
/lgtm

**Pull request merged**
