### PR TITLE
add testing of openshift-ovn-kubernetes plugin on vsphere for openshift-ovn-kubernetes and cno repos

### PR DESCRIPTION
**Pull request by JacobTanenbaum**
add testing for the ovn-kubernetes plug-in on vsphere. Since no CI testing has been done on this in the past make it optional

### CODE REVIEW

**Comment by JacobTanenbaum** [comment]
@danwinship @pecameron PTAL this is a run of CI tests on vsphere with ovn-kubernetes

**Comment by dcbw** [comment]
@JacobTanenbaum can you enable the test for CNO as well? Once that's done I'll lgtm/approve.

**Comment by dcbw** [comment]
`Waiter ResourceRecordSetsChanged failed: Rate exceeded`
/retest

**Comment by dcbw** [comment]
```

Error downloading packages:
  PyYAML-3.10-11.el7.x86_64: [Errno 256] No more mirrors to try.
  containernetworking-plugins-0.8.3-2.el7.x86_64: [Errno 256] No more mirrors to try.
  firewalld-filesystem-0.6.3-8.el7_8.1.noarch: [Errno 256] No more mirrors to try.
```
/retest

**Comment by JacobTanenbaum** [comment]
CNO test 
`Waiter ResourceRecordSetsChanged failed: Rate exceeded`
/retest

**Comment by wking** [comment]
step portion of this seems fairly straightforward

/lgtm

**Pull request merged**
