### PR TITLE
chore(RHDIP-460): add search-catalog scenario

### PR DESCRIPTION
**Pull request by pmacik**

### CODE REVIEW

**Comment by pmacik** [comment]
/pr-rehearse pull-ci-redhat-performance-backstage-performance-main-baseline-pr

**Comment by pmacik** [comment]
/pr-rehearse pull-ci-redhat-performance-backstage-performance-main-list-catalog

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-list-catalog

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-list-catalog-empty pull-ci-redhat-performance-backstage-performance-main-list-catalog

**Review by yogananth-subramanian — APPROVED** [review]
/lgtm

**Pull request merged**
