### PR TITLE
NO-ISSUE: use ansible profile_tasks plugin

### PR DESCRIPTION
**Pull request by adriengentil**
profile_tasks plugin will show the duration for each task.

### CODE REVIEW

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-agent-master-edge-e2e-metal-assisted

**Review by osherdp — APPROVED** [review]

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-agent-master-edge-e2e-metal-assisted

**Pull request merged**
