### PR TITLE
rename azure-techpreview-serial to azure-sdn-techpreview-serial

### PR DESCRIPTION
**Pull request by jluhrsen**
- applies to 4.12 only
- this also adds the openshift-e2e-azure-sdn-techpreviewserial
workflow which explicitly configures OpenShiftSDN as the CNI.
This is a noop until OpenShiftSDN is no longer the default
CNI, but eventually the plan is for OVNKubernetes to be
the default at which point this explicit configuration
will be needed.

Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>

### CODE REVIEW

**Comment by dgoodwin** [comment]
/lgtm

But there are conflicts.

**Comment by jluhrsen** [comment]
@dgoodwin , rebase done

**Pull request merged**
