### PR TITLE
Enable Network Selection in ROSA

### PR DESCRIPTION
**Pull request by krishvoor**
This PR will allow users to choose between OpenshiftSDN/ OVNKubernetes, always defaults to OVNKubernetes

### CODE REVIEW

**Comment by krishvoor** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.13-nightly-x86-perfscale-rosa-multiaz-control-plane-3nodes

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-nightly-x86-perfscale-rosa-multiaz-control-plane-24nodes-periodic

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.12-nightly-x86-perfscale-rosa-multiaz-control-plane-24nodes-periodic

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-perfscale-rosa-multiaz-control-plane-24nodes-periodic

**Comment by krishvoor** [comment]
The recent failure is not related to the PR in itself, but due to a Known bug, tracked via https://issues.redhat.com/browse/OCM-4433

**Comment by krishvoor** [comment]
Since the PR is now merged, running the rehearse

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-perfscale-rosa-multiaz-control-plane-24nodes-periodic

**Comment by krishvoor** [comment]
The job here [4.15 CP Job](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/44633/rehearse-44633-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-perfscale-rosa-multiaz-control-plane-24nodes-periodic/1716496722110189568/artifacts/perfscale-rosa-multiaz-control-plane-24nodes-periodic/rosa-cluster-provision/build-log.txt) has passed with required changes to it.

**Comment by krishvoor** [comment]
@svetsa-rh - I have updated my commit, this is  now good to merge

**Comment by krishvoor** [comment]
> /hold
@svetsa-rh do you have any feedback for this?

**Comment by svetsa-rh** [comment]
> The job here [4.15 CP Job](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/44633/rehearse-44633-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-perfscale-rosa-multiaz-control-plane-24nodes-periodic/1716496722110189568/artifacts/perfscale-rosa-multiaz-control-plane-24nodes-periodic/rosa-cluster-provision/build-log.txt) has passed while passing OpenShiftSDN as network type.
> 
> From the scope of this PR, I'll revert 4.15 CP Job to normal

Harsha, from the log I see that it is an OVN cluster while it looks like you were expecting to test SDN.

**Comment by svetsa-rh** [comment]
Also, my suggestion is to add a new test(s) to this same PR to add SDN so it's easy to rehearse than reverting changes.

**Comment by jtaleric** [comment]
```jtaleric at polaris in ~/code/rosa on master $ ./rosa create cluster --help | grep network
      --no-proxy strings                                    A comma-separated list of destination domain names, domains, IP addresses or other network CIDRs to exclude proxying.
      --private-link                                        Provides private connectivity between VPCs, AWS services, and your on-premises networks, without exposing your traffic to the public internet.
jtaleric at polaris in ~/code/rosa on master $ ./rosa version
1.2.29
I: Your ROSA CLI is up to date.
``` 

I am not sure `--network-type` is valid? 

ah, further investigation https://github.com/openshift/rosa/blob/master/cmd/create/cluster/cmd.go#L540-L547 

https://github.com/openshift/rosa/blob/master/pkg/ocm/clusters.go#L45

Maybe this is a bug against ROSA cli?

**Comment by krishvoor** [comment]
> ```
>       --no-proxy strings                                    A comma-separated list of destination domain names, domains, IP addresses or other network CIDRs to exclude proxying.
>       --private-link                                        Provides private connectivity between VPCs, AWS services, and your on-premises networks, without exposing your traffic to the public internet.
> jtaleric at polaris in ~/code/rosa on master $ ./rosa version
> 1.2.29
> I: Your ROSA CLI is up to date.
> ```
> 
> I am not sure `--network-type` is valid?
> 
> ah, further investigation https://github.com/openshift/rosa/blob/master/cmd/create/cluster/cmd.go#L540-L547
> 
> https://github.com/openshift/rosa/blob/master/pkg/ocm/clusters.go#L45
> 

More information in this [doc](https://docs.google.com/document/d/14SZXFgiuSusKOdkrG0Eq5suWG3t-ehgTXN_BT058nmY/edit) 

> Maybe this is a bug against ROSA cli?

Looks like this will not be a supported option from 4.15 GA onwards, so the code changes might be for the same.

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.12-nightly-x86-perfscale-rosa-multiaz-control-plane-24nodes-periodic

**Comment by krishvoor** [comment]
> Maybe this is a bug against ROSA cli?
> > /pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.12-nightly-x86-perfscale-rosa-multiaz-control-plane-24nodes-periodic

I suspect this `--network-type` capability is stripped away in the latest rosa-cli code,
we will have to resort to a way where this can be tested against a desired/older rosa-cli binary.

**Comment by krishvoor** [comment]
Based on conversation, we will be switching to Self-Managed AWS and make use of this option:
https://github.com/openshift/release/blob/master/ci-operator/step-registry/sdn/conf/sdn-conf-ref.yaml

**Pull request closed without merging**
