### PR TITLE
Generated release gating jobs

### PR DESCRIPTION
**Pull request by danilo-gemoli**

### CODE REVIEW

**Comment by jmguzik** [comment]
Create 4.12 release job ci-operator configurations.
PR is splitted into 3 changes:
- `openshift-release-master__ci-4.12.yaml deleted` -> to delete previously created config (and just recreate it using new method/tool)
- `{okd,nightly,ci}*4.12*.yaml created and bumped `-> actual work
- `make jobs`

/label tide/merge-method-squash
/cc @deads2k @bradmwilliams @wking @stbenjam @dgoodwin @xueqzhan @DennisPeriquet

Previous work for reference: https://github.com/openshift/release/pull/25490

**Comment by danilo-gemoli** [comment]
RPM repo configurations have already been populated in this PR [#27829](https://github.com/openshift/release/pull/27829/commits) by the following commits:

- [8696222609731b85b0be40f59685c6495065978b](https://github.com/openshift/release/pull/27829/commits/8696222609731b85b0be40f59685c6495065978b) - repos copied from 4.11
- [c04634224b01478b29f39d9760a4f7a596575ff2](https://github.com/openshift/release/pull/27829/commits/c04634224b01478b29f39d9760a4f7a596575ff2) - versions bumped

**Review by jmguzik — APPROVED** [review]

**Pull request merged**
