### PR TITLE
hypershift: rename images for OCP payload inclusion

### PR DESCRIPTION
**Pull request by ironcladlou**
This commit makes a pretty major change to how the images are named:

1. The `hypershift` image (built from the root Dockerfile) is now
   `hypershift-operator`.
2. The `hypershift-control-plane-operator` image (built from
   Dockerfile.control-plane) is now `hypershift` and is promoted.

This is because the `hypershift` image promoted to OCP should be just the
control plane components to match all the ART build stuff we already set up for
that purpose. Consider the `hypershift` image "the HyperShift component of OCP".
The `hypershift-operator` image will be the all-in-one that contains everything
else not included in the OCP payload and versioned independently of OCP (e.g.
the hypershift-operator, CLI, etc.).

### CODE REVIEW

**Review by alvaroaleman — APPROVED** [review]
/hold
I think this is correct but wanna see the rehearsal passing first

**Comment by ironcladlou** [comment]
Let's hold until tomorrow so I have plenty of time to deal with any fallout

**Pull request closed without merging**
