### PR TITLE
Sync 4.7 release jobs with 4.6

### PR DESCRIPTION
**Pull request by jsafrane**
Propagate all changes done during 4.6 development/testing to 4.7 release jobs.
cc @bparees @deads2k

### CODE REVIEW

**Comment by bparees** [comment]
@bradmwilliams i'm told you might own this process (updating the blocking/informing jobs for a new release)

/assign @bradmwilliams

**Comment by bradmwilliams** [comment]
/hold 
We had discussed these changes, in our arch call earlier this week, and it was decided that we would wait until early next week to make changes since all focus is on getting 4.6 out-the-door.

**Pull request merged**
