### PR TITLE
Add presubmits tests for Knative Eventing Hyperfoil repository 

### PR DESCRIPTION
**Pull request by pierDipi**
Add presubmit tests for https://github.com/openshift-knative/eventing-hyperfoil-benchmark

### CODE REVIEW

**Comment by matzew** [comment]
Put the `OWNERS` file to https://github.com/openshift/release/tree/450ce377609a5dffc0aab4bdb3b75172f7036867/ci-operator/jobs/openshift-knative/eventing-hyperfoil-benchmark  as well

**Comment by matzew** [comment]
Oh, `prow` has some `OWNERS` job too :taco: :tada:

**Comment by pierDipi** [comment]
I will fix the job failure on the actual branch.

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
