### PR TITLE
Serving performance tests

### PR DESCRIPTION
**Pull request by skonto**
- Similar to https://github.com/openshift/release/pull/43710
- Runs tests against the  `max_supported-1` OCP version, according to the comment [here](https://github.com/openshift/release/pull/43710#issuecomment-1790761096). This way we don't block regular runs, we will have to automate in openshift-knative/hack (auto-generate the perf jobs).

### CODE REVIEW

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-release-next-413-images

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-release-v1.11-413-images

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-release-v1.12-413-images

**Comment by skonto** [comment]
/pj-rehearse  pull-ci-openshift-knative-serving-release-v1.11-413-perf-test-e2e-aws-ocp-413

**Comment by ReToCode** [comment]
👍  looks good. Probably also want to OCP 4.14 as in https://github.com/openshift/release/pull/45220

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

/hold feel free to unhold when you are ready for this to be merged

**Comment by skonto** [comment]
closing in favor of #45397

**Pull request closed without merging**
