### PR TITLE
USHIFT-1937: Add presubmit scenario testing on arm

### PR DESCRIPTION
**Pull request by pacevedom**

### CODE REVIEW

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-metal-tests-arm

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-metal-periodic-test-arm pull-ci-openshift-microshift-main-microshift-metal-tests-arm

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-metal-periodic-test-arm pull-ci-openshift-microshift-main-microshift-metal-tests-arm

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-metal-tests-arm pull-ci-openshift-microshift-main-metal-periodic-test-arm

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-metal-tests-arm

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-metal-tests-arm

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-metal-tests-arm

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-metal-tests-arm

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-metal-periodic-test-arm

**Comment by dhellmann** [comment]
/lgtm
/hold

This looks OK to me. I didn't want to merge it when you weren't around, so I left a hold. Feel free to remove that when you're ready.

**Pull request merged**
