### PR TITLE
prepare MicroShift CI configs for org transfer

### PR DESCRIPTION
**Pull request by copejon**
This is essentially a very large string replacement in file paths and contents: `s/redhat-et/openshift`.

### CODE REVIEW

**Comment by sallyom** [comment]
/assign @wking 

Thanks!

**Review by wking — APPROVED** [review]
`ci-operator/step-registry/openshift` changes look like they're mostly mechanical renames, and if we missed something there, MicroShift approvers will have the power to fix it later, so:

/lgtm

**Comment by copejon** [comment]
@wking Correct, it's strictly an org transfer.  And thanks for the lgtm!

**Comment by ggiguash** [comment]
USHIFT-12

**Pull request merged**
