### PR TITLE
[OSPk8s] update infra-operator config

### PR DESCRIPTION
**Pull request by stuggi**

### CODE REVIEW

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-infra-operator-master-infra-operator-build-deploy

lets try again, it seems that OCP cluster on vexx died in the middle of the process [1][2]
[1] https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/39048/rehearse-39048-pull-ci-openstack-k8s-operators-infra-operator-master-infra-operator-build-deploy/1654466692668985344/artifacts/infra-operator-build-deploy/openstack-k8s-operators-build/build-log.txt
[2] https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/39048/rehearse-39048-pull-ci-openstack-k8s-operators-infra-operator-master-infra-operator-build-deploy/1654466692668985344/artifacts/infra-operator-build-deploy/openstack-k8s-operators-gather/build-log.txt

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-infra-operator-master-infra-operator-build-deploy

now with repositories created in https://quay.rdoproject.org/organization/openstack-k8s-operators

**Comment by stuggi** [comment]
@viroel infra-operator uses `apis` instead of `api`, this might be the issue now?
```
go: errors parsing go.mod:
493
/alabama/openstack-operator/go.mod:101: replace github.com/openstack-k8s-operators/infra-operator/api: version "v0.0.0-20230427061808-1c6403dc94b9" invalid: missing github.com/openstack-k8s-operators/infra-operator/api/go.mod at revision 1c6403dc94b9
```

**Comment by viroel** [comment]
> @viroel infra-operator uses `apis` instead of `api`, this might be the issue now?
> 
> ```
> go: errors parsing go.mod:
> 493
> /alabama/openstack-operator/go.mod:101: replace github.com/openstack-k8s-operators/infra-operator/api: version "v0.0.0-20230427061808-1c6403dc94b9" invalid: missing github.com/openstack-k8s-operators/infra-operator/api/go.mod at revision 1c6403dc94b9
> ```

yes. `api` is hardcoded in build step[1]. It is possible to 1) modify the script to detect `api` vs `apis` or 2) update infra-operator to use `api`

[1] https://github.com/openshift/release/blob/master/ci-operator/step-registry/openstack-k8s-operators/build/openstack-k8s-operators-build-commands.sh#L166-L171

**Review by viroel — APPROVED** [review]

**Pull request merged**
