### PR TITLE
tnozicka/openshift-acme: Auto-update ci-operator-tnozicka-openshift-acme ConfigMap when ci-operator config is changed

### PR DESCRIPTION
**Pull request by tnozicka**
Addressing https://github.com/openshift/release/pull/1467#issuecomment-421003526

/cc @bbguimaraes @stevekuznetsov

### CODE REVIEW

**Comment by tnozicka** [comment]
@stevekuznetsov @bbguimaraes That still didn't help. I could appreciate some guidance here.
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/tnozicka_openshift-acme/79/pull-ci-openshift-acme-e2e/10

**Comment by stevekuznetsov** [comment]
This is a symptom of a bad design -- we have a card to fix it. https://jira.coreos.com/browse/DPTP-141

**Comment by tnozicka** [comment]
Thanks that have moved it forward.

fwiw using a postsubmit to update a config map is also being edge driven, not level driven.

**Pull request merged**
