### PR TITLE
MGMT-16623: Change jobs that use OPENSHIFT_VERSION=4.14 as latest to 4.15

### PR DESCRIPTION
**Pull request by danmanor**

### CODE REVIEW

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-installer-master-edge-e2e-metal-assisted-odf
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted-mce-sno

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted-mce-sno

**Review by gamli75 — APPROVED** [review]

**Comment by danmanor** [comment]
I had to rebase, can you legitimate again please @gamli75 ?

**Review by gamli75 — APPROVED** [review]

**Pull request merged**
