### PR TITLE
Sync Serverless CI

### PR DESCRIPTION
**Pull request by serverless-qe**
Sync Serverless CI using openshift-knative/hack.

### CODE REVIEW

**Comment by mgencur** [comment]
Hmm. Needs rebase. Re-running the action in https://github.com/openshift-knative/hack/actions/runs/8060870509

**Review by creydr — APPROVED** [review]
/lgtm
/approve

**Comment by ReToCode** [comment]
> PR needs rebase.

come one :D @creydr @pierDipi fine with merging this without passing the last two tests? I'll re-trigger the generation.

**Comment by creydr** [comment]
> > PR needs rebase.
> 
> come one :D @creydr @pierDipi fine with merging this without passing the last two tests? I'll re-trigger the generation.

I am fine :+1:

**Comment by creydr** [comment]
I retriggered the generation (https://github.com/openshift-knative/hack/actions/runs/8064767726)

**Pull request merged**
