### PR TITLE
add disconnected install profile and remove proxy setting for fully private cluster

### PR DESCRIPTION
**Pull request by jianlinliu**
1. remove proxy setting for fully private cluster
2. adding disconnected cluster install via mirror registry

### CODE REVIEW

**Comment by jianlinliu** [comment]
@yufchang @Amoghrd pls help review

**Comment by Amoghrd** [comment]
So azure fully private behind proxy template is not required?

**Comment by jianlinliu** [comment]
> So azure fully private behind proxy template is not required?

I did not see proxy is required based on NAT Gateway is already created for the vnet. And the passed test result also proved that too.

**Comment by yunjiang29** [comment]
@jianlinliu  two workflows (`cucushift-installer-rehearse-azure-ipi-fullyprivate` and `cucushift-installer-rehearse-azure-ipi-disconnected`) were added, is it right? but looks like only disconnected workflow had been tested.

**Comment by jianlinliu** [comment]
> @jianlinliu two workflows (`cucushift-installer-rehearse-azure-ipi-fullyprivate` and `cucushift-installer-rehearse-azure-ipi-disconnected`) were added, is it right? but looks like only disconnected workflow had been tested.

`cucushift-installer-rehearse-azure-ipi-fullyprivate` is updated from the original `cucushift-installer-rehearse-azure-ipi-proxy-fullyprivate`, `cucushift-installer-rehearse-azure-ipi-disconnected` is the one newly added. 

Before adding `cucushift-installer-rehearse-azure-ipi-disconnected`, I already tested `cucushift-installer-rehearse-azure-ipi-fullyprivate`, but maybe the history is not shown in the above comments, Maybe this one - https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/27904/rehearse-27904-periodic-ci-openshift-verification-tests-master-installer-rehearse-installer-rehearse-azure/1515887378642767872/build-log.txt

**Pull request merged**
