### PR TITLE
no-jira: updating the feature gate name to be consistent with other vsphere feature gates

### PR DESCRIPTION
**Pull request by rvanderp3**
Updated the feature gate name to be consistent with other vSphere feature gates

### CODE REVIEW

**Comment by r4f4** [comment]
@rvanderp3 has the PR to update the gate name in the installer already merged? Or are you getting this in first?

**Comment by rvanderp3** [comment]
> @rvanderp3 has the PR to update the gate name in the installer already merged? Or are you getting this in first?

Hi @r4f4, I'm updating this first so I can perform payload testing with the feature gate.  see: https://github.com/openshift/api/pull/2002/files#diff-a8b6135d50534471326ea7bcd20e0f5eae25353f7788338060f718128a6a0b34R613-R619

**Review by r4f4 — COMMENTED** [review]
/approve

**Review by vrutkovs — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
