### PR TITLE
W/A for CRI-O permissions issue writing to block devices

### PR DESCRIPTION
**Pull request by orenc1**
This is a temporary workaround intended to address the issue observed in CNV and described at https://issues.redhat.com/browse/CNV-31504 in which CDI can't import PVC with volume mode of `Block`.

### CODE REVIEW

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-conformance

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-conformance

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-conformance

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-conformance

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-conformance

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-conformance

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn

**Review by davidvossel — APPROVED** [review]
/lgtm

**Pull request merged**
