### PR TITLE
MGMT-7105: add AI vsphere platform CI

### PR DESCRIPTION
**Pull request by michaellevy101**

### CODE REVIEW

**Comment by michaellevy101** [comment]
do not review please - in progress

**Comment by lranjbar** [comment]
@michaellevy101 

To retest a new job or new changes to a job here in `openshift/release` you can use:

/test pj-rehearse

Because this is vsphere the following is also useful:

/test vsphere-dry

**Comment by michaellevy101** [comment]
> /test pj-rehearse

Thanks Lisa:)

**Pull request closed without merging**
