### PR TITLE
CoreOS: use coreos namespace and coreos-builder SA

### PR DESCRIPTION
**Pull request by darkmuggle**

### CODE REVIEW

**Comment by darkmuggle** [comment]
TBH, I have no idea if this will work...AFAIK after reading the docs, and reading the code, this seems like the way to use our namespace.

/cc @cgwalters @miabbott

**Comment by cgwalters** [comment]
I think one thing that would really help me a lot is some sort of diagram of the proposed flow between Prow and gangplank.

As I understand it, Prow runs in the app.ci cluster and will then create a namespace in the "target cluster" (for us, build02) with a randomly generated namespace, etc.  In this proposal, is Gangplank code always running in the target cluster, or would it run on app.ci in this proposal?

There are multiple `coreos` namespaces, mirrored on each CI cluster.  

Would it be most accurate to say that the goal here is that gangplank is like a custom DSL/logic that is taking over the role of https://docs.ci.openshift.org/docs/architecture/step-registry/ for some of our CI?

**Comment by cgwalters** [comment]
I guess to rephrase this, the simplest thing to me as a starting point seems to be something like using cosa as the `build_root`; then AIUI Prow will capture the input git along with that, and gangplank then can create further pods in the target CI namespace as it sees fit (assuming the target pod has sufficient privileges to create more pod - if not I think we can get that enhanced).

**Comment by darkmuggle** [comment]
> I guess to rephrase this, the simplest thing to me as a starting point seems to be something like using cosa as the `build_root`; then AIUI Prow will capture the input git along with that, and gangplank then can create further pods in the target CI namespace as it sees fit (assuming the target pod has sufficient privileges to create more pod - if not I think we can get that enhanced).

https://github.com/openshift/release/pull/17533 is the result of this, but there's push back.  I'll figure something out...maybe

**Pull request closed without merging**
