### PR TITLE
[WIP] Enable oc adm upgrade status testing

### PR DESCRIPTION
**Pull request by JianLi-RH**
Hi @evakhoni  @shellyyang1989 Let's start one job which enabled the upgrade status command, if it can help us on verifying the new command, let's added more jobs.

I am using a stable-stable profile for the first job is because we don't run e2e test in stable-stable, so there is less noise than e2e jobs.

### CODE REVIEW

**Comment by JianLi-RH** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-stable-4.16-upgrade-from-stable-4.15-gcp-ipi-proxy-private-f7

**Comment by JianLi-RH** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-stable-4.16-upgrade-from-stable-4.15-gcp-ipi-proxy-private-f7

**Comment by evakhoni** [comment]
hmm, I see that you dedicated a separate schedule for running this one, but we may want to run it on as many different scenarios as we can, imo worth having it part of every run, not limited to 4 times a months as with current cron schedule

**Comment by evakhoni** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-stable-4.16-upgrade-from-stable-4.15-gcp-ipi-proxy-private-f7

**Comment by evakhoni** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-stable-4.16-upgrade-from-stable-4.15-gcp-ipi-proxy-private-f7

**Comment by evakhoni** [comment]
@JianLi-RH so I'm about to get #51046 merged, can we close this one?

**Pull request closed without merging**
