### PR TITLE
Adding azure arm

### PR DESCRIPTION
**Pull request by paigerube14**
Azure ovn arm installer with infra/workload changes

https://issues.redhat.com/browse/PERFSCALE-2744

### CODE REVIEW

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-azure-4.16-nightly-arm-control-plane-3nodes-arm

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-azure-4.16-nightly-arm-control-plane-3nodes-arm

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-azure-4.16-nightly-arm-control-plane-3nodes-arm

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-azure-4.16-nightly-arm-control-plane-3nodes-arm

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-azure-4.16-nightly-arm-control-plane-3nodes-arm

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-azure-4.16-nightly-arm-control-plane-3nodes-arm

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-azure-4.16-nightly-arm-control-plane-3nodes-arm

**Comment by paigerube14** [comment]
@qiliRedHat @svetsa-rh PTAL, passing job: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/50391/rehearse-50391-pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-azure-4.16-nightly-arm-control-plane-3nodes-arm/1774963100768800768

**Review by shahsahil264 — APPROVED** [review]
/lgtm

**Pull request merged**
