### PR TITLE
Set pre-commit job to required on manila-operator

### PR DESCRIPTION
**Pull request by viroel**

### CODE REVIEW

**Comment by viroel** [comment]
/pj-rehease pull-ci-openstack-k8s-operators-manila-operator-main-precommit-check

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-manila-operator-main-precommit-check

typo in previous comment :)

**Review by gouthampacha — APPROVED** [review]
/lgtm

Thanks @viroel

**Review by fmount — APPROVED** [review]
Thanks @viroel !

**Pull request merged**
