### PR TITLE
set security policy for aws,gcp,azure

### PR DESCRIPTION
**Pull request by liqcui**
This is part of cluster-post-config Jenkinfile, omitted in add-infra-workload script.
https://github.com/openshift-qe/ocp-qe-perfscale-ci/blob/cluster-post-config/Jenkinsfile#L161 for cluster-post-config

Adding security rule/policy for aws,gcp and azure for pbench tcp,udp hostnetwork tests, etc

### CODE REVIEW

**Comment by liqcui** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-ocp-qe-perfscale-node-density-heavy-gcp

**Comment by liqcui** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-ocp-qe-perfscale-node-density-heavy-gcp

**Comment by liqcui** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-ocp-qe-perfscale-ci-tests

**Comment by paigerube14** [comment]
@liqcui I'm not 100% sure what value code is actually used during our normal tests. Think we need to verify this is adding value

**Comment by liqcui** [comment]
> @liqcui I'm not 100% sure what value code is actually used during our normal tests. Think we need to verify this is adding value

Ok, No Problem, I should double check with you and Qiujie before starting this task :)

**Comment by svetsa-rh** [comment]
@liqcui I agree with @paigerube14. Is there a particular jira/task or anything we do in Jenkins driving this?

**Comment by paigerube14** [comment]
> @liqcui I agree with @paigerube14. Is there a particular jira/task or anything we do in Jenkins driving this?

https://github.com/openshift-qe/ocp-qe-perfscale-ci/blob/18fe3d3192eaa8e49bd9868031fa48e8e908b9c1/Jenkinsfile#L160

This section is in jenkins but i havent added to it for new clouds and I'm not sure what its doing anything

**Comment by liqcui** [comment]
> > @liqcui I agree with @paigerube14. Is there a particular jira/task or anything we do in Jenkins driving this?
> 
> https://github.com/openshift-qe/ocp-qe-perfscale-ci/blob/18fe3d3192eaa8e49bd9868031fa48e8e908b9c1/Jenkinsfile#L160
> 
> This section is in jenkins but i havent added to it for new clouds and I'm not sure what its doing anything
We can hold on the PR until we met with any issue for network testing or something that related with pbench agent

**Pull request closed without merging**
