### PR TITLE
Configure heart to love our merge robot

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/cc @kargakis this should get `heart` working finally

### CODE REVIEW

**Comment by kargakis** [comment]
You also need to enable it in the plugins config file

**Comment by stevekuznetsov** [comment]
Ah, cool

**Comment by kargakis** [comment]
Btw, I haven't updated prow yet to the latest version. Will get to it tomorrow if you haven't in the meantime.

**Comment by stevekuznetsov** [comment]
You can, I'm about to go

**Pull request merged**
