### PR TITLE
Bump AMQ Streams operator to version 2.7.0-3

### PR DESCRIPTION
**Pull request by Frawless**

### CODE REVIEW

**Comment by im-konge** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.16-lp-rosa-classic-amq-streams-2-7-rosa-aws periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.14-lp-interop-amq-streams-2-7 periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.15-lp-interop-amq-streams-2-7 periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.14-lp-rosa-classic-amq-streams-2-7-rosa-aws periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.16-lp-interop-amq-streams-2-7 periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.17-lp-interop-amq-streams-2-7

**Comment by Sau1506mya** [comment]
@im-konge , Only latest jobs need to be run in each platform. No need to run all versions. Older version jobs can be terminated, its a waste of resouces.

**Comment by im-konge** [comment]
@Sau1506mya yeah well, in previous PRs all of the jobs mentioned in the table had to be successful in order to merge the PR. If it's not required, I guess you can terminate it and for the older OCP versions on which the product doesn't need to be tested, we can just remove those files or?

**Comment by Sau1506mya** [comment]
> @Sau1506mya yeah well, in previous PRs all of the jobs mentioned in the table had to be successful in order to merge the PR. If it's not required, I guess you can terminate it and for the older OCP versions on which the product doesn't need to be tested, we can just remove those files or?

It need not be run all the mentioned jobs in the PR, only that you require will be sufficient and after that run`/pj-rehearse ack` to add the `rehearsal-ack` label in the PR to get it merged.
Don't remove the files as for now because z-stream testing effort is in progress , so that will be used there.

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.14-lp-interop-amq-streams-2-7 abort

**Comment by Frawless** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.16-lp-rosa-classic-amq-streams-2-7-rosa-aws

**Pull request merged**
