### PR TITLE
Pipelines - expand rosa-hypershift testing to OCP 4.12

### PR DESCRIPTION
**Pull request by ascerra**

### CODE REVIEW

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-rhpit-interop-tests-main-openshift-pipelines-hypershift-4.12-lp-rosa-hypershift-openshift-pipelines-rosa-hypershift-412

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-rhpit-interop-tests-main-openshift-pipelines-hypershift-4.12-lp-rosa-hypershift-openshift-pipelines-rosa-hypershift-412

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
