### PR TITLE
Add dptp members to `core-services/image-mirroring/openshift/OWNERS`

### PR DESCRIPTION
**Pull request by danilo-gemoli**
As per title.

### CODE REVIEW

**Review by Prucek — APPROVED** [review]

**Comment by smg247** [comment]
I think the entire point of the no-parent-owners config is to keep us from approving these PRs. This may no longer be desired, but if we want this, we may as well just remove that line.

**Comment by danilo-gemoli** [comment]
If we allow parents and add someone other than `dptp` in one of these:
- `core-services/image-mirroring/OWNERS`
- `core-services/OWNERS`  

wouldn't he be allowed to approve PRs in `core-services/image-mirroring/openshift/*` too?

**Comment by smg247** [comment]
> If we allow parents and add someone other than `dptp` in one of these:
> 
> * `core-services/image-mirroring/OWNERS`
> * `core-services/OWNERS`
> 
> wouldn't he be allowed to approve PRs in `core-services/image-mirroring/openshift/*` too?

Yes, but I don't see any reason why we would do that. If we did do that, it would make sense that they would also have rights in `core-services/image-mirroring/openshift`.

**Comment by danilo-gemoli** [comment]
updated

**Comment by smg247** [comment]
Now there is no reason to add `dptp` at all because we are already root level approvers.

**Pull request merged**
