### PR TITLE
USHIFT-1935: Move AWS instances to us-west-2

### PR DESCRIPTION
**Pull request by pacevedom**

### CODE REVIEW

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.14-microshift-metal-tests pull-ci-openshift-microshift-main-metal-periodic-test pull-ci-openshift-microshift-main-ocp-conformance-rhel-eus pull-ci-openshift-microshift-main-microshift-metal-cache-arm

**Comment by ggiguash** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.14-microshift-metal-tests pull-ci-openshift-microshift-main-metal-periodic-test pull-ci-openshift-microshift-main-ocp-conformance-rhel-eus pull-ci-openshift-microshift-main-microshift-metal-cache-arm

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-ocp-conformance-rhel-eus pull-ci-openshift-microshift-main-metal-periodic-test

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.14-microshift-metal-tests pull-ci-openshift-microshift-main-metal-periodic-test pull-ci-openshift-microshift-main-ocp-conformance-rhel-eus pull-ci-openshift-microshift-main-microshift-metal-cache-arm

**Comment by pmtk** [comment]
/hold
Can we also change the AMIs for clusterbot? https://github.com/openshift/release/blob/master/ci-operator/step-registry/openshift/microshift/clusterbot/openshift-microshift-clusterbot-commands.sh

**Comment by pacevedom** [comment]
> /hold Can we also change the AMIs for clusterbot? https://github.com/openshift/release/blob/master/ci-operator/step-registry/openshift/microshift/clusterbot/openshift-microshift-clusterbot-commands.sh

Coming in the next commit. Will wait until current rehearsals are done.

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-metal-periodic-test pull-ci-openshift-microshift-release-4.14-microshift-metal-tests

**Pull request merged**
