### PR TITLE
HOSTEDCP-1313: Add hypershift e2e to machine approver

### PR DESCRIPTION
**Pull request by enxebre**

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
/lgtm
/approve

**Comment by JoelSpeed** [comment]
/pj-rehearse pull-ci-openshift-cluster-machine-approver-master-e2e-hypershift

**Comment by enxebre** [comment]
/pj-rehearse pull-ci-openshift-cluster-machine-approver-master-e2e-hypershift

**Comment by enxebre** [comment]
/pj-rehearse pull-ci-openshift-cluster-machine-approver-master-e2e-hypershift

**Comment by enxebre** [comment]
/pj-rehearse pull-ci-openshift-cluster-machine-approver-master-e2e-hypershift

**Comment by JoelSpeed** [comment]
/pj-rehearse pull-ci-openshift-cluster-machine-approver-master-e2e-hypershift

**Pull request closed without merging**
