### PR TITLE
ci-operator/templates/openshift/installer: Shared subnets for new regions

### PR DESCRIPTION
**Pull request by wking**
Catching up with b7179335a3 (#6833), add shares subnets for the new regions.  This is basically as described in 424a04ac2d (#5550), although I've dropped the `--stack-policy-body` mentioned in that commit message (I dunno what it was about, since the commit message didn't give it the argument that `--stack-policy-body` expects).  Generated using:

```console
$ export AWS_PROFILE=ci  # or whatever you call it locally
$ git fetch origin
$ date --iso=m --utc
2020-01-23T20:41+0000
$ git checkout origin/release-4.3
$ git --no-pager log --oneline -1
2055609f9 (HEAD, origin/release-4.3) Merge pull request #2928 from ashcrow/4.3-signed-rhcos-bump
```

with:

```sh
for REGION in us-east-1 us-west-1 us-west-2
do
  COUNT=3
  if test us-west-1 = "${REGION}"
  then
    COUNT=2
  fi
  for INDEX in 1 2 3 4
  do
    NAME="do-not-delete-shared-vpc-${INDEX}"
    aws --region "${REGION}" cloudformation create-stack --stack-name "${NAME}" --template-body "$(cat upi/aws/cloudformation/01_vpc.yaml)" --parameters "ParameterKey=AvailabilityZoneCount,ParameterValue=${COUNT}" >/dev/null
    aws --region "${REGION}" cloudformation wait stack-create-complete --stack-name "${NAME}"
    SUBNETS="$(aws --region "${REGION}" cloudformation describe-stacks --stack-name "${NAME}" | jq -c '[.Stacks[].Outputs[] | select(.OutputKey | endswith("SubnetIds")).OutputValue | split(",")[]]' | sed "s/\"/'/g")"
    echo "${REGION}_$((INDEX - 1))) subnets=\"${SUBNETS}\";;"
  done
done
```

which spits out:

```
us-east-2_0) subnets="['subnet-0faf6d16c378ee7a7','subnet-0e104572db1b7d092','subnet-014ca96c04f36adec','subnet-0ea06057dceadfe8e','subnet-0689efe5e1f9f4212','subnet-0d36bb8edbcb3d916']";;
us-east-2_1) subnets="['subnet-085787cc4b80b84b2','subnet-09dfbf66e8f6e5b50','subnet-0db5d90ff3087444e','subnet-047f15f2a0210fbe0','subnet-0bf13f041c4233849','subnet-0e2a5320549e289d8']";;
...
```

The `COUNT` bit for `us-west-1` is because our CI account only has access to two zones there:

```console
$ aws --region us-west-1 ec2 describe-availability-zones --output text
AVAILABILITYZONES		 us-west-1					available												usw1-az3 us-west-1a
AVAILABILITYZONES		 us-west-1					available												usw1-az1 us-west-1b
```

### CODE REVIEW

**Comment by sdodson** [comment]
/lgtm
/hold
don't know if you're hoping to see decent signal from rehearse or not

**Comment by smarterclayton** [comment]
It didn't trigger a shared vpc test unfortunately.

**Comment by wking** [comment]
> It didn't trigger a shared vpc test unfortunately.

I've pushed 7e1c123c3 to try and trigger a shared-vpc rehearsal.

/hold

We can lift the hold if that works, after we drop the WIP commit back off.

**Comment by wking** [comment]
Hooray for [rehearsals][1]:

```
/bin/bash: -c: line 69: syntax error near unexpected token `)'
```

Should be fixed with 7e1c123c3 -> c1dc24782, but I guess we'll see ;).

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/6845/rehearse-6845-pull-ci-openshift-installer-master-e2e-aws-shared-vpc/1#1:build-log.txt%3A49

**Comment by wking** [comment]
[rehearsal][1]:

```
2020/01/23 23:40:09 Container setup in pod e2e-aws-shared-vpc completed successfully
```

I'll let the job finish out, because I want to get all the gathered artifacts and I forget how that works with aborted jobs.

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/6845/rehearse-6845-pull-ci-openshift-installer-master-e2e-aws-shared-vpc/2

**Comment by wking** [comment]
[shared-VPC test][1] was green [with][2]:

```
AWS region: us-east-1 (zones: us-east-1b us-east-1c)
Subnets : ['subnet-047f6294332aa3c1c','subnet-0c3bce80bbc2c8f1c','subnet-038c38c7d96364d7f','subnet-027a025e9d9db95ce','subnet-04d9008469025b101','subnet-02f75024b00b20a75']
```

would have been nice if it was run in another region, but whatever ;).  I've dropped the WIP test commit with c1dc24782 -> 7e38260d2, and we're good to go here.

/hold cancel

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/6845/rehearse-6845-pull-ci-openshift-installer-master-e2e-aws-shared-vpc/2
[2]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/6845/rehearse-6845-pull-ci-openshift-installer-master-e2e-aws-shared-vpc/2/artifacts/e2e-aws-shared-vpc/container-logs/setup.log

**Pull request merged**
