### PR TITLE
Opentelemetry zstream onboarding on ibmcloud

### PR DESCRIPTION
**Pull request by smatula**

### CODE REVIEW

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.14-lp-interop-opentelemetry-interop-ibmcloud periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.15-lp-interop-opentelemetry-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.14-lp-interop-opentelemetry-interop-ibmcloud periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.15-lp-interop-opentelemetry-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.14-lp-interop-opentelemetry-interop-ibmcloud

**Review by Simranpal — APPROVED** [review]
/lgtm

**Review by IshwarKanse — APPROVED** [review]
/lgtm

**Pull request merged**
