### PR TITLE
NO-ISSUE: Cleanup fix uid script in assisted

### PR DESCRIPTION
**Pull request by adriengentil**
The workaround script fix_uid.sh is not required anymore, the root cause
is fixed in OCP.

### CODE REVIEW

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted

**Review by osherdp — APPROVED** [review]

**Comment by adriengentil** [comment]
so it looks like the issue is still there :thinking:

**Pull request closed without merging**
