### PR TITLE
openstack: Add myself as an approver

### PR DESCRIPTION
**Pull request by pierreprinetti**
As member of the ShiftOnStack team.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@pierreprinetti this will happen automatically if you update the OWNERS files in the repositories in question -- if that's happened, we can close this

**Comment by pierreprinetti** [comment]
> update the OWNERS files

I thought I had done just that in this PR?

**Comment by pierreprinetti** [comment]
@stevekuznetsov 
I am not sure where to look. `openshift/installer` is the only repo where I have found `openstack-approvers` in the `OWNERS_ALIASES` file, and it does not look like the section in this repo.

https://github.com/openshift/installer/blob/de10297f9158c16f36471c91a3d48be2fb2938e1/OWNERS_ALIASES#L22

Where are those names coming from?

**Comment by pierreprinetti** [comment]
@stevekuznetsov 
cf https://github.com/openshift/cluster-api-provider-openstack/blob/master/OWNERS_ALIASES vs https://github.com/openshift/release/blob/a5a4e689d2d570ba6a640e69c5b0752f8b36fc58/OWNERS_ALIASES#L107-L112

**Comment by pierreprinetti** [comment]
Rebasing onto `master`.

**Pull request merged**
