### PR TITLE
417 managed

### PR DESCRIPTION
**Pull request by paigerube14**
4.17 managed jobs

### CODE REVIEW

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-rosa-4.17-nightly-krkn-tests-rosa-hcp periodic-ci-redhat-chaos-prow-scripts-main-rosa-4.17-nightly-krkn-tests-rosa periodic-ci-redhat-chaos-prow-scripts-main-rosa-4.17-nightly-krkn-rosa-hcp-node periodic-ci-redhat-chaos-prow-scripts-main-rosa-4.17-nightly-krkn-tests-rosa-node

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-rosa-4.17-nightly-krkn-tests-rosa-hcp periodic-ci-redhat-chaos-prow-scripts-main-rosa-4.17-nightly-krkn-tests-rosa

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-rosa-4.17-nightly-krkn-rosa-hcp-node

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-rosa-4.17-nightly-krkn-tests-rosa

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-rosa-4.17-nightly-krkn-tests-rosa-node

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-rosa-4.17-nightly-krkn-tests-rosa-node

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-rosa-4.17-nightly-krkn-tests-rosa-node

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-rosa-4.17-nightly-krkn-tests-rosa-node periodic-ci-redhat-chaos-prow-scripts-main-4.17-nightly-krkn-hub-node-tests

**Comment by paigerube14** [comment]
@shahsahil264 @chaitanyaenr  ptal, rosa node and normal tests are passing now

**Comment by paigerube14** [comment]
turning off hcp as a blocker on install is still being worked on

**Review by shahsahil264 — APPROVED** [review]
LGTM

**Pull request merged**
