### PR TITLE
Add power-outage scenario to the chaos test suite

### PR DESCRIPTION
**Pull request by chaitanyaenr**
This will allow us to understand and track regressions in terms of cluster recovery and performance after power outages or cluster shutdown as we very often see users turning on/off based on the demand.

### CODE REVIEW

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-krkn-hub-cloud-api-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
ci/rehearse/periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-krkn-hub-cloud-api-tests

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.14-nightly-krkn-hub-cloud-api-tests

**Pull request merged**
