### PR TITLE
assisted-installer: remove centos stream8

### PR DESCRIPTION
**Pull request by rccrdpccl**
/cc @adriengentil @gamli75

### CODE REVIEW

**Comment by rccrdpccl** [comment]
/pj-rehearsal pull-ci-openshift-assisted-service-cloud_hotfix_releases-subsystem-aws

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-cloud_hotfix_releases-subsystem-aws

**Review by adriengentil — APPROVED** [review]

**Pull request merged**
