### PR TITLE
add rollback step to OCP-60396 prow automation

### PR DESCRIPTION
**Pull request by evakhoni**
adding a previously disabled rollback step from OCP-60396 to prow automation.

/cc @jianlinliu @jiajliu @JianLi-RH @dis016 
for review

### CODE REVIEW

**Comment by evakhoni** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-stable-aws-ipi-ovn-ipsec-to-multiarch-f28

**Comment by jiajliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-stable-gcp-ipi-to-multiarch-f28

**Comment by evakhoni** [comment]
oh :facepalm: the dreaded `exec /tools/entrypoint: argument list too long`
/pj-rehearse abort

**Comment by evakhoni** [comment]
lets retry
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-stable-gcp-ipi-to-multiarch-f28

**Comment by evakhoni** [comment]
failed before reaching the step.. another one
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-stable-aws-ipi-ovn-ipsec-to-multiarch-f28

**Comment by evakhoni** [comment]
oh, again `exec /tools/entrypoint: argument list too long`
/pj-rehearse abort

**Comment by evakhoni** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-stable-aws-ipi-ovn-ipsec-to-multiarch-f28

**Comment by evakhoni** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-stable-aws-ipi-ovn-ipsec-to-multiarch-f28

**Comment by evakhoni** [comment]
ok we have a pass 
https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/55775/rehearse-55775-periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-stable-aws-ipi-ovn-ipsec-to-multiarch-f28/1826501118402760704

```
------> OCP-60396
Test Start: post-OCP-60396
passed verifying cvo image is manifest.list
to-multi rollback reject step passed.

```
/pj-rehearse ack

**Pull request merged**
