### PR TITLE
Follow up #58544

### PR DESCRIPTION
**Pull request by aleskandro**
- Revert changes to the interop- step for running CNV tests in favour of a more Prow-native step that seems not the path forward for the interop team.
- Fix minor issues from previous PR (i forgot to hold)

### CODE REVIEW

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-release-master-cnv-nightly-4.18-e2e-aws-arm64-deploy-cnv

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-release-master-cnv-nightly-4.18-e2e-aws-arm64-deploy-cnv

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-release-master-cnv-nightly-4.18-e2e-aws-arm64-deploy-cnv

**Review by droslean — APPROVED** [review]

**Comment by aleskandro** [comment]
Refers CNV-47087

**Pull request merged**
