### PR TITLE
remove devguyio from OpenShift Serverless OWNER files

### PR DESCRIPTION
**Pull request by devguyio**
as per title

### CODE REVIEW

**Comment by pierDipi** [comment]
There is this file with you https://github.com/openshift/release/blob/master/clusters/app.ci/registry-access/knative/OWNERS, do you wanna remove that one too?

**Comment by devguyio** [comment]
> * ~[core-services/image-mirroring/knative/OWNERS](https://github.com/openshift/release/blob/master/core-services/image-mirroring/knative/OWNERS)~ [devguyio]

I think it was removed, no? https://github.com/openshift/release/pull/27452/files#diff-e00d6bce2f6f089287cdf75815490abfb72b01895651f60fb9a7ccbed4a181faL15

**Comment by devguyio** [comment]
> There is this file with you https://github.com/openshift/release/blob/master/clusters/app.ci/registry-access/knative/OWNERS, do you wanna remove that one too?

@pierDipi I am removed from there -> https://github.com/openshift/release/pull/27452/files#diff-e00d6bce2f6f089287cdf75815490abfb72b01895651f60fb9a7ccbed4a181faL15

**Comment by pierDipi** [comment]
We're not approvers in some directories, so
/cc @mgencur

**Pull request merged**
