### PR TITLE
ipi-install: avoid failing step on OSUS config corner cases

### PR DESCRIPTION
**Pull request by petr-muller**
https://github.com/openshift/release/pull/40711 broke OKD jobs like https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-okd-4.14-e2e-aws-ovn/1689787699755487232

We should only mess up with OSUS if we work with OCP channels. bail out when we do not find a well-known channel in the CVO overrides file.

I also added a check for the presence of CVO overrides file itself, for good measure

### CODE REVIEW

**Comment by petr-muller** [comment]
/pj-rehearse periodic-ci-openshift-release-master-okd-4.14-e2e-aws-ovn periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-ibmcloud-ovn-multi-s390x pull-ci-openshift-coredns-master-e2e-aws-ovn pull-ci-maistra-envoy-maistra-2.4-maistra-envoy-unit-2-4

**Comment by petr-muller** [comment]
> job(s): periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade either don't exist or were not found to be affected, and cannot be rehearsed

right, cannot rehearse upgrade jobs b/c I'm technically not touching stableinitial. but i should not need it anyway

/pj-rehearse periodic-ci-openshift-release-master-okd-4.14-e2e-aws-ovn periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-ibmcloud-ovn-multi-s390x pull-ci-openshift-coredns-master-e2e-aws-ovn pull-ci-maistra-envoy-maistra-2.4-maistra-envoy-unit-2-4

**Review by vrutkovs — APPROVED** [review]
/approve
/lgtm

**Comment by vrutkovs** [comment]
```
INFO[2023-08-11T10:06:07Z] Running step e2e-aws-ovn-ipi-install-install. 
INFO[2023-08-11T10:36:51Z] Step e2e-aws-ovn-ipi-install-install succeeded after 30m43s. 
```
/pj-rehearse ack

**Comment by petr-muller** [comment]
[Behavior with OKD](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/42231/rehearse-42231-periodic-ci-openshift-release-master-okd-4.14-e2e-aws-ovn/1689940425692942336/artifacts/e2e-aws-ovn/ipi-install-install/build-log.txt) is like expected:

```
Release payload version: 4.14.0-0.okd-2023-08-10-204608
Payload architecture not found in .metadata.metadata["release.openshift.io/architecture"], using .config.architecture
Release payload architecture: amd64
No known OCP channel found in CVO manifest, clearing the channel
Will include manifests:
```

**Pull request merged**
