### PR TITLE
SPLAT-1664: Create new vsphere team alias and updated vsphere owner files.

### PR DESCRIPTION
**Pull request by vr4manta**
[SPLAT-1664](https://issues.redhat.com//browse/SPLAT-1664)

### Changes
- Create new vsphere-approvers and vsphere-reviewers alias
- Updated vsphere OWNER files to reference new aliases

### CODE REVIEW

**Comment by vr4manta** [comment]
/assign @danilo-gemoli 
Ready for review, thanks!

**Review by deepsm007 — APPROVED** [review]

**Pull request merged**
