### PR TITLE
OCPQE-26461 Enable 4.15 for QE job controller

### PR DESCRIPTION
**Pull request by jhuttana**
Enable 4.15 for QE job controller

### CODE REVIEW

**Comment by jhuttana** [comment]
/pj-rehearse periodic-ci-openshift-release-tests-master-qe-release-gate-test

**Comment by rioliu-rh** [comment]
this PR depends on https://github.com/openshift/release-tests/pull/334

**Comment by rioliu-rh** [comment]
/pj-rehearse periodic-ci-openshift-release-tests-master-qe-release-gate-test

**Pull request merged**
