### PR TITLE
Add origin-web-console-server to prow

### PR DESCRIPTION
**Pull request by jwforres**

### CODE REVIEW

**Comment by jwforres** [comment]
cc @spadgett

**Comment by jwforres** [comment]
@stevekuznetsov here is this piece, assume this needs to wait to merge until the jobs are updated, working on that next

**Comment by jwforres** [comment]
Depends on https://github.com/openshift/aos-cd-jobs/pull/853

**Comment by kargakis** [comment]
@jwforres @spadgett do you guys use the [SQ UI](https://origin-web-console-sq-status-ci.svc.ci.openshift.org/#/queue)? If not and you can live w/o a UI for the queue for some time, instead of adding `cluster/ci/config/submit-queue/submit_queue_origin_web_console_server.yaml`, you can add a github query in [here](https://github.com/openshift/release/blob/f5220366b98e440d1c1a4bff2d27ae1eaed60077/cluster/ci/config/prow/config.yaml#L27) to enable merges for the new repo and the rest should be handled for you automatically.

**Comment by jwforres** [comment]
I don't have a strong preference on whether we use SQ, we aren't going to have a ton of merges in this repo.  The bulk of the commits in this repo will be the auto-vendored bindata files.   @spadgett you have an opinion?

**Comment by stevekuznetsov** [comment]
Tide will make your life easier then, use Tide

**Comment by jwforres** [comment]
updated to use tide instead

**Comment by stevekuznetsov** [comment]
Hold my 🍺

**Comment by kargakis** [comment]
Btw, we have a basic UI for tide now: https://deck-ci.svc.ci.openshift.org/tide.html

**Pull request merged**
