### PR TITLE
velero-plugin-for-microsoft-azure: initial setup

### PR DESCRIPTION
**Pull request by hhpatel14**
Initial setup for https://github.com/openshift/velero-plugin-for-microsoft-azure. Build image, add unit-test and, mirror image to external registry.

### CODE REVIEW

**Review by kaovilai — APPROVED** [review]

**Comment by hhpatel14** [comment]
=== RUN   TestObjectExists
=== RUN   TestObjectExists/getBlob_error
    object_store_test.go:89: PASS:	Exists()
    object_store_test.go:89: PASS:	getBlob(string,string)
=== RUN   TestObjectExists/exists
    object_store_test.go:94: PASS:	Exists()
    object_store_test.go:94: PASS:	getBlob(string,string)
=== RUN   TestObjectExists/doesn't_exist
    object_store_test.go:94: PASS:	Exists()
    object_store_test.go:94: PASS:	getBlob(string,string)
=== RUN   TestObjectExists/error_checking_for_existence
    object_store_test.go:89: PASS:	Exists()
    object_store_test.go:89: PASS:	getBlob(string,string)
--- PASS: TestObjectExists (0.00s)
    --- PASS: TestObjectExists/getBlob_error (0.00s)
    --- PASS: TestObjectExists/exists (0.00s)
    --- PASS: TestObjectExists/doesn't_exist (0.00s)
    --- PASS: TestObjectExists/error_checking_for_existence (0.00s)
=== RUN   TestGetVolumeID
time="2023-02-20T21:16:55Z" level=info msg="Unable to handle CSI driver: unknown.csi.azure.com"
--- PASS: TestGetVolumeID (0.00s)
=== RUN   TestSetVolumeID
--- PASS: TestSetVolumeID (0.00s)
=== RUN   TestParseFullSnapshotName
--- PASS: TestParseFullSnapshotName (0.00s)
=== RUN   TestGetComputeResourceName
--- PASS: TestGetComputeResourceName (0.00s)
=== RUN   TestGetSnapshotTags
=== RUN   TestGetSnapshotTags/degenerate_case_(no_tags)
=== RUN   TestGetSnapshotTags/velero_tags_only_get_applied
=== RUN   TestGetSnapshotTags/slashes_in_velero_tag_keys_get_replaces_with_dashes
=== RUN   TestGetSnapshotTags/volume_tags_only_get_applied
=== RUN   TestGetSnapshotTags/non-overlapping_velero_and_volume_tags_both_get_applied
=== RUN   TestGetSnapshotTags/when_tags_overlap,_velero_tags_take_precedence
=== RUN   TestGetSnapshotTags/velero,_snapshot_and_volume_tags_all_get_applied
--- PASS: TestGetSnapshotTags (0.00s)
    --- PASS: TestGetSnapshotTags/degenerate_case_(no_tags) (0.00s)
    --- PASS: TestGetSnapshotTags/velero_tags_only_get_applied (0.00s)
    --- PASS: TestGetSnapshotTags/slashes_in_velero_tag_keys_get_replaces_with_dashes (0.00s)
    --- PASS: TestGetSnapshotTags/volume_tags_only_get_applied (0.00s)
    --- PASS: TestGetSnapshotTags/non-overlapping_velero_and_volume_tags_both_get_applied (0.00s)
    --- PASS: TestGetSnapshotTags/when_tags_overlap,_velero_tags_take_precedence (0.00s)
    --- PASS: TestGetSnapshotTags/velero,_snapshot_and_volume_tags_all_get_applied (0.00s)
PASS
ok  	github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure	0.009s

**Comment by hhpatel14** [comment]
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/36582/rehearse-36582-pull-ci-openshift-velero-plugin-for-microsoft-azure-konveyor-dev-images/1627778728668958720/artifacts/build-logs/velero-plugin-for-microsoft-azure.log

**Pull request merged**
