### PR TITLE
ci-operator/config: document RHCOS layering trick a bit more

### PR DESCRIPTION
**Pull request by jlebon**
We've had people ask multiple times what those Dockerfiles are doing, so let's add some more docs there.

### CODE REVIEW

**Comment by jlebon** [comment]
This is just a comment change. Not worth the CI runs.

/pj-rehearse skip

**Comment by jlebon** [comment]
@sdodson I probably should've inlined this one into https://github.com/openshift/release/pull/49156 when I opened the latter. Since you had a look at that one, want to stamp this one?

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by sdodson** [comment]
/label approved
just docs changes

**Pull request merged**
