### PR TITLE
Update core-assembler CI for 4.18

### PR DESCRIPTION
**Pull request by mike-nguyen**
See individual commits

### CODE REVIEW

**Comment by jlebon** [comment]
This conflicts with https://github.com/openshift/release/pull/59000 but I can rebase once this one lands.

**Comment by mike-nguyen** [comment]
/assign @bear-redhat 
Can you take a look at this? This is a prep step for branching for RHCOS.

**Comment by mike-nguyen** [comment]
@bear-redhat can you take a look when you get a chance?

**Comment by jlebon** [comment]
This is now part of https://github.com/openshift/release/pull/59083.

/close

**Pull request closed without merging**
