### PR TITLE
Adding user metadata compatability for kube-burner index step

### PR DESCRIPTION
**Pull request by vishnuchalla**
### Description
Adding user metadata compatibility for kube-burner index step. This will be useful to understand the upgrade from and to versions by looking at the kube-burner index `jobSummary`.
Related issue: https://github.com/kube-burner/kube-burner-ocp/issues/76

### Testing
Tested through PR rehearsals.

### CODE REVIEW

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-loaded-upgrade-from-4.15-loaded-upgrade-415to416-24nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-loaded-upgrade-from-4.15-loaded-upgrade-415to416-24nodes

**Comment by vishnuchalla** [comment]
Verified that we are able to capture some custom metadata as a part of the jobSummary
```
{
  "_index": "ripsaw-kube-burner-000010",
  "_type": "_doc",
  "_id": "f06ba6961d5c81ee78b7f07c9724728df6b17db91a1b6d692d4b5250bc56c28c",
  "_version": 1,
  "_score": null,
  "_source": {
    "timestamp": "2024-07-16T21:45:05Z",
    "endTimestamp": "2024-07-16T23:44:04Z",
    "elapsedTime": 7139,
    "uuid": "b87a12ad-77a0-4760-8881-0a6296574d9a",
    "metricName": "jobSummary",
    "jobConfig": {
      "name": "kube-burner-ocp-indexing"
    },
    "metadata": {
      "clusterName": "ci-op-tbj749n1-bdb4f-b6ks7",
      "clusterType": "self-managed",
      "controlPlaneArch": "amd64",
      "ipsecMode": "Disabled",
      "k8sVersion": "v1.29.6+aba1e8d",
      "masterNodesCount": 3,
      "masterNodesType": "m6a.xlarge",
      "ocpMajorVersion": "4.16",
      "ocpVersion": "4.16.0-0.nightly-2024-07-16-082234",
      "platform": "AWS",
      "prevocpMajorVersion": "4.15.22",
      "prevocpVersion": "4.15.22",
      "publish": "External",
      "region": "us-west-2",
      "sdnType": "OVNKubernetes",
      "totalNodes": 27,
      "workerArch": "amd64",
      "workerNodesCount": 24,
      "workerNodesType": "m6a.xlarge"
    },
    "version": "1.3.0@e66b468ff8d3bd9d09e97c0e49c94a2246e83f54",
    "passed": true
  },
  "fields": {
    "endTimestamp": [
      "2024-07-16T23:44:04.000Z"
    ],
    "timestamp": [
      "2024-07-16T21:45:05.000Z"
    ]
  },
  "highlight": {
    "uuid.keyword": [
      "@kibana-highlighted-field@b87a12ad-77a0-4760-8881-0a6296574d9a@/kibana-highlighted-field@"
    ],
    "metricName.keyword": [
      "@kibana-highlighted-field@jobSummary@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1721166305000
  ]
}
```

**Review by rsevilla87 — APPROVED** [review]
/lgtm

**Comment by rsevilla87** [comment]
> @vishnuchalla Where is the "custom metadata as a part of the jobSummary", I'm not seeing in cluster-density or kube-index?

The custom fields are part of the metadata object of the `jobSummary` document, find it at this comment @vishnuchalla pasted previously https://github.com/openshift/release/pull/53551#issuecomment-2232026904

**Pull request merged**
