### PR TITLE
MGMT-18313: Change image-service images building configuration

### PR DESCRIPTION
**Pull request by danmanor**

### CODE REVIEW

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-image-service-main-edge-images pull-ci-openshift-assisted-image-service-release-ocm-2.10-images pull-ci-openshift-assisted-image-service-release-ocm-2.11-images

**Comment by eifrach** [comment]
/pj-rehearse pull-ci-openshift-assisted-image-service-main-edge-e2e-ai-operator-ztp

**Pull request merged**
