### PR TITLE
fix(RHTAP-1012): Install additional packages for e2e-test-runner base image required by pprof

### PR DESCRIPTION
**Pull request by pmacik**
This PR adds a dependency for `go tool pprof -svg` command.

### CODE REVIEW

**Comment by pmacik** [comment]
/pr-rehearse pull-ci-redhat-appstudio-e2e-tests-main-images periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-basic

**Comment by pmacik** [comment]
/pr-rehearse pull-ci-redhat-appstudio-e2e-tests-main-images periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-basic

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-images periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-basic

**Comment by pmacik** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-basic

**Comment by pmacik** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-basic

**Comment by pmacik** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-basic

**Review by jhutar — APPROVED** [review]

**Pull request merged**
