### PR TITLE
Exclude CCCMO from FF process due to operator not in release

### PR DESCRIPTION
**Pull request by Danil-Grigorev**

### CODE REVIEW

**Comment by petr-muller** [comment]
/approve
/hold

Config change is correct but as DPTP I don't know if this repo can exempt itsefl from feature freeze.

**Comment by Danil-Grigorev** [comment]
@russellb We have a reminder for undoing this change in 4.9 in case automatic process won't work, could you please LGTM?

**Comment by JoelSpeed** [comment]
/hold cancel

We have discussed this on slack and have set ourselves reminders so that we remember to revert this when 4.9 opens

**Comment by petr-muller** [comment]
@JoelSpeed I think the revert won't be necessary - at code freeze nothing changes for your repos (it's the OCP repo critera that change at that time)

**Pull request merged**
