### PR TITLE
Explicitly specify dependent images for Knative Serving

### PR DESCRIPTION
**Pull request by markusthoemmes**
As per title. Step 1 in getting rid of using `$IMAGE_FORMAT`.

/assign @nak3 @mgencur

### CODE REVIEW

**Comment by nak3** [comment]
/lgtm
/hold

`/hold` for test but please feel free to unhold.

**Comment by nak3** [comment]
/retest

vpc issue.

**Comment by markusthoemmes** [comment]
/unhold

All passed but failed in cleanup. That's currently expected.

**Pull request merged**
