### PR TITLE
OCPBUGS-29478: Disable IPv6 jobs from using Loki

### PR DESCRIPTION
**Pull request by derekhiggins**
We need to figure out why our firewall rules don't get applied sometimes.

### CODE REVIEW

**Comment by derekhiggins** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-ovn-ipv6

**Comment by stbenjam** [comment]
When did the problem start? We had some Loki issues recently but they should be resolved now.

/lgtm

**Comment by derekhiggins** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-ovn-ipv6

**Pull request merged**
