### PR TITLE
Delete assisted-baremetal jobs from capi-provider-agent

### PR DESCRIPTION
**Pull request by eranco74**
These jobs constently fail, seems that hypershift requires OpenShift as managment cluster for creating a functional HostedCluster. Must of the functionality tested by these jobs is coverged by the operator workflow jobs jobs

### CODE REVIEW

**Comment by osherdp** [comment]
What about the job in another repos? I guess it doesn't make sense to maintain them as well

**Comment by eranco74** [comment]
> t doesn't make sense to maintain them as w

Pretty sure we already removed it from all other repos but I'll double check

**Comment by eranco74** [comment]
OK, there's still one optional job in assisted-test-infra.
I'll remove it as well

**Review by osherdp — APPROVED** [review]

**Pull request merged**
