### PR TITLE
Update version of AMQ Streams 2.4.0 OLM operator to 2.4.0-1

### PR DESCRIPTION
**Pull request by im-konge**
This PR updates `OLM_OPERATOR_VERSION` environment variable to `2.4.0-1` after latest release.

### CODE REVIEW

**Comment by im-konge** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.14-lp-interop-amq-streams-2-4

**Comment by jankalinic** [comment]
LGTM

**Pull request merged**
