### PR TITLE
sriov: publish operator bundle

### PR DESCRIPTION
**Pull request by zeeke**
Operator bundle publishing is useful to quickly deploy the operator via.

```
operator-sdk run bundle quay-proxy.ci.openshift.org/openshift/ci:ocp_4.18 sriov-network-operator-bundle
```

See
- https://docs.ci.openshift.org/docs/internals/images-in-ci/

---

Use CI built images for e2e tests to avoid problems like:

- https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_sriov-network-operator/981/pull-ci-openshift-sriov-network-operator-master-e2e-telco5g-sriov/1823273385409384448
```
• [FAILED] [4.855 seconds]
validation sriov [It] should deploy the operator webhook if requested
/tmp/tmp.RaN3c23vhK/sriov-network-operator/test/validation/tests/test_validation.go:101
  [FAILED] Expected
      <int32>: 3
  to equal
      <int32>: 2
  In [It] at: /tmp/tmp.RaN3c23vhK/sriov-network-operator/test/validation/tests/test_validation.go:109 @ 08/13/24 09:59:26.539
------------------------------
validation sriov should have SR-IOV node statuses not in progress
/tmp/tmp.RaN3c23vhK/sriov-network-operator/test/validation/tests/test_validation.go:117
```

- https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_sriov-network-operator/981/pull-ci-openshift-sriov-network-operator-master-e2e-telco5g-sriov/1823273385409384448/artifacts/e2e-telco5g-sriov/gather-extra/artifacts/oc_cmds/events
```
openshift-sriov-network-operator                   24m         Warning   Failed                                            pod/operator-webhook-ggplc                                                         Failed to pull image "image-registry.openshift-image-registry.svc:5000/openshift-sriov-network-operator/sriov-network-webhook:latest": reading manifest latest in image-registry.openshift-image-registry.svc:5000/openshift-sriov-network-operator/sriov-network-webhook: authentication required
openshift-sriov-network-operator                   24m         Warning   Failed                                            pod/operator-webhook-ggplc                                                         Error: ErrImagePull
```

### CODE REVIEW

**Comment by zeeke** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-master-e2e-telco5g-sriov

**Comment by zeeke** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-master-operator-e2e

**Comment by zeeke** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-master-e2e-telco5g-sriov

**Comment by zeeke** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-master-e2e-telco5g-sriov

**Comment by zeeke** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-master-e2e-telco5g-sriov

**Comment by zeeke** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-master-images

**Comment by zeeke** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-master-e2e-telco5g-sriov

**Comment by zeeke** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-master-e2e-telco5g-sriov

**Comment by zeeke** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-release-4.16-e2e-telco5g-sriov

**Review by SchSeba — APPROVED** [review]
/lgtm
/approve

**Comment by zeeke** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-master-e2e-telco5g-sriov

**Comment by zeeke** [comment]
> @zeeke is there a reason the commit remove sriov-network string from the operator bundles?
> 
> sriov-network was in front. Now it is just operator-bundle

yes, the reason is a little intricated:

```
operator:
  bundles:
  - as: operator-bundle
    base_index: operator-index
    dockerfile_path: bundleci.Dockerfile
    update_graph: replaces
  substitutions:
  ...
  - pullspec: quay.io/openshift/origin-sriov-network-webhook:.*
    with: pipeline:sriov-network-webhook
  ...
```

creates an image in the pipeline called `<as>` (i.e `sriov-network-operator-bundle` before the commit). That image is a bundle (ClusterServiceVersion + CRDs) created after the given `substitutions`, and it's used in the pipeline to deploy the latest versions (maybe just built) of the operands. Its CSV contains entries like `registry.build05.ci.openshift.org/ci-op-6ypisdtq/pipeline` and cannot be used outside the pipeline (e.g. published to quay.io).


By declaring this image:
```
images:
...
- dockerfile_path: bundleci.Dockerfile
  to: sriov-network-operator-bundle
```
we declare another bundle image (this time without substitutions!) and it gets promoted and published on quay.io. So we will be able to install the operator with:

```
operator-sdk run bundle quay.io/openshift/origin-sriov-network-operator-bundle:4.18

```
or, with [QCI](https://docs.ci.openshift.org/docs/internals/images-in-ci/#qci)
```
operator-sdk run bundle quay-proxy.ci.openshift.org/openshift/ci:ocp_4.18_sriov-network-operator-bundle
```

Let me know if it's not clear, it took me time to understand all the logic behind these builds and jobs.

**Comment by wizhaoredhat** [comment]
LGTM. This work is done so that you can deploy the operator with images from the CI build? I don't get the examples given in those failing 2 CI jobs. Did those 2 issues slip into production?

**Comment by zeeke** [comment]
> LGTM. This work is done so that you can deploy the operator with images from the CI build? I don't get the examples given in those failing 2 CI jobs. Did those 2 issues slip into production?

Yes, this will allow deploying the operator with the latest images from quay.io (which might be a little older than the latest CI build, but that's a detail).

This PR also fixes a problem we had with the `e2e-telco5g-sriov`, which was using a [script](https://github.com/openshift/sriov-network-operator/blob/master/hack/deploy-sriov-in-telco-ci.sh) to build and deploy operators and operands from scratch. That approach turned out to be flaky and sometimes produced Pull image errors.

The part:
```
  steps:
    dependencies:
      OO_INDEX: ci-index-operator-bundle
    env:
      OO_CHANNEL: alpha
      OO_INSTALL_NAMESPACE: openshift-sriov-network-operator
      OO_PACKAGE: sriov-network-operator
      OO_TARGET_NAMESPACES: '!install'
  
    test:
    - ref: ipi-install-rbac
    - ref: optional-operators-subscribe
    ...
```

makes the job using images built in the CI pipeline. The ad-hoc deploy script will then be deprecated.

**Comment by SchSeba** [comment]
/lgtm
/approve

nice work!

**Comment by SchSeba** [comment]
/cc @jupierce @bn222 @wizhaoredhat

can you please help with /lgtm?

**Comment by zeeke** [comment]
rebased to include changes from:
- https://github.com/openshift/release/pull/56589


@jupierce @jmguzik I need you to take a look here:
https://github.com/openshift/release/pull/55954/files#diff-f03dc4e13577d917b8f459d2784818e6dd0821e06bb7c95aa684d7ff7900d113

I want to publish to query.io the sriov-network-operator-bundle

**Pull request merged**
