### PR TITLE
OCPQE-17643: Unify the indention

### PR DESCRIPTION
**Pull request by liangxia**
```
$ echo -e '111\n 222\n  333\n        444'
111
 222
  333
        444
$ echo -e '111\n 222\n  333\n        444' | sed -E 's/^( +)?/  /'
  111
  222
  333
  444
```

### CODE REVIEW

**Comment by JianLi-RH** [comment]
If there is only spaces except return character, then /lgtm, else we have to deal with other white spaces, like tabs.

**Comment by liangxia** [comment]
> If there is only spaces except return character, then /lgtm, else we have to deal with other white spaces, like tabs.

I didn't see any tabs there currently. Example output,
```
failures: 9, errors: 0, skipped: 236, tests: 707 in openshift-extended-test
Failing Scenarios:
[sig-monitoring] Cluster_Observability parallel monitoring user workload monitoring when Need example app Author:hongyli-High-50024-High-49515-Check federate route and service of user workload Prometheus
[sig-updates] OTA osus instance should ConnectedOnly-Author:jiajliu-High-48621-Updateservice pod should be re-deployed when update graphDataImage of updateservice
[sig-node] NODE initContainer policy,volume,readines,quota Author:minmli-High-47[66](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-baremetalds-ipi-ovn-ipv4-fips-f4/1721959262311157760#1:build-log.txt%3A66)3-run pods in user namespaces via crio workload annotation
[sig-network-edge] Network_Edge should Author:shudili-High-50926-Support a Configurable ROUTER_MAX_CONNECTIONS in HAproxy
[sig-monitoring] Cluster_Observability parallel monitoring Author:tagao-Medium-48350-create alert-routing-edit role to allow end users to manage alerting CR
[sig-imageregistry] Image_Registry ROSA-OSD_CCS-ARO-Author:tbuskey-High-22056-Registry operator configure prometheus metric gathering
[sig-updates] OTA osus instance should ConnectedOnly-Author:yanyang-High-52596-High-59687-install/uninstall updateservice instance on a connected/http/https proxy cluster

failures: 2, errors: 0, skipped: 5, tests: 393 in cucushift-e2e
Failing Scenarios:
 Scenario: OCP-40587:Authentication Audit log oauthaccesstoken creation and deletion
 Scenario: OCP-37508:Logging One logging acceptance case for all cluster
```

**Pull request merged**
