### PR TITLE
Add dry-run mirroring Prowjobs and mappings 

### PR DESCRIPTION
**Pull request by petr-muller**
Builds on https://github.com/openshift/release/pull/4256

Add Prowjob periodics that should eventually replace mirroring
CronJobs. Initally run the mirroring with `--dry-run=true` to see that
everything work and we can fully switch from CronJobs to ProwJobs.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
This looked good in the previous PR -- any change  other than breaking it out?

**Comment by petr-muller** [comment]
> This looked good in the previous PR -- any change other than breaking it out?

Only adding `--dry-run=true` to the mirroring commands, nothing else.

**Pull request merged**
