### PR TITLE
gather: Also gather node journals from farther back

### PR DESCRIPTION
**Pull request by cgwalters**
This will be useful for me in debugging things; sometimes I want earlier boot data when debugging upgrades.

### CODE REVIEW

**Comment by cgwalters** [comment]
This impacts nearly every job, so a rehearsal is going to run a big random set of things.  Looking at say [the kubevirt e2e job](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/32369/rehearse-32369-pull-ci-openshift-hypershift-main-kubevirt-e2e-kubevirt-gcp-ovn/1570873190710775808) it looks like this is going to work.  (There's only 2 node boots there, but I'm pretty confident it will work).  At least we know this won't break anything.

**Comment by cgwalters** [comment]
/reopen

This would still be useful...

**Review by jmarrero — APPROVED** [review]

**Review by jmarrero — APPROVED** [review]
/approve
/lgtm

**Comment by cgwalters** [comment]
/pj-rehearse pull-ci-openshift-machine-config-operator-master-e2e-aws-ovn

**Pull request closed without merging**
