### PR TITLE
CI-Operator Fixes, Console Tests

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Structure ci-operator configuration explicitly, autosync

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

Add ci-operator driven tests for openshift/console

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

/assign @smarterclayton

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@smarterclayton in second commit, the amount of copy-paste for the five ci-operator jobs for openshift/console is pretty ugly

**Comment by stevekuznetsov** [comment]
I think originally I was going to write a generator for Prow config

**Comment by smarterclayton** [comment]
Agree about pasta.  It does suck that we have to intersperse the jobs.

/lgtm

**Comment by smarterclayton** [comment]
One thing - we are going to be release branching some of these jobs.  When we do, what's the right way to release branch them?  Same file, different name in directory?  I'd probably prefer to copy the job definitions rather than worry about whether they've changed incompatibly.

**Comment by stevekuznetsov** [comment]
Yeah I guess we can do `ci-operator/org/repo/branch.json` ?

Let me merge the support for custom key names to upstream so we can make them all `config.json` inside of the configmap

**Pull request merged**
