### PR TITLE
Onboard opendatahub-io/ai-edge repo to prow system

### PR DESCRIPTION
**Pull request by LaVLaS**
Onboard oepndatahub-io/ai-edge to the openshift-ci system to enable the tide plugin for PR review and approval

### CODE REVIEW

**Comment by danilo-gemoli** [comment]
Do you guys use some tools other than `ci-operator` to run your tests? Because I don't see any configuration.

**Comment by LaVLaS** [comment]
@danilo-gemoli We will in the next few weeks but I can add a simple ci-operator config if we need it for the onboarding

**Comment by danilo-gemoli** [comment]
Not needed, just asking

**Pull request merged**
