### PR TITLE
Add an optional e2e-openstack job to openshift/kubernetes

### PR DESCRIPTION
**Pull request by Fedosin**

### CODE REVIEW

**Comment by Fedosin** [comment]
/test pj-rehearse
--

**Comment by Fedosin** [comment]
@tnozicka Unfortunately now there are no registered e2e workflows for OpenStack: https://github.com/openshift/release/tree/master/ci-operator/step-registry/openshift/e2e 

Because of this we cannot generate jobs automatically with `make jobs` command, and have to do it manually.

There is a task to add the workflows: https://issues.redhat.com/browse/OSASINFRA-2078

**Review by tnozicka — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
