### PR TITLE
Securesign Operator Changes

### PR DESCRIPTION
**Pull request by tommyd450**

### CODE REVIEW

**Comment by JasonPowr** [comment]
/pj-rehearse pull-ci-securesign-secure-sign-operator-main-tas-operator-e2e

**Comment by JasonPowr** [comment]
```
 + xargs oc patch --type=merge -n openshift-rhtas-operator --patch-file /tmp/image_config.patch
Error from server (BadRequest): error decoding patch: invalid character '"' after object key:value pair
{"component":"entrypoint","error":"wrapped process failed: exit status 123","file":"sigs.k8s.io/prow/pkg/entrypoint/run.go:84","func":"sigs.k8s.io/prow/pkg/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2024-09-17T10:49:06Z"}
error: failed to execute wrapped command: exit status 123 
INFO[2024-09-17T10:49:07Z] Step tas-operator-e2e-install failed after 2m20s. 
INFO[2024-09-17T10:49:07Z] Step phase test failed after 2m20s.  
```

Seems to be failing to apply the patch

**Comment by tommyd450** [comment]
/pj-rehearse pull-ci-securesign-secure-sign-operator-main-tas-operator-e2e

**Comment by osmman** [comment]
there is some bug in generated patch
```
oc patch --type=merge -n openshift-rhtas-operator --patch-file /tmp/image_config.patch
Error from server (BadRequest): error decoding patch: invalid character '"' after object key:value pair
```

**Pull request merged**
