### PR TITLE
Add presubmits for redhat-openshift-ecosystem/openshift-preflight

### PR DESCRIPTION
**Pull request by komish**
Presubmit jobs to start testing https://github.com/redhat-openshift-ecosystem/openshift-preflight/ PRs e2e. 

This PR tests against a non-main branch for now, but this will change after initial testing of the automation looks OK.

Signed-off-by: Jose R. Gonzalez <josegonzalez89@gmail.com>

### CODE REVIEW

**Review by jomkz — APPROVED** [review]
/lgtm

**Review by droslean — APPROVED** [review]

**Pull request merged**
