### PR TITLE
Add e2e job to octavia operator with kuttl tests

### PR DESCRIPTION
**Pull request by cescgina**
Add the build-deploy-kuttl job to octavia-operator. The deploy part it's
not actually testing the operator, since octavia is not yet part of the
openstack operator, but at least the kuttl tests can run.

### CODE REVIEW

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-octavia-operator-main-octavia-operator-build-deploy-kuttl

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-octavia-operator-main-octavia-operator-build-deploy-kuttl

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-octavia-operator-main-octavia-operator-build-deploy-kuttl

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-octavia-operator-main-octavia-operator-build-deploy-kuttl

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-octavia-operator-main-octavia-operator-build-deploy-kuttl

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-octavia-operator-main-octavia-operator-build-deploy-kuttl

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-octavia-operator-main-octavia-operator-build-deploy-kuttl

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-octavia-operator-main-octavia-operator-build-deploy-kuttl

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-octavia-operator-main-octavia-operator-build-deploy-kuttl

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-octavia-operator-main-octavia-operator-build-deploy-kuttl

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-octavia-operator-main-octavia-operator-build-deploy-kuttl

**Comment by cescgina** [comment]
Tests are passing, ready for review.

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-octavia-operator-main-octavia-operator-build-deploy-kuttl

**Comment by frenzyfriday** [comment]
Looks good to me. The error `oc kustomize /alabama/install_yamls/out/openstack/openstack/cr | oc delete --ignore-not-found=true -f -
error: evalsymlink failure on '/alabama/install_yamls/out/openstack/openstack/cr' : lstat /alabama/install_yamls/out/openstack/openstack/cr: no such file or directory ` doesn't look related to this patch. I had hit this same error once but it cleared on rerun. Not really sure what caused it.

**Comment by cescgina** [comment]
> Looks good to me. The error `oc kustomize /alabama/install_yamls/out/openstack/openstack/cr | oc delete --ignore-not-found=true -f - error: evalsymlink failure on '/alabama/install_yamls/out/openstack/openstack/cr' : lstat /alabama/install_yamls/out/openstack/openstack/cr: no such file or directory ` doesn't look related to this patch. I had hit this same error once but it cleared on rerun. Not really sure what caused it.

You're right, this is not really an error. The cause is that `make openstack_deploy` has as dependency `openstack_deploy_cleanup` to delete previous deployments, but since there is none, there is nothing to delete. @Sandeepyadav93 since kuttl tests passed, do you think we need to retrigger or its fine?

**Comment by cescgina** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-octavia-operator-main-octavia-operator-build-deploy-kuttl

**Comment by Sandeepyadav93** [comment]
/lgtm

We are aware of the fact that Octavia is not integrated into the meta-operator yet and this job will still run deploy using meta-operator after kutll tests, but this job allows us to not require any further changes once this operator is integrated into meta-operator.

**Pull request merged**
