### PR TITLE
Updating odh tests to use ocp 4.6

### PR DESCRIPTION
**Pull request by crobby**

### CODE REVIEW

**Comment by crobby** [comment]
Ok, not sure why, but the jupyterhub-db is not coming up on 4.6.
It looks like it's waiting on a pvc which is stuck in Pending
I do not see a pv that would be behind the pvc.

Not sure what else to look at.

**Review by alvaroaleman — APPROVED** [review]

**Review by alvaroaleman — APPROVED** [review]

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
