### PR TITLE
Always select Friday in the current week

### PR DESCRIPTION
**Pull request by ccardenosa**

### CODE REVIEW

**Comment by ccardenosa** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-public-main-sno-spoke-4.18-nightly-telcov10n-sno-spoke-f360

**Comment by ccardenosa** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-public-main-sno-spoke-4.18-nightly-telcov10n-sno-spoke-f360

**Comment by ccardenosa** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-public-main-sno-spoke-4.18-nightly-telcov10n-sno-spoke-f360

**Comment by ccardenosa** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-public-main-sno-spoke-4.18-nightly-telcov10n-sno-spoke-f360

**Comment by ccardenosa** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-public-main-sno-spoke-4.18-nightly-telcov10n-sno-spoke-f360

**Comment by ccardenosa** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-public-main-sno-spoke-4.18-nightly-telcov10n-sno-spoke-f360

**Comment by ccardenosa** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-public-main-sno-spoke-4.18-nightly-telcov10n-sno-spoke-f360

**Comment by ccardenosa** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-public-main-sno-spoke-4.18-nightly-telcov10n-sno-spoke-f360

**Comment by ccardenosa** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-public-main-sno-spoke-4.18-nightly-telcov10n-sno-spoke-f360

**Review by natifridman — APPROVED** [review]

**Pull request merged**
