### PR TITLE
[WIP] [DNM] Change initial version to test hypershift job

### PR DESCRIPTION
**Pull request by trozet**

### CODE REVIEW

**Comment by trozet** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-release-4.14-e2e-hypershift-ovn

**Comment by ricky-rav** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-release-4.14-e2e-hypershift-ovn

**Comment by ricky-rav** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-release-4.14-e2e-hypershift-ovn

**Comment by ricky-rav** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-release-4.14-e2e-hypershift-ovn

**Pull request closed without merging**
