### PR TITLE
[WIP] create a debug cluster

### PR DESCRIPTION
**Pull request by xiaojiey**

### CODE REVIEW

**Comment by xiaojiey** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-aws-ipi-ovn-hypershift-guest-f7

**Comment by xiaojiey** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-aws-ipi-ovn-hypershift-guest-f7

**Comment by xiaojiey** [comment]
@yunjiang29 @zhaozhanqi Could you please help to review? Thanks.

**Comment by BhargaviGudi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-aws-ipi-ovn-hypershift-guest-f7

**Comment by BhargaviGudi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-aws-ipi-ovn-hypershift-guest-f7

**Pull request closed without merging**
