### PR TITLE
Sync arm64 4.12 upgrades (4.10,4.11,4.12->4.12-nightly)

### PR DESCRIPTION
**Pull request by aleskandro**

### CODE REVIEW

**Comment by kuiwang02** [comment]
@aleskandro per https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/34854/pull-ci-openshift-release-master-build-clusters/1604760106979823616, there is error
```console
Auto-merging ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
CONFLICT (content): Merge conflict in ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
Automatic merge failed; fix conflicts and then commit the result.
```

there is conflicts why the job are failing.

**Comment by kuiwang02** [comment]
/lgtm

to avoid conflicts again.

**Comment by aleskandro** [comment]
Refers ARMOCP-466

**Pull request merged**
