### PR TITLE
Adding kind label as required matching label

### PR DESCRIPTION
**Pull request by prietyc123**
Should fix https://github.com/openshift/odo/issues/4745

### CODE REVIEW

**Comment by prietyc123** [comment]
@droslean @petr-muller We are trying to make `kind` label as required for pr to merge. Could you please have a look and confirm, if the pr will address the issue completely. cc_ @kadel 

I hope I was clear with my requirement. Although please let me know if you need any further information.

**Comment by prietyc123** [comment]
I have gone through the changes done by `shipwright-io` in https://github.com/openshift/release/search?q=matching+label and observed they are doing the same way https://github.com/openshift/release/blob/master/core-services/prow/02_config/shipwright-io/cli/_prowconfig.yaml#L11 and its working for them. @kadel @dharmit I think we can merge these changes. 
I will also try to look for merged pr if any.

**Comment by prietyc123** [comment]
> Sorry, I'm not familiar with that plugin at all. I'll take a look when I have time, but ATM I'm no better to advise about this than a rando on a street.

@petr-muller Thanks for a quick reply. I will look into it further 🙂

**Comment by prietyc123** [comment]
Merged prs by `shipwright-io` team https://github.com/openshift/release/pull/16230/files required for same behavior.

**Review by dharmit — APPROVED** [review]

**Pull request merged**
