### PR TITLE
Fixup jenkins-related promoting postsubmits

### PR DESCRIPTION
**Pull request by petr-muller**
Three postsubmits were added in https://github.com/openshift/release/pull/3177
probably as copies, not generated by Prowgen. These manual postsubmits promote
the images which manual postsubmits are not supposed to do (plus, the
associated ci-operator config does not specify promotion destination).

Add `promotion` stanza for these three repos. Because these are `master`
branches, promote to `4.1` and change also `tag_specification` and
`base_images` accordingly.

### CODE REVIEW

**Comment by petr-muller** [comment]
I'm not sure whether adding this `promotion` stanza is 100% the appropriate thing to do. Maybe we should just remove the postsubmits if these images are not supposed to be promoted.

**Comment by gabemontero** [comment]
@petr-muller yeah we do *NOT* publicly publish any images related to the jenkins plugin repos

we only want to update the openshift/jenkins image that comes out of https://github.com/openshift/jenkins with the new version of each plugin already included in  that image for PR testing.

Based on your earlier comment, removing the postsubmit seems warranted, assuming we can still gather artifacts for PR test debug once those postsubmits are removed.

Or unless there is some other dependency on postsubmits I am unaware of.

**Comment by petr-muller** [comment]
@gabemontero removing the postsubmits looks like the right thing to do then - without the `promotion` stanza the jobs probably just failed to promote images anyway as no destination was configured. Removing the jobs should have no observable effect.

Promoting images does not imply *publicly publish* though - it just means that images built by CI are kept by tagging them into a given promotion destination on the api.ci cluster. Some of these destinations are then mirrored to quay, but not all of them are. You can promote to an imagestream that is not mirrored.

**Comment by gabemontero** [comment]
sounds good @petr-muller

**Comment by petr-muller** [comment]
@gabemontero I can haz `/lgtm`?

**Comment by petr-muller** [comment]
> can we trigger a rehearsal of the 3 jenkins plugin test jobs to confirm things are OK ?

@gabemontero you mean the presubmits? not really, not without artifically modifying the ci-operator config or something.

But here's a proof that these postsubmits do not even work, they basically do nothing without the promotion config:
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/branch-ci-openshift-jenkins-client-plugin-master-images/4

**Comment by gabemontero** [comment]
yeah I've had to do those temp changes in the past as well

I'll create a test PR in a plugin after this merges and ping you if something unexpected happens @petr-muller 

/lgtm

**Pull request merged**
