### PR TITLE
ci-operator/step-registry/ipi/deprovision/artifacts/bootstrap: Drop gather

### PR DESCRIPTION
**Pull request by wking**
The installer does this automatically since openshift/installer@cad7f02a8b (openshift/installer#1822).  You'd still need to SSH in to gather manually in 4.1.z, but if we think that's important we should backport the gather logic to the installer's 4.1 branch.

### CODE REVIEW

**Comment by wking** [comment]
[Rehearse][1]:

```
time="2019-12-11T05:45:52Z" level=info msg="registry steps changed" pr=6336 registry="map[ipi-deprovision-artifacts:0xc008c73920]"
time="2019-12-11T05:45:53Z" level=info msg="no jobs to rehearse have been found" pr=6336
```

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/6336/pull-ci-openshift-release-master-pj-rehearse/11253

**Comment by wking** [comment]
Rebased around #6352.  CC @AlexNPavel, so you can land this removal and stop have to worry about carrying dead code around ;).

**Comment by AlexNPavel** [comment]
@wking Rehearse not choosing any jobs right now is normal, since there are no jobs using these steps that it can test. In regards to 4.1.z not having the new gather functionality, I'll ask @stevekuznetsov about it, as I'm not quite sure how that will affect us.

**Comment by wking** [comment]
> In regards to 4.1.z not having the new gather functionality...

Just means you don't get bootstrap logs from 4.1.z tests that fail before bootstrap removal.  If that bothers folks, I think the fix is "backport the auto-gather to the installer's 4.1.z", not "write some CI hack that makes its own Terraform state assumptions".

**Comment by stevekuznetsov** [comment]
I'd love to not regress in artifacts in case that will become an issue for people working on backports -- WDYT?

**Comment by wking** [comment]
> I'd love to not regress in artifacts...

I bet we end-of-life 4.1 before we hit the next issue that would need these logs for debugging.  And if it does come up, I'm happy to volunteer to debug the issue if that allows me to not be on the hook to maintain this Terraform-state-poking crud ;).  Also, I've floated the 4.1 backport to get the installer to gather automatically (openshift/installer#2840), although that's not my backport decision to make.

**Comment by wking** [comment]
Rebased again (this time around #6429) with 06448cb9c -> 970ec020d.  If neither this PR nor the installer backport has legs with their respective maintainers, the middle ground is probably just droppping my name from `ci-operator/step-registry/ipi/deprovision/artifacts/bootstrap/OWNERS` ;).

**Pull request merged**
