### PR TITLE
Add CI for custom-resource-status

### PR DESCRIPTION
**Pull request by djzager**
Add CI for little status library.

### CODE REVIEW

**Comment by djzager** [comment]
> I think we want an OWNERS file that will enable us to make changes to this dir in the future.

Yeah. My understanding is that the OWNERS file has to be in the source project. 
Seeing that https://github.com/openshift/release/blob/master/ci-operator/config/openshift/ansible-service-broker/OWNERS is generated from https://github.com/openshift/ansible-service-broker/blob/593c28a30b24ec4e37a7ed2ea9a2fdd1ab1ff4b0/OWNERS

**Comment by mhrivnak** [comment]
Ah! So something is going to generate it here after merge? Neat.

**Pull request merged**
