### PR TITLE
installer-aro: add 4.15 branch config, remove unused main branch config

### PR DESCRIPTION
**Pull request by slintes**

### CODE REVIEW

**Comment by slintes** [comment]
this is WIP

/remove-lifecycle stale
/lifecycle frozen

**Comment by slintes** [comment]
will run new test on https://github.com/openshift/installer-aro/pull/27

/pj-rehearse ack

**Review by tiguelu — CHANGES_REQUESTED** [review]
The merge is failing with:
image

Looking at the history, it looks like the files in the job folder are auto-generated by openshift-bot. Can you remove those  2 files from the PR and we'll retry?

**Pull request merged**
