### PR TITLE
MGMT-19176: Fix operator publish step fail to mirror postgresql image

### PR DESCRIPTION
**Pull request by danmanor**
Avoid mirroring postgresql image, just grab its sha instead

link to a failing job - https://prow.ci.openshift.org/view/gs/test-platform-results/logs/branch-ci-openshift-assisted-service-release-ocm-2.11-operator-publish/1820730457130536960

depends on - https://github.com/openshift/assisted-service/pull/6956

### CODE REVIEW

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-operator-publish-verify

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-operator-publish-verify

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-operator-publish-verify

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-operator-publish-verify

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-operator-publish-verify

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-operator-publish-verify

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-operator-publish-verify

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-operator-publish-verify

**Review by CrystalChun — APPROVED** [review]
/lgtm

**Pull request merged**
