### PR TITLE
Enable TestAutoscaling for HyperShift/KubeVirt

### PR DESCRIPTION
**Pull request by orenc1**
Jira: https://issues.redhat.com/browse/CNV-31676

### CODE REVIEW

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-kubevirt-main-e2e-hypershift-kubevirt

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn

**Comment by orenc1** [comment]
nodepool and autoscaling tests were also enabled for the external workflow.
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn

**Comment by davidvossel** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn

**Review by davidvossel — COMMENTED** [review]
/approve
/lgtm
/hold

I put a hold on this because I'd like to see this test pass twice in a row. This presubmit blocks hypershift, so i like to be certain this is stable before merging.

**Comment by orenc1** [comment]
> /approve /lgtm /hold
> 
> I put a hold on this because I'd like to see this test pass twice in a row. This presubmit blocks hypershift, so i like to be certain this is stable before merging.

passed in the second time in a row

**Pull request merged**
