### PR TITLE
move build11 jobs back to build10

### PR DESCRIPTION
**Pull request by deepsm007**
Follow-up of https://github.com/openshift/ci-tools/pull/4363 

/cc @openshift/test-platform

### CODE REVIEW

**Comment by deepsm007** [comment]
Generated config will work once [this](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/branch-ci-openshift-ci-tools-master-images/1843774425674027008) postsubmit completes

**Review by wking — APPROVED** [review]
Restoring @hector-vido 's [earlier approval][1], now that this has been rebuilt after the openshift/ci-tools#4363 [postsubmit succeeded][2].

/lgtm

[1]: https://github.com/openshift/release/pull/57624#issuecomment-2400902959
[2]: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/branch-ci-openshift-ci-tools-master-images/1843774425674027008

**Pull request merged**
