### PR TITLE
Add script to collect junit and parse junit results

### PR DESCRIPTION
**Pull request by mrniranjan**

### CODE REVIEW

**Comment by mrniranjan** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-hcp-cnf-4.18-e2e-telcov10n-functional-hcp-cnf-candidate

**Comment by rshemtov13** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-hcp-cnf-4.18-e2e-telcov10n-functional-hcp-cnf-candidate

**Pull request merged**
