### PR TITLE
OPRUN-3423: Update OLMv1 jobs for GA

### PR DESCRIPTION
**Pull request by perdasilva**
Preconditions:
- [ ] [openshift/cluster-olm-operator#74](https://github.com/openshift/cluster-olm-operator/pull/74) merged

### CODE REVIEW

**Review by everettraven — APPROVED** [review]
/lgtm

**Comment by grokspawn** [comment]
/retitle OPRUN-3423: Update OLMv1 jobs for GA

**Comment by perdasilva** [comment]
Seems the NewOLM tests are passing though ^^ let's re-spin and hope for green

**Comment by LalatenduMohanty** [comment]
Removing hold as a nightly has passed all blocking jobs https://openshift-release.apps.ci.l2s4.p1.openshiftapps.com/releasestream/4.18.0-0.nightly/release/4.18.0-0.nightly-2024-11-22-231049

**Pull request merged**
