### PR TITLE
velero-plugin-for-vsm initial setup

### PR DESCRIPTION
**Pull request by hhpatel14**

### CODE REVIEW

**Comment by hhpatel14** [comment]
Uni-test logs: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/36148/rehearse-36148-pull-ci-migtools-velero-plugin-for-vsm-main-unit-test/1623072894852534272/artifacts/unit-test/unit/build-log.txt

**Comment by hhpatel14** [comment]
velero-plugin-for-vsm image logs: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/36148/rehearse-36148-pull-ci-migtools-velero-plugin-for-vsm-main-images/1623072894818979840/artifacts/build-logs/velero-plugin-for-vsm.log

**Review by droslean — APPROVED** [review]

**Pull request merged**
