### PR TITLE
MGMT-4019 Build assisted service operator bundle in prow

### PR DESCRIPTION
**Pull request by rwsu**
Adds the operator bundle image. We will use the
image later to test operator installs in prow.

### CODE REVIEW

**Comment by rwsu** [comment]
Depends on https://github.com/openshift/assisted-service/pull/1230 merging.

**Comment by rwsu** [comment]
Failed on operator-sdk download issue, will need https://github.com/openshift/assisted-service/pull/1312 to merge before retest.

**Comment by lranjbar** [comment]
It looks correct once the operator-sdk is pinned. I would check up on the docker not found failures at lines 312-323:

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/16652/rehearse-16652-pull-ci-openshift-assisted-service-master-ci-index/1371462919887261696

**Comment by YuviGold** [comment]
> It looks correct once the operator-sdk is pinned, going to need to check up on the docker not found failures at lines 312-323:
> 
> https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/16652/rehearse-16652-pull-ci-openshift-assisted-service-master-ci-index/1371462919887261696
> 
> Need to make sure it is generating the files unsure

The 312-323 is a logging error that @oshercc takes care of. This one isn't related nor blocking.
Looks good

**Comment by lranjbar** [comment]
Needs rebase but otherwise LGTM. :+1:

**Pull request merged**
