### PR TITLE
NO-ISSUE: Change OCM 2.7 periodic jobs to run once a week

### PR DESCRIPTION
**Pull request by danmanor**
Change OCM 2.7 periodic jobs to run once a week

### CODE REVIEW

**Review by osherdp — APPROVED** [review]

**Comment by danmanor** [comment]
@adriengentil @osherdp @gamli75 Do we want it to run in a specific day in the week (like Saturday) ?

**Comment by osherdp** [comment]
> @adriengentil @osherdp @gamli75 Do we want it to run in a specific day in the week (like Saturday) ?

I think it's not too critical

**Pull request merged**
