### PR TITLE
Add virt-artifacts-server to hco builds

### PR DESCRIPTION
**Pull request by erkanerol**
In https://github.com/kubevirt/hyperconverged-cluster-operator, we are introducing a new container image with PRs https://github.com/kubevirt/hyperconverged-cluster-operator/pull/1467 and https://github.com/kubevirt/hyperconverged-cluster-operator/pull/1466. We need this change to be able to get up-to-date image during tests. 

Signed-off-by: Erkan Erol <eerol@redhat.com>

### CODE REVIEW

**Comment by tiraboschi** [comment]
/hold 
waiting for https://github.com/kubevirt/hyperconverged-cluster-operator/pull/1467

**Comment by tiraboschi** [comment]
hco-e2e-image-index-azure, hco-e2e-kv-smoke-azure and hco-e2e-upgrade-index-azure are green and we have a valid explanation of why the rest is red.
/approve

**Review by tiraboschi — APPROVED** [review]

**Comment by erkanerol** [comment]
New PR: https://github.com/openshift/release/pull/21176

**Pull request closed without merging**
