### PR TITLE
add job: ocp-qe-perfscale-ci-tests-rosa-hypershift

### PR DESCRIPTION
**Pull request by LiangquanLi930**

### CODE REVIEW

**Comment by paigerube14** [comment]
@svetsa-rh PTAL. 
Thought: should we move this to a separate config to host all rosa on hypershift tests? and keep the current config for rosa specific?

**Comment by svetsa-rh** [comment]
@paigerube14 Thanks for the ping! I see functional QE has all tests listed in one high level file for their tests. Let us discuss offline how we want to organize our PerfScale tests.

**Comment by svetsa-rh** [comment]
@LiangquanLi930 Is there any specific reason why you used `rosa-aws-sts-hypershift` for provisioning this cluster instead of `rosa-aws-sts`?  Is it byoc because of prod environment?

**Comment by LiangquanLi930** [comment]
> @LiangquanLi930 Is `rosa-aws-sts-hypershift` always with byoc whether stage or production?

integration, stage and production

**Comment by LiangquanLi930** [comment]
https://issues.redhat.com/browse/OCPQE-15443

**Pull request merged**
