### PR TITLE
Add CI for oc-4.3-kubernetes-1.16.0-rc.2 k8s branches

### PR DESCRIPTION
**Pull request by soltysh**
/assign @tnozicka

### CODE REVIEW

**Comment by tnozicka** [comment]
/hold
(for rehearsals)

**Comment by tnozicka** [comment]
/approve
/lgtm
we need to start somewhere and the branches are broken

**Comment by soltysh** [comment]
Manually tagging to unblock rebase work. Also someone removed our OWNERS files :imp:

**Comment by tnozicka** [comment]
for reference this is the one to blame https://github.com/openshift/release/pull/4940

**Pull request merged**
