### PR TITLE
Add necessary bits for Vexxhost operator cluster profile

### PR DESCRIPTION
**Pull request by Sandeepyadav93**
* Add the cloud resource names into openstack-conf-resourcenames
* Add secrets into openstack-conf-clouds
* Add infos for Bosko
* Configure quotas for 2 leases (for now)

### CODE REVIEW

**Comment by jmguzik** [comment]
/hold
release when you feel it's ready

**Comment by Sandeepyadav93** [comment]
I created core-services/prow/02_config/_boskos.yaml manually, I should have used the automation "make boskos-config".

Looks like ordering matters(alphabetical) and I got the sequence wrong.

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/30774/pull-ci-openshift-release-master-boskos-config-generation/1552244526335135744

**Comment by Sandeepyadav93** [comment]
/retest

If I click on failing details for failing jobs:

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/30774/rehearse-30774-pull-ci-openshift-kuryr-kubernetes-master-e2e-openstack-kuryr/1552268975792984064

It gives "Application is not available"

**Comment by Sandeepyadav93** [comment]
@bbguimaraes @jmguzik PR is ready from my understanding, The failing jobs under pj-rehearse don't seem related to this patch but I would defer to your confirmation.

**Comment by jmguzik** [comment]
/retest
Rehearsals are just rehearsals. They do not block. I'll issue a retest since we had problems with our platform when it was spinning.

**Comment by Sandeepyadav93** [comment]
@bbguimaraes @jmguzik these rehearsal jobs failed in re-runs as well, Could you please help us in moving forward on this PRor If these failures are not related could we please merge this PR?

**Pull request merged**
