### PR TITLE
Add Disconnect & Private cluster workflow for cluster bot

### PR DESCRIPTION
**Pull request by yunjiang29**
add `cucushift-installer-rehearse-aws-usgov-ipi-disconnected-private` and `cucushift-installer-rehearse-aws-ipi-disconnected-private` for cluster bot

### CODE REVIEW

**Comment by yunjiang29** [comment]
@liangxia PTAL.

**Comment by liangxia** [comment]
Duplicate with https://github.com/openshift/release/pull/32744

**Comment by yunjiang29** [comment]
@liangxia thanks, closing this PR.

**Pull request closed without merging**
