### PR TITLE
hypershift: merge test step

### PR DESCRIPTION
**Pull request by LiangquanLi930**
merge test steps

### CODE REVIEW

**Comment by jianzhangbjz** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-ovn-kubevirt-hypershift-guest-p2-f14

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-ovn-hypershift-guest-p2-f14

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-ovn-hypershift-guest-p1-f7

**Comment by jianzhangbjz** [comment]
Failed to create the hosted cluster: https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/37927/rehearse-37927-periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-ovn-kubevirt-hypershift-guest-p2-f14/1641732156000571392/artifacts/aws-ipi-ovn-kubevirt-hypershift-guest-p2-f14/create-hostedcluster/build-log.txt
```yaml
+ echo '2023-03-31 11:28:57+00:00 Nested cluster'\''s node count is not equal to the desired replicas in the NodePool. Retrying in 30 seconds.'
2023-03-31 11:28:57+00:00 Nested cluster's node count is not equal to the desired replicas in the NodePool. Retrying in 30 seconds.
+ oc get vmi -n clusters-71b62e462ef83d4a608a
NAME                         AGE   PHASE     IP            NODENAME                      READY
71b62e462ef83d4a608a-84jm9   62m   Running   10.129.2.82   ip-10-0-145-72.ec2.internal   True
71b62e462ef83d4a608a-gsclp   62m   Running   10.131.0.46   ip-10-0-226-57.ec2.internal   True
71b62e462ef83d4a608a-svtvb   62m   Running   10.128.2.34   ip-10-0-141-41.ec2.internal   True
+ sleep 30s
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:254","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process did not exit before 5m0s grace period","severity":"error","time":"2023-03-31T11:29:13Z"}
```

**Comment by LiangquanLi930** [comment]
> kubevirt-hypershift-guest-p2-f14/1641732156000571392/artifacts/aws-ipi-ovn-kubevirt-hypershift-guest-p2-f14/create-hostedcluster/build-log.txt



> Failed to create the hosted cluster: https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/37927/rehearse-37927-periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-ovn-kubevirt-hypershift-guest-p2-f14/1641732156000571392/artifacts/aws-ipi-ovn-kubevirt-hypershift-guest-p2-f14/create-hostedcluster/build-log.txt
> 
> ```yaml
> + echo '2023-03-31 11:28:57+00:00 Nested cluster'\''s node count is not equal to the desired replicas in the NodePool. Retrying in 30 seconds.'
> 2023-03-31 11:28:57+00:00 Nested cluster's node count is not equal to the desired replicas in the NodePool. Retrying in 30 seconds.
> + oc get vmi -n clusters-71b62e462ef83d4a608a
> NAME                         AGE   PHASE     IP            NODENAME                      READY
> 71b62e462ef83d4a608a-84jm9   62m   Running   10.129.2.82   ip-10-0-145-72.ec2.internal   True
> 71b62e462ef83d4a608a-gsclp   62m   Running   10.131.0.46   ip-10-0-226-57.ec2.internal   True
> 71b62e462ef83d4a608a-svtvb   62m   Running   10.128.2.34   ip-10-0-141-41.ec2.internal   True
> + sleep 30s
> {"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:254","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process did not exit before 5m0s grace period","severity":"error","time":"2023-03-31T11:29:13Z"}
> ```

@jianzhangbjz  Thanks for your reminder, For hypershift kubevirt currently 4.13 is not GA, and our main change is the merge test step, for this failed, I will create other PR to fix it, so we can ignore

**Comment by LiangquanLi930** [comment]
https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/37927/rehearse-37927-periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-ovn-hypershift-guest-p1-f7/1641787859234983936/artifacts/aws-ipi-ovn-hypershift-guest-p1-f7/idp-htpasswd/build-log.txt

This log can verify that there is no problem with the change

**Pull request merged**
