### PR TITLE
BM CPT: Add OCP 4.17

### PR DESCRIPTION
**Pull request by josecastillolema**
| job           | ocp  | build | cron       |
|---------------|------|-------|------------|
| weekly-6nodes | 4.14 | ga    | Tuesdays   |
| weekly-6nodes | 4.16 | ga    | Sundays    |
| weekly-6nodes | 4.17 | ga    | Wednesdays |
| weekly-6nodes | 4.18 | dev   | Thursdays  |

### CODE REVIEW

**Comment by josecastillolema** [comment]
/pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.17-latest-x86-deploy-sno

**Comment by josecastillolema** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.17-latest-x86-deploy-sno

**Review by rsevilla87 — APPROVED** [review]
/lgtm

**Pull request merged**
