### PR TITLE
RHOSDT 3.4 disconnected

### PR DESCRIPTION
**Pull request by IshwarKanse**

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-distributed-tracing-qe-main-ocp-4.15-disconnected-distributed-tracing-tests-disconnected

**Comment by IshwarKanse** [comment]
pull-ci-openshift-distributed-tracing-qe-main-ocp-4.15-disconnected-distributed-tracing-tests-disconnected

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-distributed-tracing-qe-main-ocp-4.15-disconnected-distributed-tracing-tests-disconnected

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-distributed-tracing-qe-main-ocp-4.15-disconnected-distributed-tracing-tests-disconnected

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-distributed-tracing-qe-main-ocp-4.15-disconnected-distributed-tracing-tests-disconnected

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-distributed-tracing-qe-main-ocp-4.15-disconnected-distributed-tracing-tests-disconnected

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-distributed-tracing-qe-main-ocp-4.15-disconnected-distributed-tracing-tests-disconnected

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-distributed-tracing-qe-main-ocp-4.15-disconnected-distributed-tracing-tests-disconnected

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-distributed-tracing-qe-main-ocp-4.15-disconnected-distributed-tracing-tests-disconnected

**Comment by IshwarKanse** [comment]
Tested the disconnected tests on local env. For the automation, we need to update the job for Konflux using brew registry. Apparently with oc mirror we cannot set static catalogsourcename without messing with the registry path. I'll check with the oc mirror team on this.

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-distributed-tracing-qe-main-ocp-4.15-disconnected-distributed-tracing-tests-disconnected

**Review by vprashar2929 — APPROVED** [review]
/lgtm

**Pull request merged**
