### PR TITLE
Change docker log driver to jsonfile

### PR DESCRIPTION
**Pull request by soltysh**
@smarterclayton || @stevekuznetsov ptal

### CODE REVIEW

**Comment by smarterclayton** [comment]
I have a question.  Why aren't we just setting the default in ansible?

**Comment by sdodson** [comment]
> I have a question. Why aren't we just setting the default in ansible?

Master openshift-ansible does not set a default so you get whatever default docker provides, in 1.12 that appears to set journald in /etc/sysconfig/docker. In 1.13 that's unset so it'd be json-file.
release-3.7, release-3.6, release-1.5,  openshift-ansible sets the log-driver to journald by default.
release-1.4 and earlier set a default of json-file.

**Comment by soltysh** [comment]
> In 1.13 that's unset so it'd be json-file.

I'll re-check it in the both linked PRs and I'll close this pr if that's the case.

**Pull request closed without merging**
