### PR TITLE
NTO-PAO: add QE cherry-pick approver

### PR DESCRIPTION
**Pull request by shajmakh**
Add mrniranjan to be among the users to approve PAO related cherry-picks using label "cherry-pick-approved".

Signed-off-by: shereenH <shajmakh@redhat.com>

### CODE REVIEW

**Comment by shajmakh** [comment]
cc @mrniranjan

**Comment by shajmakh** [comment]
cc @MarSik @jmencak

**Comment by fromanirh** [comment]
/lgtm
/hold
leaving to @jmencak to approve and unhold (or not!)

**Comment by jmencak** [comment]
Thank you for the PR!
/hold cancel

**Pull request merged**
