### PR TITLE
Trigger cnv 2.6 deploy and test from nightly

### PR DESCRIPTION
**Pull request by dhiller**
This contains the work to create a presubmit job that will be triggered on changes within the [cnv-ci](https://github.com/openshift-cnv/cnv-ci) repository. That repo contains the mapping of cnv versions against the cvp nightly builds and other resources like scripts and manifests required to test cnv on ocp.

### CODE REVIEW

**Comment by dhiller** [comment]
/cc @orenc1 

This is the test config where the job will be run from.

**Comment by orenc1** [comment]
looks like cluster bootstrap issue on azure.

/retest

**Comment by orenc1** [comment]
```
level=error msg=Cluster operator console Degraded is True with RouteHealth_FailedGet: RouteHealthDegraded: failed to GET route (https://console-openshift-console.apps.ci-op-1yqjhhhn-d12a6.ci.azure.devcluster.openshift.com/health): Get "https://console-openshift-console.apps.ci-op-1yqjhhhn-d12a6.ci.azure.devcluster.openshift.com/health": dial tcp: lookup console-openshift-console.apps.ci-op-1yqjhhhn-d12a6.ci.azure.devcluster.openshift.com on 172.30.0.10:53: no such host
```
/retest

**Comment by dhiller** [comment]
@orenc1 TBH I don't want to wait on a successful run as we had a couple of infra issues already. I think we are just good here. Feel free to review and give your OK ;-)

**Comment by orenc1** [comment]
> @orenc1 TBH I don't want to wait on a successful run as we had a couple of infra issues already. I think we are just good here. Feel free to review and give your OK ;-)

OK, let's merge it.
/lgtm

> @orenc1 TBH I don't want to wait on a successful run as we had a couple of infra issues already. I think we are just good here. Feel free to review and give your OK ;-)

OK, let's merge it :)
/lgtm

**Pull request merged**
