### PR TITLE
Telco operators DAST  testing CI 

### PR DESCRIPTION
**Pull request by obochan-rh**

### CODE REVIEW

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
pj-rehearse abort

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Comment by obochan-rh** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-telco-operators-dast-4.16-telco-dast-ci

**Review by shaior — APPROVED** [review]
/pj-rehearse ack
/lgtm

good job

**Pull request merged**
