### PR TITLE
openstack-gather: Add floating IP information

### PR DESCRIPTION
**Pull request by pierreprinetti**

### CODE REVIEW

**Comment by pierreprinetti** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.13-e2e-openstack-proxy

**Comment by pierreprinetti** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.12-e2e-openstack-ovn-serial

**Comment by pierreprinetti** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.13-e2e-openstack-proxy periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.12-e2e-openstack-ovn-serial

**Review by mandre — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
