### PR TITLE
add cluster/test-deploy/azure

### PR DESCRIPTION
**Pull request by jim-minter**

### CODE REVIEW

**Comment by jim-minter** [comment]
@kargakis @smarterclayton  I believe this can go in now that https://github.com/openshift/openshift-ansible/pull/8257 is merged.  ptal / please merge if happy

**Comment by kargakis** [comment]
Is this going to break testing on release-3.7? 

@smarterclayton any comments?

**Comment by kargakis** [comment]
3.9 is already covered and entrypoint-gcp is now a wrapper of entrypoint-provider in openshift-ansible 3.9/master.

**Comment by kargakis** [comment]
I am going to babysit, @jim-minter can also keep an eye

**Pull request merged**
