### PR TITLE
add must-gather output to collected artifacts

### PR DESCRIPTION
**Pull request by sanchezl**
Runs must-gather.

### CODE REVIEW

**Comment by deads2k** [comment]
Looks plausible. 

/lgtm

**Comment by sdodson** [comment]
/cc @wking 
need installer-approver approval

**Comment by wking** [comment]
This is just additive?  I'd expect we could drop some of our local ad-hoc stuff when adopting must-gather.

**Comment by deads2k** [comment]
> This is just additive? I'd expect we could drop some of our local ad-hoc stuff when adopting must-gather.

We are adding it first to get comfort that it works.  Then we'll work on stabilizing the base, adding more tests, then we'll remove the duplicates.

**Comment by sanchezl** [comment]
> This is just additive? I'd expect we could drop some of our local ad-hoc stuff when adopting must-gather.

We don't want to drop any of the ad-hoc stuff until after this has been running for a bit and we are even more confident that there are no issues. I don't want to risk leaving us in the dark.

**Comment by wking** [comment]
If this is a trial run, you probably only need to touch `cluster-launch-installer-e2e.yaml`.  If we want to roll this out across CI, you'll want to touch all of the various e2e templates:

```console
$ git grep -c 'install-config.yaml' origin/master -- ci-operator | grep -v ':0$'
origin/master:ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml:1
origin/master:ci-operator/templates/openshift/installer/cluster-launch-installer-metal-e2e.yaml:1
origin/master:ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml:1
origin/master:ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml:2
origin/master:ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml:2
origin/master:ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-40.yaml:4
origin/master:ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml:2
```

As it stands, you're only touching three.  Or does must-gather not work on metal, OpenStack, etc.?

**Comment by deads2k** [comment]
> As it stands, you're only touching three. Or does must-gather not work on metal, OpenStack, etc.?

We aren't very CI aware.  Where are those?  We'd like to see if we have the right information before switching, so unless there's a reason to stop this rolling out to multiple jobs, I'd like to see it start landing

**Comment by sanchezl** [comment]
> If we want to roll this out across CI, you'll want to touch all of the various e2e templates:

Done

**Comment by deads2k** [comment]
@wking well, the must-gather bits appeared to run, but the tests we added them to are red....


/retest

**Comment by deads2k** [comment]
@wking we tried, CI on stale jobs failed.  We're reverting to what worked and merged.  We've suffered without the elided secrets for a week and cannot reasonably wait longer.

**Pull request merged**
