### PR TITLE
hypershift, kubevirt: Add dev-scripts to presubmit

### PR DESCRIPTION
**Pull request by qinqon**

### CODE REVIEW

**Comment by qinqon** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-metal-conformance

**Comment by qinqon** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-metal-conformance

**Review by nunnatsa — APPROVED** [review]
/approve
/lgtm

**Comment by qinqon** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-metal-conformance

**Review by davidvossel — COMMENTED** [review]
/approve

**Pull request merged**
