### PR TITLE
Add mirroring for GCP PD CSI Driver and Operator

### PR DESCRIPTION
**Pull request by bertinatto**
GCP PD CSI Driver Operator is going to be Tech Preview in OCP 4.7.

xref: https://issues.redhat.com/browse/STOR-363

CC @openshift/storage 
/assign @smarterclayton

### CODE REVIEW

**Comment by jsafrane** [comment]
Please update mapping_origin_4_8 too

**Comment by bertinatto** [comment]
Updated

**Comment by jsafrane** [comment]
/lgtm
@smarterclayton PTAL.

**Comment by bertinatto** [comment]
/close

There's a script to re-generate these files, and it has bee updated (along with these mappings) in https://github.com/openshift/release/pull/13770.

**Pull request closed without merging**
