### PR TITLE
aws-ipi-disconnected-sts-ep install debug

### PR DESCRIPTION
**Pull request by ming1013**

### CODE REVIEW

**Comment by ming1013** [comment]
/hold
Don't merge

**Comment by ming1013** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.11-arm64-stable-aws-ipi-disconnected-sts-ep-f28

**Comment by ming1013** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.11-arm64-stable-aws-ipi-disconnected-sts-ep-f28

**Comment by gpei** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.11-installer-rehearse-debug

**Comment by ming1013** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.11-installer-rehearse-debug

**Comment by ming1013** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.11-installer-rehearse-debug

**Pull request closed without merging**
