### PR TITLE
Use cluster_groups in config-updater's config

### PR DESCRIPTION
**Pull request by hongkailiu**
1. @alvaroaleman introduced this cool feature https://github.com/kubernetes/test-infra/pull/19006/files which we have not used yet.
2. This simplifies https://issues.redhat.com/browse/DPTP-2597

/cc @openshift/test-platform

### CODE REVIEW

**Comment by hongkailiu** [comment]
Not cool.

https://github.com/kubernetes/test-infra/blob/40d2900a41d5daeb84ba2e11d027e6d68b56403e/prow/plugins/config.go#L533

Resolved upon unmarshal.

Need to figure this out.

**Review by droslean — APPROVED** [review]

**Comment by hongkailiu** [comment]
/hold cancel

I will watch if we have the CMs created on b04.

**Pull request merged**
