### PR TITLE
[kubevirt - kubevirt-tekton-tasks-operator] onboard kubevirt-tekton-tasks-operator project

### PR DESCRIPTION
**Pull request by ksimon1**
this operator is used to deploy kubevirt tekton tasks and pipelines
(https://github.com/kubevirt/kubevirt-tekton-tasks).

/cc @akrejcir, @0xFelix 
Signed-off-by: Karel Šimon <ksimon@redhat.com>

### CODE REVIEW

**Comment by hongkailiu** [comment]
/lgtm

This should not be necessary on this repo. But Prow was facing issues this morning. Let us try again.

**Comment by petr-muller** [comment]
@hongkailiu LGTM is always required. onboarding is just auto-approved (which worked)

**Pull request merged**
