### PR TITLE
Reconfigure RPM repos to use separate mounts

### PR DESCRIPTION
**Pull request by stevekuznetsov**
The repository config is in the `base-repos` ConfigMap and we get the
ops-mirror key from a secret.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/cc @tbielawa @jupierce

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
The second commit here is the interesting one.

**Comment by tbielawa** [comment]
This seems to line up with what we discussed in the meeting earlier, however I'm not expert enough to give it an official `/lgtm`

**Comment by stevekuznetsov** [comment]
I will merge this later tonight when I have a chance to watch it deploy and revert if needed.

**Comment by stevekuznetsov** [comment]
@jupierce could you commit to validating the behavior is correct if we merge this today?

**Comment by stevekuznetsov** [comment]
@jupierce could you commit to validating the behavior is correct if we merge this today?

**Pull request merged**
