### PR TITLE
Add cherrypick endpoint to podman-py

### PR DESCRIPTION
**Pull request by umohnani8**

### CODE REVIEW

**Comment by umohnani8** [comment]
@rhatdan @giuseppe PTAL

**Comment by lsm5** [comment]
@umohnani8 looks like this commit created a bunch of additional openshift tasks? Is that the expected result? Might be worth mentioning in the commit message for others (like me) to understand. Other than that, LGTM.

**Comment by lsm5** [comment]
> @umohnani8 looks like this commit created a bunch of additional openshift tasks? Is that the expected result? Might be worth mentioning in the commit message for others (like me) to understand. Other than that, LGTM.

ohh, it's openshift release repo. Ok lol. My bad.

**Comment by lsm5** [comment]
ah, ok so we want to be able to `slash-cherrypick $FOO_BRANCH`, that's what this does, right? LGTM. Do we also need to separately account for `cherry-pick`  or is that automatically handled with this?

**Pull request merged**
