### PR TITLE
MULTIARCH-4696: security group and point to the right id_rsa path

### PR DESCRIPTION
**Pull request by prb112**

### CODE REVIEW

**Comment by prb112** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.18-ocp-e2e-powervs-ovn-multi-p-px

**Comment by prb112** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.18-ocp-e2e-powervs-ovn-multi-p-px

**Comment by prb112** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.18-ocp-e2e-powervs-ovn-multi-p-px

**Review by pkenchap — APPROVED** [review]

**Pull request merged**
