### PR TITLE
Add NTO nightly testing on OCP 4.6 and 4.7

### PR DESCRIPTION
**Pull request by kpouget**
This PR adds NTO nightly testing on Prow configuration files.

It will run make test-e2e from these branches:

    https://github.com/openshift/cluster-node-tuning-operator/tree/release-4.6
    https://github.com/openshift/cluster-node-tuning-operator/tree/release-4.7

against the latest nightly release of OpenShift,
every Sunday at midnight.

---

This PR is another try for https://github.com/openshift/release/pull/17020 that was revert in https://github.com/openshift/release/pull/17046
because of this error:
```
error: invalid configuration: tests[5].literal_steps.pre[5].dependencies[0]: cannot determine source for dependency "release:initial" - this dependency requires a "initial" release, which is not configured
```

### CODE REVIEW

**Comment by kpouget** [comment]
\uncc @ArangoGutierrez
\uncc @sjug

\assign @jmencak

**Comment by kpouget** [comment]
hey @jmencak do you have any clue what is going wrong here?
should we try again and again until it passes, or is there something more serious?

**Comment by jmencak** [comment]
> hey @jmencak do you have any clue what is going wrong here?
> should we try again and again until it passes, or is there something more serious?

So these failing tests are not "Required" and I don't think I've ever seen all tests pass when interacting with/merging into `openshift/release`.  Unfortunately, I cannot remember the set of tests passing/failing last time I merged and things worked well and the job history of that latest PR is already deleted.  So, there is probably only one way to tell and see if this really works. :)

**Comment by kpouget** [comment]
@jmencak I removed the `WIP` label, I'll let you confirm if this PR is good to go, in particular wrt. the tests failing the rehearsal

**Comment by kpouget** [comment]
@jmencak should we close this one?

**Comment by jmencak** [comment]
Yes, I believe so, @kpouget .  Let's close it.  Many thanks for your effort and help!  It has been replaced by https://github.com/openshift-psap/ci-artifacts/pull/185 and https://github.com/openshift/release/pull/19129

**Pull request closed without merging**
