### PR TITLE
[INTEROP-7554] Increase node size for Quay on OCP 4.18 interop tests.

### PR DESCRIPTION
**Pull request by dfrazzette**
Changed `COMPUTE_NODE_TYPE` to resolve OOM error; also reverted cluster_profile and BASE_DOMAIN for non-interop jobs.

### CODE REVIEW

**Comment by dfrazzette** [comment]
/pj-rehearse periodic-ci-quay-quay-tests-master-ocp-418-quay-quay-e2e-tests-quay313-ocp418-lp-interop periodic-ci-quay-quay-tests-master-ocp-418-quay-quay-e2e-tests-quay313-ocp418-lp-interop-fips

**Review by Simranpal — APPROVED** [review]
/lgtm

**Pull request merged**
