### PR TITLE
ci-operator/step-registry/openshift/e2e/test: JUnits for ImportStream failures

### PR DESCRIPTION
**Pull request by wking**
Make it easier to root-cause issues [like][1]:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.11-e2e-azure-csi/1546489885890711552/artifacts/e2e-azure-csi/gather-must-gather/artifacts/must-gather.tar | tar xOz quay-io-openshift-release-dev-ocp-v4-0-art-dev-sha256-88d9b350be62e6314c2602112467e082bbf7d4c1538ae6a096c303d78ed5326f/namespaces/openshift/image.openshift.io/imagestreams/redhat-openjdk18-openshift.yaml | yaml2json | jq -r '.status.tags[] | (.conditions // [])[] | .lastTransitionTime + " " + .type + "=" + .status + " " + .reason + ": " + .message'
2022-07-11T14:11:12Z ImportSuccess=False InternalError: Internal error occurred: registry.redhat.io/redhat-openjdk-18/openjdk18-openshift:1.0: unsupported: V2 schema 1 manifest digests are no longer supported for image pulls. Use the equivalent V2 schema 2 manifest digest instead. For more information see https://access.redhat.com/articles/6138332
2022-07-11T14:11:12Z ImportSuccess=False InternalError: Internal error occurred: registry.redhat.io/redhat-openjdk-18/openjdk18-openshift:1.1: unsupported: V2 schema 1 manifest digests are no longer supported for image pulls. Use the equivalent V2 schema 2 manifest digest instead. For more information see https://access.redhat.com/articles/6138332
2022-07-11T14:11:12Z ImportSuccess=False InternalError: Internal error occurred: registry.redhat.io/redhat-openjdk-18/openjdk18-openshift:1.2: unsupported: V2 schema 1 manifest digests are no longer supported for image pulls. Use the equivalent V2 schema 2 manifest digest instead. For more information see https://access.redhat.com/articles/6138332
```

by wrapping each failed tag in a JUnit test case and including the error message.  That will expose the failure messages to users curious about why their run failed, and also to aggregation tooling like [CI-search][2].

One testsuite for all the tags would have been nice, but seemed like more trouble than it was worth.

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=2106163#c0
[2]: https://search.ci.openshift.org/

### CODE REVIEW

**Comment by wking** [comment]
Hrm, [e2e-vsphere-ccm failed on ImageStream import][1], but for some reason the a471f60964 logic didn't create any JUnits.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/30363/rehearse-30363-pull-ci-openshift-cluster-cloud-controller-manager-operator-master-e2e-vsphere-ccm/1546639271903891456

**Comment by wking** [comment]
[Hooray][1]:

image

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/30363/rehearse-30363-pull-ci-openshift-cluster-kube-scheduler-operator-master-e2e-aws/1546671349768916992

**Comment by wking** [comment]
I've pushed 6497d89ac4b -> 39a48f23826 to fix the redundant `openshift/openshift/...` and to include the tag name as well as the ImageStream name.

**Comment by stbenjam** [comment]
Would it be possible to roll them all up into a single junit like "Image imports should succeed" that summarizes all the failures, and passes if there aren't any?

We've tried to get away from only adding test cases that fail, since they don't work well in job aggregation, and also always appear to permafail in sippy.

**Comment by wking** [comment]
Current JUnit includes the tag name and removes the doubled namespace, [like][1]:

image

Having a JUnit that passes when the image stream successfully imports should be possible, but might require some more shell ugliness.  Thoughts about getting this logic up out of the shell and into an `Early` openshift/origin test-case?

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/30363/rehearse-30363-pull-ci-openshift-aws-ebs-csi-driver-release-4.5-e2e-aws-csi/1546762535288442880

**Pull request closed without merging**
