### PR TITLE
NO-ISSUE: Increase IOPS and throughput

### PR DESCRIPTION
**Pull request by pmtk**

### CODE REVIEW

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-metal-periodic-test-arm pull-ci-openshift-microshift-main-metal-bootc-test-arm

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-metal-tests pull-ci-openshift-microshift-main-microshift-metal-tests-arm

**Review by pacevedom — APPROVED** [review]
/lgtm

**Pull request merged**
