### PR TITLE
MetalLB Operator: publish the bundle to the CI registry

### PR DESCRIPTION
**Pull request by fedepaol**
Doing back to 4.12 so we can test upgrades.

### CODE REVIEW

**Comment by fedepaol** [comment]
/hold 
depends on https://github.com/openshift/release/pull/41495 where we push the bundle to the ci registry

**Comment by fedepaol** [comment]
/pj-rehearse pull-ci-openshift-metallb-operator-release-4.13-images

**Comment by fedepaol** [comment]
/pj-rehearse pull-ci-openshift-metallb-operator-release-4.13-operator-e2e

**Review by dhellmann — COMMENTED** [review]
/approve

I'll leave the lgtm to a member of your team.

**Pull request merged**
