### PR TITLE
MCO-561: rhcos-image-layering-examples: bootstrapping configuration for the repo

### PR DESCRIPTION
**Pull request by sinnykumari**
Ran `make repo` to generate initial configs.
Running containerlinter as part of initial test
Doc: https://docs.ci.openshift.org/docs/how-tos/onboarding-a-new-component/#bootstrapping-configuration-for-a-new-repository

### CODE REVIEW

**Comment by sinnykumari** [comment]
Requires https://github.com/openshift/rhcos-image-layering-examples/pull/11

**Comment by sinnykumari** [comment]
correctly-sharded-config  seems to be failing because it matches two configmap `ci-operator/jobs/**/*master-presubmits.yaml` and `"ci-operator/jobs/**/*-layering-*.yaml\"` 

@cheesesashimi Do you know if https://github.com/openshift/release/blob/master/core-services/prow/02_config/_plugins.yaml#L371 is still in use or possible to change the regex little bit so that it doesn't match with file `openshift-rhcos-image-layering-examples-master-presubmits.yaml`

**Comment by sinnykumari** [comment]
Full error is in build log https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/39231/pull-ci-openshift-release-master-correctly-sharded-config/1656647143722586112/build-log.txt

**Comment by cheesesashimi** [comment]
The files that this regex would match are no longer present within `openshift/release`, so I think we can completely do away with those entries in https://github.com/openshift/release/blob/master/core-services/prow/02_config/_plugins.yaml#L371.

**Comment by sinnykumari** [comment]
Thanks Zack, pushed commit here to remove unused layering job references

**Comment by sinnykumari** [comment]
Tests are passing now, tagging for further review and lgtm/approval on this PR
@cheesesashimi @cgwalters @danilo-gemoli

**Pull request merged**
