### PR TITLE
Add e2e Azure UPI upgrade tests

### PR DESCRIPTION
**Pull request by aleskandro**
This PR introduces upgrades QE tests for Azure UPI on ARM64

Closes [ARMOCP-488](https://issues.redhat.com//browse/ARMOCP-488)

### CODE REVIEW

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-4.13-upgrade-from-stable-4.12-azure-upi-p3-f28

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-4.13-upgrade-from-stable-4.12-azure-upi-p3-f28

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-ec-4.13-azure-upi-p3-f28

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-ec-4.13-azure-upi-p3-f28

**Comment by droslean** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-4.13-upgrade-from-ec-4.13-azure-upi-p3-f28

**Review by droslean — APPROVED** [review]

**Comment by aleskandro** [comment]
Instellation and upgrade passed at https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/36348/rehearse-36348-periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-4.13-upgrade-from-ec-4.13-azure-upi-p3-f28/1625429397232160768

**Pull request merged**
