### PR TITLE
Add release 4.2 config for ironic-inspector

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Comment by russellb** [comment]
Please add the OWNERS files

**Comment by russellb** [comment]
and you have the release-4.2 config, but what about master?

and how about prow config?

**Comment by elfosardo** [comment]
@russellb this is just for release 4.2
master and OWNERS were already added

**Comment by russellb** [comment]
ah, missed that already merging, thanks

/lgtm

**Pull request merged**
