### PR TITLE
[SSP-operator] Adding user to subuid

### PR DESCRIPTION
**Pull request by assafad**
Adding user to subuid within unittest in kubevirt-ssp-operator-main.yaml.

### CODE REVIEW

**Comment by lyarwood** [comment]
@assafad Stupid question but why do we suddenly need this? There's no justification in the PR description or commit message.

**Comment by 0xFelix** [comment]
@lyarwood Assaf got in contact with me to try fixing https://github.com/kubevirt/ssp-operator/pull/621, this was my suggestion after also talking to Karel. But yeah, would be good to add a ref to the initial PR.

**Comment by lyarwood** [comment]
I wonder if we just need the `preset-podman-in-container-enabled: true` label enabled here as we use downstream to enable the use of podman within these containers.

**Pull request closed without merging**
