### PR TITLE
OCPQE-6256: Add destructive cucushift tests for azure-ipi

### PR DESCRIPTION
**Pull request by liangxia**
/cc @JianLi-RH @dis016 @pruan-rht @jhou1

### CODE REVIEW

**Review by dis016 — COMMENTED** [review]
/lgtm

**Comment by jhou1** [comment]
Thank you, Liang.

Looks like we need to enable destructive jobs more slowly. The current number of failures is more than we can handle.

/hold

**Comment by liangxia** [comment]
Rebase to resolve conflicts.

**Pull request closed without merging**
