### PR TITLE
Add workflow for CSI migration tests

### PR DESCRIPTION
**Pull request by jsafrane**
`openshift-e2e-aws-csi-migration` workflow runs conformance/parallel tests on AWS with CSI migration enabled. Using AWS EBS operator job for rehearsal, in the end we will probably want a periodic one.

New `openshift-e2e-aws-csi-migration` workflow, which enables  TechPreviewNoUpgrade  (storage-conf-feature-gate step) and waits for everything to be restarted (storage-conf-wait-for-csi-migration) and finally runs e2e tests, which include in-tree AWS volume tests.

### CODE REVIEW

**Comment by jsafrane** [comment]
cc @openshift/storage

**Comment by jsafrane** [comment]
Hmm, back to the drawing board, enabling TechPreviewNoUpgrade does not enable the migration.

**Comment by jsafrane** [comment]
CSI migration itself is enabled and at least the external-provisioner provisions CSI volumes:

```
I0414 21:04:09.841229       1 controller.go:1335] provision "e2e-pvc-protection-3868/pvc-protectiongttlc" class "gp2": started
I0414 21:04:09.841451       1 controller.go:511] translating storage class for in-tree plugin kubernetes.io/aws-ebs to CSI
I0414 21:04:09.841541       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"e2e-pvc-protection-3868", Name:"pvc-protectiongttlc", UID:"154ce09a-eb38-4514-8ef0-10d8603da2bc", APIVersion:"v1", ResourceVersion:"43942", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "e2e-pvc-protection-3868/pvc-protectiongttlc"
I0414 21:04:13.363421       1 controller.go:838] successfully created PV pvc-154ce09a-eb38-4514-8ef0-10d8603da2bc for PVC pvc-protectiongttlc and csi volume name vol-01fd176ef60e94b26
I0414 21:04:13.367064       1 controller.go:1442] provision "e2e-pvc-protection-3868/pvc-protectiongttlc" class "gp2": volume "pvc-154ce09a-eb38-4514-8ef0-10d8603da2bc" provisioned
I0414 21:04:13.367111       1 controller.go:1459] provision "e2e-pvc-protection-3868/pvc-protectiongttlc" class "gp2": succeeded
```

However, there are some failures we need to tolerate:

1. `TechPreviewNoUpgrade` fires an alert:
```
fail [github.com/onsi/ginkgo@v4.7.0-origin.0+incompatible/internal/leafnodes/runner.go:113]: Apr 14 21:29:33.732: Unexpected alerts fired or pending after the test run:

alert TechPreviewNoUpgrade fired for 1349 seconds with labels: {container="kube-apiserver-operator", endpoint="https", instance="10.130.0.26:8443", job="metrics", name="TechPreviewNoUpgrade", namespace="openshift-kube-apiserver-operator", pod="kube-apiserver-operator-5878c6b8df-sc7zl", service="metrics", severity="warning"}
```

2. Managed cluster should start all core operators:
```
fail [github.com/onsi/ginkgo@v4.7.0-origin.0+incompatible/internal/leafnodes/runner.go:113]: Apr 14 21:03:47.321: Some cluster operators are not ready: authentication (Degraded=True OAuthServerDeployment_UnavailablePod: OAuthServerDeploymentDegraded: 1 of 3 requested instances are unavailable for oauth-openshift.openshift-authentication (container is waiting in pending oauth-openshift-688b769d74-cb8x6 pod)), kube-apiserver (Upgradeable=False FeatureGates_RestrictedFeatureGates_TechPreviewNoUpgrade: FeatureGatesUpgradeable: "TechPreviewNoUpgrade" does not allow updates)
```
Not sure what's wrong with `authentication` operator, but having `kube-apiserver` `Upgradeable=False` is expected and should be tolerated somehow.

**Comment by jsafrane** [comment]
vsphere-csi passed !?

The other jobs are as flaky as they were before.

**Comment by bertinatto** [comment]
3 out of 4 remaining failing tests are volume expansion:

```
External Storage [Driver: disk.csi.azure.com] [Testpattern: Dynamic  Snapshot (retain policy)]  snapshottable[Feature:VolumeSnapshotDataSource] volume snapshot  controller  should check snapshot fields, check restore correctly works  after modifying source data, check deletion
External Storage [Driver: disk.csi.azure.com] [Testpattern: Dynamic PV  (block volmode)(allowExpansion)] volume-expand should resize volume when  PVC is edited while pod is using it 
External Storage [Driver: disk.csi.azure.com] [Testpattern: Dynamic PV  (default fs)(allowExpansion)] volume-expand Verify if offline PVC  expansion works
External Storage [Driver: disk.csi.azure.com] [Testpattern: Dynamic PV  (default fs)(allowExpansion)] volume-expand should resize volume when  PVC is edited while pod is using it

```
I'm checking a potential fix for those failures here: https://github.com/openshift/azure-disk-csi-driver/pull/5

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Pull request merged**
