### PR TITLE
init

### PR DESCRIPTION
**Pull request by AsherShoshan**

### CODE REVIEW

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-rhcs-rosa-main-tmp

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-rhcs-rosa-main-tmp

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-rhcs-rosa-main-tmp

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-rhcs-rosa-main-tmp

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-rhcs-rosa-main-tmp

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-rhcs-rosa-main-tmp

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-rhcs-rosa-main-tmp

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-rhcs-rosa-main-tmp

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-rhcs-rosa-main-tmp

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-rhcs-rosa-main-tmp

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-rhcs-rosa-main-tmp

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-rhcs-rosa-main-tmp

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-rhcs-rosa-main-tmp

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-rhcs-rosa-main-tmp

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-rhcs-rosa-main-tmp

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-rhcs-rosa-main-tmp

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-rhcs-rosa-main-tmp

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-rhcs-rosa-main-tmp

**Comment by nirarg** [comment]
@AsherShoshan can this PR be closed?

**Pull request closed without merging**
