### PR TITLE
Premerge job: Change to run cases with source code

### PR DESCRIPTION
**Pull request by lihongyan1**
Run cases with source code to get the code change about test cases when add new test cases or fix a case issue

### CODE REVIEW

**Comment by lihongyan1** [comment]
/pj-rehearse pull-ci-rhobs-observability-operator-main-observability-operator-e2e

**Comment by lihongyan1** [comment]
/pj-rehearse pull-ci-rhobs-observability-operator-main-observability-operator-e2e

**Comment by lihongyan1** [comment]
/pj-rehearse pull-ci-rhobs-observability-operator-main-observability-operator-e2e

**Comment by lihongyan1** [comment]
@jan--f Please help review

**Comment by jan--f** [comment]
I guess the test harness is still used in the periodic runs?

In any case this
/lgtm

**Comment by lihongyan1** [comment]
> I guess the test harness is still used in the periodic runs?
> 
> In any case this /lgtm

Yes, test harness is still used in the periodic runs and osd job

**Pull request merged**
