### PR TITLE
Add test for etcd-quorum-guard

### PR DESCRIPTION
**Pull request by RobertKrawitz**
Add test for etcd-quorum-guard

### CODE REVIEW

**Comment by sjenning** [comment]
I was trying to figure out this
```
/bin/bash: line 64: make: command not found
```
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_release/3267/rehearse-3267-pull-ci-openshift-etcd-quorum-guard-master-e2e-aws-operator/2

**Comment by RobertKrawitz** [comment]
> I was trying to figure out this
> 
> ```
> /bin/bash: line 64: make: command not found
> ```
> 
> https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_release/3267/rehearse-3267-pull-ci-openshift-etcd-quorum-guard-master-e2e-aws-operator/2

This looks odd:

```2019/03/28 15:54:38 Tagged release images from ocp/4.0:${component}, images will be pullable from registry.svc.ci.openshift.org/ci-op-cyft656v/stable:${component}
2019/03/28 15:54:38 Building src
2019/03/28 15:55:02 Build src succeeded after 23s
2019/03/28 15:55:02 Building etcd-quorum-guard
2019/03/28 15:55:21 Build etcd-quorum-guard succeeded after 19s
2019/03/28 15:55:21 Tagging etcd-quorum-guard into stable
2019/03/28 15:55:21 Create release image registry.svc.ci.openshift.org/ci-op-cyft656v/release:latest
2019/03/28 15:58:23 Executing template e2e-aws-operator
2019/03/28 15:58:23 Creating or restarting template instance
2019/03/28 15:58:23 Waiting for template instance to be ready
2019/03/28 15:58:25 Running pod e2e-aws-operator
2019/03/28 16:24:46 Container setup in pod e2e-aws-operator completed successfully
clusterversion.config.openshift.io/version condition met
/bin/bash: line 64: make: command not found
2019/03/28 16:24:50 Container test in pod e2e-aws-operator failed, exit code 127, reason Error```

This failed long after the quorum guard itself was built.  It looks like the e2e-aws-operator is where it failed.

**Comment by RobertKrawitz** [comment]
/retest
All failures in infrastructure setup.

**Pull request merged**
