### PR TITLE
[vsphere] reduce periodicity of 4.6 and 4.7 periodics

### PR DESCRIPTION
**Pull request by rvanderp3**
The intention of this PR is to reduce the periodicity of vSphere 4.6 and 4.7 periodics:

4.6/4.7 serial jobs are run on 48h intervals on odd days 
4.6/4.7 parallel jobs are run on 48h intervals on even days

Jobs are staggered such that there will be a upi or ipi job run every 12 hours and helps to check for regressions as well as the health of the CI infra.

### CODE REVIEW

**Comment by bostrt** [comment]
This looks good to me!

**Review by wking — APPROVED** [review]
/lgtm

**Pull request merged**
