### PR TITLE
Change installation namespace for gitops operator

### PR DESCRIPTION
**Pull request by varshab1210**
This PR changes operator installation namespace from openshift-operators to openshift-gitops-operator

### CODE REVIEW

**Comment by varshab1210** [comment]
/test all
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-master-v4.14-periodic-kuttl-sequential pull-ci-redhat-developer-gitops-operator-master-v4.14-kuttl-sequential periodic-ci-redhat-developer-gitops-operator-master-v4.12-periodic-kuttl-sequential periodic-ci-redhat-developer-gitops-operator-master-v4.13-periodic-kuttl-sequential

**Review by iam-veeramalla — APPROVED** [review]
/lgtm

**Comment by varshab1210** [comment]
/pj-rehearse periodic-ci-redhat-developer-gitops-operator-master-v4.13-periodic-kuttl-parallel

**Review by jaideepr97 — APPROVED** [review]

**Pull request merged**
