### PR TITLE
oVirt: increase minimal PRs resources

### PR DESCRIPTION
**Pull request by Gal-Zaidman**
Latel we have started to see PRs failing due to lack of resources on master nodes,
This PR will increase the amount of mem on each node

Signed-off-by: Gal-Zaidman <gzaidman@redhat.com>

### CODE REVIEW

**Comment by sdodson** [comment]
Do you know why RHV docs don't have a nice table formatted section like https://docs.openshift.com/container-platform/4.4/installing/installing_bare_metal/installing-bare-metal.html#minimum-resource-requirements_installing-bare-metal

Also, why does RHV require 16GiB for workers? Do we know if this is more about the control plane resources than workers that's causing CI to fail? Finally why does RHV require 3 workers rather than 2?

**Comment by Gal-Zaidman** [comment]
/hold

It seems that it is not resources related

**Comment by Gal-Zaidman** [comment]
> Do you know why RHV docs don't have a nice table formatted section like https://docs.openshift.com/container-platform/4.4/installing/installing_bare_metal/installing-bare-metal.html#minimum-resource-requirements_installing-bare-metal
> 

No, but I'll ask the docs team it would be nice

> Also, why does RHV require 16GiB for workers?

Only on conformance tests

>Do we know if this is more about the control plane resources than workers that's causing CI to fail? 

In general, the alert on low resources is fired when a certain condition is met to all the cluster in general, nothing specific to workers or master. In this case it wasn't a resources problem (the reason for closing) as I initially thought, it was a problem with port clash https://github.com/openshift/baremetal-runtimecfg/pull/71

>Finally why does RHV require 3 workers rather than 2?

We require 2 workers in our tests

**Pull request closed without merging**
