### PR TITLE
Move ovn-kubernetes packet jobs to new equinix profile

### PR DESCRIPTION
**Pull request by ardaguclu**
The current packet account will soon be closed. This PR moves to new packet account, namely equinix-ocp-metal.

### CODE REVIEW

**Comment by ardaguclu** [comment]
@danwinship could you please take a look at this change?. Old cluster_profile will be removed soon and we are moving to new one. Thanks.

**Comment by danwinship** [comment]
I don't really get what this does... where are the things that these labels actually refer to?

**Comment by ardaguclu** [comment]
> I don't really get what this does... where are the things that these labels actually refer to?

Old `packet` profile will be deleted next week, and we'll start using the new one, namely `equinix-ocp-metal`.

As far as I can see the related PRs are;
https://github.com/openshift/release/pull/25555
https://github.com/openshift/release/pull/25554
https://github.com/openshift/release/pull/25489

Thanks

**Pull request merged**
