### PR TITLE
OCM-12262 | ci: enable rosa classic profile for OCP E2E 4.18 nightly

### PR DESCRIPTION
**Pull request by yingzhanredhat**

### CODE REVIEW

**Comment by yingzhanredhat** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-rosa-advanced-stage-critical-f7

**Comment by yingzhanredhat** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-rosa-non-sts-advanced-stage-critical-f7

**Comment by yingzhanredhat** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-rosa-sts-shared-vpc-stage-critical-f7

**Comment by yingzhanredhat** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-rosa-non-sts-advanced-stage-critical-f7

**Comment by yingzhanredhat** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-rosa-advanced-stage-critical-f7

**Comment by yingzhanredhat** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-rosa-sts-shared-vpc-stage-critical-f7

**Comment by yingzhanredhat** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-rosa-sts-shared-vpc-stage-critical-f7

**Comment by yingzhanredhat** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-rosa-sts-shared-vpc-stage-critical-f7

**Comment by yingzhanredhat** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-rosa-non-sts-advanced-stage-critical-f7

**Comment by yingzhanredhat** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-rosa-sts-shared-vpc-stage-critical-f7

**Comment by yingzhanredhat** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-rosa-sts-shared-vpc-stage-critical-f7

**Comment by yingzhanredhat** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-rosa-advanced-stage-critical-f7

**Comment by yingzhanredhat** [comment]
The failed cases are debugged [here](https://redhat-internal.slack.com/archives/CCTBZUATE/p1732700299240849).

**Comment by yingzhanredhat** [comment]
@xueli181114 Could you help review this pr?

**Comment by yingzhanredhat** [comment]
@kuiwang02 @liangxia Could you help to review?

**Comment by liangxia** [comment]
The failed core-valid job indicates there are conflicts.  Rebase to latest codes should resolved the issue.

**Comment by yingzhanredhat** [comment]
@liangxia Would you help review it?

**Pull request merged**
