### PR TITLE
[vSphere][4.12]add ci job for upi/ipi on vsphere8

### PR DESCRIPTION
**Pull request by WenXinWei**

### CODE REVIEW

**Comment by WenXinWei** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-vsphere-8-ipi-ovn-etcd-encryption-p2-f14

**Comment by WenXinWei** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-vsphere-8-upi-p3-f14

**Comment by WenXinWei** [comment]
@jianlinliu @jinyunma please help review this pr, thanks.

**Comment by jianlinliu** [comment]
added the jobs per https://redhat-internal.slack.com/archives/CF8SMALS1/p1678240712221129. 

cc @liangxia to review.

**Pull request merged**
