### PR TITLE
kni: cluster-group-upgrades-operator: enable security scanning

### PR DESCRIPTION
**Pull request by danimjaffe**
per https://docs.ci.openshift.org/docs/how-tos/add-security-scanning/

### CODE REVIEW

**Comment by danimjaffe** [comment]
/pj-rehearse pull-ci-openshift-kni-cluster-group-upgrades-operator-main-security

**Comment by danimjaffe** [comment]
In order to ignore vulnerabilities you can follow the guidelines in the [following link](https://docs.ci.openshift.org/docs/how-tos/add-security-scanning/#how-to-ignore-vulnerabilities).
For reference you can see an example in the [following repo](https://github.com/openshift-kni/numaresources-operator/blob/main/.snyk).

**Comment by jc-rh** [comment]
/pj-rehearse pull-ci-openshift-kni-cluster-group-upgrades-operator-main-security

**Pull request merged**
