### PR TITLE
Remove unused field time from junit xml

### PR DESCRIPTION
**Pull request by liangxia**
The `time` field indicates the execution time of the test cases. Instead of hard code to `1`, we can omit it.

/cc @JianLi-RH @dis016 @pruan-rht @jhou1 @jianlinliu

### CODE REVIEW

**Comment by JianLi-RH** [comment]
In my impression time attribute is required for ReportPortal, without it we can NOT import junit file to ReportPortal.

**Comment by liangxia** [comment]
> In my impression time attribute is required to ReportPortal, without it we can NOT import junit file to ReportPortal.

It's not required. Example [log](https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.11-amd64-nightly-aws-ipi-imdsv2-fips-f28/1721607943792627712/artifacts/aws-ipi-imdsv2-fips-f28/openshift-extended-web-tests/artifacts/gui_test_screenshots/console-cypress.xml).

**Comment by JianLi-RH** [comment]
Yes, you are right.

/lgtm

**Pull request merged**
