### PR TITLE
bump golang to 1.13 for nfd

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
bump golang to 1.13 for nfd

Align with OpenShift/Origin 
Align with https://github.com/openshift/cluster-nfd-operator

Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
*PING* @jmencak

**Comment by ArangoGutierrez** [comment]
*PING* @jmencak @zvonkok

**Comment by ArangoGutierrez** [comment]
> I think you're missing `openshift-cluster-nfd-operator-release-4.7.yaml`

thanks for the pointer, added that

**Comment by jmencak** [comment]
I believe that after squashing the commits this should be good to go.

**Comment by ArangoGutierrez** [comment]
OpenShift Bot why don't you love me

**Pull request merged**
