### PR TITLE
Mirror PAO index image

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@fromanirh FYI

**Comment by fromanirh** [comment]
can we keep the bundle? otherwise lgtm

**Comment by cynepco3hahue** [comment]
> can we keep the bundle? otherwise lgtm

Why do we need the bundle image? I thought it includes only some metadata?

**Comment by fromanirh** [comment]
> > can we keep the bundle? otherwise lgtm
> 
> @fromanirh Why do we need the bundle image? I thought it contains only some metadata.

We don't need it :) but I'd like to keep it for a little while because it's handy for debugging/doublecheck

**Comment by cynepco3hahue** [comment]
@fromanirh Done

**Review by fromanirh — APPROVED** [review]
/lgtm

**Pull request merged**
