### PR TITLE
feat: renamed single node e2e tests to include network topology

### PR DESCRIPTION
**Pull request by eggfoobar**
Signed-off-by: ehila <ehila@redhat.com>

### CODE REVIEW

**Comment by omertuc** [comment]
> not sure if the metal installs are also OVN

All should be OVN, which ones in particular are you referring to? I can verify

**Comment by omertuc** [comment]
> not sure if the metal installs are also OVN

All should be OVN, which ones in particular are you referring to? I can verify

**Comment by omertuc** [comment]
> > All should be OVN, which ones in particular are you referring to? I can verify
> 
> Sure thing, that would be great, the ones I'm referring to are the [e2e-metal-single-node-live-iso](https://github.com/openshift/release/blob/985a7b3a1489f04aa218f17a651c8ea9f26a3723/ci-operator/config/openshift/release/openshift-release-master__nightly-4.10.yaml#L133-L137), they have the workflow [baremetalds-sno](https://steps.ci.openshift.org/workflow/baremetalds-sno)

Ah okay then yes they're OVN as well

https://github.com/openshift/assisted-test-infra//blob/46306934837f50e8d487166409b6f562463f64ee/src/tests/test_bootstrap_in_place.py#L144

**Comment by eggfoobar** [comment]
That's great! Updated to rename those as well

**Comment by eggfoobar** [comment]
Hey @omertuc , this PR fell a little behind, If you still find a need for the name change for the older jobs I went ahead and rebased it and removed the 4.12 changes since those were already updated.

**Pull request closed without merging**
