### PR TITLE
Switch knative image mirroring jobs to Prowjobs

### PR DESCRIPTION
**Pull request by petr-muller**
https://github.com/openshift/release/pull/4259 added Prowjob-based versions of image-mirroring jobs running with `--dry-run=true`. The knative job [ran fine](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/periodic-image-mirroring-knative/1), so this PR switches the mirroring jobs to Prowjobs entirely. The Prowjobs have the following advantages:

1. Their results and logs can be investigated via [Deck](https://prow.svc.ci.openshift.org/?job=periodic-image*)
2. There is a single Prowjob for each "thing" (openshift, knative, kubefed...) which iterates over its mappings, so setting up mirroring for new version means just adding a mapping file and not a new job.
3. I [documented](https://github.com/openshift/release/tree/master/core-services/quay-mirroring) how this works.

This PR does the following:

- Removes updating the CM from the postsubmit. This is not needed because both mappings and prowjob configs are automatically updated by config-updater.
- Switches the Prowjob to run `@hourly` like the original cronjobs
- Removes all config from the old config location
- Removes watching the old mapping for updates into `image-mirror` CM
- Add changes in the mappings from https://github.com/openshift/release/pull/4265

/cc @lberk  @stevekuznetsov @matzew

### CODE REVIEW

**Comment by lberk** [comment]
Thanks for the detailed explanation! @alanfx might want to take note of this as well.
/lgtm

**Comment by petr-muller** [comment]
/hold

Some of the other mirroring jobs have problems with authentization, maybe the secrets are somehow wired wrong. Need to investigate.

**Comment by petr-muller** [comment]
/hold cancel

1. Auth problems resolved, fixed in https://github.com/openshift/release/pull/4306 even for knative job
2. Updated the mapping files after https://github.com/openshift/release/pull/4305 merged

**Comment by lberk** [comment]
@petr-muller We've also pushed the knative-serving images for v0.7.1, should we include those in this change?
https://github.com/openshift/release/pull/4305

**Comment by petr-muller** [comment]
@lberk I already pulled these changes in :)

`git diff knative-mirroring:core-services/quay-mirroring/knative/mapping_knative_v0_7_quay upstream/master:cluster/ci/config/mirroring/knative/knative_v0_7_quay`

**Comment by petr-muller** [comment]
@markusthoemmes @matzew @vdemeester WDYT?

**Comment by matzew** [comment]
/lgtm

thanks for the great details, @petr-muller

**Pull request merged**
