### PR TITLE
Add configuration for FreeIPA operator

### PR DESCRIPTION
**Pull request by vashirov**
Onboard https://github.com/freeipa/freeipa-operator
Add CI config files

### CODE REVIEW

**Review by petr-muller — COMMENTED** [review]
Config looks good, needs `OWNERS` under `ci-operator/config/...` too

**Comment by vashirov** [comment]
Thank you, I missed another OWNERS file, now it's there. One of the persons there still requires to join the OpenShift org, I believe this is in progress.

There is also an ongoing PR to fix failing unit tests (due to missing `vendor/` directory): https://github.com/freeipa/freeipa-operator/pull/17

**Comment by vashirov** [comment]
Filed https://github.com/freeipa/freeipa-operator/pull/20 to fix missing envtest binaries.

**Review by petr-muller — APPROVED** [review]
LGTM
/hold

Holding to allow waiting for passing rehearsal, if needed. Feel free to unhold and merge.

**Pull request merged**
