### PR TITLE
OPNET-302: nmstate - update presubmits jobs

### PR DESCRIPTION
**Pull request by dougsland**
Now require OVN jobs.

### CODE REVIEW

**Comment by dougsland** [comment]
> I'm not seeing any changes in this PR. Maybe the changed files weren't added to the commit?

I did run `make jobs` just to make sure the `bot job` was happy. In fact, nothing changed but I forced anyway and now the bot is happy.

**Comment by cybertron** [comment]
There have to be changes for this to have any effect. https://github.com/openshift/release/blob/519c9fb78a06410630c07d9b0b3c4e5986881dbf/ci-operator/jobs/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-master-presubmits.yaml#L65 needs to be removed to make the ovn job required.

**Comment by dougsland** [comment]
not sure, running the `make jobs` locally just erase my changes. Trying a new push.

**Comment by cybertron** [comment]
Looks like it also needs to be changed here: https://github.com/openshift/release/blob/9a43a963e6315797e1a8b0bec1e2aec7133c964e/ci-operator/config/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-master.yaml#L104

**Comment by dougsland** [comment]
> Looks like it also needs to be changed here:
> 
> https://github.com/openshift/release/blob/9a43a963e6315797e1a8b0bec1e2aec7133c964e/ci-operator/config/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-master.yaml#L104

still not flying, if I do `make jobs` it returns the optional true.

**Comment by cybertron** [comment]
The same change needs to be made to the 4.14 and 4.15 config files so the jobs will be generated correctly.

**Comment by cybertron** [comment]
/lgtm
/approve
/pj-rehearse ack

This isn't changing anything in the job config so I'm not going to spend ci resources testing all of the affected jobs. From a practical perspect we're already treating this as non-optional.

**Pull request merged**
