### PR TITLE
gather-loki: flush data on disk and save chunks/indexes

### PR DESCRIPTION
**Pull request by vrutkovs**
Instead of saving fetched logs in files in-cluster Loki needs to flush data on disk and save chunks/indexes.

Use https://github.com/vrutkovs/openshift-ci-loki to run a local Loki and load chunks/indexes.

Supercedes #12873

### CODE REVIEW

**Comment by vrutkovs** [comment]
/hold

Still no luck with reusing the exported chunks

**Comment by vrutkovs** [comment]
Works perfectly now
/hold cancel

**Review by periklis — COMMENTED** [review]
Looks good to me

**Pull request merged**
