### PR TITLE
OCPQE-18695: add verification-test job azure-upi-disconnected

### PR DESCRIPTION
**Pull request by jinyunma**
Add verification test job azure-upi-disconnected on 4.14+ to automate test case [OCP-63946 - [upi-on-azure] Disconnected install](https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-63946)

### CODE REVIEW

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disconnected-f14

**Comment by jinyunma** [comment]
cc @jianlinliu @gpei to review

**Comment by jianlinliu** [comment]
Since last time we discussed with dev team, we are agreed to only cover disconnected in IPI install, because disconnected install should be irrelevant to UPI or IPI, so maybe we just need to cover IPI disconnected install, to reduce the maintenance on azure upi ARM templates.

**Pull request merged**
