### PR TITLE
Enable 4.14 Nightly with m5.xlarge instances

### PR DESCRIPTION
**Pull request by krishvoor**
This PR enables 4.1.4 nightly jobs, with worker nodes of m5.xlarge

### CODE REVIEW

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-nightly-perfscale-rosa-multiaz-ingress-perf-defaultnodes-periodic

**Comment by krishvoor** [comment]
> @krishvoor: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> ci/rehearse/periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-nightly-perfscale-rosa-multiaz-ingress-perf-defaultnodes-periodic	[e0f6a6b](https://github.com/openshift/release/commit/e0f6a6b46e5cfa349e5690ececae4b58f1de937c)	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/41953/rehearse-41953-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-nightly-perfscale-rosa-multiaz-ingress-perf-defaultnodes-periodic/1687021083326156800)	unknown	`/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-nightly-perfscale-rosa-multiaz-ingress-perf-defaultnodes-periodic`
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openshift&repo=release&pr=41953). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:krishvoor).

The error reported here is not due to the PR, but because of the timeout during user login.

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-nightly-perfscale-rosa-multiaz-ingress-perf-defaultnodes-periodic

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-nightly-perfscale-rosa-multiaz-datapath-defaultnodes-periodic

**Review by jtaleric — CHANGES_REQUESTED** [review]
@krishvoor is this PR necessary? It seems to be removing the medium scale? https://github.com/openshift/release/blob/b12220fef825bcf203767f21c195a7ddd0508920/ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.14-nightly.yaml#L24

**Comment by jtaleric** [comment]
This PR is in collision with https://github.com/openshift/release/pull/41979 

If we want to enable other rosa jobs that is one thing... this PR replaces our medium scale.

**Comment by svetsa-rh** [comment]
I too am confused what we are trying to achieve here, swapping out kube burner tests with c-d-v2.

**Pull request closed without merging**
