### PR TITLE
stackrox: Adjust 3.72&3.73 release OCP jobs according to the matrix

### PR DESCRIPTION
**Pull request by msugakov**
https://docs.engineering.redhat.com/pages/viewpage.action?spaceKey=~msugakov&title=ACS+-+OpenShift+version+support#ACSOpenShiftversionsupport-SuggestedE2Etestapproach-release-3.yyandmasterbranches

### CODE REVIEW

**Comment by gavin-stackrox** [comment]
I think we need to handle 4.6 similar to how we handle ocp-next on master. i.e. run the installer, as the cluster_claim approach does not appear to be fulfilled.

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-release-3.72-ocp-4-6-qa-e2e-tests

**Comment by gavin-stackrox** [comment]
Not a great start. First run fails and the result UI crashes my browser tab: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/36601/rehearse-36601-pull-ci-stackrox-stackrox-release-3.72-ocp-4-6-qa-e2e-tests/1628126491873120256

/pj-rehearse pull-ci-stackrox-stackrox-release-3.72-ocp-4-6-qa-e2e-tests

**Comment by gavin-stackrox** [comment]
Unfortunately the `cluster_profile` approach to getting a 4.6 cluster failed twice in a row so I backed out my changes. I suggest dropping 4.6 altogether for now. One option to enabling it would be to use the automation-flavors openshift-4 automation (as we do for ROSA, ARO, OSD) but that will require more than a quick fix.

**Review by gavin-stackrox — APPROVED** [review]
Config looks good.
/lgtm

**Comment by msugakov** [comment]
Why is this not merging?

**Comment by msugakov** [comment]
Magic.

**Pull request merged**
