### PR TITLE
Back up k8s_prometheus.yaml

### PR DESCRIPTION
**Pull request by hongkailiu**
https://jira.coreos.com/browse/DPTP-472

### CODE REVIEW

**Comment by petr-muller** [comment]
@hongkailiu We need to update the RBAC for the updater first (manually - we don't do RBAC changes automatically), then the dry run should pass.

**Comment by hongkailiu** [comment]
> @hongkailiu We need to update the RBAC for the updater first (manually - we don't do RBAC changes automatically), then the dry run should pass.

Done.

**Pull request merged**
