### PR TITLE
Adding AWS Local Zone Phase 2 CI

### PR DESCRIPTION
**Pull request by yunjiang29**
## Changes
* Rename existing `cucushift-installer-rehearse-aws-ipi-localzone[-sdn]`  to `cucushift-installer-rehearse-aws-ipi-localzone-byo-subnet[-sdn]`, the `byo-subnet` workflow is for Phase 1 (4.13 and above), the VPC and Local Zone subnets are pre-created
* The new workflow `cucushift-installer-rehearse-aws-ipi-localzone[-sdn]` is for Phase 2 (4.14 and above), VPC and Local Zone subnets are created by installer

Installer PR https://github.com/openshift/installer/pull/7137 
Enhancement PR https://github.com/openshift/enhancements/pull/1232

Phase 2: installer can create localzone subnet automatically (`platform.aws.subnets` is not required). e.g:
```
apiVersion: v1
baseDomain: example.com
metadata:
  name: edge-cluster
compute:
- name: edge
  platform:
    aws:
      zones:
      - us-east-1-nyc-1a
```

### 4.13
```
- as: aws-ipi-disconnected-mtu-localzone-fips-p2-f14
- as: aws-ipi-disconnected-mtu-localzone-fips-p3-f28-destructive
- as: aws-ipi-localzone-byo-subnet-p2-f14
- as: aws-ipi-localzone-byo-subnet-p3-f28-destructive
- as: aws-ipi-localzone-byo-subnet-sdn-p2-f14
- as: aws-ipi-localzone-byo-subnet-sdn-p3-f28-destructive
```
### 4.14
```
- as: aws-ipi-disconnected-mtu-localzone-fips-f14
- as: aws-ipi-disconnected-mtu-localzone-fips-f28-destructive
- as: aws-ipi-localzone-byo-subnet-sdn-f14
- as: aws-ipi-localzone-byo-subnet-sdn-f28-destructive
- as: aws-ipi-localzone-fips-f14
- as: aws-ipi-localzone-fips-f28-destructive
```

### CODE REVIEW

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-localzone-byo-subnet-p2-f14

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-aws-ipi-localzone-f14

**Comment by yunjiang29** [comment]
## Test 

### 4.13
https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/41574/rehearse-41574-periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-localzone-byo-subnet-p2-f14/1684499891193122816
```
Selected Local Zone: us-east-1-iah-1a
Local Zone config patch:
compute:
- name: edge
  architecture: amd64
  hyperthreading: Enabled
  replicas: 1
  platform:
    aws:
      type: c5d.2xlarge
      zones: [us-east-1-iah-1a]
platform:
  aws:
    subnets:
    - subnet-01d7f441857d28621
```
```
level=info msg=Install complete!
level=info msg=To access the cluster as the system:admin user when using 'oc', run 'export KUBECONFIG=/tmp/installer/auth/kubeconfig'
level=info msg=Access the OpenShift web-console here: https://console-openshift-console.apps.ci-op-m74ntf8c-19be6.qe.devcluster.openshift.com
level=info msg=Time elapsed: 25m11s
```

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-aws-ipi-localzone-f14

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-aws-ipi-localzone-f14

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-localzone-byo-subnet-p2-f14

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-localzone-byo-subnet-p2-f14

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-aws-ipi-localzone-fips-f14

**Comment by yunjiang29** [comment]
@jianlinliu @gpei Please review this PR when you are available, thanks

**Comment by jianlinliu** [comment]
```
- as: aws-ipi-localzone-byo-subnet-sdn-f14
- as: aws-ipi-localzone-byo-subnet-sdn-f28-destructive
- as: aws-ipi-localzone-fips-f14
- as: aws-ipi-localzone-fips-f28-destructive
```
So for sdn, even 4.14 comes to phase 2, still need byo subnet?

**Comment by yunjiang29** [comment]
> So for sdn, even 4.14 comes to phase 2, still need byo subnet?

No, just to make sure `byo-subnet` and `sdn` are covered in 4.14

**Comment by yunjiang29** [comment]
## Test
### 4.14 without byo-vpc
https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/41574/rehearse-41574-periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-aws-ipi-localzone-fips-f14/1684806121312751616

```
controlPlane:
  platform:
    aws:
      zones:
      - us-east-1f
      - us-east-1a
      type: m6i.xlarge
  architecture: amd64
  name: master
compute:
- platform:
    aws:
      zones:
      - us-east-1f
      - us-east-1a
      type: m5.xlarge
  architecture: amd64
  name: worker
  replicas: 3
- name: edge
  architecture: amd64
  hyperthreading: Enabled
  replicas: 1
  platform:
    aws:
      type: c5d.2xlarge
      zones: [us-east-1-msp-1a]
baseDomain: qe.devcluster.openshift.com
platform:
  aws:
    region: us-east-1
    userTags:
      expirationDate: 2023-07-28T14:04+0000
```

### 4.13 with byo-vpc
https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/41574/rehearse-41574-periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-localzone-byo-subnet-p2-f14/1684805962076000256

```
platform:
  aws:
    subnets:
    - 'subnet-0561c4f3092c8f629'
    - 'subnet-096a538e3b95eb2eb'
    - 'subnet-0731d3e94870cb715'
    - 'subnet-0889c6f09790b8044'
    - 'subnet-0842842c0f717556f'
    - 'subnet-0afd97710d068cdda'
    - subnet-054eab52ff9b6f80e
    region: us-east-1
    userTags:
      expirationDate: 2023-07-28T14:07+0000
controlPlane:
  platform:
    aws:
      zones:
      - "us-east-1a"
      - "us-east-1b"
      - "us-east-1c"
      type: m6i.xlarge
  architecture: amd64
  name: master
compute:
- platform:
    aws:
      zones:
      - "us-east-1a"
      - "us-east-1b"
      - "us-east-1c"
      type: m5.xlarge
  architecture: amd64
  name: worker
  replicas: 3
- name: edge
  architecture: amd64
  hyperthreading: Enabled
  replicas: 1
  platform:
    aws:
      type: c5d.2xlarge
      zones: [us-east-1-iah-1a]
baseDomain: qe.devcluster.openshift.com
```

**Comment by jianlinliu** [comment]
cc @liangxia to review

**Pull request merged**
