### PR TITLE
SPLAT-1713: Create vSphere multi vCenter periodical

### PR DESCRIPTION
**Pull request by vr4manta**
[SPLAT-1713](https://issues.redhat.com/browse/SPLAT-1713)

### Changes
- Created new vSphere multi vCenter periodical (IPI & UPI)
- Disabled e2e tests involving in-tree due to not being supported in multi vCenter environments (only for multi vCenter jobs)

### Prerequisites
- https://github.com/openshift/vmware-vsphere-csi-driver-operator/pull/228
- https://github.com/openshift/vsphere-problem-detector/pull/158
- https://github.com/openshift/installer/pull/8638
- https://github.com/openshift/installer/pull/8853
- https://github.com/openshift/installer/pull/8829
- https://github.com/openshift/installer/pull/8863
- https://github.com/openshift/installer/pull/8865

### Notes
The new periodical will need the installer to have the new featuregate for multi vcenter before this can work.  Until then, this periodical will work up until installer is executed and will fail due to vCenters > 1.

Due to branching occurring before this PR was complete, we have to migrate some logic back to 4.17 so the 4.17 release jobs will work correctly.

### CODE REVIEW

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/hold
Looking into installer issue for upi jobs.  IPI should be fine.

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/payload-job-with-prs/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-multi-vcenter
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-multi-vcenter
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-upi-multi-vcenter
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-multi-vcenter periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-multi-vcenter periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-upi-multi-vcenter periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-multi-vcenter periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-multi-vcenter periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-upi-multi-vcenter periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-upi-multi-vcenter

**Comment by vr4manta** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-multi-vcenter periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-multi-vcenter periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-upi-multi-vcenter periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-upi-multi-vcenter

**Review by vrutkovs — APPROVED** [review]
/approve

**Pull request merged**
