### PR TITLE
Reduce the fail ratio of listing account-roles/operator-roles

### PR DESCRIPTION
**Pull request by yasun1**
[OCPQE-21087](https://issues.redhat.com//browse/OCPQE-21087)

### CODE REVIEW

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-master-rosacli-aws-rosa-hcp-e2e-f3

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-master-rosacli-aws-rosa-hcp-e2e-f3

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-master-rosacli-aws-rosa-hcp-e2e-f3

**Review by radtriste — APPROVED** [review]
/lgtm

**Pull request merged**
