### PR TITLE
update capk e2e test config

### PR DESCRIPTION
**Pull request by davidvossel**
this update is required for https://github.com/openshift/cluster-api-provider-kubevirt/pull/48 to pass

### CODE REVIEW

**Comment by davidvossel** [comment]
@nunnatsa we need this update before we can merge https://github.com/openshift/cluster-api-provider-kubevirt/pull/48

**Review by nunnatsa — APPROVED** [review]
/lgtm
/approve

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-kubevirt-main-e2e-hypershift-kubevirt

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-kubevirt-main-e2e-hypershift-kubevirt

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-kubevirt-release-4.14-e2e-hypershift-kubevirt

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-kubevirt-main-e2e-hypershift-kubevirt

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-kubevirt-release-4.14-e2e-hypershift-kubevirt pull-ci-openshift-cluster-api-provider-kubevirt-main-e2e-hypershift-kubevirt

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-kubevirt-release-4.14-e2e-hypershift-kubevirt pull-ci-openshift-cluster-api-provider-kubevirt-main-e2e-hypershift-kubevirt

**Pull request merged**
