### PR TITLE
platform-operators: use build_root.from_repository=true

### PR DESCRIPTION
**Pull request by joelanford**

### CODE REVIEW

**Review by ncdc — APPROVED** [review]

**Comment by joelanford** [comment]
/pj-rehearse pull-ci-openshift-platform-operators-release-4.13-images
/pj-rehearse pull-ci-openshift-platform-operators-release-4.13-lint
/pj-rehearse pull-ci-openshift-platform-operators-release-4.13-unit
/pj-rehearse pull-ci-openshift-platform-operators-release-4.13-verify
/pj-rehearse pull-ci-openshift-platform-operators-release-4.12-images
/pj-rehearse pull-ci-openshift-platform-operators-release-4.12-lint
/pj-rehearse pull-ci-openshift-platform-operators-release-4.12-unit
/pj-rehearse pull-ci-openshift-platform-operators-release-4.12-verify

**Comment by joelanford** [comment]
/pj-rehearse pull-ci-openshift-platform-operators-release-4.12-e2e-aws-techpreview-operator
/pj-rehearse pull-ci-openshift-platform-operators-release-4.13-e2e-aws-techpreview-operator

**Comment by joelanford** [comment]
I think this is once again a case of our tests relying on fixtures that come from live catalogs, and those catalogs changing out from under us.

Two data points:
1. Rukpak requires registry+v1 bundles to support AllNamespaces mode
2. The operator our tests use (`openshift-cert-manager-operator`) no longer supports `AllNamespaces` mode, but it once did. Change happened here: https://github.com/openshift/cert-manager-operator/pull/83

So I think we can safely merge this change. We will need to separately go back to the e2e tests for the platform-operators component and choose a different operator that supports AllNamespaces mode. Long-term, we may want to introduce our own test fixture to avoid this problem in the future.

**Comment by ncdc** [comment]
SGTM

**Pull request merged**
