### PR TITLE
ci-operator/step-registry/cri-o: change the underlying OS

### PR DESCRIPTION
**Pull request by sohankunkerkar**
Update the base image

### CODE REVIEW

**Comment by haircommander** [comment]
maybe we should try centos-stream-9?

```
ast metadata expiration check: 0:14:08 ago on Wed 30 Nov 2022 03:58:41 PM UTC.
No match for argument: python
There are following alternatives for "python": python2, python36, python38, python39
Package git-2.31.1-2.el8.x86_64 is already installed.
Package gcc-8.5.0-15.el8.x86_64 is already installed.
Package libcap-devel-2.48-4.el8.x86_64 is already installed.
No match for argument: yajl-devel
Package libseccomp-devel-2.5.2-1.el8.x86_64 is already installed.
Package libselinux-devel-2.9-6.el8.x86_64 is already installed.
Package glibc-static-2.28-211.el8.x86_64 is already installed.
Package pkgconf-pkg-config-1.4.2-1.el8.x86_64 is already installed.
No match for argument: gperf

```

**Comment by sohankunkerkar** [comment]
> maybe we should try centos-stream-9?
> 
> ```
> ast metadata expiration check: 0:14:08 ago on Wed 30 Nov 2022 03:58:41 PM UTC.
> No match for argument: python
> There are following alternatives for "python": python2, python36, python38, python39
> Package git-2.31.1-2.el8.x86_64 is already installed.
> Package gcc-8.5.0-15.el8.x86_64 is already installed.
> Package libcap-devel-2.48-4.el8.x86_64 is already installed.
> No match for argument: yajl-devel
> Package libseccomp-devel-2.5.2-1.el8.x86_64 is already installed.
> Package libselinux-devel-2.9-6.el8.x86_64 is already installed.
> Package glibc-static-2.28-211.el8.x86_64 is already installed.
> Package pkgconf-pkg-config-1.4.2-1.el8.x86_64 is already installed.
> No match for argument: gperf
> ```

Yeah, let me change the `image_family` to `centos-stream-9`

**Comment by sohankunkerkar** [comment]
```
TASK [Install optional packages For Fedora/CentOS] *****************************
task path: /home/deadbeef/cri-o/contrib/test/ci/system-packages.yml:71
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failures": [
        "No package glibc-static available.",
        "No package gpgme-devel available."
    ]
```

**Comment by sohankunkerkar** [comment]
I need some help figuring out the exact repo where these two packages would be available.

**Comment by haircommander** [comment]
> I need some help figuring out the exact repo where these two packages would be available for cs-9.

https://centos.pkgs.org/9-stream/centos-crb-aarch64/glibc-static-2.34-29.el9.aarch64.rpm.html / https://centos.pkgs.org/9-stream/centos-crb-aarch64/gpgme-devel-1.15.1-6.el9.aarch64.rpm.html 
it looks like CRB needs to be enabled

**Pull request merged**
