### PR TITLE
ODH DW: Use ODH 2.x for PR checks

### PR DESCRIPTION
**Pull request by sutaakar**
Switched back to install CodeFlare operator from OLM as ODH operator requires CodeFlare subscription to be created.

### CODE REVIEW

**Comment by sutaakar** [comment]
Postponing until https://github.com/opendatahub-io/opendatahub-operator/issues/425 is implemented and available.
Then a PR can be directly applies as shown in https://github.com/opendatahub-io/odh-manifests/blob/master/tests/scripts/install.sh#L80

**Review by anishasthana — APPROVED** [review]
/lgtm

**Pull request merged**
