### PR TITLE
synthesize subnet.json to preserve steps that rely upon it

### PR DESCRIPTION
**Pull request by rvanderp3**

### CODE REVIEW

**Comment by rvanderp3** [comment]
cc @jcpowermac

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-e2e-vsphere-ovn-dualstack pull-ci-openshift-cluster-network-operator-master-e2e-vsphere-ovn-dualstack-primaryv6

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-e2e-vsphere-ovn-dualstack pull-ci-openshift-cluster-network-operator-master-e2e-vsphere-ovn-dualstack-primaryv6

**Comment by danwinship** [comment]
/approve
(ftr I have no idea what that file does and probably that directory should be owned by vsphere people, not sdn)

**Pull request merged**
