### PR TITLE
softLinks to prepare for Power buildfarm

### PR DESCRIPTION
**Pull request by vijay-vin**
Signed-off-by: Vijay Vinnakota <vijay.vinnakota@ibm.com>
This is start of work to create a native ppc64le build cluster
https://github.com/openshift/release/blob/master/clusters/JoinBuildFarm.md

### CODE REVIEW

**Comment by vijay-vin** [comment]
@deepsm007 When you get a chance, Could you please approve this PR.

**Comment by deepsm007** [comment]
@danilo-gemoli

**Pull request merged**
