### PR TITLE
Update Distirbuted Tracing interop jobs.

### PR DESCRIPTION
**Pull request by IshwarKanse**

### CODE REVIEW

**Comment by Sau1506mya** [comment]
Hi @IshwarKanse , if all the work related to this PR is completed then please add **ack** label by commenting `/pj-rehearse ack` .
Also don't forget to run `make update` command and make the commit, since you made changes in the config file for the scenarios.

**Comment by IshwarKanse** [comment]
@Sau1506mya We need to sync our forked repositories so that it has the latest upstream code. For that to happen we need to allow force push for those repos. See https://github.com/openshift/release/pull/43560

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.14-lp-interop-tempo-interop-aws periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.14-lp-interop-opentelemetry-interop-aws

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.14-lp-interop-tempo-interop-aws periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.14-lp-interop-opentelemetry-interop-aws

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.14-lp-interop-opentelemetry-interop-aws periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.14-lp-interop-tempo-interop-aws

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.14-lp-interop-opentelemetry-interop-aws

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.14-lp-interop-tempo-interop-aws

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.14-lp-interop-tempo-interop-aws periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.14-lp-interop-opentelemetry-interop-aws

**Pull request merged**
