### PR TITLE
MSI: Add RHODS-RHOAM 4.13 production scenraio

### PR DESCRIPTION
**Pull request by oharan2**

### CODE REVIEW

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-rhoam-v4.14-stage-co-exist-rosa-rhods-rhoam

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-rhoam-v4.13-production-co-exist-rosa-rhods-rhoam

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-rhoam-v4.13-production-co-exist-rosa-rhods-rhoam

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-rhoam-v4.13-production-co-exist-rosa-rhods-rhoam

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-rhoam-v4.13-production-co-exist-rosa-rhods-rhoam

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-rhoam-v4.13-production-co-exist-rosa-rhods-rhoam

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-rhoam-v4.14-stage-co-exist-rosa-rhods-rhoam

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-rhoam-v4.13-production-co-exist-rosa-rhods-rhoam

**Review by omrirh — APPROVED** [review]

**Pull request merged**
