### PR TITLE
ci-operator/templates/openshift: Remove Terraform-state-based SSH gathers

### PR DESCRIPTION
**Pull request by wking**
Like 970ec020d8 (#6336), except for the templates instead of the step registry.  CC @crawford

### CODE REVIEW

**Comment by wking** [comment]
This should help with [rhbz#1793287][1].

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1793287#c5

**Comment by bparees** [comment]
@wking can you look into these rehearsal failures and make sure they aren't caused by these changes?  

otherwise lgtm.

/approve

**Comment by wking** [comment]
> ... can you look into these rehearsal failures and make sure they aren't caused by these changes?

I did; they aren't.

**Pull request merged**
