### PR TITLE
hypershift: remove 4.12 kubevirt e2e

### PR DESCRIPTION
**Pull request by LiangquanLi930**

### CODE REVIEW

**Comment by LiangquanLi930** [comment]
@liangxia Could you help to review this PR? thanks

**Comment by liangxia** [comment]
Is there a explanation for the removal ?

**Comment by YuLi517** [comment]
We plan to GA kubevirt in OCP4.14 [OCPBU-556](https://issues.redhat.com/browse/OCPBU-556). In fact, we start our work from 4.12. But as priority change in between, the GA date is postponed again and again. Consider cloud cost and GA date, we plan to focus on 4.13 right now. We will enable 4.14 when HyperShift 4.14 is stable.

**Pull request merged**
