### PR TITLE
OCPBUGSM-46219: OCPBUGSM-46220: Update golang version to 1.18

### PR DESCRIPTION
**Pull request by eliorerz**
https://bugzilla.redhat.com/show_bug.cgi?id=2077688
https://bugzilla.redhat.com/show_bug.cgi?id=2077689

- Update golangci to v1.46.0
- Update golang version to 1.18

/cc @adriengentil

### CODE REVIEW

**Review by adriengentil — APPROVED** [review]

**Comment by eliorerz** [comment]
Already fixed as part of https://github.com/openshift/release/pull/34330 and https://github.com/openshift/release/pull/33699

**Pull request closed without merging**
