### PR TITLE
Update Tracing interop jobs

### PR DESCRIPTION
**Pull request by IshwarKanse**

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.16-lp-interop-opentelemetry-interop-aws

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.16-lp-interop-opentelemetry-interop-aws

**Review by vprashar2929 — APPROVED** [review]
/lgtm

**Pull request merged**
