### PR TITLE
Ensure mao vpshere job runs on vsphere cluster

### PR DESCRIPTION
**Pull request by michaelgugino**

### CODE REVIEW

**Comment by jcpowermac** [comment]
/assign @hongkailiu

I also removed the hold on https://github.com/openshift/ci-tools/pull/1173
so this should be the last one

**Comment by elmiko** [comment]
i was kinda wondering about that "build02" value on the last pr that touched these, but i saw it was copied from other entries and figured it was the right cluster. this makes sense though.
/lgtm

**Comment by alvaroaleman** [comment]
This PR is a no-op after https://github.com/openshift/release/pull/12098 merged. All jobs that have vsphere in their name are required to have the vsphere cluster now.
/close

**Pull request closed without merging**
