### PR TITLE
stackrox: set to unmanaged

### PR DESCRIPTION
**Pull request by gavin-stackrox**
& add missing OWNERS for future mods

### CODE REVIEW

**Comment by gavin-stackrox** [comment]
I wonder if I can "/lgtm" myself?

/lgtm

**Comment by gavin-stackrox** [comment]
hi @emilvberglind or @hongkailiu, can I get a review on this PR? thanks

**Comment by hongkailiu** [comment]
/approve

lgtm should be added automatically.

**Comment by hongkailiu** [comment]
/lgtm
whatever

**Pull request merged**
