### PR TITLE
Do not exit on error for make and rename in acceptance-lp-interop

### PR DESCRIPTION
**Pull request by smatula**

### CODE REVIEW

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-redhat-developer-service-binding-operator-release-v1.3.x-4.14-acceptance-lp-interop

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-redhat-developer-service-binding-operator-release-v1.3.x-4.14-acceptance-lp-interop

**Review by Simranpal — APPROVED** [review]

**Review by sadlerap — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
