### PR TITLE
OSSM-4914: update jobs with ossm-aws profile

### PR DESCRIPTION
**Pull request by yxun**
This PR is related to https://issues.redhat.com/browse/OSSM-4914
It updates servicemesh maistra istio, envoy and proxy workflow with new profile `ossm-aws` 
It does not update any profile in the use of hypershift workflow at this moment.

test run job logs can be found in:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/45931/rehearse-45931-pull-ci-maistra-istio-maistra-2.4-integ-helm-2-4/1729162533849272320

### CODE REVIEW

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-operator-maistra-2.4-push-images

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-integ-pilot-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-envoy-maistra-2.4-maistra-envoy-unit-2-4

**Comment by yxun** [comment]
/pj-rehearse  pull-ci-maistra-istio-maistra-3.0-maistra-istio-unit-3-0

**Review by jwendell — APPROVED** [review]

**Comment by yxun** [comment]
this PR is waiting a quota region PR :
https://github.com/openshift/release/pull/46088

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-maistra-2.4-integ-servicemesh-multicluster-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-envoy-maistra-2.4-maistra-envoy-unit-2-4

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-envoy-maistra-2.4-maistra-envoy-unit-2-4

**Pull request merged**
