### PR TITLE
Allow pacevedom to apply cherry-pick-approved

### PR DESCRIPTION
**Pull request by pmtk**
For PRs not needing QE like rebase job related

### CODE REVIEW

**Comment by pmtk** [comment]
/hold
waiting for QE's take on this

**Comment by jogeo** [comment]
We discussed this within the MicroShift team and I don't have any objection to adding pacevedom to the list of users who can apply the cherry-pick-approved label. The goal is to avoid delaying changes, such as those for CI, that do not require QE testing.  Let's just be sure not to use this for landing anything that requires QE effort.

**Pull request merged**
