### PR TITLE
OCPEDGE-1124: Ibi installer

### PR DESCRIPTION
**Pull request by jeff-roche**

### CODE REVIEW

**Review by javipolo — APPROVED** [review]

**Comment by jeff-roche** [comment]
/pj-rehearse pull-ci-openshift-kni-lifecycle-agent-main-ibi-e2e-flow

**Comment by jeff-roche** [comment]
/pj-rehearse pull-ci-openshift-kni-lifecycle-agent-main-ibi-e2e-flow

**Pull request merged**
