### PR TITLE
Add basic os test on vexxhost

### PR DESCRIPTION
**Pull request by viroel**
This patch adds a first e2e test to validate the new openstack-k8s-operators vexxhost clusterprofile.

### CODE REVIEW

**Comment by viroel** [comment]
/test e2e-openstack

not sure if triggers without removing the appropriate label

**Review by abays — APPROVED** [review]
/lgtm

**Comment by viroel** [comment]
/hold
We need to replace our openstack tenant.
We will try a bigger flavor with env variables.

**Comment by viroel** [comment]
/retest

Cloud certificate was added to vault. Lets see if that works.

**Comment by viroel** [comment]
/retest

cloud provider changed

**Comment by viroel** [comment]
Closing this PR since we plan to continue working with Hive, instead of using cluster profiles.

**Pull request closed without merging**
