### PR TITLE
Change NVIDIA GPU Operator CI to use aws-edge-infra profile

### PR DESCRIPTION
**Pull request by empovit**

### CODE REVIEW

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.14-nvidia-gpu-operator-e2e-23-9-x

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.14-nvidia-gpu-operator-e2e-23-9-x

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.14-nvidia-gpu-operator-e2e-23-9-x

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.14-nvidia-gpu-operator-e2e-23-9-x

**Review by fabiendupont — APPROVED** [review]
/lgtm

**Pull request merged**
