### PR TITLE
ceph-csi: add configuration for Bugzilla plugin

### PR DESCRIPTION
**Pull request by nixpanic**
This configuration is based on the settings from the ocs-operator
repository in the same section.

### CODE REVIEW

**Comment by nixpanic** [comment]
This seems to be needed as openshift/ceph-csi#22 contains a comment from openshift-ci-robot:

> expected the bug to target the "4.8.0" release, but it targets "OCS 4.8.0" instead

**Comment by agarwal-mudit** [comment]
This is a good thing to have, just one thing to note here: sometimes this check will fail because either we don't have a bug or bug is not in the state we the bot want it to be. In that case someone having access rights to the repo can only override that else merge will not happen.

**Comment by nixpanic** [comment]
> This is a good thing to have, just one thing to note here: sometimes this check will fail because either we don't have a bug or bug is not in the state we the bot want it to be. In that case someone having access rights to the repo can only override that else merge will not happen.

Yes, people mentioned in the `OWNERS` file should be able to override the label.

**Review by agarwal-mudit — APPROVED** [review]

**Comment by nixpanic** [comment]
/test build02-dry

Some i/o timeouts caused a failure, maybe infrastructure related?

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
