### PR TITLE
only level0 tests as identified by qe

### PR DESCRIPTION
**Pull request by miyadav**
@sunzhaohua2 @huali9 @shellyyang1989 PTAL when time permits , CCMO repo looks a good repo for these cases at the moment.

### CODE REVIEW

**Comment by miyadav** [comment]
/pj-rehearse pull-ci-openshift-cluster-cloud-controller-manager-operator-master-level0-clusterinfra-azure-ipi-proxy-tests

**Comment by shellyyang1989** [comment]
lgtm. leaving it to others for review.

**Comment by miyadav** [comment]
/pj-rehearse pull-ci-openshift-cluster-cloud-controller-manager-operator-master-level0-clusterinfra-azure-ipi-proxy-tests

**Comment by JoelSpeed** [comment]
@miyadav Is there somewhere where we can see the test suite that this is running?

At the moment the job doesn't create a JUnit output so we can't see the pass/fail of individual cases on the prow screen. Not a blocker but would be nice to have at some point if that's possible with the tooling you're using

**Comment by miyadav** [comment]
> > @miyadav Is there somewhere where we can see the test suite that this is running?
> > At the moment the job doesn't create a JUnit output so we can't see the pass/fail of individual cases on the prow screen. Not a blocker but would be nice to have at some point if that's possible with the tooling you're using
> 
> I am trying that facing some permission issues at the moment.

@JoelSpeed issue resolved , will add to other PRs and this one next week. Thanks

**Comment by miyadav** [comment]
/pj-rehearse pull-ci-openshift-cluster-cloud-controller-manager-operator-master-level0-clusterinfra-azure-ipi-proxy-tests

**Comment by miyadav** [comment]
@JoelSpeed 
[here](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/50843/rehearse-50843-pull-ci-openshift-cluster-cloud-controller-manager-operator-master-level0-clusterinfra-azure-ipi-proxy-tests/1783840551729106944/artifacts/level0-clusterinfra-azure-ipi-proxy-tests/openshift-extended-test/artifacts/) is junit now

**Comment by miyadav** [comment]
thanks @JoelSpeed , resolved conflict , see if label needs to be readded.

**Pull request merged**
