### PR TITLE
assisted installer capi: add e2e tests

### PR DESCRIPTION
**Pull request by rccrdpccl**
add e2e tests for CAPI OpenshiftAssisted bootstrap/controlplane provider

### CODE REVIEW

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-cap

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-cap

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-cap

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi

**Comment by rccrdpccl** [comment]
The idea would be executing multinode e2e tests after master merges and on demand on PRs, as it's quite expensive to run.

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi-multinode

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi-multinode

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi-multinode

**Comment by rccrdpccl** [comment]
/pj-rehearse pull-ci-openshift-assisted-cluster-api-agent-master-e2e-capi-multinode

**Review by adriengentil — APPROVED** [review]

**Pull request merged**
