### PR TITLE
MGMT-18856: add mtv operator

### PR DESCRIPTION
**Pull request by eifrach**
depends on 
- [#2548](https://github.com/openshift/assisted-test-infra/pull/2548)
- [#6711](https://github.com/openshift/assisted-service/pull/6711)

### CODE REVIEW

**Comment by eifrach** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-mtv-4-17

**Review by danmanor — APPROVED** [review]

**Comment by danmanor** [comment]
nothing to test until the PRs are merged

**Pull request merged**
