### PR TITLE
Chaos profile and cadence schedule

### PR DESCRIPTION
**Pull request by paigerube14**
Cadence schedule updates and profile for chaos

### CODE REVIEW

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-rosa-4.14-nightly-ocp-qe-perfscale-ci-tests-rosa-hog periodic-ci-redhat-chaos-krkn-hub-main-4.15-nightly-krkn-hub-tests-415

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-rosa-4.14-nightly-ocp-qe-perfscale-ci-tests-rosa-hog periodic-ci-redhat-chaos-krkn-hub-main-4.15-nightly-krkn-hub-tests-415

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.15-nightly-krkn-hub-tests-415

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.15-nightly-krkn-hub-tests-415

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.15-nightly-krkn-hub-tests-415

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.15-nightly-krkn-hub-tests-415

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.15-nightly-krkn-hub-tests-415

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.15-nightly-krkn-hub-tests-415

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-rosa-4.14-nightly-ocp-qe-perfscale-ci-tests-rosa-hog

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-rosa-4.14-nightly-ocp-qe-perfscale-ci-tests-rosa-hog

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-rosa-4.14-nightly-ocp-qe-perfscale-ci-tests-rosa-hog

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.15-nightly-krkn-hub-tests-415

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-rosa-4.14-nightly-ocp-qe-perfscale-ci-tests-rosa-hog

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.15-nightly-krkn-hub-tests-415

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-rosa-4.14-nightly-ocp-qe-perfscale-ci-tests-rosa-hog

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-rosa-4.14-nightly-ocp-qe-perfscale-ci-tests-rosa-hog

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.15-nightly-krkn-hub-tests-415

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-4.15-nightly-krkn-hub-tests-415

**Comment by paigerube14** [comment]
@chaitanyaenr thoughts on this pr, the cadences are updated and the self-managed clusters are creating as expected

**Pull request merged**
