### PR TITLE
OCPQE-22302 fix typo in 4.6->4.16 amd64 job

### PR DESCRIPTION
**Pull request by dis016**
[OCPQE-22302](https://issues.redhat.com//browse/OCPQE-22302) fix typo in job  openshift-openshift-tests-private-release-4.16__amd64-nightly-4.16-upgrade-from-stable-4.6.yaml for profile gcp-ipi-proxy-private-f30 
/cc @shellyyang1989 @JianLi-RH @jianlinliu @jiajliu @evakhoni

### CODE REVIEW

**Comment by dis016** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-4.16-upgrade-from-stable-4.6-gcp-ipi-proxy-private-f30

**Comment by jianlinliu** [comment]
cc @liangxia to review.

**Pull request merged**
