### PR TITLE
ROSA hypershift cluster should use BYO OIDC as default

### PR DESCRIPTION
**Pull request by yasun1**
update

### CODE REVIEW

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-kiali-kiali-master-kiali-hypershift-4.12-lp-rosa-hypershift-aws-lp-rosa-hypershift-412

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-kiali-kiali-master-kiali-hypershift-4.12-lp-rosa-hypershift-aws-lp-rosa-hypershift-412

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-maistra-maistra-test-tool-main-servicemesh-hypershift-4.13-lp-rosa-hypershift-servicemesh-aws-rosa-hypershift periodic-ci-kiali-kiali-master-kiali-hypershift-4.12-lp-rosa-hypershift-aws-lp-rosa-hypershift-412

**Comment by yasun1** [comment]
The changes are passed on openshift 4.13, but fail at 4.12. I believe the 4.12 issue is the provisioning issue but not related to the current changes.  

@madunn @xueli181114 Please help review. Thanks.

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.12-acceptance-lp-rosa-hypershift-412

**Comment by ascerra** [comment]
> The changes are passed on openshift 4.13, but fail at 4.12. I believe the 4.12 issue is the provisioning issue but not related to the current changes.
> 
> @madunn @xueli181114 Please help review. Thanks.

@yasun1 I believe the failure that we are seeing in the 4.12 version needs to be escalated beyond just this PR. Without the changes that you have made we are seeing consistent failures in this step for rosa-sts-hypershift testing on 4.12
- Here is a dashboard showing all failed jobs for this testing this week ([Sippy rosa-sts-hypershift-4.12](https://sippy.dptools.openshift.org/sippy-ng/jobs/4.12/runs?filters=%257B%2522items%2522%253A%255B%257B%2522id%2522%253A99%252C%2522columnField%2522%253A%2522job%2522%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522-lp-rosa%2522%257D%252C%257B%2522columnField%2522%253A%2522timestamp%2522%252C%2522operatorValue%2522%253A%2522%253E%253D%2522%252C%2522value%2522%253A%25221694988120000%2522%257D%255D%252C%2522linkOperator%2522%253A%2522and%2522%257D))

**Comment by droslean** [comment]
/hold

Temporary holding to unblock the queue

**Pull request merged**
