### PR TITLE
telco5g: Pin CNF tests repo version to pre-v2 version

### PR DESCRIPTION
**Pull request by sshnaidm**
We need time to adjust our CI to use Ginkgo v2, pin the version of repo for now to one before the move to v2.

### CODE REVIEW

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-telco5g-cnftests

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-telco5g-cnftests

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.12-e2e-telco5g-cnftests

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-telco5g-cnftests

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-telco5g

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-telco5g-cnftests

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-telco5g

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-telco5g-cnftests

**Comment by yanirq** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-telco5g-cnftests

**Pull request merged**
