### PR TITLE
USHIFT-289: add e2e-greenboot-arm

### PR DESCRIPTION
**Pull request by pmtk**

### CODE REVIEW

**Comment by ggiguash** [comment]
@pmtk, this change is LGTM. I'm also putting it on hold to let you rehearse until we're confident with the stability, etc. Feel free to unhold and merge once you're ready.

/lgtm
/hold

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.13-e2e-greenboot

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.13-e2e-greenboot-arm pull-ci-openshift-microshift-release-4.15-e2e-greenboot-arm pull-ci-openshift-microshift-main-e2e-greenboot-arm pull-ci-openshift-microshift-release-4.14-e2e-greenboot-arm

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.15-e2e-greenboot

**Comment by pmtk** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.15-e2e-greenboot

**Pull request merged**
