### PR TITLE
Update trustyai-explainability-trustyai-explainability-main.yaml

### PR DESCRIPTION
**Pull request by spolti**

### CODE REVIEW

**Comment by ruivieira** [comment]
@spolti Do we also need to change ci-operator/config/trustyai-explainability/trustyai-service-operator/trustyai-explainability-trustyai-service-operator-main.yaml?

**Review by ruivieira — CHANGES_REQUESTED** [review]
LGTM, just needing the same change on the operator.

thanks @spolti

**Comment by spolti** [comment]
> @spolti Do we also need to change ci-operator/config/trustyai-explainability/trustyai-service-operator/trustyai-explainability-trustyai-service-operator-main.yaml?

Hi @ruivieira, before applying there, would be good to merge this first to test, wdyt?

**Comment by RobGeada** [comment]
@spolti https://github.com/openshift/release/pull/52874 replaces this PR: it adds the config to the operator CI as well as uses ubi instead of ubi-minimal

**Comment by spolti** [comment]
okay

**Pull request closed without merging**
