### PR TITLE
stackrox: ROX-11697 add support for OSD GCP

### PR DESCRIPTION
**Pull request by gavin-stackrox**
This PR adds e2e tests for OSD GCP. And consolidates the automation-flavors workflow a little.

Requires: https://github.com/openshift/release/pull/31050

/hold
/uncc

### CODE REVIEW

**Comment by gavin-stackrox** [comment]
test

**Review by sbostick — APPROVED** [review]
Source changes LGTM

Any concern with the ci/rehearse/stackrox/stackrox/nightlies/images failure?
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/31051/rehearse-31051-pull-ci-stackrox-stackrox-nightlies-images/1554984656988803072

**Pull request merged**
