### PR TITLE
Kiali - expand rosa-hypershift testing to OCP 4.12

### PR DESCRIPTION
**Pull request by ascerra**

### CODE REVIEW

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-kiali-kiali-master-kiali-hypershift-4.12-lp-rosa-hypershift-aws-lp-rosa-hypershift-412

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-kiali-kiali-master-kiali-hypershift-4.12-lp-rosa-hypershift-aws-lp-rosa-hypershift-412

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
