### PR TITLE
[LPTOCPCI-819] Test Jboss Fuse 7.12 after CVE changes

### PR DESCRIPTION
**Pull request by smongiar**

### CODE REVIEW

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.14-lp-interop-jboss-fuse-interop-aws

**Comment by anramesh27** [comment]
lgtm

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.15-lp-interop-jboss-fuse-interop-aws

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.15-lp-interop-jboss-fuse-interop-aws

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.15-lp-interop-jboss-fuse-interop-aws

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.15-lp-interop-jboss-fuse-interop-aws

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.15-lp-interop-jboss-fuse-interop-aws

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.15-lp-interop-jboss-fuse-interop-aws

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.15-lp-interop-jboss-fuse-interop-aws

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.15-lp-interop-jboss-fuse-interop-aws

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.15-lp-interop-jboss-fuse-interop-aws

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.15-lp-interop-jboss-fuse-interop-aws

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.15-lp-interop-jboss-fuse-interop-aws

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.15-lp-interop-jboss-fuse-interop-aws

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.15-lp-interop-jboss-fuse-interop-aws

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.15-lp-interop-jboss-fuse-interop-aws

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.15-lp-interop-jboss-fuse-interop-aws

**Comment by anramesh27** [comment]
lgtm

**Review by petrpinkas — APPROVED** [review]
Approved

**Pull request merged**
