### PR TITLE
Enable label-sync for package-operator Org

### PR DESCRIPTION
**Pull request by thetechnick**
Signed-off-by: Nico Schieder <nschieder@redhat.com>

### CODE REVIEW

**Review by apahim — APPROVED** [review]
/lgtm

**Comment by thetechnick** [comment]
```
time="2022-10-13T16:27:11Z" level=info msg="no jobs to rehearse have been found" org=openshift repo=release
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1d6463e]
goroutine 1 [running]:
main.rehearseMain()
	/go/src/github.com/openshift/ci-tools/cmd/pj-rehearse/main.go:[15](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/33101/pull-ci-openshift-release-master-pj-rehearse/1580595478188265472#1:build-log.txt%3A15)9 +0x105e
main.main()
	/go/src/github.com/openshift/ci-tools/cmd/pj-rehearse/main.go:[17](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/33101/pull-ci-openshift-release-master-pj-rehearse/1580595478188265472#1:build-log.txt%3A17)6 +0x[19](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/33101/pull-ci-openshift-release-master-pj-rehearse/1580595478188265472#1:build-log.txt%3A19)
```
Looks like we found a bug in the rehearse job :)

**Comment by danilo-gemoli** [comment]
@smg247 is it something you're already familiar with?

**Review by droslean — APPROVED** [review]

**Pull request merged**
