### PR TITLE
Stop using legacy folder for OpenStack CSIs jobs

### PR DESCRIPTION
**Pull request by MaysaMacedo**
depends on https://github.com/openshift/csi-operator/pull/316

### CODE REVIEW

**Comment by gnufied** [comment]
/pj-rehearse pull-ci-openshift-kubernetes-master-e2e-openstack-csi-cinder

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-kubernetes-master-e2e-openstack-csi-cinder
/pj-rehearse pull-ci-openshift-kubernetes-master-e2e-openstack-csi-manila

[workers failed to fetch ignition](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/58561/rehearse-58561-pull-ci-openshift-kubernetes-master-e2e-openstack-csi-cinder/1854563907734081536/artifacts/e2e-openstack-csi-cinder/openstack-gather/artifacts/nodes/console_907s3hn9-c1a6a-q9wgv-worker-0-4xbwv.log), It might have a temporary issue. I'm retrying... 

```
[  141.726853] ignition[902]: GET error: Get "https://10.0.0.5:22623/config/worker": dial tcp 10.0.0.5:22623: connect: connection refused
[  146.727958] ignition[902]: GET https://10.0.0.5:22623/config/worker: attempt #33
```

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-kubernetes-master-e2e-openstack-csi-manila

**Comment by gnufied** [comment]
specifically some of the storage related tests are failing here:

```
 	1m48s
{  fail [k8s.io/kubernetes@v1.31.1/test/e2e/framework/volume/fixtures.go:704]: "test -b /mnt/volume2" should fail with exit code 1, but failed with error message "error sending request: Post \"https://api.vmncvf3c-c1a6a.shiftstack.devcluster.openshift.com:6443/api/v1/namespaces/e2e-multivolume-4023/pods/pod-74e0084d-d8ec-4300-89bc-da223c653da8/exec?command=%2Fbin%2Fsh&command=-c&command=test+-b+%2Fmnt%2Fvolume2&container=write-pod&container=write-pod&stderr=true&stdout=true\": CONNECT request to http://openstack-nfv:xxxxx@38.102.83.230:3128/ returned response: 503 Service Unavailable"
stdout: 
stderr: : error sending request: Post "https://api.vmncvf3c-c1a6a.shiftstack.devcluster.openshift.com:6443/api/v1/namespaces/e2e-multivolume-4023/pods/pod-74e0084d-d8ec-4300-89bc-da223c653da8/exec?command=%2Fbin%2Fsh&command=-c&command=test+-b+%2Fmnt%2Fvolume2&container=write-pod&container=write-pod&stderr=true&stdout=true": CONNECT request to http://openstack-nfv:xxxxx@38.102.83.230:3128/ returned response: 503 Service Unavailable
Ginkgo exit error 1: exit with code 1}
```

**Comment by gnufied** [comment]
@stephenfin @MaysaMacedo can you please confirm if failure here is expected? If so, feel free to add `pj-rehearsals` ack and remove the hold.

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-kubernetes-master-e2e-openstack-csi-cinder

The failures on the job looks unrelated to the change. It looks like it failed to connect to a proxy, I'm gonna give the job another try in any case.

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-kubernetes-master-e2e-openstack-csi-cinder

**Comment by stephenfin** [comment]
/pj-rehearse pull-ci-openshift-kubernetes-master-e2e-openstack-csi-cinder

Different failures from the previous run so I suspect this is a slow node, but I would like to see at least one pass before we merge

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-kubernetes-master-e2e-openstack-csi-manila

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-kubernetes-master-e2e-openstack-csi-manila

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-kubernetes-master-e2e-openstack-csi-manila

**Comment by MaysaMacedo** [comment]
/hold cancel
manila job only had two test failures related to OCP API not being available. I'm removing the hold.

**Pull request merged**
