### PR TITLE
MGMT-16249: Clean old OCP jobs in assisted-installer components

### PR DESCRIPTION
**Pull request by danmanor**
Clean old `OCP` jobs ` assisted-installer` components

### CODE REVIEW

**Review by adriengentil — APPROVED** [review]

**Comment by adriengentil** [comment]
you don't really need to rehearse, you mainly removed jobs

**Comment by danmanor** [comment]
@adriengentil WDYT? should I rehearse now?

**Review by adriengentil — APPROVED** [review]

**Comment by adriengentil** [comment]
>should I rehearse now?

no, just go ahead

**Pull request merged**
