### PR TITLE
Log Check for oadp gather dir check and increase timeout

### PR DESCRIPTION
**Pull request by smatula**

### CODE REVIEW

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-oadp-qe-oadp-qe-automation-main-oadp1.4-ocp4.16-lp-interop-oadp-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-oadp-qe-oadp-qe-automation-main-oadp1.4-ocp4.16-lp-interop-oadp-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-oadp-qe-oadp-qe-automation-main-oadp1.4-ocp4.16-lp-interop-oadp-interop-ibmcloud

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-oadp-qe-oadp-qe-automation-main-oadp1.4-ocp4.16-lp-interop-oadp-interop-ibmcloud

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
