### PR TITLE
Rename CNV interop jobs name and move to old cluster-profile

### PR DESCRIPTION
**Pull request by rabin-io**

### CODE REVIEW

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.16-ocp-cnv-odf-4.16-cnv-odf-tests-aws-upi-ocp416

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.16-ocp-cnv-odf-4.16-cnv-odf-tests-aws-upi-ocp416

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.16-ocp-cnv-odf-4.16-cnv-odf-tests-aws-upi-ocp416

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.16-ocp-cnv-odf-4.16-cnv-odf-tests-aws-upi-ocp416

**Review by lukas-bednar — APPROVED** [review]
/lgtm

**Pull request merged**
