### PR TITLE
[WIP] Bug 1829475: Updating AWS UPI proxy to blackhole the private subnets

### PR DESCRIPTION
**Pull request by ewolinetz**
This updates the VPC for the proxy case such that we remove the public subnet NATs that allow the private subnets to have external internet access and instead route all non-cluster traffic through the proxy.

We are also restricting port `3128` and `3130` access to the proxy node to just the `MACHINE_CIDR`.

Also since the ingress operator will not have direct access to the amazon route53 endpoint we remove DNS zones [1] and manually create route entries [2].

This PR depends on https://github.com/openshift/release/pull/4719

[1] https://github.com/openshift/installer/blob/master/docs/user/aws/install_upi.md#remove-dns-zones
[2] https://github.com/openshift/installer/blob/master/docs/user/aws/install_upi.md#add-the-ingress-dns-records

### CODE REVIEW

**Comment by ewolinetz** [comment]
cc @wking @danehans @bparees

**Comment by ewolinetz** [comment]
current proxy failing to start issue dependent on https://github.com/openshift/release/pull/5799

**Comment by eparis** [comment]
```
Nov 06 19:02:13 ip-10-0-13-58 release-image-download.sh[1479]: Pull failed. Retrying registry.svc.ci.openshift.org/ci-op-xkn24jg1/release@sha256:6b8ae182d5605093260b3dcaff95c8d1c55cf3ce827195841869cff33a628ef8...
Nov 06 19:03:03 ip-10-0-13-58 release-image-download.sh[1479]: time="2019-11-06T19:03:03Z" level=error msg="Error pulling image ref //registry.svc.ci.openshift.org/ci-op-xkn24jg1/release@sha256:6b8ae182d5605093260b3dcaff95c8d1c55cf3ce827195841869cff33a628ef8: Error initializing source docker://registry.svc.ci.openshift.org/ci-op-xkn24jg1/release@sha256:6b8ae182d5605093260b3dcaff95c8d1c55cf3ce827195841869cff33a628ef8: pinging docker registry returned: Get https://registry.svc.ci.openshift.org/v2/: proxyconnect tcp: dial tcp 10.0.68.238:3130: i/o timeout"
```

**Comment by ewolinetz** [comment]
currently failing tests
```
[Conformance][Area:Networking][Feature:Router] The HAProxy router should respond with 503 to unrecognized hosts [Suite:openshift/conformance/parallel/minimal]
[Conformance][Area:Networking][Feature:Router] The HAProxy router should serve routes that were created from an ingress [Suite:openshift/conformance/parallel/minimal]
[Conformance][Area:Networking][Feature:Router] The HAProxy router should support reencrypt to services backed by a serving certificate automatically [Suite:openshift/conformance/parallel/minimal]
[Feature:Builds] build have source revision metadata  started build should contain source revision information [Suite:openshift/conformance/parallel]
[Feature:ImageAppend] Image append should create images by appending them [Suite:openshift/conformance/parallel]
[Feature:ImageInfo] Image info should display information about images [Suite:openshift/conformance/parallel]
[Feature:Platform] Managed cluster should should expose cluster services outside the cluster [Suite:openshift/conformance/parallel]
[sig-network] Networking should provide Internet connection for containers [Feature:Networking-IPv4] [Suite:openshift/conformance/parallel] [Suite:k8s] [Skipped:azure]

# known issues #
[sig-network] Networking Granular Checks: Services should function for endpoint-Service: udp [Suite:openshift/conformance/parallel] [Suite:k8s] [Skipped:Network/OVNKubernetes]
[sig-network] Networking Granular Checks: Services should function for node-Service: udp [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-network] Networking Granular Checks: Services should function for pod-Service: udp [Suite:openshift/conformance/parallel] [Suite:k8s]
# known issues #
```

**Comment by danehans** [comment]
```
[Conformance][Area:Networking][Feature:Router] The HAProxy router should respond with 503 to unrecognized hosts"
```
The above test makes this call:
```
curl -X GET -H "Host:www.google.com"  -s -S -o /tmp/body -D /tmp/headers "https://aa823f02548cb431c87c6726e503da9b-777821837.us-east-1.elb.amazonaws.com" -w '{"code":%{http_code}}' -k 2>/tmp/error 1>/tmp/output || rc=$?
```

and expects the router to return a `503` http error code, but the following error occurred:
```
Nov 11 23:41:00.350: INFO: stdout: "{\"test\":0,\"rc\":7,\"curl\":{\"code\":000},\"error\":\"curl: (7) Failed connect to aa823f02548cb431c87c6726e503da9b-777821837.us-east-1.elb.amazonaws.com:443; Operation now in progress\\n\",\"body\":\"\",\"headers\":\"\"}\n"
```
 
`aa823f02548cb431c87c6726e503da9b-777821837.us-east-1.elb.amazonaws.com` is the dns name of the elb front-ending the router. Since `amazonaws.com` is not automatically added to `noProxy`, I would expect this call to go through the proxy. Are you able to review the proxy logs to verify? I could not find the proxy logs in the artifacts. If this is the case, I don't believe it's the desired behavior for the CI environment. ELB is a [supported](https://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/load-balancer-vpc-endpoints.html) vpc endpoint. Can you confirm that the vpc is configured with the elb endpoint? If so, `${AWS_REGION}.elb.amazonaws.com` should be added to `noProxy` of the installer config so the connection is routed over the aws private link to the elb api?

**Comment by danehans** [comment]
```
[Conformance][Area:Networking][Feature:Router] The HAProxy router should serve routes that were created from an ingress
```

The above test fails due to the execpod (client) making these calls:
```
# Test: 0
rc=0
: > /tmp/body /tmp/headers
curl -X GET -H "Host:1.ingress-test.com"  -s -S -o /tmp/body -D /tmp/headers "http://aa823f02548cb431c87c6726e503da9b-777821837.us-east-1.elb.amazonaws.com/test" -w '{"code":%{http_code}}' 2>/tmp/error 1>/tmp/output || rc=$?
echo "{\"test\":0,\"rc\":$(echo $rc),\"curl\":$(cat /tmp/output),\"error\":$(cat /tmp/error | json_escape),\"body\":\"$(cat /tmp/body | base64 -w 0 -)\",\"headers\":$(cat /tmp/headers | json_escape)}"
# Test: 1
rc=0
: > /tmp/body /tmp/headers
curl -X GET -H "Host:1.ingress-test.com"  -s -S -o /tmp/body -D /tmp/headers "http://aa823f02548cb431c87c6726e503da9b-777821837.us-east-1.elb.amazonaws.com/other/deep" -w '{"code":%{http_code}}' 2>/tmp/error 1>/tmp/output || rc=$?
echo "{\"test\":1,\"rc\":$(echo $rc),\"curl\":$(cat /tmp/output),\"error\":$(cat /tmp/error | json_escape),\"body\":\"$(cat /tmp/body | base64 -w 0 -)\",\"headers\":$(cat /tmp/headers | json_escape)}"
# Test: 2
rc=0
: > /tmp/body /tmp/headers
curl -X GET -H "Host:1.ingress-test.com"  -s -S -o /tmp/body -D /tmp/headers "http://aa823f02548cb431c87c6726e503da9b-777821837.us-east-1.elb.amazonaws.com/" -w '{"code":%{http_code}}' 2>/tmp/error 1>/tmp/output || rc=$?
echo "{\"test\":2,\"rc\":$(echo $rc),\"curl\":$(cat /tmp/output),\"error\":$(cat /tmp/error | json_escape),\"body\":\"$(cat /tmp/body | base64 -w 0 -)\",\"headers\":$(cat /tmp/headers | json_escape)}"
# Test: 3
rc=0
: > /tmp/body /tmp/headers
curl -X GET -H "Host:2.ingress-test.com"  -s -S -o /tmp/body -D /tmp/headers "http://aa823f02548cb431c87c6726e503da9b-777821837.us-east-1.elb.amazonaws.com/" -w '{"code":%{http_code}}' 2>/tmp/error 1>/tmp/output || rc=$?
echo "{\"test\":3,\"rc\":$(echo $rc),\"curl\":$(cat /tmp/output),\"error\":$(cat /tmp/error | json_escape),\"body\":\"$(cat /tmp/body | base64 -w 0 -)\",\"headers\":$(cat /tmp/headers | json_escape)}"
# Test: 4
rc=0
: > /tmp/body /tmp/headers
curl -X GET -H "Host:3.ingress-test.com"  -s -S -o /tmp/body -D /tmp/headers "https://aa823f02548cb431c87c6726e503da9b-777821837.us-east-1.elb.amazonaws.com/" -w '{"code":%{http_code}}' -k 2>/tmp/error 1>/tmp/output || rc=$?
echo "{\"test\":4,\"rc\":$(echo $rc),\"curl\":$(cat /tmp/output),\"error\":$(cat /tmp/error | json_escape),\"body\":\"$(cat /tmp/body | base64 -w 0 -)\",\"headers\":$(cat /tmp/headers | json_escape)}"
# Test: 5
rc=0
: > /tmp/body /tmp/headers
curl -X GET -H "Host:3.ingress-test.com"  -s -S -o /tmp/body -D /tmp/headers "http://aa823f02548cb431c87c6726e503da9b-777821837.us-east-1.elb.amazonaws.com/" -w '{"code":%{http_code}}' 2>/tmp/error 1>/tmp/output || rc=$?
echo "{\"test\":5,\"rc\":$(echo $rc),\"curl\":$(cat /tmp/output),\"error\":$(cat /tmp/error | json_escape),\"body\":\"$(cat /tmp/body | base64 -w 0 -)\",\"headers\":$(cat /tmp/headers | json_escape)}"'
```
As with https://github.com/openshift/release/pull/5308#issuecomment-553187887, the tests are trying to connect to the aws elb dns name front-ending the router and similar verification/remediation steps should be followed.

**Comment by danehans** [comment]
```
[Conformance][Area:Networking][Feature:Router] The HAProxy router should support reencrypt to services backed by a serving certificate automatically
```

The above test also connects to the aws elb public dns name front-ending the router and will require the same verification/remediation steps as https://github.com/openshift/release/pull/5308#issuecomment-553187887.

**Comment by ewolinetz** [comment]
@danehans we don't want to add those to `noProxy` because the cluster does not have direct egress access to the internet... it would need to go through the proxy to reach any AWS endpoints.
Is it possible I need to add another route53 entry? Currently we have `*.apps.${CLUSTER_NAME}.${base_domain}` only for the internal and external hosted zones

**Comment by danehans** [comment]
@ewolinetz [vpc endpoints](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints.html) provide a mechanism for routing traffic to aws api endpoints and services without having to traverse the public network (Internet). The ELB service is a supported vpc endpoint, so cluster components should be configured not to proxy connections to <aws_region>.elb.amazonaws.com.

If calls to the aws elb service **must** go through the proxy, then the client (i.e. execpod) needs to be configured for proxy. Otherwise, the client will use a typical transport when making the call.

**Comment by danehans** [comment]
After https://github.com/openshift/cluster-ingress-operator/pull/334 merges, https://github.com/openshift/release/pull/5308/files#diff-2b1b845b92f8062711789a2bfdb27290R2604-R2616 should be removed b/c the ingress operator will support managing ingress wildcard records in a proxied environment.

**Comment by danehans** [comment]
@ewolinetz looks like the latest CI failure is due to:
```
http://base-4-4.ocp.svc/rhel-server-ose/repodata/e240e3a850cef8498605cb5ad42da9c7931d69f6cfe41a1b991276002f4a4a72-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below knowledge base article 

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.

http://base-4-4.ocp.svc/rhel-server-ose/repodata/e240e3a850cef8498605cb5ad42da9c7931d69f6cfe41a1b991276002f4a4a72-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://base-4-4.ocp.svc/rhel-server-ose/repodata/e240e3a850cef8498605cb5ad42da9c7931d69f6cfe41a1b991276002f4a4a72-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
```

Let me know if you need assistance with the PR.

**Comment by danehans** [comment]
@ewolinetz the latest CI run failed b/c the auth operator is reporting a `Degraded=True` status condition. The condition is triggered due to this error:
```
2020-01-13T22:16:25.959283233Z E0113 22:16:25.959206       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: failed handling the route: route is not available at canonical host oauth-openshift.apps.ci-op-dwlzj721-4c649.origin-ci-int-aws.dev.rhcloud.com: []
```

I opened [bz 1790999](https://bugzilla.redhat.com/show_bug.cgi?id=1790999) to get assistance from the auth team in troubleshotting the issue.

**Comment by danehans** [comment]
After further investigation, the issue appears to be a UPI misconfiguration. The oauth route is unavailable b/c the ingress operator never creates the wildcard dns record for the route:

```
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  creationTimestamp: "2020-01-13T21:55:58Z"
  finalizers:
  - ingresscontroller.operator.openshift.io/finalizer-ingresscontroller
  generation: 1
  name: default
  namespace: openshift-ingress-operator
  resourceVersion: "14427"
  selfLink: /apis/operator.openshift.io/v1/namespaces/openshift-ingress-operator/ingresscontrollers/default
  uid: dda04a46-d701-4833-8c1f-6f4999ae0b4f
spec:
  endpointPublishingStrategy:
    loadBalancer:
      scope: Internal
    type: LoadBalancerService
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2020-01-13T22:16:40Z"
    reason: Valid
    status: "True"
    type: Admitted
  - lastTransitionTime: "2020-01-13T22:17:14Z"
    status: "True"
    type: Available
  - lastTransitionTime: "2020-01-13T22:17:14Z"
    message: The deployment has Available status condition set to True
    reason: DeploymentAvailable
    status: "False"
    type: DeploymentDegraded
  - lastTransitionTime: "2020-01-13T22:16:44Z"
    message: The endpoint publishing strategy supports a managed load balancer
    reason: WantedByEndpointPublishingStrategy
    status: "True"
    type: LoadBalancerManaged
  - lastTransitionTime: "2020-01-13T22:16:51Z"
    message: The LoadBalancer service is provisioned
    reason: LoadBalancerProvisioned
    status: "True"
    type: LoadBalancerReady
  - lastTransitionTime: "2020-01-13T22:16:44Z"
    message: No DNS zones are defined in the cluster dns config.
    reason: NoDNSZones
    status: "False"
    type: DNSManaged
  - lastTransitionTime: "2020-01-13T22:17:14Z"
    status: "False"
    type: Degraded
  domain: apps.ci-op-dwlzj721-4c649.origin-ci-int-aws.dev.rhcloud.com
  endpointPublishingStrategy:
    loadBalancer:
      scope: Internal
    type: LoadBalancerService
  observedGeneration: 1
  selector: ingresscontroller.operator.openshift.io/deployment-ingresscontroller=default
  tlsProfile:
    ciphers:
    - TLS_AES_128_GCM_SHA256
    - TLS_AES_256_GCM_SHA384
    - TLS_CHACHA20_POLY1305_SHA256
    - ECDHE-ECDSA-AES128-GCM-SHA256
    - ECDHE-RSA-AES128-GCM-SHA256
    - ECDHE-ECDSA-AES256-GCM-SHA384
    - ECDHE-RSA-AES256-GCM-SHA384
    - ECDHE-ECDSA-CHACHA20-POLY1305
    - ECDHE-RSA-CHACHA20-POLY1305
    - DHE-RSA-AES128-GCM-SHA256
    - DHE-RSA-AES256-GCM-SHA384
    minTLSVersion: VersionTLS12
```

The record is not created b/c no DNS zones are defined in the cluster dns config. Here's an example of what the dns object should look like:
```
$ oc get dnses.config.openshift.io/cluster -o yaml
apiVersion: config.openshift.io/v1
kind: DNS
metadata:
  creationTimestamp: "2020-01-13T18:59:48Z"
  generation: 1
  name: cluster
  resourceVersion: "433"
  selfLink: /apis/config.openshift.io/v1/dnses/cluster
  uid: 1e05972b-06d5-4f4f-a137-cca566643751
spec:
  baseDomain: dhansen.devcluster.openshift.com
  privateZone:
    tags:
      Name: dhansen-slkcg-int
      kubernetes.io/cluster/dhansen-slkcg: owned
  publicZone:
    id: Z3URY6TWQ91KVV
status: {}
```

Your dns config is empty:
```
---
apiVersion: config.openshift.io/v1
items:
- apiVersion: config.openshift.io/v1
  kind: DNS
  metadata:
    creationTimestamp: "2020-01-13T21:55:57Z"
    generation: 1
    name: cluster
    resourceVersion: "433"
    selfLink: /apis/config.openshift.io/v1/dnses/cluster
    uid: 08982628-493d-4536-8379-842be65363bf
  spec:
    baseDomain: ci-op-dwlzj721-4c649.origin-ci-int-aws.dev.rhcloud.com
  status: {}
kind: DNSList
metadata:
  continue: ""
  resourceVersion: "25483"
  selfLink: /apis/config.openshift.io/v1/dnses
```

**Comment by danehans** [comment]
xref: https://bugzilla.redhat.com/show_bug.cgi?id=1788236

**Comment by danehans** [comment]
@ewolinetz after reviewing `ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml`, I think adding [this](https://gist.githubusercontent.com/danehans/9cc346670499bdabca604379fbdcb22a/raw/4eb64858cfc7248d0c46f5bb20b3887a3a2df409/gistfile1.txt) to [here](https://github.com/openshift/release/blob/ffb4700773bd11e16b21986836df56a4d1716243/ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml#L239) will fix the failure.

**Comment by danehans** [comment]
The latest `e2e-aws-proxy` CI job fails with:
```
secret/support created
/bin/bash: -c: line 97: unexpected EOF while looking for matching `"'
```
I think it's due to a missing `"` at the end of each of [these lines](https://github.com/openshift/release/pull/5308/files#diff-2b1b845b92f8062711789a2bfdb27290R243-R245).

**Comment by danehans** [comment]
@ewolinetz looks like the latest run failed due to this error:
```
Unable to connect to the server: proxyconnect tcp: dial tcp: lookup squid.ci-op-q756x5fh-4c649.origin-ci-int-aws.dev.rhcloud.com on 10.142.0.7:53: no such host
error executing jsonpath "{.items[0].status.addresses[?(@.type==\"ExternalIP\")].address}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
	template was:
		{.items[0].status.addresses[?(@.type=="ExternalIP")].address}
	object given to jsonpath engine was:
		map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":"", "selfLink":""}}
```
I believe it's related to [this](https://github.com/openshift/release/pull/5308/files#diff-2b1b845b92f8062711789a2bfdb27290R249-R250). The host is trying to lookup the name of the proxy. DNS lookups should not be proxied.

**Comment by danehans** [comment]
@ewolinetz ptal https://bugzilla.redhat.com/show_bug.cgi?id=1784201. I think it's important that CI cover proxy setting changes. Do you mind creating a story so we can address this need in the near future? cc: @bparees

**Comment by ewolinetz** [comment]
@danehans it looks like we don't want the test container to have the proxy settings exposed to it...

**Comment by danehans** [comment]
build failure:
```
could not wait for build: the build openstack-installer failed after 5m7s with reason DockerBuildFailed: Docker build strategy has failed.
```
/retest

**Comment by ewolinetz** [comment]
@wking @danehans we see the aws-upi proxy rehearse job passing.. we don't do anything with the vsphere or gcp setup as part of this pr, thoughts on moving forward with this bad boy?

**Comment by danehans** [comment]
I'm for proceeding so we can improve our aws proxy coverage. Can you link an issue for adding support for other providers? Maybe update the title of this PR to reflect AWS support.

**Comment by danehans** [comment]
/retitle Bug 1829475: Updating AWS UPI proxy to blackhole the private subnets

**Comment by ewolinetz** [comment]
going to investigate moving this into the multi-step registry instead similar to https://github.com/openshift/release/pull/9904

**Comment by ewolinetz** [comment]
closing in favor of https://github.com/openshift/release/pull/10355

**Pull request closed without merging**
