### PR TITLE
openstack/nfv: disable mastersSchedulable earlier

### PR DESCRIPTION
**Pull request by EmilienM**
Now we'll disable `mastersSchedulable` before applying the
`PerformanceProfile` so the masters won't be rolled out to have the
worker `MachineConfig` applied.

Later the worker's `MachineSet` will be modified to support SR-IOV.

### CODE REVIEW

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.14-e2e-openstack-nfv-intel pull-ci-openshift-sriov-network-operator-release-4.11-e2e-openstack-nfv-hwoffload

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.14-e2e-openstack-nfv-intel periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.12-e2e-openstack-nfv-hwoffload

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.14-e2e-openstack-nfv-intel periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.12-e2e-openstack-nfv-hwoffload

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.14-e2e-openstack-nfv-intel

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.14-e2e-openstack-nfv-mellanox

**Comment by MaysaMacedo** [comment]
we need to check if the failures on the jobs are related to the change in the PR

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.14-e2e-openstack-nfv

**Comment by EmilienM** [comment]
> /pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.14-e2e-openstack-nfv

they aren't (the failure happens before the steps in this PR) but I still want to see 4.14 being green before we land it. However it's good to see that it behaves well on older versions, 4.12 job is green :-)

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.14-e2e-openstack-nfv-intel

**Comment by EmilienM** [comment]
The job still fails on 4.14, for some reason the masters are rolling out a new config, I'm not sure why but that's causing one of the masters to have etcd degraded.

**Comment by EmilienM** [comment]
I'm trying to figure out why the master got rolled out, I'll see if I can reproduce without a PerformanceProfile. Using https://github.com/openshift/release/pull/42440 for debug.

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.14-e2e-openstack-nfv-intel

**Comment by EmilienM** [comment]
We don't need this one anymore, we'll do https://github.com/openshift/release/pull/42478

**Pull request closed without merging**
