### PR TITLE
Undo yearly cron for adhoc tests. 

### PR DESCRIPTION
**Pull request by svetsa-rh**
This change should prevent future tests to force and run these tests as mandatory.

### CODE REVIEW

**Comment by paigerube14** [comment]
I think this will still add these as jobs to run when a pr is opened in the main branch... guess we could move common scripts out of main branch to somewhere else

**Comment by svetsa-rh** [comment]
Thanks Paige, was just going to try testing "config" :-)

**Comment by paigerube14** [comment]
very weird it said all passed but one was listed as failed...

**Pull request merged**
