### PR TITLE
ODF: remove special prow config for ceph-csi repository

### PR DESCRIPTION
**Pull request by nixpanic**
The standard ODF (red-hat-storage) Prow configuration should be sufficient. There have been two Tide queries active, which caused PRs to be merged unintentionally. Using the default configuration will make the behavior easier to understand and is less prone to making mistakes.

/assign agarwal-mudit

### CODE REVIEW

**Review by Rakshith-R — CHANGES_REQUESTED** [review]
OWNERS file seems to be have deleted too. 
I think we leave it as it is.
Other changes lgtm.

**Comment by nixpanic** [comment]
> OWNERS file seems to be have deleted too. I think we leave it as it is. Other changes lgtm.

That is intentional, the whole directory is removed. There is an `OWNERS` file in the parent directory, which manages the standard configuration for the red-hat-storage organization.

**Review by agarwal-mudit — APPROVED** [review]
/lgtm

**Review by Rakshith-R — APPROVED** [review]

**Pull request merged**
