### PR TITLE
TRT-803: Proxy jobs are failing due to test name change

### PR DESCRIPTION
**Pull request by deepsm007**
https://issues.redhat.com/browse/TRT-803

https://github.com/openshift/origin/pull/27688

### CODE REVIEW

**Review by wking — APPROVED** [review]
/lgtm

**Comment by stbenjam** [comment]
@deepsm007 You'll need to leave the old name in to not break earlier releases' proxy jobs

**Comment by stbenjam** [comment]
/hold cancel

N/m, I missed that's how you did it

**Pull request merged**
