### PR TITLE
[4.12] Establish release-controller configurations for 4.13

### PR DESCRIPTION
**Pull request by jmguzik**

### CODE REVIEW

**Comment by jmguzik** [comment]
@jupierce @bparees I would need your approval for this PR due to the mirrors change.

**Comment by jmguzik** [comment]
@xueqzhan @dgoodwin @DennisPeriquet I had to remove one periodic from 4.13 r-c configuration (see: https://github.com/openshift/release/pull/33440/commits/ab261d456c4ba8f2629d29f5b6a684d8fc15ad89). I was not able to get it generated, even though I copied all the configs from 4.12. The result of config check: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/33440/pull-ci-openshift-release-master-release-controller-config/1585227088145682432  If this is something needed, I would like to get your assistance, as I was unable to trace the root cause. We can do it in a separate PR.

**Comment by jmguzik** [comment]
Rehearsals are expected to fail.

**Comment by jmguzik** [comment]
> @xueqzhan @dgoodwin @DennisPeriquet I had to remove one periodic from 4.13 r-c configuration (see: [ab261d4](https://github.com/openshift/release/commit/ab261d456c4ba8f2629d29f5b6a684d8fc15ad89)). I was not able to get it generated, even though I copied all the configs from 4.12. The result of config check: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/33440/pull-ci-openshift-release-master-release-controller-config/1585227088145682432 If this is something needed, I would like to get your assistance, as I was unable to trace the root cause. We can do it in a separate PR.

@DennisPeriquet following this up, is this a manual change? https://github.com/openshift/release/commit/c14a9eaf7543582c83c399810ca9daa179832e53#diff-5a191dc6df89c7b1734db4ee2a53b5235f2d9214994bdf366a51350c8fac7faa

**Comment by xueqzhan** [comment]
> > @xueqzhan @dgoodwin @DennisPeriquet I had to remove one periodic from 4.13 r-c configuration (see: [ab261d4](https://github.com/openshift/release/commit/ab261d456c4ba8f2629d29f5b6a684d8fc15ad89)). I was not able to get it generated, even though I copied all the configs from 4.12. The result of config check: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/33440/pull-ci-openshift-release-master-release-controller-config/1585227088145682432 If this is something needed, I would like to get your assistance, as I was unable to trace the root cause. We can do it in a separate PR.
> 
> @DennisPeriquet following this up, is this a manual change? [c14a9ea#diff-5a191dc6df89c7b1734db4ee2a53b5235f2d9214994bdf366a51350c8fac7faa](https://github.com/openshift/release/commit/c14a9eaf7543582c83c399810ca9daa179832e53#diff-5a191dc6df89c7b1734db4ee2a53b5235f2d9214994bdf366a51350c8fac7faa)

We changed the way the install analysis job was created in https://github.com/openshift/release/pull/32009. I believe it is a manual process per release.

**Pull request merged**
