### PR TITLE
use the steps to deploy cluster rather the chain as rosacli testing d…

### PR DESCRIPTION
**Pull request by yuwang-RH**
"use the steps to deploy cluster rather the chain as rosacli testing don't need the gather step

### CODE REVIEW

**Comment by yuwang-RH** [comment]
@yasun1 Could you help review this PR?

**Comment by yuwang-RH** [comment]
@liangxia Could you help review and approve this PR? Thanks.

**Comment by liangxia** [comment]
> use the steps to deploy cluster rather the chain as rosacli testing don't need the gather step

The gather steps are not for testing purpose, they are used for debugging

**Pull request closed without merging**
