### PR TITLE
dualstack tests: try runing the full e2e test suite

### PR DESCRIPTION
**Pull request by squeed**
/cc @danwinship 
/cc @akiselev1

### CODE REVIEW

**Comment by squeed** [comment]
AFAICT, test failure is weird:

` Trying to pull virthost.ostest.test.metalkube.org:5000/localimages/local-release-image:4.7.0-0.ci.test-2020-12-09-121532-ci-op-py4m178x-ironic... unauthorized: authentication required`

/test pj-rehearse

**Comment by danwinship** [comment]
dev-scripts sets up a local mirror if you're doing ipv6 or dual-stack; I think you're skipping some of the necessary setup for that but not skipping everything that tries to use it

**Comment by squeed** [comment]
> dev-scripts sets up a local mirror if you're doing ipv6 or dual-stack; I think you're skipping some of the necessary setup for that but not skipping everything that tries to use it

The PR doesn't change that. My PR is still broken, though, but for other reasons :-).

**Comment by squeed** [comment]
This is still failing in the devscripts setup, which I didn't change. This is before any of the changes I made might take effect.

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/14198/rehearse-14198-pull-ci-openshift-baremetal-operator-master-e2e-metal-ipi-ovn-dualstack/1336698536414154752/artifacts/e2e-metal-ipi-ovn-dualstack/baremetalds-devscripts-setup/container-logs/test.log

```
+(./04_setup_ironic.sh:173): main(): sudo podman run -d --net host --privileged --name httpd-ostestpr --pod ironic-pod --env PROVISIONING_INTERFACE=ostestpr -v /opt/dev-scripts/ironic:/shared --entrypoint /bin/runhttpd virthost.ostest.test.metalkube.org:5000/localimages/local-release-image:4.7.0-0.ci.test-2020-12-09-155359-ci-op-vrg9fwnp-ironic
Trying to pull virthost.ostest.test.metalkube.org:5000/localimages/local-release-image:4.7.0-0.ci.test-2020-12-09-155359-ci-op-vrg9fwnp-ironic...
  unauthorized: authentication required
Error: unable to pull virthost.ostest.test.metalkube.org:5000/localimages/local-release-image:4.7.0-0.ci.test-2020-12-09-155359-ci-op-vrg9fwnp-ironic: Error initializing source docker://virthost.ostest.test.metalkube.org:5000/localimages/local-release-image:4.7.0-0.ci.test-2020-12-09-155359-ci-op-vrg9fwnp-ironic: Error reading manifest 4.7.0-0.ci.test-2020-12-09-155359-ci-op-vrg9fwnp-ironic in virthost.ostest.test.metalkube.org:5000/localimages/local-release-image: unauthorized: authentication required
```


@akiselev1 any thoughts?

**Comment by squeed** [comment]
is this job somehow not rehearsable?

**Pull request closed without merging**
