### PR TITLE
Modifying base domain according to aws cluster profile

### PR DESCRIPTION
**Pull request by vishnuchalla**

### CODE REVIEW

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-cloud-bulldozer-e2e-benchmarking-master-e2e-ingress-perf-single-node	
/pj-rehearse pull-ci-cloud-bulldozer-e2e-benchmarking-master-e2e-network-smoke-single-node

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-cloud-bulldozer-e2e-benchmarking-master-e2e-network-smoke-single-node

**Review by krishvoor — APPROVED** [review]
/lgtm

**Pull request merged**
