### PR TITLE
[AMQ Streams] Update AMQ Streams version to 2.5.0 after release

### PR DESCRIPTION
**Pull request by im-konge**
New version of AMQ Streams was released, so this PR updates everything related to 2.5.0.

### CODE REVIEW

**Review by jankalinic — APPROVED** [review]

**Comment by im-konge** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.14-lp-interop-amq-streams-2-5

**Comment by im-konge** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.14-lp-interop-amq-streams-2-5

**Comment by im-konge** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.14-lp-interop-amq-streams-2-5

**Comment by im-konge** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.14-lp-interop-amq-streams-2-5

**Comment by im-konge** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.14-lp-interop-amq-streams-2-5

**Comment by droslean** [comment]
/hold

Temporary holding to unblock the queue

**Pull request merged**
