### PR TITLE
Fix mirroring steps in disconnected-proxy jobs

### PR DESCRIPTION
**Pull request by bmanzari**
Add bastion_ssh_user to shared dir, used by mirroring chain

### CODE REVIEW

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-baremetal-compact-agent-ipv4-static-disconnected-proxy-p1-f7

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-baremetal-compact-agent-ipv4-static-disconnected-proxy-p1-f7

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-baremetal-compact-agent-ipv4-static-disconnected-proxy-p1-f7

**Review by aleskandro — APPROVED** [review]

**Pull request merged**
