### PR TITLE
Interop - EAP scenario onboarding

### PR DESCRIPTION
**Pull request by oharan2**

### CODE REVIEW

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-fuse-eap-tests-interop-main-eap-ocp4.14-lp-interop-eap-interop-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-fuse-eap-tests-interop-main-eap-ocp4.14-lp-interop-eap-interop-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-fuse-eap-tests-interop-main-eap-ocp4.14-lp-interop-eap-interop-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-fuse-eap-tests-interop-main-eap-ocp4.14-lp-interop-eap-interop-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-fuse-eap-tests-interop-main-eap-ocp4.14-lp-interop-eap-interop-74

**Comment by oharan2** [comment]
/pj-rehearse pull-ci-jboss-fuse-eap-tests-interop-main-eap-ocp4.14-lp-interop-images

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-fuse-eap-tests-interop-main-eap-ocp4.14-lp-interop-eap-interop-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-fuse-eap-tests-interop-main-eap-ocp4.14-lp-interop-eap-interop-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-fuse-eap-tests-interop-main-eap-ocp4.14-lp-interop-eap-interop-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-fuse-eap-tests-interop-main-eap-ocp4.14-lp-interop-eap-interop-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-fuse-eap-tests-interop-main-eap-ocp4.14-lp-interop-eap-interop-74

**Comment by oharan2** [comment]
/pj-rehearse pull-ci-jboss-eap-qe-openshift-eap-tests-main-eap-ocp4.15-lp-interop-images

**Comment by oharan2** [comment]
/pj-rehearse pull-ci-jboss-eap-qe-openshift-eap-tests-main-eap-ocp4.15-lp-interop-images

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-main-eap-ocp4.15-lp-interop-eap-interop-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-main-eap-ocp4.15-lp-interop-eap-interop-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-main-eap-ocp4.15-lp-interop-eap-interop-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-main-eap-ocp4.15-lp-interop-eap-interop-aws-74

**Comment by oharan2** [comment]
/pj-rehearse pull-ci-jboss-eap-qe-openshift-eap-tests-main-eap-ocp4.15-lp-interop-images

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-eap-interop-aws-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-eap-interop-aws-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-eap-interop-aws-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-eap-interop-aws-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-eap-interop-aws-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-eap-interop-aws-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-eap-interop-aws-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-eap-interop-aws-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-eap-interop-aws-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-eap-interop-aws-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-eap-interop-aws-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-eap-interop-aws-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-eap-interop-aws-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-eap-interop-aws-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-eap-interop-aws-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-eap-interop-aws-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-eap-interop-aws-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-eap-interop-aws-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-eap-interop-aws-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-eap-interop-aws-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-eap-interop-aws-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-eap-interop-aws-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-eap-interop-aws-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-eap-interop-aws-74

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-eap-74-interop-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-eap-74-interop-aws

**Comment by oharan2** [comment]
/pj-rehearse pull-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-images

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-jboss-eap-qe-openshift-eap-tests-7.4.x-eap-ocp4.15-lp-interop-eap-74-interop-aws

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
