### PR TITLE
MGMT-11712: baremetalds gather: remove extra hostname from resulting artifacts

### PR DESCRIPTION
**Pull request by vrutkovs**
Followup for https://github.com/openshift/release/pull/34664#discussion_r1576615655

### CODE REVIEW

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-agent-compact-ipv4 pull-ci-openshift-installer-master-e2e-agent-ha-dualstack

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-agent-compact-ipv4 pull-ci-openshift-installer-master-e2e-agent-ha-dualstack

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-agent-compact-ipv4 pull-ci-openshift-installer-master-e2e-agent-ha-dualstack

**Comment by andfasano** [comment]
Thanks @vrutkovs 

/lgtm

**Pull request merged**
