### PR TITLE
shiftstack-bugwatcher: Jira pretriage and posttriage

### PR DESCRIPTION
**Pull request by pierreprinetti**
each change in its own commit:
* group bugwatcher secrets in the Vault
* use `exec` in `commands.sh` to avoid unnecessary process forking
* move bugzilla-related bugwatcher steps in a `bugzilla/` directory
* rename the bugzilla-related bugwatcher image from `shiftstack-bugwatcher-image` to `shiftstack-bugwatcher-bugzilla-image` to make room for the new Go base image we will use for Jira
* Add jobs exercising the new Go-based Jira pretriage
* Add jobs exercising the new Go-based Jira posttriage
* Re-add Slack notifications for bugwatcher failures

Implements [OSASINFRA-2912](https://issues.redhat.com//browse/OSASINFRA-2912)
Implements [OSASINFRA-2913](https://issues.redhat.com//browse/OSASINFRA-2913)

### CODE REVIEW

**Comment by pierreprinetti** [comment]
Vendoring is now in place (https://github.com/shiftstack/bugwatcher/pull/35)
/retest

**Review by stephenfin — COMMENTED** [review]
/lgtm

**Pull request merged**
