### PR TITLE
Mirror baremetal-runtimecfg to quay.io

### PR DESCRIPTION
**Pull request by celebdor**
Signed-off-by: Antoni Segura Puimedon <antoni@redhat.com>

### CODE REVIEW

**Comment by smarterclayton** [comment]
What does `runtimecfg` mean?  What is this image doing?

**Comment by celebdor** [comment]
@smarterclayton it is 

> What does `runtimecfg` mean? What is this image doing?

It is rendering runtime configuration from go templates that some network services need on kni, oVirt and OpenStack (keepalived, node CoreDNS and mdns-publisher)

**Comment by smarterclayton** [comment]
And it's not part of your operator?  I.e. why is this in a separate image instead of part of `baremetal-operator`?  Would everyone who is using `baremetal-operator` need this content?

**Comment by celebdor** [comment]
> And it's not part of your operator? I.e. why is this in a separate image instead of part of `baremetal-operator`? Would everyone who is using `baremetal-operator` need this content?

This is logic that was moved outside of MCO templates upon review. It doesn't really belong on the baremetal operator as this is logic for init containers for static pods that run on the master and worker nodes in different platforms, not just baremetal (The baremetal in the name comes from the first platform that started developing it).

**Comment by smarterclayton** [comment]
Ok, so all platforms might use this?  Will it only ever be networking related things in the image?  Will we put everything that is not appropriate for MCO platform but IS part of a standard openshift install?

The name should match what is going into it, which is why I'm asking.  If I can understand what this will contain better I can suggest the correct name.

**Comment by celebdor** [comment]
> Ok, so all platforms might use this?

All the platforms that want to use the mDNS / keepalived solution for node resolution can use this. 

> Will it only ever be networking related things in the image?

I think so. For now it does:
- mdns-publisher,
- coredns mdns configuration
- keepalived

I'm working on adding:
- haproxy LB configuration for the APIs (like there used to be in 3.11. We reuse the openshift router image for HAProxy, but this container may have code that makes sure the API backend list is up to date as a sidecar container.

> Will we put everything that is not appropriate for MCO platform but IS part of a standard openshift install?

Do you have some examples?

> 
> The name should match what is going into it, which is why I'm asking. If I can understand what this will contain better I can suggest the correct name.

I already have it downstream as ose-baremetal-runtimecfg, though I guess that could be changed in time for 4.2

**Comment by markmc** [comment]
xref: openshift/machine-config-operator#795

**Comment by smarterclayton** [comment]
Can you add some of the additional description about what should and shouldn't go into baremetal-runtimecfg into the git repo README at https://github.com/openshift/baremetal-runtimecfg?  The name seems ok if you are "providing configuration that enables clusters without access to cloud infrastructure to establish fundamental interactions" (baremetal, runtime, cfg) (although I would prefer baremetal-runtime-config, the fact that the binary is runtimecfg gets you a pass).

/approve
/lgtm

**Comment by celebdor** [comment]
> Can you add some of the additional description about what should and shouldn't go into baremetal-runtimecfg into the git repo README at https://github.com/openshift/baremetal-runtimecfg? 

Will do. Thanks!

>The name seems ok if you are "providing configuration that enables clusters without access to cloud infrastructure to establish fundamental interactions" (baremetal, runtime, cfg) (although I would prefer baremetal-runtime-config, the fact that the binary is runtimecfg gets you a pass).
> 
> /approve
> /lgtm

**Pull request merged**
