### PR TITLE
4.11: Update mirroring lists

### PR DESCRIPTION
**Pull request by petr-muller**
- 4.11: Configure 4.11 mirroring lists
- `make openshift-image-mirror-mappings`
- 4.11: Bump latest mirroring list to 4.11
- `make openshift-image-mirror-mappings`

/hold

### CODE REVIEW

**Review by hongkailiu — APPROVED** [review]

**Review by hongkailiu — APPROVED** [review]

**Comment by petr-muller** [comment]
@bparees @smarterclayton pls review and merge at your convenience. Lists are fully automatically generated based on `core-services/image-mirroring/openshift/_config.yaml` so there should be no issue with them.

**Comment by bparees** [comment]
this just carries forward what we had for 4.10, so i would expect sign-off to be trivial, but since i'm still new to this i'll let @smarterclayton note any special considerations that need to be taken.

**Comment by bparees** [comment]
people are starting to get blocked on this, so i'm going to :crossed_fingers: 
/approve

**Comment by petr-muller** [comment]
@bparees had to rebase and update (more images in the 4.11 list), PTAL

**Pull request merged**
