### PR TITLE
HyperShift QE: MCE destroy cluster

### PR DESCRIPTION
**Pull request by LiangquanLi930**
https://issues.redhat.com/browse/HOSTEDCP-1030

### CODE REVIEW

**Review by bryan-cox — APPROVED** [review]
/lgtm

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-agent-ovn-mce-conformance

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-agent-ovn-mce-conformance

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-agent-ovn-mce-conformance

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-agent-ovn-mce-conformance

**Pull request closed without merging**
