### PR TITLE
fix e2e cluster-api-provider-libvirt tests for 4.7

### PR DESCRIPTION
**Pull request by Prashanth684**
e2e-libvirt jobs in the 4.7 branch are failing with:

```
gcloud compute --project openshift-gce-devel-ci ssh --zone us-east1-c packer@ci-op-s8btqkkv-4e104 --command 'export KUBECONFIG=/home/packer/clusters/installer/auth/kubeconfig && /home/packer/run-tests.sh'
openshift-tests version: v4.1.0-3593-g98a759f
error: suite "files" does not contain any tests
```

We have seen it in the past when there were no tests in the suite this error is thrown

### CODE REVIEW

**Comment by praveenkumar** [comment]
We do need to change it and move it like step registry where we can run same tests which are run on installer e2e side. May be an improvement.

/lgtm

**Comment by praveenkumar** [comment]
commit logs still say `wip` also please put bit more details why it was failing, as I can see we are just adding more tests in conformance test list which makes me wonder why it was breaking.

**Comment by Prashanth684** [comment]
> commit logs still say `wip` also please put bit more details why it was failing, as I can see we are just adding more tests in conformance test list which makes me wonder why it was breaking.

yes will update the commit description and remove wip. the e2e-libvirt job in https://github.com/openshift/cluster-api-provider-libvirt/pull/219 gave an error:

```
+ gcloud compute --project openshift-gce-devel-ci ssh --zone us-east1-c packer@ci-op-s8btqkkv-4e104 --command 'export KUBECONFIG=/home/packer/clusters/installer/auth/kubeconfig && /home/packer/run-tests.sh'
openshift-tests version: v4.1.0-3593-g98a759f
error: suite "files" does not contain any tests
```

which i have seen before when no tests are present. In the past adding more tests fixed it although there is the one test that is present.

**Comment by Prashanth684** [comment]
@praveenkumar ok to lgtm ?

**Pull request merged**
