### PR TITLE
add 4.11 to pelorus ci

### PR DESCRIPTION
**Pull request by weshayutin**
If this works, we'll remove 4.7 in next commit

### CODE REVIEW

**Comment by weshayutin** [comment]
@mpryc FYI

**Comment by mpryc** [comment]
dunno if it's already available? From the logs:

```
{  failed to generate steps from config: failed to resolve release latest: failed to request 4.11 from https://api.openshift.com/api/upgrades_info/v1/graph?arch=amd64&channel=stable-4.11: server returned empty list of releases (despite status code 200)}
```

**Pull request merged**
