### PR TITLE
updated for Could not resolve host issue

### PR DESCRIPTION
**Pull request by ShudiLi**
This PR is tried to fix resolve host issue when curl the custom canary route, mentioned in https://issues.redhat.com/browse/OCPQE-16324:

https://steps.ci.openshift.org/reference/ingress-azure-custom-ingresscontroller

echo "Check the route reachability via the custom ingresscontroller LB"
curl -kI --resolve ${canary_host}:443:${custom_public_ip} https://${canary_host}
Check the route reachability via the custom ingresscontroller LB
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: https; Unknown error

@lihongan @MayXuQQ, please review the update, thanks.

### CODE REVIEW

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-azure-ipi-ingress-custom-controller-f28-destructive
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-4.14-upgrade-from-stable-4.13-azure-ipi-ingress-custom-controller-fips-f28

**Comment by ShudiLi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-azure-ipi-ingress-custom-controller-fips-f28
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-azure-ipi-ingress-custom-controller-f28
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-azure-ipi-ingress-custom-controller-f28-destructive
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-ec-azure-ipi-ingress-custom-controller-f28-destructive
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-ec-azure-ipi-ingress-custom-controller-fips-f28-destructive

**Comment by ShudiLi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-azure-ipi-ingress-custom-controller-fips-f28
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-azure-ipi-ingress-custom-controller-f28
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-azure-ipi-ingress-custom-controller-f28-destructive
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-ec-azure-ipi-ingress-custom-controller-f28-destructive
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-ec-azure-ipi-ingress-custom-controller-fips-f28-destructive

**Comment by ShudiLi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-azure-ipi-ingress-custom-controller-fips-f28
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-azure-ipi-ingress-custom-controller-f28
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-azure-ipi-ingress-custom-controller-f28-destructive
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-ec-azure-ipi-ingress-custom-controller-f28-destructive
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-ec-azure-ipi-ingress-custom-controller-fips-f28-destructive

**Comment by ShudiLi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-azure-ipi-ingress-custom-controller-fips-f28
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-azure-ipi-ingress-custom-controller-f28
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-azure-ipi-ingress-custom-controller-f28-destructive
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-ec-azure-ipi-ingress-custom-controller-f28-destructive
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-ec-azure-ipi-ingress-custom-controller-fips-f28-destructive

**Comment by ShudiLi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-azure-ipi-ingress-custom-controller-fips-f28
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-azure-ipi-ingress-custom-controller-f28
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-azure-ipi-ingress-custom-controller-f28-destructive
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-ec-azure-ipi-ingress-custom-controller-f28-destructive
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-ec-azure-ipi-ingress-custom-controller-fips-f28-destructive

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-4.14-upgrade-from-stable-4.13-azure-ipi-ingress-custom-controller-fips-f28

**Pull request merged**
