### PR TITLE
Use golang image from Azure Disk CSI driver repo

### PR DESCRIPTION
**Pull request by jsafrane**
All branches from ~4.9~ 4.10 up have `.ci-operator.yaml` in the github.com/openshift/azure-disk-csi-driver repo.

### CODE REVIEW

**Comment by jsafrane** [comment]
`release-4.9/unit` looks like a flake (or at least not caused by golang change)
/retest

**Comment by jsafrane** [comment]
/test pj-rehearse
This seems to run different tests with each run. I want 4.9-unit, please!

**Comment by jsafrane** [comment]
Giving up with 4.9, updating 4.10 and newer.

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Pull request merged**
