### PR TITLE
Add job/pull-ci-openshift-ci-docs-master-links

### PR DESCRIPTION
**Pull request by hongkailiu**
Follow up https://coreos.slack.com/archives/GB7NB0CUC/p1612286892425300

### CODE REVIEW

**Comment by hongkailiu** [comment]
/close

Need to check the internal links as well.

Something like this: https://github.com/openshift/ci-docs/blob/4e2d78372dbf97d08a1da30fcc65adb61a7f9cd8/content/en/docs/architecture/ci-operator.md#L78

**Comment by hongkailiu** [comment]
/hold

require https://github.com/openshift/ci-docs/pull/77

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
