### PR TITLE
Use OCP 4.11 in main and release-1.31

### PR DESCRIPTION
**Pull request by ReToCode**
As per title

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by ReToCode** [comment]
/pj-rehearse pull-ci-openshift-knative-serverless-operator-main-4.11-upstream-e2e-mesh-aws-ocp-411

/pj-rehearse pull-ci-openshift-knative-serverless-operator-main-4.11-e2e-kitchensink-ocp-411

/pj-rehearse periodic-ci-openshift-knative-serverless-operator-main-4.11-e2e-kitchensink-ocp-411-continuous

/pj-rehearse periodic-ci-openshift-knative-serverless-operator-main-4.11-e2e-mesh-ocp-411-continuous

/pj-rehearse pull-ci-openshift-knative-serverless-operator-main-4.11-operator-e2e-aws-ocp-411

/pj-rehearse pull-ci-openshift-knative-serverless-operator-release-1.31-4.11-upgrade-kitchensink-ocp-411

/pj-rehearse pull-ci-openshift-knative-serverless-operator-main-4.11-upstream-e2e-aws-ocp-411

**Comment by ReToCode** [comment]
/pj-rehearse pull-ci-openshift-knative-serverless-operator-main-4.11-operator-e2e-aws-ocp-411

/pj-rehearse pull-ci-openshift-knative-serverless-operator-main-4.11-upstream-e2e-aws-ocp-411

/pj-rehearse pull-ci-openshift-knative-serverless-operator-release-1.31-4.11-operator-e2e-aws-ocp-411

**Comment by ReToCode** [comment]
/pj-rehearse pull-ci-openshift-knative-serverless-operator-release-1.31-4.11-operator-e2e-aws-ocp-411

**Comment by ReToCode** [comment]
/pj-rehearse pull-ci-openshift-knative-serverless-operator-main-4.11-upstream-e2e-aws-ocp-411

**Comment by ReToCode** [comment]
/pj-rehearse pull-ci-openshift-knative-serverless-operator-main-4.11-operator-e2e-aws-ocp-411

**Comment by ReToCode** [comment]
The build failed 6 times now with the `TestKnativeMetrics`, we'll tackle that one in https://issues.redhat.com/browse/SRVKE-1538. Merging this to get rid of the 4.10 version.


/pj-rehearse ack

**Pull request merged**
