### PR TITLE
EXTRA_FLAGS to be documented in cdv2

### PR DESCRIPTION
**Pull request by krishvoor**
This PR allows users to provide `--churn-duration`, `--churn-delay` 
as arguments via `EXTRA_FLAGS`

### CODE REVIEW

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-multiaz-ec-ci-tests-2nodes-periodic

**Comment by krishvoor** [comment]
Per the logs [here](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/42746/rehearse-42746-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-perfscale-rosa-multiaz-ec-ci-tests-2nodes-periodic/1696375508087869440) the failure is not related to PR in itself, however the fails at the Post Cluster Creation.

**Comment by jtaleric** [comment]
Failure not related to PR 
```
* 2023-08-29T06:31:55Z 5x kubelet: Failed to create pod sandbox: rpc error: code = DeadlineExceeded desc = context deadline exceeded
64
* 2023-08-29T06:35:36Z 1x kubelet: MountVolume.SetUp failed for volume "censor-15" : failed to sync secret cache: timed out waiting for the condition 
65
INFO[2023-08-29T06:40:39Z] Step perfscale-rosa-multiaz-ec-ci-tests-2nodes-periodic-gather-extra failed after 30m9s. 
```

**Review by jtaleric — APPROVED** [review]
lgtm

**Review by venkataanil — APPROVED** [review]

**Review by jtaleric — APPROVED** [review]
lgtm

**Pull request merged**
