### PR TITLE
vSphere: move the remaining pre-submits

### PR DESCRIPTION
**Pull request by jcpowermac**

### CODE REVIEW

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.14-e2e-vsphere-ovn

**Comment by jcpowermac** [comment]
image building issues
/pj-rehearse pull-ci-openshift-installer-release-4.14-e2e-vsphere-ovn

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.14-e2e-vsphere-ovn

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-vsphere-ovn

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-vsphere-ovn

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.13-e2e-vsphere-ovn

**Comment by jcpowermac** [comment]
This is the remaining jobs that are currently configured to `cluster profile: vsphere` that need to moved to `cluster_profile: vsphere-2` and vsphere02 build cluster.

/assign sebsoto aravindhp jsafrane jianlinliu gpei vrutkovs danwinship deads2k jhou1 bandrade sinnykumari joelspeed bparees eliorerz

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.11-installer-rehearse-vsphere

**Comment by jianlinliu** [comment]
cc @sgaoshang and @WenXinWei to be noticed this change.

**Review by vrutkovs — APPROVED** [review]
/approve
/lgtm

**Comment by aravindhp** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-vsphere-e2e-operator

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-vsphere-e2e-operator

**Comment by jcpowermac** [comment]
@aravindhp the windows job passed

**Comment by jcpowermac** [comment]
had to rebase because of test failures

/pj-rehearse ack

**Pull request merged**
