### PR TITLE
[CIGolang]debug co health check junit

### PR DESCRIPTION
**Pull request by kuiwang02**
/cc @Xia-Zhao-rh

### CODE REVIEW

**Comment by kuiwang02** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-azure-ipi-compact-f14

**Comment by kuiwang02** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-gcp-upi-xpn-f28

**Comment by kuiwang02** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-aws-ipi-sdn-f14

**Comment by kuiwang02** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-aws-ipi-sdn-f14

**Comment by kuiwang02** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-aws-ipi-sdn-f14

**Comment by kuiwang02** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-aws-ipi-sdn-f14

**Comment by kuiwang02** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-aws-ipi-sdn-f14

**Comment by kuiwang02** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-aws-ipi-sdn-f14

**Comment by kuiwang02** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-4.14-upgrade-from-stable-4.14-azure-ipi-ovn-ipsec-f28

**Comment by aleskandro** [comment]
Refers OCPQE-16722

**Pull request merged**
