### PR TITLE
[LPTOCPCI-237] - CSB interop onboarding over Openshift CI

### PR DESCRIPTION
**Pull request by smongiar**

### CODE REVIEW

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-3.20.x-jboss-fuse-ocp4.14-lp-interop-jboss-fuse-interop-aws

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-3.20.x-jboss-fuse-ocp4.14-lp-interop-jboss-fuse-interop-aws

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-3.20.x-jboss-fuse-ocp4.14-lp-interop-csb-interop-aws

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-3.20.x-jboss-fuse-ocp4.14-lp-interop-jboss-fuse-interop-aws periodic-ci-jboss-fuse-csb-tnb-tests-container-3.20.x-jboss-fuse-ocp4.14-lp-interop-csb-interop-aws

**Comment by smongiar** [comment]
> @Sau1506mya: job(s): periodic-ci-jboss-fuse-csb-tnb-tests-container-3.20.x-jboss-fuse-ocp4.14-lp-interop-jboss-fuse-interop-aws, periodic-ci-jboss-fuse-csb-tnb-tests-container-3.20.x-jboss-fuse-ocp4.14-lp-interop-csb-interop-aws either don't exist or were not found to be affected, and cannot be rehearsed

Yeah, I see. I'm creating now jobs after a renaming, thanks a lot for pointing me

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3.20.x

**Comment by smongiar** [comment]
periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-3-20-x

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-latest

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-latest

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-latest

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-latest

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-latest

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-latest

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-latest

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-latest

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-latest

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-latest

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-latest

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-latest

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-latest

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-latest

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-latest

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-latest

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-latest

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-latest

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-latest

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-latest

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-latest

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-latest

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-latest

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.14-lp-interop-csb-interop-aws-latest

**Pull request merged**
