### PR TITLE
feat(SRVKP-3656): Make downstream test versioned and on demand only

### PR DESCRIPTION
**Pull request by jhutar**

### CODE REVIEW

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-scaling-pipelines-downstream-1-12

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-master-scaling-pipelines-downstream-1-12

**Review by khrm — COMMENTED** [review]
/lgtm

**Pull request merged**
