### PR TITLE
 Adding OVN IC tests

### PR DESCRIPTION
**Pull request by venkataanil**

### CODE REVIEW

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-ovnic-ocp-qe-perfscale-aws-cni-tests-large-scale-ovnic

**Comment by venkataanil** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-ovnic-ocp-qe-perfscale-aws-cni-tests-large-scale-ovnic

**Comment by venkataanil** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-ovnic-ocp-qe-perfscale-aws-ci-tests-large-scale-ovnic

**Comment by venkataanil** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-ovnic-ocp-qe-perfscale-aws-cni-tests-large-scale-ovnic

**Comment by venkataanil** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-ovnic-ocp-qe-perfscale-aws-cnihighppn-tests-large-scale-ovnic

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-ovnic-ocp-qe-perfscale-aws-ci-cdv2-test-large-scale-ovnic

**Pull request merged**
