### PR TITLE
OpenStack: Remove Kuryr jobs

### PR DESCRIPTION
**Pull request by dulek**
Kuryr is deprecated and we're removing it in 4.15. This removes all the jobs that test with `NETWORK_TYPE: Kuryr`.

### CODE REVIEW

**Review by gryf — APPROVED** [review]
/lgtm

**Review by mandre — COMMENTED** [review]
/lgtm
/approve

For final approval,
/assign bparees

**Comment by dulek** [comment]
We also need someone from CNO and installer.

/assign danwinship
/assign sdodson

**Pull request merged**
