### PR TITLE
Add Kuryr jobs to CNO

### PR DESCRIPTION
**Pull request by MaysaMacedo**
Adds optional pre-submit installation jobs with Kuryr to the CNO.

### CODE REVIEW

**Review by pierreprinetti — APPROVED** [review]

**Review by pierreprinetti — APPROVED** [review]
Let's keep an eye on the load over time for `always_run`.

**Comment by dulek** [comment]
So the idea is that we'll need to do `/test e2e-openstack-kuryr` in order to trigger this? I think that's a fair thing to do on patches affecting Kuryr and we should be able to distinguish them easily.

An alternative could be to make it run on changes to bindata/network/kuryr and pkg/platform/openstack, but I'm not sure if it's possible?

**Comment by MaysaMacedo** [comment]
@dulek yes, we would trigger it manually. 
Regarding running on specific paths the[ `run_if_changed` ](https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#triggering-jobs-based-on-changes) field might help, but it might be better to trigger manually for now.

**Comment by dulek** [comment]
Yeah, works for me. /lgtm

**Review by droslean — APPROVED** [review]

**Pull request merged**
