### PR TITLE
knative/serverless: port job to claim

### PR DESCRIPTION
**Pull request by petr-muller**

### CODE REVIEW

**Comment by petr-muller** [comment]
/cc @markusthoemmes @mgencur 
Please check out if this is the job that you wanted to test claims on?

**Comment by markusthoemmes** [comment]
Looks good!

**Comment by petr-muller** [comment]
So this is what you get instead of installation:

```
INFO[2021-06-17T15:17:57Z] Waiting for the claimed cluster to be ready. 
INFO[2021-06-17T15:23:48Z] The claimed cluster is ready after 5m50s.   
```

**Comment by markusthoemmes** [comment]
<3

**Comment by markusthoemmes** [comment]
/test pj-rehearse

rewhacking that. puller account not created properly or so.

**Comment by markusthoemmes** [comment]
It seems like we can't create a new httpasswd user in the cluster :(

**Comment by petr-muller** [comment]
> It seems like we can't create a new httpasswd user in the cluster :(

Any idea about how to debug this? I don't see why this should work differently for the Hive-provisioned clusters?

**Comment by markusthoemmes** [comment]
I do wonder if the KUBECONFIG provided is somehow not compatible with how we generate the "followup" kubeconfigs :thinking:./ @petr-muller is it possible to get access to the build pod to have a quick play with the cluster? That used to be possible for PRs owned by the respective individual and then going via the openshift ci cluster's pods.

**Comment by petr-muller** [comment]
@markusthoemmes this is still possible, there will be a secret (or more) called `$testname-hive-admin-kubeconfig`

**Comment by stevekuznetsov** [comment]
@markusthoemmes if you provide specifics for what you're doing, what specifically is not working, etc we can help look as well.

**Comment by markusthoemmes** [comment]
Yep, will dedicate time to this today. Sadly, I don't quite have the specifica yet because our scripts send the output of the failing command to /dev/null :(. Will change things up to see what's going on.

**Comment by markusthoemmes** [comment]
For posterity: The error here is that `oc login` is failing against the cluster because of `error: x509: certificate signed by unknown authority`. `--insecure-skip-tls-verify=true` doesn't help.

Our use-case is that we're creating a few users with differing capabilities to run our tests with. We use `oc login` to create a KUBECONFIG file for each.

(Poked #forum-testplatform already and @petr-muller is aware. Just leaving the additional comment here for completeness)

**Comment by markusthoemmes** [comment]
https://issues.redhat.com/browse/DPTP-2335 for tracking.

**Comment by markusthoemmes** [comment]
/test pj-rehearse

To doublecheck something.

**Comment by petr-muller** [comment]
@markusthoemmes would you mind if I closed this PR?  Apparently it's a longer effort where you are probably with a PR of your own (so that you can access the jobs).

**Comment by markusthoemmes** [comment]
@petr-muller yep! Thanks!

/close

**Pull request closed without merging**
