### PR TITLE
USHIFT-210: Add sos report to microshift jobs

### PR DESCRIPTION
**Pull request by pacevedom**
Microshift resources collected by sos will appear when the sos plugin(https://github.com/sosreport/sos/pull/3119) is merged.

### CODE REVIEW

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-openshift-conformance-reduced

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-openshift-conformance-reduced

**Comment by pacevedom** [comment]
As it can be seen here: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/36461/rehearse-36461-pull-ci-openshift-microshift-main-e2e-openshift-conformance-reduced/1626201888368103424/artifacts/e2e-openshift-conformance-reduced/openshift-microshift-infra-sos/artifacts/
The sos report is present.

/pj-rehearse ack

**Comment by dhellmann** [comment]
/lgtm
/hold

@pacevedom this looks good. I added a hold because I wasn't sure if you wanted to merge this before we have the sos plugin. Feel free to remove the hold when you are ready to move ahead.

**Comment by pacevedom** [comment]
@dhellmann the sos wont get released until end of the month (at least), and the new plugin is not merged yet. We might as well benefit from this today, as several plugins are useful for our failures.
I will unhold it and when `sos` is updated it will take it automatically.

**Pull request merged**
