### PR TITLE
[4.15] correct release image config

### PR DESCRIPTION
**Pull request by jianlinliu**
Similar to https://github.com/openshift/release/pull/56491, update for 4.15.

### CODE REVIEW

**Comment by jianlinliu** [comment]
cc @yunjiang29 to reivew.

**Comment by jianlinliu** [comment]
cc @liangxia to review.

**Comment by liangxia** [comment]
@jianlinliu Perhaps run a rehearse job to make sure it works ?

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-multi-stable-azure-ipi-disc-fullypriv-arm-mixarch-f28

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-multi-nightly-aws-ipi-sno-etcd-encryption-basecap-none-arm-f7

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-multi-stable-azure-ipi-disc-fullypriv-arm-mixarch-f28

**Pull request merged**
