### PR TITLE
ART-3904: remove promotion step as part of removing jenkins images from install payload

### PR DESCRIPTION
**Pull request by gabemontero**

### CODE REVIEW

**Comment by gabemontero** [comment]
/assign @bparees 

we are at the point of the "remove jenkins from the OCP payload" journey where we are removing the CI promotion, and as such, the image mirroring has to reflect that per the process @jupierce has laid out to us

thanks

**Comment by coreydaley** [comment]
/retest
Looks like an infrastructure issue.

**Comment by gabemontero** [comment]
> /approve
> 
> @gabemontero can you link all the related PRs together? e.g. the cluster-samples-operator PR that removes the imagestream and image-reference

yep @bparees 
1) the imagestream itself was always pulled into openshift/library and part of the samples operator payload ... it was not a "CVO imagestream".  We just had logic in the samples operator that took the image reference env var values and overrode the image refs in the jenkins imagesterams
2) the image refs were removed with https://github.com/openshift/cluster-samples-operator/commit/f6cd1bc414f68ec4bd1dea4c3090195b8b86d07c .. that commit also removes the special case logic in the samples operator to override the imagestreams with the image refs

The overall PR for that commit was https://github.com/openshift/cluster-samples-operator/pull/416

**Pull request merged**
