### PR TITLE
Azure Disk CSI migration is GA in OCP 4.11

### PR DESCRIPTION
**Pull request by bertinatto**
This means we don't need special-purpose jobs for testing CSI mgiration, as it's going to be tested via in-tree tests.

CC @openshift/storage

/hold
for https://github.com/openshift/cluster-kube-apiserver-operator/pull/1310

### CODE REVIEW

**Comment by jsafrane** [comment]
Please remove them also from ci-operator/config/openshift/release/*4.11*

**Comment by bertinatto** [comment]
> Please remove them also from ci-operator/config/openshift/release/_4.11_

Done.

**Pull request merged**
