### PR TITLE
[WIP][DEBUG][Adding PR to test SSO case](https://github.com/openshift/release/pull/39142#top)

### PR DESCRIPTION
**Pull request by kasturinarra**

### CODE REVIEW

**Comment by kasturinarra** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-disconnected-private-p1-f28-destructive

**Comment by kasturinarra** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-disconnected-private-p1-f28

**Comment by kasturinarra** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-disconnected-private-p1-f4

**Comment by kasturinarra** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-disconnected-private-p1-f4

**Comment by kasturinarra** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-disconnected-private-p1-f4

**Comment by kuiwang02** [comment]
@kasturinarra I know it is debug PR, so suggest to add WIP and DEBUG in the title. like `[WIP][DEBUG][Adding PR to test SSO case](https://github.com/openshift/release/pull/39142#top)`

**Comment by kuiwang02** [comment]
@kasturinarra I know it is debug PR, so suggest to add WIP and DEBUG in the title. like `[WIP][DEBUG][Adding PR to test SSO case](https://github.com/openshift/release/pull/39142#top)`

**Comment by kuiwang02** [comment]
@kasturinarra I know it is debug PR, so suggest to add WIP and DEBUG in the title. like `[WIP][DEBUG][Adding PR to test SSO case](https://github.com/openshift/release/pull/39142#top)`

**Comment by kuiwang02** [comment]
@kasturinarra I know it is debug PR, so suggest to add WIP and DEBUG in the title. like `[WIP][DEBUG][Adding PR to test SSO case](https://github.com/openshift/release/pull/39142#top)`

**Comment by kasturinarra** [comment]
> @kasturinarra I know it is debug PR, so suggest to add WIP and DEBUG in the title. like `[WIP][DEBUG][Adding PR to test SSO case](https://github.com/openshift/release/pull/39142#top)`

Thanks, done !!

**Comment by kasturinarra** [comment]
> @kasturinarra I know it is debug PR, so suggest to add WIP and DEBUG in the title. like `[WIP][DEBUG][Adding PR to test SSO case](https://github.com/openshift/release/pull/39142#top)`

Thanks, done !!

**Comment by kasturinarra** [comment]
> @kasturinarra I know it is debug PR, so suggest to add WIP and DEBUG in the title. like `[WIP][DEBUG][Adding PR to test SSO case](https://github.com/openshift/release/pull/39142#top)`

Thanks, done !!

**Comment by kuiwang02** [comment]
per https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/39142/rehearse-39142-periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-disconnected-private-p1-f4/1658060363825942528#1:build-log.txt%3A66, it execute for 1m5s.

after checking https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/39142/rehearse-39142-periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-disconnected-private-p1-f4/1658060363825942528/artifacts/aws-ipi-disconnected-private-p1-f4/openshift-extended-test/build-log.txt, there is no case selected because your case has Serial and the test you selected is not for serial.

because no case selected and raise error with force exit, the step exit in run function, and `sleep 4800` is after run, so it does not take effective.

so, you could change it with following
1,  change test as the following to debug
```yaml
- as: aws-ipi-disconnected-private-p1-f4
  cron: 13 12 2,6,10,15,20,24,28 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      TEST_FILTERS: ~ChkUpgrade&;~NonPreRelease&;~Disruptive&;~ConnectedOnly&;~HyperShiftMGMT&;~MicroShiftOnly&
      TEST_SCENARIOS: "48916"
    test:
    - ref: openshift-extended-test
    workflow: cucushift-installer-rehearse-aws-ipi-disconnected-private
```
2, move `sleep 4800`
A: if you do not want to run case and then debug firstly, move here
```shell
   sleep 4800
   ret_value=0
    set -x
    if [ "W${TEST_PROVIDER}W" == "WnoneW" ]; then
        extended-platform-tests run --max-parallel-tests ${TEST_PARALLEL} \
        -o "${ARTIFACT_DIR}/extended.log" \
        --timeout "${TEST_TIMEOUT}m" --junit-dir="${ARTIFACT_DIR}/junit" -f ./case_selected || ret_value=$?
    else
        extended-platform-tests run --max-parallel-tests ${TEST_PARALLEL} \
        --provider "${TEST_PROVIDER}" -o "${ARTIFACT_DIR}/extended.log" \
        --timeout "${TEST_TIMEOUT}m" --junit-dir="${ARTIFACT_DIR}/junit" -f ./case_selected || ret_value=$?
    fi
```

B: if you want to run case firstly and then debug, move here
```shell
   ret_value=0
    set -x
    if [ "W${TEST_PROVIDER}W" == "WnoneW" ]; then
        extended-platform-tests run --max-parallel-tests ${TEST_PARALLEL} \
        -o "${ARTIFACT_DIR}/extended.log" \
        --timeout "${TEST_TIMEOUT}m" --junit-dir="${ARTIFACT_DIR}/junit" -f ./case_selected || ret_value=$?
    else
        extended-platform-tests run --max-parallel-tests ${TEST_PARALLEL} \
        --provider "${TEST_PROVIDER}" -o "${ARTIFACT_DIR}/extended.log" \
        --timeout "${TEST_TIMEOUT}m" --junit-dir="${ARTIFACT_DIR}/junit" -f ./case_selected || ret_value=$?
    fi
    sleep 4800
```

**Comment by kasturinarra** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-disconnected-private-p1-f4

**Comment by kasturinarra** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-disconnected-private-p1-f4

**Comment by kasturinarra** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-disconnected-private-p1-f4

**Comment by kasturinarra** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-disconnected-private-p1-f4

**Pull request closed without merging**
