### PR TITLE
installer: Make e2e-agent-compact job required

### PR DESCRIPTION
**Pull request by zaneb**
This job is now passing, so make it required for changes to the agent
installer.

Update the file skip patterns to avoid unnecessary job runs.

### CODE REVIEW

**Review by barbacbd — COMMENTED** [review]
/lgtm 

Had to go and find the answers to some of the questions I had. 
Do we definitely want to `skip_if_only_changed` on the openshift install command?

**Comment by barbacbd** [comment]
It does appear that some of the changed tests are failing

**Comment by zaneb** [comment]
> Do we definitely want to `skip_if_only_changed` on the openshift install command?

It's to skip changes on the directory `cmd/openshift-install/agent`.

> It does appear that some of the changed tests are failing

Looks like one hit a timeout. We want to get the time down, but can always bump the timeout again if that's just how long it takes.

**Pull request merged**
