### PR TITLE
Migrate stonesoup jobs to azure increasing cluster memory

### PR DESCRIPTION
**Pull request by flacatus**

### CODE REVIEW

**Comment by psturc** [comment]
It looks like there's no difference in terms of **worker nodes** between [large](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/36323/rehearse-36323-pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e/1625249301716275200/artifacts/redhat-appstudio-e2e/ipi-install-install/artifacts/install-config.yaml) and [xlarge](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/36323/rehearse-36323-pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1625249300768362496/artifacts/appstudio-e2e-tests/ipi-install-install/artifacts/install-config.yaml) SIZE_VARIANT

I think in order to update the worker node flavour you need to set the [`COMPUTE_NODE_TYPE` var](https://steps.ci.openshift.org/reference/ipi-conf-azure#line69)

**Comment by flacatus** [comment]
> It looks like there's no difference in terms of **worker nodes** between [large](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/36323/rehearse-36323-pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e/1625249301716275200/artifacts/redhat-appstudio-e2e/ipi-install-install/artifacts/install-config.yaml) and [xlarge](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/36323/rehearse-36323-pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1625249300768362496/artifacts/appstudio-e2e-tests/ipi-install-install/artifacts/install-config.yaml) SIZE_VARIANT
> 
> I think in order to update the worker node flavour you need to set the [`COMPUTE_NODE_TYPE` var](https://steps.ci.openshift.org/reference/ipi-conf-azure#line69)

I was just checking something, my idea is to use large

**Comment by flacatus** [comment]
/pj-rehearse max

@psturc rewrited the COMPUTE_NODE_TYPE env!

**Pull request merged**
