### PR TITLE
[red-hat-data-services/notebooks] Disable CI checks for anaconda base…

### PR DESCRIPTION
**Pull request by jstourac**
…d images

Let's disable Anaconda based image CI checks temporarily until the opendatahub-io/notebooks#225 is resolved.

### CODE REVIEW

**Comment by jstourac** [comment]
@harshad16 @atheo89, please let me know your thoughts

**Comment by jstourac** [comment]
bump

**Comment by harshad16** [comment]
@jstourac i think, we can wait on this.
as we don't do much dev work, 
let's wait just this week to see, if it still troubling us
we can try to get this in , if needed
thanks for the work. :100: 
/hold

**Comment by harshad16** [comment]
@jstourac we dont need this PR any no longer.
can you please close it. 
As we got the fix with this: https://github.com/opendatahub-io/notebooks/pull/377

**Comment by jstourac** [comment]
Thank you @harshad16, closing :+1:

**Pull request closed without merging**
