### PR TITLE
NO-ISSUE: Update job definitions for older releases

### PR DESCRIPTION
**Pull request by kwilczynski**
Ensure that job definitions are the same for releases from 1.28 to 1.23, which are the currently supported releases, to ensure that tests are consistent and run in the same manner.

Related:

- [OCPBUGS-20375](https://issues.redhat.com/browse/OCPBUGS-20375)
- [GO-2023-2102](https://pkg.go.dev/vuln/GO-2023-2102)

### CODE REVIEW

**Review by sairameshv — COMMENTED** [review]
/lgtm

I would leave to @haircommander or @saschagrunert for the approval.

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
