### PR TITLE
Make ODH CFO check optional

### PR DESCRIPTION
**Pull request by sutaakar**

### CODE REVIEW

**Review by ChristianZaccaria — APPROVED** [review]
/lgtm

**Comment by ChristianZaccaria** [comment]
Is this change because of the bug in the ci-odh-cfo tests?

**Comment by sutaakar** [comment]
Yes, also for some reason I am not able to push https://github.com/opendatahub-io/codeflare-operator/pull/59, so skipping required broken test should help.

**Comment by ChughShilpa** [comment]
lgtm

**Pull request merged**
