### PR TITLE
[WIP] Serving perf tests

### PR DESCRIPTION
**Pull request by skonto**
Test status for now. Using: https://github.com/openshift-knative/serving/pull/453. 
This runs against mid stream branch: `add_perf_tests_test_ci`. Will update it once the latter PR is merged (same for the rest of the PR here).

### CODE REVIEW

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-add_perf_tests_test_ci-413-images
/pj-rehearse pull-ci-openshift-knative-serving-add_perf_tests_test_ci-413-perf-test-e2e-aws-ocp-413

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-add_perf_tests_test_ci-413-perf-test-e2e-aws-ocp-413

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-add_perf_tests_test_ci-413-perf-test-e2e-aws-ocp-413

**Comment by skonto** [comment]
Data were ingested fine and shown on dashboard with the right build id and job name: 
Screenshot from 2023-09-26 21-20-02

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-add_perf_tests_test_ci-413-perf-test-e2e-aws-ocp-413
/pj-rehearse pull-ci-openshift-knative-serving-add_perf_tests_test_ci-413-images

**Comment by skonto** [comment]
Build03 is overloaded.

**Comment by skonto** [comment]
```
"reason": "FailedScheduling",
      "message": "0/54 nodes are available: 14 Insufficient cpu, 2 node(s) had untolerated taint {node-role.kubernetes.io/infra: }, 2 node(s) had untolerated taint {node.kubernetes.io/not-ready: }, 22 node(s) had untolerated taint {node-role.kubernetes.io/ci-tests-worker: ci-tests-worker}, 3 node(s) didn't match Pod's node affinity/selector, 3 node(s) had untolerated taint {node-role.kubernetes.io/master: }, 4 node(s) had untolerated taint {node-role.kubernetes.io/ci-longtests-worker: ci-longtests-worker}, 4 node(s) had untolerated taint {node-role.kubernetes.io/ci-prowjobs-worker: ci-prowjobs-worker}. preemption: 0/54 nodes are available: 14 No preemption victims found for incoming pod, 40 Preemption is not helpful for scheduling..",
      "source": {},
```

**Comment by bear-redhat** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-perf-tests-v1.12-413-perf-test-e2e-aws-ocp-413

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-perf-tests-v1.12-413-perf-test-e2e-aws-ocp-413

**Comment by skonto** [comment]
Image builds passed.
```
 could not run steps: step [release:latest-perf-test-e2e-aws-ocp-413] failed: failed to find a cluster pool providing the cluster: map[architecture:amd64 cloud:aws owner:openshift-ci product:ocp version:4.13] 
[36mINFO[0m[2023-11-01T09:16:36Z] Reporting job state 'failed' with reason 'executing_graph:step_failed:importing_release' 
```

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-perf-tests-v1.12-413-images

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-perf-tests-v1.11-413-images

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-perf-tests-v1.11-413-images

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-perf-tests-v1.11-413-images

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-perf-tests-v1.11-413-images

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-perf-tests-v1.11-413-images

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-perf-tests-v1.11-413-images

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-perf-tests-v1.11-413-images

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-perf-tests-v1.11-413-images

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-perf-tests-v1.12-413-perf-test-e2e-aws-ocp-413

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-perf-tests-v1.11-413-images

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-perf-tests-v1.11-413-images

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-perf-tests-v1.12-413-perf-test-e2e-aws-ocp-413

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-perf-tests-v1.11-413-perf-test-e2e-aws-ocp-413

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-perf-tests-v1.12-413-perf-test-e2e-aws-ocp-413

**Comment by skonto** [comment]
When changing the branches to the official ones I get: 

```time="2023-11-02T13:06:09Z" level=error error="failed to validate configuration openshift-knative/serving/openshift-knative-serving-release-next__413.yaml: found more than one matching config for branch release-next on repo openshift-knative/serving"
time="2023-11-02T13:06:09Z" level=fatal msg="error validating configuration files"
```

We can't have multiple configs for the same combination of variant and branch name (see metadata at the bottom of the yaml files). Two options here:
-  either add the perf tests directly in the corresponding branch yamls
- or use some other combination of ocp variant and branch name than the existing. 
cc @ReToCode

**Comment by skonto** [comment]
/pj-rehearse ci/rehearse/openshift-knative/serving/perf-tests-1.11/413-images

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-perf-tests-1.12-413-perf-test-e2e-aws-ocp-413

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-perf-tests-1.11-413-images

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-perf-tests-1.11-413-perf-test-e2e-aws-ocp-413

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-perf-tests-1.12-413-images

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-release-next-413-images

**Comment by skonto** [comment]
oh release-next does not have the new stuff yet.

**Pull request closed without merging**
