### PR TITLE
assisted-vsphere-teardown: use var files

### PR DESCRIPTION
**Pull request by vrutkovs**
Make sure all vars are set when destroying created machines

### CODE REVIEW

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-periodic
/pj-rehearse ci/rehearse/openshift/assisted-test-infra/master/e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-periodic

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Review by eliorerz — APPROVED** [review]

**Pull request merged**
