### PR TITLE
ocm - Onboard/update `go-*-utils` repos (GRC)

### PR DESCRIPTION
**Pull request by dhaiducek**
Adds SonarCloud configurations for:
- stolostron/go-template-utils
- stolostron/go-log-utils

### CODE REVIEW

**Comment by dhaiducek** [comment]
Something is broken here (could be caused by the GitHub outage). Closing and reopening.

**Comment by dhaiducek** [comment]
Blocked by
- https://github.com/stolostron/go-template-utils/pull/41
- https://github.com/stolostron/go-log-utils/pull/3
- SonarCloud repo onboarding

**Review by mprahl — APPROVED** [review]

**Review by mprahl — APPROVED** [review]

**Comment by dhaiducek** [comment]
I think this PR won't need any more changes. I've added `release-2.4` and `release-2.5` configurations for `go-template-utils`. Waiting on:
- `go-template-utils` branch `release-2.5` to be fast-forwarded by the GRC pipeline
- `release-2.4` configuration - https://github.com/stolostron/go-template-utils/pull/42

**Comment by dhaiducek** [comment]
PR is ready for approval. (Current SonarCloud rehearsal failures are expected.)

**Review by mprahl — APPROVED** [review]

**Pull request merged**
