### PR TITLE
Use SNO for GPU operator jobs

### PR DESCRIPTION
**Pull request by empovit**
* Move away from a standard 3+3 cluster and use SNO as the base cluster instead
* Remove redundant credentials

### CODE REVIEW

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.14-nvidia-gpu-operator-e2e-23-9-x

**Review by wabouhamad — COMMENTED** [review]
/lgtm

**Review by wabouhamad — COMMENTED** [review]
/lgtm

**Pull request merged**
