### PR TITLE
SPLAT-1703: Updated multi vCenter jobs to use new vsphere-elastic lease pool.

### PR DESCRIPTION
**Pull request by vr4manta**
[SPLAT-1703](https://issues.redhat.com/browse/SPLAT-1703)

### Changes
- Updated existing multi vCenter jobs to use vsphere-elastic lease pool
- Created new multi vCenter jobs in default master (vs altinfra)

### Notes
- Due to https://github.com/openshift/installer/pull/8638 not being merged yet, this test will fail due to vCenter count > 1.  Key points are to verify that the install-config.yaml is generated correctly with 3 failure domains using 2 vCenters.

### CODE REVIEW

**Comment by vr4manta** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-vsphere-multi-vcenter-ovn

**Comment by vr4manta** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-vsphere-multi-vcenter-ovn

**Comment by vr4manta** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-vsphere-multi-vcenter-ovn

**Comment by vr4manta** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-vsphere-multi-vcenter-ovn

**Comment by vr4manta** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-vsphere-multi-vcenter-ovn

**Comment by vr4manta** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-vsphere-multi-vcenter-ovn

**Comment by vr4manta** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-vsphere-multi-vcenter-ovn

**Comment by vr4manta** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-vsphere-multi-vcenter-ovn

**Comment by vr4manta** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-vsphere-multi-vcenter-ovn

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-vsphere-multi-vcenter-ovn

**Comment by rvanderp3** [comment]
/lgtm

test failure is expected.

**Comment by vr4manta** [comment]
/assign @r4f4  
Ready for review.  Thanks!

**Review by r4f4 — COMMENTED** [review]
/approve

**Pull request merged**
