### PR TITLE
gcp etcd fips jobs

### PR DESCRIPTION
**Pull request by paigerube14**
https://issues.redhat.com/browse/PERFSCALE-3115

https://issues.redhat.com/browse/OCPQE-20533
https://issues.redhat.com/browse/OCPQE-20532
https://issues.redhat.com/browse/OCPQE-20534

### CODE REVIEW

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-gcp-4.16-nightly-x86-node-density-heavy-etcd-fips-24nodes

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-gcp-4.15-nightly-x86-node-density-heavy-etcd-fips-24nodes

**Review by shahsahil264 — APPROVED** [review]
/lgtm

**Review by shahsahil264 — APPROVED** [review]
/lgtm

**Pull request merged**
