### PR TITLE
stackrox: try fast

### PR DESCRIPTION
**Pull request by gavin-stackrox**
If these prove stable lets switch to avoid https://access.redhat.com/solutions/7007136
I'll update ~3.73, 3.74,~ 4.0 also.
And try another PR with GCP.

/hold
/cc @msugakov @BradLugo 
/pj-rehearse

### CODE REVIEW

**Comment by msugakov** [comment]
Test runs look normal except that I don't know what happened to https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/38351/rehearse-38351-pull-ci-stackrox-stackrox-master-ocp-4-10-qa-e2e-tests/1646892129194086400
Tests were ran but JUnit.xmls are not there.

I would also prefer https://github.com/openshift/release/pull/38352 more.

**Review by msugakov — APPROVED** [review]
/lgtm

**Comment by gavin-stackrox** [comment]
Closing in favor of #38352.

**Pull request closed without merging**
