### PR TITLE
Collect PV and PVC json for aws-e2e tests

### PR DESCRIPTION
**Pull request by chancez**

### CODE REVIEW

**Comment by chancez** [comment]
/hold
I'd like to make sure no one thinks this is a bad idea before this merges. In particular @smarterclayton  or @wking probably can answer that.

/assign @smarterclayton
/assign @wking

**Comment by wking** [comment]
Rounded with @deads2k, who thinks this does not belong in must-gather (e.g. see #3516).  I'm don't see any issue with this, but maybe I'm missing something.  Is there a reason why this might be a bad idea that you were concerned about?

**Comment by smarterclayton** [comment]
Do PVs ever have secrets attached to them that could come from the CI infra accidentally?

**Comment by chancez** [comment]
@smarterclayton not that I'm aware of. I was hoping you might have a more solid answer on that.

**Comment by smarterclayton** [comment]
They look ok.

You should also add these as a separate PR to ci-operator (which is where templates will be moving) for the upgrade job (the first job integrated with the operator)

**Comment by smarterclayton** [comment]
/lgtm

@dobbymoodge I reviewed what is on clusters and this doesn't leak secrets, but be aware we're adding a novel thing

**Pull request merged**
