### PR TITLE
HyperShift: enbale 4.14 kubevirt in hypershift

### PR DESCRIPTION
**Pull request by LiangquanLi930**
enbale 4.14 kubevirt on baremetald in hypershift

### CODE REVIEW

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-baremetalds-conformance

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-baremetalds-conformance

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-baremetalds-conformance

**Comment by jechen0648** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-baremetalds-conformance

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-baremetalds-conformance

**Comment by LiangquanLi930** [comment]
job link: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/42448/rehearse-42448-periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-baremetalds-conformance/1696032004946006016

**Review by davidvossel — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
