### PR TITLE
3scale operator test go 1.19

### PR DESCRIPTION
**Pull request by eguzki**

### CODE REVIEW

**Comment by eguzki** [comment]
This PR supersedes #38339

**Comment by eguzki** [comment]
@miguelsorianod I think we need your approval

**Comment by eguzki** [comment]
@smg247 what is required to have this PR merged?

**Comment by smg247** [comment]
You need to acknowledge the rehearsals. read https://github.com/openshift/release/pull/41527#issuecomment-1645447465

**Comment by eguzki** [comment]
@austincunningham LGTM needed

**Review by austincunningham — APPROVED** [review]

**Pull request merged**
