### PR TITLE
add repos to stalebot

### PR DESCRIPTION
**Pull request by RiRa12621**
SRE-P would like to have all repositories that they are responsible for to be taken care of in terms of stale tickets

### CODE REVIEW

**Comment by RiRa12621** [comment]
/hold
allowing some time for the rest of the team to review

**Comment by 2uasimojo** [comment]
Big +1.

> Why not just turn it on for all repos in openshift?

That makes sense to me, if feasible.

:eyes:

**Comment by eparis** [comment]
I'm fine with doing it for openshift/*

**Comment by RiRa12621** [comment]
If we do that, how would we proceed @stevekuznetsov? Is there anything to be done except extending this PR?

**Comment by RiRa12621** [comment]
@eparis @stevekuznetsov any input on how to proceed would be greatly appreciated

cc @iamkirkbater

**Pull request closed without merging**
