### PR TITLE
Create a git-credentials secret in ci-release for release-controller

### PR DESCRIPTION
**Pull request by smarterclayton**
Changelog generation needs to be able to clone openshift/ose

### CODE REVIEW

**Comment by smarterclayton** [comment]
@bbguimaraes this account *only* needs to clone, is this the correct account to use?  It would be ideal if all this allows is cloning.

**Comment by smarterclayton** [comment]
Used by https://github.com/openshift/release-controller/pull/33

**Comment by smarterclayton** [comment]
@droslean

**Comment by bbguimaraes** [comment]
I think only @stevekuznetsov knows about (and has access to) the bot accounts. That is something we should have documented.

Judging by the deployments where those credentials are used, it doesn't look like a very restricted account. I think this is the first time we have a need to clone a private repository, it would be a good time to create dedicated credentials for that.

We can also merge as is and improve the privilege separation later.

**Comment by stevekuznetsov** [comment]
FYI anyone on DPTP has access to log in as any bot and manage tokens.

**Comment by bbguimaraes** [comment]
TIL. I will create a token with a more restricted scope tomorrow and substitute.

/lgtm

**Comment by stevekuznetsov** [comment]
Make sure we substitute it for _this_ application but don't change the rosie token otherwise

**Comment by bbguimaraes** [comment]
@smarterclayton, @stevekuznetsov: we could create a more restricted token, but it would still be read/write.

Github also has read-only deploy keys. Those work as SSH credentials, so that is something we could use if the release controller can work with that.

**Comment by smarterclayton** [comment]
Yeah, we want read only credentials for cloning in general.  I think it's
ok to have a single "you can clone our private content" token somewhere for
most things (although it would suck if someone saw
openshift/shared-secrets...)

Definitely want a token without write perm.

**Pull request merged**
