### PR TITLE
4.16 expansion hypershift jaeger

### PR DESCRIPTION
**Pull request by shakyav**

### CODE REVIEW

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.16-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.16-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.16-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by deepsm007** [comment]
/override ci/build-farm/build11-dry

We are syncing the cluster

**Comment by shakyav** [comment]
cc: [pavolloffay](https://github.com/pavolloffay)

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.16-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by pavolloffay** [comment]
The PR lacks description of changes and use-case. I was not reviewing or authoring changes to the Jaeger in this repository. I will approve but perhaps @IshwarKanse is more knowledgeable to review these changes.

**Review by pavolloffay — APPROVED** [review]

**Comment by pavolloffay** [comment]
Is it just to test on 4.16 hypershift?

**Review by IshwarKanse — APPROVED** [review]

**Pull request merged**
