### PR TITLE
terraform-rhcs-rosa-classic: Add missing examples

### PR DESCRIPTION
**Pull request by nirarg**
* Add examples jobs: "rosa-classic-public-with-multiple-machinepools-and-idps" & "rosa-classic-private-with-autoscaler-unmanaged-oidc-byo-vpc"
* Add verify-gen job
* Make "rosa-classic-private-with-autoscaler-unmanaged-oidc-byo-vpc" always_run=true
* Make "rosa-classic-public-with-shared-vpc" always_run=false

### CODE REVIEW

**Comment by nirarg** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-classic-main-rosa-classic-public-with-shared-vpc pull-ci-terraform-redhat-terraform-rhcs-rosa-classic-main-verify-format

**Comment by nirarg** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-classic-main-verify-gen

**Comment by nirarg** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-classic-main-verify-gen

**Comment by nirarg** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-classic-main-rosa-classic-private-with-autoscaler-unmanaged-oidc-byo-vpc pull-ci-terraform-redhat-terraform-rhcs-rosa-classic-main-rosa-classic-public-with-multiple-machinepools-and-idps pull-ci-terraform-redhat-terraform-rhcs-rosa-classic-main-verify-gen pull-ci-terraform-redhat-terraform-rhcs-rosa-classic-main-rosa-classic-public-with-shared-vpc pull-ci-terraform-redhat-terraform-rhcs-rosa-classic-main-verify-format

**Comment by nirarg** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-classic-main-verify-gen

**Comment by nirarg** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-classic-main-verify-gen

**Comment by nirarg** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-classic-main-verify-gen

**Review by gdbranco — APPROVED** [review]

**Pull request merged**
