### PR TITLE
add sdn workflow for azure/vsphere/gcp for 4.12

### PR DESCRIPTION
**Pull request by zhaozhanqi**

### CODE REVIEW

**Comment by zhaozhanqi** [comment]
@lihongan @anuragthehatter PTAL? thanks

**Comment by anuragthehatter** [comment]
Looks good.Thanks @zhaozhanqi 

/lgtm

**Comment by zhaozhanqi** [comment]
just rebase ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml due to conflict.

**Comment by lihongan** [comment]
next step: update 4.12 e2e test with the three SDN workflows.
cc @liangxia

**Pull request merged**
