### PR TITLE
hypershift: switch 4.13 periodics to use OCM 2.8

### PR DESCRIPTION
**Pull request by sjenning**

### CODE REVIEW

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-agent-ovn

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-agent-ovn

**Comment by LiangquanLi930** [comment]
BTW, There are still some issues due to ingress, So there may still be some warning, i will fix it asap

**Pull request merged**
