### PR TITLE
Debug and enable OpenTelemetry e2e-pdb and e2e-opampbridge testsuites.

### PR DESCRIPTION
**Pull request by IshwarKanse**
* Debug the failing multi-cluster test, will submit a pr with the fix.
* Test and enable the e2e-pdb and e2e-opampbridge testsuites.

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
Rehearsal job passed. https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/47467/rehearse-47467-pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests/1745453814762180608

**Review by iblancasa — APPROVED** [review]

**Pull request merged**
