### PR TITLE
Add CI config for RHMI operator branch rhoam-release-v1.17

### PR DESCRIPTION
**Pull request by fh-automatron**

### CODE REVIEW

**Review by hongkailiu — APPROVED** [review]

**Comment by laurafitzgerald** [comment]
@KevFan There is one failing test which will need to be addressed. `ci/prow/ordered-prow-config ` going by the logs it can be fixed with `make jobs`

**Comment by KevFan** [comment]
@laurafitzgerald Thanks, have an PR for this if you can have a look - https://github.com/integr8ly/release/pull/2

**Pull request merged**
