### PR TITLE
Migrating unit test to multistage to collect logs in artifacts

### PR DESCRIPTION
**Pull request by prietyc123**
Unit test log results in artifacts.

### CODE REVIEW

**Comment by prietyc123** [comment]
UTs artifacts dir - https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/14076/rehearse-14076-pull-ci-openshift-odo-master-unit/1334843418370641920/artifacts/unit/unit-steps/container-logs/

**Comment by dharmit** [comment]
Is there an issue on this or odo repo that one can check to understand the purpose of this PR? Looking at the yaml, I'm guessing that we're seeking 2 CPUs and 4 GiB of RAM to run odo unit tests. But I could be wrong.

**Comment by mohammedzee1000** [comment]
> Is there an issue on this or odo repo that one can check to understand the purpose of this PR? Looking at the yaml, I'm guessing that we're seeking 2 CPUs and 4 GiB of RAM to run odo unit tests. But I could be wrong.

@dharmit that is just a side effect. What is actually happening is we are moving unit tests from the deprecated template-based format to the new supported multi-stage format.

This will allow us to export logs more easily and also, will pave way to splitting up unit testing on prow indirectly as secrets are only supported in multistage builds

PR looks good to me
/lgtm

**Review by dharmit — COMMENTED** [review]
/approve

**Pull request merged**
