### PR TITLE
feat: added log gathering for ec2 and post steps

### PR DESCRIPTION
**Pull request by eggfoobar**
/assign @copejon

### CODE REVIEW

**Comment by eggfoobar** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-openshift-conformance-reduced-arm

**Comment by eggfoobar** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-openshift-conformance-reduced-arm

**Comment by eggfoobar** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-openshift-conformance-reduced-arm

**Comment by eggfoobar** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-openshift-conformance-reduced-arm

**Comment by eggfoobar** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-openshift-conformance-reduced-arm

**Comment by eggfoobar** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-openshift-conformance-reduced-arm

**Comment by eggfoobar** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-e2e-openshift-conformance-reduced-arm

**Comment by copejon** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-e2e-arm

**Pull request merged**
