### PR TITLE
Bump target version from 4.14 to 4.15 for chain upgrade

### PR DESCRIPTION
**Pull request by liangxia**
As we've reached 4.14 GA, bump up the target version from 4.14 to 4.15 for chain upgrade tests.

### CODE REVIEW

**Comment by jianlinliu** [comment]
most looks good, only 1 concern, because added one more upgrade hop, maybe upgrade would be timeout, cc @shellyyang1989

**Comment by shellyyang1989** [comment]
> most looks good, only 1 concern, because added one more upgrade hop, maybe upgrade would be timeout, cc @shellyyang1989

Yeah, at least 4.1 to 4.15 upgrade will probably exceed 24 hours TTL of Prow. We might need to 
a. request DPTP to extend the TTL, maybe AWS TTL as well
b. drop e2e test in 4.1 to 4.15 upgrade to save some time
c. manually test 4.1 to 4.15 upgrade

**Comment by shellyyang1989** [comment]
cc @JianLi-RH for awareness of the change

**Comment by jianlinliu** [comment]
> We might need to
Or starting from 4.2 instead of 4.1?

**Comment by shellyyang1989** [comment]
> > We might need to
> 
> Or starting from 4.2 instead of 4.1?

We do have 4.2 to latest upgrade. We support upgrade from all the old versions, like 4.1, 4.2, 4.3...

**Comment by jiajliu** [comment]
> c. manually test 4.1 to 4.15 upgrade

Test manually sounds terrible to me. And it sounds not convenient to add upgrade e2e cases in the manual test. I heard of a dedicated account with long TTL for performance test. Maybe we could apply for an account for chain upgrade ci, or share with performance test?

**Comment by shellyyang1989** [comment]
> > c. manually test 4.1 to 4.15 upgrade
> 
> Test manually sounds terrible to me. And it sounds not convenient to add upgrade e2e cases in the manual test. I heard of a dedicated account with long TTL for performance test. Maybe we could apply for an account for chain upgrade ci, or share with performance test?

Right, we have long-run account and we can test it in Jenkins.

**Comment by jianlinliu** [comment]
>  we have long-run account and we can test it in Jenkins.

If that, can we switch over the account to long-run account in prow ci for this specific job?

**Comment by jianlinliu** [comment]
> If that, can we switch over the account to long-run account in prow ci for this specific job?

If the TTL from prow is 24 hours, then I guess we have to run it in jenkins ci.

**Comment by shellyyang1989** [comment]
> > If that, can we switch over the account to long-run account in prow ci for this specific job?
> 
> If the TTL from prow is 24 hours, then I guess we have to run it in jenkins ci.

Yeah, sounds like this is the only solution currently:)

**Comment by liangxia** [comment]
@jiajliu @jianlinliu @shellyyang1989 
According to the job [history](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/job-history/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-4.14-upgrade-from-stable-4.1-aws-ipi-f30) for 4.1->4.14, the last two upgrade took 15h54m45s/16h48m40s, it should allow one or two more bump up.
Agree we need a long plan for the 24 hour timeout issue, but it should not block this PR moving forward.

**Comment by jiajliu** [comment]
> According to the job [history](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/job-history/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-4.14-upgrade-from-stable-4.1-aws-ipi-f30) for 4.1->4.14, the last two upgrade took 15h54m45s/16h48m40s, it should allow one or two more upgrade bump up.

From the 16h48m job [log](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-4.14-upgrade-from-stable-4.1-aws-ipi-f30/1710634008217391104), only `cucushift-chainupgrade-toimage` step finish without `openshift-upgrade-qe-test`. So if we add one more hop in `cucushift-chainupgrade-toimage` (about 80min-120min) and then chain `openshift-upgrade-qe-test` (about 5h+). It seems almost 24 hours.

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-4.15-upgrade-from-stable-4.1-aws-ipi-f30

**Pull request merged**
