### PR TITLE
origin: Pin hypershift presubmit master to 4.15

### PR DESCRIPTION
**Pull request by qinqon**

### CODE REVIEW

**Comment by qinqon** [comment]
/pj-rehearse pull-ci-openshift-origin-master-e2e-aws-ovn-kubevirt

**Review by davidvossel — COMMENTED** [review]
/lgtm

**Comment by qinqon** [comment]
/pj-rehearse pull-ci-openshift-origin-master-e2e-aws-ovn-kubevirt

cluster is created correctly now, but conformance may be flaky.

**Pull request merged**
