### PR TITLE
ci-operator/gcp: set CLOUDSDK_PYTHON to use the latest version of python

### PR DESCRIPTION
**Pull request by sohankunkerkar**
Address https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/cri-o_cri-o/6840/pull-ci-cri-o-cri-o-main-ci-crun-e2e/1650460776265158656

### CODE REVIEW

**Comment by jianlinliu** [comment]
@sohankunkerkar do you mind to fix it together in ci-operator/step-registry/gcp/deprovision/vpc/gcp-deprovision-vpc-commands.sh ?

**Comment by gpei** [comment]
cc @jianli-wei

**Comment by jianli-wei** [comment]
@sohankunkerkar Thanks for your updates! FYI I have another PR https://github.com/openshift/installer/pull/7118 addressing the issue, as there are multiple places calling `gcloud` (e.g. the steps `gcp-provision-bastionhost`, `gcp-deprovision-bastionhost`, etc.)

**Pull request merged**
