### PR TITLE
remove console cases when console is not installed

### PR DESCRIPTION
**Pull request by yapei**

### CODE REVIEW

**Comment by yapei** [comment]
@yanpzhan Could you help review?

**Comment by yanpzhan** [comment]
@yapei the update if ok for exclude console cucushift case, I see openshift-extended-web-tests is in openshift-e2e-test-qe chain, seems we need also exclude console case in cypress.

**Comment by yapei** [comment]
@yanpzhan Good point, for Cypress cases, we need update [openshift-extended-web-tests](https://github.com/openshift/release/blob/master/ci-operator/step-registry/openshift-extended/web-tests/openshift-extended-web-tests-commands.sh)

**Comment by yanpzhan** [comment]
Leave Cypress part to later pr, we could merge this update first.
/lgtm

**Pull request merged**
