### PR TITLE
Switch NTO in 4.13 to RHEL-9 base

### PR DESCRIPTION
**Pull request by jmencak**
See: OCPBUGS-13330

### CODE REVIEW

**Comment by jmencak** [comment]
/hold
https://github.com/openshift/cluster-node-tuning-operator/pull/829 needs to merge first.

**Comment by jmencak** [comment]
/pj-rehearse pull-ci-openshift-cluster-node-tuning-operator-release-4.13-e2e-aws-operator

**Comment by jmencak** [comment]
/pj-rehearse pull-ci-openshift-cluster-node-tuning-operator-release-4.13-e2e-aws-operator

**Comment by jmencak** [comment]
/pj-rehearse periodic-ci-openshift-cluster-node-tuning-operator-release-4.13-e2e-nightly

**Comment by jmencak** [comment]
/hold cancel
@yanirq , are you able to take a look in Martin's absence? Thank you!

**Comment by jmencak** [comment]
Infra issues.  pull-ci-openshift-cluster-node-tuning-operator-release-4.13-e2e-aws-operator already passed in this PR
/pj-rehearse pull-ci-openshift-cluster-node-tuning-operator-release-4.13-e2e-aws-operator

**Comment by ffromani** [comment]
/lgtm
/hold

configuration wise LGTM, I just feel a bit surprised it comes late in the 4.13 cycle.
holding to let other chime in

**Comment by jmencak** [comment]
In the hope of triggering a merge
/joke

**Pull request merged**
