### PR TITLE
WINC-1035: Configuration of the nutanix-e2e test jobs for Windows

### PR DESCRIPTION
**Pull request by yanhua121**
1. Set the windows test job nutanix-e2e-operator as required
2. Add the test job e2e-nutanix-windows to cloud-provider-nutanix repo

### CODE REVIEW

**Comment by yanhua121** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-nutanix-e2e-operator

**Review by aravindhp — APPROVED** [review]
For the WMCO changes

**Comment by mtnbikenc** [comment]
/retitle WINC-1035: Configuration of the nutanix-e2e test jobs for Windows

**Comment by yanhua121** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-nutanix-main-e2e-nutanix-windows

**Pull request merged**
