### PR TITLE
Revert "[openstack-k8s-operators][fips-check] Use custom image"

### PR DESCRIPTION
**Pull request by stuggi**
This reverts commit 8d96aeb59f5a023da582c497db979cdea4fb10f7.

Jira: [OSPRH-10362](https://issues.redhat.com//browse/OSPRH-10362)

### CODE REVIEW

**Comment by stuggi** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-test-operator-main-test-operator-build-deploy

**Comment by stuggi** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-keystone-operator-main-keystone-operator-build-deploy-kuttl

**Comment by stuggi** [comment]
also passed for keystone

```
INFO[2024-10-07T08:37:31Z] Running step keystone-operator-build-deploy-kuttl-openstack-k8s-operators-fips-check. 
INFO[2024-10-07T08:39:05Z] Step keystone-operator-build-deploy-kuttl-openstack-k8s-operators-fips-check succeeded after 1m33s. 

```

**Review by olliewalsh — APPROVED** [review]
/lgtm

**Pull request merged**
