### PR TITLE
Sanity test for renaming job names

### PR DESCRIPTION
**Pull request by svetsa-rh**
Sanity test for renaming of jobs to confirm renaming fits with existing Dashboards results view as well.

### CODE REVIEW

**Review by paigerube14 — APPROVED** [review]
/lgtm

**Review by afcollins — APPROVED** [review]
In summary, the periodic job name goes from:
>  name: periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-nightly-x86-perfscale-rosa-multiaz-node-density-cni-24nodes-periodic

to:
>  name: periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-nightly-x86-node-density-cni-24nodes

LGTM!

**Pull request merged**
