### PR TITLE
Modifying image-mirroring periodic to use new image

### PR DESCRIPTION
**Pull request by deepsm007**
/cc @hongkailiu 

/hold checking all rehearsal...

### CODE REVIEW

**Comment by deepsm007** [comment]
/pj-rehearse periodic-image-mirroring-konveyor, periodic-image-mirroring-ovirt

**Comment by deepsm007** [comment]
/pj-rehearse periodic-image-mirroring-aws-load-balancer-operator, /pj-rehearse periodic-image-mirroring-openshift-kni, /pj-rehearse periodic-image-mirroring-konveyor

**Comment by deepsm007** [comment]
/pj-rehearse periodic-image-mirroring-aws-load-balancer-operator 
/pj-rehearse periodic-image-mirroring-openshift-kni

**Comment by deepsm007** [comment]
Dry run looks good
edge-infrastructure: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/51150/rehearse-51150-periodic-image-mirroring-edge-infrastructure/1781407814321704960
external-dns-operator: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/51150/rehearse-51150-periodic-image-mirroring-external-dns-operator/1781407810949484544
hypershift: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/51150/rehearse-51150-periodic-image-mirroring-hypershift/1781407824371257344
lightspeed-service: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/51150/rehearse-51150-periodic-image-mirroring-lightspeed-service/1781407809326288896
node-observability-operator: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/51150/rehearse-51150-periodic-image-mirroring-node-observability-operator/1781407790011518976
openshift-azure: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/51150/rehearse-51150-periodic-image-mirroring-openshift-azure/1781407790825213952
osa: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/51150/rehearse-51150-periodic-image-mirroring-osa/1781407790070239232
ovirt: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/51150/rehearse-51150-periodic-image-mirroring-ovirt/1781411598758318080
redhat-developer: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/51150/rehearse-51150-periodic-image-mirroring-redhat-developer/1781407790305120256
konveyor: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/51150/rehearse-51150-periodic-image-mirroring-konveyor/1781414427904446464
aws-load-balancer-operator: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_rele[…]e-mirroring-aws-load-balancer-operator/1781415145491140608
openshift-kni: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/51150/rehearse-51150-periodic-image-mirroring-openshift-kni/1781416077993971712

**Comment by hongkailiu** [comment]
/lgtm

/hold

Free to chance if you are going to watch the rolling ...
It is late Friday afternoon. I would suggest to do it next week.

**Comment by deepsm007** [comment]
/hold cancel
Will watch the rolling before calling it a day

**Comment by deepsm007** [comment]
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-image-mirroring-aws-load-balancer-operator/1781427683977072640 
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-image-mirroring-external-dns-operator/1781427681468878848
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-image-mirroring-lightspeed-service/1781427691551985664
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-image-mirroring-osa/1781427689010237440
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-image-mirroring-edge-infrastructure/1781427672220438528
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-image-mirroring-hypershift/1781427674737020928
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-image-mirroring-konveyor/1781427676427325440
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-image-mirroring-node-observability-operator/1781427678931324928
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-image-mirroring-openshift-azure/1781427654654693376
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-image-mirroring-openshift-kni/1781427654881185792
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-image-mirroring-ovirt/1781427654969266176
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-image-mirroring-redhat-developer/1781431177941356544

**Pull request merged**
