### PR TITLE
PLNSRVCE-534: add periodic for analyzing service registry repo via jvm-build-service

### PR DESCRIPTION
**Pull request by gabemontero**
Exercising new test from https://github.com/redhat-appstudio/jvm-build-service/pull/157

### CODE REVIEW

**Comment by gabemontero** [comment]
well, that was anticlimatic:

```
.ci/common-ci-settings-and-functions.sh: line 32: JVM_BUILD_SERVICE_IMAGE: unbound variable
```

**Comment by gabemontero** [comment]
the script fix worked, but the test compile is not working in CI ... thought it worked locally.

Will dive in Thursday

```
 INFO[2022-08-04T03:16:58Z] JVM_BUILD_SERVICE_PR_SHA is not set so aborting
KUBERNETES_CONFIG=/tmp/kubeconfig-4029594308 go test -count 1 -tags periodic -timeout 150m -v ./openshift-with-appstudio-test/...
# github.com/redhat-appstudio/jvm-build-service/openshift-with-appstudio-test/e2e [github.com/redhat-appstudio/jvm-build-service/openshift-with-appstudio-test/e2e.test]
openshift-with-appstudio-test/e2e/periodic_test.go:24:8: undefined: setup
openshift-with-appstudio-test/e2e/periodic_test.go:32:3: undefined: debugAndFailTest
openshift-with-appstudio-test/e2e/periodic_test.go:38:9: undefined: streamFileYamlToTektonObj
openshift-with-appstudio-test/e2e/periodic_test.go:42:3: undefined: debugAndFailTest
openshift-with-appstudio-test/e2e/periodic_test.go:67:16: cannot assign *"github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1".Task to ta.maven in multiple assignment
openshift-with-appstudio-test/e2e/periodic_test.go:69:3: undefined: debugAndFailTest
openshift-with-appstudio-test/e2e/periodic_test.go:74:8: undefined: streamFileYamlToTektonObj
openshift-with-appstudio-test/e2e/periodic_test.go:77:3: undefined: debugAndFailTest
openshift-with-appstudio-test/e2e/periodic_test.go:79:19: cannot assign *"github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1".Pipeline to ta.pipeline in multiple assignment
openshift-with-appstudio-test/e2e/periodic_test.go:81:3: undefined: debugAndFailTest
openshift-with-appstudio-test/e2e/periodic_test.go:81:3: too many errors
```

**Comment by gabemontero** [comment]
Progress, but no victory.

Wins:
- it compiled
- it got the size of worker nodes I wanted
- the setup scripts did not die with unbounded variables

Loss:
- the appstudio bootstrap was bypassed, tekton never was installed, and so the pipeilne SA we confirm is there never showed up.

```
JVM_BUILD_SERVICE_PR_SHA is not set so aborting
KUBERNETES_CONFIG=/tmp/kubeconfig-445471052 go test -count 1 -tags periodic -timeout 150m -v ./openshift-with-appstudio-test/...
=== RUN   TestServiceRegistry
    periodic_test.go:56: time: 2022-08-04 19:12:16.200961288 +0000 UTC m=+0.200403387: dumpNodes2 found 6 nodes in list, but only logging worker nodes
    periodic_test.go:56: time: 2022-08-04 19:12:16.20104662 +0000 UTC m=+0.200488719: Node ip-10-0-166-185.ec2.internal allocatable CPU 7500m allocatable mem 31240144Ki capacity CPU 8 capacitymem 32391120Ki
    periodic_test.go:56: time: 2022-08-04 19:12:16.20106077 +0000 UTC m=+0.200502869: Node ip-10-0-169-142.ec2.internal allocatable CPU 7500m allocatable mem 31240144Ki capacity CPU 8 capacitymem 32391120Ki
    periodic_test.go:56: time: 2022-08-04 19:12:16.20106653 +0000 UTC m=+0.200508639: Node ip-10-0-253-179.ec2.internal allocatable CPU 7500m allocatable mem 31240144Ki capacity CPU 8 capacitymem 32391120Ki
    periodic_test.go:56: time: 2022-08-04 19:12:16.217783155 +0000 UTC m=+0.217225264: get of pipeline SA err: serviceaccounts "pipeline" not found
    periodic_test.go:56: time: 2022-08-04 19:12:17.221907175 +0000 UTC m=+1.221349294: get of pipeline SA err: serviceaccounts "pipeline" not found
    periodic_test.go:56: time: 2022-08-04 19:12:18.223090198 +0000 UTC m=+2.222532297: get of pipeline SA err: serviceaccounts "pipeline" not found
    periodic_test.go:56: time: 2022-08-04 19:12:19.248031186 +0000 UTC m=+3.247473285: get of pipeline SA err: serviceaccounts "pipeline" not found
    periodic_test.go:56: time: 2022-08-04 19:12:20.22215603 +0000 UTC m=+4.221598139: get of pipeline SA err: serviceaccounts "pipeline" not found

```

**Comment by gabemontero** [comment]
still only picking up https://github.com/redhat-appstudio/jvm-build-service/commit/0ab2edcb430146c63c9dd3247f72d8aba254f348

/retest

**Comment by gabemontero** [comment]
/assign @psturc 

hey - I think I could use your help on my new periodic; it has failed consistently a couple of times now wrt authentication when trying to clone infra-deployments during the e2e-tests set up on CI script.

The failure is 
```
Changing AppStudio Gitlab Org to "redhat-appstudio-qe"
Error from server (NotFound): error when creating "STDIN": namespaces "spi-system" not found
SPI configurared, set Authorization callback URL to https://spi-oauth-route-spi-system.apps.ci-op-rd00hlvt-28b91.origin-ci-int-aws.dev.rhcloud.com/
[preview-main-1659914578 e12d920] Preview mode, do not merge into main
 9 files changed, 74 insertions(+), 94 deletions(-)
 rewrite components/has/kustomization.yaml (70%)
 rewrite components/has/manager_resources_patch.yaml (63%)
remote: No anonymous write access.
fatal: Authentication failed for 'https://github.com/redhat-appstudio-qe/infra-deployments.git/'
Switched to branch 'main'
Setting app-of-apps targetRevision to preview-main-1659914578
Setting the application repo to https://github.com/redhat-appstudio-qe/infra-deployments.git, branch preview-main-1659914578 in overlay argo-cd-apps/overlays/development
application.argoproj.io/all-components-staging created
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:165","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 2h0m0s timeout","severity":"error","time":"2022-08-08T01:22:58Z"}
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:255","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process did not exit before 15s grace period","severity":"error","time":"2022-08-08T01:23:13Z"}
{"component":"entrypoint","error":"process timed out","file":"k8s.io/test-infra/prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-08-08T01:23:13Z"}
error: failed to execute wrapped command: exit status 127 
```

I'm wondering if there is some additional setup needed for periodics / cron jobs that allows access to the creds we have in openshift CI for the PRs for our various app studio repos ... hopefully that question even makes sense :-) 

If I am on the right track, can you point me to how access to those creds are set up?

thanks

**Comment by gabemontero** [comment]
ok the tests are finally running at least

I now have to update them to account for the per namespace configmap creation for the artifact cache that merged while I was out

**Comment by gabemontero** [comment]
it was progressing, just slower than what I saw on my local cluster
saw some more context exceeded type of errors, but no FailedScheduled, and the s3 local instance might have been overwhelmed at points

will play around with allowing more time, reducing the target of completes, maybe bigger nodes

**Comment by gabemontero** [comment]
Got much closer to what I last saw with my local testing (though I had to double the power of the node vs. what I ran locally, though that need could have arose for multiple factors):

```
    types.go:25: time: 2022-08-09 05:13:12.326202225 +0000 UTC m=+6123.146474372: number of artifactbuilds: 262
    types.go:25: time: 2022-08-09 05:13:12.387133783 +0000 UTC m=+6123.207405940: number of dependencybuilds: 109
    types.go:25: time: 2022-08-09 05:13:12.387160583 +0000 UTC m=+6123.207432730: dependencybuild complete count: 70, failed count: 33, contaminated count: 6
```

I've also I think have discovered (for myself ;-) ) the amount of completed db's could vary based on upstream repo changes (see https://github.com/redhat-appstudio/jvm-build-service/pull/166 for example)

So I think the better condition is to make sure completed + failed + contaminated == total db's, which is what this periodic run did in fact reach.

So updating the test back in the jvm-build-service repo (also may give it a bit more time) and then will retest here.

@stuartwdouglas check out these service registry in CI ^^

**Comment by gabemontero** [comment]
The test passed, but false positive:  

`    types.go:25: time: 2022-08-09 18:27:20.234796173 +0000 UTC m=+722.182991331: dependencybuild complete count: 0, failed count: 0, contaminated count: 0`

need to account for greater than 0

**Comment by gabemontero** [comment]
Just didn't seem to complete in time, though the numbers were awful close to the last run in https://github.com/openshift/release/pull/31046#issuecomment-1209459455

```
    types.go:25: time: 2022-08-10 00:10:18.159775563 +0000 UTC m=+6722.446766244: number of artifactbuilds: 251
    types.go:25: time: 2022-08-10 00:10:18.32569353 +0000 UTC m=+6722.612684211: number of dependencybuilds: 106
    types.go:25: time: 2022-08-10 00:10:18.325720661 +0000 UTC m=+6722.612711342: dependencybuild complete count: 67, failed count: 14, contaminated count: 4
```

it is time to IMO lgtm this regardless @psturc and then we can just start monitoring and analyzing the actually periodic results up in prow moving forward (the periodic's success / failure does not gate anything at this time), tweaking either test or runtime based on the results.  At this point the rehearsals are not gaining anything more for us.

I'll

/retest

one more time just in case we get lucky, but please tag it regardless when you come in on Wednesday @psturc 

@stuartwdouglas FYI

**Comment by psturc** [comment]
unrelated error (the CI build failed on timeout)
```
rekor                    Synced   Degraded
Waiting 10 seconds for application sync
```
/retest

**Review by psturc — APPROVED** [review]

**Comment by gabemontero** [comment]
job up at https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-redhat-appstudio-jvm-build-service-main-jvm-build-service-periodic

**Pull request merged**
