### PR TITLE
Remove golint job

### PR DESCRIPTION
**Pull request by mrkisaolamb**
golint check now is replaced by golangci-lint
in pre-commit check

### CODE REVIEW

**Comment by gibizer** [comment]
you probably need to run `make update` in the root of the repo to auto generate some changes...

**Comment by mrKisaoLamb** [comment]
> you probably need to run `make update` in the root of the repo to auto generate some changes...

Thanks, done!

**Review by gibizer — APPROVED** [review]
Looks good, we replace golint with revive provided by golangci-lint. So this is a good cleanup.

**Pull request merged**
