### PR TITLE
Make acknowledge-critical-fixes-only active to help get 4.14 stable

### PR DESCRIPTION
**Pull request by DennisPeriquet**
Files generated via:

```
make acknowledge-critical-fixes-only REPOS=/tmp/guarded_repos
```

To undo this use:

```
make revert-acknowledge-critical-fixes-only
```

We also reverted, in a separate commit, https://github.com/openshift/release/pull/42465 which added the `jira/valid-bug` requirement.

More in [slack thread](https://redhat-internal.slack.com/archives/C05FZ333VJN/p1693224219153869)

### CODE REVIEW

**Comment by DennisPeriquet** [comment]
/hold
waiting for email to be sent to give notice before merge

**Comment by DennisPeriquet** [comment]
/hold cancel
https://github.com/openshift/release/pull/42745 has merged

**Comment by cgwalters** [comment]
Was something else supposed to automatically add this label to repos?  Or admins are supposed to do it manually?

**Pull request merged**
