### PR TITLE
Bump hypershift job to golang-1.17

### PR DESCRIPTION
**Pull request by enxebre**
Needed for https://github.com/openshift/hypershift/pull/703

### CODE REVIEW

**Comment by enxebre** [comment]
I added the .ci-operator.yaml for the root image here https://github.com/openshift/hypershift/pull/703/commits/f2511cb72da7e32f32811282eb5a78cadff67ebb#diff-4d5699538541ad6da5f6ae79150b49a432b610f4cba488cec683ac9dd00b18d2

And dropped the base image golang inputs in this PR so after merging this and the counter part PR we can follow up here to use
```
build_root:
  from_repository: true
```
and for upcoming golang bumps we can make all changes atomically in the source repo.

**Review by alvaroaleman — APPROVED** [review]

**Comment by enxebre** [comment]
verify is failing because
```
Makefile:45: *** untracked files detected: M api/v1alpha1/zz_generated.deepcopy.go  M thirdparty/machineconfigoperator/pkg/apis/machineconfiguration.openshift.io/v1/zz_generated_deepcopy.go.  Stop.
```
which is expected as per https://github.com/openshift/hypershift/pull/703/commits/f2511cb72da7e32f32811282eb5a78cadff67ebb#diff-9df20abf1db3bb9568f2503505ac9835d285b3c025c57ed1e7fc3aac27c70130

Debugging now why the e2e are failing.

**Comment by enxebre** [comment]
e2e passed https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/23848/rehearse-23848-pull-ci-openshift-hypershift-main-e2e-aws-pooled/1463074248779108352

I'm testing the counterpart PR locally now so it can go green right after merging this one.

**Pull request merged**
