### PR TITLE
TRT-1786: Keep un-tarred copy of observer intervals

### PR DESCRIPTION
**Pull request by dgoodwin**
Keeping a copy of this directly in GCS will allow the sippy intervals UI
to detect it automatically. APIServer team needs this for an issue
they're working during install time.

### CODE REVIEW

**Comment by dgoodwin** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-serial

**Comment by dgoodwin** [comment]
Success: https://sippy.dptools.openshift.org/sippy-ng/job_runs/1828408424107347968/rehearse-55974-periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-serial/openshift_release/55974/intervals?filterText=&intervalFile=e2e-events-observer.json&overrideDisplayFlag=0&selectedSources=OperatorAvailable&selectedSources=OperatorProgressing&selectedSources=OperatorDegraded&selectedSources=KubeletLog&selectedSources=EtcdLog&selectedSources=EtcdLeadership&selectedSources=Alert&selectedSources=Disruption&selectedSources=E2EFailed&selectedSources=APIServerGracefulShutdown&selectedSources=KubeEvent&selectedSources=NodeState

**Review by sosiouxme — APPROVED** [review]
/lgtm

**Pull request merged**
