### PR TITLE
Update knative-eventing-sources to knative-eventing-contrib

### PR DESCRIPTION
**Pull request by lberk**
upstream knative eventing-sources has updated to eventing-contrib.  This PR updated the references accordingly, including the directory hierarchy, ci-generation, and repo references (which will be updated after this PR is merged)

### CODE REVIEW

**Comment by alanfx** [comment]
One more try after renaming the repo
/retest

**Comment by lberk** [comment]
Realised some structural changes we need to make, closing for now and will create a new PR

**Pull request closed without merging**
