### PR TITLE
[PERFSCALE-2822] Add tags to AWS cluster

### PR DESCRIPTION
**Pull request by krishvoor**
This PR aims at adding tags to cluster for >24 worker nodes:
1) Self-Managed AWS
2) ROSA

### CODE REVIEW

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.13-nightly-x86-control-plane-120nodes

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-control-plane-120nodes

**Comment by jtaleric** [comment]
Appears the required tag is there. 
Self-managed
```
platform:
  aws:
    region: us-west-2
    userTags:
      expirationDate: 2024-02-08T01:43+00:00
      TicketId: 382
```  

Managed - ` Cluster Tags: prowci:ci-rosa-s-4b1a,TicketId:382`

**Review by jtaleric — APPROVED** [review]
lgtm

**Pull request merged**
