### PR TITLE
ci-operator/config: Enable TP features before cluster creation in o/platform-operators

### PR DESCRIPTION
**Pull request by timflannagan**
Update the Makefile target from `make e2e` to `make test-e2e`.

Update the e2e prowjob to enable TP features before running the configuring Makefile target.

Signed-off-by: timflannagan <timflannagan@gmail.com>

### CODE REVIEW

**Comment by timflannagan** [comment]
Added the requisite cluster profile annotations, so hopefully that evens out the e2e runs.

/retest

**Review by exdx — COMMENTED** [review]
/lgtm

**Comment by timflannagan** [comment]
Just trying to get one more rehearsal run.

/hold

**Comment by jianzhangbjz** [comment]
Failed at:
```yaml
level=error msg=Bootstrap failed to complete: timed out waiting for the condition
level=error msg=Failed to wait for bootstrapping to complete. This error usually happens when there is a problem with control plane hosts that prevents the control plane operators from creating the control plane.
```

**Comment by jianzhangbjz** [comment]
Hi @timflannagan one question, I found we used this step https://github.com/openshift/release/blob/master/ci-operator/step-registry/ipi/conf/techpreview/ipi-conf-techpreview-commands.sh that created a file called `manifest_feature_gate.yaml`, but where we call that file to create the `FeatureGate` resource? Thanks!

**Comment by timflannagan** [comment]
Looks like we're waiting on https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/202 to merge before we can consume any of these TP workflows.

**Comment by timflannagan** [comment]
Looks like those tests are online now.

/hold cancel

**Comment by exdx** [comment]
Do we need to manually rebase this off the fix in order to pass CI?

**Pull request merged**
