### PR TITLE
Bump the oldest-supported-z-rollback to 4.11.0

### PR DESCRIPTION
**Pull request by shellyyang1989**

### CODE REVIEW

**Comment by shellyyang1989** [comment]
@wking @jianlinliu @jiajliu @JianLi-RH PTAL, Thank you.

**Comment by jianlinliu** [comment]
Shall we add slace alert together?

**Comment by jiajliu** [comment]
```
  oldest-supported-credentials-request:
    release:
      channel: candidate
      version: 4.11.0-fc.0
```
Need update together?

**Comment by shellyyang1989** [comment]
> Shall we add slace alert together?

Slack alert is for blocking job only. The current status is:
4.13 has been a blocking job and has slack alert.
4.12 is still an informing job but looks good. We will make it blocking if it keeps good after a period of time.
4.11 is still an informing job but looks bad. No passed job within the past 2 months.

**Comment by shellyyang1989** [comment]
> oldest-supported-credentials-request

It's not used in rollback job.

**Review by wking — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
