### PR TITLE
[WIP]Make HYPERSHIFT_KEEP_BROKEN_CLUSTER flag true for dump collection

### PR DESCRIPTION
**Pull request by Neha-dot-Yadav**
This PR is raised to enable keeping of broken cluster. So, that we can collect dump from management cluster and debug issues.

### CODE REVIEW

**Comment by Neha-dot-Yadav** [comment]
/pj-rehearse release-openshift-origin-installer-launch-hypershift-powervs

**Comment by Neha-dot-Yadav** [comment]
/pj-rehearse release-openshift-origin-installer-launch-hypershift-powervs

**Comment by Neha-dot-Yadav** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-powervs-cb

**Review by vrutkovs — APPROVED** [review]
/approve
/lgtm

**Comment by Neha-dot-Yadav** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-powervs-cb

**Comment by Neha-dot-Yadav** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-powervs-cb

**Comment by Neha-dot-Yadav** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-powervs-cb

**Comment by Neha-dot-Yadav** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-powervs-cb

**Comment by Neha-dot-Yadav** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-powervs-cb

**Comment by Neha-dot-Yadav** [comment]
Test PR to debug  PowerVS cluster-bot issues.

**Pull request closed without merging**
