### PR TITLE
Enable multiarch image builds in Distributed Tracing jobs.

### PR DESCRIPTION
**Pull request by IshwarKanse**
The PR uses build clusters for Distributed Tracing jobs which has multiarch image build support.

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-grafana-tempo-operator-main-tempo-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-grafana-tempo-operator-main-tempo-e2e-tests

**Review by frzifus — APPROVED** [review]

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-grafana-tempo-operator-main-tempo-e2e-tests

**Comment by IshwarKanse** [comment]
cc @droslean

**Comment by droslean** [comment]
@IshwarKanse  `pull-ci-openshift-grafana-tempo-operator-main-tempo-e2e-tests` shouldn't be affected by this change though. Let's try to rehearse the images job 

/pj-rehearse pull-ci-openshift-grafana-tempo-operator-main-images

**Comment by droslean** [comment]
/pj-rehearse pull-ci-openshift-grafana-tempo-operator-main-images

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-grafana-tempo-operator-main-images

**Comment by droslean** [comment]
@IshwarKanse It seems that the root images you are using are not multi-arch. It would be best if you changed that too.

**Comment by IshwarKanse** [comment]
@droslean Yes, will look into this, it failed on building images for ARM.

**Comment by IshwarKanse** [comment]
Closing this one out as we will be using multiarch for selected jobs and downstream tests.

**Pull request closed without merging**
