### PR TITLE
[WIP] Update e2e-metal-ipi with new cases

### PR DESCRIPTION
**Pull request by akiselev1**
This is a "demo" PR for DevConf Openshift CI presentation.

### CODE REVIEW

**Comment by andfasano** [comment]
@akiselev1 I was thinking that on such kind of PRs (where just the tests list is enriched) it would be nice to have two or three greens in a row on e2e-metal-ipi

**Comment by stbenjam** [comment]
Do not merge this until IPv6 support is restored. A bunch of newer tests require external containers, e.g. sig-node stuff is failing with:


    ```
          state:
            waiting:
              message: Back-off pulling image "gcr.io/kubernetes-e2e-test-images/agnhost:2.8"
              reason: ImagePullBackOff
    ```

**Comment by akiselev1** [comment]
@stbenjam No worries. This is my "sandbox" PR, not looking to merge.

**Comment by andfasano** [comment]
Hi @akiselev1 can we close this PR?

**Pull request closed without merging**
