### PR TITLE
MULTIARCH-4696 : CI failure with service_name unboud

### PR DESCRIPTION
**Pull request by pkenchap**
CI runs are failing with service name unbound issue - [CI job link ](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-powervs-ovn-multi-ppc64le/1805909022491021312)

Resource Group is multi-arch-cicd-resource-group
Attempt: 1/5
**environment: line 368: SERVICE_NAME: unbound variable**
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"sigs.k8s.io/prow/pkg/entrypoint/run.go:84","func":"sigs.k8s.io/prow/pkg/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2024-06-26T10:25:51Z"}
error: failed to execute wrapped command: exit status 1
}

### CODE REVIEW

**Comment by pkenchap** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-powervs-ovn-multi-ppc64le

**Comment by pkenchap** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-powervs-ovn-multi-ppc64le

**Comment by pkenchap** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-powervs-ovn-multi-ppc64le

**Comment by pkenchap** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-powervs-ovn-multi-ppc64le

**Comment by pkenchap** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-powervs-ovn-multi-ppc64le

**Review by prb112 — APPROVED** [review]
/lgtm

**Comment by prb112** [comment]
/title MULTIARCH-4696: CI failure with service_name unbound

**Pull request merged**
