### PR TITLE
NO-ISSUE: use latest release payload for the integration tests

### PR DESCRIPTION
**Pull request by andfasano**
Required by https://github.com/openshift/installer/pull/8749

### CODE REVIEW

**Comment by andfasano** [comment]
cc @patrickdillon @r4f4

**Comment by andfasano** [comment]
/pj-rehearse ack

Note that currently the integration tests are broken for another reason (lack of origin 4.17 release image)

**Comment by r4f4** [comment]
/pj-rehearse pull-ci-openshift-installer-master-agent-integration-tests

**Review by r4f4 — COMMENTED** [review]
/lgtm

I just wish there was a way to avoid the increased running time because of the dependency on the installer images as a multi-step test:
* [Before](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_installer/8749/pull-ci-openshift-installer-master-agent-integration-tests/1813956464427929600): `Test started today at 5:19 PM failed after 24m14s`
* [After](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/54542/rehearse-54542-pull-ci-openshift-installer-master-agent-integration-tests/1813976804755509248): `Test started today at 6:40 PM failed after 1h7m40s.`

/hold
Feel free to unhold if you're happy with that.

**Comment by andfasano** [comment]
> /lgtm
> 
> I just wish there was a way to avoid the increased running time because of the dependency on the installer images as a multi-step test:
> 
>     * [Before](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_installer/8749/pull-ci-openshift-installer-master-agent-integration-tests/1813956464427929600): `Test started today at 5:19 PM failed after 24m14s`
> 
>     * [After](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/54542/rehearse-54542-pull-ci-openshift-installer-master-agent-integration-tests/1813976804755509248): `Test started today at 6:40 PM failed after 1h7m40s.`
> 
> 
> /hold Feel free to unhold if you're happy with that.

Previously the integration tests referenced an (older) origin release payload, instead of the (up-to-date) ephemereal one assembled for the PR under test by the ci-operator. Even though in most of the cases it worked fine, it wasn't optimal and did not allow to test properly the agent commands, especially when a feature is spawning across differente release payload images (and this happens for the agent commands). So, despite the delayed start time (which I'm not sure it could be avoided in any case), the reference to the ephemeral release will improve in the quality and robustness (and moreover correctness) of the integration tests.

/hold cancel

**Pull request merged**
