### PR TITLE
add e2e-aws tests for all monitoring images

### PR DESCRIPTION
**Pull request by pgier**
CC @brancz

### CODE REVIEW

**Comment by brancz** [comment]
Thanks for taking care of this!

/lgtm

**Comment by brancz** [comment]
cc @enj @ericavonb can one of you have a look for oauth-proxy?

**Comment by pgier** [comment]
Had to rebase because of merge conflict and updates to generated config

**Comment by pgier** [comment]
@mrogers950 Are you ok with adding the aws tests to the oauth-proxy PR check?

**Comment by mrogers950** [comment]
@pgier That's ok with me.

**Pull request merged**
