### PR TITLE
HOSTEDCP-1120: Update HyperShift e2e-aws and agent to Utilize HCP CLI Commands

### PR DESCRIPTION
**Pull request by bryan-cox**
## Why do we need this PR?
Replaces `hypershift` portion of CLI commands with `hcp` where applicable.

## Which issue(s) this PR fixes:
Fixes [HOSTEDCP-1120](https://issues.redhat.com/browse/HOSTEDCP-1120)

### CODE REVIEW

**Comment by bryan-cox** [comment]
Several `hypershift create cluster aws` commands cannot be changed due to flags missing from hcp. Reasons why noted [here](https://issues.redhat.com/browse/HOSTEDCP-1120?focusedId=22771578&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22771578).

**Comment by bryan-cox** [comment]
Previous attempt failed due to https://github.com/openshift/hypershift/pull/2889

/pj-rehearse pull-ci-openshift-hypershift-main-e2e-aws

**Comment by LiangquanLi930** [comment]
/hold
We use `--arch`, so this will affect QE's CI
https://github.com/openshift/release/blob/f5c1d866b0c1453e8d7b5305750fd1f255c648d9/ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml#L789

**Pull request merged**
