### PR TITLE
SREP-1143: Add deadmanssnitch-operator

### PR DESCRIPTION
**Pull request by lisa**
This depends on https://github.com/openshift/deadmanssnitch-operator/pull/9

Signed-off-by: Lisa Seelye <lseelye@redhat.com>

### CODE REVIEW

**Comment by droslean** [comment]
no need for `hold`

/lgtm

**Comment by lisa** [comment]
@droslean Oh, okay. I didn't want it to be merged prematurely if the dependent PR wasn't merged. I'll clear away the label.

**Pull request merged**
