### PR TITLE
[alibabacloud ] add "cucushift-installer-check" in provision chains

### PR DESCRIPTION
**Pull request by jianli-wei**
Add `cucushift-installer-check` into provision chains, as common post-installation checks.

### CODE REVIEW

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.12-installer-rehearse-alibabacloud

**Comment by gpei** [comment]
@jianlinliu btw, we have a 4.14 testblocker for IPI Alibaba, so job `periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-alibaba-ipi-private-fips-f28 ` supposed to be failed at the bootstrap stage.

**Comment by jianlinliu** [comment]
> @jianlinliu btw, we have a 4.14 testblocker for IPI Alibaba, so job `periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-alibaba-ipi-private-fips-f28 ` supposed to be failed at the bootstrap stage.

Got it, thanks for the info.

**Pull request merged**
