### PR TITLE
Update search-e2e-test to use node 20

### PR DESCRIPTION
**Pull request by zlayne**
Update node builder version from 14 -> 20

### CODE REVIEW

**Comment by zlayne** [comment]
/pj-rehearse pull-ci-stolostron-search-e2e-test-main-lint
/pj-rehearse pull-ci-stolostron-search-e2e-test-main-deploy-and-run-e2e

**Comment by zlayne** [comment]
/pj-rehearse pull-ci-stolostron-search-e2e-test-main-deploy-and-run-e2e

**Comment by zlayne** [comment]
/pj-rehearse pull-ci-stolostron-search-e2e-test-main-deploy-and-run-e2e

**Comment by zlayne** [comment]
/pj-rehearse pull-ci-stolostron-search-e2e-test-main-deploy-and-run-e2e

**Comment by zlayne** [comment]
/pj-rehearse pull-ci-stolostron-search-e2e-test-main-deploy-and-run-e2e

**Comment by zlayne** [comment]
/pj-rehearse pull-ci-stolostron-search-e2e-test-main-deploy-and-run-e2e

**Review by dislbenn — COMMENTED** [review]
If this is for `release-2.12` you would need to update the promotion reference to `2.12`. Currently, it is still pointing to `2.11`.

**Comment by zlayne** [comment]
/unhold
@dislbenn I have added the necessary 2.12 release files and the pre/post submit jobs. Can you review again at your convenience?

**Pull request merged**
