### PR TITLE
support specify region and specify provision_shard for rosa hypershift

### PR DESCRIPTION
**Pull request by yasun1**

### CODE REVIEW

**Comment by yasun1** [comment]
@YuLi517  @jianlinliu @LiangquanLi930 Please help review.

**Comment by yasun1** [comment]
@LiangquanLi930 The steps you list do not base on region, the region in the steps is only used for rosa login. The steps we need to update to fit for the region are `aws-provision-vpc-shared` and   `aws-deprovision-stacks`.

**Comment by yasun1** [comment]
@jianlinliu The changes in `aws-provision-vpc-shared` and `aws-deprovision-stacks` require your review. Thanks.

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-rosa-sts-hypershift-guest-p1-f7

**Comment by jianlinliu** [comment]
> @jianlinliu The changes in `aws-provision-vpc-shared` and `aws-deprovision-stacks` require your review. Thanks.

Looks good to me, leave this to @yunjiang29 for double confirm.

**Comment by LiangquanLi930** [comment]
@yasun1 job is failed
```
rosa create cluster -y --mode auto --cluster-name ci-rosa-h-37a4 --role-arn arn:aws:iam::301721915996:role/ci-op-80wtmprj-Installer-Role --controlplane-iam-role arn:aws:iam::301721915996:role/ci-op-80wtmprj-ControlPlane-Role --support-role-arn arn:aws:iam::301721915996:role/ci-op-80wtmprj-Support-Role --worker-iam-role arn:aws:iam::301721915996:role/ci-op-80wtmprj-Worker-Role --region us-west-2 --version 4.13.0-0.nightly-2023-04-12-050538 --channel-group nightly --compute-machine-type m5.2xlarge  --replicas 3   --hosted-cp --classic-oidc-config --subnet-ids subnet-021526a4392c063b4,subnet-07601801f44f2de71      
ERR: Failed while validating account roles: Account role 'arn:aws:iam::301721915996:role/ci-op-80wtmprj-Installer-Role' is not compatible with version openshift-v4.13.0-0.nightly-2023-04-12-050538-nightly. Run 'rosa create account-roles' to create compatible roles and try again.
```

**Comment by yunjiang29** [comment]
> > @jianlinliu The changes in `aws-provision-vpc-shared` and `aws-deprovision-stacks` require your review. Thanks.
> 
> Looks good to me, leave this to @yunjiang29 for double confirm.

@yasun1, lgtm, let me know when you need a label

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-rosa-sts-hypershift-guest-p1-f7

**Comment by yasun1** [comment]
@yunjiang29  Thanks very much. You can add the label now.

**Pull request merged**
