### PR TITLE
SPLAT-1227: AWS Wavelength tests for installer automated

### PR DESCRIPTION
**Pull request by mtulio**
This PR introduces the following periodic (weekly), and presubmit jobs to test the PR[1] that implement the full support of Wavelength Zones on the installer:

-  `e2e-aws-ovn-wavelengthzones`: full install automation when the zone is added in the edge compute pool of install-config.yaml

[1] Installer PRs

- Full IPI: https://github.com/openshift/installer/pull/7369

This change was created originally in https://github.com/openshift/release/pull/45158 but is isolated from BYO VPC to not block the partial deliverable of the feature.

Enhancement: https://github.com/openshift/enhancements/pull/1510

### CODE REVIEW

**Comment by mtulio** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-aws-ovn-wavelengthzones

**Comment by mtulio** [comment]
The following error in the new job [1724936414694477824](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/45727/rehearse-45727-pull-ci-openshift-installer-master-e2e-aws-ovn-wavelengthzones/1724936414694477824) is expected, this job is ready to be tested in the target PR https://github.com/openshift/installer/pull/7369 :
~~~
level=error msg=failed to fetch Master Machines: failed to load asset "Install Config": failed to create install config: compute[1].platform.aws.zones: Invalid value: "us-east-1-wl1-msp-wlz-1": only zone type local-zone is valid in the edge machine pool: wavelength-zone
~~~

/pj-rehearse

**Comment by mtulio** [comment]
PR ready for review, it isolates the full automated change from BYO VPC (WIP in #45158 PR). Could you please take a look?

/assign @patrickdillon @r4f4 @rvanderp3  
/pj-rehearse ack

**Review by r4f4 — COMMENTED** [review]
/approve

**Comment by mtulio** [comment]
Hi Vadim, would you mind taking a look? (your mentioned in mostly pending owners file =] ).
This is a subset of #45158 without the BYO BPC (blocker pieces).
/assign @vrutkovs

**Review by vrutkovs — APPROVED** [review]
/approve
/lgtm

**Comment by mtulio** [comment]
cc/fwiw @yunjiang29

**Pull request merged**
