### PR TITLE
CNF-10704: add security scanning job to 4.12-4.14 for ptp

### PR DESCRIPTION
**Pull request by jzding**
Add Snyk scan to 4.12-4.14 ptp pre-submission jobs.
Add flag to snyk to report only high severity issues.

### CODE REVIEW

**Comment by jzding** [comment]
/pj-rehearse pull-ci-redhat-cne-cloud-event-proxy-release-4.12-security

**Comment by jzding** [comment]
/pj-rehearse pull-ci-openshift-ptp-operator-release-4.14-security

**Comment by jzding** [comment]
/pj-rehearse pull-ci-redhat-cne-cloud-event-proxy-release-4.14-security

**Comment by jzding** [comment]
/pj-rehearse pull-ci-openshift-ptp-operator-release-4.14-security

**Comment by jzding** [comment]
/pj-rehearse pull-ci-openshift-linuxptp-daemon-release-4.14-security

**Comment by jzding** [comment]
/pj-rehearse pull-ci-openshift-linuxptp-daemon-release-4.14-security

**Comment by jzding** [comment]
/pj-rehearse pull-ci-openshift-linuxptp-daemon-release-4.14-security

**Comment by jzding** [comment]
/pj-rehearse pull-ci-redhat-cne-cloud-event-proxy-release-4.14-security

**Comment by nishant-parekh** [comment]
/pj-rehearse pull-ci-redhat-cne-cloud-event-proxy-release-4.14-security

**Review by nishant-parekh — APPROVED** [review]

**Pull request merged**
