### PR TITLE
add vsphere ovn ipsec

### PR DESCRIPTION
**Pull request by zhaozhanqi**

### CODE REVIEW

**Comment by jinyunma** [comment]
It's better to update workflow as yours in https://github.com/openshift/release/blob/master/ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse.yaml#L73 to trigger rehearse job and verify your workflow

**Comment by zhaozhanqi** [comment]
> It's better to update workflow as yours in https://github.com/openshift/release/blob/master/ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse.yaml#L73 to trigger rehearse job and verify your workflow

Thanks, done

**Comment by jianlinliu** [comment]
@zhaozhanqi can you squash the commits?

**Pull request merged**
