### PR TITLE
Bumping kmm CI jobs to use 4.17

### PR DESCRIPTION
**Pull request by TomerNewman**
Due to the OpenShift 4.17 release, we need KMM CI jobs to use version 4.17 going forward.
This commit updates the branch to use 4.17 from now on with the new images.

/cc @ybettan @yevgeny-shnaidman

### CODE REVIEW

**Comment by ybettan** [comment]
/ok-to-test
/pj-rehease auto-ack

@TomerNewman the `/pj-rehease auto-ack` will run all KMM jobs (not the jobs on this repo) with the changes you made to the infrastructure of the KMM testing framwork - this allows us to make sure that the changes we make actually work with KMM before merging them.

For more info, check https://github.com/openshift/release/pull/57595#issuecomment-2401396628

**Comment by ybettan** [comment]
/hold

The rehearsal isn't being triggered - let's first make sure the pool was created correctly - https://redhat-internal.slack.com/archives/CBN38N3MW/p1728460597415739

**Comment by ybettan** [comment]
/unhold

Pools were created correctly:
```
oc --context hosted-mgmt get cp -n rh-ecosystem-edge-cluster-pool
NAME                                  SIZE   STANDBY   READY   BASEDOMAIN                                     IMAGESET
rh-ecosystem-edge-4-13-cluster-pool   1      1         0       ecoeng-edgeinfra-ci.devcluster.openshift.com   ocp-release-4.13.44-x86-64-for-4.13.0-0-to-4.14.0-0
rh-ecosystem-edge-4-14-cluster-pool   1      1         0       ecoeng-edgeinfra-ci.devcluster.openshift.com   ocp-release-4.14.31-x86-64-for-4.14.0-0-to-4.15.0-0
rh-ecosystem-edge-4-15-cluster-pool   2      2         0       ecoeng-edgeinfra-ci.devcluster.openshift.com   ocp-release-4.15.19-x86-64-for-4.15.0-0-to-4.16.0-0
rh-ecosystem-edge-4-17-cluster-pool   6      6         0       ecoeng-edgeinfra-ci.devcluster.openshift.com   ocp-release-4.17.0-x86-64-for-4.17.0-0-to-4.18.0-0
```

**Comment by TomerNewman** [comment]
closed PR due to messy rebase, new one  in #58262

**Pull request closed without merging**
