### PR TITLE
openstack secrets: use new keys by Martin Andre

### PR DESCRIPTION
**Pull request by petr-muller**
These keys are already prepared in BW.

/cc @mandre @stevekuznetsov

### CODE REVIEW

**Comment by petr-muller** [comment]
/hold

We're still not 100% sure we really want to do this, there's an email convo going on...

**Comment by mandre** [comment]
Is there a way to run against e2e-openstack, just to make extra sure it's not going to mess up with our ci job?
If not I guess it's ok, we can always revert the patch if we realize it broke our CI...

Thanks for taking care of this Petr!

**Comment by stevekuznetsov** [comment]
@mandre no, there is no way to check this out. Let me know if you have time to monitor new jobs and we can test it out next week, reverting if it breaks anything.

**Comment by mandre** [comment]
> @mandre no, there is no way to check this out. Let me know if you have time to monitor new jobs and we can test it out next week, reverting if it breaks anything.

Sounds good to me.

**Comment by stevekuznetsov** [comment]
Guess we didn't need this ...

/close

**Pull request closed without merging**
