### PR TITLE
RHCOS: Setup 4.11 COSA and other related fixes

### PR DESCRIPTION
**Pull request by travier**

### CODE REVIEW

**Comment by travier** [comment]
CC @miabbott @cheesesashimi

**Comment by travier** [comment]
CC @cgwalters

**Comment by travier** [comment]
Split into https://github.com/openshift/release/pull/29266

**Comment by cgwalters** [comment]
/approve
I think this looks sane, though we probably need to figure out for the next cycle why the branching job stuff seems to have branched early for us.

**Comment by travier** [comment]
Closing this one for now. We will backport some CI changes from master once they are ready there.

**Pull request closed without merging**
