### PR TITLE
Add openshift/assisted-test-infra with system-test-olm job

### PR DESCRIPTION
**Pull request by YuviGold**
Dependant on https://github.com/openshift/assisted-test-infra/pull/628 to be merged

### CODE REVIEW

**Comment by YuviGold** [comment]
Resources should be created dynamically now according to the OLM operators picked after https://github.com/openshift/assisted-test-infra/pull/707is merged by @pkliczewski 

/retest

**Comment by YuviGold** [comment]
For now it would run only CNV

**Review by osherdp — APPROVED** [review]

**Pull request merged**
