### PR TITLE
Hypershift: Use 4.12 for main periodics again

### PR DESCRIPTION
**Pull request by alvaroaleman**

### CODE REVIEW

**Comment by stbenjam** [comment]
@alvaroaleman Would it be possible to include the OpenShift release in your job name? Having jobs move between OpenShift releases doesn't work so great for some of our tooling.

**Comment by alvaroaleman** [comment]
> @alvaroaleman Would it be possible to include the OpenShift release in your job name? Having jobs move between OpenShift releases doesn't work so great for some of our tooling.

Sorry about that, that we ended up shifting conformance around was actually never intended. I'll see that I rename it.

**Pull request merged**
