### PR TITLE
Reorder check_mcp and wait_clusteroperators_continous_success for health_check

### PR DESCRIPTION
**Pull request by JianLi-RH**

### CODE REVIEW

**Comment by JianLi-RH** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-4.14-upgrade-from-eus-4.12-nutanix-ipi-proxy-fips-f14

**Comment by jianlinliu** [comment]
Suggest to update the following together:
ci-operator/step-registry/cucushift/upgrade/paused/intermediate/to-latest/cucushift-upgrade-paused-intermediate-to-latest-commands.sh
ci-operator/step-registry/cucushift/upgrade/paused/latest/cucushift-upgrade-paused-latest-commands.sh

**Pull request merged**
