### PR TITLE
Make the gce job blocking

### PR DESCRIPTION
**Pull request by 0xmichalis**
@stevekuznetsov @smarterclayton

### CODE REVIEW

**Comment by kargakis** [comment]
@paradigm @stevekuznetsov the config updater plugin did nothing, I had to update the cm manually.

**Comment by stevekuznetsov** [comment]
We didn't seem to determine any update was necessary

```
{"author":"kargakis","client":"jenkins-config-updater","eventGUID":"16c265d0-d415-11e7-9439-ae1ce31eb329","eventType":"pull_request","level":"info","msg":"Received webhook","org":"openshift","pr":449,"repo":"release","time":"2017-11-28T08:21:10Z","url":"https://github.com/openshift/release/pull/449"}
{"author":"kargakis","client":"jenkins-config-updater","level":"info","msg":"cloning openshift/release","org":"openshift","pr":449,"repo":"release","time":"2017-11-28T08:21:10Z","url":"https://github.com/openshift/release/pull/449"}
{"client":"git","level":"info","msg":"Fetching openshift/release.","time":"2017-11-28T08:21:10Z"}
{"author":"kargakis","client":"jenkins-config-updater","level":"info","msg":"checking out 81881c993643a646a6fcd02648215b37adab12fa","org":"openshift","pr":449,"repo":"release","time":"2017-11-28T08:21:12Z","url":"https://github.com/openshift/release/pull/449"}
{"client":"git","level":"info","msg":"Checkout 81881c993643a646a6fcd02648215b37adab12fa.","time":"2017-11-28T08:21:12Z"}
{"author":"kargakis","client":"jenkins-config-updater","duration":2104521169,"level":"info","msg":"Cloned and checked out target branch.","org":"openshift","pr":449,"repo":"release","time":"2017-11-28T08:21:12Z","url":"https://github.com/openshift/release/pull/449"}
```

**Comment by stevekuznetsov** [comment]
The entry is definitely in the configmap ... no idea :|

**Comment by stevekuznetsov** [comment]
Or, you know what probably happened -- we don't have hot reload for config so if JCU didn't restart to re-read the config when we merged the refactor to these files... it won't have picked that up

**Comment by stevekuznetsov** [comment]
Yeah....

```
$ oc get pods/jenkins-config-updater-6-hvwnf -n ci -o jsonpath='{.status.containerStatuses[0].state.running.startedAt}'
2017-11-20T23:03:02Z
```

**Pull request merged**
