### PR TITLE
update observatorium and operator go version

### PR DESCRIPTION
**Pull request by haoqing0110**
Fix https://github.com/open-cluster-management/backlog/issues/11308#issuecomment-877345890

### CODE REVIEW

**Comment by clyang82** [comment]
Can we use version 1.16?

**Comment by clyang82** [comment]
You need to remove this - https://github.com/openshift/release/blob/4c14a34c2742835d3021452a6d1762420d4afa92/ci-operator/config/open-cluster-management/observatorium/open-cluster-management-observatorium-release-2.3.yaml#L10 to enable `release-2.3` image can be promoted successfully.

it applies to observatorium-operator as well.

**Comment by clyang82** [comment]
@haoqing0110 there is `xz` command in `openshift/release:golang-1.14`.  but there is not in `open-cluster-management/builder:go1.16-linux`.
@ray-harris Can we have `xz` in `open-cluster-management/builder:go1.16-linux`?  if not, we need to update that command. Thanks.

**Comment by ray-harris** [comment]
@clyang82 I'll get it added and let you know when it's ready.

**Comment by ray-harris** [comment]
@clyang82 The builder images now have the `xz` command in them.

**Comment by ray-harris** [comment]
/test pj-rehearse

The two lint tests are still failing because they can't find `xz`. I just checked and it is in the new images.

**Comment by haoqing0110** [comment]
@ray-harris thanks for help!
@clyang82 removed `disabled: true` in 2.3, plz help review again.

**Comment by clyang82** [comment]
@ray-harris Thanks for your quick response and fix.

/lgtm

**Pull request merged**
