### PR TITLE
release-controller/repos: Updates for RHEL 8.4 GA

### PR DESCRIPTION
**Pull request by travier**
release-controller/repos: Use Beta repos for advanced-virt in 4.8+

This is 488c9bac3d repos: Point advanced-virt repos to the "beta" CDN

---

release-controller/repos: Remove 8.4 Beta repos

---

Revert "release-controller: Add generated deployments for RHEL 8.4 repos"

This reverts commit 89dc983549092c97a5ac8ca0b90216f12726d1a0.

### CODE REVIEW

**Comment by cgwalters** [comment]
Why not keep the 8-4 pinned repos?  Won't we potentially need them later for at least testing?

**Comment by travier** [comment]
8 & 8.4 should have the same content going forward until 8.5, and at this point we will want to move all active OCP branches to "forced" 8.4 to not move to 8.5.

**Comment by travier** [comment]
I'm not opposed to keeping them but I don't think there will be a case where we need them.

**Comment by travier** [comment]
Given https://github.com/openshift/release/pull/18664#issuecomment-844288928, I'll update this one to keep the pinned repos.

**Comment by miabbott** [comment]
And someone from DPTP...wonder if this will work

/assign dptp

**Pull request merged**
