### PR TITLE
OpenStack: Remove Kuryr jobs vol. 2

### PR DESCRIPTION
**Pull request by dulek**
PR #44015 needed to be reverted as it broke other jobs. We need to remove Kuryr from CNO before it's removed from the payload. But in order to remove it from CNO should remove the other Kuryr jobs. This commit does so.

### CODE REVIEW

**Comment by dulek** [comment]
/cc @sdodson 
/cc @bparees

Can you take a look here folks? This is a replacement for the reverted #44015 and this time it doesn't remove the image yet, just the jobs in the other repositories.

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
