### PR TITLE
Test and fix new ARO workflow 

### PR DESCRIPTION
**Pull request by slintes**
🤞🏼

### CODE REVIEW

**Comment by slintes** [comment]
/hold

do not merge before we have a successful rehearsal :)

**Comment by slintes** [comment]
/remove-lifecycle stale
/lifecycle frozen

still WIP, and it contains fixes we need for sure

**Comment by slintes** [comment]
@tsatam @lranjbar would it make sense to merge this and continue testing when the network topic is resolved?

**Review by hlipsig — APPROVED** [review]
LGTM

**Pull request merged**
