### PR TITLE
multi-arch odh-dashboard

### PR DESCRIPTION
**Pull request by puneetsharma21**
introduces multi-architecture support for the ODH Dashboard image

**Purpose**:
The primary goal of this PR is to enhance the flexibility of our image builds by supporting multiple architectures. This will ensure that the ODH Dashboard image can be used across different environments and platforms.

### CODE REVIEW

**Comment by dpanshug** [comment]
@npanpaliya asking the team about this, will get back to you in sometime

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-images

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-images

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-images

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-images

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-images

**Pull request closed without merging**
