### PR TITLE
konflux build-service: move to konflux-ci

### PR DESCRIPTION
**Pull request by chmeliik**
[STONEBLD-2336](https://issues.redhat.com//browse/STONEBLD-2336)

### CODE REVIEW

**Comment by chmeliik** [comment]
I didn't change theser references to "redhat-appstudio" https://github.com/openshift/release/blob/0e91f5041a3beaf1c6c8eee412cc97462484322a/ci-operator/config/redhat-appstudio/build-service/redhat-appstudio-build-service-main.yaml#L41-L44

The other services migrated to konflux-ci also left these as "redhat-appstudio" and I'm not familiar enough with these configs to know what would break otherwise.

**Comment by chmeliik** [comment]
/pj-rehearse pull-ci-konflux-ci-build-service-main-build-service-e2e

**Comment by chmeliik** [comment]
/pj-rehearse ack

it passed before and the tests are known to be flaky

**Review by mkosiarc — APPROVED** [review]

**Review by rcerven — APPROVED** [review]

**Pull request merged**
