### PR TITLE
Updates to run Odo Interop job on openshift 4.14

### PR DESCRIPTION
**Pull request by smatula**

### CODE REVIEW

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-redhat-developer-odo-main-odo-ocp4.14-lp-interop-odo-scenario-aws

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-redhat-developer-odo-main-odo-ocp4.14-lp-interop-odo-scenario-aws

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-redhat-developer-odo-main-odo-ocp4.14-lp-interop-odo-scenario-aws

**Comment by smatula** [comment]
/pj-rehearse periodic-ci-redhat-developer-odo-main-odo-ocp4.14-lp-interop-odo-scenario-aws

**Comment by rm3l** [comment]
/pj-rehearse periodic-ci-redhat-developer-odo-main-odo-ocp4.14-lp-interop-odo-scenario-aws

**Review by rm3l — APPROVED** [review]

**Pull request merged**
