### PR TITLE
Replace vsphere platform to vsphere-dis for disconnected jobs

### PR DESCRIPTION
**Pull request by mhanss**

### CODE REVIEW

**Comment by mhanss** [comment]
@liangxia and @hoxhaeris please review.

**Review by hoxhaeris — APPROVED** [review]

**Comment by hoxhaeris** [comment]
I can't see a respective job defined here: 
https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
for this workflow. I believe this won't work as intended.

**Comment by liangxia** [comment]
@hoxhaeris Those workflow comes from QE, and are defined in https://github.com/openshift/release/tree/master/ci-operator/step-registry/cucushift/agent/vsphere/disconnected/install

**Comment by hoxhaeris** [comment]
> @hoxhaeris Those workflow comes from QE, and are defined in https://github.com/openshift/release/tree/master/ci-operator/step-registry/cucushift/agent/vsphere/disconnected/install

Cluster-Bot will reference the jobs that are defined [here](https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml). 
The one you are referring to, the step-registry configuration, is part of what's necessary, but not all.

**Pull request merged**
