### PR TITLE
Bug 1897676: Azure UPI ignition version based on file

### PR DESCRIPTION
**Pull request by e-tienne**
Match Azure UPI bootstrap ignition version and remove newlines for compatibility

### CODE REVIEW

**Comment by e-tienne** [comment]
This needs an adjustment that I need to further test.
/hold
/wip

**Comment by e-tienne** [comment]
master/e2e-azure-upi — Job succeeded.

/hold

**Review by staebler — COMMENTED** [review]
Looks good. Squash it down to a single commit, please.

**Review by staebler — APPROVED** [review]
/lgtm

**Pull request merged**
