### PR TITLE
Create template to deploy Jenkins CI components

### PR DESCRIPTION
**Pull request by csrwng**
Adds a template to deploy CI artifacts to a new OpenShift project.

### CODE REVIEW

**Comment by csrwng** [comment]
@stevekuznetsov I ended up going with a template+jenkins rather than a playbook. I wanted to impose the least amount of resources on the client. With the template all you need is a valid cluster running and either web or cli access.

Secrets should be added directly to the template. At this point I don't know what secrets we will require, but we can handle in a follow-up PR. At that point we may want to include a script to deploy the template that will invoke something like:

```
oc process -p SECRET1="$(cat "${LOCATION_OF_SECRET1}")" \
           -p SECRET2="$(cat "${LOCATION_OF_SECRET2}")" \
           -f jenkins-setup-template.yaml | oc apply
```

**Comment by stevekuznetsov** [comment]
Seems reasonable. Since we're not expecting Ansible for the rest of the CI cluster set-up on the controller host, not requiring it here makes sense as well. I guess my only concerns would be:

 - are we fairly confident in the idempotence of the bootstrap job in Jenkins? Is it dangerous to accidentally push later on?
 - do we care that our in-lined persistent Jenkins bits from the template will drift from the upstream?

**Comment by stevekuznetsov** [comment]
Secrets we would want, off the top of my head:

 - GCE credentials
 - AWS credentials
 - SSH keys to provisioned nodes
 - GitHub API tokens

**Comment by csrwng** [comment]
> are we fairly confident in the idempotence of the bootstrap job in Jenkins? Is it dangerous to accidentally push later on?

It is idempotent, I ran it several times to test things and make changes. Furthermore, if you change your jjb jobs or other templates in the source repo, running the pipeline again applies those changes.

> do we care that our in-lined persistent Jenkins bits from the template will drift from the upstream?

It's less than ideal to include it in our template. The reason I ended up including it is because we need to add plugins on install (set the env var to do that). I'm thinking that a possible way to avoid doing that would be to have the template instantiate a job that sets up Jenkins first and then starts instantiating the other stuff. Having said that, I doubt that we will change the way we instantiate Jenkins upstream. Recent changes to the template have been minimal.

**Comment by stevekuznetsov** [comment]
OK. Sounds good. Let's merge this and see if we can finish the auth stuff as well as get this deployed on the next CI cluster re-spin.

**Pull request merged**
