### PR TITLE
don't run expensive etcd tests on doc changes

### PR DESCRIPTION
**Pull request by tjungblu**
as recommended at https://github.com/openshift/cluster-etcd-operator/pull/920#issuecomment-1234537413

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
@wking@wking iirc you don't need to do `skip_if_only_changed` if the job is optional right?

**Comment by tjungblu** [comment]
I believe it would still run the optional jobs and not skip them - they would surely not block the merge when they fail.

**Comment by tjungblu** [comment]
/assign @Elbehery 

Mustafa when you have some time tomorrow, could you PTAL for a lgtm?

**Pull request merged**
