### PR TITLE
add periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.17

### PR DESCRIPTION
**Pull request by amp-rh**
See [INTEROP-7454](https://issues.redhat.com/browse/INTEROP-7454)

### CODE REVIEW

**Comment by amp-rh** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.17-stage-opentelemetry-stage-tests

**Comment by amp-rh** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.17-stage-opentelemetry-stage-tests

**Review by calebevans — APPROVED** [review]
/lgtm

**Comment by IshwarKanse** [comment]
@amp-rh Hi, you need to add an interop job which tests the released OpenTelemetry operator version with OCP 4.17. The job config that you are adding is for stage testing, which is used for testing a pre-release operator version. You can refer the existing interop job configs for adding the 4.17 job. Refer the jobs which has interop in their name.

**Comment by IshwarKanse** [comment]
For OpenTelemetry https://github.com/openshift/release/blob/master/ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.16-lp-interop.yaml

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.17-lp-interop-opentelemetry-interop-aws

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.17-lp-interop-opentelemetry-interop-aws

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.17-lp-interop-opentelemetry-interop-aws

**Pull request merged**
