### PR TITLE
OCPQE-22599: use specific autorelease cluster profile for gcp/azure autorelease ci jobs

### PR DESCRIPTION
**Pull request by jianlinliu**
Also resolve https://issues.redhat.com/browse/OCPQE-22600 together

### CODE REVIEW

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-automated-release-azure-ipi-marketplace-mini-perm-f360 periodic-ci-openshift-openshift-tests-private-release-4.16-automated-release-gcp-ipi-mini-perm-custom-type-f360

**Comment by jianlinliu** [comment]
cc @jinyunma @jianli-wei @rioliu-rh @liangxia to review.

**Comment by rioliu-rh** [comment]
lgtm +1

**Comment by liangxia** [comment]
The error `environment: line 311: pushd: verification-tests: No such file or directory` got fixed in https://github.com/openshift/release/pull/53079

**Pull request merged**
