### PR TITLE
CONSOLE-3303: Image mirroring for nodejs-16 and nginx:stable, and build image for console plugin template 

### PR DESCRIPTION
**Pull request by cajieh**

### CODE REVIEW

**Comment by smg247** [comment]
I was poking around to see where the base image was coming from, and found: https://github.com/openshift/release/pull/35931. I know it was approved, but we can't mirror images from `docker.io`. Eventually, we end up being rate limited and jobs start to fail. You will have to get this image on quay somehow and then mirror it from there.

**Comment by cyril-ui-developer** [comment]
/assign @jhadvig 
cc: @smg247

**Comment by smg247** [comment]
Feel free to remove the hold whenever

**Pull request merged**
