### PR TITLE
build01: bump system reserved for kubelets

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @smarterclayton

### CODE REVIEW

**Comment by smarterclayton** [comment]
/lgtm

I will be recommending a similar change to api.ci, but investigating docker usage right now

**Comment by hongkailiu** [comment]
@stevekuznetsov 

RBAC missing?
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/7525/pull-ci-openshift-release-master-build01-dry/6591#1:build-log.txt%3A12

**Comment by smarterclayton** [comment]
api.ci is rolled out to 7Gi, this is the change to put that in version control config https://github.com/openshift/release/pull/7530

**Pull request merged**
