### PR TITLE
updating the config for having all recent images

### PR DESCRIPTION
**Pull request by matzew**
@lberk fixing the e2e test, since the `sequencesteper` image was not included ... :-(

### CODE REVIEW

**Comment by alanfx** [comment]
@matzew these PRs are impossible to review, but I think it looks good!
/lgtm
/approve

**Comment by stevekuznetsov** [comment]
@alanfx if you have suggestions on how to make them easier to review please let me know :)

**Comment by alanfx** [comment]
Hey @stevekuznetsov, I think the biggest issue is that the order gets changed every time there is an update, so it is confusing to figure out what is added or removed. Sorting the lines maybe?

**Pull request merged**
