### PR TITLE
Update openshift-cluster-logging-operator-master.yaml

### PR DESCRIPTION
**Pull request by jcantrill**
Use make check in unit test to get extra goodness from linting

### CODE REVIEW

**Review by alanconway — COMMENTED** [review]
/lgtm

**Review by igor-karpukhin — APPROVED** [review]
/lgtm

**Review by alanconway — APPROVED** [review]
/lgtm

**Comment by alanconway** [comment]
/hold

We have download problems: 
```
Extracting openshift client binary....
curl: (22) The requested URL returned error: 404 File not found
```

This ain't gonna work unless we put the tools somewhere that CI can get them (in an image?) or commit them to the repo (don't like that, will slow down use of repo and doesn't belong there)
@blockloop had ideas about putting tools in an image.

**Pull request closed without merging**
