### PR TITLE
Updated search-e2e prow

### PR DESCRIPTION
**Pull request by dislbenn**
Related issue: https://github.com/stolostron/backlog/issues/19026

Signed-off-by: dislbenn <lavontae.bennett@gmail.com>

### CODE REVIEW

**Review by jlpadilla — APPROVED** [review]
/lgtm

**Comment by jlpadilla** [comment]
@dislbenn the lint jobs are failing, the problem seems to bee in the project, not with this PR.  We can merge this, but we'll need to fix the project before we can merge anything else there.

**Comment by mqhackett** [comment]
Yep, it looks like the linting is failing because npm run lint is failing upstream. See this error line: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/25944/rehearse-25944-pull-ci-stolostron-search-e2e-test-release-2.5-lint/1489021967708196864#1:build-log.txt%3A68

**Pull request merged**
