### PR TITLE
wmco: mark security job as required

### PR DESCRIPTION
**Pull request by jrvaldes**
This partially reverts commit f52689b5c0d4eebcb0a0dbe1d6e2aa36afeb4451.

snyk fixes in:
- https://github.com/openshift/release/pull/46819

### CODE REVIEW

**Comment by mansikulkarni96** [comment]
Thanks for fixing this @jrvaldes 
/approve

**Comment by jrvaldes** [comment]
/hold 

for release-4.11 failure

**Comment by jrvaldes** [comment]
/hold cancel

release-4.11/security job [issue](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/46843/rehearse-46843-pull-ci-openshift-windows-machine-config-operator-release-4.11-security/1735653840574746624) to be addressed in separate PR to avoid blocking CI for release-4.11

**Comment by jrvaldes** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.15-security

**Pull request merged**
