### PR TITLE
Add openshift/build-test-images to tide

### PR DESCRIPTION
**Pull request by adambkaplan**
- Build simples2i image in addition to roots2i image
- Add build-test-images repo to tide, add approve plugin
- Add e2e-aws and e2e-aws-builds suites to tests

### CODE REVIEW

**Review by alvaroaleman — APPROVED** [review]
for the config change
/hold
cancel at your convenience

**Comment by yselkowitz** [comment]
What benefit is there to adding these images to registry.ci?  Since openshift internal registries do not support manifest lists, I'm worried that even if we were to build and push the redhat-developer build multi-arch enabled, if it goes through registry.ci, we'll only get x86 mirrored into openshift/community-e2e-images, and we'll still need a multi-arch override for testing.  Why can't the redhat-developer build (with a versioned tag) be mirrored directly without going through registry.ci?

**Comment by adambkaplan** [comment]
> What benefit is there to adding these images to registry.ci?

@yselkowitz adding the images to registry.ci was based on @gabemontero's comment [here](https://github.com/openshift/origin/pull/26149#pullrequestreview-657239897). We are already pushing the roots2i image, how is the simples2i image any different? How are multiarch images published to quay.io otherwise?

**Comment by gabemontero** [comment]
> > What benefit is there to adding these images to registry.ci?
> 
> @yselkowitz adding the images to registry.ci was based on @gabemontero's comment [here](https://github.com/openshift/origin/pull/26149#pullrequestreview-657239897). We are already pushing the roots2i image, how is the simples2i image any different? How are multiarch images published to quay.io otherwise?

Yep, following the pattern we started with roots2i (in hindsight, we should have done both when we were in here last time).
This pattern stemmed from interactions between @bparees and I with Clayton.

Among other things, it makes running our e2e in disconnected more seamless.

**Comment by gabemontero** [comment]
the failure at https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/18523/rehearse-18523-pull-ci-openshift-build-test-images-master-e2e-aws-builds/1392513319411126272 was the known verify /run based on recent node team changes 

still catching up on email, but this is mergeable IMO based on manual testing and what we see here with e2e-gcp-builds

**Pull request merged**
