### PR TITLE
OCPBUGS-18596,OCPBUGS-22382: use two replicas when provisioning registry on vsphere

### PR DESCRIPTION
**Pull request by flavianmissi**
Builds up on the work from https://github.com/openshift/release/pull/43694

### CODE REVIEW

**Comment by flavianmissi** [comment]
@wewang58 @jianlinliu could you help validate this one? TRT is still seeing disruptions on vsphere so this PR increases the number of replicas to 2 (without changing deployment strategy) in an attempt to lower disruptions.
Thanks!

**Comment by wewang58** [comment]
@flavianmissi  if increase the number of replicas to 2, it can reduce the failure?  if so i will submit a pr cc @jianlinliu

**Comment by wewang58** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-vsphere-ipi-proxy-tp-f28

**Comment by wewang58** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-vsphere-ipi-compact-f14

**Comment by wewang58** [comment]
@flavianmissi the step:[ipi-install-vsphere-registry](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/44828/rehearse-44828-periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-vsphere-ipi-compact-f14/1717362343752503296) failed

**Comment by flavianmissi** [comment]
hmm yes the logs say `cannot use ReadWriteOnce access mode with more than one replica of the image registry` which makes sense. I'll have a look.

**Comment by flavianmissi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-vsphere-ipi-compact-f14

**Comment by flavianmissi** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-vsphere-ipi-proxy-tp-f28

**Comment by wewang58** [comment]
Launched a vsphere cluster locally and create pvc with ReadWriteMany access mode, use 2 replicas, [met issues](https://privatebin.corp.redhat.com/?5417b2a0f152c59f#DVopULx5TofsxdLCoAotSsaN9Dc1k1pf7Q7E1HDkqSq4) too, synced with @duanwei33, currently we should not support update 2 replicas with the pvc defined,  @flavianmissi  can create a new story to research how to support the scenario.

**Comment by flavianmissi** [comment]
thanks @wewang58 , closing this until we have a plan.
/close

**Comment by duanwei33** [comment]
Hi @flavianmissi @wewang58, to be more accurate, vSphere CSI Driver does support the RWX access mode but replies on the vSphere version and vSAN, so it might fail in our CI.
See https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/3.0/vmware-vsphere-csp-getting-started/GUID-D4AAD99E-9128-40CE-B89C-AD451DA8379D.html for the detail.

**Pull request closed without merging**
