### PR TITLE
Run RHEL scaleup test for openshift-ansible master branch

### PR DESCRIPTION
**Pull request by vrutkovs**
4.0 development in `devel-40` is over

### CODE REVIEW

**Comment by vrutkovs** [comment]
Rehearse won't work, as this PR is a prerequisite for https://github.com/openshift/openshift-ansible/pull/11358

**Comment by sdodson** [comment]
Should we go ahead and use Clayton's suggested name of 'e2e-aws-scaleup-rhel7' ?

**Comment by vrutkovs** [comment]
Good idea, that'd clarify its RHEL7, not RHEL8 test. Updated

**Pull request merged**
