### PR TITLE
[LPTOCPCI-783] Add image promotions for mtc-apps-deployer and mtc-python-client

### PR DESCRIPTION
**Pull request by calebevans**
Note: I am replacing the oadp-qe/mtc-python-client with mtc-qe/mtc-python-client. They are the same repo from GitLab mirrored to GitHub. I think it makes more sense to have that image in the mtc-qe org.

### CODE REVIEW

**Comment by ascerra** [comment]
I just want to make sure I understand this fully.
- so the oadp-qe/mtc-python-client is currently being used by the OADP scenario.
- Now we are working on the MTC scenario and it calls for the same client.
- so we are just cleaning up the naming since its really just the mtc-python-client that is being used by the OADP scenario.

**Comment by calebevans** [comment]
> scenario

@ascerra yes that is correct

**Comment by smg247** [comment]
@calebevans these repos are causing our branch-protection job to fail:
```
{"component":"branchprotector","error":"update mtc-qe/mtc-python-client: update master from protected=false: get current branch protection: the GitHub API request returns a 403 error: {\"message\":\"Upgrade to GitHub Pro or make this repository public to enable this feature.\",\"documentation_url\":\"https://docs.github.com/rest/branches/branch-protection#get-branch-protection\"}","file":"k8s.io/test-infra/prow/cmd/branchprotector/protect.go:142","func":"main.main","level":"error","msg":"0","severity":"error","time":"2023-09-29T14:04:21Z"}
{"component":"branchprotector","error":"update mtc-qe/mtc-apps-deployer: update master from protected=false: get current branch protection: the GitHub API request returns a 403 error: {\"message\":\"Upgrade to GitHub Pro or make this repository public to enable this feature.\",\"documentation_url\":\"https://docs.github.com/rest/branches/branch-protection#get-branch-protection\"}","file":"k8s.io/test-infra/prow/cmd/branchprotector/protect.go:142","func":"main.main","level":"error","msg":"1","severity":"error","time":"2023-09-29T14:04:21Z"}
```
It appears that the repos don't allow our automation to check the branch protection settings. Can you correct this, either by changing repo settings, or by disabling branch protection for them?

**Comment by calebevans** [comment]
@smg247 these repos don't have any branch protections on them. Both of the bots and the app have permissions in the org for all repositories. What specifically do you think I need to change in the settings?

**Comment by calebevans** [comment]
@smg247 I can look into adding this but I have never had to do it for private repositories before. I'll send in a PR.

**Comment by calebevans** [comment]
@smg247 Here is the PR: https://github.com/openshift/release/pull/43845

**Pull request merged**
