### PR TITLE
replace workflow to accelerate ocm observability e2e test.

### PR DESCRIPTION
**Pull request by morvencao**
Ref: open-cluster-management/backlog#10140

### CODE REVIEW

**Review by songleo — APPROVED** [review]

**Comment by morvencao** [comment]
Looks like there is no outstanding improvement after I update the workflow, see the job https://prow.ci.openshift.org/log?container=test&id=1371346523132006400&job=rehearse-16798-pull-ci-open-cluster-management-observability-e2e-test-main-test-e2e and https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/16798/rehearse-16798-pull-ci-open-cluster-management-observability-e2e-test-main-test-e2e/1371346523132006400
It still takes over 1 hour to run the whole E2E test.

**Comment by morvencao** [comment]
I got some feedback from `dptp-helpdesk` team in slack channel #forum-testplatform
> Q: @dptp-helpdesk Is there any way to accelerate the e2e test in OCP cluster for prow, we’re using openshift-e2e-aws  workflow now, I thought ipi-aws  would be faster, but it is not after I updated the workflow, it still takes about 1 hour to finish the whole test.

> A: No, I don't think there is any way to accelerate how fast OpenShift installs
> There is no reason ipi-aws would install any faster than openshift-e2e-aws
> The whole workflow will definitely be faster, because openshift-e2e-aws is essentially ipi-aws + a test step, but I assume you define a test step yourself, so end up running basically the same thing, no matter what workflow do you use.
> Actually, maybe https://docs.ci.openshift.org/docs/architecture/step-registry/#skipping-post-steps-on-success could help with 1) green job runtime 2) if you don't care about some artifact gathering on green jobs

So replacing the workflow doesn't work, we should consider the skipping-post-steps-on-success, but also I don't think that helps a lot.

**Pull request closed without merging**
