### PR TITLE
Fix HCP versions not found

### PR DESCRIPTION
**Pull request by svetsa-rh**

### CODE REVIEW

**Comment by svetsa-rh** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.13-nightly-x86-perfscale-rosa-hcp-1zone-data-path-2nodes-periodic periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.14-nightly-x86-perfscale-rosa-hcp-1zone-data-path-2nodes-periodic

**Review by chentex — APPROVED** [review]

**Comment by svetsa-rh** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.13-nightly-x86-perfscale-rosa-hcp-1zone-data-path-2nodes-periodic periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.14-nightly-x86-perfscale-rosa-hcp-1zone-data-path-2nodes-periodic

**Comment by svetsa-rh** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.13-nightly-x86-perfscale-rosa-hcp-1zone-data-path-2nodes-periodic periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.14-nightly-x86-perfscale-rosa-hcp-1zone-data-path-2nodes-periodic

**Comment by svetsa-rh** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.13-nightly-x86-perfscale-rosa-hcp-1zone-data-path-2nodes-periodic /pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.14-nightly-x86-perfscale-rosa-hcp-1zone-data-path-2nodes-periodic

**Comment by svetsa-rh** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.13-nightly-x86-perfscale-rosa-hcp-1zone-data-path-2nodes-periodic /pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.14-nightly-x86-perfscale-rosa-hcp-1zone-data-path-2nodes-periodic

**Comment by svetsa-rh** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.13-nightly-x86-perfscale-rosa-hcp-1zone-data-path-2nodes-periodic /pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.14-nightly-x86-perfscale-rosa-hcp-1zone-data-path-2nodes-periodic

**Comment by svetsa-rh** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.13-nightly-x86-perfscale-rosa-hcp-1zone-data-path-2nodes-periodic /pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.14-nightly-x86-perfscale-rosa-hcp-1zone-data-path-2nodes-periodic

**Comment by svetsa-rh** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.15-nightly-x86-perfscale-rosa-hcp-1zone-data-path-2nodes-periodic

**Comment by svetsa-rh** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.15-nightly-x86-perfscale-rosa-hcp-1zone-data-path-2nodes-periodic

**Comment by svetsa-rh** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.13-nightly-x86-perfscale-rosa-hcp-1zone-data-path-2nodes-periodic /pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.14-nightly-x86-perfscale-rosa-hcp-1zone-data-path-2nodes-periodic pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.15-nightly-x86-perfscale-rosa-hcp-1zone-data-path-2nodes-periodic

**Comment by svetsa-rh** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.15-nightly-x86-perfscale-rosa-hcp-1zone-data-path-2nodes-periodic

**Comment by svetsa-rh** [comment]
/pj-rehearse ack

For the scope of this PR, all 3 tests are now passing. Original issue was about cluster creation failure. We are now able to get past that and failing in network tests, which Joe and Sachin confirmed are flakes or known issues (see https://redhat-internal.slack.com/archives/C05CDC19ZKJ/p1698713255158609) 

4.15 nightly - https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/45058/rehearse-45058-pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.15-nightly-x86-perfscale-rosa-hcp-1zone-data-path-2nodes-periodic/1719151368830193664
4.14 nightly - https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/45058/rehearse-45058-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.14-nightly-x86-perfscale-rosa-hcp-1zone-data-path-2nodes-periodic/1719078098047078400
4.13 nightly - https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/45058/rehearse-45058-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.13-nightly-x86-perfscale-rosa-hcp-1zone-data-path-2nodes-periodic/1719078098005135360

**Comment by svetsa-rh** [comment]
4.13 cluster created successfully https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/45058/rehearse-45058-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.13-nightly-x86-perfscale-rosa-hcp-1zone-data-path-2nodes-periodic/1719078098005135360/artifacts/perfscale-rosa-hcp-1zone-data-path-2nodes-periodic/rosa-cluster-provision/build-log.txt 
4.14 cluster created successfully https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/45058/rehearse-45058-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.14-nightly-x86-perfscale-rosa-hcp-1zone-data-path-2nodes-periodic/1719078098047078400/artifacts/perfscale-rosa-hcp-1zone-data-path-2nodes-periodic/rosa-cluster-provision/build-log.txt
4.15 cluster created successfully 13 cluster created successfully https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/45058/rehearse-45058-pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.15-nightly-x86-perfscale-rosa-hcp-1zone-data-path-2nodes-periodic/1719151368830193664/artifacts/perfscale-rosa-hcp-1zone-data-path-2nodes-periodic/rosa-cluster-provision/build-log.txt

**Review by chentex — APPROVED** [review]
LGTM

**Pull request merged**
