### PR TITLE
okd-machine-os: add e2e-openstack test

### PR DESCRIPTION
**Pull request by vrutkovs**
Adds ad-hoc optional openstack test for okd-machine-os changes

TODO:
* [x] Investigate `"cinder": executable file not found in $PATH`
      Requires https://github.com/openshift/origin/pull/26131

### CODE REVIEW

**Comment by vrutkovs** [comment]
Rehearsals fail with:
```
Node 62kvjwms-7dc7e-9578p-master-1 is reporting: "machineconfig.machineconfiguration.openshift.io \"rendered-master-8948abb5b3011f9c36aa4851feeb662e\" not found", Node 62kvjwms-7dc7e-9578p-master-2 is reporting: "machineconfig.machineconfiguration.openshift.io \"rendered-master-8948abb5b3011f9c36aa4851feeb662e\" not found", Node 62kvjwms-7dc7e-9578p-master-0 is reporting: "machineconfig.machineconfiguration.openshift.io \"rendered-master-8948abb5b3011f9c36aa4851feeb662e\" not found"
```
we'll figure it out later

**Comment by LorbusChris** [comment]
Do we want to add a test for 4.7 as well?

**Comment by vrutkovs** [comment]
Added 4.7, PTAL. master/4.6 seems to be stuck at master failing to start

**Comment by LorbusChris** [comment]
@vrutkovs rpm-ostree failed to install the extenions
```
● machine-config-daemon-firstboot.service - Machine Config Daemon Firstboot
     Loaded: loaded (/etc/systemd/system/machine-config-daemon-firstboot.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2021-03-03 17:43:42 UTC; 24min ago
    Process: 1742 ExecStartPre=/usr/bin/sh -c sed -i 's/enabled=1/enabled=0/' /etc/yum.repos.d/*.repo (code=exited, status=0/SUCCESS)
    Process: 1744 ExecStart=/run/bin/machine-config-daemon firstboot-complete-machineconfig (code=exited, status=1/FAILURE)
   Main PID: 1744 (code=exited, status=1/FAILURE)
        CPU: 2min 39.771s

Mar 03 17:43:22 246yglqq-7dc7e-dml5f-master-1 machine-config-daemon[1744]: I0303 17:43:22.317184    1744 update.go:963] Applying extensions : ["update" "--install" "glusterfs" "--install" "glusterfs-fuse" "--install" "qemu-guest-agent" "--install" "NetworkManager-ovs"]
Mar 03 17:43:27 246yglqq-7dc7e-dml5f-master-1 machine-config-daemon[1744]: I0303 17:43:27.517215    1744 update.go:376] Rolling back applied changes to OS due to error: failed to execute rpm-ostree ["update" "--install" "glusterfs" "--install" "glusterfs-fuse" "--install" "qemu-guest-agent" "--install" "NetworkManager-ovs"] : exit status 1
Mar 03 17:43:27 246yglqq-7dc7e-dml5f-master-1 machine-config-daemon[1744]: I0303 17:43:27.517296    1744 rpm-ostree.go:261] Running captured: rpm-ostree cleanup -p
Mar 03 17:43:42 246yglqq-7dc7e-dml5f-master-1 machine-config-daemon[1744]: I0303 17:43:42.344754    1744 update.go:1049] Updating files
Mar 03 17:43:42 246yglqq-7dc7e-dml5f-master-1 machine-config-daemon[1744]: I0303 17:43:42.353539    1744 update.go:1122] Deleting stale data
Mar 03 17:43:42 246yglqq-7dc7e-dml5f-master-1 machine-config-daemon[1744]: error: failed to execute rpm-ostree ["update" "--install" "glusterfs" "--install" "glusterfs-fuse" "--install" "qemu-guest-agent" "--install" "NetworkManager-ovs"] : exit status 1
Mar 03 17:43:42 246yglqq-7dc7e-dml5f-master-1 systemd[1]: machine-config-daemon-firstboot.service: Main process exited, code=exited, status=1/FAILURE
Mar 03 17:43:42 246yglqq-7dc7e-dml5f-master-1 systemd[1]: machine-config-daemon-firstboot.service: Failed with result 'exit-code'.
Mar 03 17:43:42 246yglqq-7dc7e-dml5f-master-1 systemd[1]: Failed to start Machine Config Daemon Firstboot.
Mar 03 17:43:42 246yglqq-7dc7e-dml5f-master-1 systemd[1]: machine-config-daemon-firstboot.service: Consumed 2min 39.771s CPU time.
```

**Comment by vrutkovs** [comment]
Right, https://github.com/openshift/okd-machine-os/pull/94 should fix that

**Comment by vrutkovs** [comment]
/retest

master branch test failed

**Comment by LorbusChris** [comment]
Had a look at the failure logs, most are timouts but there is this:
`"cinder": executable file not found in $PATH`, which is probably not shipped in FCOS.

**Comment by vrutkovs** [comment]
Hmm, probably OKD's upi-installer is not updated? I'll have a look

**Pull request closed without merging**
