### PR TITLE
Highlight TAP failure messages

### PR DESCRIPTION
**Pull request by porridge**
The [Test Anything Protocol](https://testanything.org/) is used by [BATS](https://github.com/bats-core/bats-core?tab=readme-ov-file) among other things (Perl testing too IIRC).

Example from [this log](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stackrox_stackrox/12068/pull-ci-stackrox-stackrox-master-ocp-4-15-scanner-v4-tests/1815513191896059904):
```
**** 23:08:35: About to run test
****
Executing the ScannerV4 Test
Worker node types for Scanner V4 tests:
rox-ci-96059904-tqhj4-master-0.c.acs-san-stackroxci.internal: e2-standard-8
rox-ci-96059904-tqhj4-master-1.c.acs-san-stackroxci.internal: e2-standard-8
rox-ci-96059904-tqhj4-master-2.c.acs-san-stackroxci.internal: e2-standard-8
rox-ci-96059904-tqhj4-worker-a-24fm7: e2-standard-16
rox-ci-96059904-tqhj4-worker-b-5q4g9: e2-standard-16
1..10
ok 1 Upgrade from old Helm chart to HEAD Helm chart with Scanner v4 enabled # in 1020671 ms
ok 2 Fresh installation of HEAD Helm chart with Scanner V4 disabled and enabling it later # in 856857 ms
ok 3 Fresh installation of HEAD Helm chart with Scanner v4 enabled # in 567917 ms
ok 4 Fresh installation of HEAD Helm charts with Scanner v4 enabled in multi-namespace mode # in 735375 ms
ok 5 [Manifest Bundle] Fresh installation without Scanner V4, adding Scanner V4 later # in 629253 ms
not ok 6 [Operator] Fresh installation with Scanner V4 enabled # in 176[123](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stackrox_stackrox/12068/pull-ci-stackrox-stackrox-master-ocp-4-15-scanner-v4-tests/1815513191896059904#1:build-log.txt%3A123) ms
# (from function `deploy_central_via_operator' in file tests/e2e/lib.sh, line 240,
#  from function `deploy_central' in file tests/e2e/lib.sh, line 214,
#  from function `_deploy_central' in file tests/e2e/run-scanner-v4.bats, line 711,
#  from function `_deploy_stackrox' in file tests/e2e/run-scanner-v4.bats, line 683,
#  in test file tests/e2e/run-scanner-v4.bats, line 370)
#   `_deploy_stackrox' failed
# INFO: Tue Jul 23 00:12:12 UTC 2024: Setting up GCP auth and config
# Current project is already set to acs-san-stackroxci. Assuming configuration already applied.
# INFO: Tue Jul 23 00:12:12 UTC 2024: Setting up the deployment environment
```

@janisz FYI

### CODE REVIEW

**Review by janisz — APPROVED** [review]

**Comment by porridge** [comment]
@deepsm007 or @Prucek can you please approve? 🥺

**Pull request merged**
