### PR TITLE
Adding CNV -lp-interop config files and jobs for interop-testing

### PR DESCRIPTION
**Pull request by Sau1506mya**

### CODE REVIEW

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.16-cnv-odf-ocp4.16-lp-interop-cnv-odf-tests-aws-upi-ocp416 pull-ci-RedHatQE-interop-testing-cnv-4.16-cnv-odf-ocp4.16-lp-interop-images

**Comment by Sau1506mya** [comment]
/pj-rehearse pull-ci-RedHatQE-interop-testing-cnv-4.14-cnv-odf-ocp4.14-lp-interop-images pull-ci-RedHatQE-interop-testing-cnv-4.15-cnv-odf-ocp4.15-lp-interop-images pull-ci-RedHatQE-interop-testing-cnv-4.16-cnv-odf-ocp4.16-lp-interop-images periodic-ci-RedHatQE-interop-testing-cnv-4.14-cnv-odf-ocp4.14-lp-interop-cnv-odf-tests-aws-upi-ocp414 periodic-ci-RedHatQE-interop-testing-cnv-4.15-cnv-odf-ocp4.15-lp-interop-cnv-odf-tests-aws-upi-ocp415 periodic-ci-RedHatQE-interop-testing-cnv-4.16-cnv-odf-ocp4.16-lp-interop-cnv-odf-tests-aws-upi-ocp416

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.14-cnv-odf-ocp4.14-lp-interop-cnv-odf-tests-aws-upi-ocp414

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.14-cnv-odf-ocp4.14-lp-interop-cnv-odf-tests-aws-upi-ocp414

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.14-cnv-odf-ocp4.14-lp-interop-cnv-odf-tests-aws-upi-ocp414

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.14-cnv-odf-ocp4.14-lp-interop-cnv-odf-tests-aws-upi-ocp414

**Review by Simranpal — APPROVED** [review]
/lgtm

**Review by lukas-bednar — APPROVED** [review]
/lgtm

**Pull request merged**
