### PR TITLE
Add workflow for gcp ipi sdn2ovn rollback

### PR DESCRIPTION
**Pull request by weliang1**
https://issues.redhat.com/browse/OCPQE-11141: IPI GCP sdn migration to ovn and rollback

@zhaozhanqi @lihongan PTAL!

### CODE REVIEW

**Comment by jianlinliu** [comment]
No validation job to test the new workflow.

**Comment by weliang1** [comment]
Can not update validation job any more in this PR, just close it and open [this new PR](https://github.com/openshift/release/pull/32494) to do the same thing.

**Pull request closed without merging**
