### PR TITLE
Move mariadb and neutron prow jobs over from 4.14 to 4.15 Hive cluster

### PR DESCRIPTION
**Pull request by bshewale**

### CODE REVIEW

**Comment by lewisdenny** [comment]
#/pj-rehearse pull-ci-openstack-k8s-operators-mariadb-operator-main-mariadb-operator-build-deploy-kuttl pull-ci-openstack-k8s-operators-neutron-operator-main-neutron-operator-build-deploy-kuttl pull-ci-openstack-k8s-operators-neutron-operator-main-neutron-operator-build-deploy-tempest

**Comment by bshewale** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-mariadb-operator-main-mariadb-operator-build-deploy-kuttl pull-ci-openstack-k8s-operators-neutron-operator-main-neutron-operator-build-deploy-kuttl pull-ci-openstack-k8s-operators-neutron-operator-main-neutron-operator-build-deploy-tempest

**Comment by bshewale** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-mariadb-operator-main-mariadb-operator-build-deploy-kuttl

**Comment by viroel** [comment]
lgtm

**Review by lewisdenny — APPROVED** [review]
/unhold

**Pull request merged**
