### PR TITLE
shiftstack/ci-configs: Add repository to Prow

### PR DESCRIPTION
**Pull request by pierreprinetti**
shiftstack/ci-configs will contain OpenStack environment definitions
ready to be deployed with shiftstack/dev-install.

Part of [OSASINFRA-2468](https://issues.redhat.com/browse/OSASINFRA-2468)

### CODE REVIEW

**Review by alvaroaleman — APPROVED** [review]

**Comment by alvaroaleman** [comment]
Cancel the hold at your convenience, I am not sure if you wanted this to merge already

**Comment by pierreprinetti** [comment]
/hold cancel
The repo's Dockerfile needs to be fixed, but it's easier to fix if this test is running in PRs.

**Review by mandre — COMMENTED** [review]
/lgtm

**Pull request merged**
