### PR TITLE
Interop - Expand MTC on ROSA to OCP 4.16

### PR DESCRIPTION
**Pull request by oharan2**

### CODE REVIEW

**Comment by oharan2** [comment]
/pj-rehearse pull-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.16-lp-rosa-classic-images

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.16-lp-rosa-classic-mtc-interop-aws-rosa

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
