### PR TITLE
ART-10673 Point 4.16 rhel9 repos to 9.4

### PR DESCRIPTION
**Pull request by locriandev**
Ref. [ART-10673](https://issues.redhat.com/browse/ART-10673) / [ART-10671](https://issues.redhat.com/browse/ART-10671)

### CODE REVIEW

**Comment by joepvd** [comment]
/lgtm

Needs to go with:
https://github.com/openshift-eng/ocp-build-data/pull/5409
https://github.com/openshift-eng/ocp-build-data/pull/5407

**Comment by sdodson** [comment]
/approve
Thanks, this is fine as we expect 9.4 modules to patch 9.2 modules in terms of validation timelines and worst case if they're slightly behind RHCOS in 4.16 is still based on 9.4 anyway.

**Comment by sdodson** [comment]
/hold
To see if we need coordination.

**Pull request merged**
