### PR TITLE
ci-operator/config/openshift/release: Bump oldest-supported-z-rollback to 4.7.21 and 4.8.2

### PR DESCRIPTION
**Pull request by wking**
For 4.8.2, this is because we've gone GA (following up on #20292, slightly before GA).

For 4.7.20, this is because 4.7.20 introduced a one-way update to a v2 OperatorConditions CRD, operator-framework/operator-lifecycle-manager#2206, [rhbz#1983158](https://bugzilla.redhat.com/show_bug.cgi?id=1983158#c5).

### CODE REVIEW

**Comment by bparees** [comment]
/lgtm

gets us back to green CI so we know if things get worse, but we need to continue to discuss the OLM change that broke z-stream downgrades and figure out what, if anything, we need to do to ensure customers can downgrade from 4.7.20+ to something older.

**Comment by wking** [comment]
4.7.20 was tombstoned (openshift/cincinnati-graph-data#918), so I've pushed d8c6dc209f -> 6488b3b929 moving to 4.7.21 instead.

**Comment by bparees** [comment]
/lgtm
/hold

@wking release the hold when you're happy w/ the rehearse results

**Comment by wking** [comment]
[4.7.21 -> 4.7.0-0.nightly-2021-08-03-004105 -> 4.7.21 passed][1], and there wasn't a 4.8 rehearsal, but I'm confident that 4.8.2 is GA, and am not aware of specific rollback-breaking changes in 4.8.z yet.

/hold cancel

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/20847/rehearse-20847-periodic-ci-openshift-release-master-nightly-4.7-e2e-aws-upgrade-rollback-oldest-supported/1422572441485447168

**Pull request merged**
