### PR TITLE
Add verify-deps step to client-go

### PR DESCRIPTION
**Pull request by soltysh**
To catch problems like the one in https://github.com/openshift/client-go/pull/287

/assign @dinhxuanvu

### CODE REVIEW

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Comment by soltysh** [comment]
/hold
for rehearse

**Comment by soltysh** [comment]
/hold cancel
this is going to be a new job, so we can't rehearse it

**Comment by soltysh** [comment]
/pj-rehearse pull-ci-openshift-client-go-master-verify-deps
/pj-rehearse pull-ci-openshift-client-go-release-4.16-verify-deps

**Comment by soltysh** [comment]
/pj-rehearse pull-ci-openshift-client-go-release-4.16-verify-deps

**Review by dinhxuanvu — COMMENTED** [review]
/lgtm

**Pull request merged**
