### PR TITLE
Update COO AWS based jobs to use cluster observability cluster poo

### PR DESCRIPTION
**Pull request by lihongyan1**
https://issues.redhat.com/browse/COO-83

### CODE REVIEW

**Comment by lihongyan1** [comment]
/pj-rehearse pull-ci-rhobs-observability-operator-main-observability-operator-e2e

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-coo-interop-production

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.15-coo-stage

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.15-coo-qeindex

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.12-coo-qeindex

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.12-coo-stage

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.12-coo-stage

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.12-coo-qeindex

**Comment by lihongyan1** [comment]
/pj-rehearse periodic-ci-rhobs-observability-operator-main-ocp-4.12-coo-stage

**Comment by jan--f** [comment]
/lgtm
/pj-rehearse ack
Thank you!

**Comment by lihongyan1** [comment]
The latest push just rebase code on master, no new change.

**Comment by lihongyan1** [comment]
@jan--f Please help add lgtm again, thanks

**Pull request merged**
