### PR TITLE
expansion of jws scenario to run for 4.18

### PR DESCRIPTION
**Pull request by vi-patel**
add FIREWATCH_DEFAULT_JIRA_ASSIGNEE
  create .config.prowgen file for slack reporting of results being auto-created with make updates
  update cron

### CODE REVIEW

**Comment by vi-patel** [comment]
/pj-rehearse periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.18-lp-interop-jws-interop-aws-fips

**Comment by vi-patel** [comment]
/pj-rehearse periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.18-lp-interop-jws-interop-aws-fips

**Review by dfrazzette — APPROVED** [review]
/lgtm

**Pull request merged**
