### PR TITLE
FIO: Bump the pullspec

### PR DESCRIPTION
**Pull request by jhrozek**
Needed for a clean upgrade run.

### CODE REVIEW

**Comment by jhrozek** [comment]
/pj-rehearse pull-ci-openshift-file-integrity-operator-master-e2e-aws
the bundle and bundle upgrade are probably going to fail and we'd need to override them but I would expect the general AWS test to pass..

**Comment by rhmdnd** [comment]
Looks like the aws-e2e test failed on DNS issues (which I presume to be unrelated).

**Comment by rhmdnd** [comment]
/pj-rehearse pull-ci-openshift-file-integrity-operator-master-e2e-aws

**Comment by rhmdnd** [comment]
/pj-rehearse pull-ci-openshift-file-integrity-operator-master-e2e-aws

**Comment by rhmdnd** [comment]
Got a clean aws e2e run with a recheck, so the failures must be transient (which we should investigate).

**Review by Vincent056 — APPROVED** [review]

**Pull request merged**
