### PR TITLE
Update openstack-operator config and disable cert validation

### PR DESCRIPTION
**Pull request by stuggi**

### CODE REVIEW

**Comment by stuggi** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-tempest

**Comment by stuggi** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-nova-operator-main-nova-operator-build-deploy-tempest

**Comment by stuggi** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-tempest pull-ci-openstack-k8s-operators-nova-operator-main-nova-operator-build-deploy-tempest

**Comment by stuggi** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-tempest

**Comment by stuggi** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-tempest

**Comment by stuggi** [comment]
`  * could not run steps: step openstack-operator-build-deploy-tempest failed: failed to wait for the created cluster claim to become ready: timed out waiting for the condition `

/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-tempest

**Comment by stuggi** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-tempest

**Comment by stuggi** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-tempest

**Comment by stuggi** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-tempest

**Comment by stuggi** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-tempest pull-ci-openstack-k8s-operators-nova-operator-main-nova-operator-build-deploy-tempest

**Review by viroel — APPROVED** [review]

**Comment by viroel** [comment]
/pj-rehearse ack

tempest.conf looks correct with the ssl disabled[1]:
`disable_ssl_certificate_validation = true`

[1] https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/44033/rehearse-44033-pull-ci-openstack-k8s-operators-nova-operator-main-nova-operator-build-deploy-tempest/1711347789327241216/artifacts/nova-operator-build-deploy-tempest/openstack-k8s-operators-tempest/artifacts/tempest.conf

**Pull request merged**
