### PR TITLE
publish es6 images for 4.5

### PR DESCRIPTION
**Pull request by jcantrill**

### CODE REVIEW

**Comment by jcantrill** [comment]
@openshift/openshift-team-developer-productivity-platform anything else required in order to merge this?

**Comment by smarterclayton** [comment]
I need details about why you are renaming these, and what happens to the old images.  Are you removing elasticsearch5?  Have you already deleted ART builds for the removed images?  Or is this a rename within a single repo?

**Comment by jcantrill** [comment]
> I need details about why you are renaming these, and what happens to the old images. Are you removing elasticsearch5? 

ES5 will be removed in 4.5+

> Have you already deleted ART builds for the removed images?
I have a pending request to resolve ART but given 4.5 is early it has some bits to reconcile first 

> Or is this a rename within a single repo?
It was suggested to me by @sosiouxme in the interest of getting away from this dance we may wish to go back to single elasticsearch repo and possibly introduce a 'next' repo for the cases where we require support of multiple streams in a GA/TP scenario.  I like this idea to avoid ahving to bump and maintain images and repos by number

**Comment by smarterclayton** [comment]
If you are removing elasticsearch5, link to the PRs (if any) where you will be changing `image-references` from `logging-elasticsearch5` to `logging-elasticsearch6`.

**Comment by jcantrill** [comment]
> If you are removing elasticsearch5, link to the PRs (if any) where you will be changing `image-references` from `logging-elasticsearch5` to `logging-elasticsearch6`.

All PRs?  ART prs?

**Comment by smarterclayton** [comment]
PRs to your repositories to change your old names to new names in `image-references`

**Comment by jcantrill** [comment]
> PRs to your repositories to change your old names to new names in `image-references`

https://github.com/openshift/cluster-logging-operator/pull/373/files#diff-22ad291dc6727021c771a33cacdd7273

**Comment by smarterclayton** [comment]
Once you link the manifest PR here I'll validate the mirroring spec and then start the process to ensure the switch.  you can get this merged faster if you don't rename the existing ones (unless you already removed CI and ART builds) but just add new copies.

**Comment by jcantrill** [comment]
> Once you link the manifest PR here I'll validate the mirroring spec and then start the process to ensure the switch. 

https://github.com/openshift/cluster-logging-operator/pull/379

> you can get this merged faster if you don't rename the existing ones (unless you already removed CI and 
Modified CI here: https://github.com/openshift/release/pull/7239

ART builds) but just add new copies.

Working on art here https://issues.redhat.com/browse/LOG-630

**Comment by smarterclayton** [comment]
/lgtm

I will manually handle the cleanup once these stop being consumed

**Pull request merged**
