### PR TITLE
[knative] Add jobs for kn-event for releases `1.3` - `1.6`

### PR DESCRIPTION
**Pull request by cardil**
Adding missing jobs for releases:

- `release-1.3`
- `release-1.4`
- `release-1.5`
- `release-1.6`

### CODE REVIEW

**Comment by rhuss** [comment]
Technically the CI runs look correct. I have some questions though, not all related to this specific PR:

* When are CI jobs are removed again ? I see jobs going back until 0.24 in other repos
*  Who is responsible for updating those jobs ? Should this be part of a some release process ? Asking, because I see varying support for different comments ? (e.g. eventing-kafka only goes up to 1.1, most missing still 1.6)
* Which components are part of that config ? What's about the core components like serving & eventing ?

**Comment by dsimansk** [comment]
> Technically the CI runs look correct. I have some questions though, not all related to this specific PR:
> 
>     * When are CI jobs are removed again ? I see jobs going back until 0.24 in other repos

We don't have any clean up policy for that. Nor has OpenShift CI any auto clean-up. In general CI is not executed until PR triggers it. It shouldn't cost any resources etc. However, ideally we would want something like supported z-streams CI only. 

>     * Who is responsible for updating those jobs ? Should this be part of a some release process ? Asking, because I see varying support for different comments ? (e.g. eventing-kafka only goes up to 1.1, most missing still 1.6)

It's being maintained per group. Eventing-kafka was probably added around 1.1 version, therefore it's first version.

>     * Which components are part of that config ? What's about the core components like serving & eventing ?

The scope is limited to `kn-plugin-event` midstream repo. Other components have their respective configs in either `openshift` or `openshift-knative/` dirs.

**Comment by rhuss** [comment]
> t's being maintained per group. Eventing-kafka was probably added around 1.1 version, therefore it's first version.

I mean 1.1. is the *latest* version in https://github.com/openshift/release/tree/master/ci-operator/jobs/openshift-knative/eventing-kafka (actually it's 1.2, but you get the point)

**Comment by rhuss** [comment]
> Other components have their respective configs in either `openshift` or `openshift-knative/` dirs.

Are there plans to harmonize this ?

**Comment by cardil** [comment]
> Are there plans to harmonize this ?

There was a proposal to migrate all the repos to openshift-knative. We should do it at some point.

But, it's not related to this PR

**Pull request merged**
