### PR TITLE
[PERFSCALE-2503]: Add ROSA 4.15 Controlplane tests

### PR DESCRIPTION
**Pull request by krishvoor**
This PR introduces, control-plane tests for 
classic ROSA 4.15 for Medium and small scale nodes.

### CODE REVIEW

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-perfscale-rosa-multiaz-control-plane-24nodes-periodic

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-perfscale-rosa-multiaz-control-plane-24nodes-periodic

**Comment by krishvoor** [comment]
Here are observations on the failed periodic jobs:
1) Failed due to `Timed out while waiting for the htpasswd idp to be ready for` [login](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/43862/rehearse-43862-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-perfscale-rosa-multiaz-control-plane-24nodes-periodic/1708047265228132352/artifacts/perfscale-rosa-multiaz-control-plane-24nodes-periodic/rosa-conf-idp-htpasswd/build-log.txt)
2) Failed due to `Timed out while waiting for the htpasswd idp to be ready for` [login](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/43862/rehearse-43862-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-perfscale-rosa-multiaz-control-plane-24nodes-periodic/1707959188019220480)

cc: @svetsa-rh @paigerube14 @jtaleric

**Comment by svetsa-rh** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-perfscale-rosa-multiaz-control-plane-120nodes-periodic periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-perfscale-rosa-multiaz-node-density-cni-24nodes-periodic periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-perfscale-rosa-multiaz-control-plane-24nodes-periodic periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-perfscale-rosa-multiaz-node-density-heavy-24nodes-periodic

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-perfscale-rosa-multiaz-node-density-cni-24nodes-periodic

**Comment by paigerube14** [comment]
CC: @svetsa-rh

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-perfscale-rosa-multiaz-node-density-cni-24nodes-periodic

**Comment by krishvoor** [comment]
The [error](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/43862/rehearse-43862-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-perfscale-rosa-multiaz-node-density-cni-24nodes-periodic/1714192880647540736#1:build-log.txt%3A110) is not related to PR at all, interesting logs state this:

```
ERR: No billing account associated. Go to https://docs.openshift.com/rosa/rosa_architecture/rosa-understanding.html to learn how to associate your billing account. You must associate a billing account to continue.
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:84","func":"k8s.io/test-infra/prow/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2023-10-17T08:17:23Z"}
error: failed to execute wrapped command: exit status 1 
INFO[2023-10-17T08:17:23Z] Step perfscale-rosa-multiaz-node-density-cni-24nodes-periodic-rosa-cluster-provision failed after 8s. 
INFO[2023-10-17T08:17:23Z] Step phase pre failed after 32s. 
```

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-perfscale-rosa-multiaz-control-plane-24nodes-periodic

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-perfscale-rosa-multiaz-control-plane-24nodes-periodic

**Comment by krishvoor** [comment]
The previous error was due to:
```
rosa create cluster -y --sts --mode auto --cluster-name ci-rosa-s-80bc --region us-west-2 --version 4.15.0-0.nightly- 
         
ERR: No billing account associated. 
Go to https://docs.openshift.com/rosa/rosa_architecture/rosa-understanding.html to learn how to associate your billing account. You must associate a billing account to continue.

{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:84","func":"k8s.io/test-infra/prow/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2023-10-17T08:17:23Z"}
error: failed to execute wrapped command: exit status 1 
```

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-nightly-x86-perfscale-rosa-multiaz-control-plane-24nodes-periodic

**Review by jtaleric — APPROVED** [review]
lgtm - @svetsa-rh ?

**Pull request merged**
