### PR TITLE
Jv/init collector config

### PR DESCRIPTION
**Pull request by JoukoVirtanen**

### CODE REVIEW

**Comment by gavin-stackrox** [comment]
I'd recommend to take the prow/02_config from stackrox unless you want the extra branch protection from openshift/prow/tide.

Similarily use https://github.com/openshift/release/blob/7f6f430f9b600c7c8a2ff7cb417ea9ff86a8615e/ci-operator/config/stackrox/stackrox/stackrox-stackrox-master.yaml as a template for collector. `promotion` and `releases` stanzas are not something you need right now.

**Comment by JoukoVirtanen** [comment]
> I'd recommend to take the prow/02_config from stackrox unless you want the extra branch protection from openshift/prow/tide.
> 
> Similarily use https://github.com/openshift/release/blob/7f6f430f9b600c7c8a2ff7cb417ea9ff86a8615e/ci-operator/config/stackrox/stackrox/stackrox-stackrox-master.yaml as a template for collector. `promotion` and `releases` stanzas are not something you need right now.

I took prow/02_config from stackrox/stackrox and changed the repo to collector. I also changed the OWNERS file. I removed the promotion and release sections from stackrox-collector-master.yaml.

**Comment by gavin-stackrox** [comment]
it looks like the rehearse lint job has failed.
you might want to add a `/hold` label to your openshift/release PRs when they are a WIP. Otherwise they will merge as soon as someone approves them.

**Comment by JoukoVirtanen** [comment]
> it looks like the rehearse lint job has failed. you might want to add a `/hold` label to your openshift/release PRs when they are a WIP. Otherwise they will merge as soon as someone approves them.

I will fix the lint job. It was't even my goal to get the lint job working initially. I just wanted to get the ball rolling by getting a config for collector in openshift. I was planning a separate PR to get lint working. However, it seemed that "make new-repo" wouldn't work without adding a test, so I added lint.

**Comment by gavin-stackrox** [comment]
> > it looks like the rehearse lint job has failed. you might want to add a `/hold` label to your openshift/release PRs when they are a WIP. Otherwise they will merge as soon as someone approves them.
> 
> I will fix the lint job. It was't even my goal to get the lint job working initially. I just wanted to get the ball rolling by getting a config for collector in openshift. I was planning a separate PR to get lint working. However, it seemed that "make new-repo" wouldn't work without adding a test, so I added lint.

got it.

**Review by gavin-stackrox — APPROVED** [review]
👍

**Comment by gavin-stackrox** [comment]
tip: one way to avoid `ci/prow` failures is to always run `make update` after a change and commit the results (works for me).

**Review by robbycochran — APPROVED** [review]

**Pull request merged**
