### PR TITLE
add operator installation periodic build

### PR DESCRIPTION
**Pull request by osherdp**
/hold
/cc @osherdp

### CODE REVIEW

**Comment by lranjbar** [comment]
We should the built ci-index image for the assisted installer operator. Similar to how OO_INDEX is used in the [optional-operators-subscribe](https://github.com/openshift/release/blob/master/ci-operator/step-registry/optional-operators/subscribe/optional-operators-subscribe-commands.sh#L110) step.

**Comment by osherdp** [comment]
> We should the built ci-index image for the assisted installer operator. Similar to how OO_INDEX is used in the [optional-operators-subscribe](https://github.com/openshift/release/blob/master/ci-operator/step-registry/optional-operators/subscribe/optional-operators-subscribe-commands.sh#L110) step.

of course, next PR

**Review by YuviGold — APPROVED** [review]
LGTM

**Pull request merged**
