### PR TITLE
Switch to gcp-opendatahub cluster profile

### PR DESCRIPTION
**Pull request by riprasad**

### CODE REVIEW

**Comment by atheo89** [comment]
Thank you Rishab for opening this PR! That's a great update. 
I guess should we apply that also to the rest of the configs (2023a & 2023b) ?

**Comment by riprasad** [comment]
@atheo89 Rest of the configs (2023a & 2023b) doesn't make use of cluster profiles. I've identified a list of jobs that uses cluster profiles. Once the test succeeds I'll make appropriate changes to all of them.

**Comment by riprasad** [comment]
Additionally, I observed that these end-to-end (e2e) tests are pre-submit tasks, implying they execute for each PR. Would it be logical to shift to running nightly e2e test jobs instead of triggering them for every PR? The execution of these e2e test jobs involves creating a new OpenShift cluster and consumes substantial resources and time. Given our current scrutiny for escalating cloud costs, this adjustment may be worth considering.

**Comment by atheo89** [comment]
Great, thank you for checking this. In regards the e2e tests i opened an issue to track it:  https://github.com/opendatahub-io/notebooks/issues/351

**Review by atheo89 — APPROVED** [review]
/lgtm

**Pull request merged**
