### PR TITLE
Stop additional prow jobs running in 18.0-fr1 branch

### PR DESCRIPTION
**Pull request by bshewale**

### CODE REVIEW

**Comment by lewisdenny** [comment]
@bshewale So what we need to do is sync all the changes from the main branch to the fr1 branch job config. 

To see exactly what needs to be changed you can run a diff:
`diff -u 59234/ci-operator/jobs/openstack-k8s-operators/neutron-operator/openstack-k8s-operators-neutron-operator-18.0-fr1-presubmits.yaml 59234/ci-operator/jobs/openstack-k8s-operators/neutron-operator/openstack-k8s-operators-neutron-operator-main-presubmits.yaml`

This is what I will use to review this patch, obviously you can ignore the branch and name differences but you can see in the below diff that we should also update `skip_if_only_changed` as well. 

Other operators will need to be updated as well, not just Neutron. 

```diff
--- 59234/ci-operator/jobs/openstack-k8s-operators/neutron-operator/openstack-k8s-operators-neutron-operator-18.0-fr1-presubmits.yaml	2024-11-27 12:23:22
+++ 59234/ci-operator/jobs/openstack-k8s-operators/neutron-operator/openstack-k8s-operators-neutron-operator-main-presubmits.yaml	2024-11-27 12:23:10
@@ -3,16 +3,17 @@
   - agent: kubernetes
     always_run: false
     branches:
-    - ^18\.0-fr1$
-    - ^18\.0-fr1-
+    - ^main$
+    - ^main-
     cluster: build09
     context: ci/prow/functional
     decorate: true
     labels:
       ci.openshift.io/generator: prowgen
       pj-rehearse.openshift.io/can-be-rehearsed: "true"
-    name: pull-ci-openstack-k8s-operators-neutron-operator-18.0-fr1-functional
+    name: pull-ci-openstack-k8s-operators-neutron-operator-main-functional
     rerun_command: /test functional
+    skip_if_only_changed: ^(renovate.json|.*\.md|test/kuttl/.*|OWNERS.*|LICENSE.*)$
     spec:
       containers:
       - args:
@@ -56,16 +57,17 @@
   - agent: kubernetes
     always_run: false
     branches:
-    - ^18\.0-fr1$
-    - ^18\.0-fr1-
+    - ^main$
+    - ^main-
     cluster: build09
     context: ci/prow/images
     decorate: true
     labels:
       ci.openshift.io/generator: prowgen
       pj-rehearse.openshift.io/can-be-rehearsed: "true"
-    name: pull-ci-openstack-k8s-operators-neutron-operator-18.0-fr1-images
+    name: pull-ci-openstack-k8s-operators-neutron-operator-main-images
     rerun_command: /test images
+    skip_if_only_changed: ^renovate.json|^README.md
     spec:
       containers:
       - args:
@@ -109,15 +111,15 @@
   - agent: kubernetes
     always_run: false
     branches:
-    - ^18\.0-fr1$
-    - ^18\.0-fr1-
+    - ^main$
+    - ^main-
     cluster: build09
     context: ci/prow/neutron-operator-build-deploy
     decorate: true
     labels:
       ci.openshift.io/generator: prowgen
       pj-rehearse.openshift.io/can-be-rehearsed: "true"
-    name: pull-ci-openstack-k8s-operators-neutron-operator-18.0-fr1-neutron-operator-build-deploy
+    name: pull-ci-openstack-k8s-operators-neutron-operator-main-neutron-operator-build-deploy
     optional: true
     rerun_command: /test neutron-operator-build-deploy
     spec:
@@ -177,16 +179,17 @@
   - agent: kubernetes
     always_run: false
     branches:
-    - ^18\.0-fr1$
-    - ^18\.0-fr1-
+    - ^main$
+    - ^main-
     cluster: build09
     context: ci/prow/neutron-operator-build-deploy-kuttl
     decorate: true
     labels:
       ci.openshift.io/generator: prowgen
       pj-rehearse.openshift.io/can-be-rehearsed: "true"
-    name: pull-ci-openstack-k8s-operators-neutron-operator-18.0-fr1-neutron-operator-build-deploy-kuttl
+    name: pull-ci-openstack-k8s-operators-neutron-operator-main-neutron-operator-build-deploy-kuttl
     rerun_command: /test neutron-operator-build-deploy-kuttl
+    skip_if_only_changed: ^(renovate.json|.*\.md|test/functional/.*|OWNERS.*|LICENSE.*)$
     spec:
       containers:
       - args:
@@ -244,15 +247,15 @@
   - agent: kubernetes
     always_run: false
     branches:
-    - ^18\.0-fr1$
-    - ^18\.0-fr1-
+    - ^main$
+    - ^main-
     cluster: build09
     context: ci/prow/neutron-operator-build-deploy-tempest
     decorate: true
     labels:
       ci.openshift.io/generator: prowgen
       pj-rehearse.openshift.io/can-be-rehearsed: "true"
-    name: pull-ci-openstack-k8s-operators-neutron-operator-18.0-fr1-neutron-operator-build-deploy-tempest
+    name: pull-ci-openstack-k8s-operators-neutron-operator-main-neutron-operator-build-deploy-tempest
     optional: true
     rerun_command: /test neutron-operator-build-deploy-tempest
     spec:
@@ -312,16 +315,17 @@
   - agent: kubernetes
     always_run: false
     branches:
-    - ^18\.0-fr1$
-    - ^18\.0-fr1-
+    - ^main$
+    - ^main-
     cluster: build09
     context: ci/prow/precommit-check
     decorate: true
     labels:
       ci.openshift.io/generator: prowgen
       pj-rehearse.openshift.io/can-be-rehearsed: "true"
-    name: pull-ci-openstack-k8s-operators-neutron-operator-18.0-fr1-precommit-check
+    name: pull-ci-openstack-k8s-operators-neutron-operator-main-precommit-check
     rerun_command: /test precommit-check
+    skip_if_only_changed: ^renovate.json|^README.md
     spec:
       containers:
       - args:
```

**Review by lewisdenny — CHANGES_REQUESTED** [review]
^

**Review by karelyatin — COMMENTED** [review]
/lgtm

**Review by karelyatin — APPROVED** [review]

**Pull request merged**
