### PR TITLE
update ocs-operator install sequence

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Moved ocs-operator to be installed in the end for ocs-operator jobs

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
@iamniting please review.

**Comment by Nikhil-Ladha** [comment]
@iamniting can you please re-trigger the test?

**Comment by iamniting** [comment]
/pj-rehearse pull-ci-red-hat-storage-ocs-operator-main-ocs-operator-bundle-e2e-aws

**Review by iamniting — APPROVED** [review]

**Pull request merged**
