### PR TITLE
Bug 1874751: OKD: build marketplace package from Dockerfile.okd

### PR DESCRIPTION
**Pull request by vrutkovs**
This builds a slightly different image for OKD so that it could be 
installed without a pull secret. OKD image would be promoted to `origin` 
namespace instead of `ocp`. Additional test are added to ensure OKD 
passes minimal OLM tests. All the added tests are optional and can be skipped with `/skip` if necessary.

See also https://github.com/operator-framework/operator-marketplace/pull/332.

/cc @ecordell @kevinrizza

### CODE REVIEW

**Comment by vrutkovs** [comment]
:facepalm: Dockerfile.okd needs fixing, but it would be convenient with those tests added. WDYT?

**Comment by vrutkovs** [comment]
Tests are failing due to https://bugzilla.redhat.com/show_bug.cgi?id=1879873, so merging this would add a test to it

**Comment by njhale** [comment]
aforementioned patch -- https://github.com/openshift/release/pull/11529#issuecomment-694112565 -- is merged and verified.

/retest

**Comment by vrutkovs** [comment]
-operators test is failing (filed https://bugzilla.redhat.com/show_bug.cgi?id=1881713 to fix that), others are passing

**Pull request merged**
