### PR TITLE
enable logging operator jobs on post release branch

### PR DESCRIPTION
**Pull request by jcantrill**
Enable jobs on logging operator branches

### CODE REVIEW

**Comment by petr-muller** [comment]
Branch name is a part of the ci-operator config file names, so if those files are called `openshift-cluster-logging-operator-master.yaml`, prowgen expects to generate jobs for a `master` branch. If the intention is to only have jobs for `master-post-release` branch, then the existing ci-operator configs need to be renamed (and prowgen run afterwards). But this would mean less jobs would gate master which is IMHO undesirable. IMHO, what we should do here is to copy ci-op configs for the new branch and generate a new set of jobs for it.

**Comment by stevekuznetsov** [comment]
We prefer to copy the files -- do this by copying your `ci-operator` configuration file and regenerating.

**Comment by stevekuznetsov** [comment]
As soon as jobs will drift, or you will want to have differences, that will be necessary. The "cost" of more configuration files we felt like was not high enough to warrant just-in-time-forking

**Pull request merged**
