### PR TITLE
[LPTOCPCI-207] Fixing MTR Interop Scenario Operator Install

### PR DESCRIPTION
**Pull request by calebevans**

### CODE REVIEW

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-windup-windup-ui-tests-v1.0-mtr-ocp4.13-lp-interop-mtr-interop-aws

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-windup-windup-ui-tests-v1.0-mtr-ocp4.13-lp-interop-mtr-interop-aws

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-windup-windup-ui-tests-v1.0-mtr-ocp4.13-lp-interop-mtr-interop-aws

**Review by madunn — APPROVED** [review]
/lgtm

**Pull request merged**
