### PR TITLE
AWS Local Zone Phase 1 support

### PR DESCRIPTION
**Pull request by yunjiang29**
* Phase 0: Create local zone and network MTU manifests.
* Phase 1: Set Local Zone subnet and edge pool in `install-config.yaml`.

## 4.12
| Profile  | Phase-X | IP |
| ------------- | ------------- | ------------- |
| `cucushift-installer-rehearse-aws-ipi-network-mtu-localzone(-sdn)`  | Phase-0  | Public  |
| `cucushift-installer-rehearse-aws-ipi-disconnected-private-network-mtu-localzone`  | Phase-0  | Private  |

## 4.13+
| Profile  | Phase-X | IP |
| ------------- | ------------- | ------------- |
| `cucushift-installer-rehearse-aws-ipi-localzone(-sdn)`  | Phase-1  | Public  |
| `cucushift-installer-rehearse-aws-ipi-disconnected-private-network-mtu-localzone`  | Phase-0  | Private  |

Local Zone enhancements: https://github.com/openshift/enhancements/pull/1232

### CODE REVIEW

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-ipi-network-mtu-localzone-p2-f14

**Comment by yunjiang29** [comment]
all jobs for local zone are:
```
periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-4.12-upgrade-from-stable-4.12-aws-ipi-network-mtu-localzone-p2-f14
periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-4.12-upgrade-from-stable-4.12-aws-ipi-network-mtu-localzone-sdn-p2-f14
periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-ipi-network-mtu-localzone-p2-f14
periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-ipi-network-mtu-localzone-p3-f28-destructive
periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-ipi-network-mtu-localzone-sdn-p2-f14
periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-ipi-network-mtu-localzone-sdn-p3-f28-destructive
periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-stable-aws-ipi-network-mtu-localzone-p2-f14
periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-stable-aws-ipi-network-mtu-localzone-p3-f28-destructive
periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-stable-aws-ipi-network-mtu-localzone-sdn-p2-f14
periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-stable-aws-ipi-network-mtu-localzone-sdn-p3-f28-destructive
periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-ec-4.13-aws-ipi-localzone-p2-f14
periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-ec-4.13-aws-ipi-localzone-sdn-p2-f14
periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-stable-4.12-aws-ipi-network-mtu-localzone-p2-f14
periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-stable-4.12-aws-ipi-network-mtu-localzone-sdn-p2-f14
periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-localzone-p2-f14
periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-localzone-p3-f28-destructive
periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-localzone-sdn-p2-f14
periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-localzone-sdn-p3-f28-destructive
```

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-ipi-network-mtu-localzone-p2-f14

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-localzone-p2-f14

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-localzone-p2-f14

**Comment by mtulio** [comment]
> Assign public IP to the edge nodes and remove all disconnect scenarios (workflows are preserved)

@yunjiang29 do you see value in keep testing the disconnected flow? Or can we get stuck on the parent zone pinning situation?

**Comment by yunjiang29** [comment]
> > Assign public IP to the edge nodes and remove all disconnect scenarios (workflows are preserved)
> 
> @yunjiang29 do you see value in keep testing the disconnected flow? 

@mtulio the main reason I removed disconnected profiles is private IP is not supported on edge node, and for a disconnected cluster, it looks like assigning a public IP to a node is not reasonable, at least I don't see such use cases, generally, the network in disconnected cluster is restricted to VPC inside only.
I don't mind that keep these disconnected profiles as a normal or experimental test, but some questions need to be considered, a) is upgrade supported? b)what if Phase-0 is obsoleted, will it be supported in Phase-1/2? 

> Or can we get stuck on the parent zone pinning situation?

I think I do not quite understand this, can you explain more about this? thanks

**Comment by mtulio** [comment]
> > > Assign public IP to the edge nodes and remove all disconnect scenarios (workflows are preserved)
> > 
> > 
> > @yunjiang29 do you see value in keep testing the disconnected flow?
> 
> @mtulio the main reason I removed disconnected profiles is private IP is not supported on edge node, and for a disconnected cluster, it looks like assigning a public IP to a node is not reasonable, at least I don't see such use cases, generally, the network in disconnected cluster is restricted to VPC inside only. I don't mind that keep these disconnected profiles as a normal or experimental test, but some questions need to be considered, a) is upgrade supported? b)what if Phase-0 is obsoleted, will it be supported in Phase-1/2?
> 
> > Or can we get stuck on the parent zone pinning situation?
> 
> I think I do not quite understand this, can you explain more about this? thanks

> a) is upgrade supported?

Not covered on the feature which will automate the installer creation, but as a regular BYO VPC in disconnected environments, CU would be able to create subnets and machine set manifests (phase-0). We don't have requirements for disconnected right now, but having the tests is a good start - as the tests already exist, I was thinking why not keep it testing and observing it. The [PublicIP](https://github.com/openshift/release/pull/37022/files#diff-264b1753b683416c605e85feafca5f9a21f1070ab3320800f2d80e88a2f243f6R69) could be used as an env var targeting the public/private scenario. :)

>  b)what if Phase-0 is obsoleted, will it be supported in Phase-1/2?

Will not be obsolete. Phase-0 is BYO VPC with local zone subnets without automation on installer for those zones. If the user would like to installer generate the machineset manifests, they don't need to supply the install config with local zone subnets, then create it manually. I think if we cover this scenario only with disconnected, seems to be fine.

wdyt?

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-ipi-disconnected-network-mtu-localzone-p2-f14

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-stable-4.12-aws-ipi-network-mtu-localzone-p2-f14

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-localzone-p2-f14

**Comment by mtulio** [comment]
> Is my understanding right?

Perfect! That's it!

**Comment by yunjiang29** [comment]
## Test result

### aws-ipi-localzone

job: https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/37022/rehearse-37022-periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-ipi-disconnected-network-mtu-localzone-p2-f14/1633847520960450560

<details><summary>Output of machineset, machine, node</summary>
<p>

```
NAMESPACE               NAME                                               DESIRED   CURRENT   READY   AVAILABLE   AGE
openshift-machine-api   ci-op-pl07tlcj-198ca-n84f4-edge-us-east-1-iah-1a   1         1         1       1           9h
openshift-machine-api   ci-op-pl07tlcj-198ca-n84f4-worker-us-east-1a       1         1         1       1           9h
openshift-machine-api   ci-op-pl07tlcj-198ca-n84f4-worker-us-east-1b       1         1         1       1           9h
openshift-machine-api   ci-op-pl07tlcj-198ca-n84f4-worker-us-east-1c       1         1         1       1           9h

NAMESPACE               NAME                                                     PHASE     TYPE          REGION      ZONE               AGE   NODE                          PROVIDERID                                    STATE
openshift-machine-api   ci-op-pl07tlcj-198ca-n84f4-edge-us-east-1-iah-1a-8zwjr   Running   c5d.2xlarge   us-east-1   us-east-1-iah-1a   8h    ip-10-0-135-29.ec2.internal   aws:///us-east-1-iah-1a/i-0dc2c9bc5bfaedf5f   running
openshift-machine-api   ci-op-pl07tlcj-198ca-n84f4-master-0                      Running   m6i.xlarge    us-east-1   us-east-1a         9h    ip-10-0-61-227.ec2.internal   aws:///us-east-1a/i-0a6cd3b059c4af535         running
openshift-machine-api   ci-op-pl07tlcj-198ca-n84f4-master-1                      Running   m6i.xlarge    us-east-1   us-east-1b         9h    ip-10-0-79-67.ec2.internal    aws:///us-east-1b/i-0ddf7fd3ccd469083         running
openshift-machine-api   ci-op-pl07tlcj-198ca-n84f4-master-2                      Running   m6i.xlarge    us-east-1   us-east-1c         9h    ip-10-0-83-90.ec2.internal    aws:///us-east-1c/i-0c657023b986b9fca         running
openshift-machine-api   ci-op-pl07tlcj-198ca-n84f4-worker-us-east-1a-5hz6z       Running   m5.xlarge     us-east-1   us-east-1a         8h    ip-10-0-48-209.ec2.internal   aws:///us-east-1a/i-067df10683d303f06         running
openshift-machine-api   ci-op-pl07tlcj-198ca-n84f4-worker-us-east-1b-mg28d       Running   m5.xlarge     us-east-1   us-east-1b         8h    ip-10-0-73-205.ec2.internal   aws:///us-east-1b/i-042429bebb44b09c1         running
openshift-machine-api   ci-op-pl07tlcj-198ca-n84f4-worker-us-east-1c-m4c6k       Running   m5.xlarge     us-east-1   us-east-1c         8h    ip-10-0-91-154.ec2.internal   aws:///us-east-1c/i-0c21326bacff88f9f         running


NAME                          STATUS   ROLES                  AGE   VERSION           INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                                                        KERNEL-VERSION                 CONTAINER-RUNTIME
ip-10-0-135-29.ec2.internal   Ready    edge,worker,wscan      8h    v1.26.2+bc894ae   10.0.135.29   72.41.0.154   Red Hat Enterprise Linux CoreOS 413.86.202303071307-0 (Ootpa)   4.18.0-372.46.1.el8_6.x86_64   cri-o://1.26.1-10.rhaos4.13.gitcb86088.el8
ip-10-0-48-209.ec2.internal   Ready    worker,wscan           8h    v1.26.2+bc894ae   10.0.48.209   <none>        Red Hat Enterprise Linux CoreOS 413.86.202303071307-0 (Ootpa)   4.18.0-372.46.1.el8_6.x86_64   cri-o://1.26.1-10.rhaos4.13.gitcb86088.el8
ip-10-0-61-227.ec2.internal   Ready    control-plane,master   8h    v1.26.2+bc894ae   10.0.61.227   <none>        Red Hat Enterprise Linux CoreOS 413.86.202303071307-0 (Ootpa)   4.18.0-372.46.1.el8_6.x86_64   cri-o://1.26.1-10.rhaos4.13.gitcb86088.el8
ip-10-0-73-205.ec2.internal   Ready    worker,wscan           8h    v1.26.2+bc894ae   10.0.73.205   <none>        Red Hat Enterprise Linux CoreOS 413.86.202303071307-0 (Ootpa)   4.18.0-372.46.1.el8_6.x86_64   cri-o://1.26.1-10.rhaos4.13.gitcb86088.el8
ip-10-0-79-67.ec2.internal    Ready    control-plane,master   8h    v1.26.2+bc894ae   10.0.79.67    <none>        Red Hat Enterprise Linux CoreOS 413.86.202303071307-0 (Ootpa)   4.18.0-372.46.1.el8_6.x86_64   cri-o://1.26.1-10.rhaos4.13.gitcb86088.el8
ip-10-0-83-90.ec2.internal    Ready    control-plane,master   8h    v1.26.2+bc894ae   10.0.83.90    <none>        Red Hat Enterprise Linux CoreOS 413.86.202303071307-0 (Ootpa)   4.18.0-372.46.1.el8_6.x86_64   cri-o://1.26.1-10.rhaos4.13.gitcb86088.el8
ip-10-0-91-154.ec2.internal   Ready    worker,wscan           8h    v1.26.2+bc894ae   10.0.91.154   <none>        Red Hat Enterprise Linux CoreOS 413.86.202303071307-0 (Ootpa)   4.18.0-372.46.1.el8_6.x86_64   cri-o://1.26.1-10.rhaos4.13.gitcb86088.el8
```

</p>
</details>


### aws-ipi-network-mtu-localzone

job: https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/37022/rehearse-37022-periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-stable-4.12-aws-ipi-network-mtu-localzone-p2-f14/1633846360337813504

<details><summary>Output of machineset, machine, node</summary>
<p>

```
NAMESPACE               NAME                                               DESIRED   CURRENT   READY   AVAILABLE   AGE
openshift-machine-api   ci-op-5hbm6vdp-cb80d-2pkhr-edge-us-east-1-iah-1a   1         1         1       1           4h6m
openshift-machine-api   ci-op-5hbm6vdp-cb80d-2pkhr-worker-us-east-1a       1         1         1       1           4h6m
openshift-machine-api   ci-op-5hbm6vdp-cb80d-2pkhr-worker-us-east-1b       1         1         1       1           4h6m
openshift-machine-api   ci-op-5hbm6vdp-cb80d-2pkhr-worker-us-east-1c       1         1         1       1           4h6m


NAME                          STATUS   ROLES                  AGE     VERSION           INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                                                        KERNEL-VERSION                 CONTAINER-RUNTIME
ip-10-0-132-47.ec2.internal   Ready    edge,worker            3h49m   v1.26.2+bc894ae   10.0.132.47   72.41.0.101   Red Hat Enterprise Linux CoreOS 413.86.202303071307-0 (Ootpa)   4.18.0-372.46.1.el8_6.x86_64   cri-o://1.26.1-10.rhaos4.13.gitcb86088.el8
ip-10-0-50-68.ec2.internal    Ready    control-plane,master   4h6m    v1.26.2+bc894ae   10.0.50.68    <none>        Red Hat Enterprise Linux CoreOS 413.86.202303071307-0 (Ootpa)   4.18.0-372.46.1.el8_6.x86_64   cri-o://1.26.1-10.rhaos4.13.gitcb86088.el8
ip-10-0-54-56.ec2.internal    Ready    worker                 3h50m   v1.26.2+bc894ae   10.0.54.56    <none>        Red Hat Enterprise Linux CoreOS 413.86.202303071307-0 (Ootpa)   4.18.0-372.46.1.el8_6.x86_64   cri-o://1.26.1-10.rhaos4.13.gitcb86088.el8
ip-10-0-65-156.ec2.internal   Ready    control-plane,master   4h6m    v1.26.2+bc894ae   10.0.65.156   <none>        Red Hat Enterprise Linux CoreOS 413.86.202303071307-0 (Ootpa)   4.18.0-372.46.1.el8_6.x86_64   cri-o://1.26.1-10.rhaos4.13.gitcb86088.el8
ip-10-0-77-251.ec2.internal   Ready    worker                 3h50m   v1.26.2+bc894ae   10.0.77.251   <none>        Red Hat Enterprise Linux CoreOS 413.86.202303071307-0 (Ootpa)   4.18.0-372.46.1.el8_6.x86_64   cri-o://1.26.1-10.rhaos4.13.gitcb86088.el8
ip-10-0-84-34.ec2.internal    Ready    control-plane,master   4h6m    v1.26.2+bc894ae   10.0.84.34    <none>        Red Hat Enterprise Linux CoreOS 413.86.202303071307-0 (Ootpa)   4.18.0-372.46.1.el8_6.x86_64   cri-o://1.26.1-10.rhaos4.13.gitcb86088.el8
ip-10-0-90-180.ec2.internal   Ready    worker                 3h50m   v1.26.2+bc894ae   10.0.90.180   <none>        Red Hat Enterprise Linux CoreOS 413.86.202303071307-0 (Ootpa)   4.18.0-372.46.1.el8_6.x86_64   cri-o://1.26.1-10.rhaos4.13.gitcb86088.el8

NAMESPACE               NAME                                                     PHASE     TYPE          REGION      ZONE               AGE    NODE                          PROVIDERID                                    STATE
openshift-machine-api   ci-op-5hbm6vdp-cb80d-2pkhr-edge-us-east-1-iah-1a-wpgph   Running   c5d.2xlarge   us-east-1   us-east-1-iah-1a   4h3m   ip-10-0-132-47.ec2.internal   aws:///us-east-1-iah-1a/i-00e7ea0d75ec9c46a   running
openshift-machine-api   ci-op-5hbm6vdp-cb80d-2pkhr-master-0                      Running   m6i.xlarge    us-east-1   us-east-1a         4h6m   ip-10-0-50-68.ec2.internal    aws:///us-east-1a/i-03cb5aa4f29de97b4         running
openshift-machine-api   ci-op-5hbm6vdp-cb80d-2pkhr-master-1                      Running   m6i.xlarge    us-east-1   us-east-1b         4h6m   ip-10-0-65-156.ec2.internal   aws:///us-east-1b/i-092a241a13bf15114         running
openshift-machine-api   ci-op-5hbm6vdp-cb80d-2pkhr-master-2                      Running   m6i.xlarge    us-east-1   us-east-1c         4h6m   ip-10-0-84-34.ec2.internal    aws:///us-east-1c/i-0d310df95b388458f         running
openshift-machine-api   ci-op-5hbm6vdp-cb80d-2pkhr-worker-us-east-1a-2lwnr       Running   m5.xlarge     us-east-1   us-east-1a         4h3m   ip-10-0-54-56.ec2.internal    aws:///us-east-1a/i-0dcb4aa7b88d167e1         running
openshift-machine-api   ci-op-5hbm6vdp-cb80d-2pkhr-worker-us-east-1b-klxwj       Running   m5.xlarge     us-east-1   us-east-1b         4h3m   ip-10-0-77-251.ec2.internal   aws:///us-east-1b/i-017f8e5c73187c4f1         running
openshift-machine-api   ci-op-5hbm6vdp-cb80d-2pkhr-worker-us-east-1c-4pzbb       Running   m5.xlarge     us-east-1   us-east-1c         4h3m   ip-10-0-90-180.ec2.internal   aws:///us-east-1c/i-026286e2a2c3e0bc5         running
```

</p>
</details>



### aws-ipi-disconnected-network-mtu-localzone

job: https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/37022/rehearse-37022-periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-ipi-disconnected-network-mtu-localzone-p2-f14/1633847520960450560

<details><summary>Output of machineset, machine, node</summary>
<p>

```
NAMESPACE               NAME                                               DESIRED   CURRENT   READY   AVAILABLE   AGE
openshift-machine-api   ci-op-jcnzzf11-d5129-x7vdz-edge-us-east-1-iah-1a   1         1         1       1           7h49m
openshift-machine-api   ci-op-jcnzzf11-d5129-x7vdz-worker-us-east-1a       1         1         1       1           7h49m
openshift-machine-api   ci-op-jcnzzf11-d5129-x7vdz-worker-us-east-1b       1         1         1       1           7h49m
openshift-machine-api   ci-op-jcnzzf11-d5129-x7vdz-worker-us-east-1c       1         1         1       1           7h49m

NAMESPACE               NAME                                                     PHASE     TYPE          REGION      ZONE               AGE     NODE                          PROVIDERID                                    STATE
openshift-machine-api   ci-op-jcnzzf11-d5129-x7vdz-edge-us-east-1-iah-1a-8jv4j   Running   c5d.2xlarge   us-east-1   us-east-1-iah-1a   7h44m   ip-10-0-133-82.ec2.internal   aws:///us-east-1-iah-1a/i-0a1b12b9253cd1430   running
openshift-machine-api   ci-op-jcnzzf11-d5129-x7vdz-master-0                      Running   m6i.xlarge    us-east-1   us-east-1a         7h49m   ip-10-0-57-102.ec2.internal   aws:///us-east-1a/i-0c56fd21a77584b54         running
openshift-machine-api   ci-op-jcnzzf11-d5129-x7vdz-master-1                      Running   m6i.xlarge    us-east-1   us-east-1b         7h49m   ip-10-0-74-155.ec2.internal   aws:///us-east-1b/i-013e36d502a8c209f         running
openshift-machine-api   ci-op-jcnzzf11-d5129-x7vdz-master-2                      Running   m6i.xlarge    us-east-1   us-east-1c         7h49m   ip-10-0-91-228.ec2.internal   aws:///us-east-1c/i-06f94872966c458a1         running
openshift-machine-api   ci-op-jcnzzf11-d5129-x7vdz-worker-us-east-1a-9vt9x       Running   m5.xlarge     us-east-1   us-east-1a         7h44m   ip-10-0-49-203.ec2.internal   aws:///us-east-1a/i-0772443af34e74c05         running
openshift-machine-api   ci-op-jcnzzf11-d5129-x7vdz-worker-us-east-1b-6dmxh       Running   m5.xlarge     us-east-1   us-east-1b         7h44m   ip-10-0-71-56.ec2.internal    aws:///us-east-1b/i-0357b1010a05225e2         running
openshift-machine-api   ci-op-jcnzzf11-d5129-x7vdz-worker-us-east-1c-t8brc       Running   m5.xlarge     us-east-1   us-east-1c         7h44m   ip-10-0-86-195.ec2.internal   aws:///us-east-1c/i-0ee8b2251d8c2b2f0         running

NAME                          STATUS                     ROLES                  AGE     VERSION           INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                                                        KERNEL-VERSION                 CONTAINER-RUNTIME
ip-10-0-133-82.ec2.internal   Ready,SchedulingDisabled   edge,worker            7h32m   v1.25.4+18eadca   10.0.133.82   <none>        Red Hat Enterprise Linux CoreOS 412.86.202303011010-0 (Ootpa)   4.18.0-372.46.1.el8_6.x86_64   cri-o://1.25.2-10.rhaos4.12.git0a083f9.el8
ip-10-0-49-203.ec2.internal   Ready                      worker                 7h39m   v1.25.4+18eadca   10.0.49.203   <none>        Red Hat Enterprise Linux CoreOS 412.86.202303011010-0 (Ootpa)   4.18.0-372.46.1.el8_6.x86_64   cri-o://1.25.2-10.rhaos4.12.git0a083f9.el8
ip-10-0-57-102.ec2.internal   Ready                      control-plane,master   7h48m   v1.25.4+18eadca   10.0.57.102   <none>        Red Hat Enterprise Linux CoreOS 412.86.202303011010-0 (Ootpa)   4.18.0-372.46.1.el8_6.x86_64   cri-o://1.25.2-10.rhaos4.12.git0a083f9.el8
ip-10-0-71-56.ec2.internal    Ready                      worker                 7h36m   v1.25.4+18eadca   10.0.71.56    <none>        Red Hat Enterprise Linux CoreOS 412.86.202303011010-0 (Ootpa)   4.18.0-372.46.1.el8_6.x86_64   cri-o://1.25.2-10.rhaos4.12.git0a083f9.el8
ip-10-0-74-155.ec2.internal   Ready                      control-plane,master   7h48m   v1.25.4+18eadca   10.0.74.155   <none>        Red Hat Enterprise Linux CoreOS 412.86.202303011010-0 (Ootpa)   4.18.0-372.46.1.el8_6.x86_64   cri-o://1.25.2-10.rhaos4.12.git0a083f9.el8
ip-10-0-86-195.ec2.internal   Ready                      worker                 7h39m   v1.25.4+18eadca   10.0.86.195   <none>        Red Hat Enterprise Linux CoreOS 412.86.202303011010-0 (Ootpa)   4.18.0-372.46.1.el8_6.x86_64   cri-o://1.25.2-10.rhaos4.12.git0a083f9.el8
ip-10-0-91-228.ec2.internal   Ready                      control-plane,master   7h48m   v1.25.4+18eadca   10.0.91.228   <none>        Red Hat Enterprise Linux CoreOS 412.86.202303011010-0 (Ootpa)   4.18.0-372.46.1.el8_6.x86_64   cri-o://1.25.2-10.rhaos4.12.git0a083f9.el8
```

</p>
</details>

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-ipi-disconnected-network-mtu-localzone-p2-f14

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-ipi-disconnected-network-mtu-localzone-p2-f14

**Comment by yunjiang29** [comment]
@jianlinliu when you get a chance please review this PR, thanks

**Comment by jianlinliu** [comment]
cc @liangxia to review.

**Pull request merged**
