### PR TITLE
Revert "Move folder services/squid-egress-proxy to app.ci"

### PR DESCRIPTION
**Pull request by hongkailiu**
This reverts commit 2014e299a8d992df1004e16886b58238fe668236.

Follow up https://github.com/openshift/release/pull/14630#issuecomment-754973635

Another reason: Not used in any jobs. As @petr-muller reminded me, we should let the manifests rot with api.ci. (I forgot this while dealing with the PR).

```
grep -irn squid-proxy .              
./services/squid-egress-proxy/build.yaml:7:    name: squid-proxy
./services/squid-egress-proxy/build.yaml:12:    name: squid-proxy
./services/squid-egress-proxy/build.yaml:20:        name: squid-proxy:latest
```

/cc @alvaroaleman

### CODE REVIEW

**Comment by petr-muller** [comment]
@hongkailiu could we pwn it entirely? is *anything* using this?

**Review by petr-muller — APPROVED** [review]
/hold

This will need pwning from app.ci

**Comment by hongkailiu** [comment]
> @hongkailiu could we pwn it entirely? is _anything_ using this?

@petr-muller 

I do not find any reference of that image in the release repo.

@ewolinetz @danehans

Do you still need this imagestream?

**Comment by hongkailiu** [comment]
merging the PR for now to revert the status.

I will `oc --context app.ci delete bc -n ci squid-proxy` after merge.
No need to clean up the `stream` since it is current sync between app.ci and api.ci.

/hold cancel

**Comment by hongkailiu** [comment]
```
oc --context app.ci delete bc -n ci squid-proxy
buildconfig.build.openshift.io "squid-proxy" deleted
```

**Pull request merged**
