### PR TITLE
openstack: get external network ID in floating IPs provision

### PR DESCRIPTION
**Pull request by EmilienM**
In some jobs that uses floating IPs (e.g. Hypershift), we need the
external network ID. This patch moves the code that wrote the external
network ID in SHARED_DIR from resourcenames to provision-fips because in resourcenames step, the clouds.yaml wasn't ready yet.
We can't really swap resourcenames and the clouds.yaml step because they have dependencies to each others.

An easy fix is to write the external network ID in the floating ips provision step.

### CODE REVIEW

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.16-e2e-openstack-ovn-serial

**Comment by EmilienM** [comment]
Oops command not found error... Will look on Monday 
/hold

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-main-cleanup-vh-mecha-central pull-ci-openshift-hypershift-main-e2e-openstack

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.16-e2e-openstack-ovn-serial

**Comment by pierreprinetti** [comment]
Please add to the PR description the reason why you are making these changes. That will help the reviewer (and your future self) get more context quickly.

Have you considered adding the resource IDs to the resourcenames step instead of the names, if that’s what we need?

**Comment by EmilienM** [comment]
> Please add to the PR description the reason why you are making these changes. That will help the reviewer (and your future self) get more context quickly.

Yeah I did that too quickly last night. I'll continue tomorrow. 

> Have you considered adding the resource IDs to the resourcenames step instead of the names, if that’s what we need?

We need the external network ID for HyperShift tests. Maysa added it to the resourcenames step but this failed because we didn't load clouds.yaml there.

**Comment by EmilienM** [comment]
jobs failed because `CLUSTER_NAME`.
I also need to write a better commit message.

@pierreprinetti if you have a better idea (less invasive), feel free to push.

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.16-e2e-openstack-ovn-serial periodic-ci-shiftstack-ci-main-cleanup-vh-mecha-central pull-ci-openshift-hypershift-main-e2e-openstack

**Comment by EmilienM** [comment]
/close
This was taken over by https://github.com/openshift/release/pull/55182
Thanks @pierreprinetti :pray:

**Pull request closed without merging**
