### PR TITLE
PowerVS: Add CAPI testing for PowerVS

### PR DESCRIPTION
**Pull request by hamzy**
This will add /test altinfra-e2e-powervs-capi-ovn

### CODE REVIEW

**Comment by r4f4** [comment]
/pj-rehearse pull-ci-openshift-installer-master-altinfra-e2e-powervs-capi-ovn

**Comment by hamzy** [comment]
/pj-rehearse pull-ci-openshift-installer-master-altinfra-e2e-powervs-capi-ovn

**Comment by hamzy** [comment]
/pj-rehearse pull-ci-openshift-installer-master-altinfra-e2e-powervs-capi-ovn

**Comment by hamzy** [comment]
/pj-rehearse pull-ci-openshift-installer-master-altinfra-e2e-powervs-capi-ovn

**Comment by hamzy** [comment]
/pj-rehearse pull-ci-openshift-installer-master-altinfra-e2e-powervs-capi-ovn

**Comment by hamzy** [comment]
/pj-rehearse pull-ci-openshift-installer-master-altinfra-e2e-powervs-capi-ovn

**Comment by hamzy** [comment]
/pj-rehearse pull-ci-openshift-installer-master-altinfra-e2e-powervs-capi-ovn

**Comment by hamzy** [comment]
/pj-rehearse pull-ci-openshift-installer-master-altinfra-e2e-powervs-capi-ovn

**Review by r4f4 — COMMENTED** [review]
/approve

**Pull request merged**
