### PR TITLE
call failure exporter in 4.10 e2e test

### PR DESCRIPTION
**Pull request by weshayutin**
Related PR.
https://github.com/konveyor/pelorus/compare/master...weshayutin:failure_ex_ci?expand=1

### CODE REVIEW

**Comment by weshayutin** [comment]
whoops.. vault was incorrect.  corrected it

**Comment by weshayutin** [comment]
HA.. here's the problem :) 

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/29693/rehearse-29693-pull-ci-konveyor-pelorus-master-4.10-e2e-openshift/1541079389314224128/artifacts/e2e-openshift/gather-extra/artifacts/pods/pelorus_committime-exporter-1-build_git-clone.log

Cloning "https://github.com/konveyor/pelorus.git" ...
error: fatal: couldn't find remote ref refs/pull/29693/head

**Comment by weshayutin** [comment]
@mpryc woot

**Comment by mpryc** [comment]
/lgtm 

Nice !

I even see the token being hidden:

```
secretsync-vault-source-path
++ cat /var/run/konveyor/pelorus/pelorus-github/TOKEN
+ export TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
+ TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

**Pull request merged**
