### PR TITLE
WIP telco: Run the aws telco job

### PR DESCRIPTION
**Pull request by sshnaidm**

### CODE REVIEW

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-master-e2e-aws-ci-tests

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-master-e2e-aws-ci-tests

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-master-e2e-aws-ci-tests

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-master-e2e-aws-ci-tests

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-master-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-release-4.13-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-release-4.14-e2e-aws-ci-tests

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-master-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-release-4.13-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-release-4.14-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-release-4.12-e2e-aws-ci-tests

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-master-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-release-4.13-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-release-4.14-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-release-4.12-e2e-aws-ci-tests

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-master-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-release-4.13-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-release-4.14-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-release-4.12-e2e-aws-ci-tests

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.14-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-release-4.14-e2e-aws-ran-profile pull-ci-openshift-kni-cnf-features-deploy-release-4.15-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-master-e2e-aws-ci-tests

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.14-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-release-4.14-e2e-aws-ran-profile pull-ci-openshift-kni-cnf-features-deploy-release-4.15-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-master-e2e-aws-ci-tests

**Comment by SchSeba** [comment]
Hi @sshnaidm I think we can close this one right? we already add support for this no?

**Pull request closed without merging**
