### PR TITLE
Clean up deprecated tool: populate-owners

### PR DESCRIPTION
**Pull request by hongkailiu**
It is deprecated by https://github.com/openshift/ci-tools/tree/master/cmd/autoowners

/cc @openshift/openshift-team-developer-productivity-test-platform

### CODE REVIEW

**Comment by hongkailiu** [comment]
@stevekuznetsov 
Not directly related to this PR, i did not find the script for image bumping ...

And thanks to @petr-muller 
```
$ git show 4b03af61053eead8bbd18ca42f5819a95f008a5c
commit 4b03af61053eead8bbd18ca42f5819a95f008a5c
Author: Petr Muller <afri@afri.cz>
Date:   Thu Sep 12 12:03:36 2019 +0200

    remove bumg-prow-images.sh, we now use autobumper
```

**Comment by petr-muller** [comment]
I don't think `hack/validate-owners.sh` should be removed, that still protects us from directories not having `OWNERS` when target repos do not have it.

**Comment by hongkailiu** [comment]
> I don't think `hack/validate-owners.sh` should be removed, that still protects us from directories not having `OWNERS` when target repos do not have it.

Overkilled. Recovered.

**Pull request merged**
