### PR TITLE
zonal do not support upgrade from TP to GA

### PR DESCRIPTION
**Pull request by sgaoshang**
zones upgrade is included in [PR](https://github.com/openshift/release/pull/35175/files), since 4.12 zones is TP and 4.13 it's GA, installation will [fail](https://reportportal-openshift.apps.ocp-c1.prod.psi.redhat.com/ui/#prow/launches/709/334246?launchesParams=page.page%3D2), so remove it

### CODE REVIEW

**Comment by sgaoshang** [comment]
@jianlinliu @liangxia pls help to review it, thanks.

**Comment by jianlinliu** [comment]
cc @liangxia

**Pull request merged**
