### PR TITLE
odo zstream expansion to ocp 4.17

### PR DESCRIPTION
**Pull request by smpsgill**

### CODE REVIEW

**Comment by Simranpal** [comment]
/pj-rehearse pull-ci-redhat-developer-odo-main-odo-ocp4.17-lp-interop-images periodic-ci-redhat-developer-odo-main-odo-ocp4.17-lp-interop-odo-scenario-ibmcloud periodic-ci-redhat-developer-odo-main-odo-ocp4.16-lp-interop-odo-scenario-ibmcloud

**Comment by Simranpal** [comment]
/pj-rehearse periodic-ci-redhat-developer-odo-main-odo-ocp4.16-lp-interop-odo-scenario-ibmcloud

**Review by dfrazzette — APPROVED** [review]

**Pull request merged**
