### PR TITLE
Move swift and telemetry prow jobs over from 4.14 to 4.15 Hive cluster

### PR DESCRIPTION
**Pull request by bshewale**

### CODE REVIEW

**Comment by lewisdenny** [comment]
#/pj-rehearse pull-ci-openstack-k8s-operators-swift-operator-main-swift-operator-build-deploy-kuttl

**Comment by lewisdenny** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-swift-operator-main-swift-operator-build-deploy-kuttl

**Comment by viroel** [comment]
lgtm

**Pull request merged**
