### PR TITLE
openstack: Move step-registry jobs to Vexxhost

### PR DESCRIPTION
**Pull request by pierreprinetti**
Maximise chances of successful builds while step-registry jobs are being
worked on.

### CODE REVIEW

**Comment by pierreprinetti** [comment]
Implements OSASINFRA-2419

**Review by mandre — COMMENTED** [review]
/lgtm

**Comment by mandre** [comment]
/hold cancel

Although the job is still failing on 4.7 due to the missing cinder client (fixed with https://github.com/openshift/origin/pull/26166) it should be good enough to move it to vexxhost. 
The job on master is successful as shown with https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/18455/rehearse-18455-pull-ci-openshift-cloud-provider-openstack-release-4.8-e2e-openstack-ipi/1394745096804503552

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
