### PR TITLE
TRY 4.12 hybrid Cluster

### PR DESCRIPTION
**Pull request by Sandeepyadav93**

### CODE REVIEW

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-install_yamls-main-install-yamls-deploy

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-install_yamls-main-install-yamls-deploy

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-install_yamls-main-install-yamls-deploy

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-cinder-operator-main-cinder-operator-build-deploy-kuttl

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-cinder-operator-main-cinder-operator-build-deploy-kuttl

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-cinder-operator-main-cinder-operator-build-deploy-tempest

**Pull request closed without merging**
