### PR TITLE
hypershift/openstack: use `hcp` instead of `hypershift` CLI

### PR DESCRIPTION
**Pull request by EmilienM**
Switch our CI job to use the product CLI used by our customers.

### CODE REVIEW

**Comment by EmilienM** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-openstack-conformance

**Comment by MaysaMacedo** [comment]
@EmilienM Is the job unrelated to this PR?

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.18-periodics-e2e-openstack-conformance

**Comment by EmilienM** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-openstack-conformance

**Review by mandre — COMMENTED** [review]
/lgtm

The [hypershift job](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/58644/rehearse-58644-pull-ci-openshift-hypershift-main-e2e-openstack-conformance/1856157195750608896) is successful ([logs from hcp command](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/58644/rehearse-58644-pull-ci-openshift-hypershift-main-e2e-openstack-conformance/1856157195750608896/artifacts/e2e-openstack-conformance/hypershift-openstack-create-hostedcluster/build-log.txt)).

@EmilienM I'll let you ack the pj-rehearse if you're good with the CI results.

**Pull request merged**
