### PR TITLE
ControlplaneMachineSet operator e2e for ARM64

### PR DESCRIPTION
**Pull request by deepsm007**
Fixing arm64 ControlplaneMachineSet operator e2e

Follow-up from https://github.com/openshift/release/pull/33678 

cc @JoelSpeed

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Looks like the ARM clusters still aren't bootstrapping

**Comment by damdo** [comment]
The PR I merged touched the same files so I think we'll need to rebase/resolve, before attempting to pass reharse.
Sorry for causing extra work @deepsm007

**Comment by deepsm007** [comment]
Arm uses different base domain causing multiple failures.

**Comment by JoelSpeed** [comment]
/pj-rehearse periodic-ci-openshift-cluster-control-plane-machine-set-operator-main-e2e-aws-arm-periodic

**Pull request merged**
