### PR TITLE
Adding supplemental cerberus image

### PR DESCRIPTION
**Pull request by paigerube14**
Missing latest cerberus image in redhat-chaos images. Need to use in https://github.com/openshift/release/pull/39697

### CODE REVIEW

**Comment by bear-redhat** [comment]
You need a new line at the end of the file to avoid messy `diff` :-)

**Comment by paigerube14** [comment]
@bear-redhat I added a new line locally but not seeing it really pop up in the git compare? Do you see?

**Comment by paigerube14** [comment]
@bear-redhat @psalajova can you PTAL this is blocking further testing with this image

**Pull request merged**
