### PR TITLE
Add Reto to image mirror knative/OWNERS

### PR DESCRIPTION
**Pull request by nak3**
As per title.

/cc @skonto @matzew @mgencur @ReToCode

### CODE REVIEW

**Comment by nak3** [comment]
Could you merge this @skonto @matzew @mgencur ?

**Comment by ReToCode** [comment]
Gentle ping @skonto @matzew @mgencur

/remove-lifecycle rotten

**Comment by ReToCode** [comment]
Gentle ping @skonto @matzew @mgencur

/remove-lifecycle stale

/retest

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
