### PR TITLE
mount e2e template jobs dashboard to grafana

### PR DESCRIPTION
**Pull request by droslean**
/cc @hongkailiu

### CODE REVIEW

**Comment by hongkailiu** [comment]
also need to define the volume in the `volumes` section.
Man ... what time is it for you? Lost your sleep?

**Comment by bbguimaraes** [comment]
/lgtm

`readOnly` is the default, so it could be removed, but couldn't the mounts under `/etc` and `/grafana-dashboard-definitions` be read-only?

**Pull request merged**
