### PR TITLE
We do not need patch manager approval for cherry picks for Cincinnati

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
As these are not part of OpenShift release payload and we build these in CPaaS and
released separately

Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
CC @sdodson @vrutkovs

**Comment by vrutkovs** [comment]
/hold

I think that removes all restrictions. Instead we want to be moved to a different group without `cherry-pick-approved` like https://github.com/LalatenduMohanty/release/blob/remove_cherrypick_approvals_for_Cincy_repos/core-services/prow/02_config/_config.yaml#L2420-L2432

**Comment by LalatenduMohanty** [comment]
@vrutkovs It is already part of that group check https://github.com/openshift/release/blob/master/core-services/prow/02_config/_config.yaml#L1610-L1611

Also you might want to check the PR which introduced it https://github.com/openshift/cincinnati/pull/314

**Comment by vrutkovs** [comment]
Ah, right.

/hold cancel

Not sure why `prow-config` is failing - perhaps `make update` is needed?

**Comment by LalatenduMohanty** [comment]
> Not sure why `prow-config` is failing - perhaps `make update` is needed?

Re-ran `make prow-config` to generate the prow configs and added the change in a separate commit.

**Comment by sdodson** [comment]
/approve
I don't think I can apply the label via the bot but I can assert that this is the policy we wish to use.

**Comment by sdodson** [comment]
@petr-muller ptal

**Pull request merged**
