### PR TITLE
update camgi version to 0.9.0

### PR DESCRIPTION
**Pull request by elmiko**
this brings in new features such as displays for ClusterOperators, CCMs, and the CCM operator.

### CODE REVIEW

**Comment by elmiko** [comment]
@vrutkovs wonder if you might take a look at this, should i run one of the pj-rehearse jobs to get an output from the tool?

**Comment by elmiko** [comment]
i'd like to get a confirmation, let's hope this works like i think :joy: 

/pj-rehearse pull-ci-openshift-run-once-duration-override-main-e2e-aws-operator

**Comment by elmiko** [comment]
looks like i've got an issue to work out with the binary build

**Comment by elmiko** [comment]
/pj-rehearse pull-ci-openshift-run-once-duration-override-main-e2e-aws-operator

**Comment by elmiko** [comment]
looks like it's working now, happy for any review @vrutkovs

**Review by vrutkovs — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
