### PR TITLE
OCPVE-260: Add 4.12 release for lvm operator 

### PR DESCRIPTION
**Pull request by suleymanakbas91**
Signed-off-by: Suleyman Akbas <sakbas@redhat.com>

### CODE REVIEW

**Review by nbalacha — APPROVED** [review]

**Comment by suleymanakbas91** [comment]
/pj-rehearse pull-ci-openshift-lvm-operator-main-lvm-operator-bundle-e2e-aws
/pj-rehearse pull-ci-openshift-lvm-operator-release-4.12-lvm-operator-bundle-e2e-aws

**Comment by suleymanakbas91** [comment]
/pj-rehearse pull-ci-openshift-lvm-operator-release-4.12-lvm-operator-bundle-e2e-aws

**Comment by suleymanakbas91** [comment]
/pj-rehearse pull-ci-openshift-lvm-operator-main-lvm-operator-bundle-e2e-aws

**Comment by suleymanakbas91** [comment]
/pj-rehearse pull-ci-openshift-lvm-operator-main-lvm-operator-bundle-e2e-aws

**Pull request merged**
