### PR TITLE
Remove unmaintained okd-scos jobs config

### PR DESCRIPTION
**Pull request by elfosardo**
The okd-scos jobs are unmaintaiened and broken since 4.16 Removing them to save some CI resources, they need to be overridden anyway.

### CODE REVIEW

**Comment by sdodson** [comment]
I would think we'd try to fix them in 4.16 and 4.17? Though not clear to me when OKD 4.16 goes EOL, I'd assume not for a few more months.

**Comment by elfosardo** [comment]
> I would think we'd try to fix them in 4.16 and 4.17? Though not clear to me when OKD 4.16 goes EOL, I'd assume not for a few more months.

@sdodson probably missing context here, I left you a message on slack, let's continue the discussion there

**Comment by sdodson** [comment]
/lgtm
/approve
We'll reintroduce these as release blocking jobs on latest supported OKD build once the dust has settled.

**Comment by ausil** [comment]
Please revert this immediately

**Comment by sdodson** [comment]
https://github.com/openshift/release/pull/55886

**Pull request merged**
