### PR TITLE
TRT-1292: add conformance to gcp-ovn-upgrade

### PR DESCRIPTION
**Pull request by neisw**
As a follow up from [TRT-1292](https://issues.redhat.com//browse/TRT-1292) we want to add conformance tests to the gcp-ovn-upgrade

### CODE REVIEW

**Comment by neisw** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-release-4.15-e2e-gcp-ovn-upgrade

**Comment by neisw** [comment]
/assign @dcbw 

Dan, following up from [TRT-1292](https://issues.redhat.com//browse/TRT-1292) we wanted to enable the conformance tests as well for the gcp-ovn-upgrade presubmit if that is agreeable.

**Comment by dcbw** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-release-4.15-e2e-gcp-ovn-upgrade
/pj-rehearse pull-ci-openshift-cluster-network-operator-release-4.16-e2e-gcp-ovn-upgrade

**Comment by neisw** [comment]
@dcbw, let me rebase this and re run the rehearsals

**Comment by neisw** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-release-4.16-e2e-gcp-ovn-upgrade

**Comment by neisw** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-release-4.16-e2e-gcp-ovn-upgrade

**Comment by neisw** [comment]
@dcbw, looks like the 4.16 issues got worked out.  we good to go on this?

**Pull request merged**
