### PR TITLE
ROX-20455: Update stackrox image to 3.61

### PR DESCRIPTION
**Pull request by janisz**
refs:
- https://github.com/stackrox/rox-ci-image/releases/tag/0.3.61
- https://github.com/stackrox/stackrox/pull/8412
- https://github.com/openshift/release/pull/45091

### CODE REVIEW

**Comment by janisz** [comment]
> failed to ensure imagestreamtags in cluster build04: failed waiting for imagestreamtag stackrox/apollo-ci:stackrox-test-0.3.61 to appear: timed out waiting for the condition

@gavin-stackrox do I remeber correctly that first we should update the core-services/image-mirroring/stackrox/mapping_supplemental_ci_images_stackrox_rox_ci_image and wait for images to appear and then we can actually use them?

**Comment by janisz** [comment]
@gavin-stackrox Created https://github.com/openshift/release/pull/45091

**Comment by gavin-stackrox** [comment]
@janisz note: it will take ~ 1 hour for the rox-ci-image to mirror. Are you sure you want this backported? Can you be selective with /pj-rehearse so it does not consume all available clusters?

**Comment by janisz** [comment]
> Are you sure you want this backported?

Yes, I think we should backport it as it's an minor Go version update from 1.20.4 to 1.20.10 `(released 2023-10-10) includes a security fix to the net/http package.`

**Comment by janisz** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-release-x.y-gke-qa-e2e-tests

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-gke-nongroovy-e2e-tests pull-ci-stackrox-stackrox-master-shell-unit-tests pull-ci-stackrox-stackrox-release-x.y-ocp-4-10-operator-e2e-tests pull-ci-stackrox-stackrox-release-4.2-ocp-4-13-qa-e2e-tests  pull-ci-stackrox-stackrox-release-4.1-ocp-4-12-ui-e2e-tests

**Comment by janisz** [comment]
@gavin-stackrox PTAL (I've rebased on master)

**Pull request merged**
