### PR TITLE
add CI configurations for merge automation of app-sre/aws-resource-exporter

### PR DESCRIPTION
**Pull request by maorfr**
we'd like to add automated merges based on an OWNERS file in a new repository: app-sre/aws-resource-exporter

follows up on https://github.com/app-sre/aws-resource-exporter/pull/57

similar to #13392

### CODE REVIEW

**Comment by maorfr** [comment]
i'm not sure if there are additional steps to this process. happy to comply!

**Comment by maorfr** [comment]
i've installed the OpenShift CI GitHub app and added the bots as collaborators according to https://docs.ci.openshift.org/docs/how-tos/onboarding-a-new-component/#granting-robots-privileges-and-installing-the-github-app

waiting for up to 4 hours for the invitations to be accepted

**Comment by smg247** [comment]
@maorfr, you should get someone from your team to review your configurations. @bear-redhat and I are not the proper folks to do that.

**Pull request closed without merging**
