### PR TITLE
adding envar to control nodeUpgradeType to hypershift-aws-create-chain for e2e-hypershift-pao

### PR DESCRIPTION
**Pull request by Patryk-Stefanski**
adding envar to control nodeUpgradeType to hypershift-aws-create-chain for e2e-hypershift-pao

### CODE REVIEW

**Comment by Tal-or** [comment]
/pj-rehearse pull-ci-openshift-cluster-node-tuning-operator-master-e2e-hypershift-pao

**Comment by Tal-or** [comment]
/pj-rehearse pull-ci-openshift-cluster-node-tuning-operator-master-e2e-hypershift-pao

**Comment by sjenning** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-conformance

**Comment by Tal-or** [comment]
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/58736/rehearse-58736-pull-ci-openshift-cluster-node-tuning-operator-master-e2e-hypershift-pao/1856369917624848384/artifacts/e2e-hypershift-pao/dump/artifacts/namespaces/clusters/hypershift.openshift.io/nodepools/62c140dbfab13cd22b38-us-east-1a.yaml

```
upgradeType: InPlace
```

**Pull request merged**
