### PR TITLE
Bug 1948585: Add periodic for OVN using local gw mode

### PR DESCRIPTION
**Pull request by jluhrsen**
Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>

### CODE REVIEW

**Comment by jluhrsen** [comment]
/retitle Bug 1948585: Add periodic for OVN using local gw mode

**Comment by jluhrsen** [comment]
@trozet , so far so good with the non baremetal job (aws). [local](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/18322/rehearse-18322-periodic-ci-openshift-release-master-nightly-4.8-e2e-aws-ovn-local-gateway/1390407896562405376/artifacts/e2e-aws-ovn-local-gateway/gather-extra/artifacts/pods/openshift-ovn-kubernetes_ovnkube-master-9trng_ovnkube-master.log) is being used and the job [passed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/18322/rehearse-18322-periodic-ci-openshift-release-master-nightly-4.8-e2e-aws-ovn-local-gateway/1390407896562405376).

that work didn't apply to the baremetal job though. latest version of this PR is trying to get that figured out.
just fyi.

**Comment by trozet** [comment]
> @trozet , so far so good with the non baremetal job (aws). [local](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/18322/rehearse-18322-periodic-ci-openshift-release-master-nightly-4.8-e2e-aws-ovn-local-gateway/1390407896562405376/artifacts/e2e-aws-ovn-local-gateway/gather-extra/artifacts/pods/openshift-ovn-kubernetes_ovnkube-master-9trng_ovnkube-master.log) is being used and the job [passed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/18322/rehearse-18322-periodic-ci-openshift-release-master-nightly-4.8-e2e-aws-ovn-local-gateway/1390407896562405376).
> 
> that work didn't apply to the baremetal job though. latest version of this PR is trying to get that figured out.
> just fyi.

Thanks Jamo. FYI there was a bug in services with local gw mode that @astoycos fixed. I dont think it's downstream yet.

**Comment by stbenjam** [comment]
> > For metal-ipi, typically we add a flag to our development scripts https://github.com/openshift-metal3/dev-scripts, and then set the flag in CI. This would let a developer easily use local gateway mode as well. If we did it this way, then we'd avoid making our scripts even bigger in CI.
> 
> ok, I can try to do it that way. I remember quickly glancing through the dev scripts which is where I found that ASSESTS_EXTRA_FOLDER variable which led me to doing it this way.
> 
> @stbenjam, can you help me understand the best way I can test my changes to dev-scripts so I know what I end up with
> is actually working? With this PR in release and the rehearsal job hack, I can at least see that my changes are working in
> our jobs. I don't have access to any baremetal env and never used the dev-scripts project before.

You can make the changes you need to dev-scripts, have some flag like OVN_LOCAL_GW.  To test it, add a temporary second commit that swaps the default value to true and you can see what CI does.

**Comment by jluhrsen** [comment]
> > > For metal-ipi, typically we add a flag to our development scripts https://github.com/openshift-metal3/dev-scripts, and then set the flag in CI. This would let a developer easily use local gateway mode as well. If we did it this way, then we'd avoid making our scripts even bigger in CI.
> > 
> > 
> > ok, I can try to do it that way. I remember quickly glancing through the dev scripts which is where I found that ASSESTS_EXTRA_FOLDER variable which led me to doing it this way.
> > @stbenjam, can you help me understand the best way I can test my changes to dev-scripts so I know what I end up with
> > is actually working? With this PR in release and the rehearsal job hack, I can at least see that my changes are working in
> > our jobs. I don't have access to any baremetal env and never used the dev-scripts project before.
> 
> You can make the changes you need to dev-scripts, have some flag like OVN_LOCAL_GW. To test it, add a temporary second commit that swaps the default value to true and you can see what CI does.

👍🏻 

working on that [here](https://github.com/openshift-metal3/dev-scripts/pull/1238)

**Comment by jluhrsen** [comment]
@trozet this is ready.

these presubmits are never going to fully pass.

[the non-local job is using shared
](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/18322/rehearse-18322-pull-ci-openshift-ovn-kubernetes-release-4.9-e2e-azure-ovn/1392524497189343232/artifacts/e2e-azure-ovn/gather-extra/artifacts/pods/openshift-ovn-kubernetes_ovnkube-master-6p854_ovnkube-master.log )and [the local job is using local](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/18322/rehearse-18322-periodic-ci-openshift-release-master-nightly-4.8-e2e-aws-ovn-local-gateway/1392524499072585728/artifacts/e2e-aws-ovn-local-gateway/gather-extra/artifacts/pods/openshift-ovn-kubernetes_ovnkube-master-2hlsv_ovnkube-master.log)

**Pull request merged**
