### PR TITLE
PowerVS: Add hack for kube-controller-manager

### PR DESCRIPTION
**Pull request by hamzy**
Adding a temporary hack to try and restart the static update nodes for the version upgrades.

### CODE REVIEW

**Comment by hamzy** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-serial-ovn-ppc64le-powervs

**Comment by mkumatag** [comment]
Its always good to add a TODO mentioning about the reason for adding this hack with a bug mentioned faxing this issue in the product otherwise there is chance that these hacks will remain in the code forever..

**Comment by mjturek** [comment]
This has been added as a mitigation for https://bugzilla.redhat.com/show_bug.cgi?id=2053582

**Comment by mjturek** [comment]
> Its always good to add a TODO mentioning about the reason for adding this hack with a bug mentioned faxing this issue in the product otherwise there is chance that these hacks will remain in the code forever..

Good point, @hamzy could you submit a follow up with a TODO saying something to the effect of "Mitigation in place while https://bugzilla.redhat.com/show_bug.cgi?id=2053582 is under investigation"

**Pull request merged**
