### PR TITLE
[CVP-3056] Remove the support for OCP 4.9 & config/jobs for OCP 4.8

### PR DESCRIPTION
**Pull request by sonam1412**
This PR is created to remove the support on OCP 4.9 by cleaning up the prow jobs and configs as well as the cluster pools.

This PR also covers the left overs of OCP 4.8 (prow jobs & configs)

### CODE REVIEW

**Comment by sonam1412** [comment]
cc: @samvarankashyap @asergienk @nmars

**Comment by asergienk** [comment]
lgtm

**Pull request merged**
