### PR TITLE
LOG-1336: Run logging code by claiming OCP cluster for testing

### PR DESCRIPTION
**Pull request by jcantrill**
This PR
* Modifies logging projects to claim an OCP cluster for testing

https://issues.redhat.com/browse/LOG-1336

### CODE REVIEW

**Comment by alanconway** [comment]
/lgtm
:100:

**Comment by jcantrill** [comment]
Closing in favor of https://github.com/openshift/release/pull/18887 until resolution of https://issues.redhat.com/browse/DPTP-2255

**Pull request closed without merging**
