### PR TITLE
fix: remove ubi8 based tf and pytorch images built from main branch

### PR DESCRIPTION
**Pull request by harshad16**
fix: remove ubi8 based tf and pytorch images built from main branch

As we only build the ubi8 tf and pytorch images on 2023a branch, they would be maintained only there.

### CODE REVIEW

**Review by atheo89 — APPROVED** [review]
/lgtm

**Comment by atheo89** [comment]
Thanks Harshad, one small change request, we need to exclude them also from the e2e test job

/remove lgtm

**Comment by harshad16** [comment]
Thanks for the review

**Pull request merged**
