### PR TITLE
ComplianceAsCode: Add BSI profiles to e2e

### PR DESCRIPTION
**Pull request by yuumasato**
Upstream is working on Bundesamt für Sicherheit in der Informationstechnik (BSI) security compliance profiles for OCP4.
Let's enable testing on those profiles so that we keep watch on any issue with the profile.

### CODE REVIEW

**Comment by yuumasato** [comment]
CC @rhmdnd @Vincent056

**Review by rhmdnd — APPROVED** [review]
/lgtm

Are we going to add periodic testing for these profiles at some point?

**Comment by yuumasato** [comment]
> Are we going to add periodic testing for these profiles at some point?

@rhmdnd Yeah, we can add periodic testing when the profile gets to a more mature state.

**Pull request merged**
