### PR TITLE
Disable nightly testing of gpu-operator/master on 4.9 and report 4.8 on slack

### PR DESCRIPTION
**Pull request by kpouget**
* Nightly testing of 4.9 was introduced last night by commit 5b6fc1f8aec8575112c1738e8d5590d0a0d6350f, based on 4.8 configuration, but we don't want to test on 4.9 yet.

* Slack reporting for 4.8 / master wasn't configured (it should be manually added after the `job` file is generated ...)

### CODE REVIEW

**Comment by jmencak** [comment]
Don't fully understand the `report_template` for Slack reporting, but the changes look sane to me.

**Comment by kpouget** [comment]
> Don't fully understand the report_template for Slack reporting

me neither ;-) it's just a copy and paste of what we already have, which is the copy and paste from the documentation!

I wanted to modify it to add direct links to our test artifacts ... but it miserably failed (no nightly slack message, but no error to debut it: |)
but in the end nothing complicated, just `<url|text> ... *bold text* :emojis*` and GO template from the GO structure of the Prow Job (not to be confused with the YAML structure though)

**Comment by kpouget** [comment]
> @kpouget: The following test **failed**, say `/retest` to rerun all failed tests:
> Test name 	Commit 	Details 	Rerun command
> ci/prow/generated-config 	[fc50a47](https://github.com/openshift/release/commit/fc50a475b40b7054a29a91a00023f9290684dce4) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/17100/pull-ci-openshift-release-master-generated-config/1374637024803295232) 	`/test generated-config`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openshift&repo=release&pr=17100). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:kpouget).

regenerating the jobs, I forgot this step ...

**Comment by ArangoGutierrez** [comment]
@kpouget `generated-config` ?

**Comment by kpouget** [comment]
pushed, thanks for the reminder :)

**Comment by kpouget** [comment]
@ArangoGutierrez this one is good to go, the `e2e-master` failure is expected

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
