### PR TITLE
Update SDN to use go 1.13 on master and 4.4+

### PR DESCRIPTION
**Pull request by juanluisvaladas**

### CODE REVIEW

**Comment by juanluisvaladas** [comment]
The verify-deps fails because go 1.12 and go 1.13 produce different vendors when go mod vendor is executed. So a few branches having the vendor generated by an older version won't work.

I guess the way to fix this would be ignoring the verify-deps errors, and once the CI is set up to use go 1.13 make the changes in the relevant branches for openshift sdn.

**Comment by danwinship** [comment]
@juanluisvaladas so to clarify, we can't fix this in sdn before merging this, because it wouldn't pass the current `verify-deps`, so we wouldn't be able to merge the fix, but as soon as we merge this, we won't be able to merge anything else in sdn until we fix the deps, but we will still be able to do that, because if we push a PR to fix the deps that will then pass the new `verify-deps`. Right?

**Comment by juanluisvaladas** [comment]
Correct

**Pull request merged**
