### PR TITLE
shiftstack-ci: Run shellcheck on more scripts

### PR DESCRIPTION
**Pull request by pierreprinetti**
Run shellcheck on all scripts that currently have no shellcheck issues.

### CODE REVIEW

**Comment by pierreprinetti** [comment]
Changed the PR to list more scripts, dropped the use of GNU Make.
Depends on https://github.com/shiftstack/shiftstack-ci/pull/138

**Comment by mandre** [comment]
What was the issue with `make shellcheck`, why did you revert to listing all files?
I imagine we can close in favor of https://github.com/openshift/release/pull/21468 now.

**Comment by pierreprinetti** [comment]
/close
superseded by https://github.com/openshift/release/pull/21468

**Pull request closed without merging**
