### PR TITLE
Set filestore as default sc

### PR DESCRIPTION
**Pull request by chao007**
Update quay.io/openshift-qe-optional-operators/aosqe-index to correct version
Set the filestore.csi.storage.gke.io  as default sc provider

### CODE REVIEW

**Comment by chao007** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-multi-nightly-gcp-ipi-compact-filestore-csi-defaultsc-amd-f28-destructive

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-multi-nightly-gcp-ipi-compact-filestore-csi-arm-f14

**Comment by jianlinliu** [comment]
cc @liangxia to review.

**Pull request merged**
