### PR TITLE
Use OCP 4.11 instead of 4.10 for knative serving release-next

### PR DESCRIPTION
**Pull request by nak3**
As per title, this patch changes to use OCP 4.11 instead of 4.10 for knative serving release-next.

### CODE REVIEW

**Comment by mgencur** [comment]
@nak3 Overall, it looks good to me. There are a lot of failures in the run "411-tls-e2e-aws-ocp-411 but it's probably not related to the changes in this PR.
Also, I don't see any difference between the config files for `411-e2e-aws-ocp-411` and `411-tls-e2e-aws-ocp-411`:
https://github.com/openshift/release/blob/9621c34f5ccdb7db738835f703b169d2129d0abc/ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-next__411-tls.yaml
https://github.com/openshift/release/blob/9621c34f5ccdb7db738835f703b169d2129d0abc/ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-next__411.yaml
Am I missing something?

**Comment by nak3** [comment]
Yeah, `TestAutoscaleSustaining/aggregation-weighted-exponential ` sometimes started failing suddenly and it happened on the daily CI https://github.com/openshift/knative-serving/pull/1222 .

For `411-tls`, sorry for the confusion. It enables `internal-tls` on openshift/knative-serving repo when job name contains `tls` as:
https://github.com/openshift/knative-serving/blob/a42405d1c360f55d6ed95fb1a5e0ab40444cf58d/openshift/e2e-common.sh#L232-L238

I thought that we can drop the TLS job soon as we should run CI with `internal-tls` by default in a few release later but probably I should add a new target in `Makefile` and use it to solve the confusion. I will change it soon.

**Comment by nak3** [comment]
Added a target to call `make test-e2e-tls`. This PR will fail until https://github.com/openshift/knative-serving/pull/1224 was merged.

**Comment by mgencur** [comment]
Thanks! 
/lgtm
/hold
Hold for the tests. Feel free to unhold.

**Comment by mgencur** [comment]
I still see `make: *** No rule to make target `test-e2e-tls'.  Stop` but I think the release-next branch needs to be re-created to get the new make target.

**Comment by nak3** [comment]
/retest

Hmm... tls test may have some issue :thinking:

**Comment by nak3** [comment]
Hmm.... TLS on 4.10 works so 4.11 didn't work :thinking: I will debug it on serving repo instead of this repo. 
@skonto @mgencur Could you please take a look?

**Comment by skonto** [comment]
```
{"severity":"ERROR","timestamp":"2022-09-01T07:08:19.44918672Z","logger":"activator","caller":"websocket/connection.go:192","message":"Failed to send ping message to ws://autoscaler.knative-serving.svc.cluster.local:8080","commit":"2e2e098","knative.dev/controller":"activator","knative.dev/pod":"activator-7869d69698-69fmt","error":"connection has not yet been established","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func3\n\t/go/src/knative.dev/serving/vendor/knative.dev/pkg/websocket/connection.go:192"}
```

**Comment by nak3** [comment]
I think you are referring to the log in `411-tls-e2e-aws-ocp-411` but I'm not sure why happened and difficult to debug in this repo so I changed the tls cluster to 4.10 for now. All test passed so I will debug it on serving repo as I commented https://github.com/openshift/release/pull/31756#issuecomment-1235053771

> Btw I dont see any tls secret mounted here.

Sorry what tls secret missed to mount. The system pod does not mount any secret with `internal-tls`. (Only queue-proxy will mount the secret.)

**Comment by skonto** [comment]
> Sorry what tls secret missed to mount
I thought activator will mount a secret for connections that go through it no?

**Comment by nak3** [comment]
> Yes I was referring to that fail. I thought activator will mount a secret for connections that go through it (scale from zero) no (it has been a while since the tls review so I might remember wrongly)?

Ah, I see. Yes, I guess that you remembered that the intial implementation. We changed the secret to get the secret via secret lister and so we just can toggle the configuration via `internal-encryption: true/false` in the configmap.

> Ok approving then, should we create a jira for 4.11 as a blocker?

Sure, I will.

**Comment by nak3** [comment]
@skonto could you add the label?

**Comment by nak3** [comment]
@skonto ping

**Comment by nak3** [comment]
@skonto ping

**Comment by nak3** [comment]
@mgencur ping

**Pull request merged**
