### PR TITLE
OCPBUGS-28690: rm sdn jobs from MCO 4.17+

### PR DESCRIPTION
**Pull request by jluhrsen**
OpenShiftSDN is completely removed in 4.17 so removing those jobs. It may be desired to remove those jobs in 4.15 and/or 4.16 but that can be done in a different commit.

### CODE REVIEW

**Comment by dkhater-redhat** [comment]
ACK that the need to remove those jobs in 4.15 and/or 4.16 in a different commit. Does the secret (e.g. cluster-secrets-equinix-ocp-metal), configMaps, or any similar resources specifically used by these jobs need to be cleaned up as well? not sure if they are exclusive to this or not? probably not?

**Comment by cheesesashimi** [comment]
@dkhater-redhat Those are managed by `ci-operator`, so there's nothing to clean up.

@jluhrsen Overall, this looks reasonable. Just a quick question before I approve this: Do you plan to handle removing the jobs from 4.15 / 4.16 in this PR or would in a separate PR? Either way is fine with us.

**Comment by jluhrsen** [comment]
> @jluhrsen Overall, this looks reasonable. Just a quick question before I approve this: Do you plan to handle removing the jobs from 4.15 / 4.16 in this PR or in a separate PR? Either way is fine with us.

sorry for the delay (was on PTO). I just updated this PR to include 4.15 and 4.16. I also noticed we have a 4.18 file to handle too so took care of that.

**Pull request merged**
