### PR TITLE
Add CI for Knative Serving 0.24 and friends

### PR DESCRIPTION
**Pull request by markusthoemmes**
As per title, nothing more to say really.

### CODE REVIEW

**Comment by nak3** [comment]
It seems these env variables are necessary :thinking: ?

https://github.com/openshift/release/blame/df2a3fc489933ade61273052b107fab821fb7f02/ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-next__4.8.yaml#L240

These are used by  https://github.com/openshift/knative-serving/blob/26fffb8ef4a98c3f4d0ed7098fc451ecfd8b6895/openshift/e2e-common.sh#L115-L123

**Comment by markusthoemmes** [comment]
Oh yeah, for sure.

**Comment by markusthoemmes** [comment]
Alright, the only missing pieces are now backporting the conformance test things to the knative-serving codebase. I do think we could merge this though at this point, WDYT @nak3?

**Comment by nak3** [comment]
/lgtm
/approve

Yes, let's merge this.
We also need to revert this tweak of the kourier controller name https://github.com/openshift/knative-serving/pull/847/files#diff-8d4780ca239f8b787f8e8831ea33becadb5238ceabc0b59b55e8ce4d7c679e39R259 for v0.24. (You might already aware it, though :smile: )

**Pull request merged**
