### PR TITLE
Add openstack-k8s-operators-ci initial tests and config

### PR DESCRIPTION
**Pull request by viroel**
Adds initial repo configuration for OpenShift CI.
Adds a image build job for a ci image needed in pre-commit tests.

### CODE REVIEW

**Comment by danilo-gemoli** [comment]
@viroel you probably needs to fulfill [this](https://docs.ci.openshift.org/docs/how-tos/onboarding-a-new-component/#granting-robots-privileges-and-installing-the-github-app)

**Comment by viroel** [comment]
> @viroel you probably needs to fulfill [this](https://docs.ci.openshift.org/docs/how-tos/onboarding-a-new-component/#granting-robots-privileges-and-installing-the-github-app)

yeah, I will reach out org admins, thanks

**Comment by Sandeepyadav93** [comment]
@viroel we would need an OWNERS file at https://github.com/tripleo-ci/openstack-k8s-operators-ci first.

**Comment by danilo-gemoli** [comment]
I see no tests in `openstack-k8s-operators-openstack-k8s-operators-ci-master.yaml`, is it intentional?

**Comment by viroel** [comment]
/rehearsals-ack

"openstack-k8s-operators-ci/master/images" succeeded

**Comment by viroel** [comment]
/pj-rehearse ack

now it should work :)

**Pull request merged**
