### PR TITLE
drop crun jobs from 4.18

### PR DESCRIPTION
**Pull request by sohankunkerkar**

### CODE REVIEW

**Comment by neisw** [comment]
Looks like there are still crun references in:
[ci-4.19-upgrade-from-stable-4.18](https://github.com/openshift/release/blob/e8d0708a91f11b4a2d22a8e959ec57c628da4d44/ci-operator/config/openshift/release/openshift-release-master__ci-4.19-upgrade-from-stable-4.18.yaml)

[ci-4.19](https://github.com/openshift/release/blob/e8d0708a91f11b4a2d22a8e959ec57c628da4d44/ci-operator/config/openshift/release/openshift-release-master__ci-4.19.yaml)

As well as [4.18-upgrade-from-stable-4.17](https://github.com/openshift/release/blob/e8d0708a91f11b4a2d22a8e959ec57c628da4d44/ci-operator/config/openshift/release/openshift-release-master__ci-4.18-upgrade-from-stable-4.17.yaml) - not sure if those give you 4.17 -> 4.18 coverage you don't get otherwise and want to keep

**Comment by neisw** [comment]
Want to make sure you see the [metal failure](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/58935/rehearse-58935-periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-ipv6-runc/1858874016169725952)

```
 Error: OCI runtime error: crun: unknown version specified
{"component":"entrypoint","error":"wrapped process failed: exit status 126","file":"sigs.k8s.io/prow/pkg/entrypoint/run.go:84","func":"sigs.k8s.io/prow/pkg/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2024-11-19T14:08:55Z"} 
```

**Comment by neisw** [comment]
Are you planning to update [openshift-release-master__nightly-4.19.yaml](https://github.com/openshift/release/blob/dfa0209d5bf79d9e9f122f918a752a730c7e223b/ci-operator/config/openshift/release/openshift-release-master__nightly-4.19.yaml) and [openshift-release-master__nightly-4.19-upgrade-from-stable-4.18.yaml](https://github.com/openshift/release/blob/dfa0209d5bf79d9e9f122f918a752a730c7e223b/ci-operator/config/openshift/release/openshift-release-master__nightly-4.19-upgrade-from-stable-4.18.yaml) as well?

**Comment by neisw** [comment]
/retest-required

[history](https://prow.ci.openshift.org/job-history/gs/test-platform-results/pr-logs/directory/pull-ci-openshift-release-master-core-valid?buildId=) shows most core-valid jobs passing but intermittent failures

**Comment by neisw** [comment]
@sohankunkerkar - have a look at the `core-valid` results `Automatic merge failed; fix conflicts and then commit the result`

**Comment by sohankunkerkar** [comment]
I checked this locally by running `make  jobs` and `make ci-oeprator-config`, but it didn't throw any error.

**Comment by neisw** [comment]
@sohankunkerkar did you rebase the pr?  Would like to get this wrapped up.  If you could rebase and push those changes and the failure still happens open a question on #forum-ocp-testplatform

**Comment by sohankunkerkar** [comment]
> @sohankunkerkar did you rebase the pr?  Would like to get this wrapped up.  If you could rebase and push those changes and the failure still happens open a question on #forum-ocp-testplatform

@neisw Yes, I have already rebased my branch on top of the master branch. I think Prow adds a ‘need-rebase’ label in case of rebase failures.

**Comment by neisw** [comment]
https://github.com/sohankunkerkar/release/tree/drop-crun-jobs-4.18 says you are 413 commits behind.  

image


I understand it will normally tell you when there are conflicts but with the failure message telling you there is a conflict I think you should make sure everything is up to date and push it and then try again

```
 {"command":"PWD=/go/src/github.com/openshift/release GIT_AUTHOR_DATE=1733991583 GIT_COMMITTER_DATE=1733991583 git merge --no-ff 06b4b0376a8af660ff56dec924b02f72f3edcd39","component":"clonerefs","error":"exit status 1","file":"sigs.k8s.io/prow/pkg/pod-utils/clone/clone.go:85","func":"sigs.k8s.io/prow/pkg/pod-utils/clone.Run.func2","level":"info","msg":"Ran command","output":"Auto-merging ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml\nCONFLICT (content): Merge conflict in ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml\nAuto-merging ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-release-4.18-presubmits.yaml\nAuto-merging ci-operator/jobs/openshift-priv/kubernetes/openshift-priv-kubernetes-release-4.18-presubmits.yaml\nAuto-merging ci-operator/config/openshift/release/openshift-release-master__nightly-4.19.yaml\nAuto-merging ci-operator/config/openshift/release/openshift-release-master__nightly-4.18.yaml\nAuto-merging ci-operator/config/openshift/release/openshift-release-master__ci-4.19.yaml\nAuto-merging ci-operator/config/openshift/kubernetes/openshift-kubernetes-release-4.19.yaml\nAutomatic merge failed; fix conflicts and then commit the result.\n","severity":"info","time":"2024-12-12T08:43:24Z"}
{"component":"clonerefs","error":"1 clone records failed","file":"sigs.k8s.io/prow/cmd/clonerefs/main.go:40","func":"main.main","level":"fatal","msg":"Failed to clone refs","severity":"fatal","time":"2024-12-12T08:43:24Z"} 
```

**Comment by neisw** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.19-e2e-azure-runc-upgrade

**Comment by neisw** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-ipv6-runc-techpreview

**Comment by neisw** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.19-e2e-metal-ipi-ovn-ipv6-runc
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-azure-ovn-runc-techpreview

**Comment by neisw** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-azure-ovn-runc-techpreview

**Comment by neisw** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.19-e2e-metal-ipi-serial-ovn-ipv6-runc

**Comment by neisw** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.19-upgrade-from-stable-4.18-e2e-metal-ipi-ovn-upgrade-runc

**Comment by neisw** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.19-e2e-azure-runc-upgrade

**Comment by neisw** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.19-e2e-azure-runc-upgrade, periodic-ci-openshift-release-master-ci-4.19-upgrade-from-stable-4.18-e2e-vsphere-runc-upgrade, periodic-ci-openshift-release-master-nightly-4.19-e2e-metal-ipi-ovn-ipv6-runc-techpreview

**Comment by neisw** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.19-e2e-azure-runc-upgrade

**Comment by neisw** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.19-upgrade-from-stable-4.18-e2e-vsphere-runc-upgrade

**Comment by neisw** [comment]
/lgtm
We can validate jobs have run for all platforms, metal, vsphere, azure, etc.. A couple of variants haven't completed but the changes here don't appear to be the cause.

**Comment by neisw** [comment]
Or not..  @sohankunkerkar looks like another rebase is needed.

**Comment by neisw** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.19-upgrade-from-stable-4.18-e2e-vsphere-runc-upgrade

**Comment by sohankunkerkar** [comment]
@neisw @haircommander could you PTAL?

**Comment by neisw** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.19-e2e-azure-runc-upgrade

**Comment by neisw** [comment]
@sohankunkerkar I believe we have gotten enough signal from all of the rehearsals at this point to verify the jobs.  Can you add the rehearsals ack and then see if someone form openshift/kubernetes and approve the changes.

**Pull request merged**
