### PR TITLE
Run Jaeger e2e tests on ROSA HyperShift.

### PR DESCRIPTION
**Pull request by IshwarKanse**

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Review by frzifus — APPROVED** [review]

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-jaegertracing-jaeger-operator-main-jaeger-product-hypershift-4.14-lp-rosa-hypershift-jaeger-product-rosa-hypershift

**Comment by IshwarKanse** [comment]
Closing this as its an issue with the ROSA cluster profile which doesnt have the required pull secrets in the test cluster to pull the CI pipeline built images.

**Pull request closed without merging**
