### PR TITLE
[INTEROP-7539][INTEROP-7513] Distributed Tracing:Jaeger Operator: Expand to OCP 4.18; create FIPS config.

### PR DESCRIPTION
**Pull request by dfrazzette**
Include OCP 4.18 FIPS-enabled testing. Also add `.config.prowgen`/`slack_reporter` config and default Jira assignee.

### CODE REVIEW

**Comment by dfrazzette** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.18-lp-interop-jaeger-interop-aws

**Comment by dfrazzette** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.18-lp-interop-jaeger-interop-aws

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.18-lp-interop-jaeger-interop-aws

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.18-lp-interop-jaeger-interop-aws

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-jaegertracing-jaeger-operator-main-jaeger-product-ocp-4.18-lp-interop-jaeger-interop-aws

**Pull request merged**
