### PR TITLE
Set OCP min version to 4.10 for knative eventing >=v1.8 

### PR DESCRIPTION
**Pull request by creydr**
As per title and https://redhat-internal.slack.com/archives/CEXRYS5QC/p1678366559989999

/assign @pierDipi @matzew

### CODE REVIEW

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-release-next-410-images
/pj-rehearse pull-ci-openshift-knative-eventing-release-v1.8-410-images
/pj-rehearse pull-ci-openshift-knative-eventing-release-v1.9-410-images

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-release-v1.8-410-images

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-release-v1.9-410-images

**Review by matzew — APPROVED** [review]
/lgtm
/approve

/hold

Was this done with the `hack` repo?

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by pierDipi** [comment]
> /lgtm /approve
> 
> /hold
> 
> Was this done with the `hack` repo?

Yes

**Comment by matzew** [comment]
I do see https://github.com/openshift-knative/hack/pull/28/files

/unhold

**Pull request merged**
