### PR TITLE
Add imagebuilder presubmit

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
FYI since you configure update-config at the same time as you check it in, you need to push the config yourself

**Comment by stevekuznetsov** [comment]
Also this:

```
 {"author":"smarterclayton","component":"hook","error":"replace config map err: body: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"configmaps \\"ci-operator-openshift-api\\" not found\",\"reason\":\"NotFound\",\"details\":{\"name\":\"ci-operator-openshift-api\",\"kind\":\"configmaps\"},\"code\":404}
```

**Comment by stevekuznetsov** [comment]
We can fix the bootstrap case where update-config is already watching but there exists no original configmap to update but we can't fix the case where you change update-config in plugins.yaml at the same time as adding the file to watch

**Comment by smarterclayton** [comment]
That's fine, was going to do it anyway.

**Pull request merged**
