### PR TITLE
SDN-4384: Move to new IPsec API  for >=4.15

### PR DESCRIPTION
**Pull request by pperiyasamy**
this is to align with CNO API changes on how to enable ipsec and support N-S

(cherry picked from commit a54aaca1b4bfe1389bf75d0e9fa02f5d1711cf49)

### CODE REVIEW

**Comment by pperiyasamy** [comment]
Reason for failure with `ci/rehearse/openshift/svt/master/reliability-v2-azure-4.15-nightly-x86-reliability-v2-1h` CI lane is because of `ovn-ipsec-host` pod on two nodes (out of 12 nodes) are crashlooping with below error though machine configs are rolled out correctly.

```
2024-04-08T15:21:43.064202187Z + counter=0
2024-04-08T15:21:43.064202187Z + '[' -f /etc/cni/net.d/10-ovn-kubernetes.conf ']'
2024-04-08T15:21:43.064360389Z ovnkube-node has configured node.
2024-04-08T15:21:43.064374189Z + echo 'ovnkube-node has configured node.'
2024-04-08T15:21:43.064374189Z + pgrep pluto
2024-04-08T15:21:43.077693637Z + echo 'pluto is not running, enable the service and/or check system logs'
2024-04-08T15:21:43.077745538Z pluto is not running, enable the service and/or check system logs
2024-04-08T15:21:43.077758338Z + exit 2
```
Running the test again to see if the issue is consistent.

**Comment by pperiyasamy** [comment]
/pj-rehearse pull-ci-openshift-svt-master-reliability-v2-azure-4.15-nightly-x86-reliability-v2-1h

**Comment by pperiyasamy** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-azure-4.15-nightly-x86-data-path-ipsec-9nodes

**Comment by pperiyasamy** [comment]
> Reason for failure with `ci/rehearse/openshift/svt/master/reliability-v2-azure-4.15-nightly-x86-reliability-v2-1h` CI lane is because of `ovn-ipsec-host` pod on two nodes (out of 12 nodes) are crashlooping with below error though machine configs are rolled out correctly.
> 
> ```
> 2024-04-08T15:21:43.064202187Z + counter=0
> 2024-04-08T15:21:43.064202187Z + '[' -f /etc/cni/net.d/10-ovn-kubernetes.conf ']'
> 2024-04-08T15:21:43.064360389Z ovnkube-node has configured node.
> 2024-04-08T15:21:43.064374189Z + echo 'ovnkube-node has configured node.'
> 2024-04-08T15:21:43.064374189Z + pgrep pluto
> 2024-04-08T15:21:43.077693637Z + echo 'pluto is not running, enable the service and/or check system logs'
> 2024-04-08T15:21:43.077745538Z pluto is not running, enable the service and/or check system logs
> 2024-04-08T15:21:43.077758338Z + exit 2
> ```
> 
> Running the test again to see if the issue is consistent.

This issue is shown up again with latest run https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/50690/rehearse-50690-pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-azure-4.15-nightly-x86-control-plane-ipsec-24nodes/1780216294851743744, seems like we may have to revisit `isIPsecMachineConfigActive` logic in CNO, created a bug https://issues.redhat.com/browse/OCPBUGS-32347 to track this.

**Comment by jluhrsen** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-e2e-aws-ovn-ipsec

**Comment by jluhrsen** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-e2e-ovn-ipsec-step-registry

**Comment by pperiyasamy** [comment]
Thanks Jamo, Now this [run](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/50690/rehearse-50690-pull-ci-openshift-cluster-network-operator-master-e2e-ovn-ipsec-step-registry/1780660589492703232) hits an issue with IPsec configuration (in this run, its on a particular worker node) which might be a another cause for why cluster operators are not coming up.  Create a JIRA [OCPBUGS-32402](https://issues.redhat.com/browse/OCPBUGS-32402) to track this.

**Comment by huiran0826** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-e2e-ovn-ipsec-step-registry

**Comment by huiran0826** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-azure-4.15-nightly-x86-control-plane-ipsec-24nodes

**Comment by pperiyasamy** [comment]
closing it in favor of https://github.com/openshift/release/pull/50740.

**Pull request closed without merging**
