### PR TITLE
baremetalds-sno: fix manifest  copy

### PR DESCRIPTION
**Pull request by vrutkovs**

### CODE REVIEW

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-single-node-live-iso

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-single-node-live-iso

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-single-node-live-iso

**Review by eranco74 — COMMENTED** [review]
/lgtm

**Pull request merged**
