### PR TITLE
rename secretly openshift-sdn-based baremetalds workflows

### PR DESCRIPTION
**Pull request by danwinship**
There were several baremetalds workflows that were openshift-sdn-based but not _obviously_ openshift-sdn-based. Since sdn is about to be deprecated (and eventually removed), the workflows where it is used should make it obvious that it's being used.

(This is a prologue to changing some of these jobs to _not_ use sdn-based workflows in 4.15, and eventually changing _all_ of them to not use sdn in 4.17, when sdn goes away.)

### CODE REVIEW

**Comment by danwinship** [comment]
/assign @stbenjam 
maybe? I'm not sure who a good person for this is at this point...

**Comment by stbenjam** [comment]
Skimming it this looks fine.  Probably @derekhiggins or someone from the metal team should check this out

**Comment by danwinship** [comment]
/assign @derekhiggins 

updated to change the three `virtualmedia` workflows to be ovn-based rather than sdn-based, since there were no corresponding ovn versions of them, so it's pretty clear that everyone currently using the sdn-based virtualmedia workflows was just using them because they wanted to test virtualmedia, not because they wanted to test sdn, so we don't have to worry about losing test coverage by switching them over.

**Comment by derekhiggins** [comment]
thanks, changes look good to me
/approve

**Comment by danwinship** [comment]
/pj-rehearse ack

rebase was just to fix up a few more jobs that got added as 4.16 branches were updated

**Pull request merged**
