### PR TITLE
ComplianceAsCode: Add e2e test for PCI-DSS

### PR DESCRIPTION
**Pull request by JAORMX**
These will be needed to develop the profiles.

Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>

### CODE REVIEW

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now e03a18fbe9efa264861b029232c836ac79cee7f3

**Comment by JAORMX** [comment]
/hold

Gotta fix the profiles first

**Review by jhrozek — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
