### PR TITLE
OCPQE-15687: Add app.ci to QE profiles

### PR DESCRIPTION
**Pull request by yunjiang29**
Fix https://issues.redhat.com/browse/OCPQE-15687 Incorrect credential is used by oc adm release extract --credentials-requests

### CODE REVIEW

**Comment by jianli-wei** [comment]
@yunjiang29 I met similar issue on Alibabacloud, see my [PR](https://github.com/openshift/release/pull/40357), I wonder how you confirm your solution would work, thanks!

**Comment by yunjiang29** [comment]
> @yunjiang29 I met similar issue on Alibabacloud, see my [PR](https://github.com/openshift/release/pull/40357), I wonder how you confirm your solution would work, thanks!

@jianli-wei  I'm not sure if it works, the rehearse job is not available for core service updating.
I just want to add [app.ci cluster](https://github.com/openshift/release/blob/dbaa81857d8ed3dc2446a67a3103e17db896147b/core-services/ci-secret-bootstrap/_config.yaml#L6) to the pull secret and have a try

**Comment by jianlinliu** [comment]
@yunjiang29 once you confirm it works, pls help other "-qe" profiles together, e.g: `ibmcloud-qe` `alibabacloud-cn-qe` `alibabacloud-qe`, and so on.

**Comment by yunjiang29** [comment]
@jianlinliu, can you add lgtm label? thanks

**Comment by jianlinliu** [comment]
@yunjiang29 did you already verify it? Or you are going to verify it after the PR get merged?

**Comment by yunjiang29** [comment]
@jianlinliu  As this PR updates the core services, it seems like it must be merged before testing it.

**Comment by jianlinliu** [comment]
Got it.

**Pull request merged**
