### PR TITLE
Add skip_if_only_changed to Jenkins repositories

### PR DESCRIPTION
**Pull request by coreydaley**
Skip tests if the following regex is matched:
    `^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$`

To cut down on infrastructure costs and time to merge for simple pull
requests

### CODE REVIEW

**Comment by coreydaley** [comment]
/assign @jkhelil 
for approval

**Comment by jkhelil** [comment]
Regex used on a couple of repos
/approve

**Comment by coreydaley** [comment]
/assign @otaviof @alicerum 
for lgtm

**Pull request merged**
