### PR TITLE
OSSM-6014 Update ocp version to latest 4.15 released GA

### PR DESCRIPTION
**Pull request by fjglira**
Jira: https://issues.redhat.com/browse/OSSM-6014?filter=12407518

### CODE REVIEW

**Comment by jwendell** [comment]
/pj-rehearse pull-ci-maistra-istio-operator-maistra-3.0-integration-ocp-4-16

**Comment by fjglira** [comment]
/pj-rehearse pull-ci-maistra-istio-operator-maistra-3.0-integration-ocp-4-16

**Comment by fjglira** [comment]
/pj-rehearse pull-ci-maistra-istio-operator-maistra-3.0-integration-ocp-4-16

**Pull request merged**
