### PR TITLE
Revert elasticsearch-proxy to OCP 4.11

### PR DESCRIPTION
**Pull request by Red-GV**
This PR reverts the OCP upgrade change to elasticsearch-proxy.

### CODE REVIEW

**Comment by Red-GV** [comment]
/pj-rehearse pull-ci-openshift-elasticsearch-proxy-master-elasticsearch-operator-e2e-5-4

**Comment by Red-GV** [comment]
/pj-rehearse pull-ci-openshift-elasticsearch-proxy-master-elasticsearch-operator-e2e-5-4

**Comment by Red-GV** [comment]
/pj-rehearse pull-ci-openshift-elasticsearch-proxy-master-elasticsearch-operator-e2e-5-4

**Comment by xperimental** [comment]
/pj-rehearse pull-ci-openshift-elasticsearch-proxy-master-elasticsearch-operator-e2e-5-4

**Comment by Red-GV** [comment]
Closing in favor of #37343

**Pull request closed without merging**
