### PR TITLE
MSI: use `stable` tag for `ods-ci`

### PR DESCRIPTION
**Pull request by rnetser**

### CODE REVIEW

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-IIB-smoke-rosa-rhods-addon-baseline-fips

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-IIB-smoke-rosa-rhods-addon-baseline-fips

**Review by omrirh — APPROVED** [review]

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-IIB-smoke-rosa-rhods-addon-baseline-fips

**Review by omrirh — APPROVED** [review]

**Pull request merged**
