### PR TITLE
Removing old OKD jobs. Replaced by okd-scos variants

### PR DESCRIPTION
**Pull request by perdasilva**
Rebase of #53866

### CODE REVIEW

**Comment by grokspawn** [comment]
We have any reason why the marketplace is getting removed from the core-services/image-mirroring ([ref](https://github.com/openshift/release/pull/54988/files#diff-5e693c3f11d80ec8b8832a2ddc47e0f60e4dbc0d69b1f9ef97af65063b090cccL12)) area?

**Comment by perdasilva** [comment]
> We have any reason why the marketplace is getting removed from the core-services/image-mirroring ([ref](https://github.com/openshift/release/pull/54988/files#diff-5e693c3f11d80ec8b8832a2ddc47e0f60e4dbc0d69b1f9ef97af65063b090cccL12)) area?

@jupierce ^

**Comment by perdasilva** [comment]
> We have any reason why the marketplace is getting removed from the core-services/image-mirroring ([ref](https://github.com/openshift/release/pull/54988/files#diff-5e693c3f11d80ec8b8832a2ddc47e0f60e4dbc0d69b1f9ef97af65063b090cccL12)) area?

@jupierce ^?

**Comment by jupierce** [comment]
@grokspawn - we are prohibited from mirroring RHEL content to public quay. The new SCOS based OKD images the OKD team is working on will prevent this. These legacy OKD images are RHEL based and must stop being mirrored.

**Pull request merged**
