### PR TITLE
Bump log level for gce test clusters

### PR DESCRIPTION
**Pull request by 0xmichalis**
/assign @smarterclayton

### CODE REVIEW

**Comment by sdodson** [comment]
I did this in https://github.com/openshift/aos-cd-jobs/pull/1064 too, but I imagine your solution is more proper. lgtm assuming these are the vars used by gcp, we should fine a way to define these in one place if possible.

**Comment by smarterclayton** [comment]
Ugh, these may blow out debugging.  We have been logging at 4 in integration for this same reason.

**Comment by smarterclayton** [comment]
4 would be better - 5 is going to be too much in practice.  Do we have concrete examples that are only at 5 that we have needed?

**Comment by kargakis** [comment]
@tnozicka please chime in since you requested it

**Comment by tnozicka** [comment]
[I requested loglevel 4 originally](https://github.com/openshift/origin/issues/18315#issuecomment-361703116) :) I think @sdodson went for 5 since that is what is set for aws jobs I think. loglevel 5 would help us uncover the informers going back in time I think, but that won't hopefully be that common.

I am fine with >=4 but ideally make it consistent across jobs.

**Comment by kargakis** [comment]
Yeah, seems that all of the rest of the jobs are using [5](https://github.com/openshift/aos-cd-jobs/blob/30095da86813babbd3335e70a1c77218f5c6d4e8/sjb/inventory/group_vars/OSEv3/general.yml#L2).

**Comment by sdodson** [comment]
@kargakis could you set debug_level based on a parameter that users can specify in the jenkins job so that if they require > 4 they could do that on their own?

**Comment by kargakis** [comment]
I don't want to add functionality that depends on Jenkins before the rewrite of the jobs.

cc @stevekuznetsov

**Comment by kargakis** [comment]
Definitely something that we should explore though: https://github.com/openshift/release/issues/588

**Comment by kargakis** [comment]
Fixed this to 4, but I guess we would also need to revert https://github.com/openshift/aos-cd-jobs/pull/1064

**Comment by sdodson** [comment]
> Fixed this to 4, but I guess we would also need to revert openshift/aos-cd-jobs#1064

I'd say rather than reverting just change all occurrences of debug_level=5 to debug_level=4?

**Pull request closed without merging**
