### PR TITLE
Remove private keys in tempest logs

### PR DESCRIPTION
**Pull request by lewisdenny**
Remove private keys in tempest logs

Tempest is printing some "secrets" which is being removed in the Prow
artifacts.

This patch removes these "secrets" before uploading to the artifacts
volume.

Pulling files from the tempest run before the logs uploaded and running
them through gitleaks with out the config used in Prow now reports no
errors so I expect it to work in Prow CI as well :)

```
❯ gitleaks7 -v --config-path "./rh-gcs-filter/ansible/files/patterns/gitleaks/7.6.1" --no-git "--path=./test_files"
INFO[0001] scan time: 1 second 555 milliseconds 877 microseconds
INFO[0001] No leaks found
```

JIRA: https://issues.redhat.com/browse/OSPRH-7445

### CODE REVIEW

**Comment by lewisdenny** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-cinder-operator-main-cinder-operator-build-deploy-tempest

**Comment by lewisdenny** [comment]
/pj-rehearse ci/rehearse/openstack-k8s-operators/cinder-operator/main/cinder-operator-build-deploy-tempest

**Comment by lewisdenny** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-cinder-operator-main-cinder-operator-build-deploy-tempest

**Comment by lewisdenny** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-cinder-operator-main-cinder-operator-build-deploy-tempest

**Comment by lewisdenny** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-cinder-operator-main-cinder-operator-build-deploy-tempest

**Comment by lewisdenny** [comment]
Okay this is now working [1]

Note: `private_key': 'private key removed`

The build log is still being censored, I think once the `Invalid input for floating_network_id` issue is fixed, the offending line won't be printed anymore and the build log will be fine. 

I'll try one thing to try fix the build log but it's not an issue now we have access to the tempest log, it's just annoying.

```
Details: {'type': 'HTTPBadRequest', 'message': "Invalid input for floating_network_id. Reason: '' is not a valid UUID.", 'detail': ''}. Trying to cleanup what we provisioned so far: {'keypair': {'name': 'tempest-keypair-653936229', 'public_key': 'ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBFQDh2G435iL16hfcLsThT3Y544U3MECBkbJqnfXMKtywLyIXXvMroPkAdPPdTWvIJDUl0wgTgbyI6NlIDpw83b2biUcEzry1DZrK4yqbLasCjoe5LoMFDZUQzbalPcQPQ==', 'fingerprint': '0a:92:46:dc:f9:51:cc:d6:38:93:34:b2:c7:ad:50:cf', 'user_id': '38f3a8051a454139b82844860c6bee44', 'private_key': 'private key removed\n'}, 'security_group': {'id': 'e27d8f24-32f7-4879-aa35-11fd327d6f14', 'name': 'tempest-securitygroup--1739850140', 'stateful': True, 'tenant_id': '58cbf5623c0d48e8b50fb3eb2afb5936', 'description': 'tempest-description--895948367', 'shared': False, 'security_group_rules': [{'id': '6f5e8c9f-d341-4bd4-b505-d04cd44037ef', 'tenant_id': '58cbf5623c0d48e8b50fb3eb2afb5936', 'security_group_id': 'e27d8f24-32f7-4879-aa35-11fd327d6f14', 'ethertype': 'IPv4', 'direction': 'egress', 'protocol': None, 'port_range_min': None, 'port_range_max': None, 'remote_ip_prefix': None, 'remote_address_group_id': None, 'normalized_cidr': None, 'remote_group_id': None, 'standard_attr_id': 452, 'description': None, 'tags': [], 'created_at': '2024-06-05T00:53:07Z', 'updated_at': '2024-06-05T00:53:07Z', 'revision_number': 0, 'project_id': '58cbf5623c0d48e8b50fb3eb2afb5936'}, {'id': 'd6c81f90-a949-4ad1-aad0-f23a3bdb8975', 'tenant_id': '58cbf5623c0d48e8b50fb3eb2afb5936', 'security_group_id': 'e27d8f24-32f7-4879-aa35-11fd327d6f14', 'ethertype': 'IPv6', 'direction': 'egress', 'protocol': None, 'port_range_min': None, 'port_range_max': None, 'remote_ip_prefix': None, 'remote_address_group_id': None, 'normalized_cidr': None, 'remote_group_id': None, 'standard_attr_id': 453, 'description': None, 'tags': [], 'created_at': '2024-06-05T00:53:07Z', 'updated_at': '2024-06-05T00:53:07Z', 'revision_number': 0, 'project_id': '58cbf5623c0d48e8b50fb3eb2afb5936'}], 'tags': [], 'created_at': '2024-06-05T00:53:07Z', 'updated_at': '2024-06-05T00:53:07Z', 'revision_number': 1, 'project_id': '58cbf5623c0d48e8b50fb3eb2afb5936'}} create_validation_resources /usr/lib/python3.9/site-packages/tempest/lib/common/validation_resources.py:231
```

**Comment by lewisdenny** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-cinder-operator-main-cinder-operator-build-deploy-tempest

**Comment by lewisdenny** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-cinder-operator-main-cinder-operator-build-deploy-tempest

**Comment by viroel** [comment]
/lgtm

thanks Lewis

**Pull request merged**
