### PR TITLE
Bug OCPBUGS-33848: Fetch interface name for the additional network from node

### PR DESCRIPTION
**Pull request by MaysaMacedo**
The name of the host interface that the additional network
is available has changed to enp4s0. Let's update the
additional network attachment to make sure Pods created with
the additional network can be correctly linked to the interface.

### CODE REVIEW

**Comment by MaysaMacedo** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.15-e2e-openstack-additional-ipv6-network

**Comment by MaysaMacedo** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.15-e2e-openstack-additional-ipv6-network

**Comment by MaysaMacedo** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.16-e2e-openstack-additional-ipv6-network

**Comment by MaysaMacedo** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.16-e2e-openstack-additional-ipv6-network

**Review by mandre — COMMENTED** [review]
/lgtm
/pj-rehearse ack

**Pull request merged**
