### PR TITLE
migtools/volume-snapshot-mover: `unmanaged: true`

### PR DESCRIPTION
**Pull request by kaovilai**
So that we can set custom rules such as requiring two approvals prior to merge

Signed-off-by: Tiger Kaovilai <tkaovila@redhat.com>

### CODE REVIEW

**Review by hhpatel14 — APPROVED** [review]
This change will not have Prow manage the branch protection. 

Since this repo is not part of openshit, we can use github actions to push images. I see the changes are enabled for that. I will make further changes to remove this repo from openshift/release.

**Review by sseago — APPROVED** [review]

**Comment by sseago** [comment]
@hhpatel14 Semi-related note: we don't want to make this change to the openshift/velero* repos. When we were running into force-push issues related to fork rebases, we tried this setting and it failed. Not an issue for volume-snapshot-mover, but just be aware that we don't want to do this for the fork repos.

**Comment by kaovilai** [comment]
> Since this repo is not part of openshit, we can use github actions to push images. 

That would probably make it faster for e2e in operator to become green again.

**Pull request merged**
