### PR TITLE
feat: add openshift-observability cluster pool for PowerMon

### PR DESCRIPTION
**Pull request by vprashar2929**
This PR adds Cluster Pool for Power Monitoring.
It adds 3 cluster pools for Power Monitoring:
* OCP 4.13(AWS)
* OCP 4.14(AWS)
* OCP 4.15(AWS)

### CODE REVIEW

**Comment by vprashar2929** [comment]
cc: @cahartma

**Comment by psalajova** [comment]
/hold 
sorry, didn't notice before, but imageset ref (https://github.com/openshift/release/pull/52493/files#diff-d2ec337fbb0ccf7b6987f1e9bf32854dd3c06486411da2930e1c42243d29d4acR19) should match those available  [here](https://github.com/openshift/release/tree/master/clusters/hosted-mgmt/hive/pools). If you have hard requirements for version, please add it along with this PR

**Comment by vprashar2929** [comment]
@psalajova Updated. Thanks for pointing that out 🙇 BTW does this need updation every time there is a new imageset version?

**Comment by psalajova** [comment]
> @psalajova Updated. Thanks for pointing that out 🙇 BTW does this need updation every time there is a new imageset version?
Np. And I don't think so, but I'm not sure, so I've asked my team and will get back to you with the answer.

/unhold

**Review by IshwarKanse — APPROVED** [review]
/lgtm

**Pull request merged**
