### PR TITLE
Add MCE publish jobs for release-4.16/MCE 2.6

### PR DESCRIPTION
**Pull request by dharaneeshvrd**

### CODE REVIEW

**Comment by dharaneeshvrd** [comment]
/pj-rehearse pull-ci-openshift-hypershift-release-4.16-mce-images

**Comment by sjenning** [comment]
/pj-rehearse pull-ci-openshift-hypershift-release-4.16-mce-images

**Comment by sjenning** [comment]
oh already rehearsed
/approve
/lgtm

**Comment by dharaneeshvrd** [comment]
/pj-rehearse pull-ci-openshift-hypershift-release-4.16-mce-images

**Pull request merged**
