### PR TITLE
NetObserv FLP prow ci config

### PR DESCRIPTION
**Pull request by memodi**
[NETOBSERV-1467](https://issues.redhat.com/browse/NETOBSERV-1467) NetObserv FLP prow ci config

### CODE REVIEW

**Comment by memodi** [comment]
/pj-rehearse pull-ci-netobserv-network-observability-operator-main-e2e-operator

**Comment by memodi** [comment]
/pj-rehearse pull-ci-netobserv-network-observability-operator-main-e2e-operator

**Comment by memodi** [comment]
/pj-rehearse pull-ci-netobserv-network-observability-operator-main-e2e-operator

**Comment by memodi** [comment]
/pj-rehearse pull-ci-netobserv-network-observability-operator-main-e2e-operator

**Comment by memodi** [comment]
Sought consultation: https://issues.redhat.com/browse/OCPCRT-300

**Comment by memodi** [comment]
/pj-rehearse pull-ci-netobserv-network-observability-operator-main-images

**Comment by memodi** [comment]
/pj-rehearse pull-ci-netobserv-network-observability-operator-main-e2e-operator

**Comment by memodi** [comment]
/pj-rehearse pull-ci-netobserv-network-observability-operator-main-e2e-operator

**Comment by memodi** [comment]
/pj-rehearse pull-ci-netobserv-network-observability-operator-main-e2e-operator

**Comment by memodi** [comment]
/cc @jpinsonneau 

Could you please help review the configs?

**Comment by dhellmann** [comment]
Approval for removing the image. I haven't checked the rest of the config changes, so please have your team look at those.

/approve

**Review by jpinsonneau — APPROVED** [review]
Looks good from what I understand. Just use go 1.20 as defined in our go.mod

**Pull request merged**
