### PR TITLE
[WIP] test wif gcp cluster

### PR DESCRIPTION
**Pull request by lento-sun**

### CODE REVIEW

**Comment by lento-sun** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-gcp-wif-test-f7

**Comment by lento-sun** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-gcp-wif-test-f7

**Comment by lento-sun** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-gcp-wif-test-f7

**Comment by lento-sun** [comment]
Test failed with:
```
NAME     CONFIG                                             UPDATED   UPDATING   DEGRADED   MACHINECOUNT   READYMACHINECOUNT   UPDATEDMACHINECOUNT   DEGRADEDMACHINECOUNT   AGE
master   rendered-master-232e7c8055db95499690be92c02c7ac0   True      False      False      3              3                   3                     0                      6h5m
worker   rendered-worker-24ed99cad9c62f3c0351c6ac99d6e3c6   False     True       True       2              0                   0                     1                      6h5m
```
This maybe a product issue, waiting to be confirmed

**Comment by patriksuba** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-gcp-wif-test-f7

**Comment by patriksuba** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-gcp-wif-test-f7

**Comment by radtriste** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-gcp-wif-test-f7

**Comment by lento-sun** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-gcp-wif-test-f7

(non-wif one as benchmark)

**Comment by lento-sun** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-gcp-wif-test-f7

(wif round2)

**Pull request closed without merging**
