### PR TITLE
Implement on-demand testing for compliance profiles

### PR DESCRIPTION
**Pull request by rhmdnd**
We run weekly CI against all the compliance profiles, but it's also nice
to opt into testing the complinace operator and content against a
specific PR before it lands. This helps us assert the behavior of a
check or fix against multiple OpenShift versions.

This commit adds new, optional job definitions for all supported
Complinace Operator profiles on 4.15.

### CODE REVIEW

**Comment by rhmdnd** [comment]
/pj-rehearse pull-ci-ComplianceAsCode-content-master-4.16-e2e-aws-ocp4-cis
/pj-rehearse pull-ci-ComplianceAsCode-content-master-4.15-e2e-aws-ocp4-cis
/pj-rehearse pull-ci-ComplianceAsCode-content-master-4.14-e2e-aws-ocp4-cis
/pj-rehearse pull-ci-ComplianceAsCode-content-master-4.13-e2e-aws-ocp4-cis

**Comment by rhmdnd** [comment]
/pj-rehearse pull-ci-ComplianceAsCode-content-master-4.16-e2e-aws-ocp4-cis
/pj-rehearse pull-ci-ComplianceAsCode-content-master-4.15-e2e-aws-ocp4-cis

**Comment by rhmdnd** [comment]
@Vincent056 @yuumasato should be ready for a review.

**Review by Vincent056 — APPROVED** [review]

**Pull request merged**
