### PR TITLE
OCPBUGS-5079: Increase openshift/console e2e-gcp-console job timeout

### PR DESCRIPTION
**Pull request by TheRealJon**

### CODE REVIEW

**Review by jcaianirh — APPROVED** [review]
/lgtm

**Comment by jerolimov** [comment]
/cc @alebedev87 @r4f4

Hey @alebedev87 @r4f4, can one of you add the rehearsals-ack label for this PR?

**Comment by jerolimov** [comment]
Ah, is it fine to run this auto-ack? Let see... :smirk: 

/pj-rehearse auto-ack

**Comment by jerolimov** [comment]
Sorry, but our success-radio is currently so low, we will never pass 10 runs in a row.

/pj-rehearse skip

**Pull request merged**
