### PR TITLE
Add approver and merge for openshift/cluster-api-provider-powervs 

### PR DESCRIPTION
**Pull request by mkumatag**
Enable newly created repo for auto merge and approval process - https://github.com/openshift/cluster-api-provider-powervs

### CODE REVIEW

**Comment by mkumatag** [comment]
@stevekuznetsov @petr-muller 

throwing me an error, not sure what am I missing here?!

```
{"component":"unset","file":"prow/cmd/checkconfig/main.go:82","func":"main.reportWarning","level":"warning","msg":"the following orgs or repos require the approved label for merging but do not enable the approve plugin: [repo: openshift/cluster-api-provider-powervs]","severity":"warning","time":"2021-06-11T14:40:13Z"}
{"component":"unset","file":"prow/cmd/checkconfig/main.go:85","func":"main.reportWarning","level":"fatal","msg":"Strict is set and there were warnings","severity":"fatal","time":"2021-06-11T14:40:13Z"}
```

**Comment by petr-muller** [comment]
`approve` plugin must be enabled to manage your `approved` labels (and related commands), otherswise you'd have unmergable PRs. Make a file for your repo like this one: https://github.com/openshift/release/blob/master/core-services/prow/02_config/openshift/ci-tools/_pluginconfig.yaml

**Comment by mkumatag** [comment]
@petr-muller @stevekuznetsov finally everything is green, can we merge this PR?

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
