### PR TITLE
Add install analysis for vsphere sdn ipi jobs

### PR DESCRIPTION
**Pull request by xueqzhan**

### CODE REVIEW

**Comment by deads2k** [comment]
You should ask Brad for a review of this.

**Comment by xueqzhan** [comment]
> You should ask Brad for a review of this.

I will, once we decide that vsphere, sdn, ipi, and the minimum number is what we want.

**Comment by xueqzhan** [comment]
@bradmwilliams We are adding another job to analyze install status across job runs for a payload. Some details (platform, network, etc) might still change. But please review the framework to make sure I am on the right track. 

This PR is making the job informing for now. But eventually it will be blocking.

**Review by bradmwilliams — APPROVED** [review]

**Comment by bradmwilliams** [comment]
Changes look good to me!

**Comment by stbenjam** [comment]
Looks good to me

/lgtm

**Pull request merged**
