### PR TITLE
Update modelmesh-serving job names and add odh-manifests job

### PR DESCRIPTION
**Pull request by Jooho**
- Add a base image for modelmesh-serving
- Update job names
- Add `odh-manifest fvt test` job

### CODE REVIEW

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-serving-main-fvt pull-ci-opendatahub-io-modelmesh-serving-main-fvt-odh-manifests

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-serving-main-fvt pull-ci-opendatahub-io-modelmesh-serving-main-fvt-odh-manifests

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-modelmesh-serving-main-fvt pull-ci-opendatahub-io-modelmesh-serving-main-fvt-odh-manifests

**Review by Xaenalt — APPROVED** [review]

**Pull request merged**
