### PR TITLE
Build new image as a tag for rosa-aws-cli

### PR DESCRIPTION
**Pull request by yasun1**
[OCM-7533](https://issues.redhat.com//browse/OCM-7533)

### CODE REVIEW

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-rosa-master-images-release-images

**Comment by yasun1** [comment]
/ pj-rehearse pull-ci-openshift-rosa-master-images-release-images

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-rosa-master-images-release-images

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-rosa-master-images-release-images

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-rosa-master-images-release-images

**Comment by yasun1** [comment]
/pj-rehearse pull-ci-openshift-rosa-master-images-release-images

**Comment by yasun1** [comment]
@ciaranRoche please help review. Thanks.

**Review by ciaranRoche — APPROVED** [review]
/lgtm

**Pull request merged**
