### PR TITLE
Add a slack notification for the canary e2e aws job

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by vrutkovs** [comment]
Needs `make update`

Lets use a different channel? Notifications may get too noisy - and we might want to have more jobs, so a seperate #notifications-ci channel might be a good idea

**Comment by bparees** [comment]
> Lets use a different channel? Notifications may get too noisy - and we might want to have more jobs, so a seperate #notifications-ci channel might be a good idea

i chose this channel because i kinda want the TRT team watching this job (the whole idea is it should not be failing frequently), but sure, we can establish a new channel and use `@mentions`

**Comment by bparees** [comment]
@vrutkovs fixed up

**Review by wking — APPROVED** [review]
/lgtm

**Pull request merged**
