### PR TITLE
Use python image as build_root for OLS

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-service-main-test-unit

**Comment by danilo-gemoli** [comment]
What? I did nothing other than rerunning and it is now passing?

**Comment by danilo-gemoli** [comment]
We're rehearsing something that is neither what I see on this PR nor what is in `o/release` at [openshift-lightspeed-service-main.yaml](https://github.com/openshift/release/blob/3c64db157e6ae6ff433f701094b456ef7ee9bd13/ci-operator/config/openshift/lightspeed-service/openshift-lightspeed-service-main.yaml):

```bash
$ oc --context=build03 -n ci get pod/f41858d8-01fc-43e1-b039-c6798a50e939 -oyaml | yq '.spec.containers[0].env[]|select(.name=="CONFIG_SPEC").value' | base64 -d | gzip -d

base_images:
  ubi9-python311:
    name: ubi-python-311
    namespace: ocp
    tag: "9"
build_root:
  image_stream_tag:
    name: ubi-python-311
    namespace: ocp
    tag: "9"
images:
- dockerfile_path: Containerfile
  to: lightspeed-service-api
promotion:
  namespace: ols
  tag: latest
releases:
  initial:
    integration:
      name: "4.15"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.15"
      namespace: ocp
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: unit
  commands: make test-unit
  container:
    from: ubi9-python311
zz_generated_metadata:
  branch: main
  org: openshift
  repo: lightspeed-service
```
ProwJob run: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/46171/rehearse-46171-pull-ci-openshift-lightspeed-service-main-unit/1729802313998012416

/cc @smg247

**Comment by danilo-gemoli** [comment]
> We're rehearsing something that is neither what I see on this PR nor what is in o/release at [openshift-lightspeed-service-main.yaml](https://github.com/openshift/release/blob/3c64db157e6ae6ff433f701094b456ef7ee9bd13/ci-operator/config/openshift/lightspeed-service/openshift-lightspeed-service-main.yaml):

https://github.com/openshift/release/pull/46170 was merged in the meantime, that's the reason.

**Comment by bparees** [comment]
using an image that doesn't have a "/go" path is not possible right now, opened https://issues.redhat.com/browse/DPTP-3776 as an RFE to add support for this.

closing this for now, we'll use the workaround in https://github.com/openshift/release/pull/46170 for now.

**Pull request closed without merging**
