### PR TITLE
network-operator: don't e2e on README changes

### PR DESCRIPTION
**Pull request by squeed**

### CODE REVIEW

**Comment by squeed** [comment]
Interesting, comments aren't allowed by the linter.

**Comment by squeed** [comment]
@danwinship PTAL, thanks.

**Comment by petr-muller** [comment]
> I feel like we shouldn't have approver bits here... I don't know how these config files work.
> But since an actual testing person commented on this bug and failed to say "no, wait! You're doing it all wrong!", I guess

We actually **want** you to own your CI config and know how it works :D

**Pull request merged**
