### PR TITLE
re-orgnize aws usgov workflows and some tidy up

### PR DESCRIPTION
**Pull request by jianlinliu**
1. create dedicated subfolder to save usgov install workflows
2. tidy up rehearse items on gcp platform
3. rename aws rehearse jobs name (remove "-qe")
4. add sleep time for gcp/azure to wait for all services booted up

### CODE REVIEW

**Comment by jianlinliu** [comment]
cc @yunjiang29 @jianli-wei for review

**Comment by jianli-wei** [comment]
LGTM

**Comment by jianlinliu** [comment]
Most of failed jobs are because lack of azure slice quota. One of them successfully got azure slice quota, installation get completed successfully, but e2e testing failed, not relevant with this PR.

So it is ready to merge now. @yunjiang29 can you help review again.

**Pull request merged**
