### PR TITLE
SPLAT-1713: Added vcenter server value to failure domains.

### PR DESCRIPTION
**Pull request by vr4manta**
[SPLAT-1713](https://issues.redhat.com//browse/SPLAT-1713)

### Changes
- Added vCenter server information to the failure domain output

### CODE REVIEW

**Comment by vr4manta** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.18-e2e-vsphere-ovn-upi

**Comment by rvanderp3** [comment]
/lgtm
/hold
feel free to drop the hold once install completes

**Comment by vr4manta** [comment]
/unhold
script completed and installer was waiting.

**Pull request merged**
