### PR TITLE
OCPBUGS-33278: remove e2e-gcp-qe-no-capabilities

### PR DESCRIPTION
**Pull request by Elbehery**
cc @openshift/openshift-team-etcd @soltysh

### CODE REVIEW

**Review by geliu2016 — APPROVED** [review]
/label cherry-pick-approved

**Comment by hasbro17** [comment]
/remove-lifecycle rotten

Another sprint and this keeps on going :)

@Elbehery Can you please rebase this?

@geliu2016 Just double checking that we can remove this job. This has never passed CI for us so not sure there's any point in running this on our PRs until it gets fixed
```
level=error msg=failed to fetch Master Machines: failed to load asset "Install Config": failed to create install config: invalid "install-config.yaml" file: [capabilities: Invalid value: types.Capabilities{BaselineCapabilitySet:"None", AdditionalEnabledCapabilities:[]v1.ClusterVersionCapability(nil)}: disabling CloudCredential capability available only for baremetal platforms, capabilities: Invalid value: types.Capabilities{BaselineCapabilitySet:"None", AdditionalEnabledCapabilities:[]v1.ClusterVersionCapability(nil)}: disabling CloudControllerManager is only supported on the Baremetal, None, or External platform with cloudControllerManager value none, capabilities: Invalid value: types.Capabilities{BaselineCapabilitySet:"None", AdditionalEnabledCapabilities:[]v1.ClusterVersionCapability(nil)}: the Ingress capability is required]
```
https://prow.ci.openshift.org/job-history/gs/test-platform-results/pr-logs/directory/pull-ci-openshift-cluster-etcd-operator-master-e2e-gcp-qe-no-capabilities?buildId=1799075460986966016

**Comment by geliu2016** [comment]
> /remove-lifecycle rotten
> 
> Another sprint and this keeps on going :)
> 
> @Elbehery Can you please rebase this?
> 
> @geliu2016 Just double checking that we can remove this job. This has never passed CI for us so not sure there's any point in running this on our PRs until it gets fixed
> 
> ```
> level=error msg=failed to fetch Master Machines: failed to load asset "Install Config": failed to create install config: invalid "install-config.yaml" file: [capabilities: Invalid value: types.Capabilities{BaselineCapabilitySet:"None", AdditionalEnabledCapabilities:[]v1.ClusterVersionCapability(nil)}: disabling CloudCredential capability available only for baremetal platforms, capabilities: Invalid value: types.Capabilities{BaselineCapabilitySet:"None", AdditionalEnabledCapabilities:[]v1.ClusterVersionCapability(nil)}: disabling CloudControllerManager is only supported on the Baremetal, None, or External platform with cloudControllerManager value none, capabilities: Invalid value: types.Capabilities{BaselineCapabilitySet:"None", AdditionalEnabledCapabilities:[]v1.ClusterVersionCapability(nil)}: the Ingress capability is required]
> ```
> 
> https://prow.ci.openshift.org/job-history/gs/test-platform-results/pr-logs/directory/pull-ci-openshift-cluster-etcd-operator-master-e2e-gcp-qe-no-capabilities?buildId=1799075460986966016

Hello [hasbro17](https://github.com/hasbro17), Got it, please remove it, thank you.

**Comment by Elbehery** [comment]
@hasbro17 rebased 👍🏽

**Pull request merged**
