### PR TITLE
OCPBUGS-11204: ovn-kubernetes: remove building duplicate RHEL9 images

### PR DESCRIPTION
**Pull request by dcbw**
Now that the main images have been moved to RHEL9, we can remove the bits here that build the rhel9-suffixed images.

### CODE REVIEW

**Comment by dcbw** [comment]
Main jobs passed; all we're testing is OCP and OKD image builds anyway.

/pj-rehearse ack

**Comment by martinkennelly** [comment]
/retitle OCPBUGS-11204: ovn-kubernetes: remove building duplicate RHEL9 images

**Review by trozet — APPROVED** [review]
/approve

**Comment by bparees** [comment]
removing names, not adding new ones, so
/approve

**Pull request merged**
