### PR TITLE
Add e2e libvirt to cluster-api-provider-libvirt

### PR DESCRIPTION
**Pull request by praveenkumar**
This will enable the tests for e2e libvirt for the `cluster-api-provider-libvirt` repo.

### CODE REVIEW

**Comment by ingvagabund** [comment]
@praveenkumar https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_release/4047/pull-ci-openshift-release-master-ordered-prow-config/6863

Please follow https://github.com/openshift/release/tree/master/ci-operator#ci-operator to resolve the failure.

**Comment by praveenkumar** [comment]
Does that command also depend of which version of docker we are using I tried on Mac and not seeing any error?

```
18:40 $ docker run -it -v $(pwd)/ci-operator:/ci-operator:z registry.svc.ci.openshift.org/ci/ci-operator-prowgen:latest --from-dir /ci-operator/config/ --to-dir /ci-operator/jobs
WARN[0000] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-ansible-service-broker-master-operator-molecule-e2e
WARN[0000] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-ansible-service-broker-master-operator-molecule-olm-e2e
WARN[0000] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-cloud-credential-operator-master-e2e-aws-upgrade
WARN[0000] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-cluster-api-actuator-pkg-master-e2e-aws-operator
WARN[0000] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-cluster-api-provider-aws-master-actuator-pkg-staleness
WARN[0000] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-cluster-api-provider-aws-master-e2e-aws-operator
WARN[0000] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-cluster-api-provider-aws-master-e2e-aws-upgrade
WARN[0000] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-cluster-api-provider-azure-master-bazel-verify
WARN[0001] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-cluster-config-operator-master-e2e-aws-upgrade
WARN[0001] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-cluster-dns-operator-release-4.1-e2e-aws-operator
WARN[0001] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-cluster-dns-operator-release-4.1-e2e-aws-upgrade
WARN[0001] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-cluster-dns-operator-release-4.2-e2e-aws-operator
WARN[0001] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-cluster-dns-operator-release-4.2-e2e-aws-upgrade
WARN[0001] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-cluster-dns-operator-release-4.3-e2e-aws-operator
WARN[0001] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-cluster-dns-operator-release-4.3-e2e-aws-upgrade
WARN[0002] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-cluster-ingress-operator-master-e2e-aws-operator
WARN[0002] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-cluster-ingress-operator-master-e2e-aws-upgrade
WARN[0002] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-cluster-network-operator-master-e2e-aws-upgrade
WARN[0002] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-cluster-samples-operator-master-e2e-aws-operator
WARN[0002] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-cluster-samples-operator-master-e2e-aws-image-ecosystem
WARN[0002] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-cluster-samples-operator-master-e2e-aws-upgrade
WARN[0002] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-cluster-storage-operator-master-e2e-aws-upgrade
WARN[0003] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-cluster-update-keys-release-4.1-e2e-aws-upgrade
WARN[0003] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-cluster-update-keys-release-4.2-e2e-aws-upgrade
WARN[0003] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-cluster-update-keys-release-4.3-e2e-aws-upgrade
WARN[0003] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-cluster-version-operator-master-e2e-aws-upgrade
WARN[0004] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-descheduler-operator-release-4.1-e2e-aws-operator
WARN[0004] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-descheduler-operator-release-4.2-e2e-aws-operator
WARN[0004] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-descheduler-operator-release-4.3-e2e-aws-operator
WARN[0004] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-image-registry-release-4.1-e2e-aws-image-registry
WARN[0004] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-image-registry-release-4.2-e2e-aws-image-registry
WARN[0004] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-image-registry-release-4.3-e2e-aws-image-registry
WARN[0005] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-kubernetes-autoscaler-release-4.1-e2e-aws-operator
WARN[0005] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-kubernetes-autoscaler-release-4.2-e2e-aws-operator
WARN[0005] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-kubernetes-autoscaler-release-4.3-e2e-aws-operator
WARN[0005] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-library-go-master-verify-alpha-build-machinery
WARN[0005] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-library-go-release-4.1-verify-alpha-build-machinery
WARN[0005] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-library-go-release-4.2-verify-alpha-build-machinery
WARN[0005] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-library-go-release-4.3-verify-alpha-build-machinery
WARN[0005] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-machine-api-operator-master-actuator-pkg-staleness
WARN[0005] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-machine-api-operator-release-4.1-actuator-pkg-staleness
WARN[0005] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-machine-api-operator-release-4.1-e2e-aws-operator
WARN[0005] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-machine-api-operator-release-4.1-e2e-aws-upgrade
WARN[0005] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-machine-api-operator-release-4.1-e2e-rhel-scaleup
WARN[0005] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-machine-api-operator-release-4.2-actuator-pkg-staleness
WARN[0005] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-machine-api-operator-release-4.2-e2e-aws-operator
WARN[0005] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-machine-api-operator-release-4.2-e2e-aws-upgrade
WARN[0005] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-machine-api-operator-release-4.2-e2e-rhel-scaleup
WARN[0005] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-machine-api-operator-release-4.3-actuator-pkg-staleness
WARN[0005] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-machine-api-operator-release-4.3-e2e-aws-operator
WARN[0005] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-machine-api-operator-release-4.3-e2e-aws-upgrade
WARN[0005] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-machine-api-operator-release-4.3-e2e-rhel-scaleup
WARN[0006] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-machine-config-operator-master-e2e-aws-upgrade
WARN[0006] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-machine-config-operator-master-e2e-rhel-scaleup
WARN[0006] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-machine-config-operator-master-e2e-etcd-quorum-loss
WARN[0006] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-machine-config-operator-master-e2e-restore-cluster-state
WARN[0006] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-openshift-ansible-master-e2e-aws-scaleup-rhel7
WARN[0006] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-openshift-ansible-release-3.11-e2e-gcp-logging
WARN[0006] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-openshift-ansible-release-4.1-e2e-aws-scaleup-rhel7
WARN[0006] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-openshift-ansible-release-4.2-e2e-aws-scaleup-rhel7
WARN[0006] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-openshift-ansible-release-4.3-e2e-aws-scaleup-rhel7
WARN[0007] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-origin-aggregated-logging-master-full-integ-aws
WARN[0007] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-prometheus-alertmanager-master-e2e-aws-upgrade
WARN[0007] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-prometheus-operator-release-4.1-e2e-aws-upgrade
WARN[0007] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-prometheus-operator-release-4.2-e2e-aws-upgrade
WARN[0007] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-prometheus-operator-release-4.3-e2e-aws-upgrade
WARN[0007] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-service-ca-operator-release-4.1-e2e-aws-operator
WARN[0007] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-service-ca-operator-release-4.1-e2e-aws-upgrade
WARN[0007] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-service-ca-operator-release-4.2-e2e-aws-operator
WARN[0007] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-service-ca-operator-release-4.2-e2e-aws-upgrade
WARN[0007] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-service-ca-operator-release-4.3-e2e-aws-operator
WARN[0007] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-openshift-service-ca-operator-release-4.3-e2e-aws-upgrade
WARN[0008] Generated job name is longer than 63 characters. This may cause issues when Prow attempts to label resources with job name. Consider a shorter name.  name=pull-ci-operator-framework-operator-metering-master-metering-e2e-aws

$ echo $?
0
```

**Comment by ingvagabund** [comment]
@praveenkumar you can ignore those warnings, they pop up for me too.

**Comment by zeenix** [comment]
Seems this didn't work? :( https://github.com/openshift/cluster-api-provider-libvirt/pull/157#issuecomment-503230191

**Comment by ingvagabund** [comment]
yeah, not sure what is still missing

**Comment by zeenix** [comment]
@ingvagabund I'm looking into it..

**Comment by zeenix** [comment]
@ingvagabund oh it works now. It wasn't me though. :) https://github.com/openshift/cluster-api-provider-libvirt/pull/157#issuecomment-503603514 . Can we remove the Jenkins job now as it almost never works now a days?

**Pull request merged**
