### PR TITLE
feat(RHTAP-970): Add jobs for running load-test-max-concurrency tests with redhat-appstudio

### PR DESCRIPTION
**Pull request by pmacik**
This PR adds 2 daily jobs for https://issues.redhat.com/browse/RHTAP-970

### CODE REVIEW

**Comment by pmacik** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-basic

**Comment by pmacik** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-basic

**Comment by pmacik** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-advanced

**Comment by pmacik** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-basic periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-advanced

**Comment by pmacik** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-basic periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-advanced

**Review by sawood14012 — APPROVED** [review]

**Pull request merged**
