### PR TITLE
Cleanup techpreview workflows

### PR DESCRIPTION
**Pull request by JoelSpeed**
It was suggested that I might be able to make the techpreview workflow simpler by directly referncing the ipi-conf-techpreview and using the regular ipi-aws-pre

This allows us to remove a bunch of configuration while maintaining the same jobs, so in theory should be easier to maintain in the future

### CODE REVIEW

**Comment by JoelSpeed** [comment]
These tests have failed because of https://github.com/openshift/origin/pull/26449, which is fixing a previous PR which broke the techpreview jobs across the board

**Review by staebler — COMMENTED** [review]
/lgtm
/approve

**Comment by JoelSpeed** [comment]
The owners check is failing because we removed the 2 folders, it is not understanding the removal of the folders for some reason. Have pinged DPTP about double checking it and getting an override

**Comment by droslean** [comment]
/lgtm
/approve
/hold

Holiding for the rehearsals. Feel free to `/hold cancel` if there is no point in waiting.

**Comment by JoelSpeed** [comment]
/hold cancel

The jobs seem to be working as expected, the failure on AWS is unrelated

**Pull request merged**
