### PR TITLE
logging - publish the oal test image logging-ci-test-runner

### PR DESCRIPTION
**Pull request by richm**

### CODE REVIEW

**Comment by richm** [comment]
@jcantrill part 1 - publish the oal test image

part 2 - write a test in clo that clones origin-aggregated-logging and runs the logging ci tests

part 3 - add a full-integ-aws test to clo in this repo

**Comment by richm** [comment]
aws flake
/retest

**Comment by richm** [comment]
aws flake
/retest

**Comment by richm** [comment]
/retest
need some head&shoulders for these flakes . . .

**Comment by richm** [comment]
keeps failing in multi-tenancy
```
F0821 01:54:42.775388   51589 helpers.go:119] error: net/http: TLS handshake timeout
```
not sure what's going on
/retest

**Comment by richm** [comment]
/retest
rsyslog flake

**Comment by jcantrill** [comment]
> @jcantrill part 1 - publish the oal test image
> 
> part 2 - write a test in clo that clones origin-aggregated-logging and runs the logging ci tests
> 
why do we need to clone the repo in CLO?  I thought the whole point of publishing the test image was to simply be able to spin up the image and run the tests

> part 3 - add a full-integ-aws test to clo in this repo

**Comment by richm** [comment]
> why do we need to clone the repo in CLO? I thought the whole point of publishing the test image was to simply be able to spin up the image and run the tests

You can't just deploy the test pod.  There is some extra stuff that has to be done in the oal `hack/test-logging.sh` script such as adding a secret for the admin.kubeconfig for the test pod to use, etc.  I suppose you could duplicate that code in CLO and maintain it separately.

**Comment by richm** [comment]
please review and lgtm

**Pull request merged**
