### PR TITLE
Bug 1963871: cluster-etcd-operator: get build_root from repo

### PR DESCRIPTION
**Pull request by mfojtik**
see: https://github.com/openshift/cluster-etcd-operator/blob/master/.ci-operator.yaml

### CODE REVIEW

**Comment by sttts** [comment]
/lgtm

/hold

until master unit and verify jobs in rehearsals are green.

**Comment by hexfusion** [comment]
/retitle Bug 1963871: cluster-etcd-operator: get build_root from repo

**Comment by hexfusion** [comment]
Dependency https://github.com/openshift/cluster-etcd-operator/pull/599 has merged. Will retest in an hour.

**Comment by lilic** [comment]
/retest

I don't think it kicked them off. 🤔

**Pull request merged**
