### PR TITLE
Remove now redundant bash from upgrade template

### PR DESCRIPTION
**Pull request by 0xmichalis**
Reusing the script in https://github.com/openshift/openshift-azure/pull/730 we are able to remove 70% code off of our e2e templates. This is an example for upgrades

@openshift/sig-azure fyi

### CODE REVIEW

**Comment by kargakis** [comment]
@stevekuznetsov @bbguimaraes

**Comment by kargakis** [comment]
The upgrade part will not work until @asalkeld's work to generate the manifest as part of createorupdate gets merged (https://github.com/openshift/openshift-azure/pull/623)

**Comment by kargakis** [comment]
> The upgrade part will not work until @asalkeld's work to generate the manifest as part of createorupdate gets merged ([openshift/openshift-azure#623](https://github.com/openshift/openshift-azure/pull/623))

Nevermind, I can work around this for now.

**Comment by kargakis** [comment]
Successful run using https://github.com/openshift/openshift-azure/pull/730

http://pastebin.test.redhat.com/670107

**Comment by kargakis** [comment]
@smarterclayton do you have any kind of upgrade tests in Origin today where you:
1. need to do something before the upgrade, eg. change a configurable in the api server
2. run the upgrade
3. verify the configuration change was applied correctly

Or the upgrade suite is still only a create->upgrade->test flow?

**Comment by smarterclayton** [comment]
not yet, that's coming soon.

**Pull request merged**
