### PR TITLE
remove periodic jobs for cluster autoscaler operator

### PR DESCRIPTION
**Pull request by elmiko**
after an internal review from the cloud infrastructure team, we do not believe these tests should be performed on a periodic basis and are removing them. This operator does not have platform specific behavior and its functionality is also transitively tested through our cluster autoscaler testing.

### CODE REVIEW

**Comment by droslean** [comment]
@elmiko You need also to delete:
https://github.com/openshift/release/blob/master/core-services/prow/02_config/_plugins.yaml#L403-L406

**Comment by elmiko** [comment]
updated with suggestion

**Comment by elmiko** [comment]
rebased

**Comment by elmiko** [comment]
rebased

**Pull request merged**
