### PR TITLE
Sync Serverless CI

### PR DESCRIPTION
**Pull request by serverless-qe**
Sync Serverless CI using openshift-knative/hack.

### CODE REVIEW

**Comment by skonto** [comment]
For reference this comes from: https://github.com/openshift-knative/hack/pull/78.

**Comment by skonto** [comment]
Serving job failed with:
```
{  failed to wait for the created cluster claim to become ready: timed out waiting for the condition}
```

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-release-v1.10-411-test-e2e-aws-ocp-411

**Comment by skonto** [comment]
/pj-rehearse periodic-ci-openshift-knative-eventing-kafka-broker-release-v1.10-411-test-reconciler-aws-ocp-411-continuous

**Comment by skonto** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-kafka-broker-release-v1.10-411-test-reconciler-aws-ocp-411

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
