### PR TITLE
hypershift-agent: add hypershift-dump

### PR DESCRIPTION
**Pull request by LiangquanLi930**
add `hypershift-dump` in hypershift-agent workflow

### CODE REVIEW

**Review by eranco74 — COMMENTED** [review]
/lgtm

**Comment by eranco74** [comment]
Looks like a bug in 4.13, hypershift operator never get to successfully create the hostedcontrolplane.

**Comment by LiangquanLi930** [comment]
looks because it: https://redhat-internal.slack.com/archives/C01C8502FMM/p1675411730344709

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-agent-ovn

**Pull request merged**
