### PR TITLE
Drop bazel from Azure jobs

### PR DESCRIPTION
**Pull request by ingvagabund**
We don't use bazel to build go binaries.
It's additional complexity that's not needed.

### CODE REVIEW

**Comment by frobware** [comment]
Isn't bazel used by the unit tests?

**Comment by ingvagabund** [comment]
> Isn't bazel used by the unit tests?
```yaml
- as: unit
  commands: |
    go test -timeout 20m ./pkg/... ./cmd/...
  container:
    from: src
```
I suppose not

**Pull request merged**
