### PR TITLE
Compliance Operator: bump build root to 1.19

### PR DESCRIPTION
**Pull request by jhrozek**
does what is says on the box. Should unlock dep bumps for CO.

### CODE REVIEW

**Comment by jhrozek** [comment]
hmm, haven't seen this before:
```
=== CONT  TestE2E/Serial_tests/TestKubeletConfigRemediation
    helpers.go:719: 2023-01-25T21:47:05Z: Waiting until suite kubelet-remediation-test-suite reaches target status 'DONE'. Current status: RUNNING
    helpers.go:719: 2023-01-25T21:47:10Z: Waiting until suite kubelet-remediation-test-suite reaches target status 'DONE'. Current status: RUNNING
    helpers.go:719: 2023-01-25T21:47:15Z: Waiting until suite kubelet-remediation-test-suite reaches target status 'DONE'. Current status: RUNNING
    helpers.go:719: 2023-01-25T21:47:20Z: Waiting until suite kubelet-remediation-test-suite reaches target status 'DONE'. Current status: RUNNING
    helpers.go:719: 2023-01-25T21:47:25Z: Waiting until suite kubelet-remediation-test-suite reaches target status 'DONE'. Current status: RUNNING
    helpers.go:719: 2023-01-25T21:47:30Z: Waiting until suite kubelet-remediation-test-suite reaches target status 'DONE'. Current status: RUNNING
    helpers.go:719: 2023-01-25T21:47:35Z: Waiting until suite kubelet-remediation-test-suite reaches target status 'DONE'. Current status: AGGREGATING
    helpers.go:719: 2023-01-25T21:47:40Z: Waiting until suite kubelet-remediation-test-suite reaches target status 'DONE'. Current status: AGGREGATING
    helpers.go:555: 2023-01-25T21:47:51Z: ComplianceScan ready (DONE)
    helpers.go:766: 2023-01-25T21:47:51Z: All scans in ComplianceSuite have finished (kubelet-remediation-test-suite)
    helpers.go:1364: 2023-01-25T21:47:56Z: Found remediation: kubelet-remediation-test-suite-kubelet-enable-streaming-connections
    helpers.go:1368: 2023-01-25T21:47:56Z: Machines updated with remediation
    helpers.go:1077: 2023-01-25T21:47:56Z: Node ip-10-0-146-109.us-west-2.compute.internal has config rendered-master-2bcbca33bda05394449b6fd059c6b0ac, desired config rendered-master-2bcbca33bda05394449b6fd059c6b0ac state Done
    helpers.go:1088: 2023-01-25T21:47:56Z: Node ip-10-0-146-109.us-west-2.compute.internal was updated
    helpers.go:1077: 2023-01-25T21:47:56Z: Node ip-10-0-160-14.us-west-2.compute.internal has config rendered-e2e-c649a245128217ae80e90c8a8f2ba291, desired config rendered-e2e-c649a245128217ae80e90c8a8f2ba291 state Done
    helpers.go:1088: 2023-01-25T21:47:56Z: Node ip-10-0-160-14.us-west-2.compute.internal was updated
    helpers.go:1077: 2023-01-25T21:47:56Z: Node ip-10-0-167-189.us-west-2.compute.internal has config rendered-master-2bcbca33bda05394449b6fd059c6b0ac, desired config rendered-master-2bcbca33bda05394449b6fd059c6b0ac state Done
    helpers.go:1088: 2023-01-25T21:47:56Z: Node ip-10-0-167-189.us-west-2.compute.internal was updated
    helpers.go:1077: 2023-01-25T21:47:56Z: Node ip-10-0-169-95.us-west-2.compute.internal has config rendered-worker-e893db68155cb0850077703a1631af2f, desired config rendered-worker-e893db68155cb0850077703a1631af2f state Done
    helpers.go:1088: 2023-01-25T21:47:56Z: Node ip-10-0-169-95.us-west-2.compute.internal was updated
    helpers.go:1077: 2023-01-25T21:47:56Z: Node ip-10-0-229-254.us-west-2.compute.internal has config rendered-master-2bcbca33bda05394449b6fd059c6b0ac, desired config rendered-master-2bcbca33bda05394449b6fd059c6b0ac state Done
    helpers.go:1088: 2023-01-25T21:47:56Z: Node ip-10-0-229-254.us-west-2.compute.internal was updated
    helpers.go:1077: 2023-01-25T21:47:56Z: Node ip-10-0-253-254.us-west-2.compute.internal has config rendered-worker-e893db68155cb0850077703a1631af2f, desired config rendered-worker-e893db68155cb0850077703a1631af2f state Done
    helpers.go:1088: 2023-01-25T21:47:56Z: Node ip-10-0-253-254.us-west-2.compute.internal was updated
    helpers.go:1091: 2023-01-25T21:47:56Z: All machines updated
    helpers.go:2414: 2023-01-25T21:47:56Z: Scan re-launched
    e2e_test.go:3541: 2023-01-25T21:47:56Z: Scan phase should be reset
    helpers.go:555: 2023-01-25T21:48:07Z: ComplianceScan ready (RUNNING)
    helpers.go:766: 2023-01-25T21:48:07Z: All scans in ComplianceSuite have finished (kubelet-remediation-test-suite)
    e2e_test.go:3548: 2023-01-25T21:48:07Z: Let's wait for it to be done now
    helpers.go:719: 2023-01-25T21:48:12Z: Waiting until suite kubelet-remediation-test-suite reaches target status 'DONE'. Current status: RUNNING
    helpers.go:719: 2023-01-25T21:48:17Z: Waiting until suite kubelet-remediation-test-suite reaches target status 'DONE'. Current status: RUNNING
    helpers.go:719: 2023-01-25T21:48:22Z: Waiting until suite kubelet-remediation-test-suite reaches target status 'DONE'. Current status: RUNNING
    helpers.go:719: 2023-01-25T21:48:27Z: Waiting until suite kubelet-remediation-test-suite reaches target status 'DONE'. Current status: RUNNING
    helpers.go:719: 2023-01-25T21:48:32Z: Waiting until suite kubelet-remediation-test-suite reaches target status 'DONE'. Current status: AGGREGATING
    helpers.go:719: 2023-01-25T21:48:37Z: Waiting until suite kubelet-remediation-test-suite reaches target status 'DONE'. Current status: AGGREGATING
    helpers.go:719: 2023-01-25T21:48:42Z: Waiting until suite kubelet-remediation-test-suite reaches target status 'DONE'. Current status: AGGREGATING
    helpers.go:316: expecting COMPLIANT got NON-COMPLIANT
```
let's try again and see if the issue goes away..

**Comment by jhrozek** [comment]
/pj-rehearse pull-ci-ComplianceAsCode-compliance-operator-master-e2e-aws

**Comment by jhrozek** [comment]
gah, a different intermittent error
/pj-rehearse pull-ci-ComplianceAsCode-compliance-operator-master-e2e-aws

**Review by rhmdnd — APPROVED** [review]
/lgtm

**Comment by jhrozek** [comment]
/pj-rehearse ack
because the tests passed and go 1.17 is not used anymore

**Pull request merged**
