### PR TITLE
network-flow-matrix: test main branch for release-4.19

### PR DESCRIPTION
**Pull request by sabinaaledort**

### CODE REVIEW

**Comment by sabinaaledort** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.19-metal-ovn-network-flow-matrix-bm

**Review by shirmoran — APPROVED** [review]

**Comment by sabinaaledort** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.19-metal-ovn-network-flow-matrix-bm

**Comment by shirmoran** [comment]
\lgtm

**Pull request merged**
