### PR TITLE
Use Serving 1.3.2 instead of 1.3.0

### PR DESCRIPTION
**Pull request by skonto**
* We use 1.3.2 and generate manifests for that here: https://github.com/openshift-knative/serverless-operator/pull/1598, so let's be accurate for that part so that generated images are available.

### CODE REVIEW

**Review by nak3 — CHANGES_REQUESTED** [review]
Why you need to use 1.3.2 instead of 1.3.0? You just want to align the number?

If upstream release 1.3.3 in the future, you will bump the image tag again?

**Comment by skonto** [comment]
@nak3 I wanted to download the latest manifests.

> If upstream release 1.3.3 in the future, you will bump the image tag again?
I dont feel it is going to be any we are moving to 1.5 today. However, do you suggest to leave it as 1.3.0 and use the manifest for 1.3.0 anyway? I dont want to hardcode anything [here](https://github.com/openshift-knative/serverless-operator/blob/1125e7f6493682ec67adcafb8c0f714c4f27c1b5/openshift-knative-operator/hack/update-manifests.sh#L76) but I could fix the S_O to pick up another namespace for the Serving images instead of using the Serving version in project.yaml.
WDYTH? Then we could keep 1.3.0 forever and manifests still get the right version.

**Comment by nak3** [comment]
> I dont feel it is going to be any we are moving to 1.5 today. However, do you suggest to leave it as 1.3.0 and use the manifest for 1.3.0 anyway? I dont want to hardcode anything [here](https://github.com/openshift-knative/serverless-operator/blob/1125e7f6493682ec67adcafb8c0f714c4f27c1b5/openshift-knative-operator/hack/update-manifests.sh#L76) but I could fix the S_O to pick up another namespace for the Serving images instead of using the Serving version in project.yaml.
WDYTH? Then we could keep 1.3.0 forever and we download the right manifests version.

In most cases, upstream does not change the manifest between the incremental release. So, I don't see any issue we use 1.3.0 manifest because we replace the image. What problem you are concerned?

> At some point we will get the manifests from the midstream repo anyway so this will be temporary so we dont have to download them from upstream and then patch them(check what Eventing is doing here https://github.com/openshift-knative/serverless-operator/pull/1591 which we will eventually folllow).

Well...  They use 1.3.2 instead of the latest tag 1.3.3 https://github.com/knative/eventing/releases/tag/knative-v1.3.3
Sorry for my repeat but if upstream release 1.3.3 in the future, you will bump the image tag as well?

**Comment by skonto** [comment]
> Sorry for my repeat but if upstream release 1.3.3 in the future, you will bump the image tag as well?
Probably I dont see much of an issue.

> In most cases, upstream does not change the manifest between the incremental release. So, I don't see any issue we use 1.3.0 manifest because we replace the image. What problem you are concerned?

In most cases true just trying to make sure I dont hit a corner case anyway.

**Comment by skonto** [comment]
Closing this will use 1.3.0.

**Pull request closed without merging**
