### PR TITLE
Interop - Expand opentelemetry and grafana-tempo on ROSA to 4.17

### PR DESCRIPTION
**Pull request by oharan2**

### CODE REVIEW

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.17-lp-rosa-classic-tempo-rosa-aws periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.17-lp-rosa-classic-opentelemetry-rosa-aws

**Comment by IshwarKanse** [comment]
@oharan2 The josb failed due to cluster provisioning infra issues. I'll retrigger the jobs.

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.17-lp-rosa-classic-tempo-rosa-aws periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.17-lp-rosa-classic-opentelemetry-rosa-aws

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.17-lp-rosa-classic-tempo-rosa-aws periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.17-lp-rosa-classic-opentelemetry-rosa-aws

**Review by IshwarKanse — APPROVED** [review]

**Pull request merged**
