### PR TITLE
Add an SSH bastion

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by hongkailiu** [comment]
the bot does a better job then I did ...
i guess we need to modify RBAC for config-updater ...

**Comment by stevekuznetsov** [comment]
@hongkailiu that's one way in, the other is to set up a reverse tunnel:

```sh
#!/bin/bash

set -o nounset
set -o pipefail
set -o errexit

token="$( oc sa get-token port-forwarder -n bastion --as system:admin )"

function OC() {
	oc --server https://api.ci.openshift.org --token "${token}" --namespace bastion "${@}"
}

function port-forward() {
	while true; do
		echo "[INFO] Setting up port-forwarding..."
		pod="$( OC get pods --selector component=sshd -o jsonpath={.items[0].metadata.name} )"
		if ! OC port-forward "${pod}" 2222; then
			echo "[WARNING] Port-forwarding failed, retrying..."
		fi
	done
}

function ssh-tunnel() {
	while true; do
		echo "[INFO] Setting up SSH tunnelling..."
		if ! ssh -N -T root@127.0.0.1 -p 2222 80:127.0.0.1:8080; then
			echo "[WARNING] SSH tunnelling failed, retrying..."
		fi
	done
}

trap "kill 0" SIGINT

# set up port forwarding from the SSH bastion to the local port 2222
port-forward &

# without a better synchonization library, we just need to wait for the port-forward to run
sleep 5

# run an SSH tunnel from the port 8080 on the SSH bastion (through local port 2222) to local port 80
ssh-tunnel &

for job in $( jobs -p ); do
	wait "${job}"
done
```

**Comment by hongkailiu** [comment]
@stevekuznetsov Are you going to check the shell in?
Just want to ask this before I do copy/paste.

**Comment by stevekuznetsov** [comment]
No, I don't think we will check it in. In general this is a specialized tool to get through firewalls and I don't imagine we (DPTP) need it to access the cluster network or anything similar.

**Comment by stevekuznetsov** [comment]
Screenshot from 2019-09-27 12-02-19

Quick diagram of how this works. Tested and working now.

**Pull request merged**
