### PR TITLE
Expansion of Servicemesh operator on ROSA to OCP4.17

### PR DESCRIPTION
**Pull request by Sau1506mya**

### CODE REVIEW

**Comment by Sau1506mya** [comment]
/pj-rehearse pull-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.17-lp-rosa-classic-images periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.17-lp-rosa-classic-servicemesh-rosa-aws

**Review by Simranpal — COMMENTED** [review]
I noticed the kiali cypress test steps are missing, as well the` kiali-cypress-tests-runner`
Is it excluded in general now or its not included only for ROSA ?

**Pull request merged**
