### PR TITLE
rename regcred secret to registry-pull-credentials 

### PR DESCRIPTION
**Pull request by droslean**
/cc @openshift/openshift-team-developer-productivity-test-platform 

this depends on https://github.com/openshift/ci-tools/pull/1242

```console
$ make jobs
```
NOTE: This PR changes only the jobs that are being managed by prowgen.

Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

### CODE REVIEW

**Review by alvaroaleman — APPROVED** [review]

**Comment by stevekuznetsov** [comment]
Rebasing this will be a PITA, merging

**Pull request merged**
