### PR TITLE
MULTIARCH-4082:Remove control-plane-operator override to fix CCO dynamic link failure for PowerVS e2e CI runs 

### PR DESCRIPTION
**Pull request by Neha-dot-Yadav**
An incident occurred when ART began moving component images from RHEL 8 to RHEL 9.  This caused issues with the HyperShift NodePool controllers, which run in an image built from RHEL 8 (in CI releases), and which attempts to execute dynamically-linked binaries extracted from the` machine-config and cluster-config operator` images.  When those three images have divergent versions of RHEL, e.g. RHEL 9 cluster-config operator images in CI releases, dynamic linking fails like:

  `error getting ignition payload: failed to execute cluster-config-operator: cluster-config-operator process failed: /payloads/get-payload3956907998/bin/cluster-config-operator: /lib64/libc.so.6: version GLIBC_2.32 not found (required by /payloads/get-payload3956907998/bin/cluster-config-operator)\n/payloads/get-payload3956907998/bin/cluster-config-operator: /lib64/libc.so.6: version GLIBC_2.3' not found (required by /payloads/get-payload3956907998/bin/cluster-config-operator)
 `
 In Ignition-serving, which is involved in NodePool validation failed, and CI runs started failing.

 The incident was resolved by making all three operators(`hypershift,cluster-config-operator and machine-config-operator`) of RHEL8.
But, PowerVS e2e runs were still facing the same issue as we were overriding the hypershift-operator with older one from base CI.

This PR fixes this, by removing  `control-plane-operator` passed as an argument while cluster creation.

### CODE REVIEW

**Comment by Neha-dot-Yadav** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-powervs

**Comment by Neha-dot-Yadav** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-powervs

**Comment by dharaneeshvrd** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-powervs

**Comment by Neha-dot-Yadav** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-powervs

**Comment by Neha-dot-Yadav** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-powervs

**Comment by dharaneeshvrd** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-powervs

**Pull request merged**
