### PR TITLE
Add additional JVM Build Service test

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
@psturc this should be good to go now

**Comment by psturc** [comment]
@stuartwdouglas ok cool let's give it a try

/pj-rehearse pull-ci-redhat-appstudio-jvm-build-service-main-jvm-build-service-in-repo-quickstarts-e2e

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-jvm-build-service-main-jvm-build-service-in-repo-jbs-e2e pull-ci-redhat-appstudio-jvm-build-service-main-jvm-build-service-in-repo-wildfly-e2e

**Comment by psturc** [comment]
failed on installing rbac (before the cluster install even started)
/pj-rehearse pull-ci-redhat-appstudio-jvm-build-service-main-jvm-build-service-in-repo-quickstarts-e2e pull-ci-redhat-appstudio-jvm-build-service-main-jvm-build-service-in-repo-jbs-e2e pull-ci-redhat-appstudio-jvm-build-service-main-jvm-build-service-in-repo-wildfly-e2e

**Comment by psturc** [comment]
@stuartwdouglas 2/3 jobs failed, please take a look at results if it's something that should be addressed

**Comment by stuartwdouglas** [comment]
/pj-rehearse pull-ci-redhat-appstudio-jvm-build-service-main-jvm-build-service-in-repo-quickstarts-e2e pull-ci-redhat-appstudio-jvm-build-service-main-jvm-build-service-in-repo-jbs-e2e pull-ci-redhat-appstudio-jvm-build-service-main-jvm-build-service-in-repo-wildfly-e2e

**Comment by stuartwdouglas** [comment]
Weirdly these jobs seem to be trigger the race that I thought I had fixed where the state + counts get out of sync, it still thinks one is building and times out even though the jobs are done.

**Comment by stuartwdouglas** [comment]
So I think we should just merge this, and I can work on the issues in the JBS repository. We are still getting good data about what does or does not build out of the tests, it is just not reporting the result correctly at the end.

**Comment by gabemontero** [comment]
per slack convo with @stuartwdouglas I'll tag this for merge and he can deal with the e2e's on the jvm-build-service etc. side

/pj-rehearse ack

**Comment by psturc** [comment]
I'm not really sure why all the required checks are stuck on "Pending" state
/retest

**Comment by psturc** [comment]
@stuartwdouglas I think this could be some issue on openshift-ci side - could you force-push to this branch to trigger required tests again?

**Comment by stuartwdouglas** [comment]
I have force pushed

**Comment by psturc** [comment]
strange errors... @stuartwdouglas  could you try to rebase, run `make jobs && make prow-config && make ci-operator-config` and push again?

**Pull request merged**
