### PR TITLE
add odh-model-controller

### PR DESCRIPTION
**Pull request by Jooho**
This will include odh-model-controller repo to openshift-ci

### CODE REVIEW

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-model-controller-main-fvt pull-ci-opendatahub-io-odh-model-controller-main-unit

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-model-controller-main-fvt

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-model-controller-main-fvt pull-ci-opendatahub-io-odh-model-controller-main-unit

**Comment by Jooho** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-model-controller-main-fvt

**Review by Xaenalt — APPROVED** [review]

**Pull request merged**
