### PR TITLE
machine-approver: use multistep job for e2e-upgrade

### PR DESCRIPTION
**Pull request by vrutkovs**
Run AWS upgrade using multistep, persist metrics and store container logs using Loki

### CODE REVIEW

**Comment by vrutkovs** [comment]
/retest

4.6 is still failing

**Review by elmiko — COMMENTED** [review]
this mostly makes sense to me, @vrutkovs could you help me understand why the changes from aws->azure and azure->gcp ?

**Comment by vrutkovs** [comment]
>could you help me understand why the changes from aws->azure and azure->gcp ?
>(am i just seeing an artifact of these files be generated by a tool or something)

Jobs are autogenerated and alphabetically sorted, so due to `e2e-aws-upgrade` -> `e2e-upgrade` rename the diff shows as if azure/gcp have been updated, but these have just been moved to the top

**Comment by elmiko** [comment]
thanks for the explanation @vrutkovs 
/lgtm

**Comment by elmiko** [comment]
/hold
do we need to wait for the rehearse jobs to succeed?

**Comment by vrutkovs** [comment]
Test history shows 4.5/4.6/master passed at least once. 4.7 is broken everywhere until a payload is created (its not being run anywhere though). I could start a few more retests, but CI won't retain success runs.

/hold cancel

**Pull request merged**
