### PR TITLE
Set worker count to WORKER_REPLICAS

### PR DESCRIPTION
**Pull request by manojnkumar**
worker count was set to 2 earlier.  Setting it back.

### CODE REVIEW

**Comment by mkumatag** [comment]
@jaypoulz we need this patch to deploy proper number of workers on ppc64le platform

**Comment by mandre** [comment]
/approve
Seems like the OpenStack team is the only one able to approve this change in this timezone, @mkumatag asked me to review the patch to unblock CI. LGTM.

**Comment by jaypoulz** [comment]
Good catch. It was accidentally broken in the terraform master upgrade patch. :)

**Pull request merged**
