### PR TITLE
revert preserving bootstrap node on SNO ipi builds

### PR DESCRIPTION
**Pull request by osherdp**
Reverts #20592
/cc @deads2k @eranco74 
/hold

I do think we didn't yet got the chance to use the artifacts (the bug is reproducing once a week or two), but let's have the revert ready for now and start thinking about our options.

### CODE REVIEW

**Comment by deads2k** [comment]
/lgtm
/approve
/hold

holding until 8/19.  On 8/19, it is time to revert the change.  If it's been more than two weeks, it's highly suggestive that we need a product change to enable debugging in the field.

**Comment by eranco74** [comment]
The issue didn't reproduce since the preserved bootstrap PR merged.

**Pull request merged**
