### PR TITLE
Add kubevirt/ssp-operator

### PR DESCRIPTION
**Pull request by akrejcir**
Run `make new-repo` for https://github.com/kubevirt/ssp-operator

### CODE REVIEW

**Review by omeryahud — APPROVED** [review]
/lgtm
/approve

**Comment by omeryahud** [comment]
/assign @bbguimaraes Hi Bruno, would appreciate your review and approval.
We expect the rehearsal job to fail, as we still have changes we have to make on our master branch.

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
