### PR TITLE
updated to skip doc test

### PR DESCRIPTION
**Pull request by amit-62**
This PR is against issue [#6500](https://github.com/cri-o/cri-o/issues/6500)

### CODE REVIEW

**Comment by amit-62** [comment]
Please suggest improvement if any.

**Comment by sohankunkerkar** [comment]
you might need to generate a new config using ` make jobs`

**Comment by amit-62** [comment]
Hi @sohankunkerkar I have generated new config using `make jobs` but there is an error stating that `always_run:true` and `skip_if_only_changed:` is mutually exclusive. Please help me to solve it.

**Comment by haircommander** [comment]
the docs seem to say that we can drop `always_run` and `skip_if_only_changed` will take its place (and run the tests in all cases except those listed in the regex)

**Comment by amit-62** [comment]
Thank you @haircommander. Should I drop `always_run`. If it is set to false then it will not run automatically against all PRs.

**Comment by haircommander** [comment]
> Thank you @haircommander. Should I drop always_run. If it is set to false then it will not run automatically against all PRs.

I think you can drop it. If it's false, the condition `skip_if_only_changed` will inform when to run the jobs

**Comment by amit-62** [comment]
@haircommander I had removed `always_run` but `make jobs` automatically set it to false.

**Comment by haircommander** [comment]
> @haircommander I had removed `always_run` but `make jobs` automatically set it to false.

fine with me!

/lgtm

**Comment by haircommander** [comment]
/rehearsals-ack

well done with the investigation here, thanks for your work @amit-62!

**Comment by amit-62** [comment]
> /rehearsals-ack
> 
> well done with the investigation here, thanks for your work @amit-62!

Thank you @haircommander.

**Pull request merged**
