### PR TITLE
Add a test job for the RC trigger

### PR DESCRIPTION
**Pull request by calebevans**
Adding temporary test job to test the RC trigger

### CODE REVIEW

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-rhpit-interop-tests-main-test-rc-trigger-test

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-rhpit-interop-tests-main-test-rc-trigger-test

**Review by Simranpal — APPROVED** [review]
/lgtm

**Pull request merged**
