### PR TITLE
OCPBUGS-42295: cert-rotation: additional fixes

### PR DESCRIPTION
**Pull request by vrutkovs**
* Ensure that node readiness is run silently to avoid spamming the logs
* Fix version detection in pod-restart-workarounds
* Re-add Multus restart workaround due to https://issues.redhat.com/browse/OCPBUGS-42001
*  Extend minimum stable period and sleep before shutdown
    This ensures that operator status has been updated after shutdown. Fixes https://issues.redhat.com/browse/OCPBUGS-42295

### CODE REVIEW

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-suspend-180d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-suspend-180d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-180d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-suspend-180d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-suspend-180d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-180d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-180d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-180d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-180d

**Comment by ardaguclu** [comment]
This looks good to me, feel free to unhold anytime you want to merge;
/lgtm
/hold

**Pull request merged**
