### PR TITLE
Remove 871 network from devqe profile

### PR DESCRIPTION
**Pull request by sgaoshang**
Remove 871 network

We found dis-connected network can not access 871 network, so remove it temporarily until the issue resolved.
Details see https://issues.redhat.com/browse/DPP-14576

### CODE REVIEW

**Comment by sgaoshang** [comment]
@jinyunma @jianlinliu Pls help to review it, thanks. cc: @WenXinWei

**Comment by jinyunma** [comment]
> We found dis-connected network can not access 871 network

I think the issue is that the connection is unavailable from pod in CI build cluster to subnet 871, see this [failed job](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-stable-vsphere-ipi-disc-f14/1776282536473792512), ssh connection timeout when bastion is provisioned in subnet 871 on devqe vsphere.

**Comment by sgaoshang** [comment]
@hongkailiu Hello, could you help to approve it? Thanks.

**Pull request merged**
