### PR TITLE
Updating to use e2e v2.1.7

### PR DESCRIPTION
**Pull request by vishnuchalla**
### Description
Updating e2e-benchmarking to v2.1.7 for perfscale jobs.

### Testing
Will be tested with few runs in this PR.
Tested at e2e-benchmarking repo level: https://github.com/cloud-bulldozer/e2e-benchmarking/pull/695

### CODE REVIEW

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-control-plane-120nodes

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-nightly-arm-control-plane-24nodes

**Comment by jtaleric** [comment]
> @vishnuchalla: now processing your pj-rehearse request. Please allow up to 10 minutes for jobs to trigger or cancel.

Curious why it never kicked off?

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-nightly-arm-control-plane-24nodes

**Comment by vishnuchalla** [comment]
> > @vishnuchalla: now processing your pj-rehearse request. Please allow up to 10 minutes for jobs to trigger or cancel.
> 
> Curious why it never kicked off?

Looks like some flaky issue in PROW. It got triggered now.

**Pull request merged**
