### PR TITLE
openstack: Remove confusing "minimal" workflow

### PR DESCRIPTION
**Pull request by pierreprinetti**
The current "openshift-e2e-openstack-minimal" workflow does not run a
minimal set of tests: it does not run ANY test. It just installs.

To avoid further confusion (and unnecessary duplication), this change
removes this "minimal" workflow.

Jobs that actually need not to run any test are modified to use the
regular OpenStack workflow "openshift-e2e-openstack-ipi" and to override
the test step with a no-op step.

### CODE REVIEW

**Comment by pierreprinetti** [comment]
The step ref yaml file has the wrong name (should end in -ref). Will get back to it.

**Comment by pierreprinetti** [comment]
This is ready for review.

**Review by mandre — COMMENTED** [review]
Nice improvement, it's indeed a lot clearer.
/lgtm

**Comment by dulek** [comment]
I think @MaysaMacedo should take a look here.

To me it's fine, I just need to see that one last job working.

**Comment by MaysaMacedo** [comment]
Looks good. I see there is another [workflow](https://github.com/openshift/release/blob/master/ci-operator/step-registry/ipi/openstack/ipi-openstack-workflow.yaml) with default installing and deprovision, would it make sense to remove since is not used anywhere?

**Pull request merged**
