### PR TITLE
OSASINFRA-3396: openstack: Add altinfra CAPI optional presubmits

### PR DESCRIPTION
**Pull request by pierreprinetti**
And also:
* move openstack-e2e-capi-ovn to the main cloud (which has Octavia enabled).
* instrument openstack-test-manifests with feature sets and gates

### CODE REVIEW

**Comment by pierreprinetti** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.7-openstack-manifests

This is the only test susceptible to succeed on the master branch.

**Comment by pierreprinetti** [comment]
/pj-rehearse pull-ci-openshift-installer-master-altinfra-openstack-capi-manifests

THIS is the test I wanted to trigger, not the one on 4.7

**Review by mandre — COMMENTED** [review]
/lgtm

**Review by r4f4 — COMMENTED** [review]
/approve

But I'd like us to revisit how we specify feature gates so it's consistent across workflows.

**Pull request merged**
