### PR TITLE
Add cluster role system:registry that can use layers API

### PR DESCRIPTION
**Pull request by dmage**
This role is needed within the task [DEVEXP-244](https://jira.coreos.com/browse/DEVEXP-244).

### CODE REVIEW

**Comment by smarterclayton** [comment]
So 3.11 didn’t ship with the right rbac role?  If you merged a change to release-3.11 to fix it we can just pull the latest onto the masters and restart.

**Comment by bparees** [comment]
> So 3.11 didn’t ship with the right rbac role? If you merged a change to release-3.11 to fix it we can just pull the latest onto the masters and restart.

@dmage i thought you already did that for 3.11 but i'm not seeing the PR?

**Comment by dmage** [comment]
@bparees no, I thought that's an experimental feature and we don't want to enable it by default in 3.11.

**Comment by dmage** [comment]
https://github.com/openshift/origin/pull/22044

**Comment by bparees** [comment]
As @dmage reminded me, this api was experimental in 3.11.  I'd rather test it out in our CI cluster first, before we send it out to all our customers in an errata release. (since apparently it never went through real QE since it wasn't usable due to rbac rules)

so we can we patch the CI cluster first and see if things look stable?

**Comment by smarterclayton** [comment]
Sure.

**Comment by bparees** [comment]
@smarterclayton noted that this is missing List permissions on imagstreams I think, so before it gets reopened and merged, the role definition needs to be double checked against 3.11 and api.ci.

here's what api.ci is using right now (after @smarterclayton added the layers api permission manually):

```
apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  annotations:
    authorization.openshift.io/system-only: "true"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{"authorization.openshift.io/system-only":"true","openshift.io/reconcile-protect":"true","rbac.authorization.kubernetes.io/autoupdate":"true"},"name":"system:registry"},"rules":[{"apiGroups":[""],"resources":["imagestreams","limitranges","resourcequotas"],"verbs":["list"]},{"apiGroups":["","image.openshift.io"],"resources":["images","imagestreamtags"],"verbs":["delete","get"]},{"apiGroups":["","image.openshift.io"],"resources":["imagestreamimages","imagestreams/layers","imagestreams/secrets"],"verbs":["get"]},{"apiGroups":["","image.openshift.io"],"resources":["images","imagestreams"],"verbs":["get","update"]},{"apiGroups":["","image.openshift.io"],"resources":["imagestreammappings"],"verbs":["create"]}]}
    openshift.io/reconcile-protect: "false"
  creationTimestamp: 2019-02-20T17:51:19Z
  name: system:registry
  resourceVersion: "75790673"
  selfLink: /apis/authorization.openshift.io/v1/clusterroles/system%3Aregistry
  uid: 2095e834-3538-11e9-9e67-42010a8e0002
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - imagestreams
  - limitranges
  - resourcequotas
  verbs:
  - list
- apiGroups:
  - ""
  - image.openshift.io
  attributeRestrictions: null
  resources:
  - images
  - imagestreamtags
  verbs:
  - delete
  - get
- apiGroups:
  - ""
  - image.openshift.io
  attributeRestrictions: null
  resources:
  - imagestreamimages
  - imagestreams/layers
  - imagestreams/secrets
  verbs:
  - get
- apiGroups:
  - ""
  - image.openshift.io
  attributeRestrictions: null
  resources:
  - images
  - imagestreams
  verbs:
  - get
  - update
- apiGroups:
  - ""
  - image.openshift.io
  attributeRestrictions: null
  resources:
  - imagestreammappings
  verbs:
  - create
```

**Comment by dmage** [comment]
@bparees @smarterclayton the registry doesn't need to list imagestreams. And the current permission is not for the api group "image.openshift.io".

**Comment by bparees** [comment]
> @bparees @smarterclayton the registry doesn't need to list imagestreams. And the current permission is not for the api group "image.openshift.io".

Both good points, I didn't see the error that @smarterclayton got, but he mentioned it here:
https://coreos.slack.com/archives/CBN38N3MW/p1550685094053500?thread_ts=1550574247.369800&cid=CBN38N3MW

**Pull request closed without merging**
