### PR TITLE
enable ci for openshift/kube-storage-version-migrator

### PR DESCRIPTION
**Pull request by sanchezl**
New repo in support of [storage-migration-for-etcd-encryption](https://github.com/openshift/enhancements/blob/master/enhancements/etcd/storage-migration-for-etcd-encryption.md).

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
FYI you are better off to assign @openshift/openshift-team-developer-productivity-test-platform 

Do you want merging, as well?

**Comment by sanchezl** [comment]
> FYI you are better off to assign @openshift/openshift-team-developer-productivity-test-platform
> 
> Do you want merging, as well?

I've opened https://github.com/openshift/release/pull/5284 to enable merging.

**Pull request merged**
