### PR TITLE
[MGMT-10097] - Revert "MGMT-15398: Pull multi-arch images from brew in AI arm job (#…

### PR DESCRIPTION
**Pull request by eifrach**
- reverting back to use postsumbit images

### CODE REVIEW

**Review by adriengentil — APPROVED** [review]

**Comment by eifrach** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-day2-arm-workers-periodic

**Comment by eifrach** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-day2-arm-workers-periodic

**Pull request merged**
