### PR TITLE
OCPQE-20304 update release settings

### PR DESCRIPTION
**Pull request by dis016**
[OCPQE-20304](https://issues.redhat.com//browse/OCPQE-20304) update release setting for n-1 to n upgrade in dev preview

### CODE REVIEW

**Comment by dis016** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-stable-4.16-upgrade-from-stable-4.16-aws-ipi-disc-priv-tp-f28

**Comment by dis016** [comment]
`INFO[2024-04-08T10:31:53Z] Resolved release latest to quay.io/openshift-release-dev/ocp-release:4.16.0-ec.3-x86_64 
INFO[20[24](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/50691/rehearse-50691-periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-stable-4.16-upgrade-from-stable-4.16-aws-ipi-disc-priv-tp-f28/1777283174267621376#1:build-log.txt%3A24)-04-08T10:31:53Z] Importing release image target.              
INFO[2024-04-08T10:31:53Z] Requesting a release from https://amd64.ocp.releases.ci.openshift.org/api/v1/releasestream/4-dev-preview/latest?in=%3E4.16.0-0+%3C4.17.0-0 
INFO[2024-04-08T10:31:53Z] Resolved release target to quay.io/openshift-release-dev/ocp-release:4.16.0-ec.4-x86_64`

**Comment by JianLi-RH** [comment]
/lgtm

Thank you @dis016

**Comment by shellyyang1989** [comment]
Good job Dinesh! Thank you.

**Pull request merged**
