### PR TITLE
o/cluster-network-operator: cleanup template jobs

### PR DESCRIPTION
**Pull request by petr-muller**
Followup to https://github.com/openshift/release/pull/13975

4.4: ~~Existing jobs were migrated to matching multi-stage ones~~ only OVN jobs were migrated, not multitenant, as the 4.4 multitenant job turned out to be problematic.
4.6: Already has matching multi-stage job, so the handcrafted on can be deleted:
https://github.com/openshift/release/blob/d129aa1662c1d0f0b5e3884cac1e334c44e73637/ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.6.yaml#L78-L85
4.7: Already have matching multi-stage jobs, handcrafted ones can be deleted:
https://github.com/openshift/release/blob/d129aa1662c1d0f0b5e3884cac1e334c44e73637/ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.7.yaml#L83-L90
https://github.com/openshift/release/blob/d129aa1662c1d0f0b5e3884cac1e334c44e73637/ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.8.yaml#L82-L89

### CODE REVIEW

**Comment by petr-muller** [comment]
I'm not seeing great results of moving the multitenant jobs to the workflow even in other repos (origin: https://github.com/openshift/release/pull/14214 sdn: https://github.com/openshift/release/pull/14213 kubernetes: https://github.com/openshift/release/pull/14212) so I think I will just leave that job out of this PR, proceed with the rest and file a blocker for _someone_ to look at the multitenant workflow.

**Comment by petr-muller** [comment]
Let's leave the 4.4 multi-tenant job out for now. For some reason it consistently passes as a [template job](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/rehearse-14180-pull-ci-openshift-cluster-network-operator-release-4.4-e2e-aws-multitenant) but consisntently fails as [multi-stage job](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/rehearse-14050-pull-ci-openshift-cluster-network-operator-release-4.4-e2e-aws-multitenant) and I don't know why that could be.

**Comment by petr-muller** [comment]
build02 hates me today (being upgraded)

/retest

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
