### PR TITLE
Add a separate workflow for each of the agent based installation topologies

### PR DESCRIPTION
**Pull request by mhanss**
[AGENT-680](https://issues.redhat.com/browse/AGENT-680)

### CODE REVIEW

**Comment by mhanss** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-vsphere-agent-disconnected-compact-p2-f14

**Comment by mhanss** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-vsphere-agent-disconnected-compact-p2-f14

**Comment by mhanss** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-vsphere-agent-sno-p2-f14

**Review by bmanzari — APPROVED** [review]

**Pull request merged**
