### PR TITLE
Update sippy base and build images to ubi:8

### PR DESCRIPTION
**Pull request by stbenjam**
In order to build the frontend, we need npm from the ubi:8 repos.

Needs https://github.com/openshift/sippy/pull/254

### CODE REVIEW

**Comment by bparees** [comment]
/approve
/lgtm

/hold

@stbenjam remove the hold once the other PR merges and you get successful rehearsals

**Comment by stbenjam** [comment]
Should be good now, I had to fix something - @bparees Can you lgtm again?

/hold cancel

**Pull request merged**
