### PR TITLE
OCM: remove approving GH review for grc

### PR DESCRIPTION
**Pull request by ycao56**
Signed-off-by: Yu Cao <ycao@redhat.com>

### CODE REVIEW

**Review by ChunxiAlexLuo — APPROVED** [review]
/lgtm

**Review by ChunxiAlexLuo — APPROVED** [review]
/lgtm

**Comment by ycao56** [comment]
/assign @alvaroaleman
Can you review and approve?

**Comment by alvaroaleman** [comment]
@ycao56 who is supposed to be able to approve changes like this for the open cluster management github org? Please add those ppl to an OWNERS file in `core-services/prow/02_config/open-cluster-management/`, I can not tell in any way if this is correct, just that it is a valid config (but the presubmit tells the same)/

**Comment by alvaroaleman** [comment]
@ycao56 also, all of these repos have owners. Please make all the repo owners approve your change instead of dptp. We can not tell you if this is the correct config.
/unassign
/uncc
/unassign @petr-muller

**Comment by ycao56** [comment]
> @ycao56 who is supposed to be able to approve changes like this for the open cluster management github org? Please add those ppl to an OWNERS file in `core-services/prow/02_config/open-cluster-management/`, I can not tell in any way if this is correct, just that it is a valid config (but the presubmit tells the same)/

@alvaroaleman I added an OWNER file to this PR. Can you check if this is ok? How can we move forward to merge this pr? I assume the owners in the list can only approve after this is merged. correct?

**Comment by alvaroaleman** [comment]
>  I assume the owners in the list can only approve after this is merged. correct?

Yes.

You can move forward with this PR by finding the owners for all the repos and making them approve it. All of the folders in core-services/prow/02_config/open-cluster-management/$repo have an OWNERS file already.

**Comment by ycao56** [comment]
@ChunxiAlexLuo has already approved the p in https://github.com/openshift/release/pull/18560#issuecomment-840565033r. He is the owner of repos this PR modifies.

**Comment by ycao56** [comment]
@alvaroaleman tide doesn't seem to honor the approval from @arewm @ChunxiAlexLuo . Is there anything missing?

**Comment by alvaroaleman** [comment]
@ycao56 @ChunxiAlexLuo is not an owner of anything, no:
```
openshift/release
$ rg ChunxiAlexLuo|wc -l
0
```

and @arewm is only an owner of the image builder repo:
```
$ rg arewm  core-services/prow/02_config/
core-services/prow/02_config/open-cluster-management/image-builder/OWNERS
5:- arewm
14:- arewm
```

If you dont want to run after everyone, that is fine. But then do not change everyones config.

**Pull request merged**
