### PR TITLE
enable prow-monitoring deploy in postsubmit updates

### PR DESCRIPTION
**Pull request by droslean**

### CODE REVIEW

**Comment by hongkailiu** [comment]
This is fine with me. I will let @stevekuznetsov to give the final call.

**Comment by petr-muller** [comment]
Just curious, what's the reason?

**Comment by droslean** [comment]
we add extra datasources that are using a `basicAuthPassword` which we get from `openshift-monitoring` namespace. We can't hardcode the secret in the configmap in order to use it via the config_updater.

**Comment by droslean** [comment]
check #3939

**Comment by stevekuznetsov** [comment]
So just change the data sources file?

**Comment by stevekuznetsov** [comment]
Instead of all this. It's nice to see the comment verification that things got updated

**Pull request merged**
