### PR TITLE
fix: change node type for managed-api to fix issue around resources

### PR DESCRIPTION
**Pull request by jjkiely**
## What
Change managed-api-service configuration for clusters to avoid resource issues, and update "addon-managed-api-service" parameter to match new values for that parameter

### CODE REVIEW

**Comment by makslion** [comment]
Shouldn't 5 workers be enough for a 1 million quota? :thinking:

**Comment by jjkiely** [comment]
@makslion for each node we have approximately 1.5 vCPU is taken up by things other than the RHOAM installation, so we need an extra node so that we meet the requirements once the overhead is taken into account

**Comment by makslion** [comment]
So 4 needed +1 extra = 5? :thinking: 
m5.xlarge has 4 vCPUs if to believe to Google. 1.5 for other components would leave us with 2.5 for RHOAM. The [sevice definition](https://access.redhat.com/articles/5534341) suggests 1M quota having 11 vCPUs what leads to 11/2.5 ≈ 5 workers :thinking: 
I'm trying to save that money like they my own :thinking:

**Comment by makslion** [comment]
I've been convinced that we need 6 workers, so

/lgtm

**Comment by makslion** [comment]
/lgtm

I've been convinced that we need 6 workers

**Comment by makslion** [comment]
I have no power here :disappointed:

**Comment by jjkiely** [comment]
Hey @jeefy if you get the chance could lgtm and approve this PR, it's already gone through our review process, but @makslion did not have permissions to leave an lgtm , thanks!

**Pull request merged**
