### PR TITLE
Use OCP 4.13 clusters for testing CaC/content

### PR DESCRIPTION
**Pull request by Vincent056**
This commit updates the cluster version to use OCP 4.13 so
we ensure our contents works on newer OCP release

### CODE REVIEW

**Comment by Vincent056** [comment]
/pj-rehearse pull-ci-ComplianceAsCode-content-master-e2e-aws-rhcos4-high

**Comment by Vincent056** [comment]
we need to wait until https://github.com/ComplianceAsCode/content/pull/10265 is merged

**Comment by Vincent056** [comment]
/pj-rehearse ci/rehearse/ComplianceAsCode/content/master/e2e-aws-ocp4-high-node

**Comment by Vincent056** [comment]
/pj-rehearse pull-ci-ComplianceAsCode-content-master-e2e-aws-ocp4-high
--


<br class="Apple-interchange-newline">

**Review by jhrozek — APPROVED** [review]
/lgtm
woo, clear tests!

**Pull request merged**
