### PR TITLE
Revert "Add new tag kubernetes.io/role/elb for public subnet"

### PR DESCRIPTION
**Pull request by yunjiang29**
* Reverts openshift/release#41411
* Support getting `infra_id` from managed cluster

OCM will add a separate step to add tags to meet their requirement.

### CODE REVIEW

**Comment by yunjiang29** [comment]
@jianlinliu PTAL.

**Comment by yunjiang29** [comment]
Waiting for new OCM implementation  get merged  https://github.com/openshift/release/pull/41620

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-rosa-sts-hypershift-guest-p1-f7

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-devpreview-aws-usgov-ipi-private-workers-marketplace-f28-destructive

**Comment by yasun1** [comment]
@yunjiang29 The provision steps which is used to validate the changes have been passed for the OCP and rosa hypershift clusters.  I think the PR is ready for merge now. 

@jianlinliu Need your LGTM again. ^^

**Comment by yunjiang29** [comment]
## test
OCP: 
https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/41664/rehearse-41664-periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-devpreview-aws-usgov-ipi-private-workers-marketplace-f28-destructive/1684451772015316992/artifacts/aws-usgov-ipi-private-workers-marketplace-f28-destructive/aws-provision-tags-for-byo-vpc/build-log.txt
```
Reading infra id from file metadata.json
infra_id: ci-op-szdbvdpn-11fa4-vnht2
Adding tags for VPC: vpc-0aa982b5fe726120c, tags: kubernetes.io/cluster/ci-op-szdbvdpn-11fa4-vnht2, value: shared.
Adding tags for private subnets:subnet-0f1229f349a6d24b0 subnet-0fd7196c8292898a2 subnet-0d95f2b5de6370539, tags: kubernetes.io/role/internal-elb, value is empty.
```

**Pull request merged**
