### PR TITLE
fix: update the image_stream_tag to use correct golang version for PowerMon(Kepler)

### PR DESCRIPTION
**Pull request by vprashar2929**
This updates the image_stream_tag to use `rhel-8-golang-1.21-openshift-4.16` for PowerMon(Kepler) job

### CODE REVIEW

**Comment by vprashar2929** [comment]
/pj-rehears pull-ci-openshift-power-monitoring-kepler-main-kepler-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-kepler-main-kepler-e2e

**Review by IshwarKanse — APPROVED** [review]
/lgtm

**Pull request merged**
