### PR TITLE
Add configs for certified operator preflight jobs

### PR DESCRIPTION
**Pull request by mrhillsman**
Signed-off-by: Melvin Hillsman <mhillsma@redhat.com>

### CODE REVIEW

**Comment by mrhillsman** [comment]
/pj-rehearse periodic-ci-redhat-openshift-ecosystem-preflight-ocp-4.12-preflight-common-claim periodic-ci-redhat-openshift-ecosystem-certified-operators-prod-ocp-4.12-preflight-prod-claim periodic-ci-redhat-openshift-ecosystem-certified-operators-preprod-ocp-4.12-preflight-preprod-claim

**Review by acornett21 — APPROVED** [review]

**Review by acornett21 — APPROVED** [review]

**Comment by mrhillsman** [comment]
/pj-rehearse periodic-ci-redhat-openshift-ecosystem-preflight-ocp-4.12-preflight-common-claim periodic-ci-redhat-openshift-ecosystem-certified-operators-prod-ocp-4.12-preflight-prod-claim periodic-ci-redhat-openshift-ecosystem-certified-operators-preprod-ocp-4.12-preflight-preprod-claim periodic-ci-redhat-openshift-ecosystem-preflight-ocp-4.13-preflight-common-claim periodic-ci-redhat-openshift-ecosystem-certified-operators-prod-ocp-4.13-preflight-prod-claim periodic-ci-redhat-openshift-ecosystem-certified-operators-preprod-ocp-4.13-preflight-preprod-claim periodic-ci-redhat-openshift-ecosystem-preflight-ocp-4.14-preflight-common-claim periodic-ci-redhat-openshift-ecosystem-certified-operators-prod-ocp-4.14-preflight-prod-claim periodic-ci-redhat-openshift-ecosystem-certified-operators-preprod-ocp-4.14-preflight-preprod-claim

**Pull request merged**
