### PR TITLE
SPLAT-1126: installer/networking/mtu cleaning gate and SDN jobs

### PR DESCRIPTION
**Pull request by mtulio**
- Cleaning the gate feature after aligned with Patrick for Slack for FF. More details in PR https://github.com/openshift/installer/pull/7765
- removing OpenShiftSDN as it will not be supported for new installs 4.15+

/assign @r4f4 @patrickdillon

### CODE REVIEW

**Comment by mtulio** [comment]
As per @makentenza comment, the OpenShiftSDN will be removed from installer 4.15, I will remove the tests on it too.
/hold

**Review by r4f4 — COMMENTED** [review]
/approve

**Review by vrutkovs — APPROVED** [review]

**Pull request merged**
