### PR TITLE
MGMT-13577: Dynamically select disk on m3.large

### PR DESCRIPTION
**Pull request by adriengentil**
It looks like equinix metal provide new hardware for m3.large, and our
assumption that `/dev/nvme0n1` is an available disk is now wrong.

This change looks dynamically for the largest available disk available
and use it.

### CODE REVIEW

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-static-ip-suite

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-odf pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-ocs

**Review by osherdp — APPROVED** [review]

**Comment by adriengentil** [comment]
Looks good! Letting the job finish...
```
# lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
nvme0n1     259:0    0 238.5G  0 disk 
├─nvme0n1p1 259:2    0   512M  0 part /boot/efi
├─nvme0n1p2 259:3    0   1.9G  0 part [SWAP]
└─nvme0n1p3 259:4    0 236.1G  0 part /
nvme1n1     259:1    0 238.5G  0 disk 
nvme3n1     259:5    0   3.5T  0 disk 
nvme2n1     259:6    0   3.5T  0 disk /home/assisted
```

**Pull request merged**
