### PR TITLE
Adjustements to the ossm sail fork

### PR DESCRIPTION
**Pull request by jwendell**

### CODE REVIEW

**Comment by jwendell** [comment]
/pj-rehearse periodic-ci-openshift-service-mesh-sail-operator-pre-main-sync-upstream

**Comment by jwendell** [comment]
/pj-rehearse periodic-ci-openshift-service-mesh-sail-operator-pre-main-sync-upstream

**Comment by jwendell** [comment]
/pj-rehearse periodic-ci-openshift-service-mesh-sail-operator-pre-main-sync-upstream

**Review by luksa — APPROVED** [review]

**Pull request merged**
