### PR TITLE
test if obs image is updated

### PR DESCRIPTION
**Pull request by ascerra**

### CODE REVIEW

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-ascerra-clc-ui-e2e-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-ascerra-clc-ui-e2e-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by vboulos** [comment]
/pj-rehearse periodic-ci-ascerra-clc-ui-e2e-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-ascerra-clc-ui-e2e-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-ascerra-clc-ui-e2e-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-ascerra-clc-ui-e2e-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-ascerra-clc-ui-e2e-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-ascerra-clc-ui-e2e-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-ascerra-clc-ui-e2e-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-ascerra-clc-ui-e2e-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-ascerra-clc-ui-e2e-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-ascerra-clc-ui-e2e-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by vboulos** [comment]
/pj-rehearse periodic-ci-ascerra-clc-ui-e2e-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-ascerra-clc-ui-e2e-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-ascerra-clc-ui-e2e-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-ascerra-clc-ui-e2e-main-acm-ocp4.12-lp-interop-acm-interop-aws

**Pull request closed without merging**
