### PR TITLE
openstack/gather: add support for volumes

### PR DESCRIPTION
**Pull request by EmilienM**
Gather volumes infos as well, for debug purposes.

### CODE REVIEW

**Comment by EmilienM** [comment]
/ph-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.14-e2e-openstack-kuryr

**Comment by EmilienM** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.14-e2e-openstack-kuryr

**Comment by EmilienM** [comment]
/hold
not working yet

**Comment by EmilienM** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-openstack-kuryr

**Review by mandre — COMMENTED** [review]
Looks good at first glance. Let's wait for CI to return so see if it was able to gather the volume info.

**Review by mandre — COMMENTED** [review]
/lgtm

The step was able to capture volumes info on the last run:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/41450/rehearse-41450-pull-ci-openshift-installer-master-e2e-openstack-kuryr/1681851517339963392/artifacts/e2e-openstack-kuryr/openstack-gather/artifacts/openstack_volumes.log

**Pull request merged**
