### PR TITLE
Add job to deploy with bonds

### PR DESCRIPTION
**Pull request by creydr**
Add a job to dev-scripts to run the common baremetal e2e test suite with a bond primary interface

### CODE REVIEW

**Comment by creydr** [comment]
dev-scripts created the bond:
```
[core@master-0 ~]$ cat /proc/net/bonding/bond0 
Ethernet Channel Bonding Driver: v3.7.1 (April 27, 2011)

Bonding Mode: fault-tolerance (active-backup)
Primary Slave: None
Currently Active Slave: enp2s0
MII Status: up
MII Polling Interval (ms): 100
Up Delay (ms): 0
Down Delay (ms): 0
Peer Notification Delay (ms): 0

Slave Interface: enp2s0
MII Status: up
Speed: Unknown
Duplex: Unknown
Link Failure Count: 0
Permanent HW addr: 00:91:4f:6e:11:08
Slave queue ID: 0

Slave Interface: enp3s0
MII Status: up
Speed: Unknown
Duplex: Unknown
Link Failure Count: 0
Permanent HW addr: 00:91:4f:6e:11:08
Slave queue ID: 0
```

**Comment by dougsland** [comment]
LGTM

**Comment by derekhiggins** [comment]
> I guess that's fine since this is not set up to run except when explicitly requested, but we still need to find a better way to integrate it into our ci.

How about adding it to the serial virtualmedia jobs e.g.
https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.12-e2e-metal-ipi-sdn-serial-virtualmedia

**Pull request merged**
