### PR TITLE
MetalLB / Operator: align build root to rhel9

### PR DESCRIPTION
**Pull request by fedepaol**
Aligning build root to rhel9 as art does

### CODE REVIEW

**Comment by fedepaol** [comment]
/pj-rehearse pull-ci-openshift-metallb-operator-release-4.14-operator-e2e

**Comment by fedepaol** [comment]
/pj-rehearse pull-ci-openshift-metallb-operator-release-4.14-operator-e2e

**Comment by joepvd** [comment]
The better approach would be to not define base images in the release repo at all. Then `.ci-operator.yaml` and `Dockerfile` from the real repo do not get overridden.

**Comment by fedepaol** [comment]
> The better approach would be to not define base images in the release repo at all. Then `.ci-operator.yaml` and `Dockerfile` from the real repo do not get overridden.


thanks for the hint!

**Comment by fedepaol** [comment]
/pj-rehearse ci/rehearse/openshift/metallb-operator/release-4.14/operator-e2e

**Comment by fedepaol** [comment]
/pj-rehearse pull-ci-openshift-metallb-operator-release-4.14-operator-e2e

**Comment by fedepaol** [comment]
/pj-rehearse pull-ci-openshift-metallb-operator-release-4.14-operator-e2e

**Comment by fedepaol** [comment]
/pj-rehearse pull-ci-openshift-metallb-operator-release-4.14-operator-e2e

**Comment by fedepaol** [comment]
CI failure related to a chicken / egg issue. The images on CI registry still suffer from the rhel8 / rhel9 skew:

/controller: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /controller)

**Pull request merged**
