### PR TITLE
Change e2e-metal-ipi periodic 4.6 scheduling

### PR DESCRIPTION
**Pull request by andfasano**
Modified 4.6 branch build schedule to every 4 hours

### CODE REVIEW

**Comment by stbenjam** [comment]
It can be less often than that, we already get runs from every nightly build.  Steve K. suggested even yearly would be OK

**Comment by stbenjam** [comment]
but maybe we just match the 4.5 job to weekly

**Comment by andfasano** [comment]
4.6 is the current master, wasn't recommended to have a more frequent schedule? Maybe we can reduce the compact and ipv4 flavors, but I'd keep the default as much as possible frequent. What do you think?

**Comment by stbenjam** [comment]
> 4.6 is the current master, wasn't recommended to have a more frequent schedule? Maybe we can reduce the compact and ipv4 flavors, but I'd keep the default as much as possible frequent. What do you think?

I don't think there's much use in the periodic itself, we run e2e-metal-ipi against every nightly build already. The periodic will just end up testing the same nightlies that were already tested.

**Pull request merged**
