### PR TITLE
Hack around the deprecation of openshift-sdn

### PR DESCRIPTION
**Pull request by danwinship**
The installer will soon mostly refuse to install clusters with openshift-sdn (https://github.com/openshift/installer/pull/7720). This should let us hack around that limitation for CI purposes...

(The exact change that's going to be made to openshift-install hasn't been figured out yet, but this should work regardless.)

(This doesn't handle metal jobs, which will be fixed by https://github.com/openshift-metal3/dev-scripts/pull/1614.)

/assign @jluhrsen

### CODE REVIEW

**Comment by danwinship** [comment]
OK, I'm failing at this...

I want to figure out from `sdn-conf-commands.sh` what version of OCP we are testing, and do one thing if it's 4.15 or 4.16, and another thing for all earlier versions. But I can't figure out any way to find that out... `openshift-install` doesn't seem to be present yet when `sdn-conf-commands.sh` runs, and the seemingly-relevant environment variables seem to indicate the version of OCP that the job is running on, not the version we will be installing.

**Comment by jluhrsen** [comment]
> OK, I'm failing at this...
> 
> I want to figure out from `sdn-conf-commands.sh` what version of OCP we are testing, and do one thing if it's 4.15 or 4.16, and another thing for all earlier versions. But I can't figure out any way to find that out... `openshift-install` doesn't seem to be present yet when `sdn-conf-commands.sh` runs, and the seemingly-relevant environment variables seem to indicate the version of OCP that the job is running on, not the version we will be installing.

maybe add an env var to the config for the jobs that are going to need it, like [this](https://github.com/openshift/release/blob/ca24e7d6bce48f325a3cc244f50fbfa4d497c14d/ci-operator/config/redhat-chaos/krkn-hub/redhat-chaos-krkn-hub-main__rosa-4.15-nightly.yaml#L45). then update your script to
check for that variable and if it exists and is version 4.15+ you can do the extra work to make OpenShiftSDN
install?

but you are right that I think the cluster is not even starting it's install process which I guess brings in openshift-install
when this sdn-conf is run.

**Comment by danwinship** [comment]
/hold
blocked on #46286

**Comment by danwinship** [comment]
/pj-rehearse pull-ci-openshift-sdn-master-e2e-aws-sdn pull-ci-openshift-origin-master-e2e-aws-multitenant pull-ci-openshift-origin-master-e2e-metal-ipi-sdn pull-ci-openshift-origin-master-e2e-openstack-ovn

**Comment by danwinship** [comment]
/pj-rehearse pull-ci-openshift-sdn-master-e2e-aws-sdn pull-ci-openshift-origin-master-e2e-aws-multitenant pull-ci-openshift-origin-master-e2e-metal-ipi-sdn pull-ci-openshift-cluster-network-operator-master-e2e-openstack-sdn periodic-ci-openshift-release-master-nightly-4.15-e2e-vsphere-sdn

**Comment by danwinship** [comment]
> /pj-rehearse pull-ci-openshift-sdn-master-e2e-aws-sdn

spurious build failure? or some sort of real-vs-pj configuration issue?

> pull-ci-openshift-origin-master-e2e-aws-multitenant
> pull-ci-openshift-origin-master-e2e-metal-ipi-sdn
> periodic-ci-openshift-release-master-nightly-4.15-e2e-vsphere-sdn

failed to use the hacks, just installed sdn normally...

> pull-ci-openshift-cluster-network-operator-master-e2e-openstack-sdn 

Worked! The [cluster-config-v1 ConfigMap](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/46156/rehearse-46156-pull-ci-openshift-cluster-network-operator-master-e2e-openstack-sdn/1731332720526626816/artifacts/e2e-openstack-sdn/gather-extra/artifacts/configmaps.json) shows that the install-config had `networkType: OVNKubernetes`, but the cluster used openshift-sdn.

**Comment by danwinship** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-e2e-gcp-sdn pull-ci-openshift-origin-master-e2e-aws-multitenant pull-ci-openshift-origin-master-e2e-metal-ipi-sdn periodic-ci-openshift-release-master-nightly-4.15-e2e-vsphere-sdn

**Comment by danwinship** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-e2e-gcp-sdn pull-ci-openshift-origin-master-e2e-aws-multitenant periodic-ci-openshift-release-master-nightly-4.15-e2e-vsphere-sdn

**Comment by danwinship** [comment]
/hold cancel
@jluhrsen This seems to work for "normal" and openstack installs. Metal installs are being covered by a devscripts fix.

**Comment by jluhrsen** [comment]
> /hold cancel @jluhrsen This seems to work for "normal" and openstack installs. Metal installs are being covered by a devscripts fix.

/lgtm

i double checked the rehearsals to make sure their running CNI was OpenShiftSDN and looks good.

**Comment by danwinship** [comment]
/assign @MaysaMacedo @EmilienM 
can one of you OK the `ci-operator/step-registry/openstack` parts of this?

**Pull request merged**
