### PR TITLE
disaster recovery first test-1

### PR DESCRIPTION
**Pull request by geliu2016**
@JianLi-RH @zhouying7780 could u pls help to review?thanks

### CODE REVIEW

**Comment by geliu2016** [comment]
Hello Michal, we plan to create DR test with prow, could u pls take a review? thanks

**Comment by geliu2016** [comment]
Hello @bbguimaraes @droslean, I saw you are reviewer of this pr, could u pls take a review it, thanks

**Review by droslean — APPROVED** [review]

**Pull request closed without merging**
