### PR TITLE
AWS/Local Zones: add periodic for LZ workflows

### PR DESCRIPTION
**Pull request by mtulio**
Introducing a weekly periodic job for Local Zone workflows, sending alerts to SPLAT channel to prevent losing signals for that feature.

Refereces:

- https://github.com/openshift/origin/pull/28363
- https://issues.redhat.com/browse/OCPBUGS-22703

### CODE REVIEW

**Comment by mtulio** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-aws-ovn-localzones

**Comment by mtulio** [comment]
> /pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-aws-ovn-localzones

TF failed to create resources (NAT GW) - unrelated to the job. Also I didn't find [CI logs](https://search.ci.openshift.org/?search=reading+EC2+EIP&maxAge=48h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job), retrying:

/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-aws-ovn-localzones

**Comment by mtulio** [comment]
[Job failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/45166/rehearse-45166-periodic-ci-openshift-release-master-nightly-4.15-e2e-aws-ovn-localzones/1719779695349731328) due the [opened bug OCPBUGS-22703](https://issues.redhat.com/browse/OCPBUGS-22703) - this periodic target to review there.
/pj-rehearse ack
/assign @dgoodwin

**Review by wking — APPROVED** [review]
/lgtm

**Comment by smg247** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-aws-ovn-localzones

**Pull request merged**
