### PR TITLE
Change redhat namespace to rh one

### PR DESCRIPTION
**Pull request by karelhala**
Based on this PR https://github.com/openshift/release/pull/24606 we gotta change the namespace of our image resource.

### CODE REVIEW

**Comment by karelhala** [comment]
ping @andrewballantyne

**Review by andrewballantyne — APPROVED** [review]

**Comment by karelhala** [comment]
ping @petr-muller can you please take a look at this? Looks like we don't have enough rights to automatically merge this PR.

**Review by petr-muller — APPROVED** [review]

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
