### PR TITLE
Fix issue DPTP-3777 Add daily test for HyperShift

### PR DESCRIPTION
**Pull request by bear-redhat**

### CODE REVIEW

**Review by hongkailiu — COMMENTED** [review]
Why does the job go to the config for ci-tools?
Could we move it to https://github.com/openshift/release/blob/master/ci-operator/jobs/infra-periodics.yaml ?

**Comment by bear-redhat** [comment]
I am not sure if we can referencing a workflow in `infra-periodics`

**Comment by bear-redhat** [comment]
/pj-rehearse periodic-ci-openshift-release-master-hypershift-4.15-periodic-ci-openshift-hypershift-hosted

**Review by hongkailiu — APPROVED** [review]

**Pull request merged**
