### PR TITLE
[WIP] test build on arm01 cluster

### PR DESCRIPTION
**Pull request by SaravanaStorageNetwork**

### CODE REVIEW

**Comment by SaravanaStorageNetwork** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-aws-ovn-arm64-techpreview

**Comment by droslean** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-aws-ovn-arm64-techpreview

**Comment by deepsm007** [comment]
@droslean look at @danilo-gemoli PR https://github.com/openshift/release/pull/42509

**Comment by SaravanaStorageNetwork** [comment]
I'm closing this to avoid confusion.

**Pull request closed without merging**
