### PR TITLE
Migrate to app.ci: periodic-image-mirroring-openshift-psap

### PR DESCRIPTION
**Pull request by hongkailiu**
https://issues.redhat.com/browse/DPTP-1654

admin_openshift-psap_list.yaml is deleted because it is not used in the job.

### CODE REVIEW

**Comment by jmencak** [comment]
@ArangoGutierrez is this something you can comment on?  Looks nfd/sro specific.

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Comment by hongkailiu** [comment]
Green on app.ci
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-image-mirroring-openshift-psap/1328840433509339136

**Pull request merged**
