### PR TITLE
Add template for standalone jobs

### PR DESCRIPTION
**Pull request by csrwng**
Adds template to define standalone jobs through the jjb controller
Also removes the jenkins template from the setup yaml... we should just use whatever is in the cluster

### CODE REVIEW

**Comment by csrwng** [comment]
@stevekuznetsov

**Comment by csrwng** [comment]
@kargakis fyi ... adds parameters to the jjb definitions so that parameters will be known before the first job is run. Fixes https://github.com/openshift/release/issues/235

**Comment by csrwng** [comment]
Need this for jobs to not fail when started by prow

**Comment by kargakis** [comment]
How/where are these configmaps consumed by Jenkins? Also what instantiates the new template?

**Comment by csrwng** [comment]
@kargakis these configmaps are consumed by the jjb controller (https://github.com/openshift/release/tree/master/jenkins/controllers/jjb) which looks for configmaps annotated with `ci.openshift.io/jenkins-job: "true"` and uses jenkins job builder (https://docs.openstack.org/infra/jenkins-job-builder/) to create/update Jenkins jobs. Right now I'm instantiating this manually, but ideally we'd automate it the same way config is automated for prow.

**Comment by kargakis** [comment]
Is this documented somewhere? If not, open an issue so we won't forget.

**Comment by csrwng** [comment]
Created issue https://github.com/openshift/release/issues/252

**Pull request merged**
