### PR TITLE
router e2e-metal-ipi add dev-scripts image base definition

### PR DESCRIPTION
**Pull request by sgreene570**
Followed along with https://github.com/openshift/release/pull/10673/files

### CODE REVIEW

**Comment by sgreene570** [comment]
```
ERROR: This check enforces that Prow configuration YAML files are formatted
ERROR: correctly. We have automation in place that generates these configs and
ERROR: new changes to these job configurations should occur from a re-generation.
ERROR: Run the following command to re-generate the Prow jobs:
ERROR: $ make prow-config
ERROR: The following errors were found:
diff -Naupr .//core-services/prow/02_config/_config.yaml /tmp/tmp.dJIiZ1NE7t/_config.yaml
--- .//core-services/prow/02_config/_config.yaml	2020-09-02 15:48:58.374806533 +0000
+++ /tmp/tmp.dJIiZ1NE7t/_config.yaml	2020-09-02 15:49:07.493806479 +0000
@@ -381,7 +381,7 @@ deck:
           - '"level":"fatal"'
           - level=fatal
           - The namespace in which this test is executing has been deleted, cancelling the test
-          - "failed to update leases: exceeded number of retries for lease"
+          - 'failed to update leases: exceeded number of retries for lease'
         name: buildlog
       required_files:
       - build-log.txt
```
Is this error expected?

**Comment by stbenjam** [comment]
Not sure, what happens if you run `make prow-config`?

**Comment by sgreene570** [comment]
When I run `make prow-config` I get the following diff:

```
[sgreene@snowplow:release]$ git diff
diff --git a/core-services/prow/02_config/_config.yaml b/core-services/prow/02_config/_config.yaml
index 553f305769..d2a26906e6 100644
--- a/core-services/prow/02_config/_config.yaml
+++ b/core-services/prow/02_config/_config.yaml
@@ -381,7 +381,7 @@ deck:
           - '"level":"fatal"'
           - level=fatal
           - The namespace in which this test is executing has been deleted, cancelling the test
-          - "failed to update leases: exceeded number of retries for lease"
+          - 'failed to update leases: exceeded number of retries for lease'
         name: buildlog
       required_files:
       - build-log.txt
```
That's the same diff in the job failure, but doesn't seem related to these changes?

**Comment by stbenjam** [comment]
I don't think it's related, is your release repo up-to-date with master?

**Comment by sgreene570** [comment]
> I don't think it's related, is your release repo up-to-date with master?

Ah, that would do it. Fixed!

**Pull request merged**
