### PR TITLE
stackrox: bump automation-flavors

### PR DESCRIPTION
**Pull request by gavin-stackrox**
This version supports env propagation to create as per https://github.com/stackrox/automation-flavors/pull/166.
/uncc

### CODE REVIEW

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-4-14-compliance-e2e-tests
/pj-rehearse pull-ci-stackrox-stackrox-release-4.1-ocp-4-13-operator-e2e-tests
/pj-rehearse pull-ci-stackrox-stackrox-release-3.74-ocp-4-6-qa-e2e-tests
/pj-rehearse pull-ci-stackrox-stackrox-release-3.74-gke-nongroovy-e2e-tests
/pj-rehearse pull-ci-stackrox-stackrox-release-4.2-aro-qa-e2e-tests
/pj-rehearse pull-ci-stackrox-stackrox-release-4.2-eks-qa-e2e-tests
/pj-rehearse pull-ci-stackrox-stackrox-release-4.3-osd-gcp-qa-e2e-tests
/pj-rehearse pull-ci-stackrox-stackrox-release-4.3-powervs-qa-e2e-tests
/pj-rehearse pull-ci-stackrox-stackrox-master-ibmcloudz-4-14-qa-e2e-tests
/pj-rehearse pull-ci-stackrox-stackrox-master-osd-aws-qa-e2e-tests
/pj-rehearse pull-ci-stackrox-stackrox-master-powervs-qa-e2e-tests
/pj-rehearse pull-ci-stackrox-stackrox-master-rosa-qa-e2e-tests
/pj-rehearse pull-ci-stackrox-stackrox-release-x.y-ocp-4-11-qa-e2e-tests

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-release-4.1-ocp-4-13-operator-e2e-tests pull-ci-stackrox-stackrox-release-3.74-ocp-4-6-qa-e2e-tests pull-ci-stackrox-stackrox-release-3.74-gke-nongroovy-e2e-tests pull-ci-stackrox-stackrox-release-4.2-aro-qa-e2e-tests pull-ci-stackrox-stackrox-release-4.2-eks-qa-e2e-tests pull-ci-stackrox-stackrox-release-4.3-osd-gcp-qa-e2e-tests pull-ci-stackrox-stackrox-release-4.3-powervs-qa-e2e-tests pull-ci-stackrox-stackrox-master-ibmcloudz-4-14-qa-e2e-tests pull-ci-stackrox-stackrox-master-osd-aws-qa-e2e-tests pull-ci-stackrox-stackrox-master-powervs-qa-e2e-tests pull-ci-stackrox-stackrox-master-rosa-qa-e2e-tests pull-ci-stackrox-stackrox-release-x.y-ocp-4-11-qa-e2e-tests

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-release-4.2-eks-qa-e2e-tests

**Comment by gavin-stackrox** [comment]
/cc @tommartensen @davdhacs 
/pj-rehearse ack - the failures are flakes, the cluster flavors are fine.

**Comment by gavin-stackrox** [comment]
yeah yeah bot
/pj-rehearse ack

**Review by tommartensen — APPROVED** [review]
/lgtm

That's a big change!

**Pull request merged**
