### PR TITLE
HOSTEDCP-2041: add hypershift-aks-e2e as optional presub for cluster-image-registry-operator

### PR DESCRIPTION
**Pull request by Patryk-Stefanski**

### CODE REVIEW

**Comment by Patryk-Stefanski** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-master-hypershift-e2e-aks

**Comment by Patryk-Stefanski** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-release-4.17-hypershift-e2e-aks

**Comment by Patryk-Stefanski** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-release-4.17-hypershift-e2e-aks

**Comment by Patryk-Stefanski** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-master-hypershift-e2e-aks

**Comment by bryan-cox** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-release-4.17-hypershift-e2e-aks

**Comment by bryan-cox** [comment]
/pj-rehearse pull-ci-openshift-cluster-image-registry-operator-master-hypershift-e2e-aks

**Pull request merged**
