### PR TITLE
Add a syntax format validation job to OLS

### PR DESCRIPTION
**Pull request by bparees**
Can't merge this until we fix the actual formatting in our repo.  Want to see what rehearsals look like.

### CODE REVIEW

**Comment by bparees** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-service-main-validate

**Comment by bparees** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-service-main-validate

**Comment by bparees** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-service-main-validate

**Comment by bparees** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-service-main-verify

**Comment by bparees** [comment]
appears to be working as desired:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/45980/rehearse-45980-pull-ci-openshift-lightspeed-service-main-verify/1727468405910409216

it would be nice if we didn't have to pip install `black` every time, but addressing that will require us to introduce a new image and possibly a new repo entirely (because if we add a new image in the OLS repo, that image will get rebuilt every time a PR is submitted).

Need to talk to DPTP about what our options are for having a "python utility image" available (we could also base it on python 3.11 in that case since we'd only have to build it when making changes to the utilities)

**Comment by bparees** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-service-main-verify

**Comment by bparees** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-service-main-verify

**Comment by bparees** [comment]
Ok this appears to be working, once we've properly formatted the code in the lightspeed repo we can rerun the rehearsal of the verify job and if it passes, merge this.

**Comment by bparees** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-service-main-verify

**Comment by bparees** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-service-main-verify

**Review by vishnuchalla — APPROVED** [review]

**Pull request merged**
