### PR TITLE
Add recert OCP stabilization timing and improve test script logging

### PR DESCRIPTION
**Pull request by mresvanis**
This PR improves the recert rename job by adding:

- timestamp-ed logging for the test script
- OCP stabilization after recert timing

### CODE REVIEW

**Comment by mresvanis** [comment]
/pj-rehearse pull-ci-rh-ecosystem-edge-recert-main-baremetalds-sno-recert-cluster-rename

**Comment by mresvanis** [comment]
/pj-rehearse pull-ci-rh-ecosystem-edge-recert-main-baremetalds-sno-recert-cluster-rename

**Comment by mresvanis** [comment]
/pj-rehearse pull-ci-rh-ecosystem-edge-recert-main-baremetalds-sno-recert-cluster-rename

**Comment by mresvanis** [comment]
/pj-rehearse pull-ci-rh-ecosystem-edge-recert-main-baremetalds-sno-recert-cluster-rename

**Comment by mresvanis** [comment]
/pj-rehearse pull-ci-rh-ecosystem-edge-recert-main-baremetalds-sno-recert-cluster-rename

**Review by eranco74 — COMMENTED** [review]
/lgtm

**Pull request merged**
