### PR TITLE
[INTEROP-7501][INTEROP-7459] Enable OCP 4.17 FIPS testing on OpenShift Pipelines 1.15

### PR DESCRIPTION
**Pull request by dfrazzette**
Created FIPS periodic job to test FIPS compliance for OpenShift Pipelines on OCP 4.17 FIPS cluster. Also updated `.config.prowgen` file to include `slack_reporter` config for interop tests.

### CODE REVIEW

**Comment by dfrazzette** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.17-lp-interop-openshift-pipelines-interop-aws-fips

**Review by srivickynesh — APPROVED** [review]

**Comment by dfrazzette** [comment]
Re-ran `make update` locally to update 1.15 periodic yaml to fix failing [generated-config](https://prow.ci.openshift.org/job-history/gs/test-platform-results/pr-logs/directory/pull-ci-openshift-release-master-generated-config) Prow check. FIPS cluster rehearsal job [1819218644719112192](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/55118/rehearse-55118-periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.17-lp-interop-openshift-pipelines-interop-aws-fips/1819218644719112192) already run and passed.

**Review by srivickynesh — APPROVED** [review]
/lgtm

**Pull request merged**
