### PR TITLE
vsphere - add network resources names to generator

### PR DESCRIPTION
**Pull request by jcpowermac**

### CODE REVIEW

**Comment by jcpowermac** [comment]
cc: @rvanderp3

**Comment by bbguimaraes** [comment]
/lgtm
/hold

@alvaroaleman, @stevekuznetsov: is this one of the cases that has to be manually migrated?

**Comment by alvaroaleman** [comment]
No, after the latest change to the boskos config sync, this should work fine. I'll have a look to verify that when it gets deployed

**Pull request merged**
