### PR TITLE
Fix NFD errors

### PR DESCRIPTION
**Pull request by liswang89**

### CODE REVIEW

**Comment by liswang89** [comment]
/pj-rehearse periodic-ci-openshift-cluster-nfd-operator-release-4.15-ocp4.15-lp-rosa-hypershift-nfd-e2e-master-aws-rosa-hypershift

**Comment by liswang89** [comment]
/pj-rehearse periodic-ci-openshift-cluster-nfd-operator-release-4.15-ocp4.15-lp-rosa-hypershift-nfd-e2e-master-aws-rosa-hypershift

**Comment by liswang89** [comment]
/pj-rehearse periodic-ci-openshift-cluster-nfd-operator-release-4.15-ocp4.15-lp-rosa-hypershift-nfd-e2e-master-aws-rosa-hypershift

**Comment by liswang89** [comment]
/pj-rehearse periodic-ci-openshift-cluster-nfd-operator-release-4.15-ocp4.15-lp-rosa-hypershift-nfd-e2e-master-aws-rosa-hypershift

**Comment by liswang89** [comment]
/pj-rehearse periodic-ci-openshift-cluster-nfd-operator-release-4.15-ocp4.15-lp-rosa-hypershift-nfd-e2e-master-aws-rosa-hypershift

**Comment by liswang89** [comment]
/pj-rehearse periodic-ci-openshift-cluster-nfd-operator-release-4.15-ocp4.15-lp-rosa-hypershift-nfd-e2e-master-aws-rosa-hypershift

**Comment by liswang89** [comment]
/pj-rehearse periodic-ci-openshift-cluster-nfd-operator-release-4.15-ocp4.15-lp-rosa-hypershift-nfd-e2e-master-aws-rosa-hypershift

**Comment by liswang89** [comment]
/pj-rehearse periodic-ci-openshift-cluster-nfd-operator-release-4.15-ocp4.15-lp-rosa-hypershift-nfd-e2e-master-aws-rosa-hypershift

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
