### PR TITLE
Cleanup release-v1 presubmits

### PR DESCRIPTION
**Pull request by charlesakalugwu**
Cleanup release-v1 presubmits

/cc @Makdaam @kwoodson

### CODE REVIEW

**Comment by kwoodson** [comment]
@charlesakalugwu, still interested in disabling this one since it is not required?

**Comment by charlesakalugwu** [comment]
> @charlesakalugwu, still interested in disabling this one since it is not required?

@kwoodson yes please :)

**Comment by jim-minter** [comment]
This is not right.

1) no-one should be changing the release-v1 settings, we shouldn't even be pushing to that branch of openshift-azure, it is now historical.
2) there should be no changeloglevel test on release-v1 presubmits: the test has not and should not be backported to release-v1.

Removing lgtm.

@charlesakalugwu or @kwoodson  I'd happily see and accept a PR to remove the changeloglevel stanza from ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v1-presubmits.yaml .

**Comment by kwoodson** [comment]
I think this does what @jim-minter was referring to so I'll sign off.

/lgtm

**Pull request merged**
