### PR TITLE
ci-operator: coreos: Remove config & jobs for 'master' branch

### PR DESCRIPTION
**Pull request by travier**
Second part of the update for 'master' -> 'main' branch renaming in CoreOS org repos. See #18487 for the first part.

### CODE REVIEW

**Comment by travier** [comment]
/unhold
All repo branches have been updated now.

**Comment by cgwalters** [comment]
I believe the rehearsals should pass now?  Let's try it.
/retest

**Comment by cgwalters** [comment]
OK well, no idea let's roll with it :smile: 
/lgtm

**Pull request merged**
