### PR TITLE
Servicemesh - expand rosa-hypershift testing to OCP 4.12

### PR DESCRIPTION
**Pull request by ascerra**

### CODE REVIEW

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-maistra-maistra-test-tool-main-servicemesh-hypershift-4.12-lp-rosa-hypershift-servicemesh-aws-rosa-hypershift-412

**Review by FilipB — APPROVED** [review]
LGTM. The plan is to use this the same way like servicemesh-ocp4.14-lp-interop? Run OSSM tests weekly against the latest ROSA?

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
