### PR TITLE
Add arm64 to multi-arch migration test on ec payloads

### PR DESCRIPTION
**Pull request by shellyyang1989**
Refers [OTA-887](https://issues.redhat.com/browse/OTA-887) [MIXEDARCH-134](https://issues.redhat.com/browse/MIXEDARCH-134) [MIXEDARCH-167](https://issues.redhat.com/browse/MIXEDARCH-167)

### CODE REVIEW

**Comment by shellyyang1989** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-dev-preview-aws-ipi-to-multiarch-p2-f14

**Comment by shellyyang1989** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-dev-preview-aws-ipi-to-multiarch-p2-f14

**Comment by shellyyang1989** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-dev-preview-aws-ipi-to-multiarch-p2-f14

**Comment by shellyyang1989** [comment]
Arch migration and scaleup passed.
```
INFO[2023-02-27T09:43:46Z] Running step aws-ipi-to-multiarch-p2-f14-cucushift-upgrade-arch-migration. 
INFO[2023-02-27T10:09:26Z] Step aws-ipi-to-multiarch-p2-f14-cucushift-upgrade-arch-migration succeeded after 25m40s. 
INFO[2023-02-27T10:09:26Z] Running step aws-ipi-to-multiarch-p2-f14-ipi-install-heterogeneous. 
INFO[2023-02-27T10:14:36Z] Step aws-ipi-to-multiarch-p2-f14-ipi-install-heterogeneous succeeded after 5m10s. 
```

cc @aleskandro @jianlinliu @liangxia @jhou1 @evakhoni for review and merge. Thanks!

**Review by aleskandro — APPROVED** [review]

**Pull request merged**
