### PR TITLE
Move pull-ci-openshift-origin-release-3.11-unit back to api.ci

### PR DESCRIPTION
**Pull request by hongkailiu**
Follow up https://coreos.slack.com/archives/CBN38N3MW/p1601988848076800

/assign @adambkaplan 

/cc @openshift/openshift-team-developer-productivity-test-platform

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/hold
I would prefer if these tests get fixed isntead to work on the 4.x build clusters. How much effort is that?

**Comment by alvaroaleman** [comment]
If we merge this I would like to see a BZ tracking the fix of these tests to work on a 4.X cluster. We need to get rid of the 3.11 cluster as it is a maintenance nightmare.

**Comment by stevekuznetsov** [comment]
And we'd want a Jira task to track us bugging the devs to fix the BZ so we don't forget about this.

**Comment by hongkailiu** [comment]
https://issues.redhat.com/browse/DPTP-1621

**Comment by hongkailiu** [comment]
https://issues.redhat.com/browse/DPTP-1621?focusedCommentId=15541217&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-15541217

**Pull request closed without merging**
