### PR TITLE
Added periodics and optional presubmit tests

### PR DESCRIPTION
**Pull request by sagidayan**

### CODE REVIEW

**Comment by sagidayan** [comment]
/pj-rehearse pull-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.10-nvidia-gpu-operator-e2e
/pj-rehearse pull-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.12-nvidia-gpu-operator-e2e
/pj-rehearse pull-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.9-nvidia-gpu-operator-e2e
/pj-rehearse pull-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.8-nvidia-gpu-operator-e2e

**Comment by sagidayan** [comment]
/pj-rehearse pull-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.12-nvidia-gpu-operator-e2e

**Comment by sagidayan** [comment]
/pj-rehearse pull-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.9-nvidia-gpu-operator-e2e

**Comment by sagidayan** [comment]
/pj-rehearse pull-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.8-nvidia-gpu-operator-e2e

**Comment by sagidayan** [comment]
/pj-rehearse pull-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.9-nvidia-gpu-operator-e2e

**Review by fabiendupont — APPROVED** [review]

**Pull request merged**
