### PR TITLE
OCPBUGS-12434: openstack-test: Include oc CLI in the base image

### PR DESCRIPTION
**Pull request by pierreprinetti**

### CODE REVIEW

**Comment by pierreprinetti** [comment]
/pj-rehearse pull-ci-openshift-openstack-test-release-4.14-test

**Comment by pierreprinetti** [comment]
/pj-rehearse ack
The rehearse is only a regression test. The expected result is in the periodics using the promoted image, which are not included in the list of rehearsable tests.

**Review by gryf — APPROVED** [review]
/lgtm

**Pull request merged**
