### PR TITLE
Add pause:3.9 image to mirroring

### PR DESCRIPTION
**Pull request by soltysh**
/assign @bertinatto

### CODE REVIEW

**Comment by ardaguclu** [comment]
/approve
/hold
I think, we need at least one job run to ensure everything is working

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-ovn-ipv6

**Comment by bertinatto** [comment]
> /approve /hold I think, we need at least one job run to ensure everything is working

/hold cancel

`/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-ovn-ipv6` job passed: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/43443/rehearse-43443-periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-ovn-ipv6/1703759730012327936

**Pull request merged**
