### PR TITLE
Add OCP CI step for mirroring Distributed Tracing operators and test images, creating catalog source and ICSP for disconnected cluster env.

### PR DESCRIPTION
**Pull request by IshwarKanse**
* The PR adds a OCP CI step to mirror the Distributed Tracing operators and test images to the disconnected cluster mirror registry. Create the image content source policy and catalog source.
* Add a CI job to run tests on a disconnected env cluster.

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-distributed-tracing-qe-main-ocp4.15-disconnected-distributed-tracing-tests-disconnected

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-distributed-tracing-qe-main-ocp4.15-disconnected-distributed-tracing-tests-disconnected

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-distributed-tracing-qe-main-ocp4.15-disconnected-distributed-tracing-tests-disconnected

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-distributed-tracing-qe-main-ocp4.15-disconnected-distributed-tracing-tests-disconnected

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-distributed-tracing-qe-main-ocp4.15-disconnected-distributed-tracing-tests-disconnected

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-distributed-tracing-qe-main-ocp4.15-disconnected-distributed-tracing-tests-disconnected

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-distributed-tracing-qe-main-ocp4.15-disconnected-distributed-tracing-tests-disconnected

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-distributed-tracing-qe-main-ocp4.15-disconnected-distributed-tracing-tests-disconnected

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-distributed-tracing-qe-main-ocp4.15-disconnected-distributed-tracing-tests-disconnected

**Review by rubenvp8510 — APPROVED** [review]

**Pull request merged**
