### PR TITLE
kubernetes: use multistep job for e2e-upgrade

### PR DESCRIPTION
**Pull request by vrutkovs**
Run GCP upgrade using multistep and persist container logs using Loki

### CODE REVIEW

**Comment by deads2k** [comment]
I want these things, but I don't know whether to merge on red or not.

**Comment by vrutkovs** [comment]
Flakes

/retest

**Comment by vrutkovs** [comment]
4.6 test [passed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/11663/rehearse-11663-pull-ci-openshift-kubernetes-release-4.6-e2e-upgrade/1303965661826912256), others failed to build

/retest

**Comment by vrutkovs** [comment]
Build failures

/retest

**Comment by vrutkovs** [comment]
master / 4.7 still flakes

/retest

**Pull request merged**
