### PR TITLE
hypershift: OCP regression test on KubeVirt-HyperShift

### PR DESCRIPTION
**Pull request by LiangquanLi930**
https://issues.redhat.com/browse/OCPQE-13741

### CODE REVIEW

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-ipi-ovn-kubevirt-hypershift-p3-f21

**Comment by LiangquanLi930** [comment]
@kuiwang02 @liangxia could you help to review this PR, thanks

**Comment by kuiwang02** [comment]
Iamok from golang's view.

**Pull request merged**
