### PR TITLE
add auto merge

### PR DESCRIPTION
**Pull request by jianzhangbjz**
As title show, add auto-merge for the https://github.com/openshift/openshift-tests-private repo.

### CODE REVIEW

**Comment by jianzhangbjz** [comment]
Get the below error, @petr-muller Anything else I missed? Should I remove this `openshift-priv/openshift-tests-private` repo? Thanks!
```
"msg":"the following orgs or repos require the approved label for merging but do not enable the approve plugin: [repo: openshift-priv/openshift-tests-private]
```

**Comment by petr-muller** [comment]
Just don't do anything with `openshift-priv/openshift-tests-private` - all config for that org is managed automatically.

**Comment by jianzhangbjz** [comment]
@petr-muller Got it, thanks! So, how to fix this failure? Or Is it depends on this PR: https://github.com/openshift/openshift-tests-private/pull/44?

**Comment by jianzhangbjz** [comment]
@petr-muller @stevekuznetsov Could you help give approval? Thanks!

**Pull request merged**
