### PR TITLE
Add preprod for certified-operators-preprod pipeline

### PR DESCRIPTION
**Pull request by mrhillsman**
Introducing a significant change to preflight-trigger and
for future-proofing work related to preflight and preflight-trigger

Signed-off-by: Melvin Hillsman <mhillsma@redhat.com>

### CODE REVIEW

**Comment by mrhillsman** [comment]
Failures are related to supplemental-ci-image missing which is part of this PR.

**Review by jomkz — APPROVED** [review]
/lgtm

**Review by bcrochet — APPROVED** [review]
/lgtm

**Review by droslean — APPROVED** [review]

**Pull request merged**
