### PR TITLE
shiftstack: Use Prow to run cireport

### PR DESCRIPTION
**Pull request by pierreprinetti**
cireport is the CI-run aggregator for ShiftStack.

### CODE REVIEW

**Comment by pierreprinetti** [comment]
/cc @EmilienM
this looks ready for a review

**Comment by pierreprinetti** [comment]
OSASINFRA-2620

**Comment by MaysaMacedo** [comment]
Just of curiosity, will it inform if any jobs on the last hour failed or only the latest job ran?

**Comment by pierreprinetti** [comment]
>Just of curiosity, will it inform if any jobs on the last hour failed or only the latest job ran?

The tool ([cireport](https://github.com/shiftstack/gazelle)) idempotently runs on every job more recent than what's in [the spreadsheet](https://docs.google.com/spreadsheets/d/16_3V8Uh1h4wIVnSA_fGHs9PrAnYdvGrX7tREVecexc4)

**Pull request merged**
