### PR TITLE
removal of install.sh items

### PR DESCRIPTION
**Pull request by cooktheryan**
Signed-off-by: Ryan Cook <rcook@redhat.com>

Closes https://github.com/redhat-et/microshift/issues/483

Reference https://github.com/redhat-et/microshift/pull/487

### CODE REVIEW

**Comment by cooktheryan** [comment]
@sallyom @copejon I took a swag at this

**Comment by cooktheryan** [comment]
will depend on https://github.com/openshift/release/pull/24306

**Comment by sallyom** [comment]
/lgtm 

:partying_face:

**Pull request merged**
