### PR TITLE
add basic jobs for instaslice-operator ci

### PR DESCRIPTION
**Pull request by kannon92**
Add lint job and `make test` jobs to test this out at first.

### CODE REVIEW

**Comment by harche** [comment]
> /override ci/prow/build-clusters

@deepsm007 not sure why are we overriding required job.

**Comment by kannon92** [comment]
/pj-rehearse pull-ci-openshift-instaslice-operator-main-unit pull-ci-openshift-instaslice-operator-main-lint

**Comment by harche** [comment]
/pj-rehearse pull-ci-openshift-instaslice-operator-main-unit pull-ci-openshift-instaslice-operator-main-lint

**Comment by kannon92** [comment]
/pj-rehearse pull-ci-openshift-instaslice-operator-main-unit pull-ci-openshift-instaslice-operator-main-lint

**Comment by kannon92** [comment]
/pj-rehearse pull-ci-openshift-instaslice-operator-main-unit pull-ci-openshift-instaslice-operator-main-lint

**Comment by kannon92** [comment]
/pj-rehearse pull-ci-openshift-instaslice-operator-main-unit pull-ci-openshift-instaslice-operator-main-lint

**Review by harche — APPROVED** [review]
/approve

**Pull request merged**
