### PR TITLE
ocm - cut new release 2.8 (governance-policy-framework)

### PR DESCRIPTION
**Pull request by JustinKuli**
https://issues.redhat.com/browse/ACM-2734

### CODE REVIEW

**Review by dhaiducek — APPROVED** [review]

**Comment by JustinKuli** [comment]
/pj-rehearse pull-ci-stolostron-governance-policy-framework-main-test-e2e-grc-framework

Looks like the other two failed because of this, and we can ignore them:
```
2023-01-25T16:50:41+00:00 Getting latest snapshot for 2.8-dev
2023-01-25T16:50:41+00:00 ERROR no manifest file found in pipeline/snapshots
```

**Comment by JustinKuli** [comment]
/pj-rehearse pull-ci-stolostron-governance-policy-framework-main-test-e2e-grc-framework

**Comment by dhaiducek** [comment]
The rehearsals are running as expected. I think getting them to pass is outside the scope of this PR.

**Pull request merged**
