### PR TITLE
Add e2e vsphere dual-stack job

### PR DESCRIPTION
**Pull request by pperiyasamy**
Signed-off-by: Periyasamy Palanisamy <pepalani@redhat.com>

### CODE REVIEW

**Comment by pperiyasamy** [comment]
/hold
requires https://github.com/openshift/installer/pull/5798

**Comment by cybertron** [comment]
```Invalid value: "DualStack": dual-stack IPv4/IPv6 is not supported for this platform, specify only one type of address```

Looks like this is correctly configuring for dual stack, so
/lgtm

**Comment by mkowalski** [comment]
Yeah the failure is expected

```
 	clusteroperator/network is not available (The network is starting up) because DaemonSet "/openshift-ovn-kubernetes/ovnkube-node" rollout is not making progress - pod ovnkube-node-5gw9s is in CrashLoopBackOff State
DaemonSet "/openshift-ovn-kubernetes/ovnkube-node" rollout is not making progress - pod ovnkube-node-jccfz is in CrashLoopBackOff State
DaemonSet "/openshift-ovn-kubernetes/ovnkube-node" rollout is not making progress - pod ovnkube-node-klm9x is in CrashLoopBackOff State
DaemonSet "/openshift-ovn-kubernetes/ovnkube-node" rollout is not making progress - last change 2023-02-07T12:35:31Z ```

We have vSphere infra with single-stack VMs what causes OVN-K8s pods to choke if they are provided with dual-stack configuration

**Comment by mkowalski** [comment]
Still debugging...
```
          message: "s.go:203] Exec(5): stdout: \"\"\nI0219 16:26:25.631482   60209
            ovs.go:204] Exec(5): stderr: \"\"\nI0219 16:26:25.631603   60209 ovs.go:200]
            Exec(6): /usr/bin/ovs-vsctl --timeout=15 -- --if-exists del-port br-int
            k8s-ci-op-nvtq0 -- --may-exist add-port br-int ovn-k8s-mp0 -- set interface
            ovn-k8s-mp0 type=internal mtu_request=1400 external-ids:iface-id=k8s-ci-op-nvtq0fv6-40555-q82nn-master-0\nI0219
            16:26:25.640688   60209 ovs.go:203] Exec(6): stdout: \"\"\nI0219 16:26:25.640706
            \  60209 ovs.go:204] Exec(6): stderr: \"\"\nI0219 16:26:25.640718   60209
            ovs.go:200] Exec(7): /usr/bin/ovs-vsctl --timeout=15 --if-exists get interface
            ovn-k8s-mp0 mac_in_use\nI0219 16:26:25.649297   60209 ovs.go:203] Exec(7):
            stdout: \"\\\"2a:fa:e2:4d:94:63\\\"\\n\"\nI0219 16:26:25.649315   60209
            ovs.go:204] Exec(7): stderr: \"\"\nI0219 16:26:25.649331   60209 ovs.go:200]
            Exec(8): /usr/bin/ovs-vsctl --timeout=15 set interface ovn-k8s-mp0 mac=2a\\:fa\\:e2\\:4d\\:94\\:63\nI0219
            16:26:25.658080   60209 ovs.go:203] Exec(8): stdout: \"\"\nI0219 16:26:25.658099
            \  60209 ovs.go:204] Exec(8): stderr: \"\"\nI0219 16:26:25.689426   60209
            gateway_init.go:260] Initializing Gateway Functionality\nI0219 16:26:25.689611
            \  60209 gateway_localnet.go:174] Node local addresses initialized to:
            map[10.129.0.2:{10.129.0.0 fffffe00} 127.0.0.1:{127.0.0.0 ff000000} 192.168.86.44:{192.168.86.0
            ffffff80} ::1:{::1 ffffffffffffffffffffffffffffffff} fd00:10:128:1::2:{fd00:10:128:1::
            ffffffffffffffff0000000000000000} fe80::28fa:e2ff:fe4d:9463:{fe80:: ffffffffffffffff0000000000000000}
            fe80::7fcf:6958:6672:4291:{fe80:: ffffffffffffffff0000000000000000} fe80::e8ee:8ff:fe06:85e:{fe80::
            ffffffffffffffff0000000000000000}]\nI0219 16:26:25.689714   60209 helper_linux.go:69]
            Provided gateway interface \"br-ex\", found as index: 5\nI0219 16:26:25.689811
            \  60209 helper_linux.go:94] Found default gateway interface br-ex 192.168.86.1\nI0219
            16:26:25.689849   60209 helper_linux.go:69] Provided gateway interface
            \"br-ex\", found as index: 5\nF0219 16:26:25.689978   60209 ovnkube.go:133]
            multiple gateway interfaces detected: br-ex \n"
          reason: Error
          startedAt: "2023-02-19T16:26:25Z"
      name: ovnkube-node
```

**Pull request closed without merging**
