### PR TITLE
Onboard manila-operator

### PR DESCRIPTION
**Pull request by viroel**
- unit test job
- pre-commit job
- operator build only job, since manila is not integrated in meta-operator yet

### CODE REVIEW

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-manila-operator-main-manila-operator-build

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-manila-operator-main-precommit-check

**Comment by viroel** [comment]
/pj-rehearse ack

pre-commit and operator-build job are passing

**Comment by fmount** [comment]
Thanks @viroel, it looks good!

**Review by fmount — APPROVED** [review]

**Comment by fmount** [comment]
@gouthampacha FYI we're onboarding `manila-operator` in CI

**Pull request merged**
