### PR TITLE
fix openshifttest mirror images list

### PR DESCRIPTION
**Pull request by lwan-wanglin**
some mirror images don't map with test cases used images, update it

### CODE REVIEW

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-aws-sc2s-ipi-disconnected-private-fips-f14

**Comment by lihongan** [comment]
/lgtm
Thank you!

**Comment by lwan-wanglin** [comment]
@yunjiang29 We can merge it now.

**Pull request merged**
