### PR TITLE
[WIP] 4.16 Hybrid

### PR DESCRIPTION
**Pull request by paigerube14**
For 4.16 testing: https://issues.redhat.com/browse/OCPQE-20494

### CODE REVIEW

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-hybrid-control-plane-120nodes

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-hybrid-control-plane-120nodes

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-hybrid-control-plane-120nodes

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-hybrid-control-plane-120nodes

**Comment by qiliRedHat** [comment]
@paigerube14 I think I may not express myself clearly about this. I hope to update our Jenkins profile to be aline with the Prow config like the master config for 120 nodes on AWS. I will address it in https://issues.redhat.com/browse/OCPQE-22426. If you agree, you can close this pr.

**Comment by paigerube14** [comment]
@qiliRedHat I'll update to have the same sizing that was on 4.15 to 4.16. I want to add the 4.16 job in this pr

**Comment by shahsahil264** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-hybrid-control-plane-120nodes

**Pull request closed without merging**
