### PR TITLE
Add openshift/kubernetes

### PR DESCRIPTION
**Pull request by tnozicka**
The fork will need some fixes to be buildable for rehearse to pass

requires:
 - [x] https://github.com/openshift/release/pull/4534

/cc @deads2k @squeed

### CODE REVIEW

**Comment by tnozicka** [comment]
@stevekuznetsov `Found configurations that do not belong to the correct auto-updating config`?

**Comment by squeed** [comment]
It looks like the job OOM'd. Do you need to do a full `make`, or can you do `make verify`?

**Comment by deads2k** [comment]
@tnozicka let's focus on the  units first and do the verifies separately.  See if you can get some good mileage out of bumping the memory to avoid OOMing

**Comment by deads2k** [comment]
also, if we can get this mostly working, my standards are fairly low for getting started.  the origin fork in particular needs some work.

**Comment by tnozicka** [comment]
requires https://github.com/openshift/release/pull/4534

**Comment by tnozicka** [comment]
rehearse failures are expected, the branches need work, CI should go first

**Pull request merged**
