### PR TITLE
Add `cluster_profile` to workflows

### PR DESCRIPTION
**Pull request by bbguimaraes**
These are specific to IaaS providers, there's no reason to repeat the profile
in each test.

/cc @openshift/openshift-team-developer-productivity-test-platform

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@bbguimaraes just for my understanding, where does the profile now come from?

**Comment by bbguimaraes** [comment]
@alvaroaleman: `steps.workflow` in `tests` in the `ci-operator` configuration file copies all fields from the workflow to the test (including `cluster_profile`):

https://steps.svc.ci.openshift.org/help/#config

This just moves the `cluster_profile` field from the tests to the workflows, for those that only target a single IaaS provider, since there's no need to repeat the profile in every test.

**Comment by bbguimaraes** [comment]
Hmm… This won't work as it is because parts of `prowgen` use `cluster_profile`.

/hold

**Comment by stevekuznetsov** [comment]
This might have to wait for a more comprehensive design

**Comment by stevekuznetsov** [comment]
I don't think we will need this

/close

**Pull request closed without merging**
