### PR TITLE
Fix Firewatch Additional Labels Bug

### PR DESCRIPTION
**Pull request by calebevans**

### CODE REVIEW

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-p2p-rosa-classic-openshift-pipelines-serverless-rosa-classic-417-rc

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-p2p-rosa-classic-openshift-pipelines-serverless-rosa-classic-417-rc

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-p2p-rosa-classic-openshift-pipelines-serverless-rosa-classic-417-rc

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-p2p-rosa-classic-openshift-pipelines-serverless-rosa-classic-417-rc

**Review by Simranpal — APPROVED** [review]
/lgtm

**Pull request merged**
