### PR TITLE
Switch to odf-aws cluster profile inside red-hat-storage org

### PR DESCRIPTION
**Pull request by malayparida2000**
https://issues.redhat.com/browse/RHSTOR-5509

### CODE REVIEW

**Comment by malayparida2000** [comment]
/pj-rehearse pull-ci-red-hat-storage-odf-operator-main-odf-operator-e2e-aws pull-ci-red-hat-storage-odf-console-master-odf-console-e2e-aws pull-ci-red-hat-storage-odf-multicluster-orchestrator-main-integration-test pull-ci-red-hat-storage-mcg-osd-deployer-main-test-suite pull-ci-red-hat-storage-mcg-ms-console-master-mcg-ms-console-e2e-aws pull-ci-red-hat-storage-ocs-operator-main-ocs-operator-bundle-e2e-aws

**Comment by malayparida2000** [comment]
/pj-rehearse pull-ci-red-hat-storage-ocs-operator-main-ocs-operator-bundle-e2e-aws

**Comment by malayparida2000** [comment]
/pj-rehearse pull-ci-red-hat-storage-ocs-operator-main-ocs-operator-bundle-e2e-aws

**Comment by malayparida2000** [comment]
/pj-rehearse pull-ci-red-hat-storage-odf-operator-main-odf-operator-e2e-aws pull-ci-red-hat-storage-odf-operator-release-4.15-odf-operator-e2e-aws pull-ci-red-hat-storage-ocs-operator-main-ocs-operator-bundle-e2e-aws pull-ci-red-hat-storage-ocs-operator-release-4.15-ocs-operator-bundle-e2e-aws pull-ci-red-hat-storage-odf-multicluster-orchestrator-main-integration-test pull-ci-red-hat-storage-odf-multicluster-orchestrator-release-4.15-integration-test pull-ci-red-hat-storage-odf-console-master-odf-console-e2e-aws pull-ci-red-hat-storage-odf-console-release-4.14-odf-console-e2e-aws pull-ci-red-hat-storage-mcg-ms-console-master-mcg-ms-console-e2e-aws pull-ci-red-hat-storage-mcg-osd-deployer-main-test-suite

**Comment by malayparida2000** [comment]
/pj-rehearse pull-ci-red-hat-storage-odf-operator-main-odf-operator-e2e-aws pull-ci-red-hat-storage-odf-operator-release-4.15-odf-operator-e2e-aws pull-ci-red-hat-storage-ocs-operator-release-4.15-ocs-operator-bundle-e2e-aws

**Comment by malayparida2000** [comment]
/pj-rehearse pull-ci-red-hat-storage-odf-multicluster-orchestrator-release-4.15-integration-test pull-ci-red-hat-storage-odf-console-master-odf-console-e2e-aws pull-ci-red-hat-storage-odf-console-release-4.14-odf-console-e2e-aws

**Comment by malayparida2000** [comment]
/pj-rehearse pull-ci-red-hat-storage-mcg-osd-deployer-main-lint pull-ci-red-hat-storage-mcg-osd-deployer-main-test-suite pull-ci-red-hat-storage-mcg-ms-console-master-mcg-ms-console-e2e-aws

**Comment by malayparida2000** [comment]
/pj-rehearse pull-ci-red-hat-storage-ocs-operator-release-4.14-ocs-operator-bundle-e2e-aws pull-ci-red-hat-storage-ocs-operator-release-4.13-ocs-operator-bundle-e2e-aws pull-ci-red-hat-storage-ocs-operator-release-4.12-ocs-operator-bundle-e2e-aws

**Comment by malayparida2000** [comment]
/pj-rehearse pull-ci-red-hat-storage-odf-operator-release-4.14-odf-operator-e2e-aws pull-ci-red-hat-storage-odf-operator-release-4.13-odf-operator-e2e-aws pull-ci-red-hat-storage-odf-operator-release-4.12-odf-operator-bundle-e2e-aws

**Comment by malayparida2000** [comment]
/pj-rehearse pull-ci-red-hat-storage-odf-multicluster-orchestrator-release-4.16-integration-test pull-ci-red-hat-storage-odf-multicluster-orchestrator-release-4.14-integration-test pull-ci-red-hat-storage-odf-multicluster-orchestrator-release-4.13-integration-test pull-ci-red-hat-storage-odf-multicluster-orchestrator-release-4.12-integration-test

**Comment by malayparida2000** [comment]
/pj-rehearse pull-ci-red-hat-storage-odf-console-release-4.13-odf-console-e2e-aws pull-ci-red-hat-storage-odf-console-release-4.12-odf-console-e2e-aws

**Comment by malayparida2000** [comment]
/pj-rehearse pull-ci-red-hat-storage-odf-operator-release-4.14-odf-operator-e2e-aws pull-ci-red-hat-storage-odf-operator-release-4.13-odf-operator-e2e-aws pull-ci-red-hat-storage-odf-operator-release-4.12-odf-operator-bundle-e2e-aws pull-ci-red-hat-storage-odf-operator-release-4.11-odf-operator-bundle-e2e-aws

**Comment by malayparida2000** [comment]
/pj-rehearse pull-ci-red-hat-storage-odf-multicluster-orchestrator-release-4.11-integration-test

**Comment by malayparida2000** [comment]
/pj-rehearse pull-ci-red-hat-storage-ocs-operator-release-4.11-ocs-operator-bundle-e2e-aws

**Comment by malayparida2000** [comment]
odf operator e2e was already flaky and had started to fail was being overridden as seen here
4.11-https://github.com/red-hat-storage/odf-operator/pull/319
4.12-https://github.com/red-hat-storage/odf-operator/pull/318
4.13-https://github.com/red-hat-storage/odf-operator/pull/353
4.14-https://github.com/red-hat-storage/odf-operator/pull/354

So the failures to odf e2e tests on branches release-4.11 to release-4.14 can be safely ignored

**Comment by malayparida2000** [comment]
@SanjalKatiyar @bipuladh 
This is a PR where we are switching to our own separate AWS cluster profile.
While making the changes we are rehearsing all the tests for all our repos. For odf-console the e2e-tests have passed for the other branches but for some reasons the test on the release-4.11 branch keeps failing with the error message 

```
[2925:0216/154341.273481:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 3151: Permission denied (13)
[3151:0216/154341.288837:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/48750/rehearse-48750-pull-ci-red-hat-storage-odf-console-release-4.13-odf-console-e2e-aws/1758504851429396480

can you please take a look and share any insights?

**Comment by agarwal-mudit** [comment]
> Tests from mcg-ms-console & mcg-osd-deployer are failing due to unrelated reasons like in-consistent vendoring in the repo. These 2 repos have been dormant since last 1.5 years(since sep 2022), and these tests have not been recently run & they are failing due to unrelated reasons so these can be ignored in my opinion. wdyt @agarwal-mudit ? https://github.com/red-hat-storage/mcg-ms-console https://github.com/red-hat-storage/mcg-osd-deployer

Yes

**Comment by SanjalKatiyar** [comment]
/pj-rehearse pull-ci-red-hat-storage-odf-console-release-4.13-odf-console-e2e-aws

**Comment by SanjalKatiyar** [comment]
> Tests from mcg-ms-console & mcg-osd-deployer are failing due to unrelated reasons like in-consistent vendoring in the repo. These 2 repos have been dormant since last 1.5 years(since sep 2022), and these tests have not been recently run & they are failing due to unrelated reasons so these can be ignored in my opinion. wdyt @agarwal-mudit ? https://github.com/red-hat-storage/mcg-ms-console https://github.com/red-hat-storage/mcg-osd-deployer

both these products are not supported anymore (in fact it was not even released), if needed we can remove their config from this repo too !!

**Comment by malayparida2000** [comment]
> > Tests from mcg-ms-console & mcg-osd-deployer are failing due to unrelated reasons like in-consistent vendoring in the repo. These 2 repos have been dormant since last 1.5 years(since sep 2022), and these tests have not been recently run & they are failing due to unrelated reasons so these can be ignored in my opinion. wdyt @agarwal-mudit ? https://github.com/red-hat-storage/mcg-ms-console https://github.com/red-hat-storage/mcg-osd-deployer
> 
> both these products are not supported anymore (in fact it was not even released), if needed we can remove their config from this repo too !!

I can remove them in a follow up PR

**Comment by SanjalKatiyar** [comment]
> ```
> [2925:0216/154341.273481:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 3151: Permission denied (13)
> [3151:0216/154341.288837:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
> ```
> can you please take a look and share any insights? is it a genuine failure due to the new AWS profile or can it be ignored?

Let's re-run and check once more, we used to face this earlier due to low resources (cpu/memory), but current `1000m` & `8Gi` should be sufficient.

**Comment by malayparida2000** [comment]
> > ```
> > [2925:0216/154341.273481:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 3151: Permission denied (13)
> > [3151:0216/154341.288837:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > can you please take a look and share any insights? is it a genuine failure due to the new AWS profile or can it be ignored?
> 
> Let's re-run and check once more, we used to face this earlier due to low resources (cpu/memory), but current `1000m` & `8Gi` should be sufficient.

Failed again for the same reason. Does the 4.13 branch tests have some different config/limits compared to other branches?

**Comment by SanjalKatiyar** [comment]
> Failed again for the same reason. Does the 4.13 branch tests have some different config/limits compared to other branches?

This passed: https://github.com/openshift/release/pull/48993, let's make release-4.13 config same as this "Test" PR...

**Comment by SanjalKatiyar** [comment]
also, plz rebase ur PR with latest `release` `master`...

**Comment by malayparida2000** [comment]
/pj-rehearse pull-ci-red-hat-storage-ocs-operator-main-ocs-operator-bundle-e2e-aws pull-ci-red-hat-storage-ocs-operator-release-4.15-ocs-operator-bundle-e2e-aws pull-ci-red-hat-storage-ocs-operator-release-4.14-ocs-operator-bundle-e2e-aws pull-ci-red-hat-storage-ocs-operator-release-4.13-ocs-operator-bundle-e2e-aws pull-ci-red-hat-storage-ocs-operator-release-4.12-ocs-operator-bundle-e2e-aws

**Comment by malayparida2000** [comment]
/pj-rehearse pull-ci-red-hat-storage-odf-operator-main-odf-operator-e2e-aws pull-ci-red-hat-storage-odf-operator-release-4.15-odf-operator-e2e-aws pull-ci-red-hat-storage-odf-operator-release-4.14-odf-operator-e2e-aws pull-ci-red-hat-storage-odf-operator-release-4.13-odf-operator-e2e-aws pull-ci-red-hat-storage-odf-operator-release-4.12-odf-operator-bundle-e2e-aws

**Comment by malayparida2000** [comment]
/pj-rehearse pull-ci-red-hat-storage-odf-multicluster-orchestrator-main-integration-test pull-ci-red-hat-storage-odf-multicluster-orchestrator-release-4.17-integration-test pull-ci-red-hat-storage-odf-multicluster-orchestrator-release-4.16-integration-test pull-ci-red-hat-storage-odf-multicluster-orchestrator-release-4.15-integration-test pull-ci-red-hat-storage-odf-multicluster-orchestrator-release-4.14-integration-test pull-ci-red-hat-storage-odf-multicluster-orchestrator-release-4.13-integration-test pull-ci-red-hat-storage-odf-multicluster-orchestrator-release-4.12-integration-test

**Comment by malayparida2000** [comment]
/pj-rehearse pull-ci-red-hat-storage-odf-console-master-odf-console-e2e-aws pull-ci-red-hat-storage-odf-console-release-4.14-odf-console-e2e-aws pull-ci-red-hat-storage-odf-console-release-4.13-odf-console-e2e-aws pull-ci-red-hat-storage-odf-console-release-4.12-odf-console-e2e-aws

**Comment by malayparida2000** [comment]
@SanjalKatiyar the odf-console tests are now passing here

**Comment by SanjalKatiyar** [comment]
> @SanjalKatiyar the odf-console tests are now passing here

LGTM.

**Comment by malayparida2000** [comment]
/pj-rehearse pull-ci-red-hat-storage-odf-multicluster-orchestrator-release-4.17-integration-test

**Comment by malayparida2000** [comment]
/pj-rehearse pull-ci-red-hat-storage-ocs-operator-main-ocs-operator-bundle-e2e-aws

**Comment by malayparida2000** [comment]
odf-multicluster-orchestrator-release-4.17-integration-test is failing for some unknown reason, as we have the deadline tomorrow and the test is for 4.17 branch we can not hold the PR anymore so please ignore that failure. ODF failures are packed by Nitin as already failing before this change due to other reasons. I will request to now please provide your approvals.

@agarwal-mudit @iamniting @SanjalKatiyar

**Review by iamniting — APPROVED** [review]

**Review by agarwal-mudit — APPROVED** [review]
/lgtm

**Review by naveenpaul1 — APPROVED** [review]

**Pull request merged**
