### PR TITLE
Serverless: Period jobs on OCP 4.8 nightly

### PR DESCRIPTION
**Pull request by mgencur**
https://issues.redhat.com/browse/SRVCOM-1340

### CODE REVIEW

**Comment by skonto** [comment]
Hi is there a run of these jobs to take a look at?

**Comment by mgencur** [comment]
@skonto Those are the `ci/rehearse` checks that are currently running. So far we had this:
* 4.7 in pre-submits and nightly with slack notifications to serverless-dev
* 4.6 nightly with slack notif (but not in pre-submit)
This PR adds 4.8 to nightly with slack notifications but not pre-submit. The 4.8 setup is using "nightly" build of OCP 4.8 compared with 4.7 which uses "stable". Those are the main differences. I'd expect at some point we'd bring 4.8 to pre-submit checks and move 4.7 to nightly only. We probably want to have pre-submit checks with the latest stable OCP version but save some headaches by moving the rest of checks to nightly jobs only.

**Comment by skonto** [comment]
It seems that the strimzi cluster never came up and the process timed out.

**Comment by mgencur** [comment]
@skonto yeah, we can either block this PR on this or get it merged and fix it later. The nightly job will fail in the mean time until we fix that. It doesn't run in pre-submits so it shouldn't block the PRs. But I don't have time today to look into it. WDYT?

**Comment by mgencur** [comment]
I tried with my 4.8.x cluster and the Strimzi installation was ok. Trying again.

/retest

**Comment by mgencur** [comment]
@skonto think this is ready for integration. The previous failure is now passing: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/18815/rehearse-18815-periodic-ci-openshift-knative-serverless-operator-main-4.8-e2e-aws-ocp-48-continuous/1399357557667008512 , and the upgrade tests failed during cluster de-provisioning. There's nothing to fix on our side.

**Pull request merged**
