### PR TITLE
Make assisted devscripts more configurable

### PR DESCRIPTION
**Pull request by carbonin**
Currently the assisted ZTP workflow sets `DEVSCRIPTS_CONFIG` and also exposes two individual devscripts config variables as individual settings (set in separate steps).

This PR combines  those steps and moves the default settings outside of `DEVSCRIPTS_CONFIG` and into the step command.

This will allow individual jobs to use `DEVSCRIPTS_CONFIG` to set or override anything they need without clobbering or copying the existing workflow defaults.

Related to https://issues.redhat.com/browse/MGMT-13889

For that issue I'll need to override `REDFISH_EMULATOR_IGNORE_BOOT_DEVICE` which wouldn't be possible without creating a new step or copying all of the default `DEVSCRIPTS_CONFIG` into my job. This will allow me to just set `REDFISH_EMULATOR_IGNORE_BOOT_DEVICE` in `DEVSCRIPTS_CONFIG` wherever I need to.

cc @adriengentil

### CODE REVIEW

**Comment by carbonin** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp pull-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-disconnected pull-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-compact-day2-workers pull-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-sno-day2-workers pull-ci-openshift-assisted-service-release-ocm-2.7-e2e-ai-operator-ztp pull-ci-openshift-assisted-service-release-ocm-2.8-e2e-ai-operator-ztp pull-ci-openshift-assisted-service-release-ocm-2.6-e2e-ai-operator-ztp pull-ci-openshift-assisted-service-release-ocm-2.5-e2e-ai-operator-ztp

**Comment by adriengentil** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-sno-day2-workers 
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-compact-day2-workers
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-disconnected
/pj-rehearse pull-ci-openshift-assisted-service-release-ocm-2.8-e2e-ai-operator-ztp

**Review by adriengentil — APPROVED** [review]

**Comment by carbonin** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-compact-day2-workers pull-ci-openshift-assisted-service-release-ocm-2.8-e2e-ai-operator-ztp pull-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-disconnected

**Pull request merged**
