### PR TITLE
Adding more node types with no workflows

### PR DESCRIPTION
**Pull request by paigerube14**

### CODE REVIEW

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-redhat-chaos-prow-scripts-main-rosa-4.15-nightly-krkn-tests-rosa-infra

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-redhat-chaos-prow-scripts-main-rosa-4.15-nightly-krkn-tests-rosa-infra

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-redhat-chaos-prow-scripts-main-rosa-4.15-nightly-krkn-tests-rosa-infra

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-redhat-chaos-prow-scripts-main-rosa-4.15-nightly-krkn-tests-rosa-infra

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-redhat-chaos-prow-scripts-main-rosa-4.15-nightly-krkn-tests-rosa-infra

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-redhat-chaos-prow-scripts-main-rosa-4.15-nightly-krkn-tests-rosa-infra

**Review by shahsahil264 — APPROVED** [review]

**Pull request merged**
