### PR TITLE
Remove upgrade template and presubmit job

### PR DESCRIPTION
**Pull request by 0xmichalis**
One less template to worry about. It seems we are converging on running the upgrade tests as part of the e2e framework.

### CODE REVIEW

**Comment by kwoodson** [comment]
@kargakis 
Where does the upgrade test run now?  Are we replacing this or combining it with e2e?

**Comment by kargakis** [comment]
@kwoodson ever since we started using the update blob to store scale set hashes and compare with VM hashes, the e2e update test essentially became a simple e2e test and the update wasn't touching any VM. That last part I am rewritting into an e2e test.

**Comment by kargakis** [comment]
Also, there are other e2e update tests in the pipeline that are going to exercise updates, eg. the key rotation e2e test.

**Comment by kargakis** [comment]
FWIW here is a WIP PR adding a re-entrancy test: https://github.com/openshift/openshift-azure/pull/831

**Pull request merged**
