### PR TITLE
Set master nodes type for cnv-ci e2e tests

### PR DESCRIPTION
**Pull request by rabin-io**

### CODE REVIEW

**Comment by rabin-io** [comment]
/pj-rehearse pull-ci-openshift-cnv-cnv-ci-release-4.14-e2e-upgrade

**Comment by rabin-io** [comment]
/pj-rehearse pull-ci-openshift-cnv-cnv-ci-release-4.14-e2e-upgrade

**Comment by rabin-io** [comment]
/pj-rehearse pull-ci-openshift-cnv-cnv-ci-release-4.14-e2e-upgrade

**Comment by rabin-io** [comment]
Hi @tiraboschi
I see we are falling on the worker MCP, can we bump the timeout to 15?
What do you think?

```
waiting for update to start
+ oc wait mcp --all --for condition=updating --timeout=5m
machineconfigpool.machineconfiguration.openshift.io/master condition met
error: timed out waiting for the condition on machineconfigpools/worker
make: *** [set_imagecontentsourcepolicy] Error 1
```

**Comment by tiraboschi** [comment]
> Hi @tiraboschi I see we are falling on the worker MCP, can we bump the timeout to 15? What do you think?

 yes, please

**Comment by rabin-io** [comment]
Created a [PR](https://github.com/openshift-cnv/cnv-ci/pull/81) for it.

**Pull request closed without merging**
