### PR TITLE
[kn-plugin-event] Fix binary build with mage

### PR DESCRIPTION
**Pull request by dsimansk**
Reset default GOFLAGS in builder image.

/cc @cardil

### CODE REVIEW

**Comment by cardil** [comment]
Why is this needed?

**Comment by cardil** [comment]
Hmm, I think the better would be to update `openshift/e2e-test.sh` in the project instead. That would help avoid possible confusion in the future.

WDYT @dsimansk?

**Comment by dsimansk** [comment]
> Hmm, I think the better would be to update `openshift/e2e-test.sh` in the project instead. That would help avoid possible confusion in the future.
> 
> WDYT @dsimansk?

I don't think that would address the flag `GOFLAGS` values when `./mage` is called in build phase. Or do you suggest to wrap `./mage` script into an openshift CI specific script?

**Comment by cardil** [comment]
Right. I'll integrate that change in https://github.com/openshift/release/pull/34573

**Pull request closed without merging**
