### PR TITLE
[azure] enable proxy mirror registry in bastion host

### PR DESCRIPTION
**Pull request by jianlinliu**
followup https://github.com/openshift/release/pull/28189:
1. reuse ignition-bastionhost from https://github.com/openshift/release/pull/28186
2. enable proxy mirror registry listening on 6001 and 6002 in bastion host
3. support Azure mag cloud login
4. correct mirror registry's rootdirectory

### CODE REVIEW

**Comment by jianlinliu** [comment]
cc @jianli-wei and @yunjiang29 for review

**Comment by jianli-wei** [comment]
> @yunjiang29 I noticed an issue in registry config yaml - https://github.com/openshift/release/pull/28371/files#diff-8d83a78a86836bb13a2148319813b32eeae5cf7ded923c9095672ee55e3ce348, I guess flexy-template also has this issue, pls help fix it, also review this PR. cc @jianli-wei for review too.

@jianlinliu What's the issue you met?

**Comment by jianlinliu** [comment]
> What's the issue you met?
The mirror registry did not use mounted host directory - /opt/mirror-registry/registry-6001/data

**Comment by yunjiang29** [comment]
> > What's the issue you met?
> 
> The mirror registry did not use mounted host directory - /opt/mirror-registry/registry-6001/data

so in Prow CI, `/var/lib/registry` is available for three registry servers? How did you find this issue?

**Comment by jianlinliu** [comment]
> so in Prow CI, /var/lib/registry is available for three registry servers? 

 "/var/lib/registry" is for container itself, per my understanding, even no volume is mounted to the directory, docker-registry will create it if there is no such directory.

> How did you find this issue?
During testing, I logged into the bastion host, check uploaded images data in host's /opt/mirror-registry/registry-6001/data, no any data there, found the configuration issue.

**Comment by yunjiang29** [comment]
fixed in flexy.

**Pull request merged**
