### PR TITLE
[WIP]MGMT-16060: Add bare-metal sno recert test

### PR DESCRIPTION
**Pull request by wangke19**
Recert with arm64 baremetal SNO

### CODE REVIEW

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-baremetalds-sno-recert-rename-f14

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-baremetalds-sno-recert-rename-f14

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-baremetalds-sno-recert-rename-f14

**Comment by wangke19** [comment]
/pj-rehearse  periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-baremetal-pxe-sno-agent-ipv4-recert-connected-f14

**Comment by wangke19** [comment]
/pj-rehearse  periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-baremetal-pxe-sno-agent-ipv4-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-pxe-sno-agent-ipv4-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-pxe-sno-agent-ipv4-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-pxe-sno-agent-ipv4-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-pxe-sno-agent-ipv4-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-pxe-sno-agent-ipv4-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-baremetalds-sno-recert-cluster-rename-etcd-encryption

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-baremetalds-sno-recert-cluster-rename-etcd-encryption

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-baremetalds-sno-recert-cluster-rename-etcd-encryption

**Comment by wangke19** [comment]
/pj-rehearse pull-ci-openshift-gcp-pd-csi-driver-release-4.16-e2e-gcp-csi-extended

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-vsphere-ipi-compact-etcd-encryption-f28

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-baremetalds-sno-recert-cluster-rename-etcd-encryption

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-pxe-sno-agent-ipv4-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-pxe-sno-agent-ipv4-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-baremetal-pxe-sno-agent-ipv4-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-pxe-sno-agent-ipv4-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-pxe-sno-agent-ipv4-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-pxe-sno-agent-ipv4-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-pxe-sno-agent-ipv4-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-pxe-sno-agent-ipv4-recert

**Comment by wangke19** [comment]
/pj-rehearse  periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-static-sno-agent-ipv4-fips-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-pxe-sno-agent-ipv4-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-static-sno-agent-ipv4-fips-recert

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-pxe-sno-agent-ipv4-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-pxe-sno-agent-ipv4-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-static-sno-agent-ipv4-fips-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-static-sno-agent-ipv4-fips-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-static-sno-agent-ipv4-fips-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-static-sno-agent-ipv4-fips-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-static-sno-agent-ipv4-fips-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-static-sno-agent-ipv4-fips-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-static-sno-agent-ipv4-fips-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-static-sno-agent-ipv4-fips-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-static-sno-agent-ipv4-fips-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-static-sno-agent-ipv4-fips-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-static-sno-agent-ipv4-fips-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-baremetal-static-sno-agent-ipv4-fips-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-baremetalds-sno-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-baremetalds-sno-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-baremetalds-sno-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-baremetalds-sno-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-baremetalds-sno-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-baremetalds-sno-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-baremetalds-sno-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-baremetalds-sno-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-baremetalds-sno-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-baremetalds-sno-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-baremetalds-sno-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-baremetalds-sno-recert

**Comment by wangke19** [comment]
pj-rehearse  periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-baremetal-pxe-sno-agent-ipv4-fips-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-baremetal-pxe-sno-agent-ipv4-fips-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-baremetal-pxe-sno-agent-ipv4-fips-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-baremetal-pxe-sno-agent-ipv4-fips-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-baremetal-pxe-sno-agent-ipv4-fips-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-baremetal-pxe-sno-agent-ipv4-fips-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-baremetal-pxe-sno-agent-ipv4-fips-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-baremetal-pxe-sno-agent-ipv4-fips-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-baremetal-pxe-sno-agent-ipv4-fips-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-baremetal-pxe-sno-agent-ipv4-fips-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-baremetal-pxe-sno-agent-ipv4-fips-recert

**Comment by wangke19** [comment]
This PR is based on ARM SNO, but for recert, we don't support ARM currently. Closing it.

**Pull request closed without merging**
