### PR TITLE
[WIP]Recert the cluster with etcd encryption

### PR DESCRIPTION
**Pull request by wangke19**
Recert the cluster with etcd encryption

### CODE REVIEW

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-aws-ipi-sno-etcd-encryption-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ipi-sno-etcd-encryption-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ipi-sno-etcd-encryption-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-aws-ipi-sno-etcd-encryption-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ipi-sno-etcd-encryption-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-aws-ipi-sno-etcd-encryption-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ipi-sno-etcd-encryption-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ipi-sno-etcd-encryption-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ipi-sno-etcd-encryption-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-aws-ipi-sno-etcd-encryption-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-aws-ipi-sno-etcd-encryption-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ipi-sno-etcd-encryption-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-e2e-aws-ipi-sno-etcd-encryption-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-aws-ipi-sno-etcd-encryption-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ipi-sno-etcd-encryption-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-e2e-aws-ipi-sno-etcd-encryption-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ipi-sno-etcd-encryption-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-aws-ipi-sno-etcd-encryption-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ipi-sno-etcd-encryption-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-aws-ipi-sno-etcd-encryption-recert

**Comment by mresvanis** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-aws-ipi-sno-etcd-encryption-recert

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.14-e2e-aws-ipi-sno-etcd-encryption-recert

**Comment by omertuc** [comment]
This will not work, we don't support that yet

**Comment by wangke19** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-recert-main-4.15-e2e-aws-ipi-sno-etcd-encryption-recert

**Comment by omertuc** [comment]
Ticket https://issues.redhat.com/browse/MGMT-17267

**Pull request closed without merging**
