### PR TITLE
Add more checks for kube-scheduler

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
As of now, we are not checking bindata, deps etc. Adding those checks

### CODE REVIEW

**Comment by ravisantoshgudimetla** [comment]
The rehearse is expected to fail because the bin data mismatch in current HEAD. https://github.com/openshift/cluster-kube-scheduler-operator/pull/79 should address the mismatch.

**Comment by sjenning** [comment]
/lgtm
@smarterclayton @stevekuznetsov could one of you force merge this (see https://github.com/openshift/release/pull/3242#issuecomment-476764078)

**Comment by ravisantoshgudimetla** [comment]
@sjenning - These are not required jobs, so merge would continue.

**Comment by sjenning** [comment]
so they aren't.  nevermind!

**Pull request merged**
