### PR TITLE
[LPTOCPCI-726] Add jobs for the interop-ocp-watcher-bot

### PR DESCRIPTION
**Pull request by calebevans**
This pull request will automate weekly status messages for our team.

Example of message: https://redhat-internal.slack.com/archives/C04PK4QPSR1/p1695685347637819
Repo for bot: https://github.com/CSPI-QE/interop-ocp-watcher-bot

### CODE REVIEW

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-rhpit-interop-tests-main-weekly_trigger-ocp-self-managed-lp-watcher-bot-message

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-rhpit-interop-tests-main-weekly_trigger-ocp-self-managed-lp-watcher-bot-message

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-rhpit-interop-tests-main-weekly_trigger-ocp-self-managed-lp-watcher-bot-message

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-rhpit-interop-tests-main-weekly_trigger-ocp-self-managed-lp-watcher-bot-message

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-rhpit-interop-tests-main-weekly_trigger-ocp-self-managed-lp-watcher-bot-message

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-rhpit-interop-tests-main-weekly_trigger-ocp-self-managed-lp-watcher-bot-message

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-rhpit-interop-tests-main-weekly_trigger-ocp-self-managed-lp-watcher-bot-message

**Review by ascerra — APPROVED** [review]

**Pull request merged**
