### PR TITLE
[INTEROP-7445] Update Serverless for OCP 4.17.

### PR DESCRIPTION
**Pull request by dfrazzette**
Update ci-operator/confg for Serverless to OCP 4.17; update go builder image to 1.22.

### CODE REVIEW

**Comment by mgencur** [comment]
This PR looks good. Most tests passed but getting the alerts failed at the end. I will need to try this manually and see how 4.17 differs from previous versions where it worked.

**Comment by mgencur** [comment]
@dfrazzette Sent this [pull request](https://github.com/openshift-knative/serverless-operator/pull/2770) to fix the alerts. Might be worth re-running the check once the PR is merged.

**Comment by dfrazzette** [comment]
/pj-rehearse periodic-ci-openshift-knative-serverless-operator-main-ocp4.17-lp-interop-operator-e2e-interop-aws-ocp417

**Comment by dfrazzette** [comment]
/pj-rehearse periodic-ci-openshift-knative-serverless-operator-main-ocp4.17-lp-interop-operator-e2e-interop-aws-ocp417

**Comment by dfrazzette** [comment]
@mgencur - All tests passed! Can you add `/lgtm` and `/approve` labels to this PR so openshift-merge-bot can merge? Thank you!

**Comment by mgencur** [comment]
@dfrazzette Looks good!

/lgtm

**Pull request merged**
