### PR TITLE
upgrade go to 1.16

### PR DESCRIPTION
**Pull request by ycao56**
Signed-off-by: Yu Cao <ycao@redhat.com>

### CODE REVIEW

**Review by willkutler — APPROVED** [review]

**Comment by dhaiducek** [comment]
The `sonarcloud` image will also need to be updated for each `postsubmit` job:
https://github.com/openshift/release/blob/2637b3c018ab847a2bb1f6d7901801eeb195171b/ci-operator/jobs/open-cluster-management/cert-policy-controller/open-cluster-management-cert-policy-controller-main-postsubmits.yaml#L77

**Review by dhaiducek — APPROVED** [review]

**Pull request merged**
