### PR TITLE
openshift/os: Add CI for c9s

### PR DESCRIPTION
**Pull request by cgwalters**

### CODE REVIEW

**Review by travier — APPROVED** [review]
/lgtm

**Comment by travier** [comment]
/hold
Are the skip rules changes expected?

**Comment by cgwalters** [comment]
OK, I don't understand the config sharding failure.  I've reread the docs a few times and verified via e.g. 

```
$ echo ci-operator/config/openshift/os/*c9s*.yaml
ci-operator/config/openshift/os/openshift-os-c9s.yaml
$
```
that my glob matches.

Why do we need this manual sharding thing versus e.g. running `sha256sum(configname)` and creating configmaps from e.g. `00..ff` or so (or if fewer than 256 configmaps are desired, make that mod N, e.g. 16 or 32 or whatever)

**Comment by cgwalters** [comment]
Pushed https://github.com/openshift/os/commit/7d1200471a4f1bb48428a565466f4781db1b0b42

**Comment by cgwalters** [comment]
Hum odd...I thought we'd be able to...oh, I see it's because we had to modify the sharding config.  I [had a random idea above](https://github.com/openshift/release/pull/20804#issuecomment-891193475) on how to avoid the manual sharding.

**Review by miabbott — APPROVED** [review]

**Review by petr-muller — APPROVED** [review]

**Comment by cgwalters** [comment]
OK had to repush because prowgen changed semantics.

**Pull request merged**
