### PR TITLE
OKD: add optional openstack test for fcos branch

### PR DESCRIPTION
**Pull request by vrutkovs**
Add an optional openstack test in `fcos` branch of installer

### CODE REVIEW

**Comment by smarterclayton** [comment]
Is the generator not working for you?  Why are you manually creating the job?

**Comment by vrutkovs** [comment]
That's a copypaste from OCP jobs btw, I'd rather stay close to those.

Checking generator in https://github.com/openshift/release/pull/6976

**Comment by vrutkovs** [comment]
It appears there is no autogenerator for openstack yet:

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/6976/rehearse-6976-pull-ci-openshift-installer-fcos-e2e-openstack/10

>Unsupported cluster type 'openstack'

**Comment by vrutkovs** [comment]
Closing in favor of https://github.com/openshift/release/pull/6976

**Pull request closed without merging**
