### PR TITLE
Adding boskos configuration for libvirt-s390x leases

### PR DESCRIPTION
**Pull request by jaypoulz**
Blocks https://github.com/openshift/release/pull/7161

### CODE REVIEW

**Comment by jaypoulz** [comment]
@hongkailiu @alvaroaleman @crawford @stevekuznetsov Once the tests complete, could I get this pushed through? It is functionally an extension of https://github.com/openshift/ci-tools/pull/506 and is needed for leasing for https://github.com/openshift/release/pull/7161

**Comment by hongkailiu** [comment]
/lgtm

/hold
cancel if you are ready.

**Comment by jaypoulz** [comment]
/hold cancel
Thanks guys!

**Pull request merged**
