### PR TITLE
odf-console master CI: upgrade OCP to 4.17

### PR DESCRIPTION
**Pull request by alfonsomthd**
- Updated `master` job config.
- Added config files for `release-4.16`.

### CODE REVIEW

**Review by GowthamShanmugam — COMMENTED** [review]
LGTM

**Comment by psalajova** [comment]
/pj-rehearse pull-ci-red-hat-storage-odf-console-release-4.16-images

**Comment by alfonsomthd** [comment]
@SanjalKatiyar @bipuladh @GowthamShanmugam @umangachapagain Please tag as all jobs were successful.

**Pull request merged**
