### PR TITLE
New repository component deployments.

### PR DESCRIPTION
**Pull request by emilvberglind**
*Secret copy from vault.
*API deployment.
*UI deployments.

### CODE REVIEW

**Comment by petr-muller** [comment]
@smg247 I think we could salvage this one (either directly or reuse what Emil did and close this one)
/remove-lifecycle rotten

**Comment by petr-muller** [comment]
boo

/meow
/pony

**Comment by smg247** [comment]
/uncc @smg247 
this has been completed in: https://github.com/openshift/release/pull/25918

**Pull request closed without merging**
