### PR TITLE
Change cloud provider for testing on PROW CI

### PR DESCRIPTION
**Pull request by musienko-maxim**
We have trouble with launching tests on the PROW CI. 
The main reason is problems with GCP. Examples with problems in the PRs:
https://github.com/devfile/devworkspace-operator/pull/674
https://github.com/devfile/devworkspace-operator/pull/673 
This PR should fix it.

### CODE REVIEW

**Review by amisevsk — APPROVED** [review]

**Review by JPinkney — APPROVED** [review]

**Review by amisevsk — COMMENTED** [review]
It looks like che-happy-path also needs to be excluded [here](https://github.com/openshift/release/blob/master/ci-operator/jobs/devfile/devworkspace-operator/devfile-devworkspace-operator-main-presubmits.yaml)

**Review by amisevsk — APPROVED** [review]

**Pull request merged**
