### PR TITLE
Cni output

### PR DESCRIPTION
**Pull request by paigerube14**
Output file name was not set causing syntax error

### CODE REVIEW

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aro-4.13-nightly-x86-perfscale-aro-node-density-cni-6nodes-periodic

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.13-nightly-x86-perfscale-aws-node-density-heavy-24nodes-periodic periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-gcp-4.13-nightly-x86-perfscale-gcp-node-density-cni-24nodes-periodic periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-nightly-x86-perfscale-aws-control-plane-24nodes-periodic periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-nightly-x86-perfscale-aws-data-path-9nodes-periodic

**Review by afcollins — APPROVED** [review]
LGTM. Let's run the smallest test we can for cni at least, but I don't expect any issues.

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-release-4.14-qe-perfscale-aws-ovn-small-node-density-cni

**Comment by jtaleric** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-release-4.14-qe-perfscale-aws-ovn-small-node-density-cni

**Comment by afcollins** [comment]
Checked these failures and they aren't related to the fix here.

4.14-nightly smoketest failed:
```
time="2023-10-04 18:30:21" level=error msg="10m0s timeout reached" file="job.go:211"
```

4.13-nightly failed:
```
Cluster initialization failed because one or more operators are not functioning properly.
```

Please merge.

**Pull request merged**
