### PR TITLE
Adds ibmcloud e2e ci config entry

### PR DESCRIPTION
**Pull request by srcarrier**
Opening initial `/release` PR to add an entry for running ibmcloud e2e on `/openshift/cluster-api-provider-ibmcloud`

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
generally looks good and makes sense to me, did we have an open PR to create the `openshift-e2e-ibmcloud` workflow?

**Comment by srcarrier** [comment]
> generally looks good and makes sense to me, did we have an open PR to create the `openshift-e2e-ibmcloud` workflow?

@elmiko I'm not certain. Would that be defined somewhere in this repo or a different one? Do you have a pointer to where an equivalent workflow has been defined for another cloud provider? I'll follow up on our end and make sure we get a PR open if one doesn't already exist.
Thanks for reviewing this Michael - appreciate it

**Comment by JoelSpeed** [comment]
> Would that be defined somewhere in this repo or a different one?

That would included in the step-registry within this repo, IIUC this is already been worked on in https://github.com/openshift/release/pull/20433, we won't be able to merge this until that PR has been merged

**Comment by elmiko** [comment]
thanks @JoelSpeed, that's what i was curious about

**Review by elmiko — COMMENTED** [review]
/lgtm
/hold waiting for #20433 to merge

**Comment by JoelSpeed** [comment]
@srcarrier Are you able to run the code generation? I'm not sure if the images are public or not. If you can't/don't have the time, we can pick this up and carry it across the line

**Comment by cjschaef** [comment]
@JoelSpeed I believe @srcarrier  is out for the year, will see if I can pull updates in...

**Comment by cjschaef** [comment]
Opened this PR with rebase and job generation
https://github.com/openshift/release/pull/24679

**Comment by jeffnowicki** [comment]
@srcarrier you can **CLOSE** this PR... @cjschaef [PR](https://github.com/openshift/release/pull/24679) will replace this PR. Thanks.

**Comment by cjschaef** [comment]
https://github.com/openshift/release/pull/24679 has merged and this PR is no longer needed

**Pull request closed without merging**
