### PR TITLE
Update junit file names for tempo operator

### PR DESCRIPTION
**Pull request by shakyav**
[LPTOCPCI-916](https://issues.redhat.com/browse/LPTOCPCI-916)

### CODE REVIEW

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.14-lp-interop-tempo-interop-aws

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.14-lp-interop-tempo-interop-aws

**Review by calebevans — APPROVED** [review]
/lgtm

**Comment by IshwarKanse** [comment]
Hi @shakyav if you want to remove the extra .xml from the junit file name, you can simply remove it from. https://github.com/openshift/release/blob/master/ci-operator/step-registry/distributed-tracing/tests/tempo/distributed-tracing-tests-tempo-ref.yaml#L17 Just change the file name from junit_tempo_test_results.xml to junit_tempo_test_results However this doesn't affect the failures reported in the junit files, I'll update the linked issue.

**Comment by shakyav** [comment]
> Hi @shakyav if you want to remove the extra .xml from the junit file name, you can simply remove it from. https://github.com/openshift/release/blob/master/ci-operator/step-registry/distributed-tracing/tests/tempo/distributed-tracing-tests-tempo-ref.yaml#L17 Just change the file name from junit_tempo_test_results.xml to junit_tempo_test_results However this doesn't affect the failures reported in the job run and not in the junit files, The issue is related to the tool cleanup operation after a test case is finished. I'll update the linked issue.

ok I'll update the PR to rename junit file as you mentioned

**Pull request merged**
