### PR TITLE
Bug 2007580: Cilium Azure: remove unidling test from TEST_SKIPS

### PR DESCRIPTION
**Pull request by vrutkovs**
This test would now be skipped in the test suite - see https://bugzilla.redhat.com/show_bug.cgi?id=1957146

@errordeveloper PTAL

### CODE REVIEW

**Comment by vrutkovs** [comment]
/hold

for rehearsals

**Review by errordeveloper — APPROVED** [review]
Thanks @vrutkovs!

**Comment by vrutkovs** [comment]
New failures:
```
[sig-network] Services should be able to update service type to NodePort listening on same port number but different protocols [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-network-edge][Conformance][Area:Networking][Feature:Router] The HAProxy router should pass the gRPC interoperability tests [Suite:openshift/conformance/parallel/minimal]
```

Lets see if these are flakes

/retest

**Comment by vrutkovs** [comment]
no network errors, lets give this another try

/retest

**Comment by errordeveloper** [comment]
Is rebase needed?

**Comment by vrutkovs** [comment]
No, I think we're good here, just needs approval from test owners

/cc @wking

**Comment by vrutkovs** [comment]
Hmm, Cilium stopped working on 4.9, probably due to 1.22 rebase.

@errordeveloper any chance you could have a look?

**Comment by errordeveloper** [comment]
> Hmm, Cilium stopped working on 4.9, probably due to 1.22 rebase.

@vrutkovs ah, of course, so this pipeline did it's job :)

**Comment by errordeveloper** [comment]
Updating Cilium to 1.10.3 as first order of business: https://github.com/openshift/release/pull/21293

**Comment by errordeveloper** [comment]
@vrutkovs I think this PR does need a rebase to incorporate #21293.

**Comment by vrutkovs** [comment]
Rebase is not necessary really (`clonerefs` would automatically rebase the code on latest master), iiuc the rehearsals already use 1.10

**Comment by errordeveloper** [comment]
> Rebase is not necessary really (`clonerefs` would automatically rebase the code on latest master), iiuc the rehearsals already use 1.10

Ha! I see... as a contributor I find this behaviour surprising, but I suppose it's something that suits OpenShift team's workflow.

**Comment by errordeveloper** [comment]
@vrutkovs I'm not sure why these still run:
```
: [sig-network-edge][Feature:Idling] Unidling should work with TCP (when fully idled) [Skipped:Network/OVNKubernetes] [Suite:openshift/conformance/parallel]
: [sig-network-edge][Feature:Idling] Unidling should work with UDP [Suite:openshift/conformance/parallel]
: [sig-network-edge][Feature:Idling] Unidling should work with TCP (while idling) [Skipped:Network/OVNKubernetes] [Suite:openshift/conformance/parallel]
```
Has something else changed since you opened this PR?

And these look new to me, perhaps could be something for Cilium team to look into?

```
: [sig-network] Services should be able to update service type to NodePort listening on same port number but different protocols [Suite:openshift/conformance/parallel] [Suite:k8s]

fail [k8s.io/kubernetes@v1.22.1/test/e2e/network/service.go:1288]: Unexpected error:
    <*errors.errorString | 0xc000a64410>: {
        s: "service is not reachable within 2m0s timeout on endpoint 10.0.128.4:32222 over UDP protocol",
    }
    service is not reachable within 2m0s timeout on endpoint 10.0.128.4:32222 over UDP protocol
occurred

: [sig-network] Services should respect internalTrafficPolicy=Local Pod to Pod [Feature:ServiceInternalTrafficPolicy] [Skipped:Network/OVNKubernetes] [Suite:openshift/conformance/parallel] [Suite:k8s]

fail [k8s.io/kubernetes@v1.22.1/test/e2e/network/service.go:2107]: expected error when trying to connect to cluster IP
Expected an error to have occurred.  Got:
    <nil>: nil
```

And this one I'm not sure how to interpret. Where can we find iperf results and how is the baseline calculated? Maybe this test is just flaky?
```
: [sig-network] Networking IPerf2 [Feature:Networking-Performance] should run iperf2 [Suite:openshift/conformance/parallel] [Suite:k8s]

fail [github.com/onsi/ginkgo@v4.7.0-origin.0+incompatible/internal/leafnodes/runner.go:113]: Sep  9 10:12:53.507: iperf2 MB/s received below baseline of 90 for client ci-op-1z8lv07i-6a060-bg2bj-worker-eastus23-r8928 to server ci-op-1z8lv07i-6a060-bg2bj-worker-eastus22-scqnk: 7
````

**Comment by vrutkovs** [comment]
>perhaps could be something for Cilium team to look into?

Unidling should be skipped for disabled CNO, seems a regression on our end. I'll add these to be skipped for now.

>[sig-network] Services should be able to update service type to NodePort listening on same port number but different protocols [Suite:openshift/conformance/parallel] [Suite:k8s]
>[sig-network] Services should respect internalTrafficPolicy=Local Pod to Pod [Feature:ServiceInternalTrafficPolicy] [Skipped:Network/OVNKubernetes] [Suite:openshift/conformance/parallel] [Suite:k8s]

These seems to be coming in k8s 1.22, I'm fine with skipping them for now

> Networking IPerf2

These are also upstream things - https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/test/e2e/network/networking_perf.go#L43

**Comment by stbenjam** [comment]
/retitle Bug 2007580: Cilium Azure: remove unidling test from TEST_SKIPS

@errordeveloper @vrutkovs  Cilium looks to still be in bad shape. I've opened a bug for it, it seems to be failing the idling tests as well as the nodeport and internal traffic policy tests.

**Comment by errordeveloper** [comment]
@stbenjam thanks for the heads-up. I will let the team know.

**Comment by vrutkovs** [comment]
Closed in favor of #23894

**Pull request closed without merging**
