### PR TITLE
Update cluster-nfd-operator configs so they use the ci OO workflows.

### PR DESCRIPTION
**Pull request by emilvberglind**

### CODE REVIEW

**Review by ArangoGutierrez — APPROVED** [review]
looks good, it should become a real PR

**Comment by ArangoGutierrez** [comment]
Looks like upgrades are still not working, is this maybe something related to the project it self (NFD) or a Prow related known thing? 
@emilvberglind @stevekuznetsov ? otherwise PR lgtm

**Comment by emilvberglind** [comment]
> Looks like upgrades are still not working, is this maybe something related to the project it self (NFD) or a Prow related known thing?
> @emilvberglind @stevekuznetsov ? otherwise PR lgtm

I believe the upgrade failures are related to this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1981872 - I do not think they are specific to this operator.

**Comment by ArangoGutierrez** [comment]
Could we remove the upgrade job for now? and save it on a Jira card as TODO once https://bugzilla.redhat.com/show_bug.cgi?id=1981872 is Fixed?

**Comment by emilvberglind** [comment]
> Could we remove the upgrade job for now? and save it on a Jira card as TODO once https://bugzilla.redhat.com/show_bug.cgi?id=1981872 is Fixed?

Sure, I can do that. I was, perhaps naively, hoping that the upgrade issues would've been resolved by now :)

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
