### PR TITLE
Switch Compliance Operator CI from aws to quay-aws profile

### PR DESCRIPTION
**Pull request by rhmdnd**
secret bootstrap and boskos configs: https://github.com/openshift/release/pull/47815
adding new cluster profile in ci-tools: https://github.com/openshift/ci-tools/pull/3899

### CODE REVIEW

**Comment by rhmdnd** [comment]
The following PRs will need to land to resolve the `invalid cluster profile "quay-aws"` errors:

https://github.com/openshift/release/pull/47815
https://github.com/openshift/ci-tools/pull/3899

**Comment by rhmdnd** [comment]
Most recent failures are due to missing ssh keys:

```
/bin/bash: line 19: /var/run/secrets/ci.openshift.io/cluster-profile/ssh-publickey: No such file or directory
```

**Comment by rhmdnd** [comment]
/pj-rehearse ci/rehearse/ComplianceAsCode/compliance-operator/master/e2e-aws-parallel
/pj-rehearse ci/rehearse/ComplianceAsCode/compliance-operator/master/e2e-aws-serial

**Comment by rhmdnd** [comment]
Trying a couple jobs now to see if the base domain works.

**Comment by rhmdnd** [comment]
/pj-rehearse pull-ci-ComplianceAsCode-compliance-operator-master-e2e-aws-parallel
/pj-rehearse pull-ci-ComplianceAsCode-compliance-operator-master-e2e-aws-serial

**Comment by rhmdnd** [comment]
/pj-rehearse periodic-ci-ComplianceAsCode-content-master-e2e-aws-ocp4-stig-weekly

**Comment by Vincent056** [comment]
```
    helpers.go:808: Result - Name: e2e-stig-master-coreos-vsyscall-kernel-argument - Status: INFO - Severity: medium
    helpers.go:815: E2E-FAILURE: The expected result for the coreos_vsyscall_kernel_argument rule didn't match. Expected 'FAIL', Got 'INFO'
```
Didn't we just changed that with https://github.com/ComplianceAsCode/content/commit/0a23020a783d0c6f34adeeac28c5f5a088c847a4

**Comment by rhmdnd** [comment]
> ```
>     helpers.go:808: Result - Name: e2e-stig-master-coreos-vsyscall-kernel-argument - Status: INFO - Severity: medium
>     helpers.go:815: E2E-FAILURE: The expected result for the coreos_vsyscall_kernel_argument rule didn't match. Expected 'FAIL', Got 'INFO'
> ```
> 
> Didn't we just changed that with [ComplianceAsCode/content@0a23020](https://github.com/ComplianceAsCode/content/commit/0a23020a783d0c6f34adeeac28c5f5a088c847a4)

Yeah - not sure if periodic jobs cache the state of the repository or something?

Looks like the cluster provisioning is working though, so that means we're at least using the new profile.

**Comment by rhmdnd** [comment]
Hitting quota issues:

```
level=error msg=Error: error creating EC2 VPC: VpcLimitExceeded: The maximum number of VPCs has been reached.
level=error msg=	status code: 400, request id: a271fcac-63cf-4dec-87f5-176c8ab9fde9
level=error
```

**Comment by rhmdnd** [comment]
/pj-rehearse pull-ci-ComplianceAsCode-compliance-operator-master-e2e-aws-parallel

**Comment by rhmdnd** [comment]
/pj-rehearse periodic-ci-ComplianceAsCode-content-master-e2e-aws-rhcos4-stig-weekly
/pj-rehearse periodic-ci-ComplianceAsCode-content-master-e2e-aws-ocp4-high-weekly
/pj-rehearse periodic-ci-ComplianceAsCode-content-master-e2e-aws-ocp4-high-node-weekly
/pj-rehearse periodic-ci-ComplianceAsCode-content-master-e2e-aws-ocp4-pci-dss-node-weekly
/pj-rehearse periodic-ci-ComplianceAsCode-content-master-e2e-aws-ocp4-e8-weekly
/pj-rehearse periodic-ci-ComplianceAsCode-content-master-e2e-aws-ocp4-moderate-weekly
/pj-rehearse periodic-ci-ComplianceAsCode-content-master-e2e-aws-rhcos4-moderate-weekly

**Comment by rhmdnd** [comment]
/pj-rehearse periodic-ci-ComplianceAsCode-content-master-e2e-aws-ocp4-high-node-weekly

**Comment by Vincent056** [comment]
periodic-ci-ComplianceAsCode-content-master-e2e-aws-ocp4-moderate-weekly

**Comment by rhmdnd** [comment]
/pj-rehearse periodic-ci-ComplianceAsCode-content-master-e2e-aws-ocp4-moderate-weekly

**Comment by rhmdnd** [comment]
/pj-rehearse periodic-ci-ComplianceAsCode-content-master-e2e-aws-rhcos4-moderate-weekly

**Comment by rhmdnd** [comment]
/pj-rehearse periodic-ci-ComplianceAsCode-content-master-e2e-aws-ocp4-e8-weekly

**Comment by rhmdnd** [comment]
/pj-rehearse periodic-ci-ComplianceAsCode-content-master-e2e-aws-ocp4-pci-dss-node-weekly

**Comment by rhmdnd** [comment]
/pj-rehearse periodic-ci-ComplianceAsCode-content-master-e2e-aws-rhcos4-stig-weekly

**Comment by rhmdnd** [comment]
/pj-rehearse periodic-ci-ComplianceAsCode-content-master-e2e-aws-rhcos4-moderate-weekly

**Comment by rhmdnd** [comment]
The ocp4-pci-dss-node-weekly and rhcos4-stig-weekly results failed because of things we need to update in the profiles themselves. They aren't failing due to the cluster profile switch. The ocp4-e8-weekly failure just hasn't been rerun from last week, which failed from VPC issues.

**Pull request merged**
