### PR TITLE
Adding the ability for config-updater to get routes in the multi arch release namespaces

### PR DESCRIPTION
**Pull request by bradmwilliams**
This commit is to resolve a failure running the master-core-dry for PR #6452 

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/6452/pull-ci-openshift-release-master-core-dry/10950

### CODE REVIEW

**Comment by petr-muller** [comment]
Applied the admin config.

**Comment by bradmwilliams** [comment]
Thanks Petr!

**Pull request merged**
