### PR TITLE
[SDN-1753]: add v4 single stack (optional, manual run) presubmit job to o/ovnk

### PR DESCRIPTION
**Pull request by jluhrsen**

### CODE REVIEW

**Comment by jluhrsen** [comment]
@abhat, this seems to do what I want. the baremetal jobs seem to have a high failure rate on bringup/install so assuming just flaky infra. but when the clusters do install the e2e's are passing. [4.10 example rehearsal job](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/27192/rehearse-27192-pull-ci-openshift-ovn-kubernetes-release-4.11-e2e-metal-ipi-ovn-ipv4/1506404595021123584). Then taking the must-gather
tar with the KAS tool, you can describe the network to verify that we are indeed only running v4:

```
❯ kubectl --kubeconfig=/tmp/kk describe network -A
Name:         cluster
Namespace:    
Labels:       <none>
Annotations:  networkoperator.openshift.io/ovn-cluster-initiator: 192.168.111.20
API Version:  operator.openshift.io/v1
Kind:         Network
Metadata:
  Creation Timestamp:  2022-03-22T23:49:15Z
  Generation:          62
  Managed Fields:
    API Version:  operator.openshift.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:networkoperator.openshift.io/ovn-cluster-initiator:
      f:spec:
        f:clusterNetwork:
        f:defaultNetwork:
          f:ovnKubernetesConfig:
            f:gatewayConfig:
            f:genevePort:
            f:mtu:
            f:policyAuditConfig:
              f:destination:
              f:maxFileSize:
              f:rateLimit:
              f:syslogFacility:
          f:type:
        f:deployKubeProxy:
        f:disableMultiNetwork:
        f:disableNetworkDiagnostics:
        f:logLevel:
        f:managementState:
        f:observedConfig:
        f:operatorLogLevel:
        f:serviceNetwork:
        f:unsupportedConfigOverrides:
        f:useMultiNetworkPolicy:
      f:status:
        f:readyReplicas:
        f:version:
    Manager:      cluster-network-operator/operconfig
    Operation:    Apply
    Time:         2022-03-22T23:49:50Z
    API Version:  operator.openshift.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:clusterNetwork:
        f:defaultNetwork:
          f:type:
        f:disableNetworkDiagnostics:
        f:managementState:
        f:observedConfig:
        f:serviceNetwork:
        f:unsupportedConfigOverrides:
      f:status:
        f:readyReplicas:
    Manager:      cluster-network-operator/clusterconfig
    Operation:    Apply
    Time:         2022-03-22T23:50:08Z
    API Version:  operator.openshift.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
        f:version:
    Manager:      cluster-network-operator
    Operation:    Update
    Time:         2022-03-22T23:49:15Z
    API Version:  operator.openshift.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:additionalNetworks:
    Manager:         openshift-tests
    Operation:       Update
    Time:            2022-03-23T01:27:03Z
  Resource Version:  195752
  UID:               ec61f033-5e9c-451f-9f2a-df1e464f2ca0
Spec:
  Additional Networks:
  Cluster Network:
    Cidr:         10.128.0.0/14
    Host Prefix:  23
  Default Network:
    Ovn Kubernetes Config:
      Gateway Config:
        Routing Via Host:  false
      Geneve Port:         6081
      Mtu:                 1400
      Policy Audit Config:
        Destination:            null
        Max File Size:          50
        Rate Limit:             20
        Syslog Facility:        local0
    Type:                       OVNKubernetes
  Deploy Kube Proxy:            false
  Disable Multi Network:        false
  Disable Network Diagnostics:  false
  Log Level:                    Normal
  Management State:             Managed
  Observed Config:              <nil>
  Operator Log Level:           Normal
  Service Network:
    172.30.0.0/16
  Unsupported Config Overrides:  <nil>
  Use Multi Network Policy:      false
Status:
  Conditions:
    Last Transition Time:  2022-03-22T23:49:15Z
    Status:                False
    Type:                  ManagementStateDegraded
    Last Transition Time:  2022-03-23T00:12:27Z
    Status:                False
    Type:                  Degraded
    Last Transition Time:  2022-03-22T23:49:15Z
    Status:                True
    Type:                  Upgradeable
    Last Transition Time:  2022-03-23T00:12:23Z
    Status:                False
    Type:                  Progressing
    Last Transition Time:  2022-03-22T23:52:37Z
    Status:                True
    Type:                  Available
  Ready Replicas:          0
  Version:                 4.11.0-0.ci.test-2022-03-22-230532-ci-op-4ldft5b1-latest
Events:                    <none>

```

**Comment by cybertron** [comment]
It looks like there is an ongoing issue with baremetal test infra being investigated, so agreed that it's unrelated to your changes.

**Review by andreaskaris — APPROVED** [review]
/LGTM

**Pull request merged**
