### PR TITLE
USHIFT-1246: Add Robot Framework execution to e2e tests

### PR DESCRIPTION
**Pull request by pacevedom**

### CODE REVIEW

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-e2e

**Comment by pacevedom** [comment]
Rehearsal failed and junit can be checked for failures. Even if it didnt pass this proves the RF tests are executing. Might be a flake after greenboot tests.

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-e2e

**Comment by dhellmann** [comment]
> Rehearsal failed and junit can be checked for failures. Even if it didnt pass this proves the RF tests are executing. Might be a flake after greenboot tests.

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/39727/rehearse-39727-pull-ci-openshift-microshift-main-microshift-e2e/1661685609179123712/artifacts/microshift-e2e/openshift-microshift-e2e-microshift-tests-aws/artifacts/log.html seems to indicate that it's unable to collect the kubeconfig file for the IP of the microshift host. The cat command fails.

**Pull request merged**
