### PR TITLE
WIP DPTP-1996 Change release jobs to use the second aws profile

### PR DESCRIPTION
**Pull request by droslean**
Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

### CODE REVIEW

**Comment by petr-muller** [comment]
/hold

We'll defintely not switch all jobs at once right from the start. Let's soak this on a job or two for a week or so before we switch all jobs.

**Comment by droslean** [comment]
/hold

Wait for https://github.com/openshift/release/pull/17201

**Pull request closed without merging**
