### PR TITLE
OCPBUGS-23957: add local-gateway periodics back to 4.14+

### PR DESCRIPTION
**Pull request by jluhrsen**
these were perma-failing a long time back and have now been repaired. add them back.

### CODE REVIEW

**Comment by jluhrsen** [comment]
originally, they were removed with [this PR](https://github.com/openshift/release/pull/48688)

**Comment by jluhrsen** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-ovn-dualstack-local-gateway

**Comment by jluhrsen** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-ovn-dualstack-local-gateway

**Comment by jluhrsen** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-ovn-dualstack-local-gateway

**Comment by jluhrsen** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ipi-ovn-dualstack-local-gateway

**Comment by jluhrsen** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-dualstack-local-gateway

**Comment by jluhrsen** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-ovn-dualstack-local-gateway

**Comment by jluhrsen** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-ovn-dualstack-local-gateway

**Comment by jluhrsen** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-ovn-dualstack-local-gateway

**Comment by kyrtapz** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-dualstack-local-gateway
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ipi-ovn-dualstack-local-gateway

**Review by vrutkovs — APPROVED** [review]
/approve
/lgtm

**Pull request closed without merging**
