### PR TITLE
OCPQE-19096: Increase test run frequencies for component readiness

### PR DESCRIPTION
**Pull request by liangxia**
There are many profiles add/remove/update/merge since we initialized this topic, the changed list here is a little different than the one we have in ticket [OCPQE-19096](https://issues.redhat.com//browse/OCPQE-19096)

### CODE REVIEW

**Comment by jianlinliu** [comment]
LGTM. cc @yunjiang29 to review.

**Comment by jhou1** [comment]
Can we increase to daily to accumulate results faster? A few things to keep in mind
- Quota failure: work with TRT to see if we could increase
- Job failures: use component readiness module to replace the daily CI troubelshooting.

**Comment by liangxia** [comment]
Rebase and resolve conflicts.

**Pull request merged**
