### PR TITLE
Update target ocp version

### PR DESCRIPTION
**Pull request by josephca**
Update target ocp version to 4.13

### CODE REVIEW

**Review by rnapoles-rh — APPROVED** [review]
/lgtm

**Comment by rnapoles-rh** [comment]
@jmguzik can you please review / approve?

**Comment by josephca** [comment]
/pj-rehearse pull-ci-janus-idp-showcase-e2e-main-v4.13-showcase-e2e-test

**Comment by josephca** [comment]
/pj-rehearse pull-ci-janus-idp-showcase-e2e-main-v4.13-showcase-e2e-test

**Pull request merged**
