### PR TITLE
Add Tempo AWS STS job

### PR DESCRIPTION
**Pull request by IshwarKanse**

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-ocp4.16-amd64-tempo-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-ocp4.16-amd64-tempo-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-ocp4.16-amd64-tempo-e2e-tests

**Review by frzifus — APPROVED** [review]

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-ocp4.16-amd64-tempo-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-ocp4.16-amd64-tempo-e2e-tests

**Comment by IshwarKanse** [comment]
The monolithic single tenant test case fails due to bug https://issues.redhat.com/browse/TRACING-4474 which is pending fix.

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-ocp4.16-amd64-tempo-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-ocp4.16-amd64-tempo-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-ocp4.16-amd64-tempo-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-ocp4.16-amd64-tempo-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-ocp4.16-amd64-tempo-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-ocp4.16-amd64-tempo-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-ocp4.16-amd64-tempo-e2e-tests

**Comment by IshwarKanse** [comment]
https://issues.redhat.com/browse/TRACING-4474

**Review by vprashar2929 — APPROVED** [review]
/lgtm

**Pull request merged**
