### PR TITLE
Remove dsp ci jobs and configs.

### PR DESCRIPTION
**Pull request by HumairAK**
No longer needed as data-science-pipelines-operator ci/jobs are sufficient for testing dsp component.

### CODE REVIEW

**Comment by HumairAK** [comment]
@harshad16 / @DharmitD

**Review by gmfrasca — COMMENTED** [review]
/lgtm

**Review by harshad16 — APPROVED** [review]
/lgtm

:+1:

**Review by DharmitD — APPROVED** [review]
/Approve

**Pull request merged**
