### PR TITLE
Wait for NodeState

### PR DESCRIPTION
**Pull request by MaysaMacedo**

### CODE REVIEW

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-release-4.16-e2e-openstack-nfv
/hold

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-release-4.16-e2e-openstack-nfv

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-release-4.16-e2e-openstack-nfv

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-release-4.16-e2e-openstack-nfv

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-release-4.16-e2e-openstack-nfv

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-release-4.16-e2e-openstack-nfv

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-release-4.16-e2e-openstack-nfv

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-release-4.16-e2e-openstack-nfv

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-release-4.16-e2e-openstack-nfv

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-release-4.16-e2e-openstack-nfv

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-release-4.16-e2e-openstack-nfv

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-release-4.16-e2e-openstack-nfv

**Comment by MaysaMacedo** [comment]
/pj-rehearse pull-ci-openshift-sriov-network-operator-release-4.16-e2e-openstack-nfv

**Comment by stephenfin** [comment]
@MaysaMacedo Is this still needed? fwiw, I've no context here so I don't know if this is a WIP patch or, if not, what it's supposed to do :confused:

**Comment by MaysaMacedo** [comment]
@stephenfin this is a nice to have, but not a requirement.
So, I'm closing as it requires some additional work with the images used in the job.

**Pull request closed without merging**
