### PR TITLE
kata-containers: Bump next to 4.15

### PR DESCRIPTION
**Pull request by ldoktor**
move "next" testing to 4.15.

I tested this manually first and it doesn't seem to resolve any SKIPPED tests so keeping everything as is for now.

### CODE REVIEW

**Review by cpmeadors — APPROVED** [review]

**Comment by ldoktor** [comment]
Well, for some reason it doesn't want to re-test. Anyway I added the extension of the wait for mcp finish to https://github.com/kata-containers/kata-containers/pull/9229 it should be safer then as it looks like it's progressing just not as fast as 4.13...

**Comment by ldoktor** [comment]
No changes, just rebased (changes happened on the kata-containers repo)

**Comment by ldoktor** [comment]
replaced by https://github.com/openshift/release/pull/50530

**Pull request closed without merging**
