### PR TITLE
Add GeoBK to ci-admin group

### PR DESCRIPTION
**Pull request by GeoBK**

### CODE REVIEW

**Comment by GeoBK** [comment]
cc @stevekuznetsov  @hongkailiu

**Review by alvaroaleman — COMMENTED** [review]
/hold
Why is this needed?

**Comment by GeoBK** [comment]
> /hold
> Why is this needed?

I currently don't have permissions to trigger jobs, this would allow me to do that

**Comment by alvaroaleman** [comment]
You can achieve that by just adding yourself here: https://github.com/openshift/release/blob/b2770007d21ea33f7ac1ea2ad780904e127448b9/core-services/prow/02_config/_config.yaml#L346

After that, you can use the rerun button on the Deck UI.

**Review by stevekuznetsov — APPROVED** [review]

**Pull request merged**
