### PR TITLE
NO-ISSUE: Add presubmit e2e test with OCP 4.15 test for assisted-service

### PR DESCRIPTION
**Pull request by danmanor**
Add `e2e presubmit` test with `OCP 4.15` test for `assisted-service`

### CODE REVIEW

**Review by gamli75 — APPROVED** [review]

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted-4-15

**Review by adriengentil — APPROVED** [review]

**Review by filanov — APPROVED** [review]

**Pull request merged**
