### PR TITLE
vSphere: move all devqe jobs to new build cluster

### PR DESCRIPTION
**Pull request by jcpowermac**

### CODE REVIEW

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-vsphere-ipi-disconnected-f14

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-vsphere-ipi-disconnected-f14

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-vsphere-ipi-disconnected-f14

**Comment by jcpowermac** [comment]
/hold
network config issues

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-vsphere-ipi-disconnected-f14

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-vsphere-ipi-proxy-tp-f28 periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-vsphere-ipi-disconnected-f14 periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-vsphere-ipi-remote-worker-f14

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-vsphere-ipi-proxy-fips-f14

**Comment by WenXinWei** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-vsphere-ipi-proxy-fips-f14

**Comment by jianlinliu** [comment]
cc @liangxia to review

**Pull request merged**
