### PR TITLE
MSI: cluster-fix destroy command

### PR DESCRIPTION
**Pull request by rnetser**

### CODE REVIEW

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-multi-cluster-smoke-v4.13-multicluster-aws-4.13-nightly-hypershift-4.13-candidate-smoke

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Comment by rnetser** [comment]
/pj-rehearse ci/rehearse/CSPI-QE/MSI/cluster-install-uninstall/multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-multi-cluster-smoke-v4.13-multicluster-aws-4-13-nightly-hypershift-4-13-candidate-smoke

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-multi-cluster-smoke-v4.13-multicluster-aws-4-13-nightly-hypershift-4-13-candidate-smoke

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Comment by rnetser** [comment]
/pj-rehearse pull-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-aws-4-13-ci-4-14-nightly

**Review by omrirh — APPROVED** [review]

**Pull request merged**
