### PR TITLE
ci-operator/step-registry/ipi/conf/aws/proxy: Use public IP for SSH

### PR DESCRIPTION
**Pull request by wking**
[Avoid][1]:

```
ssh: connect to host 10.0.1.169 port 22: Connection timed out
```

and similar when we try to SSH in from outside the VPN.

[1]: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.6-e2e-aws-proxy/1308112334144671744/artifacts/e2e-aws-proxy/gather-proxy/container-logs/test.log

### CODE REVIEW

**Comment by wking** [comment]
/hold

for rehearsals

**Comment by ewolinetz** [comment]
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/12110/rehearse-12110-pull-ci-openshift-installer-master-e2e-aws-proxy/1308174430869917696/artifacts/e2e-aws-proxy/gather-proxy/squid.service :tada:

**Pull request merged**
