### PR TITLE
OCPQE-18528: automate OCP-68544 OCP-68545 and OCP-68546

### PR DESCRIPTION
**Pull request by jinyunma**
1. Remove step `ipi-conf-azure-vmgenv1` which hardcodes instance type and region, and could not be reused
2. Change install workflow `cucushift-installer-rehearse-azure-ipi-vmgenv1` to `cucushift-installer-rehearse-azure-ipi-generation`, and set instance type and region on job config level, update related job on 4.11+ accordingly.
3.  Add new job `azure-ipi-vmgenv2` in verification-test on 4.14+
4.  Add post-check `cucushift-installer-check-azure-vm-generation` to automate OCP-68544 OCP-68545 and OCP-68546

### CODE REVIEW

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-ipi-vmgenv2-f14

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-ipi-vmgenv2-f14

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-azure-ipi-vmgenv1-f28 periodic-ci-openshift-openshift-tests-private-release-4.15-multi-nightly-azure-ipi-usertags-sa-encryption-arm-f28

**Comment by jinyunma** [comment]
periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-azure-ipi-vmgenv1-f28: [job link](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/47093/rehearse-47093-periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-azure-ipi-vmgenv1-f28/1739865116955906048), [post-check](https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/47093/rehearse-47093-periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-azure-ipi-vmgenv1-f28/1739865116955906048/artifacts/azure-ipi-vmgenv1-f28/cucushift-installer-check-azure-vm-generation/build-log.txt)
periodic-ci-openshift-openshift-tests-private-release-4.15-multi-nightly-azure-ipi-usertags-sa-encryption-arm-f28: [job link](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/47093/rehearse-47093-periodic-ci-openshift-openshift-tests-private-release-4.15-multi-nightly-azure-ipi-usertags-sa-encryption-arm-f28/1739865117031403520), [post-check](https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/47093/rehearse-47093-periodic-ci-openshift-openshift-tests-private-release-4.15-multi-nightly-azure-ipi-usertags-sa-encryption-arm-f28/1739865117031403520/artifacts/azure-ipi-usertags-sa-encryption-arm-f28/cucushift-installer-check-azure-vm-generation/build-log.txt)
periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-ipi-vmgenv2-f14: [job link](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/47093/rehearse-47093-periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-ipi-vmgenv2-f14/1739843910823317504), [post-check](https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/47093/rehearse-47093-periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-ipi-vmgenv2-f14/1739843910823317504/artifacts/azure-ipi-vmgenv2-f14/cucushift-installer-check-azure-vm-generation/build-log.txt)

cc @gpei @yunjiang29 @MayXuQQ @jianlinliu to review

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-multi-nightly-azure-ipi-usertags-sa-encryption-arm-f28

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-multi-nightly-azure-ipi-usertags-sa-encryption-arm-f28

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.11-amd64-nightly-azure-ipi-vmgenv1-f28

**Comment by jianlinliu** [comment]
cc @liangxia to review.

**Pull request merged**
