### PR TITLE
stackrox: bump release branches to 4.12

### PR DESCRIPTION
**Pull request by gavin-stackrox**
This will add 4.8 (oldest) and 4.12 (newest) openshift-4 QA e2e tests to all operational branches. I've also added some optional presubmit jobs to the branches to make branch PRs testable.

/cc @msugakov @tommartensen 
/hold

### CODE REVIEW

**Comment by gavin-stackrox** [comment]
/cc @robbycochran 
Due to these running as merge jobs under OSCI, we won't know if they work until after this config change merges and new changes are pushed to the release branches.

**Comment by gavin-stackrox** [comment]
I'm going to update this to create some optional presubmit jobs for the branches. This will make it possible to verify changes using release branch PRs. And I expect the bump to 4.12 may require corresponding repo changes.

**Comment by gavin-stackrox** [comment]
/pj-rehearse stackrox/stackrox/release-3.72/lopenshift-newest-qa-e2e-tests

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-release-3.72-openshift-newest-qa-e2e-tests

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-release-3.73-openshift-newest-qa-e2e-tests pull-ci-stackrox-stackrox-release-3.74-openshift-newest-qa-e2e-tests

**Comment by tommartensen** [comment]
> Due to these running as merge jobs under OSCI, we won't know if they work until after this config change merges and new changes are pushed to the release branches.

@gavin-stackrox 
Can we hold off the changes to (at least) 3.74 branch? As you said, we won't know if these new jobs work until we push again. We have a stable RC at the moment and see changing the CI before the release as a risk to successful, on time release.

**Comment by msugakov** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-release-3.74-openshift-newest-qa-e2e-tests

**Comment by mtodor** [comment]
> > Due to these running as merge jobs under OSCI, we won't know if they work until after this config change merges and new changes are pushed to the release branches.

> @gavin-stackrox
Can we hold off the changes to (at least) 3.74 branch? As you said, we won't know if these new jobs work until we push again. We have a stable RC at the moment and see changing the CI before the release as a risk to successful, on time release.

I agree with Tom regarding `3.74`. The release is already in its final stage, and having a new RC will push the planned release date.

**Comment by gavin-stackrox** [comment]
Closing in favor of #36274 and #36275

**Pull request closed without merging**
