### PR TITLE
add aws-outpost profile support

### PR DESCRIPTION
**Pull request by AsherShoshan**

### CODE REVIEW

**Comment by yigald18** [comment]
@yunjiang29 please take a look and merge

**Comment by yunjiang29** [comment]
@AsherShoshan you also need to add a new lease resource [1] to your profile. 

You can refer to the example [2] that I provided in QA doc and slack message.
`core-services/prow/02_config/_boskos.yaml` can be generated by running `python generate-boskos.py` automatically.

[1] https://docs.ci.openshift.org/docs/how-tos/adding-a-cluster-profile/#adding-new-leases
[2] https://github.com/openshift/release/pull/21873

**Comment by AsherShoshan** [comment]
> 

There is no such files in current repository.

**Comment by AsherShoshan** [comment]
@yunjiang29 :

**Comment by yunjiang29** [comment]
https://github.com/openshift/release/blob/master/core-services/prow/02_config/generate-boskos.py
https://github.com/openshift/release/blob/master/core-services/prow/02_config/_boskos.yaml

**Pull request closed without merging**
