### PR TITLE
Use image mirror with multi-arch support

### PR DESCRIPTION
**Pull request by r4f4**
After https://github.com/openshift/origin/pull/24887 we are seeing image
pull errors in CI for ppc64le and s390x. So for now we've created our
own multi-arch mirror.

Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>

### CODE REVIEW

**Comment by r4f4** [comment]
The "managed cluster ..." test will be fixed by https://github.com/openshift/release/pull/14394

**Comment by petr-muller** [comment]
/approve

Providing the label necessary for merge, but someone who can interpret the chnages in tests lists should provide `/lgtm`

**Comment by r4f4** [comment]
We added one more image to our multi-arch repo, so I'll do another review round of the excluded tests before this is merged.

**Comment by r4f4** [comment]
List reviewed, it's good to go now.

**Comment by r4f4** [comment]
I added a few more false-positive test failures (DNS failures and connection timeouts).

**Comment by jaypoulz** [comment]
/lgtm

I think it's worth checking this in before the holidays since this will increase our coverage, test pass rates, and most importantly, gather us the kind of quality data we need to make decisions when we come back from shutdown.

**Pull request merged**
