### PR TITLE
add e2e-operator to service-ca-operator jobs

### PR DESCRIPTION
**Pull request by mrogers950**
@openshift/sig-auth

### CODE REVIEW

**Comment by mrogers950** [comment]
@stevekuznetsov what's wrong with the ci/rehearse/openshift/service-ca-operator/master/e2e-aws test here? Our e2e on service-ca-operator master runs fine standalone.

**Comment by petr-muller** [comment]
> what's wrong with the ci/rehearse/openshift/service-ca-operator/master/e2e-aws test here? Our e2e on service-ca-operator master runs fine standalone.

@mrogers950 Looks like the `e2e-aws` rehearsal is stale here - recently we made rehearsals smarter so it currently recognizes your changes only affect the `e2e-aws-operator` job so retests only rerun that one. Rehearsals are not blocking so you can ignore it, Tide will merge the job once the review labels are set.

**Comment by mrogers950** [comment]
@smarterclayton or @deads2k PTAL for an /approve

**Comment by mrogers950** [comment]
@smarterclayton or @deads2k PTAL for an /approve

**Comment by deads2k** [comment]
looks plausible to me

/approve

**Pull request merged**
