### PR TITLE
add ALC to the OPP suite

### PR DESCRIPTION
**Pull request by vboulos**
This PR adds the Application Life Cycle tests to the OPP tests suite.
ALC runs after GRC

### CODE REVIEW

**Comment by vboulos** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.12-interop-openshift-plus-interop-aws

**Comment by vboulos** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.12-interop-openshift-plus-interop-aws

**Comment by vboulos** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.12-interop-openshift-plus-interop-aws

**Comment by vboulos** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.12-interop-openshift-plus-interop-aws

**Review by gparvin — APPROVED** [review]

**Pull request merged**
