### PR TITLE
dotnet zstream expansion to ocp 4.17

### PR DESCRIPTION
**Pull request by smpsgill**

### CODE REVIEW

**Comment by Simranpal** [comment]
/pj-rehearse pull-ci-sclorg-ansible-tests-master-dotnet-ocp4.17-lp-interop-images periodic-ci-sclorg-ansible-tests-master-dotnet-ocp4.17-lp-interop-dotnet-interop-ibmcloud

**Review by dfrazzette — APPROVED** [review]

**Pull request merged**
