### PR TITLE
MGMT-18688: Implement a more dynamic capabilities for testing assisted installed OCP cluster

### PR DESCRIPTION
**Pull request by danmanor**
Implement a more dynamic capabilities for testing assisted installed OCP cluster:

- `TEST_TYPE` - `suite`, `list` or `none`
- `TEST_LIST` - list of tests. applicable if  `TEST_TYPE : list`
- `TEST_SUITE` - The test suite to run. applicable if  `TEST_TYPE : suite`
- `TEST_PROVIDER` - the tests provider. applicable if  `TEST_TYPE : suite`
- `TEST_SKIPS` - tests to skip.

### CODE REVIEW

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted pull-ci-openshift-assisted-test-infra-master-e2e-nutanix-assisted

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted pull-ci-openshift-assisted-test-infra-master-e2e-nutanix-assisted

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-vsphere-assisted

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted

**Comment by danmanor** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted

**Comment by adriengentil** [comment]
/close
replaced by https://github.com/openshift/release/pull/56392

**Pull request closed without merging**
