### PR TITLE
monitoring-operator: rename upgrade job to be platformless, use Loki workflow

### PR DESCRIPTION
**Pull request by vrutkovs**
Run AWS upgrade tests using multistep, persistent metrics and store container logs using Loki.

/cc @lilic @s-urbaniak

### CODE REVIEW

**Comment by vrutkovs** [comment]
4.4 flaking

/retest

**Comment by lilic** [comment]
/lgtm

/hold

@s-urbaniak up to you.

**Comment by s-urbaniak** [comment]
as discussed between @lilic @vrutkovs and me OOB: this is good to merge for 4.4, 4.5. Let's wait until code freeze for 4.6 is done and enable it for 4.7 :+1:

**Pull request merged**
