### PR TITLE
OCPQE-13499  [Upgrade Issue] Prow CI 4.12-amd64-nightly-4.12-upgrade-from-stable-4.5-azure-ipi failed

### PR DESCRIPTION
**Pull request by MayXuQQ**
[OCPQE-13499](https://issues.redhat.com//browse/OCPQE-13499) [azure] Prow CI 4.12-amd64-nightly-4.12-upgrade-from-stable-4.5-azure-ipi failed

### CODE REVIEW

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-4.12-upgrade-from-stable-4.5-azure-ipi-p1-f30

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-4.12-upgrade-from-stable-4.5-azure-ipi-p1-f30

**Comment by jianlinliu** [comment]
I suggest to directly update the job's env to set `LOKI_ENABLED`to `false` in https://github.com/openshift/release/blob/master/ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.5.yaml#L74, https://github.com/openshift/release/blob/master/ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.3.yaml#L76 also need the setting.

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-4.12-upgrade-from-stable-4.5-azure-ipi-p1-f30

/pj-rehearse refresh

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-4.12-upgrade-from-stable-4.3-azure-ipi-p1-f30

**Comment by jianlinliu** [comment]
cc @liangxia and @shellyyang1989 to review this PR. For old versions (<=4.5) of IPI install, need to disable LOKI install (which is called in ipi-install chain), or else, bootstrap would fail, because of it called some unsupported api.

**Comment by shellyyang1989** [comment]
> cc @liangxia and @shellyyang1989 to review this PR. For old versions (<=4.5) of IPI install, need to disable LOKI install (which is called in ipi-install chain), or else, bootstrap would fail, because it references some unsupported k8s resources.

Thanks! So except for azure, do other platforms have the issue? If true, I'll create follow-up PRs to fix them.

**Comment by jianlinliu** [comment]
> Thanks! So except for azure, do other platforms have the issue? If true, I'll create follow-up PRs to fix them.

Yeah, only related with OCP version, not about platforms. We can see all the dev's upgrade jobs are setting `LOKI_USE_SERVICEMONITOR` (`LOKI_ENABLED` is a bit more aggressive) in ci-operator/config/openshift/release/openshift-release-master__ci-4.6-upgrade-from-stable-4.5.yaml.

Last time, I did not notice the other old versions of upgrade job, @MayXuQQ do you mind to update all `*upgrade*-4.{2,3,4,5}*` together in this PR?

**Comment by MayXuQQ** [comment]
> > Thanks! So except for azure, do other platforms have the issue? If true, I'll create follow-up PRs to fix them.
> 
> Yeah, only related with OCP version, not about platforms. We can see all the dev's upgrade jobs are setting `LOKI_USE_SERVICEMONITOR` (`LOKI_ENABLED` is a bit more aggressive) in ci-operator/config/openshift/release/openshift-release-master__ci-4.6-upgrade-from-stable-4.5.yaml.
> 
> Last time, I did not notice the other old versions of upgrade job, @MayXuQQ do you mind to update all `*upgrade*-4.{2,3,4,5}*` together in this PR?

$grep LOKI_ENABLED *4.12-upgrade-from*.yaml
openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.3.yaml:      LOKI_ENABLED: "false"
openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.5.yaml:      LOKI_ENABLED: "false"
others have not

**Comment by jianlinliu** [comment]
> others have not use LOKI_ENABLED

Can you help update others together.

**Pull request merged**
