### PR TITLE
[openshift-cnv/cnv-ci] Add promotions for 4.14, 4.15 and master

### PR DESCRIPTION
**Pull request by orenc1**

### CODE REVIEW

**Comment by tiraboschi** [comment]
OK,
/lgtm

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-cnv-cnv-ci-release-4.15-e2e-deploy /pj-rehearse pull-ci-openshift-cnv-cnv-ci-release-4.15-e2e-upgrade

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-cnv-cnv-ci-release-4.15-e2e-deploy pull-ci-openshift-cnv-cnv-ci-release-4.15-e2e-upgrade

**Pull request merged**
