### PR TITLE
rename openshift logging config files and fix jira project name in firewatch config

### PR DESCRIPTION
**Pull request by shakyav**

### CODE REVIEW

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-logging-interop-ocp-ci-main-openshift-logging-ocp4.15-lp-rosa-hypershift-openshift-logging-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-logging-interop-ocp-ci-main-openshift-logging-ocp4.14-lp-rosa-hypershift-cluster-logging-operator-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-logging-interop-ocp-ci-main-openshift-logging-ocp4.14-lp-rosa-hypershift-cluster-logging-operator-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-logging-interop-ocp-ci-main-openshift-logging-ocp4.14-lp-rosa-hypershift-cluster-logging-operator-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-logging-interop-ocp-ci-main-openshift-logging-ocp4.15-lp-rosa-hypershift-openshift-logging-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-logging-interop-ocp-ci-main-openshift-logging-ocp4.14-lp-rosa-hypershift-cluster-logging-operator-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-logging-interop-ocp-ci-main-openshift-logging-ocp4.15-lp-rosa-hypershift-openshift-logging-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-logging-interop-ocp-ci-main-openshift-logging-ocp4.15-lp-rosa-hypershift-openshift-logging-rosa-hypershift

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-openshift-logging-interop-ocp-ci-main-openshift-logging-ocp4.14-lp-rosa-hypershift-cluster-logging-operator-rosa-hypershift

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
