### PR TITLE
Remove 4.10 AWS SNO jobs

### PR DESCRIPTION
**Pull request by yunjiang29**
Based on https://bugzilla.redhat.com/show_bug.cgi?id=2042826#c17, remove 4.10 SNO jobs.

AWS SNO is officially supported starting from 4.13 https://issues.redhat.com/browse/OCPSTRAT-483

### CODE REVIEW

**Comment by gpei** [comment]
based on https://bugzilla.redhat.com/show_bug.cgi?id=2042826#c17 
/lgtm

**Comment by yunjiang29** [comment]
@liangxia PTAL

**Comment by yunjiang29** [comment]
cc @lihongan

**Comment by lihongan** [comment]
It looks good. Thank you, Yunfei.

**Pull request merged**
