### PR TITLE
Onboard Distributing Tracing operator (Tempo and Open-telemetry) on ROSA Classic

### PR DESCRIPTION
**Pull request by Sau1506mya**
Link to JIRA: [[LPTOCPCI-1363](https://issues.redhat.com/browse/LPTOCPCI-1363)]

### CODE REVIEW

**Comment by IshwarKanse** [comment]
@Sau1506mya We will need to make some small changes once RHOSDT 3.2 is released and these PRs are merged for Tempo and OTEL https://github.com/openshift/release/pull/52193 https://github.com/openshift/release/pull/52263

**Comment by Sau1506mya** [comment]
> @Sau1506mya We will need to make some small changes once RHOSDT 3.2 is released and these PRs are merged for Tempo and OTEL #52193 #52263

Okay @IshwarKanse , then we will run the rehearsal jobs

**Comment by Sau1506mya** [comment]
/pj-rehearse pull-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.14-lp-rosa-classic-images pull-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.15-lp-rosa-classic-images pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.14-lp-rosa-classic-images pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.15-lp-rosa-classic-images periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.14-lp-rosa-classic-opentelemetry-rosa-aws

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.15-lp-rosa-classic-tempo-rosa-aws periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.14-lp-rosa-classic-tempo-rosa-aws periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.15-lp-rosa-classic-opentelemetry-rosa-aws periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.14-lp-rosa-classic-opentelemetry-rosa-aws

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.14-lp-rosa-classic-opentelemetry-rosa-aws periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.15-lp-rosa-classic-opentelemetry-rosa-aws periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.14-lp-rosa-classic-tempo-rosa-aws periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.15-lp-rosa-classic-tempo-rosa-aws

**Comment by IshwarKanse** [comment]
Cluster deployment failed, re-triggering failing jobs.

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.14-lp-rosa-classic-opentelemetry-rosa-aws periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.15-lp-rosa-classic-opentelemetry-rosa-aws

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.14-lp-rosa-classic-opentelemetry-rosa-aws periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.15-lp-rosa-classic-opentelemetry-rosa-aws

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.15-lp-rosa-classic-opentelemetry-rosa-aws

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.15-lp-rosa-classic-opentelemetry-rosa-aws

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.14-lp-rosa-classic-opentelemetry-rosa-aws

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.15-lp-rosa-classic-opentelemetry-rosa-aws

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-product-ocp-4.14-lp-rosa-classic-opentelemetry-rosa-aws

**Review by IshwarKanse — APPROVED** [review]
/lgtm

**Pull request merged**
