### PR TITLE
Remove prefixes

### PR DESCRIPTION
**Pull request by rsevilla87**
As discussed on our last meeting, let's remove the prefixes we added to the UUIDs

### CODE REVIEW

**Comment by rsevilla87** [comment]
cc: @jtaleric

**Comment by vishnuchalla** [comment]
Related JIRA: https://issues.redhat.com/browse/PERFSCALE-2442. Reassigned it to Raul.

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-gcp-4.13-nightly-x86-perfscale-gcp-router-perf-5nodes-periodic

**Review by krishvoor — APPROVED** [review]
/lgtm

**Comment by vishnuchalla** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-gcp-4.12-nightly-x86-perfscale-control-plane-5nodes-periodic

**Pull request merged**
