### PR TITLE
add a step to pin release images for sno clusters before upgrades

### PR DESCRIPTION
**Pull request by shellymiron**
same as the previous job, but for sno cluster
ref PR: https://github.com/openshift/release/pull/52159

### CODE REVIEW

**Comment by shellymiron** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-4.16-upgrade-from-stable-4.16-aws-ipi-disc-priv-sno-tp-pin-mco-f60

**Comment by sergiordlr** [comment]
It is trying to pin the images in both pools worker and master. That's why the step is failing

Add this to the configuration so that we only pin the images in the master pool:
  `MCO_CONF_DAY2_PINTARGETRELEASE_MCPS: master`

**Comment by shellymiron** [comment]
reopening with a new PR

**Pull request closed without merging**
