### PR TITLE
increase resources request on e2e-aws template jobs

### PR DESCRIPTION
**Pull request by droslean**
/cc @stevekuznetsov @bbguimaraes @petr-muller @hongkailiu

### CODE REVIEW

**Comment by petr-muller** [comment]
/shrug
I'm missing information about why this is needed.

**Comment by droslean** [comment]
we created new alerts for these jobs, but it seems that a large amount of the jobs are using more resources than requested. Therefore, the most of the alerts are fake. In order to clean this up and get real alerts, we (me and @stevekuznetsov ) decide to increase those values.  However, the new values has to be debatable.. 
In my point of view, the new values are now enough (maybe we need little bit more, but we need to track the new alerts for that.)

**Comment by droslean** [comment]
lets hold this for now.

/hold

**Comment by stevekuznetsov** [comment]
What are the actual usage values today?

**Comment by stevekuznetsov** [comment]
Let's choose the value that is as small as possible to not trigger the 150% alert.

**Comment by droslean** [comment]
I think those values should be enough.  Maybe a little bit more, but I would like to merge this first and start monitoring the situation again, I will definitely have better picture.

**Pull request closed without merging**
