### PR TITLE
Move gcp clusters to us-east4-b.

### PR DESCRIPTION
**Pull request by dgoodwin**
Several days of capacity issues in us-east1-c, we need to get things
rolling again. I randomly chose us-east4-b.

We were in the midst of chasing a 4.11 regression on gcp, when gcp itself started failing to give us the vms we are requesting. This has been on-going for about two days now.

Need some help from DPTP/DPP, is this change correct and safe and do we have quota there?

### CODE REVIEW

**Comment by dgoodwin** [comment]
/hold

I think I've got the wrong place, it's us-cental1-c we're hitting problems in.

**Comment by dgoodwin** [comment]
us-central1-c is not mentioned anywhere in the release repo.... is this an installer default?

**Comment by wking** [comment]
The installer is looking at the target region and picking a few zones within it.  If you want to steer it in a particular direction, [set `zones`][1].  Doesn't look like we do that for installer-provided GCP today:

```console
$ git grep zones | grep gcp
...nothing relevant to installer-provisioned workflows...
```

but [this][2] is the installer-provisioned AWS step dancing through pre-installer zone selection.

[1]: https://github.com/openshift/installer/blob/8e61df170058df20819c25880ded2d655763a703/docs/user/gcp/customization.md#machine-pools
[2]: https://github.com/openshift/release/blob/09ee5099db6f54c6a180dc7abd754c4464342e1a/ci-operator/step-registry/ipi/conf/aws/ipi-conf-aws-commands.sh#L44-L86

**Pull request closed without merging**
