### PR TITLE
[knative-eventing] HEAD: For now we have just 4.11

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

For head/release-next, we will just have 4.11, for now ..

### CODE REVIEW

**Comment by pierDipi** [comment]
Can we update the reconciler instead of doing manual changes and go back at manual changes for everything?

**Comment by matzew** [comment]
>  Can we update the reconciler instead of doing manual changes and go back at manual changes for everything?

Ok, I can do that later - not now. sorry

**Comment by matzew** [comment]
/close
for now, I close

**Pull request closed without merging**
