### PR TITLE
openshift/cluster-openshift-apiserver-operator: Setup image mirroring

### PR DESCRIPTION
**Pull request by tnozicka**
/cc @deads2k

### CODE REVIEW

**Comment by tnozicka** [comment]
/assign @bbguimaraes @stevekuznetsov 
for approval

**Comment by smarterclayton** [comment]
There's a script that generates this and it's done by hand today.

**Comment by deads2k** [comment]
> There's a script that generates this and it's done by hand today.

@smarterclayton we've got 3 more after this one.  Can we get a pointer to the script?

**Comment by tnozicka** [comment]
@smarterclayton I followed https://docs.google.com/document/d/1rxBKXqNZoingm_wHAyA_Awj6bkHMv-2FkQRIWMWHmY8/edit
and run `make image-mirror-files`

**Comment by smarterclayton** [comment]
I corrected the doc, it was not intended that people submitted this file.

**Pull request closed without merging**
