### PR TITLE
HCO: Move all main branch's AWS lanes to CNV account

### PR DESCRIPTION
**Pull request by nunnatsa**
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

### CODE REVIEW

**Comment by nunnatsa** [comment]
/hold

Seems that some configurstions are still missing.

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-index-aws

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-index-aws

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-index-aws

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-index-sno-aws

**Comment by nunnatsa** [comment]
/pj-rehearse pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-prev-index-sno-aws

**Review by orenc1 — APPROVED** [review]
:tada: nice!
/approve

**Pull request merged**
