### PR TITLE
openshift-loki: Use loki v2.9.8 in operator branches

### PR DESCRIPTION
**Pull request by periklis**
Refs: [LOG-5504](https://issues.redhat.com//browse/LOG-5504)

/cc @xperimental @JoaoBraveCoding

### CODE REVIEW

**Comment by periklis** [comment]
/pj-rehearse pull-ci-openshift-loki-main-ci-index-loki-operator-bundle

**Comment by periklis** [comment]
/pj-rehearse pull-ci-openshift-loki-release-5.9-ci-index-loki-operator-bundle

**Comment by periklis** [comment]
/pj-rehearse pull-ci-openshift-loki-release-5.8-ci-index-loki-operator-bundle

**Comment by periklis** [comment]
/pj-rehearse pull-ci-openshift-loki-release-5.7-ci-index-loki-operator-bundle

**Comment by periklis** [comment]
/pj-rehearse pull-ci-openshift-loki-release-5.6-ci-index-loki-operator-bundle

**Review by JoaoBraveCoding — APPROVED** [review]
/lgtm

**Pull request merged**
