### PR TITLE
hypershift: avoid image builds in periodic jobs

### PR DESCRIPTION
**Pull request by sjenning**
Periodic jobs should not build new images from the source repository.  Use the images promoted into the ocp integration stream by the post-submit jobs instead.

### CODE REVIEW

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-e2e-aws-periodic

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-e2e-aws-periodic

**Comment by sjenning** [comment]
/hold
not there quite yet

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-e2e-aws-periodic

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.12-periodics-4.12-e2e-aws-periodic

**Comment by sjenning** [comment]
4.13 test failed with KAS pod restarts but this change looks good

**Comment by enxebre** [comment]
/lgtm
/hold
for you to unhold @sjenning

**Pull request merged**
