### PR TITLE
Bump/remove 4.6/4.7 openshift-ci ClusterPool jobs

### PR DESCRIPTION
**Pull request by 2uasimojo**
Since OCP 4.6 and 4.7 are
[EOL](https://access.redhat.com/support/policy/updates/openshift#dates), we should stop consuming CI resources running tests against those releases.

This commit removes knative tests against 4.6 as there exist parallel tests for later (still in-support) releases.

For jobs with no existing in-support equivalents, this commit bumps the requested release somewhat arbitrarily to 4.10, 4.11, or 4.12.

This is in preparation for decommissioning the 4.6 and 4.7 openshift-ci ClusterPools so we can use their quota for more recent releases.

### CODE REVIEW

**Review by pierDipi — COMMENTED** [review]
LGTM for Knative / serverless jobs

**Review by kovayur — APPROVED** [review]
/approve

**Comment by kovayur** [comment]
LGTM for acs-fleet-manager

**Review by NautiluX — COMMENTED** [review]
/approve

**Pull request merged**
