### PR TITLE
Add verify-commits to operator-controller and catalogd

### PR DESCRIPTION
**Pull request by dtfranz**
Adds `verify-commits` target to operator-controller and catalogd

### CODE REVIEW

**Comment by ncdc** [comment]
Waiting on https://github.com/openshift/operator-framework-operator-controller/pull/24 to merge, then we will run rehearsals

**Comment by dtfranz** [comment]
/pj-rehearse pull-ci-openshift-operator-framework-catalogd-main-verify-commits
/pj-rehearse pull-ci-openshift-operator-framework-operator-controller-main-verify-commits

**Comment by dtfranz** [comment]
/pj-rehearse pull-ci-openshift-operator-framework-catalogd-main-verify-commits

**Comment by dtfranz** [comment]
/pj-rehearse pull-ci-openshift-operator-framework-operator-controller-main-verify-commits

**Comment by ncdc** [comment]
The rehearsal is expected to fail because it's using the PULL_BASE_SHA from this repo (because the PR is here) and that commit doesn't exist in the target repo (operator-framework-catalogd). The good thing is the check is running.

**Review by ncdc — APPROVED** [review]

**Pull request merged**
