### PR TITLE
DO NOT MERGE: Temporary test to see if xml from post steps works.

### PR DESCRIPTION
**Pull request by dgoodwin**

### CODE REVIEW

**Comment by dgoodwin** [comment]
/hold

Testing a theory at this point.

**Comment by dgoodwin** [comment]
Doing this we get the junit artifact, which something else could process. (currently the job aggregator could do this) Prow however does not see and display it's contents, which limits it's usefulness a fair bit. Unsure about testgrid.

/close

**Comment by wking** [comment]
[This][1] is the Prow config that should be picking up [your `junit_e2e_20220211-9871239.xml`][2].  But Spyglass is definitely picking up the `operator conditions ...` test-cases from [gather-extra's `junit/junit_install_status.xml`][3]:

'operator conditions ...' screenshot

Perhaps the test-platform folks have a clearer idea of why this isn't working...

[1]: https://github.com/openshift/release/blob/965aa7550e2a17853870e7f80cdc6b0e454ac687/core-services/prow/02_config/_config.yaml#L73-L74
[2]: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/26183/rehearse-26183-pull-ci-openshift-cluster-logging-operator-tech-preview-e2e-operator/1492126410020491264/artifacts/e2e-operator/gather-must-gather/artifacts/
[3]: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/26183/rehearse-26183-pull-ci-openshift-cluster-logging-operator-tech-preview-e2e-operator/1492126410020491264/artifacts/e2e-operator/gather-extra/artifacts/junit/

**Comment by dgoodwin** [comment]
Now I'm curious, I'll raise in dptp slack.

**Comment by dgoodwin** [comment]
@petr-muller has pointed that the xml sample I pulled online may not be valid, it has testsuites, but no testsuite. We also are not using a junit sub-dir as the other examples do, the pattern doesn't seem to require it. I'm going to try again with better xml first.

/reopen

**Comment by petr-muller** [comment]
:popcorn:

**Comment by petr-muller** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/26183/rehearse-26183-pull-ci-openshift-machine-config-operator-release-4.9-e2e-gcp-single-node/1496459535802437632:

thisisatest

**Comment by dgoodwin** [comment]
Excellent, experiment successful.

**Pull request closed without merging**
