### PR TITLE
Interop - Onboard RHSI on ROSA classic

### PR DESCRIPTION
**Pull request by oharan2**

### CODE REVIEW

**Comment by oharan2** [comment]
/pj-rehearse pull-ci-skupperproject-skupper-openshift-smoke-test-image-main-service-interconnect-ocp4.14-lp-rosa-classic-images

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-skupperproject-skupper-openshift-smoke-test-image-main-service-interconnect-ocp4.14-lp-rosa-classic-rhsi-interop-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse pull-ci-skupperproject-skupper-openshift-smoke-test-image-main-service-interconnect-ocp4.14-lp-rosa-classic-images

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-skupperproject-skupper-openshift-smoke-test-image-main-service-interconnect-ocp4.14-lp-rosa-classic-rhsi-interop-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-skupperproject-skupper-openshift-smoke-test-image-main-service-interconnect-ocp4.14-lp-rosa-classic-rhsi-interop-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse pull-ci-skupperproject-skupper-openshift-smoke-test-image-main-service-interconnect-ocp4.14-lp-rosa-classic-images

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-skupperproject-skupper-openshift-smoke-test-image-main-service-interconnect-ocp4.14-lp-rosa-classic-rhsi-interop-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse pull-ci-skupperproject-skupper-openshift-smoke-test-image-main-service-interconnect-ocp4.14-lp-rosa-classic-images

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-skupperproject-skupper-openshift-smoke-test-image-main-service-interconnect-ocp4.14-lp-rosa-classic-rhsi-interop-rosa-aws

**Comment by oharan2** [comment]
/pj-rehearse pull-ci-skupperproject-skupper-openshift-smoke-test-image-main-service-interconnect-ocp4.14-lp-rosa-classic-images

**Comment by oharan2** [comment]
/pj-rehearse periodic-ci-skupperproject-skupper-openshift-smoke-test-image-main-service-interconnect-ocp4.14-lp-rosa-classic-rhsi-interop-rosa-aws

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
