### PR TITLE
SPO: Use go 1.20

### PR DESCRIPTION
**Pull request by jhrozek**
Let's keep up with times

### CODE REVIEW

**Comment by jhrozek** [comment]
/pj-rehearse pull-ci-openshift-security-profiles-operator-main-unit

**Comment by jhrozek** [comment]
/pj-rehearse pull-ci-openshift-security-profiles-operator-main-unit

**Comment by jhrozek** [comment]
/pj-rehearse pull-ci-openshift-security-profiles-operator-main-images

**Review by saschagrunert — APPROVED** [review]
/retest

**Comment by jhrozek** [comment]
Unfortunately this won't work, see [this comment](https://github.com/openshift/security-profiles-operator/pull/26#issuecomment-1476925716).
I'll propose a different patch that disables the unit tests temporarily.

**Pull request closed without merging**
