### PR TITLE
Expand OpenShift Pipeline to 4.16

### PR DESCRIPTION
**Pull request by liswang89**

### CODE REVIEW

**Comment by liswang89** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.16-lp-rosa-hypershift-openshift-pipelines-rosa-hypershift

**Comment by liswang89** [comment]
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.15-openshift-pipelines-ocp4.16-lp-rosa-hypershift-openshift-pipelines-rosa-hypershift

**Review by ppitonak — APPROVED** [review]

**Pull request merged**
