### PR TITLE
misc: bump osde2e go version to 1.21

### PR DESCRIPTION
**Pull request by jbpratt**
1.20 went EOL 2 months ago

https://endoflife.date/go

### CODE REVIEW

**Comment by jbpratt** [comment]
/pj-rehearse pull-ci-openshift-osde2e-main-hypershift-pr-check

**Comment by jbpratt** [comment]
/pj-rehearse pull-ci-openshift-osde2e-main-hypershift-pr-check

**Review by YiqinZhang — COMMENTED** [review]
/lgtm

**Pull request merged**
