### PR TITLE
Sync Serverless CI config/

### PR DESCRIPTION
**Pull request by serverless-qe**

### CODE REVIEW

**Comment by mgencur** [comment]
Sent https://github.com/openshift-knative/hack/pull/211 to fix this.

**Comment by mgencur** [comment]
The PR https://github.com/openshift-knative/hack/pull/211 was merged and the current PR re-generated but it's probably still wrong. It changes the target Slack channel. Need to look

**Comment by mgencur** [comment]
Asked on [Slack](https://redhat-internal.slack.com/archives/C04QDE5TK1C/p1724834456641789?thread_ts=1719312961.277299&cid=C04QDE5TK1C) if we can merge it. The config with different Slack notifications is not ours.

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by mgencur** [comment]
This PR was changing the slack channel but the INTEROP team wants to use their channel for now: https://redhat-internal.slack.com/archives/C04QDE5TK1C/p1724867812276739?thread_ts=1719312961.277299&cid=C04QDE5TK1C
I will send a fix in a separate PR.

**Pull request merged**
