### PR TITLE
[INTEROP-7365] Update ACM config for 2.10.

### PR DESCRIPTION
**Pull request by dfrazzette**

### CODE REVIEW

**Comment by dfrazzette** [comment]
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.16-lp-interop-acm-interop-aws

**Comment by vboulos** [comment]
@dfrazzette you may need to update the image in mch must-gather, it has to be `must-gather-rhel9 `
https://github.com/vboulos/release/blob/f4634b57c40d345ca9d482c1e6f4e9066c1605d9/ci-operator/step-registry/mce/must-gather/mce-must-gather-commands.sh#L9

**Comment by dfrazzette** [comment]
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.16-lp-interop-acm-interop-aws

**Comment by dfrazzette** [comment]
Reviewed by @vboulos; comments in [ACM-10644](https://issues.redhat.com/browse/ACM-10644):
>* ACM 2.10 moved to ubi 9, which creates an image with RHEL 9 in the name for must-gather
> * Test failures in rehearsal job will be investigated and fixed by team in separate PR(s).

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
