### PR TITLE
Adding openssl installation

### PR DESCRIPTION
**Pull request by tonyxrmdavidson**
This commit will install openssl as part of the oci job

### CODE REVIEW

**Comment by tonyxrmdavidson** [comment]
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-e2e-odh-mro-optional

**Comment by tonyxrmdavidson** [comment]
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-e2e-odh-mro-optional

**Review by nehachopra27 — APPROVED** [review]
Openssl and customise installation code looks good. The script failures can be fixed in next PR

**Pull request closed without merging**
