### PR TITLE
add 4.17 config

### PR DESCRIPTION
**Pull request by shakyav**
Prow job - https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/58247/rehearse-58247-periodic-ci-rhbk-sso-test-main-rhsso-product-ocp4.17-lp-rosa-hypershift-rhsso-interop-aws/1851802584226992128

### CODE REVIEW

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-rhbk-sso-test-main-rhsso-product-ocp4.17-lp-rosa-hypershift-rhsso-interop-aws

**Comment by shakyav** [comment]
/pj-rehearse periodic-ci-rhbk-sso-test-main-rhsso-product-ocp4.17-lp-rosa-hypershift-rhsso-interop-aws

**Review by Simranpal — APPROVED** [review]
/lgtm

**Pull request merged**
