### PR TITLE
OPRUN-1873: infra-periodics: add a daily job to downstream OLM commits

### PR DESCRIPTION
**Pull request by stevekuznetsov**
depends on #42749

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
This needs https://github.com/openshift/operator-framework-olm/pull/561 but is otherwise good

**Comment by stevekuznetsov** [comment]
/pj-rehearse pull-ci-openshift-operator-framework-olm-master-images

**Comment by stevekuznetsov** [comment]
/pj-rehearse pull-ci-openshift-operator-framework-olm-master-images

**Comment by stevekuznetsov** [comment]
/pj-rehearse pull-ci-openshift-operator-framework-olm-master-images

**Review by hongkailiu — APPROVED** [review]

**Pull request merged**
