### PR TITLE
Update the list of owners for PowerVS

### PR DESCRIPTION
**Pull request by rpsene**
Signed-off-by: Rafael Peria de Sene <rpsene@br.ibm.com>

### CODE REVIEW

**Comment by rpsene** [comment]
@stevekuznetsov I had to update the owners given some recent changes in the contributors. Can you review it?

**Comment by rpsene** [comment]
@stevekuznetsov @manojnkumar can you approve this one?

**Review by Elayaraja-Dhanapal — APPROVED** [review]
/lgtm

**Comment by stevekuznetsov** [comment]
He likely needs to accept the invite ...

**Comment by jupierce** [comment]
@Kuldip-Nanda please accept the invitation for the openshift organization. Once that is done, please run `/verify-owners` in this PR.

**Pull request merged**
