### PR TITLE
Hive: Get rid of unnecessary hivebase

### PR DESCRIPTION
**Pull request by 2uasimojo**
The Dockerfile.hivebase wasn't doing anything useful. (It was installing openssh-clients -- but the Dockerfile does that anyway.) So collapse the image builds to get rid of it. This should let us get rid of the Dockerfile.hivebase in the hive repo, and make the appsre ci.ext job redundant as well.

### CODE REVIEW

**Review by joelddiaz — COMMENTED** [review]
:+1: would like to get confirmation that no one is depending on these promoted images.

**Comment by 2uasimojo** [comment]
Okay, this is working now. The azure fail is spurious. And at this time the main e2e hasn't finished yet. But the e2e-gcp rehearsal succeeded, which means it got the right image, which means they all will.

**Comment by suhanime** [comment]
> Okay, this is working now. The azure fail is spurious. And at this time the main e2e hasn't finished yet. But the e2e-gcp rehearsal succeeded, which means it got the right image, which means they all will.

Cool - I will wait for the main e2e to finish before LGTM because it will merge without waiting for it to pass if it is approved

**Comment by 2uasimojo** [comment]
Actually

/hold

>  would like to get confirmation that no one is depending on these promoted images.

I found where this is being referenced: all over the default manifests in the hive repo itself.

```
[efried@efried hive]$ git grep -F hive-v4.0
Makefile:       cd overlays/deploy && kustomize edit set image registry.ci.openshift.org/openshift/hive-v4.0:hive=${IMG} && kustomize edit set namespace ${HIVE_OPERATOR_NS}
config/controllers/deployment.yaml:      - image: registry.ci.openshift.org/openshift/hive-v4.0:hive
config/hiveadmission/deployment.yaml:        image: registry.ci.openshift.org/openshift/hive-v4.0:hive
config/operator/operator_deployment.yaml:      - image: registry.ci.openshift.org/openshift/hive-v4.0:hive
hack/local-e2e-test.sh:export HIVE_IMAGE="registry.ci.openshift.org/openshift/hive-v4.0:hive"
pkg/controller/images/controller_images.go:     DefaultHiveImage = "registry.ci.openshift.org/openshift/hive-v4.0:hive"
pkg/operator/assets/bindata.go:        image: registry.ci.openshift.org/openshift/hive-v4.0:hive
pkg/operator/assets/bindata.go:      - image: registry.ci.openshift.org/openshift/hive-v4.0:hive
```

Arguably we should be using quay.io/app-sre/hive:latest instead; but that's certainly a separate issue. I'll update this to reinstate the `promotion` stanza (since that's not related to getting rid of hivebase) and worry about it another time.

**Comment by 2uasimojo** [comment]
> I'll update this to reinstate the `promotion` stanza

That's done.

Aside: I wish e2e *either* flaked less frequently *or* took about an order of magnitude less time. I would settlle for either one. Waiting a minimum of O(hours) to merge a PR is just awful. Maybe I'm spoiled.

**Pull request merged**
