### PR TITLE
chore(RHIDP-2121): Setup jobs for comparing RHDH installed with Helm and OLM

### PR DESCRIPTION
**Pull request by pmacik**

### CODE REVIEW

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp-olm

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp pull-ci-redhat-performance-backstage-performance-main-mvp-olm

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp pull-ci-redhat-performance-backstage-performance-main-mvp-olm

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp pull-ci-redhat-performance-backstage-performance-main-mvp-olm

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp pull-ci-redhat-performance-backstage-performance-main-mvp-olm

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp-olm

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp-olm

**Review by yogananth-subramanian — APPROVED** [review]

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp pull-ci-redhat-performance-backstage-performance-main-mvp-olm

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp-helm pull-ci-redhat-performance-backstage-performance-main-mvp-olm

**Review by yogananth-subramanian — APPROVED** [review]

**Pull request merged**
