### PR TITLE
Update to use go1.11 for controller-manager-operator

### PR DESCRIPTION
**Pull request by coreydaley**

### CODE REVIEW

**Comment by adambkaplan** [comment]
@coreydaley need go1.11  for release-4.0 as well. For reasons both branches are synced with master.

**Comment by coreydaley** [comment]
@adambkaplan updated, ptal

**Comment by adambkaplan** [comment]
Also may need to run prow-gen: https://github.com/openshift/release/blob/master/ci-operator/README.md#ci-operator

**Comment by coreydaley** [comment]
/retest

@adambkaplan ran the prow-gen locally and there were no errors or changes (only warnings about names longer than 63 chars)

**Comment by bparees** [comment]
you sure about this?  

https://github.com/openshift/release/blob/master/ci-operator/config/openshift/cluster-openshift-apiserver-operator/openshift-cluster-openshift-apiserver-operator-master.yaml#L12
https://github.com/openshift/release/blob/master/ci-operator/config/openshift/cluster-kube-controller-manager-operator/openshift-cluster-kube-controller-manager-operator-master.yaml#L12

**Comment by adambkaplan** [comment]
/hold

Have the rest of the control plane not bumped api and client-go?

**Comment by bparees** [comment]
dunno.  but also i'd expect this to be where you made the change to use go1.11?  https://github.com/openshift/cluster-kube-apiserver-operator/blob/master/Dockerfile.rhel7#L1

**Comment by bparees** [comment]
well i guess that FROM will be substituted somewhere in the process, but it should probably be updated regardless as part of this.

**Comment by adambkaplan** [comment]
we already have a PR to update the golang in the Dockerfile - https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/86

**Comment by adambkaplan** [comment]
@stevekuznetsov can you weigh in here on what this does?

**Comment by coreydaley** [comment]
Even after updating the Dockerfile to use go1.11, the tests are still using go1.10.

**Comment by coreydaley** [comment]
@soltysh Do we need to let this merge now due to https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/89 ?

**Comment by soltysh** [comment]
> @soltysh Do we need to let this merge now due to [openshift/cluster-openshift-controller-manager-operator#89](https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/89) ?

I'm not sure about 4.0 and 4.1 branches, yet. For now I'd stick with just master.

**Comment by coreydaley** [comment]
@soltysh thanks!

@adambkaplan updated per suggestions from @soltysh, ptal

**Comment by soltysh** [comment]
:man_facepalming: and I thought I did that in https://github.com/openshift/release/pull/3489

**Comment by coreydaley** [comment]
@soltysh You did openshift-cluster-kube-controller-manager-operator-master.yaml

**Comment by soltysh** [comment]
> @soltysh You did openshift-cluster-kube-controller-manager-operator-master.yaml

I know, that's why the :man_facepalming: :stuck_out_tongue_closed_eyes:

**Pull request merged**
