### PR TITLE
[WIP] Unblock OpenTelemetry tests

### PR DESCRIPTION
**Pull request by IshwarKanse**

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests

**Review by frzifus — APPROVED** [review]

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
Will be fixed by https://github.com/open-telemetry/opentelemetry-operator/pull/2702

**Pull request closed without merging**
