### PR TITLE
ci-operator: Mark all OLM non-e2e jobs as required

### PR DESCRIPTION
**Pull request by timflannagan**
Manually re-opening #17437 as a bad force push closed the PR and I don't have the requisite permissions to re-open that.

### CODE REVIEW

**Review by ankitathomas — APPROVED** [review]
/lgtm

**Comment by timflannagan** [comment]
Looks like some of those unit tests are broken atm. Let's get those fixed up and merge any syncs first before merging this and making them required checks.

/hold

**Pull request merged**
