### PR TITLE
fix release 4.5/4.6 config for aws-pod-identity-webhook

### PR DESCRIPTION
**Pull request by sjenning**
@stevekuznetsov @smarterclayton @bbguimaraes

### CODE REVIEW

**Comment by sjenning** [comment]
gah, making a mess of this! :disappointed:

**Comment by petr-muller** [comment]
This should not be needed, the automation creates these, but the automation got stuck: https://github.com/openshift/release/pull/7939

**Comment by sjenning** [comment]
@petr-muller so... should I close this?

**Comment by petr-muller** [comment]
Yeah, https://github.com/openshift/release/pull/8198 should bring everything from the stuck PR (including the jobs for aws-pod-identity-webhook) and we are fixing the tooling to not get stuck like that anymore.

**Pull request closed without merging**
