### PR TITLE
psap-ci-artifacts: add postsubmits gpu-operator-e2e on 'release-next' branch

### PR DESCRIPTION
**Pull request by kpouget**
Add `gpu-operator-e2e` testing on `https://github.com/openshift-psap/ci-artifacts` postsubmit on `release-next` branch.

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
/uncc  jmencak 
//uncc @dagrayvid 
/lgtm

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Comment by kpouget** [comment]
I update the code to fix [this issue](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/14813/pull-ci-openshift-release-master-ordered-prow-config/1349392892837236736/build-log.txt): 

```
ERROR: This check enforces Prow Job configuration YAML file format (ordering,
ERROR: linebreaks, indentation) to be consistent over the whole repository. We have
ERROR: automation in place that manipulates these configs and consistent formatting
ERROR: helps reviewing the changes the automation does.

ERROR: Run the following command to re-format the Prow jobs:
ERROR: $ make jobs

ERROR: The following errors were found:

diff -Naupr -I '^[[:space:]]*#.*' /tmp/tmp.y5FwpwA21Z/jobs/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-devel-postsubmits.yaml .//ci-operator/jobs/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-devel-postsubmits.yaml
--- /tmp/tmp.y5FwpwA21Z/jobs/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-devel-postsubmits.yaml	2021-01-13 16:29:28.386561604 +0000
+++ .//ci-operator/jobs/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-devel-postsubmits.yaml	2021-01-13 16:29:47.421219552 +0000
@@ -1,7 +1,6 @@
 postsubmits:
   openshift-psap/ci-artifacts:
   - agent: kubernetes
-    always_run: true
     branches:
     - devel
     cluster: build02
@@ -12,7 +11,6 @@ postsubmits:
       ci-operator.openshift.io/prowgen-controlled: "true"
       pj-rehearse.openshift.io/can-be-rehearsed: "true"
     name: pull-ci-openshift-psap-ci-artifacts-devel-gpu-operator-e2e
-    rerun_command: /test gpu-operator-e2e
     spec:
       containers:
       - args:
@@ -63,4 +61,3 @@ postsubmits:
       - name: result-aggregator
         secret:
           secretName: result-aggregator
-    trigger: (?m)^/test( | .* )gpu-operator-e2e,?($|\s.*)

```

**Comment by kpouget** [comment]
I dont understand why this fails

> {"command":"git fetch https://github.com/openshift-psap/ci-artifacts.git release-next","component":"clonerefs","error":"exit status 128","file":"prow/pod-utils/clone/clone.go:315","func":"k8s.io/test-infra/prow/pod-utils/clone.retryCommand.run","level":"info","msg":"Retrying after sleep","severity":"info","sleep":800000000,"time":"2021-01-14T08:48:15Z"}

while 
```
git fetch https://github.com/openshift-psap/ci-artifacts.git release-next
```
works on my system ...

**Comment by ArangoGutierrez** [comment]
/hold
I want to see some things into the devel branch before starting to run the tests

**Comment by kpouget** [comment]
@ArangoGutierrez FYI I changed the target branch to 'release-next' to match the pattern-matching in this document:

https://github.com/openshift/release/blob/2d5335fbe682181d26d3fd35d3370f2b0163fc1e/core-services/prow/02_config/_plugins.yaml#L805

and exactly, this one:

>   ci-operator/config/**/*release-next*.yaml:

and that solves one of the failing jobs

**Comment by kpouget** [comment]
but, wait, all the tests are passing??
so I struggled for a while, while it was only because of the CI starting to fail, or maybe a cache effect for this one

> I dont understand why this fails
> 
> > {"command":"git fetch https://github.com/openshift-psap/ci-artifacts.git release-next","component":"clonerefs","error":"exit status 128","file":"prow/pod-utils/clone/clone.go:315","func":"k8s.io/test-infra/prow/pod-utils/clone.retryCommand.run","level":"info","msg":"Retrying after sleep","severity":"info","sleep":800000000,"time":"2021-01-14T08:48:15Z"}
> 
> while
> 
> ```
> git fetch https://github.com/openshift-psap/ci-artifacts.git release-next
> ```
> 
> works on my system ...

;-)

**Review by ArangoGutierrez — APPROVED** [review]
/unhold
/lgtm

**Pull request merged**
