### PR TITLE
Add serial and TechPreviewNoUpgrade serial jobs to Cluster Config Operator

### PR DESCRIPTION
**Pull request by JoelSpeed**
We added new features that broke serial tests, need to make sure that we have these tests passing in future so as not to break the payload

### CODE REVIEW

**Comment by wking** [comment]
Seems to have [lost a race to a build03 vs. build05 change][1]?

```
diff -Naupr -I '^[[:space:]]*#.*' /tmp/tmp.cN2K2WB83T/jobs/openshift/cluster-config-operator/openshift-cluster-config-operator-master-presubmits.yaml .//ci-operator/jobs/openshift/cluster-config-operator/openshift-cluster-config-operator-master-presubmits.yaml
--- /tmp/tmp.cN2K2WB83T/jobs/openshift/cluster-config-operator/openshift-cluster-config-operator-master-presubmits.yaml	2023-08-22 22:40:17.915622916 +0000
+++ .//ci-operator/jobs/openshift/cluster-config-operator/openshift-cluster-config-operator-master-presubmits.yaml	2023-08-22 22:40:19.433721657 +0000
@@ -149,7 +149,7 @@ presubmits:
     branches:
     - ^master$
     - ^master-
-    cluster: build03
+    cluster: build05
     context: ci/prow/e2e-aws-serial
     decorate: true
     labels:
```

Removing from the merge pool momentarily to let the other merge-pool pulls land:

/hold
/test ordered-prow-config

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/batch/pull-ci-openshift-release-master-ordered-prow-config/1694117026940850176

**Comment by JoelSpeed** [comment]
/pj-rehearse ack

Nothing changed from rehearsal perspective

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
