### PR TITLE
Remove jobs periodic-ci-image-import-to-build01/2

### PR DESCRIPTION
**Pull request by hongkailiu**
Follow up https://coreos.slack.com/archives/CHY2E1BL4/p1594993882317000

After merge, I will delete those objects:

```
➜  ~ oc --context build01 get sa -n ci image-importer
NAME             SECRETS   AGE
image-importer   2         147d
➜  ~ oc --context build02 get sa -n ci image-importer
NAME             SECRETS   AGE
image-importer   2         61d
```

/cc @alvaroaleman @stevekuznetsov

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/hold
Are we sure we distribute them?

**Comment by hongkailiu** [comment]
@alvaroaleman 

That was how we import ci-tools images before the use-only-local-images work.
Maybe I did not understand your question?

**Comment by alvaroaleman** [comment]
@hongkailiu are you sure the test image distrubuting controller actually distributes them? I believe it only distributes whats references in ci-op config and a set of explicitly configured imagestreamtags. It does right now now have an option to allowlist a whole namespace (but could be added)/

**Comment by hongkailiu** [comment]
doing a new flag for namespace.

**Comment by hongkailiu** [comment]
> Needs to wait until build finishes. This also allows us to remove all auto imports we have. Do you mind either creating a card or doing it in this PR?

Do you mean those?

https://github.com/openshift/release/blob/master/clusters/build-clusters/01_cluster/openshift/ci-operator/ci-tools_imagestreams.yaml#L15

**Comment by alvaroaleman** [comment]
> Do you mean those?
> https://github.com/openshift/release/blob/master/clusters/build-clusters/01_cluster/openshift/ci-operator/ci-tools_imagestreams.yaml#L15

Sorry, too many things happening, I forgot to respond. I think pretty much all `ImageStream`s in the cluster/ directory qualify for this, right now that would be:
```
$ rg 'kind: ImageStream' clusters/
clusters/app.ci/assets/bugzilla-backporter.yaml
4:- kind: ImageStream

clusters/app.ci/assets/dptp-controller-manager.yaml
1:kind: ImageStream

clusters/app.ci/ci-chat-bot/ci-chat-bot.yaml
2:kind: ImageStream

clusters/app.ci/ci-operator-configresolver/ci-operator-configresolver.yaml
4:- kind: ImageStream

clusters/app.ci/result-aggregator/result-aggregator.yaml
4:- kind: ImageStream

clusters/app.ci/release-controller/imagestreamimport.yaml
1:kind: ImageStream

clusters/app.ci/ci-ns-ttl-controller/ci-ns-ttl-controller_imagestream.yaml
2:kind: ImageStream

clusters/app.ci/prow/03_deployment/adapter_imagestreams.yaml
5:  kind: ImageStream
18:  kind: ImageStream
31:  kind: ImageStream
44:  kind: ImageStream
57:  kind: ImageStream
70:  kind: ImageStream
83:  kind: ImageStream
96:  kind: ImageStream
109:  kind: ImageStream
122:  kind: ImageStream
135:  kind: ImageStream
148:  kind: ImageStream
161:  kind: ImageStream
174:  kind: ImageStream
187:  kind: ImageStream
200:  kind: ImageStream
213:  kind: ImageStream
226:  kind: ImageStream
239:  kind: ImageStream

clusters/build-clusters/01_cluster/ci-search/deploy.yaml
7:kind: ImageStream

clusters/build-clusters/01_cluster/openshift/release-controller/content-mirror_imagestream.yaml
2:kind: ImageStream

clusters/build-clusters/01_cluster/openshift/ci-operator/ci_imagestreams.yaml
3:kind: ImageStream

clusters/build-clusters/01_cluster/openshift/ci-operator/ci-tools_imagestreams.yaml
3:kind: ImageStream
19:kind: ImageStream
35:kind: ImageStream
51:kind: ImageStream
67:kind: ImageStream
83:kind: ImageStream
99:kind: ImageStream
115:kind: ImageStream
131:kind: ImageStream
147:kind: ImageStream
163:kind: ImageStream
179:kind: ImageStream
195:kind: ImageStream
211:kind: ImageStream
227:kind: ImageStream
243:kind: ImageStream
259:kind: ImageStream
275:kind: ImageStream
291:kind: ImageStream
307:kind: ImageStream
323:kind: ImageStream
339:kind: ImageStream
355:kind: ImageStream
371:kind: ImageStream
387:kind: ImageStream
403:kind: ImageStream

clusters/build-clusters/01_cluster/openshift/secret-mirroring/ci-secret-mirroring-controller_imagestream.yaml
2:kind: ImageStream

clusters/build-clusters/01_cluster/openshift/secret-mirroring/deployment.yaml
47:        kind: ImageStreamTag

clusters/build-clusters/01_cluster/openshift/ci-ns-ttl-controller/ci-ns-ttl-controller_dc.yaml
36:        kind: ImageStreamTag

clusters/build-clusters/01_cluster/openshift/ci-ns-ttl-controller/ci-ns-ttl-controller_imagestream.yaml
2:kind: ImageStream

clusters/build-clusters/02_cluster/openshift/ci-ns-ttl-controller/ci-ns-ttl-controller_dc.yaml
36:        kind: ImageStreamTag

clusters/build-clusters/02_cluster/openshift/ci-ns-ttl-controller/ci-ns-ttl-controller_imagestream.yaml
2:kind: ImageStream

clusters/build-clusters/02_cluster/openshift/ci-operator/ci_imagestreams.yaml
3:kind: ImageStream

clusters/build-clusters/02_cluster/openshift/ci-operator/ci-tools_imagestreams.yaml
3:kind: ImageStream
19:kind: ImageStream
35:kind: ImageStream
51:kind: ImageStream
67:kind: ImageStream
83:kind: ImageStream
99:kind: ImageStream
115:kind: ImageStream
131:kind: ImageStream
147:kind: ImageStream
163:kind: ImageStream
179:kind: ImageStream
195:kind: ImageStream
211:kind: ImageStream
227:kind: ImageStream
243:kind: ImageStream
259:kind: ImageStream
275:kind: ImageStream
291:kind: ImageStream
307:kind: ImageStream
323:kind: ImageStream
339:kind: ImageStream
355:kind: ImageStream
371:kind: ImageStream
387:kind: ImageStream
403:kind: ImageStream

clusters/build-clusters/02_cluster/openshift/release-controller/content-mirror_imagestream.yaml
2:kind: ImageStream

clusters/build-clusters/02_cluster/openshift/secret-mirroring/ci-secret-mirroring-controller_imagestream.yaml
2:kind: ImageStream

clusters/build-clusters/02_cluster/openshift/secret-mirroring/deployment.yaml
47:        kind: ImageStreamTag
```

**Comment by hongkailiu** [comment]
How can we recovery those images if we delete those objects by any chance?

**Comment by alvaroaleman** [comment]
> How can we recovery those images if we delete those objects by any chance?

The image-distribution-controller will create them on all build clusters or WDYM?

**Pull request merged**
