### PR TITLE
openstack: Bump tooling images

### PR DESCRIPTION
**Pull request by pierreprinetti**

### CODE REVIEW

**Comment by pierreprinetti** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-cleanup-vexxhost periodic-ci-shiftstack-bugwatcher-main-bugwatcher-pretriage pull-ci-shiftstack-ci-configs-main-test-provision

**Comment by pierreprinetti** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-cleanup-vexxhost periodic-ci-shiftstack-bugwatcher-main-bugwatcher-pretriage pull-ci-shiftstack-ci-configs-main-test-provision

**Comment by pierreprinetti** [comment]
/pj-rehearse pull-ci-shiftstack-ci-configs-main-test-provision

**Comment by pierreprinetti** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-cleanup-vexxhost periodic-ci-shiftstack-bugwatcher-main-bugwatcher-pretriage pull-ci-shiftstack-ci-configs-main-test-provision

**Review by mandre — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
