### PR TITLE
knative-eventing release-v0.17.2

### PR DESCRIPTION
**Pull request by lberk**

### CODE REVIEW

**Comment by matzew** [comment]
```
go install ./cmd/apiserver_receive_adapter/ ./cmd/controller/ ./cmd/in_memory/channel_controller/ ./cmd/in_memory/channel_dispatcher/ ./cmd/mtchannel_broker/ ./cmd/mtping/ ./cmd/ping/ ./cmd/pong/ ./cmd/sendevent/ ./cmd/sugar_controller/ ./cmd/v0.16/broker-cleanup/ ./cmd/v0.17/pingsource-cleanup/ ./cmd/webhook/ ./vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate
/usr/local/go/pkg/tool/linux_amd64/link: signal: killed
make: *** [install] Error 1
```

@lberk ^

**Comment by lberk** [comment]
flakes with CI infra
/retest

**Pull request merged**
