### PR TITLE
[amq streams] - update to 2.4.0 AMQ Streams version

### PR DESCRIPTION
**Pull request by see-quick**
This PR adds the following:
1. a new version of AMQ Streams product (i.e., 2.4.0)
2. adding a new strimzi-tests image `0.34.x`

### CODE REVIEW

**Comment by see-quick** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-2-4-amq-streams-ocp4.14-lp-interop-amq-streams-2-4

**Comment by see-quick** [comment]
/pj-rehearse  periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.14-lp-interop-amq-streams-2-4

**Comment by see-quick** [comment]
So, this should be merged https://github.com/openshift/release/pull/39731 and then  I can proceed with this PR

**Comment by see-quick** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.14-lp-interop-amq-streams-2-4

**Comment by see-quick** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.14-lp-interop-amq-streams-2-4

**Comment by see-quick** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.14-lp-interop-amq-streams-2-4

**Comment by see-quick** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.14-lp-interop-amq-streams-2-4

**Comment by chetna14manku** [comment]
@see-quick PR is missing `rehearsals-ack` label to get it merge, you can add it by running `/pj-rehearse ack` if job results look good to you

**Comment by see-quick** [comment]
@chetna14manku done

**Pull request merged**
