### PR TITLE
add telco cnf images to image mirroring

### PR DESCRIPTION
**Pull request by SchSeba**
now that all the metallb sriov and ptp repos are private we can enable the image mirroring again

ticket: [DPTP-4036](https://issues.redhat.com//browse/DPTP-4036)

### CODE REVIEW

**Comment by SchSeba** [comment]
waiting for https://github.com/openshift/release/pull/52340

**Comment by smg247** [comment]
/pj-rehearse pull-ci-openshift-ib-sriov-cni-release-4.15-okd-scos-images

**Comment by jupierce** [comment]
/lgtm
/hold
Please include DPTP Jira in the description for historical context before unholding.

**Comment by SchSeba** [comment]
rebased on master to fix merge conflict

@jupierce when you have time please take a look :)

**Pull request merged**
