### PR TITLE
cvo: explicitly import hypershift base images

### PR DESCRIPTION
**Pull request by petr-muller**
Follow https://github.com/openshift/release/pull/57123

### CODE REVIEW

**Comment by petr-muller** [comment]
/pj-rehearse pull-ci-openshift-cluster-version-operator-release-4.16-e2e-hypershift pull-ci-openshift-cluster-version-operator-release-4.16-e2e-hypershift-conformance pull-ci-openshift-cluster-version-operator-master-e2e-hypershift pull-ci-openshift-cluster-version-operator-master-e2e-hypershift-conformance

**Comment by wking** [comment]
Rehearsals passed, except for [the dev branch one][1], but even that one didn't fail on image-import.

/pj-rehearse ack

[1]: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/57408/rehearse-57408-pull-ci-openshift-cluster-version-operator-master-e2e-hypershift/1841547643340197888

**Pull request merged**
