### PR TITLE
Update Cilium OLM location

### PR DESCRIPTION
**Pull request by jtaleric**
Update the path to copy Cilium OLM and use latest 1.13 release

### CODE REVIEW

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.13-e2e-aws-cilium

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.13-e2e-aws-cilium

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.13-e2e-aws-cilium

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.13-e2e-aws-cilium

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.13-e2e-aws-cilium

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.13-e2e-aws-cilium

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.13-e2e-aws-cilium

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.13-e2e-aws-cilium

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.13-e2e-aws-cilium

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.13-e2e-aws-cilium

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.13-e2e-aws-cilium

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.13-e2e-aws-cilium

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.13-e2e-aws-cilium

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-e2e-aws-cilium

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.13-nightly-x86-perfscale-aws-cilium-control-plane-24nodes-periodic

**Comment by psalajova** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-e2e-aws-cilium

**Comment by smg247** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-e2e-aws-cilium

**Comment by smg247** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-e2e-aws-cilium

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-e2e-aws-cilium

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-e2e-aws-cilium

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.13-e2e-aws-cilium

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.13-e2e-aws-cilium

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.13-e2e-aws-cilium

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.13-e2e-aws-cilium

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.13-e2e-aws-cilium

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.13-nightly-x86-cilium-data-path-9nodes

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-nightly-x86-cilium-control-plane-120nodes

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-nightly-x86-cilium-control-plane-24nodes periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-cilium-node-density-cni-24nodes

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-cilium-data-path-9nodes

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-cilium-data-path-9nodes

**Comment by jtaleric** [comment]
/pj-reherase periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-cilium-control-plane-24nodes

**Comment by jtaleric** [comment]
/pj-reherase periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-cilium-control-plane-24nodes

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-nightly-x86-cilium-control-plane-24nodes

**Pull request merged**
