### PR TITLE
Update openshift/kubernetes master to build with golang 1.14

### PR DESCRIPTION
**Pull request by marun**
~This PR is pending the merge of openshift/kubernetes#166~ Merged

### CODE REVIEW

**Comment by ravisantoshgudimetla** [comment]
@marun - Should we still have golang 1.14 considering upstream kube is moving to [golang-1.15](https://groups.google.com/d/msgid/kubernetes-dev/CAOqU-DSHH4z0ybpyy%3D%3DBarP%3Dy%2BN101%3DZhZv7V%2BieGdwnjo19tQ%40mail.gmail.com?utm_medium=email&utm_source=footer)

**Comment by marun** [comment]
> @marun - Should we still have golang 1.14 considering upstream kube is moving to [golang-1.15](https://groups.google.com/d/msgid/kubernetes-dev/CAOqU-DSHH4z0ybpyy%3D%3DBarP%3Dy%2BN101%3DZhZv7V%2BieGdwnjo19tQ%40mail.gmail.com?utm_medium=email&utm_source=footer)

We're aware of the proposed upstream switch, but afaik it is undecided as to whether 4.6 will follow. This PR is required to ensure that openshift/kubernetes is built in CI with 1.14 to synchronize with ART which is already building with that version.

**Comment by deads2k** [comment]
/lgtm
/hold

release the hold when you're sure those rehearses are in a good state.

**Comment by deads2k** [comment]
/lgtm
/hold

holding until @marun is satisfied this will not bork builds.

**Pull request merged**
