### PR TITLE
Add OpenTelemetry upgrade test job using OLM

### PR DESCRIPTION
**Pull request by IshwarKanse**
* Add OpenTelemetry upgrade test job using OLM
* Add reporter_config to report job status in Slack channel. 
* Remove unneeded Prow CI plugins and set branch protection as unmanaged for Jaeger.

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-operator-main-ocp-4.13-amd64-upgrade-opentelemetry-operator-upgrade

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-operator-main-ocp-4.13-amd64-upgrade-opentelemetry-operator-upgrade

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-operator-main-ocp-4.13-amd64-upgrade-opentelemetry-operator-upgrade

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-open-telemetry-operator-main-ocp-4.13-amd64-upgrade-opentelemetry-operator-upgrade

**Comment by IshwarKanse** [comment]
@frzifus @iblancasa when you get some time can you approve this. Thanks.

**Review by frzifus — APPROVED** [review]

**Pull request merged**
