### PR TITLE
Run Jenkins s2i tests on every PR

### PR DESCRIPTION
**Pull request by adambkaplan**

### CODE REVIEW

**Comment by adambkaplan** [comment]
@stevekuznetsov looks like the generated config check fails. Is there a way to add the jenkins-based job as an item to s2i's ci-operator config?

**Comment by stevekuznetsov** [comment]
@adambkaplan if you look at the error logs you'll see the generator is just annoyed at the trailing newline

**Comment by adambkaplan** [comment]
@stevekuznetsov ready for review

**Pull request merged**
