### PR TITLE
Update feature gate step registry steps to use the install config

### PR DESCRIPTION
**Pull request by JoelSpeed**
To enable the installer to render the feature gate status, we need to make sure we are actually using the feature gates via the installer rather than placing them directly into the manifests directly. This can only be done for `TechPreviewNoUpgrade` so far.

Since there is an existing feature-set step that did this (though techpreview is wider used) I've copied it for now, at some point we should deduplicate.

The customnoupgrade step was only present in one chain, and the vars used to configure it were not present anywhere, thus, it's not currently being used. Since it's going to be broken very shortly by some installer changes, we should remove it until an install-config route exists.

CC @EmilienM @deads2k @patrickdillon

### CODE REVIEW

**Comment by deads2k** [comment]
be sure to get a rehearse

/lgtm
/approve
/hold

**Comment by EmilienM** [comment]
I don't know why the externallb job failed, TBH. I think it's not related to this PR:
https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.14-e2e-openstack-externallb-techpreview

**Comment by JoelSpeed** [comment]
The install-config for the failed job had `featureSet: TechPreviewNoUpgrade` and I can see the [featuregate](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/38769/rehearse-38769-pull-ci-openshift-installer-master-e2e-openstack-externallb-techpreview/1651229907641962496/artifacts/e2e-openstack-externallb-techpreview/gather-must-gather/artifacts/must-gather/inspect.local.7911043885319388719/cluster-scoped-resources/config.openshift.io/featuregates.yaml) itself looks correct, so the intention of this PR has worked

/hold cancel

**Pull request merged**
