### PR TITLE
STOR-1315: build e2eprovider for Secrets Store CSI Driver

### PR DESCRIPTION
**Pull request by dobsonj**
This builds the e2eprovider image that is required by https://github.com/openshift/release/pull/41655

This has to merge as a separate PR before the rehearse jobs for the operator PR will work.

/hold for https://github.com/openshift/secrets-store-csi-driver/pull/5 to merge first

cc @openshift/storage

### CODE REVIEW

**Review by mpatlasov — APPROVED** [review]

**Comment by dobsonj** [comment]
/pj-rehearse ack
the new image is built successfully

**Comment by dobsonj** [comment]
/assign @bparees 
for image-mirroring approval
it was generated with `make openshift-image-mirror-mappings`

**Comment by dobsonj** [comment]
/unhold
https://github.com/openshift/secrets-store-csi-driver/pull/5 already merged

**Pull request merged**
