### PR TITLE
Introducing Rollback informing jobs

### PR DESCRIPTION
**Pull request by bradmwilliams**
It was decided in the 5/18 SHIP architecture call that we would introduce the "rollback" jobs, as release informing, to the various nightly streams. This PR adds the jobs to versions 4.10 through 4.13.

### CODE REVIEW

**Comment by bradmwilliams** [comment]
/hold
For stakeholder buy in

**Comment by stbenjam** [comment]
> > * Who owns these jobs?
> > * Where can TRT send slack Alertmanager alerts for them?
> > * Why are they SDN? If we're going to have one, I'd suggest making it the default OCP configuration (OVN)
> > 
> > @vikaslaad Can you help? I noticed you were listed on the agenda item
> 
>     * QE would own the jobs, we are making them informing for now so that it does not block anything.
> 
>     * TRT should not be looking into the failures, patch manager and QE would look into them for z-stream releases.
> 
>     * I think you worked with Brad on the third one.

The PR still adds them to 4.14.  TRT owns all the jobs on nightlies, we no longer accept adding informers to the dev branch without someone who's actually accountable to fix them (who gets alerts when they fail), otherwise we know they'll eventually fail forever and no one will look.

**Comment by bradmwilliams** [comment]
@stbenjam @vikaslaad I have dropped the job definitions from 4.14.

**Comment by stbenjam** [comment]
/lgtm

Feel free to merge then if 4.14 is out of the picture

**Comment by vikaslaad** [comment]
@stbenjam it needs another lgtm please

**Pull request merged**
