### PR TITLE
Azure & GCP Node scenarios

### PR DESCRIPTION
**Pull request by paigerube14**

### CODE REVIEW

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-ibm-cloud-api-tests

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-ibm-cloud-api-tests

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-ibm-cloud-api-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-cloud-azure-api-tests periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-cloud-gcp-api-tests

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-ibm-cloud-api-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-cloud-gcp-api-tests periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-cloud-azure-api-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-cloud-gcp-api-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-cloud-gcp-api-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-cloud-gcp-api-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-cloud-azure-api-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-cloud-gcp-api-tests

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-cloud-gcp-api-tests

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-ibm-cloud-api-tests periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-cloud-azure-api-tests

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-ibm-cloud-api-tests periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-cloud-azure-api-tests

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-ibm-cloud-api-tests

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-ibm-cloud-api-tests

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-ibm-cloud-api-tests

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-ibm-cloud-api-tests

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-ibm-cloud-api-tests

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-ibm-cloud-api-tests

**Comment by paigerube14** [comment]
@chaitanyaenr PTAL at some previous runs of the node tests on azure and gcp

Azure: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/52581/rehearse-52581-periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-cloud-azure-api-tests/1814306552857759744
GCP: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/52581/rehearse-52581-periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-cloud-gcp-api-tests/1814017947358728192

**Review by chaitanyaenr — APPROVED** [review]
/lgtm

**Pull request merged**
