### PR TITLE
[Do not merge] MCO debug PR to run a full regression on the nutanix p…

### PR DESCRIPTION
**Pull request by sergiordlr**
…rofile used for manual execution

### CODE REVIEW

**Comment by sergiordlr** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-nutanix-ipi-gpu-mco-g2-f28 periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-nutanix-ipi-gpu-mco-g1-f28

**Comment by ptalgulk01** [comment]
Just a thought do we need here to have a slack notification for this?

**Comment by sergiordlr** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-nutanix-ipi-gpu-mco-g2-f28 periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-nutanix-ipi-gpu-mco-g1-f28

**Comment by sergiordlr** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-nutanix-ipi-gpu-mco-g2-f28 periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-nutanix-ipi-gpu-mco-g1-f28

**Comment by sergiordlr** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-nutanix-ipi-gpu-mco-g2-f28 periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-nutanix-ipi-gpu-mco-g1-f28

**Comment by sergiordlr** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-nutanix-ipi-gpu-mco-g2-f28 periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-nutanix-ipi-gpu-mco-g1-f28

**Pull request closed without merging**
