### PR TITLE
update cccmo unit test to request 100m cpu

### PR DESCRIPTION
**Pull request by elmiko**

### CODE REVIEW

**Comment by elmiko** [comment]
/pj-rehearse pull-ci-openshift-cluster-cloud-controller-manager-operator-master-unit

**Comment by elmiko** [comment]
seems like the unit test passed now, which it is not on the master currently (see https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/271). i am going to merge this and see how it affects the PR, if things look good i will port the resource update change to other release branches.

**Review by wking — APPROVED** [review]
/lgtm

**Pull request merged**
