### PR TITLE
Remove standard odh mirroring for Anaconda, keep PR mirror. Add Anaconda to RHDS repo

### PR DESCRIPTION
**Pull request by Xaenalt**
Removes the regular mirroring, keeping PR mirroring for upstream ODH, and adds in the Anaconda mirroring to RHDS

### CODE REVIEW

**Comment by atheo89** [comment]
Was the  `modh/odh-anaconda-notebook` repository created?

**Comment by harshad16** [comment]
> Was the `modh/odh-anaconda-notebook` repository created?

yes it is available now: https://quay.io/repository/modh/odh-anaconda-notebook?tab=tags

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve

Thanks :100:

**Pull request merged**
