### PR TITLE
MGDAPI-1463: Remove cleanup harness and change node count and type

### PR DESCRIPTION
**Pull request by jjkiely**
# What
Remove addon cleanup harness and change node count and machine type for managed-api-service

### CODE REVIEW

**Comment by jeefy** [comment]
Probably need to run a `make jobs` against it and push the updates. :)

**Comment by jjkiely** [comment]
Thanks @jeefy that seemed to sort it out :smile:

**Comment by MStokluska** [comment]
/lgtm
rehearse job passed successfully, cluster got cleaned up also. good job!

**Comment by jeefy** [comment]
Awesome! @jjkiely  Can the PR now remove the rehearsal? https://github.com/openshift/release/pull/18012/files#diff-d214756a87b37f0ad838abce8ddfa8993c7cd6a7614fc15384f5f3e4307f079aR1946 Thanks!

**Comment by jjkiely** [comment]
@jeefy sure thing I'll push the change now :)

**Pull request merged**
