### PR TITLE
don't build/publish docker-builder from origin

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
/hold

As soon as we're happy w/ openshift/builder's prow configuration we should be able to merge this.

@smarterclayton ptal

**Comment by bparees** [comment]
@smarterclayton @stevekuznetsov it looks like we're already publishing images from openshift/builder?

https://github.com/openshift/release/blob/master/ci-operator/config/openshift/builder/openshift-builder-master.yaml#L18-L20

https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/builder/openshift-builder-master-postsubmits.yaml#L12-L15

am I missing something?

**Comment by stevekuznetsov** [comment]
We talked about this ... we're publishing to a different location as per

https://github.com/openshift/release/blob/fd09c7b8d3e4facf4e70ff5b6de2497bc6dac636/ci-operator/config/openshift/builder/openshift-builder-master.yaml#L48-L51

**Comment by stevekuznetsov** [comment]
/lgtm

Config changes here LGTM -- someone else can cancel the hold when we're ready

**Pull request merged**
