### PR TITLE
steps/workers-rhel7: Fail if new_workers is empty

### PR DESCRIPTION
**Pull request by mtnbikenc**
A corner case was discovered where existing worker machinesets had
replicas set to 0 which resulted in no rhel worker nodes being created.
This ensures the job fails earlier instead of much later during scaleup.

Using loop_var for machineset outer loop to prevent collision with item
var in inner loops.

### CODE REVIEW

**Comment by patrickdillon** [comment]
> /lgtm

/hold
Wait I guess I'm a little confused, are we testing replicas==0 in CI?

**Comment by mtnbikenc** [comment]
> Wait I guess I'm a little confused, are we testing replicas==0 in CI?
No, we are not.  But there was a PR opened to start working on single-node installs which had replicas=0.  This test will not work in that scenario.

**Comment by patrickdillon** [comment]
/hold cancel
Thanks for the explanation!

**Pull request merged**
