### PR TITLE
Configure a nightly job for SBO master test run on odo

### PR DESCRIPTION
**Pull request by prietyc123**
Fixes https://github.com/openshift/odo/issues/4942
Fixes https://github.com/openshift/odo/issues/4955

### CODE REVIEW

**Comment by prietyc123** [comment]
DO NOT MERGE IT Before https://github.com/openshift/odo/pull/4958

/hold

**Comment by prietyc123** [comment]
Rehearsal won't post any notification. Once it gets in we will get nightly job notification on `odo-notifications` channel.

**Comment by dharmit** [comment]
@prietyc123 I see that `ci/rehearse/periodic-ci-openshift-odo-main-v4.8-operatorhub-integration-nightly` is failing to execute `odo describe`. But the problem is before that when trying to restart the component:

```
✓  Created link "sbr-eoueom" using Service Binding Operator on the cluster; component will be restarted
[odo]  •  Restarting the component  ...
[odo]  ✗  Restarting the component [1m]
[odo]  ✗  Failed to start component with name "cmp-cnwcac". Error: Failed to create the component: timeout while waiting for "cmp-cnwcac-app-dcbdf66ff-tsg4z" pod to be deleted
Deleting project: cmd-link-test154urr 
```

What do you think about this error? Would our regular integration or nightly tests hit this?

**Comment by prietyc123** [comment]
> What do you think about this error? Would our regular integration or nightly tests hit this?

@dharmit This is the problem with our nightly test. We need to debug it for fix.

**Comment by prietyc123** [comment]
> > What do you think about this error? Would our regular integration or nightly tests hit this?
> 
> @dharmit This is the problem with our nightly test. We need to debug it for fix.

test pass successfully this time https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/20728/rehearse-20728-periodic-ci-openshift-odo-main-v4.8-operatorhub-integration-nightly/1423216119212150784#1:build-log.txt%3A505 

Errors being thrown by reporting file which might be platform issue

**Review by dharmit — APPROVED** [review]

**Pull request merged**
