### PR TITLE
use ci-operator for linter jobs in libvirt-actuator repo

### PR DESCRIPTION
**Pull request by paulfantom**
Propagated from #1460

/assign @ingvagabund @enxebre @spangenberg

### CODE REVIEW

**Comment by enxebre** [comment]
looks good to me, I'll let a second view to add the label

**Comment by paulfantom** [comment]
@ingvagabund @enxebre can I have LGTM again, it was just a rebase :)

**Comment by paulfantom** [comment]
File `openshift-cluster-api-provider-libvirt-master-presubmits.yaml` is now mostly autogenerated

**Pull request merged**
