### PR TITLE
Add fast-datapath-beta repos

### PR DESCRIPTION
**Pull request by dcbw**
see also https://github.com/openshift/ocp-build-data/pull/202

@squeed @knobunc @smarterclayton @jupierce @petr-muller

### CODE REVIEW

**Comment by squeed** [comment]
Is there any chance that we'll accidentally ship a production release with a beta package?

**Comment by dcbw** [comment]
@squeed yes that's a possibility. We'd likely want to turn this on/off when we get to a certain point, but we can do that through Dockerfile magic to disable this repo when we want to flip off the beta stuff. eg something like https://github.com/openshift/ovn-kubernetes/pull/49/files#diff-3254677a7917c6c01f55212f86c57fbfR28

**Comment by stevekuznetsov** [comment]
/hold

Depends on my pull migrating the repos to `core-services/`

**Comment by dcbw** [comment]
@stevekuznetsov PTAL thanks!

**Comment by dcbw** [comment]
@jupierce this one OK now? Thanks!

**Comment by tbielawa** [comment]
You should add this to the s390x and ppc64le repo files as well so components depending on these repos can still build under those arches.

**Comment by dcbw** [comment]
> You should add this to the s390x and ppc64le repo files as well so components depending on these repos can still build under those arches.

@tbielawa done, PTAL thanks!

**Comment by tbielawa** [comment]
> > You should add this to the s390x and ppc64le repo files as well so components depending on these repos can still build under those arches.
> 
> @tbielawa done, PTAL thanks!

/lgtm

**Pull request merged**
