### PR TITLE
Adding firewatch `success_rules` to ROSA Classic scenarios

### PR DESCRIPTION
**Pull request by Sau1506mya**
Link to JIRA: [LPTOCPCI-1168](https://issues.redhat.com/browse/LPTOCPCI-1168)

### CODE REVIEW

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-servicemesh-rosa-aws

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-oadp-qe-oadp-qe-automation-main-oadp1.3-ocp4.14-lp-rosa-classic-oadp-rosa-aws

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.14-lp-rosa-classic-mtc-interop-aws-rosa

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-oadp-qe-oadp-qe-automation-main-oadp1.3-ocp4.14-lp-rosa-classic-oadp-rosa-aws

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.14-lp-rosa-classic-servicemesh-rosa-aws

**Review by Simranpal — APPROVED** [review]
/lgtm

**Pull request merged**
