### PR TITLE
Add optional single-node e2e aws master presubmit to openshift/kubernetes

### PR DESCRIPTION
**Pull request by omertuc**
Needed for https://github.com/openshift/kubernetes/pull/755

### CODE REVIEW

**Comment by omertuc** [comment]
> @omertuc: The following tests **failed**, say `/retest` to rerun all failed tests:
> 
> Test name	Commit	Details	Rerun command
> ci/rehearse/openshift/kubernetes/master/e2e-aws-single-node	[b2bbf5f](https://github.com/openshift/release/commit/b2bbf5f0d0784485b9b1522f5eb97e7bb2a3cea7)	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/18694/rehearse-18694-pull-ci-openshift-kubernetes-master-e2e-aws-single-node/1395238644825985024)	`/test pj-rehearse`
> ci/prow/pj-rehearse	[b2bbf5f](https://github.com/openshift/release/commit/b2bbf5f0d0784485b9b1522f5eb97e7bb2a3cea7)	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/18694/pull-ci-openshift-release-master-pj-rehearse/1395238405176037376)	`/test pj-rehearse`
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openshift&repo=release&pr=18694). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:omertuc).

This rehearsal seems good enough, let's merge

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
