### PR TITLE
Fixing Jenkins quay.io mirroring for 4.11

### PR DESCRIPTION
**Pull request by coreydaley**

### CODE REVIEW

**Comment by bparees** [comment]
jenkins mirroring names are approved

/approve

**Comment by coreydaley** [comment]
@bparees I'm not sure how to get that mirroring job to get a clean run, when i run the recommended `make` command locally it removes the lines that I added. Any thoughts?

**Comment by coreydaley** [comment]
I am trying to fix the 4.11 image mirroring, as the images are not currently mirrored to quay.io, but all of the rest of the versions are ..

**Comment by bparees** [comment]
you need to turn on promotion for 4.11.  see:
https://github.com/openshift/release/blob/ebc09e4809a44e38593d9205603a55ae94e061d0/ci-operator/config/openshift/jenkins/openshift-jenkins-release-4.10.yaml#L55-L57

there's no promotion stanza in the 4.11 file.

**Comment by coreydaley** [comment]
@bparees I have updated the config, ptal.

**Pull request merged**
