### PR TITLE
Add hypershift e2e job for CAPI and CAPA

### PR DESCRIPTION
**Pull request by enxebre**
Ref https://issues.redhat.com/browse/HOSTEDCP-846

### CODE REVIEW

**Comment by enxebre** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-master-e2e-hypershift
/pj-rehearse pull-ci-openshift-cluster-api-provider-aws-e2e-hypershift

**Review by damdo — COMMENTED** [review]
/lgtm

**Comment by enxebre** [comment]
Seems Nodes didn't go ready https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_rele[…]es/core/nodes/ip-10-0-138-152.ec2.internal.yaml
```
  - lastHeartbeatTime: "2023-02-27T10:21:30Z"
    lastTransitionTime: "2023-02-27T09:59:54Z"
    message: 'container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady
      message:Network plugin returns error: No CNI configuration file in /etc/kubernetes/cni/net.d/.
      Has your network provider started?'
    reason: KubeletNotReady
    status: "False"
    type: Ready
```

Not sure why Machines report running https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_rele[…]s/example-4rgv4-us-east-1a-f57d5b758-qcgjh.yaml
Something wrong with the CNO https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_rele[…]tor-d78db46f-2k5fh-cluster-network-operator.log
```
- lastTransitionTime: "2023-02-27T09:54:23Z"
  message: 'Error while updating operator configuration: could not apply (apps/v1,
    Kind=DaemonSet) openshift-ovn-kubernetes/ovnkube-node: failed to apply / update
    (apps/v1, Kind=DaemonSet) openshift-ovn-kubernetes/ovnkube-node: DaemonSet.apps
    "ovnkube-node" is invalid: [spec.template.spec.containers[0].image: Required value,
    spec.template.spec.containers[1].image: Required value, spec.template.spec.containers[4].image:
    Required value, spec.template.spec.initContainers[0].image: Required value]'
  reason: ApplyOperatorConfig
  status: "True"
  type: network.operator.openshift.io/Degraded
```
I'll retest to gather more data then troubleshoot.

/pj-rehearse pull-ci-openshift-cluster-api-master-e2e-hypershift

**Comment by enxebre** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-aws-master-e2e-hypershift

**Comment by bryan-cox** [comment]
Rerunning the tests. They should pass now that https://github.com/openshift/hypershift/pull/2230 has merged. 

/pj-rehearse pull-ci-openshift-cluster-api-provider-aws-master-e2e-hypershift

**Comment by damdo** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-aws-master-e2e-hypershift

**Comment by enxebre** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-master-e2e-hypershift

**Comment by damdo** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-aws-master-e2e-hypershift

**Comment by enxebre** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-master-e2e-hypershift

**Comment by enxebre** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-aws-master-e2e-hypershift

**Comment by enxebre** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-master-e2e-hypershift

**Comment by damdo** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-master-e2e-hypershift

**Comment by damdo** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-aws-master-e2e-hypershift

**Comment by damdo** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-master-e2e-hypershift

**Comment by enxebre** [comment]
Expectation is to go green now that presubmits are passing https://github.com/openshift/hypershift/pull/2239

/pj-rehearse pull-ci-openshift-cluster-api-provider-aws-master-e2e-hypershift
/pj-rehearse pull-ci-openshift-cluster-api-master-e2e-hypershift

**Comment by damdo** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-aws-master-e2e-hypershift
/pj-rehearse pull-ci-openshift-cluster-api-master-e2e-hypershift

**Comment by damdo** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-master-e2e-hypershift

**Comment by damdo** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-aws-master-e2e-hypershift

**Comment by damdo** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-master-e2e-hypershift

**Comment by damdo** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-master-e2e-hypershift

**Comment by enxebre** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-master-e2e-hypershift

**Review by damdo — COMMENTED** [review]
/lgtm

**Pull request merged**
