### PR TITLE
exclude OCP4.5 testcases having docker pull rate limit issues

### PR DESCRIPTION
**Pull request by vijay-vin**
Signed-off-by: Vijay Vinnakota <vijay.vinnakota@ibm.com>

The following testcases will temporarily skipped until the docker pull rate limit issue is fixed in OCP 4.6, Power architecture.

1. "[sig-instrumentation][Late] Alerts shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured [Suite:openshift/conformance/parallel]"
2.             "[sig-imageregistry][Feature:ImageLayers] Image layer subresource should return layers from tagged images [Suite:openshift/conformance/parallel]"
3.             "[sig-imageregistry][Feature:Image] oc tag should change image reference for internal images [Suite:openshift/conformance/parallel]"
4.             "[sig-network][Feature:Router] The HAProxy router should enable openshift-monitoring to pull metrics [Suite:openshift/conformance/parallel]"
5.             "[sig-imageregistry][Feature:Image] oc tag should work when only imagestreams api is available [Suite:openshift/conformance/parallel]"
6.             "[sig-instrumentation][sig-builds][Feature:Builds] Prometheus when installed on the cluster should start and expose a secured proxy and verify build metrics [Suite:openshift/conformance/parallel]"
7.             "[sig-instrumentation] Prometheus when installed on the cluster should have non-Pod host cAdvisor metrics [Suite:openshift/conformance/parallel]"
8.             "[sig-builds][Feature:Builds] Multi-stage image builds should succeed [Suite:openshift/conformance/parallel]"
9.             "[sig-builds][Feature:Builds][valueFrom] process valueFrom in build strategy environment variables should successfully resolve valueFrom in docker build environment variables [Suite:openshift/conformance/parallel]"
10.             "[sig-cli] oc rsh rsh specific flags should work well when access to a remote shell [Suite:openshift/conformance/parallel]"
11.             "[sig-instrumentation] Prometheus when installed on the cluster should have a AlertmanagerReceiversNotConfigured alert in firing state [Suite:openshift/conformance/parallel]"
12.             "[sig-cli] Kubectl client Kubectl copy should copy a file from a running Pod [Suite:openshift/conformance/parallel] [Suite:k8s]"
13.             "[sig-imageregistry][Feature:ImageLookup] Image policy should perform lookup when the object has the resolve-names annotation [Suite:openshift/conformance/parallel]"
14.             "[sig-instrumentation] Prometheus when installed on the cluster should provide ingress metrics [Suite:openshift/conformance/parallel]"
15.             "[sig-apps][Feature:Jobs] Users should be able to create and run a job in a user project [Suite:openshift/conformance/parallel]"
16.             "[sig-builds][Feature:Builds] Optimized image builds should succeed [Suite:openshift/conformance/parallel]"
17.             "[sig-instrumentation] Prometheus when installed on the cluster should start and expose a secured proxy and unsecured metrics [Suite:openshift/conformance/parallel]"
18.             "[sig-imageregistry][Feature:ImageLookup] Image policy should perform lookup when the Deployment gets the resolve-names annotation later [Suite:openshift/conformance/parallel]"
19.             "[sig-instrumentation] Prometheus when installed on the cluster shouldn't have failing rules evaluation [Suite:openshift/conformance/parallel]"
20.             "[sig-instrumentation] Prometheus when installed on the cluster when using openshift-sdn should be able to get the sdn ovs flows [Suite:openshift/conformance/parallel]"
21.             "[sig-instrumentation] Prometheus when installed on the cluster shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured [Early] [Suite:openshift/conformance/parallel]"
22.             "[sig-instrumentation][Late] Alerts shouldn't exceed the 500 series limit of total series sent via telemetry from each cluster [Suite:openshift/conformance/parallel]"
23.             "[sig-imageregistry][Feature:ImageLookup] Image policy should update standard Kube object image fields when local names are on [Suite:openshift/conformance/parallel]"
24.             "[sig-instrumentation][Late] Alerts should have a Watchdog alert in firing state the entire cluster run [Suite:openshift/conformance/parallel]"
25.             "[sig-imageregistry][Feature:ImageTriggers] Annotation trigger reconciles after the image is overwritten [Suite:openshift/conformance/parallel]"
26.             "[sig-instrumentation] Prometheus when installed on the cluster should report telemetry if a cloud.openshift.com token is present [Suite:openshift/conformance/parallel]"
27.             "[sig-network][Feature:Router] The HAProxy router should support reencrypt to services backed by a serving certificate automatically [Suite:openshift/conformance/parallel]"
28.             "[sig-cli] oc adm must-gather runs successfully with options [Suite:openshift/conformance/parallel]"
29.             "[sig-builds][Feature:Builds] prune builds based on settings in the buildconfig should prune completed builds based on the successfulBuildsHistoryLimit setting [Suite:openshift/conformance/parallel]"
30.             "[sig-imageregistry][Feature:ImageInfo] Image info should display information about images [Suite:openshift/conformance/parallel]"
31.             "[sig-imageregistry][Feature:Image] oc tag should preserve image reference for external images [Suite:openshift/conformance/parallel]"

### CODE REVIEW

**Comment by vijay-vin** [comment]
hmm.  Something is wrong, I see "error: failed to connect to the hypervisor " in the build log. Will try retest.

**Comment by vijay-vin** [comment]
I am seeing more testcases with docker pull rate limit errors. 

1. [sig-arch][Early] Managed cluster should start all core operators [Suite:openshift/conformance/parallel]
2. [sig-builds][Feature:Builds] Multi-stage image builds  should succeed [Suite:openshift/conformance/parallel]
3. [sig-builds][Feature:Builds] Optimized image builds  should succeed [Suite:openshift/conformance/parallel]
4. [sig-builds][Feature:Builds] prune builds based on settings in the buildconfig  should prune completed builds based on the successfulBuildsHistoryLimit setting [Suite:openshift/conformance/parallel]
5. [sig-builds][Feature:Builds][valueFrom] process valueFrom in build strategy environment variables  should successfully resolve valueFrom in docker build environment variables [Suite:openshift/conformance/parallel]

**Comment by vijay-vin** [comment]
The last PR retest, I have 4 testcases failed because of the docker pull rate errors.  I will try to run one more time and see.

1. [sig-builds][Feature:Builds] Multi-stage image builds  should succeed [Suite:openshift/conformance/parallel]
2. [sig-builds][Feature:Builds] Optimized image builds  should succeed [Suite:openshift/conformance/parallel]
3. [sig-builds][Feature:Builds] prune builds based on settings in the buildconfig  should prune completed builds based on the successfulBuildsHistoryLimit setting [Suite:openshift/conformance/parallel]
4. [sig-builds][Feature:Builds][valueFrom] process valueFrom in build strategy environment variables  should successfully resolve valueFrom in docker build environment variables [Suite:openshift/conformance/parallel]

**Comment by vijay-vin** [comment]
the tests did not run. Will try retest again

**Comment by vijay-vin** [comment]
Bastion and tunnel issues fixed. Going to retry now

**Comment by deepsm007** [comment]
sshd-bastion is updated with SNI changes

/retest

**Comment by vijay-vin** [comment]
tunnel restarted. Going to retest now.

**Comment by vijay-vin** [comment]
I have the same set of 4 more testcases that failed again with docker pull rate limit error.  So, I am going to add them exclude list. I will push the changes again.

**Comment by vijay-vin** [comment]
@deepsm007 can you approve it for merge. The PR job succeeded.

**Pull request merged**
