### PR TITLE
Sync Serverless CI config/

### PR DESCRIPTION
**Pull request by serverless-qe**

### CODE REVIEW

**Comment by mgencur** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-release-v1.15-416-images

Just to see the CI image replacement

**Comment by mgencur** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-release-v1.15-416-images

**Comment by maschmid** [comment]
/pj-rehearse periodic-ci-openshift-knative-serverless-operator-main-415-single-node-e2e-sno-continuous periodic-ci-openshift-knative-serverless-operator-main-415-hypershift-e2e-hypershift-continuous periodic-ci-openshift-knative-serverless-operator-main-415-osd-e2e-osd-continuous

**Comment by mgencur** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-release-v1.15-416-images

**Comment by aliok** [comment]
/lgtm
/approve

merging it?

**Pull request merged**
