### PR TITLE
Add cluster-svcat-apiserver-operator

### PR DESCRIPTION
**Pull request by jwforres**

### CODE REVIEW

**Comment by jwforres** [comment]
cc @jboyd01

**Comment by petr-muller** [comment]
/approve
/lgtm
/hold

The config looks sane, although the `unit` test job would be currently failing on your master branch `HEAD` (see the `ci/rehearse/openshift/cluster-svcat-apiserver-operator/master/unit` result). This does not block the merge here. Unhold at will.

**Comment by jboyd01** [comment]
unit tests pass, removing the hold.
/hold cancel

**Pull request merged**
