### PR TITLE
WINC-1320: [winc] Remove old images from mirror list

### PR DESCRIPTION
**Pull request by saifshaikh48**
Remove k8s.grc.io/sig-storage/csi-node-driver-registrar to move away from frozen repo. Also removed old liveness probe image, unused in WMCO repo.

Follow-up to https://github.com/openshift/release/pull/54788

### CODE REVIEW

**Comment by saifshaikh48** [comment]
/hold

until https://github.com/openshift/windows-machine-config-operator/pull/2286 goes in

**Comment by saifshaikh48** [comment]
/close

Realized removing the other images would break older WMCO branches

**Comment by saifshaikh48** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-vsphere-disconnected-e2e-operator

will need to test the 4.16 and 4.17 jobs once the backports (https://github.com/openshift/windows-machine-config-operator/pull/2352 + https://github.com/openshift/windows-machine-config-operator/pull/2353) land

**Comment by saifshaikh48** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-vsphere-disconnected-e2e-operator

**Comment by saifshaikh48** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.17-vsphere-disconnected-e2e-operator pull-ci-openshift-windows-machine-config-operator-release-4.16-vsphere-disconnected-e2e-operator

**Comment by saifshaikh48** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.16-vsphere-disconnected-e2e-operator

retesting

**Review by jrvaldes — APPROVED** [review]
/lgtm

**Comment by saifshaikh48** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-vsphere-disconnected-e2e-operator

running this again, not sure why it passed last run but the other branches didn't

**Comment by saifshaikh48** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-vsphere-disconnected-e2e-operator pull-ci-openshift-windows-machine-config-operator-master-release-4.17-disconnected-e2e-operator pull-ci-openshift-windows-machine-config-operator-master-release-4.16-disconnected-e2e-operator

**Comment by saifshaikh48** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.17-vsphere-disconnected-e2e-operator pull-ci-openshift-windows-machine-config-operator-release-4.16-vsphere-disconnected-e2e-operator

**Comment by saifshaikh48** [comment]
issues in QE mirror steps are resolved. One of the rehearsals is hitting infra quota but others look good
```
INFO Acquiring leases for test vsphere-disconnected-e2e-operator: [vsphere-dis-2-quota-slice vsphere-connected-2-quota-slice] 
ERRO error: Failed to acquire resource, current capacity: 0 free, 6 leased 
INFO  Ran for 2h22m51s                             
```

**Comment by saifshaikh48** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.17-vsphere-disconnected-e2e-operator

**Pull request merged**
