### PR TITLE
Fix assisted operator upgrade tests

### PR DESCRIPTION
**Pull request by carbonin**
Set the correct env var for assisted operator upgrade test and correct the `CHANNEL_INSTALL_OVERRIDE` value.

The scripts in assisted-service are looking for an env var called `CHANNEL`, but we were only setting `CHANNEL_INSTALL_OVERRIDE` in our script so just set one to the other before sourceing the script from assisted-service

Also, the `CHANNEL_INSTALL_OVERRIDE` value should always be the immediately previous version from the version we're testing.

cc @eliorerz @osherdp 
https://issues.redhat.com/browse/MGMT-9532

### CODE REVIEW

**Comment by carbonin** [comment]
/hold

Need to wait on some PRs in assisted-service and also want to see if the rehearse jobs pass.

**Review by filanov — APPROVED** [review]

**Comment by carbonin** [comment]
/hold

Need tests to pass.

**Comment by carbonin** [comment]
:scream: wow alright then.

/unhold

**Comment by osherdp** [comment]
@carbonin should that other spoke not get to "installed" state?
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/27293/rehearse-27293-periodic-ci-openshift-assisted-service-master-e2e-metal-assisted-operator-ztp-periodic-upgrade/1508872775345901568/artifacts/e2e-metal-assisted-operator-ztp-periodic-upgrade/assisted-baremetal-operator-gather/artifacts/assisted-spoke-cluster_assisted-agent-cluster-install-upgraded/agentclusterinstall.yaml

**Comment by carbonin** [comment]
Honestly didn't look into it last night. Just saw that it passed.
Will take a closer look today.

**Comment by carbonin** [comment]
@osherdp based on https://github.com/openshift/assisted-service/blob/7b43bbd4c5eccf273205f2fbdcab04f9335da358/deploy/operator/upgrade/after_upgrade.sh#L3 it looks like the test intentionally doesn't wait for the cluster to install after upgrade.

For comparison this value is set here before the upgrade https://github.com/openshift/assisted-service/blob/7b43bbd4c5eccf273205f2fbdcab04f9335da358/deploy/operator/upgrade/before_upgrade.sh#L3.

It is used in this script here: https://github.com/openshift/assisted-service/blob/7b43bbd4c5eccf273205f2fbdcab04f9335da358/deploy/operator/ztp/deploy_spoke_cluster.sh#L100-L103

**Comment by carbonin** [comment]
It's still unclear to me how useful this behavior is, but I think it's better to get the test green first given that it seems rather simple to do. Then we can decide if this test is worth keeping around in the same form.

**Comment by osherdp** [comment]
yes, makes sense
not sure though what's up with tide here
/retest
/refresh

**Comment by osherdp** [comment]
/retest
before calling the cops

**Pull request merged**
