### PR TITLE
Set the performance profile name for the upgrade test

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
CPU load balancing issues should be fixed by https://github.com/openshift-kni/performance-addon-operators/pull/470

**Comment by fromanirh** [comment]
/lgtm
/hold
in case other reviewers wants to chime in

**Comment by fromanirh** [comment]
/hold cancel
we want to unbreak CI so we decided to move forward at accelerated speed

**Pull request merged**
