### PR TITLE
No need to set compute_node_type in arm64 jobs anymore

### PR DESCRIPTION
**Pull request by aleskandro**
Hi @deepsm007, as of #32969, for the arm64 arch, the default node types for AWS IPI are set to `m6g.xlarge` when the cluster architecture (or the cluster profile) is `arm64`.

Would you check in this PR to remove it from the CI jobs?

/cc @deepsm007

### CODE REVIEW

**Comment by aleskandro** [comment]
/hold 
until #31965 is merged to avoid rebasing it

**Comment by aleskandro** [comment]
Hi @deepsm007 we'd be able to merge this now.

**Comment by aleskandro** [comment]
Thanks @deepsm007 as there are some failures, could you double confirm that they are not related to the changes introduced by this PR?

**Comment by deepsm007** [comment]
/unhold
The failing tests are known issues not related to PR changes, alerts for KubeApiBudgetBurn and events should not repeat pathological

**Review by deepsm007 — APPROVED** [review]

**Pull request merged**
