### PR TITLE
kni: scheduler-plugin: branch out 4.18 and point main to 4.19

### PR DESCRIPTION
**Pull request by shajmakh**
Create 4.18 relevant config and jobs and redirect main to 4.19.

### CODE REVIEW

**Review by ffromani — COMMENTED** [review]
/approve
/lgtm

**Comment by shajmakh** [comment]
needs https://github.com/openshift-kni/scheduler-plugins/pull/233

**Comment by ffromani** [comment]
/pj-rehearse pull-ci-openshift-kni-scheduler-plugins-release-4.18-security

**Comment by ffromani** [comment]
/pj-rehearse pull-ci-openshift-kni-scheduler-plugins-master-security

**Comment by ffromani** [comment]
/pj-rehearse ack

(Xref: https://github.com/openshift/release/pull/59695#issuecomment-2531386839)

**Pull request merged**
