### PR TITLE
Fix skip test list

### PR DESCRIPTION
**Pull request by mkumatag**
Part of https://github.com/openshift/origin/pull/24829 there are a bunch of testcases got modified with the additional tag `[Skipped:ibmcloud]`, this PR to fix the exclude test with the modified testcase list

skipping one more test which is failing because of the existing bug

### CODE REVIEW

**Comment by hamzy** [comment]
@mkumatag openstack-ppc64le was breaking because of https://coreos.slack.com/archives/CBN38N3MW/p1589896190317800

**Comment by petr-muller** [comment]
I will approve this to allow merge, but I would like someone who knows what should run on `ibmcloud` to `/lgtm` it, because I have no way how to check if these changes are desirable.

/approve

**Comment by manojnkumar** [comment]
/lgtm
The ones tagged ibmcloud seem to be gluster related, and we do not support gluster with OpenShift v4 on ppc64le (not sure about other arches).

**Pull request merged**
