### PR TITLE
Improving structure of ocp-qe-scale-ci tests

### PR DESCRIPTION
**Pull request by mffiedler**
Improving structure of ocp-qe-scale-ci config and jobs for versioning and making them more consistent with cucushift and verification-tests.

### CODE REVIEW

**Comment by mffiedler** [comment]
@paigerube14  @qiliRedHat Using this PR to do a small restructure and re-familiarize

**Comment by paigerube14** [comment]
Have a very similar PR and hitting the same 2 tests failing: https://github.com/openshift/release/pull/27749

**Pull request merged**
