### PR TITLE
ABI Unconfigured ephemeral installer + Install configuration image

### PR DESCRIPTION
**Pull request by bmanzari**
Implements https://issues.redhat.com/browse/AGENT-574 and https://issues.redhat.com/browse/AGENT-559

### CODE REVIEW

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-ephe-compact-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by jhou1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-ephe-sno-agent-ipv4-static-connected-p1-f14

**Comment by bmanzari** [comment]
@jhou1 please re-lgtm thanks

**Comment by jhou1** [comment]
To add lgtm, can we squash the commits?

**Pull request merged**
