### PR TITLE
add ignore list to presubmit job for terraform-provider

### PR DESCRIPTION
**Pull request by amalykhi**

### CODE REVIEW

**Comment by amalykhi** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-v1.4.0-branch-rosa-sts-advanced-critical-high-presubmit
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-critical-high-presubmit
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-critical-high-f3
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-private-critical-high-f3
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-private-critical-high-presubmit
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-v1.4.0-branch-rosa-sts-private-critical-high-presubmit
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-managed-oidc-config-e2e-periodic

**Comment by amalykhi** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-v1.4.0-branch-rosa-sts-advanced-critical-high-presubmit
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-critical-high-presubmit
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-critical-high-f3
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-private-critical-high-f3
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-private-critical-high-presubmit
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-v1.4.0-branch-rosa-sts-private-critical-high-presubmit
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-managed-oidc-config-e2e-periodic

**Comment by amalykhi** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-critical-high-presubmit

**Comment by amalykhi** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-private-critical-high-presubmit

**Comment by amalykhi** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-v1.4.0-branch-rosa-sts-advanced-critical-high-presubmit

**Comment by amalykhi** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-v1.4.0-branch-rosa-sts-private-critical-high-presubmit

**Comment by amalykhi** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-critical-high-f3

**Comment by amalykhi** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-v1.4.0-branch-rosa-sts-advanced-critical-high-presubmit

**Comment by amalykhi** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-v1.4.0-branch-rosa-sts-advanced-critical-high-presubmit

**Comment by amalykhi** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-v1.4.0-branch-rosa-sts-advanced-critical-high-presubmit

**Comment by amalykhi** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-v1.4.0-branch-rosa-sts-advanced-critical-high-presubmit

**Comment by amalykhi** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-v1.4.0-branch-rosa-sts-advanced-critical-high-presubmit
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-critical-high-f3
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-private-critical-high-f3

**Comment by amalykhi** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-v1.4.0-branch-rosa-sts-advanced-critical-high-presubmit

**Comment by AsherShoshan** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-critical-high-f3
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-private-critical-high-f3
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-v1.4.0-branch-rosa-sts-advanced-critical-high-presubmit

**Comment by AsherShoshan** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-v1.4.0-branch-rosa-sts-advanced-critical-high-presubmit

**Comment by amalykhi** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-provider-rhcs-v1.4.0-branch-rosa-sts-advanced-critical-high-presubmit

**Pull request closed without merging**
