### PR TITLE
Re-enable QE Test Jobs

### PR DESCRIPTION
**Pull request by jhou1**
/assign @liangxia 

Reenable the GCP 4.10 job. Setting `BUSHSLICER_LOG_LEVEL` to `INFO` and soft linking `kubectl`. PTAL

### CODE REVIEW

**Comment by liangxia** [comment]
LGTM
/hold
so we can check the logs in detail.

**Comment by jhou1** [comment]
@liangxia This PR is ready, can you please review? Thanks

**Pull request merged**
