### PR TITLE
Add 4.3 to 4.12 upgrade on Azure

### PR DESCRIPTION
**Pull request by shellyyang1989**
Closes [OCPQE-12661](https://issues.redhat.com/browse/OCPQE-12661)

### CODE REVIEW

**Comment by shellyyang1989** [comment]
The install failed twice due to the issue. Maybe we need to consider to change a platform.

```
level=error msg="Cluster operator monitoring Degraded is True with UpdatingPrometheusK8SFailed: Failed to rollout the stack. Error: running task Updating Prometheus-k8s failed: reconciling Prometheus object failed: creating Prometheus object failed: Prometheus.monitoring.coreos.com \"k8s\" is invalid: spec.storage.volumeClaimTemplate.metadata.creationTimestamp: Invalid value: \"null\": spec.storage.volumeClaimTemplate.metadata.creationTimestamp in body must be of type string: \"null\""
level=fatal msg="failed to initialize the cluster: Cluster operator monitoring is still updating"
```

**Comment by shellyyang1989** [comment]
Hi @jianlinliu @gpei I heard that the issue is caused by `- ref: ipi-install-monitoringpvc`. I'm considering removing the step from 4.3 to 4.12 upgrade job. Would there be any side effects if we get rid of it? cc @JianLi-RH @juzhao 

```
level=error msg="Cluster operator monitoring Degraded is True with UpdatingPrometheusK8SFailed: Failed to rollout the stack. Error: running task Updating Prometheus-k8s failed: reconciling Prometheus object failed: creating Prometheus object failed: Prometheus.monitoring.coreos.com \"k8s\" is invalid: spec.storage.volumeClaimTemplate.metadata.creationTimestamp: Invalid value: \"null\": spec.storage.volumeClaimTemplate.metadata.creationTimestamp in body must be of type string: \"null\""
level=fatal msg="failed to initialize the cluster: Cluster operator monitoring is still updating"
```

**Comment by juzhao** [comment]
if developers allow the PR[1] merged to 4.3, then no need to remove `- ref: ipi-install-monitoringpvc`
otherwise we can remove it, the step attached PVs for monitoring, which is not the same for a default cluster(it requires user to configure PVs after the cluster is ready)

[1] https://github.com/openshift/cluster-monitoring-operator/pull/1810

**Comment by shellyyang1989** [comment]
Thanks @juzhao for the confirmation! I'm afraid we would not have new 4.3 release built because it's EOL. Let me remove the step `- ref: ipi-install-monitoringpvc`.

**Comment by juzhao** [comment]
> Thanks @juzhao for the confirmation! I'm afraid we would not have new 4.3 release built because it's EOL. Let me remove the step `- ref: ipi-install-monitoringpvc`.

yes, we only support 4.6+ versions

**Comment by shellyyang1989** [comment]
@juzhao The test purpose is upgrading from 4.3 to latest.

**Comment by juzhao** [comment]
@shellyyang1989 
see from https://coreos.slack.com/archives/G79AW9Q7R/p1667530416192859
since 4.3 is EOF, we can not merge openshift/cluster-monitoring-operator#1810 to 4.3, remove ipi-install-monitoringpvc step seems the right solution

**Comment by gpei** [comment]
@shellyyang1989 seems Junqi already pointed out the cause of the monitoring Degraded issue, actually the `ipi-install-monitoringpvc` failure we talked last week is about: when "storage" operator was disabled, we need to remove this step from the related chain, not like this one.
BTW, I remember we have a CCO bug that blocks fresh install on GCP which version is < 4.6, but I see the install is indeed passed in the rehearse, this is a little confusing...
```
INFO[2022-11-04T11:02:16Z] Step phase pre succeeded after 26m20s.       
```

**Comment by shellyyang1989** [comment]
> CCO

Thanks @gpei . Right, we have [Bug 2022840](https://bugzilla.redhat.com/show_bug.cgi?id=2022840). Seems like 4.4/4.5 install would be affected.

**Comment by shellyyang1989** [comment]
The [test](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/33715/rehearse-33715-periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-4.12-upgrade-from-stable-4.3-azure-ipi/1590724414477963264) passed. 

It's ready for your review and merge. Thanks! cc @liangxia @xingxingxia @jhou1

**Pull request merged**
