### PR TITLE
Move some platform agnostic e2e jobs from gcp to azure

### PR DESCRIPTION
**Pull request by petr-muller**

### CODE REVIEW

**Comment by petr-muller** [comment]
/hold

Will conflict with https://github.com/openshift/release/pull/17984, I will rebase after it merges.

**Comment by petr-muller** [comment]
/hold

Mmnt, I made a mistake

**Review by wking — APPROVED** [review]
On a quick skim through the failed rehearsals, none of them looked obviously Azure-specific.

/lgtm

**Pull request merged**
