### PR TITLE
use new test_branch func from ci-artifacts

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by jmencak** [comment]
Reminds me of https://github.com/openshift/release/pull/24661 .  Perhaps you want to do this for all of our operators or collaborate on the original PR?  I don't mind either way.

**Comment by ArangoGutierrez** [comment]
once  #24661 is merged I will rebase
/hold

**Comment by ArangoGutierrez** [comment]
if test pass we are ready @kpouget @jmencak

**Pull request merged**
