### PR TITLE
Update OWNERS of openshift-pipelines/performance

### PR DESCRIPTION
**Pull request by vdemeester**
Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

### CODE REVIEW

**Review by jhutar — APPROVED** [review]
/lgtm
/approve

**Comment by vdemeester** [comment]
Ah there is a bot the automatically sync the OWNERS with the "targeted" repository, so all those files are already up-to-date (see https://github.com/openshift/release/blob/master/ci-operator/config/openshift-pipelines/performance/OWNERS).

I'll close that one then.

**Pull request closed without merging**
