### PR TITLE
ARMOCP-563 add 4.15 gcp for arm64

### PR DESCRIPTION
**Pull request by jeffdyoung**
similar to https://github.com/openshift/release/pull/43103, but for 4.15

### CODE REVIEW

**Comment by jeffdyoung** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.15-ocp-e2e-gcp-ovn-arm64

**Comment by Prashanth684** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.15-ocp-e2e-gcp-ovn-arm64

**Review by bradmwilliams — APPROVED** [review]

**Pull request merged**
