### PR TITLE
capture e2e-aws-operator test results

### PR DESCRIPTION
**Pull request by sanchezl**
The operator e2e test results were not being captured.

### CODE REVIEW

**Comment by deads2k** [comment]
@sanchezl broken?

/retest

**Comment by sanchezl** [comment]
@deads2k the [release-4.3 rehearse jobs are borked](https://prow.svc.ci.openshift.org/?job=rehearse*4.3*) with `error: unable to create a release: operator "cluster-network-operator" contained an invalid image-references file: no input image tag named "container-networking-plugins"`. @stevekuznetsov is aware.

**Pull request merged**
