### PR TITLE
Knative build (core) images for 0.4

### PR DESCRIPTION
**Pull request by vdemeester**
Same as https://github.com/openshift/release/pull/3307 for knative/build

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

### CODE REVIEW

**Comment by markusthoemmes** [comment]
The images referenced here are not available for mirroring. Please make a PR pass against your release branch and merge it to make sure the postsubmit tests run through.

**Comment by vdemeester** [comment]
@markusthoemmes https://github.com/openshift/knative-build/pull/34 :pray: :angel:

**Comment by matzew** [comment]
@vdemeester I marked mine as WIP - until I had actual images

**Comment by vdemeester** [comment]
@matzew @markusthoemmes images are now available :dancer:

**Comment by matzew** [comment]
this is replaced by: https://github.com/openshift/release/pull/3354

**Pull request closed without merging**
