### PR TITLE
[4.17 stable] 'arm64-latest' and 'latest'

### PR DESCRIPTION
**Pull request by jianli-wei**
debug the failures
- [periodic-ci-openshift-openshift-tests-private-release-4.17-multi-nightly-4.17-upgrade-from-stable-4.17-gcp-ipi-xpn-oidc-arm-f60 #1834479970013941760](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.17-multi-nightly-4.17-upgrade-from-stable-4.17-gcp-ipi-xpn-oidc-arm-f60/1834479970013941760)
- [periodic-ci-openshift-openshift-tests-private-release-4.17-arm64-nightly-4.17-upgrade-from-stable-4.17-gcp-ipi-disc-priv-oidc-f60 #1833693780490850304](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.17-arm64-nightly-4.17-upgrade-from-stable-4.17-gcp-ipi-disc-priv-oidc-f60/1833693780490850304)

### CODE REVIEW

**Comment by jianli-wei** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-multi-nightly-4.17-upgrade-from-stable-4.17-gcp-ipi-xpn-oidc-arm-f60

**Comment by jianli-wei** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-arm64-nightly-4.17-upgrade-from-stable-4.17-gcp-ipi-disc-priv-oidc-f60

**Comment by jianli-wei** [comment]
@jianzhangbjz could you help review? it seems I could not trigger rehearsal test, thanks!

**Comment by jianli-wei** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-multi-nightly-4.17-upgrade-from-stable-4.17-gcp-ipi-xpn-oidc-arm-f60

**Comment by jianli-wei** [comment]
@Xia-Zhao-rh @bandrade Could you please help review, as Jian Zhang is on PTO? Thanks in advance!

**Comment by jianzhangbjz** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-multi-nightly-4.17-upgrade-from-stable-4.17-gcp-ipi-xpn-oidc-arm-f60

**Comment by jianzhangbjz** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-arm64-nightly-4.17-upgrade-from-stable-4.17-gcp-ipi-disc-priv-oidc-f60

**Pull request closed without merging**
