### PR TITLE
Strict CI job cloud platform locality (balanced) part 1

### PR DESCRIPTION
**Pull request by jmguzik**
Conditions applied:

-  `openshift-priv` jobs not taken under consideration (see https://github.com/openshift/release/pull/31764 PR), I assumed they are not executed so frequently so excluded them to the separate PR
- balancing algorithm, that limits number of moved jobs (not all are rebalanced in this PR)
- release controller jobs excluded by using criteria: `!(strings.Contains(jobBase.Name, "release-openshift") || strings.Contains(jobBase.Name, "release-master") || strings.Contains(jobBase.Name, "-aggregator"))` => that resulted in excluding everything from: `ci-operator/jobs/openshift/release/` (@jupierce could you confirm the condition is ok?)

Today's job assignments:
```
build01 19775
build02 8345
build03 10297
build04 3926
build05 1830
```
Target distribution (with `openshift-priv`):
```
build01 17179
build02 7517
build03 10450
build04 4454
build05 4573
```
Target (without `openshift-priv`):
```
build01 20797
build02 7170
build03 9280
build04 3910
build05 3081
```
Without any algorithm jobs will be moved like this:
```
[b01  b02   b03    b04 b05]
[987 -1177 -1045 -16 1251]
```
After applying algo (~max deviation):
```
[b01  b02   b03 b04 b05]
[218 -599   89   41   251]
```
Out of around 4800 possible changes in this PR was made 2425 which is around 50% for the start (~30% with `openshift-priv`).

/cc @jupierce @bear-redhat 

**IMPORTANT:** In order to merge this I would need to temporarily change a tool to add ignore the option if the jobs are strictly determined but the feature is not enabled. Let me know if we want to have gradual enablement like this.

Signed-off-by: Jakub Guzik <jguzik@redhat.com>

### CODE REVIEW

**Comment by jmguzik** [comment]
Of course I made assumption that one job equals the other when speaking about load of the system, which is probably not true.

**Comment by jupierce** [comment]
@jmguzik I recalled today that this feature was added to the release controller last year: https://github.com/openshift/release-controller/pull/307 . So the release controller will override our config for most build farms. I believe this means we are safe to remove release controller specific logic from your balancing logic.
cc @bradmwilliams

**Comment by jmguzik** [comment]
/hold
and wait for flag

**Comment by jmguzik** [comment]
> @jmguzik I recalled today that this feature was added to the release controller last year: [openshift/release-controller#307](https://github.com/openshift/release-controller/pull/307) . So the release controller will override our config for most build farms. I believe this means we are safe to remove release controller specific logic from your balancing logic.

@jupierce sure, no problem. Anyway, I am adding right now the flag to support manual (gradual) colocation so it won't have any effect, at least right now.
BTW the flag will work as follows: if the cluster is assigned according to old logic, leave it like it is, if it's assigned according to new colocation logic, do not change it and allow that.

I think we can remove my temp flag once we merge all colocation PRs. I feel the 3rd one (all the rest) will be the most disruptive.

**Pull request merged**
