### PR TITLE
chore: update test runner base image to go v1.21

### PR DESCRIPTION
**Pull request by psturc**
changes in [RELEASE-230](https://issues.redhat.com//browse/RELEASE-230) require an upgrade to go v1.21

### CODE REVIEW

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e

**Review by happybhati — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
