### PR TITLE
Try e2e tests in rollback

### PR DESCRIPTION
**Pull request by shellyyang1989**
PM is interested in how e2e broken in rollback.

### CODE REVIEW

**Comment by shellyyang1989** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-azure-upi-f7 periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-baremetal-ipi-ovn-ipv4-f7 periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-gcp-ipi-ovn-ipsec-f7 periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-ibmcloud-ipi-f7 periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-nutanix-ipi-boot-categories-project-f7 periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-vsphere-upi-f7 periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-aws-ipi-byo-route53-f7

**Comment by shellyyang1989** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-gcp-ipi-ovn-ipsec-f7 periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-ibmcloud-ipi-f7 periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-nutanix-ipi-boot-categories-project-f7 pperiodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-aws-ipi-byo-route53-f7

**Comment by shellyyang1989** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-gcp-ipi-ovn-ipsec-f7 periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-ibmcloud-ipi-f7 periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-nutanix-ipi-boot-categories-project-f7 periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-aws-ipi-byo-route53-f7

**Comment by jiajliu** [comment]
From [job](https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/53256/rehearse-53256-periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-azure-upi-f7/1801837957074653184/artifacts/azure-upi-f7/cucushift-upgrade-toimage/build-log.txt), it looks like the target of last hop upgrade not expected.
```
Running command: oc adm upgrade --to-image=registry.build04.ci.openshift.org/ci-op-4czdx534/release@sha256:1fbca396b7e823de04dcaef30d39efc24d0da410d25f8b46a8888e8ace7b099a --allow-explicit-upgrade --force=true
info: Cluster is already at registry.build04.ci.openshift.org/ci-op-4czdx534/release@sha256:1fbca396b7e823de04dcaef30d39efc24d0da410d25f8b46a8888e8ace7b099a
```

**Comment by shellyyang1989** [comment]
> From [job](https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/53256/rehearse-53256-periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-azure-upi-f7/1801837957074653184/artifacts/azure-upi-f7/cucushift-upgrade-toimage/build-log.txt), it looks like the target of last hop upgrade not expected.
> 
> ```
> Running command: oc adm upgrade --to-image=registry.build04.ci.openshift.org/ci-op-4czdx534/release@sha256:1fbca396b7e823de04dcaef30d39efc24d0da410d25f8b46a8888e8ace7b099a --allow-explicit-upgrade --force=true
> info: Cluster is already at registry.build04.ci.openshift.org/ci-op-4czdx534/release@sha256:1fbca396b7e823de04dcaef30d39efc24d0da410d25f8b46a8888e8ace7b099a
> ```

Good catch!

**Comment by shellyyang1989** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-azure-upi-f7 periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-baremetal-ipi-ovn-ipv4-f7 periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-gcp-ipi-ovn-ipsec-f7 periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-ibmcloud-ipi-f7 periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-nutanix-ipi-boot-categories-project-f7 periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-vsphere-upi-f7 periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-aws-ipi-byo-route53-f7

**Comment by shellyyang1989** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-azure-upi-f7 periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-baremetal-ipi-ovn-ipv4-f7 periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-gcp-ipi-ovn-ipsec-f7 periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-ibmcloud-ipi-f7 periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-nutanix-ipi-boot-categories-project-f7 periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-vsphere-upi-f7 periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-aws-ipi-byo-route53-f7

**Comment by shellyyang1989** [comment]
The last hop is [executed](https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/53256/rehearse-53256-periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-rollback-nightly-azure-upi-f7/1802616871082528768/artifacts/azure-upi-f7/gather-extra/artifacts/clusterversion.json) now.
```
"history": [
                    {
                        "acceptedRisks": "Precondition \"ClusterVersionRecommendedUpdate\" failed because of \"UnknownUpdate\": RetrievedUpdates=False (VersionNotFound), so the recommended status of updating from 4.16.0-0.nightly-2024-06-14-130320 to 4.16.0-rc.0 is unknown.",
                        "completionTime": "2024-06-17T13:23:47Z",
                        "image": "registry.build04.ci.openshift.org/ci-op-t53hxs98/release@sha256:c56b01191de4cbb4b97c6eeaf61c5c122fcd465d1d0d671db640d877638ed790",
                        "startedTime": "2024-06-17T12:32:10Z",
                        "state": "Completed",
                        "verified": true,
                        "version": "4.16.0-rc.0"
                    },
                    {
                        "completionTime": "2024-06-17T10:30:41Z",
                        "image": "registry.build04.ci.openshift.org/ci-op-t53hxs98/release@sha256:1fbca396b7e823de04dcaef30d39efc24d0da410d25f8b46a8888e8ace7b099a",
                        "startedTime": "2024-06-17T09:31:52Z",
                        "state": "Completed",
                        "verified": false,
                        "version": "4.16.0-0.nightly-2024-06-14-130320"
                    },
                    {
                        "completionTime": "2024-06-17T09:19:27Z",
                        "image": "registry.build04.ci.openshift.org/ci-op-t53hxs98/release@sha256:c56b01191de4cbb4b97c6eeaf61c5c122fcd465d1d0d671db640d877638ed790",
                        "startedTime": "2024-06-17T08:47:51Z",
                        "state": "Completed",
                        "verified": false,
                        "version": "4.16.0-rc.0"
                    }
                ],
```

**Comment by shellyyang1989** [comment]
@liangxia PTAL Thank you!

**Pull request merged**
