### PR TITLE
remove vsphere build cluster

### PR DESCRIPTION
**Pull request by jcpowermac**

### CODE REVIEW

**Comment by jcpowermac** [comment]
> @jcpowermac: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> ci/build-farm/vsphere-dry	[df7d274](https://github.com/openshift/release/commit/df7d274fc48449e6ae307cd325c37ddd4fd21b31)	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/45875/pull-ci-openshift-release-master-vsphere-dry/1726660936183320576)	false	`/test vsphere-dry`
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openshift&repo=release&pr=45875). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:jcpowermac).

 I am assuming this is because the configuration and `vsphere` directory was removed in the same pr.

**Comment by smg247** [comment]
> > @jcpowermac: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> > Test name	Commit	Details	Required	Rerun command
> > ci/build-farm/vsphere-dry	[df7d274](https://github.com/openshift/release/commit/df7d274fc48449e6ae307cd325c37ddd4fd21b31)	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/45875/pull-ci-openshift-release-master-vsphere-dry/1726660936183320576)	false	`/test vsphere-dry`
> > [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openshift&repo=release&pr=45875). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:jcpowermac).
> 
> I am assuming this is because the configuration and `vsphere` directory was removed in the same pr.

Yes, the context should be retired after this merges. We will just need to override it to merge this.

**Comment by smg247** [comment]
@jcpowermac a text search turns up many more places where `vsphere` is defined, how did you determine these as the only instances to remove?

**Comment by jcpowermac** [comment]
/hold

wait until after thanksgiving

**Comment by danilo-gemoli** [comment]
`ci/build-farm/vsphere-dry` fails, should it be removed too?

**Comment by jcpowermac** [comment]
> `ci/build-farm/vsphere-dry` fails, should it be removed too?

Yep this cluster is to be deleted soon

**Comment by danilo-gemoli** [comment]
Probably we should delete the test `ci/build-farm/vsphere-dry `

**Pull request merged**
