### PR TITLE
Split Packet cluster profiles for the Edge team

### PR DESCRIPTION
**Pull request by lranjbar**

### CODE REVIEW

**Comment by osherdp** [comment]
/test pj-rehearse
(couldn't help myself XD)

**Comment by YuviGold** [comment]
Current failure or not related to the cluster profile change.
/approve
/lgtm

**Comment by lranjbar** [comment]
Can confirm we would have ssh errors and not even get to these errors if the cluster profile wasn't working right. The *-packet-check jobs are passing now so we should be good to go.

**Pull request merged**
