### PR TITLE
Replace the ROSA HCP workflows for external teams

### PR DESCRIPTION
**Pull request by yasun1**
The changes are mainly replacing the workflows with the new ones https://github.com/openshift/release/pull/50124.

[OCPQE-20338](https://issues.redhat.com//browse/OCPQE-20338)

### CODE REVIEW

**Comment by yasun1** [comment]
@ascerra @mffiedler @paigerube14 Please help review the changes. Thanks.

**Comment by paigerube14** [comment]
Are you able to give more detail about why this is changing/we should use hypershift over hcp? CC: @svetsa-rh

**Comment by yasun1** [comment]
@paigerube14 @shakyav The hypershift is the operator's name. The official ROSA hosted cluster on the OCM side is ROSA HCP cluster.

**Comment by yasun1** [comment]
/pj-rehearse ack
@paigerube14 @shakyav  PR is rebased. It requires LGTM again. Thanks.

**Pull request merged**
