### PR TITLE
Adding cli latest for bm refs

### PR DESCRIPTION
**Pull request by paigerube14**
Missing cli 

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-latest-x86-weekly-6nodes/1824960110242304000/artifacts/weekly-6nodes/openshift-qe-installer-bm-day2-label/build-log.txt

CC: @josecastillolema @jtaleric

### CODE REVIEW

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-latest-x86-weekly-6nodes

**Comment by paigerube14** [comment]
@jtaleric got a different error than missing oc: 

```
+ oc projects
The connection to the server api.bm.example.com:6443 was refused - did you specify the right host or port?
```

**Comment by jtaleric** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-latest-x86-weekly-6nodes

**Comment by jtaleric** [comment]
failure unrelated to `oc` being missing. looks better.

**Comment by jtaleric** [comment]
dependent on https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/639

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-latest-x86-weekly-6nodes

**Pull request merged**
