### PR TITLE
OCM-2254 | Add multiarch Dockerfile for building terraform-provider-ocm

### PR DESCRIPTION
**Pull request by enriquebelarte**
Add an extra Dockerfile for building arm64 and amd64 binaries.

### CODE REVIEW

**Comment by enriquebelarte** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-managed-oidc-config-e2e-periodic

**Review by osherdp — APPROVED** [review]

**Comment by enriquebelarte** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-managed-oidc-config-e2e-periodic

**Pull request merged**
