### PR TITLE
[openshift-docs] - Adjusting validate-portal to ensure exit 1 on child process Asciidoctor failures

### PR DESCRIPTION
**Pull request by aireilly**
makeBuild.py should error when there is a failure, or when an Asciidoctor error is logged

### CODE REVIEW

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse ci/rehearse/openshift/openshift-docs/main/validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse ci/rehearse/openshift/openshift-docs/main/validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Comment by kalexand-rh** [comment]
LGTM

**Comment by aireilly** [comment]
> LGTM

Needs /lgtm to label I think?

**Comment by aireilly** [comment]
pj-rehearse ci/rehearse/openshift/openshift-docs/main/validate-portal

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-main-validate-portal

**Review by gabriel-rh — APPROVED** [review]
LGTM

**Pull request merged**
