### PR TITLE
Rename ci-operator *.json configs to *.yaml

### PR DESCRIPTION
**Pull request by petr-muller**
Matching PRs for `ci-operator` (https://github.com/openshift/ci-operator/pull/121) and `ci-operator-prowgen` (https://github.com/openshift/ci-operator-prowgen/pull/9) were merged. This change renames all *.json ci-operator configs to YAML, and adjusts all tools and documentations that reference *.json files. JSON is a YAML subset so all existing tooling should continue to work.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Let's talk about this on Tuesday (or if you feel confident, do it Monday)

**Comment by petr-muller** [comment]
To make processing and merge easier, I have removed the JSON-to-YAML reformatting commit from this PR.

**Comment by bbguimaraes** [comment]
> To make processing and merge easier, I have removed the JSON-to-YAML reformatting commit from this PR.

@petr-muller: do you think the separation is necessary? I would rather do renaming + reformatting in one go, then communicate the change.

**Comment by petr-muller** [comment]
> @petr-muller: do you think the separation is necessary? I would rather do renaming + reformatting in one go, then communicate the change.

It was easier to keep mergeable. Plus the renaming is sensitive because of the references from `ci-operator/jobs/.../*.yaml` files and `cluster/ci/config/prow/config.yaml`. The formatting of the YAML itself does not matter that much and can be changed all at once, gradually or not at all, as we like.

**Comment by bbguimaraes** [comment]
Rebase and let's do it!

**Comment by petr-muller** [comment]
Rebased.

**Comment by petr-muller** [comment]
:crossed_fingers:

**Pull request merged**
