### PR TITLE
Revert "move shared resources ci from techpreview to ga"

### PR DESCRIPTION
**Pull request by gabemontero**
This reverts commit 90a19d3f4317836eb93579c73bc8e5aa31f8c2a6.

see https://redhat-internal.slack.com/archives/C01C8502FMM/p1676472369732279

after this, I'll update my move to GA PRs in openshift/origin, and then openshift/openshift-controller-manager and openshift/cluster-storage-operator

/assign @coreydaley 

@sjenning FYI

### CODE REVIEW

**Comment by gabemontero** [comment]
/pj-rehearse pull-ci-openshift-csi-driver-shared-resource-master-e2e-aws-csi-driver

**Comment by gabemontero** [comment]
/pj-rehearse pull-ci-openshift-csi-driver-shared-resource-operator-master-e2e-aws-csi-driver

**Comment by gabemontero** [comment]
test passed in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/36433/rehearse-36433-pull-ci-openshift-csi-driver-shared-resource-master-e2e-aws-csi-driver/1625928407114059776 but deprovisioning the cluster had a flake

```
 INFO[2023-02-15T19:46:54Z] Running step e2e-aws-csi-driver-test.        
INFO[2023-02-15T19:49:14Z] Step e2e-aws-csi-driver-test succeeded after 2m20s. 
INFO[2023-02-15T19:49:14Z] Step phase test succeeded after 2m20s.       
```

and 

```
PASS
ok  	github.com/openshift/csi-driver-shared-resource/test/e2e	60.107s
```

that said, will try for clean run one more time before putting ack label

/pj-rehearse pull-ci-openshift-csi-driver-shared-resource-master-e2e-aws-csi-driver

**Comment by gabemontero** [comment]
/pj-rehearse pull-ci-openshift-csi-driver-shared-resource-master-e2e-aws-csi-driver

**Comment by gabemontero** [comment]
/pj-rehearse pull-ci-openshift-csi-driver-shared-resource-operator-master-e2e-aws-csi-driver

**Comment by gabemontero** [comment]
bump @coreydaley can you re-lgtm (I had to rebase a few days ago)

once https://github.com/openshift/cluster-storage-operator/pull/343 merges I will retest a couple of the rehearsals, and the apply to rehearsal ack label so this can merge

**Comment by gabemontero** [comment]
/pj-rehearse pull-ci-openshift-csi-driver-shared-resource-master-e2e-aws-csi-driver

**Comment by gabemontero** [comment]
/pj-rehearse pull-ci-openshift-csi-driver-shared-resource-operator-master-e2e-aws-csi-driver

**Comment by gabemontero** [comment]
`could not run steps: step [release-inputs:latest] failed: could not create snapshot imagestream ocp/4.13 for release latest: Timeout: request did not complete within requested timeout - context deadline exceeded`

will retry those 2 rehearsals in a little bit

**Comment by gabemontero** [comment]
/pj-rehearse pull-ci-openshift-csi-driver-shared-resource-master-e2e-aws-csi-driver

**Comment by gabemontero** [comment]
/pj-rehearse pull-ci-openshift-csi-driver-shared-resource-operator-master-e2e-aws-csi-driver

**Comment by gabemontero** [comment]
/pj-rehearse ack

ok @coreydaley please lgtm and let's merge getting our e2e's back to tech preview as well

**Comment by coreydaley** [comment]
@gabemontero looks like you have a merge conflict, ping me once you resolve that and I will lgtm

**Comment by gabemontero** [comment]
/pj-rehearse pull-ci-openshift-csi-driver-shared-resource-operator-master-e2e-aws-csi-driver

**Comment by gabemontero** [comment]
ok this is ready for lgtm @coreydaley thanks

**Pull request merged**
