### PR TITLE
Adding Knative kafka broker image build for 1.2

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

as per title

/hold

/assign @pierDipi

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
Do we need image mirroring too? as a follow-up PR?

/lgtm

**Comment by matzew** [comment]
> Do we need image mirroring too? as a follow-up PR?

we do not really use any image as a mirror, atm

**Pull request merged**
