### PR TITLE
cluster-samples-operator: update OKD configs

### PR DESCRIPTION
**Pull request by vrutkovs**
* master promotes to 4.9
* promotion to OKD 4.8 is re-enabled
* added OKD release-4.9 configs

### CODE REVIEW

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Comment by adambkaplan** [comment]
/lgtm cancel

Looks like this needs a rebase.

**Comment by vrutkovs** [comment]
/hold

Something wrong with image mappings

**Comment by vrutkovs** [comment]
/hold cancel
Resolved

**Comment by gabemontero** [comment]
@vrutkovs need a new approver

**Pull request merged**
