### PR TITLE
always enable Ingress cap in install-config

### PR DESCRIPTION
**Pull request by jinyunma**
Based on OCPBUGS-33793, add Ingress cap to ADDITIONAL_ENABLED_CAPABILITIES on related job config.

### CODE REVIEW

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-aws-upi-basecap-none-arm-f2

**Comment by jinyunma** [comment]
//pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-azure-ipi-basecap-vset-arm-f2

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-azure-ipi-basecap-vset-arm-f2

**Comment by jinyunma** [comment]
cc @jianlinliu @gpei to review

**Comment by jianlinliu** [comment]
cc @liangxia to review.

**Pull request merged**
