### PR TITLE
Add openshift-psap/ci-artifacts repo to ci

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Add openshift-psap/ci-artifacts repo to ci, for now we only want to
build the image and check for healthy yaml. this test are intended to
become part of  step-registry/openshift-psap to test team owned
operators

Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
/hold
Need to add my colleague @courtneypacheco to the org 
and Fix https://github.com/openshift-psap/ci-artifacts/issues/14

**Comment by ArangoGutierrez** [comment]
I am aware ci/rehearse/openshift-psap/ci-artifacts/master/yamllint test is failing but is part of the intention to add a linter for the repo to start enhancing the project.
for this PR we want the required tests to pass, we will fix the project specific tests later on

**Comment by hongkailiu** [comment]
The job `pull-ci-openshift-psap-ci-artifacts-yamllint` is not defined as `optional`.
After we merge this PR, it will block all PRs to merge until you pass the yamllint check.

I would instead suggest
* fix the check. The rehearsal jobs showed that there isnt much to modify, OR
* mark the job `optional: true` for now and remove it after you can pass it.

**Comment by ArangoGutierrez** [comment]
@hongkailiu yamllint recommendations have been attended on the repo, now all tests are green

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
