### PR TITLE
Update jsonnet-bundler version

### PR DESCRIPTION
**Pull request by hongkailiu**
- `jsonnetfile.json` is reformatted by the new version of `jb`.

- `jb --version` is not available in the previous version

Require https://github.com/openshift/release/pull/9241

/cc @stevekuznetsov @bbguimaraes

### CODE REVIEW

**Comment by hongkailiu** [comment]
/hold

wait for the build

**Comment by droslean** [comment]
Well, it seems that `jb` doesn't exist in that image.

**Pull request merged**
