### PR TITLE
add fast-forward job for observability.

### PR DESCRIPTION
**Pull request by morvencao**
Signed-off-by: morvencao <lcao@redhat.com>

### CODE REVIEW

**Comment by clyang82** [comment]
Good catch.

Can you update this file as well - https://github.com/openshift/release/blob/master/ci-operator/config/stolostron/observatorium/stolostron-observatorium-main.yaml ?

**Comment by morvencao** [comment]
> Good catch.
> 
> Can you update this file as well - https://github.com/openshift/release/blob/master/ci-operator/config/stolostron/observatorium/stolostron-observatorium-main.yaml ?

this is in changeset, see: https://github.com/openshift/release/pull/25067/files#diff-6625f474dd2e43ca0a68210adc603938c4761344508439b8535042b83a12d4d9

**Pull request merged**
