### PR TITLE
[WIP] Multi-arch disconnected on AWS QE testconfigs

### PR DESCRIPTION
**Pull request by aleskandro**
rehearse-38799-periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-disconnected-private-p1-f4: 

https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/38799/rehearse-38799-periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-disconnected-private-p1-f4/1663148325089579008

Refers https://issues.redhat.com/browse/MIXEDARCH-262

### CODE REVIEW

**Comment by aleskandro** [comment]
Refers MIXEDARCH-262

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-disconnected-private-p1-f4

**Comment by aleskandro** [comment]
Blocked by https://issues.redhat.com/browse/OCPBUGS-13094

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-disconnected-private-p1-f28-destructive

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-disconnected-private-p1-f4

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-disconnected-private-p1-f4

**Comment by aleskandro** [comment]
Successful tests: 
rehearse-38799-periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-disconnected-private-p1-f4 :
https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/38799/rehearse-38799-periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-disconnected-private-p1-f4/1663148325089579008

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-disconnected-cco-manual-sts-ep-p2-f14

**Comment by aleskandro** [comment]
```
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-disconnected-cco-manual-sts-ep-p2-f14

/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-disconnected-private-p1-f4

/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-disconnected-private-p1-f28-destructive

/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-disconnected-private-techpreview-p3-f28


```

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-disconnected-cco-manual-sts-ep-p2-f14

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-disconnected-private-p1-f4

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-disconnected-private-p1-f28-destructive

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-disconnected-private-techpreview-p3-f28

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-disconnected-cco-manual-sts-ep-p2-f14

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-disconnected-private-techpreview-p3-f28

**Comment by lwan-wanglin** [comment]
Successful installations:

1. rehearse-38799-periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-aws-ipi-disconnected-private-sno-baselinecaps-none-p2-f14 
https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/38799/rehearse-38799-periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-aws-ipi-disconnected-private-sno-baselinecaps-none-p2-f14/1663242548719652864
2. rehearse-38799-periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-disconnected-private-p1-f4
https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/38799/rehearse-38799-periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-disconnected-private-p1-f4/1663242548874842112
3. rehearse-38799-periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-disconnected-private-p1-f28-destructive
https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/38799/rehearse-38799-periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-disconnected-private-p1-f28-destructive/1663242549227163648

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-disconnected-private-techpreview-p3-f28

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.10-amd64-nightly-4.10-upgrade-from-stable-4.9-aws-c2s-ipi-disconnected-private-p2-f14

**Comment by lwan-wanglin** [comment]
/pj-rehearse  periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-disconnected-cco-manual-sts-ep-p2-f14

**Pull request closed without merging**
