### PR TITLE
Add e2e CCM jobs for cloud-provider-aws

### PR DESCRIPTION
**Pull request by Fedosin**
To make sure AWS CCM works correctly we need to add 2 e2e jobs to its repository:
* e2e-aws-ccm tests migration from in-tree cloud provider to the CCM.
* e2e-aws-ccm-install tests fresh installation with AWS CCM.

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
/approve

Should we be adding similar jobs for other providers as well?

**Comment by Fedosin** [comment]
@JoelSpeed azure and openstack already have them. Other platforms will be added gradually.

**Pull request merged**
