### PR TITLE
HOSTEDCP-1725: hypershift: add kubevirt e2e as periodic job

### PR DESCRIPTION
**Pull request by sjenning**
@csrwng @davidvossel @stevekuznetsov

### CODE REVIEW

**Review by davidvossel — COMMENTED** [review]
/lgtm

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.17-periodics-e2e-kubevirt-aws-ovn

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.17-periodics-e2e-kubevirt-aws-ovn

**Review by davidvossel — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
