### PR TITLE
update camgi to version 0.8.0

### PR DESCRIPTION
**Pull request by elmiko**
this update brings in support for BareMetalHost and ControlPlaneMachineSet CRDs as well as some fixes for embedding the output into other html pages.

### CODE REVIEW

**Comment by elmiko** [comment]
cc @joelspeed and @stbenjam , this update contains some changes you have been asking about =)

**Comment by elmiko** [comment]
had a small issue with the release packaging, should be fixed now.
/retest

**Comment by elmiko** [comment]
looks like it's working now, the remaining failures are most likely flakes

**Review by vrutkovs — APPROVED** [review]
/lgtm

**Pull request merged**
