### PR TITLE
OSSM maistra trigger push image jobs manually

### PR DESCRIPTION
**Pull request by yxun**

### CODE REVIEW

**Review by jwendell — COMMENTED** [review]
Is it possible to run these jobs with just `/test push-image`?

**Comment by yxun** [comment]
> Is it possible to run these jobs with just `/test push-image`?

I don't think so. The `trigger` field is not in the "Tolerated Changes to Generated Jobs"
https://docs.ci.openshift.org/docs/how-tos/contributing-openshift-release/#tolerated-changes-to-generated-jobs

**Review by luksa — APPROVED** [review]

**Comment by jwendell** [comment]
> > Is it possible to run these jobs with just `/test push-image`?
> 
> I don't think so. The `trigger` field is not in the "Tolerated Changes to Generated Jobs" https://docs.ci.openshift.org/docs/how-tos/contributing-openshift-release/#tolerated-changes-to-generated-jobs

OK, I think we could at least simplify the name of these jobs, e.g., by removing the repo name from the job name. Example, `istio-operator-push-images-2.3` => `push-images`.

My concern is that the job name is so hard to guess that people will have to ask us or spend much time figuring out what to put in their `/test <job-name>` comment.

But that could be another PR I guess. YDYT?

**Comment by yxun** [comment]
I can rename those in this PR . one min

**Comment by yxun** [comment]
/pj-rehearse pull-ci-maistra-istio-operator-maistra-3.0-push-images

**Review by jwendell — APPROVED** [review]

**Pull request merged**
