### PR TITLE
ipsec: move to new api for >=4.15

### PR DESCRIPTION
**Pull request by yuvalk**
this is to align with CNO API changes on how to enable ipsec and support
N-S

### CODE REVIEW

**Comment by jcaamano** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-e2e-ovn-ipsec-step-registry
/pj-rehearse pull-ci-openshift-cluster-network-operator-release-4.15-e2e-ovn-ipsec-step-registry
/pj-rehearse pull-ci-openshift-cluster-network-operator-release-4.14-e2e-ovn-ipsec-step-registry
/pj-rehearse pull-ci-openshift-cluster-network-operator-release-4.13-e2e-metal-ipi-ovn-ipv6-ipsec

**Comment by yuvalk** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-e2e-ovn-ipsec-step-registry

**Comment by yuvalk** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-master-e2e-ovn-ipsec-step-registry

**Pull request closed without merging**
