### PR TITLE
MetalLB / Operator: move to rhel9

### PR DESCRIPTION
**Pull request by fedepaol**

### CODE REVIEW

**Comment by fedepaol** [comment]
/pj-rehearse  pull-ci-openshift-metallb-operator-release-main-images

**Comment by zeeke** [comment]
Supersedes
- https://github.com/openshift/release/pull/45027
that has been reverted by [`63d3f4d2e1aeb6296399519dca81afe4b62ced33`](https://github.com/openshift/release/commit/63d3f4d2e1aeb6296399519dca81afe4b62ced33).

Setting base image to `base-rhel9` should avoid getting reverted again by `registry-replacer`

**Pull request merged**
