### PR TITLE
OPRUN-1873: operator-framework-olm: add git to the bumper image

### PR DESCRIPTION
**Pull request by stevekuznetsov**

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
/pj-rehearse pull-ci-openshift-operator-framework-olm-master-images

**Comment by stevekuznetsov** [comment]
/pj-rehearse pull-ci-openshift-operator-framework-olm-master-images

**Review by hongkailiu — APPROVED** [review]

**Comment by stevekuznetsov** [comment]
/pj-rehearse pull-ci-openshift-operator-framework-olm-master-images

**Comment by stevekuznetsov** [comment]
/pj-rehearse pull-ci-openshift-operator-framework-olm-master-images

**Comment by stevekuznetsov** [comment]
/pj-rehearse pull-ci-openshift-operator-framework-olm-master-images

**Pull request merged**
