### PR TITLE
MGMT-4055 Test to install assisted-service operator

### PR DESCRIPTION
**Pull request by rwsu**
Adds a test to install the operator.

### CODE REVIEW

**Comment by lranjbar** [comment]
This looks good now :+1:

**Comment by lranjbar** [comment]
@rwsu I'm guessing we don't need hive or local-storage-operator for the cloud use case right?

**Comment by flaper87** [comment]
> @rwsu I'm guessing we don't need hive or local-storage-operator for the cloud use case right?

I believe this is correct, yes. We only need the LocalStorage when we are using the FS storage and Hive + BMO for the onprem case.

I see the `assisted-installer` is deployed but I'm not sure how the `AgentServiceConfig` is being created for this deployment. Would you mind pointing me to where this happens? 

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/17728/rehearse-17728-pull-ci-openshift-assisted-service-master-assisted-operator-install-aws/1382638960710258688/artifacts/assisted-operator-install-aws/gather-extra/artifacts/pods/assisted-installer_1c807309c16189266c7d15bb895f224ac6870eb8cd207869bcf9c88dbdtbklw_extract.log

Otherwise, for the little I know about this prow setup and environment, this PR lgtm

**Comment by rwsu** [comment]
> I believe this is correct, yes. We only need the LocalStorage when we are using the FS storage and Hive + BMO for the onprem case.
> 
> I see the `assisted-installer` is deployed but I'm not sure how the `AgentServiceConfig` is being created for this deployment. Would you mind pointing me to where this happens?
> 

`assisted-installer` is the namespace. The pod you are referencing is the pod that installed the operator from the bundle.  The test only installs the operator. The operand isn't installed. We can try to expand it later to install the operand, but I'm not sure if the CI is able to pull in CRDs from Hive and other dependencies using the optional-operators-ci-aws workflow. We will want to try one of the other workflows that creates an OCP cluster and install the operator on top of it.

The AgentServiceConfig crd you see is coming from https://github.com/openshift/assisted-service/tree/master/internal/controller/config/crd/bases

**Comment by flaper87** [comment]
> The test only installs the operator.

Ah, this is the part that I was missing. It seemed clear from the code but the logs confused me a bit and I thought we were installing the operand.

**Review by flaper87 — APPROVED** [review]

**Pull request merged**
