### PR TITLE
fix: Remove unit tests duplication, old branch and add mirror - OADP

### PR DESCRIPTION
**Pull request by mateusoliveira43**
Remove unit tests duplication, old branch and add mirror to OADP operator branches.

Fixes https://github.com/openshift/oadp-operator/issues/1234
Fixes https://github.com/openshift/oadp-operator/issues/1228

### CODE REVIEW

**Comment by mateusoliveira43** [comment]
/hold
talk in scrum before merging

**Review by kaovilai — APPROVED** [review]

**Comment by mateusoliveira43** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-oadp-1.1-images pull-ci-openshift-oadp-operator-oadp-1.1-unit-test pull-ci-openshift-oadp-operator-oadp-1.1-4.11-images pull-ci-openshift-oadp-operator-oadp-1.1-4.11-ci-index pull-ci-openshift-oadp-operator-oadp-1.1-4.11-e2e-test-aws

**Review by kaovilai — APPROVED** [review]

**Comment by kaovilai** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-oadp-1.1-unit-test
/pj-rehearse pull-ci-openshift-oadp-operator-oadp-1.1-4.11-images
/pj-rehearse pull-ci-openshift-oadp-operator-oadp-1.1-4.11-ci-index
/pj-rehearse pull-ci-openshift-oadp-operator-oadp-1.1-4.11-e2e-test-aws

**Comment by kaovilai** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-oadp-1.1-4.11-images

**Comment by kaovilai** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-oadp-1.1-4.11-ci-index

**Comment by kaovilai** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-oadp-1.1-4.11-e2e-test-aws

**Comment by mateusoliveira43** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-oadp-1.2-images pull-ci-openshift-oadp-operator-oadp-1.2-unit-test pull-ci-openshift-oadp-operator-oadp-1.2-4.13-images pull-ci-openshift-oadp-operator-oadp-1.2-4.13-ci-index pull-ci-openshift-oadp-operator-oadp-1.2-4.13-e2e-test-aws pull-ci-openshift-oadp-operator-oadp-1.3-images pull-ci-openshift-oadp-operator-oadp-1.3-unit-test pull-ci-openshift-oadp-operator-oadp-1.3-4.14-images pull-ci-openshift-oadp-operator-oadp-1.3-4.14-ci-index pull-ci-openshift-oadp-operator-oadp-1.3-4.14-e2e-test-aws

**Pull request merged**
