### PR TITLE
Revamp of ocs operator ci jobs

### PR DESCRIPTION
**Pull request by malayparida2000**
1. Define build root image in this repo instead of ocs-operator repo.
2. Build ocs-metrics-exporter image in ci & use it in the bundle.
3. Completely remove sqlite db based & Appregistry based index images.
    As these are deprecated since long time now.
4. Remove ocs-must-gather job as it is in a different repo now
    independent of ocs-operator.
5. Remove verify-latest-csv job as it is now added to ocs-operator-ci.
6. Stop using optional-operators-ci-aws workflow, Instead install the
    operators by first bringing up a cluster with ipi-aws workflow &
    then install the operators using make targets on ocs repo.
7. For ocs bundle use the bundle image built in the ci env.
8. Remove red-hat-storage-ocs-ci-e2e-aws job as it doesn't work since a
    long time & disabled anyways. And there is no plan to fix it.
9. Use the latest golang 1.20, ocp 4.14 related images.
10. Remove the latest-upstream tests as they are not really being used
    by us & they are failing since some time also.

TODO items-

1. Update Dockerfile paths after cleanup in ocs repo.

### CODE REVIEW

**Comment by malayparida2000** [comment]
TODO items-
1. Update Dockerfile paths after cleanup in ocs repo.
2. Remove verify latest csv after adding it to make ocs-operator-ci in the ocs repo
3. After moving to makefile from hack scripts, move the noobaa bundle install task to ocs repo
4. Remove latest-upstream jobs after more investigation

**Review by iamniting — APPROVED** [review]

**Pull request merged**
