### PR TITLE
fix: e2e-gcp-qe-no-capabilities as optional

### PR DESCRIPTION
**Pull request by Elbehery**
This PR changes etcd e2e-gcp-qe-no-capabilities ci job to `optional` 

cc @tjungblu @hasbro17 @dusk125

### CODE REVIEW

**Comment by fxierh** [comment]
I think we need an additional base image for `e2e-gcp-qe-no-capabilities` (see the `openshift-extended-test` step in the `openshift-e2e-test-qe` chain):
https://github.com/openshift/release/blob/077afcf6503638cc25185d55fedffb28549418e4/ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml#L26-L29

**Comment by Elbehery** [comment]
> openshift-e2e-test-qe

@fxierh hello 

i cant get what u mean ? 

the test suit is already part of the chain `openshift-e2e-test-qe` .. where should i add the base image ?

**Comment by fxierh** [comment]
@Elbehery I meant we probably need something like this:
https://github.com/openshift/release/blob/1edd4dc611ae8516db8de820736a325c196f31db/ci-operator/config/rh-ecosystem-edge/recert/rh-ecosystem-edge-recert-main.yaml#L10-L13
since the `openshift-extended-test` step (in the `openshift-e2e-test-qe` chain) depends on this image.

**Comment by lance5890** [comment]
update by  https://github.com/openshift/release/pull/47890

**Comment by tjungblu** [comment]
Thanks a lot @Elbehery 

/lgtm

**Pull request merged**
