### PR TITLE
ptp ci switch time for 4.16/4.17

### PR DESCRIPTION
**Pull request by jzding**
This PR is switching scheduled 4.16/4.17 PTP nightly CI so that 4.17 runs later than 4.16 and finishes in the morning. The reason being 4.17/master is where we have most code churns. By leaving the CI cluster setup in 4.17 in the morning, developers can run dev CIs during the day without re-setup 4.17 cluster.

### CODE REVIEW

**Review by aneeshkp — APPROVED** [review]
/lgtm

**Comment by vrutkovs** [comment]
Is this "we're tweaking cron time to avoid hitting other jobs because jobs don't use https://docs.ci.openshift.org/docs/architecture/quota-and-leases/"? Again?

**Comment by jzding** [comment]
> Is this "we're tweaking cron time to avoid hitting other jobs because jobs don't use https://docs.ci.openshift.org/docs/architecture/quota-and-leases/"? Again?

no. we simply switch these 2 jobs so that 4.17 setup ends up in the morning and developers and use it to do their dev testing on 4.17 during the day.

**Comment by vrutkovs** [comment]
Oh, okay
/approve

it would be handy to have it in the description :)

**Pull request merged**
