### PR TITLE
Fix issue DPTP-3957 Prepare to enable aarch64-based control plane

### PR DESCRIPTION
**Pull request by bear-redhat**

### CODE REVIEW

**Comment by bear-redhat** [comment]
/pj-rehearse periodic-ci-openshift-release-master-hypershift-4.15-periodic-ci-openshift-hypershift-hosted

**Comment by bear-redhat** [comment]
/pj-rehearse periodic-ci-openshift-release-master-hypershift-4.15-periodic-ci-openshift-hypershift-hosted

**Comment by bear-redhat** [comment]
/pj-rehearse periodic-ci-openshift-release-master-hypershift-4.15-periodic-ci-openshift-hypershift-hosted

**Comment by bear-redhat** [comment]
/pj-rehearse periodic-ci-openshift-release-master-hypershift-4.15-periodic-ci-openshift-hypershift-hosted

**Comment by bear-redhat** [comment]
/pj-rehearse periodic-ci-openshift-release-master-hypershift-4.15-periodic-ci-openshift-hypershift-hosted

**Comment by bear-redhat** [comment]
/pj-rehearse periodic-ci-openshift-release-master-hypershift-4.17-periodic-ci-openshift-hypershift-hosted

**Comment by bear-redhat** [comment]
/pj-rehearse periodic-ci-openshift-release-master-hypershift-4.16-periodic-ci-openshift-hypershift-hosted

**Comment by bear-redhat** [comment]
/pj-rehearse periodic-ci-openshift-release-master-hypershift-4.16-periodic-ci-openshift-hypershift-hosted

**Comment by bear-redhat** [comment]
/pj-rehearse periodic-ci-openshift-release-master-hypershift-4.16-periodic-ci-openshift-hypershift-hosted

**Comment by bear-redhat** [comment]
/pj-rehearse periodic-ci-openshift-release-master-hypershift-4.16-periodic-ci-openshift-hypershift-hosted

**Comment by bear-redhat** [comment]
/pj-rehearse periodic-ci-openshift-release-master-hypershift-4.16-periodic-ci-openshift-hypershift-hosted

**Comment by danilo-gemoli** [comment]
/pj-rehearse periodic-ci-openshift-release-master-hypershift-4.16-periodic-ci-openshift-hypershift-hosted

**Comment by bear-redhat** [comment]
/pj-rehearse periodic-ci-openshift-release-master-hypershift-4.16-periodic-ci-openshift-hypershift-hosted

**Comment by bear-redhat** [comment]
/pj-rehearse periodic-ci-openshift-release-master-hypershift-4.16-periodic-ci-openshift-hypershift-hosted

**Comment by bear-redhat** [comment]
/pj-rehearse periodic-ci-openshift-release-master-hypershift-4.16-periodic-ci-openshift-hypershift-hosted

**Pull request merged**
