### PR TITLE
bmctest periodic hardware test jobs

### PR DESCRIPTION
**Pull request by tdomnesc**
/hold
/uncc

### CODE REVIEW

**Comment by tdomnesc** [comment]
/pj-rehearse pull-ci-openshift-metal3-bmctest-main-servercheck-test-upstream

**Comment by tdomnesc** [comment]
/pj-rehearse pull-ci-openshift-metal3-bmctest-main-servercheck-test-upstream

**Comment by tdomnesc** [comment]
/pj-rehearse pull-ci-openshift-metal3-bmctest-main-servercheck-test-upstream

**Comment by tdomnesc** [comment]
/pj-rehearse pull-ci-openshift-metal3-bmctest-main-servercheck-test-upstream

**Comment by tdomnesc** [comment]
/pj-rehearse pull-ci-openshift-metal3-bmctest-main-servercheck-test-upstream

**Comment by tdomnesc** [comment]
/pj-rehearse pull-ci-openshift-metal3-bmctest-main-servercheck-test-upstream

**Comment by tdomnesc** [comment]
/pj-rehearse pull-ci-openshift-metal3-bmctest-main-servercheck-test-upstream

**Comment by tdomnesc** [comment]
/pj-rehearse pull-ci-openshift-metal3-bmctest-main-servercheck-test-upstream

**Comment by tdomnesc** [comment]
/pj-rehearse pull-ci-openshift-metal3-bmctest-main-servercheck-test-upstream

**Comment by tdomnesc** [comment]
/pj-rehearse pull-ci-openshift-metal3-bmctest-main-servercheck-test-upstream

**Comment by tdomnesc** [comment]
/pj-rehearse pull-ci-openshift-metal3-bmctest-main-servercheck-test-upstream

**Comment by tdomnesc** [comment]
/pj-rehearse pull-ci-openshift-metal3-bmctest-main-servercheck-test-upstream

**Comment by tdomnesc** [comment]
/pj-rehearse pull-ci-openshift-metal3-bmctest-main-servercheck-test-upstream

**Comment by tdomnesc** [comment]
/pj-rehearse pull-ci-openshift-metal3-bmctest-main-servercheck-test-openshift

**Comment by tdomnesc** [comment]
/pj-rehearse pull-ci-openshift-metal3-bmctest-main-servercheck-test-openshift

**Comment by tdomnesc** [comment]
/pj-rehearse pull-ci-openshift-metal3-bmctest-main-servercheck-test-openshift

**Comment by tdomnesc** [comment]
/pj-rehearse periodic-ci-openshift-metal3-bmctest-main-servercheck-test-upstream periodic-ci-openshift-metal3-bmctest-main-servercheck-test-openshift

**Comment by tdomnesc** [comment]
/pj-rehearse periodic-ci-openshift-metal3-bmctest-main-servercheck-test-upstream periodic-ci-openshift-metal3-bmctest-main-servercheck-test-openshift

**Comment by tdomnesc** [comment]
/pj-rehearse periodic-ci-openshift-metal3-bmctest-main-servercheck-test-upstream

**Comment by tdomnesc** [comment]
/pj-rehearse periodic-ci-openshift-metal3-bmctest-main-servercheck-test-upstream

**Comment by tdomnesc** [comment]
/pj-rehearse periodic-ci-openshift-metal3-bmctest-main-servercheck-test-upstream

**Comment by tdomnesc** [comment]
/pj-rehearse periodic-ci-openshift-metal3-bmctest-main-servercheck-test-upstream

**Comment by tdomnesc** [comment]
/pj-rehearse periodic-ci-openshift-metal3-bmctest-main-servercheck-test-openshift

**Comment by tdomnesc** [comment]
/pj-rehearse periodic-ci-openshift-metal3-bmctest-main-servercheck-test-openshift

**Comment by tdomnesc** [comment]
/pj-rehearse periodic-ci-openshift-metal3-bmctest-main-servercheck-test-openshift

**Comment by tdomnesc** [comment]
/pj-rehearse periodic-ci-openshift-metal3-bmctest-main-servercheck-test-upstream

**Comment by derekhiggins** [comment]
/lgtm
great, thanks

**Pull request merged**
