### PR TITLE
openstack-test: Add JUnit reporting

### PR DESCRIPTION
**Pull request by pierreprinetti**

### CODE REVIEW

**Comment by mandre** [comment]
This will need a rebase once https://github.com/openshift/release/pull/29777 merges.

**Comment by pierreprinetti** [comment]
Rebased! @mandre @dulek PTAL.

**Comment by dulek** [comment]
Seems like this works and results of both runs are combined! I'll let @pierreprinetti confirm before approving.

**Comment by pierreprinetti** [comment]
LGTM! openstack-test results are incorporated in Prow whenever they're run (openstack-test is never run when the previous openshift-test step fails)

**Pull request merged**
