### PR TITLE
modified source namespace for ocs addon for osde2e

### PR DESCRIPTION
**Pull request by kesavanvt**
Modified the source namespace for ocs addon after creating the secret 
Signed-off-by: kesavan <kvellalo@redhat.com>

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@kesavan can you lgtm this?

**Comment by kesavanvt** [comment]
> @kesavan can you lgtm this?

should i do it myself @alvaroaleman ?

**Comment by kesavanvt** [comment]
@jeefy Please review

**Review by droslean — APPROVED** [review]

**Pull request merged**
