### PR TITLE
MON-1208: add unit tests jobs to grafana

### PR DESCRIPTION
**Pull request by dgrisonnet**

### CODE REVIEW

**Review by paulfantom — APPROVED** [review]
/lgtm

**Comment by paulfantom** [comment]
Maybe we can split this into 2 PRs, one with `test-go` and another with `test-js` (if achievable)?

**Comment by dgrisonnet** [comment]
I attempted to run `test-js` but it turns out to be very complex to get `nodejs12` and `yarn` without being root in the container. Most of the step in their installation requires root privilege and I don't think it's worth investigating time into trying to make a rootless installation since we consider removing grafana in the future.

Here is the CI run where I attempted to run `test-js` and install all its dependencies if you wanna check it out: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/14374/rehearse-14374-pull-ci-openshift-grafana-master-test-js/1339260463426310144

**Comment by dgrisonnet** [comment]
Holding until we decide if we should invest some time into trying to run the javascript unit tests.

/hold

**Comment by dgrisonnet** [comment]
It's been decided that running Grafana's javascript unit tests isn't worth the effort.

/unhold

**Pull request merged**
