### PR TITLE
Remove unnecessary windows-e2e-operator-test-with-custom-vxlan-port workflow

### PR DESCRIPTION
**Pull request by danwinship**
#10801 added `ovn-conf-hybrid-manifest-with-custom-vxlan-port` and `ipi-aws-ovn-hybrid-custom-vxlan-port` and `windows-e2e-operator-test-with-custom-vxlan-port`. But while the former two actually did new custom-vxlan-port-related things, the latter was just an exact copy of `windows-e2e-operator-test`, just renamed. There doesn't seem to have ever been any need for it; I guess this was just back when everyone was still figuring out how step-based jobs worked so we didn't realize.

### CODE REVIEW

**Comment by danwinship** [comment]
/assign @JacobTanenbaum 

Am I crazy or is this workflow unnecessary?

**Comment by JacobTanenbaum** [comment]
good catch 
/lgtm

**Comment by danwinship** [comment]
/assign @sebsoto 
for WMCO / windows-step-registry approval

**Comment by sebsoto** [comment]
/lgtm

Thanks, looks like you are correct in that this workflow is a duplicate of the other

**Comment by danwinship** [comment]
/pj-rehearse ack
(got removed on rebase, but the rebase just synced up with the fact that some of the jobs I originally modified had since been removed)

/remove-lifecycle stale

**Pull request merged**
