### PR TITLE
vSphere none vcm fix

### PR DESCRIPTION
**Pull request by jcpowermac**

### CODE REVIEW

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.16-platform-none-vsphere-e2e-operator

**Comment by mansikulkarni96** [comment]
Still, see an error in the deprovision logs, not sure if its just a red herring:
```
Deprovisioning ci-op-jbv4nsvq-6f478
2024-06-20 14:11:06+00:00 - Collecting vCenter performance data and alerts
govc: open /var/run/vault/vsphere-ibmcloud-ci/vcenter-certificate: no such file or directory
govc: open /var/run/vault/vsphere-ibmcloud-ci/vcenter-certificate: no such file or directory
2024-06-20 14:11:06+00:00 - Copying config from shared dir...
~/installer /output
```

**Comment by jcpowermac** [comment]
> Still, see an error in the deprovision logs, not sure if its just a red herring:
> 
> ```
> Deprovisioning ci-op-jbv4nsvq-6f478
> 2024-06-20 14:11:06+00:00 - Collecting vCenter performance data and alerts
> govc: open /var/run/vault/vsphere-ibmcloud-ci/vcenter-certificate: no such file or directory
> govc: open /var/run/vault/vsphere-ibmcloud-ci/vcenter-certificate: no such file or directory
> 2024-06-20 14:11:06+00:00 - Copying config from shared dir...
> ~/installer /output
> ```

I will take a look at that too, there was another missing part of this that just merged
https://github.com/openshift/release/pull/53487

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.16-platform-none-vsphere-e2e-operator

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.16-platform-none-vsphere-e2e-operator

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.16-platform-none-vsphere-e2e-operator

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.16-platform-none-vsphere-e2e-operator pull-ci-openshift-windows-machine-config-operator-release-4.15-platform-none-vsphere-e2e-operator

**Comment by jcpowermac** [comment]
terraform is happy, just need to get pwsh/powercli variables fixed.

**Comment by jcpowermac** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.16-platform-none-vsphere-e2e-operator

**Pull request merged**
