### PR TITLE
Add IPv6 SNO test job to CI

### PR DESCRIPTION
**Pull request by eliorerz**

### CODE REVIEW

**Comment by YuviGold** [comment]
Why do we need it? Does it add covers special behavior we don't cover with ipv6 or with single-node jobs?

**Comment by eliorerz** [comment]
@YuviGold There are few if blocks that are relevant only to SNO + IPv6

**Comment by YuviGold** [comment]
@eranco74 @tsorya Is there any specific logic for that?

@eliorerz in any case, change these jobs to be optional.

**Pull request closed without merging**
