### PR TITLE
Fix maistra operator integration test

### PR DESCRIPTION
**Pull request by jwendell**
Build and push an image from the current code and use this image when testing.

### CODE REVIEW

**Comment by jwendell** [comment]
/pj-rehearse pull-ci-maistra-istio-operator-maistra-3.0-istio-operator-integration-test-3-0

**Comment by jwendell** [comment]
/pj-rehearse auto-ack pull-ci-maistra-istio-operator-maistra-3.0-istio-operator-integration-test-3-0

**Review by bartoszmajsak — APPROVED** [review]
LGTM, just one question - are we removing those images once the PR is merged?

**Comment by jwendell** [comment]
> LGTM, just one question - are we removing those images once the PR is merged?

nope. We have to still deal with garbage collection. This is also an issue with daily images which are accumulating forever.

**Comment by jwendell** [comment]
to be clear, for the sake of integration tests, this is just a workaround. The proper solution is to make use of the openshift internal registry, which is not installed by default on these clusters.

**Pull request merged**
