### PR TITLE
Fix make target calls

### PR DESCRIPTION
**Pull request by dhiller**
/cc @zcahana @orenc1

### CODE REVIEW

**Review by zcahana — APPROVED** [review]
These are now in line with the the actual [make targets](https://github.com/openshift-cnv/cnv-ci/blob/master/Makefile).

**Comment by zcahana** [comment]
/assign @orec1
/assign @tiraboschi 

I don't have OWNER settings for this directory, can you please approve?

**Comment by zcahana** [comment]
/assign @orenc1
/assign @tiraboschi

I don't have OWNER settings for this directory, can you please approve?

**Comment by zcahana** [comment]
The rehearsal jobs are failing due to a syntax error in the placeholder script for this lane. This is fixed in [cnv-ci#19](https://github.com/openshift-cnv/cnv-ci/pull/19), but fails the existing lane due to the problem fixed in this PR.

We can either manually merge cnv-ci#19, or nullify this lane (in a separate PR that will pass rehearsals) and then merge cnv-ci#19.

**Comment by zcahana** [comment]
> @dhiller: you cannot LGTM your own PR.

make sense.

**Comment by zcahana** [comment]
Need to debug `4.6-e2e-deploy` - it fails after a ~4h timeout - and I saw quite a lot of similar error in cnv-ci^release-4.6.

**Comment by zcahana** [comment]
@dhiller since the only failing lane is the `4.6-e2e-deploy` rehearsal job, which is unrelated to the change introduced in this PR - can we override the rehearsals lane here so that we can move with the upgrade tests development?

**Comment by dhiller** [comment]
> @dhiller since the only failing lane is the `4.6-e2e-deploy` rehearsal job, which is unrelated to the change introduced in this PR - can we override the rehearsals lane here so that we can move with the upgrade tests development?

We don't need to override as the lanes are not required. @orenc1 can you take a look, please?

**Review by orenc1 — APPROVED** [review]
I reviewed and it's looks good to me.

**Pull request merged**
