### PR TITLE
velero-plugin-for-aws: intial setup

### PR DESCRIPTION
**Pull request by hhpatel14**
Initial setup for https://github.com/openshift/velero-plugin-for-aws. Build image, add unit-test and, mirror image to external registry.

### CODE REVIEW

**Comment by hhpatel14** [comment]
=== RUN   TestS3URL
--- PASS: TestS3URL (0.00s)
=== RUN   TestIsValidSignatureVersion
--- PASS: TestIsValidSignatureVersion (0.00s)
=== RUN   TestObjectExists
=== RUN   TestObjectExists/exists
    object_store_test.go:126: PASS:	HeadObject(*s3.HeadObjectInput)
=== RUN   TestObjectExists/doesn't_exist
    object_store_test.go:121: PASS:	HeadObject(*s3.HeadObjectInput)
=== RUN   TestObjectExists/error_checking_for_existence
    object_store_test.go:121: PASS:	HeadObject(*s3.HeadObjectInput)
--- PASS: TestObjectExists (0.00s)
    --- PASS: TestObjectExists/exists (0.00s)
    --- PASS: TestObjectExists/doesn't_exist (0.00s)
    --- PASS: TestObjectExists/error_checking_for_existence (0.00s)
=== RUN   TestGetVolumeID
--- PASS: TestGetVolumeID (0.00s)
=== RUN   TestGetVolumeIDForCSI
=== RUN   TestGetVolumeIDForCSI/aws_csi_driver
=== RUN   TestGetVolumeIDForCSI/unknown_csi_driver
time="2023-02-17T17:28:56Z" level=info msg="Unable to handle CSI driver: unknown.drv.com"
--- PASS: TestGetVolumeIDForCSI (0.00s)
    --- PASS: TestGetVolumeIDForCSI/aws_csi_driver (0.00s)
    --- PASS: TestGetVolumeIDForCSI/unknown_csi_driver (0.00s)
=== RUN   TestSetVolumeID
--- PASS: TestSetVolumeID (0.00s)
=== RUN   TestSetVolumeIDNoZone
--- PASS: TestSetVolumeIDNoZone (0.00s)
=== RUN   TestSetVolumeIDForCSI
=== RUN   TestSetVolumeIDForCSI/set_ID_to_CSI_with_aws_EBS_CSI_driver
=== RUN   TestSetVolumeIDForCSI/set_ID_to_CSI_with_EFS_CSI_driver
--- PASS: TestSetVolumeIDForCSI (0.00s)
    --- PASS: TestSetVolumeIDForCSI/set_ID_to_CSI_with_aws_EBS_CSI_driver (0.00s)
    --- PASS: TestSetVolumeIDForCSI/set_ID_to_CSI_with_EFS_CSI_driver (0.00s)
=== RUN   TestGetTagsForCluster
=== RUN   TestGetTagsForCluster/degenerate_case_(no_tags)
=== RUN   TestGetTagsForCluster/cluster_tags_exist_and_remain_set
=== RUN   TestGetTagsForCluster/cluster_tags_only_get_applied
=== RUN   TestGetTagsForCluster/non-overlaping_cluster_and_snapshot_tags_both_get_applied
=== RUN   TestGetTagsForCluster/overlaping_cluster_tags,_current_cluster_tags_take_precedence
--- PASS: TestGetTagsForCluster (0.00s)
    --- PASS: TestGetTagsForCluster/degenerate_case_(no_tags) (0.00s)
    --- PASS: TestGetTagsForCluster/cluster_tags_exist_and_remain_set (0.00s)
    --- PASS: TestGetTagsForCluster/cluster_tags_only_get_applied (0.00s)
    --- PASS: TestGetTagsForCluster/non-overlaping_cluster_and_snapshot_tags_both_get_applied (0.00s)
    --- PASS: TestGetTagsForCluster/overlaping_cluster_tags,_current_cluster_tags_take_precedence (0.00s)
=== RUN   TestGetTags
=== RUN   TestGetTags/degenerate_case_(no_tags)
=== RUN   TestGetTags/velero_tags_only_get_applied
=== RUN   TestGetTags/volume_tags_only_get_applied
=== RUN   TestGetTags/non-overlapping_velero_and_volume_tags_both_get_applied
=== RUN   TestGetTags/when_tags_overlap,_velero_tags_take_precedence
--- PASS: TestGetTags (0.00s)
    --- PASS: TestGetTags/degenerate_case_(no_tags) (0.00s)
    --- PASS: TestGetTags/velero_tags_only_get_applied (0.00s)
    --- PASS: TestGetTags/volume_tags_only_get_applied (0.00s)
    --- PASS: TestGetTags/non-overlapping_velero_and_volume_tags_both_get_applied (0.00s)
    --- PASS: TestGetTags/when_tags_overlap,_velero_tags_take_precedence (0.00s)
PASS
ok  	github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws	0.016s

**Comment by hhpatel14** [comment]
image-build log: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/36511/rehearse-36511-pull-ci-openshift-velero-plugin-for-aws-konveyor-dev-images/1626633798479253504/artifacts/build-logs/velero-plugin-for-aws.log

**Comment by hhpatel14** [comment]
/assign hongkailiu 
@hongkailiu pinging for approval

**Review by hongkailiu — APPROVED** [review]

**Pull request merged**
