### PR TITLE
install npm for stolostron/alertmanager

### PR DESCRIPTION
**Pull request by coleenquadros**
Updating stolostron/alertmanager to v0.27.0 that requires npm 
Using reference from https://github.com/openshift/prometheus-alertmanager/pull/90#issuecomment-2051166769

Stolostron/prometheus - Update to v2.51.2 does not have react-app-test target
https://github.com/openshift/release/blob/c7452ffec3002ab757f91dc4b665b3ecfa3d8742/ci-operator/config/openshift/prometheus/openshift-prometheus-release-4.17.yaml#L70

### CODE REVIEW

**Comment by coleenquadros** [comment]
/pj-rehearse pull-ci-stolostron-prometheus-alertmanager-release-2.11-sonar-pre-submit

**Review by thibaultmg — APPROVED** [review]
/lgtm

**Comment by subbarao-meduri** [comment]
/pj-rehearse pull-ci-stolostron-prometheus-alertmanager-release-2.11-test

**Comment by subbarao-meduri** [comment]
/pj-rehearse pull-ci-stolostron-prometheus-release-2.11-react-app-test

**Comment by coleenquadros** [comment]
@subbarao-meduri let me know if this good to merge

**Comment by subbarao-meduri** [comment]
/pj-rehearse pull-ci-stolostron-prometheus-alertmanager-release-2.11-test

**Comment by subbarao-meduri** [comment]
/pj-rehearse pull-ci-stolostron-prometheus-release-2.11-react-app-test

**Review by subbarao-meduri — APPROVED** [review]
/lgtm

**Pull request merged**
