### PR TITLE
dashboards-validation: build jsonnet

### PR DESCRIPTION
**Pull request by hongkailiu**
The tools in the image have not been updated for a long time.

I have built the image already. Before building, I have backed up the image:
```
$ oc tag ci/dashboards-validation:latest ci/dashboards-validation:backup --as system:admin
```

/cc @openshift/test-platform 

/hold

Waiting for the rehearsal ...

### CODE REVIEW

**Comment by hongkailiu** [comment]
```console
oc tag ci/dashboards-validation:backup ci/dashboards-validation:latest --as system:admin
Tag ci/dashboards-validation:latest set to ci/dashboards-validation@sha256:edadfff034ce011f251da92e946206f7fcbe874b530e6b2bb5b917bc97d563c7.
```

Recovered image.

**Review by droslean — APPROVED** [review]

**Pull request merged**
