### PR TITLE
Add periodic-interop-testing-cnv-4.18

### PR DESCRIPTION
**Pull request by rabin-io**

### CODE REVIEW

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.18-ocp-cnv-odf-4.18-cnv-odf-tests-aws-upi-ocp418

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.18-ocp-cnv-odf-4.18-cnv-odf-tests-aws-upi-ocp418

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.18-ocp-cnv-odf-4.18-cnv-odf-tests-aws-ipi-ocp418

**Comment by rabin-io** [comment]
@lukas-bednar Can you please take a look, the pipeline seems to be working, it's the T1 test for CNV which fails.

**Comment by lukas-bednar** [comment]
/lgtm

Thank you Rabin!

**Review by lukas-bednar — APPROVED** [review]
/lgtm

**Review by dbasunag — APPROVED** [review]

**Pull request merged**
