### PR TITLE
ci-operator/templates: update installer ami

### PR DESCRIPTION
**Pull request by crawford**
The old AMI was accidentally deregistered.

HVM:        ami-07307c397daf4d02e
SnapshotID: snap-06c2c558005beaa25
S3Object:   s3://openshift-qe-images/rhcos/cloud/rhcos-4.0.5283-aws.vmdk

### CODE REVIEW

**Comment by wking** [comment]
Can you include the metadata like #1344?

/lgtm

**Comment by crawford** [comment]
@wking done.

**Comment by wking** [comment]
@stevekuznetsov, @smarterclayton, we'll need one of you to get this in.

**Pull request merged**
