### PR TITLE
Adding perfscale prod ES creds for e2e

### PR DESCRIPTION
**Pull request by vishnuchalla**
### Description
Adding perfscale prod ES instance to the vault to execute e2e CI tests.

### Testing
Can only be tests using e2e tests in PR: https://github.com/cloud-bulldozer/e2e-benchmarking/pull/721

### CODE REVIEW

**Comment by svetsa-rh** [comment]
@vishnuchalla When i check https://github.com/cloud-bulldozer/e2e-benchmarking/pull/721 I see not all workload tests passed. 
For ex: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/cloud-bulldozer_e2e-benchmarking/721/pull-ci-cloud-bulldozer-e2e-benchmarking-master-e2e-conc-builds-single-node/1838602197189791744 
is reporting:
`Tue Sep 24 16:19:34 UTC 2024 benchmark
Elastic server is not defined, please check`

**Review by afcollins — APPROVED** [review]
COOL

**Pull request merged**
