### PR TITLE
virt, ovn-k: relax the virt suite test selection criteria

### PR DESCRIPTION
**Pull request by maiqueb**
Run all the tests in the virt suite; this prepares the ground for us to run both TP and GA featureset features.

### CODE REVIEW

**Comment by maiqueb** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-release-4.18-e2e-aws-ovn-virt-techpreview pull-ci-openshift-origin-master-e2e-aws-ovn-virt-techpreview

**Review by tssurya — APPROVED** [review]

**Comment by maiqueb** [comment]
> why were we not running all of them and pinning some of them? surprised by that..

Silly mistake of mine. The selected tests were the same though. I just didn't take into account extensibility.

**Pull request merged**
