### PR TITLE
Prow: use --kubeconfig-dir

### PR DESCRIPTION
**Pull request by hongkailiu**
/hold

wait for https://github.com/openshift/release/pull/21208

/cc @stevekuznetsov @alvaroaleman

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Let's try this with some periodic job and test it out to see it works before using it everywhere

**Comment by hongkailiu** [comment]
/hold

let me test it everyone of them locally first.

**Comment by hongkailiu** [comment]
/hold cancel
tested every one of them.

**Pull request merged**
