### PR TITLE
FIO: Bump the pullspec

### PR DESCRIPTION
**Pull request by jhrozek**

### CODE REVIEW

**Comment by rhmdnd** [comment]
AWS error (502) standing up the environment.

/pj-rehearse e2e-aws

**Comment by rhmdnd** [comment]
/pj-rehearse pull-ci-openshift-file-integrity-operator-master-e2e-aws

**Comment by jhrozek** [comment]
/pj-rehearse pull-ci-openshift-file-integrity-operator-master-e2e-aws

**Comment by jhrozek** [comment]
/pj-rehearse pull-ci-openshift-file-integrity-operator-master-e2e-bundle-aws-upgrade

**Comment by jhrozek** [comment]
cool, the previous test ended with 502, now it's 503.

...progress? :-)

/pj-rehearse pull-ci-openshift-file-integrity-operator-master-e2e-aws

**Comment by rhmdnd** [comment]
Looks like the last failure is due to upgrade issues, which have hit us in the past, too.

See https://github.com/openshift/file-integrity-operator/pull/294 and https://github.com/openshift/release/pull/33395 (looks like the upgrade job was ignored)

**Comment by jhrozek** [comment]
> Looks like the last failure is due to upgrade issues, which have hit us in the past, too.
> 
> See [openshift/file-integrity-operator#294](https://github.com/openshift/file-integrity-operator/pull/294) and #33395 (looks like the upgrade job was ignored)

OK, then I'm going to ack the rehearsals so we can proceed with the upgrade PR.

**Comment by jhrozek** [comment]
@rhmdnd I think we still need a LGTM...

**Review by rhmdnd — APPROVED** [review]
Approving without the upgrade test since it's a known issue we've hit in the past. Investigating some ways to fix.

https://github.com/openshift/release/pull/33395

**Pull request merged**
