### PR TITLE
adding single-node and single-node with bootstrap-in-place jobs for 4.8

### PR DESCRIPTION
**Pull request by osherdp**
/hold
/cc @romfreiman @omertuc

### CODE REVIEW

**Comment by osherdp** [comment]
@romfreiman I forgot,
we want slack notifications for any of those?

**Review by alvaroaleman — APPROVED** [review]

**Comment by osherdp** [comment]
thank you @alvaroaleman 
/unhold

**Review by stevekuznetsov — APPROVED** [review]

**Pull request merged**
