### PR TITLE
Update Jaeger version to 1.51.0 in CI jobs and use regex in image tags for substituions.pullSpec.

### PR DESCRIPTION
**Pull request by IshwarKanse**
* Use regex in substitutions.pullSpec and remove the hardcoded version tags from images.

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-jaegertracing-jaeger-operator-main-jaeger-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-jaegertracing-jaeger-operator-main-jaeger-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-jaegertracing-jaeger-operator-main-jaeger-e2e-tests

**Review by rubenvp8510 — APPROVED** [review]

**Pull request merged**
