### PR TITLE
switch over rehearse testing to qe dedicated profiles

### PR DESCRIPTION
**Pull request by jianlinliu**
1. Followup https://github.com/openshift/release/pull/26920 and https://github.com/openshift/ci-tools/pull/2721
2. A typo fix

### CODE REVIEW

**Comment by jianlinliu** [comment]
@Amoghrd This PR will migrate QE's prow ci workload to the QE dedicated cluster profiles. From the job history, it finally works. So pls validate your other existing workflow. 

@yufchang you can continue your aws cluster profiles migration.

@jhou1 @pruan-rht pls help review.

**Comment by jianlinliu** [comment]
@petr-muller can you help review and approve this PR.

**Comment by petr-muller** [comment]
/unassign 

Sorry, we do not review or approve component configuration. Please work with your team.

**Comment by jianlinliu** [comment]
@petr-muller our team already reviewed and approved component part. But in this PR, I combined https://github.com/openshift/release/pull/26946 into this one, so that is why need DPTP team's  review and approved.

```
Needs approval from an approver in each of these files:
[ci-operator/config/openshift/verification-tests/OWNERS](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/verification-tests/OWNERS) [jhou1,jianlinliu]
[ci-operator/jobs/openshift/verification-tests/OWNERS](https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/verification-tests/OWNERS) [jhou1,jianlinliu]
[clusters/app.ci/prow/OWNERS](https://github.com/openshift/release/blob/master/clusters/app.ci/prow/OWNERS)
```

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
