### PR TITLE
Migration non-qe zonal to elastic

### PR DESCRIPTION
**Pull request by jcpowermac**

### CODE REVIEW

**Comment by jcpowermac** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-vsphere-upi-zones-f28 pull-ci-openshift-installer-release-4.16-e2e-vsphere-ovn-upi-zones periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-vsphere-ipi-zones-multisubnets-external-lb-f28

**Comment by jcpowermac** [comment]
/hold 

this pr will need testing

**Comment by jcpowermac** [comment]
rehearse-54278-periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-vsphere-ipi-zones-multisubnets-external-lb-f28 #1811502080460853248


```
 INFO[2024-07-11T20:47:21Z] Acquiring leases for test vsphere-ipi-zones-multisubnets-external-lb-f28: [vsphere-elastic-quota-slice vsphere-multizone-2-quota-slice] 
INFO[2024-07-11T20:47:21Z] Acquired 1 lease(s) for vsphere-elastic-quota-slice: [vsphere-elastic-42] 
INFO[2024-07-11T20:47:21Z] Acquired 2 lease(s) for vsphere-multizone-2-quota-slice: [bcr03a.dal10.1300 bcr03a.dal10.1287] 
INFO[2024-07-11T20:47:21Z] Running multi-stage test vsphere-ipi-zones-multisubnets-external-lb-f28 
INFO[2024-07-11T20:47:25Z] Running multi-stage phase pre   
```

**Review by yuqi-zhang — APPROVED** [review]

**Pull request merged**
