### PR TITLE
Vboulos add obs to opp

### PR DESCRIPTION
**Pull request by vboulos**
This PR adds the Observability tests to the OPP tests suite.
OBS runs after CLC create and before GRC and ALC

### CODE REVIEW

**Comment by vboulos** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.12-interop-openshift-plus-interop-aws

**Review by gparvin — APPROVED** [review]

**Comment by vboulos** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.12-interop-openshift-plus-interop-aws

**Comment by vboulos** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.12-interop-openshift-plus-interop-aws

**Comment by vboulos** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.12-interop-openshift-plus-interop-aws

**Review by gparvin — APPROVED** [review]

**Review by ascerra — APPROVED** [review]

**Pull request merged**
