### PR TITLE
SPLAT-1131: enable techpreview jobs to enable testing of vsphere control plane machineset operator integration 

### PR DESCRIPTION
**Pull request by rvanderp3**

### CODE REVIEW

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-vsphere-zones-techpreview

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-vsphere-zones-techpreview

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-vsphere-zones-techpreview

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-vsphere-zones-techpreview

**Review by r4f4 — COMMENTED** [review]
/approve

**Pull request merged**
