### PR TITLE
PERFSCALE-2753: Add coverage for IBM's HCP 4.13

### PR DESCRIPTION
**Pull request by krishvoor**
This PR adds CP (small) & DP for 4.13 ROSA-HCP jobs

### CODE REVIEW

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.13-nightly-x86-data-path-9nodes

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.13-nightly-x86-data-path-9nodes

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.13-nightly-x86-data-path-9nodes

**Comment by svetsa-rh** [comment]
@krishvoor It looks like this is getting past creating cluster and failing while updating security group. 
Can you try the steps on a manual cluster first and then also add some debug output to the failing step?
It's not clear why it's failing.

**Comment by krishvoor** [comment]
> @krishvoor It looks like this is getting past creating cluster and failing while updating security group. Can you try the steps on a manual cluster first and then also add some debug output to the failing step? It's not clear why it's failing.

As discussed, I am running into these issues while creating a cluster:
```
rosa create cluster --mode auto --cluster-name krishvoor-413 --region us-east-1 --version 4.13.0-0.nightly-2024-02-16-060423 --channel-group nightly --compute-machine-type m5.xlarge --tags TicketID:390 --replicas 3 --hosted-cp --properties provision_shard_id:10746dff-4b03-11ee-b47c-0a580a800afd
I: Using 'xxxx' as billing account
I: To use a different billing account, add --billing-account xxxxxxxxxx to previous command
E: Expected a valid OpenShift version: A valid version number must be specified
Valid versions: 4.15.0-0.nightly-2024-02-16-235514
4.15.0-0.nightly-2024-02-16-180726 4.15.0-0.nightly-2024-02-16-115901
4.15.0-0.nightly-2024-02-14-214710 4.15.0-0.nightly-2024-02-14-163141
4.15.0-0.nightly-2024-02-14-103043 4.15.0-0.nightly-2024-02-14-052317
4.15.0-0.nightly-2024-02-13-231030 4.15.0-0.nightly-2024-02-13-161104
4.15.0-0.nightly-2024-02-13-100737 4.15.0-0.nightly-2024-02-13-040422 
4.15.0-0.nightly-2024-02-12-213938 4.14.0-0.nightly-2024-02-16-191813
4.14.0-0.nightly-2024-02-16-083234 4.14.0-0.nightly-2024-02-16-015828
4.14.0-0.nightly-2024-02-15-160254 4.14.0-0.nightly-2024-02-15-060104
4.14.0-0.nightly-2024-02-14-232330 4.14.0-0.nightly-2024-02-14-173434 
4.14.0-0.nightly-2024-02-14-110648 4.14.0-0.nightly-2024-02-14-034024
4.14.0-0.nightly-2024-02-13-124306 4.14.0-0.nightly-2024-02-13-053554
4.14.0-0.nightly-2024-02-12-215722 4.14.0-0.nightly-2024-02-12-155721
````
Unsure if it is related to the AWS Profile used in the PR `cluster_profile: aws-perfscale-qe`, allowing it to pass past the cluster creation.

**Comment by krishvoor** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.13-nightly-x86-data-path-9nodes

**Comment by krishvoor** [comment]
> > @krishvoor It looks like this is getting past creating cluster and failing while updating security group. Can you try the steps on a manual cluster first and then also add some debug output to the failing step? It's not clear why it's failing.
> 
> @svetsa-rh 👋 As discussed, I am running into these issues while creating a cluster:
> 
> ```
> rosa create cluster --mode auto --cluster-name krishvoor-413 --region us-east-1 --version 4.13.0-0.nightly-2024-02-16-060423 --channel-group nightly --compute-machine-type m5.xlarge --tags TicketID:390 --replicas 3 --hosted-cp --properties provision_shard_id:10746dff-4b03-11ee-b47c-0a580a800afd
> I: Using 'xxxx' as billing account
> I: To use a different billing account, add --billing-account xxxxxxxxxx to previous command
> E: Expected a valid OpenShift version: A valid version number must be specified
> Valid versions: 4.15.0-0.nightly-2024-02-16-235514
> 4.15.0-0.nightly-2024-02-16-180726 4.15.0-0.nightly-2024-02-16-115901
> 4.15.0-0.nightly-2024-02-14-214710 4.15.0-0.nightly-2024-02-14-163141
> 4.15.0-0.nightly-2024-02-14-103043 4.15.0-0.nightly-2024-02-14-052317
> 4.15.0-0.nightly-2024-02-13-231030 4.15.0-0.nightly-2024-02-13-161104
> 4.15.0-0.nightly-2024-02-13-100737 4.15.0-0.nightly-2024-02-13-040422 
> 4.15.0-0.nightly-2024-02-12-213938 4.14.0-0.nightly-2024-02-16-191813
> 4.14.0-0.nightly-2024-02-16-083234 4.14.0-0.nightly-2024-02-16-015828
> 4.14.0-0.nightly-2024-02-15-160254 4.14.0-0.nightly-2024-02-15-060104
> 4.14.0-0.nightly-2024-02-14-232330 4.14.0-0.nightly-2024-02-14-173434 
> 4.14.0-0.nightly-2024-02-14-110648 4.14.0-0.nightly-2024-02-14-034024
> 4.14.0-0.nightly-2024-02-13-124306 4.14.0-0.nightly-2024-02-13-053554
> 4.14.0-0.nightly-2024-02-12-215722 4.14.0-0.nightly-2024-02-12-155721
> ```
> 
> Unsure if it is related to the AWS Profile used in the PR `cluster_profile: aws-perfscale-qe`, allowing it to pass past the cluster creation.

@svetsa-rh Did you get a chance to look at this?

**Comment by svetsa-rh** [comment]
@krishvoor will get back to you on this.

**Comment by svetsa-rh** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.13-nightly-x86-data-path-9nodes 

Retrying running job with new profiles in place.

**Pull request closed without merging**
