### PR TITLE
Move infra and install_yamls prow jobs over from 4.14 to 4.15 Hive cluster

### PR DESCRIPTION
**Pull request by bshewale**

### CODE REVIEW

**Comment by lewisdenny** [comment]
#/pj-rehearse pull-ci-openstack-k8s-operators-infra-operator-main-infra-operator-build-deploy-kuttl

**Comment by bshewale** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-infra-operator-main-infra-operator-build-deploy-kuttl

**Comment by frenzyfriday** [comment]
/lgtm

the pjrehearse jobs look green

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-install_yamls-main-install-yamls-deploy

**Comment by viroel** [comment]
/approve

patch lgtm

**Review by lewisdenny — APPROVED** [review]
/unhold

**Pull request merged**
