### PR TITLE
Bump benchmarking to v2.2.3

### PR DESCRIPTION
**Pull request by rsevilla87**
Let's bump to the most recent which includes new jobSummary document format (flatten metadata among other changes)

### CODE REVIEW

**Comment by vishnuchalla** [comment]
can we take this: https://github.com/openshift/release/pull/54893 in first please? Been open for a while

**Comment by rsevilla87** [comment]
> can we take this: #54893 in first please? Been open for a while

yeah, no worries, we can merge this later

**Comment by rsevilla87** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-control-plane-3nodes

**Comment by rsevilla87** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-arm-control-plane-24nodes

**Comment by rsevilla87** [comment]
Dashboards worked correctly with new metrics formatting 🥳

**Pull request merged**
