### PR TITLE
retester: Add ComplianceAsCode/content and ComplianceAsCode/compliance-operator

### PR DESCRIPTION
**Pull request by jhrozek**
Adds the ComplianceAsCode/content and ComplianceAsCode/compliance-operator to
the retester config. These projects test a large number of compliance profiles,
so maually checking for cluster installation failures and similar flakes is labour
intensive.

### CODE REVIEW

**Comment by rhmdnd** [comment]
Will we still be able to find flakes in CI logs?

**Comment by jhrozek** [comment]
> Will we still be able to find flakes in CI logs?

Hmm, really good question, I admit I didn't think about it, but it seems that the answer is yes. If you look at e.g. [this FIO PR]( https://github.com/openshift/file-integrity-operator/pull/317) that was retested, you can go to the [artifacts](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_file-integrity-operator/317/pull-ci-openshift-file-integrity-operator-master-e2e-aws/) page to see the previous runs

**Comment by rhmdnd** [comment]
> Hmm, really good question, I admit I didn't think about it, but it seems that the answer is yes. If you look at e.g. [this FIO PR](https://github.com/openshift/file-integrity-operator/pull/317) that was retested, you can go to the [artifacts](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_file-integrity-operator/317/pull-ci-openshift-file-integrity-operator-master-e2e-aws/) page to see the previous runs

The main reason why I'm asking is if it will still be apparent (or at least a little painful) when things are failing. For example, if there are transient issues in the tests, I'd like to know so we can find those and fix them.

I do think something like this is great for dealing with underlying cloud provider issues (AWS outages we have a lot less control over).

**Comment by jhrozek** [comment]
On Thu, Mar 09, 2023 at 11:43:56AM -0800, Lance Bragstad wrote:
> > Hmm, really good question, I admit I didn't think about it, but it seems that the answer is yes. If you look at e.g. [this FIO PR](https://github.com/openshift/file-integrity-operator/pull/317) that was retested, you can go to the [artifacts](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_file-integrity-operator/317/pull-ci-openshift-file-integrity-operator-master-e2e-aws/) page to see the previous runs
> 
> The main reason why I'm asking is if it will still be apparent (or at least a little painful) when things are failing. For example, if there are transient issues in the tests, I'd like to know so we can find those and fix them.

You should see messages like this:
https://github.com/openshift/file-integrity-operator/pull/317#issuecomment-1458312242

**Review by jmguzik — APPROVED** [review]

**Pull request merged**
