### PR TITLE
prom-label-proxy: run tests + check vendoring

### PR DESCRIPTION
**Pull request by simonpasquier**

### CODE REVIEW

**Comment by simonpasquier** [comment]
/hold

https://github.com/openshift/prom-label-proxy/pull/14 is needed first

**Comment by paulfantom** [comment]
/lgtm

unhold when ready :)

**Comment by paulfantom** [comment]
Seems like it needs some modifications in `openshift-prom-label-proxy-master-presubmits.yaml` file. Look at https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/6473/pull-ci-openshift-release-master-generated-config/13523

**Pull request merged**
