### PR TITLE
Add driver toolkit e2e periodic and master presubmit test

### PR DESCRIPTION
**Pull request by dagrayvid**
This PR will add the e2e test from https://github.com/openshift/driver-toolkit/pull/66 as a periodic test on 4.7, 4.8, 4.9, 4.10, and 4.11. It will run every 12 hours on 4.7 and every 6 hours on 4.8+. It is also an optional presubmit test for the openshift/driver-toolkit repo.

/cc @qbarrand @yevgeny-shnaidman @kpouget

### CODE REVIEW

**Comment by dagrayvid** [comment]
/hold

want to see a successful run...

**Comment by kpouget** [comment]
looks good @dagrayvid , thanks

/lgtm

**Comment by kpouget** [comment]
interesting failure is there:

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/24001/rehearse-24001-pull-ci-openshift-driver-toolkit-master-e2e-aws-driver-toolkit/1464052954045616128/artifacts/e2e-aws-driver-toolkit/test/

the others fail because of git `release-*` branches not being synced with `master`

**Comment by kpouget** [comment]
@dagrayvid, just FYI,

see what I like with ansible:

```
+ echo '## TEST: Checking imagestream/driver-toolkit ##'
## TEST: Checking imagestream/driver-toolkit ##
+ test_imagestream
+ oc get imagestream/driver-toolkit -n openshift -o yaml
+ echo
```
what happens to the output ??
```
# Check if driver-toolkit imagestream is available
test_imagestream() {
    oc get imagestream/driver-toolkit -n openshift -o yaml > ${ARTIFACT_DIR}/driver-toolkit-imagestream.yaml
}
```
ah, it's [there](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/24001/rehearse-24001-pull-ci-openshift-driver-toolkit-master-e2e-aws-driver-toolkit/1464052954045616128/artifacts/e2e-aws-driver-toolkit/test/artifacts/driver-toolkit-imagestream.yaml)

---

whereas ansible would give:
```
 roles/gpu_operator_bundle_from_commit/tasks/build_helper.yml:44
TASK: gpu_operator_bundle_from_commit : Store the logs of the helper image build (debug)
<command> oc logs bc/helper-image-builder -n gpu-operator-ci-utils > /logs/artifacts/000__gpu_operator__bundle_from_commit/helper-image-builder.log
```

**Comment by kpouget** [comment]
... and the issue is:
```
+++ oc debug node/ip-10-0-170-155.ec2.internal --quiet -- cat /host/etc/os-release
Error from server (NotFound): namespaces "ci-op-lpc2k6m0" not found
```
==> Prow test do not support using the implicit namespace *ever*, so this command (and others) should have `-n default` or `-n openshift`

**Comment by kpouget** [comment]
thanks @dagrayvid, looks good!
/lgtm

**Pull request merged**
