### PR TITLE
Set up image mirroring for ocs-operator nightly images

### PR DESCRIPTION
**Pull request by kshlm**
Depends upon #5371

### CODE REVIEW

**Comment by kshlm** [comment]
/hold
Holding till #5371 is merged.

**Comment by davidvossel** [comment]
/hold cancel

#5371 is merged now. This pr looks good to me, but we'll need someone with the right permissions to review this initial PR since we aren't in a OWNERS list yet.

**Comment by stevekuznetsov** [comment]
Please update the README as well

**Pull request merged**
