### PR TITLE
Store prow config in bare yaml files

### PR DESCRIPTION
**Pull request by 0xmichalis**
This is still the recommended way of storing config in VCS, even in
the presence of ConfigMaps.

/assign @stevekuznetsov 

Signed-off-by: Michalis Kargakis <mkargaki@redhat.com>

### CODE REVIEW

**Comment by kargakis** [comment]
@stevekuznetsov [?w=1](https://github.com/openshift/release/pull/162/files?w=1) is your friend.

**Comment by stevekuznetsov** [comment]
Why?

**Comment by stevekuznetsov** [comment]
This breaks my `oc apply -f ` happy place

**Comment by kargakis** [comment]
All things expect to read from a location in the filesystem, very few work with configmaps. Testing locally, and any tool that needs the prow config as its input (`mkpj`, and there are more to come) are the main reasons.

**Comment by kargakis** [comment]
Also, the `updateconfig` plugin expects the config to be a plain file.

**Comment by stevekuznetsov** [comment]
OK. can we pair this with the plugin so we don't lose the flow

**Comment by kargakis** [comment]
Strictly speaking, the flow doesn't change with this PR. Furthermore, the plugin is a big improvment over what's happening today. I am all for enabling it but we will need changes upstream to make the [location](https://github.com/kubernetes/test-infra/blob/b4fe4eda5931ddb3c43ebfa67932b4303d7e532f/prow/plugins/updateconfig/updateconfig.go#L31-L32) of the configs configurable.

**Comment by stevekuznetsov** [comment]
If we merge this I can't use `oc apply` to deploy the `ConfigMap`, right? Lets not break that until we can turn on the plugin and use it to update things.

**Comment by kargakis** [comment]
> If we merge this I can't use oc apply to deploy the ConfigMap, right?

How about `make prow-config`? Anyway, the plugin is up and running?

**Comment by kargakis** [comment]
> If we merge this I can't use oc apply to deploy the ConfigMap, right?

How about `make prow-config`? Anyway, the plugin is up and running.

**Pull request merged**
