### PR TITLE
aws-console-ref: use latest upi-installer

### PR DESCRIPTION
**Pull request by rphillips**
Fixes getting console logs by setting C.utf8 as the locale.

### CODE REVIEW

**Comment by rphillips** [comment]
/pjrehearse pull-ci-openshift-machine-config-operator-release-4.14-e2e-aws-disruptive

**Comment by rphillips** [comment]
/pj-rehearse pull-ci-openshift-machine-config-operator-release-4.14-e2e-aws-disruptive

**Comment by rphillips** [comment]
/pj-rehearse pull-ci-openshift-machine-config-operator-release-4.14-e2e-aws-disruptive

**Comment by rphillips** [comment]
/pj-rehearse pull-ci-openshift-machine-config-operator-release-4.14-e2e-aws-disruptive

**Comment by rphillips** [comment]
/pj-rehearse pull-ci-openshift-machine-config-operator-release-4.14-e2e-aws-disruptive

**Comment by rphillips** [comment]
/pj-rehearse pull-ci-openshift-machine-config-operator-release-4.14-e2e-aws-disruptive
/pj-rehearse periodic-ci-openshift-release-master-ci-4.11-e2e-aws

**Comment by rphillips** [comment]
/pj-rehearse pull-ci-openshift-machine-config-operator-release-4.14-e2e-aws-disruptive
/pj-rehearse periodic-ci-openshift-release-master-ci-4.11-e2e-aws

**Comment by rphillips** [comment]
/pj-rehearse pull-ci-openshift-machine-config-operator-release-4.11-e2e-aws-disruptive

**Comment by rphillips** [comment]
/pj-rehearse pull-ci-openshift-machine-config-operator-release-4.11-e2e-aws-disruptive
/pj-rehearse pull-ci-openshift-machine-config-operator-release-4.14-e2e-aws-disruptive

**Comment by rphillips** [comment]
/pj-rehearse pull-ci-openshift-machine-config-operator-release-4.11-e2e-aws-disruptive
/pj-rehearse pull-ci-openshift-machine-config-operator-release-4.14-e2e-aws-disruptive

**Review by wking — APPROVED** [review]
/lgtm

**Pull request merged**
