### PR TITLE
update CCCMO unit tests to use 200m cpu request

### PR DESCRIPTION
**Pull request by elmiko**
this change is being proposed to fix some issues that are arising when running the envtest based unit tests.

### CODE REVIEW

**Comment by elmiko** [comment]
/pj-rehearse pull-ci-openshift-cluster-cloud-controller-manager-operator-release-4.10-unit
/pr-rehearse pull-ci-openshift-cluster-cloud-controller-manager-operator-release-4.11-unit
/pr-rehearse pull-ci-openshift-cluster-cloud-controller-manager-operator-release-4.12-unit
/pr-rehearse pull-ci-openshift-cluster-cloud-controller-manager-operator-release-4.13-unit
/pr-rehearse pull-ci-openshift-cluster-cloud-controller-manager-operator-release-4.14-unit
/pr-rehearse pull-ci-openshift-cluster-cloud-controller-manager-operator-release-4.15-unit
/pr-rehearse pull-ci-openshift-cluster-cloud-controller-manager-operator-release-master-unit

**Comment by elmiko** [comment]
/pr-rehearse pull-ci-openshift-cluster-cloud-controller-manager-operator-release-4.11-unit pull-ci-openshift-cluster-cloud-controller-manager-operator-release-4.12-unit pull-ci-openshift-cluster-cloud-controller-manager-operator-release-4.13-unit pull-ci-openshift-cluster-cloud-controller-manager-operator-release-4.14-unit pull-ci-openshift-cluster-cloud-controller-manager-operator-release-4.15-unit pull-ci-openshift-cluster-cloud-controller-manager-operator-release-master-unit

**Comment by elmiko** [comment]
after some testing on the repo, i am restricting this PR to change the 4.13+ release branches. it appears that 4.12 and earlier are not affected.

**Comment by elmiko** [comment]
/pr-rehearse pull-ci-openshift-cluster-cloud-controller-manager-operator-release-master-unit pull-ci-openshift-cluster-cloud-controller-manager-operator-release-4.13-unit

**Comment by elmiko** [comment]
/pj-rehearse pull-ci-openshift-cluster-cloud-controller-manager-operator-release-4.13-unit

**Comment by elmiko** [comment]
/pr-rehearse pull-ci-openshift-cluster-cloud-controller-manager-operator-release-master-unit

**Comment by elmiko** [comment]
/pr-rehearse pull-ci-openshift-cluster-cloud-controller-manager-operator-release-master-unit

**Review by damdo — COMMENTED** [review]
/lgtm

**Pull request merged**
