### PR TITLE
Hive: Add mce-2.4 jobs

### PR DESCRIPTION
**Pull request by 2uasimojo**

### CODE REVIEW

**Comment by suhanime** [comment]
Okay basic tests work

/lgtm

**Comment by 2uasimojo** [comment]
Oh, that's not right -- it retriggered all my jobs and lost my progress. https://issues.redhat.com/browse/DPTP-3670

**Comment by 2uasimojo** [comment]
Okay so now why didn’t this auto-ack?

/pj-rehearse ack

**Pull request merged**
