### PR TITLE
Skip meta-operator go.mod changes if operator not integrated.

### PR DESCRIPTION
**Pull request by Sandeepyadav93**
Some operators are not integrated in meta operator yet, skip changes in meta-operator go.mod for those operators.

### CODE REVIEW

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-heat-operator-main-heat-operator-build

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-heat-operator-main-heat-operator-build

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-heat-operator-main-heat-operator-build

**Review by stuggi — APPROVED** [review]
/lgtm

**Pull request merged**
