### PR TITLE
Include ComplianceAsCode/content repo in testing infra

### PR DESCRIPTION
**Pull request by JAORMX**
This sets up the necessary files to start testing the
[ComplianceAsCode/content](https://github.com/ComplianceAsCode/content) repo.

This repo is dedicated on building security content in general. Existing
content already includes RHEL, Fedora, SUSE, OpenStack, and others.
Recently, OpenShift has been included. In order to better build content
for OpenShift, we'd like to start testing the OpenShift-related content
as it's being added.

So this hooks up the needed testing infrastructure so we can test the
content in a live deployment.

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/uncc
Pease re-assign me once this is not WIP anymore, currently its spamming my notifications too much.

**Comment by JAORMX** [comment]
huh, that's weird. When I initially ran make jobs a build01 job was created. Now that the job got re-ran, it complains about that job.

**Pull request merged**
