### PR TITLE
Remove OKD promote jobs for 4.7 -> 4.9

### PR DESCRIPTION
**Pull request by vrutkovs**
Currently these are no-op:
* final images don't have FCOS version recorded, as its being built from scratch
* manifest-lock is not being auto-updated
* these jobs are not being autogenerated from workflows
* additional tests (i.e. ovirt) is not being run on release acceptance, which leads to regressions

The alternative to that is regular submodule bumping via PRs

### CODE REVIEW

**Comment by LorbusChris** [comment]
For now, this seems reasonable to me. We should eventually look into making the okd-machine-os build process run on Prow with gangplank, and automating things there.
/lgtm

**Comment by vrutkovs** [comment]
> We should eventually look into making the okd-machine-os build process run on Prow with gangplank, and automating things there.

Right, the main issues with current process are
a) we have to set branch in this job and okd-machine-os Dockerfile. 4.9/4.8 is currently out of sync, so promote jobs have messed up machine-os-content for 4.8
b) we pin to particular fedora-coreos-config/openshift-os commit, so we still have to rely on manual steps to update these anyway.

**Comment by LorbusChris** [comment]
:+1: I think what'd be great for this would be an OKD e2e on `fedora-coreos-config` and `os` which takes `okd-machine-os` and bumps their respective submodule to the PR head. And then ideally have a bot open PRs for bumping the submodule on `okd-machine-os` after merges.

**Pull request merged**
