### PR TITLE
update router-http health check

### PR DESCRIPTION
**Pull request by lihongan**
HTTP route doesn't work via the external LB, we should use plain http health check for `router-http`

### CODE REVIEW

**Comment by lihongan** [comment]
/hold
need a test

**Comment by lihongan** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-vsphere-ipi-multisubnets-elb-usermanaged-f28

**Comment by lihongan** [comment]
/unhold
both HTTP and HTTPS route are working well
```
sh-4.4$ curl http://ingress-canary-openshift-ingress-canary.apps.ci-op-b6h2wwqv-83fe6.vmc-ci.devcluster.openshift.com
Healthcheck requested

sh-4.4$ curl https://canary-openshift-ingress-canary.apps.ci-op-b6h2wwqv-83fe6.vmc-ci.devcluster.openshift.com -k
Healthcheck requeste
```

**Comment by lihongan** [comment]
cc @zhaozhanqi @jianlinliu

**Comment by zhaozhanqi** [comment]
/lgtm 
thanks

**Pull request merged**
