### PR TITLE
add new base-openstack repositories in ironic-ipa-downloader

### PR DESCRIPTION
**Pull request by elfosardo**
Testing new base image with openstack repos

### CODE REVIEW

**Comment by smarterclayton** [comment]
Hrm, I’ll have to check whether your service is deployed

**Comment by elfosardo** [comment]
@smarterclayton hi!
We'd really like to unblock this as currently it's preventing to merge PRs in the ironic-ipa-downloader repo.
Also this change will need to be applied to all other ironic images at the earliest time possible to be able to correctly test the installation of openstack packages.
Can you please tell us if there's anything we could do to help ?
Thanks!

FYI @juliakreger @hardys @russellb

**Comment by smarterclayton** [comment]
Your rehearse jobs are failing, probably because the mirror server isn’t started.  I’ll have to take a look to see why.

**Comment by smarterclayton** [comment]
You should retest your images - the openstack RPM mirror app has been
deployed.

**Comment by elfosardo** [comment]
Thanks @smarterclayton

**Comment by elfosardo** [comment]
seems to work \o/

**Pull request merged**
