### PR TITLE
Report exit code back to ofcir

### PR DESCRIPTION
**Pull request by derekhiggins**
will allow us to easy find out if a specific BM env is misbehaving

### CODE REVIEW

**Comment by derekhiggins** [comment]
/pr-rehearse periodic-ci-openshift-release-master-nightly-4.11-e2e-metal-ipi-bm

**Comment by stbenjam** [comment]
/pr-rehearse periodic-ci-openshift-release-master-nightly-4.11-e2e-metal-ipi-bm

**Comment by stbenjam** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.11-e2e-metal-ipi-bm

Typo in the original rehearse

**Comment by derekhiggins** [comment]
> ci/rehearse/periodic-ci-openshift-release-master-nightly-4.11-e2e-metal-ipi-bm — Job failed.

Associated entry in ofcir logs 
[GIN] 2023/09/12 - 19:28:13 | 200 |   16.870494ms |   10.129.157.21 | DELETE   "/v1/ofcir/cir-0078?name=rehearse-43263-periodic-ci-openshift-release-master-nightly-4.11-e2e-metal-ipi-bm/1701650031573995520&rv=6"

**Pull request merged**
