### PR TITLE
OCPBUGS-38844: cert-rotation: set time on nodes when shutting down nodes

### PR DESCRIPTION
**Pull request by vrutkovs**
Multiple fixes for shutdown tests:
* Ensure that chronyd is masked (so that it won't start on boot via other services)
* Clean up logged entries
* Approve CSRs once for HA clusters
* Always copy `lb-ext.kubeconfig` as it may not change when nodes are shut down for short period
* Shutdown machines simultaneously 

Includes https://github.com/openshift/release/pull/56221

### CODE REVIEW

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-90d-age-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-90d-age-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-90d-age-90d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-90d-age-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-ha-cert-rotation-shutdown-60d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-ha-cert-rotation-shutdown-60d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-90d-age-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-ha-cert-rotation-shutdown-60d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-90d-age-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-ha-cert-rotation-shutdown-60d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-90d-age-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-ha-cert-rotation-shutdown-60d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-90d-age-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-ha-cert-rotation-shutdown-60d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-90d-age-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-ha-cert-rotation-shutdown-60d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-90d-age-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-ha-cert-rotation-shutdown-60d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-sno-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-sno-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-sno-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-sno-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-sno-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-sno-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-sno-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-sno-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-sno-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-sno-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-sno-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-sno-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-sno-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-sno-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-sno-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-sno-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-sno-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-sno-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-sno-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-sno-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-sno-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-sno-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-sno-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-sno-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-ha-cert-rotation-shutdown-90d p periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-sno-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-ha-cert-rotation-shutdown-90d p periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-sno-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-sno-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-sno-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ovn-ha-cert-rotation-shutdown-90d periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-ha-cert-rotation-shutdown-90d

**Review by dinhxuanvu — COMMENTED** [review]
/lgtm

**Pull request merged**
