### PR TITLE
Updating cli image for mirroring & removing unused periodics

### PR DESCRIPTION
**Pull request by deepsm007**
- Updating cli image 
- removing unused periodics (tekton, toolchain, codeready-toolchain, open-cluster-management) with missing mapping files

/cc @openshift/test-platform @hongkailiu 

/hold for the rehearsal...

### CODE REVIEW

**Comment by deepsm007** [comment]
Dry run looks good:
knative - https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/51354/rehearse-51354-periodic-image-mirroring-knative/1783450844851605504 
red-hat-storage - https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/51354/rehearse-51354-periodic-image-mirroring-red-hat-storage/1783450844696416256 
openshift - https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/51354/rehearse-51354-periodic-image-mirroring-openshift/1783450844792885248

**Review by hongkailiu — APPROVED** [review]

**Pull request merged**
