### PR TITLE
PR to promote the ALC image

### PR DESCRIPTION
**Pull request by vboulos**

### CODE REVIEW

**Comment by ascerra** [comment]
pull-ci-stolostron-application-ui-test-release-2.7-images

**Comment by ascerra** [comment]
/pj-rehearse pull-ci-stolostron-application-ui-test-release-2.7-images

**Review by smithbw88 — APPROVED** [review]
LGTM

**Comment by ascerra** [comment]
/pj-rehearse pull-ci-stolostron-application-ui-test-release-2.7-images

**Pull request merged**
