### PR TITLE
Move remaining blocking 4.8 release jobs out of api.ci

### PR DESCRIPTION
**Pull request by petr-muller**
/hold

These are the remaining blocking 4.8 jobs... if these go well, I will move all informing ones.
/cc @hongkailiu

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
```
 time="2021-02-10T14:15:24Z" level=error msg="Failed to get resolved config for test" error="failed resolve ReleaseBuildConfiguration: Failed resolve MultiStageTestConfiguration: no workflow named openshift-upgrade-$(CLUSTER_TYPE)" org=openshift repo=release 
```

**Comment by petr-muller** [comment]
Yeah I saw that, `pj-rehearse` does not perform substitution in inline configs.

**Comment by petr-muller** [comment]
@stevekuznetsov I froze the envvars into the inline config to avoid the problem, PTAL

**Comment by petr-muller** [comment]
/hold

```
The pod could not start because it could not mount the volume "appci-release-bot-credentials": secret "build-farm-credentials" not found
```

**Comment by petr-muller** [comment]
I will rebase this on top of https://github.com/openshift/release/pull/15914 and https://github.com/openshift/release/pull/15906, no point of doing these modifications per job.

**Comment by petr-muller** [comment]
/hold cancel

The jobs seem to give signal as expected

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
