### PR TITLE
Adding aro 416

### PR DESCRIPTION
**Pull request by paigerube14**
Adding 4.16 support on aro

### CODE REVIEW

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-aro-416

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-aro-416

**Comment by paigerube14** [comment]
Seeing same issue in first run of aro that is on the 4.15 run: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-redhat-chaos-prow-scripts-main-4.15-nightly-krkn-hub-tests-aro-415/1830516234798501888

```
+ python3.9 /home/krkn/kraken/run_kraken.py --config=/tmp/pod_scenario_config.yaml -o /tmp/report.out --junit-testcase 'Pod scenarios' --junit-testcase-path /logs/artifacts --junit-testcase-version '"4.13.40"'
/usr/local/lib/python3.9/site-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
/usr/local/lib/python3.9/site-packages/paramiko/transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,
 _              _              
| | ___ __ __ _| | _____ _ __  
| |/ / '__/ _` | |/ / _ \ '_ \ 
|   <| | | (_| |   <  __/ | | |
|_|\_\_|  \__,_|_|\_\___|_| |_|
                               
2024-09-02 09:53:01,946 [INFO] Starting kraken
2024-09-02 09:53:01,959 [INFO] Initializing client to talk to the Kubernetes cluster
2024-09-02 09:53:01,959 [INFO] Generated a uuid for the run: 240b7be6-58c7-4c0f-b036-8d806f750fbd
2024-09-02 09:53:08,038 [INFO] Fetching cluster info
2024-09-02 09:53:08,379 [INFO] 4.13.40
2024-09-02 09:53:08,381 [INFO] Server URL: https://api.w6nmchjy.southcentralus.aroapp.io:6443/
2024-09-02 09:53:08,381 [INFO] Daemon mode not enabled, will run through 1 iterations
2024-09-02 09:53:08,381 [INFO] Executing scenarios for iteration 0
2024-09-02 09:53:08,383 [INFO] scenario /tmp/pod_scenario.yaml
2024-09-02 09:53:08,465 [INFO] waiting 4 seconds for pod recovery, pod label selector: app=ovnkube-control-plane namespace pattern: openshift-ovn-kubernetes
2024-09-02 09:53:08,714 [INFO] {
	"output_id": "error",
	"output_data": {
		"error": "Not enough pods match the criteria, expected 1 but found only 0 pods"
	}
}
2024-09-02 09:53:08,714 [ERROR] scenario exception: Step 0 in /tmp/pod_scenario.yaml (kill-pods) failed
2024-09-02 09:53:08,714 [ERROR] scenario: /tmp/pod_scenario.yaml failed with exception: <class 'Exception'> file: /home/krkn/kraken/kraken/plugins/__init__.py line: 273
2024-09-02 09:53:08,715 [INFO] Checking for critical alerts firing post chaos
2024-09-02 09:53:08,888 [INFO] No critical alerts are firing!!
```

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-aro-node

**Comment by paigerube14** [comment]
@chaitanyaenr @shahsahil264 PTAL passing job here: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/56715/rehearse-56715-periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-tests-aro-416/1834674311441420288

The node scenarios I dont think we are properly able to run power outage or node scenarios because of access limitations
```
2024-09-16 14:17:45,888 [ERROR] Failed to stop node instance ci-op-p1qms117-fd6d6-4jd8w-master-1. Encountered following exception: (DenyAssignmentAuthorizationFailed) The client '040de9bb-8ff3-47da-9006-a38b728e0bad' with object id '040de9bb-8ff3-47da-9006-a38b728e0bad' has permission to perform action 'Microsoft.Compute/virtualMachines/powerOff/action' on scope '/subscriptions/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/resourceGroups/ARO-PR4FWL9I/providers/Microsoft.Compute/virtualMachines/ci-op-p1qms117-fd6d6-4jd8w-master-1'; however, the access is denied because of the deny assignment with name '8601b906-f1dc-537f-9c31-07469d6614e5' and Id '8601b906f1dc537f9c3107469d6614e5' at scope '/subscriptions/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/resourcegroups/aro-pr4fwl9i'.
Code: DenyAssignmentAuthorizationFailed
```

**Review by shahsahil264 — APPROVED** [review]

**Pull request merged**
