### PR TITLE
Sync Serverless CI config/

### PR DESCRIPTION
**Pull request by serverless-qe**

### CODE REVIEW

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-release-next-416-images

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-release-next-415-images

**Comment by creydr** [comment]
/pj-rehearse pull-ci-openshift-knative-eventing-release-next-412-images

**Comment by pierDipi** [comment]
/retest

it seems stuck?

**Pull request merged**
