### PR TITLE
cluster-etcd-operator: move agnostic tests to aws for 4.7

### PR DESCRIPTION
**Pull request by hexfusion**
gcp has been horrible lately going to try aws...

cc @marun @ironcladlou @retroflexer

### CODE REVIEW

**Comment by hexfusion** [comment]
```
Installing from release registry.build01.ci.openshift.org/ci-op-dttc4608/release@sha256:f623fc83e489d8c67498a67149f10879f00f6c5aa059c50c9f0746cb8b8eaca7
[0G[2K[1;92m? [0m[1;99mService Account (absolute path to file or JSON content) [0m[36m[Enter 2 empty lines to finish][0m
[?25l7[999;999f[6n[6nlevel=fatal msg=failed to fetch Master Machines: failed to load asset "Install Config": failed to get session: failed to load credentials: EOF
2020/12/05 17:22:45 Failed to upload $KUBECONFIG: timed out waiting for the condition: <nil>
error: failed to execute wrapped command: exit status 1
```
hmm
/retest

**Comment by hexfusion** [comment]
cc @wking

**Comment by ironcladlou** [comment]
/lgtm

Holding to give @wking and opportunity to weigh in (https://github.com/openshift/release/pull/14111#issuecomment-739375671)
/hold

**Comment by hexfusion** [comment]
/hold cancel

ping to wking was visability

**Pull request merged**
