### PR TITLE
Add periodic compliance jobs for OpenShift 4.15

### PR DESCRIPTION
**Pull request by rhmdnd**
Let's start running all compliance jobs on OpenShift 4.15 so we have a
better understanding of what the compliance posture is on that version.

### CODE REVIEW

**Comment by rhmdnd** [comment]
Looks like we do have some legitimate failures with fedramp high on 4.15.

**Comment by rhmdnd** [comment]
/pj-rehearse periodic-ci-ComplianceAsCode-content-master-4.15-e2e-aws-rhcos4-moderate-weekly
/pj-rehearse periodic-ci-ComplianceAsCode-content-master-4.15-e2e-aws-ocp4-e8-weekly

**Comment by rhmdnd** [comment]
Rehearsal failures are being tracked separately as we fix CI issues. Otherwise this is working as expected using the new CI profile and not running into service provider quota issues.

**Comment by rhmdnd** [comment]
@Vincent056 @yuumasato this should be ready for another look.

**Review by yuumasato — APPROVED** [review]
/lgtm

**Pull request merged**
