### PR TITLE
odo: add job for benchmark test

### PR DESCRIPTION
**Pull request by kadel**
add a new job for benchmark test

see https://github.com/openshift/odo/pull/1841

### CODE REVIEW

**Comment by amitkrout** [comment]
ping @mohammedzee1000

**Comment by amitkrout** [comment]
@kadel @mohammedzee1000 I don't see the ```e2e scenario``` and ```integration``` test job. Ideally it should reflect here, right ?

**Comment by mohammedzee1000** [comment]
It is there `ci/rehearse/openshift/odo/master/benchmark`
/lgtm

**Pull request merged**
