### PR TITLE
cincinnati-operator: run scorecard tests

### PR DESCRIPTION
**Pull request by hongkailiu**
We will create a new make target to simplify the cmd. But this is good enough to verify https://github.com/openshift/cincinnati-operator/pull/200

### CODE REVIEW

**Comment by hongkailiu** [comment]
/pj-rehearse pull-ci-openshift-cincinnati-operator-master-scorecard

**Comment by hongkailiu** [comment]
/pj-rehearse pull-ci-openshift-cincinnati-operator-master-scorecard

**Comment by hongkailiu** [comment]
/pj-rehearse pull-ci-openshift-cincinnati-operator-master-scorecard

**Comment by hongkailiu** [comment]
/pj-rehearse pull-ci-openshift-cincinnati-operator-master-scorecard

**Comment by hongkailiu** [comment]
/pj-rehearse pull-ci-openshift-cincinnati-operator-master-scorecard

**Comment by hongkailiu** [comment]
/pj-rehearse pull-ci-openshift-cincinnati-operator-master-scorecard

**Comment by hongkailiu** [comment]
/pj-rehearse pull-ci-openshift-cincinnati-operator-master-scorecard

**Comment by hongkailiu** [comment]
/pj-rehearse pull-ci-openshift-cincinnati-operator-master-scorecard

**Comment by hongkailiu** [comment]
/pj-rehearse pull-ci-openshift-cincinnati-operator-master-scorecard

**Review by wking — APPROVED** [review]
/lgtm

**Pull request merged**
