### PR TITLE
Add coreos-assembler 4.8 job

### PR DESCRIPTION
**Pull request by ravanelli**
Signed-off-by: Renata Ravanelli <rravanel@redhat.com>

### CODE REVIEW

**Review by darkmuggle — APPROVED** [review]
/lgtm

**Comment by cgwalters** [comment]
OK so right now, the coreos-assembler sanity jobs only run a build and unit test of coreos-assembler itself.

Particularly for the branched coreos-assembler, what makes the most sense is to test RHCOS.  But actually, I'd take a step back and say that in fact what we want to start with is testing RHCOS on the *main* coreos-assembler branch and then for `rhcos-X` branches on coreos-assembler we only test RHCOS?

The problem with *that* though is that unfortunately right now due to https://github.com/openshift/os/issues/552 we actually can't build RHCOS from cosa master.  I may try to pick that up.

OK anyways let me try to answer the question around how the current RHCOS Prow CI works.  Take a look at this:
https://github.com/openshift/release/blob/1ef72a4334f26be8c63623624025d08463834f67/ci-operator/config/openshift/os/openshift-os-master.yaml#L43

Prow is a "container-native" buildsystem, so what happens when a PR comes in is it builds an image from
https://github.com/openshift/os/blob/master/ci/Dockerfile
As the comment there says, we're making an image that is just the combination of (openshift/os source code, coreos-assembler).

Then, the glue in the release job above says to run the [build-test-qemu.sh script](https://github.com/openshift/os/blob/master/ci/build-test-qemu.sh) from inside that container.  That's where all the real work happens.

**Pull request merged**
