### PR TITLE
OCPCLOUD-2012: Add azure-manual-oidc workload to cluster-capi-operator

### PR DESCRIPTION
**Pull request by abutcher**
Requires https://github.com/openshift/cloud-credential-operator/pull/581 to enable `ccoctl azure create-all --enable-tech-preview`.

Will enable testing of Azure workload identity credentials generation for https://github.com/openshift/cluster-capi-operator/pull/124.

/hold

### CODE REVIEW

**Comment by jstuever** [comment]
/pj-rehears pull-ci-openshift-cloud-credential-operator-master-e2e-azure-manual-oidc

**Comment by jstuever** [comment]
/pj-rehearse pull-ci-openshift-cloud-credential-operator-master-e2e-azure-manual-oidc

**Comment by jstuever** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-operator-main-e2e-azure-manual-oidc

**Comment by jstuever** [comment]
Rehearsals passed on `pull-ci-openshift-cloud-credential-operator-master-e2e-azure-manual-oidc`, which tests all of the operators. I don't see a purpose in rehearsing on the individual operator repos. I recommend we apply `rehearse-ack`.

**Comment by abutcher** [comment]
/pj-rehearse pull-ci-openshift-cloud-credential-operator-master-e2e-azure-manual-oidc

**Comment by abutcher** [comment]
/hold
for rehearse signal

**Comment by abutcher** [comment]
Installation succeeded in [master job rehearsal](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/41652/rehearse-41652-pull-ci-openshift-cloud-credential-operator-master-e2e-azure-manual-oidc/1684585385289584640) but failed on a specific test.

```
[sig-instrumentation] Prometheus [apigroup:image.openshift.io] when installed on the cluster should report telemetry [Late] [Skipped:Disconnected] [Suite:openshift/conformance/parallel]
```

**Comment by abutcher** [comment]
/pj-rehearse pull-ci-openshift-cloud-credential-operator-master-e2e-azure-manual-oidc

**Comment by damdo** [comment]
Hey @abutcher is this ready for an approval?

**Comment by abutcher** [comment]
@damdo Based on the passing `ci/rehearse/openshift/cloud-credential-operator/master/e2e-azure-manual-oidc` test, I think we can approve and merge this to allow testing for CAPI in the future.

**Review by damdo — COMMENTED** [review]
Thanks.
/lgtm

**Comment by damdo** [comment]
Looks like there is a merge conflict to fix first @abutcher

**Comment by abutcher** [comment]
Rebased.

**Comment by jstuever** [comment]
/pj-rehearse pull-ci-openshift-cloud-credential-operator-master-e2e-azure-manual-oidc pull-ci-openshift-cluster-api-operator-main-e2e-azure-manual-oidc

**Comment by jstuever** [comment]
/pj-rehearse pull-ci-openshift-cloud-credential-operator-master-e2e-azure-manual-oidc
/pj-rehearse pull-ci-openshift-cluster-api-operator-main-e2e-azure-manual-oidc

**Comment by damdo** [comment]
@abutcher looks like it needs another one as some of those files have changed.

**Comment by damdo** [comment]
@abutcher it looks like this doesn't need rebase anymore, if you are happy with this we should add the rehearsals results you can add the relevant rehearsals-ack label so that this can merge.

**Pull request merged**
