### PR TITLE
Creating default Image config resource on master sidecar

### PR DESCRIPTION
**Pull request by ricardomaraschini**
Introduces a new side car, this time including Image config CRD and a default empty config CR. This resource is used during image stream imports, feature used during image-registry integration tests.

### CODE REVIEW

**Comment by dmage** [comment]
@ricardomaraschini please update also openshift-cluster-version-operator-{master,4.6,4.7}-presubmits.yaml and openshift-image-registry-release-4.{6,7}-presubmits.yaml

**Comment by ricardomaraschini** [comment]
> @ricardomaraschini please update also openshift-cluster-version-operator-{master,4.6,4.7}-presubmits.yaml and openshift-image-registry-release-4.{6,7}-presubmits.yaml

@dmage done

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
