### PR TITLE
MGMT-14367: move assisted jobs to OCP 4.14

### PR DESCRIPTION
**Pull request by adriengentil**

### CODE REVIEW

**Review by gamli75 — APPROVED** [review]

**Comment by osherdp** [comment]
@adriengentil I guess we can try the same thing here no https://github.com/openshift/release/pull/41031 ?

**Comment by adriengentil** [comment]
> @adriengentil I guess we can try the same thing here no #41031 ?
> (if ztp failures are indeed just a mismatch of versions between openshift and hypershift)

thanks, I also moved `cluster-api-provider-agent` to 4.14

**Review by osherdp — APPROVED** [review]

**Pull request merged**
