### PR TITLE
OSSM-4505 Add integration upstream test jobs

### PR DESCRIPTION
**Pull request by fjglira**
Jira: https://issues.redhat.com/browse/OSSM-4505

Add the prow job to be able to run the integration tests against OCP cluster before each PR merge

To be able to test this jobs we need to merge first this PR: https://github.com/openshift-service-mesh/istio/pull/4

### CODE REVIEW

**Comment by fjglira** [comment]
/pj-rehearse pull-ci-openshift-service-mesh-istio-master-istio-integration-pilot

**Comment by fjglira** [comment]
/pj-rehearse pull-ci-openshift-service-mesh-istio-master-istio-integration-security
/pj-rehearse pull-ci-openshift-service-mesh-istio-master-istio-integration-telemetry

**Comment by fjglira** [comment]
//pj-rehearse

**Comment by fjglira** [comment]
/pj-rehearse pull-ci-openshift-service-mesh-istio-master-istio-integration-security

**Comment by fjglira** [comment]
/pj-rehearse pull-ci-openshift-service-mesh-istio-master-istio-integration-security

**Review by dgn — APPROVED** [review]

**Pull request merged**
