### PR TITLE
Add e2e-metal-ipi-sdn-bm for scos 4.15

### PR DESCRIPTION
**Pull request by derekhiggins**
Adds metal-ip okd job for 4.15 and 4.16

### CODE REVIEW

**Comment by derekhiggins** [comment]
/pull periodic-ci-openshift-release-master-okd-scos-4.15-e2e-metal-ipi-sdn-bm

**Comment by derekhiggins** [comment]
/pj-rehearse periodic-ci-openshift-release-master-okd-scos-4.15-e2e-metal-ipi-sdn-bm

**Comment by derekhiggins** [comment]
/pj-rehearse periodic-ci-openshift-release-master-okd-scos-4.15-e2e-metal-ipi-sdn-bm

**Comment by derekhiggins** [comment]
/pj-rehearse periodic-ci-openshift-release-master-okd-scos-4.15-e2e-metal-ipi-sdn-bm

**Comment by derekhiggins** [comment]
/pj-rehearse periodic-ci-openshift-release-master-okd-scos-4.15-e2e-metal-ipi-sdn-bm

**Comment by derekhiggins** [comment]
/pj-rehearse periodic-ci-openshift-release-master-okd-scos-4.15-e2e-metal-ipi-sdn-bm

**Comment by derekhiggins** [comment]
/pj-rehearse periodic-ci-openshift-release-master-okd-scos-4.15-e2e-metal-ipi-sdn-bm

**Comment by derekhiggins** [comment]
4.15 job cc @LorbusChris @sherine-k

**Comment by LorbusChris** [comment]
gentle ping for approval, @wking

**Comment by derekhiggins** [comment]
/pj-rehearse periodic-ci-openshift-release-master-okd-scos-4.15-e2e-metal-ipi-sdn-bm

**Comment by derekhiggins** [comment]
/reopen
lets try this again, will rebase

**Comment by derekhiggins** [comment]
/pj-rehearse periodic-ci-openshift-release-master-okd-scos-4.16-e2e-metal-ipi-sdn-bm

**Comment by derekhiggins** [comment]
/pj-rehearse periodic-ci-openshift-release-master-okd-scos-4.15-e2e-metal-ipi-sdn-bm

**Comment by derekhiggins** [comment]
/pj-rehearse periodic-ci-openshift-release-master-okd-scos-4.15-e2e-metal-ipi-sdn-bm

**Pull request closed without merging**
