### PR TITLE
[OCPQE-22232][wip]add prow debug vsphere3

### PR DESCRIPTION
**Pull request by weinliu**

### CODE REVIEW

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by sunzhaohua2** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.18-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.17-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.17-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.18-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-master-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.17-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Comment by weinliu** [comment]
/pj-rehearse pull-ci-openshift-openshift-tests-private-release-4.16-debug-winc-vsphere-ipi

**Pull request closed without merging**
