### PR TITLE
AWS Localzone

### PR DESCRIPTION
**Pull request by yunjiang29**
Add AWS Local Zone support, two additional worker nodes will be added to Local Zone subnet.

### CODE REVIEW

**Comment by yunjiang29** [comment]
@jianlinliu @gpei PTAL.

**Comment by gpei** [comment]
@yunjiang29 does "us-east-2" support this, do we need to specify the REGION for this workflow?
```
# aws --region us-east-2 ec2 describe-availability-zones --filters Name=opt-in-status,Values=opted-in Name=zone-type,Values=local-zone | jq -r --arg z $az_name '.AvailabilityZones[] | select (.ParentZoneName==$z) | .ZoneName'
{
  "AvailabilityZones": []
}
```

**Comment by yunjiang29** [comment]
> @yunjiang29 does "us-east-2" support this, do we need to specify the REGION for this workflow?
> 
> ```
> # aws --region us-east-2 ec2 describe-availability-zones --filters Name=opt-in-status,Values=opted-in Name=zone-type,Values=local-zone | jq -r --arg z $az_name '.AvailabilityZones[] | select (.ParentZoneName==$z) | .ZoneName'
> {
>   "AvailabilityZones": []
> }
> ```

@gpei We use another profile `aws-1-qe` to test local zone feature, which contains `us-east-1` only https://github.com/openshift/release/pull/33470/files#diff-5169f2a74d1497f38a44e9adc57f6993269a89c3ddf90ab01f5d1d114ef61e58R42-R49

**Comment by yunjiang29** [comment]
Installation succeeded, but destroy failed due to https://issues.redhat.com/browse/OCPBUGS-2891

Ready for merge.

**Comment by jianlinliu** [comment]
> > @yunjiang29 does "us-east-2" support this, do we need to specify the REGION for this workflow?
> > ```
> > # aws --region us-east-2 ec2 describe-availability-zones --filters Name=opt-in-status,Values=opted-in Name=zone-type,Values=local-zone | jq -r --arg z $az_name '.AvailabilityZones[] | select (.ParentZoneName==$z) | .ZoneName'
> > {
> >   "AvailabilityZones": []
> > }
> > ```
> 
> @gpei We use another profile `aws-1-qe` to test local zone feature, which contains `us-east-1` only https://github.com/openshift/release/pull/33470/files#diff-5169f2a74d1497f38a44e9adc57f6993269a89c3ddf90ab01f5d1d114ef61e58R42-R49

Shall we update the cluster profile name to `aws-localzone-qe` for easy understanding?

**Comment by yunjiang29** [comment]
> Shall we update the cluster profile name to aws-localzone-qe for easy understanding?

Actually, the `aws-localzone-qe` is the first name in my mind, but I choose `aws-1-qe` is because, a) there is another different zone type, called `wavelength-zone`, it is also only available in few regions b) any other new AWS features need to be tested, `us-east-1` is always a good place.  So only `us-east-1` slice will be added in `aws-1-qe` profile.

**Comment by jianlinliu** [comment]
> Actually, the `aws-localzone-qe` is the first name in my mind, but I choose `aws-1-qe` is because, a) there is another different zone type, called `wavelength-zone`, it is also only available in few regions b) any other new AWS features need to be tested, `us-east-1` is always a good place. So only `us-east-1` slice will be added in `aws-1-qe` profile.

Got it.

**Comment by gpei** [comment]
> > @yunjiang29 does "us-east-2" support this, do we need to specify the REGION for this workflow?
> > ```
> > # aws --region us-east-2 ec2 describe-availability-zones --filters Name=opt-in-status,Values=opted-in Name=zone-type,Values=local-zone | jq -r --arg z $az_name '.AvailabilityZones[] | select (.ParentZoneName==$z) | .ZoneName'
> > {
> >   "AvailabilityZones": []
> > }
> > ```
> 
> @gpei We use another profile `aws-1-qe` to test local zone feature, which contains `us-east-1` only https://github.com/openshift/release/pull/33470/files#diff-5169f2a74d1497f38a44e9adc57f6993269a89c3ddf90ab01f5d1d114ef61e58R42-R49

Got it.
/lgtm

**Pull request merged**
