### PR TITLE
NO-JIRA: cluster-api/cluster-capi-operator: add openstack/gcp e2e

### PR DESCRIPTION
**Pull request by damdo**
Ensures openstack/gcp e2e test jobs for cluster-api and cluster-capi-operator.

### CODE REVIEW

**Comment by damdo** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-master-e2e-openstack-capi-techpreview

**Comment by damdo** [comment]
/pj-rehearse pull-ci-openshift-cluster-capi-operator-main-e2e-openstack-capi-techpreview

**Review by JoelSpeed — COMMENTED** [review]
/lgtm

**Comment by damdo** [comment]
/pj-rehearse pull-ci-openshift-cluster-capi-operator-main-e2e-openstack-capi-techpreview

**Comment by damdo** [comment]
/pj-rehearse pull-ci-openshift-cluster-capi-operator-main-e2e-openstack-capi-techpreview

**Pull request merged**
