### PR TITLE
[Step Enablement] operatorhub-subscribe-local-storage-operator

### PR DESCRIPTION
**Pull request by LiangquanLi930**

### CODE REVIEW

**Review by aleskandro — APPROVED** [review]

**Comment by LiangquanLi930** [comment]
test job: https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/38599/rehearse-38599-periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-ovn-hypershift-p1-f7/1649390361094656000

**Comment by LiangquanLi930** [comment]
https://issues.redhat.com/browse/OCPQE-14829

**Pull request merged**
