### PR TITLE
openstack: Migrate 4.7 periodics to step-registry

### PR DESCRIPTION
**Pull request by pierreprinetti**
Implements [OSASINFRA-2292](https://issues.redhat.com/browse/OSASINFRA-2292)

### CODE REVIEW

**Review by petr-muller — COMMENTED** [review]
First of all, as DPTP, thanks for this work!

Several comments:
1. The `release-*` jobs replacements should go into the config files in `ci-operator/config/openshift/release`. Of course nothing prevents you from having the same job under openshift/installer.
2. The timing is a little unfortunate for 4.8. Can we wait perhaps a week? Today is code freeze and these jobs are release-informing. The change involves renaming the job, which means we'll lose testgrid history (https://testgrid.k8s.io/redhat-openshift-ocp-release-4.8-informing#release-openshift-ocp-installer-e2e-openstack-4.8). Maybe we can start with moving the 4.9 job first?
3. As DPTP we have tools that can mass-migrate template jobs to workflows. Will the workflow work for pre-4.8 OCPs

**Comment by pierreprinetti** [comment]
Thank you @petr-muller!

To answer your comments:

> The release-* jobs replacements should go into the config files in ci-operator/config/openshift/release. Of course nothing prevents you from having the same job under openshift/installer.

I have moved them, thanks. Now let's see in how many tries I get the images right.

> The timing is a little unfortunate for 4.8. Can we wait perhaps a week? [...] Maybe we can start with moving the 4.9 job first?

Absolutely. I have no reason to push 4.8 before next week.

> As DPTP we have tools that can mass-migrate template jobs to workflows. Will the workflow work for pre-4.8 OCPs

The workflow is supposed to work for 4.6+. I didn't bother adapting it for 4.5, as to my understanding it EOLs soon.

**Comment by petr-muller** [comment]
>  I have moved them, thanks. Now let's see in how many tries I get the images right.
I think it just needs an additional
```yaml
base_images:
  openstack-installer:
    name: "4.7"
    namespace: ocp
    tag: openstack-installer
```
and then it will work

> The workflow is supposed to work for 4.6+. I didn't bother adapting it for 4.5, as to my understanding it EOLs soon. Do you have automation ready to migrate our presubmits? Shall I close this PR?
 
No need to close this PR, we'll use it as a blueprint for the automation.

**Review by mandre — COMMENTED** [review]
Super happy to see we're finally ready to move the openstack periodics to the step-registry. It looks so simple, nice job.
/lgtm

**Review by petr-muller — APPROVED** [review]

**Comment by pierreprinetti** [comment]
@petr-muller Is there something I should do to tell Testgrid to use these as the new OpenStack release-informing jobs for OpenShift 4.7?

**Comment by petr-muller** [comment]
@pierreprinetti no, it will eventually show up

**Comment by pierreprinetti** [comment]
The new jobs look fine[1][2].

@petr-muller You mentioned that you can easily replicate the change for all branches? (I can still do that if it's not quick or practical for you to do it)

[1]: https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.7-e2e-openstack-parallel
[2]: https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.7-e2e-openstack-serial

**Pull request merged**
