### PR TITLE
Remove everything related to release-bot

### PR DESCRIPTION
**Pull request by petr-muller**
Many release jobs mount the secret to `/etc/appci` but none uses it.
There is no other usage of `release-bot` in the repo. so clean up even
its manifest and secret sync config.

I dug why this exists and found
https://issues.redhat.com/browse/DPTP-1181 which addressed the need of
release jobs to self-annotate. There is no such job in the repo anymore.

xref: https://github.com/openshift/release/pull/9121/

/cc @hongkailiu @stevekuznetsov

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
/lgtm
/approve
/hold

Needs rebase :|

**Comment by petr-muller** [comment]
> Needs rebase :|

Caused by OVirt porting their stuff to multi-stage. I'll happily rebase for that reason any time :)

**Review by hongkailiu — APPROVED** [review]

**Comment by petr-muller** [comment]
```console
❯ appci delete sa release-bot -n ci
serviceaccount "release-bot" deleted

☸ build01 (ci) in release on  migrate-upi-gcp [$+] took 3s 
❯ appci delete role release-bot -n ci
role.rbac.authorization.k8s.io "release-bot" deleted

☸ build01 (ci) in release on  migrate-upi-gcp [$+] 
❯ appci delete rolebinding release-bot -n ci
rolebinding.rbac.authorization.k8s.io "release-bot" deleted

```

**Comment by petr-muller** [comment]
...and deleted the secret from BW

**Pull request merged**
