### PR TITLE
Rename ansibleee-operator to openstack-ansibleee-operator

### PR DESCRIPTION
**Pull request by fao89**
Signed-off-by: Fabricio Aguiar <fabricio.aguiar@gmail.com>

### CODE REVIEW

**Comment by fao89** [comment]
@viroel could you please take a look?

**Review by jlarriba — APPROVED** [review]

**Comment by viroel** [comment]
/lgtm
my late review on this one, but lgtm

**Comment by raukadah** [comment]
@fao89 Thank you submitting the PR, the changes looks good. The file path still contains ansibleee-operator. Do we want to rename those also?
For example: ci-operator/config/openstack-k8s-operators/ansibleee-operator to ci-operator/config/openstack-k8s-operators/openstack-ansibleee-operator

**Comment by fao89** [comment]
> @fao89 Thank you submitting the PR, the changes looks good. The file path still contains ansibleee-operator. Do we want to rename those also? For example: ci-operator/config/openstack-k8s-operators/ansibleee-operator to ci-operator/config/openstack-k8s-operators/openstack-ansibleee-operator

it is renamed:
```
release on  renameransibleee [$] via 🐍 v3.11.0 (venv) on ☁️   took 9s 
❯ ls -al  ci-operator/config/openstack-k8s-operators/ | grep ansible         
drwxr-xr-x. 1 faguiard faguiard  136 Jan 16 11:11 openstack-ansibleee-operator
```

**Comment by raukadah** [comment]
> > @fao89 Thank you submitting the PR, the changes looks good. The file path still contains ansibleee-operator. Do we want to rename those also? For example: ci-operator/config/openstack-k8s-operators/ansibleee-operator to ci-operator/config/openstack-k8s-operators/openstack-ansibleee-operator
> 
> it is renamed:
> 
> ```
> release on  renameransibleee [$] via 🐍 v3.11.0 (venv) on ☁️   took 9s 
> ❯ ls -al  ci-operator/config/openstack-k8s-operators/ | grep ansible         
> drwxr-xr-x. 1 faguiard faguiard  136 Jan 16 11:11 openstack-ansibleee-operator
> ```

Sorry my mistakes, it got renamed.

**Pull request merged**
