### PR TITLE
NO-JIRA: Add Openshift CI security job to Hypershift release-4.17 branch

### PR DESCRIPTION
**Pull request by jparrill**
This PR adds the Openshift CI Security job to check release-4.17 branch with SNYK tool. It depends on this PR:

- https://github.com/openshift/hypershift/pull/4748

/hold

### CODE REVIEW

**Comment by jparrill** [comment]
Dependant PR merged
/hold cancel

**Comment by jparrill** [comment]
/pj-rehearse pull-ci-openshift-hypershift-release-4.17-security

**Comment by jparrill** [comment]
/pj-rehearse pull-ci-openshift-hypershift-release-4.17-security

**Review by sjenning — APPROVED** [review]

**Pull request merged**
