### PR TITLE
make the must gather steps run before CLC destroy

### PR DESCRIPTION
**Pull request by vboulos**
- Move the must gather step to run just before CLC destroy

### CODE REVIEW

**Review by gparvin — APPROVED** [review]

**Comment by gparvin** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.14-interop-openshift-plus-interop-aws

**Comment by gparvin** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.14-interop-openshift-plus-interop-aws

**Comment by vboulos** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.14-interop-openshift-plus-interop-aws

**Comment by gparvin** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.14-interop-openshift-plus-interop-aws

**Review by gparvin — APPROVED** [review]

**Comment by vboulos** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.14-interop-openshift-plus-interop-aws

**Review by gparvin — APPROVED** [review]

**Review by gparvin — APPROVED** [review]

**Pull request merged**
