### PR TITLE
Point ci-operator config to ironic repos

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-master-unit pull-ci-openshift-openstack-ironic-python-agent-master-unit pull-ci-openshift-openstack-sushy-master-unit pull-ci-openshift-openstack-ironic-lib-master-unit pull-ci-openshift-openstack-ironic-inspector-master-unit

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-master-unit pull-ci-openshift-openstack-ironic-python-agent-master-unit pull-ci-openshift-openstack-sushy-master-unit pull-ci-openshift-openstack-ironic-lib-master-unit pull-ci-openshift-openstack-ironic-inspector-master-unit

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-master-unit pull-ci-openshift-openstack-ironic-python-agent-master-unit pull-ci-openshift-openstack-sushy-master-unit pull-ci-openshift-openstack-ironic-lib-master-unit pull-ci-openshift-openstack-ironic-inspector-master-unit

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-master-unit pull-ci-openshift-openstack-ironic-python-agent-master-unit pull-ci-openshift-openstack-sushy-master-unit pull-ci-openshift-openstack-ironic-lib-master-unit pull-ci-openshift-openstack-ironic-inspector-master-unit

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-master-unit pull-ci-openshift-openstack-ironic-python-agent-master-unit pull-ci-openshift-openstack-sushy-master-unit pull-ci-openshift-openstack-ironic-lib-master-unit pull-ci-openshift-openstack-ironic-inspector-master-unit

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-master-unit pull-ci-openshift-openstack-ironic-python-agent-master-unit pull-ci-openshift-openstack-sushy-master-unit pull-ci-openshift-openstack-ironic-lib-master-unit pull-ci-openshift-openstack-ironic-inspector-master-unit

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-master-unit pull-ci-openshift-openstack-ironic-python-agent-master-unit pull-ci-openshift-openstack-sushy-master-unit pull-ci-openshift-openstack-ironic-lib-master-unit pull-ci-openshift-openstack-ironic-inspector-master-unit

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-master-unit pull-ci-openshift-openstack-ironic-python-agent-master-unit pull-ci-openshift-openstack-sushy-master-unit pull-ci-openshift-openstack-ironic-lib-master-unit pull-ci-openshift-openstack-ironic-inspector-master-unit

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-master-unit pull-ci-openshift-openstack-ironic-python-agent-master-unit pull-ci-openshift-openstack-sushy-master-unit pull-ci-openshift-openstack-ironic-lib-master-unit pull-ci-openshift-openstack-ironic-inspector-master-unit

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-master-unit pull-ci-openshift-openstack-ironic-python-agent-master-unit pull-ci-openshift-openstack-sushy-master-unit pull-ci-openshift-openstack-ironic-lib-master-unit pull-ci-openshift-openstack-ironic-inspector-master-unit

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-master-unit pull-ci-openshift-openstack-ironic-python-agent-master-unit pull-ci-openshift-openstack-sushy-master-unit pull-ci-openshift-openstack-ironic-lib-master-unit pull-ci-openshift-openstack-ironic-inspector-master-unit

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-master-unit pull-ci-openshift-openstack-ironic-python-agent-master-unit pull-ci-openshift-openstack-sushy-master-unit pull-ci-openshift-openstack-ironic-lib-master-unit pull-ci-openshift-openstack-ironic-inspector-master-unit

**Comment by elfosardo** [comment]
/hold
need to finish config in the single repos

**Comment by elfosardo** [comment]
/pj-rehearse pull-ci-openshift-openstack-ironic-master-unit pull-ci-openshift-openstack-ironic-python-agent-master-unit pull-ci-openshift-openstack-sushy-master-unit pull-ci-openshift-openstack-ironic-lib-master-unit pull-ci-openshift-openstack-ironic-inspector-master-unit

**Review by iurygregory — APPROVED** [review]
/lgtm

**Pull request merged**
