### PR TITLE
Use operator directive under the PAO 4.5 jobs

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
/hold
wait for https://github.com/openshift-kni/performance-addon-operators/pull/422

**Comment by fromanirh** [comment]
/lgtm
let's see how it works in 4.5

**Comment by cynepco3hahue** [comment]
@fromanirh FYI CI passed.

**Pull request merged**
