### PR TITLE
Use internal services for RPM content-mirror

### PR DESCRIPTION
**Pull request by bear-redhat**
FQDN in the internal nginx proxy resolves to public Internet IP address and leads to traffic go through Internet, which is unnecessary

### CODE REVIEW

**Comment by hongkailiu** [comment]
Let us ask @jupierce because he contributed to the project as well.
https://github.com/openshift/content-mirror/graphs/contributors

I would announce the change for a week or so before merging so that the owner of the tests using the service will be aware.

**Comment by hongkailiu** [comment]
Besides users' report, do you have some steps to verify after merge?
Or something to monitor?

**Comment by jupierce** [comment]
That's a nice catch on the efficiency front. This change appears safe and transparent to users. 
Interestingly, other than 3.11, all these releases are EOL. I only see 3.11 activity for this in the logs. 

After deploying, you can check things with
```
curl -v https://artifacts-rpms-openshift-origin-ci-rpms.apps.ci.l2s4.p1.openshiftapps.com/openshift-origin-v3.11/repodata/repomd.xml
```

For current releases, RPMs are served through these dynamically generated services: https://github.com/openshift/release/blob/c5e100bbf0d5eb93f3366a3891c2a4edd9c60860/clusters/build-clusters/common/release-controller/rpms-ocp-4.6.yaml . So I think this is another thing we could disable when 3.11 is non longer supported.

**Pull request merged**
