### PR TITLE
OCPQE-25881: correct amd instance type config issue

### PR DESCRIPTION
**Pull request by jianlinliu**
Some job config issues introduced in #54114, x86 instance was using arm instance type, correct them here.

### CODE REVIEW

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-arm64-stable-gcp-ipi-to-multiarch-f28

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-arm64-stable-gcp-ipi-to-multiarch-f28

**Comment by jianlinliu** [comment]
cc @evakhoni to review.

**Comment by evakhoni** [comment]
thanks @jianlinliu 
good catch! seems like n2-standard-4 is the correct type for the additional x86 workers
/lgtm

**Comment by jianlinliu** [comment]
cc @liangxia to reivew.

**Pull request merged**
