### PR TITLE
test pod with persistent storage

### PR DESCRIPTION
**Pull request by copejon**
Alters the MicroShift reboot tests to deploy a pod with a pvc rather than a deployment.  This better reflects baseline customer envs with persistent storage.

[USHIFT-1020](https://issues.redhat.com//browse/USHIFT-1020)

### CODE REVIEW

**Comment by copejon** [comment]
The mass failure is a result of SSL certs being expired on kuttl's releases.

**Review by pacevedom — APPROVED** [review]
/lgtm

**Pull request merged**
