### PR TITLE
MSI: Add firewatch to hypershift workflow

### PR DESCRIPTION
**Pull request by rnetser**

### CODE REVIEW

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-operator-v4.13-hypershift-GA-stage-sanity-rosa-rhods-hypershift-fips

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-operator-v4.13-hypershift-GA-stage-sanity-rosa-rhods-hypershift-fips



<br class="Apple-interchange-newline">

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-operator-v4.13-hypershift-GA-stage-sanity-rosa-rhods-hypershift-fips

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-operator-v4.13-hypershift-GA-stage-sanity-rosa-rhods-hypershift-fips

**Review by myakove — APPROVED** [review]

**Pull request merged**
