### PR TITLE
Add jira-lifecycle plugin to assisted-service and related repos

### PR DESCRIPTION
**Pull request by vrutkovs**

### CODE REVIEW

**Review by osherdp — CHANGES_REQUESTED** [review]
if going with this solution add also assisted-installer-agent and cluster-api-provider-agent

**Comment by vrutkovs** [comment]
/hold

Nope, not it

**Review by droslean — APPROVED** [review]

**Comment by droslean** [comment]
@vrutkovs This is enabled in the org layer. /close

**Pull request closed without merging**
