### PR TITLE
Update Application Lifecycle components to omit image-remote-src env var

### PR DESCRIPTION
**Pull request by gurnben**
## Summary of Changes

This PR removes the `OSCI_IMAGE_REMOTE_REPO_SRC` env var from all jobs that leverage `ocm-ci-image-mirror` as it is no longer necessary and results in duplicate mirrors of images - this work is part of https://github.com/stolostron/backlog/issues/24969.

### CODE REVIEW

**Comment by mikeshng** [comment]
@gurnben thank you for this change.

Could you undo the `multicloud-operators-foundation` changes please? This is not an app repo and should be review by someone else. Thanks.

**Comment by xiangjingli** [comment]
@gurnben  @mikeshng  FYI The multicloud-operators-foundation repo is owned by foundation squad

**Comment by mikeshng** [comment]
Could you merge the follow PR and it should produce 0 foundation file changes for this PR.
https://github.com/gurnben/release/pull/1

**Pull request merged**
