### PR TITLE
Set the ci/prow/e2e-tests Job as a Mandatory Check for Pull Requests

### PR DESCRIPTION
**Pull request by subhashkhileri**
https://issues.redhat.com/browse/RHIDP-2215

### CODE REVIEW

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-main-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-main-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-main-e2e-tests

**Comment by subhashkhileri** [comment]
/pj-rehearse pull-ci-janus-idp-backstage-showcase-main-e2e-tests

**Review by zdrapela — APPROVED** [review]

**Pull request merged**
