### PR TITLE
Correcting the prowjobs CRD for the latest/greatest validation

### PR DESCRIPTION
**Pull request by bradmwilliams**
Bumping the prowjobs CRD up to be compliant with the latest/greatest `v1` validation

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@bradmwilliams is this causing concrete issues right now? Otherwise I'd prefer to wait until the upstream PR is merged.

**Comment by bradmwilliams** [comment]
@alvaroaleman No, this PR was just to sync our file with the changes with the upstream PR.

**Review by alvaroaleman — APPROVED** [review]
/label tide/merge-method-squash

**Pull request merged**
