### PR TITLE
preparing for Serverless 1.31.1 release

### PR DESCRIPTION
**Pull request by Kaustubh-pande**
Signed-off-by: Kautsubh pande [kpande@redhat.com](mailto:kpande@redhat.com)

cc @dsimansk @mgencur @ReToCode

### CODE REVIEW

**Comment by ReToCode** [comment]
Hm not sure if this is not going to be reverted by https://github.com/openshift-knative/hack?

@mgencur

**Comment by mgencur** [comment]
@ReToCode We only generate configs for "main" branch: https://github.com/openshift-knative/hack/blob/main/config/serverless-operator.yaml#L5

**Comment by dsimansk** [comment]
@ReToCode or @mgencur can you add `/approve` cmd pls?

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
