### PR TITLE
CNF-10016: Create new workflow for fetching and reporting telco kpi results (oslat, cyclictest)

### PR DESCRIPTION
**Pull request by fontivan**
[CNF-10016](https://issues.redhat.com//browse/CNF-10016): Create new workflow for fetching and reporting telco kpi results (oslat, cyclictest)

### CODE REVIEW

**Comment by fontivan** [comment]
Resurrection of https://github.com/openshift/release/pull/45264

**Comment by fontivan** [comment]
/pj-rehearse periodic-ci-ran-telco5g-kpi-results-master-kpi-results-415

**Comment by fontivan** [comment]
Unfortunately comments are not allowed in the job configurations, as I had some lines describing why the cron configuration is the way that it is is, e.g.: https://github.com/openshift/release/pull/51560/commits/187e3b132097383122330696e626026dcd962d96#diff-fdc7627bd922af2e7a970da42f95e58b48e2f6047a1cebcbd4f16d93d48ac6dfL22

**Comment by fontivan** [comment]
I have set the jobs to use the candidate streams since this is what we want for the actual solution. We have the same candidate streams running tests on Saturday (4.15) and Sunday (4.14) currently, and I have set the crons for those two jobs to trigger this approximately 1 hour after the respective jobs will complete.

Unforunately this means the rehersal will  fail in the latter half of the week after new builds become available, since the job will be attempting to find results for a build that has not been tested yet. I am not sure if there is any good way around this.

**Comment by deepsm007** [comment]
@fontivan Can you link a rehearsal that succeeded before merging?

**Comment by fontivan** [comment]
> @fontivan Can you link a rehearsal that succeeded before merging?

@deepsm007 I had a few successful rehersals such as https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/51560/rehearse-51560-periodic-ci-ran-telco5g-kpi-results-master-kpi-results-415/1786147024819720192 there are also some more successful runs listed here alongside a few more failures: https://prow.ci.openshift.org/pr-history/?org=openshift&repo=release&pr=51560

However I have described in greater detail here https://github.com/openshift/release/pull/51560#issuecomment-2101227120 why the rehersals are somewhat annoying for this particular job

If I use the real config we want, then today the rehearsal will fail because the test results won't be available until saturday for the matching OCP version e.g. 4.15.12

**Pull request merged**
