### PR TITLE
remove obsolete community-operators tests

### PR DESCRIPTION
**Pull request by dmesser**
These tests are now run by CVP.

### CODE REVIEW

**Comment by dmesser** [comment]
Not sure how to fix the broken tests - maybe they don't catch removal of tests?

**Comment by petr-muller** [comment]
@dmesser you need to remove also the matching directory under `ci-operator/jobs`

**Comment by dmesser** [comment]
> @dmesser you need to remove also the matching directory under `ci-operator/jobs`

Done.

**Pull request merged**
