### PR TITLE
Add ovirt presubmit to cluster etcd operator

### PR DESCRIPTION
**Pull request by Gal-Zaidman**
We wanted our e2e suite to be triggerable for this repo but to run only when it is triggered so:
always_run = false
run_if_changed : ""

### CODE REVIEW

**Comment by marun** [comment]
Please set `optional = true` as well. A job that is run on-demand has no guarantee of staying stable enough to gate merges.

**Comment by Gal-Zaidman** [comment]
> Please set `optional = true` as well. A job that is run on-demand has no guarantee of staying stable enough to gate merges.

Done

**Comment by marun** [comment]
/lgtm

@hexfusion Please approve, zero risk to us to enable this optional on-demand job.

**Comment by marun** [comment]
@Gal-Zaidman What work is proposed for openshift on ovirt that will require validating compatibility specifically with the etcd operator?

**Comment by Gal-Zaidman** [comment]
> @Gal-Zaidman What work is proposed for openshift on ovirt that will require validating compatibility specifically with the etcd operator?

Well we wanted to check this PR:
https://github.com/openshift/cluster-etcd-operator/pull/515

But it is generally good to have a test we can trigger for oVirt, our CI is stable now and we want to be able to test specific changes

**Comment by marun** [comment]
@Gal-Zaidman Note that https://github.com/openshift/cluster-etcd-operator/pull/515 only enables support for an unsupported config override. Does the job you're adding here set that override? Otherwise, running the job won't actually be testing the PR change.

**Comment by Gal-Zaidman** [comment]
> @Gal-Zaidman Note that [openshift/cluster-etcd-operator#515](https://github.com/openshift/cluster-etcd-operator/pull/515) only enables support for an unsupported config override. Does the job you're adding here set that override? Otherwise, running the job won't actually be testing the PR change.

No, it doesn't
@eslutsky what do you think should we test manually instead?

**Comment by Gal-Zaidman** [comment]
I think I'll close the PR for now, @eslutsky feel free to reopen if needed

**Pull request closed without merging**
