### PR TITLE
Update Streams for Apache Kafka after CVE respin to 2.7.0-7

### PR DESCRIPTION
**Pull request by im-konge**

### CODE REVIEW

**Comment by im-konge** [comment]
/pj-rehearse periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.18-lp-interop-amq-streams-2-7-fips periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.18-lp-interop-amq-streams-2-7

**Review by dfrazzette — APPROVED** [review]

**Pull request merged**
