### PR TITLE
ptp ci: Add bundle-check as pre-submit job

### PR DESCRIPTION
**Pull request by leo8a**
Follow up PR of https://github.com/openshift/ptp-operator/pull/499.

Signed-off-by: Leonardo Ochoa-Aday <lochoa@redhat.com>

### CODE REVIEW

**Review by jzding — APPROVED** [review]
/lgtm

**Comment by leo8a** [comment]
/pj-rehearse pull-ci-openshift-ptp-operator-master-bundle-check

**Comment by leo8a** [comment]
/pj-rehearse pull-ci-openshift-ptp-operator-master-bundle-check

**Comment by leo8a** [comment]
/pj-rehearse pull-ci-openshift-ptp-operator-master-bundle-check

**Comment by leo8a** [comment]
```
 curl https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/operator-sdk/4.11.0/operator-sdk-linux-x86_64.tar.gz? | tar -xz -C bin/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now 
```
/pj-rehearse pull-ci-openshift-ptp-operator-master-bundle-check

**Comment by jzding** [comment]
/pj-rehearse pull-ci-openshift-ptp-operator-master-bundle-check

**Comment by jzding** [comment]
/pj-rehearse pull-ci-openshift-ptp-operator-master-bundle-check

**Comment by leo8a** [comment]
/pj-rehearse pull-ci-openshift-ptp-operator-master-bundle-check

**Comment by leo8a** [comment]
/pj-rehearse pull-ci-openshift-ptp-operator-master-bundle-check

**Comment by leo8a** [comment]
/pj-rehearse pull-ci-openshift-ptp-operator-master-bundle-check

**Comment by leo8a** [comment]
/hold

wait for https://github.com/openshift/ptp-operator/pull/514 fix to land

**Comment by leo8a** [comment]
/unhold
/pj-rehearse pull-ci-openshift-ptp-operator-master-bundle-check

**Comment by leo8a** [comment]
/pj-rehearse pull-ci-openshift-ptp-operator-master-bundle-check

**Review by jzding — APPROVED** [review]
/lgtm

**Pull request merged**
