### PR TITLE
OCPBUGS-706: IBMCloud: File cli temp file

### PR DESCRIPTION
**Pull request by cjschaef**
While attempting to add retries to ibmcloud CLI commands, creation of a temporary file to store results fails due to the filepath of the ibmcloud CLI command, requiring removal of the filepath to address.

Related: https://issues.redhat.com/browse/OCPBUGS-706

### CODE REVIEW

**Comment by cjschaef** [comment]
`ibmcloud-gather-resources` has run successfully now
```
 INFO[2022-09-14T16:53:20Z] Running step e2e-ibmcloud-ipi-ibmcloud-gather-resources. 
INFO[2022-09-14T16:57:00Z] Step e2e-ibmcloud-ipi-ibmcloud-gather-resources succeeded after 3m40s. 
```
Things appear to be working properly, at least when IPI install succeeds. I'll have to confirm later in cases where IPI install fails to create some/all resources.

**Comment by cjschaef** [comment]
`cluster-api-provider-ibmcloud/main/e2e-ibmcloud` is affected by [OCPBUGS-1327](https://issues.redhat.com/browse/OCPBUGS-1327)
```
NAME                                        STATUS   ROLES                  AGE   VERSION           INTERNAL-IP    EXTERNAL-IP    OS-IMAGE                                                        KERNEL-VERSION                 CONTAINER-RUNTIME
ci-op-sgbrhc5c-4e03e-bszh6-master-0         Ready    control-plane,master   49m   v1.24.0+ebabf6d   10.242.1.5     10.242.1.5     Red Hat Enterprise Linux CoreOS 412.86.202209121449-0 (Ootpa)   4.18.0-372.19.1.el8_6.x86_64   cri-o://1.25.0-51.rhaos4.12.git315a0cb.el8
ci-op-sgbrhc5c-4e03e-bszh6-master-1         Ready    control-plane,master   48m   v1.24.0+ebabf6d   10.242.65.6    10.242.65.6    Red Hat Enterprise Linux CoreOS 412.86.202209121449-0 (Ootpa)   4.18.0-372.19.1.el8_6.x86_64   cri-o://1.25.0-51.rhaos4.12.git315a0cb.el8
ci-op-sgbrhc5c-4e03e-bszh6-master-2         Ready    control-plane,master   49m   v1.24.0+ebabf6d   10.242.128.6   10.242.128.6   Red Hat Enterprise Linux CoreOS 412.86.202209121449-0 (Ootpa)   4.18.0-372.19.1.el8_6.x86_64   cri-o://1.25.0-51.rhaos4.12.git315a0cb.el8
ci-op-sgbrhc5c-4e03e-bszh6-worker-2-vn5tq   Ready    worker                 40m   v1.24.0+ebabf6d   10.242.64.4    10.242.64.4    Red Hat Enterprise Linux CoreOS 412.86.202209121449-0 (Ootpa)   4.18.0-372.19.1.el8_6.x86_64   cri-o://1.25.0-51.rhaos4.12.git315a0cb.el8
ci-op-sgbrhc5c-4e03e-bszh6-worker-3-dl66q   Ready    worker                 40m   v1.24.0+ebabf6d   10.242.129.4   10.242.129.4   Red Hat Enterprise Linux CoreOS 412.86.202209121449-0 (Ootpa)   4.18.0-372.19.1.el8_6.x86_64   cri-o://1.25.0-51.rhaos4.12.git315a0cb.el8
```
```
# ibmcloud is instances

0787_69362abe-ddbf-4b60-b367-a873d8da58e3   ci-op-sgbrhc5c-4e03e-bszh6-master-0         running   10.242.1.5     -             bx2-4x16   ci-op-sgbrhc5c-4e03e-bszh6-rhcos   ci-op-sgbrhc5c-4e03e-bszh6-vpc   eu-gb-1   ci-op-sgbrhc5c-4e03e-bszh6   
0787_ff0b7b80-96a9-4bd9-954c-f95bec693490   ci-op-sgbrhc5c-4e03e-bszh6-worker-1-h67rq   running   10.242.0.4     -             bx2-4x16   ci-op-sgbrhc5c-4e03e-bszh6-rhcos   ci-op-sgbrhc5c-4e03e-bszh6-vpc   eu-gb-1   ci-op-sgbrhc5c-4e03e-bszh6   
0797_a0d0d1a8-a4cf-4012-8269-70b2a9f5223d   ci-op-sgbrhc5c-4e03e-bszh6-master-1         running   10.242.65.6    -             bx2-4x16   ci-op-sgbrhc5c-4e03e-bszh6-rhcos   ci-op-sgbrhc5c-4e03e-bszh6-vpc   eu-gb-2   ci-op-sgbrhc5c-4e03e-bszh6   
0797_e6a18cb1-27d7-4a24-b17d-a86f8146fc58   ci-op-sgbrhc5c-4e03e-bszh6-worker-2-vn5tq   running   10.242.64.4    -             bx2-4x16   ci-op-sgbrhc5c-4e03e-bszh6-rhcos   ci-op-sgbrhc5c-4e03e-bszh6-vpc   eu-gb-2   ci-op-sgbrhc5c-4e03e-bszh6   
07a7_5153b815-e76e-4d04-8219-9adaf954770d   ci-op-sgbrhc5c-4e03e-bszh6-master-2         running   10.242.128.6   -             bx2-4x16   ci-op-sgbrhc5c-4e03e-bszh6-rhcos   ci-op-sgbrhc5c-4e03e-bszh6-vpc   eu-gb-3   ci-op-sgbrhc5c-4e03e-bszh6   
07a7_b06f7710-f3ec-4429-a119-4d2749995eeb   ci-op-sgbrhc5c-4e03e-bszh6-worker-3-dl66q   running   10.242.129.4   -             bx2-4x16   ci-op-sgbrhc5c-4e03e-bszh6-rhcos   ci-op-sgbrhc5c-4e03e-bszh6-vpc   eu-gb-3   ci-op-sgbrhc5c-4e03e-bszh6   
```

---

This does appear to resolve the issue with `ibmcloud-gather-resources` as expected
```
 INFO[2022-09-14T16:53:20Z] Running step e2e-ibmcloud-ipi-ibmcloud-gather-resources. 
INFO[2022-09-14T16:57:00Z] Step e2e-ibmcloud-ipi-ibmcloud-gather-resources succeeded after 3m40s. 
```

**Comment by jeffnowicki** [comment]
/retitle OCPBUGS-706: IBMCloud: File cli temp file IBMCloud: File cli temp

**Comment by jeffnowicki** [comment]
/retitle OCPBUGS-706: IBMCloud: File cli temp file

**Review by MayXuQQ — APPROVED** [review]
checked 
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/32212/rehearse-32212-pull-ci-openshift-cluster-api-provider-ibmcloud-main-e2e-ibmcloud/1570075385540907008/artifacts/e2e-ibmcloud/ipi-ibmcloud-gather-resources/build-log.txt

**Pull request merged**
