### PR TITLE
step-registry/ipi-install: add config to use aws spot instances

### PR DESCRIPTION
**Pull request by AlexNPavel**
This PR adds a new environment variable for the `ipi-install-install`
reference that can be used to enable the use of AWS spot instances for
worker nodes.

### CODE REVIEW

**Comment by AlexNPavel** [comment]
This PR will initially have a new periodic for 4.12 nightly. That is only there so that `pj-rehearse` can be run with the new config and will be removed after testing is successful.

**Comment by AlexNPavel** [comment]
The machine sets for the workers properly contain the `spotMarketOption: {}` field in the `providerSpec` in the running cluster, and the worker nodes have the `machine.openshift.io/interruptible-instance` label set, so I believe the changes work as intended.

**Comment by AlexNPavel** [comment]
The dummy periodic has been removed and this PR is ready to be merged after review.

**Review by wking — APPROVED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
Jobs seem to be booting properly without the spot variable set this time, sounds good

/approve

**Pull request merged**
