### PR TITLE
Allow sa/ci-operator to get images

### PR DESCRIPTION
**Pull request by hongkailiu**
Required by https://github.com/openshift/ci-tools/pull/3521
See https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/3521/pull-ci-openshift-ci-tools-master-e2e-oo/1674232207218053120

/cc @openshift/test-platform 
/assign @droslean 

/hold

Applied already to b05 to see if it fixes the test.

### CODE REVIEW

**Comment by hongkailiu** [comment]
It works.
https://prow.ci.openshift.org/pr-history/?org=openshift&repo=ci-tools&pr=3521

**Review by droslean — APPROVED** [review]

**Pull request merged**
