### PR TITLE
OCPRHV-834: remove e2e-ovirt-sdn due to EOL

### PR DESCRIPTION
**Pull request by engelmi**
This PR removes the `e2e-ovirt-sdn` test step as ovirt will be disabled in the installer (PR: https://github.com/openshift/installer/pull/7213)

### CODE REVIEW

**Review by vrutkovs — APPROVED** [review]
/approve
/lgtm

**Comment by barbacbd** [comment]
It looks like there is a 4.15 presubmit file. Should we make those changes here too ?

**Pull request merged**
