### PR TITLE
OCPBUGS-17652: enable pre-submit for alibabacloud

### PR DESCRIPTION
**Pull request by rvanderp3**

### CODE REVIEW

**Comment by rvanderp3** [comment]
/pj-rehearse pull-ci-openshift-cluster-cloud-controller-manager-operator-release-4.14-e2e-alibaba-ovn

**Comment by rvanderp3** [comment]
confirmed that job is installing

**Comment by JoelSpeed** [comment]
Should this be added to master and 4.15 as well?

**Comment by rvanderp3** [comment]
@JoelSpeed just added master and 4.15 jobs as well.

**Pull request merged**
