### PR TITLE
hypershift: temporary remove hypershift-operator-initial base_image

### PR DESCRIPTION
**Pull request by sjenning**
Attempt to fix this mess xref https://github.com/openshift/release/pull/48326

`hypershift-operator-initial` is an image promoted by this job creating a circular dependency

### CODE REVIEW

**Comment by sjenning** [comment]
/pj-rehearse pull-ci-openshift-hypershift-release-4.15-e2e-aws

**Comment by sjenning** [comment]
/pj-rehearse pull-ci-openshift-hypershift-release-4.15-e2e-aws

**Comment by sjenning** [comment]
/pj-rehearse pull-ci-openshift-hypershift-release-4.15-e2e-aws

**Comment by sjenning** [comment]
/pj-rehearse pull-ci-openshift-hypershift-release-4.15-e2e-aws

**Review by jmguzik — APPROVED** [review]

**Pull request merged**
