### PR TITLE
[HCO] Remove 2 old tests

### PR DESCRIPTION
**Pull request by nunnatsa**
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

### CODE REVIEW

**Review by tiraboschi — APPROVED** [review]

**Comment by orenc1** [comment]
you removed 2 tests:

- hco-e2e-aws
- hco-e2e-azure

is there another test that should be removed? if no, please fix the title.
thanks

**Comment by orenc1** [comment]
merged despite the `/hold` command...

**Pull request merged**
