### PR TITLE
Run `e2e-kubevirt-aws-ovn` on us-east-1 region due to AZ requirements for HA

### PR DESCRIPTION
**Pull request by orenc1**
When testing highly available hosted clusters on AWS, it is required to run on a region that contains at least 3 availability zones, so each control plane component replica runs in a different AZ. us-west-1 and us-west-2 have only 2 AZs. With this change the job will run in a region that has >=3 AZs

### CODE REVIEW

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn

**Comment by orenc1** [comment]
the job passed and we're using a lease that contains quota slices of us-east-1 region, were there are 3 AZs.
running one more time for consistency.
/pj-rehearse

**Comment by orenc1** [comment]
added the same for the periodics.
/pj-rehearse

**Comment by orenc1** [comment]
added the same for the periodics.
/pj-rehearse

**Comment by orenc1** [comment]
ci-operator infra issue
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn

**Comment by davidvossel** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-kubevirt-main-e2e-kubevirt-aws-ovn

**Review by davidvossel — COMMENTED** [review]
/lgtm

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn

**Comment by davidvossel** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn

**Comment by orenc1** [comment]
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn

**Comment by orenc1** [comment]
still experiencing ci infra issues
/pj-rehearse pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn

**Pull request merged**
