### PR TITLE
openshift/assisted-test-infra: Use most recently tested image for assisted-service

### PR DESCRIPTION
**Pull request by lranjbar**

### CODE REVIEW

**Comment by YuviGold** [comment]
So it means we keep the assisted-service dependency as part of the Dockerfile?

**Comment by lranjbar** [comment]
It seems like we can. IMO it will be less overhead in the long term. The change here is just pulling the most recently tested version that prow built. I think it is a good optimization for the job but unsure as to why the tests are failing.

**Comment by djzager** [comment]
cc @YuviGold

**Comment by lranjbar** [comment]
Yeah seems like the jobs are a bit flaky but it is passing now.

**Review by YuviGold — APPROVED** [review]

**Pull request merged**
