### PR TITLE
WINC-1036: wmco: Delete Azure jobs in 4.10

### PR DESCRIPTION
**Pull request by aravindhp**
Microsoft is no longer publishing Windows Server 2019 images with Docker in Azure. Given that we have decided to stop supporting Azure for release-4.10.

Ran `make update`.

### CODE REVIEW

**Comment by saifshaikh48** [comment]
/lgtm

I assume you ran `make update`? Please add to the PR message if so

**Comment by aravindhp** [comment]
> /lgtm
> 
> @aravindhp I assume you ran `make update`? Please add to the PR message if so

Good catch, @saifshaikh48. I should have actually added it to the commit message but I have added it to the PR message.

**Pull request merged**
