### PR TITLE
417 hcp

### PR DESCRIPTION
**Pull request by paigerube14**
Adding all node scenarios for hcp

### CODE REVIEW

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-rosa-4.17-nightly-krkn-rosa-hcp-node

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-rosa-4.17-nightly-krkn-rosa-hcp-node periodic-ci-redhat-chaos-prow-scripts-main-rosa-4.17-nightly-krkn-tests-rosa-hcp

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-rosa-4.17-nightly-krkn-tests-rosa-hcp

**Comment by paigerube14** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-rosa-4.17-nightly-krkn-rosa-hcp-node

**Comment by paigerube14** [comment]
@chaitanyaenr @shahsahil264 hcp and node hcp now are passing and should be run on a cadence

**Review by shahsahil264 — APPROVED** [review]
LGTM

**Review by chaitanyaenr — APPROVED** [review]
/lgtm

**Pull request merged**
