### PR TITLE
OCM onboading cluster-proxy

### PR DESCRIPTION
**Pull request by xuezhaojun**
Signed-off-by: xuezhaojun <zxue@redhat.com>

/hold

### CODE REVIEW

**Comment by xuezhaojun** [comment]
> Several files have misspelled `release` in them, for example: `...relase-2.5-presubmits.yaml`

Thanks for the review, I have fixed the misspell issue, please take other look~

**Comment by schmidtd** [comment]
I don't see the files `COMPONENT_NAME` or `COMPONENT_VERSION` in the repo, or the (preferred) OSCI definitions in the `publish` step - for example:
https://github.com/openshift/release/blob/master/ci-operator/config/stolostron/prometheus-operator/stolostron-prometheus-operator-release-2.5.yaml#L74-L75

**Comment by xuezhaojun** [comment]
> I don't see the files `COMPONENT_NAME` or `COMPONENT_VERSION` in the repo, or the (preferred) OSCI definitions in the `publish` step - for example: https://github.com/openshift/release/blob/master/ci-operator/config/stolostron/prometheus-operator/stolostron-prometheus-operator-release-2.5.yaml#L74-L75

Yes, the OSCI definitions in the publish step have been added.

**Review by schmidtd — APPROVED** [review]
/lgtm

**Pull request merged**
