### PR TITLE
OCPQE-23434 Remove unsupported arm jobs

### PR DESCRIPTION
**Pull request by JianLi-RH**
/cc @lwan-wanglin @jianlinliu @shellyyang1989 @jiajliu Please help review.

Discussion is here: https://redhat-internal.slack.com/archives/CF8SMALS1/p1719981606789209

### CODE REVIEW

**Comment by jianlinliu** [comment]
vsphere does not support arm arch.

**Comment by shellyyang1989** [comment]
@JianLi-RH Please check if these profiles are covered in amd jobs. If not, please add them back to amd file

**Comment by JianLi-RH** [comment]
@shellyyang1989 they are added by https://github.com/openshift/release/pull/54740/files

**Pull request merged**
