### PR TITLE
sbo: enable testing on v1.4.x release branch

### PR DESCRIPTION
**Pull request by sadlerap**
This is just a copy of what we have on the v1.3.x release branch configuration, but configured to use the release-v1.4.x branch as a source.

### CODE REVIEW

**Comment by sadlerap** [comment]
Fixed issue with rehearsals failing - was basing this branch off of an outdated version of `master`, so it hadn't picked up #42372, which caused python issues.

**Comment by baijum** [comment]
/pj-rehearse pull-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.12-acceptance

**Comment by baijum** [comment]
/pj-rehearse periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.14-acceptance-lp-interop

**Comment by baijum** [comment]
/pj-rehearse periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.13-acceptance-lp-interop

**Comment by sadlerap** [comment]
Hmmm, these test failures look suspicious to me.  I've never seen these tests fail before in this manner - might be worth a further look/investigation.

**Comment by sadlerap** [comment]
/pj-rehearse periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.13-acceptance-lp-rosa-hypershift periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.12-acceptance-lp-rosa-hypershift-412 periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.14-acceptance-lp-interop periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.13-acceptance-lp-interop

**Comment by sadlerap** [comment]
Note: the updates to non-v1.4.x jobs are a fix for testing deploying the wrong version during lp-interop testing.  SBO's `./install.sh` installs SBO via OLM, which was pulling from SBO's downstream release channel.  This channel doesn't contain SBO v1.4 yet, so outdated versions of SBO were being tested, causing test failures.

I've changed these tests to pull directly from upstream release channels instead - we'll see if there's an improvement.

**Comment by sadlerap** [comment]
/pj-rehearse pull-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.10-acceptance pull-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.11-acceptance pull-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.12-acceptance pull-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.13-acceptance pull-ci-redhat-developer-service-binding-operator-release-v1.4.x-performance periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.14-acceptance-lp-interop periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.13-acceptance-lp-interop periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.12-acceptance-lp-rosa-hypershift-412 periodic-ci-redhat-developer-service-binding-operator-release-v1.3.x-4.13-acceptance-lp-interop periodic-ci-redhat-developer-service-binding-operator-release-v1.3.x-4.14-acceptance-lp-interop

**Comment by sadlerap** [comment]
/pj-rehearse pull-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.10-acceptance pull-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.11-acceptance pull-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.12-acceptance pull-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.13-acceptance pull-ci-redhat-developer-service-binding-operator-release-v1.4.x-performance periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.14-acceptance-lp-interop periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.13-acceptance-lp-interop periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.12-acceptance-lp-rosa-hypershift-412 periodic-ci-redhat-developer-service-binding-operator-release-v1.3.x-4.13-acceptance-lp-interop periodic-ci-redhat-developer-service-binding-operator-release-v1.3.x-4.14-acceptance-lp-interop

**Comment by sadlerap** [comment]
I'm not understanding why v1.4.x is dying on 4.12.  It looks to fail during cluster provisioning?

**Comment by sadlerap** [comment]
/pj-rehearse pull-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.11-acceptance

**Comment by sadlerap** [comment]
/pj-rehearse pull-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.10-acceptance pull-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.11-acceptance pull-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.12-acceptance pull-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.13-acceptance pull-ci-redhat-developer-service-binding-operator-release-v1.4.x-performance periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.14-acceptance-lp-interop periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.13-acceptance-lp-interop periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.12-acceptance-lp-rosa-hypershift-412 periodic-ci-redhat-developer-service-binding-operator-release-v1.3.x-4.13-acceptance-lp-interop periodic-ci-redhat-developer-service-binding-operator-release-v1.3.x-4.14-acceptance-lp-interop

**Pull request merged**
