### PR TITLE
[LPTOCPCI-819] Fix selection of wrong namespace at route creation

### PR DESCRIPTION
**Pull request by smongiar**

### CODE REVIEW

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.14-lp-interop-jboss-fuse-interop-aws

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.14-lp-interop-jboss-fuse-interop-aws

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.14-lp-interop-jboss-fuse-interop-aws

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.14-lp-interop-jboss-fuse-interop-aws

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.14-lp-interop-jboss-fuse-interop-aws

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.14-lp-interop-jboss-fuse-interop-aws

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
