### PR TITLE
[MCO] set go 1.21 build_root for release 2.11 and 2.12

### PR DESCRIPTION
**Pull request by thibaultmg**
Merging a [PR](https://github.com/stolostron/multicluster-observability-operator/pull/1532) in the `release-2.11` raises an [error](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stolostron_multicluster-observability-operator/1532/pull-ci-stolostron-multicluster-observability-operator-release-2.11-test-unit/1813586700773888000) suggesting that tests are being run on go 1.20.
This PR upgrades the `build_root` for ACM release 2.11 and 2.12. It is already set in `main`.

### CODE REVIEW

**Review by douglascamata — APPROVED** [review]
/lgtm

**Comment by thibaultmg** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-release-2.11-test-unit

**Comment by thibaultmg** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-release-2.11-test-unit

**Comment by thibaultmg** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-release-2.11-sonarcloud

**Comment by thibaultmg** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-release-2.12-sonarcloud

**Comment by thibaultmg** [comment]
/pj-rehearse pull-ci-stolostron-multicluster-observability-operator-release-2.11-sonarcloud

**Comment by thibaultmg** [comment]
@douglascamata I just checked and the two failing steps have been failing for a very long time in the repo and thus are expected to fail here. Do you know who could force merge this?

**Comment by thibaultmg** [comment]
/pj-rehearse ack pull-ci-stolostron-multicluster-observability-operator-release-2.11-sonarcloud

**Pull request merged**
