### PR TITLE
GitOps | Changing build-root

### PR DESCRIPTION
**Pull request by varshab1210**

### CODE REVIEW

**Comment by varshab1210** [comment]
/pj-rehearse redhat-developer/gitops-operator/master/v4.10-e2e redhat-developer/gitops-operator/master/v4.12-kuttl-sequential

**Comment by varshab1210** [comment]
/pj-rehearse  pull-ci-redhat-developer-gitops-operator-master-v4.12-kuttl-sequential

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.10-kuttl-sequential

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.11-kuttl-sequential

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.11-kuttl-sequential

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.11-kuttl-sequential

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-gitops-operator-master-v4.11-kuttl-sequential

**Review by wtam2018 — COMMENTED** [review]
/lgtm

**Pull request merged**
