### PR TITLE
Add Serial tests for CNCC on OpenStack

### PR DESCRIPTION
**Pull request by jcaamano**
This comes from already reviewed https://github.com/openshift/release/pull/31468 but @andreaskaris is unavailable right now and we agreed I would follow through with the rework.

Signed-off-by: Andreas Karis <ak.karis@gmail.com>
Signed-off-by: Jaime Caamaño Ruiz <jcaamano@redhat.com>

### CODE REVIEW

**Comment by abhat** [comment]
There was a comment on the original PR to update the OWNERS file with actual content instead of symlink. Can we add that change?

https://github.com/openshift/release/pull/31468#discussion_r955954041

**Comment by abhat** [comment]
@jluhrsen can you take a look as well since you helped review the original PR?

**Comment by jcaamano** [comment]
Something in the egress ip tests makes the test hung when it fails until the job times out.
I don't know why they fail but we probably need to handle `runOcWithRetry` differently, running the command in the background or in a select with a timeout.

**Comment by jcaamano** [comment]
> Something in the egress ip tests makes the test hang when it fails until the job times out.
> I don't know why they fail but we probably need to handle `runOcWithRetry` differently, running the command in the background or in a select with a timeout.
> I don't think that is a problem with this PR in particular.

https://github.com/openshift/origin/pull/27379

**Pull request merged**
