### PR TITLE
Hive: e2e-vsphere

### PR DESCRIPTION
**Pull request by 2uasimojo**
Set up e2e-vsphere for hive:
- [x] Create a wrapper workflow that just sets up and tears down a vsphere cluster without running any tests
- [ ] Create a `pre` step to grab an extra pair of vips for the test
- [x] Run vsphere-specific variant of hive's e2e

[HIVE-2270](https://issues.redhat.com//browse/HIVE-2270)

### CODE REVIEW

**Comment by 2uasimojo** [comment]
/pj-rehearse

This follows #41070.

Expect rehearsals to fail initially, as our e2e script isn't set up for vsphere yet ("unknown cloud: vsphere").

At the moment we're just making sure we can stand up the cluster we'll install hive on.

**Comment by jcpowermac** [comment]
@2uasimojo you are missing the upi-installer image from the config and image pull is failing
Take a look at https://github.com/openshift/release/pull/44273

**Comment by 2uasimojo** [comment]
> @2uasimojo you are missing the upi-installer image from the config and image pull is failing Take a look at #44273

Thanks @jcpowermac! Updated, trying again.

(Aside: Is/should there be a way for that thing to just be part of the ipi-vsphere chain?)

**Comment by 2uasimojo** [comment]
Okay, beautiful, this "worked": It correctly stood up the hub cluster and installed hive on it. Now we need to fix our test script to actually work in vsphere...

**Pull request closed without merging**
