### PR TITLE
ocm: remove latest images mirror for foundation and CLC

### PR DESCRIPTION
**Pull request by zhiweiyin318**

### CODE REVIEW

**Comment by ray-harris** [comment]
@zhiweiyin318 I would prefer for 2.4 you start using the `ocm-ci-image-mirror` workflow to mirror images to Quay. This workflow mirrors the image as soon as the image is built rather than waiting up to an hour to mirror it.

https://github.com/open-cluster-management/cicd-docs/blob/main/prow/additional_config.md#image-mirroring

**Comment by zhiweiyin318** [comment]
@ray-harris I remove the old way of latest images mirror here, and will use ocm-ci-image-mirror workflow .

**Pull request merged**
