### PR TITLE
Configs for knative-build-pipeline release-0.3 branch

### PR DESCRIPTION
**Pull request by arilivigni**

### CODE REVIEW

**Comment by mvinkler** [comment]
@arilivigni there is no release-0.3 branch in [knative-build-pipeline](https://github.com/openshift/knative-build-pipeline/) repo. You should create CI-operator config for master branch (there is release-0.1 in the upstream repo at this point). You also need to generate presubmits/postsubmits jobs from that config. You can run [this command](https://github.com/openshift/release/blob/master/hack/validate-generated-config.sh#L27) to generate these.

**Comment by arilivigni** [comment]
@mvinkler I will make the change to have it for master only

**Comment by arilivigni** [comment]
Master branch file is correct no need for 0.3

**Pull request closed without merging**
