### PR TITLE
switch to gcp-opendatahub cluster profile

### PR DESCRIPTION
**Pull request by riprasad**
Initial PR to test the gcp-opendatahub cluster profile

### CODE REVIEW

**Comment by riprasad** [comment]
/pj-rehearse pull-ci-opendatahub-io-opendatahub-operator-master-opendatahub-manifests-e2e
/pj-rehearse pull-ci-opendatahub-io-opendatahub-operator-master-opendatahub-operator-e2e

**Comment by riprasad** [comment]
/pj-rehearse pull-ci-opendatahub-io-opendatahub-operator-master-opendatahub-manifests-e2e
/pj-rehearse pull-ci-opendatahub-io-opendatahub-operator-master-opendatahub-operator-e2e

**Comment by riprasad** [comment]
/pj-rehearse pull-ci-opendatahub-io-opendatahub-operator-master-opendatahub-operator-e2e

**Comment by riprasad** [comment]
pj-rehearse

**Comment by riprasad** [comment]
The test failure is not related to the changes. New Cluster profile is working. Hence, acknowledging rehearsal.

**Comment by LaVLaS** [comment]
@riprasad Is this a PR that needs to be merged for the cluster-profile migration?

**Comment by riprasad** [comment]
@LaVLaS yes, this is for the new cluster profile.

**Comment by LaVLaS** [comment]
/pj-rehearse pull-ci-opendatahub-io-opendatahub-operator-master-opendatahub-operator-e2e

**Review by zdtsw — APPROVED** [review]
/lgtm

**Comment by riprasad** [comment]
/pj-rehearse pull-ci-opendatahub-io-opendatahub-operator-master-opendatahub-manifests-e2e
/pj-rehearse pull-ci-opendatahub-io-opendatahub-operator-master-opendatahub-operator-e2e

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

**Pull request merged**
