### PR TITLE
update to tectonic-console-builder-v22 in origin-stable

### PR DESCRIPTION
**Pull request by atiratree**

### CODE REVIEW

**Comment by suomiy** [comment]
cc @spadgett

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by spadgett** [comment]
@openshift/openshift-team-developer-productivity-test-platform for approval, thanks!

**Review by alvaroaleman — APPROVED** [review]
FTR, this is only deployed on one cluster that is considered legacy, so for the vast majority of jobs, this does nothing

**Comment by spadgett** [comment]
> FTR, this is only deployed on one cluster that is considered legacy, so for the vast majority of jobs, this does nothing

Hey @alvaroaleman, the image stream isn't synced to other clusters? How can we update our image stream for the new tag?

**Comment by alvaroaleman** [comment]
> Hey @alvaroaleman, the image stream isn't synced to other clusters? How can we update our image stream for the new tag

It is synced to other clusters, but that logic doesn't have to do anything with the change in here. That happens as soon as there is at least one test referencing that imagestreamtag.

I thought the Daemonset you adjusted was a performance optimization to make sure we pre-pull images, but its actually a workaround to a race that only exists in the old 3.11 cluster where a kubelet might decide to garbage collect an image that is in use by a build, causing the build to fail. In 4.X where the builds do not use the kubelets cache at all, this problem doesn't exist.

**Comment by spadgett** [comment]
@alvaroaleman OK, is #13715 safe to merge? The last few times we've done this, we've broken the merge queue, so I was hoping to see rehearse pass this time.

**Pull request merged**
