### PR TITLE
:lady_beetle: Adding a specific timeout to the `e2e-mesh-ocp-*` jobs

### PR DESCRIPTION
**Pull request by cardil**
Fixes https://issues.redhat.com/browse/SRVCOM-2665

## Changes

 - :lady_beetle: Adding a specific timeout to the `e2e-mesh-ocp-*` jobs

/kind bug

Related https://github.com/openshift/release/pull/41818

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by cardil** [comment]
/pj-rehearse periodic-ci-openshift-knative-serverless-operator-main-4.10-e2e-mesh-ocp-410-continuous

Looks like a flake

**Pull request merged**
