### PR TITLE
oko: Require kuttl job for cinder/glance-operator

### PR DESCRIPTION
**Pull request by kajinamit**
... to ensure basic functionality is kept when we merge PRs.

### CODE REVIEW

**Comment by kajinamit** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-cinder-operator-main-cinder-operator-build-deploy-kuttl pull-ci-openstack-k8s-operators-glance-operator-main-glance-operator-build-deploy-kuttl

**Review by Akrog — CHANGES_REQUESTED** [review]
In cinder we find that kuttl gives a good number of false negatives, so we would prefer to keep it optional.

**Comment by kajinamit** [comment]
> In cinder we find that kuttl gives a good number of false negatives, so we would prefer to keep it optional.

OK. I updated the PR to cover only glance.

**Comment by kajinamit** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-glance-operator-main-glance-operator-build-deploy-kuttl

**Comment by kajinamit** [comment]
> > In cinder we find that kuttl gives a good number of false negatives, so we would prefer to keep it optional.
> 
> OK. I updated the PR to cover only glance.

We later learned we have the override command to ignore the job result if we really need it. So as we agreed locally I've readded cinder back. https://docs.ci.openshift.org/docs/how-tos/overriding-failing-ci-jobs/

**Comment by kajinamit** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-cinder-operator-main-cinder-operator-build-deploy-kuttl pull-ci-openstack-k8s-operators-glance-operator-main-glance-operator-build-deploy-kuttl

**Pull request merged**
