### PR TITLE
OCPQE-13810 [Azure] fail to get the resource group in step gather-azure-resource of azure-ipi-resourcegroup job

### PR DESCRIPTION
**Pull request by MayXuQQ**
[azure][Prow CI] fail to get the resource group in step gather-azure-resource of azure-ipi-resourcegroup job

### CODE REVIEW

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-azure-ipi-resourcegroup-p3-f28

**Comment by MayXuQQ** [comment]
@jianlinliu

**Comment by MayXuQQ** [comment]
@jianlinliu  [build-log.txt](https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/36064/rehearse-36064-periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-azure-ipi-resourcegroup-p3-f28/1622505924402876416/artifacts/azure-ipi-resourcegroup-p3-f28/gather-azure-resource/build-log.txt)

> resourceGroupName in /tmp/secret/install-config.yaml: ci-op-g4jnwlgx-f40dc-exrg

**Comment by jianlinliu** [comment]
pls squash multiple commits into one.

**Pull request merged**
