### PR TITLE
e2e qe capi tests for vsphere

### PR DESCRIPTION
**Pull request by miyadav**
/pj-rehearse pull-ci-openshift-cluster-api-provider-vsphere-master-regression-clusterinfra-vsphere-ipi-techpreview

### CODE REVIEW

**Comment by miyadav** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-vsphere-master-regression-clusterinfra-vsphere-ipi-techpreview

**Comment by miyadav** [comment]
@damdo PTAL , it seems good to me , so that we can run it to move rebases to VERIFIED based on this test .
cc @JoelSpeed @shellyyang1989 @sunzhaohua2 @huali9

**Comment by miyadav** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-vsphere-master-regression-clusterinfra-vsphere-ipi-techpreview

**Comment by damdo** [comment]
@miyadav If you are happy with this, this will require a rehearsal ack to merge.

**Comment by miyadav** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-vsphere-master-regression-clusterinfra-vsphere-ipi-techpreview

**Pull request merged**
