### PR TITLE
openshift/velero: konveyor-dev go1.20

### PR DESCRIPTION
**Pull request by kaovilai**

### CODE REVIEW

**Review by sseago — APPROVED** [review]

**Review by shubham-pampattiwar — APPROVED** [review]

**Comment by kaovilai** [comment]
`microdnf not found.

**Comment by kaovilai** [comment]
looks like it's replaceing ubi-8 minimal rather than konveyor/builder.

**Review by shubham-pampattiwar — APPROVED** [review]

**Pull request merged**
