### PR TITLE
ci-operator/openshift/os: Sync 4.12 with master

### PR DESCRIPTION
**Pull request by travier**
This excludes SCOS test jobs that will only ever run on master.

Needs https://github.com/openshift/release/pull/29946 first
/hold

### CODE REVIEW

**Comment by miabbott** [comment]
> With #29947 landed, we should see `release-4.12` fast-forwarded to the state of `master` sometime today (I think the fast-forward job runs hourly?)
> 
> Let's wait for that to happen and then `/retest`

Spoke with DPTP team and this isn't going to happen automatically; will require some intervention from the DPTP team to get us back on track.

Maybe we just manually fast-forward and then `/retest`

**Comment by miabbott** [comment]
> Maybe we just manually fast-forward and then `/retest`

Was recommended to do this by DPTP

/retest

**Comment by travier** [comment]
Thanks, this one is now ready

**Review by HuijingHei — APPROVED** [review]

**Comment by travier** [comment]
\assign @jupierce

**Comment by bparees** [comment]
image name drop approved
/approve

**Pull request merged**
