### PR TITLE
Add missing --tags flag for library periodic import

### PR DESCRIPTION
**Pull request by coreydaley**
Fixes https://github.com/openshift/library/issues/226

### CODE REVIEW

**Comment by gabemontero** [comment]
/lgtm

with no rehearsals we'll just keep an eye on the next periodic

to verify @coreydaley , we can create a dummy PR in cluster-samples-operator that follows the procedure at https://github.com/openshift/cluster-samples-operator#update-the-content-in-this-repository-from-httpsgithubcomopenshiftlibrary

**Comment by coreydaley** [comment]
Are there any tests in the samples operator that verify the content that is imported?

**Comment by yselkowitz** [comment]
@coreydaley this made things worse, almost everything was removed.  Please fix ASAP.

**Pull request merged**
