### PR TITLE
oadp: adding oadp-1.2 to the interop testing

### PR DESCRIPTION
**Pull request by tareqalayan**

### CODE REVIEW

**Comment by tareqalayan** [comment]
@shakyav I am not really following what is missing to creaet a scnario for 1.2 
can you please help.
thanks in advance

**Comment by tareqalayan** [comment]
@calebevans we would like also to have oadp 1.2 scenario as well.
thanks in adavnce

**Comment by calebevans** [comment]
@tareqalayan you need to run the `make update` command while in the root of this repository. Commit the changes the command makes.

**Comment by tareqalayan** [comment]
> @tareqalayan you need to run the `make update` command while in the root of this repository. Commit the changes the command makes.

ack

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-oadp-qe-oadp-qe-automation-main-oadp1.2-ocp4.14-lp-interop-oadp-interop-aws

**Comment by calebevans** [comment]
@tareqalayan when that rehearsal job is finished, if it passes, I will approve this to be merged. Just want to make sure everything works as expected before we merge the change.

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-oadp-qe-oadp-qe-automation-main-oadp1.2-ocp4.14-lp-interop-oadp-interop-aws

**Review by calebevans — APPROVED** [review]
Never mind, the rehearsal won't work until it merges because of the new oadp-e2e-qe image. I will trigger the job after this merges.

/lgtm

**Pull request merged**
