### PR TITLE
LOG-1023: Added CLO add-on E2E job for production

### PR DESCRIPTION
**Pull request by igor-karpukhin**
Added CLO add-on E2E job for production environment

### CODE REVIEW

**Comment by jeefy** [comment]
/assign
@igor-karpukhin can you rebase? I can lgtm afterward :) Thanks!

**Comment by igor-karpukhin** [comment]
@jeefy thanks. I have just rebased it.

**Comment by jeefy** [comment]
/lgtm
Weird that it didn't toss your lgtm on it... 🤔

**Pull request merged**
