### PR TITLE
Allow 'openshift-tracing' to access 'qe-private-deck'

### PR DESCRIPTION
**Pull request by IshwarKanse**
For https://issues.redhat.com/browse/DPTP-3658

### CODE REVIEW

**Review by pavolloffay — APPROVED** [review]

**Comment by IshwarKanse** [comment]
@smg247 Tide was stuck in the retesting loop for this one. I added the reporter config to send the job status in our slack channel for one of our jobs. It has now triggered fresh checks which were stuck earlier. We will need a lgtm label again.

**Comment by IshwarKanse** [comment]
Closing as the team is now added to an existing group openshift-private-ci.

**Pull request closed without merging**
