### PR TITLE
USHIFT-4058: Add job-release label to main jobs

### PR DESCRIPTION
**Pull request by pacevedom**

### CODE REVIEW

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-metal-bootc-test

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-metal-bootc-test

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.17-footprint-and-performance pull-ci-openshift-microshift-release-4.17-metal-bootc-test pull-ci-openshift-microshift-release-4.17-microshift-metal-cache pull-ci-openshift-microshift-release-4.17-microshift-metal-tests pull-ci-openshift-microshift-release-4.17-ocp-full-conformance-rhel-eus pull-ci-openshift-microshift-release-4.17-test-rebase pull-ci-openshift-microshift-release-4.17-test-rpm pull-ci-openshift-microshift-release-4.17-test-unit pull-ci-openshift-microshift-release-4.17-verify pull-ci-openshift-microshift-release-4.14-images pull-ci-openshift-microshift-release-4.14-metal-periodic-test pull-ci-openshift-microshift-release-4.14-microshift-metal-tests pull-ci-openshift-microshift-release-4.14-test-rebase pull-ci-openshift-microshift-release-4.14-test-rpm pull-ci-openshift-microshift-release-4.14-test-unit pull-ci-openshift-microshift-release-4.14-verify pull-ci-openshift-microshift-release-4.16-images pull-ci-openshift-microshift-release-4.16-metal-periodic-test pull-ci-openshift-microshift-release-4.16-microshift-metal-cache pull-ci-openshift-microshift-release-4.16-microshift-metal-tests pull-ci-openshift-microshift-release-4.16-ocp-full-conformance-rhel-eus pull-ci-openshift-microshift-release-4.16-test-rebase pull-ci-openshift-microshift-release-4.16-test-rpm pull-ci-openshift-microshift-release-4.16-test-unit pull-ci-openshift-microshift-release-4.16-verify pull-ci-openshift-microshift-release-4.15-images pull-ci-openshift-microshift-release-4.15-metal-periodic-test pull-ci-openshift-microshift-release-4.15-microshift-metal-cache pull-ci-openshift-microshift-release-4.15-microshift-metal-tests pull-ci-openshift-microshift-release-4.15-ocp-conformance-rhel-eus pull-ci-openshift-microshift-release-4.15-test-rebase pull-ci-openshift-microshift-release-4.15-test-rpm pull-ci-openshift-microshift-release-4.15-test-unit pull-ci-openshift-microshift-release-4.15-verify

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.17-microshift-metal-tests pull-ci-openshift-microshift-release-4.17-test-rebase

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-footprint-and-performance pull-ci-openshift-microshift-main-images pull-ci-openshift-microshift-main-metal-bootc-periodic-test pull-ci-openshift-microshift-main-metal-bootc-test pull-ci-openshift-microshift-main-metal-periodic-test pull-ci-openshift-microshift-main-microshift-metal-cache pull-ci-openshift-microshift-main-microshift-metal-tests pull-ci-openshift-microshift-main-ocp-conformance-rhel-eus pull-ci-openshift-microshift-main-ocp-full-conformance-rhel-eus pull-ci-openshift-microshift-main-test-rebase pull-ci-openshift-microshift-main-verify

**Comment by stbenjam** [comment]
Is this why there's no 4.18 periodics? Do you use the main ones for it?  Jobs need to have the release version in their name, there really shouldn't be any master/main periodics.

https://docs.ci.openshift.org/docs/how-tos/naming-your-ci-jobs/#periodics-outside-of-openshiftrelease has more info about the structure.

Would it help if we sync live? I have some questions about some of these jobs, e.g. `pull-ci-openshift-microshift-release-4.15-metal-periodic-test` - Why does this job have periodic in the name?

**Comment by pacevedom** [comment]
> Is this why there's no 4.18 periodics? Do you use the main ones for it? Jobs need to have the release version in their name, there really shouldn't be any master/main periodics.
> 
> https://docs.ci.openshift.org/docs/how-tos/naming-your-ci-jobs/#periodics-outside-of-openshiftrelease has more info about the suggested directory structure.
> 
> Would it help if we sync live? I have some questions about some of these jobs, e.g. `pull-ci-openshift-microshift-release-4.15-metal-periodic-test` - Why does this job have periodic in the name?

Yeah lets have a quick sync, let me setup something for tomorrow

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.15-images pull-ci-openshift-microshift-release-4.15-ocp-conformance-rhel-eus pull-ci-openshift-microshift-release-4.15-test-rebase pull-ci-openshift-microshift-release-4.17-images pull-ci-openshift-microshift-release-4.17-ocp-conformance-rhel-eus pull-ci-openshift-microshift-release-4.17-test-rebase pull-ci-openshift-microshift-release-4.16-images pull-ci-openshift-microshift-release-4.16-ocp-conformance-rhel-eus pull-ci-openshift-microshift-release-4.16-test-rebase pull-ci-openshift-microshift-main-images pull-ci-openshift-microshift-main-ocp-conformance-rhel-eus pull-ci-openshift-microshift-main-test-rebase pull-ci-openshift-microshift-main-verify pull-ci-openshift-microshift-release-4.14-images pull-ci-openshift-microshift-release-4.14-test-rebase

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-footprint-and-performance pull-ci-openshift-microshift-main-images pull-ci-openshift-microshift-main-metal-bootc-periodic-test pull-ci-openshift-microshift-main-metal-bootc-test pull-ci-openshift-microshift-main-metal-periodic-test pull-ci-openshift-microshift-main-microshift-metal-cache pull-ci-openshift-microshift-main-microshift-metal-tests pull-ci-openshift-microshift-main-ocp-conformance-rhel-eus pull-ci-openshift-microshift-main-ocp-full-conformance-rhel-eus pull-ci-openshift-microshift-main-test-rebase pull-ci-openshift-microshift-main-verify

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-release-4.17-microshift-metal-tests pull-ci-openshift-microshift-release-4.17-test-rebase

**Comment by pacevedom** [comment]
closing in favor of https://github.com/openshift/release/pull/55459

**Pull request closed without merging**
