### PR TITLE
Add Hive job for AWS Gov

### PR DESCRIPTION
**Pull request by fxierh**
Hive supports AWS Gov. We thus add a long-duration job for this platform.

### CODE REVIEW

**Comment by fxierh** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-aws-usgov-ipi-private-f28-long-duration-hive

**Comment by fxierh** [comment]
@jianping-shu I'm wondering if we need another one for EC release images.

**Comment by jianping-shu** [comment]
@fxierh I don't think so for now. The cluster for installing Hive doesn't really matter, so one CI job should be fine.

**Comment by fxierh** [comment]
@liangxia Would you please take a look ? Thanks !

**Pull request merged**
