### PR TITLE
OTA-1338: cincinnati: Install the openssl-devel package for the `cargo-test` test

### PR DESCRIPTION
**Pull request by DavidHurta**
Install the openssl-devel package for the `cargo-test` test.

This pull request references https://issues.redhat.com/browse/OTA-1338

### CODE REVIEW

**Comment by Davoska** [comment]
`ci/rehearse/openshift/cincinnati/master/cargo-test` is failing; however, that's acceptable for this PR. Its tests can be finally compiled and run thanks to this PR. Yes, they fail, but this will be fixed. This PR's goal is to enable the cargo-test to compile the tests.

**Review by petr-muller — APPROVED** [review]
LOL what a shitshow (our CI state, not your PR) :D :D :D

**Comment by petr-muller** [comment]
/pj-rehearse ack 

https://github.com/openshift/release/pull/56238#issuecomment-2326862926

**Pull request merged**
