### PR TITLE
external-dns-operator: remove optional-operators workflow to enable install step

### PR DESCRIPTION
**Pull request by alebedev87**
Remove `optional-operators` workflows to let `install` steps handle the installation of the bundle. Keeping both results into a missing `external-dns-operator` namespace when the `install` step starts.

### CODE REVIEW

**Comment by alebedev87** [comment]
/pj-rehearse pull-ci-openshift-external-dns-operator-main-e2e-aws-shared-vpc-phz-operator

**Comment by alebedev87** [comment]
/pj-rehearse pull-ci-openshift-external-dns-operator-main-e2e-aws-operator

**Comment by alebedev87** [comment]
/pj-rehearse pull-ci-openshift-external-dns-operator-main-e2e-azure-infoblox-operator

**Comment by alebedev87** [comment]
/pj-rehearse pull-ci-openshift-external-dns-operator-main-e2e-aws-shared-vpc-phz-operator

**Comment by alebedev87** [comment]
/pj-rehearse pull-ci-openshift-external-dns-operator-main-e2e-aws-operator

**Review by bradmwilliams — APPROVED** [review]

**Pull request merged**
