### PR TITLE
mimic e2e-aws-proxy jobs in installer,cluster-monitoring-operator rep…

### PR DESCRIPTION
**Pull request by gabemontero**
…os for builder,openshift-controller-manager repos

@adambkaplan @bparees @openshift/openshift-team-developer-experience fyi

I'm curious how the rehearsals go ... not 100% sure these e2e's are feasible, but let's see

### CODE REVIEW

**Comment by gabemontero** [comment]
Hmmm ... it says it can't rehearse them

```
time="2019-09-19T19:49:36Z" level=info msg="Job has been chosen for rehearsal" diffs=" .Agent:   a: ''   b: 'kubernetes'" job-name=pull-ci-openshift-openshift-controller-manager-master-e2e-aws-proxy pr=5102 repo=openshift/openshift-controller-manager
time="2019-09-19T19:49:36Z" level=info msg="Job has been chosen for rehearsal" diffs=" .Agent:   a: ''   b: 'kubernetes'" job-name=pull-ci-openshift-builder-master-e2e-aws-proxy pr=5102 repo=openshift/builder
time="2019-09-19T19:49:36Z" level=warning msg="job is not allowed to be rehearsed. Label pj-rehearse.openshift.io/can-be-rehearsed is required" job=pull-ci-openshift-openshift-controller-manager-master-e2e-aws-proxy pr=5102 repo=openshift/openshift-controller-manager
time="2019-09-19T19:49:36Z" level=warning msg="job is not allowed to be rehearsed. Label pj-rehearse.openshift.io/can-be-rehearsed is required" job=pull-ci-openshift-builder-master-e2e-aws-proxy pr=5102 repo=openshift/builder

```

**Comment by gabemontero** [comment]
ok the rehearsal proxy jobs are running now

**Comment by gabemontero** [comment]
a couple of flakes but the build tests with the proxy enabled cluster ran OK

curious if the git proxy configuration at https://github.com/openshift/release/blob/master/ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml#L819-L820

has any bearing on the git clone's working ... note both http and https are listening on the same port

@ricardomaraschini ^^

**Comment by akram** [comment]
@gabemontero is this supposed to give us the ability to create jobs that run in a "proxied" was environment?

**Comment by gabemontero** [comment]
that is the idea @akram 

though I think the https flavor of the proxy provided is somewhat lacking (though I'm certainly a novice when it comes to https proxy)

**Comment by ricardomaraschini** [comment]
> a couple of flakes but the build tests with the proxy enabled cluster ran OK
> 
> curious if the git proxy configuration at https://github.com/openshift/release/blob/master/ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml#L819-L820
> 
> has any bearing on the git clone's working ... note both http and https are listening on the same port
> 
> @ricardomaraschini ^^

To use the same port is acceptable as long as the protocol used to "talk" to the proxy is  the same. What I mean is that it is perfectly fine to have:

```
http_proxy=http://squid:3128
https_proxy=http://squid:3128
```

This way, even when connecting https the communication with the proxy would be made through http.

**Comment by gabemontero** [comment]
OK this time OCM got the known flake

/retest

**Comment by adambkaplan** [comment]
/lgtm

OOM test is a known flake, Ginkgo re-runs and it _usually_ passes the second time around, which suggests the flake rate is below 50% (probably closer to 10-20%)

**Pull request merged**
