### PR TITLE
Implement IPI on BM with nmstate managed br-ex

### PR DESCRIPTION
**Pull request by qiowang721**
Implement IPI on BM with nmstate managed br-ex, allows managing br-ex bridge configuration with nmstate via injected machine-config on day1.

### CODE REVIEW

**Comment by qiowang721** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-nmstate-f14

**Comment by qiowang721** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-multi-nightly-baremetal-ipi-ovn-ipv4-nmstate-f14

**Comment by qiowang721** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-multi-nightly-baremetal-ipi-ovn-ipv4-nmstate-f14

**Comment by qiowang721** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-multi-nightly-baremetal-ipi-ovn-ipv4-nmstate-f14

**Comment by qiowang721** [comment]
@aleskandro Could you please help to review the new bm ci profile, thanks so much.

**Comment by qiowang721** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.17-multi-nightly-baremetal-ipi-ovn-ipv4-nmstate-f14

**Comment by jhou1** [comment]
Please squash the commits and assign this to someone who should review.

/uncc

**Comment by qiowang721** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-nmstate-f14

**Comment by qiowang721** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-nmstate-f14

**Comment by qiowang721** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-nmstate-f14

**Comment by qiowang721** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-nmstate-f14

**Comment by qiowang721** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-baremetal-ipi-ovn-ipv4-nmstate-f14

**Pull request closed without merging**
