### PR TITLE
Load the cluster before running chaos tests

### PR DESCRIPTION
**Pull request by chaitanyaenr**
This commit enables running cluster-density-v2 to load the cluster with various objects to stress controllers and then run chaos tests to mimic real world environment.

### CODE REVIEW

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-krkn-hub-tests

**Comment by paigerube14** [comment]
Want to [add environment variable](https://github.com/openshift/release/blob/a70603eb137cf7c7dd76e7d395213f482168c0eb/ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__nightly-4.14-loaded-upgrade-from-stable-4.12.yaml#L49) to the workflow. Think we can set this in the workflow file not int he config so it'll apply to all the tests (example like this: https://github.com/openshift/release/blob/a70603eb137cf7c7dd76e7d395213f482168c0eb/ci-operator/step-registry/servicemesh/envoy/e2e/aws/servicemesh-envoy-e2e-aws-workflow.yaml#L16)

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-krkn-hub-tests

**Pull request merged**
