### PR TITLE
Remove source fix_uid.sh from packet-teardown step

### PR DESCRIPTION
**Pull request by YuviGold**

### CODE REVIEW

**Comment by YuviGold** [comment]
@andfasano it seems to keep failing every time on a different issue that is not related to Packet.
I think that we can merge it. WDYT?

**Comment by andfasano** [comment]
> @andfasano it seems to keep failing every time on a different issue that is not related to Packet.
> I think that we can merge it. WDYT?

@YuviGold agree, Packet teardown seems to work properly even in case of failure.

/lgtm

**Pull request merged**
