### PR TITLE
Update preview comment with updated build URLs

### PR DESCRIPTION
**Pull request by aireilly**
Quality of life update - Add updated page URLs to the ocp-preview bot comment.
Test step `openshift-docs-build-docs-commands` outputs a `"${SHARED_DIR}/UPDATED_PAGES"` file which contains a list of all updated page preview URLs. 

Only prow-test-2 branch is currently targeted - will not affect production branches.

Relies on https://github.com/openshift/openshift-docs/blob/main/scripts/get-updated-preview-urls.sh in the openshift-docs repo to generate a list of page URLs.

### CODE REVIEW

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-deploy-preview

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-deploy-preview

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-deploy-preview

**Comment by aireilly** [comment]
/pj-rehearse ci/rehearse/openshift/openshift-docs/prow-test/deploy-preview

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-deploy-preview

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-deploy-preview

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-prow-test-2-deploy-preview

**Review by gabriel-rh — APPROVED** [review]
LGTM

**Pull request merged**
