### PR TITLE
[Prow CI chain Enhancement] update hypershift-aws-create to support QE PublicAndPrivate/Private test

### PR DESCRIPTION
**Pull request by LiangquanLi930**
add `endpoint-access` configuration to support QE continue run e2e test for openshift release.
[OCPQE-13166](https://issues.redhat.com/browse/OCPQE-13166)

### CODE REVIEW

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-aws-ovn-public-private

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-aws-ovn-public-private

**Comment by LiangquanLi930** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.12-periodics-4.12-conformance-aws-ovn

**Comment by sjenning** [comment]
/lgtm
/pj-rehearse periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-aws-ovn

**Comment by LiangquanLi930** [comment]
[OCPQE-13166](https://issues.redhat.com/browse/OCPQE-13166)

**Pull request merged**
