### PR TITLE
Add env option to overwrite kubevirt testing config file

### PR DESCRIPTION
**Pull request by rabin-io**

### CODE REVIEW

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.12-ocp-cnv-odf-4.12-cnv-odf-tests-aws-upi-ocp412

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.12-ocp-cnv-odf-4.12-cnv-odf-tests-aws-upi-ocp412

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.12-ocp-cnv-odf-4.12-cnv-odf-tests-aws-upi-ocp412

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.13-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp412

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.13-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413

**Comment by rabin-io** [comment]
/pj-rehearse ack

tested 4.12 and 4.13

/assign @lukas-bednar

**Comment by rabin-io** [comment]
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.13-ocp-cnv-odf-4.13-cnv-odf-tests-aws-upi-ocp413
/pj-rehearse periodic-ci-RedHatQE-interop-testing-cnv-4.12-ocp-cnv-odf-4.12-cnv-odf-tests-aws-upi-ocp412

**Review by lukas-bednar — APPROVED** [review]
/lgtm

**Pull request merged**
