### PR TITLE
add slack notification to logging jobs

### PR DESCRIPTION
**Pull request by QiaolingTang**
Add slack notification to logging jobs.

/cc @anpingli @kabirbhartiRH @gkarager

### CODE REVIEW

**Comment by QiaolingTang** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-openshift-logging-5.8-aws-ipi-f7-disruptive periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-openshift-logging-5.8-gcp-ipi-sdn-fips-f3 periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-openshift-logging-5.8-azure-ipi-ovn-etcd-encryption-f3

**Comment by QiaolingTang** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-openshift-logging-5.8-azure-ipi-proxy-workers-rhcos-rhel8-f3

**Review by anpingli — COMMENTED** [review]
/lgtm

**Pull request merged**
