### PR TITLE
Sync Serverless CI config/

### PR DESCRIPTION
**Pull request by serverless-qe**

### CODE REVIEW

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve
/ok-to-test

**Comment by dsimansk** [comment]
/pj-rehearse pull-ci-openshift-knative-net-kourier-release-v1.15-416-images

**Comment by dsimansk** [comment]
/pj-rehearse pull-ci-openshift-knative-net-istio-release-v1.15-416-images

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Comment by ReToCode** [comment]
/pj-rehearse pull-ci-openshift-knative-serving-release-v1.15-415-images

**Comment by ReToCode** [comment]
/pj-rehearse pull-ci-openshift-knative-net-istio-release-v1.15-416-images

/pj-rehearse pull-ci-openshift-knative-net-kourier-release-v1.15-416-images

**Pull request merged**
