### PR TITLE
Add env for quay api

### PR DESCRIPTION
**Pull request by flacatus**

### CODE REVIEW

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-rhtap-installer-main-rhtap-installer-e2e

**Comment by xinredhat** [comment]
/pj-rehearse pull-ci-redhat-appstudio-rhtap-installer-release-rhtap-installer-e2e

**Comment by flacatus** [comment]
/pj-rehearse pull-ci-redhat-appstudio-rhtap-installer-release-rhtap-installer-e2e

**Comment by xinredhat** [comment]
/pj-rehearse pull-ci-redhat-appstudio-rhtap-installer-release-1.0-rhtap-installer-e2e

**Comment by xinredhat** [comment]
/pj-rehearse pull-ci-redhat-appstudio-rhtap-installer-release-1.0-images

**Comment by flacatus** [comment]
@xinredhat @Roming22 im missing some envs?

**Comment by flacatus** [comment]
can you lgtm?

**Pull request merged**
