### PR TITLE
add job info in notification

### PR DESCRIPTION
**Pull request by yasun1**
[OCPQE-18417](https://issues.redhat.com//browse/OCPQE-18417)

### CODE REVIEW

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-master-rosacli-aws-rosa-sts-rosacli-e2e-f3

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.14-ec-x86-perfscale-rosa-hcp-3zones-control-plane-24nodes-periodic

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-x86-perfscale-rosa-multiaz-ec-control-plane-24nodes-periodic

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-master-rosacli-aws-rosa-sts-rosacli-e2e-f3

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-master-rosacli-aws-rosa-sts-rosacli-e2e-f3

**Comment by svetsa-rh** [comment]
Hoping that the findings will help https://issues.redhat.com/browse/OCPQE-16941 get resolved.

**Comment by yasun1** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-master-rosacli-aws-rosa-sts-rosacli-e2e-f3

**Pull request merged**
