### PR TITLE
CORS-2959: [4.16] remove sdn tests

### PR DESCRIPTION
**Pull request by jianli-wei**
Remove SDN tests from 4.16. 

What's removed from **4.16__amd64-nightly**:
- aws-ipi-disconnected-sdn-rhcos-rhel8-f14
- aws-ipi-disconnected-sdn-rhcos-rhel8-f28-destructive
- aws-ipi-proxy-sdn-workers-rhel8-fips-f14
- aws-ipi-proxy-sdn-workers-rhel8-fips-f28-destructive
- vsphere-ipi-sdn-f28
- vsphere-ipi-sdn-f28-destructive
- vsphere-ipi-sdn-migration-ovn-f14

What's updated from **4.16__amd64-nightly**:
- vsphere-upi-disconnected-sdn-rhcos-rhel8-f28 **-->** vsphere-upi-disconnected-rhcos-rhel8-f28
- vsphere-upi-disconnected-sdn-rhcos-rhel8-f28-destructive **-->** vsphere-upi-disconnected-rhcos-rhel8-f28-destructive

What's removed from **4.16__multi-nightly**:
- aws-ipi-ovn-migration-sdn-amd-f28
- aws-ipi-ovn-migration-sdn-arm-f28
- aws-ipi-sdn-arm-f14
- aws-ipi-sdn-amd-f28-destructive
- aws-ipi-sdn-migration-ovn-amd-f14
- aws-ipi-sdn-migration-ovn-arm-f14
- aws-ipi-sdn-mtu-migrate-amd-f28
- aws-ipi-sdn-mtu-migrate-arm-f28
- azure-ipi-sdn-migration-ovn-amd-f14
- azure-ipi-sdn-migration-ovn-arm-f14
- azure-ipi-sdn-amd-f28-destructive
- azure-ipi-sdn-arm-f14
- gcp-ipi-sdn-amd-f28-destructive
- gcp-ipi-sdn-arm-f14
- gcp-ipi-sdn-migration-ovn-amd-f28
- gcp-ipi-sdn-migration-ovn-arm-f28
- gcp-upi-private-xpn-sdn-amd-f28-destructive
- gcp-upi-private-xpn-sdn-arm-f14

### CODE REVIEW

**Comment by jianli-wei** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-vsphere-upi-disconnected-rhcos-rhel8-f28

**Comment by jianlinliu** [comment]
lgtm

cc @zhaozhanqi to review.

**Comment by gpei** [comment]
The 4.16 rhel worker job won't pass until https://issues.redhat.com/browse/ART-8558 fixed.

**Comment by gpei** [comment]
cc @liangxia for review

**Comment by gpei** [comment]
Note: this supposed to be merged asap, or else all 4.16 SDN jobs will be failed meaninglessly.

**Comment by liangxia** [comment]
How about the profiles that do 4.15 -> 4.16 upgrade tests ?

**Comment by gpei** [comment]
@liangxia For 4.15 SDN cluster upgraded to 4.16, it won't be broken currently, it's still supported. 
But the deprecation will be backported to 4.15 soon, so later we'll create another PR to remove 4.15 SDN jobs.

**Comment by gpei** [comment]
> For 4.15 SDN cluster upgraded to 4.16, it won't be broken currently, it's still supported

And the same case for 4.14 to 4.15, 4.14 to 4.16 upgrade jobs in the future, 4.14 SDN cluster still could be upgraded to 4.15 or 4.16.

**Comment by liangxia** [comment]
What's the network type on the cluster after we upgrade 4.14 SDN to 4.15, and then 4.16, SDN or OVN ?

**Comment by gpei** [comment]
> What's the network type on the cluster after we upgrade 4.14 SDN to 4.15, and then 4.16, SDN or OVN ?

It's still SDN.

**Comment by gpei** [comment]
The limitation comes from installer side, so only affecting the fresh install. If user specify SDN network type when installing, the installer will quit directly.

**Pull request merged**
