### PR TITLE
Onboard architecture repo

### PR DESCRIPTION
**Pull request by raukadah**
It will allow us to bring openstack bot to the architecture to manage github labels.

### CODE REVIEW

**Comment by abays** [comment]
``` 
{"component":"check-gh-automation","file":"/go/src/github.com/openshift/ci-tools/cmd/check-gh-automation/main.go:270","func":"main.checkRepos","level":"error","msg":"openshift-merge-bot app is not installed for repo","org":"openstack-k8s-operators","repo":"architecture","severity":"error","time":"2024-05-08T10:48:10Z"} 
```

I have since subsequently added the OpenShift Merge Bot to `architecture`.

/test check-gh-automation-tide

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-architecture-main-unit

**Pull request merged**
