### PR TITLE
[WIP] rerun orig ptp ci

### PR DESCRIPTION
**Pull request by jzding**

### CODE REVIEW

**Comment by jzding** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-telco5g-ptp

**Comment by jzding** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-telco5g-ptp

**Comment by jzding** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-telco5g-ptp

**Comment by nishant-parekh** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-telco5g-ptp

**Comment by nishant-parekh** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.17-e2e-telco5g-ptp

**Pull request closed without merging**
