### PR TITLE
Add 4.2 to 4.12 upgrade on AWS

### PR DESCRIPTION
**Pull request by shellyyang1989**
Closes [OCPQE-12664](https://issues.redhat.com/browse/OCPQE-12664)

### CODE REVIEW

**Comment by shellyyang1989** [comment]
Hi @juzhao The [install](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/33958/rehearse-33958-periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-4.12-upgrade-from-stable-4.2-aws-ipi/1590963234456735744) failed at monitoring. Is it relevant to `- ref: ipi-install-monitoringpvc`? Thanks!

**Comment by juzhao** [comment]
> Hi @juzhao The [install](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/33958/rehearse-33958-periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-4.12-upgrade-from-stable-4.2-aws-ipi/1590963234456735744) failed at monitoring. Is it relevant to `- ref: ipi-install-monitoringpvc`? Thanks!

yes, the fix is in 4.4 and above versions

**Comment by shellyyang1989** [comment]
The [test](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/33958/rehearse-33958-periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-4.12-upgrade-from-stable-4.2-aws-ipi/1592139069066842112) passed. It's ready for your review and merge! Thanks @xingxingxia @liangxia

**Pull request merged**
