### PR TITLE
Taking out 412

### PR DESCRIPTION
**Pull request by paigerube14**
4.12 is now at end of life, want to remove this job that tests a 4.12 on gcp

https://issues.redhat.com/browse/OCPQE-23933

### CODE REVIEW

**Comment by qiliRedHat** [comment]
@paigerube14 Do you want to take out the loaded-upgrade file in this pr as well? I just disabled the cron but did not delete the file.

**Comment by paigerube14** [comment]
@qiliRedHat can you recomment on this pr since I had to rebase

**Pull request merged**
