### PR TITLE
jira-lifecycle-plugin: remove bugzilla flags and mounts

### PR DESCRIPTION
**Pull request by AlexNPavel**

### CODE REVIEW

**Review by bradmwilliams — APPROVED** [review]

**Comment by agarwal-mudit** [comment]
Hi @AlexNPavel what is the recommendation for the components which are still using Bugzilla?
For example, Openshift Data Foundation still uses Bugzilla and these changes broke our automation.

**Comment by vikaslaad** [comment]
@agarwal-mudit is this component under OCP product in Bugzilla ? ASAIK no-one should be able to create any new bugs in OCP product.

**Comment by AlexNPavel** [comment]
@agarwal-mudit 
> Hi @AlexNPavel what is the recommendation for the components which are still using Bugzilla? For example, Openshift Data Foundation still uses Bugzilla and these changes broke our automation.

Hello. I'm sorry that these changes broke your automation. I was under the assumption that all teams had moved to Jira. If you can provide the list of github organizations that still use the bugzilla automation, I can revert their configuration to how it was before the https://github.com/openshift/release/pull/39444, which disabled the bugzilla plugin.

**Comment by agarwal-mudit** [comment]
@vikaslaad ODF is Openshift Data Foundation which comes under Redhat Storage products which moved to IBM this year. It is not a component inside OCP.

@AlexNPavel I just need it for red-hat-storage org

**Comment by AlexNPavel** [comment]
@agarwal-mudit I have made PR #39860, which should revert the bugzilla plugin removal for the `red-hat-storage` org.

**Comment by agarwal-mudit** [comment]
> @agarwal-mudit I have made PR #39860, which should revert the bugzilla plugin removal for the `red-hat-storage` org.

Thanks a lot!

**Pull request merged**
