### PR TITLE
Add e2e puppeteer test

### PR DESCRIPTION
**Pull request by musienko-maxim**

### CODE REVIEW

**Comment by musienko-maxim** [comment]
retest/ e2e-puppeteer

**Comment by musienko-maxim** [comment]
/pj-rehearse ci/rehearse/eclipse-che/che-dashboard/add-e2e-puppeteer-test/v11-dashboard-happy-path

**Comment by musienko-maxim** [comment]
/pj-rehearse  pull-ci-eclipse-che-che-dashboard-add-e2e-puppeteer-test-v11-e2e-puppeteer

**Comment by musienko-maxim** [comment]
/pj-rehearse pull-ci-eclipse-che-che-dashboard-add-e2e-puppeteer-test-v11-e2e-puppeteer

**Comment by musienko-maxim** [comment]
/pj-rehearse pull-ci-eclipse-che-che-dashboard-add-e2e-puppeteer-test-v11-e2e-puppeteer

**Comment by musienko-maxim** [comment]
/pj-rehearse pull-ci-eclipse-che-che-dashboard-add-e2e-puppeteer-test-v11-e2e-puppeteer

**Comment by musienko-maxim** [comment]
/pj-rehearse pull-ci-eclipse-che-che-dashboard-add-e2e-puppeteer-test-v11-e2e-puppeteer

**Comment by musienko-maxim** [comment]
/pj-rehearse pull-ci-eclipse-che-che-dashboard-add-e2e-puppeteer-test-v11-e2e-puppeteer

**Comment by musienko-maxim** [comment]
/pj-rehearse pull-ci-eclipse-che-che-dashboard-add-e2e-puppeteer-test-v11-e2e-puppeteer

**Comment by musienko-maxim** [comment]
/pj-rehearse pull-ci-eclipse-che-che-dashboard-add-e2e-puppeteer-test-v11-e2e-puppeteer

**Comment by musienko-maxim** [comment]
/pj-rehearse pull-ci-eclipse-che-che-dashboard-add-e2e-puppeteer-test-v11-e2e-puppeteer

**Comment by musienko-maxim** [comment]
/pj-rehearse pull-ci-eclipse-che-che-dashboard-add-e2e-puppeteer-test-v11-e2e-puppeteer

**Comment by musienko-maxim** [comment]
/pj-rehearse pull-ci-eclipse-che-che-dashboard-add-e2e-puppeteer-test-v11-e2e-puppeteer

**Comment by musienko-maxim** [comment]
/pj-rehearse pull-ci-eclipse-che-che-dashboard-add-e2e-puppeteer-test-v11-e2e-puppeteer

**Comment by musienko-maxim** [comment]
/pj-rehearse pull-ci-eclipse-che-che-dashboard-add-e2e-puppeteer-test-v11-e2e-puppeteer

**Comment by musienko-maxim** [comment]
/pj-rehearse pull-ci-eclipse-che-che-dashboard-add-e2e-puppeteer-test-v11-e2e-puppeteer

**Comment by musienko-maxim** [comment]
/pj-rehearse pull-ci-eclipse-che-che-dashboard-add-e2e-puppeteer-test-v11-e2e-puppeteer

**Comment by musienko-maxim** [comment]
/pj-rehearse pull-ci-eclipse-che-che-dashboard-add-e2e-puppeteer-test-v11-e2e-puppeteer

**Comment by musienko-maxim** [comment]
/pj-rehearse pull-ci-eclipse-che-che-dashboard-add-e2e-puppeteer-test-v11-e2e-puppeteer

**Review by akurinnoy — APPROVED** [review]

**Comment by lobziik** [comment]
@musienko-maxim Hi! I wondering, why do you need 'openshift-eng/rebasebot' related commit in this PR?

As I see, this commit with respective changes is already in the master branch, can you please remove it from this PR? :)

**Comment by musienko-maxim** [comment]
> @musienko-maxim Hi! I wondering, why do you need 'openshift-eng/rebasebot' related commit in this PR?
> 
> As I see, this commit with respective changes is already in the master branch, can you please remove it from this PR? :)

Sorry, my fault, for the long rebasing. All unnecessary commits were removed.

**Review by olexii4 — APPROVED** [review]

**Pull request merged**
