### PR TITLE
USHIFT-1777: Add test-rpm job

### PR DESCRIPTION
**Pull request by pacevedom**

### CODE REVIEW

**Comment by pacevedom** [comment]
Failure was expected. Will retrigger when https://github.com/openshift/microshift/pull/2495 merges.

**Comment by pacevedom** [comment]
Will rehearse again when https://github.com/openshift/microshift/pull/2502 is merged.

**Comment by dhellmann** [comment]
/lgtm
/hold

This looks OK to me. I'll leave a hold so we're not changing CI late on a Friday and to give @pmtk a chance to take a look.

**Pull request merged**
