### PR TITLE
SDN-5423: add option to give extra args to must-gather cmd

### PR DESCRIPTION
**Pull request by jluhrsen**
adding this to ovnk/cno jobs. should be a noop for all other jobs using the mg step

### CODE REVIEW

**Comment by jluhrsen** [comment]
/pj-rehearse pull-ci-openshift-prometheus-alertmanager-release-4.18-e2e-aws-ovn

**Comment by jluhrsen** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-release-4.18-e2e-aws-ovn

**Comment by jluhrsen** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-release-4.18-e2e-aws-ovn

**Comment by jluhrsen** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn

**Comment by jluhrsen** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn

**Comment by jluhrsen** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.18-e2e-aws-ovn

**Comment by jluhrsen** [comment]
tested a [non ovnk job](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/58083/rehearse-58083-periodic-ci-openshift-release-master-ci-4.18-e2e-aws-ovn/1855027195982909440/artifacts/e2e-aws-ovn/gather-must-gather/build-log.txt) and it's not using `--host-network` as well as [aws-ovn in ovnk](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/58083/rehearse-58083-pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn/1855025865218330624/artifacts/e2e-aws-ovn/gather-must-gather/build-log.txt) and it is using it. Both are as expected.

**Comment by jluhrsen** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-release-4.18-e2e-aws-ovn

**Review by trozet — APPROVED** [review]
I see must-gather using host-network:
```
+ echo 'Running must-gather...'
Running must-gather...
+ mkdir -p /logs/artifacts/must-gather
+ oc --insecure-skip-tls-verify adm must-gather --timeout=35m --dest-dir /logs/artifacts/must-gather --host-network
```
thanks jamo!

/lgtm

**Comment by jluhrsen** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.18-e2e-aws-ovn

**Comment by jluhrsen** [comment]
/pj-rehearse periodic-ci-openshift-ovn-kubernetes-master-ci-4.18-e2e-aws-ovn

**Comment by jluhrsen** [comment]
/pj-rehearse pull-ci-openshift-ovn-kubernetes-release-4.18-e2e-aws-ovn

**Pull request merged**
