### PR TITLE
Bump to UBI9

### PR DESCRIPTION
**Pull request by dhaiducek**
Updates `main`, `release-2.11`, and `release-2.10`

### CODE REVIEW

**Comment by dhaiducek** [comment]
Blocked by:
- https://github.com/stolostron/iam-policy-controller/pull/238
- https://github.com/stolostron/cert-policy-controller/pull/287
- https://github.com/stolostron/cert-policy-controller/pull/288
- https://github.com/stolostron/governance-policy-framework/pull/806
- https://github.com/stolostron/governance-policy-framework/pull/807

**Review by JustinKuli — APPROVED** [review]

**Comment by dhaiducek** [comment]
/pj-rehearse pull-ci-stolostron-governance-policy-propagator-main-images pull-ci-stolostron-governance-policy-propagator-release-2.10-images pull-ci-stolostron-governance-policy-propagator-release-2.11-images pull-ci-stolostron-governance-policy-addon-controller-main-images pull-ci-stolostron-governance-policy-addon-controller-release-2.11-images pull-ci-stolostron-governance-policy-addon-controller-release-2.10-images pull-ci-stolostron-iam-policy-controller-release-2.10-images pull-ci-stolostron-config-policy-controller-release-2.11-images pull-ci-stolostron-config-policy-controller-release-2.10-images pull-ci-stolostron-config-policy-controller-main-images pull-ci-stolostron-governance-policy-framework-release-2.11-images pull-ci-stolostron-governance-policy-framework-main-images

**Pull request merged**
