### PR TITLE
Enable converged for assisted master branch

### PR DESCRIPTION
**Pull request by carbonin**
Converged flow should now be usable for all ZTP jobs on the master branch. Removing the master converged-specific job as the base ZTP job is now the same.

https://issues.redhat.com/browse/MGMT-11998

/cc @osherdp @adriengentil @eranco74

### CODE REVIEW

**Comment by eranco74** [comment]
@carbonin I think that now we need to add a job that tests ZTP with converged flow disabled

**Comment by eranco74** [comment]
/pj-rehearse
let's see if it works

**Comment by carbonin** [comment]
Looks like that job failed due to an infra issue.

**Comment by carbonin** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-3masters

**Review by adriengentil — APPROVED** [review]

**Comment by eranco74** [comment]
Seems that this change enabled the converged flow in 2.7 jobs as well
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/35655/rehearse-35655-pull-ci-openshift-assisted-service-release-ocm-2.7-e2e-ai-operator-ztp-capi/1617990200313516032/artifacts/e2e-ai-operator-ztp-capi/assisted-baremetal-operator-gather/artifacts/assisted-service.log

**Pull request merged**
