### PR TITLE
WIP: Test console image for rosa 4.17

### PR DESCRIPTION
**Pull request by chetna14manku**

### CODE REVIEW

**Comment by chetna14manku** [comment]
/pj-rehearse periodic-ci-chetna14manku-serverless-operator-main-p2p-4.17-test-417-rc-iib

**Comment by chetna14manku** [comment]
/pj-rehearse periodic-ci-chetna14manku-serverless-operator-main-p2p-4.17-test-417-rc-iib

**Comment by chetna14manku** [comment]
/pj-rehearse periodic-ci-chetna14manku-serverless-operator-main-p2p-4.17-test-417-rc-iib

**Comment by chetna14manku** [comment]
/pj-rehearse periodic-ci-chetna14manku-serverless-operator-main-p2p-4.17-test-417-rc-iib

**Comment by chetna14manku** [comment]
/pj-rehearse periodic-ci-chetna14manku-serverless-operator-main-p2p-4.17-test-417-rc-iib

**Comment by calebevans** [comment]
/pj-rehearse periodic-ci-chetna14manku-serverless-operator-main-p2p-4.17-test-417-rc-iib

**Comment by chetna14manku** [comment]
/pj-rehearse periodic-ci-chetna14manku-serverless-operator-main-p2p-4.17-test-417-rc-iib

**Pull request closed without merging**
