### PR TITLE
Update config to run new Origin jobs

### PR DESCRIPTION
**Pull request by csrwng**
Adds Jenkins to proxy config and defines new jobs to run from prow

Fixes https://github.com/openshift/release/issues/187

### CODE REVIEW

**Comment by kargakis** [comment]
Awesome

/lgtm

**Comment by stevekuznetsov** [comment]
Can the bot also update other configs like the proxy? @kargakis

**Comment by kargakis** [comment]
Not today. But I can extend the proxy to use the prow config so we can take
advantage of the plugin.

**Comment by kargakis** [comment]
Opened https://github.com/openshift/release/issues/189

**Pull request merged**
