### PR TITLE
openshift/assisted-installer-agent: Initial config

### PR DESCRIPTION
**Pull request by lranjbar**
Continue work from #14874

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/uncc
feel free to ping me once this is not WIP anymore

**Comment by YuviGold** [comment]
Take a look how @djzager made the configuration file for the installer on https://github.com/openshift/release/pull/14728
I think calling `make build` in `binary_build_commands` is the one causing the permission issues.

**Review by YuviGold — APPROVED** [review]
LGTM

**Comment by lranjbar** [comment]
Work for MGMT-3319

**Comment by lranjbar** [comment]
@djzager @YuviGold This one is good to merge now.

**Comment by djzager** [comment]
/assign @alvaroaleman 

Based on this comment https://github.com/openshift/release/pull/15008#issuecomment-762459898

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
