### PR TITLE
integreatly-operator: revert e2e jobs to templates

### PR DESCRIPTION
**Pull request by petr-muller**
The jobs depend on the cluster under test having m4.xlarge workers.

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
Follow.

**Comment by laurafitzgerald** [comment]
@petr-muller I'm happy to `lgtm` this one. We are blocked on merging prs at the moment and have a number of changes we need to get in soon. Is it required for all the pj-rehearsal jobs to pass for this to merge. I understand we are just reverting some changes that were added a couple of days ago and tests were running fine before that.

**Comment by petr-muller** [comment]
@laurafitzgerald I have no idea about how the jobs (did not) work before we moved them to multi-stage (which installs clsuters with different worker sizes - smaller) @KevFan asked for this revert. If the jobs worked fine until Tuesday (which is when we merged the mass migration), it's probably safe to approve it.

**Comment by laurafitzgerald** [comment]
Thanks @petr-muller 
/lgtm

**Pull request merged**
