### PR TITLE
chore(stackrox): switch lower bound OCP from 4.10 to 4.11

### PR DESCRIPTION
**Pull request by gavin-stackrox**
## Validation

- [x] automation flavors (master, x.y) get 4.11 (:heavy_check_mark: 4.11.52)
- [x] openshift/release ipi get 4.11 (:heavy_check_mark: 4.11.52)
- [x] tests support 4.11
  - retesting 4.1 operator

### CODE REVIEW

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-4-11-compliance-e2e-tests	pull-ci-stackrox-stackrox-release-4.0-ocp-4-11-qa-e2e-tests	pull-ci-stackrox-stackrox-release-4.1-ocp-4-11-operator-e2e-tests	pull-ci-stackrox-stackrox-release-4.2-ocp-4-11-ebpf-qa-e2e-tests	pull-ci-stackrox-stackrox-release-4.2-ocp-4-11-ui-e2e-tests	  pull-ci-stackrox-stackrox-release-4.3-ocp-4-11-operator-e2e-tests

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-4-11-compliance-e2e-tests
/pj-rehearse pull-ci-stackrox-stackrox-release-4.0-ocp-4-11-qa-e2e-tests
/pj-rehearse pull-ci-stackrox-stackrox-release-4.1-ocp-4-11-operator-e2e-tests
/pj-rehearse pull-ci-stackrox-stackrox-release-4.2-ocp-4-11-ebpf-qa-e2e-tests
/pj-rehearse pull-ci-stackrox-stackrox-release-4.2-ocp-4-11-ui-e2e-tests
/pj-rehearse pull-ci-stackrox-stackrox-release-4.3-ocp-4-11-operator-e2e-tests

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-4-11-compliance-e2e-tests
/pj-rehearse pull-ci-stackrox-stackrox-release-4.0-ocp-4-11-qa-e2e-tests
/pj-rehearse pull-ci-stackrox-stackrox-release-4.1-ocp-4-11-operator-e2e-tests
/pj-rehearse pull-ci-stackrox-stackrox-release-4.2-ocp-4-11-ebpf-qa-e2e-tests
/pj-rehearse pull-ci-stackrox-stackrox-release-4.2-ocp-4-11-ui-e2e-tests
/pj-rehearse pull-ci-stackrox-stackrox-release-4.3-ocp-4-11-operator-e2e-tests

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-4-11-compliance-e2e-tests pull-ci-stackrox-stackrox-release-4.0-ocp-4-11-qa-e2e-tests pull-ci-stackrox-stackrox-release-4.1-ocp-4-11-operator-e2e-tests pull-ci-stackrox-stackrox-release-4.2-ocp-4-11-ebpf-qa-e2e-tests pull-ci-stackrox-stackrox-release-4.2-ocp-4-11-ui-e2e-tests pull-ci-stackrox-stackrox-release-4.3-ocp-4-11-operator-e2e-tests

**Comment by gavin-stackrox** [comment]
Testing looks good so far from a cluster create basis. But I need to verify version and ensure 4.11 is supported by various tests.

/cc @BradLugo @davdhacs

**Comment by gavin-stackrox** [comment]
/pj-rehearse pull-ci-stackrox-stackrox-release-4.1-ocp-4-11-operator-e2e-tests

**Review by BradLugo — APPROVED** [review]
/lgtm

**Pull request merged**
