### PR TITLE
re-add the e2e-agent-compact job

### PR DESCRIPTION
**Pull request by osherdp**
Returning the job now that a workaround has been implemented in https://github.com/openshift-metal3/dev-scripts/pull/1519.

### CODE REVIEW

**Comment by andfasano** [comment]
/hold

The `e2e-agent-compact` it's currently the only job that verifies the generation of the `agent-installer-api-server` image in the master ci-operator configuration, shipped in the OCP release payload and fundamental for the agent-based installer workflow, so it should be always run in a blocking manner.

A [fix](https://github.com/openshift/installer/pull/6977) is available but currently a more generic issue at rhcos level is preventing its success (see https://issues.redhat.com/browse/OCPBUGS-8036), which is independent by the current repo, since the related rhcos image with the fix seems not be yet available on the 4.14 branch.

A workaround has been pushed to temporary addressed that https://github.com/openshift-metal3/dev-scripts/pull/1519: if successfull, the previous job configuration could be fully restored

**Comment by osherdp** [comment]
> currently

ack. after the dev-scripts workaround merges we can fully restore the configuration
thanks!

**Comment by andfasano** [comment]
Removing the hold since https://github.com/openshift-metal3/dev-scripts/pull/1519 merged

/hold cancel

**Comment by andfasano** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-e2e-agent-compact

**Comment by andfasano** [comment]
@osherdp the bot [wiped out](https://github.com/openshift/release/commit/7552112984b0fa8ac93b8467eadd8148c931c7eb#diff-c57a0b6469c4c70a7423ed9ae84e626bc59f0347557a3b8356ea1247c7c31ec7) the `dev-scripts` image meanwhile, it needs to be re-added:

```
 dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
```

**Comment by osherdp** [comment]
> @osherdp the bot [wiped out](https://github.com/openshift/release/commit/7552112984b0fa8ac93b8467eadd8148c931c7eb#diff-c57a0b6469c4c70a7423ed9ae84e626bc59f0347557a3b8356ea1247c7c31ec7) the `dev-scripts` image meanwhile, it needs to be re-added:
> 
> ```
>  dev-scripts:
>     name: test
>     namespace: ocp-kni
>     tag: dev-scripts
> ```

ack. re-added the base image
thanks!

**Comment by osherdp** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-e2e-agent-compact

**Comment by osherdp** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-e2e-agent-compact

**Comment by osherdp** [comment]
/pj-rehearse ack
:tada:

**Pull request merged**
