### PR TITLE
Add NFD mirorring

### PR DESCRIPTION
**Pull request by zvonkok**
Add NFD mirorring

### CODE REVIEW

**Comment by zvonkok** [comment]
Any update on this?

**Comment by zvonkok** [comment]
@smarterclayton any update on this?

**Comment by zvonkok** [comment]
@smarterclayton rebased and all tests are green. It would be nice if we get those images upstream before the GA.

**Comment by petr-muller** [comment]
Stale PR, please adapt and reopen if still needed.

/close

**Pull request closed without merging**
