### PR TITLE
Add initial operator test for perceptilabs

### PR DESCRIPTION
**Pull request by tmckayus**
This PR should ultimately be against the ROE repository, but the step-registry there needs some work. It is being submitted here to make progress but it should not be merged in the release repository.

### CODE REVIEW

**Comment by tmckayus** [comment]
/retest

add set -x in the test image to figure out why namespace is not available

**Comment by tmckayus** [comment]
/retest

add some oc status calls to setup.sh and run.sh

**Comment by tmckayus** [comment]
/retest

add some more debugging stuff to setup.sh and run.sh

**Comment by tmckayus** [comment]
/retest

fix typos and retest with "oc config get-contexts"

**Comment by tmckayus** [comment]
/retest

(last run did not pick up changes in the image build for some reason)

**Comment by tmckayus** [comment]
/retest

try adding "oc create namespace $NAMESPACE" since NAMESPACE is defined in the env and seems to be the default for oc, but it doesn't exist (also possible that there are no privs to operate on it )

**Comment by tmckayus** [comment]
this still needs work to remove debugging code, as well as refactor the test image since it's referencing multiple repositories (and caching means new changes are not always picked up)

**Comment by tmckayus** [comment]
/retest

(seems to be having some infra problems)

**Comment by tmckayus** [comment]
/retest

test against a clean (squashed) version of the test runner modified for openshift-ci

**Review by stevekuznetsov — APPROVED** [review]

**Pull request merged**
