### PR TITLE
Remove AWS Windows VXLAN tests

### PR DESCRIPTION
**Pull request by sebsoto**
The AWS VXLAN port tests were put in in order to test the functionality
of the VXLAN port option before Windows vSphere functionality was done.
Now that vSphere Windows tests are proven to be adequately stable, the
AWS VXLAN port tests can be removed, as the existing vSphere tests
fully test the VXLAN option code path in the WMCO.

the job changes were generated by editing the config files and running
`make jobs`

### CODE REVIEW

**Comment by JacobTanenbaum** [comment]
why would we be removing these tests? we need to ensure that this remains stable as we make changes.

**Comment by aravindhp** [comment]
> why would we be removing these tests? we need to ensure that this remains stable as we make changes.

@JacobTanenbaum we are not removing these test but replacing them with the default VXLAN port test for AWS. The custom VXLAN port is tested with the vSphere test.

**Pull request merged**
