### PR TITLE
add acm 211 components test images

### PR DESCRIPTION
**Pull request by vboulos**
Add the ACM 2.11 components test images in order for them to get promoted to Prow

### CODE REVIEW

**Comment by vboulos** [comment]
/pj-rehearse pull-ci-stolostron-application-ui-test-release-2.11-images pull-ci-stolostron-observability_core_automation-release-2.11-images pull-ci-stolostron-acmqe-clc-test-release-2.11-images pull-ci-stolostron-acmqe-grc-test-release-2.11-images pull-ci-stolostron-clc-ui-e2e-release-2.11-images

**Review by Kyl-Bempah — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
