### PR TITLE
Move vSphere job to devqe

### PR DESCRIPTION
**Pull request by sgaoshang**
We'll move some connected job to IBMC vsphere 8 devqe

### CODE REVIEW

**Comment by sgaoshang** [comment]
/pj-rehears periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-vsphere-ipi-sdn-f14

**Comment by sgaoshang** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-vsphere-ipi-sdn-f14

**Comment by sgaoshang** [comment]
@jianlinliu @yunjiang29 pls help to review it, if more job need to move to devqe, pls let me know, thanks.

**Comment by jianlinliu** [comment]
cc @liangxia to review

**Pull request merged**
