### PR TITLE
Bug 1707486: testing the plugin

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by jsafrane** [comment]
/test config
(all chrome extensions disabled)

**Comment by jsafrane** [comment]
/test pj-rehearse
(firefox)

**Comment by jsafrane** [comment]
/retest
(do I have permissions in this repo?)

**Comment by jsafrane** [comment]
/test config
(incognito mode)

**Comment by petr-muller** [comment]
/test pj-rehearse
(firefox)

**Comment by petr-muller** [comment]
/test pj-rehearse
(ff)

**Pull request closed without merging**
