### PR TITLE
ETCD-537:use build-root from repository for openshift/etcd 4.13

### PR DESCRIPTION
**Pull request by Elbehery**
This PR uses build root from openshift/etcd repo for release 4.13

/assign @soltysh
/assign @dusk125
/assign @hasbro17

### CODE REVIEW

**Comment by Elbehery** [comment]
/hold

wait for https://github.com/openshift/etcd/pull/245

**Comment by Elbehery** [comment]
must wait for https://github.com/openshift/etcd/pull/252

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
