### PR TITLE
openshift-ansible-aws: remove tests pod and don't collect artifacts

### PR DESCRIPTION
**Pull request by vrutkovs**
Kubeconfig for admin contains internal AWS IP, so tests can't run and
node data, events can't be collected. In any case the tests are being run in GCP jobs.

@bbguimaraes PTAL

### CODE REVIEW

**Comment by bbguimaraes** [comment]
Shouldn't the provisioner be fixed instead?

What's the point of the job/template if no tests are run?

**Comment by vrutkovs** [comment]
>Shouldn't the provisioner be fixed instead?

We could create a new cluster-admin user and use it for connection, yes - but that might be a security risk.

> What's the point of the job/template if no tests are run?

Playbooks check mostly - dynamic playbooks use a different set of playbooks, so we need to ensure the cluster can be setup correctly with `prerequisites` and `deploy_cluster` playbooks. There is no need to run a full validation of installed Openshift, as its being done in gcp jobs already

**Comment by stevekuznetsov** [comment]
This is wrong and should not have been merged. It is not acceptable to not run the e2e tests in an e2e template.

**Comment by smarterclayton** [comment]
Correct - this needs to be fixed.  Not running e2e is not acceptable.  Not collecting artifacts isn’t acceptable.  Not making the provision consistent with gcp isn’t acceptable.

**Pull request merged**
