### PR TITLE
added more exported vairables

### PR DESCRIPTION
**Pull request by xinredhat**
Added more exported variables  to support Pac work with sprayproxy+github app

### CODE REVIEW

**Review by psturc — APPROVED** [review]

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-image-controller-main-image-controller-e2e

**Comment by xinredhat** [comment]
/pj-rehearse pull-ci-redhat-appstudio-image-controller-main-image-controller-e2e

**Comment by xinredhat** [comment]
/pj-rehearse pull-ci-redhat-appstudio-image-controller-main-image-controller-e2e

**Comment by xinredhat** [comment]
@psturc I just now realised that `ci/rehearse/redhat-appstudio/image-controller/main/image-controller-e2e` cannot pass, because the accordingly test cases also need to be updated, here is the [PR](https://github.com/redhat-appstudio/e2e-tests/pull/703), we need to merge the both to make e2e test work

**Comment by psturc** [comment]
/pj-rehearse pull-ci-redhat-appstudio-image-controller-main-image-controller-e2e

**Review by psturc — APPROVED** [review]

**Pull request merged**
