### PR TITLE
OCPQE-21261-scans-capiprovideribm,mapiaws,mapiazure,mapi,clustermachi…

### PR DESCRIPTION
**Pull request by miyadav**
…neapprover

Adding in bunch of 5 repos , so we have enough time to review , will follow the same process of opening bugs for dev to review(in case of sast scan failures) once green will remove optional..
@huali9 @sunzhaohua2 @JoelSpeed @shellyyang1989 PTAL when time permits .

### CODE REVIEW

**Comment by miyadav** [comment]
Apart from cluster-machine-approver , nothing else , looks like needs any bug / review PTAL when time permits , will create a bug for cluster-machine-approver only  . 
[cluster-api-provider-ibm](https://app.snyk.io/org/openshift-ci-internal/project/41470181-b64f-4f90-a7f3-fc7a035b151d/history/685332cc-b7b9-447f-b10f-41667f86883f?fromGitHubAuth=true) can be ignored permanently 
[machine-api-provider](https://app.snyk.io/org/openshift-ci-internal/project/d93899d6-f2f1-43d5-99cf-337ca21b7a94/history/abef7d46-de4b-4ca9-9317-473ae26e1256) also looks like reviewed in other sast scan bugs and should be ok to be ignored.
Opened [bug](https://issues.redhat.com/browse/OCPBUGS-45294) for review.

**Review by damdo — COMMENTED** [review]
Thanks a lot for adding this @miyadav 

/approve
/lgtm

**Pull request merged**
