### PR TITLE
Switch to Go 1.19 builders for the Submariner addon

### PR DESCRIPTION
**Pull request by skitt**

### CODE REVIEW

**Comment by skitt** [comment]
/pj-rehearse pull-ci-stolostron-submariner-addon-main-build
/pj-rehearse pull-ci-stolostron-submariner-addon-main-images
/pj-rehearse pull-ci-stolostron-submariner-addon-main-integration
/pj-rehearse pull-ci-stolostron-submariner-addon-main-unit
/pj-rehearse pull-ci-stolostron-submariner-addon-main-verify
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.3-build
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.3-images
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.3-integration
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.3-unit
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.3-verify
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.4-build
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.4-images
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.4-integration
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.4-unit
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.4-verify
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.5-build
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.5-images
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.5-integration
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.5-unit
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.5-verify
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.6-build
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.6-images
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.6-integration
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.6-unit
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.6-verify
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.7-build
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.7-images
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.7-integration
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.7-unit
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.7-verify
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.8-build
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.8-images
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.8-integration
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.8-unit
/pj-rehearse pull-ci-stolostron-submariner-addon-release-2.8-verify

**Comment by skitt** [comment]
/pj-rehearse pull-ci-stolostron-submariner-addon-main-images pull-ci-stolostron-submariner-addon-main-integration pull-ci-stolostron-submariner-addon-main-unit pull-ci-stolostron-submariner-addon-main-verify pull-ci-stolostron-submariner-addon-release-2.3-build pull-ci-stolostron-submariner-addon-release-2.3-images pull-ci-stolostron-submariner-addon-release-2.3-integration pull-ci-stolostron-submariner-addon-release-2.3-unit pull-ci-stolostron-submariner-addon-release-2.3-verify pull-ci-stolostron-submariner-addon-release-2.4-build pull-ci-stolostron-submariner-addon-release-2.4-images pull-ci-stolostron-submariner-addon-release-2.4-integration pull-ci-stolostron-submariner-addon-release-2.4-unit pull-ci-stolostron-submariner-addon-release-2.4-verify pull-ci-stolostron-submariner-addon-release-2.5-build pull-ci-stolostron-submariner-addon-release-2.5-images pull-ci-stolostron-submariner-addon-release-2.5-integration pull-ci-stolostron-submariner-addon-release-2.5-unit pull-ci-stolostron-submariner-addon-release-2.5-verify pull-ci-stolostron-submariner-addon-release-2.6-build pull-ci-stolostron-submariner-addon-release-2.6-images pull-ci-stolostron-submariner-addon-release-2.6-integration pull-ci-stolostron-submariner-addon-release-2.6-unit pull-ci-stolostron-submariner-addon-release-2.6-verify pull-ci-stolostron-submariner-addon-release-2.7-build pull-ci-stolostron-submariner-addon-release-2.7-images pull-ci-stolostron-submariner-addon-release-2.7-integration pull-ci-stolostron-submariner-addon-release-2.7-unit pull-ci-stolostron-submariner-addon-release-2.7-verify pull-ci-stolostron-submariner-addon-release-2.8-build pull-ci-stolostron-submariner-addon-release-2.8-images pull-ci-stolostron-submariner-addon-release-2.8-integration pull-ci-stolostron-submariner-addon-release-2.8-unit pull-ci-stolostron-submariner-addon-release-2.8-verify

**Comment by skitt** [comment]
/pj-rehearse ack

The verify jobs are failing because formatting changed in Go 1.19. We’ll need to fix the branches up after this is merged, we can’t handle it ahead of time.

**Comment by sridhargaddam** [comment]
> /cc @sridhargaddam @tpantelis

Jobs are failing, but we trust you'll fix it in follow up PRs :+1:

**Pull request merged**
