### PR TITLE
skip ui case in cypress for special cluster

### PR DESCRIPTION
**Pull request by yanpzhan**
Try to skip console case in cypress. since pr https://github.com/openshift/release/pull/33046/files is open, copy code in it here for testing purpose, will remove them after that pr merged.

### CODE REVIEW

**Comment by yanpzhan** [comment]
@kuiwang02 could you help to approve the pr? thanks!

**Comment by kuiwang02** [comment]
@yanpzhan it is already approved.
per message `tide Pending — Not mergeable. Must be by author openshift-bot OR Needs rehearsals-ack label.`, you need `/pj-rehearse ack` to let it merged.

**Pull request merged**
