### PR TITLE
OSSM-4014 Add 3.0 job that updates istio charts in istio-operator repo

### PR DESCRIPTION
**Pull request by dgn**
This also fixes the push-image job by using the new targets

### CODE REVIEW

**Comment by dgn** [comment]
The prowjob rehearse fails because there's a cross-dependency between the changes in https://github.com/maistra/istio-operator/pull/1196 and this change. I think we should merge this first (I tested the steps locally) and then /retest the other PR

**Review by jwendell — APPROVED** [review]

**Pull request merged**
