### PR TITLE
MULTIARCH-4859 Adding an etcd optimization for slower disks

### PR DESCRIPTION
**Pull request by tvardema**

### CODE REVIEW

**Comment by prb112** [comment]
/lgtm 
Great stuff. 

One thought you could use `-n "${SLOWER_ETCD}` and have the default an empty string.
Then you could configure it to use STANDARD/SLOWER or a different value in the future. https://docs.openshift.com/container-platform/4.15/scalability_and_performance/recommended-performance-scale-practices/recommended-etcd-practices.html#etcd-changing-hardware-speed-tolerance_recommended-etcd-practices

**Comment by tvardema** [comment]
> ... you could configure it to use STANDARD/SLOWER or a different value in the future.
Took a "hybrid" approach to making that happen.  Should allow for setting any kinds of details going forward, rather than just a boolean.  Thanks!

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-ovn-remote-libvirt-s390x

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-ovn-remote-libvirt-s390x

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-ovn-remote-libvirt-s390x

**Comment by tvardema** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.18-ocp-e2e-ovn-remote-libvirt-s390x

**Review by prb112 — APPROVED** [review]
/lgtm

**Pull request merged**
