### PR TITLE
updating openshift-preflight presubmit jobs to run on ocp 4.13

### PR DESCRIPTION
**Pull request by acornett21**
- move from 4.12 to 4.13, 4.12 soon to be EUS.
- remove 4.16, now that 4.17 is being used.

### CODE REVIEW

**Comment by acornett21** [comment]
/pj-rehearse pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.13-e2e pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.13-images

**Review by skattoju — APPROVED** [review]
/lgtm

**Review by komish — APPROVED** [review]
/lgtm

**Pull request merged**
