### PR TITLE
Change repo for NVIDIA GPU tests on 4.13

### PR DESCRIPTION
**Pull request by empovit**
Replace the old test repo with nvidia-ci for:
* All NVIDIA GPU Operator tests on 4.13
* NVIDIA GPU Operator from bundle on 4.14

### CODE REVIEW

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-nvidia-ci-main-4.13-nvidia-gpu-operator-e2e-23-9-x
/pj-rehearse periodic-ci-rh-ecosystem-edge-nvidia-ci-main-4.13-nvidia-gpu-operator-e2e-master

**Comment by empovit** [comment]
/pj-rehearse periodic-ci-rh-ecosystem-edge-nvidia-ci-main-4.13-nvidia-gpu-operator-e2e-master

**Review by wabouhamad — COMMENTED** [review]
/lgtm

**Comment by empovit** [comment]
Replaced by #51747

**Pull request closed without merging**
