### PR TITLE
Change metal-ipi workflows to new metal-ipi steps

### PR DESCRIPTION
**Pull request by ardaguclu**

### CODE REVIEW

**Comment by ardaguclu** [comment]
@bparees could you please have a look at this change?, we are moving every metal workflow to new steps. Thanks.

**Comment by bparees** [comment]
@ardaguclu have you looked into why the rehearsals failed?  i'd expect to see passing rehearsals on a PR like this before we merge it.

**Comment by ardaguclu** [comment]
Thanks @bparees. I checked all the failed jobs and they are all known flaky tests(currently we are trying to sort out). pj-rehearse runs 11 metal ipi jobs and all jobs become green at the same time is unfortunately low probability. But maybe it is better to retest again. 

/retest

**Comment by bparees** [comment]
> Thanks @bparees. I checked all the failed jobs and they are all known flaky tests(currently we are trying to sort out). pj-rehearse runs 11 metal ipi jobs and all jobs become green at the same time is unfortunately low probability. But maybe it is better to retest again.

as long as the failures are test failures, and not "the cluster didn't even install correctly/the job definition is completely broken", that's fine.


/lgtm
/approve

**Pull request merged**
