### PR TITLE
OCM-10806 | TESTONLY: compatible smoke check with new released rhcs provider

### PR DESCRIPTION
**Pull request by xueli181114**

### CODE REVIEW

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-critical-high-163 periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-private-critical-high-f3 periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-shared-vpc-critical-high-f3 periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-advanced-critical-high-f3 periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-private-critical-high-f3

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-critical-high-163

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-private-critical-high-f3

**Comment by xueli181114** [comment]
/pj-rehearse  periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-shared-vpc-critical-high-f3

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-advanced-critical-high-f3

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-hcp-private-critical-high-f3

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-private-critical-high-f3

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-private-critical-high-f3

**Comment by radtriste** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-private-critical-high-f3

**Comment by xueli181114** [comment]
periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-shared-vpc-critical-high-f3

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-critical-high-163

**Comment by xueli181114** [comment]
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-shared-vpc-critical-high-f3

**Pull request closed without merging**
