### PR TITLE
bump kuttl version to 0.17.0

### PR DESCRIPTION
**Pull request by stuggi**

### CODE REVIEW

**Comment by stuggi** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl

**Comment by stuggi** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-cinder-operator-main-cinder-operator-build-deploy-kuttl

**Review by abays — APPROVED** [review]
/lgtm

**Comment by viroel** [comment]
/pj-rehearse ack

looks good.
we don't need to run all kuttl jobs in order to validate (there are 20 jobs) 
one example of image build with kuttl 0.17: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/53841/rehearse-53841-pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl/1807703254079901696/artifacts/build-logs/openstack-operator-ci-build-deploy-kuttl-amd64.log

**Pull request merged**
