### PR TITLE
compliance-operator: Add openscap image as dependency

### PR DESCRIPTION
**Pull request by JAORMX**
We want to build this image more often and be able to properly test it.

Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>

### CODE REVIEW

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 089e85345aee2d0da02c379f52f21f139a34bf7f

**Review by jhrozek — APPROVED** [review]
/approve

**Review by jhrozek — APPROVED** [review]
/approve
/lgtm

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now bc2c4b3171e2d216459b78eecbe92bdcc0dafb0f

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 1185a38e68a816d37c7804bd05a1a5968a1f55eb

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 6a18c1c7a13afc0d7eb4e5efe8e6d1e6e8804288

**Review by stevekuznetsov — APPROVED** [review]

**Comment by stevekuznetsov** [comment]
@smarterclayton going to green-light this one as it only removes from the list of published images

**Pull request merged**
