### PR TITLE
MGMT-19084: Bump cluster pools for assisted-service

### PR DESCRIPTION
**Pull request by danmanor**
## The matrix is:

| Source | Target |
|--------|--------|
| 2.9   | 4.15   |
| 2.10    | 4.15   |
| 2.11    | 4.16   |
| 2.12   | 4.17   |
| master | 4.17   |

### CODE REVIEW

**Comment by adriengentil** [comment]
master should be 4.18 now, no?

**Comment by danmanor** [comment]
@adriengentil There is no 4.18 cluster yet

**Pull request merged**
