### PR TITLE
unlock jenkins plugin repo protection to facilitate propagation of je…

### PR DESCRIPTION
**Pull request by gabemontero**
…nkins update center versioning; protection still on the jenkins repo for the image update

/assign @bparees

### CODE REVIEW

**Comment by bparees** [comment]
@coverprice @stevekuznetsov (or someone else who understands the branch protection logic), we have a restriction "team-jenkins" on our jenkins plugin repos, yet members of that team still cannot manually merge.  Have we configured this incorrectly?  Can you give us a proper configuration so that we can give manual merge to members of that team, on those repos?

I'd rather not disable branch protection entirely if we can help it.

**Comment by gabemontero** [comment]
Based on my read of https://github.com/kubernetes/test-infra/blob/master/prow/cmd/branchprotector/README.md#fields  and the code https://github.com/kubernetes/test-infra/blob/master/prow/config/branch_protection.go#L224-L259

the `restrictions` section will say that only `team-jenkins` can push/merge to the repo even with `protect` set to `false`

but this is my first time looking at test-infra in any detail ... maybe I'm missing a nuance

**Comment by bparees** [comment]
> but this is my first time looking at test-infra in any detail ... maybe I'm missing a nuance

my understanding is protect=false would mean anyone w/ write access to the repo can push.

However looking at our repos, team-jenkins is indeed listed as being allowed to push to the branches, so i do not know why we are not getting the merge button.  I think we need the DPT team to take a look and straighten this out.

**Comment by stevekuznetsov** [comment]
With `enforce_admins: true` members of that team _should_ be able to merge, but when the required jobs are passing. If you want to merge over broken CI manually, you'll need to set `enforce_admins: false`. Do not set `protect: false` as that turns off branch protection. Does this make sense?

**Comment by bparees** [comment]
> With enforce_admins: true members of that team should be able to merge, but when the required jobs are passing. If you want to merge over broken CI manually, you'll need to set enforce_admins: false. Do not set protect: false as that turns off branch protection. Does this make sense?

it makes sense other than the fact that members of team jenkins are not "admins", so the idea that "enforce_admins" has any bearing on the behavior seems odd.

@gabemontero go ahead and set enforce_admins to false on the repos, leave branch protection on, and let's see if we get what we want.

**Comment by gabemontero** [comment]
updated @bparees 

thanks @stevekuznetsov

**Comment by stevekuznetsov** [comment]
Yeah sorry, that's the [GitHub name](https://developer.github.com/v3/repos/branches/#update-branch-protection) for that field.

**Comment by gabemontero** [comment]
it worked in that I have the merge button in PRs 

however, as the explanations here lead me to believe @bparees I still can't manually push the release commits after cutting a new plugin release from the upstream jenkinsci repos directly into the analogous openshift repos

I guess I'll have to craft a PR for that now

**Comment by bparees** [comment]
I would expect anyone who has the merge button to be able to push directly to the branch.

**Comment by gabemontero** [comment]
that is not the case ... just tried it

**Comment by gabemontero** [comment]
also, the merge button is greyed out in https://github.com/openshift/jenkins-openshift-login-plugin/pull/50 and is not enabled ... I bet it won't be enabled until the test passes

**Comment by bparees** [comment]
These changes don't propogate until the sync job runs, so i wouldn't expect any of these changes to be applied..   dunno if @stevekuznetsov has a way to force it to happen sooner.

**Comment by gabemontero** [comment]
The merge button showed up almost immediately for me in https://github.com/openshift/jenkins-openshift-login-plugin/pull/49 after this PR merged

Note though, the tests there had previously passed

**Pull request merged**
