### PR TITLE
Follow redirects when fetching openshift client tools for devfile registry test

### PR DESCRIPTION
**Pull request by josephca**
Signed-off-by: Joseph Kim <joskim@redhat.com>

devfile registry and registry-operator tests are failed with the following error. Like https://github.com/openshift/release/pull/31457, all curls
to mirror.openshift.com should follow redirects.

```
 * could not run steps: step registry-test failed: "registry-test" test steps failed: "registry-test" pod "registry-test-registry-test-steps" failed: the pod ci-op-j5cqcxvj/registry-test-registry-test-steps failed after 9s (failed containers: test): ContainerFailed one or more containers exited
Container test exited with code 1, reason Error
---
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

### CODE REVIEW

**Comment by josephca** [comment]
Fixes https://github.com/devfile/api/issues/938

**Review by johnmcollier — APPROVED** [review]
/lgtm
/approve

**Review by elsony — APPROVED** [review]
/lgtm

**Pull request merged**
