### PR TITLE
Use the new hive kubeconfig in e2e test

### PR DESCRIPTION
**Pull request by hongkailiu**
https://issues.redhat.com/browse/DPTP-2187

/hold

wait for https://github.com/openshift/release/pull/18702

I will clean up the secrets and pools, and hive deployment on app.ci in the end of the story.

### CODE REVIEW

**Review by alvaroaleman — APPROVED** [review]

**Comment by hongkailiu** [comment]
```console
$ oc --context build01 delete secret app.ci-hive-credentials -n test-credentials --as system:admin
secret "app.ci-hive-credentials" deleted

$ oc --context build02 delete secret app.ci-hive-credentials -n test-credentials --as system:admin
secret "app.ci-hive-credentials" deleted

$ oc --kubeconfig ~/Documents/secret/joe2/sa.config-updater.vsphere.config delete secret app.ci-hive-credentials -n test-credentials
secret "app.ci-hive-credentials" deleted

$ oc --kubeconfig ~/Documents/secret/christian/sa.config-updater.arm.config delete secret app.ci-hive-credentials -n test-credentials
secret "app.ci-hive-credentials" deleted

$ oc --context build01 delete secret app.ci-hive-credentials -n ci --as system:admin
secret "app.ci-hive-credentials" deleted

$ oc --context build02 delete secret app.ci-hive-credentials -n ci --as system:admin
secret "app.ci-hive-credentials" deleted

$ oc --kubeconfig ~/Documents/secret/joe2/sa.config-updater.vsphere.config delete secret app.ci-hive-credentials -n ci
secret "app.ci-hive-credentials" deleted

$ oc --kubeconfig ~/Documents/secret/christian/sa.config-updater.arm.config delete secret app.ci-hive-credentials -n ci
secret "app.ci-hive-credentials" deleted
```

**Comment by hongkailiu** [comment]
`sa.hive.app.ci.config` is removed from Vault.

```console
$ oc delete ns ci-cluster-pool --wait=false --as system:admin
namespace "ci-cluster-pool" deleted

$ oc delete ns fake-cluster-pool --wait=false --as system:admin
namespace "fake-cluster-pool" deleted

$ oc delete ClusterImageSet ocp-4.7.0-amd64 --as system:admin
clusterimageset.hive.openshift.io "ocp-4.7.0-amd64" deleted

$ oc delete -f clusters/hive/admin_hive_rbac.yaml --as system:admin                 
serviceaccount "hive" deleted
clusterrolebinding.rbac.authorization.k8s.io "ci-hive-creator" deleted
clusterrole.rbac.authorization.k8s.io "ci-hive-creator" deleted
clusterrolebinding.rbac.authorization.k8s.io "ci-hive-viewer" deleted
clusterrole.rbac.authorization.k8s.io "ci-hive-viewer" deleted

$ oc delete HiveConfig hive --as system:admin
hiveconfig.hive.openshift.io "hive" deleted

$ oc --context app.ci adm policy add-cluster-role-to-user cluster-admin hongkailiu --as system:admin
clusterrole.rbac.authorization.k8s.io/cluster-admin added: "hongkailiu"

#uninstall the cluster from OperatorHub UI

$ oc --context app.ci adm policy remove-cluster-role-from-user cluster-admin hongkailiu
clusterrole.rbac.authorization.k8s.io/cluster-admin removed: "hongkailiu"


```

**Comment by hongkailiu** [comment]
```console
$ oc get pod -n hive
No resources found in hive namespace.

$ oc delete ns hive --wait=false --as system:admin
namespace "hive" deleted
```

**Pull request merged**
