### PR TITLE
run one conformance test for sanity

### PR DESCRIPTION
**Pull request by osherdp**
Make a sanity test of our ability to access the created cluster.
This will probably only be applied to presubmit jobs, where we don't really want to run all conformance tests (but do want to validate accessibility)

### CODE REVIEW

**Comment by osherdp** [comment]
/cc @YuviGold 
once we have the fix in place we can use this

**Comment by YuviGold** [comment]
Sounds good :+1: Depends on https://github.com/openshift/assisted-test-infra/pull/928

**Comment by YuviGold** [comment]
I suggest making an internal condition to verify the job type. In case it's peridioc - run full. Otherwise - run minimal. WDYT?

**Comment by osherdp** [comment]
I must say I don't believe in those kind of under-the-hood configurations
I would prefer having it explicitly mentioned instead of letting other people (or me in the future) guess what it's using

**Comment by YuviGold** [comment]
> I must say I don't believe in those kind of under-the-hood configurations
> I would prefer having it explicitly mentioned instead of letting other people (or me in the future) guess what it's using

Currently, we have 2 workflows that we on and off get confused by. I think that this under-the-hood behavior isn't relevant for most of the maintainers. What do you suggest in order to provide simplicity and alignment?

**Comment by osherdp** [comment]
In an another effort, we can do one of the following:
* Rename workflows to be indicative about whether they run full conformance suite of minimal
* (better) have one workflow, and set ``TEST_SUITE`` to the relevant value

**Comment by YuviGold** [comment]
> In an another effort, we can do one of the following:
> 
> * Rename workflows to be indicative about whether they run full conformance suite of minimal
> * (better) have one workflow, and set `TEST_SUITE` to the relevant value

2nd one sounds good. With having minimal-suite by default and we will set full on our periodics.

/lgtm

**Comment by osherdp** [comment]
@YuviGold right, default should be minimal suite

**Comment by YuviGold** [comment]
`e2e-metal-assisted` job would keep failing until @ori-amizur will fix pytest with DHCP . We don't want to block PRs
/lgtm cancel

**Pull request merged**
