### PR TITLE
Switch krkn home dir to align with base image

### PR DESCRIPTION
**Pull request by chaitanyaenr**

### CODE REVIEW

**Review by shahsahil264 — APPROVED** [review]
LGTM

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.15-nightly-krkn-hub-tests-415

**Comment by shahsahil264** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.15-nightly-krkn-hub-tests-415

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.15-nightly-krkn-hub-tests-415

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.15-nightly-krkn-hub-tests-415

**Comment by shahsahil264** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.15-nightly-krkn-hub-tests-415

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.15-nightly-krkn-hub-tests-415

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-prow-scripts-main-4.15-nightly-krkn-hub-tests-415

**Review by shahsahil264 — APPROVED** [review]
LGTM

**Pull request merged**
