### PR TITLE
OCPBUGS-43572: fix: update baremetal lane

### PR DESCRIPTION
**Pull request by eggfoobar**
removed skip for monitor test failures
added conf step to pre step instead of test

### CODE REVIEW

**Comment by eggfoobar** [comment]
/hold

Until we verify monitor errors are resolved

**Comment by eggfoobar** [comment]
/pj-rehearse pull-ci-rh-ecosystem-edge-recert-release-4.14-baremetalds-sno-recert-cluster-rename

**Comment by mresvanis** [comment]
/pj-rehearse pull-ci-rh-ecosystem-edge-recert-v0-baremetalds-sno-recert-cluster-rename

**Comment by mresvanis** [comment]
This `ci/rehearse/rh-ecosystem-edge/recert/release-4.14/baremetalds-sno-recert-cluster-rename` job is failing due to an irrelevant to this change issue, which we need to resolve in the `release-4.14` branch of recert.

/pj-rehearse ack

**Pull request merged**
