### PR TITLE
CNF-15001: Fix cnf-features-deploy ztp CI input image

### PR DESCRIPTION
**Pull request by fontivan**
- This should match the current release like the cnf-tests image does

### CODE REVIEW

**Comment by fontivan** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-master-e2e-telco5g-sno-cnftests

**Comment by fontivan** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.17-e2e-aws-ci-tests

**Comment by fontivan** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.17-e2e-telco5g-cnftests

**Comment by fontivan** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-master-e2e-telco5g-cnftests

**Comment by fontivan** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.17-e2e-telco5g-sno-cnftests

**Comment by fontivan** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.17-e2e-telco5g-hcp-cnftests

**Comment by fontivan** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-master-e2e-telco5g-hcp-cnftests

**Comment by fontivan** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-master-e2e-aws-ci-tests

**Review by lack — APPROVED** [review]

**Comment by fontivan** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.17-e2e-telco5g-cnftests

**Comment by fontivan** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.17-e2e-aws-ci-tests

**Comment by fontivan** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.17-e2e-telco5g-sno-cnftests

**Comment by fontivan** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.17-e2e-telco5g-hcp-cnftests

**Comment by fontivan** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-master-e2e-telco5g-cnftests

**Comment by fontivan** [comment]
All the CI jobs that are failing seem to be failing with the same error 
```
  * could not run steps: step [release:latest] failed: failed to get CLI image: unable to wait for the 'cli' image in the stable stream to populate (waited for 5m5.01981621s): timed out waiting for the condition 
```

**Review by lack — APPROVED** [review]

**Comment by fontivan** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.17-e2e-telco5g-cnftests
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.17-e2e-telco5g-hcp-cnftests

**Comment by fontivan** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.17-e2e-telco5g-cnftests

**Comment by fontivan** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.17-e2e-telco5g-hcp-cnftests

**Comment by fontivan** [comment]
CI bot fixed this here before I got the pj rehease working in this branch
https://github.com/openshift/release/pull/58240

**Pull request closed without merging**
