### PR TITLE
Set OS_OUTPUT_BASEPATH for unit and int tests

### PR DESCRIPTION
**Pull request by paradigm**
Otherwise, with the preexisting ARTIFACT_DIR and LOG_DIR, test artifacts
clobber those of other tests.

This is set for command tests in another pull request.

This is currently inapplicable to verification tests.

/cc stevekuznetsov

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
We need to get bots to update these resources post-merge... perhaps the prow plugin can be expanded 
/cc @kargakis

**Comment by kargakis** [comment]
I thought these were already getting updated since they are being called out by Jenkins via using Github?

**Comment by csrwng** [comment]
The only part that doesn't take effect automatically is the changes to the configmaps.

**Pull request merged**
