### PR TITLE
Update prow jobs to use new cm-keys and cm

### PR DESCRIPTION
**Pull request by droslean**
This PR updates all the prow jobs to use a single configMap with the correct key.

### CODE REVIEW

**Comment by petr-muller** [comment]
There are few references to `*.yaml` keys left: 

```
$ grep 'key:.*yaml'
openshift/installer/openshift-installer-release-3.11-postsubmits.yaml:              key: release-3.11.yaml
openshift/installer/openshift-installer-release-3.11-presubmits.yaml:              key: release-3.11.yaml
openshift/installer/openshift-installer-release-3.11-presubmits.yaml:              key: release-3.11.yaml
openshift/openshift-azure/openshift-openshift-azure-periodics.yaml:              key: release-3.10.yaml
openshift/origin/openshift-origin-periodics.yaml:            key: master.yaml
openshift/origin/openshift-origin-release-3.10-presubmits.yaml:              key: release-3.10.yaml
openshift/release/openshift-release-periodics.yaml:            key: master.yaml
```

**Comment by droslean** [comment]
@petr-muller updated. Thanks

**Comment by droslean** [comment]
prow's config updater, won't work with this setup.

**Pull request closed without merging**
