### PR TITLE
feat: rhtap: enable firewatch for periodic job 

### PR DESCRIPTION
**Pull request by psturc**
https://issues.redhat.com/browse/RHTAP-1969

* [link to the successful run](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/46009/rehearse-46009-periodic-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests-periodic/1727719668694650880)

### CODE REVIEW

**Comment by psturc** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests-periodic

**Comment by psturc** [comment]
/pj-rehearse periodic-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests-periodic

**Comment by Dannyb48** [comment]
@psturc I though we were doing for system type failures?

**Comment by psturc** [comment]
@Dannyb48 I think it makes sense to try out [the new firewatch feature](https://github.com/CSPI-QE/firewatch/issues/103) that should detect test failures in junit.xml and create jira tickets from them


imo infra issues in our openshift-ci workflow don't concern us anymore since the time we switched to cluster pools (we're no longer hitting cluster-create/cluster-destroy issues)

if our job hits some infra-related issue, it's either:
* build cluster problem (outage)
* image build issue

both of these issues happen outside of our workflow, so firewatch can't detect them anyway

**Comment by Dannyb48** [comment]
@psturc right, thank you for the clarification!

**Pull request closed without merging**
