### PR TITLE
Enable service-ca-operator jobs

### PR DESCRIPTION
**Pull request by mrogers950**
This PR adds builds and CI for service-ca-operator. It will eventually replace the service-serving-cert-signer entries, but we can't remove them yet.

### CODE REVIEW

**Comment by mrogers950** [comment]
@droslean @stevekuznetsov PTAL

**Comment by stevekuznetsov** [comment]
@mrogers950 can you re-run the generator? Sorry, we changed some things while this PR was in flight

**Comment by mrogers950** [comment]
@stevekuznetsov I rebased and ran prowgen on it again, but there was no change. unexpected?

**Comment by mrogers950** [comment]
@stevekuznetsov done

**Pull request merged**
