### PR TITLE
MCO: bump golang to 1.15 in 4.7 and above release

### PR DESCRIPTION
**Pull request by darkmuggle**
Required for https://github.com/openshift/machine-config-operator/pull/2303

### CODE REVIEW

**Comment by sinnykumari** [comment]
we also need to update openshift-machine-config-operator-master.yaml and openshift-machine-config-operator-master__okd.yaml file. This is what MCO master branch ci uses for tests on OKD and OCP.

**Comment by sinnykumari** [comment]
For OKD related test
/cc @vrutkovs

**Comment by vrutkovs** [comment]
Looks good, thanks!

**Review by ashcrow — APPROVED** [review]

**Comment by darkmuggle** [comment]
Re-pushed with the master's updated.

**Pull request merged**
