### PR TITLE
Configure jobs and bots for new CSI repos

### PR DESCRIPTION
**Pull request by jsafrane**
Run only unit tests for now, images will be built later.

### CODE REVIEW

**Comment by jsafrane** [comment]
`ci/prow/generated-config` complains:

```
[ERROR] The following errors were found:

diff -Naupr hack/../ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-devel-40-presubmits.yaml /tmp/tmp.bjf14sDHQ7/ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-devel-40-presubmits.yaml
--- hack/../ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-devel-40-presubmits.yaml	2019-02-28 13:44:38.589202844 +0000
+++ /tmp/tmp.bjf14sDHQ7/ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-devel-40-presubmits.yaml	2019-02-28 13:48:42.551800184 +0000
@@ -106,7 +106,7 @@ presubmits:
           name: cluster-profile
         - mountPath: /usr/local/e2e-gcp
           name: job-definition
-          subPath: cluster-launch-e2e-40.yaml
+          subPath: cluster-scaleup-e2e-40.yaml
       serviceAccountName: ci-operator
       volumes:
       - name: cluster-profile
```

But I did not touch anything related to openshift-ansible-devel.
I'll fix OWNERS (waiting for their merge in other repos).

**Comment by droslean** [comment]
@jsafrane There was an issue with this job. Everything is fixed now.

**Comment by jsafrane** [comment]
Added OWNERS, ready for review.

**Pull request merged**
