### PR TITLE
Add step to enable catalogsource for Distributed Tracing stage testing

### PR DESCRIPTION
**Pull request by IshwarKanse**
Required by: https://issues.redhat.com/browse/TRACING-2538

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-distributed-tracing-qe-main-distributed-tracing-tests-dast

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-distributed-tracing-qe-main-distributed-tracing-tests-dast

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-distributed-tracing-qe-main-distributed-tracing-tests-dast

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-distributed-tracing-qe-main-distributed-tracing-tests-dast

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-distributed-tracing-qe-main-distributed-tracing-tests-dast

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-openshift-distributed-tracing-qe-main-distributed-tracing-tests-dast

**Review by iblancasa — APPROVED** [review]

**Pull request merged**
