### PR TITLE
Switch Dev Sandbox CI to OCP 4.16

### PR DESCRIPTION
**Pull request by alexeykazakov**

### CODE REVIEW

**Review by mfrancisc — APPROVED** [review]
/lgtm

**Comment by alexeykazakov** [comment]
Looks like flaky tests...

/retest

**Comment by alexeykazakov** [comment]
/pj-rehearse pull-ci-codeready-toolchain-member-operator-master-e2e

**Comment by alexeykazakov** [comment]
/pj-rehearse pull-ci-codeready-toolchain-host-operator-master-e2e

**Review by ranakan19 — APPROVED** [review]

**Pull request merged**
