### PR TITLE
edge-gpu-ci: Added presubmit ocp versioned jobs.

### PR DESCRIPTION
**Pull request by sagidayan**
/cc @mkowalski 
/cc @kpouget

### CODE REVIEW

**Comment by kpouget** [comment]
Looks good @sagidayan !

**Comment by kpouget** [comment]
4.10 [failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/25377/rehearse-25377-pull-ci-rh-ecosystem-edge-ci-artifacts-master-4.10-gpu-operator-e2e/1483433220220391424)
```
INFO[2022-01-18T13:41:23Z] Logs for container test in pod gpu-operator-e2e-ipi-conf: 
INFO[2022-01-18T13:41:23Z] /bin/bash: line 12: RELEASE_IMAGE_LATEST: unbound variable 
```

maybe it's because of you have one line missing in 4.10 config:

```
tests:
- as: gpu-operator-e2e
  steps:
    cluster_profile: aws # <--- missing
```

**Comment by sagidayan** [comment]
Both test-commits rehearse are expected to fail. FYI

**Review by mkowalski — APPROVED** [review]

**Pull request merged**
