### PR TITLE
cert-rotation: bump machine sizes

### PR DESCRIPTION
**Pull request by vrutkovs**
Increase machine size to make sure cluster VMs have sufficient resources

### CODE REVIEW

**Comment by vrutkovs** [comment]
/pj-rehearse e2e-metal-ovn-sno-cert-rotation-suspend-30d e2e-metal-ovn-sno-cert-rotation-shutdown-30d e2e-metal-ovn-ha-cert-rotation-suspend-30d e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-30d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-shutdown-30d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-30d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-30d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-sno-cert-rotation-shutdown-30d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-30d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

**Comment by vrutkovs** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-30d

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-apiserver-operator-release-4.14-e2e-metal-ovn-sno-cert-rotation-shutdown-30d pull-ci-openshift-cluster-kube-apiserver-operator-release-4.14-e2e-metal-ovn-sno-cert-rotation-suspend-30d pull-ci-openshift-cluster-kube-apiserver-operator-release-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d pull-ci-openshift-cluster-kube-apiserver-operator-release-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-30d

**Review by dinhxuanvu — COMMENTED** [review]
/lgtm

**Pull request merged**
