### PR TITLE
hac-e2e: download scripts from PR head

### PR DESCRIPTION
**Pull request by jrichter1**
instead of main every time, so any changes to the scripts propagate into the PR

### CODE REVIEW

**Comment by jrichter1** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-hac-e2e-tests

**Comment by jrichter1** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-hac-e2e-tests

**Comment by jrichter1** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-hac-e2e-tests

**Comment by jrichter1** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-hac-e2e-tests

**Comment by jrichter1** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-hac-e2e-tests

**Comment by jrichter1** [comment]
/pj-rehearse pull-ci-redhat-appstudio-infra-deployments-main-appstudio-hac-e2e-tests

**Review by rhopp — APPROVED** [review]

**Pull request merged**
