### PR TITLE
[DNM] Test kube-burner-ocp v1.6.0 with payload jobs

### PR DESCRIPTION
**Pull request by rsevilla87**
https://github.com/kube-burner/kube-burner-ocp/releases/tag/v1.6.0

Includes https://github.com/kube-burner/kube-burner-ocp/pull/163

### CODE REVIEW

**Comment by rsevilla87** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-payload-control-plane-6nodes

**Comment by afcollins** [comment]
Thanks!
Failure is because of historical regression changepoint and not caused by this test.

Latencies are down to expected values:
```
time="2024-12-12 17:33:57" level=info msg="cluster-density-v2: ContainersReady 99th: 11000 max: 12000 avg: 4182" file="pod_latency.go:250"
```

**Comment by rsevilla87** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.19-nightly-x86-payload-control-plane-6nodes periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.17-nightly-x86-payload-control-plane-6nodes

**Pull request closed without merging**
