### PR TITLE
kni: nrop: fix main references

### PR DESCRIPTION
**Pull request by ffromani**
main is 4.17 now, no longer 4.16

### CODE REVIEW

**Comment by ffromani** [comment]
requires: https://github.com/openshift-kni/numaresources-operator/pull/972

**Comment by shajmakh** [comment]
shouldn't we also create a lane for 4.16 here:
https://github.com/openshift/release/tree/e6078e00be5af10b513e7a8fdc6c18ce06e94f21/ci-operator/config/openshift-kni/numaresources-operator ?

**Comment by ffromani** [comment]
> shouldn't we also create a lane for 4.16 here: https://github.com/openshift/release/tree/e6078e00be5af10b513e7a8fdc6c18ce06e94f21/ci-operator/config/openshift-kni/numaresources-operator ?

yes, I crossed wires. Main is still against 4.16, we will branch off later.

**Comment by ffromani** [comment]
I *BADLY* crossed wires. I had an old tree. We already forked off on June 20.

**Pull request closed without merging**
