### PR TITLE
installer: build installer-artifacts in parallel with installer

### PR DESCRIPTION
**Pull request by r4f4**
This should improve running time of CI installer jobs.

### CODE REVIEW

**Comment by r4f4** [comment]
> Is there a way to determine how much faster this change made the tests?

I don't think it has. 
Looking at a run without this change: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/6928/pull-ci-openshift-installer-master-e2e-aws-ovn/1631475635010408448/build-log.txt
```bash
[36mINFO[0m[2023-03-03T02:05:47Z] Building src                                 
[36mINFO[0m[2023-03-03T02:09:56Z] Build src succeeded after 4m13s              
[36mINFO[0m[2023-03-03T02:09:56Z] Building src-oc                              
[36mINFO[0m[2023-03-03T02:09:56Z] Building baremetal-installer                 
[36mINFO[0m[2023-03-03T02:09:56Z] Building ovirt-installer                     
[36mINFO[0m[2023-03-03T02:09:56Z] Building installer                           
[36mINFO[0m[2023-03-03T02:09:56Z] Building openstack-installer                 
[36mINFO[0m[2023-03-03T02:09:57Z] Building libvirt-installer                   
[36mINFO[0m[2023-03-03T02:09:57Z] Building upi-installer                       
[36mINFO[0m[2023-03-03T02:12:26Z] Build src-oc succeeded after 2m30s           
[36mINFO[0m[2023-03-03T02:12:26Z] Tagging src-oc into stable                   
[36mINFO[0m[2023-03-03T02:24:11Z] Build installer succeeded after 12m59s       
[36mINFO[0m[2023-03-03T02:24:12Z] Tagging installer into stable                
[36mINFO[0m[2023-03-03T02:24:12Z] Building installer-artifacts          
[...]
[36mINFO[0m[2023-03-03T03:31:27Z] Build installer-artifacts succeeded after 1h7m15s        
```
So clearly the building of `installer-artifacts` is only triggered after `installer` is built.

Looking at https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/36899/rehearse-36899-pull-ci-openshift-installer-master-e2e-aws-ovn/1631414259005001728/build-log.txt
```bash
[36mINFO[0m[2023-03-02T22:02:01Z] Building src                                 
[36mINFO[0m[2023-03-02T22:06:34Z] Build src succeeded after 4m33s              
[36mINFO[0m[2023-03-02T22:06:34Z] Building upi-installer                       
[36mINFO[0m[2023-03-02T22:06:34Z] Building ovirt-installer                     
[36mINFO[0m[2023-03-02T22:06:35Z] Building baremetal-installer                 
[36mINFO[0m[2023-03-02T22:06:35Z] Building installer                           
[36mINFO[0m[2023-03-02T22:06:35Z] Building src-oc                              
[36mINFO[0m[2023-03-02T22:06:35Z] Building libvirt-installer                   
[36mINFO[0m[2023-03-02T22:06:35Z] Building openstack-installer                 
[36mINFO[0m[2023-03-02T22:06:36Z] Building installer-artifacts                 
[36mINFO[0m[2023-03-02T22:09:42Z] Build src-oc succeeded after 3m7s            
[36mINFO[0m[2023-03-02T22:09:43Z] Tagging src-oc into stable                   
[36mINFO[0m[2023-03-02T22:21:45Z] Build baremetal-installer succeeded after 14m52s 
[36mINFO[0m[2023-03-02T22:21:45Z] Tagging baremetal-installer into stable      
[36mINFO[0m[2023-03-02T22:22:08Z] Build ovirt-installer succeeded after 15m33s 
[36mINFO[0m[2023-03-02T22:22:09Z] Tagging ovirt-installer into stable          
[36mINFO[0m[2023-03-02T22:24:03Z] Build installer succeeded after 14m52s       
[...]
[36mINFO[0m[2023-03-02T23:51:12Z] Build installer-artifacts succeeded after 1h32m36s 
[36mINFO[0m[2023-03-02T23:51:12Z] Tagging installer-artifacts into stable      
```
So the builds were triggered in parallel but still it took 1h32m to build `installer-artifacts`.

That tells me the way forward is to not build installer-artifacts for Installer CI jobs.

**Comment by rna-afk** [comment]
> That tells me the way forward is to not build installer-artifacts for Installer CI jobs.

Yeah that is a significant time loss building it. We should maybe move this to a periodic test if we want to test the binaries on other platforms.

**Comment by r4f4** [comment]
> > That tells me the way forward is to not build installer-artifacts for Installer CI jobs.
> 
> Yeah that is a significant time loss building it. We should maybe move this to a periodic test if we want to test the binaries on other platforms(os).

I think these artifacts are only needed for release purposes. But the idea of a periodic to make sure we catch any breakage in other platforms is a good idea!

**Pull request closed without merging**
