### PR TITLE
[gcp] Fix installer-src template GCP region

### PR DESCRIPTION
**Pull request by csrwng**
Fixes the region used for gcp installs with the installer-src template

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
This file also doens't have the gcloud cli copy stuff.

**Comment by csrwng** [comment]
> This file also doens't have the gcloud cli copy stuff.

This is for our own tests, and I don't think we use the cli in our own stuff, but I can definitely add it

**Comment by csrwng** [comment]
Added the cli setup script for gcp

**Pull request merged**
