### PR TITLE
replace chains with workflow

### PR DESCRIPTION
**Pull request by jianzhangbjz**
I'm not sure why we don't use the `workflow` before. Maybe I missed something.
@kuiwang02 Could you help have a look when you get a chance? Thanks!

### CODE REVIEW

**Comment by kuiwang02** [comment]
/hold
we should change to that like https://github.com/openshift/release/pull/27845

**Comment by jianzhangbjz** [comment]
Don't merge it, I just use it to test the issue: https://issues.redhat.com/browse/DPTP-2813
/hold

**Comment by jianzhangbjz** [comment]
close it since has finished the testing

**Pull request closed without merging**
