### PR TITLE
add validatetion of no offensive lang to common-templates

### PR DESCRIPTION
**Pull request by dominikholler**
@ksimon1 can you please have a look?

### CODE REVIEW

**Comment by ksimon1** [comment]
But you already added it as a part of unit tests (https://github.com/kubevirt/common-templates/pull/365/files#diff-beda42571c095172ab63437d050612a571d0d9ddd3ad4f2aecbce907a9b7e3d0R32), so why we need it as a separate lane?

**Comment by dominikholler** [comment]
> But you already added it as a part of unit tests (https://github.com/kubevirt/common-templates/pull/365/files#diff-beda42571c095172ab63437d050612a571d0d9ddd3ad4f2aecbce907a9b7e3d0R32), so why we need it as a separate lane?
>

I understood yesterday in the stand up, that the test lane is required,
because the unit tests are not triggered on PRs. But I might be wrong.

**Comment by ksimon1** [comment]
in common templates unit test lane is triggered for each PR against master / release-v0.13 branch

**Comment by dominikholler** [comment]
We decided to use a github action instead.

**Pull request closed without merging**
