### PR TITLE
kccm: Move hypershift jobs to baremetalds

### PR DESCRIPTION
**Pull request by qinqon**

### CODE REVIEW

**Comment by qinqon** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-kubevirt-main-hypershift-kubevirt-conformance-baremetalds

**Comment by qinqon** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-kubevirt-release-4.15-hypershift-kubevirt-conformance-baremetalds

**Review by davidvossel — COMMENTED** [review]
/lgtm
/approve

**Comment by qinqon** [comment]
/hold
let's wait on rehearsals.

**Comment by qinqon** [comment]
/hold cancel
conformance has pass at three jobs, a pair failed uploading must gather

**Pull request merged**
