### PR TITLE
chore(RHIDP-4303): Enable CI for v1.2.x release branch of redhat-performance/backstage-performance repo

### PR DESCRIPTION
**Pull request by pmacik**

### CODE REVIEW

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-v1.2.x-mvp-helm pull-ci-redhat-performance-backstage-performance-v1.2.x-mvp-olm

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-rhdh-v1.2.x-mvp-helm pull-ci-redhat-performance-backstage-performance-rhdh-v1.2.x-mvp-olm

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-rhdh-v1.2.x-mvp-helm pull-ci-redhat-performance-backstage-performance-rhdh-v1.2.x-mvp-olm

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-rhdh-v1.2.x-mvp-helm pull-ci-redhat-performance-backstage-performance-rhdh-v1.2.x-mvp-olm pull-ci-redhat-performance-backstage-performance-rhdh-v1.2.x-images

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-rhdh-v1.2.x-mvp-helm pull-ci-redhat-performance-backstage-performance-rhdh-v1.2.x-mvp-olm

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-rhdh-v1.2.x-mvp-helm pull-ci-redhat-performance-backstage-performance-rhdh-v1.2.x-mvp-olm

**Review by jhutar — APPROVED** [review]
/lgtm

**Review by jhutar — APPROVED** [review]
/lgtm

**Pull request merged**
