### PR TITLE
 Auto-generate jobs for openshift/jenkins 

### PR DESCRIPTION
**Pull request by stevekuznetsov**
/assign @smarterclayton

### CODE REVIEW

**Comment by gabemontero** [comment]
@stevekuznetsov - does this override/replace the existing aos-cd-jobs wrt basic images generation and unit test?

Or does it only add the `/test images` and `/test all` capabilities?

@bparees ^^ (in case you do not auto watch this repo)

**Comment by gabemontero** [comment]
I do see that https://jira.coreos.com/browse/DPTP-78 is in progress, so in theory we'll have to capability to fully replace all we do in the jenkins aos-cd-jobs "soon"

**Comment by stevekuznetsov** [comment]
@smarterclayton @gabemontero why don't we figure out _where_ we want these images to be published, so we can just keep the generator simple and publish always? Do we have a namespace we can serve alpha Jenkins images from?

/cc @bparees

**Comment by bparees** [comment]
centos images can publish to docker.io/openshift/jenkins-*:latest and :release-tag, that's where they go today.

**Comment by stevekuznetsov** [comment]
CI Operator only supports publication into an OpenShift ImageStream. We can place these images into tags on the `openshift/jenkins-vXX` ImageStreams and separately set up mirroring elsewhere. @smarterclayton WDYT

**Comment by bparees** [comment]
> CI Operator only supports publication into an OpenShift ImageStream. We can place these images into tags on the openshift/jenkins-vXX ImageStreams and separately set up mirroring elsewhere. 

so how are things like docker.io/openshift/origin-docker-builder and docker.io/openshift/origin-pod getting pushed to dockerhub today?

**Comment by stevekuznetsov** [comment]
@bparees please see the shared document on this topic (and linked from onboarding)

**Pull request merged**
