### PR TITLE
OCPBUGS-29484: enable Go units tests in openshift/images

### PR DESCRIPTION
**Pull request by frobware**
Ran `make update`

Requires: https://github.com/openshift/images/pull/165.

### CODE REVIEW

**Comment by frobware** [comment]
/hold

Requires https://github.com/openshift/images/pull/165.

I also also surprised to see a change to `ci-operator/jobs/openshift-qe/baremetal-qe-infra/openshift-qe-baremetal-qe-infra-master-postsubmits.yaml` having run `make update`.

**Comment by Miciah** [comment]
Any reason not to add unit tests for other branches?  (Though the release-4.14..release-4.15 branches won't pass the test until we backport https://github.com/openshift/images/pull/165.)

**Comment by Miciah** [comment]
The rehearsal failed, which is expected, but the failure shows that additional changes may be required to fix the failing unit test:
```text
 INFO[2024-02-15T17:30:44Z] --- FAIL: TestHAProxyDefaults (0.00s)
    egress_dns_proxy_test.go:312: expected defaults in output "\nglobal\n    log         127.0.0.1 local2\n\n    chroot      /var/lib/haproxy\n    pidfile     /var/lib/haproxy/run/haproxy.pid\n    maxconn     4000\n    user        haproxy\n    group       haproxy\n\ndefaults\n    log                     global\n    mode                    tcp\n    option                  dontlognull\n    option                  tcplog\n    option                  redispatch\n    retries                 3\n    timeout http-request    100s\n    timeout queue           1m\n    timeout connect         10s\n    timeout client          1m\n    timeout server          1m\n    timeout http-keep-alive 100s\n    timeout check           10s\n" but got "\nglobal\n    log         127.0.0.1 local2\n\n    pidfile     /var/lib/haproxy/run/haproxy.pid\n    maxconn     4000\n    user        haproxy\n    group       haproxy\n\ndefaults\n    log                     global\n    mode                    tcp\n    option                  dontlognull\n    option                  tcplog\n    option                  redispatch\n    retries                 3\n    timeout http-request    100s\n    timeout queue           1m\n    timeout connect         10s\n    timeout client          1m\n    timeout server          1m\n    timeout http-keep-alive 100s\n    timeout check           10s\n\nresolvers dns-resolver\n    nameserver ns1 172.30.0.10:53\n    resolve_retries      3\n    timeout retry        1s\n    hold valid           10s\n\n\nfrontend fe1\n    bind :80\n    default_backend be1\n\nbackend be1\n    server dest1 11.12.13.14:80 check \n\n" 
```
If I diff the expected and actual output, I see more than just the `chroot` line:
```diff
@@ -2,7 +2,6 @@
 global
     log         127.0.0.1 local2
 
-    chroot      /var/lib/haproxy
     pidfile     /var/lib/haproxy/run/haproxy.pid
     maxconn     4000
     user        haproxy
@@ -22,3 +21,18 @@
     timeout server          1m
     timeout http-keep-alive 100s
     timeout check           10s
+
+resolvers dns-resolver
+    nameserver ns1 172.30.0.10:53
+    resolve_retries      3
+    timeout retry        1s
+    hold valid           10s
+
+
+frontend fe1
+    bind :80
+    default_backend be1
+
+backend be1
+    server dest1 11.12.13.14:80 check 
+
```
Or maybe the unit test is truncating the expected output?

**Comment by frobware** [comment]
```
commit 5575b9daefc26dbe423e71cef358367ffc710bf3 (HEAD -> OCPBUGS-29484-update-unit-tests, origin/OCPBUGS-29484-update-unit-tests)
Author: Andrew McDermott <amcdermo@redhat.com>
Date:   Thu Feb 15 16:23:10 2024 +0000

    egress/dns-proxy: update unit test expectations

    The chroot setting was removed by https://github.com/openshift/images/pull/137.

commit b627da1bac47355a41f46670af81d612cb09be6d
Author: Andrew McDermott <amcdermo@redhat.com>
Date:   Thu Feb 15 16:23:59 2024 +0000

    Add go.mod to enable unit tests in egress/...

commit 247d4a01eff67ef63e31968d268bbcd987adc53b (upstream/release-4.17, upstream/release-4.16, upstream/master, master)
Merge: 676f4f6 74bab8d
Author: openshift-merge-bot[bot] <148852131+openshift-merge-bot[bot]@users.noreply.github.com>
Date:   Fri Feb 9 14:42:33 2024 +0000

    Merge pull request #158 from openshift-bot/art-consistency-openshift-4.16-openshift-enterprise-egress-dns-proxy

    OCPBUGS-24861: Updating openshift-enterprise-egress-dns-proxy-container image to be consistent with ART
```
And then running: 

```
[fedora] ~o/images
% pwd
/home/aim/src/github.com/openshift/images

% go test -v ./...
=== RUN   TestHAProxyFrontendBackendConf
--- PASS: TestHAProxyFrontendBackendConf (0.02s)
=== RUN   TestHAProxyFrontendBackendConfBad
--- PASS: TestHAProxyFrontendBackendConfBad (0.01s)
=== RUN   TestHAProxyDefaults
--- PASS: TestHAProxyDefaults (0.00s)
=== RUN   TestHAProxyResolver
--- PASS: TestHAProxyResolver (0.00s)
PASS
ok  	github.com/openshift/images/egress/dns-proxy	(cached)
=== RUN   TestGenerateSquidConf
--- PASS: TestGenerateSquidConf (0.01s)
=== RUN   TestGenerateSquidConfBad
--- PASS: TestGenerateSquidConfBad (0.00s)
PASS
ok  	github.com/openshift/images/egress/http-proxy	(cached)
=== RUN   TestEgressRouter
--- PASS: TestEgressRouter (0.01s)
=== RUN   TestEgressRouterBad
--- PASS: TestEgressRouterBad (0.01s)
PASS
ok  	github.com/openshift/images/egress/router	(cached)
?   	github.com/openshift/images/pod	[no test files]
```

And with `-race`

```
% go test -race -count=10 -v ./...
?   	github.com/openshift/images/pod	[no test files]
=== RUN   TestHAProxyFrontendBackendConf
--- PASS: TestHAProxyFrontendBackendConf (0.02s)
=== RUN   TestHAProxyFrontendBackendConfBad
--- PASS: TestHAProxyFrontendBackendConfBad (0.01s)
=== RUN   TestHAProxyDefaults
--- PASS: TestHAProxyDefaults (0.00s)
=== RUN   TestHAProxyResolver
--- PASS: TestHAProxyResolver (0.00s)
=== RUN   TestHAProxyFrontendBackendConf
--- PASS: TestHAProxyFrontendBackendConf (0.02s)
=== RUN   TestHAProxyFrontendBackendConfBad
--- PASS: TestHAProxyFrontendBackendConfBad (0.01s)
=== RUN   TestHAProxyDefaults
--- PASS: TestHAProxyDefaults (0.00s)
=== RUN   TestHAProxyResolver
--- PASS: TestHAProxyResolver (0.00s)
=== RUN   TestHAProxyFrontendBackendConf
--- PASS: TestHAProxyFrontendBackendConf (0.02s)
=== RUN   TestHAProxyFrontendBackendConfBad
--- PASS: TestHAProxyFrontendBackendConfBad (0.01s)
=== RUN   TestHAProxyDefaults
--- PASS: TestHAProxyDefaults (0.00s)
=== RUN   TestHAProxyResolver
--- PASS: TestHAProxyResolver (0.00s)
=== RUN   TestHAProxyFrontendBackendConf
--- PASS: TestHAProxyFrontendBackendConf (0.02s)
=== RUN   TestHAProxyFrontendBackendConfBad
--- PASS: TestHAProxyFrontendBackendConfBad (0.01s)
=== RUN   TestHAProxyDefaults
--- PASS: TestHAProxyDefaults (0.00s)
=== RUN   TestHAProxyResolver
--- PASS: TestHAProxyResolver (0.00s)
=== RUN   TestHAProxyFrontendBackendConf
--- PASS: TestHAProxyFrontendBackendConf (0.02s)
=== RUN   TestHAProxyFrontendBackendConfBad
--- PASS: TestHAProxyFrontendBackendConfBad (0.01s)
=== RUN   TestHAProxyDefaults
--- PASS: TestHAProxyDefaults (0.00s)
=== RUN   TestHAProxyResolver
--- PASS: TestHAProxyResolver (0.00s)
=== RUN   TestHAProxyFrontendBackendConf
--- PASS: TestHAProxyFrontendBackendConf (0.02s)
=== RUN   TestHAProxyFrontendBackendConfBad
--- PASS: TestHAProxyFrontendBackendConfBad (0.01s)
=== RUN   TestHAProxyDefaults
--- PASS: TestHAProxyDefaults (0.00s)
=== RUN   TestHAProxyResolver
--- PASS: TestHAProxyResolver (0.00s)
=== RUN   TestHAProxyFrontendBackendConf
--- PASS: TestHAProxyFrontendBackendConf (0.02s)
=== RUN   TestHAProxyFrontendBackendConfBad
--- PASS: TestHAProxyFrontendBackendConfBad (0.01s)
=== RUN   TestHAProxyDefaults
--- PASS: TestHAProxyDefaults (0.00s)
=== RUN   TestHAProxyResolver
--- PASS: TestHAProxyResolver (0.00s)
=== RUN   TestHAProxyFrontendBackendConf
--- PASS: TestHAProxyFrontendBackendConf (0.02s)
=== RUN   TestHAProxyFrontendBackendConfBad
--- PASS: TestHAProxyFrontendBackendConfBad (0.01s)
=== RUN   TestHAProxyDefaults
--- PASS: TestHAProxyDefaults (0.00s)
=== RUN   TestHAProxyResolver
--- PASS: TestHAProxyResolver (0.00s)
=== RUN   TestHAProxyFrontendBackendConf
--- PASS: TestHAProxyFrontendBackendConf (0.02s)
=== RUN   TestHAProxyFrontendBackendConfBad
--- PASS: TestHAProxyFrontendBackendConfBad (0.01s)
=== RUN   TestHAProxyDefaults
--- PASS: TestHAProxyDefaults (0.00s)
=== RUN   TestHAProxyResolver
--- PASS: TestHAProxyResolver (0.00s)
=== RUN   TestHAProxyFrontendBackendConf
--- PASS: TestHAProxyFrontendBackendConf (0.02s)
=== RUN   TestHAProxyFrontendBackendConfBad
--- PASS: TestHAProxyFrontendBackendConfBad (0.01s)
=== RUN   TestHAProxyDefaults
--- PASS: TestHAProxyDefaults (0.00s)
=== RUN   TestHAProxyResolver
--- PASS: TestHAProxyResolver (0.00s)
PASS
ok  	github.com/openshift/images/egress/dns-proxy	1.375s
=== RUN   TestGenerateSquidConf
--- PASS: TestGenerateSquidConf (0.01s)
=== RUN   TestGenerateSquidConfBad
--- PASS: TestGenerateSquidConfBad (0.00s)
=== RUN   TestGenerateSquidConf
--- PASS: TestGenerateSquidConf (0.01s)
=== RUN   TestGenerateSquidConfBad
--- PASS: TestGenerateSquidConfBad (0.00s)
=== RUN   TestGenerateSquidConf
--- PASS: TestGenerateSquidConf (0.01s)
=== RUN   TestGenerateSquidConfBad
--- PASS: TestGenerateSquidConfBad (0.00s)
=== RUN   TestGenerateSquidConf
--- PASS: TestGenerateSquidConf (0.01s)
=== RUN   TestGenerateSquidConfBad
--- PASS: TestGenerateSquidConfBad (0.00s)
=== RUN   TestGenerateSquidConf
--- PASS: TestGenerateSquidConf (0.01s)
=== RUN   TestGenerateSquidConfBad
--- PASS: TestGenerateSquidConfBad (0.00s)
=== RUN   TestGenerateSquidConf
--- PASS: TestGenerateSquidConf (0.01s)
=== RUN   TestGenerateSquidConfBad
--- PASS: TestGenerateSquidConfBad (0.00s)
=== RUN   TestGenerateSquidConf
--- PASS: TestGenerateSquidConf (0.01s)
=== RUN   TestGenerateSquidConfBad
--- PASS: TestGenerateSquidConfBad (0.00s)
=== RUN   TestGenerateSquidConf
--- PASS: TestGenerateSquidConf (0.01s)
=== RUN   TestGenerateSquidConfBad
--- PASS: TestGenerateSquidConfBad (0.00s)
=== RUN   TestGenerateSquidConf
--- PASS: TestGenerateSquidConf (0.01s)
=== RUN   TestGenerateSquidConfBad
--- PASS: TestGenerateSquidConfBad (0.00s)
=== RUN   TestGenerateSquidConf
--- PASS: TestGenerateSquidConf (0.01s)
=== RUN   TestGenerateSquidConfBad
--- PASS: TestGenerateSquidConfBad (0.00s)
PASS
ok  	github.com/openshift/images/egress/http-proxy	1.093s
=== RUN   TestEgressRouter
--- PASS: TestEgressRouter (0.01s)
=== RUN   TestEgressRouterBad
--- PASS: TestEgressRouterBad (0.01s)
=== RUN   TestEgressRouter
--- PASS: TestEgressRouter (0.01s)
=== RUN   TestEgressRouterBad
--- PASS: TestEgressRouterBad (0.01s)
=== RUN   TestEgressRouter
--- PASS: TestEgressRouter (0.01s)
=== RUN   TestEgressRouterBad
--- PASS: TestEgressRouterBad (0.01s)
=== RUN   TestEgressRouter
--- PASS: TestEgressRouter (0.01s)
=== RUN   TestEgressRouterBad
--- PASS: TestEgressRouterBad (0.01s)
=== RUN   TestEgressRouter
--- PASS: TestEgressRouter (0.01s)
=== RUN   TestEgressRouterBad
--- PASS: TestEgressRouterBad (0.01s)
=== RUN   TestEgressRouter
--- PASS: TestEgressRouter (0.01s)
=== RUN   TestEgressRouterBad
--- PASS: TestEgressRouterBad (0.01s)
=== RUN   TestEgressRouter
--- PASS: TestEgressRouter (0.01s)
=== RUN   TestEgressRouterBad
--- PASS: TestEgressRouterBad (0.01s)
=== RUN   TestEgressRouter
--- PASS: TestEgressRouter (0.01s)
=== RUN   TestEgressRouterBad
--- PASS: TestEgressRouterBad (0.01s)
=== RUN   TestEgressRouter
--- PASS: TestEgressRouter (0.01s)
=== RUN   TestEgressRouterBad
--- PASS: TestEgressRouterBad (0.01s)
=== RUN   TestEgressRouter
--- PASS: TestEgressRouter (0.01s)
=== RUN   TestEgressRouterBad
--- PASS: TestEgressRouterBad (0.01s)
PASS
ok  	github.com/openshift/images/egress/router	1.208s
```

**Comment by frobware** [comment]
> Any reason not to add unit tests for other branches? (Though the release-4.14..release-4.15 branches won't pass the test until we backport [openshift/images#165](https://github.com/openshift/images/pull/165).)

I added unit tests for 4.14 and 4.15. Is that sufficient? Do we need to add older releases?

**Comment by Miciah** [comment]
> I added unit tests for 4.14 and 4.15. Is that sufficient? Do we need to add older releases?

If we had to backport a change to the release-4.13 or release-4.12 branch, would you rather have CI for those branches or not?  My opinion is that I'd rather have test coverage, and it's easy to `/override` a failing test but tedious to test manually.

**Comment by Miciah** [comment]
Andy and I discussed this on a call today.  If we ever need to backport a change to keepalived to the release-4.13 or release-4.12 branches, then we will update the CI job definition at that time.  For now, we will only add CI for the master, release-4.15, and release-4.14 branches.  

/approve

**Comment by frobware** [comment]
> Andy and I discussed this on a call today. If we ever need to backport a change to ~keepalived~ egress-router to the release-4.13 or release-4.12 branches, then we will update the CI job definition at that time. For now, we will only add CI for the master, release-4.15, and release-4.14 branches.
> 
> /approve

From a slack discussion: https://redhat-internal.slack.com/archives/CBWMXQJKD/p1711550485802899

> We have a problem with https://issues.redhat.com//browse/OCPBUGS-29484. This has two backports:
https://issues.redhat.com/browse/OCPBUGS-30414
https://issues.redhat.com/browse/OCPBUGS-30413
We can't get the backports merged until 29484 moves to verified. We can't get 29484 to verified because we need to merge the accompanying PR https://github.com/openshift/release/pull/48854. But 48854 can't merge because it depends on the backports. Suggestion: why don't I drop 4.15 and 4.14 from 48854 and we can then do these backports independently once we have the bases merged... 

Dropping CI jobs from 4.15 and 4.14 to move this along.

**Comment by frobware** [comment]
/hold cancel

Requires https://github.com/openshift/images/pull/165 which has merged.

**Comment by frobware** [comment]
`ci/rehearse/openshift/images/master/unit` jobs shows: 

```
ok  	github.com/openshift/images/egress/dns-proxy	1.071s
ok  	github.com/openshift/images/egress/http-proxy	1.025s
ok  	github.com/openshift/images/egress/router	1.049s
?   	github.com/openshift/images/pod	[no test files]
```

output pulled from: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/48854/rehearse-48854-pull-ci-openshift-images-master-unit/1773312477744861184/artifacts/test/build-log.txt.

/pj-rehearse ack

**Comment by Miciah** [comment]
Thanks!
/lgtm
/hold
in case Ryan has comments.

**Comment by rfredette** [comment]
Looks good to me as well.
/lgtm
/unhold

**Comment by frobware** [comment]
@bparees please could you review/approve.

**Pull request merged**
