### PR TITLE
Enable qe catelogsource for azure-aro

### PR DESCRIPTION
**Pull request by liangxia**
A working version for issue as described in https://github.com/openshift/release/pull/40913

### CODE REVIEW

**Comment by jianzhangbjz** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.10-amd64-nightly-4.10-upgrade-from-stable-4.10-azure-aro-cert-rotation-p1-f1

**Comment by MayXuQQ** [comment]
@mgahagan73

**Comment by jianzhangbjz** [comment]
Pass: https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/40915/rehearse-40915-periodic-ci-openshift-openshift-tests-private-release-4.10-amd64-nightly-4.10-upgrade-from-stable-4.10-azure-aro-cert-rotation-p1-f1/1676122662671224832/artifacts/azure-aro-cert-rotation-p1-f1/enable-qe-catalogsource/build-log.txt
/lgtm

**Pull request merged**
