### PR TITLE
Taking out write after each workload

### PR DESCRIPTION
**Pull request by paigerube14**
Step is the same data that the dashboard is tracking

### CODE REVIEW

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-control-plane-3nodes pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.15-nightly-x86-node-density-heavy-3nodes periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-ec-x86-data-path-2nodes

**Comment by paigerube14** [comment]
@svetsa-rh @jtaleric PTAL, failure isn't related to updates

**Review by jtaleric — APPROVED** [review]
lgtm

**Pull request merged**
