### PR TITLE
openstack: switch BYON jobs to run on managed VEXXHOST

### PR DESCRIPTION
**Pull request by EmilienM**
Use the managed cloud instead of `mecha`, so we can keep `mecha` for
advanced scenarios requiring features not available in the managed
cloud.

### CODE REVIEW

**Comment by EmilienM** [comment]
cc mandre pierreprinetti

**Comment by EmilienM** [comment]
It's failing during the [install](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/20661/rehearse-20661-pull-ci-openshift-cluster-api-provider-openstack-master-e2e-openstack-byon/1420424011271114752/artifacts/e2e-openstack-byon/ipi-install-install/artifacts/.openshift_install.log):

```
time="2021-07-28T18:01:16Z" level=error msg="Cluster operator authentication Degraded is True with IngressStateEndpoints_MissingSubsets::OAuthServerConfigObservation_Error::OAuthServerServiceEndpointAccessibleController_SyncError::OAuthServerServiceEndpointsEndpointAccessibleController_SyncError::RouterCerts_NoRouterCertSecret: IngressStateEndpointsDegraded: No subsets found for the endpoints of oauth-server\nOAuthServerConfigObservationDegraded: secret \"v4-0-config-system-router-certs\" not found\nOAuthServerServiceEndpointAccessibleControllerDegraded: Get \"https://172.30.72.157:443/healthz\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)\nOAuthServerServiceEndpointsEndpointAccessibleControllerDegraded: oauth service endpoints are not ready\nRouterCertsDegraded: neither the custom secret/v4-0-config-system-router-certs -n openshift-authentication or default secret/oauth-openshift -n openshift-authentication could be retrieved: secret \"v4-0-config-system-router-certs\" not found"
```

**Review by mandre — COMMENTED** [review]
/lgtm

Please remove the hold if you want to pursue with this PR.

**Comment by mandre** [comment]
As the bot suggests, @patrickdillon could you PTAL?
/assign @patrickdillon

**Pull request merged**
