### PR TITLE
Creating tests jobs for DVO in hypershift

### PR DESCRIPTION
**Pull request by JoaoFula**

### CODE REVIEW

**Comment by JoaoFula** [comment]
/pj-rehearse periodic-ci-app-sre-deployment-validation-operator-master-dvo-e2e-tests-hypershift

**Comment by JoaoFula** [comment]
/pj-rehearse periodic-ci-app-sre-deployment-validation-operator-master-dvo-e2e-tests-periodic

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-deployment-validation-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse periodic-ci-app-sre-deployment-validation-operator-master-dvo-e2e-tests-periodic

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-deployment-validation-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-deployment-validation-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-deployment-validation-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-deployment-validation-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-deployment-validation-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-deployment-validation-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-deployment-validation-operator-e2e-tests

**Comment by droslean** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-deployment-validation-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-deployment-validation-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-deployment-validation-operator-e2e-tests

**Comment by tremes** [comment]
/pj-rehearse pull-ci-app-sre-deployment-validation-operator-master-deployment-validation-operator-e2e-tests

**Pull request closed without merging**
