### PR TITLE
USHIFT-958: Add 4.14  to testgrid

### PR DESCRIPTION
**Pull request by pacevedom**

### CODE REVIEW

**Review by bradmwilliams — COMMENTED** [review]
/approve

**Comment by smg247** [comment]
@pacevedom Test Platform's automated tooling is attempting to remove this configuration due to `4.14` being the current release. You need to be sure to put these new tests in the `openshift-microshift-main.yaml` file as well so they do not get removed. The only reason these haven't been auto-removed already is that the `release-controller` configuration you have added here would need to be removed as well to allow the tests to pass, and that isn't something that we automate. https://github.com/openshift/release/pull/37521 is the PR, for reference.

**Pull request merged**
