### PR TITLE
Secret mirroring configuration for ocs operator addon for osde2d

### PR DESCRIPTION
**Pull request by brainfunked**
With reference to https://github.com/openshift/release/pull/13303#issuecomment-723861899, this is the secret mirroring configuration to be applied before adding the osde2e job for the ocs-converged addon.

### CODE REVIEW

**Comment by sabose** [comment]
@brainfunked @jeefy Hi Jeffrey, I think this PR needs to merged along with 13565?

**Comment by jeefy** [comment]
@brainfunked Can you fix the YAML formatting? lgtm otherwise. :)

**Comment by brainfunked** [comment]
@jeefy Just did. Tests should pass this time.

**Comment by brainfunked** [comment]
@jeefy Could you please trigger yamllint?

**Comment by jeefy** [comment]
Finally green! :taco: 

/lgtm

**Comment by brainfunked** [comment]
@jeefy This is going into a loop of changes requiring tests and approval through rebasing. Please merge this ASAP.

**Pull request closed without merging**
