### PR TITLE
Fix network type issue on SNO jobs

### PR DESCRIPTION
**Pull request by yunjiang29**

### CODE REVIEW

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.11-amd64-nightly-aws-ipi-disconnected-private-sno-f28

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-aws-ipi-disconnected-private-sno-f28-destructive

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-stable-aws-ipi-disconnected-private-sno-f14

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.11-amd64-nightly-aws-ipi-disconnected-private-sno-f28

**Pull request merged**
