### PR TITLE
update vsphere profile to vsphere-connected-2 & ingress-perf to 9 nodes

### PR DESCRIPTION
**Pull request by qiliRedHat**
https://issues.redhat.com/browse/OCPQE-20508

- Update vsphere and ibmcloud cluster-density, node-density-heavy to 24 nodes, ingress-perf to 9 nodes.
- Update vsphere profile to vsphere-connected-2

### CODE REVIEW

**Comment by qiliRedHat** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-vsphere-4.16-nightly-x86-ingress-perf-9nodes

**Comment by qiliRedHat** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-vsphere-4.15-nightly-x86-ingress-perf-9nodes

**Comment by qiliRedHat** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-vsphere-4.16-nightly-x86-ingress-perf-9nodes

**Comment by qiliRedHat** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-vsphere-4.16-nightly-x86-ingress-perf-9nodes

**Comment by qiliRedHat** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-vsphere-4.15-nightly-x86-ingress-perf-9nodes

**Comment by qiliRedHat** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-vsphere-4.15-nightly-x86-ingress-perf-9nodes

**Comment by qiliRedHat** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-vsphere-4.15-nightly-x86-ingress-perf-9nodes

**Comment by qiliRedHat** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-vsphere-4.15-nightly-x86-ingress-perf-9nodes

**Comment by qiliRedHat** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-vsphere-4.15-nightly-x86-ingress-perf-9nodes

**Comment by qiliRedHat** [comment]
@paigerube14 PTAL

**Comment by qiliRedHat** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-vsphere-4.16-nightly-x86-ingress-perf-9nodes

**Comment by qiliRedHat** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-vsphere-4.15-nightly-x86-ingress-perf-9nodes

**Comment by qiliRedHat** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-vsphere-4.15-nightly-x86-ingress-perf-9nodes

**Comment by paigerube14** [comment]
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-vsphere-4.15-nightly-x86-node-density-heavy-24nodes

**Comment by qiliRedHat** [comment]
@paigerube14 I saw all 4.16 vsphere tests had been finished in https://issues.redhat.com/browse/OCPQE-20491. This PR can be merged.

**Comment by qiliRedHat** [comment]
@liqcui PTAL.  All 4.16 vsphere tests had been finished in https://issues.redhat.com/browse/OCPQE-20491. This PR can be merged.

**Comment by qiliRedHat** [comment]
@liqcui PTAL

**Pull request merged**
