### PR TITLE
Add security scanner to openstack repos

### PR DESCRIPTION
**Pull request by mandre**

### CODE REVIEW

**Comment by pierreprinetti** [comment]
/lgtm
These jobs will require a lot more work to be actionable though.
* Maybe filter out anything lower than High, for the purpose of the test result
* Include a way to ignore report items that have been checked manually

**Comment by mandre** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-openstack-master-security

**Comment by mandre** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-openstack-main-security

**Comment by pierreprinetti** [comment]
/lgtm cancel

>    Info: the referenced anchor is not defined: */vendor/**

**Comment by pierreprinetti** [comment]
/lgtm
The issues I raised earlier are solved with a snyk config file locally to the repo. Which is in place, and apparently not OK (see the failed exclusion of /vendor). But that will have to be fixed in the repo itself.

**Pull request merged**
