### PR TITLE
oadp-operator:1.2 bump move to go1.20

### PR DESCRIPTION
**Pull request by kaovilai**

### CODE REVIEW

**Review by shubham-pampattiwar — APPROVED** [review]

**Review by sseago — APPROVED** [review]

**Comment by kaovilai** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-oadp-1.2-4.10-operator-unit-test
/pj-rehearse pull-ci-openshift-oadp-operator-oadp-1.2-4.11-operator-unit-test

**Comment by kaovilai** [comment]
ahem.. looks like my replace omits the 4.13.. which doesn't match exactly

**Review by shubham-pampattiwar — APPROVED** [review]

**Comment by kaovilai** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-oadp-1.2-4.11-operator-unit-test

**Comment by kaovilai** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-oadp-1.2-4.12-operator-unit-test

**Comment by kaovilai** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-oadp-1.2-4.13-operator-unit-test

**Review by sseago — APPROVED** [review]

**Comment by kaovilai** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-oadp-1.2-4.12-operator-unit-test

**Comment by kaovilai** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-oadp-1.2-4.13-operator-unit-test

**Pull request merged**
