### PR TITLE
[4.12 - 4.18] remove unnecessary gcp ipi oidc tests

### PR DESCRIPTION
**Pull request by jianli-wei**
There are obviously duplicated tests on gcp ipi oidc, for example, `gcp-ipi-disc-priv-oidc-fips-f28` in "4.18__amd64-stable" vs. `gcp-ipi-disc-priv-oidc-fips-f60`  in "4.18__amd64-nightly-4.18-upgrade-from-stable-4.18", `gcp-ipi-disc-priv-oidc-f28` in "4.18__arm64-stable" vs. `gcp-ipi-disc-priv-oidc-f60` in "4.18__arm64-nightly-4.18-upgrade-from-stable-4.18", etc.. Besides, too frequent OIDC tests will lead to updating project iam policy conflicts (see https://github.com/openshift/release/pull/59157). So, drop the duplicated gcp ipi oidc tests. 

What's removed | One of the duplicates
-- | --
4.12__amd64-stable: **gcp-ipi-disc-priv-oidc-fips-f60** | 4.12__amd64-nightly-4.12-upgrade-from-stable-4.12: **gcp-ipi-disc-priv-oidc-fips-f60**
4.13__amd64-stable-4.13-upgrade-from-stable-4.12: **gcp-ipi-disc-priv-oidc-fips-f60** | 4.13__amd64-nightly-4.13-upgrade-from-stable-4.12: **gcp-ipi-disc-priv-oidc-fips-f60**
4.13__amd64-stable: **gcp-ipi-disc-priv-oidc-fips-f60** | 4.13__amd64-nightly-4.13-upgrade-from-stable-4.13: **gcp-ipi-disc-priv-oidc-fips-f60**
4.14__amd64-stable-4.14-upgrade-from-stable-4.13: **gcp-ipi-disc-priv-oidc-fips-f28** | 4.14__amd64-nightly-4.14-upgrade-from-stable-4.13: **gcp-ipi-disc-priv-oidc-fips-f28**
4.14__amd64-stable: **gcp-ipi-disc-priv-oidc-fips-f28** | 4.14__amd64-nightly-4.14-upgrade-from-stable-4.14: **gcp-ipi-disc-priv-oidc-fips-f60**
4.15__amd64-stable-4.15-upgrade-from-stable-4.14: **gcp-ipi-disc-priv-oidc-fips-f28** | 4.15__amd64-nightly-4.15-upgrade-from-stable-4.14: **gcp-ipi-disc-priv-oidc-fips-f28**
4.15__amd64-stable: **gcp-ipi-disc-priv-oidc-fips-f28** | 4.15__amd64-nightly-4.15-upgrade-from-stable-4.15: **gcp-ipi-disc-priv-oidc-fips-f60**
4.15__arm64-stable-4.15-upgrade-from-stable-4.14: **gcp-ipi-disc-priv-oidc-f28** | 4.15__arm64-nightly-4.15-upgrade-from-stable-4.14: **gcp-ipi-disc-priv-oidc-f28**
4.15__arm64-stable: **gcp-ipi-disc-priv-oidc-f28** | 4.16__arm64-nightly-4.16-upgrade-from-stable-4.15: **gcp-ipi-disc-priv-oidc-f28**
4.16__amd64-stable-4.16-upgrade-from-stable-4.15: **gcp-ipi-disc-priv-oidc-fips-f28** | 4.16__amd64-nightly-4.16-upgrade-from-stable-4.15: **gcp-ipi-disc-priv-oidc-fips-f28**
4.16__amd64-stable: **gcp-ipi-disc-priv-oidc-fips-f28** | 4.16__amd64-nightly-4.16-upgrade-from-stable-4.16: **gcp-ipi-disc-priv-oidc-fips-f60**
4.16__arm64-stable-4.16-upgrade-from-stable-4.15: **gcp-ipi-disc-priv-oidc-f28** | 4.16__arm64-nightly-4.16-upgrade-from-stable-4.15: **gcp-ipi-disc-priv-oidc-f28**
4.16__arm64-stable: **gcp-ipi-disc-priv-oidc-f28** | 4.17__arm64-nightly-4.17-upgrade-from-stable-4.16: **gcp-ipi-disc-priv-oidc-f28**
4.17__amd64-stable-4.17-upgrade-from-stable-4.16: **gcp-ipi-disc-priv-oidc-fips-f28** | 4.17__amd64-nightly-4.17-upgrade-from-stable-4.16: **gcp-ipi-disc-priv-oidc-fips-f28**
4.17__amd64-stable: **gcp-ipi-disc-priv-oidc-fips-f28** | 4.17__amd64-nightly-4.17-upgrade-from-stable-4.17: **gcp-ipi-disc-priv-oidc-fips-f60**
4.17__arm64-stable-4.17-upgrade-from-stable-4.16: **gcp-ipi-disc-priv-oidc-f28** | 4.17__arm64-nightly-4.17-upgrade-from-stable-4.16: **gcp-ipi-disc-priv-oidc-f28**
4.17__arm64-stable: **gcp-ipi-disc-priv-oidc-f28** | 4.17__arm64-nightly-4.17-upgrade-from-stable-4.17: **gcp-ipi-disc-priv-oidc-f60**
4.18__amd64-stable-4.18-upgrade-from-stable-4.17: **gcp-ipi-disc-priv-oidc-fips-f28** | 4.18__amd64-nightly-4.18-upgrade-from-stable-4.17: **gcp-ipi-disc-priv-oidc-fips-f28**
4.18__amd64-stable: **gcp-ipi-disc-priv-oidc-fips-f28** | 4.18__amd64-nightly-4.18-upgrade-from-stable-4.18: **gcp-ipi-disc-priv-oidc-fips-f60**
4.18__arm64-stable-4.18-upgrade-from-stable-4.17: **gcp-ipi-disc-priv-oidc-f28** | 4.18__arm64-nightly-4.18-upgrade-from-stable-4.17: **gcp-ipi-disc-priv-oidc-f28**
4.18__arm64-stable: **gcp-ipi-disc-priv-oidc-f28** | 4.18__arm64-nightly-4.18-upgrade-from-stable-4.18: **gcp-ipi-disc-priv-oidc-f60**

### CODE REVIEW

**Comment by jianli-wei** [comment]
@jianlinliu please help review, thanks! 

BTW, I will update `gcp-ipi-proxy-oidc` into `gcp-ipi-proxy-private` in another PR.

**Comment by jianlinliu** [comment]
cc @liangxia to review.

**Pull request merged**
