### PR TITLE
Update OTEL jobs to install additional operators

### PR DESCRIPTION
**Pull request by IshwarKanse**
Install additional operators required by test case. https://github.com/open-telemetry/opentelemetry-operator/pull/3217

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-upstream-ocp-4.15-amd64-aws-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-upstream-ocp-4.15-amd64-aws-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-open-telemetry-opentelemetry-operator-main-upstream-ocp-4.15-amd64-aws-opentelemetry-e2e-tests

**Review by vprashar2929 — APPROVED** [review]
/lgtm

**Review by vprashar2929 — APPROVED** [review]
/lgtm

**Pull request merged**
