### PR TITLE
Add vsphere conformance micro upgrade jobs with core dumps

### PR DESCRIPTION
**Pull request by DennisPeriquet**
[TRT-1160](https://issues.redhat.com//browse/TRT-1160)

### CODE REVIEW

**Comment by DennisPeriquet** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-e2e-vsphere-ovn-upgrade

**Comment by DennisPeriquet** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-upgrade-from-stable-4.13-e2e-vsphere-upgrade

**Comment by DennisPeriquet** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-upgrade-from-stable-4.13-e2e-vsphere-upgrade

**Comment by DennisPeriquet** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-e2e-vsphere-ovn-upgrade
/pj-rehearse periodic-ci-openshift-release-master-ci-4.15-e2e-vsphere-ovn-upgrade

**Review by vrutkovs — APPROVED** [review]
/approve
/lgtm

**Comment by DennisPeriquet** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-e2e-vsphere-ovn-upgrade

**Comment by DennisPeriquet** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.15-e2e-vsphere-ovn-upgrade

**Comment by DennisPeriquet** [comment]
/pjrehears periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview

**Comment by DennisPeriquet** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview

**Comment by DennisPeriquet** [comment]
/pj-rehearse pull-ci-openshift-vmware-vsphere-csi-driver-release-4.15-e2e-vsphere-ovn-upgrade

**Comment by DennisPeriquet** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview

**Comment by DennisPeriquet** [comment]
i pushed an experimental change to allow `/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview` to be rehearsable.

**Pull request closed without merging**
