### PR TITLE
Update SubM main branch from 2.8 to 2.9

### PR DESCRIPTION
**Pull request by dfarrell07**

### CODE REVIEW

**Comment by dfarrell07** [comment]
I can't seem to run `make jobs` or `make update`. I'm trying while on the RH VPN and kinit'd. I don't think I needed permissions like this previously.

```
[~/go/src/openshift/release]$ make jobs
false || docker pull --platform linux/amd64 registry.ci.openshift.org/ci/ci-operator-checkconfig:latest
Error response from daemon: Head "https://registry.ci.openshift.org/v2/ci/ci-operator-checkconfig/manifests/latest": unauthorized: authentication required
make: *** [Makefile:76: ci-operator-checkconfig] Error 1
```

**Comment by skitt** [comment]
/pj-rehearse pull-ci-stolostron-submariner-addon-main-build pull-ci-stolostron-submariner-addon-main-golangci-lint pull-ci-stolostron-submariner-addon-main-images pull-ci-stolostron-submariner-addon-main-integration pull-ci-stolostron-submariner-addon-main-unit pull-ci-stolostron-submariner-addon-main-verify

(skipping sonarcloud on purpose, it always fails rehearsals).

**Pull request merged**
