### PR TITLE
Move Edge team jobs to new packet cluster profiles

### PR DESCRIPTION
**Pull request by lranjbar**
Moving the jobs managed by the edge team to new cluster profiles to use the new secrets.

### CODE REVIEW

**Comment by omertuc** [comment]
Any link to some background on what are these new cluster profiles, why this distinction was created, what's the difference between `packet`, `packet-assisted`, `packet-sno`?

**Comment by carbonin** [comment]
Looks like there are a few more changes than just changing the secrets. Can you describe what the "packet-check" jobs are doing and why they were added?

**Comment by lranjbar** [comment]
There has been a flurry of PRs in general but to try to give a TLDR:

- IT/Finance requested we move our jobs to new projects in Equinix/Packet for money reasons. 
- In Equinix the servers are created in a project associated with a project id and has some secrets (auth token and ssh key) associated with it.
- Secrets in the CI are added in a cluster profile secrets volume. This volume is created from key value pairs in the CI vault. So when we are mounting the volumes `cluster-secrets-packet-assisted` the secrets container are different then the `cluster-secrets-packet`. The secrets in the new cluster profiles have the same keys in the vault, so they are mapped to the same environment variables but with new values.
- The packet check are running the script here: https://steps.ci.openshift.org/reference/baremetalds-packet-check this script checks to see if any packet servers have failed to de-provision after 4 hours and cleans them up. It does this on a project basis, so since `packet-assisted` and `packet-sno` are new projects we require to add two more jobs to clean up servers.

**Comment by carbonin** [comment]
/lgtm

It seems like the 2.3 jobs are failing because we don't version test-infra.

**Comment by omertuc** [comment]
> There has been a flurry of PRs in general but to try to give a TLDR:
> 
> * IT/Finance requested we move our jobs to new projects in Equinix/Packet for money reasons.
> * In Equinix the servers are created in a project associated with a project id and has some secrets (auth token and ssh key) associated with it.
> * Secrets in the CI are added in a cluster profile secrets volume. This volume is created from key value pairs in the CI vault. So when we are mounting the volumes `cluster-secrets-packet-assisted` the secrets container are different then the `cluster-secrets-packet`. The secrets in the new cluster profiles have the same keys in the vault, so they are mapped to the same environment variables but with new values.
> * The packet check are running the script here: [steps.ci.openshift.org/reference/baremetalds-packet-check](https://steps.ci.openshift.org/reference/baremetalds-packet-check) this script checks to see if any packet servers have failed to de-provision after 4 hours and cleans them up. It does this on a project basis, so since `packet-assisted` and `packet-sno` are new projects we require to add two more jobs to clean up servers.

Thanks for the overview, definitely clears things up.

Didn't know about https://steps.ci.openshift.org/ - that's gold. I hate navigating through the yamls manually.

**Pull request merged**
