### PR TITLE
chore(RHIDP-2121): Add test jobs for RHDH installed with OLM

### PR DESCRIPTION
**Pull request by pmacik**

### CODE REVIEW

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp pull-ci-redhat-performance-backstage-performance-main-mvp
/test all

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/test all
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-rhdh-olm-mvp pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pr-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp-olm pull-ci-redhat-performance-backstage-performance-main-mvp

**Review by jhutar — APPROVED** [review]
/lgtm

**Pull request merged**
