### PR TITLE
fix bumping hco to golang1.21 & ocp 4.16

### PR DESCRIPTION
**Pull request by nunnatsa**

### CODE REVIEW

**Comment by dharmit** [comment]
@nunnatsa do we need to run any `pj-rehearse` here, or should I go ahead lgtm it?

**Comment by nunnatsa** [comment]
> do we need to run any `pj-rehearse` here, or should I go ahead lgtm it?

We need to wait for https://github.com/kubevirt/hyperconverged-cluster-operator/pull/2799

**Comment by nunnatsa** [comment]
/hold
waiting for https://github.com/kubevirt/hyperconverged-cluster-operator/pull/2799

**Comment by nunnatsa** [comment]
Done by the bot in #48520

**Pull request closed without merging**
