### PR TITLE
Add jobs for `main` branch of sail-operator repo

### PR DESCRIPTION
**Pull request by dgn**

### CODE REVIEW

**Review by jwendell — APPROVED** [review]

**Comment by jwendell** [comment]
The nightly job failure is legit. It's trying to use the operatorhub fork in maistra. We need to change it to openshift-service-mesh org. We can do that in a follow up though, it shouldn't block this pr.

**Comment by dgn** [comment]
Closing as this was added in https://github.com/openshift/release/pull/50564

**Pull request closed without merging**
