### PR TITLE
update env vars

### PR DESCRIPTION
**Pull request by QiaolingTang**
1. Update env vars in logging jobs
2. Remove unsupported matrix: logging 5.7 on OCP 4.15

/cc @anpingli @kabirbhartiRH @gkarager

### CODE REVIEW

**Comment by QiaolingTang** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-openshift-logging-5.8-gcp-ipi-sdn-fips-f3

**Comment by QiaolingTang** [comment]
In https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/45633/rehearse-45633-periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-openshift-logging-5.8-gcp-ipi-sdn-fips-f3/1724322934656339968/artifacts/gcp-ipi-sdn-fips-f3/ , cucushift test and web test were all triggered.

**Review by anpingli — COMMENTED** [review]
/lgtm

**Pull request merged**
