### PR TITLE
release-controller: fix RHEL AV repo baseurl

### PR DESCRIPTION
**Pull request by miabbott**
Forgot an important part of the URL in #26305

### CODE REVIEW

**Review by cgwalters — APPROVED** [review]
The content of this PR LGTM

**Review by petr-muller — APPROVED** [review]
/hold

Holding if Justin's nod is needed, feel free to unhold otherwise.

**Comment by miabbott** [comment]
Rebased and pushed a new commit based on `make update-ci-build-clusters` :arrow_up:

**Comment by HuijingHei** [comment]
I did not see any failed tests, trigger test to clarify the results
/retest

**Comment by HuijingHei** [comment]
Get error log: `{"component":"applyconfig","error":"failed to apply config","file":"/go/src/github.com/openshift/ci-tools/cmd/applyconfig/applyconfig.go:555","func":"main.main","level":"error","msg":"There were failures while applying config","severity":"error","time":"2022-02-21T17:28:48Z"}`, this is not required test and maybe can be ignored?

**Comment by petr-muller** [comment]
/test build01-dry
/test build02-dry

The failed tests are not triggered on this revision of the PR, the comment just informs that they were triggered on some previous revision and they failed. The risk of conditionally-triggered CI jobs /shrug

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
