### PR TITLE
telco5g: Fix substitution for cluster DNS name and port

### PR DESCRIPTION
**Pull request by sshnaidm**

### CODE REVIEW

**Comment by yuvalk** [comment]
you didnt explain why this is needed
is this a 4.12 thing only?

**Comment by sshnaidm** [comment]
> you didnt explain why this is needed is this a 4.12 thing only?

Maybe, we don't care in this patch which version it is. Some kubeconfigs have 2 clusters defined, we need to replace these parameters in all clusters definitions.

**Comment by yuvalk** [comment]
> > you didnt explain why this is needed is this a 4.12 thing only?
> 
> Maybe, we don't care in this patch which version it is. Some kubeconfigs have 2 clusters defined, we need to replace these parameters in all clusters definitions.

I guess I'm asking - are we sure this will work with prior versions too?

**Comment by sshnaidm** [comment]
> > > you didnt explain why this is needed is this a 4.12 thing only?
> > 
> > 
> > Maybe, we don't care in this patch which version it is. Some kubeconfigs have 2 clusters defined, we need to replace these parameters in all clusters definitions.
> 
> I guess I'm asking - are we sure this will work with prior versions too?

yes, it was tested with 11 too, it just expands the previous functionality

**Review by gpuckett-redhat — APPROVED** [review]
/lgtm

**Pull request merged**
