### PR TITLE
MULTIARCH-3731: Use hcp-cli-download component instead of hypershift-cli-download

### PR DESCRIPTION
**Pull request by dharaneeshvrd**

### CODE REVIEW

**Comment by mkumatag** [comment]
@dharaneeshvrd please provide the Jira item with adding all the information for this change

**Comment by dharaneeshvrd** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-mce-power-conformance

**Comment by dharaneeshvrd** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-mce-power-conformance

**Review by mkumatag — APPROVED** [review]
/lgtm

lets track the work item to fix the `HighlyAvailable` mode

**Pull request merged**
