### PR TITLE
NETOBSERV-1717 updates for 4.17

### PR DESCRIPTION
**Pull request by memodi**
[NETOBSERV-1717](https://issues.redhat.com//browse/NETOBSERV-1717) updates for 4.17

### CODE REVIEW

**Comment by Amoghrd** [comment]
oh okay gotcha
/lgtm

**Comment by memodi** [comment]
@Amoghrd I had to rebase, could you approve again?

**Comment by kuiwang02** [comment]
I am ok.

but it is not me to approve such PR because it is related regresion prow job.
please contact with qe-productivity to approve it.

cc @liangxia

**Pull request merged**
