### PR TITLE
Remove 2 stage pipeline for dpu operator tests

### PR DESCRIPTION
**Pull request by vrindle**

### CODE REVIEW

**Comment by jmguzik** [comment]
please let us know feedback, what was not working or missing so we could improve experience in the future.

**Comment by vrindle** [comment]
> please let us know feedback, what was not working or missing so we could improve experience in the future.

The feature worked as expected! Our requirements were the thing that changed :)

**Comment by wizhaoredhat** [comment]
Please have a more descriptive commit message. I am not sure what this achieves. What happens in the past and what this change does now.

**Comment by vrindle** [comment]
> Please have a more descriptive commit message. I am not sure what this achieves. What happens in the past and what this change does now.

ack. I addressed it

**Pull request merged**
