### PR TITLE
TRT-487: add ovn to openstack-dualstack-v6primary job name

### PR DESCRIPTION
**Pull request by jluhrsen**
this will fix the flake in the test case that checks that the job name has a string matching the running CNI (which is 'ovn' for these jobs)

### CODE REVIEW

**Comment by jluhrsen** [comment]
@mandre , @itzikb-redhat , wondering if you could look at this please?

**Review by mandre — COMMENTED** [review]
Hey @jluhrsen, thanks for taking care of it. I'm a bit surprised we're updating `e2e-openstack-dualstack-v6primary` to conform with the naming requirement but we're leaving jobs like `e2e-openstack-dualstack` untouched. Why are there not more jobs flagged as breaking the naming scheme?

Also, you should update the 4.17 periodics too after https://github.com/openshift/release/pull/52222 merged.

**Comment by jluhrsen** [comment]
> Hey @jluhrsen, thanks for taking care of it. I'm a bit surprised we're updating `e2e-openstack-dualstack-v6primary` to conform with the naming requirement but we're leaving jobs like `e2e-openstack-dualstack` untouched. Why are there not more jobs flagged as breaking the naming scheme?

there are a lot of these jobs to fix, I think, but it would be quite the task to manually look through
all of them (2k+) so I'm just taking the ones that pop up in the [sippy search](https://sippy.dptools.openshift.org/sippy-ng/tests/4.12/analysis?test=%5Bsig-ci%5D%20%5BEarly%5D%20prow%20job%20name%20should%20match%20network%20type%20%5Bapigroup%3Aconfig.openshift.io%5D%20%5BSuite%3Aopenshift%2Fconformance%2Fparallel%5D) for this failed flake.
(just a background task for me)

> Also, you should update the 4.17 periodics too after #52222 merged.

just updated this PR for that. thanks for the heads up

**Comment by jluhrsen** [comment]
@mandre , can you PTAL at this again

**Comment by mandre** [comment]
> > Hey @jluhrsen, thanks for taking care of it. I'm a bit surprised we're updating `e2e-openstack-dualstack-v6primary` to conform with the naming requirement but we're leaving jobs like `e2e-openstack-dualstack` untouched. Why are there not more jobs flagged as breaking the naming scheme?
> 
> there are a lot of these jobs to fix, I think, but it would be quite the task to manually look through all of them (2k+) so I'm just taking the ones that pop up in the [sippy search](https://sippy.dptools.openshift.org/sippy-ng/tests/4.12/analysis?test=%5Bsig-ci%5D%20%5BEarly%5D%20prow%20job%20name%20should%20match%20network%20type%20%5Bapigroup%3Aconfig.openshift.io%5D%20%5BSuite%3Aopenshift%2Fconformance%2Fparallel%5D) for this failed flake. (just a background task for me)

Would it help if our team updates the rest of our jobs to include the sdn as you did here?

> > Also, you should update the 4.17 periodics too after #52222 merged.
> 
> just updated this PR for that. thanks for the heads up

Sorry, I just noticed that we also have `e2e-openstack-dualstack-v6primary` in `ci-operator/config/openshift/openstack-test/openshift-openstack-test-release-4.18.yaml` that would need to be updated too.

**Comment by jluhrsen** [comment]
> > > Hey @jluhrsen, thanks for taking care of it. I'm a bit surprised we're updating `e2e-openstack-dualstack-v6primary` to conform with the naming requirement but we're leaving jobs like `e2e-openstack-dualstack` untouched. Why are there not more jobs flagged as breaking the naming scheme?
> > 
> > 
> > there are a lot of these jobs to fix, I think, but it would be quite the task to manually look through all of them (2k+) so I'm just taking the ones that pop up in the [sippy search](https://sippy.dptools.openshift.org/sippy-ng/tests/4.12/analysis?test=%5Bsig-ci%5D%20%5BEarly%5D%20prow%20job%20name%20should%20match%20network%20type%20%5Bapigroup%3Aconfig.openshift.io%5D%20%5BSuite%3Aopenshift%2Fconformance%2Fparallel%5D) for this failed flake. (just a background task for me)
> 
> Would it help if our team updates the rest of our jobs to include the sdn as you did here?

yes, please. that would be great :)

> 
> > > Also, you should update the 4.17 periodics too after #52222 merged.
> > 
> > 
> > just updated this PR for that. thanks for the heads up
> 
> Sorry, I just noticed that we also have `e2e-openstack-dualstack-v6primary` in `ci-operator/config/openshift/openstack-test/openshift-openstack-test-release-4.18.yaml` that would need to be updated too.

Just updated with this. sorry I missed it.

**Comment by jluhrsen** [comment]
@EmilienM @eurijon @gryf @itzikb-redhat @mandre (just took top 5 from [here](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/openstack-test/OWNERS)) :)

can you PTAL at this. just renames the job so a flake goes away.

**Pull request closed without merging**
