### PR TITLE
Bug 2001011: added upstream mapping for cloud-event-proxy to openshift 4.9

### PR DESCRIPTION
**Pull request by nishant-parekh**
added upstream mapping for cloud-event-proxy to openshift 4.9

Signed-off-by: nishant-parekh <nparekh@redhat.com>

### CODE REVIEW

**Review by aneeshkp — APPROVED** [review]

**Comment by smarterclayton** [comment]
What is this image used for?

**Comment by smarterclayton** [comment]
Naming wise the image name is very generic - this sounds like it should be prefixed with a specific subsystem (like ptp or other).  I would not expect it to be unprefixed since it’s not generic to “clouds” or “events from clouds”

**Comment by nishant-parekh** [comment]
> Naming wise the image name is very generic - this sounds like it should be prefixed with a specific subsystem (like ptp or other). I would not expect it to be unprefixed since it’s not generic to “clouds” or “events from clouds”

The rationale behind the name is that the container adheres to the Cloud Events specification  https://cloudevents.io/, and as mentioned this is a generic container that can be used in different contexts the current release being the first offering for this being used by the PTP operator.

**Comment by aneeshkp** [comment]
@smarterclayton  cloud-event-proxy container is a fast event framework based on  O-RAN Working Group   Event Consumer API for Notification and Status specifications.
cloud-event-proxy is deployed as a sidecar with other containers that want to publish their events using cloud-event-proxy event framework . It is currently used by PTP and HW Redfish events to puiblishe  events

**Pull request closed without merging**
