### PR TITLE
[WMCB] Remove WNI tests

### PR DESCRIPTION
**Pull request by PratikMahajan**
This commit removes the WNI tests from master, release-4.6, 
release-4.7 and release-4.8 branch

Ran, "make ci-operator-config", "make jobs"

### CODE REVIEW

**Review by aravindhp — CHANGES_REQUESTED** [review]
You also need to do the same for [openshift-windows-machine-config-bootstrapper-release-4.8.yaml](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-release-4.8.yaml)

**Comment by sebsoto** [comment]
lgtm besides the 4.8 change

**Review by aravindhp — APPROVED** [review]
/approve

**Pull request merged**
