### PR TITLE
[wip] update job script for cfe debug

### PR DESCRIPTION
**Pull request by lunarwhite**
debug https://issues.redhat.com/browse/OCPQE-16835

note: no need for review, don't merge

### CODE REVIEW

**Comment by lunarwhite** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-vsphere-ipi-compact-f28-destructive

**Comment by lunarwhite** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-vsphere-ipi-compact-f28-destructive

**Comment by lunarwhite** [comment]
periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-vsphere-ipi-compact-f28

**Comment by lunarwhite** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-vsphere-ipi-compact-f28

**Comment by lunarwhite** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-vsphere-ipi-compact-f28

**Comment by xingxingxia** [comment]
@lunarwhite https://github.com/openshift/release/pull/44090 has result in /1711026187670654976/artifacts/vsphere-ipi-compact-f28-destructive/openshift-extended-test-disruptive/ :
```
TEST_PARALLEL=
HOME=
PULL_REFS=
FORCE_SUCCESS_EXIT=
OS_GIT_VERSION=
UNIQUE_HASH=
PULL_BASE_SHA=
JOB_NAME=
OS_GIT_MAJOR=
KUBERNETES_SERVICE_PORT_HTTPS=
REPO_OWNER=
TEST_FILTERS=
REPORT_HANDLE_PATH=
KUBERNETES_PORT_443_TCP_PORT=
SOURCE_GIT_COMMIT=
GIT_CONFIG_KEY_0=
JOB_NAME_SAFE=
PROW_JOB_ID=
KUBERNETES_PORT_443_TCP=
OPENSHIFT_BUILD_NAME=
GOVC_URL=
PULL_TITLE=
CLUSTER_TYPE=
TERM=
OPENSHIFT_CI=
GOVC_INSECURE=
OPENSHIFT_BUILD_NAMESPACE=
PULL_PULL_SHA=
GODEBUG=x509ignoreCN=0,madvdontneed=
NSS_SDB_USE_CACHE=
PULL_NUMBER=
SSH_CLOUD_PUB_KEY=
KUBECONFIGMINIMAL=
PULL_BASE_REF=
GIT_CONFIG_COUNT=
SHLVL=
TEST_SCENARIOS=
KUBERNETES_SERVICE_PORT=
SOURCE_DATE_EPOCH=
OS_GIT_PATCH=
SOURCE_GIT_TREE_STATE=
SOURCE_GIT_TAG=
__doozer=
TEST_ROSA_LOGIN_ENV=
GOVC_RESOURCE_POOL=
BUILD_RELEASE=
JOB_TYPE=
PATH=
GOVC_DATASTORE=
KUBERNETES_SERVICE_HOST=
ENABLE_PRINT_EVENT_STDOUT=
BUILD_LOGLEVEL=
REPO_NAME=
JOB_NAME_HASH=
```
Weirdly, no proxy env vars.

**Pull request closed without merging**
