### PR TITLE
AAP pipeline with new secret

### PR DESCRIPTION
**Pull request by fabriziosta**

### CODE REVIEW

**Comment by fabriziosta** [comment]
/pj-rehearse periodic-ci-ansible-tower-qa-devel-ocp4.14-lp-interop-aap-interop-aws

**Comment by fabriziosta** [comment]
/pj-rehearse periodic-ci-ansible-tower-qa-devel-ocp4.14-lp-interop-aap-interop-aws

**Comment by fabriziosta** [comment]
/pj-rehearse periodic-ci-ansible-tower-qa-devel-ocp4.14-lp-interop-aap-interop-aws

**Review by liswang89 — APPROVED** [review]

**Pull request merged**
