### PR TITLE
origin: Pin hs/kv/bds odf to stable-4.14

### PR DESCRIPTION
**Pull request by qinqon**

### CODE REVIEW

**Comment by qinqon** [comment]
/pj-rehearse pull-ci-openshift-origin-master-e2e-baremetalds-kubevirt

**Comment by qinqon** [comment]
/pj-rehearse pull-ci-openshift-origin-master-e2e-baremetalds-kubevirt

**Comment by qinqon** [comment]
/pj-rehearse pull-ci-openshift-origin-master-e2e-baremetalds-kubevirt

**Comment by qinqon** [comment]
/pj-rehearse pull-ci-openshift-origin-master-e2e-baremetalds-kubevirt

**Comment by qinqon** [comment]
/pj-rehearse pull-ci-openshift-origin-master-e2e-baremetalds-kubevirt

**Comment by qinqon** [comment]
/pj-rehearse pull-ci-openshift-origin-master-e2e-baremetalds-kubevirt

**Comment by qinqon** [comment]
/pj-rehearse pull-ci-openshift-origin-master-e2e-baremetalds-kubevirt

**Review by maiqueb — APPROVED** [review]
/lgtm

Thank you !

**Comment by qinqon** [comment]
/pj-rehearse pull-ci-openshift-origin-master-e2e-baremetalds-kubevirt

**Review by orenc1 — APPROVED** [review]
/approve
/lgtm

**Comment by qinqon** [comment]
/hold
There were a false possitive installing the redhat catalog, let's wait for the rehearsal.

**Pull request merged**
