### PR TITLE
feat(SRVKP-3689): Add new test for image signing

### PR DESCRIPTION
**Pull request by jhutar**

### CODE REVIEW

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-images

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-images

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-images

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-images

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-images

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-images

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-images

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-images

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-images

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-images

**Review by khrm — COMMENTED** [review]
/lgtm

**Pull request merged**
