### PR TITLE
Promote systemd_unit to loki label for quicker searching

### PR DESCRIPTION
**Pull request by DennisPeriquet**
[TRT-1089](https://issues.redhat.com//browse/TRT-1089)

This [logql query](https://grafana-loki.ci.openshift.org/explore?orgId=1&left=%7B%22datasource%22:%22PCEB727DF2F34084E%22,%22queries%22:%5B%7B%22expr%22:%22%7Binvoker%3D%5C%22openshift-internal-ci%2Fdperique-job%2F9%5C%22,systemd_unit%3D%5C%22ovs-vswitchd.service%5C%22%7D%22,%22refId%22:%22A%22,%22editorMode%22:%22code%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D) shows the `systemd_unit` as a loki label using `{invoker="openshift-internal-ci/dperique-job/9",systemd_unit="ovs-vswitchd.service"}`

Screen Shot 2023-06-20 at 6 29 21 PM

### CODE REVIEW

**Comment by DennisPeriquet** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-scheduler-operator-release-4.14-e2e-aws-ovn

**Comment by DennisPeriquet** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-scheduler-operator-release-4.14-e2e-aws-ovn

**Comment by DennisPeriquet** [comment]
/pj-rehearse pull-ci-openshift-cluster-kube-scheduler-operator-release-4.14-e2e-aws-ovn

**Comment by dgoodwin** [comment]
/lgtm

Well done, thanks!

**Pull request merged**
