### PR TITLE
kubernetes: Migrate OpenStack presubmits

### PR DESCRIPTION
**Pull request by pierreprinetti**
Migrate the existing jobs to the step-registry-based jobs.

### CODE REVIEW

**Comment by pierreprinetti** [comment]
/assign @dcbw @marun
like the bot suggests

**Review by mandre — COMMENTED** [review]
/lgtm

**Comment by marun** [comment]
/approve

o/kubernetes rehearsal is passing and job is optional in any case.

**Comment by pierreprinetti** [comment]
Rebased because of https://coreos.slack.com/archives/CFUGK0K9R/p1627995943016300

**Pull request merged**
