### PR TITLE
Add new workflow for Cluster MTU

### PR DESCRIPTION
**Pull request by yunjiang29**
the installer now supports config cluster MTU in the install config (https://issues.redhat.com/browse/SPLAT-1126), 
added new job `aws-ipi-wavelength-byo-subnet-ovn-mtu-day2-f28` to cover this.

Compare to `aws-ipi-wavelength-byo-subnet-ovn-day2-f28`:
|  | `aws-ipi-wavelength-byo-subnet-ovn-day2-f28`  | `aws-ipi-wavelength-byo-subnet-ovn-mtu-day2-f28` |
| ------------- | ------------- | ------------- |
| install-config MTU  | N/A(default)  | Config MTU (`1200`) in install-config directly via `network-conf-aws-cluster-mtu`  |
| post action  | a) degrade MTU to 1200 via `network-mtu-migration-decrease`, b) add edge node  | add edge node directly  |
| purpose  | cover the process for existing cluster  | cover [SPLAT-1126](https://issues.redhat.com//browse/SPLAT-1126) |

### CODE REVIEW

**Comment by yunjiang29** [comment]
@jianlinliu @gpei let me know your thoughts about this PR, thanks.

**Comment by jianlinliu** [comment]
`aws-ipi-wavelength-byo-subnet-ovn-day2-mtu-f28` if we are setting MTU from the beginning of cluster install, I think we should remove `day2` keyword to avoid confusion.

**Comment by gpei** [comment]
> `aws-ipi-wavelength-byo-subnet-ovn-day2-mtu-f28` if we are setting MTU from the beginning of cluster install, I think we should remove `day2` keyword to avoid confusion.

I guess the `day2` keyword is mainly used for distinguish the process of adding edge node in fresh install or in post action. 
But it indeed makes the name a little confusing for how MTU was set. Or else we can make the MTU configuration more clearly like:
aws-ipi-wavelength-byo-subnet-ovn-day2-f28 - > aws-ipi-wavelength-byo-subnet-ovn-day2-**decrease-mtu**-f28
aws-ipi-wavelength-byo-subnet-ovn-day2-**mtu**-f28 - > aws-ipi-wavelength-byo-subnet-ovn-day2-**custom-mtu**-f28

**Comment by jianlinliu** [comment]
@yunjiang29 `cucushift-installer-rehearse-aws-ipi-localzone-byo-subnet-ovn-day2` also need a custom MTU, right?

**Comment by yunjiang29** [comment]
> @yunjiang29 `cucushift-installer-rehearse-aws-ipi-localzone-byo-subnet-ovn-day2` also need a custom MTU, right?

Yes,  but MTU is not required/configured at install time.

**Comment by jianlinliu** [comment]
> How about combine OVN and MTU together, means both OVN and MTU are set explicitly in this workflow/job
> `cucushift-installer-rehearse-aws-ipi-localzone-byo-subnet-ovn-day2-cluster-mtu` ->
> `cucushift-installer-rehearse-aws-ipi-localzone-byo-subnet-ovn-cluster-mtu-day2`

I am okay with that, only one comment, shall we:
`cucushift-installer-rehearse-aws-ipi-localzone-byo-subnet-ovn-day2-cluster-mtu` -> `cucushift-installer-rehearse-aws-ipi-localzone-byo-subnet-ovn-mtu-day2`

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-aws-ipi-wavelength-byo-subnet-ovn-mtu-day2-f28

**Comment by yunjiang29** [comment]
https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/47399/rehearse-47399-periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-aws-ipi-wavelength-byo-subnet-ovn-mtu-day2-f28/1744550744490512384

install-config:
```
networking:
  clusterNetworkMTU: 1200
  networkType: "OVNKubernetes"
```

post check
```
Cluster MTU: 1200
Cluster Network Type: OVNKubernetes
Expected MTU: 1200
PASS: Cluster MTU
```

**Comment by yunjiang29** [comment]
@jianlinliu @gpei PTAL, thanks

**Comment by yunjiang29** [comment]
@liangxia PTAL, thanks

**Pull request merged**
