### PR TITLE
OPRUN-3190: Reduce OLM Periodics Frequency

### PR DESCRIPTION
**Pull request by dtfranz**
Supersedes #47615

### CODE REVIEW

**Comment by tmshort** [comment]
/lgtm

Eventually, we may want to cut down the older branches to longer period (e.g. weekly).

**Comment by dtfranz** [comment]
> /lgtm
> 
> Eventually, we may want to cut down the older branches to longer period (e.g. weekly).

From @awgreene's comment [here](https://github.com/openshift/release/pull/47615#issuecomment-1889927354), it seems that happens automatically as the release's age increases. We can also probably do it manually.

**Pull request merged**
