### PR TITLE
Test e2e-gcp-ipi-sdn-migration-ovn-p2

### PR DESCRIPTION
**Pull request by weliang1**
For testing purpose, please DO NOT merge!!

### CODE REVIEW

**Comment by weliang1** [comment]
@zhaozhanqi Follow your https://github.com/openshift/release/pull/32392/files to define e2e-gcp-ipi-sdn-migration-ovn-p2, above PR passed 18 successful checks, but the log of ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml showed there no any cucushift-upgrade-prepare and cucushift-upgrade-check test cases are executed in this job:
https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/32646/rehearse-32646-periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-e2e-gcp-ipi-sdn-migration-ovn-p2/1575130762619916288/artifacts/e2e-gcp-ipi-sdn-migration-ovn-p2/cucushift-upgrade-prepare/build-log.txt
https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/32646/rehearse-32646-periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-e2e-gcp-ipi-sdn-migration-ovn-p2/1575130762619916288/artifacts/e2e-gcp-ipi-sdn-migration-ovn-p2/cucushift-upgrade-check/build-log.txt

Seem results get from https://reportportal-openshift.apps.ocp-c1.prod.psi.redhat.com/ui/#prow/launches/447 for your e2e-aws-ipi-sdn-migration-ovn-p2 job:
https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-e2e-aws-ipi-sdn-migration-ovn-p2/1572828081066872832/artifacts/e2e-aws-ipi-sdn-migration-ovn-p2/cucushift-upgrade-check/build-log.txt
https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-e2e-aws-ipi-sdn-migration-ovn-p2/1572828081066872832/artifacts/e2e-aws-ipi-sdn-migration-ovn-p2/cucushift-upgrade-prepare/build-log.txt

Any clue about this?

**Comment by zhaozhanqi** [comment]
> @zhaozhanqi Follow your https://github.com/openshift/release/pull/32392/files to define e2e-gcp-ipi-sdn-migration-ovn-p2, above PR passed 18 successful checks, but the log of ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml showed there no any cucushift-upgrade-prepare and cucushift-upgrade-check test cases are executed in this job: https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/32646/rehearse-32646-periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-e2e-gcp-ipi-sdn-migration-ovn-p2/1575130762619916288/artifacts/e2e-gcp-ipi-sdn-migration-ovn-p2/cucushift-upgrade-prepare/build-log.txt https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/32646/rehearse-32646-periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-e2e-gcp-ipi-sdn-migration-ovn-p2/1575130762619916288/artifacts/e2e-gcp-ipi-sdn-migration-ovn-p2/cucushift-upgrade-check/build-log.txt
> 
> Seem results get from https://reportportal-openshift.apps.ocp-c1.prod.psi.redhat.com/ui/#prow/launches/447 for your e2e-aws-ipi-sdn-migration-ovn-p2 job: https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-e2e-aws-ipi-sdn-migration-ovn-p2/1572828081066872832/artifacts/e2e-aws-ipi-sdn-migration-ovn-p2/cucushift-upgrade-check/build-log.txt https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-e2e-aws-ipi-sdn-migration-ovn-p2/1572828081066872832/artifacts/e2e-aws-ipi-sdn-migration-ovn-p2/cucushift-upgrade-prepare/build-log.txt
> 
> Any clue about this?

I did not find any clue. @liangxia  any thought?

**Comment by weliang1** [comment]
cucushift-upgrade-prepare and cucushift-upgrade-check test cases are executed in https://github.com/openshift/release/pull/32778.

Close this PR now

**Pull request closed without merging**
