### PR TITLE
fix(hypershift): Fix IBM Cloud periodics + remove 4.14+ tests

### PR DESCRIPTION
**Pull request by hasueki**
Fixed up failing IBM Cloud periodics for HyperShift and cleaned up unsupported tests for 4.14+.

### CODE REVIEW

**Comment by hasueki** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.12-periodics-e2e-ibmcloud-iks
/pj-rehearse periodic-ci-openshift-hypershift-release-4.12-periodics-e2e-ibmcloud-roks
/pj-rehearse periodic-ci-openshift-hypershift-release-4.13-periodics-e2e-ibmcloud-iks
/pj-rehearse periodic-ci-openshift-hypershift-release-4.13-periodics-e2e-ibmcloud-roks

**Comment by sjenning** [comment]
/approve
/lgtm
@hasueki `pj-rehearse` can only take one command per comment :man_shrugging:

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.12-periodics-e2e-ibmcloud-roks

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.13-periodics-e2e-ibmcloud-iks

**Comment by sjenning** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.13-periodics-e2e-ibmcloud-roks

**Comment by hasueki** [comment]
/pj-rehearse ci/rehearse/periodic-ci-openshift-hypershift-release-4.13-periodics-e2e-ibmcloud-roks

**Comment by hasueki** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.13-periodics-e2e-ibmcloud-roks

**Pull request closed without merging**
