### PR TITLE
SREP-1143: Add configure-alertmanager-operator

### PR DESCRIPTION
**Pull request by lisa**
Waiting on a PR to merge to openshift/configure-alertmanager-operator, but once it's done, there will be something for this changeset to do.

Signed-off-by: Lisa Seelye <lseelye@redhat.com>

### CODE REVIEW

**Comment by jewzaam** [comment]
Need to merge https://github.com/openshift/configure-alertmanager-operator/pull/3 first.

/hold

**Comment by dak1n1** [comment]
https://github.com/openshift/configure-alertmanager-operator/pull/3 has merged

**Pull request merged**
