### PR TITLE
Revert "Nutanix failure domain"

### PR DESCRIPTION
**Pull request by rvanderp3**
Reverts openshift/release#47854

### CODE REVIEW

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-nutanix-ovn

**Comment by jrvaldes** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-nutanix-e2e-operator

**Comment by deads2k** [comment]
/hold

/assign @mffiedler 

I've labelled so that we have the option, but I'm not familiar enough with the area to weigh whether it's more important to keep the old set of jobs working or the new set of jobs working.  

@mffiedler please represent QE while they're out.

**Review by mffiedler — APPROVED** [review]

**Pull request merged**
