### PR TITLE
Mirror ironic-hardware-inventory-recorder to quay.io

### PR DESCRIPTION
**Pull request by elfosardo**
Adding configuration to mirror ironic-hardware-inventory-recorder
image to quay.io

### CODE REVIEW

**Comment by smarterclayton** [comment]
Why do you guys have so many images?  Are these really all necessary?  I'd really like some reassurance that you need all these different images to accomplish your goals.  One image per task is not a scalable model for other reasons.

**Comment by elfosardo** [comment]
@smarterclayton hi!
Thank you for your comment and your questions, I'll try to be brief and exhaustive in the explanation on why we need so many images.
ironic-image: this is the main service image that runs api and conductor; this is fundamental for all the entire baremetal managing platform
ironic-inspector-image: this is the image that runs the inspector service; it's an auxiliary service for discovering hardware properties for a node managed by Ironic; if we want reliable information on the nodes we're managing, we need this
ironic-ipa-downloader: this is an helper image that allows us to download the ironic-python-agent ramdisk to be used during node discovery and inspection
ironic-rhcos-downloader (name going to change): another helper image to download the image necessary during deployment
ironic-static-ip-manager: this is another helper that allows to set and maintain an IP address for provisioning pods
ironic-hardware-inventory-recorder (the image this PR is about): this is a continuous running daemon that allows us to periodically collect info on the hardware in the managed nodes

I'm not entirely in agreement with you about the fact that "One image per task is not a scalable model for other reasons.", especially because I don't know these reasons, but maybe this can be a topic for a separate discussion.

The reason why we have this task open for this new image is because it was not included in OSP 4.2, it will be included in 4.3 and forward, hence the new related tasks.

Thanks and please let me know if you have any more questions.

CC: @juliakreger @hardys @russellb @dhellmann

**Comment by elfosardo** [comment]
@smarterclayton  please let me know if you need any more info

**Comment by elfosardo** [comment]
this was integrated in a recent automated patch

**Pull request closed without merging**
