### PR TITLE
Add azure upgrade job for 4.15 arm64 and add stable upgrade jobs for arm64 and multi

### PR DESCRIPTION
**Pull request by Prashanth684**
Adding a bunch of missed jobs (azure) for 4.15

### CODE REVIEW

**Comment by Prashanth684** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.15-upgrade-from-stable-4.14-ocp-e2e-upgrade-azure-ovn-arm64

**Comment by Prashanth684** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.15-upgrade-from-stable-4.14-ocp-e2e-upgrade-azure-ovn-heterogeneous

**Comment by Prashanth684** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.15-ocp-e2e-upgrade-azure-ovn-arm64

**Review by aleskandro — APPROVED** [review]

**Review by bradmwilliams — APPROVED** [review]

**Pull request merged**
