### PR TITLE
Onboard medik8s/ha-sno

### PR DESCRIPTION
**Pull request by mshitrit**
- build binary
- build image
- run unit tests
- no e2e tests yet

### CODE REVIEW

**Review by hongkailiu — COMMENTED** [review]
/lgtm

/hold

feel free to cancel if you want to handle the rehearsals' failures later.

**Review by petr-muller — APPROVED** [review]

**Comment by mshitrit** [comment]
Hi @hongkailiu . @petr-muller 
Looks like I don't have the permissions to unhold the PR (or that I'm missing something else :thinking: )
Can you please unhold it ?

**Comment by petr-muller** [comment]
It's not permissions, probably we were just rate limited at that time and Prow gave up.

**Comment by petr-muller** [comment]
Weird - hook got the event, other plugins processed it, but `hold` logged nothing about the event... The code for `hold` is simple, probably *somehow* we fell through one of the paths that log nothing, but I have no idea why :( 

https://github.com/kubernetes/test-infra/blob/8081d1848d1c6abc3dcf3f3ab19367cc5ad62a95/prow/plugins/hold/hold.go#L83-L115

**Pull request merged**
