### PR TITLE
Add hypershift e2e test for autoscaler

### PR DESCRIPTION
**Pull request by enxebre**
Add hypershift e2e test for autoscaler.

Needs https://github.com/openshift/release/pull/32790

### CODE REVIEW

**Comment by enxebre** [comment]
Add always run non required tests, both autoscaling and netoworking operator repo went green.
PTAL @sjenning 
FYI cc @danwinship @JoelSpeed

**Review by elmiko — COMMENTED** [review]
makes sense to me, thanks for the heads up @enxebre :+1:

**Pull request merged**
