### PR TITLE
Migrate vSphere UPI 4.3 to step-registry and VMC

### PR DESCRIPTION
**Pull request by jcpowermac**

### CODE REVIEW

**Comment by jcpowermac** [comment]
@mtnbikenc or @jhixson74 can one of you ptal? Thanks!

**Review by mtnbikenc — APPROVED** [review]
/lgtm

**Review by petr-muller — COMMENTED** [review]
/approve

This needs regenerating the metadata, looks good otherwise.

**Comment by petr-muller** [comment]
/hold

Merge conflict

**Comment by petr-muller** [comment]
/close 

Please reopen if still relevant

**Pull request closed without merging**
