### PR TITLE
Draft: Debug OCPBUGS-11567

### PR DESCRIPTION
**Pull request by shellyyang1989**

### CODE REVIEW

**Comment by shellyyang1989** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-stable-aws-ipi-to-multiarch-p2-f14

**Comment by lyman9966** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-stable-azure-ipi-baselinecaps-v412-to-multiarch-p2-f14

**Comment by shellyyang1989** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-stable-4.12-aws-ipi-disconnected-private-p1-f28

**Comment by shellyyang1989** [comment]
/pj-rehearse  periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-stable-4.12-aws-ipi-disconnected-sts-p2-f28

**Pull request closed without merging**
