### PR TITLE
Add MTC for HCP 4.15 tests

### PR DESCRIPTION
**Pull request by liswang89**

### CODE REVIEW

**Comment by liswang89** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.15-lp-rosa-hypershift-mtc-interop-aws-rosa

**Comment by liswang89** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.15-lp-rosa-hypershift-mtc-interop-aws-rosa

**Comment by liswang89** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.15-lp-rosa-hypershift-mtc-interop-aws-rosa

**Comment by liswang89** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.15-lp-rosa-hypershift-mtc-interop-aws-rosa

**Comment by liswang89** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.15-lp-rosa-hypershift-mtc-interop-aws-rosa

**Comment by liswang89** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.15-lp-rosa-hypershift-mtc-interop-aws-rosa

**Comment by liswang89** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.15-lp-rosa-hypershift-mtc-interop-aws-rosa

**Comment by liswang89** [comment]
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.15-lp-rosa-hypershift-mtc-interop-aws-rosa

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
