### PR TITLE
Run OSA production job optionally for PRs

### PR DESCRIPTION
**Pull request by 0xmichalis**

### CODE REVIEW

**Comment by kargakis** [comment]
@openshift/sig-azure adding this optional job to exercise e2e tests meant to run against the production RP (eg. https://github.com/openshift/openshift-azure/pull/824).

**Comment by mjudeikis** [comment]
lgtm

**Comment by kargakis** [comment]
/hold cancel

This job is only going to work only after the OSA RP revendor. It should block any PR that touches realrp tests but I think it's acceptable since we cannot really tests these changes yet anyway.

**Comment by kargakis** [comment]
actually the `/test all` command is required now for `run_if_changed` jobs which means that if we merge this now it's going to run on every PR with `/test all` and we don't really want that as long as the job is broken.

**Comment by kargakis** [comment]
Though we should be able to skip it in PRs where we don't need it to run with `/skip`.

**Comment by kargakis** [comment]
@petr-muller @bbguimaraes I don't understand why I need to include the *optional* job I am introducing here (always_run: false) in `all`.
```
[ERROR] ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml: ci-operator job pull-ci-openshift-openshift-azure-master-e2e-azure-prod should have trigger ((?m)^/test( all| e2e-azure-prod),?(\s+|$))
```

**Pull request merged**
