### PR TITLE
USHIFT-1588: Remove microshift-test-payload image

### PR DESCRIPTION
**Pull request by pacevedom**
Remove the need of having microshift-test-payload, since all building and dependency handling happens on the test VM itself (regardless of being metal or not).
This image was the longest to complete. By removing it we are saving more than 12 minutes on average. Building in the test machine is something that was either already happening (in the metal job), or taking 3-4 minutes in a regular t2 VM in AWS.

### CODE REVIEW

**Comment by pacevedom** [comment]
/pj-rehearse ack
Failures from conformance are related to the tests themselves, not how it was installed. Considering this, its ready for review.
@pmtk @ggiguash @copejon @eslutsky @dhellmann

**Comment by pmtk** [comment]
/test pull-ci-openshift-microshift-release-4.13-e2e-greenboot 

This looks good, let me just run 4.13 presubmit to be sure :)

**Comment by pacevedom** [comment]
/pj-rehearse periodic-ci-openshift-microshift-main-ocp-conformance-nightly periodic-ci-openshift-microshift-release-4.14-ocp-conformance-nightly pull-ci-openshift-microshift-main-microshift-metal-tests pull-ci-openshift-microshift-release-4.14-microshift-metal-tests

**Pull request merged**
