### PR TITLE
Fixes AWS jobs configs for arm64

### PR DESCRIPTION
**Pull request by aleskandro**
This PR fixes AWS UPI/IPI jobs configs definitions for both e2e and upgrade qe tests, currently failing as reported in:
- [OCPQE-13353](https://issues.redhat.com//browse/OCPQE-13353)
- [OCPQE-13358](https://issues.redhat.com//browse/OCPQE-13358)
- [OCPQE-13352](https://issues.redhat.com//browse/OCPQE-13352)

/cc @yunjiang29

### CODE REVIEW

**Comment by aleskandro** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-nightly-aws-upi-p3-f28

**Comment by kuiwang02** [comment]
i am ok from golang's view.
but it is related to regression job, so please get qe-productivity team to approve it.

**Pull request merged**
