### PR TITLE
remove rhmi e2e job from master branch, bump prow ocp version to 4.8 for rhmi 2.9 branch

### PR DESCRIPTION
**Pull request by psturc**
https://issues.redhat.com/browse/MGDAPI-1162

### Additional changes
https://github.com/openshift/release/pull/24203/commits/f031c06a4efd16cf6efe7691a8c177f9ede0c81a, https://github.com/openshift/release/pull/24203/commits/17e206aeea52191037a39dab9be93112cdf65eb0

### Explanation
We found out that prow rhoam-e2e job was using RHOAM container image built from master branch (quay.io/integreatly/integreatly-operator:master) for installing RHOAM, which is wrong. The job should use the image that is built by prow from the PR.

This is most probably caused by an env var $IMAGE_FORMAT being deprecated in openshift CI: https://docs.ci.openshift.org/docs/architecture/step-registry/#available-environment-variables
(we are relying on prow assigning a value to this env var, for example here: https://github.com/integr8ly/integreatly-operator/blob/1f35b372af3e617ea46c21feb4794fe34bfba4a2/Makefile#L206)

Fortunately, the fix seems to be straightforward, and requires only to update test job's metadata in openshift/release repo.
I already tried that for e2e job and it worked: https://github.com/openshift/release/pull/24203/commits/0f01af5d61d2c354ab9d061cc2e090f9d7f16b70
(I followed the steps here: https://docs.ci.openshift.org/docs/architecture/ci-operator/#referring-to-images-in-tests)

### CODE REVIEW

**Comment by psturc** [comment]
e2e job is failing here because the prow job uses "master" tag of integreatly-operator image.

I used the hardcoded image ("2.9") in this PR and the e2e test passed: https://github.com/integr8ly/integreatly-operator/pull/2302
Not sure if this is the best solution though

**Comment by psturc** [comment]
Hi @MStokluska, the "multitenant-rhoam-e2e" job has failed with this error
```
[BeforeSuite] BeforeSuite 
/go/src/github.com/integr8ly/integreatly-operator/test/e2e/suite_test.go:83
  Unexpected error:
      
      <*errors.errorString | 0xc0001ffad0>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
```

I assume it failed because the make command for running multitenant e2e job was failing on creating some rhoam resources:
```
...
clusterrolebinding.rbac.authorization.k8s.io/rhoam-manager-rolebinding created
Error from server (NotFound): error when creating "STDIN": namespaces "redhat-rhoam-operator" not found
Error from server (NotFound): error when creating "STDIN": namespaces "redhat-rhoam-operator" not found
Error from server (NotFound): error when creating "STDIN": namespaces "redhat-rhoam-operator" not found
Error from server (NotFound): error when creating "STDIN": namespaces "redhat-rhoam-operator" not found
Error from server (NotFound): error when creating "STDIN": namespaces "redhat-rhoam-operator" not found
Error from server (NotFound): error when creating "STDIN": namespaces "redhat-rhoam-operator" not found
Error from server (NotFound): error when creating "STDIN": namespaces "redhat-rhoam-operator" not found
```

Full log [here](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/24203/rehearse-24203-pull-ci-integr8ly-integreatly-operator-master-multitenant-rhoam-e2e/1470398783773741056/artifacts/multitenant-rhoam-e2e/test/build-log.txt)

Is this a known issue?

**Comment by MStokluska** [comment]
> 

hey, no, it should not be happening, from what I see it looks for redhat-rhoam-operator ns, while it should be looking for sandbox-rhoam-operator ns

**Pull request merged**
