### PR TITLE
Onboarding Dev Spaces operator on ROSA Classic

### PR DESCRIPTION
**Pull request by Sau1506mya**
Link to JIRA : [[LPTOCPCI-1404](https://issues.redhat.com/browse/LPTOCPCI-1404)]

### CODE REVIEW

**Comment by Sau1506mya** [comment]
/pj-rehearse pull-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.15-lp-rosa-classic-images periodic-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.15-lp-rosa-classic-devspaces-rosa-aws

**Comment by Sau1506mya** [comment]
/pj-rehearse pull-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.16-lp-rosa-classic-images periodic-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.16-lp-rosa-classic-devspaces-rosa-aws

**Comment by Sau1506mya** [comment]
/pj-rehearse pull-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.14-lp-rosa-classic-images periodic-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.14-lp-rosa-classic-devspaces-rosa-aws

**Comment by Sau1506mya** [comment]
/pj-rehearse pull-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.14-lp-rosa-classic-images periodic-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.14-lp-rosa-classic-devspaces-rosa-aws

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
