### PR TITLE
feat: Migrate to our new standalone AWS account

### PR DESCRIPTION
**Pull request by jhutar**

### CODE REVIEW

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-1000-200

**Comment by jhutar** [comment]
/pj-rehearse pull-ci-openshift-pipelines-performance-main-max-concurrency-downstream-1-13-1000-200

**Review by concaf — APPROVED** [review]
/lgtm

**Pull request merged**
