### PR TITLE
write-jobs-to-gsheet

### PR DESCRIPTION
**Pull request by qiliRedHat**
https://issues.redhat.com/browse/PERFSCALE-2954

### CODE REVIEW

**Comment by krishvoor** [comment]
@qiliRedHat Thanks for the PR, I want to understand how this https://github.com/openshift-qe/ocp-qe-perfscale-ci/tree/main/prow/generate_jobs_in_gsheet today maintained/executed.

**Comment by qiliRedHat** [comment]
> @qiliRedHat Thanks for the PR, I want to understand how this https://github.com/openshift-qe/ocp-qe-perfscale-ci/tree/main/prow/generate_jobs_in_gsheet today maintained/executed.

@krishvoor Hi Harsha
AFAIK before I start the work of https://issues.redhat.com/browse/PERFSCALE-2954, the script under generate_jobs_in_gsheet was run manually by Sharada and/or Paige when we have the need to review the latest prow jobs.
@rpattath Thought it's helpful to run it automatically every sprint so that we can get the latest information without asking some team member to help running the script. That is https://issues.redhat.com/browse/PERFSCALE-2954 what I'm working on.
One of my concern is how to remove the old tabs generated by this job. Please let me know if you have any other questions/concerns, we can continue exchange our thoughts in the JIRA after the PR is merged.

**Comment by qiliRedHat** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-write_jobs_to_gsheet-write-jobs-to-google-sheet-sprintly

**Comment by qiliRedHat** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-write_jobs_to_gsheet-write-jobs-to-google-sheet-sprintly

**Comment by qiliRedHat** [comment]
@paigerube14 @svetsa-rh PTAL

**Pull request merged**
