### PR TITLE
Add tests for NFD container

### PR DESCRIPTION
**Pull request by zvonkok**
Add tests for NFD container

### CODE REVIEW

**Comment by zvonkok** [comment]
@petr-muller @stevekuznetsov  please take a look, buildilng the 4.3 release images fails with 
```
error: unable to create a release: operator "cluster-openshift-apiserver-operator" contained an invalid image-references file: no input image tag named "openshift-apiserver"
```

all of my tests pass.

**Comment by petr-muller** [comment]
Looks good, but the repo should also be added to the Tide queries here: https://github.com/openshift/release/blob/master/cluster/ci/config/prow/config.yaml#L79

We also suggest to enable the approve plugin (https://github.com/openshift/release/blob/master/cluster/ci/config/prow/plugins.yaml#L57)

**Comment by petr-muller** [comment]
>  please take a look, buildilng the 4.3 release images fails with

This means that image was not yet built for 4.3, which is not a pressing problem,

**Comment by zvonkok** [comment]
@petr-muller regarding your points I added it to tide and the approve plugin.

**Comment by petr-muller** [comment]
> @petr-muller regarding your points I added it to tide and the approve plugin.

Hm, don't see anything new here, maybe you forgot to push?

**Comment by zvonkok** [comment]
@petr-muller ups wrong branch, it should be there now. PTAL

**Comment by zvonkok** [comment]
@petr-muller I fixed the owners file.

**Comment by zvonkok** [comment]
@petr-muller is the label `do-not-merge/invalid-owners-file` automatically removed? Thanks

**Comment by petr-muller** [comment]
/lgtm cancel

Let's stop the retest bot until I figure out why the bot does not notice @cep235 joining the org :/

**Pull request merged**
