### PR TITLE
Build multiple images in one repo and publish with condition

### PR DESCRIPTION
**Pull request by clyang82**
Build multiple images in one repo and publish with condition.
ref: https://github.com/open-cluster-management/backlog/issues/14034

Signed-off-by: clyang82 <chuyang@redhat.com>

### CODE REVIEW

**Review by songleo — APPROVED** [review]

**Review by morvencao — COMMENTED** [review]
/lgtm

**Review by morvencao — COMMENTED** [review]
/lgtm

**Pull request merged**
