### PR TITLE
Add 4.15 configs for community operators

### PR DESCRIPTION
**Pull request by Allda**
JIRA: [ISV-3704](https://issues.redhat.com//browse/ISV-3704)

### CODE REVIEW

**Comment by mporrato** [comment]
@Allda aren't you going to add 4.15 for the community dev branch too?
([ci-operator/jobs/redhat-openshift-ecosystem/community-operators-pipeline-preprod](https://github.com/openshift/release/blob/master/ci-operator/jobs/redhat-openshift-ecosystem/community-operators-pipeline-preprod/redhat-openshift-ecosystem-community-operators-pipeline-preprod-dev-presubmits.yaml))

**Comment by Allda** [comment]
> [community-operators-pipeline-preprod](https://github.com/openshift/release/blob/master/ci-operator/jobs/redhat-openshift-ecosystem/community-operators-pipeline-preprod/redhat-openshift-ecosystem-community-operators-pipeline-preprod-dev-presubmits.yaml))

I missed that, thanks for the reminder. Now it should be complete.

**Pull request merged**
