### PR TITLE
telcov10n: add testing phase and tests script to hcp-cnf testing

### PR DESCRIPTION
**Pull request by rshemtov13**
This PR will add the testing portion of our (telcov10n) Hypershift testing for NTO test cases For now we will only be testing tier-0 test cases specified in the commands.sh script. After the results have been stable for multiple runs we will gradually progress to the entire test suite.

### CODE REVIEW

**Comment by rshemtov13** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-hcp-cnf-4.17-e2e-telcov10n-functional-hcp-cnf-stable

**Comment by rshemtov13** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-hcp-cnf-4.17-e2e-telcov10n-functional-hcp-cnf-stable

**Comment by rshemtov13** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-hcp-cnf-4.17-e2e-telcov10n-functional-hcp-cnf-stable

**Comment by rshemtov13** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-hcp-cnf-4.17-e2e-telcov10n-functional-hcp-cnf-stable

**Comment by rshemtov13** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-hcp-cnf-4.17-e2e-telcov10n-functional-hcp-cnf-stable

**Comment by sshnaidm** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-hcp-cnf-4.17-e2e-telcov10n-functional-hcp-cnf-stable

**Comment by rshemtov13** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-hcp-cnf-4.17-e2e-telcov10n-functional-hcp-cnf-stable

**Comment by rshemtov13** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-hcp-cnf-4.17-e2e-telcov10n-functional-hcp-cnf-stable

**Comment by rshemtov13** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-hcp-cnf-4.17-e2e-telcov10n-functional-hcp-cnf-stable

**Comment by rshemtov13** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-hcp-cnf-4.17-e2e-telcov10n-functional-hcp-cnf-stable

**Comment by rshemtov13** [comment]
/pj-rehearse periodic-ci-openshift-kni-eco-ci-cd-main-hcp-cnf-4.18-e2e-telcov10n-functional-hcp-cnf-nightly

**Pull request closed without merging**
