### PR TITLE
Reset memory vLLM ROCM build

### PR DESCRIPTION
**Pull request by vaibhavjainwiz**

### CODE REVIEW

**Comment by droslean** [comment]
/pj-rehearse pull-ci-opendatahub-io-vllm-main-rocm-pr-image-mirror

**Comment by droslean** [comment]
/pj-rehearse pull-ci-opendatahub-io-vllm-main-rocm-pr-image-mirror

**Comment by droslean** [comment]
/pj-rehearse pull-ci-opendatahub-io-vllm-main-rocm-pr-image-mirror

**Comment by droslean** [comment]
/pj-rehearse pull-ci-opendatahub-io-vllm-main-rocm-pr-image-mirror

**Comment by dtrifiro** [comment]
This build will require ~9GB of peak memory per job (see https://github.com/Dao-AILab/flash-attention/blob/main/setup.py#L473-L485)

**Comment by dtrifiro** [comment]
@vaibhavjainwiz 
Here's a sample of the memory usage for a successful build.

image


Can you set the limits for the rocm build accordingly? i.e. 8GB requests, limit 10GB?

**Pull request closed without merging**
