### PR TITLE
Move periodic deploy job to build01

### PR DESCRIPTION
**Pull request by yuvalturg**
Signed-off-by: Yuval Turgeman <yturgema@redhat.com>

### CODE REVIEW

**Review by orenc1 — APPROVED** [review]
worth a try

**Comment by yuvalturg** [comment]
@droslean can you review this please ?

**Review by droslean — APPROVED** [review]

**Comment by droslean** [comment]
So, the rehearse [job](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/13201/rehearse-13201-periodic-ci-kubevirt-hyperconverged-cluster-operator-master-hco-e2e-deploy-nightly-master-aws/1321444756210847744) suceeded. I assume this change helped.

**Pull request merged**
