### PR TITLE
Deploy cluster-display

### PR DESCRIPTION
**Pull request by hongkailiu**
/hold
wait for https://github.com/openshift/ci-tools/pull/2075

required by https://github.com/openshift/ci-docs/pull/154

https://issues.redhat.com/browse/DPTP-2242

/cc @openshift/openshift-team-developer-productivity-test-platform

### CODE REVIEW

**Comment by hongkailiu** [comment]
rebuilding the image ...

**Comment by hongkailiu** [comment]
We are ready.
```
oc get pod -n ci ci-docs-5fd7894589-rj8qm
NAME                       READY   STATUS    RESTARTS   AGE
ci-docs-5fd7894589-rj8qm   2/2     Running   0          2m59s

oc rsh -n ci ci-docs-5fd7894589-rj8qm
Defaulted container "ci-docs" out of: ci-docs, cluster-display
~ $ curl locahost:8090
curl: (6) Could not resolve host: locahost
~ $ curl localhost:8090
404 page not found
~ $ curl localhost:8090/api/health
{"ok":true}
~ $ curl localhost:8090/api/v1/clusterpools
{"data":[{"imageSet":"ocp-4.6.0-amd64","labels":"architecture=amd64,cloud=aws,owner=dpp,product=ocp,region=us-east-1,version=4.6","maxSize":"10","name":"ci-ocp-4-6-amd64-aws-us-east-1","namespace":"ci-cluster-pool","owner":"dpp","ready":"1","releaseImage":"quay.io/openshift-release-dev/ocp-release:4.6.35-x86_64","size":"1"},{"imageSet":"ocp-4.7.0-amd64","labels":"architecture=amd64,cloud=aws,owner=dpp,product=ocp,region=us-east-1,version=4.7","maxSize":"20","name":"ci-ocp-4-7-amd64-aws-us-east-1","namespace":"ci-cluster-pool","owner":"dpp","ready":"10","releaseImage":"quay.io/openshift-release-dev/ocp-release:4.7.17-x86_64","size":"10"},{"imageSet":"ocp-4.8.0-amd64","labels":"architecture=amd64,cloud=aws,owner=dpp,product=ocp,region=us-east-1,version=4.8","maxSize":"20","name":"ci-ocp-4-8-amd64-aws-us-east-1","namespace":"ci-cluster-pool","owner":"dpp","ready":"8","releaseImage":"quay.io/openshift-release-dev/ocp-release:4.8.0-rc.0-x86_64","size":"10"},{"imageSet":"ocp-4.7.0-amd64","labels":"architecture=amd64,cloud=aws,owner=fake,product=ocp,version=4.7","maxSize":"10","name":"fake-ocp-4-7-amd64-aws","namespace":"fake-cluster-pool","owner":"fake","ready":"3","releaseImage":"quay.io/openshift-release-dev/ocp-release:4.7.17-x86_64","size":"3"}]}
```

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
