### PR TITLE
Add ruby to ctlplane pre-commit

### PR DESCRIPTION
**Pull request by fao89**

### CODE REVIEW

**Comment by fao89** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-precommit-check

**Comment by viroel** [comment]
/pj-rehearse ack

pre-commit job is green

**Comment by fao89** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-precommit-check

**Comment by fao89** [comment]
> [APPROVALNOTIFIER] This PR is **NOT APPROVED**
> 
> This pull-request has been approved by: _[fao89](https://github.com/openshift/release/pull/50782#)_, _[viroel](https://github.com/openshift/release/pull/50782#issuecomment-2047259040)_ **Once this PR has been reviewed and has the lgtm label**, please assign [aleskandro](https://github.com/aleskandro), [deepsm007](https://github.com/deepsm007) for approval. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).
> 
> The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=openshift%2Frelease).
> 
> Needs approval from an approver in each of these files:
> * ~[ci-operator/config/openstack-k8s-operators/openstack-operator/OWNERS](https://github.com/openshift/release/blob/master/ci-operator/config/openstack-k8s-operators/openstack-operator/OWNERS)~ [viroel]
> * **[ci-operator/jobs/openshift-qe/baremetal-qe-infra/OWNERS](https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift-qe/baremetal-qe-infra/OWNERS)**
> * **[ci-operator/jobs/openshift/ci-tools/OWNERS](https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/ci-tools/OWNERS)**
> * **[ci-operator/jobs/openshift/multiarch-tuning-operator/OWNERS](https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/multiarch-tuning-operator/OWNERS)**
> 
> Approvers can indicate their approval by writing `/approve` in a comment Approvers can cancel approval by writing `/approve cancel` in a comment

it breaks without `make jobs` but with `make jobs` it requires other people to approve 😕

**Comment by viroel** [comment]
> > [APPROVALNOTIFIER] This PR is **NOT APPROVED**
> > This pull-request has been approved by: _[fao89](https://github.com/openshift/release/pull/50782#)_, _[viroel](https://github.com/openshift/release/pull/50782#issuecomment-2047259040)_ **Once this PR has been reviewed and has the lgtm label**, please assign [aleskandro](https://github.com/aleskandro), [deepsm007](https://github.com/deepsm007) for approval. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).
> > The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=openshift%2Frelease).
> > Needs approval from an approver in each of these files:
> > 
> > * ~[ci-operator/config/openstack-k8s-operators/openstack-operator/OWNERS](https://github.com/openshift/release/blob/master/ci-operator/config/openstack-k8s-operators/openstack-operator/OWNERS)~ [viroel]
> > * **[ci-operator/jobs/openshift-qe/baremetal-qe-infra/OWNERS](https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift-qe/baremetal-qe-infra/OWNERS)**
> > * **[ci-operator/jobs/openshift/ci-tools/OWNERS](https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/ci-tools/OWNERS)**
> > * **[ci-operator/jobs/openshift/multiarch-tuning-operator/OWNERS](https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/multiarch-tuning-operator/OWNERS)**
> > 
> > Approvers can indicate their approval by writing `/approve` in a comment Approvers can cancel approval by writing `/approve cancel` in a comment
> 
> it breaks without `make jobs` but with `make jobs` it requires other people to approve 😕

we might need to ask testplataform team to fix this first

**Pull request merged**
