### PR TITLE
Remove old non-CSI snapshotter images

### PR DESCRIPTION
**Pull request by jsafrane**
Old snapshot implementation, based on snapshot-controller and snapshot-provisioner (and not based on CSI), has been deprecated in 4.2 and should be removed in 4.3 onwards. In 4.4 we start with CSI snapshots.

See https://docs.openshift.com/container-platform/4.2/release_notes/ocp-4-2-release-notes.html:

```
Persistent volume snapshots are deprecated in OpenShift Container Platform 4.2.
```

cc @openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
Rebased. And removing the images from 4.4 onwards, 4.3 has been released and I don't think it's a good idea to remove images from there.

**Comment by petr-muller** [comment]
@smarterclayton needs to approve the image mirroring changes

**Pull request merged**
