### PR TITLE
OSASINFRA-3231: Remove Kuryr jobs for 4.15 and 4.16

### PR DESCRIPTION
**Pull request by dulek**
This commit removes the jobs defined for release-4.15 and release-4.16 branches of Kuryr and attempts to opt Kuryr out of automated branching.

This is all because Kuryr support is dropped in 4.15.

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
/lgtm
/approve
/hold

LGTM, I know you wanted to keep these job until we remove all bits of kuryr from the installer. Please remove the hold at your convenience.

**Comment by dulek** [comment]
/hold cancel

I'll just do it right away, order doesn't really mean that much if we've removed Kuryr from CNO already.

/assign @dhellmann

**Review by mandre — COMMENTED** [review]
/lgtm

**Review by jmguzik — APPROVED** [review]

**Pull request merged**
