### PR TITLE
[release-4.14] Build ecr-credential-provider in CI

### PR DESCRIPTION
**Pull request by theobarberbany**
OCPBUGS-27759:  4.14 backport of #47648

### CODE REVIEW

**Comment by theobarberbany** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-aws-release-4.14-e2e-aws-ovn

**Comment by JoelSpeed** [comment]
/lgtm
/approve
/pj-rehearse ack

Images rehearsal passed, LGTM

**Pull request merged**
