### PR TITLE
add prod jobs and remove old ones

### PR DESCRIPTION
**Pull request by yuwang-RH**
Add new jobs on prod tesging:
rosa-sts-advanced-prod-critical-high-f3
rosa-hcp-advanced-prod-critical-high-f3
rosa-sts-upgrade-y-stream-prod-f3

And removed jobs on old CI which are migrating to one CI:
aws-rosa-upgrade-e2e-f7
aws-rosa-byo-kms-oidc-prod-critical-e2e-f3
aws-rosa-private-proxy-prod-critical-e2e-f7
aws-rosa-hcp-byo-kms-oidc-auditlog-prod-critical-e2e-f3
aws-rosa-hcp-private-proxy-prod-critical-e2e-f7
aws-rosa-hcp-upgrade-e2e-f7

### CODE REVIEW

**Review by robpblake — APPROVED** [review]
/lgtm

**Review by robpblake — APPROVED** [review]
/approve

**Comment by xueli181114** [comment]
@liangxia Can I have this merged?

**Pull request merged**
