### PR TITLE
Adds secrets for nfv cluster_type

### PR DESCRIPTION
**Pull request by adduarte**
Adds required definition for secrets for the nfv cluster type

### CODE REVIEW

**Review by hongkailiu — COMMENTED** [review]
has the added secret the same content as the others?
Could we do it similarly to https://github.com/openshift/release/pull/23271 for simplicity?
You can rebase after that one merges.

**Comment by EmilienM** [comment]
> has the added secret the same content as the others? Could we do it similarly to #23271 for simplicity? You can rebase after that one merges.

The content is different from other cluster types, so I guess we need a new one?

**Comment by EmilienM** [comment]
/lgtm

This is ready to go.

**Review by droslean — APPROVED** [review]

**Pull request merged**
