### PR TITLE
hco: enable CI on release-1.3 branch

### PR DESCRIPTION
**Pull request by tiraboschi**
hco: enable CI on release-1.3 branch

### CODE REVIEW

**Comment by orenc1** [comment]
on `hco-e2e-upgrade-aws` we've got `ImagePullBackOff` for the hco images.
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/14520/rehearse-14520-pull-ci-kubevirt-hyperconverged-cluster-operator-release-1.3-hco-e2e-upgrade-aws/1341814060018044928#1:build-log.txt%3A215

**Comment by tiraboschi** [comment]
> on `hco-e2e-upgrade-aws` we've got `ImagePullBackOff` for the hco images.
> https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/14520/rehearse-14520-pull-ci-kubevirt-hyperconverged-cluster-operator-release-1.3-hco-e2e-upgrade-aws/1341814060018044928#1:build-log.txt%3A215

After https://github.com/kubevirt/hyperconverged-cluster-operator/pull/1021 it passed (at least on AWS)

**Review by nunnatsa — APPROVED** [review]

**Pull request merged**
