### PR TITLE
WIP Build image from Dockerfile

### PR DESCRIPTION
**Pull request by sbose78**
Added a block to build image from Dockerfile
https://github.com/redhat-developer/devconsole-operator/blob/master/Dockerfile

Ideally, I would like to have this published somewhere for use both inside the CI test(s) and outside of it.
Any pointers on that?

### CODE REVIEW

**Comment by sbose78** [comment]
Need help with https://github.com/openshift/origin/issues/21627#issuecomment-478873551 .

**Comment by sbose78** [comment]
@bparees I was expecting the multi-stage build to work here. 
```
images: 
- from: os
  to: devconsole-operator
  dockerfile_path: Dockerfile
```

Here's the dockerfile https://github.com/redhat-developer/devconsole-operator/blob/master/Dockerfile
which has a structure like this 

```
FROM centos:7 as build-tools
....
...
..
FROM build-tools as builder
...
....
..
```

I see the following error in the build log which makes me wonder  if the underlying `Build` / `BuildConfig` sees things differently
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/3336/rehearse-3336-pull-ci-redhat-developer-devconsole-operator-master-images/3/build-log.txt

```
Replaced Dockerfile FROM image centos:7

Pulling image build-tools ...
error: build error: failed to pull image: repository docker.io/build-tools not found: does not exist or no pull access
2019/04/02 16:00:17 Ran for 18m53s
error: could not run steps: could not wait for build: the build devconsole-operator failed after 33s with reason PullBuilderImageFailed: Failed pulling builder image.

Pulling image build-tools ...
error: build error: failed to pull image: repository docker.io/build-tools not found: does not exist or no pull access
```

Wondering if this is because of the `Replaced Dockerfile FROM image centos:7..` line removes the reference to `build-tools` .

**Comment by bparees** [comment]
@sbose78 only the last FROM statement in your dockerfile will be replaced by your "from: os" imagestream reference:

https://github.com/redhat-developer/devconsole-operator/blob/e9c4e20a5a6f97e5d41e0df8ce64b35cadf81f07/Dockerfile#L69

So this one is going to be untouched:
https://github.com/redhat-developer/devconsole-operator/blob/e9c4e20a5a6f97e5d41e0df8ce64b35cadf81f07/Dockerfile#L61

That is why your resulting dockerfile still contains a reference to an image named "build-tools" which then cannot be fetched.

You can use "as" references to indicate other FROM references that should be replaced:
https://github.com/openshift/api/blob/master/build/v1/types.go#L437-L443

i'm not sure precisely how you specify "as" references in the ci-operator config yaml syntax.  @stevekuznetsov might be able to point you to an example of its usage.

**Pull request closed without merging**
