### PR TITLE
MSI: Add RHOAI jobs for IPI AWS workflow

### PR DESCRIPTION
**Pull request by chetna14manku**
JIRA Ticket: https://issues.redhat.com/browse/MSINTEROP-362

### CODE REVIEW

**Comment by chetna14manku** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-ipi-aws-rhods-addon-baseline-fips

**Comment by chetna14manku** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-ipi-aws-rhods-addon-baseline-fips

**Comment by chetna14manku** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-ipi-aws-rhods-addon-baseline-fips

**Comment by chetna14manku** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-ipi-aws-rhods-addon-baseline-fips

**Review by rnetser — APPROVED** [review]

**Comment by chetna14manku** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-ipi-aws-rhods-addon-baseline-fips

**Comment by chetna14manku** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-ipi-aws-rhods-addon-baseline-fips

**Comment by chetna14manku** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-ipi-aws-rhods-addon-baseline-fips

**Comment by chetna14manku** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-ipi-aws-rhods-addon-baseline-fips

**Comment by chetna14manku** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-ipi-aws-rhods-addon-baseline-fips

**Comment by chetna14manku** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-ipi-aws-rhods-addon-baseline-fips

**Comment by chetna14manku** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-ipi-aws-rhods-addon-baseline-fips

**Comment by chetna14manku** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-ipi-aws-rhods-addon-baseline-fips

**Comment by chetna14manku** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-ipi-aws-rhods-addon-baseline-fips

**Comment by chetna14manku** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhoai-addon-interop-v4.13-GA-stage-smoke-ipi-aws-rhods-addon-baseline-fips

**Comment by chetna14manku** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhoai-addon-interop-v4.13-GA-stage-smoke-ipi-aws-rhods-addon-baseline-fips

**Comment by chetna14manku** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhoai-addon-interop-v4.13-GA-stage-smoke-ipi-aws-rhods-addon-baseline-fips

**Review by rnetser — APPROVED** [review]

**Pull request merged**
