### PR TITLE
run image registry extended tests against registry repo PRs

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
(was there a reason we weren't running these tests against openshift/image-registry already?)

**Comment by bparees** [comment]
@dmage @legionus bump

**Comment by dmage** [comment]
I think the main reason that none of us can test it locally and is familiar with the syntax. Looks good, especially if it works.

**Comment by bparees** [comment]
> I think the main reason that none of us can test it locally and is familiar with the syntax. 

why can't you test/run it locally like we run any other extended test against a local cluster?  (i haven't looked at specifically what the tests do/require)

the syntax should just be `FOCUS=[registry] test/extended/core.sh`

**Comment by bparees** [comment]
since these tests are working against origin PRs i would expect them to work against image-registry PRs, so i'm merging, but we can revisit if it causes issues next time we have an image-registry PR.

**Comment by dmage** [comment]
@bparees I'm not going to discuss why our CI is far from being perfect. But your statement isn't true.

Most of our extended tests are serial, here the list of the `[registry]` tests:

  * [Feature:ImageQuota][registry][Serial][Suite:openshift/registry/serial]**[local]** Image limit range
  * [Feature:ImageQuota][registry][Serial][Suite:openshift/registry/serial]**[local]** Image resource quota
  * [registry][Serial][Suite:openshift/registry/serial] Image signature workflow
  * [Feature:ImagePrune][registry][Serial][Suite:openshift/registry/serial]**[local]** Image prune
  * [Feature:ImagePrune][registry][Serial][Suite:openshift/registry/serial]**[local]** Image hard prune
  * [Feature:ImageLookup][registry][Conformance] Image policy
  * [Feature:ImageMirror][registry][Slow] Image mirror

But our CI job [skips **[local]** tests](https://github.com/openshift/release/blob/e274d0cc4d64e55bad5ad13c29ec892f4f273efd/ci-operator/templates/cluster-launch-e2e.yaml#L146). I know it only because I spent a lot of time learning how our CI works.

So no, I don't have a way to run it locally. The best result I can achieve is by guessing which parts of .yaml files will be used and reconstructing the shell script, but that's prone to errors.

**Pull request merged**
