### PR TITLE
Bug 1799030: ci-operator/config/openshift/cluster-etcd-operator: fix Dockerfile ref in 4.{4,5,6} .

### PR DESCRIPTION
**Pull request by hexfusion**
We updated master but not 4.4 explicitly.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
@hexfusion I believe you need to make the same changes for [4.5](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/branch-ci-openshift-cluster-etcd-operator-release-4.5-images/25) and [4.6](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/branch-ci-openshift-cluster-etcd-operator-release-4.6-images/11) as well

**Comment by hexfusion** [comment]
prow seems to have lost its mind :)

**Pull request merged**
