### PR TITLE
Add pre-commit job for neutron-operator

### PR DESCRIPTION
**Pull request by gibizer**

### CODE REVIEW

**Comment by gibizer** [comment]
We need https://github.com/openstack-k8s-operators/neutron-operator/pull/133 first to make the pre-commit job green.

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-neutron-operator-master-precommit-check

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-neutron-operator-master-precommit-check

 trying again, previous issue seems related to the CI infra:
[36mINFO[0m[2023-04-06T12:38:29Z] pod pending for more than 30m0s: container "ci-scheduling-dns-wait" has not started in 30m0.008406988s:

**Comment by gibizer** [comment]
Bumped the timeout in https://github.com/openstack-k8s-operators/neutron-operator/pull/134

**Comment by gibizer** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-neutron-operator-master-precommit-check
openstack-k8s-operators/neutron-operator#134 merged

**Comment by gibizer** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-neutron-operator-master-precommit-check

https://github.com/openstack-k8s-operators/neutron-operator/pull/134 merged

**Comment by viroel** [comment]
/pj-rehearse ack

pre-commit job is passing now [1]

[1] https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/38080/rehearse-38080-pull-ci-openstack-k8s-operators-neutron-operator-master-precommit-check/1644014832300593152

**Pull request merged**
