### PR TITLE
external dns: release 1.0 config

### PR DESCRIPTION
**Pull request by alebedev87**
Follow up of https://github.com/openshift/release/pull/34949#issuecomment-1400517054.

### CODE REVIEW

**Comment by candita** [comment]
> The infoblox test passed, the cluster was deprovisioned, it's just the lease which wasn't released correctly:
> 
> ```
>  INFO[2023-01-24T16:30:57Z] Releasing leases for test e2e-azure-ovn-infoblox-operator 
> WARN[2023-01-24T16:30:59Z] Failed to update lease "eastus2--azure4-quota-slice-3"  error=status 502 Bad Gateway, status code 502 updating eastus2--azure4-quota-slice-3 
> ```
> 
> /pj-rehearse ack

@alebedev87 don't you need to get a passing result on the pj-rehearse?  Even though it isn't "required", you still want to merge this with a failed ci/rehearse test?

**Comment by alebedev87** [comment]
/pj-rehearse pull-ci-openshift-external-dns-operator-release-1.0-e2e-azure-ovn-infoblox-operator

**Comment by alebedev87** [comment]
> @alebedev87 don't you need to get a passing result on the pj-rehearse? Even though it isn't "required", you still want to merge this with a failed ci/rehearse test?

The way I understand the idea of the `pj-rehearse` is that the hard dependency on the green tests is lifted. The CI config must be valid but is not forced to have the rehearsal all green. That may be helpful in case the rehearsal cannot be green (dependency on the code, etc.) or when the rehearsal is too nondeterministic (like a lot of NetEdge test we saw recently) or when the failure was surely not related to the config change (like in this PR).

Just wanted to save some resources by not spinning another cluster but anyway I re-ran the failed test - it's all green now.

**Comment by alebedev87** [comment]
`ci/prow/ordered-prow-config` failed due to the build server change. No re-rehearsal is needed.

**Comment by alebedev87** [comment]
Rebase from master.

**Pull request merged**
