### PR TITLE
release: move all 4.7+ jobs to GCP2

### PR DESCRIPTION
**Pull request by petr-muller**
/cc @wking @droslean

### CODE REVIEW

**Comment by petr-muller** [comment]
/hold
I want to see rehearsals here

**Comment by petr-muller** [comment]
Looks like we hardcode project name: 

```
Required 'compute.networks.create' permission for 'projects/openshift-gce-devel-ci/global/networks/ci-op-3dv6rwg9-5bb69' 
```

**Comment by petr-muller** [comment]
Ugh. Looks like these are actualy quite widespread (including the hardcoded "default" regions and zones).

https://github.com/openshift/release/blob/master/ci-operator/step-registry/upi/gcp/nested/pre/upi-gcp-nested-pre-ref.yaml#L21-L22

**Comment by petr-muller** [comment]
1. periodic-ci-openshift-release-master-ci-4.7-upgrade-from-stable-4.6-e2e-gcp-ovn-upgrade: failed to install, [unusual for that job](https://testgrid.k8s.io/redhat-openshift-ocp-release-4.7-informing#periodic-ci-openshift-release-master-ci-4.7-upgrade-from-stable-4.6-e2e-gcp-ovn-upgrade)
```
level=fatal msg="failed to initialize the cluster: Cluster operator authentication is reporting a failure: WellKnownReadyControllerDegraded: kube-apiserver oauth endpoint https://10.0.0.4:6443/.well-known/oauth-authorization-server is not yet served and authentication operator keeps waiting (check kube-apiserver operator, and check that instances roll out successfully, which can take several minutes per instance)
```

2. periodic-ci-openshift-release-master-ci-4.8-upgrade-from-stable-4.7-e2e-gcp-ovn-upgrade: failed to install, [unusual for that job](https://testgrid.k8s.io/redhat-openshift-ocp-release-4.8-informing#periodic-ci-openshift-release-master-ci-4.8-upgrade-from-stable-4.7-e2e-gcp-ovn-upgrade):
```
level=fatal msg=failed to initialize the cluster: Some cluster operators are still updating: authentication, console, image-registry, ingress, kube-storage-version-migrator, monitoring
```

3. periodic-ci-openshift-release-master-ci-4.8-e2e-gcp-compact installed fine, tests failed similarly to the existing job
4. periodic-ci-openshift-release-master-ci-4.8-e2e-gcp-serial installed fine, tests failed similarly to the existing job
5. periodic-ci-openshift-release-master-nightly-4.7-e2e-gcp failed to install, [unusual for that job](https://testgrid.k8s.io/redhat-openshift-ocp-release-4.7-informing#periodic-ci-openshift-release-master-nightly-4.7-e2e-gcp):
```
level=fatal msg=failed to initialize the cluster: Working towards 4.7.0-0.nightly-2021-05-01-081439: 662 of 669 done (98% complete) 
```
6. periodic-ci-openshift-release-master-nightly-4.8-e2e-gcp failed to install, [unusual for that job](https://testgrid.k8s.io/redhat-openshift-ocp-release-4.8-informing#periodic-ci-openshift-release-master-nightly-4.8-e2e-gcp):
```
level=fatal msg=failed to initialize the cluster: Cluster operator storage is not available 
```
7. periodic-ci-openshift-release-master-nightly-4.7-e2e-gcp-fips failed to install, [unusual for that job](https://testgrid.k8s.io/redhat-openshift-ocp-release-4.7-informing#periodic-ci-openshift-release-master-nightly-4.7-e2e-gcp-fips):
```
level=fatal msg=failed to initialize the cluster: Some cluster operators are still updating: authentication, console, image-registry, ingress, kube-storage-version-migrator, monitoring, storage 
```
8. periodic-ci-openshift-release-master-nightly-4.8-e2e-gcp-fips failed to install, [unusual for the job](https://testgrid.k8s.io/redhat-openshift-ocp-release-4.8-informing#periodic-ci-openshift-release-master-nightly-4.8-e2e-gcp-fips):
```
level=fatal msg=failed to initialize the cluster: Some cluster operators are still updating: authentication, console, image-registry, ingress, monitoring 
```
9. periodic-ci-openshift-release-master-nightly-4.7-e2e-gcp-fips-serial  failed to install, [unusual for the job](https://testgrid.k8s.io/redhat-openshift-ocp-release-4.7-informing#periodic-ci-openshift-release-master-nightly-4.7-e2e-gcp-fips-serial):
```
level=fatal msg=failed to initialize the cluster: Some cluster operators are still updating: authentication, console, image-registry, ingress, kube-storage-version-migrator, monitoring 
```
10. periodic-ci-openshift-release-master-nightly-4.8-e2e-gcp-fips-serial failed to install, [unusual for the job](https://testgrid.k8s.io/redhat-openshift-ocp-release-4.8-informing#periodic-ci-openshift-release-master-nightly-4.8-e2e-gcp-fips-serial):
```
level=fatal msg=failed to initialize the cluster: Some cluster operators are still updating: authentication, console, image-registry, ingress, monitoring, storage 
```
11. periodic-ci-openshift-release-master-nightly-4.7-e2e-gcp-libvirt-cert-rotation failed because of hardcoding project IDs, fixed by https://github.com/openshift/release/pull/18262
12. periodic-ci-openshift-release-master-nightly-4.8-e2e-gcp-libvirt-cert-rotation failed because of hardcoding project IDs, fixed by https://github.com/openshift/release/pull/18262
13. periodic-ci-openshift-release-master-nightly-4.7-e2e-gcp-rt  failed to install, [unusual for the job](https://testgrid.k8s.io/redhat-openshift-ocp-release-4.7-informing#periodic-ci-openshift-release-master-nightly-4.7-e2e-gcp-rt):
```

Three jobs installed fine and passed:
periodic-ci-openshift-release-master-ci-4.8-e2e-gcp-compact-serial
periodic-ci-openshift-release-master-ci-4.8-e2e-gcp-compact-upgrade
periodic-ci-openshift-release-master-ci-4.8-e2e-gcp-upgrade

**Comment by petr-muller** [comment]
The amount of failed installations in the rehearsals is definitely suspicious

**Comment by wking** [comment]
[nightly-4.8-e2e-gcp][1]:

```
Operator degraded (CredentialsFailing): 2 of 5 credentials requests are failing to sync.
```

Is probably the provisioning credential missing something from [here][1].

[1]: https://github.com/openshift/cloud-credential-operator/blob/master/pkg/operator/utils/gcp/utils.go#L38-L54

**Comment by petr-muller** [comment]
I would not expect a credential problem to manifest in arbitrary flakes and actually succeed in some cases though?

**Comment by petr-muller** [comment]
```
level=fatal msg=failed to fetch Cluster: failed to fetch dependency of "Cluster": failed to generate asset "Platform Quota Check": error(MissingQuota): iam.googleapis.com/quota/service-account-count is not available in global because the required number of resources (5) is more than remaining quota of 0 
```

OK now we're getting somewhere. IAM was the permissions we were missing previously, right? Looks like that when we were missing that permission, we did not check the quota and tried to do our thing despite, and sometimes failed which explains the "flakiness".

**Comment by petr-muller** [comment]
Service Accounts are capped to 100 which acc to https://docs.openshift.com/container-platform/4.7/installing/installing_gcp/installing-gcp-account.html holds 20 clusters. We are also hitting router limits, capped to 20 ATM.

**Comment by petr-muller** [comment]
/test pj-rehearse

Limits were raised, trying again

**Review by wking — APPROVED** [review]
/lgtm
/hold cancel

**Pull request merged**
