### PR TITLE
Refine keyword position for disabled jobs

### PR DESCRIPTION
**Pull request by liangxia**
Move the keyword `disabled` from test name prefix to test name suffix, so that the jobs sort in a better order.

### CODE REVIEW

**Comment by pruan-rht** [comment]
@liangxia this could possibly break the previously agreed naming convention of having the format of `p<x>-f<y>`.  Just something to consider.

**Comment by liangxia** [comment]
> @liangxia this could possibly break the previously agreed naming convention of having the format of `p<x>-f<y>`. Just something to consider.

p<x> is no longer used/needed, while f<y> is still there. We are following the rules.

**Comment by liangxia** [comment]
Rebase the codes so that the required tests can pass, no code changes.

**Pull request merged**
