### PR TITLE
add job for hive long duration cases on azure

### PR DESCRIPTION
**Pull request by jianping-shu**
https://issues.redhat.com/browse/OCPQE-12681
Add azure profile for Hive long duration tests cases

### CODE REVIEW

**Comment by jianping-shu** [comment]
@lwan-wanglin @huangmingxia Here is azure job similar to aws/gcp one, PTAL

**Comment by lwan-wanglin** [comment]
job `ci/prow/yamllint` failed

**Comment by jianping-shu** [comment]
/assign @liangxia
Here is the azure job similar to the existing aws/gcp ones, pls. review and approve, thanks
The above failed job shall be a flake, the previous successful job run is 
[https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/opens[…]d64-nightly-e2e-azure-ipi-p3-long-duration](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/33593/rehearse-33593-periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-e2e-azure-ipi-p3-long-duration)

**Pull request merged**
