### PR TITLE
add quay omr test on OCP 4.12 in disconnected env

### PR DESCRIPTION
**Pull request by LiZhang19817**
add quay omr test on OCP 4.12 in disconnected

### CODE REVIEW

**Comment by LiZhang19817** [comment]
/pj-rehearse periodic-ci-quay-quay-tests-master-omr-ocp412-quay-omr-tests-omr-ocp412-disconnected

**Comment by LiZhang19817** [comment]
/pj-rehearse periodic-ci-quay-quay-tests-master-omr-ocp412-quay-omr-tests-omr-ocp412-disconnected

**Comment by LiZhang19817** [comment]
/pj-rehearse periodic-ci-quay-quay-tests-master-omr-ocp412-quay-omr-tests-omr-ocp412-disconnected

**Comment by LiZhang19817** [comment]
/pj-rehearse periodic-ci-quay-quay-tests-master-omr-ocp412-quay-omr-tests-omr-ocp412-disconnected

**Comment by LiZhang19817** [comment]
/pj-rehearse periodic-ci-quay-quay-tests-master-omr-ocp412-quay-omr-tests-omr-ocp412-disconnected

**Comment by LiZhang19817** [comment]
/pj-rehearse periodic-ci-quay-quay-tests-master-omr-ocp412-quay-omr-tests-omr-ocp412-disconnected

**Comment by LiZhang19817** [comment]
/pj-rehearse periodic-ci-quay-quay-tests-master-omr-ocp412-quay-omr-tests-omr-ocp412-disconnected

**Comment by LiZhang19817** [comment]
/pj-rehearse periodic-ci-quay-quay-tests-master-omr-ocp412-quay-omr-tests-omr-ocp412-disconnected

**Comment by LiZhang19817** [comment]
/pj-rehearse periodic-ci-quay-quay-tests-master-omr-ocp412-quay-omr-tests-omr-ocp412-disconnected

**Review by KeenonLee — COMMENTED** [review]
/lgtm

**Pull request merged**
