### PR TITLE
OKD: Exclude more images from mirroring in 4.12+

### PR DESCRIPTION
**Pull request by LorbusChris**
This change excludes the following images from mirroring:
- contour
- contour-operator
- external-dns
- external-dns-operator
- local-storage-static-provisioner

These images are currently present in OCP CI release payloads, however they are not present (anymore) in OCP stable release payloads. Ensure we can remove them from OKD too without them being re-added later by the mirroring process.

### CODE REVIEW

**Comment by LorbusChris** [comment]
/cc @vrutkovs 
fyi

**Review by vrutkovs — APPROVED** [review]

**Pull request merged**
