### PR TITLE
Expand JBoss FUSE to support FIPS

### PR DESCRIPTION
**Pull request by madunn**
Expand the JBoss FUSE scenario to support FIPS on OCP 4.17

### CODE REVIEW

**Comment by madunn** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.17-lp-interop-jboss-fuse-interop-aws-fips

**Comment by madunn** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.17-lp-interop-jboss-fuse-interop-aws-fips

**Comment by smongiar** [comment]
It needs  this [PR](https://github.com/openshift/release/pull/55966) to be merged first, for better results evaluation

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.17-lp-interop-jboss-fuse-interop-aws-fips

**Comment by madunn** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.17-lp-interop-jboss-fuse-interop-aws-fips

**Comment by smongiar** [comment]
@madunn I'm noticing it's taking the 7.12-openJDK 1.8 TAG looking at deployment [log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/55203/rehearse-55203-periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.17-lp-interop-jboss-fuse-interop-aws-fips/1838619484621901824/artifacts/jboss-fuse-interop-aws-fips/jboss-fuse-deploy-resources/build-log.txt) ... That's weird, it should take the master one from the latest tag: https://quay.io/repository/rh_integration/xpaas-qe?tab=tags

**Comment by smongiar** [comment]
We can modify:

1. This [section](https://github.com/openshift/release/blob/master/ci-operator/step-registry/jboss-fuse/deploy-resources/jboss-fuse-deploy-resources-commands.sh#L382) with `oc import-image xpaas-qe:latest --from=quay.io/rh_integration/xpaas-qe:${FUSE_RELEASE}-openjdk17 -n jboss-fuse-interop --confirm`

2. This [section](https://github.com/openshift/release/blob/c733eede6fead47cc5fc0e554c4894a5d13cefd8/ci-operator/step-registry/jboss-fuse/deploy-resources/jboss-fuse-deploy-resources-ref.yaml#L21) with `default: master`

3. Then the _README.md_ [part](https://github.com/openshift/release/blob/c733eede6fead47cc5fc0e554c4894a5d13cefd8/ci-operator/step-registry/jboss-fuse/deploy-resources/README.md?plain=1#L34) replacing `7.12.x` with `master`

**Comment by madunn** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.17-lp-interop-jboss-fuse-interop-aws-fips

**Comment by madunn** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.17-lp-interop-jboss-fuse-interop-aws-fips

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.17-lp-interop-jboss-fuse-interop-aws-fips

**Comment by madunn** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.17-lp-interop-jboss-fuse-interop-aws-fips

**Comment by madunn** [comment]
/pj-rehearse periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.17-lp-interop-jboss-fuse-interop-aws-fips

**Pull request closed without merging**
