### PR TITLE
Use techpreview feature set for CCM tests

### PR DESCRIPTION
**Pull request by Fedosin**
Now we use CustomNoUpgrade, which causes some issues on CI.

```txt
fail [github.com/onsi/ginkgo@v4.7.0-origin.0+incompatible/internal/leafnodes/runner.go:113]: Feb  1 07:02:47.811: Unexpected alerts fired or pending after the test run:  alert TechPreviewNoUpgrade fired for 4158 seconds with labels: {container="kube-apiserver-operator", endpoint="https", instance="10.129.0.20:8443", job="metrics", name="CustomNoUpgrade", namespace="openshift-kube-apiserver-operator", pod="kube-apiserver-operator-7d9ff8859b-qtx72", service="metrics", severity="warning"}
```

To prevent this we should use TechPreviewNoUpgrade feature set, as it has all necessary feature gates.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
This is now duplicating the existing `openshift-e2e-<platform>-techpreview` workflows, we should just use that instead wherever we are using the current CCM steps. Then we can delete a bunch of the config for the CCM jobs

**Comment by JoelSpeed** [comment]
We can go one step further than this and replace https://github.com/openshift/release/blob/676d89a409e6e9965135bed13208dbf803b964b5/ci-operator/config/openshift/cloud-provider-aws/openshift-cloud-provider-aws-master.yaml#L55-L59

With 
```
 - as: e2e-aws-techpreview 
   optional: true 
   steps: 
     cluster_profile: aws 
     workflow: openshift-e2e-aws-techpreview 
```

And then we can get rid of `openshift-e2e-aws-ccm-install` right? Could we do this across all of the different builds that already have techpreview variants?

**Comment by Fedosin** [comment]
@JoelSpeed I kept it because `openshift-e2e-aws-techpreview` workflow doesn't contain `storage-conf-csi-aws-ebs`, like it's done here: https://github.com/openshift/release/blob/master/ci-operator/step-registry/openshift/e2e/aws/ccm/install/openshift-e2e-aws-ccm-install-workflow.yaml#L8

I don't know if we really need it, as it just starts the csi test suite. If you think it is reasonable, I'll remove `storage-conf-csi-aws-ebs` from all CCM test workflows.

**Comment by JoelSpeed** [comment]
> I don't know if we really need it, as it just starts the csi test suite. If you think it is reasonable, I'll remove storage-conf-csi-aws-ebs from all CCM test workflows.

That seems like a reasonable thing to have for testing the CCMs, in that case, I'm happy to leave as it is for now then

/lgtm

**Pull request merged**
