### PR TITLE
Adding time scenarios

### PR DESCRIPTION
**Pull request by shahsahil264**
@paigerube14 @chaitanyaenr

### CODE REVIEW

**Comment by shahsahil264** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-krkn-hub-tests-413

**Comment by chaitanyaenr** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-krkn-hub-tests-413

**Comment by shahsahil264** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-krkn-hub-tests-413

**Comment by shahsahil264** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-krkn-hub-tests-413

**Comment by shahsahil264** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-krkn-hub-tests-413

**Comment by shahsahil264** [comment]
/pj-rehearse periodic-ci-redhat-chaos-krkn-hub-main-krkn-hub-tests-413

**Comment by paigerube14** [comment]
Things here look good to me! I see the telemetry password isn't working properly. Not sure if that is a this test case problem or issue setting in the vault

**Comment by shahsahil264** [comment]
> Things here look good to me! I see the telemetry password isn't working properly. Not sure if that is a this test case problem or issue setting in the vault

Yes, I had a chat with @chaitanyaenr , he fixed it!

**Pull request merged**
