### PR TITLE
Add sriov-network-operator image

### PR DESCRIPTION
**Pull request by pliurh**

### CODE REVIEW

**Comment by smarterclayton** [comment]
What does this operator do?

Will it be part of the payload?  If so, have you already tested whether it successfully upgrades?

Why is it a separate binary and not part of network operator?

**Comment by pliurh** [comment]
@smarterclayton, here are the answers to your question:

1. This operator is responsible for a) configuring SR-IOV devices on worker nodes, b) deploy sriov cni plugin and sriov device plugin, c) manage the config of sriov cni plugin and sriov device plugin.
2. This operator is an optional operator, and it will be delivered as a Redhat Operator through OperatorHub. User can chose to install it as a day-2 operation.
3. Since SR-IOV is not a feature which is requested by all Openshift users, so we decided to deliver it as a separate operator, rather than as a feature of cluster-network-operator in 4.2.

**Comment by smarterclayton** [comment]
Ok

**Pull request merged**
