### PR TITLE
ocm: cluster-curator-controller, place sonarcloud in precommits and update post commit make command

### PR DESCRIPTION
**Pull request by jnpacker**
Signed off by @jnpacker 

* Add the pre-merge sonar check
* Change the post merge sonar call to no longer include post-prow

### CODE REVIEW

**Comment by jnpacker** [comment]
/cc @hanqiuzh @chenz4027 

Does this look like what you saw Maggie?

**Comment by jnpacker** [comment]
My understanding is the sonar precommit job will fail in testing.

**Comment by hanqiuzh** [comment]
same error every one is hitting, but not sure why the other several tests are failing, do you need to rerun `make update` ?

**Comment by chenz4027** [comment]
no @jnpacker , sonar should fail, but others are caused by PROW issues

**Pull request merged**
