### PR TITLE
WIP: Make CSPI-QE/amq-streams onboard with dummy github repo.

### PR DESCRIPTION
**Pull request by myakove**

### CODE REVIEW

**Comment by myakove** [comment]
/pj-rehearse periodic-ci-CSPI-QE-amq-streams-main-smoke-tests

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-amq-streams-main-smoke-tests

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-amq-streams-main-smoke-tests

**Comment by myakove** [comment]
/pj-rehearse periodic-ci-CSPI-QE-amq-streams-main-smoke-tests

**Comment by myakove** [comment]
/pj-rehearse periodic-ci-CSPI-QE-amq-streams-main-smoke-tests

**Comment by myakove** [comment]
/pj-rehearse periodic-ci-CSPI-QE-amq-streams-main-smoke-tests

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-amq-streams-main-smoke-tests

**Pull request closed without merging**
