### PR TITLE
Stackrox Bump apollo-ci image to 0.3.56

### PR DESCRIPTION
**Pull request by janisz**
- https://github.com/stackrox/stackrox/pull/4658
- https://github.com/openshift/release/pull/36140

### CODE REVIEW

**Review by porridge — APPROVED** [review]
/lgtm

**Comment by gavin-stackrox** [comment]
@janisz You will need to import the image in a separate PR. Wait a few hours. Then try an image bump.

**Comment by janisz** [comment]
https://github.com/stackrox/stackrox/pull/4776

**Comment by janisz** [comment]
https://github.com/stackrox/stackrox/pull/4769

**Comment by RTann** [comment]
@janisz let's close this in favor of https://github.com/openshift/release/pull/36193

**Pull request closed without merging**
