### PR TITLE
Remove 4.9 bits

### PR DESCRIPTION
**Pull request by mkumatag**
This project never shipped into 4.9 release, hence the branch needs to be removed for that we need to remove this config file as well.

xref: https://issues.redhat.com/browse/DPTP-2610

/cc @petr-muller

### CODE REVIEW

**Comment by petr-muller** [comment]
So one implication of this change is that we already built images from that branch and published them on Quay under 4.9 (not official ones). Hence, this PR needs @smarterclayton 's approval

**Comment by mkumatag** [comment]
any help is appreciated
/assign @smarterclayton

**Pull request closed without merging**
