### PR TITLE
templates/openshift: grab bootstrap log on failure

### PR DESCRIPTION
**Pull request by sttts**
Python rewrite of https://github.com/openshift/release/pull/2581

### CODE REVIEW

**Comment by crawford** [comment]
Oh nice! I'll give this a run locally and then LGTM if it looks good.

**Comment by stevekuznetsov** [comment]
As I say in all cases where I see this -- where else can this logic live? Python in Bash in template YAML is not maintainable.

**Comment by sttts** [comment]
> As I say in all cases where I see this -- where else can this logic live? Python in Bash in template YAML is not maintainable.

Medium term this should move directly into the installer itself. So this is more an ad-hoc tool to get us visibility into the bootstrapping phase now if things go badly wrong in CI. We are blind, so this would help a lot in diagnosis when testgrid is completely red again.

**Comment by crawford** [comment]
Moving to https://github.com/openshift/release/pull/2633 (I couldn't update your branch, @sttts). That includes a few changes on top of your work.

**Pull request closed without merging**
