### PR TITLE
[WIP]Move pull-ci-openshift-installer-release-4.5-e2e-vsphere-upi to vsphere

### PR DESCRIPTION
**Pull request by hongkailiu**
/cc @alvaroaleman @stevekuznetsov

### CODE REVIEW

**Comment by alvaroaleman** [comment]
We lack permissions in the build cluster: https://github.com/openshift/release/pull/10399

**Comment by alvaroaleman** [comment]
Needs https://github.com/openshift/release/pull/10415
Also opened https://issues.redhat.com/browse/DPTP-1376 because this should run into the 15 min pod_pending_timeout rather than the 4h job timeout

**Comment by hongkailiu** [comment]
```
oc --kubeconfig sa.config-updater.vsphere.config get pod -n ocp
NAME                                  READY   STATUS    RESTARTS   AGE
base-4-1-84c6cb97b9-flgvn             1/1     Running   0          5m23s
base-4-1-84c6cb97b9-hjjg5             1/1     Running   0          8m56s
base-4-2-fbd9d966-bhh7j               1/1     Running   0          2m51s
base-4-2-fbd9d966-hjg2j               1/1     Running   0          3m44s
base-4-2-s390x-84d9c4f7b6-czkmh       1/1     Running   0          3m43s
base-4-2-s390x-84d9c4f7b6-z256q       1/1     Running   0          9m21s
base-4-3-57cd79d747-94jgg             1/1     Running   0          5m12s
base-4-3-57cd79d747-prlz8             1/1     Running   0          5m23s
base-4-3-ppc64le-599b9b7776-7fjh7     1/1     Running   0          2m52s
base-4-3-ppc64le-599b9b7776-rtfsx     1/1     Running   0          2m40s
base-4-3-rhel8-8ccc565c9-j29js        1/1     Running   0          5m23s
base-4-3-rhel8-8ccc565c9-k24r6        1/1     Running   0          3m44s
base-4-3-s390x-6789fb975-4ztkv        1/1     Running   0          8m4s
base-4-3-s390x-6789fb975-7j7ss        1/1     Running   0          9m21s
base-4-4-59ff488f84-hvw4m             1/1     Running   0          3m26s
base-4-4-59ff488f84-spbgp             1/1     Running   0          3m44s
base-4-4-ppc64le-774bfb6c47-hxp2n     1/1     Running   0          5m12s
base-4-4-ppc64le-774bfb6c47-mhtkf     1/1     Running   0          5m22s
base-4-4-rhel8-69dc78f98d-b59bb       1/1     Running   1          2m40s
base-4-4-rhel8-69dc78f98d-mlqd8       1/1     Running   0          2m51s
base-4-4-s390x-74596b87d8-669qg       1/1     Running   0          9m21s
base-4-4-s390x-74596b87d8-kznxl       1/1     Running   0          2m52s
base-4-5-7c56bc4b9c-gtbtc             1/1     Running   0          5m23s
base-4-5-7c56bc4b9c-zlqxm             1/1     Running   0          5m12s
base-4-5-ppc64le-6d8c576fc8-dn74g     1/1     Running   0          3m44s
base-4-5-ppc64le-6d8c576fc8-vb6vh     1/1     Running   1          3m26s
base-4-5-rhel8-8d587f85-fdr98         1/1     Running   0          8m5s
base-4-5-rhel8-8d587f85-x5nfv         1/1     Running   0          7m54s
base-4-5-s390x-887f8668f-vpmws        1/1     Running   0          2m40s
base-4-5-s390x-887f8668f-wnqh5        1/1     Running   0          2m52s
base-4-6-6bf4899ff4-68mf7             1/1     Running   0          2m40s
base-4-6-6bf4899ff4-7dhhw             1/1     Running   0          2m51s
base-4-6-ppc64le-5cc66df7d9-ps4xn     1/1     Running   0          3m44s
base-4-6-ppc64le-5cc66df7d9-wbhfv     1/1     Running   0          3m25s
base-4-6-rhel8-7bcb5b8f7d-b5rch       1/1     Running   0          2m51s
base-4-6-rhel8-7bcb5b8f7d-t9zsv       1/1     Running   0          8m5s
base-4-6-s390x-6759756786-886ws       1/1     Running   1          2m40s
base-4-6-s390x-6759756786-dwsnb       1/1     Running   0          2m52s
base-4-7-5d5f588bbc-cp7hg             1/1     Running   0          7m53s
base-4-7-5d5f588bbc-m6ldt             1/1     Running   0          8m4s
base-4-7-ppc64le-7f54d8d4fb-49pxt     1/1     Running   0          3m44s
base-4-7-ppc64le-7f54d8d4fb-r4wkg     1/1     Running   0          3m25s
base-4-7-rhel8-65b478b49f-6rjgf       1/1     Running   0          9m21s
base-4-7-rhel8-65b478b49f-npr7f       1/1     Running   0          5m23s
base-4-7-s390x-69b4866cf5-4rrlp       1/1     Running   0          2m40s
base-4-7-s390x-69b4866cf5-mrzfj       1/1     Running   0          2m51s
base-openstack-4-2-b66bd6cbf-8q524    1/1     Running   0          2m40s
base-openstack-4-2-b66bd6cbf-v5hmj    1/1     Running   0          2m51s
base-openstack-4-3-f8c96bfd8-2l2gn    1/1     Running   0          2m52s
base-openstack-4-3-f8c96bfd8-6n8vj    1/1     Running   0          3m44s
base-openstack-4-4-6ffdb965cf-srcp2   1/1     Running   0          3m44s
base-openstack-4-4-6ffdb965cf-tftvq   1/1     Running   0          8m5s
base-openstack-4-5-fbf5d7958-ds6jx    1/1     Running   0          5m23s
base-openstack-4-5-fbf5d7958-mpb7m    1/1     Running   0          5m12s
base-openstack-4-6-8ff7d8897-jfnf5    1/1     Running   0          8m3s
base-openstack-4-6-8ff7d8897-s5q78    1/1     Running   0          9m21s
base-openstack-4-7-566dc99b56-4w5cp   1/1     Running   0          5m23s
base-openstack-4-7-566dc99b56-jqcgm   1/1     Running   0          2m51s
openstack-beta-4-3-86f7f44fcc-7ng75   1/1     Running   0          8m3s
openstack-beta-4-3-86f7f44fcc-lx7mm   1/1     Running   0          7m53s
openstack-beta-4-4-79df9bdf64-8ft5z   1/1     Running   0          2m40s
openstack-beta-4-4-79df9bdf64-8r5z5   1/1     Running   0          2m51s
openstack-beta-4-5-c46b59f55-blxsg    1/1     Running   0          3m26s
openstack-beta-4-5-c46b59f55-sk5j9    1/1     Running   0          3m44s
openstack-beta-4-6-d96f59fd6-clcg2    1/1     Running   0          5m22s
openstack-beta-4-6-d96f59fd6-snhkn    1/1     Running   0          5m12s
openstack-beta-4-7-5777886fc7-b5dh4   1/1     Running   0          9m21s
openstack-beta-4-7-5777886fc7-bq89c   1/1     Running   0          3m44s
```

/test pj-rehearse

**Pull request closed without merging**
