### PR TITLE
BUILD-278: step-registry: add a step which configures nodes to use cgroupsv2

### PR DESCRIPTION
**Pull request by vrutkovs**
Split openshift/builder config from https://github.com/openshift/release/pull/19115

### CODE REVIEW

**Comment by gabemontero** [comment]
/retitle BUILD-278: step-registry: add a step which configures nodes to use cgroupsv2

**Comment by gabemontero** [comment]
so to be clear @vrutkovs @adambkaplan , we expect the rehearsal job to fail since https://github.com/openshift/builder/pull/252 has not merged.

we just want this to fail "in the right way"

i.e. the right test suite is launched, and when we look at the failures, we see that the builder image chose to go down the cgroupv2 path, but since there is no `memory.max` file, it complains

**Comment by gabemontero** [comment]
the 4.9 failure is what we were expecting:  from one of the testcases:  `error: failed to retrieve cgroup limits: cannot determine ...: open /sys/fs/cgroup/memory.max: no such file or directory`

same with master

so "failing as expected"

/lgtm

**Review by adambkaplan — APPROVED** [review]
/approve

**Comment by gabemontero** [comment]
> /retest-required
> 
> Please review the [full test history](https://prow.ci.openshift.org/pr-history/?org=openshift&repo=release&pr=20125) for this PR and help us cut down flakes.

that's new to me @vrutkovs @adambkaplan :-) .... I wonder if the bot will let us merge this now if the rehearsals are still failing ... stayed tuned

**Pull request merged**
