### PR TITLE
MULTIARCH-4696: move back to s922 in wdc06

### PR DESCRIPTION
**Pull request by prb112**
[MULTIARCH-4696](https://issues.redhat.com//browse/MULTIARCH-4696): move back to s922 in wdc06

### CODE REVIEW

**Comment by prb112** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.15-ocp-e2e-powervs-ovn-multi-ppc64le

**Comment by prb112** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.15-ocp-e2e-powervs-ovn-multi-ppc64le

**Review by pkenchap — APPROVED** [review]
/lgtm

**Pull request merged**
