### PR TITLE
WIP: cspi - add amq-streams

### PR DESCRIPTION
**Pull request by rnetser**

### CODE REVIEW

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-layered-products-amq-streams-master-smoke-tests

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-layered-products-amq-streams-master-smoke-tests

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-cspi-amq-streams-master-smoke-tests --ignore

**Comment by myakove** [comment]
/pj-rehearse periodic-ci-CSPI-QE-amq-streams-master-smoke-tests

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-amq-streams-master-smoke-tests

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-amq-streams-master-smoke-tests

**Comment by myakove** [comment]
/pj-rehearse periodic-ci-CSPI-QE-amq-streams-master-smoke-tests

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-amq-streams-master-smoke-tests

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-amq-streams-master-smoke-tests

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-amq-streams-main-smoke-tests

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-amq-streams-main-smoke-tests

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-amq-streams-main-smoke-tests

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-amq-streams-main-smoke-tests

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-amq-streams-main-amq-streams-smoke-tests

**Comment by rnetser** [comment]
Won't pursue this path

**Pull request closed without merging**
