### PR TITLE
Hive: Remove OCM 2.5 tests

### PR DESCRIPTION
**Pull request by 2uasimojo**
OCM 2.5 is [EOL](https://access.redhat.com/support/policy/updates/advanced-cluster-management#lifecycle-dates)

### CODE REVIEW

**Comment by suhanime** [comment]
Shouldn't we remove the relevant [jobs](https://github.com/openshift/release/tree/master/ci-operator/jobs/openshift/hive) as well?

**Comment by 2uasimojo** [comment]
yah, bot agrees with you, for got to `make update`, incoming...

**Review by hongkailiu — COMMENTED** [review]
/approve

**Pull request merged**
