### PR TITLE
ROX-12481: Let operator build use mirrored golang 1.17.12.

### PR DESCRIPTION
**Pull request by porridge**
~~This is waiting for https://github.com/openshift/release/pull/31790 to merge.~~
/cc @gavin-stackrox

### CODE REVIEW

**Comment by porridge** [comment]
:hankey: [this](https://github.com/openshift/release/pull/31790/files) does not even work, looks like there was a step I missed - copy `docker.io/library/golang:X` to `quay.io/stackrox-io/ci:golang-X` right @gavin-stackrox ?
Perhaps we should just do it the way @misberner [suggested](https://srox.slack.com/archives/CELUQKESC/p1661843772545939?thread_ts=1661774422.895409&cid=CELUQKESC) instead..

**Comment by gavin-stackrox** [comment]
I pushed quay.io/stackrox-io/ci:golang-1.17.12, so it should work in 1 hour when that gets mirrored.

I agree that it would be simpler to use `rox-ci-image:stackrox-build` as the `builder` image to follow the same golang updates. That is already mirrored. But the exact syntax for getting that to work with OSCI escapes me. And also how to make it work for local dev builds and CI builds.

**Comment by porridge** [comment]
@gavin-stackrox how do I check whether https://github.com/openshift/release/pull/32063 was processed, without triggering these jobs? I don't see a relevant job under https://prow.ci.openshift.org/?job=*mirroring* ...

**Comment by porridge** [comment]
I *guess* this means the image is still not mirrored? (Even though almost 2 hours passed)...
```
  * could not resolve inputs: could not determine inputs for step [input:golang-1.17.12]: could not resolve base image from stackrox/golang:1.17.12: imagestreamtags.image.openshift.io "golang:1.17.12" not found 
```

**Comment by gavin-stackrox** [comment]
This is the job: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-image-mirroring-supplemental-ci-images/1567543399425249280 and I see it mirroring.
I have seen delays getting to the build server registries. Lets try a retest.
/test pj-rehearse-max

**Comment by porridge** [comment]
Looks like it worked this time, and the failing jobs are unrelated. Can you `/lgtm` this please @gavin-stackrox ?

**Pull request merged**
