### PR TITLE
kubevirt: ssp: Remove master

### PR DESCRIPTION
**Pull request by opokornyy**
This PR removes master from CI.

### CODE REVIEW

**Comment by opokornyy** [comment]
/hold

Make sure that all PRs against master are merged

**Comment by lyarwood** [comment]
> /hold
> 
> Make sure that there are no more PRs on master branch

/approve

https://github.com/kubevirt/ssp-operator/pulls?q=is%3Apr+is%3Aopen+base%3Amaster+

^ Is empty, the only other change I'd like to see land on `master` now is a `git rm -rf` and some documentation stating clearly that the branch is dead and development has moved to main.

**Pull request merged**
