### PR TITLE
Bug 1897737: Censor UserData in the openshift-install logfile

### PR DESCRIPTION
**Pull request by pierreprinetti**
A follow-up to https://github.com/openshift/release/pull/13646

### CODE REVIEW

**Review by Fedosin — COMMENTED** [review]
/lgtm
/hold
/retest

Let's wait for the tests

**Comment by pierreprinetti** [comment]
Tests now look green for most platforms
/hold cancel

**Comment by wking** [comment]
[One e2e-openstack rehearsal][1] using the template:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/14489/rehearse-14489-pull-ci-openshift-cluster-api-provider-openstack-master-e2e-openstack/1341432698572378112/artifacts/e2e-openstack/installer/.openshift_install.log | grep 'password: \|X-Auth-Token\|UserData'
time="2020-12-22T17:33:13Z" level=debug msg="      - .user_data: planned value cty.StringVal(\"6d3f2ea39c078a5523c15ad0ed9bed5bfb3e352c\") does not match config value cty.StringVal(\"{\\\"ignition\\\":{\\\"config\\\":{\\\"merge\\\":[{\\\"httpHeaders\\\":[{\\\"name\\\":\\\"X-Auth-Token REDACTED
time="2020-12-22T17:34:05Z" level=debug msg="      - .user_data: planned value cty.StringVal(\"6d3f2ea39c078a5523c15ad0ed9bed5bfb3e352c\") does not match config value cty.StringVal(\"{\\\"ignition\\\":{\\\"config\\\":{\\\"merge\\\":[{\\\"httpHeaders\\\":[{\\\"name\\\":\\\"X-Auth-Token REDACTED
time="2020-12-22T17:34:06Z" level=debug msg="2020-12-22T17:34:06.314Z [DEBUG] plugin.terraform-provider-openstack: 2020/12/22 17:34:06 [DEBUG] Create Options: &servers.CreateOpts{Name:\"cldxvmwb-c2dcd-7v2w4-bootstrap\", ImageRef:\"22b8c33d-519a-43ce-8825-a89c9a24c125\", FlavorRef:\"6a23f4ef-c643-4cad-8d7e-14268e313c7f\", SecurityGroups:[]string{}, UserData: REDACTED, Tags:[]string{\"openshiftClusterID=cldxvmwb-c2dcd-7v2w4\"}}"
time="2020-12-22T18:07:52Z" level=info msg="Login to the console with user: \"kubeadmin\", and password: REDACTED
```

Seems fine to me.  [One e2e-openstack-ipi rehearsal][2] using multi-step:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/14489/rehearse-14489-pull-ci-openshift-installer-master-e2e-openstack-ipi/1341432692620660736/artifacts/e2e-openstack-ipi/ipi-install-install/.openshift_install.log | grep 'password: \|X-Auth-Token\|UserData'
time="2020-12-22T17:42:00Z" level=debug msg="      - .user_data: planned value cty.StringVal(\"42c9f877735ae7a1f57ea25e53dab042f0d1aee6\") does not match config value cty.StringVal(\"{\\\"ignition\\\":{\\\"config\\\":{\\\"merge\\\":[{\\\"httpHeaders\\\":[{\\\"name\\\":\\\"X-Auth-Token REDACTED
time="2020-12-22T17:42:42Z" level=debug msg="      - .user_data: planned value cty.StringVal(\"42c9f877735ae7a1f57ea25e53dab042f0d1aee6\") does not match config value cty.StringVal(\"{\\\"ignition\\\":{\\\"config\\\":{\\\"merge\\\":[{\\\"httpHeaders\\\":[{\\\"name\\\":\\\"X-Auth-Token REDACTED
time="2020-12-22T17:42:43Z" level=debug msg="2020-12-22T17:42:43.025Z [DEBUG] plugin.terraform-provider-openstack: 2020/12/22 17:42:43 [DEBUG] Create Options: &servers.CreateOpts{Name:\"lllcscrt-5ee9d-btmgx-bootstrap\", ImageRef:\"9bde77c1-9c75-4eab-bb7c-e11796c1ce9d\", FlavorRef:\"a895e676-4fef-4941-b8a6-c72b26c0c2fd\", SecurityGroups:[]string{}, UserData: REDACTED, Tags:[]string{\"openshiftClusterID=lllcscrt-5ee9d-btmgx\"}}"
```

Looks fine too.

/lgtm

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/14489/rehearse-14489-pull-ci-openshift-cluster-api-provider-openstack-master-e2e-openstack/1341432698572378112
[2]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/14489/rehearse-14489-pull-ci-openshift-installer-master-e2e-openstack-ipi/1341432692620660736

**Pull request merged**
