### PR TITLE
OCP Logging: updated the OCP version for vector 0.21-rh to test against to 4.12

### PR DESCRIPTION
**Pull request by syedriko**
OCP Logging: updated the OCP version for vector 0.21-rh to test against to 4.12

### CODE REVIEW

**Comment by syedriko** [comment]
/pj-rehearse pull-ci-ViaQ-vector-v0.21-rh-cluster-logging-operator-e2e-5-6

**Review by jcantrill — COMMENTED** [review]
/lgtm
/pj-rehearse ack

**Comment by syedriko** [comment]
@jcantrill it's /pj-rehearsal ack

**Comment by syedriko** [comment]
@jcantrill "/pj-rehearse ack" didn't have an effect?

**Pull request merged**
