### PR TITLE
MSI: Remove trigger job

### PR DESCRIPTION
**Pull request by rnetser**

### CODE REVIEW

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-trigger

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-trigger

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-trigger

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-cluster-install-uninstall-multi-cluster-install-uninstall-trigger

**Review by omrim12 — APPROVED** [review]

**Review by omrirh — APPROVED** [review]

**Pull request merged**
