### PR TITLE
Publish machine-os-downloader to quay.io for 4.4

### PR DESCRIPTION
**Pull request by elfosardo**
Correcting name of image to be published instead of rhcos-downloader.

### CODE REVIEW

**Comment by elfosardo** [comment]
@smarterclayton  when you have a minute, could you please double-check this? Thanks!

**Comment by wking** [comment]
This should bump [4.2 as well][1] for [rhbz#1784505][2], no?

[1]: https://github.com/openshift/release/blob/33ba05130123f10bd20daccfec45dd7de2107280/core-services/image-mirroring/openshift/mapping_origin_4_2#L96
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1784505

**Comment by wking** [comment]
[Never mind about 4.2][1], we should leave that alone.

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1784505#c1

**Pull request merged**
