### PR TITLE
fix INTEROP-7408

### PR DESCRIPTION
**Pull request by amp-rh**
See [INTEROP-7408](https://issues.redhat.com/browse/INTEROP-7408).

update quay ocp 4.17 cluster profile from `aws-qe` to `aws-cspi-qe`.

### CODE REVIEW

**Comment by amp-rh** [comment]
/pj-rehearse periodic-ci-quay-quay-tests-master-ocp-417-quay-quay-e2e-tests-quay312-ocp417-lp-interop

**Comment by amp-rh** [comment]
/pj-rehearse periodic-ci-quay-quay-tests-master-ocp-417-quay-quay-e2e-tests-quay312-ocp417-lp-interop

**Comment by LiZhang19817** [comment]
@amp-rh Pls help me understand why need to change **cluster_profile to aws-cspi-qe.** for some Quay testing CI jobs?

**Pull request merged**
