### PR TITLE
Modifying the cluster subnet to enable new HAproxy config for CI

### PR DESCRIPTION
**Pull request by deepsm007**
Signed off: Deep Mistry

cc @jaypoulz

### CODE REVIEW

**Comment by deepsm007** [comment]
https://github.com/openshift/release/pull/16135

**Review by jaypoulz — COMMENTED** [review]
The follow up patch is ideal for fixing this for good going forward, but this patch will unblock upgrade testing on P/Z for the time being until we can determine how far we can back port the libvirt dnsmasq injection fix.

**Review by jaypoulz — APPROVED** [review]

**Pull request merged**
