### PR TITLE
CNV nightly bundle tests

### PR DESCRIPTION
**Pull request by danielBelenky**
Signed-off-by: Daniel Belenky <dbelenky@redhat.com>

### CODE REVIEW

**Comment by tiraboschi** [comment]
/override ci/rehearse/periodic-ci-kubevirt-hyperconverged-cluster-operator-release-4.5-hco-e2e-nightly-bundle-release-4-5-azure4

**Comment by danielBelenky** [comment]
/override ci/rehearse/periodic-ci-kubevirt-hyperconverged-cluster-operator-release-4.5-hco-e2e-nightly-bundle-release-4-5-azure4

**Pull request merged**
