### PR TITLE
trt-863: remove install cmd cluster-data gathering

### PR DESCRIPTION
**Pull request by neisw**
Functionality has moved to origin, removing previous cluster-data collection commands.

### CODE REVIEW

**Comment by neisw** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-ovn-remote-libvirt-s390x

**Comment by neisw** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-ovn-ppc64le-powervs

**Comment by neisw** [comment]
/pj-rehearse periodic-ci-openshift-release-master-ci-4.14-e2e-aws-ovn

**Comment by neisw** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-ovn-ppc64le-powervs

**Comment by deepsm007** [comment]
> /pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-ovn-ppc64le-powervs

We can skip this rehearsal

**Pull request merged**
