### PR TITLE
Add z-stream config for odo

### PR DESCRIPTION
**Pull request by smpsgill**

### CODE REVIEW

**Review by calebevans — APPROVED** [review]
/lgtm

**Comment by Simranpal** [comment]
/pj-rehearse periodic-ci-redhat-developer-odo-main-odo-ocp4.15-lp-interop-odo-scenario-ibmcloud

**Comment by rm3l** [comment]
/pj-rehearse periodic-ci-redhat-developer-odo-main-odo-ocp4.15-lp-interop-odo-scenario-ibmcloud

**Comment by Simranpal** [comment]
/pj-rehearse periodic-ci-redhat-developer-odo-main-odo-ocp4.15-lp-interop-odo-scenario-ibmcloud

**Pull request merged**
