### PR TITLE
Drop all rollback test

### PR DESCRIPTION
**Pull request by shellyyang1989**
Dropping rollback test as we won't support rollback at any version.

### CODE REVIEW

**Comment by evakhoni** [comment]
/lgtm
/hold
let's wait for https://github.com/openshift/oc/pull/1806

**Comment by evakhoni** [comment]
fyi I just opened https://github.com/openshift/release/pull/53845 which covers the e2e automation ticket revert part, while this one covers CI implementation https://issues.redhat.com/browse/OTA-1071
looks like this one needs a rebase, @shellyyang1989 if needed, feel free to add me as collaborator so I can take care of that

**Comment by shellyyang1989** [comment]
> fyi I just opened #53845 which covers the e2e automation ticket revert part, while this one covers CI implementation https://issues.redhat.com/browse/OTA-1071 looks like this one needs a rebase, @shellyyang1989 if needed, feel free to add me as collaborator so I can take care of that

Thanks Evgeni! How could I add collaborator?

**Comment by evakhoni** [comment]
> Thanks Evgeni! How could I add collaborator?

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository#inviting-a-collaborator-to-a-personal-repository
/meow

**Comment by evakhoni** [comment]
/lgtm  
@bandrade please approve if LGTY, trying to make this one ready so we can merge by unholding the moment https://github.com/openshift/oc/pull/1806 is merged

**Comment by evakhoni** [comment]
ok, OCPBUGS-35994 verified and merging!  
/unhold

**Comment by evakhoni** [comment]
@shellyyang1989 needs rebase again :man_facepalming:

**Comment by shellyyang1989** [comment]
/pj-rehearse ack

cc @evakhoni for lgtm. Thank you!

**Comment by evakhoni** [comment]
np.  
/lgtm
/approve

**Comment by shellyyang1989** [comment]
cc @liangxia to approve. Thank you!

**Pull request merged**
