### PR TITLE
Add snyk scanner

### PR DESCRIPTION
**Pull request by miyadav**
@elmiko @sunzhaohua2 @huali9 @shellyyang1989 @JoelSpeed PTAL when time permits , if it is helping us to add this .

[reference](https://docs.ci.openshift.org/docs/how-tos/add-security-scanning/)

### CODE REVIEW

**Comment by miyadav** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-gcp-master-security

**Comment by shellyyang1989** [comment]
It's fine with me, but leaving it to the dev experts to see if it makes sense.

**Comment by JoelSpeed** [comment]
I believe this is desirable in the long term, so I'm +1, but, given there are already failures, how do we handle this? Do we need to configure it to ignore the low and medium risk stuff, or should we be attempting to fix these upstream and then bring the changes back down? Anyone seen any guidance?

**Comment by miyadav** [comment]
@JoelSpeed I think , this issue we are seeing here  is already fixed by [this](https://issues.redhat.com/browse/OCPBUGS-28331)

**Comment by JoelSpeed** [comment]
Have tagged that other fix, lets retry once that's through

**Comment by miyadav** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-gcp-master-security

**Comment by miyadav** [comment]
/pj-rehearse pull-ci-openshift-cluster-api-provider-gcp-master-security

**Pull request closed without merging**
