### PR TITLE
USHIFT-1437: run microshift test script remotely on the host, not in the CI pod

### PR DESCRIPTION
**Pull request by dhellmann**
Fixes the issue with https://github.com/openshift/microshift/pull/2042

/assign @copejon @pacevedom

### CODE REVIEW

**Comment by copejon** [comment]
Per the build-cluster output, needs `make update-ci-build-clusters` to be run

**Comment by dhellmann** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-metal-tests

**Comment by dhellmann** [comment]
> Per the build-cluster output, needs `make update-ci-build-clusters` to be run

I don't know what that is. The output is changing ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml, which isn't a file I'm comfortable updating. The job isn't required, so I think we can merge our change without it, unless you know what that file is?

**Comment by copejon** [comment]
I think then you just need to rebase on the master:HEAD

**Comment by dhellmann** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-metal-tests

**Comment by dhellmann** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-metal-tests

**Comment by dhellmann** [comment]
This is a dupe of #41239 but let's see how the rehearsal goes.

**Comment by dhellmann** [comment]
/close

Let's take https://github.com/openshift/release/pull/41239 instead

**Pull request closed without merging**
