### PR TITLE
Use build root from 4.10 and 4.11 Alertmanager repository

### PR DESCRIPTION
**Pull request by jan--f**

### CODE REVIEW

**Review by marioferh — COMMENTED** [review]
/lgtm

**Comment by jan--f** [comment]
/pj-rehearse pull-ci-openshift-prometheus-alertmanager-release-4.10-test
/pj-rehearse pull-ci-openshift-prometheus-alertmanager-release-4.10-vendor

**Comment by slashpai** [comment]
@jan--f Since 4.10 jiras are closed I think we don't changes for 4.10 files here?

**Comment by simonpasquier** [comment]
/label rehearsals-ack

I assume that the e2e test failure isn't related to the build root change (the image build is ok).

**Pull request merged**
