### PR TITLE
microshift: move yq fetch / checksum validation to operator config file

### PR DESCRIPTION
**Pull request by copejon**
[USHIFT-298](https://issues.redhat.com//browse/USHIFT-298)

### CODE REVIEW

**Comment by copejon** [comment]
openshift-conformance-sig-api-machinery and the copr-rpm-health-check failed due ssh connectivity issues, rerunning.

**Comment by copejon** [comment]
More ssh flakes.  
/test pj-rehearse

**Comment by dhellmann** [comment]
/lgtm

I'll let you remove the WIP label if this is OK to merge.

**Pull request merged**
