### PR TITLE
Creating manual job for metal cluster's test.

### PR DESCRIPTION
**Pull request by ricardomaraschini**
This commit creates a prow job to run image registry operator CI tests over metal clusters.

### CODE REVIEW

**Comment by dmage** [comment]
@abhinavdahiya can you help us with this job definition? Kubernetes API never spins up, but there are no debug information in artifacts except [the installer log](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/5369/rehearse-5369-pull-ci-openshift-cluster-image-registry-operator-master-e2e-metal/3/artifacts/e2e-metal/installer/.openshift_install.log).

**Comment by ricardomaraschini** [comment]
Hello @abhinavdahiya , did you find something ?

**Comment by ricardomaraschini** [comment]
/hold 

It is still unclear why we can't deploy a cluster using "metal" cluster profile. We gonna have to wait until we get some feedback from the team responsible before we push this forward.

**Pull request closed without merging**
