### PR TITLE
Undeploy secret-mirroring

### PR DESCRIPTION
**Pull request by hongkailiu**
The implementation is replaced by https://github.com/openshift/ci-tools/pull/1077

/hold

After merge i will delete those on `api.ci` and `build01/2`:

```bash
oc --context api.ci get sa -n ci secret-mirroring-controller
NAME                          SECRETS   AGE
secret-mirroring-controller   2         1y

oc --context api.ci get clusterrole secret-mirroring-controller
NAME
secret-mirroring-controller

oc --context api.ci get clusterrolebinding secret-mirroring-controller
NAME                          ROLE                           USERS   GROUPS   SERVICE ACCOUNTS                 SUBJECTS
secret-mirroring-controller   /secret-mirroring-controller                    ci/secret-mirroring-controller

oc --context api.ci get dc -n ci secret-mirroring-controller
NAME                          REVISION   DESIRED   CURRENT   TRIGGERED BY
secret-mirroring-controller   2787       1         1         config,image(ci-secret-mirroring-controller:latest)
```

/cc @alvaroaleman @stevekuznetsov

### CODE REVIEW

**Comment by alvaroaleman** [comment]
The other implementation is feature gated, until its merged and we prepare a PR to enable it we can leave this I think

**Comment by hongkailiu** [comment]
```bash
➜  Downloads oc --context api.ci delete dc -n ci secret-mirroring-controller --wait=false
deploymentconfig.apps.openshift.io "secret-mirroring-controller" deleted
➜  Downloads oc --context api.ci delete sa -n ci secret-mirroring-controller --wait=false
serviceaccount "secret-mirroring-controller" deleted
➜  Downloads oc --as system:admin --context api.ci delete clusterrole secret-mirroring-controller --wait=false
clusterrole.authorization.openshift.io "secret-mirroring-controller" deleted
➜  Downloads oc --as system:admin --context api.ci delete clusterrolebinding secret-mirroring-controller --wait=false
clusterrolebinding.authorization.openshift.io "secret-mirroring-controller" deleted
```

**Pull request merged**
