### PR TITLE
Upgrade Cilium to 1.10.3

### PR DESCRIPTION
**Pull request by errordeveloper**

### CODE REVIEW

**Comment by errordeveloper** [comment]
I believe we are hitting this: https://bugzilla.redhat.com/show_bug.cgi?id=1997050

I am not sure how to confirm this from the results in CI, it seems like like the task of gathering logs actually fails, but I am also not so familiar with Prow. @vrutkovs do you know if we can find CNO logs?

**Comment by vrutkovs** [comment]
[CNO logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/21293/rehearse-21293-periodic-ci-openshift-release-master-ci-4.9-e2e-azure-cilium/1429883583895441408/artifacts/e2e-azure-cilium/gather-extra/artifacts/pods/openshift-network-operator_network-operator-79ff95fcd8-8brj7_network-operator_previous.log)

Seems to be the same crash

**Comment by errordeveloper** [comment]
@vrutkovs when should this pick up https://github.com/openshift/cluster-network-operator/pull/1188?

**Review by vrutkovs — APPROVED** [review]
/approve
/lgtm

Some tests are still failing, but it can be sorted out in a separate PR

**Comment by errordeveloper** [comment]
@vrutkovs thanks very much for getting this over the line!

**Pull request merged**
