### PR TITLE
DTK: Updating the RHEL version from 8.6 to 9.2 in CI images.

### PR DESCRIPTION
**Pull request by ybettan**

### CODE REVIEW

**Review by joepvd — APPROVED** [review]
/lgtm

**Comment by qbarrand** [comment]
/pj-rehearse auto-ack
/hold
@ybettan please unhold to merge.

**Comment by ybettan** [comment]
/override ci/rehearse/openshift/driver-toolkit/release-4.13/check-commits-count
/override ci/rehearse/openshift/driver-toolkit/release-4.15/check-commits-count
There are not actual commits to KMM so those jobs are expected to fail.

/test ci/rehearse/openshift/driver-toolkit/release-4.15/e2e-aws
/test ci/rehearse/openshift/driver-toolkit/release-4.15/e2e-aws-driver-toolkit-presubmit
/test ci/rehearse/openshift/driver-toolkit/release-4.15/e2e-upgrade

**Comment by ybettan** [comment]
/pj-rehearse pull-ci-openshift-driver-toolkit-release-4.13-e2e-upgrade

**Comment by ybettan** [comment]
/pj-rehearse ack
`check-commits-count` are supposed to fail as there are not actual commits to KMM
`e2e-aws-driver-toolkit-presubmit` is broken unrelated to this PR - see https://github.com/openshift/driver-toolkit/pull/123

**Pull request merged**
