### PR TITLE
hypershift: convert cluster pool tests to nested

### PR DESCRIPTION
**Pull request by sjenning**
cc @alvaroaleman @csrwng 

Also renames the `e2e-aws-nested` test to `e2e-aws` as there is now no distinction.

### CODE REVIEW

**Review by alvaroaleman — APPROVED** [review]
/hold

Looks good, but after what happened this week I want to see rehearsals pass before we merge this

**Comment by sjenning** [comment]
AWS EIP quota increased

/test pj-rehearse

**Pull request merged**
