### PR TITLE
MSI: Add addon operator workflows

### PR DESCRIPTION
**Pull request by rnetser**

### CODE REVIEW

**Review by myakove — APPROVED** [review]

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-operator-v4.13-hypershift-sanity-rosa-rhods-hypershift

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-operator-v4.13-hypershift-sanity-rosa-rhods-hypershift

**Review by omrirh — APPROVED** [review]

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-operator-v4.13-hypershift-sanity-rosa-rhods-hypershift

**Comment by rnetser** [comment]
/pj-rehearse periodic-ci-CSPI-QE-MSI-rhods-addon-v4.13-smoke-rosa-rhods

**Review by myakove — APPROVED** [review]

**Pull request merged**
