### PR TITLE
Add new OADP job for virtualization testing.

### PR DESCRIPTION
**Pull request by mrnold**
Continue #48568, with TEST_VIRT environment variable set to launch oadp-operator's virtualization tests.

### CODE REVIEW

**Review by kaovilai — APPROVED** [review]

**Comment by kaovilai** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-master-4.14-e2e-test-kubevirt-aws

**Comment by kaovilai** [comment]
```
[AfterSuite] 
/go/src/github.com/openshift/oadp-operator/tests/e2e/e2e_suite_test.go:167
  > Enter [AfterSuite] TOP-LEVEL - /go/src/github.com/openshift/oadp-operator/tests/e2e/e2e_suite_test.go:167 @ 02/09/24 02:09:14.914
2024/02/09 02:09:14 Deleting Velero CR
  [FAILED] Unexpected error:
      <*errors.errorString | 0xc000b73240>: 
      resource name may not be empty
      {
          s: "resource name may not be empty",
      }
  occurred
  In [AfterSuite] at: /go/src/github.com/openshift/oadp-operator/tests/e2e/e2e_suite_test.go:176 @ 02/09/24 02:09:15.117
  < Exit [AfterSuite] TOP-LEVEL - /go/src/github.com/openshift/oadp-operator/tests/e2e/e2e_suite_test.go:167 @ 02/09/24 02:09:15.117 (203ms)
[AfterSuite] [FAILED] [0.203 seconds]
[AfterSuite] 
/go/src/github.com/openshift/oadp-operator/tests/e2e/e2e_suite_test.go:167
```
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/48623/rehearse-48623-pull-ci-openshift-oadp-operator-master-4.14-e2e-test-kubevirt-aws/1755762982920392704#1:build-log.txt%3A513

**Comment by mrnold** [comment]
This needs https://github.com/openshift/oadp-operator/pull/1325 to merge first.

**Comment by kaovilai** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-master-4.14-e2e-test-kubevirt-aws

**Pull request merged**
