### PR TITLE
Add rebasebot periodic job for openstack-sushy

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Comment by elfosardo** [comment]
/pj-rehearse periodic-ci-openshift-eng-rebasebot-main-openstack-sushy

**Comment by JoelSpeed** [comment]
The rebase bot expects tags at the beginning of commit messages to understand how to handle commits not present in the upstream.
Normally either `UPSTREAM: <carry>:`, `UPSTREAM: <drop>:` or `UPSTREAM: <PR Num>`.
As you haven't used those commit formats, it doesn't understand the commit and drops it (by default I think the tag policy is strict), you could try setting the tag policy to warn instead of strict and then it should continue to pick the commits for now, but I'd recommend adjust the commit messages on a rebase so that you can enforce the strict tag policy in the future

**Comment by elfosardo** [comment]
thanks @JoelSpeed I'll do some tests following your instructions

**Comment by elfosardo** [comment]
we're good to go

**Pull request merged**
