### PR TITLE
odo enable lgtm_acts_as_approve and disable sticky lgtm

### PR DESCRIPTION
**Pull request by kadel**
- enable review_acts_as_lgtm (use GitHub reviews for lgtm)
- disable sticky lgtm

### CODE REVIEW

**Comment by kadel** [comment]
ping @bbguimaraes @hongkailiu

**Comment by petr-muller** [comment]
@kadel it's approved, anyone can give `/lgtm` - we prefer impacted team members to provide that

**Comment by kadel** [comment]
> @kadel it's approved, anyone can give `/lgtm` - we prefer impacted team members to provide that

oh, ok. I didn't know that anyone can give lgtm. Thx

**Pull request merged**
