### PR TITLE
KCMO: Use in repo build-root

### PR DESCRIPTION
**Pull request by tnozicka**
A canary.

Requires https://github.com/openshift/cluster-kube-controller-manager-operator/pull/466

/cc @soltysh @sttts @marun

### CODE REVIEW

**Comment by tnozicka** [comment]
/hold
for https://github.com/openshift/cluster-kube-controller-manager-operator/pull/466

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by tnozicka** [comment]
/retest
https://github.com/openshift/cluster-kube-controller-manager-operator/pull/466 merged

**Comment by tnozicka** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/12720/rehearse-12720-pull-ci-openshift-cluster-kube-controller-manager-operator-master-verify/1315926414544867328
```
could not resolve inputs: could not determine inputs for step [input:root]: could not resolve base image: imagestreamtags.image.openshift.io "release:rhel-8-release-golang-1.15-openshift-4.7" not found
time="2020-10-13T08:06:28Z" level=info msg="Reporting job state 'failed' with reason 'resolving_inputs'"
```
it looks like it forgot to mention the namespace or parse it because the image is there:
```
podman pull registry.svc.ci.openshift.org/openshift/release:rhel-8-release-golang-1.15-openshift-4.7
Trying to pull registry.svc.ci.openshift.org/openshift/release:rhel-8-release-golang-1.15-openshift-4.7...
Getting image source signatures
Copying blob a2ffc302bb17 skipped: already exists  
Copying blob c4d668e229cd skipped: already exists  
Copying blob 6ce40d9bec2e skipped: already exists  
Copying blob ec1681b6a383 skipped: already exists  
Copying blob 9d0d09b1ea44 skipped: already exists  
Copying blob a58713c9c924 [--------------------------------------] 0.0b / 0.0b
Copying config 0816b29902 done  
Writing manifest to image destination
Storing signatures
0816b29902d899fabe406cf2f3066dcb6ed6bec7e56c08ee63ec2a82d94f3420

```

**Comment by tnozicka** [comment]
the feature is not working yet - it can't provide the images https://issues.redhat.com/browse/DPTP-1640

**Pull request closed without merging**
