### PR TITLE
CORS-3790: Remove existing CI for AWS Outposts

### PR DESCRIPTION
**Pull request by yunjiang29**
Shutdown any resource created by engineering in the AWS Outpost account.

The cluster profile will be removed in a separate PR.

### CODE REVIEW

**Comment by yunjiang29** [comment]
cc @gpei @jianlinliu @jiajliu @qiliRedHat for review and awareness

**Comment by jiajliu** [comment]
upgrade part lgtm

**Comment by jianlinliu** [comment]
/lgtm

Does that mean we do not need to cover outpost any more ?

**Comment by yunjiang29** [comment]
> @yunjiang29 Does that mean we do not need to cover outpost any more ? 

Yes.

> How about keeping the steps and install workflow yaml files, just remove those ci jobs

OK

**Comment by yunjiang29** [comment]
@liangxia PTAL, thanks

**Pull request merged**
