### PR TITLE
flip GRC and ALC steps

### PR DESCRIPTION
**Pull request by vboulos**
- Flip GRC and ALC tests
- Add new CLC params to make it more flexible to switch between cloud providers (managed clusters)

### CODE REVIEW

**Comment by vboulos** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.15-interop-openshift-plus-interop-aws

**Comment by vboulos** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.15-interop-openshift-plus-interop-aws

**Comment by vboulos** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.15-interop-openshift-plus-interop-aws

**Comment by vboulos** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.15-interop-openshift-plus-interop-aws

**Comment by vboulos** [comment]
/pj-rehearse periodic-ci-stolostron-policy-collection-main-opp-ocp4.15-interop-openshift-plus-interop-aws

**Review by gparvin — APPROVED** [review]
This looks good.  The CLOUD_PROVIDERS magic is documented somewhere else I'm guessing? Or maybe the content of the secret documents how it's used...

**Pull request merged**
