### PR TITLE
Adding the End-Of-Life flag to releases

### PR DESCRIPTION
**Pull request by bradmwilliams**

### CODE REVIEW

**Comment by bradmwilliams** [comment]
/hold
Depends on https://github.com/openshift/release-controller/pull/380

**Comment by DennisPeriquet** [comment]
Hi @bradmwilliams, I just saw https://access.redhat.com/support/policy/updates/openshift.  So does this mean all of 4.1 - 4.6 should be marked as EOL?  In this PR, I only saw 4.1 - 4.4.  Thx.

**Comment by bradmwilliams** [comment]
@DennisPeriquet I don't think we are following the EOL guidelines that explicitly.  This is purely just a clean up effort to remove the older releases that we no longer officially support. 

As for 4.6, that's actually the Lont-Term Support release, so that's definitely not getting EOL'ed anytime soon.

**Pull request merged**
