### PR TITLE
Update the master sidecar

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by smarterclayton** [comment]
The failure there is genuine and is a combo of the things oleg was using to test rehearse

**Comment by bparees** [comment]
/lgtm

by proxy

**Comment by bparees** [comment]
/hold
rehearsal still failed

**Comment by deads2k** [comment]
was green before

/retest

**Comment by coreydaley** [comment]
> was green before
> 
> /retest

@dmage pushed an update since then.

**Pull request merged**
