### PR TITLE
Add Nutanix E2E workflow for Nutanix MAPI changes

### PR DESCRIPTION
**Pull request by adiantum**
- added config for openshift-e2e-nutanix for Nutanix MAPI
 - generated jobs
 - cluster build01 defined because VPN only available on build01

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Could we also add an operator variant like we have in AWS, https://github.com/openshift/release/blob/cb790f87eaef1af02bb53ee2ce75beb3461dbc0c/ci-operator/config/openshift/machine-api-provider-aws/openshift-machine-api-provider-aws-main.yaml#L65-L77

This runs a wider Machine API specific E2E suite

**Comment by JoelSpeed** [comment]
Config looks fine, would be nice to see some of the tests pass first, let's retry
/retest

**Comment by thunderboltsid** [comment]
@JoelSpeed the tests seem to be failing due to the PVC for prometheus not being bound due to the CSI Operator not being found.

```
- message: 'constraints not satisfiable: no operators found in package nutanixcsioperator
          in the catalog referenced by subscription nutanixcsioperator, subscription
          nutanixcsioperator exists'
        reason: ConstraintsNotSatisfiable
        status: "True"
        type: ResolutionFailed
```

We did not see this prior to Friday. Do you think this could be due to enforcing the version constraints i.e. CSI Operator being published for 4.10 but not 4.11 explicitly?

**Comment by JoelSpeed** [comment]
The CSI isn't something I know a lot about, let me see if I can find someone with more context to help out

**Comment by thunderboltsid** [comment]
We're seeing this with the latest builds (e.g. `4.11.0-0.nightly-2022-06-25-081133`)
```
~ oc get packagemanifests -n openshift-marketplace | grep 'nutanix'
~
```
but not with the slightly older builds `4.11.0-0.nightly-2022-06-15-222801`
```
~ oc get packagemanifests -n openshift-marketplace | grep 'nutanix'
nutanixcsioperator                                 Certified Operators   4d23h
```

**Comment by JoelSpeed** [comment]
/approve
/lgtm

Tests failed but the CI config is clearly working

**Pull request merged**
