### PR TITLE
config/job/step-registry for devspaces.

### PR DESCRIPTION
**Pull request by ascerra**

### CODE REVIEW

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.14-lp-interop-devspaces-interop-aws

**Comment by ascerra** [comment]
/pj-rehearse periodic-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.14-lp-interop-devspaces-interop-aws

**Review by pmacik — APPROVED** [review]

**Pull request merged**
