### PR TITLE
Add initial aws-managed-cspi-qe quota slice

### PR DESCRIPTION
**Pull request by rnetser**
Our team is onboarding and adding a cluster profile, here is the quota slice:  

https://github.com/openshift/ci-tools/pull/3318

### CODE REVIEW

**Comment by ascerra** [comment]
We also need to add the quota slice to the boskos_reaper.yaml
https://github.com/openshift/release/pull/34638/files

**Comment by rnetser** [comment]
> We also need to add the quota slice to the boskos_reaper.yaml https://github.com/openshift/release/pull/34638/files

The file looks different in the repo now:
https://github.com/openshift/release/blob/master/clusters/app.ci/prow/03_deployment/boskos_reaper.yaml

Am I missing something?

**Comment by ascerra** [comment]
> > We also need to add the quota slice to the boskos_reaper.yaml https://github.com/openshift/release/pull/34638/files
> 
> @ascerra The file looks different in the repo now: https://github.com/openshift/release/blob/master/clusters/app.ci/prow/03_deployment/boskos_reaper.yaml
> 
> Am I missing something?

Sorry it looks like my information was out of date. They [updated](https://github.com/openshift/release/pull/36642/files) how they maintain this file 2 weeks ago. So it looks like explicitly placing our quota-slice in this file is no longer needed.

**Pull request merged**
