### PR TITLE
openstack: Tag application credentials

### PR DESCRIPTION
**Pull request by pierreprinetti**
Facilitate associating application credentials with their originating cluster.

### CODE REVIEW

**Comment by pierreprinetti** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.14-e2e-openstack-ovn

**Review by mandre — COMMENTED** [review]
/lgtm
/approve

**Comment by pierreprinetti** [comment]
/pj-rehearse pull-ci-openshift-machine-api-provider-openstack-release-4.15-e2e-openstack-proxy

**Review by mandre — COMMENTED** [review]
/lgtm

**Pull request merged**
