### PR TITLE
Disable kubevirt-plugin gating job temporarily

### PR DESCRIPTION
**Pull request by irosenzw**
Disable the job until the Azure e2e tests will be fixed

Signed-off-by: Ido Rosenzwig <irosenzw@redhat.com>

### CODE REVIEW

**Comment by yaacov** [comment]
Thank you :+1:

**Review by petr-muller — APPROVED** [review]
> @Petr Muller I think both of them are in PTO for the next 2 weeks, can you do it maybe ? it's very small PR - just disabling our test because of the kubernetes Azure bug so it won't block us for the rest of the month

Approving b/c @irosenzw asked ^^^

**Pull request merged**
