### PR TITLE
feat(ibm): Enable verify on release testing

### PR DESCRIPTION
**Pull request by a-dsouza**
Enables our verify testing for release ci flow

### CODE REVIEW

**Comment by a-dsouza** [comment]
/pj-rehearse pull-ci-openshift-hypershift-release-4.14-e2e-ibmcloud-iks

**Comment by a-dsouza** [comment]
/pj-rehearse pull-ci-openshift-hypershift-release-4.14-e2e-ibmcloud-roks

**Comment by a-dsouza** [comment]
/pj-rehearse pull-ci-openshift-hypershift-release-4.13-e2e-ibmcloud-iks

**Comment by a-dsouza** [comment]
/pj-rehearse pull-ci-openshift-hypershift-release-4.13-e2e-ibmcloud-roks

**Comment by a-dsouza** [comment]
/pj-rehearse pull-ci-openshift-hypershift-release-4.12-e2e-ibmcloud-iks

**Comment by a-dsouza** [comment]
/pj-rehearse pull-ci-openshift-hypershift-release-4.12-e2e-ibmcloud-roks

**Comment by a-dsouza** [comment]
/pj-rehearse pull-ci-openshift-hypershift-release-4.15-e2e-ibmcloud-iks

**Comment by a-dsouza** [comment]
/pj-rehearse pull-ci-openshift-hypershift-release-4.15-e2e-ibmcloud-roks

**Comment by a-dsouza** [comment]
/pj-rehearse pull-ci-openshift-hypershift-release-4.15-e2e-ibmcloud-iks

**Comment by a-dsouza** [comment]
/pj-rehearse pull-ci-openshift-hypershift-release-4.15-e2e-ibmcloud-roks

**Comment by a-dsouza** [comment]
/pj-rehearse pull-ci-openshift-hypershift-release-4.15-e2e-ibmcloud-iks

**Comment by a-dsouza** [comment]
/pj-rehearse pull-ci-openshift-hypershift-release-4.15-e2e-ibmcloud-roks

**Comment by bryan-cox** [comment]
/pj-rehearse pull-ci-openshift-hypershift-release-4.15-e2e-ibmcloud-roks
/pj-rehearse pull-ci-openshift-hypershift-release-4.15-e2e-ibmcloud-iks

**Comment by a-dsouza** [comment]
/pj-rehearse pull-ci-openshift-hypershift-release-4.15-e2e-ibmcloud-iks

**Review by hasueki — APPROVED** [review]
/lgtm

**Pull request merged**
