### PR TITLE
rhobs/observability-operator: mark e2e test on OCP as optional

### PR DESCRIPTION
**Pull request by jan--f**
This corresponds to our github merge requirements.

### CODE REVIEW

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Comment by jan--f** [comment]
/pj-rehearse pull-ci-rhobs-observability-operator-main-observability-operator-e2e

**Comment by jan--f** [comment]
/pj-rehearse ack

Adding rehearse ack since the goal here is to make the flacky test optional.

**Pull request merged**
