### PR TITLE
Add external-storage to CI

### PR DESCRIPTION
**Pull request by tsmetana**

### CODE REVIEW

**Comment by droslean** [comment]
/hold

Hold, until granting access to the robots to the external-storage repository. Also, the webhook has to be configured as well.

**Comment by petr-muller** [comment]
> Hold, until granting access to the robots to the external-storage repository. Also, the webhook has to be configured as well.

Huh, anything special going on here? The repo is under `openshift` org, both robots and webhooks should set up for the whole org. What's different here?

**Comment by droslean** [comment]
I will use the robot's account to configure the webhook

**Pull request merged**
