### PR TITLE
Add redhat-appstudio/release-service-catalog repository

### PR DESCRIPTION
**Pull request by johnbieren**
Add the release-service-catalog repo with the same settings as the redhat-appstudio/release-service repo so we can start using openshift ci in our catalog repo.

### CODE REVIEW

**Comment by johnbieren** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-main-release-pipelines-e2e-suite

**Comment by johnbieren** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-main-release-pipelines-e2e-suite

**Comment by johnbieren** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-main-release-pipelines-e2e-suite

**Comment by johnbieren** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-main-release-pipelines-e2e-suite

**Comment by johnbieren** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-main-release-pipelines-e2e-suite

**Comment by johnbieren** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-main-release-pipelines-e2e-suite

**Comment by johnbieren** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-main-release-pipelines-e2e-suite

**Comment by johnbieren** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-main-release-pipelines-e2e-suite

**Comment by johnbieren** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-development-release-pipelines-e2e-suite

**Comment by johnbieren** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-development-release-pipelines-e2e-suite

**Comment by johnbieren** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-development-release-pipelines-e2e-suite

**Comment by johnbieren** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-development-release-pipelines-e2e-suite

**Comment by johnbieren** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-development-release-pipelines-e2e-suite

**Comment by johnbieren** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-development-release-pipelines-e2e-suite

**Comment by johnbieren** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-development-release-pipelines-e2e-suite

**Comment by johnbieren** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-development-release-pipelines-e2e-suite

**Comment by johnbieren** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-development-release-pipelines-e2e-suite

**Comment by johnbieren** [comment]
Blocked by https://github.com/redhat-appstudio/e2e-tests/pull/957

**Comment by johnbieren** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-development-release-pipelines-e2e-suite

**Comment by johnbieren** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-development-release-pipelines-e2e-suite

**Comment by johnbieren** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-development-release-pipelines-e2e-suite

**Comment by johnbieren** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-development-release-pipelines-e2e-suite

**Comment by johnbieren** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-development-release-pipelines-e2e-suite

**Comment by jinqi7** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-development-release-pipelines-e2e-suite

**Comment by jinqi7** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-development-release-pipelines-e2e-suite

**Comment by jinqi7** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-development-release-pipelines-e2e-suite

**Comment by jinqi7** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-development-release-pipelines-e2e-suite

**Comment by jinqi7** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-development-release-pipelines-e2e-suite

**Comment by jinqi7** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-development-release-pipelines-e2e-suite

**Comment by jinqi7** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-development-release-pipelines-e2e-suite

**Comment by jinqi7** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-development-release-pipelines-e2e-suite

**Comment by jinqi7** [comment]
/pj-rehearse pull-ci-redhat-appstudio-release-service-catalog-development-release-pipelines-e2e-suite

**Pull request merged**
