### PR TITLE
OSASINFRA-3627: [CI] Dummy job to test reach against machines behind Red Hat VPN

### PR DESCRIPTION
**Pull request by MiguelCarpio**
Dummy curl to titan20.lab.eng.tlv2.redhat.com for testing reachable

Executes a cloud connection test against rhoso-giant28

Get openstack catalog list from the underlying ocp (where run the RHOSO Control Plane)

Get openstack catalog list from using the openstackclient

### CODE REVIEW

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-openshift-e2e-openstack-dummy

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-openshift-e2e-openstack-dummy

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-openshift-e2e-openstack-dummy

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-openshift-e2e-openstack-dummy

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-openshift-e2e-openstack-dummy

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-openshift-e2e-openstack-dummy

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-openshift-e2e-openstack-dummy

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-openshift-e2e-openstack-dummy

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-openshift-e2e-openstack-dummy

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-openshift-e2e-openstack-dummy

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-openshift-e2e-openstack-dummy

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-openshift-e2e-openstack-dummy

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-openshift-e2e-openstack-dummy

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-openshift-e2e-openstack-dummy

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-openshift-e2e-openstack-dummy

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-openshift-e2e-openstack-dummy

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-openshift-e2e-openstack-dummy

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-openshift-e2e-openstack-dummy

**Comment by rlobillo** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-openshift-e2e-openstack-dummy

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-openshift-e2e-openstack-dummy

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-openshift-e2e-openstack-dummy

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-openshift-e2e-openstack-dummy

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-openshift-e2e-openstack-dummy

**Comment by MiguelCarpio** [comment]
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-openshift-e2e-openstack-dummy

**Pull request closed without merging**
