### PR TITLE
assisted-nutanix: don't setup CSI and registry operator

### PR DESCRIPTION
**Pull request by vrutkovs**
This seems to block installation now, as CSI operators are not being applied to spoke cluster (assisted only)

This also now randomizes API/Ingress VIPs used so that several simultaneous rehearsals would not use the same IP pairs

### CODE REVIEW

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-nutanix-assisted
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-nutanix-assisted-2workers

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-nutanix-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-nutanix-assisted
/cc @eliorerz

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-nutanix-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-nutanix-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-nutanix-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-machine-api-provider-nutanix-release-4.12-e2e-nutanix-operator

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-nutanix-assisted

**Comment by vrutkovs** [comment]
>failed uploading image: unmarshalling error response invalid character 's' looking for beginning of value for response body stream timeout

/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-nutanix-assisted

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-machine-api-provider-nutanix-main-e2e-nutanix

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-nutanix-assisted

**Review by eliorerz — APPROVED** [review]
LGTM

**Pull request merged**
