### PR TITLE
Add okd configs for machine-api-operator and provider repos

### PR DESCRIPTION
**Pull request by Prashanth684**
As an effort to validate https://github.com/openshift/release/pull/50118, we want to make sure that changes for
creating okd jobs work in a few components and verifying that pre and
postsubmits work as expected. Once that is done, these images can be
promoted and mirrored to origin.

### CODE REVIEW

**Comment by Prashanth684** [comment]
/pj-rehearse pull-ci-openshift-machine-api-operator-master-okd-scos-images

**Comment by Prashanth684** [comment]
/pj-rehearse pull-ci-openshift-machine-api-provider-aws-main-okd-scos-images

**Comment by Prashanth684** [comment]
/pj-rehearse pull-ci-openshift-machine-api-provider-azure-main-okd-scos-images

**Comment by Prashanth684** [comment]
/pj-rehearse pull-ci-openshift-machine-api-provider-gcp-main-okd-scos-images

**Comment by Prashanth684** [comment]
/cc @JoelSpeed @elmiko could you PTAL these changes - they add configs for building images for OKD using centos base images rather than RHEL(https://issues.redhat.com/browse/OKD-210). I pulled these changes from a bigger PR(https://github.com/openshift/release/pull/50118), adding configs for all repos. We want to add these configs to a few components and merge them so we can validate that they are built and published correctly and mirror these to origin. Once that is done, we plan a big merge for all other components.

**Comment by Prashanth684** [comment]
/pj-rehearse pull-ci-openshift-machine-api-operator-master-okd-scos-images

**Comment by Prashanth684** [comment]
/pj-rehearse pull-ci-openshift-machine-api-provider-aws-main-okd-scos-images

**Comment by Prashanth684** [comment]
/pj-rehearse pull-ci-openshift-machine-api-provider-azure-main-okd-scos-images

**Comment by Prashanth684** [comment]
/pj-rehearse pull-ci-openshift-machine-api-provider-ibmcloud-main-okd-scos-images

**Comment by elmiko** [comment]
@Prashanth684  this generally looks good to me, but do we want to be running on all these platforms?

**Comment by Prashanth684** [comment]
> @Prashanth684 this generally looks good to me, but do we want to be running on all these platforms?

Whatever images we used to mirror for OKD, are being rebuilt with centos as base, so these are not "new" as such. This [PR](https://github.com/openshift/release/pull/49084/files) stopped the mirroring since we were leaking RHEL content and with this change that should be fixed.

**Comment by Prashanth684** [comment]
/pj-rehearse pull-ci-openshift-machine-api-provider-nutanix-main-okd-scos-images

**Comment by Prashanth684** [comment]
@elmiko are we good for an approval?

**Pull request merged**
