### PR TITLE
build02/kvm-device-plugin: Deploy daemonset w/serviceaccount, add role for it

### PR DESCRIPTION
**Pull request by cgwalters**
Copied from cgwalters/kvm-device-plugin@67f52fe
which I tested on a fresh cluster in a new namespace.

I think the problem is previously I was testing in the `kube-system`
namespace.

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@cgwalters this PR won't change anything. Not sure which fluentd DS you are referring to but I presume it works because its bound to a privileged SCC, not because its name starts with `admin`. You will need to add something like this for the SA: https://docs.openshift.com/container-platform/4.6/authentication/managing-security-context-constraints.html#security-context-constraints-example_configuring-internal-oauth

**Comment by cgwalters** [comment]
I modeled this after 
https://github.com/openshift/release/blob/master/core-services/cluster/logging/admin_fluentd-daemonset.yaml

**Comment by cgwalters** [comment]
Are you sure it won't work?  If the daemonset is created by a privileged user (and that's what the `admin_` prefix is doing right?) then we should get a SCC that allows this by default.  I definitely tested this code in a fresh cluster-bot as `kube:admin` in GCP.

**Comment by alvaroaleman** [comment]
The admin prefix does nothing and the user that creates everything has cluster-admin perms.

**Comment by cgwalters** [comment]
Yeah you're totally right sorry.  (Every time I have to debug sccs/rolebindings I have to re-read all the docs)

**Comment by cgwalters** [comment]
OK :new: reworked and ran this in a test cluster in a new namespace with this RBAC setup.

**Review by alvaroaleman — APPROVED** [review]

**Review by alvaroaleman — APPROVED** [review]

**Comment by cgwalters** [comment]
OK, it looks like this is running now, I see the daemonset running on 32 nodes.

But...my test pod fails to schedule
`  Warning  FailedScheduling   <unknown>                             0/32 nodes are available: 32 Insufficient devices.kubevirt.io/kvm.`

We updated the bootimage references on this cluster to 4.6, but did we ever delete any machines to cause them to reprovision from the new bootimage? 

Does `oc debug node/$somenode chroot /host ls -al /dev/kvm` work?

If not can you try e.g. `oc -n openshift-machine-api delete machine/$somemachine` ?

**Pull request merged**
