### PR TITLE
MGMT-14926: Assisted-Installer: Change test infra jobs to use OCP 4.14

### PR DESCRIPTION
**Pull request by eliorerz**
/cc @eliorerz

### CODE REVIEW

**Comment by eliorerz** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-periodic

**Comment by eliorerz** [comment]
/pj-rehearse periodic-ci-openshift-assisted-test-infra-master-e2e-nutanix-assisted-periodic

**Review by adriengentil — APPROVED** [review]
:crossed_fingers:

**Comment by eliorerz** [comment]
/pj-rehearse ci/rehearse/openshift/assisted-test-infra/master/e2e-metal-assisted-lvm

**Comment by eliorerz** [comment]
/pj-rehearse ci/rehearse/openshift/assisted-test-infra/master/e2e-metal-assisted-none

**Comment by eliorerz** [comment]
/pj-rehearse ci/rehearse/openshift/assisted-test-infra/master/e2e-metal-assisted-prod

**Comment by eliorerz** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-tang

**Comment by eliorerz** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-lvm

**Comment by eliorerz** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-single-node

**Comment by eliorerz** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-tpmv2

**Comment by eliorerz** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-none

**Comment by eliorerz** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-mce

**Comment by eliorerz** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-mce-sno

**Comment by eliorerz** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-prod

**Comment by eliorerz** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-day2-single-node

**Comment by eliorerz** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-mce

**Comment by eliorerz** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-mce-sno

**Review by osherdp — APPROVED** [review]

**Pull request merged**
