### PR TITLE
PowerVS: MissingStaticPodControllerDegraded

### PR DESCRIPTION
**Pull request by hamzy**
For the 4.13 release, they will not backport a fix for the MissingStaticPodControllerDegraded error.  Therefore, implement a hack to restart the kubelet on each of the master nodes.

### CODE REVIEW

**Comment by hamzy** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-ovn-ppc64le-powervs

**Comment by hamzy** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-ovn-ppc64le-powervs

**Comment by hamzy** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-ovn-ppc64le-powervs

**Comment by hamzy** [comment]
Hello
@bandrade
@jhou1
@jianzhangbjz
@kuiwang02
@liangxia
@rioliu-rh
@sergiordlr
@xia-zhao-rh
@yapei

Can one of you approve this small change?

**Review by jaypoulz — CHANGES_REQUESTED** [review]
I don't love this approach. My concern is that checking based on version forces us to carry version numbers forward manually instead of being automatically able to copy paste configs when a new version is branched. Additionally, this seems like a workaround that could be useful for other teams and stuff like that makes sense to live in a step registry step. Lastly, making these changes via ignition is more consistent with other machine-based configurations happening in CI.

Can we look into adding a step registry step for https://github.com/redhat-ztp/dev-utils/tree/static-pod-check/static-pod-check via ignition?

That way we can structure this patch as off by default, but enabled on specific jobs as needed.

**Comment by hamzy** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-ovn-ppc64le-powervs

**Comment by hamzy** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-ovn-ppc64le-powervs

**Comment by hamzy** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-ovn-ppc64le-powervs

**Comment by hamzy** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-ovn-ppc64le-powervs

**Comment by hamzy** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-ovn-ppc64le-powervs

**Comment by hamzy** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-ovn-ppc64le-powervs

**Comment by hamzy** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-ovn-ppc64le-powervs

**Comment by hamzy** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-ovn-remote-libvirt-ppc64le

**Comment by hamzy** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-ovn-remote-libvirt-ppc64le

**Comment by hamzy** [comment]
@jaypoulz 
```
sh-4.4$ oc debug node/libvirt-ppc64le-1-1-4-64km9-master-0
Temporary namespace openshift-debug-jb65q is created for debugging node...
Starting pod/libvirt-ppc64le-1-1-4-64km9-master-0-debug ...
To use host binaries, run `chroot /host`
Pod IP: 192.168.1.11
If you don't see a command prompt, try pressing enter.
sh-4.4# chroot /host
sh-5.1# systemctl status static-pod-check-workaround.service
● static-pod-check-workaround.service - Check for stuck static pod revisions
     Loaded: loaded (/etc/systemd/system/static-pod-check-workaround.service; enabled; preset: disabled)
     Active: active (running) since Tue 2023-09-19 22:09:59 UTC; 1h 3min ago
...
```

**Review by jaypoulz — APPROVED** [review]
This looks good to me.
I like that we have it around in case we need it again in the future, but it's limited in impact for now. Feel free to /unhold when ready.

**Comment by stbenjam** [comment]
/approve

Merge conflicts need to be resolved. It would be nicer if this problem was fixed in the product, maintaining workarounds in CI isn't great.

**Pull request merged**
