### PR TITLE
Update cnv-ci-src image base

### PR DESCRIPTION
**Pull request by rabin-io**

### CODE REVIEW

**Comment by rabin-io** [comment]
/pj-rehearse pull-ci-openshift-cnv-cnv-ci-release-4.14-images
/pj-rehearse pull-ci-openshift-cnv-cnv-ci-release-4.13-images
/pj-rehearse pull-ci-openshift-cnv-cnv-ci-release-4.12-images

**Comment by rabin-io** [comment]
/pj-rehearse pull-ci-openshift-cnv-cnv-ci-release-4.13-images pull-ci-openshift-cnv-cnv-ci-release-4.12-images

**Review by tiraboschi — APPROVED** [review]

**Comment by rabin-io** [comment]
/pj-rehearse pull-ci-openshift-cnv-cnv-ci-release-4.13-images

**Pull request merged**
