### PR TITLE
Add e2e test to openshift/hive

### PR DESCRIPTION
**Pull request by csrwng**
Adds an openshift_installer_src test to the Hive configuration.

### CODE REVIEW

**Comment by dgoodwin** [comment]
/lgtm
/hold

until we get the other PR merged

**Comment by petr-muller** [comment]
/hold

It is surprising to see *two* very similar jobs are added after adding just a single clause to the ci-op config. Is it intentional?

**Comment by csrwng** [comment]
Thank you @petr-muller. It was not intentional, it's fixed.

**Comment by csrwng** [comment]
@dgoodwin this should be ready to go

**Comment by petr-muller** [comment]
Needs https://github.com/openshift/release/pull/2753 to merge and also probably regenerate the jobs with new prowgen

**Comment by csrwng** [comment]
Thanks @petr-muller. Rebased and regenerated.
@dgoodwin you mind taking a second look?

**Pull request merged**
