### PR TITLE
Update import policy for PoweVS images

### PR DESCRIPTION
**Pull request by rpsene**
Signed-off-by: Rafael Peria de Sene <rpsene@br.ibm.com>

### CODE REVIEW

**Comment by petr-muller** [comment]
/hold

The change was intentional (https://github.com/openshift/release/pull/18979) and `ImageStream` imports were replaced with mirroring jobs ( https://docs.ci.openshift.org/docs/how-tos/external-images/ ). Is there a reason why these images should work differently?

**Comment by rpsene** [comment]
@petr-muller there is no special case for this image, but the hourly periodic job to mirror is not getting the latest image (he image we use is in a public quay.io location). Is this behavior expected?

**Comment by petr-muller** [comment]
That's because the job seems to be a dumpster fire: https://prow.ci.openshift.org/?job=periodic-image-mirroring-supplemental-*

```
error: unable to push manifest to registry.ci.openshift.org/ocp-on-powervs/powervs-container-host: received unexpected HTTP status: 500 Internal Server Error
error: unable to push manifest to registry.ci.openshift.org/ocp-on-powervs/powervs-container-host: received unexpected HTTP status: 500 Internal Server Error
error: unable to push manifest to registry.ci.openshift.org/ocp-on-powervs/powervs-container-host: received unexpected HTTP status: 500 Internal Server Error
error: unable to push manifest to registry.ci.openshift.org/ocp-on-powervs/powervs-container-host: received unexpected HTTP status: 500 Internal Server Error
error: unable to push manifest to registry.ci.openshift.org/ocp-on-powervs/powervs-container-host: received unexpected HTTP status: 500 Internal Server Error
error: unable to push manifest to registry.ci.openshift.org/ocp-on-powervs/powervs-container-host: received unexpected HTTP status: 500 Internal Server Error
error: unable to push manifest to registry.ci.openshift.org/ocp-on-powervs/powervs-container-host: received unexpected HTTP status: 500 Internal Server Error
error: unable to push manifest to registry.ci.openshift.org/ocp-on-powervs/powervs-container-host: received unexpected HTTP status: 500 Internal Server Error
error: unable to push manifest to registry.ci.openshift.org/ocp-on-powervs/powervs-container-host:powervs-actions: errors:
manifest blob unknown: blob unknown to registry
manifest blob unknown: blob unknown to registry
manifest blob unknown: blob unknown to registry
error: unable to push manifest to registry.ci.openshift.org/ocp-on-powervs/powervs-container-host:4.6: manifest invalid: manifest invalid
error: unable to push manifest to registry.ci.openshift.org/ocp-on-powervs/powervs-container-host:powervs-ocp-jenkins-deployment: manifest invalid: manifest invalid
error: unable to push manifest to registry.ci.openshift.org/ocp-on-powervs/powervs-container-host:latest: manifest invalid: manifest invalid
error: unable to push manifest to registry.ci.openshift.org/ocp-on-powervs/powervs-container-host:4.7: manifest invalid: manifest invalid 
```

@hongkailiu is this somethng you're still working on?

**Comment by rpsene** [comment]
@hongkailiu any feedback on why the image is not getting updated?

**Comment by hongkailiu** [comment]
> @hongkailiu any feedback on why the image is not getting updated?

The images should be up to date now. Sorry for the convenience.
There are issues with oc-image-mirror command and I have to do some manual retries.

**Comment by hongkailiu** [comment]
@rpsene 

I believe this PR can be closed.

We prefer image mirroring over importing.
Imports are pull-throughs. There is no guarantee that the images are stored locally in the registry.
We would like to make our CI registry more independent of other services.

**Pull request closed without merging**
