### PR TITLE
OCPQE-12669: Add ginkgo upgrade to openshift-upgrade-qe-test-paused-to-latest

### PR DESCRIPTION
**Pull request by liangxia**

### CODE REVIEW

**Comment by shellyyang1989** [comment]
lgtm. BTW, the chain covers the stable to stable eus testing by using the `--to-latest` option for upgrade. The stable to nightly eus [chain](https://github.com/openshift/release/blob/master/ci-operator/step-registry/cucushift/upgrade/paused/cucushift-upgrade-paused-workflow.yaml) seems to require the change as well.

**Comment by liangxia** [comment]
> lgtm. BTW, the chain covers the stable to stable eus testing by using the `--to-latest` option for upgrade. The stable to nightly eus [chain](https://github.com/openshift/release/blob/master/ci-operator/step-registry/cucushift/upgrade/paused/cucushift-upgrade-paused-workflow.yaml) seems to require the change as well.

That's a different one and need extra effort.  Will use a follow PR for that.

**Pull request merged**
