### PR TITLE
assisted-test-infra: inject promtail for e2e-metal-single-node-live-iso test

### PR DESCRIPTION
**Pull request by vrutkovs**
Ref: https://github.com/openshift/assisted-test-infra/pull/1980

Needs https://github.com/openshift/assisted-test-infra/pull/1987 to fix Ignition paths and https://github.com/openshift/assisted-test-infra/pull/2017 to fix number of params to run_container

### CODE REVIEW

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-single-node-live-iso

**Comment by smg247** [comment]
/uncc
You don't need my review on this one

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-single-node-live-iso

**Review by osherdp — APPROVED** [review]

**Comment by osherdp** [comment]
```
retry.api:api.py:40 run_container() takes from 2 to 4 positional arguments but 5 were given
```
do you know what this is about?

**Comment by vrutkovs** [comment]
Ah, we need https://github.com/openshift/assisted-test-infra/pull/2017 first

**Comment by vrutkovs** [comment]
/pj-rehearse pull-ci-openshift-assisted-test-infra-master-e2e-metal-single-node-live-iso

**Pull request closed without merging**
