### PR TITLE
Adds a new image that uses Jenkins to deploy OCP in PowerVS

### PR DESCRIPTION
**Pull request by rpsene**
Signed-off-by: Rafael Peria de Sene <rpsene@br.ibm.com>

### CODE REVIEW

**Comment by rpsene** [comment]
@Kuldip-Nanda can you take a look at this PR?

**Comment by Kuldip-Nanda** [comment]
Can I be added as a reviewer?

**Review by Kuldip-Nanda — COMMENTED** [review]
This looks ok.

**Review by stevekuznetsov — APPROVED** [review]
without whitespace, looks ok?

**Comment by stevekuznetsov** [comment]
I am not super sure why this is failing that validation, but if you rebase it should be fine.

/hold

**Pull request closed without merging**
