### PR TITLE
Adding remaining openshift-docs branches to Prow

### PR DESCRIPTION
**Pull request by aireilly**
This PR brings the final openshift-docs branches into Prow

### CODE REVIEW

**Comment by kalexand-rh** [comment]
LGTM

**Review by kalexand-rh — APPROVED** [review]

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-pipelines-docs-1.11-validate-asciidoc

**Comment by aireilly** [comment]
/pj-rehearse pull-ci-openshift-openshift-docs-pipelines-docs-1.11-deploy-preview

**Pull request merged**
