### PR TITLE
MULTIARCH-4553: Enabling HCP with IBMZ workflow in 4.15 periodic job runs

### PR DESCRIPTION
**Pull request by phani2898**
Enabling HCP IBMZ workflow for 4.15 periodic jobs

**Added :** 
- New config and job in 4.15 periodics
- Added a WA for the node detachment [bug](https://issues.redhat.com/browse/HOSTEDCP-1427) while destroying the HCP

**Changes :**
- Changed the base domain for HCP
- Changed SSH key creation and usage 
- Changed the approach to add floating ip to the zVSIs as per the latest ibmcloud udpate

### CODE REVIEW

**Comment by phani2898** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance

**Comment by phani2898** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance

**Comment by phani2898** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-mce-ibmz-conformance

**Comment by phani2898** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance 
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-mce-ibmz-conformance

**Comment by phani2898** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-mce-ibmz-conformance

**Comment by phani2898** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance

**Comment by phani2898** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-mce-ibmz-conformance

**Comment by phani2898** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance

**Comment by phani2898** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-mce-ibmz-conformance

**Comment by phani2898** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-mce-ibmz-conformance

**Comment by phani2898** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-mce-ibmz-conformance

**Comment by phani2898** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance

**Comment by phani2898** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-mce-ibmz-conformance

**Comment by phani2898** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance

**Comment by phani2898** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-mce-ibmz-conformance

**Comment by phani2898** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-mce-ibmz-conformance

**Comment by phani2898** [comment]
https://issues.redhat.com/browse/HOSTEDCP-1427 , This bug is blocking to have a successful rehearsal for both 4.14 and 4.15.

**Comment by phani2898** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance

**Comment by phani2898** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-mce-ibmz-conformance

**Comment by phani2898** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance

**Comment by phani2898** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance

**Comment by phani2898** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance

**Comment by phani2898** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance

**Comment by phani2898** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance

**Comment by phani2898** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance

**Comment by phani2898** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance

**Comment by veera-damisetti** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance

**Comment by veera-damisetti** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance

**Comment by veera-damisetti** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance

**Comment by veera-damisetti** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance

**Comment by veera-damisetti** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance

**Comment by veera-damisetti** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance

**Comment by veera-damisetti** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance

**Comment by veera-damisetti** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance

**Comment by veera-damisetti** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance

**Comment by veera-damisetti** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance

**Comment by veera-damisetti** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance

**Comment by veera-damisetti** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance

**Comment by veera-damisetti** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-ibmz-conformance

**Comment by phani2898** [comment]
@csrwng Can you please review and add necessary labels for this PR ?

**Comment by enxebre** [comment]
/hold
Hi @phani2898 can you please squash all 34 commits into a single one?

**Comment by enxebre** [comment]
/hold cancel
Cancelling hold as tide/merge-method-squash was applied. As a good practice please still squash your commits into atomic meaningful ones in this an upcoming PRs for easier review and faster merging. Thanks @phani2898 !

**Comment by phani2898** [comment]
> /hold cancel Cancelling hold as tide/merge-method-squash was applied. As a good practice please still squash your commits into atomic meaningful ones in this an upcoming PRs for easier review and faster merging. Thanks @phani2898 !

okay sure, thanks @enxebre , Can you also please add the approve label as well ?

**Comment by phani2898** [comment]
Closing this as https://github.com/openshift/release/pull/50374 this is merged which does the same job

**Pull request closed without merging**
