### PR TITLE
add baseimage 'assisted-service-scripts' to support hypershift agent

### PR DESCRIPTION
**Pull request by LiangquanLi930**

### CODE REVIEW

**Comment by LiangquanLi930** [comment]
@jhou1 @liangxia Could you help to review this PR? Thanks

**Comment by jhou1** [comment]
Does this also need to be applied to 4.16 files and other versions?

**Comment by LiangquanLi930** [comment]
> Does this also need to be applied to 4.16 files and other versions?

We don't need to update to 4.16. For MCE-Agent 4.16, we need to wait for MCE2.6, which will require 2 weeks or even more after OCP 4.15 GA to have the build for MCE 2.6.

**Pull request merged**
