### PR TITLE
Add cloud-network-config-controller to image mirroring

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
This PR adds the new network component "cloud-network-config-controller" to the image mirroring. 

Background:

EP: https://github.com/openshift/enhancements/pull/571
Repo: https://github.com/openshift/cloud-network-config-controller
Release PRs enabling OCP CI/CD: https://github.com/openshift/release/pull/15824 / https://github.com/openshift/release/pull/17088 

As seen in the repo, there isn't much code for now. However, once the pending API PR gets in: https://github.com/openshift/api/pull/859 that will change. There is a dependency to get this PR in as to create the proper image references in the CNO when deploying the component and testing the functionality implemented.

/assign @smarterclayton

### CODE REVIEW

**Comment by alexanderConstantinescu** [comment]
So, `/test prow-config` failed, but I fail to see why it did so because of my change. Here's me running it locally:

```
$ make prow-config
docker pull registry.ci.openshift.org/ci/determinize-prow-config:latest
latest: Pulling from ci/determinize-prow-config
Digest: sha256:ce0f68bce32402548e50c977952521f44c3a57cd1a93cf1e74e8fa211fe84f66
Status: Image is up to date for registry.ci.openshift.org/ci/determinize-prow-config:latest
registry.ci.openshift.org/ci/determinize-prow-config:latest
docker run --rm -v "/home/aconstan/go/src/github.com/openshift/release/core-services/prow/02_config:/config:z" registry.ci.openshift.org/ci/determinize-prow-config:latest --prow-config-dir /config
aconstan@work ~/go/src/github.com/openshift/release (add-cloud-network-config-controller-to-image-mirroring) $ git status
On branch add-cloud-network-config-controller-to-image-mirroring
Your branch is up to date with 'myfork/add-cloud-network-config-controller-to-image-mirroring'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   core-services/prow/02_config/_config.yaml
        modified:   core-services/prow/02_config/_plugins.yaml

no changes added to commit (use "git add" and/or "git commit -a")
aconstan@work ~/go/src/github.com/openshift/release (add-cloud-network-config-controller-to-image-mirroring) $ git diff
diff --git a/core-services/prow/02_config/_config.yaml b/core-services/prow/02_config/_config.yaml
index f3008d5bd6..d2cdcd722d 100644
--- a/core-services/prow/02_config/_config.yaml
+++ b/core-services/prow/02_config/_config.yaml
@@ -634,6 +634,7 @@ jenkins_operators:
   max_goroutines: 1
 log_level: debug
 managed_webhooks:
+  auto_accept_invitation: false
   respect_legacy_global_token: false
 owners_dir_blacklist:
   default:
diff --git a/core-services/prow/02_config/_plugins.yaml b/core-services/prow/02_config/_plugins.yaml
index c3379e43e3..07d024d03f 100644
--- a/core-services/prow/02_config/_plugins.yaml
+++ b/core-services/prow/02_config/_plugins.yaml
@@ -4089,6 +4089,9 @@ owners:
   labels_blacklist:
   - approved
   - lgtm
+  labels_denylist:
+  - approved
+  - lgtm
 plugins:
   3scale/3scale-operator:
     plugins:
```

**Comment by smarterclayton** [comment]
Name is approved.  Will tag when prow-config passes.

**Pull request merged**
