### PR TITLE
Debug Distributed Tracing job and fix minor issues. 

### PR DESCRIPTION
**Pull request by IshwarKanse**
Debug Distributed Tracing job and fix minor issues with operator bundle installation.

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-open-telemetry-opentelemetry-operator-main-ocp-4.14-amd64-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-open-telemetry-opentelemetry-operator-main-ocp-4.14-amd64-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-open-telemetry-opentelemetry-operator-main-ocp-4.14-amd64-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-open-telemetry-opentelemetry-operator-main-ocp-4.14-amd64-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
/pj-rehearse periodic-ci-open-telemetry-opentelemetry-operator-main-ocp-4.14-amd64-opentelemetry-e2e-tests

**Comment by IshwarKanse** [comment]
For OTEL, we have a bug filed to fix cases which needs to work on Prow https://issues.redhat.com/browse/TRACING-3357

**Review by iblancasa — APPROVED** [review]

**Pull request merged**
