### PR TITLE
fix aws sno control plane vm type

### PR DESCRIPTION
**Pull request by lwan-wanglin**
refer: https://issues.redhat.com/browse/OCPQE-18639

### CODE REVIEW

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-multi-nightly-aws-ipi-disconnected-private-sno-arm-f14

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-multi-nightly-aws-ipi-disc-sno-baselinecaps-none-arm-f28

**Comment by lwan-wanglin** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-multi-nightly-aws-ipi-ovn-ipsec-arm-mixarch-f28

**Comment by lwan-wanglin** [comment]
@yunjiang29 the triggled job installation part all succeed, PTAL, thanks!

**Comment by yunjiang29** [comment]
@liangxia PTAL, thanks

**Pull request merged**
