### PR TITLE
add branches to kie-cloud-operator job

### PR DESCRIPTION
**Pull request by tchughesiv**
Signed-off-by: tchughesiv <tchughesiv@gmail.com>

### CODE REVIEW

**Comment by petr-muller** [comment]
@tchughesiv It looks like you are adding manually crafted (or copy-pasted) jobs. While that's possible, it's prone to mistakes and rot - we suggest to put a ci-operator config in place for the branch and generate jobs from that using Prowgen.

**Comment by tchughesiv** [comment]
@petr-muller thanks for the heads up... should be resolved now

**Comment by tchughesiv** [comment]
@petr-muller let me know if i need to change anything else

**Comment by tchughesiv** [comment]
@droslean @petr-muller any status? anything else we need to do on this?

**Comment by tchughesiv** [comment]
@droslean here's what we get with that test:
```shell
[ERROR] This check enforces that configuration YAML files will be uploaded automatically
[ERROR] as they change. You are adding a file that is not covered by the automatic upload.
[ERROR] Contact an administrator to resolve this issue.

[ERROR] The following errors were found:

time="2019-04-29T14:09:21Z" level=warning msg="Failed to determine info for prow job config" error="file name was not prefixed with \"ci-operator-jobs-\": \"infra-periodics\"" source-file=ci-operator/jobs/infra-periodics.yaml
time="2019-04-29T14:09:22Z" level=error msg="Config file does not belong to any auto-updating config." source-file=ci-operator/config/kiegroup/kie-cloud-operator/kiegroup-kie-cloud-operator-1.0.x.yaml
time="2019-04-29T14:09:22Z" level=error msg="Config file does not belong to any auto-updating config." source-file=ci-operator/config/kiegroup/kie-cloud-operator/kiegroup-kie-cloud-operator-1.1.x.yaml
time="2019-04-29T14:09:23Z" level=error msg="Config file does not belong to any auto-updating config." source-file=ci-operator/jobs/kiegroup/kie-cloud-operator/kiegroup-kie-cloud-operator-1.0.x-postsubmits.yaml
time="2019-04-29T14:09:23Z" level=error msg="Config file does not belong to any auto-updating config." source-file=ci-operator/jobs/kiegroup/kie-cloud-operator/kiegroup-kie-cloud-operator-1.0.x-presubmits.yaml
time="2019-04-29T14:09:23Z" level=error msg="Config file does not belong to any auto-updating config." source-file=ci-operator/jobs/kiegroup/kie-cloud-operator/kiegroup-kie-cloud-operator-1.1.x-postsubmits.yaml
time="2019-04-29T14:09:23Z" level=error msg="Config file does not belong to any auto-updating config." source-file=ci-operator/jobs/kiegroup/kie-cloud-operator/kiegroup-kie-cloud-operator-1.1.x-presubmits.yaml
time="2019-04-29T14:09:26Z" level=fatal msg="Found configurations that do not belong to the correct auto-updating config"
```

**Comment by droslean** [comment]
this is because your branches doesn't follow the `config_updater` in `plugins.yaml`.

**Comment by droslean** [comment]
I believe its better if the name of the branches will change to `release-1.x.x` format

**Comment by droslean** [comment]
That means that the filenames will change also. And the actual branch names as well. https://github.com/kiegroup/kie-cloud-operator/branches

**Comment by tchughesiv** [comment]
i've also rebased assuming those configs should have already been formatted, but they haven't yet.

**Comment by droslean** [comment]
Please use the latest `ci-operator-prowgen` and re-generate the jobs

**Comment by tchughesiv** [comment]
@droslean just my own or all?

**Comment by droslean** [comment]
it doesn't matter. The others have already changed  in #3627

**Comment by tchughesiv** [comment]
@droslean done, no changes ... notice, the test is failing on _other_ jobs unrelated to mine.
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/3503/pull-ci-openshift-release-master-ordered-prow-config/5501/build-log.txt

**Comment by droslean** [comment]
#3628 opened to fix the issue.

**Comment by droslean** [comment]
good to go :)

**Comment by tchughesiv** [comment]
> good to go :)

@droslean does someone have to approve & lgtm?

**Pull request merged**
