### PR TITLE
Switch 'chectl-devworkspace-happy-path' job to 'che-aws' cluster profile

### PR DESCRIPTION
**Pull request by dmytro-ndp**
Change list:
1. Switch `che-incubator > chectl > chectl-devworkspace-happy-path` job to '**che-aws**' cluster profile.
2. Update owner list of `devfile/devworkspace-operator` jobs.

Related to the issue https://issues.redhat.com/browse/CRW-5370

### CODE REVIEW

**Review by amisevsk — APPROVED** [review]

**Review by tolusha — APPROVED** [review]

**Review by svor — APPROVED** [review]

**Comment by jmguzik** [comment]
This has to be solved: https://github.com/openshift/release/pull/47780#issuecomment-1896465158

**Comment by dmytro-ndp** [comment]
@jmguzik : thank you for review!
About:
> One way to make the user trusted is to add them as [members](https://github.com/orgs/openshift/people) of the openshift org

It appears that I don't have the necessary permissions to add the user `AObuchow` to https://github.com/orgs/openshift/people. Could you please guide me on how to proceed?

**Review by musienko-maxim — APPROVED** [review]

**Pull request merged**
