### PR TITLE
oadp: use ocp builder golang

### PR DESCRIPTION
**Pull request by kaovilai**
- Revert "oadp-operator: use Dockerfile in repo and don't replace build root (#41255)"
- oadp: Use ocp builder golang

### CODE REVIEW

**Comment by kaovilai** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-velero-datamover-4.10-operator-unit-test

**Comment by kaovilai** [comment]
/pj-rehearse pull-ci-openshift-oadp-operator-master-4.11-operator-unit-test

**Review by shubham-pampattiwar — APPROVED** [review]

**Pull request merged**
