### PR TITLE
Fix e2e openstack job for openstack-cinder-csi-driver-operator

### PR DESCRIPTION
**Pull request by Fedosin**

### CODE REVIEW

**Comment by jsafrane** [comment]
Please update also 4.7 and 4.8 config. And should be 4.6 fixed too?

**Comment by Fedosin** [comment]
yes, previously this PR also contained e2e tests for 4.7 and 4.8, but it turned out that openstack ci can't handle 3 simultaneous jobs and therefore pj-rehearse couldn't pass. So we decided to add support for 4.7 and 4.8 in separate PRs. 4.6 support is not required since we don't have Cinder CSI there.

**Comment by jsafrane** [comment]
```
    <*exec.Error | 0xc001312840>: {
        Name: "cinder",
        Err: {
            s: "executable file not found in $PATH",
        },
    }
    exec: "cinder": executable file not found in $PATH
occurred
```

Looks like the tests run on something that does not have `/usr/bin/cinder` installed.

**Review by mandre — COMMENTED** [review]
/lgtm

**Pull request merged**
