### PR TITLE
Add support for new startup image

### PR DESCRIPTION
**Pull request by asalkeld**
this is needed for: https://github.com/openshift/openshift-azure/pull/1151

cc @mjudeikis

### CODE REVIEW

**Comment by mjudeikis** [comment]
@asalkeld run these on your PR:
```
docker run -it -v $(pwd)/ci-operator/jobs:/jobs:z registry.svc.ci.openshift.org/ci/determinize-prow-jobs:latest --prow-jobs-dir /jobs
docker run -it -v $(pwd)/ci-operator:/ci-operator:z registry.svc.ci.openshift.org/ci/ci-operator-prowgen:latest --from-dir /ci-operator/config/ --to-dir /ci-operator/jobs 
```
linting is off

**Comment by petr-muller** [comment]
> @asalkeld run these on your PR:

...and make sure you have the latest images pulled (very common gotcha)

**Comment by jim-minter** [comment]
@asalkeld I've pushed an additional commit here.  Rules of thumb:
* no existing v* config should refer to the startup image as it's not going to be backported to that branch
* all master config should refer to the startup image as it's an essential component on master
* (the next major v* release we make will refer to the startup image as it'll be a branch at that point)

**Comment by jim-minter** [comment]
/hold
want to get a vm image build through before we merge this

**Pull request merged**
