### PR TITLE
Promote the Distributed Tracing tests runner image for running acceptance tests.

### PR DESCRIPTION
**Pull request by IshwarKanse**

### CODE REVIEW

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-distributed-tracing-qe-main-ocp4.13-amd64-distributed-tracing-tests-acceptance

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-distributed-tracing-qe-main-ocp4.13-amd64-distributed-tracing-tests-acceptance

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-distributed-tracing-qe-main-ocp4.13-amd64-distributed-tracing-tests-acceptance pull-ci-openshift-distributed-tracing-qe-main-ocp4.13-amd64-acceptance-distributed-tracing-tests-acceptance

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-distributed-tracing-qe-main-ocp4.13-amd64-distributed-tracing-tests-acceptance

**Comment by IshwarKanse** [comment]
/pj-rehearse pull-ci-openshift-distributed-tracing-qe-main-ocp4.13-amd64-distributed-tracing-tests-acceptance

**Review by vprashar2929 — APPROVED** [review]
/lgtm

**Pull request merged**
