### PR TITLE
add prow vendor check

### PR DESCRIPTION
**Pull request by laurafitzgerald**
**JIRA**
https://issues.redhat.com/browse/INTLY-4602

**Related PR**
https://github.com/integr8ly/heimdall/pull/18

**What**
Adding prow job to run vendor check command

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
Requires merge of the related pr first for tests to pass.

**Comment by mikenairn** [comment]
/hold cancel 

Dependent PR is now merged integr8ly/heimdall#18

**Comment by laurafitzgerald** [comment]
@mikenairn can we merge this one now?

**Pull request merged**
