### PR TITLE
OSASINFRA-3282: OpenStack: Add v6primary dual-stack CI

### PR DESCRIPTION
**Pull request by MaysaMacedo**

### CODE REVIEW

**Comment by MaysaMacedo** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.15-e2e-openstack-dualstack-v6primary

**Comment by MaysaMacedo** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.15-e2e-openstack-dualstack-v6primary
/cc @EmilienM 
looks promising, only one test failed

**Comment by gryf** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.15-e2e-openstack-dualstack-v6primary
Seems like there is one test which permfail. Let see if that's a pattern.

**Comment by MaysaMacedo** [comment]
`when FIPS is disabled the HAProxy router should serve routes when configured with a 1024-bit RSA key`
Is always failing, I'm debugging it. I see it also fails on vsphere v6 primary jobs

**Comment by MaysaMacedo** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.15-e2e-openstack-dualstack-v6primary

**Comment by MaysaMacedo** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.15-e2e-openstack-dualstack-v6primary

**Comment by MaysaMacedo** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.15-e2e-openstack-dualstack-v6primary

**Comment by MaysaMacedo** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.15-e2e-openstack-dualstack-v6primary

**Pull request merged**
