### PR TITLE
Adding debug logging

### PR DESCRIPTION
**Pull request by FilipB**

### CODE REVIEW

**Comment by yxun** [comment]
It looks like we are getting git auth error.
Do we have the correct mounted secret token for this job ?

```
curl -sSfLH 'Authorization: token XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' https://api.github.com/user
++ jq --raw-output .login
curl: (22) The requested URL returned error: 401
```

**Comment by FilipB** [comment]
> It looks like we are getting git auth error. Do we have the correct mounted secret token for this job ?
> 
> ```
> curl -sSfLH 'Authorization: token XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' https://api.github.com/user
> ++ jq --raw-output .login
> curl: (22) The requested URL returned error: 401
> ```

Correct. The token is bad

**Pull request closed without merging**
