### PR TITLE
chore: add v1.2.2 for securesign/rekor

### PR DESCRIPTION
**Pull request by lance**
Adds configuration for the v1.2.2 release branch on the securesign/rekor repository, and one minor change to the release-next job.

### CODE REVIEW

**Review by sallyom — APPROVED** [review]
/lgtm

**Comment by lance** [comment]
Thanks for the `/lgtm` @cooktheryan and @sallyom - once this merges, then we can pin the version in image-factory. https://github.com/securesign/image-factory/issues/16

**Pull request merged**
