### PR TITLE
Add main branch for ODH oprator for v2

### PR DESCRIPTION
**Pull request by zdtsw**
When PR to newly set "main" branch of opendatahub-operator, CI not running "Pending — Not mergeable. No Tide query for branch main found"

- Add main branch for opendatahub-operator v2/new operator
- similar to feature-rearchitecture branch
- can add e2e test (similar to master branch) later if needed

### CODE REVIEW

**Comment by VaishnaviHire** [comment]
@zdtsw You will probably need to run `make jobs`

**Comment by zdtsw** [comment]
> @zdtsw You will probably need to run `make jobs`

finally it passed..... was a bug in the makefile not allow me to just "make job".....

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

**Comment by danilo-gemoli** [comment]
[This comment](https://github.com/openshift/release/pull/42337#issuecomment-1682047464) goes unnoticed most of the time, I'm wondering if we need to make it somehow more visible @zdtsw @VaishnaviHire .
/lgtm
/pj-rehearse ack

**Pull request merged**
