### PR TITLE
Added multi-arch cluster-samples jobs to 4.5 periodics file

### PR DESCRIPTION
**Pull request by jaypoulz**
Signed-off-by: Renin <reninking@gmail.com>

Closes #8854 
Closes https://github.com/openshift/release/pull/8859

### CODE REVIEW

**Comment by jaypoulz** [comment]
Blocked by: https://github.com/openshift/origin/pull/25387

**Comment by jaypoulz** [comment]
/assign @hongkailiu
This was completely green, but I needed to push an update to resolve a conflict with the template-test tracking list.
Can I get an approval for these new jobs? They're informative only.

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
