### PR TITLE
cri-o: bump image to golang-1.19

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt~ <pehunt@redhat.com>

### CODE REVIEW

**Comment by haircommander** [comment]
@sohankunkerkar @wgahnagl @harche @rphillips PTAL

**Review by sohankunkerkar — APPROVED** [review]
/lgtm

**Comment by haircommander** [comment]
images passed @sohankunkerkar @rphillips can I have a tag back?
/pj-rehearse skip

**Pull request merged**
