### PR TITLE
USHIFT-953: Use rhel9 base images for CI

### PR DESCRIPTION
**Pull request by pacevedom**

### CODE REVIEW

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-e2e

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-e2e

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-e2e

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-e2e

**Comment by pacevedom** [comment]
/pj-rehearse pull-ci-openshift-microshift-main-microshift-e2e

**Comment by dhellmann** [comment]
`microshift-e2e` is failing with 

```
STEP 3/8: RUN pip3 install --upgrade pip &&   pip3 install setuptools-rust cryptography pyyaml pygithub gitpython
/bin/sh: line 1: pip3: command not found
```

**Pull request closed without merging**
