### PR TITLE
Fix ironic images prevalidation jobs

### PR DESCRIPTION
**Pull request by elfosardo**
Remove and refactor some parts to simplify configuration especially for
prevalidation jobs.

### CODE REVIEW

**Comment by hardys** [comment]
lgtm and the 4.7 rehearse job failure seems unrelated, but rechecked so we can hopefully get that green, just to make sure.

**Comment by andfasano** [comment]
@elfosardo the prevalidation job failed due a timeout could be related?

**Comment by andfasano** [comment]
> @elfosardo the prevalidation job failed due a timeout could be related?

Ok seems not

**Review by bfournie — APPROVED** [review]

**Pull request merged**
