### PR TITLE
Use operator directive under the PAO jobs

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
Probably it will not work because we use `oc` command under `make functests`(`cluster-label-worker-cnf`).

**Comment by cynepco3hahue** [comment]
so we should create a Dockerfile similar to the HCO one - https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/deploy/Dockerfile.src.ci

**Comment by cynepco3hahue** [comment]
@fromanirh @yanirq Can you please review?

**Review by fromanirh — COMMENTED** [review]
/lgtm

**Comment by fromanirh** [comment]
> /lgtm

this was just because I failed to refresh the github page

**Pull request merged**
