### PR TITLE
[WIP]debug ocp-68660

### PR DESCRIPTION
**Pull request by ShudiLi**

### CODE REVIEW

**Comment by ShudiLi** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.16-installer-rehearse-debug

**Comment by ShudiLi** [comment]
/pj-rehearse pull-ci-openshift-cluster-network-operator-release-4.16-e2e-vsphere-ovn

**Comment by ShudiLi** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.16-installer-rehearse-debug

**Comment by ShudiLi** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.16-installer-rehearse-debug

**Comment by lihongan** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.16-installer-rehearse-debug

**Comment by ShudiLi** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.16-installer-rehearse-debug

**Comment by ShudiLi** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.16-installer-rehearse-debug

**Pull request closed without merging**
