### PR TITLE
kubernetes-autoscaler: add lint, vet, fmt tests.

### PR DESCRIPTION
**Pull request by michaelgugino**

### CODE REVIEW

**Comment by petr-muller** [comment]
Hm, when at it, can you please fix https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/kubernetes-autoscaler/OWNERS so it contains openshift people like https://github.com/openshift/release/blob/master/ci-operator/config/openshift/kubernetes-autoscaler/OWNERS does, so that you do not need top-level approvers for your stuff?

**Comment by paulfantom** [comment]
Seems like I did only partial sync and OWNERS in `ci-operator/config/...` is ok, but one in `ci-operator/jobs/...` is not. @michaelgugino could you fix it in this PR?

**Comment by petr-muller** [comment]
It can be a separate PR too, I don't mind :)

**Comment by paulfantom** [comment]
If you say so: https://github.com/openshift/release/pull/3265 :smile:

**Pull request merged**
