### PR TITLE
Remove jobs using equinix profile

### PR DESCRIPTION
**Pull request by derekhiggins**
These jobs were recently added and use the equinix profile
to provide a baremetal host. This profile is only intended to run
CI jobs for baremetal ipi and we are under a lot of pressure to reduce
it usage(and remove all workloads off equinix). Remove these jobs as
they represent about 12% of our usage.

### CODE REVIEW

**Comment by derekhiggins** [comment]
pinging OWNERS @giuseppe @haircommander @kolyshkin @mrunalp @nalind @saschagrunert @umohnani8 @vrothberg
Can we remove these (or can you find an alternative? ) it long to me that these jobs are not ipi related but are using the ipi equinix profile which is way over subscribed.

**Comment by saschagrunert** [comment]
cc @wgahnagl @rphillips, can we remove those jobs?

**Comment by haircommander** [comment]
we do have plans of migrating these jobs to gcp, but we have not yet done so. we will need them until we do. I would say in a sprint or two we can remove them. Is that a reasonable timeline @derekhiggins

**Comment by derekhiggins** [comment]
> we do have plans of migrating these jobs to gcp, but we have not yet done so. we will need them until we do. I would say in a sprint or two we can remove them. Is that a reasonable timeline @derekhiggins

I'll find out but I'm under a lot of pressure to eliminate almost all of the usage on this account ASAP.

**Comment by derekhiggins** [comment]
> > we do have plans of migrating these jobs to gcp, but we have not yet done so. we will need them until we do. I would say in a sprint or two we can remove them. Is that a reasonable timeline @derekhiggins
> 
> I'll find out but I'm under a lot of pressure to eliminate almost all of the usage on this account ASAP.

Migrating would be great as soon as possible, in the meantime anything that could be done to reduce usage would be appreciated e.g. consolidating jobs ?

**Comment by derekhiggins** [comment]
No longer needed, jobs migrated to gcp https://github.com/openshift/release/pull/30733
thanks.

**Pull request closed without merging**
