### PR TITLE
WIP: Onboard Service Binding Operator on ROSA Classic

### PR DESCRIPTION
**Pull request by Sau1506mya**
Link for JIRA : [LPTOCPCI-846](https://issues.redhat.com/browse/LPTOCPCI-846)

### CODE REVIEW

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-ocp4.15-lp-rosa-classic-acceptance-lp-rosa-classic

**Comment by sadlerap** [comment]
/pj-rehearse periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-ocp4.15-lp-rosa-classic-acceptance-lp-rosa-classic

**Comment by Sau1506mya** [comment]
/pj-rehearse periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-ocp4.15-lp-rosa-classic-acceptance-lp-rosa-classic

**Comment by Sau1506mya** [comment]
Job failed as SBO is going to be deprecated and confirmed from PQE. 
So, closing this PR.

**Pull request closed without merging**
