### PR TITLE
Add support of non standard ports (again)

### PR DESCRIPTION
**Pull request by derekhiggins**
Nodes in MOC all share the same Floating IP
with a different PORT for both ssh and squid

### CODE REVIEW

**Comment by derekhiggins** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-ovn-ipv6 periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-sdn-bm periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-ovn-dualstack periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-serial-ovn-dualstack pull-ci-openshift-installer-master-e2e-agent-compact-ipv4 pull-ci-openshift-installer-master-e2e-agent-sno-ipv6 pull-ci-openshift-assisted-service-release-ocm-2.10-e2e-ai-operator-ztp periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-agent-connected-ipv4-metal3-conformance

**Comment by derekhiggins** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-mce-agent-connected-ipv4-metal3-conformance periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-serial-ovn-dualstack

**Comment by andfasano** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-agent-compact-ipv4

**Pull request merged**
