### PR TITLE
Fix prevalidation repositories for OCP 4.8

### PR DESCRIPTION
**Pull request by elfosardo**
Also properly name the prevalidation repos for 4.6 and 4.7

### CODE REVIEW

**Comment by elfosardo** [comment]
@jupierce @smarterclayton please have a look at this ASAP this is blocking the ironic images CI for 4.8

**Comment by sosiouxme** [comment]
/approve
(don't think it will let me though)

**Comment by sosiouxme** [comment]
heh, shows what i know.

**Pull request merged**
