### PR TITLE
SRVKE-913 Use pooled clusters for Eventing CI on OCP 4.8

### PR DESCRIPTION
**Pull request by mgencur**
https://issues.redhat.com/browse/SRVKE-913

The updates got generators on openshift/knative-eventing side are available in TBD.

### CODE REVIEW

**Comment by mgencur** [comment]
@matzew The ci config generator is updated in https://github.com/openshift/knative-eventing/pull/1384

**Comment by mgencur** [comment]
Reported the reconciler-test failure as https://issues.redhat.com/browse/SRVKE-918 , it was in several PRs already.

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by mgencur** [comment]
/hold cancel

The release-next won't pass until the scripts are on that branch. Maybe tomorrow. Right now they're only on main branch of knative-eventing.

**Pull request merged**
