### PR TITLE
STOR 1129: Add vsphere upgrade job with some Pods that use PVs

### PR DESCRIPTION
**Pull request by jsafrane**
OCP 4.13 enables CSI migration and we want to make sure that upgrade from 4.12 does not break any workloads that use storage.

The job creates 50 1-replica StatefulSets and expects they survive upgrade to 4.13.

CSI migration on vSphere is a complex process, therefore I'd like to run this job relatively often during 4.13 development. It can drop to once per week after 4.13 GA. 

cc @openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
Added more debug dumps in each step to diagnose potential errors

**Comment by jsafrane** [comment]
Now it's perfect & debuggable.

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Pull request merged**
