### PR TITLE
bug fix duplicate repo clone

### PR DESCRIPTION
**Pull request by vishnuchalla**
### Description
Bug fix on duplicate cloning of the e2e repo. Checked and verified it in a hacky way by doing a `ls` which inidcated that the repo already had e2e source code in it. But the only thing the we need to make sure is that, if it is able to clone PR specific changes. It should ideally be the case as the others use it same way, but it can only be verified through e2e once this PR is merged.

### Testing
Tested and verified in by adding some commands in PROW scripts.
```
+ pwd
/e2e
+ ls -lhart
total 28K
drwxrwxr-x. 20 root root 4.0K Feb 15 15:35 workloads
drwxrwxr-x.  5 root root 4.0K Feb 15 15:35 utils
drwxrwxr-x.  2 root root   24 Feb 15 15:35 prow
drwxrwxr-x.  2 root root   78 Feb 15 15:35 ci
-rw-rw-r--.  1 root root  136 Feb 15 15:35 README.md
-rw-rw-r--.  1 root root  12K Feb 15 15:35 LICENSE
-rw-rw-r--.  1 root root   42 Feb 15 15:35 .gitignore
drwxrwxr-x.  3 root root   28 Feb 15 15:35 .github
drwxrwxr-x.  8 root root  162 Feb 15 15:35 .git
drwxr-xr-x.  8 root root  135 Feb 15 15:36 .
dr-xr-xr-x.  1 root root   79 Feb 15 19:54 ..
++ whoami
+ echo 'Current user: 1004360000'
Current user: 1004360000
+ git clone https://github.com/cloud-bulldozer/e2e-benchmarking
fatal: could not create work tree dir 'e2e-benchmarking': Permission denied
```
Also verified on perms with this [sample run](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/48871/rehearse-48871-pull-ci-cloud-bulldozer-e2e-benchmarking-master-e2e-cluster-density-v2-single-node/1758307633053306880/artifacts/e2e-cluster-density-v2-single-node/cloud-bulldozer-e2e-benchmarking-cluster-density-v2/build-log.txt).

### CODE REVIEW

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-cloud-bulldozer-e2e-benchmarking-master-e2e-cluster-density-v2-single-node

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-cloud-bulldozer-e2e-benchmarking-master-e2e-cluster-density-v2-single-node

**Comment by vishnuchalla** [comment]
/pj-rehearse pull-ci-cloud-bulldozer-e2e-benchmarking-master-e2e-cluster-density-v2-single-node

**Review by krishvoor — APPROVED** [review]
/lgtm

**Pull request merged**
