### PR TITLE
Add MCE publish jobs for cluster api provider kubevirt

### PR DESCRIPTION
**Pull request by davidvossel**
This creates capk publish jobs for mce

### CODE REVIEW

**Comment by davidvossel** [comment]
/assign @bparees

@bparees I changed the names of some of our container images here in order to align with the convention other similar cluster api provider images are using. openshift-ci bot says this change needs your approval

**Comment by bparees** [comment]
/approve

thanks for cleaning up the names

**Review by gurnben — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
