### PR TITLE
Release controller generator refactor

### PR DESCRIPTION
**Pull request by bradmwilliams**
Refactoring the release-controller generator to separate the changes that go to `api.ci` and `app.ci` and adding support for the "origin" resources that we've been carrying around manually.  I've also added the one Role that was missing, post-migration, for the origin release-controller.

### CODE REVIEW

**Review by petr-muller — APPROVED** [review]
/hold

LGTM, holding if Steve wants to have a look

**Review by stevekuznetsov — APPROVED** [review]

**Pull request merged**
