### PR TITLE
chore(RHIDP-461): Add jobs to run MVP scenario

### PR DESCRIPTION
**Pull request by pmacik**

### CODE REVIEW

**Comment by pmacik** [comment]
/pj-rehears pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp

**Review by yogananth-subramanian — APPROVED** [review]

**Comment by pmacik** [comment]
Depends on #47801

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp  pull-ci-redhat-performance-backstage-performance-main-mvp-scalability pull-ci-redhat-performance-backstage-performance-main-mvp-resources-scalability

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp pull-ci-redhat-performance-backstage-performance-main-mvp-resources-scalability pull-ci-redhat-performance-backstage-performance-main-mvp-scalability

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp pull-ci-redhat-performance-backstage-performance-main-mvp-resources-scalability pull-ci-redhat-performance-backstage-performance-main-mvp-scalability

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp pull-ci-redhat-performance-backstage-performance-main-mvp-resources-scalability pull-ci-redhat-performance-backstage-performance-main-mvp-scalability

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp-scalability

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp-scalability

**Comment by pmacik** [comment]
/pj-rehearse pull-ci-redhat-performance-backstage-performance-main-mvp pull-ci-redhat-performance-backstage-performance-main-mvp-resources-scalability

**Review by yogananth-subramanian — APPROVED** [review]

**Pull request merged**
