### PR TITLE
Changing io tests xml generation dir

### PR DESCRIPTION
**Pull request by JoaoFula**
Changing the dir where we generate the xml pytest report so that it's picked up by the sessionfinish fixture to send the report to report portal

### CODE REVIEW

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-openshift-insights-operator-master-insights-operator-e2e-tests

**Review by ncaak — APPROVED** [review]
/lgtm

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-openshift-insights-operator-master-insights-operator-e2e-tests

**Comment by smg247** [comment]
/pj-rehearse pull-ci-openshift-insights-operator-master-insights-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-openshift-insights-operator-master-insights-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse ci/rehearse/openshift/insights-operator/master/insights-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-openshift-insights-operator-master-insights-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-openshift-insights-operator-master-insights-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-openshift-insights-operator-master-insights-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-openshift-insights-operator-master-insights-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-openshift-insights-operator-master-insights-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-openshift-insights-operator-master-insights-operator-e2e-tests

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-openshift-insights-operator-master-insights-operator-e2e-tests

**Comment by JoaoFula** [comment]
https://reportportal-smqe.apps.ocp-c1.prod.psi.redhat.com/ui/#ccx/dashboard/1658 
job uploaded to report portal successfully

**Review by ncaak — APPROVED** [review]
/lgtm

**Pull request merged**
