### PR TITLE
Adjust ghproxy tokens alerts to the upstream impl

### PR DESCRIPTION
**Pull request by jmguzik**
Signed-off-by: Jakub Guzik <jguzik@redhat.com>

### CODE REVIEW

**Comment by jmguzik** [comment]
/cc @smg247 @danilo-gemoli 
@danilo-gemoli please check if in line with your implementation.

**Comment by jmguzik** [comment]
Ups, error :)

**Comment by jmguzik** [comment]
Should be ok now :)

**Review by danilo-gemoli — APPROVED** [review]

**Pull request merged**
