### PR TITLE
RFE-6242: add an optional OpenStack job to cluster-ingress-operator

### PR DESCRIPTION
**Pull request by EmilienM**
We didn't have a job and we want to be able to run one to test our PRs.

### CODE REVIEW

**Comment by EmilienM** [comment]
/pj-rehearse pull-ci-openshift-cluster-ingress-operator-master-e2e-openstack-ovn

**Comment by Miciah** [comment]
@EmilienM, is there a Jira ticket that the PR and commit message should reference?

**Comment by EmilienM** [comment]
> @EmilienM, could you also add an e2e-openstack-operator test to run the openshift/cluster-ingress-operator repository's E2E suite?

I don't think we need two OpenStack jobs for presubmit. So if you prefer I could run e2e-openstack-operator instead of the proposed one?
I'll try it and see how it works.

**Comment by EmilienM** [comment]
/pj-rehearse pull-ci-openshift-cluster-ingress-operator-master-e2e-openstack-operator

**Comment by EmilienM** [comment]
@Miciah running CIO e2e failed on OpenStack:

```panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1a774eb]

goroutine 11358 [running]:
testing.tRunner.func1.2({0x1d3d600, 0x3428a50})
	/usr/lib/golang/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
	/usr/lib/golang/src/testing/testing.go:1634 +0x377
panic({0x1d3d600?, 0x3428a50?})
	/usr/lib/golang/src/runtime/panic.go:770 +0x132
github.com/openshift/cluster-ingress-operator/test/e2e.updateDNSConfig(...)
	/go/src/github.com/openshift/cluster-ingress-operator/test/e2e/dns_ingressdegrade_test.go:89
github.com/openshift/cluster-ingress-operator/test/e2e.TestIngressStatus(0xc000511380)
	/go/src/github.com/openshift/cluster-ingress-operator/test/e2e/dns_ingressdegrade_test.go:53 +0x34b
testing.tRunner(0xc000511380, 0x218c9f8)
	/usr/lib/golang/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 11200
	/usr/lib/golang/src/testing/testing.go:1742 +0x390
FAIL	github.com/openshift/cluster-ingress-operator/test/e2e	1612.553s
FAIL
make: *** [Makefile:56: test-e2e] Error 1
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1a774eb]

goroutine 11358 [running]:
testing.tRunner.func1.2({0x1d3d600, 0x3428a50})
	/usr/lib/golang/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
	/usr/lib/golang/src/testing/testing.go:1634 +0x377
panic({0x1d3d600?, 0x3428a50?})
	/usr/lib/golang/src/runtime/panic.go:770 +0x132
github.com/openshift/cluster-ingress-operator/test/e2e.updateDNSConfig(...)
	/go/src/github.com/openshift/cluster-ingress-operator/test/e2e/dns_ingressdegrade_test.go:89
github.com/openshift/cluster-ingress-operator/test/e2e.TestIngressStatus(0xc000511380)
	/go/src/github.com/openshift/cluster-ingress-operator/test/e2e/dns_ingressdegrade_test.go:53 +0x34b
testing.tRunner(0xc000511380, 0x218c9f8)
	/usr/lib/golang/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 11200
	/usr/lib/golang/src/testing/testing.go:1742 +0x390
FAIL	github.com/openshift/cluster-ingress-operator/test/e2e	1612.553s
FAIL
make: *** [Makefile:56: test-e2e] Error 1panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1a774eb]

goroutine 11358 [running]:
testing.tRunner.func1.2({0x1d3d600, 0x3428a50})
	/usr/lib/golang/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
	/usr/lib/golang/src/testing/testing.go:1634 +0x377
panic({0x1d3d600?, 0x3428a50?})
	/usr/lib/golang/src/runtime/panic.go:770 +0x132
github.com/openshift/cluster-ingress-operator/test/e2e.updateDNSConfig(...)
	/go/src/github.com/openshift/cluster-ingress-operator/test/e2e/dns_ingressdegrade_test.go:89
github.com/openshift/cluster-ingress-operator/test/e2e.TestIngressStatus(0xc000511380)
	/go/src/github.com/openshift/cluster-ingress-operator/test/e2e/dns_ingressdegrade_test.go:53 +0x34b
testing.tRunner(0xc000511380, 0x218c9f8)
	/usr/lib/golang/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 11200
	/usr/lib/golang/src/testing/testing.go:1742 +0x390
FAIL	github.com/openshift/cluster-ingress-operator/test/e2e	1612.553s
FAIL
make: *** [Makefile:56: test-e2e] Error 1
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1a774eb]

goroutine 11358 [running]:
testing.tRunner.func1.2({0x1d3d600, 0x3428a50})
	/usr/lib/golang/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
	/usr/lib/golang/src/testing/testing.go:1634 +0x377
panic({0x1d3d600?, 0x3428a50?})
	/usr/lib/golang/src/runtime/panic.go:770 +0x132
github.com/openshift/cluster-ingress-operator/test/e2e.updateDNSConfig(...)
	/go/src/github.com/openshift/cluster-ingress-operator/test/e2e/dns_ingressdegrade_test.go:89
github.com/openshift/cluster-ingress-operator/test/e2e.TestIngressStatus(0xc000511380)
	/go/src/github.com/openshift/cluster-ingress-operator/test/e2e/dns_ingressdegrade_test.go:53 +0x34b
testing.tRunner(0xc000511380, 0x218c9f8)
	/usr/lib/golang/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 11200
	/usr/lib/golang/src/testing/testing.go:1742 +0x390
FAIL	github.com/openshift/cluster-ingress-operator/test/e2e	1612.553s
FAIL
make: *** [Makefile:56: test-e2e] Error 1
```

**Comment by EmilienM** [comment]
Fixing it here: https://github.com/openshift/cluster-ingress-operator/pull/1153

**Comment by Miciah** [comment]
Thanks!
/lgtm

**Comment by EmilienM** [comment]
let's merge it so we can test https://github.com/openshift/cluster-ingress-operator/pull/1153 on OpenStack !

**Pull request merged**
