### PR TITLE
odf-console: move CI to 4.15

### PR DESCRIPTION
**Pull request by alfonsomthd**

### CODE REVIEW

**Comment by alfonsomthd** [comment]
/pj-rehearse pull-ci-red-hat-storage-odf-console-master-odf-console-e2e-aws

**Comment by alfonsomthd** [comment]
/pj-rehearse pull-ci-red-hat-storage-odf-console-release-4.15-odf-console-e2e-aws

**Comment by alfonsomthd** [comment]
/pj-rehearse pull-ci-red-hat-storage-odf-console-master-odf-console-e2e-aws

**Comment by SanjalKatiyar** [comment]
/pj-rehearse pull-ci-red-hat-storage-odf-console-master-odf-console-e2e-aws

**Comment by SanjalKatiyar** [comment]
/pj-rehearse pull-ci-red-hat-storage-odf-console-release-4.15-odf-console-e2e-aws

**Comment by alfonsomthd** [comment]
/pj-rehearse pull-ci-red-hat-storage-odf-console-master-odf-console-e2e-aws

**Comment by alfonsomthd** [comment]
/pj-rehearse pull-ci-red-hat-storage-odf-console-release-4.15-odf-console-e2e-aws

**Comment by alfonsomthd** [comment]
/pj-rehearse pull-ci-red-hat-storage-odf-console-release-4.15-odf-console-e2e-aws

**Comment by bipuladh** [comment]
/pj-rehearse pull-ci-red-hat-storage-odf-console-release-4.15-odf-console-e2e-aws

**Comment by alfonsomthd** [comment]
@hongkailiu Can you please merge this?

**Pull request merged**
