### PR TITLE
Enable featuregate GCP workflow as gcp-ipi-proxy-techpreview

### PR DESCRIPTION
**Pull request by miyadav**
@sunzhaohua2 @huali9 @jhou1 PTAL , raising a fresh PR as old one , had many merges ( due to lot of changes in same files , wanted to avoid difficulties for us)

cc @jiajliu

### CODE REVIEW

**Comment by jianlinliu** [comment]
Shall we remove cucushift-installer-rehearse-gcp-ipi-capi now, right?

**Comment by jianlinliu** [comment]
@jianli-wei per https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/30042/rehearse-30042-periodic-ci-openshift-verification-tests-master-installer-rehearse-4.11-installer-rehearse-gcp-techpreview/1542738117423796224, seem like `n2-standard-1` is removed from gcloud ?

**Comment by jianli-wei** [comment]
> @jianli-wei per https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/30042/rehearse-30042-periodic-ci-openshift-verification-tests-master-installer-rehearse-4.11-installer-rehearse-gcp-techpreview/1542738117423796224, seem like `n2-standard-1` is removed from gcloud ?

Yes, it seems so. 
```
$ gcloud compute regions describe us-central1 | grep zones: -A5
zones:
- https://www.googleapis.com/compute/v1/projects/openshift-qe/zones/us-central1-a
- https://www.googleapis.com/compute/v1/projects/openshift-qe/zones/us-central1-b
- https://www.googleapis.com/compute/v1/projects/openshift-qe/zones/us-central1-c
- https://www.googleapis.com/compute/v1/projects/openshift-qe/zones/us-central1-f
$ gcloud compute machine-types list --zones us-central1-a | grep "n2-standard-1\s"
$ gcloud compute machine-types list --zones us-central1-b | grep "n2-standard-1\s"
$ gcloud compute machine-types list --zones us-central1-c | grep "n2-standard-1\s"
$ gcloud compute machine-types list --zones us-central1-f | grep "n2-standard-1\s"
$

**Comment by jianlinliu** [comment]
> > @jianli-wei per https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/30042/rehearse-30042-periodic-ci-openshift-verification-tests-master-installer-rehearse-4.11-installer-rehearse-gcp-techpreview/1542738117423796224, seem like `n2-standard-1` is removed from gcloud ?
> 
> Yes, it seems so.
Can you help prepare a new PR to fix that? or maybe you can suggest @miyadav to do some change in this PR directly to shorten the fix process.

**Comment by miyadav** [comment]
Thanks @jianlinliu , @jianli-wei  Are you opening up a helper PR for this  issue ? Let me know if I shall put a hold on this till then?

**Comment by jianli-wei** [comment]
> Thanks @jianlinliu , @jianli-wei Are you opening up a helper PR for this issue ? Let me know if I shall put a hold on this till then?

Sorry, I did nothing. Suggest to update in this PR. Thanks!

**Comment by jianlinliu** [comment]
> Shall we remove cucushift-installer-rehearse-gcp-ipi-capi now, right?

Any update for this?

**Comment by jianlinliu** [comment]
btw, pls squash multiple commits into one.

**Comment by miyadav** [comment]
> > Shall we remove cucushift-installer-rehearse-gcp-ipi-capi now, right?
> 
> Any update for this?

@jianlinliu ,  Yes removed it. Thanks .

**Comment by huali9** [comment]
Validate passed.
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/30042/rehearse-30042-periodic-ci-openshift-verification-tests-master-installer-rehearse-4.10-installer-rehearse-gcp/1543796555415293952
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/30042/rehearse-30042-periodic-ci-openshift-verification-tests-master-installer-rehearse-4.11-installer-rehearse-gcp/1543796555192995840

/lgtm

**Pull request merged**
