### PR TITLE
WINC-1092: [winc] Remove AWS jobs on 4.10

### PR DESCRIPTION
**Pull request by saifshaikh48**
This PR removes the AWS jobs since AWS has removed the `-Containers*` Windows Server 2019 images. These came with docker pre-installed, which was a pre-requisite on 4.10. 2019 is the only supported Windows version on WMCO 5.x.

The AWS upgrade job was migrated to run on vSphere instead.

Ran `make update`

### CODE REVIEW

**Comment by saifshaikh48** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.10-vsphere-e2e-upgrade

**Comment by saifshaikh48** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.10-vsphere-e2e-upgrade

**Comment by saifshaikh48** [comment]
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.10-vsphere-e2e-upgrade

**Review by aravindhp — APPROVED** [review]

**Pull request merged**
