### PR TITLE
Add presubmit command to force GPU Operator test on OCP 4.7

### PR DESCRIPTION
**Pull request by kpouget**

### CODE REVIEW

**Comment by kpouget** [comment]
@omertuc this PR can be merged, the rehearsal failure is expected as 4.7 nightly is currently broken

this PR allows triggering  GPU Operator on OCP 4.7 testing from a PR.

**Comment by omertuc** [comment]
/lgtm

but I have no power here

**Comment by kpouget** [comment]
@omertuc seems like you can `\lgtm` :)

thanks!

\hold cancel

**Pull request merged**
