### PR TITLE
openstack-tests: Add the base images to Installer

### PR DESCRIPTION
**Pull request by pierreprinetti**
This is a prerequisite for changing the OpenStack workflows to include openstack-tests.

### CODE REVIEW

**Comment by pierreprinetti** [comment]
/assign @jstuever
as the bot suggests.

**Review by mandre — COMMENTED** [review]
/lgtm

**Comment by jhixson74** [comment]
/approve
/lgtm

This LGTM, I am not sure if I can approve, but am doing so anyway ;-)

**Pull request merged**
