### PR TITLE
Bug 1942764: ci-operator/templates: Use LEASED_RESOURCE for upi-e2e

### PR DESCRIPTION
**Pull request by mtnbikenc**
Leases are being acquired for other regions however the template was
hard coded to a single region.

### CODE REVIEW

**Comment by mtnbikenc** [comment]
Confirmed the [e2e-aws-upi job](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/18722/rehearse-18722-pull-ci-openshift-installer-master-e2e-aws-upi/1395377156036497408) obtained a lease in `us-east-2` and created the cluster in `us-east-2`.

**Comment by mtnbikenc** [comment]
@staebler This bug is for e2e-aws but the same thing is happening for azure.  Should I attempt to also fix azure or open another bug?  The azure region is randomly selected in the [code](https://github.com/openshift/release/blob/268a9afd63eaf09133398465533458ecbc96aeeb/ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml#L1248-L1260).

```
[36mINFO[0m[2021-05-20T14:06:59Z] Acquiring leases for test e2e-azure-upi      
[36mINFO[0m[2021-05-20T14:06:59Z] Acquired 1 lease(s) for azure4-quota-slice: [westus--azure4-quota-slice-0] 
[36mINFO[0m[2021-05-20T14:06:59Z] Executing template e2e-azure-upi             
[36mINFO[0m[2021-05-20T14:59:11Z] Logs for container setup in pod e2e-azure-upi: 
[36mINFO[0m[2021-05-20T14:59:11Z] Installing from release registry.build01.ci.openshift.org/ci-op-q6sf31r3/release@sha256:f3a2f724b1d53c971d096220e8f9c72381b159138f754e7348614a356f555e3c 
[36mINFO[0m[2021-05-20T14:59:11Z] Azure region: centralus
```

**Comment by staebler** [comment]
> @staebler This bug is for e2e-aws but the same thing is happening for azure. Should I attempt to also fix azure or open another bug? The azure region is randomly selected in the [code](https://github.com/openshift/release/blob/268a9afd63eaf09133398465533458ecbc96aeeb/ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml#L1248-L1260).
> 
> ```
> �[36mINFO�[0m[2021-05-20T14:06:59Z] Acquiring leases for test e2e-azure-upi      
> �[36mINFO�[0m[2021-05-20T14:06:59Z] Acquired 1 lease(s) for azure4-quota-slice: [westus--azure4-quota-slice-0] 
> �[36mINFO�[0m[2021-05-20T14:06:59Z] Executing template e2e-azure-upi             
> �[36mINFO�[0m[2021-05-20T14:59:11Z] Logs for container setup in pod e2e-azure-upi: 
> �[36mINFO�[0m[2021-05-20T14:59:11Z] Installing from release registry.build01.ci.openshift.org/ci-op-q6sf31r3/release@sha256:f3a2f724b1d53c971d096220e8f9c72381b159138f754e7348614a356f555e3c 
> �[36mINFO�[0m[2021-05-20T14:59:11Z] Azure region: centralus
> ```

Let's fix it here.

**Comment by mtnbikenc** [comment]
Updated to include `AZURE_REGION`.

**Comment by staebler** [comment]
Azure change looks good, too.
/lgtm
```
[36mINFO[0m[2021-05-21T13:30:46Z] Acquiring leases for test e2e-azure-upi      
[36mINFO[0m[2021-05-21T13:30:47Z] Acquired 1 lease(s) for azure4-quota-slice: [eastus--azure4-quota-slice-4] 
```
followed later by
```

Azure region: eastus
```

**Pull request merged**
