### PR TITLE
move cloud team long duration jobs to multi clusters

### PR DESCRIPTION
**Pull request by sunzhaohua2**
@miyadav @huali9 PTAL

### CODE REVIEW

**Comment by huali9** [comment]
better run one
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.15-multi-nightly-aws-ipi-disc-amd-mixarch-f28-longduration-cloud

**Comment by huali9** [comment]
the result looks good.

**Comment by sunzhaohua2** [comment]
close this, new pr https://github.com/openshift/release/pull/47076

**Pull request closed without merging**
