### PR TITLE
change zone in dedicatedhost test on 4.12

### PR DESCRIPTION
**Pull request by MayXuQQ**
debug the failure of periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-ibmcloud-ipi-dedicatedhost-static-f28

### CODE REVIEW

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.12-installer-rehearse-ibmcloud

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.12-installer-rehearse-ibmcloud

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-ibmcloud-ipi-dedicatedhost-static-f28

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.12-installer-rehearse-ibmcloud

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-ibmcloud-ipi-dedicatedhost-static-f28

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.12-installer-rehearse-ibmcloud

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-ibmcloud-ipi-dedicatedhost-static-f28

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-ibmcloud-ipi-dedicatedhost-static-f28

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-ibmcloud-ipi-dedicatedhost-static-f28

**Comment by MayXuQQ** [comment]
@jianlinliu could you help review, change the zone to "2", to fix the failure in https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/job-history/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-ibmcloud-ipi-dedicatedhost-static-f28
thanks a lot

**Comment by jianlinliu** [comment]
cc @liangxia to review

**Pull request merged**
