### PR TITLE
OCPQE-18638: Add upgrade job for automated release

### PR DESCRIPTION
**Pull request by liangxia**

### CODE REVIEW

**Comment by JianLi-RH** [comment]
what does `automated-release-stable` in the file name mean? Can you please describe it in the README.md file?

**Comment by liangxia** [comment]
> what does `automated-release-stable` in the file name mean? Can you please describe it in the README.md file?

`automated-release` jobs are used to collect data to get prepared for the upcoming real automated release. Those are the trial jobs, used to collect job/cases pass/fail ratios. It's not the final decision, you can see we only add one job for e2e (weeks ago and already merged) and another one for upgrade (in this PR). You can get more context in the linked jira issue.

**Pull request merged**
