### PR TITLE
edge ecosystem ci-artifacts: Added tests

### PR DESCRIPTION
**Pull request by sagidayan**
/cc @mkowalski 
/cc @kpouget

### CODE REVIEW

**Comment by kpouget** [comment]
seems good to me,
just double check if you're sure you want `gpu-operator-e2e` to `always_run: true`

for this erro:
>    * could not run steps: step test-commit failed: failed to create credentials: could not read source credential: secrets "nvidia-ci-secrets" is forbidden: User "system:serviceaccount:ci:ci-operator" cannot get resource "secrets" in API group "" in the namespace "edge-group" 

I think you want to revert 

> namespace: edge-group

to

> namespace: test-credentials

I think we don't have control over this value

**Comment by kpouget** [comment]
```

2022-01-10 14:32:12,896 p=86 u=edge-ci-runner n=ansible | roles/gpu_operator_bundle_from_commit/tasks/build_bundle.yml:18
2022-01-10 14:32:12,896 p=86 u=edge-ci-runner n=ansible | TASK: gpu_operator_bundle_from_commit : Ensure that quay secret file path is set
2022-01-10 14:32:12,896 p=86 u=edge-ci-runner n=ansible | ----- FAILED ----
2022-01-10 14:32:12,896 p=86 u=edge-ci-runner n=ansible | msg: non-zero return code
2022-01-10 14:32:12,896 p=86 u=edge-ci-runner n=ansible | 
2022-01-10 14:32:12,896 p=86 u=edge-ci-runner n=ansible | <command> test -f /var/run/nvidia-ci-secrets/openshift-psap-openshift-ci-secret.yml
```

error must from from the top script (`gpu-operator.sh`):

```
+ GPU_OPERATOR_QUAY_BUNDLE_PUSH_SECRET=/var/run/nvidia-ci-secrets/openshift-psap-openshift-ci-secret.yml
```

but this is independent of this PR, this one worked as expected I think

entitlement was validated:

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/25085/rehearse-25085-pull-ci-rh-ecosystem-edge-ci-artifacts-master-gpu-operator-e2e/1480534909746417664/artifacts/gpu-operator-e2e/presubmit-operatorhub/artifacts/003__entitlement__wait/entitlement-test.pod.log

(I didn't disable it yet when deploying from OperatorHub)

**Review by mkowalski — APPROVED** [review]

**Pull request merged**
