### PR TITLE
[WIP][Temp][Storage-Az-HCP cluster]

### PR DESCRIPTION
**Pull request by ropatil010**
AZ HCP cluster creation

### CODE REVIEW

**Comment by ropatil010** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-azure-ipi-ovn-hypershift-install-f28

**Comment by gangwgr** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-vsphere-agent-ha-f14

**Comment by ropatil010** [comment]
/pj-rehearse-[periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-baremetal-3-plus-1-agent-ipv4-static-f14

**Comment by ropatil010** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-ovn-ipsec-amd-mixarch-f28-destructive

**Comment by gangwgr** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-ovn-ipsec-amd-mixarch-f28-destructive

**Comment by gangwgr** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-ovn-ipsec-amd-mixarch-f28-destructive

**Comment by ropatil010** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-aws-ipi-ovn-ipsec-amd-mixarch-f28-destructive

**Comment by ropatil010** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-aws-sc2s-ipi-disconnected-private-fips-f14

**Comment by ropatil010** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-aws-sc2s-ipi-disconnected-private-fips-f14

**Comment by gangwgr** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-aws-sc2s-ipi-disconnected-private-fips-f14

**Comment by ropatil010** [comment]
Closing

**Pull request closed without merging**
