### PR TITLE
Running knative-eventing/sources against OCP4

### PR DESCRIPTION
**Pull request by matzew**
Regenerated the config for Knative Eventng/Sources master branch. The only diff with the 0.3 branch for now is the promotion's name.

### CODE REVIEW

**Comment by mgencur** [comment]
Hi Matthias, the current changes look good but you also need to re-generate the Prow jobs using a "docker run" command and commit those as well. The command is as follows:
`docker run -it -v “$(pwd)/ci-operator:/ci-operator:z”         \
  registry.svc.ci.openshift.org/ci/ci-operator-prowgen:latest \
    --from-dir /ci-operator/config --to-dir /ci-operator/jobs
`

**Comment by mgencur** [comment]
I think this looks good. I don't know why the remaining tests fail. @petr-muller can you advise, please?

**Comment by petr-muller** [comment]
> I think this looks good. I don't know why the remaining tests fail. @petr-muller can you advise, please? Especially the correctly-sharded-config

The images rehearsal fails for a reason that seems like some misconfiguration in the build config, a `k8sevents` file does not seem to be found where expected:

```
2019/03/21 12:19:14 Build knative-eventing-test-k8sevents failed, printing logs:
Pulling image "docker-registry.default.svc:5000/ci-op-hkvbd983/pipeline@sha256:7f7defdd09a6414e210d69be25baba104e3e23010dd467bad512f695f13c31ab" ...
error: error copying source path /go/bin/k8sevents to .: API error (404): {"message":"lstat /var/lib/docker/overlay2/2d53da93e25f581b9f6ff110141b94bbe86c3603494e56001bafa1cb622a448f/merged/go/bin/k8sevents: no such file or directory"}
```

`correctly-sharded-config` is a new test - the failures are probably even unrelated to this PR, it looks like some of the checked-in setup is wrong already. It's related to knative, so you can fix it here or in a separate PR.

The test validates all jobs refer to the correct CM shard when they need some ci-operator config. The shards are specified by the CM updater plugin [config](https://github.com/openshift/release/blob/master/cluster/ci/config/prow/plugins.yaml#L636) - based on filename pattern, a shard is selected where the given config file will be placed. The warnings spot cases where a job tries to find some config in a different shard.

Look at the messages:

```
msg="Invalid config map map shard for injected CI-Operator config key." expected=ci-operator-misc-configs got=ci-operator-master-configs job=periodic-ci-openshift-knative-build-release-0.2-e2e key=openshift-knative-build-release-0.2.yaml source-file=ci-operator/jobs/openshift/knative-build/openshift-knative-build-periodics.yaml
msg="Invalid config map map shard for injected CI-Operator config key." expected=ci-operator-misc-configs got=ci-operator-master-configs job=periodic-ci-openshift-knative-eventing-release-0.2-e2e key=openshift-knative-eventing-release-0.2.yaml source-file=ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-periodics.yaml
msg="Invalid config map map shard for injected CI-Operator config key." expected=ci-operator-misc-configs got=ci-operator-master-configs job=periodic-ci-openshift-knative-eventing-sources-release-0.2-e2e key=openshift-knative-eventing-sources-release-0.2.yaml source-file=ci-operator/jobs/openshift/knative-eventing-sources/openshift-knative-eventing-sources-periodics.yaml
msg="Invalid config map map shard for injected CI-Operator config key." expected=ci-operator-misc-configs got=ci-operator-master-configs job=periodic-ci-openshift-knative-serving-release-0.2-e2e key=openshift-knative-serving-release-0.2.yaml source-file=ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-periodics.yaml
```

So for example, the first message warns about [this config](https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/knative-build/openshift-knative-build-periodics.yaml#L78), where the job refers to `openshift-knative-build-release-0.2.yaml` config from `ci-operator-master-configs` CM, but that config would be placed in [ci-operator-misc-configs](https://github.com/openshift/release/blob/master/cluster/ci/config/prow/plugins.yaml#L641).

**Comment by petr-muller** [comment]
Fixing the sharding in https://github.com/openshift/release/pull/3184 to speed up repo fix a little

**Comment by mgencur** [comment]
/lgtm
The E2E tests in the target repository will be fixed soon. They're supposed to fail now because the target master branch hasn't been updated to the desired state. That's a next item on our list.

**Pull request merged**
