### PR TITLE
Add tests for Alibaba Disk CSI driver operator

### PR DESCRIPTION
**Pull request by jsafrane**
CSI driver tests need a YAML manifest with definition of supported features to run openshift-tests binary. This manifest is in the alibaba-disk-csi-driver-operator github repo, but we will need it in tests for other repos (like the driver itself). To be able to find / use the manifest in the other repos, we need to:  
* Distribute the driver test manifest.yaml as image `alibaba-disk-csi-driver-operator-test`.
* Add a step to copy the manifest from the image to `$SHARED_DIR`.
* Add workflow to install a cluster + copy the manifest to `$SHARED_DIR` (via the step above) + run the tests (that already knows where the manifest is in `$SHARED_DIR`.

### CODE REVIEW

**Comment by jsafrane** [comment]
/hold
It's not possible to install a cluster

```
: Run multi-stage test e2e-alibabacloud-disk-csi - e2e-alibabacloud-disk-csi-ipi-conf-alibabacloud container test expand_less | 0s
-- | --
Alibaba region: us-west-2 /bin/bash: line 18: CI_RESOURCE_GROUP_ID: unbound variable
```

**Comment by jsafrane** [comment]
daily check if Aliabab works ;-)
/retest

**Comment by jsafrane** [comment]
The tests fail in `gather-alibabacloud-console` step, which is unrelated to CSI. The same test fails in other Alibaba e2e tests: https://github.com/openshift/installer/pull/5604 / https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_installer/5604/pull-ci-openshift-installer-master-e2e-alibaba/1496424012073406464

**Comment by jsafrane** [comment]
I'm marking the tests as optional until the console is fixed.

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Review by kwoodson — APPROVED** [review]
/lgtm

**Comment by bparees** [comment]
image name looks fine
/approve

**Pull request merged**
