### PR TITLE
kubevirt: ssp: Add job for branch release-v0.12

### PR DESCRIPTION
**Pull request by akrejcir**
A new release branch was created in ssp-operator. This PR adds the branch to CI.

### CODE REVIEW

**Comment by ksimon1** [comment]
@kwiesmueller please use lgtm only after the tests passed, because in this repo lgtm means the same as approve and openshift bot doesn't wait for test results

**Comment by akrejcir** [comment]
I thought the merge would be blocked when I removed the `approved` label.
I will `/hold` next time.

**Pull request merged**
