### PR TITLE
4.3: fips tests are required to promote machine-os-content

### LINKED ISSUE #5853: [RFE] Add FIPS tests to inform the 4.3 promote job
(Not sure if this is the best place to track this, but going to start here)

To ensure that the FIPS enablement work does not regress, we would like to add a test that runs the OpenShift installer with FIPS enabled to the job that promotes the 4.3 `machine-os-content`

I believe the job in question is `release-promote-openshift-machine-os-content-e2e-aws-4.3` and we need a set of tests to validate FIPS works before the job passes.

From @nee1esh 

> The goal is to make sure that when new drop of RHCOS gets promoted into OpenShift a FIPS test is run to ensure
> 1. Node comes-up in FIPS mode post-install.
> 2. maybe in future, cluster comes up in FIPS mode.
> 3. Even better (in the future) if we can run one of the e2e (say AWS e2e) in FIPS mode to make sure nothing is regressing with the new change.
> Main goal is to avoid the regression we had and cover various regression surfaces via this test

I've spoken to @cgwalters and @vrutkovs about possibly helping out with this.

If there are other details that I have missed, please add them in the comments.

cc: @ashcrow

### PR DESCRIPTION
**Pull request by vrutkovs**
Update machine-os-content promotion job with additional test - FIPS on AWS

Fixes #5853

### CODE REVIEW

**Comment by vrutkovs** [comment]
Yes, `--template` supports multipaths, implemeted that. 

Seems promotion would start only when all targets complete, so both tests are expected to pass if I understood correctly

**Comment by cgwalters** [comment]
Hmm.  I'm OK with this but I also feel like if we have:

 - Basic single node FIPS works as an RHCOS test (which @mike-nguyen is working on)
 - Make the existing aws-fips job blocking (easy)

We're in a pretty good place too.

**Comment by petr-muller** [comment]
I thinks this broke the job: https://prow.svc.ci.openshift.org/?job=release-promote-openshift-machine-os-content-e2e-aws-4.3

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-promote-openshift-machine-os-content-e2e-aws-4.3/3989#1:build-log.txt%3A20 says:

```
error: failed to generate secret e2e-aws-fips-cluster-profile: could not read dir /usr/local/e2e-aws-fips-cluster-profile: open /usr/local/e2e-aws-fips-cluster-profile: no such file or directory 
```

**Pull request merged**
