### PR TITLE
add a cluster-scoped-3scale branch

### PR DESCRIPTION
**Pull request by austincunningham**
Add a feature branch for cluster-scoped-3scale

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
@austincunningham we usually tolerate a number of the rehearsals failing, e.g. e2e tests but normally we get the shorter ones passing e.g. format. I see they are all failing so it makes me think that the configuration won't work if the file name doesn't match the branch. the links don't seem to be working for me either so will try retest first..
/test pj-rehearse

**Comment by austincunningham** [comment]
> @austincunningham we usually tolerate a number of the rehearsals failing, e.g. e2e tests but normally we get the shorter ones passing e.g. format. I see they are all failing so it makes me think that the configuration won't work if the file name doesn't match the branch. the links don't seem to be working for me either so will try retest first..

we already have a difference i.e. the branch has to be in lower case `mgdapi-` when created and the file has to be `MGDAPI-` s

**Comment by laurafitzgerald** [comment]
@austincunningham  looks like this wont work as configured. -> `fatal: couldn't find remote ref MGDAPI-cluster-scoped-3scale`
We either need to update the branch name or update the configuration here to accept the branch name for the correctly-shared-config test.

**Comment by laurafitzgerald** [comment]
seeing some rehearsals pass now 
/lgtm
/approve

**Pull request merged**
