### PR TITLE
ACM step-registry updates

### PR DESCRIPTION
**Pull request by dhaiducek**
- Bump step registry Go version
- Bump ClusterPool checkout timeout
- Handle `get` errors during RHACM deployment (stderr was inadvertently being redirected to the MCH name)

### CODE REVIEW

**Comment by dhaiducek** [comment]
/pj-rehearse "pull-ci-stolostron-governance-policy-framework-main-test-e2e-grc-framework"

**Comment by dhaiducek** [comment]
/pj-rehearse "pull-ci-stolostron-governance-policy-framework-main-test-e2e-grc-framework"

**Comment by dhaiducek** [comment]
/pj-rehearse "pull-ci-stolostron-governance-policy-framework-main-test-e2e-grc-framework"

**Comment by dhaiducek** [comment]
/pj-rehearse "pull-ci-stolostron-governance-policy-framework-main-pr-image-mirror"

**Comment by dhaiducek** [comment]
/pj-rehearse "pull-ci-stolostron-governance-policy-framework-release-2.8-test-e2e-grc-framework"

**Comment by dhaiducek** [comment]
/pj-rehearse "pull-ci-stolostron-governance-policy-framework-main-test-e2e-grc-framework"

**Comment by dhaiducek** [comment]
/pj-rehearse pull-ci-stolostron-governance-policy-framework-main-test-e2e-grc-framework

**Comment by dhaiducek** [comment]
/pj-rehearse pull-ci-stolostron-governance-policy-framework-main-test-e2e-grc-framework

**Comment by dhaiducek** [comment]
/pj-rehearse pull-ci-stolostron-governance-policy-framework-main-test-e2e-grc-framework

**Comment by dhaiducek** [comment]
/pj-rehearse pull-ci-stolostron-governance-policy-framework-main-test-e2e-grc-framework

**Comment by dhaiducek** [comment]
/pj-rehearse pull-ci-stolostron-governance-policy-framework-main-test-e2e-grc-framework

**Comment by dhaiducek** [comment]
/pj-rehearse pull-ci-stolostron-governance-policy-framework-main-test-e2e-grc-framework

**Comment by dhaiducek** [comment]
/pj-rehearse pull-ci-stolostron-governance-policy-framework-main-test-e2e-grc-framework

**Comment by dhaiducek** [comment]
/pj-rehearse pull-ci-stolostron-governance-policy-framework-main-test-e2e-grc-framework

**Comment by dhaiducek** [comment]
/pj-rehearse pull-ci-stolostron-governance-policy-framework-main-test-e2e-grc-framework

**Comment by dhaiducek** [comment]
Slack thread: https://redhat-internal.slack.com/archives/CSZLMKPS5/p1686335964759959

**Comment by dhaiducek** [comment]
/pj-rehearse pull-ci-stolostron-governance-policy-framework-main-test-e2e-grc-framework

**Review by gurnben — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
