### PR TITLE
Condense container networking plugins into single image

### PR DESCRIPTION
**Pull request by dougbtv**
We've recently condensed the two images for the containernetworking CNI plugins from two images down into one image.

@smarterclayton previously I had you create this PR for us to update mirroring: https://github.com/openshift/release/pull/2656 -- if there's a better procedure for performing this rather than this PR, please let me know. Thank you!

### CODE REVIEW

**Comment by smarterclayton** [comment]
Reverting, this wasn't actually ever built.

Also, why is the source and destination different?  That is not allowed.

**Comment by smarterclayton** [comment]
Where did you condense the images?  I'm not seeing that in the ci-operator config for your project?

**Comment by dougbtv** [comment]
@smarterclayton -- thanks for the revert. I've gone ahead and rebased the follow-up pull request: https://github.com/openshift/release/pull/4367 based on this reversion.

The source and destination differing is the mistake that I made. #4367 should have the same source and destination.

Having the images condensed should be part of the build system change that we made, available in the ART gitlab @ https://gitlab.cee.redhat.com/openshift-art/ocp-build-data/merge_requests/172/diffs -- and then implemented in this pending PR for the cluster-network-operator @ https://github.com/openshift/cluster-network-operator/pull/237

As for the ci-operator, [this particular github search](https://github.com/openshift/ci-tools/search?q=container-networking&unscoped_q=container-networking) to find references to the `container-networking-plugins-*` didn't turn anything up, so, I don't believe we had anything in that repo related to these images. Is there something that we should have had there? Thanks.

**Comment by smarterclayton** [comment]
You have to make the change in ci-operator config as well.
 ci-operator/config/openshift/containernetworking-plugins/openshift-containernetworking-plugins-master.yaml

**Pull request merged**
