### PR TITLE
telco5g: Use spot instances for jobs

### PR DESCRIPTION
**Pull request by sshnaidm**

### CODE REVIEW

**Comment by hector-vido** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.17-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-release-4.17-e2e-aws-ran-profile pull-ci-openshift-kni-cnf-features-deploy-release-4.16-e2e-aws-ran-profile pull-ci-openshift-kni-cnf-features-deploy-release-4.16-e2e-aws-ci-tests

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-master-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-release-4.16-e2e-aws-ci-tests

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-master-e2e-aws-ci-tests pull-ci-openshift-kni-cnf-features-deploy-release-4.16-e2e-aws-ci-tests

**Comment by sshnaidm** [comment]
/pj-rehearse pull-ci-openshift-kni-cnf-features-deploy-release-4.16-e2e-aws-ci-tests

**Review by SchSeba — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
