### PR TITLE
NE-1244: Add azure-manual-oidc workload to cluster ingress operator

### PR DESCRIPTION
**Pull request by dlom**
This PR enables e2e verification of the changes necessary to complete [NE-1244](https://issues.redhat.com//browse/NE-1244) (https://github.com/openshift/cluster-ingress-operator/pull/929)

/cc @abutcher @Miciah

### CODE REVIEW

**Comment by dlom** [comment]
/pj-rehearse pull-ci-openshift-cluster-ingress-operator-master-e2e-azure-manual-oidc

**Comment by abutcher** [comment]
Looks like the test failed in the IPI deprovision but was a successful install + test otherwise.
```
level=info msg=Install complete!
```

**Comment by Miciah** [comment]
Notwithstahding the deprovisioning failure, is the job ready to merge?

From what I can tell,
/lgtm

/hold
in case we need to fix the deprovisioning issue before adding the job.

**Comment by abutcher** [comment]
The deprovisioning failure has no other history and will not be related to AZWI. I think we continue with this merge and open a low priority bug for the deprovisioning failure so that folks can keep track of it if it happens again but my take is that its just a blip / lag on the Azure side that would be rare and unavoidable.

**Comment by abutcher** [comment]
https://issues.redhat.com/browse/OCPBUGS-16699

**Pull request merged**
