### PR TITLE
updating openshift-preflight jobs to use 4.11 and 4.14

### PR DESCRIPTION
**Pull request by acornett21**
- Updating `openshift-preflight` to use 4.11 and 4.14.

### CODE REVIEW

**Comment by acornett21** [comment]
/pj-rehearse pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.14-e2e

**Comment by acornett21** [comment]
/pj-rehearse pull-ci-redhat-openshift-ecosystem-openshift-preflight-main-4.14-e2e

**Review by komish — APPROVED** [review]
/lgtm

**Pull request merged**
