### PR TITLE
Upversion TALM to 4.19

### PR DESCRIPTION
**Pull request by sudomakeinstall2**

### CODE REVIEW

**Comment by sudomakeinstall2** [comment]
/pj-rehearse pull-ci-openshift-kni-cluster-group-upgrades-operator-main-security

**Comment by jc-rh** [comment]
/pj-rehearse ci/rehearse/openshift-kni/cluster-group-upgrades-operator/main/images

**Comment by jc-rh** [comment]
/pj-rehearse pull-ci-openshift-kni-cluster-group-upgrades-operator-main-images

**Pull request merged**
