### PR TITLE
Add Mihawk C155F2U33 back to the lease pool

### PR DESCRIPTION
**Pull request by Shilpa-Gokul**
Mihawk C155F2U33 is updated with latest RHEL 8.8. Adding it back to the lease pool to be used for production CI runs

### CODE REVIEW

**Comment by Shilpa-Gokul** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-ovn-remote-libvirt-ppc64le

**Comment by Shilpa-Gokul** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-ovn-remote-libvirt-ppc64le

**Comment by Shilpa-Gokul** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.12-ocp-e2e-ovn-remote-libvirt-ppc64le

**Comment by Shilpa-Gokul** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.11-ocp-e2e-ovn-remote-libvirt-ppc64le

**Comment by Shilpa-Gokul** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.11-ocp-e2e-remote-libvirt-ppc64le

**Comment by Shilpa-Gokul** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-ovn-remote-libvirt-ppc64le

**Comment by Shilpa-Gokul** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.10-ocp-e2e-remote-libvirt-ppc64le

**Comment by hamzy** [comment]
/hold
The the ansible script and anaconda kickstarter file need to be in source code control and run off of that before this merges.

**Comment by yussufsh** [comment]
> /hold The the ansible script and anaconda kickstarter file need to be in source code control and run off of that before this merges.
We want to try this one system to verify that new builds works well with latest versions. The system setup is done already and the machine is registered. Once we verify things work will push to the source repository and provision other machines with the automation.

**Comment by hamzy** [comment]
The only way to force that every configuration step is recorded is to make it a condition that both a clean reinstall and ansible need to be performed.  An example is that the passwordless ocp user is missing in ansible.  If we just say that we will do this at some later stage, then stuff like this gets forgotten.

**Comment by mkumatag** [comment]
Based on the offline conversation, I see @yussufsh made an effort to make scripts working temporarily with the hacks(of course for the long term - we need to work on making things better) but for now we can unhold and merge this PR.

/lgtm

**Review by jaypoulz — APPROVED** [review]
/approve

**Pull request merged**
