### PR TITLE
[4.14/4.15] Opt out cypress tests for profile vsphere-ipi-disk-encryption-tang

### PR DESCRIPTION
**Pull request by liangxia**
Context in https://redhat-internal.slack.com/archives/C015H2WDJRY/p1698070785033039

/cc @yanpzhan @sgaoshang @jianlinliu @jhou1

### CODE REVIEW

**Comment by sgaoshang** [comment]
@jianlinliu I think we should also remove it from vsphere-ipi-disk-encryption-tang-fips-f28-destructive job

**Comment by liangxia** [comment]
> @jianlinliu I think we should also remove it from vsphere-ipi-disk-encryption-tang-fips-f28-destructive job

Nope. `openshift-e2e-test-qe-destructive` does not contain cypress tests.

**Comment by jianlinliu** [comment]
@liangxia shall we also update the older versions on this job?

**Comment by liangxia** [comment]
> @liangxia shall we also update the older versions on this job?

I think yes, but not sure.
As it exist in 4.11, and the profile in 4.11 was added on 2023-02-13. Does the issue occur since then or only happen recently ?

**Comment by jianlinliu** [comment]
> > @liangxia shall we also update the older versions on this job?
> 
> I think yes, but not sure. As it exist in 4.11, and the profile in 4.11 was added on 2023-02-13. Does the issue occur since then or only happen recently ?

Recently a vsphere build farm migration happening, it affects all the existing ci jobs, so to be safer, I suggest to update the other versions too.

**Pull request merged**
