### PR TITLE
PLNSRVCE-452: add building of jvm cache image

### PR DESCRIPTION
**Pull request by gabemontero**

### CODE REVIEW

**Comment by gabemontero** [comment]
OK progress.  maven dep downloads work, but then

```
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:2.6:resources (default-resources) on project hacbs-cache: Cannot create resource output directory: /work/cache/target/classes -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :hacbs-cache
```

**Comment by gabemontero** [comment]
ok permissions are more restrictive when running this dockerfile in openshift builds 

`mkdir: cannot create directory ‘/work/cache/target’: Permission denied`

I'm going to have to pull elements from https://github.com/openshift/jenkins/blob/master/slave-base/Dockerfile.rhel8 and maybe https://github.com/openshift/jenkins/blob/master/agent-maven/Dockerfile.rhel8 to get a builder base and then try to layer the java Dockerfile in jvm-build-service off of that

I'll pick up on this when I get back from PTO, unless someone else on the team has the bandwidth to take this on in the interim.

Until then, updates to the java components images in jvm-build-service will not show up in the openshift CI based jvm-build-service-e2e

@stuartwdouglas @Michkov @psturc FYI

**Comment by gabemontero** [comment]
ok cache image build successful !!

**Comment by gabemontero** [comment]
and the e2e output has what we want:

```
jvm build service golang operator image:
registry.build01.ci.openshift.org/ci-op-x992n636/pipeline@sha256:2e61a626837f597f9f667dd3ca3c40dc71331150afbaaa0582fceacc132828eb
jvm build service jvm cache image:
registry.build01.ci.openshift.org/ci-op-x992n636/pipeline@sha256:4ed6a27341fa11a1f1d834bcf8cded47ab6522f07e6e03361fb8d45c24965ce6
```

working on the other java based images now, will update this PR with those in a bit

**Comment by gabemontero** [comment]
/assign @mmorhun 

hey @mmorhun - I believe you are back on July 4, and with @psturc on PTO, I believe you are the only member of the team that can lgtm this PR.

aside from all the green e2e's here, nothing from this PR should take effect elsewhere until I validate the changes here and merge https://github.com/redhat-appstudio/jvm-build-service/pull/90, and then make the infra-deployment changes to ultimately update the image references when the e2e's run.

thanks

Monday July 4 is a US holiday but I will be back on July 5.

**Review by mmorhun — APPROVED** [review]
LGTM

**Pull request merged**
