### PR TITLE
add mco sno pin target image

### PR DESCRIPTION
**Pull request by shellymiron**
clone of the previous [PR](https://github.com/openshift/release/pull/59027)

### CODE REVIEW

**Comment by shellymiron** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-4.16-upgrade-from-stable-4.16-aws-ipi-disc-priv-sno-tp-pin-mco-f60

**Comment by shellymiron** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-4.16-upgrade-from-stable-4.16-aws-ipi-disc-priv-sno-tp-pin-mco-f60

**Comment by sergiordlr** [comment]
The upgrade failed because of the expected reason.

/lgtm

**Pull request merged**
