### PR TITLE
Add cert-manager.yaml for build02

### PR DESCRIPTION
**Pull request by hongkailiu**
Pay my debt. See https://github.com/openshift/release/pull/15007

/cc nobody

### CODE REVIEW

**Comment by hongkailiu** [comment]
@alvaroaleman 

Do we have to change to `apiVersion: apiextensions.k8s.io/v1beta1`?

https://github.com/openshift/release/pull/15007/commits/2ee82219523f12fbcbd8b9ef6eb586dd48820f95#diff-83cdfe11a2c7fe30fc92d171226482da3ab004b41be970cf71e961f55f69bd12L17

**Comment by alvaroaleman** [comment]
> Do we have to change to apiVersion: apiextensions.k8s.io/v1beta1

Not sure, I can not tell you offhand if this is a valid v1 manifest. You can check with dry-run=server.

Can we deduplicate this among the cluster and only have per-cluster whats unique (clusterIssuer I think?)

**Comment by hongkailiu** [comment]
> Can we deduplicate this among the cluster and only have per-cluster whats unique (clusterIssuer I think?)

It is kind of different for the deployment (mainly because of targeting diff. cloud provider).

`app.ci`: we change `--leader-election-namespace`
https://github.com/openshift/release/blob/0cdb90b42b02c2a9ef98287b008b8a2e2019af39/clusters/app.ci/cert-manager/cert-manager.yaml#L7061

`build01`: injected the aws credentials via env. var. and `--dns01-recursive-nameservers="8.8.8.8:53"`
https://github.com/openshift/release/blob/49cae4e79d592185c34900d06020415f520600e5/clusters/build-clusters/01_cluster/cert-manager/cert-manager.yaml#L7066-L7076

`build02`: `--dns01-recursive-nameservers="8.8.8.8:53"`

I feel we should make its own yaml because we do not need to think about breaking others if we start to modify. We could do `git diff` to compare.

**Comment by hongkailiu** [comment]
/hold

let me check the validation.

**Comment by hongkailiu** [comment]
Ha.
Mine is `v1beta1` already. The following cmd passed with warning. Resolving warning will lead to more changes which I think upstream should do.
```
oc --context build02 apply -f clusters/build-clusters/02_cluster/cert-manager/cert-manager.yaml --dry-run=server --as system:admin
```

/hold cancel

**Comment by alvaroaleman** [comment]
> I feel we should make its own yaml because we do not need to think about breaking others if we start to modify. We could do git diff to compare.

Sure, but there is for example a 5k line set of CRDs that are identical everywhere. I would prefer to only have seperate manifests for things that are actually different, isntead of duplicating so much.

**Review by alvaroaleman — APPROVED** [review]

**Comment by hongkailiu** [comment]
/hold

will watch the deployment after lunch

**Pull request merged**
