### PR TITLE
add env for sdn plugin

### PR DESCRIPTION
**Pull request by zhaozhanqi**
@JianLi-RH @jiajliu @shellyyang1989 ^^

### CODE REVIEW

**Comment by shellyyang1989** [comment]
Hi @zhaozhanqi what issue does it fix?

**Comment by zhaozhanqi** [comment]
> Hi @zhaozhanqi what issue does it fix?

for sdn cluster from 4.15 which is not supported for installation, so we need this parameter to hack the cluster to force setup openshift-sdn plugin.

**Comment by zhaozhanqi** [comment]
@liangxia Could you help take a look and approve this?

**Pull request merged**
