### PR TITLE
[CSB] Store TNB framework pod logs

### PR DESCRIPTION
**Pull request by smongiar**

### CODE REVIEW

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.16-lp-interop-csb-interop-aws-latest

**Comment by smongiar** [comment]
/pj-rehearse periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.16-lp-interop-csb-interop-aws-latest

**Review by dfrazzette — APPROVED** [review]

**Comment by dfrazzette** [comment]
@smongiar - PR is awaiting approval from someone in the 
[OWNERS](https://github.com/openshift/release/blob/master/OWNERS) file (currently only @jupierce).

**Pull request merged**
