### PR TITLE
[openshift/jenkins-sync-plugin] Update _prowconfig.yaml 

### PR DESCRIPTION
**Pull request by ramessesii2**
remove `jira/valid-bug` label requirement

### CODE REVIEW

**Comment by ramessesii2** [comment]
okay, the exact reason why `prow-config` test is failing is not clear to me from the build logs.
I ran `make prow-config`  locally, I didn't get anything unusual.

**Comment by sayan-biswas** [comment]
> okay, the exact reason why `prow-config` test is failing is not clear to me from the build logs. I ran `make prow-config` locally, I didn't get anything unusual.
> 
> ```shell
> ➜  release (patch-1) make prow-config
> false || docker pull --platform linux/amd64 registry.ci.openshift.org/ci/determinize-prow-config:latest
> latest: Pulling from ci/determinize-prow-config
> Digest: sha256:85681e5cc1902f9631f4d39600e39aa4ac6cc4db95ed8849f30b0e08b2c9e153
> Status: Image is up to date for registry.ci.openshift.org/ci/determinize-prow-config:latest
> registry.ci.openshift.org/ci/determinize-prow-config:latest
> docker run --platform linux/amd64 --user 1000:1000 --rm -v "/home/ramesses/Work/redhat/release/core-services/prow/02_config:/config:z" registry.ci.openshift.org/ci/determinize-prow-config:latest --prow-config-dir /config --sharded-prow-config-base-dir /config --sharded-plugin-config-base-dir /config
> ```

Run the `make prow-config` and then push the changes. Should automatically format.

**Review by sayan-biswas — APPROVED** [review]

**Pull request merged**
