### PR TITLE
Add nightly e2e-vsphere-ovn jobs

### PR DESCRIPTION
**Pull request by jluhrsen**
Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>

### CODE REVIEW

**Comment by jluhrsen** [comment]
@danwinship , could you PTAL? I want to get some vsphere history in a nightly job so I can more easily start looking in to https://bugzilla.redhat.com/show_bug.cgi?id=1936556

**Comment by aravindhp** [comment]
@jluhrsen there are Windows e2e jobs that already use hybrid OVN on vSphere. Just calling that out in case it will help. 

/cc @JacobTanenbaum

**Comment by jluhrsen** [comment]
@danwinship, this ok with you?

**Comment by danielmellado** [comment]
Do we want to use windows e2e jobs? even if they use hybrid OVN on vSphere I would add this set as well

**Comment by jluhrsen** [comment]
> Do we want to use windows e2e jobs? even if they use hybrid OVN on vSphere I would add this set as well

are you saying to add a nightly windows job in addition to this or instead of this?

**Comment by danielmellado** [comment]
> > Do we want to use windows e2e jobs? even if they use hybrid OVN on vSphere I would add this set as well
> 
> are you saying to add a nightly windows job in addition to this or instead of this?

what I'm saying is that I think that, even if there's some windows job using hybrid OVN on vSphere, we should have these ones you proposed, maybe I misunderstood the comment from @aravindhp and he was just pasting them as a reference to yours.

**Comment by jluhrsen** [comment]
> > > Do we want to use windows e2e jobs? even if they use hybrid OVN on vSphere I would add this set as well
> > 
> > 
> > are you saying to add a nightly windows job in addition to this or instead of this?
> 
> what I'm saying is that I think that, even if there's some windows job using hybrid OVN on vSphere, we should have these ones you proposed, maybe I misunderstood the comment from @aravindhp and he was just pasting them as a reference to yours.

we currently have just vsphere-ovn jobs and we have ovn-windows jobs. both are just presubmits right now though. This PR is tyring to get a periodic non-PR job running for vsphere so we can get a better handle on it's health and try to fix that it's perma-failing as a presubmit and just getting ignored. If we want ovn-windows running periodically too, I can push a separate PR for that. I'll bring it up with the team.

**Comment by aravindhp** [comment]
@jluhrsen why do you need a new nightly to get vSphere history for debugging [BZ 1936556](https://bugzilla.redhat.com/show_bug.cgi?id=1936556)? Won't the history on [openshift-windows-machine-config-operator-master-vsphere-e2e-operator](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-windows-machine-config-operator-master-vsphere-e2e-operator) suffice?

**Comment by jluhrsen** [comment]
> @jluhrsen why do you need a new nightly to get vSphere history for debugging [BZ 1936556](https://bugzilla.redhat.com/show_bug.cgi?id=1936556)? Won't the history on [openshift-windows-machine-config-operator-master-vsphere-e2e-operator](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-windows-machine-config-operator-master-vsphere-e2e-operator) suffice?


those are also presubmit jobs. The main reason for this PR is because the e2e-vsphere-ovn presubmit job is failing
every time (almost) and it's just being ignored and providing no benefit. Does it always fail for the same reason? Does it
fail in 4.6 or 4.7 or 4.8? different reasons? it's not in testgrid.

We're thinking the vsphere deployment is important to OVN in general and we should know it's health. Even if we only
use the presubmit job and there is a failure, we might be debugging some problem from the actual unmerged PR.

The end goal is to get this job as a periodic, figure out where it's broken, fix it and then hopefully the presubmit job
will pass reliably for PRs and when it does fail it won't be ignored.

**Comment by aravindhp** [comment]
>The end goal is to get this job as a periodic, figure out where it's broken, fix it and then hopefully the presubmit job will pass reliably for PRs and when it does fail it won't be ignored.

Sounds good. I was coming from the perspective of debugging  [BZ 1936556](https://bugzilla.redhat.com/show_bug.cgi?id=1936556) which I think can be done without the nightly job. It seems like you want to add this job to track the health of OVN on vSphere in general.

**Comment by jluhrsen** [comment]
> > The end goal is to get this job as a periodic, figure out where it's broken, fix it and then hopefully the presubmit job will pass reliably for PRs and when it does fail it won't be ignored.
> 
> Sounds good. I was coming from the perspective of debugging [BZ 1936556](https://bugzilla.redhat.com/show_bug.cgi?id=1936556) which I think can be done without the nightly job. It seems like you want to add this job to track the health of OVN on vSphere in general.

ah... We don't want to track the long term and future health of ovn+vsphere, but yes, that is also something I need to debug and the periodic will be useful for that, but you are right that I could have used the presubmits if needed.

**Comment by jluhrsen** [comment]
@petr-muller , ok to approve this one?

**Pull request merged**
