### PR TITLE
[OCPCLOUD-809] Add generate CI tasks for AWS, GCP and Azure providers, MAO and CAO

### PR DESCRIPTION
**Pull request by Danil-Grigorev**
This PR is co-dependent on others, and should be merged *after* the following list, which will allow testing real functionality:
- https://github.com/openshift/cluster-autoscaler-operator/pull/181
- https://github.com/openshift/machine-api-operator/pull/744
- https://github.com/openshift/cluster-api-provider-aws/pull/368
- https://github.com/openshift/cluster-api-provider-azure/pull/180
- https://github.com/openshift/cluster-api-provider-gcp/pull/133

### CODE REVIEW

**Review by elmiko — APPROVED** [review]
/lgtm

**Review by michaelgugino — APPROVED** [review]
/approve

**Pull request merged**
