### PR TITLE
openstack: produce machine-friendlier data

### PR DESCRIPTION
**Pull request by pierreprinetti**
This PR proposes two changes:
* add JSON-formatted openstack-specific gather data
* fail the DNS deprovision step when DNS deprovisioning fails

These changes make our CI output easier to parse automatically.

### CODE REVIEW

**Comment by pierreprinetti** [comment]
/ pull-ci-openshift-installer-master-openstack-manifests

**Comment by pierreprinetti** [comment]
/pj-rehearse pull-ci-openshift-installer-master-e2e-openstack-ovn

**Comment by pierreprinetti** [comment]
/pj-rehearse periodic-ci-shiftstack-shiftstack-ci-4.12-e2e-openstack-ovn

**Review by mandre — COMMENTED** [review]
/lgtm

**Comment by mandre** [comment]
Job failed for reasons unrelated to the change. We can see it successfully created the json artifacts and deprovisioned DNS records:
- https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/35126/rehearse-35126-pull-ci-openshift-cloud-provider-openstack-master-e2e-openstack/1610913212662812672/artifacts/e2e-openstack/openstack-gather/artifacts/json/
- https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/35126/rehearse-35126-pull-ci-openshift-cloud-provider-openstack-master-e2e-openstack/1610913212662812672/artifacts/e2e-openstack/openstack-deprovision-dnsrecords/

/pj-rehearse ack

**Pull request merged**
