### PR TITLE
telemeter: add benchmark tests execution

### PR DESCRIPTION
**Pull request by paulfantom**
/cc @squat

### CODE REVIEW

**Comment by paulfantom** [comment]
Holding to prevent merge until `ci/rehearse/openshift/telemeter/master/benchmark` is green.

/hold

**Comment by squat** [comment]
sorry @paulfantom, the correct Make target is `test-benchmark` [0]. Just to be sure, the benchmark process requires access to `oc` and `curl`. Do we have these in the container?

[0] https://github.com/openshift/telemeter/blob/master/Makefile#L153

**Comment by paulfantom** [comment]
I've updated make target to correct one in previous force-push :)

**Comment by paulfantom** [comment]
Accidentally closed it :(

**Pull request merged**
