### PR TITLE
decrease number of periodic jobs for ovirt CI

### PR DESCRIPTION
**Pull request by eslutsky**
this is consecutive [PR](https://github.com/openshift/release/pull/38494) , to satisfy the requirement for reducing the available hardware resources for oVirt CI.

### CODE REVIEW

**Comment by michalskrivanek** [comment]
lgtm

**Comment by bkhizgiy** [comment]
lgtm

**Review by bkhizgiy — APPROVED** [review]
lgmt

**Review by danilo-gemoli — APPROVED** [review]

**Pull request merged**
