### PR TITLE
add periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.17-lp-interop-acm-interop-aws

### PR DESCRIPTION
**Pull request by amp-rh**
[INTEROP-7438](https://issues.redhat.com/browse/INTEROP-7438)

### CODE REVIEW

**Comment by amp-rh** [comment]
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.17-lp-interop-acm-interop-aws

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
