### PR TITLE
Initialize arm01 cluster

### PR DESCRIPTION
**Pull request by LorbusChris**
Onboarding for the new ARM build cluster on AWS

### CODE REVIEW

**Comment by hongkailiu** [comment]
Could you write a line?

https://github.com/openshift/release/tree/master/clusters

**Review by hongkailiu — APPROVED** [review]

**Comment by alvaroaleman** [comment]
@LorbusChris please add appropriate OWNERS
/hold

**Comment by LorbusChris** [comment]
updated :) 

/cc @aravindhp @gmarkley-VI 
fyi I've added you the approvers for the cluster as well

**Review by alvaroaleman — APPROVED** [review]
/hold cancel

**Pull request merged**
