### PR TITLE
Add packet to boskos reaper

### PR DESCRIPTION
**Pull request by honza**

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/lgtm cancel
the config for the app.ci cluster needs updating, please do not use the maketarget but add the config

**Comment by honza** [comment]
>  the config for the app.ci cluster needs updating, please do not use the maketarget but add the config

Would you mind fleshing this out a bit? I'm not super familiar with the all of the various pieces involved...

**Comment by alvaroaleman** [comment]
> Would you mind fleshing this out a bit? I'm not super familiar with the all of the various pieces involved...

The same change you made in `core-services/prow/03_deployment/boskos_reaper.yaml` also need to be made in `clusters/app.ci/prow/03_deployment/boskos_reaper.yaml`. You can use `verify-app-ci` to verify.

The background on this is that we are currently working on migrating Prow itself onto a dedicated cluster, which means that we need to version an almost-but-not-quite identical copy of the config in the meantime.

**Comment by honza** [comment]
Thanks! I just updated the other file.

**Comment by alvaroaleman** [comment]
@honza and because that changes the hash of the file, you need to run `make update-app-ci` and add the change to the PR, sorry for the hassle.

**Comment by honza** [comment]
No worries at all, thanks for your help. Updated, and rebased on top of master.

**Pull request merged**
