### PR TITLE
Add mirroring to redhat-cne quay for images

### PR DESCRIPTION
**Pull request by nishant-parekh**
- cloud-event-proxy
  - hw-event-proxy

Signed-off-by: Nishant Parekh <nparekh@redhat.com>

### CODE REVIEW

**Review by jzding — APPROVED** [review]

**Comment by petr-muller** [comment]
/lgtm cancel

There's no job that consumes this mapping file, please follow https://docs.ci.openshift.org/docs/how-tos/mirroring-to-quay/#configuring-mirroring-for-new-repository

**Pull request closed without merging**
