### PR TITLE
osa test-base move to new home

### PR DESCRIPTION
**Pull request by mjudeikis**
makes test-base to be built from azure-misc using ci-operator
depends on: https://github.com/openshift/azure-misc/pull/73

This is needed so test image could run `ssh` commands. In this case its for conformance tests
We want to disable the sync pod because it breaks the conformance tests.

### CODE REVIEW

**Comment by kargakis** [comment]
This image is also used by openshift-azure so the azure-misc move doesn't make much sense unless we agree to move all of our CI config in azure-misc.

**Comment by mjudeikis** [comment]
Idea is, we need more complex logic, which can't be easily coded into BuildConfig

**Comment by kargakis** [comment]
Can you give an example of "complex logic" that we need today and does not work?

**Comment by kargakis** [comment]
> And now I need to add some borrowed logic from openshift-ansible so we can run commands as non priv containers and use ssh.

What keeps you from fixing that here vs moving to azure-misc?

**Comment by mjudeikis** [comment]
entrypoint and user-setup script in this commit. 
`ssh, scp` in the image does not work, any command which requires USER to be present in the container does not work. This hit us with `az` binary way back, MSFT fixed it, now it came back with ssh to disable sync pod.

**Comment by mjudeikis** [comment]
> What keeps you from fixing that here vs moving to azure-misc?

Ci operator does `git-clone` and builds. What it gonna build? I dont want to add all these scripts to our current buildConfig definition.

**Comment by mjudeikis** [comment]
Ref here: https://github.com/openshift/azure-misc/pull/73

**Comment by kargakis** [comment]
> entrypoint and user-setup script in this commit.
> `ssh, scp` in the image does not work, any command which requires USER to be present in the container does not work. This hit us with `az` binary way back, MSFT fixed it, now it came back with ssh to disable sync pod.

Can you also explain where do you need to use ssh or scp? Is it the conformance e2e suite? It would be better to spell the answers to the "Why we need this?" question in the PR description.

**Comment by mjudeikis** [comment]
> Can you also explain where do you need to use ssh or scp? Is it the conformance e2e suite? It would be better to spell the answers to the "Why we need this?" question in the PR description.

Updated. Yes, it is for conformance, or any other e2e which needs to run `ssh`

**Comment by stevekuznetsov** [comment]
Base container for e2e that can SSH into nodes on the cluster seems like a problem that more than just azure deployer will have -- maybe you should talk to @csrwng @vrutkovs @wking about how they are thinking about this

**Comment by kargakis** [comment]
After giving this some thought I still think the move to azure-misc is
problematic. 1. You litter ci config in two different places (azure-misc,
release) 2. You pull a dependency on azure-misc for openshift-azure. In the
scenario the CI cluster gets recreated, you would have to merge something
in azure-misc for the openshift-azure tests to start working. I also think
that a BC is more flexible in that regard.

Not sure why adding ssh/scp in the BC is not working but we should explore
that route first.

**Comment by mjudeikis** [comment]
> Not sure why adding ssh/scp in the BC is not working but we should explore
that route first.

I did already explored this. openshift-ansible already solved it here https://github.com/openshift/openshift-ansible/blob/master/images/installer/Dockerfile.rhel7#L41 and I just replicating it. The only think what changes that our Dockerfile now needs additional files with it to be copied over. Our build config limitation is that it does not carry additional files with it, just plain dockerfile

**Comment by kargakis** [comment]
>  Our build config limitation is that it does not carry additional files with it, just plain dockerfile

You should be able to move the dockerfile and the extra files out to a separate directory, mount the files in the dockerfile and have a build use the directory you created as a context directory to run a docker build, wouldn't that work?

**Comment by vrutkovs** [comment]
I'm not entirely sure why would you want a separate Dockerfile for Azure, but FYI openshift-ansible has now has `Dockerfile.ci` to be used in CI (see #1638). Wouldn't it be easier for you guys to update openshift-ansible image with necessary packages?

**Comment by kargakis** [comment]
> Wouldn't it be easier for you guys to update openshift-ansible image with necessary packages?

No, this is unrelated to the openshift-ansible repo. It's the base image that we use to run tests in azure-misc and openshift-azure.

**Pull request closed without merging**
