### PR TITLE
OCPQE-18646: create a disk partition on new disk for upi-on-azure

### PR DESCRIPTION
**Pull request by jinyunma**
automate test case:  
OCP-41047 [UPI-on-Azure] Creating a separate partition for /var or its subdirectory on a new disk at install time

### CODE REVIEW

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disk-parition-var-f14

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disk-parition-var-f14

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disk-parition-var-f14

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disk-parition-var-f14

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disk-parition-var-f14

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disk-parition-var-f14

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disk-parition-var-f14

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disk-parition-var-f14

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disk-parition-var-f14

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disk-partition-var-f14

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disk-partition-var-f14

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disk-partition-var-f14

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disk-partition-var-container-f14 periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disk-partition-var-etcd-f14

**Comment by jinyunma** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.15-e2e-azure-ovn-upi

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disk-partition-var-f14

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disk-partition-var-f14

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disk-partition-var-container-f14 periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disk-partition-var-etcd-f14

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disk-partition-var-f14 periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disk-partition-var-etcd-f14

**Comment by jinyunma** [comment]
/pj-rehearse pull-ci-openshift-installer-release-4.15-e2e-azure-ovn-upi

**Comment by jinyunma** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disk-partition-var-container-f14

**Comment by jinyunma** [comment]
azure-upi-disk-partition-var-container: [job](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/47235/rehearse-47235-periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disk-partition-var-container-f14/1744558480158625792), [cucushift-installer-check-azure-disk-partition](https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/47235/rehearse-47235-periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disk-partition-var-container-f14/1744558480158625792/artifacts/azure-upi-disk-partition-var-container-f14/cucushift-installer-check-azure-disk-partition/build-log.txt)
azure-upi-disk-partition-var-etcd: [job](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/47235/rehearse-47235-periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disk-partition-var-etcd-f14/1744528247158214656), [cucushift-installer-check-azure-disk-partition](https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/47235/rehearse-47235-periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disk-partition-var-etcd-f14/1744528247158214656/artifacts/azure-upi-disk-partition-var-etcd-f14/cucushift-installer-check-azure-disk-partition/build-log.txt)
azure-upi-disk-partition-var: [job](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/47235/rehearse-47235-periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disk-partition-var-f14/1744528247103688704), [cucushift-installer-check-azure-disk-partition](https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/47235/rehearse-47235-periodic-ci-openshift-verification-tests-master-installation-nightly-4.15-azure-upi-disk-partition-var-f14/1744528247103688704/artifacts/azure-upi-disk-partition-var-f14/cucushift-installer-check-azure-disk-partition/build-log.txt)

cc @jianlinliu @gpei to review

**Comment by jianlinliu** [comment]
@jinyunma Sorry to be late to notice this PR, for OCP-41047, I saw there are several place to interfere with UPI template, also butane, personally it is a bit complicated, maybe not easier maintain than in flexy, I prefer to keep the case in v4-installer-autotest, unless there are indeed some requirement to ask us to run a regular ci testing for the the extra disk partition coverage, wdyt?

**Comment by jinyunma** [comment]
> @jinyunma Sorry to be late to notice this PR. For OCP-41047, I saw there are several place to interfere with UPI template, and butane. Personally it is a bit complicated, maybe not easier to maintain than in flexy, I prefer to keep the case in v4-installer-autotest, unless there are indeed some requirement to ask us to run a regular ci testing for the the extra disk partition coverage, wdyt?

Yes, it will update upi arm template for additional disk. It's okay for me to run case only in v4-installer-autotest so far. I will close this PR.

**Pull request closed without merging**
