### PR TITLE
Add Submariner ACM 2.6 jobs

### PR DESCRIPTION
**Pull request by dfarrell07**
Copied from the 2.5 jobs with the version numbers changed.

Relates-to: stolostron/backlog#23462

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

**Comment by skitt** [comment]
/hold

This needs the config files as well.

**Comment by dfarrell07** [comment]
FYI, if I run `make update`, it suggests

```
-    cluster: build03
+    cluster: build01
```

**Comment by skitt** [comment]
> FYI, if I run `make update`, it suggests
> 
> ```
> -    cluster: build03
> +    cluster: build01
> ```

Let’s do that, it will allow the ordered-prow-config test to pass.

**Comment by dfarrell07** [comment]
Yep, was just seeing that too, will-send..

**Comment by dfarrell07** [comment]
Come on bot, you can do it... :eyes:

**Pull request merged**
