### PR TITLE
add in-repo e2e with pruning for comparison

### PR DESCRIPTION
**Pull request by gabemontero**
/assign @psturc 

@stuartwdouglas FYI

Ideally we get this merged soon and we start testing https://github.com/redhat-appstudio/jvm-build-service/pull/171 today with it

### CODE REVIEW

**Comment by psturc** [comment]
@gabemontero I approved this PR, but now it seems you need to update this PR with changes after running `make ci-operator-config` (as mentioned in the [ci-operator-config-metadata job run](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/31184/pull-ci-openshift-release-master-ci-operator-config-metadata/1557006997486833664))

**Comment by gabemontero** [comment]
yep ... will update in a sec @psturc and will need a re-lgtm

**Comment by gabemontero** [comment]
`make ci-operator-config` output pushed @psturc (I had a blank line)

**Comment by gabemontero** [comment]
go ahead and tag @psturc but I'm going to hold to make sure the rehearsal finishes (it is not a required job)

/hold

**Comment by gabemontero** [comment]
no "luck" in that the in repo with pruning passed here @stuartwdouglas @psturc ... but then for whatever weird reason it seemed to be happening in the infra-deployments PRs vs. the jvm-build-service or e2e-tests PRs (I am beginning to wonder if there is a setup difference in infra that leads to that).

Though we did get a failure in https://github.com/redhat-appstudio/jvm-build-service/pull/166 before removed the test from e2e-tests, so it is possible to get in jvm-build-service PRs.

I'll create a comparison PR or use another existing PR today to compare with the runs in https://github.com/redhat-appstudio/jvm-build-service/pull/171

/hold cancel

**Pull request merged**
