### PR TITLE
MultiArch build odh-dashboard

### PR DESCRIPTION
**Pull request by puneetsharma21**
introduces multi-architecture support for the ODH Dashboard image

Purpose:
The primary goal of this PR is to enhance the flexibility of our image builds by supporting multiple architectures. This will ensure that the ODH Dashboard image can be used across different environments and platforms.

### CODE REVIEW

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-images

**Comment by puneetsharma21** [comment]
/pj-rehearse branch-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse branch-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-images

**Comment by puneetsharma21** [comment]
pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by mdafsanhossain** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Comment by puneetsharma21** [comment]
/pj-rehearse pull-ci-opendatahub-io-odh-dashboard-main-odh-dashboard-multiarch-build

**Pull request closed without merging**
