### PR TITLE
Includes 'oc describe' when gathering logs from all resources

### PR DESCRIPTION
**Pull request by viroel**
Get outputs from 'oc describe' for all resources from operators and services namespaces.

### CODE REVIEW

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-cinder-operator-master-cinder-operator-build-deploy-kuttl

**Review by ASBishop — COMMENTED** [review]
A big +1 from me, thanks!

**Comment by viroel** [comment]
oc describe outputs:

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/38195/rehearse-38195-pull-ci-openstack-k8s-operators-cinder-operator-master-cinder-operator-build-deploy-kuttl/1645477142340833280/artifacts/cinder-operator-build-deploy-kuttl/openstack-k8s-operators-gather/artifacts/statefulset.apps/

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
