### PR TITLE
Update custom SG for enabling SSH/22

### PR DESCRIPTION
**Pull request by yunjiang29**
### RHEL
```
cucushift-installer-rehearse-aws-ipi-disconnected-private-provision
* cucushift-installer-rehearse-aws-ipi-disconnected-private-workers-rhcos-rhel8-provision

cucushift-installer-rehearse-aws-ipi-proxy-provision
* cucushift-installer-rehearse-aws-ipi-proxy-workers-rhel8-provision
* cucushift-installer-rehearse-aws-ipi-proxy-workers-rhel8-etcd-encryption-provision
```

### Private clusters
```
cucushift-installer-rehearse-aws-ipi-disconnected-private-cco-manual-security-token-service-efs-provision
cucushift-installer-rehearse-aws-ipi-disconnected-private-cco-manual-security-token-service-private-s3-with-ep-sts-ec2-elb-provision
cucushift-installer-rehearse-aws-ipi-disconnected-private-cco-manual-security-token-service-provision
cucushift-installer-rehearse-aws-ipi-disconnected-private-network-mtu-edge-zone-provision
cucushift-installer-rehearse-aws-ipi-disconnected-private-provision
cucushift-installer-rehearse-aws-ipi-disconnected-private-sno-provision
cucushift-installer-rehearse-aws-ipi-disconnected-private-techpreview-provision
cucushift-installer-rehearse-aws-ipi-disconnected-private-workers-rhcos-rhel8-provision
cucushift-installer-rehearse-aws-ipi-private-cco-manual-security-token-service-provision
cucushift-installer-rehearse-aws-ipi-private-ovn-ipsec-provision
cucushift-installer-rehearse-aws-ipi-private-provision
cucushift-installer-rehearse-aws-ipi-private-shared-vpc-phz-sts-provision
```

### CODE REVIEW

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-disc-priv-workers-rhcos-rhel8-f14

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-disc-priv-workers-rhcos-rhel8-f14

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-aws-ipi-disc-priv-sts-efs-arm-f2

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-private-shared-vpc-phz-sts-f2

**Comment by yunjiang29** [comment]
/pj-rehearse pull-ci-openshift-csi-operator-master-e2e-aws-csi-extended

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-ovn-hypershift-private-mgmt-f7

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-rosa-hcp-security-group-stage-full-f7

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-disc-priv-workers-rhcos-rhel8-f14

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-disc-priv-workers-rhcos-rhel8-f14

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-ovn-hypershift-private-mgmt-f7

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-private-shared-vpc-phz-sts-f2

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-rosa-hcp-security-group-stage-full-f7

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-multi-nightly-aws-ipi-disc-priv-sts-efs-arm-f2

**Comment by yunjiang29** [comment]
/pj-rehearse pull-ci-openshift-csi-operator-master-e2e-aws-csi-extended

**Comment by yunjiang29** [comment]
/pj-rehearse pull-ci-openshift-csi-operator-master-e2e-aws-csi-extended

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-disc-priv-workers-rhcos-rhel8-f14

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-ovn-hypershift-private-mgmt-f7

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-private-shared-vpc-phz-sts-f2

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-private-shared-vpc-phz-sts-f2

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-ovn-hypershift-private-mgmt-f7

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-disc-priv-workers-rhcos-rhel8-f14

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-disc-priv-workers-rhcos-rhel8-f14

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-ovn-hypershift-private-mgmt-f7

**Comment by yunjiang29** [comment]
#### tests
* ROSA https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/52741/rehearse-52741-periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-rosa-hcp-security-group-stage-full-f7/1797867925437157376

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-disc-priv-workers-rhcos-rhel8-f14

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-disc-priv-workers-rhcos-rhel8-f14

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-disc-priv-workers-rhcos-rhel8-f14

**Comment by yunjiang29** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-disc-priv-workers-rhcos-rhel8-f14

**Comment by jianlinliu** [comment]
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-private-shared-vpc-phz-sts-f2

**Comment by yunjiang29** [comment]
#### 4.13
* https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/52741/rehearse-52741-periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-aws-ipi-disc-priv-workers-rhcos-rhel8-f14/1798226905988599808

provision
```
OCP Version: 4.13
Custom SG in 4.13- is not applicable, skip now.
```
deprovision
```
No custom SG was created, skip now.
```

**Comment by yunjiang29** [comment]
@jianlinliu @gpei this PR is ready for merge

**Pull request merged**
