### PR TITLE
switch to opendatahub cluster profile

### PR DESCRIPTION
**Pull request by riprasad**

### CODE REVIEW

**Comment by riprasad** [comment]
The test failure doesn't seem related to the changes. New Cluster profile is working. Hence, acknowledging rehearsal.

**Comment by israel-hdez** [comment]
/pj-rehearse pull-ci-opendatahub-io-kserve-master-e2e-fast pull-ci-opendatahub-io-kserve-master-e2e-slow

**Comment by riprasad** [comment]
@israel-hdez DNS issue has been resolved. Please take a look

**Comment by israel-hdez** [comment]
Hey @riprasad .
The failing test is because of a pod being OOMKilled. I saw that issue yesterday when working on something else. 

I already have a PR with the fix in the repo of the component.

The issue is unrelated to the work you are doing. So, let's get this PR merged.

**Review by israel-hdez — APPROVED** [review]

**Pull request merged**
