### PR TITLE
Bump HyperShift version

### PR DESCRIPTION
**Pull request by bear-redhat**
```
oc --context app.ci -n ci start-build hypershift-cli --as system:admin

oc --context app.ci -n ci tag hypershift-cli:latest hypershift-cli:20230712 --as system:admin

docker run -ti --rm -v ~/workspace/mgmt-aws:/mgmt-aws:ro registry.ci.openshift.org/ci/hypershift-cli:20230712 install --oidc-storage-provider-s3-bucket-name=hypershift-oidc-provider --oidc-storage-provider-s3-credentials=/mgmt-aws --oidc-storage-provider-s3-region=us-east-1 --hypershift-image=registry.ci.openshift.org/ci/hypershift-cli:20230712 --enable-uwm-telemetry-remote-write=false render > hypershift-install-20230712.yaml

oc --context hive apply -f hypershift-install-20230712.yaml  --as system:admin
```

### CODE REVIEW

**Comment by hongkailiu** [comment]
> docker run -ti --rm -v ~/workspace/mgmt-aws:/mgmt-aws:ro

I just feel it adds a new tech debt. Could you please make a card to implement a way that everything could use it?

**Comment by hongkailiu** [comment]
/lgtm
/hold

Need to see how rehearsal goes.

**Comment by bear-redhat** [comment]
> > docker run -ti --rm -v ~/workspace/mgmt-aws:/mgmt-aws:ro
> 
> I just feel it adds a new tech debt. Could you please make a card to implement a way that everything could use it?

It should be already there in `vault`. Just a credential to `ci-2` AWS account.

**Pull request merged**
