### PR TITLE
Temporarily use OpenShift 4.8 for QA tests.

### PR DESCRIPTION
**Pull request by porridge**
https://issues.redhat.com/browse/ROX-12314
[webhooks are broken on 4.11](https://srox.slack.com/archives/C0321S70YK1/p1661335962892879)

/cc @janisz 
/test pj-rehearse-max

### CODE REVIEW

**Review by janisz — APPROVED** [review]

**Comment by porridge** [comment]
Trying to unwedge the `[do-not-merge/work-in-progress](https://github.com/openshift/release/labels/do-not-merge%2Fwork-in-progress)` label by closing/re-opening the PR.

**Pull request merged**
