### PR TITLE
[INTEROP-7731] Change cron expressions to prevent periodic jobs from

### PR DESCRIPTION
**Pull request by amp-rh**
bypassing weekly trigger job and running on scheduled date.

(Forked from https://github.com/openshift/release/pull/59937)

### CODE REVIEW

**Comment by dfrazzette** [comment]
Changes are non-functional to periodic jobs, so waiving rehearsal runs.

**Review by dfrazzette — APPROVED** [review]

**Comment by alanfx** [comment]
The Infinispan changes /lgtm

**Comment by alanfx** [comment]
The Infinispan changes /lgtm

**Pull request merged**
