### PR TITLE
Revert "Remove superceded operation condition testing code"

### PR DESCRIPTION
**Pull request by bparees**
Reverts openshift/release#20454

Reverting for now per:
https://coreos.slack.com/archives/C01CQA76KMX/p1626869349416400?thread_ts=1626805662.402900&cid=C01CQA76KMX

1) we don't have the equivalent to these tests in 4.8 and earlier
2) sippy uses these test results to do some processing

But replacing this functionality still seems like a worthy goal.

### CODE REVIEW

**Comment by wking** [comment]
/hold

4.8 [definitely has the new tests][1]; it's just 4.7 and earlier.  Does that sway folks?

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws/1413177400551804928

**Comment by deads2k** [comment]
/assign @dmage 

Oleg/TRT can decide about merge or not here.

**Comment by dmage** [comment]
/lgtm
/hold cancel

Let's bring it back until we find a good replacement.

**Pull request merged**
