### PR TITLE
Update cno 4.13+ to use Dockerfile, not Dockerfile.rhel7

### PR DESCRIPTION
**Pull request by jluhrsen**

### CODE REVIEW

**Comment by martinkennelly** [comment]
This should not merge before: https://github.com/openshift/cluster-network-operator/pull/1768

**Comment by jluhrsen** [comment]
https://issues.redhat.com/browse/OCPBUGS-11503

**Comment by jluhrsen** [comment]
/hold

need [this bug](https://issues.redhat.com/browse/OCPBUGS-11503) resolved once [this PR](https://github.com/openshift/cluster-network-operator/pull/1772) is merged

**Pull request merged**
