### PR TITLE
Replace rpms.svc.ci.openshift.org

### PR DESCRIPTION
**Pull request by hongkailiu**
https://issues.redhat.com/browse/DPTP-1874

```bash
$ find . -type f   -exec gsed -i 's/rpms.svc.ci.openshift.org/artifacts-rpms-openshift-origin-ci-rpms.apps.ci.l2s4.p1.openshiftapps.com/g' {} \;
```

/hold

Requiring https://github.com/openshift/release/pull/15000

/cc @stevekuznetsov

### CODE REVIEW

**Comment by hongkailiu** [comment]
We need to change the generator too.

**Review by stevekuznetsov — APPROVED** [review]

**Pull request merged**
