### PR TITLE
Update nfsplugin tests

### PR DESCRIPTION
**Pull request by Fedosin**
Add new tests and remove `e2e-aws` that doesn't make sense here.

### CODE REVIEW

**Comment by sdodson** [comment]
Is there a test that actually exercises the plugin? Where is that?

**Comment by Fedosin** [comment]
@sdodson the downstream version is here https://github.com/openshift/csi-driver-nfs
Now it is required for Manila CSI driver to be able to create volumes in NFS.

We do not plan to make any modifications in downstream, so I think real tests are not necessary for the repository. Its functionality (e2e tests) will be tested along with Manila CSI on our CI soon.

**Comment by sdodson** [comment]
Ok, as long it gets tested somewhere in the product.

**Pull request merged**
