### PR TITLE
Remove CI for ovs-operator in preparation to repo archival

### PR DESCRIPTION
**Pull request by booxter**
The operator CRD (OVS) was moved to ovn-operator (under OVNController name) and ovs-operator is no longer needed. We plan to archive the repo. This is in preparation to this action.

### CODE REVIEW

**Review by karelyatin — COMMENTED** [review]
/lgtm

**Comment by karelyatin** [comment]
@Sandeepyadav93 can you also check this if this is enough or some other steps are required for retiring the jobs

**Comment by Sandeepyadav93** [comment]
/lgtm

I think a bot which runs on regular intervals updates this file  `core-services/sanitize-prow-jobs/_config.yaml` automatically, its okay to modify this via PR but then we will require approval from the file owners(dptp team in this case.)

**Comment by Sandeepyadav93** [comment]
/assign bbguimaraes droslean

We want to remove CI for our ovs repo as its merging in a different repo, could you please review changes to `core-services/sanitize-prow-jobs/_config.yaml` file

**Comment by booxter** [comment]
changes since the previous version: rebased on latest master.

**Review by karelyatin — APPROVED** [review]
/lgtm

**Review by droslean — APPROVED** [review]

**Pull request merged**
