### PR TITLE
add connectivity check

### PR DESCRIPTION
**Pull request by qiliRedHat**
https://issues.redhat.com/browse/OCPQE-27462
Function test passed
Test result on a 3 masters 6 workers cluster - connectivity test used 56s
```
 % ./openshift-qe-connectivity-check-commands.sh
[INFO]Deleting test namespace connectivity-check
namespace "connectivity-check" deleted
Error from server (NotFound): namespaces "connectivity-check" not found
[INFO]Test namespace connectivity-check is deleted.
[INFO]Creating test namespace connectivity-check
Already on project "connectivity-check" on server "https://api.mbhalodi-preserve-r03.qe.azure.devcluster.openshift.com:6443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app rails-postgresql-example

to build a new example application in Ruby. Or use kubectl to deploy a simple Kubernetes application:

    kubectl create deployment hello-node --image=registry.k8s.io/e2e-test-images/agnhost:2.43 -- /agnhost serve-hostname

[INFO]Creating DaemonSet
Warning: spec.template.spec.nodeSelector[beta.kubernetes.io/os]: deprecated since v1.14; use "kubernetes.io/os" instead
daemonset.apps/hello-daemonset created
[INFO]Waiting for pods to become 'Running'... retries remaining: 9
No resources found in connectivity-check namespace.
All pods are Running!
[INFO]Start connectivity check between each pair of nodes. This will take some time in large cluster.
-------------------------
Node 0: Pinging from pod: hello-daemonset-cjxg7
0->1:Testing pods connection from pod hello-daemonset-cjxg7 to 10.128.0.113:8080
0->2:Testing pods connection from pod hello-daemonset-cjxg7 to 10.129.2.143:8080
0->3:Testing pods connection from pod hello-daemonset-cjxg7 to 10.129.0.118:8080
0->4:Testing pods connection from pod hello-daemonset-cjxg7 to 10.130.1.4:8080
0->5:Testing pods connection from pod hello-daemonset-cjxg7 to 10.128.3.83:8080
-------------------------
Node 1: Pinging from pod: hello-daemonset-frn4j
1->2:Testing pods connection from pod hello-daemonset-frn4j to 10.129.2.143:8080
1->3:Testing pods connection from pod hello-daemonset-frn4j to 10.129.0.118:8080
1->4:Testing pods connection from pod hello-daemonset-frn4j to 10.130.1.4:8080
1->5:Testing pods connection from pod hello-daemonset-frn4j to 10.128.3.83:8080
-------------------------
Node 2: Pinging from pod: hello-daemonset-m9bwb
2->3:Testing pods connection from pod hello-daemonset-m9bwb to 10.129.0.118:8080
2->4:Testing pods connection from pod hello-daemonset-m9bwb to 10.130.1.4:8080
2->5:Testing pods connection from pod hello-daemonset-m9bwb to 10.128.3.83:8080
-------------------------
Node 3: Pinging from pod: hello-daemonset-qth9w
3->4:Testing pods connection from pod hello-daemonset-qth9w to 10.130.1.4:8080
3->5:Testing pods connection from pod hello-daemonset-qth9w to 10.128.3.83:8080
-------------------------
Node 4: Pinging from pod: hello-daemonset-w8jsx
4->5:Testing pods connection from pod hello-daemonset-w8jsx to 10.128.3.83:8080
-------------------------
Node 5: Pinging from pod: hello-daemonset-ztz9p

real	0m56.078s
user	0m2.706s
sys	0m0.883s
==========TEST RESULT=============
Connectivity test PASSED.
[INFO]Deleting test namespace connectivity-check
namespace "connectivity-check" deleted
Error from server (NotFound): namespaces "connectivity-check" not found
[INFO]Test namespace connectivity-check is deleted.
```
24 worker nodes + 3 infra nodes' cluster check used 5 mins + to run the connectivity check. The time is acceptable, I added the step to all 24 nodes ipsec upgrade jobs.
```
-------------------------
Node 26: Pinging from pod: hello-daemonset-xbhhl

real	5m22.341s
user	0m38.359s
sys	0m13.349s
==========TEST RESULT=============
Connectivity test PASSED.
```

### CODE REVIEW

**Comment by qiliRedHat** [comment]
@huiran0826 Would you help to review this step? After this is merged, I'll add it to perfscale's ipsec jobs to do the connectivity check before starting a performance test.

**Comment by qiliRedHat** [comment]
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-ipsec-4.18-nightly-x86-loaded-upgrade-from-4.17-loaded-upgrade-417to418-24nodes

**Comment by qiliRedHat** [comment]
@mohit-sheth @jtaleric PTAL

**Review by jtaleric — APPROVED** [review]
/lgtm

**Pull request merged**
