### PR TITLE
MGMT-9924: greet each PR contribution with instructions

### PR DESCRIPTION
**Pull request by osherdp**
Using the new ``always_post`` option, this will send a message for each PR to ``assisted-installer-deployment`` about how code should be tested and reviewed.

This option of ``welcome`` plugin still haven't been fully-tested, so I'm unsure if it will work.
Either way please let me know if you prefer changing wording here or add/remove content from it.

/cc @mkowalski @eliorerz 
/hold

### CODE REVIEW

**Review by eliorerz — APPROVED** [review]

**Comment by osherdp** [comment]
/unhold
thank you!

**Comment by mkowalski** [comment]
Nice, thanks! Belated review but useful stuff 👍🏻

**Pull request merged**
