### PR TITLE
 add an aws-ovn micro upgrade job for 4.10

### PR DESCRIPTION
**Pull request by deads2k**
I want to have an 4.10-aws-ovn-update-micro job.  I can't find a definition for it and I don't know to get it. Changing some names to see if magic happens.

/hold until someone can explain what's happening and why its ok for this

### CODE REVIEW

**Comment by deads2k** [comment]
/assign @bradmwilliams 

Brad explained where these values come from.  I think this should now pass CI

/hold cancel

**Review by bradmwilliams — APPROVED** [review]

**Comment by deads2k** [comment]
trt is on approvers for the other two packages.  I consider myself an honorary member.  labelling.

**Pull request merged**
