### PR TITLE
Use set images from repositories

### PR DESCRIPTION
**Pull request by racheljpg**
This is a PR to remove the base image from the release config for multiple repositories so they can use the set images from the repository instead. Thanks!

### CODE REVIEW

**Comment by racheljpg** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-alibaba-cloud-release-4.15-images pull-ci-openshift-cloud-provider-alibaba-cloud-master-images
/pj-rehearse pull-ci-openshift-cloud-provider-aws-release-4.15-images pull-ci-openshift-cloud-provider-aws-master-images
/pj-rehearse pull-ci-openshift-cloud-provider-gcp-release-4.15-images pull-ci-openshift-cloud-provider-gcp-master-images

/pj-rehearse pull-ci-openshift-cluster-api-operator-release-4.15-images pull-ci-openshift-cluster-api-operator-master-images
/pj-rehearse pull-ci-openshift-cluster-api-provider-aws-release-4.15-images pull-ci-openshift-cluster-api-provider-aws-master-images
/pj-rehearse pull-ci-openshift-cluster-api-provider-azure-release-4.15-images pull-ci-openshift-cluster-api-provider-azure-master-images
/pj-rehearse pull-ci-openshift-cluster-api-release-4.15-images pull-ci-openshift-cluster-api-master-images

/pj-rehearse pull-ci-openshift-machine-api-operator-release-4.15-images pull-ci-openshift-machine-api-operator-master-images
/pj-rehearse pull-ci-openshift-machine-api-provider-gcp-release-4.15-images pull-ci-openshift-machine-api-provider-gcp-master-images
/pj-rehearse pull-ci-openshift-machine-api-provider-powervs-release-4.15-images pull-ci-openshift-machine-api-provider-powervs-master-images

**Comment by racheljpg** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-alibaba-cloud-release-4.15-images pull-ci-openshift-cloud-provider-alibaba-cloud-master-images
pull-ci-openshift-cloud-provider-aws-release-4.15-images pull-ci-openshift-cloud-provider-aws-master-images
pull-ci-openshift-cloud-provider-gcp-release-4.15-images pull-ci-openshift-cloud-provider-gcp-master-images

pull-ci-openshift-cluster-api-operator-release-4.15-images pull-ci-openshift-cluster-api-operator-master-images
pull-ci-openshift-cluster-api-provider-aws-release-4.15-images pull-ci-openshift-cluster-api-provider-aws-master-images
pull-ci-openshift-cluster-api-provider-azure-release-4.15-images pull-ci-openshift-cluster-api-provider-azure-master-images
pull-ci-openshift-cluster-api-release-4.15-images pull-ci-openshift-cluster-api-master-images

pull-ci-openshift-machine-api-operator-release-4.15-images pull-ci-openshift-machine-api-operator-master-images
pull-ci-openshift-machine-api-provider-gcp-release-4.15-images pull-ci-openshift-machine-api-provider-gcp-master-images
pull-ci-openshift-machine-api-provider-powervs-release-4.15-images pull-ci-openshift-machine-api-provider-powervs-master-images

**Comment by racheljpg** [comment]
/pj-rehearse pull-ci-openshift-cloud-provider-alibaba-cloud-release-4.15-images pull-ci-openshift-cloud-provider-alibaba-cloud-master-images pull-ci-openshift-cloud-provider-aws-release-4.15-images pull-ci-openshift-cloud-provider-aws-master-images pull-ci-openshift-cloud-provider-gcp-release-4.15-images pull-ci-openshift-cloud-provider-gcp-master-images pull-ci-openshift-cluster-api-operator-release-4.15-images pull-ci-openshift-cluster-api-operator-master-images pull-ci-openshift-cluster-api-provider-aws-release-4.15-images pull-ci-openshift-cluster-api-provider-aws-master-images pull-ci-openshift-cluster-api-provider-azure-release-4.15-images pull-ci-openshift-cluster-api-provider-azure-master-images pull-ci-openshift-cluster-api-release-4.15-images pull-ci-openshift-cluster-api-master-images pull-ci-openshift-machine-api-operator-release-4.15-images pull-ci-openshift-machine-api-operator-master-images pull-ci-openshift-machine-api-provider-gcp-release-4.15-images pull-ci-openshift-machine-api-provider-gcp-master-images pull-ci-openshift-machine-api-provider-powervs-release-4.15-images pull-ci-openshift-machine-api-provider-powervs-master-images

**Review by davidvossel — COMMENTED** [review]
/approve

**Pull request merged**
