### PR TITLE
terraform-rhcs-rosa: Add pre-merge job - running example

### PR DESCRIPTION
**Pull request by nirarg**

### CODE REVIEW

**Comment by nirarg** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-main-run-rosa-classic-public

**Comment by nirarg** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-main-run-rosa-classic-public

**Comment by nirarg** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-main-run-rosa-classic-public

**Comment by nirarg** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-main-run-rosa-classic-public

**Comment by AsherShoshan** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-main-run-rosa-classic-public

**Review by enriquebelarte — APPROVED** [review]

**Comment by nirarg** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-main-run-rosa-classic-public

**Comment by nirarg** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-main-rosa-classic-public

**Comment by enriquebelarte** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-main-run-rosa-classic-public

**Comment by amalykhi** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-main-rosa-classic-public

**Comment by nirarg** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-main-rosa-classic-public

**Comment by nirarg** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-main-rosa-classic-public

**Comment by nirarg** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-main-rosa-classic-public

**Comment by nirarg** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-main-rosa-classic-public-with-shared-vpc
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-main-rosa-classic-public

**Comment by nirarg** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-main-rosa-classic-public-with-shared-vpc

**Comment by nirarg** [comment]
/pj-rehearse pull-ci-terraform-redhat-terraform-rhcs-rosa-main-rosa-classic-public

**Pull request merged**
