### PR TITLE
Enable e2e sig-builds test for baremetal IPI

### PR DESCRIPTION
**Pull request by andfasano**
This PR re-adds the sig-builds tests, as they were excluded initially due the lack of:
* Mirrored test images
* Not trusted sef-signed certificate for the dev-scripts repository used to mirror test images

Requires https://github.com/openshift-metal3/dev-scripts/pull/1203
Requires https://github.com/openshift/origin/pull/26019 to support disconnected environments

### CODE REVIEW

**Comment by ardaguclu** [comment]
I think, there should be at least one disconnected job passing.

**Comment by andfasano** [comment]
> I think, there should be at least one disconnected job passing.

Good idea, let me try

**Pull request closed without merging**
