### PR TITLE
Gather rest client latency and error rate to be able to detect performance regressions

### PR DESCRIPTION
**Pull request by dgrisonnet**
Collect the latencies and error rates of the proxies in front of the apiserver to be able to detect regression from a particular network proxy. I can be either the load balancers, the services, or direct access via the pod.

The actual queries are based on https://github.com/openshift/cluster-kube-apiserver-operator/pull/1272 and look like the following if they were not one-lined:

rest client 99th percentile of request latency:
```
sum by(type) (
  histogram_quantile(0.99, sum(rate(
    label_replace(rest_client_request_duration_seconds_bucket{verb="GET",url=~"https?://api-int.*"},"type","load_balancer","","")[1h:30s]
  )) by (le,type))
  or
  histogram_quantile(0.99, sum(rate(
    label_replace(rest_client_request_duration_seconds_bucket{verb="GET",url!~"https?://(api-int|\\[::1\\]|127\\.0\\.0\\.1|localhost).*"},"type","service","","")[1h:30s]
  )) by (le,type))
  or
  histogram_quantile(0.99, sum(rate(
    label_replace(rest_client_request_duration_seconds_bucket{verb="GET",url=~"https?://(\\[::1\\]|127\\.0\\.0\\.1|localhost).*"},"type","pod","","")[1h:30s]
  )) by (le,type))
)
```

rest client average request latency:
```
sum by(type) (
  label_replace(
    sum(rate(rest_client_request_duration_seconds_sum{verb="GET",url=~"https?://api-int.*"}[1h:30s]))
    /
    sum(rate(rest_client_request_duration_seconds_count{verb="GET",url=~"https?://api-int.*"}[1h:30s]))
  ,"type","load_balancer","","")
  or
  label_replace(
    sum(rate(rest_client_request_duration_seconds_sum{verb="GET",url=~"https?://(api-int|\\[::1\\]|127\\.0\\.0\\.1|localhost).*"}[1h:30s]))
    /
    sum(rate(rest_client_request_duration_seconds_count{verb="GET",url=~"https?://(api-int|\\[::1\\]|127\\.0\\.0\\.1|localhost).*"}[1h:30s]))
  ,"type","service","","")
  or
  label_replace(
    sum(rate(rest_client_request_duration_seconds_sum{verb="GET",url=~"https?://(\\[::1\\]|127\\.0\\.0\\.1|localhost).*"}[1h:30s]))
    /
    sum(rate(rest_client_request_duration_seconds_count{verb="GET",url=~"https?://(\\[::1\\]|127\\.0\\.0\\.1|localhost).*"}[1h:30s]))
  ,"type","pod","","")
)
```

rest client error rate:
```
sum by(type) (
  label_replace(
    sum(rate(rest_client_requests_total{code="<error>",host=~"api-int.*"}[5m]))
    /
    sum(rate(rest_client_requests_total{host=~"api-int.*"}[5m]))
  ,"type","load_balancer","","")
  or
  label_replace(
    sum(rate(rest_client_requests_total{code="<error>",host!~"(api-int|\\[::1\\]|127\\.0\\.0\\.1|localhost).*"}[5m]))
    /
    sum(rate(rest_client_requests_total{host!~"(api-int|\\[::1\\]|127\\.0\\.0\\.1|localhost).*"}[5m]))
  ,"type","service","","")
  or
  label_replace(
    sum(rate(rest_client_requests_total{code="<error>",host=~"(\\[::1\\]|127\\.0\\.0\\.1|localhost).*"}[5m]))
    /
    sum(rate(rest_client_requests_total{host=~"(\\[::1\\]|127\\.0\\.0\\.1|localhost).*"}[5m]))
  ,"type","pod","","")
)
```

Note that all the graphs resulting from these queries will have 3 entries, one for each type of proxy.

### CODE REVIEW

**Comment by tkashem** [comment]
LGTM

giving an opportunity for @aojea to review

**Comment by aojea** [comment]
@dgrisonnet I ended changing the regex to avoid getting the host+path and get the host only
```
              sum(rate(
                label_replace(rest_client_request_duration_seconds_bucket{verb="GET",url=~"https?://api-int.*"},
                  "host","$1","url","https?://([^/\\s]+).*")[5m:30s]
                )) by (le,host,service,namespace,node)
```

**Comment by dgrisonnet** [comment]
It doesn't affect this PR since I am not relabeling the URL label to extract the host. Here, I am only exposing a higher-level type information which takes three values: load_balancer, service, and pod to avoid consuming too much resource

**Comment by aojea** [comment]
> It doesn't affect this PR since I am not relabeling the URL label to extract the host. Here, I am only exposing a higher-level type information which takes three values: load_balancer, service, and pod to avoid consuming too much resource

you are the expert here
/lgtm

**Pull request merged**
