### PR TITLE
OLS Moving hypershift-hosted cluster profile to observability one

### PR DESCRIPTION
**Pull request by JoaoFula**

### CODE REVIEW

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-service-main-e2e-ols-cluster

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-service-main-e2e-ols-cluster

**Comment by JoaoFula** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-service-main-e2e-ols-cluster

**Review by tisnik — COMMENTED** [review]
lgtm

**Comment by tisnik** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-service-main-e2e-ols-cluster

**Comment by tisnik** [comment]
/pj-rehearse pull-ci-openshift-lightspeed-service-main-e2e-ols-cluster

**Pull request merged**
