### PR TITLE
Move remaining repos to claim 4.12 clusters

### PR DESCRIPTION
**Pull request by Sandeepyadav93**

### CODE REVIEW

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-tempest pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl pull-ci-openstack-k8s-operators-install_yamls-main-install-yamls-deploy

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-tempest pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl pull-ci-openstack-k8s-operators-install_yamls-main-install-yamls-deploy

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl

**Comment by Sandeepyadav93** [comment]
/hold

Testing with a fix

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl

**Comment by Sandeepyadav93** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl

**Comment by viroel** [comment]
/lgtm

thanks @Sandeepyadav93

**Pull request merged**
