### PR TITLE
feat: switch profile to gcp-virtualization for ssp operator

### PR DESCRIPTION
**Pull request by ksimon1**
feat: switch profile to gcp-virtualization for ssp operator

### CODE REVIEW

**Review by jmguzik — APPROVED** [review]

**Comment by dominikholler** [comment]
What is the relation of this PR to https://github.com/openshift/release/pull/35726 ?

**Comment by ksimon1** [comment]
@jmguzik can you please review this PR?

**Review by 0xFelix — APPROVED** [review]
/lgtm

**Pull request merged**
