### PR TITLE
ci-operator/config: delete cosa buildroot image

### PR DESCRIPTION
**Pull request by jlebon**
We're no longer supporting a "buildroot" cosa image. So delete the
associated imagestream definitions and build configs and make CI tests
build from the vanilla `Dockerfile` instead.

See coreos/coreos-assembler#2550.

### CODE REVIEW

**Review by dustymabe — APPROVED** [review]
/lgtm

**Comment by jlebon** [comment]
OK, the error is:

```
mkdir: cannot create directory '/go': Permission denied
```

because it's trying to clone into `/go`. I think this is why https://github.com/coreos/coreos-assembler/blob/6bc6c015e35426433b9e0e40c8edeb9bdf0e2537/Dockerfile#L10 exists, which I cargo-culted from `Dockerfile.buildroot`, except that here it's trying to do this on the `fedora:35` image. I guess we could make it use the previous cosa image, but it'd be much nicer and less confusing to have it do a bona fide build from scratch.

Looking at https://steps.ci.openshift.org/ci-operator-reference, I don't see a way to customize the cloning path (the `--src-root` argument to `clonerefs`). @hongkailiu is that correct? Is there a way to clone to e.g. `/var/tmp` instead?

**Comment by cgwalters** [comment]
I think one thing to investigate here is dropping the `USER builder` from cosa by default.  We already ask people to provide a giant `podman ...` wrapper script, for which we could easily specify `--user builder`.

Actually there I think the path to pursue is having the cosa container work seamlessly via `toolbx`.

And we'd change our pipeline to default to `--user builder` too.

But anyways hmm...can't we also fix this by using the Fedora base image as a root?

**Comment by jlebon** [comment]
> But anyways hmm...can't we also fix this by using the Fedora base image as a root?

That'd be ideal, though I'm not sure how to configure this from the ci-operator config. I don't see a key exposed for controlling the user/SCC used in https://steps.ci.openshift.org/ci-operator-reference.

**Comment by cgwalters** [comment]
I mean can't we do:

```
build_root_image:
  name: fedora
  namespace: coreos
  tag: 35
```

Oh I see we're kind of trying to get away from hardcoding the fedora version in here.  So we can do something like this in cosa:

https://github.com/openshift/release/blob/9a98071c5e173771e28aff981101690cf724e181/ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.10__okd.yaml#L11
:arrow_right: 
https://github.com/openshift/ironic-image/blob/master/.ci-operator.yaml

**Comment by jlebon** [comment]
> Oh I see we're kind of trying to get away from hardcoding the fedora version in here. So we can do something like this in cosa:
> 
> https://github.com/openshift/release/blob/9a98071c5e173771e28aff981101690cf724e181/ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.10__okd.yaml#L11
> 
> arrow_right
> [openshift/ironic-image@`master`/.ci-operator.yaml](https://github.com/openshift/ironic-image/blob/master/.ci-operator.yaml?rgh-link-date=2021-11-18T20%3A49%3A16Z)

Yeah, was looking at that. But... don't we want Prow to build the `Dockerfile` itself? E.g. I don't want to re-implement what we do in the `Dockerfile` as part of a one-liner `binary_build_commands` like we had before. I'm probably missing something basic here since it seems like a simple enough setup.

**Comment by jlebon** [comment]
I guess one major hack is to ship a thin wrapper around the vanilla Fedora images that just does the `chmod` workaround and then use that as its `FROM` in the `Dockerfile`?

**Comment by jlebon** [comment]
Woohoo, looks like that worked! :tada: Wasn't able to shed the Fedora version hardcoding, but at least we don't have to define a separate buildroot image for deps, and we can reuse the canonical Dockerfile. Too bad the `.ci-operator.yaml` dropin when using `from_repository: true` doesn't support inline `Dockerfile` definition like we do here, which would've let us not hardcode the Fedora version here.

**Pull request merged**
