### PR TITLE
SPLAT-1007: capture OVA cache details to troubleshoot parsing failures

### PR DESCRIPTION
**Pull request by rvanderp3**
Adding OVA information gathering to troubleshoot https://github.com/openshift/installer/issues/7037

### CODE REVIEW

**Comment by rvanderp3** [comment]
/hold
/uncc @DennisPeriquet @dgoodwin 
uncc'ing until ready for review

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-vsphere-ovn-csi

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-vsphere-ovn-csi

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-zones

**Comment by rvanderp3** [comment]
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-aws-csi

**Comment by rvanderp3** [comment]
Interrupted `periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-zones` on the build cluster and confirmed that the debug information is recorded in the step logs.  Also confirmed that for a success, the OVA details aren't gathered. Additionally, a non-vSphere(periodic-ci-openshift-release-master-nightly-4.13-e2e-aws-csi ) job was interrupted to ensure that the collection logic is not invoked.

**Review by aravindhp — COMMENTED** [review]
/lgtm

Thanks for doing this, @rvanderp3

**Pull request closed without merging**
