### PR TITLE
chore: remove kepler references from jobs

### PR DESCRIPTION
**Pull request by vprashar2929**
This PR removes any occurrence of Kepler in power-monitoring operator jobs. This is done to separate between power-monitoring operator and Kepler-related jobs.

### CODE REVIEW

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-power-monitoring-operator-v1alpha1-power-monitoring-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-power-monitoring-operator-v1alpha1-power-monitoring-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-power-monitoring-operator-v1alpha1-power-monitoring-operator-e2e

**Comment by vprashar2929** [comment]
/pj-rehearse pull-ci-openshift-power-monitoring-power-monitoring-operator-v1alpha1-power-monitoring-operator-e2e

**Review by vimalk78 — APPROVED** [review]
/lgtm

**Pull request merged**
