### PR TITLE
OKD/SCOS vsphere test fixes

### PR DESCRIPTION
**Pull request by LorbusChris**
Supersedes https://github.com/openshift/release/pull/44258

/cc @jcpowermac

### CODE REVIEW

**Comment by LorbusChris** [comment]
/pj-rehearse periodic-ci-openshift-release-master-okd-scos-4.14-e2e-vsphere-ovn

**Comment by LorbusChris** [comment]
/pj-rehearse periodic-ci-openshift-release-master-okd-scos-4.14-e2e-vsphere-ovn

**Comment by LorbusChris** [comment]
although the rehearsal test didn't pass, the payload creation is successful with this, so this looks like it's working as intended

**Comment by jcpowermac** [comment]
@LorbusChris looks like `make ci-operator-config` needs to be run
otherwise LGTM
Thanks for fixing up my earlier pr

**Comment by LorbusChris** [comment]
Thanks! updated

**Comment by LorbusChris** [comment]
/assign @dgoodwin @sdodson 
for approval

**Pull request merged**
