### PR TITLE
DPTP-2270: Convert BUNDLE_IMAGE and INDEX_IMAGE to dependencies and use dependency_overrides for default values.

### PR DESCRIPTION
**Pull request by emilvberglind**
With [DPTP-2270](https://issues.redhat.com/browse/DPTP-2270) we're converting CVP steps that are using BUNDLE_IMAGE or INDEX_IMAGE as environment params to instead use dependencies and dependency_overrides.

### CODE REVIEW

**Comment by emilvberglind** [comment]
/assign @petr-muller 

I was a little unsure about this ticket, but I _think_ this is right?

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
