### PR TITLE
Add support for openstack_init

### PR DESCRIPTION
**Pull request by dprince**
Depends-On: https://github.com/openstack-k8s-operators/install_yamls/pull/963
Jira: [OSPRH-11298](https://issues.redhat.com//browse/OSPRH-11298)

### CODE REVIEW

**Comment by dprince** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-mariadb-operator-main-mariadb-operator-build-deploy

**Comment by dprince** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-mariadb-operator-main-mariadb-operator-build-deploy

**Comment by viroel** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-mariadb-operator-main-mariadb-operator-build-deploy

https://github.com/openshift/release/pull/59733/commits/37e4bc892703b9f2c6159240c66944a4704a2b04 is now merged

**Comment by viroel** [comment]
/lgtm

the code added is not affecting the current deploy process.

**Pull request merged**
