### PR TITLE
Rename csi-driver-projected-resource image

### PR DESCRIPTION
**Pull request by adambkaplan**
Rename the image for csi-driver-projected-resource to
csi-driver-shared-resource. This prepares us to rename the repository.
The original name will be retained for prior versions of OpenShift.

### CODE REVIEW

**Comment by adambkaplan** [comment]
/hold

We need agreement that the rename is something we want to proceed with, plus stage PRs for affected components.

**Comment by adambkaplan** [comment]
/assign @smarterclayton 

/cc @bparees 

Changes to image mirroring require Clayton approval. We are going to follow this PR up with others to rename the source repository

**Review by otaviof — APPROVED** [review]

**Comment by adambkaplan** [comment]
/close

Easier to refile this PR now that the repo has been renamed

**Pull request closed without merging**
