### PR TITLE
[Draft] verify OCPBUGS-34974 additional service endpoint

### PR DESCRIPTION
**Pull request by MayXuQQ**
https://issues.redhat.com/browse/OCPBUGS-34974

### CODE REVIEW

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.17-installer-rehearse-ibmcloud

**Comment by jianlinliu** [comment]
@MayXuQQ where is the pj-rehearse job to verify OCPBUGS-34974 ?

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.17-installer-rehearse-ibmcloud

**Comment by MayXuQQ** [comment]
> @MayXuQQ where is the pj-rehearse job to verify OCPBUGS-34974 ?

based on [1805175947838623744](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/53554/rehearse-53554-periodic-ci-openshift-verification-tests-master-installer-rehearse-4.17-installer-rehearse-ibmcloud/1805175947838623744)
I think the newly added service endpoint has not be supported in the installer.

**Comment by jianlinliu** [comment]
> I think the newly added service endpoint has not be supported in the installer.

Then what purpose for this PR ? 
OCPBUGS-34974 is saying they are supposed to be supported?

**Pull request closed without merging**
