### PR TITLE
[ibmcloud] fix step check-ibmcloud-destroy result is FAILURE

### PR DESCRIPTION
**Pull request by MayXuQQ**

### CODE REVIEW

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.15-installer-rehearse-ibmcloud-disconnected

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.15-installer-rehearse-ibmcloud

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.15-installer-rehearse-ibmcloud-disconnected

**Comment by MayXuQQ** [comment]
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.15-installer-rehearse-ibmcloud

**Comment by jianlinliu** [comment]
Just like what we discussed in slack, I do not think this PR will fix anything, but if you think it can resolve your issues, I will let it go.

**Pull request merged**
