### PR TITLE
Fix and align kubevirt-mce-conformance periodic

### PR DESCRIPTION
**Pull request by orenc1**
- Increase VM disk size from 32Gi to 64Gi
- Align the number of guest nodes of baremetalds to be the same as in aws (3, default).
- Add ssh-key so we can ssh into the nodes if needed for debug.

### CODE REVIEW

**Comment by orenc1** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-mce-conformance

**Comment by orenc1** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-mce-conformance periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-kubevirt-conformance

**Comment by orenc1** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-mce-conformance periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-kubevirt-conformance

**Comment by orenc1** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-mce-conformance periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-kubevirt-conformance

**Comment by orenc1** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-mce-conformance

**Comment by orenc1** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-mce-conformance periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-mce-baremetalds-conformance

**Comment by orenc1** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-mce-conformance

**Comment by orenc1** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-mce-conformance periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-mce-baremetalds-conformance

**Comment by orenc1** [comment]
**without live migration test in conformance:**
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-mce-conformance periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-mce-baremetalds-conformance

**Comment by orenc1** [comment]
adding ssh key
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-mce-conformance periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-mce-baremetalds-conformance

**Comment by orenc1** [comment]
previous run passed on both platform. now with live migration test:
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-mce-conformance periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-mce-baremetalds-conformance

**Comment by orenc1** [comment]
increasing disk size of VMs:
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-mce-conformance periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-mce-baremetalds-conformance

**Comment by orenc1** [comment]
aws succeeded on last run. running again to check for consistency:
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-mce-conformance periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-mce-baremetalds-conformance

**Comment by orenc1** [comment]
/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-mce-conformance periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-mce-baremetalds-conformance

**Comment by qinqon** [comment]
/lgtm
/approve
/hold

Wait for rehearsal results

**Comment by orenc1** [comment]
- 2 guest nodes on both platforms
- aws: 2 infra BM workers
- both: 64Gi disk

/pj-rehearse periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-mce-conformance periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-mce-baremetalds-conformance

**Review by davidvossel — COMMENTED** [review]
/lgtm
/approve

**Review by davidvossel — COMMENTED** [review]
/hold cancel
/pj-rehearse ack

I think this change likely improves the baremetalds lane. We're still seeing timeouts in the aws MCE lane, but we can follow up on that

**Comment by orenc1** [comment]
https://github.com/openshift/origin/pull/28319 will probably fix the aws lane as well.
/unhold

**Pull request merged**
