### PR TITLE
switch to aws-opendatahub cluster profile

### PR DESCRIPTION
**Pull request by riprasad**
Initial PR to test the new cluster profile

### CODE REVIEW

**Comment by riprasad** [comment]
cc @sutaakar

**Comment by riprasad** [comment]
/pj-rehearse pull-ci-opendatahub-io-codeflare-operator-main-e2e-odh-cfo

**Comment by riprasad** [comment]
/pj-rehearse pull-ci-opendatahub-io-codeflare-operator-main-e2e-odh-cfo

**Comment by riprasad** [comment]
/pj-rehearse pull-ci-opendatahub-io-codeflare-operator-main-e2e-odh-cfo

**Comment by riprasad** [comment]
/pj-rehearse pull-ci-opendatahub-io-codeflare-operator-main-e2e-odh-cfo

**Comment by riprasad** [comment]
/pj-rehearse pull-ci-opendatahub-io-codeflare-operator-main-e2e-odh-cfo

**Comment by riprasad** [comment]
/pj-rehearse pull-ci-opendatahub-io-codeflare-operator-main-e2e-odh-cfo

**Comment by riprasad** [comment]
/pj-rehearse pull-ci-opendatahub-io-codeflare-operator-main-e2e-odh-cfo

**Comment by riprasad** [comment]
/pj-rehearse pull-ci-opendatahub-io-codeflare-operator-main-e2e-odh-cfo

**Comment by riprasad** [comment]
/pj-rehearse pull-ci-opendatahub-io-codeflare-operator-main-e2e-odh-cfo

**Comment by riprasad** [comment]
/pj-rehearse pull-ci-opendatahub-io-codeflare-operator-main-e2e-odh-cfo

**Comment by riprasad** [comment]
/pj-rehearse pull-ci-opendatahub-io-codeflare-operator-main-e2e-odh-cfo

**Comment by riprasad** [comment]
/pj-rehearse pull-ci-opendatahub-io-codeflare-operator-main-e2e-odh-cfo

**Comment by riprasad** [comment]
/pj-rehearse pull-ci-opendatahub-io-codeflare-operator-main-e2e-odh-cfo

**Comment by sutaakar** [comment]
Holding the merge until December

**Comment by sutaakar** [comment]
@riprasad Thanks

**Pull request merged**
