### PR TITLE
Move glance and heat prow jobs over from 4.14 to 4.15 Hive cluster

### PR DESCRIPTION
**Pull request by bshewale**

### CODE REVIEW

**Comment by lewisdenny** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-glance-operator-main-glance-operator-build-deploy-kuttl pull-ci-openstack-k8s-operators-glance-operator-main-glance-operator-build-deploy-tempest pull-ci-openstack-k8s-operators-heat-operator-main-heat-operator-build-deploy-kuttl

**Comment by lewisdenny** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-glance-operator-main-glance-operator-build-deploy-kuttl pull-ci-openstack-k8s-operators-heat-operator-main-heat-operator-build-deploy-kuttl

**Comment by frenzyfriday** [comment]
/lgtm

the pj rehearse jobs look green

**Comment by viroel** [comment]
lgtm

**Review by lewisdenny — APPROVED** [review]
/unhold

**Pull request merged**
