### PR TITLE
Removing openshift-psap/special-resource-operator NOT openshift/special-resource-operator

### PR DESCRIPTION
**Pull request by zvonkok**
Removing openshift-psap/special-resource-operator NOT openshift/special-resource-operator

We only need CI for one instance not both

### CODE REVIEW

**Comment by dagrayvid** [comment]
@zvonkok are you sure you don't want to keep the unit tests and verify step? Or make the e2e tests postsubmit as I mentioned?

I prepared this in a branch just waiting for Eduardo to check it over
https://github.com/openshift/release/compare/master...dagrayvid:sro-upstream-e2e-postsubmit

**Review by ArangoGutierrez — APPROVED** [review]
I think this is good, we need think better how do we want to test this operator
/lgtm

**Comment by dagrayvid** [comment]
@zvonkok @ArangoGutierrez Okay, sounds good to me. We can proceed with this. This might need a rebase to fix the merge conflict?

**Pull request closed without merging**
