### PR TITLE
ci-operator/openshift/os: Remove unused c9s jobs

### PR DESCRIPTION
**Pull request by travier**
They will be included as part of the jobs running on master.

### CODE REVIEW

**Comment by travier** [comment]
CC @miabbott

**Comment by miabbott** [comment]
@travier Need to run `make update`

Ends up deleting `ci-operator/jobs/openshift/os/openshift-os-c9s-postsubmits.yaml` and `ci-operator/jobs/openshift/os/openshift-os-c9s-presubmits.yaml`

**Pull request merged**
