### PR TITLE
WIP: Run ARM periodic on ARM build farm node

### PR DESCRIPTION
**Pull request by deepsm007**
cc @nobody

### CODE REVIEW

**Comment by deepsm007** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-upgrade-aws-ovn-arm64

**Comment by deepsm007** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-upgrade-aws-ovn-arm64

**Comment by droslean** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-upgrade-aws-ovn-arm64

**Comment by deepsm007** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-upgrade-aws-ovn-arm64

**Comment by deepsm007** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-upgrade-aws-ovn-arm64

**Comment by deepsm007** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-upgrade-aws-ovn-arm64

**Comment by deepsm007** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-upgrade-aws-ovn-arm64

**Comment by droslean** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-upgrade-aws-ovn-arm64

**Comment by deepsm007** [comment]
/pj-rehearse periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-upgrade-aws-ovn-arm64

**Pull request closed without merging**
